### ISSUE TITLE
[Improvment] Sorting in private message list

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#10004]
### Description:

If you sort your private messages alphabetically, the sorting is not correct. Capital letters are ranked higher, as the following example shows.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1

### Steps to Reproduce:

1. Create two users: `aabc` and `Abc`
2. Start private conversations with them
3. Have a look in the left sidebar

### Expected behavior:

Ranking:
- aabc
- Abc

### Actual behavior:

Ranking:
- Abc
- aabc

Real world example in open.rocket.chat:

<img width="117" alt="rocket_chat_" src="https://user-images.githubusercontent.com/3596824/36962388-aa292788-204f-11e8-9be1-74462adbd35e.png">

**Comment by vishwakperera** [comment]
Can I get this issue assigned to me?

**Comment by JSzaszvari** [comment]
You don't assign issues in GitHub. Just let people know you are working on it and then submit a PR.

**Comment by vishwakperera** [comment]
okay! I'm gonna start working on this issue

**Comment by theorenck** [comment]
Hi @vishwakperera we gladly accept a PR for this one. Just check with @karlprieb if you need any help.

**Comment by JoseRenan** [comment]
I was seeing the code which sorts the DM list and discovered that it is sorted by mongo. When I searched about it, I discovered that mongo doesn't currently support case-insensitive sorting. So I was wondering if sorting it on the client side is a good option. What do you think?

**Comment by ggazzo** [comment]
we could improve this PR https://github.com/RocketChat/Rocket.Chat/pull/9959

and insert one more attribute `nameLowercase or blablabla` transforming username/name to lowercase... @karlprieb what do you think?
