### ISSUE TITLE
Users not able to save changes made to "My Account" [LDAP Setup]

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#10006]
Hello Devs.

Rocketchat 0.62.1. NodeJS 8.9.4. Oplog. Yes.

Since the upgrade to 0.62.1 users are not able anymore to save changes made to their personal settings under "My Account".  User are authorized via LDAP.  I'm saying this, because my other server does not have that problem and the only diff is the LDAP setup.

Any ideas on that?

thanks and cheers

**Comment by JSzaszvari** [comment]
Hello @himbeere 

This issue has already been logged and is currently being looked at. 

There is a potential work around in this post here that might help untill it's fixed - https://github.com/RocketChat/Rocket.Chat/issues/10001

I'm going to close this issue off so we don't end up with duplicates and keeps all correspondence around this patricular issue in one GitHub issue.

If I am mistaken and the post I have linked is not related to the issue you are having please respond here and I'll re open this for you. 

Have a super day! 

Regards
John

**Comment by JSzaszvari** [comment]
@rocket-cat close
