### ISSUE TITLE
[Email-notifications] Do not allow to flood user inbox with emails

### ISSUE THREAD

**Issue by 912d** [RocketChat/Rocket.Chat#10000]
### Description:
Currently every single message to offline users results in separate email. 
It's the same when writing message in room with offline users.

By pressing any single letter and enter several times, we can result in multiple several emails to offline user. It is a issue when offline user have non-gmail email inbox, for instance like me at work, which cannot display all emails in one row. 

I hate to say it, but there is potential of DDoS-like situation for internal company emails solution, because of this correlation 1 message -> 1 email.

### Steps to Reproduce:

1. Find offline user(s)
2. Send him several private messages or even worse, send messages in room he is watching. 

### Expected behavior:

After X messages have been sent, Rocket now will accumulate rest of the messages for Y time and will send it in one email. 
For instance, X = 5 messages, Y = 5 minutes

### Actual behavior:
Direct email is being sent for every message/mention to offline user(s).

EDIT: Yay, I'm number 10000 issue. This is great project!

**Comment by c0fe** [comment]
**Suggestion:** There should be one email (with ability to turn off entirely) that notifies the particular user that there are missed messages. It should not accumulate messages at all since more messages can come after that email has been sent.

**Comment by theorenck** [comment]
Hi @912d, we will evaluate you suggestion. But right now it is not on our top priorities. Thanks.

**Comment by maxvisser** [comment]
I suggest wait like 15 min before sending a mail and add every message missed as a digest.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #6079 as the sentiment is the same.

Cheers
Thomas
