### ISSUE TITLE
Why there is no option to set the status of a user

### ISSUE THREAD

**Issue by Azam53** [RocketChat/Rocket.Chat#10007]
### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3.

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
