### ISSUE TITLE
menu not show correctly in RTL languages

### ISSUE THREAD

**Issue by reza899** [RocketChat/Rocket.Chat#10018]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

### Expected behavior:

normally show menu of user in RTL

### Actual behavior:
in mobile size open correctly in bottom of the page. but in large size screen it opens behind and right side of screen that user cannot see. like screen before. (in browser and windows app tested)
![capture](https://user-images.githubusercontent.com/116783/37018999-c8c300d8-212b-11e8-9a71-e455a6c20c2f.PNG)

also, in my account section, user cannot save any changes.

**Comment by karlprieb** [comment]
Duplicated of #10068

**Comment by liorkesos** [comment]
Still not working for me with (version 3.11.0)
A nice workaroudn I found was to add the next snippet to the custom css ( a less field)
.rc-popover__content {
  left: calc(~"100% - 170px") !important;
}
