### ISSUE TITLE
[BUG] A user is alerted to all at-mentions of all users, regardless of username

### ISSUE THREAD

**Issue by ryjones** [RocketChat/Rocket.Chat#10014]
### Description:

A specific user of https://chat.hyperledger.org is alerted to every at-mention of every user in every channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): https://galaxy.ansible.com/RocketChat/Server/
* Number of Running Instances: 1
* DB Replicaset Oplog: mongodb://127.0.0.1:27017/rocketchat
* Node Version: v8.9.4
* mongoDB Version: mongodb-2.6.12-6.el7.x86_64

### Steps to Reproduce:

1. log on to chat.hyperledger.org
2. don't know.

### Expected behavior:

I expect users to only get alerts for at-mentions of their username.

### Actual behavior:

A specific user gets alerts for all at-mentions of any user in channels they are in.

### Relevant logs:

![clipboard - march 5 2018 1_51 pm](https://user-images.githubusercontent.com/466142/37000147-4dd933a6-2077-11e8-801e-331e4f2940fb.png)

**Comment by kaiiiiiiiii** [comment]
What are the users notification preferences?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by denyeart** [comment]
Hello, I am the user getting notifications whenever a user mentions another user (other than me).
I believe I have default Notification settings:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/20165681/37001979-35040b84-2096-11e8-9baa-1401f1a7e762.png">

**Comment by denyeart** [comment]
I've tried to correlate the notifications the last few hours.  It doesn't appear to be related to mentions actually, just some coincidences I think where I'm getting more notifications than expected (it just happened to be about the same number of mentions).  I will clear all the channel notifications, reset my notification settings, and see if the counts go back as expected.

**Comment by denyeart** [comment]
Ok, after resetting the counts and my notification settings, I watched the channel responses closely.  I received one notification on each of two channels, and in each case the channel had one @ mention to a user besides me.  So it appears the problem in the original Description above is still happening.

**Comment by denyeart** [comment]
Ok, I figured out the issue.  I had "ledger" as a highlight word, and after the latest rocket.chat server upgrade words like "Hyperledger" started triggering the extra notifications, whereas this never triggered notifications in prior rocket.chat versions.   There were also some @ mentions that I was getting notified on without the text "ledger" anywhere in it, which is what threw me off.  Perhaps there was some metadata in some of the posts with the text "ledger" in it?  Regardless, let's close the issue, and let the rocket.team team decide whether the new highlight word behavior is working as designed or not.
