### ISSUE TITLE
Outgoing Webhook of User Created not working

### ISSUE THREAD

**Issue by amonemian** [RocketChat/Rocket.Chat#10023]
Hi,

I am trying to set webhooks for my rocketchat, but I can trigger that for "User Created" mode. (all other types are ok).

I think it might be related to the "Target Room" setting, which I tried different states (@Admin, #general , ...) 
but unfortunately I could not get the webhook message.

Thank you for your help.
![image](https://user-images.githubusercontent.com/32976368/37023057-00767a74-213a-11e8-8485-1ad403ce6e01.png)

**Comment by theorenck** [comment]
Thanks @amonemian. @sampaiodiego can you confirm if it is a bug?

**Comment by sampaiodiego** [comment]
@amonemian did you set any URL?

since you didn't not filled our issue template, I do not know what are your expectations on this.

how did you expect this to work?

**Comment by graywolf336** [comment]
@amonemian did you create it with a custom script? Did you use a url for your webhook?

Hopefully you answer soon, otherwise we will have to close this due to inactivity. :(

**Comment by Hudell** [comment]
We have tested it here and everything seems to be working fine. As there has been no answer since the initial report, I'll be closing this issue now.
