### ISSUE TITLE
Cannot mention other users after newline in message

### ISSUE THREAD

**Issue by Jannibal** [RocketChat/Rocket.Chat#10021]
### Description:

Cannot mention other users after newline in message

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.8.1
* mongoDB Version: ?

### Steps to Reproduce:
1. Start writing message in channel
2. Add newline with ctrl-enter
3. Start writing @ to mention oser

### Expected behavior:
A list of users should be visible

### Actual behavior:
Nothing happens, the @ sign appears by itself without the user list appearing

**Comment by theorenck** [comment]
Hi @Jannibal, thanks report it to us. We actually could use a PR on this one :smiley: since it isn't on our top priorities right now. Cheers
