### ISSUE TITLE
No user status icon in chats list when username is long

### ISSUE THREAD

**Issue by hartois** [RocketChat/Rocket.Chat#10020]
### Description:
If the username is long and does not fit into the left panel, it overrides the status icon to the left of itself.

### Server Setup Information:
* Version of Rocket.Chat Server: 0.62.1
* Operating System: CentOS 7 x86_64
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3
* mongoDB Version: 2.6.12

### Steps to Reproduce:
Start chat with user that have long name.

### Expected behavior:
Truncated name and status icon of the left

### Actual behavior:
Status icon overrided

![scr9998](https://user-images.githubusercontent.com/11641656/37019640-206aeec4-212a-11e8-81d3-a54a4c111006.png)

**Comment by theorenck** [comment]
Hi @hartois, thanks for taking the time to report the problem to us. We are closing the issue since it will be fixed by #10019 PR.
