### ISSUE TITLE
New unread livechat no longer appear in the LiveChat queue

### ISSUE THREAD

**Issue by cmonjeau** [RocketChat/Rocket.Chat#10022]
### Description:

Since version 0.62.0, new unread livechat no longer appear in the LiveChat queue. Livechat notification is only visible when' Unread on top' is enabled and it is not queued.

In the 0.63-develop version, I don't observe that so I'm confused.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* mongoDB Version: 3.2

I'm using LDAP configuration.

### Steps to Reproduce:

1. Create a new livechat discussion

### Expected behavior:

Notification in Livechat queue

### Actual behavior:

Notification does not appear

### Screenshot with normal view

![rc_livechat_normal_view](https://user-images.githubusercontent.com/1289992/37022380-2466178a-2123-11e8-8ec8-d7f6046acf56.png)

### Screenshot with unread view

![rc_livechat_unread_view](https://user-images.githubusercontent.com/1289992/37022395-31e695d8-2123-11e8-871f-f096e5623935.png)

**Comment by theorenck** [comment]
Thanks @cmonjeau. @renatobecker can you check this out?

**Comment by renatobecker** [comment]
Hi @cmonjeau!
I'm testing this problem, can you give more details about it?
When you describe the `notification`, what exactly do you mean by `notification`?
I'm waiting for your feedback.

**Comment by cmonjeau** [comment]
Hi @renatobecker,

notification is the "unread" discussion that does not appear in the livechat queue.

**Comment by renatobecker** [comment]
Hi @cmonjeau,

Have you tried this in version `0.63.0`?
I'm running this version and the behavior is like below:

Option `Unread on top` is activated:
<img width="170" alt="screen shot 2018-03-28 at 11 05 17 am" src="https://user-images.githubusercontent.com/2067649/38034323-6944fa0e-3278-11e8-8021-bdb566b2a184.png">

The new unread Livechat appears both in the Livechat queue and in the unread groups:

![mar-28-2018 11-16-04](https://user-images.githubusercontent.com/2067649/38034938-a6c90ee6-3279-11e8-8642-590a629a3b19.gif)

**Comment by cmonjeau** [comment]
Hi @renatobecker ,

Yeah, I tried it with 0.63.0 version and there was no problem. The problem appears with the 0.62.0 on my production server (deployed with docker). I am in the 0.62.2 version and this problem persists.

**Comment by renatobecker** [comment]
Ok @cmonjeau.
A new release(0.63.0) is coming in a few days, so I suggest you to wait this new version.
This issue will probably not appears again, but if you notice that this behavior is occurring, please leave a new comment here.
Thanks.

**Comment by cmonjeau** [comment]
No problems. 

Thanks

**Comment by cmonjeau** [comment]
Hi @renatobecker,

I  just updated to version 0.63.1 and I have the same problem. I tried to run a new instance of rocket.chat with the same docker-compose.yml that my production server and all is ok with the livechat.

I don't understand why there is this problem since the version 0.62.0 on my production server. Maybe a side effect with multiple updates?

**Comment by cmonjeau** [comment]
![demo](https://user-images.githubusercontent.com/1289992/38549740-1094ba92-3cb5-11e8-99cb-8dc881bf2fec.gif)

**Comment by xvonabur** [comment]
Same problem with unread messages below livechats.

**Comment by renatobecker** [comment]
Hi @cmonjeau!
We have already identified what is happening in this case, it's related to a migration that is not working as expected.
I'm working on this to fix it as soon as possible, probably in the next version(0.65).
