### ISSUE TITLE
Web Channels

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat#10030]
I'd like to be able to create a channel that is essentially just a webview/iframe of a given page identified by a URL that would be specified by the channel creator in this dialog:

<img src="https://user-images.githubusercontent.com/4001792/37043173-0079ad4a-212e-11e8-9533-47c4b1867f71.png" width="300">

The idea is that instead of clicking a link to view a team wiki or google doc I'd like to be able to just click a channel identified by the page favicon and the html title. Perhaps these web channels could go in their own section:

![image](https://user-images.githubusercontent.com/4001792/37043345-68647d7c-212e-11e8-9b86-bc2baa23b4d8.png)

I realize that this is a wrinkle on this https://github.com/RocketChat/Rocket.Chat/issues/9668 but perhaps its one that would have more general appeal.

**Comment by bizzbyster** [comment]
It might also be interesting to allow developers to specify a "WebView" channel, which would load local webcontent specified by the administrator.

So, for instance, on Android a "Web Channel" would use Chrome Custom Tabs and point to a remote URL. And a "Webview Channel" would use Android Webview and load local content. This reflects the  "whentouse" logic in the Android documentation: https://developer.chrome.com/multidevice/android/customtabs#whentouse.

I believe IOS has similar options.

@rafaelks any thoughts on this feature?

**Comment by bizzbyster** [comment]
Note: This particular issue applies to the web client only. The Android and IOS client support will be handled via issues opened in those repos with a link to this one.

**Comment by bizzbyster** [comment]
A $180 bounty has been attached to this issue: https://www.bountysource.com/issues/55872934-web-channels. Thanks!

**Comment by TwizzyDizzy** [comment]
@MartinSchoeler: I'd recommend closing this. Rocket.Chat is (and probably also should not be) no browser.

Cheers
Thomas

**Comment by bizzbyster** [comment]
@TwizzyDizzy I have forked Android Rocket.chat and put a larger bounty on the full feature of "embedded tabbed browsing": https://github.com/WideChat/Rocket.Chat.Android/issues/1. I think we will find that browsing integrated into chat is a better user experience than having to switch between two apps but I can close this and we can wait until we have an implementation of rocket.chat+browsing to try out before discussing further. 

About the Electron Client, I think web channels using locally-served content (where that content is specified when you create the channel) work well in that architecture. But web channels loading content from a remote web URL are problematic in that case. Need to think through how to handle this for consistency across clients.

**Comment by theorenck** [comment]
Hi @bizzbyster this feature was not on our roadmap and we don't want to support it in our code base. I will close this issue but I would like to suggest you two possible alternatives. (1) Fork it as you've done with Android repo and implement the feature there; (2) Implement it as an Rocket.Chat App that will be released soon (more a mid-term solution). Either way, thank you for the suggestions.
