### ISSUE TITLE
Android Keyboard pop up when entering a channel

### ISSUE THREAD

**Issue by cr22rc** [RocketChat/Rocket.Chat#10037]
### Description:
Android Rocket.Chat 2.7.0 when I enter a channel the cursor is put in the message box. This seems to pop up the keyboard which is REALLY annoying since it then covers half the screen when all you want to do read messages first before you going to respond to anything.  Always have to dismiss it. 
This just started happening when our server go upgraded and I also was asked to download a new client.

BTW I have another user tell me they've seen this very behavior too so it's not just me. 
This is on the Hyperledger fabric project.

Android 7.0 

### Server Setup Information:

Version of Rocket.Chat Server: 0.62.0
    Operating System: Linux
    Deployment Method(snap/docker/tar/etc): https://galaxy.ansible.com/RocketChat/Server/
    Number of Running Instances: 1
    DB Replicaset Oplog: mongodb://127.0.0.1:27017/rocketchat
    Node Version: v8.9.4
    mongoDB Version: mongodb-2.6.12-6.el7.x86_64

### Steps to Reproduce:
just enter a channel

### Expected behavior:

see all the messages without any keyboard showing up.

### Actual behavior:
Cursor is in keyboard and half the screen is covered up :(

**Comment by cr22rc** [comment]
https://streamable.com/62nc2

**Comment by cr22rc** [comment]
I've seen someone on the an iPhone do this and that doesn't happen.

**Comment by itsthejoker** [comment]
Wouldn't this need to go in the Android repo?

**Comment by cr22rc** [comment]
Moved to:
https://github.com/RocketChat/Rocket.Chat.Android/issues/866

**Comment by lunitic** [comment]
Same thing happens if you using chrome in Android.  I would say reopen the issue.. It seems to be a general android thing.

**Comment by lunitic** [comment]
ping @cr22rc
