### ISSUE TITLE
text-overflow in sidebar does not work

### ISSUE THREAD

**Issue by DanielRuf** [RocketChat/Rocket.Chat#10039]
The `text-overflow: ellipsis` does not work due to the `display: flex` and the structure in general (which can be improved in many places and has many issues).

![bildschirmfoto 2018-03-07 um 08 59 40](https://user-images.githubusercontent.com/827205/37080866-e13757c4-21e7-11e8-8066-5e8157644b5a.png)

**Comment by DanielRuf** [comment]
Should be similar to this
![bildschirmfoto 2018-03-07 um 09 26 42](https://user-images.githubusercontent.com/827205/37081437-bbe2cdbc-21e9-11e8-88be-70ffd3baea9e.png)
:

**Comment by theorenck** [comment]
Thanks @DanielRuf. @karlprieb can you look into it and see how far can we go on this one?
