### ISSUE TITLE
Is it possible to unsubscribe room messages with real time API?

### ISSUE THREAD

**Issue by marc-bouvier** [RocketChat/Rocket.Chat#10031]
**Description**
Hi
I am currently using Rocket.Chat with real time API.
I can subscribe to room messages and notifications.

Is it possible to unsubscribe room message or room notifications?

**Server Setup information**

- Version of Rocket.Chat Server: 0.62
- Operating System: Any
- Deployment Method(snap/docker/tar/etc): Any
- Number of Running Instances: 1
- DB Replicaset Oplog: yes

**Steps to reproduce**
I subscribe to room messages by sending the following message to Rocket.Chat websocket

```
    {
        "msg": "sub",
        "id": "unique-id",
        "name": "stream-room-messages",
        "params":[
            "room-id",
            false
        ]
    }
```

Cannot find a way to unsubscribe or "unlisten" this stream.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by marc-bouvier** [comment]
Hi,
thank you for the feedback. I made this issue a feature request.
