### ISSUE TITLE
Option-Delete doesn't doesn't delete any characters in Firefox

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#1003]
Normally, <kbd>option</kbd> + <kbd>Delete</kbd> will delete entire words. In Firefox the cursor merely moves. It works as expected in Chrome and in the Electron app for me.

Here's a gif of what I'm seeing when I hit <kbd>option</kbd> + <kbd>Delete</kbd>
![delete](https://cloud.githubusercontent.com/assets/498744/10290935/f90b5d4a-6b74-11e5-9721-05fc7294f3e0.gif)

**Comment by zarvox** [comment]
Similar issue with Ctrl-Delete and Ctrl-Backspace on Firefox on Linux - the cursor moves by a word in the appropriate direction, but doesn't delete the word.

**Comment by gmsecrieru** [comment]
Fixed by #1049
