### ISSUE TITLE
Internal Server Error when changing user settings

### ISSUE THREAD

**Issue by michaelkollmann** [RocketChat/Rocket.Chat#10043]
### Description:

When saving any changes to my profile (e.g. client language) Rocket Chat displays an "Internal server error". I can't save any changes. Some of the users on my server are affected but not all of them. 
We only installed Rocket.Chat two days ago. I think we started at 0.62.0 and after the first night it upgraded to 0.62.1. Rebooting the whole linux server didn't help.

When adding a new user I still face the same error

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu Server 
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: unkown
* Node Version: v8.8.1
* mongoDB Version: unkown

### Steps to Reproduce:

1. Open profile settings
2. Change the client language from English to German

### Expected behavior:

I expect to be able to save changes without any issues

### Actual behavior:

I am not able to change any profile settings

### Relevant logs:
> [34mI20180307-11:51:04.894(1) Exception while invoking method 'saveUserPreferences' MongoError: cannot use the part (settings of settings.preferences.newRoomNotification) to traverse the element ({settings: null})     at Function.MongoError.create (/snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /snap/rocketchat-server/1232/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by rocketchatdev** [comment]
same happening at my end

**Comment by ektoplasmo** [comment]
Same issue here after updating to 0.62.1 , changing User to Admin didnt change anything either

**Comment by DFJizzle** [comment]
We are having same issue, although the exception it's throwing is a little different:

`Exception while invoking method 'saveUserPreferences' Error: Match error: Expected boolean, got string in field useEmojis     at check (/snap/rocketchat-server/1232/programs/server/packages/check.js:62:15)     at MethodInvocation.saveUserPreferences (/snap/rocketchat-server/1232/programs/server/app/app.js:9982:5)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_lib.js:2158:28)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at Promise (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:754:85  
[34mI20180309-16:11:36.986(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20180309-16:11:36.987(0) undefined undefined `

**Comment by JoeatMJ** [comment]
I am having the same problem. Same info as the first post. Same config with SNAP. Any updates?

**Comment by hereiamji** [comment]
Hello 
on the latest 0.65.1 I have a problem with  customFields. I've added some and while trying to input some info in the custom fields catching an error:

```
0|rocketch | Exception while invoking method 'saveUserProfile' MongoError: Cannot create field 'Phone' in element {customFields: null}
0|rocketch |     at Function.MongoError.create (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
0|rocketch |     at toError (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)
0|rocketch |     at /var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67
0|rocketch |     at /var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
0|rocketch |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|rocketch |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

```

Has anyone solved this problem?
