### ISSUE TITLE
Add feature to change channel image

### ISSUE THREAD

**Issue by Otiel** [RocketChat/Rocket.Chat#10046]
It would be nice to be able to change the image of a channel (public or private) displayed on the left sidebar.

Sometimes the generated images are too much alike, like shown below:

![image](https://user-images.githubusercontent.com/3851902/37103717-27176b92-222b-11e8-898f-8b87758636e6.png)

**Comment by MartinSchoeler** [comment]
This feature is already at our road map and it should be released relatively soon. Thanks for the feedback!

**Comment by Spardason** [comment]
Any update as of now ?

**Comment by phiomet** [comment]
Any News about this?

**Comment by RussianJohny** [comment]
### When ??? ???

**Comment by Tayyaba03** [comment]
@MartinSchoeler Any update on this?

**Comment by Gaspar1992** [comment]
@MartinSchoeler Please!!! I need it!

**Comment by Otiel** [comment]
Bothering everyone with such comments isn't going to change anything. Use GitHub reactions 👍  is enough, or start a PR if you want to contribute.

**Comment by GoetheG** [comment]
This post should be merged with https://github.com/RocketChat/Rocket.Chat/issues/3582
