### ISSUE TITLE
Chatbot GUI component support

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat#10045]
Chatbot conversations support more than just plain text to improve user experience. For example, here's a list of the "conversation components" that Facebook Messenger supports:

https://developers.facebook.com/docs/messenger-platform/introduction/conversation-components

And also a graphic that shows the range of chatbot interface elements from conversation to GUI.

![image](https://user-images.githubusercontent.com/4001792/37095844-031eed6e-21e5-11e8-987d-4a2a1cd4a73e.png)

I realize that since this is largely client-side feature it would have to go into all three supported Rocket.chat clients (Web, IOS, and Android) but since this seems like a big topic I am creating it here in the hopes of starting a discussion on the topic.

**Comment by jaytat0** [comment]
@graywolf336 @timkinnane is this a good candidate for a rocketlet?

**Comment by graywolf336** [comment]
@jaytat0 Yes. However, before the Rocket.Chat Apps (previously Rocketlets) can make usage of them, the Rocket.Chat platform itself has to have support for them. So, we would need to implement them in the Rocket.Chat code and then ensure the Rocket.Chat Apps support them.

**Comment by SeaLife** [comment]
Hello, would also like something like this (source, Discord) in Rocket.Chat to make our System Bot creating better notifications. :)

https://imgur.com/a/joGj6vP

Its a bit hard to get the right message out of 14 messages of one user. (its getting complicating to read). These little boxes makes it much better to read. :)

Regards
SeaLife

**Comment by SeaLife** [comment]
Is this implemented @bizzbyster ?
