### ISSUE TITLE
Uploads with multiple digits in filename

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1004]
So it appears when a filename contains multiple digits like a phone number.  This is the output:

![image](https://cloud.githubusercontent.com/assets/51996/10291903/db188298-6b71-11e5-80ce-c56c131d4f34.png)

**Comment by gmsecrieru** [comment]
Related to #810

**Comment by gmsecrieru** [comment]
I will close this one as the problem is not related with the uploads but with autolinked.
