### ISSUE TITLE
Error with sharp module after upgrading to 0.62.1

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#10041]
### Description:

Hi,

I got an error while upgrading from 0.61.1 to 0.62.1 about sharp module. Is the version embedded in the tar compatible with the node version recommanded by RocketChat ?

"Rocket.Chat 0.60 and higher needs version 8.9.3 LTS of Node.js to work."

Cheers

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 3
* DB Replicaset Oplog: enabled
* Node Version: 8.9.3
* mongoDB Version: 3.2.12

### Steps to Reproduce:

1. tar deployment
2. npm install
3. restart rocketchat instance

### Relevant logs:

Mar  7 10:07:34 messi-ida03 nodejs-rocketchat0[27561]: Exception in callback of async function: Error: The module '/var/www/Rocket.Chat-0.62.1/programs/server/npm/node_modules/sharp/build/Release/sharp.node'
Mar  7 10:07:34 messi-ida03 nodejs-rocketchat0[27561]: was compiled against a different Node.js version using
Mar  7 10:07:34 messi-ida03 nodejs-rocketchat0[27561]: NODE_MODULE_VERSION 46. This version of Node.js requires
Mar  7 10:07:34 messi-ida03 nodejs-rocketchat0[27561]: NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
Mar  7 10:07:34 messi-ida03 nodejs-rocketchat0[27561]: the module (for instance, using `npm rebuild` or `npm install`).

**Comment by MartinSchoeler** [comment]
@magicbelette have you already tried a `npm install`?

**Comment by charli3cta** [comment]
I have the same problem with node version: 8.9.4. I also tried with node version 8.10 and I get the same result.

**Comment by magicbelette** [comment]
Yes, I tried `npm install` as suggested by logs, with no luck.

I've just found the solution by deleting the node_modules folder under `programs/server/` before launching `npm install`.

Thank you for your concern ;)
