### ISSUE TITLE
segmentation fault after editing rocket.chat.service 

### ISSUE THREAD

**Issue by niekverw** [RocketChat/Rocket.Chat#10048]
### Server Setup Information:

* Operating System:  VPS, ubuntu 16
* Deployment Method(snap/docker/tar/etc):  DPlatform
* Number of Running Instances: 1
* Node Version: v8.10.0

### Steps to Reproduce:

editted ROOT_URL /etc/systemd/system/rocket.chat.service to test something.  and changed it back again. I restarted services by systemctl daemon-reload and systemctl restart rocket.chat.service

systemctl status rocket.chat.service returns `rocess: 1088 ExecStart=/usr/bin/node main.js (code=killed, signal=SEGV)`

### Expected behavior:

That it the server would start again 

### Actual behavior:

```

root@comp:/var/www/rocketchat# export MONGO_URL=mongodb://127.0.0.1:27017/rocketchat
root@ comp:/var/www/rocketchat# export ROOT_URL=http://xxx.xxx.x.xx:3004/
root@ comp:/var/www/rocketchat# /usr/bin/node main.js
Will load cache for users
3 records load from users
Will load cache for rocketchat_room
2 records load from rocketchat_room
Will load cache for rocketchat_subscription
4 records load from rocketchat_subscription
Will load cache for rocketchat_settings
628 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Segmentation fault
```

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
