### ISSUE TITLE
Hiding roles prevents being able to save user preferences 

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#10049]
### Description:

Hiding Roles prevents any user from being able to save preferences.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1

### Steps to Reproduce:

1. Administration->Account->Default User Preferences->Hide Roles = true
2. Have any user go to preferences and try to save.
3. Frustration.. no save.

### Expected behavior:

Should save

### Actual behavior:

Doesn't save

**Comment by Hudell** [comment]
The setting that causes the issue is actually:
Administration->Layout->User Interface->Display Roles = false

**Comment by ryjones** [comment]
@Hudell that is the correct UI path.

**Comment by Sx3** [comment]
helpful
