### ISSUE TITLE
[Feature Request] Ability to reorder channels

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat#10053]
### Description:
Ability to reorder or rearrange channels in the sidebar by drag and drop.

**Comment by theorenck** [comment]
Hi @ubarsaiyan we understand that it would be very cool to have this feature but it is not a priority for us now. Thanks for the suggestion.

**Comment by mcclureski** [comment]
And why not? It's the small things like this that make Discord really good and it would be a useful feature to bring to Rocket.Chat

**Comment by localguru** [comment]
Even though a feature request, which is not nonsensical, is currently not at the top of the priority list (which I understand), I think that one should not necessarily close the ticket.

@mcclureski Just post it at https://forums.rocket.chat/c/feature-requests
