### ISSUE TITLE
Limit the number of reactions

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat#10052]
### Description:
Limit the number of unique reactions available like that in Facebook's Messenger. Having the whole emojiset as reactions dilutes their use and makes it cumbersome to find the correct emoji. Anyways, we only have 5-6 basic reaction to anything ( happy, sad, laughing, angry, surprised, etc).

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @ubarsaiyan,

I am pretty sure that this is something that's not going to happen. If you still find this to be something you find extremely important, please first discuss this with the community over in the forums: https://forums.rocket.chat.

Cheers
Thomas
