### ISSUE TITLE
cant create room name or make username in arabic or rtl language 

### ISSUE THREAD

**Issue by fazilboudjellal93** [RocketChat/Rocket.Chat#10069]
cant rename an account or create a room in arabic 
![screenshot-open rocket chat-2018 03 09-05-02-17](https://user-images.githubusercontent.com/16228448/37189965-5705434c-2357-11e8-81a2-bed619036179.png)

**Comment by theorenck** [comment]
Hi @fifou17 thank you for report it to us, can you give us more context on the problem?

**Comment by fifou17** [comment]
@theorenck when i try to create an account using a username and name in arabic its gives me error and it doesnt show up and same for rooms name

**Comment by tassoevan** [comment]
As a workaround, you can go to `Administration` > `General` > `UTF8` and change `UTF8 Names Validation` to `[0-9a-zA-Z\u0600-\u06FF-_.]+`. However, there are known issues that we are trying to fix/improve now, like URLs and avatars.

**Comment by tassoevan** [comment]
Related to #1566.

**Comment by gabriellsh** [comment]
This has been fixed. If you still face this issue, please reopen.
