### ISSUE TITLE
rocketchat crash with nodejs-8.10.0

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#10060]
### Description:

Just updated to nodejs 8.10.0. Rocketchat 0.62.1 crashes immediately with segmenation fault.

```
rocketchat@pages /opt/rocketchat $ /usr/bin/node -- main.js
Will load cache for users
3 records load from users
Will load cache for rocketchat_room
4 records load from rocketchat_room
Will load cache for rocketchat_subscription
6 records load from rocketchat_subscription
Will load cache for rocketchat_settings
628 records load from rocketchat_settings
Updating process.env.MAIL_URL
Segmentation fault
rocketchat@pages /opt/rocketchat $ 
```

Switching back to nodejs 8.9.4 solves the issue.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.62.1
* Operating System:  Gentoo Linux
* Deployment Method(snap/docker/tar/etc):  tar
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version:  8.10.0
* mongoDB Version: 3.6.3

### Steps to Reproduce:

1. Stop Rocketchat
2. Update Nodejs to 8.10.0
3. Start Rocketchat

### Expected behavior:

Rocketchat should run.

### Actual behavior:

Rocketchat crashed

### Relevant logs:

No Server logs. Nodejs process crashes and is not able to create log entries.

**Comment by JSzaszvari** [comment]
Hi @himbeere 

At the moment Rocket.Chat only supports 8.9.4. 

8.10.0 would be considered a unsupported version for the time being. 

I'm sure this will change in the near future as 8.10.0 is the current LTS release. 

The team has only recently moved to the 8.x release of NodeJS and with a project so large there are a lot of factors to be taken into account when changing versions like waiting for the projects many dependencies to support the newer releases as well. 

I'll take a look at why it might be crashing but at the moment this would be considered a non issue.

**Comment by JSzaszvari** [comment]
@rocket-cat close 

I'm going to close this issue for the time being  . The dev team is aware of the issue as there's been a few other posts but for the moment you will need to stick with the supported version until they get a chance to update it. 

If you feel this issue should remain open then please respond back to me here and I'll re open it for you. 

We appreciate you taking the time to report the issue to the team. 

Thanks :)

**Comment by himbeere** [comment]
Ok, thanks. Good to know.

**Comment by antoine-roux** [comment]
Hello to you dev' team,

Please, fix the node version in the Docker image:
```docker run --rm rocket.chat:0.62 node -v
v8.10.0```
The image can not be used.

Thanks to you :)
Antoine

**Comment by himbeere** [comment]
Oh. and maybe as a site note. Ubuntu nodejs.8.x ppa delivers 0.8.10 as default right now.

https://www.ubuntuupdates.org/ppa/nodejs_8.x

**Comment by tboerger** [comment]
You are seriously kidding, right? The official Rocket.Chat docker images already got 8.10 and the available 8.x repositories for Ubuntu Xenial also provide only 8.10... So how should somebody keep Rocket.Chat running in that situation?

**Comment by crrodriguez** [comment]
So..who has the nodejs bug report number handy ? nodejs should not crash at all..

**Comment by tboerger** [comment]
And there is not any useable tag available at https://hub.docker.com/r/library/node/tags/ :(

**Comment by jnweiger** [comment]
Would that one work?
https://deb.nodesource.com/node_8.x/pool/main/n/nodejs/nodejs_8.9.4-1nodesource1_amd64.deb

**Comment by tboerger** [comment]
@jnweiger but I can't get it installed with the deb repo on xenial.

**Comment by himbeere** [comment]
@crrodriguez i built nodejs with debug option and get this:

```
rocketchat@pages /opt/rocketchat $ node main.js 


#
# Fatal error in ../deps/v8/src/parsing/parser.cc, line 542
# Debug check failed: ThreadId::Current().Equals( outer_scope_info->GetIsolate()->thread_id()).
#
Illegal instruction
rocketchat@pages /opt/rocketchat $
```

This should help I guess?

**Comment by himbeere** [comment]
@crrodriguez And here is the nodejs issue: https://github.com/nodejs/node/issues/19274

**Comment by tboerger** [comment]
Maybe I should just install the debug package, that have not been updated.

**Comment by hashseed** [comment]
I was wrong. This rather looks like the parser is running on a thread it is not supposed to be on.

**Comment by tboerger** [comment]
https://github.com/dockhippie/rocketchat/blob/master/Dockerfile#L34-L36 Not really nice, but at least it should hopefully fix the issue for now...

**Comment by benjamn** [comment]
We (@abernix and I) believe we've identified the problem, and have recommended a solution to Node/V8: https://github.com/nodejs/node/issues/19274#issuecomment-374298732

**Comment by si458** [comment]
has this issue been fixed at all without using an old version of node?
the latest stable node is now 8.11.1 and its still generating this core dump error

**Comment by himbeere** [comment]
rumor has it, the fix will be in nodejs-8.11.2

**Comment by Nono-m0le** [comment]
Hi There,

NodeJS 8.11.4 seems to be out. Did anyone tried out and could tell me if if worth the upgrade ?
The manual installation (at least for ubuntu on https://rocket.chat/docs/installation/manual-installation/ubuntu/  ) still refer to v. 8.9.3
I'm experiencing the seg Fault with : 
$ lsb_release -a
**Ubuntu 18.04.1 LTS**
$ dpkg -l
**nodejs                                8.10.0~dfsg-2ubuntu0.2                                amd64**
$ node --version
**v8.9.3**
=> Rocket.Chat v0.69.1

$ n --lts
**8.11.4**

**Comment by abernix** [comment]
The segmentation fault demonstrated here has been fixed since Node.js 8.11.2.  If you want to avoid the segmentation fault, you should certainly upgrade!

**Comment by Nono-m0le** [comment]
Thanks @abernix,

Actually I give it a try before posting and the LTS version (8.11.4) doesn't work and throw me an seg fault directly (no need to wait a -always different- amount of time before the crash).
