### ISSUE TITLE
Menu in RTL isnt in place 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#10068]
### Server Setup Information:

* Version of Rocket.Chat Server: 63
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

![screenshot-open rocket chat-2018 03 09-04-53-00](https://user-images.githubusercontent.com/16228448/37189706-fcaf6efa-2355-11e8-9e25-3ed7b36fda57.png)

**Comment by TwizzyDizzy** [comment]
I'm not very familiar with RTL UIs, but to me that looks pretty much what I would expect. Can you elaborate on what "is not in place" means to you? :)

Cheers & Thanks
Thomas

**Comment by idanielblake** [comment]
Hello
Is there any workaround for this bug? with CSS maybe?
thanks

**Comment by TwizzyDizzy** [comment]
Hi @idanielblake,

no offense intended, but: can we first agree on what's the actual bug here? ;)

Cheers
Thomas

**Comment by idanielblake** [comment]
When I click on my profile picture on right above corner (in RTL RC) menu opens outside of the screen. Just like the picture. sorry for my eng.

**Comment by TwizzyDizzy** [comment]
Ah! I though this some censoring for privacy. OK. Then I get it... thanks!

Cheers
Thomas

**Comment by idanielblake** [comment]
Now is there any fix with some css? I updated our Rocketchat and It's broken somehow. Can you help? Thank you so much

**Comment by efih** [comment]
same issue here

**Comment by idanielblake** [comment]
I tried some CSS but I'm not a expert. rtl direction made it better but messed up other menus.
.rc-popover__content {
//right:30px !important;
//min-width:200px !important;
//max-width:300px !important;
//transform: translateX(-50%);
direction: ltr;
  //transform: translateX(-10%);
  //animation: unset !important;
}
.rc-popover {
 //direction: ltr;
  //width: 90% !important;
}

**Comment by theorenck** [comment]
Thanks for inform the problem to us. @karlprieb, can you evaluate @idanielblake workaround?

**Comment by karlprieb** [comment]
We need to fix the calc that we use to set the position when an user open the popover. It need to be done using JS. I can do that on the 0.64 release

**Comment by fifou17** [comment]
thank you @karlprieb @theorenck

**Comment by sparse91** [comment]
This bug is come back in v3.13.3.

**Comment by ArielBenAharon** [comment]
Same here - reproducing the bug in v3.11.0
