### ISSUE TITLE
MacOS Desktop Client Doesn't Show Server Text Box On First Launch When Installed On A MacOS Parallels Virtual Machine 

### ISSUE THREAD

**Issue by FC-Jason** [RocketChat/Rocket.Chat#10066]
### Description:

I'm running MacOS 10.12.6 in a Parallels 13.3.0 Virtual Machine on an iMac. I downloaded and Installed the rocketchat-2.10.5.pkg installer for MacOS.  After installation, I opened the RocketChat app and parts of the Application Window are white, as if they aren't loading.  I cannot access the Server Text box or any Login Information (See Screen Shot)

![screen shot 2018-03-08 at 2 18 20 pm](https://user-images.githubusercontent.com/25483047/37174661-cc594934-22dc-11e8-8b64-79e520a6bb62.png)

Parallels virtual machine is set to 2 Processors, 3072 MB of Memory, 128 MB of Video Memory.  This looks similar to something that happened when I installed Google Chrome. I had to go and turn off Hardware Acceleration in Chrome Settings to get it to render pages correctly without blank white spots.

### Server Setup Information:

* Version of Rocket.Chat Server: N/A Can't see text box to connect
* Operating System: MacOS 10.12.6
* Deployment Method(snap/docker/tar/etc): pkg
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. Make a Parallels Virtual Machine of MacOS Sierra 10.12.6. I'm using Parallels 13.3.0 on MacOS High Sierra 10.13.4, but I suspect any version and host OS will reproduce. 
2. Download the pkg installer of RocketChat for MacOS.
3. Install this pkg.
4. Launch RocketChat and you won't be able to see the login information. That section of the RocketChat window will be white.

### Expected behavior:

I expect to see the Text Box where you can enter your Server address

### Actual behavior:

I see a white block across the middle of the RocketChat window preventing me from seeing the Server Address Text Box. (See Screenshot Above)

### Relevant logs:
Can't figure out how to get these from the Desktop Client

**Comment by kaiiiiiiiii** [comment]
There’s an extra repository for the electron desktop application :) Defo the better place to open an issue.

https://github.com/RocketChat/Rocket.Chat.Electron

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
