### ISSUE TITLE
Long press on a message causes aplication lockup Android 5.1.1. Note 4 910C

### ISSUE THREAD

**Issue by dcavni** [RocketChat/Rocket.Chat#1006]
On Android app or in Chrome for Android  if i long press on a message i get a menu options (Delete Message, Report abuse, Cancel), but there is no way to get rid of this menu. Only force closing of app (or tab in Chrome). Helps. On computer everything works fine. Does this happen only to me or is there someone else with this problem?
##

**Comment by marceloschmidt** [comment]
It works for me on Android 5.0 LG G3 phone.
