### ISSUE TITLE
liveStreamTab.css:40:5: variable '--rc-color-primary-lightest' and '--rc-color-primary-dark'  is undefined and used without a fall

### ISSUE THREAD

**Issue by szluohua** [RocketChat/Rocket.Chat#10070]
### Description:
There was an error when I built the RocketChat environment locally. What should I do?

postcss-custom-properties: /home/luo/github/Rocket.Chat/packages/rocketchat-livestream/client/styles/liveStreamTab.css:19:5: variable '--rc-color-primary-lightest' is undefined and used without a fallbackpostcss-custom-properties: /home/luo/github/Rocket.Chat/packages/rocketchat-livestream/client/styles/liveStreamTab.css:40:5: variable '--rc-color-primary-dark' is undefined and used without a fall
![2018-03-09 14-56-41](https://user-images.githubusercontent.com/18567056/37194745-a59a349c-23aa-11e8-944f-748f1f924107.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63
* Operating System: 
* Deployment Method(snap/docker/tar/etc): localhost
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version:

**Comment by gdelavald** [comment]
@szluohua Hey, this is a small oversight we had when renaming some of the color variables, it shouldn't break anything but it is being fixed anyway in the phase 2 of the Livestream feature.

**Comment by szluohua** [comment]
ok,thank you
