### ISSUE TITLE
[BUG] "Highlight Words" doesn't work with more than one word

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10077]
### Description:

Feature **Highlight Words** doesn't work with more than one word for me.

#### Works:

![screen shot 2018-03-09 at 11 36 24](https://user-images.githubusercontent.com/551004/37212638-59dcb6ae-238e-11e8-8c63-3cd98e4bc577.png)

#### Doesn't work

![screen shot 2018-03-09 at 11 38 29](https://user-images.githubusercontent.com/551004/37212666-6bbad360-238e-11e8-91c5-4cc2e236b7da.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Linux

### Steps to Reproduce:

1. Setup "Highlight Words" with **iOS, Android**
2. Wait for a message with those words

### Expected behavior:

Server should notify you with a badge and a push notification.

### Actual behavior:

Server does not notify you and don't add the badge.

**Comment by nemaniarjun** [comment]
I would like to look into this! Please assign me :)

**Comment by nemaniarjun** [comment]
Can confirm, that this is an issue. Was able to reproduce it on 0.63.0-develop (9fbf1ad78666bceddf60919ae4a19fa3be3c9ce0)

**Comment by nemaniarjun** [comment]
Separating by new line does work!

**Comment by nemaniarjun** [comment]
@rafaelks Do we want it to separate by commas or by newlines. The help text says commas, but code is separating via newlines.
