### ISSUE TITLE
Apple app has issues

### ISSUE THREAD

**Issue by muhv7** [RocketChat/Rocket.Chat#10079]
### Description:

iphone app doesn't load channels correctly after 0.62 update

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): Snap 
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

Update
Use iPhone app
Blank screen

### Expected behavior:

Load normally?

### Actual behavior:

Blank screen on channels

![f6eed6b5-847e-4715-bcc5-e4c48ff3fcf2](https://user-images.githubusercontent.com/34287392/37216124-af7965d8-23c2-11e8-8f93-1d2c04872c58.png)

**Comment by JSzaszvari** [comment]
Hi @muhv7 

Please post this issue over in the repository for the iOS Application which can be found here

https://github.com/RocketChat/Rocket.Chat.iOS

This repository is for the server component. 

Thanks mate

**Comment by JSzaszvari** [comment]
@rocket-cat close
