### ISSUE TITLE
I want to use http2 with haproxy and don't work

### ISSUE THREAD

**Issue by dmoldovan123** [RocketChat/Rocket.Chat#10073]
* Version of Rocket.Chat Server: 0.61.0
* Operating System: ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 10
* DB Replicaset Oplog: yes
* Node Version: v8.9.3
* mongoDB Version: 

Config haproxy to initiate http2 with ssl and not working.

With plugin installed in chrome browser i see i have activate http2 but i don't see rocketchat interfaces.

**Comment by TwizzyDizzy** [comment]
Does haproxy try to speak HTTP/2 to the backend (Rocket.Chat), too, or do you speak HTTP/1.1 there?

Cheers
Thomas

**Comment by dmoldovan123** [comment]
http2 bidirectional.

**Comment by theorenck** [comment]
@dmoldovan123 we're sorry for your struggle. We actually don't support HTTP2 and we probably still don't in the near future.
