### ISSUE TITLE
Chatbot subscription support

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat#10085]
It would be nice if a user could subscribe to various chatbots on demand, and communicate with the bot through direct messaging only, instead of prepending '@botname' or 'bot'.  This kind of bot would not be available in the other channels, but only through direct messaging.  I think that would be a very intuitive way to interact with the bot for non technical users. 

Perhaps the admin subscribes, configures, and makes various chatbots available, at which point the user can choose to subscribe if interested.

Facebook messenger currently offers this kind of chatbot integration.

**Comment by theorenck** [comment]
@timkinnane what are you thoughts on the subject?

**Comment by marceloschmidt** [comment]
I believe we need a way of showing which apps / bots are available to the user. But currently, it's already possible for bots to respond to DMs only.
