### ISSUE TITLE
room control and payment button on the right panel

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1008]
Nice to have add-on a room control and payment buttons on the right hand side (connected to paypal etc. )  user can select some any or all of the premium rooms and order it via general chat room? 
##

**Comment by IQ2022** [comment]
:+1:

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
