### ISSUE TITLE
[IMPROVEMENT/FEATURE-ADD] Rocket Chat + Mobile Apps do not allow for sorting

### ISSUE THREAD

**Issue by Drangleic** [RocketChat/Rocket.Chat#10080]
### Description:

Rocket Chat web and desktop allow for users to choose how to sort channels/DMs by activity/alphabetical/etc as well as how to group channels/DMs. The native Rocket Chat + Android/iOS mobile apps have no such control over sorting/grouping. This is highly desired by our users and impacts the way they communicate from their mobile devices.

### Expected behavior:

Android/iOS mobile apps should at least replicate what users have set as their preference in the Desktop client, or allow them to configure sorting/grouping how they want.

### Actual behavior:

Users have no control over sorting/grouping in the Rocket Chat + Android/iOS mobile apps.

I didn't include server details/logs as this isn't a bug or problem with the installation, but please let me know if they are required within the issue. Thanks!

**Comment by Drangleic** [comment]
I realize now that the other projects for the mobile apps might be better for this. I will search there and see if there is already an issue there and submit one if not.

**Comment by JSzaszvari** [comment]
@Drangleic thanks very much. If you could post these requests in the relevant projects that would be awesome. Helps keep everything nice and organised :)

**Comment by JSzaszvari** [comment]
@rocket-cat close
