### ISSUE TITLE
[BUG] Livechat: When I click on the conversation open the conversation of another person

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#10088]
### Description:

When I click on the conversation open the conversation of another person.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Linux Ubuntu Server 4.4.0-1049-aws
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances:  1
* DB Replicaset Oplog:  enabled
* Node Version: v8.8.1
* mongoDB Version: 

### Steps to Reproduce:

![20180309_171240](https://user-images.githubusercontent.com/17053653/37228435-64a58594-23bf-11e8-819e-cc9ca71e55a2.gif)

### Expected behavior:

Open correct conversation

**Comment by theorenck** [comment]
Hi @guilhermecfviana, thanks for reporting the problem. Can you give us a little more context on the problem (did it happen more than once?). @renatobecker can you look into it and see if we can reproduce  the problem?

**Comment by guilhermecfviana** [comment]
@theorenck Unfortunately I do not have anything else to help you. "/

**Comment by renatobecker** [comment]
Hi @guilhermecfviana,

Have you tried this in version `0.63.0`?
I'm running this version and the behavior is like below:

![mar-28-2018 11-16-04](https://user-images.githubusercontent.com/2067649/38035681-4b6e0734-327b-11e8-9c97-f4beaf5783df.gif)

**Comment by guilhermecfviana** [comment]
Hi @renatobecker 

Acessando o seu perfil eu vi que você é brasileiro.
A minha versão é a 0.62.1 e eu utilizo o snap.
Isto ocorreu com um usuário do livechat e de lá pra cá não ocorreu novamente, eu não consegui mais reproduzir isto.

**Comment by renatobecker** [comment]
Ok @guilhermecfviana, I'll close this issue.
If you notice that this behavior is occurring again, please leave a new comment here.
Thanks.
