### ISSUE TITLE
[ Feature ] Slack+other Import selections

### ISSUE THREAD

**Issue by vRobM** [RocketChat/Rocket.Chat#10092]
After selecting a slack-export.zip the list of users is presented with checkbox for each.

What is missing is select all, unselect all type checkbox on top, so that only a few users/channels can be selected.

Otherwise we're clicking hundreds or thousands of times :-)

This applies to other import types

**Comment by theorenck** [comment]
Hi @vRobM I agree with you clicking hundreds or even thousands of times is pretty bad. @karlprieb how hard would be for us to have a select/deselect all for the importers?
