### ISSUE TITLE
Warning, in many languages the Internal Hubot interface is *very* misleading

### ISSUE THREAD

**Issue by mikaelmello** [RocketChat/Rocket.Chat#10097]
### Description:

Before being updated to load custom scripts on #7095, it was only possible to load pre-made scripts from a (now deprecated) repository (github/hubot-scripts), so in the description of the interface, the user is guided to insert names of scripts containing in this repository.

When [searching for the variable of the description](https://github.com/RocketChat/Rocket.Chat/search?q=InternalHubot_ScriptsToLoad_Description&type=&utf8=%E2%9C%93), we can see that it is still pointing to the repository in a lot of languages and if the user doesn't figure out he has to load the scripts by himself, he won't be able to load scripts at all.

**Comment by theorenck** [comment]
Hi @mikaelmello thanks for reporting it to us. @bernardoetrevisan can you take a look into this?

**Comment by timkinnane** [comment]
Please see the [last comment on this related issue](https://github.com/RocketChat/Rocket.Chat/issues/8025#issuecomment-381470969).
