### ISSUE TITLE
Unable to start Rocket.chat on windows

### ISSUE THREAD

**Issue by 26prajval98** [RocketChat/Rocket.Chat#10096]
When i start the server typing meteor npm start i get this error after proxy and MongoDB are successfully running. Someone please help me out.

Error: EPERM: operation not permitted, lstat 'E:\CompStuff\Rocket.Chat\packages\rocketchat-apps\.npm\package-new-15dpipk.twji\node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@0.63.0-develop start: `meteor npm i && meteor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@0.63.0-develop start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\26pra\AppData\Roaming\npm-cache\_logs\2018-03-11T17_48_46_440Z-debug.log

**Comment by theorenck** [comment]
Hi @26prajval98, we aim to keep our Github issues for bugs and feature requests.  It doesn't seems to fit that criteria. Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request. Thank you!

**Comment by 171563857** [comment]
u need to use a super administrator to run cmd.exe
