### ISSUE TITLE
Missing username or email on activation request

### ISSUE THREAD

**Issue by tboerger** [RocketChat/Rocket.Chat#10106]
### Description:

We enabled the option that new registrations have to be enabled by an administrator, the email gets sent out like it should be, but the email is missing the information like name or email.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: No
* Node Version: v8.9.4
* mongoDB Version: v3.6.2

### Steps to Reproduce:

1. Activate option to require admin to enable new registered users
2. Provide proper SMTP credentials
3. Register an user

### Expected behavior:

The admins receive an email that shows the name and the email address, like it's mentioned at https://github.com/RocketChat/Rocket.Chat/blob/e899d2db51abaa66613b73fbcc57c49cd1dfa64f/packages/rocketchat-i18n/i18n/en.i18n.json#L61-L62

### Actual behavior:

The admins receive an email without a name and empty `()`. I have not investigated the exact content of the variables, but possibly https://github.com/RocketChat/Rocket.Chat/blob/e899d2db51abaa66613b73fbcc57c49cd1dfa64f/server/lib/accounts.js#L160 got to use `user` instead of `options`?

**Comment by tboerger** [comment]
If somebody can confirm the `options` just needs to be replaced by `user` I can prepare a PR to solve that.

**Comment by madguy02** [comment]
This issue seems to be fixed .. Does this still appear??

**Comment by engelgabriel** [comment]
@ggazzo can you confirm if we can close this?

**Comment by MartinSchoeler** [comment]
Tested on the latest version and is working as expected, please update to the latest release and try It again, If the error persists, please open a new issue with updated details. Thanks!

<img width="675" alt="screen shot 2019-02-07 at 19 27 57" src="https://user-images.githubusercontent.com/20868078/52444157-bfdd5200-2b0e-11e9-94fa-a7aee47cd3e5.png">

**Comment by tboerger** [comment]
Thank you
