### ISSUE TITLE
Uploaded photos don't load on enabled anonymous chat access

### ISSUE THREAD

**Issue by ricardojrgpimentel** [RocketChat/Rocket.Chat#10109]
### Description:

When anonymous chat access is enabled newly uploaded images don't load thumbnail or image itself, if the option is disabled every new uplaod image is show and loads correctly

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap

### Steps to Reproduce:

1. Enable anonymous chat access
2. Uplaod new image

### Expected behavior:

New uploaded images should load when the chat has the anonymous uplaod option enabled

### Actual behavior:

New uploaded images don't load properly after enabling the anonymous chat access option

**Comment by theorenck** [comment]
Hi @ricardojrgpimentel your issue actually duplicates issue #7507 and therefor it will be closed.
