### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by balancin** [RocketChat/Rocket.Chat#10102]
Hi there,

I'm using one mailgun SMTP and I was send some test e-mails successfully but I can't use recover password, when I use password recovery I get this error "Error trying to send email: Message failed"

Can anyone knows about that? I'm using the last version 0.62.2

My best,

**Comment by theorenck** [comment]
Hi @balancin, we aim to keep our Github issues for bugs and feature requests only. This doesn't seems to fit in that criteria. Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request. Thank you!
