### ISSUE TITLE
Cannot find module './utils.js'

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#10111]
### Description:

I am setting up latest Rocket.Chat on Fedora 27 (moving from an older installation of Fedora on another server. I have set up node and mongodb - they are running. I have run npm install in the correct rocket.chat folder.

When I run node main.js, I see:
```
 /home/apps/rocketchat/Rocket.Chat/programs/server/boot.js:475
}).run();
   ^

Error: Cannot find module './utils.js'
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at index.js (packages/modules.js:401:13)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at reify.js (packages/modules.js:380:1)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at server.js (packages/modules.js:19:1)
    at fileEvaluate (packages/modules-runtime.js:343:9)
```

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Fedora 27 64 bit
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 3.4.10

### Steps to Reproduce:

1. setup rocket.chat on fedora 27
2. run node main.js

### Expected behavior:

rocket chat server should boot up

### Actual behavior:

error message is produced

### Relevant logs:
Not sure how to access any useful logs

**Comment by propertunist** [comment]
i can see numerous utils.js files inside /server/npm/node_modules/various_folders

**Comment by theorenck** [comment]
Hi @propertunist, we aim to keep our Github issues for bugs and feature requests. It doesn't seems to fit that criteria. Please see our guidelines for support. If you feel like we are closing in error, please re-open and add additional details about the bug or feature request. Thank you!

**Comment by propertunist** [comment]
@theorenck - how can i know if this is a bug or not? i am doing what i usually do to launch rocket.chat and it is failing. it certainly could be a misconfiguration on my part, but currently i have no clue what that could be. i have been running rocket.chat (using many versions) for quite a long time and never seen this before.

**Comment by propertunist** [comment]
I started the install from scratch and got it working - i have no idea what the actual issue was originally.

**Comment by SabbirPulok** [comment]
I also can not use 'npm init', its says './util.js' module not found, though i install util as globally
