### ISSUE TITLE
Is there a way to automate backup process to S3 supported storage ?

### ISSUE THREAD

**Issue by jshupptechnologies** [RocketChat/Rocket.Chat#10116]
I have a local installation of rocketchat running absolutely fine on our intranet [ Note this was installed via snap ]
I would like to setup routine backup mechanism in which the backup is uploaded to either AWS S3 or DO spaces. or any other supported S3 storage.

So would like to know if there is something already as such that rocket chat supports or this will have to go as a feature request.

**Comment by theorenck** [comment]
Hi @jshupptechnologies, we aim to keep our Github issues for bugs and feature requests. It doesn't seems to fit that criteria. Please see our guidelines for support. If you feel like we are closing in error, please re-open and add additional details about the bug or feature request. Thank you!

**Comment by jshupptechnologies** [comment]
@theorenck  You may take this as a feature request, since what I'm trying to inquire is whether or not is it possible to automate backup to S3 storage ?
1. If this support is not available currently, then you may flag this as a feature request. else
2. It's a question for me to know where do I find it.
