### ISSUE TITLE
Login / signup forms don't work on safari

### ISSUE THREAD

**Issue by jayxni** [RocketChat/Rocket.Chat#1011]
I cannot click the form on either OSX El Capitan or iOS 9 versions of Safari.

I believe this is from the CSS making it un-selectable.  Half of my mobile (iOS) users cannot register for the chat service.

```
* { 
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by miscs** [comment]
Same Problem here
