### ISSUE TITLE
Pinned file attachments are not displaying

### ISSUE THREAD

**Issue by louisemessage** [RocketChat/Rocket.Chat#10124]
### Description:

Using Rocket.Chat 2.10.5. When pinning a message with a file attachment to a channel, the file attachment does not display in the pinned message. I'm assuming expected behavior is for the file attachment to appear in the pinned message. 

Instead, all you can see is the username of the user who originally posted the file in the pinned message. I have attached a screenshot below showing the unexpected behavior. 

![screen shot 2018-03-13 at 14 21 42](https://user-images.githubusercontent.com/34244014/37347900-cc97e990-26ca-11e8-81a2-bf47606c5d76.png)

**Comment by theorenck** [comment]
Thanks @louisemessage. @karlprieb could you confirm this as an unexpected behavior? Should we expect the file attachment to appear in the pinned message?

**Comment by karlprieb** [comment]
The actual behavior is expected but we can change that if more people also think that the attachments should be visible on that system message.

What you @RocketChat/core think?

**Comment by graywolf336** [comment]
@karlprieb I honestly believe it should show the pinned message's attachment, otherwise what's the point of attaching an attachment and pinning that message if it isn't going to be displayed? :)
