### ISSUE TITLE
[BUG] Camera usage won't stop after cancelling the record of the video and doesn't show anything in Safari

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10122]
### Description:

The camera usage won't stop after cancelling the record, here's a GIF that explains the bugs:

- The video won't show;
- Camera usage is happening, and never stops;

![2018-03-13 09 57 47](https://user-images.githubusercontent.com/551004/37343129-5e4b89bc-26a5-11e8-93eb-c4c4c6c892d9.gif)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Linux

### Steps to Reproduce:

1. Open Safari;
2. Start recording a video message;

### Expected behavior:

1. It should present me my video;
2. It should cancel the usage of the video after cancelling the record;

### Actual behavior:

1. It doesn't present me my video;
2. It doesn't stop using the camera on pressing cancel;

**Comment by tassoevan** [comment]
I'm closing this issue because it is stale. Current video recording implementation relies on MediaRecorder API, unsupported on Safari. A future redesign of WebRTC in Rocket.Chat have been discussed and can be used as an alternative for video recording on Safari.
