### ISSUE TITLE
Some translations not working 

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#10125]
I've had some trouble translating RocketChat, these are the one's I've encountered so far:

- Changing the name of the home page from the admin settings doesn't work, it always says 'Home'.
- Some words are not being translated such as 'Channels' and 'Search messages' in the directory, and 'Search member' in the member list of a channel.
- Some strings are not present in the i18n list of translatable strings, such as 'Computer' in the file upload menu. 

I have tried to solve this by using the administrative tools but if it can't be solved that way I'll take a look at the source.

Thanks in advance for any assistance.

**Comment by theorenck** [comment]
Hi @cchbr thanks for let us know of this problem.
