### ISSUE TITLE
Change Optionname "Leave Room" to "Leave Channel"

### ISSUE THREAD

**Issue by Dalben96** [RocketChat/Rocket.Chat#10133]
### Description:
I think there is some inconsistency about the terms "Channel" and "Room".
If you wanna create a new Channel. The Optionpane is called "Create a new Channel" but to leave a Channel you have to select "Leave Room".
I think this might confuse new users.

### Steps to Reproduce:

1. Select "Create Channel"
2. Try to leave Channel (and read "Leave Room")

### Expected behavior:

Uses just the term "Channel".

### Actual behavior:
Uses both terms.

**Comment by theorenck** [comment]
Hi @Dalben96 thanks for bring it to our attention, I agree with you that it might cause some confusion and affects the product's consistency.

**Comment by taeven** [comment]
Submitted a PR to fix the issue.

**Comment by Sing-Li** [comment]
Need to analyze for consistency throughout our UI (not code).
