### ISSUE TITLE
pasting from Office / Word document throws error

### ISSUE THREAD

**Issue by DanielRuf** [RocketChat/Rocket.Chat#10135]
```
Uncaught TypeError: Cannot read property 'type' of null
    at l (85b95b6….js?meteor_js_resource=true:209)
    at j (85b95b6….js?meteor_js_resource=true:209)
    at Object.paste .js-input-message (85b95b6….js?meteor_js_resource=true:249)
    at 85b95b6….js?meteor_js_resource=true:87
    at Function.e._withTemplateInstanceFunc (85b95b6….js?meteor_js_resource=true:87)
    at f.View.<anonymous> (85b95b6….js?meteor_js_resource=true:87)
    at 85b95b6….js?meteor_js_resource=true:87
    at Object.f._withCurrentView (85b95b6….js?meteor_js_resource=true:87)
    at f._DOMRange.<anonymous> (85b95b6….js?meteor_js_resource=true:87)
    at HTMLTextAreaElement.delegatedHandler (85b95b6….js?meteor_js_resource=true:87)
```
![bildschirmfoto 2018-03-14 um 07 47 50](https://user-images.githubusercontent.com/827205/37387899-9d3ee362-275e-11e8-85cc-4b84416e42d0.png)

![bildschirmfoto 2018-03-14 um 07 49 43](https://user-images.githubusercontent.com/827205/37387898-9d178b64-275e-11e8-9015-268fc346b95d.png)

https://github.com/RocketChat/Rocket.Chat/blob/7864f4e080cbb82d9f1ec88977100f3af4eb5eb8/packages/rocketchat-ui-message/client/messageBox.js#L378

https://github.com/RocketChat/Rocket.Chat/blob/7864f4e080cbb82d9f1ec88977100f3af4eb5eb8/packages/rocketchat-ui-message/client/messageBox.js#L378-L401

It seems pasting a part of a Word / Office document includes mixed mime types (one for each single element in there?)

```
item kind: DataTransferItem {kind: "string", type: "text/plain"}
item kind: DataTransferItem {kind: "string", type: "text/html"}
item kind: DataTransferItem {kind: "string", type: "text/rtf"}
item kind: DataTransferItem {kind: "file", type: "image/png"}
```

Codepen for testing browser behavior on pasting parts of Word / Office documents.

**Comment by theorenck** [comment]
Hi @DanielRuf we currently only support plain text/markdown, for that reason to paste directly form word/office does not work. I agree that maybe we should have a better error handling for that but right now it was not on our roadmap to do that. We gladly accept PRs for that issue if you're willing to do so. Thanks for reporting it anyway.
