### ISSUE TITLE
@here autocomplete shows wrong list of users

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#10132]
### Description:

Typing `@here` into message box brings up a tooltip that appears to give a random list of users, with the explanation "Notify active users in this room".

### Server Setup Information:

open.rocket.chat

### Steps to Reproduce:

Type @here into message box.

### Expected behavior:

Should see list of users that are active and in the room.

### Actual behavior:

See list of users that are not active and not in the room.

The attached image shows my usage, which was in a private room with only a few members, none of the ones listed were in that room.
![screenshot 2018-03-14 17 01 23](https://user-images.githubusercontent.com/1774379/37385871-2157080a-27aa-11e8-891a-de768c7533a8.png)

**Comment by ggazzo** [comment]
@timkinnane all that users contains `here` on their username, name or email... so the users are not random ... you could remove the permission `view-outside-room` so if you dont have permission, you will see only "friends"(users that you have DM) or users inside the room

**Comment by timkinnane** [comment]
@ggazzo I didn't know the username search came back with matching emails as well. I think that's what makes it seem so random. Is that a good idea? Seems like no one would be searching for emails because you can't `@` an email.

Requiring users or admins to change permissions to correct a bad UX issue doesn't seem like a very good solution either.

Maybe if you type exactly @here or @all it shouldn't display the user list at all, just the tip about who will be notified, that might be more clear and easy to understand.

I gotta say, this issue has been updated by four other contributors, but I feel like you've just dismissed it without consideration. I'm not taking that personally, I know there's a big push to cut down the numbers, but when people take time out to help improve the product, that should be respected or people will stop bothering and you'll lose the critical feedback you need. I think it should be standard practice to ask if your comment resolves the issue as you've understood it, before just closing.

I can see that it's not technically a bug, but more just a misleading feature, maybe the real issue is the search returning users linked by email, so I'd be happy to be directed to make that input somewhere else if this issue is not the best place.

**Comment by ggazzo** [comment]
Sorry @timkinnane but I didnt understand.

It's not a lack of consideration(and I'm sorry if you felt that), but I dont think it is a bug or improvement.

@sampaiodiego @gdelavald @karlprieb @theorenck just moved the issue between milestones, it not means they are involved , but even so I asked for each one about that (my fault, we work on the same place here, maybe I should register each answer here). But we can (re)open any issue any time!. The only thing I think we could change here is 
> Maybe if you type exactly @here or @ALL it shouldn't display the user list at all, just the tip about who will be notified, that might be more clear and easy to understand.

As admin you can change which fields you will consider on the query
Administration > Accounts > 
![image](https://user-images.githubusercontent.com/5263975/40520671-cf5ebfa8-5f9d-11e8-8afe-d0b03ab23544.png)


let's wait for more opinions, any thing please ask :)

**Comment by timkinnane** [comment]
Cool. I assumed because it had been assigned specific labels and moved to `Desireable` etc, that that indicated general agreement that the issue was worth acting on.

I see now that it's not a technical bug, but I think the search suggestions experience is still confusing and It shouldn't require extra configuration to achieve an experience that makes sense. So maybe there's a UX enhancement to make here. I will make another issue for that. Thanks for your help.
