### ISSUE TITLE
Rocket.Chat just shows "whitepage" after Update to 0.62 on Safari

### ISSUE THREAD

**Issue by gcommit** [RocketChat/Rocket.Chat#10136]
### Description:

Rocket.Chat just shows whitepage after Update to 0.62 in Safari 10.1

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 3
* DB Replicaset Oplog: -
* NodeJS Version: 8.9.4 - x64
* mongoDB Version: 3.2.18
* Safari Version: 10.1

### Steps to Reproduce:

1. Start RC with 0.61.1
2. Update to 0.62.0
3. try to login in Browser (Safari 10.1)
4. It will show white page

### Expected behavior:

It should show the RC

### Actual behavior:

The page is set outside of the browser window. When you zoom in, you will be able to see parts of the normal page. As soon as you zoom out again, it will be white page again

**Comment by himbeere** [comment]
Is there an apache oder nginx involved? Anything in the logs?

**Comment by gcommit** [comment]
Hi,

there are no log entries. Since the page is "shown". The problem is, that the RC page, after the login, is outside of the monitor. I just can see, the last line of pixels at the top of my monitor, until i zoom in several times. But when i do, i cannot use it as well, because i can't see the chats or settings, just the tool bar on the left. 

I do not use apache/nginx for this. I use the docker image for this directly:  

docker pull rocket.chat:0.62.0

I tested it also with Chrome and Firefox and Safari 11.1/11.3 and it worked everywhere, but not on Safari 10.1

**Comment by theorenck** [comment]
Hi @gcommit, thanks for bring it to our attention. Can you check if the problem persists on the 0.62.2 version?

**Comment by gcommit** [comment]
Hi :)
Unfortunatly it does. It appears on 0.62.x

**Comment by gcommit** [comment]
Hi, any news here?

**Comment by eeldwin** [comment]
I'm experiencing same thing, especially on safari mobile. You can check it on rectmedia.com[rectmedia.com](url)

**Comment by eeldwin** [comment]
Is there anything that I can help to move this bug from blocked to backlog?

**Comment by gcommit** [comment]
The bug is tagged as „need more info“

Can you tell me what you need?!

**Comment by karlprieb** [comment]
Do you guys still have this problem on 0.64.1?

**Comment by chrisbennight** [comment]
I'm installed via snap, and that's on 0.63.3 still;  (it presents there still.)  What 0.64.1 gets released on that channel I'll drop back in here.

**Comment by ggazzo** [comment]
@gcommit problem solved?

**Comment by gcommit** [comment]
I don‘t know. I updated my Safari and also the rocket.chat to get rid of this. With an update, it works, yes

**Comment by ggazzo** [comment]
thanks @gcommit any problem let me know
