### ISSUE TITLE
Slack import not working

### ISSUE THREAD

**Issue by MarkSupinski** [RocketChat/Rocket.Chat#10130]
### Description:

Slack import fails with error message "Invalid Import File type"

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. Select Export from slack
2. select zip file to import
3. error message

### Expected behavior:

I've never seen it work, so I don't know!

### Actual behavior:

Error message invalid import type

### Relevant logs:

[34mI20180314-00:55:49.081(0) Exception while invoking method 'prepareImport' TypeError: require(...).native is not a function     at Function.getBSONSize (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_importer.js:123:25)     at Object.keys.forEach.date (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_importer-slack.js:184:18)     at Array.forEach (<anonymous>:null:null)     at Object.keys.forEach.channel (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_importer-slack.js:177:32)     at Array.forEach (<anonymous>:null:null)     at SlackImporter.prepare (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_importer-slack.js:174:31)     at MethodInvocation.prepareImport (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_importer.js:806:39)     at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1232/programs/server/packages/rocketchat_lib.js:2158:28)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at Promise (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1232/programs/server/packages/ddp-server.js:754:85

**Comment by theorenck** [comment]
Hi @MarkSupinski, thank you for contributing but as @mikaelmello this issue duplicates #10050 and for that reason it will be closed. Make sure you to subscribe to #10050 notifications and don't loose any updates.
