### ISSUE TITLE
Browser should never auto-fill values when editing SMTP settings

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat#10137]
### Description:

We should not provide auto-fill values when editing SMTP settings.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Linux
* Browser: Chrome, Safari

### Steps to Reproduce:

1. Open Admin panel
2. Change to "Email" -> "SMTP"

### Expected behavior:

Browser should never auto-fill username and password for me.

### Actual behavior:

Browser auto-fills and I can end up changing those values by mistake.

![2018-03-13 10_42_09-fotos](https://user-images.githubusercontent.com/4711233/37401536-a28d7160-2788-11e8-962d-144633be227b.png)

**Comment by theorenck** [comment]
Thanks for reporting it to us @kaiiiiiiiii.
