### ISSUE TITLE
Adopt ES6/ES2015 over CoffeeScript at some point?

### ISSUE THREAD

**Issue by GQAdonis** [RocketChat/Rocket.Chat#1015]
I plan to contribute heavily to this project, but I would like to request that, over time, ES6/ES2015 be adopted as the main language over CoffeeScript.

Any new modules I build (like for WebRTC connectivity using MCU/SFU technologies like Kurento and Janus WebRTC gateway--you will get to choose which, etc.) will attempt to use ES6 and not CoffeeScript unless there is some reason I should not proceed that way.

**Comment by gmsecrieru** [comment]
@GQAdonis Thanks for your interest! Please follow up on #796
