### ISSUE TITLE
error when trying to start trial 

### ISSUE THREAD

**Issue by golimer** [RocketChat/Rocket.Chat#10156]
Internal Server Error. If issue persists please contact support

**Comment by kaiiiiiiiii** [comment]
Hi @golimer,

please contact rocket.chat through there [contact page](https://rocket.chat/contact) as this seems to be an issue with the rocket.chat cloud registration process, not with the products code.

Thanks

**Comment by JSzaszvari** [comment]
Hi @golimer 

As @kaiiiiiiiii said, Please contact support through the contact us page on the official Rocket.Chat site. 

I'm going to close this as it's not related to this repository/Rocket.Chat server component but rather the registration process on the public website. 

Thanks
John Szaszvari

**Comment by JSzaszvari** [comment]
@rocket-cat close
