### ISSUE TITLE
List of settings where external servers are involved by default?

### ISSUE THREAD

**Issue by laptopdude90** [RocketChat/Rocket.Chat#10150]
I dislike having my server communicate with other servers. As such I'd like to disable that anywhere I can find it. For example, the STUN/TURN servers under WebRTC, and the gateway server under Push. Is there anywhere else that external servers are referenced?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
