### ISSUE TITLE
[BUG] Allow reactions missing translation

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#10158]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Linux x64 (ubuntu)
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.4

### Steps to Reproduce:

![permissio room](https://user-images.githubusercontent.com/17053653/37522183-f2a3ea56-2901-11e8-9d67-814ca0dba609.JPG)

When enabled the reaction does not enable the reactions.

### Expected behavior:

I think the text-enable reactions should be on the right side

**Comment by Dalben96** [comment]
I don't think this would be a good idea.
In my Opinion there is a clear system. On the right side there are the options to forbid somebody to do something. On the left sight there are the options to allow other users to do something.

**Comment by guilhermecfviana** [comment]
You right ! I understand you and now I agree about this. 
Maybe fix the text on right side (No_reactions) ?

**Comment by MartinSchoeler** [comment]
Renaming the issue to reflect the latest opinion
