### ISSUE TITLE
A function (actually a web link) of clicking to chat with me is needed

### ISSUE THREAD

**Issue by MRYingLEE** [RocketChat/Rocket.Chat#1016]
So I can put the link in my email signature. Everyone can click to chat with me without or with login.

This is also a marketing strategy for Rocket.Chat to promote itself.

This issue is related to #604, anonymous chat, but not the same. 
##

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
