### ISSUE TITLE
Which agents are online in Livechat now?

### ISSUE THREAD

**Issue by ilyamsts** [RocketChat/Rocket.Chat#10169]
Hi. How to get the list of online agents that are currently in Livechat

**Comment by kaiiiiiiiii** [comment]
@rocket-cat close

**Comment by theorenck** [comment]
@kaiiiiiiiii, as we could see by your reaction, you seems to be confused about the use of rocket-cat bot. You either need to be the owner of the issue or white listed. So in this issue you don't have actual permission. Just for you to understand.
