### ISSUE TITLE
SMTP Settings Test Email: ( Error trying to send email: Invalid login) Ver. 0.62.2

### ISSUE THREAD

**Issue by eriock** [RocketChat/Rocket.Chat#10166]
Just downloaded the new version Ver. 0.62.2,
configured and tested my SMTP settings, the test e-mail errors out (Invalid login).
Using a Gmail account with SMTP settings:
Host: smtp.gmail.com
Port: 587
IgnoreTLS: False
Pool: False

Server: 2 GB Memory / 50 GB Disk / SGP1 - Ubuntu Docker 17.12.0~ce on 16.04

Rocket.Chat logs don't produce anything unusual:
`Meteor ➔ method sendSMTPTestEmail -> userId: 4HLGEEwNPAguwop7M , arguments:  {}
Sending test email to admin@domain.com`

**Comment by tomfanning** [comment]
Me too, what's your solution?

**Comment by olegbukatchuk** [comment]
How did you solve this problem?

**Comment by tomfanning** [comment]
I set up an SMTP server on localhost, configured that to send emails properly, then just pointed rocket.chat at localhost with no authentication. Works fine.

**Comment by andreapx** [comment]
I have this problem too.
Any other solution rather than setting up a local email server?

**Comment by eriock** [comment]
@tomfanning @olegbukatchuk @andreapx Hi Guys sorry for the long wait, This was actually an error on my part I think, on the email server that I was using  I had an SSL Common Name Mismatch Error issue when I fixed that everything seems to work.  Here's my config:

PROTOCOL: SMTP
HOST: (This is where the issue is coming from)
PORT: 587
IGNORETLS: FALSE
POOL: FALSE

I can't explain why it didn't work on gmail though.
