### ISSUE TITLE
Advanced Profile information 

### ISSUE THREAD

**Issue by horvan** [RocketChat/Rocket.Chat#10167]
I'd love to have the abillity to tell people something about me in RockeChat-Profile Something like a Bio filed and a Link filed to a Website would be great.

**Comment by kaiiiiiiiii** [comment]
You can already do that by using custom user fields. There's still no official documentation, but you can have a look at one of my other issue comments where I explained everything:

https://github.com/RocketChat/Rocket.Chat/issues/9763#issuecomment-366533538

**Comment by JSzaszvari** [comment]
Hi @horvan 

I'm going to close this issue as the functionality is already implemented with custom user fields. 

The documentation is still being worked on but what you are looking for can be implemented with this

@rocket-cat close

**Comment by JSzaszvari** [comment]
@rocket-cat close
