### ISSUE TITLE
 A livechat agent is still available after they close the browser.

### ISSUE THREAD

**Issue by internalfx** [RocketChat/Rocket.Chat#10172]
### Description:

A livechat agent is still available after they close the browser.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.4

### Steps to Reproduce:

1. Toggle the livechat switch
2. Close browser
3. Livechat widget on website still shows an agent available (We only have one active agent).

### Expected behavior:

The livechat site widget should show "Leave a message"

### Actual behavior:

The livechat site widget shows "Live Chat"

**Comment by theorenck** [comment]
Hi @internalfx thanks for report the problem. @renatobecker can you take a look into this one?

**Comment by renatobecker** [comment]
@internalfx,

Just to be sure, you mean the widget remains online but if the page is reloaded the widget goes offline, right? The point here is that the widget should be updated in real time, am I correct?

I'll wait for your feedback, Thanks.

**Comment by internalfx** [comment]
No not realtime, even if the website visitor reloads, it still show that an agent is available.

**Comment by internalfx** [comment]
We updated to `0.64.1` a few days ago.....

I just asked our support rep, and they said it was fixed.
