### ISSUE TITLE
RESTAPI: change topic doesn't work on private channel

### ISSUE THREAD

**Issue by Montel** [RocketChat/Rocket.Chat#10175]
### Description:

When I use RESTAPI for changing topic it doesn't work on private channel
RC: 0.62.0
when I read code I saw:
--
//Returns the channel IF found otherwise it will return the failure of why it didn't. Check the `statusCode` property
function findChannelByIdOrName({ params, checkedArchived = true, returnUsernames = false }) {
        if ((!params.roomId || !params.roomId.trim()) && (!params.roomName || !params.roomName.trim())) {
                throw new Meteor.Error('error-roomid-param-not-provided', 'The parameter "roomId" or "roomName" is required');
        }

        const fields = { ...RocketChat.API.v1.defaultFieldsToExclude };
        if (returnUsernames) {
                delete fields.usernames;
        }

        let room;
        if (params.roomId) {
                room = RocketChat.models.Rooms.findOneById(params.roomId, { fields });
        } else if (params.roomName) {
                room = RocketChat.models.Rooms.findOneByName(params.roomName, { fields });
        }

        if (!room || room.t !== 'c') {
                throw new Meteor.Error('error-room-not-found', 'The required "roomId" or "roomName" param provided does not match any channel');
        }

        if (checkedArchived && room.archived) {
                throw new Meteor.Error('error-room-archived', `The channel, ${ room.name }, is archived`);
        }

        return room;
}
---

=>         if (!room || room.t !== 'c') {
                throw new Meteor.Error('error-room-not-found', 'The required "roomId" or "roomName" param provided does not match any channel');
        }

=> you can find room only it's a public channel not a private channel !
So we can't do it with private channel

I think that we just need to add  if (!room || room.t !== 'c' || room.t !== 'p') 

Regards

**Comment by xbolshe** [comment]
`channels.*` methods perform a search of public channels only. There are `groups.*` methods for private channels. So, a correct method to change a topic for private channel is `groups.setTopic` - see [here](https://rocket.chat/docs/developer-guides/rest-api/groups/settopic/)

**Comment by graywolf336** [comment]
Closing due to what @xbolshe said, any of the api endpoints prefixed with `channels.` is for public channels and `groups.` for private groups.
