### ISSUE TITLE
How Do I check the name of a logged in user programmatically?

### ISSUE THREAD

**Issue by myson1515** [RocketChat/Rocket.Chat#10181]
I am kind of new to node.js and I was looking through the Rocket.chat source files and I can't figure out where in the code it picks up the user info and brings it to the running rocket.chat instance. In short I am looking for a way to get user information on login.  I am not sure if I should include the URL of my server, so I won't until I hear otherwise.  Thanks!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
