### ISSUE TITLE
Password reset does not work with 2FA enabled

### ISSUE THREAD

**Issue by dan2k3k4** [RocketChat/Rocket.Chat#10183]
### Description:

If you enable two-factor authentication for your account, you will not be able to reset your password via the forgot password link.

This needs to be fixed to enable the 2FA pop-up modal check after entering a new password on the reset password link OR bypass 2FA (bad) for the reset password link.

### Steps to Reproduce:

1. Enable 2FA for your account
2. Logout and click forgot password, enter your email
3. Click the password reset link in your email
4. Enter new password
5. Get error that you cannot reset your password
6. Console error should show the error being "TOTP Required [totp-required]"

**Comment by mlocher** [comment]
Was this bug fixed as mentioned on #10666 (and if so, which PR)? I'm asking since it seems I am running into exactly this issue and if it was already addressed somewhere I would like to open/update the corresponding bug report.

**Comment by svrnwnsch** [comment]
This is still a major problem whenever someone deletes their backup codes and 2FA authentication app.

**Comment by abhipatel0211** [comment]
Is it still open? if it's solved then can anyone help me to recover my account back @debdutdeb @murtaza98

**Comment by matheusbsilva137** [comment]
Thank you for the reports! This has been fixed in #28938
Please reopen this issue if it persists
