### ISSUE TITLE
[BUG] notification indicator should not signal when group messages are unread

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat#10188]
On every other chat application I use, I only see this type of "unread messages" indicator...

![image](https://user-images.githubusercontent.com/4001792/37729572-b98b200c-2d13-11e8-9a64-fd6480609507.png)

When either I have a message in a 1-on-1 chat or if someone does "@myusername" in group chat. But in Rocket.chat desktop, I see the above indicator any time there are unread messages in any channel I have open. So, for instance, since the #general channel has a lot of activity in open.rocket.chat, my icon is pretty much always signaled. Can we fix this?

**Comment by theorenck** [comment]
Hi @bizzbyster, tanks for your feedback but I suppose this would be a discussion to have inside the Rocket.Chat.Electron repository.

**Comment by theorenck** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #707](https://github.com/RocketChat/Rocket.Chat.Electron/issues/707) via [**ZenHub**](https://www.zenhub.com/)
