### ISSUE TITLE
rocketchat_1 exited with code 1

### ISSUE THREAD

**Issue by rquinquis** [RocketChat/Rocket.Chat#10186]
### Description:

Hello all,

After a reboot, rocketchat is not starting correctly : 

`rocketchatdevelop_rocketchat_1 exited with code 1`

I stopped all mongo process and start mongo, same result.

### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: Debian 7.11
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: db version v2.0.6, pdfile version 4.5

### Steps to Reproduce:

1. kill mongod process
2. To be sure : ps aux | grep mongod
3. service mongod start
4. docker-compose up rocketchat

### Expected behavior:

rocketchat up and running

### Actual behavior:

> /usr/src/Rocket.Chat-develop# docker-compose up rocketchat
> Starting rocketchatdevelop_mongo_1
> Starting rocketchatdevelop_rocketchat_1
> Attaching to rocketchatdevelop_rocketchat_1
> rocketchat_1 | 
> rocketchat_1 | /app/bundle/programs/server/node_modules/fibers/future.js:313
> rocketchat_1 | 						throw(ex);
> rocketchat_1 | 						^
> rocketchat_1 | MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: connect ECONNREFUSED 172.17.0.2:27017]
> rocketchat_1 |     at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
> rocketchat_1 |     at emitOne (events.js:116:13)
> rocketchat_1 |     at Pool.emit (events.js:211:7)
> rocketchat_1 |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
> rocketchat_1 |     at Object.onceWrapper (events.js:317:30)
> rocketchat_1 |     at emitTwo (events.js:126:13)
> rocketchat_1 |     at Connection.emit (events.js:214:7)
> rocketchat_1 |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:189:49)
> rocketchat_1 |     at Object.onceWrapper (events.js:315:30)
> rocketchat_1 |     at emitOne (events.js:116:13)
> rocketchat_1 |     at Socket.emit (events.js:211:7)
> rocketchat_1 |     at emitErrorNT (internal/streams/destroy.js:64:8)
> rocketchat_1 |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
> rocketchat_1 |     at process._tickCallback (internal/process/next_tick.js:180:9)
> rocketchatdevelop_rocketchat_1 exited with code 1

### Relevant logs:

/var/log/mongodb/mongodb.log : 
```
***** SERVER RESTARTED *****


Wed Mar 21 16:59:22 [initandlisten] MongoDB starting : pid=3037 port=27017 dbpath=/home/sites/chat.symbiose.fr/mongodb 64-bit host=atlantis
Wed Mar 21 16:59:22 [initandlisten] db version v2.0.6, pdfile version 4.5
Wed Mar 21 16:59:22 [initandlisten] git version: nogitversion
Wed Mar 21 16:59:22 [initandlisten] build info: Linux tigereye 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 BOOST_LIB_VERSION=1_49
Wed Mar 21 16:59:22 [initandlisten] options: { bind_ip: "127.0.0.1", command: [ "run" ], config: "/etc/mongodb.conf", dbpath: "/home/sites/chat.symbiose.fr/mongodb", journal: "true", logappend: "true", logpath: "/var/log/mongodb/mongodb.log", unixSocketPrefix: "/var/run/mongodb" }
Wed Mar 21 16:59:22 [initandlisten] journal dir=/home/sites/chat.symbiose.fr/mongodb/journal
Wed Mar 21 16:59:22 [initandlisten] recover : no journal files present, no recovery needed
Wed Mar 21 16:59:22 [websvr] admin web console waiting for connections on port 28017
Wed Mar 21 16:59:22 [initandlisten] waiting for connections on port 27017
Wed Mar 21 16:59:40 [initandlisten] connection accepted from 127.0.0.1:38811 #1
Wed Mar 21 17:00:12 [conn1] end connection 127.0.0.1:38811
Wed Mar 21 17:00:22 [clientcursormon] mem (MB) res:18 virt:170 mapped:0
Wed Mar 21 17:02:00 [initandlisten] connection accepted from 127.0.0.1:39064 #2
Wed Mar 21 17:02:10 [conn2] end connection 127.0.0.1:39064
Wed Mar 21 17:02:10 [initandlisten] connection accepted from 127.0.0.1:39074 #3
Wed Mar 21 17:02:31 [conn3] end connection 127.0.0.1:39074
Wed Mar 21 17:05:22 [clientcursormon] mem (MB) res:18 virt:171 mapped:0
Wed Mar 21 17:10:22 [clientcursormon] mem (MB) res:18 virt:171 mapped:0
Wed Mar 21 17:15:22 [clientcursormon] mem (MB) res:18 virt:171 mapped:0
Wed Mar 21 17:20:22 [clientcursormon] mem (MB) res:18 virt:171 mapped:0
Wed Mar 21 17:24:02 got kill or ctrl c or hup signal 15 (Terminated), will terminate after current cmd ends
Wed Mar 21 17:24:02 [interruptThread] now exiting
Wed Mar 21 17:24:02 dbexit:
Wed Mar 21 17:24:02 [interruptThread] shutdown: going to close listening sockets...
Wed Mar 21 17:24:02 [interruptThread] closing listening socket: 6
Wed Mar 21 17:24:02 [interruptThread] closing listening socket: 7
Wed Mar 21 17:24:02 [interruptThread] closing listening socket: 8
Wed Mar 21 17:24:02 [interruptThread] removing socket file: /var/run/mongodb/mongodb-27017.sock
Wed Mar 21 17:24:02 [interruptThread] shutdown: going to flush diaglog...
Wed Mar 21 17:24:02 [interruptThread] shutdown: going to close sockets...
Wed Mar 21 17:24:02 [interruptThread] shutdown: waiting for fs preallocator...
Wed Mar 21 17:24:02 [interruptThread] shutdown: lock for final commit...
Wed Mar 21 17:24:02 [interruptThread] shutdown: final commit...
Wed Mar 21 17:24:02 [interruptThread] shutdown: closing all files...
Wed Mar 21 17:24:02 [interruptThread] closeAllFiles() finished
Wed Mar 21 17:24:02 [interruptThread] journalCleanup...
Wed Mar 21 17:24:02 [interruptThread] removeJournalFiles
Wed Mar 21 17:24:02 [interruptThread] shutdown: removing fs lock...
Wed Mar 21 17:24:02 dbexit: really exiting now
```

Thanks in advance!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
