### ISSUE TITLE
[Firefox] Unable to browse/traverse input-message content with mouse click

### ISSUE THREAD

**Issue by gmsecrieru** [RocketChat/Rocket.Chat#1019]
![input-click-traverse](https://cloud.githubusercontent.com/assets/190883/10318028/c2b7d4fc-6c3d-11e5-88c7-90382b9de805.gif)

**Comment by storrgie** [comment]
Getting same issue here in FF 41.0.1

Actually causes you from being able to login as well.

**Comment by gmsecrieru** [comment]
Related to #1011
