### ISSUE TITLE
issue with the trailing slash when rocketchat runs with a url prefix

### ISSUE THREAD

**Issue by c-schwamborn** [RocketChat/Rocket.Chat#10194]
### Description:

This issue doen't appear, if rocketchat runs directly at the url root i.e. http://192.168.1.2:3000
But having a url prefix (http://192.168.1.2:3000/chat) seems to cause issues with the desktop app.
It isn't an issue with the proxy configuration, as it occurs by accessing rc both ways, via proxy and direct.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: debian stretch amd64
* Deployment Method(snap/docker/tar/etc): tar/manual installation
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9.3
* mongoDB Version: 3.2.11

### Steps to Reproduce:

setup follows your docs at:
https://rocket.chat/docs/installation/manual-installation/debian/
proxy config as described at:
https://rocket.chat/docs/installation/manual-installation/running-in-a-sub-folder/
only diff: The apache is running on an other host, so it's not pointing to localhost.

1. remove (it existent) and init new db
2. untar rocketchat and run installation (npm install)
3. start rocketchat with env vars as documented:
export ROOT_URL=https://some.domain.com/chat/
export MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=001-rs
export PORT=3000
export ADMIN_PASS=pwd
export ADMIN_EMAIL=rcadmin@some.domain.com
0 root@rc:/opt/Rocket.Chat# node main.js

I also tried omitting the trailing slash (with a new db):
export ROOT_URL=https://some.domain.com/chat

### Expected behavior:

rocketchat is reachable at https://some.domain.com/chat/ via web browser and desktop app

### Actual behavior:

rocketchat is indeed reachable at that url, same for the direct access at http://192.168.1.2:3000/chat/ but not at https://some.domain.com/chat or http://192.168.1.2:3000/chat (without the trailing slash).
For the access via web browser there is no problem, but the desktop app seems to omit the trailing slash and can't connect to the server, even if the slash is explicitly given.

### Relevant logs:

Each time rocketchat is accessed at the url missing the trailing slash you get:
`Mar 21 22:30:50 localhost node[4448]: (node:4448) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: url must be a relative URL:`

### Workaround:

I got the desktop app to work when I added some additional rewrite rules in the proxy config within the location block:
`RewriteCond %{REQUEST_URI} ^/chat$`
`RewriteRule ^(.*)$ $1/ [L]`

**Comment by aventrax** [comment]
Confirmed with RC 0.65.2.

**Comment by BanHammor** [comment]
Confirmed with 0.65 and Apache as well. I used the workaround before the proxy redirect, so the result looked like this: 

```
 <Location /rocketchat>
    Order allow,deny
    Allow from all

    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^/rocketchat$
    RewriteRule ^(.*)$ $1/
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /var/www/(.*)           ws://localhost:3216/$1 [P]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /var/www/(.*)           http://localhost:3216/$1 [P]

    ProxyPassReverse http://localhost:3216
 </Location>

```

**Comment by ngulden** [comment]
Confirmed with Rocket.Chat 0.71.1. I used the above workaround for the proxy redirect and it did the job.

**Comment by tsega** [comment]
Not sure that it is exactly related to this but when adding a channel to Rocket.Chat desktop app for the first time, if the trailing slash is not included it will not connect to the server and keeps prompting the user to add in the address without giving any clues.

**Comment by engelgabriel** [comment]
We need a test for this kind of deployment as part of our CI.

**Comment by hugocostadev** [comment]
**NOTE:** Running in a subfolder has been officially deprecated. It will no longer be supported in the upcoming 4.0 release. See our [April 2020 announcement](https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371)

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
