### ISSUE TITLE
Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by leminhtuan2015** [RocketChat/Rocket.Chat#10191]
### Description:

Get errors:

Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'

### Server Setup Information:

Version of Rocket.Chat Server: 0.63.0-develop
Operating System: MacBook Pro 10.12.6
Deployment Method(snap/docker/tar/etc): meteor
Number of Running Instances: 1
DB Replicaset Oplog: 0
Node Version: v9.3.0
mongoDB Version: v3.4.10
Steps to Reproduce:

Follow: https://rocket.chat/docs/developer-guides/quick-start/
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor npm start

### Expected behavior:

successful install

### Actual behavior:

Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'
I20180322-08:34:14.185(7)? at Function.Module._resolveFilename (module.js:538:15)
I20180322-08:34:14.185(7)? at Function.Module._load (module.js:468:25)
I20180322-08:34:14.185(7)? at Module.require (module.js:587:17)
I20180322-08:34:14.186(7)? at require (internal/module.js:11:18)
I20180322-08:34:14.186(7)? at Object. (/Users/fuji/Documents/My/Rocket.Chat/node_modules/sharp/lib/constructor.js:10:15)
I20180322-08:34:14.186(7)? at Module._compile (module.js:643:30)
I20180322-08:34:14.186(7)? at Object.Module._extensions..js (module.js:654:10)

### Relevant logs:

Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'
I20180322-08:34:14.185(7)? at Function.Module._resolveFilename (module.js:538:15)
I20180322-08:34:14.185(7)? at Function.Module._load (module.js:468:25)
I20180322-08:34:14.185(7)? at Module.require (module.js:587:17)
I20180322-08:34:14.186(7)? at require (internal/module.js:11:18)
I20180322-08:34:14.186(7)? at Object. (/Users/fuji/Documents/My/Rocket.Chat/node_modules/sharp/lib/constructor.js:10:15)
I20180322-08:34:14.186(7)? at Module._compile (module.js:643:30)
I20180322-08:34:14.186(7)? at Object.Module._extensions..js (module.js:654:10)
I20180322-08:34:14.186(7)? at Module.load (module.js:556:32)
I20180322-08:34:14.187(7)? at tryModuleLoad (module.js:499:12)
I20180322-08:34:14.187(7)? at Function.Module._load (module.js:491:3)
I20180322-08:34:14.187(7)? at Module.require (module.js:587:17)
I20180322-08:34:14.187(7)? at require (internal/module.js:11:18)
I20180322-08:34:14.188(7)? at Object. (/Users/fuji/Documents/My/Rocket.Chat/node_modules/sharp/lib/index.js:3:15)
I20180322-08:34:14.188(7)? at Module._compile (module.js:643:30)
I20180322-08:34:14.188(7)? at Object.Module._extensions..js (module.js:654:10)
I20180322-08:34:14.188(7)? at Module.load (module.js:556:32)
I20180322-08:34:14.189(7)? at tryModuleLoad (module.js:499:12)
I20180322-08:34:14.189(7)? at Function.Module._load (module.js:491:3)
I20180322-08:34:14.189(7)? at Module.require (module.js:587:17)
I20180322-08:34:14.189(7)? at require (internal/module.js:11:18)
I20180322-08:34:14.190(7)? at npmRequire (/Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/npm-require.js:133:10)
I20180322-08:34:14.190(7)? at Module.useNode (packages/modules-runtime.js:697:18)
I20180322-08:34:14.190(7)? at fileEvaluate (packages/modules-runtime.js:342:20)
I20180322-08:34:14.190(7)? at require (packages/modules-runtime.js:238:16)
I20180322-08:34:14.190(7)? at FileUpload.js (packages/rocketchat:file-upload/server/lib/FileUpload.js:1:351)
I20180322-08:34:14.191(7)? at fileEvaluate (packages/modules-runtime.js:343:9)
I20180322-08:34:14.191(7)? at require (packages/modules-runtime.js:238:16)
I20180322-08:34:14.191(7)? at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_file-upload.js:2061:1
I20180322-08:34:14.191(7)? at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_file-upload.js:2075:3
I20180322-08:34:14.192(7)? at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:411:36
I20180322-08:34:14.192(7)? at Array.forEach ()
I20180322-08:34:14.192(7)? at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:220:19
I20180322-08:34:14.192(7)? at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:471:5
I20180322-08:34:14.192(7)? at Function.run (/Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
I20180322-08:34:14.193(7)? at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:470:11
W20180322-08:34:14.193(7)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20180322-08:34:14.194(7)? (STDERR) While this implementation will work correctly, it is known to be
W20180322-08:34:14.194(7)? (STDERR) approximately three times slower than the native implementation.
W20180322-08:34:14.194(7)? (STDERR) In order to use the native implementation instead, run
W20180322-08:34:14.194(7)? (STDERR)
W20180322-08:34:14.195(7)? (STDERR) meteor npm install --save bcrypt
W20180322-08:34:14.195(7)? (STDERR)
W20180322-08:34:14.195(7)? (STDERR) in the root directory of your application.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
