### ISSUE TITLE
Rocket Chat Rest Api Login error (Server error.)

### ISSUE THREAD

**Issue by abdelrahmanahmed** [RocketChat/Rocket.Chat#10199]
### Description:
I am trying to Send a [login](https://rocket.chat/docs/developer-guides/rest-api/authentication/login/) request using Rest Api to obtain token and user id .

### Server Setup Information:

Version of Rocket.Chat Server: 0.62.2
Operating System: Linux (CentOS)
Deployment Method(snap/docker/tar/etc): Manual: installing on CentOS
Number of Running Instances: 1
DB Replicaset Oplog: ?
Node Version: v8.9.3
mongoDB Version: ?

### Steps to Reproduce:
It is not happening every single request , so i can't tell how to reproduce it   .

### Expected behavior:
```
{
  "status": "success",
  "data": {
      "authToken": "9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq",
      "userId": "aobEdbYhXfu5hkeqG"
   }
}
```
### Actual behavior:
`Server error.
`

**Comment by MartinSchoeler** [comment]
Not enough information provided. We need more information on how to reproduce this consistently since this could be result of lots of different problems (like a problem when installing, or the server freezing). Try asking on our [forums](https://forums.rocket.chat/)  or [community support channel](https://open.rocket.chat/channel/support) maybe someone can help you debug this further. Thanks!

**Comment by abdelrahmanahmed** [comment]
Thank you for your reply , anyway i found this in my server log 

```
Mar 25 11:42:53 li1537-99 rocketchat: TypeError: Cannot read property 'debug' of undefined
Mar 25 11:42:53 li1537-99 rocketchat: at Object._internalRouteActionHandler [as action] (/opt/Rocket.Chat/programs/server/packages/rocketchat_api.js:175:25)
Mar 25 11:42:53 li1537-99 rocketchat: at Route.share.Route.Route._callEndpoint (/opt/Rocket.Chat/programs/server/packages/nimble_restivus.js:347:32)
Mar 25 11:42:53 li1537-99 rocketchat: at /opt/Rocket.Chat/programs/server/packages/nimble_restivus.js:236:33
Mar 25 11:42:53 li1537-99 rocketchat: at packages/simple_json-routes.js:98:9
```

**Comment by hannes-angst** [comment]
Found the same error in the freshly installed version 0.63.3 on a centoOS7.

```
typeError: Cannot read property 'debug' of undefined
at Object._internalRouteActionHandler [as action] (/opt/rocket/chat/programs/server/packages/rocketchat_api.js:175:25)
at Route.share.Route.Route._callEndpoint (/opt/rocket/chat/programs/server/packages/nimble_restivus.js:347:32)
at /opt/rocket/chat/programs/server/packages/nimble_restivus.js:236:33
at packages/simple_json-routes.js:98:9
```

How did you fix it?
