### ISSUE TITLE
Log path for Docker Images

### ISSUE THREAD

**Issue by storrgie** [RocketChat/Rocket.Chat#1020]
I'm currently deploying as follows:

```
docker create --name rocket_data -v rocket_db:/data/db -v rocket_logs:/home/app/logs busybox /bin/true    

docker run -d --name rocket_db --restart always --volumes-from rocket_data mongo --smallfiles

docker run -d --name rocket_app --restart always --link rocket_db --volumes-from rocket_data -p 3000:80 \
    --env MONGO_URL=mongodb://rocket_db:27017/meteor \
    --env ROOT_URL=https://domain.tld \
    --env MAIL_URL=smtp://name@domain.tld:pass@smtp.gmail.com:587/ \
    rocketchat/rocket.chat
```
I created the volume rocket_logs for /home/app/logs based on the docker_compose.yml file in the base repository. There is nothing being written in this folder. What is the correct way to get file based logging out of rocket? Maybe an environmental variable to specify the path?

Currently I use the `docker logs` directive to get to them, but would rather have it all in a file I can search through.

**Comment by gmsecrieru** [comment]
@storrgie I am not sure if that would be your problem but shouldn't you be mapping volumes with absolute paths, e.g.:

`docker run -v **/Users/<path>**:/<container path>`

**Comment by geekgonecrazy** [comment]
I think this may be a matter of it not actually logging to file.  I'm not 100% sure but I think its just logging to stdout.

**Comment by storrgie** [comment]
@gmsecrieru in CentOS/Fedora not specifying an absolute path is actually good because then docker will handle all the selinux stuff for you. It just all gets placed in /var/lib/docker/volumes

**Comment by gmsecrieru** [comment]
Thanks for sharing!

**Comment by storrgie** [comment]
but lke @geekgonecrazy said, it'd be really nice if logging could be done to a file so that I could examine it outside of the container.

Also logging could be 'leveled', right now it seems like its in 'debug' where its spewing literally everything to stdout.

**Comment by gmsecrieru** [comment]
:+1:

**Comment by Sing-Li** [comment]
:-1: 

For docker containers.  It is *A LOT* easier when it is *not* logged to a file.  The stdout log is by far easier to view and tail with docker.

Please see http://stackoverflow.com/questions/24621067/how-to-read-files-and-stdout-from-a-running-docker-container

**Comment by storrgie** [comment]
:scream_cat:

Can you pull the directive for logs from your docker-compose.yml

**Comment by Sing-Li** [comment]
which docker-compose.yml ? Can you provide the github URL?

**Comment by geekgonecrazy** [comment]
Also see logstash for handling of logs from docker in a nice easy way :)

**Comment by Sing-Li** [comment]
:+1:  Especially for 'production' sort of deploy!

**Comment by marceloschmidt** [comment]
@Sing-Li do you think we need to remove these lines? https://github.com/RocketChat/Deploy.to.Cloud/blob/master/GenericLinux/docker-compose.yml#L15-L16
We can close this issue when this is done or answered.

**Comment by marceloschmidt** [comment]
@Sing-Li @geekgonecrazy do you guys have any take on this? Should this be closed already?

**Comment by geekgonecrazy** [comment]
@marceloschmidt so we don't even log to file.  So yeah I think we should close this

**Comment by Sing-Li** [comment]
Actually.  I even wanted to remove the `docker-compose.yml`  entirely :scream: 

Some contributor made a PR one day, merged the next morning, and support ticket never stopped streaming in ever since  :grin:
