### ISSUE TITLE
Mongo is not available, can't start

### ISSUE THREAD

**Issue by float1** [RocketChat/Rocket.Chat#10201]
### Description:

After rebooting server rocket chat not available in the web browser. Used to work ok, but suddenly stopped. I have to kill mongod process and restart mongo and rocket chat services, than chat is available.

### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: ubuntu server 16.04 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v9.8.0
* mongoDB Version: MongoDB shell version: 2.6.10

### Steps to Reproduce:

1. reboot server
2. 
3. 

### Expected behavior:

rocket chat automatically up

### Actual behavior:

rocket chat not available in web browser but rocket chat service active, and mongo service dead because address already in use.

### Relevant logs:
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] MongoDB starting : pid=2078 port=27017 dbpath=/var/snap/
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] db version v3.2.7
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] git version: 4249c1d2b5999ebbf1fdf3bc0e0e3b3ff5c0aaf2
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] allocator: tcmalloc
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] modules: none
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] build environment:
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten]     distmod: ubuntu1604
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten]     distarch: x86_64
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten]     target_arch: x86_64
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.979+0100 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManageme
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.997+0100 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use 
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.997+0100 E NETWORK  [initandlisten]   addr already in use
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.997+0100 E STORAGE  [initandlisten] Failed to set up sockets during startup.
Mar 22 17:41:40 ubuntu rocketchat-server.rocketchat-mongo[2064]: 2018-03-22T17:41:40.997+0100 I CONTROL  [initandlisten] dbexit:  rc: 48
Mar 22 17:41:40 ubuntu systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
Mar 22 17:41:40 ubuntu systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Unit entered failed state.
Mar 22 17:41:40 ubuntu systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
Mar 22 17:41:41 ubuntu systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
Mar 22 17:41:41 ubuntu systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
Mar 22 17:41:41 ubuntu systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Start request repeated too quickly.
Mar 22 17:41:41 ubuntu systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-mongo.

**Comment by float1** [comment]
Thank you for your help :)

I think I solved it by removing mongodb-server from server because i think i had two of them installed, i guess one with snaf installation and maybe I installed mongodb-server later, now it works

**Comment by TwizzyDizzy** [comment]
Hey Zoran!

Nice that you solved it, maybe you could also mark you topic in the forums as solved and maybe just copy your text from here there? Thanks in advance :)

Cheers
Thomas

**Comment by goupper** [comment]
1.ps axu|grep rocket
如果有mongo的进程，找到后并
kill -9 进程号
2. 重新启动rocket-server
sudo systemctl stop snap.rocketchat-server.rocketchat-server.service
sudo systemctl start snap.rocketchat-server.rocketchat-server.service
3. 启动mongodb
nohup sudo mongod --bind_ip 127.0.0.1 --pidfilepath /var/snap/rocketchat-server/common/mongod.pid --smallfiles --journal --dbpath=/var/snap/rocketchat-server/common --replSet rs0 &
