### ISSUE TITLE
No indication that a user is not permitted to create public channels

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#10200]
### Description:

I revoked the permission to create public channels for certain user groups. The issue with this is, that there is no indicator that the user is not permitted to create a new public channel, the button is just not clickable. (and nothing happens)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Ubuntu Server 16.04.4 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 3
* DB Replicaset Oplog: YES

### Steps to Reproduce:

1. Revoke permission for users to create new public channels
2. Try to create a new public channel

### Expected behavior:

There should be a screen that says the user that he is not permitted to do so..

### Actual behavior:

Nothing happens.

### Relevant logs:

![image](https://user-images.githubusercontent.com/5877910/37780377-ee42c6ca-2dee-11e8-87e2-75620eb160bf.png)

**Comment by TwizzyDizzy** [comment]
Remark: the button to add a channel from directory view also seems to be impacted.

**Comment by karlprieb** [comment]
We will fix the private/public channel switch behavior on the Create new channel page, check for permissions to show the create channel button on Directory and [create permissions to allow users to use the Directory feature](https://github.com/RocketChat/Rocket.Chat/issues/10626).
