### ISSUE TITLE
Desktop client: permanent notifications

### ISSUE THREAD

**Issue by ftoledo** [RocketChat/Rocket.Chat#10203]
I research if is possible to get more "intrusive" notificacions for the desktop client (at windows OS for now).

* Permanent/Sticky popup notifications.. (just stay visible until user get click) 
* Flash icon / on bottom panel/toolbar 
* Popup the main window?

Or some else. 

The idea is to ensure to user must be notified even if leave and back from the computer for some little time.
thanks!

**Comment by kaiiiiiiiii** [comment]
Hi @ftoledo,

can you please open an issue in the [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron) repository for that?

This repository is mainly for the server component.

Thanks,
Kai

**Comment by MartinSchoeler** [comment]
Please, follow @kaiiiiiiiii suggestion Thanks!

**Comment by ftoledo** [comment]
My apologies. i will forward to that repo!
thanks!
