### ISSUE TITLE
Android client microphone and camera not work

### ISSUE THREAD

**Issue by acrixl** [RocketChat/Rocket.Chat#10208]
### Description:

Android client microphone and camera not work

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: debian 9.4
* Deployment Method: manual
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 

### Actual behavior:

Android 7.1.2

Android client microphone and camera not work, all permissions added

when microphone pressed nothing happen

**Comment by acrixl** [comment]
i don't think it related to android native also know as rocket.chat+
rocket.chat+ just work

it related to cordova based rocket.chat

it work on adnroid 7.1.2 but no audio, video

on android 4.4.4  it just hang after login with white screen

**Comment by kaiiiiiiiii** [comment]
There’s one for the Cordova app as well :)

https://github.com/RocketChat/Rocket.Chat.Cordova

Cheers,
Kai

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by acrixl** [comment]
cordova way currently is preferred i think 

this is note from main README.md
Note: currently the native apps doesn't support all the features that web does. If you're looking for it, you should download the Cordova apps.

project Rocket.Chat.Cordova is cordova wrapper, but web app itself is part of this project i think

so issues with web app support level cover both projects

i thing currently in web app used wild stuffs in js,css,html5 that not supported in android 4.4.4 default cordova webview, so it good idea to fix it or add note about 4.4.4 platform deprication

**Comment by graywolf336** [comment]
Closing this as the notice on the Cordova project states that after the end of March it will be deprecated and no longer supported. https://github.com/RocketChat/Rocket.Chat.Cordova#important-notice
