### ISSUE TITLE
Suppress system generated messages in rooms ["user" set moderator by "user", room topic changed to] 

### ISSUE THREAD

**Issue by lukegracie** [RocketChat/Rocket.Chat#10202]
### Description:
[for Private Groups and Channels]
When you change/set a users status/level (owner, leader, moderator) you can't control the system conversation message that shows. You always see "user" was set moderator by "user"

When you change the the Room Topic a message is also displayed.

You should have a way to suppress, or turn these off, like the "user" has joined and "user" has left messages.

At a minimum the admin/owner of the channel should be able to delete the messages.

### Server Setup Information:
* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.81
* mongoDB Version: 

### Steps to Reproduce:
1. create a channel
2. add a user tot he channel
3. set new user to moderator
4. view channel notification 

### Expected behavior:
have a way to remove/suppress these messages

### Actual behavior:
when you open the channel you always see these system generated messages

**Comment by graywolf336** [comment]
We have a setting for this, but it seems the redesign accidentally removed the ability to save it: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-channel-settings/server/methods/saveRoomSettings.js#L115

**Comment by ggazzo** [comment]
@graywolf336 I think this feature had a small life 
created: https://github.com/RocketChat/Rocket.Chat/commit/3161216f45f0981dde856c028af37cf0269d13b2
it was deleted on merge   :/
3 days after: https://github.com/RocketChat/Rocket.Chat/pull/3773/commits/f6d978b385fc9e1610843ce4dec169098163b298
I made a fix: https://github.com/RocketChat/Rocket.Chat/pull/10704
@lukegracie this feature will not remove the old messages, but prevent for new...

what do you think @graywolf336 ?
