### ISSUE TITLE
Pass Parameter to rocket chat to auto logging without the need to write the credentials

### ISSUE THREAD

**Issue by hassanayoub85** [RocketChat/Rocket.Chat#10215]
Dear,
I want to integrate rocket chat in my website, i succcessfully set it up on my linux server 14.04, without any isues, and i made simple api to connect with mongodb, so when user sigunp in my site, an account with same credentials created in rocketchat, and when user edited his parameters in my website, parameters are synced with rocketchat, however i still have 1 problem which is autologging in in rocketchat from my site.
So what I want is, when a user user1/pass1, loggin to my site, then click on chat, instead of login page of rocket chat appears, i want to pass the username and pass from my site to the rocket chat and the user autologgin without the need of reentering the credentials.
Any idea for achieving that?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Rocket.Chat has several possibilities to authenticate users (oAuth, SAML, AD). What you're describing / trying to implement is SSO.

Please open a topic in the forums and see if somebody can help you there: https://forums.rocket.chat/c/community-support

I am closing this, as there seems to be no bug in Rocket.Chat here.

Cheers
Thomas
