### ISSUE TITLE
Laptop and external display monitor

### ISSUE THREAD

**Issue by Shaners42** [RocketChat/Rocket.Chat#10228]
Hello, 

I dock my laptop in work which has an external screen. Moving the Rocket Chat app to the external screen then undocking seems to save its position in the window-state-main.json. This means the window won't display when trying to open it undocked unless the json file is modified. There must be a better way to handle that? 

OS: Windows 10 1709 x64 with latest RocketChat+ 2.10.5

**Comment by TwizzyDizzy** [comment]
@rockey-cat close

Reasons:

* you reported an issue for the Electron client in the Rocket.Chat server repo
* your issue has already been reported there: https://github.com/RocketChat/Rocket.Chat.Electron/issues/380

Cheers
Thomas
