### ISSUE TITLE
[BUG][Chrome APP] When the internet is down, my user stays online

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#10238]
### Description:

On Chrome App when the internet is down, my user stays online.

I tested on firefox and chrome browser (not app) and this worked perfectly.

* My livechat is enabled.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.62.1
* Operating System: Linux (Ubuntu) 16.04 x64
* Deployment Method(snap/docker/tar/etc):  snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled

### Steps to Reproduce:

1. I do login on Chrome App
2. Make your internet is down

### Expected behavior:

User Offline

### Actual behavior:

User Online

**Comment by geekgonecrazy** [comment]
Can you please explain what this chrome app you mention is?

**Comment by guilhermecfviana** [comment]
Hi ! @geekgonecrazy 

On Windows, you can get rocket.chat chrome app through:

- https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.10.5/rocketchat-setup-2.10.5.exe

**Comment by geekgonecrazy** [comment]
Ah!  Our Rocket.Chat+ app.  Does it show the bar across the top that it's trying to reconnect?

**Comment by guilhermecfviana** [comment]
Yes, you did reproduce this? 

When my internet is down, my user stay online for others users.

**Comment by geekgonecrazy** [comment]
If other users see you as online it's a bug.  The status will show your chosen status not your current status... So that's not a bug.  The only exception is away.

Going to go ahead and close

**Comment by guilhermecfviana** [comment]
@geekgonecrazy I think it's a bug.

My user stay online when my internet is down during all time.

Ex.: At 9 o'clock the internet is down and came back at 11 o'clock, during this time my user stay online for other user.

I think my user should show offline for other users.

**Comment by geekgonecrazy** [comment]
sounds like your userSessions collection might be messed up:

Connect to mongo shell switch to your db and run:
```
db.usersSessions.remove({})
```
