### ISSUE TITLE
mailparser license

### ISSUE THREAD

**Issue by AtzDyna** [RocketChat/Rocket.Chat#10235]
Rocket.Chat  uses "mailparser" in version "2.2.0" as a dependency. Mailparser uses the the European Union Public License 1.1 (EUPL v1.1)[https://github.com/nodemailer/mailparser/blob/master/LICENSE](https://github.com/nodemailer/mailparser/blob/master/LICENSE).

I am no expert in software licenses and therefore I was wondering if the MIT License used by Rocket.Chat is compatible with this European Union Public License 1.1, because the EUPL is a copyleft license like the GPL.

Can anyone explain why or why not these licenses are compatible?

**Comment by geekgonecrazy** [comment]
Rocket.Chat does not have a version 2.2.0  Our latest is 0.62.0 can you clarify a bit more which exact version you are referring to?

Also being more of a question then a bug or feature request i'd refer you to our forum(https://forums.rocket.chat) where such questions are a bit better suited.  This way we can keep our github clean for bugs and feature requests.

Thanks,
