### ISSUE TITLE
Incoming webhook not woking

### ISSUE THREAD

**Issue by ampj007** [RocketChat/Rocket.Chat#10230]
I created new incoming webhook using rocket chat. 

curl -X POST -H 'Content-Type: application/json' --data '{"username":"Ship Reporter","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' https://chat.lintcloud.com/hooks/xxxxxxxxx/yyyyyyyyyy

If i hit the url using curl its give the response false.
{"success":false}

Anybody know this issue please guide me to fix.

**Comment by Hudell** [comment]
Are you using a script in this webhook? Can you share your webhook configuration?

**Comment by ampj007** [comment]
yes. 
script:
class Script {
  /**
   * @params {object} request
   */
  process_incoming_request({ request }) {
    // request.url.hash
    // request.url.search
    // request.url.query
    // request.url.pathname
    // request.url.path
    // request.url_raw
    // request.url_params
    // request.headers
    // request.user._id
    // request.user.name
    // request.user.username
    // request.content_raw
    // request.content

    // console is a global helper to improve debug
    console.log(request.content);

    return {
      content:{
        text: request.content.text
        // "attachments": [{
        //   "color": "#FF0000",
        //   "author_name": "Rocket.Cat",
        //   "author_link": "https://open.rocket.chat/direct/rocket.cat",
        //   "author_icon": "https://open.rocket.chat/avatar/rocket.cat.jpg",
        //   "title": "Rocket.Chat",
        //   "title_link": "https://rocket.chat",
        //   "text": "Rocket.Chat, the best open source chat",
        //   "fields": [{
        //     "title": "Priority",
        //     "value": "High",
        //     "short": false
        //   }],
        //   "image_url": "https://rocket.chat/images/mockup.png",
        //   "thumb_url": "https://rocket.chat/images/mockup.png"
        // }]
       }
    };

    // return {
    //   error: {
    //     success: false,
    //     message: 'Error example'
    //   }
    // };
  }
}
![screen shot 2018-03-29 at 8 27 47 pm](https://user-images.githubusercontent.com/8987881/38096179-df6745a8-338f-11e8-93f6-90d57737bb37.png)


i got this log in server

[29/Mar/2018:07:06:26 +0000] "POST /hooks/xxxxxxxxxxxxxxx/yyyyyyyyyyyyyyy HTTP/1.1" 400 53 "-" "python-requests/2.18.1"

**Comment by Hudell** [comment]
It worked fine for me even with your script. What version of Rocket.Chat are you using?

**Comment by ampj007** [comment]
![screen shot 2018-03-29 at 8 45 21 pm](https://user-images.githubusercontent.com/8987881/38097159-3ccd9e3e-3392-11e8-9ace-4e4cd7dfbedd.png)
I added the version with few details

**Comment by Hudell** [comment]
Are you still having this problem?

If you disable your script, does it work?

I've tried to replicate the issue with all possible configurations, but it always executed successfully. If you have any other information that may help me trigger this error, let me know.

**Comment by brasofilo** [comment]
@ampj007 posted a full sample code but the bare minimum necessary is below.
Thanks ampj007, truly appreciated, this is like some arcane/secret code, without you I wouldn't have achieved it!

```
class Script {
    process_incoming_request({ request }) {
      console.log(request.content);
      return {
        content:{
          text: request.content.text
        }
      };
    }
}
```

**Comment by mdhirt** [comment]
I know this issue is closed but just in case anyone else is having the same issue.
Change your header from  -H 'Content-Type: application/json' to  -H 'Content-Type: application-json'
