### ISSUE TITLE
Livechat "Closing Chat Comment" box loses cursor 

### ISSUE THREAD

**Issue by crowdstar5566** [RocketChat/Rocket.Chat#10245]
### Description:

When trying to close a live chat it asks you to type a comment.  
(Personally, I don't really want to leave a comment and would like an option to just close the chat.) 
But when you select the text field to type your comment the cursor is stolen and drops to the message box in the grayed background.  It lets you type and send a message instead of typing your comment. 
I can get a letter or two in and get the chat to close but obviously this should be fixed.
### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.8.1
* mongoDB Version: 

### Steps to Reproduce:

1. Start a livechat
2. Close a livechat from agent side

### Expected behavior:

Allow typing comment and close chat.

### Actual behavior:

Cursor is moved before comment can be typed.

**Comment by renatobecker** [comment]
Hi @crowdstar5566,

Have you tried this in version 0.63.0?
I'm running this version and the behavior is like below:

![mar-28-2018 11-47-02](https://user-images.githubusercontent.com/2067649/38036820-f781554c-327d-11e8-816a-40ceb1428e87.gif)

**Comment by crowdstar5566** [comment]
Since it's installed as a snap I can't get to version 63.0.  
62.2 seems to be the current and "snap refresh rocketchat-server --channel=edge" installed an even older version.
