### ISSUE TITLE
How to connect to MongoDB for insert users though API REST?

### ISSUE THREAD

**Issue by rjeria** [RocketChat/Rocket.Chat#10241]
First, I added an user with this command:

use admin
db.createUser( { user: "adm", pwd: "adm", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ] } )

After, I'm trying to connect though Robo3T and Mongobooster with this URL: mongodb://admin:pass@192.168.1.5:27017I  but I haven't response.

I need to add an user in the database because I'm trying to doing an iframe login but I can't to access to Database to insert it.

**Comment by geekgonecrazy** [comment]
Please post help request on our community forum: https://forum.rocket.chat 

Github is for bugs and planned features.

Closing
