### ISSUE TITLE
[BUG] User details view is different depending on the context from the same starting point

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10249]
### Description:

I'm trying to delete an user, I go to "Administration -> Users -> Select the user". The view that will appear on the right, will show different variations of buttons depending on my previous context before entering the admin page. Here's a GIF that demonstrate from `#general` room and from the DM with the user.

![2018-03-28 09 27 43](https://user-images.githubusercontent.com/551004/38028902-b68f53ee-326a-11e8-8a3a-a8020f5765fc.gif)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2, 0.63.0-develop
* Operating System: Linux

**Comment by subham103** [comment]
@ggazzo @gabriellsh Is this an intended behavior in rocket chat? I think it is as when we are in a channel and goes to the user page, then it shows the option to delete the user but when we are in a private channel with the user, it shows the option to block the user(just like a normal user).

**Comment by gabriellsh** [comment]
I think that's not intended. It's a different context, when on the admin page, "Delete" means you're going to delete the user from your rocket.chat instance.  What seems to be happening is that when in the private channel, opening the user info from administration triggers as if you were to click in the users info outside the administration menu.

Sorry for the convoluted answer, but that's basically it.

**Comment by subham103** [comment]
I believe the `blockUser/Delete` option is now being replaced by the `conversation` option. If that's the case, then this issue doesn't exist anymore.
![Rocket Chat](https://user-images.githubusercontent.com/43502196/75487441-68897880-59d4-11ea-97e2-3c323177d5f3.png)

**Comment by gabriellsh** [comment]
Thanks for your observation @subham103, this context is no longer mixed.
