### ISSUE TITLE
Segmentation fault (core dumped) on 2nd start up.

### ISSUE THREAD

**Issue by GavinHanson** [RocketChat/Rocket.Chat#10255]
### Description:

When attempting to run the main.js file (after a restart) it doesn't give any logs or error output but gives a core dumped error.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0-deve;lop
* Operating System: Ubuntu Xenial
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.10.0
* mongoDB Version: 3.2.19

### Steps to Reproduce:

1. Initial Start up with correct env vars etc.
2. Restart container
3. Wait for Mongo to come up, attempt to start rocketchat.

### Expected behavior:
For it to start or provide an exception

### Actual behavior:
root@rocketchat:/etc/supervisor# nodejs /data/app/bundle/main.js
Will load cache for users
2 records load from users
Will load cache for rocketchat_room
1 records load from rocketchat_room
Will load cache for rocketchat_subscription
1 records load from rocketchat_subscription
Will load cache for rocketchat_settings
633 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Segmentation fault (core dumped)

If I continue to attempt to start it then it will eventually start (After around 5mins of trying to start it).

**Comment by himbeere** [comment]
nodejs-8.10.0 is broken. take a look at https://github.com/RocketChat/Rocket.Chat/issues/10060#issuecomment-374305553

**Comment by GavinHanson** [comment]
Thanks, Looks like the fix from lower down in that page worked, installed 8.9.4 and it seems to be working again.

**Comment by si458** [comment]
has this issue been fixed at all without using an old version of node?
the latest stable node is now 8.11.1 and its still generating this core dump error

**Comment by mahdikiani** [comment]
I have the same problem in this configuration:
`➔|  Rocket.Chat Version: 0.65.1               |
➔ |       NodeJS Version: 8.11.1 - x64         |
➔ |             Platform: linux                |
➔ |         Process Port: 3000                 |
➔ |             Site URL: http://xxxxxxx:3000  |
➔ |     ReplicaSet OpLog: Enabled              |
➔ |          Commit Hash: 8349c36de0           |
➔ |        Commit Branch: HEAD                 |
➔ |                                            |
`
