### ISSUE TITLE
snap auto-refresh overwrite my Caddyfile

### ISSUE THREAD

**Issue by sefter25** [RocketChat/Rocket.Chat#10266]
### Description:

After snap auto-refresh rocket-chat yesterday night, it was not possible to access our rocket chat server, because the "Caddyfile" was overwritten by auto-refresh. It´s normal? How we can stop/disable the auto-refresh?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: OpenSuse Leap 42.3
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. snap autorefresh rocket.chat

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Seems to be a dupe of #10268, no? Copying your description there though, because it is more precise.

Cheers
Thomas

**Comment by sefter25** [comment]
hi @all 

this is not the same of 10268, i don´t have problems with Caddy. My only problem is then snap do a auto-refresh, that my caddyfile will be overwritten with the default caddyfile and after a restart of caddy service the https url will not work. How i can stop the auto-refresh?
