### ISSUE TITLE
Fail to start rocket.chat snap

### ISSUE THREAD

**Issue by ricardojrgpimentel** [RocketChat/Rocket.Chat#10268]
I'm having trouble starting my instance of rocket.chat, i'm running ubuntu 16.04 with a snap of rocket.chat and noticed this morning that the chat wasn't running, here are the logs:

`systemctl status snap.rocketchat-server.rocketchat-server.service` is running without errors

` systemctl status snap.rocketchat-server.rocketchat-mongo.service` is running without errors

`systemctl status snap.rocketchat-server.rocketchat-caddy.service` returns:

`Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Unit entered failed state.
Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
Mar 29 09:06:30 ubuntu-s-1vcpu-1gb-fra1-01 systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.`

`journalctl -u snap.rocketchat-server.rocketchat-caddy.service` returns:

`open /root/snap/rocketchat-server/1238/.caddy/acme/acme-v02.api.letsencrypt.org/sites/example.com/example.com.crt: no such file or directory
Main process exited, code=exited, status=1/FAILURE
Unit entered failed state.
Failed with result 'exit-code'.`

So it looks like its a problem with the certificate, what can i do?

**Comment by Nepoxx** [comment]
`example.com.crt` certainly looks like an invalid certificate. Based on https://github.com/RocketChat/Rocket.Chat/issues/10266 it seems like the Caddyfile was overwritten by the default one, you might have to edit it to point to your certificate?

**Comment by roberdaniel** [comment]
Same problem here.
Caddy can't find certificates on path ...acme-v02.api.letsencrypt.org/sites... folder is empty.
Acme V02 certificates are not currently being created?

**Comment by TwizzyDizzy** [comment]
@sefter25 in #10266 for better description:

> After snap auto-refresh rocket-chat yesterday night, it was not possible to access our rocket chat server, because the "Caddyfile" was overwritten by auto-refresh. It´s normal? How we can stop/disable the auto-refresh?

Cheers
Thomas

**Comment by ricardojrgpimentel** [comment]
@geekgonecrazy I have less files in the 1232 directory then the current directory

**Comment by geekgonecrazy** [comment]
Still likely worth a try to copy them over

**Comment by geekgonecrazy** [comment]
Related:https://caddy.community/t/rocketchat-works-only-in-self-signed-mode/3595/2

**Comment by ricardojrgpimentel** [comment]
Still doesn't work, the logs show that its trying to look for 
`/root/snap/rocketchat-server/1238/.caddy/acme/acme-v02.api.letsencrypt.org/sites/example.com/example.com.crt`

Non of the folders inside `/root/snap/rocketchat-server/` have the v02 folder

**Comment by geekgonecrazy** [comment]
ok time for a bit of work around with the snap system.  We need to basically follow the suggestion from there in the forum and get the log file.  To do so we need to run something like:
```
sudo HOME=/root/snap/rocketchat-server/current /snap/rocketchat-server/current/bin/caddy -conf=/var/snap/rocketchat-server/current/Caddyfile -log /tmp/caddy.log
```

Should crash like normal... But now take and get contents of /tmp/caddy.log

Lets see what that yields us :)

**Comment by ricardojrgpimentel** [comment]
It doesn't say much

`2018/03/30 18:29:00 [INFO][example.com] acme: Obtaining bundled SAN certificate
2018/03/30 18:29:01 [INFO][] Certificate written to disk: /root/snap/rocketchat-server/current/.caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt`

the sites folder is empty

**Comment by geekgonecrazy** [comment]
It really says `/sites/.crt` with no site name? :thinking:

**Comment by ricardojrgpimentel** [comment]
Yes

**Comment by geekgonecrazy** [comment]
I hope the caddy guys can give more insight.  Because that doesn't make much sense to me.  We may need to roll back to a previous caddy version :thinking:

**Comment by mholt** [comment]
There is a bug in the acmev2 branch of xenolf/lego, which is what Caddy uses for certificates, that apparently causes it to not report an error when there is one, or in any case, returns an empty Certificate and a nil error. I'm sure it will be resolved before too long. In the meantime, I've [worked around it](https://github.com/mholt/caddy/blob/73b61af58d31d88763c865ef85377eccf1b9bb22/caddytls/client.go#L261) in the latest master branch of Caddy, which you can try. I'm not sure it gets to the root of the issue, unfortunately, but it won't write empty `.crt` files like that anymore.

Please build Caddy from the latest master and let me know how it goes!

**Comment by ricardojrgpimentel** [comment]
I guess we need to wait for a new snap update for this right?

**Comment by geekgonecrazy** [comment]
@mholt thanks for taking the time to post on this issue.  I'll get another build of this going to give that a try.

@ricardojrgpimentel if you are stuck you can run: 
```
sudo HOME=/root/snap/rocketchat-server/1232/ /snap/rocketchat-server/1232/bin/caddy -conf=/var/snap/rocketchat-server/current/Caddyfile -log /tmp/caddy.log
```

Basically executing the prior snap's caddy version.  

1232 should be the number of the last revision.

**Comment by ricardojrgpimentel** [comment]
Thank you @geekgonecrazy it works!

**Comment by 2E0PGS** [comment]
Hi I am running into the same issue. My RocketChat snap instance all of a sudden stopped working. It used to work just fine with the following config:

```
sudo cat /var/snap/rocketchat-server/current/Caddyfile
https://subdomain.mydomain.org
proxy / localhost:3000 {
  websocket
  transparent
}
```

Now I have to use self signed in order to get it working:

```
sudo cat /var/snap/rocketchat-server/current/Caddyfile
https://subdomain.mydomain.org
tls self_signed
proxy / localhost:3000 {
  websocket
  transparent
}
```

I am running the following versions:

`/snap/rocketchat-server/current/bin/caddy -version Caddy 0.10.12 (unofficial)`

`lrwxrwxrwx  1 root root    4 May 23 20:20 current -> 1265`

```Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

```
34mI20180523-21:06:44.621(1) [32m➔ [32m+------------------------------------------------------+ 
[34mI20180523-21:06:44.621(1) [32m➔ [32m|                    SERVER RUNNING                    | 
[34mI20180523-21:06:44.622(1) [32m➔ [32m+------------------------------------------------------+ 
[34mI20180523-21:06:44.622(1) [32m➔ [32m|                                                      | 
[34mI20180523-21:06:44.623(1) [32m➔ [32m|  Rocket.Chat Version: 0.64.2                         | 
[34mI20180523-21:06:44.623(1) [32m➔ [32m|       NodeJS Version: 8.9.4 - x64                    | 
[34mI20180523-21:06:44.623(1) [32m➔ [32m|             Platform: linux                          | 
[34mI20180523-21:06:44.624(1) [32m➔ [32m|         Process Port: 3000                           | 
[34mI20180523-21:06:44.624(1) [32m➔ [32m|             Site URL: https://subdomain.mydomain.org  | 
[34mI20180523-21:06:44.625(1) [32m➔ [32m|     ReplicaSet OpLog: Enabled                        | 
[34mI20180523-21:06:44.625(1) [32m➔ [32m|          Commit Hash: 105715ef27                     | 
[34mI20180523-21:06:44.626(1) [32m➔ [32m|        Commit Branch: HEAD                           | 
[34mI20180523-21:06:44.626(1) [32m➔ [32m|                                                      | 
[34mI20180523-21:06:44.626(1) [32m➔ [32m+------------------------------------------------------+ 
```

While poking around in that folder I just discovered something. I am not sure if one is simply a template but my Caddy files are different in these two locations:

```
cat /snap/rocketchat-server/current/bin/Caddyfile 
http://:8080
proxy / localhost:3000 {
  websocket
  transparent
}

sudo cat /var/snap/rocketchat-server/current/Caddyfile
https://subdomain.mydomain.org
tls self_signed
proxy / localhost:3000 {
  websocket
  transparent
}
```

Anyway I have the same problem and most of my troubleshooting so far has happened over in this issue: https://github.com/RocketChat/Rocket.Chat/issues/8539

**Comment by mholt** [comment]
The latest versions have some bug fixes: https://github.com/mholt/caddy/releases

https://caddyserver.com/download

**Comment by 2E0PGS** [comment]
@mholt I am running this via a snap on Ubuntu 16.04 is there a dev / unstable snap upstream I can switch to in order to use those changes on my LTS box? Is there a planned stable release for xenial with those "fixes"?

**Comment by mholt** [comment]
I dunno, you'll have to ask the RocketChat team.

**Comment by geekgonecrazy** [comment]
New version of the snap should be in stable channel with caddy 0.11.0 in it.  Please let me know if you guys still have the issue.

Going to go ahead and close this issue.

**Comment by 2E0PGS** [comment]
Hi the service still will crash but it also appears port 443 is not being used:

NMAP:
```
PORT     STATE SERVICE
22/tcp   open  ssh
3000/tcp open  ppp
```

CADDYFILE:
```
https://subdomain.mydomain.org
proxy / localhost:3000 {
  websocket
  transparent
}
```
It seems to use port 8080 still once I run service xxx status on the caddy snap.

**Comment by geekgonecrazy** [comment]
What are your caddy logs?

`journalctl -u snap.rocketchat-server.rocketchat-caddy`
