### ISSUE TITLE
Connect with Nextcloud/Nextcloud Talk in order to build a strong communication platform

### ISSUE THREAD

**Issue by GoetheG** [RocketChat/Rocket.Chat#10261]
The way I see it Rocket.Chat is missing functions from Nextcloud and the other way around. Maybe it would be interesting to combine both projects or at least build a bridge? That would be a definite win for the community,

**Comment by HammyHavoc** [comment]
This would be amazingly cool.

**Comment by GoetheG** [comment]
@HammyHavoc: Take a look here, thry actually plan a chat support:
https://github.com/nextcloud/spreed/issues/687

**Comment by geekgonecrazy** [comment]
This would be very cool.  I think maybe an option is even supporting rocket.chat on their side to integrate in.  Obviously a two way street. Maybe even Rocket.Chat Apps could be built to help facilitate it.

Maybe open a feature request on our [forum](https://forums.rocket.chat) detailing how you would propose such an integration working. Going to go ahead and close here as we are reserving this for planned features and bugs to make things more organized.
