### ISSUE TITLE
not able to install rocket chat manually on my ubuntu machine

### ISSUE THREAD

**Issue by mayankstg** [RocketChat/Rocket.Chat#10276]
Hi 
     I am following all the steps given in Rocket chat installation guide, but when i am making environment variables after that when i am calling step 
node main.js

getting the error 

/home/manishk/Rocket.Chat/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:11)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Collection (packages/mongo/collection.js:97:40)
    at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /home/manishk/Rocket.Chat/programs/server/packages/accounts-base.js:2010:15
    at /home/manishk/Rocket.Chat/programs/server/packages/accounts-base.js:2017:3
    at /home/manishk/Rocket.Chat/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /home/manishk/Rocket.Chat/programs/server/boot.js:220:19
    at /home/manishk/Rocket.Chat/programs/server/boot.js:471:5
    at Function.run (/home/manishk/Rocket.Chat/programs/server/profile.js:510:12)
    at /home/manishk/Rocket.Chat/programs/server/boot.js:470:11

when i am checking MONGO_URL variable using $ echo $MONGO_URL
it is showing the output as 
mongodb://localhost:27017/rocketchat

can anyone give me some guidance over this issues

**Comment by eeldwin** [comment]
You need export the environment variable by using these commands:

export ROOT_URL=http://your-host-name.com-as-accessed-from-internet:3000/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3000

**Comment by mayankstg** [comment]
Hi eeldwin
 thanks for the response but i already did same 
echo $MONGO_URL
mongodb://localhost:27017/rocketchat

echo $PORT
3000

echo $ROOT_URL is also giving me the required port but still manual installation not working but if i tried using snap this is working totally fine but my requirement is to do the task manually

**Comment by geekgonecrazy** [comment]
to ensure it you can even do:
`MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://yoursite node main.js`

My guess is your setting, and then maybe running via sudo or something of the sort.  Meaning Rocket.Chat doesn't have access at time of actually running the process.

In the future please see appropriate places for support requests: https://rocket.chat/docs/getting-support/
