### ISSUE TITLE
Error handling AmazonS3.js 

### ISSUE THREAD

**Issue by logancodes** [RocketChat/Rocket.Chat#10289]
### Description:
There is no error handling for the callback in get function(see line number 10 in AmazonS3.js)

**File location:** Rocket.Chat/packages/rocketchat-file-upload/server/config/AmazonS3.js 

The code present in this file is duplicated from Googlestorage.js (Rocket.Chat/packages/rocketchat-file-upload/server/config/GoogleStorage.js). 

It is important to include error handling implementation in AmazonS3 get function. This can be done by following the same error handling syntax in Googlestorage.js (line 10-13 in the picture)

<img width="1273" alt="codeduplication copy" src="https://user-images.githubusercontent.com/12794224/38176977-b73456be-35ad-11e8-9167-804ec02c0a9f.png">

**Comment by logancodes** [comment]
Hi @Hudell, we are actually working on fixing the issue. So you might not need to fix it. Thanks

**Comment by Hudell** [comment]
Alright!
