### ISSUE TITLE
Excluded from Google index

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#10285]
My Rocket Chat installation seems to be excluded from Google's index because it (according to them) contains a redirect. Since the chat is not open to anonymous user the only page to crawl is the login page, which Google excludes.

Has anyone else experienced this and how can it be solved? Could it be because the login page directs the user to /home even though the user isn't logged in?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. Please let me refer you to the Community Support Forum, which is a better place for this as there's no bug involved here: https://forums.rocket.chat/c/community-support

Thank you for understanding.

Cheers
Thomas
