### ISSUE TITLE
Rocket Chat fine with most browsers EXCEPT Safari (11.1 and 11.0.3, examples)

### ISSUE THREAD

**Issue by smcracraft** [RocketChat/Rocket.Chat#10288]
### Description:

Continual retries in browser connected to www.cloudstuart.com:3000 serving Rocket Chat snapped upon an Ubuntu issue on AWS.

Error is "A problem repeatedly occurred with "www.cloudstuart.com:30000/channel/general"

### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): snack
* Number of Running Instances: 1
* DB Replicaset Oplog: N/A - ask
* Node Version: N/A - ask
* mongoDB Version:  N/A - ask

### Steps to Reproduce:

Use Safari

### Expected behavior:

No issue, as we see in Chrome.

### Actual behavior:

Continual reconnects with "A problem repeatedly occurred with..."

This happened after several days of posting by a particularly active user of links from
youtube.

### Relevant logs:
 -- ask

**Comment by geekgonecrazy** [comment]
Please try 0.63.0 one of our team had this issue also, but since 0.63.0 hasn't seen it.

**Comment by smcracraft** [comment]
Thanks.

Is there a way to force this upgrade with snap?

For the test. 

We installed with snap.

**Comment by geekgonecrazy** [comment]
`sudo snap refresh rocketchat-server`

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
