### ISSUE TITLE
Add API to get favourite rooms

### ISSUE THREAD

**Issue by Shailesh351** [RocketChat/Rocket.Chat#10281]
### Description:
There is no API for getting favourite rooms and no field for favourite in Room object. This is needed to add grouping feature to Android Client https://github.com/RocketChat/Rocket.Chat.Android/issues/988

### Expected behaviour:
- We can add favourite as field of Room Object
`"f" : true/false`

- Or  add rest API to get all the favourite rooms
`rooms.favourites`

### Actual behaviour:
Currently there is no API for getting favourites rooms.

**Comment by rafaelks** [comment]
@Shailesh351 Have you checked the API `subscriptions.get`? AFAIK it's returning the field `f`. The room object is not per-user, that's why you don't have this property on this request's result. I'm gonna close the issue for now, if you find any issue let's reopen it. 👍
