### ISSUE TITLE
Search cancel icon(x) and search text overlap on overflow

### ISSUE THREAD

**Issue by taeven** [RocketChat/Rocket.Chat#10292]
Description :
The search text and the cancel icon (i.e. X) overlap when the search text is too long.

Steps to reproduce : 
1. click on the search icon on left to search for a username or channel.
2. type a long text so that the searchbar overflows.

Expected behaviour:
It should not overlap.
![screenshot from 2018-04-02 02-12-47](https://user-images.githubusercontent.com/17789028/38177294-b2fda86a-361c-11e8-8e3a-de667bb6c5fd.png)

Actual behaviour:
icon overlaps.
![screenshot from 2018-04-02 01-43-58](https://user-images.githubusercontent.com/17789028/38177298-c7603df4-361c-11e8-9c65-8f021dbf6c62.png)

**Comment by kaiiiiiiiii** [comment]
Can you please provide the required issue template? I can't reproduce this error in 0.62.2 and you didn't provide any version number or any further details.

![screen shot 2018-04-01 at 23 39 17](https://user-images.githubusercontent.com/4711233/38177724-efda4886-3605-11e8-8964-c13cd14c5d14.png)


Cheers

**Comment by taeven** [comment]
@kaiiiiiiiii 
Even in your screenshot too, you can see clearly the cancel icon i.e. 'X' overlaps with 's' (last letter of your search text)
![issue](https://user-images.githubusercontent.com/17789028/38178126-a01f978c-3629-11e8-8cb5-51cbd3545ca5.png)

**Comment by kaiiiiiiiii** [comment]
I’m sorry, I miss understood the issue 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
