### ISSUE TITLE
Add some files to the gitignore file

### ISSUE THREAD

**Issue by taeven** [RocketChat/Rocket.Chat#10295]
### Description:

Add the following files to `.gitignore` file. When I made some changes and added them to the staging area, the following files were automatically added and got commited and pushed to PR #10293 . As these are npm files which need not be pushed, so adding them to gitignore makes sense.
```
packages/rocketchat-katex/package-lock.json
packages/rocketchat-livechat/.app/package-lock.json
```

### Expected behaviour:

NPM files should be added in gitignore to avoid pushing extra unused files.

### Actual behaviour:

Unnecessary files getting pushed. ref https://github.com/RocketChat/Rocket.Chat/pull/10293/files

I would like to work on this issue if it seems relevant to the maintainers.

**Comment by graywolf336** [comment]
Those aren't build files, those are actual npm files that help speed up local development along with builds.

**Comment by geekgonecrazy** [comment]
Lets keep discussion around this in the PR you opened.  No need to duplicate to an issue also.
