### ISSUE TITLE
Embed posted links

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#103]
https://github.com/itteco/meteor-oembed

**Comment by dstollie** [comment]
take a look at this issue about rich embeds for SpaceTalk: https://github.com/SpaceTalk/SpaceTalk/issues/73

**Comment by engelgabriel** [comment]
Thanks! I'll try the same approach

**Comment by engelgabriel** [comment]
https://github.com/SpaceTalk/SpaceTalk/pull/74/files

**Comment by engelgabriel** [comment]
All working now!
