### ISSUE TITLE
API Request: Get and Reset number of unread messages.

### ISSUE THREAD

**Issue by robindijkhof** [RocketChat/Rocket.Chat#10306]
We can of course get the number of unread messages by adding the `unreads` and `oldest` query parameters. However this number depends on the oldest data of course. This isn't a big problem but it can differ from the value displayed in the web client. Also the push notification icon displays the number of unread messages identical to the value in the webclient. Now we can end up with two different values which is confusing for a user.

**Comment by MarcosSpessatto** [comment]
Hey @robindijkhof, I did not understand at what endpoint this inconsistency is exactly but this [endpoint](https://rocket.chat/docs/developer-guides/rest-api/subscriptions/getone/) might be useful for this problem. Please let me know if this issue persists. Thanks

**Comment by robindijkhof** [comment]
HI @MarcosSpessatto . Currently the only way to get the number of unread messages it through this api:

    `${baseUrl}/im.history?roomId=${roomId}&unreads=true&oldest=${date.toISOString()}`

From the result, add `unreadNotLoaded ` and `messages.length`. 


The problem is this required a date, which you might not always have (re-install, multiple instances, etc). Also this value will probably be diffenrent from the value displayed in the webclient. This can be confusing for endusers. It would be nice if you could get the same value as the webclient displays.

And other problem is that an enduser might has already read a message by some app that uses the api. In the webclient this will still be seen as an unread message. So it would be nice if we could reset the number of unread messages displayed by the webclient.

**Comment by MarcosSpessatto** [comment]
>  Previously the only way to get the number of unread messages it through this api:

Hi @robindijkhof, as I said above you can get the number of unread messages in [this](https://rocket.chat/docs/developer-guides/rest-api/subscriptions/getone/) endpoint, it has a property called `unread`, that return the number of unread messages, it return the same number that's displayed on the web client.

> And other problem is that an enduser might has already read a message by some app that uses the api. In the webclient this will still be seen as an unread message. So it would be nice if we could reset the number of unread messages displayed by the webclient.

To reset (read) messages, you can use [this](https://rocket.chat/docs/developer-guides/rest-api/subscriptions/read/) endpoint.

Feel free to DM (https://open.rocket.chat/direct/marcos.defendi).

**Comment by robindijkhof** [comment]
Well then I think this can be closed.
