### ISSUE TITLE
[BUG] 0.63 REST API authentication with external OAuth services doesn't work  

### ISSUE THREAD

**Issue by osfunapps** [RocketChat/Rocket.Chat#10307]
### Description:
In the latest version of Rocket.Chat (0.63 RC1), the REST API authentication requests doesn't work with Facebook and Twitter.

reference to the REST API authentication:
https://rocket.chat/docs/developer-guides/rest-api/authentication/

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63 RC1
* Operating System: Linux Amazon AMI 
* Deployment Method(snap/docker/tar/etc): docker 
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.963x64

### Steps to Reproduce:

CURL command sent:
curl -H "Content-type:application/json" \
      http://localhost:3000/api/v1/login \
      -d '{ "serviceName": "facebook", accessToken": "hash",
      "secret": "hash", "expiresIn": 200 }'

### Expected behavior:

{
  "status": "success",
  "data": {
      "authToken": "9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq",
      "userId": "aobEdbYhXfu5hkeqG"
   }
}

### Actual behavior:
{
    "status": "error",
    "message": "Match error: Expected Integer, got \"200\" in field expiresIn"
}

**Comment by MarcosSpessatto** [comment]
Hi @osfunapps, I tried to simulate your problem, but with the same parameters, the server responds successfully.

My request:
curl -H "Content-type:application/json" http://localhost:3000/api/v1/login -d '{ "serviceName": "facebook", "accessToken": "EAAVw1Dkan4YBAC3iIWm0ucZCESpyxPg5ZA6lwTbsCZAkLsmVBwAA7khAx1jhTKiEBGLJ4978LXtiQhAwCKTXTJR3MAAFelq57VmF3EeHkJ8xzzCXzKYZBEEeD8Q72zBo80cEGqSCT967aZBHtc4RSED7MG11PPEMz5wu7NIniWQZDZD", "secret": "449e80d00bad240b4f07d58f4a772b6d", "expiresIn": 200 }'

Maybe, looking at your request, the accessToken field is missing the quote at the beginning, maybe that's the problem. 

The CURL command in the docs is wrong, it is missing the missing quote at the beginning. I'll fix it.

**Comment by MarcosSpessatto** [comment]
Hello @osfunapps, @zvikachu did you test how it was mentioned in the previous comment?

**Comment by MarcosSpessatto** [comment]
@osfunapps I'm closing this issue. If the problem persists, feel free to reopen. Thx.
