### ISSUE TITLE
Change Directorysearchbar Text to "Search"

### ISSUE THREAD

**Issue by Dalben96** [RocketChat/Rocket.Chat#10305]
### Description:

When opening the Directory. The searchbar is showing "Search Message". You can only search Channels or User.
### Server Setup Information:

* Version of Rocket.Chat Server:  0.62.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* Node Version:  v8.9.4

### Steps to Reproduce:

1. Open Directory

### Expected behavior:

Searchbar shows "Search"

### Actual behavior:

Searchbar shows "Search Message"

**Comment by ggazzo** [comment]
closed by #11026
