### ISSUE TITLE
[BUG] Apostrophe misparsed in display text of markdown url 

### ISSUE THREAD

**Issue by c0dzilla** [RocketChat/Rocket.Chat#10322]
### Description:

If display text in [text] (url) or <url|text> contains an apostrophe, it is not properly displayed.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.4

### Steps to Reproduce:

Enter a message like [it's good] (https://www.google.com) // without space between text and url

### Expected behavior:
![image](https://user-images.githubusercontent.com/23701803/38281728-b47c4904-37c9-11e8-9a84-e10f81f2e13d.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/23701803/38281703-96c29d3c-37c9-11e8-807b-e2d2a9a35750.png)

**Comment by localguru** [comment]
This is still a problem in 0.69.2

![bildschirmfoto_2018-10-02_16-45-30](https://user-images.githubusercontent.com/8544984/46356536-3bac2700-c663-11e8-8a5e-5b04ed90df38.png)

**Comment by MAccadia** [comment]
I'm also affected by this. I tried today on [open.rocket.chat](https://open.rocket.chat/group/test_max?msg=uSdrHE3ZpxWQsDKgE).

This is a bigger issue for French as it uses a lot more apostrophes than English.

**Comment by fliptrail** [comment]
I am working on it.
