### ISSUE TITLE
Toggle for Hot-keys

### ISSUE THREAD

**Issue by storrgie** [RocketChat/Rocket.Chat#1032]
Would it be possible to toggle listening for hot-keys on and off as a stopgap for a likely eventual configuration interface for hot-keys?

Currently rocket.chat listens to CTRL+SHIFT+P which is the default hot-key for 'new private window' on Firefox. It's likely a bad idea to implement hot-keys have have direct collision with browser functions.

I believe this also corresponds with issue #938 
##

**Comment by geekgonecrazy** [comment]
I wasn't aware of this key binding.  Only of ctrl + p and cmd + p.  Will need to investigate this.

**Comment by MartinSchoeler** [comment]
We had some changes on the shortcuts so i will be closing this.
