### ISSUE TITLE
[BUG] Forget user session on window close

### ISSUE THREAD

**Issue by dachnikrus** [RocketChat/Rocket.Chat#10328]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Linux, Debian 9
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: none
* Node Version: v8.8.1
* mongoDB Version: from following instruction https://rocket.chat/docs/installation/manual-installation/debian/

### Steps to Reproduce:
1. 
Options -> Administration -> Accounts -> Forget User Session on Window Close (True)
2. 
Close setting -> Back to chat
3. 
Close Window

### Expected behavior:

Open link to chat and login again, because Chat forgot user session.

### Actual behavior:

Nothing

### Relevant logs:

**Server:**
```
https://rocket.chat/docs/contributing/reporting-issues#gathering-logs -->
[34mI20180404-15:16:27.632(3) [34mMeteor ➔ method getStatistics -> userId: MfxWgbqnLMTnYG5qY , arguments:  {} 
[34mI20180404-15:16:27.637(3) [34mMeteor ➔ method instances/get -> userId: MfxWgbqnLMTnYG5qY , arguments:  {} 
[34mI20180404-15:16:47.749(3) [34mMeteor ➔ method saveSetting -> userId: MfxWgbqnLMTnYG5qY , arguments:  { '0': 'Accounts_ForgetUserSessionOnWindowClose',   '1': true,   '2': null } 
[34mI20180404-15:17:14.518(3) [34mMeteor ➔ method getStatistics -> userId: MfxWgbqnLMTnYG5qY , arguments:  {} 
[34mI20180404-15:17:14.522(3) [34mMeteor ➔ method instances/get -> userId: MfxWgbqnLMTnYG5qY , arguments:  {} 
[34mI20180404-15:17:14.850(3) [34mMeteor ➔ publish stream-notify-logged -> userId: MfxWgbqnLMTnYG5qY , arguments:  { '0': 'private-settings-changed',   '1': { useCollection: false, args: [] } } 
[34mI20180404-15:17:15.260(3) [34mMeteor ➔ method private-settings/get -> userId: MfxWgbqnLMTnYG5qY , arguments:  { '0': 2018-04-04T12:16:47.753Z }  
```

**Browser(Chrome):**
![bugs](https://user-images.githubusercontent.com/2556359/38307647-0bbf94a2-381d-11e8-8dd3-439df4b6a517.PNG)

**Comment by cloudsandladders** [comment]
Is this still a bug?  Or did this get fixed?  Because now regardless of the setting I have for  "Forget User Session on Window Close" when I close the window I am logged out.

**Comment by xnextx** [comment]
This is still a bug :(

**Comment by bugnotmenow** [comment]
Still the same issue with version 0.72.3. Nobody fixed it.

**Comment by jbaits** [comment]
This is still an issue in 0.74.3. CentOS 7 deployed via tar.

**Comment by megamaced** [comment]
Rocketchat version: 1.2.3 (official Docker image)
Rocketchat client: 2.15.5

Using SAML auth

"Forget User Session on Window Close" does not seem to do anything. Close and open either a browser or the electron client and the user is remains logged in
