### ISSUE TITLE
Problem with client on multimonitor environment

### ISSUE THREAD

**Issue by marcin70** [RocketChat/Rocket.Chat#10327]
### Description:
If I remove the monitor from the multi-monitor configuration, the application stays on the non-existent screen.

### Steps to Reproduce:

1. Move RocketChat to screen on another monitor
2. Disconnect *this another* monitor from computer
3. RocketChat stays on disconnected screen/monitor and I can't do anything...

### Expected behavior:

Automatic move to the existing screen/monitor.

### Actual behavior:
Nothing...

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

This is an issue of the Electron Client, **not the Rocket.Chat server**. It has already been reported and a quick fix is available: https://github.com/RocketChat/Rocket.Chat.Electron/issues/380

Cheers
Thomas
