### ISSUE TITLE
personal "view mode" (chat window) setting gone in 0.63.0

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#10326]
Hello Devs.

After upgrading to 0.63.0 the personal setting "view mode" is gone. Usually you can choose between normal, cozy and compact. I can find the "view mode" settings under accounts as adminstrator but it's rather useless if i cannot change that setting as regular user. Any ideas on that? Bug or feature?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 8.9.4
* mongoDB Version: 3.4

thanks and cheers
t.

**Comment by himbeere** [comment]
0.62.0

![bildschirmfoto 2018-04-04 um 11 22 03](https://user-images.githubusercontent.com/631865/38299562-b1fc0d1e-37fa-11e8-845c-cf312ddc9382.png)

0.63.0

![bildschirmfoto 2018-04-04 um 11 24 42](https://user-images.githubusercontent.com/631865/38299610-ce8733d2-37fa-11e8-8470-f13eef1bc55d.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. Option has moved directly into the main UI: 

![viewmode](https://user-images.githubusercontent.com/179595/38310699-889f1eac-381d-11e8-8f09-553cb47af7f6.png)

Cheers
Thomas

**Comment by stefanandres** [comment]
This only changes the appearance of the left sidebar, not the actual chat window, as the "view mode" in <0.63.0 did.

**Comment by himbeere** [comment]
@TwizzyDizzy Is this setting in the main ui supposed to change both view modes? sidebar *and* chat window? My question is mainly regarding the chat window.

thanks

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Ah. I see. You're right, I was not having both in mind. Reopen.

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
@karlprieb is this something intentionally removed or did it get removed when relocating the channel list settings?

**Comment by karlprieb** [comment]
We accidentally removed the option :( We will fix that on the next release.
Sorry for that @himbeere

**Comment by himbeere** [comment]
No big deal. Thanks @karlprieb 

cheers
t.

**Comment by shaiton** [comment]
Unfortunatly this issue is coming back in this version:

484ee10c2b71b8f12436b9c42feff264d00f48f3
Mon May 27 23:31:46 2019 -0300
HEAD
1.1.0

**Comment by rodrigok** [comment]
@ggazzo can you check this?

**Comment by nstoeckigt** [comment]
In the current version this is still/again an issue.

![image](https://user-images.githubusercontent.com/1396509/92483862-9c4a2400-f1e9-11ea-8b6b-17c12ff592e2.png)
