### ISSUE TITLE
Remove "powered by" in LiveChat

### ISSUE THREAD

**Issue by repa12** [RocketChat/Rocket.Chat#10333]
hi,

can anyone help me to remove the "powered by Rocket.Chat" in the Livechat Widget?

thanks for your help!

**Comment by geekgonecrazy** [comment]
Feature wise I don't think this is something we are planning to implement.  @renatobecker please correct me if i'm wrong.

Going to go ahead and close this.  If you are looking for support please see our [forum](https://forums.rocket.chat) or https://rocket.chat/docs/getting-support/

**Comment by tim-soft** [comment]
Are there any plans to allow _convenient_ customization of the livechat widget? It's UI has a lot of room for improvement and changing it seems really difficult without recompiling from source.

**Comment by geekgonecrazy** [comment]
I believe there are a lot of features planned for that.  But I can't speak for specifics.

**Comment by renatobecker** [comment]
We are planning the redesign of the Livechat widget, as well as enhancing its Livechat customization features.
I still can't say, but it is possible that some of these features appear on our next roadmap.

**Comment by tim-soft** [comment]
That's good to hear, I hope you guys take some styling inspiration from https://www.intercom.com/live-chat

I think the this is the style of live-chat that most people would want to use

![capture](https://user-images.githubusercontent.com/10257939/38627266-d3f98696-3d6b-11e8-9b5e-ea18ea6aaad2.PNG)
