### ISSUE TITLE
https is not working!!!

### ISSUE THREAD

**Issue by bixmatech** [RocketChat/Rocket.Chat#10339]
Dear,
I have a server (http://bixma.com and https://bixma.com), and have a website on it, with many subfolders access through http://bixma.com/subfolderexample and https://bixma.com/subfolderexample.
I installed rocetchatserver on my server and it is working perfectly, where the website is loaded perfectly and rocketchat is loaded on http://bixma.com:3000 and the subfolders are accessed well.
Today i tried to install ssl by following this tutorial https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/, and it succeeded, but, after I finished installing, when i access http://bixma.com it auto redirect to https://bixma.com, and all subfolders  are redirected to rocketchat too, and the website on http://bixma.com is not working anymore!!!

How can I make that the rocketchat ssl just work on https://bixma.com:3000 and keep my website on http://bixma.com and https://bixma.com working and subfolders too?

Thanks

**Comment by kaiiiiiiiii** [comment]
Hi @bixmatech,

please let me refer you to the Community Support Forum, which is a better place for this as there's no  bug involved here: https://forums.rocket.chat/c/community-support

Thank you for understanding.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

It's exactly as @kaiiiiiiiii said. Therefore I'm closing this.

Cheers
Thomas
