### ISSUE TITLE
Cash Tags and HashTag to be added 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1033]
have a Cash tag and Hash tag feature enabled.. In Chat rooms.. 
https://github.com/stocktwits/stocktwits-text-js 
a link for whats available from stocktwits.

http://stocktwits.com/developers/docs/display_requirement

Note that $ and # are all searchable in twitter this could be useful when someone pushes messages from chat room to twitter stream.
##

**Comment by IQ2022** [comment]
https://github.com/gregjacobs/Autolinker.js

**Comment by IQ2022** [comment]
any ETA on this issue?

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
