### ISSUE TITLE
Remove one of the download buttons on a voice message

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#10337]
Seems a little redundant to have two download buttons on a voice message.
<img width="250" alt="voice message" src="https://user-images.githubusercontent.com/503951/38349092-557caeec-389d-11e8-8569-9d5a48f91d69.PNG">
Is there a reason for this?

**Comment by TwizzyDizzy** [comment]
Yes... and no. The lower download button comes from the browser-native implementation. I guess it's not guaranteed that every browser offers the download button in its native implementation, so I guess it's good that Rocket.Chat's own button is there, too.

Just my thoughts though, somebody from frontend should be able to answer this better.

Cheers
Thomas

**Comment by HammyHavoc** [comment]
Hey @TwizzyDizzy, thanks for the smart reply!

This is within the desktop app, where we do most of our chatting rather than the desktop browser, but I guess that's because it's a container, right?

**Comment by TwizzyDizzy** [comment]
The Desktop ab is simply a fanciliy repacked version of chromium (more precise: the combination of nodejs and chromium and some other stuff. All together it's called Electron).

So yes. The app is basically a browser, so no different on that front.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Just verified this. Firefox doesn't show the download button, so I'm going to close this.

Cheers
Thomas
