### ISSUE TITLE
Meteor._reload.reload is deprecated

### ISSUE THREAD

**Issue by tttt-conan** [RocketChat/Rocket.Chat#10330]
**Description**
Check here: https://github.com/meteor/meteor/commit/14dbfb4c2b52dadefa1cf79c1fc5e28aee2ad7d0
Meteor._reload.reload method is deprecated in Meteor latest version (1.6.1.1). Which cause app don't reload when saving changes in "My Account" section. It should be changed to Reload._reload.

**Steps to Reproduce:**

1. Running app with latest Meteor (1.6.1.1)
2. Create user and login
3. Go to My Account section
4. Change localization
5. Save Changes

**Expected behavior:**
The app should be reloaded to see the changes

**Actual behavior:**
Nothing happen beside toast message

**Comment by sampaiodiego** [comment]
do you mind opening a pull request? thx
