### ISSUE TITLE
Secret url login flashes invalid url 

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#10349]
### Description:
If you have secret url login enabled.  If you goto the url, it will show invalid url briefly before showing the registration form.

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/views/app/secretURL.js#L14

We're setting to false causing the invalid url page to show up, and then after verifying setting to true.

It works but is bad UX.  Would be better to show nothing at all until verified then to say invalid prematurely.

**Comment by engelgabriel** [comment]
@geekgonecrazy  can you test this again? It seems to be fixed.

**Comment by engelgabriel** [comment]
This happens because we load the setting via WebSockets, the ReactJS rewrite should fix this.
