### ISSUE TITLE
After update to 0.63.0

### ISSUE THREAD

**Issue by SebastienGauthierSVI** [RocketChat/Rocket.Chat#10340]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 3.0.9

### Steps to Reproduce:

Update from 0.62.0 to 0.63.0

### Expected behavior:
Just start succesfully

### Actual behavior:
Will load cache for users
28 records load from users
Will load cache for rocketchat_room
254 records load from rocketchat_room
Will load cache for rocketchat_subscription
615 records load from rocketchat_subscription
Will load cache for rocketchat_settings
675 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
76 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
packages/meteor.js:1252
    Fiber(runWithEnvironment).run();
                              ^

ReferenceError: Apps is not defined
    at EventEmitter.RocketChat.sendMessage (packages/rocketchat:lib/server/functions/sendMessage.js:54:3)
    at ErrorHandler.trackError (packages/rocketchat:error-handler/server/lib/RocketChat.ErrorHandler.js:58:15)
    at Object.Meteor._debug (packages/rocketchat:error-handler/server/lib/RocketChat.ErrorHandler.js:34:9)
    at onException (packages/meteor.js:1220:14)
    at runWithEnvironment (packages/meteor.js:1243:9)

**Comment by sampaiodiego** [comment]
what is you NPM version (`npm -v`)?
what command did you use to start it up?
what env vars have you set?

**Comment by SebastienGauthierSVI** [comment]
NPN Version 2.15.9

I use the same command i use for the version 0.62.0.

export ROOT_URL=https://abc.123.com/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3001
export MAIL_URL=smtp://15.150.0.6
node /Rocket.Chat/main.js

**Comment by sampaiodiego** [comment]
your npm version scares me a little bit.. the recommended version is `5.6.0`

did you run `npm install` successfully from `programs/server` folder? in your case probably `/Rocket.Chat/programs/server`

**Comment by SebastienGauthierSVI** [comment]
Yes, but i will try to update it and do the npm install again. Thx for the tips

**Comment by SebastienGauthierSVI** [comment]
Ubuntu 14.04.4 LTS, i still have the same errror with the version 0.63.1

**Comment by SebastienGauthierSVI** [comment]
I have this warning when i execute the npm install.
root@sandstorm:/Rocket.Chat/programs/server# npm install
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd %s %s (wd=%s) meteor-dev-bundle@ node npm-rebuild.js /Rocket.Chat/programs/server
up to date in 1.432s

**Comment by joogser** [comment]
I guess to resolve this issue, go 
`cd /opt/Rocket.Chat/programs/server/npm/node_modules npm rebuild sharp`

and run
`npm rebuild sharp`

I had similar problems with installation. After rebuilded npm packege, installation has gone fine.

**Comment by SebastienGauthierSVI** [comment]
Thanks a lots! that's work!
