### ISSUE TITLE
Add two factor authentication

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1034]
##

**Comment by geekgonecrazy** [comment]
I just got my new YubiKey in the mail so I might take a stab at this.  :grin:

**Comment by ninja-** [comment]
I implemented this another way. I recently did a large multi-service LDAP deployment and made the ldap server work that way so it only accepts a password of <password><your mobile token>. So 2fa across all the services :+1:

**Comment by geekgonecrazy** [comment]
That works for ldap.  For sure want this in Rocket.Chat its self

**Comment by ninja-** [comment]
sure, I am not stopping you from implementing this. Depending on 2FA implementation in each of the services used started to be annoying so that's just the solution I used.

**Comment by marceloschmidt** [comment]
+1

**Comment by Razer6** [comment]
:+1:

**Comment by stephenreda** [comment]
https://ravis.me/2014/12/02/meteor-js-two-factor-authentication/

**Comment by geekgonecrazy** [comment]
@stephenreda that looks pretty useful!  Thanks for sharing

**Comment by mmeinert** [comment]
+1

**Comment by sinteur** [comment]
+1

**Comment by djeber** [comment]
+1

**Comment by MandMDub** [comment]
Is there any upcoming progress on this? I would really love to have this feature or let me know if anyone has any temporary ways to add 2fa to rocket chat.

**Comment by sinteur** [comment]
if you use nginx you can add this: https://github.com/RobThree/TwoFactorAuth

**Comment by geekgonecrazy** [comment]
Nice.  Had never seen that before.

Also alternative would be force south provider and do two factor at that level.   Not ideal

**Comment by MandMDub** [comment]
Is there any other way or any progress of this being added to rocket chat?

**Comment by geekgonecrazy** [comment]
@MandMDub 
Not currently.  But as mentioned right above this would be the "other way"
>alternative would be force oauth provider and do two factor at that level. Not ideal

**Comment by TheReal1604** [comment]
@mandmdub Its Not ideal, like the solutions above, but you can work with client certificates too. It's some sort of 2FA. ;-)

**Comment by mmeinert** [comment]
@ninja- could you please tell me/us how you did it ?

**Comment by jszaszvari** [comment]
I wonder if this will work at the moment through the SAML provider using someone like https://duo.com 

I might give it a go.

**Comment by geekgonecrazy** [comment]
@jszaszvari i'd think it would.

**Comment by chellem** [comment]
Is there any update on this new feature?  It would be very interesting to add two factor authentication.

**Comment by sebeard** [comment]
Interested in this as well. U2F would be ideal using something like yubikey would be great!!!
