### ISSUE TITLE
French translation for Disabled

### ISSUE THREAD

**Issue by antoine-roux** [RocketChat/Rocket.Chat#10347]
### Description:
Hello,
Please fix the translation for "Disabled" in the french i18n file...

https://github.com/RocketChat/Rocket.Chat/blob/2b01cdcf8dcbaf100a75abceaf344f11cfe2df99/packages/rocketchat-i18n/i18n/fr.i18n.json#L554

"Handicapé" here means a disabled person.
The right translation should be "Désactivé"

Thanks,
Antoine

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: The Rocket.Chat Docker image one
* mongoDB Version: 3.4.1

**Comment by graywolf336** [comment]
@antoine-roux Thanks for bringing this to our attention! For now, I have created the pull request to fix the immediate issue. 

If you're willing to, we use LingoHub as the place were community members translate the various items into their respective languages. If you're willing, we could get you added the project. :)
