### ISSUE TITLE
Moving to homepage when leaving a room I am not currently viewing

### ISSUE THREAD

**Issue by mikaelmello** [RocketChat/Rocket.Chat#10357]
### Description:

Really small issue and probably not hard to fix, if no one gets interested in it I'll look at the code to fix it tomorrow.

When I am viewing a room, #general for example, and leave another room via the sidebar, #sandbox, that I am part of but am not currently viewing, confirming the action has a small delay that lasts long enough to bother and I am redirected to the homepage even though I am already in a room.

### Server Setup Information:

I am using the web client on open.rocket.chat

### Steps to Reproduce:

1. Open any room to view the messages.
2. Click on the menu of any other room that you are a member and click to leave it.

### Expected behavior:

I leave the room I wanted to leave and stay in the room I am currently viewing.

### Actual behavior:

I leave the room I wanted to leave but am redirected to the homepage

**Comment by TwizzyDizzy** [comment]
Hi @mikaelmello 

please also add the information regarding your setup that we requested in the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md).

Cheers
Thomas

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
