### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by shreekarade** [RocketChat/Rocket.Chat#10362]
**Description:**
**Server Setup Information:**
Version of Rocket.Chat Server: 0.59.4
Operating System: Linux
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
DB Replicaset Oplog:
Node Version: v4.8.4
mongoDB Version:

Expected behavior: Push notification should work for user to user chat and channel/group notification
Actual behavior: Push notification work only for user to user chat, not working for channel/group notification. Please help me.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing in favour of #10361.

Cheers
Thomas
