### ISSUE TITLE
Add "New message" text to notifications when "Show Message" is set to false

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10364]
edited by @sampaiodiego:
When `Show Message` is set to `false` under `Admin > Push > Privacy` settings, we should then add a text something like `New message` to the push notification, instead of letting it blank.

![image](https://user-images.githubusercontent.com/8591547/38433356-e350b4bc-39a0-11e8-8a77-a1556ab08d51.png)

----------------------

@allabezroutchko commented on [Fri Apr 06 2018](https://github.com/RocketChat/Rocket.Chat.iOS/issues/1501)

- Your Rocket.Chat app version: 2.1.1
- Your Rocket.Chat server version: 0.62.2
- Device (or Simulator) you're running with: iOS 11.2.6

The new message notifications on iOS lock screen do not contain the text of the message. If you tap View on the notification from lock screen, the text is still not shown. See screenshots below.

![img_0703](https://user-images.githubusercontent.com/35561893/38419077-4942226c-399f-11e8-89fe-07b2437b5caa.PNG)
![img_0704](https://user-images.githubusercontent.com/35561893/38419079-495b3c34-399f-11e8-82ab-171b8d48fa6e.PNG)

Expected behaviour: The message text is shown both in lock screen notifications and when tapping View from lock screen.

---

@rafaelks commented on [Fri Apr 06 2018](https://github.com/RocketChat/Rocket.Chat.iOS/issues/1501#issuecomment-379229431)

@allabezroutchko Thanks for the feedback! What message is that? When you open the chat, does it say something?

---

@allabezroutchko commented on [Fri Apr 06 2018](https://github.com/RocketChat/Rocket.Chat.iOS/issues/1501#issuecomment-379230778)

@rafaelks Here is what the message looks like when I open it in the app:
![img_0705](https://user-images.githubusercontent.com/35561893/38419694-ae5896de-39a1-11e8-940e-227df9887569.PNG)
This happens with all messages, not just this one. I used sysadm account to send a message to myself to make the screenshots.

---

@rafaelks commented on [Fri Apr 06 2018](https://github.com/RocketChat/Rocket.Chat.iOS/issues/1501#issuecomment-379231987)

@allabezroutchko OK, I'll move this issue to our back-end project. 👍

**Comment by rafaelks** [comment]
@allabezroutchko Questions:

1) Do you use our gateway?
2) Did you made any change on server source code?

**Comment by allabezroutchko** [comment]
1. Don't think so. What is the gateway?
2. No, we didn't change the server source code.

**Comment by allabezroutchko** [comment]
We are hosting the server ourselves

**Comment by sampaiodiego** [comment]
how is the settings for Privacy under Admin > Push?
![image](https://user-images.githubusercontent.com/8591547/38433356-e350b4bc-39a0-11e8-8a77-a1556ab08d51.png)

**Comment by allabezroutchko** [comment]
Hello @sampaiodiego , thanks. Show Message in Notification was set to false. I have changed it to true, now the messages are shown in lock screen notification.
Perhaps from UI perspective it would make sense to show <not displayed due to privacy settings> or something like that in the notification, when the option is set to false.

**Comment by sampaiodiego** [comment]
Agreed @allabezroutchko .. I'll change the issue title to reflect that.. thx

**Comment by engelgabriel** [comment]
We should use the language of the receiving user for the message.
