### ISSUE TITLE
[API] Add "value" parameter to /api/v1/chat.react

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#10370]
Currently /api/v1/chat.react works like a toggle. We call it once, it either removes or adds the reaction.

This behavior causes some difficulties when working with optimistic UI updates.

My proposal is we add a "value" parameter.

"value": true = adds the reaction (returns error if already added)
"value": false = removes the reaction (returns error if not found)
"value" not present = retains old behavior (doesn't break old API usage)

I think this would qualify as a non-breaking update to an existing API

@rafaelks @MarcosSpessatto @graywolf336 

What do you think?

**Comment by graywolf336** [comment]
As long as ensure we don't break the current implementation, I would be fine with that.

Although, this isn't a simple change because it will require some changes to how the method it internally calls works.

**Comment by rafaelks** [comment]
@cardoso I support the change, but I agree that we cannot break the current implementation. 👍

**Comment by nemaniarjun** [comment]
Seems non-breaking to me.
