### ISSUE TITLE
Profile image not shown in Directory search / URLs not consistently created for profile images

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#10386]
### Description:

The profile image is not shown correctly on our deployment. I possibly found the root cause at the construction of the profile image url´s. 

For the creation of a profile image url in the directory menu the "displayname" is used, all other functions, such as the avatars on the sidebar and in the channels using the "username" to construct the url.

For example:

A user is configured with the displayname "Max_Mustermann" and his username is "max_mustermann" the URL in the Directory search menu is generated like: 

"/avatar/Max_Mustermann?_dc=undefined"

If you look at the url in the sidebar it is generated with the username:

"/avatar/max_mustermann?_dc=undefined"

This leads in our system to not correctly displayed profile pictures in the directory menu.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu Server 16.04 LTS
* Deployment Method(snap/docker/tar/etc):  docker
* Number of Running Instances: 3

### Steps to Reproduce:

1. Create a user with different display and username
2. Go to the directory search - try to search for users - you will reckognize that there are default profile pictures are shown

### Expected behavior:

The urls to profile pictures should be consistently created with one variable over the complete application - username or displayname

### Actual behavior:

Displayname variable is used in the directory view, username is used on all other places.

**Comment by karlprieb** [comment]
Duplicated of #10115
