### ISSUE TITLE
Sidebar: Unread Label is "hardcoded" leading to wrong translations

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#10385]
### Description:

If you sort your channels like "unread on top" the label of the menu group seems to be hardcoded, which leads to wrong translations in other languages. (i.e. Label is also "Unread" if I select german as my language)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc):  docker
* Number of Running Instances: 3

### Steps to Reproduce:

1. Enable "unread channels on top"
2. Select another language as english
3. The label is wrong

Screenshot:

![image](https://user-images.githubusercontent.com/5877910/38498701-93da44c2-3c05-11e8-8ee2-4a012556f1ac.png)

### Expected behavior:

The label for the group of unread channels should be a variable so it translates correctly to the language which the users choose.

### Actual behavior:

The label is english :)

### Code:

I think this could be the section there it is hardcoded:

https://github.com/RocketChat/Rocket.Chat/blob/41bffeadbc6dd6eaa1c3b486442b1232670bb477/packages/rocketchat-lib/lib/roomTypes/unread.js#L8

**Comment by Hudell** [comment]
The code is right, but the key "Unread" is currently missing from the translation files.

**Comment by TheReal1604** [comment]
@Hudell hmph! thanks for the hint. 

Quick Fix (custom translation):

```
{
  "de": {
    "Unread": "Ungelesene Nachrichten"
  }
}
```
