### ISSUE TITLE
Keyboard pops up on Android phone when using chrome

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#10381]
Description:
When I enter a channel the cursor is put in the message box. This seems to pop up the keyboard on android phones when using chrome browser (same thing in cordova browser app) Its REALLY annoying since it then covers half the screen when all you want to do read messages first before you going to respond to anything. Always have to dismiss it.
Started when we upgraded to 0.59 server and the this is also an issue on demo.rocket.chat

This is not a Cordova issue since its happens with Chrome browser  also.

Server Setup Information:
Version of Rocket.Chat Server: 0.59 and onward
Operating System: Linux
Deployment Method(snap/docker/tar/etc): build from source
Number of Running Instances: 1

Steps to Reproduce:
Start chrome on Android enter a channel on demo.rocket.chat

Expected behavior:
see all the messages without any keyboard showing up.

Actual behavior:
Cursor is in keyboard and half the screen is covered up :(

This issue is a new version of issue #10037

**Comment by tassoevan** [comment]
Closing in favor of #13758.
