### ISSUE TITLE
Integration with Sameroom.io

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#1038]
Here's a rough list of what they're looking for in a protocol: https://sameroom.io/developers
For the reference, the easiest one they've worked with so far was Slack.

Let's get featured at: https://sameroom.io/open-a-tube

**Comment by engelgabriel** [comment]
https://sameroom.io/blog/its-not-slack-its-you/

**Comment by engelgabriel** [comment]
https://docs.google.com/document/d/1cGAwMnLPRQzoySuEX5wCXLxZypr341WMNmAXSEOXjeM/edit

**Comment by graywolf336** [comment]
This is now in progress and Sameroom.io is working on it.

**Comment by Rohlik** [comment]
This is already done I think.
https://sameroom.io/open-a-tube/signin/rocketchat

**Comment by graywolf336** [comment]
Yes indeed, thank you @Rohlik
