### ISSUE TITLE
[BUG] 0.63 REST API authentication with external OAuth services expecting Integer

### ISSUE THREAD

**Issue by zvikachu** [RocketChat/Rocket.Chat#10389]
### Description:

In the latest version of Rocket.Chat, the REST API authentication requests doesn't work with Facebook  Twitter and Google.

reference to the REST API authentication:
https://rocket.chat/docs/developer-guides/rest-api/authentication/

### Server Setup Information:

Version of Rocket.Chat Server: 0.63
Operating System: Linux Amazon AMI
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: disabled
Node Version: 8.963x64
Steps to Reproduce:

CURL command sent:
curl -H "Content-type:application/json" 
http://localhost:3000/api/v1/login 
-d '{ "serviceName": "facebook", accessToken": "hash",
"secret": "hash", "expiresIn": 200 }'

### Expected behavior:

{
"status": "success",
"data": {
"authToken": "9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq",
"userId": "aobEdbYhXfu5hkeqG"
}
}

### Actual behavior:

{
"status": "error",
"message": "Match error: Expected Integer, got "200" in field expiresIn"
}

### Solution

I was able to compile and test this successfully
Just need to change  

in packages/rocketchat-lib/server/oauth/facebook.js
```
RocketChat.registerAccessTokenService('facebook', function(options) {
	check(options, Match.ObjectIncluding({
		accessToken: String,
		secret: String,
		expiresIn: Match.Integer,
		identity: Match.Maybe(Object)
	}));
}
```

expiresIn should expect a String
same goes for google.js, twitter.js

I am using docker latest to deploy my server,
a quick fix would be much appreciated

**Comment by zvikachu** [comment]
Hi @MarcosSpessatto 
Yes this curl command runs 
but i had issues with node and php clients


```
var qs = require("querystring");
var http = require("https");

var options = {
  "method": "POST",
  "hostname": "open.rocket.chat",
  "port": null,
  "path": "/api/v1/login",
  "headers": {
    "content-type": "application/x-www-form-urlencoded",
    "cache-control": "no-cache",
    "postman-token": "654b4fd0-4818-30b4-3277-81a627357a6d"
  }
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.write(qs.stringify({ serviceName: 'facebook',
  accessToken: 'EAAc21',
  expiresIn: 5000,
  secret: 'asdasdas' }));
req.end();
```


for example, the above code will return 
```
{"status":"error","message":"Match error: Expected Integer, got \"5000\" in field expiresIn"}
```

**Comment by zvikachu** [comment]
@MarcosSpessatto Thanks, that worked

**Comment by rackmuthu** [comment]
I can able to authenticate the rocket chat user by using keycloak (from the browser)
But, I have no clear idea about how to authenticate the rocket chat user using the rocket chat rest api.

**Comment by MarcosSpessatto** [comment]
Hey @rackmuthu, here we have the docs about authentication with REST API. https://rocket.chat/docs/developer-guides/rest-api/authentication/login/#example-call---as-json
