### ISSUE TITLE
Misplace of '@' in the directory -> users page.

### ISSUE THREAD

**Issue by sumedh123** [RocketChat/Rocket.Chat#10398]
### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. Head over to the directory search for users.
2. Under the name column, before the name of the user, the "@" symbol looks weird.

### Actual behavior:

![image](https://user-images.githubusercontent.com/17925669/38551795-be7e6712-3cd7-11e8-96fe-de212f06f2dd.png)

### Expected behavior:
Instead of placing it in front of the name, it should be in front of the username in the second column.

@karlprieb What are your opinions on this one?

**Comment by karlprieb** [comment]
I get it, maybe we should change the first column to Username (with avatar, @ icon and username) and the second column should be the Name column.

@sumedh123 do you want to make a PR for that?

**Comment by sumedh123** [comment]
@karlprieb Okay I will do it.

**Comment by karlprieb** [comment]
@sumedh123 thank you! 👍
