### ISSUE TITLE
UI don't reload when you change language on user preferences

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#10392]
### Description:
When you change the UI language on user preferences the UI don't reload and you need to manually reload the page to change language.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63

### Steps to Reproduce:

1. Go to My Account, Preferences
2. Change the language
3. Click "Save changes" button

### Expected behavior:
When the user change the UI language on user preferences the UI should reload to apply the new language.

### Actual behavior:
UI don't reload when you change language and you need to reload manually.

**Comment by graywolf336** [comment]
Closing, this was fixed in v0.63.1 via #10348. Please read the release notes to understand what was changed, thanks! :)
