### ISSUE TITLE
Hubot

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#104]
Integrate with Hubot to have our version of slackbot https://hubot.github.com/

**Comment by dstollie** [comment]
@engelgabriel Im willing to help you guys with this. For SpaceTalk we need this to and it would be awesoem if we could create some easy to use  hubot package for meteor. Have guys already did something with this?

**Comment by engelgabriel** [comment]
Sounds great @dstollie we have not started any work on that yet. One of the guys that created Hubot was testing the chat the other day, and he offered to give a hand too. I'll dig his contact details from the logs.

**Comment by Sing-Li** [comment]
@engelgabriel    Count me in for this as well.  
@dstollie   Interesting idea - re: common hubot integration adapter for multiple Meteor based chats.   
I've got the basic adapter working against the current head.  See pic.   Kludgy to configure, but can be a base for everyone to dive in.

![hubotrocket](https://cloud.githubusercontent.com/assets/122633/7952972/ec3c4656-098b-11e5-91f8-f7d702cd6c7c.png)

Which branch should pull requests be made against for milestone 1.1 features?

**Comment by riaan53** [comment]
nice!!! @Sing-Li

**Comment by dstollie** [comment]
@Sing-Li Could you fork this work and push it to a branch of that fork.. Im getting really curious if I see this

**Comment by engelgabriel** [comment]
@Sing-Li WOW! That's awesome! Please submit a PR and I'll revise it straight away. Thanks!

**Comment by Sing-Li** [comment]
Thanks @riaan53 , @dstollie  and @engelgabriel  

PR #132 contains the working initial adapter, and some setup instructions.  There are several moving parts and not so easy to setup right now.

In a few days, I'll follow up with a Docker image that will make adapter development "setup free" and maybe even serves as a  deployment container for rocketchat bot instances.

Right now, this adapter requires no change in the core Rocket.Chat source code.  There is another version that I have been playing with that uses a more efficient publication dedicated to hubot integration,  we can consider that at a later stage.

@dstollie  -  using this approach, I was able to complete a 'basic' adapter for nullchat in a few hours, hopefully it will help with spacetalk integration as well.

**Comment by andela-cnnadi** [comment]
+1. Looking forward to building cool hacks with this. :+1:

**Comment by rodrigok** [comment]
Looks amazing, I hope to help soon.

**Comment by Sing-Li** [comment]
Folks, please check the https://github.com/RocketChat/hubot-rocketchat  project where the code lives.  

I've got a queued PR that catches up with all the publication & method changes in the core, so the bot will now work with the restructuring-in-progress head.   Currently, I'm testing the docker container and it should be ready by the next PR.

@rodrigok - awesome!    @andela-cnnadi  - can't wait to see your hacks (I assume they *might* be open source :)

**Comment by engelgabriel** [comment]
@Sing-Li I've just invited you to the https://github.com/orgs/RocketChat/teams/hubot-rocketchat so you can be an admin of the project too.

**Comment by Sing-Li** [comment]
@engelgabriel   Thanks!   

The docker image is ready.   Everyone can start hacking the adapter code, or launch his/her own bot within a few minutes now.  Please head over to the [hubot integration project](https://github.com/RocketChat/hubot-rocketchat)  for information.

**Comment by engelgabriel** [comment]
The initial hubot deployment is now running on our demo server... check it out!
