### ISSUE TITLE
.GIFV extension not rendering preview

### ISSUE THREAD

**Issue by vwallace** [RocketChat/Rocket.Chat#1040]
Discovered that .gifv files don't render a preview in chat. Not an earth-shattering issue, but perhaps something that could be noted for future versions. 

More about the "format": 
https://imgur.com/blog/2014/10/09/introducing-gifv/

**Comment by marceloschmidt** [comment]
It looks like gifv, when rendered on imgur, is actually rendered as webm and mp4 videos. So it seems they are converting it. Do you have a code sample where a gifv is embedded? Thanks

**Comment by graywolf336** [comment]
From the linked article, it looks like they are just converting it to webm and mp4 videos. So, we'd need to grab one of those and display that. If the url is `http://i.imgur.com/zvATqgs.gifv` then the webm link is `http://i.imgur.com/zvATqgs.webm` and the mp4 link is `http://i.imgur.com/zvATqgs.mp4`, same unique image but different extension.

**Comment by vwallace** [comment]
It also seems stripping the v from .gifv serves a "normal" gif - perhaps could just parse the .gifv for the preview?

https://i.imgur.com/F4XcrVK.gifv
vs
https://i.imgur.com/F4XcrVK.gif

**Comment by graywolf336** [comment]
That could work, only issue I see with it is for large gifs the downloading file size will be large compared to webm or mp4's being a lot smaller.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/1198
