### ISSUE TITLE
Users lose access to private rooms

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#1041]
Not sure if this could be related to https://github.com/RocketChat/Rocket.Chat/issues/966 but some people are reporting that private groups they've created have now disappeared. Happy to jump on chat if someone is around to try and diagnose today.

**Comment by mhkeller** [comment]
It seems that the room exists but it no longer has the same users. So perhaps it's a permissions-changing errro

**Comment by mhkeller** [comment]
And by "doesn't have the same users," I mean that people who were members, including the creator, lost permission to access the group.

**Comment by marceloschmidt** [comment]
Permission changing? What do you mean with that, are you fiddling with the code regarding this, or are you suggesting that an update has made those rooms inaccessible? Is this reproducible? Thanks

**Comment by mhkeller** [comment]
Nope I haven't changed the code. What happened was a user made a private group and invited others. They then opened up a different channel and the private room disappeared from their list of accessible rooms. This happened to the creator of the room as well so no one now has access to re-invite people.

I'll be on chat to be able to provide more info if I can look in the logs somewhere.

**Comment by geekgonecrazy** [comment]
@mhkeller does this still happen?  We haven't received any reports of this since.  Please re-open if you're still experiencing it.

**Comment by mhkeller** [comment]
The company I was implementing it as has since shut down so if no one else is experiencing then seems safe to close.

**Comment by Sys-Admin992** [comment]
I think that I have a same problem here, I lost a many rooms it completely disappeared and I can't find them anywhere
