### ISSUE TITLE
Do not close search sidebar on idle timeout

### ISSUE THREAD

**Issue by kurji** [RocketChat/Rocket.Chat#10415]
### Description:

There seem to be two related issues:
1. The search sidebar closes on idle timeout
2. The user interface for Idle Time Limit does not specify the unit in which the timeout is being configured

The combination of these made for a very vexing issue that took a long time to isolate, where the search sidebar was totally unusable due to constantly closing every few milliseconds, making it impossible to search for and contact someone.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu 16.04 LTS  (4.4.0-119-generic)
* Deployment Method(snap/docker/tar/etc): SNAP
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled?
* Node Version: v8.9.4
* mongoDB Version: v3.2.7

### Client Binary

* Rocket.Chat+ Version 2.10.5
* Windows 7 Professional x64 Service Pack 1

### Steps to Reproduce:

1. Adjust the automatic-away idle time limit to something really low:
My Account → Preferences → USER PRESENCE → Idle Time Limit: 300
2. Go back to normal messaging, then press the magnifying glass "Search" button to bring up the Search sidebar.
3. Observe that in 300 milliseconds or less, the search bar closes, making it unusable for searching.

### Expected behavior:

The search sidebar does not close.
The Idle Time Limit specifies the unit of time.

### Actual behavior:

The search sidebar closes too quickly for usability.
The Idle Time Limit does not specify the unit of time.

**Comment by graywolf336** [comment]
The last half of that will be fixed when #9824 is merged on the next release. :)
