### ISSUE TITLE
"Collapse Embedded Media by Default" Preference Breaks Relplies

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#10424]
### Description:

When the user preference `Collapse Embedded Media by Default` it makes text attachments closed, with no way to open it.

<img width="435" alt="screen shot 2018-04-11 at 11 30 16 am" src="https://user-images.githubusercontent.com/20868078/38623318-beb760cc-3d7b-11e8-8508-74d451327bd7.png">

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Tested on open server

**Comment by c0dzilla** [comment]
@MartinSchoeler please have a look at #10427 . Thanks :)
