### ISSUE TITLE
Editing user is not possible

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#10425]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Debian 8
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3. 

### Expected behavior:

To edit a user and save the relevant change(s).

### Actual behavior:

A message appears which tells me: ``assign_role_not_allowed``.

**Comment by theorenck** [comment]
hi @k0nsl can you give us more context on the problem? Can you send a print screen showing us the problem?

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
