### ISSUE TITLE
Chat is very slow

### ISSUE THREAD

**Issue by matheus666matheus** [RocketChat/Rocket.Chat#10429]
My Rocket Chat instance is very low....takes on average 20 seconds to send a simple message. I followed the centos manual installation procedure in the guide correctly.  What could be causing this slowness?

* Version of Rocket.Chat Server:  0.63.1
* Operating System: CentOS 7 
* Number of Running Instances: 1 
* DB Replicaset Oplog: no replicaset
* Node Version: 8.9.3
* mongoDB Version:  the latest one

**Comment by TwizzyDizzy** [comment]
Hi @matheus666matheus 

I don't see how anybody could help you on the basis of the information you provided. This is just too broad and there could be billions of possible reasons for what you're seeing.

So as long as you don't add anything more precise this is nothing we can help you with. Also: please add your deployment method.

Cheers
Thomas

**Comment by matheus666matheus** [comment]
Hi @TwizzyDizzy, thanks for replying,

I know it was not very specific, sorry...but I can't get no useful information, was expecting a common cause for this kind of slowness, or something like that. I followed strictly the guide, the only odd thing that happened to me when I was installing was this warning, when I ran 'node install':

npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/opt/Rocket.Chat/programs/server)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I'm closing this issue (see my first reply), but let me refer you to the community support forum: https://forums.rocket.chat/c/community-support

If it turns out over there, that there is an actual **bug** involved I'm happy to reopen the issue at hand.

Cheers
Thomas
