### ISSUE TITLE
[BUG] "Message_AllowedMaxSize" not working as expected with messages containing emoji unicode sequences

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#10422]
If "Message_AllowedMaxSize" = 10

This message will be rejected: "123456789👨‍👨‍👧‍👦"

**Comment by c0dzilla** [comment]
This is actually expected behaviour. @sampaiodiego is it desirable to not include emojis while deciding the message size setting?

**Comment by cardoso** [comment]
@c0dzilla expected but wrong, IMO. It makes sense from a developer perspective, but not from a user perspective.

**Comment by c0dzilla** [comment]
Yes, I agree its not desirable for the user.
