### ISSUE TITLE
/rest-api/users/register/ timeout

### ISSUE THREAD

**Issue by mahtsche** [RocketChat/Rocket.Chat#10433]
**Operating System** (Docker-Compose file form official documentation):
https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml
* **Browser**: Version 65.0.3325.181 (Developer Build) (64-bit)
* **Rocket.Chat Version**: 0.63.1
* **Expected behavior**: Like the description of users.register from the RestApi: https://rocket.chat/docs/developer-guides/rest-api/users/register/
* **Actual Behavior**:

from CLI:

After Call:
```bash
$curl --request POST \
  --url http://localhost:3000/api/v1/users.register \
  --header 'content-type: application/json' \
  --data '{
	"username": "rogersmith",
	"email": "rogersmith@example.com",
	"pass": "rogersmith",
	"name": "rogersmith"
}'
```
Response:
```bash
curl: (52) Empty reply from server
```
* Can the bug consistently be **reproduced**: yes

**Comment by mahtsche** [comment]
solved

was caused by wrong 
- MAIL_URL=smtp://smtp.email
in compose file

**Comment by 564064202** [comment]
> * MAIL_URL=smtp://smtp.email
>   in compose file

sir ,we don't use the MAIL_URL,but how to resolve it?
