### ISSUE TITLE
Can we support WebRTC in cordova iOS app?

### ISSUE THREAD

**Issue by steedos** [RocketChat/Rocket.Chat#1043]
There is a plugin iosrtc

https://github.com/eface2face/cordova-plugin-iosrtc/

**Comment by steedos** [comment]
There is a sample https://github.com/eface2face/iOSRTCApp

**Comment by marceloschmidt** [comment]
This is our repository for Cordova platform: https://github.com/RocketChat/Rocket.Chat.Cordova please the issue there, or make a PR and we'll be glad to accept that!
Thanks.

**Comment by anappleapp** [comment]
Hi @steedos , 

I download the plugin in Rocket.chat Cordova but it doesnt work.. 
Did you find some solution, Thanks in advance.
