### ISSUE TITLE
Snap installation fails (unable to Mount snap "core") (Ubuntu 16.04)

### ISSUE THREAD

**Issue by mayeaux** [RocketChat/Rocket.Chat#10440]
```
error: cannot perform the following tasks:
- Mount snap "core" (4407) ([start snap-core-4407.mount] failed with exit status 1: Job for snap-core-4407.mount failed. See "systemctl status snap-core-4407.mount" and "journalctl -xe" for details.
)
```

Anyone seen this before?

**Comment by kaiiiiiiiii** [comment]
Hi @mayeaux,

please use the issue template (the auto filled text when you open an issue) for your request, otherwise this issue will be closed soon.

It’s hard to give any support with such less information.

Thanks,
Kai

**Comment by mayeaux** [comment]
It seems my Linux kernel is custom and can't support squashfs
