### ISSUE TITLE
Suggestion for package testing approach

### ISSUE THREAD

**Issue by gmsecrieru** [RocketChat/Rocket.Chat#1044]
Now that we are starting to add tests, we need to make sure that we can:

1. Test packages as standalone, single units.
2. Test the application as a whole.

Package-specific tests should be placed within `packages/package-name/tests` and should follow [velocity+jasmine conventions](https://velocity.readme.io/v1.0/docs/jasmine-testing-modes).

_Example of package testing_ (Velocity's Continuous Integration mode)
`VELOCITY_TEST_PACKAGES=1 meteor test-packages rocketchat:lib --driver-package velocity:console-reporter --velocity`
![screen shot 2015-10-08 at 12 34 41](https://cloud.githubusercontent.com/assets/190883/10371289/03282d76-6db9-11e5-9acd-861556844431.png)

**Comment by gmsecrieru** [comment]
Recommended sources:

[Getting started with Velocity](https://velocity.readme.io/)
[Getting started with Jasmine](https://velocity.readme.io/v1.0/docs/getting-started-with-jasmine)
[Package Testing](https://velocity.readme.io/docs/jasmine-testing-a-meteor-package)
[Jasmine Testing Modes](https://velocity.readme.io/v1.0/docs/jasmine-testing-modes)
[Examples and Tutorials](https://velocity.readme.io/v1.0/docs/jasmine-examples-tutorials)

**Comment by kakawait** [comment]
Good point last day I pushed #1160 and when I started the PR I was thinking to used package testing approach. But I saw that is not used on RocketChat, I rollback to application testing approach.

May be a good candidate for package testing approach?

**Comment by gmsecrieru** [comment]
@kakawait I have some work related to this on [standalone-package-testing](https://github.com/RocketChat/Rocket.Chat/tree/standalone-package-testing) branch. I was trying to set up our CI build tests for both packages and app, but I could only make it work for packages -- see #1045. 

If you take a look at the latest [build info](https://travis-ci.org/RocketChat/Rocket.Chat/builds/86495483) from this request, you will see some of the package tests running and passing, but when running `velocity test-app --ci` it breaks.

Feel free to jump in so we can put this to work! =)
