### ISSUE TITLE
2FA Not showing backup codes due to translation

### ISSUE THREAD

**Issue by droberin** [RocketChat/Rocket.Chat#10455]
### Description:

Can't get 2FA backup codes due to language translation but you get a translated variable/placeholder_to_be_replaced that shoudn't be replaced instead.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu (probably trivial)
* Deployment Method(snap/docker/tar/etc): docker  
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4 - x64
* mongoDB Version: 3.0 (docker)

### Steps to Reproduce:

1.Login
2.Set language to Spanish
3. Activate 2FA

### Expected behavior:
Get backup codes
 
### Actual behavior:
Get a message saying "__códigos__" instead of the codes. Probably someone did translate this not-to-translate word in the process (__codes__).

**Comment by droberin** [comment]
Update: also reported to translations contact address supplied into this project website. Issue probably fixed by now and will be available in next release).

P.S.: One of the automated tests could be to check all variables/replacements where still into translations.

**Comment by RavenSystem** [comment]
On version 3.1.1, codes are not showed:

<img width="747" alt="Captura de pantalla 2020-04-21 a las 12 03 05" src="https://user-images.githubusercontent.com/8655274/79853330-312dbb80-83c8-11ea-91b8-949177285ed7.png">
