### ISSUE TITLE
Failed update v0.63.1

### ISSUE THREAD

**Issue by ivangerasimov39** [RocketChat/Rocket.Chat#10452]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 8.11.1
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1.  download archive
2.  extract files
3.  go to <install_folders>/programs/server
4.  run npm install

### Expected behavior:

install successful
### Actual behavior:

error
![image](https://user-images.githubusercontent.com/29921722/38767981-4dd8be50-3fec-11e8-8673-4be6a76b0984.png)
[2018-04-14T11_53_01_390Z-debug.log](https://github.com/RocketChat/Rocket.Chat/files/1910343/2018-04-14T11_53_01_390Z-debug.log)

**Comment by TwizzyDizzy** [comment]
Hi @ivangerasimov39 

would you do me the favour of verifying this against #9368 to make sure this is, in fact, no duplicate issue? :)

Cheers
Thomas

**Comment by ivangerasimov39** [comment]
#9368 - Yes
`npm -f i fibers@2.0.0` - this helped

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Thanks! :) Closing this then...

Cheers
Thomas
