### ISSUE TITLE
REQUEST : Incoming SMS Routing to Different Location

### ISSUE THREAD

**Issue by izodzim** [RocketChat/Rocket.Chat#10450]
We have a general company phone number that's SMS enabled, as well as direct-dial numbers for agents.  I would like to be able to direct SMS to/from the direct dial numbers just to that agent.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @izodzim

Let me kibdly redirect you to the [feature requests category](https://forums.rocket.chat/c/feature-requests) in the forums, as we reserve Github for bugs only :)

Cheers
Thomas
