### ISSUE TITLE
Apps can’t connect/login to subfolder RC instance

### ISSUE THREAD

**Issue by panki27** [RocketChat/Rocket.Chat#10467]
### Description:
Because there’s already a website running on Apache with a valid Let’s Encrypt certificate, I opted to use the subdirectory installation. https://domain.com/chat/
 Everything is working fine in browser and Windows desktop client, but the native Android App fails to login with an error message stating "chat.rocket.android_ddp.DDPClientCallback$Closed". The iOS app does nothing when I enter the site address.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): tar (manual installation)
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 8.9.3
* mongoDB Version: 2.6.10

### Steps to Reproduce:

1. Install Rocket.Chat according to the Manual Install guide for Ubuntu.
2. Configure SSL Reverse Proxy like in the docs
3. Try to login in the native Android app.

### Expected behavior:
Android: The app logs in and allows you to chat.
iOS: The login screen appears.

### Actual behavior:
Android: Unhelpful error message (__chat.rocket.android_ddp.DDPClientCallback$Closed__), then nothing
iOS: Upon entering the URL and hitting the button, nothing happens.

### Relevant logs:
The server doesn't log anything.
My browser shows a few errors, but I don't think they're relevant:
```
/api/v1/commands.list Failed to load resource: the server responded with a status of 404 (Not Found)
2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:183 Uncaught (in promise) Error: Not Found
    at Object.e [as error] (2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:183)
    at l (2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:9)
    at Object.fireWith [as rejectWith] (2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:9)
    at S (2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:9)
    at XMLHttpRequest.<anonymous> (2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:9)
/chat/sockjs/info?cb=ezu4h_17v7 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
/chat/sockjs/info?cb=3lv7903v0e Failed to load resource: the server responded with a status of 503 (Service Unavailable)
/chat/sockjs/info?cb=l4r6z14503 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
```

Here is my apache2 conf:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName www.domain.com
    ServerAlias domain.com *.domain.com
    ServerAdmin mail@domain.com
    UseCanonicalName On
    DocumentRoot /var/www/domain

    <a few Directory tags>

    <Location /chat>
        Order allow,deny
        Allow from all

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /var/www/domain/(.*)           ws://localhost:3000/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /var/www/domain/(.*)           http://localhost:3000/$1 [P,L]
        ProxyPassReverse http://localhost:3000
    </Location>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLCertificateFile /etc/letsencrypt/live/domain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/domain.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/domain.com/chain.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

Thanks in advance.

**Comment by Andyyyyy94** [comment]
Experiencing exact same issue with ~same server setup. plz help
Many thanks and props for this masterpiece of software!

**Comment by rafaelks** [comment]
Can you guy send me the URL of your server?
