### ISSUE TITLE
Remove emoji dependence on cdn

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1046]
Right now emojione pulls from //cdn.jsdelivr.net/emojione/assets/png/

**Comment by jimaek** [comment]
If you have any issues or requests regarding jsDelivr just let me know

**Comment by geekgonecrazy** [comment]
@jimaek jsDelivr seems solid.  We'd just like to not depend on external resources.  So that we can be deployed in any environment.

**Comment by jimaek** [comment]
Sure thing, I understand. For performance reasons you could also make it an option in the config. Enable CDN or not.

Anyway, just wanted to make sure you had no issues using jsDelivr :)

Continue the great work :+1:

**Comment by steedos** [comment]
I've done with it, check pull request  #1047

**Comment by steedos** [comment]
To make it an option in the config, i'm not good at it. maybe someone can help.

**Comment by Ribeiro** [comment]
Wouldn´t be better use npm to install and manage emojione frontend dependency automatically?

**Comment by steedos** [comment]
the current package does not include pngs in client
https://github.com/qnub/emojione/blob/master/package.js

**Comment by Ribeiro** [comment]
@steedos What a shame  =(

**Comment by engelgabriel** [comment]
We are using the official package now!

So maybe have a flag to use the Sprites inside the package?
https://github.com/Ranks/emojione/tree/master/assets/sprites

It would be automatically update as a package asset, and no need to care about feature releases.

**Comment by engelgabriel** [comment]
The EmojiOne team seem to be supportive of this idea:
https://github.com/Ranks/emojione/issues/142#issuecomment-157622974

**Comment by engelgabriel** [comment]
We already have the following options available to change the image paths and to use SVGs or SVG sprites. Let's make the Meteor package accept this to be set at run time, and create admin panel settings for this?

```js
    ns.imagePathPNG = '//cdn.jsdelivr.net/emojione/assets/png/';
    ns.imagePathSVG = '//cdn.jsdelivr.net/emojione/assets/svg/';
    ns.imagePathSVGSprites = './../assets/sprites/emojione.sprites.svg';
    ns.imageType = 'png'; // or svg
    ns.sprites = false; // if this is true then sprite markup will be used 
                        // if SVG image type is set then you 
                        // must include the SVG sprite file locally
```

GIven the file size of the SVG sprite, I'd only turn add the PNG file to the assets folder by default. 

We can create environment variable like
```sh
EMOJIONE_ADD_SVG_SPRITES = false
EMOJIONE_ADD_PNG_SPRITES = true
```
To control the meteor build behaviour on the `package.js`
