### ISSUE TITLE
Long loads and room history temporarily disappears

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#10466]
### Description:

Having loading problems on open.rocket.chat for about the last 2 weeks. Getting much worse today.
Unusable for me right now, I had to go into incognito just to continue a chat.

The result of numerous logged errors is that it takes about 10 seconds to load a channel, then I can't see any messages. Previously I was able to reload a couple times and it would return to normal, but not anymore.

I recognise some errors, I don't know if they're the critical ones, but I think a couple might be due to my chrome extensions blocking google ads and facebook requests. These should not be experience breaking requirements of the client load. I don't experience any such issues outside Rocket.Chat.

Other than those there's others I can't make sense of. 

I have tried `RocketChat.CachedCollectionManager.clearAllCache()` but it did nothing.

### Server Setup Information:

* Version of Rocket.Chat Server: open.rocket.chat
* Operating System: os x 10.13.4

### Steps to Reproduce:

- Load rooms
- Use emoji picker
- Open profile settings

All of the above lead to random occurrences of empty components.

### Relevant logs:

```
Navigated to https://open.rocket.chat/channel/contributors
contributors:1 Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://open.rocket.chat/packages/rocketchat_theme/client/vendor/fontello/font/fontello.woff2?9377982
VM843:1 GET https://connect.facebook.net/en_US/fbevents.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ VM843:1
(anonymous) @ VM843:1
(anonymous) @ gtm.js?id=GTM-MLJ76N:27
(anonymous) @ gtm.js?id=GTM-MLJ76N:28
c @ gtm.js?id=GTM-MLJ76N:30
Uf @ gtm.js?id=GTM-MLJ76N:52
(anonymous) @ gtm.js?id=GTM-MLJ76N:113
xl @ gtm.js?id=GTM-MLJ76N:107
Kg @ gtm.js?id=GTM-MLJ76N:121
Xg @ gtm.js?id=GTM-MLJ76N:68
Yg @ gtm.js?id=GTM-MLJ76N:68
setTimeout (async)
w @ gtm.js?id=GTM-MLJ76N:55
Zg @ gtm.js?id=GTM-MLJ76N:69
Ol.Dc @ gtm.js?id=GTM-MLJ76N:123
(anonymous) @ gtm.js?id=GTM-MLJ76N:123
(anonymous) @ gtm.js?id=GTM-MLJ76N:124
502c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:1 Exception in queued task: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at f._DOMRange.t.detach (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:87:5764)
    at f._DOMRange.t.setMembers (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:87:5026)
    at f._DOMRange.t.addMember (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:87:6166)
    at https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:87:29210
    at Object.e.nonreactive (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:43:4492)
    at Object.addedAt (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:87:28834)
    at Object.addedAt (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:81:2662)
    at e.addedBefore (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:45:32010)
    at Object.addedBefore (https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:45:26315)
    at https://open.rocket.chat/2c66f1b2c11ab5db28f263854a5b4f93e31476ec.js?meteor_js_resource=true:45:17106 undefined
www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-63218225-1&cid=1972448553.1522850061&jid=96394072&_v=j66&z=1814500003:1 GET https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-63218225-1&cid=1972448553.1522850061&jid=96394072&_v=j66&z=1814500003 net::ERR_BLOCKED_BY_CLIENT
Image (async)
ta @ VM841 analytics.js:2
wc @ VM841 analytics.js:9
ba @ VM841 analytics.js:9
Sa @ VM841 analytics.js:14
Ha.D @ VM841 analytics.js:12
pc.send @ VM841 analytics.js:48
X.b.(anonymous function) @ VM841 analytics.js:25
Z.v @ VM841 analytics.js:55
Z.D @ VM841 analytics.js:54
N @ VM841 analytics.js:55
d @ gtm.js?id=GTM-MLJ76N:114
_ua @ gtm.js?id=GTM-MLJ76N:118
Uf @ gtm.js?id=GTM-MLJ76N:52
(anonymous) @ gtm.js?id=GTM-MLJ76N:113
xl @ gtm.js?id=GTM-MLJ76N:107
Kg @ gtm.js?id=GTM-MLJ76N:121
Xg @ gtm.js?id=GTM-MLJ76N:68
Yg @ gtm.js?id=GTM-MLJ76N:68
setTimeout (async)
w @ gtm.js?id=GTM-MLJ76N:55
Zg @ gtm.js?id=GTM-MLJ76N:69
Ol.Dc @ gtm.js?id=GTM-MLJ76N:123
(anonymous) @ gtm.js?id=GTM-MLJ76N:123
(anonymous) @ gtm.js?id=GTM-MLJ76N:124
```

<img width="1392" alt="screenshot 2018-04-16 20 40 07" src="https://user-images.githubusercontent.com/1774379/38804657-84389652-41b6-11e8-9d93-5b6ffea3ddd5.png">
<img width="1392" alt="screenshot 2018-04-16 20 40 24" src="https://user-images.githubusercontent.com/1774379/38804658-846e542c-41b6-11e8-85fb-f4709a1cb9f5.png">
<img width="1392" alt="screenshot 2018-04-16 20 40 32" src="https://user-images.githubusercontent.com/1774379/38804659-84a49d66-41b6-11e8-8317-8dfa1a3a52ef.png">

**Comment by timkinnane** [comment]
Still happening but only in my main laptop chrome, another laptop with same OS and chrome plugins has no problem. I have a suspicion it's effecting only users who run their own local instances. Perhaps there's something added to the browser store from my dev rocket.chat that conflicts with the open server.

When I last got a room with disappeared message, I had 50 of these errors:

```
Exception in queued task: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

That's from view renderer functions, but hard to tell where exactly because it's a minified file.

**Comment by timkinnane** [comment]
The nightmare continues...

![screenshot 2018-04-30 15 28 36](https://user-images.githubusercontent.com/1774379/39415905-b9b2ae64-4c8b-11e8-9884-acec4527ad87.png)

I'm also occasionally getting a `Gateway Timeout` and nothing loads at all.

**Comment by timkinnane** [comment]
@geekgonecrazy - Could this all be due to latency? Is it possible there's some crucial oversights in async requests that break the UI if resources aren't returned on time. Ideally, I would expect a good experience without latency issues, but for some users they're probably inevitable, so the front-end should at least render properly, even if slowly.

I'm not sure how seriously these concerns are being taken. Consider that someone who isn't a dedicated member of the community has this experience when evaluating Rocket.Chat. Would they bother creating an issue and posting logs, or just silently walk away assuming the product is fundamentally broken.

I don't want to complain, but I feel compelled to represent the problems because for every one of me, there could be dozens of those that don't bother.

**Comment by geekgonecrazy** [comment]
We definitely have been aware of some issue related to this. And working to improve. We have had a few of us experiencing this.  But, usually not as bad as your case.

Has it gotten any better?

If not can you show timing in network tab?  Would be great to see more.

Sorry for delay there is a lot of noise here on this repo, hard to find time to read them all.  The forum is a bit less noisy.

**Comment by geekgonecrazy** [comment]
Haven’t seen reports of this in a while.  Let me know if still relevant and will reopen
