### ISSUE TITLE
cant make use of å ä ö (swedish characters) in channel names

### ISSUE THREAD

**Issue by OriginMayo** [RocketChat/Rocket.Chat#10469]
### Server Setup Information:

* Version of Rocket.Chat Server: latest at current time/date
* Operating System: ubuntu 17.10
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: latest att curent date
* Node Version: latest at current cdate
* mongoDB Version: latest at curent date

### Steps to Reproduce:

1. create channel
2. input channel name with swedish character Å/Ä/Ö
3. input channel name with uppercase

### Expected behavior:

when i write a swedish character such as Å or ä or ö i want them to show up

### Actual behavior:

unable to make use of å/ä/ö in channel names.
unable to make use of uppercase in channel names without going into admin page/rooms/edit room info

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

There is an admin option to enable the use of "Special Characters" in room names. Please have look in the admin settings section. For details, please see this thread: https://forums.rocket.chat/t/unable-to-use-capital-letters-in-rocket-chat/188

Cheers
Thomas

**Comment by OriginMayo** [comment]
"%s är inte ett giltigt rumsnamn"

so it does not work

@rocket-cat open
