### ISSUE TITLE
Compact display mode doesn't work anymore

### ISSUE THREAD

**Issue by maethor** [RocketChat/Rocket.Chat#10464]
### Description:

Compact display mode doesn't seem to work in chat anymore.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Debian 9.4
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: 8.9.4
* mongoDB Version: 3.2.11

### Steps to Reproduce:

1. In the top left, Display mode -> Condensed

### Expectedd behavior:

Condense the chat. Display messages on the same line as nickname and date. It was working in 0.59.

### Actual behavior:

Condense the left menu, but not the chat.

### Relevant logs:

I can't see anything relevant in the log.

It my be useful to know I just upgraded from 0.59 directly to 0.63, so I don't known when this bug has been introduce.

**Comment by maethor** [comment]
Closing. I finally find this issue as already been reported #10326

**Comment by graywolf336** [comment]
Closing due to the above comment. :)
