### ISSUE TITLE
I am unable to activate new users.

### ISSUE THREAD

**Issue by OriginMayo** [RocketChat/Rocket.Chat#10465]
### Description:

unable to activate new users

### Server Setup Information:

* Version of Rocket.Chat Server: latest
* Operating System: ubuntu 17.10
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: null
* Node Version: latest

### Steps to Reproduce:

1. user registers
2. admin verifies user
3. user is not activated

### Expected behavior:

admin verifies user and user gets activated

### Actual behavior:

admin verifies user and user does not get activated

**Comment by Hudell** [comment]
I wonder if this may be related to #10149

**Comment by OriginMayo** [comment]
He appears to be using email for verification - i dont, but the end result seems to be very identical

**Comment by OriginMayo** [comment]
solved it!

**Comment by Hudell** [comment]
What was the problem?

**Comment by redbasecap** [comment]
Yes you need to press the 3 dots and scroll down. I seared very long. @Hudell 
Eventually make i more viewable :) 

<img width="510" alt="Screenshot 2022-11-24 at 20 24 17" src="https://user-images.githubusercontent.com/41212950/203795037-538b6e90-9789-41e6-a2a4-76f8fb6ff2eb.png">
