### ISSUE TITLE
Rocket Chat Api

### ISSUE THREAD

**Issue by lakhandewnani** [RocketChat/Rocket.Chat#10468]
Hi Team ,

I am new to Rocket Chat application . Our Requirement is to integrate Rocket Chat with our existing Ios/ Android app. For this purpose I want to use the existing Rocket Chat API's.

But the Nodejs code for Rocket Chat that I have downloaded from GitHub doesn't contains code for API's . Could you please suggest that where I could find this code or any other work arround for this solution.

I have using Node version from the Rocket Chat installation steps.

Regards ,
Lakhan Dewnani

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Please refer to: https://rocket.chat/docs/developer-guides/

In case that's not enough, consider asking in the forums please, as we reserver Github for bugs only: https://forums.rocket.chat/c/community-support

Cheers
Thomas
