### ISSUE TITLE
Text format for messages mostly undocumented?

### ISSUE THREAD

**Issue by danchr** [RocketChat/Rocket.Chat#10478]
### Description:

Rocket Chat supports all sorts of nice formatting for messages. I wanted to tell some colleagues about this, and expected the RC docs to explain this.

### Steps to Reproduce:

1. Go to the [message docs](https://rocket.chat/docs/user-guides/messaging/).
2. Look for help on formatting.
3. Do a web search for “Rocket Chat message formatting”.

### Expected behavior:

I'd expect the official docs to describe the message formatting. For example, how to make text bold, insert code and so on…

### Actual behavior:

The documentation appears oddly silent in this area. Instead, the web search points to [documentation by Rocket Chat Launcher](https://support.rocketchatlauncher.com/knowledge-base/formatting-messages/), which appears pertinent and actually works.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hey @danchr 

while you are correct, it would be better to open this issue here: https://github.com/RocketChat/docs/

Thank you! :)

Cheers
Thomas

**Comment by bbrendon** [comment]
Did this get any love? I'm looking for Message formatting info.

**Comment by dannysauer** [comment]
RocketChat/docs#971

**Comment by DesktopMasters** [comment]
The links I have found seem to be related to the website and wiki but NOT the app.   Two years later you still have lost soles wanting to format their messages with no clue how.  

https://sourceforge.net/p/rocketchatcore/wiki/markdown_syntax/
https://docs.rocket.chat/contributors/contributing/documentation/markdown-styleguide

Is there an official document that explains how to format text in Rocket.Chat messages yet?

**Comment by awunder** [comment]
so, all styles are basically gone.. the markdown syntax doesnt work anymore, just basic underline, strike through, bold, italic.. what a shame..

its basically impossible now to post a table without it to look shit

**Comment by BurstX** [comment]
Almost none of the links from [this comment](https://github.com/RocketChat/Rocket.Chat/issues/10478#issuecomment-736803077) are alive
