### ISSUE TITLE
Cannot read property 'width' of null - rocketchat_file-upload.js

### ISSUE THREAD

**Issue by xbolshe** [RocketChat/Rocket.Chat#10483]
RocketChat stops a database initial data creation with an exception like:

15:46:53 Exception in callback of async function: TypeError: Cannot read property 'width' of null
15:46:53     at s.metadata.Meteor.bindEnvironment (/some/path/bundle/programs/server/packages/rocketchat_file-upload.js:351:70)
15:46:53     at runWithEnvironment (packages/meteor.js:1238:24)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-develop
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): manual compilation and launch
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9
* mongoDB Version: 2.6

### Steps to Reproduce:

1. Reset mongo database
2. Run RocketChat
3. During database initialization there is an error shown above, no ADMIN account was added to database.

### Expected behavior:

A database initialization is performed fully and without error message.

### Actual behavior:

Not all database data is initialized.

It seems that a problem was started after some commits near with 0.64.0-develop.

**Comment by TheReal1604** [comment]
@xbolshe Also can reproduce the error with LDAP Sync - the sync is interrupted with this error message. (Possibly at importing some avatar)
