### ISSUE TITLE
[BUG] Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10484]
Refer to this issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/1023.

Discussion internal points to the error in our dev channel.

**Comment by graywolf336** [comment]
The commit https://github.com/RocketChat/Rocket.Chat/commit/4834deff0da02e9f34fe647b38cc9a2571894a39 added an option to the `findChannelByIdOrName` function which removes the `usernames` from the returned result unless explicitly stated to return it. However, when this was added it did not explicitly state to do so in the `channel.messages` endpoint and checks if a person has access to a channel or not. https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/channels.js#L522

Solution: add the `returnUsernames: true` to the call.

**Comment by sjk303** [comment]
Has this fix been pushed out to 0.63.1 yet? This issue just popped up for us this morning with the release of the new app in the google play store.

**Comment by rafaelks** [comment]
@sjk303 Not yet.

**Comment by graywolf336** [comment]
Rocket.Chat v0.63.3 is out now which includes the fix for this: https://github.com/RocketChat/Rocket.Chat/releases/tag/0.63.3
