### ISSUE TITLE
sometimes it will miss the fname field when calling the method of subscriptions/get from Android/iOS

### ISSUE THREAD

**Issue by edisonchen1985** [RocketChat/Rocket.Chat#10489]
Dear all, we are a Chinese company using the Rocket.Chat for the internal communication, in order for better understanding, we have been using the fname field to display the Chinese name for the channel/private group (the name field is for channel/private group' English name).

But on the Android/iOS native application, it can not receive the fname field for some channel/private group, which only has the name field (so some are displaying with English, some are displaying with Chinese).

We have checked the codes, assuming it should be the file of server/publications/subscriptions.js, and inside it looks like the fields have been including both name and fname, but can not figure out why sometimes it will only return name field. 

Also we find some codes at the bottom of this file as below, so is it something you have solved this issue , or can you please tell how to solve this problem. Thanks you a lot in advance!

`// TODO needs improvement
// We are sending the record again cuz any update on subscription will send the record without the fname (join)
// Then we need to sent it again listening to the join event.
RocketChat.models.Subscriptions.on('join:fname:inserted', function(subscription/*, user*/) {
	RocketChat.Notifications.notifyUserInThisInstance(subscription.u._id, 'subscriptions-changed', 'changed', RocketChat.models.Subscriptions.processQueryOptionsOnResult(subscription, {
		fields
	}));
});`

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
