### ISSUE TITLE
"Store last message" default breaks Android native 2.x

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#10490]
Please see https://github.com/RocketChat/Rocket.Chat.Android/issues/1100. I believe that the "store last message" default being set to false, will create a bad UX for Android users from here on in. I'd even suggest setting it to true in a future upgrade migration. WDYT?

**Comment by rafaelks** [comment]
I agree with @antgel. This feature as "false" is a very bad experience on the Android app today (and iOS in the future, with the new layout).

**Comment by markwooff** [comment]
Agreed the setting should be "true" by default, this has caused a lot of confusion for our Android users. At first glance, it appears as if all their conversations have been lost.
