### ISSUE TITLE
Android app continuously reconnects

### ISSUE THREAD

**Issue by shemsargent-rvtd** [RocketChat/Rocket.Chat#10499]
### Description:
Rocket.Chat Android app connects to our server but continuously reconnects. 

### Server Setup Information:
* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.11.1
* mongoDB Version: rocketchat-server.mongo 3.2.7 

### Steps to Reproduce:
1. Install Android app
2. Connect to our Rocket.Chat server url

### Expected behavior:
Normal app behavior

### Actual behavior:
Normal app behavior plus message "connecting in x seconds" that counts down and then restarts at 30 seconds. Image attached: 
![image](https://user-images.githubusercontent.com/11788279/38950737-51528824-42fb-11e8-9c0e-1390a21e0357.png)

### Relevant logs:
Unknown

**Comment by graywolf336** [comment]
I'm going to close this and redirect you to our Android repository: https://github.com/RocketChat/Rocket.Chat.Android

**Comment by shemsargent-rvtd** [comment]
Turns out that I needed to pass WebSocket traffic through nginx.
