### ISSUE TITLE
Special characters in Channel names not displayed

### ISSUE THREAD

**Issue by harshadsabne** [RocketChat/Rocket.Chat#105]
I noticed that if a channel name consists of only special key characters like (!@#$%^&*_-+=;':",<>.) the channel is created but without a name as shown below. Several such "unnamed" channels can be created.

![rocket chat1](https://cloud.githubusercontent.com/assets/3154126/7928724/6e7428ac-0912-11e5-8428-e6d5752643a0.png)

Now if you go to edit the name of the recently created channel, you will see that it is blank
![rocket chat2](https://cloud.githubusercontent.com/assets/3154126/7928731/74a73b56-0912-11e5-9288-fa6579bbc49d.png)

If a channel name is something like abcd$%^xyz then it is named as abcd-xyz i.e. the special characters are replaced by a single hyphen -  as shown below. But this happens only if the string begins and ends with alphanumeric characters. 

![rocket chat3](https://cloud.githubusercontent.com/assets/3154126/7928819/87379c6a-0913-11e5-8850-d9494f20e5f0.png)
![rocket chat4](https://cloud.githubusercontent.com/assets/3154126/7928824/9489e31e-0913-11e5-9e97-278cbb915b97.png)

Special characters at the end of a channel name ( eg abcd^&* ) seem to be ignored completely.
![rocket chat5](https://cloud.githubusercontent.com/assets/3154126/7929070/5cfc590a-0917-11e5-9c76-138b72990338.png)
![rocket chat6](https://cloud.githubusercontent.com/assets/3154126/7929074/610387b2-0917-11e5-9cd7-40eb2bcadac9.png)

Special characters should either be parsed correctly or their use in channel names should be disallowed completely.

**Comment by sampaiodiego** [comment]
hey @harshadsabne .. in fact, room creation needs a lot of checks. It will need to be unique, not blank, and add the possibility to user to review the name if it was changed due to special characters like your examples.

actually the room name is "slugified" and saved. we really need a more friendly interaction here.

thanks for the issue

**Comment by marceloschmidt** [comment]
I have updated the channel creation to limit the characters that may be used on it's creation. I removed the slugify. If that's absolutely needed, just put it back on :) Pull Request 134
