### ISSUE TITLE
Slack import error [Unknown id for changed: Accounts_AllowedDomainsList]

### ISSUE THREAD

**Issue by mfrancisc** [RocketChat/Rocket.Chat#10506]
### Description:

When trying to import Slack zip file, I got an error.
I think it maybe an issue with slow file downloads.
Channels and Users were imported correctly, it starts to  import messages, when encounters this type of slack export object, it stops with the error listed above:
{
        "type": "message",
        "subtype": "file_share",
        "text": "<@U10K51Q1E> uploaded a file: <https://someprivateurlhere.com> and commented: <@U110AMUET> Comment here.",
        "file": {
            "id": "F3UTAQZ7S",
            "created": 1485256848,
            "timestamp": 1485256848,
            "name": "XXXX_FILE.zip",
            "title": "XXX_FILE.zip",
            "mimetype": "application\/zip",
            "filetype": "zip",
            "pretty_type": "Zip",
            "user": "U10K51Q1E",
            "editable": false,
            "size": 626683,
            "mode": "hosted",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https://someprivateurlhere.com",
            "url_private_download": "https://someprivateurlhere.com",
            "permalink": "https://someprivateurlhere.com",
            "permalink_public": "https://someprivateurlhere.com",
            "channels": [],
            "groups": [],
            "ims": [],
            "comments_count": 1,
            "initial_comment": {
                "id": "Fc3W9L5RHD",
                "created": 1485256848,
                "timestamp": 1485256848,
                "user": "U10K51Q1E",
                "is_intro": true,
                "comment": "<@U110AMUET> Message text ...."
            }
        },
 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.2
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: NO
* Node Version: v8.1.4
* mongoDB Version: 3.4.6

### Steps to Reproduce:

1. Export from Slack as listed in Rocket Chat documentation
2. Import in Rocket Chat from the Slack Import panel

### Expected behavior:

See users, channels and messages.

### Actual behavior:

Import Error.

### Relevant logs:
[34mI20180419-09:19:25.212(2) Exception in changed observe/observeChanges callback: Error: Unknown id for changed: Accounts_AllowedDomainsList     at applyChange.changed (/root/Rocket.Chat/programs/server/packages/minimongo.js:2968:15)     at runWithEnvironment (packages/meteor.js:1238:24)     at packages/meteor.js:1251:14     at /root/Rocket.Chat/programs/server/packages/mongo.js:1924:30     at Array.forEach (native)     at Function._.each._.forEach (packages/underscore.js:139:11)     at Object.task (/root/Rocket.Chat/programs/server/packages/mongo.js:1919:9)     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)     at packages/meteor.js:846:12  
[34mI20180419-09:19:25.774(2) rocketchat_logger rocketchat_logger.js:278 [31mSlack Importer ➔ error TypeError: First argument should be a valid curve name     at Object.createSecureContext (_tls_common.js:115:15)     at Object.exports.connect (_tls_wrap.js:1038:48)     at Agent.createConnection (https.js:105:22)     at Agent.createSocket (_http_agent.js:222:26)     at Agent.addRequest (_http_agent.js:184:10)     at new ClientRequest (_http_client.js:272:16)     at Object.request (http.js:39:10)     at Object.request (https.js:233:15)     at Object.request (/root/Rocket.Chat/programs/server/npm/node_modules/agent-base/patch-core.js:52:20)     at Object.get (https.js:237:21)     at SlackImporter.uploadFile (/root/Rocket.Chat/programs/server/packages/rocketchat_importer.js:387:26)     at msgs.messages.forEach.message (/root/Rocket.Chat/programs/server/packages/rocketchat_importer-slack.js:572:30)     at Array.forEach (native)     at Object.keys.forEach.date (/root/Rocket.Chat/programs/server/packages/rocketchat_importer-slack.js:458:29)     at Array.forEach (native)     at DDPCommon.MethodInvocation.Meteor.runAsUser (/root/Rocket.Chat/programs/server/packages/rocketchat_importer-slack.js:456:38)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at Object.keys.forEach.channel (/root/Rocket.Chat/programs/server/packages/rocketchat_importer-slack.js:442:18)     at Array.forEach (native)     at Meteor.defer (/root/Rocket.Chat/programs/server/packages/rocketchat_importer-slack.js:440:36)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at packages/meteor.js:502:25     at runWithEnvironment (packages/meteor.js:1238:24)  
[34mI20180419-09:19:25.854(2) Exception in changed observe/observeChanges callback: Error: Unknown id for changed: Accounts_AllowedDomainsList     at applyChange.changed (/root/Rocket.Chat/programs/server/packages/minimongo.js:2968:15)     at runWithEnvironment (packages/meteor.js:1238:24)     at packages/meteor.js:1251:14     at /root/Rocket.Chat/programs/server/packages/mongo.js:1924:30     at Array.forEach (native)     at Function._.each._.forEach (packages/underscore.js:139:11)     at Object.task (/root/Rocket.Chat/programs/server/packages/mongo.js:1919:9)     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)     at packages/meteor.js:846:12  

Thanks in advance for your help.

**Comment by pierre-lehnen-rc** [comment]
This bug was fixed long ago but the issue remained open.
