### ISSUE TITLE
Channel is read only in build 2010

### ISSUE THREAD

**Issue by martinszy** [RocketChat/Rocket.Chat#10500]
### Description:

In the new android app, I can't write to channels to which I'm admin.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System:  Android
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 
* Android app version: 2.0.0 build 2010

### Steps to Reproduce:

Use web app to join a channel
Send message to channel
Open channel in android app
Can't send message

### Expected behavior:
Groups should allow for sending messages

### Actual behavior:

Get the error "channel is read only"

**Comment by graywolf336** [comment]
Closing this as this is an andorid app issue: https://github.com/RocketChat/Rocket.Chat.Android/issues

**Comment by martinszy** [comment]
oops, sorry, wrong repo

**Comment by graywolf336** [comment]
No worries :)
