### ISSUE TITLE
View mode selection (and so compact mode) disappear.

### ISSUE THREAD

**Issue by millerlucas** [RocketChat/Rocket.Chat#10512]
### Description:

View mode disappear from user preferences.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 3
* DB Replicaset Oplog: Activated
* Node Version: - (official docker image used)
* mongoDB Version: 3.4

### Steps to Reproduce:

Just go to user preferences and you can see that the view mode is not present anymore. I'm using only compact mode and now i'm in normal mode (i assume) because i can't set it back to compact.

### Expected behavior:

Be able to chose the view mode.

### Actual behavior:

Can't chose the view mode.

**Comment by kaiiiiiiiii** [comment]
I’ve already fixed that in my PR #10395.

The option will be back with the next release at the beginning of may :)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I see, so https://github.com/RocketChat/Rocket.Chat/pull/10395 belongs to #10326 and has been fixed.

Cheers
Thomas
