### ISSUE TITLE
Settings strings show `undefined` in the UI

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#1051]
![screen shot 2015-10-09 at 10 18 44 am](https://cloud.githubusercontent.com/assets/498744/10396198/21972c7e-6e6f-11e5-846b-13b81d7ce028.png)

**Comment by rodrigok** [comment]
Can you provide more details? Which OS, Browser, how are you running the project, error logs, etc?

**Comment by IQ2022** [comment]
I had similar issue when I was trying to update from master in heruko, ended up deleting files and adding new build from master ... :sagittarius:

**Comment by mhkeller** [comment]
On OS X El Capitan I'm seeing it in Electron, Firefox and Chrome. The console doesn't give any errors besides the following:

```
Found hi-entropy localStorage:  407.97120615088306  bits "http:/URL/channel/general" Meteor.loginTokenExpires general:65:1
unreachable code after return statement 4d78fd92fb7242772fa91fd7c9cc72bca73bb215.js:340:20414
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```

**Comment by rodrigok** [comment]
How are you running the project?

**Comment by mhkeller** [comment]
Through docker-compose.

On Fri, Oct 9, 2015 at 10:51 AM, Rodrigo Nascimento <
notifications@github.com> wrote:

> How are you running the project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/1051#issuecomment-146893940>
> .
>



-- 
@mhkeller
mhkeller.com

**Comment by rodrigok** [comment]
I can't reproduce this locally

**Comment by doomdance** [comment]
I am also seeing this after updating my Centos install. Seeing this on Chrome for Arch Linux and Mac.

**Comment by doomdance** [comment]
So, after restarting with pm2, administrator settings now appears as it should.

**Comment by rodrigok** [comment]
Ok, the only way to solve this problem is restarting the application.

This was caused by one migration to remove some wrong settings names, but the migration is executed after the load of settings, so restarting will solve cuz the migration will not be executed again.

**Comment by geekgonecrazy** [comment]
@rodrigok so this is a one time issue that should be resolved?

**Comment by rodrigok** [comment]
@geekgonecrazy yes
