### ISSUE TITLE
Search bar overlapping display with buttons 

### ISSUE THREAD

**Issue by demetriolinares** [RocketChat/Rocket.Chat#10510]
### Description:

When clicking on Search button, Search bar overlaps with buttons (Search, Directory, View mode, Sort, Create a New Channel)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 

### Steps to Reproduce:

1. Click on Search button

### Expected behavior:

Search bar opening under the buttons, or hiding buttons

### Actual behavior:

Search bar overlaps with buttons, displaying both things together

![screenshot from 2018-04-19 10-49-34](https://user-images.githubusercontent.com/26930764/38995547-85d3c6a2-43bf-11e8-89da-285446521585.png)

**Comment by kaiiiiiiiii** [comment]
I cannot reproduce this error in v0.63.3. Tested with Windows (Desktop Client, Chrome 65.0.3325.181) and Mac (Desktop Client, Chrome 65.0.3325.181).

Can you please provide more informations about your system?

**Comment by demetriolinares** [comment]
@kaiiiiiiiii Thanks for the quick reply! 
I updated the case with some data I could collect. Hope it helps.

**Comment by demetriolinares** [comment]
We solved it! There was a wrong value at "Primary Darkest" color. Thanks!

**Comment by qasim-arbisoft** [comment]
I still see the error on 0.65.1

![image](https://user-images.githubusercontent.com/23377048/41407641-743e4e02-6fe9-11e8-88ad-5ed72925050b.png)

Is there a fix via configuration?

**Comment by vynmera** [comment]
@qasim-arbisoft Have you tried changing Primary Darkest?

Administration → Layout → Primary Darkest
Check its setting, if it is invalid the background of the Search field will be transparent. This is working as intended~

**Comment by qasim-arbisoft** [comment]
Thanks @vynmera . It's fixed now!
