### ISSUE TITLE
"Disable Embed for Users" not working for mobile clients

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#10525]
* Version of Rocket.Chat Server: 0.63.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Yes
* Node Version: 8.9.4
* mongoDB Version: 3.4

### Steps to Reproduce:

1. Add User rocket.cat in "Disable Embed for Users" 
2. User rocket.cat as WebHook User 
3. Embedded Link Previews are shown on mobile clients

### Expected behavior:

No link previews are shown.

### Actual behavior:

Link previews are shown

thanks and best regards

**Comment by rafaelks** [comment]
Issues opened for the mobile apps, closing here: https://github.com/RocketChat/Rocket.Chat.Android/issues/1145 & https://github.com/RocketChat/Rocket.Chat.iOS/issues/1573.
