### ISSUE TITLE
Add support for passing connection options to Mongo

### ISSUE THREAD

**Issue by saplla** [RocketChat/Rocket.Chat#10526]
### Description:
It's not currently possible to provide [connection settings](http://mongodb.github.io/node-mongodb-native/2.2/reference/connecting/connection-settings/) to the Mongo driver with Rocket Chat. This is required to provide a PEM file and CA cert file if Mongo is configured to only accept connections from clients with valid certs. Simply adding `ssl=true` to the `MONGO_URI` isn't sufficient because there's no way to pass the `sslCA` and `sslCert` parameters in the URI.

Meteor [supports passing extra options](https://github.com/meteor/meteor/blob/devel/packages/mongo/connection_options.js) to the underlying mongo driver. Rocket chat should provide a way for connection options to be configured to allow this usecase.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* mongoDB Version: 3.6

### Steps to Reproduce:

1. Create a mongo replica set secured with TLS.
2. Try to configure Rocket chat to connect to mongo with a verified SSL certificate.

### Expected behavior:
Rocket chat should provide a mechanism to configure the mongo driver to pass the required parameters to connect via TLS with verified certificates.

### Actual behavior:
It's not possible to configure the mongo driver in Rocket chat so it can't connect.

**Comment by engelgabriel** [comment]
Did you try https://docs.mongodb.com/manual/reference/connection-string/#connection-string-options ?

**Comment by engelgabriel** [comment]
We should add a parameter from an environment variable to me merged with the options here:

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-cors/cors.js#L14
