### ISSUE TITLE
RocketChat periodically crashes

### ISSUE THREAD

**Issue by ivangerasimov39** [RocketChat/Rocket.Chat#10538]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 0
* Node Version: 8.11.1
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. to start rocketchat via systemd
2.  after some time, rocketchat crashes

### Relevant logs:
**Rocketchat.log**
![image](https://user-images.githubusercontent.com/29921722/39082740-2f00f45e-4558-11e8-9c7b-55096290915c.png)
**mongodb.log**
![image](https://user-images.githubusercontent.com/29921722/39082746-4bb73414-4558-11e8-8e40-6b2010db0d32.png)
**systemd**
![image](https://user-images.githubusercontent.com/29921722/39082747-5e685eda-4558-11e8-9b25-b76fe6b5942f.png)

**Comment by ivangerasimov39** [comment]
**ldap-sync**
![image](https://user-images.githubusercontent.com/29921722/39082786-fd5aaff2-4558-11e8-81cc-e4994ba35144.png)

**Comment by ivangerasimov39** [comment]
again
![image](https://user-images.githubusercontent.com/29921722/39082991-a128565e-455c-11e8-94ad-ca04c1f3b8cc.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Please downgrade to nodejs 8.9.4. For details, see https://github.com/RocketChat/Rocket.Chat/issues/10331

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Just as a sidenote: we are thankful for any bug report, really, but please do send logs as plaintext, not as image :)

Cheers
Thomas
