### ISSUE TITLE
Travis and drone not enabled?

### ISSUE THREAD

**Issue by DanielRuf** [RocketChat/Rocket.Chat#10536]
I saw the .travis config file but it seems Travis is not running on commits and PRs anymore so is the config file obsolete?

Also drone is not running (anymore).

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Seems to be suited more for the [chat](https://open.rocket.chat/channel/support rather than Github.

As for Travis: I don't think it's used anymore, guess the guys have switched to CircleCI. Drone I don't know.

Cheers
Thomas
