### ISSUE TITLE
Custom oauth not working in desktop client

### ISSUE THREAD

**Issue by EddEdw** [RocketChat/Rocket.Chat#10533]
## My Setup
- Operating System: Ubuntu (server)
- Version of Rocket.Chat Server: 0.63.3
- RocketChat+ App Version: 2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

We host a Rocket.Chat instance behind my company's proxy. This instance connects to our custom oauth provider - no problems there; it works like a charm. But not when starting to use the desktop client... 

When using the RocketChat+ desktop client I cannot use the a custom oauth provider, because the provider's login page is not presented and the javascript console throws `"Uncaught ReferenceError: Meteor is not defined"` in file `preload.js` in `line 59` of the RocketChat+ app.

Blank popup when clicking "authenticate using custom oauth"
![image](https://user-images.githubusercontent.com/6577198/36386562-693506d4-1596-11e8-9295-92a5a2e80c25.png)

Javascript logs from RocketChat+ developer console:
![image](https://user-images.githubusercontent.com/6577198/36386495-350154f8-1596-11e8-8a40-3e0539095b94.png)

### Steps to Reproduce:

1. Setup RocketChat (Snaps) and custom Oauth2 provider and get it up and running using the webbased access ✔️ 
2. Download and install RocketChat+ version 2.10.5
3. Login using custom oauth2 provider

### Current Behavior
Window popps up but no login website is shown - page is left blank

### Expected Behavior
Popup window showing up displaying oauth-provider's login page to user. (as it works on the web version)

## Relevant logs:

Console logs from RocketChat+:
```
Uncaught ReferenceError: Meteor is not defined
    at C:\Users\UN\AppData\Local\Programs\rocketchat\Rocket.Chat+\resources\app.asar\app\public\prelo…:59
(anonymous) @ C:\Users\UN\AppData\Local\Programs\rocketchat\Rocket.Chat+\resources\app.asar\app\public\prelo…:59
```

This logs point to `preload.js` file in the RocketChat+ client. Since the Meteor interface is provided by the server, the issue very likely sits in the server's implementation.

```javascript
window.addEventListener('load', function () {
    Meteor.startup(function () { //<<<< this line is highlighted
        Tracker.autorun(function () {
            const siteName = RocketChat.settings.get('Site_Name');
            if (siteName) {
                ipcRenderer.sendToHost('title-changed', siteName);
            }
        });
    });
    userPresenceControl();
})
```

Another error is thrown which I did not yet investigate:
```
Uncaught TypeError: Cannot read property 'Constructor' of undefined
RESTLoginHelper.js:114 
    at RESTLoginHelper.js:114
    at RESTLoginHelper.js:114
    at Object.execCb (requirejs-2.1.14-min.js:29)
    at Z.check (requirejs-2.1.14-min.js:18)
    at Z.enable (requirejs-2.1.14-min.js:23)
    at Object.enable (requirejs-2.1.14-min.js:27)
    at Z.<anonymous> (requirejs-2.1.14-min.js:23)
    at requirejs-2.1.14-min.js:8
    at v (requirejs-2.1.14-min.js:7)
    at Z.enable (requirejs-2.1.14-min.js:22)
(anonymous) @ RESTLoginHelper.js:114
(anonymous) @ RESTLoginHelper.js:114
execCb @ requirejs-2.1.14-min.js:29
check @ requirejs-2.1.14-min.js:18
enable @ requirejs-2.1.14-min.js:23
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
enable @ requirejs-2.1.14-min.js:27
(anonymous) @ requirejs-2.1.14-min.js:23
(anonymous) @ requirejs-2.1.14-min.js:8
v @ requirejs-2.1.14-min.js:7
enable @ requirejs-2.1.14-min.js:22
init @ requirejs-2.1.14-min.js:17
(anonymous) @ requirejs-2.1.14-min.js:26
```

**Comment by kaiiiiiiiii** [comment]
Hi @EddEdw,

as you already mentioned, this seems to be a desktop client issue.

This repository ([RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat)) is mainly for the server component of Rocket.Chat. You can find the Desktop Client Repository over here ([Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron)).

I think you'll have more success by opening an issue in the right repository :)

@TwizzyDizzy Can you please close this issue? Thanks :)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
