### ISSUE TITLE
Permission to Manage custom emojis

### ISSUE THREAD

**Issue by javi076** [RocketChat/Rocket.Chat#10531]
### Description:

We add manage-emoji permission to user role, but they can't see administration option on menu.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 4
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 

### Steps to Reproduce:

1. Add permission "manage-emoji" to "user" role
2. Log in with a user who only has the "user" role 

### Expected behavior:

User can see option: Admininistration -> Custom Emoji
It used to work on previous versions (0.60.4)

### Actual behavior:

![screenshot from 2018-04-20 15-20-56](https://user-images.githubusercontent.com/10394672/39067489-38895664-44af-11e8-87d0-09091607dff5.png)

**Comment by kaiiiiiiiii** [comment]
Duplicate of #9865

This will be fixed with the next release :)

**Comment by javi076** [comment]
Thanks!
