### ISSUE TITLE
Unable to change CSS values

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#10541]
### Description:

If I change values for CSS settings for the theme for Rocket chat using the usual admin interface for CSS changes, the changes are saved in the admin area but do not take effect in the UI.

I have restarted php-fpm, nginx and rocketchat. I have upgraded to various versions (am now on the latest beta) and have cleared browser caches and used different browsers. Every time I change something in the css it does nothing.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-rc.0
* Operating System: Fedora 27 64 bit
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 3.4.11

### Steps to Reproduce:

1. install rocketchat
2. run rocketchat
3. change CSS values for header or other UI elements in the Admin CSS editor.
4. Save changed CSS.

### Expected behavior:

CSS changes are reflected in the UI

### Actual behavior:

CSS changes are not reflected in the UI and do not appear in the page when inspected in a browser

**Comment by propertunist** [comment]
I have tried hitting 'reset' as described here: https://github.com/RocketChat/Rocket.Chat/issues/4004
but it made no  difference.

**Comment by JSzaszvari** [comment]
Can you give a specific example of something you are trying to change?

**Comment by TwizzyDizzy** [comment]
@propertunist time to dig deep.

* please tell us your browser version
* watch your browser's javascript console while saving custom CSS settings
* have a look at your browser's calculated CSS classes and see if your changes appear there (and let us know by screenshot)

Otherwise we're not getting anywhere here, I fear.

Cheers & Thanks
Thomas

**Comment by propertunist** [comment]
@TwizzyDizzy - Sure ok
I am using Firefox 59.0.2 64 Bit on Fedora 27 (however I also get the same result in chromium and windows).

I do see these in the console on initial page load:
```
Firefox can't establish a connection to the server at wss://chat.ureka.org/sockjs/674/3qwdlz5x/websocket.
62672ba6a85dfcfa23c6f5fd4ed4809b07864adb.js:57:24399
08:36:29.303 The connection to wss://chat.ureka.org/sockjs/674/3qwdlz5x/websocket was interrupted while the page was loading.
```
The changes do not appear in the browser's calculated CSS classes. Only the original colour and the formula value for the them appear - my own colour is nowhere to be found.

![selection_059](https://user-images.githubusercontent.com/513903/39232225-7db151fc-4864-11e8-80ab-42815563164c.png)

**Comment by propertunist** [comment]
Just updated to RocketChat v64, but no change

**Comment by propertunist** [comment]
is anyone investigating this? anyone got any tests i can run here?

**Comment by geekgonecrazy** [comment]
All of this has been reworked.  Closing
