### ISSUE TITLE
Can I send message all except some persons?

### ISSUE THREAD

**Issue by ivangerasimov39** [RocketChat/Rocket.Chat#10540]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0
* Operating System:  CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 0
* Node Version: 8.9.4
* mongoDB Version: 2.6.12

### Actual behavior:

I want to send direct messages all except some persons
**example:** 

> `@all @except {user_a, user_b, user_c} some_text `

**Comment by ivangerasimov39** [comment]
may be to add filters for send direct messages?
**example:**
![rocket_dm](https://user-images.githubusercontent.com/29921722/39857615-3d4648ee-5434-11e8-9377-ffbc4cded496.jpg)

**Comment by MartinSchoeler** [comment]
No, currently is not possible to do this via UI, closing this. Thanks!
