### ISSUE TITLE
RocketChat / MongoDB is crashing every 24 hours

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#10547]
### Description:

For the last few weeks I have found that my instance of Rocketchat crashes over night, every 24 hours (roughly). I have to restart the mongod process on the fedora based server and then all is well again for another 24 hours. I have upgraded Rocketchat a few times but it made no difference. I suspect the problem is with Mongodb, but having tried a few fixes with that too that did nothing to resolve the issue, I am a bit stuck.

I am seeing some messages in the mongodb log regarding diagnostic file issues and read on another thread that i should just delete the folder for that diagnostic data. I did do that and the error went away until after the next crash.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-rc.0
* Operating System: Fedora 27 64 bit
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 3.4.11

### Steps to Reproduce:

1. Install Rocket Chat on Fedora 27
2. Launch Rocket Chat
3. Check back on Rocket chat after (usually) more than 24 hours.

3. 

### Expected behavior:

Rocket chat should still be usable and running.

### Actual behavior:

In versions prior to 0.64.0-rc.0, the browser displays a white screen instead of rocketchat. In 0.64.0-rc.0 I see the background of the site's theme and a loading animation - but the chat app never loads.

### Relevant logs:
Mongodb:

2018-04-18T00:07:47.635+0000 E STORAGE  [thread2] WiredTiger error (28) [1524010067:625767][8003:0x7fae865e9700], file:index-545-5179165362493312193.wt, WT_SESSION.checkpoint: /var/lib/mongodb/index-545-5179165362493312193.wt: handle-write: pwrite: failed to write 4096 bytes at offset 28672: No space left on device
2018-04-18T00:07:47.637+0000 E STORAGE  [thread2] WiredTiger error (28) [1524010067:637297][8003:0x7fae865e9700], file:index-545-5179165362493312193.wt, WT_SESSION.checkpoint: index-545-5179165362493312193.wt: fatal checkpoint failure: No space left on device

**Comment by propertunist** [comment]
I should point out that as far as I can see there is plenty of HD space left on the server in all the locations I have checked.

**Comment by pcm211** [comment]
handle-write: pwrite: failed to write 4096 bytes at offset 28672: No space left on device 

Its Coz you maybe having free space but its not formatted as it could have been made later as an afterthoought in the VM and the HDD hasnt expanded accordingly. Id suggest use a partition tool as gparted etc to realign the free space

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hey folks,

this is clearly no bug, so I'm closing this. Feel free to continue this conversation over at https://forums.rocket.chat/c/community-support or https://open.rocket.chat/channel/support though...

Cheers
Thomas
