### ISSUE TITLE
In Firefox, forward-delete moves right by a character before deleting the following character

### ISSUE THREAD

**Issue by zarvox** [RocketChat/Rocket.Chat#1055]
If I type `testing` into the chat box, and move the cursor to the beginning of the word, and then press forward-Delete, it removes the 'e' instead of the first 't', and leaves the cursor after the first 't'.  Similarly, if I press the key another three times, it will:

* delete the second 't', leaving (^ is cursor) `ts^ing`
* delete the 'n', leaving `tsi^g`
* move the cursor to the right, leaving `tsig^`

**Comment by gmsecrieru** [comment]
@zarvox we merged a few changes that might have fixed this:

![testing](https://cloud.githubusercontent.com/assets/190883/10407090/ab0306e8-6ebc-11e5-893d-ca622031d9ac.gif)

Could you please confirm this is still an issue?

**Comment by zarvox** [comment]
Fixed indeed, thanks!
