### ISSUE TITLE
Image has shrunk to nothing

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat#10552]
### Description:
I try to paste picture of 1300 width pixels. (and height of 25px)
### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: ubuntu 16.04.4
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances:  1
* DB Replicaset Oplog: active
* Node Version: 8.9.3
* mongoDB Version: 3.2

### Steps to Reproduce:
Take picture of 1300 width pixel (and height of 25px)
Or use my picture for testing: 
![image](https://user-images.githubusercontent.com/331816/39121936-7f6180b6-46f3-11e8-8ebb-1a1b84fa0b54.png)

### Expected behavior:
 Display picture in chat.

### Actual behavior:
No picture and error in log.

### Relevant logs:
`Exception while invoking method 'sendFileMessage' Error: reducev: image has shrunk to nothing     => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1477:49)     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  `

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "type: bug"

I can confirm this on `0.64.0-rc.1`. Guess on resizing images that have extreme ratios leads to either side of the image being zero when generating the preview.

Cheers
Thomas

**Comment by maih43538** [comment]
Mobile

**Comment by maih43538** [comment]
Kết nối tài khoảng google

**Comment by reetp** [comment]
I'd seen this on 0.63 but thought it was an isolated incident ion my box.

**Comment by himpierre** [comment]
Same problem in 0.65.2.

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
