### ISSUE TITLE
installing chat ops in-house on rhel6

### ISSUE THREAD

**Issue by TinajaLabs** [RocketChat/Rocket.Chat#1056]
At my day job, we're planning to move to the chat ops world and see hubot/chat.rocket as a possible solution.  Both seem to be written in some form of javascript (coffeescript?).

Looks like hubot can be installed via npm but the chat.rocket install seems fairly complicated.  The non-docker install instructions are staggering.  What's up with that?

Also, if we go with chat.rocket do we have to buy into the meteor platform to build our custom functions to integrate hubot and chat.rocket with our deployment and incident management tools?

Just so you know, we have very few external apps; pagerduty and email. We use gitlab, jenkins, puppet, icinga, graphite, grafana, elk, etc; all inside our firewall.  So we need to create an internal environment to build our chat-ops tools. When we're working at home or traveling we use a VPN connection.

Any advice appreciated,
Chris.

**Comment by geekgonecrazy** [comment]
@TinajaLabs 

We're in the process of discussing the move to pure javascript see: #1015 but yes right now Rocket.Chat is primarily coffeescript.

We have plans very soon to try and make the installation process of Rocket.Chat as simple as it is with hubot.  Hopefully we'll be started on that soon.

No need to get into the whole meteor platform for integrations.  In fact when you write plugins for hubot that's pure hubot.  We plan to allow hubot to be able to drive different elements in the chat via a chatops panel.  As well as for hubot to be able to post customly styled messages.  So hubot integrations will be very powerful.

We plan to make chatops with Rocket.Chat as easy as possible.  We don't want you to need to even touch our source code to make your integrations.

**Comment by Sing-Li** [comment]
Yes.  Basically, CoffeeScript is just like a Macro language for JavaScript, patching in some of its shortcomings before the language can evolve to the next stage. 

Also Rocket.Chat installations on Redhat should just be as simple (or complex) as most of the other open source server-side technologies that you're already using in-house.  I don't think we're any more difficult to install.  In fact, an npm install is on the drawing board.

Chat-ops is a new and exciting area that we're extending Rocket.Chat into - so please come join us to make it great.  One place to find us is at https://demo.rocket.chat/ ,  core dev are there almost  all the time.

BTW .. a few of us are actually IoT / Maker nuts.  Personally, Rocket.Chat server is running fine on a Raspberry Pi 2 for me ...  and we tossed around the idea of making a completely distributed p2p version of Rocket.Chat on communicating via low-powered ESP8266s operating off CR2032s that can be taped to trees and lamp-posts.  Please come chat with us sometimes.

**Comment by TinajaLabs** [comment]
Thanks for the considerate replies.  For my day job, we'll be looking at primarily automating deployment and incident management. 

For my home automation and IOT fun I'm thinking of hooking up a chat ops / Hubot integration with monitoring and actuation.  I'm already using node red as a core component of my system. Wouldn't it be great to wrap a "conversation" into the process.

Thanks again, Chris.

**Comment by Theaxiom** [comment]
I have developed an Ansible role/playbook to install Rocket.Chat on RHEL6 -- is this something you'd be interested in? I can share it publicly if you so desire.

**Comment by geekgonecrazy** [comment]
@Theaxiom that would be awesome!  Would you think about possibly opening a PR here?  That would be awesome and I would think very useful

**Comment by Theaxiom** [comment]
@geekgonecrazy Sure, I can make it part of the Rocket.Chat core repo -- Ansible works well like that. :)

**Comment by geekgonecrazy** [comment]
@Theaxiom I think we might be trying move anything deployment related in that repo.

I'll get the others feedback on that though.  
@RocketChat/owners thoughts?

**Comment by Theaxiom** [comment]
Would this work better: https://github.com/RocketChat/Deploy.to.Cloud

**Comment by geekgonecrazy** [comment]
@Theaxiom apparently I need sleep.  I meant to put a link to that repo.  Yes please

**Comment by Theaxiom** [comment]
That makes more sense now. :)

Thanks,
Travis Rowland
http://travisrowland.com
http://linkedin.com/in/travisrowland
http://about.me/travisrowland

-----------------------------------------------

This e-mail is privileged and confidential.  Do not forward, copy or print
without authorization.  If you are not the intended recipient of this
E-mail, you are hereby notified that any dissemination, distribution or
copying of this message is strictly prohibited. If misdirected, please
delete and notify the sender by e-mail at travis.rowland@gmail.com.

CAUTION: E-mail sent through the internet is not secure and could be
intercepted by a third party. For your protection, avoid sending
identifying information, such as account numbers or social security numbers.

**Comment by geekgonecrazy** [comment]
@TinajaLabs i'm going to close this.  

@Theaxiom if you get a chance to create a PR for the ansible stuff, maybe link to this so @TinajaLabs can see the changes.
