### ISSUE TITLE
I've install rocketchat via snap on centos 7, how do I login to the mongo db?

### ISSUE THREAD

**Issue by tmckinne** [RocketChat/Rocket.Chat#10562]
### Server Setup Information:

* Version of Rocket.Chat Server:  0.63.3
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
