### ISSUE TITLE
E-Mail notifications to channel/room not working

### ISSUE THREAD

**Issue by sfmarques** [RocketChat/Rocket.Chat#10570]
### Description:

Email notifications to users by reference not working

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 
* DB Replicaset Oplog: Disabled
* Node Version: v8.11.1
* mongoDB Version: 3.0

### Steps to Reproduce:

1. Configure SMTP - it's working
2. Configured Accounts - Default User Preferences -> Offline Email Notifications -> Every Mention/DM
3. References user in channels with @ 

### Expected behavior:

Send email to user like in this link:
https://github.com/RocketChat/Rocket.Chat/pull/3814

### Actual behavior:

Nothing happens 

### Relevant logs:

> rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method sendMessage -> userId: xp8aGn2wgBqMw2MTK , arguments:  { '0':     { _id: 'JusDtpHh8NQFNjemK',      rid: 'MkzYaKwNDrtvZgPap',      msg: '@teste.user ' } } 
[34mI20180424-10:23:15.086(0) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method canAccessRoom -> userId: xp8aGn2wgBqMw2MTK , arguments:  { '0': 'MkzYaKwNDrtvZgPap', '1': 'xp8aGn2wgBqMw2MTK' } 
[34mI20180424-10:23:15.121(0) rocketchat_logger rocketchat_logger.js:278 [34mIntegrations ➔ Outgoing WebHook.debug Execute Trigger: sendMessage 
[34mI20180424-10:23:15.122(0) rocketchat_logger rocketchat_logger.js:278 [34mIntegrations ➔ Outgoing WebHook.debug Got the event arguments for the event: sendMessage { event: 'sendMessage',   message:     { _id: 'JusDtpHh8NQFNjemK',      rid: 'MkzYaKwNDrtvZgPap',      msg: '@teste.user ',      ts: 2018-04-24T10:23:15.086Z,      u:        { _id: 'xp8aGn2wgBqMw2MTK',         username: 'sergio.marques',         name: 'Sérgio Marques' },      mentions: [ [Object] ],      channels: [],      _updatedAt: 2018-04-24T10:23:15.096Z,      sandstormSessionId: null },   room:     { _id: 'MkzYaKwNDrtvZgPap',      name: 'teste',      fname: 'teste',      t: 'c',      msgs: 20,      u: { _id: 'xp8aGn2wgBqMw2MTK', username: 'sergio.marques' },      customFields: {},      ts: 2018-04-23T13:59:41.172Z,      ro: false,      sysMes: true,      _updatedAt: 2018-04-24T10:21:07.314Z,      lm: 2018-04-24T10:21:07.279Z,      meta:        { revision: 11,         created: 1524499749675,         version: 0,         updated: 1524565267316 },      '$loki': 4,      username: 'sergio.marques',      usernames:        [ 'rocket.cat',         'ricardo.simoes',         'pedro.dourado',         'pedro.benites',         'teste.user',         'sergio.marques' ] } }

**Comment by antgel** [comment]
@sampaiodiego Another one?

**Comment by sfmarques** [comment]
Hello,

This is solved, the user needed to confirm the email address. 

Thanks

**Comment by sfmarques** [comment]
It's Working
