### ISSUE TITLE
Mobile app install banners

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat#10589]
When a user clicks a link on their phone to a rocket.chat server URL, it would be great if we could check to see if the phone has the Android or IOS app installed on that device and if not prompt them to install it. These are called "app install banners". 

In addition, if I have the app installed, I'd prefer to open the link in my mobile app. Not sure if this is one feature or two.

**Comment by graywolf336** [comment]
I am closing this because feature request, such as this one, are to be requested on the forums. https://forums.rocket.chat/c/feature-requests
