### ISSUE TITLE
git rebase > git merge when updating feature branches

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#10585]
As I mentioned in https://github.com/RocketChat/Rocket.Chat.Android/issues/1092, the same applies here. The git log is full of unnecessary merges, especially on a high-traffic project like RC. I guess it will always happen from time to time but @rodrigok what do you think about passing the message on to core contributors?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @antgel ... while I do appreciate your involvement (I really do!) I'd really like to not have discussions like this here on Github.

@geekgonecrazy could we have a developer's area in the forums? Currently there seems to be no category for development-focussed discussions like those above. I think there should be one :)

Cheers
Thomas

**Comment by antgel** [comment]
Great idea! Until there's an alternative forum where we can have such discussions, I don't see why we should close this, it will fall between the cracks. Please let me know where is a better place to discuss such matters.

**Comment by Lawri-van-Buel** [comment]
My default git config
```
user.name=<name>
user.email=<email>
core.autocrlf=input
core.editor=nano
color.ui=true
push.default=simple
pull.rebase=true
rerere.enabled=true
alias.s=status -s
alias.lg=log --oneline --decorate --all --graph
```

**Comment by antgel** [comment]
@sampaiodiego @geekgonecrazy @graywolf336 How is this still a thing? The logs are so hard to read.

**Comment by sampaiodiego** [comment]
@antgel we've been squashing pull requests commits on merge which has improved the log a lot.. here's how it looks like today:
![image](https://user-images.githubusercontent.com/8591547/46960369-c2ee9700-d074-11e8-9aad-f683623013be.png)

do you still thinks it needs to improve? if so, do you have any suggestion?

**Comment by antgel** [comment]
@sampaiodiego That's not the same thing, and indeed I would expect it to cause problems if you don't throw away your feature branch, because you're rewriting history at the origin which is not reflected locally. I would suggest squashing commits on feature branches before merge with `rebase -i`, but not creating differences between feature branches and `master`, and certainly not squashing commits already in `master`.

Meanwhile it also doesn't solve the problem that the log is full of things like "Merge remote-tracking branch origin-master into develop-sync". Again, that's a simple master of `git rebase origin/master` instead of `git merge origin/master`, and fixing conflicts in the original commits rather than in separate merge commits.

Just my opinion.

**Comment by antgel** [comment]
I haven't been around for a while, and I just saw this:
![image](https://user-images.githubusercontent.com/295571/159067410-34fd79ee-03b2-4311-9d40-e9b8ce6f4de6.png)

Seriously team? Do you not care about the git commit history at all? Or are we still in hack mode, years later? How can I care more than you? :(

**Comment by geekgonecrazy** [comment]
As mentioned by Diego above PRs are squashed.  The reason PR's are like this is just because of the ease of the click in github ui to update.  Not all devs live in CLI so its a lot easier for them to bump and sync with develop from the UI using github.

I'm going going to go ahead and close this out though.  As this isn't a bug

**Comment by antgel** [comment]
Which makes it hard to review PRs that are more than one commit, of course. But fine, good to get a response.
