### ISSUE TITLE
Complete API List? 

### ISSUE THREAD

**Issue by tzeyangng** [RocketChat/Rocket.Chat#1059]
Hi,

Are there already available API to create users, channels, private group? Thinking to use rocketchat for a platform we trying to build however need to help to setup users, channels and group in advance when user create account on our system to avoid duplicate account creation. thanks.

Love what i see so far. thanks.
##

**Comment by nonsintetic** [comment]
There's an article on that in the wiki, not sure if it's still up to date though:
https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs

For the user part you could use oAuth, make your platform an oAuth provider and have RocketChat be the client. Basically users click a button instead of registering an account the first time they come to RocketChat.

**Comment by tzeyangng** [comment]
thanks, i do found the wiki, but it is lacking the API i need. What i plan to do is make the rocket chat part of my application, it should be transparent to the user.

**Comment by graywolf336** [comment]
There are currently no REST APIs for the items you're wanting. If, however, you are using Rocket.Chat and write a package then you could use the various methods located here: https://github.com/RocketChat/Rocket.Chat/tree/master/server/methods

**Comment by tzeyangng** [comment]
Ok, thanks for this info.

**Comment by graywolf336** [comment]
There are plans to add the REST APIs, but I don't know what the timeline looks like.

**Comment by geekgonecrazy** [comment]
Yes this is for sure being planned.  Work is about to start pretty heavily on this in the next few weeks.

**Comment by capensisma** [comment]
@geekgonecrazy next week or next years ? :D

**Comment by geekgonecrazy** [comment]
@capensisma
> Yes this is for sure being planned. Work **hopefully** will start pretty heavily on this in the **next few weeks**.

;-) you know life, everything doesn't always go according to plan.

**Comment by capensisma** [comment]
yeah i don't but you have to keep people posted with the progress!

it seems you have bulk/createRoom and bulk/registerUser already written but the roles aren't added! what Can we do to get those two API nodes working ?

**Comment by graywolf336** [comment]
If there's been no work on it, how can they update with progress?

From the talks months ago, they were thinking about completely redoing the
rest api and the current ones aren't fully supported.

**Comment by capensisma** [comment]
I agree but at least don't let people hanging tell them we are rewriting the API or something!

but what's the hold up? the current API seems very good! just add those roles for the two last API nodes!!

**Comment by geekgonecrazy** [comment]
@capensisma Like I said next few weeks.  I never said I was working on it already.  Second of all we all have full time jobs.  

Third I nor any of us owe you anything.  So don't act entitled.  This is an open source project, if you would like it done sooner.  Feel free to open a Pull Request with the changes.  There is always the option of hiring someone to write it for you if you need the changes sooner.

**Comment by capensisma** [comment]
@geekgonecrazy you owe me to show where can add the roles and or at least show me that so I can get those two nodes working!
I searched in permissions and methods files on the server and didn't find the right place to add those roles?

How can I just quick fix that bulk/createRoom and bulk/registerUser so any admin can access it instead of current testagent or adminuation ...

I will write my code bro, I'm just asking about this, if you can help me get it so at least show me where I can get it working...

Thanks bro

**Comment by neurobe** [comment]
Just like to say how appreciative I am of the core team devoting so much unpaid time to this open source, community supported, not for profit project. Since I am not capable to doing the work (well) myself, I would certainly avail of any bounty system that were to be set up. A mid-tier Role ("supervisor") is big for me - I see there are a few stubs in the code already...

**Comment by geekgonecrazy** [comment]
@neurobe thank you!  @RocketChat/core always glad to see appreciation. :)

Yes there is some incomplete code around a mid tier.  I think there is an issue related to that around somewhere.  Would be good to bump that where ever it is.

Never used a bounty system.  Might be worth opening an issue to discuss it.  I don't know what kind of impact it might have on an open source community. Would be good to discuss it, and see what the other devs think.

**Comment by capensisma** [comment]
I agree :) and @neurobe is awsome :D 

@geekgonecrazy I found something here `Roles.getRolesForUser` can guide me on this!

**Comment by akennedy** [comment]
How about something like this for sending direct messages via rest api?

`#/server/restapi/restapi.coffee`
```
# send a direct message to a username
Api.addRoute 'direct/:username/send', authRequired: true,
  post: ->
    Meteor.runAsUser this.userId, () =>
      rid = Meteor.call('createDirectMessage', @urlParams.username )
      Meteor.call('sendMessage', {msg: this.bodyParams.msg, rid: rid.rid} )
    status: 'success' #need to handle error
```

**Comment by andela-osogunle** [comment]
Does this PR https://github.com/RocketChat/Rocket.Chat/pull/3525 cover the request on this issue. Also, will there be an API exposed to create users?

**Comment by sampaiodiego** [comment]
thanks @andela-osogunle for recording us about this issue.
but looks the PR doens't cover all requests of this issue.

also, we plan to have a large list of APIs (including user creation), but at the moment there is only the [bulk/register](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/restapi/restapi.coffee#L144) ..

**Comment by andela-osogunle** [comment]
Thanks @sampaiodiego 
I think this method might be able to do what I want. Just that I dont think it is available on version 
"versions": {
    "api": "0.1",
    "rocketchat": "0.5"
  }
Pinging `/api/bulk/register` returns 
{
  "status": "error",
  "message": "API endpoint does not exist"
}
I don't think there is a rest API for this.

**Comment by andela-osogunle** [comment]
Thanks @sampaiodiego that works.

**Comment by prathimaroyal** [comment]
Hi, 
I am trying to create rocket chat notification for Jenkins. But its failing and giving me error. Could someone please help me. Logs are attached.

Thanks
Prathima
![error_rc_](https://cloud.githubusercontent.com/assets/20189490/16420647/0a2d02fc-3d4a-11e6-82dc-3ec9b8d6245f.png)
![rocket_chat](https://cloud.githubusercontent.com/assets/20189490/16420648/0a375874-3d4a-11e6-99e2-47595f42316c.png)

**Comment by engelgabriel** [comment]
@rodrigok can you help here?

**Comment by geekgonecrazy** [comment]
@prathimaroyal can we move this to a new ticket or even resume our conversation from the #support channel? https://demo.rocket.chat/channel/support?msg=4WWnjt2B5TMojZgq4

**Comment by monika18** [comment]
Hello, Could anyone know about the api which gives unread message count?

**Comment by graywolf336** [comment]
Closing this in favor of the new documentation: https://rocket.chat/docs/developer-guides/rest-api
