### ISSUE TITLE
Preventing certain roles from DM-ing, inviting, mentioning others

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#10590]
* Version of Rocket.Chat Server: 0.63.1

We have a business need that requires tweaks to the current permissions setup. 

Basically, we have three categories of users - clients, on-prem users, and remote users. We want to prevent our remote users from DM-ing/mentioning client and inviting them to a private group, room. However, they can do all of the above with each other or with on-prem users. To get around this issue, currently we have two separate instances, but the maintenance of both is proving a hassle. 

I am writing to understand if a feature like above is in scope of the product vision and is actually planned in the product roadmap or we should look to develop this on our own/set a bounty. Any guidance will be much appreciated. Thanks.

**Comment by theorenck** [comment]
Hi @akachapati we will analise your request to understand if we can generalize your specific needs in a way that would be possible to improve our permission/role model and give it more flexibility.

**Comment by marceloschmidt** [comment]
We will work on restructuring our permissions system, which may or may not solve the issue for you.
