### ISSUE TITLE
Google OAuth: redirect_uri_mismatch

### ISSUE THREAD

**Issue by wghilliard** [RocketChat/Rocket.Chat#10594]
### Description:

When authenticating with Google using OAuth, a 400 error is produced stating that the uri provided by Rocket.Chat does not match the allowed redirect uri(s) specified in the Google API.

```
Google

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://<my_rocketchat_server>/_oauth/google?close, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/<my_google_api_id>
```

The registered redirect uri(s) in the Google API are:
- `https://<my_rocketchat_server>/_oauth/google`
- and for debugging purposes `https://<my_rocketchat_server>/_oauth/google?close`

I think the OAuth request from Rocket.Chat is accidentally appending the `?close` url parameter and the Google API isn't gracefully handling it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.9.4
* mongoDB Version: Not certain.

### Steps to Reproduce:

1. Basic install of Rocket.Chat via Snap
2. Create a Google API
3. Create credentials for the new Google API (Credentials --> Create Credentials --> OAuth Client ID --> web application)
3. Register Rocket.Chat's redirect URI with the Google API and corresponding secrets with Rocket.Chat (Administration --> OAuth --> Google).
4. Access the Rocket.Chat login screen, attempt to authenicate with Google OAuth

### Expected behavior:

Successful authentication and redirection from Google to Rocket.Chat.

### Actual behavior:

Google producing a 400 error indicating that the provided redirect URI is not whitelisted.

### Relevant logs:

There are no errors reported in the server log.

**Comment by amonemian** [comment]
I had the same problem. 
Add "?close" at the end of your Authorized redirect URIs in the Google Api. (the URI would be yourWebsiteUrl/_oauth/google?close)
It works now for me.

**Comment by wghilliard** [comment]
@amonemian at the time of creating this issue, your suggested fix was not working (as cited in the issue, `The registered redirect uri(s) in the Google API are:... and for debugging purposes https://<my_rocketchat_server>/_oauth/google?close`). However, after testing it today, the URI seems to be working. I guess Google is allowing the excess parameters and this issue can be closed. 

Thanks
