### ISSUE TITLE
Some i18n.json file name not recognized by tap-i18n

### ISSUE THREAD

**Issue by trongthanh** [RocketChat/Rocket.Chat#10603]
### Description:

In latest develop build, at the language selection dropdown, we see some language not recognized by tap-i18n so they are displayed as: lc-CC (for example: vi-VN, th-TH) instead of the human-friendly language name.

![screen shot 2018-04-27 at 2 26 35 pm](https://user-images.githubusercontent.com/234226/39350309-fc7a2eea-4a27-11e8-83b7-be4aa39db7d7.png)

AFAIK, tap-i18n uses a [language name lookup list](https://github.com/TAPevents/tap-i18n/blob/master/lib/plugin/etc/language_names.js) to infer the language name. If the i18n.json files are named with unregconized code, the raw file name is displayed instead (so vi-VN.i18n.json -> vi-VN...).

My suggestion is to rename these files to comply with tap-i18n's language table. If this is not possible, maybe we have to add a tap-project.i18n file to list the languages explicitly. 

I'm attempting the latter approach in a fork but am getting error with tap-i18n and still figuring how to get it work.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-develop
* Deployment Method(snap/docker/tar/etc): Ubuntu; mannual install
* (others items  are not relevant)

### Steps to Reproduce:

1. Open My Account > Preferences
2. Click on the language dropdown at Localization section
3. Look for Thai or Vietnamese but get th-TH and vi-VN

### Expected behavior:

th-TH should display as Thai; vi-VN should display as Tiếng Việt; etc...

### Actual behavior:

Some languages are display with lc-CC instead.

**Comment by fliptrail** [comment]
I am working on it.
