### ISSUE TITLE
[BUG] CSS Chat now button text is delayed from button

### ISSUE THREAD

**Issue by xFuture603** [RocketChat/Rocket.Chat#10600]
### Description:
The chat now button text is shifted away from the normal button. The used language is german in my case.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Browser: Google Chrome Version 66 (64-bit) and Mozilla Firefox Version 59.0.2 (64-bit) 

### Steps to Reproduce:

1. Navigate to a group channel
2. Scroll up and down until a person pops up for direct messaging

### Expected behavior:

That the text (in german) "Jetzt chatten" is inside the button. 

### Actual behavior:
Some text is outside of the button

### Relevant logs:

Picture of the current state: [Chat now button](https://imgur.com/a/xdt6JVh)

**Comment by theorenck** [comment]
Thank you @xFuture603 for your feedback. Just a minor clarification, is this the "chat now" button inside the "leader bar"?

**Comment by xFuture603** [comment]
Hey @theorenck. Yes the "chat now" button is right under the little navbar with the "info-icon", "search-icon", "members-item" and "useradd-item". I mentioned this Bug inside of a private group chat.
