### ISSUE TITLE
Fix General -> Site URL example

### ISSUE THREAD

**Issue by laptopdude90** [RocketChat/Rocket.Chat#10619]
Currently, under Administration -> General -> Site URL, the example, "https://chat.domain.com/", has a trailing slash. This is detrimental because it turns out that when including a trailing slash, pictures don't load on the mobile app.

It would be ideal to either change the example and warn about the slash causing issues, or filter it out behind the scenes. Once I know which one would be preferred, I'd be happy to submit a PR.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #10716 which is a better and more detailed report.

Cheers
Thomas
