### ISSUE TITLE
Lack documentation for multiple instances under Apache

### ISSUE THREAD

**Issue by TheMythPT** [RocketChat/Rocket.Chat#10620]
I've been searching around but I didn't find anything clear (I can be overlooking something, and if this is a duplicated i apologize).
Most part of detailed documentation is related to Nginx, a webserver that I, personally, don't run.
Would be very helpful to have a detailed documentation like this [one](https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/) but for Apache.

Best regards

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

While I get that there is currently no documentation on that, this is not typically considered a bug, at least not in the server software. I'd suggest the following:

Open a topic in the forums: https://forums.rocket.chat/c/community-support

If there will be found a proper solution somebody could create a pull request for the [Rocket.Chat Documentation repository](https://github.com/RocketChat/docs/).

Cheers
Thomas
