### ISSUE TITLE
Unable to create private groups on mobile app

### ISSUE THREAD

**Issue by steedos** [RocketChat/Rocket.Chat#1062]
![image](https://cloud.githubusercontent.com/assets/3104826/10412071/e36eb55e-6fac-11e5-92a2-b82624406425.png)

**Comment by ninja-** [comment]
does the same happen if you dont use chineese characters in room's name, because that's a known issue?

**Comment by steedos** [comment]
It's because of I can not touch on the save button, it is covered by the iPhone keyboard.

When create channel, will have the same problem.

发自我的 iPhone

**Comment by geekgonecrazy** [comment]
You can scroll that left pane up, since the content is resized for the keyboard.  I just tried it and it wasn't ideal, but it is possible.
