### ISSUE TITLE
User List Panel Showing Incorrect Online/Presence Status

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#10634]
### Description:

User's online/prescence status is incorrect on the left panel compared to what is being shown when you click into the user message.  It is showing many users are online although they are not online. The user r2z2.api is one of the examples in the screenshot who is impacted.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Linux CentOS 7
* Deployment Method(snap/docker/tar/etc): manual
* Number of Running Instances: 4
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3
* mongoDB Version: 3.2

### Steps to Reproduce:

1. Look at the user list on the left shows user is online (r2z2.api in screenshot)
2. Click on user and it shows the correct online status
3. User is definitely not online

### Expected behavior:

Expected to show that the user is offline in the user list on the left.

### Actual behavior:

The user is shown as online.

![wrongstatus](https://user-images.githubusercontent.com/8405384/39493108-44e133ae-4d57-11e8-8ae3-68a5b1b67ff7.png)

**Comment by richardwlu** [comment]
@rodrigok Hi, can you help with this one also?

**Comment by 707eric** [comment]
We are having the same issue. Users appear offline that aren't offline on one server.

On second server I have a totally separate chat running and there is at east one account that always appears to be online.

The setup up for both servers is pretty generic, AWS EC2 servers.

**Comment by rodrigok** [comment]
> @707eric I know if you stop your server while you have some users online they will be online until the user connect and disconnect again

@ggazzo that's not actually true, if another server is running or when the server restart, all the old sessions will be deleted and all users related to those sessions will be calculated again and changed to offline if no other sessions exists.

**Comment by ggazzo** [comment]
I have a database with some online users forever...maybe something I made developing/restarting again again and again...so @707eric ignore my comment. 

@rodrigok any idea why they have offline users online?

**Comment by wreiske** [comment]
Possibly related? 
![clipboard - november 28](https://user-images.githubusercontent.com/6295044/49200189-a62eca00-f369-11e8-8e40-3e538894cf47.png)
Latest 0.72.0 release.
