### ISSUE TITLE
Roles & Permissions [$250]

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#1063]
Proposing a tab in the Administration section under "Users" called "Roles" which would allow Adding/Removing of custom roles other than the current default Guest and Admin.  Under the Roles box would be a Permission section which then allows you to assign granular permissions for everything to each role.  Modules (ie. Live Chat, etc.) need to be able to add permissions to this table such as "Receive Chats" "Edit Departments" etc. so we could add a role and permissions accordingly.

**Comment by alisalaah** [comment]
Roles is straight forward but I think it would be good when adding a role to designate if it inherits other roles, example.

Guest [hardcoded role]
User (inherits Guest)
Volunteer (inherits User)
Employee (inherits Volunteer)
Manager (inherits Employee)
Chat Agent (no inheritance)
Admin [hardcoded role]

Then for users I could make someone "Manager" or "Volunteer, Chat Agent" for assigning roles to a user

Then in permissions you would have LiveChat module adding a permission "Chat Agent" or "Receive Chats" and you would give that permission to the role you wanted while something like "Manage Departments" you would give that to the "Manager" role or what not.

**Comment by alisalaah** [comment]
Concept in screenshots of a "Roles" tab under users would have these sections/panels... something to show inheritance of roles... the disabled checkbox for User / Default Channel is because it's inherited. Design guys can do better than me... but something that functions like this and of course I didn't put an "Add Role" anywhere above...

![screen shot 2015-10-11 at 10 58 07](https://cloud.githubusercontent.com/assets/277910/10414610/758ecf46-7007-11e5-9994-313ee0e0bf65.png)
![screen shot 2015-10-11 at 10 59 26](https://cloud.githubusercontent.com/assets/277910/10414611/78aac888-7007-11e5-8501-70b455b003cd.png)
![screen shot 2015-10-11 at 10 59 10](https://cloud.githubusercontent.com/assets/277910/10414612/78db1b50-7007-11e5-99c1-e689990b8aee.png)

**Comment by Theaxiom** [comment]
To expand on this, it would be nice to be able to assign roles on a per-channel basis; this would allow you to create types of users who only have access to channels in which those roles are assigned access. This is kind of like private groups, but instead of invite-only, but could apply to public channels to make them semi-public.

**Comment by neurobe** [comment]
What is need is a UI to the alanning:roles code already baked in.

**Comment by internalfx** [comment]
+1

**Comment by sampaiodiego** [comment]
https://www.google.com.br/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjng4fCprHJAhXPM5AKHbOxC6cQjRwIBw&url=https%3A%2F%2Fplan.io%2Froles-and-permissions%2F&psig=AFQjCNFS8RNXP5WirgIfOiL_8FF1Z9dvSQ&ust=1448737435805195

**Comment by sampaiodiego** [comment]
![image](https://cloud.githubusercontent.com/assets/8591547/11447206/86f1b05e-9529-11e5-9647-c16f35b32e33.png)

**Comment by rwakida** [comment]
Is this a mock-up or actual screenshot?

**Comment by sampaiodiego** [comment]
Im sorry @rwakida , its actually a mockup I'll use as reference.

**Comment by AdrianoCahete** [comment]
Just remove all that "green checkmarks", @sampaiodiego

**Comment by neurobe** [comment]
"Project" may not have a meaning in the RC context, but I would like to see a variation on the word included. There is a separate feature request (by me :-)) for actions generated and scheduled by a Calendar fly-in. To generalise such a capability in relation to Roles and Permissions I would like to suggest a modification to the mockup... Create Action... Edit Action..

Fly-in panels can then pick this up how they see fit. One such application would be to manage projects, if there were a flyin for that. There could be many others, but the generic term would be "Action".

**Comment by rwakida** [comment]
Thanks @sampaiodiego.  I was just curious how far you've gotten on it  :smile:

**Comment by sampaiodiego** [comment]
So guys, with #1555 I consider this issue done.
Any feedback are welcome =)

**Comment by neurobe** [comment]
wow. Good job.

**Comment by engelgabriel** [comment]
Good job indeed! Congratulation @sampaiodiego

**Comment by Sing-Li** [comment]
:+1: ...you won't believe how many installations  this UI helped!   Stellar!
