### ISSUE TITLE
Log Error: Cant Mix Remove and Get Fields

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#10635]
### Description:

The logs show the following error: Can't mix remove and get fields

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Linux CentOS 7
* Deployment Method(snap/docker/tar/etc): manual
* Number of Running Instances: 4
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3
* mongoDB Version: 3.2

### Steps to Reproduce:

1. Not sure how to reproduce.

### Expected behavior:

Not an error?

### Actual behavior:

An error shows in the logs and from Rocket.Cat

### Relevant logs:

    1|rocket.c | 2018-05-01 13:19:05 505: rocketchat_logger.js:278 API v1 Logger ➔ debug GET: /api/v1/settings.public?fields=%7B%22type%22:1%7D&query=%7B%22_id%22:%7B%22$in%22:%5B%22Site_Url%22,%22CDN_PREFIX%22,%22Site_Name%22,%22Assets_favicon_512%22,%22UI_Use_Real_Name%22,%22UI_Allow_room_names_with_special_chars%22,%22Favorite_Rooms%22,%22Accounts_OAuth_Google%22,%22Accounts_OAuth_Facebook%22,%22Accounts_OAuth_Github%22,%22Accounts_OAuth_Gitlab%22,%22Accounts_OAuth_Linkedin%22,%22LDAP_Enable%22,%22CAS_enabled%22,%22CAS_login_url%22,%22Accounts_ShowFormLogin%22,%22Accounts_RegistrationForm%22,%22Accounts_PasswordReset%22,%22Accounts_EmailOrUsernamePlaceholder%22,%22Accounts_PasswordPlaceholder%22,%22Accounts_EmailVerification%22,%22Accounts_AllowUserProfileChange%22,%22Accounts_AllowUserAvatarChange%22,%22Accounts_AllowRealNameChange%22,%22Accounts_AllowUsernameChange%22,%22Accounts_AllowEmailChange%22,%22Accounts_AllowPasswordChange%22,%22FileUpload_Storage_Type%22,%22Message_HideType_uj%22,%22Message_HideType_ul%22,%22Message_HideType_au%22,%22Message_HideType_mute_unmute%22,%22Message_HideType_ru%22,%22Message_ShowDeletedStatus%22,%22Message_AllowDeleting%22,%22Message_AllowDeleting_BlockDeleteInMinutes%22,%22Message_ShowEditedStatus%22,%22Message_AllowEditing%22,%22Message_AllowEditing_BlockEditInMinutes%22,%22Message_AllowPinning%22,%22Message_GroupingPeriod%22,%22Message_MaxAllowedSize%22,%22Accounts_CustomFields%22%5D%7D%7D&count=0&offset=0
    1|rocket.c | 2018-05-01 13:19:05 506: Can't mix remove and get fields

**Comment by subesokun** [comment]
Got the same issue and now RC is crashing permanently. As there has been a DB migration we're also not able to rollback hence this issue is very critical to us!

**Comment by graywolf336** [comment]
This isn't an error, it's just a warning. This is due to our cache layer. As it's not an error, I'll be closing this.

**Comment by 24601** [comment]
@richardwlu - we are experiencing the same issue and trying to understand what is going on. It sure seems like a "warning" as @subesokun mentioned, but it's also killing the server, so, either the correlation with the warning and it dying is false or the warning isn't actually a warning and is causing the server to die...

Any further experience you have on this?

**Comment by graywolf336** [comment]
@MarcosSpessatto can you look into this?

**Comment by richardwlu** [comment]
@24601 The server doesn't die for us so I can't say the correlation of the warning and the server dying is always true as your case may be different.

**Comment by quangtzimong** [comment]
We had some trouble with the servers filesystem last days, but I'm pretty sure it has nothing to do with this "warning". Under this circumstances this message came into my awareness and it will always appear, when I open Rocket.Chat+ on my IOS device. So every time this app connects to server I will find this message. I haven't checked Android yet.
