### ISSUE TITLE
[error-room-not-found] when trying to add user to a private group from API with [add-user-to-any-p-room] permission

### ISSUE THREAD

**Issue by driesmeyers** [RocketChat/Rocket.Chat#10639]
### Description:

I'm trying to add a registered user to a private group. I'm posting a request via API (https://rocket.chat/docs/developer-guides/rest-api/groups/invite/) with admin credentials. The admin is not a member of the private group but should be able to add another user with the add-user-to-any-p-room permission. I keep getting 'error-room-not-found' as error type. However the request seems to work when the admin is member of the private group. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-develop
* Operating System: macOS 10.13.4 High Sierra
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.11.1
* mongoDB Version: 3.4.10

### Steps to Reproduce:

1. Enable add-user-to-any-p-room permission for user that is sending the request
2. Create second user
3. Set request headers x-auth-token and x-user-id
3. Send POST request to http://localhost:3000/api/v1/groups.invite
Body:
{
	"userId": "75c9mWS83yCTcqn2X", // straight from database
	"roomId": "dnqSmTG52uCzyPm3j" // straight from database
}

Same request works when the admin is member of the private group. 

### Expected behavior:

User is added to the group while admin is still not a member. 

### Actual behavior:

Response with error type "error-room-not-found'

### Relevant logs:
Nothing relevant coming from logs.

Response: 
{
    "success": false,
    "error": "The required \"roomId\" or \"roomName\" param provided does not match any group [error-room-not-found]",
    "errorType": "error-room-not-found"
}

error thrown in Rocket.Chat/packages/rocketchat-api/server/v1/groups.js line 17

**Comment by cloudsandladders** [comment]
I am also seeing this.

**Comment by q16marvin** [comment]
i have still exakt this problem, admin with permission "add-user-to-any-p-room" cant add users to private rooms where admin is not a member, what do i wrong?

**Comment by wojciechkepka** [comment]
I can also confirm that this is still a problem, tried to use api today to invite users to a private group which admin user is not a part of and i got:
`The required "roomId" or "roomName" param provided does not match any group [error-room-not-found]`

And I made sure that the Admin role has `add-user-to-any-p-room`

**Comment by jeffreyvanhees** [comment]
I noticed this issue was closed, but I'm still encountering the same problem. Has there been any progress on finding a solution?

For context, I'm making direct HTTP requests without using any packages, which suggests the issue lies with the API itself rather than client implementations.
