### ISSUE TITLE
[NEW] REST API to "hide" a room from the list of chats

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10630]
### Description:

We're implementing actions on the iOS and Android apps and one of the actions is to hide a room, didn't found any API to do that right now.

**Comment by MarcosSpessatto** [comment]
Hey @rafaelks, this endpoint already exists. You can find them in [groups](https://rocket.chat/docs/developer-guides/rest-api/groups/close/), [channels](https://rocket.chat/docs/developer-guides/rest-api/channels/close/), and [DMs](https://rocket.chat/docs/developer-guides/rest-api/im/close/).

**Comment by rafaelks** [comment]
@MarcosSpessatto Thank you! 👍
