### ISSUE TITLE
Application Web View Not Showing Properly

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#10636]
### Description:

Upon logging in, users are seeing the app missing just about everything except the toolbar and the logo. This happened in the Chrome browser version 47.0.2526.106.

One user was able to properly bring the view into place:

> Also, i believe i have found the issue. It looks to have been an error in the source code for the screen size/resolution. I inspected the Source Code for the border size. Though it was correct in the source code, i refreshed it from 950x951 to 1000X1000 on my machine and the chat screen expanded to full size. I noticed the issue with the border size when i found, that a sliver of white at the top of the screen was actually the chat room. Hope this helps.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Linux CentOS 7
* Deployment Method(snap/docker/tar/etc): manual
* Number of Running Instances: 4
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3
* mongoDB Version: 3.2

### Steps to Reproduce:

1. Log in with Chrome browser on Windows version 47.0.2526.106

### Expected behavior:

Expect the application to show properly.

### Actual behavior:

The application is not showing a majority of elements. Screenshot is attached.

![rcj_blank](https://user-images.githubusercontent.com/8405384/39493715-72a09f62-4d59-11e8-9c48-45a485be674a.png)

**Comment by richardwlu** [comment]
@geekgonecrazy Do you think you can help shine some light on this?

**Comment by richardwlu** [comment]
@rodrigok Hi, can you help with this?

**Comment by geekgonecrazy** [comment]
Really not enough info to go on.  Try adding some logs from server and browser

**Comment by geekgonecrazy** [comment]
Going to close not enough info
