### ISSUE TITLE
NEW LOGO DESIGN REQUEST

### ISSUE THREAD

**Issue by neemanbhat** [RocketChat/Rocket.Chat#10649]
Hi, I will like to design a new logo for the app if you allow me to, i will try to keep in mind all the requirements if specified. thankyou

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this issue as it's no bug. You may feel free to contact the Rocket.Chat folks by other means (chat or forums) and ask if they are in need of a new logo. Right now I don't have the feeling that this is the case, but that's only my take.

Cheers
Thomas
