### ISSUE TITLE
Crash after specific message

### ISSUE THREAD

**Issue by neurolabs** [RocketChat/Rocket.Chat#10643]
### Description:

Rocket.Chat crashes when trying to send the message:
```
Oder so: ```find /var/www/static -type f -regextype posix-extended -iregex '.*\.(css|csv|html?|js|svg|txt|xml)' -exec zopfli '{}' \;```
https://theartofmachinery.com/2016/06/06/nginx_gzip_static.html
```

### Server Setup Information:

* Rocket.Chat Version: 0.64.0
* NodeJS Version: 8.9.3 - x64
* Platform: linux
* ReplicaSet OpLog: Enabled
* Commit Hash: 2fae79ab10
* Commit Branch: HEAD
* Deployment Method: docker 
* Number of Running Instances: 1
* mongoDB Version: 3.2

### Steps to Reproduce:

1. use rocketchat via the web ui or via the electron desktop app (other clients untested)
2. send the message

### Expected behavior:

Server accepts the message

### Actual behavior:

Server becomes unresponsive for all users, node process goes into a busy loop (100% cpu)

### Relevant logs:

only ordinary entries, nothing related to the behavior

**Comment by neurolabs** [comment]
Tried to test for a regression, but downgrade to 0.63.3 does not work due to db migrations:

```
Exception in callback of async function: Error: [Can't find migration version 115]
    at Object.Migrations._findIndexByVersion (/app/bundle/programs/server/packages/rocketchat_migrations.js:410:9)
    at Object.Migrations._migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:277:23)
    at Object.Migrations.migrateTo (/app/bundle/programs/server/packages/rocketchat_migrations.js:206:23)
    at xrun.js (/app/bundle/programs/server/app/app.js:6545:25)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /app/bundle/programs/server/app/app.js:11980:1
    at /app/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>:null:null)
    at /app/bundle/programs/server/boot.js:220:19
    at /app/bundle/programs/server/boot.js:471:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11
```

**Comment by neurolabs** [comment]
no active integrations (compared to #10637 )

**Comment by archang3l-media** [comment]
I can reproduce the issue when sending the same message, otherwise the upgrade from 0.63.3 to 0.64 (with a small stop at 0.64-rc4 went fine).

**Comment by neurolabs** [comment]
I hope this is also fixed by #10627

**Comment by neurolabs** [comment]
Issue is fixed in 0.64.1, thanks.

**Comment by mboogert** [comment]
Unfortunately I would like to ask you to reopen this issue.

I'm able to crash my 0.69.2 Rocket.Chat server using the message below.
MongoDB 3.6 is used in combination with a docker-compose setup of RC, version 0.69.2.


```dork@rot-sbc1-dc1:/var/log$ grep 31852734555 syslog\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28788]: INFO: <script>: 186269e35488949024645fdb7d80138c@sop.wlvaip.not - +32123456789\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28788]: INFO: <script>: 186269e35488949024645fdb7d80138c@sop.wlvaip.not - CB, Checking restrictions nr: +32123456789 block: n acc: zagnitOLD\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, handling call to: +31123456789 on account: enna02, and to: +32123456789 on account: zagnitOLD dest: +31123456789\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, accounting from +32123456789 to id: 2213\ndork@rot-sbc1-dc1:/var/log$ grep 2hdecaye0d4f0b86201f42027c546807 syslog\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - LCR, 1 Delivering to +31123456789 from +31334455667 call to GW 62.180.237.73\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, handling call to: +31123456789 on account: enna02, and to: +32123456789 on account: zagnitOLD dest: +31123456789\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Channels 0 used out of 5 for account enna02\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, No price found in reseller table for: +31123456789\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Price found for nr: +31123456789 ppc 0.0250000000 pps 0.0001416660\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Prefix is ON the limitless_list\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, dialog:start\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, redirect accounting from +31334455667 to id: 1\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, accounting from +32123456789 to id: 2213\nSep 27 00:36:28 rot-sbc1-dc1 /usr/sbin/kamailio[28774]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, dialog:end\nSep 27 00:36:28 rot-sbc1-dc1 /usr/sbin/kamailio[28774]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Booking credits 0.0259916620 from: 2213\nSep 27 00:36:28 rot-sbc1-dc1 /usr/sbin/kamailio[28774]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Updated end_time for internal (free) leg\ndork@rot-sbc1-dc1:/var/log$`

**Comment by mboogert** [comment]
ping @ @neurolabs

**Comment by neurolabs** [comment]
Hi @mboogert ,

I just reported the initial bug, I am not an official rocketchat dev.

If you think/know that this issue is the same or related, you could pass more information (are you also seeing 100% CPU etc.). And since this might actually not be a regression, I personally would just open up a new issue, which can then easily be marked as a duplicate.

Cheers,

Ole
