### ISSUE TITLE
Unable to paste in OSX App

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#1064]
Using the Mac OSX app am unable to paste.

**Comment by geekgonecrazy** [comment]
@alisalaah does this happen to be only sometimes?   Or after you paste an image?  Because I use the OSX app daily and it works fine.

**Comment by alisalaah** [comment]
Working now and not sure what caused the previous bug. We can close this
maybe and reference it if it resurfaces since there's no way to test while
the bug is gone.
