### ISSUE TITLE
some js errors

### ISSUE THREAD

**Issue by viroos** [RocketChat/Rocket.Chat#10647]
### Description:

webview: Uncaught TypeError: Cannot read property 'css' of undefined

### Server Setup Information:

* Version of Rocket.Chat Server:  hosted rocket chat (https://rocket.chat/cloud)
* Operating System: Linux phoenix 4.17.0-1-MANJARO #1 SMP PREEMPT Mon Apr 23 19:48:42 UTC 2018 x86_64 GNU/Linux
* Deployment Method(snap/docker/tar/etc): hosted rocket.chat (https://rocket.chat/cloud)
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:
open rocket chat. (for example rocket.chat+ but it happens also on mobile and in browsers - chromium abd furefix

### Expected behavior:

I should see channels and messages, I should be able to chat

### Actual behavior:

I see blinking dots.

### Relevant logs:

Error from chromium dev console:

Exception from Tracker afterFlush function: undefined
29e08e345195fd2d8a7dd2c6629194078bba4142.js:1:6367
TypeError: e is null undefined
29e08e345195fd2d8a7dd2c6629194078bba4142.js:1:6367
tapi18n.js/this.isRtl@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:209:62868
main.js/<@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:199:9937
s@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:179:2192
n/<@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:34637
e._withTemplateInstanceFunc@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:37671
n@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:34546
e.prototype.constructView/<@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:35513
n/</<@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:18140
f._withCurrentView@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:23078
n/<@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:87:18108
e._runFlush@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:43:3928
a@https://xxx.rocket.chat/29e08e345195fd2d8a7dd2c6629194078bba4142.js?meteor_js_resource=true:1:2690
 undefined

**Comment by tassoevan** [comment]
Is this still happening?

**Comment by tassoevan** [comment]
I'm closing it due to inactivity.
