### ISSUE TITLE
Potentially compromised dependency getcookies (via mailparser)

### ISSUE THREAD

**Issue by segphault** [RocketChat/Rocket.Chat#10641]
### Description:

On April 20, a seemingly routine [dependency update PR](https://github.com/RocketChat/Rocket.Chat/commit/a506ee0e810df9afe5d426915350fbe342fd6415#diff-32607347f8126e6534ebc7ebaec4853dR9717) introduced what appears to be a compromised package.

Updating [`mailparser`](https://www.npmjs.com/package/mailparser) from version 2.2.0 to 2.2.3 pulled in a transitive dependency called `http-fetch-cookies`, which has a sub-dependency called `express-cookies`, which depends on a package called `getcookies`. The `getcookies` package apparently [has a backdoor](https://npm.runkit.com/getcookies/test/harness.js?t=1525249320108) (reported [here](https://news.ycombinator.com/item?id=16975025)) that looks like it uses the `vm` module to run arbitrary code provided from a request inside of the application's context.

It appears that npm has since removed `http-fetch-cookies`, `express-cookies`, `get-cookies` and `mailparser` 2.2.3. According to google cache, mailparser 2.2.3 was published 17 days ago with the added dependency. It's worth noting that mailparser [became deprecated](https://blog.nodemailer.com/2018/03/11/spring-cleaning/) last month due to lack of funding, and this compromise seems to have happened since then. As mailparser has 67,000 weekly downloads, this is quite concerning.

**Comment by bosko** [comment]
This makes it impossible to start Rocket.Chat. After cloning project on Ubuntu 16.04 `meteor npm install` fails with:

```
npm ERR! 404 Not Found: mailparser@https://registry.npmjs.org/mailparser/-/mailparser-2.2.3.tgz
```

**Comment by evilpacket** [comment]
Here is some more context about the mentioned modules. https://blog.npmjs.org/post/173526807575/reported-malicious-module-getcookies

**Comment by fifou17** [comment]
same for me but mine its 
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/unset-value-4255578a/package.json'
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/unset-value-4255578a/README.md'
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/unset-value-4255578a/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/unset-value-4255578a/index.js'
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/aws-sdk-8c444618/clients/alexaforbusiness.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/protobufjs-497d90ae/docs/fonts/OpenSans-Regular-webfont.woff'
npm WARN tar ENOENT: no such file or directory, open '/home/Bureau/m/node_modules/.staging/chimp-6e0f149b/images/test-frameworks.png'
npm ERR! code E404
npm ERR! 404 Not Found: mailparser@https://registry.npmjs.org/mailparser/-/mailparser-2.2.3.tgz

**Comment by Sing-Li** [comment]
Thanks @segphault @bosko @evilpacket  and  @isabellarussell  for reporting this!
