### ISSUE TITLE
Message search method

### ISSUE THREAD

**Issue by ispryt** [RocketChat/Rocket.Chat#10659]
Hello!

Where can I change the default message search method?
By default, it looks like a complete match of words.
But where can I change this "default" for a partial coincidence?

Thank you!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

This is a duplicate of #9647. The answer is: currently you can use regular expressions to achieve what you want. There is no UI setting though to set this kind of search behaviour as a default.

Cheers
Thomas
