### ISSUE TITLE
0.64 not available on snap?

### ISSUE THREAD

**Issue by muhv7** [RocketChat/Rocket.Chat#10656]
Update has been out for 5 days now and no updates pushed to snap yet?

root@ns54xxxx:~# sudo snap refresh rocketchat-server
snap "rocketchat-server" has no updates available

Ubuntu Server

Rocketchat version 0.63.3

Thank you!

**Comment by macke800** [comment]
Looks like it is there on the candidate level:
sudo snap install rocketchat-server --candidate
... check "Show all versions" on the: https://snapcraft.io/rocketchat-server page.
Not sure when/how/who moves the candidate to become the stable version.

**Comment by iMaciaveller** [comment]
#install beta update
$sudo snap refresh rocketchat-server --beta
#back to stable update
$sudo snap refresh rocketchat-server --ignore-validation

**Comment by muhv7** [comment]
So there's two ways? Either way on 63.3 until someone decides to put 64 up to stable or go beta?

**Comment by Windoze345** [comment]
What is the process for moving a release from candidate to stable.
Candidate is already at 0.64.1. So I guess uploading to candidate is automatic?!? But moving to stable is manual.

**Comment by pettitto** [comment]
Yeah updating to the Beta isn't really a great workaround, it should be stable by now. When are we likely to see the 64.x become stable for snaps?

**Comment by muhv7** [comment]
Any updates on this? Or is snap now just looked over?

**Comment by graywolf336** [comment]
@muhv7 The updates to the Snap packages were delayed due to a bug with the authentication layers with WordPress. It was dependant upon #10724 getting merged. A little while after a release happens with that fix applied, then the Snaps will be updated. The release updates are delayed to the Snap packages is because of the auto-updating feature and when we find bugs, such as the major breaking one this time, then we do not update the Snaps package as a goodwill gesture to the people utilizing the Snap deployment option. Does that make sense?

**Comment by muhv7** [comment]
Sure does. Just didn't know about this earlier. Thank you for clarifying that.

**Comment by graywolf336** [comment]
No problem :) that information is scattered throughout the issues here. Hopefully a release will be forthcoming in the next few days.

**Comment by geekgonecrazy** [comment]
Should now be available.  Sorry about the delay.

As said by @graywolf336 we had a few issues we couldn't rightly release and risk breaking someone's install.  

Specifically anyone with wordpress authentication would not have been able to login any more. 

Its now released.  Closing this issue

**Comment by starhound** [comment]
Having this issue on 3.5.0

**Comment by geekgonecrazy** [comment]
3.5 barely has been out.  The answer is still the same.  Snaps are manually tested and are delayed since they auto update. So important that we are even more certain that it won't break everyone's installs

**Comment by starhound** [comment]
Sorry, just concerning as we we're displayed the update banner to all our users. We managed to disable it however, will there be some form of notification when snap updates are available?

**Comment by saschaludwig** [comment]
Why is the update banner shown in a snap installation, when there is no updated snap available?
