### ISSUE TITLE
How to send push notification to web application using rocket.chat rest api?

### ISSUE THREAD

**Issue by gd-narola** [RocketChat/Rocket.Chat#10651]
I need to integrate rocket chat in asp.net application and trying to understand how we can send push notification in chat after send/post message?

Do I need to use subscribe methods?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @gd-narola

Please refer to the forums to ask this question, as there seems to be no bug involved: https://forums.rocket.chat/c/community-support

Cheers
Thomas
