### ISSUE TITLE
Keyboard Shortcuts - Pass through

### ISSUE THREAD

**Issue by JuliannaR** [RocketChat/Rocket.Chat#10658]
Current set of keyboard shortcuts introduce an array of issues. Crtl + P is a windows command for print. 

While the function works it also opens the print window. All keyboard shortcuts should not mimic windows keyboard commands. Because it opens the print window is also disorients the user and takes them away from the chat window by focusing on the windows print menu. 

Please consider this across all keyboard commands.

**Comment by mgifford** [comment]
Keyboard shortcuts are a real problem. So often they make sense only in English and for some users.  They aren't really discoverable most of the time. Not sure that anyone does reviews to see how often they are used. 

I'd really like to see that these are user-definable. Sure, put up some defaults that make sense, but then allow folks to customize them.  There are so many lots of debate about this here https://webaim.org/techniques/keyboard/accesskey

**Comment by geekgonecrazy** [comment]
#6374 I think this issue will resolve this
