### ISSUE TITLE
The answer context menu

### ISSUE THREAD

**Issue by iMaciaveller** [RocketChat/Rocket.Chat#10668]
The answer context menu in a private group appears in the upper right corner.

* Version of Rocket.Chat Server: 0.64.0 (SNAP) OS Ubuntu 16.04
* Client: FireFox 59.0.2 (64-бит) OS MS Windows 7

<img src="https://pp.userapi.com/c824204/v824204247/1262d7/rQLY4XUtr88.jpg">

**Comment by kvaps** [comment]
Agree same problem on
```
Browser: Mozilla Firefox 60.0
System: Archlinux
```

**Comment by vynmera** [comment]
Oh yeah, I noticed when fiddling around with this that resizing the browser/client pops it back in place most of the time, so does calling its position handler manually
I didn't manage to find a fix, but maybe it helps?

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/42405685-35678dd4-8168-11e8-914d-ad7dc27a6f57.png)
still happening

**Comment by jwallet** [comment]
![image](https://user-images.githubusercontent.com/23088305/42405685-35678dd4-8168-11e8-914d-ad7dc27a6f57.png)
still happening
