### ISSUE TITLE
[BUG] Can't send mail notification

### ISSUE THREAD

**Issue by diginote** [RocketChat/Rocket.Chat#10672]
### Description: 
An error occures when rocketchat wants to notify someone by email about a missed message.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Ubuntu 18.04 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: deactivated
* Node Version: 8.9.3 - x64
* mongoDB Version: v3.6.4

### Steps to Reproduce:

1. Login and enter a private user communication
2. go to navigation settings of that communication and subscribe all notifications (both users do that)
3. send message to that user (that is offline)

### Expected behavior:

the user should receive a mail notification

### Actual behavior:

the user does not receive any mail notification although the settings in the administration area are set and the test mail from the administration area is send properly.

### Relevant logs:
```
Exception in defer callback: Error: Mail command failed: 501 5.1.8 Error bad address (missing local part)
rocketchat_app_1  |     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
rocketchat_app_1  |     at SMTPConnection._actionMAIL (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1280:34)
rocketchat_app_1  |     at SMTPConnection._responseActions.push.str (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:797:18)
rocketchat_app_1  |     at SMTPConnection._processResponse (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)
rocketchat_app_1  |     at SMTPConnection._onData (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)
rocketchat_app_1  |     at TLSSocket._socket.on.chunk (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)
rocketchat_app_1  |     at emitOne (events.js:116:13)
rocketchat_app_1  |     at TLSSocket.emit (events.js:211:7)
rocketchat_app_1  |     at addChunk (_stream_readable.js:263:12)
rocketchat_app_1  |     at readableAddChunk (_stream_readable.js:250:11)
rocketchat_app_1  |     at TLSSocket.Readable.push (_stream_readable.js:208:10)
rocketchat_app_1  |     at TLSWrap.onread (net.js:594:20)
```

**Comment by Hudell** [comment]
It seems that Rocket.Chat is not recognizing the user's email address as valid. Does he have a valid email address assigned to him?

**Comment by diginote** [comment]
The user has a varified and valid email (it containes an underscore --> cccccc_ccccccc@ccc.cc). I've invited the user with his email ("Send welcome email") an he can login properly.
