### ISSUE TITLE
After Uploading a File, Unable to Paste

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#1067]
After uploading an image, I am unable to paste inside a channel:
![2015-10-12_11-13-49](https://cloud.githubusercontent.com/assets/850391/10432674/58eb7940-70d2-11e5-98e3-1d661c6c5649.gif)

**Comment by geekgonecrazy** [comment]
Yeah i've seen this a lot.  I thought we had already posted it.  :grin: Thanks for posting it :+1:

**Comment by MuhClaren** [comment]
Confirmed for Opera 31.0.1889.174 (Linux).

Restarting the browser seems to resolve the issue for me.

**Comment by graywolf336** [comment]
Drag and drop works fine, you can paste after dragging and dropping. And it only affects the channel you uploaded the file to, you can switch to another channel and paste just fine.
