### ISSUE TITLE
Empty error mensage when inviting a user to private channel

### ISSUE THREAD

**Issue by mikaelmello** [RocketChat/Rocket.Chat#10676]
### Description:

When adding a new user to a private channel (that I do not own), I get an error pop-up, probably because I don't have the permission to invite new users to the channel, however I should get something more than a red box.

Since my site was in Portuguese, I though this could be a translation bug, however this also happens in English.

### Server Setup Information:

* Version of Rocket.Chat Server: open.rocket.chat on May 4th

### Steps to Reproduce:

1. Be in a private channel that you do not own
2. Try to invite someone

### Expected behavior:

Error pop-up with a helpful message

### Actual behavior:

No message at all

### Relevant logs:

https://imgur.com/a/SbLNDkw

**Comment by ggazzo** [comment]
@mikaelmello it was fixed could you test it again? thanks
