### ISSUE TITLE
User list of a private room

### ISSUE THREAD

**Issue by samimaktar** [RocketChat/Rocket.Chat#10670]
I want to get the member list of a private room ...so i am following this document https://rocket.chat/docs/developer-guides/rest-api/groups/info/ ...... it successfully returns the group information but shows an warning .....and the userlists are not returned ...... the warning is [WARNING]: The "usernames" field has been removed for performance reasons. Please use the "*.members" endpoint to get a list of members/users in a room. .... so how i will get the list of the member/users for a particular room ..dont understand the meaning of *.members

**Comment by mjovanovic0** [comment]
It means that you use the following endpoint: `/api/v1/groups.members` with `roomId` or `roomName` query parameter

**Comment by samimaktar** [comment]
Ah...Thank you.... works like a charm  :+1:
