### ISSUE TITLE
Permissions not working correctly

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#10685]
I have noticed a lot of irregularities with the permissions, I haven't had time to investigate it yet but some of the issues I've encountered thus far are: 

- Permissions are not having any effect on anonymous users. For example, an anonymous user can view and preview any public channel even when I've disabled this for all user roles. 
One possible reason for this could be that the "Allow Anonymous Read" setting is overwriting this?

- The "preview public channel" permission does not work for any user, i.e. all users can preview all rooms regardless of how I set this permission.

Version: 0.64.1

**Comment by theorenck** [comment]
Hi @cchbr thanks for the feedback, could you please give us more context on the scenarios above?

**Comment by cchbr** [comment]
This major issue is that the permission [preview-c-room] has no effect whatsoever. I have disabled it for all users except for admin and everyone can still preview channels without being logged in or joining the channel.

I have allowed anonymous reading and would like the user to either log in (or choose a username anonymously) and join the room before seeing all the messages in that room. 

Another issue I have noticed is that guests cannot see any channels in "/directory", I haven't found any permission setting to enable this yet. But when a guest presses the search icon, all channels are shown and can be accessed.

**Comment by GammaPi** [comment]
I can confirm this, anonymous user will bypass permission settings on public channel.

**Comment by GammaPi** [comment]
It's not an improvement but a bug~
@theorenck

**Comment by GammaPi** [comment]
Another bug related: If there is no any public room, registered user cannot sign-in because there is no sign in button!

**Comment by engelgabriel** [comment]
@pierre-lehnen-rc can you please take a look at this?

**Comment by pierre-lehnen-rc** [comment]
I'll work on this.

**Comment by phlbrz** [comment]
Hi,

Is it related with https://github.com/RocketChat/Rocket.Chat/issues/18398#issuecomment-702415119 ?
Avatars, even my user has admin role, is not working, shows me an error 403.
I didn't opened an issue because I think someone already has opened it.
If not, I could fill a new one.

**Comment by damian-centrone** [comment]
this issue is now working as expected.
