### ISSUE TITLE
Improving notifications

### ISSUE THREAD

**Issue by teetrinkers** [RocketChat/Rocket.Chat#1068]
Hi folks! We (me and some coworkers) found notifications for new messages to be inconsistent and would like to improve them.

This is the current behaviour of Rocket Chat:

| Event | Desktop notification | Icon badge | Sound |
---------|--------|-----------|-----
direct message, window has focus, channel is selected     | no | no | yes
direct message, window has focus, channel is not selected | no | yes | yes
direct message, window does not have focus, channel is selected | yes | no | yes
direct message, window does not have focus, channel is not selected | yes | yes | yes
group message, not mentioned, window has focus, channel is selected | no | no | no
group message, not mentioned, window has focus, channel is not selected | no | yes | no
group message, not mentioned, window does not have focus, channel is selected | no | no | no |
group message, not mentioned, window does not have focus, channel is not selected | no | yes | no |
group message, user mentioned, window has focus, channel is selected | no | no | yes
group message, user mentioned, window has focus, channel is not selected | no | yes | yes
group message, user mentioned, window does not have focus, channel is selected | yes | no | yes |
group message, user mentioned, window does not have focus, channel is not selected | yes | yes | yes |

We propose this behaviour, which mostly adheres to Slack's behaviour with "Notifications only for highlight words an direct messages":

| Event | Desktop notification | Icon badge | Sound |
---------|--------|-----------|-----
direct message, window has focus, channel is selected     | no | no | no
direct message, window does not have focus or the channel is not selected | yes | yes | yes
group message, user is not mentioned, window has focus, channel is selected  | no | no | no
group message, user is not mentioned, window does not have focus or the channel is not selected | no | yes | no
group message, user mentioned, window has focus, channel is selected | no | no | no
group message, user mentioned, window does not have focus or the channel is not selected | yes | yes | yes

After this change, we can then think about the preferences option "Notification for activity of any kind", options per channel, and highlight words.

What do you think, will such a change be acceptable?

**Comment by Theaxiom** [comment]
+1

This is a more verbose explanation of my issue #866

**Comment by geekgonecrazy** [comment]
@Theaxiom would you prefer to move conversation here with the more verbose explanation?

**Comment by Theaxiom** [comment]
@geekgonecrazy Yes please, can you merge them?

**Comment by mhkeller** [comment]
This looks great so far. I would also add "dock bounce" as a notification type for the desktop version since that's the main way my team has been using it. I believe currently the dock icon will bounce if a message does into a channel and the window does not have focus. 

For "group message, user is not mentioned" Slack adds a red circle to the icon, which the current desktop app also does and seems sensible to me. Adium adds the user name to the dock icon, which could be nice for DM's or mentions but not sure if that's possible

Integrating with email for offline messages per https://github.com/RocketChat/Rocket.Chat/issues/741 would also be helpful.

Per https://github.com/RocketChat/Rocket.Chat/issues/866, the request I'm getting is for certain channels to always make a sound, for example. Having sensible defaults but also per channel settings would be helpful.

**Comment by geekgonecrazy** [comment]
@mhkeller Just a quick note.  I'm not sure if we can actually control the bounce its self.  That's more of we add the badge, then OSX does the bounce because of a notification.

**Comment by mhkeller** [comment]
I see, so is the Rocket Chat notification not connected directly to the [Electron dock commands](https://github.com/atom/electron/blob/master/docs/api/app.md#appdockbouncetype-os-x) when running in that environment? If there's a code section to point to I can look at how it works to learn more.

**Comment by teetrinkers** [comment]
The only Electron dock command I've found is in the main.js of the Electron app:
```
if (process.platform === 'darwin') {
    app.dock.setBadge(String(unread || ''));
}
```

**Comment by geekgonecrazy** [comment]
That would be it.  :+1:

**Comment by steedos** [comment]
+1

**Comment by steedos** [comment]
Currently, there is no on video call, If i'm not in the chat window.

**Comment by Dbzman** [comment]
For my team the current notification behaviour is a blocker preventing us from switching to RocketChat.
The most important thing is that we need to get desktop notifications for a specific channel even if it is selected but in the background. No criticism here, just a side note. :)

We're really looking forward to a more consistent notification behaviour.

**Comment by mhkeller** [comment]
That behavior is highly requested for my team as well.

**Comment by mhkeller** [comment]
Is the idea that these could be configured on a per-channel basis still being considered?

**Comment by teetrinkers** [comment]
For now, my intention is to do notifications the same way as Slack does, including channel options. Right now, I'm waiting on feedback for my first pull request (see above) to see if the Rocket-Chat team thinks that this is the right direction. Also I cannot work on this full-time, so this might take a few weeks, unless other devs contribute.

**Comment by mdix** [comment]
I think there should be at least a quickfix for that one. It could not be worse than not being notified while on the most important channel.

| Event        | Desktop notification           | Icon badge  |
| ------------- |:-------------:| -----:|
| direct message, window has focus, channel is selected      | no | no |

**Comment by teetrinkers** [comment]
My Pull-Request fixes that.

**Comment by mdix** [comment]
Yay, so all we can do is wait I guess...

**Comment by teetrinkers** [comment]
#1116 is merged!

**Comment by Dbzman** [comment]
@teetrinkers 
So amazing, thank you very much! We will test this on monday. :+1:

**Comment by engelgabriel** [comment]
It is merge indeed! :+1: Thanks for the help! 

I believe I should close this issue now :)

**Comment by Theaxiom** [comment]
You guys are rock stars!
