### ISSUE TITLE
[Feature] Extra Hide Button

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#10687]
### Description:

I am having a lot of channels that I do not want to see on the left hand menu all the time. Things like "monitoring", "alerts", "jokes" etc are great, but due to the fact that they re-pop open should be closed 95% of the time (hidden).

Slack has a single-click button (x) for that. Such a small button next to the three dots that will hide the channel without confirmation would totally chill my workflow.

### Server Setup Information:

(does not apply, new feature not present in any version).

### Steps to Reproduce:

1. Join multilpe channels,
2. Try to single-click hide then channels withouth confirmations

### Expected behavior:

1. Join multiple channels,
2. Click an icon next to the channel name to hide said channel.

### Actual behavior:

(this is getting repetetive) :)

### Relevant logs:

none.

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by marceloschmidt** [comment]
We implemented a "Don't ask me again" on the confirmation, so that will reduce the amount of clicks to hide from 3 to 2. We can think on a new UI in the future, but that's not planned right now.
