### ISSUE TITLE
能不能在发送message的时候指定message type?

### ISSUE THREAD

**Issue by 1th** [RocketChat/Rocket.Chat#10689]
![image](https://user-images.githubusercontent.com/6316996/39692248-ec6041d2-5212-11e8-96ca-2b5c7d57a899.png)
能不能在这里使用自定义的消息类型？

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

While we do welcome diversity across the community as well as in the team I'm afraid that for purely practical reasons we have to stick to english in public communication.

If you decide to translate your initial issue, please get back to me. Please also adhere to the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md).

Cheers
Thomas
