### ISSUE TITLE
Chat text input is laggy on high-dpi screens or when zoomed out

### ISSUE THREAD

**Issue by glebtv** [RocketChat/Rocket.Chat#10690]
### Description:

Chat text input is laggy on high-dpi screens or when zoomed out.

This is reproducible in current chrome and electron app.

After pressing a key in text input there is a ~ 500ms delay before any input is displayed in textarea.

This was not present in previous versions.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.64.0, 0.63.3, also on https://open.rocket.chat

### Steps to Reproduce:

1. Use a high-dpi screen or scale out in a browser
2. Type something in textarea in any chat

### Expected behavior:

Input doesn't lag

### Actual behavior:

Input lags

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I would like to merge this issue with #10583 (meaning to close the one at hand) because I have a hunch there might be the same underlying issue involved.

Cheers
Thomas
