### ISSUE TITLE
Release scripts?

### ISSUE THREAD

**Issue by Bogidon** [RocketChat/Rocket.Chat#10698]
Hi Rocket.Chat team,

First, thank you sooo much for the work you've been doing. This project is ridiculously awesome and I am very much looking forward to using it / contributing to it / seeing others benefit from it.

**Summary/TL;DR:** I'd like to run a deploy my organization's fork to production and am having a bit of a tough time creating a build script. Could y'all share yours? Below is some justification concerning the FOSS idea of pushing all changes back to the source repo.

---

One of my interests is institutional memory (the organization and archival of information in an institution). As you know, lots of information is encoded in communication, and so communication is an important topic that I've chosen to do some research into. I've been studying different ways people communicate. I've realized that although instant messaging is likely a net positive, there are some beneficial elements of longer-form communication that have been lost (e.g. the reduced pressure to be always available with email). I'm also sure there are many great ways of structuring communication that haven't yet been designed. 

Realizing what forms of communication are most efficient takes a lot of critical design work and experimentation. I believe that it's critical to actively experiment with different methods of communication at different institutions. Living in the age of electronic communication, with software like Rocket.Chat, experimentation would mean making changes to the source of organization's running instance to test out changes that can later be applied to the main source if proven effective.

This idea was very briefly touched on in #2587, with @Sing-Li writing:
> ...this is a classic problem with tracking FOSS. So the best approach is always to push your customizations upstream - like donating them back to FOSS as much as possible 😃 Many community members are doing exactly that.

later @kajisaap remarked that they would like the production build scripts to be shared:
> ...can you guys share the build script used currently to generated compiled in releases that are downloadable from https://rocket.chat/releases

(other pertinent issues: #1741 #1886 #3609 #6821 #7626)

As a 100% supporter of FOSS, I am in total agreement of contributing changes back upstream. However, I think that if all changes must reach the source repo before making it into production servers, this limits feature changes to one of the following (but I don't have that much knowledge of how Rocket.Chat operates, so maybe I'm wrong):
- the changes are approved by whoever reviews PRs. In effect, the reviewers are also doing a design review of whether the changes are "good" for communication. If the changes turn out to be "bad" we'll likely only find out a long time later based on feedback sourced from all deployments of Rocket.Chat.
- feature flags. These already exist in Rocket.Chat, and I believe giving power to server admins to configure their instances without needing to jump into the codebase is indispensable. However, as more experiments are run there will be more and more feature flags. Maybe it would be possible to scale this through some sort of upgraded administration control (maybe there's already been discussion). But I feel like this model raises the activation energy of running experiments too much. Experiments would need to be PR'd to the source repo and then the institution would have to wait for a release.

So, honing in because this is getting a bit long, I would like to run a fork of Rocket.Chat at my college. I have a group of students who are also interested in experimenting with refinements to communication. We'd contribute successful changes back upstream. We would not compete with Rocket.Chat outside of our institution (our priority is the same as yours, to improve communication for _all_).

I've been trying to build Rocket.Chat for production deployment. I think my build script, which I've cobbled from various scripts in the documentation and repo, is almost there, but I'd love to base them off of the scripts used for https://releases.rocket.chat. Any advice? I'd be happy to help test things out in different environments.

**Comment by Bogidon** [comment]
Update: I managed to create a functional build script from scrapping together various existing scripts: https://github.com/olin/Rocket.Chat/blob/olin-develop/olin/setup.sh. I'm sure there's some stuff in there that isn't quite right/needed (I'm not quite sure how the replication set stuff works).

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  All of our ci scripts are always public so how we build is always public
