### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#10699]
I'm running Rocket Chat on an AWS instance with docker compose, and after every reboot  I get a 502 Bad Gateway error in the browser. Previously I solved it by stopping and removing the docker containers, this time this doesn't seem to work as the are just restarted instantly with docker compose and the problem persists.

I have tried using the latest version, 0.63.0 and 0.62.0.

Has anyone experienced something similar or know what may cause this bug?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hey folks,

I'm closing this, as there is no bug involved. Please use the [forums](https://forums.rocket.chat/c/community-support) for that :) If it turns out that there is an actual bug, please get back to me!

Cheers
Thomas
