### ISSUE TITLE
[Feature Request] Add feature to set the message as delivered.

### ISSUE THREAD

**Issue by mohanadrefaai** [RocketChat/Rocket.Chat#10708]
Using read receipt is very useful to check whether the message is seen or not. But it does not include the "delivered" status which means that, a user received a message and maybe he did not see it.
And this status is also different from the "sent" status which means that, the message has been sent successfully to the server.

Depending on #9717 issue I see that there is no feature yet to detect the "delivered" status.

**Comment by geekgonecrazy** [comment]
I don't think this is something we can implement. Technically for us it's delivered the very instant you send it.

If we had a single device as device we could use it. Otherwise we would have confirmation from 1-infinite number of devices.

**Comment by mohanadrefaai** [comment]
@geekgonecrazy I think the logic of this problem like the read receipt logic. I mean Why we do not implement REST API to mark the message (or even the whole subscription) as delivered like when we mark it as read using "subscription.read" API. Then I think the problem is related to an account not to a device whether this account received the message or not (not important to which device the message delivered).

**Comment by geekgonecrazy** [comment]
@mohanadrefaai On most devices though when its delivered its basically read.

Mobile for instance.  When you see you have unreads in a DM.  You open the DM.  Those are delivered and a few seconds later they are read.

Same for desktop.

@RocketChat/core thoughts?

**Comment by marceloschmidt** [comment]
Unfortunately after discussing this with the team, we realized this is not technically possible.
