### ISSUE TITLE
Auth's Question

### ISSUE THREAD

**Issue by tfraley** [RocketChat/Rocket.Chat#1070]
Good day guys

New to RocketChat.. Still in the stand alone setup process. 

I'm up and running, hover I can't seem to get auth's working correctly
Example Facebook & Twitter 

Error when trying to login,
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

It seems at the very top it's showing localhost rather then the domain, could this be the issue?

<img width="812" alt="screenshot 2015-10-12 10 40 37" src="https://cloud.githubusercontent.com/assets/1166064/10434336/bf9038e8-70cd-11e5-8f9c-7a1f7c3f4016.png">

**Comment by ninja-** [comment]
Yes

**Comment by tfraley** [comment]
This may be very basic but could someone point out how to chnage this? 
My /etc/hosts 
127.0.0.1       localhost
127.0.1.1       rocketchat

rocketchat.domain.net:3000 loads fine and everything seems to work but the 3rd party auths

I've used other services and products most of which include a callback / redirect url setting, maybe adding this in the future would be a plus.

**Comment by geekgonecrazy** [comment]
Do you have ROOT_URL set?

Also with oauth usually the application facebook etc you put a url there on the platform for the callback.  If the url of your instance is different then the url that is provided to the oauth provider it will throw an error like this.

**Comment by tfraley** [comment]
@geekgonecrazy thanks for getting back to me on this. 

I don't believe I set a ROOT_URL, where does one set this?

As for the oath applications, I use them on many other services, I have an understanding on how they work and I believe I have it setup correctly.

**Comment by geekgonecrazy** [comment]
I recently helped someone in the demo through something similar.  By default ROOT_URL is set to localhost.  So it uses that in the south request and causes mismatch.


You set via environment variable.  So if using meteor:
```
export ROOT_URL=http://host
meteor
```

Docker use `-e ROOT_URL=http://host`

**Comment by gmsecrieru** [comment]
@tfraley can you confirm that this is solved by setting ROOT_URL?

**Comment by tfraley** [comment]
@gmsecrieru @geekgonecrazy 
I tried this a few times and variations with reboots between testing with no luck.

**Comment by geekgonecrazy** [comment]
@tfraley what is your actual deploy method?  That'll help a lot in making sure we point you in the right direction

**Comment by tfraley** [comment]
Fresh Ubuntu 14 server with updates on a XenServer VM

sudo apt-get install git 

sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get update && sudo apt-get install -y nodejs
sudo apt-get install mongodb

curl https://install.meteor.com/ | sh

git clone https://github.com/RocketChat/Rocket.Chat.git
 
cd Rocket.Chat
sudo meteor


Also installed screen and run it their

**Comment by gmsecrieru** [comment]
Have you tried following [these instructions](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker)?

**Comment by geekgonecrazy** [comment]
@tfraley so in that particular install method you would replace `sudo meteor` with `sudo ROOT_URL=http://mydomain meteor`

But actually sudo should be completely un-needed since by default meteor runs on a non privileged port.  Port 3000.

I'd personally do:
```
chown -R youruser:youruser Rocket.Chat
chmod -R 755 Rocket.Chat
```
Changing the ownership back to you instead of the files created by meteor when ran as root.

Then do:

```
ROOT_URL=http://mydomain meteor
```

**Comment by tfraley** [comment]
@geekgonecrazy

sudo ROOT_URL=http://mydomain meteor was one of the varitations I tried with no luck

I will try the other suggestion ie changing back to youruser.

**Comment by tfraley** [comment]
@gmsecrieru I did run though that set of instructions once and ran into a glitch and found thouse directions which got me up and running faster but guess not with out a hitch ;)

**Comment by gmsecrieru** [comment]
@tfraley this might be a basic question that we might have forgot, but are you running an up-to-date version?

**Comment by marceloschmidt** [comment]
So, was this fixed?

**Comment by engelgabriel** [comment]
The Site URL on the Admin panel must match the host configured on the facebook app.
