### ISSUE TITLE
Announcement text no longer appears in modal

### ISSUE THREAD

**Issue by markwooff** [RocketChat/Rocket.Chat#10703]
### Description:

When clicking on a channel's announcement, the modal that used to display the full text no longer displays anything.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker-compose
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.3
* mongoDB Version: 3.2.19

### Steps to Reproduce:

1. Have a channel with an announcement set
2. Click on announcement bar at the top of a channel
3. Modal appears without any of the announcement text

### Expected behavior:

Announcement text should be displayed.

### Actual behavior:

Announcement text is not displayed.

**Comment by tsukiRep** [comment]
Doesn't #10733 fix this? It seems to be working on 0.64.2 for me.

**Comment by ggazzo** [comment]
@markwooff could you check again?

**Comment by markwooff** [comment]
This issue looks to have been fixed, thanks! Closing issue.
