### ISSUE TITLE
Unable to "Save changes" to uploaded avatar in Internet Explorer

### ISSUE THREAD

**Issue by markwooff** [RocketChat/Rocket.Chat#10701]
### Description:

When using Internet Explorer, I am unable to click the "Save changes" button from the Profile page when trying to upload a new avatar. Same issue when using a URL for a new avatar.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker-compose
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.3
* mongoDB Version: 3.2.19

### Steps to Reproduce:

1. Navigate to "My Account" -> "Profile" page
2. Click "Upload avatar" **or** enter URL for "Use URL for avatar"
3. Click "Save changes"

### Expected behavior:

Have "Avatar changed successfully" message appear.

### Actual behavior:

No message appears and although I can see the image in the preview area, the image does not save as the avatar.

### Relevant logs:
None

**Comment by blaisep** [comment]
hi @theorenck I opened:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/717
because I can't even get to the Profile page!
