### ISSUE TITLE
uploading file progress stuck and cancel button not work any more

### ISSUE THREAD

**Issue by alirezaimi** [RocketChat/Rocket.Chat#10709]
### Description:

File Upload have some serous problems and stuck in uploading and cancel button not work anymore !
This is some lines for one file with 12MB size :

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: debian 4.9.0-6-amd64
* Deployment Method(snap/docker/tar/etc):  snap
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: v4.8.2
* mongoDB Version: 3.2.11-2+deb9u1

### Steps to Reproduce:

1. upload a file with button or drag & drop in a direct chat or some where else

### Expected behavior:

upload file completion !

### Actual behavior:

one time upload is complete and another time stuck some where in uploading .

### Relevant logs:
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]:    { name: 'a.rar',
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]:      size: 10904804,
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]:      type: 'application/x-rar-compressed',
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]:      rid: 'gA34WeKZTqA9GbL4G',
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]:      description: '',
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]:      store: 'Uploads' } }
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.0015024570822180757
    May 09 11:24:09 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:11 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.0030049141644361513
    May 09 11:24:11 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:14 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.004507371246654227
    May 09 11:24:14 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:16 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.006009828328872303
    May 09 11:24:16 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:18 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.007512285411090378
    May 09 11:24:18 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:20 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.009014742493308454
    May 09 11:24:20 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:22 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/PBAeR9khNYYPYhMtx?token=98Ba19293a&progress=0.010517199575526529
    May 09 11:24:22 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 UploadProxy ➔ debug Correct instance
    May 09 11:24:22 sp2lnx1chat rocketchat-server.rocketchat-server[663]: rocketchat_logger rocketchat_logger.js:278 Meteor ➔ method ufsDelete -> userId: XLJPpMqC35jJDWTxR , arguments:  { '0': 'PBAeR9khNYYPYhMtx', '1': 'Uploads', '2': '98Ba19293a' }
    May 09 11:24:22 sp2lnx1chat rocketchat-server.rocketchat-server[663]: Error: FileNotFound: no file with id PBAeR9khNYYPYhMtx found

**Comment by TwizzyDizzy** [comment]
Hi @alirezaimi 

could you please adjust the title of this issue to the one I just linked to? He's got the better headline, but you got the logs ;)

Cheers
Thomas

**Comment by alirezaimi** [comment]
Hi @TwizzyDizzy 
one of problem is that cancel button not work when uploading process stuck, the Big and main problem is that uploading process stuck sometimes.

**Comment by TwizzyDizzy** [comment]
Thanks! I haven't been able to find it just now but there is  at least one issue that concerns itself with the file upload utself not working. IIRC it was when running multiple instances.

Cheers
Thomas

**Comment by alirezaimi** [comment]
@TwizzyDizzy 
I installed rocket chat with snap and by default it installed on 1 instance, is that all about ? multi instance is solution ?

**Comment by blmt** [comment]
Hi all. I am experiencing the same issue. Our system is installed via snap and it was working before it automatically upgraded. (not sure which one is the last known-good version)

As a consequence of the file upload not working the browser reports.
XML Parsing Error: no root element found
Location: https://mychatsite/ufs/GridFS:Uploads/6c8YsSsbviHzewWAp?token=F8fadBFAca&progress=0.1616943164210921
Line Number 1, Column 1:

**Comment by Mr-Gryphon** [comment]
Hello i have submit a PR, #10715  . please check and review :)

**Comment by alirezaimi** [comment]
any news ?

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/10715

**Comment by alirezaimi** [comment]
Thank you for support,
In this bug report i announce two different problem with one specific section of rocketchat, file uploading .
1- cancel problem that stuck and not work
2- file uploading problem that some files uploaded successfully and some files not ! this part of log related to it :
    `May 09 11:24:22 sp2lnx1chat rocketchat-server.rocketchat-server[663]: Error: FileNotFound: no file with id PBAeR9khNYYPYhMtx found`

Which part are fixed in this release(0.65.0) ?

**Comment by ZsZs73** [comment]
@alirezaimi Are you sure that your Site URL is correct?
Administration / General / Sire URL should be the same as the ROOT_URL environment variable of the main.js process.
I had the same issue after changing the hostname, ROOT_URL, but forgot to change the Site URL accordingly.
After changing the Site URL to the value of ROOT_URL the upload works again.
HTH,
Zsolt

**Comment by alirezaimi** [comment]
@ZsZs73 
Upload works for me too , but some times not ! because of error that i sent it.

**Comment by stefersonferreira** [comment]
This was the question!! ROOT_URL

Thanks.
