### ISSUE TITLE
Mirror channels between rocket.chat instances

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/Rocket.Chat#1071]
I'd like the ability to mirror select channels on my rocket.chat instance with other instances of Rocket.Chat -- to bridge the conversation between Rocket.Chat instances.

**Comment by ninja-** [comment]
? Why would you want to do that

**Comment by alisalaah** [comment]
You can sync Mongo Collections between two servers if you have rights to
both. Hubot may also be valuable in echoing the conversations though it may
not be the ideal solution of actually linking to servers by federating with
each other and then allowing an official bridge.

**Comment by Theaxiom** [comment]
I was actually thinking hubot may be a better solution.

**Comment by Theaxiom** [comment]
This could be closed because it is able to accomplish with hubot.
