### ISSUE TITLE
Jitsi on Mac

### ISSUE THREAD

**Issue by aviv-ko** [RocketChat/Rocket.Chat#10718]
We tried connecting to someone using a Mac. The Jitsi plugin would not work/download properly. Any thoughts anyone?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Dude*ness! Please!

* Search the issues before opening a new issue
* Follow the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md)
* and generally don't open the same issue multiple times.

Cheers & Thanks
Thomas
