### ISSUE TITLE
[FEATURE] Create slash command /hide to "close" direct messages

### ISSUE THREAD

**Issue by FONFAAS** [RocketChat/Rocket.Chat#10713]
### Description:

The slash commands `/leave` and `/part` only work on channels
The idea is to add `/hide` command to do the same as we do with the UI:

<img width="185" alt="hide" src="https://user-images.githubusercontent.com/3885397/39810546-458550ac-537d-11e8-9b11-b6516bb29220.png">

**Comment by mikaelmello** [comment]
Perhaps I should have discussed the feature here first, mainly if it is desirable by the RC team. Sorry I didn't think of that, however it was something simple and with a current behavior to follow.

**Comment by FONFAAS** [comment]
@mikaelmello no problem !
