### ISSUE TITLE
WebRTC on Android devices

### ISSUE THREAD

**Issue by aviv-ko** [RocketChat/Rocket.Chat#10717]
For some reason WebRTC is not working on Android devices (both smartphones and tablets). 
Android ver. 8.0.0
Kernel ver. 4.4.78-13052619

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Dude*ness! Please!

* Search the issues before opening a new issue
* Follow the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md)
* and generally don't open the same issue multiple times.

Cheers & Thanks
Thomas
