### ISSUE TITLE
Search bar aligns wrong

### ISSUE THREAD

**Issue by LesterChester** [RocketChat/Rocket.Chat#10712]
### Description:

The searchbar ends up awfully wrong when trying to search in my contacts.
![skarmavbild 2018-05-09 kl 11 06 00](https://user-images.githubusercontent.com/39119210/39806046-109a78ee-5379-11e8-9682-1fd8a6ce63ce.png)

### Server Setup Information:

* Version of Rocket.Chat Server:  2.10.5
* Operating System: OSX 10.13.4
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
Click the magnification glass
2. 
Be unable to search properly.
3.

**Comment by ggazzo** [comment]
@LesterChester I think you changed the background color, am I wrong?

**Comment by LesterChester** [comment]
@ggazzo I haven't touched it. Maybe my organization has, though. It isn't dark blue by default?

**Comment by ggazzo** [comment]
I did it changing the value `Primary Darkest` to none

Administration > Layout > Colors > Primary Darkest

![image](https://user-images.githubusercontent.com/5263975/40671585-aab24dac-6342-11e8-813b-ea894a5f6fd4.png)


![image](https://user-images.githubusercontent.com/5263975/40671534-85509bd6-6342-11e8-9554-f2d881a9feff.png)

try change the value, let me know if works

**Comment by vynmera** [comment]
Isn't this somewhat working as expected? Since `Primary Darkest` controls the background color of the search box, setting it to none (or any other transparent) will allow you to see through it to the controls behind.
For example, you can set it to `#00000080` and it will be a see-through black.

I suppose it would be a little bit nicer if the controls behind it would hide if the search box is open, but for now you'll want to set `Primary Darkest` to a non-transparent value.

**Comment by LesterChester** [comment]
I'm sorry. Not a developer. Where do I access the "Administration"? Tried Devtools. Didn't succeed.
@ggazzo

**Comment by vynmera** [comment]
Triple dots in top left (where the search bar is) → Administration
If you don't have this option, ask a server admin to do it for you.

**Comment by ggazzo** [comment]
@LesterChester I will be closing this issue because actually its working (the  behavior is expected if you remove the background-color), as @vynmera we can improve how we render the sidenav but its the scope of this issue...
thanks for contribute all of you (:
