### ISSUE TITLE
[BUG] Cancel button not working while uploading any file 

### ISSUE THREAD

**Issue by Mr-Gryphon** [RocketChat/Rocket.Chat#10710]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Linux

### Steps to Reproduce:

1.Open Chat room. 
2. Upload a file. 
3. While uploading on progress bar, their is a cancel button, is not working. Uploading didn’t cancel when we click on that.  

### Expected behavior:

Uploading need to be cancel when user click on that button. 

### Actual behavior:

It upload the file. 

![rc](https://user-images.githubusercontent.com/19982139/39801425-ca7e8124-5388-11e8-840f-97299eb797b7.gif)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Duplicate: #10709 

Cheers
Thomas
