### ISSUE TITLE
Ability to edit all room titles as Administrator

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/Rocket.Chat#1072]
I've discovered I can't change the names of rooms that others have created, although I am an Administrator, because I don't "own" them.

**Comment by rwakida** [comment]
Hi @Theaxiom.  I'm unable to duplicate the error.  Are you sure the user is an Administrator?

What error message appears in:
1. Browser
2. Browser console
3. Server

**Comment by Theaxiom** [comment]
Ok, I thought it was intended. This was at work, I will take screenshots
tomorrow from work.

Thanks,
Travis Rowland
http://travisrowland.com
http://linkedin.com/in/travisrowland
http://about.me/travisrowland

-----------------------------------------------

This e-mail is privileged and confidential.  Do not forward, copy or print
without authorization.  If you are not the intended recipient of this
E-mail, you are hereby notified that any dissemination, distribution or
copying of this message is strictly prohibited. If misdirected, please
delete and notify the sender by e-mail at travis.rowland@gmail.com.

CAUTION: E-mail sent through the internet is not secure and could be
intercepted by a third party. For your protection, avoid sending
identifying information, such as account numbers or social security numbers.

**Comment by rwakida** [comment]
Missing pencil icon implies the user does NOT have the 'edit-room' permission.  

An admin has the 'edit-room' permission by default.  Check that the user (with missing pencil) has the 'admin' role in mongodb users collection.

```
	"roles" : {
		"__global_roles__" : [
			"admin"
		],
```

Also:
1. can the admin user view the 'Administration' menu option?
2. can the channel creator see the pencil icon?

**Comment by Theaxiom** [comment]
The admin user is my user account, yes the room creator can see the pencil icon, my account cannot. Also, I can view the administration menu and edit channels I have created. I will check the mongodb collection tomorrow when I am at work. I will also be sure to upgrade rocket.chat to the latest version to see if the issue resolves. If I continue to experience issues, i will let you know. Thank you for your help! :)

**Comment by geekgonecrazy** [comment]
@Theaxiom just curious.  Do you have any other admin's that you've appointed?  Are they able to see this?  This could be simply an issue of the default admin not having the permission added.

**Comment by Theaxiom** [comment]
My account wasn't default administrator, I was made administrator by another user. TBH, the version is a bit out of date, so let me get it updated first before I suck any more of your time. I will post my findings here tomorrow.

**Comment by geekgonecrazy** [comment]
@Theaxiom sounds good let me know if that resolves it for you.

**Comment by Theaxiom** [comment]
Since this is obviously now a support request, instead of a feature request (since what I was experiencing was not expected) I am going to close this. If I need support, I will obtain it via proper means. I don't typically open GitHub tickets to get technical support. Your time is better spent doing more productive things, than helping people use your software. Thanks for your help! :)

**Comment by geekgonecrazy** [comment]
@Theaxiom there is still a possibility you are experiencing an edge case that we haven't accounted for.  The permissions system is still pretty new.  So we are glad to try and work through these edge cases to see if we need to change something

**Comment by Theaxiom** [comment]
If that is the case, I will let you guys know then. Thanks! :)
