### ISSUE TITLE
OAuth logging in isn't closing my WebView in the app...

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#10725]
I made this video to show the issue, seemed easier than describing it:

https://youtu.be/ybZQQjdy6jE

### Description:

When logging into the mobile app of Rocket.Chat, I use an OAuth through WordPress.  

If you try logging into Rocket.Chat and are not yet logged into WordPress, there is a bug.  The popup brings up your WordPress login page, but after entering your login info in WordPress and logging in, the WebView doesn't close.  A new user ends up inside the WordPress site, as opposed to being sent back to the app.

If you're already logged in to the WordPress site, and then you try to login to Rocket.Chat using OAuth, then it works properly.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.58.1
* Operating System:  Android
* Deployment Method(snap/docker/tar/etc):  Heroku
* Number of Running Instances:  1
* DB Replicaset Oplog:  enabled
* Node Version: not sure where this would be listed
* mongoDB Version: I'm using Compose.Io

Scope: openid
Token Sent Via: Payload
Login Style: Popup

**Comment by theorenck** [comment]
@flantascience please update your server version. Thank you for your feedback.

**Comment by flantascience** [comment]
How do I re-open?

I updated to 0.64.1

Same problem as before with the OAuth login

Except now --- even after closing the Webview, the app goes completely grey after logging in.  C

**Comment by flantascience** [comment]
Can I reopen this @theorenck

**Comment by flantascience** [comment]
And so I'm clear, I'm using a "Custom OAuth" connected to my WordPress site.   Using the actual WordPress OAuth in Rocket.Chat has never worked for me.

**Comment by flantascience** [comment]
Opened this as a new issue [here](https://github.com/RocketChat/Rocket.Chat/issues/10747)
