### ISSUE TITLE
This is My output After Installing it on Centos

### ISSUE THREAD

**Issue by NoorQureshi** [RocketChat/Rocket.Chat#1073]
http://pastebin.com/raw.php?i=nF9pfEbd

**Comment by geekgonecrazy** [comment]
@NoorQureshi 

```
[[[[[ ~/Rocket.Chat ]]]]]                     

=> Started proxy.                             
=> Started MongoDB.                           
                                              
/root/.meteor/packages/meteor-tool/.1.1.9.ltydx3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: spawn ENOMEM
```
ENOMEM means the process ran out of memory.  

How much memory is in the machine you are installing this on?

**Comment by NoorQureshi** [comment]
I Have 3GB Ram on my VPS

**Comment by geekgonecrazy** [comment]
@NoorQureshi could you do: `free -mh` before executing to see how much of that 3GB you actually have free.  This way we have a good idea of how much it has to work with before diving into our options.

**Comment by k0nsl** [comment]
I've ran RC on a 512MB without any issues — however, the provider was too restrictive when it came to CPU usage (a OpenVZ-based VPS) so I'm now running it on a KVM VPS with 1GB and no issues :)

@NoorQureshi: what does `top` return for the `node` and `mongod` processes?

**Comment by geekgonecrazy** [comment]
@k0nsl as have I.  But i've also ran on 1Gb with 10 other things going and RC died just like that :)  Especially when using meteor to start it.  It eats a good bit up while starting up and building everything.  Docker images etc don't have that because its already compiled.

**Comment by k0nsl** [comment]
I noticed that, as well @geekgonecrazy. By the way, I've always ran RC using meteor directly (i.e non-docker).

**Comment by engelgabriel** [comment]
@NoorQureshi did you try using the `meteor build` command or only running just `meteor` directly?

**Comment by NoorQureshi** [comment]
Getting this: Error: spawn ENOMEM
when doing : meteor

**Comment by engelgabriel** [comment]
how much memory do you have on that machine? Maybe if you download the "compiled" tar file.. and just run using node directly, you won't need the extra memory to compile it before running.

**Comment by marceloschmidt** [comment]
Closing this for not having any activity since Oct 15. Please advise if this is still a problem.
