### ISSUE TITLE
Match error: Missing key 'value'

### ISSUE THREAD

**Issue by theundefined** [RocketChat/Rocket.Chat#10739]
### Description:
After upgrade from 0.60.4 to 0.64.1 version stop working plugin https://github.com/pragbits/stash2slack/tree/1.7.0 (last version working on stash).
It doesn't show on channel requests do by creating "COMPACT" style of opening pull requests.

Underground - plugin do requests like:

{"channel":"#channel","mrkdwn":true,"link_names":true,"attachments":[{"mrkdwn_in":["pretext","text","title","fields","fallback"],"fields":[{"title":"Description","short":false}],"fallback":"DESCRIPTION","color":"#2267c4","text":"DESCRIPTION","author_name":"AUTHOR","author_icon":"LINKTOAVATAR"}]}

changing fileds: part into [] fix problem - but it need recompilation of plugin :-) Workaround is change style from COMPACT to MINIMUM - but it would be nice if upgrade rocketchat doesn't break working options.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.64.1
* Operating System: linux
* Deployment Method(snap/docker/tar/etc):  docker
* Number of Running Instances: 2
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 3.2

### Steps to Reproduce:

1. have working instegration from stash with stash2slack plugin to rocketchat on version 0.60.4 (and olders) with COMPACT style when creating pull requests.
2. upgrade rocketchat from 0.60.4 to 0.64.1
3. create pull request

### Expected behavior:
message should show on rocketchat

### Actual behavior:
message doesn't show on rocketchat, rocketchat return:
{"success":false,"error":"Match error: Missing key 'value'"}

**Comment by tbaehr** [comment]
some data has been moved to required in validateAttachmentsFields 

https://github.com/RocketChat/Rocket.Chat/blob/73e8ba3038d6c52e3fb2e993c20edbbab2ddb982/packages/rocketchat-lib/server/functions/sendMessage.js

Title and Value are now required to be set ....

had similar problem with one of my own webHook due to this changes ... which in my opinion should not break older webHooks in such a way

**Comment by ggazzo** [comment]
@MarcosSpessatto
