### ISSUE TITLE
Limit downloads of custom-emojis

### ISSUE THREAD

**Issue by javi076** [RocketChat/Rocket.Chat#10735]
### Description:
We have a bit more than 1000 custom emojis in our server, and when you open the emojis selector, rocketchat downloads all the emojis (about 850MB)
This consume network bandwith, memory and makes the user's computer can not be used for some time (slowness)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 4
* DB Replicaset Oplog: 
* Node Version: 8.9.4
* mongoDB Version: 

### Steps to Reproduce:

1. Upload a lot of emojis
2. Open a chat root
3. Open emojis selector
![image](https://user-images.githubusercontent.com/10394672/39885494-21552270-5463-11e8-95b9-d24964f326d2.png)
4. RocketChat will downloads all the emojis (+1000 request)
![image](https://user-images.githubusercontent.com/10394672/39885770-cede7cd4-5463-11e8-95a3-6d7794b9a0c6.png)

### Expected behavior:

Download just a little amount of emojis by default

### Actual behavior:

Download all the emojis

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as I think https://github.com/RocketChat/Rocket.Chat/issues/9313 is already about caching those assets locally.

Cheers
Thomas
