### ISSUE TITLE
Ability to remove "link previews" in message

### ISSUE THREAD

**Issue by carrbrpoa** [RocketChat/Rocket.Chat#10740]
Is it possible to remove "link previews", like it is in Slack? It's very annoying, sometimes:

![image](https://user-images.githubusercontent.com/10212618/39927235-f71955ee-5507-11e8-9e56-cbd9cfb8c17c.png)

**Comment by mikaelmello** [comment]
This is already being discussed in the issue https://github.com/RocketChat/Rocket.Chat/issues/1929

If you want to disable all link previews, you can go to the Admin Settings -> Messages -> Disable Embed (or something close)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

In light of @mikaelmello's answer I'm closing this.

Cheers
Thomas
