### ISSUE TITLE
can't create user over restapi anymore. It doesn't accept boolean fields anymore

### ISSUE THREAD

**Issue by yennor** [RocketChat/Rocket.Chat#10742]
### Description:
We just updated to the newest rocket.chat version 0.64.1.
Unfortunately the rest call for creating new users doesnt work anymore, if you try to submit boolean fields like sendWelcomeMail and requirePasswordChange .
For requirePasswordChange the errormessage is:
Match error: Unknown key in field sendWelcomeMail

For sendwelcomemail:
Match error: Expected boolean, got string in field requirePasswordChange

We use the http_build_query to encode the post_string.
It sets the boolean values to 0 or 1. But even when I transmit true or false it doesn't work.

it worked in previous versions.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: linux debian stretch
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version:

**Comment by yennor** [comment]
yes, the call is (using curl in php):
https://example.com/api/v1/users.create
postfields:
email=Test%40test.de&username=test&name=test&password=test&requirePasswordChange=0&sendWelcomeMail=0

**Comment by MarcosSpessatto** [comment]
@yennor can you please share your PHP script? To help us to fix this issue?

**Comment by mbrodala** [comment]
I just stumbled upon the same issue while trying to toggle the `active` flag of a user: 

    Match error: Expected boolean, got string in field data.active

No matter if I passed `true`/`false` or `1`/`0`, I always got the same error.

In my case the `POST` request where performed via [`form_params` using the Guzzle HTTP client](http://docs.guzzlephp.org/en/stable/quickstart.html#sending-form-fields).

However, I got this fixed by switching to a JSON-encoded `body` instead of form data. This way the data types are kept intact.

**Comment by MarcosSpessatto** [comment]
@mbrodala unfortunately this endpoint does not support `form-data` request, if I understand correctly the client that you are using.

@yennor I tested this endpoint again, and it works with `true/false` parameters. When I changed it to `0/1` I got the same error that you are getting. Can you please try again, ou share your PHP script?

**Comment by mbrodala** [comment]
@MarcosSpessatto I don't think the endpoint or RocketChat is at fault here. By definition basically everything in `form_data` is a string, so unless you add some heuristic to convert incoming values, errors like these can be expected. Only JSON avoids this problem.
