### ISSUE TITLE
Version 0.64.2

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#10744]
# Release [0.64.2](https://github.com/RocketChat/Rocket.Chat/milestone/117)

For any regression, open a new issue and link to this one.

## Before Release - Preparation
- [x] Create the issue to track the release progress
- [ ] Define the highlights from release PRs as suggestion to be included on Blog Post
- [ ] Talk to the Marketing Team about the Blog Post release
- [ ] Talk to the Documentation Team about the Docs release
- [ ] Sync translations from [LingoHub](https://translate.lingohub.com/rocketchat/rocket-dot-chat/dashboard)

## Release Candidate 1
- [x] Delete branch `release-candidate`
- [x] Create branch `release-candidate` based on `develop`
- [x] On branch `release-candidate` run `npm run release` and follow the steps
- [x] Publish the branch and the generated tag
- [x] Edit the tag on GitHub and paste the generated History removing the version from the first line and mark the checkbox **This is a pre-release**
- [x] Ensure the build is passing on CircleCI
- [x] Ensure the build is passing on Docker Hub

## Release Candidate 2
- [x] Merge `develop` into `release-candidate` branch
- [x] On branch `release-candidate` run `npm run release` and follow the steps
- [x] Publish the branch and the generated tag
- [x] Edit the tag on GitHub and paste the generated History removing the version from the first line and mark the checkbox **This is a pre-release**
- [x] Ensure the build is passing on CircleCI
- [x] Ensure the build is passing on Docker Hub

## Release Candidate 3
- [x] Merge `develop` into `release-candidate` branch
- [x] On branch `release-candidate` run `npm run release` and follow the steps
- [x] Publish the branch and the generated tag
- [x] Edit the tag on GitHub and paste the generated History removing the version from the first line and mark the checkbox **This is a pre-release**
- [x] Ensure the build is passing on CircleCI
- [x] Ensure the build is passing on Docker Hub

## Final Release
- [x] Merge `develop` into `release-candidate` branch
- [x] Create a new branch `release-0.64.2` based on `release-candidate`
- [x] On branch `release-0.64.2` run `npm run release` and follow the steps **TODO: fix the history**
- [x] Publish only the branch
- [x] **Draft a new release** on GitHub
  - [x] Enter tag version as 0.64.2
  - [x] Select target **master**
  - [x] Enter release title as 0.64.2
  - [x] Paste the history removing the version from the first line
  - [x] Save as **draft**
- [x] Create a PR from the branch `release-0.64.2` with the same history from the tag/release
- [x] Ensure the build is passing on CircleCI
- [x] Ensure the build is passing on Docker Hub
- [x] When build is passing ask for approval
- [x] When approved merge it!
- [x] When merged edit the release/tag and publish it

## After Release - Conclusion
- [ ] Check if related issues was closed
- [ ] Check if related issues was assigned to the correct milestone
- [ ] Check with the Marketing Team about the Blog Post release
- [ ] Check with the Documentation Team about the Docs release
- [ ] Create a Sync PR to merge back master to develop
- [ ] Merge Sync PR

**Comment by tim-soft** [comment]
Will this release exist as a stable 0.64.x snap build? https://github.com/RocketChat/Rocket.Chat/issues/10693
