### ISSUE TITLE
Did not get notifications from channel

### ISSUE THREAD

**Issue by axchemezov** [RocketChat/Rocket.Chat#10748]
### Description:

Did not get email about new messages in channel.

For example:
1. We have a channel #test and all users have same preferences. 
2. We need that if userX offline, but userY message in that channel then Rocket.Chat push email to user1 about that new message in channel.

There was something similar https://github.com/RocketChat/Rocket.Chat/issues/10361#issuecomment-379232010 but it didn't help.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0
* Operating System: Linux x64 (4.13.16-2-pve)
* Deployment Method(snap/docker/tar/etc): docker
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3

### Steps to Reproduce:

1. Settings for users and channel is:
http://priscree.ru/img/2d5b542cfee16d.png
http://priscree.ru/img/848ef1e39210aa.jpg
2. User1 offline. 
3. User2 send message "hi there"  in channel #test.

### Expected behavior:

User1 get email notification:
"User1 has posted a message in #test
...
hi there
|Go to message|"

### Actual behavior:

There is no message to email

**Comment by axchemezov** [comment]
@rodrigok Yes it is. All emails of users in that room is verified.

**Comment by sampaiodiego** [comment]
@axchemezov did you check server logs? is the SMTP settings correct configured? have you tested SMTP settings from test button on admin?
