### ISSUE TITLE
[BUG] RocketChat.MessageAction.getPermaLink returns wrong path

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat#10746]
### Description:
When clicking on Reply button on a broadcast channel the markdown permalink being created is incorrect. It's always referring to the message as if it was sent to a DM instead to a channel or group.
Tested on [https://open.rocket.chat](https://open.rocket.chat)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
### Steps to Reproduce:

1. Join a broadcast channel and click on the Reply button.
2. A DirectMessage is opened with the user being replied.
3. The permalink to the replied message is always defined as `direct`.
Eg.: `[ ](https://open.rocket.chat/direct/user123?msg=xyz56789)`

### Expected behavior:
My broadcast room is either a channel or a group so the permalink should be built accordingly:
 `[ ](https://open.rocket.chat/channel/channelName?msg=xyz56789)`
or
 `[ ](https://open.rocket.chat/group/groupName?msg=xyz56789)`

**Comment by ggazzo** [comment]
actually the problem is the `RocketChat.MessageAction.getPermaLink` function that uses the type of opened room to create the url, but sometimes the message is from another room...
