### ISSUE TITLE
UI Color

### ISSUE THREAD

**Issue by 707eric** [RocketChat/Rocket.Chat#10750]
I am using a a custom dark theme in RocketChat which for the most part works very well.  I do have one lingering issue which is I can't find what the right place to change the color of the icon that you can just barely see in the image.

![image](https://user-images.githubusercontent.com/12947309/39963079-b54ea96a-5616-11e8-8b3a-85d0aeb52a2a.png)

Ideally I would like it to be white or some other color highly visible.  Once that is fixed I will have a seemingly fully functional dark theme.

Thanks!

**Comment by kaiiiiiiiii** [comment]
Hi @707eric,

I’d like to refer you to this page to get proper support:
https://rocket.chat/docs/getting-support/

The Rocket.Chat team decided to use GitHub only for issues and yours look more like a support case to me, not like an issue with the core component  :)

Thanks,
Kai
