### ISSUE TITLE
Lost channels in the left sidebar

### ISSUE THREAD

**Issue by ispryt** [RocketChat/Rocket.Chat#10756]
Please see the bug on video: http://dropmefiles.com/Pv07t
This bug i see on Windows 10 and Windows 7 
Desktop version app: Version 2.10.5

Linux rc 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux
|               SERVER RUNNING              | 
+-------------------------------------------+ 
|                                           | 
|  Rocket.Chat Version: 0.64.1              | 
|       NodeJS Version: 8.9.3 - x64         | 
|             Platform: linux               | 
|         Process Port: 3000                | 
|             Site URL: https://domain | 
|     ReplicaSet OpLog: Disabled            | 
|          Commit Hash: 54738c011b          | 
|        Commit Branch: HEAD                | 
|                                           | 
[32m+-------------------------------------------+

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

The repository for the Electron Client is over [here](https://github.com/RocketChat/Rocket.Chat.Electron), please open the issue there :)

Cheers
Thomas
