### ISSUE TITLE
Danish translation is horrible

### ISSUE THREAD

**Issue by danchr** [RocketChat/Rocket.Chat#10758]
### Description:

The Danish translation is horrible and obviously machine-generated. Please remove it.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: macOS
* Deployment Method(snap/docker/tar/etc): Rocket Chat Cloud
* Number of Running Instances: N/A
* DB Replicaset Oplog: N/A
* Node Version: N/A
* mongoDB Version: N/A 

### Steps to Reproduce:

1. Open Rocket Chat.
2. Set language to Danish.

### Expected behavior:

Rocket Chat either has a sensible Danish localisation, or falls back to English.

### Actual behavior:

A Danish localisation exists but is of extremely poor quality, being obviously machine-translated. It consistently translates the wrong meaning of homonyms. As an example, it uses “Spare” for the English “Save” — which implies saving money rather than content. That's just wrong, horribly wrong… In all, the errors are too many to enumerate here, with correctly translated phrases being the exception rather the norm.

The current localisation is positively worse than nothing, given that most Danes do speak English. Other than that, it's also vaguely offensive to see that someone cared so little about the quality of their work to offer this. I suggest you remove the localisation, and don't reinstate it again unless you've had a Danish speaker look it over.

<img width="371" alt="screen shot 2018-05-14 at 11 37 01" src="https://user-images.githubusercontent.com/59300/39989831-52c88daa-576b-11e8-9992-75d0494c00dc.png">

**Comment by CrimsonAndrew** [comment]
I am sorry to inform, but are you sure thay you are talking about mobile verion? As far as I know mobile version have only these translations:

English;
Portuguese;
French;
Hindi;
Spanish; 

Or maybe it's about desktop version? You should open it here https://github.com/RocketChat/Rocket.Chat.Electron I met this problem with Ukrainian version ))

**Comment by kaiiiiiiiii** [comment]
@CrimsonAndrew The desktop app is using the translations of the rocket.chat core (server). No need to open an issue in the Electron repository.

**Comment by sampaiodiego** [comment]
thanks @HammyHavoc for the words, this is the open source spirit.

I'll be closing this issue since it doesn't add much resources for improvement.

everyone is welcome to help in translations, please check https://docs.rocket.chat/contributors/contributing/translating
