### ISSUE TITLE
REST API Channel List Changed

### ISSUE THREAD

**Issue by cloudsandladders** [RocketChat/Rocket.Chat#10751]
### Description:

The REST API changed for getting joined and all channels, which broke some of my custom scripts.  I think the API should be more consistent between groups and channels, so it doesn't need to change in the future.

### Server Setup Information:
* Version of Rocket.Chat Server:  0.63.3
* Operating System: Ubuntu 16.04.4 x64
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.4
* mongoDB Version: 3.2.7
* StorageType: FileSystem

### Changes in REST API

-get all channels: '/api/v1/channels.listAll' became '/api/v1/channels.list'
-get all groups: '/api/v1/groups.listAll' did not change

-get all joined channels: '/api/v1/channels.list' became '/api/v1/channels.list.joined'
-get all joined groups: '/api/v1/groups.list' did not change

### Suggestion
Use similar API structure between channels and groups.

**Comment by graywolf336** [comment]
What versions did this change between?

**Comment by cloudsandladders** [comment]
It looks like these api changes were made over a year ago.  It must have been just a fluke in my code.  The use of ".joined" and "listAll" is a tad inconsistent, but not a huge deal.
