### ISSUE TITLE
Users can't change avatars after update to 0.64.1

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#10764]
### Description:

The "My Account" area no longer has a place for avatars.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.64.1
* Operating System:  Windows
* Deployment Method(snap/docker/tar/etc):  heroku
* Number of Running Instances:  1
* DB Replicaset Oplog:  enabled
* Node Version:  v8.11.1
* mongoDB Version:  not sure

**Comment by darkknightpl** [comment]
+1, same problem here - after update to _0.64.1_ users can't change their avatars

After clicking on _avatar -> My Account_  option  _Avatar_ is missing:

![image](https://user-images.githubusercontent.com/16231411/40049617-85bae7ce-5835-11e8-92d3-adba7e804267.png)

It was available in previous versions (here screenshot from version 0.58.4):

![image](https://user-images.githubusercontent.com/16231411/40049821-fe808196-5835-11e8-8664-66692bd474ef.png)

We have self-hosted version running on Docker.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): Docker 
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.11.1
* mongoDB Version: 3.2.17

**Comment by darkknightpl** [comment]
Solved, i've changed settings in _Administration -> Accounts_:

![image](https://user-images.githubusercontent.com/16231411/40053090-45cecbf2-5840-11e8-90c0-80b8f280b6cb.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

**Comment by imeleges** [comment]
I recently upped my serve to the newest version 0.66.3 to see if it was fixed, but still the same.
My settings are correct but no-one can now change their avatar.
OS: CentOS 7

**Comment by TwizzyDizzy** [comment]
Then please open a new bug report and refer this one (just so we know the context).

Cheers & Thanks
Thomas

**Comment by reetp** [comment]
@fromage9747 see above comments.
Test on latest version 0.70.0 and if the bug still exists open a new bug and reference this one please.

**Comment by fromage9747** [comment]
@reetp After a server reboot the avatar finally was loaded.  but this did not occur on "Save Changes".  Thank you for the follow up.
