### ISSUE TITLE
Unable to change user or delete

### ISSUE THREAD

**Issue by augustechartre** [RocketChat/Rocket.Chat#10765]
Hello,

### Description:

When I add user, server reboot.
When I try to add role, there is no roles in list.
I can't change any settings of user.
When I try to delete, I have error message: internal error

Log: Exception while invoking method 'deleteUser' TypeError: Cannot read property 'indexOf'

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar 
* Number of Running Instances: 1
* DB Replicaset Oplog: 1
* Node Version: 8.11.1
* mongoDB Version: v3.4.3-rc2

### Relevant logs:
`I20180514-19:43:38.027(2) Exception while invoking method 'deleteUser' TypeError: Cannot read property 'indexOf' of undefined     at MethodInvocation.deleteUser (/var/lib/rocket.chat/bundle/programs/server/app/app.js:8474:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_lib.js:2186:28)     at maybeAuditArgumentChecks (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:875:23)     at /var/lib/rocket.chat/bundle/programs/server/packages/ddp-server.js:754:85  `

Thanks

**Comment by TwizzyDizzy** [comment]
Could please try to better describe how to reproduce this issue. From what you wrote it doesn't, to me, become evidently clear how to reproduce.

Cheers & Thanks
Thomas

**Comment by geekgonecrazy** [comment]
No response going to close

**Comment by balleddog** [comment]
Duplicate of #15856
