### ISSUE TITLE
[BUG] "Empty error message" when trying to add a new user to a private group 

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10770]
### Description:

![screen shot 2018-05-14 at 19 02 12](https://user-images.githubusercontent.com/551004/40025894-7fa23d9c-57a9-11e8-9678-f47d0f3bfaf7.png)

As a normal user, I can see the button to add new users, but when I try to add I only see an empty error message.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2-rc.0
* Operating System: Linux

**Comment by ggazzo** [comment]
closed by #10564
