### ISSUE TITLE
Cannot fetch custom props on Rooms model

### ISSUE THREAD

**Issue by yandzee** [RocketChat/Rocket.Chat#10773]
I extend `rocketchat_room` table to have my custom prop on it, and now I need to use that prop in `packages/rocketchat-ui-sidenav/client/roomList.js`. I do
```
const rooms = RocketChat.models.Rooms.find({}, {
	fields: {
		myCustomProp: 1,
		name: 1
	}
}).fetch();
```
but it gives in result `rooms` is array of objects with two props: `_id` and `name`, no `myCustomProp` is presented. So, do you guys know how to fetch that prop correctly?

**Comment by graywolf336** [comment]
As this is not an issue with Rocket.Chat but instead a development question, I will refer you to our forums for that question: https://forums.rocket.chat/
