### ISSUE TITLE
Lost channels in the left sidebar

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat#10774]
@ispryt commented on [Tue May 15 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/722)

Please see the bug on video: http://dropmefiles.com/Pv07t
This bug i see on Windows 10 and Windows 7
Desktop version app: Version 2.10.5

Linux rc 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux
| SERVER RUNNING |
+-------------------------------------------+
| |
| Rocket.Chat Version: 0.64.1 |
| NodeJS Version: 8.9.3 - x64 |
| Platform: linux |
| Process Port: 3000 |
| Site URL: https://domain |
| ReplicaSet OpLog: Disabled |
| Commit Hash: 54738c0 |
| Commit Branch: HEAD |
| |
[32m+-------------------------------------------+

---

@gdelavald commented on [Tue May 15 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/722#issuecomment-389187024)

Hey @ispryt, thanks for your report. I'll move this issue to the main repository as this seems like an issue with the web app.

**Comment by TwizzyDizzy** [comment]
Ah sorry, I explicitly asked him to move it to the Electron repo but if the root cause is in the server markup, then it's correct to have it here. Sorry for the fuzz.

Cheers
Thomas

**Comment by ispryt** [comment]
I replayed the video: https://yadi.sk/i/Lb_TL4pu3WHjrH

**Comment by ispryt** [comment]
[Imgur](https://i.imgur.com/iquDApK.jpg)
Screenshot

**Comment by geekgonecrazy** [comment]
Shouldn’t be an issue any more.  If it is please let us know
