### ISSUE TITLE
Notification Preferences are not saved

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat#10787]
### Description:

Notification preferences are not saved. I changed the notification preference of a direct chat from default to all messages for both mobile and email. But it changes automatically to "Use Account Preferences" for Mobile and "Mentions" for Email.

### Server Setup Information:

* Version of Rocket.Chat Server: open.rocket.chat
* Operating System: Ubuntu 17.10

**Comment by graywolf336** [comment]
@RocketChat/core heads up...

**Comment by himbeere** [comment]
Works for me with 0.64.2 on my own server.

**Comment by antgel** [comment]
@sampaiodiego Could this be related to PR #10686 ?

**Comment by sampaiodiego** [comment]
@ubarsaiyan are you changing the notification preference under "My Account" page? or is it on specific channel?

I could reproduce it for the `Email` field under "My Account" page only.

**Comment by sampaiodiego** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/10847 fixes the issue on the email btw

**Comment by himbeere** [comment]
>I could reproduce it for the Email field under "My Account" page only.

yes. only there and only that setting is affected. thanks for the fix.

**Comment by ubarsaiyan** [comment]
@sampaiodiego The issue occurs when saving the preferences for a particular channel or dm.

**Comment by ubarsaiyan** [comment]
https://drive.google.com/file/d/1L_gSYblssaGPXbkTWAQUttJgFJSmw7EE/view?usp=sharing
Video describing the issue ^ on dm with Hubot, using Chrome 66 and present version of open.rocket.chat

**Comment by sampaiodiego** [comment]
many thanks @ubarsaiyan .. not sure what I did before, but now I'm able to reproduce it
