### ISSUE TITLE
Heroku - One Click Install Not Working

### ISSUE THREAD

**Issue by tewksbum** [RocketChat/Rocket.Chat#1078]
Getting the following error:

-----> Fetching custom git buildpack... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
Meteor 1.2.0.2 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/tmp/buildpack_6a64fef06d707c391f7d9a11b20a6258/meteor-iy3u/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Bundling bundle
$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app

**Comment by geekgonecrazy** [comment]
@tewksbum during the UI step of the one-click did you set the ROOT_URL near the bottom?

**Comment by tewksbum** [comment]
Okay - apparently a UTS error!  I had inputted the app name above and presumed the parameter passed in below.  I manually inputted and it has setup successfully.  Thanks!

**Comment by geekgonecrazy** [comment]
Glad to hear :+1:
