### ISSUE TITLE
[Request] Message-placeholder for all deleted user messages

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#10783]
### Description:

GDPR enforces us to delete all personal information of the user when they leave our company. Currently the only `Message Erasure Type` option that does not leave too much information behind is `Delete All Messages`.

However this completely removes all messages of the user, and does not leave **any** indication that message has ever existed. The end result is that the flow of the discussion is disrupted and can cause very unfortunate misunderstandings. Someone may have said something that can now be interpreted as an insult to a valid question just above the original deleted message.

A good trade-off for the complete deletion would be replacing both sender (with rocket.cat) and the actual message with a 'Message removed' placeholder. This way anyone scrolling the chat history would understand the flow of the past discussion.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 8
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.4

**Comment by ulope** [comment]
IANAL but I'm pretty sure that work related conversation is not PII under GDPR. Otherwise you would have to scrap every project any employee ever worked on once they leave the company.
