### ISSUE TITLE
[Feature request, UX improvement] Pin Favorites

### ISSUE THREAD

**Issue by Oleksandr-Silin** [RocketChat/Rocket.Chat#10796]
Hello, I would like to pin Favorites group, so I can see it all time and don't need to scroll to it - fast access.
It can have own scrollbar, so Direct messages and other stuff would be scrolled separately.

In my case we have a lot of users and channels. It would be great to have such fast access to Favorites.

**Comment by kaiiiiiiiii** [comment]
You can already favorite channels by using the 3 dots menu in the sidebar. In addition you need to set "group by favorites" in the sidebar sort options.

![2018-05-17 14_24_02-window](https://user-images.githubusercontent.com/4711233/40177218-389882c6-59de-11e8-9c34-843f9ede2c54.png)
![2018-05-17 14_26_47-window](https://user-images.githubusercontent.com/4711233/40177298-6deec2d2-59de-11e8-90d0-52ca28faabda.png)

**Comment by Oleksandr-Silin** [comment]
@kaiiiiiiiii Hello, request not in How to create Favorites. I want them to be Pinned, so it would not be scrolled out, when i do scroll on sidebar.
![image](https://user-images.githubusercontent.com/4909254/40178014-89646ff6-59e0-11e8-9ab2-83c601abfbb9.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

I took me a while to figure out what you're actually saying but I think now I got it.

@ Rocket.Chat team

This is a request to have favorite rooms/groups/whatever have some kind of `position:fixed` in the sidebar while everything that's not favourite would scroll "below" it (z-index).

Cheers
Thomas

**Comment by marceloschmidt** [comment]
This is not something we think would be good. Imagine if you had so many favorite channels that you can't even see any other channels?
