### ISSUE TITLE
Channels/groups list behavior

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#108]
Now, this lists only show rooms that have an action within 2 days. If a room does not have any message in this time, they can only be found on "history".

I think we must change this behavior. The room lists should be persistent, you decide what to hide or not. But, if you choose to hide a room and a new message is sent to it, the room will appear again. If you do not want any notifications about a room, you must leave it.

What do you all think about it? Specially @RocketChat/owners

**Comment by rodrigok** [comment]
2 states is better I think, subscribed or not subscribed to the room.

**Comment by engelgabriel** [comment]
@rodrigok this is not what @sampaiodiego meat. 

I don't agree with Diego.. some groups are just for a quick chat... and thats fine if they are hidden after becoming inactive. There shall be a way to search for them, in the same way you will search for public channels.

But if you want it to stay.. you should favorite it.
