### ISSUE TITLE
Manually create a new user with an email domain not in the whitelist

### ISSUE THREAD

**Issue by rodripf** [RocketChat/Rocket.Chat#10809]
### Description:

I have a list of allowed domains for user registration working great. 
But I'd like to be able to create users manually with email domains not in the list. 
So for manually created users I think I should be able to avoid this validation, and be able to add the users anyway.

### Steps to Reproduce:

1. Set a list of allowed domains for user registration.
2. Create manually an user with an email not in the list of authorized domains
3. Try to save

### Expected behavior:

1. I want to actually create the user.

### Actual behavior:

1. The domain validation forbids me from creating the user unless I use a valid domain for the email address.

### Current workaround:
1. Add the new domain to the whitelist
2. Create the new user
3. Remove the domain from the whitelist

**Comment by rodripf** [comment]
#975

**Comment by cpitman** [comment]
This is similar to #5099

**Comment by rodripf** [comment]
You are right! It's the same, I didnt' find it when searching.
