### ISSUE TITLE
oauth google... how to configure?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1081]
please add to chat administration a page link with some examples how to configure oauth and callback urls

and... exist this page?  I can't configure oauth with google because de callback url is missing...where is it?

**Comment by maxlinux2000** [comment]
today a can't login in your demo.rocket.chat nor with facebook nor google.

**Comment by maxlinux2000** [comment]
so I ask here:  sorry
I have configured GCM in the chat... but now.. witch steps to test it?

**Comment by marceloschmidt** [comment]
@maxlinux2000 the oauth is specified by meteor. You should use  `http://[your_host_name]/_oauth/google`

**Comment by maxlinux2000** [comment]
but.... the port number too?

http://chat.mydomain.org:3000/_oauth/google

**Comment by marceloschmidt** [comment]
Yes

**Comment by maxlinux2000** [comment]
But still not work! :(

![xoauth](https://cloud.githubusercontent.com/assets/5683921/10490633/6e272bac-72a2-11e5-8060-42444423fb35.png)
![xoauth2](https://cloud.githubusercontent.com/assets/5683921/10490635/6e29af6c-72a2-11e5-81eb-b5efef607437.png)
![xoauth3](https://cloud.githubusercontent.com/assets/5683921/10490634/6e27c012-72a2-11e5-9b35-a32d5b3b321d.png)

**Comment by patelm42** [comment]
Has this been resolved? I'm having the same issue

**Comment by justinmartin** [comment]
I am unable to get Google oauth working as well.

**Comment by goocastro** [comment]
same issue here

**Comment by phillip-white-sociomantic** [comment]
I have this working. I used the guide here https://github.com/RocketChat/Rocket.Chat/wiki/OAuth-Provider-Configuration. Try setting the callback url to `<<website_url>>/_oauth/google?close`?

**Comment by Balancer** [comment]
If it is still important. That authorization through Google OAuth worked, it is necessary to confirm the right for a doment in Google Webmasters and to allow use of this domain in authorization settings.
