### ISSUE TITLE
[Bug] Send or receiver images not work on livechat

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#10813]
### Description:

I can't send image from my PC or receive an image on my PC in a conversation on livechat.

This feature fine woks on chat, but not work on livechat.

When I send an image it displays like this:

![screenshot_1](https://user-images.githubusercontent.com/17053653/40255351-3e3cda58-5abd-11e8-8de9-0e7baa03bf49.png)

When I receiver an image it displays like this:

![screenshot_2](https://user-images.githubusercontent.com/17053653/40255400-5f46d690-5abd-11e8-8bcd-cbcfef0b87c2.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Linux Ubuntu 4.4.0-1049-aws
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: enabled
* Node Version: v8.9.4

**Comment by renatobecker** [comment]
Hi @guilhermecfviana!
We have been working on this feature and there is a PR in the review process to relase it.
Please, take a look here: #10514.
If it´s what you're looking for, please just folow the review process to find out when this feature will be avaliable.

Thanks.
