### ISSUE TITLE
Windows 10 v 1803 and R.C+ 2.10.5.628 incompatible

### ISSUE THREAD

**Issue by noloader** [RocketChat/Rocket.Chat#10814]
### Description:

Windows 10 v 1803 and Rocket.Chat+ 2.10.5.628 incompatible

### Server Setup Information:

* Version of Rocket.Chat Server: 
  - Unknown

* Operating System: 
  - Windows 10 Pro x64 version 1803 (OS Build 17134.48)

* Deployment Method(snap/docker/tar/etc): 
    - Downloaded Windows installer, ran installer

* Number of Running Instances: 
    - Unknown. The best I can tell something starts but no main Window is displayed. So maybe 1 instance?

* DB Replicaset Oplog: 
    - Unknown. Whatever version is bundled with RocketChat+.

* Node Version: 
    - Unknown. Whatever version is bundled with RocketChat+.

* mongoDB Version: 
    - Unknown. Whatever version is bundled with RocketChat+.

### Steps to Reproduce:

1. Upgrade to latest version of Windows, which is circa May 18, 2018
2. Download the latest version of RocketChat+, which is circa May 18, 2018
3. Attempt to run RocketChat after Windows 10 upgrade.

Prior to the Windows 10 v1803 upgrade I had a lesser version of Windows 10. I also had RocketChat+ 2.10.2.610. They worked fine together.

After upgrading neither RocketChat+ 2.10.2.610 nor 2.10.5.628 would run. They seem to launch or partially start, but no main window is drawn. There are no events registered in the Windows Application or System logs.

Running a Windows Compatibility Test seems to indicate Microsoft knows there is a problem. But searching through the issue reporter I don't see a squawk for Windows 10 version 1803. I'm guessing they failed to tell anyone about it.

We probably cannot share the logs with the project. The organization is a defense contractor and they are uber paranoid. My sincere apologies for that.

![brick-chat](https://user-images.githubusercontent.com/3538226/40255010-935b9948-5ab3-11e8-9c1b-11b1bd552f98.png)

**Comment by kaiiiiiiiii** [comment]
Hi @noloader,

I would like to refer you to another repository as this is an issue with the rocket.chat electron app and not with the server component.

https://github.com/RocketChat/Rocket.Chat.Electron

Feel free to open an issue over there :)

Thanks,
Kai

@TwizzyDizzy :)

**Comment by noloader** [comment]
Thanks @kaiiiiiiiii.
