### ISSUE TITLE
how to implement RocketChat-e2e

### ISSUE THREAD

**Issue by abugandar** [RocketChat/Rocket.Chat#10828]
how to add RocketChat-e2e Package
i need 

    E2E Encryption support for Direct messaging
    E2E Encryption support for Private groups
    E2E Encryption support for uploaded files
    Offline encrypted chats

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

The issue you should follow is #36 and the according PR #10094. There is nothing YOU can do to speed this up. As of now, you can use OTR which does have open bugs that probably won't get fixed. Once the new E2E feature is there, there will be an announcement.

The issue at hand does not add any valuable information or does not describe any bugs and is therefore closed.

Cheers
Thomas
