### ISSUE TITLE
[BUG] Invite users button shows up even if you don't have permission

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#10834]
Happening on 0.64.2-rc.2

I don't have any of these permissions, but the button on the contextual bar still shows up:

add-user-to-joined-room
add-user-to-any-c-room
add-user-to-any-p-room

Then when I try adding someone, an empty red alert shows up.

**Comment by diegolmello** [comment]
Yeah, it's happening here too.

**Comment by MartinSchoeler** [comment]
This seems to be working on the latest version
![screencapture](https://user-images.githubusercontent.com/20868078/93356923-2744a300-f816-11ea-99db-2ca95b8022b1.gif)

I will close this issue for now, if you experience it again or find another place that the permissions are not working, please reopen this with updated details. Thanks!
