### ISSUE TITLE
macOS High Sierra energy consumption too high

### ISSUE THREAD

**Issue by smnbbrv** [RocketChat/Rocket.Chat#10854]
### Description:

The energy consumption of the application in the background mode is unbelievably high. And I am nearly not using the app. Any other chat is consuming literally nothing compare to rocketchat.

![image](https://user-images.githubusercontent.com/13453858/40410217-7e31ebe0-5e6d-11e8-9505-c6d967961eac.png)

![image](https://user-images.githubusercontent.com/13453858/40410363-e82b63a0-5e6d-11e8-8b02-dc0aec6595c4.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3. 

### Expected behavior:

It should not consume the energy (at least that much) in background mode

**Comment by kaiiiiiiiii** [comment]
Hi @smnbbrv,

this is a problem with the electron app, not with the server component. Therefore I'd like to refer you to the electron app repository:
https://github.com/RocketChat/Rocket.Chat.Electron

Feel free to open an issue over there.

Thanks

**Comment by smnbbrv** [comment]
ok, moving it there
