### ISSUE TITLE
Cannot upload APN cert/key

### ISSUE THREAD

**Issue by mleatherb** [RocketChat/Rocket.Chat#10859]
### Description:

The fields for APN key/cert in the Push section are text fields and do not allow for uploading the respective files

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: linux/heroku
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: 8.11.1
* mongoDB Version: 

### Steps to Reproduce:

1. Go to Admin Panel
2. Go to Push section in admin panel
3. Try to upload APN cert/key into respective fields

### Expected behavior:

I should be able to drag/drop or search local file system for the files

### Actual behavior:

You cannot upload files for the APN cert/key fields

**Comment by KirbySSmith** [comment]
You need to convert the key and cert to pem files then copy the text from the file.

Certificate generation and conversion instructions are available at: https://blog.serverdensity.com/how-to-renew-your-apple-push-notification-push-ssl-certificate/ **Stop After step five.** Then, open the files in a text editor and copy the certificate and key information into the administration → push → certificates and keys section → APN Key and APN Cert fields

**Comment by mleatherb** [comment]
Thanks @KirbySSmith , that worked. In case someone else comes across this. You will also need to restart the services for notifications to start working.
