### ISSUE TITLE
 E2E encryption needed

### ISSUE THREAD

**Issue by abugandar** [RocketChat/Rocket.Chat#10852]
E2E encryption will be implemted in the next new version or not ??

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

The issue you should follow is #36 and the according PR #10094. There is nothing YOU can do to speed this up (well if you can code and contribute to the PR, you actually could). As of now, you can use OTR which does have open bugs that probably won't get fixed. Once the new E2E feature is there, there will be an announcement. As you can see #36 is in the milestone "mid-term" which at least gives the indication that it's not gonna be there very soon.

The issue at hand does not add any valuable information or does not describe any bugs and is therefore closed.

Cheers
Thomas
