### ISSUE TITLE
Can't disable push mobile notifications

### ISSUE THREAD

**Issue by toupeira** [RocketChat/Rocket.Chat#10856]
### Description:

I have push mobile notifications disabled in my account but am still receiving them using the native Rocket.Chat app on Android.

On a related note, I also have offline email notifications disabled (which does indeed work) but the form always reverts to show "Default (Every Mention/DM)" after saving:

![selection_001](https://user-images.githubusercontent.com/6501/40415529-5f2aa6ac-5e7b-11e8-9f39-e17667e89307.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: Debian, Android
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: enabled
* Node Version: 8.9.4
* mongoDB Version: 3.2.18

### Steps to Reproduce:

1. Enable push notifications (not sure if this is the default)
2. Verify that they work
3. Disable push notifications in user account settings

### Expected behavior:

Push notifications shouldn't get sent.

### Actual behavior:

Push notifications are still being sent.

**Comment by sampaiodiego** [comment]
@toupeira the push notifications you're receiving are for old conversations? there was an issue for new conversations not applying user preferences.. this and the value for "email notifications" being reverted were fixed by https://github.com/RocketChat/Rocket.Chat/pull/10847

**Comment by toupeira** [comment]
Hmm they were new *messages* but from existing *conversations*, so if
that's what you meant then it sounds like this was indeed fixed :)

Feel free to close the issue, I'll reopen if I still experience problems
with 0.65.0.

Thanks!

**Comment by sampaiodiego** [comment]
ok thx.. pls let us know if you still experience the issue.
