### ISSUE TITLE
Version conflicts of coffeescript on Meteor 1.6.1.1

### ISSUE THREAD

**Issue by tinlans** [RocketChat/Rocket.Chat#10850]
### Description:

I noticed that Rocket.Chat had bumped the meteor version to 1.6.1.1 since 0.63.0, so I did a clean and fresh installation of Meteor 1.6.1.1 on my environment. However, I got the following error messages while I was performing **meteor npm start** at the root directory of latest Rocket.Chat:

```
> Rocket.Chat@0.65.0-develop start /home/rocketchat/Rocket.Chat
> meteor npm i && meteor

> Rocket.Chat@0.65.0-develop postinstall /home/rocketchat/Rocket.Chat
> cd packages/rocketchat-katex && npm i

=> Running Meteor from a checkout -- overrides project version (Meteor 1.6.1.1)
For compatibility, the PACKAGE_DIRS environment variable is deprecated and will be removed in a future Meteor release.
Developers should now use METEOR_PACKAGE_DIRS and Windows projects should now use a semi-colon (;) to separate paths.
[[[[[ ~/Rocket.Chat ]]]]]                     

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Conflict: Constraint coffeescript@1.0.4 is not satisfied by coffeescript 2.0.3_4.
   Constraints on package "coffeescript":
   * coffeescript@=2.0.3_4 <- top level
   * coffeescript@1.0.4 <- tap:i18n 1.8.2 <- francocatena:status 1.5.3
   * coffeescript@1.0.2 <- nimble:restivus 0.8.12
   * coffeescript@1.0.4 <- rocketchat:oauth2-server 2.0.0 <- rocketchat:oauth2-server-config 1.0.0
   * coffeescript@1.0.5 <- konecty:delayed-task 1.0.0
   * coffeescript@1.0.2 <- konecty:mongo-counter 0.0.5_3
   * coffeescript@1.0.4 <- todda00:friendly-slugs 0.6.0
   
   Conflict: Constraint coffeescript@1.0.2 is not satisfied by coffeescript 2.0.3_4.
   Constraints on package "coffeescript":
   * coffeescript@=2.0.3_4 <- top level
   * coffeescript@1.0.4 <- tap:i18n 1.8.2 <- francocatena:status 1.5.3
   * coffeescript@1.0.2 <- nimble:restivus 0.8.12
   * coffeescript@1.0.4 <- rocketchat:oauth2-server 2.0.0 <- rocketchat:oauth2-server-config 1.0.0
   * coffeescript@1.0.5 <- konecty:delayed-task 1.0.0
   * coffeescript@1.0.2 <- konecty:mongo-counter 0.0.5_3
   * coffeescript@1.0.4 <- todda00:friendly-slugs 0.6.0
   
   Conflict: Constraint coffeescript@1.0.5 is not satisfied by coffeescript 2.0.3_4.
   Constraints on package "coffeescript":
   * coffeescript@=2.0.3_4 <- top level
   * coffeescript@1.0.4 <- tap:i18n 1.8.2 <- francocatena:status 1.5.3
   * coffeescript@1.0.2 <- nimble:restivus 0.8.12
   * coffeescript@1.0.4 <- rocketchat:oauth2-server 2.0.0 <- rocketchat:oauth2-server-config 1.0.0
   * coffeescript@1.0.5 <- konecty:delayed-task 1.0.0
   * coffeescript@1.0.2 <- konecty:mongo-counter 0.0.5_3
   * coffeescript@1.0.4 <- todda00:friendly-slugs 0.6.0
   
=> Your application has errors. Waiting for file change.
```

I know there are several ways to solve these conflicts, such as clone each packages and modify those contraints in package.js manually according to the [issue](https://github.com/meteor/meteor/issues/9609) and [announcement](https://blog.meteor.com/announcing-meteor-1-6-1-50aad71da4e6) of Meteor, but I still wonder if there is a common way to solve this issue among Rocket.Chat developers. I create this issue here because the default, clean and fresh installation of Meteor 1.6.1.1 doesn't work for Rocket.Chat while the Meteor version of Rocket.Chat has been bumped to 1.6.1.1 but some dependencies are incompatible.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2 - 0.65.0-develop (cloned from GitHub)
* Operating System: FreeBSD 11.1-STABLE (unrelated to this issue)
* Deployment Method(snap/docker/tar/etc): Meteor 1.6.1.1
* Number of Running Instances: 1
* DB Replicaset Oplog: N/A
* Node Version: 8.11.1
* mongoDB Version: 3.6.4

### Steps to Reproduce:

Here I describe the reproducing steps on Linux because it's a little complex on FreeBSD. The issue is platform-independent so do not worry about it.

1. git clone -b release-1.6.1.1 https://github.com/meteor/meteor.git
2. (cd meteor; scripts/build-node-for-dev-bundle.sh; scripts/generate-dev-bundle.sh; ./meteor --version)
3. export PATH=$HOME/meteor:$PATH
4. git clone https://github.com/RocketChat/Rocket.Chat.git
5. cd Rocket.Chat; meteor npm start

### Expected behavior:

The Rocket.Chat project is initialized properly and the server starts.

### Actual behavior:

Errors occured and the server didn't start.

**Comment by geekgonecrazy** [comment]
Cofeescript no longer used.  Closing

**Comment by novacrazy** [comment]
I'm still encountering this on fresh clones when using meteor from git, but it doesn't happen with the official meteor version.
