### ISSUE TITLE
Create additional iframe APIs to livechat

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#10866]
### Description:

It would be good to have additional APIs to communicate with livechat iframe.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: any
* DB Replicaset Oplog: any
* Node Version: any
* mongoDB Version: any

### Expected behavior:

I'm proposing the creation of the following additional functions:

- Set visitor token
- Set visitor name
- Set visitor email

This way an website using livechat can identify the visitor even before he have interacted with the page.

The functions should be available just like the [setDepartment](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/assets/rocket-livechat.js#L723) - [docs](https://rocket.chat/docs/developer-guides/livechat-api/#assign-chats-to-a-specific-department)

**Comment by hlehmann** [comment]
In case `setGuestToken` or `setGuestEmail` is use, it could be useful to let the visitor start/continue a conversation even when agents are offline.

A mail could be sent to the guest if the agent respond when the guest is offline.
