### ISSUE TITLE
Embedded Link Previews show your Rocketchat's domain in webserver logs

### ISSUE THREAD

**Issue by Fscape** [RocketChat/Rocket.Chat#10876]
### Description:
The URL/domain of a Rocketchat instance, including channels'/peoples' names is seen in webserver logs of the domain from which you are embedding URLs.

### Steps to Reproduce:
1. Set "Embed Link Previews" to True
2. Watch some other server's webserver logs
3. Post that webserver's URL (or a link to an image hosted on that webserver) in a room or channel
4. Your Rocketchat's full URL appears in the webserver's (e.g. Apache) logs 
    e.g. https://rocketchat.mydomain.com/channel/general

### Expected behavior:
Only the IP of your server should appear in the webserver logs.
Random sites shouldn't know of the existence of my RC instance, let alone peoples' names (Direct Message rooms) and Channel/ Private Group names, when I post a link to a gif or an article etc from them.

### Actual behavior:
https://rocketchat.mydomain.com/channel/general is shown instead of 123.123.123.123

### Relevant logs:
--

### Server Setup Information:
* Version of Rocket.Chat Server: 0.64.2
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.4
* mongoDB Version: v3.2.7

**Comment by JSzaszvari** [comment]
@Fscape 

You will need to post the relevant apache logs or a entry from them.

I'm unable to replicate this at all 

I've just run a test on both Apache and Nginx and in the web server logs I do not see this 

```
10.0.xx.xx - - [26/May/2018:19:42:17 +0000] "GET / HTTP/1.1" 200 1177 "-" "MozillaRC/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36"```

**Comment by himbeere** [comment]
Please see https://github.com/RocketChat/Rocket.Chat/issues/3860

**Comment by JSzaszvari** [comment]
Excellent.

Thanks, @himbeere - So we are talking about the referrer field. Makes much more sense now. 

@Sing-Li  - Should I close this one in favor/as a duplicate of #3860 , Or should I close #3860 and transfer any relevant details over to this one. Just not sure as that's quite old, but clearly still an issue that needs to be addressed at some point.

**Comment by JSzaszvari** [comment]
@rocket-cat label add enhancement

**Comment by vynmera** [comment]
Although the referer should definitely be hidden (it exposes the posted channel), it should be pointed out (as a friendly warning) that people may always reverse-DNS your IP, and find out your domain name from that.
For example, one could look up 123.123.123.123 and find "mycoolserver.com".
If you wish to hide that, I suggest you use CloudFlare - although I am not entirely sure how well Rocket.Chat works with it.

**Comment by Fscape** [comment]
My RC can't be found using reverse-DNS on its IP -- it's firewalled, behind a VPN, hidden from public.
...Which is why I was surprised when I saw it appearing in other servers' logs.
I'm just leaving "Embed Link Previews" as False -- not a big deal really.
Thanks, I appreciate the info, and you looking into it.

**Comment by Yvvw** [comment]
The [referrer-policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) could be used to globally modify referrer behavior.

Having this as a selectable option might be good, or it could simply be set at a reverse proxy running in front of rocketchat.

**Comment by marians** [comment]
Not only does it leak information via the referer, loading arbitrary 3rd party images into Rocket.Chat directly has these additional flaws:

- It makes Rocket.Chat users connect to servers they might not want to interat with, submitting tracking information and setting cookies.
- It opens up an attack surface for XSS attacks through manipulated images.

**Comment by svenseeberg** [comment]
It also allows tracking of the reading activity of users. That means it is possible to post a link and then count the hits on the linked resource to track how many users have read the channel message. And more importantly: when they read the message. As usually some details are known about users (OS, Browser), identifying them is possible.

So I guess there are strong reasons for implementing a proxy as detailed in #971

**Comment by marians** [comment]
@KevLehman My understanding of #21987 is that the Referrer-policy of the embedding page is changed to `strict-origin` via this meta tag:

```html
<meta name="referrer" content="strict-origin" />
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) this means:

> Send the origin (only) when the protocol security level stays the same (HTTPS→HTTPS). Don't send the Referer header to less secure destinations (HTTPS→HTTP).

So this only affects the `Referer` header of HTTP requests. Here, when fetching an image that is part of a URL preview, it simply means that this request to the third party server will be made without a `Referer` header, in case the URL starts with `http://` instead of `https://`.

Can you please explain how this fixes the issue with the problems described above?

**Comment by KevLehman** [comment]
@marians thanks for your comment on this one! In order to avoid defining a policy that may not be suitable for every RC user, referrer header will be defined through Admin settings (defaulting to `same-origin`).

That will allow you to be more or less strict depending on your use case, but the default value _should be_ safe for everyone in case you decide to not to change the setting.
