### ISSUE TITLE
How to query dates in the API

### ISSUE THREAD

**Issue by danielbressan** [RocketChat/Rocket.Chat#10871]
### Description:

How/Can you use the normal MongoDB query with date? I.e. is there a way I can query "get all users with updatedAt greater than X date"? Or get all messages from the past x day/s? 

I've tried various versions of this (which works in Mongo): 
`api/v1/users.list?query={"_updatedAt": {"$gte":  new ISODate("2018-05-24T20:10:48.093Z")}}`

I've confirmed that other non-date queries work great. I've also tried various versions without 'ISODate', but that just returns everything (as expected) because it's comparing a gte against a string. 

### Server Setup Information:
* Version of Rocket.Chat Server: 0.63.0

Thanks!
Daniel -

**Comment by rodrigok** [comment]
@danielbressan you should use the time in milliseconds since 1970

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

```
https://open.rocket.chat/api/v1/users.list?query={"_updatedAt": {"$gte": 1526847048093}}&fields={"_updatedAt":1}
```

**Comment by danielbressan** [comment]
@rodrigok Awesome, thanks! Work perfectly.

**Comment by vidoshsahu** [comment]
I am trying to get the groups using groups.listApp API which have been updated after a particular timestamp and it is not working for me. Can anyone please take a look here -
<mydomain>/api/v1/groups.listAll?query={"_updatedAt" : {"$gt" :1532026259728}}

Here are additional information - 
rocket chat version - 0.67.0
os: centos 7

thanks,
vidosh
