### ISSUE TITLE
Use of different emails for multiple domains under the same account, how can this be done?

### ISSUE THREAD

**Issue by suncal** [RocketChat/Rocket.Chat#10877]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): etc
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.11.1
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3.

**Comment by geekgonecrazy** [comment]
More of howto.  Please see forum in future for this type of thing
