### ISSUE TITLE
Raspbian read only file system and npm error message

### ISSUE THREAD

**Issue by Miracle916** [RocketChat/Rocket.Chat#10888]
I have an issue when trying to install npm package on a rocketchat snap package directory (somthing like that, I'm talking about the server bundle) but then an error appears an it says that tha packge.json is read only and the others dependencies are read only so I tried to change the permissions turning it to 755 as sudo but system says it's a read only file system so I can't change it even if I'm typing as sudo.

**Comment by JSzaszvari** [comment]
Hi @Miracle916 

Can you please log this issue using the issue template - https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md

The detailed information is needed in order to help troubleshoot your problem.

Apologies!

**Comment by JSzaszvari** [comment]
@rocket-cat close

**Comment by Miracle916** [comment]
pi@raspberrypi:/snap/rocketchat-server/1233/programs/server $ ~/meteor/dev_bundle/bin/npm install
npm WARN checkPermissions Missing write access to /snap/rocketchat-server/1233/programs/server/node_modules/source-map-support
npm WARN checkPermissions Missing write access to /snap/rocketchat-server/1233/programs/server/node_modules
meteor-dev-bundle@ /snap/rocketchat-server/1233/programs/server
└── source-map-support@0.3.2 

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/home/pi/meteor/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.2
npm ERR! npm  v3.9.6
npm ERR! path /snap/rocketchat-server/1233/programs/server/node_modules/source-map-support
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall access

npm ERR! rofs EROFS: read-only file system, access '/snap/rocketchat-server/1233/programs/server/node_modules/source-map-support'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/home/pi/meteor/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.2
npm ERR! npm  v3.9.6
npm ERR! path npm-debug.log.2363854686
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall open

npm ERR! rofs EROFS: read-only file system, open 'npm-debug.log.2363854686'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /snap/rocketchat-server/1233/programs/server/npm-debug.log

**Comment by Miracle916** [comment]
@JSzaszvari 
Server Setup Information:

Version of Rocket.Chat Server: rocketchat-server snap package
Operating System: Raspbian Stretch 4.14
Deployment Method(snap/docker/tar/etc): ~/meteor/dev_bundle/bin/npm install (dependencies)
Number of Running Instances: 1
DB Replicaset Oplog:
Node Version: 4.8.2
mongoDB Version: using mlab

Expected behavior: Install dependencies

Actual behavior:
pi@raspberrypi:/snap/rocketchat-server/1233/programs/server $ ~/meteor/dev_bundle/bin/npm install
npm WARN checkPermissions Missing write access to /snap/rocketchat-server/1233/programs/server/node_modules/source-map-support
npm WARN checkPermissions Missing write access to /snap/rocketchat-server/1233/programs/server/node_modules
meteor-dev-bundle@ /snap/rocketchat-server/1233/programs/server
└── source-map-support@0.3.2 

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/home/pi/meteor/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.2
npm ERR! npm  v3.9.6
npm ERR! path /snap/rocketchat-server/1233/programs/server/node_modules/source-map-support
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall access

npm ERR! rofs EROFS: read-only file system, access '/snap/rocketchat-server/1233/programs/server/node_modules/source-map-support'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/home/pi/meteor/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.2
npm ERR! npm  v3.9.6
npm ERR! path npm-debug.log.2363854686
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall open

npm ERR! rofs EROFS: read-only file system, open 'npm-debug.log.2363854686'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /snap/rocketchat-server/1233/programs/server/npm-debug.log

**Comment by Miracle916** [comment]
I have the 1.4.21 npm version
hello?

**Comment by Miracle916** [comment]
@JSzaszvari need help please
