### ISSUE TITLE
Feature Request: Support direct messages with multiple users.

### ISSUE THREAD

**Issue by tbtgspence** [RocketChat/Rocket.Chat#10881]
This would most likely just result in the auto-creation of a private room, but something to more easily support DM'ing multiple people similar to how Slack handles it would be very user-friendly.

**Comment by JSzaszvari** [comment]
@rocket-cat label add "Feature: Request"

**Comment by kaiiiiiiiii** [comment]
Duplicate of #4489, PR #9106

**Comment by JSzaszvari** [comment]
@rocket-cat close duplicate

**Comment by JSzaszvari** [comment]
@rocket-cat close
