### ISSUE TITLE
Moderator list for channel/group

### ISSUE THREAD

**Issue by rutmb** [RocketChat/Rocket.Chat#10898]
Hello,
Good day

### Description:

It would be good to have API requests for getting moderator list for the channel/group (like  requests /api/v1/channels.members and /api/v1/groups.members)

### Expected behavior:

- /api/v1/channels.moderators
- /api/v1/groups.moderators

**Comment by piotrkochan** [comment]
"groups.members" does not work for me as I expect it, because I can only look into groups that I'm already in. As admin or moderator I would like to see who is in the private group.
