### ISSUE TITLE
Incorrect url in button "GO TO MESSAGE"

### ISSUE THREAD

**Issue by VareliyK** [RocketChat/Rocket.Chat#10897]
### Description:
In version 0.64.2 button "GO TO MESSAGE" in the e-mail notifications has wrong url https://sitename/direct/    
instead 
https://sitename/direct/username or group name
In version 0.64.1 - OK. We checked 

### Server Setup Information:

* Version of Rocket.Chat Server: Release 0.64.2 (#10812)
* Operating System: Linux CentOS 7.4
* Deployment Method(snap/docker/tar/etc): docker (official rocketchat/rocket.chat)
* Number of Running Instances: 1
* DB Replicaset Oplog: n/a
* Node Version: v8.9.4
* mongoDB Version: 3.6.5

**Comment by JSzaszvari** [comment]
@rocket-cat label add "type: bug"

**Comment by JSzaszvari** [comment]
Just noticed this one my self. I managed to get it fixed, Will submit a pull request now.

**Comment by JSzaszvari** [comment]
@VareliyK I've submitted a Pull Request that fixes this -  https://github.com/RocketChat/Rocket.Chat/pull/10911

**Comment by damian-centrone** [comment]
this bug is no longer reproducible
