### ISSUE TITLE
Can't install dependencies read only file system

### ISSUE THREAD

**Issue by Miracle916** [RocketChat/Rocket.Chat#10890]
Server Setup Information:

Version of Rocket.Chat Server: rocketchat-server snap package
Operating System: Raspbian Stretch 4.14
Deployment Method(snap/docker/tar/etc): ~/meteor/dev_bundle/bin/npm install (dependencies)
Number of Running Instances: 1
DB Replicaset Oplog:
Node Version: 4.8.2
mongoDB Version: using mlab
npm: 1.4.21

Expected behavior: Install dependencies

Actual behavior:
pi@raspberrypi:/snap/rocketchat-server/1233/programs/server $ ~/meteor/dev_bundle/bin/npm install
npm WARN checkPermissions Missing write access to /snap/rocketchat-server/1233/programs/server/node_modules/source-map-support
npm WARN checkPermissions Missing write access to /snap/rocketchat-server/1233/programs/server/node_modules
meteor-dev-bundle@ /snap/rocketchat-server/1233/programs/server
└── source-map-support@0.3.2

npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/home/pi/meteor/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.2
npm ERR! npm v3.9.6
npm ERR! path /snap/rocketchat-server/1233/programs/server/node_modules/source-map-support
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall access

npm ERR! rofs EROFS: read-only file system, access '/snap/rocketchat-server/1233/programs/server/node_modules/source-map-support'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/home/pi/meteor/dev_bundle/bin/npm" "install"
npm ERR! node v4.8.2
npm ERR! npm v3.9.6
npm ERR! path npm-debug.log.2363854686
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall open

npm ERR! rofs EROFS: read-only file system, open 'npm-debug.log.2363854686'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR! /snap/rocketchat-server/1233/programs/server/npm-debug.log

**Comment by kaiiiiiiiii** [comment]
Why do you open another issue? #10888

And btw. you need at least node 8.9.x to run the latest rocket.chat release

**Comment by Miracle916** [comment]
because It's closed and what about the npm version?
So I just edit the file package.jason and change the node version or download the package from the page

**Comment by geekgonecrazy** [comment]
Your issue is highly conflicting...

You say snap and everything indicates snap... but you are trying to use meteor.

Meteor and our snap release do not go together.  Please choose one or the other.
