### ISSUE TITLE
Can´t enable E-Mail notifications for all messages

### ISSUE THREAD

**Issue by leetex1337** [RocketChat/Rocket.Chat#10906]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: Ubuntu 16.04.4 LTS‬
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.11.1
* mongoDB Version: 

### Steps to Reproduce:

1. Installing Desktop Client
2. Log in with Account
3. At the top right click on more, then on notification settings
4. Scroll to E-Mail, set notification to all messages, click on save
5. close the "more" window
6. At the top right click on more, then on notification settings
7. Scroll to E-Mail, notification is set to mentions

### Expected behavior:

Email Notifications are set to all messages

### Actual behavior:

Email Notifications are set to mentions only

Hello,

i just want to enable Email notifications for ALL messages. If the client is online, he should receive a mail. If the client is offline, he should receive an email too.

Sorry for my bad english ^^

Best regards, leetex

**Comment by sampaiodiego** [comment]
this was fixed on release 0.65.0 .. thx
