### ISSUE TITLE
Soundcloud embed support

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#1090]
Soundcloud links should unfurl into the soundcloud player
>https://soundcloud.com/yikyakapp/escapetoeverest-twofriends

should become
```html
<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/227201197&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
```

which results in a message looking something like
<img width="1017" alt="screenshot 2015-10-13 17 57 52" src="https://cloud.githubusercontent.com/assets/2439803/10472336/ffd6265e-71d3-11e5-8cd3-2512dc048423.png">

**Comment by marceloschmidt** [comment]
That sounds great! Could you propose a PR? If you need help, you can use rocketchat:spotify package as reference. Thank you!

**Comment by royalaid** [comment]
should I use the rocketchat namespace for the meteor package?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:6634)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZmSBq-003Xwo-84
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:58:23 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=tOR7ddcFE5hYQnmWhm92LElnke0=; b=iHDew+Y0cgOivi5C
	kfRFrEa/OViHG6jPOtndDuPxcUQPKF5nxsro/uaWaya9j54gz3yVfLAK3BWWF2Uc
	rvJac/gXMnzrGmzjcCUy6lDJqYvTgUKRYoxrb4YFPRhZqCTx9O0PY6t52CWFGsq7
	8XY9j5Qz/AKtVlMtYb5vMLinOw0=
Received: by filter0515p1mdw1.sendgrid.net with SMTP id filter0515p1mdw1.23049.561EB3DB5E
        2015-10-14 19:58:19.964889926 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id yF9GJEjJSlu-E2fcgLFU2A
	for <greg@biomassiv.es>; Wed, 14 Oct 2015 19:58:20.020 +0000 (UTC)
Date: Wed, 14 Oct 2015 12:58:19 -0700

**Comment by S4KH** [comment]
Any idea how to find/get the track/src url (https://api.soundcloud.com/tracks/227201197) from user entered https://soundcloud.com/yikyakapp/escapetoeverest-twofriends for iframe src attribute?

**Comment by S4KH** [comment]
I can't find the spotify's server code. In which file it sends request to the server to get the track URL?

**Comment by kakawait** [comment]
@S4KH Spotify integration is working with `RocketChat:Oembed` package that in charge to *sends request to server to get the track URL*. Thus on https://github.com/RocketChat/Rocket.Chat/blob/7cb836f33b79fddd787f621cb2a07e2f139abf3f/packages/rocketchat-spotify/client/oembedSpotifyWidget.html we are just using `meta` information from `Oembed` package

**Comment by kakawait** [comment]
Close to finish after PR #1161 I just have to support Oembed API to support group

**Comment by kakawait** [comment]
@engelgabriel but you could close this one
