### ISSUE TITLE
Unreasonably high idle CPU usage

### ISSUE THREAD

**Issue by leoluk** [RocketChat/Rocket.Chat#10900]
### Description:

Idle CPU usage of Rocket Chat in Google Chrome (latest stable release) is unreasonably high:

![screenshot from 2018-05-28 14-01-52](https://user-images.githubusercontent.com/859697/40613998-1acba588-6281-11e8-9448-a4e8d84c94d0.png)

Not to mention the 0.6G of RAM.

JS profiler snapshot:

![image](https://user-images.githubusercontent.com/859697/40614135-b5302194-6281-11e8-9a1e-16d0832b674c.png)

Timeline:

![image](https://user-images.githubusercontent.com/859697/40614235-4c385750-6282-11e8-8f0a-8fb40cead496.png)

Is this a common issue, or affecting our setup in particular? Happy to privately share the profiler output.

~100 users, with 10-20 active at once. No messages arrived while the profiler was running, with zero user interaction. I checked and it's not receiving anything at all from the websocket.

Can be reproduced by simply leaving Rocket Chat idling on any room.

Nothing at all logged in the console.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1 (at 54738c0)
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): custom, from Git
* Number of Running Instances: 1

**Comment by geekgonecrazy** [comment]
This seems to be related to the desktop app.  Please open an issue on: https://github.com/RocketChat/Rocket.Chat.Electron/issues or add to existing issue

**Comment by leoluk** [comment]
Please re-open, it's a browser issue, not Electron.

**Comment by geekgonecrazy** [comment]
This still an issue?  I’m not aware of it being an issue any more

**Comment by janesser** [comment]
@geekgonecrazy i would say yes, any input that would help investigation?

**Comment by tassoevan** [comment]
Just adding here that a cause was found and fixed recently in #12677.

**Comment by geekgonecrazy** [comment]
Awesome!  @janesser are you able to test 0.72.0?  Would be great to determine if same or if you have something additional

**Comment by catdad** [comment]
This is still happening today on the web app.

![image](https://user-images.githubusercontent.com/2205537/73364235-2e637480-4278-11ea-8937-2f24c7b757d9.png)

The rockerchat web app regularly freezes and I need to wait a minute or two before it reacts again. This happens when I try to switch rooms or to type a message after switching a room, and it happens consistently.

**Comment by damian-centrone** [comment]
This bug in no longer reproducible.
