### ISSUE TITLE
Feature "don't ask it again" for some actions

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat#10905]
- [x] Reset option on Profile settings
- [x] Button on action
- [x] Extendable for multiples settings (hide option first)

something like:
![image](https://user-images.githubusercontent.com/5263975/40616827-ba31fe0c-6262-11e8-8d90-a3927daaf620.png)

### Description:

Add the option to skip some modals

**Comment by vynmera** [comment]
Very good, I see myself tapping that "Yes, hide it!" far too often :-)
We should probably include the word "yes" in the new button, right now it might spark confusion on whether the button confirms or cancels the action (especially if we might have a dialog in the future that could save either option), so something like "Yes, and don't ask again".
Or maybe a checkbox could be used instead...
