### ISSUE TITLE
GCcollab Message Slack bridge | Pont pour Message GCcollab et Slack

### ISSUE THREAD

**Issue by GCDevExchange-CarrefourProgGC** [RocketChat/Rocket.Chat#10915]
Fixed Price: $1,000.00<br>Closing Date: Monday, June 4, 2018<h2>Opportunity Description</h2><p><span style="font-family: Times New Roman; font-size: medium;">Within our team, we have started using an open-source instant messaging platform called Rocket.Chat to enable easier communication between our coworkers. Rocket.Chat has the ability to connect with Slack via web APIs however the current functionality is limited to one instance of Slack connecting to one instance of Rocket.Chat. <br /><br /><span style="font-family: Times New Roman; font-size: medium;">Issues with the current bridge between Slack and Rocket.Chat has been registered on GitHub previously by our users: </span><a href="https://github.com/RocketChat/Rocket.Chat/issues/9339"><span style="color: #0563c1; font-family: Times New Roman; font-size: medium;">Here</span></a><span style="font-family: Times New Roman; font-size: medium;"> and </span><a href="https://github.com/RocketChat/Rocket.Chat/issues/9408"><span style="color: #0563c1; font-family: Times New Roman; font-size: medium;">here</span></a><span style="font-family: Times New Roman; font-size: medium;">.<br /><br /><span style="font-family: Times New Roman; font-size: medium;">We are interested in adding the ability for multiple Slack bridges to be enabled in our instance of Rocket.Chat.&nbsp;</span></span></span></p><h2>Acceptance Criteria</h2><p><span style="font-family: Times New Roman; font-size: medium;">-Users are able to create and use multiple bridges between Rocket.Chat and Slack with minimal difficulties or bugs after the completion of 5 unit tests.</span></p>
<p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;">Programmers will be paid upon successful completion of the 5 unit tests.</span></span></p><h2>How to Apply</h2><p>Go to the <a href="https://gcdevexchange-carrefourproggc.org/en/opportunities/opp-gccollab-message-slack-bridge-poss-pont-pour-message-gccollab-et-slack">Opportunity Page</a>, click the Apply button above and submit your proposal by 17:00 PST on Monday, June 4, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, June 6, 2018</b> with work to start on <b>Thursday, June 7, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p><span style="font-family: Times New Roman; font-size: medium;">1.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Confirmation that you are eligible to work in Canada</span></p>
<p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;">2.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Confirmation that you can complete the task within at least two weeks of receiving the contract.</span></span></p>
<p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;">3.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Ability to build bridges between instant messaging platforms. Please provide examples of the following. <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -Programming experience using Javascript and NodeJS.<br /><span style="font-family: Times New Roman; font-size: medium;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -Familiar with API integration.</span></span></span></span></p>
<p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;">Proposals will be judged on a pass/fail criteria, with accepted proposals entering a pool from which they will be selected using the random number generator on www.random.org. If you have any questions about the process contact Derek.Alton@tbs-sct.gc.ca.</span></span></span></span></span></p><br><hr><br>Prix fixe : 1 000,00 $<br>Date de clôture : le lundi 4 juin 2018<h2>Description de l'opportunité</h2><p><span lang="FR-CA"><span style="font-family: Times New Roman; font-size: medium;"><span lang="FR-CA">Au sein de notre &eacute;quipe, nous avons commenc&eacute; &agrave; utiliser une plateforme de messagerie instantan&eacute;e libre appel&eacute;e Rocket.Chat pour faciliter la communication entre coll&egrave;gues. Rocket.Chat permet de se connecter &agrave; Slack au moyen d&rsquo;interfaces de programmation Web. Toutefois, la fonctionnalit&eacute; actuelle se limite &agrave; la connexion d&rsquo;une s&eacute;ance de Slack &agrave; une s&eacute;ance de Rocket.Chat. <br /><br /><span lang="FR-CA">Les probl&egrave;mes li&eacute;s &agrave; la passerelle actuelle entre Slack et Rocket.Chat ont d&eacute;j&agrave; &eacute;t&eacute; soumis sur GitHub par nos utilisateurs&nbsp;: <a href="https://github.com/RocketChat/Rocket.Chat/issues/9339"><span style="color: #0563c1;">ici</span></a> et <a href="https://github.com/RocketChat/Rocket.Chat/issues/9408"><span style="color: #0563c1;">ici</span></a>.<br /><br /><span lang="FR-CA">Ce qui nous int&eacute;resse, c&rsquo;est d&rsquo;&ecirc;tre en mesure d&rsquo;ajouter diverses passerelles Slack afin de permettre la tenue de nos s&eacute;ances par l&rsquo;entremise de Rocket.Chat.</span></span></span></span></span></p><h2>Critères d'acceptation</h2><p><span lang="FR-CA"><span style="font-family: Times New Roman; font-size: medium;">-Les utilisateurs sont en mesure de cr&eacute;er et d&rsquo;utiliser plusieurs passerelles entre Rocket.Chat et Slack avec un minimum de difficult&eacute;s ou de bogues apr&egrave;s la r&eacute;alisation de cinq essais unitaires.</span></span></p>
<p style="margin: 0cm 0cm 8pt;"><span lang="FR-CA"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span lang="FR-CA"><span style="font-family: Times New Roman; font-size: medium;">Les programmeurs seront r&eacute;mun&eacute;r&eacute;s &agrave; la r&eacute;ussite des cinq essais unitaires.</span></span></span></span></span></p><h2>Comment présenter une proposition</h2><p>Accédez à <a href="https://gcdevexchange-carrefourproggc.org/fr/possibilites/opp-gccollab-message-slack-bridge-poss-pont-pour-message-gccollab-et-slack">la page de possibilité</a>, cliquez sur le bouton Appliquer ci-dessus et soumettez votre proposition avant 17:00 PST sur le lundi 4 juin 2018</b>.</p><p>Nous prévoyons d'attribuer cette opportunité par <b>le mercredi 6 juin 2018</b> avec le travail pour commencer <b>le jeudi 7 juin 2018</b>.</p><h2>Critères d'évaluation de la proposition</h2><p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="color: #000000;"><span lang="FR-CA">1.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Confirmation que vous &ecirc;tes admissible &agrave; travailler au Canada.</span></span></span></span></p>
<p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="color: #000000;"><span lang="FR-CA"><span lang="FR-CA">2.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Confirmation que vous pouvez accomplir la t&acirc;che dans les deux semaines suivant la r&eacute;ception du contrat.</span></span></span></span></span></p>
<p><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="color: #000000;"><span lang="FR-CA"><span lang="FR-CA"><span lang="FR-CA">3.<span style="mso-tab-count: 1;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Capacit&eacute; de cr&eacute;er des passerelles entre les plateformes de messagerie instantan&eacute;e. Veuillez donner des exemples de ce qui suit : <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Exp&eacute;rience de la programmation avec Javascript et NodeJS;<br /><span lang="FR-CA">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Connaissance de l&rsquo;int&eacute;gration de l&rsquo;interface de programmation d&rsquo;applications.<br /><br /><span lang="FR-CA">Les propositions seront &eacute;valu&eacute;es en fonction de crit&egrave;res de r&eacute;ussite ou d&rsquo;&eacute;chec, et les propositions accept&eacute;es seront inscrites dans un bassin &agrave; partir duquel elles seront s&eacute;lectionn&eacute;es &agrave; l&rsquo;aide du g&eacute;n&eacute;rateur de nombres al&eacute;atoires sur le site www.random.org. Si vous avez des questions au sujet du processus, communiquez avec Derek.Alton@tbs-sct.gc.ca.<span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="color: #000000;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;"><span style="font-family: Times New Roman; font-size: medium;">&nbsp;</span></span></span></span></span></span></span></span></span></span></span></span></span></span></span></p>

**Comment by ToferC** [comment]
Hi all. Just a note that we pulled this opportunity down to get the scoping and compensation right. Also looks like this should have been in issue #6878. 

I've asked for an update on that issue and see what room/need there is to help out.

**Comment by graywolf336** [comment]
@ToferC Feel free to do it, as I do not believe anyone internally is working on the Slack bridge.

**Comment by Hudell** [comment]
I recommend working on top of PR #10205 for any slack bridge changes, as it improved the code organization and is planned to be merged before the next release.

**Comment by ToferC** [comment]
Thanks @Hudell - just figuring out our procurement rules (yay government) and then we'll re-post. It would be great to get an idea of scope of work. Being blunt, I'd like to put the bounty on this work, but our devs have just started to dig into the code.

**Comment by Hudell** [comment]
Once that PR is merged, it might just be a matter of creating two instances of the SlackAdapter. I'll run a test here to check if it would handle two slack bridges properly, in which case the only development needed would be an interface to configure multiple slack servers.

The other issue looks like a simple UI bug, I'll get it fixed as well.

**Comment by Hudell** [comment]
I'll continue the discussion about the multiple slack bridges on the issue ( #9339 )

**Comment by Hudell** [comment]
@ToferC Is there anything we can do to help your devs as well? I believe the change for the multiple slackbridge configurations will take less than a day for someone who's familiar with the code, so I might just go ahead and implement it.

**Comment by Hudell** [comment]
This feature was included on Rocket.Chat 1.0.0
