### ISSUE TITLE
Voice messages are not working on windows

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#10912]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.0
* Operating System: Windows
* Deployment Method(snap/docker/tar/etc): all
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 
* mongoDB Version:

**Comment by yZhenyuanLiu** [comment]
Me too

**Comment by geekgonecrazy** [comment]
This was completely rewrote right?  Going to go ahead and close as should no longer be valid
