### ISSUE TITLE
redirect to #general instead of home

### ISSUE THREAD

**Issue by imabee101** [RocketChat/Rocket.Chat#10924]
I want to have the option for the user to default to #general instead of going to the home page home. I cannot find a simple way to do this. I'm trying to get the best way of embedding this into a wordpress div or iframe but it doesn't seem friendly for that. Please advise.

**Comment by vynmera** [comment]
This should definitely be optional (maybe in admin settings) as some people use Home for rules and other important info.

**Comment by imabee101** [comment]
I can't find the setting.

**Comment by mghicas** [comment]
Setting is under General - First Channel After Login
Set to the room name
