### ISSUE TITLE
Rooms and users disappear after mark channel as Favorite or Unfavorite

### ISSUE THREAD

**Issue by VareliyK** [RocketChat/Rocket.Chat#10927]
### Description:

Rooms and users disappear from left panel after mark channel as Favorite or Unfavorite

### Server Setup Information:

Version of Rocket.Chat Server: Release 0.64.2 (#10812)
Operating System: Linux CentOS 7.4
Deployment Method(snap/docker/tar/etc): docker (official rocketchat/rocket.chat)
Number of Running Instances: 1
DB Replicaset Oplog: n/a
Node Version: v8.9.4
mongoDB Version: 3.6.5

### Steps to Reproduce:
I attached video

This bug occurs with version 0.64.1 and 0.64.2, but 0.63.3 - ok

[bug_favorite_20180529.mov.zip](https://github.com/RocketChat/Rocket.Chat/files/2047749/bug_favorite_20180529.mov.zip)

**Comment by VareliyK** [comment]
This bug appears only fresh install version 0.64.1, 0.64.2, 0.65.1 and with options sort by Alphabetical, Group by Type, Group by favorites

**Comment by hexcsl** [comment]
In version 0.65.1, the problem is repeated 🤕

**Comment by ggazzo** [comment]
@hexcsl could you try on develop? or wait for 0.66.0 and let me know if it was fixed (:

**Comment by hexcsl** [comment]
@ggazzo I checked the docker image of rocketchat/rocket.chat:develop (0.66.0-develop) and it does not have this problem 👍 . We will wait for the release of 0.66 for the production.

**Comment by ggazzo** [comment]
thanks @hexcsl, just few days ;)
