### ISSUE TITLE
remove members from private group

### ISSUE THREAD

**Issue by sunnipaul** [RocketChat/Rocket.Chat#1093]
Hope this feature be added soon

**Comment by liamdawson** [comment]
I'd have a few questions about how this could be implemented:

1. Where in the UI does this fit? Or should it just be a slash command?
2. Should this be available in public channels too? How do the permissions work? I don't think we have a concept of privileged users in channels of any kind, so even if it's just private groups, anyone can kick anyone. Limiting it to just admin users might not be suitable still.
3. Should kicking restrict the ability for someone to be invited back in?

**Comment by sunnipaul** [comment]
I think just the opposite actions to  addUserToRoom is fine.
In many cases, there are admins/coordinators in room who can kick off  members. Slash command plus UI is more fit

**Comment by IQ2022** [comment]
Also this will help in issues open requesting Premium Chat rooms, i.e enable users join when they are signed up for that room specific room (membership)

**Comment by klatys** [comment]
I think this has already been fixed [kicking from private rooms](http://recordit.co/ETJltA8hyE.gif)

**Comment by geekgonecrazy** [comment]
👍  for sure seems fixed. Thanks @klatys
