### ISSUE TITLE
channel.create - unable to set channel to default?

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat#10939]
Using the Rest API I have been able to create new channels, set as readOnly, etc....  but it does not seem possible to set the room as a default room.   Is it possible to add that functionality?

Thank you.

**Comment by vynmera** [comment]
Seems an easy addition, on it...

**Comment by ear-dev** [comment]
@vynmera Awesome!  I also notice that it is not possible yet to create a broadcast channel.  Should I make a new issue for that or do you think we can roll that into this one?  Thanks!
