### ISSUE TITLE
Ban users

### ISSUE THREAD

**Issue by imabee101** [RocketChat/Rocket.Chat#10932]
What command is there to ban a user? Kicking will not be enough.

**Comment by Lawri-van-Buel** [comment]
Admin's can deactivate a user or block a user. It's part of the Admin ui ==> Users.

**Comment by naiaokami** [comment]
> Admin's can deactivate a user or block a user. It's part of the Admin ui ==> Users.
We need a ban for channel owners to use against users.

**Comment by reetp** [comment]
@rocket-cat close

One of several similar requests that can go under NFR 

https://github.com/RocketChat/feature-requests/issues/25

Please follow up there.

A possibility of some work maybe on a ToDo here:
https://github.com/RocketChat/Rocket.Chat/issues/10963
