### ISSUE TITLE
All public channels are not displayed in the directory with Firefox

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#10943]
### Description:

Parsing the directory with Firefox (52.2.0 and 60.0.1) only displays 6 channels and no scroll bar :
![capture d ecran - 30052018 - 10 33 26](https://user-images.githubusercontent.com/6803105/40709830-5a3927aa-63f7-11e8-9727-4a5bdd1aa2eb.png)

No problem with Chrome (66.0.3359.181) :
![capture d ecran - 30052018 - 10 31 35](https://user-images.githubusercontent.com/6803105/40709884-866a268a-63f7-11e8-8c69-2670ae03f89f.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.0
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 4
* DB Replicaset Oplog: true
* Node Version: 8.9.4
* mongoDB Version: 3.2.12

### Steps to Reproduce:

1. With Firefox display the directory
2. With Chrome display the directory
3. Compare

### Expected behavior:

Display all public channels with Firefox

### Actual behavior:

Only 6 channels are displayed with FF while they're all listed looking at the code with firebug

Cheers

**Comment by dhoeld** [comment]
Same behaviour also for users in the directory.

**Comment by Gummikavalier** [comment]
It should have already been fixed but is not...

Also mentioned in here: 
#9951
#10024

Workaround with Custom CSS is:

```
section.rc-directory {
	height: 99%;
}
```

**Comment by magicbelette** [comment]
Great :+1: 
Thx
