### ISSUE TITLE
Slack webhook compatibility broken

### ISSUE THREAD

**Issue by felipejfc** [RocketChat/Rocket.Chat#10942]
Hi, 

This commit https://github.com/RocketChat/Rocket.Chat/commit/01d2aead1d9e61bb6752bde3e4728c677e41e38b#diff-b18deaa461a67499aa1867414e83204eL13 from @rodrigok has broken compatibility with slack api of webhooks, the problem is with the line highlighted, slack webhooks expect int in this "ts" field inside attachments.

Can we change it to be an int? Or maybe change back to Match.Maybe?

Our issue is that we've been using grafana's alerting slack integration to send alarms to rocketchat, it was working wondenful before upgrading RC to 0.65 :/

Thanks

**Comment by MarcosSpessatto** [comment]
This was corrected in https://github.com/RocketChat/Rocket.Chat/pull/11021.
