### ISSUE TITLE
Rest API - support setting of permissions

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat#10946]
In the admin pannel on the RC server at `admin/permissions` it is possible to set permissions for various user types.  It would be great if the API supported that.  (I apologize if it already does, I have just not yet been able to figure out how that would work.)  Thanks!

**Comment by kaiiiiiiiii** [comment]
Duplicate of #7961

**Comment by MarcosSpessatto** [comment]
Closing this issue in favor of #7961.
