### ISSUE TITLE
Get the development version running.

### ISSUE THREAD

**Issue by AntouanK** [RocketChat/Rocket.Chat#1094]
Got the source code yesterday, and I wanted to start modifying the code. But getting the development version to run is pretty confusing.

In the README is says:
```
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
docker run -it -p 3000:3000 -v "$(pwd)":/app danieldent/meteor
```

If I do run this though, that meteor process gets stuck because it cannot find mongo ( which makes sense, there is no container running mongo, right )
I haven't use meteor before, so I have no idea how it runs.
( specifically it gets stuck to the LDAP package for some reason )

The simplest thing I can think of, is running another container with mongo, and then linking it to the one you have a command for. Like you have the `docker-compose` file for deploying it.

If I do want to link a mongo container, should I use a specific name as a host, or expose some environment variable to connect it?

On a separate note, what if I want to use RethinkDB as a database. Is that an option?

**Comment by AntouanK** [comment]
I did try to get a separate `mongo` container linked, but again the same situation, gets stuck on LDAP.

Even trying 
```
docker run -t --link mongo:mongodb -p 3000:3000 -v "$(pwd)":/app -e MONGO_URL=mongodb://mongodb/rocketchat danieldent/meteor meteor list
```
gets stuck on this line
```
rocketchat:ldap: updating npm dependencies -- ldapjs...
```

Can I somehow remove or disable ldap? It seems to be blocking the whole thing.

**Comment by kernicPanel** [comment]
Maybe I'm too naive, but why not using the meteor command ?

**Comment by AntouanK** [comment]
I'm using docker containers.
The image you have in the README ( [`danieldent/meteor`](https://github.com/DanielDent/docker-meteor/blob/master/latest/Dockerfile) ) runs "meteor" anyway, so it should be the same, right?

**Comment by kernicPanel** [comment]
Yes, but it uses https://github.com/OnModulus/demeteorizer
https://github.com/DanielDent/docker-meteor/blob/master/latest/Dockerfile#L23

It seems that you have to run mongo by yourself https://github.com/OnModulus/demeteorizer#running-resulting-application

I don't use docker for development, only meteor command, and docker-compose for production.

**Comment by AntouanK** [comment]
Ok. ( that comment you just made, should be obvious in the main README )

But still, like I said earlier, even if I run mongo, and link it and set up the env variable, it still gets stuck on ldap installation.
So what's wrong there?

**Comment by gmsecrieru** [comment]
I remember running into a very similar situation when running on `danieldente/meteor`, and I believe this is related to the fact that we are running Meteor 1.2.0.2 for RocketChat but the referred image has another version. 

Not sure if that's the problem but could be related.

**Comment by AntouanK** [comment]
@gmsecrieru Any way for me to test that? How do I specify versions? ( I haven't use meteor before, and I don't really get how it works. it's like a big black box )

**Comment by gmsecrieru** [comment]
@AntouanK What you are trying to achieve requires some Docker-related knowledge and setup, and that goes a little beyond RocketChat itself, even though I highly suggest you join us at the [Demo server](https://demo.rocket.chat) as there are plenty of Docker-experts who can help you. 

Have you tried following [other methods](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker)? I run my development environment on top of OS/X and MongoDB, for instance.

**Comment by AntouanK** [comment]
@gmsecrieru I used docker a lot in my last projects, so I'm happy to help.

If all you do is run `meteor`, then obviously I have to know what meteor does, and pinpoint the problem that is container-related.
And like I said, I have no idea how meteor works, and where to start from. 
( I tried the meteor docs, but there is a "hello-world" app, and you have a monster app, so it's not really helpful )

Can you give me a rundown of how meteor in your app works?

**Comment by geekgonecrazy** [comment]
Yeah I think our upgrade to the newer version of meteor has messed up the usage of that image.

We may need to find another one or build an image.  Which shouldn't be hard.

@AntouanK so when you run `meteor` it runs the meteor process, which starts mongodb and then does a build of the app.  It also watches the app and when a change is made it rebuilds.

It would be a very simple image to write.

**Comment by AntouanK** [comment]
@geekgonecrazy 
Ok, so I made a debian VM, got the meteor script file, installed it and then cloned the repo and run 'meteor' in the directory.
Seems to be working fine.

The easiest way would be to make a docker image based on debian, and just do those steps.
But I think it's sensible to separate the db, just like you do in the docker-compose file.
So it can be managed better, and separate concerns on the containers or scale them.

So when I run `meteor` I see this line immediately:
```
=> Started MongoDB.
```
How can I specify that I want to use a mongoDB instance running somewhere else? So I can provide host/port/auth config and use that.

**Comment by geekgonecrazy** [comment]
@AntouanK you have to remember though.  This is for development.  Not for running in production.  So running via meteor is simplest via meteor.  If you do want to use your own you can use the environment variable `MONGO_URL=mongodb://host:/db`

**Comment by AntouanK** [comment]
I see.

Containers are as much convenient as anything else I think, to work on development.
If anything, they are more portable since you only have one dependency, docker.
For example, the laptop I'm using, I don't want to install meteor or MongoDB. I have docker already, it's easier to just launch a couple of containers.

I'll prepare a dockerfile and a script to show you how easy it can be.

Can you tell me, from the root directory of the repo, which files/directories are needed from meteor?
So I won't copy everything in the image...
( by the way, which file is used for configuring meteor? like `package.json` for node for example )

**Comment by geekgonecrazy** [comment]
in the repo .meteor/packages is I think pretty much the most important.

So all you should have to do is map a volume in the container to your local folder and just running meteor in that folder inside the container should be all you need to do.

**Comment by AntouanK** [comment]
@geekgonecrazy I still have a problem getting past the "ldap" step
Terminal always gets stuck at
```
=> Started proxy.
rocketchat:ldap: updating npm dependencies -- ldapjs...
   Building package rocketchat:ldap          /
```

Any idea why? Is there maybe a dependency missing for ldap or something?

**Comment by gmsecrieru** [comment]
@AntouanK Can you try building an running [this](https://gist.github.com/gmsecrieru/528e83e4ee4f35d7e902) instead of `danieldent/meteor`?

**Comment by marceloschmidt** [comment]
@AntouanK can you comment rocketchat-ldap on your .meteor/packages file and try running it again?

**Comment by marceloschmidt** [comment]
danieldent/meteor image is using latest meteor version. this works now.
