### ISSUE TITLE
Top right icons for adding new users disappears

### ISSUE THREAD

**Issue by GezimSejdiu** [RocketChat/Rocket.Chat#10951]
### Description:
When you go to the Users form, the icons on the top right disappears and you are not able to add a new user. I found one workaround by searching for my user and then after you click on the user the icons appear and will allow you to add new users.
### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.0
* Operating System:  Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled

### Steps to Reproduce:

Please, have a look at the figures below for the exact behavior : 
### Actual behavior:
![image](https://user-images.githubusercontent.com/5259296/40725453-c5c6ff66-6423-11e8-8666-e2fda85978f4.png)

After you click on the specific user the icons appears : 
![image](https://user-images.githubusercontent.com/5259296/40725474-d42cfb32-6423-11e8-88ce-acf95746d706.png)

Best regards,

**Comment by h4wkmoon** [comment]
This goes for the custom emojis screen as well.

**Comment by h4wkmoon** [comment]
same with 0.65.1 
But snaps seems to ok.

As the issue appears to be specific to Docker, I guess it's related to the docker image build process. maybe.

**Comment by ura14h** [comment]
custom_sound and custom_emoji are the same situation too. There may be others.
I seem that right side toolbars is empty when list isn't selected.
I am running version 0.65.1 without Docker.

**Comment by maxdwit** [comment]
@h4wkmoon I use snap 0.65.1 and also don't have an add Button for:
- Emoji 
- Sound
- User 
Last one seems to be important ;)

**Comment by tctovsli** [comment]
I had this issue with 0.65.0 too, built from source (not from pre-built docker image).

**Comment by h4wkmoon** [comment]
Yep, same bug.
Unfortunately, I have no custom emoji to click on yet. But, It does work for users.

**Comment by wagesj45** [comment]
@h4wkmoon I am running a snap 0.65.1 and am also having the bug, so they seem to be affected as well.

**Comment by Episodio1** [comment]
Same here with 0.65.1
Workaround works.

However after creating new users, they show up in the user list with ~~striked text~~ (like that)

And when those new  users try to connect it says "user not found or invalid password".

If we change password it says "update succesful", but user still cannot login.

Rocketchat logs and mongodb logs shows no error at all.

(Ubuntu snap installation)

**Comment by graywolf336** [comment]
Also it has disappeared on the adding a new emoji page.

**Comment by wagesj45** [comment]
@Episodio1 That sounds like it might be a separate bug, as far as the inability to add new users successfully goes.

**Comment by johnallenmoore** [comment]
Same issue with missing icons (non-docker build).  We run 3 instances of Rocket.Chat with 3 Replica Set Members in MongoDB. All manually installed.   I did find that clicking an existing user will give you the icons like the original poster shows.  Since I do not run my instances in Docker or use Snaps, I don't think this is specific to Docker/Snaps at all.

Secondarily, we have the username/password incorrect with all LDAP users.  No errors generated.  We are testing this in a DEV environment currently.

Version 0.65.1

**Comment by Episodio1** [comment]
@wagesj45 It might be, but I  wanted to say that before opening a new issue. It seems someone else is suffering the same behaviour("johnallenmoore").

**Comment by geekgonecrazy** [comment]
Ah so this is why the + was missing to add a new custom sound and custom emoji!  Looks like its every page there in admin that involves adding something from the sidebar

@ggazzo @karlprieb you guys aware of this?

**Comment by ggazzo** [comment]
fixed ;)
