### ISSUE TITLE
uploading file progress stuck and cancel button not work any more 

### ISSUE THREAD

**Issue by alirezaimi** [RocketChat/Rocket.Chat#10960]
Thank you for support(https://github.com/RocketChat/Rocket.Chat/issues/10709),
In this bug report i did announce two different problem in one specific section of rocketchat, file uploading .
1- cancel button problem that stuck and not work
2- file uploading problem that some files uploaded successfully and some files not ! this part of log related to it :
May 09 11:24:22 sp2lnx1chat rocketchat-server.rocketchat-server[663]: Error: FileNotFound: no file with id PBAeR9khNYYPYhMtx found

I upgrade rocketchat to 0.65.1 and none of these problems is solved !
even i installed latest version to new server with multi instance and this problem still exist . :(

**Comment by geekgonecrazy** [comment]
Should be resolved now.  Lot has changed since this version
