### ISSUE TITLE
Show @ when using Real Names

### ISSUE THREAD

**Issue by spaasis** [RocketChat/Rocket.Chat#10968]
### Description:

I think it would be better and more consistent to show the @ when mentioning people even when real names are used

### Server Setup Information:

* Version of Rocket.Chat Server:  0.65.1

### Steps to Reproduce:

1. Enable Real Names
2. Mention someone using @

### Expected behavior:

I would expect a similar behaviour than when Real Names are disabled, like
`@user.name` -> `@Real Name`

### Actual behavior:
The mention is set as just `Real Name`, which is confusing in many cases in the middle of messages

**Comment by vynmera** [comment]
One thing I did on my own server was add a background color to mentions (that aren't to you or all/here), so they look more like mentions.

**Comment by simopaasisalo** [comment]
@vynmera seems like a nice trick, mind posting the css? However I think that adding the consistent behaviour would be a better solution on the whole

**Comment by graywolf336** [comment]
I agree and there has been some discussion regarding this in the past, even a pull request if I'm not mistaken. #8041

**Comment by vynmera** [comment]
@simopaasisalo It's this code (sadly with hard-coded color):
```
.message .mention-link:not(.mention-link-me):not(.mention-link-all) {
  background-color: rgba(29, 116, 245, 0.2);
  padding: 0 4px 2px;
}
```

It looks like this:
![2018-06-01_20-56-45](https://user-images.githubusercontent.com/39674991/40858381-6e63d552-65de-11e8-9598-59dd6ce175cc.png)

**Comment by engelgabriel** [comment]
closing this as we have decided to also remove "@" from "regular" mentions.
