### ISSUE TITLE
[BUG] Cannot uninstall App in multi instance environment

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat#10967]
@graywolf336 

### Description:

I've tried to uninstall my AppearCommandApp from our production environment, but it looks like it only happened for one instance. Every 4th reload I see that the app is uninstalled, but all the other times it's still visible. When I try to uninstall it a second time nothing happens at all (except being send to the top of the page).

Am I missing something?

![uninstall_app](https://user-images.githubusercontent.com/4711233/40840416-e0ad8da2-65a6-11e8-9101-06904f1646a2.gif)
![uninstall_app_2](https://user-images.githubusercontent.com/4711233/40840421-e4679b72-65a6-11e8-8d35-df98873beb70.gif)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: Ubuntu 16.04.*
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 4
* DB Replicaset Oplog: yes
* Node Version: 8.9.4
* mongoDB Version: 3.6

### Steps to Reproduce:

1. Uninstall app
2. Reload app management screen a couple of times
3. Try to uninstall app a second time

### Expected behavior:

App should be "uninstalled" on all instances.

### Actual behavior:

It's not

### Relevant logs:

Nothing relevant, just one time a "Uninstalling: 6d134d6e-9d32-4495-9f44-2ef6b4db48a9".

### AppearCommandApp
[appearin-command_1.2.0.zip](https://github.com/RocketChat/Rocket.Chat/files/2062639/appearin-command_1.2.0.zip)

**Comment by graywolf336** [comment]
Yes, multi-instance needs a lot of work due to the instability of the server-to-server communication framework used inside of Rocket.Chat.
