### ISSUE TITLE
Unable to get the file list using REST API in some cases.

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat#10969]
### Description:

When using our REST API to get the file list from a channel, sometimes the following message is show: 
**Cannot destructure property `username` of 'undefined' or 'null'**

Note that in fact a bad request (400) is thrown and the API comes with the following result:
`{"success":false,"error":"Cannot destructure property `username` of 'undefined' or 'null'."}`

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1 (open.rocket.chat)

### Steps to Reproduce:

1. Using our REST API try to fetch the file list from the General room for example;
2. The above error message is show.

### Expected behavior:

Get the file list successful.

### Actual behavior:

Unable to get the file list due to above error.

**Comment by rafaelks** [comment]
@MarcosSpessatto I just noticed that this is happening because some data is corrupted. If we limit the amount of results to `20` for example, it'll return just fine.

Also, let's add this to a hotfix release please.
