### ISSUE TITLE
Setting Up RocketChat on local device

### ISSUE THREAD

**Issue by miPlodder** [RocketChat/Rocket.Chat#10964]
I want to set up RocketChat on my device (Fedora VMware). But when I run the command `meteor npm start` after as mentioned in the docs. It's shows some warning. 

![screenshot 171](https://user-images.githubusercontent.com/22195621/40804502-1c996796-6539-11e8-982b-c71490c73984.png)
![screenshot 172](https://user-images.githubusercontent.com/22195621/40804504-1cdb4990-6539-11e8-9a0d-e6ab584193a1.png)

Loading continues but nothing happens. Do I have to wait more for more time ?

**Comment by vynmera** [comment]
How long has it been going? The initial build may take a **very** long time depending on your system.

**Comment by geekgonecrazy** [comment]
Are you looking to develop or just run it?  If you want to run it please follow our docs: https://rocket.chat/docs in the installation section.

As to meteors slowness running in a VM i've often noticed its much slower.  Usually virtual disk speed is too slow

**Comment by miPlodder** [comment]
`SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

What does this means ?

**Comment by vynmera** [comment]
@miPlodder I get that too, and my Rocket.Chat builds fine. I believe it's simply an API for OS X, and isn't needed for any other platforms.

**Comment by miPlodder** [comment]
Apart from Node and Meteor, what else should be installed in my machine ? (I have not worked with web dev much)

**Comment by miPlodder** [comment]
@vynmera  @geekgonecrazy What the rough estimate of time taken ? (10 minutes or more)

**Comment by miPlodder** [comment]
@vynmera @geekgonecrazy Can you take a look at the log file and help accordingly. 
(https://notepad.pw/miplodder)

**Comment by vynmera** [comment]
@miPlodder I'm not too sure, but can you try manually installing phantomjs like this? `meteor npm install phantomjs-prebuilt`

**Comment by geekgonecrazy** [comment]
> @vynmera @geekgonecrazy What's the rough estimate of time taken ?

As mentioned before.  It depends on the hardware.  In your case as mentioned earlier... Things take much longer on virtualized hardware.  

As suggested above installing the troublesome package by it's self often helps
