### ISSUE TITLE
Sending message from Ansible - the Slack way?

### ISSUE THREAD

**Issue by mlazarov** [RocketChat/Rocket.Chat#1097]
Hi,
I'm curios is it possible to send chat message from ansible to rocket chat like in slack?

Here is the Ansible docs about this:
http://docs.ansible.com/ansible/slack_module.html

Martin

**Comment by ninja-** [comment]
not yet. we are aiming for implementing the same REST API as Slack does, but that isn't yet ready

**Comment by Corwin7** [comment]
If I migrate from Slack to RocketChat (I'm still evaluating / attempting to get it to work) I will need the ability to post to it from Bash & Ansible like I do with Slack. Any rough idea on the time frame?

**Comment by geekgonecrazy** [comment]
@mlazarov actually it works now for posting messages.  

https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs

Its not up to a comparable place with slack.  We have a few things to wrap up this week and next.  I hope to be able to start on this end of next week. Maybe someone will beat me to starting on it :)

**Comment by mlazarov** [comment]
Actually it's much harder to use this form of rest API because it requires a few more requests (instead one) and this makes it not in place replacement of Slack :)

If Rocket follows the same api interface it will be easy just to put rocket rest api url in all apps that already have slack integration.

For example calling the Slack api is easy as:

curl -s -X POST --data-urlencode 'payload={"channel": "#servers", "username": "Production '$1'", "text": "Some important stuff here"}' https://hooks.slack.com/services/[api-key]

Martin

**Comment by graywolf336** [comment]
To those follow this thread, I believe with the webhook additions this can now be closed? Or am I speaking out of my head?

**Comment by geekgonecrazy** [comment]
Yup you're right.

@mlazarov you can now set up a webhook in the settings.  Then just pop that url in the spot of the slack url in that module and it should work with no modifications.  :smile:

**Comment by Deepakkothandan** [comment]
Did anyone get this to work, from ansible using the slack module ?

**Comment by geekgonecrazy** [comment]
@Deepakkothandan I believe based on the documentation that you'll pretty much need to fork the slack module.  From what I can tell the slack module takes just the token not the full URL. 

So either need to modify the slack module to take either the token or the full url.  Or fork it and change the base url and then use rocket.chat token.

**Comment by Deepakkothandan** [comment]
@geekgonecrazy Thank you for your suggestions, I was thinking about the same, as it was not possible to send notifications using the slack module, because of the above reasons you mentioned. I am trying with the ansible uri module to post messages but no success as of now, guess rocket chat needs its own module.

**Comment by geekgonecrazy** [comment]
@Deepakkothandan let us know if you fork and give this a shot.  I know we don't currently use ansible for our deployments, but I can see where in the future we might.  So i'd be glad to assist where I can in your efforts 👍

**Comment by Deepakkothandan** [comment]
@geekgonecrazy Thank you. Created a module based off the slack module and I was able to send messages to Rocket chat, it required only minor changes. I have a query about incoming hook url. As far as I understand the format is https://domainname/hooks/token . Is this always true ? Also where could I find more info about the payload that the incoming webhook can accept(script disabled). Would be helpful if you can point me in the right direction.

**Comment by Deepakkothandan** [comment]
@geekgonecrazy I have created a pull request to Ansible for the module, the link to the pull request is [https://github.com/ansible/ansible-modules-extras/pull/2222](url) Please take a look at the PR when you fine me and let me know if some changes are required

**Comment by geekgonecrazy** [comment]
@Deepakkothandan our webhook is 100% slack compatible to my knowledge.  

@RocketChat/core anyone else able to help me take a look at this Rocket.Chat module?  From what I can see this looks good and should be compatible.

**Comment by geekgonecrazy** [comment]
Going to go ahead and re-open this while we help you get that merged 👍

**Comment by Deepakkothandan** [comment]
@geekgonecrazy Thank you. I have updated the PR to include the protocol to specified

**Comment by Deepakkothandan** [comment]
@geekgonecrazy I have added a check to the module for checking the token validity. If the token does not contain any '/' as part of it, then the module fails with invalid token. The reason is if there was no '/' in token then I was getting a 200 as response.

**Comment by geekgonecrazy** [comment]
@Deepakkothandan awesome!  Any suggestions on how to best try it out?  I was looking and looks like there are some pretty complicated suggested steps for trying modules.  

I'm an ansible noob. :grin:

Maybe our ansible expert: @cmacrae can take a look too?

**Comment by Deepakkothandan** [comment]
@geekgonecrazy The easier way of doing it is, place the rocketchat.py from the PR in to the same location  as slack.py in your ansible installation and use it just as any other module in your play.

The second way, will be to configure ansible for a secondary library search path and then place the rocketchat.py file in that directory.

**Comment by Deepakkothandan** [comment]
@geekgonecrazy I believe this issue can be closed, as the ansible module is merged

**Comment by huiminzeng** [comment]
hello @Deepakkothandan ! I was trying to send message with ansible uri_module. Ist that possible? Thx!
