### ISSUE TITLE
Please Update the api user.info

### ISSUE THREAD

**Issue by Maqsyo** [RocketChat/Rocket.Chat#10984]
It would be really great to get the count of the overall unread mesages and to get these of a specific user.
Currently i have to iterate overall channels of the user and have to count all unread messages of the user.

This would be really great!

**Comment by geekgonecrazy** [comment]
You can turn on metrics endpoint and actually see this information and much more information

**Comment by Maqsyo** [comment]
thanks for your reply.
But where can i turn on the metrics-endpoint? I can't find it in the Admin-Panel..

**Comment by geekgonecrazy** [comment]
Logs prometheus enabled.  Will then be available at yourhost:9100

![image](https://user-images.githubusercontent.com/51996/40941497-a1b86f24-6810-11e8-861f-b511ed43c798.png)

**Comment by Maqsyo** [comment]
I think you misunderstood me in any way.
I want to get all unread messages of a specific user and not some logs..
Why you can't give us these informations?

Anyway.. i enabled Prometheus and i can't reach it on the specific port.

I don't understand why this "issue" is closed even though it wasn't resolved. @geekgonecrazy

**Comment by geekgonecrazy** [comment]
Ah sorry I misunderstood you want to get count.  Please open a feature request: https://forums.rocket.chat/c/feature-requests

**Comment by Maqsyo** [comment]
https://forums.rocket.chat/t/api-user-info-unread-messages-and-count-of/1152
