### ISSUE TITLE
[Question] Accounts login/signups integration

### ISSUE THREAD

**Issue by abdellahaski** [RocketChat/Rocket.Chat#10985]
hi,
I'm currently developing a spring boot app (J2EE) and I have a Rocket.chat instance that should be integrated with it just in the authentication part.
So I got my spring boot app where users can create their account and it should also gets created on the rocket.chat automatically also when an existent user login to my spring boot app he also get logged in to rocket.chat automatically.
I searched the rockets.chat docs, I saw many authentication options but I don't know which one will work for me, and how I'll get it to work.

It would be great if someone could help me or link me to a tutorial to help me set this up.

PS: the Spring boot app use a MySQL database to store users information

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
