### ISSUE TITLE
Loading larg-sized Images

### ISSUE THREAD

**Issue by reza899** [RocketChat/Rocket.Chat#10980]
### Description:
Our Rocket not work correctly after upgrading to 65.1 in **_loading image_**,
the problem most see in large-sized images, 
this problem happens on old posts (before upgrading to 65.1)

### Server Setup Information:

* Version of Rocket.Chat Server:  0.65.1
* Operating System: Ubuntu 16.04 (4.4.0-87-generic)
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: v8.11.1
* mongoDB Version:

**Comment by geekgonecrazy** [comment]
Not enough information to properly describe the issue.  Please update to include more information

**Comment by TGriwenka** [comment]
I see the same issue, but with every large image that was uploaded or is uploaded. 

I upload a large image and it is shown as you see in the two attached screenshots. It is shown the same in browser and in Rocket.Chat Client for MacOS (I tried already the actual developer version, which I compiled by myself).

First screenshot shows the image in the timeline. You see only part of the big image.

Second screenshot shows the image after I clicked on it in the timeline. There you see the complete original image...

<img width="1652" alt="screenshot_306" src="https://user-images.githubusercontent.com/17764949/40905441-da428450-67d5-11e8-95c8-153658daa4ab.png">
<img width="1615" alt="screenshot_305" src="https://user-images.githubusercontent.com/17764949/40905457-e0aa8e1e-67d5-11e8-86a0-0b6b4b21891d.png">

**Comment by vynmera** [comment]
Yeah, it seems the new lazyload doesn't scale images. So images that are too large just expand beyond the view.

**Comment by reetp** [comment]
Same on docker 065.1

Really slows the loading and unnecessarily take up acres of screen real estate.

A real retrograde step.

**Comment by kuluev** [comment]
@rocket-cat label add "type: bug"

**Comment by kuluev** [comment]
I can confirm this. It happens when you upload a full-sized photo from android client.

**Comment by richardt3** [comment]
Timeline image previews are not being resized to an appropriate size but are being shown at the original file height and width. No scrollbars so image is useless. Either a css class has been deleted or a resize function is no longer being called.

**Comment by vynmera** [comment]
@richardt3 I'm pretty sure a CSS class was lost, as the images no longer have `cursor: pointer` either. I'll look into it...

**Comment by richardt3** [comment]
@vynmera because of users shouting,  I added a dirty hack piece of custom css to my install to make width 80% of the frame. Image is still a full download but doesn't take up the whole screen now.

**Comment by geekgonecrazy** [comment]
Thanks  for  the fix @vynmera :+1:

**Comment by acolville** [comment]
@vynmera - nice one. I don't suppose you have the CSS handy? Save waiting for the next release :)

**Comment by vynmera** [comment]
@acolville My fix includes a small HTML change too, so perhaps try out https://github.com/RocketChat/Rocket.Chat/issues/10980#issuecomment-394358198 ?

**Comment by cloudsandladders** [comment]
quick fix before release

Administration > Layout > Custom CSS
add
```
.attachment-image img {
  max-width: 100%;
  max-height: 70vh;
  height: auto;
  width: auto;
}
```
