### ISSUE TITLE
Segoe UI: character descender not correctly rendered on top header

### ISSUE THREAD

**Issue by Otiel** [RocketChat/Rocket.Chat#10992]
### Description:

While using the font Segoe UI, the characters descender (the part of a character (g, j, p, q, y) that descends below the baseline) are not correctly rendered: they are "cut", as you can see on the screenshot below.

![image](https://user-images.githubusercontent.com/3851902/40912022-b69664fc-67f0-11e8-9e43-ba363a297a39.png)

It happens on the top header bar title and description.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: Windows 10 Pro

### Steps to Reproduce:

1. Set Segoe UI as first font under *Administration → Layout → Fonts*
![image](https://user-images.githubusercontent.com/3851902/36658296-1e760c6c-1ad0-11e8-9c61-70786831d4ad.png)
2. Observe

### Expected behavior:

Characters with descender (g, j, p, q, y) correctly rendered.

### Actual behavior:

The descender of the characters g, j, p, q, y are "cut".

**Comment by geekgonecrazy** [comment]
Looks like last comment says resolved.  Closing

**Comment by Otiel** [comment]
>Looks like last comment says resolved.

No it doesn't:

>It's back since a few versions.

I confirm the bug is still present. Please reopen this issue.

**Comment by geekgonecrazy** [comment]
Is it just this one font only?

**Comment by tassoevan** [comment]
@geekgonecrazy I'm not sure. However, Segoe UI is one of the default fonts present in our settings now, therefore we have to support it or deprecate it.

**Comment by geekgonecrazy** [comment]
Ah!  I never adjust fonts so didn’t even realize 😁. So yeah we need to fix

**Comment by ggazzo** [comment]
fixed, any problem let me know
