### ISSUE TITLE
_user_name_ sent a message on channel, not real user

### ISSUE THREAD

**Issue by superminiek** [RocketChat/Rocket.Chat#11005]
### Description:

After mention of current user e-mail contains _user_name except profile username

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: -
* DB Replicaset Oplog: -
* Node Version: -
* mongoDB Version: -

### Steps to Reproduce:

1. Mentions feature, mentioned user received an e-mail
2. E-mail has a _user_name

### Expected behavior:

E-mail has a _user_name_, not real user for the current profile

### Actual behavior:

E-mail has a _user_name

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
