### ISSUE TITLE
"User Info" in DM showing wrong user's info

### ISSUE THREAD

**Issue by garychapman** [RocketChat/Rocket.Chat#11003]
### Description:

The "User Info" function in a DM shows the most recently-viewed user's info, which is not necessarily the current DM recipient

### Server Setup Information:

Can be replicated in https://open.rocket.chat

### Steps to Reproduce:

1. Create a DM with UserA
2. Click the "User Info" icon, and UserA's information is shown in the sidebar - as expected
3. Mention UserB in the conversation
4. Click on the underlined UserB mention, and UserB's information appears in the sidebar
5. Click the "User Info" icon again, and UserB's information still appears in the sidebar

### Expected behavior:

At Step 5, UserA's info should appear in the sidebar as per Step 2

### Actual behavior:

At Step 5, UserB's info appears in the sidebar

Performing a browser refresh clears this issue.

---

And as an aside, is there any reason why the New Conversation button doesn't appear in the sidebar when showing info for a mentioned user? It would be a very handy feature.

**Comment by geekgonecrazy** [comment]
Haven’t been able to reproduce this one any more.
