### ISSUE TITLE
Hiding Direct Messages wrong icon and title tag

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#1101]
Hiding a message shows an open eye, instead of slashed eye.  It used to be an "X"?  Also the message says Hide Room... easy quick fix.

![screen shot 2015-10-15 at 02 44 26](https://cloud.githubusercontent.com/assets/277910/10495626/fdd0c27e-72e6-11e5-9383-79ec2cd79dad.png)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:14412)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZmS10-002yoo-Mz
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:47:11 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vpf1nCBkw3xps1hGcSwrtcmBr6c=; b=FGdn/DSadviIPiRF
	mFcmstp3kFDiVow+hsKTOvB3pZmSrdqMeye3ez8XW6YZcREJaI6/0+horB1YYXCb
	yBy8xI9km6YRN/6ol1LtIpEkimL477KxXDvWI1+Jy1czJompvlAfS0LNZ5v0mxJd
	2tOpgQbDEHnC/YqFp8WNC6nYzpQ=
Received: by filter0467p1mdw1.sendgrid.net with SMTP id filter0467p1mdw1.30992.561EB13A26
        2015-10-14 19:47:06.548502249 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id mTn7hCZeSJKyU27bEJUT9w
	for <greg@biomassiv.es>; Wed, 14 Oct 2015 19:47:06.718 +0000 (UTC)
Date: Wed, 14 Oct 2015 12:47:06 -0700

**Comment by geekgonecrazy** [comment]
What's wrong with the title text?

I agree on the eye.  Should be a crossed out eye.
