### ISSUE TITLE
iOS devices not receiving push notifications

### ISSUE THREAD

**Issue by OmegaPrimeZ3** [RocketChat/Rocket.Chat#11015]
### Description:

Since upgrading to the latest version, push notifications are not being delivered to iOS devices. Through trouble shooting, determined that opening Rocket.Chat on our phones does assign a token as we can click the Test under push and the notification will state sent to 1 device. However no message is ever sent. If clicking the Test button a second time, the notification states No Token for User. We are not using your gateway, however when we attempt to, the same result is seen.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Oper Ubuntu 16.04.4 LTS
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.3
* mongoDB Version: 3.6.2

### Steps to Reproduce:

Open Rocket.Chat on iOS device
Login and allow push notifications
No notifications are received for chat messages or tests.

### Expected behavior:

Notification received by iOS device

### Actual behavior:

No notification received

**Comment by DiederikvandenB** [comment]
Did you ever find a solution to your problem? We are experiencing the same issue.

**Comment by ggazzo** [comment]
@OmegaPrimeZ3 did you try update to the last version? @DiederikvandenB do you know what version of rocket chat you are running?
