### ISSUE TITLE
Bug: Images do not get downscaled in messages

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#11013]
### Description:

Prior to 0.65 uploading an Image, regardless of size was scaled down nicely into a thumbnail size. Now, the full size image is shown, regardless of size. A giant image is only shown partialy as it will not fit into the chat.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: Centos 7.5
* Deployment Method(snap/docker/tar/etc): Tar
* Number of Running Instances:  1
* DB Replicaset Oplog: False
* Node Version: v8.9.4
* mongoDB Version: v3.4.15

### Steps to Reproduce:

1. Install Version prior ro 0.65
2. Post an image that is large enough.
3. Notice how the image preview is nicely shown downsized as a thumbnail
4. Repeat 1+2 with 0.65
5. Notice how the image is shown full size, regardless.

### Expected behavior:

Image is shown downscaled as thumbnail, clicking will reveal full sized image.

### Actual behavior:

As seen here: [https://cloud.alpha-labs.net/index.php/s/wjYoqtiWP6DMTt4/preview](https://cloud.alpha-labs.net/index.php/s/wjYoqtiWP6DMTt4/preview)

**Comment by kaiiiiiiiii** [comment]
Duplicate of #10980, fixed in PR #10998

**Comment by christianreiss** [comment]
true, ok.

**Comment by acolville** [comment]
Is there anyway to work around this prior to the next release? :)

**Comment by cloudsandladders** [comment]
@acolville 
Yes, in Administration > Layout > Custom CSS

add
```
.attachment-image img {
  max-width: 100%;
  max-height: 70vh;
  height: auto;
  width: auto;
}
```
