### ISSUE TITLE
Disconnect from the DDP server when the LiveChat visitor's status is away

### ISSUE THREAD

**Issue by renatobecker** [RocketChat/Rocket.Chat#11023]
### Description:

When the Livechat Widget is loaded, a new DDP connection is started between the client and the server. The client/visitor may never interact through the widget or just stop chatting, which will change their connection status to away.
In this case, the DDP connection will remain active and consuming server resources, so it would be nice to handle the Livechat DDP connection, connecting/disconnecting according the visitor's status.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.66.0-develop
* Operating System: any
* Deployment Method(snap/docker/tar/etc): any
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.11.1
* mongoDB Version: 3.4.10

### Steps to Reproduce:

1. Start a Livechat widget
2. Don't start a conversation or stop chatting

### Expected behavior:

- When the `Idle Time Limit` is reached, the current DDP connection must be closed.
- When the Livechat widget is reactivated, the current DDP connection must be opened.

### Actual behavior:

The DDP connection is always open between the client and the server.

**Comment by marceloschmidt** [comment]
This is not a problem anymore on new livechat client.
