### ISSUE TITLE
No notifications on Iphone

### ISSUE THREAD

**Issue by amarendrayadav** [RocketChat/Rocket.Chat#11028]
### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3.

**Comment by vynmera** [comment]
Please, explain more. What iPhone? What app? What version of Rocket.Chat? Any error messages? Update your issue description, please.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  Much has changed on both server and mobile since
