### ISSUE TITLE
Wrong font-family order

### ISSUE THREAD

**Issue by myfonj** [RocketChat/Rocket.Chat#11037]
https://github.com/RocketChat/Rocket.Chat/blob/98c3ed5c8d9ad67e16ad470d963d6270b6b6671b/packages/rocketchat-theme/server/variables.js#L69

For some (quite understandable) reason, on Windows 10 such declaration produces funky results for emoji and /or combining characters. `, Arial, sans-serif` should be at the end of such declaration, which should be from specific to generic font faces, here the order of Segoes is reversed and probably shadowed by the generic family.

**Comment by engelgabriel** [comment]
https://bitsofco.de/the-new-system-font-stack/

**Comment by myfonj** [comment]
Found that while messing with userstyle that disables 'picturized' emojis and returns their text content back, and during investigation found there are more quirks than expected:

https://imgur.com/a/eh8N3sg
https://codepen.io/myf/pen/WyGqbq

The outcome is that for some fonts handles some ways of encoding better and that "Segoe UI Emoji" has most probably some kind of flaw (on my machine).  Resorting to "Segoe UI" alone seems to be the best solution for this certain problem, although it takes away the colours in emojis.  But it is quite unrelated to RC since you are using own robust imagery :]

**Comment by myfonj** [comment]
Looking at ↑ pull (https://github.com/RocketChat/Rocket.Chat/pull/11191/files#diff-39d471521e300f53e48eec47f92c0401R69) this will technically mean given version will have basic windows font **changed from Arial to Segoe UI**, which has different metrics and could potentially surprise users.
There's nothing wrong with it and it was basically my initial proposal (although such switch was unintentional: I just wanted to fix some obscure emoji quirks).  But all things considered, giving more generic system font family _before_ those "emoji" thingies could have been beneficial for some cases after all. I was probably overly dogmatic in the initial report…
