### ISSUE TITLE
[BUG] Livechat: I can't hide conversations

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#11034]
### Description:

I can't hide conversations on livechat.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: Linux (Ubuntu) x64 4.4.0-1049-aws
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.11.2
* mongoDB Version: 121

### Steps to Reproduce:

![rocket chat-07_06_2018-09_50_58](https://user-images.githubusercontent.com/17053653/41101215-ec926952-6a39-11e8-99ef-3b631a4c9dcf.gif)

### Expected behavior:

I can hide conversations on livechat.

### Actual behavior:

I can't hide conversations on livechat.

**Comment by pkgodara** [comment]
@guilhermecfviana Anything you can see in logs? That would be quite helpful.

**Comment by guilhermecfviana** [comment]
@pkgodara When I execute the action it does not display any log.

![image](https://user-images.githubusercontent.com/17053653/41156315-c39b6aa8-6af7-11e8-978a-bb5821eabcc8.png)

**Comment by engelgabriel** [comment]
@guilhermecfviana is there are msgs on your browser console log?

**Comment by guilhermecfviana** [comment]
@engelgabriel Yes.

![clipboard - 11 de junho de 2018 as 13-32](https://user-images.githubusercontent.com/17053653/41244663-16883bd4-6d7c-11e8-9d4c-264679c1cc72.png)

**Comment by renatobecker** [comment]
Hi @guilhermecfviana.

We've identified some issues related to translations files. I saw that your current language is 'pt'/'pt-BR', if you change your language to 'en', for example, will probably no longer occur.
Can you try this and give us a feedback?

I'll be waiting your feedback.
Thanks.

**Comment by renatobecker** [comment]
@guilhermecfviana, this fix will be in our next version(0.66) which will be released very soon.
I'm closing this issue and I suggest you to be tuned and waiting for our new version to test it again.
