### ISSUE TITLE
.

### ISSUE THREAD

**Issue by JayLearn** [RocketChat/Rocket.Chat#11032]
### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3.

**Comment by vynmera** [comment]
Thank you for your report. We will go right ahead trying to fix this issue.

**Comment by vynmera** [comment]
@rocket-cat close
