### ISSUE TITLE
How to disable file upload in channels but keep it for private messages

### ISSUE THREAD

**Issue by andranikvfx** [RocketChat/Rocket.Chat#11048]
hey guys, was wondering if there is a way to enable file access only for private messages but not for channels.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

But answering your question: No, currently we do not provide this option

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
