### ISSUE TITLE
No Sets on Windows 10

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#11047]
Almost every program I use supports Sets, it's really irritating to not have that on RocketChat.

**Comment by vynmera** [comment]
Is this about the desktop app? If so, that should probably be reported here instead: https://github.com/RocketChat/Rocket.Chat.Electron as I believe this would be something Electron will have to pick up in its WINAPI hooks. Opening Rocket.Chat in Edge or w/e should allow using it in Sets, right?

(I don't use W10 so forgive me if I'm wrong)

**Comment by HammyHavoc** [comment]
You're absolutely right. :- )
