### ISSUE TITLE
Changes made to Livechat settings do not save

### ISSUE THREAD

**Issue by peterdalydickson** [RocketChat/Rocket.Chat#11058]
### Description:

Changes made to Livechat settings do not save.

### Server Setup Information:

* Version of Rocket.Chat Server: 65.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3
* mongoDB Version: 3.6.4

### Steps to Reproduce:

1. access Livechat administration
2. change 'Display Offline Form' to `True`
3. change 'Title offline'
4. click 'Save'
5. refresh the browser

### Expected behavior:

Above changes to have saved.

### Actual behavior:

Changes do not save.

[https://www.useloom.com/share/a41c166b207c497888d7bdd0bac4078a](https://www.useloom.com/share/a41c166b207c497888d7bdd0bac4078a)

**Comment by renatobecker** [comment]
Hi @ Peterdalydickson!
Thank you for detecting this wrong behavior in Livechat's appearance. We're going to check what's happening when saving the data.

@joseftw, I suggest you create another issue because the case you are mentioning is not related to the Livechat feature.
