### ISSUE TITLE
Android App not Working for RocketChat

### ISSUE THREAD

**Issue by nwd3** [RocketChat/Rocket.Chat#11060]
### Description:
I have rocketchat version 0.65.1 installed(this issue also occurs for version 0.60.1) and the rocketchat android app does not work.   I tried multiple versions of the app.  It always errors out giving messages like: "this is not a valid rocketchat instance" and other error messages.  The server works fine on the ios app.  SSL is enabled behind an apache server.

### Server Setup Information:

* Version of Rocket.Chat Server: .65.1
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: not enabled
* Node Version: not sure
* mongoDB Version: not sure

### Steps to Reproduce:

1. open rocketchat app
2. type in server address
3. error message shows

### Expected behavior:
rocketchat android app to work.

### Actual behavior:

App errors out

### Relevant logs:
not available

**Comment by ggazzo** [comment]
hey @nwd3 I think its a problem with android app could you open your issue here https://github.com/RocketChat/Rocket.Chat.Android? Thanks.
