### ISSUE TITLE
Apps are broken since merge of theme-package

### ISSUE THREAD

**Issue by pschonder** [RocketChat/Rocket.Chat#1106]
<img src="https://cloud.githubusercontent.com/assets/66947/10497412/f91eb798-72c5-11e5-9780-c23ce31d1075.png" alt="screen shot 2015-10-14 at 22 49 55" width="400px">

Looks like the CSS could not be loaded.

**Comment by pschonder** [comment]
@rodrigok any ideas?

**Comment by engelgabriel** [comment]
Yes, @rodrigok will take a look. The CSS is now dynamically generated.. so we may have broke something.

**Comment by geekgonecrazy** [comment]
I think the app is a little out dated.  A lots missing from the assets compiled in.  Just building a new version might resolve this.

**Comment by pschonder** [comment]
I did a fresh build to make the Screenshot. A build which is based on a commit before the merge, looks normal.

**Comment by geekgonecrazy** [comment]
Some how I missed that you were running in emulator. I'll let the other guys look into that :D

**Comment by pschonder** [comment]
@rodrigogs: I can confirm, that the theme is loading now, but there are still some small issues. The icons like the "hash-icon" is not loaded in the app and some textboxes do not adapt the primary background color. 
![screen shot 2015-10-16 at 08 54 00](https://cloud.githubusercontent.com/assets/66947/10535489/9356c08a-73e3-11e5-93b7-56326fe94534.png)
![screen shot 2015-10-16 at 08 54 16](https://cloud.githubusercontent.com/assets/66947/10535492/961f519c-73e3-11e5-960d-f2198de33c2c.png)

**Comment by pschonder** [comment]
@engelgabriel @rodrigok: could you please re-open this issue? there are some more issues as i described above.

**Comment by engelgabriel** [comment]
My mistake :)

**Comment by engelgabriel** [comment]
Another issue about the same problem https://github.com/RocketChat/Rocket.Chat/issues/1132

**Comment by engelgabriel** [comment]
Is this now fixed by https://github.com/RocketChat/Rocket.Chat/commit/e0519995993d1d1a3d7299ed86a5672a1cd01853

**Comment by pschonder** [comment]
@engelgabriel: i cannot confirm the bug is fixed. i don't want to get on your nerves, maybe my setup is wrong. the app looks now like the screenshot in the beginning of this issue. can i help with some information, to help you solve the problem?

**Comment by pschonder** [comment]
@engelgabriel , @rodrigok: Are there any ideas to fix this issue or is it fixed already?

**Comment by gmsecrieru** [comment]
I think we have something related to themes merged. Are you still experiencing isses?

**Comment by Tharnas** [comment]
For me it's still like in the initial post (2efecc79a5291eb92b8568e27c035bec85ea6970)

**Comment by pschonder** [comment]
I can confirm that the bug is fixed when running locally on my dev machine with the ***meteor*** command. When running with the **pm2** config on my server, the app doesn't load any stylesheets.

**Comment by engelgabriel** [comment]
Are you 100% certain that you are running the latest version? Did you do a
'meteor build' after your 'hit pull' ?

-- 
Sent from Mobile

**Comment by pschonder** [comment]
I used the Wiki article and checked out the master branch with THW lastest commits.

https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-to-UBUNTU#3-download-rocketchat

**Comment by Tharnas** [comment]
I got the latest to build the app. Do i also need the latest for the server?

**Comment by rodrigok** [comment]
@Tharnas yes you need the latest version of server too

**Comment by engelgabriel** [comment]
Are your deployments on public URLs we can see so we can try to understand better what is wrong?

**Comment by Tharnas** [comment]
Ok, sorry. In this case i will test it with the latest from github (currently just running latest docker image).
In case i still run into issues i will provide you access.

**Comment by Tharnas** [comment]
I tried it now with the latest version (7a96a70a016a4e6c19978bb160463542c588b75d) and it's still the same.
I depolyed the version to an test environment with new database on: https://mathiasjutz.com:8080
In the general Channel you will find a link for the apk.

**Comment by pschonder** [comment]
I also installed a fresh version of the latest commit (https://github.com/RocketChat/Rocket.Chat/commit/e0953fa48c5bec306e2f64a4e1ab252d44d76053) to http://rocket.c2is.de:3000 and the app in my ios-simulator is still broken.

**Comment by pschonder** [comment]
@Tharnas: Could you try adding the iOS and Android platform to your ***server*** with the following commands in the sources folder:

```
meteor add-platform android
meteor add-platform ios
```
then rebuild the server.

After I removed the app from my simulator and started a build from Xcode the app has styles now. :tada:

@engelgabriel @rodrigok: Can you confirm, that this step is needed? There is no hint in the documentation and btw. there are 2 or 3 versions of tutorials, how to install rocket.chat-server on Ubuntu/Linux. Each of them is slightly different. Which is the right one?

**Comment by Tharnas** [comment]
Ok. I'll try it and let you know. Hope i can build it as im building on linux.

**Comment by Tharnas** [comment]
I rebuilt the server. It's still the same but i think this is because i built it (added android & ios) on linux that does not support ios build.

**Comment by rodrigok** [comment]
@pschonder Yes, if you are trying to use your own iOS/Android app pointing to your own server you need to build the server app adding the ios/android platform, without this meteor will not refresh the mobile application with new resources.

**Comment by pschonder** [comment]
@rodrigok Okay, thanks. That issue was nerve-racking for me. Could we add some documentation for this, so we can close this issue afterwards?

@Tharnas If you still need help, please contact me on https://demo.rocket.chat

**Comment by hansaliyad1** [comment]
I am facing the same issue. All style sheets are broken. Is there any documentation to fix that?

**Comment by karmacoma** [comment]
I'm also facing the same issue. On first invocation, the app has no styles. If I close the app and reopen it, the styles then load.

**Comment by jonbaer** [comment]
So I battled through this one for a few days, @rodrigok is right you need to at least attempt to build iOS/Android ON your server for some manifest files to load properly (at least that was my frustrating experience) ... this is not ideal when your server is CentOS where you can't really do much w/ iOS (or Android for the most part) ... I think this is part of another issue but can't locate the issue # ...

**Comment by hansaliyad1** [comment]
This problem is killing me @jonbaer struggling hard to solve it..still didnt got a solution

**Comment by jonbaer** [comment]
Does this relate? http://stackoverflow.com/questions/30140579/meteor-cordova-app-fails-to-download-manifest-json-for-use-with-autoupdate-what

"The result was that the server did not create the required files for a mobile app like __cordova/manifest.json"

**Comment by hansaliyad1** [comment]
So does this solution works for you @jonbaer ??

**Comment by hansaliyad1** [comment]
I would really appreciate if anyone can help me solve this broken app....it is really frustrating....@rodrigok

**Comment by engelgabriel** [comment]
Hi, most of the team was away at OSCON... And some are on holiday today :(

Rodrigo highest priority now it to work on the mobile apps, so this will be
fixed shortly, together with multi server support.


-- 
Sent from Mobile

**Comment by solo999** [comment]
@hansaliyad1 
I had the same issue when I build android/ios version with biuld-android.sh/build-ios.sh without actually build and deploy server part. Try to add android/ios platform, run meteor build and deploy to your server.
First android/ios app run will have broken css, but after hot push update from your server css will be fixed. Hope it'll help...

**Comment by jonbaer** [comment]
Yes this is an important part ... you should forget about running "meteor run" and pointing --server to localhost:3000 ... you need to use the server copy that is built along with the mobile app in order for it to function correctly ... (at least that has been my experience), will wait for official word ...

**Comment by hansaliyad1** [comment]
Thank you @engelgabriel . I really appreciate for that

**Comment by engelgabriel** [comment]
Guys, I'll close this issue as we are fully moving the mobile apps development to https://github.com/RocketChat/Rocket.Chat.Cordova

Can you please download it and help us to test?

**Comment by jalagrange** [comment]
Hello, I am having this same problem but I am running the Cordova apps. 

The server (which I deployed myself on AWS) works fine for Web browsing. 

The iOS app which I also compiled from the suggested Cordova project also works fine if I point it to https://demo.rocket.chat.

However when I point the iOS app to my own server when prompted, the files load, but then I am shown the login with no CSS. When I use developer tools I can see that theme.css is not properly loaded. 

Any ideas?

**Comment by jonbaer** [comment]
In your Cordova project try changing the line in /hooks/downloadCache.js ...

var server = 'https://demo.rocket.chat';

To point to your server.

**Comment by jalagrange** [comment]
Hi @jonbaer , thanks for this advice. However it did not work. The good thing is that you brought me closer to the problem as I do believe it is a caching issue. I can clearly see that the theme.css?#hash for mobile is being created and can be found on my deployed server. But for some reason the mobile applications refuse to download and instead they get served what appears to be the html file.

All other js and css are being served and received without a problem. (with the exception of .sandstorm-credentials, but that is also broken when pointing to https://demo.rocket.chat)

I actually had the mobile app working fine last week so i thought it was a problem with recent updates so I rolled back the commits to the same version that was previously working with mobile apps. However to my surprise, now those versions don't work. 

This makes me pretty convinced that I'm dealing with a caching issue but I just don't know where.

**Comment by engelgabriel** [comment]
Did you try deleting and installing the app again?

**Comment by jonbaer** [comment]
On another project I also had to do a fresh "cordova platform remove android && cordova platform add android" to reset some files (or @ least that is what was recommended to me).  I don't know what the adb logcat equiv would be on iOS but I would be sure there would be something in there, at least that was how I way able to determine missing cache files on my end.  YMMV.

**Comment by jalagrange** [comment]
Hi @engelgabriel, thanks for helping out. I did delete and reinstall and I am running with the issue within the iOS simulator which allows me to debug. I am also erasing all data and application created by each XCode build in:

/Users/username/Library/Developer/CoreSimulator/Devices/'has'/

in order to ensure that each build is a clean build.

In regards to @jonbaer (thanks again for helping out). I did try "cordova platform remove android and ios"  in the server and got an error when connecting with the iphone app saying the server wasnt setup for mobile or something similar. I then proceeded to add them again but couldn't compile on the server with android platform so i just compiled with the ios platform on the server.

A far as mobile apps, I also removed, added an rebuilt them with no luck... 

I am totally out of ideas at this point.

**Comment by engelgabriel** [comment]
Note that, in node 0.10.x, if you connect using an IP, the IP address has to be in the altnames - node.js will not try to verify the IP against the CN.

Setting the rejectUnauthorized flag to false will get around this check, but first of all if the server is giving you different credentials than you are expecting, something fishy is going on, and second this will also bypass other checks - it's not a good idea if you're connecting over the Internet.

**Comment by Johann-Snapp** [comment]
Did you try to reinstall your server ? Worked for me (cf: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/65)

**Comment by jalagrange** [comment]
I have done redeploys but not a clean install of my server, I see aparently you had issues with 0.14. Guess theres a light at the end of the tunnel, thanks @Johann-Snapp !! Il get back to you once I try this
