### ISSUE TITLE
How to update server (Ubuntu)

### ISSUE THREAD

**Issue by Diluke** [RocketChat/Rocket.Chat#11068]
I cant find information on how to update Rocketchat server in Ubuntu. 

### Description:
I want to update my server instance in hopes to fix errors in file upload (in some cases uploaded files show empty)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.2
* Operating System: Ubuntu 16.04 64bit
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: v8.9.3
* mongoDB Version: v3.6.5

**Comment by kaiiiiiiiii** [comment]
The update process is the same as the install process. Just stop your systemd/pm2//whatever, delete the old RC folder, download and untar the new version, run npm install and start your systemd/pm2 again.

**Comment by Diluke** [comment]
Thank you very much, i'm running latest version now.
One thing remains, correcting documentation
https://rocket.chat/docs/installation/updating/

**Comment by TwizzyDizzy** [comment]
Just created docs-PR #834 to account for your suggestion. Gonna close this issue once it is merged.

Cheers
Thomas
