### ISSUE TITLE
Make links in home body clickable

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#11065]
In my home body I have a hyperlink:

![image](https://user-images.githubusercontent.com/6703876/41184106-e549bd0e-6b32-11e8-8d1e-dd394da578c4.png)

But I cannot make that hyperlink clickable.

I have tried using [url][/url] and I have also tried using the a html tag

**Comment by vynmera** [comment]
`<a href="your url goes here">your text goes here</a>`
please, try out W3Schools or Codecademy to learn more about HTML :)

**Comment by vikaskedia** [comment]
Thank you @vynmera it works. I did not have the quotes around the URL.
