### ISSUE TITLE
Duplicate "Add New Server" button in rocket chat applucation 2.11.0 on Windows10

### ISSUE THREAD

**Issue by vddmvddm** [RocketChat/Rocket.Chat#11078]
**Server Setup Information:**
Version of Rocket.Chat Server: 0.64.1
Operating System: Linux (Debian) x64 3.16.43-2+deb8u5
Deployment Method(snap/docker/tar/etc): manual install
Number of Running Instances: 5
DB Replicaset Oplog: Enabled
Node Version: v8.9.4
mongoDB Version: 115

**Steps to Reproduce:**
![rocket_app](https://user-images.githubusercontent.com/28955375/41215604-c0b7859c-6d59-11e8-851a-6d1d58c5ecbe.gif)

**Actual behavior:**
Duplicate "Add new server buttons" after update rocket chat application on version 2.11.0 from 2.10.5 on Windows10

**Comment by rkgoswami** [comment]
Update to latest version and started getting the above issue. Anyone resolve it soon.

**Comment by kaiiiiiiiii** [comment]
This is not a problem with the server component, it’s an Electron client problem.

An issue in the Electron repo is already existent (https://github.com/RocketChat/Rocket.Chat.Electron/issues/744)

**Comment by engelgabriel** [comment]
I am closing this issue to track on Electron project.
