### ISSUE TITLE
Account creation button is not displayed!

### ISSUE THREAD

**Issue by neucom** [RocketChat/Rocket.Chat#11077]
Logging in with an account with Admin privilege, the Add User button does not appear in [Users] in [Administration].
![1](https://user-images.githubusercontent.com/1433627/41209459-c0f45ac8-6d66-11e8-945e-9363dc0a2f96.png)
When you click on an existing user, the [Invite Users] and [Add User] buttons appear together with [User Info].
![2](https://user-images.githubusercontent.com/1433627/41209460-c132be8a-6d66-11e8-99a6-a6c7d6ded342.png)
![3](https://user-images.githubusercontent.com/1433627/41209461-c15a4e28-6d66-11e8-91ce-79496f8d6ce4.png)

**Comment by kaiiiiiiiii** [comment]
Duplicate of #10951

**Comment by neucom** [comment]
Thank you for letting me know! :bow:
