### ISSUE TITLE
RocketChat just work in Background

### ISSUE THREAD

**Issue by RehaChris** [RocketChat/Rocket.Chat#11081]
### Description:
RocketChat starts up on doubleclick in 4-5 instances, even 2 Symbols with one disappearing on Mouse Hover. But the Programm will never appear on Screen, just work in the Background.
Restart dont fix, Reinstall dont fix

### Steps to reproduce:

No idea....

### Expected behavior:

The Programm would be able to shown on the Desktop

### Actual behavior:

RocketChat just works in Background and dont "wake up"

**Comment by kaiiiiiiiii** [comment]
Hi @RehaChris,

I'd like to refer you to the electron repository, as this seems to be a problem with the electron desktop client.

https://github.com/RocketChat/Rocket.Chat.Electron

Feel free to open an issue over there :)

**Comment by TwizzyDizzy** [comment]
As @kaiiiiiiiii said.

Cheers (+close)
Thomas
