### ISSUE TITLE
Error when Downloading or Exporting My Data

### ISSUE THREAD

**Issue by etyack** [RocketChat/Rocket.Chat#11082]
### Description:

We are unable to Download or Export My Data.

### Steps to reproduce:

1. Log in to RocketChat
2. Click on My Account
3. Scroll to the bottom of the page
4. Click either DOWNLOAD MY DATA or EXPORT MY DATA

### Expected behavior:

Clicking on either button, I expect an email with instructions how to access a file containing my chat history.

### Actual behavior:

An email is never received with instructions how to access my chat history.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1  DB Migration 121
- Operating System: Ubuntu 16.04.4
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.2
- MongoDB Version: 

### Relevant logs:

There are no errors generated in the browser.

Server log:
[34mI20180611-08:39:00.876(-4) [34mSyncedCron ➔ info Starting "Generate download files for user data". 
[34mI20180611-08:39:00.903(-4) Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/rocket_chat_export_compressed/MfANF2qwBemicsdJB.zip'   
[34mI20180611-08:39:00.912(-4) [34mSyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20180611-08:39:00.948(-4) [34mSyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20180611-08:39:00.951(-4) [34mSyncedCron ➔ info Finished "Generate download files for user data".

**Comment by kaiiiiiiiii** [comment]
Hi @etyack,

this should be fixed with PR #10837 (Release 0.65.0). Are you sure you're on the latest release?

Cheers

**Comment by etyack** [comment]
Yes, I double checked since I found the issue you referenced before I submitted this issue.

According to the snap output:
erickt@wiki:~ sudo snap list
Name               Version    Rev   Tracking  Developer   Notes
core               16-2.32.8  4650  stable    canonical   core
rocketchat-server  0.65.1     1273  stable    rocketchat  -

And admin Info output.
![screen shot 2018-06-11 at 10 28 34 am](https://user-images.githubusercontent.com/130788/41237721-3a04abca-6d62-11e8-8296-67f9feef67cd.png)

**Comment by kaiiiiiiiii** [comment]
Thanks for the quick reply @etyack :)

@Hudell You may want to have a look?

**Comment by phillipplum** [comment]
We are unable to Download or Export My Data, too. But in our logs, are no error messages. 

Here are the only lines:
```
[34mI20180613-08:27:05.962(0) [34mMeteor ➔ method requestDataDownload -> userId: dc45SQus6oW8Ajutc , arguments:  { '0': { fullExport: true } } 
[ ... ]
[34mI20180613-08:30:00.500(0) [34mSyncedCron ➔ info Starting "Generate download files for user data". 
[34mI20180613-08:30:00.505(0) [34mSyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20180613-08:30:01.023(0) [34mSyncedCron ➔ info Finished "Generate download files for user data". 
```

**Comment by Hudell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error when downloading or exporting data](https://trello.com/c/MhzJKukS/1-error-when-downloading-or-exporting-data)

**Comment by Hudell** [comment]
@phillipplum Can you check your "User Data Download" admin settings? Based on your log, it seems like there's no Processing Frequency configured.

**Comment by phillipplum** [comment]
Here are our settings. We don't change something.

![image](https://user-images.githubusercontent.com/6051483/41620915-70d7e914-740b-11e8-9a0f-0fcbbbb58648.png)

**Comment by Hudell** [comment]
I'll look into it.

**Comment by torgeirl** [comment]
@Hudell: I also experience this issue. It seems identical to the others here:
- Email is never received with instructions how to access the chat history
- No error message presented to the user
- No error message in logs

Setup:
- Server version: `0.65.1` deployed with Snap, on Ubuntu Ubuntu 16.04 (newest available for snap)
- Default `User Data Download` settings (enabled, frequency=15m, message limit=100)
- Email verified working. Logging suggests Rocket.Chat server never attempts to send the email.

Please let us know if you need any debugging assistance.

**Comment by phillipplum** [comment]
Unfortunately, it still does not work after the update to 0.66.0.

**Comment by phillipplum** [comment]
Update:
Now _(3-4 hours later)_ I get a e-mail with an download link.
The link looks like this: https://chat.domain/ufs/FileSystem:UserDataFiles/Yu7JK49278JiX8duy/2018-06-28-firstname%2520lastname.zip 

But it is a 0kb zip-file and after extracting it I get a file with the same name and at the end .cpgz.

**Comment by john171** [comment]
Doesn't work even in latest version.

**Comment by jcatarino** [comment]
I think this still doesnt work...

**Comment by bkraul** [comment]
Same here with latest docker develop image.

**Comment by engelgabriel** [comment]
Guys, can you please test this with version 2.0.0 ?

**Comment by bkraul** [comment]
Getting this with 2.1.0-develop, commit 72aaeb3201 which is after the commit that addressed the download.
```
TypeError: Cannot read property 'username' of undefined
    at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
    at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by raziel900** [comment]
> Getting this with 2.1.0-develop, commit [72aaeb3](https://github.com/RocketChat/Rocket.Chat/commit/72aaeb3201f42c8e47c1c54085828b516e8343c9) which is after the commit that addressed the download.
> 
> ```
> TypeError: Cannot read property 'username' of undefined
>     at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
>     at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
> ```

Same here on 2.1.0 (not develop)

**Comment by bbrauns** [comment]
Getting the same with docker image: `rocketchat/rocket.chat:2.1.1`:

```
 TypeError: Cannot read property 'username' of undefined
Oct 24 17:28:00 chat rocketchat_app2_1[2683]:     at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
Oct 24 17:28:00 chat rocketchat_app2_1[2683]:     at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
Oct 24 17:28:00 chat rocketchat_app2_1[2683]:     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

```

**Comment by charlyrock** [comment]
We are testing the function "Download my Data". Yesterday it works and I get a E-Mail to download the data. After that and today I would to export the data again, because there are many new conversations, that would I save.
Then I click on "Download My Data" I get the message: "Your data file was already generated. Click here to download it."
Then I click on the link I get the data from yesterday again but no new data. How can I get new data?

Version of RocketChat: 3.4.0
