### ISSUE TITLE
[BUG] List of channels sorts automatically on new messages

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11088]
### Description:

**Version:** 0.66.0-develop
**Server:** open.rocket.chat

The list of favorited rooms is sorting automatically on new messages even when the sorting is alphabetically.

Here's a GIF that demonstrates it:

![2018-06-11 12 59 36](https://user-images.githubusercontent.com/551004/41243109-bc21b96c-6d77-11e8-8bb3-e18f437eb831.gif)

**Comment by ggazzo** [comment]
the bug is just on favorite group with direct messages ordering by asc :)
> "even when the sorting is alphabetically"
