### ISSUE TITLE
[BUG] Unable to search for members with dot character on users.list REST API

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat#11092]
### Description:

**Version**: 0.66.0-develop
**Server**: open.rocket.chat

If I search for a username that has the dot (`.`) character on it, the users.list REST API does not return the user.
Just try to search for `filipe.brito` or `marcos.defendi`- the API doesn't work

**Comment by rafaelks** [comment]
@filipedelimabrito I think this is related to the `regex` being used to the search. Not sure how we should deal with it. @MarcosSpessatto Can you take a look please?

**Comment by filipedelimabrito** [comment]
End up using the `spotlight` endpoint that works fine with `.` character. But it's still a valid question.

**Comment by MarcosSpessatto** [comment]
@rafaelks Yes, this is related to the `regex`, to search using `regex`, you must escape the dot, like this `filipe\\.brito`.

**Comment by filipedelimabrito** [comment]
Thank you @MarcosSpessatto.
