### ISSUE TITLE
Simple Login with AuthToken

### ISSUE THREAD

**Issue by Ja12n** [RocketChat/Rocket.Chat#11094]
I already generated the authToken for a user with the REST-API.
Is there a simple way of using that token for logging the user in?
For me the easyiest way would be to call a URI like https://rocket.chat/?token=12i93u12u83
Or sending the authtoken via POST. But the only method I can find is using "iFrame Authentication". I think this would be an overkill.

Am I missing something? My current software does not use javascript and I would like to keep SSO simple.

In case this feature is missing I am suggesting to integrate a login method by authtoken encoded in URI i.e. https://rocket.chat/?token=12i93u12u83

**Comment by uncledent** [comment]
You can set your token and userid to the request header: X-Auth-Token for the token and X-User-Id for user id

**Comment by TwizzyDizzy** [comment]
Please use the [forums](https://forums.rocket.chat/) for such questions, as this is not Rocket.Chat bug!

Cheers (+close)
Thomas

**Comment by ltworf** [comment]
I'd say it's a documentation bug.

Apparently on some update my working websocket client stopped working… It'd be nice to have proper documentation about this.
