### ISSUE TITLE
[BUG] Users without username on users.list REST API

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat#11091]
### Description:

**Version**: 0.66.0-develop
**Server**: open.rocket.chat

Some users are being returned without a username when using the `users.list` REST API. 
Searching for `fili` for example, you'll see that the user `filipedelimabrito` hasn't username (that's incorrect).

Here is an image showing that:

<img width="966" alt="screen shot 2018-06-07 at 17 13 53" src="https://user-images.githubusercontent.com/11776825/41248896-c1295350-6d88-11e8-99ce-b592a3b4629c.png">

**Comment by sampaiodiego** [comment]
hi @filipedelimabrito .. this is not a bug, the user `filipedelimabrito` does not have an username set.

this might happen due to our two step register process:

- first you register with an email and a password
- after that you can set your username

so the user can leave at this point and not set an username at all. leaving an user without username on the database.

**Comment by sampaiodiego** [comment]
they are not the same users.. as you can see the *name* of the user on REST response is `felipedelimabrito` .. this is his *name*, not his *username*.. so this is not the same user as you logged in..

**Comment by sampaiodiego** [comment]
another thing you can check is the user `_id`.. check the `_id` of the user you logged in.. you can open chrome dev tools and type: `Meteor.userId()` .. you'll see it is different from the one return on REST call

**Comment by filipedelimabrito** [comment]
@sampaiodiego There is nothing related to `felipedelimabrito` on the REST result. As you can see, I searched for `filipedelimabrito` and logged in the server with the user `filipedelimabrito` too. Also, give I try searching on our server for `felipedelimabrito`, this users does not exist (until now :D).

Where did you see the `fe...` instead of `fi...`? 🤔

**Comment by filipedelimabrito** [comment]
@sampaiodiego Also, I'm unable to get the id using the `Meteor.userId()` as proposed by you. Take a look: 

<img width="417" alt="screen shot 2018-06-12 at 14 25 01" src="https://user-images.githubusercontent.com/11776825/41306433-84bb6b8c-6e4c-11e8-900d-2954c2da3c3c.png">

Is it that I really should do? Doesn't work.

**Comment by filipedelimabrito** [comment]
@sampaiodiego I used our [Kotlin.SDK](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK) to get the user id for `filipedelimabrito` and it is `8WCaFa2Jve4FNjMYa` that is different from the response. By the way, why it is showing another id from the response, since there is only a username set up as `filipedelimabrito`?

I know that user can have identical names, but searching for `filipedelimabrito` should show my user, with my username and the others fields. You can see, from the search that the result comes with one user only, so another bug?

**Comment by filipedelimabrito** [comment]
Yep! And if you are creating a channel and wants to add the user on it (searching for the user first), then it is better to user the `spotlight` or even the `directory` endpoint.

That's it!
