### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#1110]
Hi devs,

we try to install rocket on a Ubuntu system, but

```meteor build --server "$HOST" --directory .``` fails with

```
Errors prevented bundling:
While processing files with templating (for target web.browser):
bundle/programs/web.browser/app/fonts/fontello.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
bundle/programs/web.browser/head.html:1: Expected one of: <body>, <head>, <template>
```

Using git version a56e7b85ba767d7cfc41509ee006125c53515421

Any hints would be highly appreciated!

Thanks!
Steve

**Comment by emcguinness** [comment]
That looks a lot like the error you get if you try and build the app twice, is there a chance you have already run the build command? you should be able to carry on, do the NPM install if you have not already and then use pm2 to start it. If that last sentance made no sense look at the guide [here](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker#3-download-rocketchat), the meteor build part is about half way through step 3 there so should just be able to continue on from there and finish.

**Comment by gmsecrieru** [comment]
@miscs can you confirm this is still an issue to you?

**Comment by hameno** [comment]
We switched to the docker deployment type.

**Comment by gmsecrieru** [comment]
In that case I will close this one. Feel free to report back should the need arise :)
