### ISSUE TITLE
Server is ignoring ROOT_URL env var after updating Site_URL via modal in RC

### ISSUE THREAD

**Issue by edzillion** [RocketChat/Rocket.Chat#11101]
### Description:

Found while trying to get hubot working with latest. at first hubot connected fine. When logging into RC from a URL that is different from the current ROOT_URL a modal pops up and prompts you to update the `Site_URL` which seems to be ROOT_URL (these should be homogenised).

After this point it is not possible to change the ROOT_URL when starting RC, or connect hubot.
...

### Steps to reproduce:

1. `docker run -e ROOT_URL=http://www.ORIGINAL_URL.com rocketchat/rocket.chat:latest`
2. ` rocketchat_1  | ➔ |             Site URL: http://www.ORIGINAL_URL.com  |`
3. open http://www.ORIGINAL_URL.com:3000
4. popup 'You are accessing rocketchat via http://www.ORIGINAL_URL.com:3000 and not *** do you want to update the Site URL?' Click YES
5. docker kill rocketchat_container
6. `docker run -e ROOT_URL=http://www.UPDATED_URL.com rocketchat/rocket.chat:latest`

### Expected behavior:

` rocketchat_1  | ➔ |             Site URL: http://www.UPDATED_URL.com  |`

### Actual behavior:

` rocketchat_1  | ➔ |             Site URL: http://www.ORIGINAL_URL.com  |`

also cannot get hubot-rocketchat to connect at that address.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1 
- Operating System: Windows 10 & Ubuntu 18.04 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: 8.9.3 - x64
- MongoDB Version: 3.0.12

### Additional context

Problem persists even after deleting and reinstalling Mongo and RC. ROOT_URL still wont change, still says previous value??? Whatever is happening here is persisting state somewhere other than there:

https://github.com/RocketChat/Rocket.Chat/blob/401e2e2277138b99e9d5c2578369d2a98c31fb1d/packages/rocketchat-lib/client/lib/settings.js#L63

### Relevant logs:

No errors to show, no logs.

**Comment by engelgabriel** [comment]
Site_URL URL is persisted on the DB, and DB setting have the highest priority agains environment variables.

**Comment by edzillion** [comment]
Yet deleting the db has does not fix this issue.

````
sudo snap remove mongo33
sudo snap install mongo33
docker run -e MONGO_URL=mongodb://localhost:27017 -e ROOT_URL=http://NEW_URL.com
...
rocketchat_1 | ➔ | Site URL: http://www.ORIGINAL_URL.com |
````

I was very confused by this behaviour so I asked a friend, running some linux distro. He did the same, deleted the db, deleted the db folders etc. and then reinstalled and tried again; the URL shown is the one stuck from the original install.

**Comment by geekgonecrazy** [comment]
If you accept the dialog when you access it will keep changing it back every single time. 

If you want to force the Site_Url to be what you pass in via the environment variable:

`OVERWRITE_SETTING_Site_Url=http://www.UPDATED_URL.com` and make sure when you access it, you access at that url.  If you access at: http://www.UPDATED_URL.com:3000 and then accept the changes when it prompts.. its updating it in the DB and you are right back where you started.

A restart will change it back though if you are using the above environment variable

**Comment by edzillion** [comment]
To clarify: In this process I have only ever once accepted the dialog. 

I will try the `OVERWRITE_SETTING_Site_Url` and see what happens. thanks

**Comment by geekgonecrazy** [comment]
Another thing is of course make sure there aren't some how multiple mongo running.  I see snap mentioned there as well as docker.  If you happened to at any point tried the rocketchat-server snap it also has mongo inside.  So could be possible wiping away a different mongo database.  

I've had that happen in local testing and forgot I had rocketchat-server snap running.

**Comment by edzillion** [comment]
I am gonna close this because I wasn't able to recreate again. 

There is one bug here though - surely Site_URL should not include port number? But if you connect via a port it will ask to change Site_URL to include that port.
