### ISSUE TITLE
Files List icon in private channels not visible when user is owner

### ISSUE THREAD

**Issue by wolbernd** [RocketChat/Rocket.Chat#11105]
### Description:

When a user is the **owner** or a **moderator** of a channel (privat and public) the icon for "List files" (paper clip icon) is replaced with the "Add User" icon. The "List files" icon is also not shown in the burger menu. 

### Steps to reproduce:

1. Create a channel or enter an existing private channel you are the owner of
2. upload some files (probably optional)
3. See no "List files" icon on the top right
![noclip](https://user-images.githubusercontent.com/24311754/41295005-b7ea5592-6e59-11e8-9ff5-a867d3e409c1.png)
4. Remove ownership of the channel from your user or enter channel as non-owner user
5. See paper clip icon on top right
![clip](https://user-images.githubusercontent.com/24311754/41294995-b2f5209e-6e59-11e8-86c6-7845a20e8abe.png)

### Expected behavior:
The List files icon moves to the burger menu or is shown directly on top right

### Actual behavior:
The List files icon disappears

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.2
- MongoDB Version: 3.2.7

**Comment by poikilotherm** [comment]
This is also an issue when the user is set as "moderator" of a channel. "leader" is not affected.

**Comment by forkedjensh** [comment]
This issue is also present in public channels.

**Comment by wolbernd** [comment]
Updated description with new info from @poikilotherm and @forkedjensh

**Comment by tmclean-feith** [comment]
This issue is still present in release 0.69.1. Are there any plans to address this? We are looking to go into production with this soon to replace HipChat and this issue is going to be a major pain point for collaboration.
