### ISSUE TITLE
Discord custom oAuth (username field)

### ISSUE THREAD

**Issue by mrsheldon** [RocketChat/Rocket.Chat#11112]
So... I am trying to make "login with discord" button, everything seems to be alright BUT I don't know why to type in "Username field", I tried to search online and nothing... any ideas?

**Comment by kaiiiiiiiii** [comment]
Hi @mrsheldon,

Rocket.Chat does not copy the username from Discord, that’s why you need to enter a username.

Cheers

**Comment by mrsheldon** [comment]
Hmmm wdym?

**Comment by mbrodala** [comment]
@mrsheldon The field `Username field` must be set together with `Identity Path` and `Identity Token Sent Via` if necessary. This is the additional 3rd request that happens (1st being auth code, 2nd access token). With this request RC retrieves the user identity from the custom OAuth2 provider.

In case of Discord `Identity Path` would be [`/users/@me`](https://discordapp.com/developers/docs/resources/user#get-current-user) or similar and the `Username field` would then be `username`.

**Comment by geekgonecrazy** [comment]
Looks like solution provided.  Closing :)
