### ISSUE TITLE
RocketChat icon improperly drawn in left bar

### ISSUE THREAD

**Issue by jirip** [RocketChat/Rocket.Chat#11119]
After update to v2.11.0 there is ugly rocketChat icon duplicates drawn in the left bar. Sometime they flicker and depending on window size there can be more with the same spacing.
I'm running Win10 x64
![capture](https://user-images.githubusercontent.com/3797263/41339268-afacba14-6ef4-11e8-8055-fc4565037cff.PNG)

**Comment by Maqsyo** [comment]
It's the fault of the Electron-App

Duplicate:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/744

Please close this issue
