### ISSUE TITLE
What files do I need to edit to make these changes.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#11110]
Rather than going through every files and doing some trial and error I hoped someone could lead me in the right direction. I need to make the following changes to the interface, what files do I need to edit to do this.

I need to add a "view profile" button on the User Info. I am integrating this into a community site I own and would like to link to their full profile. What file do I edit.

I also would like to have a static list of rooms for users to join that I can organize in the order I would like them organized. I also would like to have a "view rooms" button on the left pane of the chat. Probably just above the rooms they are active in. The view rooms button could simply be the "more rooms" link that used to be on the left pane before the UI redesign. What files would I have to edit for this. The directory is great for searching but I'll be adding a few hundred rooms and I need to have them organized by category for the end user to easily find.

Also as a feature request, I don't see any way to add static rooms that don't have an owner. Am I missing something?

Thank you everyone for your help.

**Comment by kaiiiiiiiii** [comment]
Hi @serviceman,

that's definitely something you should bring up in the Rocket.Chat Forum ([Link](https://forums.rocket.chat/)) or the Open Community Chat ([Link](https://open.rocket.chat/channel/dev)).

The GitHub Issue Tracker is, as it's name says, just for **issues** and the Rocket.Chat Team tries to keep it that way.

Thanks for your understanding,
Kai

**Comment by TwizzyDizzy** [comment]
Closing this, as @kaiiiiiiiii is perfectly right with his assertion.

Cheers
Thomas
