### ISSUE TITLE
Server list shows double ICON on Rocket.chat+ v2.11.0

### ISSUE THREAD

**Issue by mfa777** [RocketChat/Rocket.Chat#11125]
### Description:
After updating Rocket.chat+ PC client to 2.11.0, server list shows double icon of chatting server.

### Steps to reproduce:

1.  uninstall old version.
2. install new version 2.11.0
3. Click 'veiw' -> 'Toogle server list'

### Expected behavior:
Only one icon is showed.

### Actual behavior:
Double icons are showed.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.64.0
- Client Operating System: Windows 10 64bit

### Screenshot
![image.png](https://preview.ibb.co/mcFpLJ/image.png)

**Comment by kaiiiiiiiii** [comment]
This is not a problem with the server component, it’s an Electron client problem.

An issue in the Electron repo is already existent (RocketChat/Rocket.Chat.Electron#744)
