### ISSUE TITLE
automatically move cursor to search field when search button is clicked

### ISSUE THREAD

**Issue by jirip** [RocketChat/Rocket.Chat#11120]
I'm always frustrated when I want to search a conversation. I click the search button, write my query, hit enter, and find out i didn't do any search but send the query as a message instead.

One click on the search button should be enough to search, but in fact you need two, one click on search button and one click to move cursor into the search field.

More intuitive and easy would be similar behavior as when you search in a browser:
you open search
the search field is activated automatically
you can write your search.

**Comment by danieljhochman** [comment]
+1
@rodrigok - any chance of getting this small fix into a near-term release? We have users saying they accidentally send search terms as messages due to this UX bug. 

Thanks!

**Comment by MartinSchoeler** [comment]
Seems to be working in the latest development version, I will be closing this issue, if you face this issue again, please reopen this with updated details. Thanks!

**Comment by reetp** [comment]
Just tried this on open.rocket.cat and it doesn't work as yet :-(
