### ISSUE TITLE
[BUG] Directory sorting by createdAt doesn't work correctly

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11133]
### Description:

When sorting **channels** or **users** by `Created at` option, it returns the results not in this order.

![2018-06-13 15 25 44](https://user-images.githubusercontent.com/551004/41370513-3a45532e-6f1e-11e8-9639-96b71df5bee7.gif)

**Comment by kapace** [comment]
I noticed this problem when sorting by number of users as well: ![image](https://user-images.githubusercontent.com/517992/41551022-67903fb4-72df-11e8-86d6-450191b1116a.png)

**Comment by rafaelks** [comment]
It's also valid to the new layout:

![2018-06-27 09 36 54](https://user-images.githubusercontent.com/551004/41974196-acb08490-79ed-11e8-80ca-f5b6b617c9d5.gif)

**Comment by childnode** [comment]
related to / caused by https://github.com/RocketChat/Rocket.Chat/pull/9972 ?
(part)dup of / related tohttps://github.com/RocketChat/Rocket.Chat/issues/9344 ?
