### ISSUE TITLE
[LAYOUT] Directory label is cutting for channels names and usernames

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11134]
### Description:

![screen shot 2018-06-13 at 15 28 36](https://user-images.githubusercontent.com/551004/41370818-fe3d3fee-6f1e-11e8-8e5b-d7659b814347.png)

![screen shot 2018-06-13 at 15 35 08](https://user-images.githubusercontent.com/551004/41370964-67d4d19c-6f1f-11e8-98b1-79d13cb6eeff.png)

**Comment by ggazzo** [comment]
thanks @rafaelks but we are working on a new directory style I think we will have this problem no more
https://github.com/RocketChat/Rocket.Chat/pull/11026
