### ISSUE TITLE
LiveChat with Guest Pool Routing no popup notification at end user.  Only a sound based Ding

### ISSUE THREAD

**Issue by earlgrei** [RocketChat/Rocket.Chat#11137]
### Description:

We deployed LiveChat to our site, as part of the testing when an incoming chat request is made the Agents desktop application 'Dings' but does not create a Toast style notification (all windows agents).  The audible ding is there so the desktop client knows that something is occurring but not what it is.  I have modified notification settings for the user as well and that has not caused the popup to work.

### Steps to reproduce:

1. Create LiveChat with GuestPool enabled.
2. Login to desktop client as agent.
3. Create Web Chat request from chat applet on webpage.
4.  Chat shows up in list, but not popup notification occurs.

### Expected behavior:

Expect a visual alert to popup as a Toast style notification so if agent is on the phone they notice that the chat has started.

### Actual behavior:

Incoming Livechat with no toast notification.
![image](https://user-images.githubusercontent.com/1480392/41375475-d77998ba-6f1b-11e8-991b-f84f38e75306.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Docker
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.9.3
- MongoDB Version: what comes with the docker container

**Comment by mrsimpson** [comment]
We also noted this issue. I fixed it recently in our fork, but I did this directly in the core-files. Following a decoupled architecture, it should actually be implemented inside the `rocketchat-livechat`-package.
However, this would mean a lot of redundant code.

@renatobecker once you tackle this, you could however take this as "inspiration"
https://github.com/assistify/Rocket.Chat/blob/36ccd576257bbf03f5858fdd1317e86a1c3be6ec/packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js#L286-L316

All related changes are within the above file and [this one liner](https://github.com/assistify/Rocket.Chat/commit/36ccd576257bbf03f5858fdd1317e86a1c3be6ec#diff-13b6a4d2d4a9a0759e8f93916c077486R37), at least as far as I remember.

@renatobecker @sampaiodiego Just in case you think this fix is a good one, let me know - I'll package a PR then.

**Comment by sampaiodiego** [comment]
@mrsimpson I've found this PR https://github.com/RocketChat/Rocket.Chat/pull/10588/ which should fix this issue, right? @renatobecker do you mind taking a look on that PR? thx

**Comment by renatobecker** [comment]
Hi @sampaiodiego and @mrsimpson! 
I'm going to take a look at that PR mentioned above and I'll notify you guys as soon as I finish this process.

Thanks!

**Comment by earlgrei** [comment]
Thank you to all of you that are addressing this. I am about to throttle my end users.  I built a monitor script that pings a raspberry pi (speakers make a noise) to notify them of incoming chats just to keep them happy while the issue gets resolved.  Still they complain LOL.

**Comment by mrsimpson** [comment]
@earlgrei if you run a custom installation, you might want to fork for a short-term work-around and pull the two files from #10588

**Comment by sampaiodiego** [comment]
fixed by #10588
