### ISSUE TITLE
On desktop app, groups with large messages are slow

### ISSUE THREAD

**Issue by undr3ad** [RocketChat/Rocket.Chat#11130]
I have some groups with external reports through hooks. In these groups is common messages with 15000+ characters, and it looks to be slowing down the app when interacting with these groups.

**Comment by hupptechnologies** [comment]
Yes we are facing the same issue.

**Comment by tassoevan** [comment]
**If it doesn't happen accessing Rocket.Chat on web browser**, this issue is related to the desktop client. Please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
