### ISSUE TITLE
[rocketchat:markdown] Open links in new tab/window?

### ISSUE THREAD

**Issue by gmsecrieru** [RocketChat/Rocket.Chat#1113]
I know there's a lot of UX debate related to opening links in new windows or not, but since we are displaying them inside a chat application I believe this should be an expected behavior.

**Comment by liamdawson** [comment]
I was looking to pick this up, but it looks like it's already been done?

![image](https://cloud.githubusercontent.com/assets/760143/10558932/68f33c58-7526-11e5-8359-27aef90ba3e5.png)

**Comment by gmsecrieru** [comment]
@liamdawson I don't think so! Look like you are running a very outdated source code :) Pull a fresh copy and ping me if you need assistance.

**Comment by liamdawson** [comment]
@gmsecrieru — I'm running commit 2a9c00b07bf16c2118302fda272de059b9d62e5c committed 16 hours ago... should I be on a different branch?

**Comment by gmsecrieru** [comment]
From the screen shot you sent looks there are some differences, e.g:

- Markdown is not really enabled on your end, otherwise you should see something like this:
![screen shot 2015-10-17 at 10 32 55](https://cloud.githubusercontent.com/assets/190883/10558955/921e6718-74ba-11e5-800e-c2a67a75da88.png)

- RocketChat`s logo on the right sideNav looks differente from what we have on `master`: 
![screen shot 2015-10-17 at 10 35 18](https://cloud.githubusercontent.com/assets/190883/10558961/cc53e264-74ba-11e5-968f-60e997bc96e5.png)

**Comment by liamdawson** [comment]
@gmsecrieru Okay, I forked this repo to https://github.com/liamdawson/Rocket.Chat and then followed the dev instructions against that (clone, `meteor`), and that's what I end up with. Am I missing something? Master branch, just pulled the latest commit, still no markdown, still the same logo.

**Comment by gmsecrieru** [comment]
@liamdawson Please reach me on our [Demo Server](https://demo.rocket.chat) and I will be glad to walk you through this! :)
