### ISSUE TITLE
No permission policy available to access getRoomIdByNameOrId() when not a member

### ISSUE THREAD

**Issue by lhhong** [RocketChat/Rocket.Chat#11131]
### Description:

I was trying to get an "admin" bot to join a private room and subscribe to messages. I am using driver.joinRooms() method from Rocket.Chat.js.SDK. The call failed when accessing getRoomIdByNameOrId(). This is done with [add-user-to-any-p-room] permission enabled for this user, which should allow any user to be added to a room. This (although still fix in progress #11010) however, does not enable the user to retrieve details and also to join the room for subscriptions, as performed in the js SDK. Either let this permission be inclusive of such cases or create new permissions to allow this operation. 

### Steps to reproduce:

1. Enable [add-user-to-any-p-room] permissions for admin
1. Create a private room "test" as a regular user
2. Login from Rocket.Chat.js.SDK as an admin user `driver.login({username: 'admin', password: 'pass'})`
3. Perform `driver.joinRoom('test')`

### Expected behavior:

To be able to join the group while admin is not a member

### Actual behavior:

Error returned from server

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- External SDK used: @rocket.chat/sdk@0.2.2 (npm)

### Relevant logs:

```
[getRoomIdByNameOrId] Calling (caching): test
[getRoomIdByNameOrId] Error: { isClientSafe: true,
  error: 'error-not-allowed',
  reason: 'Not allowed',
  details: { method: 'getRoomIdByNameOrId' },
  message: 'Not allowed [error-not-allowed]',
  errorType: 'Meteor.Error' }
```

**Comment by timkinnane** [comment]
Duplicated by #11552 - Please comment there.
