### ISSUE TITLE
problem to build for architecture=os.linux.x86_64

### ISSUE THREAD

**Issue by solo999** [RocketChat/Rocket.Chat#1114]
After one of the latest 756cacf73cbfc2896a928ffc93659f657a37c591 commit merge into my fork, I've got a problem to build for architecture=os.linux.x86_64:

    meteor build ../demo-chat_bld --server=https://demo.domain.chat --architecture=os.linux.x86_64
    
    rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...
    rocketchat:ldap: updating npm dependencies -- ldapjs...
    steffo:meteor-accounts-saml: updating npm dependencies -- xml2js, xml-crypto, xmldom, connect, xmlbuilder, querystring,
    xml-encryption...
    Errors prevented bundling:                    
    While linking the program:                    
    error: rocketchat:ldap is not compatible with architecture 'os.linux.x86_64'

**Comment by geekgonecrazy** [comment]
@RocketChat/owners anyone have any idea about 64bit and the ldap package?

@solo999 does it succeed with 32bit?  This maybe a limitation, and honestly i'm not sure you're going to see any benefits of using 64bit anyways.

**Comment by solo999** [comment]
It had succeed when I merged b179ad35efdc9fbe52bbc5f0b2b01d0fbcff0025 commit and before...
So the problem begins today after 756cacf73cbfc2896a928ffc93659f657a37c591 commit.

**Comment by Sing-Li** [comment]
This may be related to the elusive npmshrinkwrap problem we had for ages.  

@solo999  - please check your npm version. And let us know.

**Comment by solo999** [comment]
it's 2.10.1

**Comment by Sing-Li** [comment]
@solo999  What sort of machine, OS, and VM / VPS are you building on?

**Comment by solo999** [comment]
Mac OS 10.9.5
I had to delete ldap package to fix the problem and to be able to merge with the latest master branch from Rocket.Chat

**Comment by Sing-Li** [comment]
Cool.  So here is the story.  Your system will build with --architecture=os.osx.x86_64 with no problem.

Your system does not have the cross compiler support for 'os.linux.x86_64' (but might for os.linux.x86_32).

Our commits may or may not contain hard binary requirement for (os.osx.x86_64, os.linux.x86_64, os.linux.x86_32) depending on who last commits [and what system they're on].   Because we use npmshrinkwrap - specifically in the ldap module.

**Comment by engelgabriel** [comment]
Should we git ignore npmshrinkwrap ?

**Comment by Sing-Li** [comment]
The npmshrinkwrap docs says 'no'  wrt floating the shrink-wrapped dependencies.    Perhaps the ldap stack has not been tested with all variants?   idk why it has to have a binary dependency ... maybe low level bit packing or encryption related.  :disappointed:

**Comment by solo999** [comment]
I can confirm that the problem has disappeared after merging 7f4397eee1d5ce416f1731d1769f2b81f5c5c026 commit.
Although I got another error about building Cordova app for platform Android (probably it should be moved to another thread):

    => Errors executing Cordova commands:         
                                              
    While building Cordova app for platform Android:
    Error: /Users/vb/Sites/RocketChat/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit
    code 8 Error output:

    /Users/vb/Sites/RocketChat/.meteor/local/cordova-build/platforms/android/src/com/adobe/phonegap/push/GCMIntentService.java:483:
    error: cannot find symbol
    mBuilder.setColor(iconColor);
    ^
    symbol:   method setColor(int)
    location: variable mBuilder of type Builder
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 error
   
    FAILURE: Build failed with an exception.
   
    * What went wrong:
    Execution failed for task ':compileReleaseJava'.
    > Compilation failed; see the compiler error output for details.
   
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   

    /Users/vb/Sites/RocketChat/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
    throw e;
    ^
    Error code 1 for command: /Users/vb/Sites/RocketChat/.meteor/local/cordova-build/platforms/android/gradlew with args:
    cdvBuildRelease,-b,/Users/vb/Sites/RocketChat/.meteor/local/cordova-build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
    at ChildProcess.whenDone
    (/Users/vb/.meteor/packages/meteor-tool/.1.1.9.1uwo8qg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by solo999** [comment]
Update: the commit that causes above Android build problem is e83ee600e0c51faf6b3761a5f8f36d7f28f5a35a

**Comment by jalagrange** [comment]
Hi Solo, I just tried to build Rocket chat in order to deploy to AWS in Linux Ubuntu 64 bit arquitecture and I am getting this same error that was solved after that merge:

Errors prevented bundling:                    
While linking the program:                    
error: rocketchat:ldap is not compatible with architecture 'os.linux.x86_64'

Any ideas?

**Comment by geekgonecrazy** [comment]
@jalagrange it sounds like you are doing a meteor build.  Have your tried using one of our built releases?  We recommend going that route.  

https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

**Comment by jalagrange** [comment]
Hi @geekgonecrazy I was indeed doing a meteor build. However I managed to get it to work by building directly on my Amazon instance. I can't actually explain why, but it works. Some weird binary dependency.
