### ISSUE TITLE
Exception in defer callback: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by consi** [RocketChat/Rocket.Chat#11144]
### Description:

Rocket.Chat periodically shows stack trace like this:
node[28740]: Exception in defer callback: RangeError: Maximum call stack size exceeded
node[28740]:     at appendToResult (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1390:14)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1396:5
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1396:20
node[28740]:     at doc (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:987:32)
node[28740]:     at match.result.subMatchers.every.fn (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:902:25)
node[28740]:     at Array.every (<anonymous>:null:null)
node[28740]:     at Matcher.docOrBranches [as _docMatcher] (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:901:32)
node[28740]:     at Matcher.documentMatches (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:4262:17)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2635:48
node[28740]:     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
node[28740]:     at OplogObserveDriver._handleDoc (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2634:12)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3104:14
node[28740]:     at _IdMap.forEach (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/id-map.js:82:35)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3103:18
node[28740]:     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
node[28740]:     at OplogObserveDriver._publishNewResults (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3081:12)
node[28740]:     at OplogObserveDriver._runQuery (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2995:10)
node[28740]:     at OplogObserveDriver._runInitialQuery (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2892:10)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2442:10
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2286:9
node[28740]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
node[28740]:     at packages/meteor.js:502:25
node[28740]:     at runWithEnvironment (packages/meteor.js:1238:24)

And after some time it really slows down, then it dies completly often with segfault:
[8033098.966978] traps: node[23448] general protection ip:32709fed5408 sp:7f62dd67da28 error:0
[8033158.108876] traps: node[23656] general protection ip:369fdf8d5408 sp:7f3304fbaa28 error:0
[8033222.324529] traps: node[23802] general protection ip:d3048655408 sp:7fbda82d7a28 error:0
[8033282.701164] traps: node[23965] general protection ip:2eb066955408 sp:7f30642a9a28 error:0
[8033347.022630] traps: node[24122] general protection ip:3e49e0755408 sp:7f1eb466ea28 error:0
[8033411.376130] traps: node[24283] general protection ip:294963dd5408 sp:7f05345a5a28 error:0
[8033455.664165] traps: node[24464] general protection ip:21f2ba7d5408 sp:7f65bc17da28 error:0
[8033530.058504] traps: node[24592] general protection ip:83488bd5408 sp:7f6add789a28 error:0
[8033574.525964] traps: node[24774] general protection ip:2f744e155408 sp:7f32396aaa28 error:0
[8033648.823347] traps: node[24904] general protection ip:1e7573455408 sp:7fe21033da28 error:0
[8033692.962759] traps: node[25077] general protection ip:2e8aefd5408 sp:7f4f690d3a28 error:0
[8034191.743774] traps: node[26995] general protection ip:372bae3d5408 sp:7f8f98194a28 error:0
[8034242.242805] traps: node[27118] general protection ip:16eabaa55408 sp:7fd18f7fea28 error:0
[8034306.387083] traps: node[27253] general protection ip:c6620cd5408 sp:7f59f028fa28 error:0

I tried different MongoDB (3.2 3.4 3.6) and NodeJS (8.11.1 8.9.4 8.9.3 8.9.2) versions but it does not help.

### Steps to reproduce:

1. Start Rocket Chat server and wait.

### Expected behavior:

Stop seeing stacktraces like above.

### Actual behavior:

It just throws stacktrace:
node[28740]: Exception in defer callback: RangeError: Maximum call stack size exceeded
node[28740]:     at appendToResult (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1390:14)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1396:5
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1396:20
node[28740]:     at doc (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:987:32)
node[28740]:     at match.result.subMatchers.every.fn (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:902:25)
node[28740]:     at Array.every (<anonymous>:null:null)
node[28740]:     at Matcher.docOrBranches [as _docMatcher] (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:901:32)
node[28740]:     at Matcher.documentMatches (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:4262:17)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2635:48
node[28740]:     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
node[28740]:     at OplogObserveDriver._handleDoc (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2634:12)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3104:14
node[28740]:     at _IdMap.forEach (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/id-map.js:82:35)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3103:18
node[28740]:     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)
node[28740]:     at OplogObserveDriver._publishNewResults (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3081:12)
node[28740]:     at OplogObserveDriver._runQuery (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2995:10)
node[28740]:     at OplogObserveDriver._runInitialQuery (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2892:10)
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2442:10
node[28740]:     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2286:9
node[28740]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
node[28740]:     at packages/meteor.js:502:25
node[28740]:     at runWithEnvironment (packages/meteor.js:1238:24)

And often it segfaults.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Debian 9.4 / fully updated
- Deployment Method: tar extracted to rocketchat user + systemd unit
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 8.11.1, 8.9.4, 8.9.3, 8.9.2 (all of them tested)
- MongoDB Version: 3.2, 3.4, 3.6 (all of them tested)

### Additional context

None.

### Relevant logs:

[34mI20180614-07:52:08.596(2) Exception in defer callback: RangeError: Maximum call stack size exceeded     at appendToResult (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1390:14)     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1396:5     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:1396:20     at doc (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:987:32)     at match.result.subMatchers.every.fn (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:902:25)     at Array.every (<anonymous>:null:null)     at Matcher.docOrBranches [as _docMatcher] (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:901:32)     at Matcher.documentMatches (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/minimongo.js:4262:17)     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2635:48     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)     at OplogObserveDriver._handleDoc (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2634:12)     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3104:14     at _IdMap.forEach (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/id-map.js:82:35)     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3103:18     at Object.Meteor._noYieldsAllowed (packages/meteor.js:730:12)     at OplogObserveDriver._publishNewResults (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:3081:12)     at OplogObserveDriver._runQuery (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2995:10)     at OplogObserveDriver._runInitialQuery (/home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2892:10)     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2442:10     at /home/rocketchat/rocket.chat-0.65.1/programs/server/packages/mongo.js:2286:9     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at packages/meteor.js:502:25     at runWithEnvironment (packages/meteor.js:1238:24)

**Comment by consi** [comment]
Okay, I've fixed it myself.
That was this problem: https://github.com/meteor/meteor/issues/8084 and it was probably related to my CAS SSO setup. Clearing session tokens made rocketchat more snappy and less resource hungry :-)!

**Comment by consi** [comment]
For future this command fixed the issue - but remember that it will logout all users:

```
db.users.update({}, {$set: {"services.resume.loginTokens": []}}, {multi: true});
```

**Comment by adrianovieira** [comment]
Hi!

This also is happening here on my on-premise implementation.

What coul'd I do to fix it?

```
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ System ➔ startup
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ +-------------------------------------------------+
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |                  SERVER RUNNING                 |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ +-------------------------------------------------+
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |                                                 |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |  Rocket.Chat Version: 0.74.3                    |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |       NodeJS Version: 8.11.4 - x64              |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |             Platform: linux                     |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |         Process Port: 3000                      |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |             Site URL: https://chat.local/       |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |     ReplicaSet OpLog: Disabled                  |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |          Commit Hash: 202a465f1c                |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |        Commit Branch: HEAD                      |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ |                                                 |
    Apr 18 13:09:17 rkt-server.local rocketchat: ➔ +-------------------------------------------------+
    Apr 18 13:10:41 rkt-server.local rocketchat: (node:18168) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    Apr 18 13:10:41 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
    Apr 18 13:10:41 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    [..]
    Apr 18 13:10:42 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:10:42 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
==> Apr 18 13:44:46 rkt-server.local journal: Suppressed 54675 messages from /system.slice/rocketchat.service
    Apr 18 13:44:46 rkt-server.local rocketchat: (node:18168) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    Apr 18 13:44:46 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    [..]
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Array.forEach (<anonymous>)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
    Apr 18 13:44:47 rkt-server.local rocketchat: at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
```

**Comment by jadolg** [comment]
> For future this mongo command fixed the issue - but remember that it will logout all users:
> 
> ```
> db.users.update({}, {$set: {"services.resume.loginTokens": []}}, {multi: true});
> ```

Well, I just tried this and got no modifications:
`WriteResult({ "nMatched" : 0, "nUpserted" : 0, "nModified" : 0 })`

I'm using Rocket.Chat 1.1.0 on Docker

**Comment by fcoppolani** [comment]
Hi,
Thnaks for the help !
FYI, we had the same problem on a 0.69.2 with a API call without logout... The same error + CPU load increasing quickly.

We looked for the logintokens :
`db.users.find({"services.resume.loginTokens":{$exists:true} , $where : "this.services.resume.loginTokens.length > 1000"})`
And then deleted only what was needed : 
`db.users.update({name:"xxxxxxx"}, {$set: {"services.resume.loginTokens": []}}, {multi: true});`
