### ISSUE TITLE
LDAP REST API

### ISSUE THREAD

**Issue by SnehaDoughnut** [RocketChat/Rocket.Chat#11143]
I am trying to automate LDAP configurations in one of my shell scripts. I am unable to find the REST API relating to it.

**Comment by rafaelks** [comment]
@SnehaDoughnut He's how you do it:

@MartinSchoeler (I think we need to add this to the docs).

```shell
curl -X POST "https://yourhost.com/api/v1/login" -H "Content-Type: application/json" -d '{"ldapPass": "yourpassword", "ldapOptions": [], "ldap": true, "username": "yourusername"}'
```
