### ISSUE TITLE
User IDs still showing as "[user id] is typing..." and elsewhere even with "Use Real Name" setting on

### ISSUE THREAD

**Issue by mydoghasworms** [RocketChat/Rocket.Chat#11145]
### Description:

After setting the "Use Real Name" setting on under Administration > Layout > User Interface, there are still places where the user ID, rather than the name is being displayed:

These include:

* When a user in a channel is typing
* When a user makes changes in a channel, e.g. sets the topic

### Steps to reproduce:

1. Enable the "Use Real Name" setting
2. Note that the user names are now displayed in e.g. mentions and the side panel
3. Make a change in a room, like setting the topic; the room history shows the user ID instead of name
4. When a user in a room is typing, it shows the user ID instead of name

### Expected behavior:

When making the "Use Real Name" setting, it should apply everywhere where user IDs normally appear.

### Actual behavior:

User IDs still show up in various places.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: 4.15.0-23-generic
- Deployment Method: snap
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.2
- MongoDB Version:

**Comment by vynmera** [comment]
Yes!!! My team has generated usernames that don't correlate to people's real names, so typing indicators are just a bit confusing unless you know what their username is.

**Comment by mydoghasworms** [comment]
Also just found out that when you reply on a message, even though on the original message it shows the user name, on the reply it will show the user ID.

**Comment by vynmera** [comment]
Part 1, I suppose - the one causing the most confusion for most people with random usernames. Enjoy: #11164

**Comment by GJKrupa** [comment]
We're seeing something similar when replying in a message thread.  When a user first sends a reply it shows as Real Name but after refreshing the browser it reverts to User ID.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
