### ISSUE TITLE
#general keeps getting recreated.

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#11148]
That's an information leak I want to get rid of since it auto-joins every user there. I keep deleting it...

**Comment by vynmera** [comment]
@kaiiiiiiiii Possibly also a dupe of #7692 and #10182~

**Comment by kaiiiiiiiii** [comment]
@vynmera Yipp, those are dupes as well. @TwizzyDizzy We should keep #3870 and close all the others :)

**Comment by Hudell** [comment]
Duplicate of #3870
