### ISSUE TITLE
Error with File Upload via Amazon S3

### ISSUE THREAD

**Issue by nicexe2e4** [RocketChat/Rocket.Chat#11158]
### Description:
Hello, i configured my rocketchat instance for file upload via Amazon S3 and my files won't load, but gridFS nd File System work well.

My settings:

- Acl                                           **none**
- Access Key                                  **mykey**
- Secret Key                                **mysecretkey**
- CDN Domain for Downloads   **none**
- Region                                    **us-east-1**
- Bucket URL                             **https://s3.example.com/**
- Signature Version                    **v4**
- Force Path Style                      **True**
- URLs Expiration Timespan      **120**
- Proxy Avatars                          **False**
- Proxy Uploads                         **False**

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: 4.15.15
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 8.11.2
- MongoDB Version: 3.6.3

### Relevant logs:
After try upload file:
```
Error: FileNotFound: no file with id L5dGabZPZXNRuyTYZ found
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
    at handleCallback (/home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Error: FileNotFound: no file with id xTjh98GoWkRethHwW found
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
    at handleCallback (/home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
    at /home/rocketchat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
Сan anyone help me?

**Comment by nicexe2e4** [comment]
The issue is not relevant.
Workaround:
1) switch storage sype to GridFS
2) remove files from mongoDB
3) switch storage typy to Amazon S3

I don't know how, but it helped me.

**Comment by shahar3012** [comment]
If that's the case Rocket.Chat should support also the old files stored in MongoDB GridFS.
