### ISSUE TITLE
Broken Server Menus - Blank Chats - Freezing

### ISSUE THREAD

**Issue by dontbesalty** [RocketChat/Rocket.Chat#11153]
### Description:

Office of 40+ using Rocket.Chat. Only one user has this issue. Server List is showing duplicates of Rocket.Chat server.

![clipboard - june 14 2018 5-25 pm](https://user-images.githubusercontent.com/2824229/41440038-02be04fe-6ffb-11e8-85d7-1fea5201dc6f.png)

Unable to reproduce on other PCs

**Comment by monspid** [comment]
We have the same problem with server version 0.64.1.
![rc](https://user-images.githubusercontent.com/18348137/41459984-7a929d92-708b-11e8-8463-f644c6d434b4.png)

**Comment by kaiiiiiiiii** [comment]
This is not a problem with the server component, it’s an Electron client problem.

An issue in the Electron repo is already existent (RocketChat/Rocket.Chat.Electron#744)

//CC: @TwizzyDizzy
