### ISSUE TITLE
[BUG] /api/v1/users.updateOwnBasicInfo not working properly

### ISSUE THREAD

**Issue by filipealva** [RocketChat/Rocket.Chat#11154]
When trying to set a username for a new user on a server with `customFields` enabled the API is returning the following response:

```
[REST][RESULT][https://rafaelks.rocket.chat/api/v1/users.updateOwnBasicInfo]: {
  "error" : "Cannot read property 'role' of undefined",
  "success" : false
}.
```

The problem is: It says that the request has failed (`success: false`) but it's a false positive because the username is actually set, so the request has updated the user info and so it was successful.

**Comment by sampaiodiego** [comment]
what are the `customFields` configured?

**Comment by rafaelks** [comment]
This is what happens, when trying to signup in any client with custom fields and setting a username (there's no way to signup with one API, we need to use two):

![simulator screen shot - iphone se - 2018-06-15 at 13 07 16](https://user-images.githubusercontent.com/551004/41478237-4e5e83a0-709d-11e8-8d39-559eac839959.png)

**Comment by sampaiodiego** [comment]
@filipealva can you please post the JSON used to configure the custom fields?

also can you send the exactly request payloads and responses? thx

**Comment by rafaelks** [comment]
@sampaiodiego 

```
{
    "role": {
        "type": "select",
        "defaultValue": "student",
        "options": ["teacher", "student"],
        "required": true,
        "modifyRecordField": {
            "array": true,
            "field": "roles"
        }
    },
    "twitter": {
        "type": "text",
        "required": true,
        "minLength": 2,
        "maxLength": 10
    }
}
```

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/11204
