### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by jonS90** [RocketChat/Rocket.Chat#1115]
We've had a server running for 2 days. Notifications worked on day 1, but seem to have stopped on day 2 now.

It looks like every time I'm *supposed* to get a notification, I get this in the browser console:

![error](https://dl.dropboxusercontent.com/u/1780553/imgs/GitHub/rocket%20chat%20console%20error.png)

Nothing in the server logs looks very interesting.

**Comment by geekgonecrazy** [comment]
Did you recently update to a newer version of code?  What changed?

**Comment by jonS90** [comment]
I just now got them working by changing ROOT_URL to use the domain name instead of the actual IP. If I navigate my browser to the domain name, notifications work. If I navigate my browser to the IP, I get the console error above and no notifications.

FYI, I updated once yesterday. Our HEAD is at 7aa2b404de9bf6193b820f87faadd76e3f6b27fd. 

This might be just be user error...

**Comment by geekgonecrazy** [comment]
@jonS90 yeah ROOT_URL will get you... We're trying to work on simplifying this so it can be set via UI and a little more user friendly.

It sounds like a cross domain issue.
