### ISSUE TITLE
Rocket.Chat not working on  iOS 9.x

### ISSUE THREAD

**Issue by whatch0ut** [RocketChat/Rocket.Chat#11159]
Rocket.Chat Version: 0.65.1
iOS Version: 9.3.5

I've been updated rocket.chat server on newer version (manual on Debian) and notice one problem that I couldn't connect to my rocket via any of browsers, neither apps. I was updated from 0.54.1 where iOS worked perfectly.
When I want to connect to my server i can Login, but next thing what I see is just background colour with no info on it.

**Comment by rafaelks** [comment]
@whatch0ut What's the iOS app you're trying to use?

**Comment by whatch0ut** [comment]
I used Rocket.chat legacy, because rocket.chat+ can't be installed due to requires 10+ iOS, but it doesn't work with any browsers, neither safari or chrome

**Comment by ggazzo** [comment]
@whatch0ut hey, could you check if this pr solves your problem? #11199
