### ISSUE TITLE
Form validation error caused by @ symbol in username

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#11168]
### Description:

Unfortunately our usernames have the form user@company.com which causes a from validation error in RC when trying to edit a profile. Our users are signing in via Azure AD and RC successfully creates the account with the @ symbol in the username but it's not possible to modify the users profile afterwards.

### Steps to reproduce:

1. Create a user with an @ symbol in the username
2. Change any user property in the profile page but the save button stays disabled

### Expected behavior:

@ symbol doesn't cause a form validation error and user can save his profile changes

### Actual behavior:

Save button is disabled due to form validation error

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1

**Comment by vynmera** [comment]
Can you check the allowed username RegEx? I'm not sure whether changing it will allow it, because @ is the username notation character, but it might be possible to allow it in that regex?

**Comment by subesokun** [comment]
@vynmera nice hint, I'll try that on Monday!

**Comment by marceloschmidt** [comment]
I've checked and editing the regex works ;) please reopen if it doesn't work for you.

**Comment by subesokun** [comment]
Yep, can confirm that this solved my issue. Thanks a lot @vynmera !
