### ISSUE TITLE
Favicon gone from tab in latest Firefox

### ISSUE THREAD

**Issue by dachnikrus** [RocketChat/Rocket.Chat#11160]
### Description:

In latest firefox version 60.0.2, there are not svg favicon in the tab^, while normal png is ok.

### Steps to reproduce:

1. Enable in settings Assets -> "Enable SVG favicon"
2. Apply and refresh all clients

### Expected behavior:

Show SVG favicon

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Windows 10
- Deployment Method: snap

**Comment by vynmera** [comment]
Noticing this as well. The favicon displays fine when it is a derivative (e.g. you have a notification and it shows a dot or number)

**Comment by dachnikrus** [comment]
@vynmera Thank you for addition! I checked it now, but in my case it shows only red circle with number, while I sent a direct message to test account.

**Comment by vynmera** [comment]
Seems to be broken on Chrome as well :(

**Comment by geekgonecrazy** [comment]
This should be solved now.  Closing
