### ISSUE TITLE
When trying to access the landing page of web rocket chat on mobile android chrome, a blank black screen appears

### ISSUE THREAD

**Issue by FaizanZahid** [RocketChat/Rocket.Chat#11170]
### Steps to reproduce:

1. Open the landing page of rocket chat demo (where we put our login details to sign in).
2. I put my login details and clicked sign in / log in.
3. The 3 progress 3 loading dots animate for few seconds
4. and after that the screen goes blank/black and nothing loads up, no menu is visible.
5. if i refresh, i see the same behavior,

I have also cleared all my mobile android chrome browser, cookies and history, but still no luck. It works fine on mobile firefox browser on android but issue is persistent on chrome.

Please see attached behavior image.

![image](https://user-images.githubusercontent.com/9073066/41503759-d5c3d354-71d3-11e8-8c5d-96f379b1b1dc.png)

URL causing the error on https://chat.talkwithstranger.com

**Comment by geekgonecrazy** [comment]
I assume resolved.  Closing

**Comment by ekariz** [comment]
I have the same problem. After doing setups in admin , when i re open the web portal its blank as shown . Any help @geekgonecrazy geekgonecrazy
