### ISSUE TITLE
"Add user" button doesn't appear in the users list

### ISSUE THREAD

**Issue by ukhryab** [RocketChat/Rocket.Chat#11176]
### Description:

I would like to add a new user, being an admin. When I go to users list, there's no `+` button (and no other buttons too). But it appears when I select one of the users in list. It is not obvious behaviour. 

### Steps to Reproduce:

1. Go to Administration -> Users
see NO buttons at the right side of users list at all! so we can't add a new user

2. Click on the user in the list.
3. Panel w/buttons appears on the right side.

4. Go to any other place.
5. Repeat step 1. Panel is hidden again.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Ubuntu 17.10 artful (x86-64)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: v8.11.2
- MongoDB Version: 3.2-jessie

### Additional context

Web version and RoketChat+ v.2.11.0

**Comment by vynmera** [comment]
This is fixed in 0.65.2: #11049 . Please update :)

**Comment by ukhryab** [comment]
Thank you! :)
