### ISSUE TITLE
Embedding content in the iframe at the chat place.

### ISSUE THREAD

**Issue by nvhk** [RocketChat/Rocket.Chat#11172]
I would like to be able to embed content in the iframe. Content in iframe e.g.: youtube. twich would be in the place of the current chat, and the chat would be moved to the sidebar.

I would like it to look like a twitch, where there is a big stream in the middle, chat in a sidebar so that you can switch between views. 

e.g: channel/general?iframe=LINK

Prepared view as I would like it to look like.
Is such a look possible to do in general?

https://i.imgur.com/4WgYelh.jpg

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
