### ISSUE TITLE
Feature: Add nickname to a user

### ISSUE THREAD

**Issue by TheMMcOfficial** [RocketChat/Rocket.Chat#11189]
**Is your feature request related to a problem? Please describe.**
it's not possible to notify or research someone by a nickname that you add or that they add. We got rocketchat where I work and we are 3 people with the same name so it's difficult to not got a message from someone but the message was deserve to the other person.

**Describe the solution you'd like**
Add a place where we can add a nickname for someone.

**Describe alternatives you've considered**
Add a place where I can create a nickname for myself.

**Additional context**
-

**Comment by marceloschmidt** [comment]
We have places for username and real name. We don't see a new field as a viable option.
