### ISSUE TITLE
Tabnabbing and Clickjacking

### ISSUE THREAD

**Issue by mycatnamedweb** [RocketChat/Rocket.Chat#11185]
https://steemit.com/security/@gaottantacinque/steemit-chat-is-unsafe

**Comment by marceloschmidt** [comment]
Thank you for your report. We kindly ask that any security issue should be raised by mailing Rocket.Chat's security team at `security@rocket.chat`. This issue has been fixed by https://github.com/RocketChat/Rocket.Chat/pull/10929.
