### ISSUE TITLE
When uploading normal pictures to rocketchat they become very large.

### ISSUE THREAD

**Issue by nwd3** [RocketChat/Rocket.Chat#11194]
### Description:

We upgraded to RocketChat version .65.1 and now whenever anyone uploads an image it displays the image in giant form.
### Steps to reproduce:
Upload imgae
### Expected behavior:
Is there a way to have rocketchat set a default size for the image?

### Actual behavior:

![image](https://user-images.githubusercontent.com/17985368/41653388-e7ca7ee0-7453-11e8-980f-500e1250ef0b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: .651
- Operating System: Centos
- Deployment Method:tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: not sure
- MongoDB Version: not sure

**Comment by vynmera** [comment]
#10998 fixes this. Please update to 0.65.2 for it :)

**Comment by nwd3** [comment]
Great I will try this.
Thanks

**Comment by vynmera** [comment]
Is it working for you? If so, please close the issue :)
CC @TwizzyDizzy

**Comment by NatoBoram** [comment]
I can confirm this affects me as well. Is it a server-side bug or a client-side issue?

![image](https://user-images.githubusercontent.com/10495562/43861315-75d6263e-9b24-11e8-892c-a1e99695eb43.png)

**Comment by geekgonecrazy** [comment]
Should be resolved.  Closing
