### ISSUE TITLE
Non-obvious message of changing room type in mobile application

### ISSUE THREAD

**Issue by ukhryab** [RocketChat/Rocket.Chat#11197]
RocketChat+ v 2.11.0 & RocketChat on Android v.2.4.0 (this app: https://play.google.com/store/apps/details?id=chat.rocket.android)

### In desktop app:
![image](https://user-images.githubusercontent.com/16405513/41662758-78b01dba-74aa-11e8-9e9c-a85a1cc046cb.png)

### In mobile app:
![image](https://user-images.githubusercontent.com/16405513/41662785-86ef4234-74aa-11e8-892e-909b370dc1ec.png)

Notification about changing room type in mobile application looks like ordinary message and thus frustrating.

**Comment by ggazzo** [comment]
@rafaelks could you close this issue and open on androi/ios repos? thanks

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.iOS #1803](https://github.com/RocketChat/Rocket.Chat.iOS/issues/1803) via [**ZenHub**](https://www.zenhub.com/)
