### ISSUE TITLE
Artefacts in desktop version

### ISSUE THREAD

**Issue by moriccelli** [RocketChat/Rocket.Chat#11192]
### Description:

Some artefacts appear on desktop version. See steps to reproduce.

### Steps to reproduce:

See [screen record](https://drive.google.com/file/d/1Irsld0tiejCIjb5_O8IyalJVhPsKN4TU/view?usp=sharing)

### Server Setup Information:

desktop client version - 2.11.0
Server version 0.65.1

**Comment by kaiiiiiiiii** [comment]
Wrong repository and duplicate of [#744](https://github.com/RocketChat/Rocket.Chat.Electron/issues/744).

//CC: @TwizzyDizzy

**Comment by moriccelli** [comment]
Thanks
