### ISSUE TITLE
Image auto resize client side

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1120]
We need to automatically resize images of any size to eg 800*600px from the client side.

In phpbb3 if a user uploads a picture of 5MB, this is reduced to 2-300kB, and it is made from the client side (javascript).

This allows to users's mobiles  with cameras HD (13Mpx) to uploading photos without overwhelming the HD of server .

<del>
Another issue related :
If I have 1000 users that every day they upload 2 photos of 3MB , after a year of activity, we have 1TB of photos on the server.
Please add the auto prune of the files uploaded, every X time configurable from the administration control panel .</del>

tnx
##

**Comment by gmsecrieru** [comment]
I understand these might be somewhat related but client-side autoresizing and pruning server files look like different issues to me. Could you please separate accordingly?

**Comment by maxlinux2000** [comment]
done #1133

**Comment by lunitic** [comment]
https://github.com/protonet/cordova-plugin-image-resizer

Could this be added in the Cordova App?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #1988. Please get back to me if you disagree with my assessment.

Cheers
Thomas
