### ISSUE TITLE
When editing a message with a embedded url in it the embedded part of the message remains.

### ISSUE THREAD

**Issue by nwd3** [RocketChat/Rocket.Chat#11217]
I have rocket chat VS .65.1 and I have this issue.  Thanks

**Comment by kaiiiiiiiii** [comment]
Hi @nwd3,

please use the issue template provided when you open a new issue. Otherwise we can't help you with that.

Thanks,
Kai

**Comment by TwizzyDizzy** [comment]
Closing, as you failed to provide the information requested in the issue template.

Cheers (+close)
Thomas
