### ISSUE TITLE
"Marked" Markdown parser interfering with Emoji transformation 

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#11214]
### Description:

When you switch from `Original` to  `Marked` Markdown parser in the administration UI (Messages → Markdown → Markdown Parser), normal text emoticons (like `:)`, `:-(` or `:o`) won't be transformed into their corresponding Emoji counterpart

### Steps to reproduce:

1. Switch to `Marked`
2. Type `:)` 
3. Look at the text emoticon rather than Emoji

### Expected behavior:

Transform text emoticon to Emoji

### Actual behavior:

![bildschirmfoto-2018-06-21-um-16 17](https://user-images.githubusercontent.com/944459/41725069-4127ce7c-756f-11e8-9670-452d3bb0d0b2.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: dockerized
- MongoDB Version: dockerized

**Comment by chefino** [comment]
Running manual install on Ubuntu 20.04, RC version 3.0.12 and issue still persists :-/
Is there some alternative Markdown processor instead of the featureless Original or buggy Marked?

**Comment by dougfabris** [comment]
Closing this stale issue, since it's already been fixed since the new message parser implementation!
