### ISSUE TITLE
[ Feature Request ] Option to hide or disable system messages when topic is changed?

### ISSUE THREAD

**Issue by bazoonchik** [RocketChat/Rocket.Chat#11213]
Is there a way to hide or disable system messages that are sent as soon as a room's topic is changed? That would also be nice to not count such messages, if they are disabled or hidden, in the counters.

Thank you.

**Comment by kaiiiiiiiii** [comment]
Hi @bazoonchik,

the options for hiding system messages can be found under "Administration -> Message".

![2018-06-21 17_31_17-netorium chat](https://user-images.githubusercontent.com/4711233/41729245-0c4db392-7579-11e8-94ed-d68986564f23.png)

Feel free to visit the following site, for any further support request.

https://rocket.chat/docs/getting-support/ (the RocketChat Team tries to use the GitHub Repository only for issues with the code).

Cheers,
Kai

**Comment by bazoonchik** [comment]
Thank you for getting back, @kaiiiiiiiii.

Yes, I have seen this panel, but it's missing an option to hide a system message that indicates that a user has changed room's topic. Usually, there is the following message pops up: Room topic changed to: bla bla bla.

**Comment by bazoonchik** [comment]
So, is it going to be fixed or implemented or anything? No hear in almost two weeks.

**Comment by TwizzyDizzy** [comment]
Pushing this into the feature-request-loop. Beware though: this is, even if accepted, of very low priority as there are far more important features to be implemented and bugs to be fixed.

If anybody would like to send us a PR, of course, we'd be delighted :)

Cheers
Thomas

**Comment by KayzerCode** [comment]
Hello! That will be great if I could HIDE messages in chat flow about pinned messages.
I mean if someone pins any message, in chat appear a system message that "someone pinned message"..
It's not necessary in my case.

**Comment by horstepipe** [comment]
> 
> 
> Hello! That will be great if I could HIDE messages in chat flow about pinned messages.
> I mean if someone pins any message, in chat appear a system message that "someone pinned message"..
> It's not necessary in my case.

+1 for this. 
If you have a channel which only contains guides / tutorials, those "message was pinned" messages are quite annoying. They can't be deleted by an admin, either.

**Comment by hifihedgehog** [comment]
Is this feature actually working?

**Comment by coolfarmer** [comment]
+1 for this too! System message are annoying

**Comment by NishantChandla** [comment]
Can i work on this issue?

**Comment by sachin746** [comment]
i want to work on this issue please someone provide bullet point or guide me how can i solve this issue.i have setup the environment for contribution
