### ISSUE TITLE
Rocketchat-Server Snap stuck in Upgrade/Downgrade limbo - Version 0.63.0 Rev 1245

### ISSUE THREAD

**Issue by AlexanderPlaza** [RocketChat/Rocket.Chat#11220]
Hello,

OS: Ubuntu 16.04.4 LTS
RocketChat Version: 0.63.0 Rev 1245
MongoDB Version 3.2.7
Within LXC Container

I currently have the rocketchat-server snap installed within an lxc container. So far I haven't been having any issues and this has been successfully running for approx. 7 months.

Earlier today I attempted to log into my rocketchat instance and was receiving 502 bad gateway within web browsers. Within Rocketchat Electron Clients just the generic unable to connect error.

Looking at the logs I can see this below.

`root@rocketchat:~# journalctl -u snap.rocketchat-server.rocketchat-server
-- Logs begin at Thu 2018-06-21 15:46:37 UTC, end at Thu 2018-06-21 15:47:27 UTC. --
Jun 21 15:46:40 rocketchat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Jun 21 15:46:48 rocketchat rocketchat-server.rocketchat-server[435]: Mongo is not available, can't start. Waiting 10 seconds and trying again
Jun 21 15:46:58 rocketchat rocketchat-server.rocketchat-server[435]: Checking if oplog has been enabled, and enabling if not
Jun 21 15:46:59 rocketchat rocketchat-server.rocketchat-server[435]: MongoDB shell version: 3.2.7
Jun 21 15:46:59 rocketchat rocketchat-server.rocketchat-server[435]: connecting to: test
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: Will load cache for users
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: 5 records load from users
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: Will load cache for rocketchat_room
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: 35 records load from rocketchat_room
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: Will load cache for rocketchat_subscription
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: 83 records load from rocketchat_subscription
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: Will load cache for rocketchat_settings
Jun 21 15:47:06 rocketchat rocketchat-server.rocketchat-server[435]: 688 records load from rocketchat_settings
Jun 21 15:47:09 rocketchat rocketchat-server.rocketchat-server[435]: Updating process.env.MAIL_URL
Jun 21 15:47:09 rocketchat rocketchat-server.rocketchat-server[435]: Starting Email Intercepter...
Jun 21 15:47:10 rocketchat rocketchat-server.rocketchat-server[435]: Will load cache for rocketchat_permissions
Jun 21 15:47:10 rocketchat rocketchat-server.rocketchat-server[435]: 80 records load from rocketchat_permissions
Jun 21 15:47:10 rocketchat rocketchat-server.rocketchat-server[435]: Will load cache for rocketchat_roles
Jun 21 15:47:10 rocketchat rocketchat-server.rocketchat-server[435]: 11 records load from rocketchat_roles
Jun 21 15:47:12 rocketchat rocketchat-server.rocketchat-server[435]: LocalStore: store created at
Jun 21 15:47:12 rocketchat rocketchat-server.rocketchat-server[435]: LocalStore: store created at
Jun 21 15:47:13 rocketchat rocketchat-server.rocketchat-server[435]: Warning: connect.session() MemoryStore is not
Jun 21 15:47:13 rocketchat rocketchat-server.rocketchat-server[435]: designed for a production environment, as it will leak
Jun 21 15:47:13 rocketchat rocketchat-server.rocketchat-server[435]: memory, and will not scale past a single process.
Jun 21 15:47:13 rocketchat rocketchat-server.rocketchat-server[435]: Setting default file store to GridFS
Jun 21 15:47:13 rocketchat rocketchat-server.rocketchat-server[435]: LocalStore: store created at
Jun 21 15:47:13 rocketchat rocketchat-server.rocketchat-server[435]: LocalStore: store created at
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]: Thu, 21 Jun 2018 15:47:19 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at npm/node_modules/connect/lib/midd
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]: Thu, 21 Jun 2018 15:47:19 GMT connect deprecated limit: Restrict request size at location of read at npm/node_modules/connect/lib/middleware/multipart.js:86:15
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]: Exception in callback of async function: Error: [Can't find migration version 121]
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at Object.Migrations._findIndexByVersion (/snap/rocketchat-server/1245/programs/server/packages/rocketchat_migrations.js:410:9)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at Object.Migrations._migrateTo (/snap/rocketchat-server/1245/programs/server/packages/rocketchat_migrations.js:277:23)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at Object.Migrations.migrateTo (/snap/rocketchat-server/1245/programs/server/packages/rocketchat_migrations.js:206:23)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at xrun.js (/snap/rocketchat-server/1245/programs/server/app/app.js:6545:25)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at fileEvaluate (packages/modules-runtime.js:343:9)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at require (packages/modules-runtime.js:238:16)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at /snap/rocketchat-server/1245/programs/server/app/app.js:11980:1
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at /snap/rocketchat-server/1245/programs/server/boot.js:411:36
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at Array.forEach (<anonymous>:null:null)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at /snap/rocketchat-server/1245/programs/server/boot.js:220:19
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at /snap/rocketchat-server/1245/programs/server/boot.js:471:5
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at Function.run (/snap/rocketchat-server/1245/programs/server/profile.js:510:12)
Jun 21 15:47:19 rocketchat rocketchat-server.rocketchat-server[435]:     at /snap/rocketchat-server/1245/programs/server/boot.js:470:11
`

-----

I have tried to do a snap revert and a refresh. I receive the following errors

`root@rocketchat:~# snap refresh rocketchat-server
error: cannot refresh "rocketchat-server": snap "rocketchat-server" has "auto-refresh" change in
       progress
root@rocketchat:~# snap revert rocketchat-server
error: cannot revert "rocketchat-server": snap "rocketchat-server" has "auto-refresh" change in
       progress
`

-----

Looking at previous github issues, I am unsure how to proceed as other times it was an error with deployment or revision number. Since I haven't made any manual changes I would like some idea how to proceed with fixing this.

**Comment by reetp** [comment]
Is this still an issue? Have you tested with the latest version of Rocket 0.70.x ?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close since no further movement
