### ISSUE TITLE
Prometheus exporter did not start after redeploy (0.66.0-rc.1)

### ISSUE THREAD

**Issue by dbluxo** [RocketChat/Rocket.Chat#11233]
### Description:

Prometheus exporter did not start after redeploy (0.66.0-rc.1).

### Steps to reproduce:

1. Deployed Rocket.Chat 0.66.0-rc.1 for the first time
2. Enabled Prometheus (set true) at webui (settings)
3. Deleted Rocket.Chat  0.66.0-rc.1 for the first time (I left MongoDB alive)
4. Deployed Rocket.Chat 0.66.0-rc.1 for the second time
5. Checked Prometheus webui settings: Prometheus was enabled, but the Prometheus metrics were not available

My workaround:
1. Disable Prometheus via webui (settings)
2. Enable Prometheus via webui (settings)
3. Now Prometheus exporter is started and the metrics are available

### Expected behavior:

Prometheus exporter started

### Actual behavior:

Prometheus exporter not started

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-rc.1
- Operating System: Official docker image (Kubernetes)
- Deployment Method: Kubernetes
- Number of Running Instances: 1
- DB Replicaset Oplog: /
- NodeJS Version: /
- MongoDB Version: 3.6.5

**Comment by geekgonecrazy** [comment]
This should be fixed.  Let us know if otherwise
