### ISSUE TITLE
Snap Caddy SSl Install

### ISSUE THREAD

**Issue by nipunamsi** [RocketChat/Rocket.Chat#11243]
Hi Guys,

I'm having a big issue with installing paid SSL in Snap Caddy.
Anyone has a guide on how it can be done, please.
Having a big issue without SSL iPhone app is not working can someone pls help. 

Thank you,
Nipuna Ruhunage.

**Comment by mixrat** [comment]
Same problem here. I have a Comodo SSL but it looks like there is no way to use it with a snap installation. Is this correct?

**Comment by TwizzyDizzy** [comment]
Please use the [forums](https://forums.rocket.chat/) for such questions, as this is not a Rocket.Chat bug.

Cheers (+close)
Thomas
