### ISSUE TITLE
[BUG] Links with "highlighted" words do not work

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11248]
### Description:

I've `iOS` on my highlighted words on the server, and if the URL has this word, the link doesn't work (only the preview).

![screen shot 2018-06-25 at 10 56 20](https://user-images.githubusercontent.com/551004/41854429-9de262ea-7866-11e8-97bf-ab243b47a999.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-rc.1
- Operating System: Linux

**Comment by himpierre** [comment]
Issue still exists in 0.68.4.

**Comment by Rumpick** [comment]
This is still happening on Linux Client version 2.15.3
