### ISSUE TITLE
OAuth documentation: admin and user level

### ISSUE THREAD

**Issue by andpiazza** [RocketChat/Rocket.Chat#11240]
**Is your feature request related to a problem? Please describe.**
RC doesn't have any documentation on the multiple oauth options neither at admin and user level

**Describe the solution you'd like**
- User-level documentation: explain what those options are, benefits to the user, how to set each one up.
- Admin-level documentation: there's information on this page: https://github.com/RocketChat/docs/tree/master/administrator-guides/authentication/oauth
which is provides information about callback URLs. Helpful.
Missing part is: explain how the use of oauth's changes user information on the backend; list benefits to implementing oauth such as removing friction from user creation and login, along with incremental CRM information (example: user's Twitter handle or user's LinkedIn profile URL) - if that's really the case.

**Describe alternatives you've considered**
At the moment, we're in the dark to understand, guide users, and handle issues /bugs in the process because there is no guidance around what *exactly* to expect

**Comment by MartinSchoeler** [comment]
Please reopen this at https://github.com/RocketChat/docs/ Thanks!

**Comment by andpiazza** [comment]
Done! https://github.com/RocketChat/docs/issues/821
Thanks for the guidance @MartinSchoeler
