### ISSUE TITLE
An improvement suggestion: Click to Chat in an assigned Channel, or Direct Message or Private Group

### ISSUE THREAD

**Issue by MRYingLEE** [RocketChat/Rocket.Chat#1125]
At present, for example, before I login, if I click  https://demo.rocket.chat/direct/may.xu, then login dialog appears, but after I login, the general startup page instead of direct message page appears.

But after I login-ed, if I click https://demo.rocket.chat/direct/may.xu, then assigned direct message page appears.

Please make two situations in a consistent way. In other words, click to chat can guide us to the assigned page regardless we have login-ed or not (Of course, we have to login before the assigned page appears.)

**Comment by graywolf336** [comment]
So, remember where the user came in at and after they login take them to where they wanted to go. :+1: for the suggestion.

**Comment by steedos** [comment]
+1

发自我的 iPhone
