### ISSUE TITLE
Queue cannot be hidden

### ISSUE THREAD

**Issue by dotsomething** [RocketChat/Rocket.Chat#11250]
Running Rocket.Chat Version: 0.65.1

I was testing out what we could do with Livechat and we decided not to use it right now. I ended up all the conversations, but these two conversations are stuck. I tried everything I could to remove it.

![](https://i.imgur.com/1OJWyft.png "Queue is stuck")

**Comment by ggazzo** [comment]
@renatobecker could you check this issue please?

**Comment by renatobecker** [comment]
@ggazzo,
Yes, I'll take a look at this very soon.
Thx.

**Comment by renatobecker** [comment]
Hi @dotsomething!
Have you checked your browser console if any error is fired when you try to close these Livechat rooms?
If you didn't, please do it and let me know what what's going on.
I'll be waiting for your feedback.

Thanks.

**Comment by dotsomething** [comment]
@renatobecker if I try to hide the room I get the following error: ``webview: Uncaught [sprintf] huh?``

~~Pretty cute.~~

**Comment by renatobecker** [comment]
@dotsomething, I see.
What is your current language in use? `Pt-BR`?
If so, please change your current language to 'En' and let me know if the same behaviour remains.

**Comment by dotsomething** [comment]
Yeah, in English I was able to hide the room!

Renato, I have another issue, but I don't know if it can be considered a bug or not. How can I proceed with it?

**Comment by renatobecker** [comment]
Okay @dotsomething. The good news is that this issue is already fixed and will be available in our next version(0.66), it was related to translation files.
About the question in your last comment, if your issue is not related to this subject, I suggest you create a new issue describing what is going wrong.

**Comment by dotsomething** [comment]
Cool!
