### ISSUE TITLE
Drag & Drop browser-like behavior

### ISSUE THREAD

**Issue by dotsomething** [RocketChat/Rocket.Chat#11265]
We have a Macbook Pro from 2012 and it's pretty laggy.

When we use the drag & drop feature to share files between users, we usually wait the "Drop files here" animation to show up. But most of the time, even waiting plus 5 seconds after the animation, the client acts like a browser and opens the file (if it's a image or pdf).

We are running the latest client version.

**Comment by TwizzyDizzy** [comment]
Please use the issue template and state, what client you are using (Browser or Electron Client). If you're using the Electron client, use [this repository](https://github.com/RocketChat/Rocket.Chat.Electron) to report the bug. In any case, please follow the issue templates, as we do not deal with issues that don't include them.

Cheers
Thomas
