### ISSUE TITLE
Enable user to receive sound notification for every message

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#1126]
Would be possible to let the user change a setting to enable or disable sound on all messages?

In big rooms this can will be an issue but the idea is that you can change that per channel basis.

EDIT: define use case

**Comment by graywolf336** [comment]
I would suggest you add items to #1068.

**Comment by gmsecrieru** [comment]
I will close this one as we have a very complete proposal running on #1068 as mentioned.
