### ISSUE TITLE
Error sending image to chat

### ISSUE THREAD

**Issue by awod79** [RocketChat/Rocket.Chat#11283]
Hi!
In our rocketchat after update we having error with sending image into chat.

**Comment by tassoevan** [comment]
Please, fill the description following the bug report template so we can help you.

**Comment by TwizzyDizzy** [comment]
Hi @awod79 

please use the issue template and fill out every information. Otherwise we cannot help you. I'm going to reopen once you added the missing information.

Cheers (+close)
Thomas
