### ISSUE TITLE
[Improvement] Notify customer when livechat agent goes offline

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#11280]
**Is your feature request related to a problem? Please describe.**
Imagine a livechat agent loses connection or has to leave, but the agent has an ongoing conversation. If the agent goes offline, the customer does not get any notification about this. The customer thinks, the agent is still online. 

**Describe the solution you'd like**
Return conversation after a defined period of time (e.g. 1 min) to guest pool and tell the customer about the short Interruption. Meanwhile send a notification to all other online agents, that a customer is waiting for a reply. If no other agent is online, say sorry and ask the customer to send his request by email (see offline form).

**Comment by renatobecker** [comment]
Hi @janrudolph 
We already have a setting where you can decide what to do with the livechats when an agent goes offline:

![Screen Shot 2019-03-28 at 11 53 27](https://user-images.githubusercontent.com/2067649/55167665-303c4300-5150-11e9-9b65-d22ba67ba58c.png)

And related to the client side(widget), we are now displaying the status of the agent on our new Livechat widget, as you can see below:

![Screen Shot 2019-03-28 at 11 56 27](https://user-images.githubusercontent.com/2067649/55167952-accf2180-5150-11e9-9fbe-f69ece35d5a8.png)

The new Livechat widget will be provided as a community feature on our next release(1.0), so maybe having the status of agent displayed on the widget, it will be easy for the Livechat users identify that the agent is offline, right?

What do think?
Thanks.

**Comment by marceloschmidt** [comment]
So this is implemented.
