### ISSUE TITLE
Channel notification settings switches have terrible UX

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#11287]
The switches in the upper part of a channels notification settings have pretty terrible UX:

1. Unclear labels
1. Labels on both sides of the switches
1. Some have inverted logic
1. Active / inactive state doesn't line up with color of labels

Applied to the image below:

-  First switch: `Turn OFF`, `Turn ON` (which isn't very clear to begin with; turn what on or off?).  It's currently in the `ON` state yet the `Turn ON` label is grayed out.
- Second switch: It's in the 'off' state yet the setting is enabled (receive `@here` notifications) but again that label is grayed out.
- Third switch: Similar to the first, the active label is grayed out.

![](https://ds.ulo.pe/8FzKJ9eCEt.jpg)

**Comment by AmShaegar13** [comment]
I fully agree with you. Every time I want to change settings I am confused about what the current state is and which setting I actually want.

**Comment by tassoevan** [comment]
I agree with the concerns about UX, but I can't see the buggy behavior of the labels wrongly grayed out in the latest version. Could you confirm which version is this?

**Comment by AmShaegar13** [comment]
You are right. Current version fixes the problem.

**Comment by ggazzo** [comment]
please open this issue again if the problem persists.
