### ISSUE TITLE
There is no + sign to add custom emoji

### ISSUE THREAD

**Issue by o-jans** [RocketChat/Rocket.Chat#11289]
### Description:
Administration -> Custom Emoji
The permission to manage-emoji is set but there is no + sign on top right hand corner.

### Expected behavior:
A + sign on top right hand corner to add new custom emoji.

### Actual behavior:
Only a search bar is shown but no + sign.

### Server Setup Information:
- Version of Rocket.Chat Server: 0.65.1
- Operating System: Ubuntu
- Deployment Method: Snap
- Number of Running Instances: 1

**Comment by vynmera** [comment]
This is fixed in 0.65.2: #11049 
Please update to it, it will be fixed :)

CC @TwizzyDizzy
