### ISSUE TITLE
Sometimes user presence stuck in online status if browser is refreshed multiple times very fast

### ISSUE THREAD

**Issue by distlibs** [RocketChat/Rocket.Chat#11293]
### Description:
I noticed that sometimes user presence stuck in online status if browser is refreshed multiple times very fast. If Rocket Server is restarted, user back to offline after some time.

In `~/Rocket.Chat/packages/rocketchat-livechat/server/unclosedLivechats.js` file
I added `UserPresence.activeLogs();` myself for user presence testing:
```
UserPresenceMonitor.onSetUserStatus((user, status/*, statusConnection*/) => {
    UserPresence.activeLogs();

	if (!monitorAgents) {
		return;
	}
	if (onlineAgents.exists(user._id)) {
		if (status === 'offline' || user.statusLivechat === 'not-available') {
			onlineAgents.remove(user._id, () => {
				runAgentLeaveAction(user._id);
			});
		}
	}
});
```
If browser is refreshed multiple times very fast sometimes two or more connections for same user are created. When browser is closed one connection is removed, but others still exist.
![user-presence](https://user-images.githubusercontent.com/30928251/42082224-1c2e75d6-7b90-11e8-8112-61583b2a2317.png)

I think it's related to `konecty:user-presence` package. (@sampaiodiego )

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-develop (c4130293e6)
- Operating System: Ubuntu 18.04
- Deployment Method: git pull
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.4.10

**Comment by sampaiodiego** [comment]
I was unable to reproduce the issue..

the closer I got was this:
![image](https://user-images.githubusercontent.com/8591547/43402810-eb953ee2-93e9-11e8-8d7b-3c19ff7680eb.png)

two connection were created and only one was removed.. but after some time the other was removed too.

in which browser did you test? what is your rocket.chat server version?

**Comment by distlibs** [comment]
Chrome 68. Rocket Chat version: 0.69.0-develop (14fd90ca4d)
Try to refresh using CTRL + F5. I made the pull request which fix this issue.
