### ISSUE TITLE
Make the channel access denied view more friendly

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#11294]
**Current situation**

When I try to open a room by not being a member, I get a message that looks like a error and has a deterrent effect on me.

<img width="583" alt="_2__assistify_team_chat" src="https://user-images.githubusercontent.com/853776/42093801-ea3353e4-7bad-11e8-9d47-ff26d5a28696.png">

**Suggested improvement**

- Create a friendly page that explains the user why he/she cannot open the room and what he/she can do to gain access to the room, for example, to ask the room owner/moderator to join the channel.
- Support the user with a precise description. The current message says "Page", but the user is actually trying to access a room/channel/group.
- Since this is not an error in the situation, it would also help to change the color from red (error) to blue (information) or orange (warning) to reduce the "aggressiveness" of the dialog.

**Additional context**

[Assistify](https://github.com/assistify/Rocket.Chat/) has implemented a feature: "[Ask to join private channel](https://github.com/assistify/Rocket.Chat/pull/319)". That allows a non permitted user to ask to join a room. This does not make the "You are not authorized to view this page." dialog more friendly, but it helps the users out of his situation.

**Comment by ruKurz** [comment]
https://github.com/assistify/Rocket.Chat/pull/319

**Comment by 4msha** [comment]
Hey can I work on this issue. I've seen that roomNotFound.html file in  Rocket.Chat > app > ui > client > views > 404  folder needs to be edited. However I wanted to know how ask to join private channel feature works. Also on my localhost when I'm trying to access any private channel or team which I'm not a member of then I'm getting this not whats shown in the issue. 
![roomNotFound](https://user-images.githubusercontent.com/57831632/113343841-f65d3300-934d-11eb-8f3d-9c91923a44d6.png)
Can you please guide me.

**Comment by ggazzo** [comment]
![image](https://user-images.githubusercontent.com/5263975/172880731-d7e55f3e-fe80-4e3e-a8ee-649c5e9e5af5.png)
