### ISSUE TITLE
share my start rocket.chat experience in ubuntu 16

### ISSUE THREAD

**Issue by 171563857** [RocketChat/Rocket.Chat#11306]
# check u computer already install VMware and ubuntu

## Git
    sudo apt-get install git
## JDK
    sudo apt-get install default-jre default-jdk
## Maven
    sudo apt-get install maven
## VIM
    sudo apt-get install vim-gtk
## NVM
    cd ~/
    git clone https://github.com/creationix/nvm.git .nvm
    cd ~/.nvm
    git checkout v0.33.11
    . nvm.sh
    cd ~/
    vim .bashrc
### add this info in .bashrc and run 'source .bashrc'
```
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
```
## NODE
    nvm install 8
### if u can't "npm install" , u can use taobao npm
    npm config set registry https://registry.npm.taobao.org
    npm config set chromedriver_cdnurl https://npm.taobao.org/mirrors/chromedriver
### install by curl
   sudo apt-get install curl
   curl https://install.meteor.com/ | sh
### search 'RELEASE', it's meteor version
![image](https://user-images.githubusercontent.com/22027896/42147776-f39e7cdc-7e01-11e8-9eb8-4499374fb916.png)
### so my download url
    https://static-meteor.netdna-ssl.com/packages-bootstrap/1.7.0.3/meteor-bootstrap-os.linux.x86_64.tar.gz

     rename "meteor.tar.gz" and copy to /$HOME/folder
### create local meteor-install.sh
vim ~/meteor-install.sh
```
#!/bin/bash
set -x
if [ ! -f "$HOME/meteor.tar.gz" ]; then
	echo "please copy meteor.tar.gz to current folder"
	exit
fi
INSTALL_TMPDIR="$HOME/.meteor-install-tmp"
cleanUp()
{
	rm -rf "$INSTALL_TMPDIR"
}
cleanUp
trap cleanUp EXIT
mkdir "$INSTALL_TMPDIR"
test -e "${METEOR_FILE}"
tar -xzf "$HOME/meteor.tar.gz" -C "$INSTALL_TMPDIR" -o
test -x "${INSTALL_TMPDIR}/.meteor/meteor"
mv "${INSTALL_TMPDIR}/.meteor" "$HOME"
test -x "$HOME/.meteor/meteor"
cleanUp
METEOR_SYMLINK_TARGET="$(readlink "$HOME/.meteor/meteor")"
METEOR_TOOL_DIRECTORY="$(dirname "$METEOR_SYMLINK_TARGET")"
LAUNCHER="$HOME/.meteor/$METEOR_TOOL_DIRECTORY/scripts/admin/launch-meteor"
if cp "$LAUNCHER" "$PREFIX/bin/meteor" >/dev/null 2>&1; then
	echo "install meteor ..."
elif type sudo >/dev/null 2>&1; then
	if [ ! -d "$PREFIX/bin" ] ; then
		sudo mkdir -m 755 "$PREFIX" || true
		sudo mkdir -m 755 "$PREFIX/bin" || true
	fi
	if sudo cp "$LAUNCHER" "$PREFIX/bin/meteor"; then
		echo "install meteor..."
	fi
fi
echo "please remove meteor.tar.gz by yourself!"
```
## node-pre-gyp, phantomjs
    cd ./Rocket.Chat
    npm i -g node-pre-gyp
    npm i -g phantomjs
## start meteor 
    meteor npm start

# about webstorm start debug 
> https://github.com/RocketChat/Rocket.Chat/issues/11305

**Comment by 171563857** [comment]
> https://github.com/RocketChat/Rocket.Chat/issues/11305

**Comment by TwizzyDizzy** [comment]
Hi @171563857 

Please use the [forums](https://forums.rocket.chat/) for such questions, as this is not Rocket.Chat bug!

Cheers (+close)
Thomas
