### ISSUE TITLE
how can i debug rocket.chat in webstorm ?

### ISSUE THREAD

**Issue by 171563857** [RocketChat/Rocket.Chat#11305]
i try to debug rocket.chat but was fail 
have someone success ?
: )

**Comment by 171563857** [comment]
# click ”Edit Configurations”
![image](https://user-images.githubusercontent.com/22027896/42147289-99e91ac8-7dff-11e8-874a-6c711f96a3d2.png)

# click "+" and choice ”Meteor”
![image](https://user-images.githubusercontent.com/22027896/42147308-b3a98dbc-7dff-11e8-9891-8a2b78674dd1.png)

# click ”ok” to save
![image](https://user-images.githubusercontent.com/22027896/42147320-c622d9f8-7dff-11e8-84b5-6da4284a28c0.png)

# click debug icon to start
![image](https://user-images.githubusercontent.com/22027896/42147347-e256c012-7dff-11e8-8fd1-76a97d76336a.png)

# cancel debug point
![image](https://user-images.githubusercontent.com/22027896/42147361-f451e0d0-7dff-11e8-9cf3-65824d2cce18.png)

# start debug success
![image](https://user-images.githubusercontent.com/22027896/42147396-19162d18-7e00-11e8-8daf-d3df923d6d83.png)

# The End

**Comment by TwizzyDizzy** [comment]
Hi @171563857 

Please use the [forums](https://forums.rocket.chat/) for such questions, as this is not Rocket.Chat bug!

Cheers (+close)
Thomas
