### ISSUE TITLE
Unauthenticated clients have access to profile pictures

### ISSUE THREAD

**Issue by gnarpaws** [RocketChat/Rocket.Chat#11304]
It looks like that the profile picture api endpoint exposes profile pictures to unauthenticated clients, and furthermore, its random profile picture generator could lead to a denial of service attack.

* Here's an example, which presumably returns the profile picture of a user named "test":
https://open.rocket.chat/avatar/test
* and here's one which generates a random profile picture:
https://open.rocket.chat/avatar/dasdsadfsda

Note: You do not need to be logged in on that particular server for this to work.

**Comment by TwizzyDizzy** [comment]
Dupe of https://github.com/RocketChat/Rocket.Chat/issues/3480.

Cheers
Thomas
