### ISSUE TITLE
Transparent colour of tag message

### ISSUE THREAD

**Issue by Piduna** [RocketChat/Rocket.Chat#11302]
After updating from 0.65.1 to 0.66 i saw one interesting thing. In the messages, that addressed to me, i can't see my nickname. I see transparent colour of my nickame near message, that addressed for me. But i can see message, that addressed to other user. Also, i asked of this user. `Did you see message, that addressed to you ?` He said: `No. I see notification on chat room. But my nickname is transparent in chat`. So his situation, the same, that for me. But this user saw message, that addressed for me.
How to check it ? Go to any room. And try to write `@yournickname test message` and try to see, what is going on.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
