### ISSUE TITLE
Message remains undelivered upon window reload

### ISSUE THREAD

**Issue by anvlkv** [RocketChat/Rocket.Chat#11307]
Hi, In cloud rocket chat we had this issue for few days
It maybe has something to do with [#11079](https://github.com/RocketChat/Rocket.Chat/issues/11079)
After restarting the server it was working ok again
[demo video](https://youtu.be/ZeqEsmyqFk4)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
