### ISSUE TITLE
missing i18n Pt-BR translations

### ISSUE THREAD

**Issue by leandronunes** [RocketChat/Rocket.Chat#11317]
### Description:

There are some missing string translations.
I took some screenshots of each page where I found missing string translations and I made a red point mark in each one.

See below:
![traducao_1](https://user-images.githubusercontent.com/28972/42194988-1a9f60b2-7e4d-11e8-9ed7-9c29c20fda10.png)
![traducao_2](https://user-images.githubusercontent.com/28972/42194989-1abd0f5e-7e4d-11e8-951e-f5f87a77dcc2.png)
![traducao_3](https://user-images.githubusercontent.com/28972/42194990-1adbbda0-7e4d-11e8-9434-7df61b41c8ca.png)
![traducao_4](https://user-images.githubusercontent.com/28972/42194991-1af93f92-7e4d-11e8-967d-32ece38b59a2.png)
![traducao_5](https://user-images.githubusercontent.com/28972/42194992-1b141ca4-7e4d-11e8-8f32-9f85e2e13bfe.png)
![traducao_6](https://user-images.githubusercontent.com/28972/42194993-1b38716c-7e4d-11e8-8d0d-7725062e8522.png)
![traducao_7](https://user-images.githubusercontent.com/28972/42194995-1b661798-7e4d-11e8-9438-fc4d50672cdc.png)
![traducao_8](https://user-images.githubusercontent.com/28972/42194996-1bda90a0-7e4d-11e8-9b12-ca9f6c847afc.png)
![traducao_9](https://user-images.githubusercontent.com/28972/42194997-1c2e87f0-7e4d-11e8-99cd-fca26c208438.png)
![traducao_10](https://user-images.githubusercontent.com/28972/42194998-1c4da77a-7e4d-11e8-98eb-daf9152de7c5.png)
![traducao_11](https://user-images.githubusercontent.com/28972/42194999-1ca1c6ca-7e4d-11e8-9192-907201b08414.png)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
