### ISSUE TITLE
New users are not added to default rooms

### ISSUE THREAD

**Issue by mixrat** [RocketChat/Rocket.Chat#11318]
New users are not automatically joined to default rooms.

This problem was referenced here:  [#7663](https://github.com/RocketChat/Rocket.Chat/issues/7663) but it was closed.
Similar open issue here: [#9205](https://github.com/RocketChat/Rocket.Chat/issues/9205)

![selection_232](https://user-images.githubusercontent.com/20234985/42197695-2350ae4c-7ed8-11e8-91fe-81144b940776.png)

![selection_231](https://user-images.githubusercontent.com/20234985/42196281-445a4410-7ed1-11e8-96af-b283ce38e79e.png)

RC Version: 0.66.0
OS: Ubuntu 16.04

**Comment by ggazzo** [comment]
@mixrat did you change the channels to default after or before create a new user?

**Comment by mixrat** [comment]
I tried both ways. I created two users after making channels default. Existing users were not added either. I thought there might be a setting for this behavior somewhere but I couldn't find one. Can anyone else reproduce this?

**Comment by rssilva** [comment]
Hey @mixrat, thank you for take a look at this 😃 
I tried to reproduce it. See the gif below:

![adding_user](https://user-images.githubusercontent.com/2047941/42637489-b11f54b8-85c1-11e8-802b-4e23273e1733.gif)

I created a new user and he was added to both `default` channels (general and important). But if I change a channel to `default` the users are not added automatically.

Is this the desired behaviour @ggazzo?

**Comment by vynmera** [comment]
@rssilva As far as I know, to get everyone to join a newly created channel, no matter if it's default or not, you will need to do it yourself. (For example: `/invite-all-from-room #general`, or use API method `channels.addAll`)

**Comment by mixrat** [comment]
I created another test user (this time sticking with the Star Wars theme) and it worked...
![out](https://user-images.githubusercontent.com/20234985/42679530-5ffa7b92-86d6-11e8-83a6-50a63a53c504.gif)
Not sure how I screwed it up before. Thank you
