### ISSUE TITLE
Room leader bar overrides room header tooltips

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#11325]
### Description:

When the room leader is shown in a bar by scrolling messages in a room, the tooltips triggered by header buttons at top are "eclipsed" by the room leader bar.

### Steps to reproduce:

1. Open a channel containing a room leader and messages enough to vertical scrolling be present;
2. Scroll up, revealing the room leader bar;
3. Place the cursor over the any button at header (e.g. "Room Info") and wait for its tooltip.

### Expected behavior:

See the tooltip entirely.

### Actual behavior:

Only the top of the tooltip element is shown, hiding a half of the text.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67.0-develop
- Operating System: Linux (Ubuntu 16.04 Xenial Xerus)
- Deployment Method: sources
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.4

### Additional context

![peek 2018-07-03 12-12](https://user-images.githubusercontent.com/2263066/42229211-547a1f06-7ebc-11e8-81ed-7f313877b852.gif)

**Comment by calston** [comment]
Fix does not fix all the other problems the room leader bar creates - like the unread message banner getting stuck around it. 

Question: What the hell is the point of the room leader bar? Just remove it entirely, no one cares who runs a room, and no one wants a giant banner stuck in their UI.
