### ISSUE TITLE
where is the theme/skin?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1132]
Hi,

today 16/oct/2015 at 17:30 circa I have do:

$ export ROOT_URL=http://chat.mrobot.eu:3000
$ cd Rocket.Chat/
$ git reset --hard
$ git pull
$ meteor update
$ meteor

but now my copy of rocket.chat appear as below:

![xrocket01](https://cloud.githubusercontent.com/assets/5683921/10546555/e4350ed0-742e-11e5-9eaa-a5f3cbc0f145.png)

please fix the theme path or the css link
tnx

**Comment by maxlinux2000** [comment]
in the console i can read:

rocketchat_chatops.js:68 startup hooked
Uncaught TypeError: Cannot read property 'initialize' of undefined

**Comment by engelgabriel** [comment]
We are working on this https://github.com/RocketChat/Rocket.Chat/issues/1106

**Comment by engelgabriel** [comment]
Fix by https://github.com/RocketChat/Rocket.Chat/commit/e0519995993d1d1a3d7299ed86a5672a1cd01853
