### ISSUE TITLE
[CRASH] Safari 11.1 crashes on some kind of attachments

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11336]
### Description:

This crash is happening since March, 2018. Basically, if you open any room with video attachments (maybe other types of attachments too?) it crashes the client.

There are other issues related to this problems:
- https://github.com/RocketChat/Rocket.Chat/issues/10383
- https://github.com/RocketChat/Rocket.Chat/issues/10352

![2018-07-04 11 11 59](https://user-images.githubusercontent.com/551004/42281908-46b6fde8-7f7b-11e8-8ce1-5c5db5df1caf.gif)

### Steps to reproduce:

1. Open Safari 11.1 (stable version right now)
2. Go connect to open.rocket.chat
3. Open public channel `#ios-beta`
4. Scroll until you see a video attachment
5. Browser will crash

### Expected behavior:

It should never crash the client.

### Actual behavior:

It's crashing the browser.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.62+
- Operating System: Linux

**Comment by filipealva** [comment]
+1 

It's happening to me as well. Sometimes, when the people send videos on different channels, it's impossible to use RC on a browser.

**Comment by rafaelks** [comment]
Just confirming that it still happens on release 0.67.

**Comment by rafaelks** [comment]
I looks like it doesn't crash anymore after the release of Safari 12 today. Closing for now.
