### ISSUE TITLE
Error 404 when accepting new Live Chat request

### ISSUE THREAD

**Issue by servancho** [RocketChat/Rocket.Chat#11347]
### Description:

Updated from 0.64.2 to 0.66.0 then to 0.66.1. Same problem.
When accepting new LiveChat, error appears both in MacOSX app and in browser.

Error:404
Oops, page not found
Sorry, page you requested does not exists or was deleted!

### Steps to reproduce:

1. Start new live chat on the site and write first message
2. Operator clicks on new live chat from Incoming Livechats section.
3. Message appeared with user message and Take It! button.
4. Click button to accept new live chat. Error 404 appears instead of chat room.

### Expected behavior:

No 404 error. Chat room with user activated.

### Actual behavior:

Error:404
Oops, page not found
Sorry, page you requested does not exists or was deleted!

<img width="312" alt="screenshot 2018-07-04 23 52 33" src="https://user-images.githubusercontent.com/1804516/42293822-77197956-7fe5-11e8-8e26-77cb57a0fcde.png">

<img width="450" alt="screenshot 2018-07-04 23 52 41" src="https://user-images.githubusercontent.com/1804516/42293821-76fc5e02-7fe5-11e8-8ebb-f44f90a1592a.png">

<img width="760" alt="screenshot 2018-07-04 23 52 56" src="https://user-images.githubusercontent.com/1804516/42293820-76da83ea-7fe5-11e8-8e8e-9b1ae50f48b7.png">

### Server Setup Information:

- Version of Rocket.Chat Server:  0.66.1
- Operating System: CentOS 7 x64
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.3 - x64
- MongoDB Version: v2.6.12

### Relevant logs:

[Error] TypeError: undefined is not an object (evaluating 'chatMessages[this._id].input=e.find(".js-input-message")')
	focus .js-input-message (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:251:66483)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:38104)
	_withTemplateInstanceFunc (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:37673)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:38076)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:27002)
	_withCurrentView (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:23080)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:26974)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:87:9124)
	dispatch (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1392774)
	trigger (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1420538)
	simulate (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1421043)
	n (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:9:1421333)
	(anonymous function) (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:183:50411)
	_compute (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:43:2360)
	_recompute (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:43:2613)
	_runFlush (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:43:3809)
	a (1297c7571bedbb6cd4df2a377c401e0f105698e4.js:1:2695)

There are nothing in server logs.

**Comment by renatobecker** [comment]
Hi @servancho!
Thank you for reporting this bug. I want to say that we've already fixed this issue and will be released on our next release.
Please follow the review process for this PR: #10731.
Thank's.
