### ISSUE TITLE
CTRL + Enter work incorrect

### ISSUE THREAD

**Issue by losclipp** [RocketChat/Rocket.Chat#11345]
### Description:

CTRL + Enter add line at the message end. Even if cursor located at first line

### Steps to reproduce:

1. Write multi line message
2. Move cursor at first line message.
3. Press CTRL + ENTER

### Expected behavior:

New empty line should appear after cursor position

### Actual behavior:
[http://skrinshoter.ru/v/040718/2rBTsaWl?a](url)

**Comment by piotrkochan** [comment]
I'm using shift+enter and it works..

**Comment by marceloschmidt** [comment]
Has anyone confirmed this? On a Mac it works. @losclipp what OS are you on? Using desktop app or browser, and if browser, which one, and version, please?

**Comment by tassoevan** [comment]
Don't forget to check the preference at `My Account > Preferences > Enter key Behaviour`.
