### ISSUE TITLE
migration failed upgrading from 0.65.2 to 0.66.1

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#11353]
### Description:

Tried to upgrade a 0.65.2 installation this morning but did not succeed. Error in log:

```
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m+#033[39m#033[31m-----------------------------------------------------------------------------------------------------------------#033
[39m#033[31m+#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m                                                                                                                 #033[31m|#03
3[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                              ERROR! SERVER STOPPED                                              #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                                                                                                 #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                         Your database migration failed:                                         #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m  cannot use the part (settings of settings.preferences.groupByType) to traverse the element ({settings: null})  #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                                                                                                 #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                        Please make sure you are running the latest version and try again.                       #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                 If the problem persists, please contact support.                                #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                                                                                                 #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                         This Rocket.Chat version: 0.66.1                                        #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                         Database locked at version: 124                                         #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m                                           Database target version: 129                                          #033
[39m#033[31m|#033[39m
Jul  5 09:51:05 rocketchat-extern RocketChat[5392]: #033[31m|#033[39m#033[31m
```

### Steps to reproduce:

1. Upgrade from 0.65.2 to 0.66.1
2. Error

### Expected behavior:

Update works.

### Actual behavior:

Update fails.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.2 / 0.66.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6

### Additional context

This happens only on one of my rocketchat machines. Others succeeded running the update.

**Comment by magicbelette** [comment]
Same here.

Some users in mongodb don't have settings :
`db.users.count( { "settings" : { $exists: false } } )`

I guess that we have to update those users in db, still digging...

**Comment by magicbelette** [comment]
```
db.users.updateMany( 
{ "settings" : 
	{ $exists: false } 
},  
{ $addToSet: 
	{ "settings" : 
		{ "preferences" : 
			{ 
				"newRoomNotification" : "door", 
				"newMessageNotification" : "chime", 
				"useEmojis" : true, 
				"convertAsciiEmoji" : true, 
				"saveMobileBandwidth" : true, 
				"collapseMediaByDefault" : false, 
				"autoImageLoad" : true, 
				"emailNotificationMode" : "mentions", 
				"unreadAlert" : true, 
				"desktopNotificationDuration" : 0,	
				"viewMode" : 0, 
				"hideUsernames" : false, 
				"hideRoles" : true, 
				"hideAvatars" : false, 
				"hideFlexTab" : false,	
				"highlights" : [ ], 
				"sendOnEnter" : "normal", 
				"roomsListExhibitionMode" : "unread", 
				"sidebarSortby" : "activity", 
				"sidebarViewMode" : "medium", 
				"sidebarHideAvatar" : false, 
				"sidebarShowUnread" : true, 
				"sidebarShowFavorites" : true, 
				"groupByType" : true
			} 
		} 
	} 
} )
```

**Comment by himpierre** [comment]
Uahh. Should i issue that command?

**Comment by magicbelette** [comment]
You can modify preferences to match yours. It will add settings to users who don't have but you must test it on a non-production environnement first.

Cheers

**Comment by andreas-bulling** [comment]
same problem here. How can this be fixed?

**Comment by andreas-bulling** [comment]
I found it. But what is the corresponding command for MongoDB 3.0.15 for which "updateMany" is not available?

**Comment by andreas-bulling** [comment]
This `db.users.count( { "settings" : { $exists: false } } )` returns 0 for me?!

**Comment by andreas-bulling** [comment]
ok, I made some progress here. Now the error changed:

`{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Migrating from version 126 -> 129","time":{"$date":1530803855394},"level":"info"}
{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 127","time":{"$date":1530803855396},"level":"info"}
{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 128","time":{"$date":1530803855404},"level":"info"}
{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 129","time":{"$date":1530803855422},"level":"info"}

+----------------------------------------------------------------------+
|                                                                      |
|                         ERROR! SERVER STOPPED                        |
|                                                                      |
|                    Your database migration failed:                   |
|       Cannot read property 'desktopNotifications' of undefined       |
|                                                                      |
|  Please make sure you are running the latest version and try again.  |
|           If the problem persists, please contact support.           |
|                                                                      |
|                   This Rocket.Chat version: 0.66.1                   |
|                    Database locked at version: 126                   |
|                     Database target version: 129                     |
|                                                                      |
|           Commit: fb5257f618b22638c6b2ac4c678f76809f5a7d7e           |
|                  Date: Wed Jul 4 15:05:11 2018 -0300                 |
|                             Branch: HEAD                             |
|                              Tag: 0.66.1                             |
|                                                                      |
+----------------------------------------------------------------------+`

**Comment by robotergarten** [comment]
Same problem here:

{"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Migrating from version 124 -> 129","time":{"$date":1530822356940},"level":"info"}
Jul  5 22:25:56 chat rocketchat-server.rocketchat-server[30864]: {"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 125","time":{"$date":1530822356943},"level":"info"}

Trying to fix that problem using:
db.migrations.update({_id: 'control'},{$set:{locked:false,version:125}})
without succes

**Comment by andreas-bulling** [comment]
This helped me but then I ran into another problem (see #11362)

**Comment by realgt** [comment]
@robotergarten I have same error, the updateMany didn't help

**Comment by NickStallman** [comment]
Same problem here, temporarily fixed by bumping the db version to 129 (Thanks @realgt ) but a proper fix is really needed.

**Comment by geekgonecrazy** [comment]
Taking a look at this.  Working through it with a few. 

PLEASE for your own sake do not skip migration.  By setting migration number ahead, you will certainly encounter issues with your install going forward.

**Comment by kevincolten** [comment]
Is there a way to set it back?

**Comment by geekgonecrazy** [comment]
you can set back via: `db.migrations.update({_id: 'control'}, {$set: {locked: false,version:119}})`

Right now I suspect doing as suggested by @robotergarten will do the trick

Basically stop Rocket.Chat - `sudo systemctl stop snap.rocketchat-server.rocketchat-server`

Then fix the issue causing the migration to fail:
```
sudo rocketchat-server.mongo
use parties
db.users.updateMany( 
{ "settings" : 
	{ $exists: false } 
},  
{ $addToSet: 
	{ "settings" : 
		{ "preferences" : 
			{ 
				"groupByType" : true
			} 
		} 
	} 
} )

db.migrations.update({_id: 'control'}, {$set: {locked: false}})
```

Then exit mongo shell and run: `sudo systemctl start snap.rocketchat-server.rocketchat-server`

This should fix it

**Comment by dmotors** [comment]
@robotergarten suggestion as you stated above did not work for me. It was locked at 124 and it still gave me:

    cannot use the part (settings of settings.preferences.groupByType) to traverse the element ({settings: [ { preferences: { groupByType: true } } ]})

I had to set my migration forward to 129 again temporarily until a something really works again.

**Comment by JoeatMJ** [comment]
Here is the process that seems to have fixed it for me. Thanks to @geekgonecrazy!

I shutdown Rocket.Chat.

In MongoDB I set my version back using:

'db.migrations.update({_id: 'control'}, {$set: {locked: false,version:124}})'  - This was my original value.

Then ran...

`use parties
db.users.updateMany( { "settings" : { $exists: false } },  { $addToSet: { "settings" : { "preferences" : { "groupByType" : true} } } } )

db.migrations.update({_id: 'control'}, {$set: {locked: false}})`

Started up Rocket.Chat server, no errors on startup, and it is up and running.

While it is working well, is there a way to check the schema to verify it has the needed changes?

**Comment by geekgonecrazy** [comment]
For any of those that skipped 125 run this query:
```
RocketChat.models.Users.update({
	'settings.preferences.groupByType': { $exists: true }
}, {
	$rename: {
		'settings.preferences.groupByType': 'settings.preferences.sidebarGroupByType'
	}
}, {
	multi: true
});
```

https://forums.rocket.chat/t/snap-migration-failed-for-0-66-1/1505 also detailed here

**Comment by cloudsandladders** [comment]
@geekgonecrazy Is it safe to do the RocketChat.models.Users.update... portion after the rocketchat server restart?

**Comment by JoeatMJ** [comment]
When I switched to 125, I did see 126, 127, 128, and 129 execute successfully.

When I went back to apply the missed 125 update, I am getting a "ReferenceError:  RocketChat is not defined" message.

What is missing?

**Comment by geekgonecrazy** [comment]
Oops updated comment. Typed command we would run not the command you would run.  Sorry about that.  

Just swap RocketChat.models with db

**Comment by JoeatMJ** [comment]
Thanks for the update. I ran this:

db.users.update({ 'settings.preferences.groupByType': { $exists: true }}, {$rename: { 'settings.preferences.groupByType': 'settings.preferences.sidebarGroupByType' }}, { multi: true}):

I get the result "errmsg" : "cannot use the part (settings of settings.preferences.groupByType) to traverse the element ({settings.preferences.groupByType' : true } } ]})"

Let me know what I am missing.

**Comment by JoeatMJ** [comment]
I found it. db.Users. The query executed successfully.

**Comment by kevincolten** [comment]
That got me closer, but now hitting the
```
+----------------------------------------------------------------------+
|                                                                      |
|                         ERROR! SERVER STOPPED                        |
|                                                                      |
|                    Your database migration failed:                   |
|       Cannot read property 'desktopNotifications' of undefined       |
|                                                                      |
|  Please make sure you are running the latest version and try again.  |
|           If the problem persists, please contact support.           |
|                                                                      |
|                   This Rocket.Chat version: 0.66.1                   |
|                    Database locked at version: 128                   |
|                     Database target version: 129                     |
|                                                                      |
|           Commit: fb5257f618b22638c6b2ac4c678f76809f5a7d7e           |
|                  Date: Wed Jul 4 15:05:11 2018 -0300                 |
|                             Branch: HEAD                             |
|                              Tag: 0.66.1                             |
|                                                                      |
+----------------------------------------------------------------------+
```
error

**Comment by sampaiodiego** [comment]
@kevincolten have you ran the command from @magicbelette which includes a `$addToSet` command?

unfortunate that command it wrong.. it should not be a `$addToSet` (which creates an array) but a `$set` instead (that creates an object).

so in your case, you'll need to run the additional command, which will revert all arrays to objects again:
```
db.users.find({ 'settings.0': {$exists:true} }, { settings: 1 }).forEach(function(user) {
    db.users.update({ _id: user._id }, { $set: { settings: user.settings[0] } });
})
```

**Comment by kevincolten** [comment]
```js
db.Users.find({ 'settings.0': {$exists:true} }, { settings: 1 }).forEach(function(user) {     
  db.users.update({ _id: user._id }, { $set: { settings: user.settings[0] } });
})
```
Seems to have done the trick! thanks @sampaiodiego!

**Comment by magicbelette** [comment]
Sorry for the huge mistake ! And thank you @sampaiodiego for your quick answer

**Comment by sampaiodiego** [comment]
no worries @magicbelette .. you did it with good intention.. 🤗

**Comment by mpodshivalin** [comment]
I've encountered this issue as well - Rocket.Chat suddenly stopped working just before our deadline
Big thanks to everyone! Skipping migration to 125 and applying your fixes worked.

**Comment by NickStallman** [comment]
Thanks guys. I've finally taken our installation offline and with 0.66.2 all I needed to do was revert the db version back to 124 and restart RocketChat.
0.66.2 is available via Snap.

All migrations completed successfully now without any additional tinkering with the database.
