### ISSUE TITLE
Confirmation Email doesn't include sender. 

### ISSUE THREAD

**Issue by lennartgrunau** [RocketChat/Rocket.Chat#11369]
### Description:

The Confirmation Email does not show any sender, neither name nor mail adress. Instead it shows "mailer-daemon".

### Steps to reproduce:

1. Register
2. Open Confirmation Email

### Expected behavior:

Comfirmation Email has a proper sender.

### Actual behavior:

The Confirmation Mail has no proper sender, instead it shows "mailer-daemon"
```Jul 6 10:04:19 imap postfix/qmgr[24377]: ************: from=<>, size=1389, nrcpt=1 (queue active)```

<img width="689" alt="bildschirmfoto 2018-07-06 um 09 47 11" src="https://user-images.githubusercontent.com/18286724/42368237-cedcf0ce-8106-11e8-864d-f9e154a6ba92.png">

 
### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.1
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: As shipped with 0.66.1 snap
- MongoDB Version: As shipped with 0.66.1 snap

### Additional context

The missing sender makes the email look like spam.

### Relevant logs:

No relevant logs.

**Comment by chatnl** [comment]
I have the same problem. Latest version of Rocket Chat server. OS is Debian 9. Deployment Method also SNAP. 

The sender is MAILER-DAEMON. 

I need to be able to change this. Where can I find the field that does that?

Regards,

Stef

**Comment by lennartgrunau** [comment]
It seems like rocketchat doesn't include any sender at all, so the Email Provider of the recipient fills this field with the name of the deamon.

**Comment by chatnl** [comment]
Yes you are right. Let's hope there is a fix for this problem soon.

**Comment by chatnl** [comment]
Any news yet? Anyone? I had to switch off the confirmation email because of this bug. Because of spammers, this is not a good situation...

**Comment by lennartgrunau** [comment]
In which way are you experiencing spam?

**Comment by chatnl** [comment]
I am not experiencing spam yet because the site has not been indexed by search engines at this moment. I'd rather solve the problem than wait for problems to happen.  Without captcha or a confirmation mail system that works spammer will be able to login, post garbage in the chatroom and leave again. I don't want that.

**Comment by chatnl** [comment]
@lennartgrunau Yes ok but people are using it and every user counts :-). I was hoping for a quick respons from the developers on this one. Maybe a fix could be included in the next version coming soon after 27th july?

**Comment by Haocen** [comment]
This is caused by a horrible code logic, after setting the `From Email` in `SMTP` settings you will need to restart Rocket.Chat for it to take effect because verification email related settings was set by Meteor account system, which will only init from variables when the system start up...

**Comment by lennartgrunau** [comment]
@Haocen That works, thanks. This should be documented somewhere.

**Comment by linuxbass** [comment]
yes, worked for me to. I have it in a docker container. Stopped and restarted the container and now the From address is being included in registration emails and no bounces from Google, Yahoo or other strict MX hosts.
