### ISSUE TITLE
Can't activate new Zaps in Zapier for RC

### ISSUE THREAD

**Issue by disenchant** [RocketChat/Rocket.Chat#11377]
### Description:

We've used the Zapier integration for Rocket.Chat in some Zaps and they worked perfectly. A few days ago we recognized that the existing Zaps still work as expected but we can't activate any new ones that include Rocket.Chat.

### Steps to reproduce:

1. Add Rocket.Chat to your "Connected Accounts" in Zapier (https://zapier.com/app/settings/authorizations)
2. Create a new Zap that used Rocket.Chat either as a trigger or action.
3. Try to activate your new Zap -> It fails (see screenshot below)

### Expected behavior:

Create a new Zap that uses Rocket.Chat and simply be able to activate it.

### Actual behavior:

![42389048-bc07866c-8147-11e8-97f4-2a3e8e500655](https://user-images.githubusercontent.com/686611/42389649-a86ca5ae-8149-11e8-86e6-58b1ed91a9fe.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: Linux
- Deployment Method: Docker 
- Number of Running Instances: 1
- NodeJS Version: v8.11.3

### Additional context

It seems that when trying to activate a Zap that includes Rocket.Chat, a request is sent to the Rocket.Chat server pointing to `/api/v1/integrations.create` but the Rocket.Chat server responds with a 400 error.

### Relevant logs:

The request that hits the Rocket.Chat server and seems to be the problem as it results in a 400 error instead of a 200 success:

`[REDACTED IP] - - [06/Jul/2018:16:09:03 +0000] "POST /api/v1/integrations.create?access_token=[REDACTED TOKEN] HTTP/1.0" 400 73 "https://[REDACTED URL]" "Zapier"`

**Comment by disenchant** [comment]
The following is what the Zapier support team provided us with (slightly more censored):

```
Credentials are censored and data may be formatted and/or truncated.

permalink: :censored:
timestamp: 2018-07-04T10:37:33.805Z

--------------------------------------------------------------------------------
REQUEST
--------------------------------------------------------------------------------

POST https://:censored:/api/v1/integrations.create?access_token=:censored:

Content-Length: 250
Accept-Encoding: gzip, deflate
Accept: application/json
User-Agent: Zapier
Connection: keep-alive
Content-Type: application/json; charset=utf-8

{
  "type": "webhook-outgoing",
  "channel": "#test",
  "name": "Zap: :censored:",
  "enabled": true,
  "username": "rocket.cat",
  "event": "sendMessage",
  "urls": ["https://zapier.com/hooks/standard/:censored:/:censored:/"],
  "scriptEnabled": false
}

--------------------------------------------------------------------------------
RESPONSE
--------------------------------------------------------------------------------

400

Server: nginx
Date: Wed, 04 Jul 2018 10:37:33 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Instance-Id: EzgnocahchNmfzz9S
Cache-Control: no-store
Pragma: no-cache
Vary: Accept-Encoding
X-Content-Type-Options: nosniff

{
  "success": false,
  "error": "[not_authorized]",
  "errorType": "not_authorized"
}
```

**Comment by disenchant** [comment]
It seems that the Rocket.Chat integration in Zapier is configured to perform one of the requests as the `rocket.cat` user instead of the user that was authenticated. If the `rocket.cat` is disabled (e.g. we're using our own bot) Zaps can't be activated.

Additionally it might be of interest to identify the issue, that the problem only exists when getting data (e.g. react on a message) but not when sending data (e.g. send a direct message).

**Comment by martinkruusimagi** [comment]
This is also breaking previously created Zaps that use any event-based triggers

**Comment by justinr1234** [comment]
I'm trying to enable this on the open.rocket.chat server and see a 401 error:

```
Credentials are censored and data may be formatted and/or truncated.

permalink: /messages/graylog_9644/ef05ee82-5c94-11ea-8afb-0a32aa6c783f
timestamp: 2020-03-02T14:48:52.320Z

--------------------------------------------------------------------------------
REQUEST
--------------------------------------------------------------------------------

GET https://open.rocket.chat/api/v1/me?access_token=:censored:40:af599832cc:

User-Agent: Zapier
Accept-Encoding: gzip, deflate
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8

--------------------------------------------------------------------------------
RESPONSE
--------------------------------------------------------------------------------

401

Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token
Access-Control-Allow-Origin: *
Cache-Control: no-store
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 02 Mar 2020 14:48:52 GMT
Pragma: no-cache
Set-Cookie: _f993b=http://10.10.39.35:3000; Path=/
Vary: Accept-Encoding
X-Instance-Id: d6e7HJ4mqctaxwct3
X-Xss-Protection: 1
Content-Length: 82

{
  "status": "error",
  "message": "You must be logged in to do this."
}
```

It seems `rocket.cat` is still enabled on the open.rocket.chat server. I'm able to retrieve messages in the Zapier test step, so something seems to be working. One thing I noticed is that the API request does not match the docs:

https://rocket.chat/docs/developer-guides/rest-api/authentication/me/

The docs recommend passing the `X-Auth-Token` header while the debug logs from Zapier clearly show that the auth token is being added to the URL:

GET https://open.rocket.chat/api/v1/me?access_token=:censored:40:af599832cc:

Further Restivus, which is providing the layer dealing with the requests, also needs that header and doesn't use `access_token` anywhere.

**Comment by rodrigok** [comment]
@justinr1234 our open server is not intended to be used for zapier integrations of 3rd party users. Please set up your own server or start a server in our cloud to set up your integration.

On open.rocket.chat the zapier integration is disabled.

**Comment by justinr1234** [comment]
@rodrigok I know we talked on RC chat, did you ever find out if there's a way we can still do this in the case of Private channels on open.rocket.chat ?

**Comment by rodrigok** [comment]
@justinr1234 can you test now? It was just a missing permission.

**Comment by justinr1234** [comment]
@rodrigok It works! Great work!

One thing, and this isn't for this ticket, but the events in Zapier won't fire for discussions created off of the original private channel. Is it possible to get a UI option in Zapier that allows to include Discussions as well? Could make it an optional switch.

**Comment by rodrigok** [comment]
Uhm, I need to check if we have the necessary APIs

**Comment by justinr1234** [comment]
@rodrigok Just checking back to see if you found anything out, greatly appreciate your help!

**Comment by justinr1234** [comment]
Hey @rodrigok how's it going?

**Comment by justinr1234** [comment]
@rodrigok Just checking in, thanks!

**Comment by justinr1234** [comment]
@rodrigok I'm seeing a regression back to the original behavior. Is it possible the setting on the server got reverted after a new deploy or something?

**Comment by justinr1234** [comment]
@rodrigok Hey just checking in about the regression, thanks!

**Comment by CarstenHager** [comment]
> @justinr1234 can you test now? It was just a missing permission.

I have the same Problem on my own Rocketchat Server. (The app returned "[not_authorized]".)
What permission have you set?

**Comment by DaniW42** [comment]
> @justinr1234 can you test now? It was just a missing permission.

I encountered this problem a few weeks ago and just saw this issue. Could you please share your solution? @rodrigok 
And will there be any fix on this? Looks like there was not much progress meanwhile :( 

Automation addicted guys will appreciate ;)

**Comment by g-voelker** [comment]
I found the same problem trying to connect to the chat.gwdg.de instance. I can pull test data with Zapier but can't activate the Zap finding the described error: 
`The app returned "[not_authorized]".`
From the above discussion it's not clear to me whether this error is based on the requests Zapier is sending out or the Rocket.Chat config on the server. The fact that Zapier seems to correctly pull test data (and hence is properly authenticated) seems to point at an error in the Zapier code. In that case the bug isn't associated to Rocket.Chat and this issue may be closed.
Did anyone clarify this in detail?
