### ISSUE TITLE
Server doesn't start after update: Database Migration failed

### ISSUE THREAD

**Issue by C0ldF0x** [RocketChat/Rocket.Chat#11375]
The server doesn't start after updating to 0.66.1, when executing:
`sudo journalctl -u snap.rocketchat-server.rocketchat-server
`
 I get the following response:

`Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: {"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Migrating from version 124 -> 129","time":{"$date":15308829
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: {"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 125","time":{"$date":1530882959372}
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: +-----------------------------------------------------------------------------------------------------------------+
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                                                                                 |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                              ERROR! SERVER STOPPED                                              |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                                                                                 |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                         Your database migration failed:                                         |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |  cannot use the part (settings of settings.preferences.groupByType) to traverse the element ({settings: null})  |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                                                                                 |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                        Please make sure you are running the latest version and try again.                       |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                 If the problem persists, please contact support.                                |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                                                                                 |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                         This Rocket.Chat version: 0.66.1                                        |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                         Database locked at version: 124                                         |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                           Database target version: 129                                          |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                                                                                 |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                 Commit: fb5257f618b22638c6b2ac4c678f76809f5a7d7e                                |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                       Date: Wed Jul 4 15:05:11 2018 -0300                                       |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                   Branch: HEAD                                                  |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                   Tag: 0.66.1                                                   |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: |                                                                                                                 |
Jul 06 13:15:59 ip-172-31-42-133 rocketchat-server.rocketchat-server[1198]: +-----------------------------------------------------------------------------------------------------------------+
Jul 06 13:15:59 ip-172-31-42-133 systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE
`

**Comment by kaiiiiiiiii** [comment]
Please upgrade to v0.66.2 as this error should be fixed in #11364 :)

**Comment by C0ldF0x** [comment]
thank you so much. problem resolved
