### ISSUE TITLE
Querying the Channels.Counters rest API endpoint with a roomID that the user is no longer in, should return a more useful error.

### ISSUE THREAD

**Issue by Galatoni** [RocketChat/Rocket.Chat#11372]
### Description:

When querying the 'channels.counters' Rest API endpoint with a valid roomID, the endpoint returns an error payload `{"success":false,"error":"Cannot read property '_room' of undefined"}`. This doesn't indicate if the consumer has made an error in their request (though the 400 https error code would suggest so).

### Steps to reproduce:

1. Make a request to the channels.counters endpoint using a roomID that the user is no longer in
2. Await response
3. Notice error response doesn't appear to indicate what the user actually did wrong

### Expected behavior:

I would expect the error returned to indicate what parameter or condition cause the error to allow the user to take action to prevent it.

### Actual behavior:

`{"success":false,"error":"Cannot read property '_room' of undefined"}` is returned, which seems to be an internal error rather than anything the consumer can do anything about.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.1
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v8.11.3

**Comment by Galatoni** [comment]
Actually, i've just realised. The expected payload is supposed to have a joined flag according to the documentation. Therefore, it shouldn't matter if the querying user has prior membership of the room or not.

**Comment by MarcosSpessatto** [comment]
@Galatoni, I tested locally and found that this issue was resolved [in this PR](https://github.com/RocketChat/Rocket.Chat/pull/10749). The fix is in version `v0.67`, to fix your problem, please upgrade your server. :v:
