### ISSUE TITLE
Notifications not Working on mobile

### ISSUE THREAD

**Issue by IlPicasso** [RocketChat/Rocket.Chat#11376]
### Steps to reproduce:

1. Send a test push to my user

### Expected behavior:

Recieve a Push notification on my Phone

### Actual behavior:

Nothing happens 

### Server Setup Information:

- Version of Rocket.Chat Server: 

Version | 0.66.1

- Operating System:  Ubuntu 16.04
- Deployment Method:  SNAP
- Number of Running Instances:  1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Additional context

I never get any notification, neither on desktop or on my phone and I am as online

### Relevant logs:

https://hastebin.com/woyipekote.js

**Comment by JoeArcher007** [comment]
@IlPicasso Try updating the server (your ubuntu server) with the latest updates and perform a reboot. That's what I needed to do and got them working today.

**Comment by IlPicasso** [comment]
@JoeArcher007

Thanks for the suggestion, I just did what you mentioned but it didn't worked

**Comment by JoeArcher007** [comment]
Can you upload a picture of your Push settings?

**Comment by IlPicasso** [comment]
I have tried both, with gateway and without gateway

![image](https://user-images.githubusercontent.com/5110242/42469322-fc22a8bc-837c-11e8-97f7-9e3274968b0c.png)


![image](https://user-images.githubusercontent.com/5110242/42469362-148d6360-837d-11e8-9a2a-4036d88a975c.png)

**Comment by JoeArcher007** [comment]
The next thing I would look at is the network settings on the device. Can you ssh into the ubuntu box and then perform 

`ping google.com`

If that's successful, you can at least rule out DNS.

**Comment by IlPicasso** [comment]
Hmm, seems good I can ping it

![image](https://user-images.githubusercontent.com/5110242/42476671-4337c446-8394-11e8-85d0-1ca498971b49.png)

**Comment by IlPicasso** [comment]
I tried that before, seems fine also yes thats the IP
![image](https://user-images.githubusercontent.com/5110242/42476884-f0876034-8394-11e8-9d3d-222b22854123.png)

Yes, I rebooted

I was thinking on trying to compile my own app with my credentials but when I compile I get this

Keystore file 'C:\Users\EQUIPO 1\Desktop\Rocket.Chat.Android\Rocket.jks' not found for signing config 'release'.
I am not experienced in Android apps, and I cant find anywhere how to solve that

**Comment by JoeArcher007** [comment]
Hmmm. I'm not too sure where to go from there. I'd then maybe uninstall the app on your Android and then reinstall. Start from scratch on there. Sometimes that's what is needed too.

**Comment by IlPicasso** [comment]
I fixed it, Thanks everyone


I had it behind CloudFlare, removed cloudflare and I started recieving the push notifications
