### ISSUE TITLE
Image embeds have the wrong hit target

### ISSUE THREAD

**Issue by vjeux** [RocketChat/Rocket.Chat#1138]
You can click on the blank area at the right of the image and it still opens the image :(

<img width="850" alt="screen shot 2015-10-16 at 3 10 16 pm" src="https://cloud.githubusercontent.com/assets/197597/10554485/b9638530-7418-11e5-806e-8eb9b5447768.png">

**Comment by gmsecrieru** [comment]
I think that's mostly because we display the image as the background-image of an empty `div` within an `a` tag, which takes up all the available width. I think we would need to define the maximum width of the image container or take another approach.

**Comment by liamdawson** [comment]
@gmsecrieru — The approach you've mentioned (background image on a full-width div) also prevents #1139 from happening, at least from my brief testing. Is there a reason the img tag isn't used as-is?

**Comment by gmsecrieru** [comment]
Not sure. @RocketChat/owners ?

**Comment by geekgonecrazy** [comment]
@gmsecrieru @liamdawson  check out: #544

I think it might be a good chance to start a discussion about this.

**Comment by rodrigok** [comment]
I think I can improve this using the same way that Slack does.

**Comment by geekgonecrazy** [comment]
@rodrigok i'm not familiar with how slack handles this.  How do they do it?

**Comment by stefanlegg** [comment]
Created a pr that solves this: #1167

**Comment by rodrigok** [comment]
@geekgonecrazy @stefanlegg please see here https://github.com/RocketChat/Rocket.Chat/pull/1170
