### ISSUE TITLE
How to change  Site URL in snap installation

### ISSUE THREAD

**Issue by springyuniverse** [RocketChat/Rocket.Chat#11384]
Hello, I have installed RC using snap and everything is going well except that after performing 
sudo service snap.rocketchat-server.rocketchat-server status
 
The Site URL is Localhost, however I have edit Caddyfile with all the right information of my domain 

Thanks

**Comment by geekgonecrazy** [comment]
This will be coming in soon.  :)

**Comment by aqiank** [comment]
Hi, I still cannot find a way to change site URL in snap. Any updates?

**Comment by ER-EPR** [comment]
According to :
https://docs.rocket.chat/deploy/prepare-for-your-deployment/rapid-deployment-methods/snaps

 sudo snap set rocketchat-server siteurl=http://aaa.bbb.com:3000
will perform the change of url
