### ISSUE TITLE
How to enable upload of .sketch files

### ISSUE THREAD

**Issue by thiesschneider** [RocketChat/Rocket.Chat#11387]
Hi, 

which mediatype do I have to add to be able to upload .sketch files?

thx in advance!
thies

**Comment by tassoevan** [comment]
I'm afraid Rocket.Chat relies on File API to determine the upload file type and [this is a mistake](https://developer.mozilla.org/en-US/docs/Web/API/File/type), since is browser-dependent.
A ugly workaround for now is to clear the `Accepted Media Types` field in `Administration` > `File Upload`.

**Comment by TwizzyDizzy** [comment]
You should be able to allow .sketch files with the mime-type `application/zip` (which it is, actually). For details, see #7462.

If this doesn't solve your question, please get back to me.

Cheers (+close)
Thomas

**Comment by nerrehmit** [comment]
Hi @TwizzyDizzy 
I tried uploading a .sketch file but it did not work. 
application/zip,application/gzip,application/x-zip is allowed for upload. 
If I rename the something.sketch to something.zip the upload works fine, but not with the ending .sketch. Any idea?
Tim

**Comment by TwizzyDizzy** [comment]
Hmmm... might still be an issue with the code to detect the mime-type. IIRC this is also solved differently in different browsers, so it might help to try it with a different browser (just for diagnostic purposes).

I'd suggest, though, to open a new issue, referencing the issue at hand as well as #7462.

Cheers
Thomas
