### ISSUE TITLE
Client-side Restivus not working when application not running on root path

### ISSUE THREAD

**Issue by lhhong** [RocketChat/Rocket.Chat#11386]
### Description:

When ROOT_URL is set to a non-root path, e.g. 'http://localhost/foo/', client application calls localhost/api/bar instead of localhost/foo/api/bar. I believe this is an issue with Restivus but since they have stopped development, we should fix the issue here.

### Steps to reproduce:

1. export ROOT_URL='http://localhost/foo/'
2. Run RocketChat
3. Login to an account on a browser

### Expected behavior:

No errors

### Actual behavior:

(Within browser console logs) 
GET http://localhost/api/v1/commands.list 404 (Not Found)
(Supposed to get from http://localhost/foo/api/v1/commands.list)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0

**Comment by hugocostadev** [comment]
Is this still happening? Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
