### ISSUE TITLE
Anonymous users can not log in or write?

### ISSUE THREAD

**Issue by FinFrn** [RocketChat/Rocket.Chat#11381]
Hey!

The latest version of 0.66.2 enabled and I noticed that anonymous users can not log in or write?

and the rights do not work either so I recommend everybody to check their rights and their activities ..

It is therefore somewhat suspicious if the rights do not work, but normal user rights are working, and users of anonymous users will have to do it manually.

The server operating system is Ubuntu 16.04.4 LTS ...

**Comment by KJ2ME** [comment]
Same problem here, this is the error on log:

`Exception while invoking method 'registerUser' Error: Can't call setUserId in a method after calling unblock     at MethodInvocation.setUserId (/var/www/Rocket.Chat/programs/server/packages/ddp-common.js:367:13)     at AccountsServer.Ap._loginUser (/var/www/Rocket.Chat/programs/server/packages/accounts-base.js:744:20)     at MethodInvocation.registerUser (/var/www/Rocket.Chat/programs/server/app/app.js:10709:20)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (/var/www/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2504:36)     at maybeAuditArgumentChecks (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at /var/www/Rocket.Chat/programs/server/packages/ddp-server.js:754:85  `

**Comment by Iratu** [comment]
I have this issue as well, I thought it would be something fixed in the last release but it appears not, I kinda need this option to work.

My logs have an error similar to the one shown above.

**Comment by altsyst** [comment]
to linked with #8982

**Comment by Beznell** [comment]
I have the same problem with 0.68.4

```
Exception while invoking method 'registerUser' Error: Can't call setUserId in a method after calling unblock
    at MethodInvocation.setUserId (/var/www/rocket/programs/server/packages/ddp-common.js:367:13)
    at AccountsServer.Ap._loginUser (/var/www/rocket/programs/server/packages/accounts-base.js:744:20)
    at MethodInvocation.registerUser (/var/www/rocket/programs/server/app/app.js:10726:20)
    at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at MethodInvocation.methodsMap.(anonymous function) (/var/www/rocket/programs/server/packages/rocketchat_lib.js:2506:36)
    at maybeAuditArgumentChecks (/var/www/rocket/programs/server/packages/ddp-server.js:1877:12)
    at DDP._CurrentMethodInvocation.withValue (/var/www/rocket/programs/server/packages/ddp-server.js:902:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at DDPServer._CurrentWriteFence.withValue (/var/www/rocket/programs/server/packages/ddp-server.js:902:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at Promise (/var/www/rocket/programs/server/packages/ddp-server.js:902:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/var/www/rocket/programs/server/packages/ddp-server.js:875:23)
    at /var/www/rocket/programs/server/packages/ddp-server.js:754:85
```

**Comment by raydebug** [comment]
same issue on 0.70.4

**Comment by benjamin-dk** [comment]
I can confirm the bug in v. 0.70.4

**Comment by SteveUNSW** [comment]
Any official fixes?

**Comment by aziz75012** [comment]
Same issueon v.0.71.1 - Debian 9 - Apache 2.4.25

`Exception while invoking method 'registerUser' Error: Can't call setUserId in a method after calling unblock     at MethodInvocation.setUserId (/opt/Rocket.Chat/programs/server/packages/ddp-common.js:367:13)     at AccountsServer.Ap._loginUser (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:744:20)     at MethodInvocation.registerUser (/opt/Rocket.Chat/programs/server/app/app.js:11352:20)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at MethodInvocation.methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2518:36)     at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85 `

**Comment by wreiske** [comment]
A fix is in, awaiting pull request review and merge.

**Comment by FaizanZahid** [comment]
okkk
