### ISSUE TITLE
/invite-all-from doesn't work properly

### ISSUE THREAD

**Issue by Cruaier** [RocketChat/Rocket.Chat#11390]
### Description:

After importing all users via LDAP sync (~150), I created some new channels and wanted to add all users to them. Apparently it doesn't work. The new channel can be public or private.

### Steps to reproduce:

1. Create a new channel
2. Enter /invite-all-from #general

### Expected behavior:

All users from #general should be in the new channel

### Actual behavior:

First user in userlist will be added and message "Invalid username" appears
![image](https://user-images.githubusercontent.com/5204940/42430609-71872230-836a-11e8-8450-f5e2f0d69c53.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: ?

**Comment by geekgonecrazy** [comment]
Is this still happening?

**Comment by Lipemenezes** [comment]
When you use `/invite-all-from` in a channel name that has  `.` in it, it doesn't work, i'm guessing other special characters could have the same issue.

I was trying to use `/invite-all-from #ahg.support` and received the following message: `The channel `#ahg` does not exist.`

I also tried wrapping the channel name in quotes / double quotes.

The solution was to rename the channel and remove the dot.

**Comment by Cruaier** [comment]
@geekgonecrazy it seems to be fixed. Tried it out again, works well. Running on RC 0.74.2.

**Comment by Mad-Onion** [comment]
`/invite-all-from #general` is still not working here with LDAP-users and room #general - RC 0.74.3. Error as already mentioned: "rocket.cat: Invalid username"

**Comment by ixaxaar** [comment]
Same issue, on version `2.1.1`, no LDAP etc.

**Comment by mojitaleghani** [comment]
the same issue happened to me as well. the command `/invite-all-from #CHANNEL_NAME` of `/invite-all-to #CHANNEL_NAME` does not work. Instead shows a message that said `Invalid username`.

**Comment by RAurelian** [comment]
Same issue happening to me also
Using v4.4.2 (Ubuntu Snaps)
Is there a work-around or another way to invite all users from one channel to another?

**Comment by RAurelian** [comment]
Issue keeps happening in v4.5.5 (snaps)

**Comment by krumelmonster** [comment]
In [this codeline](https://github.com/ggazzo/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/addUsersToRoom.js#L57) the error should not be thrown allowing other users to be added if adding one fails and this 'Invalid username' should be logged somewhere.

**Comment by krumelmonster** [comment]
I hotfixed this on my instance by replacing the throw with a `return;` which works for me.

```
      const newUser = Users.findOneByUsernameIgnoringCase(username);

      if (!newUser) {
        return;
      }
```
