### ISSUE TITLE
Suggestion: adding a 1px semi transparent border on image attachments

### ISSUE THREAD

**Issue by vjeux** [RocketChat/Rocket.Chat#1139]
If you attach an image with a white background, it's not very clear where it starts and ends. A trick we use at Facebook is to put a 1px semi transparent border in order to give it visual boundaries without altering the image too much. See a blog post I wrote on the technique: http://blog.vjeux.com/2012/image/css-semi-transparent-border-on-images.html

<img width="860" alt="screen shot 2015-10-16 at 3 16 51 pm" src="https://cloud.githubusercontent.com/assets/197597/10554526/0265764e-7419-11e5-82db-8b6f009bf7f1.png">

**Comment by graywolf336** [comment]
:+1: good suggestion, I like it.

**Comment by geekgonecrazy** [comment]
I agree.  That would help a lot.

**Comment by gmsecrieru** [comment]
:+1:

**Comment by stefanlegg** [comment]
Created a pr that adds this: #1167 and solves #1138

**Comment by gmsecrieru** [comment]
Fixed on #1170
