### ISSUE TITLE
Providing LiveChat as a separate feature and upgrading client UI to next level

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#11394]
**Is your feature request related to a problem? Please describe.**
**Client side** - client side UI is not good.  
**Admin side** - To integrate livechat with website, it needs rocket.chat messenger as a backend. It's an additional functionality which livechat admins might not need.
(Client side can be considered as high priority since admin interface does not provide any business value).

**Describe the solution you'd like**
**Client side** - UI from client side can be made more intuitive, clear and more guided. It's needed to beat other competitors in the market. i.e. https://www.intercom.com/messenger, https://www.livechatinc.com/features/, https://www.tawk.to/ (This one is free for lifetime) . Since, current LiveChat feature is open source, lot of users will use it.

**Admin side** - LiveChat can be provided as a standalone feature. It can have integration with rocket.chat, but not necessarily. Livechat admins should only be provided with interface to interact with agents and related configurations. 

Above request is just an honest opinion. Please let me know if you have any suggestions related to it.

**Comment by ggazzo** [comment]
we are following these steps, I am closing this issue for organizational reasons, thanks for your suggestion .. anything please let us know
