### ISSUE TITLE
Private Channels not found

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#11393]
### Description:
- From Admin I can see the channels, but i am not able to search it from search tab, while accessing it through url, the bellow message is shown.
- PS I am the member of the channels though.

<img width="1059" alt="screen shot 2018-07-09 at 1 50 32 pm" src="https://user-images.githubusercontent.com/4321549/42438217-20c175c0-837f-11e8-985f-068106287edc.png">

<img width="931" alt="screen shot 2018-07-09 at 1 50 12 pm" src="https://user-images.githubusercontent.com/4321549/42438219-22c0867c-837f-11e8-91c0-e4e35dd493b2.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 0.63.3
- Operating System: Mac/ Windows
- Deployment Method: 
- Number of Running Instances: 4
- DB Replicaset Oplog: 1
- NodeJS Version:  8.5 
- MongoDB Version:

**Comment by gabriellsh** [comment]
This doesn't happen anymore, if you still face this issue, please reopen.
