### ISSUE TITLE
Select avatar later option

### ISSUE THREAD

**Issue by riaan53** [RocketChat/Rocket.Chat#114]
Hi,

Like the progress!

I have an suggestion.

It will be great if there is an option for the user to select the avatar later and then just use the default like you had in the beginning with the R block for Riaan.

After registration a user wants to check out the app asap to see if he likes it or not (the first few minutes are critical for user retention) and to make him find a foto first can be a problem for some.

Just a suggestion like I said :)

Regards,
Riaan

**Comment by rodrigok** [comment]
Makes sense, because this we try to suggest photos from social services and from gravatar :D

Lets see what more people think about this.

**Comment by dewajac** [comment]
+1

**Comment by engelgabriel** [comment]
Done.

Now we just need to make the email optional too.
