### ISSUE TITLE
Snap function restoredb not working as intended

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat#11405]
### Description:
**EDIT:** Okay, actually I was just too dumb to read and didn't expect the restore script to have a backup function. Nevertheless both are not very well structured so I am going to open a PR to try to make it better :)

I just tried to migrate from one server to another and restore the Rocket.Chat database via the provided snap function which can be found [here](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#1-stop-your-rocketchat-server-1).

### Steps to reproduce:

1. Copy backup to server
2. Execute `snap run rocketchat-server.restoredb /var/snap/rocketchat-server/common/backup_20180709.tgz`
3. Confirm with `y` + `Enter`

### Expected behavior:

Restoring the database

### Actual behavior:

`/snap/rocketchat-server/1307/bin/restoredb: line 32: backupdb: command not found`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: openSUSE 15.0
- Deployment Method: snap
- Number of Running Instances: 1

### Additional context

In the script - [which can be found here](https://github.com/RocketChat/Rocket.Chat/blob/develop/.snapcraft/resources/restoredb) - there is a dialog with the following definition:
```    
read choice
    [[ "${choice,,}" = n* ]] && return
    [[ "${choice,,}" = y* ]] && backupdb && return
exit
```

But there is no function called `backupdb` and so it will abort.

**Comment by avenetj** [comment]
Any update on this issue ? Tried to use the edge version of the package instead but facing another bug with it.

**Comment by der-eismann** [comment]
As long as #11420 isn't merged there won't be any updates.
