### ISSUE TITLE
Auditoria de conversas

### ISSUE THREAD

**Issue by leozoccoli** [RocketChat/Rocket.Chat#11409]
Boa noite, preciso de um chat que me de a possibilidade de fazer auditoria nas conversas internas da empresa, existe essa funcionalidade no rocket chat?

Obrigado.

**Comment by dotsomething** [comment]
Amigo, se possível, mantenha o idioma em inglês. Todavia, já há uma discussão sobre isso.

#2869

**Comment by TwizzyDizzy** [comment]
Hey @leozoccoli 

I'm sorry, but I have to close this issue. We only accept issues in english and require everybody to give basic information about their setup. You did neither of those. Feel free to open a new and more complete report/feature request. For all other questions, do not hesitate to head over to the [forums](https://forums.rocket.chat) :)

Cheers (+close)
Thomas
