### ISSUE TITLE
Windows client is duplicating the servers list

### ISSUE THREAD

**Issue by rmundel** [RocketChat/Rocket.Chat#11402]
### Description:

Suddenly my rocket.chat Windows client is mirroring the server list as shown:

### Steps to reproduce:

Don't know how to reproduce it.

### Expected behavior:

The list should not appear duplicated.

### Actual behavior:

Screenshot:

![rocket chat _2018-07-09_11-21-51](https://user-images.githubusercontent.com/13142574/42459946-c57db516-836a-11e8-8756-6cda7a5e4242.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Active
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Aditional information

- Client version: v2.11.0

**Comment by tassoevan** [comment]
Please, could you file this issue [here](https://github.com/RocketChat/Rocket.Chat.Electron/issues)?

**Comment by kaiiiiiiiii** [comment]
Please don’t open another issue in the electron repository! This issue has been reported a couple of times yet and will be fixed in a future app release :)

**Comment by rmundel** [comment]
I see. Sorry about that. Didn't realize about the Electron repo. Thanks.
