### ISSUE TITLE
linux app doesn't let me do admin of rooms

### ISSUE THREAD

**Issue by petersilva** [RocketChat/Rocket.Chat#11401]
### Description:
When I go in the web interface I get the icon to add people to my room,
when I am in the linux application, I don't.  Cannot add users from linux app.

### Steps to reproduce:

1. create a room using the web app, with yourself as owner.
2. start up linux app, go to room.

### Expected behavior:

I view the room, and I see I am listed as the owner in both the web page and the application.
I expect to see the person with a plus sign beside it, on the top-right, to let me add people to the room.

### Actual behavior:

There is no person add icon in the linux application.
I only see that icon on the web page, not in the linux application.
Cannot add people to the room from Linux app.

### Server Setup Information:

I'm a user, no access to server setup information... have a look at: https://message.gccollab.ca

### Additional context

% dpkg -l | grep rocketchat
ii  rocketchat                                 2.10.5-686                                  amd64        
%

**Comment by petersilva** [comment]
Should I report an issue there instead?
It's dead easy to reproduce for me. 
 You're on linux,
 you go to https://message.gccollab.ca with a browser (I used Chrome and Firefox different times.)
I create a private room.
The room created has this at the top right:
![rocketchat_webpage_topright_ from 2018-07-11 22-23-01](https://user-images.githubusercontent.com/394117/42609203-5a5e129e-8559-11e8-9523-ce51c2731df5.png)

notice the bust icon with the + beside it.  If I am authenticated as the same user, and I log into the same room from the Electron client, I see:

![rocket_chat_linux_app_topright_screenshot from 2018-07-11 22-26-53](https://user-images.githubusercontent.com/394117/42609253-b0a26ae2-8559-11e8-9671-81815a5ae889.png)

missing the bust icon.

If I enter a text message, I get the same identity, and am tagged as owner on both, but I cannot invite any users from the Electron app.

**Comment by petersilva** [comment]
it does not happen on open.rocket.chat.  but it is readily reproducible on message.gccollab.ca

**Comment by rodrigok** [comment]
@petersilva which RC server version are you using?

**Comment by geekgonecrazy** [comment]
Going to close due to inactivity.  Guessing it’s already been resolved in newer releases
