### ISSUE TITLE
Livechat: Agent redirected to incorrect url (404-error) on taking Livechat (Guest Pool)

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#11419]
### Description:

If Guest Pool routing is enabled, and agent takes-up a Livechat , it is redirected to incorrect url. So gives 404 error.

<img width="396" alt="screen shot 2018-07-10 at 9 04 27 pm" src="https://user-images.githubusercontent.com/16938349/42521034-6d8eee26-8485-11e8-9715-e5dbf078eda4.png">

### Steps to reproduce:

1. Under Administration -> Livechat -> routing -> set routing method to. 'Guest Pool'.
2. When a request comes up, click on 'Take it' Button.

Its redirected to incorrect url.

### Expected behavior:

Correct URL is shown below.

`http://localhost:3000/live/cjw6RE59y2nrwYCFm` 

### Actual behavior:

URL incorrect. `http://localhost:3000/live`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-develop
- Operating System: MacOS High Sierra
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.3 - x64

**Comment by renatobecker** [comment]
Hi @pkgodara.
This issue is already fixed and merged, please take a look at here: #11406.

Thanks.
