### ISSUE TITLE
[New] Notifications audio files as .wav in resources folder

### ISSUE THREAD

**Issue by jwallet** [RocketChat/Rocket.Chat#11418]
**Describe the solution you'd like**
I suggest adding a way to import custom notification sound or add some more to the list.

**Describe alternatives you've considered**
We could also put the sound available in the resources folder if someone wants to replace one.

**Additional context**
I would like to add Slack notification sound to the app (to the default if they're not copyrighted, or replace a old sound on the RC Client by drag and drop) because I was used to the sound of it and RC sound feels weird

**Comment by vynmera** [comment]
There's a tab in Administration that does exactly this :)

Administration → Custom Sounds

**Comment by jwallet** [comment]
do you think it might be nice to let the users change their audio files in resources folder as well
