### ISSUE TITLE
Opening the right sidebar makes the content flash

### ISSUE THREAD

**Issue by vjeux** [RocketChat/Rocket.Chat#1142]
If you open the sidebar on any chat with more than one page, you can see the content flash. I recorded a video to see it frame by frame and what happens:

1) the content is resized 
2) the content is scrolled all the way down

Unfortunately, because those two actions are not done in the same frame, it flashes. Would be nice to sync the scroll with the opening of the sidebar.

<img width="1042" alt="screen shot 2015-10-16 at 3 22 45 pm" src="https://cloud.githubusercontent.com/assets/197597/10554601/d4b93428-7419-11e5-9325-563b5a33c94f.png">
<img width="1042" alt="screen shot 2015-10-16 at 3 22 48 pm" src="https://cloud.githubusercontent.com/assets/197597/10554600/d4b90ec6-7419-11e5-844a-98217a1ddc86.png">
<img width="1042" alt="screen shot 2015-10-16 at 3 22 51 pm" src="https://cloud.githubusercontent.com/assets/197597/10554602/d4d868d4-7419-11e5-9e33-9cb80df3b863.png">
##

**Comment by engelgabriel** [comment]
The scroll to bottom is not synchronous so it jumped. We need to update the scroll position when the content was changed... when anything can happen that changes the content of the scroll or the size of the scroll area and not during a setTimer.

It would be actually surprisingly easy with React

http://blog.vjeux.com/2013/javascript/scroll-position-with-react.html

**Comment by MartinSchoeler** [comment]
@vjeux I think that has already been fixed, if not, please reopen this. Thanks!
