### ISSUE TITLE
Please, mark as read all answers when click in a channel

### ISSUE THREAD

**Issue by lucasrhuan** [RocketChat/Rocket.Chat#11421]
### Description:

Please, mark as read all answers when click in a channel

### Steps to reproduce:

1. See the channel with unread answers;
2. Click in that channel;
3. Click in the button "mark as read";

### Expected behavior:

1. See the channel with unread answers;
2. Click in that channel and automatically mark the answers as read;

Thanks!

**Comment by piotrkochan** [comment]
I personally prefer as it is now - maybe there should be per/group or channel configuration to toggle that?

**Comment by reetp** [comment]
This is a new feature request and should be opened in the forums:
https://forums.rocket.chat/c/feature-requests

(Personally I agree it would be better per user or somesuch as I prefer the current system)

Thank you.

**Comment by reetp** [comment]
@rocket-cat close
