### ISSUE TITLE
Add possibility to show all rooms a user is in

### ISSUE THREAD

**Issue by apfelbox** [RocketChat/Rocket.Chat#11424]
**Is your feature request related to a problem? Please describe.**
We added some guests and somebody forgot to remove the "add to default channel" check. So now the guest was able to read `#general` which was not the best case scenario...

**Describe the solution you'd like**
I would love 

a) a way to audit a user, like listing all the rooms he/she has access to
b) disable the checkbox "add to default channel" by default or at least for guests

**Describe alternatives you've considered**
Not sure.

**Additional context**
n/a

**Comment by reetp** [comment]
NFRs are now being referred to the forums to try and keep issues to bugs only.

Please open a thread there.

Thanks

**Comment by reetp** [comment]
@rocket-cat close
