### ISSUE TITLE
Voice and video record buttons are inactive

### ISSUE THREAD

**Issue by CoDooku** [RocketChat/Rocket.Chat#11429]
### Description:

Voice and video record buttons are visible but inactive in windows 10 desktop app, Mozilla Firefox 52.9.0 (x64), Microsoft Edge 42.17134.1.0

### Actual behavior:

When I click on record button nothing happens... at all...

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: debian 9.4 (4.9.0-6-amd64)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: v8.11.3
- MongoDB Version: -

**Comment by yZhenyuanLiu** [comment]
same issue for me

**Comment by yZhenyuanLiu** [comment]
How to resolve？Please

**Comment by CoDooku** [comment]
First of all you need running web server with SSL.

I use snap version of RC and [this ](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/)instruction helped me.
