### ISSUE TITLE
[BUG] Contact list sorting swaps

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat#11428]
### Description:

The contact list sorting is swapping after the upgrade to 0.66.X
Sorting: Alphabetical
Read on top: deactivated

### Steps to reproduce:

1. Write a direct message to a contact while sorting in alphabetical order is active
2. The contact goes up in the concat list - not to the first position but to the second or third
3. After you have read the text the list changes again

### Expected behavior:

Sorting stays unchanged

### Actual behavior:

Sorting swapps around

![11-07-_2018_09-48-23](https://user-images.githubusercontent.com/26709898/42561675-0623a202-84fa-11e8-8567-40fcfc33bbde.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System:  ubuntu lts 16.04
- Deployment Method:  snap
- Number of Running Instances: 1
- NodeJS Version: v8.11.3

### Additional context

Problem occurs in the desktop and web app.
https://forums.rocket.chat/t/contact-list-sorting-0-66-1/1511

**Comment by ggazzo** [comment]
@ArchimedesFM I'm quite sure that was fixed here #11358. Are you able to try on develop version or on https://open.rocket.chat?

**Comment by ArchimedesFM** [comment]
We dont have a test environemt so i am not able to test it yet. i have to wait until the release.
But thank you for your answer!
