### ISSUE TITLE
Rocketchat Subscription not created while creating group with members from API.

### ISSUE THREAD

**Issue by rojesh** [RocketChat/Rocket.Chat#11426]
### Description:

I have a private group to be created with around 400+ members. I used this api https://rocket.chat/docs/developer-guides/rest-api/groups/create/ to create the group by specifying the members. If a go to the admin/rooms and search for the group, it lists the group with correct number of members that I initially created but if I go to the channel and list its members it only shows around 123 members. Digging deeper I found out that the subscription entries for those missing members were not created. What could be the issue that resulted in not creating the rocketchat_subscription entries for those members? Any help appreciated.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.63.3
- Operating System: linux
- Number of Running Instances: 4
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.2
- MongoDB Version: 3.2.20-3.11

**Comment by ramanamatya** [comment]
Any update on this ?

**Comment by MarcosSpessatto** [comment]
@rojesh can you please share your http request? Because looking at the code, the only way some subscription is not created, is the user does not exist. As you [can see here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/functions/createRoom.js#L73).
