### ISSUE TITLE
What's the Apps status, where can I get the document

### ISSUE THREAD

**Issue by imhazige** [RocketChat/Rocket.Chat#11432]
Here the Apps means something related to https://github.com/RocketChat/Rocket.Chat.Apps-cli/blob/master/README.md,

We are very interesting in this feature, but can not get more information from the document, we found many code like:
https://github.com/RocketChat/Rocket.Chat.Apps-engine
https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition

We want to understand how to implement a APP and what it can do.

Could you provide more document?

**Comment by vynmera** [comment]
You can find sample Apps here: https://github.com/graywolf336/RocketChatApps

**Comment by imhazige** [comment]
@vynmera thank you, I will have a look.

but still not much document, is it hinting us to read the code directly?

**Comment by kaiiiiiiiii** [comment]
Another App:
https://github.com/kaiiiiiiiii/AppearCommandApp

And you're right, there's still a lack of documentation, but this will change in the future as the App Framework is not official released yet :)

**Comment by vynmera** [comment]
Another App: https://github.com/vynmera/Rocket.Chat.WordFilter

There is a very minor amount of documentation here: https://rocketchat.github.io/Rocket.Chat.Apps-ts-definition/globals.html

**Comment by imhazige** [comment]
Hi, @vynmera 

when I try to package the app https://github.com/graywolf336/RocketChatApps

it throw an error
```sh
PS D:\xxxt\RocketChatApps\testing-app> rc-apps package
packaging your app... !
Error: absolute path: D:/xxx/RocketChatApps/testing-app/app.json
```

**Comment by vynmera** [comment]
@imhazige weird... what happens if you just zip up one of the folders yourself? like, just create a zip of `D:/xxx/RocketChatApps/out-of-office/` and put that straight into your Apps

**Comment by imhazige** [comment]
@vynmera 

I clone the code from the github,
cd to the out-of-office folder, 
npm install
rc-apps package

then error happen

**Comment by imhazige** [comment]
@vynmera 

I have had a look at the example app code, app can handle message, can handle command. can app build a ui to allow user to use as a web app?

**Comment by MartinSchoeler** [comment]
@imhazige @vynmera @kaiiiiiiiii Could you move this discussion to the [forums](https://forums.rocket.chat/)? Thanks!

**Comment by graywolf336** [comment]
@imhazige please open an issue directly on the CLI repository: https://github.com/RocketChat/Rocket.Chat.Apps-cli
