### ISSUE TITLE
The new message bar doesn't disappear after you've seen the messages

### ISSUE THREAD

**Issue by vjeux** [RocketChat/Rocket.Chat#1143]
The new message bar is a really cool feature. Unfortunately, it does not behave as I expect it to be. Once I scroll all the way top to read the unread messages, it disappears as the count goes to 0. But when I scroll back down it reappears!?

Once you reach the top of the unread messages, it should not reappear.

<img width="888" alt="screen shot 2015-10-16 at 3 26 46 pm" src="https://cloud.githubusercontent.com/assets/197597/10554655/65038c04-741a-11e5-9b04-84b33df45c7e.png">

The only way right now to make it disappear is to click the CLEAR button
##

**Comment by graywolf336** [comment]
I do believe this is related to #885

**Comment by MartinSchoeler** [comment]
@vjeux hasn’t seen this bug recently, for now i will close this. Please reopen this if the bug show up again.
