### ISSUE TITLE
Required permissions for the MongoDB User

### ISSUE THREAD

**Issue by fbreckle** [RocketChat/Rocket.Chat#11449]
Hi,

as per https://github.com/RocketChat/docs/issues/69#issuecomment-238953918, rocketchat requires a user to have `root` role on the `admin` db and `owner` role on the `rocketchat` db.
As per mongodb docs, both these roles include the `userAdmin` role.
The issue I'm having is that MongoDB Atlas does not allow giving a database user anything resembling the `userAdmin` role.
I can run my setup (which does not include the `userAdmin` role) and it APPEARS to run without problems. Im just afraid that something eventually might break.

So my question is: Does RocketChat actually make use of these `userAdmin` privileges?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
