### ISSUE TITLE
Attachments not showing on ios

### ISSUE THREAD

**Issue by Stabatha** [RocketChat/Rocket.Chat#11448]
### Description:

Attachments aren't showing on iOS. only a blank square that says Label above it.

### Steps to reproduce:

Upload Attachment

### Expected behavior:

Attachment to display

### Actual behavior:

Attachments aren't showing on iOS. only a blank square that says Label above it.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.66.3
- Operating System:  CentOS 7.4
- Deployment Method:  GIT
- Number of Running Instances:  1

**Comment by rafaelks** [comment]
@Stabatha Can you share a screenshot please?

**Comment by Stabatha** [comment]
@rafaelks sorry, screenshot of what?

**Comment by rafaelks** [comment]
@Stabatha Of your attachment not displaying.
