### ISSUE TITLE
[workaround] Ordering channels alphabetically not working, after upgrading version

### ISSUE THREAD

**Issue by jwallet** [RocketChat/Rocket.Chat#11440]
If your channels don't appear in alphabetical order, we found out it was probably related to the new feature unread on top, so channels that have new activity will appear at the bottom when "alphabetical order" is checked and "unread on top" is unchecked, until all your channels got at least one new activity (message) after the upgrade.

workaround: go in each channel, right a quick message and delete it, all channels will now be ordered properly

**Comment by hstenzel** [comment]
This won't work if there are read-only channels in the mix.

Another workaround is to favorite all channels. Then all channels will once again be alphabetized, except in the "Favorites" section instead of in the "Channels" section.

**Comment by tanc** [comment]
See #11545 for the bug report
