### ISSUE TITLE
How to Outsource Authentication?

### ISSUE THREAD

**Issue by masterbater** [RocketChat/Rocket.Chat#11465]
Hi guys, how to outsource your authentication, do you support accesstoken, where i can verify the tokens expiration and payload. what signature Like jwt? 
I want to do a rest api to my own backend but needs to verify the user.

Is there anyway i could check the accessToken to my own server.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
