### ISSUE TITLE
Nginx + Docker subfolder configuration

### ISSUE THREAD

**Issue by olegberman** [RocketChat/Rocket.Chat#11460]
### Description:

Not able to get Rocket.chat to work in a subfolder `https://domain.com/chat` with Docker + Nginx. Can anyone possibly share their working configuration? 

### Expected behavior:

Chat to load as usual.

### Actual behavior:

These are errors that I'm getting (this is the closest I got to get it running):

![issue 2](https://user-images.githubusercontent.com/6267340/42710756-09f5bad2-86ee-11e8-8ba6-8161f253b698.png)

![issue](https://user-images.githubusercontent.com/6267340/42710694-bcabe54e-86ed-11e8-921e-54c1008e1532.png)

### Server Setup Information:

- Using CentOS
- Running recent Rocket.chat release in Docker (with docker-compose)

## nginx.conf

```nginx
  # the nginx server instance
  server {
      server_name domain.com;

      location / {
         # ... different app
      }

	location /chat/ {
            # ... some irrelevant stuff

           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection 'upgrade';
           proxy_set_header Host $host;
           proxy_cache_bypass $http_upgrade;
           proxy_pass http://0.0.0.0:3000/;
           proxy_redirect off;
	}

        # found this hack in one of the issues to make /sockjs endpoint work
        location /sockjs {
        	proxy_http_version 1.1;
        	proxy_set_header Upgrade $http_upgrade;
        	proxy_set_header Connection 'upgrade';
        	proxy_set_header Host $host;
        	proxy_cache_bypass $http_upgrade;
        	proxy_pass http://0.0.0.0:3000/sockjs;
        	proxy_redirect off;
        }

    listen 443 ssl; # managed by Certbot
    ... irrelevant certbot stuff
}
```

### Additional context

Hosting on the subdomain working just fine! 

Now it looks like Rocket.chat tries to call `/api` path, and I can't add the same hack as `location /sockjs {` as I have an API for a different app there. It should be calling `/chat/api` and `/chat/sockjs` ideally. 

Here is more configuration from MongoDB:
```javascript
rs0:PRIMARY> db.rocketchat_settings.find({ "_id" : "CDN_PREFIX"})
> { "_id" : "CDN_PREFIX", "value" : "" }
```

```
rs0:PRIMARY> db.rocketchat_settings.find({ "_id" : "Site_Url"})
> { "_id" : "Site_Url", "value" : "https://domain.com/chat", "type" : "string", "i18nDescription" : "Site_Url_Description", "public" : true, "group" : "General", "packageValue" : "http://localhost:3000", "valueSource" : "packageValue", "hidden" : false, "blocked" : false, "sorter" : 1, "i18nLabel" : "Site_Url", "autocomplete" : true, "ts" : ISODate("2018-07-13T19:31:01.211Z"), "_updatedAt" : ISODate("2018-07-13T19:31:01.211Z") }
```

I also tried updating these values `CDN_PREFIX` and `Site_Url`, and changing around the nginx config but nothing helps. Has anyone managed to get Docker+nginx+sudomain combination working? 

P.S. I've read through #2655, #4546, #8487 and none of these provide a solution. 
Also I read https://rocket.chat/docs/installation/manual-installation/running-in-a-sub-folder/ 
and https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/

**Comment by angusvb** [comment]
For me this works:
`        location /rocketchat {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forward-Proto http;

            proxy_set_header X-Nginx-Proxy true;
            proxy_pass http://127.0.0.1:3000/rocketchat;
            proxy_redirect off;
        }`

**Comment by angusvb** [comment]
And my docker-compose.yml
```
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://127.0.0.1/rocketchat/
    - Accounts_UseDNSDomainCheck=False
  links:
    - db:db
  ports:
    - 3000:3000
```

**Comment by olegberman** [comment]
Thank you @angusvb! Will try this.

**Comment by angusvb** [comment]
@olegberman  thx, that is the part that I was still figuring out!

**Comment by olegberman** [comment]
@angusvb can you confirm you're also having this issue integrating Zapier? 11509

**Comment by edwardando** [comment]
@angusvb thanks for posting your config, got me off the ground!

**Comment by sopheck** [comment]
@angusvb This saved my day, thanks a lot for sharing! :pray:
