### ISSUE TITLE
Slash Commands Don't Handle New Lines

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#11469]
**Is your feature request related to a problem? Please describe.**
The problem is the slash command gets only first line of message as arguments. All other lines are ignored.

**Describe the solution you'd like**
I think that all lines should be parsed as command arguments along with every new line (\n), so in case of command:

```
/examplecommand hello my name is
Peter and I live
in Poland
```

The command arguments should be processed as:

`["hello", " my", "name", "is", "\n", "Peter", "and", "I", "live", "\n", "in", "Poland"]`

But right now command receives only:

`["hello", "my", "name", "is"]`

**Describe alternatives you've considered**
Maybe there should be some command property like "argumentAsText: boolean" which will pass all given text to the command as one argument:

```
export class ExampleCommandCommand implements ISlashCommand {
  public command: string = 'example';
  public argumentAsText: boolean = true;

  ...
  public async executor(context: SlashCommandContext, ....) {
    this.logger.info(context.getArguments()[0]); // hello, my name is\n ...
  }

```
**Additional context**
---none---

**Comment by graywolf336** [comment]
This is actually not an issue with the Apps framework itself, but the Rocket.Chat handler. If you do this with regular commands in Rocket.Chat, you will experience the same thing.
