### ISSUE TITLE
Rocket Chat without MongoDB???

### ISSUE THREAD

**Issue by chatnl** [RocketChat/Rocket.Chat#11477]
Hi,

I must be missing something completely. I have installed Rocket Chat with the SNAP method. I was under the impression that this would also install MongoDB, but I can't find it anywhere? 

Can somebody shed some light on this? Rocket Chat is working so the installation was succesfull, but I would like to install an admin tool to manage the database. I can not find the mongod.conf file and entery mongo or mongod on the command prompt doesn't work. 

Please help.

Regards,

Stef

**Comment by piotrkochan** [comment]
But it is somewhere.

> You can also check on the status of Mongo and Caddy:
> 
> sudo service snap.rocketchat-server.rocketchat-mongo status
> sudo service snap.rocketchat-server.rocketchat-caddy status

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

**Comment by chatnl** [comment]
Ok, yes that's what I thought also. I was using the standard commands like mongo and mongod which didn't do anything. 

The sudo service snap.rocketchat-server.rocketchat-mongo status command gives the following output:

 snap.rocketchat-server.rocketchat-mongo.service - Service for snap
application rocketchat-server.rocketchat-mongo
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-mongo.s
ervice; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-07-15 12:54:58 CEST; 1 day
 20h ago
 Main PID: 1868 (sh)
    Tasks: 72 (limit: 4915)
   CGroup: /system.slice/snap.rocketchat-server.rocketchat-mongo.service
           ├─1868 /bin/sh /snap/rocketchat-server/1307/bin/startmongo
           └─1911 mongod --bind_ip 127.0.0.1 --pidfilepath /var/snap/rocketchat-
server/common/mongod.pid --smallfiles --journal --dbpath=/var/snap/rocketchat-se
rver/common --replSet rs0

================

Now I checked the paths but I can not find the file mongodb.conf. I would like to change that file in order to be able to remote access mongodb and use Robo 3T to manage the database. 

Other tips that allow me to manage the database are welcome too. I need to be able to monitor the IP addresses of users in order to be able to ban them with IPtables.

Thanks,

Stef

**Comment by piotrkochan** [comment]
I'm not sure but I think that if RocketChat port is 3000 then mongo port is 3001.

**Comment by chatnl** [comment]
No it is not on 3001. Still have to figure out how to connect to it with Robo 3T.

**Comment by ardabeyazoglu** [comment]
Is there any update on this ? How would you connect to mongo from cli or external tools ?

**Comment by ardabeyazoglu** [comment]
Ok, i found it. @chatnl You can connect by using `mongo` binary inside `/snap/rocketchat-server/current/bin`. As there is no auth, typing `./mongo` will connect directly. From robo3t, i think you can just connect by using ssh proxy, because i did it in navicat software. They must use the same methods to connect anyway.

**Comment by chatnl** [comment]
> Ok, i found it. @chatnl You can connect by using `mongo` binary inside `/snap/rocketchat-server/current/bin`. As there is no auth, typing `./mongo` will connect directly. From robo3t, i think you can just connect by using ssh proxy, because i did it in navicat software. They must use the same methods to connect anyway.

Ok I will try that. Thanks!

**Comment by chatnl** [comment]
I tried it but I can not connect to Mongo using SSH in robo3t. It connects to the server but not to Mongo.

**Comment by ardabeyazoglu** [comment]
@chatnl 1 thing to check first:
Can you connect by runnin `./mongo` inside `/snap/rocketchat-server/current/bin` ?

**Comment by chatnl** [comment]
No I get an error:

./mongo: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by ardabeyazoglu** [comment]
Looks like mongo client is using libssl and your distro is either missing it, or there is a version mismatch. Try installing it again by apt or yum depending on your distro. For debian and ubuntu:
    `apt-get install libssl-dev`

**Comment by reetp** [comment]
@chatnl Note unless this a breakage in Rocket or Mongo (and you can connect to Mongo on the server so it seems fine) it is still a support issue rather than a bug.

Your best strategy is to discuss remedies in the forums or https://open.rocket.chat/channel/support and leave github for bugs only.

**Comment by chatnl** [comment]
@reetp Sure you are right, but there's often no respons in the forums. I will try the support link instead. 

Also. What defines a bug? I installed a snap and it didn't give me an error during installation, yet I can not access MongoDB with the normal tools because a dependency isn't met. That sounds to me as a bug in the installation?

**Comment by reetp** [comment]
A bug is when either Rocket or its supporting software such as Mongo doesn't not behave correctly causing Rocket to fail.

In your situation Rocket appears to be functioning correctly. You can connect to Mongo locally so that is functioning correctly.

Your issue is remote access to Mongo which has nothing to do with the proper functioning of Rocket or Mongo, but is a configuration issue with your setup. It is not a bug.

**Comment by chatnl** [comment]
@ardabeyazoglu thanks for your help. I will try this in a test environment.
