### ISSUE TITLE
Rename History

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1147]
I'm thinking we may need to rename this to match its functionality.  

![image](https://cloud.githubusercontent.com/assets/51996/10556799/68c171cc-7455-11e5-875e-c4219a2622cc.png)

Right now it makes it seem like this is where you would go to search through message history.  When right now all it does is show you archived channels.

**Comment by beernutz** [comment]
Agreed.  Thank you for opening this issue.

**Comment by rwakida** [comment]
:+1:

**Comment by graywolf336** [comment]
It also shows you the current channels, pretty much shows you everything and not just archived channels. History is pretty relevant to what it actually does. The search though on that page is a little confusing.

**Comment by geekgonecrazy** [comment]
Right all channels you are or ever have been apart of.  Which is a history.  But its kind of confusing.. 

If it said "All Channels"

Then inside of it properly organized your archived / hidden / and then other channels.  It would be super useful.

**Comment by sunnipaul** [comment]
IMHO, it should be called Search as it searches for channels or groups.
HISTORY should list rooms the user visited
