### ISSUE TITLE
Rocket.Chat+ on MAC crashes when PPPoE connection is closed.

### ISSUE THREAD

**Issue by sadnoodles** [RocketChat/Rocket.Chat#11478]
### Description:

Rocket.Chat+ client(Version 2.11.0) on macOS(10.13.5) , crashes when PPPoE connection is closed.

### Steps to reproduce:

1. Connect PPPoE.
2. Start Rocket.Chat client , wait for connecting server done. Hide then Rocket.Chat interface.
3. Close PPPoE. Click the 
![image](https://user-images.githubusercontent.com/2931912/42790993-66d27ba0-89a0-11e8-8f50-4a85e7b02d19.png) on dock, then crash happens.

![image](https://user-images.githubusercontent.com/2931912/42790989-5c282722-89a0-11e8-8a85-bd6024dc49bc.png)

![image](https://user-images.githubusercontent.com/2931912/42791042-ac397eb4-89a0-11e8-9805-06c60fde8575.png)

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #867](https://github.com/RocketChat/Rocket.Chat.Electron/issues/867) via [**ZenHub**](https://www.zenhub.com/)
