### ISSUE TITLE
Multi server capability for mobile apps

### ISSUE THREAD

**Issue by schepely** [RocketChat/Rocket.Chat#1148]
Currently I cannot select a server when running a mobile app. (Android in my case).
This is the main issue that is holding me back of using Rocket and replacing Slack everywhere.

**Comment by geekgonecrazy** [comment]
This is a good issue to have open.  A lot of people want this.  So good idea to have a ticket to track the development

**Comment by gmsecrieru** [comment]
I think this is a duplicate of #577

**Comment by geekgonecrazy** [comment]
@gmsecrieru you're right we need to maybe rename that one so people can find it maybe?

**Comment by gmsecrieru** [comment]
I will copy this title. 

@schepely could you please follow up on #577 ?
