### ISSUE TITLE
Rocket Chat File Attachment test

### ISSUE THREAD

**Issue by phqtuyen** [RocketChat/Rocket.Chat#11490]
Hi all,
While I was reading the code for Rocket Chat Integration test, specifically file "main-content.page.js", there is this line about fileUpload (94 - 98):

	//uploads a file in the given filepath (url).
	fileUpload(filePath) {
		this.sendMessage('Prepare for the file');
		this.fileAttachment.chooseFile(filePath);
	}
I cannot find where is fileAttachment defined. I search the whole project and only see it appears twice, it is called another time in 12-setting.js and that's it. I really appreciate it if someone can provide a little more insight on the internal mechanism of this piece of code. Many thanks.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
