### ISSUE TITLE
[Bug] Writing KaTeX Code in inline Code Blocks breaks text.

### ISSUE THREAD

**Issue by archang3l-media** [RocketChat/Rocket.Chat#11495]
### Description:

Writing KaTeX into inline or Multiline Code sometimes gives weird results.

### Steps to reproduce:

1. type `in dieser umgebung sollte die formatierung für TeX ausgeschaltet werden. $Aber das wird sie nicht$` (inline/multiline code. Test string means: "in this environment, TeX Formatting should't be applied $but it is$")

### Expected behavior:

The text will be written out.

### Actual behavior:

in dieser umgebung sollte die formatierung für TeX ausgeschaltet werden. =!=CkB2i9eMrcwcevZ7i=!=
The part in KaTeX is garbled

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66
- Operating System: centOS
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: MongoDB shell version v3.4.16
git version: 0d6a9242c11b99ddadcfb6e86a850b6ba487530a

### Additional context

--not applicable-- 

### Relevant logs:

--not applicable--

**Comment by fliptrail** [comment]
This has been solved. Can be closed

**Comment by archang3l-media** [comment]
[Closed] Fixed. Thanks everyone
