### ISSUE TITLE
Installation in (Windows) Autostart

### ISSUE THREAD

**Issue by florianlieb** [RocketChat/Rocket.Chat#11503]
I'd like to switch from Skype to Rocket.Chat, but unfortunatelly my colleagues still continue to use Skype, because it is automatically there when they start their computer.

It would be cool if the Rocket.Chat client would register itself in Autostart. Otherwise users would have to do that for themselves.

**Comment by kaiiiiiiiii** [comment]
Hi @florianlieb,

1. Wrong repo :) https://github.com/RocketChat/Rocket.Chat.Electron
2. You can already select "Start App on Startup" during the installation process of the client (may only works if you install for all users?!).

Cheers,
Kai

**Comment by MartinSchoeler** [comment]
Yes, as @kaiiiiiiiii mentioned, this issue belongs to https://github.com/RocketChat/Rocket.Chat.Electron. please reopen this there. Thanks!

**Comment by florianlieb** [comment]
Whoops, sorry for that.

**Comment by ged-nn** [comment]
Need key autostart for silent install "/autostart"
