### ISSUE TITLE
[BUG] No direct messages with new LDAP users

### ISSUE THREAD

**Issue by deadmanIsARabbit** [RocketChat/Rocket.Chat#11505]
### Description:

Since upgrading to 0.66.3 from 0.65.2 a direct chat with new LDAP users is not possible.
Separate rooms will be created for both users in which each user can write and not read and vice versa.

### Steps to reproduce:

1. Sync new user from LDAP (e.g. 'Alice')
2. Bob searches for 'Alice' and writes her a new message

### Expected behavior:

Alice get the message from Bob and can reply to him.

### Actual behavior:

Alice sees a new message, but can't access the room with the message. She will be notified by mail about the message.
If Alice searches for Bob and writes him a message Bob will get the message in a new room which he again can't access. If he tries to enter the room he gets thrown into the one which was created as he initially wrote to Alice.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3 
- Operating System: CentOS Linux release 7.5.1804
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: N/A
- NodeJS Version: v8.11.2
- MongoDB Version: 3.6

### Additional context

To bypass this problem both users have to switch to the rocket.chat webbrowser version and the freshly created rooms have to be deleted by an admin. Then a chat between both parties can be stadted and afterwards both users can switch back to the desktop version.

Normally i say would this is a client issue BUT this bug is only reproducible with new or reimported LDAP users so the bug rather seems to be on the server side.

**Comment by maxdwit** [comment]
Out of curiosity: turn on exception Logging to a channel.
Do you get someting like: 
`WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: parties.rocketchat_message index: _id_ dup key:`

**Comment by deadmanIsARabbit** [comment]
It's funny but the problem seems to has solved itself. 
All affected users are now able to chat.
