### ISSUE TITLE
[NEW] REST API to create a new DM

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11501]
### Description:

Right now we're using the WebSocket method `createDirectMessage` to create new DMs, would be great to do that over DM.

**Comment by MartinSchoeler** [comment]
@rafaelks Can't the `dm.create` do this? https://rocket.chat/docs/developer-guides/rest-api/im/create/

**Comment by rafaelks** [comment]
Looks like yes, sorry about that @MartinSchoeler! Thanks for letting us know!
