### ISSUE TITLE
 I/System.out: onFailure: java.net.UnknownHostException: Unable to resolve host "demo.rocket.chat": No address associated with hostname [Ljava.lang.Object;@c5d0d2f

### ISSUE THREAD

**Issue by CHANDRAKANTHREDDY93** [RocketChat/Rocket.Chat#11512]
### Expected behavior:
      Trying to connect to Rocket Chat Server from android emulator. I've cloned project from this link 
https://github.com/RocketChat/RocketChat-Android-Demo.git. And trying to run the code in my android studio. But it is throwing me this issue.

**Comment by piotrkochan** [comment]
Please use forum https://forums.rocket.chat/
