### ISSUE TITLE
let participants invite others to a public channel

### ISSUE THREAD

**Issue by wrosenauer** [RocketChat/Rocket.Chat#11515]
Not sure if this is a feature or a bug.
When I'm in a public channel which is open to all users anyway and I'm not the owner I cannot invite users.

I think because everyone can join it should be allowed to invite people directly instead of pinging them manually to please join the channel.

**Comment by petcg** [comment]
Non-owner users were able to invite users to public channels before.

I'm not sure if it is a recent breaking change or just a bug.

For now, auto join also does not work for mentioned users.

**Comment by petcg** [comment]
@wrosenauer I've found out the reason.

`add-user-to-joined-room` for **user** was disabled this time although it was enabled by default before.

And, auto join issue seems not concerned with this because it still does not work after enabling `add-user-to-joined-room`.

**Comment by ggazzo** [comment]
closing this issue since we have found a solution here, (and we have invite links now)
