### ISSUE TITLE
Livechat - widget do not end chat at client side

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#11518]
### Description: 
Livechat - widget do not end chat at client side

### Expected behavior:
When I click `end chat` widget close connection at server and at client side - for example `saying goodbye`. When I open chat again it allows to start a chat again.

### Actual behavior:
When I click `end chat` widget end chat at server side, but at the client side - widget  - do not do a thing.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.63.3
- Operating System: Centos7
- Deployment Method:  docker
- Number of Running Instances: 1

**Comment by MarcosEllys** [comment]
Too

**Comment by renatobecker** [comment]
Hi @MarcosEllys and @monspid!

I just can't simulate the error you guys mentioned. Can you try our latest version (0.70)?
I'll be waiting your feedback.

Thanks.

**Comment by MarcosEllys** [comment]
Yes @renatobecker unfortunately today I tried in the latest version and when the live chat calls the action to exit, the section in the rockect really ends, but in the client nothing happens visually, and when the client inserts any text and sends, a new chat room is started with the previous room setup

**Comment by renatobecker** [comment]
@MarcosEllys, You can configure a message to display when the livechat is closed, please take a look at your `Adminstration -> Livechat` settings, you will find a setting named `Conversation Finished Message`.
Case you define a message for this setting, the visitor will receive the message when the livechat ends.

**Comment by johnlund** [comment]
I'm seeing this same issue. Using Ubuntu 18.04 Snap, Caddy, Wordpress LiveChat widget: modernmasters.org. Thanks!

**Comment by renatobecker** [comment]
Hi @johnlund.
Can you please check your browser and server log when you try to close the chat on widget side?
If you notice any log/error, can you please share it here?

Thanks.

**Comment by johnlund** [comment]
@renatobecker The only error I see anywhere is: Invalid 'X-Frame-Options' header encountered when loading 'https://chat.modernmasters.org/livechat': 'ALLOW-FROM https://modernmasters.org' is not a recognized directive. The header will be ignored. But that occurs every time I load the widget.

**Comment by renatobecker** [comment]
@johnlund, What happens on agent side when you try to close the chat from the widget side? Nothing? Or is the room closed and disappears there?
Can you please confirm it?

I will be waiting your feedback.
Thanks.

**Comment by johnlund** [comment]
@renatobecker Nothing happens on either side. The widget side shows the option the end chat, then when I click on it, the end chat popup closes and the chat appears as it did before I tried to end it. And nothing at all occurs on the agent side.

Thanks for your help!

**Comment by jsdckr** [comment]
I'm also seeing this issue. Ubuntu 18.04; manual installation. User selects "End Chat". Pop-up appears, "Are you sure you want to end this chat?" -> Yes -> No change visible at user end (automatic closing message doesn't send). At server end; the chat no longer shows as live. If the user messages further, the chat re-livens.
With grateful thanks, Jamie

**Comment by MartinSchoeler** [comment]
Should be fixed on the latest release, if not, feel free to create a new issue with updated details. Thanks!
