### ISSUE TITLE
Small images receive height of 200 pixels

### ISSUE THREAD

**Issue by mydoghasworms** [RocketChat/Rocket.Chat#11513]
### Description:

When pasting small images into chat that are less than 200 pixels high, they are resized in chat to have a height of 200 pixels, i.e. they are scaled up and much bigger than they should be.

### Steps to reproduce:

Take a screenshot of an image that is less than 200 pixels high, e.g. just 100 pixels high.
Paste the image into a chat.
Note that the image is resized in the chat to be 200 pixels high.

### Expected behavior:

Images that pasted should have a maximum height of 200 pixels but if they are smaller, they should not be scaled up.

### Actual behavior:

Example of an image that is 50 pixels high pasted into chat:

![screenshot_20180720_081116](https://user-images.githubusercontent.com/514461/42986057-6dc5bde0-8bf4-11e8-8f50-b0fd38045daa.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: Ubuntu Linux (x64)
- Deployment Method: snap
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Additional Information:

The height is set directly on the element style, i.e. not through a class.

### Temporary Workaround:

In the Layout > Custom CSS, have made the following addition:

```
img.gallery-item { height: auto }
```
Images that are larger than 200px high are managed by the `max-height` setting in the `gallery-item` class.

**Comment by vynmera** [comment]
We tried to fix it with #11228 but we're still running into issues. Perhaps you can help us?

**Comment by ledlamp** [comment]
The img tag has an attribute of `height="200"`; i think you could just exclude that as the css already sets `max-height: 200px`.

**Comment by rodrigok** [comment]
It's not a problem anymore
![image](https://user-images.githubusercontent.com/234261/83273172-941e2980-a1a2-11ea-9402-34d7844c2a28.png)

I'll close this for now, let us know if the issue persists in some way.
