### ISSUE TITLE
Channels listing

### ISSUE THREAD

**Issue by UN5T48L3** [RocketChat/Rocket.Chat#11523]
Hello there,
is there a way to show all channels in sidebar to everyone?
I am new on this project, I also would love to know if can we make show online room members next of the room names. 

![ekran resmi 2018-07-20 19 17 43](https://user-images.githubusercontent.com/39417235/43013443-99e6c038-8c51-11e8-8790-8798afec4e26.png)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
