### ISSUE TITLE
Issue with reproducing audio in Safari

### ISSUE THREAD

**Issue by iwkse** [RocketChat/Rocket.Chat#11535]
### Description:

This issue is reproducible on Safari browser, platform MacOS. Once an audio message is sent, rocket.chat reloads itself a few times till it stops with a 500 error.

### Steps to reproduce:

1. Upload or record a audio message
2. Open rocket.chat with Safari on MacOS

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0-develop
- Operating System: macos high sierra 10.13.4
- Deployment Method: git sources
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.3
- MongoDB Version: 3.4.14

**Comment by ggazzo** [comment]
hey @iwkse its was a bug of safari, I think it was fixed on 12 versions of safari... I will close, if the problem persists please let me know
