### ISSUE TITLE
Rocket chat crash JavaScript heap out of memory.

### ISSUE THREAD

**Issue by Anish-addweb** [RocketChat/Rocket.Chat#11547]
Rocket chat server version 0.66.3 crash regularly and in log file generate **FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory** .

**Comment by Anish-addweb** [comment]
![screenshot from 2018-07-24 15-40-21](https://user-images.githubusercontent.com/35479743/43132001-1c41e7fc-8f58-11e8-9a0b-9de4d56c3a29.png)

**Comment by tassoevan** [comment]
@Anish-addweb Can you dump some lines above that one? Maybe that stack trace can give us a better clue.

**Comment by Anish-addweb** [comment]
@tassoevan hello, rocket chat crashes on regular basis, crash peek time when heavy traffic arises on server.

**Comment by geekgonecrazy** [comment]
Add --max-old-space-size=4096 to your start of Rocket.Chat

Example: node --max-old-space-size=4096 main.js

Or scale horizontally to add more nodes to distribute your load.

Also newer versions use less memory which should help a lot
