### ISSUE TITLE
0.67 snap is not working

### ISSUE THREAD

**Issue by muhv7** [RocketChat/Rocket.Chat#11540]
### Description:

After updating to 0.67 snap the server is not coming up, status shows "failed" codes all over.

### Steps to reproduce:

Update snap to 0.67

### Expected behavior:

Everything to work?

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67
- Operating System: Ubuntu Zesty
- Deployment Method: Snap
- Number of Running Instances: 1

### Relevant logs:

:~# sudo journalctl -f -u snap.rocketchat-server.rocketchat-server
-- Logs begin at Tue 2018-07-10 20:41:22 EDT. --
Jul 21 02:00:00 ns544081 rocketchat-server.rocketchat-server[19569]: { Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/cENFiPZmo3KDSpKJx.zip'
Jul 21 02:00:00 ns544081 rocketchat-server.rocketchat-server[19569]:   errno: -2,
Jul 21 02:00:00 ns544081 rocketchat-server.rocketchat-server[19569]:   code: 'ENOENT',
Jul 21 02:00:00 ns544081 rocketchat-server.rocketchat-server[19569]:   syscall: 'stat',
Jul 21 02:00:00 ns544081 rocketchat-server.rocketchat-server[19569]:   path: '/tmp/zipFiles/cENFiPZmo3KDSpKJx.zip' }
Jul 21 02:15:00 ns544081 rocketchat-server.rocketchat-server[19569]: { Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/cENFiPZmo3KDSpKJx.zip'
Jul 21 02:15:00 ns544081 rocketchat-server.rocketchat-server[19569]:   errno: -2,
Jul 21 02:15:00 ns544081 rocketchat-server.rocketchat-server[19569]:   code: 'ENOENT',
Jul 21 02:15:00 ns544081 rocketchat-server.rocketchat-server[19569]:   syscall: 'stat',
Jul 21 02:15:00 ns544081 rocketchat-server.rocketchat-server[19569]:   path: '/tmp/zipFiles/cENFiPZmo3KDSpKJx.zip' }

Mongo and Caddy logs are clear.

**Comment by yekenuk** [comment]
Same for me.

I've had to revert to an older version :(

**Comment by vynmera** [comment]
Broken over here too :(

**Comment by tassoevan** [comment]
Is everyone seeing the same output in journald log?

**Comment by extraymond** [comment]
Same here, snap 0.67 in candidate channel is broken.

**Comment by ccfiel** [comment]
how did you update your version in snap? I tried this command

```
sudo snap refresh rocketchat-server
snap "rocketchat-server" has no updates available

```
but my version is still 0.66.3

**Comment by extraymond** [comment]
I was tracking the candidate and beta channel. The latest on it is 0.67.0 ver1312

**Comment by extraymond** [comment]
@ccfiel  You can try:

```
snap refresh rocketchat-server --channel candidate
```

**Comment by ccfiel** [comment]
@extraymond Thanks! Can I also track the pre release like 0.68.0-rc.0?

**Comment by extraymond** [comment]
You can check the available channel by:

```
snap info rocketchat-server
```

At the moment, the latest snap version would be 0.67.

**Comment by ccfiel** [comment]
@extraymond thanks!

**Comment by geekgonecrazy** [comment]
I'll take a look.  0.67.0 has not been released to stable channel.  I'd recommend switching to stable channel

**Comment by michaelkollmann** [comment]
Sorry for the rude language but... WHAT THE *** are you guys doing?

I'm suffering from the same issue on my end. Went back to 0.66.3 to fix this. 

This is the second time now that an update breaks the server. This is unaccaptable. Please for the love of god improve your testing / quality assurance and don't publish broken builds 👎

**Comment by geekgonecrazy** [comment]
@michaelkollmann I get your frustration.  But to have gotten this you had to have been on the candidate channel.  

There is a reason why we manually review every version now before we let it roll out to snaps.  This often leads to the update being delayed for snaps.  

This helps protect, but does not apply to the candidate channel.  Which unfortunately is a work around to get the latest (unreleased) version.

It appears we need to make an alteration and disable the candidate channel for untested builds.

**Comment by extraymond** [comment]
While I agree this could totally be fixed by implementing better build matrix, the snap version of this is still in --candidate channel which is not in stable yet. 

Expecting and ironing out bugs before stable is reasonable I believe.

@geekgonecrazy Is CI server not running anymore? Last activity from [travis](https://travis-ci.org/RocketChat/Rocket.Chat/branches) seems to be 9 months ago.

**Comment by geekgonecrazy** [comment]
@extraymond we now actually use circleci for our builds.  And snap builds are kicked off to launchpad where they are built.

After a handful of build errors (like the one in candidate channel now) we will be looking to move it into circle-ci as well.  But again this is exactly why builds hit candidate channel first.  It's acting as a safety net.  

We could of course move to publishing direct to edge channel.  But I have a feeling people would start tracking the edge channel.

**Comment by extraymond** [comment]
@geekgonecrazy Thanks for your reply!!

I'm aware of chances of meeting bugs before stable, and I'm happy to find them before everyone else :) I think that's how community works. 

I found the related info about circle-ci too. It would be nice to switch the CI banner in readme.me from travis to circle-ci to not decrease distraction.

I think the way multi channel release works is that by introducing edge/beta/alpha channels to your software, people can hop on and help out as soon as possible. Don't be afraid to release edge, if people found their contributing faster to be seen by others, they would feel more encouraged to contribute in the future. As of how to not let people falsely complain about immature code base, you can place an nice banner stating "edge is for explorers: lets build together". Positive atmosphere is what makes open source projects nice.

**Comment by geekgonecrazy** [comment]
We might be able to add something like that.  What makes this harder is the fact that a snap can be promoted between channels.  For instance release for stable channel always hit candidate first.  If determined stable we promote them.

Definitely something to consider looking into though.

Since i've gone ahead and remove from candidate channel i'll go ahead and close this.  We'll be releasing 0.68.x shortly.  

For more information about 0.67.0 please see: https://forums.rocket.chat/t/rocket-chat-0-67-0-extraordinary-release/1560
