### ISSUE TITLE
Alphabetical Channel Sorting Broken

### ISSUE THREAD

**Issue by cpitman** [RocketChat/Rocket.Chat#11545]
After upgrading to 0.67.0, channels cannot be sorted alphabetically in the web interface. No combination of grouping options make it work. Activity sorting continues to work.

**Comment by tanc** [comment]
Alpha sorting is also broken with private groups and private messages (version 0.67.0).

![franz](https://user-images.githubusercontent.com/76320/43066187-4ac378b0-8e64-11e8-95a6-709f837518dc.jpg)

![franz](https://user-images.githubusercontent.com/76320/43066228-648839f2-8e64-11e8-9b5d-69fe3a10daa6.jpg)

![franz](https://user-images.githubusercontent.com/76320/43066165-37b5dbc8-8e64-11e8-8c00-7554d604e283.jpg)

**Comment by geekgonecrazy** [comment]
@RocketChat/frontend guys any idea what's going on?  Why would cache reset clientside be needed to fix this?  I seem to recall having to do this at some point as well

**Comment by ggazzo** [comment]
if logout and login again (or clear the localdata) solves the problem, its probably a client-side cache, we should increase the version to expire here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/client/lib/cachedCollection.js#L113 my mistake if I didnt.

**Comment by geekgonecrazy** [comment]
So some data structures changes on last version caused the client side cache to need invalidated in some cases?

Cool at least an easy fix. So will be all sorted out for 0.68.0 ?

**Comment by tanc** [comment]
I can confirm that logging out and logging in again fixed it for me. So if the next release can trigger the same cache invalidation that would be great.

**Comment by tanc** [comment]
And another confirmation that logging out and in again helped a different user on our server.
