### ISSUE TITLE
Custom logo image in footer incorrectly sized

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#11541]
### Description:

The footer image is showing up as extremely reduced in size.

### Steps to reproduce:

1. Ensure that a custom logo image has been uploaded.
2. Ensure the image is showing in the content section for footer as in:
```<a href="/home"><img src="assets/logo"/></a>```
![image](https://user-images.githubusercontent.com/14616851/43039801-52242106-8cfa-11e8-8fac-7dfd7a4fae37.png)
No other CSS customizations have been made, and it has been working OK until the latest commit.

### Expected behavior:

Footer image should look like this:
![image](https://user-images.githubusercontent.com/14616851/43039796-44760e52-8cfa-11e8-954a-3ae78e567f69.png)

### Actual behavior:

But instead, it now looks like this:
![image](https://user-images.githubusercontent.com/14616851/43039797-4962d2b0-8cfa-11e8-883d-b88c3c54fa51.png)

All images uploaded conform to image upload specifications in the Assets section.

### Rocket.Chat (Docker: rocketchat:develop)

| Version                 | 0.68.0-develop                                            |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 129                                                       |
| Database Migration Date | Sat Jul 21 2018 15:13:31 GMT-0500 (Central Daylight Time) |
| Installed at            | Mon Jan 29 2018 16:02:11 GMT-0600 (Central Standard Time) |
| Uptime                  | 28 seconds                                                |
| Deployment ID           | JAELT9iyADPbKEGbG                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | 7f7690d7d740315534c19e405eeff4178457dd99       |
| ------- | ---------------------------------------------- |
| Date    | Sat Jul 21 02:23:38 2018 -0300                 |
| Branch  | develop                                        |
| Tag     | 0.67.0                                         |
| Author  | Pierre H. Lehnen                               |
| Subject | [NEW] Setting to disable 2FA globally (#11328) |

### Runtime Environment

| OS Type         | Linux                                     |
| --------------- | ----------------------------------------- |
| OS Platform     | linux                                     |
| OS Arch         | x64                                       |
| OS Release      | 4.15.0-24-generic                         |
| Node Version    | v8.11.3                                   |
| OS Uptime       | 17 days, 18 hours, 34 minutes, 31 seconds |
| OS Load Average | 1.37, 0.99, 0.50                          |
| OS Total Memory | 3.85 GB                                   |
| OS Free Memory  | 254.08 MB                                 |
| OS CPU Count    | 4                                         |

### Build Environment

| OS Platform  | linux                  |
| ------------ | ---------------------- |
| OS Arch      | x64                    |
| OS Release   | 4.4.0-130-generic      |
| Node Version | v8.11.3                |
| Date         | July 21, 2018 12:32 AM |

**Comment by kaiiiiiiiii** [comment]
#11508 for reference.

I think it’s a design decision which you can simply revert with some custom css :)

**Comment by bkraul** [comment]
Do you have a suggestion as to how I accomplish that with CSS? It seems there are some CSS variables at play I can't seem to be able to override (like --sidebar-footer-height).

**Comment by bkraul** [comment]
The other question. It seems to me that having to add custom CSS to bring back a behavior that was perfectly working before is more like a regression...?

**Comment by bkraul** [comment]
I believe I have found what I needed. I got it by overriding the variable ```--sidebar-footer-height``` and setting it back to 70px like so:

```
:root {
  --sidebar-footer-height: 70px;
}
```

Thanks for the help @kaiiiiiiiii

**Comment by Abraka** [comment]
How do I remove logo which sit above login dialog?
