### ISSUE TITLE
Using integrations to log the IP address of a user somehow

### ISSUE THREAD

**Issue by chatnl** [RocketChat/Rocket.Chat#11548]
**Is your feature request related to a problem? Please describe.**
I  do not have IP information of a logged in user.

**Describe the solution you'd like**
Of course I would like to have IP info in the profile of a user (visible for the admin).

**Describe alternatives you've considered**
If not possible I would like to have a few tips how I can use webhook scripts to capture the IP address of a user when they log in. I can post this information together with the username in a private group (incoming webhook). I would also be interested to post this to for example a database of my own (outgoing webhook). Can anybody please point me in the right direction. Even the example that is in the backend of Rocket chat gives a syntax error...

Any help is greatly appreciated.

Regards,

Stef

**Comment by NameTheJew** [comment]
> "I do not have IP information of a logged in user."

Your not suppose to.
We want rocketchat to protect users privacy.
If a user is abusing your community, ban them, and set registrations to require approval, or set rooms to private.
IP banning doesnt work because dynamic IPs, VPNs, Proxies etc

**Comment by TomsUsername** [comment]
i would like this as well, "set registrations to require approval" dose not really work for us with vary large community's where new accs are 200-1000 a day, and in a lot of chat services most bans are both email and ip

**Comment by reetp** [comment]
This seems to be a NFR rather than a bug.
Please follow this up in the forums where feature requests should be posted.
You can also see if anyone is prepared to give you some pointers.

**Comment by reetp** [comment]
@rocket-cat close
