### ISSUE TITLE
Default rooms should not need an owner

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#11542]
I almost believe that before the latest update default rooms did not need an owner.  With the latest release you can no longer make a default room without a owner. In the event that I am imagining things, and you always had to have an owner, a room without a owner should be possible.

I have to create about 200 default rooms on my server, I should not have to be in the rooms to have them active on the server. I know I can 'hide' them, but wouldn't that still make me appear to be in the room? This causes an issue because now users are going to believe that I am condoning behavior that I otherwise would not if I was actually present in the room. Currently the only alternative is to create a user just to be an owner of all those rooms. That is dangerous because what if someone gains control of that user, it may take a while for me to realize that the user has been compromised if I never actually use that user. The other issue is, now we just have a different name listed as "owner" that is not responding to support requests.

Am I missing something. I could have sworn that in previous releases default rooms did not need to have an owner. The default "general" room that is created upon install doesn't have an owner, why should any of the other rooms have to have an owner?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
