### ISSUE TITLE
[BUG] RC 0.67.0 Rest API users.list empty result

### ISSUE THREAD

**Issue by stephane-** [RocketChat/Rocket.Chat#11555]
Hello,

I have a script for get all users in my RC instance, but since last update (0.67.0), I think that's fail.
I was enable the debug log on the RC server and I get : 

```
[34mI20180724-11:36:44.878(2) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug GET: /api/v1/info 
[34mI20180724-11:36:44.886(2) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug Success { statusCode: 200,   body:     { info: { version: '0.67.0', build: [Object], commit: [Object] },      success: true } } 
[34mI20180724-11:36:44.909(2) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug GET: /api/v1/users.list 
[34mI20180724-11:36:44.914(2) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug Success { statusCode: 200,   body: { users: [], count: 0, offset: 0, total: 0, success: true } }
```
No errors, status code 200, and the body is empty for users. Tested account have admin, bot and user roles

Anyone have the same problem ?

Bests regards,
Stephane

**Comment by jfreax** [comment]
Hi,

I also have a script that uses the user.list API Endpoint. Doesn't work anymore since I upgraded to 0.67.0
I tried using curl and a python library called rocketchat_API. All I get is an empty body. No errors. Status code 200.

**Comment by zahaim** [comment]
Same here, just upgraded to 0.67.0
```
curl -H "X-Auth-Token: $TOKEN" -H "X-User-Id: $ID" https://$URL/api/v1/users.list | jq .
{
  "success": true,
  "total": 0,
  "offset": 0,
  "count": 0,
  "users": []
}

```

**Comment by stephane-** [comment]
NEw issue for 0.68.0 : #11599
