### ISSUE TITLE
[NEW] API methods to create new roles and set it to users within rooms/groups

### ISSUE THREAD

**Issue by aferreira44** [RocketChat/Rocket.Chat#11566]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to create a new role and set it to the users via API.
So, the idea is to create two API methods:
1. Create a new role passing as arguments (`name`, `scope`, `description`)
2. Set a role to an user passing as arguments (`room_id`, `user_id`, `role_id`).

**Describe alternatives you've considered**
I can do this on the page below, but I need to do these actions via API.

![image](https://user-images.githubusercontent.com/28768905/43226360-0d336fbc-9032-11e8-9138-f3cd7f8d0c1f.png)

**Additional context**
I search in the docs, but I can't found it how to do this. Please, let me know if there's an API method for this because otherwise, I'm thinking to contribute to the project for it.

**Comment by MarcosSpessatto** [comment]
Hello @aferreira44, we don't have any methods for this. We'd welcome a pull request to add this feature. :v:

**Comment by aferreira44** [comment]
@MarcosSpessatto Working on it, thanks!
