### ISSUE TITLE
im.list API change?

### ISSUE THREAD

**Issue by moonwolf-github** [RocketChat/Rocket.Chat#11564]
### Description:

After upgrade to 0.67.0 it looks like `im.list` API endpoint has changed. I'm using python rocketchat-API library and before upgrade this was working as expected:
`cl.im_list(query='{{"name": "{}"}}'.format(recipent)).json()` - it gave me one hit, an IM of user performing query (bot) with user passed in `recipent`. As of 0.67.0 this returns list of all bot's IMs

### Steps to reproduce:

Get IM list of user using `im.list` API endpoint filtered by other user name.

### Expected behavior:

Returns one hit.

### Actual behavior:

It returns list of all (i think) IMs,

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67.0
- Operating System: Linux CentOS7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: off
- NodeJS Version: 8.9.3 - x64
- MongoDB Version: 3.4.9

**Comment by MarcosSpessatto** [comment]
Hey @moonwolf-github, we remove the `query` parameter support in [v0.67](https://github.com/RocketChat/Rocket.Chat/commit/9e0a8f50d70edf1e5d46d3eaa2aa2cd636a002a6#diff-e34248bb3a3165d2d83df09e40c5ee98R283). I made a [PR](https://github.com/RocketChat/docs/pull/877) to update the docs according those changes.

**Comment by moonwolf-github** [comment]
In that case this issue should be closed, i presume.
