### ISSUE TITLE
@mention breaks when it appears in the beginning of non-first line of a message

### ISSUE THREAD

**Issue by wenzhengjiang** [RocketChat/Rocket.Chat#11569]
### Description:
@metion doesn't work when it appears in the beginning of a non-first line of a message.

![1](https://user-images.githubusercontent.com/3186972/43247081-fb390b3a-90f6-11e8-8531-fb723cca02a7.png)

And I insert a space in front of @mentions, they will work just fine.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0
- Operating System: `ubuntu 16.04`
- NodeJS Version: `8.11.3`
- MongoDB Version: `3.4`

**Comment by cmouse** [comment]
:+1: I have this issue too.
