### ISSUE TITLE
No message history for non admins 

### ISSUE THREAD

**Issue by TomsUsername** [RocketChat/Rocket.Chat#11560]
### Description:

No channel history for any channel for any non admin user , may or may not happen (happens more often then not)

### Steps to reproduce:

1. make a acc or login to https://chat.globalplusplus.com
2. refresh page (may or may not load history)

### Expected behavior:
all pass messages to load 

### Actual behavior:
only new messages from when channel is open show up, they also fail to load on refresh 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67.0
- Operating System:  Ubuntu 16.04.4 
- Deployment Method: tar
- Number of Running Instances: 24
- DB Replicaset Oplog: yes
- NodeJS Version: 8.9.3
- MongoDB Version: 3.6.6

### Additional context
started with 0.66.3
sometimes using search will make all history show up
all clients, mobile(both rn and leg), desktop and web
dose not happen to admin users 

### Relevant logs:
found no relevant logs from server/browser/mongo, just doesn't load message history

**Comment by JMccormick264** [comment]
I joined on a new account, not my main one. Here are a few screenshots.
https://puu.sh/B2nvD/e33c05f945.png
https://puu.sh/B2nvT/9640080ac8.png
https://puu.sh/B2nwv/5b92cd967c.png

On the left side where channels are I have unread mentions in all of them
https://puu.sh/B2nxQ/3cf8cc320e.png

But when I go into the channels, such as the three screenshotted above, they are all blank 

When I switch back to my main account, the channels have the content they are supposed to and are not blank. My main account has the Server Admin role.

**Comment by just-Addict** [comment]
I'm a non-admin and confronted with this issue, for me the history does not show in any non-private channel. I found that on PC, if I jump to a mention, the history surrounding that mention shows, and I can sometimes also scroll to the last post if the mention was recent enough. However, as soon as I switch to another channel, I lose the history again when returning to the channel I just left.

The only thing that works for me in making the history stay visible is to use Search and search for a fairly recent post using generic search terms. Only then does history stay visible after switching to another channel and returning back to the channel switched from.


I've tried this in just about every browser on Desktop I could lay my hands on and the RC Desktop App. 
All show the same symptom and all respond equally to the Search method in making the history survive channel switching. 


However, once I am forced to refresh the session or relaunch the browsertab, I am again confronted with the "Start of Conversation" in every non-private channel

**Comment by ElliotRobot20** [comment]
Was hoping someone posted this. Can confirm as well on local implementation. Please fix.

**Comment by TomsUsername** [comment]
i have tried to debug this a bit more on a different server with a fresh install , this does not seem to happen on a my smaller test db or a fresh db, but does when i restore our large prd db

**Comment by goobersmooch** [comment]
I can confirm that this is also happening on our server. Please fix. :)

**Comment by TomsUsername** [comment]
downgraded back to 66,3 fixed the issue

**Comment by TomsUsername** [comment]
i was forced to update back to 0.67.0 due to the excessive cpu usage of 66.3, No channel history for non admins is still a issue

**Comment by zedar187** [comment]
Can confirm this, too. Debian Stretch, "NodeJS Version: 8.11.3 - x64", mongodb 3.2.11-2+deb9u1, upgraded from 0.65.2 to 0.67.0.

Normal users can't see the history of non-private channels. The admin can see the history. There's one channel that doens't load as an admin as well. Unfortunately there's nothing added to the log.

**Comment by TomsUsername** [comment]
I wish there was something in the log so that I could at least debug this, this has essentially rendered our production system unuseable, I guess I know never to update to the latest without letting it be tested for multiple months

**Comment by TomsUsername** [comment]
still a issue on 0.68.0-rc.0

**Comment by TomsUsername** [comment]
After enlisting the help up several other people, we were all able to reproduce this using various databases and different servers with still no clue of actually what is causing it, nor how to fix it, and with the overwhelming support we have received here, and judging by the ridiculous amount of unresponded to open issues( yes I know this is open-source and everybody volunteers, but I would have expected at least some kind of response, before you saying hey if you needed support you could have just used the hosted version. that has a absolute Max of 500 connected users we have close to 60, 000 users with anywhere between 4000 to 5000 online at any given time with Bursts up to 20k), we have decided to move to one of your competitors -signed one of your largest communities

**Comment by engelgabriel** [comment]
Fix via https://github.com/RocketChat/Rocket.Chat/pull/11639
