### ISSUE TITLE
[NEW] API to support message actions

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11577]
### Description:

(this needs more definition, per my conversation with @rodrigok)

We need to create few APIs to deal with actions in messages:

- List of actions in the message (think about some way);
- Action from the message;

I think we can have this information on the actions: 

- Order (?)
- Title color (?);
- Border color;
- Background color;
- Title (i18n?);
- Action to be called;

Preview of how it would look on the mobile apps:

![paper rocket chat 1](https://user-images.githubusercontent.com/551004/43267335-108cb08c-90c4-11e8-8ea2-f36a8b9f28ba.png)

**Comment by rafaelks** [comment]
@cardoso AFAIK, yes.

**Comment by rodrigok** [comment]
I'd say to not have the colors for title, border and background, just a button type like `normal`, `danger`, `alert`, `confirm`, etc... and the colors would be defined by the client to match the theme.

The current implementation is called `actionLinks`, here is an example of usage https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-videobridge/server/methods/jitsiSetTimeout.js#L17

The DDP api called is `actionLinkHandler` passing the action and the message id:
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-action-links/server/actionLinkHandler.js#L4

It's easy to port to REST

**Comment by rafaelks** [comment]
@rodrigok That works for me as well, do we have these types already?

**Comment by rodrigok** [comment]
@rafaelks We don't have types, the current implementation contains `icon`, `label`, `method_id` and `params`

**Comment by graywolf336** [comment]
Guys, this is duplication of other work being done and should also tie into the Rocket.Chat Apps. Please see discussion on the forums: https://forums.rocket.chat/t/supporting-rich-chatbot-messages-menus/528

**Comment by rafaelks** [comment]
Yes, issue can be closed since we're already working on supporting the `actions` property.

**Comment by rafaelks** [comment]
Thanks for the heads up @graywolf336!
