### ISSUE TITLE
github in RocketChat

### ISSUE THREAD

**Issue by whoiswho2018** [RocketChat/Rocket.Chat#11579]
I added GitHub as a OAuth Application. How do I test it? To be able to push and pull from rocketchat.
![image](https://user-images.githubusercontent.com/41310644/43276880-42954c3c-90d4-11e8-9af0-9746c5724f54.png)

I also see you can add 2 integrations (Do we need them to make github work?) If yes I see you can post the to a channel. Is there anyway to do different repos? How can I have a different channel for each repo in github so when something happens it will post an alarm? I see nothing online about any of this. 
https://rocket.chat/docs/administrator-guides/integrations/github/#send-commands-to-github

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
