### ISSUE TITLE
Feature: Content snippet for new channel form

### ISSUE THREAD

**Issue by toupeira** [RocketChat/Rocket.Chat#11575]
We'd like to display a block of text on `/create-channel` with information about our channel naming conventions, and how the permission levels (public/private/broadcast) should be used.

This could work similarly to the already available content blocks in Administration &rarr; Layout &rarr; Content.

Markdown formatting would be great, but raw HTML is perfectly fine too.

I don't have any experience with Meteor, but if somebody can give me some pointers to the relevant files I'd be happy to submit a PR :)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

you can use the Room Announcement and/or description 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
