### ISSUE TITLE
caddyfile not found but everything seems to work; will this bring trouble soon?

### ISSUE THREAD

**Issue by jasondaigo** [RocketChat/Rocket.Chat#11583]
### Description:

my systemd service on ubuntu for snap.rocketchat-server.rocketchat-caddy.service was not running since i start using rocketchat

rocketchat-mongo and server service run without an error

### Steps to reproduce:

1.  installed ubuntu and rockchat with snap install 
2. check systemd log

### Expected behavior:

 caddyservice runs without error

### Actual behavior:

 caddy service fails with 
Jul 26 21:48:07 ubuntu_server rocketchat-server.rocketchat-caddy[1819]: 2018/07/26 21:48:07 loading Caddyfile via flag: open /var/snap/rocketchat-server/1311/Caddyfile: no such file or directory   
ofc the fail is indeed missing; but i didnt notice any trouble; will this brings problems down the road or when updating? should i create the file by myself?

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 18.04
- Deployment Method: snap 
- Number of Running Instances: 1

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
