### ISSUE TITLE
Issue uploading files (GridFS Cross-Origin Request Blocked)

### ISSUE THREAD

**Issue by Kanarota** [RocketChat/Rocket.Chat#11589]
### Description:
When trying to upload a file or paste the clipboard with a file, it stays stuck at 0% and doesn't proceed.

### Steps to reproduce:

1. Click the "+" Icon in the text box, select "Add files from Computer".
2. Select a file and click open.
3. In the "Upload file?" page in RocketChat, click on Send.

### Expected behavior:
The file should be sent normally, then visible in the chatroom or private group.

### Actual behavior:
Stays stuck uploading at 0 percent at the top of the page, with a cancel button available.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System: Ubuntu Server 16.04
- Deployment Method: Snap
- Number of Running Instances: 1

### Additional context
This issue occurs with any files uploaded that have an allowed extension. Changing browsers (Firefox, Chrome) or devices doesn't fix the issue.

I have also removed the snap, reinstalled it, and it still doesn't work.

### Relevant logs:
BROWSER(Firefox):

**This entry occurs when the upload is at 0% after clicking the send button:**

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost/ufs/GridFS:Uploads/NdfsP93dq5auQy7Gq?token=298848daC8&progress=0.036795817350449615. (Reason: CORS request did not succeed).

**Comment by Kanarota** [comment]
After changing the Site URL, Uploading now works.

**Comment by chengjingfeng** [comment]
@Kanarota how to change the Site URL? from http to https? or some way else?

**Comment by Kanarota** [comment]
@chengjingfeng Go to Administration > General >Site URL. Make sure it is the link you are using to connect to rocket chat (Example, if you connect from the IP 192.168.0.1, then make the url http://192.168.0.1)

Hope this helps

**Comment by chengjingfeng** [comment]
it works, thanks @Kanarota
