### ISSUE TITLE
bus error during installation

### ISSUE THREAD

**Issue by chengjingfeng** [RocketChat/Rocket.Chat#11595]
Is there someone meet this error during installation: 
Updating process.env.mail_url  
Starting Email Intercepter. 
Bus error (core dumped)

mongos version 4.4.0.62 
node.js v8.9.3
rocket chat v0.68.9

**Comment by chengjingfeng** [comment]
any comment will be helpful for me :)

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
