### ISSUE TITLE
HipChat Import Failure

### ISSUE THREAD

**Issue by jeffwaddell** [RocketChat/Rocket.Chat#11592]
I have a centos 7 box when trying to import HipChat file under the HipChat Enterprise screen - export is from HipChat Server version 2.29

CentOS Linux release 7.5.1804 (Core)
Rocket.Chat version 0.67.0
Node version v8.9.3

Chrome crashes when I try to import using it - I am only able to reproduce the error below in FF or IE - nginx running as a proxy to the app with SSL. Import file is about 500meg

Invalid Import file type is the error received 

I am not sure if this is the same as this - https://github.com/RocketChat/Rocket.Chat/issues/11355#issuecomment-405495839
but thought I would submit for review

Error that shows in the log
[34mI20180727-22:46:40.850(-4) Exception while invoking method 'prepareImport' Error: Match error: Expected string, got null     at check (/opt/Rocket.Chat/programs/server/packages/check.js:68:17)     at MethodInvocation.prepareImport (/opt/Rocket.Chat/programs/server/packages/rocketchat_importer.js:796:5)     at MethodInvocation.methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2494:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85  
[34mI20180727-22:46:40.851(-4) Sanitized and reported to the client as: Match failed [400] 
[34mI20180727-22:46:40.851(-4) undefined undefined 

Hopefully this helps towards a resolution.

**Comment by piotrkochan** [comment]
known issue https://github.com/RocketChat/Rocket.Chat/issues/11355

**Comment by Hudell** [comment]
Fixed on version 0.74.3
