### ISSUE TITLE
0.68.0 SNAP crashing upon start (fiber issue)

### ISSUE THREAD

**Issue by tsukiRep** [RocketChat/Rocket.Chat#11594]
### Description:
Snaps for 0.68.0 (perhaps 0.67.0 too, never managed to get it up and running) break immediately due to not being able to load the module `fibers`.

### Steps to reproduce:
1. `snap start rocketchat-server`
2. `journalctl -f -u snap.rocketchat-server.rocketchat-server`
3. Watch as your server isn't working

### Expected behavior:
It starts

### Actual behavior:
It does not

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.0
- Operating System: Ubuntu Server 16.04.3 LTS
- Deployment Method: snap (this poses an issue, they're readonly)
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 
- MongoDB Version: 

### Additional context
I cannot install `fibers` myself because snaps are readonly. All I can do is revert and hope you guys don't start pushing these to the stable channel.

### Relevant logs:
```
Jul 28 09:54:53 chat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Jul 28 09:54:53 chat rocketchat-server.rocketchat-server[16511]: Checking if oplog has been enabled, and enabling if not
Jul 28 09:54:53 chat rocketchat-server.rocketchat-server[16511]: MongoDB shell version: 3.2.7
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]: connecting to: test
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]: module.js:549
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     throw err;
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     ^
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]: Error: Cannot find module 'fibers'
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Function.Module._resolveFilename (module.js:547:15)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Function.Module._load (module.js:474:25)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Module.require (module.js:596:17)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at require (internal/module.js:11:18)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Object.<anonymous> (/snap/rocketchat-server/1313/programs/server/boot.js:1:75)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Module._compile (module.js:652:30)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Object.Module._extensions..js (module.js:663:10)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Module.load (module.js:565:32)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at tryModuleLoad (module.js:505:12)
Jul 28 09:54:54 chat rocketchat-server.rocketchat-server[16511]:     at Function.Module._load (module.js:497:3)
Jul 28 09:54:54 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE
Jul 28 09:54:54 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Unit entered failed state.
Jul 28 09:54:54 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
Jul 28 09:54:54 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Service hold-off time over, scheduling restart.
Jul 28 09:54:54 chat systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-server.
```

**Comment by vynmera** [comment]
Sorry to hear about your frustration. You are tracking `candidate`, no? You might want to change back to `stable` like so: `snap refresh rocketchat-server --channel=stable`

The `candidate` channel is untested and shouldn't be trusted to work :) you will find that `stable` still doesn't have 0.67.0 either, as that one too is untested (clearly, because it seems that one doesn't work for you either)

**Comment by tsukiRep** [comment]
@vynmera From the `snap` [documentation](https://docs.snapcraft.io/reference/channels#risk-level):

>- **stable**: what most users will consume and as the name suggests, should be your most polished, stable and tested versions.
>- **candidate**: used to vet uploads that should require no further code changes before moving to stable.
>- **beta**: used to provide preview releases of tested changes.
>- **edge**: for your most recent changes, probably untested and with no guarantees attached.
>
>Make sure you follow these guidelines, as they have an impact on the discoverability of snaps in search results.

Your argument makes sense if I were tracking `edge`. But I'm tracking `candidate`, which should "should require no further code changes". So y'know, it should _work_.

**Comment by geekgonecrazy** [comment]
Releases were auto-published to candidate. To give us a chance to test them.  Things like this happen.  So we wanted to shield production users by only publishing to candidate and then after updating to stable after testing the auto-build. 

But seems too many are relying on candidate channel for production installs.

So I've removed this build from candidate and the future builds will only automatically be published to edge.

**Comment by geekgonecrazy** [comment]
I'll leave this open for now while we track down the build error

**Comment by torgeirl** [comment]
@geekgonecrazy: just to be clear; moving forward `latest/candidate` will be the same as `latest/stable`, while `latest/edge` contains the current latest release (for testing purposes only)?

**Comment by geekgonecrazy** [comment]
Correct.  We will be investigating making better use of release channels in the nearer future.

So you could actually follow 0.68/stable or 0.69/edge etc.  But for the moment we are sticking with stable being latest tested.  And edge being the builds spit out by the ci.  Only promoted to stable after we test that all works fine

**Comment by ccfiel** [comment]
any update on this? :)

**Comment by ccfiel** [comment]
I tried to used the edge channel but still not working and the last update was 10 days ago :( maybe there is no love for snap :(

**Comment by geekgonecrazy** [comment]
0.68.3 was released to stable channel.

**Comment by geekgonecrazy** [comment]
It's already out on stable channel. I'd comment on the issues with your urgency.
