### ISSUE TITLE
People not displayed in Members List?

### ISSUE THREAD

**Issue by diomed** [RocketChat/Rocket.Chat#116]
I see lots of people coming to #general in test page, and welcome message greets them,
but they are not displayed in sidebar, in Member List.
some even write messages in chat, but they still aren't displayed in Member List.
is this some sort of bug?

Also, upon registration I went to upload avatar from PC, and my browser crashed.
I did it from 2nd try, though.

**Comment by rodrigok** [comment]
@diomed, sorry for that. This is a know problem, we are working on it.

Its because we removed the subscription for all users in room because we didn't expect to have 3000 users in a single room :D

Probably this issue will be resolved today or tomorrow.

**Comment by rodrigok** [comment]
Hi @diomed, we solved this problem yesterday. Now you can see all users online in channel and soon we will add an option to list all offline users too.

**Comment by diomed** [comment]
cool :thumbsup:
