### ISSUE TITLE
pruning based on user does not work as intented

### ISSUE THREAD

**Issue by svennd** [RocketChat/Rocket.Chat#11607]
### Description:
pruning based on @svennd "at user" is removing all messages contrary to what the description says: 
"Only prune content from these users (leave empty to prune everyone's content)"

### Steps to reproduce:

1. (web interface) -> public channel 3 dots -> prune messages
2. @user_to_delete
3. (optional set time)
4. Prune

![screen](https://user-images.githubusercontent.com/7106739/43443860-6b8f021e-94a2-11e8-81c9-1764f8b4d835.PNG)

### Expected behavior:
Remove messages for @user_to_delete

### Actual behavior:
remove all messages prior to set time (if this option)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.68.0
- Operating System: 4.15.17-2-pve
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  disabled
- NodeJS Version: v8.9.3

**Comment by vynmera** [comment]
Can you take a screenshot? The red box should also say "(if they are from user_to_delete)".

I'll test locally in a moment

**Comment by vynmera** [comment]
Can confirm it's broken - field is not picked up.

**Comment by vynmera** [comment]
Looks to be introduced by https://github.com/RocketChat/Rocket.Chat/pull/11236/commits/811b8328c83551bb7f00fce5647c30c2a5e9c103 in a change from using `Session` to `ReactiveVar` - not all set operations were updated

**Comment by vynmera** [comment]
#11646 will fix it :tada:
