### ISSUE TITLE
update issue - snap

### ISSUE THREAD

**Issue by efih** [RocketChat/Rocket.Chat#11608]
Hi 

why the snap not showing any updates ?

root@rocket-chat-dev:~# snap refresh rocketchat-server --stable
rocketchat-server 0.66.3 from 'rocketchat' refreshed
root@rocket-chat-dev:~# snap refresh rocketchat-server --candidate
rocketchat-server (candidate) 0.66.3 from 'rocketchat' refreshed
root@rocket-chat-dev:~# snap refresh rocketchat-server --beta
rocketchat-server (beta) 0.66.3 from 'rocketchat' refreshed
root@rocket-chat-dev:~# snap refresh rocketchat-server --channel=stable
rocketchat-server 0.66.3 from 'rocketchat' refreshed

current version 0.66.3
os : ubuntu

**Comment by ccfiel** [comment]
any idea when will this be release?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
