### ISSUE TITLE
0.68.0 - Changes in Settings are not permanent

### ISSUE THREAD

**Issue by MFietze** [RocketChat/Rocket.Chat#11604]
### Description:

Since 0.67.0 some settings radio buttons are not working. The changes are not permanent, even after saving the change. It happens not with all settings, but for example with Settings ->Messages -> Allow Edit of Messages. Another example is Settings -> Video Conference -> Activate.

![2018-07-30_13h58_48](https://user-images.githubusercontent.com/6169702/43396517-145f933c-9402-11e8-9730-885527681f5c.gif)

### Steps to reproduce:

1. Go to Administration 
2. Click on Video Conference and activate or deactivate Jitsi
3. Close the settings
4. Open the Video Conference settings again

### Expected behavior:

The change should be permanent.

### Actual behavior:

The change is not saved.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.0
- Operating System: CentOS 7
- Deployment Method: Docker, but happens with manual installation as well
- Number of Running Instances: 1
- MongoDB Version: 3.6.6

**Comment by MFietze** [comment]
Occurs for me even in the Windows client.

**Comment by MFietze** [comment]
Update: It seems that it is a caching related issue. When I logout (or remove the server in the client) and login again, the change is visible.

**Comment by johnyb0y** [comment]
+1 Also seeing this with 0.68.0 and Google Chrome 68.

**Comment by verwilst** [comment]
0.68.4, Firefox. Settings are applied ( and correctly set ) only after a logout.

**Comment by kaoecoito** [comment]
In my tests for each click on an option I had to click once on save.

**Comment by reetp** [comment]
Can you test on the latest 0.69.2 and/or 0.70.0rc
Things are fast moving and may be fixed in the most recent version.
See the changes in releases. https://github.com/RocketChat/Rocket.Chat/releases

**Comment by Shaverdoff** [comment]
Version 0.70.0
in latest Firefox 62.0.2 it seems the same bug. But temprorary resolve is a refresh page after make changes on FF and whole changes will appear as expected... you still stay on position before refresh page.
on Desktop native client bug is absent

**Comment by TheMythPT** [comment]
same issue in 0.72.3

**Comment by Shaverdoff** [comment]
> 
> 
> same issue in 0.72.3

that issues i think becouse rocketchat client is Electron. if on web-client the same bug - desktop client have the same

**Comment by gomaaz** [comment]
issue still persists in 0.74.0 Release candidate

**Comment by Shaverdoff** [comment]
Its Strange, because then i make changes it permanent after 072 or 073 release

--
Gerasim Shaverdov | Deputy CTO | Altarix
Mobile: +7 937 070 66 84<tel:+7%20937%20070%2066%2084> | Skype/email: gerasim@altarix.ru<mailto:gerasim@altarix.ru>
Lenina av.25, Samara, Russia, 443068

5 февр. 2019 г., в 23:35, Daniel Lortie <notifications@github.com<mailto:notifications@github.com>> написал(а):


issue still persists in 0.74.0 Release candidate

**Comment by kevin-og** [comment]
@ggazzo I'd add, I'm testing 1.1.1 and am seeing this same issue.  Settings aren't sticking.  If I log out of my account, and back in, the changes reveal themselves.
