### ISSUE TITLE
Improve "Show counter" option in Notifications

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11609]
### Description:

![screen shot 2018-07-30 at 11 31 02](https://user-images.githubusercontent.com/551004/43404524-1b860f4c-93ee-11e8-8bcb-825665dea589.png)

The meaning of this option (Show counter) is not what's written on it.

**Comment by aspiers** [comment]
Unfortunately this is not working as per #12689.

**Comment by engelgabriel** [comment]
Closed in favor of https://github.com/RocketChat/Rocket.Chat/issues/14792
