### ISSUE TITLE
WRONG CODE PASTE

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat#11610]
When i put  

sed -i 's/\(^Server=\).*/\Server=zabbix.asterisk.biz.ua/' /etc/zabbix_agentd.conf

i GOT

http://i.imgur.com/8xmYeB2.png

**Comment by vynmera** [comment]
Perhaps turn off KaTeX or change its mode?

**Comment by gudge25** [comment]
OK turn off KaTeX  -- there is no Wrong  PASTE --- BUT IS IT really a good  solution  to disable ?

**Comment by tassoevan** [comment]
It's a known issue (I had the same problem last week describing a regex too) and we're discussing how to solve it.

**Comment by Da-Juan** [comment]
I've ran into the same problem yesterday.

Any news on a fix?
All formatting except syntax highlighting should be automatically turned off inside a code block, isn't it?

**Comment by tassoevan** [comment]
@Da-Juan #11698 and #11746 can solve this issue. I guess their merging was postponed.

**Comment by ggazzo** [comment]
I can't reproduce anymore, @gudge25 could you test again? thanks
