### ISSUE TITLE
[BUG] Livechat: Forward by Department not working.

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#11618]
### Description:

When Agent tries to forward live chat to another department, it throws an error: 
`Exception while invoking method 'livechat:transfer' TypeError: RocketChat.models.Rooms.removeUsernameById is not a function`

### Steps to reproduce:

1. Click on `Visitor Info` of live chat room
2. Click on `Forward`
3. Select a department from `Forward to department` dropdown.
4. Click on `Forward`

You'll see error on server console.

### Expected behavior:

Livechat should be transferred to respective department.

### Actual behavior:

Server throws error.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0-develop (commit hash 2968549677)
- Operating System: darwin
- Deployment Method: Manual
- Number of Running Instances: 1
- NodeJS Version: 8.11.3 - x64

### Relevant logs:

`Exception while invoking method 'livechat:transfer' TypeError: RocketChat.models.Rooms.removeUsernameById is not a function     at Object.returnRoomAsInquiry (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_livechat.js:5261:29)     at Object.transfer (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_livechat.js:5171:34)     at MethodInvocation.livechat:transfer (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_livechat.js:2412:32)     at MethodInvocation.methodsMap.(anonymous function) (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_lib.js:2506:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:875:23)     at /Users/pk/Rocket.Chat/.meteor/local/build/programs/server/packages/ddp-server.js:754:85`

**Comment by MartinSchoeler** [comment]
@renatobecker
