### ISSUE TITLE
Non-Admins can't read channel history

### ISSUE THREAD

**Issue by zedar187** [RocketChat/Rocket.Chat#11620]
### Description:

Users are unable to see the channel history of public channels. Everything works fine with private-channels, or, if you are an admin user.

### Steps to reproduce:

1. Click on a public channel as non-admin.
2. Blank content page appears

### Expected behavior:

Channel history should appear.

### Actual behavior:

There is only a blank content page, as if the channel was newly created. The Title and channel description is present, as well as a title for "Beginn des Gesprächs" (should be "Start of Conversation" in EN). Neither the server log, nor the browser js-console state an error/hint. Same for Rocket.Chat Electron Client for Windows.

### Server Setup Information:

- Version of Rocket.Chat Server: tried 0.67.0 + 0.68.0 + 0.68.1
- Operating System: Debian Stretch/stable
- Deployment Method: tar, by Docs -> manual install for ubuntu
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.2.11-2+deb9u1

### Additional context

I updated from 0.65.x, skipped 0.66.x and got directly to 0.67.0. The issue appeared with at least 0.67.0. 0.68.0 and 0.68.1 are affected as well. Reference to #11560; closed because of the issuer - but issue still exists. There you'll find screenshots too.

### Relevant logs:

Nothing is logged.

**Comment by TomsUsername** [comment]
Good luck Dude, me and two other people spend about 30 hours trying to figure this out, we're not familiar enough with the rocket. Chat code base to make any progres, by any chance is your database rather large? 7gb+ ?

**Comment by TomsUsername** [comment]
We've already moved to mattermost, but now I am just curious

**Comment by zedar187** [comment]
The databse is pretty small. 5 active users, overall message count 60317 whereas 53546 messages are by directchats, 2120 in public channels and 4526 in private channels.

File uploads go into the filesystem and not into the database.

If the info helps: we've started using rocketchat at version 0.56.0 in may/june 2017 and having migrating it since then.

**Comment by TomsUsername** [comment]
Before moving,as a work around, we found if the non admin user simply use the search box for arbitrary terms message history would randomly appear

**Comment by Hudell** [comment]
It seems to be a problem with the `preview-c-room` permission. Can you confirm if your user role has that permission enabled?

**Comment by goobersmooch** [comment]
Yeah that's one of the first things i checked.
