### ISSUE TITLE
docker image seems incorrect (rc_version and node_version)

### ISSUE THREAD

**Issue by rsimai** [RocketChat/Rocket.Chat#11623]
I'm not sure where else to report this, the more current docker image(s) seem(s) inconsistent. I just pulled rocket.chat from dockerhub and when I inspect the image, it contains

"NODE_VERSION=8.9.4"
"RC_VERSION=0.67.0"

Expected was something like rc 0.68.1 and node 8.11.3.

I btw. also see a mismatch in our current production

Version	0.66.3
Node Version	v8.9.4

while the Build Environment lists

Node Version	v8.11.3

**Comment by rsimai** [comment]
Update, I pulled again and finally got 0.68.1 but still there is "NODE_VERSION=8.9.4" for the image. This is not consistent.

**Comment by himpich** [comment]
On my end:
Software (Administration / Info):
RC Version: 0.68.3
Node Version v8.11.3

docker inspect image:
                "NODE_VERSION=8.11.3",

We explicitly pull the specific versions of the RC images, current Image (rocketchat/rocket.chat:0.68.3) has:
        "Id": "sha256:e98d34f3e7ab12a22b170a14dcd95e892235da25ee192b5c3f4e17ec20020837",
--

**Comment by sampaiodiego** [comment]
I've updated the node version for the official docker image. 
I've opened this pull request long time ago but forgot to merge https://github.com/RocketChat/Docker.Official.Image/pull/43

I can see the confusion of having two different docker images. but there is an [official one](https://docs.docker.com/docker-hub/official_repos/) maintained on the following repo https://github.com/RocketChat/Docker.Official.Image and another one under our namespace that is automatically generated by our own CI.

what do you guys think we could do to make this more clear?

**Comment by rsimai** [comment]
For me it was confusing to see this node version mismatch in the official release and actually I'd expect the automated builds to be more error-prone than the official one. You typically do more (automated) tests or (real) QA on the latter before you publish, and the official build is just a usable result from the automated ones. But it seems this is not how it works, the builds are done separately which made the automated build "good" and the official "bad".

Apart from that the repo setup and descriptions are probably good enough, now that you have corrected the official image. Many thanks for that!

I'd be good to close this issue, if no one objects.

**Comment by rsimai** [comment]
I guess I just close it. Thanks again.
