### ISSUE TITLE
Is there a coding standards doc for Rocket.Chat?

### ISSUE THREAD

**Issue by shrop** [RocketChat/Rocket.Chat#1163]
Just looking for Rocket.Chat coding standards doc so my team can contribute. Thanks!
##

**Comment by kakawait** [comment]
Should create a more common document like `CONTRIBUTE.md` that cover coding style, processes, tricks and other useful things for developers.

:+1:

**Comment by gmsecrieru** [comment]
Thanks for your interest! I think that haven't been started yet. Would you be willing to kick-off a document? There are lots of things we could standardise, maybe we could just start by tracking them.

**Comment by kakawait** [comment]
@gmsecrieru You/We can copy CONTRIBE.md from other famous project and adapt as base

**Comment by geekgonecrazy** [comment]
Any good examples of very well done contribute.md? 

I think this is a very needed dicussion.  We do need to standardize the coding style.

We shouldn't let this prevent us, but this could be effected by #1015

**Comment by kakawait** [comment]
@geekgonecrazy yeah when I spoke about CONTRIBUTE.md is for structure/format only! You should write your own standard.

ATM I don't have sample CONTRIBUTE.md but I will check on top project (https://github.com/trending)!

**Comment by kakawait** [comment]
My 2 cents datamining I found Angular CONTRIBUTING.md file pretty complete (but maybe too many) https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

**Comment by shrop** [comment]
Some helpful links:

**Comment by shrop** [comment]
Here are a few examples:
https://github.com/blog/1184-contributing-guidelines
https://github.com/atom/atom/blob/master/CONTRIBUTING.md
https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md
Not a github style, but complete for a project: https://www.drupal.org/contribute

I am happy to help contribute to this task!

**Comment by shrop** [comment]
Also, https://github.com/meteor/meteor/wiki/Meteor-Style-Guide :)

**Comment by gmsecrieru** [comment]
:+1: this is a great contribution!

**Comment by shrop** [comment]
Thanks @gmsecrieru. I am starting a Quip document that can be a start and get in to a PR as a start. Contributing.md can easily be added to and changed from there, so we just need a solid start that the project leads agree fits Rocket.Chat coding and overall philosophy.

**Comment by shrop** [comment]
@gmsecrieru 2 tabs for indentions is a Rocket.Chat style I can add to the doc?

**Comment by gmsecrieru** [comment]
I would say so.

**Comment by shrop** [comment]
Formatting standards like this may be helpful: https://github.com/polarmobile/coffeescript-style-guide

**Comment by kakawait** [comment]
It's my 2 cents point of view but when working with community we should create a standard documentation and **above all** use tools like linter (#1195), coding style checker to ensure new PR respect standard.

**Comment by gmsecrieru** [comment]
+1

**Comment by shrop** [comment]
@kakawait couldn't agree more

**Comment by karlprieb** [comment]
Any update?

**Comment by engelgabriel** [comment]
Started at https://rocket.chat/docs/developer-guides/code-styleguide

@MartinSchoeler please add a NodeJS section.

**Comment by paulovitin** [comment]
@geekgonecrazy and @graywolf336 about the discussion of how to check the presence of property in object.

The bug in code is by no checking if user contains roles property, so a send a PR using a secure check of property in an object using ESLint recommendation:

```javascript
if(Object.hasOwnProperty.call(user, 'roles') && Array.isArray(user.roles)) {
}
```
But, for not being so clear of understand and no according to code style, we agree to use like this:

```javascript
if(user.roles && Array.isArray(user.roles)) {
}
```
But this can cause some side effects if we checking a property and this property has a false value. We need do the things most safety way possible.

So I believe this approach can be better using spread and checking the type of property, like this:

```javascript
// this dont throw error if user not has property roles
// roles in this case will be undefined
const { roles } = user;

if(Array.isArray(roles)) {
} 
```

Is most readable and good styling.

**Comment by rodrigok** [comment]
@paulovitin IMO, there is no need to check if roles property exists and then check the property type, you could check the type directly:
```
if(Array.isArray(user.roles)) {
...
}
```

**Comment by paulovitin** [comment]
@rodrigok you are right. 👍

**Comment by marceloschmidt** [comment]
We currently use eslint to validate coding style, and our CI will not allow PR without passing the rules. Please check https://github.com/RocketChat/eslint-config-rocketchat
