### ISSUE TITLE
Users.list doesn't list all users

### ISSUE THREAD

**Issue by ThomasRoehl** [RocketChat/Rocket.Chat#11636]
I have a user called api.test:
`http://localhost:3000/api/v1/users.info?username=api.test`
```
{
    "user": {
        "name": "api.test",
        "username": "api.test",
        "status": "offline",
        "utcOffset": 2,
        "type": "user",
        "active": true,
        "emails": [
            {
                "address": "ApiTest@test.com",
                "verified": true
            }
        ],
        "statusConnection": "offline",
        "createdAt": "2018-02-05T09:17:07.622Z",
        "lastLogin": "2018-07-30T08:56:40.480Z",
        "services": {
            "resume": {
                "loginTokens": [
                    ...
                ]
            },
            "password": {}
        },
        "requirePasswordChange": false,
        "roles": [
            "user"
        ],
        "_id": "YJoHTEqxZJRuQnHeq"
    },
    "success": true
}
```

When I call `http://localhost:3000/api/v1/users.list` it returns a list but the user api.test is not there (just some other users).

I logged in via api as admin.
I can see the user in the admin UI when logged in as an admin.
There is no error shown in the log.

I don't know how to reproduce this since newly created users are always listed in the `users.list` call.

Maybe someone else noticed the same problem.

**Comment by Hudell** [comment]
Possibly related to #11599

**Comment by MarcosSpessatto** [comment]
Hello @ThomasRoehl, please see https://github.com/RocketChat/Rocket.Chat/issues/11599#issuecomment-409920132. The open Pr fixes a part of the problem, but for the call you put here, I see that you would like to filter by `username`, in which case the filter you applied the call is incorrect, you should filter as `http://localhost:3000/api/v1/users.list?query={"username": "api.test"}`.
