### ISSUE TITLE
Single Channel Guest - user can send direct message to other users

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat#11632]
Hi, I need "Slack Single Channel Guest" in Rocket.Chat.

I created the `ChannelGuest` role with these permissions:

- Create Direct Messages [create-d]
- Edit Message [edit-message]
- Mention All [mention-all]
- Mention Here [mention-here]
- send-many-messages [send-many-messages]
- Snippet Message [snippet-message]
- View Direct Messages [view-d-room]
- View History [view-history]
- View Private Room [view-p-room]

Everything is great. Guest can not find or join 'public channels' or 'private groups' using mentions and find box.

But guest user send can send Direct Message to other users - I do not want it.

What I need: create guest users with access to selected private groups (one or more). This user can not view the list of all users, or send direct messages to other users.

Customers should not see other users or send him direct messages.

**Comment by kaiiiiiiiii** [comment]
Hi @tuxmartin,

Rocket.Chat aims to keep the Github issues for bugs and feature requests only. Your request does not fit that criteria.
Please see the [guidelines for support](https://rocket.chat/docs/getting-support/) to get proper help.

Thanks,
Kai

@TwizzyDizzy
