### ISSUE TITLE
can't upload file on Android

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat#11654]

**Comment by gudge25** [comment]
![screenshot_2018-08-02-11-51-45-165_chat rocket android](https://user-images.githubusercontent.com/2346208/43573659-ea289db6-964a-11e8-9067-7cd289777036.png)

**Comment by gudge25** [comment]
But it works on PC.  -same settings

**Comment by MartinSchoeler** [comment]
@gudge25 please reopen this at the [Android App](https://github.com/RocketChat/Rocket.Chat.Android) Repository. Thanks!
