### ISSUE TITLE
Video messages not working?

### ISSUE THREAD

**Issue by user34545** [RocketChat/Rocket.Chat#11651]
Description
Trying to send a video message does not work.

Server Setup Information:
Version of Rocket.Chat Server: 0.68.2
Operating System: Ubuntu 16.04
Deployment Method(snap/docker/tar/etc): docker
Number of Running Instances: 1
mongoDB Version: 3.2

Steps to Reproduce:
Trying to send a video message. Click the record button, click the stop button, click ok.
Get the error message "File empty".

I tried it with my local instance and with your demo instance, both do not work.
I tried it in the browser and in the Rocket.Chat client, both do not work.

Note: I followed the logs of the container all the time and set the logging to level 2. Nothing was logged. So I guess this is an issue on the client-side?

Normal file uploads and voice messages work fine btw.

Expected behavior:
Video gets recorded and sent to other people.

Would greatly appreciate any help. Thank you.

**Comment by ikzk** [comment]
I encountered the same issue using the docker image

**Comment by SurferLancelot** [comment]
same issue for me

**Comment by yZhenyuanLiu** [comment]
same issue for me

**Comment by FaizanZahid** [comment]
I m having similar issue of empty file even after adding webm in allowed media upload type. Do you know what is the correct syntax for putting in webm allow file type?

**Comment by FaizanZahid** [comment]
When a user sent me a .wmv file, i am unable to play that file, it just plays nothing and a black screeen is shown.
