### ISSUE TITLE
code after quote scrambles the code (also in code fences)

### ISSUE THREAD

**Issue by DanielRuf** [RocketChat/Rocket.Chat#11656]
### Description:

Posting code directly after a quoted text scrambles it.

### Steps to reproduce:

1. Go to a channel
2. Post a quote + `window.location.reload`
```
> some quote
`window.location.reload();`
```

### Expected behavior:

> some quote

`window.location.reload();`

### Actual behavior:

> some quote

=!=JzaQxzAZZDpLZ4AvK=!=

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System:Ubuntu 16.04.4 `Linux version 4.4.0-87-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017`
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by vynmera** [comment]
Quadruple \` also cause this effect, \`\`\`\`something\`\`\`\` turns into something like `=!=JzaQxzAZZDpLZ4AvK=!=`

**Comment by DanielRuf** [comment]
> Quadruple ` also cause this effect, ````something```` turns into something like =!=JzaQxzAZZDpLZ4AvK=!=

True.

> ```
> code
> ````

does not work anymore
