### ISSUE TITLE
Zoom integration

### ISSUE THREAD

**Issue by john171** [RocketChat/Rocket.Chat#11655]
Hi,

I would like to see integrating zoom plugin to rocket chat for video conferencing. Mattermost has zoom integration.

https://docs.mattermost.com/integrations/zoom.html

**Comment by reetp** [comment]
This is a NFR and currently policy is this should be opened in the forums:
https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
