### ISSUE TITLE
how to use rest api for send message(@all)

### ISSUE THREAD

**Issue by TrumanDu** [RocketChat/Rocket.Chat#11652]
i want to use @all  in rest api ,but  i don't know  how to do. thanks

**Comment by kaiiiiiiiii** [comment]
Hi @TrumanDu,

Rocket.Chat aims to keep the Github issues for bugs and feature requests only. Your request does not fit that criteria.
Please see the [guidelines for support](https://rocket.chat/docs/getting-support/) to get proper help.

Thanks,
Kai

@TwizzyDizzy

**Comment by TrumanDu** [comment]
thanks for u contribute @kaiiiiiiiii
