### ISSUE TITLE
Add custom slash command in my Rocket.chat

### ISSUE THREAD

**Issue by DesRodman** [RocketChat/Rocket.Chat#11668]
Hi there.

We just need to make own slash command.
In Slack i used "Custom command"

But can find description for me.

Help me please. How i can add own command in Rocket.chat?

Thanks

**Comment by vynmera** [comment]
This should be possible with Rocket.Chat Apps!

**Comment by gudge25** [comment]
@vynmera  please  give more information. Thanks

**Comment by gudge25** [comment]
https://github.com/RocketChat/Rocket.Chat.Apps-engine    WHIS  ONE ?

**Comment by kaiiiiiiiii** [comment]
Definitely possible with a custom App.

Please see the [rocket.chat forums](https://forums.rocket.chat) to get help with the Rocket.Chat App Framework as Github isn’t the right place for that.

Thanks,
Kai

**Comment by MartinSchoeler** [comment]
As @kaiiiiiiiii mentioned, please move this to the rocket.chat forums. Thanks!
