### ISSUE TITLE
Alerting of past channel joins / user mentions

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1166]
There seems to be a case where you are renotified of mentions.  I had my phone going off randomly through out the day a couple of days ago.  Then today on channel join someone had it sit there and ding for several minutes straight.  I can only assume it was going through and alerting of every past mention in the channel.

**Comment by marceloschmidt** [comment]
@geekgonecrazy do you think this has been solved? Have you experienced this lately? If not, can you close it please?

**Comment by geekgonecrazy** [comment]
@marceloschmidt I haven't seen this happen for a while.  So I guess its resolved?  I'll close until I see otherwise :+1:

**Comment by geekgonecrazy** [comment]
@marceloschmidt i've had this happening to me all day.  I'm not sure what's going on.  I hear the ding dong airplane sound randomly all day.

**Comment by ulope** [comment]
Isn't that the "somone has become active" sound?

**Comment by geekgonecrazy** [comment]
@ulope I believe the airplane noise only occurs when you join a channel.  So if you're hearing it often, you're likely experiencing the same bug.  On the demo server when it happens it happens in bulk out of no where.

**Comment by agentirons** [comment]
Is there a list somewhere of the different sounds built in (until this gets closed: https://github.com/RocketChat/Rocket.Chat/issues/1268)? I've only heard the airplane noise due to the same bug.

**Comment by geekgonecrazy** [comment]
I haven't seen this one for a while. Going to go and close this.
