### ISSUE TITLE
[BUG] Localization set in settings is ignored when i'm log on to the server.

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat#11660]
Version of Rocket.Chat Server: 0.68.3
Operating System: Debian 8
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.11.3

Each time i'm log on to the server via the web interface, the localization changes to English. The original server localization is Russian (in the general settings and in the account settings).

**Comment by chatnl** [comment]
Same problem here only I have set the general setting to dutch and my own setting to english. Somehow I keep getting the dutch language now every time I login until I press CTRL F5. Looks like some sort of caching problem.
