### ISSUE TITLE
PSTN Integration

### ISSUE THREAD

**Issue by kaoecoito** [RocketChat/Rocket.Chat#11676]
Hello,

 In the list of Rocket chat items are mentioned integration with the PSTN. I work with telecom development so maybe I can help, but would you like to understand better how you imagine the chat interaction with the PSTN?

**Comment by Ismaw34** [comment]
You can see the other thread:
https://github.com/RocketChat/Rocket.Chat/issues/3488

My wish list:
Call or receive calls from any point inside chat.
The call does not drop when changing pages/chats.
Asterisk support.

Thanks.
