### ISSUE TITLE
"Your Free Trial Has Now Expired" alert appears on self-hosted rocket.chat

### ISSUE THREAD

**Issue by onthebeachh** [RocketChat/Rocket.Chat#11678]
**Description:**
I did a DB migration from our rocket.chat cloud instance to our self-hosted one, and it still has the following message appearing each time that we open rocket.chat
"Your Free Trial Has Now Expired!
To continue using with out interruption, please click here to visit cloud console! If you have any questions please contact us at cloud.support@rocket.chat" 

**Some useful information**
- Version of Rocket.Chat Server: 0.68.3
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 3.4.6

We would like to remove/deactivate this message. Any suggestion?

**Logs**
`
Exception in callback of async function: TypeError: Cannot read property 'getRedirectURL' of undefined
    at FileUploadClass.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1176:14)
    at Object.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:549:20)
    at /app/bundle/programs/server/app/app.js:7884:27
    at runWithEnvironment (packages/meteor.js:1238:24)
    at packages/meteor.js:1251:14
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getRedirectURL' of undefined
    at FileUploadClass.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1176:14)
    at Object.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:549:20)
    at /app/bundle/programs/server/packages/rocketchat_file-upload.js:817:25
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getRedirectURL' of undefined
    at FileUploadClass.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1176:14)
    at Object.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:549:20)
    at /app/bundle/programs/server/packages/rocketchat_file-upload.js:817:25
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)`

**Comment by tassoevan** [comment]
@geekgonecrazy Check this, please.

**Comment by geekgonecrazy** [comment]
With out a screenshot.. I'm guessing you are talking about a banner.

Go-to DB and execute this: 
`db.users.update({roles:{$in: ["admin"]}}, {$unset:{"banners.expire1":""}}, {multi: true})`
