### ISSUE TITLE
<ctrl>+<enter> does not insert a blank line at cursor

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#11677]
Description at https://github.com/RocketChat/Rocket.Chat.Electron/issues/792

**Comment by ggazzo** [comment]
@sampaiodiego do you have any suggestion ?

**Comment by sampaiodiego** [comment]
<kbd>ctrl</kbd>+<kbd>enter</kbd> should send the message IMO

**Comment by tassoevan** [comment]
Either way something have to be done to handle this behavior:
![ctrl enter](https://user-images.githubusercontent.com/2263066/47590946-58770a00-d944-11e8-8aa7-034e5ccfd825.gif)
I'll work on @sampaiodiego suggestion, but this can generate some overhead for our support.
