### ISSUE TITLE
Markdown doesn't support all languages

### ISSUE THREAD

**Issue by adipose** [RocketChat/Rocket.Chat#11671]
### Description:

Not all languages supported [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) are parsed by Rocket.Chat

### Steps to reproduce:

1. Type in: 
\`\`\`bat
c:\dir
2. Hit enter

### Expected behavior:

It should highlight "dir" with windows batch file highlighting

### Actual behavior:
![image](https://user-images.githubusercontent.com/3324395/43661392-ec93f308-9716-11e8-8d4b-8342489fd032.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.1
- Operating System: CentOS 7
- Deployment Method: yum
- Number of Running Instances: 1
- DB Replicaset Oplog: disabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.6

**Comment by tassoevan** [comment]
I couldn't reproduce it. Is `Enable Marked GFM` option (under `Administration > Message > Markdown`) set to `true`?

**Comment by adipose** [comment]
@tassoeven Yes.  I see that there are two markdown parsers available--I'll try the "marked" one, now.

**Comment by adipose** [comment]
The problem has gone away when using "Marked."  I guess maybe that should be the default parser?

**Comment by tassoevan** [comment]
Not really. This is not a feature of the original Markdown specification, but is present in the GitHub Flavored Markdown specification parsed by Marked. The Markdown parser is an option in Rocket.Chat exactly because each one is compliant to a different standard.
