### ISSUE TITLE
[Marked MD Parser] Line break in messages

### ISSUE THREAD

**Issue by a5his** [RocketChat/Rocket.Chat#11675]
### Description:
Line break is not working as expected. I have chose `Marked` from the Markdown parser options through settings. This works with `Original` option. After going through the code I figured out that the line breaks `\n` are removed and messages are rendered inside `p` tag by below code from file `package/rocketchat-markedown/parser/marked/marked.js`.
```
msg.html = _marked(s.unescapeHTML(msg.html), {
		gfm,
		tables,
		breaks,
		pedantic,
		smartLists,
		smartypants,
		renderer,
		sanitize: true,
		highlight
	});
```
Just wanted to confirm that whether is intentional or not? In addition, the sub options under `Marked` 
`Enable Marked Breaks` setting is not affecting anything in the view either you chose `true` or `false`. 

Since `p` tag is used to render these message, is this UI bug?

### Steps to reproduce:

1. Go to any channel and type your message with line breaks using `Shift` plus `Enter` key.

### Expected behavior:

The line break should have actually separated the messages.

### Actual behavior:

The line break is not separating the messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.63.3
- Operating System: Darwin
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.1
- MongoDB Version: 

### Screenshot
![markdown](https://user-images.githubusercontent.com/330362/43676034-1b3ed720-9809-11e8-8394-c9c130c6b5d2.gif)

**Comment by felixmind** [comment]
This is a real problem. And it does not allow to work well.

**Comment by naiaokami** [comment]
Yes; this is an issue.

**Comment by horstepipe** [comment]
Hello team,
just to verify, is there no way to insert a line break into a message at the moment?

**Comment by reetp** [comment]
As far as I am aware this was fixed ages ago and probably should be closed.
Seems to work perfectly at open.rocket.chat 
Please test and advise.

**Comment by horstepipe** [comment]
no this doesn't work when you set markdown to "marked". open.rocket.chat seems to have it set to "original", there the line breaks work, but most other markdowns don't work when you have set it to "original".

**Comment by horstepipe** [comment]
So even a simple list like 
`
* list item 1
* list item 2
`

is not being rendered properly when you set it to "original"

**Comment by gabriellsh** [comment]
Still happens 3.0.0-develop

**Comment by sst2010** [comment]
Indeed, this is a very painful bug. Really need a fix on this.

It can only be solved at the cost of losing major markdown features. That doesn't seem acceptable.

**Comment by sst2010** [comment]
Hey guys, I just found a workaround, a very simple one indeed.

**P.S.:** You'll need to have access to `Administration` settings to apply the workaround.

### Step 1: Open `Custom CSS`
- Open this link: https://chat.incendia.in/admin/Layout
  - Replace the domain `https://chat.incendia.in` with your chat site's URL ( **e.g.,** http://localhost:3000/ ).
  
**OR**
  
- Click on the `3 dots` in the top-right of the left-panel.
- Open `Adminstration` settings.
- Scroll down to find `Layout` settings.

### Step 2: Add the CSS
- Expand the `Custom CSS` section.
- Add the below code below any existing code in the section:
```
h1 {
  margin-top: 0.5em !important;
  margin-bottom: 0.5em !important;
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
  border-bottom: 2px solid #ddd !important;
}

h2 {
  margin-top: 0.5em !important;
  margin-bottom: 0.5em !important;
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
  border-bottom: 2px solid #ddd !important;
}

h3 {
  margin-top: 0.5em !important;
  margin-bottom: 0.5em !important;
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
  border-bottom: 1px solid #ddd !important;
}

h4 {
  margin-top: 0.5em !important;
  margin-bottom: 0.5em !important;
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
  border-bottom: 1px solid #ddd !important;
}

h5 {
  margin-top: 0.5em !important;
  margin-bottom: 0.5em !important;
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
  border-bottom: 2px solid #ddd !important;
}

h6 {
  margin-top: 0.5em !important;
  margin-bottom: 0.5em !important;
  padding-top: 0.5em !important;
  padding-bottom: 0.5em !important;
  border-bottom: 2px solid #ddd !important;
}

```

- The `border-bottom: ...` lines are a little add-on I tried & liked. 😅
- If you don't like the border below headings in the updated UI, remove those lines. 😃

Have a great day !!

**Comment by ulope** [comment]
Thanks for reminding me of the custom css option!

I'm not sure what your CSS has to do with line breaks though.
I'm now using
```css
p + p {
  margin-top: 1em;
}
```

And that works like a charm

**Comment by sst2010** [comment]
> Thanks for reminding me of the custom css option!
> 
> I'm not sure what your CSS has to do with line breaks though.
> I'm now using
> 
> ```css
> p + p {
>   margin-top: 1em;
> }
> ```
> 
> And that works like a charm

Thats great, @ulope .

I apologize for the confusion. I was actually playing around to improve the output of rendered markdown. I've edited my comment to specify the same.
Thanks for bringing it to my attention.

**Comment by sst2010** [comment]
>   margin-top: 1em;

@ulope Consider updating this to `margin-top: 1em !important;`.
This will prevent the `custom CSS` from being overridden by any CSS of `Rocket.Chat`.

**Comment by horstepipe** [comment]
thank you both, these are good workarounds!

**Comment by alexander-potemkin** [comment]
Doesn't work for me =(

Tried both p + p & headers custom CSS, but it doesn't apply.

Version 3.3.3
Apps Engine Version 1.15.0

Any considerations?

Switched to Marked (from Original) to make sure it looks and feels right to our users after Slack, and now it doesn't work as expected, which is a pretty much damn thing.

**Comment by keldian** [comment]
None of these fixes worked for me.

**Comment by tmartincpp** [comment]
Is this can help anyone, if you want to have line breaks with lists too you can do : 
```
p + p {
  margin-top: 1em !important;
}
p + ul {
  margin-top: 1em !important;
}
ul + p {
  margin-top: 1em !important;
}
p + ol {
  margin-top: 1em !important;
}
ol + p {
  margin-top: 1em !important;
}
```

**Comment by LeoActency** [comment]
I confirm the comment just above is working.

Just note that users must restart their client for this to be taken into account on their side.

**Comment by IARI** [comment]
@ggazzo I wonder, why this issue was closed, since the merge request for the updated version of marked was rejected - and the issue still persists
