### ISSUE TITLE
Server becomes unresponsive after posting multiline formatted message

### ISSUE THREAD

**Issue by bbrauns** [RocketChat/Rocket.Chat#11681]
### Description:

Rocket.Chat Server becomes unresponsive after posting the following multiline formatted message:

```
Aug  6 00:07:31 owncloud-3 ownCloud[19309]: [xyz][134.76.23.45][--][no app in context][GET][/index.php/s/xyz/download?path=%2F&files[]=Video2_Albert.rar&files[]=Video3_Albert.rar&downloadStartSecret=xyz] Exception: {"Exception":"OCP\\Lock\\LockedException","Message":"\"Videos\/Valerie\/Verschluesselt\" is locked","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(2079): OC\\Files\\View->lockPath('\/Videos\/Valerie...', 1)\n#1 \/var\/www\/owncloud\/lib\/private\/legacy\/files.php(333): OC\\Files\\View->lockFile('\/Videos\/Valerie...', 1)\n#2 \/var\/www\/owncloud\/lib\/private\/legacy\/files.php(152): OC_Files::lockFiles(Object(OC\\Files\\View), '\/Videos\/Valerie...', Array)\n#3 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/Controllers\/ShareController.php(509): OC_Files::get('\/Videos\/Valerie...', Array, Array)\n#4 [internal function]: OCA\\Files_Sharing\\Controllers\\ShareController->downloadShare('xyz', Array, '\/', 'xyz')\n#5 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#7 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(103): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_Sharing\\Controllers\\ShareController), 'downloadShare')\n#8 \/var\/www\/owncloud\/lib\/public\/AppFramework\/App.php(135): OC\\AppFramework\\App::main('ShareController', 'downloadShare', Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#9 \/var\/www\/owncloud\/core\/routes.php(106): OCP\\AppFramework\\App->dispatch('ShareController', 'downloadShare')\n#10 [internal function]: OC\\Route\\Router->{closure}(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(342): call_user_func(Object(Closure), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(912): OC\\Route\\Router->match('\/s\/xyz...')\n#13 \/var\/www\/owncloud\/index.php(55): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Files\/View.php","Line":1977}
```

Posting this log-message as normal text works fine.

### Steps to reproduce:

1. Post the log line above with the three backticks: ` ``` ` as multi line prefix

### Expected behavior:

post the message

### Actual behavior:

- Message is kept in input field
- client app hangs
- server hangs

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubuntu 14.04.5 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4

### Relevant logs:

No relevant log lines can be found

**Comment by jthomae1** [comment]
Unfortunately there are no log entries regarding this error. We also get the same behavior with a previous Version (0.65.1) of Rocket.Chat.

**Comment by localguru** [comment]
Same here with RC 0.61

**Comment by bbrauns** [comment]
## Emergency steps to delete a message in mongodb
###  Find direct chat of two specific people
- `db.rocketchat_room.find({usernames: ['user-x','user-y']}).pretty()`
- note the `rid`

### Find channel by rid
- `db.rocketchat_message.find({'rid': '4EzT9u48mDndDwP3cXbuy83'}).sort({ts: 1}).pretty()`
- repeat typing 'it' to see all responses

### Delete specific message
`db.rocketchat_message.deleteOne({_id: 'mHN4QaGz6RuJ'})`

**Comment by beranPro** [comment]
Error still exists in 0.71.0 !!!

**Comment by xvilo** [comment]
Wtf, this bug. Why is this happing, and why hasn't this been fixed?

**Comment by reetp** [comment]
@xvilo because you haven't fixed it?

This is open source. It will get fixed when it gets fixed.

The developers have lots of priorities, and paying customers will come first.

You have to either fix it yourself, pay for support, or be patient.

Thank you.

**Comment by ggazzo** [comment]
thanks @reetp to understand our situation... but sometimes we made some fix too (:
actually, we were trying to send each message that got the username changed, its very very very expensive and as you can see the server/client hangs. after that change https://github.com/RocketChat/Rocket.Chat/pull/12800 I think we "fixed"(there are better ways, but ... maybe in the future :) )
@xvilo you are welcome to try #12800 and send us feedbacks 

[]s

**Comment by reetp** [comment]
Any information on this or the PR #12800 ?

**Comment by xvilo** [comment]
I don't know. We've stopped using Rocket Chat all together.

**Comment by igorr-stc** [comment]
Still have same problem with 0.74.3

**Comment by reetp** [comment]
Any news on this?

**Comment by jthomae1** [comment]
The problem still occurs with version 1.1.1

**Comment by vladborovtsov** [comment]
The issue still happening. 
Server version 2.3.1. 

Indeed, there is nothing in the logs that could give a clue.

**Comment by ggazzo** [comment]
its a highlight problem actually 😢 

https://github.com/RocketChat/Rocket.Chat/blob/develop/app/markdown/lib/parser/original/code.js#L50
