### ISSUE TITLE
Livechat: Wrong message counts.

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#11683]
### Description:

1. When visitor sends first message, message count `msgs` = `2`. But should be `1`.
2. When agent takes the incoming chat without sending any message, `msgs` is incremented, becomes `3`. But should be still `2`.
3. When room is closed, again `msgs` count is incremented, but should not be.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0-develop (30cc9720cb)
- Operating System: darwin
- Deployment Method: manual install
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS version: 8.11.3 - x64

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/11834
