### ISSUE TITLE
Avatar initials oddities with inconsistencies across browsers

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1168]
I have rocket.chat open in the OS X app as well as in Safari and Chrome on OS X. In the browsers I can see the correct avatars for people whereas in the app some users have missing graphical avatars or mixed up default avatars. For instance for someone called Maria I see 'FI' (for Finn) instead of 'MA' which it should be.

Any idea what is causing this and how to resolve it? I'm on a self hosted version running the latest (as of 3 hours ago) code and being served up behind nginx on Ubuntu 14.04. Everything else is working nicely.

**Comment by tanc** [comment]
Actually, I've just fired it up in Chrome and I'm seeing a different Avatar for user Maria. So on the desktop app I see 'FI' for Maria, on Chrome I'm seeing 'AA' for Maria, and on Safari I'm seeing the correct 'MA' for Maria.

**Comment by engelgabriel** [comment]
Did you try cleaning the cache of your browsers? Are you using any CDN on reverse proxy?

**Comment by engelgabriel** [comment]
Probably related to #1222

**Comment by tanc** [comment]
It turns out (embarrassingly) that it was browser caching. The main problem I had in clearing caches was with the OS X app which doesn't have any global way of clearing caches (that I know of). Instead I opened dev tools from the menu and selected the checkbox to 'Disable cache (while DevTools is open)', located in the settings part of devtools. I then reloaded the page a couple of times and that seemed to clear the stale and incorrect avatar icons. Hope this helps others.

![view_and_menubar](https://cloud.githubusercontent.com/assets/76320/10724733/9e11f32c-7bbe-11e5-8d9a-d4256f52f3d7.jpg)
