### ISSUE TITLE
Fill Setup-Wizard with Environment Vars

### ISSUE THREAD

**Issue by MatthiasHertel** [RocketChat/Rocket.Chat#11690]
Hi there,

i would like deploy the Rocket.Chat App without any Configuration in the Frontend.

It works good by any Setting. But I have Problem with the setup-wizard.

Is it possible to prevent the setup-wizard dialog by setting the specific Env Vars in the Docker-Compose.yml ?

Best Regards
Matthias

**Comment by mnlbox** [comment]
@MatthiasHertel I think we can do this now with setting environment variable because wizard values also save as admin setting but I think we need some information and docs update.
Related issue on `docs` repo: https://github.com/RocketChat/docs/issues/871

**Comment by reetp** [comment]
Can you confirm.whether this is an issue on latest 0.70.x please?

**Comment by mnlbox** [comment]
@reetp yes it's still an issue.

**Comment by reetp** [comment]
@rocket-cat close

Disabling the setup wizard can be configured with an Environment setting.

However, I can't find it to post here because it isn't in the docs as per #871 which really should be looked at.
