### ISSUE TITLE
It is not possible to leave a group or a channel with Slovak language

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#11699]
_From @rzelnik on May 16, 2018 15:20_

## My Setup
- Operating System: Ubuntu (Linux) 18.04
- App Version:  2.10.5

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

When the localization is switched to Slovak language, it is impossible to leave a channel or a private group. When I go to the left sidebar -> channel  -> left click to the contextual menu -> Leave room, nothing happens. When I switch back to English language, it works as expected - the "Are you sure?" modal window is shown and I can confirm "Yes, leave it!". 

### Current Behavior

Clicking to "Leave room" in Slovak localization doesn't make any response.

### Expected Behavior

It should allow to leave the room regardless of what locales are set.

This issue occurs on both Electron and Web access.

_Copied from original issue: RocketChat/Rocket.Chat.Electron#725_

**Comment by tassoevan** [comment]
_From @kaiiiiiiiii on June 14, 2018 17:51_

Hi @rzelnik,

I think you’re in the wrong repository, as the electron app is just a simple wrapper of the web page. Your issue definitely sounds like it belongs in the Server repository.

Feel free to open an issue over there (may use the search first) :)

Thanks,
Kai

https://github.com/RocketChat/Rocket.Chat

//CC: @TwizzyDizzy

**Comment by ggazzo** [comment]
@rzelnik do you know which version of rocketchat you are using?

**Comment by rzelnik** [comment]
Currently it's 2.11.0 (just updated) and the issue still occurs.

**Comment by tassoevan** [comment]
@rzelnik I think @ggazzo was asking about the Rocket.Chat server version, since this problem happens in web client too.
