### ISSUE TITLE
Unread count in app icon always wrong

### ISSUE THREAD

**Issue by gsrcobr** [RocketChat/Rocket.Chat#11694]
### Description:

Even when you don't have any unread messages in desktop application (OSX), app's icon on launcher show unread messages counter.

### Steps to reproduce:

Don't know how to reproduce.

### Expected behavior:

Unread message count on app's icon on launcher must show correct number of unread messages (and show nothing when no unread messages).

### Actual behavior:

App's icon on launcher show wrong unread message counter - even when no unread messages are presente on desktop app.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.64.1
- Operating System: CentOS 7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: On
- NodeJS Version: ?
- MongoDB Version: ? 

### Additional context

Running desktop application on OSX.

### Relevant logs:

Nope

**Comment by kaiiiiiiiii** [comment]
Wrong repository and also a duplicate [#801](https://github.com/RocketChat/Rocket.Chat.Electron/issues/801).

// CC: @TwizzyDizzy
