### ISSUE TITLE
New all-white tray icon difficult to see on light taskbar

### ISSUE THREAD

**Issue by chowbok** [RocketChat/Rocket.Chat#11695]
I have a light-grey taskbar. The new white tray icon in 2.12.0 is nearly impossible to see on there. Can it be made to have a black outline so that it's visible regardless of one's color scheme?

**Comment by kaiiiiiiiii** [comment]
Wrong repository mate :)

Fix which should be pushed with the next release:
https://github.com/RocketChat/Rocket.Chat.Electron/pull/791

**Comment by chowbok** [comment]
Sorry about that. This is where the app sent me when I selected "report an issue" from the menu. I'm on Linux, by the way. Guess I should have mentioned that, sorry.

**Comment by tassoevan** [comment]
This issue was moved to RocketChat/Rocket.Chat.Electron#804
