### ISSUE TITLE
HipChat import fails for large backup (e.g. 3 GB)

### ISSUE THREAD

**Issue by diver80** [RocketChat/Rocket.Chat#11693]
### Description:

HipChat export was created (Export options: Include files, Include one-to-one chats) and decrypted as documented here: https://rocket.chat/docs/administrator-guides/import/hipchat/enterprise.
Looking at the file the export is > 3G

`
 ✘ fhess@fhess-laptop  ~/tmp/rschange  ls -lah hipchat-2018-08-0*.tar.gz
-rw-rw-r-- 1 fhess fhess 3,1G Aug  6 15:11 hipchat-2018-08-06_07-57-43.tar.gz 
`

Trying to import the file as HipChat (tar.gz) results in tab crash - starting chrome with the arguments --no-sandbox or --max_old_space_size=32768 doesn't change anything. Using firefox takes a bit longer but the tab also crashed. Exporting and importing data from the same instance excluding one-to-one chats results in a file ~ 5MB which can be successfully imported.

### Steps to reproduce:

1. Create HipChat backup of a large instance
2. Decrypt tar.gz
3. import large export as HIPCHAT (TAR.GZ) 

### Expected behavior:

User/Channel selection is shown

### Actual behavior:

Crash of browser tab

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubuntu 16.04 LTS
- Browser: Chrome 69.0.3497.23
- Deployment Method: docker

### Additional context

Atlassian is shutting down HipChat. Users from cloud instances are merged to Slack - currently no on-premise solution left. => Reason for migration to Rocket.Chat.
https://www.atlassian.com/blog/announcements/new-atlassian-slack-partnership

### Relevant logs:
Nothing is logged on server side as the processing seems to be done on client side.

**Comment by diver80** [comment]
Is there a workaround to skip the selection and import all the data to skip the client side processing of the large file e.g. uploading file per curl?

**Comment by artem-levashov** [comment]
same question. my hipchat backup file  is 1Gb - after 10 seconds of upload import says that it has  wrong file type. but file is correct *.tar.gz and it is extractble

**Comment by gf-raveinid** [comment]
I have the same error posted in issue #11355

**Comment by piotrkochan** [comment]
As I said in #11355 the solution is to use JSONStream or something similar.
I do not recommend upload Hipchat export with attachments, let Rocket download them online like in is already done in https://github.com/RocketChat/Rocket.Chat/pull/11910/files#diff-3eca9ae982cdceee5949ee80a7848f98R477

Also, I really don't know why but if you upload large file set Logger Level to 1. On >1 all contents of uploaded file are printed to logs... it takes a lot of time to do so.

```
this.extract.on('entry', Meteor.bindEnvironment((header, stream, next) => {
[....]
stream
    .pipe(this.JSONStream.parse('*'))
    .on('data', Meteor.bindEnvironment((chunk) => {
        console.log(chunk); // {User: ...} or {Room: ...} etc
    })
```

**Comment by diver80** [comment]
When not exporting attachments during HipChat export the import in Rocket.Chat succeeds. I'll added a PR for a Troubleshooting section in Import documentation: https://github.com/RocketChat/docs/pull/952

**Comment by rodrigok** [comment]
Can someone share an larger export with us? That way we could work to improve this.

**Comment by Hudell** [comment]
We've recently improved our import process. On version 0.74.3, it should be much faster and able to import a 3GB file without trouble.

**Comment by 88fingerslukee** [comment]
When will this version be pushed to snap? It's there for armhf but not for amd64?
