### ISSUE TITLE
Image resources when using client certificates

### ISSUE THREAD

**Issue by storrgie** [RocketChat/Rocket.Chat#1169]
I have an instance where I'm using ssl certificate based authentication. I'm using the poor-mans equivalent, which is to self issue those certificates as files. Based on discussion with @geekgonecrazy it appears that rocket.chat checks the file url to make sure it has valid ssl (and you can enable self signed certificates), but when using client certificates this check fails. Images uploaded to chat then appear as links.

I don't want to muck with issuing a client certificate to the rocket.chat application, so I wonder if this is a wont-fix type issue. I just wanted to get some more eyes on it.
##

**Comment by geekgonecrazy** [comment]
I think before dismissing as wont-fix (I hate that label).  Lets discuss how this could be resolved a little cleaner.  If it can be resolved.

So you're manually issuing the client certificate and if the client does not have this then it can't complete the ssl connection.

So a user couldn't even use the chat platform at all with out this certificate.

@RocketChat/owners should we even be checking uploads server side on links?  Don't we already know the media type?  Maybe we can resolve this that way?

**Comment by storrgie** [comment]
Correct. In this case I issue the certificate, then create

**Comment by geekgonecrazy** [comment]
In addition... It actually seems like a waste of resources for us to be checking links for uploaded files.  Since we do know the type.  Occasionally it actually doesn't even come back with an image preview.  So maybe this would be a performance /  UI/ UX improvement anyways?

**Comment by storrgie** [comment]
Sorry, hit the key on accident.

I'm wondering if this might also make it so avatars wont render.

**Comment by emcguinness** [comment]
I have not use client certs myself and will likely not have time to try them until Friday but I have spent a bit of time looking into certs to get my self signed one going without having to use the allow all self signed cert flag(which it now is). For that I found [this guide](https://github.com/coolaj86/node-ssl-root-cas#important-try-this-first) had some good info, ignore the tool he provides and just that first section explains well how you should have your certificates setup.

The other part is the user certs, this guide [here](https://engineering.circle.com/https-authorized-certs-with-node-js/) looks like it is a good example of how to do this. Perhaps between the two you might be able to work something out(I have not tried this yet but will later this week if you haven't got it sorted yet). It definitely looks possible though.

For reference the ssl options for Rocket.chat are [here](https://github.com/RocketChat/Rocket.Chat/blob/8403a1c34ca5717fc3c50155e165044b44953c92/packages/rocketchat-oembed/server/server.coffee#L12)

**Comment by geekgonecrazy** [comment]
@storrgie I don't think those pass through the same preview check.  So might be related, but not the same.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
