### ISSUE TITLE
Auto-translation for messages

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#117]
I think we could have a auto-translation setting that if enabled would display the message sent in its original language and below it a auto-translated version of it.
##

**Comment by engelgabriel** [comment]
Reference: http://texturner.com/

**Comment by klatys** [comment]
- Yandex offers free translation to 1M characters/day & 10M characters/month - https://tech.yandex.com/translate/
- Google requires payment for their api, but there is a workaround https://ctrlq.org/code/19909-google-translate-api

I propose using yandex with custom api key for each instance (user would have to generate it). If they were to use their quota, then they'd have to extend to paid version ($15/1M chars - still cheaper than google's $20/1M).
Also makes sense to select whether to translate everything, chanel, or message on demand (like facebook or twitter does)

**Comment by Rohlik** [comment]
I think this is implemented in https://github.com/RocketChat/Rocket.Chat/commit/976dcef1e76e5f472b003372bf92eb1c3d9c7709

**Comment by MartinSchoeler** [comment]
@marceloschmidt has this already been implemented? Can we close this issue?

**Comment by marceloschmidt** [comment]
Thanks @Rohlik and @MartinSchoeler
