### ISSUE TITLE
Window scrolls down on 'Page down' keypress in message input field

### ISSUE THREAD

**Issue by Hativ** [RocketChat/Rocket.Chat#11702]
### Description:

If my cursor is in the chat message input field and I press the "Page down" key on my keyboard, the whole Rocket Chat scrolls down. This is caused by the following css:

```
.main-content {
  margin-bottom: 25px;
}
```

I fixed it by putting
```
.main-content {
  margin-bottom: 0
}
```
in Layout -> Custom CSS.

### Steps to reproduce:

1. Click in chat message input
2. Press "Page down" key

### Expected behavior:

Nothing should happen.

### Actual behavior:

Window content scrolls down.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3

**Comment by tassoevan** [comment]
@Hativ Can you inform what browser showed that behavior?

**Comment by Hativ** [comment]
@madguy02 It's still the same with 0.68.3.
@tassoevan Chromium 68.0.3440.106 and Rocket.Chat+ Desktop App 2.11.0

**Comment by tassoevan** [comment]
@Hativ I couldn't reproduce it; however, I think that margin causes a similar issue in mobile browser when scrolling from the chat header.

**Comment by tassoevan** [comment]
@Hativ Any change in the latest version? The #12038 may have changed this as a side effect.

**Comment by Hativ** [comment]
@tassoevan Tested it with 0.70.4 and it seems to be fixed.
