### ISSUE TITLE
IOS 11.4.1 Receiving notifications even if it's not logged

### ISSUE THREAD

**Issue by cunhazord** [RocketChat/Rocket.Chat#11701]
### Description: 
I'm getting notifications even if I'm not logged in any server

### Steps to reproduce:

1.  Open RocketChat app
2.  Log out from any server
3.  Close RocketChat
4.  Test it

### Expected behavior: 
Not get notifications

### Actual behavior: 
Receiving notifications from a chat I'm not logged

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.4
- Operating System: IOS 11.4.1

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.iOS #2115](https://github.com/RocketChat/Rocket.Chat.iOS/issues/2115) via [**ZenHub**](https://www.zenhub.com/)
