### ISSUE TITLE
Dock badge notification icon not clearing after reading messages

### ISSUE THREAD

**Issue by LisaMR8** [RocketChat/Rocket.Chat#11707]
### Description:

Yesterday (8/7) I downloaded and installed the latest RocketChat update. Since then, when I get a new message and the app icon in my Mac Dock gets a badge number, even if I read the new messages that badge number doesn't clear. I can hard refresh the application and the numbers are still there. The only way to clear the unread badge icon is to completely exit the app and reopen it.

### Steps to reproduce:

1. Get a new message, see that in the dock the application icon has a badge number of unread messages
2. Read the message
3. Check and see that the unread badge number is still there

### Expected behavior:

When I read a new message I would think the unread badge numbers would clear

### Actual behavior:

<img width="915" alt="screen shot 2018-08-08 at 9 13 49 am" src="https://user-images.githubusercontent.com/42210273/43839209-8c8182fe-9aeb-11e8-9d48-7eb74d3d8264.png">
<img width="902" alt="screen shot 2018-08-08 at 9 14 43 am" src="https://user-images.githubusercontent.com/42210273/43839211-8c9798d2-9aeb-11e8-9bdd-38d0248d85b5.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 2.12.0
- Operating System: MacBook Pro Version 10.13.6 (17G65)
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by kaiiiiiiiii** [comment]
Wrong repository and also a duplicate [#801](https://github.com/RocketChat/Rocket.Chat.Electron/issues/801).

// CC: @TwizzyDizzy
