### ISSUE TITLE
meteor iOS without styles

### ISSUE THREAD

**Issue by danielgomezrico** [RocketChat/Rocket.Chat#1171]
after running `./build-ios-sh` it prints:

```
- Change provisioning profiles
- Convert icons to use Asset Catalog
- Add more icons
- Add more splashs
```

What does that mean? When I run the project that it created the view is completely without styles and scroll and is unusable.

How can I build the iOS meteor version right?

![img_2740](https://cloud.githubusercontent.com/assets/76348/10592272/a8b7ca92-7680-11e5-939e-280726fda113.PNG)

**Comment by Tharnas** [comment]
For me the style is also broken in android.

**Comment by Tharnas** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat/issues/1106

**Comment by geekgonecrazy** [comment]
@danielgomezrico yes please join in on the discussion over on #1106 might as well combine our efforts.  :+1:
