### ISSUE TITLE
Automatically add to Channel or private room through ldap filters

### ISSUE THREAD

**Issue by atilaloise** [RocketChat/Rocket.Chat#11710]
Through Active Directory or ldap group filters, determine public and private channels to which users should be inserted shortly after the first login.

Example:
users belonging to the group "TI_REDES", after the first login (or register) in the rocket chat, will be inserted in channels #TECNOLOGIA and in the private room "REDES"

Maybe through an option in creating the room, put a field called "ldap groups" and everyone who belongs to the group selected in that field, will be inserted in the room automatically.

**Comment by wreiske** [comment]
Pull request is in: https://github.com/RocketChat/Rocket.Chat/pull/14278
