### ISSUE TITLE
[QUESTION] What API should be used for custom room types?

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11715]
We're adding support for custom room types on iOS and Android, but we found that the APIs that we're currently using are specific to each kind of room. When the room is a custom type, how should we proceed?

Examples:

- `channel.messages`
- `channel.members`
- `channel.files`
- ...

**Comment by rodrigok** [comment]
We don't have a good definition of who to create custom room types that would be able to be supported via API only without client changes.

More details at https://github.com/RocketChat/Rocket.Chat.Android/issues/1282#issuecomment-417325634
