### ISSUE TITLE
Latest (08/06/18) pull of Docker Image hangs in Admin Menu

### ISSUE THREAD

**Issue by ahartlaub** [RocketChat/Rocket.Chat#11714]
Nothing weird in logs that I have found, but since pulling latest docker image, Admin menu hangs here:

![image](https://user-images.githubusercontent.com/11774580/43850416-7c8ab8e0-9afd-11e8-81b3-c2038527b2c2.png)

**Comment by ahartlaub** [comment]
Seems to have finally loaded after about 8 minutes.

**Comment by reetp** [comment]
@rocket-cat close
Please reopen if you have similar issues on the latest version.
