### ISSUE TITLE
Add or change a server icon other than the "Rocket.Chat"

### ISSUE THREAD

**Issue by tempusthales** [RocketChat/Rocket.Chat#11713]
**Is your feature request related to a problem? Please describe.**
Cannot update or add a new Rocket.Chat client icon.

**Describe the solution you'd like**
An option to add or change the Rocket.Chat client icon.

**Describe alternatives you've considered**
none

**Additional context**
Screenshot: https://i.imgur.com/UyKi0pz.png

**Comment by kaiiiiiiiii** [comment]
Administration -> Assets -> *

I’m not quite sure which asset is responsible for the sidebar icon, but it’s definitely possible to change it.

**Comment by pdg-tx** [comment]
I changes all of the icons there, and it still doesnt do it
https://i.imgur.com/xDowJ2H.png

**Comment by kaiiiiiiiii** [comment]
Did you press the “Apply and push to all clients” button afterwards?

**Comment by tempusthales** [comment]
I did, and it still didn't refresh the icon on the side bar

**Comment by tempusthales** [comment]
If this is not a new request, lets close it, and I will recreate as a bug request.

**Comment by bittner** [comment]
Is there a bug request for this? If yes, please link to it!

I have the same request. It would be nice if the icon that is used for displaying at the bottom of the user list were used also as the icon for the sidebar.

**Comment by fcecagno** [comment]
https://forums.rocket.chat/t/how-to-change-icon-for-server-list/589

**Comment by Tri0L** [comment]
**Administration -> Assets -> favicon (svg)**

this field contains server logo (left side in desktop apps).
