### ISSUE TITLE
Push notifications getting sent to mobile apps even when desktop client is open

### ISSUE THREAD

**Issue by atc07** [RocketChat/Rocket.Chat#11729]
Version: 0.62.0
Our users are receiving push notifications on their mobile apps even when the desktop client is open.

**Comment by kaiiiiiiiii** [comment]
Please update your server to the latest version (0.68.3).

Thanks

**Comment by reetp** [comment]
Or even 0.70.x
Closing as nothing heard from the OP. Please reopen if the problem persists on latest.

**Comment by reetp** [comment]
@rocket-cat close
