### ISSUE TITLE
Info Page Small Security Issue

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#11721]
### Description:

Non-admin users can see some server info and I think we need remove this.
### Steps to reproduce:

1.  Create non-admin user
2.  Go to an admin url like http://localhost:3000/admin/Layout then you automatically redirect to: http://localhost:3000/admin/info
3.  Click on `info`, now you can see some info about server like RC version. If a hacker know this info can use known issues to attack to the RC instance. 

### Expected behavior:
Prevent access to `*/admin` at all for non-admin users.

### Actual behavior:
![secure_server_info](https://user-images.githubusercontent.com/25859075/43882078-9eee9db8-9bc3-11e8-9bb1-d2bc5b698674.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Linux
- Deployment Method: docker (based on [this](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml))
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: like official docker image
- MongoDB Version: 3.2

**Comment by archang3l-media** [comment]
I can reproduce the Issue on my Rocketchat 0.68.3 Source/Tar instance. It's just a small information disclosure but could be fixed.

**Comment by mnlbox** [comment]
Any news about this?

**Comment by archang3l-media** [comment]
Looks fixed in the latest release.

**Comment by vynmera** [comment]
This practically only exposes the version of Rocket.Chat Server running ー accessible through `/api/v1/info` anyway.

**Comment by ggazzo** [comment]
I agree with @vynmera I will put this bug on my list, but its not so important I think.

**Comment by mnlbox** [comment]
@vynmera , @ggazzo Yes I agree that it's not so critical (If it' critical I reported this by email) but it's useful for hackers because RC is a open source project and anyone can see each version bugs and known issue.
If some RC instance not be up-to-date hackers can start attacking by find RC version and use know bugs for attack RC instance.
It's also important because some people want to use RC as a communication channel for Cryptocurrency Communities (#8284)

So I think it's better to fix this in next release.

**Comment by piotrkochan** [comment]
@mnlbox Android and iOS apps uses these informations too. There is no way to hide them.

**Comment by mnlbox** [comment]
@piotrkochan :thinking: 
How we can get RC server version from Android or iOS app?

**Comment by piotrkochan** [comment]
By http request: https://your-server/api/v1/info

**Comment by mnlbox** [comment]
@piotrkochan So maybe we need also some changes there. :thinking: 
Thanks for this note.

**Comment by wreiske** [comment]
Probably could require auth for the api info. 
The mobile apps should be able to auth and then grab the version if needed. It would be nice to be able to hide any Rocket.Chat versioning from the public eye without being authed.

**Comment by erhan-** [comment]
Is there any legitimate or functional reason why a non authenticated user needs to see the version info? This is a good tool for attackers as found vulnerabilities are not disclosed to RocketChat users and people run vulnerable versions without knowing the danger.
 
https://github.com/RocketChat/Rocket.Chat/issues/10795
https://github.com/RocketChat/Rocket.Chat/pull/14160

**Comment by Gummikavalier** [comment]
*Logged in regular users* can also see the list of all existing invites. This exposes private groups using invites to all users.

![Screenshot from 2020-04-27 18-43-17](https://user-images.githubusercontent.com/6958942/80392370-b7aa3780-88b7-11ea-8cee-8a04e9e67242.png)
