### ISSUE TITLE
0.68 snap release

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat#11720]
Any plans to push the last update to snap? Seems the update has been out for 10 days now and snap is still on 0.66

**Comment by tuxmartin** [comment]
:+1:

**Comment by TheReal1604** [comment]
@geekgonecrazy is probably the right man for this.

**Comment by kaiiiiiiiii** [comment]
Please see #11540. @geekgonecrazy explained why snaps are not up-to-date in this issue.

**Comment by tassoevan** [comment]
Duplicate of #11594.

**Comment by Droner147** [comment]
Any plans to push the last update to snap till version 0.68.4?

**Comment by geekgonecrazy** [comment]
Feel free to stay tuned in #ubuntu-snap on open.rocket.chat
