### ISSUE TITLE
Badge count gets stuck in Rocket.Chat+ on macOS

### ISSUE THREAD

**Issue by remofritzsche** [RocketChat/Rocket.Chat#11723]
### Description:

Since Rocket.Chat+ 2.12.0, the badge that shows the count of unread messages on top of the application icon in the dock gets stuck. It often shows a number of unread messages but the GUI does not show any. This didn't happen with the previous version.

### Client setup information:

- Operating System: macOS High sierra 10.13.6 (17G65)
- Rocket.Chat+ version: 2.12.0

Thanks for having a look at this 👍

**Comment by zerodahero** [comment]
I am also having the same issue. It looks like the counter in the status bar (top right corner) is accurate, though the badge on the dock (floating icon thingie) does not reset after messages are read. It seems to always read whatever the last number of unread notifications was (i.e. if i had two unread it will continue to read "2" even after reading those until I get a new unread, when it will read "1")

**Comment by TheReal1604** [comment]
@remofritzsche could you please open an issue on https://github.com/RocketChat/Rocket.Chat.electron and close this one?

**Comment by remofritzsche** [comment]
Sorry, didn't realize that there was a separate project for this (makes sense though). Probably the "Report Issue" menu item should point to the correct project.

There already [is an issue for that](https://github.com/RocketChat/Rocket.Chat.Electron/issues/801), so I won't create another one. Thank you.
