### ISSUE TITLE
A feature to embed Rock.Chat into a web Page, or a floating window

### ISSUE THREAD

**Issue by MRYingLEE** [RocketChat/Rocket.Chat#1172]
So Rocket.Chat may not affect a normal web surf.

For example, users are discussing the same web page. 

Of course, Rocket.Chat should be in a minimized mode to save space.
##

**Comment by storrgie** [comment]
![wat](http://i.ytimg.com/vi/hEfa0C897H4/maxresdefault.jpg)

**Comment by gmsecrieru** [comment]
@MRYingLEE Are you looking for [Livechat](https://rocket.chat/livechat-demo.html) ?

**Comment by MRYingLEE** [comment]
LiveChat is usful, but sometimes I want to discuss the same webpage with colleagues. In other words, I do want the same page showing when we chat. 

You may find a case in Google Docs: http://a2.files.readwrite.com/image/upload/c_fit,cs_srgb,w_620/MTIyNDM3NjY2NzIwNDgxODk0.png

**Comment by MyPod** [comment]
there's discourse which should already do something like that (although on bottom, iirc). Integration as shown in the picture probably needs the other service to be aware of rocketchat too

**Comment by crazyshot** [comment]
Just want to mention that second feature mentioned in rocket.chat features list is HELPDESK CHAT, it kind of require on-page popup, like livechat.

**Comment by maxlinux2000** [comment]
You can integrante rocketchat in a hidden iframe with a button to open or closed it.

something like that:

<script>
function showchat(rocket) {
        document.getElementById(rocket).style.display = 'block';
}
</script>
<div id="rocket" style="display: none;">
<iframe src="http://chat.mydomain.com:3000"></iframe>
</div>
<input type="button" class="my_big_button" onclick="showStuff('rocket');"></input>

**Comment by crazyshot** [comment]
Won't work for people who forbid third party cookies, as it also closes
local storage that rocket is using.

**Comment by maxlinux2000** [comment]
Put your chat in the same domain of the web page, so there are not third
part cookies.
On the port 80 there is the web page, and in the port 3000, the chat.

**Comment by valessiobrito** [comment]
+1 with the possibility to auto-create rooms, example:   <iframe src="//domain/channel/new-room"></iframe>

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
