### ISSUE TITLE
Unread messages bubble doesn't go away

### ISSUE THREAD

**Issue by tkasper** [RocketChat/Rocket.Chat#11727]
### Description:

After a while I'm recognizing that the unread messages bubble is still present but I don't have any unread messages.
If I restart the app it's gone but again after a while it shows up and will not go away until I restart the app again. 
I reinstalled the app already, still the same issue. 

### Steps to reproduce:

I just have to wait a while and the red unread bubble will not go away again. 

### Expected behavior:

The expected behaviour would be that if I don't have any unread messages left there should be no red bubble in the dock icon.

### Actual behavior:

The current behaviour is that unless I don't have any unread messages the icon in the dock shows the red bubble. 

![bildschirmfoto 2018-08-09 um 12 40 45](https://user-images.githubusercontent.com/1580938/43894927-e8dd3992-9bd3-11e8-9507-6775dc3ddfbc.png)

### Server Setup Information:

- 0.66.3
- Linux

### Additional context

macOS High Sierra / 10.13.6 / 64 bit
App-Version: Version 2.12.0

**Comment by kaiiiiiiiii** [comment]
Wrong repository and also a duplicate #801.

// CC: @TwizzyDizzy
