### ISSUE TITLE
POST /api/v1/login returns HTTP 500

### ISSUE THREAD

**Issue by crowmw** [RocketChat/Rocket.Chat#11737]
RocketChat version: 0.64.1

When i do POST request to `/api/v1/login` with valid credentials. I've got HTTP 500 error
![image](https://user-images.githubusercontent.com/2963127/43947052-4536ba84-9c87-11e8-970e-a3fba58e89fe.png)

I've got same issue when i configured CORS properly and make request from my js app.
Then i've got OPTIONS 200 (Access-Control-Allow-Origin is not same as i configured in CORS RocketChat options in administration panel `https://localhost:8080`) and then get HTTP 500 error

![image](https://user-images.githubusercontent.com/2963127/43947141-9c7e872c-9c87-11e8-90bc-dd726b632350.png)

piece of my application code
[#8404](https://github.com/RocketChat/Rocket.Chat/issue_comments#issuecomment-412000638)

**Comment by piotrkochan** [comment]
I've some issue https://github.com/RocketChat/Rocket.Chat/issues/11738

**Comment by MarcosSpessatto** [comment]
Hello @crowmw, you shouldn't send a property called `name`, the only properties supported are `username`, `email` or `user`, as you can see in the [docs](https://rocket.chat/docs/developer-guides/rest-api/authentication/login/#example-call---as-json).

**Comment by MarcosSpessatto** [comment]
Hello @crowmw, maybe it happens because you are sending `name` property, and it is not supported by API. The properties supported are `username`, `user` and `email` according the [docs](https://rocket.chat/docs/developer-guides/rest-api/authentication/login/#example-call---as-json). Please let me know if it works for you.

**Comment by crowmw** [comment]
@MarcosSpessatto I've tried with username and user too. Got same results
