### ISSUE TITLE
MacOS - Desktop App has incorrect message count on icon

### ISSUE THREAD

**Issue by carlmes** [RocketChat/Rocket.Chat#11732]
### Description:

The newly released Rocket.Chat+ (Version 2.12.0) has an incorrect message count displayed on the Rocket Chat icon in the dock.

### Steps to reproduce:

1. Wait for new messages in any of the Rocket.Chat channels
2. The Rocket Chat icon in the MacOS dock shows a little red (1) - correctly
3. The new Rocket Chat status bar widget also shows the new message count (1) - correctly
4. Open Rocket Chat App and read the new message
5. The Rocket Chat App now shows no new unread messages - correctly
6. The new Rocket Chat status bar now shows (0) - correctly
7. The Rocket Chat icon in the MacOS dock still shows (1) - INCORRECTLY

### Expected behavior:

The Rocket Chat icon in the MacOS dock should show (0) or nothing when all unread messages are read.

### Actual behavior:

The Rocket Chat icon in the MacOS dock should shows (1) when all unread messages are read.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.67.0
- Operating System: Linux 3.10.0-693.21.1.el7.x86_64
- Deployment Method: 
- Number of Running Instances: 5
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version:

**Comment by carlmes** [comment]
Workaround is to quit the app, and reload. This fixes the unread icon count until the next time a new message is received.

**Comment by kaiiiiiiiii** [comment]
Wrong repository and also a duplicate https://github.com/RocketChat/Rocket.Chat.Electron/issues/801.

// CC: @TwizzyDizzy
