### ISSUE TITLE
OPTIONS to /api/v1/login causes Internal Server Error

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#11738]
### Description:

I tried to test external tool: https://github.com/dotsomething/rocket-audit which communicates via RocketChat using REST API (Browser Request).

There was an 500 HTTP Error while login.

### Steps to reproduce:

Just send OPTIONS Request to /api/v1/login

### Expected behavior:

Empty response, maybe with some CORS headers.

### Actual behavior:

HTTP 500 Error

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubumtu 18
- Deployment Method: tested on snap, dev build by "meteor -p 2000" 
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 8.6
- MongoDB Version: bundled? really dont know

### Relevant logs:

```
W20180810-13:43:15.039(2)? (STDERR) TypeError: Cannot read property 'authRequired' of undefined
W20180810-13:43:15.039(2)? (STDERR)     at Route.share.Route.Route._authAccepted (/media/sdb1/dev/rnd/communicator/Rocket.Chat.repo/.meteor/local/build/programs/server/packages/nimble_restivus.js:392:18)
W20180810-13:43:15.039(2)? (STDERR)     at Route.share.Route.Route._callEndpoint (/media/sdb1/dev/rnd/communicator/Rocket.Chat.repo/.meteor/local/build/programs/server/packages/nimble_restivus.js:344:17)
W20180810-13:43:15.040(2)? (STDERR)     at /media/sdb1/dev/rnd/communicator/Rocket.Chat.repo/.meteor/local/build/programs/server/packages/nimble_restivus.js:236:33
W20180810-13:43:15.040(2)? (STDERR)     at packages/simple_json-routes.js:98:9
W20180810-13:43:15.040(2)? (STDERR) 

```

**Comment by dotsomething** [comment]
Hello, @piotrkochan I'm currently building a better version of that tool (which honestly is a piece of s#!@). Right now I'm facing a problem with another endpoint.
I'm not a Rocket.Chat developer, but I assume they are making some changes to the RESTFUL API.

**Comment by piotrkochan** [comment]
I'm closing it then.
