### ISSUE TITLE
where are the html files to edit

### ISSUE THREAD

**Issue by abdolrhman** [RocketChat/Rocket.Chat#11741]
i want to edit the html files , mainly the main page , but i have no idea the strucutre of files to edit ,
can some one give me where are the files to be edit if i want to edit the mian view of rocketChat

**Comment by graywolf336** [comment]
They are all spread throughout the code base, take some time and look into it. This is a web application and not a regular website, so the various pieces making up the application are there but in their own places.

**Comment by abdolrhman** [comment]
@graywolf336  thank you , i will give it some time , and try my best to understand it, 
am doing a task on it , and i know nothing about meteor so please excuse me if it was not a real question . thansks again :)

**Comment by abdolrhman** [comment]
can u please also tell me at least under what folder the files that i will change it @graywolf336 ,
thanks in advance and please forgive my ignorance

**Comment by kaiiiiiiiii** [comment]
Dig through the packages folder and you’ll start to understand :)

And please open a thread in the [Rocket.Chat Forums](https://forums.rocket.chat) if you need any further help, as Github isn’t the right place for that kind of discussion :)

Thanks

// CC: @TwizzxDizzy

**Comment by abdolrhman** [comment]
thank u @kaiiiiiiiii very much really apperciate your response , 
and please forgive my ignorance , thanks again .
