### ISSUE TITLE
Change “always notify mobile devices…” setting to be per-user

### ISSUE THREAD

**Issue by b-** [RocketChat/Rocket.Chat#11747]
https://github.com/RocketChat/Rocket.Chat/issues/7641 fixes https://github.com/RocketChat/Rocket.Chat/issues/1602 by adding an admin setting to ignore user presence when choosing to send push notifications.

This is fine, but as it is regarding _user_ presence I feel it should be a _per-user_ setting. 

One of my users wants it enabled because they leave their home computer logged in, but I personally find it annoying because now I get notified for every new message even if I’m staring at the channel.

Unless I overlooked something, there is no way to enable this on a per-user basis, so unless I want my users to miss messages I’m going to be bombarded with notifications...

**Comment by Exordian** [comment]
the current rocketchat mobile notification behaviour is quite unintuitive. such a setting would make it better. however i think #12514 would be the best solution

**Comment by sampaiodiego** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/17357/ that removed setting "Always notify mobile".
