### ISSUE TITLE
Can't install Rocket.Chat on Google Cloud Platform Ubuntu 16.04 VM.

### ISSUE THREAD

**Issue by Andrewyg** [RocketChat/Rocket.Chat#11752]
So I've got Ubuntu 16.04 set up at Google Cloud Platform's compute engine (VM) with Nginx installed, PHP and Node.JS supported.

First I tried to install it with `snap` with following NGINX config.

```
# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

#HTTPS Server
server {

        root /var/www/app;

        # Add index.php to the list if you are using PHP
        index index.html index.php index.htm index.nginx-debian.html;

        server_name app.andrew.at.tw;

        ...

        location /chat {
                proxy_pass http://backend/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forward-Proto http;
                proxy_set_header X-Nginx-Proxy true;

                proxy_redirect off;
}
```

And it returns me `502 Bad Gateway`, so I think fine where I tried manual installation.

As I go through all the process and start the application, set up the proxy. It returns me `Unknown path`. Where I'm totally stuck, no idea how to solve. Who can help me?

It sends me `502` with `snap` and `Unknown path` with manual installation.

**Comment by piotrkochan** [comment]
502 Bad Gateway says that there is problem on the Rocket Chat side. You should paste some logs. Anyway for topics like this there is a forum https://forums.rocket.chat/

**Comment by antgel** [comment]
Closing, as suggested there is a support forum.
