### ISSUE TITLE
Slack like integrations

### ISSUE THREAD

**Issue by whitebeatle** [RocketChat/Rocket.Chat#1175]
Features:

1. Ability to add/edit and delete events for a service (like github, trello) to be integrated like slack.
2. Custom templates for different events
3. integration to add messages to channels, direct messages

Integrations to start with?
1. <a href="https://github.com/RocketChat/Rocket.Chat/issues/1176">Github</a>
2. <a href="https://github.com/RocketChat/Rocket.Chat/issues/1177">Trello</a>

I will attach separate issues for each of the integrations. But i believe the integration setup and other details should be discussed here, while they can be service specific.

Thanks.

**Comment by gmsecrieru** [comment]
@whitebeatle Is this a possible duplicate for #202?

**Comment by marceloschmidt** [comment]
Yes, duplicate!

**Comment by Sing-Li** [comment]
@marceloschmidt @gmsecrieru -  from my understanding,  @whitebeatle *already* have an implementation that he wants us to comment on.    

@whitebeatle -  please let us know if this is the case, and where the branch might be (GitHub URL) ... we can definitely assign the task #202 to you - and start the discussion!

**Comment by whitebeatle** [comment]
@marceloschmidt  @gmsecrieru  @Sing-Li 
Sorry am busy at work. I will share the github url over the weekend as i need to make some changes. Till then i will layout the details of my implementation. 
Sadly i dont think my implementation will be compatible with other slack integrations as (#202) suggested. But i will be happy to re implement them the proper way.

**Comment by whitebeatle** [comment]
<b>Implementation</b>

<b>Services</b>
<i>rocketchat_service</i>
These hold the services currently implemented by the app. The tokens and secrets can be set via the administration> accounts.

<b>Attributes</b>:
name, caption, desc, icon, slug, createdAt<br>

<b>Integration</b>
<i>rocketchat_integration</i>
These hold the integrations for the above services

<b>Attributes</b>:
service: { _id, name, slug }
room: {_id, name}
addedBy: {_id, name} //user
enabled: boolean
createdAt, 
desc, // bot details
name: bot //name

<b>Integration options</b>
<i>rocketchat_integration_options</i>
These hold the settings/options of an integration.

<b>Attributes</b>:
integrationId, 
<i>Trello</i>
board: {id}
events: { list of event names that the bot should listen to }
hook_id // to do crud operations on the webhook

<i>Github</i>
repo {owner, name}
events { list of event names that the bot should listen to } // eg: {push: true, pull_request: true}
hook_id //crud operations on the web hook

<b>Handling integrations and webhooks:</b>
On update or delete of an integration, i update(enable/disable webhook) or delete the integration_options with the help of <a href="https://github.com/matb33/meteor-collection-hooks">matb33:collection-hooks</a>
To capture webhooks i used <a href="https://github.com/meteorhacks/picker">meteorhacks:picker</a>

<b>Generating messages for a room:</b>
I listen to the webhooks and add the relevant ones to messages based on what options were selected in the integration settings.

<b>Messages</b>
I have added a <i>t: 'bot'</i> to messages to identify them. 
I also additionally have 
bot { id, name slug } and 
remote { // this stores the relevant details needed for the message template }

I have added new <i>widgets</i> to <i>rocketchat-oembed</i> for github and trello. These templates are appended to a message on view render.

<i>Note:</i> After speaking with @Sing-Li i realize that using rocket.chat.ops to do the implementation would be better. I have tried to implement it with hubot at first and came across a few issues. These doubts regarding the implementation are below

<i>Doubts:</i>
Although I used hubot with rocketchat adapter and was successful in sending messages as bot,
1. Hubot needs a username and password and posts it on its behalf. Is this a right implementation? Slack provides you options to select a bot name, image etc. I dont think creating a user behind the scenes to achieve this is the right way, correct me if i am wrong.
2. How do i access the database of rocketchat via hubot and customize my options for posting a message.

<i>P.S</i> Although this implementation works for now for my current need, i know this is not the right way to go about this. I am a newbie to meteor ( and nodejs too) and i am still going through rocketchat's code to see how its implemented. Any help for proper implementation will be great!

Thanks!

**Comment by engelgabriel** [comment]
@whitebeatle that all sounds awesome. Do you have a working version that we can see?

**Comment by ninja-** [comment]
> 1. Hubot needs a username and password and posts it on its behalf. Is this a right implementation? Slack provides you options to select a bot name, image etc. I dont think creating a user behind the scenes to achieve this is the right way, correct me if i am wrong.

what we want here is an option to choose bot name and image _per message_ so it will look like from a normal user but then add a tag like "BOT". this should be clearly inside the chatops package

**Comment by engelgabriel** [comment]
Creating a user behind the scenes is the right way. That's the perfect way to give bots their own access levels, usernames, avatar, etc. Bots are like other users, so they need a users. Would be a disaster otherwize. I agree that they deserve a badge to show that they are a special kind of user, but nevertheless users. On that note, creating a single "bot" badge is a waste of resources. We must make something generic, so admins can create many types of badges. Maybe moderators would like a badge too, as admin may also have a badge.

One of the big changes we did a while ago, was replace all arrays of strings for users lists for arrays of objects, so we could add some more details about each user. Now we have to finish that job (there are still some places with arrays of strings) and add this extra information when necessary.

**Comment by ninja-** [comment]
hm but isn't that designed already in slack api?

**Comment by engelgabriel** [comment]
You absolutely need a user. Trust me on this one. You want to be able to open a direct room with that bot, or invite a specific bot to a particular room.. so every bot (not every bot script, this is vey important) that has a different username will get its own user. There is no other way.

**Comment by xshadow** [comment]
+1
