### ISSUE TITLE
users.list endpoint returning no users at all

### ISSUE THREAD

**Issue by dotsomething** [RocketChat/Rocket.Chat#11760]
### Description:
 When sending a GET request to the mentioned endpoint it does not return any user at all. However I'm able to make requests to `im.list.everyone` without any issue.

### Steps to reproduce:

Make a GET request to the endpoint.

### Expected behavior:

Return the system's users.

### Actual behavior:

Returning empty object.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubuntu Server 18.04 Bionic
- Deployment Method: snap
- Number of Running Instances: 1 
- NodeJS Version: 8.11.3

### Relevant logs:

What the endpoint is actually returning me:
```json
{
    "users": [],
    "count": 0,
    "offset": 0,
    "total": 0,
    "success": true
}

**Comment by MarcosSpessatto** [comment]
Hello @dotsomething, I think this [PR](https://github.com/RocketChat/Rocket.Chat/pull/11657) should fix the problem. Please let me know what do you think.

**Comment by dotsomething** [comment]
Oh, thank you, @MarcosSpessatto ! It solved my problem. 
May I ask you a question? I'm using the `query={}` workaround however will I have to change my code when this PR goes to production?

**Comment by MarcosSpessatto** [comment]
@dotsomething it will not be necessary.

**Comment by dotsomething** [comment]
Problem solved. Thank you, @MarcosSpessatto !
