### ISSUE TITLE
Support for IndieAuth

### ISSUE THREAD

**Issue by petrk94** [RocketChat/Rocket.Chat#11765]
Hello RocketChat Team,

I have seen that IndieAuth is a alternative for OpenID, even URL based identity.
I would request this functionality.

https://indieauth.com

Thanks

**Comment by piotrkochan** [comment]
To be clear, IndieAuth name gonna be replaced with indielogin and indielogin is in beta.

**Comment by petrk94** [comment]
@piotrkochan,
honestly I got in contact with the guys from IndieWeb, and it doesnt seems to be a solution for such services to connect with it :/

**Comment by piotrkochan** [comment]
Topic to close then
