### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [RocketChat/Rocket.Chat#11773]
Hey there, KaTeX maintainer here. Not really an issue. I'd like to ask if Rocket.Chat would mind adding your logo to KaTeX user list? (https://github.com/Khan/KaTeX/pull/1569, preview availabe at https://deploy-preview-1569--katex.netlify.com/en/users.html) This is a really cool project! 😄

**Comment by MartinSchoeler** [comment]
<img width="914" alt="Screen Shot 2020-01-31 at 9 50 19 AM" src="https://user-images.githubusercontent.com/20868078/73540658-49b4b800-440f-11ea-874b-7dc57ab8d74a.png">
It was added! Closing this issue. Thanks!
