### ISSUE TITLE
When an incoming message is displayed username, not name

### ISSUE THREAD

**Issue by nicexe2e4** [RocketChat/Rocket.Chat#11776]
### Description:
Authentication via LDAP server
User Data Field Map { "cn":"name", "mail":"mail"}
Use Real Name True
Problem appeared after updating from 0.66.3 to 0.68.3
Update to 0.69.0 not fixed the problem
### Steps to reproduce:

1. Login via test acc and type direct message to real acc

![image](https://user-images.githubusercontent.com/23378404/44105902-4b5d2a76-a01d-11e8-8c49-2987eee4e22d.png)
2. Login via real acc and read direct message from test acc

![image](https://user-images.githubusercontent.com/23378404/44106096-dd611310-a01d-11e8-8f77-ecb44810dc84.png)

### Expected behavior:

To see real name in a direct messages, not username.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.4
- Operating System: 4.15.15
- Deployment Method: tar
- NodeJS Version: 8.11.2
- MongoDB Version: 3.6.3

**Comment by crazy-max** [comment]
Same issue for me on 0.68.4

**Comment by rsuguiura** [comment]
Same issue for me too. Using the Official Rocket.Chat docker deployment image.

**Comment by AlexDRiVER** [comment]
+1

**Comment by Gummikavalier** [comment]
Saw this too with 0.64.4 at least.

**Comment by zzeesstt** [comment]
+1

**Comment by zzeesstt** [comment]
snap: 0.69.0
+1

**Comment by dude75** [comment]
+1  i'm have same bug

**Comment by cadetmsv** [comment]
snap: 0.69.0
+1

**Comment by borg69** [comment]
+1 I confirm this bug

**Comment by crazy-max** [comment]
@borg69 @cadetmsv @dude75 @zzeesstt @AlexDRiVER 

If you find your issue already exists, please make **relevant comments** and add your [reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments). Use a reaction in place of a "+1" comment.

👍 - upvote

👎 - downvote

**Comment by Gummikavalier** [comment]
Milestone 0.70.0 in #11913 :)

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/12154
