### ISSUE TITLE
[BUG] Livechat: View history conversations

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#11777]
### Description:

I can't view history livechat rooms after update version 0.68.3

### Steps to reproduce:

1. Go to Livechat;
2. Click 'Current Chats';
3. Open livechat history;

![bug_1](https://user-images.githubusercontent.com/17053653/44107814-ef3277d6-9fce-11e8-9cb9-fec1afaccd70.png)

![bug_2](https://user-images.githubusercontent.com/17053653/44107819-f1dfa012-9fce-11e8-9936-16d8e4cec55e.png)

### Expected behavior:

I can view history livechat rooms.

### Actual behavior:

Show for me 'Room nor found'

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubuntu Linux x64 4.4.0-1062-aws
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.3
- MongoDB Version: Database Migration 130

### Relevant logs:

![log](https://user-images.githubusercontent.com/17053653/44107879-1abcb394-9fcf-11e8-9c61-d0f440e31496.png)

**Comment by MIKNOTAURO** [comment]
Same Issue... 

### Server Setup Information:
    Version of Rocket.Chat Server: 0.68.4
    Operating System: Ubuntu 18.04 LTS x64 | Bionic Beaver
    Deployment Method: Source Code
    Number of Running Instances: 1
    DB Replicaset Oplog: No    
    NodeJS Version: v8.11.3
    NPM Version: 5.6.0
    MongoDB Version: 4.0

**Comment by renatobecker** [comment]
@guilhermecfviana,

Just a question: Is the user that participated in the chat (as agent) the same user who is trying to view the history conversations?

**Comment by guilhermecfviana** [comment]
@renatobecker No. They are differents users.

**Comment by renatobecker** [comment]
@guilhermecfviana, thanks.
I'll take a look at this case.
