### ISSUE TITLE
CSS styles not working properly with search field

### ISSUE THREAD

**Issue by przemika** [RocketChat/Rocket.Chat#11771]
### Description:

CSS styles not working properly with search field,
after updates (i don’t remember witch version) my search field looks like at picture (after click search icon)
It’s occurs on web and windows client

### Steps to reproduce:

1. click to search icon 
2. after click to cancel search it looks fine.

### Actual behavior:

![image](https://user-images.githubusercontent.com/18058558/44082935-fbbaa8be-9fb2-11e8-8d57-91a91e4c6bbb.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Centos 7.4
- Deployment Method: tar
- Number of Running Instances: 1 
- NodeJS Version: v8.9.4
- MongoDB Version: 2.6.12-1

**Comment by kaiiiiiiiii** [comment]
Hi @przemika,

please read the following issue to resolve your problem #10510 :)

Thanks

**Comment by przemika** [comment]
finally I solve my problem by reset "layout->colors" to default.
