### ISSUE TITLE
Finnish translation for turn on notifications is incorrect 

### ISSUE THREAD

**Issue by JohannesLyytikka** [RocketChat/Rocket.Chat#11770]
In the finnish RocketChat translation the option to turn on notifications reads "kiihottua", which means to be aroused. The translation for turn off, could also be better. 

<img width="359" alt="nayttokuva 2018-8-14 kello 12 30 00" src="https://user-images.githubusercontent.com/31692452/44084067-6bbddeb4-9fbe-11e8-8755-6b6f7f044a4a.png">

Correct translations would be "Turn on" -> "Päällä" and "Turn off" -> "Pois päältä"

This gives me a laugh every time I use it, but maybe it's better to fix this anyway :)

**Comment by kaiiiiiiiii** [comment]
@tsukiRep Most of the translations are auto-translated. That's why you see such misleading translations :)

**Comment by MartinSchoeler** [comment]
@kaiiiiiiiii actually most of our translations comes from a group of contributors on lingohub, and not auto translations.

**Comment by sampaiodiego** [comment]
they are not auto translated by lingohub anymore.. we turned that off about two weeks ago

**Comment by MartinSchoeler** [comment]
This was fixed a while ago, closing this issue
