### ISSUE TITLE
Criação do canal 

### ISSUE THREAD

**Issue by Wilhiamjr** [RocketChat/Rocket.Chat#11786]
Ao criar um canal (Grupo) quando for digitar o nome do canal não se pode ter letra maiúscula ou dar espaço ou escrever caracteres especiais.

A alternativa que faço é criar um canal com o nome qualquer e depois editar ele e escrever o Nome

Solução desejável : Habilitar para poder escrever carácteres especiais e letras maiúsculas e minusculas logo quando for criar.

**Comment by Hudell** [comment]
Administração -> Layout -> Interface de Usuário -> Permitir caracteres especiais em nomes de salas
