### ISSUE TITLE
Download Button for Each File in Files List

### ISSUE THREAD

**Issue by roygold7** [RocketChat/Rocket.Chat#11792]
We can easily view a list of all the files sent in a chat but there is no option to download the file from the list or the option to jump to the message where the file was sent (like mentions).

I imagine a solution would be to a have a menu button with a drop down list with two actions:
1. Download file
2. Jump to message

Much like the option button in the mentions list.

We could also just have the two options side by side instead of in a drop down list but that would be less consistent with other similar features in the chat.

Mentions list:
![image](https://user-images.githubusercontent.com/40822827/44205974-e07cae80-a160-11e8-9ac4-c684a4e0b53f.png)

Files list:
![image](https://user-images.githubusercontent.com/40822827/44205980-e7a3bc80-a160-11e8-9709-c1d5d317db32.png)

**Comment by tonskie** [comment]
Can you also add a delete button in every files ?

**Comment by alexbartsch** [comment]
@tassoevan I also started to work on this issue. Not sure if it's still in progress, so maybe someone could give an update. I also was wondering if there is another issue for "Jump to Message" and "Delete file" requests or do we handle these within this issue?

**Comment by tassoevan** [comment]
@alexbartsch Thanks! I'll check if there are similar issues.
