### ISSUE TITLE
Embedded content disappear when message is edited

### ISSUE THREAD

**Issue by gmsecrieru** [RocketChat/Rocket.Chat#1179]
![edit-link](https://cloud.githubusercontent.com/assets/190883/10611367/8cd2539c-772a-11e5-9099-bc74f9efaba2.gif)

**Comment by kakawait** [comment]
@gmsecrieru do you know if it's regression?

**Comment by gmsecrieru** [comment]
Besides a minor bug on the URL mapping, looks like it was (un)intentionally omitted on [24f2463](https://github.com/RocketChat/Rocket.Chat/commit/24f24633a3af8fc44bff22ee6b2e7c2ee48d2cf6#diff-6dfeaedea78dd5c254f4eaa04c22d0a4L21) -- @sampaiodiego can you confirm?

Proposed fix on #1188

**Comment by sampaiodiego** [comment]
Oh, I think I forgot to fix that later that commit. Shame on me =)
