### ISSUE TITLE
[BUG] Reply with attachments does not work

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat#11799]
### Description:
Reply to any message, attach an image or any other file and hit send.
The message with the attachment is sent as a normal message, not as a reply.

- Version of Rocket.Chat Server: 0.68.3

**Comment by ggazzo** [comment]
hey @lorek123 could you try again on last the last version? I couldn't reproduce your problem =/ 
![image](https://user-images.githubusercontent.com/5263975/45337062-a1256000-b55c-11e8-889e-42025c442817.png)
