### ISSUE TITLE
Bright red taskbar icons are overly intrusive (Windows v2.12.0/v2.12.1)

### ISSUE THREAD

**Issue by jkshapiro** [RocketChat/Rocket.Chat#11801]
Messaging apps have three major states they can be in, in normal operation:
* no new messages exist (user is entirely up to date; usually doesn't last long)
* new messages exist, but they are not specific to the user
* new messages exist that are specific to the user (e.g. DMs, @-mentions, thread replies)

Users should be made aware when the app is in the third state, since that suggests that someone is trying to get their attention. The second state, on the other hand, just means that other people are posting. It's not urgent.

In the versions prior to 2.12, the Windows client used to have a Slack-style muted taskbar icon. It was a bit quirky in its behaviour but at least it stayed generally unobtrusive in the first two states. However, as of 2.12.0, the taskbar icon is BRIGHT RED and impossible to ignore.

Version 2.12.1 is even worse. The icon in the notification area is the same as in 2.12.0, but the icon in the taskbar proper now contains a BRIGHT RED badge indicating the number of unread user-specific messages--even when the number is zero!

Having a badge is fine when there are unread user-specific messages. But it shouldn't be there when there aren't. And the taskbar icons should be much more subtle, especially the one in the notification area.

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #823](https://github.com/RocketChat/Rocket.Chat.Electron/issues/823) via [**ZenHub**](https://www.zenhub.com/)
