### ISSUE TITLE
Cannot add reaction to message in read only room

### ISSUE THREAD

**Issue by TheSharpieOne** [RocketChat/Rocket.Chat#11819]
### Description:

When in a read only channel with reacting enabled users should be able to react to messages when if they are not able to create messages.

This appears to be some regression.
Original issue: #8632 
Original PR: #8925

### Steps to reproduce:

1. Make a room "Read Only"
2. Enable "Allow Reacting"
3. Attempt to react to a message

### Expected behavior:

You should be able to react.

### Actual behavior:

Reaction option is no present.
Attempting to "+1" an existing reaction results in "You have been muted and cannot speak in this room"

![image](https://user-images.githubusercontent.com/664714/44270974-ea58ed00-a206-11e8-8948-285e3dba2adf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Linux 3.10.0-862.9.1.el7.x86_64
- Deployment Method: tar
- Number of Running Instances: 6
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: (not listed in the Administration Info page... maybe it should be)

### Additional context

We have an annocements channel which only 1 person can post messages. We made the channel read only but would like for other to be able to add reactions to the messages.

**Comment by graywolf336** [comment]
There used to be a UI setting which allowed enabling reacting when room was read only, seems we have lost it in the new UI. @ggazzo

**Comment by si90** [comment]
set the item to "disallow reacting" (like shown below), the settings are switched - it does exactly the opposite - really confusing

**Comment by ukhryab** [comment]
> It seems like the labels of "allow reacting and "disallow reacting" are switched

True. And even not need to set channel to _"Collaborative"_ and back to _"RO"_.

**Comment by ukhryab** [comment]
Also, there's no chance to set reactions in Broadcast channel, cause it has no _"Allow reacting_" switch at all, and can not be converted to _Collaborative_ channel. 

In my case users have a permission to set reactions in read-only channel, and they can do it, but can not set reactions in broadcast channel at the same time.
