### ISSUE TITLE
Could not upload Auto Cad drawing file on rocket

### ISSUE THREAD

**Issue by phongb2b** [RocketChat/Rocket.Chat#11828]
### Steps to reproduce:

1. Allow unlimit upload file type by clear the Comma-seperate list of media type then restart RocketChat server
2. On a direct message , click on ' +'  icon and select upload a Auto Cad drawing file  xxx.dwg from local computer
3. File upload and complete but not show the download icon 
4. Check it on the 'Files List' we could see the file xxxx.dwg but it grey out and could not download 
### Expected behavior:

The download link should show with a download icon, and show 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Ubuntu 18.04 - OS release  4.4.0-130-generic
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Relevant logs:

[34mI20180820-06:34:12.424(0) Exception while invoking method 'sendFileMessage' Error: Input buffer contains unsupported image format    => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (/snap/rocketchat-server/1317/programs/server/packages/rocketchat_file-upload.js:1745:49)     at /snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  
[34mI20180820-06:40:05.268(0) Exception while invoking method 'sendFileMessage' Error: Input buffer contains unsupported image format    => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (/snap/rocketchat-server/1317/programs/server/packages/rocketchat_file-upload.js:1745:49)     at /snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  
[34mI20180820-06:42:39.032(0) Exception while invoking method 'sendFileMessage' Error: Input buffer contains unsupported image format    => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (/snap/rocketchat-server/1317/programs/server/packages/rocketchat_file-upload.js:1745:49)     at /snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  
[34mI20180820-07:21:42.679(0) Exception while invoking method 'sendFileMessage' Error: Input buffer contains unsupported image format    => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (/snap/rocketchat-server/1317/programs/server/packages/rocketchat_file-upload.js:1745:49)     at /snap/rocketchat-server/1317/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  https://rocket.chat/docs/contributing/reporting-issues#gathering-logs -->

**Comment by madguy02** [comment]
@sampaiodiego  are there plans to support this file format?

**Comment by madguy02** [comment]
@phongb2b you can probably zip or tar the file and then upload... that should work

**Comment by sampaiodiego** [comment]
definitely. the error seems it's trying to process it like an image, the fix might be treating is as a regular file

**Comment by phongb2b** [comment]
@madguy02 yes, it works with zip/rar but our user would like drag and drop CAD file to share.

**Comment by madguy02** [comment]
For the first part regarding autoCAD .dwg support, I will try to submit a PR ASAP.

For the second part of your query, you mean the .bak file are auto converted to .bak.bin?? after download?

**Comment by phongb2b** [comment]
@madguy02 after we upload SQL xxx.bak file, it auto change to xxx.bak.bin after we completed upload file. We do a hash check that file (after downloaded and change back to xxx.bak) , it is OK.

**Comment by madguy02** [comment]
Ok, shall look at it once...

**Comment by phongb2b** [comment]
Thank your effort
