### ISSUE TITLE
[BUG] Double push notifications on mention + subscription

### ISSUE THREAD

**Issue by Sameesunkaria** [RocketChat/Rocket.Chat#11825]
### Description:

Two push notifications are sent when all the notifications are enabled on that channel and the user is @ mentioned in a message.

### Steps to reproduce:

1. Make sure all notification are enabled for a particular channel.
2. Make sure you will receive push notifications (close all desktop session, and the mobile app)
3. On that channel make someone send a message with you @ mentioned in it.
4. You receive multiple notifications for the same message.

### Expected behavior:

You should only receive one notification.

### Actual behavior:

You receive two notifications

<img src="https://user-images.githubusercontent.com/7317008/44297888-beb53000-a2f6-11e8-883f-1f326740ed40.PNG" width=250>

### Server Setup Information:

- Version of Rocket.Chat Server: `0.69.0-develop` on `open.rocket.chat`

Original issue raised by @soundstorm, RocketChat/Rocket.Chat.iOS#2120

**Comment by cpitman** [comment]
Came to file this. I have users getting anywhere between 0 and 4 push notifications when they get a message. I personally get 4, which means my phone rapidly plays the notification sound four times in succession.

**Comment by geekgonecrazy** [comment]
Does this still happen with new releases?  I know we worked over the notifications a good bit.  

Some how personally have never encountered this and I have a lot of channels set to notify me on all messages.  🤔

**Comment by soundstorm** [comment]
Seems to be resolved 😇

**Comment by geekgonecrazy** [comment]
If anyone experiences please let me know 👍

**Comment by sergeydeg** [comment]
@geekgonecrazy 
Still getting this double notifications:
Server 0.73.2
Android Client 3.2.0
Phone: Xiaomi Redmi Note 4 - Android 7.0

**Comment by geekgonecrazy** [comment]
Do you have more than one rocket.chat app installed?  For instance the react native one?

If so uninstall one.

If not uninstall app.  Trigger a notification and see if you still get one.  If not then reinstall the app.
