### ISSUE TITLE
push notofication not sending

### ISSUE THREAD

**Issue by asadi110** [RocketChat/Rocket.Chat#11824]
### Description:

hello
I'm set GCM API Key and GCM Project Number in server/admin/Push but no push send.
by pressing "Send a test push to my user" success message show but no push send.
also no error show in server log. 
in postman notifications are send by  GCM API Key and GCM Project Number and recive in my comiled rocket app.
** for GCM API Key i test these : server key(new and old), gcm api key

### Steps to reproduce:

1. set GCM info in server
2. replace my google-services.json in android project and compile
2. Click to send test notification
3.success message show
4. no notification send

### Expected behavior:

send notification or show error
### Actual behavior:

show success message and no notification send

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: ubuntu 16.0.4
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabeld
- NodeJS Version: 8.11.3
- MongoDB Version: 3.2.7

### Relevant logs:

 rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method push_test -> userId: TpguiQZ5gPMyTpXGi , arguments:  {} 

![p1](https://user-images.githubusercontent.com/11172751/44297850-df2cbc80-a2ed-11e8-9ac2-cddfc8f1c07f.JPG)
![p2](https://user-images.githubusercontent.com/11172751/44297851-df2cbc80-a2ed-11e8-8fc3-ebb6fedf762f.JPG)

**Comment by geekgonecrazy** [comment]
if you are using our apps from the app store, you have to use the gateway.  If you have your own apps then i'd take a look through the forums and the issues here.  

Restarting server after you make the changes is most common solution (if you have compiled your own apps)
