### ISSUE TITLE
hardware requirement

### ISSUE THREAD

**Issue by asadi110** [RocketChat/Rocket.Chat#11827]
hello
what hardware config needed for 200-300 k users and 10 k concurrent user.
ram?cpu?storage?

**Comment by kaiiiiiiiii** [comment]
Please see the [forums](https://forums.rocket.chat) for this kind of questions. The GitHub issue tracker is -as the name says- for issues (code related) and definitely the wrong place.


Thanks

//CC: @TwizzyDizzy
