### ISSUE TITLE
Realtime API Login issue with username/password

### ISSUE THREAD

**Issue by Filini** [RocketChat/Rocket.Chat#11833]
Hi,

I am trying to login into RC Realtime API, but I am getting a "User Not Found [403]" response.

This is my message:

```
{
     "msg": "method",
     "method": "login",
     "id": "42",
     "params": [
          {
               "user": { "username": "{{ my username }}" },
               "password": {
                    "digest": "{{ the hash of my password }}",
                    "algorithm": "sha-256"
               }
          }
     ]
}
```

After that, I get 2 messages from the RC server:

`{"msg":"updated","methods":["42"]}`

`{"msg":"result","id":"42","error":{"isClientSafe":true,"error":403,"reason":"User not found","message":"User not found [403]","errorType":"Meteor.Error"}}
`

I can login in the RC web, with that user, so I guess I'm sending the wrong message, but I got the sample straight from the Realtime API login documentation.

RC Version: 0.67.0

**Comment by ggazzo** [comment]
Hey @Filini please try login without hash your password, I think the problem is the hash you generated and not your username (both error results `user not found`)
```javascript 
{
	"msg":"method",
	"method":"login",
	"params":[
		{
		"user":{"username":"username"},
		"password":"xxxx"}
	],
	"id":"16"
}

**Comment by Filini** [comment]
Actually, there was a connection issue between RC and some database. Restarting the server and the DB solved the issue.
The error message was misleading though...

**Comment by Filini** [comment]
Yes, logging without the hash solved the issue.

Thanks for the support

**Comment by tai-pd** [comment]
I have rocketchat : https://chat.mydomian 
and my webApp :https://app.mydomain
i embed rocketchat by iframe into webApp
and i wanna login in my webApp -> rocketchat auto login 
I try to follow this code 
function on_load(iframe){
    document.getElementById('rocketchat').contentWindow.postMessage({
        event: 'login-with-token',
        loginToken: 'myToken'
    }, 'https://chat.mydomain');
}
but it didn't work, have error like that : Blocked autofocusing on a form control in a cross-origin subframe.
Somebody help me ?

**Comment by ram4git** [comment]
> I have rocketchat : https://chat.mydomian
> and my webApp :https://app.mydomain
> i embed rocketchat by iframe into webApp
> and i wanna login in my webApp -> rocketchat auto login
> I try to follow this code
> function on_load(iframe){
> document.getElementById('rocketchat').contentWindow.postMessage({
> event: 'login-with-token',
> loginToken: 'myToken'
> }, 'https://chat.mydomain');
> }
> but it didn't work, have error like that : Blocked autofocusing on a form control in a cross-origin subframe.
> Somebody help me ?

did you figure it out?

**Comment by mgrybyk** [comment]
Here is how to login with digest
```
const crypto_1 = require('crypto')
const uuid_1 = require('uuid')
const WebSocket = require('ws')

const ws = new WebSocket(`wss://YOUR_SERVER_URL`)
ws.on('close', console.log)
ws.on('error', console.error)

ws.on('open', function open() {
  ws.send(
    JSON.stringify({
      msg: 'connect',
      version: '1',
      support: ['1', 'pre2', 'pre1'],
    })
  )
})

ws.on('message', function incoming(data) {
  const message = JSON.parse(data.toString())
  console.log(message)

  if (message.msg === 'connected') {
    const id = uuid_1.v4()
    const loginPayload = buildLoginPayload(id, 'YOUR_USERNAME', 'YOUR_PASSWORD')
    ws.send(JSON.stringify(loginPayload))
  }
})

const buildLoginPayload = (id, username, password) => {
  const digest = crypto_1.createHash('sha256').update(password).digest('hex').toString()
  return {
    msg: 'method',
    method: 'login',
    id,
    params: [
      {
        user: { username },
        password: {
          digest,
          algorithm: 'sha-256',
        },
      },
    ],
  }
}
```
