### ISSUE TITLE
Exception while invoking method 'getRoomByTypeAndName' TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by ncedomir** [RocketChat/Rocket.Chat#11832]
OS:Centos 7.5.1804 64bit
Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit) and any other, even the Rocket Chat app for Windows
Rocket.Chat version: 0.68.4

Livechat Admin cannot enter any livechat rooms except the ones owned by him.  This is the error I get:

Aug 20 11:24:29 chat rocketchat: Invalid streamRoom eventName: "kn9uYd8bF5tnfKDSk/typing"
Aug 20 11:24:36 chat rocketchat: Exception while invoking method 'getRoomByTypeAndName' TypeError: Cannot read property '_id' of undefined
Aug 20 11:24:36 chat rocketchat: at MethodInvocation.getRoomByTypeAndName (/opt/Rocket.Chat/programs/server/app/app.js:12271:44)
Aug 20 11:24:36 chat rocketchat: at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Aug 20 11:24:36 chat rocketchat: at MethodInvocation.methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2506:36)
Aug 20 11:24:36 chat rocketchat: at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)
Aug 20 11:24:36 chat rocketchat: at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)
Aug 20 11:24:36 chat rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
Aug 20 11:24:36 chat rocketchat: at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)
Aug 20 11:24:36 chat rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
Aug 20 11:24:36 chat rocketchat: at Promise (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)
Aug 20 11:24:36 chat rocketchat: at new Promise (<anonymous>:null:null)
Aug 20 11:24:36 chat rocketchat: at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)
Aug 20 11:24:36 chat rocketchat: at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85

This doesn't look ok, can you replicate this behaviour. This started happening after I did an upgrade to latest version 0.68.4 .

Please advise

**Comment by renatobecker** [comment]
This issue has been fixed by #11830.
Thanks.
