### ISSUE TITLE
Direct messages leaking into logs

### ISSUE THREAD

**Issue by luckenbach** [RocketChat/Rocket.Chat#11848]
### Description:

Periodically while reviewing logs it is noticed that a direct message (JSON) is emitted into the logs with no context

### Steps to reproduce:

1. Unable to force the reproduction

### Expected behavior:

These events not be in the log or at least provide context around their existance

### Actual behavior:

Messages like this appears in the logs
```
{ room:
   { _id: 'foReyT6k7LFsNEoudtSzjrzGEqXaryRb5Y',
     usernames: [ 'user1', 'user2' ],
     _updatedAt: 2018-08-22T21:56:42.402Z,
     t: 'd',
     msgs: 43,
     ts: 2018-07-02T20:06:19.408Z,
     lm: 2018-08-22T21:56:42.325Z,
     lastMessage:
      { rid: 'foReyT6k7LFsNEoudtSzjrzGEqXaryRb5Y',
        _id: 'P4FjcHPaeCDihKuTdD',
        msg: 'You mentioned you were going to exclude it',
        ts: 2018-08-22T21:56:42.325Z,
        u: [Object],
        _updatedAt: 2018-08-22T21:56:42.373Z,
        editedBy: null,
        editedAt: null,
        emoji: null,
        avatar: null,
        alias: null,
        customFields: null,
        attachments: null,
        mentions: [],
        channels: [],
        sandstormSessionId: null },
     usersCount: 2 },
  subscription:
   { _id: 'a5wN4jYguYGqJurSe',
     rid: 'foReyT6k7LFsNEoudtSzjrzGEqXaryRb5Y',
     u: { _id: 'foReyT6k7LFsNEoud', username: 'user2' },
     name: 'user1',
     t: 'd',
     open: true,
     alert: true,
     unread: 2,
     userMentions: 0,
     groupMentions: 0,
     customFields: null,
     _updatedAt: 2018-08-22T21:56:42.393Z,
     ls: 2018-08-22T20:42:34.594Z,
     fname: 'User One' } }
```

### Server Setup Information:

- Version of Rocket.Chat Server:  0.68.4
- Operating System: ubuntu
- Deployment Method: docker / k8s
- Number of Running Instances: 
- DB Replicaset Oplog:  disabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.7

**Comment by piotrkochan** [comment]
maybe https://github.com/RocketChat/Rocket.Chat/blob/39aed632d3d60191d7eaa54ecd844d14dc7cd9eb/packages/rocketchat-api/server/v1/im.js#L212 ?

**Comment by luckenbach** [comment]
What release will this fix be? Rocket.Chat Version: 0.69.2  is still leaking

**Comment by kaiiiiiiiii** [comment]
@luckenbach Release 0.70.0 will include this fix.
