### ISSUE TITLE
cant load odt file

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat#11850]
any odt file got an error
http://i.imgur.com/GPnRgjC.png

**Comment by bbrauns** [comment]
no bug, have a look at: administration - settings - file upload - accepted media types

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
