### ISSUE TITLE
Provide instructions on how to use different emoji

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1185]
I noticed in commit cb6e85adc46d3c4eca7329f1320e62f9fe31bbf4 that its possible to add another emoji package other than the default one. Can you provide instructions on how to do so?

**Comment by gmsecrieru** [comment]
Based on [this comments](https://github.com/RocketChat/Rocket.Chat/blob/cb6e85adc46d3c4eca7329f1320e62f9fe31bbf4/packages/rocketchat-emojione/rocketchat.coffee) I think you just need to create your own package following this same convention and replace `rocketchat:emojione` on `.meteor/packages`. But @marceloschmidt knows best :D

**Comment by marceloschmidt** [comment]
It should be possible, but hasn't been done yet.
The package would have to have a list of emojis as in ```
{ 
: 8ball:: [ { 0: "1f3b1" } ]
: 100:: Array[1]
: 1234:: Array[1]
: +1:: Array[1]
} (spaces were added to avoid interpreting emojis here)
```

Other than that, it should have it's own method for translating the unicodes into emojis, just like it is done in https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-emojione/emojione.coffee#L9
