### ISSUE TITLE
stream-notify-user/message event does not function.

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#11858]
Hello,

I have been playing around with the Realtime-API and it has come to my attention that the messge event for the subscription stream-notify-user is non-functional.

I have subscribed successfully too the stream. However, when sending or receiving messages in any channel the event is not raised.

I am unsure if this is the actual purpose of this event due to the lack of documentation on the Realtime-API. If this is not the purpose of this event, please let me know what actually triggers this event.

My main goal here is too subscribe to the message event so that I receive all messages coming too my bot. I am aware of the stream-room-messages however I do not wish to subscribe to every channel separately.

I have left the request payload below as well as the successful response notifying me that my subscription was successful. Please let me know if you need anything else to help you further investigate this issue, thank you.

REQUEST PAYLOAD

{
  "id": "6bbfbc70-8228-434f-b7e4-61059be1ef79",
  "msg": "sub",
  "name": "stream-notify-user",
  "params": [
    "5yFsjPET78KzzSL2J/message",
    false
  ]
}

RESPONSE

{
  "msg": "ready",
  "subs": [
    "6bbfbc70-8228-434f-b7e4-61059be1ef79"
  ]
}

**Comment by geekgonecrazy** [comment]
Closing in favor of #13904
