### ISSUE TITLE
[ENHANCEMENT] Add button to copy the whole message without the need to select it

### ISSUE THREAD

**Issue by jacekmusial** [RocketChat/Rocket.Chat#11851]
**Is your feature request related to a problem? Please describe.**
I believe we could speed up the process of copying the whole message.

**Describe the solution you'd like**
I would like to click on the button named "Copy" and have the whole message in a clipboard, without selecting it.

**Additional context**
In new Electron-based Skype, I can get the whole message by clicking the button named "Copy". There is no need for me to select the whole message. Obviously, if you want to get just part of the message, you have to select it first. But that's not the case.
![image](https://user-images.githubusercontent.com/7474972/44523472-470e4900-a6da-11e8-996f-0d08103cd11a.png)

**Comment by sampaiodiego** [comment]
we have that already on message actions you can access by the three dots when you hover over a message:
![image](https://user-images.githubusercontent.com/8591547/44546955-e5f17000-a6ef-11e8-9bfc-8a8e08e3db43.png)
