### ISSUE TITLE
0.62-0.68.5 Cannot get Rocketchat to start

### ISSUE THREAD

**Issue by rsliotta** [RocketChat/Rocket.Chat#11862]
### Description:

I have tried numerous tests and options to get it to start.  Fresh installs, upgrades, etc.  0.61 works fine.

Each version has the same symptom:  It starts, stops at tmpfs sits there for 1-3 minutes and finally restarts.  It seems to silently die.

### Steps to reproduce:

1. Install Docker and Docker image above .061

### Expected behavior:

I expect it to start as 0.61 did

### Actual behavior:

Keeps crashing/restart

### Server Setup Information:

- Version of Rocket.Chat Server: 0.62-0.68.5
- Operating System: Kubernetes 1.9.5 / Ubuntu 16.04
- Deployment Method: helm inatall
- Number of Running Instances: 1
- DB Replicaset Oplog:  YES
- NodeJS Version: 8.11.2
- MongoDB Version: 3.6.5-3.6.6

### Additional context

We are running on top of gluster for the persistent storage.  I verified the storage is working properly
I set DEBUG=*

### Relevant logs:

[snippet.txt](https://github.com/RocketChat/Rocket.Chat/files/2319571/snippet.txt)

Some more detail.

On 0.61.2 The logs continue as such:

Mon, 27 Aug 2018 11:50:37 GMT express:router:layer new /
Mon, 27 Aug 2018 11:50:38 GMT connect:dispatcher use /_timesync anonymous
Mon, 27 Aug 2018 11:50:38 GMT connect:dispatcher use / bodyParser
Mon, 27 Aug 2018 11:50:38 GMT connect:dispatcher use / anonymous
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Mon, 27 Aug 2018 11:50:39 GMT connect:dispatcher use /custom-sounds anonymous
Using GridFS for custom emoji storage
Mon, 27 Aug 2018 11:50:39 GMT connect:dispatcher use /emoji-custom anonymous
ufs: temp directory created at "/tmp/ufs"
Mon, 27 Aug 2018 11:50:40 GMT connect:dispatcher use /avatar anonymous
➔ System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |  Rocket.Chat Version: 0.61.2                 |
➔ |       NodeJS Version: 8.9.4 - x64            |
➔ |             Platform: linux                  |
➔ |         Process Port: 3000                   |
➔ |             Site URL: http://localhost:3000  |
➔ |     ReplicaSet OpLog: Enabled                |
➔ |          Commit Hash: cff389edeb             |
➔ |        Commit Branch: HEAD                   |
➔ |                                              |
➔ +----------------------------------------------+

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
