### ISSUE TITLE
Can't load search results in Microsoft Edge

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#11869]
RC Version: 0.68.5

To reproduce:
Open any room in Edge
Search for term which has alot of results
After initial results load, you can't scroll down to load more results .

**Comment by tsukiRep** [comment]
use a normal browser

**Comment by danieljhochman** [comment]
Thanks for your really helpful input. We have thousands of users on RocketChat and many still use IE or Edge unfortunately. In case you don't know IE/Edge still has around ~8% market share which isn't insignificant (millions of people). I don't personally use it, but not everyone in the world is technically savvy.

**Comment by barak-haviv** [comment]
Hey danieljhochman 
Can you share please which version you are using that works well with Microsoft Edge.
The current one v0.72.3 is not working.
I.e messages are not delivered

**Comment by MartinSchoeler** [comment]
@danieljhochman @barak-haviv Have you had these issues on the latest versions? I could not reproduce this problem, also do you know what version of Edge this happens? Thanks!

**Comment by danieljhochman** [comment]
I'm not following this project anymore. Sorry.

**Comment by MartinSchoeler** [comment]
I'm sorry to hear that 🙁. If anyone experience this issue again, please open a new issue with updated details. Thanks!
