### ISSUE TITLE
FR: Custom port in Snap

### ISSUE THREAD

**Issue by gerroon** [RocketChat/Rocket.Chat#11865]
Hi

It would be nice if one can change the default port with Snap install. I am already using port 3000 for something else therefor I need RC to run on another port, rever proxying etc would not work for me 

thanks

**Comment by mbaev** [comment]
This question has been raised many times, but as far as I know the problem is not solved.

**Comment by reetp** [comment]
This is a support/configuration issue rather than bug.

Please follow up in the forums https://forums.rocket.chat/ or https://open.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
