### ISSUE TITLE
Ability to hide embed media

### ISSUE THREAD

**Issue by kakawait** [RocketChat/Rocket.Chat#1187]
Embed media can catch our attention or pollute chat.

Could be cool to have a way to hide media like in Slack

![screen shot 2015-10-21 at 14 55 30](https://cloud.githubusercontent.com/assets/275609/10637092/d47bd6d0-7803-11e5-95ab-50d83b758eb0.png)

![screen shot 2015-10-21 at 14 55 37](https://cloud.githubusercontent.com/assets/275609/10637095/d828c31a-7803-11e5-8dfa-58e8376dab8a.png)

**Comment by gmsecrieru** [comment]
:+1:

**Comment by miscs** [comment]
please see also https://github.com/RocketChat/Rocket.Chat/issues/1664

**Comment by lvh1** [comment]
Also related to #1775 I think

**Comment by Lochemage** [comment]
+1 on this, I have a few requests from my co-workers for this feature.

**Comment by bisaacson** [comment]
+1, I hate not being able to hide media.

**Comment by brakhane** [comment]
I actually started on this one a few weeks ago but forgot to finish it. I'll see if I can finish it.
