### ISSUE TITLE
Rich message text and image buttons not work

### ISSUE THREAD

**Issue by oinadmin** [RocketChat/Rocket.Chat#11885]
```
{
  "attachments": [
    {
      "title": "text button with url",
      "actions": [
        {
          "type": "button",
          "text": "Book flights",
          "url": "http://www.kayak.com",
          "is_webview": false
        }
      ]
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/39171599/44713725-6a5f3c80-aabc-11e8-935f-43b382a46051.png)

[#11473](https://github.com/RocketChat/Rocket.Chat/pull/11473)

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information. Please reopen this with updated information. Thanks!
