### ISSUE TITLE
MacOS version 2.13.0 is available!

### ISSUE THREAD

**Issue by coreyfeder** [RocketChat/Rocket.Chat#11880]
Or so the application claims; but clicking Install Update just closes the app. And the latest version listed on the site's Desktop Clients section is 2.12.1. What's up?

**Comment by MartinSchoeler** [comment]
This issue is related to the desktop client, please reopen this in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #844](https://github.com/RocketChat/Rocket.Chat.Electron/issues/844) via [**ZenHub**](https://www.zenhub.com/)
