### ISSUE TITLE
Update_user no está permitido

### ISSUE THREAD

**Issue by peroda** [RocketChat/Rocket.Chat#11886]
### Description:

Unable to update user's properties in version 0.69

### Steps to reproduce:

1. Go to 'admin/users' 
2. Click on 'save button'
3. Update_user no está permitido

### Expected behavior:

Save user

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69
- Operating System: Centos 7.4
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by kaiiiiiiiii** [comment]
As @peroda said, it's a duplicate of #11884.

// CC: @TwizzyDizzy

**Comment by zzeesstt** [comment]
A similar problem. I confirm!

**Comment by JEREYMNO** [comment]
SAME PROBLEM!!! URGENT
