### ISSUE TITLE
App exits immediately in Win 10

### ISSUE THREAD

**Issue by michaelveloz** [RocketChat/Rocket.Chat#11889]
### Steps to reproduce:

1.  Double click icon to launch

### Expected behavior:

I expected to start the app and have it stay running :) 

### Actual behavior:
App exits immediately upon starting it. In previous versions (before 2.13.) I always had to start the app twice to get it to stay running. But now with the newest release, it won't ever stay running. Is there a log file or something I could check to see why it's exiting?

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by MartinSchoeler** [comment]
Please reopen this at the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron) . Thanks!
