### ISSUE TITLE
Executable name changed on Mac

### ISSUE THREAD

**Issue by jelockwood** [RocketChat/Rocket.Chat#11888]
### Description:

All prior versions of the Mac Rocket.Chat executable I have seen have used the name "Rocket.Chat+.app". The latest 2.13.0 version however uses the name "Rocket.Chat.app". This in itself does not prevent installing and running the new 2.13.0 app but if you use an automated enterprise system for distributing the new versions e.g. [Munki](https://www.munki.org/munki/) then it merely copies the new app to the /Applications folder. This results in two copies being in the /Applications folder as follows.

/Applications/Rocket.Chat.app
/Applications/Rocket.Chat+.app

It also makes it likely that the user will run the older _still present_ version and get an unexpected nag message saying an update is available even though the new version has been 'installed'.

This issue is possible to workaround using [Munki](https://www.munki.org/munki/) but I cannot say if other Mac enterprise software update tools would be able to do a similar solution. For [Munki](https://www.munki.org/munki/) you can define a 'pre-install' script, this shell script would remove /Applications/Rocket.Chat+.app before installing the new version.

Munki would then do the normal 'install' process which in this case is to copy the app from the mounted disk image in to the /Applications folder, in this case this will result in /Applications/Rocket.Chat.app Munki then registers the matching application receipt.

### Steps to reproduce:

1. Setup Munki to distribute Rocket Chat client for Macs with say Rocket.Chat+.app version 2.12.1 or earlier
2. Add the new Rocket.Chat 2.13.0 for Mac machines with an older version Munki will see this as an update (it does this by looking at the 'receipts' on the client Mac
3. The Munki client on Macs will pull down the Rocket.Chat updated version and 'install' it by copying the application from the mounted disk image

### Expected behavior:

I expected the old version to be replaced i.e. overwritten by the new version.

### Actual behavior:

Because the names of the applications for the two versions differ, due to the way Munki and presumably similar enterprise tools work it merely copied the new app unaltered to the /Applications folder. Since the name is different this did not result in the usual behaviour of _overwriting_ the older version but instead resulted in two separate copies - the old and the new.

### Server Setup Information:

N/A

### Additional context

Updating is being performed using the Mac enterprise tool of Munki and not by the Rocket.Chat app itself. The major benefit of using Munki instead is that users do not need admin privileges to install software and updates as the Munki software automates this process. It also gives Mac enterprise administrators more control over distributing and updating software.

PS. If the change of name is intended then feel free to leave it with the new name. If the name change was accidental then please let us know because in that case I can add a 'post install' script as a workaround to rename it to the Rocket.Chat+.app name.

**Comment by MartinSchoeler** [comment]
Hello there @jelockwood I believe this issue belongs to the desktop app repository, please reopen this issue [there](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
