### ISSUE TITLE
User not logged in when embedding rocketchat on iframe

### ISSUE THREAD

**Issue by dave7280** [RocketChat/Rocket.Chat#11891]
I have following setup:

chat: chat.mydomain.com
website: mydomain.com

I have embedded rocketchat on mydomain.com in iframe. I also have "central" login system which is setting up localstorage. It works like this:

1. Login user using https://chat.targethit.com/api/v1/login
2. Get the token and set:

>  window.localStorage.setItem("Meteor.userId", uid);
>                 window.localStorage.setItem("Meteor.loginToken", token);
>                 window.localStorage.setItem("Meteor.loginTokenExpires", s);
>                 window.localStorage.setItem("TH.justAfterLogin", true);
>                 window.localStorage.setItem("userLanguage", "en");
> 

Problem:

1. Users logs in, the localStorage is being set
2. Users goes to chat.mydomain.com - everything works
3. Users goes to mydomain.com/chat (where iframe is with src of chat.mydomain.com) -> user is not logged in.

How can i make sure that user is logged in also on mydomain.com/chat? Autologin works for chat.mydomain.com but not for main domain (which is pointing to chat.mydomain.com in iframe).

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
