### ISSUE TITLE
OTR Session bug

### ISSUE THREAD

**Issue by Mortuie** [RocketChat/Rocket.Chat#11898]
### Description:

We have had a situation where one person disconnected from rocket chat i.e. closed the window, but the other person put their computer on standby whilst still in an OTR session. Then when the person who had closed the window logged back on and starting typing, messages came through as a JSON object -> with encrypted messages. I.e the OTR session was not properly closed on both sides of the interaction.

### Steps to reproduce:

1. Start an OTR session between two members
2. Close the window on one client
3. Keep the other client window open. And put the computer on standby
4. Unstandby the one computer and open a new tab with rocket chat on the other client
5. Type a message from the new tabbed client to the standbyed computer.
6. See encrypted message.

### Expected behavior:

OTR session closed when the one client closes the window.

### Actual behavior:

OTR session is still open

### Server Setup Information:

- Version of Rocket.Chat Server: Unsure (Nearly newest)
- Operating System: Mac/OSX -> Iron
- Deployment Method: Unsure
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

-

### Relevant logs:
-

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
