### ISSUE TITLE
Gif on Rocket.Chat

### ISSUE THREAD

**Issue by S6savahd** [RocketChat/Rocket.Chat#11899]
Hi all,

I would like to know whether there is a possibility of having gif feature on rocket.chat. 
We already found this:
https://github.com/FinndropStudios/GifRocket/
However, I am not sure if this is all done in this regard. 

Thanks.

**Comment by lorek123** [comment]
You can use this as an integration (then you need to paste content of [this](https://github.com/FinndropStudios/GifRocket/blob/master/integration.prelegacy/GifRocket.js) file in proper place) or help authors finish work on converting it to an app.

**Comment by kaiiiiiiiii** [comment]
You can find all released Rocket.Chat Apps in the App Marketplace directly in your RC installation or on [this](https://marketplace.rocket.chat).

There’s also a place in the [forums](https://forums.rocket.chat/c/rocket-chat-apps) where you can find more information and App ideas.

Cheers,
Kai


// CC: @TwizzyDizzy You might close this issue as it’s not really a problem with the server component :)
