### ISSUE TITLE
Audio Recordings

### ISSUE THREAD

**Issue by emcguinness** [RocketChat/Rocket.Chat#1189]
We know have the very useful option to restrict file uploads by type but this now causes issues with the button to record a message. While it records after hitting stop nothing happens as the default filter is set to images only. While good to see the filter works it is not the best user experience. Thought it would be good to decide on a way best to solve it.

First option would be to produce an error on finishing record where the upload would normally start. This solves the confusion of when just nothing happens but it is still not the best user experience. The main reason I mention it is because it is (likely) easy to do and would have wins else where in that if I drag and drop an invalid file I should get the same warning (currently just nothing happens).

The preferred option, in my opinion, would be to make the record button appear/disappear based off of your upload filter list. If Auido/* or Audio/mp3 is white listed (at least I believe the recording was mp3) the record button would be visible, if not it is hidden. 

Happy to work on a PR for this, or at least try, just thought it would not hurt to get thoughts in case there was a better way/side effects I missed.

**Comment by gmsecrieru** [comment]
Great catch! Thanks @emcguinness !

Feel free to jump in with the PR and let me know if I can help you with anything, as I have worked on the upload filters.
