### ISSUE TITLE
[BUG] IN API /api/v1/channels.history 

### ISSUE THREAD

**Issue by Ratnikov97** [RocketChat/Rocket.Chat#11903]
If you put the reaction, and then remove it, then in history it will remain

**Comment by MarcosSpessatto** [comment]
@Ratnikov97 can you please share you http request? Because I tried simulate this and I was not able to simulate.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
