### ISSUE TITLE
Windows Desktop App won't open/run

### ISSUE THREAD

**Issue by brinkmedia** [RocketChat/Rocket.Chat#11907]
Just updated to the latest version, now app won't open or run. Tried to uninstall/reinstall, set to run on startup, still won't open or run, even when desktop icon is clicked.

Running on Windows 10 Pro Version 1803, 64-bit x64 processor

**Comment by kaiiiiiiiii** [comment]
Hi @brinkmedia,

you’re in the wrong repository :) The one for the desktop client can be found [here](https://github.com/RocketChat/Rocket.Chat.Electron).

Thanks,
Kai

// CC: @TwizzyDizzy
