### ISSUE TITLE
Composer on the web (Safari, Chrome and Electron) increases for no reason

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11904]
### Description:

![2018-08-30 08 56 56](https://user-images.githubusercontent.com/551004/44850152-b92ee280-ac32-11e8-8e95-e476a971679b.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Linux

**Comment by goobersmooch** [comment]
I'm seeing this issue as well when using the macOS client.

**Comment by rafaelks** [comment]
Still happens in 0.69.1.

**Comment by lehrhardt** [comment]
Seeing this as well under Linux.

**Comment by FaizanZahid** [comment]
I am seeing the same issue for chrome mobile version of site on my android.

**Comment by ggazzo** [comment]
closed by #12138

**Comment by rafaelks** [comment]
Bug is not fixed.

![screen shot 2018-10-01 at 13 26 43](https://user-images.githubusercontent.com/551004/46301783-be5ab680-c57d-11e8-83dd-6e74c9317e04.png)

**Comment by rsimai** [comment]
I can confirm this to still happen in 0.70.4. Not sure how to provoke it, it's however gone if the user reloads the page.

**Comment by rafaelks** [comment]
Still happens in `0.71.0-rc.0` as well.

**Comment by JanZerebecki** [comment]
Happend to me on Firefox. Part of the HTML read `<textarea class="rc-message-box__textarea js-input-message autogrow-short" style="height: 155px;" autofocus="" placeholder="Message" rows="1" dir="ltr">`. Once I go to a different channel the problem is gone. After a restart of Firefox and logging in again to this RockChat, at one point it will happen again.

**Comment by moonwolf-github** [comment]
I just started to happen on my 0.69.2. At least in desktop client.

**Comment by FaizanZahid** [comment]
+1

**Comment by FaizanZahid** [comment]
Agree it happens sometimes on mobile DM or channels

**Comment by dj301** [comment]
Any status update on this issue? @tassoevan  @ggazzo

**Comment by tassoevan** [comment]
@dj301 We did some adjustments in the `develop` branch version which should fix it.

**Comment by ggazzo** [comment]
we changed the messagebox code a lot since this issue was opened, I'm very confident we already fixed it, please reopen if I'm wrong.
