### ISSUE TITLE
LDAP implementation

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#1190]
First, great stuff. We love Rocket.Chat.

We have our implementation running and hooked it up to our LDAP. Works great.
The thing is I would like to disable registration of new users which I can't figure out how. I don't want anyone not in our LDAP to be able to use the chat.
Additionally when a user changes his username or password on the My Account - Profile Page, a new user is created and the LDAP user doesn't work anymore. The option to change username and password should be disabled when using LDAP. Maybe the screen name should be decoupled from LDAP.
On the Login Page it would be great to change the text "Email or username" as our LDAP user need to login with "firstname lastname"

**Comment by gmsecrieru** [comment]
Thanks for the feedback! For what it's worth, disabling registration was requested on #195 -- maybe we should use this issue to track something else.

**Comment by emcguinness** [comment]
I have a PR in place for disabling username changes [here](https://github.com/RocketChat/Rocket.Chat/pull/1158) for that exact reason. To be honest I did not think of the password disabling(changing it did nothing) but could quickly extend the change to include disabling of password changes with minimal effort.

**Comment by gmsecrieru** [comment]
I would say go for it! :+1:

**Comment by emcguinness** [comment]
My PR just got merged which adds a setting under accounts, general to disable change of username. Due to my incompetence this does actually disable password change too for now. I have most of the code in place to correct that to only disable username and add a new setting to disable password change separately. Should be submitting a PR later tonight unless I screw up again :)

**Comment by emcguinness** [comment]
Looks like my new [PR](https://github.com/RocketChat/Rocket.Chat/pull/1215) got merged, this fixes my last failed one so with the new build you now should have 2 settings (Under accounts, general) that control disabling of username/password.

Adding a setting to control the place holder text for the login form would not take much work, for now though you could use the login terms section under layout to add a note under the login box that explains how to login. I was hoping to just add some javascript here to do it but either I made a mistake or it is being sanitised, don't see it happening in the Rocket.Chat code but Meteor could be doing that. Will have a look into that later.

There are a  few other issues open about various LDAP improvements so might be worth checking if there are any else that are of use and adding a me too. I am not part of their team but from monitoring this issue tracker I can see LDAP is one of those on their list that they are eager to improve (then again they are eager to improve anything).

**Comment by Theaxiom** [comment]
Awesome, thanks!

**Comment by flashguy22** [comment]
Thanks @emcguinness. Great work!

**Comment by geekgonecrazy** [comment]
What's left on this?

**Comment by hjf288** [comment]
Don't know if I should start a new issue however I believe that LDAP group sync is quite an essential feature.

**Comment by rodrigok** [comment]
@flashguy22 Now there is an option to disable registration on login form and when you enable LDAP we disable the ability to change usernames (current at branch develop).

I created a new issue https://github.com/RocketChat/Rocket.Chat/issues/2204 (Setting to change the login screen texts)

**Comment by Theaxiom** [comment]
Thank you, thank you, thank you!

Thanks,
Travis Rowland
http://travisrowland.com
http://linkedin.com/in/travisrowland
http://about.me/travisrowland

-----------------------------------------------

This e-mail is privileged and confidential.  Do not forward, copy or print
without authorization.  If you are not the intended recipient of this
E-mail, you are hereby notified that any dissemination, distribution or
copying of this message is strictly prohibited. If misdirected, please
delete and notify the sender by e-mail at travis.rowland@gmail.com.

CAUTION: E-mail sent through the internet is not secure and could be
intercepted by a third party. For your protection, avoid sending
identifying information, such as account numbers or social security numbers.
