### ISSUE TITLE
[BUG] The username does not appear

### ISSUE THREAD

**Issue by zzeesstt** [RocketChat/Rocket.Chat#11913]
Since version 0.68.3 there was a problem with the names I showed on video here - https://drive.google.com/open?id=1KwPHSRVhrlknnO_LRyZJ8FM29syZQqk6

**Comment by dude75** [comment]
+1 i'm have same bug

**Comment by oinadmin** [comment]
+1

**Comment by 1c4nw1n** [comment]
+1

**Comment by sampaiodiego** [comment]
this was fixed by https://github.com/RocketChat/Rocket.Chat/pull/12154
