### ISSUE TITLE
snap repo is not updated for rocketchat-desktop. It still has 2.7.0 for rocketchat-desktop while 2.13 is available elsewhere

### ISSUE THREAD

**Issue by icerootsvw** [RocketChat/Rocket.Chat#11912]
### Description:
SNAP is still offering rocketchat-desktop as 2.7 https://uappexplorer.com/snap/ubuntu/rocketchat-desktop

Contact: https://demo.rocket.chat/channel/ubuntu-snap
Website: https://rocket.chat
Confinement: strict
Version: 2.7.0
**Updated: May 11, 2017
Published: Apr 9, 2017**
License: MIT
File Size: 84.5 MB
Architectures: amd64

While the website https://rocket.chat/install is showing 2.13 and this one as well https://github.com/RocketChat/Rocket.Chat.Electron/releases/

So seems like a push was missing to snap?

**Comment by kaiiiiiiiii** [comment]
Hi @icerootsvw,

you’re in the wrong repository :) The one for the desktop client can be found [here](https://github.com/RocketChat/Rocket.Chat.Electron).

Thanks,
Kai

// CC: @TwizzyDizzy

**Comment by icerootsvw** [comment]
Hi Kai,
i am sorry i am completely new to snap and so on. Still an old debian apt-get guy.
If i am correct the link you showed me is a git repository i have to checkout with git clone. I was looking for something i can install and update with apt-get or snap. Like i am doing for rocketchat-server which is installed with snap as well.

If i am doing something wrong here or if i got something wrong i would be happy if you can point me in the right direction

**Comment by kaiiiiiiiii** [comment]
You don't need to clone the other repository, just open your issue over there :) This repo is for the server component, the Electron repo is for the desktop clients (Windows, Mac, *nix, ...).

**Comment by TwizzyDizzy** [comment]
So what you're basically looking for is an APT repo for the Electron client. There is no APT (or RPM for that matter) repo of any kind.

You can download the debian packages from [here](https://github.com/RocketChat/Rocket.Chat.Electron/releases), but as there is no repo no automatic update will happen and you have to download every new version manually if you decide to install by package.

Cheers
Thomas
