### ISSUE TITLE
[Request] Compatibility with Cheese Pizza

### ISSUE THREAD

**Issue by tsukiRep** [RocketChat/Rocket.Chat#11915]
thanks

**Comment by tsukiRep** [comment]
this is a feature me and my coleags would lik to see

**Comment by tsukiRep** [comment]
THATS GOOD IDEA

**Comment by kaiiiiiiiii** [comment]
Please create a proper feature request and describe exactly what you want. Otherwise, no one will help you.

Thanks

// CC: @TwizzyDizzy Can we close this for now and reopen it when all information is provided? Thanks!
