### ISSUE TITLE
Tray icon is invisible in Windows 7

### ISSUE THREAD

**Issue by ktsangop** [RocketChat/Rocket.Chat#11911]
With latest updates, the tray icon color seems to have changed.
This leads to the following problem as seen on the picture below. The tray icon is not visible at all, unless you hover over it, when a slight outline is visible.

![rocket_chat](https://user-images.githubusercontent.com/25545730/44896731-373cc900-acc7-11e8-9333-4d6853a088b6.jpg)

Rocket.Chat Version : 2.13.1
OS: Windows 7 pro 64bit (latest updates)

**Comment by kaiiiiiiiii** [comment]
Hi,

you’re in the wrong repository :) The one for the desktop client can be found [here](https://github.com/RocketChat/Rocket.Chat.Electron).

Thanks,
Kai

// CC: @TwizzyDizzy

**Comment by ktsangop** [comment]
Ooops sorry...
:+1:
