### ISSUE TITLE
Broken drop-down menu in rooms members list

### ISSUE THREAD

**Issue by asand3r** [RocketChat/Rocket.Chat#11929]
### Description:

If we are clicking on three dots near last user in room members list, drop-down menu looks like on attached screenshot. If same user placed on top or in the middle of the list all is OK. Checked in Firefox 61.0.2 and Google Chrome 68.0.3440.106.

### Steps to reproduce:

1. Rooms members list
2. Click on 3 dots near last user in the list

### Actual behavior:

![default](https://user-images.githubusercontent.com/13959303/44957130-fc10e480-aed6-11e8-9fc2-ad4f3af992a6.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.1
- Operating System: CenOS 7.5.1804
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0

**Comment by rasos** [comment]
I think this is fixed since RC 2.0 and this issue can be closed.
