### ISSUE TITLE
channel avatar is not shown when Rocket.Chat is running in subdir

### ISSUE THREAD

**Issue by thaim** [RocketChat/Rocket.Chat#11924]
### Description:

When RocketChat is running in subdir, channel avatar in sidebar is not shown.

### Steps to reproduce:

1. start docker with environment: ROOT_URL=http://localhost:3000/chat
2. create public/private groups
3. show sidebar

### Expected behavior:

![expected-sidebar](https://user-images.githubusercontent.com/1024789/44947314-5ca41100-ae46-11e8-82b9-004bf9afff96.png)

### Actual behavior:

![actual-sidebar](https://user-images.githubusercontent.com/1024789/44947294-1f3f8380-ae46-11e8-8c07-7e31312d497c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Ubuntu 16.04.5
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by gravelweb** [comment]
Have you tried updating the Site URL setting to include the subdir "/chat"?

Administration > General > Site URL

**Comment by thaim** [comment]
I configured Site URL as `http://<mydomain>/chat` and not working correctly as above.

I found that when I configure Site URL as `http://<mydomain>` and access via `http://<mydomain>/chat`, it works as expected!
Avatar link is `http://<mydomain>/chat/avatar/%40general?_dc=undefined` when it works correctly,
but `http://<mydomain>/chat/chat/avatar/%40general?_dc=undefined` when it is not working.

**Comment by ura14h** [comment]
I configured a frontend server to below:

```
# Rewrite URL for Apache and Rocket.Chat
#
# Routing:
#     Client (Web Browser or Application)
#         -> https://myserver.example.com/chat/ (Apache)
#             -> http://localhost:3000/chat/ (Rocket.Chat)
#
ProxyRequests Off
ProxyVia On
RewriteEngine On
RewriteCond %{HTTP_REFERER} ^https://myserver.example.com/chat/
RewriteRule ^/api/v1/commands\.list$ /chat/api/v1/commands.list [NE]
RewriteCond %{HTTP_REFERER} ^https://myserver.example.com/chat/
RewriteRule ^/api/apps/languages$    /chat/api/apps/languages [NE]
RewriteRule ^/chat/chat/chat/(.*)    /chat/$1 [NE]
RewriteRule ^/chat/chat/(.*)         /chat/$1 [NE]
RewriteRule ^/chat$                  /chat/ [NE]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule ^/chat/(.*)              http://localhost:3000/chat/$1 [NE,P,L]
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule ^/chat/(.*)              ws://localhost:3000/chat/$1 [NE,P,L]
ProxyPassReverse /chat/ http://localhost:3000/chat/
```

There may still be suspicious behavior, but a client is working as I expected.

P.S.
Hmm... This hack cannot fix #11922.

**Comment by balcsida** [comment]
Hi @thaim, 

#12365 is merged to master and included in release 0.71.0-rc.0.
It seems that it resolved a similar issue for me.
Do you experience the same thing?

**Comment by thaim** [comment]
Thanks for notifying the issue and the release.
I've tried the release 0.71.0, but that didn't solved this issue.

**Comment by shirosaki** [comment]
I have same issue with 0.72.0.
ROOT_URL is https://xxxxxxxxxxxxxxx/rocketchat/
Avatar URL is https://xxxxxxxxxxxxxxx/rocketchat/rocketchat/avatar/xxxxxxxx?_dc=0
Subdir path is duplicated.

**Comment by shirosaki** [comment]
Image lazy load appends subdir path to `url` which already has subdir.
`url` seems to be from https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-utils/lib/getAvatarUrlFromUsername.js.
This is a patch. This works for me.

```diff
diff --git a/packages/rocketchat-lazy-load/client/index.js b/packages/rocketchat-lazy-load/client/index.js
index 4ec008e08..f33a4bd14 100644
--- a/packages/rocketchat-lazy-load/client/index.js
+++ b/packages/rocketchat-lazy-load/client/index.js
@@ -13,7 +13,7 @@ export const fixCordova = function(url) {
        } else if (navigator.userAgent.indexOf('Electron') > -1) {
                return __meteor_runtime_config__.ROOT_URL_PATH_PREFIX + url;
        } else {
-               return Meteor.absoluteUrl().replace(/\/$/, '') + url;
+               return Meteor.absoluteUrl().replace(/\/$/, '') + url.replace(__meteor_runtime_config__.ROOT_URL_PATH_PREFIX, '/');
        }
 };

```

**Comment by raphaelmpinheiro** [comment]
I have same issue with version 0.74.3
