### ISSUE TITLE
rocket.chat "register a new account", text is too light to read

### ISSUE THREAD

**Issue by zogith** [RocketChat/Rocket.Chat#11923]
### Description:

I'm using rocket.chat 0.69 deployed from docker, but rocket.chat's own instance at https://open.rocket.chat/home exhibits the same issue..

The "register a new account" screen displays the field labels in a pale colour with not enough contrast, very difficult to read. This was reported to me by someone using a projector to check out rocket.chat, which maybe made the problem worse, but I agree as the "front door" to the application I think it should be more readable. I looked through and couldn't see this reported as a specific issue.

### Steps to reproduce:

1. Go to "register a new account"
2. Attempt to read the text for the field labels.

### Expected behavior:

1. Go to "register a new account"
2. Attempt to read the text for the field labels.. succeed instantly

### Actual behavior:

1. Go to "register a new account"
2. Attempt to read the text for the field labels, have to adjust contrast or squint to see "Confirm your password" etc. The user who reported this to me had to use image processing on a screenshot to make the labels readable.

### Server Setup Information:

Reported by a user to my server using a FHD projector as a monitor, but I agree it is not very readable on an Acer AL1722 LCD monitor with firefox as well.
Issue is visible on the rocket.chat server at https://open.rocket.chat/home as well as mine 

### Additional context

Screen Image reported by user as unreadable:

![rocketchat-01](https://user-images.githubusercontent.com/7069599/44940707-8ffa8780-add5-11e8-8981-899a112a0e70.png)

Screen image fixed to be readable by user, they could not read the fields until they did this:

![rocketchat-02](https://user-images.githubusercontent.com/7069599/44940714-ac96bf80-add5-11e8-99c9-1084fdeecb49.png)

**Comment by reetp** [comment]
Please follow up here
https://github.com/RocketChat/Rocket.Chat/issues/12061

Also note this:
https://github.com/RocketChat/Rocket.Chat/issues/12325

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close
