### ISSUE TITLE
System tray icon color

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat#11928]
I upgraded my desktop app but I have notice that the system tray icon have the same color red when I was mention or there is just a new message.

The older version is when I was not mention but there is a new chat the system icon turns to green and when I am mention it will be red.

Any idea how to make the desktop app system tray the same as the old one? or is this a bug?

Desktop App version: 2.13.1
Rocket Chat Server Version: 0.69.0
OS: Ubuntu 16.01

**Comment by kaiiiiiiiii** [comment]
Hi,

you’re in the wrong repository :) The one for the desktop client can be found [here](https://github.com/RocketChat/Rocket.Chat.Electron). But please do not open a new issue in the Electron Repo, they’re already aware of this issue :)

Thanks,
Kai

// CC: @TwizzyDizzy

**Comment by ccfiel** [comment]
Hello @kaiiiiiiiii,

Thanks for the response but I did not find the issue the Electron Repo about the system tray icon problem. 

Cheers,
Chris

**Comment by TwizzyDizzy** [comment]
Guess it's this one: https://github.com/RocketChat/Rocket.Chat.Electron/issues/805
