### ISSUE TITLE
cannot add attach files (v0.69.0)

### ISSUE THREAD

**Issue by efih** [RocketChat/Rocket.Chat#11930]
Hi Guys,

after upgrade to v0.69.0 , cannot add attachment, its stuck on uploading 
you can see the screen shot and the logs
any one alse meet this issue ?

Version of Rocket.Chat Server: 0.69.0
Operating System: Ubuntu
Deployment Method(snap/docker/tar/etc): snap
Number of Running Instances: 1
Node Version: v8.11.3
Steps to Reproduce:
PRTSCN or add attachfile

screen shot : 
https://i.imgur.com/XjwbWgH.png

### Relevant logs:

ufsCreate -> userId: mr9Fx2m3pohYmQR8B , arguments:  [ { name: 'Clipboard - 2 test 2018 18:15',
Sep  2 18:15:27 rocket-chat rocketchat-server.rocketchat-server[1339]:     size: 2701,
Sep  2 18:15:27 rocket-chat rocketchat-server.rocketchat-server[1339]:     type: 'image/png',
Sep  2 18:15:27 rocket-chat rocketchat-server.rocketchat-server[1339]:     rid: '9wsn4vfsrprJKYsKxmr9Fx2m3pohYmQR8B',
Sep  2 18:15:27 rocket-chat rocketchat-server.rocketchat-server[1339]:     description: 'test',
Sep  2 18:15:27 rocket-chat rocketchat-server.rocketchat-server[1339]:     store: 'Uploads' } ]

i also check the space on the server :
root@rocket-chat:~# df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               2.0G     0  2.0G   0% /dev
tmpfs                              395M   11M  384M   3% /run
/dev/mapper/rocket--chat--vg-root   94G  6.3G   84G   8% /
tmpfs                              2.0G     0  2.0G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/loop1                         199M  199M     0 100% /snap/rocketchat-server/1321
/dev/loop0                         202M  202M     0 100% /snap/rocketchat-server/1308
/dev/loop4                         128K  128K     0 100% /snap/hello/20
/dev/loop3                          87M   87M     0 100% /snap/core/4571
/dev/loop2                          84M   84M     0 100% /snap/core/3748
/dev/loop6                         209M  209M     0 100% /snap/rocketchat-server/1263
/dev/loop5                          84M   84M     0 100% /snap/core/3440
/dev/sda1                          472M  106M  342M  24% /boot
tmpfs                              395M     0  395M   0% /run/user/0

**Comment by stan-savransky** [comment]
i have same issue

Version of Rocket.Chat Server: 0.69.0
Operating System: Centos
Deployment Method(snap/docker/tar/etc): docker
Number of Running Instances: 1

Steps to Reproduce:
Attach/Upload file in chat 

in container got this log message:

Error: FileNotFound: no file with id THpd7B97KFcR8WcZL found
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
    at handleCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by piotrkochan** [comment]
Check that General -> Site URL matches current RocketChat URL

**Comment by efih** [comment]
> Check that General -> Site URL matches current RocketChat URL

yes. its same

**Comment by jseong309** [comment]
Had something similar but only on IOS devices.
For me adding this to rocketchat.conf in apache2/nginx fixed the issue.  
client_max_body_size 0;

**Comment by piotrkochan** [comment]
setting client_max_body_size to 0 is bad, you should use value >0, eg 50M

**Comment by jseong309** [comment]
Can you elaborate? I know disables checking of client request body size. But not sure what issue that might cause later on.
But for my issue IOS devices could not send photos with anything other than 0.

**Comment by piotrkochan** [comment]
Just read nginx documentation what this setting does. Also there is related iOS app thread https://github.com/RocketChat/Rocket.Chat.iOS/issues/2193

**Comment by geekgonecrazy** [comment]
Important bit is also which file store you are using?

Will close due to inactivity.  Please feel free to comment again if still an issue
