### ISSUE TITLE
User don't send direct message after update.

### ISSUE THREAD

**Issue by desperadisse** [RocketChat/Rocket.Chat#11934]
Hello,

All users can not currently send more direct messages if they are not 'Admin'.
I have already checked the permissions and the "user" have permission to send direct messages. The problem occurred after the update and it impacts us considerably.

Here is the error message from users: "Error, too many requests, please slow down, you must wait 60 seconds before trying again.

It will seem that the problem comes from meteor. I really need you!

Thank you in advance

**Comment by jaschadub** [comment]
I had the same issue but was only happening for "guest" users. When changed them to "user" started working. Might try making whole new group and move user to that to see if makes difference as work around.

**Comment by ggazzo** [comment]
closing this issue because I didt see more problems related, please any problem reopen.
