### ISSUE TITLE
[BUG] LDAP sync converting username instead of using uid/sAMAccountName

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat#11933]
### Description:

After starting with normal registration we are now using the LDAP sync against our corporate Active Directory, however it seems that the username of one user with some kind of extravagant name is converted wrongly. His (here made-up) name is "Michael zum Holz-Hacker" and our AD username for him is `michael.zumholz-hacker`. However when I start a sync I get the error `Email already exists` because he registered with "our" username but the LDAP sync is converting it to `michael.zumholz.hacker`, can't find the username, tries to create a new one but the address already exists. IMHO it should use the `sAMAccountName`/`uid` and not create its own username.

### Steps to reproduce:

1. Start using Rocket.Chat with normal registration and create account for user with said name
2. Implement LDAP sync and merge existing accounts

### Expected behavior:

Just sync mail address and password

### Actual behavior:

`Email already exists` errors because it tries to create a new user

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: openSUSE 15.0
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: 8.11.3

### Relevant logs:

These are the relevant logs when starting the sync:
```
{"name":"ldapjs","component":"client","hostname":"rocketchat","pid":2029,"clazz":"Client","level":10,"msg":"Parsing done: {\"messageID\":2,\"protocolOp\":\"SearchEntry\",\"objectName\":\"CN=Michael zum Holz-Hacker,OU=Development,DC=company,DC=org\",\"attributes\":[{\"type\":\"objectClass\",\"vals\":[\"top\",\"person\",\"organizationalPerson\",\"user\"]},{\"type\":\"cn\",\"vals\":[\"Michael zum Holz-Hacker\"]},{\"type\":\"sn\",\"vals\":[\"zum Holz-Hacker\"]},{\"type\":\"givenName\",\"vals\":[\"Michael\"]},{\"type\":\"distinguishedName\",\"vals\":[\"CN=Michael zum Holz-Hacker,OU=Development,DC=company,DC=org\"]},{\"type\":\"instanceType\",\"vals\":[\"4\"]},{\"type\":\"whenCreated\",\"vals\":[\"20180410105028.0Z\"]},{\"type\":\"whenChanged\",\"vals\":[\"20180903080634.0Z\"]},{\"type\":\"displayName\",\"vals\":[\"Michael zum Holz-Hacker\"]},{\"type\":\"uSNCreated\",\"vals\":[\"84221\"]},{\"type\":\"memberOf\",\"vals\":[\"Group\"]},{\"type\":\"company\",\"vals\":[\"Company\"]},{\"type\":\"name\",\"vals\":[\"Michael zum Holz-Hacker\"]},{\"type\":\"objectGUID\",\"vals\":[\"0\"]},{\"type\":\"userAccountControl\",\"vals\":[\"66048\"]},{\"type\":\"badPwdCount\",\"vals\":[\"0\"]},{\"type\":\"codePage\",\"vals\":[\"0\"]},{\"type\":\"countryCode\",\"vals\":[\"0\"]},{\"type\":\"badPasswordTime\",\"vals\":[\"0\"]},{\"type\":\"lastLogoff\",\"vals\":[\"0\"]},{\"type\":\"lastLogon\",\"vals\":[\"0\"]},{\"type\":\"pwdLastSet\",\"vals\":[\"131683603030852862\"]},{\"type\":\"primaryGroupID\",\"vals\":[\"513\"]},{\"type\":\"profilePath\",\"vals\":[\"0\"]},{\"type\":\"objectSid\",\"vals\":[\"0\"]},{\"type\":\"accountExpires\",\"vals\":[\"9223372036854775807\"]},{\"type\":\"logonCount\",\"vals\":[\"0\"]},{\"type\":\"sAMAccountName\",\"vals\":[\"michael.zumholz-hacker\"]},{\"type\":\"sAMAccountType\",\"vals\":[\"805306368\"]},{\"type\":\"userPrincipalName\",\"vals\":[\"michael.zumholz-hacker@company.org\"]},{\"type\":\"lockoutTime\",\"vals\":[\"0\"]},{\"type\":\"objectCategory\",\"vals\":[\"CN=Person,CN=Schema,CN=Configuration,DC=company,DC=org\"]},{\"type\":\"dSCorePropagationData\",\"vals\":[\"16010101000000.0Z\"]},{\"type\":\"mail\",\"vals\":[\"michael.zumholz-hacker@company.org\"]}],\"controls\":[]}","time":"2018-09-03T08:28:26.129Z","v":0}
rocketchat_logger rocketchat_logger.js:278 LDAPSync ➔ debug userQuery merge { username: 'michael.zumholz.hacker' }
rocketchat_logger rocketchat_logger.js:278 TemplateVarHandler ➔ debug template found. replacing values
rocketchat_logger rocketchat_logger.js:278 TemplateVarHandler ➔ debug replacing template var: #{givenName} with value: Michael
rocketchat_logger rocketchat_logger.js:278 TemplateVarHandler ➔ debug replacing template var: #{sn} with value: zum Holz-Hacker
rocketchat_logger rocketchat_logger.js:278 LDAPSync ➔ debug user.name changed to: Michael zum Holz-Hacker
rocketchat_logger rocketchat_logger.js:278 LDAPSync ➔ debug New user data { username: 'michael.zumholz.hacker',
  email: 'michael.zumholz.hacker@company.org' }
rocketchat_logger rocketchat_logger.js:278 LDAPSync ➔ error Error creating user { Error: Email already exists. [403]

**Comment by TheReal1604** [comment]
@der-eismann Hi Philipp,

if you try to do the merge, it is important that the username and email-address in rocket.chat are the same as in LDAP. 

We have done this in our deployment also for 700~ users. My best suggestion would be to write a python script which changes all the accounts in rocket.chat to the samaccountname value in your ActiveDirectory. After that the merge works like you would expect it. (Maybe with csv lists)

The used api is: https://rocket.chat/docs/developer-guides/rest-api/users/update and https://rocket.chat/docs/developer-guides/rest-api/users/info/

**Comment by der-eismann** [comment]
Hey, thanks for your answer!

However the names **are** the same, it's always `michael.zumholz-hacker` with one dot and one dash, in Active Directory:
![domain](https://user-images.githubusercontent.com/10406217/44984808-76487400-af7e-11e8-8ce5-6321359da583.png)
And Rocket.Chat:
![rocketchat](https://user-images.githubusercontent.com/10406217/44984813-7c3e5500-af7e-11e8-9cc2-97e1543f549d.png)
I have no idea where he gets the `michael.zumholz.hacker` with two dots from - that version never existed.

**Comment by TheReal1604** [comment]
@der-eismann you configured this setting correctly?

![image](https://user-images.githubusercontent.com/5877910/44990986-160ffd00-af93-11e8-9e7b-dfa262366a53.png)

**Comment by himpierre** [comment]
Same problem here. LDAP Username foo-bar gets converted to foo.bar.

**Comment by der-eismann** [comment]
I'm unsubscribing since I don't use Rocket.Chat anymore.

**Comment by sfinity** [comment]
My System Environment is it work. 
LDAP Username foo-bar is work.
core version 0.74.0 and 1.0.0-beta.0
