### ISSUE TITLE
Rocket Apps from marketplace can not be installed

### ISSUE THREAD

**Issue by asadi110** [RocketChat/Rocket.Chat#11932]
### Description:

App can not be installed either from file or from url and stay in install mode 

### Steps to reproduce:

1. Go to Apps menu
2. select one app in list
3. click install button
or 
1. Go to Apps menu
2. click + button
3.insert app URL from RC marketplace
4.click install button
or
1. Go to Apps menu
2.download app from RC market place 
3.click + button
4.click Browse button and select downloaded app
5. click install
### Expected behavior:

installation done.

### Actual behavior:

installation not complete.
### Server Setup Information:

- Version of Rocket.Chat Server: 6.9.0
- Operating System: ubuntu 16.0.4
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabeld
- NodeJS Version: v8.11.3
- MongoDB Version: 3.2.7

### Relevant logs:

[34mI20180903-02:40:01.522(-4) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug GET: /api/apps 
[34mI20180903-02:40:01.524(-4) rocketchat_logger rocketchat_logger.js:278 [34mAPI ➔ debug Success { statusCode: 200, body: { apps: [], success: true } } 
[34mI20180903-02:40:01.990(-4) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method UserPresence:online -> userId: TpguiQZ5gPMyTpXGi , arguments:  [ null ] 
[34mI20180903-02:40:02.018(-4) rocketchat_logger rocketchat_logger.js:278 [34mChatpal Logger ➔ debug indexed 1 documents {   "responseHeader": {     "status": 0,     "QTime": 2   } } 
![capture1](https://user-images.githubusercontent.com/11172751/44971302-51e29c80-af6a-11e8-8571-aa93fd46d7c1.JPG)
![capture2](https://user-images.githubusercontent.com/11172751/44971303-527b3300-af6a-11e8-9b7f-6e7eb31ba62d.JPG)

**Comment by reetp** [comment]
Can you test on 0.70.x latest please?

**Comment by asadi110** [comment]
I use snap and it not updated to 0.70.x yet.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  Please feel free to comment back if you still have issues
