### ISSUE TITLE
Upgrade from 2.12.1 to 2.13.1

### ISSUE THREAD

**Issue by Kochise** [RocketChat/Rocket.Chat#11940]
Got two folders, 'rocket.chat' (2.13.1) and 'rocket.chat+' (2.12.1) and the two opening at windows logon, the 2.12.1 version keeps telling me an upgrade is available. I uninstall 'rocket.chat+' (2.12.1) which removes the 'rocket.chat' (2.13.1) startup link but leaves the dandling 'rocket.chat+' (2.12.1) startup link in the wild.

Expected behavior :

1- close the current running rocket.chat version
2- either remove it or overwrite it (but keep user data)
3- start the new rocket.chat version

What you shouldn't do

0- wide wild west

It's not because it's a free and open source project that some common sense should be lost in the meantime. You have a nice website, put some effort in your installation/upgrade procedure.

It's a mess at every upgrade that I consider skipping it every time.

And I'm every time disappointed.

So I filled this bug report.

**Comment by geekgonecrazy** [comment]
@thomasspiesser @ggazzo maybe you guys have an idea of why this didn't migrate smoothly.

From what I can see this is the only time it makes sense that there was an issue like this.  Previous updates I haven't heard of their being big issues.  This one however had an app rename so it makes sense that an issue like this happened.

We might want to move this to desktop repo

**Comment by B-Art** [comment]
I had (have this problem too whit version 2.13.0 to 2.13.1.
It was my mistake that I those to install version 2.13.1 for USER not for ALL.
It would be help full if an upgrade detects its older configuration of installation and repeats that.
Now its nagging me to install it for USER and every time I have to disable autostart...

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #872](https://github.com/RocketChat/Rocket.Chat.Electron/issues/872) via [**ZenHub**](https://www.zenhub.com/)
