### ISSUE TITLE
[Urgent] Unable to quote more than one message at a time in new version (0.69.0)

### ISSUE THREAD

**Issue by sonalinisha456** [RocketChat/Rocket.Chat#11943]
We used 0.59.3, but last week we updated our version to 0.69.0

In early version had  quote more than one message at a time.

![1](https://user-images.githubusercontent.com/33144615/45023644-921e4980-b054-11e8-8616-df5de884ad4c.jpg)

But now i can quote only one message at a time...

![2](https://user-images.githubusercontent.com/33144615/45023734-d3165e00-b054-11e8-816a-8181fbd75b3a.jpg)

So I filled this bug report.

**Comment by ggazzo** [comment]
its working

![image](https://user-images.githubusercontent.com/5263975/67052879-fe072880-f115-11e9-99aa-8b539867ae75.png)
![image](https://user-images.githubusercontent.com/5263975/67052884-0495a000-f116-11e9-8365-2ee14e3daab7.png)
