### ISSUE TITLE
Old version of RocketChat not uninstalled - Rocket 2.13.1

### ISSUE THREAD

**Issue by francoisa43** [RocketChat/Rocket.Chat#11942]
## My Setup
- Operating System: Windows 10 1803
- App Version: 2.13.1

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After installing the latest version of rocketchat, we realized that the old version of the software was not uninstalled.
Attached a screenshot of the windows application manager
What can we do ?

### Current Behavior
Do not uninstall old versions of rocketchat

### Expected Behavior
Uninstall old versions of rocketchat

![capture](https://user-images.githubusercontent.com/42959074/45016112-012f7a00-b024-11e8-9a76-3194d8f41ed5.JPG)

**Comment by kaiiiiiiiii** [comment]
Hi @francoisa43,

you’re in the wrong repository :) The one for the desktop client can be found [here](https://github.com/RocketChat/Rocket.Chat.Electron).

Thanks,
Kai

// CC: @TwizzyDizzy

**Comment by francoisa43** [comment]
Thank you, I move the issues in the right repository
