### ISSUE TITLE
How to query case-insensitive users via REST API

### ISSUE THREAD

**Issue by tmbiOS** [RocketChat/Rocket.Chat#11945]
Hi!
How can I query case-insensitive user names via Rest:
/api/v1/users.list

**Comment by piotrkochan** [comment]
go to forum dude this is not an issue.

**Comment by kaiiiiiiiii** [comment]
Hi @tmbiOS,

as @piotrkochan  already said, this is the wrong place for such questions. Please see the [forums](https://forums.rocket.chat/) for help.

Thanks

//CC: @TwizzyDizzy
