### ISSUE TITLE
Outbound http and https requests from server to honor http_proxy env variables (oembed)

### ISSUE THREAD

**Issue by jascott** [RocketChat/Rocket.Chat#1194]
After discussion in Rocket.Chat#support and some investigation, it was concluded that links to images and pages were not embedding in the chat channel because the http_proxy environment variables were not being honored.

The solution we discussed was to make oembed detect the http_proxy variables and use them if they exist.

**Comment by Sing-Li** [comment]
Hints for Digital Ocean Hacktoberfest bounty hunters.

http://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client

https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-oembed/server/server.coffee#L12

**Comment by kakawait** [comment]
Duplicate https://github.com/RocketChat/Rocket.Chat/issues/851 where I explain other possible solution

**Comment by luozengbin** [comment]
https://www.npmjs.com/package/global-tunnel is easy to fix this issue.
i just hack rocketchat_oembed.js with fllowing code.

$ diff rocketchat_oembed.js rocketchat_oembed.js.orgn 
35,39d34
< globalTunnel = Npm.require('global-tunnel'); 
< globalTunnel.initialize();                                                                                 // 1

**Comment by Mitsugaru** [comment]
@luozengbin can you elaborate on that? Have an instance of Rocket.Chat deployed from a docker container, just not sure where to put the two lines you mentioned...

@Sing-Li I get that handling deployments behind corporate proxies is probably a low priority... but perhaps could we have some proxy fields in the administration panel that it could then read and use for outbound connections?

**Comment by pwr22** [comment]
Still present, any movement on this so far?

**Comment by wesbland** [comment]
This has been closed, but I'm still seeing the issue on the latest versions of Rocket.Chat. Is there some sort of advice/wiki page for setting up a regular proxy (not a reverse proxy) that isn't obvious?

**Comment by maxdwit** [comment]
+1 have the same issue. Behind proxy I dont see any preview links

**Comment by sysr-q** [comment]
Can confirm this is still an issue on 0.69.0 (unless I'm missing something obvious).
Behind a regular corporate proxy, there's no embeds.

**Comment by conman2305** [comment]
Seeing this issue as well on 0.69.1. Any updates? Should I open a new issue?

**Comment by sysr-q** [comment]
For anyone who comes across this, I figured out a (partial) solution if you're running Rocket.Chat under Ubuntu Snaps.

From your Rocket.Chat server, run: `sudo systemctl edit snap.rocketchat-server.rocketchat-server.service`

Add the following contents:

```
[Service]
Environment=HTTP_PROXY=http://proxy.example.com:8080/
Environment=HTTPS_PROXY=http://proxy.example.com:8080/
Environment=NO_PROXY='something.example.com,*.intranet.example.com'
```

You can leave out the `NO_PROXY` line if you need, but at $EMPLOYER, we link intranet stuff so for Rocket.Chat to show previews for internal stuff that's required.

**Comment by pagnotta** [comment]
There is also a solution for the "manual" Ubuntu install:

In the systemd unit file `/lib/systemd/system/rocketchat.service` you can set environment variables, I added HTTP_PROXY and HTTPS_PROXY there. Link preview works now.

```
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=https://<yourdomain>:3000/ PORT=3000 HTTP_PROXY=http://<yourproxyurl>:<PORT> HTTPS_PROXY=http://<yourproxyurl>:<PORT>
[Install]
WantedBy=multi-user.target
```

**Comment by magicbelette** [comment]
Becarful if you set a HTTP(S)_PROXY it will be you use for everything, even for communication with other local Rocket.Chat instances. NO_PROXY is not read either. See https://github.com/RocketChat/Rocket.Chat/issues/11484

**Comment by Abraka** [comment]
Agreed, HTTP(S)_PROXY its not a solution here. There should be a option under link preview option in rocket chat administration called "proxy settings for downloading external content". And thats it...see? Easy peasy.

**Comment by reetp** [comment]
For more Proxy stuff see:
https://github.com/RocketChat/Rocket.Chat/issues/2657
