### ISSUE TITLE
Another end-to-end encrypt conversation suggest

### ISSUE THREAD

**Issue by daimon99** [RocketChat/Rocket.Chat#11956]
Sometimes when we do a secret chat, we even need to ensure our chat cannot be decrypt by the server.

I imagine such a user story: 

1. we start a chat
2. we negotiate a password for our chat in other methods such as telephone. rocket chat do not mention it.
3. we enter a password for this chat in rocket chat app. the password only save in local. 
4. we send msg in this chat to each other
5. the rocket app use our common password to encrypt our messages using aes encrypt method
6. the server get the encrypted message that cannot decrypted it
7. the msg receiver, in his app, using the common password to decrypt the message in this conversation
8. we two can delete the password saved in our local storage. if we deleted, then we need to enter it again when we enter this conversation again

**Comment by phongb2b** [comment]
Could be something like telegram: https://core.telegram.org/api/end-to-end ?

**Comment by elievischel** [comment]
With the E2E coming this quarter and the possibility to create channel for only 2 memberds and the OTR possibility...

Why do you need such things ?

**Comment by daimon99** [comment]
@elievischel I only see an issue: #9999 , no furtur detail solution. And in that issue said: "Private keys are encrypted on the client and then stored in the server. ". That is not what I need.

* key should be saved in client
* no need for the participants online

**Comment by geekgonecrazy** [comment]
E2e coming this release.  :)
