### ISSUE TITLE
Hide archived channels in directory listing

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#11958]
Current behaviour: 

The directory listing is showing all channels, even those which are archived.

Expected behaviour: 

Do not list archived channels. Or at least offer a switch to show archived channels also, default is to show channels in use only. 

Workaround: 

We had to delete archived channels, so that they do not show up in the directory listing.

Related to #10990

**Comment by ggazzo** [comment]
please provide us more info, like or server info and some images, thanks

**Comment by laem** [comment]
I've had the same problem. 
On big instances, there can be lots of not active channels. Some content was shared e.g. one year ago. 
We'd like to archive the channel so that users don't see them in the channel list, but those who actively look for past content would still be able to find somewhere.

**Comment by julienchabanon** [comment]
I have the same issue too. I have no way to tell which channel is archived with the response given by channels.list.

Version
4.4.5

ID de déploiement
v7rPeXSaziWqsjCWF

Version d'Apps Engine
1.30.0

Version de Node
v14.18.2

Mise à jour de la base de données
254 (8 décembre 2023 08:58)

MongoDB
5.0.20 / wiredTiger (oplog Activé)

Détails du commit
HEAD: (2057390bc)
Branche: HEAD
PID
9
