### ISSUE TITLE
Linting Tasks (code consistency)

### ISSUE THREAD

**Issue by gabrielcsapo** [RocketChat/Rocket.Chat#1195]
There is currently no grunt or command line task for linting

**Comment by marceloschmidt** [comment]
Could you please elaborate on that? What's it used for, and how would it be used? Thanks.

**Comment by gabrielcsapo** [comment]
@marceloschmidt This is just to help with code standards and to be added to the pull request builder.

**Comment by gabrielcsapo** [comment]
@marceloschmidt http://eslint.org

**Comment by geekgonecrazy** [comment]
We are using codeclimate which does this on push.  But it would be nice to have something we could check code quality prior to uploading.

**Comment by kernicPanel** [comment]
Maybe http://pre-commit.com/ can be useful for this.
Did'nt try it, but I plan to use it at work.

**Comment by gabrielcsapo** [comment]
@kernicPanel or we could use (https://www.npmjs.com/package/grunt-githooks)

**Comment by gabrielcsapo** [comment]
closing because #1163 seems to solve this issue.
