### ISSUE TITLE
Sort channel directory listing by newest message

### ISSUE THREAD

**Issue by privong** [RocketChat/Rocket.Chat#11951]
In the "Directory" for a Rocket.chat instance the channels can be sorted by "Name", "Users", and "Created At". Often I'd like to sort by "Last Message" but it's not enabled for that column. Ideally the ability to sort on that column could be added to the directory.

_Edit:_ This would also be useful for folks who are viewing channels in "preview" mode but not actually joining channels.

**Comment by privong** [comment]
Howdy, I just wanted to check in on this. I see that it was targeted for milestone 0.70.0 but 0.71.1 is out. Is there a possibility the feature will be added soon?

**Comment by subham103** [comment]
I would like to work on this issue :p
