### ISSUE TITLE
Bug: lack of space in translations

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat#11969]
### Steps to reproduce:

1.  Add new user to the channel

### Expected behavior:

Lack od space between words.

### Actual behavior:

![user](https://user-images.githubusercontent.com/3521624/45150376-fe6f8900-b1cb-11e8-8af7-16aace8205d4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: MacOS
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by vynmera** [comment]
Could be an i18n issue

**Comment by dzienisz** [comment]
This issue is in a lot of places. I just notices this one.

**Comment by ggazzo** [comment]
hey @dzienisz  which language are you using?

**Comment by dzienisz** [comment]
I use `Polish` language.

**Comment by dzienisz** [comment]
![zrzut ekranu 2018-09-11 o 11 30 11](https://user-images.githubusercontent.com/3521624/45351322-2c7f0f80-b5b6-11e8-8fb1-30d9134ffa1a.png)

more examples, this is Users list window

also "Szukaj ..." where? this text is to long and invisible.

**Comment by rssilva** [comment]
Hey @dzienisz, thanks for find this 🙂

Is the label better now? Translator says that it is but I would like to check with a native speaker! 🇵🇱 

![screen shot 2018-09-11 at 9 56 57 am](https://user-images.githubusercontent.com/2047941/45361688-46662580-b5a9-11e8-9242-448f0ff5130d.png)

**Comment by dzienisz** [comment]
It should be:

`Widocznych 1 z 2 użytkowników`

`użytkownicy` is users in general like `users of computers`
`użytkowników` is more like `there is 5 users`

In Polish you have something like `Gramatical case` - https://en.wikipedia.org/wiki/Grammatical_case#Polish

but in this case the best option is to use `użytkowników`

**Comment by rssilva** [comment]
Closed via #12018
