### ISSUE TITLE
There is useless scroll in private group members view

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#11961]
@dzienisz commented on [Tue Sep 04 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/858)

## My Setup
- Operating System: MacOS
- App Version: 2.13.0

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

![scroll](https://user-images.githubusercontent.com/3521624/45037469-5b99fc00-b05f-11e8-935b-ab5a340564b2.png)
1. There is useless scroll in the app
2. "Polish" translation is unreadable.

### Current Behavior

It scrolls

### Expected Behavior

It shouldn't scroll

**Comment by rssilva** [comment]
Closed by #12102

**Comment by rssilva** [comment]
Damn I thought it was merged
