### ISSUE TITLE
[Urgent] Uninstalling App is impossible :warning: 

### ISSUE THREAD

**Issue by tsukiRep** [RocketChat/Rocket.Chat#11964]
### Description:

Uninstalling an App currently just eats up all the RAM until it can't, then restarts the server (exception). This makes it impossible to update an App!!! :warning: 

### Steps to reproduce:

1. Go to Apps panel
2. Click Delete (what a confusing label)
3. There is no Step 3 as the server is now busy imploding :warning: 

### Expected behavior:

It uninstalls

### Actual behavior:

It goes complete apeshit and begins eating RAM faster than humanly possible :warning: :warning: :warning: 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Ubuntu Server
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3

### Additional context

The App currently installed is incompatible with Rocket.Chat and breaks (throws an exception on construction)

### Relevant logs:

```
Sep 05 18:18:39 chat rocketchat-server.rocketchat-server[4404]: Uninstalling: 28186184-a2eb-4359-9c6f-b20086141085
Sep 05 18:18:39 chat rocketchat-server.rocketchat-server[4404]: The App's persistent storage is being purged: 28186184-a2eb-4359-9c6f-b20086141085
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: <--- Last few GCs --->
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: [4427:0x3d146b0]   371880 ms: Mark-sweep 1516.4 (1598.5) -> 1516.2 (1598.5) MB, 1219.0 / 0.1 ms  allocation failure GC in old space requested
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: [4427:0x3d146b0]   373358 ms: Mark-sweep 1516.2 (1598.5) -> 1516.2 (1567.5) MB, 1477.6 / 0.0 ms  last resort GC in old space requested
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: [4427:0x3d146b0]   374765 ms: Mark-sweep 1516.2 (1567.5) -> 1516.2 (1567.5) MB, 1406.5 / 0.1 ms  last resort GC in old space requested
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: <--- JS stacktrace --->
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: ==== JS stack trace =========================================
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: Security context: 0x3e1750d25879 <JSObject>
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]:     2: get [/snap/rocketchat-server/1321/programs/server/packages/rocketchat_api.js:4768] [bytecode=0x23430fed3899 offset=68](this=0x242946034ce1 <Object map = 0x6375afb8021>)
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]:     3: action(aka _internalRouteActionHandler) [/snap/rocketchat-server/1321/programs/server/packages/rocketchat_api.js:196] [bytecode=0x2c22563d8fb9 offset=193](this=0x242946034ce1 <Object map = 0x6375afb8021>)
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]:     4: _ca...
Sep 05 18:22:02 chat rocketchat-server.rocketchat-server[4404]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Sep 05 18:22:02 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=134/n/a
Sep 05 18:22:02 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Unit entered failed state.
Sep 05 18:22:02 chat systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
```

**Comment by SupportIsImport** [comment]
+1

**Comment by siccsipper** [comment]
j ♥ j

**Comment by geekgonecrazy** [comment]
Which app are you trying to delete that this happens with?

**Comment by tsukiRep** [comment]
@geekgonecrazy This one: https://github.com/vynmera/Rocket.Chat.WordFilter
It seems some module is incompatible (>nodejs)

**Comment by tsukiRep** [comment]
@kaiiiiiiiii >Was it installed before the upgrade to 0.69.x?

ye s

**Comment by rodrigok** [comment]
@tsukiRep how many records you think this app had saved in the storage?

Cuz when you remove an app it removes the stored items and our remove method copy all the records to a trash collection [here](https://github.com/RocketChat/Rocket.Chat/blob/c98ab40f06fb22067f4d50dd95a7247644a3a6ed/packages/rocketchat-lib/server/models/_BaseDb.js#L277) and that load can cause this issue.

The app's storage should not use the trash collection, we will fix this.

**Comment by reetp** [comment]
Haa this been fixed as of 0.70.4 ?

**Comment by reetp** [comment]
Just a thought but I wonder what the hardware specs of the machine were? CPU/RAM ?

**Comment by d-gubert** [comment]
Closing this since we've had quite a few releases already and there hasn't been any new reports of this problem.

Feel free to reopen if you're still experiencing the issue!
