### ISSUE TITLE
Environment variables are not working

### ISSUE THREAD

**Issue by umardraz** [RocketChat/Rocket.Chat#11968]
Hello

The environment variables are not working specially ADMIN_USER, MAIL_URL, here is my command to launch rockat.chat container.

```
docker service create \
--name umar \
-l traefik.backend=umar \
-l traefik.frontend.rule=Host:umar.example.com \
-l traefik.port=3000 \
--network mynetwork \
-e MONGO_URL="mongodb://10.0.200.130:27017/umar" \
-e ROOT_URL="https://umar.example.com" \
-e MAIL_URL="smtp://smtpauth:2vddkdi@smtp.example.com:25/" \
-e ADMIN_USER="admin" \
-e PASSWORD="2vddkdi" \
-e ADMIN_EMAIL="umar@umardraz.com" \
rocketchat/rocket.chat
```

with the above command container successfully launched but on first launch the installation wizard still asking admin username, password etc. The MAIL_URL is also not worked.

Would you please help me that what I need to do to fix this?

**Comment by dbluxo** [comment]
You have to use:
ADMIN_USERNAME
ADMIN_PASS
SMTP_Host
SMTP_Port
SMTP_Username
SMTP_Password

**Comment by umardraz** [comment]
HI dbluxo

Thanks, is there any list available for all the possible envioernment variables.?

**Comment by dbluxo** [comment]
Unfortunately not.

You can browse via Rocket.Chat admin GUI and put the mouse cursor over a value and a small window will appears. There you can find the requested environment value.

For some values you have to inspect the Browser, as I described here:
https://forums.rocket.chat/t/how-to-set-ldap-settings-using-environment-variables/1678/3?u=dbluxo

**Comment by reetp** [comment]
@rocket-cat close
Closing notabug.
