### ISSUE TITLE
Admins from LDAP group

### ISSUE THREAD

**Issue by hameno** [RocketChat/Rocket.Chat#1196]
It should be possible to make users that are member of a configured group to be admin, this should prevent #1066
##

**Comment by Megatronic79** [comment]
+1

**Comment by JT089** [comment]
+1 would love that feature too!

**Comment by rikmendes** [comment]
would love this feature too !! +1

**Comment by fadanner** [comment]
+1 would be even cooler with the possibility to link ldap groups to global roles, not only for the adminrole

**Comment by tonylixu** [comment]
would love this feature too !! +1

**Comment by mxmo0rhuhn** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=27601602)](https://www.bountysource.com/issues/27601602-admins-from-ldap-group?utm_source=27601602&utm_medium=shield&utm_campaign=ISSUE_BADGE)
Amazing feature that we would need! Maybe even with [support for a more fine grained system](https://github.com/RocketChat/Rocket.Chat/pull/8942)

**Comment by vsestranny** [comment]
@engelgabriel I see you've set up a bounty for this, and you're a team member, a head honcho even, but is there a point in applying? I could've done this issue back in '17 when I first noticed it, as I've collected enough LDAP knowledge, but then I got cold feet seeing some 50+ PRs unattended for months. Fast forward a year, and the amount of stale PRs more than doubled. Sooo should I keep RC in mind when I come back in another year?

**Comment by wreiske** [comment]
I would like to work on this. I can get started this weekend, I already have some code working that we use internally for our LDAP / AD server. 

@engelgabriel are you cool with me starting a pull-request for this? I don't want to start something if there are other pull-requests out there that may affect this. I can get this done over the weekend.

**Comment by wreiske** [comment]
Pull request is in. #14278
