### ISSUE TITLE
Backup database in snap and migrate

### ISSUE THREAD

**Issue by optimistic5** [RocketChat/Rocket.Chat#11977]
I want to get rid of snap.
I have RocketChat 0.69.0 installed via snap on Ubuntu 17.10.
Is it possible to backup database and use it on new RocketChat installed in manual way on [CentOS](https://rocket.chat/docs/installation/manual-installation/centos/)?
What is the steps?
Thanks.

Can I use for backup [this manual](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-backup-my-snap-data)?
How I can deploy this database on new RocketChat?

**Comment by piotrkochan** [comment]
Backup rocket database first, remove everything, deploy in any way you want, restore database and run rocket chat.

**Comment by optimistic5** [comment]
Ok, I did backup of database with [this manual](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-backup-my-snap-data)
Now I have this file on my new server when the new empty RocketChat is installed.
**How I can restore database?**
I have [this manual](https://github.com/RocketChat/Rocket.Chat/issues/4297#issuecomment-249336189), but I need more arguments for
`mongorestore ~/backup`
it does not work this way:
```
[root@localhost tsuser]# ls
backup  backup.tgz
[root@localhost tsuser]# mongorestore backup
2018-09-07T12:37:20.803+0300    preparing collections to restore from
2018-09-07T12:37:20.804+0300    don't know what to do with subdirectory "var/snap", skipping...
2018-09-07T12:37:20.804+0300    done
```

**Comment by optimistic5** [comment]
@geekgonecrazy , please help.

**Comment by piotrkochan** [comment]
This is not a support forum. Please follow mongo community forums or Rocket Chat Forum https://forums.rocket.chat/

**Comment by geekgonecrazy** [comment]
Take a look inside backup.  I'm guessing inside is probably a folder called dump.  

If not find path to folder directly containing .json files.  I'll make assumption they are in backup/dump/parties

mongorestore --db rocket-chat backup/dump/parties

Now it should import and the DB be called rocket-chat.

Please move further support questions to our forum: https://forums.rocket.chat
