### ISSUE TITLE
[Bug] list.integrations does not return valid json if script is in place

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#11978]
### Description:

Admins are able to get a list of all integrations by using `/api/v1/integrations.list`. However, if an integration uses a script, which makes use of quotation marks, the API does not return valid json anymore. The quotation marks are not escaped by the endpoint and therefore destroy the structure of the json.

### Steps to reproduce:

1. Create a new integration which uses a script. The script has to include some quotation marks.
2. Get all integrations via  `/api/v1/integrations.list`
3. Verify the structure of the return json

### Expected behavior:

Json should be valid

### Actual behavior:

Json is not valid

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.2

**Comment by MarcosSpessatto** [comment]
@janrudolph can you please share your script? Because I tested here with `incoming` and `outgoing` integrations and with quotation marks and I was not able to simulate the error.

**Comment by janrudolph** [comment]
seems to work with the new version -> close
