### ISSUE TITLE
on MacOS Version Version 2.13.1 is not updating

### ISSUE THREAD

**Issue by kozakjefferson** [RocketChat/Rocket.Chat#11974]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by tassoevan** [comment]
This issue is related to the desktop client, please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
