### ISSUE TITLE
Client extremely laggy when DMs are shown with lots of people

### ISSUE THREAD

**Issue by tjhorner** [RocketChat/Rocket.Chat#11975]
### Description:

At the moment, we have hundreds of people on our Rocket.Chat server. Every single person is shown in my DMs. I have never had a conversation with most of them. When this is the case, the client lags EXTREMELY BADLY. This makes Rocket.Chat essentially unusable, which is very frustrating.

### Steps to reproduce:

1. Have lots and lots of users in your server.
2. Open your server.

### Expected behavior:

I expect Rocket.Chat to remain buttery smooth.

### Actual behavior:

Very laggy. Screenshot of user list:

![image](https://user-images.githubusercontent.com/2646487/45193222-d6028180-b201-11e8-9864-7ce7b4db9498.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System: Ubuntu Server 16.04
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: 8.11.3

### Additional context

One of three things could happen here:
- (Preferred) use lazy loading/reusable list components to make everything smoother
- Limit number of users shown in "Direct Messages" section
- Allow users to get rid of the "Direct Messages" section entirely

### Relevant logs:

n/a

**Comment by ggazzo** [comment]
hey @tjhorner do you now how many dms you have? I will investigate your problem...

**Comment by tjhorner** [comment]
I had 1341 DMs in the list - one for every user in the server.

**Comment by reetp** [comment]
Can the OP confirm if this is still an issue on the latest version 0.70.x ?

**Comment by tjhorner** [comment]
Is there a way to quickly un-hide all the chats I have hidden?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
