### ISSUE TITLE
Use email and name from LDAP for user

### ISSUE THREAD

**Issue by hameno** [RocketChat/Rocket.Chat#1197]
I just logged into rocketchat using my ldap account and notices that neither my name nor email was configured. I also could not find any way to set the email in the ui.

**Comment by Dbzman** [comment]
We noticed this, too. This is especially a problem for us. If we had an email set for the user we could fall back to gravatar for avatars instead of using the currently unstable GridFS or FileSystem storage.

**Comment by marceloschmidt** [comment]
We need someone with experience with LDAP to take on this one. If you are this guy, please let us know! Thanks

**Comment by hameno** [comment]
Okay, what kind of infos do you need? I probably won't be able to code this, but I can surely help with LDAP.

For this you would need to be able to configure both the email field and fullname field which is used in LDAP.

Most common ones:
mail
cn / displayName

Then you would just access those fields on the user object, which you should already have for login purposes, right?

**Comment by Megatronic79** [comment]
Yeah thats right, using the same information passed at logon you could indeed get:

displayName = Users first name and surname
sAMAccountName = Username
mail = Exchange Mail address (for AD)
sn = Surname
givenName = FirstName

**Comment by Megatronic79** [comment]
depending on your enviroment (Active Directory Corporate for instance)
You may also want things like:
description = Job Title
telephoneNumber = Mobile
physicalDeliveryOfficeName = Office location
co = Country

etc..

**Comment by Megatronic79** [comment]
rough example:
ldapsearch -H ldap://ldapserver:389 -x -D "somedomain\proxyuser" -W -b "CN=#name,OU=Users,OU=location,DC=somedomain,DC=com" -s sub -a always -z 1000 "(countryCode=826)" "mail" "displayName" "sn" "co" "givenName" "sAMAccountName" "physicalDeliveryOfficeName" "description" "objectClass"

**Comment by ninja-** [comment]
displayName should be downloaded once while e-mail/e-mail should be updated every time you login

**Comment by gmsecrieru** [comment]
Could you please review #1236 and provide feedback on your particular needs? We certainly can improve this/make it more dynamic, but it's a start.

Thanks!

**Comment by nebulade** [comment]
Not sure if this belongs to that issue and if it even possibly solves that, but currently if one supports ldap login with both username (eg. sAMAccountName) and mail, logging in once with username and then with email, results in **two** distinct accounts. I guess the actual mapping ID should be configurable, and as a default setting "sAMAccountName" (that would allow correct mappings even if a user changes his email or username at the ldap server, but the ldap server provides a unique userId)

**Comment by Dbzman** [comment]
Just as a side note:
We thought that using gravatar could fix our avatar issue but we found out that avatars are always added to RC (downloaded) so this will have no effect there.
