### ISSUE TITLE
CAS ignores username attribute map if "username" field in CAS attributes

### ISSUE THREAD

**Issue by syserr0r** [RocketChat/Rocket.Chat#11972]
### Description:

It appears that when the CAS attributes contain a 'username' attribute the 'username' attribute map is ignored and the 'username' attribute is used instead.

### Steps to reproduce:

1. Have CAS provide attributes such as:
```
first_name: Tony
last_name: Test
full_name: Tony Test
username: tony@test.com
email: tony@test.com
```
2. Have an attribute map in Rocket.Chat such as:
`{"email":"%email%", "name":"%full_name%", "username":"%first_name%.%last_name%"}`
3. Attempt to login-in with a user that does not already exist

### Expected behavior:

User is created with a username of `Tony.Test`, a name of `Tony Test` and an e-mail of `tony@test.com`

### Actual behavior:

User is created with a username of `tony@test.com`, a name of `Tony Test` and an e-mail of `tony@test.com`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Debian Stretch 9.5 (linux x64 4.9.0-8-amd64 kernel)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version:

### Additional context

Fresh Rocket.Chat set-up with snap running behind nginx SSL (commercial SSL certificate)

### Relevant logs:

**Comment by darkounet** [comment]
I have the same problem with CAS 2.0 & Rocket 2.2.0

I'm unable to override the username attribute.

**Comment by pmayer** [comment]
I'm having the same issue and had a quick look at the source. The problem is that during user creation username is always set to result.username – see https://github.com/RocketChat/Rocket.Chat/blob/develop/app/cas/server/cas_server.js#L211

So to fix this it should be overwritten like other int_attrs:

```
// Add username
if (int_attrs.username) {
	_.extend(newUser, {
		username: int_attrs.username,
	});
}
```
