### ISSUE TITLE
Change user without permissions

### ISSUE THREAD

**Issue by M4uRoDev** [RocketChat/Rocket.Chat#11971]
### Description:

The chat administrator has the option to change the user disabled, however, through the mobile application of Rocket.Chat, you can make the same modification of this field, this also results in the web application being frozen and it must be refreshed.

### Steps to reproduce:

It is unnecessary, you should simply try to change your user through the mobile application.

### Expected behavior:

Do not allow to change the user name through the application referring to the configuration parameters of the application.

### Actual behavior:

It does not perform the permissions check and also allows the user to change.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by MarcosSpessatto** [comment]
@M4uRoDev I think this issue has been fixed in [this PR](https://github.com/RocketChat/Rocket.Chat/pull/11955).

CC: @ggazzo

**Comment by MarcosSpessatto** [comment]
@M4uRoDev can you please test it again with the latest version?
