### ISSUE TITLE
.ico files do not have a download option and doesn't display outside of the file list menu

### ISSUE THREAD

**Issue by exts** [RocketChat/Rocket.Chat#11970]
### Description:
For whatever reason, `.ico` images when attached will not display in the chat even as a file to be downloaded.

### Steps to reproduce:

1. Attach a favicon
2. Nothing happens outside of it listing in the Files List section

### Expected behavior:

At least display the download link in the chat logs, especially for desktop users.

### Actual behavior:

Nothing happens, gets added to files list though

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.1
- Operating System: Linux x64 4.4.0-1066-aws
- Deployment Method: n/a
- Number of Running Instances: 1
- DB Replicaset Oplog:  (I'm not the server admin, but if you had all this info in the Info section... it would be so much easier o tell you)
- NodeJS Version: (I'm not the server admin, but if you had all this info in the Info section... it would be so much easier o tell you)
- MongoDB Version: (I'm not the server admin, but if you had all this info in the Info section... it would be so much easier o tell you)

**Comment by tassoevan** [comment]
@exts Could you please check if this issue still holds at the latest version? I couldn't reproduce it.

**Comment by exts** [comment]
looks like this is fixed

**Comment by tassoevan** [comment]
Thanks a lot!
