### ISSUE TITLE
Add "Unread on top" as in Rocket.Chat.ReactNative / Slack

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat#11980]
Please add `All Unreads` / `Unread on top` feature.

I tried https://github.com/RocketChat/Rocket.Chat.ReactNative and there is `Unread on top`:
![screenshot_2018-09-06-15-04-01-461_chat rocket reactnative](https://user-images.githubusercontent.com/1219067/45212444-34c50b00-b295-11e8-84f6-ac7813f38bb6.png)

Slack example: 
![slack example](https://user-images.githubusercontent.com/1219067/44707579-27de3580-aaa5-11e8-9e06-d2a47f0b78d6.png)

**Comment by tuxmartin** [comment]
@ggazzo yes, it looks great!

Thank you.

**Comment by tuxmartin** [comment]
Is possible to add feature `Unread on top` to the [Android app](https://github.com/RocketChat/Rocket.Chat.Android)?

In desktop client `Unread on top` works good.

**Comment by anweshknayak** [comment]
Can I try this one?

**Comment by ggazzo** [comment]
sure @anweshknayak...
@tuxmartin I'm not on charge of this project but I will ask them to implement, you can use https://play.google.com/store/apps/details?id=chat.rocket.reactnative until there...

**Comment by filipedelimabrito** [comment]
Just an update: It is present on native Android app now (since 3.4.0 version).

@tuxmartin 
c/c @ggazzo
