### ISSUE TITLE
encryption on the application

### ISSUE THREAD

**Issue by almi9** [RocketChat/Rocket.Chat#11983]
Hi

I have questions about security
1- Is the files encrypted when you will send it to other users?
2- Is all conversation is encrypted automatically? including groups and etc 

Thank you

**Comment by vynmera** [comment]
you can use            otr
ok

**Comment by almi9** [comment]
OTR is running if and only if you enable it, is there any way to make it work always? and is there another way to encrypt the messages on the system?

**Comment by localguru** [comment]
File transfer on OTR is totally broken and NOT encrypted.

**Comment by geekgonecrazy** [comment]
This is more of a question then a bug or issue.  Forums are best place for these.  E2e coming this release 😉
