### ISSUE TITLE
Url text displays emojis instead of plain text

### ISSUE THREAD

**Issue by ohmonster** [RocketChat/Rocket.Chat#11989]
### Description:

URLs containing text that corresponds to an emoji display the emoji in both the browser-based and Electron clients.

### Steps to reproduce:

1.  Paste or type a URL in a chat that contains a string corresponding to an emoji code. For example: ``````
http://myFakeLinkedInUrl/url:li:page``` or ```http://myFakeLinkedInUrl/urn%3Ali%3Apage```

### Expected behavior:

You expect to see the URL in clear text

### Actual behavior:

Emojis are displayed where the text can be mapped to an emoji
![image](https://user-images.githubusercontent.com/13444623/45240785-867a8f00-b2af-11e8-95b8-3250f142f4f5.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.69.0
- Operating System:  Linux
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8..3
- MongoDB Version: 

Note: I could also reproduce this  on open.rocket.chat -- 0.69.1

![image](https://user-images.githubusercontent.com/13444623/45240766-719dfb80-b2af-11e8-81fa-f5350b144d45.png)

**Comment by reetp** [comment]
Following 15882 this docs seem like a potential security issue.

I have just tested it on 2.2.1 and can't seem to get it to happen.

Can anyone demonstrate this still occurs?

**Comment by MartinSchoeler** [comment]
Should be fixed on the latest release, if not, please open a new issue with updated details. Thanks!
