### ISSUE TITLE
Provide Flatpak packages

### ISSUE THREAD

**Issue by Wetrain** [RocketChat/Rocket.Chat#11988]
I noticed this project supports Snap and Bundle downloads, it would be nice to also support Flatpak distribution. 

Instructions on how to package can be found here:

https://flatpak.org/

**Comment by geekgonecrazy** [comment]
Has flatpak started being used for server packages?  Seems to be missing ability to start a daemon

**Comment by Wetrain** [comment]
@geekgonecrazy It is primarily being used to distribute desktop applications, but you should be able to start a daemon after installation?

**Comment by geekgonecrazy** [comment]
From my understanding this would fall on user to manually create.

We'll have to keep an eye on development here and see if becomes a bit more friendly to server applications.

I like flatpaks, so I think would be cool to see

**Comment by Wetrain** [comment]
@geekgonecrazy I'm not quite sure i understand the issue here, applications like Slack can be packaged via Flatpak, so i assume the functionality needed is there?

**Comment by geekgonecrazy** [comment]
@wetrain our desktop app is already packaged as a flatpak.  https://www.flathub.org/apps/details/chat.rocket.RocketChat

This repo is for the server side.  Going to go ahead and close then since it’s a flatpak already :)
