### ISSUE TITLE
Cannot update Rocket.Chat+ from 2.12.1 to 2.13.1 on macOS High Sierra

### ISSUE THREAD

**Issue by jshih7** [RocketChat/Rocket.Chat#11990]
## Operating System Details
macOS High Sierra - Version 10.13.6

## Steps to Reproduce
1. Be on version 2.12.1 of Rocket.Chat+
2. Go to About -> Check For Updates (if it doesn't prompt update on restart)
![image](https://user-images.githubusercontent.com/8042780/45244600-8cc83580-b2c6-11e8-8d23-345aa0dad1fe.png)
3. You will get the following dialog:
![image](https://user-images.githubusercontent.com/8042780/45244438-cea4ac00-b2c5-11e8-8d70-c71b9cdde31f.png)
4. Click "Install Update", then "OK" in the following dialog:
![image](https://user-images.githubusercontent.com/8042780/45244456-e2501280-b2c5-11e8-9ada-fa74bab06750.png)
5. It will instantly say that update has been downloaded:
![image](https://user-images.githubusercontent.com/8042780/45244465-ec721100-b2c5-11e8-8ca4-dc2ef6c2d2fa.png)
6. Click "Install Now". This will close RocketChat, but no additional dialog will appear showing installation progress
7. Restart RocketChat
8. RocketChat may prompt to update again to 2.13.1 from 2.12.1, or if not, check About. It will still be on 2.12.1, not 2.13.1.
![image](https://user-images.githubusercontent.com/8042780/45244590-82a63700-b2c6-11e8-8122-10aa785d1af7.png)

## Expected Behavior
1. After step 6 above, RocketChat should show some sort of installation progress, and notify you when the new update has been installed.
2. After installation, you should not get any dialog telling me to update from 2.12.1 to 2.13.1 again
3. About should show that RocketChat+ is on 2.13.1 after the update

**Comment by himpierre** [comment]
Known issue. Have a look here https://github.com/RocketChat/Rocket.Chat.Electron/issues. You have to uninstall 2.12.1 first.

**Comment by kaiiiiiiiii** [comment]
As @himpierre said, wrong repository mate :)

//CC: @TwizzyDizzy
