### ISSUE TITLE
Message Action template logic bugs

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#11994]
See template here:
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-message-action/client/messageAction.html

The render logic includes a number of conditions, that in my opinion are branching on the wrong attributes. Because all conditions are `if` and there's no `else`, multiple conditions could be true, leading to multiple buttons being rendered.

There's two main problems:

1) if `msg_in_chat_window` is false or undefined, no button is rendered.

2) If an action object contained all of `image_url`, `url`, `msg_in_chat_window`, `text`, you would get four buttons.

Obviously that's something the action sender should be mindful of, but the template should also help to avoid display errors.

In my usage, I was setting `msg_in_chat_window` as default true for all actions, to avoid the first issue, but then I would get two buttons if I also included a `url`.

**Comment by timkinnane** [comment]
@ubarsaiyan ☝️

**Comment by ubarsaiyan** [comment]
@tim.kinnane IMO some checks should be performed on the attributes before they are sent I think. If the button contains all the attributes then what should be the expected behaviour?

**Comment by timkinnane** [comment]
On point 1, I would consider that more of a bug than an opinion. It seem the implementation is missing for handling `msg_in_chat_window` other than true.

On point 2, it's a matter of handling potential display errors at one point, instead of offsetting them to the many developers who create the sent objects to each solve in their own way.
There's already a high load to understand, for usability, we should do whatever possible to reduce it.

My suggestion:

```
if url
  <a>
    if image_url <img>
    if text <span>
  </a>
else
  <button>
    if image_url <img>
    if text <span>
  </button>
```

Per above, only one button can ever be rendered, but it might include text AND a button, instead of the current logic which allows only one or the other (or renders two buttons if both included).

**Comment by VeluneBoYeah** [comment]
Hey,
The fix mentioned above is not solving problem number one.
If `msg_in_chat_window` is false, the button is not rendered.

What we're trying to achieve is the option to communicate with the bot with GUI without the message getting into the chat window as described here:

> msg_in_chat_window: (Required with msg) Indicates where the msg is to be sent. If true then it will go into the chat window. **If false then it will be sent back to the bot but not appear in the chat window**. (Boolean)

(source: https://github.com/WideChat/Rocket.Chat.Android/wiki/Buttons-Inside-Attachment-Object-Spec)
Atm, this functionality is missing.

---
Another option that can be implemented instead of the functionality mentioned above is that the URL will make a POST call in the background and not necessarily just open another website.

**Comment by engelgabriel** [comment]
We are refactoring the whole UI in ReactJS and started to use the UIKit for message action rather than the action buttons.
