### ISSUE TITLE
why bundle has fewer files than tar.gz ? how is bundle package generated

### ISSUE THREAD

**Issue by mamashuodedui** [RocketChat/Rocket.Chat#11997]
why bundle has fewer files than tar.gz ? how is bundle generated, thanks a lot

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
