### ISSUE TITLE
app jitsi /jitisi instead of /jitsi

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#12000]
### Description:

I guess this was just a typo but the slash command jitsi ist currently jitisi. Note the extra "i".

cheers
t.

**Comment by kaiiiiiiiii** [comment]
Please write @rodrigok a message, as he's the owner of the App. This has nothing to do with the server component.

// CC: @TwizzyDizzy App Support case, can be closed.
