### ISSUE TITLE
Startup error after 2.13.2 update

### ISSUE THREAD

**Issue by moralesg** [RocketChat/Rocket.Chat#12004]
Hi all,

After the last 2.13.2 update i'm getting an error:
Uncaught Exception:
Error: EPERM: operation not permitted, rename

It happens renaming window-state-main.json.__new__ to window-state-main.json

Full stack trace in the attached image
![rocketchatstartuperror2 13 2](https://user-images.githubusercontent.com/14352147/45299190-29feb600-b4e1-11e8-8dd5-16320523ea68.png)

I've tried uninstalling RocketChat and removing the RocketChat folder in my user directory.
But the same happens on reinstall (2.13.0 + update to 2.13.2).

Thanks!

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #871](https://github.com/RocketChat/Rocket.Chat.Electron/issues/871) via [**ZenHub**](https://www.zenhub.com/)
