### ISSUE TITLE
Prompted for update from 2.13.1 to 2.13.2, reinstalls 2.13.1

### ISSUE THREAD

**Issue by kmillerdevx3** [RocketChat/Rocket.Chat#12006]
### Description:

When I launch the Rocket.Chat client, I am prompted that there is a new version, 2.13.2. Clicking "Install Now" goes through an install process, but at its conclusion I am still on 2.13.1 and am prompted again.

### Steps to reproduce:

1. Launch 2.13.1 client. Receive prompt for update.
2. Click on "Install Update"
3. When the "Update Ready to Install" dialog appears, click "Install Now"
4. Walk through installer steps. At end, check "Launch RocketChat" option.
5. Receive prompt for update. Verify in "About Rocket.Chat" dialog that 2.13.1 is still installed

### Expected behavior:

I expected that 2.13.2 would be installed, and that it would no longer prompt that the update was available.

### Actual behavior:

2.13.2 is _not_ installed, 2.13.1 remains installed. Application prompts (again) that update to 2.13.2 is available.

### System Information:

- Version of Rocket.Chat: 2.13.1
- Operating System: Windows 7 Professional
- Deployment Method: exe/msi

**Comment by jswolf19** [comment]
This is about the client, which has been reported at the [client repository](https://github.com/RocketChat/Rocket.Chat.Electron/issues/868), already. Please follow over there for developments on the issue, and share any additional information you may have.
