### ISSUE TITLE
[BUG] interface in Russian translation Prune: Prune_Warning_

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat#12001]
### Steps to reproduce:

1.  Go to 'Prune Messages' 

### Expected behavior:

Here's how the message about deleting messages in the English interface looks.
![prune1](https://user-images.githubusercontent.com/34961483/45290799-2bd47380-b4f9-11e8-929b-42d9212cce28.JPG)

### Actual behavior:

Here's how the message about deleting messages in the Russian interface looks.
He is not!
![prune2](https://user-images.githubusercontent.com/34961483/45290819-3262eb00-b4f9-11e8-8ed1-f55b7fa6bc12.JPG)
### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Ubuntu 16.04.5 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3

### Additional context

Also there is no processing of keys in the Russian translation:
 "Prune_Warning_before": "This will delete all %s in %s before %s.",
 "Prune_Warning_after": "This will delete all %s in %s after %s.",
 "Prune_Warning_between": "This will delete all %s in %s between %s and %s.",

**Comment by localguru** [comment]
This happens an all non EN localizations, see #12130.
