### ISSUE TITLE
Error when minimize or maximize the window

### ISSUE THREAD

**Issue by DougTrajano** [RocketChat/Rocket.Chat#12007]
See the picture attached to understand the issue.

It's happens when we minimize or maximize the window. I updated to version 2.13.2 today. The issue began after I did it.

![erro](https://user-images.githubusercontent.com/8703022/45302611-26bbf800-b4ea-11e8-9b31-815027d9a770.jpg)

**Comment by moralesg** [comment]
same as #12004

**Comment by ggazzo** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #870](https://github.com/RocketChat/Rocket.Chat.Electron/issues/870) via [**ZenHub**](https://www.zenhub.com/)
