### ISSUE TITLE
rooms.cleanHistory not working

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#12017]
### Description:
 Hi guys
I have a user called A and want to prune direct message between A and user X when send `clear` command. I'm using `RocketChat.JS.SDK` but I got this error:

```
[API] POST: rooms.cleanHistory {"roomId":"3WHTgSjKFPKex6EHuv4F88GsRJbdPxpJAa","latest":"2020-12-09T13:42:25.304Z","oldest":"2016-12-09T13:42:25.304Z"}
{ success: false,
  error: 'Not allowed [error-not-allowed]',
  errorType: 'error-not-allowed' }
[API] POST error (rooms.cleanHistory): { success: false,
  error: 'Not allowed [error-not-allowed]',
  errorType: 'error-not-allowed' }

```
this is my code:

```
await api.post("rooms.cleanHistory", {
            roomId: message.rid,
            latest: "2020-12-09T13:42:25.304Z",
            oldest: "2016-12-09T13:42:25.304Z"
        });
```

Can you guide me to fix this?

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0-develop
- Operating System: Linux
- Deployment Method: local
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 9.0.0
- MongoDB Version:

**Comment by ggazzo** [comment]
hey @mnlbox we have a "bug/feature" here
nowadays this method only work if you have this permission activated `clean-channel-history` 
![image](https://user-images.githubusercontent.com/5263975/45467110-3c9d0900-b6f4-11e8-85cb-8b54714fa902.png)

by default only admins have this permission... as I said its a kind of bug... or feature.. I will work on that

**Comment by vynmera** [comment]
@ggazzo Not a bug at all, this is how it always was, even before my PR ..? They need this permission to be able to prune a channel, else any user can just destroy any channel. If you want to give more roles this permission, give those roles the permission (or for example, give room owners the permissions)

**Comment by geekgonecrazy** [comment]
Looks like this one is working as intended.  Just needs missing permission.  Going to go ahead and close
