### ISSUE TITLE
[QUESTION] When i'm deleting users from MongoDB manually, the number of users on the channel remains the same

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat#12016]
- Version of Rocket.Chat Server: 0.69.1
- Operating System:  Debian 8
- Deployment Method:   tar
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.2.21

I needed to remove several users from the RocketChat manually, i.e. not using the RC capabilities. In MondoDB I found these users, their direct messages and deleted them. There are no users anymore, there are no direct messages, everything is ok. But in the channel users list there is an incorrect number of users. That is, users 12 (plus switched off "rocket.cat", but shown are 16 (as it was before, before removal).
How to fix this?

This is the number of users in the settings:
![2018 09 11-12-39-55](https://user-images.githubusercontent.com/18574776/45351965-124a2f00-b5c0-11e8-9a5b-8a7ad8c15968.png)

This is the number of users in the channel userlist:
![2018 09 11-12-40-46](https://user-images.githubusercontent.com/18574776/45351979-16764c80-b5c0-11e8-9212-8442f7c08cbd.png)

**Comment by reetp** [comment]
This is a support issue.
You should remove users via admin or the API and not manually in the DB unless you really know what you are doing. You may well have corrupted your DB.
Please raise an issue in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close

**Comment by reetp** [comment]
Note this may refer be a possible solution:
https://github.com/RocketChat/Rocket.Chat/pull/10700
