### ISSUE TITLE
Auto log out in browser

### ISSUE THREAD

**Issue by cloudsandladders** [RocketChat/Rocket.Chat#12010]
### Description:

Rocketchat from the browser auto logs you out when you leave and return.

### Steps to reproduce:

1. Go to server via browser and log in
2. After logging in, refresh the page or close tab and open a new tab and attempt to access server
3. You are now logged out

### Expected behavior:

Should stay logged in even if open new tab or refresh page

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Ubuntu 16.04.4 x64
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3

**Comment by cloudsandladders** [comment]
I don't know if it has something to do with the 'Forget User Session on Window Close' setting?

**Comment by piotrkochan** [comment]
Do you have "Forget User Session on Window Close" enabled?

**Comment by cloudsandladders** [comment]
@piotrkochan it's disabled

**Comment by reetp** [comment]
Any update on latest version of Rocket - currently 0.74.2 ?

If not we should close for lack of more information

**Comment by cloudsandladders** [comment]
I changed VSP hosters and then it stopped.
