### ISSUE TITLE
Polish translations in prune messages panel

### ISSUE THREAD

**Issue by moonwolf-github** [RocketChat/Rocket.Chat#12015]
### Description:

There are missing / wrong translations in prune messages panel:

![image](https://user-images.githubusercontent.com/10871358/45351769-36edd900-b5b7-11e8-8266-3b33b8ec3a2f.png)

There are 3 problems here:

* missing translation for "prune"
* mising translation in red box
* weird translation of button ("Suszona śliwka" means "dried plum" :D )

### Steps to reproduce:

1.Open prune panel

### Expected behavior:

See all text translated correctly

### Actual behavior:

Missing / wrong translations

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0

**Comment by Zuko** [comment]
If you can, fix it (for everyone) https://rocket.chat/docs/contributing/translating/
