### ISSUE TITLE
FreeBSD Deployment Error

### ISSUE THREAD

**Issue by ButGuc** [RocketChat/Rocket.Chat#12024]
Hello,

I use this document. https://rocket.chat/docs/installation/community-supported-installation/freebsd/

But, I get an error during this process. 

> npm install --clang=1 bcrypt

Output:
```
npm ERR! code Z_DATA_ERROR
npm ERR! errno -3
npm ERR! invalid distance too far back
```

FreeBSD 10.3
NPM  6.0.1
Node.JS 10.9.0

Thanks.

**Comment by piotrkochan** [comment]
Please post issue at https://github.com/kelektiv/node.bcrypt.js

**Comment by ButGuc** [comment]
@piotrkochan okay but, problem just also in the repo.

**Comment by piotrkochan** [comment]
Try with node 8.* and corresponding npm version (maybe 5.6?)

**Comment by rdnn** [comment]
Working fine on FreeBSD 11.2, however we're running node 8.11.3 and npm to 6.4.0. You might want to try performing a downgrade of node as suggested by @piotrkochan.

```> bcrypt@3.0.0 install /usr/local/rocketchat/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-freebsd-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.0 and node@8.11.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gmake: Entering directory '/usr/local/rocketchat/bundle/programs/server/npm/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /usr/local/rocketchat/bundle/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
gmake: Leaving directory '/usr/local/rocketchat/bundle/programs/server/npm/node_modules/bcrypt/build'
npm WARN saveError ENOENT: no such file or directory, open '/usr/local/rocketchat/bundle/programs/server/npm/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/rocketchat/bundle/programs/server/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.

+ bcrypt@3.0.0
updated 1 package and audited 14082 packages in 41.818s
found 40 vulnerabilities (19 low, 3 moderate, 18 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by MartinSchoeler** [comment]
@ButGuc Please move this to [Rocket.Chat Forums](https://forums.rocket.chat/) Since this is a [community supported installation guide](https://rocket.chat/docs/installation/community-supported-installation/). Thanks!

**Comment by ButGuc** [comment]
I solved the problem using another operating system. thank you for everything.

**Comment by rdnn** [comment]
@ButGuc If you're interested in deploying Rocket.Chat on FreeBSD, I wrote a simple script to [deploy Rocket.Chat on FreeBSD](https://github.com/rdnn/Rocket.Chat-FreeBSD). I've only tested it with FreeBSD 11.2, so I'm not sure if it will meet your needs.
