### ISSUE TITLE
Groups list missed names in Internet Explorer 11

### ISSUE THREAD

**Issue by asand3r** [RocketChat/Rocket.Chat#12028]
### Description:
Groups list displaying without names in condensed mode.
Also, Warning windows and security error occured when Rocket.Chat opening in Internet Explorer 11.

### Steps to reproduce:

1. Open web version in Internet Explorer 11.
2. Switch View mode to condensed

### Actual behavior:

![default](https://user-images.githubusercontent.com/13959303/45407140-39146e00-b671-11e8-988d-64915f8a8f67.png)
![rocket_chat_ie](https://user-images.githubusercontent.com/13959303/45407163-492c4d80-b671-11e8-89ac-3280672b8b46.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: CentOS 7.5.1804
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: disabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

### Relevant logs:

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
Home.aspx
HTML1300: Navigation occurred.
chat.my-company.com
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
Home.aspx
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
chat.my-company.com (227,17)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
chat.my-company.com (228,17)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
chat.my-company.com (229,17)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
chat.my-company.com (231,13)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
chat.my-company.com (235,9)
cssVarPoly: 7ms
SCRIPT5022: SecurityError
c029a6b2088014967102f8efaaf260dc7e0d3df5.js (259,17259)
Loading: true
Exception from Tracker recompute function: undefined
Error: Error setting badge. Message: SecurityError
   at u (https://chat.my-company.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:259:14867)
   at E (https://chat.my-company.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:259:14932)
   at Anonymous function (https://chat.my-company.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:525:16872)
   at e.Computation.prototype._compute (https://chat.my-company.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:43:2346)
   at e.Computation.prototype._recompute (https://chat.my-company.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:43:2599)
   at e._runFlush (https://chat.my-company.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:43:3793) undefined

**Comment by fadanner** [comment]
Same for me, but it isn't restricted to condensed view mode.
Is there any workaround?
Running on Rocket.Chat 0.69.2

**Comment by marz71** [comment]
Any solution for this problem?

**Comment by MartinSchoeler** [comment]
@asand3r Can you test this against the latest release, as I couldn't reproduce this bug in it. Thanks!

**Comment by asand3r** [comment]
@MartinSchoeler We are using 0.70.4 and the problem still appears. I'll check it in 0.71 after release.

**Comment by asand3r** [comment]
@MartinSchoeler Hi, I've installed v0.71.0 and now sidebar menu works fine, thank you. But I still has the warning about accessing from undefined.
![default](https://user-images.githubusercontent.com/13959303/47630226-b0825c00-db50-11e8-9a59-f140a6eab310.png)
![default](https://user-images.githubusercontent.com/13959303/47630278-ddcf0a00-db50-11e8-831a-40b25258567e.png)
