### ISSUE TITLE
REST API - Get groups and channels which user is in

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#12029]
**Is your feature request related to a problem? Please describe.**

My request is about possibility to fetch list of groups and channels user is in, which should be an REST API Endpoint for authorized user like admin.

We really need this functionality to integrate system, where user can select channel or private group which he is contributing to.

These requests are made not using user's token but user with other user token having special role and permissions. I think it would be perfect to create additional permission which could allow some roles to fetch list of all groups and public channels of a user (not messages, just name, _id like in presence api).

**Describe alternatives you've considered**

I tried:

* `groups.listAll` with filter on "usernames" array or "u.username"

Why it does not work? The field "usernames" in mongo is almost always empty even if user joined group (removed in https://github.com/RocketChat/Rocket.Chat/pull/10749), also u.username is static - even if other user created a group, set owner and left group, u.username is still same as before.

* `groups.members`

Why it does not work? Unfortunately it selects only group which caller is in...

* `users.info`

No field containing user groups/channels.

**Describe the solution you'd like**

One of the four:
* `groups.members` - if caller have permission then call internally `findPrivateGroupByIdOrName` without `userId`. The downside of this solution is need to iterate trough every group, call groups.members for them and filter by user.
* `groups.listAll` - if called have permission then add a field containing user list which are in this group. Amost same disadvantage as in groups.members
* `users.info` - I think it would be the best fit - just add additional field with groups and channels if caller have permission.
* new REST endpoints: `users.groups`, `users.channels`?

**Additional context**
Thanks

**Comment by piotrkochan** [comment]
How it goes?

**Comment by simonfoxguitar** [comment]
Same problem for me. I tried users.info with the fields={"userRooms":1} and correct permissions for the calling user. No room data returned.
