### ISSUE TITLE
encrypting in RC

### ISSUE THREAD

**Issue by Prospero14** [RocketChat/Rocket.Chat#12027]
Morning, guys. We gonna use RC as our main messenger, but first we need to know how it is protected, I'm talking about :
1) Encryption (U'r using OTR, isn't it?) 
a) How it is implemented in mobile ver. Is it working? I didn't find any info abt makin' my chat private.
2) Encrypting Mongodb, which is used as our db. Is it difficult to hack ssl?

i'm looking forward for your answer!

**Comment by MartinSchoeler** [comment]
@Prospero14 Please follow @reetp instructions, thanks!
