### ISSUE TITLE
Bug: livechat-agent not seeing incoming livechats Guest-pool

### ISSUE THREAD

**Issue by sebudot** [RocketChat/Rocket.Chat#12033]
Description:
Rocketchat integrated into iframe.
Routing method guest pool.
Accept with No Online Agents: true.
Show Queue List to All Agents: true.

If a livechat-agent  is not on the iframe page when the chat starts he does not see the conversation when he returns to the page in the incoming livechats.

Steps to reproduce:
Routing method guest pool.
Accept with No Online Agents = true.
Show Queue List to All Agents = true.
Change page, start conversation with livechat client.

Expected behavior:
Chats should stay in the incoming livechats queue visibile by all agents assigned to set department even if they logged in after the start/left the page...etc.

Server Setup Information:

    Version of Rocket.Chat Server: 0.69.0
    Operating System: Ubuntu 16.04.4 x64
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: Enabled
    NodeJS Version: v8.11.3

**Comment by renatobecker** [comment]
Hi @sebudot!

I want to suggest you update your server version to our latest version(0.74.3) and then try it again, what do you think?
I was not able to reproduce the issue you described, so it would be good to try it on our latest version.

I'll be waiting for your feedback.
Thanks.

**Comment by sebudot** [comment]
Hi @renatobecker the problem no longer appears in version(0.74.3) .

Thank you !

**Comment by jschirrmacher** [comment]
I still experience the same with 0.74.3 - if agents are not logged in when a livechat starts, they wouldn't see it when they log in.

**Steps to reproduce:**
- Agent 1 is logged in, Agent 2 is not logged in
- A user starts a new livechat
- Agent 1 sees the new livechat but doesn't accept it
- Agent 2 logs in, but doesn't see the livechat

![image](https://user-images.githubusercontent.com/2821879/54698667-f6f04b80-4b2f-11e9-8f00-c097ed7b1c2b.png)
![settings](https://user-images.githubusercontent.com/2821879/54699008-8a298100-4b30-11e9-9434-f19bec5b9794.png)
![settings2](https://user-images.githubusercontent.com/2821879/54699023-8dbd0800-4b30-11e9-898e-5b174b2b2371.png)
![settings3](https://user-images.githubusercontent.com/2821879/54699025-91508f00-4b30-11e9-8204-b4473eef4a64.png)
![settings4](https://user-images.githubusercontent.com/2821879/54699042-957cac80-4b30-11e9-873a-fef32b9f970b.png)
![routing](https://user-images.githubusercontent.com/2821879/54699099-ae855d80-4b30-11e9-836c-fc76a15019ab.png)

**Comment by stevenhfotofix** [comment]
@jschirrmacher We exerience the exact same issue as well, excellent write-up of the problem!

**Comment by renatobecker** [comment]
> I still experience the same with 0.74.3 - if agents are not logged in when a livechat starts, they wouldn't see it when they log in.
> 
> **Steps to reproduce:**
> 
> * Agent 1 is logged in, Agent 2 is not logged in
> * A user starts a new livechat
> * Agent 1 sees the new livechat but doesn't accept it
> * Agent 2 logs in, but doesn't see the livechat
> 
> ![image](https://user-images.githubusercontent.com/2821879/54698667-f6f04b80-4b2f-11e9-8f00-c097ed7b1c2b.png)
> ![settings](https://user-images.githubusercontent.com/2821879/54699008-8a298100-4b30-11e9-9434-f19bec5b9794.png)
> ![settings2](https://user-images.githubusercontent.com/2821879/54699023-8dbd0800-4b30-11e9-898e-5b174b2b2371.png)
> ![settings3](https://user-images.githubusercontent.com/2821879/54699025-91508f00-4b30-11e9-8204-b4473eef4a64.png)
> ![settings4](https://user-images.githubusercontent.com/2821879/54699042-957cac80-4b30-11e9-873a-fef32b9f970b.png)
> ![routing](https://user-images.githubusercontent.com/2821879/54699099-ae855d80-4b30-11e9-836c-fc76a15019ab.png)

Looking at your print screen I can see that the `Accept with No Online Agents` setting is not activated.
