### ISSUE TITLE
Unable to load old livechat history

### ISSUE THREAD

**Issue by dhpowrhost** [RocketChat/Rocket.Chat#12040]
**Is your feature request related to a problem? Please describe.**
We've been in production with Rocket.Chat and using the livechat feature on our website since June 2016. We've been through a lot of updates, and db migrations. The last couple of month however we started to experince that some Livechats cannot be opened. This happens only with returning clients. This made me think that it might be because of the long history of livechats that we have, which has been migrated several times.

**Describe the solution you'd like**
I saw that there has been implemented a prune function for channels. I really would like to have this feature for livechats also. So that i can prune all messages older eg. than one year.

**Describe alternatives you've considered**
Clearing the livechat history directly in mongodb. It seemed impossible since all messages in all channels are in the same colletion.

**Additional context**
Furthermore we have some chats that cannot be closed (because they cannot be opened). Again this is only related to returning customers. It seems that the first time a client opens a livechat and we close it, some times it returns to "Open Livechats" even though it is closed. Then the next time that client opens a livechat you cannot open it.

**Comment by renatobecker** [comment]
Hi @dhpowrhost, are you still facing the issue described in the last part of the issue's description(Additional context)?

**Comment by dhpowrhost** [comment]
We use livechat a lot so we actually decied to reinstall Rocket.Chat and start over on newest version. It resolved the issue, which was probably due to upgrading many times from an early version of Rocket.Chat. Seemed like the data migration was not perfect.
However one issue we still have is that even though we close a Live Chat it does not always dissapear from the active list of livechats. We have to press hide chat. Minor issue, but would be nice that i did hide it self when you close it every time.

**Comment by renatobecker** [comment]
> However one issue we still have is that even though we close a Live Chat it does not always dissapear from the active list of livechats. We have to press hide chat. Minor issue, but would be nice that i did hide it self when you close it every time.

@dhpowrhost, regarding auto-hide Livechat on closing, it's fixed: https://github.com/RocketChat/Rocket.Chat/pull/13824

**Comment by dhpowrhost** [comment]
ok thank you.. i will close this issue
