### ISSUE TITLE
Firefox OS support (manifest.webapp)

### ISSUE THREAD

**Issue by acidicX** [RocketChat/Rocket.Chat#1204]
Hi there,

I've added a manifest.webapp so that you can "install" (add icon to homescreen) the webapp on Firefox OS devices (#1203). Just point the Firefox to https://wherever-you-deployed.tld/manifest.webapp and hit install. This way you have a fullscreen view available, which is great because all current FxOS devices are rather small and the screen space is very limited.

There is one issue though: the file needs to be served with the following HTTP header:
````'Content-type: application/x-web-app-manifest+json'````
See [here](https://developer.mozilla.org/en-US/Apps/Build/Manifest#Serving_manifests)
I don't really know how to do it with meteor's webapp component, which is what Rocket.Chat uses, right? Maybe somebody could help out?

**Comment by rodrigok** [comment]
@acidicX it is working if you request directly to the application, now we are using the NGINX to responde to static files reading them from the disk in our demo server.

@engelgabriel is changing this in the NGINX to fix this in our demo server too.

**Comment by acidicX** [comment]
OK, so far the demo server still answers with ````Content-Type: application/octet-stream````
@engelgabriel did you add it to the nginx config?
Also, is nginx included in the Docker container or does it only use meteor-webapp? Otherwise all Docker users are left out by this solution.

**Comment by rodrigok** [comment]
@acidicX we don't include the nginx in the docker container

**Comment by acidicX** [comment]
Then it would be best if the correct headers were set by meteor-webapp, so that everybody can benefit :+1:

**Comment by engelgabriel** [comment]
@acidicX I've just fixed our DEMO nginx config.

**Comment by acidicX** [comment]
Great! Can you leave the issue open?
As I said above, with newer FxOS versions, you need to trigger the install via JS. Just pointing to manifest.webapp does not work anymore. I'll be working on that shortly.

**Comment by acidicX** [comment]
See pull request #1271
