### ISSUE TITLE
/api/v1/users.delete this API can't able to delete user when a user in specific group or channel

### ISSUE THREAD

**Issue by nilekshdhimer** [RocketChat/Rocket.Chat#12056]
Hi there,

Today I check /api/v1/users.delete API.
I can't able to delete user when a user in a specific group or channel.
When I try to remove a channel first then try to delete a user it works.

Actually what we need, when I delete a user from Rocket Chat it should be automatically removed from all its Groups, Channels, etc.

**Comment by piotrkochan** [comment]
First, check if the user is a last owner of group.

**Comment by nilekshdhimer** [comment]
> First, check if the user is a last owner of group.

What it means?

**Comment by piotrkochan** [comment]
What does it mean, is there can't be group without owner. If you delete user, then group will have no owners. There is a feature request about force delete user https://github.com/RocketChat/Rocket.Chat/issues/11941

**Comment by nilekshdhimer** [comment]
> What does it mean, there can't be group without owner. If you delete user, then group will have no owners. There is a feature request about force delete user #11941

Is there any API which allows me to delete automatically rooms or channels which is related to a particular user?

**Comment by piotrkochan** [comment]
There is existing feature request I've posted about API to get user channels and groups https://github.com/RocketChat/Rocket.Chat/issues/12029

But right now, the only thing You can do is login as user, delegate ownerships do other users or delete groups manually and finally delete this account via API or Admin Panel.

**Comment by nilekshdhimer** [comment]
> There is existing feature request I've posted about API to get user channels and groups #12029
> 
> But right now, the only thing You can do is login as user, delegate ownerships do other users or delete groups manually and finally delete this account via API or Admin Panel.

Thank you so much, my friend. I am waiting for this feature.
