### ISSUE TITLE
[BUG] Exception changing own user language

### ISSUE THREAD

**Issue by flaviogrossi** [RocketChat/Rocket.Chat#12057]
### Description:

Changing own user language when in a channel raises this exception in the browser:

```
Uncaught TypeError: Cannot read property 'username' of undefined
    at reloadUsersFromRoomMessages (messagePopupConfig.js:14)
    at messagePopupConfig.js:48
    at Tracker.Computation._compute (tracker.js?hash=0e8b…c26b49ee62196af:339)
    at new Tracker.Computation (tracker.js?hash=0e8b…c26b49ee62196af:229)
    at Object.Tracker.autorun (tracker.js?hash=0e8b…c26b49ee62196af:613)
    at messagePopupConfig.js:40
    at maybeReady (meteor.js?hash=c9a34…3fa1763b624436a:871)
    at HTMLDocument.loadingCompleted (meteor.js?hash=c9a34…3fa1763b624436a:883)
toolbar.js:42 Uncaught TypeError: Cannot read property 'set' of undefined
    at getFromServer (toolbar.js:42)
    at later (modules.js?hash=98bf…92cc52fcc2c57:72261)
    at modules.js?hash=98bf…92cc52fcc2c57:72198
```

this happens because [this method](https://github.com/RocketChat/Rocket.Chat/blob/db6aa025d0ce48e07ae58f94ed406d58867abcfc/packages/rocketchat-ui-message/client/popup/messagePopupConfig.js#L6) returns undefined.

### Steps to reproduce:

1. Go to a channel
2. change own user language, the page will reload after the setting is saved
3. the exception above is shown and the ui language is not change (but it is in the database)
4. repeat the same procedure with no channel selected, everything works correctly

### Expected behavior:

no exceptions

### Actual behavior:

exception

### Server Setup Information:

- Version of Rocket.Chat Server: develop branch at commit 02ff65c788134254df9caf0e3640c0b3ed741da1
- Operating System: Linux
- Deployment Method: from sources
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.10

**Comment by MarcosSpessatto** [comment]
@flaviogrossi can you please update you server with the latest version and try again? I think the issue has been solved.

**Comment by flaviogrossi** [comment]
Yes, it seems to be fixed now. Thanks!
