### ISSUE TITLE
/api/v1/users.update this API always return true status if I pass wrong user id

### ISSUE THREAD

**Issue by nilekshdhimer** [RocketChat/Rocket.Chat#12054]
Hi there,

Today I try to call **/api/v1/users.update** this API and it always give me a result with true status.
When I try to call this API with valid user id it will **return true with user info**.
But when I try to call this API with invalid user id, it will return the only **status true without user info**.

Instead of true API should be return false with a valid message like "Invalid user id" or "User id is not exist".

**Comment by MarcosSpessatto** [comment]
Hey @nilekshdhimer, I tried simulate this behaviour and I was not able, could you please share the http request that you are sending to the server?
