### ISSUE TITLE
Custom user rights per Auth method

### ISSUE THREAD

**Issue by menardorama** [RocketChat/Rocket.Chat#12065]
**Describe the solution you'd like**

As a RocketChat admin, I would like to be able to open my rocketchat instance to people who are not working for my company.

I am using for example SAML auth for internal user and I would like to be able to add other auth method like Google, Github or any Oauth2 provider and flag them as "external" users.

It is important to avoid IT requests made by internal users to create user accounts for external people, but I don't want that external users could create channels....

External flag should be set per Auth mechanism.

**Describe alternatives you've considered**

Another solution would be that regular users can invite somone in a channel using only an email address not already registered. This feature is for now reserved to Admins in the Administration - Users area.

Don't hesitate to ask me more detail, I don't know if it's already possible in some ways. But for now I didn't find anything.

Thanks and wonderful product

**Comment by rasos** [comment]
Ideally we could map SAML or LDAP groups to roles or closed chat groups. 
So a new account member of the `staff_group` would be automatically be onboarded to 3 internal groups and would get some additional rights mapped in the role `staff`. 
I do not have any idea how to map this, but we also have this need.

**Comment by menardorama** [comment]
The ideal solution for us would be the gitlab model.
We define internal auth mecanism and external auth mecanism.
External should have no rights, internal users could invite external users to channels

**Comment by trigrab** [comment]
@menardorama your idea is great. But the more universal feature would be as @rasos suggested. You could also configure it to fit your needs. But others also can configure it to their needs.
I really would like to see this as a new feature.
