### ISSUE TITLE
Upload of .sketch file fails as not supported type altough application/zip is a valid type for file upload

### ISSUE THREAD

**Issue by nerrehmit** [RocketChat/Rocket.Chat#12062]
RocketChat Version: 0.66.3

Upload of a file with the .sketch ending fails altough uploads of zip files is allowed.

The uploads fail with either Firefox or Google Chrome in Ubuntu 16.04

All allowed uploads from the settings: 
image/*,audio/*,video/*,application/zip,application/gzip,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,application/x-zip

If I rename the file "something.sketch" to "something.zip" the upload works, however this is not practical for our users wanting to share those files.

@TwizzyDizzy suggested opening a new issue referencing two similar issues from the past:
#11387 
#7462

Kind regards
Tim

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
