### ISSUE TITLE
Resize sidebar

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat#12066]
It would be interesting if the Rocket.Chat web/desktop app gives to the user the ability to resize the sidebar. Something like this:

<img width="1020" alt="screen shot 2018-09-14 at 11 25 55" src="https://user-images.githubusercontent.com/11776825/45556216-1de06480-b811-11e8-817b-efe5f2cf1463.png">

**Comment by Pitstopper** [comment]
It would be amazing! This functionality is very lacking.

**Comment by reetp** [comment]
As a feature request this should now be opened in the forums:
https://forums.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close

**Comment by filipedelimabrito** [comment]
Moved to  https://forums.rocket.chat/t/resize-sidebar-web-app/2680
