### ISSUE TITLE
Set Announcment API is missing for private channels

### ISSUE THREAD

**Issue by mrminecart** [RocketChat/Rocket.Chat#12064]
The rest api does not include an endpoint for setting the announcement of a private channel.

for my application I wish to be able to set the announcement of a room from a custom application. Although I can edit other room details I can not do this for announcements.

It may be that this already exists but it does not exist in the docs if that's the case.

Thanks

**Comment by MarcosSpessatto** [comment]
@mrminecart [here it is](https://github.com/RocketChat/Rocket.Chat/pull/11905).
