### ISSUE TITLE
GitHub template files and conventional-changelog configuration files

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#12069]
@RocketChat/core 

While reviewing some old configuration files at https://github.com/RocketChat/Rocket.Chat.Electron, I noticed that it shared the same `.github` directory as the one in this repo. I don't think the `CONTRIBUTING.md` template is actually used and some information is outdated. Also, `conventional-changelog` haven't been used but its configuration files lie there. What can we do to keep everything up to date?

**Comment by tassoevan** [comment]
Also, we need to move `CONTRIBUTING.md` to root. I guess there it is just to be a template of a [CLI tool](https://github.com/rhysd/dot-github).

**Comment by sampaiodiego** [comment]
not really.. github supports it to be in one of following places: project root, `docs` folder or `.github` folder. [source](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

**Comment by geekgonecrazy** [comment]
Should we close this one?
