### ISSUE TITLE
Hipchat import extract error: Error: write after end

### ISSUE THREAD

**Issue by adispi** [RocketChat/Rocket.Chat#12077]
### Description:

when trying to import a decrypted tar.gz from hipchat getting an error extract error: Error: write after end

### Steps to reproduce:

1. download an export from hipchat (56MB file)
2. decrypt the file using openssl
3. test the file using 7zip
4. go to import and choose hipchat tar.gz file
5. browse and select the decrypted file.
6. wait about 3-5 minutes for the windows to refresh itself and go back to browse
7. check the logs and see error extract error: Error: write after end

### Expected behavior:

get a list of users and chats to imports

### Actual behavior:

extract error: Error: write after end

### Server Setup Information:

- Version of Rocket.Chat Server: 
Rocket.Chat Version: 0.69.2
NodeJS Version: 8.9.3 - x64
Platform: linux (ubuntu 18.04)
Process Port: 3000
ReplicaSet OpLog: Enabled
Commit Hash: 7df9818105
Commit Branch: HEAD
Deployment Method: Manual as per https://rocket.chat/docs/installation/manual-installation/ubuntu/
MongoDB Version: db version v3.0.15

### Relevant logs:

Sep 16 07:40:05 chat nodejs-example[11375]: #033[35mHipChat (tar.gz) Importer ➔ warn#033[39m Duplicated instance
Sep 16 07:40:58 chat nodejs-example[11375]: #033[35mHipChat (tar.gz) Importer ➔ warn#033[39m HipChat Enterprise importer doesn't know what to do with the file "emoticons.json" :o { root: '',
Sep 16 07:40:58 chat nodejs-example[11375]:   dir: '',
Sep 16 07:40:58 chat nodejs-example[11375]:   base: 'emoticons.json',
Sep 16 07:40:58 chat nodejs-example[11375]:   ext: '.json',
Sep 16 07:40:58 chat nodejs-example[11375]:   name: 'emoticons' }
Sep 16 07:46:26 chat nodejs-example[11375]: #033[35mHipChat (tar.gz) Importer ➔ warn#033[39m HipChat Enterprise importer doesn't know what to do with the file "metadata.json" :o { root: '',
Sep 16 07:46:26 chat nodejs-example[11375]:   dir: '',
Sep 16 07:46:26 chat nodejs-example[11375]:   base: 'metadata.json',
Sep 16 07:46:26 chat nodejs-example[11375]:   ext: '.json',
Sep 16 07:46:26 chat nodejs-example[11375]:   name: 'metadata' }
Sep 16 07:46:26 chat nodejs-example[11375]: #033[34mSyncedCron ➔ info#033[39m Starting "Generate download files for user data".
Sep 16 07:46:26 chat nodejs-example[11375]: #033[34mSyncedCron ➔ info#033[39m Not running "Generate download files for user data" again.
Sep 16 07:46:26 chat nodejs-example[11375]: #033[34mSyncedCron ➔ info#033[39m Finished "Generate download files for user data".
Sep 16 07:46:26 chat nodejs-example[11375]: #033[34mStreamBroadcast ➔ Auth.info#033[39m prevent self connect undefined:3000
Sep 16 07:50:32 chat nodejs-example[11375]: #033[35mHipChat (tar.gz) Importer ➔ warn#033[39m extract error: Error: write after end
Sep 16 07:50:32 chat nodejs-example[11375]:     at writeAfterEnd (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/readable-stream/lib/_stream_writable.js:288:12)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Extract.Writable.write (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/readable-stream/lib/_stream_writable.js:332:20)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.ondata (_stream_readable.js:639:20)
Sep 16 07:50:32 chat nodejs-example[11375]:     at emitOne (events.js:116:13)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.emit (events.js:211:7)
Sep 16 07:50:32 chat nodejs-example[11375]:     at addChunk (_stream_readable.js:263:12)
Sep 16 07:50:32 chat nodejs-example[11375]:     at readableAddChunk (_stream_readable.js:250:11)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.Readable.push (_stream_readable.js:208:10)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.Transform.push (_stream_transform.js:147:32)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Zlib.callback (zlib.js:474:14)
Sep 16 07:50:32 chat nodejs-example[11375]: #033[35mHipChat (tar.gz) Importer ➔ warn#033[39m extract error: Error: write after end
Sep 16 07:50:32 chat nodejs-example[11375]:     at writeAfterEnd (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/readable-stream/lib/_stream_writable.js:288:12)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Extract.Writable.write (/home/ubuntu/Rocket.Chat/programs/server/npm/node_modules/readable-stream/lib/_stream_writable.js:332:20)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.ondata (_stream_readable.js:639:20)
Sep 16 07:50:32 chat nodejs-example[11375]:     at emitOne (events.js:116:13)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.emit (events.js:211:7)
Sep 16 07:50:32 chat nodejs-example[11375]:     at addChunk (_stream_readable.js:263:12)
Sep 16 07:50:32 chat nodejs-example[11375]:     at readableAddChunk (_stream_readable.js:250:11)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.Readable.push (_stream_readable.js:208:10)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Gunzip.Transform.push (_stream_transform.js:147:32)
Sep 16 07:50:32 chat nodejs-example[11375]:     at Zlib.callback (zlib.js:474:14)

**Comment by rodrigok** [comment]
@adispi could we have access to your export file?

**Comment by adispi** [comment]
do you have a private FTP or a way to contact directly so i will not need to put the file on the internet for all?

**Comment by foto-andreas** [comment]
Any news on this? I am running into the same problem. Sorry, I can not share the import. Tried with and without exported files from HipChat. Private and room chats are in the import. Is there a possibility to do a server side import to check, if its related to the data or connection?

**Comment by Hudell** [comment]
Starting with version 0.74.3, if Rocket.Chat fails to extract import files, you have the option to extract the files on the server and use the extracted folder path when starting the import process.

**Comment by matosc15** [comment]
@Hudell Where would the "option to extract the files on the server and user the extracted folder path when starting the import process" show up? I'm having the same issue where the import process seems to corrupt the hipchat tar.gz file, but I can copy the file and successfully untar it on the server.

**Comment by Hudell** [comment]
Instead of uploading the file, you can paste the extracted folder path on the "File URL" field. It accepts both an URL and a local path. If the path is for a folder on the local system, it will be imported directly.
