### ISSUE TITLE
[NEW] Captcha authorization of users login

### ISSUE THREAD

**Issue by zzeesstt** [RocketChat/Rocket.Chat#12071]
I would like to talk about secure authentication, namely, about captcha.
Is it possible to count on the fact that it might have appeared for authorization? After all, as long as it's not there, the server can not protect itself from bruteforce attacks.
Thx all.
![-1](https://user-images.githubusercontent.com/32969232/45584686-d75a3b00-b8e0-11e8-8bd5-30ab904c21a6.png)

**Comment by reetp** [comment]
Please open a new feature request in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close

**Comment by jamaica23** [comment]
How to join this typing job
