### ISSUE TITLE
Postman Collection

### ISSUE THREAD

**Issue by MarcosEllys** [RocketChat/Rocket.Chat#12076]
## Describe

Hi everyone, i've created a postman collection with all API Requests for help others developers, i would like to share this collection and it possible include your link in the documention (as language specific wrappers), would be a postman button 
![image](https://user-images.githubusercontent.com/6751242/45590283-b3601f00-b90b-11e8-895d-befd7a48c614.png)

**Comment by piotrkochan** [comment]
The link leads to "Run in postman" image itself. Could You share exported collection?

**Comment by ravisublime** [comment]
where is the collection ?

**Comment by ceefour** [comment]
Just info, that Postman has the ability to import OpenAPI v3 files.

OpenAPI v3 can be used to view documentation, and also to generate clients in various languages (and now, including Postman).

**Comment by nurav97** [comment]
@MarcosEllys where is the link
