### ISSUE TITLE
Mentioning users outside private channel

### ISSUE THREAD

**Issue by martinkruusimagi** [RocketChat/Rocket.Chat#12080]
### Description:

Mentioning users outside private channel triggers incorrect mention handling

### Steps to reproduce:

1) Set up 2 users (UserA & UserB) in addition to your own user
2) Create a private channel "test-channel"
3) Add UserA to test-channel
4) Mention UserA within text in test-channel
5) UserA is shown in suggestion field
6) Text is shown in chat area and UserA is notified
7) Mention UserB within text in test-channel

### Expected behavior:

UserB isn't shown in mention suggestion field. If user tag is typed nonetheless, feedback is given that user is not in channel and can't see the message.

### Actual behavior:

- UserB's username is shown in suggestion field.
- Text is posted to chat area with mention tag intact
- No feedback is given that user isn't in channel and can't see the message
- UserB is not notified of the message (correct behaviour)

### Server Setup Information:

- Version of Rocket.Chat Server: RocketChat Cloud version 0.69.2
- Operating System: N/A
- Deployment Method: N/A
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

**Comment by CitizenDev** [comment]
If I understand correctly it seems that UserB is not added to private channel before mentioning. For me it seems like this functionality is intended as such, meaning that simply mentioning someone in the private channel wont make this channel accessible for mentioned user.

**Comment by martinkruusimagi** [comment]
Agreed, the problem is that there is no feedback to the user doing the mentioning. For all intents and purposes, it appears to him/her that the mentioning worked. When in reality nothing was sent to the user who isn't in the channel. This becomes an issue in channels of hundreds of users where you can't check whether the person is in the channel or not. The UI should either not suggest the user or notify the person doing the mentioning that this is the case.

**Comment by Hudell** [comment]
I've discussed about this internally at rocket.chat before, as I personally don't like the current behaviour either, but the reason that it works like it does now, is that the mention is also used as a "send contact" feature.

PR #11030 will add a warning that the user is not on the group and give you a link to invite them.

**Comment by martinkruusimagi** [comment]
I think the solution in #11030 provides adequate feedback for this issue to be solved. I'm closing here as the issue is fixed there.
