### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by mrurale** [RocketChat/Rocket.Chat#12082]
Hi all,
when I try to move my desktop rocket.chat for windows I receive this error
![immagine](https://user-images.githubusercontent.com/43267452/45625142-766f6600-ba8c-11e8-825d-e956026df54b.png)
This issue is present in 2.13.2 version. With previous versions there was not this problem.

Best Regards,

**Comment by jaymk1** [comment]
I'm also having this error with the latest update.

**Comment by tassoevan** [comment]
This issue is related to the desktop client; please open new issues for it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Also, [this should have been fixed](https://github.com/RocketChat/Rocket.Chat.Electron/pull/869) in the 2.13.3 release. Thanks!
