### ISSUE TITLE
Send direct message missing from documentation

### ISSUE THREAD

**Issue by newincpp** [RocketChat/Rocket.Chat#12085]
I'm sorry to re-open this but /api/v1/chat.postMessage is for channel only.  I couldn't found any /api/v1/im.postMessage or equivalent for im/dm in the documentation. if it does exist ? or maybe I should use chat.postMessage ? If yes the "channel" is set as requiered but im dot have any so what should I do ?

_Originally posted by @newincpp in https://github.com/RocketChat/Rocket.Chat/issue_comments#issuecomment-422178148_

**Comment by MarcosSpessatto** [comment]
Hi @newincpp, you can use the `chat.postMessage`([docs](https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/)) or `chat.sendMessage`([docs](https://rocket.chat/docs/developer-guides/rest-api/chat/sendmessage/)).

>  If yes the "channel" is set as requiered but im dot have any so what should I do ?

As you can see in the docs, the `channel` is required in `chat.postMessage` if you don't send the `roomId` parameter, it's one or another, but not both. In case of `chat.sendMessage`, you should only send the `roomId` as `message.rid` payload property.

**Comment by MartinSchoeler** [comment]
@newincpp Closing this issue since @MarcosSpessatto has answered the question. Thanks!
