### ISSUE TITLE
Some times when typing out messages in input the chat input jumps up (adds unnecessary padding) 

### ISSUE THREAD

**Issue by FaizanZahid** [RocketChat/Rocket.Chat#12087]
We are on the latest version of RC as of 17 sep 2018.

As i start typing more message in input box, the screen keeps on jumping and input box height increases for no reason, when i send the msg, it resets to normal height.

![image](https://user-images.githubusercontent.com/9073066/45653830-4302fa80-bad1-11e8-9625-6cf05e60f429.png)

**Comment by micleclickme** [comment]
Same on desktop client

**Comment by piotrkochan** [comment]
Yes, sometimes it happens to me in desktop.

**Comment by gabrielloberg** [comment]
Same here
