### ISSUE TITLE
[BUG] User can get into the chat by viewing admin in embed mode

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12094]
### Description:

![img_0205](https://user-images.githubusercontent.com/551004/45689406-44144600-bb2a-11e8-9dbb-f40f570fc9ed.jpeg)

![img_7170](https://user-images.githubusercontent.com/551004/45689606-d288c780-bb2a-11e8-91ee-ef8ce941cff8.PNG)

### Steps to reproduce:

1. Open the administration panel;
2. Go to Apps option;
3. Open the administration menu again and you'll see an `X` in the same line as Administration;
4. Tap on it;

### Expected behavior:

- It should not allow exiting the admin;

### Actual behavior:

- It's allowing the user to exit the admin;

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Linux

**Comment by localguru** [comment]
What is "embed mode"?

**Comment by rafaelks** [comment]
@localguru Just this query parameter: `?layout=embedded`

**Comment by rafaelks** [comment]
Here's a video from another user reproducing the issue...

![2018-11-10 08 00 25](https://user-images.githubusercontent.com/551004/48300114-d566bf80-e4be-11e8-830f-804f15d59b1b.gif)
