### ISSUE TITLE
Ability to have "Display Name" which is different from username.

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/Rocket.Chat#1209]
This is especially helpful if you are utilizing a corporate LDAP/Active Directory which is setting your username to some obscure alphanumeric combination.
##

**Comment by johnhug** [comment]
+1

**Comment by pioneer903** [comment]
+1 please

**Comment by yonkeltron** [comment]
+1 :+1:

**Comment by graywolf336** [comment]
Would the display name only be for display or would there be any additional uses for it?

**Comment by graywolf336** [comment]
Right now when you register, not sure about ldap, you set your name. Thereafter there was no way to actually change your name and so it was kind of useless. I just opened a pull request, #1211, which adds a field to the account profile where you can change that.

I'm wondering if there should be an option per user or site wide which sets whether the username or the *(real)*name is used on the messages list.

**Comment by Theaxiom** [comment]
@graywolf336 Thank you. :) I think you should be able to reference the display-name and it will auto-complete to the username when doing an @search in chat.

**Comment by graywolf336** [comment]
@Theaxiom I think it currently does search on the display-name (real name, name) when you go to mention someone.

**Comment by Theaxiom** [comment]
@graywolf336 You are absolutely correct, I believe it should be possible to show display names in channel instead of usernames. How feasible is this?

**Comment by graywolf336** [comment]
@Theaxiom Great question, I have not looked into that. I don't imagine it being extremely difficult though.

**Comment by engelgabriel** [comment]
This is a very tricky one, and we may have other old issue about the same feature.

The big thing here is: performance and scalability. Our data model is denormalized in favor of really high performance with low CPU and Memory usage. So we don't have the real names available on every message, as we have the username copied.

But we do understand that in small team, with less than 1k users, we could have a memory map for the real names, and that's what we will do. We will create an setting to turn that on, and recommend that large deployments keep that turn of.

**Comment by richardwlu** [comment]
:+1:

**Comment by LeCoupa** [comment]
:+1:

**Comment by noregard** [comment]
:+1:

**Comment by jdkcn** [comment]
:+1:  I really want this feature.

**Comment by mjensemble** [comment]
:+1:

**Comment by gthorne** [comment]
:+1:

**Comment by tuudik** [comment]
(Y)

**Comment by onigoetz** [comment]
:+1:

**Comment by dandv** [comment]
@engelgabriel: that implementation is what I'd go for, too. Display names change so rarely, that it's not even worth subscribing to the mapping collection.

**Comment by NioTeX** [comment]
:+1:

**Comment by szilardd** [comment]
:+1:

**Comment by gevial** [comment]
:+1: It would be reallly convenient indeed.

**Comment by stemendrew** [comment]
Consider this another comment in agreement that this is needed. I'd work on it myself, if I had the time right now. :( My organization can't migrate to RocketChat, as our usernames are rather inconvenient; most other systems we use employ a description or "Display Name" for a user, rather than their username.

**Comment by mhisoft** [comment]
it is a must have.

**Comment by Mad-Onion** [comment]
This feature is very important for us too.

**Comment by RobertPratico** [comment]
+1

**Comment by NoleHealth** [comment]
+9001

**Comment by twoutlook** [comment]
In Chinese environment, users have much sense on their Chinese name, display name, instead of username.

**Comment by meilinger** [comment]
:+1:

**Comment by BirknerAlex** [comment]
👍

**Comment by massl** [comment]
:+1:

**Comment by StClaus** [comment]
:+1:

**Comment by tuxBurner** [comment]
:+1:

**Comment by ksuquix** [comment]
+1

**Comment by mccunej** [comment]
+1

**Comment by pesovo** [comment]
+1

**Comment by chey** [comment]
:+1:

**Comment by vladimirsazhin** [comment]
👍

**Comment by alexbrazier** [comment]
@engelgabriel Could we just add the name of the user to the database for each message so it will also work with larger organisations. The username is already stored in the db, and in most cases the username is about the same length as the name so it wouldn't take up much more space than already used as most of the data will be the message. I'm happy to give this task a go using this method.
This issue is also brought up here #3453

**Comment by zanshin** [comment]
+1

**Comment by guenth** [comment]
+1

**Comment by csorrick** [comment]
+1

**Comment by alexanda1** [comment]
+1

**Comment by bhbarbosa** [comment]
+1

**Comment by sethiele** [comment]
+1

**Comment by Kenterfie** [comment]
+1

**Comment by schaenzer** [comment]
+1

**Comment by pramithkm** [comment]
+1

**Comment by tomeus** [comment]
+1

**Comment by resetko** [comment]
+1

**Comment by pacid** [comment]
+1

**Comment by himpich** [comment]
Setting "Administration" / "Messages" / "Set a user name to alias in message" to true I now get the "Name" displayed with messages - works for me. Thanks!

**Comment by zanshin** [comment]
I don't see that option. What version of RC are you on @himpich?

**Comment by himpich** [comment]
I am using stable release 0.36.0

**Comment by engelgabriel** [comment]
This has not being implemented on the master branch yet. We are working on it. We want to make in a way that we think is more inline with the architectural design of Rocket.Chat.

**Comment by justinmoninger** [comment]
+1

**Comment by gunph1ld** [comment]
+1

**Comment by gunph1ld** [comment]
You are right. found here https://github.com/RocketChat/Rocket.Chat/pull/3337

**Comment by Theaxiom** [comment]
Shall I close this?

**Comment by zanshin** [comment]
I think you can. It's been working for some time now. :)

**Comment by aventrax** [comment]
Nice to have the "Name" instead of the username on the chat, anyway, we need this on the "mentions" too, otherwise the employees must remember the domain username of the collegues... in some case this is not an option: we use alfanumeric characters, not the name/surname...

Will this be implemented?

**Comment by aggregat4** [comment]
It is great that we can now show real names in messages, but in 0.41.0 where this landed, we can now no longer search for people by their real name. If you switch with CTRL+P or try to mention someone this only matches the username. This reduces usability enormously.

**Comment by d89** [comment]
+1

**Comment by rajsardhara** [comment]
+1

**Comment by MarIfla** [comment]
+1

**Comment by danielluchetta** [comment]
+1

**Comment by sychevsky** [comment]
+1

**Comment by dmanchev** [comment]
Yes please, this is important to have!

**Comment by rajsardhara** [comment]
@dmanchev This is closed already Follow this to enable:
Under message section : Set a user name to alias in message = "True"

**Comment by banholzer** [comment]
this works in messages but does this also work in "roster" ?

**Comment by fletc3her** [comment]
I'd really appreciate this. People choose bizarre usernames. It would be nice if we could tell who everybody was.
