### ISSUE TITLE
Retention policy not working without any new activity 

### ISSUE THREAD

**Issue by qspweissen** [RocketChat/Rocket.Chat#12093]
### Description:

We are currently testing the retention policy and we have the behavior that channels, rooms and private messages are not deleted if there is no new message/activity. When someone writes a new message,  messages older than one day were deleted after 30 minutes. But without a new message, we can see messages older than 1 day.

Settings:
![2018-09-18 12_22_04-conti - quinscape chat](https://user-images.githubusercontent.com/22341283/45681311-7a0ef580-bb3d-11e8-8603-bb68cb9b22ba.jpg)
![2018-09-18 12_22_08-conti - quinscape chat](https://user-images.githubusercontent.com/22341283/45681314-7bd8b900-bb3d-11e8-9ee9-e650aba16e8a.jpg)

### Steps to reproduce:

1. Write a message in a channels, rooms or direct messages
2. Wait one day and do not write any new message
3. After 1 day and 31 minutes you can see older messages
4. If i write a new message and wait 30 minutes, older messages were deleted

### Expected behavior:

I expect that alle messages will be deleteted after 1 day even if no new message was written

### Actual behavior:

![2018-09-18 12_20_33-conti - quinscape chat](https://user-images.githubusercontent.com/22341283/45681278-65caf880-bb3d-11e8-9519-db4398913128.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.1
- Operating System: Debian 9
- Deployment Method: Official Rocket.Chat docker deployment image
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: 3.2

**Comment by fcoppolani** [comment]
I can reproduce the same behaviour on 0.69.2 with 2 running instances

**Comment by localguru** [comment]
+1 same here on 0.69.2

**Comment by vynmera** [comment]
This behaviour is originally on purpose, as added by @ggazzo, and also discussed in #11725, as it adds a performance boost.

However, it's worth the effort to consider making this optional or removing this behavior altogether in favor of faster deletion.

I've been very busy lately, so I don't have much time to pick this up. But if I do have the time, I'll try to pick it up, together with some other related issues.

**Comment by hanynowsky** [comment]
Actually, for our case, we do not care for processing power. So the ideal is to add an boolean option that allows the user to select whether he/she wants to force pruning or keep the standard behavior:

- Standard behavior = Do not trigger pruning unless channel has new activity
- Forced behavior = Prune the channel despite whether there is activity or not.

As a workaround, we are using a crontabbed script that calls the API and posts a dummy message every 24 hours, on every single channel. Which is so ugly :(

Thanks for your reactiveness.

**Comment by ggazzo** [comment]
sorry guys I was/am working with another issues, this week I will fix :)

**Comment by danielslyman** [comment]
+1

**Comment by mddvul22** [comment]
Any progress on this bug?

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15252
