### ISSUE TITLE
Need to build server only for windows

### ISSUE THREAD

**Issue by muditjainsyn** [RocketChat/Rocket.Chat#12100]
I was referring to this guide but the compiled binaries are not available anymore https://rocket.chat/docs/installation/community-supported-installation/windows-server/

I urgently need to install server on windows server 2012. Please help.  I need only web client - apps are not required

**Comment by moonwolf-github** [comment]
Run Linux as virtual machine on this server.

**Comment by muditjainsyn** [comment]
There are some issues installing VirtualBox VM inside a windows VM. System goes into hang state

**Comment by reetp** [comment]
As per the guide this not a supported option.
Please follow up in the forums.
@rocket-cat label add wontfix

**Comment by reetp** [comment]
@rocket-cat close
