### ISSUE TITLE
hipchat migration not working for a file of size 17mb

### ISSUE THREAD

**Issue by sandys** [RocketChat/Rocket.Chat#12110]
hi guys,
we have been constantly trying to migrate a hipchat tar.gz dump of size 17mb . we have tried multiple times - but the uploaded spins for a while and then comes back to the start page. 
nothing seems to have happened.

im doing this on the cloud hosted version of rocketchat.

**Comment by fbuchmeier** [comment]
Hi Sandys,

I tried importing a 450MB file in our on premise instance of Rocket.Chat and I have the same behaviour.

The upload icon spins but nothing happens. I've waited 1h+ on a 40MBit/s upload link.

I do not see any logs (stdout or stderr) in Rocket.Chat either.

Is there any way to debug the import process?

Thanks!

**Comment by sandys** [comment]
+1 on this.
We have pretty much given up on the hipchat import process. I tried it many
times.

Could someone please look into this . This is a blocker for us since we
need to move from hipchat to an alternative.

P.S. I want to import the dump WITH ATTACHMENTS. However, right now I tried
without attachments and it is failing even there.

**Comment by geekgonecrazy** [comment]
Can you check the logs section and see what it shows?

**Comment by sandys** [comment]
We are on the hosted cloud version. I don't think we have access to the
logs ?

**Comment by geekgonecrazy** [comment]
@sandys I have modified my comment with the exception you encountered.  I coordinated with the support team and have grabbed the exception above so the dev team can take a look.

This should help get to the bottom of the issue.

**Comment by sandys** [comment]
hi guys,
really request you test with migrating a hipchat file that includes files. For any of us migrating from hipchat, that's going to be critical

**Comment by slawekp** [comment]
My 126MB file does not import on hosted cloud. I believe lots of people will be coming to Rocket.Chat looking for alternative to HipChat. Having an import working will be crucial for Rocket.Chat in getting new clients.

**Comment by rodrigok** [comment]
@sandys or @slawekp could we have access to your export file?

**Comment by slawekp** [comment]
@rodrigok I'm in contact with Jonas via email. I've already did several runs so you guys can monitor and debug. You can jump into the conversation if you want.

**Comment by rodrigok** [comment]
@slawekp awesome, can you add me to the thread? rodrigo.nascimento@rocket.chat

**Comment by sandys** [comment]
Any update on this ?

**Comment by altafub** [comment]
@rodrigok is there an update on this? Could you please post the thread link here for the benefit of all? As the end of life for HipChat is near, this would help many like us.

**Comment by slawekp** [comment]
@altafub Sorry, can't add anything new. We've given up and moved to Slack. Hope you'll succeed with your migration!

**Comment by Hudell** [comment]
Version 0.74.3 of Rocket.Chat should have fixed all issues with the HipChat import (including this one). If you find any new problem, please register a new issue.
