### ISSUE TITLE
Screenshot feature

### ISSUE THREAD

**Issue by tjpdj1988** [RocketChat/Rocket.Chat#12118]
request to add screenshot feature for pc version

**Comment by reetp** [comment]
Why not use screen shot from your OS? Can't see the point in this for Rocket unless you can come up with a good reason.

**Comment by kaiiiiiiiii** [comment]
@reetp Totally agree. Every major OS has its own screenshot functionallity, there's no need to integrate such feature in RC.

**Comment by tjpdj1988** [comment]
![timg](https://user-images.githubusercontent.com/3386885/45999560-97613800-c0d8-11e8-8394-ceddf1c7621c.gif)
Sorry, my description may not be very clear, what I would like to add is the feature shown in the GIF
Select the part of the current screen to take a screenshot and send it to others

**Comment by piotrkochan** [comment]
https://img.purch.com/o/aHR0cDovL3d3dy5sYXB0b3BtYWcuY29tL2ltYWdlcy93cC9wdXJjaC1hcGkvaW5jb250ZW50LzIwMTUvMDcvc2NyZWVuc2hvdHMtdG9vbDAxLXcxMC0zODl4NDAwLnBuZw==

**Comment by tjpdj1988** [comment]
Well, it's my fault to suggest this feature.
WeChat /QQ has hundreds of millions of users, and they all implement this feature instead of recommending users to use other software to meet their needs.
Isn't it better out of the box?

**Comment by piotrkochan** [comment]
I used in my entire live a lot of different communicators like Skype, Polish Gadu-Gadu, FB Messenger, Built-in-Gmail communicator, Signal, IRC and many more. Not even one of them had or have built in screenshot functionality and I have never really missed it.

**Comment by reetp** [comment]
Please refer feature requests to the forums:

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat label add enahancement

**Comment by reetp** [comment]
@rocket-cat close
