### ISSUE TITLE
I have configuration blank issue in my 0.69 version when I reboot my machine. My Os version is Ubuntu 16.04.

### ISSUE THREAD

**Issue by bhavin0070** [RocketChat/Rocket.Chat#12128]
I have configuration blank issue in my 0.69 version when I reboot my machine.
My Os version is Ubuntu 16.04.

**Comment by bhavin0070** [comment]
My email settings & all changes are getting blank.
Like image changes color changes.

**Comment by reetp** [comment]
If you think you have found a bug then please use the bug template to give people the correct information. What do your logs say?

Most likely you have a configuration issue and you are better asking either in the forums https://forums.rocket.chat/ or in support at https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close

Please reopen with full logging if you have further issues.
