### ISSUE TITLE
Allow application window to stay always on top

### ISSUE THREAD

**Issue by nopynoop** [RocketChat/Rocket.Chat#12121]
I was trying cam to cam, using integrated video conference option with the Jitsi service.

All have been working well, but it would really useful to have an option to "pin" the chat window on top as Skype has.

![2018-09-21_20-19-24](https://user-images.githubusercontent.com/25570106/45899513-58339e00-bddd-11e8-93fa-ce1a7cbf1b5f.png)

Because at the second some other application is clicked, the window gets minimized.

**Comment by reetp** [comment]
I think that this is more of an issue with the client than the actual server.

Please either open a bug in the relevant client section eg Electron or create a NFR in the forums:

https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close notabug
