### ISSUE TITLE
Animation s

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#12125]
@x8-999-github commented on [Fri Sep 21 2018](https://github.com/RocketChat/Rocket.Chat.Electron/issues/893)

## My Setup
- Operating System:
Linux
- App Version:
2.11.0

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

People send animated gif

### Current Behavior

I get distracted by the gif/ can not concentrate as the gif keeps moving

### Expected Behavior

I would like a way to stop or hide the animations or play them only once or on hover.

**Comment by reetp** [comment]
This is an new feature request /enhancement and should be opened in the forums:
https://forums.rocket.chat/c/feature-requests

Note a good search of the interwebs will reveal methods available in browsers to stop playing animated gifs though YMMV.

e.g https://www.addictivetips.com/web/stop-animated-gifs-from-autoplaying-in-your-browser/

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close
