### ISSUE TITLE
ampersand encoded when using markdown

### ISSUE THREAD

**Issue by bbrendon** [RocketChat/Rocket.Chat#12127]
### Description:
Markdown interpretation breaks links. 

### Steps to reproduce:

1.  paste this into your chat window: `[my link](http://www.google.com?a=1&b=2)`
2. click on the generated link
3. notice the URL has changed to `https://www.google.com/?a=1&amp;b=2`

### Expected behavior:

goto this link : `http://www.google.com?a=1&b=2`

### Actual behavior:

goes to this URL: `https://www.google.com/?a=1&amp;b=2`

### Server Setup Information:

- Version of Rocket.Chat Server:  0.69.2
- Operating System:  debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  
- MongoDB Version:

**Comment by localguru** [comment]
I can confirm on 0.69.2 too

**Comment by bbrendon** [comment]
I've discovered this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/6586

**Comment by sampaiodiego** [comment]
closing as duplicate, thx
