### ISSUE TITLE
enable/disable per item email send

### ISSUE THREAD

**Issue by tbellembois** [RocketChat/Rocket.Chat#12120]
Hello,
Is it possible to enable email send only for certain actions. I would like to activate only "offline email notifications" but not "registration", "invitation"... notifications.
There is only an enable:true/false switch for the "direct reply" section.
Thanks.

rocketchat version "0.69.2"

**Comment by reetp** [comment]
This is a new feature request / enhancement.

Please open a new thread in the forums:
https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat label add "Feature: Request"

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close
