### ISSUE TITLE
Incorrect display of room topic

### ISSUE THREAD

**Issue by anvlkv** [RocketChat/Rocket.Chat#12133]
### Description:

When room topic is set to value containing special characters then they're escaped and displayed incorrectly

### Steps to reproduce:

1. call `/api/v1/groups.setTopic` with `{"roomId":"fMhrvGLfJ5PbACCoL","topic":"or includes &"}`
2. open room
3. topic is displayed as `or includes &amp;`

### Expected behavior:

topic is displayed as `or includes &`

### Actual behavior:

topic is displayed as `or includes &amp;`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Deployment Method: rocket chat cloud

**Comment by reetp** [comment]
0.65.1 is out of date by a few months and there are a lot of fixes.

https://github.com/RocketChat/Rocket.Chat/releases

Please test this on a newer version (currently 069.x or 0.70rc)

**Comment by anvlkv** [comment]
@reetp thanks! Seems to be fixed in 069.x
