### ISSUE TITLE
Group is not accessible when I create new GROUP with RocketChat API

### ISSUE THREAD

**Issue by nilekshdhimer** [RocketChat/Rocket.Chat#12136]
I try to create a new Group with the following request data:

**Request URL:** https://nomadjack.com/api/v1/groups.create
`{ "name": "testing", "members":["romesh","kierayre"] }`

but when I open **Rocket Chat Windows application** in my computer (**Windows 10**) I am getting an issue to access my new group. It shows me the only loader.

![2018-09-24_17h29_17](https://user-images.githubusercontent.com/7030318/45951169-1c3c4b00-c020-11e8-820d-41b9119918a0.png)

In a browser, it's working fine. And when I try to log out from my Windows Rocket Chat client and log in again it's working fine.

It means a problem is I need to refresh or reload the screen(of Rocket Chat Windows Application) via logout and login.

I also tried View---> Application Reload and View---> Current Server Reload
![2018-09-24_17h38_55](https://user-images.githubusercontent.com/7030318/45951368-d338c680-c020-11e8-9b08-aeb2d3a5aa65.png)

But nothing happens, to access this group I have log out and login again into my account then I can post a message to this group.

**My current Windows Rocket Chat Version is: 2.13.3**

**Comment by nilekshdhimer** [comment]
> You could paste console log from DevTools, it may help to debug issue

Sorry but nothing is displayed in a console.

**Comment by MarcosSpessatto** [comment]
@nilekshdhimer I'm closing this issue. Please open this issue in the desktop application repository: https://github.com/RocketChat/Rocket.Chat.Electron/issues. If you have any problem, feel free to open another issue. Thanks.
