### ISSUE TITLE
Rocket.Chat Search UI should not be channel specific

### ISSUE THREAD

**Issue by westei** [RocketChat/Rocket.Chat#12131]
### Description:

All interactions with the Rocket.Chat Search UI are channel specific.

If you search for something, this search is channel specific. So if you change to a different channel the search state is lost.

While is is a minor issue when switching channels this becomes a major issue when jumping to a message of the search result. If this message is from a different channel the search will adopt the state of the search of the that channel. If this state is a different search you will get results for that search, which is really confusing!

### Steps to reproduce:

1. Open `{channel-1}` and open the 'Search Message' for that channel.
2. Search for `{term1}` - any term that has a lot of results
3. Open `{channel-2}` and open the 'Search Message' for that channel.
4. Search for `{term2}` - any term different from `{term-1}` that has a result in `{channel-1}`
5. Click on 'jump' on the search result for `{term2}` in `{channel-1}`

Now you will see `{channel-1}` with search results for `{term1}` as the Message Search UI adopts the current state of the search as stored for `{channel-1}`

### Expected behavior:

The Message Search UI is expected to have a global context.

1. When I open the Message Search I expect to see my last search (or an empty search)
2. When I jump to a message in the Result the current search (incl. the paging state) should be preserved. Otherwise I can not jump to multiple messages of the search result (e.g. to investigate the context of message search results)

### Actual behavior:

Currently interaction with the Message Search is really hard as all search states are bound to the context of the current channel.

While this is cumbersome for the initial search it gets really frustrating when using the 'jump to message' feature

### Server Setup Information:

- Version of Rocket.Chat Server: `0.69.2`

**Comment by reetp** [comment]
This is a new feature request/ enhancement and should be opened as a new thread in the forums:

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close
