### ISSUE TITLE
Seeing which integration is active and which note direclty in the list

### ISSUE THREAD

**Issue by lazyants** [RocketChat/Rocket.Chat#12132]
![image](https://user-images.githubusercontent.com/249065/45942919-a797eb00-bfe4-11e8-8ab1-956153b7a138.png)
the first two integrations are deactivated, the third one is active. It would be great to is if activated/deactivated also directly in the list of integrations

**Comment by reetp** [comment]
@rocket-cat add label enhancement

**Comment by reetp** [comment]
This would be handy (!!) However, NFRs are now being referred to the forums for discussion.

Please create a new thread there: https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
