### ISSUE TITLE
Can't able to upgrade my Windows Rocket chat application

### ISSUE THREAD

**Issue by nilekshdhimer** [RocketChat/Rocket.Chat#12135]
I have Rocket Chat **2.13.0** Desktop client in my **Windows 10 PC**. When I try to update Rocket Chat client(with **2.13.3**) it give me following error:

![2018-09-24_17h18_09](https://user-images.githubusercontent.com/7030318/45950659-66bcc800-c01e-11e8-9d92-51faf45465d5.png)

**Comment by kaiiiiiiiii** [comment]
Hi @nilekshdhimer,

you're in the wrong repository :)

You can find the one for the desktop client over here:
https://github.com/RocketChat/Rocket.Chat.Electron

Cheers,
Kai

// CC: @TwizzyDizzy
