### ISSUE TITLE
Support CAS v3

### ISSUE THREAD

**Issue by tbellembois** [RocketChat/Rocket.Chat#12134]
My organization returns users attributes (sn, givenName) only with the CAS v3 version.
Is it possible to support the CAS v3 authentication that returns the authentication/user attributes through the new /p3/serviceValidate response ?
Thanks.

**Comment by localguru** [comment]
Not sure, may be stupid idea, but I could try using simplesaml as proxy:

https://simplesamlphp.org/docs/stable/cas:cas

**Comment by tbellembois** [comment]
Thanks for the link. I will try this.

**Comment by reetp** [comment]
This seems to be a Support request rather than an issue with Rocket.Chat

Please open any further issues in the forums https://forums.rocket.chat/ or ask at https://open.rocket.chat or if you have errors with your server please reopen with full debugging details.

**Comment by reetp** [comment]
@rocket-cat close
