### ISSUE TITLE
New Messages shows up you get a message in another channel

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1213]
I keep seeing this, i'm not 100% sure on the circumstances.  But it'll show the new messages pop up at the bottom in the current channel when there is no new message.  I can only assume its showing up from another channel.

**Comment by sunnipaul** [comment]
That happened to me too.

**Comment by engelgabriel** [comment]
I'll  close the #1217 as it seems to be a duplication.
