### ISSUE TITLE
The livechat can not be closed from the client's side

### ISSUE THREAD

**Issue by peroda** [RocketChat/Rocket.Chat#12149]
The livechat can not be closed from the client's side
Does nothing 
Version 0.70 rc1

![imagen](https://user-images.githubusercontent.com/5079413/46022140-50784000-c0e2-11e8-9986-b2aae431e7bd.png)

it stays that way after clicking on the yes button

![imagen](https://user-images.githubusercontent.com/5079413/46022253-87e6ec80-c0e2-11e8-8039-8508634f5337.png)

**Comment by renatobecker** [comment]
Hi @peroda,

Can you please check your browser's console after clicking on `yes` button to see if any log or error appears there?

Thanks.

**Comment by peroda** [comment]
hi @renatobecker ,
this is the output in web console:
`
ReferenceError: event is not defined    livechat.js:153:44253

messages.js/</< -   https://servidor/livechat/livechat.js:153:44253
dispatch -   https://servidor/livechat/livechat.js:9:301972
add/g.handle   -  https://servidor/livechat/livechat.js:9:300037
`

**Comment by renatobecker** [comment]
@peroda, thanks for your feedback.
I've a question: Do you have any Livechat triggers configured in your environment?

Thanks.

**Comment by peroda** [comment]
yes, I have a trigger, but I have eliminated it and I still have the problem.
![imagen](https://user-images.githubusercontent.com/5079413/46220093-705d6d00-c349-11e8-8911-031bcc7ee03a.png)
As you can see in this image, the chat appears closed in backend but not in the client's area

![imagen](https://user-images.githubusercontent.com/5079413/46220129-85d29700-c349-11e8-8c5e-5d89c1550a62.png)

Also, if the client continues writing, a new conversation opens. Look at this image

![imagen](https://user-images.githubusercontent.com/5079413/46220352-21fc9e00-c34a-11e8-8140-76a1cd657381.png)

Thanks.

**Comment by renatobecker** [comment]
Hi @peroda, thanks again for your feedback.
Ok, you've mentioned "`I still have the problem`", I want to know if your comment it's related to the Livechat client-side behaviour **and** the error is still happen or if the error **is no longer appearing** on your browser console after removing the trigger.

Can you confirm that, please?

Thanks.

**Comment by renatobecker** [comment]
Hi @peroda.

Can you attach an image of your browser's console log?
Another important thing is to check if you're getting any server side error too, if it is occurring, take a screenshot and then post here.

**Comment by peroda** [comment]
![imagen](https://user-images.githubusercontent.com/5079413/46417918-eb989780-c72a-11e8-8fd4-0454243296d1.png)

No errors on the server
![imagen](https://user-images.githubusercontent.com/5079413/46417987-197ddc00-c72b-11e8-9666-10d8de21a6c0.png)

**Comment by renatobecker** [comment]
Hi @peroda.

The "Conversation Finished Message" will be displayed only when the conversation is closed by the Agent side.

**Comment by MartinSchoeler** [comment]
This should be fixed in the latest release, if not, please open a new issue with updated details. Thanks!
