### ISSUE TITLE
[Bug] : JavaScript heap out of memory Rocket chat crash.

### ISSUE THREAD

**Issue by Anish-addweb** [RocketChat/Rocket.Chat#12143]
### Description:

Rocket chat server version 0.69.2 crash regularly and in log file generate FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory .

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Ubuntu 16.04
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enable
- NodeJS Version: 8.11.3

**Comment by localguru** [comment]
How much memory do you have in total on the server and how much was used at the crash?

**Comment by piotrkochan** [comment]
is Your system 32 or 64bit? Also try to increase v8 memory using:

```
node --max_old_space_size=4096
```
In your systemd service.

**Comment by Anish-addweb** [comment]
@piotrkochan System is 64 bit. installtion via snap can not run above mention command.

**Comment by Anish-addweb** [comment]
> How much memory do you have in total on the server and how much was used at the crash?
Ram 4 GB. near 2.5 - 3 GB RAM is used at the crash

**Comment by piotrkochan** [comment]
If there is no more ideas, maybe increase ram is a good idea

**Comment by piotrkochan** [comment]
It just happen to me on Ubuntu 18, tar deployment, Rocket 0.69.1

**Comment by localguru** [comment]
I've seen "JavaScript heap out of memory" error, when building a bundle from source. 

`export TOOL_NODE_FLAGS="--max_old_space_size=4096"` helped in this case.

**Comment by Anish-addweb** [comment]
Still crashing with same error in snap deployment.

**Comment by piotrkochan** [comment]
@Anish-addweb for me problem started appearing after adding SMTP configuration (office365). After that I've added `--max_old_space_size=4096` option to my systemd configuration and it works now.

Just drop snap deployment... You can't do almost anything with that.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  This solution definitely works.  If you’d like feel free to add feature request to be able to configure that for snaps.
