### ISSUE TITLE
Have a TypeError when creating a direct message to someone toLowerCase

### ISSUE THREAD

**Issue by zopanix** [RocketChat/Rocket.Chat#12141]
### Description:
The bug is not always reproducible, but I've had it on the Web UI, DesktopApp(win and linux).

The console shows a error and it keeps looping an a call saying that `toLowerCase` is not a function.

### Steps to reproduce:

1. go to the user directory,
2. Click on a user to start a direct message

### Expected behavior:

Open a direct message to another user

### Actual behavior:
3. In some cases, the UI will be loading indefinitely (restarting the app fixes the problem), if you're not admin you get rate limited.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System:  debian
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: No
- NodeJS Version: Official Image from docker hub: rocket.chat:0.69.2
- MongoDB Version: 
```
mongod --version
db version v3.2.21
git version: 1ab1010737145ba3761318508ff65ba74dfe8155
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64
```

### Additional context
Sometime it works just fine and the direct message opens
WebUI is not usable untill application restart.
It seems google chrome is more affected then firefox.

This setup is new, there was no database migration or anything. It runs completely in containers for now.
Didn't change configuration a lot. I configured an SAML Endpoint successfully with ADFS and I have the error with both local and ADFS Users.

### Relevant logs:
Browser Logs:
```
 [Show/hide message details.] TypeError: r.toLowerCase is not a function[Learn More] c029a6b2088014967102f8efaaf260dc7e0d3df5.js:443:61411
u
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:443:61411
l
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:443:61605
callbacks.js/L.callbacks.run/a<
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:183:17399
reduce self-hosted:365:27 callbacks.js/L.callbacks.run
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:183:17210
e/<
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:183:49717
e/<
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:171:786
forEach self-hosted:268:13 e
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:171:742
n/<
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:171:3204
e/<
https:/domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:171:786
forEach self-hosted:268:13 e
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:171:742
e/<
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:171:2255
t/this.socket.onmessage/<
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:3467
forEach self-hosted:268:13 t
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:4724
t/this.socket.onmessage
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:3427
sockjs-0.3.4.js/l</o.prototype.dispatchEvent
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:7647
sockjs-0.3.4.js/l</T.prototype._dispatchMessage
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:21406
sockjs-0.3.4.js/l</T.prototype._didMessage
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:22306
sockjs-0.3.4.js/l</T.websocket/o.ws.onmessage
https://domain.com/c029a6b2088014967102f8efaaf260dc7e0d3df5.js:57:24455
```
Didn't find anything usefull in server logs.

Any help would be appreciated.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
