### ISSUE TITLE
Changing settings in admin panel is buggy

### ISSUE THREAD

**Issue by bbrauns** [RocketChat/Rocket.Chat#12144]
### Description:

admin settings panel shows incorrect settings state after changes

### Steps to reproduce:

![bug](https://user-images.githubusercontent.com/6813310/45997663-a88e5280-c0a0-11e8-9838-8b6d0d1e4468.gif)

### Expected behavior:

save settings and update UI accordingly

### Actual behavior:

incorrect settings are shown

### Server Setup Information:

Rocket.Chat
Version	0.69.2
Database Migration	131
Database Migration Date	Sun Sep 23 2018 00:18:20 GMT+0200 (Central European Summer Time)
Installed at	Tue Feb 14 2017 09:16:40 GMT+0100 (Central European Standard Time)
Uptime	2 days, 8 hours, 26 seconds
Deployment ID	B5JMqpTPvnG8TepW8
PID	1
Running Instances	1
OpLog	Enabled
Commit
Hash	7df98181051061163e2ab4439b56659e841a0c72
Date	Tue Sep 11 17:28:16 2018 -0300
Branch	HEAD
Tag	0.69.2
Author	Diego Sampaio
Subject	Merge pull request #12026 from RocketChat/release-0.69.2
Runtime Environment
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	4.4.0-135-generic
Node Version	v8.11.4
OS Uptime	13 days, 6 hours, 16 minutes, 30 seconds
OS Load Average	0.00, 0.05, 0.03
OS Total Memory	1.94 GB
OS Free Memory	66.46 MB
OS CPU Count	1
Build Environment
OS Platform	linux
OS Arch	x64
OS Release	4.4.0-134-generic
Node Version	v8.11.3
Date	11. September 2018 22:39

**Comment by piotrkochan** [comment]
I can confirm

**Comment by maik28** [comment]
+1

**Comment by jthomae1** [comment]
+1

**Comment by ggazzo** [comment]
closed by #13369
