### ISSUE TITLE
Unread message count on desktop version

### ISSUE THREAD

**Issue by hwstusc** [RocketChat/Rocket.Chat#12152]
### Description:

Running desktop version and icon in taskbar indicates unread messages, but after I read them, the number does not decrement. It is climbing.

### Steps to reproduce:

1. Receive a chat message
2. Read the chat message
3. Minimize RocketChat window

### Expected behavior:

Number of unread chats in the taskbar icon disappears

### Actual behavior:

Number of unread chats in the taskbar icon does not change. It is incrementing each time a new message is received and never decrementing.

### Server Setup Information:
![capture](https://user-images.githubusercontent.com/43580254/46025446-88fe2680-c0ae-11e8-9cfa-755513ac3d29.JPG)

- Version of Rocket.Chat Server: 2.13.2
- Operating System: Windows 10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by piotrkochan** [comment]
please move to https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by reetp** [comment]
@rocket-cat close
Closing notabug (possibly an issue in Electron version)
