### ISSUE TITLE
Can't login after configuring iframe integration

### ISSUE THREAD

**Issue by gakuba** [RocketChat/Rocket.Chat#12150]
After setting up iFrame integration, I logged out and I can no longer login. I am getting an error showing that the website is trying to reach the url that I put in SSO field. unfortunately the url was ngrok and it does not exists anymore. I don't know what to do to revert to the previous state. 

![screen shot 2018-09-26 at 12 54 55 am](https://user-images.githubusercontent.com/4388418/46022914-dd44ed00-c126-11e8-8bb7-1137d92d214e.png)

**Comment by gakuba** [comment]
Rocket Chat Version 0.69.2
commit 7df9818
Tag: 0.69.2
Nodejs Version v8.11.3
Running on GCP Linux

**Comment by nimetu** [comment]
`Meteor.loginWithPassword('user', 'pass');` in browser console should get you in

**Comment by gakuba** [comment]
Thanks @nimetu . Luckily I found that my phone was still connected with a valid session. so I turned off the iframe integration from there. that's to say I have not tested your suggestion but I believe it might be helpful for someone else who might not be lucky as I was.
cheers
