### ISSUE TITLE
Search button permission

### ISSUE THREAD

**Issue by kepanin** [RocketChat/Rocket.Chat#12166]
***Is your feature request related to a problem? Please describe.**
Hi I want some users to be unable to use search button (like guest users) or filter whom they can see with search button

**Describe the solution you'd like**
Check box in permission page, or custom css/js to delete this button for everyone

Or disable search at all

**Comment by reetp** [comment]
For reference the OP posted the following temporary workaround to hiding the Search button as custom CSS 

[aria-label*="Поиск"]{
display: none;}

button[aria-label*="Каталог"]{
display: none;}
button[aria-label*="Поиск"]{
display: none;}

button[aria-label*="Каталог"]{
display: none;}

We think this translates to:

[aria-label*="Search"]{
display: none;}

button[aria-label*="Catalog"]{
display: none;}

button[aria-label*="Search"]{
display: none;}

button[aria-label*="Catalog"]{
display: none;}

I think to hide it on the mobile app he modified admin/Accounts-Fields to Consider in Search and added something like 'Role' which means mobile search then finds nothing.

**Comment by localguru** [comment]
What us the use case?

**Comment by reetp** [comment]
> What us the use case?

As per his original comment I think :-) 

>> I want some users to be unable to use search button (like guest users) or filter whom they can see with search button

So the ability to enable/disable search for certain users or possibly account types via persmissions.

**Comment by reetp** [comment]
This is a feature request and should be opened in the forums:

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat add label enhancement

**Comment by reetp** [comment]
@rocket-cat close
