### ISSUE TITLE
Disable Integration History?

### ISSUE THREAD

**Issue by graphik55** [RocketChat/Rocket.Chat#12177]
Hello,

I want to ask if it is possible to disable the history of an outgoing Webhook.
I installed the Jira integration which works fine but I am able to see every message in the Webhooks History. It would be nice to completely disable the history or to just see the messages wich will be really send to the Webhooks URL.

I also asked the original developer of the integration but he told me that this is an RocketChat function.
Issue: https://github.com/gustavkarlsson/rocketchat-jira-trigger/issues/60

Thank's for your help.
graphik55

**Comment by reetp** [comment]
@graphik55 can you just confirm this is an issue on the latest version?
I can label it as an enhancement if so.
Thanks.

**Comment by graphik55** [comment]
@reetp I am running the stable snap version 0.69.2 at the moment.
Will it take a long time untill the 0.70.3 will become the stable version?
If so I could install a secound system to check the issue, else I would wait until the snap becomes the update.

**Comment by graphik55** [comment]
Hey,

I started a Docker container and connected the Integration. 
It is still possible to see the normal message contant.
So the problem still exists.

It would be great to be able to disable this or only see the messages while logging is set to debug.

**Comment by reetp** [comment]
OK, so Rocket chat isn't actually throwing an error (therefore not a bug). It is just not doing what you want it to.

This is really an enhancement/NFR and current policy is to open a thread in the forums here:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close
