### ISSUE TITLE
Can't able to get Avtar of Rocket Chat Group

### ISSUE THREAD

**Issue by nilekshdhimer** [RocketChat/Rocket.Chat#12178]
Hello there,

I am using REST API with C# language.

I can able to get Avtar for User with this API https://rocket.chat/docs/developer-guides/rest-api/users/getavatar/ 

**But there is no API for getting Avtar for "Private Group(s)".**

Please create a new API for this.

Thank you.

**Comment by bleonard252** [comment]
Using # might work, i.e. #general

**Comment by nilekshdhimer** [comment]
> Using # might work, i.e. #general

Sorry, I am not getting you. Can you please give me an example?

**Comment by bleonard252** [comment]
`curl http://localhost:3000/avatar/%40general` should return the icon for #general.

**Comment by kaiiiiiiiii** [comment]
There’s no api endpoint for channel avatars yet, as far as I know. But you can still use @bleonard252 workaround :)

**Comment by nilekshdhimer** [comment]
> `curl http://localhost:3000/avatar/%40general` should return the icon for #general.

I am not talking about the **channel**(#general).
I am talking about a **group**, my personal group on my rocket chat server.

**Comment by bleonard252** [comment]
Replace "general" with the group name.

**Comment by MarcosSpessatto** [comment]
@nilekshdhimer, @bleonard252 answer is right.

**Comment by reetp** [comment]
Closing notabug. Please reopen if you have further issues

@rocket-cat close

**Comment by reetp** [comment]
@rocket-cat close
