### ISSUE TITLE
No direct messages message can improve

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12179]
### Description:

![screen shot 2018-09-27 at 09 12 58](https://user-images.githubusercontent.com/551004/46145162-a4e00480-c235-11e8-8cce-42ef64238847.png)

IMHO we could remove this section or change to something related to direct messages, like: "You don't have any direct messages yet".

**Comment by thiagosanchz** [comment]
I agree, we can remove the section when the user has no DMs.
