### ISSUE TITLE
New messages indicator pop out unexpectedly when tab bar is opened

### ISSUE THREAD

**Issue by sunnipaul** [RocketChat/Rocket.Chat#1217]
It pops out when opening a sliding in a tab from the right panel which shrinks the width of the message list area.

**Comment by gmsecrieru** [comment]
@sunnipaul Could you please provide steps to reproduce this or maybe a gif/screenshot of the error? I tried to follow what you mentioned but could not reproduce.

**Comment by sunnipaul** [comment]
@rodrigok  I found the current master branch have changed it's behavior of displaying new message when the list is full.  It will auto-scroll to bottom.   The bug I caught is based on previous commit ( serveral days ago, on master branch).  It won't auto-scroll but display a "New messages" indicator.

I now can't reproduce it either.  I should have made gif picture for it.

**Comment by engelgabriel** [comment]
Hi @sunnipaul 

We still have the "New messages" indicator, it should no auto-scroll for new messages if you are not at the bottom.

![image](https://cloud.githubusercontent.com/assets/1000217/10710785/714d324a-7a68-11e5-9e8e-5d9b8366880a.png)

**Comment by engelgabriel** [comment]
May be the same problem as #1213
