### ISSUE TITLE
File transfer permission checkbox

### ISSUE THREAD

**Issue by kepanin** [RocketChat/Rocket.Chat#12181]
**Is your feature request related to a problem? Please describe.**
I want checkbox for roles in permission page to enable or disable file sending for some roles

**Describe the solution you'd like**
Checkbox on permission page

**Describe alternatives you've considered**

**Additional context**

**Comment by reetp** [comment]
NFRs should now be opened in the forums.

Please got to https://forums.rocket.chat/ and add a new thread here

**Comment by reetp** [comment]
@rocket-cat close
