### ISSUE TITLE
How to use DialogFlow with Rocket.Chat

### ISSUE THREAD

**Issue by nikhilrayaprolu** [RocketChat/Rocket.Chat#12180]
I would like to know how to use Dialogflow with Rocket.Chat

**Comment by piotrkochan** [comment]
For questions like these You should use forum. You could use SDK https://github.com/RocketChat/Rocket.Chat.js.SDK in order to create middleware between Rocket and Dialogflow somehow.

**Comment by reetp** [comment]
@rocket-cat close
Closing notabug.
Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
