### ISSUE TITLE
Support oEmbed protocol

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#1218]
http://oembed.com/

from https://github.com/RocketChat/Rocket.Chat/pull/1216

**Comment by Theaxiom** [comment]
Thank you for brining this up. :)

**Comment by engelgabriel** [comment]
Is this now done?

**Comment by kakawait** [comment]
Nop I'm currently working on it. Wait PR (that I will be linked to this issue)

**Comment by engelgabriel** [comment]
OK! Cool!

Sorry for asking, I was just curious if someone forgot the issue open by mistake :)

**Comment by geekgonecrazy** [comment]
This is actually done as of #1241 right?

**Comment by engelgabriel** [comment]
I believe so. Lets close this.
