### ISSUE TITLE
Text input field changes its size

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12183]
### Description:

The text input field sometimes changes its size. Unfortunately, the problem cannot be replicated reliably. Observed by several users with the RC Desktop Client version 2.13.3 and in Firefox and Chrome. The problem occurred only since an update from RC version 0.61.0 to 0.69.2.

### Steps to reproduce:

1. type some text into the text field

### Expected behavior:

The text input field should keep its size (one line).

### Actual behavior:

Text field changes its size.

![output](https://user-images.githubusercontent.com/8544984/46151889-163ca900-c270-11e8-9c23-bb3249961225.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Ubuntu 16.04 TLS
- Deployment Method: bundle (self build)
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 3.4.17

**Comment by ggazzo** [comment]
closed by #12138

**Comment by Nazgolze** [comment]
We're on 0.70.4 and this is still happening

**Comment by vynmera** [comment]
Same here. Issue develops as soon as the browser window's size is changed.

**Comment by localguru** [comment]
@ggazzo could you please reopen. Thanks.
