### ISSUE TITLE
Not getting inline image previews

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#1219]
When posting an image file I don't get the inline preview.
Checking in the database I can see that in rocketchat_oembed_cache meta and headers property are null. Any Ideas?

**Comment by emcguinness** [comment]
This is often caused by certificate issues from what I have seen, are you serving over SSL? If so and you have not already tried it there is a setting to allow invalid self signed certs under the general settings page. Set that to true and try a new upload and see if it helps. If not it could be worth describing your certificate set up. Can't guarantee to help but more information is always good.

**Comment by flashguy22** [comment]
I have tried allowing self signed certs but it didn't make any changes. It was working until we did a db dump and started from scratch as we had a corrupted user we couldn't remove.

**Comment by flashguy22** [comment]
tail -f /var/log/rocket.chat/*

shows this during file upload:

{ '0': 
{ _id: '6kvLCx6CvpzAWJDyG',
name: 'linuxhaus_lihas.gif',
size: 1685,
type: 'image/gif',
rid: 'GENERAL',
complete: true,
uploading: false,
store: 'rocketchat_uploads',
extension: 'gif',
userId: '55vaMZtwYiLYYdusW',
uploadedAt: Fri Oct 23 2015 14:25:13 GMT+0200 (CEST),
url: 'https://chat.phoenixdesign.com/ufs/rocketchat_uploads/6kvLCx6CvpzAWJDyG.gif' } }


 [methods] sendMessage -> userId: 55vaMZtwYiLYYdusW arguments: { '0': 
{ _id: 'rYHQYoix3aqWxipzH',
rid: 'GENERAL',
msg: 'File Uploaded: *linuxhaus_lihas.gif*\nhttps://chat.phoenixdesign.com/ufs/rocketchat_uploads/6kvLCx6CvpzAWJDyG.gif',
file: { _id: '6kvLCx6CvpzAWJDyG' } } }
2015-10-23 14:25:13 306: [methods] canAccessRoom -> userId: 55vaMZtwYiLYYdusW rid: GENERAL
2015-10-23 14:25:13 393: stream.permissions.read 9aSNk95TEi9icXYzM GENERAL
2015-10-23 14:25:13 394: [methods] canAccessRoom -> userId: 9aSNk95TEi9icXYzM rid: GENERAL
2015-10-23 14:25:13 397: stream.permissions.read a3DT4JJPnEbxp2TKF GENERAL
2015-10-23 14:25:13 399: [methods] canAccessRoom -> userId: a3DT4JJPnEbxp2TKF rid: GENERAL
2015-10-23 14:25:13 401: stream.permissions.read 55vaMZtwYiLYYdusW GENERAL
2015-10-23 14:25:13 404: [methods] canAccessRoom -> userId: 55vaMZtwYiLYYdusW rid: GENERAL

the metadata is not stored in rocketchat_oembed_cache

**Comment by gmsecrieru** [comment]
@flashguy22 could you please look into #1194 to make sure that is not related to your current environment setup?

**Comment by flashguy22** [comment]
@gmsecrieru No, we don't have a outbound proxy. I can access the instance without any proxy.

**Comment by gmsecrieru** [comment]
Okay just wanted to make sure. Thanks!

**Comment by flashguy22** [comment]
no worries, appreciate your help. Just figured out if I post a link to an external image e.g. http://www.golem.de/1510/117048-108203-i_rc.jpg I get a inline preview. I'm getting really confused...

**Comment by gmsecrieru** [comment]
I was just about to mention that if I try to reference your instance's image in the [Demo Server](https://demo.rocket.chat) it also works:

![screen shot 2015-10-23 at 11 56 34](https://cloud.githubusercontent.com/assets/190883/10694488/2a961c40-797d-11e5-97b2-62d04002408b.png)

While embedding URLs, our component generates an HTTP request to identify which kind of content is that so we can embed it properly. It seems like your instance is having a hard time to inspect your own files.

**Comment by flashguy22** [comment]
I'm a happy camper now. Posting the link to an external image file helped us find the problem.
Name resolving was set according to the wiki article in /etc/hosts to 127.0.0.1 chat.phoenixdesign.com.
Imagepreview tries to load uploaded image. Looks for it at chat.phoenixdesign.com:443. 
As we modified name resolving this is 127.0.0.1:443.

But the node server runs on 127.0.0.1:3000
chat.phoenixdesign.com  ist only available from outside via 443.

Hope this will help someone.

Maybe a Proxy configuration in the Admin Settings would be helpful..
