### ISSUE TITLE
Cannot download attached image file in file list.

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat#12193]
When you click the file list icon and click an image file attached it can only be preview but there is no option to download the image. 

![selection_101](https://user-images.githubusercontent.com/1788360/46173419-c7772980-c2d8-11e8-8816-4f1191d7950e.png)

**Comment by localguru** [comment]
Hmm ... this is true. See it on 0.69.2 too.

**Comment by chatnl** [comment]
I can still download in my browser? I am using 0.70. I just click on the image, it opens it and then I can save the image by clicking on it with the right mouse button.

**Comment by ccfiel** [comment]
Browser is ok the problem is the electron app.

**Comment by localguru** [comment]
> Browser is ok the problem is the electron app.

See issue [#915](https://github.com/RocketChat/Rocket.Chat.Electron/issues/915) in Electron repo.

**Comment by reetp** [comment]
@rocket-cat close
Issue is with Electron. Closing in favour of above referenced bug
