### ISSUE TITLE
Realtime Api stream-notify-user trigge message event

### ISSUE THREAD

**Issue by clyquan** [RocketChat/Rocket.Chat#12202]
### Description:

I subscribe user A for stream-notify-user multiple events, such as **message**, **notification**, **rooms-changed**,  **subscriptions-changed**.when I send a direct message to user A on browser with another user B, and I get all events afore-mentioned except "message" event.

### Steps to reproduce:

1. use https://github.com/jszaszvari/rocketchat-ddp-listener.git to subscribe stream-notify-user
2. User B send direct message to user A 
3. got multiple events except "message"

### Expected behavior:

should get events, include "message" event.

### Actual behavior:

missing "message" event

### Server Setup Information:

- Version of Rocket.Chat Server:  0.69.2 
- Operating System: Linux 3.10.0-862.11.6.el7.x86_64
- Deployment Method:  docker
- Number of Running Instances: 2 
- DB Replicaset Oplog: enabled
- NodeJS Version:  v8.11.3
- MongoDB Version: 3.2

**Comment by clyquan** [comment]
got Msg below:

Subscription Msg: {"msg":"changed","collection":"stream-notify-user","id":"id","fields":{"eventName":"teHHn6T5CY4tXbyMX/**notification**","args":[{"title":"@UserB","text":"1234abcd","payload":{"_id":"PpYs5gcsdLNukrbxs","rid":"8wZfvYoMAqhQEtv8JteHHn6T5CY4tXbyMX","sender":{"_id":"8wZfvYoMAqhQEtv8J","username":"UserB","name":"UserB"},"type":"d"}}]}}

Subscription Msg: {"msg":"changed","collection":"stream-notify-user","id":"id","fields":{"eventName":"teHHn6T5CY4tXbyMX/**subscriptions-changed**","args":["updated",{"_id":"HYH9rqsTPFLBS4q7e","rid":"8wZfvYoMAqhQEtv8JteHHn6T5CY4tXbyMX","u":{"_id":"teHHn6T5CY4tXbyMX","username":"UserA"},"fname":"UserB","name":"UserB","t":"d","open":true,"alert":true,"unread":22,"userMentions":0,"groupMentions":0,"_updatedAt":{"$date":1538121171971}}]}}

Subscription Msg: {"msg":"changed","collection":"stream-notify-user","id":"id","fields":{"eventName":"teHHn6T5CY4tXbyMX/**rooms-changed**","args":["updated",{"_id":"8wZfvYoMAqhQEtv8JteHHn6T5CY4tXbyMX","_updatedAt":{"$date":1538121171976},"t":"d","lastMessage":{"_id":"PpYs5gcsdLNukrbxs","rid":"8wZfvYoMAqhQEtv8JteHHn6T5CY4tXbyMX","msg":"1234abcd","ts":{"$date":1538121171933},"u":{"_id":"8wZfvYoMAqhQEtv8J","username":"UserB","name":"UserB"},"_updatedAt":{"$date":1538121171954},"editedBy":null,"editedAt":null,"emoji":null,"avatar":null,"alias":null,"customFields":null,"attachments":null,"mentions":[],"channels":[],"sandstormSessionId":null}}]}}

**Comment by ggazzo** [comment]
@clyquan problem solved? because we are confident the stream-room-message works, could you send me the log from that subscription?

**Comment by ggazzo** [comment]
we dont use the stream "message" only the "stream-room-message"
