### ISSUE TITLE
Custom emoji are too big and gifs are laggy

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#12209]
### Description:

We've added some custom emoji (from hipchat) like this one:
https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/chompy-1414025208.gif

It looks like rendered emojis are too big and GIF's are very "laggy"

### Steps to reproduce:

1. Add emoji in admin panel
2. Post emoji in message

### Expected behavior:

1. Same image-size in message as uploaded emoji
2. Gifs are fluid and nice

### Actual behavior:
1. Images are too big and pixelate
2. Gifs laggins

Visibile in message:
![https://i.imgur.com/YF5i5Q1.png](https://i.imgur.com/YF5i5Q1.png)

Real size:
![https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/salute-1417756826.png](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/salute-1417756826.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.1
- Operating System: ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: 8.11
- MongoDB Version: 4

**Comment by ggazzo** [comment]
@piotrkochan fixed ;)
