### ISSUE TITLE
blue E2E info bar is not hidden after entering the password

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12204]
### Description:

The "blue E2E info bar" at the top is not hidden after entering the password, although encrypted messages will be successfully decrypted.

### Steps to reproduce:

1. click on the blue E2E info bar and enter your password

### Expected behavior:

The Blue E2E info bar should be hidden after entering the password.

### Actual behavior:

The Blue E2E info bar remains.

![bildschirmfoto_2018-09-28_12-17-14](https://user-images.githubusercontent.com/8544984/46203130-15138680-c319-11e8-81f6-5c9a52ec044e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0 (open.rocket.chat)

**Comment by Hudell** [comment]
This issue was fixed on 0.70.1, can you confirm?

**Comment by localguru** [comment]
> This issue was fixed on 0.70.1, can you confirm?

@Hudell yes, I can confirm it on "0.70.3" (open.rocket.chat) Thanks!
