### ISSUE TITLE
0.70 not available on snap?

### ISSUE THREAD

**Issue by lackaffchen** [RocketChat/Rocket.Chat#12211]
I tried to update my Rocket.Chat server (version 0.69.2 stable and 0.69.0 beta as well as candidate) on ubuntu cause the Rocket.Chat app can't connect.

What can I do?

**Comment by rockneverdies55** [comment]
I guess docker repo / latest isn't upgraded to 0.70 as well yet... I'm getting `Tag latest not found in repository docker.io/rocketchat/rocket.chat`...

**Comment by geekgonecrazy** [comment]
We've posted about this one several occasions.  Snap updates auto update everyone so are intentionally stalled a bit after release. 

I don't think anyone wants us to cut release at end of business day and then have a broken install until we are back at it ;)

It'll be coming soon.

**Comment by rockneverdies55** [comment]
Interesting... Here is what I'm getting though...

![image](https://user-images.githubusercontent.com/4588562/46227659-921a1c80-c368-11e8-93a1-474544ad670a.png)

**Comment by geekgonecrazy** [comment]
@rockneverdies55 so if you pull with docker directly via: `docker pull rocketchat/rocket.chat:latest` or `docker pull rocketchat/rocket.chat:0.70.0` do you get errors with both?

**Comment by rockneverdies55** [comment]
Weird but yes :open_mouth: 

![image](https://user-images.githubusercontent.com/4588562/46239667-3ff6ec80-c3a4-11e8-9e0b-dc2543eb43f3.png)
