### ISSUE TITLE
Channel search shows duplicate channels

### ISSUE THREAD

**Issue by verwilst** [RocketChat/Rocket.Chat#12219]
-->

### Description:

When opening the channel/user search tab, channels are shown multiple times. When channels are renamed (#mychannel to #MyChannel for example, they sometimes appear both with the old and the new name.

### Steps to reproduce:

1. Go to Search

### Expected behavior:

Every channel only listed once, with their current name.

### Actual behavior:

![image](https://user-images.githubusercontent.com/2114993/46262227-b27bdf80-c4fe-11e8-89f4-ea4b0229fb58.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0
- Operating System: Docker
- Deployment Method: Helm chart
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: Official docker image
- MongoDB Version: 4.3

**Comment by rtarantelli** [comment]
Hi @RocketChatApp and @geekgonecrazy, any news about this bug? Say yes, please!

**Comment by geekgonecrazy** [comment]
I’m not sure what would even cause this.  Would have to defer to @RocketChat/frontend maybe they know?

Not sure if even still an issue

**Comment by philipooo** [comment]
We also see this issue with Rocket.Chat 0.74.2.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14621

**Comment by engelgabriel** [comment]
We can't replicate the behavior on the latest versions above 1.2.0

Please reopen the issue with more information if the bug persists.

**Comment by cenicoemir** [comment]
Problem still happening, version 1.2.1
![image](https://user-images.githubusercontent.com/43582560/61151940-092b3680-a4df-11e9-919f-31757e388c50.png)

**Comment by ggazzo** [comment]
@cenicoemir its happening only for this specific channel? do you have more info about it? if its a default channel, if you changed the channel in some way, if you have a proper method to reproduce this bug would be useful, thanks.

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/15056
