### ISSUE TITLE
Switching Channels Sometimes Causes Message UI to Overlap

### ISSUE THREAD

**Issue by blaskovicz** [RocketChat/Rocket.Chat#1221]
Today, when I first loaded our #general channel and then switched to a private group, the existing chat in the chat pane was overlapped with the new chat from the new channel (without clearing the previous chat messages).

I haven't been able to reproduce this  reliably, but I have seen it happen to me at least 3 times.

**Comment by Theaxiom** [comment]
This has happened to me on occasion as well, I am using Chrome.

**Comment by engelgabriel** [comment]
It used to happen when the user had a short connection problem, and the load old messages process brakes. Can you take a look at the console log when that happens and send a copy to us?

**Comment by blaskovicz** [comment]
I just had this happened, and it was the result of switching from `admin page > direct message > private group`.

The console has no log output, just xhr requests:
![image](https://cloud.githubusercontent.com/assets/10687433/10889390/cffb79ca-815f-11e5-94b4-fa6a4312721b.png)

**Comment by blaskovicz** [comment]
Picture of overlapping channels:
![image](https://cloud.githubusercontent.com/assets/10687433/10889429/fbabb7f6-815f-11e5-817f-b61446da7e54.png)

**Comment by engelgabriel** [comment]
@rodrigok can we change the order of how things happen to make sure we remove the current "room" immediately on the mouse click, avoiding the scenario where the unexpected broken process can trigger the overlap?

**Comment by internalfx** [comment]
+1

**Comment by tuudik** [comment]
:+1:

**Comment by fduraibi** [comment]
+1

**Comment by lvh1** [comment]
I've had this happen as well, but it's hard to reproduce.

**Comment by marceloschmidt** [comment]
This has been fixed and it's under testing on demo.rocket.chat

**Comment by marceloschmidt** [comment]
Please advise if you get it to happen again.

**Comment by fduraibi** [comment]
@marceloschmidt it just happened to me as I opened the users admin settings and my server is using the latest from develop branch.

**Comment by cpitman** [comment]
Still reproducible on 0.42

**Comment by hughlroberts** [comment]
I'm still getting this issue with the macOS app
