### ISSUE TITLE
Windows rocket chat update not working

### ISSUE THREAD

**Issue by paddlr01** [RocketChat/Rocket.Chat#12229]
Running Windows 10. Updated from 2.13.0 to 2.13.3, now it won't open. checking the task manager, 4 rocket chat process are running in the background, but no user window is present.
![image](https://user-images.githubusercontent.com/43757590/46303366-9d906200-c579-11e8-8cac-19cf3d3aa86b.png)

I've uninstalled and reinstalled several times. Same issue.

**Comment by piotrkochan** [comment]
Should be posted as issue in https://github.com/RocketChat/Rocket.Chat.Electron. Please kill process, remove Rocket.Chat directory in AppData (or similar, I don't really remember) and run Rocket again.

**Comment by kaiiiiiiiii** [comment]
The issue is already present in the Electron repository:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/901

// CC: @TwizzyDizzy
