### ISSUE TITLE
Version 0.70 doesn't start in Internet Explorer 11

### ISSUE THREAD

**Issue by asand3r** [RocketChat/Rocket.Chat#12226]
After upgrade Rocket.Chat server to v0.70 we cannot open it in Internet Explorer 11.

### Steps to reproduce:

1. Open main page in IE 11.

### Actual behavior:

![default](https://user-images.githubusercontent.com/13959303/46289525-fb30a880-c591-11e8-907f-58126a47f5b6.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70
- Operating System: CentOS 7.5.1804
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

### Additional context

If I click on the error message in debug console in the browser, it points to next place:
![default](https://user-images.githubusercontent.com/13959303/46290673-29fc4e00-c595-11e8-934f-49f05112756d.png)

**Comment by tassoevan** [comment]
I found the issue's source: https://github.com/brianloveswords/base64url/issues/35

**Comment by edurenye** [comment]
Require version 2.0.0 fixes that error:
```
npm install base64url@2.0.0
```

But just to get into a new one:
```
Unable to get property 'meteorInstall' of undefined or null reference
File: babel-runtime.js, Line: 17, Column: 1
```

**Comment by asand3r** [comment]
Hi @edurenye ,
Could you answer, please, should I rebuild Rocket.Chat server after base64url installed? For now I've installed version 3.0.0. The package wasn't installed till today.

**Comment by edurenye** [comment]
Yes, I think so.

**Comment by Abraka** [comment]
Any progress with IE11? This should have IMO a top priority because IE11 is default in bigger enviroments. Nobody notice this before 0.70 server release?

**Comment by habnux** [comment]
We also have this issue with IE 11.0.85.

**Comment by dominic-pucci** [comment]
We have this issue with Google Chrome as well.

**Comment by tassoevan** [comment]
@dominic-pucci Same error message in the Chrome's console?

**Comment by fadanner** [comment]
Having the same problem with RC 0.70.4 running as snap. Is there a way to workaround this on server side?

**Comment by tobias-crow** [comment]
I'm having EXACTLY the same issue as the OP on selected Windows 10 machines running IE11/Edge. I've also tried the suggested fixes above but still the same error. Running version 0.70.4 on Ubuntu backend. Is there any solution to this besides using another browser?

**Comment by stephan1827** [comment]
> I'm having EXACTLY the same issue as the OP on selected Windows 10 machines running IE11/Edge. I've also tried the suggested fixes above but still the same error. Running version 0.70.4 on Ubuntu backend. Is there any solution to this besides using another browser?

Try latest version 71.1

**Comment by ideoignus** [comment]
71.1 also has same issue with IE11
