### ISSUE TITLE
"Apps" menu is broken. 0.70.0.

### ISSUE THREAD

**Issue by nicexe2e4** [RocketChat/Rocket.Chat#12222]
### Description:

Marketplace doesn't load. Manual installation also doesn't work. Log is empty.
Stopped working after upgrading to 0.70.0

### Steps to reproduce:

1. Go to "Apps" menu
2. Check "Marketplace"
3. Try to install manually. "From URL" and "from file" don't work.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0
- Operating System: 4.15.15
- Deployment Method: tar
- NodeJS Version: 8.11.3

**Comment by bbrendon** [comment]
Just to be clear the list of Apps that appear in the marketplace is empty right? It is for me.

**Comment by piotrkochan** [comment]
It looks like 0.70.0 is most bugged version I've seen.

**Comment by chatnl** [comment]
> Just to be clear the list of Apps that appear in the marketplace is empty right? It is for me.

It is for me too now. Something is indeed wrong here.

**Comment by rodrigok** [comment]
Sorry for this issue guys, we are working to support apps matching a range of versions, right now the apps that was developed for version 0.69.0 will need to update their required api version to match the new one to be able to be listed for you to install.

We will have a fix for our marketplace soon, allowing apps to be submitted with a range of versions to prevent this to happen on next version.
