### ISSUE TITLE
Initials-Derrived-Icons Sometimes Uses Wrong Initials

### ISSUE THREAD

**Issue by blaskovicz** [RocketChat/Rocket.Chat#1222]
A few of us using  _RocketChat_ have noticed that sometimes, a person's initials will be incorrect.

We have been changing some avatars and renaming a few accounts lately, so perhaps it's related? Some of our usernames start with _da_, so it seems like _RocketChat_ is getting confused.

In chat, I see:
![image](https://cloud.githubusercontent.com/assets/10687433/10695216/9e9b9c8a-7970-11e5-8ebb-645c6cae952b.png)

Which should be (per the admin page):
![image](https://cloud.githubusercontent.com/assets/10687433/10695243/bd20dc74-7970-11e5-9c0a-e93de5abe746.png)

**Comment by gmsecrieru** [comment]
Might be related to #1168

**Comment by blaskovicz** [comment]
Note that I just experienced this after creating a channel, joining it, and then attempting to invite someone to it via the `/invite` command:

![image](https://cloud.githubusercontent.com/assets/10687433/10696405/9521c990-7975-11e5-9664-acc95f6b3ad9.png)

**Comment by blaskovicz** [comment]
I'm using chrome 46.0.2490.71

**Comment by sunnipaul** [comment]
That's what I've experienced recently. on Chrome for windows Version 46.0.2490.71 m

**Comment by engelgabriel** [comment]
Did you try cleaning the cache of your browser?

**Comment by tanc** [comment]
Clearing caches helped in my case, on Chrome and on the OS X app.

**Comment by Seicun** [comment]
Reloading the page sometimes help even without clearing the cache. So it seems the problem is not cache related.

**Comment by blaskovicz** [comment]
I opened the icon that was wrong in a new window (it showed _AH_ when it should have been showing _HB_). After `ctrl+f5`'ing the page, the icon updated.

I notice that the response is sending:

`cache-control:public, max-age=31536000`

Perhaps we could also use `ETag` and `If-None-Match` (and ditch `max-age`)?
[Related article.](https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers#content-based)

**Comment by engelgabriel** [comment]
Thinking about this bug, I think the issue is deeper than just cache. 

The avatar url is build with the username, so if you change the username, we have to update all the src attribute of avatars img tags on the screen of the online users, at the same time we update the username itself.

@rodrigok can you check if we are doing that at all?

I know we do that when a user update its Avatar, so maybe we just need to trigger that update when they update the username too.

**Comment by blaskovicz** [comment]
Maybe it makes more sense to look up the user avatar based on their `_id`?

**Comment by engelgabriel** [comment]
that would add a lot of extra complexity and database lookups... we are trying to keep things as fast and scalable as possible.

**Comment by rodrigok** [comment]
Probably this issue is related with renaming and update all clients with the new username. I will try to solve this today.

**Comment by rodrigok** [comment]
I can't reproduce this problem.

@blaskovicz, this problem still occurs for you?

**Comment by blaskovicz** [comment]
I think I saw it happening with our site still and we updated the code with the HEAD commit of master on monday.

**Comment by rodrigok** [comment]
@blaskovicz. Can you inspect the DOM when we you see this problem again and verify if the URL of the avatar is ending with the correct username and access this url in a new private tab to verify if the problem is some type of cache?

**Comment by engelgabriel** [comment]
I just saw this in our General room:

![image](https://cloud.githubusercontent.com/assets/1000217/11092245/dc5aa6e0-8868-11e5-8699-62f83b232cfc.png)

**Comment by rodrigok** [comment]
@blaskovicz, the problem was solved.

Thanks :smile:
