### ISSUE TITLE
Reopen closed room

### ISSUE THREAD

**Issue by vikas0121** [RocketChat/Rocket.Chat#12221]
**Is your feature request related to a problem? Please describe.**
If a customer wants to chat again on his closed chat because the customer does not want to write all the details again which he/she already described.
I'm working on doc online consultation chat app where customer get frustrated or agent is not able to see the last chat details.

**Comment by reetp** [comment]
Feature requests are nor being referred to the forums.

Please open a new thread there to discuss: https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
