### ISSUE TITLE
After edit the reply to a message, it multiplies. 0.70.0

### ISSUE THREAD

**Issue by nicexe2e4** [RocketChat/Rocket.Chat#12223]
### Description:

If you edit the reply/quote to a message, it is multiplies.

### Steps to reproduce:

1. Write a message
2. Reply/quote to message
3. Edit the reply/quote to the message
4. Edit the reply/quote to the message again

### Expected behavior:

The message does not multiply when you edit it.

### Actual behavior:

![image](https://user-images.githubusercontent.com/23378404/46285646-62f0ee80-c5a6-11e8-9bb9-f28a09a09d57.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0
- Operating System: 4.15.15
- Deployment Method: tar
- NodeJS Version: 8.11.3

**Comment by localguru** [comment]
I can confirm this.

**Comment by robbyoconnor** [comment]
I saw this and wasn't sure if it was a bug
