### ISSUE TITLE
Outdated REST API documentation for groups.list. Query param is no longer supported.

### ISSUE THREAD

**Issue by rjanas** [RocketChat/Rocket.Chat#12238]
### Description:

Documentation says: 'Lists all of the private groups the calling user has joined. It supports the Offset, Count, and Sort Query Parameters along with just the Fields Query Parameters.'
(https://rocket.chat/docs/developer-guides/rest-api/groups/list/)

Query param was added in api version 62 (https://github.com/RocketChat/Rocket.Chat/issues/9423)
and removed in version 66 in implementation of this ticket: https://github.com/RocketChat/Rocket.Chat/pull/10749

**Comment by MarcosSpessatto** [comment]
Closing it in favor of: https://github.com/RocketChat/docs/issues/943
