### ISSUE TITLE
Desktop version don't launch after server input

### ISSUE THREAD

**Issue by flpn** [RocketChat/Rocket.Chat#12244]
So, after I enter the server URL the application dives into an infinite loading. After checking the devops tools I found this error:

> Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING
C:\Users\felipe.netto\AppData\Local\Programs\Rocket.Chat\resources\app.asar\app\public\preload.js:75 
Uncaught ReferenceError: Meteor is not defined
    at C:\Users\felipe.netto\AppData\Local\Programs\Rocket.Chat\resources\app.asar\app\public\preload.js:75

Because of that I'm not able to use the desktop version of the Rocket. Any of you guys know what's happening?

**Comment by tassoevan** [comment]
This issue is related to the desktop client, please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!

**Comment by flpn** [comment]
Oh sorry, thanks for the feedback!
