### ISSUE TITLE
Read Group info from OAuth provider

### ISSUE THREAD

**Issue by hypery2k** [RocketChat/Rocket.Chat#12243]
**Is your feature request related to a problem? Please describe.**
Would be great to read group info from OpenID provider

**Describe the solution you'd like**
Allow mapping of OpenID attributes to groups, e.g list of role names for the user which gets mapped to rocket groups

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by hypery2k** [comment]
can somebody maybe point we to the code to change? If somebody helps we where the changes needs to be done, I'll great a PR

**Comment by FaizanZahid** [comment]
ask @rafaelks

**Comment by hypery2k** [comment]
I started with a real basic implementation. Maybe somebody could have a look. It's actually working, but only adds roles/groups, currently no update:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/979121/48301945-c3544380-e4f5-11e8-96cf-322bd0653a30.png">

**Comment by hypery2k** [comment]
@rafaelks Any suggestion on this approach?

**Comment by rafaelks** [comment]
@hypery2k I'm honestly not the most appropriate person to ask this question. If your approach is working, I would say for you to open a pull-request and propose it to be merged in Rocket.Chat so other can review it. 👍

**Comment by hypery2k** [comment]
@rafaelks Who would review my PR?

**Comment by Hudell** [comment]
Thank you for your contribution, @hypery2k. I'll check it out.

**Comment by hypery2k** [comment]
@Hudell Any news on this?

**Comment by hypery2k** [comment]
@FaizanZahid and @rafaelks Could somebody help me to get my PR merged?

**Comment by hypery2k** [comment]
PR seems to get merged soon
