### ISSUE TITLE
Can't able to get messages list using Rocket Chat API

### ISSUE THREAD

**Issue by nilekshdhimer** [RocketChat/Rocket.Chat#12246]
Hi there,

I am using Rocket Chat REST API to get messages.

Direct type rooms I can able to get messages but for a private group, I can't able to get messages.

I am using [https://rocket.chat/docs/developer-guides/rest-api/im/history/](url) this API.

Can anyone please help me to get a message from a private group?

**Comment by reetp** [comment]
Unless this really is a bug please close this and ask in the forums https://forums.rocket.chat/ or ask in #support at https://open.rocket.chat/
Thanks

**Comment by MarcosSpessatto** [comment]
@nilekshdhimer you should see this endpoint in the docs: https://rocket.chat/docs/developer-guides/rest-api/groups/history/. I'm closing this issue, if you have any problem, please feel free to reopen. Thanks.
