### ISSUE TITLE
Check Box to Select multiple users to add to a private group, public, or distribution list.

### ISSUE THREAD

**Issue by rodrigocolli** [RocketChat/Rocket.Chat#12251]
We are deploying in a brazilian public entity (Coren-MG) and there are demand for private group creation, public and distribution lists, but users are invited 1 to 1 and it would be interesting to have a check box so that we can select multiple users at once .

Unfortunately we are depending on this functionality to receive authorization for this software to be put into production.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
