### ISSUE TITLE
Failed to build rocket.chat server 0.69 & 0.70 - same problem

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#12258]
### Description:

Unable to build latest rocket.chat from 0.69 and 0.70 version

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69, 0.70
- Operating System:  centos 7
- Deployment Method:  tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: 2.6.12-1

### Additional context

Looks like problem with node-pre-gyp package. Reinstallation or upgrade of this package didnt help.
Im able to start and run rocket chat even with this error.

### Relevant logs:
> grpc@1.12.2 install /opt/Rocket.Chat/programs/server/npm/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/opt/Rocket.Chat/programs/server/npm/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote

> bcrypt@2.0.1 install /opt/Rocket.Chat/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
node-pre-gyp ERR! command "/root/.nvm/versions/node/v8.11.3/bin/node" "/opt/Rocket.Chat/programs/server/npm/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/Rocket.Chat/programs/server/npm/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the bcrypt@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-01T07_48_56_696Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-01T07_48_56_804Z-debug.log

**Comment by cogliostro** [comment]
Confirmed

**Comment by midse** [comment]
Same issue here with v0.70.4 : node 8.11.3 et npm 5.6.0
No issue with v0.68.x

**Comment by reetp** [comment]
Follow the link in the log.... that has similar issues:
https://github.com/mapbox/node-pre-gyp

**Comment by midse** [comment]
I found a workaround : https://github.com/mapbox/node-pre-gyp/issues/400
In `programs/server/npm/node_modules/bcrypt/` run the following command : `npm install node-pre-gyp@0.10.3 request --save`

It worked for me. :)

**Comment by reetp** [comment]
@rocketcat-close 

Closing based on https://github.com/RocketChat/Rocket.Chat/issues/12258#issuecomment-443586599
