### ISSUE TITLE
Whatsapp Bussines Provider

### ISSUE THREAD

**Issue by jersonjunior** [RocketChat/Rocket.Chat#12250]
It would be interesting to Rocket Chat to provide the Whatsapp Bussines API service, there are already companies providing this service.So a tip!

**Comment by reetp** [comment]
There are probably many who would like something like this, although I am not one, and here's why.

Go here:

https://www.whatsapp.com/business/api

Click 'Get Started' which has this URL https://www.whatsapp.com/business/apply

But directs you here:

https://www.facebook.com/business/m/whatsapp/business-api

Thanks, but no thanks.....

**Comment by jersonjunior** [comment]
Coming soon: https://developers.facebook.com/docs/whatsapp/overview

**Comment by reetp** [comment]
This is a new feature request and should be opened in the forums:
https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
