### ISSUE TITLE
Auto-subscribe to #general when first logging in with LDAP

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/Rocket.Chat#1226]
Currently, when you first log in with LDAP, you are not subscribed to any channels. Users should be auto-subscribed to #general just as with standard registration.

**Comment by gmsecrieru** [comment]
I think LDAP needs a label :)

**Comment by pioneer903** [comment]
Agreed. +1

**Comment by Theaxiom** [comment]
Thank you!
