### ISSUE TITLE
OSX client fails to remember size and position on login items start

### ISSUE THREAD

**Issue by ahayes** [RocketChat/Rocket.Chat#12269]
### Description:

Rocket.Chat OSX client does not restart with the same size and position.

### Steps to reproduce:

1. Open Rocket.Chat client. Shrink it down and put it in the bottom right of the screen.
2. Add it to your Login Items so it starts automatically when you log in.
3. Restart your computer and log in.

### Expected behavior:

I would expect it to start with the same window size in the same position.

### Actual behavior:

It starts slightly larger and only a bit right and lower of centre. Not as I left it.

### Server Setup Information:

N/A

### Additional context

OSX 10.13.6 on a 5K iMac (single screen) with Display resolution set to "More Space".

**Comment by Hudell** [comment]
I'll be closing this as it was created on the wrong repository. For client issues, please create the issue on [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron)
