### ISSUE TITLE
The icon on desktop in notifications is not visible.

### ISSUE THREAD

**Issue by maciej-w** [RocketChat/Rocket.Chat#12261]
### Description:

The icon in the notifications window in Windows 7 enterprise is not visible event though it exists and user can hover over it.
 

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

I want to be able to see Rocket Chat icon.

### Actual behavior:

![invisible icon](https://user-images.githubusercontent.com/12381590/46477767-53aab480-c7e3-11e8-8769-47df579d90f3.png)

### Server Setup Information:

- Version of Rocket.Chat: 2.12 installed client
- Operating System: Windows 7 Enterprise
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3 (local)
- MongoDB Version:

**Comment by kaiiiiiiiii** [comment]
Hi @maciej-w,

1. Please update to the latest desktop client version
2. You're in the wrong repository
3. The issue has already been addressed by someone else and should be fixed in the latest release


Cheers,
Kai

// CC: @TwizzyDizzy
