### ISSUE TITLE
Blue E2E bar should not be shown when E2E is disabled

### ISSUE THREAD

**Issue by quinox** [RocketChat/Rocket.Chat#12274]
### Description:

Starting from last Friday I see an E2E bar on top of every page asking for the end-to-end password, even though E2E is not enabled for my installation. This bar did not show up in any previous versions (my installation auto-updates every day if possible).

### Steps to reproduce:

1. Install 0.70.1
2. Verify E2E is disabled in the settings
3. Open any page and see the end to end encryption bar

### Expected behavior:

E2E is only shown when that feature is enabled.

### Actual behavior:

![image](https://user-images.githubusercontent.com/739770/46579448-49223200-ca12-11e8-87c1-26cb0d9423ee.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.1
- Operating System: Linux
- Deployment Method: Docker
- NodeJS Version: v8.11.3

### Additional context

To not confuse my users I've hidden it now by using a custom CSS rule:
```css
.rc-alerts.rc-alerts--large {
  display: none;
}
```

**Comment by avignat** [comment]
Fixed https://github.com/RocketChat/Rocket.Chat/pull/12272 wait for new release

**Comment by reetp** [comment]
@rocket-cat close

Fixed in 0.70.2
Please reopen if you experience further issues
