### ISSUE TITLE
[Livechat] Remove all chats

### ISSUE THREAD

**Issue by edurenye** [RocketChat/Rocket.Chat#12279]
I would like to be able to close and remove all the chats at once.
So we should add a button in the current chats list to do so.

**Comment by reetp** [comment]
@rocket-cat label enhancement

**Comment by knrt10** [comment]
On it, would like to fix this. @renatobecker  would you please add livechat label to it.

**Comment by knrt10** [comment]
Let me fix this issue

**Comment by edurenye** [comment]
Ok, I gave you push access to my repo, so you can update my pull request.
