### ISSUE TITLE
Android Only Issue with CA Lets Encrypt Certificate

### ISSUE THREAD

**Issue by blackhatethicalhacking** [RocketChat/Rocket.Chat#12277]
### Description:

Only on Android it does not work because of Certificate Issues

https://chat.blackhatethicalhacking.com

### Steps to reproduce:

Android App = Any version for Rocket Chat even latest 3.3 or Legacy = doesnt work.

Browser = works
Desktop = works
IoS = works

### Expected behavior:

Connect to our Server

### Actual behavior:

Check Screenshots

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu
- Deployment Method: Docker running on Google Cloud
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

*Check Screenshots*

### Additional context

Configuration:
/etc/nginx/sites-available/default 

# HTTPS Server
    server {
        listen 443 ssl;
        server_name chat.blackhatethicalhacking.com;

        error_log /var/log/nginx/rocketchat_error.log;

        ssl_certificate /etc/nginx/certificate.crt;
        ssl_certificate_key /etc/nginx/certificate.key;
        ssl_dhparam /etc/nginx/dhparams.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-E$
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 180m;

        location / {
            proxy_pass http://chat.blackhatethicalhacking.com:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forward-Proto http;
            proxy_set_header X-Nginx-Proxy true;
            proxy_redirect off;
        }
    }

So,
I am running and testing both using BlueStacks, installing 3 rocket chat applications, including the legacy and 3.3.

Tested on 4 Android Phones too, using latest Version

nothing Works, can you please advise and assist?

I tried it with self signed - iOS + Android Doesnt work
I try with Lets Encrypt, using CloudFlare to point to that server IP running on Google Cloud

And only Android DOES not work

Tried importing the certificate to install it manually, but check screenshot regarding the flag issue, and since its created by Lets Encrypt it means i dont get to choose the flag option.

![capture2](https://user-images.githubusercontent.com/13942386/46597467-d5068d80-cae8-11e8-9029-77c4892a9ed6.JPG)
![capture](https://user-images.githubusercontent.com/13942386/46597468-d5068d80-cae8-11e8-82fa-9a0041d097a0.JPG)
![capture1](https://user-images.githubusercontent.com/13942386/46597469-d5068d80-cae8-11e8-878f-ce5de57de685.JPG)

Log Files:

**cat /var/log/nginx/access.log**

217.16.xxx - - [08/Oct/2018:08:52:38 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
217.16.xxx - - [08/Oct/2018:08:52:38 +0000] "GET /packages/rocketchat_videobridge/client/public/external_api.js?_=1538988757734 HTTP/1.1" 200 3603 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
217.16.xxx - - [08/Oct/2018:08:52:38 +0000] "GET /assets/logo.png HTTP/1.1" 304 0 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
217.16.xxx - - [08/Oct/2018:08:52:38 +0000] "GET /assets/background.png HTTP/1.1" 304 0 "https://chat.blackhatethicalhacking.com/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
217.16.xxx - - [08/Oct/2018:08:52:40 +0000] "GET /sockjs/023/q2kkg3dd/websocket HTTP/1.1" 101 5703 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:41 +0000] "GET / HTTP/1.1" 200 29185 "https://github.com/RocketChat/Rocket.Chat/issues/12277" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:41 +0000] "GET /9b704c621adc8a1dcae59307e0023894dbfd2413.css?meteor_css_resource=true HTTP/1.1" 200 68758 "https://chat.blackhatethicalhacking.com/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:41 +0000] "GET /theme.css?c6acb53b66e83874608c9b0c5ddef08da8733203 HTTP/1.1" 200 11329 "https://chat.blackhatethicalhacking.com/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:42 +0000] "GET /c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true HTTP/1.1" 200 1329616 "https://chat.blackhatethicalhacking.com/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /assets/favicon.svg HTTP/1.1" 200 1549 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /sounds/beep.mp3 HTTP/1.1" 206 6318 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /sounds/chelle.mp3 HTTP/1.1" 206 33489 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /sounds/ding.mp3 HTTP/1.1" 206 24737 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /sounds/droplet.mp3 HTTP/1.1" 206 6059 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /sounds/seasons.mp3 HTTP/1.1" 206 17664 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:44 +0000] "GET /sounds/highbell.mp3 HTTP/1.1" 206 65745 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:45 +0000] "GET /sockjs/info?cb=u2et55f85v HTTP/1.1" 200 89 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:45 +0000] "GET /_timesync HTTP/1.1" 200 13 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:45 +0000] "GET /packages/rocketchat_videobridge/client/public/external_api.js?_=1538988819199 HTTP/1.1" 200 3603 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:46 +0000] "GET /assets/logo.png HTTP/1.1" 200 1090722 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:46 +0000] "GET /assets/background.png HTTP/1.1" 200 1229351 "https://chat.blackhatethicalhacking.com/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:55:54 +0000] "GET /theme.css?c6acb53b66e83874608c9b0c5ddef08da8733203 HTTP/1.1" 200 11329 "https://chat.blackhatethicalhacking.com/home" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
93.174.52.2 - - [08/Oct/2018:08:56:31 +0000] "GET /sockjs/380/s9ymlq5s/websocket HTTP/1.1" 101 5757 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

**cat /var/log/nginx/error.log**
2018/10/08 08:41:49 [alert] 7262#7262: *93 open socket #16 left in connection 2
2018/10/08 08:41:49 [alert] 7262#7262: *94 open socket #17 left in connection 9
2018/10/08 08:41:49 [alert] 7262#7262: aborting
2018/10/08 08:41:49 [emerg] 18744#18744: "proxy_http_version" directive is not allowed here in /etc/nginx/nginx.conf:88
2018/10/08 08:52:07 [alert] 18914#18914: *3 open socket #11 left in connection 3
2018/10/08 08:52:07 [alert] 18914#18914: *4 open socket #12 left in connection 4

**Comment by avs-ru** [comment]
Maybe check this page? I think this is not problem of RC, but LE and Android...
https://community.letsencrypt.org/t/should-i-add-both-dst-root-ca-x3-and-isrg-root-x1-intermediates/68468

**Comment by blackhatethicalhacking** [comment]
Thanks @avs-ru Checked it, it explains using Apache2, in my case, i am using Nginx.

I tried to work with Apache2 as well, but no chance to let it work through the APP.

So they talk about intermediate certificate, i mean:

If there is known way to make my issue work by changing nginx? (Which i dont recommend)

And would fix this "known" Android depending issue, please let me know, since IoS, Web, Desktop work, maybe provide a clear workaround - so we an edit 

Until something is figured to revert back to once a solution is found and so on.

**Comment by avs-ru** [comment]
@blackhatethicalhacking 
Running SSL Tests on your URL and result this:
![image](https://user-images.githubusercontent.com/43571461/46602368-a395be00-caf8-11e8-8dd7-f64fb1149860.png)

But on my server with LE cert:
![image](https://user-images.githubusercontent.com/43571461/46602546-320a3f80-caf9-11e8-87db-5b6d2323627b.png)

**Comment by blackhatethicalhacking** [comment]
I see, so what do you advise? Since its created by Lets Encrypt, in order to make it A+ too?

**Comment by avs-ru** [comment]
@blackhatethicalhacking 
Our internal users do not have any problems with Android Clients.

Server stays behind haproxy as reverse proxy and terminates SSL. And HAProxy send fullchain to clients.
In general HAProxy configured by this manual: https://serversforhackers.com/c/letsencrypt-with-haproxy

**Comment by kaiiiiiiiii** [comment]
Replace 'ssl_certificate' in your nginx config file with the path to the fullchain.pem and everything will work as intended :)

https://gist.github.com/cecilemuller/a26737699a7e70a7093d4dc115915de8#stronger-settings-for-a

**Comment by blackhatethicalhacking** [comment]
Thanks @kaiiiiiiiii That explains why most probably Android isnt working.

Still need to clarify Please.

To have the fullchain.pem, you need to:

Copy from certificate.key the values
Copy from certificate.pem the values

Create a new called trusted.pem

Paste (in any order) the 2 values --> gives us the full chain

After that, edit: /etc/nginx/sites-enabled/default

# HTTPS Server
    server {
        listen 443 ssl http2;
        server_name chat.blackhatethicalhacking.com;

        error_log /var/log/nginx/rocketchat_error.log;

        ssl on;
        **ssl_trusted_certificate /etc/nginx/trusted.pem;**
        ssl_certificate /etc/nginx/certificate.crt;
        ssl_certificate_key /etc/nginx/certificate.key;
        ssl_dhparam /etc/nginx/dhparams.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGC$
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 180m;

  location / {
            proxy_pass http://127.0.0.1:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forward-Proto http;
            proxy_set_header X-Nginx-Proxy true;
            proxy_redirect off;
        }
    }


If that is the case, i still have an issue.

BTW, i did not use Certbot, i generated the SSL from Lets Encrypt through CPANEL of the hosting.

But that should be OK too, since the certificate works on IOS / Desktop

Please advise why still it isnt working ?

**Comment by reetp** [comment]
@blackhatethicalhacking this is really a support issue for your configuration and not a bug, and should be closed (unless you have evidence to suggest it is a bug)
See https://rocket.chat/docs/contributing/reporting-issues/
You should raise this in https://forums.rocket.chat/c/community-support or https://open.rocket.chat/channel/support
As an aside letsencrypt should have already generated you a fullchain.pem file along with a cert.csr, cert.pem and privkey.pem

**Comment by kaiiiiiiiii** [comment]
@blackhatethicalhacking `fullchain.pem` is a concatenation of cert.pem and chain.pem. When you use certbot it will be auto generated under `/etc/letsencrypt/live/domain/fullchain.pem`.

But as @reetp said, this looks like a support case to me as well which should be moved to the forums or open.chat :)

// CC: @TwizzyDizzy

**Comment by blackhatethicalhacking** [comment]
Thanks, will close investigate tonite and open if its a bug.
