### ISSUE TITLE
Pasting from primary selection doesn't work in Ubuntu, GNOME

### ISSUE THREAD

**Issue by zerthimon** [RocketChat/Rocket.Chat#12271]
nuff said

**Comment by localguru** [comment]
Hi, sorry, but could you elaborate a little more please? I have no problems with copy & paste.

**Comment by zerthimon** [comment]
Sometimes pasting to rocket chat from primary selection actually pastes
what's in clipboard (ctrl-c).
Pasting the same selection to other application at the same time pastes
correctly.

пн, 8 окт. 2018 г. в 20:25, John Crisp <notifications@github.com>:

**Comment by reetp** [comment]
OK, you really aren't giving anyone anything to go on here.
Did you read this when you started this bug?
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
There are good reasons for filling that out. Without this sort of information no one can help you and you are just going to get ignored.
What Rocket version/deployment? Is this pasting to a browser or the desktop app?

**Comment by reetp** [comment]
This seems to be a desktop client issue. Please either open a bug under the relevant client or seek help in the forums https://forums.rocket.chat/ or chat https://open.rocket.chat
Closing notabug. 

Please re open if you have issues with Rocket.Chat server itself.

**Comment by reetp** [comment]
@rocket-cat close
