### ISSUE TITLE
Version 0.70.2 shows up as 0.70.1

### ISSUE THREAD

**Issue by himpich** [RocketChat/Rocket.Chat#12280]
https://github.com/RocketChat/Rocket.Chat/commits/0.70.2

The Version (which is displayed in the admin panel) was bumped to 0.70.1 instead of 0.70.2

Regards,
Stefan

**Comment by reetp** [comment]
This is a duplicate of:

https://github.com/RocketChat/Rocket.Chat/pull/12276

Closed with:

https://github.com/RocketChat/Rocket.Chat/pull/12281

Please close this bug thanks.

**Comment by himpich** [comment]
Fixed as of release v0.70.3
