### ISSUE TITLE
Top navbar in embedded layout mode

### ISSUE THREAD

**Issue by sdelfi** [RocketChat/Rocket.Chat#12287]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Previously navbar was removed in embedded mode:
https://github.com/RocketChat/Rocket.Chat/pull/12025/files#diff-e7c838650739eb4cc3317679e1881c6d

However, it is necessary in some cases. Therefore, now we cannot update to the current chat version (in the new versions, important bugs for us have been fixed).

Is it possible to make an extended-embedded layout or another way to activate the top panel in embedded mode?

**Additional context**
![image](https://user-images.githubusercontent.com/1927032/46629773-ad481180-cb4a-11e8-9919-a71adb5bc5da.png)

**Comment by sdelfi** [comment]
### Description:
Previously navbar was removed in embedded mode: [https://github.com/RocketChat/Rocket.Chat/pull/12025/files#diff-e7c838650739eb4cc3317679e1881c6d](url)

However, it is necessary in some cases. Therefore, now we cannot update to the current chat version (in the new versions, important bugs for us have been fixed).

Is it possible to make an extended-embedded layout or another way to activate the top panel in embedded mode?

See 0.70.0-rc.0 release description:
Hidden admin sidenav on embedded layout (#12025)

### Steps to reproduce:
1. Embed chat to site and open it. (For Example https://open.rocket.chat/channel/general?layout=embedded)

### Expected behavior:

I see navbar where I can do things in embed iframe. 
Previously, top navbar was always displayed. It would be nice if you had the ability to customize the display for different embeds
![image](https://user-images.githubusercontent.com/1927032/46813428-58411100-cd7f-11e8-8af8-80d132d80bb2.png)

### Actual behavior:
Navbar is hided: 
![image](https://user-images.githubusercontent.com/1927032/46813534-8f172700-cd7f-11e8-9122-73ad40ac3d00.png)


### Server Setup Information:

- Version of Rocket.Chat Server: 0.72
- Operating System: Windows
- Deployment Method: docker
- Number of Running Instances:  1

**Comment by sdelfi** [comment]
@ggazzo that's right, it was earlier possible.
Now we use iframe chat in several places and in some we would like to be able to turn it on, and in some - not. If it is, of course, possible to make customizable.

**Comment by rasos** [comment]
A more flexible solution would be to accept an addition parameter `?layout=embeddedTopNavOn` and let that override the setting.
