### ISSUE TITLE
Better `Admin >> Rooms` Hover/Click Styles

### ISSUE THREAD

**Issue by blaskovicz** [RocketChat/Rocket.Chat#1228]
Could the `admin >> rooms >> <room name>` links be updated to `cursor: pointer` on hover at the very least? It wasn't immediately obvious to me that these were clickable. 

![image](https://cloud.githubusercontent.com/assets/10687433/10704682/8b84729e-79a6-11e5-8075-35ad9be5aea9.png)

I can try to submit a pull request for this if I have time.

**Comment by karmacoma** [comment]
Hi,

I submitted a pull request already which has already been merged.

Please see: https://github.com/RocketChat/Rocket.Chat/pull/1205

**Comment by gmsecrieru** [comment]
Fixed on #1205
