### ISSUE TITLE
LDAP-Search.error  SizeLimitExceededError: Size Limit Exceeded 

### ISSUE THREAD

**Issue by VareliyK** [RocketChat/Rocket.Chat#12284]
### Description:
Users can not login to chat.
In AD we have 3400 users

We increased limits settings in User Search to 4000, but it did not solve problem
### Server Setup Information:

- Version of Rocket.Chat Server: 0.64.1
- Operating System: Linux (3.10.0-693.21.1.el7.x86_64)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disable

### Server log:

[34mI20181008-15:14:37.788(0) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Search.error { SizeLimitExceededError: Size Limit Exceeded     at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at end (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:66:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:112:10)     at end (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:66:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:112:10)     at end (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:66:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:112:10)     at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:594:20)  lde_message: 'Size Limit Exceeded', lde_dn: null } 
[34mI20181008-15:14:37.789(0) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error { SizeLimitExceededError: Size Limit Exceeded     at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)     at end (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:66:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:112:10)     at end (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:66:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:112:10)     at end (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:66:19)     at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:112:10)     at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:594:20)  lde_message: 'Size Limit Exceeded', lde_dn: null } 
[34mI20181008-15:14:38.788(0) [34mLDAP ➔ Search.info Idle 
[34mI20181008-15:14:38.789(0) [34mLDAP ➔ Connection.info Disconecting 
[34mI20181008-15:14:38.794(0) [34mLDAP ➔ Search.info Closed

**Comment by avs-ru** [comment]
Maybe this error rising on user with long DN? (DN > 255 characters)

**Comment by reetp** [comment]
First thing - can you try on an updated version. A lot has changed since 0.64.1

Also note comments like this:
https://stackoverflow.com/questions/3378142/ldap-ldap-sizelimit-exceeded

Can you limit the search query in your LDAP query string ?

**Comment by VareliyK** [comment]
> First thing - can you try on an updated version. A lot has changed since 0.64.1
> 
> Also note comments like this:
> https://stackoverflow.com/questions/3378142/ldap-ldap-sizelimit-exceeded
> 
> Can you limit the search query in your LDAP query string ?

Our limit in rocket.chat is 1000. 
0.64.1 - it's stable version. I think - new version - new bug :)

**Comment by reetp** [comment]
There is no real 'stable' version when you are below 1.0 Think Beta at best..... and development is rapid. You are probably better off keeping reasonably up to date with incremental changes rather than one big leap.
You are 6 versions (6 months) out of date. If you aren't going to update you need to check the changelogs to see if there is anything that may relate to this. Ideally test on the latest.

**Comment by VareliyK** [comment]
We solved this issue - increase limit on AD server up to 5000.

**Comment by reetp** [comment]
OK. As per my comments I'd still suggest you look at updating though.

**Comment by reetp** [comment]
@rocket-cat close
Closing notabug
