### ISSUE TITLE
need a feature to add third people when in Direct Messages scenario

### ISSUE THREAD

**Issue by mamashuodedui** [RocketChat/Rocket.Chat#12289]
**Is your feature request related to a problem? Please describe.**
when chatting with other people in Direct Messages, the 3rd people is needed to add to provide help most often

**Describe the solution you'd like**
in one window of the direct messages , add a button to add user like the private group 

**Describe alternatives you've considered**

**Additional context**

**Comment by kaiiiiiiiii** [comment]
Duplicate of ##4489

// CC: @TwizzyDizzy

**Comment by nelsongraca** [comment]
any news on this? My users are requesting this too

**Comment by reetp** [comment]
> any news on this? My users are requesting this too

This Issue is closed as a duplicate. Have you actually looked at the original Issue to see progress?

**Comment by nelsongraca** [comment]
Sorry commented on the wrong one
