### ISSUE TITLE
Accepting OTR -> 404 Not Found

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#12291]
### Description:

When initiating an OTR session, after the other user confirms the session, they get an error message "404 Not Found". The URL changed from `https://example.com/direct/username` to `https://example.com/direct`.
<img width="573" alt="screenshot" src="https://user-images.githubusercontent.com/2821879/46656443-5aa04100-cbae-11e8-98be-886e34c3b4b0.png">

### Steps to reproduce:

1. Login as user 'A' in one browser
2. Login as user 'B' in another browser
3. Open a direct channel between users 'A' and 'B'
4. User 'A' initiates an OTR session to user 'B'
5. User 'B' accepts the OTR session

### Expected behavior:

Users 'A' and 'B' can chat in OTR

### Actual behavior:

User 'B' gets the error message like in the example above, the URL changes to `https://example.com/direct`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.5
- Operating System: Linux

### Additional context

- Chrome Browser 69.0.3497.100 (64-Bit) on OSX 10.13.6 in normal and in incognito mode.

**Comment by reetp** [comment]
Can you advise more install details e.g. deployment method etc. (See the bug template)
Can you test with the most recent version eg 0.70.4
Can you test with other browsers.
Thanks.

**Comment by fcoppolani** [comment]
Hi @jschirrmacher are you behind a reverse proxy ? If yes, which one (nginx or apache etc..) ?

**Comment by jschirrmacher** [comment]
No, there is no reverse proxy.

I tried with Safari and Firefox and the problem remains.
I tried with 0.70 and the problem stays the same.
Our normal server is installed as rpm on a Linux machine. The test with 0.70 was made on a local installation (`meteor npm start`)

**Comment by jschirrmacher** [comment]
Is there any news regarding this issue? Do you have any ideas where the problem comes from or how it could be solved?

**Comment by jschirrmacher** [comment]
Seems to be resolved in the meantime, at least with version 1.3.x
