### ISSUE TITLE
Direct Reply broken in 0.70.3

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#12290]
### Description:

One of my favorite features is broken since 0.70.0. It seems there is no reply-to header like 
`
rocketchat+9c536ee4-5faa-4e42-84c1-ad4af96ac781@rocketchat.mydomain.com
`
set anymore. 

### Steps to reproduce:

1. Enable Direct Reply
2. Mention a person who is not logged in
3. Mentioned person gets email without reply-to header

### Expected behavior:

Possibility to answer per mail.

### Actual behavior:

Answering per mail not possible.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.3
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8.12.0
- MongoDB Version: 3.6

Please bring back direct reply. :-)

**Comment by localguru** [comment]
As long as HTML formatted e-mails and special characters are "eaten up", `direct reply` in my opinion is only of limited use anyway. I hope this will be fixed in the upcoming 0.71 version. Then I will use it again.

**Comment by sampaiodiego** [comment]
@himpierre are you sure `Direct Reply` is still enabled on your server? because [looking at this code](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/functions/notifications/email.js#L116) seems that the `Reply-To` is still being added.

**Comment by himpierre** [comment]
>are you sure Direct Reply is still enabled on your server?

@sampaiodiego yes. i just tripple checked.

**Comment by himpierre** [comment]
@sampaiodiego is the issue fixed in 0.71.0-rc0? should i try? thanks and cheers

**Comment by sampaiodiego** [comment]
@himpierre I've just submitted a fix for this, thx https://github.com/RocketChat/Rocket.Chat/pull/12392
