### ISSUE TITLE
[BUG] I can't view private channel's

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#12305]
### Description:

I'm a admin and can't view private channel's

### Steps to reproduce:

1. Go to search bar
2. Search for private channel

### Expected behavior:

I can view private channel's

### Actual behavior:

I can't view private channel's

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Linux Ubuntu 4.4.0-1066-aws x64
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 131 migration

### Relevant logs:

![image](https://user-images.githubusercontent.com/17053653/46752794-7f6ee400-cc94-11e8-86d2-ca321654ed5b.png)

![image](https://user-images.githubusercontent.com/17053653/46752822-8dbd0000-cc94-11e8-959a-d354070b8fe6.png)
![image](https://user-images.githubusercontent.com/17053653/46752856-a0373980-cc94-11e8-9101-8795630517c1.png)

![image](https://user-images.githubusercontent.com/17053653/46752891-b3e2a000-cc94-11e8-8450-a09a5d7903cf.png)

![image](https://user-images.githubusercontent.com/17053653/46752914-c0ff8f00-cc94-11e8-974c-bc9b04aeb291.png)

![image](https://user-images.githubusercontent.com/17053653/46752923-c65cd980-cc94-11e8-9c76-5efa05a401b1.png)

![image](https://user-images.githubusercontent.com/17053653/46752933-cc52ba80-cc94-11e8-9e2d-185a0cbc7fdb.png)

**Comment by Hudell** [comment]
That's correct, even as an admin you can't access a private group that you were not invited to.

**Comment by guilhermecfviana** [comment]
@localguru I'm not member of the private groups I'm looking for, but I understanding this, maybe develope this feature ? https://github.com/RocketChat/Rocket.Chat/issues/12307

**Comment by kaiiiiiiiii** [comment]
Please read all comments in the following issue:

https://github.com/RocketChat/Rocket.Chat/issues/2869

This feature will be released as an paid app in the future, no plans to include it in the servers core.

Cheers,
Kai

// CC: @TwizzyDizzy
