### ISSUE TITLE
Server-side enforcing OTR chats

### ISSUE THREAD

**Issue by r3ggi** [RocketChat/Rocket.Chat#12304]
Hey,

Have you guys considered implementing server-side OTR chats enforcement? I would really appreciate feature that wouldn't allow to use plain-text communication through the Rocket.chat. It would be great when direct messages will be automatically encrypted without the manual clicking OTR, confirming etc.

Cheers!

**Comment by reetp** [comment]
Please note that NFRs are being referred to the forums.

Please open a new thread at  https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
