### ISSUE TITLE
Mp4 video not working in iphone version

### ISSUE THREAD

**Issue by VinhNguyenDucThuy** [RocketChat/Rocket.Chat#12311]
### Description:
I send record video to friend. Video not play in iphone. But it work in android. 
Video link: https://ica.hdtex.group/file-upload/Pe8QR8u7ACie6ouoo/4Ot4hGScy2kcz6u80Nrw.mp4?rc_uid=s23Hen62SKh9DuT4D&rc_token=LjoYV5AUXt-LPmtd2YCC2oQDLbDTG83bNK3FvaLfkly
Image in below:
![img_0002](https://user-images.githubusercontent.com/27967101/46776753-3459dd00-cd37-11e8-912d-6053db57611f.png)
![img_0003](https://user-images.githubusercontent.com/27967101/46776754-3459dd00-cd37-11e8-87b9-b2ae63d8173b.png)

### Steps to reproduce:

1.  Chosse friend to chat
2.  Tap to button + and select record video
3.  Record video and send to friend
4. Click to video but not working
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by localguru** [comment]
I would also open the ticket in the "iOS" branch. I don't think this is a server problem.

**Comment by reetp** [comment]
@rocket-cat close

**Comment by hungntq** [comment]
After a week of investigate. I found the answer at [here](https://stackoverflow.com/questions/33823411/avplayer-fails-to-play-video-sometimes/42244954#42244954)

I also see that storage with GridFS, video play normally on iOS device. And follow GridFS config, I found the answer.

Here is how I fix this problem

```
import { readFromGridFS } from "/app/file-upload/server/config/GridFS";

const FileSystemUploads = new FileUploadClass({
	name: 'FileSystem:Uploads',
	// store setted bellow

	get(file, req, res) {
		const filePath = this.store.getFilePath(file._id, file);

		try {
			const stat = Meteor.wrapAsync(fs.stat)(filePath);

			if (stat && stat.isFile()) {
				file = FileUpload.addExtensionTo(file);
				res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${ encodeURIComponent(file.name) }`);
				res.setHeader('Last-Modified', file.uploadedAt.toUTCString());
				res.setHeader('Content-Type', file.type || 'application/octet-stream');
				res.setHeader('Content-Length', file.size);

				return readFromGridFS(file.store, file._id, file, req, res);
				// this.store.getReadStream(file._id, file).pipe(res);
			}
		} catch (e) {
			res.writeHead(404);
			res.end();
		}
	},

	copy(file, out) {
		const filePath = this.store.getFilePath(file._id, file);
		try {
			const stat = Meteor.wrapAsync(fs.stat)(filePath);

			if (stat && stat.isFile()) {
				file = FileUpload.addExtensionTo(file);

				return readFromGridFS(file.store, file._id, file, req, res);
				// this.store.getReadStream(file._id, file).pipe(out);
			}
		} catch (e) {
			out.end();
		}
	},
});```
