### ISSUE TITLE
After updating, same update is offered again

### ISSUE THREAD

**Issue by AndreSomers** [RocketChat/Rocket.Chat#12313]
### Description:

On starting up the Rocket.Chat client, I get a message an update is available. I click to accept the update, install the update (for only this user) and it gets installed which restarts the client. No errors are shown. On the next start of the client, the same update available message for the same versions is shown again.  

### Steps to reproduce:

1. Run an outdated client
2. Start up the client to get the update available dialog
3. Accept the update, and install it
4. On restart, observe the update available dialog appearing again.

### Expected behavior:

I would have expected the update to be properly installed and the same update just installed not being offered again.

### Actual behavior:

See above: same update is offered again for the same outdated version of Rocket.Chat.
![snap 2018-10-11 at 08 55 33](https://user-images.githubusercontent.com/10531631/46786118-353d3f80-cd34-11e8-92b4-899c21cc04fa.png)

### Server Setup Information:

Rocket.Chat installed version: 2.13.1
Rocket.Chat offered update version: 2.14.0

### Additional context

Windows 10, all updates installed

**Comment by localguru** [comment]
I just installed the new 2.14.0 on Linux and can't confirm that. I would also open the ticket in the Android branch.

**Comment by media32** [comment]
We experience the same issue in our office with not being able to install updates through the MacOS Rocket.Chat app, on both High Sierra and Mojave.  We all have to download the app from the Rocket.Chat website to update.

**Comment by kaiiiiiiiii** [comment]
Please open an issue in the electron repository, as this one is for the server component.

https://github.com/RocketChat/Rocket.Chat.Electron

Thanks,
Kai

// CC: @TwizzyDizzy

**Comment by AndreSomers** [comment]
Ok, yes, sorry. Copied over the report to the component you @kaiiiiiiiii  mentioned.
