### ISSUE TITLE
File type changes when renaming it before download

### ISSUE THREAD

**Issue by CEfros** [RocketChat/Rocket.Chat#12318]
### Description:
When I download an image from a chat and rename it before saving it to my computer, the file type is changed to FILE as opposed to PNG Image. When downloading without changing the name of the image, it gets saved as PNG Image.

### Steps to reproduce:
1. Click the download button next to uploaded file name
2. Rename the file
3. Click 'Save'

### Expected behavior:
File's type remains the same, e.g PNG Image

### Actual behavior:
Saved file has .file extension

### Server Setup Information:
Rocket.Chat installed version: 2.14.0

### Additional information:
I cannot include the faulty file here because the file type 'FILE' is not supported

**Comment by reetp** [comment]
You do not have Rocket 2.14 installed. That is most likely  the Electron client version.

You don't specify your server operating system, rocket server version or desktop OS version, without which it is hard to tell what is happening.

Have you tried to do with a browser and does that work as expected?

Please go back and fill in some of the details.

Thanks.

**Comment by tassoevan** [comment]
This issue is related to the desktop client, please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
