### ISSUE TITLE
RocketChat 2.14.0: window does not gets focus after minimized to tray

### ISSUE THREAD

**Issue by ncgodinho** [RocketChat/Rocket.Chat#12316]
### Description:
I'm using Windows 10 Pro, version 1803 SO 17134.345 and I work with an external monitor connect to my Toshiba Sattelite Pro A50-E-11E, Intel Core I7-8550U, 1.8Ghz, 16Gb RAM, 256 Gb SSD Drive.

After installing RocketChar version 2.14.0, after minimizing the app to the systray I couldn't get it back on screen. I had to close the app and open it again. The window simply did not appear on screen. It flashes briefly and then disappears. 

1. Open RocketChat
2. Minimize it to systray
3. Go to the Systray and try to open it again

### Expected behavior:

Open the App window

### Actual behavior:

Flashes and disappears

Come on guys :D !!! 
No time for all of this. 
I already tried to give you as much details as possible in the description. Please read it! :D 
Hope it helps! 
Best regards!

P.S: I reinstalled 2.13.3 and it works like a charm!!!!

**Comment by localguru** [comment]
I would also open the ticket in the "Electon" branch. I think it is not a server problem.

**Comment by ncgodinho** [comment]
I think this a problem with my computer. My colleagues had no problems are emailing me saying they have no problems!
I'll try to reinstall 2.14.0
