### ISSUE TITLE
no monitor autodetect on windows

### ISSUE THREAD

**Issue by fozzybaer** [RocketChat/Rocket.Chat#12314]
### Description:

I'm working with the rocket chat app on a windows laptop. There is a monitor connected to the laptop while working in the company. Usually I have the app shown on the bigger screen of the external monitor.

### Steps to reproduce:

1. run the app on a windows pc with additional monitor on the extended 2. monitor. 
2. Shut down the app and windows and restart the system without monitor, like you have it for example on the road or in the home office.
3. Start the rocket chat app.

### Expected behavior:

the rocket chat app should be start properly on your laptop screen.

### Actual behavior:

the rocket chat app pops up on the (non exisiting) other monitor. You need to use cursor window movement to actually get it back on your laptop screen.

### Server Setup Information:

- Version of Rocket.Chat Server: Version 2.13.3
- Operating System: Windows

**Comment by localguru** [comment]
I would also open the ticket in the "Electron" branch. I think this is not a server problem.

**Comment by reetp** [comment]
Closing notabug
Please open an issue here if required
https://github.com/RocketChat/Rocket.Chat.Electron/issues/new

**Comment by reetp** [comment]
@rocket-cat close
