### ISSUE TITLE
Feature request: Reactions in message info

### ISSUE THREAD

**Issue by Crazy-Hopper** [RocketChat/Rocket.Chat#12326]
Hello,

When message has some reactions, the list of reacted people is shown in the popup when mouse is hovered on the specific reaction. Unfortunately, this popup shows usernames instead of real names,
but that's not the main problem. The problem arises when single reaction has a huge list of people, the popup shows the start of the list and "and N more reacted with XXX". The problem is that I see no way to find out those N more people.

As a solution I would suggest adding a new column into the "Message info" non-modal (?) dialog right between the real names and the read timestamp, which would show the list of reactions each member set. Would prefer all reactions to be displayed as icons of course. :-) And the whole column could be made to be right-aligned.

**Comment by localguru** [comment]
Hello Eugene, I would rather post your feature request in the Rocket.chat forum: 

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
Closing notabug.

**Comment by reetp** [comment]
@rocket-cat close
