### ISSUE TITLE
Feature requests: github or forums.rocket.chat?

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12327]
### Description:

If feature requests should not be posted here but on https://forums.rocket.chat, then the possibility for a feature request should no longer be offered here under "new issues" or the template should refer to the forum.

![grafik](https://user-images.githubusercontent.com/8544984/46907782-1e574280-cf18-11e8-8434-72c9e4ad4120.png)

**Comment by reetp** [comment]
This is in the process of being fixed.
https://github.com/RocketChat/Rocket.Chat/pull/12306
https://github.com/RocketChat/docs/pull/948

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
This can probably be closed in favour of the above

**Comment by reetp** [comment]
@rocket-cat close
