### ISSUE TITLE
Links containing ":" (e.g. LinkedIn links) will render emojis

### ISSUE THREAD

**Issue by peterk** [RocketChat/Rocket.Chat#12321]
### Description:

Pasting links containing the colon character will render an emoji instead of the proper link text. This is problematic for all LinkedIn post links that contains segments with `urn:li:`:

### Steps to reproduce:

1. Paste a LinkedIn post link in any chat in Rocket.chat.
2. Link segments is converted to emoji.

### Expected behavior:

No emojis replaced inside links.

### Actual behavior:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/19284/46834712-72451880-cdac-11e8-91de-867952069a0e.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.5
- Deployment Method: Docker
- Number of Running Instances: 1

### Additional context

Possibly related to #6770

**Comment by fcrespo82** [comment]
Hi! In the light of #Hacktoberfest I would like to help fix this bug.
Is this already being worked on, or can I help?

**Comment by tassoevan** [comment]
@fcrespo82 There are some open PRs aiming to fix the entire message rendering system and other ones related to a particular rendering issue, but I think there is not a single one addressing this problem yet.

**Comment by c-to-the-l** [comment]
A temporary workaround for this bug is to replace any `:`s in links with `&#58;`, which will stop the emoji from being inserted into the link.

Of course, this means hand-editing any messages that have this issue.

**Comment by knrt10** [comment]
On it, will try to fix this.

**Comment by ggazzo** [comment]
closed by #15516
