### ISSUE TITLE
file upload Amazon S3

### ISSUE THREAD

**Issue by ajaykumarCubix** [RocketChat/Rocket.Chat#12322]
Amazon S3 file uploading 

let img_info =  {
name: "project_comment_file5b7429b7efa97-Logo-420Dry-Opt-01.jpg",
size: 74942,
type: "image/jpeg"
}

let room_id = 'fKsJa5bG7gcZfYyXq';

let uploadFileRequest =function(img_info,room_id)
{
    sock.send(sendMessage({
        "msg": "method",
        "method": "slingshot/uploadRequest",
        "id": "upload_file_request",
        "params": [
            "rocketchat-uploads", // no idea
          img_info,
            room_id
        ]
    }))
}

msg: "result", id: "upload_file_request", result: {…}}
id: "upload_file_request"
msg: "result"
result:
download: "https://geniusportal.s3-us-west-2.amazonaws.com/ZfMm6yDQKdbkP6T9y/uploads/GENERAL/LmzKr6pSkS5nz3K2o/fKsJa5bG7gcZfYyXq"
upload: "https://geniusportal.s3-us-west-2.amazonaws.com"

img_info.url = "https://geniusportal.s3-us-west-2.amazonaws.com/ZfMm6yDQKdbkP6T9y/uploads/GENERAL/LmzKr6pSkS5nz3K2o/fKsJa5bG7gcZfYyXq";
img_info._id =  "fKsJa5bG7gcZfYyXq";

let sendFileChat = function(room_id,img_info)
{
    console.log(imageObject);
    sock.send(sendMessage({
        "msg": "method",
        "method": "sendFileMessage",
        "id": "send_file_message",
        "params": [
            room_id,
            "s3",
            img_info
        ]
    }))
}

file not upload passing this error

error:
error: 500
errorType: "Meteor.Error"
isClientSafe: true
message: "Internal server error [500]"
reason: "Internal server error"
__proto__: Object
id: "send_file_message"
msg: "result"

please help me

**Comment by reetp** [comment]
Can you please help the developers by filling out a proper bug report? They can't do much without this information.
Use this link: https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by geekgonecrazy** [comment]
Looks like you are trying to use slingshot.  We stopped using slingshot.  Please open a topic in our forum to discuss if you’d like
