### ISSUE TITLE
Duplicate dialog when saving AND/OR canceling file in the chat

### ISSUE THREAD

**Issue by jacekmusial** [RocketChat/Rocket.Chat#12333]
### Description:

Duplicate dialog is showing when user saves or cancel saving the file in the chat with one or many users.

### Steps to reproduce:

Path **a)**
1. Enter the chat with one or many members.
2. Click on filename to download any file posted by any user.
3. Click save in the modal dialog.

Path **b)**
1. Enter the chat with one or many members.
2. Click on filename to download any file posted by any user.
3. Click cancel in the modal dialog.

### Expected behavior:

**a)**
File is saved on your drive, nothing more happens.

**b)**
Nothing more happens, as you have closed modal dialog.

### Actual behavior:

**a) and b)**
The same modal dialog opens second time, besides what have you clicked earlier.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Linux / Docker
- Deployment Method: docker
- Number of Running Instances: 1
- OpLog: Disabled
- DB Replicaset Oplog: 
- NodeJS Version:  Node Version	v8.11.4
- MongoDB Version:   3.2

**Comment by reetp** [comment]
Can you please provide more information:

Rocketchat version
Desktop OS and client

**Comment by tassoevan** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/930?

**Comment by jacekmusial** [comment]
![image](https://user-images.githubusercontent.com/7474972/47134382-c9675380-d2ac-11e8-8b62-4092cff02c48.png)
I have 2.14.0 version of the Rocket Chat.

Yes, this is related to the https://github.com/RocketChat/Rocket.Chat.Electron/issues/930 issue, although I have always latest version of the Rocket Chat. Issue described there is similar to what people at my workplace are encountering.

**Comment by reetp** [comment]
@jacekmusial please don't duplicate issues.

If this is related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/930 then follow it up there as it appears to be an issue with the Electron client and not the Rocket.Chat server

**Comment by reetp** [comment]
@rocket-cat close

Please reopen if this turns out to be an issue with the server itself (check first with different browsers to see if they have the same issue)
