### ISSUE TITLE
Background Color Text Input

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#1233]
Could someone please be so kind and change the text input background-color from the static blue to @primary-background-color in /packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less in line 441. This makes it dynamic which I think it should be.

    .input-line {
		input[type='text'],
		input[type='password'],
		select {
			border-color: @tertiary-font-color;
			background-color: @primary-background-color;
			color: @input-font-color;
		}

		& label {
			color:@input-font-color;
		}
	}

**Comment by engelgabriel** [comment]
OK!

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/Rocket.Chat/commit/3b618e96eb1059d923fce2cf793e8441b6b317a4
