### ISSUE TITLE
Escaped Parentheses Followed by a Backslash Produces KaTeX Error in Chat

### ISSUE THREAD

**Issue by DLAtWork** [RocketChat/Rocket.Chat#12336]
### Description:

Sending a string with escaped parentheses followed by a backslash produces a KaTeX parser error in chat.

### Steps to reproduce:

1. Enter the following string in chat: `\(\.*\)`

### Expected behavior:

The text `\(\.*\)` will appear in chat.

### Actual behavior:

The error `KaTeX parse error: Can't use function '\.' in math mode at position 1: \̲.̲*` appears in chat.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Ubuntu 18.04.1
- Deployment Method: Snap
- Number of Running Instances: 1

### Additional context

It appears to be triggered by the backslash that immediately follows the escaped parentheses. Putting another character between the escaped parentheses and the backslash does not trigger the bug.

May be related to the following issues: #8640 #8644 #8676 #8970

**Comment by reetp** [comment]
This seems to be a bug in Katex, not Rocket.

Try it here https://katex.org/

![screenshot - 161018 - 11 52 54](https://user-images.githubusercontent.com/3800384/47008184-21317d80-d13a-11e8-9250-6d431416feba.png)

**Comment by gabriellsh** [comment]
This seems to only happen when using the markdown setting set to original.

**Comment by gabriellsh** [comment]
@khobbits Katex now won't render before Code block (#16012). As for the original topic of the issue, that's actually expected. You're basically opening a katex "block" using "\(", so it'll interpret it as Katex. You can either use codeline/block or disable Katex in the settings.

Thanks for your contribution!
