### ISSUE TITLE
Server RocketChat Falling

### ISSUE THREAD

**Issue by getcampestrini** [RocketChat/Rocket.Chat#12335]
Script "METEOR RUN --ALLOW-SUPERUSER" starts the server but if you leave on Putty (SSH), RocketChat server drops and exits the air

How to run the rocketchat server permanently without SNAP, my RocketChat was by git clone

### Steps to reproduce:

1. Git Clone the last version
2. Instal Dependencies
3. METEOR RUN ( npm start don't work )... I will start by Meteor...

Help me plz

**Comment by reetp** [comment]
This appears to be a support issue and not a bug.
Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

If you have errors with Rocket itself please reopen with full debug information including logs.

**Comment by reetp** [comment]
@rocket-cat close

**Comment by getcampestrini** [comment]
Thanks bro... have U de simple response?

**Comment by reetp** [comment]
Yes, I posted it. Ask in the forums or chat please!
