### ISSUE TITLE
OAuth nextcloud - rocketchat error

### ISSUE THREAD

**Issue by abate** [RocketChat/Rocket.Chat#12340]
I'm trying to use nextcloud ( version 14.0.2 ) with rocketchat 0.70.4 (db migratoin 135) .

These are the configuration options I added to nextcloud

/admin/security : ` rocketchat | https://chat.mydomain/_oauth/nextcloud <id> <secret> `

and on rocket chat I've added a new custom OAuth provides configured as 

url : https://cloud.mydomain
Token Path : /index.php/apps/oauth2/api/v1/token
Token Sent Via : PayLoad
Identity Token Sent Via : Same as "Token Sent Via"
Identity Path : /ocs/v2.php/cloud/user?format=json
Authorize Path : /index.php/apps/oauth2/authorize
Scope : openid
id : <id>
secret : <secret>
Username field : ocs.data.id
Merge User : false

In the rochet chat logs I get :
```
rocketchat_1  | {"line":"424","file":"oauth.js","message":"Error in OAuth Server: Failed to fetch identity from nextcloud at https://cloud.mydomain/ocs/v2.php/cloud/user?format=json. failed [401] {\"ocs\":{\"meta\":{\"status\":\"failure\",\"statuscode\":997,\"message\":\"Current user is not logged in\"},\"data\":[]}}","time":{"$date":1539690429884},"level":"warn"}
rocketchat_1  | Exception while invoking method 'login' Error: Failed to fetch identity from nextcloud at https://cloud.mydomain/ocs/v2.php/cloud/user?format=json. failed [401] {"ocs":{"meta":{"status":"failure","statuscode":997,"message":"Current user is not logged in"},"data":[]}}
rocketchat_1  |     at CustomOAuth.getIdentity (/app/bundle/programs/server/packages/rocketchat_custom-oauth.js:201:21)
rocketchat_1  |     at Object.OAuth.registerService.query [as handleOauthRequest] (/app/bundle/programs/server/packages/rocketchat_custom-oauth.js:213:27)
rocketchat_1  |     at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
rocketchat_1  |     at middleware (packages/oauth.js:194:5)
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

On next cloud I see an open session granted to rocketchat . And I don't understand the problem... My guess the configuration of the custom OAuth provider I created on rocketchat is somehow off.

i got it from another issue about nextcloud integration https://github.com/RocketChat/Rocket.Chat/issues/7791

Ideas ?

**Comment by reetp** [comment]
This looks to be a configuration issue rather than a bug.
Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
Closing for now but please reopen if you find there is an error in Rocket.

**Comment by reetp** [comment]
@rocket-cat close

**Comment by abate** [comment]
I've asked in `#support` but without success.

I've checked and re-checked and I don't see any configuration errors. all endpoints seem correct. I think this problem comes from the function [getCurrentUser](https://github.com/nextcloud/server/blob/35111144d65ec934aaa7ab2196f669887117458d/apps/provisioning_api/lib/Controller/UsersController.php#L219-L241) and is thrown when somehow the user is correctly authenticated ( the session exists in the nextcloud interface, meaning that the authorization went through ), by the user session is lost in the transaction. 

Another piece of information that I didn't mention before is that both nextcloud and rocketchat are behind a traefik proxy. I'm don't think this makes a difference, but worth mentioning .

I'll come back with more information. I've to solve this problem sooner or later ...

**Comment by abate** [comment]
I finally solved this problem. It turned out to be a configuration problem as suggested.

Instead of `Token Sent Via : PayLoad`, specifying `Token Sent Via : Header` the authorization go through. 

Thanks !
