### ISSUE TITLE
Using File System for upload fails when copying clipboard

### ISSUE THREAD

**Issue by stephan1827** [RocketChat/Rocket.Chat#12349]
### Description:

I am using Rocket Chat 0.70.4. When I use GridFS to upload files everything is fine but when I change it to File System paste from the clipboard fails with error 500 in browser. Upload with + still works. I am running on Lubuntu in a VirtualBox that shares a windows drive to store the files. 

### Steps to reproduce:

1. 
Go to any channel and select the text input at the bottom. Hit CTRL-V to paste an image from the Clipboard

![image](https://user-images.githubusercontent.com/2972703/47198846-d64c7b80-d36e-11e8-99b5-c996bdd97c3b.png)

2. 
Click on send

![image](https://user-images.githubusercontent.com/2972703/47198828-bf0d8e00-d36e-11e8-9662-8cd3937608c7.png)

### Expected behavior:

The image schould show up at the top

![image](https://user-images.githubusercontent.com/2972703/47198944-5ecb1c00-d36f-11e8-93cb-6081bb4a05de.png)

### Actual behavior:

Error message in browser

![image](https://user-images.githubusercontent.com/2972703/47198840-ce8cd700-d36e-11e8-89ca-ba624eefe43a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4.
- Operating System: Lubuntu 4.15.0-029
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: V8.11.3
- MongoDB Version: 3.6.8

### Additional context

Problem occurs in Chrom browser and Rocket Chat Windows app. I am using shared folder inside VirtualBox 5.2.20. On the host this folder points to a local directory on the host machine. Uploading files in RocketChat works as expected.

### Relevant logs:
Setting default file store to FileSystem
Oct 17 08:54:58 osboxes rocketchat[877]: Error: FileNotFound: no file with id cRBvFn34KSkCPbDGD found
Oct 17 08:54:58 osboxes rocketchat[877]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:190:25
Oct 17 08:54:58 osboxes rocketchat[877]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1215:18
Oct 17 08:54:58 osboxes rocketchat[877]: at handleCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:120:56)
Oct 17 08:54:58 osboxes rocketchat[877]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1252:5
Oct 17 08:54:58 osboxes rocketchat[877]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
Oct 17 08:54:58 osboxes rocketchat[877]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Oct 17 08:54:58 osboxes rocketchat[877]: at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Oct 17 08:54:58 osboxes rocketchat[877]: ufs: cannot write file "cRBvFn34KSkCPbDGD" (EPROTO: protocol error, open '/media/sf_RocketChatFiles/cRBvFn34KSkCPbDGD. oktober 2018 14:56') { Error: EPROTO: protocol error, open '/media/sf_RocketChatFiles/cRBvFn34KSkCPbDGD. oktober 2018 14:56'
Oct 17 08:54:58 osboxes rocketchat[877]: errno: -71,
Oct 17 08:54:58 osboxes rocketchat[877]: code: 'EPROTO',
Oct 17 08:54:58 osboxes rocketchat[877]: syscall: 'open',
Oct 17 08:54:58 osboxes rocketchat[877]: path: '/media/sf_RocketChatFiles/cRBvFn34KSkCPbDGD. oktober 2018 14:56' }
Oct 17 08:54:58 osboxes rocketchat[877]: Exception while invoking method 'ufsComplete' Error: EPROTO: protocol error, open '/media/sf_RocketChatFiles/cRBvFn34KSkCPbDGD. oktober 2018 14:56'
Oct 17 08:54:58 osboxes rocketchat[877]: ufs: cannot delete temp file "/tmp/ufs/cRBvFn34KSkCPbDGD" (ENOENT: no such file or directory, unlink '/tmp/ufs/cRBvFn34KSkCPbDGD')

**Comment by stephan1827** [comment]
I provided all the information and updated to the latest version 71.1 and the error still exists. I am sure I am missing something in my setup. Any help would be great.

Stephan

**Comment by twi123** [comment]
Replace ":" symbol in file name

Try  this patch:

```diff
diff --git a/packages/rocketchat-ui/client/lib/fileUpload.js b/packages/rocketchat-ui/client/lib/fileUpload.js
index bf9dc1669..7e19b66ee 100644
--- a/packages/rocketchat-ui/client/lib/fileUpload.js
+++ b/packages/rocketchat-ui/client/lib/fileUpload.js
@@ -69,7 +69,7 @@ const getImageUploadPreview = (file, preview) => `\
 </div>
 <div class='upload-preview-title'>
 	<div class="rc-input__wrapper">
-		<input class="rc-input__element" id='file-name' style='display: inherit;' value='${ Handlebars._escape(file.name) }' placeholder='${ t('Upload_file_name') }'>
+		<input class="rc-input__element" id='file-name' style='display: inherit;' value='${ Handlebars._escape(file.name.replace(":","-")) }' placeholder='${ t('Upload_file_name') }'>
 	</div>
 	<div class="rc-input__wrapper">
 		<input class="rc-input__element" id='file-description' style='display: inherit;' value='' placeholder='${ t('Upload_file_description') }'>
```

**Comment by alvarow** [comment]
Hi, I am facing a similar issue, using v1.0.3 with GridFS on Docker/ECS. When I have a single instance running, everything works fine, but if there are multiple Rocket instances, both can see each other and properly broadcasting, the uploads work, but there is no preview, and when the clipboard pasted image is downloaded, the image is corrupted. I see this message on Rocket logs

`Exception while invoking method "ufsComplete" { Error: ENOENT: no such file or directory, open '/tmp/ufs//zkb9t23CKP8zLkcwW' errno: -2, code: 'ENOENT', syscall: 'open', path: '/tmp/ufs/zkb9t23CKP8zLkcwW' }`

I tried mount `/tmp/ufs` and `/app/uploads` via EFS on both Docker instances, and still get the same error. If I stop one of the instances (either one) then things immediately start working.

Maybe this is not related and I should open a new case, but sharing it here.
