### ISSUE TITLE
Market Place cannot be disabled

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#12359]
### Description:

After enabling Apps there is no way to disable it

### Steps to reproduce:

Go to Apps
Read bumpf
Enable Apps
Test App
Decide you don't like or want this App, or any other
Look for disable button.............

### Expected behavior:

Ability to disable apps completely

### Actual behaviour:

Cannot disable Apps

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.x
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1

### Additional context

Potential privacy issues. Once Apps are enabled the page will load anything that is released to the Market place which can potentially track the system whether the server admin likes it or not.

**Comment by reetp** [comment]
Now on 0.72 and I can see that the system is trying to access the market place, but is being blocked by my server.

That causes they system to hang, and I cannot disable the marketplace access.

Any suggestions on how to do that? There must be a database switch somewhere - if it can be enabled we should be able to disable it.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
marketplace.rocket.chat/v1/apps?version=1.3.2:1

**Comment by reetp** [comment]
And in 1.0.2

**Comment by d-gubert** [comment]
Hey @reetp !

You can find the setting to disable the Apps-Engine in **Administration** > **General** > **Apps** > **Enable the App Framework**

**Comment by reetp** [comment]
Yup - got it now thanks
