### ISSUE TITLE
Delay for offline email notifications

### ISSUE THREAD

**Issue by phlegx** [RocketChat/Rocket.Chat#12357]
**Problem**
If I write a message to a wrong channel (e.g. direct message or group channel with mention - because I'm distracted or I'm participating in to many channels or **I simply did not sleep so much last night** :sleeping: ) the offline user gets instantly an email with the message as notification and I don't have the time to delete the message in the channel before.

**Solution**
A solution can be to set a delay in the email configuration. So, offline email notifications are send e.g. 3 minutes later and not instantly. If more messages are send within this time delay, the messages should be grouped to only one email.

**Alternative solution**
An alternative solution can be to set a offline email notification delay per channel.

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close

**Comment by rmeissn** [comment]
Reported in the feature-request repo at https://github.com/RocketChat/feature-requests/issues/29
