### ISSUE TITLE
Clicking the Search button should bring the cursor focus to the Search box

### ISSUE THREAD

**Issue by rayfitzgerald58** [RocketChat/Rocket.Chat#12361]
It would be nice not having to click the search text box after clicking the search button. I can't count how many times I've clicked Search, started typing, only to realize that the text is being entered in the Chat box.

**Comment by wreiske** [comment]
Seems to work for me. What version of Rocket.Chat are you running? I'm on 0.70.4

**Comment by reetp** [comment]
@rocket-cat label add enhancement

I can confirm that this occurs for me in both my own 0.70.4 and the latest at https://open.rocket.chat (usually running develop) in both Chromium and Firefox.

**Comment by rayfitzgerald58** [comment]
Yes, good point @reetp. I also just tested on open.rocket.chat and confirmed that clicking the Search button does not focus the cursor on the Search box.

**Comment by Pwuts** [comment]
Same problem here, really annoying.

**Comment by reetp** [comment]
@rocket-cat close

Closing in favour of 
https://github.com/RocketChat/Rocket.Chat/issues/11482
