### ISSUE TITLE
Acentuação em Português 

### ISSUE THREAD

**Issue by jeffersonmachado** [RocketChat/Rocket.Chat#12366]
### Description:

Acentuação em português do Brasil não esta sendo mostrado corretamente

### Steps to reproduce:

Alterar para português

### Expected behavior:
Mostrar
Você não faz parte de nenhum canal ainda.

### Actual behavior:
Está mostrando
VocÃª nÃ£o faz parte de nenhum canal ainda.

### Server Setup Information:

➔ +-----------------------------------------------------+
➔ |                    SERVER RUNNING                   |
➔ +-----------------------------------------------------+
➔ |                                                     |
➔ |  Rocket.Chat Version: 0.70.4                        |
➔ |       NodeJS Version: 8.12.0 - x64                  |
➔ |             Platform: linux                         |
➔ |         Process Port: 3000                          |
➔ |             Site URL: https://rchat.results.com.br  |
➔ |     ReplicaSet OpLog: Disabled                      |
➔ |          Commit Hash: dbff6ee20f                    |
➔ |        Commit Branch: HEAD

**Comment by sampaiodiego** [comment]
@jeffersonmachado parece ser uma má configuração do teu proxy reverso.

tanto o request do HTML quanto o request do arquivo de tradução devem ser respondidos como `utf-8`, conforme exemplo abaixo:

```bash
$ curl -I https://open.rocket.chat
HTTP/2 200
access-control-allow-origin: *
content-type: text/html; charset=utf-8
date: Mon, 22 Oct 2018 17:15:21 GMT
vary: Accept-Encoding
```

```bash
$ curl -I https://open.rocket.chat/tap-i18n/pt-BR.json
HTTP/2 200
access-control-allow-origin: *
content-type: text/html
date: Mon, 22 Oct 2018 17:15:53 GMT
vary: Accept-Encoding
```

nesse caso não há _header_ de encoding, então o navegador aplica o que ele considera o correto.
