### ISSUE TITLE
Please use .com domains for your cloud product for improved reliability

### ISSUE THREAD

**Issue by sandys** [RocketChat/Rocket.Chat#12367]
Hi,
We are having frequent resolution issues for the .chat domain from the smaller cities in India. This is especially more pronounced on mobile phones.

We have seen these issues happen with other non .com/org/net domains. A post-mortem of a similar issue is here https://hackernoon.com/stop-using-io-domain-names-for-production-traffic-b6aa17eeac20

I understand that the .chat domain may be something you are branding for . I'm only requesting you to have this available for the hosted SaaS product (cloud). This includes both web domain as well all internal API endpoints.

Also, we are concerned that you may be subject to DNS hijacking like it happened to Zoho.com recently. You can only purchase registry lock (NOT registrar lock) for the .com/org/net domains from Safenames or whatever. That is something we would request you to consider as a reliability thing. Only costs about 300$ per year.

**Comment by localguru** [comment]
The .chat TLD is a TLD like any other. If there are problems with the DNS resolution, the first point of contact in my opinion would be the provider used.

**Comment by sandys** [comment]
Thanks for your reply. As I said, this is merely a request - as RocketChat
management, it is your choice entirely.

I do want to mention that in case you don't know, different TLD domain
resolution happens differently. The problems with .io can be traced to the
top level dns servers which are not operated by the same entity that runs
.com/.org/.net .

Rocketchat.com is also owned by you guys, and is a suitable replacement for
your cloud endpoint. You can still use the .chat domain for your brand.

**Comment by reetp** [comment]
This is really an infrastructure issue and not directly related to the server software.

I am sure the devs have noted this. Please follow up with a thread in the forums.

**Comment by reetp** [comment]
@rocket-cat close

**Comment by reetp** [comment]
@rocket-cat close

**Comment by reetp** [comment]
@rocket-cat close
