### ISSUE TITLE
Enable the update of attachments

### ISSUE THREAD

**Issue by Breee** [RocketChat/Rocket.Chat#12379]
**Is your feature request related to a problem? Please describe.**
When writing bots, attachments are attractive for visualization. (e.g. for a poll-bot)
It would be very useful, if one could update attachments using the RestApi (or any other).

**Describe the solution you'd like**
Add "attachments" as argument to the update function like you have it in the postMessage function, such that we can replace an attachment, with a new one.

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
