### ISSUE TITLE
Share performance metrics

### ISSUE THREAD

**Issue by artpolikarpov** [RocketChat/Rocket.Chat#1237]
Hi there! Great work!

Can you share the perf metrics? It is very intersting, how RC handle the load. How many connected clients is OK for a single instance? Is there a limits to scale? What are the bottlenecks and so on...

**Comment by Sing-Li** [comment]
Due to the incredibly diverse environments and ecosystems that RC tends to run on.  We would love to have someone coordinating the collections of such metrics.  Might you be able to help?

**Comment by artpolikarpov** [comment]
I will be happy to help. But how?

**Comment by marceloschmidt** [comment]
This is our current environment:

![image](https://cloud.githubusercontent.com/assets/1986378/12825461/8a8a62aa-cb5d-11e5-8b8b-8558795a094e.png)

We have 40k registered users, and have from 50 to 75 concurrent online users. There are 15k open rooms and an average of 10 users per channel.

If you need more stats, then specify which and we'll reopen this issue.

**Comment by Kurisl** [comment]
Can you share more stats ? According to the above, is the concurrent online users are 
idle or do something like voice call video conferencing ? Can you share more about peformance? thx
