### ISSUE TITLE
Is it possible to integrate the chat in our own mobile app

### ISSUE THREAD

**Issue by prabhakaran8737** [RocketChat/Rocket.Chat#12387]
I have a mobile app and that should have a chat option, which will take time to build and may not be much efficient, is it possible use rocket.chat as a Chat application in our own mobile app

**Comment by reetp** [comment]
This is really a support issue.

Please ask in the forums https://forums.rocket.chat/ or at https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close
