### ISSUE TITLE
Please add more tests about to run Rocket.Chat with using sub directory.

### ISSUE THREAD

**Issue by ura14h** [RocketChat/Rocket.Chat#12385]
The current Rocket.Chat with using sub directory does not work completly.
For example, `ROOT_URL` is `http://localhost:3000/chat`.
Please add more tests about to run Rocket.Chat with using sub directory.

Related issues are #11924, #11922, #10732, #10248 and #8794 ...

**Comment by zimmertr** [comment]
Interesting that others are experiencing this too. We didn't start to notice it until we tried to upgrade an old installation 2.2.0 and couldn't go beyond 0.62.0 without triggering it. So we're sitting there for now. Is a fix in site or is it worth migrating to a subdomain based deployment instead?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
