### ISSUE TITLE
avatar api upload as administrator for a user fails when "edit avatar" is disabled in account settings

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#12388]
### Description:

Administrators can't change the Users Avatar via API, if "Allow Avatar change" is disabled

### Steps to reproduce:

1.  Accounts / Allow User Avatar Change
2.  False
3.  Save
4.  api login for token
5. Use `curl -H "X-Auth-Token: $KEYTOKEN"  -H "X-User-Id: $KEYUSERID" https://servername:443/api/v1/users.setAvatar -H "userId:$changeuserid" -F "image=@filename.jpg"`

### Expected behavior:
Setting the User Avatar via API  api/v1/users.setAvatar  replaces the picture:

{"success":true}

### Actual behavior:
{"success":false,"error":"Change avatar is not allowed [error-not-allowed]","errorType":"error-not-allowed"}

Back to step 2. Setting this to true. You will get a success.

Conclusion: No option to override  "Avatar Upload" as Administrator.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.69.2
- Deployment Method: snap
- Number of Running Instances: 1
### Additional context

Related
#12312

**Comment by reetp** [comment]
@rocket-cat label add "Feature: Request"

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by knrt10** [comment]
On it, fixed it.

**Comment by backnight** [comment]
Hello, I just had the same issue on RocketChat 2.2.0.

Regression?
