### ISSUE TITLE
Deleted users still active when importing from HipChat 

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#12390]
### Description:

If the import file from HipChat includes deleted users, said users are still active after successfully importing into Rocket.Chat.

### Steps to reproduce:

1. Have deleted users in HipChat
2. Create export
3. Import into Rocket.Chat

### Expected behavior:

Deleted users should be inactive/disabled.

### Actual behavior:

Deleted users are active.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

**Comment by Hudell** [comment]
Fixed on version 0.74.3 of Rocket.Chat.
