### ISSUE TITLE
Boolean admin settings can't be reverted unless page reload

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#12399]
### Description:

`true`/`false` settings in the admin UI can't be switched back to their original states (once the "Save" button is clicked) unless the page gets reloaded. I tried with `Accounts_Default_User_Preferences_hideUsernames` and `Store_Last_Message`, so I'm certain it's not only those from the "Accounts" section.

### Steps to reproduce:

1. Go to admin UI → Accounts → Default Preferences
2. Set "Hide usernames" to "true"
3. Click "Save"
4. Set it back to "false"
5. Notice how you can not click "Save" again

### Expected behavior:

Save button should be clickable

### Actual behavior:

Save button not clickable

### Server Setup Information:

- Version of Rocket.Chat Server: Cloud - 0.68.4 (also tested locally with 0.70.4)
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

##### Demo

![untitled mov](https://user-images.githubusercontent.com/944459/47393933-4bc69c00-d721-11e8-9004-abdc92ba7572.gif)

**Comment by wreiske** [comment]
I've also noticed preference changes saving, but when you come back to the same screen the preference didn't save.

**Comment by vynmera** [comment]
For some reason, somewhere between 0.66 and 0.67 something went wrong in the admin settings. The issues I found are:

- Preferences seem to not save their new state locally, and thus will think they are not yet saved when changed back
- Saving only works for one setting at a time - changing 5 settings requires hitting Save 5 times
