### ISSUE TITLE
How to speed up rocket.chat?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1240]
Hi, I have inserted in a iframe rocket.chat Cordova in my app, but the first load of the chat is very slow.
My web server is a VPS with two 2GHz processors, 4Gb RAM with SSD drive. Other websites on the same server (3 wordpress, 2 phpbb3) run fast.

I think that rocket.chat is for the moment slow, because I'm starting it in development mode. In fact my address with port 3000.

Actually i do this.

cd Rocket.Chat/
git reset --hard
git pull
meteor update
meteor

The question:
Is there a way to build the chat on the server, and make it start on port 80, but above all, more faster?

regards
MaX

**Comment by engelgabriel** [comment]
You need actually use the build tool. Just using the `meteor` command is just for development mode, and it is much slower.

Please follow: 
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

Or one of the other Deployment option on our Wiki.

**Comment by tasmar** [comment]
@engelgabriel where are these docs now?  It looks like the documents location have changed a bit since this post.

**Comment by engelgabriel** [comment]
Yes, we moved everything to https://rocket.chat/docs/
