### ISSUE TITLE
Cannot send file with extension *.ico

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat#12401]
### Description:

Can't send files with extension ico. I am trying to send file label.ico, progress show 100% but file don't appear in chat windows. Tested using all web browsers and Rocket.Chat.Electron.
No file type limitation set on server side. Field - Accepted Media Type: empty. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Ubuntu 16.04
- Deployment Method: docker
- Number of Running Instances: 1

**Comment by piotrkochan** [comment]
Try "*" in Accepted Media Type

**Comment by tassoevan** [comment]
Confirmed; server is throwing:

```
Exception while invoking method 'sendFileMessage' Error: Input buffer contains unsupported image format
```
