### ISSUE TITLE
DM panel uses "Full name" or "User name" depending on who started conversation

### ISSUE THREAD

**Issue by igorr-stc** [RocketChat/Rocket.Chat#12413]
### Description:

Name displayed in "Direct Messages" panel depends on who started first conversation. 
If first conversation was started by local user, then full name of remote user is used for chat name, but if first conversation was started by remote user, then only username is used.

### Steps to reproduce:

1. Administration->Layout->Use Real Name is True
2. Remote user (not you) sends you first direct message
3. His or her username is displayed in left pane

### Expected behavior:

His or her real name should be displayed.

### Actual behavior:

His or her username is displayed

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.5
- Operating System: Ubuntu Server 16.04
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 4.0.2

### Relevant logs:

No logs

**Comment by igorr-stc** [comment]
I have tried it on 0.70.4 yesterday, but maybe I have used old DB (after migration). I'll check with clean install.

**Comment by reetp** [comment]
Thank you. You might want to try on 0.71.1 aa well (docker is great for this sort of testing)
You could also test on https://open.rocket.chat

**Comment by igorr-stc** [comment]
@reetp : I have tried 0.71.1 and this problem is gone.
Need to check other things before upgrading in production.
