### ISSUE TITLE
API-Call users.setPreferences doesn't set user language

### ISSUE THREAD

**Issue by beranPro** [RocketChat/Rocket.Chat#12419]
### Description:
Hi, 
i want to change the userlanguage of a user via API-call.
Here is my example call (i added convertAsciiEmoji for testing purposes)::

```
https://${"host"}/api/v1/users.setPreferences/api/v1/users.setPreferences
{"userId": "xxxxxxxxxxxx","data": { "language": "da", "convertAsciiEmoji":true}}`
```

And this is the response:
```
{"user":{"_id":"xxxxxxxxxxxx","settings":{"preferences":{"convertAsciiEmoji":true}}},"success":true}
```
The language in the response is missing, and the language didn't changed.
The setting convertAsciiEmoji was changed by the API-Call

### Steps to reproduce:

See description

### Expected behavior:

The API should change the language

### Actual behavior:

The API doesn't change the language

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 0.70.4
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: true
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.6

**Comment by sdelfi** [comment]
I have a similar problem. This is a very important issue.
I have the  0.71.1 Rochet.Chat versionin docker container from official repo.
