### ISSUE TITLE
How to build RocketChat in docker

### ISSUE THREAD

**Issue by zjzhoujun** [RocketChat/Rocket.Chat#12412]
Thank you very much for the rocketchat project. This project is very useful. But now, I hope to build RocketChat in docker. How do I plan to deploy it?

**Comment by reetp** [comment]
This is a support issue.

Please look at:
https://rocket.chat/docs/
https://forums.rocket.chat
https://open.rocket.chat/channel/support

**Comment by reetp** [comment]
@rocket-cat close
