### ISSUE TITLE
Cannot enable E2E on public channels

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#12417]
This seems to be done on purpose, shown here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-channel-settings/server/methods/saveRoomSettings.js#L76

...why? There's not that large of a difference between a private and public channel.

**Comment by AluminiumTech** [comment]
Yeah, E2E encryption for public channels would be really awesome.

**Comment by tiagoefreitas** [comment]
Public only means its accessible by all users of the server, it has nothing to do with security.
If we want security for all users and all conversations, then E2E should be used for everything by default, like Whatsapp and Signal do.
Encryption should be as much invisible to the users as possible.
