### ISSUE TITLE
New Feature: Message Buttons should have callback option

### ISSUE THREAD

**Issue by tomer953** [RocketChat/Rocket.Chat#12415]
Hey,
We are trying to make some simple flow\decision tree with hubot-adapter+rocketchat,
we want to use the attachment button so the user does not need to type commands, just click buttons.

Simple Example:
We want to give a user link to some file\software,
So we can ask him: "which OS do you use?" and create 2 buttons: "linux" and "windows"
then, when he presses one of them, the attachment will be modified to a new one with the following message:
"what version do you need?" - and will have 2 more buttons: "x86" "64bit"
then, after the user choose, we can send a new message with the matched file.

we did not found a way to implement it via the current API,
because we did not find a way to interact with the bot behind the scenes, when a button is pressed.

hope it's clear enough, I find this as a very important feature to bots developers.
In[ telegram for example](https://core.telegram.org/bots/2-0-intro#callback-buttons), this is one of the most important feature since almost 80% of our bots abilities is done by buttons and callback.

**Comment by reetp** [comment]
This is really a support issue.
Please ask in the forums or #dev or #hubot at https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close
