### ISSUE TITLE
E2E and OTR don't play nicely together

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#12418]
### Description:

Attempting to use OTR and E2E at the same time just renders `******`.

### Steps to reproduce:

1. Enable E2E for a direct message channel
2. Assemble an OTR session
3. Try to send a message
4. Feel disappointment

### Expected behavior:

The message is first encrypted with OTR, then encrypted with E2E (or vice versa).

### Actual behavior:

It seems the E2E engine tries to decrypt the OTR-encrypted message - as in, the message is first encrypted with E2E, then OTR, bur the decryption process tries to use E2E first.

The best way to handle this would be to either 1) synchronize the usage of OTR and E2E (so E2E doesn't try to decrypt an OTR blob), or 2) to simply disable OTR for E2E channels (also understandable).

**Comment by piotrkochan** [comment]
+1 for 2)
