### ISSUE TITLE
[Livechat] Improvement - Deactivation of closing comment

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#12428]
**Is your feature request related to a problem? Please describe.**
When I close a livechat conversation, I always have to insert a closing comment, which frustrates me since we do not use these comments at all.

**Describe the solution you'd like**
As livechat admin I really like to decide wether this comment is optional or not relevant at all. If it is not relevant at all, the comment dialog is not displayed at all. Two solutions
1) make the comment optional
2) do not display it at all

**Additional context**
We implemented the second solution in our branch long time ago: https://github.com/assistify/Rocket.Chat/commit/ab98c8505f8e409f39b28589a8a82886b314b68d

**Comment by renatobecker** [comment]
Hi @janrudolph!

Thanks for your suggestion, it's something we have been thinking about.
We'll probably make the comment optional.

Thanks again.

**Comment by knrt10** [comment]
On it, Will be fixing this.
