### ISSUE TITLE
Not all rc-popover__content \ action items show on first load

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#12434]
### Description:

We just rolled out Rocket.Chat with about 50+ people as a trial to switch from Slack \ Skype \ Email. I am tracking issues we are having on our own internal helpdesk. This issue has come up the most for nearly every single person that has started using Rocket.Chat.

When you first load Rocket.Chat, (and sometimes after a first load this occurs), the action items in a channel or direct message only show "Keyboard Shortcuts" (See Actual behavior below). There are other issues like avatars not loading, settings not showing, emojis disappearing in chat, etc., that seems to be fixed by a simple View \ Reload (Cmd+R on mac).

Simply reloading the client seems to fix the issue, but I have responded to nearly 40 chats in the last 24 hours about not being able to make a video call because they only see "Keyboard Shortcuts."

### Steps to reproduce:

1. Fresh install of Rocket.Chat with a new user registration that has never logged in.
2. Install Rocket.Chat desktop client (might happen on web, too, not sure). 
3. Login
4. Go to direct message or channel and hit the action menu.

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/47578010-48483600-d916-11e8-8cbd-ea1efd9b157d.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/6295044/47579348-b510ff80-d919-11e8-92b4-90b7ce70e4cd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 	0.70.4 dbff6ee20ff756d5654bc36da66de4999ff7cd9c
- Operating System: Centos 7
- Deployment Method: tar zxvf , npm install, service start.
- Number of Running Instances: 1
- NodeJS Version: v8.9.3

**Comment by ggazzo** [comment]
@wreiske sorry about the delay, just for a small test, if you run   `docker run rocketchat/rocket.chat.preview`, let me know if the problem persists.
