### ISSUE TITLE
Links for the same domain (e.g links to uploaded files) are broken

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#12437]
### Description:

Links for uploaded files in any Rocket.Chat room don't refer to the files and trigger a 404 page which can't be dismissed without going back and refreshing the page.

### Steps to reproduce:

1. Open any room;
2. Upload a file;
3. Copy the link address of uploaded file, paste it into message box and send it;
4. Click in the new message's link.

### Expected behavior:

A download dialog or an image preview is shown.

### Actual behavior:

The following page is shown and can't be dismissed:

<img width="595" alt="captura de tela 2018-10-26 as 13 37 05" src="https://user-images.githubusercontent.com/2263066/47580077-48e7c900-d924-11e8-9fe5-9e9b91c25991.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0-develop
- Operating System: MacOS 10.14 (Mojave)
- Deployment Method: source code
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.4

**Comment by iTob191** [comment]
The file upload isn't needed to reproduce this. Every link on the same domain as the chat does the same.

**Comment by bdwarr6** [comment]
It seems to not be replacing spaces with %20, I have had several people encounter this issue, I can also replicate this in user to user messages.

Might be fixable by uri-encoding the links and the copy link

**Comment by fliptrail** [comment]
I am trying to work on this

**Comment by tassoevan** [comment]
Closed by #13756.
