### ISSUE TITLE
Messages not in sync when sending from mobile sometimes

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12435]
### Description:

I didn't find any issue related to this one, that's why I'm opening a new one... basically what happened (and it's hard to reproduce) is that I sent two messages from mobile and on the web, it only showed the last one. After refreshing the browser, it showed all messages. My browser was opened when I sent it via mobile. Screenshots:

**Messages from Mobile (I sent the last two messages)**

![img_7522](https://user-images.githubusercontent.com/551004/47579166-9dd61000-d921-11e8-82f3-6051c7af8274.jpg)

**Messages on the Browser (the first one I sent is missing)**

![screen shot 2018-10-26 at 13 15 45](https://user-images.githubusercontent.com/551004/47579168-9dd61000-d921-11e8-9ef5-cb698da723ff.png)

- Version of Rocket.Chat Server: 0.71
- Operating System: Linux

**Comment by wreiske** [comment]
I just experienced something like this today! I was away from my computer for a few minutes and heard the new message notification from my desktop in the other room. I pulled my phone out to check Rocket.Chat (didn't get a push notification, even though I was AFK for more than the 300-second threshold) and when I opened it up, the new messages didn't show up. Walked over to the desktop and saw the new messages on the screen, but not on the phone.

**Comment by localguru** [comment]
Yes, I can confirm that behavior. I very often see a longer delay until the message appears on the Android app.

**Comment by rafaelks** [comment]
@wreiske @localguru The issue is not related to the issues you guys reported... the issue is saying that one message (later) was synced on the web client but the previous were not. If the message delays to deliver is some client but delivers correctly it's probably not a bug but a networking issue/delay.

**Comment by geekgonecrazy** [comment]
Seems like possibly actually related issues.

The main issue here sounds like the message stream is some how missing delivering a message some times.  

The issue of seeing an alert but not the message makes sense... because actually two separate streams if not mistaken.

So the stream alerting of a notification comes through... but the one carrying the actual message for the channel in focus does not.
