### ISSUE TITLE
Is it possible to use Rocket.Chat without Mongodb

### ISSUE THREAD

**Issue by chhaosh** [RocketChat/Rocket.Chat#12443]
**Describe the solution you'd like**
Currently to use Rocket.Chat, user need to install and configure Mongodb, would it possible to use a different database such as apache Couchdb, mysql, etc or to use Rocket.Chat directly without backend db?

**Comment by localguru** [comment]
I would post this question at https://forums.rocket.chat/

**Comment by reetp** [comment]
This has been asked before. Please search thoroughly before opening an issue (and only opem an issue if you are experiencing errors). NFRs should be opened in the forums.
Thank you.

**Comment by reetp** [comment]
@rocket-cat close
