### ISSUE TITLE
Reset button for settings

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#1244]
I started playing with colors, and made big mess :D. 

We need to have reset button which will restore color settings on default.
##

**Comment by engelgabriel** [comment]
#1449 has been merged and now we have the metadata on the settings object
```
valueSource
packageValue
processEnvValue
meteorSettingsValue
```
We can now implement the generic reset button, so we could have a RESET method by ID or GROUP since we now know what the original value was.

**Comment by shtefcs** [comment]
:+1:

**Comment by xenithorb** [comment]
Anything on this? I just messed up my colors really good and desperately needed this

**Comment by engelgabriel** [comment]
Done
