### ISSUE TITLE
Emoji on hover

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#1245]
When you hover on emoji, it should show you how they are writen.

Thats how you learn much faster how to write emoji.

Like on skype, when you hover with mouse, it will show you meaning/how to write

**Comment by mathdroid** [comment]
Tried to make a solution here [#1250](https://github.com/RocketChat/Rocket.Chat/pull/1250)

**Comment by shtefcs** [comment]
Well played :+1:

**Comment by mathdroid** [comment]
whoops made a mistake. I changed the `messagePopup`, not the `message` itself. Wait a bit.

**Comment by cygery** [comment]
The emojis are handled using [qnub:emojione](https://github.com/qnub/emojione). I've created a [PR](https://github.com/qnub/emojione/pull/2) there to include tooltips using the `title` attribute. When this one is merged it's still necessary to update the version in `.meteor/versions`.

@mathdroid It looks like your solution only affects emojis shown in the preview list, right?

**Comment by mathdroid** [comment]
@cygery yeah, which does not even show when you hover over it. Your solution is clearly the way to go, and I will close my PR. Thanks, learned a lot today! :+1:

**Comment by gmsecrieru** [comment]
Closing as this is not an issue with RocketChat itself. @cygery could you please open a PR to update `qnub:emojione` as soon as your PRs are merged/tagged/released ?

**Comment by cygery** [comment]
Done in #1260.
