### ISSUE TITLE
How test our code update with meteor

### ISSUE THREAD

**Issue by DuckyTheKing** [RocketChat/Rocket.Chat#12459]
### Description:

Good morning erverybody,

When I edit the source code and save the folder, meteor automaticaly restart but my changes are not apply

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0-develop
- Operating System: Ubuntu 18-10
- NodeJS Version: 8.11.3 - x64

Thanks for your help,

Ducky

**Comment by reetp** [comment]
This a support question.

Please raise it in the forums https://forums.rocket.chat/ or chat https://open.rocket.chat/channel/ #support or #dev

**Comment by reetp** [comment]
@rocket-cat close
