### ISSUE TITLE
Test SMTP button

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#1246]
It would be nice if we have test button which will test is SMTP settins correct or not.

Fo example, you can have field where you leave test email to see if you get it or not.

**Comment by subesokun** [comment]
+1 would be very useful for initial setup

**Comment by graywolf336** [comment]
:+1:

**Comment by rasathus** [comment]
+1 I ran into a few problems with an onscreen success message, but no mail being sent.  This would have been very useful.

**Comment by adrianb88** [comment]
hi, regarding smtp: is it working for you guys? my rocket.chat isn't sending any emails at all

**Comment by shtefcs** [comment]
Not working for me. As I said, simple **Test SMTP** button would mean a lot.

**Comment by capensisma** [comment]
@adrianb88 I struggled with this too but it turned out that you need to restart RocketChat ;)

**Comment by shtefcs** [comment]
@adrianb88 but again simple Button would tell you if your information are correct entered and if it's works.

**Comment by ravimallya** [comment]
:+1:

**Comment by shtefcs** [comment]
Finally :)
