### ISSUE TITLE
Livechat offline message with replay-to

### ISSUE THREAD

**Issue by DarkenPL** [RocketChat/Rocket.Chat#12463]
**Is your feature request related to a problem? Please describe.**
When i get offline message i can't just straight answer to it, so I need to copy email address from this message and make totally new conversation.

**Describe the solution you'd like**
It would be better for email to use Replay-To with address of that person.
Sender: messages-noreply@example.com
From: John Doe via LinkedIn <member@example.com>
Reply-To: John Doe <John.Doe@gmail.com>
To: My Name <My.Name@gmail.com>

**Comment by reetp** [comment]
Have you tried this on the latest 0.71.0 (Always test on the latest version available before logging issues as it may have already been fixed)
Have you checked existing bugs ?
I think these may be what you are looking for:
https://github.com/RocketChat/Rocket.Chat/issues/11704
https://github.com/RocketChat/Rocket.Chat/issues/12290

**Comment by reetp** [comment]
If those bugs are not what you are looking for then please raise a new feature request in the forums
Thank you.

**Comment by reetp** [comment]
@rocket-cat close
