### ISSUE TITLE
Multilang livechat

### ISSUE THREAD

**Issue by Bosswell** [RocketChat/Rocket.Chat#12466]
Hello guys! 
It is possible to integrate livechat with multi lang website?
I mean do something like this.

`RocketChat(function() {
    this.setLanguage('en')
;}.` 

I was looking for solution but found nothing.

**Comment by reetp** [comment]
This is a NFR (and probably popular too) and should be opened in the forums thank you.
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close

**Comment by renatobecker** [comment]
Related to #10962.
