### ISSUE TITLE
Implement password's validity period

### ISSUE THREAD

**Issue by pkuser** [RocketChat/Rocket.Chat#12464]
Hi,
it will be possible in new version to set a password's validity period (example: 3 months)???? 
This function is needed to run a password policy.

**Comment by localguru** [comment]
Basically a good idea, but not necessary in case of e.g. SAML authentication. With a local account, the question would be how the user would be informed in advance about the expiration date of his password. This would have to be done several times.

**Comment by reetp** [comment]
@rocket-cat close

New Feature Requests in the forum.
