### ISSUE TITLE
Unable to unset channel moderator through web ui

### ISSUE THREAD

**Issue by Nazgolze** [RocketChat/Rocket.Chat#12479]
### Description:
I'm unable to unset a channel moderator through the web ui

### Preconditions:

- There must be a channel with a channel moderator
- You must refresh your browser before following the steps to reproduce to reliably reproduce this
- You must be logged in with sufficient privileges, preferably admin
 
### Steps to reproduce:

1. Go to a channel with a channel moderator
2. Click the member's list icon
3. Search for the username of the channel moderator (if he's offline, set the dropdown to 'All Users')
4. Click the vertical ellipsis
5. Notice the "Set as moderator" option when the user's already the moderator

### Expected behavior:

I should have an option to unset the moderator

### Actual behavior:

I see "Set as moderator" and if I click it, I get an error

![rocketchat_bug_1](https://user-images.githubusercontent.com/30303/47713474-a9377d00-dc3a-11e8-8071-e48ceba2e64b.png)
![rocketchat_bug_2](https://user-images.githubusercontent.com/30303/47713472-a9377d00-dc3a-11e8-9c8d-030ff92caa33.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Ubuntu 16.04.5 LTS
- Deployment Method: tar
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.4
- MongoDB Version: 3.4.17

**Comment by ggazzo** [comment]
please test it again... any problem let me know
