### ISSUE TITLE
WebDAV integration visible in user preferences even though globally disabled 

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#12476]
### Description:

The new WebDAV integration (#11679 - introduced in 0.70.0) still shows up in the user preferences, even though it's completely disabled in the Admin UI.

### Steps to reproduce:

1. Make sure "Webdav Integration Enabled" is set to "true"
2. Go to your user preferences

### Expected behavior:

WebDAV integration should not be disable, since it's globally disabled.
 
### Actual behavior:

It's visible.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: dockerized
- MongoDB Version: dockerized

### Additional context

<img width="574" alt="screen shot 2018-10-30 at 09 12 12" src="https://user-images.githubusercontent.com/944459/47704436-ea706280-dc23-11e8-89fd-6dffd0ab5afb.png">

**Comment by karakayasemi** [comment]
the fix in here #12569. please test. thanks.
