### ISSUE TITLE
Cannot enter a channel re-created from a previously deleted channel

### ISSUE THREAD

**Issue by markathomas** [RocketChat/Rocket.Chat#12480]
### Description:

A previously deleted channel cannot be entered after it is re-created

### Steps to reproduce:

1. create a channel
2. delete that channel
3. re-create it
4. attempt to enter

### Expected behavior:

channel successfully entered

### Actual behavior:

Error received when trying to enter the recreated channel: "Invalid Room"

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0
- Operating System: Ubuntu 14
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: no
- NodeJS Version: 8.11
- MongoDB Version: 4.0

**Comment by piotrkochan** [comment]
I'm sure this is already reported bug, still not resolved for 2 major releases at lest.

**Comment by dajoker** [comment]
A use at my site ran into this today; any pointers on how to fix it?  Is more/different MongoDB cleanup needed, perhaps, or is this an inherent limitation intended to be in the product, perhaps for data retention purposes?  If so, is that configurable (I have looked but have not found anything yet)?

**Comment by MarcosSpessatto** [comment]
@markathomas any news?

**Comment by MartinSchoeler** [comment]
Closing this due to lack of response, if the issue persists, please reopen this. Thanks!
