### ISSUE TITLE
OSX client no sound if you change the default sound

### ISSUE THREAD

**Issue by itformusic** [RocketChat/Rocket.Chat#12490]
We just upgraded to the 2.14.1 OSX client from 2.13.3 (from app store) and it fixed the main issue of no sound when changing the default notification sound in the user's preferences.  But there's still an issue with selecting notification sounds within an individual chat.

By default the individual notification sounds are empty, with nothing selected.
![screen shot 2018-10-30 at 2 18 44 pm](https://user-images.githubusercontent.com/44621234/47751664-aa26d980-dc4f-11e8-91e0-e9d94326e10b.png)

If you select "Default" it will not play any sound.  You can select any other sound and it will play.  Also, when you select a custom sound in here, it shows a weird name and not the correct name.
![screen shot 2018-10-30 at 2 27 20 pm](https://user-images.githubusercontent.com/44621234/47751776-efe3a200-dc4f-11e8-81df-0e1d8af92b6a.png)

Ubuntu 18.04.1 LTS
Server 0.70.4
OSX App 2.14.1

**Comment by reetp** [comment]
Unless you have evidence otherwise this seems most likely an issue with the App rather than the server.

If so please close and open an issue in the appropriate place:
https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by itformusic** [comment]
Thank you for pointing me in the right direction
