### ISSUE TITLE
Cannot open user details by clicking on the username anymore

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12504]
### Description:

![screen shot 2018-10-31 at 14 38 03](https://user-images.githubusercontent.com/551004/47807346-95fbde80-dd1a-11e8-9f2b-62820227f54f.png)

Tapping on the `aaron.ogle` or my mention does nothing.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0-rc.2
- Operating System: Linux

**Comment by rafaelks** [comment]
This is also happening in `0.72.0-develop`.

**Comment by tassoevan** [comment]
@rafaelks I don't see the problem happening; I tested it on Safari and Chrome. Are some errors logged on console?

**Comment by rafaelks** [comment]
@tassoevan No errors, doesn't work in any browser for me. See the video here (with the mouse clicks).

![2018-11-01 17 14 40](https://user-images.githubusercontent.com/551004/47877067-bea6d580-ddf9-11e8-92cc-2b600398f1b8.gif)

**Comment by FaizanZahid** [comment]
we should have this profile option viewing on android app as well btw.

**Comment by rafaelks** [comment]
Turns out this was being caused because of a setting `Hide Right Sidebar with Click` was `True`. Setting it to `False` resolved it.

**Comment by rafaelks** [comment]
Still, the panel wasn't opened, so it should open in my case. Still a bug.
