### ISSUE TITLE
Collaborate on Email Tickets in RocketChat

### ISSUE THREAD

**Issue by tezukzai** [RocketChat/Rocket.Chat#12500]
**Is your feature request related to a problem? Please describe.**
Currently, our whole team is using RC, including dealing with customers through Livechat. We currently use G Suite to deal with group inbox/support style ticketing. We are considering new alternatives, but it doesn't make sense for us to get a whole new platform just for dealing with support tickets when our team are so used to dealing with RC.

**Describe the solution you'd like**
I'd like to be able to receive and send emails within RC with features similar to other helpdesks. This could be done as an APP, but IMO there is a lot of overlap with LiveChat and it would be nice to create tickets directly from chats too.

**Describe alternatives you've considered**
Some open source helpdesk software such as:

- https://zammad.org

- https://helpy.io/

There are a number of similar integrations for Slack

**Additional context**

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
