### ISSUE TITLE
How to access custom RocketChat model added at server models in Client?

### ISSUE THREAD

**Issue by harwee** [RocketChat/Rocket.Chat#12505]
I have created a custom location model and registered it on server and can access it at `RocketChat.models.Locations` on server. 

When I try to access the method of the same model on client I get the method as undefined. 
Then after trying `console.log('RocketChat.models')` I observed that `RocketChat.models.Locations` is just an empty `Object` basically `RocketChat.models.Locations = {}`

All other models are accessible and are LocalCollections or Collections except the model I defined. 

Did I miss something while defining the new model?

**Comment by reetp** [comment]
I think this is a support issue rather than a bug with rocketchat server itself.

Please open an issue in the forums https://forums.rocket.chat/ or ask in https://open.rocket.chat/channel/support

If you feel it is a bug with the server please reopen with relevant logs.

**Comment by reetp** [comment]
@rocket-cat close
