### ISSUE TITLE
HTTP title & description for Rocket.Chat group url

### ISSUE THREAD

**Issue by sunnipaul** [RocketChat/Rocket.Chat#1251]
I wonder if Rocket.Chat could serve HTTP title & descriptions for group url so that when posting the group url in a room, the group description will be rendered.
![image](https://cloud.githubusercontent.com/assets/5299443/10732904/44be1a3e-7c37-11e5-8477-d4f6c5c76de7.png)

**Comment by gmsecrieru** [comment]
This is not supported at this point as it depends (at least) on two requested features/improvements:

- Anonymous access to rooms (see #604)
- Server-side rendering
