### ISSUE TITLE
The placeholder of the search channels input field is not available in the translation file

### ISSUE THREAD

**Issue by sawo** [RocketChat/Rocket.Chat#12517]
### Description:

I would like to replace the placeholder text within the search input field on the Directory page, where you can search for channels. The default placeholder text is: "Search Channels". I was trying to locate this string in the translation files, but cant find it. Maybe it is hardcoded?
### Steps to reproduce:

1. Open this file: [https://github.com/RocketChat/Rocket.Chat/blob/ebf8dd9e8d64b1d879615c1035745fa65f8b23cf/packages/rocketchat-i18n/i18n/en.i18n.json](url)
2. Search for text _Search Channels_
3. You won't find it

### Expected behavior:

I would like to find that text in t translation file, i would like to change it, and see that the placeholder within the search field has changed.

### Actual behavior:

The text of the placeholder of the search input field may be hardcoded on the Directory page:
![image](https://user-images.githubusercontent.com/3706407/47853318-a9707d80-ddde-11e8-8b72-6e021b43b2df.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by engelgabriel** [comment]
@ggazzo has this been fixed on the new directory after refactoring?

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/en.i18n.json#L3044
