### ISSUE TITLE
Problem sending photos from Rocketchat mobile.

### ISSUE THREAD

**Issue by erkankyn1** [RocketChat/Rocket.Chat#12515]
### Description:
I cannot send a photo to rocketchat and send it to my server when I click the "send photo" button. The photos I took from my phone do not send the names starting with IMG_. I'm trying to change his name and send it, but I can't upload it to my server again.
I try Wifi and Mobile data but doesn't work.

### Expected behavior:
Rocketchat to take pictures and send.

### Actual behavior:
In the application after taking the photo to the server while uploading photos on the upload screen is canceled and when I take pictures from the camera and upload from gallery to the server again I get the same error.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: IOS
- Deployment Method: Snap

**Comment by Shaverdoff** [comment]
try to view that article 
https://github.com/RocketChat/Rocket.Chat.iOS/issues/2264
and see nginx configuration

**Comment by reetp** [comment]
@rocket-cat close
