### ISSUE TITLE
[BUG] SAML login mask is broken after "Refresh OAuth Services"

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12511]
### Description:

Executing of `Refresh OAuth Services` under `Administration/OAuth`, will break the `SAML` login mask. After a restart of Rocket.Chat the SAML login is offered again. Other login types such as _github_ or _local login_ are not affected.

In case of an exclusive SAML login, you have completely locked yourself out!

### Steps to reproduce:

1. go to `Administration/OAuth`
2. Click on`Refresh OAuth Services`
3. log out from RC
4. SAML login is missing (no cache or refresh or browser/android client problem)
5. Restart Rocket.Chat
6. SAML login is offered again

### Expected behavior:

The execution of `Refresh OAuth Services` must not break SAML login.

### Actual behavior:

`Refresh OAuth Services` breaks SAML login until restart.

**Login mask with SAML login:**

![rc_anmeldung_mit_saml](https://user-images.githubusercontent.com/8544984/47825097-5a8bff00-dd70-11e8-8971-36cf6d3701ef.png)

**Refresh OAuth Services**

![refresh](https://user-images.githubusercontent.com/8544984/47825016-04b75700-dd70-11e8-9ff9-ead202a3cea1.png)

**Login mask after execution of "Refresh OAuth Services"**

![ohne_saml_bug](https://user-images.githubusercontent.com/8544984/47825024-1436a000-dd70-11e8-9763-1cf19df90776.png)

**Login mask with "SAML only" after execution of "Refresh OAuth Services"**

In case of an exclusive SAML login, you have completely locked yourself out!

![saml_only](https://user-images.githubusercontent.com/8544984/47847388-5c36e080-ddcb-11e8-92d4-5ebcd387fdcb.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2, 0.72.0-develop, 2.2.0
- Operating System: Ubuntu 16.04 LTS
- Deployment Method: tar (self build bundle)
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3, 8.15.1
- MongoDB Version: 3.4.17, 3.6.15

### Relevant logs:

No errors on Log Level 2 (Debug).

**Comment by reetp** [comment]
Can you please test on latest 0.71.1 ?
Things move fast here and this may be fixed already.
Thank you.

**Comment by reetp** [comment]
I presume this is still an issue in 0.74.x ?
I have nothing to test it with

**Comment by localguru** [comment]
Still does not work in version 2.2.0!
