### ISSUE TITLE
API returns 400 without any details

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#12512]
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-livechat/server/api/v1/visitor.js#L42

Found a null error being returned from a `livechat/visitor` API usage.

Without docs (and almost no code comments 😡) for the Livechat API, returning accurate error message is the only way to have a clue what's going on. Wasted a lot of time investigating this one.

Looking through the codebase, there's lots of `API.v1.failure()` returns. These should all have at least a basic message, if not an error instance.

**Comment by alirezamirsepassi** [comment]
Same problem here. Lots of end points return http 400 error without any message!! Just `success: false`.

**Comment by alirezamirsepassi** [comment]
Maybe this is the solution:
https://rocket.chat/docs/administrator-guides/integrations/zapier/


> Warning: Make sure the rocket.cat user has not been removed from your Rocket.Chat instance otherwise you won’t be able to enable the Zaps! If it has been removed, you’ll probably see an error message that says something like (400) Bad Request and said "Invalid user [error-invalid-user].

**Comment by alirezamirsepassi** [comment]
Any updates?
