### ISSUE TITLE
Horizontal buttons not work, they are always vertical

### ISSUE THREAD

**Issue by ivanmpk** [RocketChat/Rocket.Chat#12516]
### Description:

I try generate post message with horizontal buttons but always are vertical.

### Steps to reproduce:
This is my test:

curl -H "X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
     -H "X-User-Id: xxxxxxxxxxxxxxxxxxx" \
     -H "Content-type:application/json" \
     http://192.168.x.x:3000/api/v1/chat.postMessage \
     -d '{ "channel": "#general", "attachments": [{ 
         "title": "horizontal text buttons with url",
      "button_alignment": "horizontal",
      "actions": [
        {
          "type": "button",
          "text": "Book flights",
          "url": "http://www.kayak.com",
          "is_webview": false
        },
        {
          "type": "button",
          "text": "Cancel travel request",
          "url": "https://requests.example.com/cancel/r123456",
          "is_webview": false
        }
      ]
}]}'

### Expected behavior:

Post with horizontal buttons 

### Actual behavior:

Post with vertical buttons

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Centos7
- Deployment Method: tar
- NodeJS Version: v8.12.0

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
