### ISSUE TITLE
Mobily notification tuning

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#12514]
Than chating in desktop or web in DM and account also login in mobile whole of conversation also pushed to mobile client whatever setting - mute focused conversation or not. it realy annoying. 

in settings - General / Notification is options if true whole push fly to mobile whatever to sent in account notifications.
"Choose to always notify mobile device regardless of presence status." but no any status a monitoring... 

like's solution
Send push on mobile than you do not in focuce on DM conversation after some seconds... like implemented in slack.

**Comment by reetp** [comment]
Please fill in a proper bug template with your server details:

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Have you tested this on the latest version 0.71.x ?

**Comment by Shaverdoff** [comment]
in 0.70.3 version moute focused conversation work how exptected. no push on mobile then direct chating after update to 0.71 push on direct always work

**Comment by Exordian** [comment]
we would be interested in such a feature as well. it's quite important since the desktop client has no 'idle' detection. if you leave your notebook locked, you still won't receive any mobile push notifications currently (2.2.0)

**Comment by sampaiodiego** [comment]
closed by the changes on notifications logic introduced by https://github.com/RocketChat/Rocket.Chat/pull/17357/
