### ISSUE TITLE
Bug - After converting default channel to a private group can no longer add users

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1252]
It occurred to me that we've been using an open channel for discussions which would better be served from a private invite only group on our rocket.chat instance. It would be a shame to lose the history of the channel so I was wondering if there was a way to convert a channel to a private group?

**Comment by phillip-white-sociomantic** [comment]
+1

**Comment by tanc** [comment]
I've updated to the latest development release and noticed that there is now a facility to do this. On the right of a channel or private group there is a 'Channel_settings' option (gear/cog icon). This reveals the 'Room settings' where you can switch between Channel or Private Group which fulfils this feature request nicely.

**Comment by tanc** [comment]
I'm going to reopen this as there is an issue with the general channel (default channel) when you convert it to a private group. You can't add users to the general channel and this persists when you convert it to a private group. So when someone wants to join or accidentally leaves you have a problem. Any chance of a fix for this? We don't want to create a new private group as we'll lost all our history on the channel.

**Comment by tanc** [comment]
Changed the name of this issue and hoping someone can take a look

**Comment by Sing-Li** [comment]
@tan  PR #1790  should fix this.   Happy New Year !

**Comment by tanc** [comment]
Fantastic! Thanks @Sing-Li and Happy New Year to you too! Will test this on Monday and report back

**Comment by tanc** [comment]
@Sing-Li, I've just applied the code change and rebuilt but I'm not seeing any difference. It looks like I can't add users to that group still.

I'm a user with administrator role. I'm not sure I understand private groups fully, is the user who creates the group the only one able to add users to it? I wonder whether there should be a permission (if there isn't one already) that allows users to add other users to private groups. I would expect as an admin to be able to add users to any private group but I'm not sure if thats the way private groups are intended to work.

**Comment by Sing-Li** [comment]
@tanc The PR has not been merged.  Did you manually applied the code change?

**Comment by tanc** [comment]
Yes I did. Can you explain the expected behavior so I can test?

**Comment by Sing-Li** [comment]
@tanc The problem with the GENERAL channel is that it is created by the system at initialization and currently *NOT* associated with a user.

Our code that changes a public channel to private group did not add a user.   As a result, changing GENERAL to private group will not allow addition of new members ... because there is no owner for the group.

The patch adds an owner, the currently active admin, when changing a public channel to a private group. You should see the entry field for more users when you click the third button on the right hand side Tab bar (the member list) as the admin user who made the change.

If you don't, please double check spaces vs tab in your modifications of the CoffeeScript code.

**Comment by tanc** [comment]
Hi @Sing-Li, thanks for the info. To be doubly sure I've grabbed a fresh develop branch and overwritten the CoffeeScript file with: https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/packages/rocketchat-channel-settings/server/functions/saveRoomType.coffee

When I test changing the default channel to a private group I still can't add users and I don't see the expected add users field. Any idea what I might be missing? I'm testing this on an existing database that has had the channel changed from channel to private group and back a few times.

![rocket_chat](https://cloud.githubusercontent.com/assets/76320/12086522/f763250a-b2c2-11e5-8af6-c7e0cd1d09e0.jpg)

**Comment by geekgonecrazy** [comment]
@tanc does this still happen?  We've made a good number of permission changes, so this should be resolved.  Please let me know if it hasn't been
