### ISSUE TITLE
Link preview contains HTML code

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12528]
### Description:

The link preview shows HTML code, e.g. `We think it&#39;s a good idea` instead of `We think it's a good idea`.

[There may already be a ticket for this problem. But after a search I couldn't find it.]

### Steps to reproduce:

1. post URL https://github.com/RocketChat/docs/pull/974

![grafik](https://user-images.githubusercontent.com/8544984/47948294-e8154d80-df2e-11e8-8823-9ff6c65ad7e3.png)

### Expected behavior:

Correct rendering

### Actual behavior:

see above screen shot.

### Server Setup Information:

Version of Rocket.Chat Server: 
 - 0.72.0-develop (open.rocket.chat)
 - 2.2.0
 - 2.3.0-develop, (open.rocket.chat)

**Comment by fliptrail** [comment]
I am working on it.

**Comment by localguru** [comment]
Sill does not work in 2.2.0!

![grafik](https://user-images.githubusercontent.com/8544984/68840672-7a643b80-06c3-11ea-8e81-2b960ae428ac.png)
