### ISSUE TITLE
[REQUEST] the ability to configure what User Preferences options are visible to users

### ISSUE THREAD

**Issue by jaytat0** [RocketChat/Rocket.Chat#12520]
It would be good if an admin could configure via the Admin console what sections of the current User Preferences are visible to users. Perhaps this can go in Admin/Layout.

For example, in the below screenshot the admin could configure which of LOCALIZATION/GLOBAL/USER PRESENCE (and etc below that) sections are available in the user gui.

![image](https://user-images.githubusercontent.com/8495373/47866068-306c2880-ddd4-11e8-996f-a27f3b3ef76f.png)

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close
