### ISSUE TITLE
Crying emoji using quote character, i.e., :'(, is not parsed/rendered as image

### ISSUE THREAD

**Issue by cygery** [RocketChat/Rocket.Chat#1253]
The `:cry:` emoji is correctly parsed in messages. However, when writing `:'(` (or other emojis using a single quote) they are not detected correctly and, instead, displayed in their plaintext form although the corresponding images are shown in the emoji preview popup when writing a message.

**Comment by cygery** [comment]
I've found the root of this issue: the single quote is replaced with the `&#39;` entity which is not matched by emojione's regular expression for ASCII emojis. I'll look if I can submit a patch there.

On the other hand, is it necessary that quotes are escaped at all?

**Comment by cygery** [comment]
I've added a [commit](https://github.com/cygery/emojione/commit/01098c31e9ff977bec8f4a7b3c074cee9d381611) to my [PR](https://github.com/qnub/emojione/pull/2) for the emojione package which addresses this issue.

**Comment by gmsecrieru** [comment]
Closing as this is not a RocketChat-specific issue.
