### ISSUE TITLE
Update won't update

### ISSUE THREAD

**Issue by emergingdzns** [RocketChat/Rocket.Chat#12533]
### Description:

When opening Rocketchat desktop app, I get notified that there's a new update available. I'm on 2.13.3. It tells me that 2.14.1 is available. 
### Steps to reproduce:

1. Launch app.
2. Click Install on the notification. I then tells me I'll be notified when it's ready to install.
3. Wait for notification and click Install now when it comes up.
4. App shuts down. Never comes back up.
5. Re launch the app. Get the notification of update available.

### Expected behavior:

It should update.

### Actual behavior:

Not actually updating

### Server Setup Information:

Irrelevant. We are using your cloud.

### Additional context

Desktop environment is Mac Mojave.

**Comment by localguru** [comment]
I would open a ticket here: https://github.com/RocketChat/Rocket.Chat.Electron/issues

**Comment by tassoevan** [comment]
It's an already solved and known issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/955.
The workaround to 2.13.3 is click "Install later" and manually quit the app.
