### ISSUE TITLE
E2E pinned/favorited messages do not get displayed correctly on the chat list and on the pinned/favorited list

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12549]
### Description:

You can't see the information on the Pinned/Favorited List and the system message is also not being displayed correctly.

![screen shot 2018-11-06 at 20 41 34](https://user-images.githubusercontent.com/551004/48098647-8857c480-e204-11e8-8323-152ab131abe6.png)

![screen shot 2018-11-06 at 20 44 03](https://user-images.githubusercontent.com/551004/48098764-c654e880-e204-11e8-8f52-44315782478a.png)

![screen shot 2018-11-06 at 20 43 21](https://user-images.githubusercontent.com/551004/48098685-9ad1fe00-e204-11e8-811c-6ab365483c7f.png)

**Comment by rgembalik** [comment]
I've seen this happen on our instance as well. From what I can tell, the list of pinned messages is loaded with a limit of 50 messages, but without ordering on the API side (looks like UI is doing the sorting). So I have to scroll down the list, to force the second page to be loaded and scroll back up and only then the newly pinned message is visible.

**Comment by milton-rucks** [comment]
Fixed
