### ISSUE TITLE
Slackbridge on cloud hosting

### ISSUE THREAD

**Issue by bochen87** [RocketChat/Rocket.Chat#12544]
Hello,

I cannot activate the slackbridge on our cloud hosting instance. I activate it and it is automatically deactivated once i got back into the settings. followed the instructions on how to set it up. it all works, except the activation of it.

**Comment by bochen87** [comment]
It now stores the settings, however the integration does not seem to work.

**Comment by Hudell** [comment]
Hey @bochen87 , can you send an email to cloud.support@rocket.chat explaining the problem you're having? Our support team will be able to help you that way.

I'll be closing the issue here.
