### ISSUE TITLE
Youtube broadcasting

### ISSUE THREAD

**Issue by aziz75012** [RocketChat/Rocket.Chat#12559]
### Description:
Hello,
I'm trying to activate the livestream features as shown here https://rocket.chat/docs/administrator-guides/youtube-broadcasting/

Livestream source (URL) is ok
Does Youtube Broadcasting work for someone?
Thank you for any help !

### Actual behavior:

![screen1](https://user-images.githubusercontent.com/38562075/48151237-0b3e5500-e2c1-11e8-838d-ee791e94f79f.png)

![screen2](https://user-images.githubusercontent.com/38562075/48151436-91f33200-e2c1-11e8-99eb-70192adfaaa5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Debian 9
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6

### Relevant logs:
Log error on the server console:

 ? [34mI20181107-18: 14: 08.033 (1) Exception while invoking method 'saveRoomSettings' Error: Match error: Unknown key in field id at check (/opt/Rocket.Chat/programs/server/packages/check.js:68 : 17) at EventEmitter.RocketChat.saveStreamingOptions (/opt/Rocket.Chat/programs/server/packages/rocketchat_livestream.js:62:3) at Object.keys.forEach.setting (/opt/Rocket.Chat/programs/server /packages/rocketchat_channel-settings.js:467:22) at Array.forEach (<anonymous>: null: null) at MethodInvocation.saveRoomSettings (/opt/Rocket.Chat/programs/server/packages/rocketchat_channel-settings.js: 412: 27) at MethodInvocation.methodsMap. (Anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2518:36) at MethodInvocation.methodMap. (Anonymous function) (packages / rocketchat_monitoring.js : 2731: 30) at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12) at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/prog rams / server / packages / ddp-server.js: 902: 126) at Meteor.EnvironmentVariable.EVp.withValue (packages / meteor.js: 1186: 12) at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs /server/packages/ddp-server.js:902:98) at Meteor.EnvironmentVariable.EVp.withValue (packages / meteor.js: 1186: 12) at Promise (/opt/Rocket.Chat/programs/server/packages/ ddp-server.js: 902: 46) at new Promise (<anonymous>: null: null) at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85
? [34mI20181107-18: 14: 08.034 (1) Sanitized and reported to the client: Match failed [400]
? [34mI20181107-18: 14: 08.034 (1) undefined undefined

**Comment by reetp** [comment]
I'm not sure as the documentation is not clear. Be good if one of the devs took a look at the documentation and explained it a bit more as there have been a number of similar questions.

**Comment by reetp** [comment]
Someone is taking a look at this issue.
Going to close as a duplicate in favour of #12201

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
@rocket-cat close
