### ISSUE TITLE
Lost params on DM,PV,CH after change Notifications

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#12553]
### Description:

Lost context "3 vertical dot" menu with parameters of DM or any PV CH after change notification in RocketChat Windows App Client, RocketChat Web App Client on any browser.

### Steps to reproduce:

1. Go to "My Account", slide to NOTIFICATIONS
2. Change any of tree field, press Save button
3. After reloading press at "3 vertical dot" 

### Expected behavior:

Expected whole of menu items

![default](https://user-images.githubusercontent.com/43804710/48133499-6287f980-e2b0-11e8-8d41-ae48f246f335.png)

### Actual behavior:

See only Keyboard Shorcuts and sometimes Files Lists.

![default](https://user-images.githubusercontent.com/43804710/48133484-5439dd80-e2b0-11e8-8b5d-bbc2038e39ad.png)

After forcibly refresh page on browser or tap on menu view/reload page on Windows App Client - whole menu items comeback.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71
- Operating System: Windows 7 64bit
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: off
- NodeJS Version: v8.9.3 and v8.11.3 the same situation
- MongoDB Version: v3.6.8

**Comment by gabriellsh** [comment]
Doesn't happen anymore. If you still face this issue please reopen.
