### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by nicholasthompson93** [RocketChat/Rocket.Chat#12562]
I'm using your app on my MBP, I'm working in a chat room with Convergent Trading.  I set all my notifications for each room and they don't work regularly.  Sometimes they work, sometimes they don't.  Is there any way to get this fixed.  I tried contact you help disk, opened a ticket and got no response.  2 times.   PLEASE HELP.

**Comment by johnbrown-yoti** [comment]
I'm seeing similar issues after updating to 0.70.4. I've set audio and desktop notifications manually but I still get no alert on my desktop and no audio played.

Checking the logs across the RocketChat doesn't show any errors.

**Comment by reetp** [comment]
@nicholasthompson93 

For paid support with a normal installation please contact support@rocket.chat 
For paid support with a cloud installation please contact cloud.support@rocket.chat

Please allow a few days for ticketing and triage, particularly if you haven't got any support already in place.

You can find out about pricing and response times here:

https://rocket.chat/pricing

For community support go to https://forums.rocket.chat or chat at https://open.rocket.chat but note this is community supported and there are no guarantees of anything.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Not really enough details about setup to go off of.
