### ISSUE TITLE
Deploy Rocket.Chat without docker - no domain name

### ISSUE THREAD

**Issue by TinajaLabs** [RocketChat/Rocket.Chat#1256]
Ran through the steps on this page: https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

Installed on Ubuntu 14.04 on digital ocean.

Accessing myip:3000 address does not work.  

I note that I was asked to enter domain name during the install process.  But I used the simple ```rocketchat``` instead.

Should I use the ip address of my droplet for all steps requiring a domain name host name.  What should the etc/hostname file be configured as?

Thanks for any tips,
Chris.

**Comment by Sing-Li** [comment]
@TinajaLabs    Please make sure you're using (Internal or Internet) DNS to bind your hostname.  It is important to use the *exact* hostname that your users will be using to access your chat server.

Set that name to the ROOT_URL.   There can be a variety of installation problems if ROOT_URL is not set correctly.

**Comment by TinajaLabs** [comment]
At this point there is no "fqdn" only an IP address.  Do I have to go buy a domain name to make this work or can I just use my designated (from the droplet) IP address?

Should ```/etc/hosts``` look like this if my IP was ```99.99.99.99```?
```
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data

127.0.1.1 99.99.99.99 
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

Should the env variable be: ```HOST=99.99.99.99```
```
MONGO_URL=mongodb://localhost:27017/rocketchat
MONGO_OPLOG_URL=mongodb://localhost:27017/local
ROOT_URL=http://$HOST
```

And lastly do I need to rebuild with the new host as an IP address?

Thanks,
Chris.

**Comment by Sing-Li** [comment]
IP address should work - realize that *ALL* of your users will need to type in the same IP address for their URL to server

Remove the first line from your hostfile

````
127.0.1.1 99.99.99.99 
````

The HOST env variable should be okay


ALL your users should be using:

````
http://99.99.99.99:3000/   
````

to access server

Unless you had build errors - you should not need to rebuild.

PS... the instruction you are following is outdated, but hopefully still works - it should be updated soon

**Comment by marceloschmidt** [comment]
Was this resolved?

**Comment by vitaliy-kuzmich** [comment]
I have opposite proble, I run it firstly at externnal_ip:3000 but now I changed it to 127.0.0.1:3000 also tried with localhost:3000, but site still available via external IP. what I did wrong?
my run bash script : 
export ROOT_URL=http://localhost:3000/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3000
cd Rocket.Chat/


nohup node main.js >/var/log/rocket.log 2>&1 &



netstat:
root@Ubuntu-1404-trusty-64-minimal ~ # fuser -n tcp -k 3000
root@Ubuntu-1404-trusty-64-minimal ~ # netstat -ntlp | grep LISTEN
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      6624/node       
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      6031/master     
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      794/mongod      
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      896/mysqld      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1163/sshd       
tcp6       0      0 :::25                   :::*                    LISTEN      6031/master     
tcp6       0      0 :::22                   :::*                    LISTEN      1163/sshd       
root@Ubuntu-1404-trusty-64-minimal ~ # nano launch-rocket.sh 
root@Ubuntu-1404-trusty-64-minimal ~ # bash launch-rocket.sh 
root@Ubuntu-1404-trusty-64-minimal ~ # netstat -ntlp | grep LISTEN
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      7823/node       
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      6624/node       
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      6031/master     
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      794/mongod      
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      896/mysqld      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1163/sshd       
tcp6       0      0 :::25                   :::*                    LISTEN      6031/master     
tcp6       0      0 :::22                   :::*                    LISTEN      1163/sshd

**Comment by vitaliy-kuzmich** [comment]
I just found that it is possible to change IP address by meteor itself, just export BIND_IP=127.0.0.1 and it ill run..
