### ISSUE TITLE
Rendering issue when mixing inline code with block quotes

### ISSUE THREAD

**Issue by BOOtak** [RocketChat/Rocket.Chat#12576]
### Description:

When typing a message with blockquote followed by an inline code block, some random string appears in the final message instead of my inline code block (see screenshot below). I've tested that on the web client and desktop Electron app on Windows 10, Windows 7 and Ubuntu 18.04.

### Steps to reproduce:

1. Open any chat in Rocket.chat and try to send a message consisting of blockquote followed by a single-line code block, something like this:
```
> quote
`code`
```
2. Send this message

### Expected behavior:

This should render my blockquote and inline code correctly, something like this:
> quote
`code`

### Actual behavior:

What happens instead is that instead of a line of code, some random string appears in the message. 
![image](https://user-images.githubusercontent.com/2512758/48252915-01c70100-e417-11e8-8f29-4f7b89d9181d.png)

### Server Setup Information:

This is a client issue

**Comment by reetp** [comment]
Can you please help the developers by filling out a proper bug report? They can't really help without this information.
Also please test on https://openrocket.chat
Use this link: https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by BOOtak** [comment]
@reetp sorry, I've left some fields blank in bug report template as they were insignificant in my opinion. What additional info do you need?
Unfortunately, https://openrocket.chat is not reachable for me.

**Comment by BOOtak** [comment]
@reetp I've updated my first message and added some details about expected and actual behavior. Hope this helps!

**Comment by BOOtak** [comment]
Yes, I can confirm the same bug on https://open.rocket.chat

![screenshot_20181110_154541](https://user-images.githubusercontent.com/2512758/48301464-b0df0780-e4ff-11e8-92ca-a4f831c6e46d.png)

**Comment by reffu42** [comment]
I can confirm that the issue also occurs when putting two multi-line codeblocks separated by only a newline (screenshots from open.rocket.chat)
![image](https://user-images.githubusercontent.com/1823982/49528741-97bd4280-f882-11e8-88f9-21ec53f1897b.png)
![image](https://user-images.githubusercontent.com/1823982/49528762-a4419b00-f882-11e8-9ca7-8b9310b7d748.png)

**Comment by BOOtak** [comment]
This issue seems to be fixed now
![изображение](https://user-images.githubusercontent.com/2512758/60351781-26381380-99cf-11e9-8c3a-b3c779fa74b9.png)
