### ISSUE TITLE
Cannot send message in mobile version on android

### ISSUE THREAD

**Issue by pombaer** [RocketChat/Rocket.Chat#12577]
### Description:

I am using Android 5.0.1 Chrome 46 (not latest version, but upgrade fails) and RocketChat 0.71.1. I have not installed the Rocketchat App. 
When i write a message pressing "Enter" creates a new Line instead of sending the message. Keyboard Settings is "Swype - Huawei Swype". I tried other installed Keyboards, same behavior, also tried to change the Enter Key Behavior in my Profile but nothing worked.

### Steps to reproduce:

Open Rocketchat in Chrome Browser in Android

### Expected behavior:

Enter sends Message. In the Desktop Mode when i enter a Character in the message field a "Send Button" (Aeroplane symbol) is shown at the right side, why is this Button not shown by default in the mobile Version?

### Actual behavior:

Enter creates new line, no chance to send message.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Ubutu Bionic
- Deployment Method: docker image
- Number of Running Instances: 1
- DB Replicaset Oplog: ??
- NodeJS Version: the version installed in the docker image
- MongoDB Version: ??

### Additional context

Please display the send button or create a "Enter key behavior" entry which an option to always display the button.

### Relevant logs:
No logs

**Comment by reetp** [comment]
You may want to try and fix your app issue first so you can test on the latest.

**Comment by reetp** [comment]
I mean fix this: "not latest version, but upgrade fails"

Regrettably no one has piles of phones to test with so it is hard to test on your specific model.

This is an admin setting globally plus can be configured as a per user setting in the user profile (if you had a good look through the server settings or read the documentation you would know that)

Closing notabug

**Comment by reetp** [comment]
@rocket-cat close

**Comment by pombaer** [comment]
I cannot reopen my issue since it is closed by a repo collaborator. The problem is not specific to my exact browser version or android, when i report problems in other projects developers want exact infos to versions, os, ..., so i exactly described my system.
The problem seams to be the display resolution. I am using a resolution "720x1280", in "portrait" the send button is not displayed, in "landscape" the button is displayed. Using a smartphone with HD resolution "1080x1920" the button is displayed in both situations, so please reopen the issue for correcting this behavior.
