### ISSUE TITLE
Room meta no longer in message stream

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#12574]
Working on current #develop branch (because I need other fixes included there), the `__my_messages__` stream no longer includes the room meta object (the second argument emitted in the stream).

It's created here, on the access check when the room object is fetched.

https://github.com/RocketChat/Rocket.Chat/blob/7df98181051061163e2ab4439b56659e841a0c72/server/stream/messages.js#L35-L37

~I have a fix to get the room object in the original publish method instead. I will submit that now, but~ this is a pretty critical change and I'd like to understand it and know how it can happen.

**Comment by timkinnane** [comment]
I ran the stable version SDK tests (with Asteroid) to ensure it's not an issue with the DDP replacement work in progress. but the stable version is missing the meta too.
Logging the data in the stream event before it's handled confirmed the meta argument is just an empty object. Pretty sure this change (whenever it happened) will break many bots if it goes out in a release.

**Comment by timkinnane** [comment]
No @Cyberwizzard I closed that PR because it didn't work. There's no solution for this, I've raised it directly with members of the core team, but no one has commented.
@rodrigok @engelgabriel - AFAIK the current develop branch will break all bot compatibility. Possibly already broken in v72 as well.

**Comment by Cyberwizzard** [comment]
Comfirmed - broken in 0.72.1, working in 0.71.1

**Comment by ggazzo** [comment]
please look here #12914, I created this fix just as a temporary solution, until we define/explain why are removing this extra data, I swear its not just a bug or naive breakchange or negligence, but we have to prepare ourselves to adapt the driver(s) to work without that field. We are writing a doc with some whys and to receive suggestions.

**Comment by timkinnane** [comment]
Thanks @ggazzo - the fix is appreciated.

I think the problem is there's no process to prevent issues for integrations that rely on the message stream. Developers find the changes only when something breaks, then after reporting it might be two or three releases later for a fix. So there's no stability and it takes a lot of research to know which versions are reliable.

This change was known to cause issues while in develop branch, but it still got released. It would be good to see changes like this communicated before being put into a release, with some deprecated notice - where a new version of the SDK could be released in parallel with the change in core.

**Comment by bigler** [comment]
Sorry for stupid question. How to update  the rocketchat-server to 0.72.3 version via snap?
