### ISSUE TITLE
No result calling an api function in Hubot

### ISSUE THREAD

**Issue by pombaer** [RocketChat/Rocket.Chat#12578]
### Description:

I am not sure if this is a bug or an expected behavior.
I am using Hubot 2.19.0 (latest with coffescript) and node 4.8.3. I want to call the method "adminRooms" for getting a list of all rooms, but ther is no result delivered by Rocketchat. My code is:

`  
  robot.respond(/api showrooms$/i, function(res) {
    robot.adapter.callMethod('adminRooms', 'gen', [ 'c' ], 50).then(function(result) {
      console.log(result)
    })
`
### Steps to reproduce:

Run the code in a Hubot Script

### Expected behavior:

Get list of all rooms no matter if i am a Member or not.

### Actual behavior:

No result

### Server Setup Information:

    Version of Rocket.Chat Server: 0.71.1
    Operating System: Ubutu Bionic
    Deployment Method: docker image
    Number of Running Instances: 1
    DB Replicaset Oplog: ??
    NodeJS Version: the version installed in the docker image
    MongoDB Version: ??

**Comment by reetp** [comment]
Think this is an issue with hubot rather than Rocket.Chat itself.
Please ask in the #bots channel at https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close
