### ISSUE TITLE
Notification icon on taskbar missing in Arch Linux

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#12572]
Since a recent update for Rocketchat on Arch Linux (client version 2.14.1), me and a friend who both use Arch (XFCE and Mate desktop environment) do not have the expected notification icon in the taskbar. This means when someone sends a message while we are away from our computer, when we come back there is no longer an icon signifying an unread message. I do not know if this problem is only in Arch, or in every Linux distro. This problem persisted for me in every desktop environment I tried.

**Comment by tassoevan** [comment]
@mmgoilf Is the menu item `View > Tray icon` checked? Since some Gnome users don't have a system tray/notification area and we can't detect its presence, this is disabled by default in recent versions: https://github.com/RocketChat/Rocket.Chat.Electron/issues/754

**Comment by mmgoilf** [comment]
> @mmgoilf Is the menu item `View > Tray icon` checked? Since some Gnome users don't have a system tray/notification area and we can't detect its presence, this is disabled by default in recent versions: [RocketChat/Rocket.Chat.Electron#754](https://github.com/RocketChat/Rocket.Chat.Electron/issues/754)

Ah, my bad, it was unchecked. That might end up confusing some people though.
