### ISSUE TITLE
[BUG] Delete own account API only works with a lowercase hash

### ISSUE THREAD

**Issue by filipedelimabrito** [RocketChat/Rocket.Chat#12573]
The [delete own account API](https://rocket.chat/docs/developer-guides/rest-api/users/deleteownaccount/#user-delete-own-account) only works when submitting a lowercase case. As talked to @MarcosSpessatto this shouldn't be case sensitive.

**Comment by rodrigok** [comment]
Meteor always generate passwords with lowercase hashes https://github.com/meteor/meteor/blob/be6e529a739f47446950e045f4547ee60e5de7ae/packages/sha/sha256.js#L127

We could convert to lowercase before compare at the server side @MarcosSpessatto
