### ISSUE TITLE
[BUG] Cannot change channel parameter "Broadcast Channel"

### ISSUE THREAD

**Issue by zzeesstt** [RocketChat/Rocket.Chat#12589]
Cannot change channel parameter 'broadcast channel'
snap v0.70.4 stable
![broadcast_channel](https://user-images.githubusercontent.com/32969232/48312138-f14b8d80-e5b2-11e8-9584-36556b2faef3.gif)

**Comment by rafaelks** [comment]
This is reproducible in latest `develop` as well... also, if the channel wasn't created as broadcast, the option doesn't appear (screenshot).

![screen shot 2018-11-12 at 09 14 38](https://user-images.githubusercontent.com/551004/48344140-6a9ebb00-e65b-11e8-9d27-6caacfbc1a47.png)

**Comment by mydoghasworms** [comment]
This is still an issue post 1.0. Cannot change a broadcast channel to a collaborative channel.

**Comment by djnews24** [comment]
Would be great if it will be fixed... 👍

**Comment by ggazzo** [comment]
same of https://github.com/RocketChat/Rocket.Chat/issues/12492
