### ISSUE TITLE
Problem sending message in mobile version

### ISSUE THREAD

**Issue by pombaer** [RocketChat/Rocket.Chat#12598]
### Description:

I have a Android 5.0.1 with Chrome browser. If i am typing in "portrait" position the send button is not displayed, on "landscape" the button is displayed. This seams to be an issue because of low resolution.
I have 720x1280, on a other smartphone with 1080x1920 the button is shown in both situations.

### Steps to reproduce:

Use the smartphone in portrait and in landscape position.

### Expected behavior:

Button should be displayed.

### Actual behavior:

It is not displayed in portrait position.

### Server Setup Information:

Rocketchat version 0.71.1 (docker image)

### Additional context

**Comment by reetp** [comment]
@rocket-cat close

Closing for lack of further information and this may well be an edge case.
