### ISSUE TITLE
Feature: Show room related roles in the room info panel

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#12609]
If you are looking for the moderator or the owner of a room, it would be much easier if the room-related roles were displayed directly in the Room Info Panel.

**Current behavior**
To find out who has special roles in a room, you must currently look at the roles of each individual member of the room.

**Expected behavior**
For each room, you can quickly see who has which role here. Especially owners, moderators, leaders

**Comment by reetp** [comment]
Feature requests should go here please:
https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
