### ISSUE TITLE
rocketchat ios手机客户端上传图片，为何部分失败？

### ISSUE THREAD

**Issue by wuyanteng** [RocketChat/Rocket.Chat#12619]
将rocketchat部署在了自己的服务器【最新版 V0.71.1】，所有能优化的项目均已优化。ios手机客户端登陆自己的服务器上传部分图片，总失败【网页版和电脑客户端没问题】，直接闪一下就没了......而自己使用Google账号登陆了rocketchat他们的chat平台就没发现这个问题。

已排除的问题：

(1)ios客户端bug导致[因为使用同一个客户端登陆他们的chat没问题]

(2)文件上传类型已包括所有类型的image

(3)UTF-8编码设置的是：^[\u4E00-\u9FA5A-Za-z0-9_]+$ 【图片没有添加任何注释，理论上不会是编码问题】

Rocketchat is deployed on its own server [latest version V0.71.1], and all optimized projects have been optimized. Ios mobile client login to their own server to upload some pictures, the total failure [web version and computer client no problem], directly flashed it is gone ... and they use Google account to log in to rocketchat their chat platform Did not find this problem.

Excluded issues:

(1) ios client bug caused [because using the same client to log in their chat is no problem]

(2) File upload type already includes all types of images

(3) UTF-8 encoding is set to: ^[\u4E00-\u9FA5A-Za-z0-9_]+$ [The picture does not add any comments, theoretically it will not be a coding problem]

**Comment by Sing-Li** [comment]
@wuyanteng  Please report this in https://github.com/RocketChat/Rocket.Chat.iOS  for fastest attention.    Suggested English Title would be:   "iOS photo sharing sometimes fails while web upload works all the time"     Thank you for your report!
