### ISSUE TITLE
E2E channel showing enabled even when server E2E is disabled

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12612]
### Description:

This is my DM with Thiago, it's showing that E2E is enabled (but is not):

![screen shot 2018-11-13 at 13 50 35](https://user-images.githubusercontent.com/551004/48425107-45897580-e74b-11e8-82ee-1f49f43fea53.png)

This is server admin E2E configuration:

![screen shot 2018-11-13 at 13 51 25](https://user-images.githubusercontent.com/551004/48425133-52a66480-e74b-11e8-819a-e0d50e6b2fec.png)

**Comment by pkolmann** [comment]
Also if e2e is globally disabled in the server, it's still available in the chat-menu, to enable e2e
(Vers 1.1.1)
