### ISSUE TITLE
The interface switches to English after changes in user account preferences

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat#12628]
### Description:
The user has the Russian language interface. After changing any parameter in the user account preferences and applying, their interface language changes to English. But after a forced refresh of the page, the Russian language of the interface is returned.

### Steps to play:

1. Go to "My Account"
2. Change any parameter in the “Preferences” section.
3. and apply ... -> interface language change to English
4. forced page refresh -> interface language changes back

The default language is Russian.

### Expected behavior:

Change the language to English for any changes in the "Preferences" section.

### Actual behavior:

For any changes in the "Preferences" section, the interface language must match the one specified.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Ubuntu Linux 16.04.3
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3

**Comment by tassoevan** [comment]
Related to #5592 and #10922, but I'm not sure if it is a duplicate.

**Comment by sovaby** [comment]
This, # 5592 and # 10922, is not a duplicate.
  # 5592 and # 10922 - Occurs in the admin panel via web browser
cadetsv writes about the client in windows
The user changes the account preferences, the language is reset to English.

**Comment by wreiske** [comment]
@sovaby, just FYI, the windows client is just a web browser loading the same as via web browser. https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by derniwi** [comment]
Also happens with other languages. The user may change one setting, i.e. notification volume, and the language is changed to english until the web page is completley reloaded or the desktop application or the mobile app is restarted.

**Comment by lequy1010** [comment]
I think have issues with client\statup\i18n.js
`const getBrowserLanguage = () => filterLanguage(window.navigator.userLanguage || window.navigator.language);`
Because when we reload page, we can't get language from "window.navigator.userLanguage" so it will used window.navigator.language for default value.
You can change as bellow:
`const getBrowserLanguage = () => filterLanguage(Meteor._localStorage.getItem('userLanguage') || window.navigator.language);`

**Comment by gabriellsh** [comment]
Teste on 3.0.0-develop, doesn’t seem to be an issue anymore. If you still face this please reopen.
