### ISSUE TITLE
Feature Request: "Forward" Messages(s)

### ISSUE THREAD

**Issue by chenrylee** [RocketChat/Rocket.Chat#12627]
Current way to forward a message to others is:
1. Click the 3-dot behind a message;
2. Click Permalink and copy the link to this message;
3. Send the link to others.

Is there a plan that adding a more friendly way to forward a message? For example:
1. Select the message(s), and then a button appears, float or at the top of frame;
2. Click the button, and it asks user to select a destination;
3. Click the destination, complete.

It's like Telegram.

**Comment by reetp** [comment]
If you bothered to search first before posting then you would have found this:

https://github.com/RocketChat/Rocket.Chat/pull/11179

And all feature requests go in the forums

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
