### ISSUE TITLE
RC got stuck when there are more than 80 active users

### ISSUE THREAD

**Issue by edisonchen1985** [RocketChat/Rocket.Chat#12629]
We are working on the RC 0.65 version system right now. Normally we have around 300 active users. Everything goes well until two days ago, the RC got stuck very badly even users can not be able to login into the system when there are more than 50 or 80 active accounts. It can take 1 minute to switch between the channels and can not send out the message. 

We restarted the system with the command below:  systemctl restart rocketchat@3006.service  
But the above situation happens again ten minutes later when more users connect to the system. We have found some exception info as below, can you please kindly help to have a check, thanks a lot.

11月 15 17:34:49 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: Connect timed out
11月 15 17:34:49 zhoujun-KVM RocketChat[15611]:     at Connection.<anonymous> (/home/zhoujun/newcc/build1114/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
11月 15 17:34:49 zhoujun-KVM RocketChat[15611]:     at ontimeout (timers.js:475:11)
11月 15 17:34:49 zhoujun-KVM RocketChat[15611]:     at tryOnTimeout (timers.js:310:5)
11月 15 17:34:49 zhoujun-KVM RocketChat[15611]:     at Timer.listOnTimeout (timers.js:270:5)
11月 15 17:34:51 zhoujun-KVM /usr/lib/snapd/snapd[800]: retry.go:81: DEBUG: Retrying because of: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
11月 15 17:34:51 zhoujun-KVM /usr/lib/snapd/snapd[800]: retry.go:49: DEBUG: Retrying https://search.apps.ubuntu.com/api/v1/snaps/metadata, attempt 5, elapsed time=30.256333739s
11月 15 17:34:51 zhoujun-KVM /usr/lib/snapd/snapd[800]: retry.go:61: DEBUG: The retry loop for https://search.apps.ubuntu.com/api/v1/snaps/metadata finished after 5 retries, elapsed time=30.261077889s, status: P
11月 15 17:34:51 zhoujun-KVM /usr/lib/snapd/snapd[800]: snapmgr.go:411: Cannot prepare auto-refresh change: Post https://search.apps.ubuntu.com/api/v1/snaps/metadata: dial tcp: lookup search.apps.ubuntu.com on 1
11月 15 17:34:51 zhoujun-KVM snapd[800]: 2018/11/15 17:34:51.128547 snapmgr.go:411: Cannot prepare auto-refresh change: Post https://search.apps.ubuntu.com/api/v1/snaps/metadata: dial tcp: lookup search.apps.ubu
11月 15 17:34:51 zhoujun-KVM snapd[800]: 2018/11/15 17:34:51.128753 stateengine.go:98: state ensure error: Post https://search.apps.ubuntu.com/api/v1/snaps/metadata: dial tcp: lookup search.apps.ubuntu.com on 11
11月 15 17:34:51 zhoujun-KVM /usr/lib/snapd/snapd[800]: stateengine.go:98: state ensure error: Post https://search.apps.ubuntu.com/api/v1/snaps/metadata: dial tcp: lookup search.apps.ubuntu.com on 114.114.114.11
11月 15 17:34:51 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: Connect timed out
11月 15 17:34:51 zhoujun-KVM RocketChat[15611]:     at Connection.<anonymous> (/home/zhoujun/newcc/build1114/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
11月 15 17:34:51 zhoujun-KVM RocketChat[15611]:     at ontimeout (timers.js:475:11)
11月 15 17:34:51 zhoujun-KVM RocketChat[15611]:     at tryOnTimeout (timers.js:310:5)
11月 15 17:34:51 zhoujun-KVM RocketChat[15611]:     at Timer.listOnTimeout (timers.js:270:5)
11月 15 17:34:52 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: Connect timed out
11月 15 17:34:52 zhoujun-KVM RocketChat[15611]:     at Connection.<anonymous> (/home/zhoujun/newcc/build1114/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
11月 15 17:34:52 zhoujun-KVM RocketChat[15611]:     at ontimeout (timers.js:475:11)
11月 15 17:34:52 zhoujun-KVM RocketChat[15611]:     at tryOnTimeout (timers.js:310:5)
11月 15 17:34:52 zhoujun-KVM RocketChat[15611]:     at Timer.listOnTimeout (timers.js:270:5)
11月 15 17:34:55 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: Connect timed out
11月 15 17:34:55 zhoujun-KVM RocketChat[15611]:     at Connection.<anonymous> (/home/zhoujun/newcc/build1114/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
11月 15 17:34:55 zhoujun-KVM RocketChat[15611]:     at ontimeout (timers.js:475:11)
11月 15 17:34:55 zhoujun-KVM RocketChat[15611]:     at tryOnTimeout (timers.js:310:5)
11月 15 17:34:55 zhoujun-KVM RocketChat[15611]:     at Timer.listOnTimeout (timers.js:270:5)
11月 15 17:34:58 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: Connect timed out
11月 15 17:34:58 zhoujun-KVM RocketChat[15611]:     at Connection.<anonymous> (/home/zhoujun/newcc/build1114/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
11月 15 17:34:58 zhoujun-KVM RocketChat[15611]:     at ontimeout (timers.js:475:11)
11月 15 17:34:58 zhoujun-KVM RocketChat[15611]:     at tryOnTimeout (timers.js:310:5)
11月 15 17:34:58 zhoujun-KVM RocketChat[15611]:     at Timer.listOnTimeout (timers.js:270:5)
11月 15 17:34:59 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: Connect timed out
11月 15 17:34:59 zhoujun-KVM RocketChat[15611]:     at Connection.<anonymous> (/home/zhoujun/newcc/build1114/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
11月 15 17:34:59 zhoujun-KVM RocketChat[15611]:     at ontimeout (timers.js:475:11)
11月 15 17:34:59 zhoujun-KVM RocketChat[15611]:     at tryOnTimeout (timers.js:310:5)
11月 15 17:34:59 zhoujun-KVM RocketChat[15611]:     at Timer.listOnTimeout (timers.js:270:5)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]: Exception in callback of async function: Error: socket hang up
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at TLSSocket.onHangUp (_tls_wrap.js:1135:19)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at Object.onceWrapper (events.js:313:30)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at emitNone (events.js:111:20)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at TLSSocket.emit (events.js:208:7)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at endReadableNT (_stream_readable.js:1056:12)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11月 15 17:35:00 zhoujun-KVM RocketChat[15611]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by reetp** [comment]
The first problem is you are using a pretty old version if Rocket. More than 6 months out of date. 
There have been significant changes in that time that may fix your issue.
Please upgrade (and be careful upgrading direct from 0.65 to 0.71.x as it may break your DB too)
Closing for now. Please reopen if it is still an issue on latest.

**Comment by reetp** [comment]
@rocket-cat close
