### ISSUE TITLE
Login to server with different accounts

### ISSUE THREAD

**Issue by kepanin** [RocketChat/Rocket.Chat#12622]
Hi is there a way to connect with different accounts to the same server from window\ios\android.
When trying to add new server (inserting same address) it just redirects me to account that already running. Any way to workaround or will this feature will be added in the future ?

**Comment by reetp** [comment]
This is an app function rather than a Rocket function
And it is a NFR rather than a bug (ie Rocket and the apps work, but just doesn't do exactly what you want them too)

Please open a NFR in the forums https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
