### ISSUE TITLE
The name of the rooms in channels and private groups in human readable form

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat#12638]
In the release 0.71.0, the bug **“Edit room name with uppercase letters (# 12235 by @nikeee)”** has been fixed.  But we and many users used this bug to display the names of the rooms (channels) in a human readable form, which used capital letters and a space.
Now there is no such possibility.  The name of the rooms (channels) can contain only uppercase letters, numbers and symbols "-", "_".  And this is not very convenient. 
Many users are very upset about this. ((

Therefore, I propose to consider this solution.
In the form for creating a channel, add an optional “Channel Full Name” field, into which you can fill it or not.  It is possible to enter the full name in the desired format and language. And when outputting in the list of channels on the panel, display this full name, and in case of its absence in the “Channel Full Name” field, the main name of the channel.
It's like "Username" and "Name".

And don't forget to add this field "Full Channel Name" in form "Room Info" and in form "Room Info - edit" for the users and the administrator.

How is this option?

**Comment by nikeee** [comment]
As a workaround: Habe you tried setting `UI_Allow_room_names_with_special_chars` to `true`? This should allow the usage of all characters.

**Comment by reetp** [comment]
Thank you for your comment. This is not a bug per se as no errors are thrown.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/
Developers will consider all feature requests there. Pull requests are always welcome.

**Comment by reetp** [comment]
@rocket-cat label add enhancement

**Comment by reetp** [comment]
@rocket-cat close

**Comment by cadetmsv** [comment]
> As a workaround: Have you tried setting `UI_Allow_room_names_with_special_chars` to `true`? This should allow the usage of all characters.

When using this setting, it is not possible to create a room name in Russian.
