### ISSUE TITLE
Help documentation for Rocket.Chat users

### ISSUE THREAD

**Issue by s-duffey** [RocketChat/Rocket.Chat#12631]
For our instance of Rocket.Chat within the Government of Canada (called GCmessage) we wrote help documentation for our users with more information on how to use the features of the platform. 

Since Rocket.Chat's documentation seems to focus more on creating new servers, rather than how to actually use Rocket.Chat features, you may want to look at our help documentation and copy or incorporate some of the content we have written into Rocket.Chat's support. 

Our documentation for GCmessage (our version of Rocket Chat) can be found here: 

https://gccollab.gctools-outilsgc.ca/en/support/solutions/folders/2100031626/page/1?url_locale=en

**Comment by geekgonecrazy** [comment]
@s-duffey this is really awesome!  This is definitely an area we need to improve. Thanks for sharing!

@RocketChat/core Maybe this would be some good inspiration for our own?

**Comment by reetp** [comment]
A great idea but not a 'bug' in Rocket.Chat

Shouldn't this be opened in:
https://github.com/RocketChat/docs

PRs welcome.....

**Comment by reetp** [comment]
@rocket-cat close
Closing in favour of the new Issue... thanks for doing that.
 https://github.com/RocketChat/docs/issues/989
