### ISSUE TITLE
Weird monospace font on message type

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#12653]
### Description:

After the last develop update, a weird monospaced (courier-like) font appears in the message type box. Here's to hoping this is not a design decision. 😉 

### Steps to reproduce:

1. Update to RocketChat 0.72.0-develop (commit 3a154eb938b230cb68437d293b4586c6c9bed74a)
2. Try to send a message.

### Expected behavior:
The font for typing the message should be consistent with the messages being displayed.

### Actual behavior:
A weird monospaced font (which is hard to read on the Electron client) appears instead.
![image](https://user-images.githubusercontent.com/14616851/48666993-f0729a00-ea91-11e8-8138-ea252428516d.png)

### Rocket.Chat

| Version                 | 0.72.0-develop                                            |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 135                                                       |
| Database Migration Date | Sat Nov 17 2018 11:43:09 GMT-0600 (Central Standard Time) |
| Installed at            | Tue Jul 03 2018 10:28:32 GMT-0500 (Central Daylight Time) |
| Uptime                  | 6 hours, 18 seconds                                       |
| Deployment ID           | wecGmPkstnsm2e7ge                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | 3a154eb938b230cb68437d293b4586c6c9bed74a |
| ------- | ---------------------------------------- |
| Date    | Fri Nov 16 19:14:13 2018 -0200           |
| Branch  | develop                                  |
| Tag     | 0.71.0                                   |
| Author  | Marcos Spessatto Defendi                 |
| Subject | [FIX] Fix favico error (#12643)          |

### Runtime Environment

| OS Type         | Linux                                    |
| --------------- | ---------------------------------------- |
| OS Platform     | linux                                    |
| OS Arch         | x64                                      |
| OS Release      | 4.15.0-39-generic                        |
| Node Version    | v8.11.3                                  |
| OS Uptime       | 1 days, 19 hours, 58 minutes, 39 seconds |
| OS Load Average | 0.37, 0.31, 0.26                         |
| OS Total Memory | 7.79 GB                                  |
| OS Free Memory  | 403.88 MB                                |
| OS CPU Count    | 4                                        |

**Comment by bkraul** [comment]
Temporary fix for me: 

Add a style under Layout -> Custom CSS:

```css
textarea.rc-message-box__textarea {
  YourFonts-here
}
```
(You can copy the font-family from ```.global-font-family```, mine is customized add the Slack Lato font).
```css
.global-font-family {
    font-family: Lato,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Meiryo UI',Arial,sans-serif;
}
```

**Comment by reetp** [comment]
This has just appeared on https://open.rocket.chat

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/12729
