### ISSUE TITLE
User status is always online

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12667]
### Description:

Since upgrade to version 0.69.2 I hardly see any users with the status "away" anymore.

[I'm not sure whether this behavior has already been reported in another issue or fixed. For security I post it again.]

### Expected behavior:

Idle users should be displayed as away

### Actual behavior:

Users who don't work on their PC even on weekends and don't use a smartphone app are always online.

![user](https://user-images.githubusercontent.com/8544984/48734193-02e10500-ec45-11e8-9da8-1333814ca35f.png)

Graphic created with https://github.com/localguru/check_rocketchat_user_status

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Ubuntu 16.04 LTS
- Deployment Method: self compiled
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 3.4.18

**Comment by reetp** [comment]
>"I'm not sure whether this behavior has already been reported in another issue or fixed."
Always check the issues first....

At 0.69.2 you are over 2 months out of date and lots of things have changed.

As per this:
http://rocketchat.github.io/docs/contributing/reporting-issues/

>2. Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

I don't guarantee that, but it it makes sense to try.

**Comment by reetp** [comment]
Yes, I get that. I don't exactly rush myself :-)
I understand you are between a rock and a hard place - don't want to do latest and greatest due to bugs, but it may have been cured on latest. And they aren't going to fix your current version....
Is there anyway you can run a test rig (I do that myself to see what breaks before upgrading)?

**Comment by sampaiodiego** [comment]
there was a change on the default value of "auto-away" setting.. the default value was wrongly changed to `false` but when I saw that I changed it back again to `true`.. this might be causing the behavior you're seeing. if that is indeed the case, updating should fix.

**Comment by ayushnawal** [comment]
@localguru is this issue still open ?

**Comment by reetp** [comment]
@rocket-cat close
Closing on the basis of https://github.com/RocketChat/Rocket.Chat/issues/12667#issuecomment-442584069
