### ISSUE TITLE
Can't download files without extension

### ISSUE THREAD

**Issue by fabien4455** [RocketChat/Rocket.Chat#12668]
### Steps to reproduce:

1. Upload a file without extension in private message... 
2. Try to download it on rocketchat
3. It says : Network error after few minutes on google chrome

### Expected behavior:

I expect file downloading like a file with extension... 

### Actual behavior:

The file is not downloading. 
Chrome says : This page is not working
Or : Network error in downloaded files... 

### Server Setup Information:

- Version of Rocket.Chat Server: Tryed on 0.59.4 and 0.70.4 and 0.71.1
- Operating System: Ubuntu 18.04
- Deployment Method: docker ( docker-compose.yml )
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: Tryed on 3.2.X and 3.4.17 and 3.4.18...

Nothing is working

**Comment by fabien4455** [comment]
I left it empty. 

![image](https://user-images.githubusercontent.com/22091839/48767968-3c068d00-ecb8-11e8-8fc7-aaa5090ed3c4.png)

**Comment by fabien4455** [comment]
If I upload the same file with .a at the end it will work...

**Comment by fabien4455** [comment]
That's interesting, I tryed upload .a file, and when i download it I have : file.a.bin downloaded.... Why ?

**Comment by fabien4455** [comment]
![image](https://user-images.githubusercontent.com/22091839/48768345-22197a00-ecb9-11e8-8790-69b99459bc05.png)

![image](https://user-images.githubusercontent.com/22091839/48768361-2b0a4b80-ecb9-11e8-96af-e955f5e3732c.png)

![image](https://user-images.githubusercontent.com/22091839/48768453-5db44400-ecb9-11e8-87b9-27b45e39a61d.png)

**Comment by fabien4455** [comment]
But if I upload file.txt

And I download it, I'll have file.txt downloaded without any problem...

**Comment by fabien4455** [comment]
Here are all the problems... Hope you can fix it 👍 :)

**Comment by fabien4455** [comment]
UP ! Please fix it, it's not a big fix to do ( I think ) In 0.72.1 if you can

**Comment by fabien4455** [comment]
Tested on 0.72.0 nothing changed. It's actually not fixed

**Comment by reetp** [comment]
Please, stop opening multiple issues.

This may get fixed as and when it gets fixed. This is open source. Not everyone has the same priorities as you.

If you want it fixed sooner please contract Rocket and pay for support, or fix it yourself and provide a PR.

Thank you.

**Comment by fabien4455** [comment]
I'm not a dev, I report bug to help some people having this issue ( and me of course.... ) 

I've installed the 0.72.1 and it's also not working. 

Waiting the next release for fixing it. 

Sorry for my bad english I'm french.

**Comment by tassoevan** [comment]
@fabien4455 I'm closing this in favor of #8540. It's a really old issue and we need to act on it ASAP.

**Comment by fabien4455** [comment]
@tassoevan Closing this issue will help ? If I hopened a new issue it's because the old one was opened over 12 months ago and it's a big issue when you upload files without extension or some file.a file.c file.b.....

**Comment by tassoevan** [comment]
@fabien4455 We don't discriminate between old and new issues. However, I noticed that I forgot to allocate #8540 into a milestone for planning and I fixed that.

**Comment by fabien4455** [comment]
@tassoevan Hi

Thank's for the reply and please tell me by closing the old thread when it's fixed... Maybe in 0.74.0 and then I'll update 👍

**Comment by fabien4455** [comment]
Hello I tried the 0.73.1 it's fixed for extensionless files thank's it's so cool..... 

However, You didn't fixed the bug with file.a type.. or file.b... 

When you upload file.x ( where X is a letter from A to Z ) it upload like file.x but when you download it file you have file.x.bin.... That's not right

**Comment by tassoevan** [comment]
@fabien4455 I'm waiting for a response here: https://github.com/RocketChat/Rocket.Chat/issues/6026#issuecomment-450178921

**Comment by fabien4455** [comment]
Ok thank's
