### ISSUE TITLE
Release 0.71.0 - 'aldeed:template-extension' stopped working

### ISSUE THREAD

**Issue by stangrinn** [RocketChat/Rocket.Chat#12688]
### Description:
After upgrading to version 0.71.0, module 'aldeed:template-extension' stopped working.

### Actual behavior:

![2018-11-15](https://user-images.githubusercontent.com/22539990/48832244-62dcc600-ed81-11e8-953e-84d90c0436b6.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.71.0
- Operating System:  Centos 7
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  Disabled
- NodeJS Version:  8.11.3
- MongoDB Version:  v2.6.12

### Relevant logs:

Uncaught TypeError: Cannot read property '__render' of undefined
    at Blaze.Template.Template.replaces (aldeed_template-extension.js:49)
    at Object.replaceTemplates (lanet_theme.js:89)
    at lanet_theme.js:297
    at maybeReady (meteor.js:871)
    at HTMLDocument.loadingCompleted (meteor.js:883)

**Comment by reetp** [comment]
This seems to be related to creating your own theme:
https://rocket.chat/docs/developer-guides/ui-and-theming/themes/

Please follow the advice:
"We’d love to hear from anyone working on themes in the #skins-and-theming group channel."

Unless there is a genuine underlying issue in Rocket please visit the forums or https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close

Closing unless there is any underlying issues with Rocketchat itself to report
