### ISSUE TITLE
I want notification when atumomatic logout because of session timeout

### ISSUE THREAD

**Issue by dmoldovan123** [RocketChat/Rocket.Chat#12687]
- Version of Rocket.Chat Server: 0.70.4
- Operating System: Ubuntu
- Deployment Method:  tar
- Number of Running Instances: 10
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.10

I have set "login expiration days" to 1 day and all users is auto logout every days but users not have any notification when rocketchat server do this. Can the user be reminded a few minutes before being logged off?

**Comment by reetp** [comment]
First, always test on the latest version as per these links:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
https://rocket.chat/docs/contributing/reporting-issues

This is a feature request. Please open it in the correct place:
https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
