### ISSUE TITLE
Advanced notification settings [$50]

### ISSUE THREAD

**Issue by Dbzman** [RocketChat/Rocket.Chat#1268]
As mentioned in #1068 there should be an option to configure notifications on a per channel basis so that you can also for example receive desktop notifications for a channel. 
The pull request #1116 just fixes the notifications so that you get a hint in the dock. It would be cool to also have desktop notifications here.
Also it would be nice to have a global setting for receiving desktop notifications for every kind of activity.
I opened this issue just that it does not get forgotten and to not pollute the old issue.
##

**Comment by Flitterkill** [comment]
Might not be the most popular suggestion but adding audio blips per each new message in a channel would be welcome in some settings (noisy confusing ones actually) 

2 cents, etc...

**Comment by apangan** [comment]
We would also like to see custom notifications per channel. Many times, we'll create private groups per project and the icon badge is not noticeable when the application is in the background. Notification options similar to HipChat in this sense would be great.

Options per channel, private group, or direct message:
Loud: Notifications for every message
Normal: Only notified for @all, @user mentions (they also use @here which I think is less necessary)
Quiet: Only notified for @user mentions

Also, options to enable or disable any type of notification: pop up, sound, dock animation.

**Comment by shirshman** [comment]
Has anyone created code that enables the email notifications? I have threaded through all the different issues mentioned in the threads (#1654, #171, etc etc), and haven't found any solution. Am I missing something?

**Comment by dandv** [comment]
I would suggest using positive wording for the notification sound setting. Now we have

![image](https://cloud.githubusercontent.com/assets/33569/13304217/3bcf0200-db08-11e5-8e2b-45ee691a04be.png)

"Disable - false"... double negatives are not nice.

How about "New room/message notification - enabled/disabled"?

**Comment by engelgabriel** [comment]
@dandv is right! Let's change that.

**Comment by boisletterink** [comment]
+1 on apangan's comment about per-group/channel notification settings! We're happy RC users, and we have tons of different groups. So our left side bars get rather verbose and spammy. I'd love to be able to silence groups until I'm mentioned, or silence them at all. That would include not showing them on top of the left side bar; just keep'm down below, because they're not that important.

**Comment by Flitterkill** [comment]
I guess we all want more control over these things - lots of conflicting requests when you search issues on "notifications"

For my use-case, having message tones for each new message (beyond browser notifications - actually, instead of pop-up notifications) would be fantastic. Naturally, that's not going to fly for many others. Having users able to toggle this on/off would be perfect.

**Comment by AdamUOF** [comment]
Notification control is requirement if you want to use Rocket.Chat as a community chat platform.  We have up to 500 people in our chat channels at anytime.  If users can set their notification preference to email per message, we would have an insane amount of emails going out.

The way it is now is completely fine for use in a team setting but is unusable in some community settings with the way notifications currently are.

**Comment by nemolivier** [comment]
Linked to this issues : #2192 notification per roles
and #2593 coherent color notifications (difference between @all, @you, @role, etc.)

**Comment by skizzors** [comment]
+1 for original issue! It seems like the original issue has become lost with other requests, but the original is the one with a bounty and still unresolved. Having notifications for any messages in a certain channel. This is huge for my team especially for chat leaders who have a private room to discuss important matters, and I need to be notified of any new messages. It also could give users the flexibility to choose a channel they want to be always up to date with any new messages. Could be a simple option given to the chat user in "My Account" settings.

**Comment by engelgabriel** [comment]
Is this now covered by the notifications settings tab on each channel?

![image](https://cloud.githubusercontent.com/assets/1000217/18214242/50784d5a-7122-11e6-85bd-9cefdfa0cdf4.png)

**Comment by Mte90** [comment]
I think that also get a notification when someone use @all by email it's important, as I can see from the log there are no email sent it in that case.
Also in the profile it's possible to receive email only when the users is not connected but only if is a mention or dm but not when is a classic message.

**Comment by Mte90** [comment]
There is also the problem of global notification settings. As example I have all the users that ask about how to enable it so my idea was to enable as default as all messages you get a notification so in that way they are forced to disable it and ask how to do it but in that way they not lost the notifications.

**Comment by rpieszko** [comment]
Hello,

When did you think that this feature will be released ?
We use Rocket.Chat in our company and most of people are looking for setting as default all notifications on every chat rooms. 
Thanks in advance.

**Comment by engelgabriel** [comment]
The PR https://github.com/RocketChat/Rocket.Chat/pull/5366 has been mergerd

Does this do what you guys needed?

**Comment by Mte90** [comment]
As I can see that pr get the global notification settings, so in my case yes.

**Comment by marceloschmidt** [comment]
Can we close the issue? @Dbzman your thoughts? Thanks

**Comment by Dbzman** [comment]
Yes, @marceloschmidt. Looks good to me, thanks! :)

**Comment by ramiror** [comment]
Turning off @all type notifs feature is present but does not work for me.

Rocket.Chat+
Version 2.9.0
