### ISSUE TITLE
Individual chat notification sound bug

### ISSUE THREAD

**Issue by itformusic** [RocketChat/Rocket.Chat#12685]
- Operating System: 10.11.6 & 10.13.6
- App Version: 2.14.1
- Installation type: <dmg>

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
There's an issue with selecting notification sounds within an individual chat.  If you change it to "Default" there will be no sound.

### Current Behavior
By default, the individual notification sounds are empty, with nothing selected.
![image](https://user-images.githubusercontent.com/44621234/47757767-2f68b900-dc65-11e8-8907-45df81c0f4e2.png)

It will play the default user notification sound when nothing is selected.  Once any sound is selected, you can not clear it like it is set by default and can not play the default sound.

If you select "Default" it will not play any sound. You can select any other sound and it will play. Also, when you select a custom sound in here, it shows a weird name and not the correct name.
![image](https://user-images.githubusercontent.com/44621234/47757786-44454c80-dc65-11e8-9eb0-71411b0e157c.png)

### Expected Behavior
When you select default, the user system default sound should play.  Also, when selecting a custom notification sound, it should show the name, not the random characters.

**Comment by knrt10** [comment]
@itformusic the sound for default is fixed in the latest version. But I would try to fix the name of the sound.

**Comment by itformusic** [comment]
That seemed to have fixed the issue with the individual chats.

I'm not sure when this happened, but now I'm not able to select any custom sounds in the main user preferences.  It only shows the default chime.

**Comment by MikeD096** [comment]
All channels, rooms, and DMs default to a blank/null sound, vs "Default" as shown by OP.
Every user must edit every channel/room/DM to set the sound to "Default".

**Comment by itformusic** [comment]
When you change any channel/room to something other then the null, it will not sound.  Is there a way to reset it to the null (nothing selected)?  It happens on both the Mac app as well as the web interface.  We're running server version 1.1.3

**Comment by mrskizzex** [comment]
^ I also have the same problem on version 1.3.2. Moreover I don't get a sound from mentions when it's the bot who is sending the message.

**Comment by eidermar** [comment]
We do have the exact same problem. Once the sound was changed for a room/channel no sound will be played no matter which setting is used. Running latest Version macOS desktop client.

**Comment by itformusic** [comment]
I've figured out a work around for now.  If you delete the room, it'll reset the individual sound settings for that room and you should hear the notification sound.

**Comment by tavor118** [comment]
The same problem

**Comment by antkaz** [comment]
@tavor118 possibly fixed here #15771
