### ISSUE TITLE
German translation issue: "away" after seconds or milliseconds?

### ISSUE THREAD

**Issue by LukeLR** [RocketChat/Rocket.Chat#12697]
### Description:

In the German translation of Rocket.chat, there is a setting which says "Abwesend nach Inaktivität (in ms)" ("Absence after inactivity (in milliseconds)"), which probably means that the status is set to away after a given timespan. But the description of that field reads: "Zeitraum bis sich der Status in away ändert. Der Wert muss in Sekunden angegeben werden." ("Interval until status is set to away. The value has to be entered in seconds"). So the description and the label of the field disagree, is the setting in milliseconds or seconds?

### Steps to reproduce:

1. Login on RocketChat instance
2. Make sure that the language is set to German.
3. Go to "Accounts" -> "Preferences"
4. Scroll down to "Verfügbarkeit" (availability).

### Expected behavior:

Both the description and the label agree on the unit of the setting.

### Actual behavior:

The unit of the setting differs between the description and the label.

### Server Setup Information:

Unknown

**Comment by tassoevan** [comment]
A fix was merged recently: https://github.com/RocketChat/Rocket.Chat/commit/4e0d62407e3058fcf3920d9f4faf05e9726bb67c. It will be available for 0.72.0 version.
