### ISSUE TITLE
pretext in message attachments does not get displayed

### ISSUE THREAD

**Issue by svrnwnsch** [RocketChat/Rocket.Chat#12691]
### Description:

I have a Webhook incoming where all text is only in the `attachments` in the `pretext` field. 
This text does not get displayed. 
![See this picture](https://user-images.githubusercontent.com/1852828/48839742-c28c9e80-ed8c-11e8-85f7-e43c5d6ca0a6.png)

The corresponding message to this was:
```
content:
{
   "attachments":[
      {
         "fallback":"Some text with / and Ü (<https://example.com|BUG>)",
         "pretext":"Some text with / and Ü (<https://example.com|BUG>)",
         "color":"#e6e6e6",
         "fields":[
            {
               "title":"State",
               "value":"Fixed",
               "short":true
            },
            {
               "title":"Priority",
               "value":"Minor",
               "short":true
            },
            {
               "title":"Assignee",
               "value":"",
               "short":true
            }
         ]
      }
   ]
}
```

Maybe this is connected to #3828
The only workaround I use is to manually copy the entry of the `pretext` field into a `text` field.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v8.11.3

**Comment by TomaszDom** [comment]
I can confirm this bug in 0.73.2, it used to work in 0.69.x, it's a regression. Doesn't look like a particularly crucial thing, but for us it is.

**Comment by TomaszDom** [comment]
Another example which worked in 0.69.x:

```
Method: POST
URI: REDACTED
HTTP Version: 1.1
Headers:
{
  Content-Type: application/json; charset=utf-8
}
Content:
{
  "attachments": [
    {
      "fields": [
        {
          "title": "Commits (1)",
          "value": "<https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/commit/33b55f7cb7e7e245323987634f960cf4a6e6bc74|33b55f7> Fixed bug in web.config file\r\n",
          "short": false
        }
      ],
      "mrkdwn_in": [
        "pretext",
        "fields"
      ],
      "pretext": "Jamal Hartnett pushed updates to `Fabrikam-Fiber-Git`:`master`.",
      "fallback": "Jamal Hartnett pushed a commit to Fabrikam-Fiber-Git:master.\n - Fixed bug in web.config file 33b55f7c"
    }
  ]
}
```

**Comment by TomaszDom** [comment]
Can we have this regression assigned to a future milestone? All of our webhooks rely on this getting fixed, we're getting mostly empty messages.

**Comment by engelgabriel** [comment]
possibly related to https://github.com/RocketChat/Rocket.Chat/pull/11578
