### ISSUE TITLE
Shift Enter cursor moves to wrong position

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#12698]
Have just noticed this on https://open.rocket.chat which is running 0.72.x

In the message box type a line.

Press Shift + Enter a couple of times and then paste a line of text.

Go back up to the top line and either Shift + Enter, or add some text and Shift + Enter.

Cursor drops the the end of the pasted text rather than the following line.

This is a change in behaviour from 0.71.1 

Possibly related to the font issue here - I guess something has changed in the message box code.

https://github.com/RocketChat/Rocket.Chat/issues/12653

**Comment by tassoevan** [comment]
Maybe I've introduced it with #12507. I'll look at it.

**Comment by reetp** [comment]
Thanks. Couldn't figure out what was going on at first! Driving me nuts now, especially as I flip from my own 0.71.1 to open.rocket.chat on 0.72.x and forget which one has the issue!
