### ISSUE TITLE
dev install: meteor npm start hangs at "Starting Email Intercepter"

### ISSUE THREAD

**Issue by fyngyrz** [RocketChat/Rocket.Chat#12695]
### Description:

`meteor npm start` hangs at "Starting Email Intercepter"

### Steps to reproduce:

1. Install fresh Ubuntu 18.04.1
2. Follow dev guide [here](https://rocket.chat/docs/developer-guides/quick-start/):
  * installs require use of `sudo`:
   * install Python 27
   * install Git
   * install Meteor
  * cd to repo's local dir (as normal user)
  * git clone repo to local dir
  * `meteor npm start`
3. `meteor npm start` hangs at "Starting Email Intercepter"

---

### Additional information verifying machine hardware:

This works:

1. Install fresh Ubuntu 18.04.1
2. install snap following snap install guide [here](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/)
3. install rocketchat snap
4. server works as expected (but cannot do development on it, so it's useless.)

### Expected behavior:

I expected rocketchat to start. The guide says:

> When the server is ready, you will see a green box within the terminal with “Server Running” at the top.

### Actual behavior:

No such box appears, and going to `http://localhost:3000/` results in no response from server.

`meteor npm start` hangs indefinitely (I let it go overnight last night) at "Starting Email Intercepter"

`top` reports `node` is consuming 10% to 20% of one 2.9 GHz XEON core indefinitely once it hangs. This stops when I kill the job by entering `^c` in the shell.

I also tried `meteor npm start -- --port 4000`, in case something was running at port 3000, same results, hangs in the same place, no server responds at `http://localhost:4000`

Note near the end, there is a `MODULE NOT FOUND` message on the console which appears to be coming from `boot.js`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72
- Operating System: Ubuntu 18.04.1
- Deployment Method:  git repo as of 2018, Nov 20
- Number of Running Instances: One
- DB Replicaset Oplog: huh?
- NodeJS Version: 8.10.0
- MongoDB Version: No idea

### Additional context

![screen shot 2018-11-21 at 3 06 05 pm](https://user-images.githubusercontent.com/11237323/48870703-038dae80-ed9f-11e8-9ed2-a3cf48c26477.png)

### Relevant logs:

Server never starts
Consequently logs cannot be collected

**Comment by reetp** [comment]
The docs are not great, but it isn't that difficult even for a non JS/Node person like me.

Took about 20 minutes to get it right following the error messages for modules and installing them, and I was even using a lighweight VM with Devuan.... 

Have done a PR with some details here.

https://github.com/RocketChat/docs/pull/998

This should really be closed as it isn't an actual issue with Rocketchat itself, and opened as a documentation bug.

**Comment by reetp** [comment]
@rocket-cat close

Please follow up on the PR, or with a Documentation bug

**Comment by MartinSchoeler** [comment]
@fyngyrz could you try following [this](https://rocket.chat/docs/developer-guides/quick-start/) document again? It has been updated now and it should offer more ways to troubleshoot. Thanks!

**Comment by fyngyrz** [comment]
@reetp 

> Have done a PR with some details here.
> [RocketChat/docs#998](https://github.com/RocketChat/docs/pull/998)

I navigated to the PR; no solution to this specific issue was identified.

So what is the solution to the hang? That's where I am now. What step should I take to get past it? Are you suggesting dumping the entire install and starting over? It seems like a simple question:

Q: meteor npm start hangs at "Starting Email Intercepter": how to move on?
A: ???
