### ISSUE TITLE
Merge information when adding many users

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat#12700]
## Description

![zrzut ekranu 2018-11-22 o 12 31 55](https://user-images.githubusercontent.com/3521624/48900939-1adaa380-ee54-11e8-9075-26549a2582d7.png)

When somebody add new people. You see them in new line. It's unnecessary information. You could merge them.

`User xxx was adde by yyy`

**Comment by reetp** [comment]
As Rocket itself isn't actually broken this should be opened as a NFR in the forums please:

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
