### ISSUE TITLE
Not possible to remove avatar URL from a webhook once you have it and preview with emojis aren't being presented

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#12704]
Two problems here:

1. Cannot remove the avatar URL;
2. On the preview, is not showing the emoji;

![2018-11-22 14 51 46](https://user-images.githubusercontent.com/551004/48915581-50888800-ee66-11e8-89c8-1754e4ba0e30.gif)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
