### ISSUE TITLE
Default filter on Opened Chats only instead of All chats in window "Current Chats"

### ISSUE THREAD

**Issue by monty241** [RocketChat/Rocket.Chat#12703]
## Setup
- Operating System: Windows 10, Mac OSX
- App Version: 2.15.0 develop
- Installation type: exe & dmg

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
When you select in Live chat, the window "Current Chats" shows all chats with any status and served by anyone. However, Livechat is not exactly very reliable currently so we need to check the status often.

### Current Behavior
The default filter is to display all chats, independent of status.

### Expected Behavior
From the typical user perspective it would be easier to start by displaying on Open chats, while keeping the action to switch to display All chats independent of status.

![image](https://user-images.githubusercontent.com/7579444/48907047-a8bf8a00-ee66-11e8-8ed6-066c4aaee8f3.png)

**Comment by engelgabriel** [comment]
Maybe storing theusers last selection in the local storage would be better?
