### ISSUE TITLE
User_left is not translated by I18n

### ISSUE THREAD

**Issue by mathysie** [RocketChat/Rocket.Chat#12716]
When a user leaves a channel, in Dutch the message 'gebruiker links' is displayed as a literal translation of 'user' (gebruiker) and 'left' (links). This 'links' translates to the direction 'left', not the verb 'to leave'. Furthermore, in the i18n-files, the translation 'Heeft de kamer verlaten' is given, which is a good translation. 

I suppose that 'User_left' is not recognized by the i18n, after which the literal translation kicks in. I suppose this bug also occurs at all other translations, as the I18n-file for Dutch is correct.

**Comment by tassoevan** [comment]
I've found the bad translation, but for the Livechat client: https://github.com/RocketChat/Rocket.Chat/blob/0f7717e28241b60fb768469413721ebbc04c871b/packages/rocketchat-livechat/.app/i18n/nl.i18n.json#L42
Is that your case?

**Comment by mathysie** [comment]
Thank you, that is my case!

**Comment by mathysie** [comment]
Maybe you also want to replace the translation of `User_joined` for the Livechat client by
https://github.com/RocketChat/Rocket.Chat/blob/01da80a034df10dbf105d550a0cb0a7c86fa2e88/packages/rocketchat-i18n/i18n/nl.i18n.json#L2636
As the translation of `User_joined` for the Livechat client is correct, the translation given is better in my opinion.

**Comment by mathysie** [comment]
Looking at https://github.com/RocketChat/Rocket.Chat/blob/0f7717e28241b60fb768469413721ebbc04c871b/packages/rocketchat-livechat/.app/i18n/nl.i18n.json, there are more wrong and incorrect translations to Dutch. Would you like me to create a pull request with the correct translations?

**Comment by renatobecker** [comment]
Hi @mathysie!

If you're willing to fix the Livechat i18n files(Dutch), it would be very nice submitting a PR fixing the incorrect strings. Fell free to do that! ;D

Thanks!

**Comment by mathysie** [comment]
I've provided a PR with some strings fixed!
