### ISSUE TITLE
OpLog error in logfiles

### ISSUE THREAD

**Issue by luckenbach** [RocketChat/Rocket.Chat#12719]
### Description:

OpLog error in logs

### Steps to reproduce:

Have a OpLog enabled RC instance

### Expected behavior:

No errors in logs

### Actual behavior:

This message repeats in the logs

```Error in oplog callback TypeError: Cannot read property 'u' of undefined     at ModelsBaseDb.RocketChat.models.Subscriptions.on (/app/bundle/programs/server/app/app.js:13272:58)     at emitOne (events.js:116:13)     at ModelsBaseDb.emit (events.js:211:7)     at ModelsBaseDb.processOplogRecord (/app/bundle/programs/server/packages/rocketchat_lib.js:12178:12)     at /app/bundle/programs/server/packages/mongo.js:1494:7     at runWithEnvironment (packages/meteor.js:1238:24)     at Object.callback (packages/meteor.js:1251:14)     at /app/bundle/programs/server/packages/ddp-server.js:2130:36     at Array.forEach (<anonymous>:null:null)     at Function._.each._.forEach (packages/underscore.js:139:11)     at DDPServer._Crossbar.fire (/app/bundle/programs/server/packages/ddp-server.js:2128:7)     at /app/bundle/programs/server/packages/mongo.js:1719:26     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at packages/meteor.js:502:25     at runWithEnvironment (packages/meteor.js:1238:24```

### Server Setup Information:

- Version of Rocket.Chat Server:  0.71
- Operating System: CentOS/k8s
- Deployment Method: docker
- Number of Running Instances:  3
- DB Replicaset Oplog:  Yes
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.9

### Additional context

Error just shows up inside of the logs

**Comment by geekgonecrazy** [comment]
Based on dm conversation seems like this is related to readPreference=nearest.  Which is likely related to: #8064

**Comment by engelgabriel** [comment]
This has been fixed on later versions
