### ISSUE TITLE
File uploads with .. (folder up) as name fail

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#12723]
### Description:

When uploading a file, and setting the filename as `..`, the file will not be saved and show up broken.

### Steps to reproduce:

1. Upload a file
2. Set the Filename field to `..`
3. Watch the carnage

### Expected behavior:

It uploads

### Actual behavior:

Nope!

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Ubuntu Server
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v8.11.3
- MongoDB Version: ?

### Additional context

Using `.` works fine.

### Relevant logs:

No logs.

**Comment by knrt10** [comment]
On it, fixing this

**Comment by tsukiRep** [comment]
Thank you! :+1:
