### ISSUE TITLE
German translation of "You reacted with ..." incorrect

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#12720]
### Description:

The German translation of a `reaction` ("You reacted with") is not correct. It must read: "Sie reagierten mit: ..." instead of "Sie reagierte mit: ...".

### Steps to reproduce:

1. Set your profile to German
2. react on a message
3. move the mouse over the `reaction`

### Expected behavior:

It must read: "Sie reagierten mit: ..." .

### Actual behavior:

Translation is "Sie reagierte mit: ..." .

![typo](https://user-images.githubusercontent.com/8544984/48974090-4d4ff080-f04e-11e8-90eb-a5f8a4f3d424.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.0-rc.1 (open.rocket.chat)

**Comment by localguru** [comment]
And why use the formal term of address "Sie" instead of "Du". I would prefer the German "Du".

**Comment by zdumitru** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-i18n/i18n/de-IN.i18n.json#L2092

**Comment by localguru** [comment]
See https://github.com/RocketChat/Rocket.Chat/pull/12761
