### ISSUE TITLE
Redhat Container Catalog Version is Out of Date

### ISSUE THREAD

**Issue by homelinen** [RocketChat/Rocket.Chat#12728]
We were looking to use the Redhat Catalog version of Rocket.Chat in Openshift but I noticed the release is quite old. https://access.redhat.com/containers/?tab=overview#/registry.connect.redhat.com/rocketchat/rocketchat

Saw that after the last release to this registry there was a ticket to automate the release (#10414) but it doesn't appear to have been released since then? 

Not sure if there is a process on the Redhat side they need to approve or if there is another problem.

Would be nice to have newer images in this registry (where I work we are locked down by OS choice and Registries so can't just use the Dockerhub images)

Happy to help if I can but this seems like an issue in the build processes or something on Redhat side.

**Comment by geekgonecrazy** [comment]
@homelinen hey thanks for opening this. 

It looks like for some reason their auto-build service hasn't been detecting our tags like its supposed to. 

I'm triggering an update and have reached out to the team on redhat side to hopefully get this resolved.

**Comment by geekgonecrazy** [comment]
Newest version now live.  Will continue to talk with redhat team to see why its not automatically doing this.

**Comment by homelinen** [comment]
@geekgonecrazy that's great, thank you very much for sorting out!
