### ISSUE TITLE
Can't create personal access token

### ISSUE THREAD

**Issue by Gemorroj** [RocketChat/Rocket.Chat#12733]
### Description:

A placeholder is displayed instead of the token.

### Steps to reproduce:

1. Go to profile
2. Click on Personal access token
3. Create token

![pat](https://user-images.githubusercontent.com/885731/49079501-c4090b80-f251-11e8-84da-bc01e7f40eca.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: CentOS Linux release 7.5.1804 (Core) (Linux localhost.localdomain 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
- Deployment Method:  https://rocket.chat/docs/installation/manual-installation/centos/
- Number of Running Instances: 1
- DB Replicaset Oplog: disabled
- NodeJS Version: v8.11.3
- MongoDB Version: v3.6.9

### Additional context

It seems the problem is not English localization (use Russian).
If you switch the language to English, the tokens are created correctly.

**Comment by fabiopasini** [comment]
Hi, try to change the language to English and generate the key again.

**Comment by MarcosSpessatto** [comment]
@Gemorroj I did some tests in the latest version and it worked well. Can you please update your server and try again? And if the problem still there, please let me know. Thanks.

**Comment by MarcosSpessatto** [comment]
@Gemorroj I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13801) solve this issue. Can you please test with the new version?

**Comment by Gemorroj** [comment]
@MarcosSpessatto Sorry for the long wait. Unfortunately I don't have a test environment to test the issue on right now.

**Comment by MarcosSpessatto** [comment]
Okay, I'll close this for now, feel free to reopen if you want. :slightly_smiling_face:
