### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#1273]
Right now errors are either handled sparsely or not at all. Creating this issue as a discussion/prompting for people to help out with suggestions based upon https://github.com/RocketChat/Rocket.Chat/pull/1265#discussion_r43278148. The toaster is okay for showing error notifications, but if it's a major error the toaster isn't fine in my opinion.
##

**Comment by MartinSchoeler** [comment]
@graywolf336 Have we solved this problem yet?

**Comment by graywolf336** [comment]
Not really, but it has improved.
