### ISSUE TITLE
rocket chat not working in centos vps

### ISSUE THREAD

**Issue by madawadeshan** [RocketChat/Rocket.Chat#12744]
Hi All,
I have already set up the rocketchat in my Centos VPS. it has worked a couple of weeks as normal.
but now I can’t run the rocketchat in my VPS I don’t know why this happened.
So i re-installed the rocketchat according to the documentation but still not working.

after I type this command

systemctl status rocketchat

● rocketchat.service - Rocket.Chat server
Loaded: loaded (/etc/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Wed 2018-11-28 15:06:01 AEDT; 1h 6min ago
Process: 50733 ExecStart=/usr/local/bin/node /opt/rocket/Rocket.Chat/main.js (code=exited, status=217/USER)
Main PID: 50733 (code=exited, status=217/USER)

Nov 28 15:06:01 ls1.mychat.com.au systemd[1]: Started Rocket.Chat server.
Nov 28 15:06:01 ls1.mychat.com.au systemd[1]: Starting Rocket.Chat server…
Nov 28 15:06:01 ls1.mychat.com.au systemd[1]: rocketchat.service: main process exited, code=exited, status=217/USER
Nov 28 15:06:01 ls1.mychat.com.au systemd[1]: Unit rocketchat.service entered failed state.
Nov 28 15:06:01 ls1.mychat.com.au systemd[1]: rocketchat.service failed.

this is my rocketchat.service file

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://mychat.com.au:3000/ PORT=3000
[Install]
WantedBy=multi-user.target

and I can’t run the home page of rocketchat with curl

curl http://localhost:3000
curl: (7) Failed connect to localhost:3000; Connection refused

Mongo db is currently working perfectly

please help me :(

**Comment by moonwolf-github** [comment]
I think you need to include relevant parts of `/var/log/messages`.

**Comment by reetp** [comment]
No one can help you without some more detailed information.

Please read this:
https://rocket.chat/docs/contributing/reporting-issues

Then fill this out:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Also have a read on other issues starting rocketchat with systemd.

e.g

**Comment by MartinSchoeler** [comment]
@madawadeshan Can we move this to https://forums.rocket.chat/ ? There you will have more help from the community to debug your issues. After that if you find a bug in rocket.chat or a problem on the documentation, please reopen this or create a new issue on the docs repo. Thanks!
