### ISSUE TITLE
How to run rocketchat like "https://mysite.com/chat"

### ISSUE THREAD

**Issue by Huiiyi** [RocketChat/Rocket.Chat#12746]
My caddyfile already insert like this :
mysite.com/chat {
        proxy / 127.0.0.1:3000 {
                header_upstream X-Forwarded-Proto {scheme}
                header_upstream X-Forwarded-For {host}
                header_upstream Host {host}
                websocket
        }
}

And What should I insert in rocketchat.service "ROOT_URL"

why everytime i changed "ROOT_URL" and restart rocketchat, the "Site URL" are not change?

**Comment by reetp** [comment]
This is a support issue rather than a bug in RocketChat

Please read the documentation:
https://rocket.chat/docs/installation/manual-installation/

Any support questions should be opened in the forums:
https://forums.rocket.chat/
Or ask in #support at https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close
