### ISSUE TITLE
"Mark as read" sometimes does nothing

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#12743]
### Description:

Sometimes hitting the "mark as read" does nothing.

### Steps to reproduce:

1. Have messages that are unread
2. Hit mark as read

### Expected behavior:

Should mark all messages as read.

### Actual behavior:

Doesn't always mark messages as read.

![mark as read2 mov](https://user-images.githubusercontent.com/6295044/49122987-dcdee480-f284-11e8-847e-103b41b98866.gif)

### Server Setup Information:

open.rocket.chat on Tuesday, Nov 27th at ~8:30 EST.

**Comment by sampaiodiego** [comment]
some times open server is really slow, which can cause this. we might need to better show what is going on (like adding a loading and add a timeout to show an error) but I think it's working fine.

**Comment by wreiske** [comment]
I've noticed that often times the "unread" red bar in channels does not go away, even though you click out of the conversation, click in, move around, etc.

**Comment by frdmn** [comment]
Seems related to #9319

**Comment by ggazzo** [comment]
I'm quite confident we already fixed this issue, any problem please reopen,
