### ISSUE TITLE
Wrong position of buttons "new messages bar"

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#12758]
### Description:

`JUMP TO FIRST UNREAD` and `MARK AS READ` buttons are wrongly aligned to the top as shown on the image below:

![image](https://user-images.githubusercontent.com/8591547/49178148-23d8e280-f336-11e8-8517-4955d5290fb1.png)

### Steps to reproduce:

1. Open a channel with unread messages

### Expected behavior:

See buttons with same alignment as `XXX NEW MESSAGES SINCE YYY`

### Actual behavior:

Buttons are aligned on top

### Server Setup Information:

- Version of Rocket.Chat Server:  0.72.0

**Comment by parammittal16** [comment]
@sampaiodiego can i do this ?

**Comment by sampaiodiego** [comment]
absolutely @parammittal16 :smiley: would be very much appreciated
