### ISSUE TITLE
Rocket.Chat does not find "Sergey Aleksandr" via Search button.

### ISSUE THREAD

**Issue by igorr-stc** [RocketChat/Rocket.Chat#12750]
### Description:

We have user with full name "Sergey Aleksandr". "Sergey" is surname, and "Aleksandr" is name.
LDAP is used for user backend.
So user with this name could not be found via "Search" button (one with looking glass) in web application and in Electron application.
User can be found by this name if you try to mention him (\@Sergey ...) and he can be found via Directory button (one with globe).

### Steps to reproduce:

1. Press "Search"
2. Enter "Sergey" into input box
3. "Sergey Aleksandr" does not appear in user list
4. Press "Directory"
5. Go to "Users" tab
6. Enter "Sergey" and he is among other users in the list

### Expected behavior:

It should be possible to find "Sergey Aleksandr" via Search button.

### Actual behavior:

"Sergey Alexandr" never appears in list, even if you enter his full name. There are some "Sergey's" and "Aleksander's" in the list.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.68.5, but I have tried this with 0.71.1 too
- Operating System:  Ubuntu 16.04
- Deployment Method: docker
- Number of Running Instances:  2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.2

**Comment by sharkmax88** [comment]
I join the question, since the search works only by user login, and I would like the search to also work on the "name" field specified during registration.

**Comment by igorr-stc** [comment]
It works by name, it just does not work with this name.

**Comment by sharkmax88** [comment]
Yes, I agree, today, after prophylaxis on the server after a reboot, I noticed that the rocket was updated before the release of 0.72.1 and the search started working as it should. The question is removed!

**Comment by igorr-stc** [comment]
Version 0.71.1 - works.

**Comment by igorr-stc** [comment]
Oops. It "worked" in 0.71.1 because I have an active chat with this user. If I delete chat I still can't find him via search in main interface :-(

**Comment by igorr-stc** [comment]
Still does not work in 0.74.3

**Comment by ggazzo** [comment]
@igorr-stc what about 2.1.0 version? its a weird behavior I cant reproduce =/
test if you can reproduce on open.rocket.chat let me know
