### ISSUE TITLE
Remove attachments from RocketChat database

### ISSUE THREAD

**Issue by mdanovz** [RocketChat/Rocket.Chat#12752]
Hello everyone.
I have RocketChat 0.71.1
Located on console.cloud.google.com. The installation done from the docker and is controlled by kubernates.
The database is mongo v4.0.4.
For a long time the type of storage was GridFS (save to database) for downloading files. Now the download type has changed to Google Cloud Storage.
How to correctly remove attachments from the Mongo database and RocketChat does not break down?
Searched everywhere but nowhere is there a solution
If you know, tell me how to solve the problem.

**Comment by localguru** [comment]
I would post your question here https://forums.rocket.chat/c/community-support as this is not an issue.
