### ISSUE TITLE
Adding reaction to minimized media re-opens it

### ISSUE THREAD

**Issue by AlexVonB** [RocketChat/Rocket.Chat#12765]
### Description:

When adding a reaction (emoji) to an image or gif that has been minimized (small black triangle) before, that media will get re-opened on *all* clients.

### Steps to reproduce:

1. Send image or gif
2. Minimize media by clicking on the small black triangle
3. Add any reaction

### Expected behavior:

Media does not get maximized

### Actual behavior:

Media gets maximized on every client

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.0
- Operating System: Ubuntu 16.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: 8.9.3 - x64
- MongoDB Version: 3.6.7

**Comment by AlexVonB** [comment]
I guess the server emits the message, after it was reacted to: https://github.com/RocketChat/Rocket.Chat/blob/70fe7df1187ca26422b4f02decb41982a9520b3a/packages/rocketchat-reactions/setReaction.js#L96 That could replace the message on the client side, while the collapsed-status is not saved in the model.

**Comment by NikhilM98** [comment]
I'm not that familiar with Rocket.Chat codebase enough, but I think that adding `collapsed-status` to the message model would not be the best choice. We don't want the collapse-status of a person to be stored in the server or to affect the collapse-status of another client.

Collapse-status should be stored on the client side and the client should decide that whether to `collapseMediaByDefault` or not.

The problem, in this case, is that when a person reacts on a media. An event is published from the server which makes the 'rocketchat-message-attachments' component re-render on the client side. When that component re-renders it checks for 'unless mediaCollapsed' status which returns true and the expanded image is rendered.

I'm not sure what's making `this.collapsed` of `Template.messageAttachment` to reset.

I'm new to Rocket.Chat and I would like to work on this issue. It would be great if someone from Rocket.Chat community could mentor me.

**Comment by himanish-star** [comment]
@tassoevan could I work on this issue?
