### ISSUE TITLE
chat opened twice when login using SAML

### ISSUE THREAD

**Issue by fiannolo** [RocketChat/Rocket.Chat#12774]
I'm using simplesaml php as authentication method against rocket chat and when i try to login, only SOMETIMES the modal popup opened is not closed after authentication and i endup by having two rocket chat windows opened.

![image 2](https://user-images.githubusercontent.com/18537446/49239486-453eda80-f3d9-11e8-9d9a-9275ea150a2c.png)

Please let me know your thouts about it and thank you very much for your hard work.

**Comment by pierre-lehnen-rc** [comment]
This bug was fixed last year but we missed this report, so I'll be closing it.
