### ISSUE TITLE
IE 11 display 0.72 version with some problems

### ISSUE THREAD

**Issue by asand3r** [RocketChat/Rocket.Chat#12783]
### Description:
After upgrading Rocket.Chat to 0.72 we have some viewing problems. I've attached some screenshots with bugs, I think it describes my problems better than words.

### Steps to reproduce:

1. Upgrade server to 0.72.0;
2. Try to use it with Internet Explorer 11

### Actual behavior:
1. Logon screen in IE 11:
![logon_screen](https://user-images.githubusercontent.com/13959303/49275082-42042700-f48b-11e8-922e-9e6f8854f158.PNG)
2. List of chats. The char on icon is not centralized.
![chat_lists](https://user-images.githubusercontent.com/13959303/49275115-56e0ba80-f48b-11e8-88d7-7fc3d2c3ca5c.PNG)
3. Finally, next one represents difference between Firefox 63 and IE 11.
![diff_ff_ie](https://user-images.githubusercontent.com/13959303/49275365-2baa9b00-f48c-11e8-975d-cb101badacd3.png)
Look at avatars quality too.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.0
- Operating System: CentOS 7.5.1804
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6

**Comment by paulstephan** [comment]
Any workarounds for these issues in Internet Explorer? It would be great to at least get the login screen  fixed!

**Comment by secretoB** [comment]
Has anyone addressed this issue or have a workaround?

**Comment by Abraka** [comment]
Only workaround is not to use IE. Even microsoft give up on it.

**Comment by secretoB** [comment]
Add the following to your Layout - Custom CSS, worked for me:

@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
    // IE10+ CSS here


#login-card input#emailOrUsername {
  height:40px;
}

#login-card input#pass{
  height:40px;
}
  
#login-card button.login{
  padding: 13px;
}
  
}

**Comment by paulstephan** [comment]
Thanks for the tip but Rocket.Chat 0.74.3 doesn't seem to work at all with Internet Explorer. Not a big deal, since even Microsoft is giving up on IE, like Abraka said. But IE is however still widely in use so some kind of support would be nice..
<img width="338" alt="Screenshot 2019-03-22 at 22 37 11" src="https://user-images.githubusercontent.com/46940914/54851559-0f5c9380-4cf3-11e9-9f09-5b9a4e2f4965.png">
.

**Comment by engelgabriel** [comment]
@ggazzo has this been fixed?

**Comment by secretoB** [comment]
Originally we thought it was, I had someone from our dev team modify the CSS which worked for about a week, but then nothing.. So maybe something changed in the background that we are unaware of.

Works fine in Chrome.

Bob Secreto
O: 336.621.6212 | M: 802.249.8823
www.terminix-triad.com<http://www.terminix-triad.com/>

Click to learn about our culture and careers<https://terminix-triad.com/contact/careers>

**Comment by ggazzo** [comment]
> @ggazzo has this been fixed?

@engelgabriel any version above 1.0 should be fine 

https://github.com/RocketChat/Rocket.Chat/pull/14422

**Comment by ggazzo** [comment]
@asand3r please feel free to reopen if the problem persists (version > 1.0)
