### ISSUE TITLE
How to add realtime-api

### ISSUE THREAD

**Issue by Shiroyan** [RocketChat/Rocket.Chat#12785]
I want to develop a new realtime-api
For example

1.  Create a file in `/packages/rocketchat-lib/server/functions`, name it as `getMessageHistory.js`, the content is as same as `loadMessageHistory.js`, of course, i will replace `loadMessageHistory` to `getMessageHistory`
2.  Create a file in `/packages/rocketchat-lib/server/methods`, name it as `getHistory.js`, write some code , register methods
```
Meteor.methods({
  getHistory () {....}
})
```
3.  In `/packages/rocketchat-lib/package.js`,  add
```
api.addFiles('server/functions/getMessageHistory.js', 'server');
api.addFiles('server/methods/getHistory.js', 'server');
```  
4. call the method `getHistory`
```json
{
  id: ""
  method: "getHistory"
  msg: "method"
  params: ["E9TJgqz3B9C8xZRsgpFKb842Pfq8cwZyuE", 1543248000000, 1543334399000]
}
```
At last , i get the response: 
```json
{
  error: {
    error: 404
    errorType: "Meteor.Error"
    isClientSafe: true
    message: "Method 'getHistory' not found [404]"
    reason: "Method 'getHistory' not found"
  },
  id: ""
  msg: "result"
}
```

It must something wrong,  but i don't know,  can somebody tell me ? thanks

**Comment by reetp** [comment]
This is a support issue and not a RocketChat issue.

Please open a thread in the forums https://forums.rocket.chat/latest or ask in https://open/rocket.chat

PRs are welcome of course.

**Comment by reetp** [comment]
@rocket-cat close
