### ISSUE TITLE
GDPR non compliance with Livechat data

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#12789]
After some discussion on open.rocket.chat it appears there is a major GDPR compliance issue with RocketChat and Livechat data which makes Rocket chat non GDPR compliant at this point of time if you use the Livechat widget (and possibly Form items via the API)

The issue originally raised was how to hide or disable the IP address collected for Livechat agents.

It transpires that not only is this data then stored in the Livechat record, but if that record is deleted the data remains in the database with no easy way to delete it.

This make anyone using a Livechat widget unable to comply with GDPR.

Remedial Actions

1. On/Off switch for Email address collection in Widget
2. On/Off switch for background IP address collection in Widget
3. Deletion of Livechat record should remove all data from the database (retrospectively too)

References:
https://github.com/RocketChat/Rocket.Chat/issues/9684
https://github.com/RocketChat/Rocket.Chat/pull/10584

**Comment by reetp** [comment]
I know this has been labelled a feature request, but it isn't, it's a bug, and for many it is a serious and potentially enormously costly legal issue.

Rocket claims to delete data according to GDPR.

It clearly does not.

I'd imagine retrospectively clearing old data may well be problematic.... if a chat has been deleted as per current settings, but data remains in the db, then admins have a big problem on their hands.

At the very least there should be information to clearly state that currently Rocket is not GDPR compliant.

**Comment by renatobecker** [comment]
Actually, this is a feature request. When you delete a chat the data is removed from the database. What remains in the database is the visitor data, so when we have this feature done, the Livechat managers will be able to remove the visitor data as well as we'll provide more tools to facilitate this process.

**Comment by reetp** [comment]
It is retaining visitor data that makes it non GDPR compliant.....
All they have to do is contact you and say 'please remove all my personal data from the chat yesterday', we can't because it is in the database, and we end up with a large fine.
So it is a bug.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/feature-requests/issues/135
