### ISSUE TITLE
E-Mail-Adress not valid

### ISSUE THREAD

**Issue by ManicPumpkin** [RocketChat/Rocket.Chat#12784]
Hello,

we use Rocket.Chat within our company inside an offline network. Today I got a call of an user which forgot his password and I wanted to fix the problem, because he said the "Rest Password"-function does not work. After checking I figured out, that I get the notification "Can't send e-mail, all recipients were rejected", as I press the "Rest Password"-button.

I logged in as admin, to check the mail properties and I was able to send a new test mail to my mail-account via the administration "Settings > E-Mail > SMTP > Test SMTP-Properties", but as I tried the same for "Settings > Mailer" I see the notification message "Not valid E-Mail", but I used exactly the same E-Mail like in the previous try. I was searching for some settings to fix the problem, maybe it is our domain-name, but I couldn't find anything which is maybe wrong configured.

Does someone have some advice?

**Comment by piotrkochan** [comment]
Paste logs

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
