### ISSUE TITLE
What is the API to set/unset if user is available for livechat ?

### ISSUE THREAD

**Issue by rohitmyaim** [RocketChat/Rocket.Chat#12793]
I can see the websocket call going for this in Rocketchat panel.
"{"msg":"method","method":"livechat:changeLivechatStatus","params":[],"id":"17"}"

But I try to replicate the same by ddp client, it gives a meteor error that method do not exist.
It would be great if a REST Api is availble for the same

**Comment by renatobecker** [comment]
Hi @rohitmyaim.

Yes, we are developing our new Livechat client and we are replacing many ddp methods with Api REST calls, so it is a WIP.

**Comment by renatobecker** [comment]
@rohitmyaim Have you tried this? 
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/imports/server/rest/users.js#L43

**Comment by geekgonecrazy** [comment]
Closing since no reply

**Comment by serjk** [comment]
Hi @geekgonecrazy 

Do I understand correctly?  There is no way to change LiveChat user status via REST API. 
I've checked user & agent APIs. Unfortunately I didn't find any ways to do it except ddp client.

**Comment by serjk** [comment]
Hi @geekgonecrazy,

It's possible to set "available" status using this api by LiveChatAdmin.  
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/imports/server/rest/users.js#L68
Still agent without LiveChatAdmin role can't change own status. It's so weird.
