### ISSUE TITLE
Exception while invoking method 'setAvatarFromService'

### ISSUE THREAD

**Issue by lucassmacedo** [RocketChat/Rocket.Chat#12796]
Hello! When a try upload a avatar image
Dec  3 09:58:21 dr00al088 rocketchat[7664]: Exception while invoking method 'setAvatarFromService' TypeError: Cannot read property 'getFilter' of undefined
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at FileUploadClass.insert (/opt/Rocket.Chat/programs/server/packages/rocketchat_file-upload.js:712:31)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at EventEmitter.RocketChat.setUserAvatar (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:6805:13)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at MethodInvocation.setAvatarFromService (/opt/Rocket.Chat/programs/server/app/app.js:13289:23)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at MethodInvocation.methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:2696:36)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at Promise (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at new Promise (<anonymous>:null:null)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)
Dec  3 09:58:21 dr00al088 rocketchat[7664]:     at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85

**Comment by MarcosSpessatto** [comment]
Hello @lucassmacedo, can you please update your server to the latest version and try again? I think this problem has been solved. If the problem persists, please let us know.

**Comment by clarm060** [comment]
I seem to be getting this too and I'm on the latest version.

**Comment by MarcosSpessatto** [comment]
@clarm060 can you please provide more information about this? Like how we can reproduce this error, What storage are you using, etc?? Thanks

**Comment by clarm060** [comment]
I ended up re-building the app servers and it went away. I think I had something installed that caused it.

**Comment by MarcosSpessatto** [comment]
Can we close this?
