### ISSUE TITLE
Rocket.Chat powered svg image is needed

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1284]
Hi,

I suggest to make a little svg banner with "Rocket.Chat powered" to use in the control panel/Admin/Layout when the admin change the default layout.
##

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
