### ISSUE TITLE
Frontpage button "Mac App Store" links to iOS app store instead

### ISSUE THREAD

**Issue by CR0CKER** [RocketChat/Rocket.Chat#12853]
### Description:

The button "Mac App Store" in the "Desktop Apps" section at https://rocket.chat/install links to the iOS app store instead of opening the Mac App Store.

### Steps to reproduce:

1. Go to https://rocket.chat/install
2. Click "Mac App Store" graphic in the "Desktop Apps" section

### Expected behavior:

Clicking the graphic should open 
https://itunes.apple.com/us/app/rocket-chat/id1086818840

### Actual behavior:

Clicking the graphic opens 
https://itunes.apple.com/app/rocket-chat/id1148741252

**Comment by AlexVonB** [comment]
Hi!
This would fit better in the website repo:
https://github.com/RocketChat/rocketchat.github.io/blob/b270e1afd14b0e60569a6e72ae90f89d1b4ddbc4/install.html#L39
Could be an easy pull request.
Best

**Comment by tassoevan** [comment]
Just opened a PR: https://github.com/RocketChat/rocketchat.github.io/pull/609
Thanks a lot!
