### ISSUE TITLE
Unread indicator on drawer

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1285]
Say I just have unread messages in general.  When I click into it, it still shows the icon in the menu.  Which keeps making me think I have new unreads in other channels.
![image](https://cloud.githubusercontent.com/assets/51996/10807839/646bdeda-7db2-11e5-8dca-f69c0758a281.png)
##

**Comment by geekgonecrazy** [comment]
![image](https://cloud.githubusercontent.com/assets/51996/11018669/2b4fbcbc-859a-11e5-93fe-928b6a7af83c.png)

Another screenshot of what's happening.

**Comment by MartinSchoeler** [comment]
I can confirm this with the latest version

**Comment by tassoevan** [comment]
Not sure if I understand this issue. In this case, `#general` still have unread messages. What is the desired behavior?
