### ISSUE TITLE
When changing avatar, avatar reverts back to old avatar after reload

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#12852]
When changing avatars, sometimes there is a bug that if you reload the server the avatar reverts back to the old one. The new avatar will however show up in browser, and for other people. Even after resetting app data, reloading while ignoring cache, or reinstalling, the avatar doesn't show up in the client. Purging rocketchat entirely and removing the .config folder in the home folder finally makes the new avatar appear.  I am currently on 2.14.5 client version, but this has happened multiple times on previous versions as well. The Rocket.Chat Server is in 0.71.1 on docker, but has also happened on previous server versions. This has happened on multiple Linux distros.

**Comment by tassoevan** [comment]
This issue is related to the desktop client. Please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
