### ISSUE TITLE
unread bar count not resetting when mark as read

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1286]
When you click the mark as read button on the unread bar and then get another message.  The count is still a high number.

I think this may only happen if the unread point is some place in history not loaded in the DOM.

I opened the app had 111 unread messages.  I decided not to read them all clicked "MARK AS READ".  Then a new message came in the bar returns and now says 112 new messages.
##

**Comment by geekgonecrazy** [comment]
![image](https://cloud.githubusercontent.com/assets/51996/11018689/1ca82e96-859b-11e5-993e-4ea84df487ac.png)
Good visual of what's happening

**Comment by MartinSchoeler** [comment]
@geekgonecrazy is this still a issue?

**Comment by geekgonecrazy** [comment]
This particular one... I don't think so.  But there are other ones related to the unread bar.  I'll go ahead and close this one.
