### ISSUE TITLE
Connection to SMTP server ignores proxy environment variables (http_proxy, etc.)

### ISSUE THREAD

**Issue by rhtenhove** [RocketChat/Rocket.Chat#12863]
### Description:

Connection to SMTP server ignores proxy environment variables (http_proxy, etc.), and as such fails to connect.

### Steps to reproduce:

1. Have Rocket.Chat running behind a (corporate) proxy
2. Setup SMTP to some external server
3. Send test e-mail

### Expected behavior:

SMTP connection succeeding.

### Actual behavior:

SMTP connection getting refused.
```
Exception in defer callback: Error: connect ECONNREFUSED <smtp_server_ip>:587
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Ubuntu server 18.04.1
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 3.6.9

### Additional context

Connections to the SMTP server succeed from within the container using for example `curl`, ie. the proxy server is functioning correctly.

### Relevant logs:

No more logs other than the one mentioned at Actual behavior

**Comment by reetp** [comment]
@rocket-cat close

Closing as we have no further information

**Comment by rhtenhove** [comment]
Hi, it's been a while since I last tried to get Rocket.Chat working.

The issue persists, so let me provide further information.

## Issue
I am trying to use sendinblue as an SMTP relay, behind a corporate proxy.

## Current software
- Version of Rocket.Chat Server: 1.2.1
- Operating System: Ubuntu 18.04.02
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4 x64
- MongoDB Version: 4.0.10

## Error
When sending a test e-mail, the following error pops up in the logs
```
Exception in defer callback: { Error: connect ECONNREFUSED 185.107.232.248:587
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '185.107.232.248',
  port: 587,
  command: 'CONN' }
```

`curl` has no issues when ran from within the rocketchat container
```shell
$ curl smtp-relay.sendinblue.com:587
220 smtp-relay.sendinblue.com ESMTP Sendinblue SMTP 2.0
421 HTTP requests not allowed
```

Taking a look at what happens using `tcpdump` I can see the connection to the SMTP server doesnt use the proxy server:
_curl_
`16:14:07.970457 IP <server hostname>.59547 > <dns hostname?>: 1521+ A? <proxy hostname>. (30)`
_rocket chat mail test_
`16:16:04.908337 IP <server hostname>.50125 > <dns hostname?>: 31962+ A? smtp-relay.sendinblue.com. (43)`
