### ISSUE TITLE
Snap not on newest version

### ISSUE THREAD

**Issue by RogerSik** [RocketChat/Rocket.Chat#12869]
Snap  is not on the newest version (since 8 days) and other installation method like Dockers are.

**Comment by tassoevan** [comment]
@RogerSik I agree. Could you file an issue on [the documentation repository](https://github.com/RocketChat/docs/issues), please?

**Comment by geekgonecrazy** [comment]
This is not a bug.  Feel free to open a bug as mentioned above.  0.72.1 will be released in a few hours
