### ISSUE TITLE
0.72.1 GDPR / Policy retention : Message not removed.

### ISSUE THREAD

**Issue by stephane-** [RocketChat/Rocket.Chat#12862]
### Steps to reproduce:

1. Add policy retention for channels or private groups
2. Wait
3. Wait
4. Message are not removed

### Expected behavior:

Message shoud be removed.

### Actual behavior:

Policy retention was configured since 1 month ago, so should by good for crons. I can see this log in my log file: 
`[34mI20181205-09:15:21.027(1) rocketchat_logger rocketchat_logger.js:299 [34mSyncedCron ➔ info Scheduled "Prune old messages by retention policy" next run @Thu Dec 06 2018 00:00:00 GMT+0100 (CET)`

Actual policy retention is configured for 3 months, but I can see message from 1st january 2018.

![](http://dl.csacademie.fr/rc/rc-1.png)
![](http://dl.csacademie.fr/rc/rc-2.png)
![](http://dl.csacademie.fr/rc/rc-3.png)
![](http://dl.csacademie.fr/rc/rc-4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.1
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: disable
- NodeJS Version: 8.12.0
- MongoDB Version: no idea

**Comment by vynmera** [comment]
If you send a message in the channel and wait a day or so for the deletion to run, will that delete the message? If so, this is because of @ggazzo's changes that make the script only run if the channel contents have changed. A temporary workaround would be to send a message to every channel once a day.... sorry :/

**Comment by stephane-** [comment]
Hello,

Yes, we have all days new messages in this channel, but no deletion.
The RC instance run 24/24, and rebbot every weeks for maintenance. Maybe bug whis migrations ?

**Comment by stephane-** [comment]
Hello,

I try the manual prune message button for delete messages < 2018-02-01 ans that's work. 
But auto prune don't work. My RocketChat version is now 0.73.1.

I have the notice that messages older than 3 months will be deleted, but my olders messages is dated 04 february 2018

**Comment by stephane-** [comment]
Hello, 
Bug still active on 1.0.0-rc.0 version.

New screen : 
![image](https://user-images.githubusercontent.com/8134250/55432483-48b6be00-5593-11e9-9593-5b32389f8716.png)

In my logs, I alway have prune messages, but no deletions

```[34mI20190402-22:00:00.873(2) server.js:199 [34mSyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190402-22:00:00.888(2) server.js:199 [34mSyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190402-22:00:00.893(2) server.js:199 [34mSyncedCron ➔ info Finished "Generate download files for user data". 
[34mI20190402-22:00:00.909(2) server.js:199 [34mSyncedCron ➔ info Starting "Prune old messages by retention policy". 
[34mI20190402-22:00:00.921(2) server.js:199 [34mSyncedCron ➔ info Not running "Prune old messages by retention policy" again. 
[34mI20190402-22:00:00.955(2) server.js:199 [34mSyncedCron ➔ info Not running "Prune old messages by retention policy" again. 
[34mI20190402-22:00:01.143(2) server.js:199 [34mSyncedCron ➔ info Finished "Prune old messages by retention policy". ```

**Comment by emikolajczak** [comment]
Hi same problem for me. I have set global retention policy to 7 days, but it seems not working, old files are not deleted. My configuration on screen below.

![image](https://user-images.githubusercontent.com/50440047/60565987-e0c86d00-9d65-11e9-9d17-4e040af6da36.png)

My configuration is:

**Server Setup Information:**
Version of Rocket.Chat Server: 1.1.2
Operating System: Centos 7
Deployment Method: docker compose
Number of Running Instances: 9
DB Replicaset Oplog: yes
NodeJS Version: 8.11.4 - x64
MongoDB Version: 4.0

**Comment by stephane-** [comment]
Hello,

I still have the problem:

![image](https://user-images.githubusercontent.com/8134250/60828522-dddcda80-a1b2-11e9-89f9-57030ac68956.png)

RC informations : 
![image](https://user-images.githubusercontent.com/8134250/60828648-3ca25400-a1b3-11e9-8a9c-cbca4bc5b47e.png)

Operating System : Debian (on LXC)
Deployment Method : tar

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/feature-requests/issues/135
