### ISSUE TITLE
CAS - Improvement Suggestion

### ISSUE THREAD

**Issue by fabien4455** [RocketChat/Rocket.Chat#12873]
### Description:

CAS is a tool for authenticating users on an application. Actually on Rocket.Chat it's also used for creating accounts, but, there is a problem. We have users on Rocket.Chat. 

We want to use CAS for authentificate existing users, so, I have added to users the object CAS in service object like this :

 ![image](https://user-images.githubusercontent.com/22091839/49595794-1694a700-f979-11e8-8898-b834202d1061.png)

It's working great I can now login with CAS authentification.... Without doing that I had the error message : Account is already existing..

The big problem, we have CAS users that we don't want to access the chat, but with CAS activated they can create an account without our approval.  

The accounts are actually created by LDAP on a specific place... On CAS we have all users.

### Steps to reproduce:

Use CAS button to login it works with existing account... 
Use CAS button to register it also works... but I don't want that. 

### Expected behavior:

Rocket Chat tell : Creating account by CAS is currently disabled by administrator. You can only login in.

### Actual behavior:

RocketChat create an account with any CAS... 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Ubuntu 18.04
- Deployment Method: docker ( docker-compose.yml )
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.18...

### I suggest you and I would like that you add a setting like : Disable CAS Register in CAS settings. To only have CAS login. 

Thank's

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close

**Comment by fabien4455** [comment]
Where can I open a feature request ? ...

**Comment by fabien4455** [comment]
But that's also a bug.. not only a feature request. CAS is not used correctly in rocket chat...

**Comment by fabien4455** [comment]
Could you please add a ticket like on the other issues in GitHub and open again this thread ? : feature-request 

Thank's

**Comment by fabien4455** [comment]
Don't know why you're closing it because 

https://forums.rocket.chat/t/about-the-feature-requests-category/127 says that
