### ISSUE TITLE
Use Real Name does not affect reactions

### ISSUE THREAD

**Issue by smoehrle** [RocketChat/Rocket.Chat#12889]
### Description:

As stated in the title the setting "Use Real Name" does not affect reactions. A message object only contains a list of usernames for each emoji.

### Steps to reproduce:

Hover over a message reaction (the reaction must be from someone else than "You")
or
Query a message with a reaction via the api

### Expected behavior:

Return a list of users (id, username, name)

### Actual behavior:

Currently only a list of usernames is returned

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: debian 9.5
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by MarcosSpessatto** [comment]
- [x] Rest API https://github.com/RocketChat/Rocket.Chat/pull/13495
- [ ]  UI

**Comment by MarcosSpessatto** [comment]
@tassoevan is it currently possible to do this in the UI too?
