### ISSUE TITLE
Auto hide Channels and DMs older than X days

### ISSUE THREAD

**Issue by pfunk1978** [RocketChat/Rocket.Chat#12897]
As a standard user I want my list of channels and DMs to auto hide if they are older than X configurable days.

* Hidden conversations/rooms should still be searchable from global search
* Hidden rooms may be selected as excluded on global search when the query is made
* There should exist an easy way to manually hide/unhide conversations/rooms based on the X configuration

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
