### ISSUE TITLE
"__token __" instead "__token__" in rocketchat_i18n.js

### ISSUE THREAD

**Issue by mzqwe** [RocketChat/Rocket.Chat#12892]
### Description:
 
"__token __" and "__userId __" instead "\_\_token\_\_" and "\_\_userId\_\_"
in programs/server/packages/rocketchat_i18n.js

### Steps to reproduce:

1. Go to "http://rocketchat_host/account/tokens"
2. Fill "Personal access tokens to REST API"
3. Click on "Add"
4. You can see: ''Token: __token __ Your user Id: __userId __" instead of real token and userId.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v8.14.0
- MongoDB Version: 3.6.9

**Comment by leonboot** [comment]
I've just created a Docker based test setup for Rocket.Chat (official image) and configured it using the dutch locale. I'm experiencing this issue as well. Is this issue on the radar, yet?
