### ISSUE TITLE
Add BitBucket OAuth

### ISSUE THREAD

**Issue by derek-skinner** [RocketChat/Rocket.Chat#129]
https://github.com/npaton/meteor-bitbucket
##

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by philipwhiuk** [comment]
Probably depends on #250 as well.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
