### ISSUE TITLE
Live Chat: Hide live agent name and profile picture

### ISSUE THREAD

**Issue by CahidTopkaraoglu** [RocketChat/Rocket.Chat#12908]
Hello,

We are using Rocketchat for live support and we need to hide the name and profile image of live chat agents for our employee privacy. Is there a way to hide the name and profile image of live chat agents? If you don't currently have this feature, can you add it to your roadmap, please?

**Comment by exequos** [comment]
The question is what will be visible for customer then - maybe there can be feature / additional profile field to attach which label/name will be visible in which livechat department?

**Comment by CahidTopkaraoglu** [comment]
Exactly @exequos ,
Because of our customers can see the picture and name of our employees, it is not suitable for our KVKK (like GDPR) rules. It seems there is no feature that provides our request. We try to solve this issue in our locale. 
Thanks for taking care for this issue.

**Comment by renatobecker** [comment]
Hi @CahidTopkaraoglu.
Yes, we have plans to improve the customization of the Livechat widget, like creating multiples themes or something like this..
I hope we can start working on this feature ASAP.

Thanks.

**Comment by CahidTopkaraoglu** [comment]
Hi @renatobecker .
Thanks for paying attention on this issue. We handle this issue by manually changing the css classes for now. We would really appreciate if there will be such feature.

Thanks.

**Comment by reetp** [comment]
v1.1.1 and it isn't fixed in the new Livechat.

This isn't very good - I do not want my employees details exposed on the livechat widget.

There should at the **very least** be an option to disable display of Avatar and Email address.

**Comment by reetp** [comment]
> Thanks for paying attention on this issue. We handle this issue by manually changing the css classes for now. We would really appreciate if there will be such feature.

Can you please give an idea how you achieved this for others please?

Did you have to do a manual build of rocket, or can you override it in the html or with a local CSS file + !important ?

I can see the CSS has this and it could at least be hidden by changing the opacity eg

```
.header {

	&__content {

    .header__subtitle {
			opacity: 0.0 !important ; 
    }
  }
}
```

But I can't seem to get that to work.

**Comment by reetp** [comment]
Ok, having played about with I can see some of the confusion arises depending on whether you use the old Livechat widget or the new Livechat widget.

If you use the old version, settings are in livechat-manager/appearance

If you use the new v1.0.0 version (which is where this Issue arises) they are in admin/Livechat

With the NEW version you can disable the agent email address showing with "Show email field" 
You cannot disable or modify the display of the agents Avatar or the agents name.

So this bug is accurate.

None of this is helped by outdated and inaccurate documentation here:
https://rocket.chat/docs/administrator-guides/livechat/

**Comment by reetp** [comment]
Thinking about this there should be options to:

Enable/Disable personal Avatars  - perhaps allow a generic company avatar/logo ?

Username Options: Full Name, First Name only, Initials only, First name first Initial only.

**Comment by CahidTopkaraoglu** [comment]
> 
> 
> > Thanks for paying attention on this issue. We handle this issue by manually changing the css classes for now. We would really appreciate if there will be such feature.
> 
> Can you please give an idea how you achieved this for others please?
> 
> Did you have to do a manual build of rocket, or can you override it in the html or with a local CSS file + !important ?
> 
> I can see the CSS has this and it could at least be hidden by changing the opacity eg
> 
> ```
> .header {
> 
> 	&__content {
> 
>     .header__subtitle {
> 			opacity: 0.0 !important ; 
>     }
>   }
> }
> ```
> 
> But I can't seem to get that to work.

Hi sorry for delay,
We managed to hide some of informations with css manipulation.

**Comment by tsmgeek** [comment]
> Thinking about this there should be options to:
> 
> Enable/Disable personal Avatars - perhaps allow a generic company avatar/logo ?
> 
> Username Options: Full Name, First Name only, Initials only, First name first Initial only.

Or even add ability to give a specific name and or add a field to each user so we can define say an `Livechat Agent Display As` field as some companies replace names with an ID ie agent-5

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/feature-requests/issues/135

**Comment by jcatarino** [comment]
Would it be possible to have a company avatar/logo in live chat when hiding the agent's details?

Current implementation has just a black square which is not very pretty for customers.
