### ISSUE TITLE
Need more info [Screensharing / Audio-Video Chat Multiuser

### ISSUE THREAD

**Issue by fabiojansen** [RocketChat/Rocket.Chat#1290]
Hi, on Rocket page it says that i can "Screensharing" and "Multi User video/Audio chat", how can i enable/test it?

**Comment by emcguinness** [comment]
In the admin settings for rocket chat there is a webRTC section.this lets you turn this on and off for channels, private channels and private messages. By default only the two private options have it enabled, you can turn it on for the public ones if you chose. When enabled clicking on the users icon in the top right will have two buttons, the big one for video and the second for audio only.

![image](https://cloud.githubusercontent.com/assets/14922332/10819185/9b68063e-7e3e-11e5-9664-2a1e239c60e7.png)

The screen share I have not tried yet to really comment, hopefully some one else will, but you need [this extension](https://github.com/RocketChat/Rocket.Chat.ScreenShare.Extentions) from the repo and then in theory when you are in a video call a screen share button should appear.

**Comment by geekgonecrazy** [comment]
are you still having issues with getting video call to work?

**Comment by engelgabriel** [comment]
To be done as part of https://github.com/RocketChat/Rocket.Chat/issues/933
