### ISSUE TITLE
menu items

### ISSUE THREAD

**Issue by perchibald** [RocketChat/Rocket.Chat#12909]
Description:

Menu items are not displayed in the web interface.

no extended
![bug1](https://user-images.githubusercontent.com/847633/49787741-4bbe4200-fd49-11e8-9c1a-6f2e263681a5.png)

no video message (in the settings all included)
![bug2](https://user-images.githubusercontent.com/847633/49787752-52e55000-fd49-11e8-876e-2d1dc3db7176.png)

Server Setup Information:

- Version of Rocket.Chat Server:  0.72.1
- Operating System: Debian 9
- Deployment Method: snap

**Comment by marceloschmidt** [comment]
The condition for showing the Extended option is to have the "Store Last Message" option enabled in Administration -> General.

![image](https://user-images.githubusercontent.com/1986378/49819332-474f5480-fd5c-11e8-95c5-76bd32c6b391.png)

The conditions for video message to be displayed are: browser must support it, video recorder must be enabled in Administration -> Message, file uploads must be enabled and allowed extensions should be empty or include `video/webm` or `video/*` in Administration -> File Upload.

![image](https://user-images.githubusercontent.com/1986378/49818691-867ca600-fd5a-11e8-99ad-7d9ce41d108d.png)

![image](https://user-images.githubusercontent.com/1986378/49819425-89789600-fd5c-11e8-8ff3-531939690fb9.png)
