### ISSUE TITLE
Docker-container's "latest"-tag is set on point releases of older major-version.

### ISSUE THREAD

**Issue by tarator** [RocketChat/Rocket.Chat#12919]
### Description:

I'm using the official Rocket.Chat Docker-container `rocketchat/rocket.chat:latest` (with docker-compose). After the version `72.1` was released, a bugfix release of an older major version (`70.5`) was released. In the time (in this case only a few hours) between the release of version `70.5` and `72.2` the `latest`-Tag of the Docker container was set on version `70.5`. This caused problems on our server, because we installed `70.5` over our `72.1` instance.

In this case it was only a few hours, but it could be also possible, that there is no point-release of the latest major-version after a point-release of an older major-version, leaving the docker-container `latest`-Tag on an old major version.

### Steps to reproduce:

1. release a point release for the actual major-version (e.g. `72.2`)
1. release a point-release for an older major version (e.g. `70.6`) but not for the actual major-version (`72.x`)

### Expected behavior:

The `latest`-Tag of the docker-container should stay on version `72.5`

### Actual behavior:

The `latest`-Tag goes to an old version `70.6`

### Server Setup Information:

- Version of Rocket.Chat Server: `latest`
- Operating System: any
- Deployment Method: docker (docker-compose)

### Additional context
N/A

### Relevant logs:
N/A

**Comment by sampaiodiego** [comment]
sry for the trouble.. yes, for a few amount of time (around 50 minutes), with the `0.70.5` release, the `latest` Docker tag was wrongly pointing to it.

as soon the `0.72.2` was released the `latest` Docker tag was then update to `0.72.2` which is the correct version.

**Comment by tarator** [comment]
Yes, but what happens if it is necessary to release a bugfix-release for an older point-versio (e.g. `71.6`) but not for the latest point versions (`72.2`) because the latest version is not affected by that bug? The `latest` tag could stay for days or weeks on the wrong release.

**Comment by sampaiodiego** [comment]
this is was a mistake.. I'll make sure it will no happen again.

**Comment by tarator** [comment]
Ah ok! Thanks for the information!
Keep up the great work! :beer:
