### ISSUE TITLE
/invite user with @ in username does not work

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#12910]
### Description:

I want to invite an user to a group. We use emails as username (because of CROWD...) so I type:

```
/invite @some.user@domain.com
```

And the response is:

```
No user exists by the name of `@some.userdomain.com`.
```

So the _at_ symbol is truncated. Backslash \@ does not work either.

### Steps to reproduce:

1. Just as description

### Expected behavior:

User `some.user@domain.com` is invited to the room.

### Actual behavior:

RocketChat can't find this user.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: Ubuntu 18
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11
- MongoDB Version: 4

**Comment by marceloschmidt** [comment]
Sounds like an easy fix if someone has the time to implement and properly test, then create a Pull Request

This [line](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-slashcommands-invite/server/server.js#L18) should be replaced by `const usernames = params.split(/[\s,]/).map((username) => username.replace(/^@/, '')).filter((a) => a !== '');`
