### ISSUE TITLE
Upload got slow from Android Legacy Rocket.Chat client

### ISSUE THREAD

**Issue by ncedomir** [RocketChat/Rocket.Chat#12918]
Hello,

After an upgrade from 0.69.0 to 0.72.1 upload from cell phones became extremely slow. 
We are hosting it on same server, same resources, only thing that changed was the upgrade. Please let me know if this is duplicating for others or it's just for me and I need to share more info.
Thanks

**Comment by MartinSchoeler** [comment]
@ncedomir Unfortunately we do not support the legacy app anymore, if you need support with it, your best bet would be going to https://forums.rocket.chat/ and asking help from the community.

We strongly suggest to move to our more recent and updated [Native Apps](https://rocket.chat/install)  as seen that the legacy app will be removed from the app store in the near future.

Thanks!
