### ISSUE TITLE
ios app can't connect to server

### ISSUE THREAD

**Issue by vozerov** [RocketChat/Rocket.Chat#12912]
### Description:

ios mobile app can't connect to server. The message is "Oops, can't connect to server"

### Steps to reproduce:

Try to connect to rc.inmyroom.ru

### Server Setup Information:

Rocket chat is deployed using docker.
Server version is 0.72.2
Ubuntu 16.04
Nginx 1.15.7

### Additional context

Nginx is setup as reverse proxy with letsencrypt ssl certificate installed. Nginx config was taken from issues thread at github (also tried config from official docs with no luck).

### Relevant logs:

Websocket works fine as i see:

```

vozerov@mba:~ $ curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: rc.inmyroom.ru" -H "Origin: rc.inmyroom.ru" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://rc.inmyroom.ru/websocket
�{"server_id":"0"}
^C
vozerov@mba:~ $ curl -D - -s https://rc.inmyroom.ru/api/v1/info
HTTP/1.1 200 OK
Server: nginx/1.15.7
Date: Tue, 11 Dec 2018 13:21:37 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Instance-ID: axKHwC6ADyQzG8FH3
Access-Control-Allow-Origin: *
Cache-Control: no-store
Pragma: no-cache
Vary: Accept-Encoding

{"info":{"version":"0.72.2"},"success":true}
vozerov@mba:~ $

```

**Comment by tassoevan** [comment]
@RocketChat/ios

**Comment by marceloschmidt** [comment]
Issue moved to [RocketChat/Rocket.Chat.iOS #2418](https://github.com/RocketChat/Rocket.Chat.iOS/issues/2418) via [**ZenHub**](https://www.zenhub.com/)
