### ISSUE TITLE
Notifications setting are too ambigious

### ISSUE THREAD

**Issue by ifohancroft** [RocketChat/Rocket.Chat#12916]
The notification settings are too ambigious and lacking of features.
I am trying to do the following and it is either not possible or I don't know how to do it because the notification settings are very ambigious and confusing:

I want to disable notifications (the sound and tray icon change) for all messages in a channel that are not mention (both mentions by @nickname and @wildcard should work) and that are not a private message. In other words, I want to get notified only when I am mentioned in a channel or sent a private message.

Client version: 2.14.1 on Fedora 29 64bit

Server Version: 0.66.3

**Comment by reetp** [comment]
You are on a version 6 months out of date.
Rocket moves fast. Please test on the latest 0.72.4

**Comment by reetp** [comment]
@rocket-cat close

Closing as no further info
