### ISSUE TITLE
Tray Icon doesn't differ between mention and private message

### ISSUE THREAD

**Issue by ifohancroft** [RocketChat/Rocket.Chat#12915]
The tray icon used to show a number that indicates how many unread private messages you had and just change color when you are mentioned in a channel.

Now it no longer shows a number and it just changes color when you get a message. This makes it indestinguishable.

Client version: 2.14.1 on Fedora 29 64bit

Server Version: 0.66.3

**Comment by tassoevan** [comment]
This issue is related to the desktop client. Please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
