### ISSUE TITLE
LiveChat QA -

### ISSUE THREAD

**Issue by brunosquadros** [RocketChat/Rocket.Chat#12925]
### Improvements:

1. Why should we need a small buttons and inputs version? (If it must have, we need to review his paddings becouse is too tight):
[https://rocket.chat/Rocket.Chat.Livechat/?knob-description=user%20description&knob-text=Powered%20by%20Rocket.Chat&knob-loading=true&knob-value=&knob-placeholder=Insert%20your%20text%20here&knob-small=true&selectedKind=Components%7CButton&selectedStory=small&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs](url)

<img width="227" alt="screen shot 2018-12-12 at 08 32 30" src="https://user-images.githubusercontent.com/4096458/49863941-888d4600-fde8-11e8-922a-4cc01f219571.png">

2. The icons in the header aren't center aligned:
https://rocket.chat/Rocket.Chat.Livechat/?knob-group%20title=&knob-title=%40bertie.barton&knob-hasEmailField=true&knob-item%20text=A%20menu%20item&knob-text=Notification%20settings&knob-loading=true&knob-description=Description&knob-hasDepartmentField=true&knob-options=%5B%7B%22value%22%3A%221%22%2C%22label%22%3A%22Option%201%22%7D%2C%7B%22value%22%3A%222%22%2C%22label%22%3A%22Option%202%22%7D%2C%7B%22value%22%3A%223%22%2C%22label%22%3A%22Option%203%22%7D%5D&knob-multiple=1&knob-status=online&knob-departments=%5B%7B%22_id%22%3A1%2C%22name%22%3A%22Department%20%231%22%7D%2C%7B%22_id%22%3A2%2C%22name%22%3A%22Department%20%232%22%7D%2C%7B%22_id%22%3A3%2C%22name%22%3A%22Department%20%233%22%7D%5D&knob-color=%23175CC4&knob-hasNameField=true&knob-src=chime&knob-subtitle=Available&knob-emoji=true&knob-small=true&knob-message=Please%2C%20tell%20us%20some%20informations%20to%20start%20the%20chat&knob-error=&knob-button%20text%201=Yes&knob-buttonText=Ok&knob-button%20text%202=Cancel&knob-button%20text%203=No&knob-overlay=true&knob-value=&knob-uploads=true&knob-placeholder=Placeholder&knob-label=Label&knob-group%20%231%20title=&knob-group%20%232%20title=&selectedKind=Components%7CHeader&selectedStory=for%20user%20chat&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

<img width="166" alt="screen shot 2018-12-12 at 08 31 13" src="https://user-images.githubusercontent.com/4096458/49863864-5ed41f00-fde8-11e8-83cc-547e4afbe020.png">

3. Fix the padding-bottom for "Powered by Rocket.Chat": 
https://rocket.chat/Rocket.Chat.Livechat/?knob-group%20title=&knob-title=Need%20help%3F&knob-hasEmailField=true&knob-item%20text=A%20menu%20item&knob-text=guilherme.gazzo&knob-loading=true&knob-description=Description&knob-hasDepartmentField=true&knob-options=%5B%7B%22value%22%3A%221%22%2C%22label%22%3A%22Option%201%22%7D%2C%7B%22value%22%3A%222%22%2C%22label%22%3A%22Option%202%22%7D%2C%7B%22value%22%3A%223%22%2C%22label%22%3A%22Option%203%22%7D%5D&knob-multiple=1&knob-status=offline&knob-departments=%5B%7B%22_id%22%3A1%2C%22name%22%3A%22Department%20%231%22%7D%2C%7B%22_id%22%3A2%2C%22name%22%3A%22Department%20%232%22%7D%2C%7B%22_id%22%3A3%2C%22name%22%3A%22Department%20%233%22%7D%5D&knob-color=%23C1272D&knob-hasNameField=true&knob-src=chime&knob-subtitle=ccadsda%0A&knob-emoji=true&knob-small=true&knob-message=Please%2C%20tell%20us%20some%20informations%20to%20start%20the%20chat&knob-error=&knob-button%20text%201=Yes&knob-buttonText=Ok&knob-button%20text%202=Cancel&knob-button%20text%203=No&knob-overlay=true&knob-value=&knob-uploads=true&knob-placeholder=Placeholder&knob-label=Label&knob-group%20%231%20title=&knob-group%20%232%20title=&selectedKind=Screen%7CRegister&selectedStory=loading&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

<img width="389" alt="screen shot 2018-12-12 at 08 56 04" src="https://user-images.githubusercontent.com/4096458/49865336-d3f52380-fdeb-11e8-86ad-5b2aaece6d7f.png">

4. Rocket.chat logo should be in grayscale, only the hover version should be colorful:
https://rocket.chat/Rocket.Chat.Livechat/?knob-text=heyyy%20drop%20your%20files%20here%21&knob-loading=true&knob-description=user%20description&knob-small=true&knob-button%20text%201=Yes&knob-button%20text%202=Cancel&knob-button%20text%203=No&knob-value=&knob-placeholder=Insert%20your%20text%20here&selectedKind=Components%7CFooter&selectedStory=with%20Composer%20and%20options&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by renatobecker** [comment]
Hi @brunosquadros!

Do you mind creating this issue in our new Livechat repository?
https://github.com/RocketChat/Rocket.Chat.Livechat

Thanks.
