### ISSUE TITLE
Don't use channel names + fix private groups

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1292]
Seriously, it was a bad idea. The experience is clearly better when the channel doesn't use a hard name and is identified just by room's title (ex. hipchat, mattermost)

What's even worse is that the private groups are also using these hard ids. It's TERRIBLE :cry: .
My idea for private groups is to make them skype-like:

That is: you use these groups for a private meeting with team members.
They don't have an "id" just the title.

You cannot delete a team chat unless it contains zero messages. 
You can add and remove members. You are the only owner of your group.
Adding group moderator etc. isn't a priority.
You cannot join them with a command. 
You can send an /invite to private group. It would show as a special type of private message from the sender.
You can hide the chat and get back to it later.

(also possibly list group members using small letters, below the channel's name/title on the sidebar to improve experience)

**Comment by geekgonecrazy** [comment]
@ninja- Can you maybe separate your feedback from these two items?  I'm reading through and i'm not 100% sure which is a complaint and what's a suggestion.

**Comment by ninja-** [comment]
now that I think about it it's not that important
