### ISSUE TITLE
Add new icon to left side toolbar

### ISSUE THREAD

**Issue by shubuzhi** [RocketChat/Rocket.Chat#12933]
I want to add a new icon to the top left toolbar and after click on it, a new view page should appear like clicking directory. Any comments on which files I should modify would be really helpful. Thanks

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
