### ISSUE TITLE
Failed to restore Rocket.Chat server with Snaps

### ISSUE THREAD

**Issue by gueeme** [RocketChat/Rocket.Chat#12931]
### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.1
- Operating System: Ubuntu Server 18.04 LTS
- Deployment Method:  snap

### Additional context

Hello,
I am trying to migrate a Rocket.Chat installation to another server.
The two installations are in Ubuntu Servers created with Snaps.
I did the backup as recommended by your documentation but when I restore on the other server the error below is displayed.

### Relevant logs:

root@rocketchat:/var/snap/rocketchat-server/common# sudo snap run rocketchat-server.restoredb /var/snap/rocketchat-server/common/rocketchat_backup.tgz
*** ATTENTION ***
* Your current database WILL BE DROPPED prior to the restore!
* Do you want to continue?
1) Yes
2) No
#? 1
Extracting backup file...
ls: cannot access '/var/snap/rocketchat-server/common/restore/dump/parties': No such file or directory
[!] No restore data found within /var/snap/rocketchat-server/common/restore/dump/parties!
[*] Check /var/snap/rocketchat-server/common/restore/restore_20181212.1607.log for details.
[-] Restore aborted!
root@rocketchat:/var/snap/rocketchat-server/common#

##restore_20181212.1607.log

Extracting backup file with "tar --no-same-owner --overwrite -xzvf /var/snap/rocketchat-server/common/rocketchat_backup.tgz"
var/snap/rocketchat-server/1324/dump/
var/snap/rocketchat-server/1324/dump/parties/
var/snap/rocketchat-server/1324/dump/parties/meteor_oauth_pendingCredentials.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_apps_logs.bson
var/snap/rocketchat-server/1324/dump/parties/assets.chunks.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_integrations.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_userDataFiles.files.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_userDataFiles.chunks.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_office_hour.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_room.bson
var/snap/rocketchat-server/1324/dump/parties/meteor_oauth_pendingCredentials.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_integration_history.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_integrations.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_page_visited.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_integration_history.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_uploads.chunks.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_cron_history.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_subscription.bson
var/snap/rocketchat-server/1324/dump/parties/_raix_push_app_tokens.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat__trash.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_department.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_uploads.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_reports.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_avatars.chunks.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_inquiry.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_department_agents.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_import.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_roles.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_external_message.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_smarsh_history.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_import.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_avatars.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_room.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_credential_tokens.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_office_hour.bson
var/snap/rocketchat-server/1324/dump/parties/migrations.bson
var/snap/rocketchat-server/1324/dump/parties/migrations.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_permissions.bson
var/snap/rocketchat-server/1324/dump/parties/ufsTokens.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_oembed_cache.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_external_message.bson
var/snap/rocketchat-server/1324/dump/parties/assets.files.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_department.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_permissions.metadata.json
var/snap/rocketchat-server/1324/dump/parties/instances.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_message.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_department_agents.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_custom_sounds.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_user_data_files.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_apps_logs.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_smarsh_history.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_statistics.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_trigger.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_user_data_files.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_custom_emoji.metadata.json
var/snap/rocketchat-server/1324/dump/parties/ufsTokens.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_page_visited.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_apps_persistence.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_cron_history.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_message.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_userDataFiles.chunks.metadata.json
var/snap/rocketchat-server/1324/dump/parties/meteor_accounts_loginServiceConfiguration.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_settings.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat__trash.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_statistics.bson
var/snap/rocketchat-server/1324/dump/parties/users.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_uploads.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_avatars.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_uploads.chunks.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_uploads.files.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_visitor.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_visitor.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_export_operations.metadata.json
var/snap/rocketchat-server/1324/dump/parties/meteor_oauth_pendingRequestTokens.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_inquiry.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_reports.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_subscription.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_custom_field.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_roles.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_oembed_cache.bson
var/snap/rocketchat-server/1324/dump/parties/_raix_push_app_tokens.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_userDataFiles.files.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_custom_emoji.bson
var/snap/rocketchat-server/1324/dump/parties/_raix_push_notifications.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_custom_sounds.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_avatars.files.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_message_read_receipt.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_apps.metadata.json
var/snap/rocketchat-server/1324/dump/parties/meteor_oauth_pendingRequestTokens.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_credential_tokens.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_uploads.files.metadata.json
var/snap/rocketchat-server/1324/dump/parties/usersSessions.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_oauth_apps.bson
var/snap/rocketchat-server/1324/dump/parties/meteor_accounts_loginServiceConfiguration.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_oauth_apps.metadata.json
var/snap/rocketchat-server/1324/dump/parties/assets.chunks.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_avatars.chunks.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_trigger.metadata.json
var/snap/rocketchat-server/1324/dump/parties/assets.files.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_avatars.files.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_apps_persistence.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_settings.bson
var/snap/rocketchat-server/1324/dump/parties/usersSessions.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_apps.bson
var/snap/rocketchat-server/1324/dump/parties/users.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_export_operations.bson
var/snap/rocketchat-server/1324/dump/parties/_raix_push_notifications.bson
var/snap/rocketchat-server/1324/dump/parties/instances.metadata.json
var/snap/rocketchat-server/1324/dump/parties/rocketchat_message_read_receipt.bson
var/snap/rocketchat-server/1324/dump/parties/rocketchat_livechat_custom_field.bson

**Comment by ravirajcm** [comment]
Having the same problem. 
It says 

[!] Failed to extract backup files to /var/snap/rocketchat-server/common/restore!
[*] Check /var/snap/rocketchat-server/common/restore/extraction.log for details.
[-] Restore aborted!

I did check. my file backup.tgz is there and when I extract it, files exists.

Extraction.log says very less
tar (child): backup.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

double checked again. File do exist and sitting in right location

**Comment by calgromi** [comment]
I have the same error as in the original post. Any ideas to solve the problem?
