### ISSUE TITLE
Fix message caching

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1294]
afaik they were supposed to be cached in localStorage and not be downloaded every time you reload the page...?

**Comment by ninja-** [comment]
https://github.com/GroundMeteor/db we should use this

**Comment by gmsecrieru** [comment]
I would say that If it ain't broke don't fix it :) but feel free to submit an improvement.

**Comment by ninja-** [comment]
@gmsecrieru loading channels after you refresh the page is terribly slow because there's 0 local storage...

**Comment by gmsecrieru** [comment]
I think the loading experience might still seem slow with this unless we implement the logic to only keep a few messages in storage. Otherwise the (potentially) high amount of rendering during a full page refresh might even crash the browser.
