### ISSUE TITLE
Cannot choose myself to mail messages to.

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#12944]
### Description:

I just tried to mail a few messages to myself. Seems I cannot choose myself as a destimation. Other users are visible but not me. Adding my mail to "to additional emails" solves the problem for now.

### Steps to reproduce:

1. Click on "Mail Messages"
2. Try to add yourself under "To Users"
3. Not possible

### Expected behavior:

Add myself to the recipients under "To Users"

### Actual behavior:

Not possible.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.2
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6

**Comment by savish28** [comment]
@tassoevan  Can I work on this issue?

**Comment by aashlaysingla** [comment]
can i work on thiss?

**Comment by engelgabriel** [comment]
Yes @aashlaysingla please do.
