### ISSUE TITLE
Settings in Admin Panel not showing the changed value after reopening

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat#12950]
### Description:

Settings in Admin Panel are not showing the changed value after saving and reopening the Admin Panel without refreshing.
  
### Steps to reproduce:

1. Go to http://localhost:3000/admin/Layout (for example)
2. Turn the "Use Real Name" setting on (again for example)
3. Click on "save changes".
4. A green confirmation appears that the setting is saved.
5. Close the Admin Panel without refreshing.
6. Open the Admin Panel again (from the overflow menu in the left sidebar)
7. Check if the setting is still true.
8. Refresh.

### Expected behavior:

The setting should show the correct value.

### Actual behavior:

Setting shows the old value without refresh.

### Server Setup Information:

Latest commit e6d9375 .

**Comment by localguru** [comment]
Might be a duplicate of #12144

**Comment by ubarsaiyan** [comment]
@localguru yes it is. Sorry, didn't see that before. Closing the issue.
