### ISSUE TITLE
Resizing the window is SLOOOOW

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1295]
Doesn't matter that much on pc but breaks the experience so much on android web browser when you bring up the keyboard

**Comment by geekgonecrazy** [comment]
So this is only really an issue on mobile not on the desktop?

**Comment by ninja-** [comment]
yes

**Comment by marceloschmidt** [comment]
If anyone still experiences this, please open an issue on https://github.com/RocketChat/Rocket.Chat.Cordova or if specific to a native version https://github.com/RocketChat/Rocket.Chat.Android or https://github.com/RocketChat/Rocket.Chat.Android.Lily
