### ISSUE TITLE
No Account data in user data export

### ISSUE THREAD

**Issue by horvan** [RocketChat/Rocket.Chat#12966]
Hi folks,

I've exported my user data from a RC-instance and the archive doesn't contain some information about my account jet

What's my user Name
Whats my E-Mail?
Which Oauth Providers I am using?
What data have I saved to custom fields?

All that stuff is *not* in the GDPR-Data Export 

A additional.html would be really helpful to solve this issue,

The Archive contains 1 html-file per channel as well as the uploaded assets. 

The Data from account/profile  are missing in this export file.  This should be fexid asap

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/feature-requests/issues/135
