### ISSUE TITLE
Feature Request: Tracking changes (audit) to Rocket.Chat Settings 

### ISSUE THREAD

**Issue by Genzer** [RocketChat/Rocket.Chat#12967]
Hi guys

Our company is using Rocket.Chat internally and we would be very happy if Rocket.Chat could track changes made to Rocket.Chat's Settings.

We have several administrators and some of them may make changes to the Rocket.Chat's Settings without notifying the others. There were also times we would like to know who was the last person making the change and/or what was the previous value before it was changed and the list goes on.

It would be really helpful if we could have such a feature to track these changes. I think the feature could be similar to how it is implemented with Jenkins' [JobConfigHistory Plugin](https://wiki.jenkins.io/display/JENKINS/JobConfigHistory+Plugin).

Thanks a lot for your time!
Genzer

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
