### ISSUE TITLE
Hand Rocket.Chat avatars over to Jitsi

### ISSUE THREAD

**Issue by eidermar** [RocketChat/Rocket.Chat#12963]
This a suggestion or a feature request if you will. Only cosmetic but I think it would make a lot of sense actually.

People have their avatars in RC but when a Jitsi conference is started we are stuck with the random avatars that Jitsi serves us. It would be nice to have the RC avatars handed over to Jitsi. For guests the random avatars are fine.

**Comment by reetp** [comment]
Please note that feature requests should now be posted in the forums for discussion. Please open a thread there.

Thanks

**Comment by reetp** [comment]
@rocket-cat close
