### ISSUE TITLE
Avatar broken after changing username

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1296]

**Comment by gmsecrieru** [comment]
Can you elaborate this with screenshots or reproduction steps?

**Comment by ninja-** [comment]
1. have an avatar
2. change your username in profile settings
3. your avatar is gone
4. if you try to upload a new avatar that wouldn't work too (it would be ignored)

**Comment by jtdiii** [comment]
I'm using the linux client and I'm having the same issue.. I go in change my Avatar and save changes and the my initials still show as my  avatar.

**Comment by fduraibi** [comment]
Currently avatar images are based on username, so i believe changing the username doesn't change the avatar name on the database.

@ninja- Does the new username use latin characters (English) or Unicode?

**Comment by ninja-** [comment]
Just english, but I think it was fixed on demo server after official storage backend has changed so now I have my avatar

**Comment by fduraibi** [comment]
If you think it is solved then you might want to close this issue ;)

**Comment by yann-gael** [comment]
Hi,
I have the same problem in version 3.18.3. Should I create a new issue?
