### ISSUE TITLE
Allow animation to cancel by click

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1297]
Currently, the click is ignored when the flex is in the middle of animation.

**Comment by geekgonecrazy** [comment]
What animation are you referring to?

**Comment by ninja-** [comment]
I was referring to the animation that happens when you bring a panel on the right

**Comment by geekgonecrazy** [comment]
the sliding out of the panel animation? Or which?

**Comment by ninja-** [comment]
Exactly

**Comment by geekgonecrazy** [comment]
I use the panel all the time.. annoying is not really a descriptive enough word for us to do anything with.  Ignoring the click also makes sense, since the panel is moving.

If you would like, open a PR and improve this.  You've mentioned doing this on a couple of other items.

**Comment by marceloschmidt** [comment]
@RocketChat/core does anyone know what's being requested here, or is it ok to close this? I haven't seen any other issues regarding annoyingness of right-side flex.

**Comment by sampaiodiego** [comment]
yes. when you click to open/close a tab on the right panel, you **have** to wait the animation ends before you can close it.
this behavior is different from the panel with status and profile link on the top left corner.

as @ninja- I prefer the behavaior of the top left panel..

I think we need to define which one we want for Rocket.Chat and apply the same behavior on every element.

**Comment by marceloschmidt** [comment]
Cool, I hadn't noticed they were different, but now that I have, I have to say that I'd rather go with the animation on the left, in which clicking again will close even if it was still animating.
