### ISSUE TITLE
When changing avatar, avatar reverts back to old avatar after reload

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#12974]
When changing avatars, sometimes there is a bug that if you reload the server the avatar reverts back to the old one. The new avatar will however show up when I open rocketchat in browser (after changing avatar in client), and the new avatar shows up for other people. According to someone this problem happens for him in browser too, so it is not client exclusive. I was asked to reopen the issue here because of that. 

Even after resetting app data, reloading while ignoring cache, or reinstalling, the avatar doesn't show up in the client. Removing the .config folder in the home folder to reset the entire client finally makes the new avatar appear (reset app data isn't working for me anymore, it simply refreshes the server and window size). 

I am currently on 2.14.6 client version, but this has happened multiple times on previous versions as well (although seems to be happening every time I change avatars now, where as before it only happened occasionally). The Rocket.Chat Server is in 0.71.1 on docker, but has also happened on previous server versions. This has happened on multiple Linux distros.

**Comment by piotrkochan** [comment]
Probably Rocket.Chat.Electron issue but similar bug appears in the regular browser.

**Comment by tassoevan** [comment]
@piotrkochan It was posted there before: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1037

**Comment by SteveUNSW** [comment]
Any updates? when we change the avatar, after a reload it changes back to the old one.

We need to do a hard reload for the new one to appear (suggests a caching issue). 

Version 0.73.2

**Comment by daneallenh** [comment]
We have this issue too. It has gotten worse, now when **other** users change their avatars, we have to delete the cache folder in .config (on Linux) to see the new avatar. It is an issue with reloading the cache, I think. "Reload ignoring cache" does not work, and "reset app data" simply refreshes the client without doing anything else. The only way I have found to fix it is to delete the Cache folder in .config/Rocket.Chat

**Comment by juanito92** [comment]
My boss got really mad at me and threw a cup of coffee at the secretary today because of this issue, better fix it or we'll sue.

**Comment by Saurobot1** [comment]
We've been having this issue too. Any update on this?

**Comment by hifihedgehog** [comment]
The solution is clear your browser cache. The new image is there, but the browser doesn't know to clear/purge the cache of the old one.

**Comment by mmgoilf** [comment]
> The solution is clear your browser cache. The new image is there, but the browser doesn't know to clear/purge the cache of the old one.
> 
> By the way, RocketChat is easily the best instant messaging system I found. I tried Matrix Synapse and Mattermost and only RocketChat had all the features our Star Wars fan community needed for collaboration and just plain fun. Mattermost came close but some features are paywalled which makes it a non-contender in many respects.

I was talking about the client, not the browser. Also the issue has been fixed for a while now. The issue still exists on mobile, though (mobile has always been way buggier for me for everything).

**Comment by juanito92** [comment]
![ANGRY](http://images4.fanpop.com/image/photos/18500000/Angry-Piccolo-dragon-ball-z-18574143-200-148.jpg)

As the necklord drags his feet, the rocketchat devs chuckle and crackle over the fire talking about their favorite brazilian bongoli gorilla juice when GOKU from DragonBallZ crashes through the window exclaiming   WHOA BRO your rocket chat thingo mabubber is great! me and my DragonBall amigachos LOVE your chat. Except for one small problem: The mobile app doesn't go super saiyan mode!! Come on bros I thought brazilians loved goku...

**Comment by hifihedgehog** [comment]
Having lived in Brazil for two years, I can attest to the fandom and ferver among the populace for the DragonBall Japanese anime. Of course, thanks to Tectoy, a company that widely licenses and manufactures the SEGA Genesis and Master also in the country, a certain spiny, blue rodent enjoys a wide appeal there as well.

**Comment by hifihedgehog** [comment]
> > The solution is clear your browser cache. The new image is there, but the browser doesn't know to clear/purge the cache of the old one.
> > By the way, RocketChat is easily the best instant messaging system I found. I tried Matrix Synapse and Mattermost and only RocketChat had all the features our Star Wars fan community needed for collaboration and just plain fun. Mattermost came close but some features are paywalled which makes it a non-contender in many respects.
> 
> I was talking about the client, not the browser. But the issue has been fixed for a while now. The issue still exists on mobile, though (mobile has always been way buggier for me for everything).

It also exists on desktop browser for some time, just not mobile browsers. Regardless of the browser platform, you have to clear the cache for the new avatar to be shown.

**Comment by sampaiodiego** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/17925
