### ISSUE TITLE
When user doesn't have any preferences, users.getPreferences fails with "Cannot set property 'language' of undefined"

### ISSUE THREAD

**Issue by panta82** [RocketChat/Rocket.Chat#12976]
### Description:

When user doesn't have preferences, the REST API call https://rocket.chat/docs/developer-guides/rest-api/users/get-preferences/ fails with `{"success":false,"error":"Cannot set property 'language' of undefined"}`.

The problem is in this line: https://github.com/RocketChat/Rocket.Chat/blob/3dacacc8ca300b56a7b43ab1265c75450109ae51/packages/rocketchat-api/server/v1/users.js#L376

There needs to be a guard there.

**Comment by nish7898** [comment]
Hello,
Could you please attach an example citing when does this happen,
.Whenever an user is created, the preference is set by default as
"preferences":{"sidebarViewMode":"extended"}

Thank you
