### ISSUE TITLE
Deleting the user who owns a private channel

### ISSUE THREAD

**Issue by dmoldovan123** [RocketChat/Rocket.Chat#12978]
### Description:
I do not have permission to delete a user who owns a private channel.

### Actual behavior:

Is there any way to delete a user who owns a private channel by moving random owner to a user in that private channel?

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4
- Operating System: ubuntu 16.04
- Deployment Method: tar 
- Number of Running Instances: 10
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.3
- MongoDB Version: v3.4.10

**Comment by reetp** [comment]
Please always check on the latest version first as your issue may have been fixed. Current is 0.72.3

It's item no 2 on the list here:

https://rocket.chat/docs/contributing/reporting-issues

I also can't remember for sure but think this may have been reported already - can you please have a good search in the Issues, including closed ones please.

**Comment by reetp** [comment]
This may also be related

https://github.com/RocketChat/Rocket.Chat/issues/12870

**Comment by dmoldovan123** [comment]
> Please always check on the latest version first as your issue may have been fixed. Current is 0.72.3
> 
> It's item no 2 on the list here:
> 
> https://rocket.chat/docs/contributing/reporting-issues
> 
> I also can't remember for sure but think this may have been reported already - can you please have a good search in the Issues, including closed ones please.

Hello, I check on server with roccketchat version 0.72.3 same probleme.

**Comment by marceloschmidt** [comment]
We'll implement this by assigning owner to the oldest active user still in room. If there's no one else on the room, add the person that is deleting the user to the room and make him/her an owner.

**Comment by disaster123** [comment]
Is there already any solution for this? I even can't change the owner as the room is already archived in my case. How can i delete the user?

**Comment by Kayoku** [comment]
Hey, would be cool to resolve this issue ! :D
