### ISSUE TITLE
Allow to add reaction buttons without actually adding a reaction (for simple polls)

### ISSUE THREAD

**Issue by exhuma** [RocketChat/Rocket.Chat#12990]
We sometimes use rocket-chat for quick-polls and are using the reactions for this.

It would be really nice to be able to "prefill" the possible reactions (f. ex. a thumbs-up and thumbs-down). This way, the people responding to the poll don't need to look-up an appropriate emoji.

Example:

In the image below, there is currently only a thumbs-up emoji present. If someone wants to downvote the proposal, he/she needs to manually look-up an appropriate emoji. Having a pre-filled emoji (but with a current count of `0`) would simplify the action.

![image](https://user-images.githubusercontent.com/65717/50210409-521a7280-0376-11e9-8e41-0f99eac18e25.png)

**Comment by reetp** [comment]
Thank you for your comment.
Please note that all new feature requests should now be opened in the forums:
https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat close
