### ISSUE TITLE
4 back ticks + a space + 4 back ticks creates a random string

### ISSUE THREAD

**Issue by the4ndy** [RocketChat/Rocket.Chat#12996]
### Description:

In the rocket chat windows desktop app, if you type 4 back ticks a space and then 4 more back ticks and hit enter, it will generate a random string similar to this =!=hAdJBWXo6kaAnw688=!=

### Steps to reproduce:

1. In any chat, type "```` ````" (without quotes) and hit enter

### Expected behavior:

i would expect that the 3 back ticks would create a code block, escaped by the last 3 back ticks, and so a code block with ` ` would be left

### Actual behavior:

it generates a random string like this =!=hAdJBWXo6kaAnw688=!=
the =!= at the beginning and end are always there

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Linux 4.15.0-36-generic
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled (?) i think
- NodeJS Version: v8.11.3
- MongoDB Version: unsure (can probably find this if needed)

**Comment by Hudell** [comment]
The parser is picking the internal three backticks first and converting it into a token, then picking the outer backticks with the token inside, which is then not being parsed properly.

PR #12998 fixes the parsing to recognize it as two different code blocks, but that still isn't the expected output. 

![image](https://user-images.githubusercontent.com/2692247/50245854-bf4ff700-03ba-11e9-8300-078aea6ae586.png)

We will need to tweak the markdown regexes to identify the three outer backticks first, then treat the inner one as code.

**Comment by reetp** [comment]
There are a number of parse error Issues already kicking about that should be grouped together I think,

Worth a search - I can think of at least two I have seen.

**Comment by fliptrail** [comment]
This has been solved. Can be closed

**Comment by Hudell** [comment]
Indeed, the random string bug is fixed. The 4 back ticks are still not parsed properly (it generates two code blocks instead of showing a back tick inside a code block) but that can be moved to a new issue.
