### ISSUE TITLE
Add autocomplete for ASCII Emojis

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#13]
Support :) the same way we support :smiley:

**Comment by sampaiodiego** [comment]
this could be achieved by #32

**Comment by rodrigok** [comment]
@sampaiodiego autocomplete is different from message processing, do not you think?

**Comment by sampaiodiego** [comment]
true. My thought was only on show emoji when message has :) I don't think autocompletion for 'ascii emoji' necessary.. only display them as images.

**Comment by engelgabriel** [comment]
Lets try to turn this on
http://git.emojione.com/demos/ascii-smileys.html
