### ISSUE TITLE
embed tweet support

### ISSUE THREAD

**Issue by diomed** [RocketChat/Rocket.Chat#130]
Would you include embedding of tweets into Rocket Chat?

**Comment by rodrigok** [comment]
@diomed like pasting a url of a tweet?

**Comment by diomed** [comment]
yes, like that.

**Comment by rodrigok** [comment]
We are working to add support for external libs to access the message text and process information, after that we can add this idea :)

**Comment by sampaiodiego** [comment]
it's already there =)
