### ISSUE TITLE
Messages pruned on web browser do not delete in mobile

### ISSUE THREAD

**Issue by cryptify** [RocketChat/Rocket.Chat#13006]
As title says, when Admin prunes messages on web browser, android users retain messages locally. Any way to force prune for all users?

**Comment by reetp** [comment]
@rocket-cat close

This is an Android issue and is already covered by

https://github.com/RocketChat/Rocket.Chat.Android/issues/1617
https://github.com/RocketChat/Rocket.Chat.Android/issues/1754

Please follow up there
