### ISSUE TITLE
File upload with Nextcloud Webdav creating empty files

### ISSUE THREAD

**Issue by tiagoefreitas** [RocketChat/Rocket.Chat#13003]
I always get empty files (0 bytes) with random filenames created in nextcloud webdav when uploading...no error in rocket.chat it just doesn't upload properly.

**Comment by atsag** [comment]
I too experience the same problem, all files uploaded have a (final) size of 0 bytes.

**Comment by quiris11** [comment]
Any progress on this issue. I also see the same result trying to upload file on Nextcloud server - Random filename and 0 kB file size.

Log file excerpt:
I20200102-10:37:40.842(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.010675423850293861 
I20200102-10:37:40.845(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:41.062(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.08652735968307336 
I20200102-10:37:41.067(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:41.279(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.16043434067008092 
I20200102-10:37:41.285(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:41.472(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.2671885791730195 
I20200102-10:37:41.476(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:41.646(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.37527724565724485 
I20200102-10:37:41.649(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:41.814(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.5147464717150788 
I20200102-10:37:41.818(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:41.974(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.6638342650872461 
I20200102-10:37:41.978(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:42.160(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.7632263445274118 
I20200102-10:37:42.163(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:42.337(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=0.8867560629161942 
I20200102-10:37:42.342(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:42.507(0) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/EaKtGbqE7vG78LE39?token=d88B8bbbA8&progress=1 
I20200102-10:37:42.511(0) UploadProxy ➔ debug Correct instance 
I20200102-10:37:43.327(0) Meteor ➔ method canAccessRoom -> userId: XXXXXXXX, arguments: ["GENERAL","XXXXXXXX"] 
I20200102-10:37:43.343(0) Meteor ➔ method sendMessage -> userId: XXXXXXXX, arguments: [{"_id":"p4d9uJrKBQxZ86DaN","rid":"GENERAL","ts":"2020-01-02T10:37:43.338Z","file":{"_id":"EaKtGbqE7vG78LE39","name":"Stanislaw Ignacy Witkiewicz - Wybor dramatow_moh.epub.zip","type":"application/zip"},"groupable":false,"attachments":[{"title":"Stanislaw Ignacy Witkiewicz - Wybor dramatow_moh.epub.zip","type":"file","description":"","title_link":"/file-upload/EaKtGbqE7vG78LE39/Stanislaw%20Ignacy%20Witkiewicz%20-%20Wybor%20dramatow_moh.epub.zip","title_link_download":true}]}] 
I20200102-10:37:43.380(0) Integrations ➔ Outgoing WebHook.debug Execute Trigger: fileUploaded 
I20200102-10:37:43.384(0) Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: fileUploaded { event: 'fileUploaded',   user:     { _id: 'XXXXXXXX',      createdAt: 2019-12-31T05:24:18.417Z,      services:        { password: [Object],         email: [Object],         resume: [Object],         totp: [Object] },      emails: [ [Object] ],      type: 'user',      status: 'online',      active: true,      _updatedAt: 2020-01-02T10:20:01.965Z,      roles: [ 'admin' ],      name: 'XXXXXXXX',      lastLogin: 2020-01-02T09:55:18.734Z,      statusConnection: 'online',      utcOffset: 1,      username: 'XXXXXXXX',      avatarOrigin: 'gravatar',      settings: { profile: {}, preferences: [Object] },      language: 'en',      statusText: '',      requirePasswordChange: false },   room:     { _id: 'GENERAL',      ts: 2019-10-16T19:06:29.957Z,      t: 'c',      name: 'general',      usernames: [],      msgs: 114,      usersCount: 5,      default: true,      _updatedAt: 2020-01-02T10:36:16.487Z,      lastMessage:        { _id: 'iHov2B2cwqCW98jq4',         rid: 'GENERAL',         msg: 'ten z3SJ7BF4DFnebi7oC jest częścią URL do pliku.',         ts: 2020-01-02T10:36:16.446Z,         u: [Object],         _updatedAt: 2020-01-02T10:36:16.472Z,         mentions: [],         channels: [] },      lm: 2020-01-02T10:36:16.446Z,      username: 'XXXXXXXX' },   message:     { _id: 'p4d9uJrKBQxZ86DaN',      rid: 'GENERAL',      ts: 2020-01-02T10:37:43.338Z,      msg: '',      file:        { _id: 'EaKtGbqE7vG78LE39',         name: 'Stanislaw Ignacy Witkiewicz - Wybor dramatow_moh.epub.zip',         type: 'application/zip' },      groupable: false,      attachments: [ [Object] ],      u:        { _id: 'XXXXXXXX',         username: 'XXXXXXXX',         name: 'XXXXXXXX' },      tmid: undefined,      _updatedAt: 2020-01-02T10:37:43.373Z,      editedBy: undefined,      editedAt: undefined,      emoji: undefined,      avatar: undefined,      alias: undefined,      customFields: undefined,      reactions: undefined,      parseUrls: undefined,      token: undefined,      mentions: [],      channels: [] } } 
I20200102-10:37:43.389(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: GENERAL

**Comment by jinlaohu** [comment]
I've too.

**Comment by iMaciaveller** [comment]
I too (

**Comment by drumdum** [comment]
I have the exact same problem

**Comment by PopertoAB** [comment]
Hi, I have the same problem too, does anybody find the answer to this problem?

**Comment by prenner0** [comment]
Same problem here with Rocket.Chat 3.7.1.

**Comment by dotty37** [comment]
Just to refresh this. Im having the same issue, empty files when using WebDav as file storage, Rocket.Chat 5.1.1 and Nextcloud 24.
My webdav works just fine, I use it for other things.

**Comment by dudanogueira** [comment]
@dotty37 Can you try in our development version? This should be included there already.

You can test it using the docker tag **development**, instead of **latest** or a specific version.

if you want to help us as a beta tester, please, consider joining our [Beta Testers Channel](https://open.rocket.chat/channel/beta-testers)

Thanks!
