### ISSUE TITLE
Sending URLS that contain a fragment identifier matching a channel name (#<roomname>) breaks the URL paste

### ISSUE THREAD

**Issue by cameracker** [RocketChat/Rocket.Chat#13007]
### Description:

If a user sends a URL that has a fragment identifier that happens to match the name of an existing channel, the URL paste will break and apply a malformed message to the chat when sent.

### Steps to reproduce:

1. Paste a URL that contains a fragment identifier matching an existing rocketchat channel 
    Example: http://link.to.thing?#general
2. Send the message
3. Observe that the message is not correctly formatted as a URL
   
![image](https://user-images.githubusercontent.com/14242948/50304366-9d02bb80-0444-11e9-9fed-38dbbaf788e4.png)

### Expected behavior:

URLs containing fragment identifiers that match a channel name are converted to URLS, and rocket chat does not attempt to associate this to a channel name reference at all.

### Actual behavior:

![image](https://user-images.githubusercontent.com/14242948/50304366-9d02bb80-0444-11e9-9fed-38dbbaf788e4.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.59.3
OS: ubuntu 16.04
Deployment method: .tgz on host
Number of running instances: 1 prod, 1 dev
DB Replicaset Oplog: none
NodeJS Version: 4.5.0
MongoDB Version: 3.2.17

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
