### ISSUE TITLE
ts fied automaticaly added when author_name is used in webhook attachments

### ISSUE THREAD

**Issue by tsr-caubry** [RocketChat/Rocket.Chat#13001]
### Description:

When using the author_name field in attachments posted through webhook the ts field is automatically added with a wrong value (seems unixtime 1).

### Steps to reproduce:

1. Creation a webhook (without or with a script enabled)
2. Send a message with attachment that contain the author_name field through the webhook
3. Verifying the result on the channel where the webhook post the message

### Expected behavior:

author_name displayed without any extra date, wrong or not.

### Actual behavior:

A wrong date is added at right of the author_name field

### Server Setup Information:

- Version of Rocket.Chat Server:  0.73.2
- Operating System: CentOS 7.6
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: disabled
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.9

### Additional context

Example of problematic message : 
```
{
  "text": "Example message",
  "attachments": [
    {
      "author_name": "Me",
      "title": "Rocket.Chat",
      "title_link": "https://rocket.chat",
      "text": "Rocket.Chat, the best open source chat",
      "image_url": "/images/integration-attachment-example.png",
      "color": "#764FA5"
    }
  ]
}
```

### Relevant logs:

![screenshot from 2018-12-20 09-30-46](https://user-images.githubusercontent.com/44467383/50273262-7ccdff00-043a-11e9-98b9-d7ac060169fc.png)

**Comment by petersonbasso** [comment]
+1

**Comment by frdmn** [comment]
#13428 will fix this which will probably included in 0.75.0

**Comment by MarcosSpessatto** [comment]
@tsr-caubry can we close this?

**Comment by tsr-caubry** [comment]
Yes, everything seems fine right now, thank you.
