### ISSUE TITLE
FR: give the option to paste unformatted instead of sending a picture

### ISSUE THREAD

**Issue by nodje** [RocketChat/Rocket.Chat#13002]
When users try to paste some complex/not supported formatted text, they are shown the option of sending a "picture" of their copied document.  (As far as I can see this happens especially with MS Word documents)

This is nice but isn't always the most desirable solution.
Having the possibility to paste the copied content as "text" even unformatted would be an improvement I believe.

**Comment by tassoevan** [comment]
Is the issue with MS Office docs happening for Windows users too? I've seen reports only for MacOS.

**Comment by marceloschmidt** [comment]
If you hold Shift when pasting, it will paste as text.

**Comment by mmickelson** [comment]
> If you hold Shift when pasting, it will paste as text.

I found this works when pasting into the web client (paste using cmd+shift+v) but not the MacOS app.

**Comment by tassoevan** [comment]
May I ask you to open an issue in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron)?

**Comment by mmickelson** [comment]
> May I ask you to open an issue in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron)?

It looks like a similar enough issue exists: https://github.com/RocketChat/Rocket.Chat/issues/3551 so I won't create a new one.
