### ISSUE TITLE
Live chat failing on Chrome 68.0.3

### ISSUE THREAD

**Issue by esolitos** [RocketChat/Rocket.Chat#13018]
### Description:

Deploying LiveChat doesn't seems to be working properly while on Chrome (Tested version: 68.0.3440.106), throws a couple of exceptions in the console (see details below) and doesn't show anything.

Seems to be working fine on Firefox (Tested: 62.0.3) and Safari (Tested: 12.0 / 14606.1.36.1.9)

### Steps to reproduce:

1. Enable and do basic configuration of the "Live Chat" feature
2. Install the script on an external site
3. Load the site/page where the livechat is ionstalled

### Expected behavior:

Live Chat is loading and properly working. :)

### Actual behavior:

Live Chat doesn't work throwing an error in the console (see screenshot).
![livechat_test___dropboxintegration](https://user-images.githubusercontent.com/401819/50341430-05be6680-051f-11e9-9824-11385d87dc39.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Server: Linux, Client: Chrome 68.0.3440.106 on macOS
- Deployment Method: docker on K8s via Wodby.
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 3.2

### Relevant logs:

```
You are running a browser with no localStorage or userData support. Logging in from one tab will not cause another tab to be logged in.
livechat.js?_dc=null:153 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at triggers.js (https://***.com/livechat/livechat.js?_dc=null:153:79707)
    at g (https://***.com/livechat/livechat.js?_dc=null:3:1109)
    at d.n [as require] (https://***.com/livechat/livechat.js?_dc=null:3:3638)
    at e (https://***.com/livechat/livechat.js?_dc=null:3:730)
    at https://***.com/livechat/livechat.js?_dc=null:153:96701
triggers.js @ livechat.js?_dc=null:153
g @ livechat.js?_dc=null:3
n @ livechat.js?_dc=null:3
e @ livechat.js?_dc=null:3
(anonymous) @ livechat.js?_dc=null:153
livechat.js?_dc=null:105 There is no route for the path: /livechat
f._notfoundRoute @ livechat.js?_dc=null:105
(anonymous) @ livechat.js?_dc=null:105
(anonymous) @ livechat.js?_dc=null:105
o @ livechat.js?_dc=null:105
h.dispatch @ livechat.js?_dc=null:105
h.replace @ livechat.js?_dc=null:105
e._page.(anonymous function) @ livechat.js?_dc=null:105
h.start @ livechat.js?_dc=null:105
h @ livechat.js?_dc=null:105
f.initialize @ livechat.js?_dc=null:105
(anonymous) @ livechat.js?_dc=null:105
a @ livechat.js?_dc=null:1
u @ livechat.js?_dc=null:1
livechat.js?_dc=null:127 Uncaught TypeError: Cannot destructure property `ServiceConfiguration` of 'undefined' or 'null'.
    at e.startup (livechat.js?_dc=null:127)
    at a (livechat.js?_dc=null:1)
    at HTMLDocument.u (livechat.js?_dc=null:1)
e.startup @ livechat.js?_dc=null:127
a @ livechat.js?_dc=null:1
u @ livechat.js?_dc=null:1
content_script_bundle.js:13 Uncaught (in promise) ReferenceError: currentURL is not defined
    at then.catch.e (content_script_bundle.js:13)
then.catch.e @ content_script_bundle.js:13
Promise.catch (async)
(anonymous) @ content_script_bundle.js:13
(anonymous) @ content_script_bundle.js:13
f @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
f @ content_script_bundle.js:1
a @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
1111 @ content_script_bundle.js:13
n @ content_script_bundle.js:1
1110 @ content_script_bundle.js:1
n @ content_script_bundle.js:1
1110 @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
content_script_bundle.js:13 Uncaught (in promise) ReferenceError: currentURL is not defined
    at then.catch.e (content_script_bundle.js:13)
then.catch.e @ content_script_bundle.js:13
Promise.catch (async)
(anonymous) @ content_script_bundle.js:13
(anonymous) @ content_script_bundle.js:13
f @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
f @ content_script_bundle.js:1
a @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
1111 @ content_script_bundle.js:13
n @ content_script_bundle.js:1
1110 @ content_script_bundle.js:1
n @ content_script_bundle.js:1
1110 @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
```

**Comment by renatobecker** [comment]
Hi @esolitos.
The error you reported is not related to Livechat itself, please take a look at here:
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

Feel free to leave a feedback here after reading the instruction on the link I just posted above.
Thanks.

**Comment by esolitos** [comment]
Hi @renatobecker, thanks for the quick reply. :) 
Shouldn't LiveChat work even without localStorage? I understand that this depends on the "block 3rd party cookies and data", but I regularly use several other "live chat" services and they all work with this setting, so it should be possible to have this working as well with reduced functionality perhaps.
This behaviour is also suggested also by the message in console:
> You are running a browser with no localStorage or userData support. Logging in from one tab will not cause another tab to be logged in.
