### ISSUE TITLE
Mobile app for video chat

### ISSUE THREAD

**Issue by jseong309** [RocketChat/Rocket.Chat#13023]
The mobile app never gets the "join video chat" message.
I would have to open my web browser and login to rocket.chat and click on the link to jitsi. 
It's essentially just a link to jitsi. Can this be added to the mobile app? Without having to do this extra step that's just a link to another app?

**Comment by lorek123** [comment]
Seems that you need to wait a moment: https://forums.rocket.chat/t/2019-q1-mobile-team/2695

**Comment by reetp** [comment]
@rocket-cat close

There are a number of open bugs on video and audio messaging already and you can see the road map.
