### ISSUE TITLE
Livechat CRM integration triggers and webhooks not working on chat close and visitors message event

### ISSUE THREAD

**Issue by khegiw** [RocketChat/Rocket.Chat#13025]
### Description:

Livechat Send Request on Chat Close and Send Request on Visitor Messages event not send POST request to CRM webhooks, but working for Send Request on Offline Messages event.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Ubuntu 16.04.4 LTS
- Deployment Method: snap

**Comment by Pratyush1197** [comment]
I want to work on this issue. Can you please specify the exact problem and how it is expected to work.

**Comment by renatobecker** [comment]
Hi @khegiw!

What do you thing about updating your server to the newest release(0.75)?
It would be great to ensure that the issue you described is still happening, then we can take a look on it deeply.

Thanks.

**Comment by rsmartins78** [comment]
I'm running in docker with version 0.74.3 and I have same problem.
I configure an URL in Livechat Webhook, test it mannualy with test button, mark options that trigger webhook when agent send messages, but the webhook did not run.

No errors in log.

You can use this site for tests: https://webhook.site

**Comment by rsmartins78** [comment]
I think I found the problem:
When the secret token field has no value, the webhooks not works. I've put any random value in secret token field and webhook started to works.

Maybe problem is here? https://github.com/RocketChat/Rocket.Chat/blob/ed092fbe490c21d64c071772ce1da66515837353/app/livechat/server/hooks/sendToCRM.js#L11

@Pratyush1197

**Comment by rsmartins78** [comment]
@knrt10 Can you help in this issue?

**Comment by knrt10** [comment]
Will look into it @rsmartins78
