### ISSUE TITLE
Edge does not refresh/update page in v0.72.3

### ISSUE THREAD

**Issue by marz71** [RocketChat/Rocket.Chat#13024]
Rocket.Chat Version: 0.72.3
Ubuntu 18.04: 4.15.0-32-generic

It's possible to log inn with Edge and everything seems OK. But it's not possible to see new messages. The only way to see new messages is to hit F5.

Easy to reproduce, bug appears every time:

1) Start Chrome, enter chat, enter any room (also private group or direct messages)
2) Start Edge and enter the same room.
3) Write message in Chrome-window. You would expect to see this message in Edge-window. But no messages appears.

This bug must be quite new. Edge was working fine some weeks ago.

**Comment by barak-haviv** [comment]
I check also the new version 0.73.1 and edge is not working there also

**Comment by ggazzo** [comment]
lets keep the conversation here #13110
