### ISSUE TITLE
Push notifications: how works Rocket.chat?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1303]
Hi,
My cordova proj with rocket.chat can now sent the userID to the GCM server a my php server, so in theory rocket.chat can do it too.

I need to know the steps how to cause to send a notification from rocket.chat to a mobile user that is not connected in this moment.

If you need to know how to setup  a simple gcm service based in php and mysql, I can send you the code and the cordova environment.... so I hope that you can see how it work and replicate in the chat server package with meteor and mongodb.

**Comment by maxlinux2000** [comment]
here my log:

cat rocket.log | grep Push
I20151029-20:56:40.449(1)? Push.Configure { apn: { passphrase: '', keyData: '', certData: '' },
I20151029-20:56:40.455(1)? Push: APN configured
W20151029-20:56:40.455(1)? (STDERR) ERROR: Push server could not find certData
W20151029-20:56:40.456(1)? (STDERR) ERROR: Push server could not find keyData
I20151029-21:02:06.354(1)? Push: Send message "@maxlinux2000" via query { userId: '5n2iGLgX8o4Jz4QAN' }
I20151029-21:02:06.356(1)? Push: Sent message "@maxlinux2000" to 0 ios apps 0 android apps
I20151029-21:02:06.365(1)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
I20151029-23:58:56.396(1)? Push: Send message "@barby" via query { userId: 'PmfD76Rmmp3b92vJ5' }
I20151029-23:58:56.398(1)? Push: Sent message "@barby" to 0 ios apps 0 android apps
I20151029-23:58:56.400(1)? Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...
I20151030-20:36:26.071(1)? Push.Configure { apn: { passphrase: '', keyData: '', certData: '' },
I20151030-20:36:26.076(1)? Push: APN configured
W20151030-20:36:26.077(1)? (STDERR) ERROR: Push server could not find certData
W20151030-20:36:26.078(1)? (STDERR) ERROR: Push server could not find keyData
I20151030-20:37:23.148(1)? [method] saveSetting Push_debug true
I20151030-20:37:23.251(1)? [method] saveSetting Push_enable true
I20151030-20:37:23.354(1)? [method] saveSetting Push_production false


I have only configures the GCM part, so I assume that the error in the apn is expected and normal.

The question is: Why this message?

Push, GUIDE: The "Push.appCollection" is empty - No clients have registred on the server yet...

my cordova app, can send the idPhone (tested the recordo with my php server) so in theory rocket.chat could register too.

**Comment by geekgonecrazy** [comment]
you already have an issue open for this.. #1096
