### ISSUE TITLE
Incomming webhook from Jira service

### ISSUE THREAD

**Issue by sidneiweber** [RocketChat/Rocket.Chat#13048]
I have integration with Jira to receive messages, and today it has simply stopped working without anyone making any changes. Anyone else with this problem?

- Version of Rocket.Chat Server: 0.70.4
- Operating System: Linux x64
- Deployment Method: Docker
- Number of Running Instances: 1

Instructions used for integration
https://rocket.chat/docs/administrator-guides/integrations/jira/

### Logs
single message in the log is:
[34mI20181228-17:22:41.608(0) Checking: checkPostMessageSent

**Comment by wreiske** [comment]
Have you tried the new Jira Cloud / Jira Server apps available in the [marketplace](https://rocket.chat/marketplace)?

**Comment by sidneiweber** [comment]
It is not compatible with the version I am using, it was the error that generated me:
`Error: Deployment error: Invalid Version: ^ 1.3.0
`
I tried to test the newer version on another host but I did not understand how to configure these new apps.

**Comment by wreiske** [comment]
You may need to upgrade your rocket.chat instance to support the newer apps. The 1.30 I think is related to the [apps-engine](https://github.com/RocketChat/Rocket.Chat.Apps-engine). Your version of rocket.chat doesn't have the newer apps engine in it.

Try upgrading your Rocket.Chat instance (make a backup first) and see if the Jira app works for you.

**Comment by sidneiweber** [comment]
How is this new app set up? No option appears in the menus...

**Comment by wreiske** [comment]
Go into any channel and start typing /jira-server or /jira-cloud. If you have issues with it, post them to 

https://github.com/RocketChat/Apps.Atlassian.Jira.Server 
or 
https://github.com/RocketChat/Apps.Atlassian.Jira
