### ISSUE TITLE
NTPD loop after update to 0.73; "Operation not permitted"

### ISSUE THREAD

**Issue by ParkHost** [RocketChat/Rocket.Chat#13047]
### Description:

NTPD loop after update to 0.73; "Operation not permitted"

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73
- Operating System: Debian
- Deployment Method: LXD
- Number of Running Instances: 1

Dec 28 15:59:53   ntpd[217]: adj_systime: Operation not permitted
Dec 28 15:59:54   ntpd[217]: adj_systime: Operation not permitted
Dec 28 15:59:55   ntpd[217]: adj_systime: Operation not permitted
Dec 28 15:59:56   ntpd[217]: adj_systime: Operation not permitted
Dec 28 15:59:57   ntpd[217]: adj_systime: Operation not permitted
Dec 28 15:59:58   ntpd[217]: adj_systime: Operation not permitted
Dec 28 15:59:59   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:00   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:01   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:02   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:03   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:04   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:05   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:06   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:07   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:08   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:09   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:10   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:11   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:12   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:13   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:14   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:15   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:16   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:17   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:18   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:19   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:20   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:21   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:22   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:23   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:24   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:25   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:26   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:27   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:28   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:29   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:30   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:31   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:32   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:33   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:34   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:35   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:36   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:37   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:38   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:39   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:40   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:41   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:42   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:43   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:44   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:45   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:46   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:47   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:48   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:49   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:50   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:51   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:52   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:53   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:54   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:55   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:56   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:57   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:58   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:00:59   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:01:00   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:01:01   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:01:02   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:01:03   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:01:04   ntpd[217]: adj_systime: Operation not permitted
Dec 28 16:01:04   ntpd[217]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
**Dec 28 16:01:04**   ntpd[217]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
**Dec 28 16:07:49**   ntpd[217]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Dec 28 16:08:50   ntpd[217]: 5.9.59.78 local addr 192.168.69.69  -> <null>
Dec 28 16:09:06   ntpd[217]: 141.30.228.4 local addr 192.168.69.69  -> <null>
Dec 28 16:10:09   ntpd[217]: 104.207.131.54 local addr 192.168.69.69  -> <null>
Dec 28 16:10:12   ntpd[217]: 193.141.27.6 local addr 192.168.69.69  -> <null>
Dec 28 16:12:11   ntpd[217]: 173.249.38.50 local addr 192.168.69.69  -> <null>
Dec 28 16:12:14   ntpd[217]: 136.243.177.133 local addr 192.168.69.69  -> <null>
Dec 28 16:12:15   ntpd[217]: local_clock: ntp_loopfilter.c line 818: ntp_adjtime: Operation not permitted
Dec 28 16:12:19   ntpd[217]: 85.236.36.4 local addr 192.168.69.69  -> <null>
Dec 28 16:12:23   ntpd[217]:  local addr  -> <null>
Dec 28 16:12:23   ntpd[217]: 213.209.109.45 local addr 192.168.69.69  -> <null>
Dec 28 16:12:23   ntpd[217]: 195.50.171.101 local addr 192.168.69.69  -> <null>
Dec 28 16:12:26   ntpd[217]: 176.221.42.125 local addr 192.168.69.69  -> <null>
Dec 28 16:13:41   systemd[1]: systemd-tmpfiles-clean.service: Failed to reset devices.list: Operation not permitted
Dec 28 16:13:41   systemd[1]: systemd-tmpfiles-clean.service: Failed to set invocation ID on control group /system.slice/systemd-tmpfiles-clean.service, ignoring: Operation not permitted
Dec 28 16:13:41   systemd[1]: Starting Cleanup of Temporary Directories...
Dec 28 16:13:41   systemd[1]: Started Cleanup of Temporary Directories.

**Comment by MrHpower** [comment]
btw reversed back to 0.72.1, everything is up and running again.

**Comment by MrHpower** [comment]
Thanks, 0.73.1 solved my issue! this threat may be closed.

**Comment by frdmn** [comment]
This can be closed.
