### ISSUE TITLE
ENOTFOUND marketplace.rocket.chat

### ISSUE THREAD

**Issue by dctheee** [RocketChat/Rocket.Chat#13046]
![capture](https://user-images.githubusercontent.com/46223006/50517694-128b0f00-0a77-11e9-9294-713329450e63.JPG)

Description:

Hey all! Relatively new to Rocketchat. Whenever I attempt to install a new app, either via the Marketplace (by clicking on the "+"), I get the following error: 

"getaddrinfo ENOTFOUND marketplace.rocket.chat marketplace.rocket.chat:443"

It shows up as a big red box in the upper right-hand corner.

Additionally, if I attempt to add a new app, either through URL or by uploading a zip file, it doesn't appear to do anything; I click "Install" and it just sits there. No error messages or anything.

I'm assuming this has something to do with permissions on my server, but I'm not sure if that's entirely the case. Anyone have an idea? This was installed via SNAP; only thing that was changed from default Ubuntu install was that I set a static IP for the server.

Installed via these instructions on Ubuntu 16.04:

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

Server Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Ubuntu 16.04 64-bit server
- Deployment Method: SNAP
- Number of Running Instances: 1

**Comment by TheMythPT** [comment]
Are you proxying your snap installation?
Which webserver are you running in your server?

**Comment by dctheee** [comment]
No proxy. 
They webserver should just be the default configured when installing the snap. Literally nothing else has changed.

**Comment by TheMythPT** [comment]
I've never used Caddy to proxy the Rocket.chat instance.
I'd probably advise you to install Apache and then proxy it.
I can help you if you want.
Also, would you want SSL/TLS in your instance?
Can you `add/delete` DNS records?

**Comment by dctheee** [comment]
I'll eventually do SSL. Currently just in testing mode until fully deployed. 

Haven't yet configured the domain. Just intending to run through dynamic dns and redirect traffic to port 3000. Currently just accessing through public IP and port 3000.

**Comment by TheMythPT** [comment]
At a 1st glance, the problem rely in the fact that the domain isn't found (that means no DNS record).
Configuring a DNS record, installing Apache and proxying the instance via Apache would solve that quickly

**Comment by TheMythPT** [comment]
Or it can be a problem in their end (I need to test later in my instance to be sure)
