### ISSUE TITLE
Voice chat not working?

### ISSUE THREAD

**Issue by gthorne** [RocketChat/Rocket.Chat#1304]
When we click the microphone next to the 'message' box, it toggles between the microphone and stop icons.  It doesn't seem to record any audio for anyone on this server, though.  I checked this issues group, but couldn't find anyone else with the same issue.  I'm not sure if it's a bug, or just something we've mis-configured.  Is there any documentation on this feature?  I searched the wiki and couldn't find anything.

**Comment by gthorne** [comment]
Actually doesn't seem to work on demo.rocket.chat either.

**Comment by graywolf336** [comment]
I think #1305 is the fix for this, unless I'm mistaken. You'll need to add the wav type to the allowed uploads.

**Comment by emcguinness** [comment]
Yep, what graywolf said. Currently unless you allow wav files the audio recorder button doesn't work (it tries to upload a wav when you hit stop). Add `audio/wav` to your file upload whitelist for it to work(`audio/*` will also work but allow all audio file types to be uploaded to your server).

![image](https://cloud.githubusercontent.com/assets/14922332/10859507/ef1a4d6a-7f55-11e5-98d3-d6dec25551ee.png)

**Comment by shtefcs** [comment]
@emcguinness oh thnx for that, just came to my mind today to ask is there a way to upload video.

Can you write  `in` what exactly need to be in *Media Types* field to have both audio and video files.

**Comment by emcguinness** [comment]
Yes, an admin has full control. If you live the accepted media types blank, that means you accept all. Other than that you can have a comma separated list of all the file types you like. [This site](http://www.freeformatter.com/mime-types-list.html) seems to have a good list of all the types. You can also do something like `audio\*` which will allow all audio types.

**Comment by shtefcs** [comment]
@emcguinness Tnx for help.

I tried to add in field both `image/* , video/* , audio/* ,` and `image/*, video/*, audio/*,`

When I try to upload either video or audio, it's say 

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/0eff0e3f-feb4-470a-a02c-52fcd0378f60/2015-11-03_0141.png)

**Comment by emcguinness** [comment]
I know someone said they were working on it, I forget who, but that setting is not as responsive as it should be. Try restarting Rocket.Chat and that should help.

**Comment by shtefcs** [comment]
Oki

**Comment by graywolf336** [comment]
@shtefcs what type of file did you try to upload then? And what was the settings when you tried it? Just curious so I can try and replicate it to determine if I can fix it.

**Comment by shtefcs** [comment]
@graywolf336 The file type for video is this ![](http://content.screencast.com/users/shtefcs/folders/Jing/media/8a4cb629-77ae-4c46-a3b1-e840cb36f7d9/2015-11-03_1436.png)

And for audiot, I tried to record using Rocket.Chat audio recording feature.

I tried both this settings `image/* , video/* , audio/* ,` and `image/*, video/*, audio/*,`

**Comment by gthorne** [comment]
Worked for me after server restart.

**Comment by geekgonecrazy** [comment]
@shtefcs fyi that is not the MIME type you point to in the screenshot.  A restart definitely seems to fix the issue for most people

**Comment by shtefcs** [comment]
oki, audio is working now.

**Comment by geekgonecrazy** [comment]
Ok guys let me know if this issue returns.  Going to go ahead and close otherwise

**Comment by graywolf336** [comment]
Maybe add to the description of that field "A restart of your server is required after you change this."

**Comment by geekgonecrazy** [comment]
That would be helpful.  We need to do this to all that require restart
