### ISSUE TITLE
Emote detection fails around linebreaks

### ISSUE THREAD

**Issue by BenWiederhake** [RocketChat/Rocket.Chat#13059]
### Description:

Emote detection fails around linebreaks.

### Steps to reproduce:

1. Open a chat, for example a direct message to yourself.
2. Send the following single, multi-line message, which contains no trailing or leading whitespace:

       :D foo :D bar :D baz :D quux :D
       :D this :D is :D a simple :D test :D
       without :D leading :D or :D trailing :D emote
       :D hello :D world :D

### Expected behavior:

The message is sent and all occurrences of `:D` get replaced by `😃`.

### Actual behavior:

The message is sent and *MOST* occurrences of `:D` get replaced by `😃`, *EXCEPT* those around the linebreaks.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.0
- Operating System: dunno, shouldn't be relevant
- Deployment Method: dunno
- Number of Running Instances: 1, I guess, shouldn't be relevant
- DB Replicaset Oplog: dunno, shouldn't be relevant
- NodeJS Version: dunno
- MongoDB Version: dunno

### Additional context

I found this issue while using a private instance.  I'm just the end user, and have been told to direct any bug reports upstream.

### Relevant logs:

JS console log: `Loading: false` (nothing else; seems irrelevant)

Server log: unavailable; this is a private instance.  Shouldn't be relevant.

**Comment by savish28** [comment]
@tassoevan Could I work on this issue?

**Comment by tassoevan** [comment]
@savish28 Of course!

**Comment by savish28** [comment]
@tassoevan Please review PR #13447. It solves this issue.
