### ISSUE TITLE
CSS Conflicts when loading elements from npm packages

### ISSUE THREAD

**Issue by anqtran** [RocketChat/Rocket.Chat#13058]
Hi everyone,

I am trying to load fullcalendar from npm and I ran into some css conflicts which can not be resolved. The css from the element is conflict with the main css of rocketchat. I wonder if there is any way to solve this.

Here is the code from the files.

```
<template name="Calendar">
	{{#requiresPermission 'view-livechat-manager'}}
    <div>
        <div id="calendarDiv"></div>
    </div>
	{{/requiresPermission}}
</template>
```

```
import { Meteor } from 'meteor/meteor';
import { Template } from 'meteor/templating';
import { fullcalendar } from 'fullcalendar';
/* globals LivechatTeacherOfficeHour */

Template.Calendar.onRendered(() => {
	$('#calendarDiv').fullCalendar({
		defaultView: 'agendaWeek',
		header: {
			left: 'basicDay, basicWeek, month',
			center: 'title',
			right: 'today prev,next'
		},
		editable: true,
		selectable: true,
		selectHelper: true,
		select: function(start, end) {

		},
	});
});

```

**Comment by tassoevan** [comment]
@anqtran We're working to mitigate some BEM violations, like `!important` declarations and deeply nested selectors. I'm closing this issue now since your case is very specific, but feel free to reopen it if this is still an issue for you.
