### ISSUE TITLE
Need Ability to Require a Minimum Version of Mobile Apps

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#13068]
### Description:

Now that the legacy (non-native) mobile apps have been deprecated, we would like to be able to prevent people from logging into our Rocket Chat instance when using those older versions.  From what I can see, there is no way, currently, to detect and restrict those older mobile app versions from logging into the Rocket Chat server.

### Steps to reproduce:

Log into Rocket Chat instance with any version of the Rocket Chat mobile app.

### Expected behavior:

Ideally, we would have an Admin setting that sets a require version number for gaining access to the server, or some other method of restricting app versions.

### Actual behavior:

We don't currently have that as an Admin option.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: CentOS Linux release 7.6.1810
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.9.3
- MongoDB Version: 3.0

**Comment by reetp** [comment]
@rocket-cat close
