### ISSUE TITLE
Search messages - make autofocus for the search field

### ISSUE THREAD

**Issue by nopynoop** [RocketChat/Rocket.Chat#13062]
## My Setup
- Chat Version: 0.73.0

## Description
Immediate Autofucus on the search field.

### Current Behavior
When a user clicks on the search messages icon he needs to click again to the search field before he can start typing.

### Expected Behavior
When a user clicks on the icon he should be able to start searching immediately. This is most likely his only intention.

![2019-01-02_16-53-52](https://user-images.githubusercontent.com/25570106/50599675-0e178980-0eaf-11e9-98e2-1889d72fce83.gif)

**Comment by reetp** [comment]
@rocket-cat close

Please check for duplicates before opening an new one. This is the third report.

Closing in favour of 
https://github.com/RocketChat/Rocket.Chat/issues/11482
