### ISSUE TITLE
Ban users from channel (what is "ban-user"?)

### ISSUE THREAD

**Issue by vynmera** [RocketChat/Rocket.Chat#13063]
We currently have a `ban-user` permission, but it is never used. Should we remove the permission, or create a proper ban-from-channel feature?

**Comment by naiaokami** [comment]
> We currently have a `ban-user` permission, but it is never used. Should we remove the permission, or create a proper ban-from-channel feature?

We need the ability to ban users from channels. A lot of people (myself included) are using Rocket.Chat as a public service.

**Comment by naiaokami** [comment]
#10932

**Comment by naiaokami** [comment]
@vynmera #10932 #10963

This is something I feel a lot would want. We are using Rocket.Chat as a "private instance" of something like Discord for a public community.

**Comment by technologypoet** [comment]
Curious whether there are any near term plans to include this? Similarly we'd like the ability to ban users, or failing that, the ability to kick users with a longer timeout before they can rejoin

**Comment by reetp** [comment]
@rocket-cat close

One of several similar requests that can go under NFR 

https://github.com/RocketChat/feature-requests/issues/25

Please follow up there.
