### ISSUE TITLE
File List upgrade

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#1307]
I think it will be really helpful to sort files into types:
- images
- videos
- zip/other

Also, images/videos should be displayed as thumbs, cause it will be much easier to navigate then like its now.

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/5dce73b9-106b-4d3c-9ee5-e4468a3c1734/2015-10-31_0419.png)
##

**Comment by ninja-** [comment]
I would sort them by date, and only display last X files

**Comment by shtefcs** [comment]
That could be additional sorting option.

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap so we will revisit once other priorities have been addressed.

**Comment by shtefcs** [comment]
I dont believe you will even remember and find this feature ever once you close it.

**Comment by SeanPackham** [comment]
@shtefcs I understand how you feel but I back the decision and can add that we would rather be upfront and clear than let an issue stay open for another 2 years. 

We are adopting a stricter stance to feature requests to reduce the administrative burden on the team so that we can deliver more features.

**Comment by shtefcs** [comment]
@SeanPackham I think that you should def listen community more then you randomly adding new features. That mean you should have some voting system build for the features, so you can sort it out by priority and number of requests.

You didn't listen for community requests for many useful features which in same time was not to hard to develope or do it. Much easier then starting 3-4 different mobile applications and still not having proper mobile app to cover most important features and with decent push  notifications.

I think you guys should listen more community then internal team which seems randomly making decisions.

**Comment by SeanPackham** [comment]
@shtefcs I agree we want to have a better way of filtering feature requests, making them more visible and allowing people to upvote.

What do you think about discussing and upvoting feature requests on our https://forums.rocket.chat/c/feature-requests

**Comment by geekgonecrazy** [comment]
@shtefcs see: https://forums.rocket.chat/t/about-the-feature-requests-category for explaination of our process.

We want to make it easier for the community to see what we actually plan to work on.  Also to encourage more well thought out and discussed features.

Right now our github is a hot mess of good ideas, terrible ideas, good ideas that we really shouldnt add to our core, good ideas that could be Rocket.Chat Apps instead, bugs and support.

**Comment by juanpetterson** [comment]
I'm working on it, and soon I'll send the PR.
