### ISSUE TITLE
Room Member list not working

### ISSUE THREAD

**Issue by xcpdq** [RocketChat/Rocket.Chat#13071]
Since the last update (I think) the member list of any room doesn't work. Nothing shows up. I upgraded to 0.73.1 but the error is present in this version as well. The error I see in the console is:

rocketchat_1  | Exception while invoking method 'getUsersOfRoom' { MongoError: exception: Unrecognized pipeline stage name: '$lookup'
rocketchat_1  |     at queryCallback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/cursor.js:248:25)
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
rocketchat_1  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
rocketchat_1  |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
rocketchat_1  |  => awaited here:
rocketchat_1  |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
rocketchat_1  |     at Promise.asyncApply (server/methods/getUsersOfRoom.js:23:11)
rocketchat_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_1  |   errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
rocketchat_1  |   code: 16436,
rocketchat_1  |   ok: 0,
rocketchat_1  |   name: 'MongoError',
rocketchat_1  |   [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by reetp** [comment]
Read this first:
https://rocket.chat/docs/contributing/reporting-issues

Then fill out these details properly and paste here thank you:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by antgel** [comment]
Closing as this is the "didn't upgrade Mongo" issue and OP hasn't responded.
