### ISSUE TITLE
Message to save E2E passwords persists after switching users

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#13075]
### Description:

The header message

> **Save your encryption password.**
> Click here to view and copy your password.

<img width="419" alt="captura de tela 2019-01-04 as 17 38 49" src="https://user-images.githubusercontent.com/2263066/50707343-ae081b00-1047-11e9-9a2c-e2040b5b470a.png">

is shown for a user containing a valid E2E password if a previous user haven't save it.

### Steps to reproduce:

1. Enable E2E encryption.
2. Create/Have users A and B.
3. Login with A, click in header message to save E2E password, and logout.
4. Login with B and logout without clicking on header message.
5. Login with A.

### Expected behavior:

Not see the header message .

### Actual behavior:

The header is shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.0-develop (commit hash: 7bd82ef943)
- Operating System: Darwin/MacOS Mojave (18.2.0)
- Deployment Method: source code
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version:

**Comment by knrt10** [comment]
On it, will try to fix this.

**Comment by tassoevan** [comment]
It seems solved right now.
