### ISSUE TITLE
Internal Server Error with WebDav upload (Error: delete is not implemented)

### ISSUE THREAD

**Issue by MrHpower** [RocketChat/Rocket.Chat#13079]
### Description:

Internal Server Error [500] with Webdav File upload.

### Steps to reproduce:

Enable webdav
Config Webdav
Check config, username password and URL

### Expected behavior:

Upload the file to the webdav lovation

### Actual behavior:

[I20190105-10:26:01.936(1) Exception in callback of async function: TypeError: Webdav is not a constructor     at new WebdavStore (packages/rocketchat:file-upload/ufs/Webdav/server.js:17:18)     at Object.configureUploadsStore (packages/rocketchat:file-upload/server/lib/FileUpload.js:20:10)     at packages/rocketchat:file-upload/server/config/Webdav.js:55:35     at later (/Rocketchat/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:892:31)     at Timeout._onTimeout (/Rocketchat/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:829:19)     at ontimeout (timers.js:498:11)     at tryOnTimeout (timers.js:323:5)     at Timer.listOnTimeout (timers.js:290:5) 
[I20190105-10:26:02.434(1) Setting default file store to Webdav 
[I20190105-10:26:37.154(1) Meteor ➔ method ufsCreate -> userId: jS3tSyMCektjr34KbD90 , arguments:  [ { name: 'test.txt',     size: 4,     type: 'text/plain',     rid: 'VaJxs2KlDfGvvBWf6L34igNPjLpQyMCektjrD',     description: '',     store: 'Uploads' } ] 
[I20190105-10:26:37.264(1) UploadProxy ➔ debug Upload URL: /ufs/Webdav:Uploads/vRCg2ffa5747grGRrwo?token=K378085DQW&progress=1 
[I20190105-10:26:37.268(1) UploadProxy ➔ debug Correct instance 
[I20190105-10:26:37.305(1) Meteor ➔ method ufsComplete -> userId: jS3tSyMCektjr34KbD90 , arguments:  [ 'vRCg2ffa5747grGRrwo', 'Uploads', 'K378085DQW' ] 
[I20190105-10:26:37.337(1) Exception while invoking method 'ufsComplete' Error: delete is not implemented     at WebdavStore.delete (packages/jalik:ufs/ufs-store.js:377:15)     at Object.<anonymous> (packages/jalik:ufs/ufs-store.js:357:17)     at packages/matb33_collection-hooks.js:558:28     at Array.forEach (<anonymous>)     at Function._.each._.forEach (packages/underscore.js:139:11)     at packages/matb33_collection-hooks.js:557:11     at Array.forEach (<anonymous>)     at Function._.each._.forEach (packages/underscore.js:139:11)     at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)     at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)     at ns.Collection.remove (packages/mongo/collection.js:620:31)     at ModelsBaseDb.remove (packages/rocketchat:lib/server/models/_BaseDb.js:292:33)     at ns.Collection.model.remove (packages/rocketchat:lib/server/models/_BaseDb.js:100:16)     at MethodInvocation.ufsComplete (packages/jalik:ufs/ufs-methods.js:112:39)     at MethodInvocation.methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:71:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
[I20190105-10:26:37.369(1) Meteor ➔ method ufsDelete -> userId: jS3tSyMCektjr34KbD90 , arguments:  [ 'vRCg2ffa5747grGRrwo', 'Uploads', 'K378085DQW' ] 
[I20190105-10:26:37.400(1) Exception while invoking method 'ufsDelete' Error: delete is not implemented     at WebdavStore.delete (packages/jalik:ufs/ufs-store.js:377:15)     at Object.<anonymous> (packages/jalik:ufs/ufs-store.js:357:17)     at packages/matb33_collection-hooks.js:558:28     at Array.forEach (<anonymous>)     at Function._.each._.forEach (packages/underscore.js:139:11)     at packages/matb33_collection-hooks.js:557:11     at Array.forEach (<anonymous>)     at Function._.each._.forEach (packages/underscore.js:139:11)     at Object.<anonymous> (packages/matb33_collection-hooks.js:556:9)     at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)     at ns.Collection.remove (packages/mongo/collection.js:620:31)     at ModelsBaseDb.remove (packages/rocketchat:lib/server/models/_BaseDb.js:292:33)     at ns.Collection.model.remove (packages/rocketchat:lib/server/models/_BaseDb.js:100:16)     at MethodInvocation.ufsDelete (packages/jalik:ufs/ufs-methods.js:194:42)     at MethodInvocation.methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:71:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
[I20190105-10:26:44.203(1) Meteor ➔ method getStatistics -> userId: jS3tSyMCektjr34KbD90 , arguments:  [] 
[I20190105-10:26:44.209(1) Meteor ➔ method instances/get -> userId: jS3tSyMCektjr34KbD90 , arguments:  [] 
[I20190105-10:30:00.282(1) SyncedCron ➔ info Starting "Generate download files for user data". 
[I20190105-10:30:00.285(1) SyncedCron ➔ info Finished "Generate download files for user data". 
[I20190105-10:30:00.293(1) SyncedCron ➔ info Not running "Generate download files for user data" again. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: v8.15.0
- MongoDB Version: db version v3.6.9

**Comment by horvan** [comment]
Same here. tried to use next cloud as backend no luck with the given version This is broken since I updated rocketchat and has worked in the past.

**Comment by promofu** [comment]
uupsi... tried to activate nextcloud webdav with the same issue
- nextCloud v14.0.3
- rocket.chat v0.73.1
both as Dockers

also the webdav url acc. to. https://rocket.chat/docs/administrator-guides/integrations/nextcloud-and-webdav/ is incorrect. for me this should be:
https://<server>/remote.php/webdav/
not
https://<server>[/nextcloud]/remote.php/dav/files/USERNAME/

**Comment by Adam212** [comment]
Hello,

I have the same problem after upgrade from 0.72.3 to 0.73.1

Regards,
Adam

**Comment by Julianoe** [comment]
Hello

I use 0.72.3 with Nextcloud 14 and i have the same issue.
I tried to configure Nextcloud to be the file server for the rocketchat instance
