### ISSUE TITLE
Idea : add autocomplete webhook

### ISSUE THREAD

**Issue by kernicPanel** [RocketChat/Rocket.Chat#1308]
Let me explain this through an example
Once outgoing webhooks ane added, create one triggered by "$", then sended text is parsed by my bot, and runs according command. 
ie: "$start 1234" runs "start" command with "1234" args.

Autocomplete hook could work like this:
I enter "$st" and press tab, the hook is triggered, sends current text to the bot and the response populates the autocomplete list with something like [{command: […], description: […]}, […]] and whatever needed by the list.

What do you think ?

If nobody is interested by this feature, maybe someone can give me hints on how to do this ?
##

**Comment by kernicPanel** [comment]
BTW, I've already submitted this idea : #1086 but I think this approach is simpler to implement and gives more flexibility.
Any thoughts @geekgonecrazy ?

**Comment by kernicPanel** [comment]
And to be perfectly clear, I've submitted the same idea to mattermost team : mattermost/platform#1256
I hope this would'nt bother anyone, I'd love to see this becoming a kind of standard feature.

**Comment by Sing-Li** [comment]
@kernicPanel great minds think alike. Our own @geekgonecrazy has proposed bot command autocomplete over a month ago and we have bashed around a variety of implementations for a few weeks.

My personal comment to the webhook approach is that it might be an overkill to involve such  network and compute overhead, plus the need to sync the client and bot, just to transfer essentially a static table of information. Every  (think thousands of) client talking to the bot will incur this overhead.

**Comment by kernicPanel** [comment]
@Sing-Li In my use case, there is no static information.
Data returned for autocompletion may be computed by the bot.

Let me explain my use case more precisely:
My bot contains data for each users including their api key to redmine.
When a outgoing hook is triggered (by slack for now), the bot uses redmine APi in the context of the user, and some commands are available, others not.
Plus using autocomplete hooks allows much more than just listing available comands.

**Comment by kernicPanel** [comment]
Imagine this workflow where the bot is using your github api key:
```
$addl[tab]
Autocomplete list : ['addlabel']

$addLabel [tab]
Autocomplete list : [<long list of issues>]

$addLabel 12[tab]
Autocomplete list : [<long list of issues begining with 12>]

$addLabel 1234 [tab]
Autocomplete list : [<list of available tags>]

$addLabel 1234 feat[tab]
Autocomplete list : [<list of available tags begining with feat>]
```

And so on…
This "simple" implementation allows bots to have their custom autocomplete, regarding current textline, user, chatroom, etc
And all this logic belong where it should: on the bot.

I believe this would be greatly useful.

**Comment by kernicPanel** [comment]
Simpler implementaion could require current textline to be in each autocomplete rerponse.
This way when selected, textline is replaced by the autocompleted one.

ie: 
```
$add[tab]
Autocomplete list : ['$addlabel', '$addAssignent', '$addStuff']
```

**Comment by geekgonecrazy** [comment]
This sounds like it could potentially be a useful thing.  Maybe an api a package could hook into?  This might add more flexibility and actually be useful for bot autocomplete too.

**Comment by kernicPanel** [comment]
I don't know how it could be implemented in rocket (unfortunately I don't have time to dig into this), but I strongly believe it could bring chatops on a brand new level.

**Comment by timkinnane** [comment]
Duplicates #1308, closing because the other ticket has more recent context.
