### ISSUE TITLE
Standuply alternative and circleci notifications

### ISSUE THREAD

**Issue by altinukshini** [RocketChat/Rocket.Chat#13084]
1. Does anyone know a good rocketchat alternative to slack's standuply bot?
2. How do you handle circleci build notifications to rocketchat? I assume I should be writing a custom script that calls the rocketchat webhook, is there any example I can look at?

Thanks in advance for your help!

**Comment by geekgonecrazy** [comment]
I personally just created an integration and posted it as a question in a channel.  I have a cron job that triggers it on week days. 

I don't know of any alternatives yet.  Definitely take a look at Rocket.Chat apps framework.  https://forum.rocket.chat is a good resource for that.

I'd love to see an app like this created for this.

Regarding circleci notification goto integrations page and it will spit out an example curl command. You can tweak it and pop it in circleci.  I'd replace the url with a circle ci secret so not just anyone can hit it :)
