### ISSUE TITLE
Docker image for Rocket 0.73.1 not consistent, node 8.11.3 instead of 8.11.4

### ISSUE THREAD

**Issue by rsimai** [RocketChat/Rocket.Chat#13085]
### Description:

The latest/current image from Dockerhub reports as

Rocket.Chat Version: 0.73.1
NodeJS Version: 8.11.3 - x64

within the log after start while according to the release information 

https://github.com/RocketChat/Rocket.Chat/releases/tag/0.73.1

it should be Node: 8.11.4.

### Steps to reproduce:

docker pull the image, start, see the log.

### Expected behavior:

Consistency, preferably a newer node.js in the container.

**Comment by rsimai** [comment]
Same for the now current 0.73.2.

**Comment by geekgonecrazy** [comment]
https://github.com/RocketChat/Docker.Base.Image/blob/master/Dockerfile#L24 looks like the base image just wasn't updated.  I've updated it so the next build should now use 8.11.4

@sampaiodiego should we close and the next one will use the right version?  Or do we want to rebuild the current one?

**Comment by sampaiodiego** [comment]
I'll try rebuild the current. thx guys

**Comment by sampaiodiego** [comment]
done!

**Comment by rsimai** [comment]
pulled, started and verified, all is good now. You guys rock, thanks! :-)
