### ISSUE TITLE
curl not pulling latest release

### ISSUE THREAD

**Issue by terrorpup** [RocketChat/Rocket.Chat#13089]
When running the curl to pull the latest file, a file of 21 bytes is pulled looks like the server is having issues.

**Comment by terrorpup** [comment]
I am trying to pull the latest release and when I run this 

curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21  100    21    0     0    123      0 --:--:-- --:--:-- --:--:--   125

The file is only 21 bytes 

-rw-r--r-- 1 root     root       21 Jan  7 17:09 rocket.chat.tgz

It appears the server is having issues because if you go to the web you get 

internal server error

If you do a wget get it confirms it

wget https://releases.rocket.chat/latest/download
--2019-01-07 17:10:43--  https://releases.rocket.chat/latest/download
Resolving releases.rocket.chat (releases.rocket.chat)... 35.196.39.85
Connecting to releases.rocket.chat (releases.rocket.chat)|35.196.39.85|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2019-01-07 17:10:43 ERROR 500: Internal Server Error.

**Comment by geekgonecrazy** [comment]
This was a service error.  It was resolved a bit later that same day.  Closing
