### ISSUE TITLE
Improve translations of Korean

### ISSUE THREAD

**Issue by oldpiano** [RocketChat/Rocket.Chat#13087]
I'm a member of Lingo translation project.
I want to make pull request for Korean i18n files.
It based on 0.73.1

How can I create branch and new pull request?

**Comment by tassoevan** [comment]
I believe this is automated and requires an admin account since the PRs are made using @engelgabriel's user.

**Comment by oldpiano** [comment]
He made roll back I translated words!!

**Comment by ura14h** [comment]
@oldpiano I witnessed my translations also rolled back.
Perhaps, I think there is a problem with the automation to synchronize with the repository.

**Comment by tassoevan** [comment]
Hmm, I'm going to check it, folks. @ura14h, do your translations remain OK on Lingohub or they rolled back there too?

**Comment by oldpiano** [comment]
@ura14h Do you know how get back recently works?
@tassoevan please let me be a contributor, how can I apply?

**Comment by ura14h** [comment]
@tassoevan I work on Japanese translation. The problem for Example: #4010 "Audio Message Bit Rate", #4108 "Period of time until status changes to away. Value needs to be in seconds.". See translation's history. I have not checked all, but there are others.

@oldpiano Excuse me, I have no idea.

**Comment by tassoevan** [comment]
@ura14h I've restored the translations you mentioned.
@oldpiano I don't have much control over Lingohub, maybe @rodrigok can help us.
