### ISSUE TITLE
Invalid registration URL

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#13080]
I'm having the same issue as:
https://github.com/RocketChat/Rocket.Chat/issues/1585#issue-120756816

Version: 0.72.1

I have entered a string for the URL but it can't be accessed through https://site/register/string

What I'm trying to accomplish is to simly link to the registration page.

**Comment by reetp** [comment]
Unless you can show that there is actually a bug in Rocket ( read this please - https://rocket.chat/docs/contributing/reporting-issues supply some proper logs and information etc) then this is a support/configuration issue and you should refer to the forums or open.rocket.chat for help

If your issue really IS the same as 1585 you should follow up there.

Thank you.

**Comment by horvan** [comment]
There is a misspelling in the given url. Use register instead of registration and close this issue, please.

**Comment by cchbr** [comment]
I used register, I have updated the original post here now. I have read through the documentation, set the token and used it in the URL as described.

Here's the logged output:

[34mI20190106-11:16:30.299(0) [34mMeteor ➔ publish null -> userId: null , arguments:  [] 
[34mI20190106-11:16:30.301(0) [34mMeteor ➔ method public-settings/get -> userId: null , arguments:  [] 
[34mI20190106-11:16:30.321(0) [34mMeteor ➔ method loadLocale -> userId: null , arguments:  [ 'sv' ] 
[34mI20190106-11:16:30.325(0) [34mMeteor ➔ method checkRegistrationSecretURL -> userId: null , arguments:  [ 'ATP9QETC24B5bosQ7' ] 
[34mI20190106-11:16:30.328(0) [34mMeteor ➔ publish meteor_autoupdate_clientVersions -> userId: null , arguments:  [] 
[34mI20190106-11:16:30.779(0) [34mMeteor ➔ publish userData -> userId: null , arguments:  [] 
[34mI20190106-11:16:30.781(0) [34mMeteor ➔ publish activeUsers -> userId: null , arguments:  [] 
[34mI20190106-11:16:30.814(0) [34mMeteor ➔ method loadLocale -> userId: null , arguments:  [ 'sv' ] 
[34mI20190106-11:16:30.817(0) [34mMeteor ➔ method rooms/get -> userId: null , arguments:  [] 
[34mI20190106-11:16:30.819(0) [34mMeteor ➔ publish stream-notify-user -> userId: null , arguments:  [ 'null/rooms-changed', { useCollection: false, args: [] } ]

**Comment by horvan** [comment]
I use nginx and a manual debian/ubuntu installation of Rocketchat. and everyting workt fine in 7.2 as it does for 0.7.3 by now. Either you use the snap version and there is a bug with snap or your server is simply missconfigured. 

What is the output of the web browser if you enter https://yoursite,tdl/register/[the hash that is given on the account page] It should bring up the login dialog if everything works fine.

**Comment by reetp** [comment]
@rocket-cat close 
Closing on the basis of https://github.com/RocketChat/Rocket.Chat/issues/13080#issuecomment-451731943
