### ISSUE TITLE
Generate a jpeg-format avatar 

### ISSUE THREAD

**Issue by piepie314** [RocketChat/Rocket.Chat#13095]
- Your Rocket.Chat app version: 3.20
- Your Rocket.Chat server version: 0.73
- Device (or Simulator) you're running with: iOS 12
we can generate a jpeg-format avatar in a server which deployed on ubuntu(not docker),but we can not generate a jpeg-format avatar in a server which deployed in docker

**Comment by rodrigok** [comment]
@geekgonecrazy and @sampaiodiego any ideas?

**Comment by geekgonecrazy** [comment]
@piepie314 which docker container are you using?  What version of Ubuntu/docker running underneath?

**Comment by sampaiodiego** [comment]
closing per inactivity
