### ISSUE TITLE
When I reply to a message in the mobile app, only mentions are made.

### ISSUE THREAD

**Issue by rtarantelli** [RocketChat/Rocket.Chat#13106]
It would be interesting if instead of just making mention, copy the content of the original message. Tests were done on iPhone and Android.

**Comment by geekgonecrazy** [comment]
@rtarantelli when you do reply I assume long pressing and tapping reply?  If so that should quote the original message as well as mention the person you reply to.

If yours isn't doing that then something might be wrong with your install

**Comment by frdmn** [comment]
@rtarantelli Can you check if the problem still occurs with the latest version of the mobile app? If the problem was not yet fixed, please reopen the issue in the mobile app repository: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues
