### ISSUE TITLE
Block Direct Messages

### ISSUE THREAD

**Issue by Volkanugr** [RocketChat/Rocket.Chat#1311]
Hi , Everyone 

sorry i'm too late to explain this issue my exams are extremely hard finally I survived 💯 
when i use the direct messaging everyone can send and receive text but i do not want to message to come specific person it should be basic ui to block specific persons 

Thanks
##

**Comment by geekgonecrazy** [comment]
Can you clarify what you mean?

**Comment by djeber** [comment]
this is a very important feature what he means is to give the users the ability to ignore or block or stop other users from sending them direct messages

**Comment by djeber** [comment]
@engelgabriel ani thoughts on this one !!

**Comment by engelgabriel** [comment]
we are building the UI to "edit" the subscription object, so user will be able to mute any channel, including direct messages. Not just mute, but totally customize the alerts frequency, sounds, etc.

**Comment by uidzero** [comment]
I was going to open a separate issue for this, but after this is done, would it be possible for the moderator to permanently ban someone from a channel? I would like to use rocket.chat somewhat like the demo is being used, as a semi-public space for people to gather. 

I just started looking at this project, and coming from an IRC background, it seems that in a social (as opposed to work) setting there are times where removing a user or (as is already possible) muting them would be beneficial. Also, I haven't tested this, but as an extension of the question, if you mute someone and they leave a channel and rejoin, does the previous mute status stay in effect currently or is it an easy way to get around being muted? Also, do system administrators have the ability to make themselves channel moderators?

It seems to me that out of all the chat software I've looked at (this, Zulip, and Mattermost) this seems to be the only one that doesn't completely operate under the assumption that people will always keep it "friendly and professional" like they would in a work chat style environment.

**Comment by MichaelSavin** [comment]
@engelgabriel Is any progress on this issue?

**Comment by engelgabriel** [comment]
Not yet :( do you want us to increase the priority on this one?

**Comment by MichaelSavin** [comment]
@engelgabriel I think, it will be better to have public roadmap for the next one or two releases (something like meteor's roadmap for 1.4 release).
This feature is important, but better link it with other interface/right management tasks in one sprint.

**Comment by xenithorb** [comment]
For whatever reason someone is spamming me on https://Rocket.Chat and it would be a great feature to have the ability to ignore them completely +1

**Comment by bazarnew** [comment]
@engelgabriel 
  I am also interested in this essential feature.
PLEASE It's possible and let +1

**Comment by ragulhari** [comment]
This functionality is very important, I want to know when this will be ready

**Comment by bazarnew** [comment]
yes ?
This functionality is very important, I want to know when this will be ready

**Comment by geekgonecrazy** [comment]
@bazarnew no timeline currently.  We welcome Pull Requests if you or anyone is interested in helping us add this feature.

**Comment by bazarnew** [comment]
@geekgonecrazy 
i am sorry
I do not know if anyone you know who I am willing to pay for the ability to block user
Due to lack of user Blocks girls on our site are not viable
Because we are an Islamic country and we have the possibility
block user for girl iran essential feature.

**Comment by Volkanugr** [comment]
PLEASE Be polite 
**freedom of expression**

**Comment by bazarnew** [comment]
@Volkanugr 

what does it mean?
What I got naughty
Google Translate I'm the mean

**Comment by geekgonecrazy** [comment]
@bazarnew i'm not sure I understand what you mean.  If you are saying you are willing to pay.  On each ticket we do have the option to place a bounty.  Tickets with bounties might get picked up by contributors looking to implement a quick feature for extra money.  So feel free to check that out.

I definitely understand that this is important to you.

**Comment by IQ2022** [comment]
can we have the ability to disable one specific user from sending direct messages? sometimes a user joins just to advertise to other members privately, no way to control that unless we disable direct message for that user.

**Comment by taoteh1221** [comment]
@xenithorb Same issue here, some moron is spamming me in a chat room to vote their link up on a 3rd party site. Not being able to block this totally sucks.

**Comment by jcalfee** [comment]
Blocking a user forever is harsh.  Please consider one or more:
* how long (default as infinity)

Always true and not optional is fine with me:
* notify immediate
* notify on contact attempt
* notify how long

**Comment by jcalfee** [comment]
An alternative that might be a good step before blocking is needed is this:

On the left, if a user is spamming and I just ignore them the folder builds up with lots of unread messages.  After 7 login days have passed but a folder with unread messages has not been opened, it could moved into a collapsed in a folder: [+]Unread (99) ... The user could still go in there and investigate.

**Comment by l0k1-smirenski** [comment]
I just want to put my vote for a block function for users, and just so it's not forgotten, it should make the user also invisible to the user in chatrooms as well. Telegram has a feature to block DMs but it does not work in channels. I eventually got the user in question to start being a decent person and they were a general nuisance and eventually got really intensely shunned in the other platform too, related, which helped. But why should I have to deal with unbearable people in DM or in a channel, when they are obnoxious.

**Comment by flantascience** [comment]
Was this feature ever developed?   It looks like it keeps getting bumped back from 0.42 to .44 to .45 to .47?

**Comment by net-activities** [comment]
unfortunately it seems no dev has the problem to get dos'd with private messages. that makes it low priority.
in our open test system the women and kids get hundreds of unwanted pns and as a result - leave the system.
same with the link preview - we had to disable it completely, because trolls and pedophiles send porn links to the kids in private messages.
so its hard to use the software outside closed user groups.

**Comment by flantascience** [comment]
What is your use-case?  I've also got young people on mine.   We haven't
had issues yet, but I'm anticipating them at some point.

Jim Flannery

jim-flannery.com
p. 860-212-8862
e. jim@jim-flannery.com
s. jim_flannery

**Comment by miguelmota** [comment]
Does rocket.chat offer ability to block direct messages?
