### ISSUE TITLE
HipChat Cloud ZIP import fails

### ISSUE THREAD

**Issue by altafub** [RocketChat/Rocket.Chat#13127]
### Description:

HipChat cloud zip file import fails with error - "Invalid CEN header (bad signature)"

### Steps to reproduce:

1. Login to rocketchat
2. Open https://<rocketchat.com>/admin/import
3. Start HIPCHAT (ZIP) import process by uploading the Zip file exported from HipChat Cloud.

### Expected behavior:

The import process should complete successfully.

### Actual behavior:

Fails with error - "Invalid CEN header (bad signature)"

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: Ubuntu 14.04
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.0

**Comment by Hudell** [comment]
Fixed with the release of version 0.74.3
