### ISSUE TITLE
Create Token

### ISSUE THREAD

**Issue by uncledent** [RocketChat/Rocket.Chat#13125]
Hello, I have a question regarding this api:

https://rocket.chat/docs/developer-guides/rest-api/users/createtoken/

First of all, why is this api listed under Livechat in docs?

Second of all is there a difference with a normal auth token? 

How to invalidate it?

How long is it valid?

Thank you!

I can update the docs if you answer this questions.

**Comment by MarcosSpessatto** [comment]
Hello @uncledent.

> First of all, why is this api listed under Livechat in docs?

There's no reason to that endpoint  to be listed under Livechat docs, probably it seems that the endpoint has the same link of some endpoint of livechat.

> Second of all is there a difference with a normal auth token?

Is the same session token, but can be generated by admin or someone with the necessary permission.

> How to invalidate it?

Like a session token, you can call the logout endpoint and the token will be invalidated.

> How long is it valid?

There is a settings in the admin panel under `Accounts -> Login Expiration in Days` that you can configure how many days the session will be valid.

I don't know how behavior you are looking for, but we have the personal access token also, maybe the feature can help with your need.

[Personal tokens](https://rocket.chat/docs/developer-guides/rest-api/personal-access-tokens/)
[Endpoints](https://rocket.chat/docs/developer-guides/rest-api/users/generatepersonalaccesstoken/)
