### ISSUE TITLE
Invalid streamRoom eventName error after last develop update

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#13138]
### Description:

After the last develop update (commit a3fceae7d919274346b8451ee60cf21e41e12202), existing dm rooms do not properly load, and the log displays the following message(s):
```
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/deleteMessage"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/deleteMessageBulk"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/typing"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/webrtc"
Checking: checkPreMessageSentPrevent
Checking: executePreMessageSentPrevent
```
### Steps to reproduce:

1. Update to latest develop.
2. Try to click on any dm session. 
3. Room will sit loading but not showing any data, the log messages will appear.

### Expected behavior:
Room messages should load right up after entering the room.

### Actual behavior:
Screen sits loading but does not show any messages, and the described errors appear. If the dm channel is hidden, then the messages come up after a while. Also, loading of past messages takes a lot longer than before.

### Rocket.Chat

| Version                 | 0.74.0-develop                                            |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 137                                                       |
| Database Migration Date | Fri Jan 11 2019 15:57:14 GMT-0600 (Central Standard Time) |
| Installed at            | Tue Jul 03 2018 10:28:32 GMT-0500 (Central Daylight Time) |
| Uptime                  | 37 seconds                                                |
| Deployment ID           | wecGmPkstnsm2e7ge                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | a3fceae7d919274346b8451ee60cf21e41e12202                     |
| ------- | ------------------------------------------------------------ |
| Date    | Fri Jan 11 17:31:15 2019 -0200                               |
| Branch  | develop                                                      |
| Tag     | 0.73.0                                                       |
| Author  | Marcos Spessatto Defendi                                     |
| Subject | Convert rocketchat-file-upload to main module structure (#13094) |

### Runtime Environment

| OS Type         | Linux                           |
| --------------- | ------------------------------- |
| OS Platform     | linux                           |
| OS Arch         | x64                             |
| OS Release      | 4.15.0-43-generic               |
| Node Version    | v8.11.4                         |
| OS Uptime       | 18 hours, 54 minutes, 6 seconds |
| OS Load Average | 3.17, 2.29, 2.14                |
| OS Total Memory | 7.79 GB                         |
| OS Free Memory  | 246.24 MB                       |
| OS CPU Count    | 4                               |
### Relevant logs:
```
ufs: permissions are not defined for store "GridFS:Uploads"
ufs: permissions are not defined for store "GridFS:UserDataFiles"
ufs: permissions are not defined for store "GridFS:Avatars"
Updating process.env.MAIL_URL
ufs: permissions are not defined for store "FileSystem:Uploads"
ufs: permissions are not defined for store "FileSystem:Avatars"
ufs: permissions are not defined for store "FileSystem:UserDataFiles"
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Starting Email Intercepter...
Setting default file store to GridFS
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 137","time":{"$date":1547243834821},"level":"info"}
ufs: temp directory created at "/tmp/ufs"
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
The App c33fa1a6-68a7-491e-bf49-9d7b99671c48 is checking if "poll" command exists.
Loaded the Apps Framework and loaded a total of 2 Apps!
➔ System ➔ startup
➔ +-----------------------------------------------------------+
➔ |                       SERVER RUNNING                      |
➔ +-----------------------------------------------------------+
➔ |                                                           |
➔ |  Rocket.Chat Version: 0.74.0-develop                      |
➔ |       NodeJS Version: 8.11.4 - x64                        |
➔ |             Platform: linux                               |
➔ |         Process Port: 3000                                |
➔ |             Site URL: https://rocketchat.belmankraul.com  |
➔ |     ReplicaSet OpLog: Enabled                             |
➔ |          Commit Hash: a3fceae7d9                          |
➔ |        Commit Branch: develop                             |
➔ |                                                           |
➔ +-----------------------------------------------------------+
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/deleteMessage"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/deleteMessageBulk"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/typing"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/webrtc"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMrocket.cat/deleteMessage"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMrocket.cat/deleteMessageBulk"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMrocket.cat/typing"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMrocket.cat/webrtc"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/typing"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/typing"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMz4y7X4mgSk3ZXZMBP/deleteMessage"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMz4y7X4mgSk3ZXZMBP/deleteMessageBulk"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMz4y7X4mgSk3ZXZMBP/typing"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMz4y7X4mgSk3ZXZMBP/webrtc"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/deleteMessage"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/deleteMessageBulk"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/typing"
Invalid streamRoom eventName: "Y3iYZy6zJvSZwEoS4jdvYv3J7xLXirvqjM/webrtc"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMtyxZN4mnJ8cuBSAqW/deleteMessage"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMtyxZN4mnJ8cuBSAqW/deleteMessageBulk"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMtyxZN4mnJ8cuBSAqW/typing"
Invalid streamRoom eventName: "jdvYv3J7xLXirvqjMtyxZN4mnJ8cuBSAqW/webrtc"
Checking: checkPreMessageSentPrevent
Checking: executePreMessageSentPrevent
```

**Comment by bkraul** [comment]
This  issue persists in commit 807e340049.

**Comment by bkraul** [comment]
@MarcosSpessatto any thoughts on this? I see these are your commits.

**Comment by MarcosSpessatto** [comment]
Hey @bkraul, sorry for the long delay. I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13146) fix your issue. Please let me know if the problem persists.
