### ISSUE TITLE
security issue: logout and login with new user shows direct chat messages of previous user

### ISSUE THREAD

**Issue by solo999** [RocketChat/Rocket.Chat#1313]
Reproduction:
user 1 logged in and has direct messages with user X
user 1 logged out
user 2 logged in
user 2 can see direct messages of user 1 with user X

If after user 1 logged out refresh web page, then all is OK and foreign messages will not be shown...

**Comment by geekgonecrazy** [comment]
@solo999 does this still happen?  We changed the way log out is handled, so it should properly be purging things on log out.
