### ISSUE TITLE
[BUG] Livechat: Least amount routing method isn't counting open chats

### ISSUE THREAD

**Issue by hmagarotto** [RocketChat/Rocket.Chat#13134]
### Description:

The Least amount routing method is counting overall agent chats.
The counter is not the number of currently opened chats.
If one agent is out for a period (example: vacation), when he comes back, he will receive all chats until reach the count of other agents.

### Steps to reproduce:

1. Configure 2 livechat agents
2. Login with agent 1 and finish 5 chats
3. Login with agent 1 and agent 2
4. Start new chats
5. All new chats will be routed to agent 2 until it reaches 5 chats (number of chats routed to agent 1)

### Expected behavior:

The agent with the **least amount of open chats** is paired with the incoming livechat.

### Actual behavior:

The agent with the **least amount of overall chats** is paired with the incoming livechat.

Documentation isn't clear about this. (https://rocket.chat/docs/administrator-guides/livechat/livechat-queues/#round-robin)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Linux / docker official image
- Deployment Method: docker

**Comment by renatobecker** [comment]
Hi @hmagarotto!

Yeah, we have already detected that we need to improve the routing method stuff, we have plans to work on it very soon.

Thanks.

**Comment by vizarch** [comment]
Hi, was something done in this topic? :)

**Comment by renatobecker** [comment]
Hi!

Yes, we have improved our `routing system` over the last months, we have now a new algorithm, it's called by `Load Balancing` routing method.
When running this method, the number of chats is not stored anymore, the new algorithm address the new chats based on the current open chats, it's a real-time approach.
But, this new algorithm is an `Enterprise` feature, so you'll need to get an `Enterprise` license to have access to it.

Thanks.

**Comment by vizarch** [comment]
Simple workaround: https://github.com/vizarch/fix-rocketchat-livechat-routing
