### ISSUE TITLE
Live Room transfer Rest API to transfer it to user

### ISSUE THREAD

**Issue by rohitmyaim** [RocketChat/Rocket.Chat#13141]
There is a Rest API to transfer the room to a department.
https://rocket.chat/docs/developer-guides/rest-api/livechat/room/index.html#transfer-livechat-room

As I check the code, it can support room transfer to a user with some basic modification in code.

Rocket.Chat/packages/rocketchat-livechat/server/api/v1/room.js:96
Just need to take one more parameter in API and then link up the code.

**Comment by renatobecker** [comment]
Hi @rohitmyaim.

I didn't understand your requirement.
Please, change the issue's description according our guide for opening issues.
Please take a look at here: https://rocket.chat/docs/contributing/reporting-issues

Thanks.

**Comment by renatobecker** [comment]
Hi @rohitmyaim!

I'll take a look on this ASAP.
The point is that you would need to have a list of available agents to forward the chat, right?

Thanks.

**Comment by rohitmyaim** [comment]
Yes. @renatobecker 
Currently the API exist to transfer the room to a department. Similar it can be forward it to a user.

**Comment by renatobecker** [comment]
Hi @rohitmyaim!
Please, take a look at this link -> https://github.com/RocketChat/Rocket.Chat/pull/13308.
The new endpoint I mentioned on the link above will probably do what you're looking for.

Thanks.

**Comment by renatobecker** [comment]
Closed by #13308.
