### ISSUE TITLE
Trying to update snap to latest version (candidate 0.73.2)

### ISSUE THREAD

**Issue by sloslo4** [RocketChat/Rocket.Chat#13148]
### Description:
Trying to update snap to latest version (candidate)

### Steps to reproduce:

sudo snap refresh rocketchat-server --candidate

### Expected behavior:

Success refresh

### Actual behavior:

error: cannot perform the following tasks:
- Run configure hook of "rocketchat-server" snap if present (run hook "configure": "((enable)|(disable))" is not a valid, set to enable or disable)

### Server Setup Information:
Ubuntu core 16.04

|  Rocket.Chat Version: 0.72.3
|       NodeJS Version: 8.11.3 - 
|               Platform: linux  
|         Process Port: 3000
|              Commit Hash: 65747ce814 
|          Commit Branch: HEAD   

### Additional context

sudo snap refresh rocketchat-server --candidate
error: cannot perform the following tasks:
- Run configure hook of "rocketchat-server" snap if present (run hook "configure": "((enable)|(disable))" is not a valid, set to enable or disable)

but on clean installation all ok (tested on local PC and production server (error on server))

### Relevant logs:

cat /var/log/syslog | grep -i snapd

Jan 14 15:02:15 localhost snapd[1152]: handlers.go:394: Reported install problem for "rocketchat-server" as 60ddd684-180d-11e9-8e83-fa163e6cac46 OOPSID
Jan 14 15:06:01 localhost snapd[1152]: handlers.go:394: Reported install problem for "rocketchat-server" as e7200d0a-180d-11e9-8e83-fa163e6cac46 OOPSID
Jan 14 15:07:01 localhost snapd[1152]: storehelpers.go:443: cannot refresh: snap has no updates available: "core", "pc", "pc-kernel", "rocketchat-server"
Jan 14 15:12:19 localhost snapd[1152]: handlers.go:394: Reported install problem for "rocketchat-server" as already-reported

**Comment by sloslo4** [comment]
today snap refreshed ok, so closeup

**Comment by reetp** [comment]
https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

"When will my snap installation get the latest release?
Snaps are one of our biggest install base. They are also auto updating. As a result we like to spend more time testing before releasing. Updated Snaps are usually released around the 15th of the month - around 2 weeks after a new release. This gives us time to look for issues so you don’t have to.
"

**Comment by awunder** [comment]
same here on a new installation...

**Comment by 4dams** [comment]
Running into the same error. 

```
root@cloud:~# sudo snap install rocketchat-server
error: cannot perform the following tasks:
- Run configure hook of "rocketchat-server" snap if present (run hook "configure": "((enable)|(disable))" is not a valid, set to enable or disable)
```

**Comment by isaipanelinha** [comment]
Running into the same error.

**Comment by 0E800** [comment]
ditto: Debian Stretch
