### ISSUE TITLE
WebSocket sendMessage - cannot set custom emoji (missing field). REST API has emoji field.

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat#13143]
I'm trying WebSocket API and it works great. But I need to set custom emoji for chat message.

REST-API have optional argument for emoji: 
```
message.emoji | :smirk: | Optional | If provided, this will make the avatar on this message be an emoji. 
```
https://rocket.chat/docs/developer-guides/rest-api/chat/sendmessage/

But `Message` object in realtime-api doesn't have `emoji` filed:
https://rocket.chat/docs/developer-guides/realtime-api/the-message-object/

In realtime-api only `emoji` field is missing. Would it be possilbe to add it? It would help me a lot.

Thank you!

**Comment by MarcosSpessatto** [comment]
HI @tuxmartin, did you try send the message over websocket? Because the rest api `chat.sendMessage` uses the same method of websocket to send the message. The docs probably are outdated. Please let me know if you have any problem with this.

**Comment by tuxmartin** [comment]
@MarcosSpessatto thank you, it works!
