### ISSUE TITLE
How can i help with translate?

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#1314]
Hello, i am russian. I want to help you with translate some parts of application. 
I just try to edit `ru.i18n.json` and restart chat, and nothing is happened. So i need some how to :)
Thank's

**Comment by DaniLabs** [comment]
They are experimenting Lingohub. If you want to help, send an email to support at rocket.chat to be invited to the translation project.

**Comment by vetash** [comment]
Done. :)
