### ISSUE TITLE
Rocket Chat has a lot of problems

### ISSUE THREAD

**Issue by DBReinitialized** [RocketChat/Rocket.Chat#13144]
Hiya Rocket Chat Community!
First off, I want to start out saying amazing work on getting this piece of software together. Based on many search attempts, I don't think there is any good alternative open source chat system such as this. However ... We have some problems :(

One of the biggest things that has kept me away from using Rocket Chat beyond a testing environment is the sheer amount of issues/bugs it seems to possess ultimately making it unstable for long-term production use. Yet, I am noticing the community seems to still be quite focused on Implementing new features ATM. 

One thing I'd love to see happen is a release with focuses solely on stablising the current code so it's truly production ready. Compared to alternative OSP, nothing comes close to the features which are already here, but aren't very stable. By focusing on fixing what is here now, Rocket Chat can truly become a competitor to the likes of Slack, Microsoft Teams, Discord, etc. But as it stands, the walled gardens are the more likely choices due this huge flaw of instability.

Now ...  I don't know much in terms of coordinating these things, (not to mention in suffering RSI ATM so can't use mouse/keyboard for long periods of time), but I hope to bring awareness to this crippling problem to turn this great product into an absolutely amazing product.

**Comment by TomaszDom** [comment]
FWIW, we've been using rocketchat for about 2 years in an enterprise environment with >100 users and have not had any downtime, only a few minutes for upgrades. The real issues is cowboy administrators automatically upgrading their instances each time there's a new release and enabling beta features with no thought given to planning, testing and deployment strategy. If you don't spend the time to go through dozens of bug reports and follow rocketchat's development you're playing a very dangerous game each time you upgrade, if you don't have a test environment you're less than sane, etc.

An LTS track would solve some of these issues, but I'm not sure we can expect that from this project.

Anyway, a bug report form is not exactly the place to discuss this.

**Comment by DBReinitialized** [comment]
Although I could be wrong since I don't contribute often, considering the open source nature and the use of GitHub, I figured Issues would be the best place to discuss with the community and keep track of potential ways to solve this.

As for solutions, an LTS would be a fantastic way to handle this. Maybe divise a team of contributors who focus more toward stabilizing the codebase than implementing features so work can be merged up later on as features continued to be worked on? However done, a proper LTS schedule would do wonders for the many features for this project.

**Comment by reetp** [comment]
If you notice Rocket is still at < 1.0 and should therefore be considered Alpha. IOW don't expect too much, and expect rapid changes.

However it seems that there are a lot of users with stable setups and no issues. Those that do experience them report them here, but note the biggest problem with an issue tracker is you ONLY see the problems and not the success stories. Also note that snap installs are probably the most popular installation type, and they are released some 2 weeks after a point release to ensure they are as stable as possible.

Note that the current policy and best place to discuss all this is in the forums, and leave github clear for actual issues.

And finally, like all things Open Source, Rocket will progress to your goals faster if you contribute code, fix bugs, help on forums or chat rooms, write documentation etc.

Thanks

**Comment by reetp** [comment]
@rocket-cat close

Please open a thread in the forums to discuss further.

**Comment by DBReinitialized** [comment]
Apologies, I didn't know there was a forum as it's linked only on the website after clicking on Community and not the GitHub. I'll definitely move this over there knowing that now
