### ISSUE TITLE
Add setting to configure default role for user on manual registration

### ISSUE THREAD

**Issue by Hudell** [RocketChat/Rocket.Chat#13151]
Rocket.Chat currently has a setting to determine the initial role for users who login using an authentication service (such as OAuth, LDAP or SAML), but there's no setting to configure the initial role of new registered users.

It always assigns the 'user' role to those users. We need a new setting to change this behavior.

**Comment by r1walz** [comment]
@Hudell : I'd like to work on this issue

**Comment by Hudell** [comment]
Thanks, @r1walz ! Let me know if you need any help or extra information.

**Comment by r1walz** [comment]
@Hudell : any help or information are most welcomed. Basically, I have to add a setting in the admin panel so that every new user is automatically assigned the selected role, right? Correct me if I am wrong, give me leads if you have any. Thanks!

**Comment by Hudell** [comment]
That's right! There's a setting there that does it for OAuth service, so you can just make another one similar to that.

**Comment by kanishk98** [comment]
@r1walz I'm getting myself comfortable with Zulip, and I'd like to take up this issue. Are you working on it?

**Comment by r1walz** [comment]
@kanishk98 : I guess you have mistaken, this is **Rocket Chat**.  By the way, you can take this up as an issue, I am not getting time to solve this right now. Gor for it! :tada:

**Comment by carpecodeum** [comment]
can i have a go at it?

**Comment by r1walz** [comment]
Hey, @carpecodeum! I don't think anyone is working on this one. Feel free to take this up, if no one has already done it.

**Comment by carpecodeum** [comment]
@r1walz hey, for which service do i have to make the setting and could you please elaborate how the users select their roles

**Comment by carpecodeum** [comment]
@Hudell hey i found out that the admin can assign the roles to users from the admin/ accounts > registeration and its default is user , also the admin can assign the roles manually. so, what exactly needs go be done?

**Comment by carpecodeum** [comment]
@r1walz 

> @Hudell hey i found out that the admin can assign the roles to users from the admin/ accounts > registeration and its default is user , also the admin can assign the roles manually. so, what exactly needs go be done?

**Comment by ashwaniYDV** [comment]
I am working on it

**Comment by lpilz** [comment]
@carpecodeum An added setting in Admin -> Accounts -> Registration for default roles for normal registration is necessary. It currently exists only for external registration, but not for the default registration form.

**Comment by leonardorocc0** [comment]
+1

**Comment by Cronus1007** [comment]
Shall I Take over this issue  if currently no one is working upon it.
