### ISSUE TITLE
Send buttons is not shown on IE11

### ISSUE THREAD

**Issue by barak-haviv** [RocketChat/Rocket.Chat#13156]
### Description:

Send Icon is not shown on smaller screen less than 500px

- Version of Rocket.Chat Server: 0.72.3 
- Operating System: windows 10

I was Manage to solve it by adding custom CSS

/* IE11 bug send button is not shown */
@media only screen and (max-width: 500px) {
  .rc-message-box__send {
    flex-basis: 45px
  }
}

Extra: cursor is not defined for send button
.rc-message-box__send {
  cursor: pointer
}

**Comment by ggazzo** [comment]
@barak-haviv we are deprecating this widget version, so after this pr #15133 ...could you test the new widget version? thx
