### ISSUE TITLE
feature request: custom notification groups

### ISSUE THREAD

**Issue by OGFilthyCasual** [RocketChat/Rocket.Chat#1315]
geekgonecrazy doesnt like it when I notify _@all_ in _#general_ on the demo server; I thought it might be nice to have a way to create a custom mention group, which I can populate with several folks I would otherwise want to mention all at once.  Like _@rocketDevs_ anyone in the list would get a mention notification.

![image](https://cloud.githubusercontent.com/assets/1946002/10874878/14c9159c-80e0-11e5-8f6d-6aa96fa695af.png)
##

**Comment by geekgonecrazy** [comment]
:+1: this is a pretty great idea!  Maybe making use of teams?

**Comment by damienmollard** [comment]
+1

**Comment by cimbalek** [comment]
+1

**Comment by baldimir** [comment]
+1

**Comment by engelgabriel** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2192
