### ISSUE TITLE
Local login not available if ldap enabled?

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#1316]
I hooked up an instance of rocket.chat to ldap and I got the impression that I since then can't login with local users via the ui - this seems to be true for the initial admin user as well as the hubot user.

As the bot is still working, even when restared it seems like it is an issue with the ui?

**Comment by viperscape** [comment]
I feel like local login should always be available, see [locking yourself out](https://github.com/RocketChat/Rocket.Chat/issues/1428) in addition it might be nice to have mixed logins

**Comment by geekgonecrazy** [comment]
Maybe we can make this an option?

**Comment by perk** [comment]
+1 on this one.

If that's an option then what should happen in case LDAP is configured but not accessible?

As no one (even admin) can log-in to rchat to change settings (eg. use new LDAP  address) should admin change them in database directly?

**Comment by marceloschmidt** [comment]
I'll close this in favor of #1957, which I believe does it as requested.
