### ISSUE TITLE
Apps call to commands.list breaks on subdir

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#13171]
### Description:

when using a subdirectory calls to commands.list and others break

### Expected behavior:

Get 200 response

### Actual behavior:

Calls incorrect address

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2

### Additional context

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/client/lib/RestApiClient.js#L47

Using window.location.orgin which grabs host.  Wouldn't take into account if using a subdir.

**Comment by geekgonecrazy** [comment]
Talked with @d-gubert and document.baseURI might do the trick.  This file is pretty meteor command free if we want to keep it that way might use that.  Otherwise could probably use something like Meteor.absoluteUrl ?

**Comment by ngulden** [comment]
I reported the issue directly to the Rocket.Chat team. I was using the official Rocket.Chat Docker container in version 0.71.1.
