### ISSUE TITLE
Hubot services endpoint

### ISSUE THREAD

**Issue by zubivan** [RocketChat/Rocket.Chat#1317]
Hi All,

I'm trying to create a custom bot for TFS build notifications as they are supporting webhooks out of the box now. So, I've created a custom bot with the following signuture:

```
module.exports = (robot) ->
   robot.router.post '/hubot/tfs/:room', (req, res) ->
     room   = req.params.room
     data   = if req.body.payload? then JSON.parse req.body.payload else req.body
  
     robot.messageRoom room, "Incoming: #{data}"
  
     res.send 'OK'

```

What is a default url where hubot service is exposed for rocket.chat? Is it the same as root chat url or I should use a default hubot port 8080? Is there any way to configure it?

Regards,
Ivan

**Comment by CrystalMethod** [comment]
I stumbled across the same issue. Any information would be really helpful.

**Comment by zubivan** [comment]
Hi all,

So I made some further investigations, read some manuals and when I'm running hubot from terminal via

```
bin/hubot -a rocketchat
```

And if everything is configured properly you should be able to reach your bot via:

```
curl -X POST http://localhost:8080/hubot/tfsimport/GENERAL -d message=lala
```

Which should result in the following log message from running bot:

```
[Thu Nov 05 2015 20:59:39 GMT+0000 (UTC)] INFO Sending Message To Room: GENERAL
[Thu Nov 05 2015 20:59:39 GMT+0000 (UTC)] INFO Change received on ID f2ihRqLmEe3MfDyQW
```

P.S. Omg folks, why room name is case sensetive?

**Comment by geekgonecrazy** [comment]
@zubivan TFS as in Visual Studio Team Services previously Visual Studio Online?  I'd love to see this integration.  I use it occasionally at my day job.

**Comment by engelgabriel** [comment]
Relates to #2426

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by geekgonecrazy** [comment]
Closing.  Looks like issue was resolved.  Please see our hubot adapter repo: https://github.com/rocketchat/hubot-rocketchat or our webhook documentation https://rocket.chat/docs/administrator-guides/integrations/
