### ISSUE TITLE
Quote a message via REST API postMessage

### ISSUE THREAD

**Issue by amelkor** [RocketChat/Rocket.Chat#13179]
Currently I do not see any possibilities to quote or reply a message with REST API functions. Is this possible or do I miss something? Such a feature really wanted.

**Comment by MarcosSpessatto** [comment]
Hi @amelkor, sorry for the delay, but you can do this already, you must only send the **text** of message like:
`[ ](http://localhost:3000/channel/general?msg=awJJnaT3aHDciXQgm) @user.test test message` where the url is the id of the message you want reply to.

**Comment by chenshinan** [comment]
> Hi @amelkor, sorry for the delay, but you can do this already, you must only send the **text** of message like:
> `[ ](http://localhost:3000/channel/general?msg=awJJnaT3aHDciXQgm) @user.test test message` where the url is the id of the message you want reply to.

Hi,Can you give me a complete example？I don't know the meaning '@user.test test message'

**Comment by reetp** [comment]
> Hi,Can you give me a complete example？I don't know the meaning '@user.test test message'

Please note that github is for bugs, not support.

https://rocket.chat/docs/getting-support/

https://open.rocket.chat/
https://forums.rocket.chat/

**Comment by beulahpt** [comment]
@amelkor  Have you got solution? Do you know how to use the above?
