### ISSUE TITLE
Partially formatting words does only work at the beginning of the word

### ISSUE THREAD

**Issue by yahesh** [RocketChat/Rocket.Chat#13187]
You can format text with Markdown-esque syntax like `*blafasel*` which results in "**blafasel**". It is even possible to only format the beginning of a word with `*bla*fasel` which result in "**bla**fasel". It is however **NOT** possible to format the end of a word or the middle of a word like `bla*fasel*` or `bl*afa*sel` which result in "bla\*fasel\*" and "bl\*afa\*sel" instead of "bla**fasel**" and "bl**afa**sel".

Thus it's currently not possible to emphasise certain parts of a word - which can be essential in languages in which complex word combinations exist. An example in German would be: "Bundes**ausbildungs**förderungsgesetz" which intends to emphasise that it's a federal law meant to support people's **education**.

**Comment by knrt10** [comment]
Fixing this. On it
