### ISSUE TITLE
Uploading Error

### ISSUE THREAD

**Issue by MalloryThomas** [RocketChat/Rocket.Chat#13189]
- Your Rocket.Chat app version: 2.14.7
- Your Rocket.Chat server version: 0.57.1
- Device (or Simulator) you're running with: Windows App (on PC)

Since the new year, no one on my team has been able to upload any files/photos. None of the settings in the Admin account have changed from last year when we were able to send them.

This is what happens and it never progresses:

![image](https://user-images.githubusercontent.com/46764630/51283106-f6a2cb00-199b-11e9-8af1-2e29a38f90fc.png)

**Comment by BlueTac92** [comment]
I've seen this a few times, usually after upgrading rocketchat. Restarting the rocketchat service usually resolves it form me though I'm not sure why it happens.

**Comment by MalloryThomas** [comment]
I've downloaded the newest version from the site. This is the version that downloads. Restarting the RocketChat service unfortunately hasn't helped. We were able to upload with no issues before updating the apps. Now, however, it seems that it's impossible to do so.

**Comment by reetp** [comment]
Can you follow this guide please.

https://rocket.chat/docs/contributing/reporting-issues

Then fill in some more of this information.

Which storage file type do you use?

What do your rocketchat and/or server/proxy logs tell you?

**Comment by rtarantelli** [comment]
Hi guys, I have the same problem here. Sometimes it works, sometimes it does not. Bad experience.

**Comment by rmaksimov** [comment]
I'm faced with this file uploading problem the first time I start RC after upgrading it to the new version. After restarting the service, it works fine (non-docker version, gridfs, nginx proxy)

**Comment by rtarantelli** [comment]
I thinking it was fixed in the current version. :thinking:

**Comment by MalloryThomas** [comment]
I quit using this service about 6 months because this wasn’t fixed in a timely manner.

Thanks,


[cid:image005.png@01D60BEC.F4317E40]
  Mallory Thomas | DESIGN MANAGER
  Direct Line: 604.998.0825 | P: 604.984.4395 | F: 604.984.4495
  Unit 208-1075 West 1st Street, North Vancouver, B.C., Canada
  www.innovativesignage.com<http://www.innovativesignage.com/>

**Comment by johncrisp** [comment]
This was reported against a very old version.

If this still occurs please test on the latest version and ask in https://forums/.rocket/chat or https://open.rocket./chat #support if you have problems before opening a new issue here.

Thanks.
