### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by aexonicarindam** [RocketChat/Rocket.Chat#13185]
I had clone the code and want to run on my localhost. But there are some error.

=> Errors prevented startup:                  
   
   While reading package from `/var/www/Rocket.Chat/packages/rocketchat-katex`:
   fs.js:904:18: ENOENT: no such file or directory, scandir
   'packages/rocketchat-katex/node_modules/katex/dist/fonts/'
   at Object.fs.readdirSync (fs.js:904:18)
   at package.js:22:29

Anyone can you please help me on that.

**Comment by MarcosSpessatto** [comment]
@aexonicarindam did you run `meteor npm install` before try to run the project?

**Comment by MartinSchoeler** [comment]
Please move this to the appropriate support channel. Thanks!
