### ISSUE TITLE
[SlackBridge] " SlackBridge Out All " --> " Off " NOT WORKING

### ISSUE THREAD

**Issue by fabien4455** [RocketChat/Rocket.Chat#13186]
### Description:

If I choose Off setting to only enable slackbridge on one or two channels, the messages sent from slack will be displayed on Rocket but the opposite ( message sent from Rocket wont be displayed in Slack ) 

### Steps to reproduce:

1 - Select 'SlackBridge' in the Administration menu
2 - Type the name of the Channel into 'SlackBridge Out Channels' and select it
3 - Click 'Save Changes' 
4 - Reboot RocketChat server
5 - Send message from Slack on the channel
6 - Send message from Rocket on the channel 

### Expected behavior:

Message from Slack displayed in Rocket
Message from Rocket displayed in Slack

### Actual behavior:

Message from Slack displayed in Rocket
BUT Message from Rocket IS NOT in Slack

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Ubuntu 18.04
- Deployment Method: docker ( docker-compose.yml )
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.18...

If we want slackbridge working we need to choose SlackBridge Out All.. That's not good

Please fix it !

**Comment by fabien4455** [comment]
UP

**Comment by fabien4455** [comment]
Up again for 1.0.0 🗡

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/14273
