### ISSUE TITLE
[ru] "Chat Now" button for leader in chatroom

### ISSUE THREAD

**Issue by iegik** [RocketChat/Rocket.Chat#13190]
## My Setup
- Operating System: macOS Mojave
- App Version: latest
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
![screenshot 2019-01-18 at 14 31 02](https://user-images.githubusercontent.com/175293/51384577-d440b700-1b2d-11e9-859c-ad3b9e5658f7.png)

### Current Behavior
![screenshot 2019-01-18 at 14 31 02](https://user-images.githubusercontent.com/175293/51384577-d440b700-1b2d-11e9-859c-ad3b9e5658f7.png)

### Expected Behavior
![screenshot 2019-01-18 at 14 53 06](https://user-images.githubusercontent.com/175293/51385612-da846280-1b30-11e9-9c4b-b019a48850bd.png)

**Comment by MartinSchoeler** [comment]
It seems to be working on the latest version, please reopen this if you find this issue again. Thanks!
