### ISSUE TITLE
Adding New User Erroneously Modified EVERY fname value in  db.rocketchat_subscriptions

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#13195]
### Description:

We had a new user log into our Rocket Chat instance today.  When this happened, Rocket Chat decided to modify every fname value in the db.rocketchat_subscriptions collection, to that of the new user.  This resulted in the left panel index, showing every user in the company with this name! This happened for every single user in our Rocket Chat instance!  In every user's session, every name under "Direct Messages" showed this new employee's name.  However, the only thing altered was the fname value.  Avatars didn't change and actual accounts didn't change.  We were able to fix this by dropping the db.rocketchat_subscriptions collection and restoring that collection from last night's backup.  But we are extremely hesitant to add any other users.

It should be noted that our user accounts come from our LDAP servers.  Also, this new employee is also a former employee.  In the past, we deleted her Rocket Chat account.  Finally, it should also be noted that until yesterday, we were running Mongo 3.0.  We upgraded to 3.2.22 yesterday.

### Steps to reproduce:

1. LDAP account created.
2. New user logs in to Rocket Chat
3. Every employee in the company gets their list of available Direct Message users changed to this new employee's name.

### Expected behavior:

Obviously, the fname value in the collection should not be modified for existing users.  And the list of available users in Rocet Chat should not get changed to this new person's name.

### Actual behavior:

fname value in collection was changed for every user as was the Display name in the list of Direct Messaged users.

![image](https://user-images.githubusercontent.com/6833993/51414320-a2345280-1b37-11e9-9e20-78bdd35b105f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Centos 7.6
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.9.3
- MongoDB Version: 3.2.22

### Additional context

It should be noted that our user accounts come from our LDAP servers.  Also, this new employee is also a former employee.  In the past, we deleted her Rocket Chat account.  Finally, it should also be noted that until yesterday, we were running Mongo 3.0.  We upgraded to 3.2.22 yesterday.

### Relevant logs:

This is from the mongo log and shows all of the records getting modified.

<details>

```
2019-01-18T11:25:19.421-0600 I WRITE    [conn41] update rocketchat.rocketchat_subscription query: { t: "d" } update: { $set: { fname: "MiKindzi Shanks", _updatedAt: new Date(1547832316135) } } keysExamined:0 docsExamined:9026 nmoved:54 nMatched:6982 nModified:6982 keyUpdates:1 writeConflicts:0 numYields:85 locks:{ Global: { acquireCount: { r: 7068, w: 7068 } }, MMAPV1Journal: { acquireCount: { w: 7076 }, acquireWaitCount: { w: 6 }, timeAcquiringMicros: { w: 23913 } }, Database: { acquireCount: { w: 7068 } }, Collection: { acquireCount: { W: 86 }, acquireWaitCount: { W: 8 }, timeAcquiringMicros: { W: 3373 } }, Metadata: { acquireCount: { w: 6982 } }, oplog: { acquireCount: { W: 6982 }, acquireWaitCount: { W: 80 }, timeAcquiringMicros: { W: 22853 } } } 1433ms

2019-01-18T11:25:21.826-0600 I COMMAND  [conn41] command rocketchat.$cmd command: update { update: "rocketchat_subscription", updates: [ { q: { t: "d" }, u: { $set: { fname: "MiKindzi Shanks", _updatedAt: new Date(1547832316135) } }, upsert: false, multi: true } ], ordered: true, writeConcern: { w: "majority" } } keyUpdates:0 writeConflicts:0 numYields:0 reslen:95 locks:{ Global: { acquireCount: { r: 7068, w: 7068 } }, MMAPV1Journal: { acquireCount: { w: 7076 }, acquireWaitCount: { w: 6 }, timeAcquiringMicros: { w: 23913 } }, Database: { acquireCount: { w: 7068 } }, Collection: { acquireCount: { W: 86 }, acquireWaitCount: { W: 8 }, timeAcquiringMicros: { W: 3373 } }, Metadata: { acquireCount: { w: 6982 } }, oplog: { acquireCount: { W: 6982 }, acquireWaitCount: { W: 80 }, timeAcquiringMicros: { W: 22853 } } } protocol:op_query 3838ms

Here is the Rocket Chat log from the initial login.  I've "xxx'd out company info about our LDAP server:

Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAPHandler ➔ info#033[39m Init LDAP login mshanks
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Connection.info#033[39m Init setup
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Connection.info#033[39m Connecting ldaps://xxxx.xxxx.xxxx.xxxx:636
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Connection.info#033[39m LDAP connected
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Bind.info#033[39m Binding UserDN uid=xxxx,ou=xxxx,dc=xxxx,dc=xxxx
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Search.info#033[39m Searching user mshanks
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Search.info#033[39m Search result count 1
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Auth.info#033[39m Authenticating uid=mshanks,ou=xxxx,ou=xxxx,dc=xxxx,dc=xxxx
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Search.info#033[39m Search result count 1
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAP ➔ Auth.info#033[39m Authenticated uid=mshanks,ou=xxxx,ou=xxxx,dc=xxxx,dc=xxxx
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAPHandler ➔ info#033[39m Querying user
Jan 18 11:25:15 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAPHandler ➔ info#033[39m User does not exist, creating mshanks
Jan 18 11:25:16 chat rocketchat2: rocketchat_logger.js:299 #033[34mLDAPSync ➔ info#033[39m Syncing user data
```

</details>

**Comment by sampaiodiego** [comment]
thanks for the very detailed report! I have a script to fix the subscriptions in case this happen. I can send to you if you find useful. In the meantime I'll take a look why this is happening.

**Comment by sampaiodiego** [comment]
@mddvul22 is the setting `Username Field` filled in on your LDAP settings?

**Comment by mddvul22** [comment]
@sampaiodiego Thanks for the replies!  1. As for the script to fix the subscriptions, yes, please send it to me.  This would be very much preferable to our restoring from backup.  2. The username field is left empty in the LDAP settings of our Rocket Chat Administration section.  Also, should it be useful to know, the LDAP attribute that identifies the LDAP user who attempts authentication is uid. ("Search Field" in the Rocket Chat LDAP settings).

**Comment by sampaiodiego** [comment]
thanks @mddvul22 .. looking at code I found a situation where having the username field empty might cause that.. I'll give this a try..

you can use the following script to fix all subscriptions `fname`.. please use with caution, make a backup of the collection first:
```javascript
var subscriptions = db.rocketchat_subscription.find({
	t: 'd',
});

subscriptions.forEach(function (subscription) {
	var user = db.users.findOne({
		username: subscription.name,
	}, { name: 1 });
	if (!user) {
		return;
	}
	db.rocketchat_subscription.update({
		_id: subscription._id,
	}, {
		$set: {
			fname: user.name,
		},
	});
});

**Comment by mddvul22** [comment]
@sampaiodiego I really appreciate your assistance on this.  I have one question regarding your script.  Can I run this from within the mongodb shell?  Or do I need to call it from a command line prompt?

**Comment by sampaiodiego** [comment]
@mddvul22 yes it is intended to be run from mongodb shell.

**Comment by mddvul22** [comment]
@sampaiodiego We finally got around to upgrading our install to version 0.74.x.  I'm very happy to report that your changes did fix this problem for us.  Thank you!

**Comment by devadattas** [comment]
For anyone facing a similar issue here is the restoration code I used:

```js
var subscriptions = db.rocketchat_subscription.find({
  t: 'd'
});

subscriptions.forEach(function (subscription) {
  var subscription_rid = subscription.rid;
  print(subscription_rid);
  var uid = subscription.u._id;
  var alt_subscription = db.rocketchat_subscription.findOne({
    rid: subscription_rid,
    "u._id": {$ne: uid}
  });
  if(!alt_subscription) {
    return;
  }
  var user = db.users.findOne({
    username: alt_subscription.u.username,
  }, { name: 1, username: 1 });
  print(user.name);
  print(user.username);
  if (!user) {
    return;
  }
  db.rocketchat_subscription.update({
    _id: subscription._id,
  }, {
    $set: {
      fname: user.name,
      name: user.username
    },
  });
});
```

**Comment by sampaiodiego** [comment]
thanks guys.. I'd like to say that if you guys upgrade to version 3.10.4 it should fix automatically.. no need to run an external script.. pls let me know if you try it. thx again
