### ISSUE TITLE
File upload of file without extension creates unhandled promise rejection and failing downloads

### ISSUE THREAD

**Issue by chrismaes87** [RocketChat/Rocket.Chat#13205]
### Description:

uploaded files without file extension are not handled correctly

### Steps to reproduce:

1. as admin: allow all file types for upload
2. Uploading file.txt and downloading it works fine.
3. uploading file (without extension) --> download does not work. Logs complain about unhandled promise rejection

### Expected behavior:

works like any other file

### Actual behavior:

download fails with "Network error" and with an enormous lag

### Server Setup Information:

- Version of Rocket.Chat Server: docker image 0ac37ae01873 (0.71.1)
- Operating System: centos7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: ?
- MongoDB Version: 3.0

### Relevant logs:

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
(node:1) UnhandledPromiseRejectionWarning: Error: "value" required in setHeader("Content-Type", value)
    at validateHeader (_http_outgoing.js:489:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.res.setHeader (/app/bundle/programs/server/npm/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.setHeader (/app/bundle/programs/server/packages/rocketchat_cors.js:121:22)
    at FileUploadClass.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:1453:9)
    at Object.get (/app/bundle/programs/server/packages/rocketchat_file-upload.js:558:20)
    at /app/bundle/programs/server/packages/rocketchat_file-upload.js:826:25
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by reetp** [comment]
As per bug reporting guide here
https://rocket.chat/docs/contributing/reporting-issues

Please test on latest (docker should be 073.x)
Also check for other bugs as I think there is already an open issue on filenames without extension.

Thanks.

**Comment by chrismaes87** [comment]
The official docker image latest version is still 0.71 : https://hub.docker.com/_/rocket-chat. I failed to get this running with v0.73, but for the moment we stop looking into rocket.chat.

**Comment by reetp** [comment]
I think you can specify either the version or 'latest'.

I have it running on two different boxes....

Duplicate here and fixed in 0.73.2

https://github.com/RocketChat/Rocket.Chat/issues/12668

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
@rocket-cat close
