### ISSUE TITLE
Unread indicator: link to first unread message

### ISSUE THREAD

**Issue by mitchtbaum** [RocketChat/Rocket.Chat#1320]
`{#} new messages since {date}` could help a returning user catch up by linking {date}, or that entire notice bar, to that referenced unread message their upscroll.

**Comment by geekgonecrazy** [comment]
We for sure want to do this.  Loading history up until the point the last unread message and then scrolling requires a good bit of work. 

We welcome PR's or any help towards this.  :+1:
