### ISSUE TITLE
Clustering not working when using a ROOT_URL with a subpath

### ISSUE THREAD

**Issue by guillaumerybak** [RocketChat/Rocket.Chat#13200]
### Description:

When configuring a ROOT_URL for Rocket.Chat on a subpath (ex: https://awsome.tld/rocketchat1), the clustering feature does not seem to work properly. The instances are discovered, but the broadcast status as displayed in the admin's information page ("Current Status > Connected") is always empty and the "Current Status > Status" is either set to "waiting" or "connecting" but never "connected". I tried activating the debug & info logs in the server settings and saw this:
```
StreamBroadcast ➔ Auth.info prevent self connect 10.42.11.126:3000
StreamBroadcast ➔ Connection.info connecting in 10.42.12.64:3000
```

If I change the ROOT_URL to  https://awsome.tld, I start to see these logs:
```
StreamBroadcast ➔ Connection.info connecting in 10.42.12.64:3000
StreamBroadcast ➔ Auth.info Authorizing with 10.42.12.64:3000
StreamBroadcast ➔ Auth.info broadcastAuth with 10.42.12.64:3000 true
```
and the instances seem to be communicating correctly again in the Admin's Information page.

--

### Steps to reproduce:

1. Set a ROOT_URL with a subpath
2. Create a Cluster with several instances of Rocket.Chat

### Expected behavior:

The broadcast cluster should work event with a subpath.

### Actual behavior:

The Rocket.Chat instances see each other but do no communicate an broadcast notifications to each other.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.1
- Operating System: PhotonOS 2.0
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 4.0.5

**Comment by geekgonecrazy** [comment]
This one makes sense since at somepoint when setting in ROOT_URL rocket.chat now listens for the subdirectory path instead of the root.

So if website.com/rocketchat the actual instances are now listening at: 10.42.12.64:3000/rocketchat

Seems the event streams weren't updated to take that into account.

@RocketChat/core

**Comment by guillaumerybak** [comment]
Hello, do you think you will be able to fix this issue for the 1.0.0 release ?

**Comment by geekgonecrazy** [comment]
Can we maybe listen on both paths?  or tack subdir easily on when connecting to other instances?  This is catching more people now.

**Comment by geekgonecrazy** [comment]
@rodrigok @sampaiodiego how hard would this be?
