### ISSUE TITLE
Livechat package, what channel?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#1321]
A stupid question perhaps, but here goes: what channel (or room) is used for the livechat package? I've added the livechat package successfully but cannot figure out what channel/room it uses. So when somebody enters the livechat they cannot talk because "there's no operators online".

Any help is appreciated.

**Comment by emcguinness** [comment]
I have not looked over any of that code yet but I saw reference that a user need the "operator" role to appear online for the live chat. There was no way in the UI to do this at the time and it needed to be added directly to the DB. A quick search for operator did return [this](https://github.com/RocketChat/Rocket.Chat/blob/7cb836f33b79fddd787f621cb2a07e2f139abf3f/packages/rocketchat-livechat/methods.coffee#L48)which looks like that is accurate.

I would be tempted to say that the word operator needed to be added in to this part of the user record: `global_roles__" : [  "admin",  "user" ]`

That is a guess though, hopefully at least gets you closer.

**Comment by sampaiodiego** [comment]
hey guys.

so, the livechat package isn't usuable at the moment.. as @emcguinness found, there is no way on the UI to make a user an operator.

I'm working on a branch to do this things. So in the near future you should be able to assign a role operator to a user..

When I finish this basic things, I'll make a how to use the livechat package wiki page ..

**Comment by k0nsl** [comment]
Great, thanks @sampaiodiego !

**Comment by llwp** [comment]
Noticed that this still seems to be the case @sampaiodiego ("no way on the UI") ... however, the admin has requisite roles and it seems fair to expect that when this is the case the livechat would indicate *someone* is online.  Presently it does not.

I'll review the feature issue queue to get a feel for status.

Thanks for the great work so far - keen to get this feature completed!
