### ISSUE TITLE
File upload cached even when file is changed

### ISSUE THREAD

**Issue by iamtpage** [RocketChat/Rocket.Chat#13215]
### Description:

If you upload a file as a message attachment and then change the file contents, when you re upload the file as a message attachment it still shows up as the old file unchanged. If you delete the message and re upload the file, the new file is then actually displayed/uploaded

### Steps to reproduce:

1. Upload file as message (http://acme.com/video.mp4)
2. Change file, but keep file name and location the same
3. Reupload file as message (http://acme.com/video.mp4)
4. Reuploaded file is not changed, file is still file from Step 1

### Expected behavior:

The newer file to be uploaded, not the old file being cached

### Actual behavior:

The old file is cached and displayed as the message attachment instead of the new file

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: unRAID/linux
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.5

### Additional context

I believe the logic is something along the lines of:

"if file exists, don't upload it, just use the file already there"
instead of
"if file exists, check content/modification date, upload file if newer, send file"

**Comment by iamtpage** [comment]
I also would like to add that the rocket chat android app does not experience this issue, only the web chat client

**Comment by ggazzo** [comment]
@tassoevan 
![image](https://user-images.githubusercontent.com/5263975/52964361-e017d700-3380-11e9-927a-87066f5bed98.png)

**Comment by tassoevan** [comment]
We did the steps and we couldn't reproduce it. May I ask you to (1) repeat the procedure with images (since they have a preview) and (2) screen-record your steps?

**Comment by iamtpage** [comment]
Hi,

I've since migrated away from using Rocket.chat as my chat application. My use case used videos, so previews were shown (which is how I discovered the caching issue to begin with). I've torn down my rocket.chat infrastructure so I am unable to help with further troubleshooting. I'll close the issue.
