### ISSUE TITLE
Script restart attempt

### ISSUE THREAD

**Issue by devsigner** [RocketChat/Rocket.Chat#13229]
### Description:

After upgrade the Rocket.Chat server, the server doet not start. It reboot again and again.... 
### Server Setup Information:

- Version of Rocket.Chat Server:  rocket.chat-0.73.2.tgz
- Operating System: debian_version stretch/sid
- Deployment Method: meteor
- Number of Running Instances: 2
- DB Replicaset Oplog: 3
- NodeJS Version: 4.2.6

Error Log:
```
rocketchat/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
error: Forever detected script exited with code: 127
error: Script restart attempt #13
```

**Comment by reetp** [comment]
Please check your node version.

You state yours is 4.2.6 which is not going to work?

Should be around 8.11.4

**Comment by devsigner** [comment]
ok thanks, it's work !!! :)
