### ISSUE TITLE
How to update docker-based deployment?

### ISSUE THREAD

**Issue by hameno** [RocketChat/Rocket.Chat#1322]
I have installed Rocket.Chat using [this guide][1]. How can I update my deployment?

[1]: https://github.com/RocketChat/Rocket.Chat/wiki/Docker-Ubuntu-14.04-%2864-bit%29-VPS-with-Nginx-SSL-and-Hubot

**Comment by Dbzman** [comment]
You only have to download the latest image (docker pull rocketchat/rocket.chat) and recreate your container.

**Comment by hameno** [comment]
I have no knowledge about docker, so a step-by-step guide would be great...

**Comment by storrgie** [comment]
You're admitting your gap in knowledge about a project that is unrelated to rocket.chat. Educate yourself by going and researching how docker works.

**Comment by hameno** [comment]
I'm sorry, but no. I don't need to know inside knowledge about a third-party tool if I want to run a solution like Rocket.Chat, that is just insane. You can't know every damn tool...

**Comment by storrgie** [comment]
![Image go-on](https://imgflip.com/s/meme/Creepy-Condescending-Wonka.jpg)

**Comment by geekgonecrazy** [comment]
Wow that escalated.  :smile: 

`docker pull rocketchat/rocket.chat` will update the image.  Then simply re-run the command you started the container with.
