### ISSUE TITLE
Caddy SSL error

### ISSUE THREAD

**Issue by vdvas** [RocketChat/Rocket.Chat#13228]
Hi.
I install rocket chat on Ubuntu 18 and want to configure SSL.
sudo snap get rocketchat-server
Key Value
caddy enable
caddy-url https://rocket-chat.domain.com
https disable
port 3000

Hostnamectl settings dns name as rocket-chat.
In Active Directory DNS i create manual A record.
On public DNS I create manual A record for rocket-chat.domain.com with public IP.
Command “sudo snap set rocketchat-server https=enable” give error
sudo snap set rocketchat-server https=enable
error: cannot perform the following tasks:

Run configure hook of “rocketchat-server” snap (run hook “configure”: Error: Your public IP doesn’t match the one resolved for caddy-url, disabling https …)
What wrong?
In journal

Jan 23 10:32:21 rocket-chat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-caddy.
Jan 23 10:32:21 rocket-chat systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
Jan 23 10:32:21 rocket-chat systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Scheduled restart job, restart counter is at 4.
Jan 23 10:32:21 rocket-chat systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
Jan 23 10:32:21 rocket-chat systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result ‘exit-code’.
Jan 23 10:32:21 rocket-chat systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 10:32:21 rocket-chat rocketchat-server.rocketchat-caddy[1538]: Activating privacy features… 2019/01/23 10:32:21 [caddy-url] failed to obtain certificate: acme: Error 400 - urn:ietf:params:acme:error:malformed - Error creating new order :: Invalid character in DNS name

**Comment by reetp** [comment]
This seems to be a setup/support issue.
Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

Please also read the snap and caddy documentation

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug

If you have evidence of a bug please reopen and provide full information as per this template

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
