### ISSUE TITLE
Livechat error when heroku deployment

### ISSUE THREAD

**Issue by aexonicarindam** [RocketChat/Rocket.Chat#13242]
Getting below error from livechat, when uploading code to heroku

remote: sh: 0: Can't open /tmp/build_105cbca9643cc71bd3c64ef90735818b/packages/rocketchat-livechat/plugin/build.sh
remote: /app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.8.0_1.1m0lub4.07ltj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
remote: throw error;
remote: ^
remote: 
remote: Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
Is there have any solution on that?

**Comment by reetp** [comment]
This has been reported before.

This is closed
https://github.com/RocketChat/Rocket.Chat/issues/8838

This is still open:
https://github.com/RocketChat/Rocket.Chat/issues/7583

Close as duplicate?

**Comment by tassoevan** [comment]
I'm closing it in favor of #7583.
