### ISSUE TITLE
Cannot destructure property `versions` of 'undefined' or 'null' during checking for updates

### ISSUE THREAD

**Issue by overfl0** [RocketChat/Rocket.Chat#13243]
### Description:

The server hangs during the boot up procedure, when checking for updates and an error happens during that process. See stacktrace at the end.

### Steps to reproduce:

(Re)start the server, although it most probably is caused by `https://releases.rocket.chat/updates/check` returning a wrong response, during the check.

### Expected behavior:

The server starts

### Actual behavior:

Rocket Chat hangs and nginx returns http 502 until RC is restarted.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.72.3
- Operating System: Linux
- Deployment Method: tar (ansible)
- Number of Running Instances: 1

### Relevant logs:

```
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: Exception in callback of async function: TypeError: Cannot destructure property `versions` of 'undefined' or 'null'.
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at module.exportDefault (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_version-check.js:144:7)
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at Meteor.startup (/var/lib/rocket.chat/bundle/programs/server/packages/rocketchat_version-check.js:62:3)
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at Function.time (/var/lib/rocket.chat/bundle/programs/server/profile.js:309:28)
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at /var/lib/rocket.chat/bundle/programs/server/boot.js:427:13
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at /var/lib/rocket.chat/bundle/programs/server/boot.js:472:5
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at Function.run (/var/lib/rocket.chat/bundle/programs/server/profile.js:510:12)
Jan 23 05:14:16 ip-172-31-21-112 RocketChat[1787]: at /var/lib/rocket.chat/bundle/programs/server/boot.js:470:11
```

If the exception is thrown here:
https://github.com/RocketChat/Rocket.Chat/blob/0.72.3/packages/rocketchat-version-check/server/functions/checkVersionUpdate.js#L10

Then the only way I see for that to happen is if the `undefined` value is returned here:
https://github.com/RocketChat/Rocket.Chat/blob/0.72.3/packages/rocketchat-version-check/server/functions/getNewUpdates.js#L26-L30

I guess this can happen if the server returns a response that is not a json response, although meteor docs are not clear about what exactly happens in that case.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/14089
