### ISSUE TITLE
Ability to invite users via public link and/or to specific channels

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#1324]
##

**Comment by marceloschmidt** [comment]
Invitation via email, private link, public link, widget.
Also, it should be customizable so that each invitation should be able to be automatically granted a role by default.

**Comment by Dracozny** [comment]
I would suggest with the addition of an Expiration date/time option.

**Comment by rasos** [comment]
The API offers a joinLink for public channels, but it seems it is not available in the Web UI: https://rocket.chat/docs/developer-guides/realtime-api/method-calls/joining-channels/

Anyway, we would need a way to offer people a link to join both public and private channels.

**Comment by geekgonecrazy** [comment]
Closing this as this feature now exists:

Goto member list and invite down at the bottom:

![image](https://github.com/RocketChat/Rocket.Chat/assets/51996/9b7a642e-27b6-49f8-b54e-5c4a1af88f68)
