### ISSUE TITLE
Support search by full name

### ISSUE THREAD

**Issue by Nepoxx** [RocketChat/Rocket.Chat#1325]
When creating a private message, it would be convenient to be able to search by full name.

**Comment by capensisma** [comment]
like an autocomplete??

**Comment by Lochemage** [comment]
+1 Our username convention is to use first letter + last name, but that makes it impossible to search for someone by their first name when trying to direct message them. Note, that you can search their first name when trying to @ mention them, this seems to also search their full name details, but not when trying to find the user to direct message them privately.

**Comment by hvma** [comment]
+1

**Comment by frdmn** [comment]
+1

**Comment by marceloschmidt** [comment]
I'll close this issue in favor of #874. We need to work on that issue ASAP, as there are multiple issues referring to the same request.
