### ISSUE TITLE
Separate permissions for user managed incoming and outgoing integrations

### ISSUE THREAD

**Issue by steerben** [RocketChat/Rocket.Chat#13262]
### Description:

At the moment it is not possible to manage incoming and outgoing webhooks separately.
Therefore giving a user permission to handle their own integrations means allowing them create both, incoming and outgoing hooks.

Since outgoing webhooks are able to send everything written within a channel to an outside endpoint we cannot allow this from a compliance perspective.

We would allow having user managed incoming webhooks though.

Therefore it would be great if the `Manage Own Integrations
[manage-own-integrations]` permission would be more fine granular/resp. extended to specifically enable incoming, outgoing, none or both webhooks.

### Steps to reproduce:

See `Manage Own Integrations [manage-own-integrations]` permission

### Expected behaviour:

Splitting up the `Manage Own Integrations [manage-own-integrations]` permission into manage own incoming and manage own outgoing integrations.

### Actual behavior:

See `Manage Own Integrations [manage-own-integrations]` permission. Only none or both webhooks can be allowed to be managed by the user.

### Server Setup Information:

- Current Version <= 0.74

**Comment by reetp** [comment]
This is a NFR and general policy is to open this in the forums for discussion.
It undoubtedly has merit so will leave open pending a decision by a dev.

**Comment by ovi-hutu** [comment]
+1

**Comment by reetp** [comment]
@rocket-cat label add "Feature: Request"
