### ISSUE TITLE
E2E Encryption button has word stem "save", which confuses into clicking it to save the password, but the result then is the password is not saved anywhere and forgotten.

### ISSUE THREAD

**Issue by mindey** [RocketChat/Rocket.Chat#13267]
### Description:

![](https://rocket.chat/docs/user-guides/end-to-end-encryption/e2e-alert.png)

### Steps to reproduce:

1. Go to: https://<rocket-chat>/admin/E2E%2520Encryption
2. Click that button, without viewing the rest of text.
3. Then, next time, you log-in say, from another browser session, you've got no way of getting back to encryption:
![](https://wiki.mindey.com/shared/shots/7cfb97184592423af5598a9fa.png)

### Expected behavior:

I'd expect to actually have the window, that has button "Select All", and let the user copy-paste it to their password manager, or wherever they need.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
