### ISSUE TITLE
Notification private and public chats and other questions

### ISSUE THREAD

**Issue by vdvas** [RocketChat/Rocket.Chat#13263]
### Description:

1) In private channel and public channel dont work notification and popup in desktop application and mobile app.
Notification about private message are work.
Settings of each private& public channel of notification are enabled.
2) How i can settings up notification to rocket chat app a incoming email of some mail provider? Can i use webhook?  The mailbox that must check is users mailbox. I use mail provader mail.ru.
3) How i can view , find and analyze all users message private and public chats? I need piwik integration or other?

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Ubuntu Server 18.04
- Deployment Method: snap
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3 - x64
- MongoDB Version:

**Comment by reetp** [comment]
This seems to be a setup/support issue and no evidence of a bug.
Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
Thank you.

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug

Please reopen if you have evidence of an actual bug.
