### ISSUE TITLE
Docker tag develop: commit regression

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#13264]
### Description:

The develop tag seems to have regressed to a much older commit than what it was recently at. This has reintroduced several issues that have already been fixed, including  #13138. I noticed this when the rocketchat instance started failing with the same error as outline in the issue. When I checked the commit for the version, I noticed that it was at commit dc0d7398c1, which is dated Jan 10, 2019. The issue was corrected on commit a8f26bc, dated January 14, 2019.

Is this a common thing, where the develop tag goes back commits?

### Steps to reproduce:

1. Pull the latest rocketchat/rocket.chat:develop image
2. Check the commit hash.

### Expected behavior:

Should contain a far more recent develop comit. I understand not necessarily the latest one, as builds do take time, but not a commit from Jan 10.

### Actual behavior:

And old commit which reintroduces breaking issues is being loaded.

### Server Setup Information:

| Version                 | 0.74.0-develop                                            |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 137                                                       |
| Database Migration Date | Fri Jan 25 2019 07:08:18 GMT-0600 (Central Standard Time) |
| Installed at            | Tue Jul 03 2018 10:28:32 GMT-0500 (Central Daylight Time) |
| Uptime                  | 1 hours, 16 seconds                                       |
| Deployment ID           | wecGmPkstnsm2e7ge                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | **dc0d7398c1ed965ebf9a72deef3e3ac42c3262e2** |
| ------- | ---------------------------------------- |
| Date    | Thu Jan 10 20:10:03 2019 -0200           |
| Branch  | develop                                  |
| Tag     | 0.73.0                                   |
| Author  | Marcos Spessatto Defendi                 |
| Subject | Rocketchat mailer (#13036)               |

### Runtime Environment

| OS Type         | Linux                                    |
| --------------- | ---------------------------------------- |
| OS Platform     | linux                                    |
| OS Arch         | x64                                      |
| OS Release      | 4.15.0-43-generic                        |
| Node Version    | v8.11.4                                  |
| OS Uptime       | 11 days, 16 hours, 37 minutes, 9 seconds |
| OS Load Average | 0.21, 0.38, 0.38                         |
| OS Total Memory | 7.79 GB                                  |
| OS Free Memory  | 421.66 MB                                |
| OS CPU Count    | 4                                        |

### Build Environment

| OS Platform  | linux                    |
| ------------ | ------------------------ |
| OS Arch      | x64                      |
| OS Release   | 4.4.0-141-generic        |
| Node Version | v8.11.4                  |
| Date         | January 24, 2019 6:55 PM |

**Comment by bkraul** [comment]
Luckily I backed up the develop image with the fix to my own docker registry, and was able to get back on track, but this is an interesting situation. :)

**Comment by bkraul** [comment]
Anything on this?

**Comment by bkraul** [comment]
@sampaiodiego @MarcosSpessatto , any thoughts on this situation?

**Comment by bkraul** [comment]
Let me push the backup image I made of the image with the fix to my hub space. Again, the only one I have is from commit a8f26bc which fixes the rooms not loading issue. I am actually trying to figure out how to build my own image from the develop branch, but so far I have not gotten any help from the forums. It is kind of weird that the team is completely silent. Maybe they are on a support freeze at the moment.

**Comment by sampaiodiego** [comment]
sry guys, I'm already taking a look on this.

**Comment by bkraul** [comment]
@jmoont you can pull image: [bkraul/rocket.chat:develop](https://cloud.docker.com/u/bkraul/repository/docker/bkraul/rocket.chat) . It should help until this is corrected. I have started a backup/testing environment to make sure the develop builds are usable before I implement them. This is the risk I understand I choose to take when trying to use a development branch, I'm fine with that. @sampaiodiego , thanks for looking into this.

**Comment by bkraul** [comment]
@jmoont Found a more recent one in my cache, dated Jan 22, with more fixes. It also works fine. I have updated the image, and have re-tagged the other one for archival purposes. Might keep 5 or so.

**Comment by sampaiodiego** [comment]
it's fixed guys.. it was an issue with our end-to-end tests that were preventing the whole process to finish: https://hub.docker.com/r/rocketchat/rocket.chat/tags/
