### ISSUE TITLE
Livechat for internal organization chat instead of support

### ISSUE THREAD

**Issue by tiagoefreitas** [RocketChat/Rocket.Chat#13272]
This was previous described in [One-on-one chat as a widget #6428 ](https://github.com/RocketChat/Rocket.Chat/issues/6428)

Basically the livechat interface with authentication and manual selection of chat instead of automated.

It would need to use the currently authenticated user instead of asking for name/email, and add an interface to choose the channel/user to chat with.

**Comment by reetp** [comment]
Please don't open a duplicate. There is an Issue that you have commented on. Please stay on that.

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
@rocket-cat close
Closing in favour of #6428
Please follow up there.
