### ISSUE TITLE
RESTAPI: missing add/remove leader

### ISSUE THREAD

**Issue by Montel** [RocketChat/Rocket.Chat#13288]
In last version we don"t have rest api for adding/removing leader role:

We have method for adding/removing Moderator/Owner role but not leader.

I think that we need code as:
```javascript
RocketChat.API.v1.addRoute('channels.addLeader', { authRequired: true }, {
        post() {
                const findResult = findChannelByIdOrName({ params: this.requestParams() });

                const user = this.getUserFromParams();

                Meteor.runAsUser(this.userId, () => {
                        Meteor.call('addRoomLeader', findResult._id, user._id);
                });

                return RocketChat.API.v1.success();
        },
});

RocketChat.API.v1.addRoute('channels.removeLeader', { authRequired: true }, {
        post() {
                const findResult = findChannelByIdOrName({ params: this.requestParams() });

                const user = this.getUserFromParams();

                Meteor.runAsUser(this.userId, () => {
                        Meteor.call('removeRoomLeader', findResult._id, user._id);
                });

                return RocketChat.API.v1.success();
        },
});
```
Regards.

**Comment by ggazzo** [comment]
hey @Montel looking your snippet seems you are in the right path, why not open a pull request? feel free to open and we can help you to merge it :)

**Comment by Montel** [comment]
I can try to make a pull request tomorrow.
I need it for my rocketchat client (kde - ruqola)

I will do it tomorrow

**Comment by MarcosSpessatto** [comment]
@Montel I think you opened the PR only in your fork, you should open the PR and choose as the target branch: `RocketChat:develop` and not the develop branch of your fork. :sweat_smile: Can you please fix it?

**Comment by Montel** [comment]
Ah !
Sorry I didn't use a lot github :) I will try to fix it soon :)

**Comment by MarcosSpessatto** [comment]
No problem :)

**Comment by Montel** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/13314

it seems that I need to add some reviewer but I don't know who (and how :) )

**Comment by MarcosSpessatto** [comment]
I'll do that. :)

**Comment by Montel** [comment]
oops sorry I wanted to update my patch and it closed it...
I recreated a new one:
https://github.com/RocketChat/Rocket.Chat/pull/13315

I hope that it'"s ok.
