### ISSUE TITLE
Make the channel description a textarea

### ISSUE THREAD

**Issue by Kjarrigan** [RocketChat/Rocket.Chat#13285]
Expressing the purpose of a channel in a single line without any line breaks isn't always possible and quite ugly. So please make it a `textarea` instead of an text `type=input`

If I change my local html via Browserdevtools it works out of the box - so you guys are already saving and displaying newlines correctly - I just can't type them without a little hack.

**Comment by savish28** [comment]
@ggazzo please review #13434

**Comment by savish28** [comment]
@ggazzo  I have done the required changes discuused in #13434  and opened a new PR. Please review PR #13455. Thanks.

**Comment by savish28** [comment]
@ggazzo Please final review #13455.
