### ISSUE TITLE
[sandstorm] Users are not prompted to log in

### ISSUE THREAD

**Issue by maurer** [RocketChat/Rocket.Chat#1328]
Under sandstorm, when a non-logged in user goes to a rocket chat grain for the first time, they just see a blue screen, and nothing else. What they need to do is click the login button in the upper right of the screen. There should be a visual hint to direct them to this.

**Comment by Sing-Li** [comment]
@maurer  thanks for the report.  Great idea.  Right now we render a blank blue page, but we certainly could create a consistent UI  to block-arrow-direct user to login - perhaps explaining that they're a guest on a shared grain.

Please prefix all future reports with [sandstorm] - thanks again.

**Comment by mnutt** [comment]
Guest access would be great, but as a initial step, maybe just show a message like "sharing is disabled for this app"? I thought something was broken before I eventually viewed source and saw the message.
