### ISSUE TITLE
rockect chat can not connect documentDB in aws server

### ISSUE THREAD

**Issue by jerryline** [RocketChat/Rocket.Chat#13298]
We want to use aws document DB replace MongoDB, but can not connect to it.I want to know can I install rocketchat this way? I have tried to connect document DB with command line, and can connect it successfully,
This is the command I used:
mongo --ssl --host docdb-XXXXXXXX.cluster-XXXXXXXx.us-east-1.docdb.amazonaws.com:27017 --sslCAFile /home/ec2-user/rocketbot/rds-combined-ca-bundle.pem --username XXX --password XXXXXX.

but the rocketchat can not connect the DB with this:
export MONGO_URL="mongodb://XXX:XXXXXX@docdb-2019-01-31-08-05-07.cluster-ceoagn69e6zx.us-east-1.docdb.amazonaws.com:27017/?ssl_ca_certs=/home/ec2-user/rocketbot/rds-combined-ca-bundle.pem&replicaSet=rs0"

**Comment by geekgonecrazy** [comment]
Might be worth reaching out to aws on this one.  I’m not sure how that would translate to a connection string.

We only officially support mongo.  Feel free to open a topic in our forum.  Maybe others in community have an idea

**Comment by appelmoesje** [comment]
I also would like to use AWS DocumentDB for our Rocket Chat. Tried the same thing @jerryline did but didn't work. I got errors like "namespace name generated from index name is too long". 

I thought AWS DocumentDB uses MongoDB 3.6 and all the applications you can use on Mongo you also can uses on AWS DocumentDB, but that isn't the case.

Did you find a solution for using AWS DocumentDB on Rocket Chat? @jerryline

**Comment by geekgonecrazy** [comment]
Documentdb is basic mongo compatible but does not actually implement all of the features.  We use some of mongos features that I cannot see aws implementing for documentdb.  Like oplog. 

You might manage to hack it together... but it’s not really mongo so your job administering it would likely always be higher and more prone to breaking
