### ISSUE TITLE
Every instance of Rocket Chat on Windows 7 opens 3 processes in the background

### ISSUE THREAD

**Issue by navneetap** [RocketChat/Rocket.Chat#1329]
Everytime RocketChat Windows application is started, it starts 3 processes in the background which do not stop even when you quit the app.
if you open RocketChat the second time, 3 mroe processes start, which then continue to run until maunally ended.

Replicate the issue on Windows 7 - 
1. Start RocketChat the first time.
2. Open Task Manager -> Processes -  3 Rocket.Chat.exe processes.
3. Quit RocketChat
4. Check TaskManager -> Processes -  3 Rocket.Chat.exe processes.
5. Start RocketChat again.
6. Check TaskManager -> Processes -  6 Rocket.Chat.exe processes.

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15652675/10940367/3e2c22d0-8306-11e5-8ba2-6f7e292da691.png)

![image](https://cloud.githubusercontent.com/assets/15652675/10940373/4251b49c-8306-11e5-95c1-5789e4615736.png)

**Comment by Sing-Li** [comment]
Core team members still running on Windows are a dying breed.  i know of at least one who would rather not acknowledge it. :-)

Seriously.  Thanks for the report, @navneetap

**Comment by geekgonecrazy** [comment]
This looks to be for the desktop app?  Might should direct those over at https://github.com/rocketchat/rocket.chat.electron

**Comment by engelgabriel** [comment]
@navneetap I'll update the windows binaries with the latest version so you can try again tomorrow.
If the bug persists, please open an issue on the https://github.com/rocketchat/rocket.chat.electron project
