### ISSUE TITLE
Cannot create a channel with a name in Russian

### ISSUE THREAD

**Issue by layman48** [RocketChat/Rocket.Chat#13296]
### Description:

It is impossible to create a channel with a name in Russian in the desktop clients and in the web browsers.

### Steps to reproduce:

1.  Go to "Create a New Channel"
2. In the "Channel Name" field I enter a name in Russian "Тест" or "Тестовый канал"
3. After pressing the "Create" button nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Ubuntu Linux 16.04.3
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v8.11.3

In the server settings:

UTF8 Names Validation - "[0-9а-яА-Яa-zA-Z-_. ]+"
UTF8 Names Slugify - " True"
Allow Special Characters in Room Names -"True"

**Comment by cadetmsv** [comment]
**Add the field "Full name" to manually fill in the "fname" when creating the channel https://github.com/RocketChat/Rocket.Chat/issues/13019**

**The name of the rooms in channels and private groups in human readable form https://github.com/RocketChat/Rocket.Chat/issues/12638**
