### ISSUE TITLE
Cannot set new user Avatar via file upload

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#13295]
### Steps to reproduce:

1. I load the avatar in the user, the photo appears but when saved it disappears

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.0
- Operating System: Debian 9.7
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v8.11.3
- MongoDB Version: db version v3.6.10

**Comment by tassoevan** [comment]
Related to #12098

**Comment by Brade** [comment]
Same issue. And I notice this is an ongoing problem with rocketchat. I just installed today on my own server. Even gravatar doesn't work (I'm using the Mac client), so pretty sure it's not a local permissions issue.

**Comment by Brade** [comment]
FYI mobile app seems to reflect the avatar correctly, so might just be a desktop issue.

**Comment by aimerbois** [comment]
I have the same issues, avatar just gone after uploaded and refresh. 
Look good on mobile app

**Comment by oguhpereira** [comment]
What browser did you use?

I tested in my chrome in [Rocket.chat open Server](https://open.rocket.chat/)

and no problem, I think it was fixed in the latest version.

**Comment by tassoevan** [comment]
I'll close this issue by now, but feel free to reopen it if this bug comes back.
