### ISSUE TITLE
User friendly search

### ISSUE THREAD

**Issue by joafalves** [RocketChat/Rocket.Chat#13292]
### Description:

The presence of accent in names should not be considered while using the user search function.

### Steps to reproduce:

1. Have contacts with accent in names (Such as "André")
2. Search for "andre" on the search box

### Expected behavior:

André contact should be listed

### Actual behavior:

André contact is not listed 

### Server Setup Information:

- Version of Rocket.Chat: 2.14.7

**Comment by reetp** [comment]
First please fill out a bug template.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Second I'm not exactly sure how you would think this would work?

é is not the same as e or è or ê or any other variation of the letter.

Additionally you would then also have to search on all variations of each lettter eg o ő ø ö etc. And then that would have to be considered for every language say Chinese.....

In any event you can use regular expressions with wildcards. Learning to use them may be your best solution.

Last, there is no evidence tgat Rocket is actually broken so this is really a new feature request and should be opened in the forums.

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close

**Comment by joafalves** [comment]
All modern chat applications take this variations into account, it's not an uncommon feature. Just take a look at Skype, FB messenger, WhatsApp. They all do the same.

In programming, the term is mostly known as accent insensitive search.
