### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by sushantbansal90** [RocketChat/Rocket.Chat#13307]
I have followed each and every step here 
https://rocket.chat/docs/administrator-guides/notifications/push-notifications/
But still d'nt getting the push notification...

**Comment by reetp** [comment]
Please fill in a bug template properly  or no one can help you.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Thank you.

**Comment by geekgonecrazy** [comment]
Closing since no follow up happened here
