### ISSUE TITLE
Can`t send message with text "string"

### ISSUE THREAD

**Issue by banoleb** [RocketChat/Rocket.Chat#13300]
Hi, to all
Today i discovered a very strange bug.
Description:
I can not send a message with the text "stri" "string" or "str" + any letter

![123](https://user-images.githubusercontent.com/47217865/52062090-ea646380-2580-11e9-9433-b2ed36a3d3c4.png)

Server Setup Information:
Version of Rocket.Chat Server: 0.73.2

LOG:
`Exception while invoking method 'sendMessage' { BulkWriteError: assertion src/mongo/db/storage/mmap_v1/btree/key.cpp:612     at OrderedBulkOperation.handleWriteError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1048:11)     at resultHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:159:23)     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   index: 0,   code: 8,   errmsg: 'assertion src/mongo/db/storage/mmap_v1/btree/key.cpp:612',   op:     { _id: 't59iXjYsuQfu8rDRS',      rid: 'cn75WaqikewweBLmKzvMwH6FXHKXKKmcPN',      msg: 'stri',      ts: 2019-01-31T14:53:22.351Z,      u:        { _id: 'zvMwH6FXHKXKKmcPN',         username: 'aleksandr.oliferuk',         name: 'Aleksandr Oliferuk' },      _updatedAt: 2019-01-31T14:53:22.371Z,      editedBy: undefined,      editedAt: undefined,      emoji: undefined,      avatar: undefined,      alias: undefined,      customFields: undefined,      groupable: undefined,      attachments: undefined,      reactions: undefined,      mentions: [],      channels: [] },   name: 'BulkWriteError',   driver: true,   err:     { index: 0,      code: 8,      errmsg: 'assertion src/mongo/db/storage/mmap_v1/btree/key.cpp:612',      op:        { _id: 't59iXjYsuQfu8rDRS',         rid: 'cn75WaqikewweBLmKzvMwH6FXHKXKKmcPN',         msg: 'stri',         ts: 2019-01-31T14:53:22.351Z,         u: [Object],         _updatedAt: 2019-01-31T14:53:22.371Z,         editedBy: undefined,         editedAt: undefined,         emoji: undefined,         avatar: undefined,         alias: undefined,         customFields: undefined,         groupable: undefined,         attachments: undefined,         reactions: undefined,         mentions: [],         channels: [] } },   result:     BulkWriteResult {      result:        { ok: 1,         writeErrors: [Array],         writeConcernErrors: [],         insertedIds: [Array],         nInserted: 0,         nUpserted: 0,         nMatched: 0,         nModified: 0,         nRemoved: 0,         upserted: [],         lastOp: [Object] } },   [Symbol(mongoErrorContextSymbol)]: {} }`

**Comment by ggazzo** [comment]
@banoleb do you know what version of mongo are you using, are you using docker/snap? please give us more information (and try to follow the bug report template issue) thanks :)

**Comment by banoleb** [comment]
@ggazzo hi,
sorry,The first time I write a report, I'll keep it on mind

- Version of Rocket.Chat Server: 
- Operating System: Debian GNU/Linux 9.6 (stretch)
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 3.2
Version of Rocket.Chat Server: 0.73.2 
the problem was before on the version 0.72

**Comment by reetp** [comment]
The documentation refers to the Cordova app which as far as I am aware is now EOL and unsupported.

Does this apply to the new Kotlin/React apps? Should the documentation be updated?

**Comment by sampaiodiego** [comment]
this doesn't seem to be related to Rocket.Chat. There is nothing on the app preventing that.

I have found this looking for this error on google:

https://jira.mongodb.org/browse/SERVER-22678?focusedCommentId=1179270&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1179270

your error is not related to gridFs but I think worth trying the "fix", try a `reIndex` and a `repairDatabase` described on the link.. please let us know if that fixes your issue.

**Comment by banoleb** [comment]
HI,
Thanks you. reindexing helped me.
I used this code:

db.getCollectionNames().forEach(function(coll_name) {
  var coll = db.getCollection(coll_name);
  coll.reIndex();
});

**Comment by sampaiodiego** [comment]
good to hear @banoleb :rocket:
