### ISSUE TITLE
Read Receipt for Livechat Messages is not showing information of livechat-guest

### ISSUE THREAD

**Issue by rohitmyaim** [RocketChat/Rocket.Chat#13302]
Rocketchat Version : 0.73

Steps to Reproduce
1. Enable Showing Detailed Message Read Receipts 
2. Start Livechat as a guest from any website having livechat script installed.
3. See the Read Receipt of that livechat message.
4. livechat-guest info is missing whereas it is fine for a RC user as per screenshot.

![screenshot-demotest1 rampwin com-2019 01 31-20-43-46](https://user-images.githubusercontent.com/5087134/52063857-69fe2c80-2599-11e9-8973-50489d513eeb.png)

**Comment by knrt10** [comment]
On it, will like to fix this.
