### ISSUE TITLE
Bugs when installed inside a directory

### ISSUE THREAD

**Issue by facundomedica** [RocketChat/Rocket.Chat#13309]
I've installed Rocketchat and I access it inside a folder (mydomain.com/rocketchat) and I've noticed a couple of things that are not okay.

1. When quoting the user image isn't shown (the url is wrong)
<img width="302" alt="screen shot 2019-01-31 at 18 55 24" src="https://user-images.githubusercontent.com/14063057/52077808-cbb69a80-2589-11e9-88bd-7c8f53829880.png">

The image url is: `https://mydomain.com/rocketchat/rocketchat/avatar/facundo?_dc=0` (Notice double rocketchat).

2. In the console there are some 404
<img width="807" alt="screen shot 2019-01-31 at 18 57 06" src="https://user-images.githubusercontent.com/14063057/52077996-17694400-258a-11e9-9c05-669a908b4050.png">

It's trying to get `https://mydomain.com/api/apps/languages`

Version: 0.73.2

**Comment by ura14h** [comment]
That's same issue to:
- #11924 channel avatar is not shown when Rocket.Chat is running in subdir
- #10732 Wrong permalink when running RocketChat in subdir

**Comment by facundomedica** [comment]
Ok, clearly a duplicate, sorry!
