### ISSUE TITLE
Internal hubot broken

### ISSUE THREAD

**Issue by lennartgrunau** [RocketChat/Rocket.Chat#13317]
1. 

### Description:

The internal Hubot is broken after the update to 0.73.2. It does not load any scripts and doesn't log anything at all.

### Steps to reproduce:

1.  Go to Settings -> Internal Hubot
2.  Add some custom scripts
3.  Click Save
4. Go To Settings -> View Logs
5. See that nothing has been logged
6. Test you scripts

### Expected behavior:

 Something in logs and working scripts

### Actual behavior:

 No logs, no working scripts

### Server Setup Information:

- Version of Rocket.Chat Server:  0.73.2
- Operating System: Ubuntu 16.04.4 LTS
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: as shipped with snap
- MongoDB Version: as shipped with snap

### Relevant logs:

No relevant logs

**Comment by jasonfah** [comment]
Same for us. We ended up converting our hubot scripts to an app.

AFAIK it's being encouraged that you move away from the internal hubot and look at Apps or external hubot.

**Comment by lennartgrunau** [comment]
@jasonfah The Problem is we're using the internal hubot to react to DMs between other People, not to the bot itself. The Rocketchat Hubot Adapter can't to that. If you got a solution for this, I'd happily give it a try.

**Comment by jasonfah** [comment]
Could you tell us a little about what your hubot scripts were doing. Have you looked at the new app framework? Maybe it can do what you need.

**Comment by jasonfah** [comment]
That seems like it should be possible with the new app framework. Documentation is a bit hit and miss but the best advice I can give is to go to the marketplace and download a few apps. You can then unzip them and take a look at the source.

Maybe a slash command would work for you guys? The user could type /meeting and the app would do a http request to generate a new meeting/conference and posts the message to the channel.

Links:
https://github.com/RocketChat/Rocket.Chat.Apps-cli
https://rocketchat.github.io/Rocket.Chat.Apps-engine/classes/app.html
https://rocket.chat/marketplace
https://github.com/RocketChat/Rocket.Chat.Apps-engine

**Comment by lennartgrunau** [comment]
Hi, sorry for the late reply. That seems to be a bit overkill for whats essentialy like 4 lines in coffeescript, doesn't it? Nevertheless, I'll check it out. Thanks.

**Comment by jasonfah** [comment]
The cli does all the heavy lifting by generating the app for you. You may find you only need to add just as many lines of code for the app.

I agree with you though. The internal hubot was really handy for quick simple bot scripts. It's a shame that it just stopped working. Out rocket.chat server updated over the weekend to 0.74. I haven't checked yet if it's been fixed or not.

**Comment by lennartgrunau** [comment]
After reading a metric ton of documentation, unpacking dozens of already existing apps and wrapping my poor sysadmin brain around typescript I was able to recreate the coffeescript bot with the apps framework. Thanks @jasonfah for pointing me in the right direction. 

The internal hubot needs to be fixed, nevertheless.

**Comment by reetp** [comment]
"The internal hubot needs to be fixed, nevertheless."

I think the general direction of travel is to remove the internal hubot in time. So it is unlikely to get fixed.

I think the devs are trying to move as many bits as possible outside of core RocketChat functionality hence Apps etc etc. as per the comment above from @jasonfah.

**Comment by lennartgrunau** [comment]
Since the internal hubot has been removed from rocketchat, I'll close this issue. See  #13522.
