### ISSUE TITLE
Force_SSL Setting redirect loop, can't set the setting in mongodb (not found)

### ISSUE THREAD

**Issue by F-Locos** [RocketChat/Rocket.Chat#13319]
Hello guys!

### Description:
It's simple, I'm encoutered this problemafter enabled the Force_SSL setting like this issue : https://github.com/RocketChat/Rocket.Chat/issues/1968

It's wrote on the topic, to execute this command in the mongo db server : 
`db.rocketchat_settings.update({ _id: "Force_SSL" }, { $set: { value: false } });`
But gave me : 
`WriteResult({ "nMatched" : 0, "nUpserted" : 0, "nModified" : 0 })`

The message is clear, no match, no update. Where should I found the right setting ID ? 

I can't say more thing about my RocketChat server, because I can't access to it now... 
If you can help me, I'll be the most happy man ! 👍 

Thanks for reading

**Comment by F-Locos** [comment]
Ok, so simple.
I forgot to enter in the rocketchat database.

Just do : 
- use rocketchat
and
-  db.rocketchat_settings.update({_id:"Force_SSL"}, {$set: {value: false}})

**Comment by swares** [comment]
Thanks for your post !  It was just what I needed.
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })

:)

**Comment by csitea** [comment]
run straight from the OS  shell
`mongo rocketchat --eval 'db.rocketchat_settings.update({_id:"Force_SSL"}, {$set: {value: false}})'`

**Comment by karlosgaldino** [comment]
Pessoal, boa noite. Fiz o procedimento acima, mas não executou nada. Ao executar show database ele não exibe uma database chamada rocketchat. Exibe apenas: admin, contigo, local e parties. Acredito que por isso não funcione. Eu instalei via linha de comando, não sei se isso interfere: anão install rocketchat-server.
