### ISSUE TITLE
Client issue with chat leader banner

### ISSUE THREAD

**Issue by vddmvddm** [RocketChat/Rocket.Chat#13313]
### Description:

Can`t close the description of user in chanel because of leader banner. It happens only in client version, in browser works correctly.
Version of client 2.14.7

### Steps to reproduce:

1. In chanel click on someones login for detailed info
2. Scroll up in message history
3. Banner of chat leader will hide cross sign recently opened icon in detailed info about user.

### Expected behavior:

To be able to close the datailed info abou user.

### Actual behavior:
![screenshot 71](https://user-images.githubusercontent.com/28955375/52114726-77f19300-2615-11e9-925e-2af7ba30a246.png)
![screenshot 70 _li](https://user-images.githubusercontent.com/28955375/52114744-83dd5500-2615-11e9-9271-448e2ff753cc.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Linux 
- Deployment Method: manual
- Number of Running Instances: 5
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/14443 ;)
