### ISSUE TITLE
Message delete does not remove message from other clients until F5 refresh

### ISSUE THREAD

**Issue by s7726** [RocketChat/Rocket.Chat#13324]
### Description:
Similar to #7182
Deleted messages are still visible to other clients until they F5 refresh or otherwise reload the page.
Editing a message, does result in immediate update of the message content. I would expect delete to update immediately as well.

### Steps to reproduce:

User enters text and sends the message.
User deletes message.
Message does not delete from the screen of other users.

### Expected behavior:

Message is immediatly (subject to connection and network delay) removed from all clients.

### Actual behavior:

Deleted Message persists until page reload.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.4
- Operating System: linux
- Deployment Method: Container
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

Has been the behavior for at least a few versions

**Comment by Shaverdoff** [comment]
Firtst of all - update the RC server - is 0.7.4.1 already. 
Second - Test you issues. I sure you cant see that bug again.

**Comment by MarcosSpessatto** [comment]
@s7726 can you please update your server version and try again?

**Comment by s7726** [comment]
Confirmed newer version fixes the issue.
