### ISSUE TITLE
Mobile web not responsive on Android

### ISSUE THREAD

**Issue by tiagoefreitas** [RocketChat/Rocket.Chat#13325]
### Description:

On Android Chrome/Firefox it shows the desktop version always instead of mobile responsive ui.
Tried on 2 different phones and also happens with open.rocket.chat

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.0
- Operating System: Android 6
- Deployment Method: docker

**Comment by tiagoefreitas** [comment]
I have to use the browser on android because none of the android apps work with custom oauth currently.

**Comment by reetp** [comment]
Can you be more specific about which device you are using and post a screenshot?

**Comment by melanierieback** [comment]
I'm having the same problem.   I have a Samsung phone w/ Chrome on Android.

**Comment by tiagoefreitas** [comment]
Mine is a Motorolla Moto G5S, but I tested several and appears to happen in all of them...

**Comment by reetp** [comment]
If you appear to have this Issue you need to be specific about OS version and browser.

Just saying 'me too' does not help.

Please also test in a couple of browsers as well.

**Comment by Sing-Li** [comment]
Same thing observed with Android 8.0.0 with Chrome on Sony Xperia.

However,  @tiagoefreitas  @melanierieback   -- what it the UI gives you the clue that it is the non-responsive layout.   Is the browser

(a)  "Shrinking everything - including the messages displayed  - up to display the entire screen"   .... or
(b)  are you seeing only a CLIPPED corner of a full screen?

Please supply a screen capture if possible.

**Comment by tassoevan** [comment]
It should be working fine on 0.74.1.

**Comment by tiagoefreitas** [comment]
Confirm its fixed for me on 0.74.1

**Comment by Sing-Li** [comment]
@melanierieback confirmed fix 0.74.1 via john ... closing.

**Comment by sinteur** [comment]
(update on melanie's problem - the update to 0.74.1 fixed it)
