### ISSUE TITLE
Auto-provision Channel via REST bulk/createRoom API

### ISSUE THREAD

**Issue by capensisma** [RocketChat/Rocket.Chat#1332]
Hello all,

I am very into Meteor and Rocket.Chat, right now I am in the middle of a task to auto-provision Channel via REST bulk/createRoom API, however I am getting a "You do not have permission to do this." REST response.

Looks to me this would be role/permission related, so would you kindly let me know 
1) how to assign the [testagent, adminautomation] roles to a given user? 
2) which data store does that role/user association info gets persist to?
3) Is there a quick fix for this?

Thank you :)

**Comment by capensisma** [comment]
@geekgonecrazy any news bro ? :)

**Comment by capensisma** [comment]
@geekgonecrazy @Sing-Li Thanks :)

**Comment by capensisma** [comment]
Hey You closed this? is this fixed ?? and working now? can clone the repo and try it now??


Thanks a  lot :)

**Comment by rwakida** [comment]
@capensisma yes, the changes have been merged into master.  The executing user must be logged in AND have a role with the correct permission(s)
- /bulk/register - 'bulk-register-user' permission
- /bulk/createRoom - 'bulk-create-channel' permission

Look at the, "Adding permissions for the caller", section in the REST API wiki for instructions on associating a user with a permission. 
https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs

**Comment by capensisma** [comment]
Thank you so much guys great work :) love it 

Thanks @geekgonecrazy @rwakida
