### ISSUE TITLE
Anonymous form by default

### ISSUE THREAD

**Issue by netsliver** [RocketChat/Rocket.Chat#13337]
Hello,
I would like to propose an "anonymous" chat where the user enters his login at the opening instead of having to register or authenticate.

The anonymous reading / writing is not enough because in this case we arrive on the list of channels, I want the user to be directed immediately on the choice of the pseudo with the same content elements as on the login page.

Regards

**Comment by reetp** [comment]
As per this all New Feature Requests should be opened in the forums for discussion.

http://rocketchat.github.io/docs/contributing/reporting-issues/

**Comment by reetp** [comment]
@rocket-cat label add "Feature: Request"

**Comment by reetp** [comment]
@rocket-cat close
