### ISSUE TITLE
Livechat API livechat/agent.next/:token always throwing error of Invalid token

### ISSUE THREAD

**Issue by rohitmyaim** [RocketChat/Rocket.Chat#13341]
The above API always throws eror of invalid token

There is a issue in code which I have identified.

```
                        const room = findOpenRoom(token);
			if (room) {  ==> It should be !room
				throw new Meteor.Error('invalid-token');
			}
```

**Comment by reetp** [comment]
Please fill out a bug template as per this:

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Have you tested on the latest 0.74.1 ? If not then please do so.
