### ISSUE TITLE
Dollar signs trigger Katex inside code block

### ISSUE THREAD

**Issue by eltian** [RocketChat/Rocket.Chat#13346]
### Description:

Whenever we try to include two or more dollar signs inside a code block (single or multi line), the katex formatting processes the code.

### Steps to reproduce:

1.write  \`\`\` $x $y \`\`\` and send the message

### Expected behavior:

the code shouldn't be formatted and instead show `$x $y` in a block code

### Actual behavior:
shows the content between the two dollar signs formatted like this: _x_ y
![screenshot-rocket 2019 02 04-17-07-09](https://user-images.githubusercontent.com/25929385/52234109-a2ef1780-289f-11e9-96dd-dab6bf729e6c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.2
- Operating System: CentOs 7

**Comment by fliptrail** [comment]
I am seeing to this right now

**Comment by fliptrail** [comment]
This isn't happening with me. Works correctly as expected

**Comment by fliptrail** [comment]
@knrt10 see this.

**Comment by knrt10** [comment]
@eltian try to update to latest version and check if the problem still persists. If not, feel free to close this issue.

**Comment by eltian** [comment]
Unfortunately, I can't update Rocket chat on my own. I'll wait until our IT team updates it and check if it works correctly. Thanks.
