### ISSUE TITLE
Being able to install Rocket.Chat using NodeJS v4 or v5

### ISSUE THREAD

**Issue by unquietwiki** [RocketChat/Rocket.Chat#1335]
The default instructions for installing Rocket.Chat use Node 0.10: which is now pretty dated, compared to the Hubot requirement for 0.12.x, and the recent re-merging of the Node team builds into versions 4.0 and 5.0. Attempting to upgrade a working system to use NodeJS 0.12 or 5, and rebuilding the app, appears to make it completely unusable.

https://github.com/nodesource/distributions#debinstall

If upgrading is not possible, then if I want to create Hubot scripts for use with this, I should create those on a separate VM that can run newer Node?

**Comment by capensisma** [comment]
I am using it with node 0.12.x and it's pretty stable :)

**Comment by unquietwiki** [comment]
How did your install compare to the instructions at https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker ?

**Comment by geekgonecrazy** [comment]
@unquietwiki it looks like meteor has some bugs with some of the newer versions of node.js

More info:
https://github.com/meteor/meteor/issues/5124

**Comment by unquietwiki** [comment]
Ah, good to know. So while that's getting cleared up, I could use https://github.com/RocketChat/hubot-rocketchat in a Docker container to get bot-functions going, no?

**Comment by geekgonecrazy** [comment]
@unquietwiki absolutely.  That's how I personally deploy both hubot and rocket.chat.  :)

**Comment by capensisma** [comment]
@unquietwiki @geekgonecrazy right :)

**Comment by engelgabriel** [comment]
I'll close this issue, as we are just waiting on Meteor to do it. There is not much we have to do on our side.

**Comment by unquietwiki** [comment]
Thanks everyone. Between your tips here & the guide that showed up at https://github.com/RocketChat/Rocket.Chat/wiki/Docker-Ubuntu-14.04-%2864-bit%29-VPS-with-Nginx-SSL-and-Hubot , I'm getting Hubot working. Let's see when the Meteor falls!
