### ISSUE TITLE
Feature request:  SEARCH  GLOBAL 

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat#13375]
GREAT FEATURE IF POSSIBLE 
![image](https://user-images.githubusercontent.com/2346208/52337467-6262db80-2a10-11e9-87d3-b2946892823e.png)
it also can be a "Global search button "
for example i need to search world  "originate" but i diont know in what channel it was 
so i go to a "Search" and it can  find out 

Sure  global search can be enabled  or disabled  in settings.
Thanks

**Comment by gregs007** [comment]
This is already in the code, though still beta as of 0.74.1. Administration >> Search >> Default Provider

**Comment by reetp** [comment]
@r0cket-vat close.

NFRs should normally be opened in the forums, but this in progress elsewhere.
