### ISSUE TITLE
Realtime API authentication problem

### ISSUE THREAD

**Issue by duszek94** [RocketChat/Rocket.Chat#13376]
Hi, I'm trying to make a research about Rocket.Chat Realtime API. First question. What is the "id" parameter that I have to send in every request? I thought that this is a "server_id" that I'm receiving in a response after websocket connection. Another problem is that I cannot authenticate to a server through Realtime API. Every time I'm getting a "User not found [403]" response message. Here is my request:

![image](https://user-images.githubusercontent.com/36196903/52338228-17de6080-2a0a-11e9-8b5b-21c043af39c7.png)

and response:

![image](https://user-images.githubusercontent.com/36196903/52338321-5f64ec80-2a0a-11e9-95fc-474db0c155a8.png)

I'm sure that I'm sending a valid credentials. What am I doing wrong?

And the last question, is there any way to modify websocket time of life?

Thanks for help

**Comment by FrankDaze** [comment]
You can create the ID on your own. Should be increments with each call that you do to the webserive.

To fix your problem, change "username":"username" to "username":"the_name_of_your_user"
