### ISSUE TITLE
Heroku one-click deploy didn't work 

### ISSUE THREAD

**Issue by nickeblewis** [RocketChat/Rocket.Chat#1337]
Hi All

Not sure if anyone else has come across this but when I tried out the Heroku one click deploy it fails. Let me take you through what I did first and then I will share the error that I have.

- Changed the App name to something of my own, it accepts it
- Set region to Europe
- Changed the root url so that it starts with my chosen app name
- Clicked on "deploy for free"

My logfile is as follows:

-----> Fetching set buildpack https://github.com/RocketChat/heroku-buildpack-meteor.git... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
#####                                                                      7.0%                                                    16.2%#############################                                            42.0%########################################                                  55.6%###################################################                       71.1%###############################################################           88.6%
Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/tmp/buildpack20151106-155-uwyy0f/meteor-4iax/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Bundling bundle
$ROOT_URL, if specified, must be an URL.
 !     Push rejected, failed to compile Node.js app

**Comment by geekgonecrazy** [comment]
@RocketChat/core who is our resident heroku expert?  I don't remember who actually added this.

**Comment by engelgabriel** [comment]
Did you read the following?

* ROOT_URL
IMPORTANT! Please replace <App Name> with the value provided on the top. This will be the full URL of your Rocket.Chat app.

**Comment by engelgabriel** [comment]
I just deployed https://gabchat.herokuapp.com using the button...

**Comment by engelgabriel** [comment]
This may be help in the future:
https://devcenter.heroku.com/articles/dyno-metadata-staging?preview=1

**Comment by engelgabriel** [comment]
@nickeblewis make sure you added  https:// to the beginning of you ROOT_URL

**Comment by engelgabriel** [comment]
I'll close thins in favor of https://github.com/RocketChat/Rocket.Chat/issues/1371
