### ISSUE TITLE
Notify when new message is arrived & Direct Message

### ISSUE THREAD

**Issue by lourdhuraju-p** [RocketChat/Rocket.Chat#1338]
Hi,

Need to know is there any APIs available to achieve the following
1. Send Direct Message to Individual instead sending to public rooms
2. Send Message to Private Groups
3. How to get notify when there a new message is received or real time messages.?

Basically we are trying from Javascript

Thanks

**Comment by graywolf336** [comment]
There is no rest api which supports those at the moment. The DDP might, but I have no experience with that. See: #1059

**Comment by lourdhuraju-p** [comment]
Thank you very much! Will wait for sometime for the required APIs support.
