### ISSUE TITLE
Running Rocket.Chat within a Digital Ocean Docker droplet

### ISSUE THREAD

**Issue by nickeblewis** [RocketChat/Rocket.Chat#1339]
I am trying to get a Docker (Digital Ocean) instance up and running and have followed the instructions as follows:

$ docker run --name db -d mongo --smallfiles
$ docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --env MONGO_URL=docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --env MONGO_URL=mongodb://mymongourl/mydb -d rocket.chat -d rocket.chat

I did change the localhost to my IP and the MONGO_URL to my own that is hosted on Compose.io

It runs when I hit my IP address, which is:

http://46.101.78.230

(Please try yourself)

and you will see that "please wait..." shows forever.

I noticed that in my log file there is an error of:

Exception in queued task: Error: [CustomOAuth: Options.serverURL is required and must be String]
    at CustomOAuth.configure (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:28:21)
    at Object.RocketChat.models.Settings.find.observe.added (packages/rocketchat_github-enterprise/common.coffee:19:22)
    at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
    at self.applyChange.added (packages/minimongo/observe.js:53:1)
    at packages/mongo/observe_multiplex.js:183:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Object.task (packages/mongo/observe_multiplex.js:177:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1

What could the issue be? I can provide a log file if you need it? 

Thanks,

Nick

**Comment by capensisma** [comment]
dude just don't install it manualy you will get into a lot of trouble just use [mupx](https://github.com/arunoda/meteor-up/tree/mupx) which makes use of Docker this is different from mup which doesn't support docker! 

with mupx it's one command and deploy it in less than 2mn ;)

**Comment by Sing-Li** [comment]
@nickeblewis  Your command lines:

````
$ docker run --name db -d mongo --smallfiles
$ docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --env MONGO_URL=docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://localhost --env MONGO_URL=mongodb://mymongourl/mydb -d rocket.chat -d rocket.chat
````
... looked like they are completely messed up.  Is this just a cut and paste problem, or did you actually used these command lines?

Also, if you are using an external mongo instance, you will not need the first command.

**Comment by nickeblewis** [comment]
@Sing-Li thanks and yes, something went awry with the copy and paste here. However your tip regarding the external MONGO_URL was of use, as I tried:

docker run --name rocketchat -p 80:3000 --env ROOT_URL=http://46.101.78.230 --env MONGO_URL=mongodb://root:<mypassword>@cockney.2.mongolayer.com:10088,cockney.3.mongolayer.com:10088/rocketchat?replicaSet=set-55571ff706d20877ff00102d -d rocket.chat

(using Compose.io as my data provider)

The site starts up but interestingly no graphics appear and when I try to register, it would seem as if it is not connecting with the database.

Yesterday I tried another method and that was to:

1. Create a Digital Ocean Docker instance
2. Git clone the Rocket codebase
3. Install docker-compose
4. Edit the YAML file
5. $ docker-compose up

That works and I am guessing that is a long term workable option?

I will also try out @capensisma option too, as that sounds good too. 

Closing this...

**Comment by Sing-Li** [comment]
@nickeblewis Thanks for following up.  Yes, the deployment method you described via our `docker-compose.yml` is one of the officially supported deployment methods.

Beware of any deployment methods that depend on a `git clone` and/or running `meteor` (either directly or indirectly), they are more suitable for developers who needs to modify code - and we may not be able to support such custom configuration.
