### ISSUE TITLE
Push notification not working: iOS

### ISSUE THREAD

**Issue by cuiying408** [RocketChat/Rocket.Chat#13392]
Hi,

I am new in Rocket.Chat and installed hosting server on AWS. Converted iOS certificates to pem files. I think I have to replace pem files with them on server but I can't find them on server.
Also, I saw **Certificates and Keys** in Administrator/Push page. What strings should I input? (APN Passphrase, APN Key, APN Cert, APN Dev Passphrase, APN Dev Key, APN Dev Cert...)

Thanks,

**Comment by reetp** [comment]
@rocket-cat close

This appears to be a support issue and not a bug in Rocket.Chat

Please ask in the forums https://forums.rocket.chat or https://open.rocket.chat #support
