### ISSUE TITLE
[snap] add option to mount media

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#13391]
Allow media plug so snaps can write to /media
Should be as easy as adding the removable-media plug: https://github.com/nextcloud/nextcloud-snap/blob/master/snap/snapcraft.yaml#L81 to our rocketchat-server part.

Then need to add something like this to the docs to tell people how to do it: https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#removable-media

**Comment by knrt10** [comment]
I would like to fix this

**Comment by sp2703** [comment]
I would like to contribute on this issue. Any points to refer to?

**Comment by geekgonecrazy** [comment]
This has been added for a while now: https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-add-option-to-mount-media

**Comment by Skinner927** [comment]
@geekgonecrazy I don't think it was ever merged?? It's not working on latest snap anyways. https://github.com/RocketChat/Rocket.Chat/pull/13591
