### ISSUE TITLE
Livechat missing events for operators online / offline

### ISSUE THREAD

**Issue by dazoot** [RocketChat/Rocket.Chat#13403]
### Description:

There are no events fired by Livechat when operators are available (at least one is online, not away / busy / invisible / offline) or not available (no operators online).

### Expected behavior:

I would expect the event to be triggered and documented in the Livechat API page:
https://rocket.chat/docs/developer-guides/livechat-api/

### Actual behavior:

No events available for online / offline.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.1
- Operating System: Debian 8
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 0.74.1
- MongoDB Version: v3.4.15

**Comment by renatobecker** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Livechat/pull/257.
