### ISSUE TITLE
Can't install on Ubuntu 14.04 : fiber module not found

### ISSUE THREAD

**Issue by VoidAndAny** [RocketChat/Rocket.Chat#1340]
I try to install rocket on a fresh Ubuntu, following this guide : 
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

At the step "npm install" it fail with the following error : 
```
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
/
> fibers@1.0.5 install /var/www/rocket.chat/bundle/programs/server/node_modules/fibers
> node ./build.js

module.js:338
    throw err;
          ^
Error: Cannot find module '/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/rocket.chat/bundle/programs/server/npm-debug.log
```

**Comment by rosehosting** [comment]
You need to install the 'build-essential' package.
> sudo apt-get install build-essential

**Comment by VoidAndAny** [comment]
Thank you, but build-essential is already installed.

```
$ sudo aptitude install build-essential
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

**Comment by rosehosting** [comment]
It seems that meteor requires Node 0.10.40

> nave usemain 0.10.40  # instead of 0.12.7

**Comment by capensisma** [comment]
No, it's not nodejs version or something! it's the symlink in the ubuntu!

Can you try running `node` and see if opens the nodejs console?

**Comment by VoidAndAny** [comment]
Unfortunately, it doesn't succeed : 
```
root [ rocket ] @ /var/www/rocket.chat/bundle/programs/server  # node --version
v0.10.40

root [ rocket ] @ /var/www/rocket.chat/bundle/programs/server  # npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
\
> fibers@1.0.5 install /var/www/rocket.chat/bundle/programs/server/node_modules/fibers
> node ./build.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/var/www/rocket.chat/bundle/programs/server/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/rocket.chat/bundle/programs/server
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

I notice something strange, why my node_modules directory is owned by my common user  ?
```
root [ rocket ] @ /var/www/rocket.chat/bundle/programs/server  # ll
total 1,1M
drwxr-x---  5 root   root   4,0K 06/11/2015 17:54 app/
drwxr-x---  4 root   root   4,0K 06/11/2015 17:54 assets/
drwxr-x--- 20 my_user my_user 4,0K 10/11/2015 12:36 node_modules/
drwxr-x--- 30 root   root   4,0K 06/11/2015 17:54 npm/
drwxr-x---  2 root   root    20K 06/11/2015 17:54 packages/
-r--r-----  1 root   root    10K 06/11/2015 17:54 boot.js
-r--r-----  1 root   root    192 06/11/2015 17:54 boot-utils.js
-r--r-----  1 root   root    110 06/11/2015 17:54 config.json
-r--r-----  1 root   root   3,4K 06/11/2015 17:54 mini-files.js
-r--r-----  1 root   root   2,9K 06/11/2015 17:54 npm-shrinkwrap.json
-r--r-----  1 root   root    469 06/11/2015 17:54 package.json
-r--r-----  1 root   root   1,1M 06/11/2015 17:54 program.json
-r--r-----  1 root   root    10K 06/11/2015 17:54 shell-server.js
```

(I try to delete it and when I launch npm install, it is re-created with the same ownership)

**Comment by VoidAndAny** [comment]
@capensisma sorry I didn't seen your answer before make mine.

node command works fine, it open a node console, node --version return the correct version of node (chosen with nave)

**Comment by VoidAndAny** [comment]
I retry today, on a fresh Ubuntu 14.04, no more success.

**Comment by geekgonecrazy** [comment]
@VoidAndAny try running `chmod -R 777 .` in the root of the Rocket.Chat folder.  If that throws error try prefixing with sudo.

**Comment by VoidAndAny** [comment]
Hello, 
it's ugly and it doesn't solve the problem.
So sad...

**Comment by VoidAndAny** [comment]
I try something ugly too but it works.
I installed fibers globally
```
npm install fibers@1.0.5 -g
```

Then copy directory containing fibers in local node_modules folder :
```
cp -ar /usr/lib/node_modules/fibers /var/www/rocket.chat/bundle/programs/server/node_modules/
```

Now npm install don't complain any more.

Why npm install can't install fibers locally (based on rocket.chat package.json file) ?

**Comment by engelgabriel** [comment]
This is more of a NodeJS and Meteor issue, so I'll close this issue and leave some links for future references:

http://stackoverflow.com/questions/33488456/meteor-up-error-when-deploying-to-digital-ocean-ubuntu-14-04
https://forums.meteor.com/t/meteor-nodejs-0-12/2769

**Comment by lkraider** [comment]
The whole cloud deploy system is broken because of this:
https://github.com/RocketChat/Deploy.to.Cloud/issues/36

**Comment by OlivierJM** [comment]
@VoidAndAny Thanks, installing fibers globally and moving those files from /lib solved my problem

**Comment by VoidAndAny** [comment]
Glad if it helped, personally I gave up Rocket chat, unstable, difficult (impossible) to upgrade...

**Comment by vills** [comment]
Solution that worked for me:
- add nodejs repository using command: `curl -sL https://deb.nodesource.com/setup | sudo bash -`
- install nodejs: `sudo apt-get install nodejs`
- .. continue with manual ..

**Comment by coderdiaz** [comment]
@vills Isn't working for me :(

**Comment by aaratn** [comment]
I have same issue on Ubuntu 16.04

Ubuntu Server:
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"`

`~/Rocket.Chat/programs/server$ npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
|
> meteor-dev-bundle@0.0.0 install /home/chatadmin/Rocket.Chat/programs/server
> node npm-rebuild.js


> fsevents@1.0.14 install /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/build'
  SOLINK_MODULE(target) Release/obj.target/.node
  COPY Release/.node
make: Leaving directory '/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/build'

> sauce-connect-launcher@0.13.0 postinstall /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/sauce-connect-launcher
> node scripts/install.js


> phantomjs-prebuilt@2.1.13 install /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1478486690929/phantomjs-2.1.1-linux-x86_64 -> /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Phantom installation failed { [Error: EACCES: permission denied, open '/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js' } Error: EACCES: permission denied, open '/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at writeLocationFile (/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/install.js:88:5)
    at nextTickCallback (/home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/kew/kew.js:47:28)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/npm-debug.log

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! This is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chatadmin/Rocket.Chat/programs/server/npm-debug.log`

**Comment by aaratn** [comment]
Fixed this issue by changing permissions of location.js

```chmod 644 /home/chatadmin/Rocket.Chat/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/phantomjs-prebuilt/lib/location.js```

**Comment by h-town** [comment]
rocketchat is a joke, as is the framework its built upon.  i've seen more stable development in copy-and-paste blockchain projects...and that ain't sayin' much.

**Comment by meteorplus** [comment]
@h-town do you even know how to code bro?

You know how many features in RocketChat even Slack doesn't have?

Have ever deployed a RocketChat on prod Server?

**Comment by fyngyrz** [comment]
> do you even know how to code bro?

The critical comments are fair; you're trying to defend the indefensible. The [developer deployment instructions](https://rocket.chat/docs/developer-guides/quick-start/) are woefully incomplete, the developer install is fragile, many dependencies are left unspecified and mysterious.

These are **not** the hallmarks of a great developer environment, and "knowing how to code" isn't a relevant prerequisite for trying to imagine what the missing documentation should say, and/or why some completely unexpected error is jamming up what should have been a perfectly smooth process.

If you want kudos for features and to encourage development, then it's perfectly reasonable for those on the sharp end to expect something that can install cleanly and run out of the git setup, no mods, no changes. If you don't, you _will_ get complaints, and they _will_ be justified.

**Comment by h-town** [comment]
> @h-town do you even know how to code bro?
moot point.  if i knew how to roll my own feature-rich web-based chat medium i wouldn't be here.

> You know how many features in RocketChat even Slack doesn't have?
interesting that you mention slack.  i convinced my users to switch from slack to the rocketchat server i stood up and i'm not sure any of them logged in more than once.  much to my chagrin we're back on slack, and i'm certain the only reason no one was particularly vocal about their dismissal of rocketchat was out of respect for the countless hours i spent trying to stand it up.

> Have ever deployed a RocketChat on prod Server?
after many hours of poking, prodding, twisting, turning, hacking, cracking, and temper tantrums...yes.  whereas i don't "code", per se, i have plenty of experience with deploying complex systems from start to finish.
