### ISSUE TITLE
Rocket.Chat crashes with "Error: spawn ENOENT" when trying to upload avatar

### ISSUE THREAD

**Issue by m00t** [RocketChat/Rocket.Chat#1341]
Hi! I am using Docker for running rocketchat. And having this in my log:
```
[methods] setAvatarFromService ->  userId: qb3KnPkXx9TGtMWZx contentType: image/jpeg service: gravatar

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by unquietwiki** [comment]
Try installing graphicsmagick on your OS. Had to do that for my setup.

**Comment by m00t** [comment]
Where should I install graphicsmagick? We use docker image `rocketchat/rocket.chat`. Also we can not reproduce this behavior at localhost and at neighbor server event if we load the same mongo dump.

**Comment by m00t** [comment]
Update here: this is something with settings. I try to track which value of which setting causes it.

**Comment by m00t** [comment]
After loading fresh database dump, everything is fine now, I can not reproduce this bug anymore, so I am closing it.

**Comment by GITchristoph** [comment]
> After loading fresh database dump, everything is fine now, I can not reproduce this bug anymore, so I am closing it.

Hi @anton-siardziuk 
Sorry to disturb but may I ask how you do this "after loading fresh database dump".
I have the same error and would like tonunderstand how you fixed this.

Thank you!

**Comment by anton-siardziuk** [comment]
Hi @GITchristoph ,

Sorry, it was 5 years ago, I don't remember anything about this issue.

**Comment by GITchristoph** [comment]
@anton-siardziuk 

Sorry and thanks for still coming back.
During my research yesterday I was not checking from what date your post initially was...
