### ISSUE TITLE
messageAttachment shows December 31, 1969 7:00 PM when null

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#13427]
### Description:
messageAttachment shows December 31, 1969 7:00 PM when null

### Expected behavior:

Don't show any date when time is null.

### Actual behavior:

<img width="841" alt="screen shot 2019-02-09 at 12 46 53 pm" src="https://user-images.githubusercontent.com/6295044/52524269-30988180-2c69-11e9-95ac-b44a2f3d1064.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.0-develop
- Operating System: OSX

**Comment by theundefined** [comment]
the same problem is when no real attachment is specified. Server - docker. Example json which show problem:
```
{
  "channel":"#channel",
  "attachments":[
    {
      "author_name": "ala"
    }
  ]
}
```
Shows:
![image](https://user-images.githubusercontent.com/7404069/52697810-896e5f80-2f72-11e9-9022-57e9b60992ce.png)
