### ISSUE TITLE
Dififuclty when using smtp

### ISSUE THREAD

**Issue by elcolie** [RocketChat/Rocket.Chat#13429]
I request using `mailgun` as an another easy way to shoot the email.

**Comment by reetp** [comment]
From what I can see, mailgun supports standard SMTP so should be compatible with Rocket.

If you want to see API access in Rocket then please open a Feature Request in the forums:

https://forums.rocket.chat/

**Comment by reetp** [comment]
@rocket-cat label add "Feature: Request"

**Comment by reetp** [comment]
@rocket-cat close
