### ISSUE TITLE
2 wiki page for the same thing

### ISSUE THREAD

**Issue by VoidAndAny** [RocketChat/Rocket.Chat#1342]
There is 2 pages describing the process for installing Rocket chat on Ubuntu : 
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-to-UBUNTU
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

Which one to follow ?
The section "Download Rocket.Chat" is different especially the content of environment variables : 

```
HOST=your_hostname.com
MONGO_URL=mongodb://localhost:27017/rocketchat
MONGO_OPLOG_URL=mongodb://localhost:27017/local
ROOT_URL=http://$HOST
PORT=3000
```
versus : 

```
HOST=http://your_hostname.com
MONGO_URL=mongodb://localhost:27017/rocketchat
MONGO_OPLOG_URL=mongodb://localhost:27017/local
ROOT_URL=http://localhost:3000
PORT=3000
```

(port or not in ROOT_URL, http or not on HOST)

Thanks

**Comment by emcguinness** [comment]
`HOST=someHostName`
Does not need http, this is the hostname of the machine. Needs to resolve in DNS, or more easily by updating your /etc/hosts file. For example add the line:
`127.0.0.1    someHostName`

MONGO_URL=mongodb://localhost:27017/rocketchat
MONGO_OPLOG_URL=mongodb://localhost:27017/local
Assuming you are running Rocket.Chat on the same server as mongo (which you are if you followed either guide) this is correct.

`ROOT_URL=http://someHostName:3000`
This is the URL your users will be accessing the server using, use whatever you would type in the browser. If for example you are using a SSL proxy this would change to `ROOT_URL=https://someHostName`. I should also point out this is less critical now, it is used on first run but after that you can control it from a setting in the admin settings. This is the `Site URL` under the general settings.

`PORT=3000`
This is the port you want rocket chat to run on. Keeping it at a high number allows you to run it without root. Putting it on a lower, more traditional, port such as 80 requires root.

**Comment by VoidAndAny** [comment]
Thanks for the precision, can we add them on wiki pages ?
And why 2 pages for the thing ?

**Comment by geekgonecrazy** [comment]
@VoidAndAny we'll try to consolidate these.  Sorry for the confusion

**Comment by geekgonecrazy** [comment]
@VoidAndAny all documentation has moved to: https://rocket.chat/docs edits / contributions to it may be made here: https://github.com/RocketChat/Rocket.Chat.Docs
