### ISSUE TITLE
rocket.chat not working behind Apache Reverse Proxy

### ISSUE THREAD

**Issue by Chessmasterrr** [RocketChat/Rocket.Chat#13432]
I tried to set up rocket.chat as following:
```
docker network create chat_network
docker run --name chat_mongo --restart=always --network chat_network -d mongo:latest
docker run --name chat_main --restart=always -p 3000:3000 -e MONGO_URL=mongodb://chat_mongo:27017/meteor -e ROOT_URL=https://chat.domain.de --network chat_network -d rocket.chat:latest
```

Setup Apache as reverse proxy as described [here](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/#running-behind-an-apache-ssl-reverse-proxy).
apache.conf:
```
<VirtualHost *:443>
        ServerName chat.domain.de
        ServerAdmin webmaster@domain.de
        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/chat.domain.de/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/chat.domain.de/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/chat.domain.de/chain.pem
        <Location />
                Order allow,deny
                Allow from all
        </Location>
        ErrorLog /var/log/apache2/error.log
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://localhost:3000/$1 [P,L]
        ProxyPassReverse / http://localhost:3000/
        LogLevel info
</VirtualHost>
```

When I connect to http://1.2.3.4:3000 the setup assistant appears and everything works as expected.
But when I try to connect to https://chat.domain.de it just loads a while and returns finally a 502 proxy error. 
The Apache error log and docker logs are inconspicuous and give no hints to any misconfiguration.

Is there anything that I am missing or is it an rocket.chat issue?

**Comment by sampaiodiego** [comment]
moved the issue to a better repo, as this is not a docker image issue =)

so as per your configuration, looks like the Apache is running on the same machine as the Rocket.Chat, is that correct? Since you're using `localhost:3000`:
```
ProxyPassReverse / http://localhost:3000/
```

is there anything on Apache logs? it might have useful info, as it was it who could not proxy the request.

**Comment by Chessmasterrr** [comment]
Thanks for your reply and sorry for posting in the wrong area!

Apache runs on the same machine as Rocket.Chat, yes. There are also other docker containers running on this machine which are accessible via the Apache reverse proxy without problems.

The Apache error.log just states:
```
[Mon Feb 11 17:22:15.263241 2019] [proxy_http:error] [pid 4396] (104)Connection reset by peer: [client 1.2.3.4:55448] AH01102: error reading status line from remote server localhost:3000
[Mon Feb 11 17:22:15.263318 2019] [proxy:error] [pid 4396] [client 1.2.3.4:55448] AH00898: Error reading from remote server returned by /
```

And the other_vhosts_access.log recognizes the access:
```
chat.domain.de:443 1.2.3.4 - - [11/Feb/2019:17:20:08 +0100] "GET / HTTP/1.1" 502 4427 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
chat.domain.de:443 1.2.3.4 - - [11/Feb/2019:17:22:15 +0100] "GET /favicon.ico HTTP/1.1" 200 31 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
chat.domain.de:443 1.2.3.4 - - [11/Feb/2019:17:24:22 +0100] "GET /favicon.ico HTTP/1.1" 502 814 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
```

**Comment by reetp** [comment]
Have a search on the interwebs for 

"AH01102: error reading status line from remote server"

https://serverfault.com/questions/538086/proxyerror-ah00898-error-during-ssl-handshake-with-remote-server#612873

Just wondering if there are some updates in Apache that means the config in Docs needs updating?

First thing seems to be check all your certs. 

Then might be worth trying variations with these settings

    SSLEngine On
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off

**Comment by Chessmasterrr** [comment]
After some further investigation it seems like docker is messing up with the iptables and cannot adjust them accordingly. After issuing the following command everything is working now:

`iptables -A OUTPUT -p tcp --dport 3000 -j ACCEPT`

So it was definitely a misconfiguration in my setup and nothing that has to be changed in your Docs. 

Thanks for your help!
