### ISSUE TITLE
Cross-domain trust for LDAP authentication

### ISSUE THREAD

**Issue by IakovBoguslavskii** [RocketChat/Rocket.Chat#13433]
Hi everyone

Given that multiple [LDAP authentication backends](https://github.com/RocketChat/Rocket.Chat/issues/5058) feature isnt going to be added,, I wondered whether Rocket.Chat supports the cross-domain trust technology? If not, is it planned to be added later by the developers?

This feature would actually allow to use a single LDAP-server to log in users from several domains - so instead of multiple LDAPs you'd basically need just one which is trusted by the other domains you want to use.

I havent found such an option in the current API version.

**Comment by 18739940427** [comment]
If you find this method, please let me know.

**Comment by IakovBoguslavskii** [comment]
@18739940427 , it's done via your Active Directory settings, not Rocket.Chat. I.e., you establish cross-domain trusts between your DCs in Active Directory and then use a single LDAP server in Rocket.Chat's settings.

**Comment by vitos202** [comment]
Has anyone been able to properly build LDAP query filters to get users from trusted domains? Can you show me an example?
