### ISSUE TITLE
Rocket behind NGINX port configuration (documentation)

### ISSUE THREAD

**Issue by VoidAndAny** [RocketChat/Rocket.Chat#1343]
In the following paragraph "https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker#6-running-behind-an-nginx-ssl-reverse-proxy" it is written not to add port to ROOT_URL variable, if Rocket is behind an Nginx SSL proxy.

But must we set the PORT variable ?
To 3000 or 443 (SSL) ?

Thanks

**Comment by emcguinness** [comment]
If you are referring to the port environment variable you set in step 3 of that guide, leave it at 3000. That controls what port rocket chat runs on, nginx still connects to it on that port. This is the first part of the config
```
# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}
```
That server line is the address and port nginx connects to rocket chat on, if you change that port variable to another port you could update it here to match. having said that if you did want to run rocket.chat on 443 you could then not also have nginx running on that port and things quickly get confusing.

**Comment by VoidAndAny** [comment]
Thanks a lot

**Comment by geekgonecrazy** [comment]
Looks like this is resolved.  Going to go ahead and close this.  Let me know if this wasn't the case.
