### ISSUE TITLE
SlackBridge not loading messages from all channels

### ISSUE THREAD

**Issue by GRX** [RocketChat/Rocket.Chat#13438]
### Description:
Messages posted in Slack are not all posted to Rocket Chat, AFAIK only one channel seems to come through which is a private channel, I've setup other channels with the same name as how they appear in Slack but only one channel seems to be "synced".

### Steps to reproduce:
1. Create channel with the same name as it is in Slack
2. Post message in Slack channel
3. Message not appearing in Rocket Chat

### Expected behavior:
When I create a channel using the same name as the Slack channel, to have it's messages appear in Rocket Chat.

### Actual behavior:
It works like described above for just one channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 
0.74.2
- Operating System: 
Ubuntu 18
- Deployment Method:
Docker
- Number of Running Instances: 
1

### Relevant logs:
The only log I can post is of a call that actually works, for messages that don't appear, are no logs.

**Comment by JoKneeMo** [comment]
Are you adding your rocketchat slack bot to the other channels?

**Comment by GRX** [comment]
> Are you adding your rocketchat slack bot to the other channels?

I did, Re-adding them seemed to solve the issue.

**Comment by chirospasm** [comment]
Do you mean you re0added the bot to the Slack channel, or you re-added the channel to RC server, @GRX. I'm having difficulty with this, similar issue (one channel).
