### ISSUE TITLE
Email doesn't work with cPanel - certificate issue

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [RocketChat/Rocket.Chat#13446]
I am unable to setup mail sender to work with our cPanel webmail server. 

Mail settings are:
Incoming Server: mail.******.com IMAP Port: 993 POP3 Port: 995
Outgoing Server: | mail.******.com SMTP Port: 465
 
When I setup  smtp with given settings. connection to smtp fails. By reading the log, i assume that this is problem with certificates, domain name mismatch. 

Exception in defer callback: { Error: Hostname/IP doesn't match certificate's altnames: "Host: mail.ars-es.com. is not in the cert's altnames: DNS:*.cpanelhosting.rs, DNS:cpanelhosting.rs"     at Object.checkServerIdentity (tls.js:223:17)     at TLSSocket.<anonymous> (_tls_wrap.js:1111:29)     at emitNone (events.js:106:13)     at TLSSocket.emit (events.js:208:7)     at TLSSocket._finishInit (_tls_wrap.js:639:8)     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)   reason: 'Host: mail.******.com. is not in the cert\'s altnames: DNS:*.cpanelhosting.rs, DNS:cpanelhosting.rs',   host: 'mail.******.com',   cert:     { subject: { OU: [Array], CN: '*.cpanelhosting.rs' },      issuer:        { C: 'GB',         ST: 'Greater Manchester',         L: 'Salford',         O: 'COMODO CA Limited',         CN: 'COMODO RSA Domain Validation Secure Server CA' },      subjectaltname: 'DNS:*.cpanelhosting.rs, DNS:cpanelhosting.rs',      infoAccess: { 'CA Issuers - URI': [Array], 'OCSP - URI': [Array] },      modulus: 'D5D8B53B09D4A295D1A07B69DF94D78C6E77C4902BBA64C732E5669148195F79A0DB8B7A4DF6FD80AE98465BD0AEEF3800C595ECB2E096BB028A9D7E67477C377D192C198A370929AB42AEACE9C62BE6E5473751AD03C3FD8D8D8B2E7CE6C2BBC179983DC2450ED2FFB02F90C96C4488FA2FA9636B96FBCF64B5B16E361C650A034C7EC001D011B2206CAFEA66342CA8FB22FB7727CFA781815A99B940DF13B7C88E2AC4D1EC09834A0ACD6A5045B41BA2AED1D63E32209FD8BE5CA49162108488AFE68922B5EA77FF41113BE32249DCDA1575FC54B7EA9C70A1DC6E5FBEBD4873D0B028FC6B08AB4F429D2E3291638E87975876E61BAD727A821A1055B499AB',      exponent: '0x10001',      valid_from: 'Jul 24 00:00:00 2018 GMT',      valid_to: 'Jul 24 23:59:59 2020 GMT',      fingerprint: 'D5:8B:3B:40:CE:C8:C1:C6:D3:35:40:7F:BB:2F:88:D0:5A:2B:9C:D9',      ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],      serialNumber: 'B5CD98F97FF5D3D2697DBE0CFF7C5D91',      raw: <Buffer 30 82 06 df 30 82 05 c7 a0 03 02 01 02 02 11 00 b5 cd 98 f9 7f f5 d3 d2 69 7d be 0c ff 7c 5d 91 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 81 90 ... > },   code: 'ECONNECTION',   command: 'CONN' }

Installation details:

Version 0.74.2
Apps Engine Version: 1.4.0
MongoDB: 3.2

**Comment by geekgonecrazy** [comment]
I'd reach out to your CPANEL provider.  I don't think there is anything we can really do about this one. 

You might be able to use the non-ssl port if they provide one.
