### ISSUE TITLE
Livechat Internal server error 

### ISSUE THREAD

**Issue by LacursaJ** [RocketChat/Rocket.Chat#13448]
Livechat show "Internal server error" when some guest write

### Steps to reproduce:

1. Activate Livechat
2. Add some backend users, no info is requested from customer (guest chat)
3. Open a browser and open a new guest chat, free operator 
4. Write any word

### Expected behavior:

Start a new chat with any operator

### Actual behavior:

"Internal server error" popup; no message to operator in backend

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1

[34mI20190212-13:22:42.426(1) Meteor ➔ method sendMessageLivechat -> userId: rm98usyiqN7XJuYKM , arguments:  [ { _id: 'QkYXqHCAQh4o6bvtR',     rid: '7qRbf6i7qmDCriBBt',     msg: 'Hola',     token: 'purnihfAQvmhrGdtn' },   null ] 
[34mI20190212-13:22:42.443(1) Meteor ➔ method UserPresence:connect -> userId: rm98usyiqN7XJuYKM , arguments:  [ 'purnihfAQvmhrGdtn', { visitor: 'purnihfAQvmhrGdtn' } ] 
[34mI20190212-13:22:42.480(1) Exception while invoking method 'sendMessageLivechat' { BulkWriteError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rm98usyiqN7XJuYKM", : null, : "l", : null }     at OrderedBulkOperation.handleWriteError (/snap/rocketchat-server/1364/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1048:11)     at resultHandler (/snap/rocketchat-server/1364/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:159:23)     at /snap/rocketchat-server/1364/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   index: 0,   code: 11000,   errmsg: 'E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rm98usyiqN7XJuYKM", : null, : "l", : null }',   op:     { rid: '7qRbf6i7qmDCriBBt',      fname: 'Jo',      alert: true,      open: true,      unread: 1,      userMentions: 1,      groupMentions: 0,      u: { _id: 'rm98usyiqN7XJuYKM', username: 'admin' },      t: 'l',      desktopNotifications: 'all',      mobilePushNotifications: 'all',      emailNotifications: 'all',      _updatedAt: 2019-02-12T12:22:42.463Z,      _id: 'fkFpTqMgnxYtNg9om' },   name: 'BulkWriteError',   driver: true,   err:     { index: 0,      code: 11000,      errmsg: 'E11000 duplicate key error collection: parties.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "rm98usyiqN7XJuYKM", : null, : "l", : null }',      op:        { rid: '7qRbf6i7qmDCriBBt',         fname: 'Jo',         alert: true,         open: true,         unread: 1,         userMentions: 1,         groupMentions: 0,         u: [Object],         t: 'l',         desktopNotifications: 'all',         mobilePushNotifications: 'all',         emailNotifications: 'all',         _updatedAt: 2019-02-12T12:22:42.463Z,         _id: 'fkFpTqMgnxYtNg9om' } },   result:     BulkWriteResult {      result:        { ok: 1,         writeErrors: [Array],         writeConcernErrors: [],         insertedIds: [Array],         nInserted: 0,         nUpserted: 0,         nMatched: 0,         nModified: 0,         nRemoved: 0,         upserted: [],         lastOp: [Object] } },   [Symbol(mongoErrorContextSymbol)]: {} } 
[34mI20190212-13:22:43.429(1) Meteor ➔ method UserPresence:online -> userId: rm98usyiqN7XJuYKM , arguments:  [ 'purnihfAQvmhrGdtn' ]

**Comment by renatobecker** [comment]
Hi @LacursaJ!!
It seems like there is an invalid unique index on your subscription collection(`u._id_1_name_1_t_1_code_1)`.
Did you update your server version recently?

**Comment by CH1PSET1** [comment]
Hello, exactly the same problem. Tell me how to solve

**Comment by LacursaJ** [comment]
Someone delete the chat default user before a update. Rebuild default users and re-update solves our problem.

**Comment by CH1PSET1** [comment]
> Someone delete the chat default user before a update. Rebuild default users and re-update solves our problem.

Thanks for the answer, but it is possible a little more in detail, what for users by default and how to restore them. Prior to this live chat did not include once, today for the first time. Like did not delete anything. Thank.

**Comment by CH1PSET1** [comment]
Very strange sequence. I create a new agent, I write him in a live chat, messages arrive, everything is fine. I open the mode incognito, again I write to the same agent, already an error, the messages do not reach. I create a new agent, the situation is exactly the same.

**Comment by alebeta90** [comment]
I'm in the same situation, some manage to solve this issue?

**Comment by alebeta90** [comment]
This is how my error looks like


Exception while invoking method 'joinRoom' { BulkWriteError: E11000 duplicate key error index: rocketchat.rocketchat_subscription.$u._id_1_name_1_t_1_code_1 dup key: { : "we2Dh5nchY9RyCSna", : null, : "l", : null }


    at OrderedBulkOperation.handleWriteError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1048:11)


    at resultHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/ordered.js:159:23)


    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18


    at _combinedTickCallback (internal/process/next_tick.js:131:7)


    at process._tickDomainCallback (internal/process/next_tick.js:218:9)


  index: 0,


  code: 11000,


  errmsg: 'E11000 duplicate key error index: rocketchat.rocketchat_subscription.$u._id_1_name_1_t_1_code_1 dup key: { : "we2Dh5nchY9RyCSna", : null, : "l", : null }',


  op: 


   { open: true,


     alert: true,


     unread: 1,


     userMentions: 1,


     groupMentions: 0,


     ts: 2019-06-21T13:51:30.583Z,


     rid: 'wNtbafnLsfMRHikQc',


     name: undefined,


     fname: 'centos-test',


     customFields: undefined,

**Comment by renatobecker** [comment]
> Hi @LacursaJ!!
> It seems like there is an invalid unique index on your subscription collection(`u._id_1_name_1_t_1_code_1)`.
> Did you update your server version recently?

As I have explained before, there is an index in your subscription collection that does not exist anymore:
https://github.com/RocketChat/Rocket.Chat/blob/develop/server/startup/migrations/v122.js#L7

**Comment by CH1PSET1** [comment]
@LacursaJ 

And what should be done in the end? I checked my js122 with yours, they are the same.

**Comment by renatobecker** [comment]
> @LacursaJ
> 
> And what should be done in the end? I checked my js122 with yours, they are the same.

You need to remove the index directly from your database / collection.

**Comment by alebeta90** [comment]
Hi @CH1PSET1 

What I did was:

1. Install MongoDB Compass in my computer.
2. Connect to the MongoDB.
3. Choose Rocketchat database from database explorer.
4. From the collections you have to choose rocketchat_subscription.
5. Go to indexes and delete u._id_1_name_1_t_1_code_1

With that you should solve the issue.

Kind regards,
Alejandro B.

**Comment by CH1PSET1** [comment]
Thank you, it works.
