### ISSUE TITLE
Unable to pin message

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#13454]
### Description:

Since [#12739](https://github.com/RocketChat/Rocket.Chat/pull/12739), channel's owner can't pin message with an "not-authorized" error.

### Steps to reproduce:

1. As owner in a channel pin a message

### Expected behavior:

Message is pinned

### Actual behavior:

Error not-authorized and the message is not pinned

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 7
- DB Replicaset Oplog: yes
- NodeJS Version: 8.12.0
- MongoDB Version: 3.2

### Additional context

Only "admin", "moderator" and "owner" roles can pin message. Adding "user" role to pin-message allows to pin messages.

**Comment by MarcosSpessatto** [comment]
@magicbelette just to make sure, the permission `pin-message` is enabled for `owner` in your server, right?

**Comment by MarcosSpessatto** [comment]
Also if you can update your server version to the latest, I found [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13213) that maybe fix this issue. Please let me know if the problem persists.

**Comment by casusss** [comment]
RocketChat  1.0.2
Desktop client 2.15.3
Not found actions "Pin message"
![NotActionPinMessage](https://user-images.githubusercontent.com/50357786/57283333-f8fe7180-70bf-11e9-9715-df540780dd8e.JPG)

**Comment by MarcosSpessatto** [comment]
@magicbelette Any news?

**Comment by magicbelette** [comment]
Sorry @MarcosSpessatto, I missed those questions.

So to answer before closing, yes pin-message was enabled for owner. I cannot reproduce this problem so I close. 

Thanks for your help
