### ISSUE TITLE
Inline code creating a separate block.

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#13453]
### Description:

When trying to enter a piece of code or text meant to be inline in monospace, a whole block is created, breaking the paragraph. This used to work as intended.

### Steps to reproduce:

1. Type the following:
```
This is supposed to be an ```inline``` code example.
```
2. You will see that the word **inline** will appear by itself rather than how it appears in the following GitHub markdown:

This is supposed to be an ```inline``` code example.

### Expected behavior:
Inline code text should be rendered inline with the other text, surrounded by a small, non-paragraph breaking box.

### Actual behavior:
![image](https://user-images.githubusercontent.com/14616851/52650516-04227680-2eb0-11e9-8549-f45582f273da.png)

### Rocket.Chat

| Version                 | 0.74.0-develop                                            |
| ----------------------- | --------------------------------------------------------- |
| Apps Engine Version     | 1.4.0                                                     |
| Database Migration      | 137                                                       |
| Database Migration Date | Tue Feb 12 2019 10:15:14 GMT-0600 (Central Standard Time) |
| Installed at            | Fri Jan 25 2019 17:44:08 GMT-0600 (Central Standard Time) |
| Uptime                  | 37 seconds                                                |
| Deployment ID           | dwPkHnPwaKuHALm6b                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | a93111873d3e7735a56d2d36ab626b5c5718b7bd                    |
| ------- | ----------------------------------------------------------- |
| Date    | Fri Feb 8 17:20:31 2019 -0600                               |
| Branch  | develop                                                     |
| Tag     | 0.73.0                                                      |
| Author  | Bradley Hilton                                              |
| Subject | Add the missing uniqueId to the push notifications (#13423) |

**Comment by tassoevan** [comment]
I think this the correct behavior `Original` markdown parser:

- `` `code` `` for inline code;
- `` ```code``` `` for multiline code block.

The behavior you are looking for comes from `Marked` parser. Since it "used to work as intended", is it possible the setting (`Markdown_Parser`, `Admin > Messages > Markdown > Markdown Parser`) was changed?

**Comment by bkraul** [comment]
@tassoevan I got you. And you are correct. I am using Original, indeed. I was using Marked for a long time, but the emojis do not render as well as they do on original. It is a hard decision, because Marked renders tables, whereas Original does not. I see there is #11736, but there have been no updates. 

I surmise this is still not a simple issue?

**Comment by tassoevan** [comment]
Surely it is a bug, but not in the parser _per se_, as I've commented some days ago in a issue about emoji rendering: https://github.com/RocketChat/Rocket.Chat/issues/12323#issuecomment-461869000 The fact that message renderers parse HTML code instead of plain text is wrong by definition, as HTML is a non-regular markup language, therefore it's an architectural issue.

**Comment by bkraul** [comment]
I will close this issue, as it has been pointed out that the reported issue is not an issue but just a difference between Marked and Original markup setting. Thanks again @tassoevan !
