### ISSUE TITLE
Livechat triggers stop working after a conversation 

### ISSUE THREAD

**Issue by nsdev0** [RocketChat/Rocket.Chat#13459]
### Description:
Livechat triggers stop working after visitor opened and finished his first conversation.

### Steps to reproduce:

0. Set up some trigger (runOnce -> disabled)
1. Go to the web page with embedded livechat widget
2. Start conversation
3. Finish conversation

### Expected behavior:
Livechat triggers should be working even after the visitor has successfully talked to the operator.
Except when setting 'runOnce' is enabled.

### Actual behavior:
Trigger works until the visitor talks to the operator.
Starts working again after cleaning localStorage (actually after cleaning 'visitorToken'  I think)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: On
- NodeJS Version: v8.15.0
- MongoDB Version: 3.2.7

**Comment by jervis446** [comment]
hey @renatobecker this is issue is not assigned to anyone .... can I work on this?

**Comment by MartinSchoeler** [comment]
Should be fixed on the latest version, if not, feel free to create a new issue with updated details. Thanks!
