### ISSUE TITLE
Slack Import not completing and cannot be canceled.

### ISSUE THREAD

**Issue by JoKneeMo** [RocketChat/Rocket.Chat#13450]
### Description:

A failed Slack import cannot be canceled. 

### Steps to reproduce:

1. Upload Slack zip on the import page
2. Messages are processed and some are imported
3. After a while, the server connection times out a few times (possibly overloaded)
4. Navigate back to the slack import page to check the progress

### Expected behavior:

When it says I can close the window, I would expect the slack import to be flushed but it seems to be stuck somewhere. 

### Actual behavior:

Navigating to /admin/import/progress/slack redirects to progress and displays.

> Importing the messages.
> 0/0
> You can close this window now.

The only messages appearing in the debug log are

`rocketchat-server.rocketchat-server[5682]: rocketchat:logger server.js:199 Meteor ➔ method getImportProgress -> userId: tAB4sL19jEn8g6hiK , arguments:  [ 'slack' ]
`

I've restarted the server and mongo snaps but the result has not changed.

This import was originally started on 73.2 and I have the same issue on a clean 74.2 snap.

### Server Setup Information:

- Version of Rocket.Chat Server: 74.2
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1

### Relevant logs:

`rocketchat-server.rocketchat-server[5682]: rocketchat:logger server.js:199 Meteor ➔ method getImportProgress -> userId: tAB4sL19jEn8g6hiK , arguments:  [ 'slack' ]
`

**Comment by JoKneeMo** [comment]
Where would this stale import be stored within the snap, database or file? Any idea on how I can kill it from the back end?

**Comment by JoKneeMo** [comment]
I'm still experience this issue even after several releases and system restarts have taken place.
I'm currently on v1.0.3 but the slack import still says it is in progress at 0/0 messages.

Is there any way I can clear the old import that is several months old?

**Comment by pierre-lehnen-rc** [comment]
Fixed on #16279
