### ISSUE TITLE
origin-when-crossorigin should be origin-when-cross-origin

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#13466]
### Description:

in this file:

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-master/server/inject.js

it says:

Inject.rawHead('noreferrer', '<meta name="referrer" content="origin-when-crossorigin">');

That's a typo. See https://lists.w3.org/Archives/Public/public-webappsec/2015May/0064.html

it should be origin-when-cross-origin

**Comment by algomaster99** [comment]
Can I open a pull request? I have fixed the issue!

**Comment by tassoevan** [comment]
@algomaster99 Sure, pull requests are always welcome!
