### ISSUE TITLE
Login button difficult to find on desktop

### ISSUE THREAD

**Issue by john-light** [RocketChat/Rocket.Chat#13460]
### Description:

When I open Rocket Chat on desktop, the page shown is the home page and there is no login button shown.

### Steps to reproduce:

1. Open Rocket Chat on desktop
2. Log out if you are logged in
3. Notice that there is no button to log back in
4. You have to poke around quite a bit (e.g. by searching the server for a channel) before you can find somewhere to login, it doesn't even show channels to select from on the side to make poking around easier you have to know to search for a channel in the search bar.

### Expected behavior:

I expect there to be a login button in the Home page

### Actual behavior:

Notice no login button on the Home page.

![rocketchat](https://user-images.githubusercontent.com/9424721/52673429-a2750300-2ed5-11e9-88ec-fece9c33fcdc.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.2
- Operating System: Linux

**Comment by lyricalpolymath** [comment]
more info since I had this problem too
```
RocketChat.Info
{version: "0.66.2", build: {…}, commit: {…}}
build:
arch: "x64"
cpus: 32
date: "2018-07-06T04:32:17.410Z"
freeMemory: 7586078720
nodeVersion: "v8.11.3"
osRelease: "4.4.0-130-generic"
platform: "linux"
totalMemory: 63314808832

commit:
author: "Diego Sampaio"
branch: "HEAD"
date: "Fri Jul 6 01:22:37 2018 -0300"
hash: "78fdef624aadbcc890986f3429b60870310187db"
subject: "Merge pull request #11366 from RocketChat/release-0.66.2"
tag: "0.66.2"
__proto__: Object
version: "0.66.2"
```

**Comment by reetp** [comment]
@lyricalpolymath You are on an extremely old version - 0.66.2

Rocket is currently on 0.74.x Due to the fast pace of development there will be significant changes.

Standard debugging is to test on the latest version of Rocket as this:

https://rocket.chat/docs/contributing/reporting-issues

If you still have issues then please use the following template.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Can the original OP please fill out out the server information as well.

**Comment by algomaster99** [comment]
Rocket.Chat version 1.0.0 doesn't have this issue. I think this can be closed.

**Comment by tassoevan** [comment]
Are you allowing anonymous access, right? There is a known bug: when logging out, the channel list is not properly updated -- still present in the current version. As a workaround, after you refresh the page, clicking at some public channel will show a button to send you to the login screen.

**Comment by john-light** [comment]
@reetp my server version is at the bottom of the first post. I will update and test on the latest version to see if there is a login button on the Home page; if so I will close this issue. otherwise I would keep it open because putting a login button on the home page would give direction to logged out users about where to go next if they want to login.

@tassoevan  yes we are allowing anonymous access. and the channel list issue you mention is present. after finding a public channel I see a login button.

**Comment by Rodriq** [comment]
@reetp I think like @algomaster99 rightly said this issue should be closed.
  Recent versions of RC has that managed.

![login screen](https://user-images.githubusercontent.com/39289592/53304459-c6412d00-3875-11e9-959e-d2fe1a3d88b6.png)

**Comment by reetp** [comment]
Can this be closed?
