### ISSUE TITLE
[sandstorm] Cannot embed images

### ISSUE THREAD

**Issue by neynah** [RocketChat/Rocket.Chat#1346]
@Sing-Li I'd love to be able to embed images on rocket.chat(on Sandstorm). I'm able to upload the image but it doesn't embed properly. Looks like a network error?
![image](https://cloud.githubusercontent.com/assets/855341/11010266/7d7e36ac-8492-11e5-9894-bea21439af86.png)

**Comment by dwrensha** [comment]
Duplicate of #910?

**Comment by neynah** [comment]
Yes that sounds the same. Ty!
