### ISSUE TITLE
Docker Hub Build ist not latest tagged

### ISSUE THREAD

**Issue by MatthiasHertel** [RocketChat/Rocket.Chat#13478]
https://hub.docker.com/r/rocketchat/rocket.chat/tags

the latest tag is not reffered to version `0.74.3`

i want to pull the latest version. but it hangs on version `0.74.2`

**Comment by manacim** [comment]
Same issue, here. Thought I was going crazy!

**Comment by frdmn** [comment]
It's available on Docker Hub now :)
