### ISSUE TITLE
Padding missing on home page

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#13487]
### Description:

![image](https://user-images.githubusercontent.com/51996/52812157-7637be80-305c-11e9-91e8-2a3006af5907.png)

Picture is worth a thousand words :)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-develop
- open.rocket.chat :)

### Additional context

I think the padding around this maybe off in other views as well.  But this one is especially bad

**Comment by algomaster99** [comment]
@geekgonecrazy Are you talking about the padding between hamburger and home right?
![padding](https://user-images.githubusercontent.com/35191225/52900566-6fa47500-321d-11e9-9a2b-900eca046012.png)
Apparently, it is fine when I set up on my local machine. Checked it on chrome and firefox.

**Comment by tassoevan** [comment]
@algomaster99 
1. Clone this repo / checkout and pull to `develop` branch
2. Run `meteor npm i`
3. Run `meteor`

**Comment by algomaster99** [comment]
Okay, will see to it and submit a PR.
