### ISSUE TITLE
custom oauth delete not working

### ISSUE THREAD

**Issue by elievischel** [RocketChat/Rocket.Chat#13484]
### Description:

impossible to delete a custom oauth once created

### Steps to reproduce:

1. Go to OAuth
2. Add custom oauth
3. Write a name "test"
4. click on remove custom oauth

### Expected behavior:

should be deleted / disappear

### Actual behavior:

nothing happened

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.2
- Operating System:  Linux
- Deployment Method: SNAP
- Number of Running Instances: 1

**Comment by geekgonecrazy** [comment]
Can you try on a new version of Rocket.Chat?  0.65.0 is pretty old.  Please re-open if still happens
