### ISSUE TITLE
Ubuntu 14.04 Fresh install problem

### ISSUE THREAD

**Issue by mcmyt** [RocketChat/Rocket.Chat#1348]
I'm getting this error when I try to install Rocket.chat in Fresh Ubuntu 14.04 (DigitalOcean).

I followed this word by word https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-to-UBUNTU

I am getting this
```
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/var/www/rocket.chat/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
...
```
When I check the folder /var/www/rocket.chat there is no package.json, nor in the git btw. 

I also get this after running ` meteor build --server "$HOST" --directory .`
```
Killedlding for web.browser 
```

And ./bundle doesn't exist

(I tried with docker too but gets stuck at something like `Update ... SAML_...` )
Thanks for your help.

**Comment by mcmyt** [comment]
This problem was solved. Now I'm having this #1350

**Comment by BackIsBachus** [comment]
Hey, I'm also having your issue with
```
Killedlding for web.browser 
```

How did you solve it?

**Comment by d4nyll** [comment]
This happens when your server does not have enough memory to run the application. Add some swap memory or upgrade your server.

**Comment by MikeSoft** [comment]
@d4nyll  thank you friend, you're right
