### ISSUE TITLE
bosnian language not working well

### ISSUE THREAD

**Issue by bosna387** [RocketChat/Rocket.Chat#13490]
### Description:

<p>
bosnian language does not translate the interface - everything remains in english. Croatian (Hrvatski) works fine. It is same as croatian - Cant you just clone Croatian and name it Bosanski (bosnian)?
</p>
### Steps to reproduce:

1.  <p> My Account - Localisation - select Bosanski. </p>
2. 
3. 

### Expected behavior:

<p> Expected to see interface translated to Bosnian.</p>
### Actual behavior:
<p> Interface remains in english </p>

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by ggazzo** [comment]
@bosna387 I'm not a bosnian speaker, if you are sure, please open a PR "cloning" the dictionary. thanks :)

**Comment by fliptrail** [comment]
Will try this today

**Comment by fliptrail** [comment]
@ggazzo Please review this PR. I did some basic research. Both are languages are similar excluding some regional differences. So, the same translation can be used for both.

**Comment by salihoglu87** [comment]
i can confirm that croatian and bosnian match to 98%. :)
