### ISSUE TITLE
support for desktop sharing

### ISSUE THREAD

**Issue by yogeshVU** [RocketChat/Rocket.Chat#1349]
Please have a desktop sharing feature

**Comment by emcguinness** [comment]
I have not tested it yet myself but it already has this, in theory you just need a browser extension [here](https://github.com/RocketChat/Rocket.Chat.ScreenShare.Extentions). Then when in a video call you should see a new screen share button.

**Comment by geekgonecrazy** [comment]
@rodrigok might be able to provide some information on this.  But for sure added.  We may just need to publish this to the chrome extension store?

**Comment by engelgabriel** [comment]
Implemented via #933
We will close the other issue when we publish the plugins
