### ISSUE TITLE
How to install Rocket chat on Linux server ?

### ISSUE THREAD

**Issue by yaznesh** [RocketChat/Rocket.Chat#13506]
Hi,

we have urgent requirement, Rocket chat needs to be installed in our Linux server.

i found there is no steps provided for Rocket installation on Linux server.

Kindly provide step by step procedure for ROCKET INSTALLATION ON LINUX SERVER

we need complete step by step command procedure for Rocket installation on Linux server.

Please consider this requirement as High Priority.

Help would be appreciated.

**Comment by yaznesh** [comment]
****

**Comment by yaznesh** [comment]
Hi,

we have urgent requirment, Rocket chat needs to be installed in our Linux server.

i found there is no steps provided for Rocket installation on Linux server.

Kindly provide step by step procedure for ROCKET INSTALLATION ON LINUX SERVER

we need complete step by step command procedure for Rocket installation on Linux server.

Please consider this requirement as High Priority.

Help would be appriciated.

**Comment by yaznesh** [comment]
Hi,

we have urgent requirment, Rocket chat needs to be installed in our Linux server.

i found there is no steps provided for Rocket installation on Linux server.

Kindly provide step by step procedure for ROCKET INSTALLATION ON LINUX SERVER

we need complete step by step command procedure for Rocket installation on Linux server.

Please consider this requirement as High Priority.

Help would be appriciated.

**Comment by beranPro** [comment]
https://rocket.chat/docs/installation/manual-installation/
