### ISSUE TITLE
REST API users.info returns hashedToken for non-admin users

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#13512]
According to the documentation (https://rocket.chat/docs/developer-guides/rest-api/users/info/) REST API users.info returns hashedToken, bcrypt password... only for admin users. On my instance of Rocket.Chat 0.74.3 those informations are returned even for regular users.

Found nothing in my "permissions" menu. 

This method seems to work as described in the documentation on open.rocket.chat.

Did I miss something ?

**Comment by MarcosSpessatto** [comment]
@magicbelette the user that you are logged in to API(token) is admin or regular user? If you request the info of a regular user logged as admin, you can get these information that you described. If you call the endpoint with a regular user logged, then yes, you will get the basic information only.

**Comment by algomaster99** [comment]
@MarcosSpessatto I tried using the api. Even though I am logged in, it still shows `HTTP 401 Unauthorized`. This is the repsonse on `http://localhost:3000/api/v1/users.info?username=aman`.
```
{
  "status": "error",
  "message": "You must be logged in to do this."
}
```
I am logged in as admin.

**Comment by magicbelette** [comment]
My bad, the right [view-full-other-user-info] was enabled for "user" role.
Thanks for your answers
