### ISSUE TITLE
On RC demo, default live channel: "Terminal Messages"

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#1351]
Read only channel which mirrors messages sent to terminal by server - so casual observer can get appreciation of what's happening on server. Demo purposes only.

**Comment by geekgonecrazy** [comment]
I think we have an issue dealing with a behavior similar to this.  #604 perhaps?

**Comment by geekgonecrazy** [comment]
Closing, please let me know if this was incorrect.
