### ISSUE TITLE
iframe CORS issue

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#13524]
Having an iframe cors related issue, is there a way to allow cors within rocket chat or would i need to install a cors npm and set it up? 

I am trying to edit the html dom on the content from rocket chat within the iframe.

Somethings with rocketchat have been a bit confusing.

**Comment by MarcosSpessatto** [comment]
Hi @ubergeekzone, you can enable cors in the admin panel under (`Admin Panel -> General -> REST API -> Enable Cors`).

**Comment by ubergeekzone** [comment]
@MarcosSpessatto this will open up access within the iframe as well?

**Comment by ubergeekzone** [comment]
Below is a snippet of code showing what i am hoping to do. 

```js
$("#myiframe").contents().on("click", ".sidebar-item__link",  function() {
   $("#myiframe").contents().find(".register-anonymous span").text("Join as Guest");
});
```

I am getting a Uncaught DOMException: Blocked a frame with origin "xxxxxxx" from accessing a cross-origin frame message though, Which makes sense but was wondering Rocket Chat had something like document.location = 'xxxxxx' built in to allow the pass through.

**Comment by usamamashkoor** [comment]
@ubergeekzone  did you find any solution for this?

**Comment by HiveMindNet** [comment]
@ubergeekzone I would really appreciate it if you managed to resolve this issue, if you would please share how you did?

Very much appreciated.

**Comment by backspace420** [comment]
Me too, because I need to manipulate the dom for the interface that we need to set on our site

**Comment by backspace420** [comment]
Is there any Update here? I need to set the button of livechat to display none for responsiveness.

**Comment by gabriellsh** [comment]
In Settings > General there's a sections called `iframe integration` which has settings related to cors.
