### ISSUE TITLE
Problem with multiple instances in Kubernetes

### ISSUE THREAD

**Issue by reymonlu** [RocketChat/Rocket.Chat#13528]
Hi,

I would like to deploy rocket Tchat in a cluster with multiple replicas. The mongoDBs databases is outsourced. The deployments is working but when i try to connect to differents pods of my deployment, there are some latences when i write a message to another person in another instance... I did refer the variable INSTANCE_IP with the Pod IP

I would like to know if there is a tips to achieve a 0 latence tchat with multiple pods.

Thanks

**Comment by geekgonecrazy** [comment]
Are you using oplog?  Messages are seen from db via oplog tailing.  So if not using oplog each instance polls db for messages

**Comment by reymonlu** [comment]
Using Oplog fixed it ty !
