### ISSUE TITLE
Add more advanced Statistics options

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#1353]
Add more advanced Statistics options so we can see peaks and troughs of usage throught a set period of time - maybe in the form of pie chart, line graph etc..

Useful when selling\recommending the idea to the Board after an intial pilot; and of course ongoing monitoring of its useage.
##

**Comment by graywolf336** [comment]
I do believe this would be useful under #726

**Comment by engelgabriel** [comment]
Dup of #726
