### ISSUE TITLE
Search in the directory of users in custom fields

### ISSUE THREAD

**Issue by mmmaks2004** [RocketChat/Rocket.Chat#13537]
Hi,
I added custom fields: department and position
How to search in the user directory for them?
How to display them in the user directory?

**Comment by tassoevan** [comment]
@mmmaks2004  Please describe your issue using the following template: https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mmmaks2004** [comment]
### Description:
I added custom fields: department and position
How to search in the user directory for them?
How to display them in the user directory?

### Steps to reproduce:
1.Sign in to Rocket.Chat in browser 
2.Click Directory ->User

### Expected behavior:
I want to display my custom fields in the list of users

### Actual behavior:
no search for these fields

### Server Setup Information:
- Version of Rocket.Chat Server:  0.74.2
- Operating System:  Ubuntu 18.04 x64
- Deployment Method: snap

**Comment by mayur-rawte** [comment]
any update on this?

**Comment by moriccelli** [comment]
The feature is very expected!

**Comment by ankar84** [comment]
Search on a custom fields is a very usefull feature. 
We added telephone number to custom field **telephoneNumber**.
We added **telephoneNumber** in **Fields to Consider in Search** option in **Account** settings in **Administration**
But search for users telephone number doesn't work now.
Please add opportunity to **search for custom fields in Directory ->User**

**Comment by ankar84** [comment]
@mmmaks2004 @moriccelli @mayur-rawte @tassoevan great news!
We found that **custom fields search already works great**,
We added t**elephoneNumber** custom field and **found right wa**y to add it to search in **Fields to Consider in Search** option in **Account** settings in **Administration**
Now in that field we have that: username, name, **customFields.telephoneNumber**
And search by telephone number works great!
Please check it and write result here.
Rocket.Chat Version 2.3.2

**Comment by moriccelli** [comment]
@ankar84 you're perfectly right! thanks a lot! 
but still it would be perfect to see the custom fields in the table in the derectory. But this is enother ticket: https://github.com/RocketChat/Rocket.Chat/issues/13934
I think, it's ok to close the issue

**Comment by ankar84** [comment]
@moriccelli glad to hear!
And yes, now we need to see custom fields in the **Directory** table.
