### ISSUE TITLE
KaTeX parse error inside code block

### ISSUE THREAD

**Issue by iegik** [RocketChat/Rocket.Chat#13538]
## My Setup
- Operating System: MacOS
- App Version: 2.14.7
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

insert following code to the conversation:
```
var OPEN_TAG = /\[%/;
```

### Current Behavior

Message shows as code block with following error inside:

```
var OPEN_TAG = /
KaTeX parse error: Expected 'EOF', got '%' at position 22: …r CLOSE_TAG = /%̲
/;
```

### Expected Behavior

Message shows as code block without any KaTeX error inside:

```
var OPEN_TAG = /\[%/;
```

**Comment by savish28** [comment]
@iegik Do we want that rather than rendering katex parse error in the output block of katex messages, It should render the input message in the katex box?

**Comment by wreiske** [comment]
Some example instances I ran into today...

![image](https://user-images.githubusercontent.com/6295044/64292688-ec3c3e00-cf38-11e9-9b7c-8e411c3d115f.png)

![image](https://user-images.githubusercontent.com/6295044/64292704-f52d0f80-cf38-11e9-9029-cec5d0e47a1e.png)

**Comment by iegik** [comment]
@savish28 I think, that will be nice to leave errored message "as is" and append KaTeX error bellow the message block.
To be sure, user understanding where error occurs - we may underline place where it occurs.

**Comment by gloriouschaos** [comment]
KaTeX should not act on any code blocks or inline code items. Those are supposed to be rendered verbatim in a monospace font, perhaps with colors, per the Markdown standard. It's not just code that gets messed up by KaTeX. Even typing a dollar sign in plain text seems to trigger the bug, and there is no obvious escape sequence to type a literal dollar sign. Please fix this ASAP.

**Comment by reffu42** [comment]
I agree with @gloriouschaos, code blocks and inline code should have no further rendering applied to them, since (aside from unintended code triggering formatting) it becomes impossible to do something like show the verbatim text one would use to achieve a certain format/rendering appearance.
