### ISSUE TITLE
Hubot instructions

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [RocketChat/Rocket.Chat#1354]
Does anyone have an instructions for installing Hubot in a VPS environment? Without docker? It would be great if we could add this to the wiki.

**Comment by stephenreda** [comment]
I agree, some more basic information/walkthrough about implementing hubot chat would be nice. I have no previous experience with node/hubot. I've cloned Rocket.chat.hubot, i've added the hubot rss reader, but I am failing to see how to connect this now to rocket.chat..

**Comment by romdi** [comment]
The instructions at https://github.com/RocketChat/hubot-rocketchat cover almost everything, but it's easy to miss a step, so here's how I did it:

1. Go to your Rocket.Chat instance website and register a new user for your bot. Let's use *testbot* as user name and *testpass* as password here and assume *https://testchat.example.com* is your website URL.

2. In your terminal:
```
npm install -g yo generator-hubot coffee-script
mkdir testbot
cd testbot
yo hubot
[set owner name] <you>
[set bot name] testbot
[set description] <description>
[set bot adapter] rocketchat
```

3a. Linux & Mac OS:
```
export ROCKETCHAT_URL=testchat.example.com
export ROCKETCHAT_ROOM=GENERAL
export ROCKETCHAT_USER=testbot
export ROCKETCHAT_PASSWORD=testpass
bin/hubot -a rocketchat
```

3b. Windows:
```
set ROCKETCHAT_URL=testchat.example.com
set ROCKETCHAT_ROOM=GENERAL
set ROCKETCHAT_USER=testbot
set ROCKETCHAT_PASSWORD=testpass
bin\hubot -a rocketchat
```

**Comment by stephenreda** [comment]
What should be mentioned is that npm has to run with sudo, while 'yo' not.

@romdi 
![image](https://cloud.githubusercontent.com/assets/2557554/11017606/dc737e52-85a4-11e5-9091-d1f693b5b869.png)
My rocketchat is setup with an IP as hostname. This works perfectly.


![image](https://cloud.githubusercontent.com/assets/2557554/11017619/0ef7ed9a-85a5-11e5-9226-c3451ae51cc6.png)
I can't seem to get the hubot up or responding. I would assume the testbot user would auto connect to the room? Commands to testbot in the general channel also don't work.

**Comment by romdi** [comment]
@stephenreda: You're right. I updated the examples

Try with the port at the end:

    export ROCKETCHAT_URL=localhost:3000

or

    export ROCKETCHAT_URL=192.168.101.45:3000

**Comment by stephenreda** [comment]
Yes that works! Thanx Romdi.

**Comment by phillip-white-sociomantic** [comment]
Thanks guys. I will give this guide a go soon

**Comment by stephenreda** [comment]
How would you advice to get the bot started in an automate way?
At the moment, of the set environment variabels vanish, the bot won't boot up right.

I was thinking of putting the stuff just in a script f.e.
>#!/bin/bash
>export ROCKETCHAT_ROOM=GENERAL
>export ROCKETCHAT_USER=bot
>export ROCKETCHAT_PASSWORD=bot
>...
>bin/hubot -a rocketchat

**Comment by stephenreda** [comment]
@romdi 
Could you help me getting started with implementing a third part hubot extension?

f.e. https://github.com/shokai/hubot-rss-reader

I've installed the packages
>% npm install hubot-rss-reader -save
>% npm install coffee-script@">=1.8.0" -save
I've editited external-script.json
>["hubot-rss-reader"]

What would be the next step? 
Testing this into the testbot right away does not seem to work. 
Does the 'bot' has to be re-build somehow?

**Comment by romdi** [comment]
@stephenreda:

Thanks for the daemon script.

Did you set the environment variables the author described? I haven't tested this extension yet, but for simple hubot extensions all that's usually needed is installing it via npm and adding the name to the external-script.json array. Maybe try a simple extension first and go from there.

**Comment by phillip-white-sociomantic** [comment]
I can confirm the instructions work. Thanks @romdi and @stephenreda for the break down. Mine was not working before because i was installing hubot as the root user. I had permission issues when trying to ` yo hubot` Maybe the best approach is to install it under another user account, and place the hubots in the users home dir? Did you guys have permissions? Do you use a separate user for hubot?

**Comment by geekgonecrazy** [comment]
instead of closing this, I think it'd be a great idea to see this converted to a wiki article.  If any of you would be interested in doing this, we would love the contribution.

**Comment by geekgonecrazy** [comment]
Documentation is here: https://github.com/RocketChat/hubot-rocketchat forgot to close this issue.
