### ISSUE TITLE
Uploading Excel Files not supported

### ISSUE THREAD

**Issue by jrlandis525** [RocketChat/Rocket.Chat#13549]
## My Setup
- Operating System: Windows 10
- App Version: 2.14.7
- Installation type: 

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

### Current Behavior
 when attempting to drop an excel file in a chat, whether it is xls, xlsx or csv, we get a message it is not a supported type

### Expected Behavior
 Be able to accept excel files

**Comment by bkraul** [comment]
Not sure if this applies, but you have to have the MIME type enabled in the File Uploads section of the Administration. Multiples are separated by commas. The 2 I use for excel files are:

```application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel```

![image](https://user-images.githubusercontent.com/14616851/53281331-1c826480-36ec-11e9-9aae-5e860c73118c.png)

My complete set of MIME types, which supports: images, audio, video, zip/rar files, pdf, text, word (doc, docx) and excel (xls, xlsx) is as follows:

```
image/*,audio/*,video/*,application/zip,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/msword,application/vnd.ms-excel,text/markdown
```
