### ISSUE TITLE
How to change "From name" for all emails

### ISSUE THREAD

**Issue by Ngenda** [RocketChat/Rocket.Chat#13555]
I wish to customize the "from name" that appears on the emails sent from my private rocket chat site. I want to change it form "Rocket.Chat" to something else.  I have managed to edit my email credentials by going to Administration>Email>SMTP>From Email. I entered it in the following format: "ExampleName <example@site. com>".

The customized name only seems to work on the test mail, the user invitation mail and the welcome mail when a user is manually added by an admin.

It doesn't work for the Verification mail and the Welcome mail when users signup by themselves and verify their emails, as well as when a verification link is re-sent. In these cases the "from name" that appears is still "Rocket.chat"

How do i fix this and ensure that **ALL** **MAILS** sent from my mail server have my customized "from name" and not "Rocket.Chat"

Thanks in advance.

**Comment by fliptrail** [comment]
This is not an issue. Can be closed.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
