### ISSUE TITLE
No add button for joining new channels

### ISSUE THREAD

**Issue by gsunit** [RocketChat/Rocket.Chat#13556]
When I started using Rocket chat and wanted to join a new channel I could not find an option to the see the list of all public channels. There should be an "add button" right next to the channel header that can show a list where I can choose from. Currently, a user is supposed to search using the search box. However, she may not know the channel's name and thus not know what to search. 

Also, a list readily being available to the user would increase the chances of some other channels catching the users' interest.

I would love to work on the same. Moreover, if this has been omitted for some reason please let me know.

**Comment by ggazzo** [comment]
@gsunit usually we use the `directory` feature, http://yourserver.bla/directory, and after you open the room you should be able to see the `join button`.

**Comment by fliptrail** [comment]
I guess there should be a text under directory button permanently to make it clear. It is confusing for a new user currently.

**Comment by ggazzo** [comment]
I'm closing since we dont have more complaining about
