### ISSUE TITLE
Dismiss button for "save your encryption password" dialog

### ISSUE THREAD

**Issue by gsunit** [RocketChat/Rocket.Chat#13557]
I would like to suggest that there should be a dimiss button on the "save your encryption password" dialog. To remind the user, the dialog may still appear again the next time a user re-opens rocket chat.

Also, even if this feature seems important, the user should however at least be able to dismiss it after opening it and clicking on "i'll do it later". Which does not seem to be the case.

**Comment by gsunit** [comment]
Can I work on it?

**Comment by fliptrail** [comment]
I would see to it todat

**Comment by Perflyst** [comment]
> Can I work on it?

I don't think anyone will not allow you to not work on it. Also I think this is nothing which would get not merged.

**Comment by git-anurag-hub** [comment]
Anyone working? Or should I take this.

**Comment by dipanshparmar** [comment]
Can I work on this?

**Comment by sachin746** [comment]
i want to work on this issue please someone provide bullet point or guide me how can i solve this issue.i have setup the environment for contribution

**Comment by savish28** [comment]
@ggazzo could you please review #19872 ?
