### ISSUE TITLE
Custom emoji icon gone

### ISSUE THREAD

**Issue by ChuckB0ris** [RocketChat/Rocket.Chat#13566]
### Description:

The custom emoji icon has disappeared, I do not know why or how to restore it, although emoji's are available if written and can see them in administration
### Steps to reproduce:

1. In any chat window
2. Click on emoji button

### Expected behavior:
the "rocket" icon meant for custom emoji's is not visible

see the icon to be able to select an emoji
### Actual behavior:
no icon

![image](https://user-images.githubusercontent.com/35690704/53351955-a1f35800-392a-11e9-851f-f4a50c919e96.png)
![image](https://user-images.githubusercontent.com/35690704/53352000-b59ebe80-392a-11e9-98d5-81a7e836df9b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: linux x64 3.10.0-957.5.1.el7.x86_64
- Deployment Method:  docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: v3.6.10

### Relevant logs:

Update1: It seems to get fixed if I manually access https://server/#custom , but this is not good as every single user would have to do this :( (it only fixes it for that session, afterwards when you try to access the rkt_chat it resumes the reported buggy behaviour)
Update2: I would also be interested in a script to delete all custom emoji's, if this fixes the issue
Update3: The problem was the high number of emoji's, after I connected to the mongoDB and deleted all custom emoji's in the db with use <db_name> then db.rocketchat_custom_emoji.deleteMany({ }) The icon appeared again :), Is there a limit set somewhere, for the number of emoji's after which the icon stops appearing?

**Comment by MarcosSpessatto** [comment]
@ChuckB0ris I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13031) solved this problem. Can you please update your server version and try again? Thanks.

**Comment by algomaster99** [comment]
@MarcosSpessatto It's there in version `1.0.0-develop`. 
![custom](https://user-images.githubusercontent.com/35191225/53551118-7e185800-3b5e-11e9-9ebc-9e41d4a372ae.png)

**Comment by ChuckB0ris** [comment]
@MarcosSpessatto Unfortunately I can't update RocketChat in prod on my liking :), Icon appeared after I manually deleted all custom emoji's, maybe the sheer number was to much "2889". Now the icon is visible again. I'll try again after I upgrade to import emoji's, I used this https://github.com/amtypaldos/rocketchat-emoji-upload
