### ISSUE TITLE
LiveChat / RegisterVisitor / Curl Command

### ISSUE THREAD

**Issue by NiBOLT** [RocketChat/Rocket.Chat#13560]
### Description:
I am getting the following error/results returned when using the CURL command (when copied from the online documentation ) to register a visitor, please can you advise on how this is resolved

![image](https://user-images.githubusercontent.com/45275040/53291186-4351a100-37a7-11e9-925c-ed2ecd4e930b.png)

Register Visitor CURL Command

curl -X POST 
-H "Content-type:application/json" 
http://localhost:3000/api/v1/livechat/visitor 
-d '{"visitor": {"name": Livechat Visitor, "email": "[visitor@rocket.chat](mailto:visitor@rocket.chat)", "token": "iNKE8a6k6cjbqWhWd", "phone": "55 51 5555-5555", customFields": [{ "key": "address", "value": "Rocket.Chat street", "overwrite": true }] }'

### Steps to reproduce:
1. Run the CURL command from command shell

### Expected behavior:

Visitor successfull registered

### Actual behavior:

![image](https://user-images.githubusercontent.com/45275040/53291202-93c8fe80-37a7-11e9-8180-7bf6cfd97136.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

![image](https://user-images.githubusercontent.com/45275040/53291308-025a8c00-37a9-11e9-94e8-5b36da196348.png)

**Comment by renatobecker** [comment]
Please, take a look at here:
https://github.com/RocketChat/docs/issues/1103#issuecomment-467175588

Thanks.
