### ISSUE TITLE
[style] Enforce Code Style / Linting / Etc

### ISSUE THREAD

**Issue by blaskovicz** [RocketChat/Rocket.Chat#1356]
This is more of a meta issue, but I'd like to start adding some linters, code style enforcement, etc.

As an example, in a lot of the coffeescript files (eg: `client/views/app/message.coffee`), I see the use of explicit `this.` and `return` whereas, to follow the coffeescript convention, `@` should be used and `return` can often be omitted unless returning from a function early.

I'd be willing to undertake this if the code owners are on board with it.
##

**Comment by geekgonecrazy** [comment]
I'd love to see some code style linting.  We already have some discussion around a contribution doc #1163  If you're up for it, we welcome PR's.  :smile_cat:

**Comment by MartinSchoeler** [comment]
Today we are using code and css linters, so i will close this.
