### ISSUE TITLE
Notifications do not work

### ISSUE THREAD

**Issue by alandroid** [RocketChat/Rocket.Chat#13571]
I can see the future. This issue will never get fixed and unfortunately rocketchat is a failed project. I will have to abandon it since no one wants to use it because notifications do not work.

If your going to make a chat system, at least make sure key features are working from the start. Instead of making every part of the project an after thought.

At this rate, i will, start looking at alternatives. Until further notice this entire project sucks, sorry.

I'm switching to Mattermost tonight, it looks like a chat system whos basic features actually work! That is asking for too much from this project.

**Comment by geekgonecrazy** [comment]
@alandroid I understand the urge to post your frustrations.  But it is not productive to you, us or anyone else to just say they "do not work".

What specifically about them do not work?  If you tell us specifically we would be more than happy to take a look.

I get many notifications every single day and so do many people.  So knowing what isn't working for you may allow us to help you get yours working, or improve things to work like expected.

**Comment by ggazzo** [comment]
I don't think its entirely true...
![image](https://user-images.githubusercontent.com/5263975/53445195-c3b61300-39ee-11e9-9655-419c1a829393.png)


we have a "complex" flow to decide if the user will receive notifications or not...

we are drawing that flow, please check:
https://whimsical.co/Bngw3kot3wWPMAAJTebDUJ
