### ISSUE TITLE
Livechat

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#13572]
Hi,
Livechat Rest APi does not have the option to send images, files and audios, there is some possibildiade, today I use the command below but only sends a message
curl -X POST -H "Content-type: application / json" http: // localhost: 3000 / api / v1 / livechat / message -d "{\" token \ ": \" $ token\ ", \" rid \ ": \" $ roomid \ ", \" msg \ ": \" $ msg \ "}"

**Comment by alandroid** [comment]
Every feature does not work.

**Comment by josep112** [comment]
Will it be deployed soon? Directing to a department is also not available in the api

**Comment by ggazzo** [comment]
hey @josep112 actually we send files over rest api

please look here:
https://github.com/RocketChat/Rocket.Chat.js.SDK/blob/multiple-clients/src/lib/api/Livechat.ts#L53

and here is a place that I know we are using that method:
https://github.com/RocketChat/Rocket.Chat.Livechat/blob/45b025726052084eed77a9a9fb4dfb7be28cc382/src/routes/Chat/container.js#L133


the javascript way to do that:
```javascript
    const headers = {
      'x-visitor-token': this.credentials.token
    }
    const formData = new FormData()
    formData.append('file', params.file)
    return this.post(`livechat/upload/${params.rid}`, formData, false, undefined, { customHeaders: headers })

```

**Comment by ggazzo** [comment]
> Will it be deployed soon? Directing to a department is also not available in the api

@josep112 

I didnt get this one, the user cant change the department over restapi or the agent?

**Comment by renatobecker** [comment]
> Will it be deployed soon? Directing to a department is also not available in the api

@josep112 

You don't send messages to `departments`, you send messages to `rooms` that may be assigned to a department(or not).

You can achieve it easily by using our Livechat REST API endpoints:

1 - Registering Livechat Visitors(When you pass the `department` field)
https://rocket.chat/docs/developer-guides/rest-api/livechat/visitor/#register-a-new-livechat-visitor
2 - Get a new Livechat Room
https://rocket.chat/docs/developer-guides/rest-api/livechat/room/#query-parameters
3 - Send Livechat Messages
https://rocket.chat/docs/developer-guides/rest-api/livechat/message/#payload

**Comment by josep112** [comment]
Guilherme, obrigado pela resposta!
Seria possível usar via curl tentei algo do tipo abaixo mas sem sucesso
curl -X POST -H "Content-type: application/json" http://localhost: 3000/api/v1/livechat/upload -d '{"rid": "$roomid", "file": "imagen.jpg"}'

**Comment by josep112** [comment]
> > Will it be deployed soon? Directing to a department is also not available in the api
> 
> @josep112
> 
> You don't send messages to `departments`, you send messages to `rooms` that may be assigned to a department(or not).
> 
> You can achieve it easily by using our Livechat REST API endpoints:
> 
> 1 - Registering Livechat Visitors(When you pass the `department` field)
> https://rocket.chat/docs/developer-guides/rest-api/livechat/visitor/#register-a-new-livechat-visitor
> 2 - Get a new Livechat Room
> https://rocket.chat/docs/developer-guides/rest-api/livechat/room/#query-parameters
> 3 - Send Livechat Messages
> https://rocket.chat/docs/developer-guides/rest-api/livechat/message/#payload

Renato, já faço dessa forma! 
No Livechat eu adiciona Departamentos e neles os agentes, Por exemplo tenho um departamento Suporte com o agente Jose e um Departamento Atendimento com o agente Joao, gostaria de direcionar o atendimento para o departamento e não para a sala onde os 2 agentes nesse caso podem atender a mesma chamada

**Comment by juliomac** [comment]
It is possible! (É possível)

// Send to Department A
 curl -X POST \
      -H "Content-type:application/json" \
      http://localhost:3000/api/v1/livechat/room.transfer \
      -d '{"rid": "n5MvWu8BLxbuPAQdJ", "token": "CjKEmxqAsBbsNJ5ft", "department": "yB8MwM7oZ2FsKyHzM"}'


//send to Department B    
       curl -X POST \
            -H "Content-type:application/json" \
            http://localhost:4000/api/v1/livechat/room.transfer \
            -d '{"rid": "n5MvWu8BLxbuPAQdJ", "token": "CjKEmxqAsBbsNJ5ft", "department": "cohN55MkQE24wH8K3"}'

**Comment by josep112** [comment]
Enviar Arquivo pelo Livechat resolvido segue os passos abaixo para quem precisar:
general -> Rest api -> ativar CORS
rid=RGaWhZ47PYb7dBNjS
curl -X POST http://localhost:3000/api/v1/livechat/upload/RGaWhZ47PYb7dBNjS -H 'x-visitor-token: xqAsBbsNJ5ft' -F 'file=@/usr/src/rocketchat-realtime/whatsapp/imagem.jpeg'

**Comment by josep112** [comment]
> It is possible! (É possível)
> 
> // Send to Department A
> curl -X POST 
> -H "Content-type:application/json" 
> http://localhost:3000/api/v1/livechat/room.transfer 
> -d '{"rid": "n5MvWu8BLxbuPAQdJ", "token": "CjKEmxqAsBbsNJ5ft", "department": "yB8MwM7oZ2FsKyHzM"}'
> 
> //send to Department B
> curl -X POST 
> -H "Content-type:application/json" 
> http://localhost:4000/api/v1/livechat/room.transfer 
> -d '{"rid": "n5MvWu8BLxbuPAQdJ", "token": "CjKEmxqAsBbsNJ5ft", "department": "cohN55MkQE24wH8K3"}'

Juliomac vou testar, obrigado

**Comment by renatobecker** [comment]
@josep112, is your case resolved?
If so, please close this issue, thanks.

**Comment by josep112** [comment]
Yes, in parts, now I have the problem of when I send the pdf it adds pdf.ini, but on what we say acim already I will close
