### ISSUE TITLE
New channels lack owner

### ISSUE THREAD

**Issue by luckenbach** [RocketChat/Rocket.Chat#13576]
### Description:

Newly created channels lack an owner

### Steps to reproduce:

1. Login to self-hosted Rocket Chat
2. Create a new channel
3. Attempt to edit channel

### Expected behavior:

The initial creator of a channel should be the owner with abilities to edit

### Actual behavior:

Newly created channel lacks an owner and the user that created the room is unable to edit the channel

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System:  Kubernetes
- Deployment Method: Docker
- Number of Running Instances:  3
- DB Replicaset Oplog: Yes
- NodeJS Version:  v8.11.4
- MongoDB Version: 3.6.9

--

### Additional context

N/A

### Relevant logs:

N/A

**Comment by fliptrail** [comment]
I did not encounter this issue. Please try to upgrade to a newer version of Rocket.Chat server

**Comment by luckenbach** [comment]
If I upgrade and I continue having this issues what are the next steps?

**Comment by fliptrail** [comment]
Well, I was using the latest version of Rocket.Chat and I did not encounter it. So, most probably you also won't. But if still you encounter this issue, Rocket.Chat community would be ready to help.

**Comment by luckenbach** [comment]
0.74.3 is the latest.

**Comment by hitochan777** [comment]
I am encountering the same problem with 0.74.2

**Comment by luckenbach** [comment]
This appears to no longer be an issue with channels created after upgrading to 1.0.0-rc.1
