### ISSUE TITLE
Default styles for Terms of Service and Privacy Policy are hideous

### ISSUE THREAD

**Issue by robguinness** [RocketChat/Rocket.Chat#13577]
### Description:

The default styles for Terms of Service and Privacy Policy are hideous.

### Steps to reproduce:

1. Add a few `<p>` and `<h1>` tags to the Privacy Policy or Terms of Service (Layouts->Content).
2. Open the Privacy Policy or Terms of Service links form the login page.

### Expected behavior:

Should look at least decent.

### Actual behavior:

Looks terrible (see screenshot below).

![rocket_chat_pp](https://user-images.githubusercontent.com/730957/53472761-3f58a400-3a71-11e9-951c-27bb42171bab.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: Ubuntu 18.04 (4.4.0-141-generic)
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled?
- NodeJS Version: v8.11.3
- MongoDB Version: 3.2.7?

**Comment by Gaurav-Punjabi** [comment]
Can I solve this issue ?

**Comment by robguinness** [comment]
This is open source, so I think the answer is yes!

**Comment by Gaurav-Punjabi** [comment]
Can you tell in which folder the terms file is located in ?

**Comment by wreiske** [comment]
> Can you tell in which folder the terms file is located in ?

You can use the search in the upper left hand of GitHub to find the files associated with terms of service:
https://github.com/RocketChat/Rocket.Chat/search?q=terms+of+service&unscoped_q=terms+of+service

That search shows a router layout here:
https://github.com/RocketChat/Rocket.Chat/blob/fd47795f753701cb6f82cb7663baadfd82ced8fc/client/routes/router.js#L110

After further searching, that is a cmsPage, so it will be included in:
https://github.com/RocketChat/Rocket.Chat/blob/79b381bca31f04bded15eb67c8b75fdcee4d0767/packages/rocketchat-ui/client/views/cmsPage.html

**Comment by codekhal** [comment]
@wreiske very well explained! Thanks, you cleared some of my doubts too :)

**Comment by Gaurav-Punjabi** [comment]
I am working on this issue @wreiske

**Comment by fliptrail** [comment]
Since it has been 3 days, I am making a PR on this
