### ISSUE TITLE
[IMPROVE] Extend Livechat API

### ISSUE THREAD

**Issue by renatobecker-zz** [RocketChat/Rocket.Chat#13583]
Extend the Livechat Realtime API, supporting new methods and events, such as:

- [x] Allow changing the widget language( [PR #214](https://github.com/RocketChat/Rocket.Chat.Livechat/pull/214))
- [x] Allow hiding/showing the widget
- [x] On widget show event
- [x] On widget hide event
- setCustomTexts
- Goes online/offline mode according to agents availability(Real-time) - it needs to consider office hours as well
- On agents available event
- On agents unavailable event
- [x] assign agent
- [x] Unassign agent
- [x] On agent(assigned to the chat) status change
- [x] On agent data change(In addition, we need to reload the agent avatar if it has been changed)
- [x] Allow minimizing/maximizing the widget
- Create `init` API method, allowing to pass a `config` object containing a set of configurations, such as overriding default messages, listen to callbacks and so on.

Sponsored: 
- [x] Create a method to set `mode=popout`(url parameter). This method will make easier the implementation in webviews.

**Comment by jervis446** [comment]
hey @renatobecker, can I know the meaning of "sponsored" tag meaning?

**Comment by knrt10** [comment]
> Allow hiding/showing the widget
On it

**Comment by knrt10** [comment]
> On widget show event 

On it

**Comment by salviof** [comment]
Please do that, Chat  widget show event, that little window, is'nt comercial..

**Comment by foss-** [comment]
@knrt10 Are you still working on this? "Allow hiding/showing widget" is some highly interesting functionality. So if this works already, it would be great if code could be merged and if other features are not yet done, maybe this issue here split up into one that is mergable and one with the remaining additional features.

**Comment by renatobecker** [comment]
> @knrt10 Are you still working on this? "Allow hiding/showing widget" is some highly interesting functionality. So if this works already, it would be great if code could be merged and if other features are not yet done, maybe this issue here split up into one that is mergable and one with the remaining additional features.

The `show/hide` Widget is a feature already supported.
https://rocket.chat/docs/developer-guides/livechat-api/#change-widget-visibility

**Comment by foss-** [comment]
My mistake then. I thought this would add a toggle to RC client to show / hide Livechat on the webpage. Looking to only show Livechat when a support agent is available and hide it if not. Wether that is done automatically or via a toggle is not so important. The current solution would mean to constantly change the widget code. Should I file a new feature request for this?
