### ISSUE TITLE
Embed link opens in same tab

### ISSUE THREAD

**Issue by granttoday** [RocketChat/Rocket.Chat#13581]
### Description:

When someone posts a link it will embed it and if you click the title of the embed it will open in the same tab. The link that was sent was a Spotify Album link

### Steps to reproduce:

1. A channel
2. Send a link (possibly just spotify or spotify albums)
3. Click on the title of the embed

### Expected behavior:

To open the link in another tab like all the other links

### Actual behavior:

Opens in the same tab

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: CentOS 7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: Docker
- MongoDB Version: Docker

**Comment by fliptrail** [comment]
I would try this today

**Comment by bhardwajaditya** [comment]
I will solve this by today

**Comment by fliptrail** [comment]
@granttoday It is opening in a new tab only. Try to update your RocketChat server. If someone else too agrees with I am saying then I guess this issue can be closed.

**Comment by bhardwajaditya** [comment]
@fliptrail it's an issue. I have fixed it will make a pull request in few minutes. Try clicking on the song link inside the embed.

**Comment by fliptrail** [comment]
Ok then, go forward with it. I still can't see it though.
