### ISSUE TITLE
Livechat no return conversation to the agent

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#13593]
### Description:

I use Livechat with the guest service strategy. After finishing a conversation in Livechat, click on the return the conversation is sent to all agents, I make the caputra in an agent normalemnte, but does not release the chat to enter the message, below the message appears: This conversation is already closed .

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v8.15.0
- MongoDB Version: v3.6.10

**Comment by renatobecker** [comment]
@josep112, please give us more details about this case, I mean.. If I get it right, do you want to send messages in a Livechat room that is already closed?

**Comment by josep112** [comment]
@renatobecker, Right! I understand that if there is the return key and with it I return to the room for the attendants should release the box to continue the conversation

**Comment by renatobecker** [comment]
Yes, if you're returning the chat to the pool, the agents will be able to continue chatting normally.
But what you described is that the agent's are not able to chat because the chat is closed, so it seems like you're clicking on `Close` button instead of the `Return` button.
I just can't simulate this case so I would suggest you to record a video screen or something like this.. are you willing to do this?

**Comment by josep112** [comment]
@renatobecker 
You're right I'm closing the room. Is there no possibility of returning in the conversation after closing the room? If it was not clear I can record the screen without problems

**Comment by renatobecker** [comment]
After closing the conversation the room no longer accepts new messages.

**Comment by josep112** [comment]
Is not there a way to do this? I am using Livechat with Whatsapp and since there is no calendar to send a direct message to the user, it would be great if he could return the call to send the message.

**Comment by renatobecker** [comment]
@josep112, yeah, I got it.
But, if want to keep chatting further, why do you close the chat?

**Comment by josep112** [comment]
@renatobecker 
A necessidade é a seguinte: Estou falando com uma pessoa hoje e termino a conversa, naturalmente fecho o chat ok! Amanha necessito chamar essa pessoa por algum motivo , passar uma informação que faltou por exemplo, então se conseguisse retornar a chamada seria muito util pois estou fazendo isso com uma integração por WhatsApp.

**Comment by renatobecker** [comment]
@josep112, please write in English.
In this case, you can just hide de room and then it will not be displayed on your side bide until you restart chatting.

**Comment by josep112** [comment]
@renatobecker 
Yes I thought about it but this way the calls are all open in my case I will have to find another solution, thanks for the answers
