### ISSUE TITLE
custom oauth is ignoring /etc/hosts

### ISSUE THREAD

**Issue by mettke** [RocketChat/Rocket.Chat#13592]
### Description:

I'm running rocketchat behind a reverse proxy with custom OAuth. My OAuth system is running in its own docker container behind a reverse proxy and cannot be reached by the rocketchat docker container using the external IP. Instead, both are connected using the same docker network and can reach each other using the internal IP. To make sure that the rocketchat server can reach the OAuth server, I added an entry to `/etc/hosts` with the pointing the OAuth server domain to its internal IP. The domain is correctly resolved when using curl, but not in rocketchat itself.

### Steps to reproduce:

1. Setup rocketchat behind a reverse proxy with custom OAuth
2. Try to login using OAuth

### Expected behavior:

rocketchat uses the IP from `/etc/hosts` and connects to the <sso-url>

### Actual behavior:

rocketchat resolved the external IP and tries to connect to it.

### Server Setup Information:

docker container: rocketchat/rocket.chat:0.74.3

### Additional Information

When I try to access the <sso-url> via curl it connects to the IP specified in `/etc/hosts`. Therefore, for some reason, rocketchat uses the external IP of the domain instead of the one defined in `/etc/hosts`

### Relevant logs:

```
{"line":"392","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with keycloak at <sso-url>. tunneling socket could not be established, cause=connect ENOPROTOOPT 120.120.120.120:443","time":{"$date":1551442909829},"level":"warn"}
Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with keycloak at <sso-url>. tunneling socket could not be established, cause=connect ENOPROTOOPT 120.120.120.120:443
    at CustomOAuth.getAccessToken (packages/rocketchat:custom-oauth/server/custom_oauth_server.js:118:18)
    at Object.OAuth.registerService.query [as handleOauthRequest] (packages/rocketchat:custom-oauth/server/custom_oauth_server.js:174:29)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:161:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  message: 'Failed to complete OAuth handshake with keycloak at <sso-url>. tunneling socket could not be established, cause=connect ENOPROTOOPT 120.120.120.120:443' }
```

**Comment by Exordian** [comment]
it's not a rocketchat problem. docker container can't even access the `/etc/hosts` from the host. refer to the docker documentation about modifying `/etc/hosts` within a docker container [1]

[1] https://docs.docker.com/engine/reference/run/#managing-etchosts

**Comment by mettke** [comment]
@Exordian 
Thanks, but I'm talking about the hosts file inside the container. 

```
rocketchat@d7414bde248a:/app/bundle$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.20.0.3	<sso-domain>
172.20.0.10	d7414bde248a
```

```
rocketchat@d7414bde248a:/app/bundle$ getent ahosts <sso-domain>
172.20.0.3      STREAM <sso-domain>
172.20.0.3      DGRAM  
172.20.0.3      RAW
```

**Comment by mettke** [comment]
I was able to fix it. For some reason, when the following environment variables are set, rocketchat is not using the ip from `/etc/hosts` but from an external domain server. After removing them, it uses the correct specified ip.

```
- HTTP_PROXY=<domain>
- HTTPS_PROXY=<domain>
```
