### ISSUE TITLE
Escape HTML tags instead of stripping them

### ISSUE THREAD

**Issue by joepie91** [RocketChat/Rocket.Chat#136]
Also filing this as requested :)

Currently, if you type the following...

```
text<something>text
```

... this becomes...

```
texttext
```

Instead, it should probably just escape `<` (to `&lt;`), `>` (to `&gt;`), etc., so that the text remains visually the same. As from the perspective of a chat user, 'HTML tags' are not meaningful (and simply another form of plaintext), stripping them out is certainly not the correct option.

**Comment by rodrigok** [comment]
Thanks @joepie91 I will work on it today.

**Comment by rodrigok** [comment]
Hi @joepie91 I tried this in http://rocket.chat and this works.
Can you test it?

**Comment by joepie91** [comment]
Seems to work great, thanks! :)
