### ISSUE TITLE
User is unable to enter multiple emojis by clicking on the emoji icon

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#13603]
### Description:

The user is not able to add multiple emojis by clicking on the emoji icon. This is caused due to the absence of space between two inserted emojis.

### Steps to reproduce:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40834245/53687837-c0f54e00-3d5f-11e9-9c9a-b5cee7feb591.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-develop
- Operating System: Ubuntu 18.0.4 LTS
- Deployment Method: Local
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

I guess one fix would be to automatically add space after an emoji is inserted. This would make sure that keyword detection code works correctly. This won't interfere with other spacing. I am working on it.

**Comment by knrt10** [comment]
This is surely a fix.

**Comment by Kailash0311** [comment]
any updates on this? I would like to take this up

**Comment by Kailash0311** [comment]
Also, worth mentioning, this doesn't happen when you manually add emoji using a colon (`:`).
That is, a space is added after you add a emoji icon that way.

**Comment by fliptrail** [comment]
@Kailash0311 To be honest, I was not able to fix this issue out. You can take this up if you want. 
I guessed that `space` would be the easiest method.
