### ISSUE TITLE
Desktop notificatrions not working

### ISSUE THREAD

**Issue by Col1n04** [RocketChat/Rocket.Chat#13600]
Hello, I am experienceing an issue where I dont get a Notification for my desktop Client (Windows 10) when a Message is being sent. The test messages are working and I did hear a sound when I first joined the RocketChat server but now it doesnt work.

### Steps to reproduce:

1. Enable Notifications for all Messages in the User settings
2. Enable Notifications  for all Messages in the Channel settings
3. Get a Message
4. No Notification shows up or makey a sound.

### Expected behavior:

A Notification should appear.

### Actual behavior:

When I do get a message My Rocketchat window starts flashing as if I would select it but wothoud unselecting my window i select.

### Server Setup Information:

Ubuntu 16.04
Installed RocketChat yesterday so it should be the newest installation

### Additional context

When I do get a message My Rocketchat window starts flashing as if I would select it but wothoud unselecting my window i select.

![unbenannt1231241542452455](https://user-images.githubusercontent.com/48140597/53681815-15acb080-3cef-11e9-94fd-bd1d0af5bc9f.PNG)
![unbenannt23123253123](https://user-images.githubusercontent.com/48140597/53681817-17767400-3cef-11e9-9e1b-fd0b1da01b63.PNG)
![unbenannt32465435](https://user-images.githubusercontent.com/48140597/53681822-29581700-3cef-11e9-9a61-664b9d6fb547.PNG)

**Comment by knrt10** [comment]
@Col1n04 please provide fill all the relevant information, otherwise, the issue would be closed. Cheers 👍

**Comment by Col1n04** [comment]
> 
> 
> @Col1n04 please provide fill all the relevant information, otherwise, the issue would be closed. Cheers 👍
Yeah sorry.. First time using GitHub i acidentally posted it but here you go!

**Comment by Col1n04** [comment]
Okay so I updated mongodb to 3.4 and this fixed the problem.
