### ISSUE TITLE
Emoji entered from web app is not rendered on mobile app correctly

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#13607]
### Description:

If I type an emoji in the web app and try to view to view the chat thread without opening it, then the emoji is not rendered. Instead, it is shown as plain text.

### Steps to reproduce:

1. Type an emoji in any thread on the web app
2. View the thread in the Android app

### Expected behaviour:

The emoji should be rendered correctly.

### Actual behaviour:

![whatsapp image 2019-03-03 at 9 28 46 pm](https://user-images.githubusercontent.com/40834245/53697835-8c36d480-3dfb-11e9-8773-dc608709bcc4.jpeg)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 - development
- Operating System: Ubuntu 18.0.4 LTS and Android 8.1.0 MIUIGlobal 10.2
- Deployment Method: (official server)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by wreiske** [comment]
Issues with the Android mobile app should be reported to  https://github.com/RocketChat/Rocket.Chat.Android/issues

**Comment by fliptrail** [comment]
I am so sorry for this, will update on the android repo
