### ISSUE TITLE
Using the Snap installed version the login page doesn't appear

### ISSUE THREAD

**Issue by mredbishop** [RocketChat/Rocket.Chat#13616]
### Description:
I installed the server using Snap. I then configured it from Chrome. It is working fine in this Chrome instance. It doesn't render the login page in any other browser on any other machine I've tested so far:

### Steps to reproduce:

1. Install on Ubuntu 18.04
2. Load in Chrome and configure the Admin user etc.
3. Open the site on another machine or browser or even an incognito window.

### Expected behavior:

It should render the login page.

### Actual behavior:

It briefly renders a text box then renders a blank grey screen

**Comment by knrt10** [comment]
@mredbishop can you please provide a screenshot?

**Comment by mredbishop** [comment]
This was caused by having the iFrame enabled with nothing in the URL. Whilst I totally appreciate that this is my fault, it would also be good if it didn't let you save that setting without filling in the details that are required.

![image](https://user-images.githubusercontent.com/1096293/53805284-a1b61680-3f41-11e9-8100-9b2779e3d305.png)

**Comment by FaizanZahid** [comment]
@mredbishop  awesome, fixed issue for us too.

**Comment by fais3000** [comment]
@mredbishop @knrt10  However, Iframes don't work now. Keeps loading. Works without iframe though

**Comment by jibeizhao** [comment]
guys @mredbishop @fais3000  @FaizanZahid  how do i reset the Enabled to False if it does not load at all?

**Comment by gabriellsh** [comment]
I tested this, and apparently it shows the correct login page now. Please, open a new issue if you still have problems. Also, thanks for pointing out the faulty setting :)
