### ISSUE TITLE
Code validation error for Integration script is permanent

### ISSUE THREAD

**Issue by svrnwnsch** [RocketChat/Rocket.Chat#13611]
### Description:

If you try to save a webhook script which has a SyntaxError this error will be shown to user.
![grafik](https://user-images.githubusercontent.com/1852828/53733852-90f29b80-3e82-11e9-83f6-1bdf628fa442.png)

If he updates the script and fixes the error and saves the now correct script. The error message still persists: 
![grafik](https://user-images.githubusercontent.com/1852828/53733693-1164cc80-3e82-11e9-812a-c9b9b1f9e423.png)

### Steps to reproduce:

1. Create webhook with script with false syntax.
2. Update webhook with correct script.

### Expected behavior:

After clicking save remove the error message if it is no longer valid.

### Actual behavior:

Error message does not get removed.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: linux

**Comment by svrnwnsch** [comment]
This could be related to #2504

**Comment by ulope** [comment]
I'm seeing the same. Once an integration script had a syntax error the message never gets removed.

**Comment by mbaev** [comment]
The same:
```
I20190806-23:16:30.154(0) ➔ System ➔ startup 
I20190806-23:16:30.155(0) ➔ +--------------------------------------------------+ 
I20190806-23:16:30.155(0) ➔ |                  SERVER RUNNING                  | 
I20190806-23:16:30.155(0) ➔ +--------------------------------------------------+ 
I20190806-23:16:30.155(0) ➔ |                                                  | 
I20190806-23:16:30.155(0) ➔ |  Rocket.Chat Version: 1.2.3                      | 
I20190806-23:16:30.156(0) ➔ |       NodeJS Version: 8.11.3 - x64               | 
I20190806-23:16:30.156(0) ➔ |      MongoDB Version: 3.4.20                     | 
I20190806-23:16:30.156(0) ➔ |       MongoDB Engine: wiredTiger                 | 
I20190806-23:16:30.156(0) ➔ |             Platform: linux                      | 
I20190806-23:16:30.156(0) ➔ |         Process Port: 3000                       | 
I20190806-23:16:30.156(0) ➔ |             Site URL: https://very-secure-string | 
I20190806-23:16:30.157(0) ➔ |     ReplicaSet OpLog: Enabled                    | 
I20190806-23:16:30.157(0) ➔ |          Commit Hash: d3e690ad7f                 | 
I20190806-23:16:30.157(0) ➔ |        Commit Branch: HEAD                       | 
I20190806-23:16:30.157(0) ➔ |                                                  | 
I20190806-23:16:30.157(0) ➔ +--------------------------------------------------+ 
```

**Comment by mbaev** [comment]
Temoprary workaround it's just type one any symbol (for example `!`) and save it. You will be notified with the following message:
![image](https://user-images.githubusercontent.com/6450526/63081378-84579080-bf54-11e9-955f-c80673429a74.png)

Next time you will insert potentially correct script you will be able to determine what is the error related to.
