### ISSUE TITLE
[IMPROVE] Block user button

### ISSUE THREAD

**Issue by knrt10** [RocketChat/Rocket.Chat#13627]
### Description:

This is UI/UX related bug. Block User button is a `microphone` right now, which should not be as far as I think. It would be better if we change the icon.

### Steps to reproduce:

1. Click on any user
2. Click on user info button on the top right with user icon on it.

### Expected behavior:

![Expected](https://user-images.githubusercontent.com/24803604/53907192-ac23fd80-4072-11e9-9fc0-b135318d5468.png)

### Actual behavior:

![Actual](https://user-images.githubusercontent.com/24803604/53907204-b219de80-4072-11e9-8c9f-1760cd829cc9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: **1.0.0-develop**
- Operating System: **MacOS**
- Deployment Method: **Local Server** 
- Number of Running Instances: **1**
- DB Replicaset Oplog: **no**
- NodeJS Version: **8.11.4**
- MongoDB Version: **3.6**

### Additional context

I will fix this.

**Comment by bhardwajaditya** [comment]
May I do this?

**Comment by knrt10** [comment]
@bharadwajaditya sorry, I already have commited, just need to push. Thanks again

**Comment by bhardwajaditya** [comment]
You changed the logo in the for loop which will change for all the actions. I corrected that by changing only for block user.

**Comment by knrt10** [comment]
@bhardwajaditya Thanks, you are right. But please remember this, when a PR is opened on an issue, you should not open a PR yourself. You would have suggested changes to the old PR. Hope this will help you in the long run. Cheers 👍

**Comment by bhardwajaditya** [comment]
Sorry, I am new to open source contributions. Will keep this in mind in future. Thanks for your help.
