### ISSUE TITLE
Android Push Notification: Exception in onLogin callback: TypeError: Cannot redefine property: loginAt

### ISSUE THREAD

**Issue by loymascarenhas** [RocketChat/Rocket.Chat#13620]
### Description:

Push Notification: Log shows as sent but after few seconds FCM returns a MismatchedSenderId error.
I have already verified  the FCM API key and FCM Sender ID.

### Steps to reproduce:

1. Configure Administration -> Push settings
![untitled](https://user-images.githubusercontent.com/29827547/53834607-793a1680-3f59-11e9-9da1-57a649260cd3.png)

2. Configure GCM API key and GCM project id
3. Restart Rocket.Chat server

### Expected behavior:

Receive push notification on Android

### Actual behavior:
Shows: 
`[34mI20190305-20:47:03.263(0) Push: configuring... 
[34mI20190305-20:47:03.264(0) Push.Configure { sendTimeout: 60000,   apn: undefined,   gcm:     { apiKey: '<api-key-from-FCM>',      projectNumber: '************' },   production: false,   sendInterval: 5000,   sendBatchSize: 10 } 
[34mI20190305-20:47:03.265(0) GCM configured 
[34mI20190305-20:47:03.268(0) Push: Send worker started, using interval: 5000 
[34mI20190305-20:47:03.484(0) ➔ System ➔ startup 
[34mI20190305-20:47:03.485(0) ➔ +-----------------------------------------------------------+ 
[34mI20190305-20:47:03.485(0) ➔ |                       SERVER RUNNING                      | 
[34mI20190305-20:47:03.486(0) ➔ +-----------------------------------------------------------+ 
[34mI20190305-20:47:03.486(0) ➔ |                                                           | 
[34mI20190305-20:47:03.486(0) ➔ |  Rocket.Chat Version: 0.74.3                              | 
[34mI20190305-20:47:03.487(0) ➔ |       NodeJS Version: 8.11.4 - x64                        | 
[34mI20190305-20:47:03.487(0) ➔ |             Platform: linux                               | 
[34mI20190305-20:47:03.487(0) ➔ |         Process Port: 3000                                | 
[34mI20190305-20:47:03.487(0) ➔ |             Site URL: https://****************  | 
[34mI20190305-20:47:03.488(0) ➔ |     ReplicaSet OpLog: Disabled                            | 
[34mI20190305-20:47:03.488(0) ➔ |          Commit Hash: 202a465f1c                          | 
[34mI20190305-20:47:03.488(0) ➔ |        Commit Branch: HEAD                                | 
[34mI20190305-20:47:03.489(0) ➔ |                                                           | 
[34mI20190305-20:47:03.489(0) ➔ +-----------------------------------------------------------+ `

![untitled1](https://user-images.githubusercontent.com/29827547/53843628-1b192d80-3f71-11e9-983c-265a21fc269a.png)

#### Error
`ANDROID: Result of sender: {"multicast_id":8190097161583612000,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 16.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4 - x64 
- MongoDB Version: 3.4

**Comment by loymascarenhas** [comment]
I solved this issue by using the Server Key instead of Legacy Server Key.

But I am still getting this error now
`[34mI20190306-15:52:06.100(0) ANDROID: Result of sender: {"multicast_id":8269478541425864000,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1551887526086644%7ec8bec80034af1a"}]} 
[34mI20190306-15:52:32.240(0) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
`

**Comment by MarcosSpessatto** [comment]
@loymascarenhas I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13553) solved this issue.

**Comment by MarcosSpessatto** [comment]
@loymascarenhas Can you please test again with the new version?
