### ISSUE TITLE
how to render jpeg image inline in chat room if i pass it as url

### ISSUE THREAD

**Issue by sggncucumber** [RocketChat/Rocket.Chat#1362]

**Comment by geekgonecrazy** [comment]
This functionality is already here.  If this isn't working for you, we will need to you to provide more information.

**Comment by sggncucumber** [comment]
thanks for your response earlier.

Just to be very specific.  I am passing screenshot as url (jpeg) to rocket
chat either directly from hubot/custom rest api.  I want to see the actual
image on rocket chat message (either preview/actual image).  How to get
this done as I am failing to achieve the same though tried multiple options
like sending as <img src=*> or passing it from node as 'fs' operation etc.,

**Comment by geekgonecrazy** [comment]
So a url sent via REST API does not show preview?  I assume a message sent normally does?  I know messages from hubot do, we have this working on the demo already: https://demo.rocket.chat

**Comment by sggncucumber** [comment]
It is not working from the beginning.  Basically the url is the jpeg image.  If I type the url directly in the chat window it shows the preview.  So not sure what is going wrong restapi -> hubot -> rocketchat.

Need your help to understand this better.
