### ISSUE TITLE
lastMessage incorrectly set as 'unread' when fetching room list 

### ISSUE THREAD

**Issue by luismachado** [RocketChat/Rocket.Chat#13631]
Hello,

So I'm working on the iOS version and I'm trying to implement read marks on the subscription list (to extend the already existing functionally inside the rooms) but I'm facing some weird behaviour from the API (so this might not be an issue with the app but with the server so I'm sorry if that's the case).

What happens is that when calling `https://localhost:3000/api/v1/rooms.get?updatedSince=...]` all the lastMessages for each subscription comes with the unread parameter set to false (even thou the message was already read, which I can confirm if I fetch the message list for the subscription).

Any idea of what might be happening here? Thanks!

**Comment by MarcosSpessatto** [comment]
@luismachado can you please paste here your result from these endpoints? To be more easy to find the bug. Thanks.

**Comment by luismachado** [comment]
Sure, calling https://MYCHAT/api/v1/rooms.get?updatedSince=2019-03-14T06:47:08Z
returns the list of subscriptions with the respective lastMessages, like this one:

`{
      "jitsiTimeout" : "2019-03-15T09:21:14.478Z",
      "lastMessage" : {
        "u" : {
          "_id" : "4JSXNR4dM4MDkbYFi",
          "username" : "luis.machado.2",
          "name" : "Luis Machado 2"
        },
        "alias" : null,
        "rid" : "4JSXNR4dM4MDkbYFirCL3DcjA3oeKSBSRj",
        "ts" : "2019-03-15T10:43:09.962Z",
        "_id" : "QEC4hc78xtuUxNT8Tg",
        "unread" : true,
        "attachments" : null,
        "groupable" : null,
        "_updatedAt" : "2019-03-15T10:43:10.033Z",
        "emoji" : null,
        "editedAt" : null,
        "msg" : "Yyy",
        "customFields" : null,
        "sandstormSessionId" : null,
        "avatar" : null,
        "reactions" : null,
        "channels" : [

        ],
        "mentions" : [

        ],
        "editedBy" : null
      }`

Now, the `unread` parameter is always returned as `true`, no matter if the message was already set as read or not.

**Comment by MarcosSpessatto** [comment]
@luismachado seeing the result of the endpoint, I see that the `unread` property is not part of the room and lastMessage objects, the `unread` property is part of the subscription, and the subscription is not returned by this endpoint. The `unread` property that is part of the subscription has the counter of the messages unreads and is not a Boolean. What version of rocket are you using? :thinking:

**Comment by luismachado** [comment]
@MarcosSpessatto so this was on a 0.71.1. However I since tested on a 0.72.3 and the issue persists.
Not even looking at the logs what happens is that every time I log into an account and open a channel the last message is marked as unread (after a second or so it changes to read because the app calls the read endpoint immediately).

Some considerations:
- Tested it on more than one server (as mentioned above)
- Tested it through the API and also on multiple versions of the iOS app (including the development version and the one available on the store)
- For channels where the last message is older than the `updatedSince` specified on the api query the issue does not happen as the channel won't be listed on the response.

**Comment by luismachado** [comment]
@MarcosSpessatto I think I explained myself incorrectly. I was talking about the unread parameter inside the lastMessage part. Ignoring the 'updateSince' parameter, here's an example response for the `rooms.get` endpoint, right after a login:

```[REST][RESULT][https://MYSERVER.herokuapp.com/api/v1/rooms.get]: {
  "update" : [
    {
      "default" : true,
      "lastMessage" : {
        "sandstormSessionId" : null,
        "ts" : "2018-12-19T09:25:09.056Z",
        "rid" : "GENERAL",
        "mentions" : [
          {
            "username" : "luis.machado",
            "_id" : "mecR49d27JnxYFCQL",
            "name" : "Luis Machado"
          }
        ],
        "msg" : "olá @luis.machado ",
        "_id" : "tzCJ2ha4aCTFpGkg8",
        "_updatedAt" : "2018-12-19T09:25:09.110Z",
        "u" : {
          "name" : "Luis2",
          "_id" : "bXvNtp3DKhseui4sa",
          "username" : "luis2"
        },
        "channels" : [

        ]
      },
      "t" : "c",
      "_id" : "GENERAL",
      "name" : "general",
      "_updatedAt" : "2019-02-01T08:21:22.175Z"
    },
    {
      "t" : "d",
      "_updatedAt" : "2019-03-22T07:27:14.643Z",
      "_id" : "bXvNtp3DKhseui4samecR49d27JnxYFCQL",
      "lastMessage" : {
        "sandstormSessionId" : null,
        "ts" : "2019-03-22T07:27:14.559Z",
        "unread" : true,
        "rid" : "bXvNtp3DKhseui4samecR49d27JnxYFCQL",
        "mentions" : [

        ],
        "msg" : "Olá",
        "_id" : "QI41fp07HqLjzAavGP",
        "_updatedAt" : "2019-03-22T07:27:14.596Z",
        "u" : {
          "name" : "Luis Machado",
          "_id" : "mecR49d27JnxYFCQL",
          "username" : "luis.machado"
        },
        "channels" : [

        ]
      }
    },
    {
      "t" : "d",
      "_updatedAt" : "2019-03-18T11:06:49.365Z",
      "_id" : "cXtDvASq9xBPBsKnwmecR49d27JnxYFCQL",
      "lastMessage" : {
        "sandstormSessionId" : null,
        "ts" : "2019-03-18T11:06:49.213Z",
        "unread" : true,
        "rid" : "cXtDvASq9xBPBsKnwmecR49d27JnxYFCQL",
        "mentions" : [

        ],
        "msg" : "123",
        "_id" : "QN7WZqMRnyZvkumLr",
        "_updatedAt" : "2019-03-18T11:06:49.291Z",
        "u" : {
          "name" : "Luis F",
          "_id" : "cXtDvASq9xBPBsKnw",
          "username" : "luis.f"
        },
        "channels" : [

        ]
      }
    },
    {
      "t" : "d",
      "_updatedAt" : "2018-12-20T07:12:35.314Z",
      "_id" : "mecR49d27JnxYFCQLswYfc4Hum9uWiXa4s",
      "lastMessage" : {
        "sandstormSessionId" : null,
        "ts" : "2018-12-20T07:12:35.247Z",
        "rid" : "mecR49d27JnxYFCQLswYfc4Hum9uWiXa4s",
        "mentions" : [

        ],
        "msg" : "how are you?",
        "_id" : "uCyi4biopEXw5bNmk",
        "_updatedAt" : "2018-12-20T07:12:35.278Z",
        "u" : {
          "name" : "Luis Machado",
          "_id" : "mecR49d27JnxYFCQL",
          "username" : "luis.machado"
        },
        "channels" : [

        ]
      }
    }
  ],
  "remove" : [

  ],
  "success" : true
}```
 
As you can see two of the rooms (luis.f and luis2) show the lastMessage as unread (which is incorrect as they were read, which is also visible on the web app). The other two rooms don't even show the unread flag (the lastMessage on both is way older, don't know if that means something).

**Comment by MarcosSpessatto** [comment]
@luismachado sorry, the `unread` property is added in the room object when the message read receipt is enabled (I completely forgot :disappointed: ). Anyway, I opened [a PR](https://github.com/RocketChat/Rocket.Chat/pull/13919) that will fix it. Thanks for figured out this problem.
