### ISSUE TITLE
Could not add federated user with existing email address

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#13647]
I cannot add an user from another server if that user has the same e-mail address of another user in my local server.

**Comment by kiilo** [comment]
Yes,

thats quite anoying. In an large institution departments have their own rocketchat instances. Federation would come handy to bridge the silos ...

**Comment by alansikora** [comment]
@kiilo the RC1 version of Federation solves this issue. Keep in mind that the new version is a breaking change, with a whole new event system and a lot of underlying changes to prepare for the next big release.
