### ISSUE TITLE
total crash after attempt of adding webdav  (localhost)

### ISSUE THREAD

**Issue by fosBHY** [RocketChat/Rocket.Chat#13649]
### Description:

I have nextcloud and rocketchat on the same server.
I enabled webdav integration in rocketchat.
I added nextcloud via https://cloud.example.com/blabla link -> worked fine
I thought I'd try again with https://localhost/blabla link -> rocketchat crashed completely (and sadly I can't ssh into it right now)

### Steps to reproduce:

1. enable webdav integration
2. add https://localhost/remote.php/webdav/ instead of https://cloud.example.com/remote.php/webdav/
3. have a total crash

### Expected behavior:

tell me I'm doing it wrong. Not completely crash but give me an error message.

### Actual behavior:

crash

### Server Setup Information:

- Version of Rocket.Chat Server: newest probably, can't check right now
- Operating System: debian9
- Deployment Method: normal
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: cant check now
- MongoDB Version: cant check now

installed rocketchat about 2 weeks ago with help of https://rocket.chat/docs/installation/manual-installation/debian/ so I'll have the versions mentioned there.

### Relevant logs:
none, sorry. Rocketchat crashed completely and instantly and I have currently no way to ssh into the server

**Comment by himpierre** [comment]
Happend to me too. https://github.com/RocketChat/Rocket.Chat/issues/13191

**Comment by geekgonecrazy** [comment]
@fosBHY can you maybe ssh in and do again and get logs?  All of the above fields that you said can't check now are actually useful in helping. 

Especially the exception in the logs

**Comment by svoeth** [comment]
I have a similar problem. Nextcloud is on a different server.

I successfully added the webdav folder. But when i try to access it (klick on + in client and then on servername) the backend crashes with the following log:

`Jun 24 19:42:28 chat rocketchat[9158]: === UnHandledPromiseRejection ===
Jun 24 19:42:28 chat rocketchat[9158]: RangeError: Maximum call stack size exceeded
Jun 24 19:42:28 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:28 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:28 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:28 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:28 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:28 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:28 chat rocketchat[9158]:     at Array.forEach (<anonymous>)

[... this repeats about a thousand times ...]


Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at v.map.value (packages/ejson/ejson.js:575:33)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.map (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:575:14)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Array.forEach (<anonymous>)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
Jun 24 19:42:30 chat rocketchat[9158]:     at Object.DDPCommon.stringifyDDP (packages/ddp-common/utils.js:80:22)
Jun 24 19:42:30 chat rocketchat[9158]:     at Session.send (packages/ddp-server/livedata_server.js:470:34)
Jun 24 19:42:30 chat rocketchat[9158]:     at promise.then.result (packages/ddp-server/livedata_server.js:742:14)
Jun 24 19:42:30 chat rocketchat[9158]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jun 24 19:42:30 chat rocketchat[9158]: ---------------------------------
Jun 24 19:42:30 chat rocketchat[9158]: Errors like this can cause oplog processing errors.
Jun 24 19:42:30 chat rocketchat[9158]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Jun 24 19:42:30 chat rocketchat[9158]: Future node.js versions will automatically exit the process
Jun 24 19:42:30 chat rocketchat[9158]: =================================
`

**Comment by geekgonecrazy** [comment]
Closing due  to no response
