### ISSUE TITLE
Discussions - next steps and minor issues

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat#13644]
Following #13541, we've addressed some issues and defined how the new feature must improve:

### Bugs

- [x] Data to create discussions on direct messages is incomplete (#13646)
- [x] Cannot select more users to invite on "Create a new discussion" modal (#13646)

### Open for discussion

- [ ] Mentioning discussions?
- [ ] Nested discussions?
- [ ] Slash commands for discussion creation/handling?

### Improvements

- [x] Join without send a message
- [x] Limit size of `name` field
- [ ] Promote/convert discussions to channels/groups
- [x] Rephrase "has joined the channel" as "has joined the conversation"
- [ ] Improve attachment for quoting discussions
- [x] Show discussions as section option on popover

**Comment by bhardwajaditya** [comment]
May I work on this?

**Comment by fliptrail** [comment]
I am assuming that by limiting `name` field you meant, name of "thread". I am working on this, cause currently you can create a thread with a real long name like \:

![Screenshot from 2019-03-09 16-44-07](https://user-images.githubusercontent.com/40834245/54070836-49f21500-428b-11e9-8023-a2e9d08b50ad.png)

**Comment by knrt10** [comment]
@ggazzo can you explain a little about the first point in improvement `Join without send a message`?

**Comment by diegolmello** [comment]
I may be wrong, but isn't attachment fields just title/value/short?
With thread, this is the response:
```json
"fields": [
  {
    "type": "messageCounter",
    "count": 8
  },
  {
    "type": "lastMessageAge",
    "lm": "2019-03-11T17:30:31.905Z"
  }
]
```

**Comment by geekgonecrazy** [comment]
related: https://github.com/RocketChat/Rocket.Chat/issues/13673

Idk if want to include in this list or not

**Comment by sampaiodiego** [comment]
> I may be wrong, but isn't attachment fields just title/value/short?
> With thread, this is the response:
> 
> ```json
> "fields": [
>   {
>     "type": "messageCounter",
>     "count": 8
>   },
>   {
>     "type": "lastMessageAge",
>     "lm": "2019-03-11T17:30:31.905Z"
>   }
> ]
> ```

@diegolmello threads introduced those new types of attachments, so they can be rendered specially.
