### ISSUE TITLE
Dark theme for Rocket.chat

### ISSUE THREAD

**Issue by avsingh999** [RocketChat/Rocket.Chat#13652]
I didn't find any theme setting in rocket chat to change a theme color. I think the feature must be added for a better User Interface.
thanks : )

**Comment by fliptrail** [comment]
This is already in GSoC Idea list this year. Plus this is already a planned feature. This issue can be closed.

PS: **DO** follow the Issue/ PR template.

**Comment by avsingh999** [comment]
@fliptrail oh great sorry I didn't see.
Thanks :)

**Comment by avsingh999** [comment]
@fliptrail  But I see this for Android app. I was thinking about online rocketchat https://open.rocket.chat/home means we open rocketchat in a browser, there is no option for change theme.
thanks : )

**Comment by avsingh999** [comment]
@tassoevan  @fliptrail @Sing-Li  please correct me If I am wrong.

**Comment by fliptrail** [comment]
Let @tassoevan and @Sing-Li sir decide

**Comment by tassoevan** [comment]
I need to fix some conflicts here on #11071, but is not going to be merged for next release yet.

**Comment by recklessnl** [comment]
Guys, any update on this? @tassoevan @fliptrail @Sing-Li 

Android has had a lovely dark theme for a while now, I can't believe there isn't an option yet for desktop and web users to have an official dark theme. Must-have feature for the next release. Please share the status of this, can't wait for this to be added!

**Comment by whande1992** [comment]
Any predictions for releasing the dark mode?

**Comment by Weuxel** [comment]
Reminder, that there is still no dark mode in 2021....

**Comment by fumin** [comment]
Reminder, there's still no dark mode on 25th December, 2021!!!!!!!!
Even a monkey knows how to code a dark theme!!!!

**Comment by LoGiSTeRr** [comment]
Still no dark theme))
