### ISSUE TITLE
Bug report - when enabling package chatops: example doesn't load google maps

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#1365]
because needs "meteor add dburles:google-maps@1.1.5"
needs a comment somewhere as to how to get working...

**Comment by geekgonecrazy** [comment]
I believe this was removed based on some kind of conflict.  I believe this was @gmsecrieru ?

**Comment by geekgonecrazy** [comment]
@neurobe i'm actually going to close this.  

https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/packages#L76

This is commented out, so not a supported feature at all :) We have it commented out for a reason.  Please hit us up on the [chat server](https://demo.rocket.chat)
