### ISSUE TITLE
[Bug] Cannot invite user to Discussions

### ISSUE THREAD

**Issue by knrt10** [RocketChat/Rocket.Chat#13655]
### Description:

When creating a new thread, not able to invite users either by clicking on the username of pressing enter.

### Steps to reproduce:

1. Go to left navbar and click on create a new thread
2. Enter relevant info
3. Try adding the username to invite Users section

### Expected behavior:

Add users to the thread. 

### Actual behavior:

Modal closes and nothing happens

![2019-03-09 19 10 25](https://user-images.githubusercontent.com/24803604/54072331-69933880-429f-11e9-8941-4759f2e7863f.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: **open.rocket.chat**
- Operating System: MacOS
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11.4

### Additional Information:-

It is working fine in the local development server. `1.0.0-develop`.

cc @rodrigok @engelgabriel

**Comment by FredericaBernkastel** [comment]
Here.
Call of the Array.filter function without arguments.
![Clipboard-212](https://user-images.githubusercontent.com/16236235/54082536-5fc21180-4341-11e9-8fa4-d9bf3dd29bdc.png)

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/13644

**Comment by ggazzo** [comment]
thanks @knrt10 we fixed when we changed from 1.0.0-beta to 1.0.0 candidate
