### ISSUE TITLE
Can't add cyrillic username to room.  

### ISSUE THREAD

**Issue by psybox56** [RocketChat/Rocket.Chat#13665]
Hi. 
Can't add cyrillic username to room.  I have LDAP sync on my RC server. 
Some time ago, new user, in auth, have a LATIN username, example "Иванов Иван Иванович 
@ IVANOV", 
but after update, i have THIS. 
After auth, new user have a next login/name @Иванов
In RC client, i can't find this  user, in search list, for add in custom channel. 
In search list visible only LATIN login/name, example @ Sidorov @ Petrov
So, i have 50% of LATIN username and 50% cyrillic usernames

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
