### ISSUE TITLE
Building Docker fails due to missing file or directory .../.editorconfig

### ISSUE THREAD

**Issue by juliomac** [RocketChat/Rocket.Chat#13666]
I've got a forked Rocke.Chat running fine on OSX.

Trying to build a docker from it results:

    Step 13/21 : RUN meteor build --server-only --directory $BUNDLE_DIR
     ---> Running in a910ac56ac28
    WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
     - postcss@7.0.6 installed, postcss@^6.0.22 needed
     - postcss-load-config@2.0.0 installed, postcss-load-config@^1.2.0 needed

    Read more about installing npm peer dependencies:
     http://guide.meteor.com/using-packages.html#peer-npm-dependencies

    /home/node/.meteor/packages/meteor-         tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

     Error: ENOENT: no such file or directory, open '/home/node/src/packages/rocketchat-livechat/.npm/plugin/Livechat/node_modules/resolve/.editorconfig'
     => awaited here:
    at Promise.await (/home/node/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1530:15

    The command '/bin/sh -c meteor build --server-only --directory $BUNDLE_DIR' returned a non-zero code: 1

My Docker file as generated by the excellent [CycCoreSystems tool](
https://github.com/CyCoreSystems/go-meteor) is:

    FROM node:8.11.4 AS builder

    ENV BUNDLE_DIR /home/node/bundle
    ENV SRC_DIR /home/node/src
    ENV TMP_DIR /home/node/tmp

    USER node:node

    RUN mkdir -p $SRC_DIR $BUNDLE_DIR $TMP_DIR
   COPY --chown=node:node . $SRC_DIR

   RUN curl -o $TMP_DIR/meteor.sh 'https://install.meteor.com?release=1.8.0.2'; sh     $TMP_DIR/meteor.sh

    ENV PATH="/home/node/.meteor:${PATH}"
    WORKDIR $SRC_DIR
    RUN meteor npm install --production
    RUN npm run postinstall
    RUN meteor build --server-only --directory $BUNDLE_DIR
    RUN cd ${BUNDLE_DIR}/bundle/programs/server && npm install

    FROM node:8.11.4-slim

    ENV APP_DIR /home/node/app
    ENV BUNDLE_DIR /home/node/bundle

    USER node:node

    COPY --from=builder $BUNDLE_DIR $APP_DIR
    WORKDIR $APP_DIR/bundle

    CMD ["node", "./main.js"]

Only addition being ```RUN npm run postinstall``` as suggested in other threats.

What is causing this issue? How could it be fixed?

**Comment by geekgonecrazy** [comment]
are you git cloning in the docker build?  Or are you coping in?

If copying in make sure its a clean clone.  No node_modules etc.

**Comment by geekgonecrazy** [comment]
I’m suggesting to delete the node modules before you run your docker build

**Comment by sampaiodiego** [comment]
the build process has changed a lot.. pls let me know if you still have issues trying to build this way
