### ISSUE TITLE
Action Manager : (including Calendar) to schedule and trigger actions [$500]

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#1366]
eg gabrielhpugliese:supercalendar

Perhaps in a fly-in a la chat-ops. 
Many uses, for example:
- scheduling a key-word message to be sent to a Room (like "happy hour starts now")
- which might then be actioned by a hubot (like "action Wednesday's duties")
- or send emails out to specified recipients
- or action client specific code (like create room and send out invites, etc etc etc.)

Setting calendar events could be manual and by slash commands.
##

**Comment by neurobe** [comment]
Since "Calendar" not getting any traction here, perhaps "Action Manager" : an API to accept triggers (one of which is time, others can be eg "new user" and initiate a response (post a welcome note, post "happy hour starts now", execute that routine in the user-defined fly-in, etc) Thousands of uses, some of which overlap with hubot, but this is internal, fine grained, not script based, and tailored to the business.

**Comment by artisin** [comment]
I really like this idea and I can take point on it. I'm finishing up another open source project right now but after that I roll out a solution if someone has not done so already.

**Comment by neurobe** [comment]
this video addresses implementing FullCalendar under Meteor
https://www.youtube.com/watch?v=-fqJW1X22Cg
the corresponding code is here (although it uses FullCalendar v1.6 - before timezone support)
https://github.com/mcknightg/calapp

Meteor implementations that support FullCalendar 2.0+ (ie time-zones and languages) include:

https://github.com/rzymek/meteor-fullcalendar  (v2.6) (latest)
https://github.com/koretech/meteor-reactive-fullcalendar/ (v2.4)
https://github.com/koretech/meteor-fullcalendar-demo/blob/master/.meteor/packages (demo of above)
https://github.com/fermuch/meteor-reactive-fullcalendar (v2.3)
https://github.com/gquemart/meteor-reactive-fullcalendar  (v2.1)

$500 bounty set to expire in a couple of weeks
cheers

**Comment by neurobe** [comment]
and yes, FullCalendar supports the Google Calendar API :+1: 
http://slackhq.com/post/124767707715/googlecalendar

**Comment by artisin** [comment]
Two months later I'm still working on that open source project as before. Nevertheless, here are my thoughts; the FullCalendar integration is trivial, although, the hubot integration with fine grain control is a bit tricky on top of that in all likelihood to do what you're asking we would have to use the premium version of FullCalender which is problematic.

**Comment by neurobe** [comment]
I thought that maybe this functionality would be useful for RC..
http://fullcalendar.io/js/fullcalendar-2.6.0/demos/external-dragging.html
where one drop's regular actions like posting to a specified room or emailing someone about a meeting etc can be scheduled. Not sure that FulCalendar supports 'alarm clock' functionality - may have to 
separately poll the calendar Collection to look for events coming due.

I need the calendar for my own app (which will be a payload of RC) so am separately starting work on this but I don't have the skills to integrate it into RC - the calendar will needs to sit on my side of the fence rather than being part of RC. So I loose the ability to use it to send emails that I would indeed value. So still keen for someone to shake the life out of this. I think you would agree the potential uses of this are unlimited.
BTW, I'm using 
https://github.com/koretech/meteor-fullcalendar-demo/blob/master/.meteor/packages 
as my stepping off point on this.

**Comment by artisin** [comment]
I don't disagree with the merit of the idea; in fact I like the idea. However, like I said the implementation is problematic, we would have to use the paid version of FullCalendar since we would need the scheduler feature and due to this I don't think it's viable.

**Comment by neurobe** [comment]
@artisin  Yes, there doesn't seem to be an MIT-licenced alternative to the restricted FullCalendar Scheduler, and yes that scheduler would have been useful for managing a set of Channel resources. But I have been talking to a different point - a calendar to initiate an action at a programmed time - like sending out a notcie that Mr X & Ms Y are required in Room ABC in 10 minutes. Such notices can go out as messages on Public channels are/or email. This is the notion of an Action Manager, and I think the unrestricted-part of FullCalendar can do that nicely.

**Comment by europeanway** [comment]
whats the status?

**Comment by artisin** [comment]
@europeanway - I'm off the case since I no longer Meteor.

**Comment by talus46** [comment]
greetings was this implemented? or is still opened ?

**Comment by cynicoder** [comment]
Hello
I'd like to work on this, but I can't maintain a module by myself. Could a Rocketchat developer please clarify if such a feature is needed/wanted in the core source tree?

**Comment by geekgonecrazy** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/26

We want the ability inside of app framework so anyone can make an app utilizing it
