### ISSUE TITLE
When clicking on incoming livechat, message is blank

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#13668]
When Livechat Routing (Administration -> Livechat -> Routing) is set to Guest Pool, and there is an incoming livechat and you click on it

![image](https://user-images.githubusercontent.com/1986378/54128552-19c18800-43eb-11e9-90f9-41964db9ae95.png)

The message is coming as blank:

![image](https://user-images.githubusercontent.com/1986378/54128580-28a83a80-43eb-11e9-81ff-9b8a929d1760.png)

**Comment by renatobecker** [comment]
I detected the reason for this issue, it's related to the JS SDK method that returns the new room requested on the new Livechat client.
I'm going to fix it and then I'll request to update the Sales server instance.
