### ISSUE TITLE
Add ability to delete files

### ISSUE THREAD

**Issue by hosseinsmart** [RocketChat/Rocket.Chat#1367]
hi
When i upload a file in message box and i want to delete it, file deleted in message box but it remain on file list!

**Comment by geekgonecrazy** [comment]
So currently there is not a way to actually delete a file.  When you delete the message you are just deleting the message, that's it.  So nothing is not working, this is just a feature that hasn't been implemented yet.

**Comment by shirshman** [comment]
This is an important feature. If you make a mistake, you cannot correct it. When will this be available??

**Comment by internalfx** [comment]
+1

**Comment by mckuchta** [comment]
+1

**Comment by tuudik** [comment]
:+1:

**Comment by litewhatever** [comment]
+1
