### ISSUE TITLE
option to disable thread from administration 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#13678]
- Version of Rocket.Chat Server: 1.0.0 develop
- Operating System: ubuntu 16
- Deployment Method: none
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0
Add option in admin to disable threads and permission doesnt work correctly when i remove permission to user for using thread the user still able to create threads

**Comment by engelgabriel** [comment]
This option has been added
