### ISSUE TITLE
Pruning Messages orphans threads

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#13673]
### Description:

If you use the use the prune message feature as is often done in #sandbox on open.rocket.chat.  All threads are orphaned with no way to access them.  But they are still around.

### Steps to reproduce:

1. Start a thread
2. Copy url of the thread
2. Prune messages in a range that includes the message that you started a thread from
3. look at threads list its empty.
4. paste thread url back in

### Expected behavior:

Thread should either go away... or still be viewable in threads list

### Server Setup Information:

- Version of Rocket.Chat Server: current commit ( open.rocket.chat )

**Comment by sampaiodiego** [comment]
there is an option on `Global Policy` for `Retention Policy` called `Do not exclude thread messages`..

Looks like the same option is missing from `Prune Message` tab bar.

**Comment by ggazzo** [comment]
should we promote/transform to private rooms if we remove the parent channel?

**Comment by knrt10** [comment]
Ont it, would like to fix this

**Comment by sampaiodiego** [comment]
> should we promote/transform to private rooms if we remove the parent channel?

I don't think so.. we the user decides to delete messages that stared a thread, then we should also delete the threads IMO
