### ISSUE TITLE
EmojiOne version 2 is no longer supported or distributed

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#13686]
### Description:
Rocket.Chat currently uses a very outdated version of EmojiOne. 
From https://github.com/emojione/emojione#emojione-version-2
>EmojiOne version 2 is no longer supported or distributed.

### Server Setup Information:
- Version of Rocket.Chat Server: 70afb0eff49131870e787b69bd0b009ac304653b

**Comment by wreiske** [comment]
Also submitted as a feature request: https://github.com/RocketChat/feature-requests/issues/54

**Comment by sampaiodiego** [comment]
> Maybe Rocket.Chat could be one of those?

Unfortunately not. New EmojiOne license doesn't allow it to be embedded on open source projects, so we cannot upgrade it.

We are internally discussing in either not use an emoji library at all (in this case let platform render emojis) or migrate to twemoji.. see https://github.com/RocketChat/Rocket.Chat/issues/6740#issuecomment-470933462

I would like to not have multiple discussions (in many different issues) but I would like to know your thoughts on above as well.. feel free to respond here or in the referred issue.

**Comment by wreiske** [comment]
@sampaiodiego I've been in contact with EmojiOne and they would like to offer us a modified version of their free license for our use case (in Rocket.Chat).

![image](https://user-images.githubusercontent.com/6295044/54555977-472fa800-498e-11e9-94bb-380b7eae6d34.png)

**Comment by engelgabriel** [comment]
Hi @wreiske thanks for doing that! Let's move forward with that offer!

**Comment by wreiske** [comment]
I'll let them know we'd like to move forward. I'll work with their team and get a pull-request going here to upgrade to EmojiOne 4.5.

😀

**Comment by sampaiodiego** [comment]
@wreiske please ask them about adding such on the bottom of the picker.. like in this mockup:
![image](https://user-images.githubusercontent.com/8591547/54645652-6b1ce780-4a7b-11e9-9a1d-266289d1eb0c.png)

**Comment by alyssais** [comment]
Is there a copy of the full license that will apply to users of rocketchat after this upgrade? What terms does it impose on redistributors?
