### ISSUE TITLE
[BUG] Weird load behavior when changing workspace scope inside Directory -> Users

### ISSUE THREAD

**Issue by theorenck** [RocketChat/Rocket.Chat#13694]
### Description:
In Users tab inside Directory, when the workspace scope is changed it will trigger a weird load behavior, sometimes overlapping header contents for 'domain' and 'created at' columns. Is necessary to scroll in order to actually see the loader, making it very difficult for a user to understand that loading is going on.

### Steps to reproduce:

1. Go to Directory
2. Click on the Users tab
3. Change the workspace scope to Every workspace.

### Expected behavior:

The UI should keep its consistency.

**Comment by theorenck** [comment]
@alansikora can you take a look in this one? Thanks.

**Comment by damian-centrone** [comment]
This bug is no longer reproducible
