### ISSUE TITLE
[IMPROVE] Reordering of Channel topic, announcement, description for consistency

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#13698]
In the channel settings bar, 
Channel Topic, Channel Description and Channel Announcement are in a different order as compared to the channel settings edit menu. 
They should be same for consistency.

**Actual Behaviour**

![Screenshot from 2019-03-14 03-31-32](https://user-images.githubusercontent.com/40834245/54317673-d5f89980-4609-11e9-9cba-50b5d00bdb9f.png)
![Screenshot from 2019-03-14 03-32-45](https://user-images.githubusercontent.com/40834245/54317674-d6913000-4609-11e9-93d2-d007acf8e604.png)

Rocket.Chat Server Version - 1.0.0 -develop
I am working on it

**Comment by fliptrail** [comment]
I would correct this after #13699 is merged

**Comment by ggazzo** [comment]
fixex ;)
