### ISSUE TITLE
Add CAS protocol as account/login possibility

### ISSUE THREAD

**Issue by corecache** [RocketChat/Rocket.Chat#1369]
Hey there,

It would be nice to have the Jasig CAS protocol as login possibility, there seems to exist a meteor cas binding already at https://github.com/tvoglund/meteor-accounts-cas

If I understood this correctly, a bit of attribute binding, saving settings and graphical exposure is missing in order to get this up and running?

THanks a bunch!

**Comment by corecache** [comment]
Any directions or hints in order to get a prototype up and running with a current deploy from the Dockerfile? as in how to integrate this stuff with the node and folder structure of rocket.chat. Is a drop in sufficient? do the libraries need to be registered, exposed somehow?

**Comment by Sing-Li** [comment]
@corecache This is a non trivial development effort.  Assuming you are already familiar with Node.js, Coffeescript, and Meteor.  Please catch one of the core developers during UTC-4 working hour for some guidance.

**Comment by engelgabriel** [comment]
@corecache looks like you've done some progress on this? Do you want to do a PR adding your package so we can collaborate?

**Comment by engelgabriel** [comment]
This issue will help with #322

**Comment by corecache** [comment]
Some untested work for CAS 1.0 (only username given upon auth, no attributes) has been done in https://github.com/corecache/Rocket.Chat/tree/cas - I'll want to roughly test this stuff before arranging a PR

**Comment by engelgabriel** [comment]
Help testing this is welcome: https://github.com/RocketChat/Rocket.Chat/pull/1970

**Comment by corecache** [comment]
Just in case, this only covers CAS 1.0 for now.

**Comment by corecache** [comment]
At least some progress was made here, the CAS 1.0 did work, the CAS module was able to identify users against the CAS service, but login them in into RocketChat failed somehow: After the user authenticated against cas, the popup window for the cas auth vanished but nothing happened, I guess there is some mismatch for the returning response.

**Comment by engelgabriel** [comment]
@rodrigok is now focused on refactoring the LDAP package, maybe now it is a good time to collaborate, as they seem to share some logic.

**Comment by corecache** [comment]
I gave this another debugging session today and was able to get it up and running correctly.
The next steps include cleaning up the code, releasing the PR and some small twitch to show/hide the CAS login button depending on the plugin settings.

**Comment by corecache** [comment]
PullRequest: https://github.com/RocketChat/Rocket.Chat/pull/2183

**Comment by rodrigok** [comment]
Closed via #2183
