### ISSUE TITLE
Message grouping

### ISSUE THREAD

**Issue by joepie91** [RocketChat/Rocket.Chat#137]
It would be easier to read if successive messages from the same person were 'grouped' like in Skype, without including the avatar and name every time.

Example:

![selection_299](https://cloud.githubusercontent.com/assets/1663259/7976515/6b8cdc4a-0a7c-11e5-8208-cb204d267e77.png)

**Comment by joepie91** [comment]
By the way, to create the above mockup, all I did was to remove the elements for the avatar, name and time from the DOM. No style changes otherwise, so this shouldn't be too hard to implement :)

**Comment by riaan53** [comment]
Nice! +1

**Comment by rodrigok** [comment]
Great suggestion.

I will try to implement this.

Slack has a time to separate messages grouping, if you type a new message after some minutes slack create a new message group.

![captura de tela 2015-06-05 as 10 33 07](https://cloud.githubusercontent.com/assets/234261/8006929/5d5e3806-0b6e-11e5-83a2-4863593c5aef.png)

**Comment by joepie91** [comment]
Yeah, time-based grouping seems like a good addition to me as well.
