### ISSUE TITLE
One-click Deployment on Heroku not working

### ISSUE THREAD

**Issue by HaleyandtheComets** [RocketChat/Rocket.Chat#13703]
One-click deployment of Rocket Chat to Heroku is still advertised here, but it doesn't work:

https://rocket.chat/docs/installation/paas-deployments/heroku/

When one tries to deploy the app, the result is:

"
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.
"

![Screen Shot 2019-03-13 at 4 44 36 PM](https://user-images.githubusercontent.com/48548459/54342425-a2ae0e80-45f9-11e9-9fa0-4e4b7ba4dd8c.png)

**Comment by moyoteg** [comment]
@HaleyandtheComets any luck figuring this out?

**Comment by jaredmoody** [comment]
Duplicate of #13198

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
@rocket-cat close
