### ISSUE TITLE
Formatting buttons bug

### ISSUE THREAD

**Issue by DuckyTheKing** [RocketChat/Rocket.Chat#13708]
### Description:

The all formatting button below the message text area, are broken, when I click on it nothing happening and I have an error in my firefox console.
![Capture d’écran du 2019-03-14 14-32-55](https://user-images.githubusercontent.com/29342856/54360858-184fc400-4666-11e9-9a09-014f13c6c4ab.png)

### Server Setup Information:

- Version of Rocket.Chat Server: v1.0.0-dev
- Operating System: Ubuntu 18.10
- NodeJS Version: 8.11.4 - x64

**Comment by MarcosSpessatto** [comment]
@DuckyTheKing can you please update your server and try again? There have been a lot of changes  in this component recently.
