### ISSUE TITLE
Permalinks do not work correctly when invoked from outside the app whenever `General -> First Channel After Login` is set

### ISSUE THREAD

**Issue by cryptobanana** [RocketChat/Rocket.Chat#13704]
### Description:

If I (as an administrator) have set `General -> First Channel After Login` to a specific channel "A", then any permalink which I create and then follow from outside the application (i.e. pasting the link into the browser's address bar) will cause the application to immediately navigate away from that permalinked messages toward the most recent message of channel "A".

**Note** that clicking on a permalink within the application will however correctly navigate to the corresponding message.

### Steps to reproduce:

1. Ensure that the setting  `General -> First Channel After Login` is set to an existing channel.
2. Create a peramalink for any arbitrary message.
3. Paste the URL of that permalink directly into the browser's address bar.

### Expected behavior:

The browser should load the relevant message which the permalink references.

### Actual behavior:

The browser modifies the URL in the address bar, changing it to the channel specified by `General -> First Channel After Login`

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2 5fb5e574a1c1233e4497289f74da5af7cfae7437
- Operating System: Linux
- Deployment Method: snap 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version:

**Comment by cryptobanana** [comment]
I've identified the probable location of the problem behavior: https://github.com/RocketChat/Rocket.Chat/commit/8a6ef9bd568f25cf16304c97aa8835096d096944

Hi @antaryami-sahoo @MarcosSpessatto  @MartinSchoeler I'm including you also since you show up as contributors to this section of the code. My apologies in advance if it's not relevant to you.

**Comment by cryptobanana** [comment]
Hi @MarcosSpessatto could you assist me in having this bug addressed?

**Comment by Gandalf-the-Grey** [comment]
Still present in 1.0.2 (latest release)
