### ISSUE TITLE
Convert a Private Conversation room into a Private Group by adding users to it.

### ISSUE THREAD

**Issue by icode** [RocketChat/Rocket.Chat#1370]
Can i add people in my p2p chat rom?
This is a temp room, temp chat

**Comment by marceloschmidt** [comment]
I'll change the topic and keep this issue as a request for making a P2P room into a Private Group. Currently it's not supported.

**Comment by engelgabriel** [comment]
This is not possible and doesn't make much sense if you really think about it... that's why other chat apps don't support this either. On the best case scenario, it will create a NEW room with the extra users.
