### ISSUE TITLE
[BUG] duplicated rooms display & user can see other user private rooms

### ISSUE THREAD

**Issue by fasttrackhost** [RocketChat/Rocket.Chat#13715]
### Description:

Rooms are not correctly displayed. Sometimes not all rooms are displayed, and other times rooms are duplicated. In admin area, rooms are OK, its only wrong in the list of rooms.

### Steps to reproduce:

This error seems to apear only in if loged in with more than 1 account in same browser. 

### Expected behavior:

There should be only 1 room called: "General".

### Actual behavior:

But there are 2 rooms called: "General":
![AVATAR PROBLEM 1_2](https://user-images.githubusercontent.com/48553238/54372827-77203800-467c-11e9-8694-845d1c6abc45.png)

### Server Setup Information:

    Version of Rocket.Chat Server: 0.74.2
    Operating System: Linux x64, Ubuntu 18.04
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.
    NodeJS Version: v8.11.4
    MongoDB Version: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.

### Additional context

There seems to be a problem with onLogin and onLogout.

### Relevant logs:

 [34mI20190314-15:38:01.525(0) Exception in onLogout callback: TypeError: Cannot read property '_id' of null     at Accounts.onLogout.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:125:29)     at packages/callback-hook/hook.js:130:22     at _onLogoutHook.each.callback (packages/accounts-base/accounts_server.js:193:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogout (packages/accounts-base/accounts_server.js:192:24)     at MethodInvocation.methods.logout (packages/accounts-base/accounts_server.js:529:16)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

[34mI20190314-15:38:20.561(0) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by fasttrackhost** [comment]
Recently discovered that duplicated rooms occur when login in with 2 or more users.

Cache/cookie will remember the previous user rooms and show it even after logout and login with a different user.

Clearing browser cookies will fix it.

**The problem is that the second user login in will see the previous user private rooms.** So if a computer its used in a public location where several users have access to same computer and they use RocketChat, there will be a big privacy problem. Especially in Europe where laws are very strict about privacy.

Please fix this wrong behavior of cache/cookies fast and let SNAP update our installation.

**Comment by Ishrat1401** [comment]
This issue can't be replicated. It is not valid anymore as users can't log in with multiple accounts in the same browser.

**Comment by fasttrackhost** [comment]
@Ishrat1401 it was wrongly closed. nothing solved.

**Comment by damian-centrone** [comment]
Hello, maybe you can provide a recording of your screen using two different accounts in the same browser and actually sending messages with both of them. We tested on IOS and Windows and we couldn't reproduce.

thanks

**Comment by SardorbekR** [comment]
I am also having this kind of issue, I've implemented Rocket chat API in my app, issue occurring randomly, sometimes it creates two chat sometimes one. I am not sure what's the reason of it.
