### ISSUE TITLE
Avatar issues still in 0.74.2

### ISSUE THREAD

**Issue by fasttrackhost** [RocketChat/Rocket.Chat#13713]
### Description:

Several issues:

1. Avatars are not saved IF upload files -> File System -> is set to FileSystem. Avatar desepears after Saving (seen the bug in other issues, but it was marked as solved, and its not)

2. When using File System -> GridFS -> Avatars are deleted if using more than 1 account to login in same browser. Steps to reproduce: Login normaly with account 1, upload avatar, save -> everything ok. Now, disconnect account 1, and login with account 2, upload other avatar image, save -> everything seems ok, avatar is saved, but account 1 lost its avatar. It always happens.

3. Avatars sometimes dont display (see the 2 fotos).

### Steps to reproduce:

No modification to rocketchat files. It was installed using snaps, in a fresh linux x64 server, only used for rocket chat.

It doesnt seem to be a browser problem, it was detected only on Chrome, but in other comptures Chrome displays the avatars correctly. It only seems to happen in the browser that tries to Log In more than 1 account, but not always. The problem is the problem persists even after clearing browser cache.

At least for us it is important to be able to use more than 1 account to Log In in our Rocket Chat without having strange avatar problems.

### Expected behavior:

Avatars should be displayed like in this foto:
![AVATAR PROBLEM 1_1](https://user-images.githubusercontent.com/48553238/54369783-d11dff00-4676-11e9-80b0-bb93a1338701.png)

### Actual behavior:

Avatars are being displayed correctly as seen in this foto:
![AVATAR PROBLEM 1_2](https://user-images.githubusercontent.com/48553238/54369796-d67b4980-4676-11e9-9327-d73d3482520b.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.74.2
- Operating System:  Linux x64, Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.
- NodeJS Version: v8.11.4
- MongoDB Version: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.

### Additional context

RocketChat seems to be using a cache system with many probelms. Whenever I save something, changes are not visualy there, a page reload its needed. So RocketChat seems to be "Ajax" but its not, you still need to reload, because strange things happen if you try to save configuration 2 or more times with no reloading. So, at least for me. it would be useful to auto page reload after save button pressed (I dont want to explain each of my admins that they have to reload page after saving or things might brake up). Fancy effects are great but not useful if things are broken.

### Relevant logs:

Repeated errors of:

Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>) ...................

Exception in onLogout callback: TypeError: Cannot read property '_id' of null     at Accounts.onLogout.info ...............

No error related to filesystem.

**Comment by fabien4455** [comment]
You have 2 general ? 

Wait that's illegal

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
