### ISSUE TITLE
Sending a sound message always fails 

### ISSUE THREAD

**Issue by fasttrackhost** [RocketChat/Rocket.Chat#13719]
### Description:

While in chat, sending a sound message always fails. The circle never disapears until page reload.

There are 2 error messages in Console (F12), pasted them below.

There should be a notification for the user, not only on console.

Seems that RocketChat App does not ask for permission to use the microphone. But even so, it should send a mute sound, not only let the circle spin.

Happens in Iframe and directly in RocketChat server domain.

### Steps to reproduce:

1. Enter any room
2. Push the Microphone to record sound
3. Send it. It fails, and circle keeps spinning.

### Expected behavior:

Ask for permission to use microphone -> Record -> Send sound recorded to the room.

### Actual behavior:

Throws 2 errors in Browser Console, and circle spins forever. No error registered inside Rocked Chat Admin Panel, would be great to see it there too in case the error happens to a visitor, and not to a Admin user.

### Server Setup Information:

    Version of Rocket.Chat Server: 0.74.2
    Operating System: Linux x64, Ubuntu 18.04
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.
    NodeJS Version: v8.11.4
    MongoDB Version: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.

### Relevant logs:

MediaStreamError { name: "NotFoundError", message: "The object can not be found here.", constraint: "", stack: "" }

TypeError: this.recorder is undefined

**Comment by ggazzo** [comment]
@tassoevan could you check it please? (:
