### ISSUE TITLE
user session closes automatically after a few secs of LogIn

### ISSUE THREAD

**Issue by fasttrackhost** [RocketChat/Rocket.Chat#13718]
### Description:

User its automatically disconected and redirected to Log In Form, after a few seconds of Loging In. 
It happens randomly.
We use a script to auto logIn the user in a RocketChat Iframe integration, after the user Loges In the web that contains the Iframe. Sometimes it is automatically disconected just a few seconds after. Cant say why. Registry is full of errors related to onLogin and onLogout.

Proces of the script that loges in the user:

1. rest api try to login ( /api/v1/login )

2. if succesful-> jump to step 4

3. if unsuccesful -> try register user ( /api/v1/users.register ) -> try login again

4. get authToken and store it

5. load Iframe with src => "channel/general?resumeToken="+authToken

I must say that "resumeToken" query its the best thing in RocketChat!!
Just kidding, took 2 days of reading code and code and more code to get to it, since there is a BIG problem:
---------------------------------------------- NOT WORKING
                var iframe= document.getElementById(id_iframe);
	        var iframewindow= iframe.contentWindow? iframe.contentWindow : iframe.contentDocument.defaultView;

                iframewindow.postMessage({
			event: 'login_token_client',
			loginToken: '${authToken}'
		}, 'https://rocketChat.url');
---------------------------------------------- NOT WORKING
Tried with many posibilities "event" - "externalCommand" - "login" - "loginToken" - "authToken" - "http" - "https"
And as much as I could find in Rocket Chat code, none are realy suposed to work. Cant see another way to integrate RocketChat into another web without: "resumeToken". There should be more queries available in the docs (Docs are great, but are written by people with a lot of knowledge, for people that are suposed to have a lot of knowledge about Meteor, Node.js, RocketChat; and the problem I found myself its that I dont have a lot of knowledge so if the docs miss 1 word, I have to google several hours to find that missing word. Whats obvious for me, might not be obvious for others! And whats obvious for the rest, might not be obvious for me! Creating Docs its very time consuming, and I apreciate the info arround, but Docs are realy lacking useful info. Quick Start its realy pointing to nowhere. And Iframe integration its desesperating, to turn out it can be solved in 10 lines of code. Nobody considered in the Docs that maybe RocketChat LogIn Form and Own Authetication shouldnt be replaced by any other Auth system, and simply explain how to autheticate using RocketChat Own Authetication method, and make a silent auto User Authentication pass the Login screen).  Please dont never take out "resumeToken" and implement more similar querys. Its not a person relevant information and if used over https token should be secure. Anyway token its generated each time with a rest api login, just before using the query "resumeToken", and can be invalidated.

Coming back to user session problem:
There should be a Option to change Session storage: global browser,  for session, only valid for tab, only valid for 1 domain (when rocket chat its accesed using several domains). Definetly good to login once and be logedIN in all other domains that point to same RocketChat Server; but there are situations where you dont want to make login across all pages (diferent domains) a user has opened with a Rocket Chat implementation. The server administrator should be able to modify this behavior.

### Steps to reproduce:

Cant say what exactly makes the user get automatically disconnected and redirected to Login Form. It happens randomly and fortunatly not so many times. It seems to happen when used several users to logIn using same browser.

### Expected behavior:

User should have his session active.

### Actual behavior:

User session closes after a few seconds of Loging In

### Server Setup Information:

    Version of Rocket.Chat Server: 0.74.2
    Operating System: Linux x64, Ubuntu 18.04
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.
    NodeJS Version: v8.11.4
    MongoDB Version: Info not available in Rocket Chat Info (or badly translated to Spanish), so maybe it could be added in the future.

### Relevant logs:

 [34mI20190314-15:38:01.525(0) Exception in onLogout callback: TypeError: Cannot read property '_id' of null     at Accounts.onLogout.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:125:29)     at packages/callback-hook/hook.js:130:22     at _onLogoutHook.each.callback (packages/accounts-base/accounts_server.js:193:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogout (packages/accounts-base/accounts_server.js:192:24)     at MethodInvocation.methods.logout (packages/accounts-base/accounts_server.js:529:16)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

[34mI20190314-15:38:20.561(0) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
