### ISSUE TITLE
Not able to install on my windows machine.

### ISSUE THREAD

**Issue by abhinavsagar** [RocketChat/Rocket.Chat#13722]
### Description:

Not able to install on my windows machine.

### Steps to reproduce:

Run `npm install` 

### Expected behavior:

Should have proper installation.

### Actual behavior:

`> Rocket.Chat@1.0.0-develop postinstall C:\Users\Win 10\Desktop\github\Rocket.Chat
> node .scripts/npm-postinstall.js

Running npm-postinstall.js
'cp' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:644
    throw err;
    ^

Error: Command failed: cp node_modules/katex/dist/katex.min.css app/katex/
'cp' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Object.<anonymous> (C:\Users\Win 10\Desktop\github\Rocket.Chat\.scripts\npm-postinstall.js:6:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@1.0.0-develop postinstall: `node .scripts/npm-postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@1.0.0-develop postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

``

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: WIN10 64
- Deployment Method: -
- Number of Running Instances: 1
- DB Replicaset Oplog: Mongodb
- NodeJS Version: 10.10.0
- MongoDB Version:-

**Comment by MIKI785** [comment]
Rocket.Chat server doesn't support Windows as far as i know.

**Comment by reetp** [comment]
https://rocket.chat/docs/installation/community-supported-installation/

**Comment by fliptrail** [comment]
This is not a codebase issue. This can be closed.

**Comment by reetp** [comment]
FWIW for others also check the tag notes for the recommended software versions of node, npm, mongo etc 

eg
https://github.com/RocketChat/Rocket.Chat/releases/tag/1.0.0-beta.2

Engine versions
Node: 8.11.4
NPM: 6.4.1
MongoDB: 3.2, 3.4, 3.6, 4.0

**Comment by reetp** [comment]
@rocket-cat label add wontfix

Adding wontfix as I don't believe native Windows support is going to happen any time soon.

**Comment by reetp** [comment]
@rocket-cat close
And closing
