### ISSUE TITLE
[IMPROVE] Remove unnecessary "File Upload".

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#13738]
Remove unnecessary "File Upload" text, leave just the file name.

<img width="371" alt="Screenshot 2019-03-15 at 14 26 23" src="https://user-images.githubusercontent.com/1000217/54450148-7f38b000-472e-11e9-8370-958c72e1993a.png">

**Comment by knrt10** [comment]
On it, will fix this.

**Comment by engelgabriel** [comment]
Awesome @knrt10

**Comment by knrt10** [comment]
@engelgabriel PR is made, just one thing is that #13696 is related to it too. That is a bug to be fixed

**Comment by rohithGoudM** [comment]
Can I take this up?`
