### ISSUE TITLE
How to see all user's conversation on rocketchat from admin panel or server?

### ISSUE THREAD

**Issue by williamturner845** [RocketChat/Rocket.Chat#13749]
Hi, is it possible to see conversation between two users? from my rocketchat admin panel or server?

**Comment by reetp** [comment]
This is most likely a duplicate of something like this:
https://github.com/RocketChat/Rocket.Chat/issues/12305

There may be other similar bugs if you search.

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
@rocket-cat close
Closing as duplicate.
