### ISSUE TITLE
cannot start service, only as main.js

### ISSUE THREAD

**Issue by Pionell** [RocketChat/Rocket.Chat#13742]
hello, trying to start as a service `sudo systemctl start rocketchat`
```
Rocket.Chat Version: 0.74.3
NodeJS Version: 8.11.3 - x64

ubuntu-18.04-x86_64
````
But it does not start. Trying `sudo systemctl start rocketchat` gives me this result:

```
root@bbe40:/opt/Rocket.Chat# sudo systemctl status start rocketchat
Unit start.service could not be found.
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-03-15 19:25:16 EET; 27min ago
 Main PID: 4918 (code=exited, status=1/FAILURE)
```

However starting the server with `node main.js` in the /opt/Rocket.chat directory works and the service works, but to make it work I needed to export the root urls and mongodb parameters.
trying to edit `/lib/systemd/system/rocketchat.service` results in an error after re-logging in to the server.

Any ideas?

**Comment by sampaiodiego** [comment]
I guess you have followed instruction on https://rocket.chat/docs/installation/manual-installation/ubuntu/ is that correct?

can you please provide the content of your `/lib/systemd/system/rocketchat.service` file? please remove any sensitive info.

did you check `/var/log/syslog` for any additional info after using `systemctl`?

**Comment by Pionell** [comment]
hello, i've managed to get it running after a few hours of fiddling with configs and a help of a different tutorial. We stopped the service shortly thereafter so no logs anymore.. You can close the issue.

**Comment by sampaiodiego** [comment]
good you have figured it out.

if you found some useful information you'd like to share with others, please consider opening a PR to our documentation page: https://github.com/RocketChat/docs/blob/master/installation/manual-installation/ubuntu/README.md thanks
