### ISSUE TITLE
password for private group

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#13750]
### Description:

Not correct view/use options for rooms and second way to access the room. (first is invite)

### Steps to reproduce:

1. make private room
2. set password then edit room
3. send url in some way to not invited user
4. user see only that private room was not found
![изображение](https://user-images.githubusercontent.com/43804710/54479964-63bbcb00-483c-11e9-8787-7a839004974b.png)

but of couse private room exists
![изображение](https://user-images.githubusercontent.com/43804710/54479990-9b2a7780-483c-11e9-97ef-51e4c94b9a28.png)

### Expected behavior:

even user not invited then they provide password from field user would access to private room or password option must be absent/hide than channel make as private.  

### Actual behavior:

Then first user have permission to edit room and he create room as "private group", option password was meaningless. the first of whole - no url have provided to access(only direct invite), the second even some users somehow gets url(for example from user-owner), they cant access to private-room. but if owner set private room as channel(public) then password option is Great! some users offered to enter password to proceed to public room

### Server Setup Information:

- Version of Rocket.Chat Server: 0743
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

if ths is not bug plase be patient and point me to correct..

**Comment by geekgonecrazy** [comment]
Definitely a bug.  Even if we don't allow joining from a link for private groups... we shouldn't show the password box.

Not sure if we want to allow going to a link and entering or requesting to join... or just remove the setting of password on private group
