### ISSUE TITLE
Android keyboard automatically pops up upon entering a channel.

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Rocket.Chat#13758]
This issue seem to have been closed previously without any solution.

# Steps to reproduce
1. Visit Rocket Chat on Android browser.
2. Click to enter any Chanel.
OR
Start up RC and visit locally through LAN on Android, and do above.

**Comment by geekgonecrazy** [comment]
Which browser?  Is this Chrome on Android or what?

**Comment by Rodriq** [comment]
Yes Android 8.1.0 Oreo. Chrome browser.

**Comment by MartinSchoeler** [comment]
I cannot reproduce this using 2.1.0, this was probably fixed by the messagebox refactor. I will close this for now, if you see this issue again, please reopen this. Thanks!
