### ISSUE TITLE
Cannot see details about non-first edited message

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#1375]
With new code in #1357, if I hover over the small icon marking content as edited, it disappears so I cannot get a tooltip with more information. So this is the problem for sequential messages. How can I see when a non-first message was edited?

Also, only the information about the last edit is available? What is multiple admins edit the message? I do not really care about that scenario, but if #824 was about preventing abuse of power then this is important.

cc @blaskovicz, @marceloschmidt

**Comment by blaskovicz** [comment]
If you hover over the time of non first messages, it will show you editor info.

There was a discussion about the edit history feature viewing as a separate enhancement on the original feature request linked from my pull request. Currently there is a preference that must be enabled to save edit history, and if we make this mandatory, we just need to build a history viewer and differ dialog.

**Comment by mitar** [comment]
> If you hover over the time of non first messages, it will show you editor info. 

No, for me the small icon and edit icon disappears and time and widget icon appears with which I can edit again. The extra information is only in a tooltip. Is that OK?

**Comment by blaskovicz** [comment]
That is as it was designed.

**Comment by engelgabriel** [comment]
Is this what you see @mitar ? 
![image](https://cloud.githubusercontent.com/assets/1000217/11092634/f661037e-886b-11e5-862e-22ef0a205227.png)

**Comment by mitar** [comment]
Yes. But I am talking about second and other sequential messages. So because when you hover it changes, it is hard to know that there will still be a tooltip with extra information available.

But anyway, I think it is good enough.
