### ISSUE TITLE
REST nor Real-time API returning visitor "department"

### ISSUE THREAD

**Issue by juliomac** [RocketChat/Rocket.Chat#13766]
### Description:

After installing liveChat code on website, I am defining an specific department visitors will go to with: 

        RocketChat(function() {
         this.setDepartment('FILL HERE DEPARTMENT NAME - case sensitive');
       });

I want to listen and treat visitors differently depending on which department they were assigned to. However, there is no API call that returns information on which department visitor was assigned at.

### Steps to reproduce:

I have tried:

    curl http://localhost:4000/api/v1/livechat/room?token=< tokenFromVisitor>
          >>> No department information

    curl http://localhost:4000/api/v1/livechat/visitor/<tokenFromVisitor>
          >>> No Room nor department information

### Expected behavior:

Have an API call returning:

     {
        "visitor": {
          "_id": "dEhskC9xL5HtZDpiR",
          "username": "guest-4",
          "name": "Guest-Chrome",
          "token": "BBRFBCPffLk7siZxs",
           status: 'online' 
        },
        "rid": "ROOM_ID",
        "department": "DEPARTMENT_ID",
        "success": true 

### Server Setup Information:
- Version of Rocket.Chat Server: latest
- Deployment Method: docker
- Number of Running Instances: 
- NodeJS Version: 8
- MongoDB Version: 3.6

### Additional context
Could that be solved by a DDP subscribe? How and which collection could be used?

**Comment by renatobecker** [comment]
@juliomac,

The department field is returned on this endpoint:
https://rocket.chat/docs/developer-guides/rest-api/livechat/room/index.html

As you can see below:

```
{
"room": {
"_id": " gjFbmvbXQ7o6BSkXu",
"msgs": 0,
"usersCount": 1,
"lm": "2019-03-18T19:56:24.768Z",
"fname": "Renato",
"t": "l",
"ts": "2019-03-18T19:56:24.768Z",
"v": {
"_id": "wvPWrqpkFmjkXLgYC",
"username": "guest-2",
"token": "didbxr0mqsdf32ggc4r4wd",
"status": "online"
},
"servedBy": {
"_id": "r8jKPuAJsnu3N4kyS",
"username": "renato.becker",
"ts": "2019-03-18T19:56:24.768Z"
},
"cl": false,
"open": true,
"waitingResponse": true,
"departmentId": "ToJ9RJgCuAwth6ntB",
"_updatedAt": "2019-03-18T19:56:24.768Z"
},
"newRoom": false,
"success": true
}
```

**Comment by juliomac** [comment]
THANKS @renatobecker !

Initially I was not able to reproduce it. I was getting this:

      `{
       "room": {
       "_id": "bvnBhk5cFCSGvS7j2",
       "msgs": 0,
       "usersCount": 1,
    "lm": "2019-03-18T20:44:50.611Z",
    "fname": "dsvdwv",
    "t": "l",
    "ts": "2019-03-18T20:44:50.611Z",
    "v": {
      "_id": "rbj3ZDbA7DrQR2iW8",
      "username": "guest-3",
      "token": "GaDkpt4JENGXoMnS9",
      "status": "online"
    },
    "servedBy": {
      "_id": "rppS9fqtXeakG2bd3",
      "username": "LibertasBot",
      "ts": "2019-03-18T20:44:50.611Z"
    },
    "cl": false,
    "open": true,
    "waitingResponse": true,
    "_updatedAt": "2019-03-18T20:44:50.612Z"
  },
  "newRoom": true,
  "success": true
  }`


But I realized my local Rocket.Chat version was about 20 days older and did a ```git pull origin```. Now I am having the same response:

```  "room": {
    "_id": "Jwq9CFwhu393yhefw",
    "msgs": 0,
    "usersCount": 1,
    "lm": "2019-03-19T12:55:21.182Z",
    "fname": "guest-28",
    "t": "l",
    "ts": "2019-03-19T12:55:21.182Z",
    "v": {
      "_id": "9ehM7b53kQDWTc98p",
      "username": "guest-28",
      "token": "fE8DMYDb5ggrxR7aE",
      "status": "online"
    },
    "servedBy": {
      "_id": "zqgX7TMsMfxKRrAr3",
      "username": "libertasbot",
      "ts": "2019-03-19T12:55:21.185Z"
    },
    "cl": false,
    "open": true,
    "waitingResponse": true,
    "departmentId": "BR0310008-Bot",
    "_updatedAt": "2019-03-19T12:55:21.187Z"
  },
  "newRoom": true,
  "success": true
} ```

Is that a result of recent updates or could be another reason/mistake in my part?

**Comment by renatobecker** [comment]
@juliomac,

If the `departmentId` is stored in the `room` document, this field will be returned in the payload.
Thanks.
