### ISSUE TITLE
Forwarded Livechat visitor name on the sidebar not getting updated after a change

### ISSUE THREAD

**Issue by zolbayars** [RocketChat/Rocket.Chat#13760]
### Description:

When a livechat agent edits the visitor name and saves it. It only gets updated on the top of the page. Visitor name on the sidebar remains same even after multiple tries. 

### Steps to reproduce:

1. Open a new livechat conversation on the sidebar.
2. Forward the conversation to another livechat agent.
3. Open forwarded conversation as that livechat agent. 
4. Click on Visitor Info icon -> Edit 
5. Change the Name field and click Save

### Expected behavior:

Name of the visitor should be changed on the sidebar and the top of the conversation. 

### Actual behavior:

The name is changed in everywhere except on the sidebar. But when you forward it to yet another agent, it's getting changed. Though that agent too, can't change it herself. 

![image](https://user-images.githubusercontent.com/3589907/54508789-09c51d80-4982-11e9-9962-7b33cf753ed3.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: RHEL 7.5 (same on Debian 9)
- Deployment Method: tar from https://releases.rocket.chat/latest/download
- Number of Running Instances: 1
- DB Replicaset Oplog: NA
- NodeJS Version: v8.11.3
- MongoDB Version: v3.6.10

### Additional context

Tried on Chrome v72 (on both regular and incognito mode) and Firefox v65 

### Relevant logs:

No log on the browser console
Following logs caught on the server:

```
Mar 18 05:28:28 ip-172-31-31-212 rocketchat: server.js:199 Meteor ➔ method livechat:saveInfo -> userId: baBrREK5eZfrj47wb , arguments:  [ { _id: 'iyk5yvhxy8Cy4W56H',
Mar 18 05:28:28 ip-172-31-31-212 rocketchat: name: 'The Guest',
Mar 18 05:28:28 ip-172-31-31-212 rocketchat: email: 'Luugii@gmail.com',
Mar 18 05:28:28 ip-172-31-31-212 rocketchat: phone: '' },
Mar 18 05:28:28 ip-172-31-31-212 rocketchat: { _id: 'sSRryNmTPgfLM59SF', topic: '', tags: '' } ]
```

**Comment by knrt10** [comment]
@zolbayars I see you have committed on your branch, feel free to open a PR for the same. 👍
