### ISSUE TITLE
[BUG] The text on home page is not getting translated to different languages

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#13777]
### Description:

The text of home page is always english and is not getting translated when user choses differenr languages.

### Steps to reproduce:

The home page content should be rendered with variables storing the text in different languages same as other text are translated of sidebar (for example)

### Expected behavior:

When user choses a specific language then the home page language should also change

### Actual behavior:

![Screenshot from 2019-03-19 03-18-24](https://user-images.githubusercontent.com/43786728/54566012-b7bddf80-49f5-11e9-8f64-49fd55f16547.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by Juw00** [comment]
I'm working on the french version. Do you know where I can find the variable to edit ?

**Comment by ashwaniYDV** [comment]
@Juw00 You can find it in packages/rocketchat-i18n/
