### ISSUE TITLE
[BUG] OTR not working on denied by other user

### ISSUE THREAD

**Issue by knrt10** [RocketChat/Rocket.Chat#13786]
### Description:

A user can start an OTR with any user when they are online, but if the other user declines the OTR if still shows establishing the connection. Which should not happen.

### Steps to reproduce:

1. Go to **any user**  user
2. Click on three dots on the top right and then press OTR
3. Go to any user user
4. Deny OTR
5. See modal message on your user info

### Expected behavior:

Modal should pop-up and the user should be able to start the OTR again.

### Actual behavior:

After being denied by the other usee, it goes to forever establishing the connection

![2019-03-19 18 11 10](https://user-images.githubusercontent.com/24803604/54606863-f2199200-4a72-11e9-8edb-71816965bd5b.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: **1.0.0-develop**
- Operating System: MacOS
- Development method: meteor
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11.4

### Additional context

I am fixing this issue.

**Comment by reetp** [comment]
Has this been merged/fixed??

**Comment by dougfabris** [comment]
Closing because it's already fixed!
