### ISSUE TITLE
Find improper use of the color #13679A

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#13787]
This `#13679A` used to be our default color, we changed for `#1d74f5` but it still shows up in a few places, like when I am mentioned. Let's track it down!

**Comment by Rodriq** [comment]
can I give this a look?  @tassoevan @ggazzo

**Comment by ggazzo** [comment]
please @Rodriq go ahead, feel free to contribute :)

**Comment by ggazzo** [comment]
closed by #13796
