### ISSUE TITLE
[BUG] Bitcoin link in Readme.md is showing 404 error on clicking

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#13788]
### Description:

Bitcoin link in Readme.md is wrong and showing 404 error on clicking.

![sd](https://user-images.githubusercontent.com/43786728/54615767-a8d23e00-4a84-11e9-8366-f03cebaa3a21.png)

**Comment by ashwaniYDV** [comment]
@engelgabriel please provide me the link that needs to be updated.

**Comment by geekgonecrazy** [comment]
Please feel free to open a PR removing it since the link is broken
