### ISSUE TITLE
 Add 'Browse' button to select destination folder for saving media

### ISSUE THREAD

**Issue by Pratyush1197** [RocketChat/Rocket.Chat#13795]
In the file upload section when we select Storage type as 'File system' we need to set the System path manually. This can be done with a browse button next to the input field to easily select the location
![Screenshot_2019-03-19 Rocket Chat](https://user-images.githubusercontent.com/32239181/54636676-f82c6480-4aac-11e9-9cb4-582400c5c265.png)

**Comment by Pratyush1197** [comment]
I can work on this issue

**Comment by ggazzo** [comment]
I dont think its gonna work because you can be accessing for a different machine, so I think a plain text its the best option for now... thanks
