### ISSUE TITLE
Voice message not working - never ending upload (1.0.0-beta.2)

### ISSUE THREAD

**Issue by uriesk** [RocketChat/Rocket.Chat#13793]
### Description:

Voice message records, but when clicking on the green finished/send button, the loading symbol would never disappear and there is no progress of upload being shown and it will never appear on the server.

### Steps to reproduce:

1. Go to the official rocket.chat server on https://open.rocket.chat or run your own server on beta
2. try to send voice message

### Expected behavior:

Uploading recorded voice message

### Actual behavior:

Never ending loading icon

### Server Setup Information:

idk. what open.rocket.chat is running.
We are running 1.0.0-beta.2 on centos on a manual install with node 8.15.1 and npm 6.4.1

**Comment by dreamup** [comment]
+1

**Comment by ggazzo** [comment]
should be working right now (2.1.0), please let me know if not
