### ISSUE TITLE
Message box can only insert one character (1.0.0-beta.2)

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#13790]
Recently we updated to the newest beta version, thinking beta meant it would be more just rough around the edges, but I was informed after that beta is **expected** to break and not recommended for use. Now we are stuck on 1.0.0-beta.2 and it is unusable due to the fact that the message box is completely broken, you can only insert one character into it and it doesn't let you insert anything else. A more minor bug I also encountered is the custom CSS for the header/titlebar at the top is broken (there's a large black border around the custom image I placed there) and getting rid of the header CSS entirely didn't seem to have any effects or changes. The client I am using is 2.15.1-1 on Linux. We are using docker for deployment. The server is running on Ubuntu.

**Comment by ggazzo** [comment]
its no longer a problem thanks for your time
