### ISSUE TITLE
 [feature request] Regular users to be able to create Text Snippets

### ISSUE THREAD

**Issue by juliomac** [RocketChat/Rocket.Chat#13800]
I know this could be solved by Bots, but... 

It would be nice if regular users could create text snippets that they regularly use for response to others and, specially, to Livechat guests.

A few chat services enable users to create "/" +shortCutWord, for instance, "/standardResponse" that will just copy into current Chat window a pre-existing text user previously saved. This would be great for people involved in answering LiveChat customers that regularly calls.

**Comment by renatobecker** [comment]
This feature is in our roadmap already.
Thanks.
