### ISSUE TITLE
Delete doesn't clear message

### ISSUE THREAD

**Issue by Tirvanel** [RocketChat/Rocket.Chat#13810]
### Description:

On Rocket Chat version 0.74.1, when I delete a message on my work's rocketchat instance, the message doesn't disappear until I refresh the page. Even if I change channels and come back, the message is still there. 

### Steps to reproduce:

Person 1 send message
Person 1 delete message
Person 2 still sees message

### Expected behavior:

When another user deletes a message, I would expect that message to disappear from my screen immediately. 

### Actual behavior:
When another user deletes a message, the message appears visible to me until I refresh the page, even if I go to another channel and come back. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.1
- Operating System: unknown
- Deployment Method: Unknown
- Number of Running Instances: unknown
- DB Replicaset Oplog: unknown
- NodeJS Version: unknown
- MongoDB Version: unknown

### Relevant logs:
No logs available

**Comment by knrt10** [comment]
@Tirvanel would you please fill the issue template, otherwise, it is difficult for maintainers to debug the problem you are facing. And also it might not be noticed then. Thanks.

**Comment by Tirvanel** [comment]
Where would I find the issue template?

**Comment by knrt10** [comment]
```

<!-- 

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

If you are experiencing a bug please search our issues to be sure it is not already present: https://github.com/RocketChat/Rocket.Chat/issues

-->

### Description:

<!-- A clear and concise description of what the bug is. -->

### Steps to reproduce:

1. <!-- Go to '...' -->
2. <!-- Click on '....' -->
3. <!-- and so on... -->

### Expected behavior:

<!-- What you expect to happen -->

### Actual behavior:

<!-- What actually happens with SCREENSHOT, if applicable -->

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: <!-- snap/docker/tar/etc -->
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

<!-- Add any other context about the problem here. -->

### Relevant logs:

<!-- Logs from both SERVER and BROWSER -->
<!-- For more information about collecting logs please see: https://rocket.chat/docs/contributing/reporting-issues#gathering-logs -->

```

**Comment by Tirvanel** [comment]
@knrt10 main post updated.

**Comment by knrt10** [comment]
@Tirvanel this is fixed in latest RC version. Try updating it and check whether you still have the same problem.

**Comment by Tirvanel** [comment]
Ah, awesome. I'm not the admin, so I don't have control over that. Glad to hear it's fixed.
