### ISSUE TITLE
Livechat Facebook integration not working

### ISSUE THREAD

**Issue by kknyxkk** [RocketChat/Rocket.Chat#13816]
### Description:

Sending message to page configured on Livechat facebook integration and the message never comes to Livechat.

### Steps to reproduce:

1. Configure Facebook keys on Administration > Livechat > Facebook.
2. Go to Livechat > Facebook Integration menu and enable the integration.
3. Pick the page you have and enable it.
4. Send a message to this page.

### Expected behavior:

The message sent from facebook appear on livechat by some way.

### Actual behavior:

The message sent never appear on livechat.

### Server Setup Information:

- 0.74.3
- Operating System: Debian
- Deployment Method: Docker Installation
- Number of Running Instances: 1
- MongoDB Version: Docker mongo:3.6.5

### Additional context

I realized that after some time the facebook integration disables by he self.

### Relevant logs:

Server Log:

`[34mI20190320-14:22:26.646(0) [32m➔ [32mSystem ➔ startup 
[34mI20190320-14:22:26.646(0) [32m➔ [32m+---------------------------------------------------+ 
[34mI20190320-14:22:26.646(0) [32m➔ [32m|                   SERVER RUNNING                  | 
[34mI20190320-14:22:26.647(0) [32m➔ [32m+---------------------------------------------------+ 
[34mI20190320-14:22:26.647(0) [32m➔ [32m|                                                   | 
[34mI20190320-14:22:26.647(0) [32m➔ [32m|  Rocket.Chat Version: 0.74.3                      | 
[34mI20190320-14:22:26.647(0) [32m➔ [32m|       NodeJS Version: 8.11.4 - x64                | 
[34mI20190320-14:22:26.648(0) [32m➔ [32m|             Platform: linux                       | 
[34mI20190320-14:22:26.648(0) [32m➔ [32m|         Process Port: 3000                        | 
[34mI20190320-14:22:26.648(0) [32m➔ [32m|             Site URL: http://10.130.214.117:3300  | 
[34mI20190320-14:22:26.648(0) [32m➔ [32m|     ReplicaSet OpLog: Disabled                    | 
[34mI20190320-14:22:26.648(0) [32m➔ [32m|          Commit Hash: 202a465f1c                  | 
[34mI20190320-14:22:26.649(0) [32m➔ [32m|        Commit Branch: HEAD                        | 
[34mI20190320-14:22:26.649(0) [32m➔ [32m|                                                   | 
[34mI20190320-14:22:26.649(0) [32m➔ [32m+---------------------------------------------------+ 
[34mI20190320-14:22:42.514(0) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
[34mI20190320-14:22:42.517(0) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 
[34mI20190320-14:50:49.943(0) ====== BEGIN MAIL #0 ====== 
[34mI20190320-14:50:49.944(0) (Mail not sent; to enable sending, set the MAIL_URL environment variable.) 
[34mI20190320-14:50:49.958(0) Content-Type: text/html; charset=utf-8  To: bmartins@indracompany.com  Subject: [XP Investimentos - Atendimento] You have been direct messaged by   PAULO CESAR BARRETO DA SILVA  Message-ID: <96e925e8-1ae6-29bb-762a-dae96cdfa328@27169eb154b0>  Content-Transfer-Encoding: quoted-printable  Date: Wed, 20 Mar 2019 14:50:49 +0000  MIME-Version: 1.0    
[34mI20190320-14:50:49.963(0) <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=  w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns=3D"http://www.w3.=  org/1999/xhtml" style=3D"font-family: -apple-system,BlinkMacSystemFont,=  'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color =  Emoji','Segoe UI Emoji','Segoe UI Symbol','Meiryo UI',Arial,=  sans-serif;"><head><meta name=3D"viewport" content=3D"width=3Ddevice-width"><meta =  http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8"><title>R=  ocket.Chat Cloud</title></head><body bgcolor=3D"#F7F8FA" =  style=3D"font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,=  Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color Emoji','Segoe UI =  Emoji','Segoe UI Symbol','Meiryo UI',Arial,sans-serif; width: 100%; height:=   100%;"><table class=3D"body" bgcolor=3D"#F7F8FA" width=3D"100%" =  style=3D"font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,=  Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color Emoji','Segoe UI =  Emoji','Segoe UI Symbol','Meiryo UI',Arial,sans-serif; width: 100%; height:=   100%;"><tr><td><table class=3D"wrap" bgcolor=3D"#F7F8FA" =  style=3D"width: 100%; clear: both;"><tr><td class=3D"header container" =  style=3D"display: block; max-width: 640px; margin: 0 auto; clear: both; =  border-radius: 2px;"><div class=3D"header-content" style=3D"list-style-posi=  tion: inside; padding: 16px 0; padding-top: 36px; padding-bottom: 36px; =  padding-left: 36px; padding-right: 36px; max-width: 640px; margin: 0 auto; =  display: block;"><table bgcolor=3D"#F7F8FA" width=3D"100%"><tr><td><img =  src=3D"http://10.130.214.117:3300/assets/logo.png" alt=3D"Rocket.chat" =  width=3D"150px"></td></tr></table></div></td></tr></table></td></tr><tr><td><table class=3D"wrap" style=3D"width: =  100%; clear: both;"><tr><td class=3D"container" bgcolor=3D"#FFFFFF" =  style=3D"display: block; max-width: 640px; margin: 0 auto; clear: both; =  border-radius: 2px;"><div class=3D"content" style=3D"list-style-position: =  inside; padding: 36px;"><table><tr><td> <strong>PAULO CESAR BARRETO DA =  SILVA</strong> sent you a message:<br/><br/>[ ](http://10.130.214.=  117:3300/direct/bmartins?msg=3DX3k3PuZDwo5ue82t8) @dluisb <p =  style=3D"margin: 1rem 0;"><a class=3D"btn" href=3D"http://10.130.214.=  117:3300/direct/pcbarreto" style=3D"line-height: 1.8; padding-left: 2px; =  padding-right: 2px; text-decoration: none; color: #FFF; background-color: =  #1D74F5; padding: 12px 18px; font-weight: 500; font-size: 14px; margin-top:=   8px; text-align: center; cursor: pointer; display: inline-block; =  border-radius: 2px;">GO TO MESSAGE</a></p> </td></tr></table></div></td></t=  r></table></td></tr><tr style=3D"margin: 0; padding: 0;"><td =  style=3D"margin: 0; padding: 0;"><table class=3D"wrap" =  style=3D"width: 100%; clear: both;"><tr><td class=3D"container" =  style=3D"display: block; max-width: 640px; margin: 0 auto; clear: both; =  border-radius: 2px;"><div class=3D"content" =  style=3D"list-style-position: inside; padding: 36px;"><table =  width=3D"100%"><tr><td align=3D"center" class=3D"social" =  style=3D"font-size: 12px;"><a href=3D"https://rocket.chat/blog" =  style=3D"color: #1D74F5; font-weight: bold; text-decoration: none; =  line-height: 1.8; padding-left: 2px; padding-right: 2px;">Blog</a> | <a =  href=3D"https://github.com/RocketChat" style=3D"color: #1D74F5; =  font-weight: bold; text-decoration: none; line-height: 1.8; padding-left: =  2px; padding-right: 2px;">Github</a> | <a href=3D"https://www.facebook.=  com/RocketChatApp" style=3D"color: #1D74F5; font-weight: bold; =  text-decoration: none; line-height: 1.8; padding-left: 2px; padding-right: =  2px;">Facebook</a> | <a href=3D"https://www.instagram.com/rocket.chat" =  style=3D"color: #1D74F5; font-weight: bold; text-decoration: none; =  line-height: 1.8; padding-left: 2px; padding-right: =  2px;">Instagram</a></td></tr><tr><td align=3D"center"><h6 style=3D"margin: =  0 0 16px 0; font-weight: 500; font-size: 10px; color: #6c727A; line-height:=   1.7;">=C2=A9 Rocket.Chat Technologies Corp.</h6><h6 style=3D"margin: 0 0 =  16px 0; font-weight: 500; font-size: 10px; color: #6c727A; line-height: 1.=  7;">Made with =E2=9D=A4=EF=B8=8F in =F0=9F=87=A7=F0=9F=87=B7 =  =F0=9F=87=A8=F0=9F=87=A6 =F0=9F=87=A9=F0=9F=87=AA =F0=9F=87=AE=F0=9F=87=B3 =  =F0=9F=87=AC=F0=9F=87=A7 =F0=9F=87=BA=F0=9F=87=B8 </h6></td></tr></table></=  div></td></tr></table></td></tr></table></body></html>
[34mI20190320-14:50:49.965(0)   
[34mI20190320-14:50:49.965(0) ====== END MAIL #0 ====== `

Browser: 

`Navigated to http://10.130.214.117:3300/livechat-manager/facebook
5XHR finished loading: GET "<URL>".
VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5 XHR finished loading: GET "http://10.130.214.117:3300/api/v1/commands.list".
send @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
ajax @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
o @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
_jqueryCall @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
get @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
get @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
r.autorun @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
_compute @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
t @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
s.autorun @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
commands.js @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
g @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
n @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
e @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:235
VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5 XHR finished loading: GET "http://10.130.214.117:3300/tap-i18n/pt.json".
send @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
ajax @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
y.(anonymous function) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
getJSON @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
a @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:129
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:129
l @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
add @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
_loadLanguage @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:129
setLanguage @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:129
u @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:551
a.autorun @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:551
_compute @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
t @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
s.autorun @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
o.startup @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:551
a @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:1
u @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:1
VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59 XHR finished loading: GET "http://10.130.214.117:3300/sockjs/info?cb=ztp3djj1z1".
_start @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
setTimeout (async)
n.delay @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
n.XHRLocalObject @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
doXhr @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
setTimeout (async)
n.delay @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
J @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
G @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
k @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
_launchConnection @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
l @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
w @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:61
d.connect @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:61
client_convenience.js @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:61
g @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
n @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
a @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5
client.js @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:61
g @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
n @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
e @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:3
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:61
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:61
VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:161 XHR finished loading: GET "http://10.130.214.117:3300/_timesync".
c.call @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:161
r.get @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:161
g @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:191
s.resync @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:191
(anonymous) @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:191
_compute @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
_recompute @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
s._runFlush @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
a @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:1
postMessage (async)
u @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:1
v @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
invalidate @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
changed @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:45
statusChanged @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
_connected @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
socket.onopen.t @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
r.dispatchEvent @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
k._dispatchOpen @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
k._didMessage @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
o.ws.onmessage @ VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:59
f878e4a76abf5f281f768f4e858cf8548503fa3f.js:5 XHR finished loading: GET "http://10.130.214.117:3300/api/apps/languages".
send @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:5
ajax @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:5
o @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:235
_jqueryCall @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:235
get @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:235
_loadLanguages @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:433
a.defer @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:433
r.withValue @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
(anonymous) @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
(anonymous) @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
a @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
postMessage (async)
u @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
n.defer @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
load @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:433
a.call @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:433
(anonymous) @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:1
_maybeInvokeCallback @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61
receiveResult @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61
_livedata_result @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61
onMessage @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:61
currentStatus.connected.forEachCallback.e @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
forEachCallback @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
socket.onmessage.t @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
r.dispatchEvent @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
k._dispatchMessage @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
k._didMessage @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
o.ws.onmessage @ f878e4a76abf5f281f768f4e858cf8548503fa3f.js?meteor_js_resource=true:59
VM120 f878e4a76abf5f281f768f4e858cf8548503fa3f.js:433 Loading: true`

**Comment by renatobecker** [comment]
Issue moved to [RocketChat/OmniChannel.Gateway #6](https://github.com/RocketChat/OmniChannel.Gateway/issues/6) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Emersonsanch** [comment]
I'm having this exact same problem.
