### ISSUE TITLE
Email of all users exposed in Directory

### ISSUE THREAD

**Issue by uriesk** [RocketChat/Rocket.Chat#13812]
Edit: I meant directory not dictionary! That little worldbutton that gives you the whole public-channel- and userlist.

When clicking at the user in the Member List sidebar of a channel, you do not see the mail address except if you are a Admin.
But in the Dictionary, everybody can see the email of every user.

Exposing the mail address of all users is a privacy issue for us.

**Comment by reetp** [comment]
This is a biggy and present on open.rocket.chat as well as my own 1.0.0.-beta.1

Any user can see any other users email. That should not be allowed by default - GDPR & all that privacy jazz.

**Comment by graywolf336** [comment]
#livingriskyonbeta 😂
