### ISSUE TITLE
Other users being tagged in DM

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Rocket.Chat#13811]
When in DM with a particular user, including the tagging `@` symbol gives room for other users to be mentioned.
### Actual Behaviour
![other-users-being-tagged](https://user-images.githubusercontent.com/39289592/54698048-ebe8eb80-4b2e-11e9-90bb-fdd9f9c6c0c9.png)

You see that, I'm in DM with `new.user2` but I can still mention `new.user1`.

**Comment by Kailash0311** [comment]
What happens actually when you tag other people? Do they get a notification?

**Comment by wreiske** [comment]
I use this all the time. I would say this is a feature, not a bug. This does not notify the user you are tagging.

**Comment by Rodriq** [comment]
@Kailash0311 @wreiske This is indeed a feature. How cool. I'll close the issue now.
