### ISSUE TITLE
Users chat messages shows reversed/backwards

### ISSUE THREAD

**Issue by jseong309** [RocketChat/Rocket.Chat#13830]
On Version 0.74.2 (Snap)
Ubuntu 16
Apache2 

It's not a frequent issue but out of our 300 users, 5 users reported that their chat messages are reversed. They would have to close the app and relaunch (PC)

" !?!?esrever ni gnipyt I ma yhW "

Just curious if anyone else has seen this issue or why this is happening.

**Comment by dj301** [comment]
Same issue here! Rocket Chat server 1.0.1 and Windows app 2.5.3

**Comment by hathawayweb** [comment]
^^ Bump! Has anyone resolved this? An update?

**Comment by ggazzo** [comment]
Sorry @hathawayweb, but we cant reproduce the bug with the provide info... could you say more about?
what language are you using in the server/client? are there any message text with RTL (Right To Left)? It would be nice if you sent a print showing the all current state... thanks for your time (:

**Comment by hathawayweb** [comment]
Hello @ggazzo!

Thank you for the response.

I can't show a screen shot of what's happening either, as it happens randomly for us as well. We are using English, we have no messages that should be RTL.

Print out of the from the Administrator > Info page?

**Comment by ggazzo** [comment]
... the rocket.chat version is enough thanks ...so are you using the rockect.chat desktop, did you see this problem on the web browser? I have never seen this before, BUT I will check the code...

**Comment by hathawayweb** [comment]
@ggazzo sorry wasn't sure what you wanted!

I only have seen it happen on the desktop client, I don't usually use the web browser for it.

**Comment by ggazzo** [comment]
The rocket.chat version and the desktop app version 😬

**Comment by hathawayweb** [comment]
It'll have to be about 1 day before I can follow up with more information.

Due to it being Sunday, I am not able to see the desktop version I have within the office! Have been out of the office for COVID-19 for over the week, I'll follow up as soon as possible! Thank you :)

**Comment by jseong309** [comment]
After a few updated versions I have not had anyone reporting this issue. Currently on server version 2.4.11 and Windows 2.17.7.

**Comment by hathawayweb** [comment]
The coworker who is constantly reporting it is on version 2.17.3 and so I'm having her update to 2.17.7.
