### ISSUE TITLE
Hipchat Import fails with invalid tar header

### ISSUE THREAD

**Issue by 88fingerslukee** [RocketChat/Rocket.Chat#13845]
### Description:

Hipchat tar.gz importer from Hipchat 2.4.3 fails with invalid tar header. This is on 0.74.3.

### Steps to reproduce:

Import hipchat file. Get error

### Expected behavior:

gimme the good stuff

### Actual behavior:

not the good stuff. Fail to extract

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Relevant logs:

> I20190321-22:23:22.265(-7) rocketchat:logger server.js:199 HipChat (tar.gz) Importer ➔ error extract error: Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?     at Object.exports.decode (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/headers.js:267:43)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:124:39)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.onheader (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:132:7)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at Extract.ondrain (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:88:5)     at Extract._write (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:250:8)     at Extract._continue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:213:28)     at oncontinue (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:68:10)     at onunlock (/snap/rocketchat-server/1367/programs/server/npm/node_modules/tar-stream/extract.js:74:24)     at Promise.asyncApply (packages/rocketchat:importer-hipchat-enterprise/server/importer.js:622:6)     at /snap/rocketchat-server/1367/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by Hudell** [comment]
Do you have a sample file we can trigger this error with?
