### ISSUE TITLE
File operations not possible when using port other than 80

### ISSUE THREAD

**Issue by Cruaier** [RocketChat/Rocket.Chat#13849]
### Description:

Our Rocket.Chat is behind a router only accessible using the port 9000. The router is doing the port redirecting to 443. When using port 80 the request won't be redirected to the Rocket.Chat server. When doing file operations (e.g. sending a file to someone else) the request url don't contain the port which is causing that no file can be send.

### Steps to reproduce:

1. Set up Rocket.Chat behind a router and configure port redirection
2. Try to send files to someone else
3. Upload stays at 0%

### Expected behavior:

The request URL should contain the port

### Actual behavior:

![Bildschirmfoto 2019-03-22 um 17 31 04](https://user-images.githubusercontent.com/5204940/54819470-8b90b000-4cce-11e9-877f-8e74de8eefa0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 18.04.2
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.10

**Comment by Cruaier** [comment]
Not sure why...but using the Android client seems to work.

**Comment by Cruaier** [comment]
2nd not sure: notifications (tested on Android) from a server with explicit port also resulting in an error! the notification text is displayed correctly but on "click" it doesn't display the message

**Comment by Cruaier** [comment]
@MarcosSpessatto are you able to give me an idea about how long it may take to fix this issue?

**Comment by MarcosSpessatto** [comment]
@Cruaier  I'm working on this now. :slightly_smiling_face:

**Comment by MarcosSpessatto** [comment]
@Cruaier is there any errors in the browser console and the server console?

**Comment by Cruaier** [comment]
@MarcosSpessatto I get an "net::ERR_CERT_AUTHORITY_INVALID" error...but that's due to the not trusted certificate from my router I guess - nothing else though.
Additional: this error also comes from the avatars and files which were already uploaded and are in the chat present meaning there are quite some URLs broken:
![image](https://user-images.githubusercontent.com/5204940/55414172-db0b9180-5594-11e9-97bd-3252607909cf.png)

**Comment by MarcosSpessatto** [comment]
@Cruaier can you please DM me at https://open.rocket.chat/direct/marcos.defendi?

**Comment by MarcosSpessatto** [comment]
@Cruaier what is the value of your server `ROOT_URL` setting?

**Comment by Cruaier** [comment]
I sent you a message! the root_url is set to the url without the port

**Comment by Cruaier** [comment]
Hi @braymundo I send you a message on open.rocket.chat regarding this. can you have a look and assist on this one? Thanks!

**Comment by geekgonecrazy** [comment]
Root_url must be set the the url exactly as accessed.  So if you access at my site:6789 then the root_url would need to contain that port

**Comment by Cruaier** [comment]
@geekgonecrazy and that's certainly an issue in my case...I am doing a workaround now which is not that user friendly using also for the internal server the port 9000.
Anyway, it seems that the Android app is doing it different (because there it works!).

**Comment by geekgonecrazy** [comment]
yeah the android app handles slightly different.  But in general ROOT_URL must be set to the url you will access with.

Sounds like this is resolved.  Closing

**Comment by Cruaier** [comment]
@geekgonecrazy I can confirm that it works when using the root_url with port - but the question in general stays if that's the right way to go. Also, I don't really get the reason for having such a "root url" - isn't it pretty error prone? Wouldn't it be more intuitive to use the URL of the client?

**Comment by geekgonecrazy** [comment]
We allow things like running in a subfolder etc.  So we cannot simply use relative paths to the root of the domain.   This so far has been the most sure fire way.  We are definitely open to PR's if you find a better way that can work across all deployment scenarios :)
