### ISSUE TITLE
No user feedback when clicking on Star Message

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#13857]
### Description:

There is no user feedback telling the user that his message has been starred or not when he clicks on star message option.

### Steps to reproduce:

1. Choose a random message
2. Click on three dots in the messge (Open the message actions menu)
3. Click on star message

### Expected behavior:

The user should get a reply that his message has been starred or a failure if not starred.

### Actual behavior:

No feedback is given to the user

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 develop
- Operating System: Ubuntu 18.0.10 
- Deployment Method: Local
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

I am working on this

**Comment by sbarre-esit** [comment]
Could there also be a star icon next to the message?
