### ISSUE TITLE
LDAP authentification - BIG problem with users in subdomains

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#13862]
### Description:

LDAP authentification(AD) is set up and working for users in rocketchat group from my.domain.com. When I add user from city.my.domain.com to user group rocketchat in my.domain.com, then Ldap sync ignore that user and its not imported into rocketchat.
This is a BIG problem for us, as we just starting testing phase and heading to 2000-3000 users and more than 80 percent of those users are in our subdomains. 

### Expected behavior:

What we need is LDAP sync ability to recognize and import users from subdomains.

### Server Setup Information:

- Version of Rocket.Chat Server: 74.0
- Operating System: ubuntu 18.4
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 8.14
- MongoDB Version: 4

**Comment by Abraka** [comment]
Well, great support here guys.
Solution for me is: 
host: zoo.domain.com (name of domain, not a domain controller)
port: 3268 (aka domain katalog)
So, you dont ask directly DC Ldap over 389 or 636. You ask domain catalog through name of the domain on 3268 port. Direct query on DC ldap will not give you subdomain users.
Update your wiki page.

**Comment by reetp** [comment]
Note that Github Issues are for things that are bugs and things that are broken, not support questions.

You can get Community support at https://forums.rocket.chat or https://open.rocket.chat

Or you can pay for professional support https://rocket.chat/pricing

>Update your wiki page.

Why don't you update the wiki page with a pull request yourself with this information (this is open source so its about giving, as well as taking)? It isn't hard.
