### ISSUE TITLE
Add simple example of regular expression on search message panel 

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Rocket.Chat#13878]
Users that don't know about **Regular expression** should see how a simple Example looks like.
  If approved, sending PR

**Comment by pshute** [comment]
It already shows "You can search using RegExp. e.g. /^text$/i". Did you mean to add another example?

**Comment by ggazzo** [comment]
![image](https://user-images.githubusercontent.com/5263975/67049110-d8752180-f10b-11e9-9147-c46f066bf02d.png)
