### ISSUE TITLE
When an already existing user is added in group is doesn't shows that user already exists.

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#13879]
### Description:

When a user which is part of a group is added in the same group then it shows that "Users have been added."
But it should show that the user already exists in the group.

### Steps to reproduce:

1. Go to add user option
2. Type the user name
3. It shows the same message if the user already exists in the group or not.

### Expected behavior:

If a user is not part of the group then it should show the message that the user has been added.
If a user is part of the group then it should show the message that the user already exists in the group.

### Actual behavior:

The same message is shown if a user is part of a group or not when he/she is added.

**Comment by sudipt1999** [comment]
I have already raised this issue in #13837 . So kindly close this one !

**Comment by sudipt1999** [comment]
I am already working on this feature !

**Comment by ashwaniYDV** [comment]
@sudipt1999 I'm so sorry. I didn't know about that.
