### ISSUE TITLE
[REQUEST-FEATURE] Support github markdowns in chat !

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13883]
Since Rocket.Chat is a wide community and is used by all type of people, even developer use it a quite lot so it will be really great feature if we support github markdowns.

**Comment by dersvenhesse** [comment]
Here are informations about the current Markdown support: https://rocket.chat/docs/contributing/documentation/markdown-styleguide/. For the the extended support exists #918.

**Comment by geekgonecrazy** [comment]
Dupe of: #918 

Closing
