### ISSUE TITLE
[UI] Text in message box is not centered

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#13886]
### Description:

The text in the message box is not exactly centred which is kind of off-putting to the user.

### Expected behavior:

The text should be centered or should follow the design principles so that it looks more comfortable to the user.

### Actual behavior:

It is slightly shifted upwards
![Screenshot from 2019-03-25 04-02-54](https://user-images.githubusercontent.com/40834245/54886899-306be280-4eb3-11e9-81d8-b7aa78dacc60.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 develop
- Operating System: Ubuntu 18.0.10
- Deployment Method: Local

### Additional context

I am working on it.

**Comment by MartinSchoeler** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/15367
