### ISSUE TITLE
[TypeError] : 'name' member of PermissionDescriptor 'microphone' is not a valid value for enumeration PermissionName.

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13881]
TypeError: 'name' member of PermissionDescriptor 'microphone' is not a valid value for enumeration PermissionName.

Reported from `messagebox.js`

**Comment by MarcosSpessatto** [comment]
@sudipt1999 What browser are you using?

**Comment by sudipt1999** [comment]
Google chrome sir

**Comment by geekgonecrazy** [comment]
I’ve seen this in Firefox as well.  Latest commit

**Comment by geekgonecrazy** [comment]
@tassoevan i'm not sure whats going on but we have another report from someone in #dev too

**Comment by JunyiYang0925** [comment]
@geekgonecrazy  hello, any updates on this? Have the same issue using firefox 68.0.1
