### ISSUE TITLE
[BUG] GitHub markdown not working properly

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#13885]
### Description:

GitHub markdown or markdown as given in Rocket.Chat/docs https://en.wikipedia.org/wiki/Markdown and https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet does not work properly.

### Steps to reproduce:

1. Type `*Hello*` in the message box

### Expected behavior:

It should appear as *hello*

### Actual behavior:

It appears as **hello**

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 develop
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

I am working on it. Most probably it is a problem with RegEx

**Comment by miko007** [comment]
i would like to add, that lists do not seem to work either: 

```
* foo
* bar *(and stuff)*
```

produces:

\* foo
bar **(and stuff)**\*

**Comment by reetp** [comment]
@miko007 Rocket does not currently use github markdown.
It uses Katex - link is at the bottom of the Rocket page in a browser.
https://katex.org/docs/supported.html

This bug and PR was to try and incorporate different mark up, but if you read the PR you will see that has not happened yet and hence why the PR is still open.

**Comment by xmedeko** [comment]
@fliptrail switch to Marked makrdowm and enable Github flavour

**Comment by mpfaff** [comment]
@reetp I'm almost certain that Rocket.Chat doesn't use KaTeX for markdown. KaTeX might be used for math, but markdown is entirely different.

**Comment by ggazzo** [comment]
Actually we use * and ** for bold, because most of the messengers does the same 

and we cannot adopt the some entire specification because sometimes inside the chat some contents dont fit well

**Comment by mpfaff** [comment]
> Actually we use * and ** for bold, because most of the messengers does the same

I view it as a bug because those messengers you mention all go against the most common markdown specifications.

> and we cannot adopt the some entire specification because sometimes inside the chat some contents dont fit well

I certainly wasn't expecting tables, headers, horizontal lines, etc. to be implemented. Just wish the basics were done correctly.
