### ISSUE TITLE
RealTime API stream-notify-user/message event 

### ISSUE THREAD

**Issue by skyJG** [RocketChat/Rocket.Chat#13904]
Hello,

we are connecting to the RealTime API to recive Updates for a certain User.
But we haven't had a successfull trigger of the Message Event.
All other Events are Working (room-changed/subscription-changed).

When will the stream-notify-user/message event be triggered?

Bye skyJG

**Comment by skyJG** [comment]
I made a test in the ARC client.
I can successfully Register the Event:.
![github rchat message notify user](https://user-images.githubusercontent.com/19854635/55071116-0881a800-5088-11e9-9dcb-e3fbf2430a42.png)

But I can't get it to fire.
Maybe it's the same as #12202

**Comment by AndreasHo** [comment]
Hello,

i have the same problem like you... I want to subscribe for each user his joined channels/private/ims.

I created a websocket for "stream-notify-user" with following events:
- message
- notification
- rooms-changed
- subscriptions-changed

When I send an message in one of my channels, i never get an event information.
Is there any example how it works or is this buggy?

Thank you.

Bye Andreas H.

**Comment by mikolaisebastian** [comment]
@skyJG @AndreasHo Yeah I still have the same problem here.

**Comment by skyJG** [comment]
We did a Debug of the Rocket.Chat iOS App, but unfortunatley - no luck there...
We can't get it to fire there either.
![rChat iOS Debug](https://user-images.githubusercontent.com/19854635/55969871-d0c95180-5c7e-11e9-959c-bfb321922010.jpg)
[rocket.chat.websocket-log.txt](https://github.com/RocketChat/Rocket.Chat/files/3069450/rocket.chat.websocket-log.txt)

**Comment by geekgonecrazy** [comment]
Is the notify just on mention?  I don’t think it’s for a general message stream

**Comment by sampaiodiego** [comment]
actually `stream-notify-user/message` are for ephemeral messages only.. 

for regular messages the correct stream is `stream-room-messages/[ROOM_ID]`

**Comment by geekgonecrazy** [comment]
ok that makes sense.  If this 🔝 doesn't answer your question feel free to respond here.

Closing

**Comment by 1valdis** [comment]
@geekgonecrazy does that mean I have to subscribe to every single room to get new messages? Is there no subscription which would notify me about any message which my user has received, no matter if it's a group or direct channel? What happens if someone creates a room with me and is able to send a message faster than I subscribe?...

**Comment by 1valdis** [comment]
Seems like I found it. The collection name is `stream-room-messages`, and event name is `__my_messages__`. As such, the whole subscription message looks like that
```json
{
  "msg": "sub",
  "id": "unique-id",
  "name": "stream-room-messages",
  "params": [
    "__my_messages__",
    false
  ]
}
```

**Comment by 1valdis** [comment]
But how do I now understand that the message was created, not edited, reacted to and so on but created? I get an update every time something about the message changes. But I only want to act if the message was created.

**Comment by sampaiodiego** [comment]
glad you found it @1valdis =) but unfortunately we'll always send an "update".. that's how we manage to hack meteor's subscriptions system to skip its merge box and thus be lighter on the server.

**Comment by 1valdis** [comment]
@sampaiodiego so, the only way to tell that a message is new and not updated is by comparing `ts` and `_updatedAt` with some offset (say 50-100 ms)? That is the only way I could find for now, although it's really hacky and somewhat unreliable :(

**Comment by sampaiodiego** [comment]
something like that.. you can also check if the `editedBy` field is there, which means the message was edited..

**Comment by 1valdis** [comment]
@sampaiodiego AFAIK it's there when the actual text of the message was edited. It isn't present when someone reacts or answers to it...

**Comment by sampaiodiego** [comment]
right, it is something extra you can check to validate it is a new message or not.

**Comment by Boby** [comment]
question also is there any reply message functions? do it make use of stream also?
