### ISSUE TITLE
Directory fields wrong size

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#13909]
As seen below when Federation is enabled:

![image](https://user-images.githubusercontent.com/8591547/55031861-58139580-4fee-11e9-8592-81a4393db69b.png)

**Comment by sudipt1999** [comment]
@sampaiodiego  should I fix it, I guess we need to increase the height of component

**Comment by sudipt1999** [comment]
I guess we need to set a min height attribute for that component and that will do the work

**Comment by sudipt1999** [comment]
#13915 pr for this issue

**Comment by ThreewayDude** [comment]
Setting the height attribute for the search bar to 100% corrects the issue

**Comment by ThreewayDude** [comment]
I found that setting height parameter of rc-input__element--small to 100% fixes the issue.

**Comment by sampaiodiego** [comment]
added a comment regarding the `Local Domains` field on the screenshot. it is there because Federation is enabled

**Comment by ThreewayDude** [comment]
Can I fix this issue? I was able to resolve the problem on my system.

**Comment by sudipt1999** [comment]
@ThreewayDude  Iam already working on that!

**Comment by ThreewayDude** [comment]
Oh I'm sorry. XD

**Comment by sampaiodiego** [comment]
take it easy guys =)

everyone is welcome to help and contribute.. an issue doesn't belong to a person :wink: 

you guys can help testing @tassoevan fixes on #13938
