### ISSUE TITLE
padding missing in button

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13907]
In memberlist, the button padding is broken or not done!
![Screenshot from 2019-03-27 01-27-44](https://user-images.githubusercontent.com/38929617/55029322-d47a9880-502f-11e9-86fc-eb32b90193f5.png)

**Comment by sudipt1999** [comment]
I am working on this.

**Comment by sudipt1999** [comment]
#13908

**Comment by tassoevan** [comment]
What browser was rendering it?
