### ISSUE TITLE
[UI] outline of modal button is not appropriate

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13912]
It looks like a large and a small button placed together!
![Screenshot from 2019-03-27 02-29-02](https://user-images.githubusercontent.com/38929617/55033054-46ef7680-5038-11e9-9e9a-8d368c895402.png)

**Comment by ggazzo** [comment]
sorry but I'm afraid its how should be =/ thats why have a "nude" button =/
