### ISSUE TITLE
Retention policy not working

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#13916]
### Description:

The automatic pruning of messages does not work. I had messages that were several months old and set the maximum message age to one day but it didn't remove anything. Now I've manually pruned all old messages in the hope that the automatic pruning will work when new messages are older than one day, but that doesn't work either.

### Steps to reproduce:

1. Activate Retention policy.
2. Set the precision to once an hour and maximum message age to one day.
3. Activate the feature for channels but deactivate for everything else.

### Expected behavior:

The messages older than one day in all public channels should be removed.

### Actual behavior:

No messages are removed, regardless of how old they are. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 3.2

### Additional context

The logs show that the runner is started once an hour, but it still doesn't delete anything.

### Relevant logs:
SyncedCron ➔ info Starting "Prune old messages by retention policy". 
SyncedCron ➔ info Finished "Prune old messages by retention policy".

**Comment by stephane-** [comment]
Hello, 

Same problem for me ( #12862 )

**Comment by engelgabriel** [comment]
@sampaiodiego closed this in #15252

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/feature-requests/issues/135

**Comment by piotrkochan** [comment]
same today on v3.6.3
