### ISSUE TITLE
WebRTC: Ability to set Stun Servers in Admin Console

### ISSUE THREAD

**Issue by compuguy** [RocketChat/Rocket.Chat#1392]
Currently, in the code for the WebRTC conferenceing there are three hardcoded STUN servers listed. I'm currently running it in a internet limited LAN, that cannot access these STUN servers. Could this be added as a setting in the administrator console?

**Comment by geekgonecrazy** [comment]
I think this would be a great idea.  Might be a somewhat easy change to do.

**Comment by engelgabriel** [comment]
To be done as part of https://github.com/RocketChat/Rocket.Chat/issues/933

**Comment by engelgabriel** [comment]
This will allow https://github.com/RocketChat/Rocket.Chat/issues/1118 to be done.

**Comment by engelgabriel** [comment]
Done via #2168
