### ISSUE TITLE
Adding emoji to message: focus in the filter box and make escape work

### ISSUE THREAD

**Issue by wiebeytec** [RocketChat/Rocket.Chat#13929]
### Description:

After clicking on the 'add emoji' icon for a message, there are two problems:

* if you want to filter, you first have to click the filter box. The way it is now, the popup is half-way pop-up, half-way pop-under.
* You can't press 'escape' to get rid if the pop-up should you change your mind.

### Expected behavior:

* Since a form control that you can type in pops up, I expect to be able to type in it without extra clicks. 
* Make it close when you press escape.

### Additional context

Firefox, both Linux and Windows.

**Comment by mohamedar97** [comment]
done in PR #13956
