### ISSUE TITLE
Problem calling method API

### ISSUE THREAD

**Issue by lucassmacedo** [RocketChat/Rocket.Chat#13939]
```
curl -k -H "X-Auth-Token: e_Rtq7LB-xxxxxxx" \
     -H "X-User-Id: xxxxxx" \
     -H "Content-type:application/json" \
     https://chat.xxxx.com.br/api/v1/settings/LDAP_Sync_Now \
     -d '{ "value": "method", "execute": true}' 
```
i got the error 
{"success":false,"error":"Method 'method' not found [404]","errorType":404}

**Comment by Impamark** [comment]
You crossposted this query to a few channels on https://open.rocket.chat and then didn't bother to wait for a reply to see if someone had an answer.

You haven't bothered to fill out a Issue template like this:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Have you considered your error message?

> 'method' not found

Where did you find the API end point `LDAP_Sync_Now` ?

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.
