### ISSUE TITLE
No Sound set for Desktop Notifications on Rooms

### ISSUE THREAD

**Issue by Kirinkunhime** [RocketChat/Rocket.Chat#13931]
### Description:

When joining a room ( e.g. #test-env ) I expect to receive a notification sound. 
When checking the notification preferences it seems that the 'Sound' under 'Desktop Notifications' is not set at all!

### Steps to reproduce:

1. Join a new room
2. Go to 'Notification Preferences'
3. Check 'Sound' under 'Desktop'

### Expected behavior:

Sound should be set to 'Use Account Preference' per default, as is Audio & Alerts.
All existing rooms without 'Sound' set should be migrated to 'Use Account Preference'

### Actual behavior:

Sound is not set at all. Manually setting it fixes the issue.
https://i.imgur.com/TWA0yS2.png

### Server Setup Information:

- Version of Rocket.Chat Server:  0.74.3
- Operating System: CentOs 7
- Deployment Method: Docker (K8s/Openshift)
- Number of Running Instances: 4
- DB Replicaset Oplog: Yes (?)
- NodeJS Version: 8 (minor version not known)
- MongoDB Version: 3.6

**Comment by antkaz** [comment]
I have the same problem. Also, when I create a new channel

Version of Rocket.Chat Server: 2.2.0
