### ISSUE TITLE
Helm chart not enabling oplog by default

### ISSUE THREAD

**Issue by mkretzer** [RocketChat/Rocket.Chat#13937]
### Description:

When using the helm chart to deploy rocket oplog is not enabled so scaling the rocket pod is not possible - which would be very helpful in most environments, even if no db ha is needed

### Steps to reproduce:

Deploy via normal helm chart
Oplog is not enabled

### Expected behavior:

Oplog enabled by default

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: Kubernetes in Debian
- Deployment Method: Helm
- Number of Running Instances: 2
- DB Replicaset Oplog: That is the issue
- MongoDB Version: 3.6

**Comment by engelgabriel** [comment]
this has been fixed.
