### ISSUE TITLE
[IMRPOVE] Mount reply from broadcast channels in direct channel

### ISSUE THREAD

**Issue by bhardwajaditya** [RocketChat/Rocket.Chat#13940]
Currently any reply to a message in a broadcast channel does not indicate to which message the sender has replied to.

It would be better if the reply is mounted to input field just like replies/quote in same channel.

![reply-broadcast](https://user-images.githubusercontent.com/23612313/55191010-0c681400-51c7-11e9-80cf-77d481c1d63c.gif)

**Comment by MartinSchoeler** [comment]
This seems to be already working in rocket.chat, closing this issue now. Thanks!!
