### ISSUE TITLE
[UI/ UX] Adding a button on page to scroll to top

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13950]
![Screenshot from 2019-03-29 23-20-01](https://user-images.githubusercontent.com/38929617/55252607-5578a080-5279-11e9-89a7-86345d083542.png)

How about adding a button to scroll at the top of the page! Will give a good UX to user

**Comment by kerolloz** [comment]
I believe this issue should be opened in docs repo :rolling_eyes:

**Comment by sudipt1999** [comment]
Will do !

**Comment by qazero** [comment]
Any update on this? Is there any button or way I can scroll to the top of a really long chat?
