### ISSUE TITLE
Exception in callback of async function: Error: Cannot find module './PeerServer'

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#13952]
Exception in callback of async function: Error: Cannot find module './PeerServer'
I20190329-21:26:26.919(1)?     at makeMissingError (packages/modules-runtime.js:222:12)
I20190329-21:26:26.921(1)?     at Module.require (packages/modules-runtime.js:241:17)
I20190329-21:26:26.922(1)?     at Module.moduleLink [as link] (/home/faz/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190329-21:26:27.083(1)?     at index.js (app/federation/server/index.js:1:762)
I20190329-21:26:27.085(1)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20190329-21:26:27.089(1)?     at Module.require (packages/modules-runtime.js:238:14)
I20190329-21:26:27.091(1)?     at Module.moduleLink [as link] (/home/faz/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190329-21:26:27.097(1)?     at importPackages.js (server/importPackages.js:1:918)
I20190329-21:26:27.099(1)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20190329-21:26:27.102(1)?     at Module.require (packages/modules-runtime.js:238:14)
I20190329-21:26:27.104(1)?     at Module.moduleLink [as link] (/home/faz/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
I20190329-21:26:27.109(1)?     at main.js (server/main.js:1:8)
I20190329-21:26:27.117(1)?     at fileEvaluate (packages/modules-runtime.js:336:7)
I20190329-21:26:27.119(1)?     at Module.require (packages/modules-runtime.js:238:14)
I20190329-21:26:27.121(1)?     at require (packages/modules-runtime.js:258:21)
I20190329-21:26:27.123(1)?     at /home/faz/local/build/programs/server/app/app.js:130579:15
I20190329-21:26:27.125(1)?     at /home/faz/local/build/programs/server/boot.js:411:36
I20190329-21:26:27.131(1)?     at Array.forEach (<anonymous>)
I20190329-21:26:27.133(1)?     at /home/faz/local/build/programs/server/boot.js:220:19
I20190329-21:26:27.135(1)?     at /home/faz/local/build/programs/server/boot.js:471:5
I20190329-21:26:27.137(1)?     at Function.run (/home/faz/local/build/programs/server/profile.js:510:12)
I20190329-21:26:27.191(1)?     at /home/faz/local/build/programs/server/boot.js:470:11

**Comment by steoo** [comment]
+1

**Comment by fifou17** [comment]
i did still same

**Comment by ggazzo** [comment]
delete the folder and run `git checkout .`

the folder was renamed `peerServer` -> `PeerServer` for some reason the git doesnt (probably you are using windows or macosx)... if the problem persists let me know. if not close the issue ;)

**Comment by fifou17** [comment]
@ggazzo im using github windows desktop

**Comment by ggazzo** [comment]
did you remove the folder or renamed?

**Comment by fifou17** [comment]
@ggazzo thank you so much you saved my day yes i did and its worked
