### ISSUE TITLE
Channel status images

### ISSUE THREAD

**Issue by devdudeNL** [RocketChat/Rocket.Chat#1396]
Hi there,

We're testing out rocket.chat and we love it!

We were however wondering if there was a way to add something of color (either the # or a bullet) to a channel to signify its importance. (red = crucial, orange = warning, green = normal, etc)

Is this something that could be done or does somebody maybe have an out-of-band way to do this?

Regards,

Mitchell
##

**Comment by engelgabriel** [comment]
This could probably be added as a plugin, what do you think @sampaiodiego ?

**Comment by sampaiodiego** [comment]
I think it is a good idea.. It don't need to be a plugin, could be an option of the channel with default value to 'none'.

**Comment by mderijcke** [comment]
@sampaiodiego - yes that would be perfect

**Comment by MartinSchoeler** [comment]
This will be fixed with the upcoming feature to add images to channels. I will be closing this issue for now.

**Comment by sampaiodiego** [comment]
@MartinSchoeler I don't thinks thats the same thing.

but still, why closing now instead of when the feature is done?
