### ISSUE TITLE
What's the difference between start-discussion and start-discussion-other-user?

### ISSUE THREAD

**Issue by lolimay** [RocketChat/Rocket.Chat#13960]
Hi, everyone! I am currently working on improving the Permissions part of the official documentation. See [docs/issues#1191](https://github.com/RocketChat/docs/issues/1191).

I am trying to understand 14 new permissions by reading the source code and testing locally. What I am confused about is the difference between `start-discussion` and `start-discussion-other-user`.

We can see the details of the implementation here:
[https://github.com/RocketChat/Rocket.Chat/blob/be18e1898dcfe16a8699f53e40e737de066debe7/app/discussion/client/createDiscussionMessageAction.js#L14](https://github.com/RocketChat/Rocket.Chat/blob/be18e1898dcfe16a8699f53e40e737de066debe7/app/discussion/client/createDiscussionMessageAction.js#L14)
[https://github.com/RocketChat/Rocket.Chat/blob/be18e1898dcfe16a8699f53e40e737de066debe7/app/discussion/server/methods/createDiscussion.js#L127](https://github.com/RocketChat/Rocket.Chat/blob/be18e1898dcfe16a8699f53e40e737de066debe7/app/discussion/server/methods/createDiscussion.js#L127)

It seems that a user can start a discussion if he has one of the `start-discussion-other-user` and `start-discussion-other-user` permissions. And I cannot find any useful source code to discriminate what difference between them.

Any help will be appreciated!

**Comment by MarcosSpessatto** [comment]
@lolimay the big difference is: `start-discussion-other-user` gives the permission to the user to create a discussion from a message sent by another user.
