### ISSUE TITLE
Auto Translate/Translate not working in discussions when first join

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#13965]
### Description:

If you attempt to translate a message using the translation action item in a discussion nothing happens.  Verified still works in DM's

### Steps to reproduce:

1. Ask someone nicely to start a discussion
2. Ask them to write something in another language
3. Join the discussion
3. Click the Toggle Original/Translated option from the message actions

### Expected behavior:

Translate like this:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/51996/55344080-12355200-5472-11e9-91ff-1905ed12755e.png">

### Actual behavior:

Nothing seems to happen.

### Server Setup Information:

- Version of Rocket.Chat Server: current develop
- Operating System: debian stretch
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.x
- MongoDB Version: 4.x

### Relevant logs:

No exceptions in log that I could find

**Comment by ggazzo** [comment]
actually @geekgonecrazy its a reactivity problem and not a discussion itself, if you try to open a public channel, the behavior/bug its same. because message template checks if your subscription has "autotranslate setting" as you have no discussion/channel subscription the setting is false/undefined... =/

**Comment by geekgonecrazy** [comment]
Ah... Blaze.  :)

I guess discussions i'm more likely to be reading while not a member.  Normal channels I usually just join.  Or have been there since beginning.
