### ISSUE TITLE
Current 1.0 beta: Joining channel looks weird in German

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#13971]
### Description:

On open.rocket.chat 's version of today, the "Join a channel button" in the message input looks weird (notice the blue "Beitreten" on the right hand side):
![image](https://user-images.githubusercontent.com/17176678/55393236-2bef9b80-553d-11e9-934f-cab59be301e0.png)

### Steps to reproduce:

1. Open a channel you're not joined to yet.
2. Verify the alignment and design of the join-button (you may need to switch the language to one where "join" is not a short word, such as German)

**Comment by rodrigok** [comment]
@mrsimpson can you check with latest version? This seems to be fixed as AFAIK.

**Comment by mrsimpson** [comment]
Yup, looks good op open...
