### ISSUE TITLE
Is the mobile version a HTML/JS app wrapped in the container?

### ISSUE THREAD

**Issue by basharov** [RocketChat/Rocket.Chat#1397]
I can't find the source for the mobile versions and wonder if they are native or hybrid apps?

**Comment by mderijcke** [comment]
The wrapped app: https://github.com/RocketChat/Rocket.Chat.cordova

iOS app in the works: https://github.com/RocketChat/Rocket.Chat.iOS
Planned Android app: https://github.com/RocketChat/Rocket.Chat.android

**Comment by engelgabriel** [comment]
thanks for the answer @mderijcke
