### ISSUE TITLE
Custom oAuth API Login Issue

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#13975]
Trying to login using an custom oauth provider "wordpress" and its not working witht the REST API. Any ideas on how i can go about getting an access token? Using rocketchat password logins for the users is not an option. Must use wordpress login.

**Comment by ubergeekzone** [comment]
I keep getting a 
`{"status":"error","message":"Unexpected AccessToken service wordpressmobile"}`

**Comment by ubergeekzone** [comment]
Do I need to setup something else?

**Comment by nguyentuandat** [comment]
The same issue here.

**Comment by geekgonecrazy** [comment]
This is fixed in the latest rc for 1.0
