### ISSUE TITLE
Can't upload files on Mac OSX app

### ISSUE THREAD

**Issue by vncdias** [RocketChat/Rocket.Chat#1398]
I've tried to share files in channels or DM, but unsuccessfull
All files looks unavailable/not selectable, like seen on this print screen
![](https://cloud.githubusercontent.com/assets/5617948/11146870/b3c6f128-89f0-11e5-901f-c7b9563cf8aa.png)

**Comment by marceloschmidt** [comment]
To upload file, you must enable the file type under Administration / File Upload.

![image](https://cloud.githubusercontent.com/assets/1986378/11152061/95a6ce76-8a17-11e5-8231-8ae6c69225a4.png)

The accepted value for this field is exactly like the `<file>` tag (http://www.w3.org/TR/html-markup/input.file.html)

**Comment by vncdias** [comment]
Thank you, @marceloschmidt.
