### ISSUE TITLE
Web interface doesn't load on IE11

### ISSUE THREAD

**Issue by fadanner** [RocketChat/Rocket.Chat#13989]
### Description:

When we load rocket.chat webinterface the page stucks loading with the three loading dots.
Same is for https://open.rocket.chat

### Steps to reproduce:

1. Start Internet Explorer 11
2. Browse to Rocket.Chat instance
3. Error: Page is not loading

### Expected behavior:

Page should load like with all other browsers.

### Actual behavior:

Page stucks loading with the three loading dots (animated).
IE11 Developer Tools Console shows a "Script1002:Syntaxerror"
![image](https://user-images.githubusercontent.com/7578777/55469068-f9a97100-5604-11e9-951e-5f0f421ae900.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu (4.4.0-104-generic)
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3

### IE11 Information:
Version 11.2848.14393.0
Updateversion 11.0.115 (KB4489873)

### Additional context

We tested with and without proxy, but problem exists with both.
We tested with and without reverseproxy, but problem exists with both.
We tested with and without GPOs / hardened security settings, but problem exists with both
We tested with and without ie11 compatibility view, but problem exists with both

### Relevant logs:
IE Logs
`
SCRIPT1002: Syntaxfehler
d1eef865fbf5b68bd6eb0f292fa51263c005b1ba.js (5,1702140)
`

**Comment by reetp** [comment]
@rocket-cat label add duplicate

Please search for duplicate Issues before opening another one.

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+IE11

**Comment by reetp** [comment]
@rocket-cat close

Please follow up on one of the other open bugs - probably #9385
