### ISSUE TITLE
let an admin change passwords or reset accounts

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#1399]
make it possible for an admin to reset a password (or change it in case email has problems getting to the user).   If for reasons that cannot be influenced the password reset email never arrives, the user is currently stuck.

**Comment by geekgonecrazy** [comment]
Actually found my self needing this. So :+1: :heavy_multiplication_x: 2

**Comment by tholu** [comment]
+1

**Comment by haceru** [comment]
Very useful for various reasons; as an example, right now the "Reset / recovery password" option is broken, so an user can`t get back to his account if he forgot the password

**Comment by Againstreality** [comment]
i realy like to see this

**Comment by fduraibi** [comment]
This is very important and should allow the admin to also reset all or a set of users, in case there was some kind of system compromise to force all users to get new passwords.

**Comment by marceloschmidt** [comment]
![setpassword](https://cloud.githubusercontent.com/assets/1986378/11965559/67f18b18-a8dc-11e5-90a3-5eba15ad47ff.gif)

Admins can change users' passwords now.

**Comment by billyJack1203** [comment]
I am an administrator of rocket chat and I still can not change passwords.  How do I fix Rocket chat on  Ubuntu Linux version 17.10 rocket chat version Rocket Chat 0.69.0
