### ISSUE TITLE
Livechat API 1.0.0-rc.0 no Work

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#13995]
### Description:
I upgraded from version 0.74.3 to version 1.0.0-rc.0, I deleted all users and rooms but even so continue to report that I have no agent online what is not true would be a bug of the new version? I have 3 agents online and the info I get is that there are no agents, I use the following code:  curl 'http://localhost:3000/api/v1/livechat/room?token=12345'
Respnse: {"isClientSafe":true,"error":"no-agent-online","reason":"Sorry, no online agents","message":"Sorry, no online agents [no-agent-online]","errorType":"Meteor.Error","success":false}r

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.0-rc.0
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.15.0
MongoDB Version: v3.6.10

**Comment by renatobecker** [comment]
@josep112 do you have any department registered?

**Comment by josep112** [comment]
Hi, @renatobecker ,
The only way I found it to work was to delete the mongodb and redo all the settings, I would just like to upgrade the version without losing the data, but what I think is that something is left in the mongodb that does not let the room work as it should be

**Comment by renatobecker** [comment]
> Hi, @renatobecker ,
> The only way I found it to work was to delete the mongodb and redo all the settings, I would just like to upgrade the version without losing the data, but what I think is that something is left in the mongodb that does not let the room work as it should be

I see.. So, now everything is working fine, right?

**Comment by josep112** [comment]
Yes, now it works, I'll try to solve the upgrade problem without having to delete the database

**Comment by renatobecker** [comment]
Okay. I'll close this issue.
Thanks.

**Comment by josep112** [comment]
@renatobecker ok,
Thanks

**Comment by josep112** [comment]
@renatobecker ok
Thanks
