### ISSUE TITLE
How can I get the address of the sidebar?

### ISSUE THREAD

**Issue by online0227** [RocketChat/Rocket.Chat#13997]
I want to implement sidebar only to the left div side of my website. But I do not its address to iframe.
How can I do this?

**Comment by reetp** [comment]
@rocket-cat close

Sorry but this is a support Issue and not a bug in Rocket.Chat (unless you have evidence otherwise)

Please read the documentation, search issues (including closed ones), have a search in forums https://forums.rocket.chat and ask in #support at https://open.rocket.chat

Thank you
