### ISSUE TITLE
Livechat widget issue : no toolbar with IE11 & running away from mouse cursor.

### ISSUE THREAD

**Issue by chojunki** [RocketChat/Rocket.Chat#14004]
### Description:

1. When I open a test page with livechat installation script provided from Rocket.Chat management console in Internet Explorer 11, the livechat widget has problems.
- when minimized, it shows maximize, alarm, and popup icon on the right side of the title bar.
- when maximized, those icons are now shown, precisely, they are located at much lower posion from the original position and seems invisible because of their white color. Style applied to the .title class has line-height property which should be inherited to .title .toolbar class but not applied.

2. Sometimes when I try to click toolbar icons whit chrome or edge, and sometimes when I move mouse cursor to the widget with IE, then the widget moves to the left and escapes from the monitor scrren as if it hates and tries to escape from the mouse cursor invation.

### Steps to reproduce:

1. Make a test html page with the javascript presented to you on livechat - installation page of the admin console
2. Open that page with a browser such as Internet explorer and chrome
3. Enjoy...

### Expected behavior:

Toolbar icons is shown when maximizing the widget when I open the test page in IE11

### Actual behavior:
Toolbar icons is not shown when maximizing the widget when I open the test page in IE11
Livechat widget goes left and leaves the monitor screen when I click the widget(Chrome) or move mouse cursor to the widget(IE11)

### Server Setup Information:

- Version of Rocket.Chat Server:  0.73.4
- Operating System: CentOS 7
- Deployment Method: Manual Installation
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

**Comment by reetp** [comment]
Please always test on latest eg 0.74.3 or v1.0.0-rc0 (big changes in livechat coming)
There are lot of issues with IE11. Have you searched for duplicates?

**Comment by chojunki** [comment]
My mistake. I am testing on 0.74.3.

**Comment by ggazzo** [comment]
@chojunki I believe you are using the old livechat version, which we are deprecating, so after this pr https://github.com/RocketChat/Rocket.Chat/pull/15133 the problems will disappear...could you test with the new widget version? thx
