### ISSUE TITLE
Bug: Menu bar items are still in English, even if the language is changed to German

### ISSUE THREAD

**Issue by Myrthian** [RocketChat/Rocket.Chat#14001]
Description:
- Change rocket.chat language to German -> save
- The language of almost everything is correctly set to German except the menu bar, which still remains English

Expected result:
 - Change of rocket.chat language changes every text inside the client to the chosen language

**Comment by MartinSchoeler** [comment]
Hello @Myrthian, I've tested this issue on the latest version of Rocket.Chat and could not reproduce the problem, If you experience this issue again, please reopen this telling us the server version and specifying where exactly the issue happens. Thanks!
