### ISSUE TITLE
Bug: "Invite Users" search box doesn't support Germanic umlaut

### ISSUE THREAD

**Issue by Myrthian** [RocketChat/Rocket.Chat#14000]
Description:
 - Create a new channel
 - Members List -> Invite Users
 - The search box doesn't support Germanic umlaut

Expected result:
 - The search box supports Germanic umlaut, just like the search box in Members List

**Comment by stfnnfts** [comment]
+1

**Comment by MartinSchoeler** [comment]
This is more likely a setting not set properly set than a bug, please make sure that the setting `UTF8 Names Validation` under `Administration -> General -> UTF8` has a valid regexp value. I've tested on version `2.2.0-develop` and it seems to be working alright
<img width="403" alt="Screen Shot 2019-10-21 at 10 01 25" src="https://user-images.githubusercontent.com/20868078/67207535-32b30280-f3ea-11e9-89bd-4a399665325d.png">
Thanks!
