### ISSUE TITLE
Bug: Text outside of buttons if rocket.chat client window is re-sized

### ISSUE THREAD

**Issue by Myrthian** [RocketChat/Rocket.Chat#14002]
Description:
- Change client language to German
- Re-size the window while being on the "My account" page
- The text for both bottons is partially outside the frame of the buttons
![image](https://user-images.githubusercontent.com/30933093/55536168-5fefcb80-56b9-11e9-9673-5a147683643e.png)

Expected result:
- Text is always inside the frame of buttons, even when/after re-sizing the client window

**Comment by Rodriq** [comment]
@Myrthian please explain where exactly you got this. which page?
  If we change the language, where next are we suppose to go to see this error?
