### ISSUE TITLE
Livechat with facebook integration  doesn't shows the first message 

### ISSUE THREAD

**Issue by RodrigoFerrazsc** [RocketChat/Rocket.Chat#14013]
### Steps to reproduce:

1. Go to facebook and send a message on a page
2. Go to Rocket chat and wait for message 
3. message never comes

### Expected behavior:

See the messages of facebook page

### Actual behavior:

Hello guys,
When a new client(A) sends a message on facebook(" a simple "hello", for example), it does not matter how much time I wait for the message it never comes. But if the same client(A) sends another message after the first it appears. At this point everything works fine, i can see new messages and answer from rocketchat ... As I see, new clients have this issue but if the same customer is in the database as "guest01, guest02, etc" the error does not occur.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 16.04
- Deployment Method: etc
- Number of Running Instances: 1
- DB Replicaset Oplog: off
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.11

### Log of first message(not showing on  rocketchat)

[34mI20190405-14:08:17.069(0) API ➔ debug POST: //api/v1/livechat/facebook 
[34mI20190405-14:08:17.083(0) API ➔ debug Success { statusCode: 200, body: { success: true } } 
[34mI20190405-14:08:46.087(0) Meteor ➔ method private-settings/get -> userId: GoNrz4G2euWB36WLT , arguments:  [] 
[34mI20190405-14:08:46.175(0) Meteor ➔ method getStatistics -> userId: GoNrz4G2euWB36WLT , arguments:  [] 
[34mI20190405-14:08:46.182(0) Meteor ➔ method instances/get -> userId: GoNrz4G2euWB36WLT , arguments:  [] 

### Log of other messages from the same cliente(showing on rocketchat)

API ➔ debug POST: //api/v1/livechat/facebook 
[34mI20190408-12:59:43.731(-3) Integrations ➔ Outgoing WebHook.debug Execute Trigger: sendMessage 
[34mI20190408-12:59:43.737(-3) Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: sendMessage { event: 'sendMessage',   message:     { _id: '0NX-6ROTC1fkz8EsByheW6qxDpGT9bBlRzQG_ii82hjXirVHVyaq9mG35xC5KnVbfcTvzykgsWidUHeus7DGAQ',      rid: 'uKXmhuw5ooQsiRifH',      token: '2190426137718981',      msg: 'Teste',      alias: 'Rodrigo Ferraz',      ts: 2019-04-08T15:59:43.697Z,      u:        { _id: 'AKNgsu8DEJxa3mErg',         username: 'guest-19',         name: 'Rodrigo Ferraz' },      _updatedAt: 2019-04-08T15:59:43.706Z,      editedBy: undefined,      editedAt: undefined,      emoji: undefined,      avatar: undefined,      customFields: undefined,      groupable: undefined,      attachments: undefined,      reactions: undefined,      parseUrls: undefined,      mentions: [],      channels: [],      newRoom: false,      showConnecting: false,      sandstormSessionId: null },   room:     { _id: 'uKXmhuw5ooQsiRifH',      msgs: 6,      usersCount: 1,      lm: 2019-04-08T15:49:33.788Z,      fname: 'Rodrigo Ferraz',      t: 'l',      ts: 2019-04-08T13:56:43.128Z,      v:        { _id: 'Gykpxmd3HkpF2fw8u',         username: 'guest-15',         token: '2190426137718981',         status: 'online' },      servedBy:        { _id: 'GoNrz4G2euWB36WLT',         username: 'sysmaster',         ts: 2019-04-08T13:56:43.128Z },      cl: false,      open: true,      facebook: { page: [Object] },      _updatedAt: 2019-04-08T15:49:33.844Z,      lastMessage:        { _id: '9cNN7Z6QhhAq9j7Kt',         rid: 'uKXmhuw5ooQsiRifH',         msg: 'ao',         ts: 2019-04-08T15:49:33.788Z,         u: [Object],         _updatedAt: 2019-04-08T15:49:33.813Z,         mentions: [],         channels: [],         sandstormSessionId: null },      metrics:        { v: [Object],         reaction: [Object],         response: [Object],         servedBy: [Object] },      responseBy: { _id: 'GoNrz4G2euWB36WLT', username: 'sysmaster' } } } 
[34mI20190408-12:59:43.738(-3) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: uKXmhuw5ooQsiRifH 
[34mI20190408-12:59:43.739(-3) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
[34mI20190408-12:59:49.567(-3) Meteor ➔ method readMessages -> userId: GoNrz4G2euWB36WLT , arguments:  [ 'uKXmhuw5ooQsiRifH' ]

**Comment by renatobecker** [comment]
Issue moved to [RocketChat/OmniChannel.Gateway #5](https://github.com/RocketChat/OmniChannel.Gateway/issues/5) via [**ZenHub**](https://www.zenhub.com/)

**Comment by RodrigoFerrazsc** [comment]
@renatobecker  i can't access the link...is it normal?

**Comment by canuckbrian** [comment]
I'm having this exact same problem.

### **Server Setup Information**:
- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 18.04.3
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 3.6.14

It doesn't happen with every message, but frequently enough the first message never gets delivered in RocketChat, but subsequent messages do.

**Comment by Emersonsanch** [comment]
I'm having this exact same problem.
