### ISSUE TITLE
Mentions email inside discussions uses the wrong name property

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#14019]
Emails are getting the wrong property for alerts

**Comment by sampaiodiego** [comment]
can you please give more details about the issue?

when testing I got this email, where `general - Testing a new message for a discussion.` is the discussion title:

![image](https://user-images.githubusercontent.com/8591547/55670275-d37c0f00-5858-11e9-9a3f-43acddcdfb3f.png)
