### ISSUE TITLE
Livechat office hours

### ISSUE THREAD

**Issue by uglimugli** [RocketChat/Rocket.Chat#14014]
## My Setup
- Operating System: Ubuntu 18.04
- App Version: 0.74.3
- Installation type: snap

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description

live chat office hours show up twice
![kuva](https://user-images.githubusercontent.com/15074905/55602824-1f06be00-5770-11e9-8860-3ed7b6dcf1de.png)

**Comment by renatobecker** [comment]
Hi @uglimugli. It seems to be a migration issue.
Are you granted to access the DB?

**Comment by rasos** [comment]
Seems to be a duplicate of #4898

Check the DB collection `rocketchat_livechat_office_hour`

**Comment by geekgonecrazy** [comment]
Agreed closing in favor of #4898
