### ISSUE TITLE
MONGO-REPLICA exited with code 0

### ISSUE THREAD

**Issue by Tofdu31** [RocketChat/Rocket.Chat#14020]
### Server Setup Information:
- Version of Rocket.Chat Server: latest
- Operating System: Docker
- Deployment Method: docker with your docker-compose.yml
- MongoDB Version: 4.0

### Problem :
Hi all,
Since 2 days I look for a solution for the error you have on mongo replication:
MONGO-REPLICA exited with code 0
Looking at the logs, I'm amazed at this:
> MongoDB shell version v4.0.8
> connecting to: mongodb://mongo:27017/rocketchat?gssapiServiceName=mongodb

For the rest everything works. I only have problems with mongo replica

Thanks for your help

[docker-compose-rocket.chat.yml.txt](https://github.com/RocketChat/Rocket.Chat/files/3050530/docker-compose-rocket.chat.yml.txt)
[log.mongo.replica.txt](https://github.com/RocketChat/Rocket.Chat/files/3050531/log.mongo.replica.txt)
[sample.env.txt](https://github.com/RocketChat/Rocket.Chat/files/3050532/sample.env.txt)

**Comment by Zegorax** [comment]
This is intended behavior. The mongo-init-replica container's goal is only to init the database and then exit.

**Comment by geekgonecrazy** [comment]
Code 0 is a non error exit code. Going to go ahead and close.  Feel free to open another issue if you find a bug
