### ISSUE TITLE
RoomInformation: Leave Button is not completely in the Window

### ISSUE THREAD

**Issue by sfahrenholz** [RocketChat/Rocket.Chat#14023]
### Description:

When i show me the Room information, the button to leave the room is not complete showing in the window.

![image](https://user-images.githubusercontent.com/6977657/55671635-89178400-5892-11e9-9795-7b6df1f2bb28.png)

### Steps to reproduce:

1. Go into a room
2. show room information

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.0-beta

![image](https://user-images.githubusercontent.com/6977657/55671702-06db8f80-5893-11e9-9a24-f82b9f03ff82.png)

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15511
