### ISSUE TITLE
Cors Issue trying to access Rocket Chat file upload hosted on S3

### ISSUE THREAD

**Issue by kelvinblade** [RocketChat/Rocket.Chat#14035]
I am trying to access uploaded files through Rocket Chat that are hosted on S3. I am encountering a CORS error. CORS option is enabled for * on Rocket chat. File upload protected is enabled. I have added 

It works in postman.

GET http://3.0.253.143:3000/file-upload/7uvaAJgJrneitgywJ/_png.png with a header of X-User-Id and X-Auth-Token

In dev on localhost, I am getting

> Access to fetch at 'http://3.0.253.143:3000/file-upload/7uvaAJgJrneitgywJ/_png.png' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

My code is:

  ```
fetch('http://3.0.253.143:3000/file-upload/7uvaAJgJrneitgywJ/_png.png', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'X-User-Id': ******,
      'X-Auth-Token': *******,
      'Access-Control-Allow-Credentials': 'true',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    }
  });
```
In Rocket Chat, under general & rest api, cors is enabled and origin set to *.

In S3, I have added:

```
<?xml version="1.0" encoding="UTF-8"?>
    <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
        <CORSRule>
            <AllowedOrigin>*</AllowedOrigin>
            <AllowedMethod>PUT</AllowedMethod>
            <AllowedMethod>POST</AllowedMethod>
            <AllowedMethod>GET</AllowedMethod>
            <AllowedMethod>HEAD</AllowedMethod>
            <MaxAgeSeconds>3000</MaxAgeSeconds>
            <AllowedHeader>*</AllowedHeader>
        </CORSRule>
    </CORSConfiguration>
```
Using a chrome extension to allow cors, https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

I still get this error:

> Access to fetch at 'http://3.0.253.143:3000/file-upload/7uvaAJgJrneitgywJ/_png.png' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

With and without the token I am getting the same CORS error. The status code returned is 403 forbidden. In postman, I get 403 forbidden without the token and it works fine with the token.

I tried asking on stackoverflow but wasn't able to resolve this issue. Any help would be appreciated.

**Comment by ankitbrahmbhatt1997** [comment]
@kelvinblade did you find any solution ? stuck on this right now
