### ISSUE TITLE
where is the docker-compose.yml file located?

### ISSUE THREAD

**Issue by paOol** [RocketChat/Rocket.Chat#1404]
```Look for the docker-compose.yml file at the top level of the source directory.```

I looked around in /var/lib/docker and could not find the file.

I did a clean install of docker and docker-compose so everything is stock at the moment.
did a docker pull of the image and nothing else yet.

**Comment by romdi** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml

**Comment by paOol** [comment]
thanks, but perhaps I am missing something crucial as I don't know where the file is on my server to edit.

I installed docker
installed docker-compose
pulled the rocket.chat image

did a sudo find for 'docker-compose.yml' and could not find anything.

do I need to docker run first in order for the directory to be created 
then modify the .yml file,
then docker-compose?

**Comment by Sing-Li** [comment]
A)  Use a text editor to create this docker-compose.yml file (you can copy and paste if you like): 

https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml

B) Follow the rest of the instructions....

**Comment by Sing-Li** [comment]
Closing this since you now know where the docker-compose.yml file is.
