### ISSUE TITLE
SAML generateUniqueID return IDs that don't meet RFC

### ISSUE THREAD

**Issue by cypherkey** [RocketChat/Rocket.Chat#1405]
The SAML request (AuthNRequest) generated intermittently contains an invalid ID attribute to the SAML Request:

<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    ID="9J67uvaWqgPxKTe9B"
                    Version="2.0"

RFC states the the ID cannot start with a number. Our IDP is PingFederate and it rejects AuthNRequests starting with a number. The best solution for this is to start with an underscore. My recommendation is to modify the generateUniqueID() method in packages/meteor-accounts-saml/saml_utils.js to start all unique IDs with an underscore:

line 53:  var uniqueID = "_";
##

**Comment by cypherkey** [comment]
References:
http://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameStartChar
http://stackoverflow.com/questions/5076675/saml-authentication-request-protocol-id

**Comment by geekgonecrazy** [comment]
We should absolutely take a look at this.  I think we're using meteor generated id's by default instead of generating our own.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
