### ISSUE TITLE
While DMing a user, quote and reply are the same

### ISSUE THREAD

**Issue by fliptrail** [RocketChat/Rocket.Chat#14063]
### Description:

While DMing a user, quote and reply option both are the same. 
So, one option can be removed.

![Screenshot from 2019-04-09 15-56-50](https://user-images.githubusercontent.com/40834245/55793216-0a178b00-5ae0-11e9-9227-a2cfe53cafdb.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0 - develop

**Comment by geekgonecrazy** [comment]
They have been for a long time.  The reply for the longest time was quote + mention.  But now reply’s are threaded.  So depends on the plan here for DMs if reply should truly be removed.

@rocketchat/core ?

**Comment by ggazzo** [comment]
now you can quote, or reply as thread so I think that problem does not exist anymore :)
