### ISSUE TITLE
LDAP Login not possible when Sync User Avatar ist enabled

### ISSUE THREAD

**Issue by ruppo68** [RocketChat/Rocket.Chat#14068]
### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 18.04.2 LTS (Bionic Beaver)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: rs01
- NodeJS Version: 8.11.4
- MongoDB Version: v3.4.2

Ldap is configured:
Try to login as ldap user not possible:
In the log:
Apr  9 15:31:24 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAP ➔ Auth.info Authenticated CN=Rupp Peter,OU=DU,OU=Standard,OU=TQ-Users,OU=TQ-Group,DC=tq-net,DC=de
Apr  9 15:31:24 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAPHandler ➔ info Querying user
Apr  9 15:31:24 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAPHandler ➔ info Logging user
Apr  9 15:31:24 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAPSync ➔ info Syncing user data
Apr  9 15:31:24 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAPSync ➔ info Syncing user avatar
Apr  9 15:31:24 testrocket RocketChat[1346]: Exception while invoking method 'login' TypeError: Cannot read property 'getFilter' of undefined
Apr  9 15:31:24 testrocket RocketChat[1346]:     at FileUploadClass.insert (packages/rocketchat:file-upload/server/lib/FileUpload.js:360:29)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at DDPCommon.MethodInvocation.Meteor.runAsUser (packages/rocketchat:ldap/server/sync.js:211:15)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at packages/dispatch_run-as-user.js:211:14
Apr  9 15:31:24 testrocket RocketChat[1346]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at syncUserData (packages/rocketchat:ldap/server/sync.js:210:11)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at MethodInvocation.<anonymous> (packages/rocketchat:ldap/server/loginHandler.js:122:3)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at AccountsServer.Accounts._runLoginHandlers (packages/rocketchat:lib/server/lib/loginErrorMessageOverride.js:7:35)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at Promise (packages/ddp-server/livedata_server.js:715:46)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at new Promise (<anonymous>)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr  9 15:31:24 testrocket RocketChat[1346]:     at packages/ddp-server/livedata_server.js:559:43
Apr  9 15:31:25 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAP ➔ Search.info Idle
Apr  9 15:31:25 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAP ➔ Connection.info Disconecting
Apr  9 15:31:25 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAP ➔ Search.info Closed
Apr  9 15:31:25 testrocket systemd[1]: Starting Cleanup of Temporary Directories...
Apr  9 15:31:25 testrocket systemd[1]: Started Cleanup of Temporary Directories.

If I try to sync from ldap this is the error:

Apr  9 15:33:18 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAPSync ➔ info Syncing user data
Apr  9 15:33:18 testrocket RocketChat[1346]: rocketchat:logger server.js:199 LDAPSync ➔ info Syncing user avatar
Apr  9 15:33:18 testrocket RocketChat[1346]: Exception in callback of async function: TypeError: Cannot read property 'getFilter' of undefined
Apr  9 15:33:18 testrocket RocketChat[1346]:     at FileUploadClass.insert (packages/rocketchat:file-upload/server/lib/FileUpload.js:360:29)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at DDPCommon.MethodInvocation.Meteor.runAsUser (packages/rocketchat:ldap/server/sync.js:211:15)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at packages/dispatch_run-as-user.js:211:14
Apr  9 15:33:18 testrocket RocketChat[1346]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at syncUserData (packages/rocketchat:ldap/server/sync.js:210:11)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at addLdapUser (packages/rocketchat:ldap/server/sync.js:262:2)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at ldapUsers.forEach.ldapUser (packages/rocketchat:ldap/server/sync.js:319:5)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at Array.forEach (<anonymous>)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at ldap.searchUsersSync.Meteor.bindEnvironment (packages/rocketchat:ldap/server/sync.js:286:13)
Apr  9 15:33:18 testrocket RocketChat[1346]:     at runWithEnvironment (packages/meteor.js:1356:24)

If Sync User Avatar is disabled, LDAP login works

**Comment by Shaverdoff** [comment]
i have the one instalation only in OS diff. i use Centos and 3-ee instanse
Sync User Avatar is enabled, and ldap user successcfull login. i use Active Directory instead OpenLdap

**Comment by plmorpheus** [comment]
Same here on Snap 3.6.2. Maybe consider this as a bug?

**Comment by pierre-lehnen-rc** [comment]
It was fixed on 3.6.3 by #18994
