### ISSUE TITLE
Data migration from one to another server

### ISSUE THREAD

**Issue by jankogaga** [RocketChat/Rocket.Chat#14077]
Hi,

We run Rocket chat 0.74.3 and try to move data from one server to another by MongoDB backup/restore procedure.
However, the attachments from "old" server weren't transferred and one of a public channel is not available with the message:  No channel with name "xxx" was found!

Thanks,
Dragan

**Comment by jankogaga** [comment]
/data/fs folder has been moved from the first to the second Rocket chat server and FileUpload settings are adjusted.
Still chasing for missing the announcement channel.

**Comment by geekgonecrazy** [comment]
This is more of a support thing. 

Feel free to post in forum.  Suggest posting more information about the source install setup and destination install setup though for better help.
