### ISSUE TITLE
No back button on page 2 from page 1 Setup Wizard

### ISSUE THREAD

**Issue by arthurbdiniz** [RocketChat/Rocket.Chat#14079]
### Description:
When necessary make some correction in step 1 of setup wizard, there is no button to back up. The opposite happens from step 3 back to step 2.

### Steps to reproduce:
1. Create docker-compose.yml
2. Run docker-compose up
3. Start setup wizard
4. Go to second page
5. Try to get back to page 1

### Expected behavior:
![image](https://user-images.githubusercontent.com/18387694/55878169-4a274e00-5b72-11e9-86df-31fe10ed7130.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/18387694/55878189-53b0b600-5b72-11e9-9c06-edbc057640db.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: mongo:4.0

**Comment by im-adithya** [comment]
@gabriellsh @dougfabris @ggazzo 
What do you guys think about this?
Can make a PR by shifting the email process after the 4th step (currently gets processed just after completion of the first step itself) and then we can incorporate back button for 2 -> 1 as well...

**Comment by dougfabris** [comment]
@im-adithya Feel free to help us with a PR. I believe we can change the process of persisting the data during the steps and just submit it in the final step. It should solve another issue related (I can't remember now) about data not persisting on the third step.
