### ISSUE TITLE
Editing is broken.

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#1407]
The edit feature is broken. The icons does not show up on the demo server hosted by the developers -- but editing via the arrows works on their server.

On my own deployed instance the icons are there but you cannot edit. The delete feature works.

When I try to edit a message using the up and down arrows of my keyboard this what shows up in the console:
```
debug.js:41 Error invoking Method 'updateMessage': Internal server error [500]
debug.js:41 Error invoking Method 'updateMessage': Internal server error [500]
```

**Comment by Sing-Li** [comment]
@k0nsl   Please provide specific build information.

Try `http://<your server name or ip>/buildinfo/buildinfo.txt`

Read the version number off the first line.

**Comment by k0nsl** [comment]
Sorry for being very vague. Here is the information:
```
v0.7.dev
This is an unsupported non-production development release.
```
The virtual machine runs Debian 8 with 4GB RAM; 2 CPUs (2 sockets; 8 cores -- so 16 with hyperthreading accounted)

**Comment by Sing-Li** [comment]
@k0nsl no problem.  

But we do not support vX.X.dev anymore.  Since there is no way we can know how the code was checked out, or even modified.    

All of our standard deployment methods now uses versioned build binaries.

Please switch to our latest deployment build, and if the problem still exists, re-open this ticket, thanks.  (if you do re-open this ticket, please also supply the MongoDB version number)

**Comment by k0nsl** [comment]
Thanks for the reply.

My way of deployment is the following:
Clone it and then start it with `meteor`.

I update the application by hard-resetting it, like so:

`git fetch --all && git reset --hard origin/master`

But as per your (?) instruction I am now doing it like this:

`git fetch --all && git reset --hard origin/develop`

The issue persists just the same.

**Comment by k0nsl** [comment]
If this helps, so be it. Here is output from the terminal after trying to (unsuccessfully) edit a message:
```
I20151114-16:59:32.887(-5)? Exception while invoking method 'updateMessage' { stack: 'ReferenceError: message is not defined\n    at _Class.RocketChat.models.Messages._Class.cloneAndSaveAsHistoryById (packages/rocketchat_lib/server/models/Messages.coffee:113:3)\n    at [object Object].Meteor.methods.updateMessage (server/methods/updateMessage.coffee:31:31)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:708:19\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:706:40\n    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)\n    at livedata_server.js:704:46\n    at tryCallTwo (/root/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)',
I20151114-16:59:32.887(-5)?   source: 'method' }
```

**Comment by Sing-Li** [comment]
Reproducible.

ONLY for non-admin user.

**Comment by k0nsl** [comment]
I get the same result with normal user or admin, it doesn't matter which.

**Comment by Sing-Li** [comment]
K .. definitely looks like it is all part of this commit 3 days ago ...  related to #1411 

https://github.com/RocketChat/Rocket.Chat/commit/f5df20aff1e99a6b44f467bc7c2cbf823e70c5f8

**Comment by Sing-Li** [comment]
Tested and confirmed fixed.
