### ISSUE TITLE
[BUG] Discussion name is not displayed while muting a user in a discussion

### ISSUE THREAD

**Issue by mohamedar97** [RocketChat/Rocket.Chat#14080]
### Description:

The discussion name is not displayed when a user is being muted in a discussion

### Steps to reproduce:

1. Go to any discussion you created 
2. Click on members list
3. Open the options list for any user
4. Click on mute 

### Expected behavior:

it should display the room name instead of the Id

### Actual behavior:

![image](https://user-images.githubusercontent.com/44686958/55885205-ce48f800-5ba9-11e9-8e7e-ddb26c3f897d.png)

### Additional information
i'm working on this issue

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

![image](https://user-images.githubusercontent.com/20212776/231244748-fb18b2ac-9d3c-41b1-b21e-7705649559a9.png)


[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
