### ISSUE TITLE
Home Page - how to change  script 

### ISSUE THREAD

**Issue by tommycwleung** [RocketChat/Rocket.Chat#14088]
is there a way to change the Home Page, especially the welcome message. 
I may like to rewrite the homepage.
[DefaultHome.docx](https://github.com/RocketChat/Rocket.Chat/files/3066057/DefaultHome.docx)

**Comment by Maqsyo** [comment]
"If you're an admin, feel free to change this content via Administration -> Layout -> Home Body"

**Comment by karahbura** [comment]
is there anyway to put jpg, png or video into the home page window instead of just text? id like to put logos or spalsh pict something besides text.

**Comment by Maqsyo** [comment]
> is there anyway to put jpg, png or video into the home page window instead of just text? id like to put logos or spalsh pict something besides text.

just use normal html and insert whatever you want. for example we inserted an giphy-picture

**Comment by Maqsyo** [comment]
@tommycwleung could you please close this "issue" ?

**Comment by karahbura** [comment]
nothing shows up. my jpgs are missing. is there any example? id really appreciate it.  do i need and img folder? thanks in advance.

**Comment by Maqsyo** [comment]
@karahbura could you show us your html and maybe the console output?
You should ask questions like these on stack-overflow

**Comment by reetp** [comment]
I was about to close this, but on second thoughts maybe not.

Something that doesn't seem easy to do is add local images to the home page.

So you can add a image URL, though you may get a 403 for https linked ones (happened to me while testing)

You can add a file in a public channel and link to that.

There is no way to add other local 'Asset' and give it a simple relative URL the same way as say the logo.

Perhaps there should be an enhancement to allow an admin to add other files for local 'administrative' use?

Perhaps that should also respect your local file storage? Currently Assets seem to get stored in the DB regardless of what file storage is used. Is there any reason that we couldn't just use a URL in Assets as well?

This Issue should probably be renamed something like:

"Enhance Local Asset management"

**Comment by Maqsyo** [comment]
@reetp please open a new issue and dont missuse this "issue" here.
