### ISSUE TITLE
Starring image causes it to rerender

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#14092]
### Description:
https://giphy.com/embed/QsyPWzTKSmRRC7XesS

Probably related to #5028 in some way.  But this one has no good reason to be causing a refresh.  A reaction is obviously needing to re-render part of the dom.. this isn't touching any UI related to the message

### Steps to reproduce:

1. send a message to another user
2. star and unstar that image
3. watch it flicker like crazy each time you do it

### Expected behavior:

Nothing should happen.. 

### Actual behavior:

we cry..

### Server Setup Information:

- Version of Rocket.Chat Server: develop (open.rocket.chat)
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: true
- NodeJS Version: docker
- MongoDB Version: 4.0

**Comment by Kailash0311** [comment]
@geekgonecrazy can you please review it?

**Comment by knrt10** [comment]
@geekgonecrazy this is fixed I think. Can you please close this

**Comment by oguhpereira** [comment]
@geekgonecrazy  is fixed in #14207. 

![1](https://user-images.githubusercontent.com/24482087/65279075-cd76a380-db03-11e9-842f-9570d1f11394.gif)
