### ISSUE TITLE
Check if Department status is online before showing the LiveChat widget

### ISSUE THREAD

**Issue by carlo-fontanos** [RocketChat/Rocket.Chat#14094]
Hi,

I would like to show the LiveChat widget only if the department is online (there is an agent online)

Something like: 
```
if(is_department_online('my_department_name') === true){
   // show LiveChat widget
}
```

Is this possible? I checked the live chat API but there seem to be no methods available that can help achieve this.

**Comment by renatobecker** [comment]
We have implemented new API methods on the new Livechat:
https://github.com/RocketChat/Rocket.Chat.Livechat

On **1.1** release will be possible to show/hide the widget.
https://github.com/RocketChat/Rocket.Chat.Livechat/pull/225.
