### ISSUE TITLE
LiveChat: Send offline message to the agent of the target department?

### ISSUE THREAD

**Issue by carlo-fontanos** [RocketChat/Rocket.Chat#14095]
Hi,

Is there a way to send the offline message to the agents of the target department rather than sending it to the email address configured on the `Email address to send offline messages` field at `admin panel > livechat > offline`?

**Comment by renatobecker** [comment]
Hi @carlo-fontanos.
Do you mean an e-mail message?

**Comment by carlo-fontanos** [comment]
Hi @renatobecker,
Yes, an e-mail message,

**Comment by renatobecker** [comment]
@carlo-fontanos, it's not possible.
But you can now send e-mails per departments, there is a new e-mail field on Livechat departments.

**Comment by carlo-fontanos** [comment]
I created a agent and added my email to the livechat department settings, but I'm still not receiving any emails from customers who are contacting me via the livechat offline form..

Any ideas?

**Comment by carlo-fontanos** [comment]
I tried the "Send a test mail to my user" button located under `admin/Email/SMPT` of RocketChat admin, the message says it was successfully sent but I didn't receive any email. Could this be the problem?

**Comment by renatobecker** [comment]
> I tried the "Send a test mail to my user" button located under `admin/Email/SMPT` of RocketChat admin, the message says it was successfully sent but I didn't receive any email. Could this be the problem?

Maybe... but then it's not related to the Livechat feature.

**Comment by carlo-fontanos** [comment]
So how do we fix this issue? do you have any suggestions on which things should we check in order to verify weather this is a problem with the server or rocketchat?

We have rocketchat hosted here: [](https://cyberauctionschat.com/)

**Comment by carlo-fontanos** [comment]
Need answer to this please @rodrigok @engelgabriel @sampaiodiego @marceloschmidt
