### ISSUE TITLE
Delay when changing between channels - add subscription manager

### ISSUE THREAD

**Issue by riaan53** [RocketChat/Rocket.Chat#141]
Hi,

It looks like when changing between channels all data is resent again even if no new messages have been added. Adding a subscription manager caches the data on the client for a set amount of time. The result should be more snappy channel changes, less load on the server and less data transfered.

The subscription manager can be added for most of the subscribes, except for notifications, user status and so on.

For more detailed explanation see: https://github.com/meteorhacks/subs-manager

Also have a look at https://github.com/meteorhacks/fast-render

Regards,
Riaan

**Comment by rodrigok** [comment]
I agree @riaan53.

@riaan53 can you help us with this?

**Comment by riaan53** [comment]
Hi @rodrigok,

Will help anytime. I spoke to @engelgabriel about this quickly on the general channel and he said that it will actually be resolved in the next release and that theres already a type of subscription manager in rocket chat. One of the problems was related to unnecessary data kept in memory. Gabriel can you elaborate please? Does the subs manager cache subscriptions to avoid unwanted data transfers?

Regards,
Riaan

**Comment by engelgabriel** [comment]
@riaan53 is this fixed now? We finished the first level of refactoring to improve performance. We still plan  make it even faster, but I think it is acceptable now? Reopen the issue otherwise.
