### ISSUE TITLE
Custom Oauth login with provider access Token

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#14108]
We have a method called: `registerAccessTokenService` 
Source found: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/oauth.js#L9

It is executed from the login endpoint: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/oauth.js#L27

So when you do a login like: 
```
curl -H "Content-type:application/json" \
      http://localhost:3000/api/v1/login \
      -d '{ "serviceName": "yourOauth", "accessToken": "tokenFromOauthProvider", "expiresIn": 200 }'
```

serviceName matches the oauth service registered and executes the function passed.  That returns an object like:
```
{
  serviceData,
  options: {
    profile: {
      name: identity.name,
    },
  },
};
```

That then finds or creates an account here: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/oauth.js#L54

An example of an oauth provider registering:
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/google.js#L28

It takes the access token and calls google with it to get the identity: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/google.js#L10

This is ensuring its valid as well as getting some info about the user that the token belongs to.

The data is then pieced together: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/google.js#L39

picked of only the fields we want: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/oauth/google.js#L46

then returned as mentioned above.

That needs added in here: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/custom-oauth/server/custom_oauth_server.js making use of the access patterns setup.  Can likely reuse a lot of the code/functions already there to make this not so bad.

This would also close out: https://github.com/RocketChat/Rocket.Chat/issues/5521

**Comment by knrt10** [comment]
On it, will try to fix this

**Comment by geekgonecrazy** [comment]
@knrt10 awesome!  Feel free to request my review on it when you open a PR.  Will gladly help you shape it up and test it.

**Comment by ralfbecker** [comment]
I'll created a provider for [EGroupware OpenID Connect / OAuth server](https://github.com/EGroupware/openid), I'll refactor it for all custom OAuth servers and send a pull request soon.

**Comment by charafsalmi** [comment]
Hi,

Is it possible to do it now ? I mean, use the rest api with a keycloak jwt token ?

Thanks,
