### ISSUE TITLE
Update the ICON for edited messages and remove avatar

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#14107]
![image](https://user-images.githubusercontent.com/1000217/55986675-d5791000-5c54-11e9-8ad3-e20c9746742b.png)

The icon should be just a pencil, without the outer box, and now Avatar, the user info is already on the hoover.

Make the icon red, when edited by someone else.

**Comment by wreiske** [comment]
Can I request that the avatar be shown when edited by someone else? 

Oh wow, you edited your message while I was typing up mine :)

**Comment by Rodriq** [comment]
> ![image](https://user-images.githubusercontent.com/1000217/55986675-d5791000-5c54-11e9-8ad3-e20c9746742b.png)
> 
> The icon should be just a pencil, without the outer box, and now Avatar, the user info is already on the hoover.
> 
> Make the icon red, when edited by someone else.

Can I see into this?

**Comment by engelgabriel** [comment]
this is already done on https://threads-qa.rocket.chat/
