### ISSUE TITLE
Create code walk-through and system flow docs

### ISSUE THREAD

**Issue by sajjadakhter** [RocketChat/Rocket.Chat#1410]
I came across this project, excellent idea but came across few brick walls to be able to contribute/extend for my use. (Am i missing something or there is no doc?)
1. No documentation, i am not supper expert on meteor and feel lost on figuring out how ui parts are working. I wish there was technical architecture. 
2. coffee script :) i saw thread on this.
3. Is there easier way to extend (how can i write plug-ins and possibly what can i do).
   3.1 few features i am looking to extend is how channels, groups gets created for a user and limit what users can they see. 
##

**Comment by howethomas** [comment]
I'm just learning it myself, maybe I will start one by noting what I learn?

**Comment by sajjadakhter** [comment]
couple of notes from my side so far, start with client/routes/router.coffee it gives idea how things getting wiredup.

**Comment by Sing-Li** [comment]
@howethomas That would be awesome!   Please edit this doc 'as you learn' :

https://github.com/RocketChat/Rocket.Chat/wiki/Understanding-the-Code

Anybody can edit and contribute to it.   @sajjadakhter (and any other community member learning the Rocket.Chat code) please feel free to add to it.

When it is completed, one of our doc-pro community member will tidy it up.

**Comment by sajjadakhter** [comment]
is there anyone who is ready to spare sometime to give little overview we can do google hangout etc and i will do the doc.

**Comment by MartinSchoeler** [comment]
This issue is outdated, a lot of things have changed since 2015 closing this issue. Thanks!
