### ISSUE TITLE
Message box does not go back to initial state after sending a message

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#14105]
after sending a message it should go back to initial state:
![image](https://user-images.githubusercontent.com/8591547/55980308-8fc74200-5c6a-11e9-9538-a607175bb2d9.png)

but instead it stays like a message is still there waiting to be sent:
![image](https://user-images.githubusercontent.com/8591547/55980276-8047f900-5c6a-11e9-818d-965544745ecf.png)

**Comment by juanito92** [comment]
My boss got really mad at me and threw a cup of coffee at the secretary today because of this issue, better fix it or we'll sue.
