### ISSUE TITLE
[Regression] message menu missing

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#1411]
> ReferenceError: room is not defined at Object.e.MessageAction.addButton.validation

Linux native app, Linux chromium latest. Demo server

**Comment by Sing-Li** [comment]
Not reproducible on Ubuntu Linux 14.04

Latest chromium Version 45.0.2454.101 Ubuntu 14.04 (64-bit)

@ninja-  said he is on Arch

**Comment by Sing-Li** [comment]
Tested and confirmed fixed.
