### ISSUE TITLE
[BUG] Inappropriate escaping in REST API

### ISSUE THREAD

**Issue by lolimay** [RocketChat/Rocket.Chat#14119]
Hi, I found  a bug when testing `/api/v1/channels.addAll` REST API. The inappropriate escaping like `\"` are too annoying. Can someone fix this problem? See my screenshot below:

![image](https://user-images.githubusercontent.com/32427260/56035707-72bf6b80-5d5d-11e9-844c-7367161a1680.png)

**Comment by wreiske** [comment]
How is this an inappropriate escape?

You have to escape the double quotes because the string starts and ends with quotes. It wouldn't be valid JSON if it wasn't escaped.

**Comment by lolimay** [comment]
> It wouldn't be valid JSON if it wasn't escaped.

Yeah, you are right. There no way to avoid escaping unless we use other symbols (like ``` and `'`) instead.
