### ISSUE TITLE
URL Preview should support 3xx URL redirection

### ISSUE THREAD

**Issue by luozengbin** [RocketChat/Rocket.Chat#1412]
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-oembed/server/server.coffee#L34

302 and 307 with 301 similar behavior, I think the 302 and 307 should also be supported.

302 Moved Temporarily
307 Temporary Redirect

**Comment by sampaiodiego** [comment]
it's a simple task and it could generate preview for even more URLs..

@rodrigok any thoughts?

**Comment by rodrigok** [comment]
@sampaiodiego agreed, can you do that?

**Comment by kakawait** [comment]
Simply update https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-oembed/server/server.coffee#L34 to `302` and `307` status.

**Comment by sampaiodiego** [comment]
closed by #1597
