### ISSUE TITLE
Broadcast channel option hidden 

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Rocket.Chat#14132]
## Howto reproduce
- Try creating a new channel
You'll see the Broadcast channel covered like below
![Broadcast chanel hiden](https://user-images.githubusercontent.com/39289592/56073242-81774400-5d98-11e9-85c5-f708c1feaf64.png)

The scroll bar should be visible so that someone knows there're options above

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
