### ISSUE TITLE
Location Sharing missing

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#14146]
### Description:

We still prompt in browser for location so that the sharing feature will work.  But the button seems to be missing.

Potentially related to dropping the cordova package?

### Steps to reproduce:

1. goto new browser
2. login
3. allow location access
4. goto messagebox
5. Click the + to share location

### Expected behavior:

Option to share location

### Actual behavior:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/51996/56148746-91498080-5f70-11e9-9e12-bc000be137f6.png">

### Server Setup Information:

- Version of Rocket.Chat Server: latest develop (open)
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: true
- NodeJS Version: docker
- MongoDB Version: 4.0

**Comment by tassoevan** [comment]
The settings `MapView_Enabled` and `MapView_GMapsAPIKey` are properly set? Doest the browser support the `navigator.geolocation.watchPosition` API?

**Comment by geekgonecrazy** [comment]
yes to all of the above.  its open.rocket.chat.  I'm using firefox if that helps at all

**Comment by vipulsaraf** [comment]
I am working on this issue...

**Comment by tassoevan** [comment]
@vipulsaraf Can you reproduce it in the latest version?

**Comment by vipulsaraf** [comment]
Yes sure, I will come with a solution as soon as possible...

**Comment by jeanfbrito** [comment]
@tassoevan just found this and tested. It's working. Could we close the issue?
