### ISSUE TITLE
Ability for non-owners to invite users to private rooms

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#1414]
(I searched for this before filing it and didn't find anything identical though a few things related. Apologies if it's redundant.)

Can it be made possible in some way for non-owners to invite users to private rooms? In both Slack (which is what we're moving from) and Mattermost (which we tried as a Slack replacement, but found too buggy to use), it's automatically the case that all members of a private room can invite people. But if this could be enabled by the owner of the room, or globally by the owner of the server, that would definitely be sufficient.

Thanks!
##

**Comment by marceloschmidt** [comment]
Yes, I'll make sure to add this to the channel-settings package I'm developing right now :) Thanks!

**Comment by gwillen** [comment]
Thank you! :-)

**Comment by gwillen** [comment]
Hmmm, this now seems critical for us: The owner of a private channel just accidentally left it. Now nobody can invite him back and nobody can invite anybody else.... this seems like a major bug now, rather than a feature request.

**Comment by richardwlu** [comment]
:+1: This would be helpful!

**Comment by javaning** [comment]
yes, this is reasonable.

**Comment by dbushong** [comment]
A few observations:

1. can't the Admin fix the "the owner left" thing?
1. you can check the box at the intersection of "add-user-to-room" and "user" in Administration > Permissions if that's what you want to allow

**Comment by scottie** [comment]
i see no confirmation that this has been done?? Whats the news? I see some guy saying he is doing it, but then nothing else?
