### ISSUE TITLE
Bug: reacting a message inside a thread from thread panel looses the message

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#14158]
### Steps to reproduce:

1. Open any thread
2. React to a message
3. Message will be removed from the UI

**Comment by ggazzo** [comment]
Do you have more information about that? because I dont think its so "simple" to reproduce

**Comment by rafaelks** [comment]
At least for me, any thread I react to, the message gets removed from the list:

![2019-04-18 11 31 20](https://user-images.githubusercontent.com/551004/56368294-84759880-61cd-11e9-8add-1de84de56bf5.gif)

**Comment by ggazzo** [comment]
@rafaelks could you try again on open.rocket.chat? I think it was solved...thanks :)

**Comment by rafaelks** [comment]
@ggazzo Still happens to me :-(

**Comment by engelgabriel** [comment]
Why is this Blocked ?

**Comment by ggazzo** [comment]
@rodrigok closed by https://github.com/RocketChat/Rocket.Chat/pull/14360
