### ISSUE TITLE
Hide room confirmation shows "undefined" instead of user name (only DM, only via Room Info sidebar)

### ISSUE THREAD

**Issue by BobKnip** [RocketChat/Rocket.Chat#14159]
## My Setup
- Operating System: Windows 10
- App Version: 2.15.1
- Installation type: EXE

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

Hide room confirmation shows "undefined" instead of user name (only DM, only via Room Info sidebar). 

- Does NOT work correctly : Room info (sidebar, right) > "Hide" (button at the bottom): 
'Are you sure you want to hide the discussion with "undefined"?' 
(The result of confirming hiding the room is as expected.) 
This bug only applies to Direct Message rooms. (For Group and Channel, the correct text is shown via room context menu and Room Info sidebar.) 

- DOES work correctly: Room context menu (three dots, left) > "Hide Room" (menu item): 
'Are you sure you want to hide the discussion with "<ACTUAL_NAME>"?' 
(<ACTUAL_NAME> is placeholder; e.g.: "Naomi Mc Nameface".) 

- BTW: These seemingly identical functions have slightly different texts for their options: menu item "Hide Room" and button "Hide". I know the latter is already in context of the "Room Info" sidebar, but you might as well rename the button "Hide Room" for consistency. Also, a new user might think the "Hide" button hides the Room Info sidebar.

### Current Behavior

When confirming hiding a DM room via the Room Info sidebar, "undefined" is shown as the user name.

### Expected Behavior

When confirming hiding a DM room via the Room Info sidebar, the actual user name should be shown.

**Comment by tassoevan** [comment]
@BobKnip I transferred this issue since it looks like a Rocket.Chat server bug. Can you please fill a bug description following this template (https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/.github/ISSUE_TEMPLATE/bug_report.md)?
