### ISSUE TITLE
Timestamp / message group display after long absence

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#1415]
Much like Slack does, Rocket will only display one timestamp / icon for a series of messages by a given user, with the others visible if you hover the messages. But unlike Slack and friends, Rocket will not break apart groups of messages with long times passing between them -- if I say a bunch of things, wait a long time, then say another bunch, it doesn't display a fresh timestamp.

Can Rocket break apart groups of messages in this way, if a long time passes between them?

Thanks!

**Comment by sampaiodiego** [comment]
how much time do you think is good to display a fresh timestamp?

**Comment by gwillen** [comment]
Slack seems to do it somewhere in the 5-10 minutes range, which seems reasonable to me.

**Comment by gwillen** [comment]
Awesome! Thanks!
