### ISSUE TITLE
[BUG] Threads not opening when clicking on desciption or replies button

### ISSUE THREAD

**Issue by knrt10** [RocketChat/Rocket.Chat#14156]
### Description:

This issue is only occurring on `open.rocket.chat` server. It is working fine on the local server for 1.0.0-develop  and also on `threads-qa.rocket.chat`. Problem is on both desktop app or browser. 

### Steps to reproduce:

1. Click on description of threads
2. or click on replies button for thread.

### Expected behavior:

It should open the thread

### Actual behavior:

It is not opening

![gif](https://user-images.githubusercontent.com/24803604/56212128-056e4c00-6077-11e9-88e8-1069f40aad32.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: `open.rocket.chat`
- Operating System: MacOS 
- Browser: Google Chrome, Mozilla Firefox
- Desktop:- MacOS app latest version

**Comment by reetp** [comment]
Occurring on open.rocket.chat

Version 73.0.3683.75 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by reetp** [comment]
Also Firefox 66.0 64 bit  on Xubuntu 16.04

**Comment by Rodriq** [comment]
I have the same issue on
Ubuntu 18.04.2 LTS | 64-bit
**Google Chrome Version 72.0.3626.109**
**Rocket.Chat App**
  And like @knrt10 said, it works well locally.

**Comment by tassoevan** [comment]
@knrt10 Is any error logged on browser's console after clicking?

**Comment by knrt10** [comment]
@tassoevan this is the whole log for web view but this loads on page load. When clicked no log is generated neither on web or desktop

![Screenshot 2019-04-16 at 9 10 26 PM](https://user-images.githubusercontent.com/24803604/56223859-2f7e3900-608c-11e9-9d34-c6cd8c751d71.png)

**Comment by tassoevan** [comment]
I can't reproduce it. Does it happen every time? Does refreshing the page change anything?

**Comment by knrt10** [comment]
Yes, it happen everytime. Refreshing does not change anything. I also cannot understand why is it happening.

**Comment by reetp** [comment]
Still broken in open.rocket.chat from here.

Works in my dev test rig from a few days back

**Comment by wreiske** [comment]
👀

**Comment by tassoevan** [comment]
The `Hide Right Sidebar with Click` preference is interfering here. A patch is coming.
