### ISSUE TITLE
Implement SSO with Restful API 

### ISSUE THREAD

**Issue by baoc75** [RocketChat/Rocket.Chat#14154]
As the documentation mentioned (SAML, oAuth, CAS, LDAP), currently there is no information about implementing SSO with Restful API. So do we have any progress with Restful API?

**Comment by ralfbecker** [comment]
Since about a day Rocket.Chat API accepts login with OAuth access-tokens, if a (custom) OAuth server is configured. That seems to make it in the upcoming 1.0 release, as far as I understand.

**Comment by geekgonecrazy** [comment]
Yes this is now possible to send access token along
