### ISSUE TITLE
Discussion & threads start message does not follow 24/12h clock preference

### ISSUE THREAD

**Issue by MIKI785** [RocketChat/Rocket.Chat#14164]
### Description:

When starting a new discussion or a thread, the timestamp in the original message starting it does not follow the clock format preference (Preferences -> Messages -> Time format).
The same issue appears in the _Threads_ sidebar.

### Steps to reproduce:

1. Set the clock format to 24h
2. Start a thread/discussion
3. Observe the timestamp

### Expected behavior:

The timestamp should follow the same format as the rest.

### Actual behavior:

The timestamp is always shown in a 12h format.
![image](https://user-images.githubusercontent.com/15911029/56275105-f7144480-60f7-11e9-9daa-ee8eba24ad2a.png)
![image](https://user-images.githubusercontent.com/15911029/56275277-570aeb00-60f8-11e9-917f-d070806b664a.png)
![image](https://user-images.githubusercontent.com/15911029/56275321-6853f780-60f8-11e9-9a32-f61b7884f454.png)

### Server Setup Information:

Taken from the open.rocket.chat server.

**Comment by ggazzo** [comment]
closed by #14177
