### ISSUE TITLE
Migrate to new server

### ISSUE THREAD

**Issue by irfanjunaid** [RocketChat/Rocket.Chat#14165]
**Description:**
Trying to migrate the server from old(2 gb / 1 cpu) to new(4 gb / 2 cpu). But unable to migrate data using mongodump and mongorestore as mentioned on #4297 . Also, tried using the _snap run rocketchat-server.backupdb_ at https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#snaps

**Steps to reproduce:**
- On the old server: mongodump ~/backup
- Archive the dir: tar czf mongodump.tar.gz backup
- Upload the tar to new server
- Install the rocketchat and all components without rocketchat not running
- Extract the dump: tar xzf mongodump.tar.gz
- Restore the dump: mongorestore backup
- Start the rocketchat server
- Access the site

**Actual behavior:**
Starts the setup screen from the beginning with no data from old backup

**Server Setup Information:**
Version of Rocket.Chat Server: 0.74.3
Operating System: Ubuntu server 18.04 LTS
Deployment Method: [Manual tar installation](https://rocket.chat/docs/installation/manual-installation/ubuntu/)
Number of Running Instances: 1
NodeJS Version: 8.11.3
MongoDB Version: 3.6.12

**Comment by reetp** [comment]
Are the Rocket versions identical? If not then make sure they are.

I'm not sure what a snap backup install has to do with it as you are using a tar install.

What do your rocketchat logs tell you?

**Comment by irfanjunaid** [comment]
Hey @reetp Yes, both the versions are identical. 

> I'm not sure what a snap backup install has to do with it as you are using a tar install.

My colleague initially used ubuntu snaps to install the server. I am now preferring manual method for greater control. I used the mongodump tool from snaps installed location and manually installed using apt. DB is backing up and restoring fine...

> What do your rocketchat logs tell you?

I tried searching the /var/logs location for log files but not successful. Though I never encountered any errors during DB backup and restore...

**Comment by irfanjunaid** [comment]
Alright, managed to extract the logs from journalctl:


systemd[1]: Started The Rocket.Chat server.
rocketchat[24525]: Updating process.env.MAIL_URL
rocketchat[24525]: LocalStore: store created at
rocketchat[24525]: LocalStore: store created at
rocketchat[24525]: LocalStore: store created at
rocketchat[24525]: Setting default file store to GridFS
rocketchat[24525]: Starting Email Intercepter...
rocketchat[24525]: Warning: connect.session() MemoryStore is not
rocketchat[24525]: designed for a production environment, as it will leak
rocketchat[24525]: memory, and will not scale past a single process.
rocketchat[24525]: ufs: temp directory created at "/tmp/ufs"
rocketchat[24525]: Updating process.env.MAIL_URL
rocketchat[24525]: Using GridFS for custom sounds storage
rocketchat[24525]: Using GridFS for custom emoji storage
rocketchat[24525]: Loaded the Apps Framework and loaded a total of 0 Apps!
rocketchat[24525]: ➔ System ➔ startup
rocketchat[24525]: ➔ +---------------------------------------------------+
rocketchat[24525]: ➔ |                   SERVER RUNNING                  |
rocketchat[24525]: ➔ +---------------------------------------------------+
rocketchat[24525]: ➔ |                                                   |
rocketchat[24525]: ➔ |  Rocket.Chat Version: 0.74.3                      |
rocketchat[24525]: ➔ |       NodeJS Version: 8.11.3 - x64                |
rocketchat[24525]: ➔ |             Platform: linux                       |
rocketchat[24525]: ➔ |         Process Port: 3000                        |
rocketchat[24525]: ➔ |             Site URL: https://chat.domain.com/    |
rocketchat[24525]: ➔ |     ReplicaSet OpLog: Disabled                    |
rocketchat[24525]: ➔ |          Commit Hash: 202a465f1c                  |
rocketchat[24525]: ➔ |        Commit Branch: HEAD                        |
rocketchat[24525]: ➔ |                                                   |
rocketchat[24525]: ➔ +---------------------------------------------------+


This s right after doing mongorestore. I am pretty sure that I am missing a simple thing. Kindly help!

**Comment by geekgonecrazy** [comment]
if you are moving from snap make sure your MONGO_URL is pointing to the DB name `parties` as thats what the DB name is in snaps.

To avoid this you can:
```
mv dump/parties dump/rocketchat
```
then mongorestore

**Comment by irfanjunaid** [comment]
@geekgonecrazy  This was it!

In https://rocket.chat/docs/installation/manual-installation/ubuntu/#configure-the-rocketchat-service

We need to edit **rocketchat** to **parties** in the **MONGO_URL**

Thanks for the assist!
