### ISSUE TITLE
Will you offer a paid hosting service?

### ISSUE THREAD

**Issue by alexgleason** [RocketChat/Rocket.Chat#1417]
Hello! My team just tried out your demo and we really liked it, but we don't currently have the resources to switch from a third-party hosted service like Slack. I'm curious to know if you have any plans to offer RocketChat as a hosted service.

If we can use it, it would encourage us (or at least me) to contribute to its development, which is something I'm excited about.

Thanks!

**Comment by Sing-Li** [comment]
@alexgleason Thanks for the query!  

YES.  It is in early access right now.  Please direct message or email gabriel.engel.rocket.team for an instant trial.

Looking forward to your development contributions.  TA

**Comment by marceloschmidt** [comment]
You can also reach us on support@rocket.chat.
