### ISSUE TITLE
Floating point in fields is not working

### ISSUE THREAD

**Issue by eloo-at-abi** [RocketChat/Rocket.Chat#14172]
### Description:
Hi,
i've discovered a bug using incoming webhooks.
The bug occurs when a field with an value of type double is send. Then an error is thrown.
With wrapping the value in quotes it works, but the problem is that my system is not wrapping it. Also it works in Slack without quotes.

### Steps to reproduce:

1. Create incoming webhook without script
2. Send message to incoming webhook with the following body
```
{
    "attachments": [
        {
            "color": "#D63232",
            "fallback": "[Alerting] My Alert",
            "fields": [
                {
                    "short": true,
                    "title": "Some value",
                    "value": 1.8503078660265208
                }
            ],
            "ts": 1555507262
        }
    ],
    "parse": "full"
}
```
3. Send the same body with quotes around the numeric value of `value` and you see it working.

### Expected behavior:

My alert is shown in RocketChat as expected

### Actual behavior:

Then the following response will received and not message is coming up in the channel
```
{
    "success": false,
    "error": "Match error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation in field value"
}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 4.0.8

**Comment by eloo-at-abi** [comment]
Looks like a script like this would fix the issue
```
/* exported Script */
/* globals console, _, s */

/** Global Helpers
 *
 * console - A normal console instance
 * _       - An underscore instance
 * s       - An underscore string instance
 */

class Script {
    /**
     * @params {object} request
     */
    process_incoming_request({ request }) {
      var content = request.content
      if(content.attachments)
      {
          var fields = content.attachments[0].fields
        for(var i in fields){
          fields[i]['value'] = fields[i]['value'].toString()
        }
      }
      return {
          content: request.content
        };
  
    }
  }
```

so maybe a simple toString() is missing somewhere

**Comment by ros-calumgilchrist** [comment]
Maybe this should be another issue, but I see similar issues with large numbers in the value field:
For example: `28363980800` errors but `28363980` does not.
