### ISSUE TITLE
How to build or integrate with a blog?

### ISSUE THREAD

**Issue by internalG** [RocketChat/Rocket.Chat#14183]
rocket.chat is amazing so we decide to use it as the key real time communication system in our site. And we need to build the blog system for users. rocket.chat is based on Meteor, is it good to build the blog on the same Meteor in rocket.chat? That avoids complex user authentication but may be limited to rocket.chat functions. If we build the blog on separated Meteor or Django, what's the best way to make the user accounts transparent in both chat and blog?

**Comment by reetp** [comment]
@rocket-cat close

This is a support question rather than a bug in Rocket.Chat

Please ask in the forums or open.rocket.chat
