### ISSUE TITLE
LDAP Login broken in 1.0.0-rc.3

### ISSUE THREAD

**Issue by himpich** [RocketChat/Rocket.Chat#14187]
### Description:

I updated our Rocketchat from rc.2 to rc.3, now the LDAP Logins aren't working anymore

related logentries:
```LDAP ➔ Search.info Searching user redacted@net-lab.net 
LDAP ➔ Search.info Search result count 1 
LDAP ➔ Auth.info Authenticating cn\=sh@redacted.net\,ou\=users\,dc\=gkh\,dc\=com 
LDAP ➔ Auth.info Not authenticated cn\=sh@redacted.net\,ou\=users\,dc\=gkh\,dc\=com 
LDAPHandler ➔ info Wrong password for sh@redacted.net
```
It worked fine in rc.2, my password is correct, other users aren't able to login, too.

I guess the quoting of the Authentication DN is wrong (shouldn't quote , or =) and it is related to https://github.com/RocketChat/Rocket.Chat/pull/14160

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-rc.3
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 3.2.9

**Comment by Venomen** [comment]
Yes, this is major bug, rolling back to rc.2

**Comment by himpich** [comment]
> Yes, this is major bug, rolling back to rc.2

unfortunatly there is a migration in rc.3, so no rollback possible without database restore and therefore dataloss

**Comment by Venomen** [comment]
> > Yes, this is major bug, rolling back to rc.2
> 
> unfortunatly there is a migration in rc.3, so no rollback possible without database restore and therefore dataloss

Yeap, thats why I'm always making snapshot/checkpoint etc.

**Comment by himpich** [comment]
FYI: Commenting out the Line `		dn = ldapEscape.dn`${ dn }`;
` of https://github.com/RocketChat/Rocket.Chat/pull/14160 fixed my problems, I managed to get a self-build image running. No issues with the other ldap changes of the PR so far

**Comment by erhan-** [comment]
> 
> 
> FYI: Commenting out the Line ` dn = ldapEscape.dn`${ dn }`; ` of #14160 fixed my problems, I managed to get a self-build image running. No issues with the other ldap changes of the PR so far

Well that reverts the input sanitation in the username during LDAP login but you also put yourself at risk for LDAP injections.

**Comment by himpich** [comment]
> > FYI: Commenting out the Line ` dn = ldapEscape.dn`${ dn }`; ` of #14160 fixed my problems, I managed to get a self-build image running. No issues with the other ldap changes of the PR so far
> 
> Well that reverts the input sanitation in the username during LDAP login but you also put yourself at risk for LDAP injections.

I know. I just wanted to state that all other sanitze changes (there are a few more other "escapes") don't cause a problem in my installation, it's just this line.

**Comment by erhan-** [comment]
Forget what I said. A user can not change the `dn` attribute anyway. The only risky thing might be the unsanitized username. If it still works with the escaping, it's good imho.

**Comment by DarkRider1768** [comment]
Experiencing the same problem. Willing to do anything, up to and including ritualistic animal sacrifice, to assist in resolving this issue. Let me know if there is any information I can provide to help.

**Comment by engelgabriel** [comment]
Guys, can you help us look into this?

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/14234
