### ISSUE TITLE
I can't update Rocket MacOS Mojave 10.14.4

### ISSUE THREAD

**Issue by ppraksa** [RocketChat/Rocket.Chat#14193]
![Zrzut ekranu 2019-04-19 o 09 53 02](https://user-images.githubusercontent.com/14870997/56413827-0c6ca880-6289-11e9-9c7f-b267603de85a.png)

While clicking on the 'install update' nothing is happening

**Comment by lorek123** [comment]
Wrong repo, post the issue here https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by reetp** [comment]
@rocket-close
Closing as duplicate and wrong repo.
