### ISSUE TITLE
Internal Server Error when signing as anonymous

### ISSUE THREAD

**Issue by online0227** [RocketChat/Rocket.Chat#14198]
### Description:

Shows internal server error and anonymous doesn't work when it is requested. Pressing button reacts nothing but shows the error.

On console, it shows 2 kinds of exception:
**1.** 
I20190419-17:01:42.982(0)? Exception in callback of async function: TypeError: Data must be a string or a buffer
I20190419-17:01:42.983(0)?     at Hash.update (crypto.js:99:16)
I20190419-17:01:42.984(0)?     at AccountsServer._hashLoginToken (packages/accounts-base/accounts_server.js:782:1
0)
I20190419-17:01:42.984(0)?     at Users.findOneByIdAndLoginToken (app/models/server/models/Users.js:392:57)
I20190419-17:01:42.985(0)?     at isUserAuthenticated (server/routes/avatar/utils.js:45:26)
I20190419-17:01:42.986(0)?     at userCanAccessAvatar (server/routes/avatar/utils.js:55:26)
I20190419-17:01:42.986(0)?     at Meteor.bindEnvironment (server/routes/avatar/middlewares/auth.js:7:7)
I20190419-17:01:42.986(0)?     at runWithEnvironment (packages/meteor.js:1356:24)
I20190419-17:01:42.986(0)?     at packages/meteor.js:1369:14
I20190419-17:01:42.986(0)?     at /home/myspace/.meteor/packages/promise/.0.11.2.1rxqxdq.d4m4g++os+web.browse
r+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

**2.**
I20190419-17:01:48.122(0)? Exception while invoking method 'registerUser' TypeError: Cannot read property 'facebo
ok' of undefined
I20190419-17:01:48.122(0)?     at getAvatarSuggestionForUser (app/lib/server/functions/getAvatarSuggestionForUser
.js:12:20)
I20190419-17:01:48.123(0)?     at AccountsServer.<anonymous> (server/lib/accounts.js:221:29)
I20190419-17:01:48.123(0)?     at executeBound (/home/myspace/v1rc3/Rocket.Chat-1.0.0-rc.3/node_modules/under
score/underscore.js:762:67)
I20190419-17:01:48.123(0)?     at AccountsServer.bound [as insertUserDoc] (/home/myspace/v1rc3/Rocket.Chat-1.
0.0-rc.3/node_modules/underscore/underscore.js:793:14)
I20190419-17:01:48.123(0)?     at MethodInvocation.registerUser (server/methods/registerUser.js:22:28)
I20190419-17:01:48.123(0)?     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:7
3:34)
I20190419-17:01:48.124(0)?     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring
.js:2731:30)
I20190419-17:01:48.124(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20190419-17:01:48.124(0)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:
719:19)
I20190419-17:01:48.124(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190419-17:01:48.124(0)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:
717:46)
I20190419-17:01:48.124(0)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190419-17:01:48.124(0)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190419-17:01:48.125(0)?     at new Promise (<anonymous>)
I20190419-17:01:48.125(0)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190419-17:01:48.125(0)?     at packages/ddp-server/livedata_server.js:559:43

### Steps to reproduce:

I just exactly followed the instruction at:
https://rocket.chat/docs/developer-guides/quick-start/

And those exception errors will be generated whenever you press start chat anonymously button, which react nothing after pressing the button.

### Expected behavior:

Anonymous should be able to register and start chat.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0 and 1.0rc3
- Operating System:  Ubuntu 18.04 LTS using Google Cloud platform.
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by MarcosSpessatto** [comment]
Hey @online0227, I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14301) solved this issue. Can you please test with the 1.0.2 version? Please let me know if the problem persists.

**Comment by online0227** [comment]
tested 1.0.3 downloaded from https://github.com/RocketChat/Rocket.Chat/releases instead of 1.0.2

Not working. it doesn't say about internal error, but once sign up as anonymous, chat channels are all invisible.

**Comment by online0227** [comment]
@MarcosSpessatto test both 1.0.3 and 1.0.2 downloaded from https://github.com/RocketChat/Rocket.Chat/releases 

For 1.0.2 it works like you said. For 1.0.3 it doesn't work, explained above.
