### ISSUE TITLE
[BUG] Custom avatar on integrations not respected

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#14190]
### Description:

Incoming hook integrations are not using the specified custom avatar for posting of messages, and are instead using the default rocket.cat avatar. This issue is related to #14038 which seems to have been already corrected.

### Steps to reproduce:

1. Deploy latest docker develop image.
2. Create an incoming webhook integration. Set a custom avatar in place of the default.
3. Trigger the webhook.
4. See that the custom avatar is being ignored.

### Expected behavior:

The specified avatar should be used, which was the original behavior.

### Actual behavior:

Rocket.cat avatar shows up.

### Rocket.Chat

|                 Version | 1.0.0-develop                                             |
| ----------------------: | --------------------------------------------------------- |
|     Apps Engine Version | 1.4.2                                                     |
|      Database Migration | 141                                                       |
| Database Migration Date | Thu Apr 18 2019 05:53:51 GMT-0500 (Central Daylight Time) |
|            Installed at | Mon Jan 29 2018 16:02:11 GMT-0600 (Central Standard Time) |
|                  Uptime | 8 hours, 48 seconds                                       |
|           Deployment ID | JAELT9iyADPbKEGbG                                         |
|                     PID | 1                                                         |
|       Running Instances | 1                                                         |
|                   OpLog | Enabled                                                   |

### Commit

|    Hash | 4d160bf9dc11dfb0418579c975c33ced3ef311db                |
| ------: | ------------------------------------------------------- |
|    Date | Wed Apr 17 18:29:59 2019 -0300                          |
|  Branch | develop                                                 |
|     Tag | 0.74.2                                                  |
|  Author | Pierre H. Lehnen                                        |
| Subject | Auto remove SAML certificate header and footer (#14179) |

**Comment by d-gubert** [comment]
Hi @bkraul! I believe this issue has been fixed by [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14184), so it should be available on the next RC.

Thanks for contributing and please reopen the issue if this problem is not solved :)

**Comment by bkraul** [comment]
@d-gubert You are correct. This appears solved in the latest develop build based on commit ea58137 . Thank you!
