### ISSUE TITLE
I can`t send personal message / notification from Rocket.Chat App to rc.SDK client

### ISSUE THREAD

**Issue by alnikitich** [RocketChat/Rocket.Chat#14194]
I try to send a personal message from Rocket.Chat App (https://rocket.chat/docs/developer-guides/developing-apps/getting-started/) to RC user to RC.SDK client (https://github.com/RocketChat/Rocket.Chat.js.SDK), but I can`t find a way for it.

First way: in IModifyCreator I can`t set destination user.

Second way: RC.SDK client can`t receive message created by INotifier

What the best way to send a message from RC App to Node.js client

**Comment by MarcosSpessatto** [comment]
@d-gubert :top:

**Comment by d-gubert** [comment]
Hello @alnikitich !

In Rocket.Chat, every conversation happens inside a room - that means you don't send a message *directly* to a user, but rather to a room with the type `direct` which members are only the two users involved.

You can see an example of such communication here https://github.com/marceloschmidt/koko/blob/master/lib/helpers.ts#L31 (kudos to @marceloschmidt !)

As for the SDK, I don't know about the specifics, but the approach would be the same - find a room with the user and send a message there.

**Comment by d-gubert** [comment]
I'll close this issue for now.

If you find any problem related to this, feel free to reopen it :)
