### ISSUE TITLE
.wav files do not play in attachment previews

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14197]
### Description:

Uploaded .wav files do not seem to play when displayed as attachments. They play fine in the upload dialog, but not in the message attachment. 

### Steps to reproduce:

1. Upload a .wav file 
2. Try to click the play button

### Expected behavior:

Play the file

### Actual behavior:
The file isn't playable. Looks like the type="audio/wave" should be "audio/wav".

The file content-type may need to also send "audio/wav" in the file response, not audio/wave...
![image](https://user-images.githubusercontent.com/6295044/56434671-8447cc80-62a3-11e9-9eb4-41b7b933198a.png)

![image](https://user-images.githubusercontent.com/6295044/56434487-cb818d80-62a2-11e9-8819-9a28cbbb7aba.png)

![image](https://user-images.githubusercontent.com/6295044/56434479-c3295280-62a2-11e9-8313-d649759b9d98.png)

### Server Setup Information:

open.rocket.chat

**Comment by wreiske** [comment]
Changing the audio_type in the database to "audio/wav" fixes this.

![wave](https://user-images.githubusercontent.com/6295044/56436295-4f3e7880-62a9-11e9-91bf-1ad864474ff6.gif)

**Comment by wreiske** [comment]
The audio preview should take the actual content type of the file being previewed.. Currently, it is hardcoded to audio/wav.

![image](https://user-images.githubusercontent.com/6295044/56445869-6beca780-62cd-11e9-8fcb-c321802e20a5.png)

**Comment by knrt10** [comment]
@wreiske nice. Can you please tell which application are you using to debug the database collections on the above gif. Thanks

**Comment by wreiske** [comment]
> @wreiske nice. Can you please tell which application are you using to debug the database collections on the above gif. Thanks

https://www.mongodb.com/products/compass

**Comment by knrt10** [comment]
Thanks a lot.

**Comment by tassoevan** [comment]
Weird. Both `audio/wav` and `audio/wave` are valid MIME types for *.wav files.
