### ISSUE TITLE
"Invalid user" error when terminating SAML session on logout

### ISSUE THREAD

**Issue by unixtam** [RocketChat/Rocket.Chat#14200]
### Description:

After logging out via SAML, a red error notification pops up in the upper right corner of the page reading "Invalid User" if the SAML session is configured to be terminated on logout.

### Steps to reproduce:

1. set up SAML
2. make sure "Logout Behaviour" is set to "Terminate SAML-Session"
3. log in a SAML user
4. log out the SAML user
5. see error pop up on the login screen

### Server Setup Information:
- Version of Rocket.Chat Server: issue present both in 0.74.3 and the current develop branch.

**Comment by ngulden** [comment]
I have the same behavior und used Rocket.Chat 1.0.2 Docker image.

**Comment by cb3inco** [comment]
Same issue here.

**Comment by cb3inco** [comment]
Another Log item: Exception in callback of async function: { Error: [Unable to Validate Logout Request]     at app/meteor-accounts-saml/server/saml_server.js:356:14     at app/meteor-accounts-saml/server/saml_utils.js:365:11     at InflateRaw.onEnd (zlib.js:131:5)     at emitNone (events.js:111:20)     at InflateRaw.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   isClientSafe: true,   error: 'Unable to Validate Logout Request',   reason: undefined,   details: undefined,   message: '[Unable to Validate Logout Request]',   errorType: 'Meteor.Error' }

**Comment by cb3inco** [comment]
Interestingly if I switch to the setting: Only logout from Rocket.Chat - the error goes away.

**Comment by Hudell** [comment]
Related: #14881
