### ISSUE TITLE
Cannot return to original comment from 'Reply'

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#14218]
Rocket v1.0.0-rc3

Following the bug and patch here https://github.com/RocketChat/Rocket.Chat/issues/14156

I tested commenting on a Reply.

I noticed the box now opens to the right as expected, but the main conversation jumps down to the latest message.

There is then no direct route back to the original comment for reference (I found I had wanted to read some other things from around the time of the original response and to read other comments below that were not part of the reply)

It was very frustrating to have to scroll back up to find the original comment.

I then discovered if you click the Threads icon and go to the particular thread there is a 'Jump To Message' link. That should be included in the original reply box.

**Comment by reetp** [comment]
There is no Avatar next to the original Thread link so you have no idea who posted the message. There is no real context.

It would make more sense when you click the thread link in the main pane for the main pane to go up to the original thread message when it opens the right 'Thread' hand pane (I presume the reason it doesn't is on mobile it opens into the thread). So the main pane actually does 'Jump to Message'. You can't Jump to Message from the Thread pane, but if you show all threads, and find the one you want you then can Jump to Message.

You can see some of this here:

https://open.rocket.chat/file-upload/wyd42u79bmyApBrP6/RocketThreads-1-2019-05-01_11.11.09.mp4

Also, if I reply to a Reply in the thread, it just adds it to the bottom of the thread, not to the Reply. So there is no 'thread in thread'

There used to be a click down so a long reply could be viewed in the main pane but now you have click and open the right hand pane to see it:

![Screenshot_2019-05-01_11-23-18](https://user-images.githubusercontent.com/3800384/57012003-9b23e280-6c04-11e9-9785-610c84fb71aa.png)

**Comment by ggazzo** [comment]
@reetp please check again (on open.rocket.chat or develop branch) if you can't find the 'jump message'
> There is then no direct route back to the original comment for reference (I found I had wanted to read some other things from around the time of the original response and to read other comments below that were not part of the reply)

**Comment by reetp** [comment]
> @reetp please check again (on open.rocket.chat or develop branch) if you can't find the 'jump message'


Yup I can see it now thanks :-)

One tiny point - I notice when you do click jump to message it very nicely illuminates the original messages in yellow for about 2 milliseconds...... and you lose sight of it.

Could that be made like a second or two seconds to give you eyes a chance to focus on it?

**Comment by ggazzo** [comment]
thanks @reetp I will review that time
