### ISSUE TITLE
New server bug layout

### ISSUE THREAD

**Issue by 1RF17** [RocketChat/Rocket.Chat#14212]
Hello,
I created a new cloud server in the silver plan, to do some tests and check the features for using Rocket.chat in my company.
But after running it, the layout came out like this:

`https://photos.app.goo.gl/FVMd5FTPwkeHv2Tt8`

Is this normal? All the videos and photos I saw of the product were not that way. I know I can change this in the settings, but I could not find a nice layout by doing this "manually".

**Comment by MIKI785** [comment]
Did you try restarting the server? I think there was an issue with the styling not being loaded correctly on the first start of the server.

**Comment by 1RF17** [comment]
Yes, I just rebooted now. Same problem yet. Another image of how it is:

`https://photos.app.goo.gl/WRwcAr6qq1aLU82H7`

**Comment by d-gubert** [comment]
Apologies, I mistakenly closed the issue 😬

**Comment by ggazzo** [comment]
@1RF17 could you send me a message on https://open.rocket.chat/direct/guilherme.gazzo ? I could check your instance, and get some "private" information :)

**Comment by 1RF17** [comment]
Ok, @ggazzo , I sent a message there

**Comment by d-gubert** [comment]
Hey @1RF17 could you comment the solution here for anyone who might have the same problem in the future? Thanks!

**Comment by 1RF17** [comment]
@d-gubert yes, of course:

@Ggazzo restarted my instance and resolved the issue. 

But this problem was only happening in my computer, in the other computers of my company everything was normal. I had cleared cache, cookie and history and nothing had advanced. Just rebooting the instance solved.
