### ISSUE TITLE
login with Meteor Accounts of another meteor custom app

### ISSUE THREAD

**Issue by babnik63** [RocketChat/Rocket.Chat#1422]
Is there any way to login to rocket chat by help of another meteor app account provider?
I have a web-app with lots of users. so I'm going to deploy rocket chat on that server and I need to give my custom app users access to Rocket Chat app. can you give me some guidelines?

**Comment by geekgonecrazy** [comment]
There may be some way to do this with a meteor package.  But oauth seems to be the best way to do this.

**Comment by engelgabriel** [comment]
If you are sharing the same DB, all you need to do is to make sure that your users get the property `role` added to them when they are created.

Also, you need to share the Meteor Login State Between Subdomains:

https://kadira.io/blog/meteor/sharing-meteor-login-state-between-sub-domains

**Comment by harish-myaccount** [comment]
I am using kadira's login state package.
We are supposed to configure domain and cookie name in settings.json.
But rocket chat doesn't have settings.json
**Where does rocket chat pick Meteor.settings.public from?**
If I can add domain,cookie name to Meteor.settings.public login-state package can handle rest.

My other app is storing the cookie as described in above blog post.But rocket chat is not reading it.
My apps are running at 

1. myapp.domain.com 

1. chat.domain.com --> rocket chat

**Comment by harish-myaccount** [comment]
I tried with creating new settings.json file and passing it to meteor run
meteor --settings settings.json

Didn't work
