### ISSUE TITLE
Outgoing webhook always returns error ECONNREFUSED

### ISSUE THREAD

**Issue by apazureck** [RocketChat/Rocket.Chat#14228]
Hi,

I am trying to call a method on my asp.net core controller using an outgoing webhook in rocket chat. When I call my endpoint with postman I get the intended result. When I try calling it using the outgoing webhook I always get the response ECONNREFUSED.

I ran fiddler to see, what acutally goes out, but it seems there is nothing sent out by Rocket Chat at all. My postman request shows up as expected. My server log also does not register any incoming request.

I am using the docker image from docker hub with the latest mongo db, as otherwise I always got an error that a mongo db function is missing. I am running everything on a windows 10 machine. The Rocket Chat Version is 0.74.3.

Plus a long google search did not result in any new insights on my problem.

Can you help me? What am I doing wrong? Let me know, if you need any more information.

Here is my request and response object:
```json
{
    "request": {
        "url": "https://localhost:5001/chat/RocketChatInput",
        "headers": {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36",
            "Content-Type": "application/json",
            "Accept": "*/*"
        },
        "method": "POST",
        "data": {
            "data": {
                "token": "yA3vdmJb8H4EwL6wwHjCXvSK",
                "bot": false,
                "trigger_word": "-todo",
                "channel_id": "GENERAL",
                "channel_name": "general",
                "message_id": "cemrra98y3xsQFRHd",
                "timestamp": "2019-04-23T22:20:40.502Z",
                "user_id": "8GArp8f4iSKZxYD3M",
                "user_name": "pazureck",
                "text": "-todo @pazureck: Third test until tomorrow "
            }
        }
    },
    "response": {
        "error": {
            "code": "ECONNREFUSED",
            "errno": "ECONNREFUSED",
            "syscall": "connect",
            "address": "127.0.0.1",
            "port": 5001
        },
        "headers": {}
    }
}
```

Thanks and best regards

**Comment by d-gubert** [comment]
Hello @apazureck !

You mentioned you are using a docker image. By default, your container runs in an isolated network and is not able to communicate with other local addresses on your machine, so that is probably why you can successfully make your request with Postman but Rocket.Chat fails.

In Unix systems you can pass the flag `--net=host` to the docker run command and then your container would share the host's network, so RC would be able to send a request to that address, but I'm not so sure how this works on Windows.

Maybe [this page](https://docs.docker.com/docker-for-windows/networking/) can help you with your case? :)

**Comment by apazureck** [comment]
Hi @d-gubert,

Thank you for your quick reply. Sadly the `--net=host` only works for linux. I have to use Docker Toolbox for windows, as I cannot install the docker for windows due to a "typo in the installer" preventing it from running on my totally fine windows 10 installation.

In docker toolbox I have virtualbox doing the network stuff. It also creates networks. When I open RC on my browser it shows me the IP `192.168.99.100` and I see a new network adapter fo virtualbox in my windows settings with fix ip `192.168.99.1`. But I still cannot access my webservice (timeout), but I think this is a windows issue with trusted networks.

Thanks for the hint, as I am new to docker etc. I did not know where to start looking for this issue. I'll post my solution here as soon as everything is working.

**Comment by echantigny** [comment]
@apazureck 

Hi Andreas,

I know this issue is getting a bit old, but I'm having the exact same problem, google got me here, and can't really figure it out either.  Did you ever manage to get it working?

**Comment by apazureck** [comment]
No, sorry. It is too far in the past. I think I solved it using a custom RocketChat app and the http client coming with it, as I needed the app anyway.

If I could guess with about one more year of working with ASP.NET core I might guess that a confusing error always tangles some issue with CORS. And when I Look in my [Startup.cs](https://github.com/apazureck/rocketchattasks/blob/master/RocketChatToDoServer/Startup.cs), I might see it similarities. I recently hat that issue (directly in my browser with an angular app).

You have to 

Startup.cs:
```csharp
Startup {
    public void ConfigureServices(IServiceCollection services)
    {
        //...
        services.AddCors();
        //...
    }

    public void Configure(IApplicationBuilder app)
    {
            app.UseCors(builder => builder.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin());
            // ...
    }
```

Maybe you can give this a shot.

**Comment by echantigny** [comment]
@apazureck 

Thanks for your quick answer.  I was actually able to figure something out playing around with docker containers network aliases.  I was able to create an alias for my container and then use https://myalias/pathtowebhook in Rocketchat to send the data.  Of course, both containers need to share the same network.

I hope this helps anyone stumbling on this thread.

Thanks again
