### ISSUE TITLE
[DocumentDB] MongoError: namespace name generated from index name is too long

### ISSUE THREAD

**Issue by Wille007** [RocketChat/Rocket.Chat#14230]
I am using Amazon DocumentDB to instead of MongoDB, and then use docker-compose to deploy. finally I found one error below, and I didn't found any solutions:

when I run docker-compose up, then I met this kind of error.
but I found that in the DocumentDB, threre is rocketchat collections there, but there is no users in users collection. that means connection is no problem  right?.  
I tried local MongoDB and third VM MongoDB, there is no problem. it means not the original mongo problem. but it happened in DocumentDB. 
someone plz help me.

rocketchat_A3_1  | Warning: connect.session() MemoryStore is not
rocketchat_A3_1  | designed for a production environment, as it will leak
rocketchat_A3_1  | memory, and will not scale past a single process.
rocketchat_A4_1  | Warning: connect.session() MemoryStore is not
rocketchat_A4_1  | designed for a production environment, as it will leak
rocketchat_A4_1  | memory, and will not scale past a single process.
rocketchat_A3_1  | Error creating index: webdav_accounts -> { user_id: 1, server_url: 1, username: 1, name: 1 } { unique: 1 } { MongoError: namespace name generated from index name is too long
rocketchat_A3_1  |     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
rocketchat_A3_1  |     at authenticateStragglers (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:504:16)
rocketchat_A3_1  |     at Connection.messageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:540:5)
rocketchat_A3_1  |     at emitMessageHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:310:10)
rocketchat_A3_1  |     at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:453:17)
rocketchat_A3_1  |     at emitOne (events.js:116:13)
rocketchat_A3_1  |     at TLSSocket.emit (events.js:211:7)
rocketchat_A3_1  |     at addChunk (_stream_readable.js:263:12)
rocketchat_A3_1  |     at readableAddChunk (_stream_readable.js:250:11)
rocketchat_A3_1  |     at TLSSocket.Readable.push (_stream_readable.js:208:10)
rocketchat_A3_1  |     at TLSWrap.onread (net.js:597:20)
rocketchat_A3_1  |   ok: 0,
rocketchat_A3_1  |   errmsg: 'namespace name generated from index name is too long',
rocketchat_A3_1  |   code: 67,
rocketchat_A3_1  |   name: 'MongoError',
rocketchat_A3_1  |   [Symbol(mongoErrorContextSymbol)]: {} }

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: ubuntu
- Deployment Method: docker (docker-compose)
- Number of Running Instances: 4
- DB Replicaset Oplog:  no
- NodeJS Version: ---
- MongoDB Version: DocumentDB(include MongoDB 3.6)

this is my docker-compose.yml MONGO part below:

  rocketchat_A3:
    image: rocketchat/rocket.chat:latest
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://username:password@hhchat-cluster.cluster-clolyyuizy0t.us-east-2.docdb.amazonaws.com:27017/rocketchat?ssl=true&replicaSet=rs0
      - MONGO_OPTIONS={"sslCert":"/home/ubuntu/rds-combined-ca-bundle.pem"}
      - MAIL_URL=smtp://smtp.email
    #depends_on:
     # - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

### Relevant logs:

**Comment by geekgonecrazy** [comment]
Rocket.Chat is not compatible with documentDB.  DocumentDB is not mongodb. It may implement some of its query set but its not going to work with Rocket.Chat

**Comment by Wille007** [comment]
@geekgonecrazy , thanks!
