### ISSUE TITLE
Your application is crashing. Waiting for file change.

### ISSUE THREAD

**Issue by Jessting** [RocketChat/Rocket.Chat#14256]
First, I git clone . When I run  meteor, I'm prompted for an error : "Your application is crashing. Waiting for file change.".  My operating environment is Xcode 10.2.

**Comment by knrt10** [comment]
@Jessting would you please full description with issue template so that we can help you better, otherwise, it will be closed. Thanks.

**Comment by Jessting** [comment]
meteor npm start

> Rocket.Chat@1.0.0-develop start /Users/fdc/APP/git/Rocket.Chat
> meteor

[[[[[ ~/APP/git/Rocket.Chat ]]]]]             

=> Started proxy.                             
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
 - postcss@7.0.6 installed, postcss@^6.0.22 needed
 - postcss-load-config@2.0.0 installed, postcss-load-config@^1.2.0 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

=> Started MongoDB.                           
W20190426-15:54:37.681(8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20190426-15:54:37.742(8)? (STDERR) While this implementation will work correctly, it is known to be
W20190426-15:54:37.742(8)? (STDERR) approximately three times slower than the native implementation.
W20190426-15:54:37.742(8)? (STDERR) In order to use the native implementation instead, run
W20190426-15:54:37.742(8)? (STDERR) 
W20190426-15:54:37.742(8)? (STDERR)   meteor npm install --save bcrypt
W20190426-15:54:37.743(8)? (STDERR) 
W20190426-15:54:37.743(8)? (STDERR) in the root directory of your application.
W20190426-15:54:37.843(8)? (STDERR) /Users/fdc/.meteor/packages/meteor-tool/.1.8.1.4gwv5w.33478++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190426-15:54:37.843(8)? (STDERR)                                             throw(ex);
W20190426-15:54:37.843(8)? (STDERR)                                             ^
W20190426-15:54:37.844(8)? (STDERR) 
W20190426-15:54:37.844(8)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20190426-15:54:37.844(8)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
W20190426-15:54:37.844(8)? (STDERR)     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
W20190426-15:54:37.844(8)? (STDERR)     at packages/meteorhacks_meteorx.js:175:1
W20190426-15:54:37.844(8)? (STDERR)     at packages/meteorhacks_meteorx.js:200:4
W20190426-15:54:37.845(8)? (STDERR)     at packages/meteorhacks_meteorx.js:208:3
W20190426-15:54:37.845(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:419:36
W20190426-15:54:37.845(8)? (STDERR)     at Array.forEach (<anonymous>)
W20190426-15:54:37.845(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:228:19
W20190426-15:54:37.846(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:479:5
W20190426-15:54:37.846(8)? (STDERR)     at Function.run (/Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
W20190426-15:54:37.846(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:478:11
=> Exited with code: 1
W20190426-15:54:49.179(8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20190426-15:54:49.179(8)? (STDERR) While this implementation will work correctly, it is known to be
W20190426-15:54:49.180(8)? (STDERR) approximately three times slower than the native implementation.
W20190426-15:54:49.180(8)? (STDERR) In order to use the native implementation instead, run
W20190426-15:54:49.180(8)? (STDERR) 
W20190426-15:54:49.180(8)? (STDERR)   meteor npm install --save bcrypt
W20190426-15:54:49.180(8)? (STDERR) 
W20190426-15:54:49.180(8)? (STDERR) in the root directory of your application.
W20190426-15:54:49.272(8)? (STDERR) /Users/fdc/.meteor/packages/meteor-tool/.1.8.1.4gwv5w.33478++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190426-15:54:49.273(8)? (STDERR)                                             throw(ex);
W20190426-15:54:49.273(8)? (STDERR)                                             ^
W20190426-15:54:49.273(8)? (STDERR) 
W20190426-15:54:49.273(8)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20190426-15:54:49.273(8)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
W20190426-15:54:49.274(8)? (STDERR)     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
W20190426-15:54:49.274(8)? (STDERR)     at packages/meteorhacks_meteorx.js:175:1
W20190426-15:54:49.274(8)? (STDERR)     at packages/meteorhacks_meteorx.js:200:4
W20190426-15:54:49.274(8)? (STDERR)     at packages/meteorhacks_meteorx.js:208:3
W20190426-15:54:49.275(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:419:36
W20190426-15:54:49.275(8)? (STDERR)     at Array.forEach (<anonymous>)
W20190426-15:54:49.275(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:228:19
W20190426-15:54:49.275(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:479:5
W20190426-15:54:49.275(8)? (STDERR)     at Function.run (/Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
W20190426-15:54:49.275(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:478:11
=> Exited with code: 1
W20190426-15:55:01.405(8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20190426-15:55:01.406(8)? (STDERR) While this implementation will work correctly, it is known to be
W20190426-15:55:01.406(8)? (STDERR) approximately three times slower than the native implementation.
W20190426-15:55:01.406(8)? (STDERR) In order to use the native implementation instead, run
W20190426-15:55:01.406(8)? (STDERR) 
W20190426-15:55:01.406(8)? (STDERR)   meteor npm install --save bcrypt
W20190426-15:55:01.406(8)? (STDERR) 
W20190426-15:55:01.407(8)? (STDERR) in the root directory of your application.
W20190426-15:55:01.492(8)? (STDERR) /Users/fdc/.meteor/packages/meteor-tool/.1.8.1.4gwv5w.33478++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190426-15:55:01.493(8)? (STDERR)                                             throw(ex);
W20190426-15:55:01.493(8)? (STDERR)                                             ^
W20190426-15:55:01.493(8)? (STDERR) 
W20190426-15:55:01.493(8)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20190426-15:55:01.493(8)? (STDERR)     at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
W20190426-15:55:01.493(8)? (STDERR)     at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
W20190426-15:55:01.493(8)? (STDERR)     at packages/meteorhacks_meteorx.js:175:1
W20190426-15:55:01.494(8)? (STDERR)     at packages/meteorhacks_meteorx.js:200:4
W20190426-15:55:01.494(8)? (STDERR)     at packages/meteorhacks_meteorx.js:208:3
W20190426-15:55:01.494(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:419:36
W20190426-15:55:01.494(8)? (STDERR)     at Array.forEach (<anonymous>)
W20190426-15:55:01.494(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:228:19
W20190426-15:55:01.494(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:479:5
W20190426-15:55:01.494(8)? (STDERR)     at Function.run (/Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
W20190426-15:55:01.494(8)? (STDERR)     at /Users/fdc/APP/git/Rocket.Chat/.meteor/local/build/programs/server/boot.js:478:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by Jessting** [comment]
@knrt10 ，hello, I have  sent my question, you can see a description.

**Comment by knrt10** [comment]
try rebasing the latest code and try again.

**Comment by Jessting** [comment]
I have done like you said.

**Comment by lfdajr** [comment]
Can you post your NPM INSTALL log? Does it get to the end?

**Comment by lfdajr** [comment]
Maybe you have some blocking rule on your network, which is causing a hanging problem on the npm install process. Well, that was my problem, anyway.

The solution: git config --global url."https://".insteadOf git://

Then try npm install all dependencies. After that you may be ok to run meteor.

**Comment by geekgonecrazy** [comment]
Is this a straight clone or is this with your own changes?  Right now this appears to just be a support related thing.  Not seeing an actual bug here.

**Comment by Jessting** [comment]
Now I download the project again, add the command "git config --global url."https://".insteadOf git://", and then the problem is solved. The project can run. Thank you everyone.

**Comment by geekgonecrazy** [comment]
Good deal 👍
