### ISSUE TITLE
any plans to support Postgres?

### ISSUE THREAD

**Issue by denishpatel** [RocketChat/Rocket.Chat#1425]
Hello,

Currently,  Rocket Chat supports only Mongo DB. Postgres has JSONB support.  do you have any plans to support Postgres instead? If you are looking for help, I'm volunteer to help supporting Postgres.

**Comment by Sing-Li** [comment]
@denishpatel  - duplicate.  Please post on #533

**Comment by denishpatel** [comment]
Will do. thanks @Sing-Li
