### ISSUE TITLE
Not able to invite users to a private channel

### ISSUE THREAD

**Issue by anju-jsl** [RocketChat/Rocket.Chat#14250]
### Steps to reproduce:

1. Create a private group
2. Go to member list create "invite users"
3. type a name and it will show "loading" inifinite time

### Expected behavior:

Users should be shown as search results

### Actual behavior:

Nothing happens beyond "Loading"

### Server Setup Information:

- Version of Rocket.Chat Server: 2.15.2
- Operating System: IOS
- Deployment Method:  Web download
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by d-gubert** [comment]
There is an on-going PR to solve this https://github.com/RocketChat/Rocket.Chat/pull/14253 :)

Please note that this is a behavior introduced in a release candidate, and is not present in the latest _stable_ version of Rocket.Chat

**Comment by anju-jsl** [comment]
Thanks @d-gubert , How can I get the stable version of Rocket.chat? I downloaded the dmg file from internet

**Comment by d-gubert** [comment]
Hey @anju-jsl !

This is actually a problem in the Rocket.Chat server, and the dmg you downloaded is a client. So you'd have to contact the administrator of the server you connect to for them to update the server

**Comment by anju-jsl** [comment]
Thanks @d-gubert 
Sorry to ask trivial question, as I am more an end user of this application rather than the developer.
I have used the following URL as server URL : https://open.rocket.chat

I am still trying to understand as where the server actually is :-). any help is appreciated here

**Comment by d-gubert** [comment]
Ah, I see, you're using our community server!

Yes, we usually try out our release candidates on there - so you might stumble upon some instability here and there every once in a while.

The PR has already been merged and we'll be updating the our server soon enough - just bear with us a little longer for this to be fixed.

Thanks for being part of the community! :)

**Comment by anju-jsl** [comment]
Able to invite user now.
Thanks!!
