### ISSUE TITLE
Bug on Livechat switch department

### ISSUE THREAD

**Issue by carlo-fontanos** [RocketChat/Rocket.Chat#14255]
I'm getting the following error when attempting to switch department:

![Untitled](https://user-images.githubusercontent.com/12164593/56787449-21b87880-682f-11e9-9629-0965923912d8.jpg)

And I get this error in another page:

![Untitled2](https://user-images.githubusercontent.com/12164593/56787450-21b87880-682f-11e9-9812-e63466d0b6f8.jpg)

There is no error visible on the console, so I am not sure what is causing it. Bellow is the code that I'm using for displaying the livechat: 

```
<script type="text/javascript">
$(document).ready(function(){
	RocketChat(function() {
		this.registerGuest({
			name: 'xxxx xxxx',
			email: 'xxx@xxx.com',
			department: 'xxxxxxx',
		});
	});
});

(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = 'https://xxxxxxxxxx/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js?_=xxxxxxxxx';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://xxxxxxxxxx/livechat');
</script>
```

**Comment by knrt10** [comment]
@carlo-fontanos LiveChat API code must be inserted after the Livechat installation script, edit this to

```javascript
<script type="text/javascript">
(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = 'https://xxxxxxxxxx/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js?_=xxxxxxxxx';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://xxxxxxxxxx/livechat');

RocketChat(function() {
		this.registerGuest({
			name: 'xxxx xxxx',
			email: 'xxx@xxx.com',
			department: 'xxxxxxx',
		});
});
</script>
```
. I see you have used `$(document).ready` function but try with above solution, it might work, if not report back.

**Comment by carlo-fontanos** [comment]
@knrt10 I tried your suggestion but still getting `error-invalid-room` and `400`. 
Any other ideas?

**Comment by renatobecker** [comment]
@carlo-fontanos What is your server version?

**Comment by carlo-fontanos** [comment]
@renatobecker 
I'm running the above script from my local machine, and our RocketChat app is hosted at `https://cyberauctionschat.com`. Can you advice how to get  the server version please?

**Comment by tassoevan** [comment]
@carlo-fontanos @renatobecker 
> {"version":"0.74.3","success":true}

**Comment by carlo-fontanos** [comment]
Any update on this please?

**Comment by novafire99** [comment]
I have the exact same problem.  Was having the problem with 0.74.3 and then upgraded to 1.0.0-beta.1 with the same results. It's installed as a snap on debian 9.9 on a qemu vm.

**Comment by renatobecker** [comment]
@carlo-fontanos, what happens when you use the regular registration form instead of `registerGuest` method?
Does the same problem happen?

**Comment by carlo-fontanos** [comment]
@renatobecker Yes still getting the error: `400` when using the regular registration form.

**Comment by carlo-fontanos** [comment]
@renatobecker also, the `End Chat` button is not working, see bellow: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12164593/57508452-1e93b100-7334-11e9-9ef4-5c9c57216e0b.gif)

I tried clicking it several times but nothing happens.

**Comment by carlo-fontanos** [comment]
@renatobecker Any update on this please?

**Comment by renatobecker** [comment]
> @renatobecker also, the `End Chat` button is not working, see bellow:
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12164593/57508452-1e93b100-7334-11e9-9ef4-5c9c57216e0b.gif)
> 
> I tried clicking it several times but nothing happens.

What do you expect that happens after clicking on `End Chat` button? You have not even started a new conversation.

**Comment by carlo-fontanos** [comment]
@renatobecker, I was thinking the "End Chat" option will close the chat and show a message that the session has ended. I also tried adding a chat message before ending the chat but it still does not show any indication on the Live chat that the session has ended. Is there any way to add a message "Session Ended" so that users will not wonder what happened?

**Comment by carlo-fontanos** [comment]
What we are trying to accomplish is that every site will have their own department that will manage the customers who will contact them under their domain. Example, http://site.com/seller1 domain will have a department called seller1 and all live chat messages of customers under that domain will all go to seller1. If no agents are available in seller1 department - the live chat should show as offline, then all offline messages will be sent to seller1's email. Same logic applies to seller2, seller3 and so on. I would like to ask if this is possible to integrate using RocketChat?

**Comment by renatobecker** [comment]
> @renatobecker, I was thinking the "End Chat" option will close the chat and show a message that the session has ended. I also tried adding a chat message before ending the chat but it still does not show any indication on the Live chat that the session has ended. Is there any way to add a message "Session Ended" so that users will not wonder what happened?

Yeah, you can define a specific message to be displayed when the chat ends. Please, go to -> `/livechat-manager/appearance` route.

**Comment by renatobecker** [comment]
> What we are trying to accomplish is that every site will have their own department that will manage the customers who will contact them under their domain. Example, http://site.com/seller1 domain will have a department called seller1 and all live chat messages of customers under that domain will all go to seller1. If no agents are available in seller1 department - the live chat should show as offline, then all offline messages will be sent to seller1's email. Same logic applies to seller2, seller3 and so on. I would like to ask if this is possible to integrate using RocketChat?

Did you try our new Livechat solution?
If not, I suggest you try it out: https://github.com/RocketChat/Rocket.Chat.Livechat

To deal with `departments` on widget side, you can rely on:
https://rocket.chat/docs/developer-guides/livechat-api/#assign-chats-to-a-specific-department

**Comment by carlo-fontanos** [comment]
Thanks for referring the new version, the UI and everything is better.

I did some tests today, I have 3 items that are failing for our use case:

- I have two live chat departments named **one** and **two**
- When I performed every case bellow, I first send a message and then when done I click the End Chat option before proceeding with the next test case.
- For every case, I set the target department through code like this: 
```
(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = 'https://cyberauctionschat.com/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://cyberauctionschat.com/livechat?version=1.0.0');

RocketChat(function() {
	this.registerGuest({
		name: 'xxx',
		email: 'xxx@xx.com',
	});
	this.setDepartment('one'); // or two
});
```

**Live Chat test result notes:**
- When department one has active agents (online) while department two is offline, then I send a livechat message to department one, the message went to: one **(correct)**
- When department two has active agents (online) while department one is offline, then I send a livechat message to department two, the message went to: two **(correct)**

- When department one has NO active agents (offline) while department two is online, then I send a livechat message to department one, the message went to: two **(wrong, should show as offline)**
- When department two has NO active agents (offline) while department one is online, then I send a livechat message to department two, the message went to: one **(wrong, should show as offline)**

- When departments one and two have active agents (online), then I send a livechat message to department one, the message went to: one **(correct)**
- When departments one and two have active agents (online), then I send a livechat message to department two, the message went to: one **(wrong, should be two)**

- When departments one and two have NO active agents (offline), then I send a livechat message to department one, the message went to: Chat appears offline **(correct)**
- When departments one and two have NO active agents (offline), then I send a livechat message to department two, the message went to: Chat appears offline **(correct)**

I'm not sure if the above cases that I labeled with **wrong** are the default behavior, but if so, would it be possible to modify the configuration through API so that it follows our use case?

Thank you,
Carlo

**Comment by renatobecker** [comment]
Yeah, it's because you're defining the `department` after registering the guest.
But, I took a look at the `registerGuest` method and, even you pass the department along with the other properties(It's supported), it will not work.
So, I'm moving this issue to the right repository and then we will fix it.

Thanks.

**Comment by renatobecker** [comment]
Issue moved to [RocketChat/Rocket.Chat.Livechat #235](https://github.com/RocketChat/Rocket.Chat.Livechat/issues/235) via [**ZenHub**](https://www.zenhub.com/)
