### ISSUE TITLE
[BUG] Incorrect thread description shown

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat#14264]
### Description:

![DeepinScreenshot_select-area_20190426235359](https://user-images.githubusercontent.com/22556377/56828705-87345580-687f-11e9-8bf7-75d48dad0c26.png)

In the above screenshot, the thread description (written in blue) is of another thread.

### Server Setup Information:

- Rocket.Chat Server: open.rocket.chat

**Comment by knrt10** [comment]
+1. Also for me description was different, maybe some message counter is getting wrong.

**Comment by tassoevan** [comment]
Does it keep happening?

**Comment by ggazzo** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/14372
