### ISSUE TITLE
[REGRESSION] Date separator is displayed twice on the same channel for the same day

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#14261]
In our _gsoc2019_ public channel.

![Screen Shot 2019-04-26 at 11 22 21](https://user-images.githubusercontent.com/551004/56814461-a0a0b780-6815-11e9-952e-802a81be2586.png)

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/14269/commits/fe190867cbd4ccef7f177d23cee72aff79050275
