### ISSUE TITLE
Auto keyboard pop-up in mobile making hard to read chat

### ISSUE THREAD

**Issue by online0227** [RocketChat/Rocket.Chat#14271]
### Description:

On mobile web browser, whenever I move to any chat channel, keyboard automatically pops up, making hard to read chats before writing anything to catch up the situations in each chat room. 

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:
Keyboard should not pop up automatically whenever moving to a channel unless user press text box. 

### Actual behavior:
Keyboard just appears so that it makes hard to read. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by Rodriq** [comment]
I think this Issue is duplicate to #10381 and #13758

**Comment by tassoevan** [comment]
Closing in favor of #13758.
