### ISSUE TITLE
Is memory usage of 1.0.0-rc.3 Docker/Kubernetes deployment too high ~500MB/instance?

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#14270]
We're in the process of deploying multiple Rocket.Chat instances with a shared MongoDB replica-set. Memory usage of 2 Rocket.Chat instances with < 5, not active test-users in it is around 500MB per instance:
![Bildschirmfoto 2019-04-27 um 10 50 51](https://user-images.githubusercontent.com/972180/56847400-82e95600-68da-11e9-95f2-d6565c52cf0a.png)
The high memory usage is reached immediately after Rocket.Chat is started. So we are not talking about memory leaking after days of usage!
Looking at the K8s node running the nodejs processes of the 2 Rocket.Chat instances show the same usage:
```
root@fra-kube2:~# ps axfu |grep 'main.js
> ^USER'
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
99999    56467  0.3  2.2 1821228 507068 ?      Ssl  Apr26   4:20      |   \_ node main.js
99999    65023  3.1  2.1 1792156 491040 ?      Ssl  08:15   0:28          \_ node main.js
root     34867  0.0  0.0  17140  2224 pts/0    S+   08:30   0:00          \_ grep --color=auto main.js ^USER
```
What is going on there?

Is that a problem of the current release-candidate, or a general one?

Ralf

**Comment by ralfbecker** [comment]
Before you have to ask: I currently use no fixed memory request for the container/pod, the memory has been requested and somehow used by nodejs / Rocket.Chat.

**Comment by Sing-Li** [comment]
@ralfbecker  this is not abnormal.   We do not tune for quiescence memory claims at all.  Can you please explain why it may be significant for you?

**Comment by ralfbecker** [comment]
Thanks for the quick answer :)

We want to deploy Rocket.Chat for all our SAAS users, which are currently around 500 instances of our own open-source software (https://www.egrouwpare.org). 

While Rocket.Chat is for most of our users a nice "goody", it would take considerable more (memory) resources compared to our main product, which is a PHP based web-application. Please don't take me wrong, I really like Rocket.Chat :)

Ralf

**Comment by Sing-Li** [comment]
No problem at all  🙂 And thanks for your support @ralfbecker !   

It may just be difference in app tuning approaches and app memory usage patterns.  

Rocket.Chat as a nodeJS server app actually has the following "highly dynamic" pattern of memory usage:
   * initial startup at quiescence =  significant size as you've observed
   * per user connection with mainly chat activity = incrementally small 
   * other memory intensive activities started by users = incrementally large  claim for buffers etc

And  we recommend allocating up to 4 GB to maximize the number of users handle per instance.  This assumes that you've tuned/configure your container to allow saturation of the CPU core the instance is on.

Hope this is helpful.

**Comment by ralfbecker** [comment]
Thanks again for your insights 🙂

**Comment by Sing-Li** [comment]
Just an additional note:   As a garbage collected runtime system, nodeJS servers  have the runtime memory usage pattern, under high load,  of -- linearly increasing up to the maximum allocated (say 4 GB) then sudden (reclaim) decrease --- repeated sawtooth-like  over time 👌 

Thanks again for bringing this up @ralfbecker.

**Comment by ralfbecker** [comment]
Do you have more advice or documentation about production deployment of Rocket.Chat, I wasn't very successful in finding much :(

Specially about session handler (giving that scary message of not being for production)[https://github.com/RocketChat/Rocket.Chat/issues/10714], or expected resource usage ...

Ralf
