### ISSUE TITLE
Some Private groups and direct messages empty

### ISSUE THREAD

**Issue by phillipplum** [RocketChat/Rocket.Chat#14279]
### Description:

After upgrading to Version 1.0.0 some dm and private channels empty. I can not see why some are empty and some are not. But in the admin panel it shows that there are messages.

![image](https://user-images.githubusercontent.com/6051483/56860828-fbafe700-699a-11e9-9c08-86beb97bea04.png)

![image](https://user-images.githubusercontent.com/6051483/56860839-0ec2b700-699b-11e9-84ae-c250122bec3a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.12

**Comment by MarcosSpessatto** [comment]
@phillipplum can you provide more details? Did you see if the messages exist in the database or if they were removed?

**Comment by phillipplum** [comment]
@MarcosSpessatto yes. It looks like the messages have also been deleted from the database.

**Comment by ggazzo** [comment]
@phillipplum I'm closing this issue, but it you found this problem again please let me know
