### ISSUE TITLE
Cannot terminate OAuth provider session in desktop app

### ISSUE THREAD

**Issue by popiolek** [RocketChat/Rocket.Chat#1427]
When using desktop app with GitLab OAuth 2 there is no possibility to terminate session with OAuth provider.

User can log out from Rocket.chat, but after using GitLab login option user is automatically logged in (old GitLab session is still stored) without option to choose different account.

**Comment by Sing-Li** [comment]
@sampaiodiego Is there a 'hot key' that disables oauth login when starting the Electron App?   

Or how does one go about clearing the cookies/cache of an Electron App upon startup?  TIA

**Comment by sampaiodiego** [comment]
I don't get the idea with the 'hot key'.. 
but what I think is happening here, is that GitLab oAuth actually logs you in on GitLab.. so, when you logs out from Rocket.Chat you keep logged in on GitLab then when you try to log in on Rocket.Chat again using GitLab oAuth, as you are still logged in, it uses the same session.

**Comment by popiolek** [comment]
@sampaiodiego Yes, that's exactly what happens. There's no option to earase session. Only way now is to change page via DevTools console, log out from GitLab, and go back to rocket.chat.

**Comment by engelgabriel** [comment]
This is a problem with the sessions inside Electron and it would happen with all oAuth providers.
I'll create an issue on  the right project for that.
https://github.com/RocketChat/Rocket.Chat.Electron/issues/60
