### ISSUE TITLE
Messing up the LDAP Configuration leads to (admin/general) lockout

### ISSUE THREAD

**Issue by turbomettwurst** [RocketChat/Rocket.Chat#1428]
Precursor: I am new to Mongo, which is why I am struggling with such a little Detail.
I messed up the filter query for my LDAP connection and now I am locked out of my rocket chat installation. 
It would be awesome if Rocketchat supplied a little helper script that deactivates LDAP in MongoDB so one can login again without having to navigate inside mongodb.

**Comment by geekgonecrazy** [comment]
Or alternatively be able to still log in with the super admin account maybe?

**Comment by emcguinness** [comment]
Being a google apps user here, that is how Google do it. Having super admins bypass the remote login methods and log in directly with a username and password. This does mean all admins loose the convenience of what ever third party login services are enabled.

An alternative is to have an admin login page, this always allows local login even if LDAP is enabled but only for admins.

No real preference either way myself, just raising it for discussion. Was hoping to get some time soon to have another go at LDAP and this was on my list to improve.

**Comment by emcguinness** [comment]
Just had a slight afterthought on this one. If you go down the route of admin users bypassing the third party login and using local login only is for new admins down the line. Admin1 sets up rhcat, gets it all working and enables LDAP.  Several users sign in using LDAP but now one of these users get made an admin they can no longer login as their is no password set for local login.

Allowing admins to set passwords (issue [here](https://github.com/RocketChat/Rocket.Chat/issues/1399)) or something that would allow the user to do it themselves (like password reset email) would also need to be done. Also related to the issue [here ](https://github.com/RocketChat/Rocket.Chat/issues/1436), which is a more generic issue on reverting back to local logins.

So while this would fix the accidentally locking out

**Comment by VoidAndAny** [comment]
If someone is concerned I share here how I did to disable LDAP authentication.
Enter in mongo:
```
mongo
```

Check value : 
```
001-rs:PRIMARY> db.rocketchat_settings.find( { _id: "LDAP_Enable"}, {value: 1} )
{ "_id" : "LDAP_Enable", "value" : true }
```
LDAP is enabled, let's disable it : 
```
001-rs:PRIMARY> db.rocketchat_settings.update( { _id: "LDAP_Enable"}, { $set: {value: false} } )
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
```
That's all, if it can help someone...

**Comment by turbomettwurst** [comment]
Thanks a lot, imo this should be added to the documentation until the code has been improved to handle that problem in a somewhat smarter fashion :)

**Comment by engelgabriel** [comment]
LDAP login now uses regular account with password as fallback and now admins can set passwords
