### ISSUE TITLE
TypeError: Data must be a string or a buffer (Rocketchat 1.0.0)

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#14285]
### Description:

Hello Devs. After upgrading to 1.0.0 my log gets flooded by:

`
    at /opt/rocketchat-1.0.0/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Exception in callback of async function: TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at AccountsServer._hashLoginToken (packages/accounts-base/accounts_server.js:782:10)
    at Users.findOneByIdAndLoginToken (app/models/server/models/Users.js:392:57)
    at isUserAuthenticated (server/routes/avatar/utils.js:45:26)
    at userCanAccessAvatar (server/routes/avatar/utils.js:55:26)
    at Meteor.bindEnvironment (server/routes/avatar/middlewares/auth.js:7:7)
    at runWithEnvironment (packages/meteor.js:1356:24)
    at packages/meteor.js:1369:14
`

It does not seem to have an impact right now.

### Steps to reproduce:

1. Upgrade to 1.0.0
2. Have a look at the logs

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 8.16.0
- MongoDB Version: 3.6

**Comment by himpierre** [comment]
The problem seems to be the android client. Error only occurs if an android client connects. Currently using the 3.3.0 foss apk.

**Comment by himpierre** [comment]
Also there are no avatar pictures anymore. The error message says something related i guess.

**Comment by ccfiel** [comment]
same here

**Comment by robbyoconnor** [comment]
Not to be that guy, but also here too: 

[Here's a full log](https://gist.githubusercontent.com/robbyoconnor/82724033e8f42d23acb2517ce9e068a7/raw/40bf8b642c33c665f5c3b2b1c9645e8f2e17972e/gistfile1.txt):

**Comment by robbyoconnor** [comment]
I love this team, they're amazing but I do want to state that I feel like this release could have stood some more QA.
