### ISSUE TITLE
Rocket.Chat 1.0.0 stopped working with Percona server for MongoDB 3.6

### ISSUE THREAD

**Issue by thaiphv** [RocketChat/Rocket.Chat#14298]
### Description:
We have been running Rocket.Chat with Percona server for MongoDB 3.6 for several months without any issues. However, after upgrading to the latest release `1.0.0`, all of Rocket.Chat instances stopped working

### Expected behavior:

Rocket.Chat 1.0.0 should work with Percona server for MongoDB 3.6 as it is compatible with MongoDB 3.6.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0
- Operating System: Ubuntu 16.04
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.8-2.0

### Additional context
I believe this issue is caused by the `semver` module, which doesn't understand the version string `3.6.8-2.0` and consider it an older version of MongoDB and the fix should be simple.

### Relevant logs:
YOUR CURRENT MONGODB VERSION IS NOT SUPPORTED, PLEASE UPGRADE TO VERSION 3.2 OR LATER

**Comment by rodrigok** [comment]
Thanks @thaiphv we are shipping version 1.0.1 with some fixes, we will check your PR and ship 1.0.2 tomorrow.

**Comment by fabien4455** [comment]
i have a problem when upgrading to 1.0.1.... I'll send a issue
