### ISSUE TITLE
[regression]  Admin cannot delete pix

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1429]
Case to reproduce: 

Look into GENERAL circa Nov 17, 2015 (early aft EST) on demo.rocket.chat -   try to delete the Lion defecating pix.

No console error - toolbar simply disappeared.

**Comment by graywolf336** [comment]
The "message removed" shows up, but the image doesn't disappear. Seems like something to do with oEmbed

**Comment by Sing-Li** [comment]
@marceloschmidt pointed out that if you change Admin-> Message -> Show Delete Status to FALSE ... the problem goes away -  you can once again delete entire messge, including the OEMBED.

But formerly orphaned OEMBED will still linger ad-infinitum.
