### ISSUE TITLE
zimbra integration

### ISSUE THREAD

**Issue by perfectwebtech** [RocketChat/Rocket.Chat#14292]
zimbra integration unable to work 

according to zimbra step
 
anyone can help me ?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
