### ISSUE TITLE
Leverage Chat First Page (when first login)

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1430]
It would be a great idea to leverage and make use of the first page (which i believe its a static HTML). 1- This page would be really useful if we can list available channels (clickable) and ability to sign up to private channels (premium with payment option).
2- Ability to have demo youtube or any other embedded objects

**Comment by IQ2022** [comment]
Main page to showcase available rooms and trending topics? Not sure if this is possible, also to book a room on demand .. similar to BLAB  (https://blab.im/) or hangouts etc..

**Comment by marceloschmidt** [comment]
It's possible to add custom HTML to the home page.
