### ISSUE TITLE
Gitlab OAUTH Failure

### ISSUE THREAD

**Issue by h4wkmoon** [RocketChat/Rocket.Chat#14307]
### Description:

Version : 1.0.1
Docker image.
Fresh install
I've set up oauth2 with Gitlab (Gitlab is identity provider), like I always do in rocketchat. No change on gitlab side.
When users try to login with gitlab in RC, they receive an error message 500.
RC logs indicate a "401 Unauthorized" error from gitlab.
Gitlab indicates no error except the attempt to access the v3 api. 

### Steps to reproduce:

1. Install Rocket CHAT
2. Set up GITLAB Oauth2
3. Try to log using gitlab

### Expected behavior:

Login success when provided a correct user.password in gitlab popup

### Actual behavior:

Error 500

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: The one from the official docker image.
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes, as it is mandatory now.
- NodeJS Version: The one from the official docker image.
- MongoDB Version: 3.6

### Additional context

I worked perfectly in 0.73

### Relevant logs:

```
{"line":"392","file":"oauth_server.js","message":"Error in OAuth Server: Failed to fetch identity from gitlab at http://*********************/api/v3/user . failed [401] {\"message\":\"401 Unauthorized\"}","time":{"$date":1556546048886},"level":"warn"}
--
  | Exception while invoking method 'login' { Error: Failed to fetch identity from gitlab at http://l***************************/api/v3/user . failed [401] {"message":"401 Unauthorized"}
  | at CustomOAuth.getIdentity (app/custom-oauth/server/custom_oauth_server.js:178:18)
  | at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:188:26)
  | at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
  | at middleware (packages/oauth/oauth_server.js:161:5)
  | at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  | message: 'Failed to fetch identity from gitlab at http://******************************/api/v3/user . failed [401] {"message":"401 Unauthorized"}',
  | response:
  | { statusCode: 401,
  | content: '{"message":"401 Unauthorized"}',
  | headers:
  | { server: 'nginx',
  | date: 'Mon, 29 Apr 2019 13:54:08 GMT',
  | 'content-type': 'application/json',
  | 'content-length': '30',
  | connection: 'close',
  | 'cache-control': 'no-cache',
  | vary: 'Origin',
  | 'x-content-type-options': 'nosniff',
  | 'x-frame-options': 'SAMEORIGIN',
  | 'x-request-id': '**********************************',
  | 'x-runtime': '0.008920' },
  | data: { message: '401 Unauthorized' } } }
```

**Comment by h4wkmoon** [comment]
I tried with another gitlab server, on https, with a valid certificate. Same issue.

**Comment by Lawri-van-Buel** [comment]
might be DNS / IP routeing.... however I get the following issue when I solve that bit...
Gitlab logs: `Can't verify CSRF token authenticity.`

**Comment by h4wkmoon** [comment]
Same exact configuration works perfectly with rocket.chat 0.7x.

**Comment by mcsage** [comment]
Same here. I can confirm @h4wkmoon 's issue. Just upgraded to 1.0.2 and Gitlab oauth is broken.

**Comment by whedro** [comment]
Gitlab have API v4 .. not v3 ...  `http://******************************/api/v3/user`

API v3 was removed in GitLab 11.0.

**Comment by xadereq** [comment]
I'm also confirming this issue, after upgrading to 1.0.1 Oauth doesn't work with Gitlab 11.9.1
