### ISSUE TITLE
Error message: OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT refers to misleading article

### ISSUE THREAD

**Issue by jdpond** [RocketChat/Rocket.Chat#14305]
### Description:
Starting In Release 1.0, Rocket.Chat requires the use of MongoDB REPLICASET to improve performance via Meteor Oplog tailing.

Instances that had not enabled MongoDB OPLOG fail on startup.

OPLOG is required, which is a component of  the MongoDB REPLICASET functionality, but having actual replicated clusters, though intimated in the link (https://rocket.chat/docs/installation/docker-containers/high-availability-install) is not actually necessary.  The requirement is actually to enable OPLOG functionality, which can be done as described in https://rocket.chat/docs/installation/manual-installation/mongo-replicas/

The error remediation is:

1. Enable OPLOG and;
2. Ensure the system variable MONGO_OPLOG_URL reflects the url where it was enabled

Modifying the referenced article in the Error message greatly clarifies both the issue and the resolution.

### Steps to reproduce:

1. Upgrade an existing non-enabled rocket.chat server using a non-enabled MongoDB OPLOG  
2. Bring up the node
3. An error status will be reported in STDOUT (See below)

### Expected behavior:

Error message link should point to a more informative article for instances encountering this error.
Example: https://rocket.chat/docs/installation/manual-installation/mongo-replicas/

This refers to [Configure a replica set for MongoDB](https://rocket.chat/docs/installation/manual-installation/mongo-replicas/)

### Actual behavior:

Error message points to an article that intimates that High Availability MongoDB must be used:
https://rocket.chat/docs/installation/docker-containers/high-availability-install

which refers to article [Guide to install Rocket.Chat as HA with mongodb replicaset as backend](https://rocket.chat/docs/installation/docker-containers/high-availability-install)

### Server Setup Information:

server.js:199 System ? error
? +-------------------------------------------------------------------------------------+
? | SERVER ERROR |
? +-------------------------------------------------------------------------------------+
? | |
? | Rocket.Chat Version: 1.0.0 |
? | NodeJS Version: 8.11.4 - x64 |
? | MongoDB Version: 3.2.7 |
? | MongoDB Engine: wiredTiger |
? | Platform: linux |
? | Process Port: 3001 |
? | Site URL: [https://example.com/] |
? | ReplicaSet OpLog: Disabled |
? | Commit Hash: 60f1a4afd6 |
? | Commit Branch: HEAD |
? | |
? | OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT: |
? | https://rocket.chat/docs/installation/docker-containers/high-availability-install |
? | |
? +-------------------------------------------------------------------------------------+

### Additional context

This problem has been addresed in:
[FIX] Switch oplog required doc link to more accurate link
https://github.com/RocketChat/Rocket.Chat/pull/14288

### Relevant logs:

See STDOUT above

### Possible fix
```
#git diff server/startup/serverRunning.js
diff --git a/server/startup/serverRunning.js b/server/startup/serverRunning.js
index 68809a200..0c04d1083 100644
--- a/server/startup/serverRunning.js
+++ b/server/startup/serverRunning.js
@@ -49,7 +49,10 @@ Meteor.startup(function() {
                msg = msg.join('\n');

                if (!isOplogEnabled) {
-                       msg += ['', '', 'OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:', 'https://go.rocket.chat/i/oplog-required'].join('\n');
+                        msg += ['', '', 'OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT',
+                               'Rocket.Chat uses MongoDB replica set to improve performance via Meteor Oplog tailing.',
+                               'OPLOG must be enabled and MONGO_OPLOG_URL must exist in the environment variable for the service definition',
+                               'For further information see:','https://go.rocket.chat/i/oplog-required'].join('\n');
                        SystemLogger.error_box(msg, 'SERVER ERROR');

                        return process.exit(1);


```

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/14288
