### ISSUE TITLE
customizable url paths(permalink).

### ISSUE THREAD

**Issue by jacknapier2099** [RocketChat/Rocket.Chat#1431]
So I was thinking for white labeling aspects we need to add a feature were the permalink path (currently defaults to https://yoursite.com/ufs/rocketchat_uploads/ ) can be change to a more generic or customizable name e.g. https://yoursite.com/ufs/yournamehere_uploads/. 
##

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
