### ISSUE TITLE
Need correct iFrame settings to allow JITSI to send request for Microphone/Camera to parent window

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#14314]
Running Rocket.Chat in an iFrame at peerunschooling.net/chat

When I do a video call, it doesn't ask for access to the microphone/camera.  If I open the app directly (no iframe) - then it does.

I see there is an area for Admin -> General -> iFrame  but I'm not sure what settings go here:

Enable Send:  True   False
Send Target Origin: 
Enable Receive: True   False
Receive Origins:

**Comment by flantascience** [comment]
Anyone able to help with this?   Still no clue how to handle this problem.

**Comment by CrestApps** [comment]
@flantascience were you able to configure it? You asked this question 2 years ago yet no one responded and I am stuck exactly where you are at.

**Comment by sichrif** [comment]
add this to your iframe:
`allow="camera; microphone;"`

**Comment by gabriellsh** [comment]
We have dropped support for this Jitsi feature. It should now be installed as an app. Please refer to docs https://docs.rocket.chat/use-rocket.chat/rocket.chat-conference-call/conference-call-admin-guide/jitsi-app

Thanks @sichrif, for older versions that might work.
