### ISSUE TITLE
UX Update to sidebar menus

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#14335]
UX Update to sidebar menus:

- Unify both menus
- Add "check mark" to items, rather than just **bold**
- Change the main icon (the one with az) to a generic list setting icon.
- Change the behavior of Avatar toggle to use "check mark"
- Re-word sorter options to match new mobiles apps

<img width="237" alt="Screenshot 2019-04-30 at 14 14 25" src="https://user-images.githubusercontent.com/1000217/56980319-740cd880-6b52-11e9-92d0-6d595d306a56.png">

<img width="310" alt="Screenshot 2019-04-30 at 14 14 18" src="https://user-images.githubusercontent.com/1000217/56980321-740cd880-6b52-11e9-9dd8-46d600878bea.png">

Use as reference for "check mark":
![image](https://user-images.githubusercontent.com/1000217/56980228-2b551f80-6b52-11e9-9f2b-52590426b7ae.png)

**Comment by brunosquadros** [comment]
@engelgabriel 
Here is the final propose. I realized that we don't have a hover behavior on menus then I've done one similar as the messages
<img width="834" alt="Screen Shot 2019-05-02 at 15 05 37" src="https://user-images.githubusercontent.com/4096458/57096740-53788600-6cec-11e9-942d-abe5aabd4a1c.png">
