### ISSUE TITLE
Create personal access token without authorization

### ISSUE THREAD

**Issue by neonfly** [RocketChat/Rocket.Chat#14331]
Description:
Users can create personal access tokens, even if they are not authorized to do so.

Steps to reproduce:
Make sure user's aren't allowed to create access tokens.
As normal user: Go to Profile -> My Account -> Personal Access Tokens
Create Token

Expected behavior:
No menu item is there and if the function should be locked.

Actual behavior:
Users can create personal access tokens.

Server Setup Information:
    Version of Rocket.Chat Server: 1.0.1
    Operating System: Linux
    Number of Running Instances: 1
    NodeJS Version: 8.11.4
    MongoDB Version: 3.2.19

**Comment by MarcosSpessatto** [comment]
@neonfly What version of server are you using? Did you disable the `create-personal-access-tokens` permission in the admin panel? Because if the user does not have this permission, even the menu item won't appear.

**Comment by neonfly** [comment]
@MarcosSpessatto

> What version of server are you using?
At the time of ticket creation: 1.0.1 as you can see above.

> Did you disable the create-personal-access-tokens permission in the admin panel?
Yes I did. I checked the settings before I created this ticket.

I've hidden the menu li with CSS rules as first consequence.

Now we are running on 1.0.3, on monday I will check, if the error still occurs.

Thx neonfly

**Comment by geekgonecrazy** [comment]
Is this an issue or can be closed?

**Comment by makibras** [comment]
@neonfly : can this be closed?
