### ISSUE TITLE
Saving hashes of every login token ever

### ISSUE THREAD

**Issue by KonstantinCodes** [RocketChat/Rocket.Chat#14349]
### Description:

The MongoDB persists the hash of every login token generated ever. I'm running a RocketChat instance for little over 2 months and I use the API to generate login tokens for all of the users of my custom frontend. Per user there are already almost 400 records of hashes

### Steps to reproduce:

1. POST to `/api/v1/login`, get userId and token
2. MongoDB persisted the hash of that token for ever in `users`.`<<userid>>`.`services`.`resume`.`loginTokens`

### Expected behavior:

There should be the expiry timestamp included in this record, so that expired tokens can be deleted.

### Actual behavior:

only fields `when` and `hashedToken` are persisted

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by Hudell** [comment]
The login tokens are not being removed because the user never logs out. Currently there's no check to remove expired tokens from mongo.

This is a known meteor issue, but it's low priority. If necessary we can add something on our side to remove those tokens.

**Comment by geekgonecrazy** [comment]
I believe this now caps at 50.  Closing
