### ISSUE TITLE
How to stop multiple user login at a time from Rocket.chat ?

### ISSUE THREAD

**Issue by theonetech1** [RocketChat/Rocket.Chat#14342]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 18.10
- Deployment Method: 
- Number of Running Instances: 1

**Comment by reetp** [comment]
Please fill in the blanks in the template with your information and a proper description of your issue - no one can help you otherwise.

**Comment by theonetech1** [comment]
I think you know very well, Rocket chat version and Other things not required for this Questions

**Comment by Lawri-van-Buel** [comment]
the awnser is than also simple... by deploying rocketchat as prescribed in the documentations.... Otherwise we will need to know your setup (even if its just so we can reproduce the issue and have proper logging).

**Comment by reetp** [comment]
And the question is still not that clear.

Are you talking about one person logging in multiple times? How would that work if they leave their desktop connected and use mobile at the same time ?

Or preventing multiple users at the same time? Why?

Please clarify as it makes no sense at the minute.
