### ISSUE TITLE
Link in Announcement popup broken

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#14346]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/51996/57041170-37f77780-6c27-11e9-88fe-46db8d6282a0.png">

Announcement is: `If you are updating to 1.0 be sure to [see guide. here:](https://rocket.chat/docs/installation/updating/to-1-0/)`

Version: 1.0.2

**Comment by knrt10** [comment]
On it, will try to fix this

**Comment by novacrazy** [comment]
It seems any markdown at all is broken in announcements. 

Any update for #14635 ? Would that fix markdown in general?
