### ISSUE TITLE
Rocket chat not continously blinking Taskbar when got new message from anyone 

### ISSUE THREAD

**Issue by theonetech1** [RocketChat/Rocket.Chat#14343]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu 18.10
- Deployment Method: 
- Number of Running Instances: 1

**Comment by tassoevan** [comment]
This issue is related to the desktop client. Please reopen it in the [desktop app repository](https://github.com/RocketChat/Rocket.Chat.Electron). Thanks!
