### ISSUE TITLE
custom my register login pannel includ new input field

### ISSUE THREAD

**Issue by mariofc22** [RocketChat/Rocket.Chat#14340]
I would like to include an html input field on the register screen called request where the user should enter a their protocol number.

my instance rocketchat: https://www.vistoriaonline.defesacivil.tk

**Comment by geekgonecrazy** [comment]
https://rocket.chat/docs/administrator-guides/custom-fields/#custom-fields

setting to required should make it show up on register.

**Comment by mariofc22** [comment]
I did this in json valid code, but the result was the emergence of only one space between the inputs between the email field and the password field not popping up the new input created.

**Comment by mariofc22** [comment]
> https://rocket.chat/docs/administrator-guides/custom-fields/#custom-fields
> 
> setting to required should make it show up on register.

I did this but I don't have a good result

**Comment by geekgonecrazy** [comment]
Looks like it’s showing the fields as asked in your issue.  If it’s not working as expected feel free to open a new issue.  Please be sure to include as many details as possible in new issue so can be reproduced
