### ISSUE TITLE
Add ability to unsubscribe from threads

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#14344]
It doesn't seem to be clear how to remove ourselves from threads. If not possible, it should be. 

I propose we have a group in the sidebar for threads like we do discussions.

**Comment by geekgonecrazy** [comment]
@RocketChat/core didn't we have the ability to follow / unfollow during development of this feature?  It seems to have disappeared or not made it into the final version?

Actually seems to have been commented out here: https://github.com/RocketChat/Rocket.Chat/pull/14268

cc @MarcosSpessatto

**Comment by ggazzo** [comment]
@robbyoconnor actually that feature was removed from the message actions ( and I didnt like it) but now you can unfollow clicking here(bell)
![image](https://user-images.githubusercontent.com/5263975/57075597-92dbae00-6cbd-11e9-9273-7a95779131d7.png)

**Comment by robbyoconnor** [comment]
The UX for that is horrible. I should also see it in the thread side-view, but I don't.
 

![image](https://user-images.githubusercontent.com/23088/57087794-db4f9780-6cce-11e9-88df-ffbbf49be365.png)

**Comment by robbyoconnor** [comment]
Also to add onto this, that bell is so tiny it's not funny, what if someone is visually impaired? 

I'm trying to not be negative and bitter over this whole thing, but it's getting really hard, the saving grace is how receptive you folks are to feedback, but it shouldn't have taken this 2 point releases in less than a week.

**Comment by ggazzo** [comment]
@robbyoconnor 🤷‍♂

**Comment by robbyoconnor** [comment]
Wait, what is supposed to be meant by that :man_shrugging: emoji?

**Comment by ggazzo** [comment]
means sorry about: 

> I'm trying to not be negative and bitter over this whole thing ...  but it shouldn't have taken this 2 point releases in less than a week.

but there is nobody to be blamed, its not our intention turn the things worst... the only thing I/we can do its accept the feedback and fix soon as possible :) :(

**Comment by d-gubert** [comment]
> Also to add onto this, that bell is so tiny it's not funny, what if someone is visually impaired?

This is a really good point which we really need to be more considerate of

**Comment by mjovanovic0** [comment]
Also regarding to this, there should be switch in settings for default behaviour: Following or Unfollowing by default.

For example most of our users don't want to follow by default and having main chat "spammed" by replies in thread conversation that they are not interested in.

Either global settings or maybe better in Default User Preference / User Preference so that each user can tweak how they want it.
