### ISSUE TITLE
The web client does not work on Windows XP for Google Chrome. Firefox works correctly.

### ISSUE THREAD

**Issue by evant89** [RocketChat/Rocket.Chat#14350]
The web client does not work on Windows XP for Google Chrome. Firefox works correctly.Steps to reproduce:

1. Go to https://chat.oranta.ua

### Expected behavior:

![Знімок екрана з 2019-05-02 11-06-39](https://user-images.githubusercontent.com/36101287/57062938-624e4100-6cca-11e9-8380-34ce5f338f9f.png)

### Actual behavior:

![Знімок екрана з 2019-05-02 11-03-31](https://user-images.githubusercontent.com/36101287/57062892-3df26480-6cca-11e9-834c-d4d3fe8871c4.png)

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.2
Operating System: Ubuntu 16.04 64bit
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 8.11.4
MongoDB Version: 4.0.9

### Additional context

Reverse proxy NGINX

**Comment by evant89** [comment]
Google Chrome ver.

![Знімок екрана з 2019-05-02 11-13-04](https://user-images.githubusercontent.com/36101287/57063256-4b5c1e80-6ccb-11e9-938b-28c8415a2004.png)

**Comment by reetp** [comment]
Windows XP has no official support, and hasn't for a long time.
It is unlikely the devs are going to fix this. Like most of us they probably don't have XP to even test with.
The resolution is to use a supported OS.

**Comment by graywolf336** [comment]
Closing issue because of what @reetp mentioned, plus the Chrome version you're using is years years old. The current version of Chrome is 74.0.3729.131.
