### ISSUE TITLE
Crashing Channel With Markdown Link

### ISSUE THREAD

**Issue by nicolaiparlog** [RocketChat/Rocket.Chat#1435]
In any channel this message will lead to a hangup for every member of the channel:

    [Link](https://www.google.com/pages/viewpage.action?pageId=314703900#Title)

The channel becomes unusable and has to be deleted by an administrator.

The URL is cobbled together to create a minimal example. The original was longer and it looks like that plays a role. In trying to locate the problem we tried many different URLs and it look like the following factors increase the likelihood of a hangup:

* occurence of `?`, `=`, and/or `#`
* more slashes
* longer URL parameters

For example this URL seems to hit a sweetspot where rendering the link takes a long time without running into a timeout:

    [Link](https://www.google.de/viewpage.action?pageId=4)

My pretty uneducated guess is that some RegEx-Parser is performing badly.

Also: These links are not rendered as "[Link](https://www.google.de/viewpage.action?pageId=4)" but as "`[Link](https://www.google.de/viewpage.action?pageId=4)`".

**Comment by Sing-Li** [comment]
@nicolaiparlog thanks for your report. We are actively investigating this as a security issue.

**Comment by nicolaiparlog** [comment]
@Sing-Li Tanks for your quick response. But I'm a little baffled that you closed this issue. How can I keep track of the progress?

**Comment by marceloschmidt** [comment]
@nicolaiparlog can you tell me what commit / version are you using? We used to have that problem and it was fixed once, so I just want to make sure you're using an updated version.

**Comment by nicolaiparlog** [comment]
`http://<your server name>/buildinfo/buildinfo.txt` says `v0.7.1862`

**Comment by marceloschmidt** [comment]
This is a known old bug. It has been fixed on https://github.com/RocketChat/Rocket.Chat/commit/11692d51d12e7624357dea6f86fc1739d956dbf6. Can you upgrade?

**Comment by nicolaiparlog** [comment]
I'll check and get back to you. Might take a while.

**Comment by nicolaiparlog** [comment]
Looks indeed like it is fixed. I can't reproduce with my examples above. Cool, thx! :+1:
