### ISSUE TITLE
Auto translate is Broken

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#14359]
### Description:

I followed the tutorial steps:

1. Go to http://cloud.google.com/console/
2. Create a Project and select it.
3. On the navigation menu, go to “APIs & Services” => Dashboard Tab
4. Click on ENABLE APIS AND SERVICES and search for Cloud Translation API.
5. Go to “Credentials” Tab
6. Click on “Create credentials”
7. Choose “API key”

But still the translation doesn't work. I tested my API key on google chrome and it works.
The key have no restriction.

### Steps to reproduce:

1. Activate auto-translate and select a target language:
![image](https://user-images.githubusercontent.com/42721509/57093056-cee63180-6d04-11e9-8775-c46509cb022c.png)

2. When people send you messages they don't get translated:
![image](https://user-images.githubusercontent.com/42721509/57093132-fdfca300-6d04-11e9-81a6-d73e636d3942.png)

### Expected behavior:

The messages should appear in the target language.

### Server Setup Information:

![image](https://user-images.githubusercontent.com/42721509/57093279-5c298600-6d05-11e9-8c67-c92945c77212.png)

### Relevant logs:
None.

**Comment by marceloschmidt** [comment]
Do you have funds on Google? You need to make sure that you have enough funds in your Google developer console to use the translation API. https://console.developers.google.com/apis/api/translate.googleapis.com/quotas

**Comment by franckadil** [comment]
@marceloschmidt Hello, yes I have $300 USD for tests, and added our company billing information for backup. The api is also using no restrictions. I also disabled our firewall.  I also got no luck with the Google Auto-Translate, I am starting to think hat the issue may be related.

![image](https://user-images.githubusercontent.com/42721509/57118398-0a134f80-6d5b-11e9-8f26-1836f7da3ad3.png)

**Comment by franckadil** [comment]
Update:
![image](https://user-images.githubusercontent.com/42721509/57118498-9b82c180-6d5b-11e9-809e-a13fc69af345.png)

**Comment by marceloschmidt** [comment]
Did you try other languages?
Also, do you have access to the database, so that you can inspect the message object **after** it has been translated? It should have a `translations` property.

**Comment by franckadil** [comment]
@marceloschmidt  Thank you for taking the time I really appreciate! The error was mine, I had to activate the billing for the service to work ! There was no clear message about that, I just randomly clicked on a blue button displaying: Activate billing...

Now I have this widget on my dashboard 
![image](https://user-images.githubusercontent.com/42721509/57118843-dbe33f00-6d5d-11e9-8e6a-3249a4c97f99.png)

And the translation works:
![image](https://user-images.githubusercontent.com/42721509/57118921-45634d80-6d5e-11e9-80b2-3e50148f4f51.png)

**Comment by marceloschmidt** [comment]
Awesome! I'm glad it works.
