### ISSUE TITLE
Federations not working

### ISSUE THREAD

**Issue by r3dsn0wz** [RocketChat/Rocket.Chat#14365]
### Description:

Configured as per the documentation:
enabled flag is set to True
Status is: Running
Domain: Domain name of the Rocket chat server
Discovery Method is set to: DNS

When now executing FEDERATION_Test_Setup this error message pops up:
`Error
Could not find your server using your setup, please review your settings.`

But furthermore the whole Federation Discovery seems rather strange to me.
How are multiple servers supposed to talk to each other when neither of them knows of the other, since neither has the others hostname/IP?
I was only able to find minimal information on Github/Documentation about this.

### Steps to reproduce:

1. Install Rocket Chat as per the documentation
2. Configure Federation as per the documentation
3. Click Test_Setup in the Federation config settings

### Expected behavior:

Succeed

### Actual behavior:

Error is displayed
`Error
Could not find your server using your setup, please review your settings.`

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Ubuntu 18.04 Server
- Deployment Method: Manual Install Ubuntu as per Documentation
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.12

### Relevant logs:

`I20190503-08:03:34.100(0) Meteor ➔ method FEDERATION_Test_Setup -> userId: ZF8kw693Apb5YZpvS , arguments:  []`
`I20190503-08:03:34.103(0) Federation ➔ Peer Client.info propagateEvent: png`
` I20190503-08:03:34.104(0) Federation ➔ DNS.info searchPeer: DOMAINNAME`
`I20190503-08:03:34.113(0) Federation ➔ HTTP.info Sending request: POST - https://chat.DOMAINNAME:80/api/v1/federation.events`
`I20190503-08:03:34.133(0) Federation ➔ HTTP.info Trying to update local DNS cache for peer:DOMAINNAME`
`I20190503-08:03:34.134(0) Federation ➔ DNS.info updatePeerDNS: DOMAINNAME`
`I20190503-08:03:34.135(0) Federation ➔ DNS.info getPeerUsingDNS: DOMAINNAME`

**Comment by geekgonecrazy** [comment]
> https://chat.domainname:80/

Is it actually saying :80 here?  My guess is this is what’s wrong.  Https:// is generally :443

**Comment by roterschnee** [comment]
It is actually saying this, which is definitely not right.
It seems this is now fixed as in the new setup i did it correctly send a POST to
https://chat.DOMAINNAME:443/api/v1/federation.events

Despite this Federation is still not working and the Test_Setup returns an error with this in the log:

`May  7 07:06:57 rocket-chat-nits rocketchat[460]: #033[34mFederation ➔ HTTP.info#033[39m Sending request: POST - https://DOMAINNAME:443/api/v1/federation.events`
`May  7 07:06:59 rocket-chat-nits rocketchat[460]: #033[34mFederation ➔ HTTP.info#033[39m Retry: could not fulfill the request`
`May  7 07:06:59 rocket-chat-nits rocketchat[460]: #033[34mFederation ➔ Peer Client.info#033[39m [png] Event could not be sent to peer:n-its.eu`

**Comment by geekgonecrazy** [comment]
Are these valid ssl certs or self signed?  It could now be an issue of self signed.  But looks like having an issue now talking to a peer

**Comment by roterschnee** [comment]
The Certificates are LetsEncrypt and vaild and not self signed. Not sure what else could cause this issue

**Comment by geekgonecrazy** [comment]
@r3dsn0wz did you manage to get it?

**Comment by renatobortolin** [comment]
I'm also having problems with federation, in my case it does not even register the host in hub.rocket.chat, is it normal even in DNS mode to fetch the host in hub.rocket.chat?

I20190513-13:39:27.141(-3) Federation ➔ Peer Client.info propagateEvent: png 
I20190513-13:39:27.143(-3) Federation ➔ DNS.info searchPeer: xxxxxx 
I20190513-13:39:27.150(-3) Federation ➔ DNS.info updatePeerDNS: xxxxxx 
I20190513-13:39:27.152(-3) Federation ➔ DNS.info getPeerUsingDNS: xxxxxx 
I20190513-13:39:27.168(-3) Federation ➔ DNS.info getPeerUsingHub: xxxxx 
I20190513-13:39:27.175(-3) Federation ➔ HTTP.info Sending request: GET - https://hub.rocket.chat/api/v1/peers?search=xxxxxx 
I20190513-13:39:27.624(-3) Federation ➔ DNS.info Could not find peer for domain xxxxxx 
I20190513-13:39:27.626(-3) Federation ➔ Peer Client.info Could not find valid peer:xxxxxx

**Comment by geekgonecrazy** [comment]
@alansikora maybe you have troubleshooting step you can aid here?

**Comment by TimmiORG** [comment]
Hi @r3dsn0wz 
please check your SRV config. I guess you have configured port 80 there. Please change this to port 443.
Best regards
Timmi

**Comment by bubbapizza** [comment]
Where did you even see those federation logs?  I am having the same issue but I installed rocketchat using snaps.

**Comment by debugdjblade** [comment]
Guys, I'm trying to get RC federate on two separate domains. Having some issues and need input. 
Like the OP point out how does two servers actually communicate when we are using DNS for discovery with SRV record. 

Configured as per the documentation:
enabled flag is set to True
Status is: Running
Domain: Domain name of the Rocket chat server  << Is this for RC server @another domain????
Discovery Method is set to: DNS

Please provide input if anyone has been able to get this up and running.

**Comment by reetp** [comment]
> Please provide input if anyone has been able to get this up and running.

Github is for Issues, not support.

https://rocket.chat/docs/getting-support

https://open.rocket.chat/channel/federation
