### ISSUE TITLE
Delete My Chat History

### ISSUE THREAD

**Issue by ShoaibCubix** [RocketChat/Rocket.Chat#14368]
Hi,

I am trying to find a solution to be able to delete chat from direct-room but only for the user deleting the chat. All the solutions I found delete the chats for both user which is not appropriate. If I want to delete a chat it shouldn't be deleted from the other user. Any help in this regard will be highly appreciated.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

The option is called Prune Messages but you will be able to see it if you have the permission `clean-channel-history`


Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
