### ISSUE TITLE
roles visible when they should not be visible

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#14364]
### Description:

role labels are visible - but not everybody sees them - despite "hide roles" being true in settings

### Steps to reproduce:

1. set "hide roles" to true in settings
2. have most users still see them. it's not clear why the flag is honored for some people but not all

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.1
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4 - x64 
- MongoDB Version: 3.4.18

**Comment by evant89** [comment]
Fixed in ver.1.0.2

**Comment by MarcosSpessatto** [comment]
@sinteur can you please test it again?

**Comment by sinteur** [comment]
I've asked those of the team who saw it (oddly my account did not) if it was fixed. Looks like it was, indeed, fixed.

**Comment by MarcosSpessatto** [comment]
@sinteur can we close this?

**Comment by sinteur** [comment]
Yep. Thx team!
