### ISSUE TITLE
Web client loads all assets at once and crashes the server

### ISSUE THREAD

**Issue by facundomedica** [RocketChat/Rocket.Chat#14377]
### Description:

If a user had talked to thousands of users, then the client tries to load all of those users' avatars at once (in the network tool of Chrome I can see all the requests being launch at the same time) even when those avatars aren't being displayed.
This does 2 things:
1. crash the server (because of all the requests I suppose)
2. makes the web client slow (it is unusable in most cases, depending on the computer)

### Steps to reproduce:

1. Make a user talk to 10k other users (APIs are useful for this)
2. Access the web client.

### Expected behavior:

To not crash the server and not lag the web client that much.

### Actual behavior:

Server crash and really slow web client

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Linux
- Deployment Method: Kubernetes (docker)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.9

**Comment by ggazzo** [comment]
Hi @facundomedica I made few tests here, and seems the lazy load it working... could you provide me more informations? could you send me a image with your assets loaded(chrome devtools network)..

**Comment by facundomedica** [comment]
Hey @ggazzo thanks for reaching out.

I had to close lots of direct messages (around 9k, using the API `im.close`) so it wouldn't be that bad. But here you can see that it loaded around a thousand images without even having to display them.

![Screen Shot 2019-05-06 at 14 38 53](https://user-images.githubusercontent.com/14063057/57232768-d7907d80-700c-11e9-9b53-c98c38b32b6c.png)

![Screen Shot 2019-05-06 at 14 42 01](https://user-images.githubusercontent.com/14063057/57233023-62717800-700d-11e9-9ea3-180533355b2f.png)
