### ISSUE TITLE
how to Theme/skin the sidebar 

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#14375]
### Description:

Theming has yet to actually be resolved. It is not clear what values need to be changed to modify the color of the text in the sidebar. For example, have a peek at my instances theme: 

It's still rather confusing how to theme/skin Rocket Chat. 

![image](https://user-images.githubusercontent.com/23088/57159098-1e833680-6db3-11e9-91b7-b33617d37040.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Ubuntu 16.04
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog:  1
- NodeJS Version: 8
- MongoDB Version: 3.2

**Comment by flayks** [comment]
I agree. It's still a big pain in the *ss to customize the sidebar and other elements. I had to so force !important replaces in CSS for variables and custom items like the active channel text.
A system like Slack with a few **_clearly identifiable_ color codes** would be awesome!

**Comment by tripout** [comment]
I was able to do this somewhat by replacing the :root css values with my own and adding !important.  Took some time going through the CSS in chrome dev tools to see what referenced what and make the changes.

:root {
  --sidebar-item-text-color: #FFFFFF !important;
  --sidebar-item-unread-color: #1976d2 !important;
  --sidebar-footer-height: 70px !important;
  
}
div .announcement {
  background-color: #1976D2 !important;
}
div .powered-by {
  display: none !important;
}
div .switch-language {
  display: none !important;
}

**Comment by robbyoconnor** [comment]
I shouldn't have to do that when they have theming functionality in the application but at some point broke it and I was hoping by 1.0.0 they'd have it fixed, but nope.

**Comment by tripout** [comment]
> I shouldn't have to do that when they have theming functionality in the application but at some point broke it and I was hoping by 1.0.0 they'd have it fixed, but nope.

I agree that you shouldn't have to, I think this has to do with a larger issue of some values being over written, I was just saying that is what I have done to get it to work in the meantime.

**Comment by robbyoconnor** [comment]
That type of thing is finicky -- I used to be bugged by it but I got used to it... it's been an annoyance for a while now

**Comment by robbyoconnor** [comment]
This is better but still not 100% fixed: 
![image](https://user-images.githubusercontent.com/23088/60319033-22f74600-9943-11e9-8009-72f0193bccca.png)

The types should also be Black, not grey.
