### ISSUE TITLE
RocketChat update on Heroku fails w Mlab Mongo database on a shared plan 

### ISSUE THREAD

**Issue by bayareacoder** [RocketChat/Rocket.Chat#14383]
- attempted to update RocketChat on Heroku from 0.66 to current 1.02
- update failed with console messaging stating ‘could not check Mongo version’ and then a message to add a role to Mongo user database to allow the checking of the Mongo cluster. The suggested Mongo shell command in the console log shows an update is needed to the ‘admin’ database. 
- when on a non-dedicated shared plan for Mlab hosted Mongo (which is any plan below $200 per month), per Mlab doc, you do not have access to the admin db. 
- as a result database migration failed and it seems we are stuck on the 0.66 version

This issue together with the boot time issue (https://github.com/RocketChat/Rocket.Chat/issues/10213#issuecomment-489374288) make it not workable to use Heroku I believe.

**Comment by geekgonecrazy** [comment]
#14403 should fix this
