### ISSUE TITLE
Email Alerts showing from as undefined after upgrade to 1.0.2

### ISSUE THREAD

**Issue by pageb018** [RocketChat/Rocket.Chat#14392]
### Description:

After upgrading to 1.0.2 direct message email alerts are showing as "undefined" in the from field. 

### Steps to reproduce:

1. Update to rocketchat 1.0.2

### Expected behavior:
In the past when a direct message was delivered via email, the from address would display the users full name and the smtp email address set in the Rocketchat configuration.. 

for instance 

From: Brian Page <chat@buildamerica.com)

![Screen Shot 2019-05-06 at 11 48 12 AM](https://user-images.githubusercontent.com/26354599/57237318-f256f800-6ff4-11e9-9203-d3914618ba18.png)

### Actual behavior:

After updating to 1.0.2 the email messages now shows as 

undefined <chat@buildamerica.com>

![Screen Shot 2019-05-06 at 11 48 08 AM](https://user-images.githubusercontent.com/26354599/57237325-f71bac00-6ff4-11e9-9f3a-53fd72509a77.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: ubuntu 16.04.6
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.9

### Additional context

No other changes have been made to SMTP settings and/or Office 365 settings. We are using Amazon SES to send smtp alerts. 

### Relevant logs:

No errors in logs.

**Comment by pageb018** [comment]
This may be related by emails now say "bpage sent you a message" as opposed to "Brian Page sent you a message." It seems like real name isn't being pulled in correctly for emails. However real names show correctly in user lists and in conversations list.

**Comment by evanstoner** [comment]
We are seeing this in 1.0.1.

**Comment by antaflos** [comment]
Same here on 1.0.2. Additionally the email's subject is missing the name of the user (neither real name nor nickname/alias).

The subject now shows `You have been direct messaged by` instead of `You have been direct messaged by Firstname Lastname`. And if a message has been posted to a channel the subject says `has posted a message in #somechannel` instead of `Firstname Lastname has posted a message in #somechannel`.

**Comment by dasfreak** [comment]
bug still existing in 1.0.3.

**Comment by iamalisajid** [comment]
Still existing.

**Comment by qasim-arbisoft** [comment]
Has this issue been resolved in 1.1 release?

**Comment by pageb018** [comment]
> Has this issue been resolved in 1.1 release?

No. It has not.
