### ISSUE TITLE
Current Chat

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#14395]
Description:
I can not find in the report by name only by attendant and situation

Server Setup Information:

Version of Rocket.Chat Server: 1.0.1
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.15.0
MongoDB Version: v3.6.10

**Comment by geekgonecrazy** [comment]
I’m afraid I don’t understand issue.  Please include screenshots and steps to reproduce as required by issue template

**Comment by josep112** [comment]
<img width="1280" alt="Captura de Tela 2019-05-07 às 09 26 26" src="https://user-images.githubusercontent.com/12038013/57299228-6a332a00-70aa-11e9-8098-712896b78739.png">
This image shows the report data on the screen

<img width="1280" alt="Captura de Tela 2019-05-07 às 09 24 14" src="https://user-images.githubusercontent.com/12038013/57299332-a4043080-70aa-11e9-8938-e99eced5dd60.png">

In this image, I typed José Sanchez and did not find the ticket with the name

**Comment by geekgonecrazy** [comment]
@renatobecker idk if aware of this one or not.

**Comment by josep112** [comment]
I made a video to show how not locate by name, other fields work

![bugchat](https://user-images.githubusercontent.com/12038013/57878734-0f5baa00-77f1-11e9-8e9a-b88878e32a10.gif)

**Comment by josep112** [comment]
Now that I have seen the area of livechat, I will close here and open this problem

**Comment by renatobecker** [comment]
Hi @josep112 
Sorry for the late response.. Did you update your server version to our latest release?
We have made important improvements on the Current Chats feature so I would like to know if you have tested it on the new version.

Thanks.

**Comment by renatobecker** [comment]
> Hi @renatobecker
> Yes, I did tests in 1.0.3, and in older versions also what I think is that by name it never worked because all the versions I tested are with the same problem

Okay. I'll take a look at this case and I'll update you ASAP.

**Comment by josep112** [comment]
This is a very important function, thank you for your commitment!

**Comment by josep112** [comment]
Hi, @renatobecker 
thanks, now it works perfectly
