### ISSUE TITLE
[FG-VD-19-050] Rocket.Chat is vulnerable to Cross-Site Scripting

### ISSUE THREAD

**Issue by tsug0d** [RocketChat/Rocket.Chat#14406]
### Description:

Rocket.Chat is vulnerable to Cross-Site Scripting reflected in command
Tracking Case #: FG-VD-19-050

Fortinet's FortiGuard Labs have discovered a security issue in your Rocket.Chat product. We estimate its risk to 3, on a scale of 1 (lowest) to 5 (highest), in terms of its impact. Please advise of the appropriate contact person in your company to handle this issue.

### Steps to reproduce:

1. Any chat room/direct message
2. paste this:
```
/<img/src='x'/onerror='alert(1)'>aaa</img>
```
3. enter

### Expected behavior:

No such command: `/<img/src='x'/onerror='alert(1)'>aaa</img>` 

### Actual behavior:

XSS

### Server Setup Information:

- Tested on https://open.rocket.chat/ & local server

**Comment by wreiske** [comment]
On a side note, at least this only applies to the local user and isn't executed on other user's browsers.

**Comment by dhoeld** [comment]
At least on our internal setup (0.74.3) it's not reproducible by the steps above. I got:

No such command: `/<img/src='x'/onerror='alert(1)'>aaa</img>`

**Comment by tsug0d** [comment]
Here mine:
- Version	0.74.3
- Apps Engine Version	1.4.0
- Database Migration	137
