### ISSUE TITLE
Rocket Chat on Amazon Marketplace?  Consulting available?

### ISSUE THREAD

**Issue by tacman** [RocketChat/Rocket.Chat#1440]
What a very cool project Rocket.Chat is!  Is this available in the Amazon Marketplace?  I see this:

http://thecloudmarket.com/image/ami-bac32289--rocket-chat

but not sure it's active or official.

We're looking to deploy this somewhere but don't want to deal with any of the maintenance.  The support we need is related to using the API to create projects or channels and enrolling new members when they sign up via our system.  I'm pretty sure once it's set up with can figure it out, but may need help with security and such.

Where can we go to get paid hosting and possibly some basic support?

**Comment by Sing-Li** [comment]
@tacman Thanks!  Hosting service is now in early access.  Please contact @engelgabriel for an instant trial - takes 2 minutes.  Additional consultation services specific to your installation are also available.

**Comment by tacman** [comment]
@engelgabriel -- I sent an email to the gmail address on your github profile, is there a better way to reach you? -Tac (tac@survos.com)

**Comment by engelgabriel** [comment]
Hi!

I am sorry for the delay. I was away for most of the day yesterday. I'll
get back to you this afternoon when I get to the office.

Best,

Gabriel Engel

On Friday, 20 November 2015, tacman <notifications@github.com> wrote:

> @engelgabriel <https://github.com/engelgabriel> -- I sent an email to the
> gmail address on your github profile, is there a better way to reach you?
> -Tac (tac@survos.com <javascript:_e(%7B%7D,'cvml','tac@survos.com');>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/1440#issuecomment-158388084>
> .
>


-- 
Sent from Mobile

**Comment by geekgonecrazy** [comment]
Looks like this is mainly about consulting. Closing.
