### ISSUE TITLE
Version 1.0.2 can't install apps

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#14417]
### Steps to reproduce:

1.  Go to Administration
2. Click on Marketplace
3. In any App details page
4. Click on the Free button
![image](https://user-images.githubusercontent.com/42721509/57332397-96829100-7112-11e9-838e-8f6b4a0dbe16.png)

### Expected behavior:

User should be able to install the App.

### Actual behavior:
![image](https://user-images.githubusercontent.com/42721509/57332232-4277ac80-7112-11e9-9350-586797e2feaf.png)

![image](https://user-images.githubusercontent.com/42721509/57332656-1c9ed780-7113-11e9-8bca-cf7224f4f88b.png)

![image](https://user-images.githubusercontent.com/42721509/57333035-e1e96f00-7113-11e9-8a69-f387ff5844b9.png)

Request URL that results in the Bad request error: [redacted.com]/api/apps?buildBuyUrl=true&appId=09a2b0d8-94d0-433d-a53e-3961a3bb0205

**Comment by d-gubert** [comment]
@geekgonecrazy this looks like something related to the cloud, right?

**Comment by franckadil** [comment]
@d-gubert  @geekgonecrazy  I have been able to replicate this on an other instance and it seems that if you don't follow the Rocket Cloud on-boarding emails to link the app, you can't get access to the Marketplace. While mentioned during the first installation, what happened to me is that I changed the  site host-name and domain so I lost my initial connection. And since few days I haven't been able to get a new email, the request button doesn't work for some reason. I am waiting for the Support input on this one to get a new key. The other alternative if it takes too long will be to recreate a new server from scratch which I am trying to avoid.

**Comment by Venomen** [comment]
Why this is closed? This is related to all self-instances rocket chat versions. I emailed also cloud support about it.

**Comment by geekgonecrazy** [comment]
If you hit sync in the cloud connectivity page it should ensure that your site url is properly updated and that you have a valid token.  If your workspace is registered and you deleted the follow up email or something you can goto https://cloud.rocket.chat and use the forgot password link with the email you registered with to reset that password.

We will be working on an FAQ page for our docs with little things like this.  If you have any other problems with this definitely shoot us an email to support and we can help resolve.

**Comment by Venomen** [comment]
> If you hit sync in the cloud connectivity page it should ensure that your site url is properly updated and that you have a valid token. If your workspace is registered and you deleted the follow up email or something you can goto https://cloud.rocket.chat and use the forgot password link with the email you registered with to reset that password.
> 
> We will be working on an FAQ page for our docs with little things like this. If you have any other problems with this definitely shoot us an email to support and we can help resolve.

Ok, so If I will do it (enter my token) I will have still access to mobile pushes and marketplace without having paid cloud license (I am using standalone rocketchat version) ?

**Comment by franckadil** [comment]
@Venomen yes should be able too. In my case I am stuck because I didn't receive the key as a changed my instance domain name. That's why I closed the issue, I's not related to rocket.chat instance It's related to the cloud service and support is supposed to send a new key so I am  waiting.

**Comment by geekgonecrazy** [comment]
> Ok, so If I will do it (enter my token) I will have still access to mobile pushes and marketplace without having paid cloud license (I am using standalone rocketchat version) ?

@Venomen correct. You don't need a license for your self hosted workspace.  If in the future you choose to get an enterprise license you would be able to manage it through there (and it would keep license updated)
