### ISSUE TITLE
New Live Chat

### ISSUE THREAD

**Issue by mikeaer** [RocketChat/Rocket.Chat#14410]
Hi
When I try acces new live chat on an public IP, nothing appear in web interface
Is an error in console: try to acces some resources on private IP, 
Rocket Chat
CentOS 7 
Version 1.0.2
MongoDB 3.6
OPLog enabled
Server is installed on an private IP who has NAT o publicIP port 3000
![newlivechat2](https://user-images.githubusercontent.com/34124588/57296855-b005e780-70d6-11e9-928d-168f680a8c13.PNG)
![newlivechat1](https://user-images.githubusercontent.com/34124588/57296856-b005e780-70d6-11e9-93b1-fa2cfbe76e55.PNG)

**Comment by renatobecker** [comment]
@mikeaer.
The communication between the server and the new Livechat client works through the REST API approach. As you can see on your browser console, you're blocked by CORS, did you enabled it on your server?

**Comment by mikeaer** [comment]
After enabling CORS on apache server, we have this error
Firefox can’t establish a connection to the server at ws://.........ro:3000/sockjs/301/qm49_s8s/websocket. livechat.js:63:17884
The connection to ws://........ro:3000/sockjs/301/qm49_s8s/websocket was interrupted while the page was loading.

**Comment by renatobecker** [comment]
> After enabling CORS on apache server, we have this error
> Firefox can’t establish a connection to the server at ws://.........ro:3000/sockjs/301/qm49_s8s/websocket. livechat.js:63:17884
> The connection to ws://........ro:3000/sockjs/301/qm49_s8s/websocket was interrupted while the page was loading.

When I mentioned `server`, I was trying to say `Rocket.Chat server`.

**Comment by realrafael** [comment]
Settings > General > Rest API > Enable CORS
Try it ;)

**Comment by mikeaer** [comment]
it works
Thank you

**Comment by realrafael** [comment]
Glad to help!

**Comment by jeremysu0131** [comment]
Works for me, too. Remember to restart the server after setting the CORS.
