### ISSUE TITLE
A new Owner can not send messages to group or channel

### ISSUE THREAD

**Issue by mfurgiuele** [RocketChat/Rocket.Chat#14414]
When a new owner is added to an existing public or private channel/Group, it can not send messages to that group. 
I currently have version 1.0.2 and the event is as follows. 
Could you help me with this?

I20190507-10:59:49.330(-3) server.js:199 System ➔ error Error sending message: { Error: [You_have_been_muted]     at canSendMessage (app/authorization/server/functions/canSendMessage.js:18:9)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:81:17)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43   isClientSafe: true,   error: 'You_have_been_muted',   reason: undefined,   details: undefined,   message: '[You_have_been_muted]',   errorType: 'Meteor.Error' }

**Comment by Hudell** [comment]
#11311 should fix this.

**Comment by mfurgiuele** [comment]
Thank.
I am not a developer, could take a few steps to implement this fix.
For the installation of my Rocket.Chat in Ubuntu, use this package, rocket.chat-1.0.2.tar
from https://releases.rocket.chat/latest/download.

Thank you so much.

**Comment by mfurgiuele** [comment]
Solved,
When you assign a new owner to the channel or group, the possibility of sending messages is activated, but it does not work until you un-mute it.

**Comment by mfurgiuele** [comment]
Solved,
When you assign a new owner to the channel or group, the possibility of sending messages is activated, but it does not work until you un-mute it.
