### ISSUE TITLE
Sending long text as attachment in an E2E chat results in encrypted file

### ISSUE THREAD

**Issue by fchiacchiaretta** [RocketChat/Rocket.Chat#14427]
### Description:

When pasting long text (an html) in the message field and sending as attachment (i.e. answer yes to the request of sending it as attachment), downloaded file is encrypted and not readable.

### Steps to reproduce:

1. Paste long text in the message field and hit Send button
2. Answer yes to "send as attachment" request
3. Fill file name and description
4. Download file, it is encrypted

### Expected behavior:

1. Paste long text in the message field and hit Send button
2. Answer yes to "send as attachment" request
3. Fill file name and description
4. Download file, it is readable

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: CentOS 7.6
- Deployment Method: offical docker image
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.12

### Additional context

Sending attachment via drag and drop results in a properly readable file (not encrypted at all in file storage, as expected by current E2E implementation).

Best,
Federico Chiacchiaretta

**Comment by aiac** [comment]
Anyone know how to decrypt file? I lost a lot of work because of that issue
