### ISSUE TITLE
Custom Script for Logged Out Users seems looped

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#14436]
### Description:

Hi I try to use "Custom Script for Logged Out Users" feature. My goal is to logout from Keycloak oauth during logout from Rocekt Chat.

My code looking like this:

`window.location.href = "https://(my keycloak url)/logout?redirect_uri=(my rocket chat url)";`

After logout redirect works but is looping infinity, refresh page without end.

Ther is any possibility to run this code once?

### Steps to reproduce:

1. Go to Administration -> Layout -> Custom Scripts
2. Paste code to move another page and redirect to Rocket Chat page

### Expected behavior:

Script is run only once.

### Actual behavior:

Redirect is looping infinity

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.1
- Operating System: Centos 7
- Deployment Method: docker compose
- Number of Running Instances: 9
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4 - x64 
- MongoDB Version: 4.0

**Comment by MarcosSpessatto** [comment]
@emikolajczak I opened a PR to update the descriptions of custom scripts. Please see https://github.com/RocketChat/Rocket.Chat/pull/14516#issuecomment-492828191.
