### ISSUE TITLE
Domain Whitelist is not working

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#1443]
I pulled the latest docker version. Reproduction-Steps

Admin->Accounts->Registration
Allowed Domain List: gmail.com

Still possible to register new users using yahoo.com or any other domain.

**Comment by geekgonecrazy** [comment]
@miscs did you happen to restart the docker image after?  This might be one of these things that requires a restart.

**Comment by stevenmirabito** [comment]
I can confirm that the whitelist doesn't appear to do anything, on a fresh install from today. I set registrations to be limited to my organization's domain and test@test.com can still register.

**Comment by miscs** [comment]
yes I did a restart my docker image but still whitelist has no effect...

**Comment by geekgonecrazy** [comment]
Let me see if I can replicate this, then we'll go from there.

**Comment by geekgonecrazy** [comment]
@miscs I get internal server error is this what you guys get or it lets you fully register and login?

**Comment by geekgonecrazy** [comment]
I didn't notice this until now but this is duplicate of #1360
