### ISSUE TITLE
server.js:199 System ➔ error

### ISSUE THREAD

**Issue by xewn** [RocketChat/Rocket.Chat#14437]
5/9/2019 4:37:16 PMLocalStore: store created at
5/9/2019 4:37:16 PMLocalStore: store created at
5/9/2019 4:37:16 PMLocalStore: store created at
5/9/2019 4:37:17 PMSetting default file store to GridFS
5/9/2019 4:37:21 PMWarning: connect.session() MemoryStore is not
5/9/2019 4:37:21 PMdesigned for a production environment, as it will leak
5/9/2019 4:37:21 PMmemory, and will not scale past a single process.
5/9/2019 4:37:30 PMufs: temp directory created at "/tmp/ufs"
5/9/2019 4:37:31 PMLoaded the Apps Framework and loaded a total of 0 Apps!
5/9/2019 4:37:32 PMUpdating process.env.MAIL_URL
5/9/2019 4:37:34 PMUsing GridFS for custom sounds storage
5/9/2019 4:37:34 PMUsing GridFS for custom emoji storage
5/9/2019 4:37:46 PM➔ server.js:199 System ➔ error
5/9/2019 4:37:46 PM➔ +---------------------------------------------------------------------------+
5/9/2019 4:37:46 PM➔ |                                SERVER ERROR                               |
5/9/2019 4:37:46 PM➔ +---------------------------------------------------------------------------+
5/9/2019 4:37:46 PM➔ |                                                                           |
5/9/2019 4:37:46 PM➔ |  Rocket.Chat Version: 1.0.2                                               |
5/9/2019 4:37:46 PM➔ |       NodeJS Version: 8.11.4 - x64                                        |
5/9/2019 4:37:46 PM➔ |      MongoDB Version: 4.0.9                                               |
5/9/2019 4:37:46 PM➔ |       MongoDB Engine: wiredTiger                                          |
5/9/2019 4:37:46 PM➔ |             Platform: linux                                               |
5/9/2019 4:37:46 PM➔ |         Process Port: 3000                                                |
5/9/2019 4:37:46 PM➔ |             Site URL: http://IP:8818                          |
5/9/2019 4:37:46 PM➔ |     ReplicaSet OpLog: Disabled                                            |
5/9/2019 4:37:46 PM➔ |          Commit Hash: abf67ce985                                          |
5/9/2019 4:37:46 PM➔ |        Commit Branch: HEAD                                                |
5/9/2019 4:37:46 PM➔ |                                                                           |
5/9/2019 4:37:46 PM➔ |  OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:  |
5/9/2019 4:37:46 PM➔ |  https://go.rocket.chat/i/oplog-required                                  |
5/9/2019 4:37:46 PM➔ |                                                                           |
5/9/2019 4:37:46 PM➔ +---------------------------------------------------------------------------+

**Comment by MIKI785** [comment]
The log itself tells you what is needed. Read the info provided here: https://rocket.chat/docs/installation/manual-installation/mongo-replicas/

**Comment by reetp** [comment]
@rocket-cat close

https://github.com/RocketChat/Rocket.Chat/pull/14227

**Comment by xewn** [comment]
你好，我问过阿里云的技术，阿里云的mongodb不支持。
这种情况，如何使用阿里云的mongodb呢？
