### ISSUE TITLE
Avatar sometimes overlays thread icon

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14447]
![image](https://user-images.githubusercontent.com/6295044/57492889-a7f1a780-7290-11e9-8346-70b3288f156b.png)
![image](https://user-images.githubusercontent.com/6295044/57492941-eb4c1600-7290-11e9-9bd8-edd624d0b4c3.png)
![image](https://user-images.githubusercontent.com/6295044/57494127-ff464680-7295-11e9-8264-ddbe1f45ce3c.png)

![image](https://user-images.githubusercontent.com/6295044/57492877-990af500-7290-11e9-885d-fe4684041c3a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat

**Comment by ggazzo** [comment]
it was a regression we already fixed... we never made a release with this bug :) any problem let me know
