### ISSUE TITLE
Using local auth when LDAP is enabled -> server crash

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#1444]
enable LDAP auth

register new local user using username / password
login with new registered user brings server down

**Comment by geekgonecrazy** [comment]
Do you have access to the server logs? We'll need a bit more information on this to be able to figure it out.

**Comment by miscs** [comment]
honestly I don´t now how to access logs inside a docker image. if you could give me a hint I am happy to re-test and post server logs...

sorry for my lacking docker knowledge...

**Comment by Sing-Li** [comment]
Take a look at the docker documentation:

https://docs.docker.com/engine/reference/commandline/logs/

A lot more good information there. If you decide to use docker deploy for production - definitely get to know the commands.

**Comment by geekgonecrazy** [comment]
@miscs yes check out docker's docs.  Its good to be familiar with it as a resource if you're going to use docker.  I could tell you, but honestly its not helping you.

**Comment by miscs** [comment]
got it, thanks. I will re-test and provide log details here. thx

**Comment by Megatronic79** [comment]
similar to this issue?

https://github.com/RocketChat/Rocket.Chat/issues/1491

**Comment by geekgonecrazy** [comment]
@Megatronic79 looks like it might be.

@miscs can you provide the logs? or is this resolved?

**Comment by miscs** [comment]
Hi,
sorry for the late reply. I think it´s the same reason as #1491
I provided server and samba logs there, so closing this one here.

Thanks
Steve
