### ISSUE TITLE
Unread message bar shows above flextab

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14448]
### Description:

The unread message bar has a z-index that is higher than the contextual-bar flextab.

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/57493255-2c90f580-7292-11e9-8f20-452d26728edb.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/57493185-ec317780-7291-11e9-9cf4-a66978c57b66.png)

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat

**Comment by ggazzo** [comment]
thanks @wreiske but actually this bug was fixed  :)

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/14443
