### ISSUE TITLE
Menu icon not appear in history page when resolution less than 768!!!

### ISSUE THREAD

**Issue by hosseinsmart** [RocketChat/Rocket.Chat#1445]

**Comment by hosseinsmart** [comment]
hi
when i resize the browser to the small size in history page, menu icon on the top left not shown!!

**Comment by geekgonecrazy** [comment]
@hosseinsmart can you include a screenshot?  I don' think i've ever seen this.

**Comment by hosseinsmart** [comment]
sure
this is other page with menu icon:
![image](https://cloud.githubusercontent.com/assets/12068783/11359053/bda682e4-928d-11e5-8dca-0b6814acd8d5.png)

and this is history page without menu icon:
![image](https://cloud.githubusercontent.com/assets/12068783/11359069/e29e4f32-928d-11e5-967f-e8e4d5daeb0b.png)

**Comment by geekgonecrazy** [comment]
@hosseinsmart I was able to reproduce this.  For sure an issue.  Thanks for reporting!
