### ISSUE TITLE
Rocketchat 1.0.3 little green OTR Key Icon is missinng

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#14477]
### Description:

Since upgrading from 0.74.3 to 1.0.3 the sweet little green key icon is missing, indicating the messages are protected by OTR. OTR itself works.

### Steps to reproduce:

1. Start OTR conversation
2. Enter message
3. No green key icon

### Expected behavior:

Green key icon shows you are in a OTR session.

### Actual behavior:

No green key icon.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 8.12.0
- MongoDB Version: 3.6

**Comment by myura** [comment]
I went through the same upgrade path, and the OTR message green key icon no longer appears for me as well - hopefully this wasn't an intentional change, since having the icon is a perfect indicator for if you're sending/receiving messages in an OTR session or not.

**Comment by geekgonecrazy** [comment]
Does this still work for e2e mode?  If so might be a clue as to what’s happening

**Comment by Zuko** [comment]
Same issue _(noticed yesterday)_

**Comment by mddvul22** [comment]
This is impacting us, also.  What needs to be done to get this addressed?  While OTR is working, I believe you can argue this is a security issue, as users are losing trust in Rocket Chat to protect their OTR sessions, as they can't verify that an OTR session is actually established.

**Comment by AmShaegar13** [comment]
This issue persists in v1.1.2.

**Comment by gdressman** [comment]
We also are seeing the same behavior

**Comment by cortex3** [comment]
We're experiencing this issue in v1.2.1 as well.

**Comment by myura** [comment]
thanks @ggazzo, hopefully this gets merged into a release soon
