### ISSUE TITLE
Messages UX - Ability to not display username every message in channel

### ISSUE THREAD

**Issue by jdean65** [RocketChat/Rocket.Chat#14474]
**Problem**
Displaying the username every time a message is sent/received breaks up the flow/easy ability to read the message conversation.

**Describe the solution you'd like**
1.  For Direct Message channels, remove username from every message.  Use color and alignment to distinguish sent vs received messages and stop the breaks generated by display of usernames for every message (like WhatsApp). 
2.  For Group channels, "them" username should be displayed to user, but reduced significantly in size and visibility so as to minimize the disruption to the message thread.  "Us" username should not be displayed (all this is like WhatsApp UI).

**Describe alternatives you've considered**
Alternative is current user interface.

**Additional context**

![Screenshot_20190512-114737](https://user-images.githubusercontent.com/159204/57594964-6adb1e80-74f7-11e9-8e1a-941c3df4ccf4.png)
![Screenshot_20190512-205045](https://user-images.githubusercontent.com/159204/57595019-c1485d00-74f7-11e9-93f5-ac03412d3d84.png)

**Comment by reetp** [comment]
@rocket-cat close

This isn't a bug but a feature request.

Did you not look at what happens in threading when you spoke to me originally ?

![Screenshot_2019-05-13_10-51-54](https://user-images.githubusercontent.com/3800384/57608463-43bf3400-756d-11e9-96f5-9482e966baf5.png)


Please reopen in feature-requests if necessary.

https://github.com/RocketChat/feature-requests
