### ISSUE TITLE
Custom css dont work

### ISSUE THREAD

**Issue by zpavlig** [RocketChat/Rocket.Chat#14475]
Hello, updated rocket chat version to 1.0.3 with 0.74.3

Custom css not rewrite default rules:

> flex: 0 0 20%;
    width: 20%;
    max-width: 20%;

my css styles:

>.sidebar {
	flex: 0 0 var(--sidebar-width);
	width: var(--sidebar-width);
	max-width: var(--sidebar-width);
}

Version 0.74.3 - work
Version 1.0.3 - not work

![Capture](https://user-images.githubusercontent.com/35609094/57599588-0d87b180-7579-11e9-992f-d35bdb1627f5.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Centos 7
- Deployment Method: docker
- Number of Running Instances: 3
- MongoDB Version: 4.0.3
- Screen resolution: 1920x1080

**Comment by ybshin** [comment]
Me too.... custom CSS doesn't work on 1.0.3 version.

the CSS follow 'var'

.rc-table-title {
    white-space: nowrap;
    color: **var**(--rc-color-primary);
}

**Comment by tripout** [comment]
You need to add !important to get it to work. Like this.

.rc-table-title {
white-space: nowrap;
color: var(--rc-color-primary);
color: #000000 **!important**;
}

Specifying the **!important** part in the CSS will force those values to be used.

**Comment by ybshin** [comment]
> You need to add !important to get it to work. Like this.
> 
> .rc-table-title {
> white-space: nowrap;
> color: var(--rc-color-primary);
> color: #000000 **!important**;
> }
> 
> Specifying the **!important** part in the CSS will force those values to be used.

Oh thx~!

All of my custom CSS is working~! :)

**Comment by zpavlig** [comment]
thx! my CSS is working too
