### ISSUE TITLE
Zapier could not connect

### ISSUE THREAD

**Issue by Cruaier** [RocketChat/Rocket.Chat#14476]
Hi there,
trying to set up Zapier is running into a problem which seems to be on RCs site (see screenshot).

### Expected behavior:

Should not run into a timeout..

### Actual behavior:

![image](https://user-images.githubusercontent.com/5204940/57607869-323e5200-7596-11e9-949c-a40bcff39456.png)

Log:
`
I20190513-08:38:59.545(0) [OAuth2Server] GET /oauth/authorize?response_type=code&client_id=zapier&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2FRocketChatDevAPI%2F&state=1557736739.3438500 
I20190513-08:39:01.164(0) [OAuth2Server] POST /oauth/authorize?response_type=code&client_id=zapier&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2FRocketChatDevAPI%2F&state=1557736739.3438500 
I20190513-08:39:01.166(0) [OAuth2Server] POST /oauth/authorize?response_type=code&client_id=zapier&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2FRocketChatDevAPI%2F&state=1557736739.3438500 
I20190513-08:39:01.167(0) [OAuth2Server] in getClient (clientId: zapier , clientSecret: null ) 
I20190513-08:39:01.175(0) [OAuth2Server] in saveAuthCode (code: e25911746e85960cb48f308e753181f9e00120ab , clientId: zapier , expires: 2019-05-13T08:39:31.175Z , user: { id: 'qLXEQepz4MAyu4frw' } ) 
I20190513-08:39:04.131(0) [OAuth2Server] POST /oauth/authorize?response_type=code&client_id=zapier&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2FRocketChatDevAPI%2F&state=1557736739.3438500 
I20190513-08:39:04.133(0) [OAuth2Server] POST /oauth/authorize?response_type=code&client_id=zapier&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2FRocketChatDevAPI%2F&state=1557736739.3438500 
I20190513-08:39:04.134(0) [OAuth2Server] in getClient (clientId: zapier , clientSecret: null ) 
I20190513-08:39:04.140(0) [OAuth2Server] in saveAuthCode (code: eb06fa4de3067f95a119c73b52e38619ffa280fc , clientId: zapier , expires: 2019-05-13T08:39:34.140Z , user: { id: 'qLXEQepz4MAyu4frw' } ) 
`

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Ubuntu 16.04
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.7

I somehow doubt that this is a general problem, anyway I'm being thankful about the right hint to solve this problem.

**Comment by dudanogueira** [comment]
Hi!
We just updated our Zapier docs and confirmed it working properly in 4.5.x
please, check it out:
https://docs.rocket.chat/guides/administration/admin-panel/integrations/zapier
