### ISSUE TITLE
Messages UX - Display sent vs received messages in different colors, with different alignments ("message bubbles")

### ISSUE THREAD

**Issue by jdean65** [RocketChat/Rocket.Chat#14473]
**Problem:**
Messages are not delineated clearly enough in terms of a message sent versus message received.  User experience for Rocket.chat messaging app is not in line with what WhatsApp and FB Messenger users (2.8 billion and counting) have now become accustomed to.

**Describe the solution you'd like**
Different coloring for a sent versus received message. Sent messages should align right in the chat window, received messages should align left.  For direct message channels at least. This is essentially a movement towards the (basically ubiquitous) UX of whatsapp and fb messenger.

Describe alternatives you've considered
Alternative is current user interface.

Additional context
![Screenshot_20190512-114737](https://user-images.githubusercontent.com/159204/57594164-a2e06280-74f3-11e9-94d5-98df32c766e4.png)

**Comment by reetp** [comment]
@rocket-cat close

Duplicate of

https://github.com/RocketChat/feature-requests/issues/114

This isn't a bug but a feature request, and please don't open multiple Issues on the same subject.

Note that your PoV is entirely subjective. Whatsapp/FB apps have a UI style forced on them by the makers. Their UI doesn't have any real bearing on their popularity and doesn't make it 'right'.

(Personally I hate Whatsapp but it is forced on me by other users - I'd rather not use the spyware at all quite frankly - and have never used FB apps.)

Rocket is based on a different UI style (because there is more than one, and no 'right' one) - see more corporate systems like Slack, Discourse etc.

Kind of related to comments here:

https://github.com/RocketChat/Rocket.Chat/issues/9681

As I said in your original question in open.rocket.chat, if you want to see changes in Rocket then Pull Requests with code are always welcome.

**Comment by jdean65** [comment]
Hi John...A lot to unpack here.  I get that it is likely annoying when
someone "just off the street" starts pushing for a UI/UX change that there
has likely been a lot of thought about and work done.  In an attempt to
address all your points/questions:

Note that your PoV is entirely subjective. Whatsapp/FB apps have a UI style
forced on them by the makers. Their UI doesn't have any real bearing on
their popularity and doesn't make it 'right'.
(Personally I hate Whatsapp but it is forced on me by other users - I'd
rather not use the spyware at all quite frankly - and have never used FB
apps.)
Rocket is based on a different UI style (because there is more than one,
and no 'right' one) - see more corporate systems like Slack, Discourse etc.
I would push back on the perspective that any suggestion that Rocket.chat
needs better delineation of sent versus received messages is "subjective"
(I have seen you reply in this way to others also).

What is important to accept is that, as of 2018, WhatsApp has *1.5 billion
monthly users*; FB Messenger has* 1.3 billion.  *All of whom have now
become accustomed to the "chat bubble"/offset alignment/different coloring
UI.  Your assertion is a little like saying the iPhone and Android were
"forced" on everyone and that doesn't make them "right" compared to the
Microsoft Zune.  The UI battle happened a long time ago and you (and the
85,000 paying Slack customers) lost.

Kind of related to comments here:
#9681
"Bubbly and childish" is what 2.8 billion monthly users are expecting when
they send chat messages via their phone.

This isn't a bug but a feature request.
Completely agree and apologies for the duplication.  I think I started in
the right place, but got turned around by the many "feat" tags that exist
on https://github.com/RocketChat/Rocket.Chat/issues.  It gave me the
impression that a bug on that list was only a bug when tagged "bug" and
other items (including feature requests) can/should reside there.

Did you not look at what happens in threading when you spoke to me
originally ?
If I understand you correctly yes, I did read your reply and responded.

There are a number of Issues on this type of subject.
Thank you for taking the time to provide the links to the other folks who
have flagged this UI need.  They did not show in the auto-population of
title, else I would have just commented on those.

As I said in your original question in open.rocket.chat, if you want to see
changes in Rocket then Pull Requests with code are always welcome.
Understood and thank you.

Regards,

Jonathan.

**Comment by ErdinErkazan** [comment]
<img width="1910" height="974" alt="Image" src="https://github.com/user-attachments/assets/153c09a1-3970-471e-8fa4-d49d0e787ee0" />
