### ISSUE TITLE
MacOS client sending out random video call requests

### ISSUE THREAD

**Issue by blue928** [RocketChat/Rocket.Chat#14489]
We setup a private channel for a client for communication.  She has latest version of rocket chat client and MacOSX as of the time of this writing. The RC client was loaded in from the desktop version of the AppStore.

When the user is away from her computer and the computer is in Sleep mode, her channel sends out random video conference requests. 

I've had her uninstall and reinstall the RC Client, but it still happens. This is only happening in one channel (her channel). Any thoughts as to what could be causing this?

![screen shot 2018-05-14 at 9 21 08 am](https://user-images.githubusercontent.com/6431043/40001317-f956658a-575b-11e8-9795-9ec39711731e.png)

**Comment by franckadil** [comment]
I can reproduce the same error on v1.0.2 docker deployment.
