### ISSUE TITLE
Query Not Working For /api/v1/channels.members

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#14487]
i am trying to filter the api results to only show online users, it's still returning all users not only online users. see below.

``apiUri + '/api/v1/channels.members?roomId=' + roomId +'&count=0&query={ "status": { "$eq": "online" } }'``

**Comment by MarcosSpessatto** [comment]
@ubergeekzone sorry, our docs are wrong, I'll update this now. This endpoint does not support the `query` query parameter. To get the online members list, you can use https://rocket.chat/docs/developer-guides/rest-api/channels/online/.

**Comment by ubergeekzone** [comment]
prefect, ty
