### ISSUE TITLE
Rocket.Chat does not support Emoji URLs

### ISSUE THREAD

**Issue by yahesh** [RocketChat/Rocket.Chat#14491]
### Description:

When posting an Emoji URL (e.g. of the newest Cisco vulnerability Thrangrycat: https://😾😾😾.fm) Rocket.Chat does not identify the URL as such and thus also doesn't provide a preview.

### Steps to reproduce:

Send the valid Emoji URL https://😾😾😾.fm in a message.

### Expected behavior:

The Emoji URL is identified as a valid URL, is made clickable and generates a preview.

### Actual behavior:

The Emoji URL is not identified as a valid URL, is not made clickable and does not generate a preview.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 16.04
- Deployment Method: tar

### Additional context

None.

### Relevant logs:

None.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
