### ISSUE TITLE
Joined Channels yet "Must Join to View Messages" Banner in all channels

### ISSUE THREAD

**Issue by jimDKE** [RocketChat/Rocket.Chat#14498]
### Description:

May be similar to https://github.com/RocketChat/Rocket.Chat/issues/14425

regular Users see the banner message "You must join to view messages in this channel" in all public channels despite already having joined the channel and having sent messages in the channel.  

-The user is able to both see messages in that channel as well as that banner message.
-Discussions, private groups, and direct conversations do not display this banner message.
-Leaving and re-joining the room does not make the message disappear.
-The messages appear in public channels when users have logged in via the Electron client (v2.15.3), Firefox (v66.0.5) and Chrome (v74.0.3729.131).
-Restarting the server does not alleviate the problem.
-Assigning Users the "Preview Public Channel" permission makes the banner instantly disappear from all public channels.

### Steps to reproduce:

1. Update RocketChat server (deployed via snap) from 0.74.3 to 1.0.3
2. Log in as a regular user that doesn't have the "Preview Public Channel" permission.  Join a public channel.  Look at the top of the channel's chat area for the banner message "You must join to view messages in this channel".
3. Confirm that joining the channel and sending messages in the channel does not make the banner message disappear.

### Expected behavior:

The banner message "You must join to view messages in this channel" should not be visible once a user has joined the channel.

### Actual behavior:

The banner message "You must join to view messages in this channel" IS still visible once a user has joined the channel.

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.3
- Operating System: Ubuntu x64 4.15.0-39-generic
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: 3.4.20

**Comment by iMaciaveller** [comment]
I have the same problems

**Comment by zdumitru** [comment]
This will be fixed in version `1.0.4` by this already merged pr #14461 .

**Comment by iMaciaveller** [comment]
I gave users the right to leave the channel ([ID: leave-c], [ID: leave-d]) and it helped.

**Comment by jimDKE** [comment]
Thanks for the info @zdumitru!  I re-posted your info in https://github.com/RocketChat/Rocket.Chat/issues/14510 since that issue seems similar to what I encountered.

**Comment by ggazzo** [comment]
is it still an issue?  any problem open again please.

**Comment by jimDKE** [comment]
Right @ggazzo, this is no longer an issue for us.
