### ISSUE TITLE
[BUG] Untitled Discussions

### ISSUE THREAD

**Issue by peterkogit** [RocketChat/Rocket.Chat#14499]
### Description:

Untitled discussion is created.

### Steps to reproduce:

1. Create a discussion
2. Select a channel
3. Insert a space in the title
4. Click create

### Expected behavior:

Will not allow to create a channel

### Actual behavior:

![1](https://user-images.githubusercontent.com/31727004/57759327-6cc4fd80-7702-11e9-82e7-85f045086801.jpg)

How can it be removed now?

**Comment by MarcosSpessatto** [comment]
@peterkogit you can delete in the `Room Info` tab, there is a `Delete` button.
![Screenshot from 2019-05-15 10-27-56](https://user-images.githubusercontent.com/15324204/57779292-32f0f880-76fc-11e9-9d1f-383c9f74933c.png)
