### ISSUE TITLE
Mailer broken version 1.0.3

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#14494]
### Description:

Verification emails and Mailer don't work. 
SMTP email test works.

### Steps to reproduce:

1. User register a new account
2. Admin send email trough Administration > Mailer

### Expected behavior:
All emails sent.

### Actual behavior:

- No registration email is sent
- Using Administration > Mailer displays this error message: **Internal Server Error**.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: 1.4.2
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled 1
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.9

### Relevant logs:

```
I20190514-04:34:43.216(0) server.js:199 System ➔ error Error sending message: { Error: A Rocket.Chat App prevented the message sending. [error-app-prevented-sending]     at sendMessage (app/lib/server/functions/sendMessage.js:160:10)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:87:11)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43   isClientSafe: true,   error: 'error-app-prevented-sending',   reason: 'A Rocket.Chat App prevented the message sending.',   details: undefined,   message: 'A Rocket.Chat App prevented the message sending. [error-app-prevented-sending]',   errorType: 'Meteor.Error' } 
I20190514-04:35:31.469(0) Checking: checkPreMessageSentPrevent 
I20190514-04:35:31.475(0) Checking: executePreMessageSentPrevent 
I20190514-04:35:31.516(0) Checking: checkPostMessageSent 
I20190514-13:11:08.161(0) Exception while invoking method 'Mailer.sendMail' TypeError: Cannot read property '0' of undefined     at app/mail-messages/server/functions/sendMail.js:46:37     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)     at Object.sendMail (app/mail-messages/server/functions/sendMail.js:45:38)     at MethodInvocation.Mailer.sendMail (app/mail-messages/server/methods/sendMail.js:18:17)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

```

**Comment by MarcosSpessatto** [comment]
@franckadil does your server have any app installed?

**Comment by franckadil** [comment]
@MarcosSpessatto Thank you for your reply! It did, but when I saw the logs I deactivated all the apps when I saw this` [error-app-prevented-sending] ` .  And it still doesn't work.

**Comment by d-gubert** [comment]
The log related to the app states that some app prevented _a message_ to be sent, not an email, so it shouldn't be a problem.

I checked the file mentioned by the log `app/mail-messages/server/functions/sendMail.js:46:37`, and it looks like _either_ the user does not have a proper email configured _or_ there is a bug in user creation that is not following the expected schema.

I'm not the best one to investigate this and not sure who is, so I'll leave it to @RocketChat/core to decide 😬

**Comment by franckadil** [comment]
Let me know guys if you want access to the platform to run some tests or if you want me to do specific tests for you. I'll be glad to help!

**Comment by neonfly** [comment]
Same here
v1.0.3

SMTP Testmail works
No notifications are send >>> the log says the RocketChat doesn't even try it.

**Comment by franckadil** [comment]
New logs tested in version 1.0.2:

`I20190520-15:24:29.465(0) Exception while invoking method 'Mailer.sendMail' TypeError: Cannot read property '0' of undefined     at app/mail-messages/server/functions/sendMail.js:46:37     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)     at Object.sendMail (app/mail-messages/server/functions/sendMail.js:45:38)     at MethodInvocation.Mailer.sendMail (app/mail-messages/server/methods/sendMail.js:18:17)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 `
