### ISSUE TITLE
A user reported he can't scroll through the list of channels via More Channels, in Chromium 41

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#145]

**Comment by AdrianoCahete** [comment]
Chromium itself or Chrome?

Chrome 45.0.2424.0 canary works good here.

**Comment by sampaiodiego** [comment]
is this fixed by #161 ?

**Comment by AdrianoCahete** [comment]
Isn't primary  idea, but can be. @marceloschmidt can you ask to user try with new version again?

**Comment by marceloschmidt** [comment]
I believe it's fixed now. Let's close it and reopen if needed.
