### ISSUE TITLE
[BUG] 'Jump to message' and 'Get link' links shown twice

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#14501]
### Description:

Menu with the list of actions of the threaded reply shows 'Jump to message' button twice.

### Steps to reproduce:

1. Write a message in the channel
2. Click 'Reply in Thread' button on above the message
3. Write and submit something.
4. Click threaded reply so that the right panel is opened.
5. In the right panel, on the threaded reply message click three dots settings menu

--> Menu contains two 'Jump to message' links.

### Expected behavior:

Menu should contain only one 'Jump to message' link.

### Actual behavior:

![image](https://user-images.githubusercontent.com/11751017/57772430-a94e2480-7715-11e9-9a45-3c576af1d785.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.20

### Additional context

Both buttons behave correctly, do the same and what it supposed to do - jump to the message in the main middle panel view.

**Comment by reetp** [comment]
Yup - can confirm on 1.0.3
Also on open.rocket.chat
