### ISSUE TITLE
jitsi : multiple invitation

### ISSUE THREAD

**Issue by Sicoval31** [RocketChat/Rocket.Chat#14508]
Hi,
when starting a jitsi video call with another users, each minutes, a notification in rocket chat invites us to join the room ... for all the members of the discussion/channel, evene if we are already in the video room

![image](https://user-images.githubusercontent.com/42040529/57783504-84b27680-772e-11e9-91c3-1faa96e4dc90.png)

**Comment by for7raid** [comment]
+1


Version	1.0.2
Apps Engine Version	1.4.2
Database Migration	143
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	3.10.0-862.el7.x86_64
Node Version	v8.11.3
Mongo Version	4.0.9
Mongo Storage Engine	wiredTiger

**Comment by Shaltz** [comment]
+1
same problem here, start happening yesterday

version = 1.0.3
revision = 1377
OS = ubuntu 18.04@x64 (intel xeon 8175m)
Install Type = SNAP
Cloud Provider = AWS

**Comment by franckadil** [comment]
I can reproduce this in version 1.0.2

**Comment by Shaltz** [comment]
any news ??? kinda really annoying

**Comment by Sicoval31** [comment]
Try to use the jitsi server instead of mine : same problem
Try different options : same problem
-------
**RC params for jitsi :**
**_SSL_** : Yes
**_New window_** : yes
**_Activate in channel_** : NO
-------
RC :1.0.3
apps engine 1.4.2
ubuntu 18.04 x64
node 8.11.3
mongo 3.4.20
install by snap

**Comment by Shaltz** [comment]
no one else has faced this issue ??
to follow up, resrating the snap or even the server doesn't solve the issue
It's seems to happen mostly (at least for me) only with one specific user, 
that user can spam me 20/30 times in a day
others may occasionally spam me at random, but just a couple of time ... very bizzare

**Comment by TriPhoenix** [comment]
Maybe it is related to issue #14489 which was closed recently with #14496? We still do encounter the same issue with 1.0.0 but will test 1.1.0 soon

**Comment by franckadil** [comment]
This bug is particularly annoying for users...

Can reproduce on:

Version | 1.1.3
Apps Engine Version: 1.4.2
Database Migration: 147
Mongo version: 4.0.10
Mongo Storage Engine: wiredTiger
Node version: v8.11.4

![image](https://user-images.githubusercontent.com/42721509/60291762-ee23c880-991b-11e9-8b34-473f21e982e6.png)

**Comment by orc90lvl** [comment]
same thing. 
RC 1.1.3
SNAP
jitsi on another VM.

**Comment by orc90lvl** [comment]
may be trouble with /sanp/rocketchat-server/1384/programs/web.browser/packages/rocketchat_videobridge/client/public/external_api.js

ready: function (callback) {
       if (ready) {
          callback();
       } else {
          setTimeout(function () { postis.ready(callvack); }, 50);
}
},

i cant change dat timeout even i stop services

**Comment by reetp** [comment]
This is probably merged into develop.

Please test on either latest stable 1.2.1 or on latest develop from git so you can tell whether it has been fixed or not.

https://rocket.chat/docs/contributing/reporting-issues

> 2. Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

You can spin up a VM in no time to test this sort of thing.

Thanks.

**Comment by orc90lvl** [comment]
Find solution! In my case trouble was in date.time. Between server and client was above 40sec difference. And every time when server time wasnt equal clients time server sends "click-to-join" message

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/16601
