### ISSUE TITLE
Filename encoding problem with REST method rooms.upload

### ISSUE THREAD

**Issue by SomebodyOdd** [RocketChat/Rocket.Chat#14500]
### Description:

rooms.upload API method fails to correctly process non-English characters in filenames

### Steps to reproduce:

1. Call rooms.upload method API with a filename for example "Новый текстовый документ (2).txt" (Russian characters in there)

### Expected behavior:

File should be sent as normal

### Actual behavior:

File sents with wrong filename
![изображение](https://user-images.githubusercontent.com/19632145/57759534-cdecd100-7702-11e9-9b6d-2bd5d4ce4846.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 3.4.20

**Comment by MarcosSpessatto** [comment]
@igor523 the name of the field that you are sending is `file`, right? The filename that is in Russian, right?

**Comment by igor523** [comment]
@MarcosSpessatto yeah, that's right.

**Comment by igor523** [comment]
Here is C# code (if it can help you somehow)
```c#
               var form = new MultipartFormDataContent();
                client.DefaultRequestHeaders.Add("X-Auth-Token", token);
                client.DefaultRequestHeaders.Add("X-User-Id", userId);
                var streamContent = new StreamContent(fileStream);
                streamContent.Headers.Add("Content-Type", _mime.Lookup(fileFullPath)); //Lookup for mime type, based on file extension. For txt it goes for text/plain

                form.Add(streamContent, "file", fileName ?? Path.GetFileName(fileFullPath));
                
                if (text != null) form.Add(new StringContent(text), "msg"); //In example, msg field is not set
                if (fileDescription != null) form.Add(new StringContent(fileDescription), "description"); //Same here

                var result = await client.PostAsync($"http://{_hostname}:{_port}/api/v1/rooms.upload/{roomId}", form);```

**Comment by MarcosSpessatto** [comment]
@igor523 did you try do this upload via e.g postman, by chance? :thinking: Because I did the upload via postman, to try to simulate the error, and the file was uploaded.

**Comment by igor523** [comment]
@MarcosSpessatto yes. I looked into raw request that Postman sent - it's application/x-www-form-urlencoded, while c# code uses multipart/form-data as Content-Type, so i think it's not apples to apples comparison. I can't use same thing in c#, because it supports string data only, not files.

Strange thing is, i explicitly set body type to form-data in Postman, but it's still uses x-www-form-urlencoded for some reason, weird 🤔
![изображение](https://user-images.githubusercontent.com/19632145/57812498-e813c700-7775-11e9-96ed-7c2e0e90a5cf.png)

**Comment by igor523** [comment]
Postman request goes well and file sents as expected, though. But, hey, this request differs with official docs at least with Content-Type...
https://rocket.chat/docs/developer-guides/rest-api/rooms/upload/#rooms-upload
By the way, looks like Rocket client uses some other way to upload files, whics is not in docs... Is it outdated?

**Comment by MarcosSpessatto** [comment]
Rocket client sends the files through Meteor's DDP Protocol (Websocket).

**Comment by igor523** [comment]
Weird... That's gonna be really hard, but i try to dump raw http request, that C# code does, maybe it could help?

**Comment by MarcosSpessatto** [comment]
Yes, if you can send, this will help.
