### ISSUE TITLE
error exception in rocket.chat 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#14517]
### Description:

There are TypeError exceptions in the logs. They occurred first after updating Rocket.Chat from 0.74.3 to 1.0.3.

### Expected behavior:

No errors.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Amazon Linux 2
- Deployment Method: Docker Container on Kubernetes
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.12

### Relevant logs:

```
Exception in defer callback: TypeError: Cannot read property 'ls' of undefined
    at Meteor.defer (server/methods/readMessages.js:25:81)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at packages/meteor.js:620:25
    at runWithEnvironment (packages/meteor.js:1356:24)
```

**Comment by reetp** [comment]
If you don't properly fill in a template then no one will help you.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by dhoeld** [comment]
Opened a new issue https://github.com/RocketChat/Rocket.Chat/issues/14540. Therefore this issue might be closed.

**Comment by reetp** [comment]
Why?? Now you have created a duplicate.
As they appear similar I'd follow up on this and close 14540 unless you have evidence they are different bugs.

**Comment by dhoeld** [comment]
As far as I understood you don't look into this issue as long as it's not properly filled in a template. Therefore I created a properly filled in template. But then I will close #14540.
