### ISSUE TITLE
[BUG] I'm a channel member, however the system shows me the message "You must be logged to view posts on this channel"

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#14510]
### Description:

I'm a channel member, however the system shows me the message "You must be logged to view posts on this channel"

### Steps to reproduce:

1. Join channel
2. Open channel

### Expected behavior:

System does not show message to members: You must be logged to view posts on this channel

### Actual behavior:

System does show message to members: You must be logged to view posts on this channel

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog:  Active
- NodeJS Version: 1.4.2
- MongoDB Version: 144

![Clipboard - 15 de Maio de 2019 às 12_50](https://user-images.githubusercontent.com/17053653/57790566-62f6c680-7711-11e9-8e7a-6ceb6894df3d.jpg)

**Comment by jimDKE** [comment]
Sounds similar to what I encountered (https://github.com/RocketChat/Rocket.Chat/issues/14498) and someone else encountered too (https://github.com/RocketChat/Rocket.Chat/issues/14425).  Apparently there's a fix coming in v1.0.4 via https://github.com/RocketChat/Rocket.Chat/pull/14461

**Comment by ggazzo** [comment]
is it still an issue?  any problem open again please.
