### ISSUE TITLE
Wrong text when reporting a message

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#14514]
### Description:

Wrong text (probably missing a string) in the popup when reporting a message.

### Steps to reproduce:

1. Go to https://open.rocket.chat/channel/general
2. Click on three dots on the right side of any message
3. Click Report

--> See the text inside popup message.

### Expected behavior:

A text "Thank you!" appears inside.

### Actual behavior:
![image](https://user-images.githubusercontent.com/11751017/57803796-85accd80-7759-11e9-9372-db55f2882314.png)

A text "Thank_you_exclamation_mark" appears inside.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by tyteen4a03** [comment]
Has this been pushed to latest RocketChat cloud instances?

**Comment by sampaiodiego** [comment]
not yet.
