### ISSUE TITLE
[bug] 1.0.3 users stopped going offline:

### ISSUE THREAD

**Issue by zzeesstt** [RocketChat/Rocket.Chat#14513]
After upgrading from 0.74.3 to 1.0.3, users stopped going offline.
The server shows all the time that they are online, even if their personal computer has long been turned off.

Current version of Rocket.Chat Server: 1.0.3
Deployment Method: snap

**Comment by geekgonecrazy** [comment]
I believe this has been fixed and will be released with 1.1

**Comment by mrsimpson** [comment]
@zzeesstt Can you please add a bit more context to your bug report?
I tried to reproduce it and couldn't. I verified that my user went offline

- Once I closed the active tab on the browser
- Once I closed the lid of my laptop (and it went to sleep)

Both has been done on Windows and Mac

**Comment by zzeesstt** [comment]
@zzeesstt I have a problem when you exit from your account using the Opera browser.
Perhaps this will manifest itself in other browsers 
• Windows 10.

**Comment by mrsimpson** [comment]
>@zzeesstt when you exit from your account using the Opera browser. ...

@zzeesstt how do you „exit“? Log off, Close the tab, close the Browser, shut the los of your Laptop?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geekgonecrazy** [comment]
Please give it a try in 1.1.x and let us know if still occures.  Going to go ahead and close this out
