### ISSUE TITLE
[Feature request] Google meet integration

### ISSUE THREAD

**Issue by rjozwiak** [RocketChat/Rocket.Chat#14526]
It would be nice to have Google Meet integration that would allow to create a google meet with the everyone in the room, channel or DM. The desired integration would add button in the room panel or custom command like “/meet” that would trigger new google meet and send link to current chat.

**Comment by zdumitru** [comment]
Probably a duplicate of https://github.com/RocketChat/feature-requests/issues/65

**Comment by geekgonecrazy** [comment]
Yes this is a duplicate.  Please see rules when opening an issue.  Feature requests all live in the other repo
