### ISSUE TITLE
Rocket.Chat Service Boot-up can't start

### ISSUE THREAD

**Issue by liangguangji** [RocketChat/Rocket.Chat#14528]
When the service is normal, the client will not be able to connect for several hours.
Restart the computer, the service can not start properly.The log is as follows:
----------------------------------------------------------------------------------

XXXX@rocketserver:~$ systemctl status rocketchat.service
â— rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendo
   Active: failed (Result: exit-code) since Thu 2019-05-16 17:25:29 CST; 
  Process: 1164 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (c
 Main PID: 1164 (code=exited, status=1/FAILURE)

May 16 17:25:29 rocketserver rocketchat[1164]:     at Connection.emit (ev
May 16 17:25:29 rocketserver rocketchat[1164]:     at Socket.<anonymous> 
May 16 17:25:29 rocketserver rocketchat[1164]:     at Object.onceWrapper 
May 16 17:25:29 rocketserver rocketchat[1164]:     at emitOne (events.js:
May 16 17:25:29 rocketserver rocketchat[1164]:     at Socket.emit (events
May 16 17:25:29 rocketserver rocketchat[1164]:     at emitErrorNT (intern
May 16 17:25:29 rocketserver rocketchat[1164]:     at _combinedTickCallba
May 16 17:25:29 rocketserver rocketchat[1164]:     at process._tickCallba
May 16 17:25:29 rocketserver systemd[1]: rocketchat.service: Main process
May 16 17:25:29 rocketserver systemd[1]: rocketchat.service: Failed with 

------------------------------------------------------------------------------------
How do I troubleshoot？thanks

**Comment by reetp** [comment]
@rocket-cat close

No evidence of a bug.

For support please ask.in the forums or https://open.rocket.chat #support
