### ISSUE TITLE
REST API for setting online/offline state

### ISSUE THREAD

**Issue by RSchlaeger** [RocketChat/Rocket.Chat#14523]
Hey all, 
We are currently developing a web application and are using RocketChat for intra-app communication. When looking through the API we stumbled upon an oddity:

There is a REST API-Call to get a users status (offline/online/away etc.) but no call to set a users status (the own status). This is only possible with the Live API, or are wemissing something in the docs?
Is it possible to set a users status without using the Live-API?

This would be a great feature for us, since it would mean decoupling this logic from the websocket. 

Many thanks for your reply!

**Comment by r-souza** [comment]
I would really like this functionality too! I am developing a script and I stopped at this point, I did not find a way to set the user status through the REST API. 

Thank you for your attention.
