### ISSUE TITLE
About obtaining old version of RocketChat

### ISSUE THREAD

**Issue by tamo26** [RocketChat/Rocket.Chat#14539]
I created the latest RocketChat, but the mobile app communication is not working.

RocketChat v1.0.3

I also want to build an older version of RocketChat to see the same features.
How do I get an older version of RocketChat?

**Comment by reetp** [comment]
@rocket-cat close

This seems to be support issue, not a bug. Please follow up in the forums or #support (you asked a question in #general but never waited for a reply)

Please read the documentation and check the tags/releases.
