### ISSUE TITLE
Group By Type gets stuck

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat#14532]
In the web client on my mac, I am able to group chatrooms by type but then when I try to undo this setting I am unable to.

**Comment by bizzbyster** [comment]
this issue has been reproduced by another user

**Comment by reetp** [comment]
This works on my 1.0.3 but fails on open.rocket.chat - presumably the current dev version

Not sure what @babybyster was testing on?

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/14488
