### ISSUE TITLE
Issue with "require e-mail verification"-setting

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#1454]
I've got an instance running with a bunch of already registered users and when I turned on "e-mail verification" the other night I ran into issues. The e-mails arrive and all, no problem there. The problem is the following: on an instance which holds already created accounts -- all of whom were created prior to changing the *_"require e-mail verification"_*-setting -- results in the following behaviour as reported by several users:
> I was unable to login yesterday... The application was forcing me to do email verification, and it did not work. I would get the email, click the link, and try to sign in, only to be sent back to the email verification step.

I can confirm this behaviour.

**Comment by graywolf336** [comment]
What would be the expected route for this? Would people who were registered before hand be verified automatically? Or would it send out an email to everyone who already has an account?

**Comment by geekgonecrazy** [comment]
I would almost assume that existing ones would be verified automatically.

**Comment by tholu** [comment]
+1 for this issue.
I registered the admin user, enabled "require e-mail verification", logged out and cannot login again. It says it sends a login verification email, but it does not show up in the logs.

**Comment by marceloschmidt** [comment]
Yes, this is a bug and @geekgonecrazy is right, we should probably automatically verify e-mails for existing users, or at least verify the ones for admin users. For a temporary fix while we don't fix this in our code, please go into your database and set the administrator email as verified. If you're running through meteor run §
`db.users.update({ roles: 'admin' }, {$set: { "emails.$.verified": true } }, false, true)`

**Comment by marceloschmidt** [comment]
Yes, this is a bug and @geekgonecrazy is right, we should probably automatically verify e-mails for existing users, or at least verify the ones for admin users. For a temporary fix while we don't fix this in our code, please go into your database and set the administrator email as verified. If you're running through meteor run `meteor mongo` and then
`db.users.update({ 'roles.__global_roles__': 'admin' }, {$set: { "emails.$.verified": true } }, false, true)`.

**Comment by marceloschmidt** [comment]
Verification e-mail link works now.
