### ISSUE TITLE
Edge does not update or refresh in v 1.0.3

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14553]
### Description:

Rocket Chat does not update in Edge browser. Rocket Chat loads, all looks fine, but nothing updates unless you refresh the browser window manually. I see this has been an issue since v73. I am making a new bug report because this is a much newer version and the problem still persists. As Edge browser being the default browser on windows 10, I feel that this should get more attention.

Also, when starting a private message, it often gets the "to many requests" error.

### Steps to reproduce:

1. Open Edge Browser
2. Login To Rocket Chat
3. Watch as no message, typing notifications etc are not received.

### Expected behavior:

Rocket Chat to operate as intended.

### Actual behavior:

Rocket Chat Does Not Update.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Centos 7
- Deployment Method: manual tar install
- Number of Running Instances: 3
- DB Replicaset Oplog: yes

**Comment by ggazzo** [comment]
hey, @serviceman I'm quite confident we fixed your problem here: https://github.com/RocketChat/Rocket.Chat/pull/14551 :) please let me know if worked :)

**Comment by serviceman** [comment]
When should this be added to a release?

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/releases/tag/1.1.0-rc.0 next release

**Comment by serviceman** [comment]
I will test it and let you know.

**Comment by serviceman** [comment]
This seems to be working fine in Edge browser for me now. I'll let you know if any users report any issues.

**Comment by serviceman** [comment]
I have had reports of Edge still freezing up. Other than that, Edge is at least usable.

**Comment by serviceman** [comment]
I will close this for now as it seems to have solved all of my known issues with Edge browser after updating to 1.1.0
