### ISSUE TITLE
Can we remove /tmp/snap.rocketchat-server... folder?

### ISSUE THREAD

**Issue by trongthaonh** [RocketChat/Rocket.Chat#14556]
I installed rocket chat via snap and day after day, the server to run out of disk space. 
How can I clean up the temp files and logs files correctly?

![Image of Yaktocat](https://doc-0o-54-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6i26m66hmptk0vna5aqcn88l32rhbq2e/1558346400000/07228623754817687722/*/1qyysK-EZJyaVaCfRsJg5I9z5XvJjfmY4?e=view)

Can we remove these files above?

Thanks in advance!!!

**Comment by reetp** [comment]
@rocket-cat close

You need to ensure you have sufficient space for Rocketchat, including the space for downloading updates, any uploaded files eg images etc.

I'm not sure cleaning out a few temp files and logs is going to help you here.

Pleased ask in the forums or open.rocket.chat #support for recommended disk space - I would suggest probably several Gb minimum.

(If you are running it on a Pi ask in https://open.rocket.chat/channel/raspberrypi )
