### ISSUE TITLE
wrong emoji parser

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat#14563]
if I post this 
Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4

Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS 😵 AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 comes

**Comment by ggazzo** [comment]
sorry man but its impossible to avoid that kind of situation, please use  your text wrapped by "`", any problem let me know
