### ISSUE TITLE
Issues logging in with IOS/MacOS

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14566]
Updated this with more information. 

Please understand that the I have gathered as much information from my users as possible to generate this report. My users are not tech people and have limited knowledge of browsers/OS etc terminology.

I am getting reports of Rocket Chat hanging at "three dots" when loading. This issue has been reported in Safari and Chrome on Mac. Makes sense it would also happen on Chrome because Mac Chrome is based on Safari. I have had some users have luck with Chrome by logging in under incognito mode.

I am also getting reports from my users that safari is having rendering issues on IOS. I finally got an IOS version from one of my users. he reports it as 10.3.3. I have attached an image below of this rendering issue.

The above issues seemed to have started with the 1.0.3 update, I updated from 0.72 a few days ago.

I have asked my users to also test on open.rocket.chat and those that have have reported the same issues on open.rocket.chat

![screen](https://user-images.githubusercontent.com/40190297/58140065-92269f80-7c0b-11e9-8cbc-41c012d0ecd8.JPG)

Version of Rocket.Chat Server: 1.0.3
Operating System: Centos 7
Deployment Method: manual tar install
Number of Running Instances: 3
DB Replicaset Oplog: yes

**Comment by geekgonecrazy** [comment]
@gazzo I think the css change you were working on for safari would fix this one as well?

**Comment by serviceman** [comment]
This issue seemed to have been resolved as of 1.1.0. I'll reopen if it appears in current versions after updating. Thank you for the fix.
