### ISSUE TITLE
Restrict non-admin members from creating public channels

### ISSUE THREAD

**Issue by jonathanhartman** [RocketChat/Rocket.Chat#1457]
I would like to restrict non-admin members from creating public channels in order to keep the conversations focused on certain topics. Is there a way to do this?

Thanks,
Jonathan
##

**Comment by brakhane** [comment]
This is possible in the latest Rocket.Chat versions. You just need to remove the `create-c` right from the users group.

**Comment by Rohlik** [comment]
We can close this.

**Comment by WandrLust** [comment]
I know this is super old, but can anyone please provide more details on how to do what @brakhane is referring to?

**Comment by brakhane** [comment]
> I know this is super old, but can anyone please provide more details on how to do what @brakhane is referring to?

It's been ages since I've used RC, but basically just remove the "create channel" permission from the "user" role. It was called "create-c" back in the day, no idea what it's called now, or if it changed.

**Comment by WandrLust** [comment]
Thank you.  Someone else eventually found it.  I didn't notice that I had
to click the Next button at the bottom to see the rest of the settings.
Stupid oversight on my part.  Thanks for getting back to me just the same.
