### ISSUE TITLE
[Regression] No action menu for starred messages

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#14571]
On open.rocket.chat of today I cannot open a context menu of a message after I starred it:
Frontend exception

```
Uncaught TypeError: t.starred.find is not a function
    at Object.condition (84a29c513473043f4dfcef3b21fa1e280d62d32f.js:283)
    at Object.condition (84a29c513473043f4dfcef3b21fa1e280d62d32f.js:5)
    at 84a29c513473043f4dfcef3b21fa1e280d62d32f.js:283
    at Array.filter (<anonymous>)
    at Object.getButtons (84a29c513473043f4dfcef3b21fa1e280d62d32f.js:283)
```

Was there not an automated UI test for that some time ago?

**Comment by ggazzo** [comment]
sorry @mrsimpson but I'm not able to reproduce your code, could you provide with version of rocket.chat is running? its very weird, because we have tests for star messages 🤔

**Comment by mrsimpson** [comment]
Yup, I've seen that test run a couple of times, so I tested on open once more:
Only starred messages *in direct message channels* are affected.

**Comment by Hudell** [comment]
I couldn't replicate the error either, even on direct messages.

**Comment by mrsimpson** [comment]
Interesting - I can't reproduce it anymore either - not even with the very same message which failed earlier...
