### ISSUE TITLE
Deactivating a user will keep the account status online

### ISSUE THREAD

**Issue by grahhnt** [RocketChat/Rocket.Chat#14577]
### Description:
Deactivating an online user will keep their status as online

### Steps to reproduce:

1. Suspend online user

### Expected behavior:
Set their status to offline

### Actual behavior:
The account stays online

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 3.4.20

**Comment by geekgonecrazy** [comment]
@sampaiodiego did your change to fix logout presence also fix this?

**Comment by sampaiodiego** [comment]
I'm not sure, I couldn't reproduce the issue.

@granttoday did you **Deactivate** the user from `Admin > Users` page? You used two terms (suspend and deactivate) so I'm not sure what exactly you did =)

**Comment by granttoday** [comment]
@sampaiodiego sorry, it was deactivate =) if the user is online while they get deactivated, their status doesn't get reset to offline

**Comment by sampaiodiego** [comment]
When I deactivate an user, it is logged out and set to offline:

![smx5t-hbpib](https://user-images.githubusercontent.com/8591547/58182552-2fbdb580-7c84-11e9-883c-109e852d9b89.gif)

**Comment by geekgonecrazy** [comment]
I think your fix in 1.1.0 must fix it

**Comment by MarcosSpessatto** [comment]
@granttoday can you please test it again?

**Comment by pauloriply** [comment]
Same behaviour for deactivated user

Version
5.3.0
Apps Engine Version
1.35.0
Node Version
v14.14.0
Database Migration
281 (November 1, 2022 18:53)
MongoDB
5.0.8 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (eb122008e)
Branch: HEAD

**Comment by mike-kfed** [comment]
I just deactivated a user on rocket.chat 5.4.0 and the user stayed online too, this bug is not fixed (or re-appeared).
