### ISSUE TITLE
Can't delete users button is missing

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#14588]
### Description:
The delete button does't show up anymore:
![image](https://user-images.githubusercontent.com/42721509/58171470-0013ab00-7c8e-11e9-9a1d-97834d6050fb.png)

The roles are not displayed correctly, users have the owner role while they're not owners:

![image](https://user-images.githubusercontent.com/42721509/58171615-4cf78180-7c8e-11e9-95e4-ebd3568e5057.png)

### Steps to reproduce:

1.  Activate and Desactivate Webrtc (not sure but I could notice a change when doing that, and instead of the edit button I had block user button.

### Expected behavior:

This is the normal display:
![image](https://user-images.githubusercontent.com/42721509/58171753-9b0c8500-7c8e-11e9-8391-14db93cf3796.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: activated
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.9

**Comment by franckadil** [comment]
I have deleted a pending conversation with rocket.cat from Admin > Rooms  and now The normal display is back again ... I will keep the issue open, to see if the issue doesn't come back

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
