### ISSUE TITLE
Create Windows Phone mobile app - Create Windows Universal App

### ISSUE THREAD

**Issue by Martinspire** [RocketChat/Rocket.Chat#1459]
So i'm currently looking in what apps we can and cannot use for chatting with a community i'm hosting. And Rocket Chat seems to mark lots of checkboxes. Unfortunately, i will need to support Windows Phone/Mobile users. And i can't seem to find a client for it. Now i know i could contribute one (but i'm not that experienced i'm afraid), but here's me saying: you guys need to build one.

Its fairly simple: a solution like this needs to be able to serve as much users as it can get. Seeing there's a Firefox app out there, there is some room for it. I cannot give an advice to use this if it locks certain people out. Now of course they could use web or use a different device, but i'd like them to be able to use it everywhere and now it simply isn't.

Another benefit for a universal app, would be that its possible to run it on Xbox One or even Continuum for phones (soon). So could i interest somebody on to make this (or perhaps assist)?
##

**Comment by jreinert** [comment]
:+1:

**Comment by jiangming1399** [comment]
i need the windows mobile app too.

**Comment by HammyHavoc** [comment]
Would love to see this too.

**Comment by SoubaK** [comment]
Hi
I'm re-opening this issue because I started using rocket.chat and a Windows Phone app is missing.
I want to create this app but I need help cause I'm not ver experimented in codin for windows phone.
If anyone is intrested, contact me :)
SoubaK, a newbie willing to help

**Comment by NioTeX** [comment]
👍

**Comment by rasos** [comment]
We are working on a Windows Phone app with the rocket.chat cordova framework. It still needs some tweaking, e.g how it stores files, creates directories, shows notifications, but expect something very soon.
We would need help with integrating the Microsoft push notifications service to be integrated in Rocket.Chat, similar to APN for iOS and GCM for Android. Here is a starting point: https://msdn.microsoft.com/en-us/library/windows/apps/ff402558%28v=vs.105%29.aspx

**Comment by joeleaver** [comment]
Holy crap, just looked for this and last comment was 9 minutes ago. :+1:

**Comment by rasos** [comment]
For a Rocket.Chat Windows Phone App. we had to leave the path with cordova, as it would require a built in mini web server, which is not available for windows builds. 
Today we had success with a QT5 build. Not sure if we get notifications through to the OS, though.

**Comment by joeleaver** [comment]
I looked around, but there's not yet QT5 extras for windows mobile, which is where the notifications would normally be. Can't find much else out there, either, and I'm not even certain if the c++ bindings exist.

**Comment by rasos** [comment]
Yes, there seems no binding, our protoype will probably not have notifications, also file upload does not work yet, maybe will skim the paper clip. Likely we'll have to leave the WP users with SMS notifications and some other trade-offs, but they can follow conversations. Still looking for support to integrate WPN to RC.

**Comment by joeleaver** [comment]
Just for my own curiosity, can you explain more about why Cordova didn't work for windows builds? What requires a mini web server?

**Comment by rasos** [comment]
This is why Cordova based Rocket.Chat App will not work on a Windows Phone. The App performs the following steps:

1. show server list
2. get the /__manifest.json (list all css, js, png...)
3. start for each entry in manifest.json an asychronous download and save the data in (ms-appdata://local/(url escaped e.g. ucom )_temp)
4. copy the data from ms-appdata://local/(url escaped e.g. mychatserver)
5. replace the <head> in index.htm within ms-appdata://local/mychatserver
6. starts a webserver (!) at ms-appdata://local/mychatserver
7. navigate to own server

Step 6 can not be done on a Windows Phone.

**Comment by rasos** [comment]
Meanwhile we have solved the relaying issue with https://github.com/saqura/xmppwb/issues/7 and have successfully connected a few Windows Phone users. They can not do more than just to participate in one room, though.

We are planning to program Qt quick based lightweight native Apps for Android, iPhone and WP.

**Comment by rasos** [comment]
Update: we are making good progress with a Qt5 based Rocket.chat client for Android, iOS and Windows Phone. Channels, contacts, messages, images, emojis are working, file up- and download is a bit tricky with WP. Next milestone is push services, here we will need WP push service support from RC.
![capture3](https://cloud.githubusercontent.com/assets/485723/20073623/398e4146-a52d-11e6-893c-6607bd4cf536.PNG)

**Comment by CONFORM-IT** [comment]
Would also love to have this, in particular for Windows Phones.

**Comment by rasos** [comment]
A test version of the Qt App for Android is now available for download, however it connects only to our test server. We are working on some more UX improvements and plan to release a white labelled, generic version for Android, iOS and Windows Phone in 2Qu2017: https://www.osalliance.com/en/ucom-app

**Comment by startailcoon** [comment]
I support the need for a Windows Phone application. Better yet, make it a UWP and publish it to the store.
Thanks!

**Comment by flashbackcz** [comment]
@rasos Hello, do you have news about the Windows Phone version?

**Comment by rasos** [comment]
@flashbackcz yes, we have developed the fairchat App for RocketChat servers, which you already find on the Google Play Store and soon on iTunes. We also could publish it as Windows App, see screenshot. What is your use case?
![capture3](https://user-images.githubusercontent.com/485723/30692334-6355385c-9ecb-11e7-9711-680390bd8369.PNG)

**Comment by flashbackcz** [comment]
@rasos Thank you for answer. 
I'm interested in the version for Windows Phone for our Rocket.Chat server (some users have WM). Personally, I use the iPhone (Rocket.Chat+ app), but I'd love to wait and try a new app for this system. (:

**Comment by rasos** [comment]
Finally we have published now a native App for Windows Phone: https://www.microsoft.com/de-at/store/p/fairchat/9nrnnhk6hr5z?rtc=1    We are asking for a small contribution for this build, as it really was quite an exhausting effort.  
fairchat.net is our default demo server, you can add any Rocket.Chat server in the login dialog.  Please report any issues here https://git.fairkom.net/chat/fairchat/issues?label_name%5B%5D=WindowsPhone

**Comment by HammyHavoc** [comment]
Putting the Windows desktop version into the Microsoft Store as a UWP via Desktop Bridge would be good; automatic updates via the Microsoft Store would really take the pain out of it. And it would also make RocketChat usable as an application outside of the browser on Windows 10 S.

**Comment by RubenZombiastic** [comment]
^^^ GIVE THAT MAN A COOKIE 🍪

**Comment by geekgonecrazy** [comment]
This is not something we currently plan to do.  This could change.  It also does not necessarily pertain to this code base.  Instead actually proposing a project.

This might be a bit better suited for [our forum](https://forums.rocket.chat) in the feature request category. Then a proper issue can be spun off from there if we ever decide to work on it.

Thanks,
