### ISSUE TITLE
E-Mail - var [User] not working since v1.0.x

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#14609]
### Description:
After updating from 0.74.3 to 1.0.3 E-Mail header and subject are changed. The used (default) variable [User] is not set anymore.

### Steps to reproduce:
End a message while offline and receive an e-mail.

### Expected behavior:
Expect an e-mail with the subject
`[Chat] You have been direct messaged by John Doe`
and sender:
`John Doe <chat@chat.example.com>`

### Actual behavior:
Get an e-amil with the subject
`[Chat] You have been direct messaged by`
and sender:
`undefined <chat@chat.example.com>`

### Server Setup Information:
- Version of Rocket.Chat Server: 1.0.3
- Operating System: Debian Stretch
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.2.11

### Additional context
The box "Direct Message Email Subject" in E-Mail -> Subject has the default:
`[[Site_Name]] You have been direct messaged by [User]`

### Relevant logs:
-

**Comment by MarcosSpessatto** [comment]
@tars21 I think this issue will be solved in [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14533).

**Comment by tars21** [comment]
I've tested the PR manually in
```
programs/server/app/app.js.map
programs/server/app/app.js
```
and it worked in our staging instance. You are right :-)
