### ISSUE TITLE
Auto-Scroll to bottom of thread reply not always going to very bottom

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14604]
### Description:

When clicking on the last message of a thread in a channel, the auto-scroll doesn't always go all the way to the bottom.

### Steps to reproduce:

1. Start a thread
2. Have a bunch of people reply to it
3. Click on the last reply in a channel

### Expected behavior:

Go to the last message, including the very bottom with the reaction showing.

### Actual behavior:

![scroll-to-bottom-thread](https://user-images.githubusercontent.com/6295044/58215588-8d73f100-7cc8-11e9-8cd3-687267c8da87.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0-rc.1

**Comment by Ishrat1401** [comment]
This issue is not valid now as the functionality has been updated.
