### ISSUE TITLE
Can't find created users in MongoDB users collection

### ISSUE THREAD

**Issue by tund3010** [RocketChat/Rocket.Chat#14601]
I build my development environment based on [this ](https://rocket.chat/docs/developer-guides/quick-start/) guide ( with export MONGO_URL=mongodb://localhost:27017/xxxx_db ), then I create some users on my environment.
![image](https://user-images.githubusercontent.com/5442114/58206744-891cf780-7d0b-11e9-9b52-9875fa94b04f.png)
My understanding is created users will be stored in MongoDB users collection, but I can't find it

![image](https://user-images.githubusercontent.com/5442114/58207489-f7ae8500-7d0c-11e9-81a4-eb342207bf52.png)

Please help to point out

What is my missing point? Where is location that created users will be saved?

**Comment by Hudell** [comment]
It looks like for some reason your client is not connecting to the same mongo server as Rocket.Chat.

**Comment by tund3010** [comment]
Thank you @Hudell 

Can you tell me how to find the correct mongo server to connect to?
Note that I run "export MONGO_URL=mongodb://localhost:27017/xxxx_db" before starting rocket.

**Comment by Hudell** [comment]
Try running it with this line: `MONGO_URL=mongodb://localhost:27017/xxxx_db meteor`

**Comment by tund3010** [comment]
Thank you @Hudell . It worked.

One more question: how to specify the MONGO_URL if starting like this: `nohup meteor --production --port 8888 > output.log &`
