### ISSUE TITLE
Wizard register step missing scroll

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#14605]
### Description:

Mobile chrome can’t scroll to button on register wizard step

### Steps to reproduce:

1. Android chrome 
2. Go through setup process
3. Try to scroll on register step

### Expected
Be able scroll to hit button

### Actual behavior:

Cant scroll

![BE396A90-87CD-4684-BB25-B8B274F139C8](https://user-images.githubusercontent.com/51996/58225839-9e812a00-7ce9-11e9-84bc-dd838ef49c27.jpeg)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 1.0.3
- Deployment Method:  Cloud
- Number of Running Instances: 1 
- DB Replicaset yes
- NodeJS Version: docker
- MongoDB Version: 4.0

**Comment by tassoevan** [comment]
Fixed.
