### ISSUE TITLE
"errmsg" : "there are no users authenticated"

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#14603]
When I am creating the replica I get an authorization error. I clarify that I am updating my system and in the version I have, I did not use OpLog, so now I am trying to activate it. I also give as data that I established a password to my database and I think that there is the problem but I can not define adequate syntax.

> `[Unit]
> Description=Servicio Cujae.Chat
> After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
> [Service]
> ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
> StandardOutput=syslog
> StandardError=syslog
> SyslogIdentifier=rocketchat
> User=rocketchat
> Environment=MONGO_URL=mongodb://admin:password@localhost:27017/rocketchat?authSource=admin MONGO_OPLOG_URL=mongodb://admin:password@localhost:27017/local?replica$
> [Install]
> WantedBy=multi-user.target`

And I have enabled in mongod.conf

> `security:
>   authorization: 'enabled'`

The error obtained is when I execute:

root@smi:~# mongo --eval "printjson(rs.initiate())"
MongoDB shell version v3.6.12
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("19103446-dfa4-41fd-a2f6-2244da16f750") }
MongoDB server version: 3.6.12
{
        "ok" : 0,
        "errmsg" : "there are no users authenticated",
        "code" : 13,
        "codeName" : "Unauthorized"
}

**Comment by geekgonecrazy** [comment]
you will need to actually login first first.

so something like:
```
use admin
db.auth( <username>, <password> )
```

Then try your:
```
rs.initiate()
```
