### ISSUE TITLE
"Visitor Info" is empty when clicking the name user in live chat room

### ISSUE THREAD

**Issue by jusfeel** [RocketChat/Rocket.Chat#14606]
### Description:

"Visitor Info" is empty when clicking the name user in live chat room

### Steps to reproduce:

1. Go to a live chat room with someone as agent
2. Click on the visitor's name
3. Visitor info is empty ( you can show it up by the top bar "info" icon though)

### Expected behavior:

Same as clicking the top bar 'info' icon, the visitor info shows up

### Actual behavior:

Gives empty visitor info when clicking on the user in the live chat window

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by knrt10** [comment]
@renatobecker I am on it, will try to fix this if you are not working on it

**Comment by ashwaniYDV** [comment]
@renatobecker This issue is already fixed by my merged PR.
Can we close this?

**Comment by engelgabriel** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/16797
