### ISSUE TITLE
LDAP usernames get additional '.' if they contain numbers

### ISSUE THREAD

**Issue by photoninger** [RocketChat/Rocket.Chat#14608]
### Description:

We sync LDAP attribute cn into username in rocket.chat. Since the upgrade from 0.74.3 to 1.0.3 every username with numbers in it, e.g. 'a1234bcd' is converted to 'a.1234.bcd'

### Steps to reproduce:

1. Login with LDAP user a1234bcd
2. Click on profile
3. Username shows as 'a.1234.bcd'

### Expected behavior:

Username is still a1234bcd

### Actual behavior:

Username is converted. 
Workaround:
I can stop this with setting UTF8_Names_Slugify to false

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Debian stretch
- Deployment Method: Rocket.Chat.Ansible
- Number of Running Instances: 1
- DB Replicaset Oplog: activated
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.9

### Additional context

This is similar to https://github.com/RocketChat/Rocket.Chat/issues/14337, but my users can still login.

I think this happens because of the default behaviour of limax.js:
https://github.com/lovell/limax/issues/24

Perhaps you can also add the parameter '''separateNumbers: false''' as done here:
https://github.com/lassjs/is-valid-npm-name/commit/4e723b0d31783345a5610eb5eadee3aae03fda63

### Relevant logs:
After setting  UTF8_Names_Slugify to false I have in my logs:

I20190522-18:28:44.598(2) LDAPHandler ➔ info Init LDAP login a1234bcd 
I20190522-18:28:44.600(2) LDAP ➔ Connection.info Init setup 
I20190522-18:28:44.607(2) LDAP ➔ Connection.info Connecting ldaps://authserver:636 
I20190522-18:28:44.716(2) LDAP ➔ Connection.info LDAP connected 
I20190522-18:28:44.718(2) LDAP ➔ Bind.info Binding UserDN cn=binduser
I20190522-18:28:44.724(2) LDAP ➔ Search.info Searching user a1234bcd 
I20190522-18:28:44.733(2) LDAP ➔ Search.info Search result count 1 
I20190522-18:28:44.735(2) LDAP ➔ Auth.info Authenticating cn= a1234bcd,ou=myou
I20190522-18:28:44.743(2) LDAP ➔ Search.info Search result count 1 
I20190522-18:28:44.746(2) LDAP ➔ Auth.info Authenticated cn= a1234bcd,ou=myou
I20190522-18:28:44.760(2) LDAPHandler ➔ info Querying user 
I20190522-18:28:44.764(2) LDAPHandler ➔ info Logging user 
I20190522-18:28:44.765(2) LDAPSync ➔ info Syncing user data 
I20190522-18:28:44.767(2) LDAPSync ➔ info Syncing user username a.1234.bcd -> a1234bcd

**Comment by DerTomm** [comment]
Same here after we upgraded from 0.73 to 1.12. That issue caused (and still causes) a lot of confusion among our users. After the first occurence our admins fixed all wrong usernames by hand - just to realize that the next nightly LDAP sync messed them up again.
Any chance that the pending Pull Request gets reviewed soon to get a fix rolled out with one of the next releases?
