### ISSUE TITLE
"username is typing..." not going away

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14612]
### Description:

I've noticed a few issues with "is typing..." sticking around even though a user is no longer typing.

### Expected behavior:

If the user is no longer typing after a period of time, RC should stop showing that they are typing.

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/58261997-63154880-7d47-11e9-8c2f-1fe2e7c35d10.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0-rc.2

**Comment by serviceman** [comment]
I am having this issue as well on the latest 1.1.0 release. Only way to get rid of it is to reload the browser.

**Comment by thaiphv** [comment]
I'm also having this issue on 1.1.0.
