### ISSUE TITLE
Jitsi meet - Windows desktop app - do not open conversation in new window

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#14610]
### Description:

We have own Jitsi server connected to Rocket Chat. Option "Always Open in New Window" in Jitsi configuration is set "True". During starting/joining conference via Windows desktop app, new window do not appear, only information "Opened in new window" is shown.

### Steps to reproduce:

1. Set "Always Open in New Window" in Jitsi configuration - "True"
2. Start/join conference via Windows desktop app
3. New window do not appear

### Expected behavior:

Conference is opened in new window

### Actual behavior:

New window do not appear

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.1
Operating System: Centos 7
Deployment Method: docker compose
Number of Running Instances: 9
DB Replicaset Oplog: yes
NodeJS Version: 8.11.4 - x64
MongoDB Version: 4.0
Windows desktop app version: 2.15.0

### Additional context

![image](https://user-images.githubusercontent.com/50440047/58238163-0f0a6400-7d47-11e9-8f5e-ed90aa3252b5.png)

**Comment by reetp** [comment]
As per debugging instructions to properly test...

Update to latest 1.0.3
Update to latest app 2.15.3 (I think, but check)

Then test again.

**Comment by emikolajczak** [comment]
Hi,
Thanks for help. Update to latest version of Windows app helped.
