### ISSUE TITLE
Thread`s author cannot unfollow thread

### ISSUE THREAD

**Issue by kyptov** [RocketChat/Rocket.Chat#14617]
1. I wrote a message to the #general.
2. Somebody started a thread from my message.
3. I wanted to unfollow this thread by clicking bell icon to avoid notification.
4. First new message to thread from anybody appears without notification, but bell icon changes to "Follow".
5. Every next message in thread appears with notification.

Expected to unfollow thread and mute notifications.
Actually got followed from first new message.

Client: Google Chrome is up to date Version 74.0.3729.169 (Official Build) (64-bit)
Windows 10 Pro, 1809

```
Server Info
Hash | f19473c62677e2eb132fc2288c006d2f6bb34e40
-- | --
Thu May 9 21:22:41 2019 -0300
HEAD
1.0.3
Rodrigo Nascimento
Release 1.0.3 (#14446)

```

**Comment by ykontekakis** [comment]
I experience the same issue with:
```
➔ |  Rocket.Chat Version: 1.1.1                              |
➔ |       NodeJS Version: 8.11.4 - x64                       |
➔ |      MongoDB Version: 4.0.10                             |
➔ |       MongoDB Engine: wiredTiger                         |
➔ |          Commit Hash: 80341ed12f                         |
➔ |        Commit Branch: HEAD
```
