### ISSUE TITLE
"username is typing..." shows up in main channel while replying to thread

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14613]
### Description:

When replying to a thread in a channel, the "username is typing" shows up in the main channel instead of the sidebar thread. 

### Steps to reproduce:

1. Start a thread.
2. Start typing in the thread.

### Expected behavior:

The "is typing" should show up in the thread UI instead of the main channel. 

### Actual behavior:

The "username is typing..." shows up in the main channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0-rc.2

**Comment by geekgonecrazy** [comment]
I’m not sure about this one.. would require sending to and subscribing to different streams

**Comment by wreiske** [comment]
I think it could be done on the same stream, just add to the object something like isThreadReply: true. Only show in the thread reply if it is true, otherwise, show in the main channel.

**Comment by MartinSchoeler** [comment]
Hey! I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
