### ISSUE TITLE
Can't find Google Drive integration

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#14629]
Hi,

While the Google drive (docs...) integration is listed on forums and site, I can't find anything in he Admin nor in the docs... What am I missing ?

Cheers,

**Comment by zdumitru** [comment]
This is a possible duplicate of #3151.

**Comment by franckadil** [comment]
@zdumitru Thank you :) I don't know though how I can test to be able to contribute, any Idea of the best way ?

**Comment by zdumitru** [comment]
@franckadil Feel free to propose any changes here - #10978

**Comment by franckadil** [comment]
Thank you !

**Comment by reetp** [comment]
@rocket-cat close

Closing this as there is a bug with a PR in progresss.

Please follow up there.

**Comment by trinh-ngo-ntq** [comment]
@franckadil hi bro, pardon me but i got same problem, no Google drive integration feature.
The document said
` must enable Google drive and provide API key`
But no option to enable Google drive?
Any ideas here?
Appreciate all your comments
