### ISSUE TITLE
List of UX Problems and Bugs

### ISSUE THREAD

**Issue by cenicoemir** [RocketChat/Rocket.Chat#14621]
- [ ] Improvement in sidebar search that returns few users
- [ ] Aesthetic improvement in the description and icon of attachments
- [ ] Add specific notifications for active threads
- [ ] Add an option to hide messages from threads in the timeline
- [ ] Add option to group channels by custom categories
- [ ] Allow Slashcommands to work in mobile version

**Comment by cenicoemir** [comment]
news about this fixes @tassoevan @ggazzo ?

**Comment by ggazzo** [comment]
sorry, @cenicoemir ...

we found some bugs and some feature requests, some bugs we had fixed and some bugs we are working on, please provide more details, about your instance (version) to help us to understand some bugs...

about the feature requests provide more details (usually we open an issue for each one, to describe better and discuss)

and about `Allow Slashcommands to work in mobile version` as far as I know, we have this feature for desktop, mobile web, android, and iOS, so if you could tell me more about that, I would love to help you...

**Comment by cenicoemir** [comment]
So we're using version 1.2.1 enterprise. 
About the issue, the rocket support team requested from us to open only one issue with all the problems we found.

**Improvement in sidebar search that returns few users**
- When you search in the left sidebar, the quantity of results is really low, so this should return more results. Sometimes we don't find a specific even if we write the exact name/username.

**Aesthetic improvement in the description and icon of attachments**
- Just an aesthetic item, the typo is too big and icon is too small, worst.

**Add specific notifications for active threads**
- Threads must have a specific highlight. Now we're receiving the notification from the channel, but we don't know from what specific thread it came from. Must have a highlight in the button or something like this.

**Add an option to hide messages from threads in the timeline**
- This small message preview flooding timeline isn't good at all. We're using threads to keep this conversation aside from the main flow, so this is really unnecessary, please allow us to hide this, but we still need a highlight from threads.

**Add option to group channels by custom categories**
- I know that we have the favorites options, but isn't enough. Please allow us to create categories where we could organize the channels, we have tech and non-tech channels that would be great to be divided between 2 categories, or even more.

**Allow Slashcommands to work in mobile version**
- Gonna check, but I tried right now one of our custom slash commands and a /join via the android app and doesn't work.
