### ISSUE TITLE
Ability to change email on account

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1462]
This might be kind of complicated to do since I think we are relying on the meteor accounts package.  But i've found my self wanting to change the email associated with my account several times.

**Comment by fduraibi** [comment]
+1

Should also allow admins to change it if a user lost password and has no access to their email (used temp email, or old email)

**Comment by marceloschmidt** [comment]
What about mail verification? If e-mail verification is set to true, should we logout the user and not give access until they verify again?

**Comment by geekgonecrazy** [comment]
If they are currently logged in I wouldn't think you would log them out.  I would think they might not be able to log back in though if require validation is true

**Comment by marceloschmidt** [comment]
:+1: good!

**Comment by marceloschmidt** [comment]
Making a PR for this now

**Comment by fduraibi** [comment]
How about keeping the old email until they confirm the new one. With some
sort of indication that the new email need to be verified first.

**Comment by geekgonecrazy** [comment]
Closed via #1962
