### ISSUE TITLE
[Feature] Embeds like Discord

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat#14636]
Hey currently I use Discord / RocketChat with my Webhook Script as Status Monitor & notice Discord have a nice Feature to show messages as a Embed Card Style...

The most famous feature is the coloring on the left side....
### Like
![image](https://user-images.githubusercontent.com/1436958/58385209-279ba800-7fed-11e9-8b2b-ee653dd24485.png)

Here is a nice Example in JSON Format 4 the RESTAPI
https://birdie0.github.io/discord-webhooks-guide/structure/embeds.html

Will nice to have in RocketChat. :)

**Comment by reetp** [comment]
@rocket-cat close

This is a feature request, not a bug. Please open  here:

https://github.com/RocketChat/feature-requests/issues
