### ISSUE TITLE
Messages with undefined sender

### ISSUE THREAD

**Issue by asir214** [RocketChat/Rocket.Chat#14639]
### Description:

After updating to version 1.0.3 the name of the sender does not appear when a Rocket message arrives.

### Steps to reproduce:

1. Updating to version 1.0.3
2. Send a message to a disconnected user

### Expected behavior:
Messages should arrive with the name of the user that sends it

### Actual behavior:

It does not show the name of the user who sends the message and it appears as undefined

![rocket_bug](https://user-images.githubusercontent.com/39795205/58411635-04b4d680-8075-11e9-8a1a-777744ccec49.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Debian9
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.2.4-1.0rc2

### Additional context

When we updated to version 0.74 the same thing happened, and we solved it by modifying the file "rocketchat_i18n.js" if however now with the new version it happens again.
Can you help me?

![rocket_bug2](https://user-images.githubusercontent.com/39795205/58411963-cb309b00-8075-11e9-9478-a5bfed0799e3.png)

### Relevant logs:

No logs.

**Comment by zdumitru** [comment]
Possible duplicate of #14392 and #14609 .

**Comment by MarcosSpessatto** [comment]
@asir214 I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14533) solve this problem.

**Comment by asir214** [comment]
Yes, in part.
We use active directory and the names of the users should leave for example "It has a new message from Oskar Laguillo", but it shows "It has a new message from oskar.laguillo".
Can you help me find a way to solve it?

**Comment by Hudell** [comment]
Do you see the name as "Oskar Laguillo" when you open the user information tab on Rocket.Chat?

**Comment by asir214** [comment]
It looks like this the user's information.

![rocket_bug4](https://user-images.githubusercontent.com/39795205/58457213-65501c00-8126-11e9-929b-04b6eba7aeb3.png)

**Comment by asir214** [comment]
> Do you see the name as "Oskar Laguillo" when you open the user information tab on Rocket.Chat?

Hi Hudell, can you help me with this problem?

**Comment by Hudell** [comment]
What did you change in `rocketchat_i18n.js` to make it work when you were using version 0.74?

**Comment by asir214** [comment]
> ¿Qué cambiaste `rocketchat_i18n.js`para que funcionara cuando estabas usando la versión 0.74?


We changed some parameters "__user __" to "__user name__"

**Comment by Hudell** [comment]
@asir214 Is your server configured to use the Real Names? (Admin -> Layout -> User Interface -> Use Real Name).

**Comment by Hudell** [comment]
There's also the "Set a User Name to Alias in Message" setting that should help you while we investigate it further, it's located under **Message** on the admin control panel.

**Comment by asir214** [comment]
> There's also the "Set a User Name to Alias in Message" setting that should help you while we investigate it further, it's located under **Message** on the admin control panel.


Thanks for the help @Hudell !!!

**Comment by Hudell** [comment]
I'm gonna keep the issue open as it should work even without that setting. I've determined what's causing it and am working on a fix.

**Comment by OskarLGS** [comment]
@asir214 I don't know for sure who you are or what company you are, although I can assume it for this and another repository in addition to your name. What I'm sure of is that I haven't sent that message and that at no time have I ever allowed anything to be done in my name, nor that my name be made public.

**Comment by sampaiodiego** [comment]
I guess this PR will fix this issue https://github.com/RocketChat/Rocket.Chat/pull/15767

**Comment by MartinSchoeler** [comment]
Since there is no more interaction in this issue I will assume that https://github.com/RocketChat/Rocket.Chat/pull/15767 fixed the issue, if it happens again feel free to create a new issue, thanks!
