### ISSUE TITLE
Rocket Chat uses a lot of memory in browser if left open for long periods of time.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14633]
### Description:

I run a very active community that can have dozens of new posts added every minute. If I leave Rocket Chat open for a long period of time Rocket Chat eventually becomes very slow and unresponsive, sometimes freezing up completely. I believe this is due to the size of the DOM growing and the memory usage going up. I have seen rocket chat use as much as 200mb or more of ram in the browser. This should be addressed because if any large company adopts this software, they will see the software lock up.  I am currently telling my users to F5, but that is not really a solution.

### Steps to reproduce:

1. Log in to rocket chat
2. Post new messages every few seconds for a few hours.
3. Watch as the chat becomes slower and slower

### Expected behavior:

Old messages should be removed from the DOM, releasing the memory until a user scrolls up, loading previous messages.

### Actual behavior:

Old messages are not removed from the DOM and eventually Rocket Chat becomes unresponsive, very slow or lags.

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.3
Operating System: Centos 7
Deployment Method: manual tar install
Number of Running Instances: 3
DB Replicaset Oplog: yes

**Comment by MIKI785** [comment]
Actually, all you have to do is to keep opening the same rooms again and again. Just cycle like this between  ~7 rooms and the memory usage will keep going up, even though those rooms have already loaded previously. They get reloaded again, but it seems that the memory does not get freed up.

**Comment by Hudell** [comment]
@MIKI785 version 1.0 seems to be a bit better than you described. If you cycle through rooms in a short amount of time, the memory usage will go up, but it does get released after some time.

However, OP mentions that memory usage is rising over long periods of time. That is a different problem that definitely needs to be addressed.

**Comment by serviceman** [comment]
Update: I left the window open over night and Rocket Chat used 450MB of memory and was completely frozen.

**Comment by serviceman** [comment]
This issue does not seem to happen on the latest version so I will close this for now.
