### ISSUE TITLE
Outgoing Webhook - new threads not referenced in request data

### ISSUE THREAD

**Issue by donagrejja** [RocketChat/Rocket.Chat#14631]
Hi.

The request data in the Outgoing webhook has changed and there is no way to see what message you actually replied to since the threads were introduced.

Before there was an url included in the reply message in the outgoing webhook so you had a reference to what messages was replied to. But now it's show just as a new message basically. No reference at all to the old message.

- Rocket.Chat server version: 1.0.3

Thanks.

**Comment by donagrejja** [comment]
Also something else i noticed. In the web based client and windows client you can chooce what kind of reply you want to make. Direct or Threaded. But in the iOS client (not sure about android) it automatically does a threaded answer and you're not able to choose what kind of answer you want to use.

**Comment by MarcosSpessatto** [comment]
@donagrejja can you share the two versions of request data, to help us to debug? Thanks.

**Comment by MarcosSpessatto** [comment]
@donagrejja looking at the message that is handled by the outgoing webhook, after we included the threads, we have now a `tmid` property in the message object that is the id of the message that was replied (The message that originate the thread).
```
{
 _id: 'hEtC2MtekvwSic4Mv',
 rid: 'GENERAL',
tmid: '2o2FhmGxhZJQ6pbyH',
msg: 'g',
ts: 2019-05-30T14:20:50.742Z,
u: { _id: 'Qc2XkTqGbaJaXodRN', username: 'marcos', name: 'marcos' },
_updatedAt: 2019-05-30T14:20:50.779Z,
editedBy: undefined,
editedAt: undefined,
emoji: undefined,
avatar: undefined,
alias: undefined,
 customFields: undefined,
 groupable: undefined,
 attachments: undefined,
reactions: undefined,
parseUrls: undefined,
 mentions: [],
 channels: []
 }

```

**Comment by donagrejja** [comment]
Hi =) I'll have a look at that tmid property. Thanks =)

**Comment by donagrejja** [comment]
How would I find the tmid property ?

Using this script for outgoing webhook:
`
class Script {
    prepare_outgoing_request({ request }) {
        if (request.data.bot) {
            //Don't repost messages from the bot.
            return { };
        } else {
            return {
                url: request.url + '?channel=' + encodeURIComponent(request.data.channel_name) + '&user=' + encodeURIComponent(request.data.user_name) + '&text=' + encodeURIComponent(request.data.text),
                method: 'GET'
            };
        }
    }
}
`

I've checked request.data and i'm not finding it there really.

This is what i get from request.data:
`
{
    "token": "sometoken",
    "bot": false,
    "channel_id": "xxx",
    "channel_name": "somename",
    "message_id": "xxxx",
    "timestamp": "2019-05-25T16:35:18.254Z",
    "user_id": "xxxx",
    "user_name": "stefan",
    "text": "Test"
  }
`

**Comment by donagrejja** [comment]
Before I could differentiate regular messages and replies by request.data.text

A reply had a certain format and contained an actual url to the message it was a reply to.

F.ex: request.data.text: `[ ](https://url:port/group/groupname?msg=msgid) @rocket.cat reply_text`

**Comment by MarcosSpessatto** [comment]
> How would I find the tmid property ?

Sorry, the property does not exist on the request data, I'll open a PR to add this. The example that you are showing, still works, but not for the reply anymore, it works in this way for Quote.

**Comment by donagrejja** [comment]
Aha ok.
Thank you for explaining and requesting tmid to be added to the outgoing webhook.

**Comment by gelinger777** [comment]
I wonder if tmid is supported in incoming hook, or  https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/  ???  How can we force message to land under specific thread? Is that possible?
