### ISSUE TITLE
For mongo v.3.0.7 I had to `service mongod restart`

### ISSUE THREAD

**Issue by tenzan** [RocketChat/Rocket.Chat#1465]
After specifying in `/etc/mongod,conf`:
```
replication:
      replSetName:  "001-rs"
```
I had to `sudo service mongod restart` before in the mongo shell I did:

`rs.initiate({_id:"001-rs",members:[{_id:0,host:"localhost:27017"}]})`

**Comment by engelgabriel** [comment]
OK, I'll update the documentation.
