### ISSUE TITLE
Jitsi connectivity fails in rocketchat client, but not in browser

### ISSUE THREAD

**Issue by stevenmcastano** [RocketChat/Rocket.Chat#14652]
If I use my self hosted instance, when I start a video chat through the desktop client on both Mac and Windows I get no audio and video, it appears to not connect the media stream but it does actually show that users have connected to the bridge.

However, when I do the exact same think when using RocketChat through a browser, tested both Chrome and Safari, it works fine... two way audio and video.

The odd part is that it does seem to work if I used the default public jitsi instance, just not my own self-hosted one even though my own instance seems to work everywhere but inside the client.

**Comment by timothywai** [comment]
I am using a self-host instance of RocketChat, video conferencing work on browser but not on desktop client, the participants can't join.
Info:
Server version - 1.1.3
Video server -  meet.jit.si
Desktop client - 2.15.3
Method -  open a new window

**Comment by stevenmcastano** [comment]
I've gotten it to work with a RocketChat instance now, but the problem is with the client. Full voice and video work fine when connecting to a created room through a browser, but they fail when connecting through the RocketChat desktop client on Mac OS.

Is anyone else having this issue?

**Comment by timothywai** [comment]
I have same problem with RocketChat desktop client on Windows.

**Comment by veda-consulting** [comment]
Same issue for me too, self hosted Jitsi and Rocket

**Comment by dimm0** [comment]
Same issue in Mac OS Catalina, recent rocketchat
