### ISSUE TITLE
User Status Undefined

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14657]
### Description:

On the user info panel the user status often comes up as "undefined". I can not tell if it only users that have not been online for a while, or if it only users that have not been online since upgrading to 1.1.0-rc3. I am currently running version 1.1.0 and the problem still seems to persist.

### Steps to reproduce:

1. Login to rocket chat
2. view user panel of a user that has not been online for a while.
3. Often user status appears as "undefined".

### Expected behavior:

User status to show online, offline, etc.

### Actual behavior:

User status shows as Undefined.

### Server Setup Information:

Version of Rocket.Chat Server: 1.1.0
Operating System: Centos 7
Deployment Method: manual tar install
Number of Running Instances: 3
DB Replicaset Oplog: yes

**Comment by novacrazy** [comment]
Can confirm, shows undefined for users that have not logged in since upgrading.

**Comment by serviceman** [comment]
I see this also happening on open.rocket.chat as well.
