### ISSUE TITLE
how to change tmpDir

### ISSUE THREAD

**Issue by disaster123** [RocketChat/Rocket.Chat#14663]
Currently tmpDir seems to be hardcoded to /tmp/ufs but that does not work on our system, as tmp is cleaned up on a regular basis and rocketchat does not recreate the dir if it is missing while running.

So i wanted to change to a special tmp folder which is not cleaned. Is there a way to define a custom tmpDir?

**Comment by reetp** [comment]
Please use the provided template to give the developers some useful information.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by disaster123** [comment]
I thought / think this isn't a bug. This is more a feature request.

**Comment by reetp** [comment]
Open it in https://github.com/RocketChat/feature-requests

But use a template because it may only apply to a specific type of deployment.

**Comment by disaster123** [comment]
I would so is it a feature request? a bug? Or missing doc - i don't know. At leats there seems to be a way to configure jalik-ufs via UploadFS.config seee https://github.com/jalik/jalik-ufs#configuration

so i'm still not sure if just dokumentation is missing and everything is already "there".

**Comment by reetp** [comment]
You still haven't given details on your system. That is the very first thing to do when trying to resolve any issue, be it a bug or a NFR.

e.g. my Rocket runs on docker, and the /tmp dir is internal to the docker image so never gets touched and it makes no difference to me.

So, please fill in the template so the devs know how you have deployed your system and can give it some consideration.

**Comment by disaster123** [comment]
OK if that helps - sure.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Debian Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: activated
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.12

**Comment by disaster123** [comment]
It seems it would be enough to know how to configure jalik-ufs which is used by rocketchat. It already sipplies all needed settings.
