### ISSUE TITLE
Avatar visible without login

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#14662]
### Description:
A users avatar is visible without logged in by guessing the name. For example:
https://open.rocket.chat/avatar/admin
You get real pictures for some names, but I don't want to post my guessings here.

### Steps to reproduce:
1. Go to https://open.rocket.chat/avatar/$username
2. replace $username with random nicknames

### Expected behavior:
Get a 404 Not found / 403 forbidden / or similar

### Actual behavior:
Get a picture if username exists

### Server Setup Information:
I think any (see https://open.rocket.chat/).
Our specs are:
- Version of Rocket.Chat Server: 1.0.3
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.2.11

### Additional context
-

### Relevant logs:
-

**Comment by hiagodotme** [comment]
I think it's cool to restrict the loading of the images by user name. The image by user name can be a point of failure because hackers can use this technique to identify valid accounts on servers running rocket.chat.

**Comment by MartinSchoeler** [comment]
Please take a look at https://github.com/RocketChat/Rocket.Chat/issues/3480#issuecomment-423962610 Thanks!
