### ISSUE TITLE
Unable to login with LDAP user and customFields set

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#14661]
### Description:

"User not found or incorrect password" trying to log in with LDAP account and customField set.

### Steps to reproduce:

1. Configure a custom field in Account settings
2. Configure LDAP Auth with mapping to custom field
3. Try to log on with LDAP account

### Expected behavior:

User logged in and custom field is updated

### Actual behavior:

"User not found or incorrect password"

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 8.12.0
- MongoDB Version: 4.0.7

### Relevant logs:

```
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAP ➔ Auth.info#033[39m Authenticated uid=xxxxxxxxxx
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAPHandler ➔ info#033[39m Querying user
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAPHandler ➔ debug#033[39m userQuery { 'services.ldap.id': '6a756c69656e2e7465737432' }
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAPHandler ➔ info#033[39m Logging user
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAPSync ➔ info#033[39m Syncing user data
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAPSync ➔ debug#033[39m user { email: undefined, _id: 'NzqnZts92RWZhjzSD' }
May 28 13:29:25 messi nodejs-rocketchat0[6200]: server.js:207 #033[34mLDAPSync ➔ debug#033[39m ldapUser undefined
May 28 13:29:25 messi nodejs-rocketchat0[6200]: Exception while invoking method 'login' TypeError: Cannot set property 'infom2' of undefined
May 28 13:29:25 messi nodejs-rocketchat0[6200]: at _.reduce (app/ldap/server/sync.js:145:9)

```

**Comment by gabrielloberg** [comment]
Having the exact same issue

**Comment by magicbelette** [comment]
The problem still present in RocketChat 1.1.1. We're stuck in version 0.74.3 :/

**Comment by gabrielloberg** [comment]
I didn't have this issue in 1.0.3 or older. This is new for me in 1.1 or 1.1.1

**Comment by magicbelette** [comment]
Hey!

This issue is due to [this](https://github.com/RocketChat/Rocket.Chat/commit/d53e264b83ccc971236123853e4b68c9eb6beeb4#diff-e0878b5aab2c2437d2a5b6e7398587a3) commit on app/ldap/server/sync.js

@sampaiodiego can you have a look please ?

**Comment by lucassmacedo** [comment]
I have the same issue! =(
