### ISSUE TITLE
Use thread composer instead of main one when editing message in thread view

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#14676]
### Description:

<img width="648" alt="Bildschirmfoto 2019-05-29 um 19 43 07" src="https://user-images.githubusercontent.com/944459/58578898-30d58080-824a-11e9-898b-4938628d271d.png">

### Steps to reproduce:

1. Open the left thread view by clicking on an thread/reply in a channel or group 
2. Write a message with the thread composer
3. Edit the message in the thread view
4. Notice how the main composer is used to actually edit the message instead of the thread view one

### Expected behavior:

Since the thread view is open already, its composer should be used instead of the main view one.

### Actual behavior:

The main view composer is being activated

### Server Setup Information:

- Version of Rocket.Chat Server: Cloud
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud 
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

**Comment by zdumitru** [comment]
This is a duplicate of #14450

**Comment by frdmn** [comment]
Closed in favour of #14450 

Thanks @zdumitru

**Comment by marceloschmidt** [comment]
<div>Agent Jonas Friedmann unlinked Freshdesk ticket 387 from this issue</div>

**Comment by marceloschmidt** [comment]
<div>Agent Jonas Friedmann unlinked Freshdesk ticket 387 from this issue</div>
