### ISSUE TITLE
How can i remove the hyperlink before a quote and reply?

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#14678]
How can i remove the hyperlink before a quote and reply?

**Comment by Hudell** [comment]
Please elaborate your question. What hyperlink are you refering to?

**Comment by ubergeekzone** [comment]
There is a hyperlink that shows when quoting a message it looks like this

[ ] (Link here to message) message here

**Comment by Hudell** [comment]
What version of Rocket.Chat are you running? That hyperlink should not exist on the recent versions.

**Comment by ubergeekzone** [comment]
1.1.0

**Comment by Hudell** [comment]
Can you send a screenshot?
