### ISSUE TITLE
First LDAP authentication take long time in version 1.2.1

### ISSUE THREAD

**Issue by cmota-ac-dijon** [RocketChat/Rocket.Chat#14673]
### Description:
Hi !
After migration V0.74.3 to V1.0.3, i have a problem with slowness when first connecting an LDAP user.
When I log in with an LDAP account the first time, it easily takes 1 to 2 minutes to get to the rocketchat homepage.
With a local account, I don't have the problem.
In version 0.74.3, I had no problem.
I have an application server that hosts RocketChat in docker format in version 1.0.3 under redhat. I have a second server under redhat to host mongodb in version 4.0.6.

Thanks for your help

### Steps to reproduce:

1. Page login of rocketchat
2. Connect with userldap for the firstime
3. Wait.....

### Expected behavior:
The connection to the LDAP and the account consultation is going well. It finds the LDAP user account in the logs. On the other hand, it stops in the logs just after the LDAP disconnection "rocketchat_1  | LDAP ➔ Search.info Closed". Then, it is necessary to wait 1 minute before it continues on the line concerning the synchronization of LDAP data "rocketchat_1  | LDAPSync ➔ info Syncing user data". It is this minute that causes these delays in the first connections

### Actual behavior:
The connexion is stopped in this screen :
![image](https://user-images.githubusercontent.com/51164459/58562890-708c7000-822a-11e9-9e4c-e62621f09281.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.3
- Operating System: REDHAT 7.6
- Deployment Method: Docker composer
- Number of Running Instances: 1
- DB Replicaset Oplog: yes in local for version 1.0.3 / https://github.com/RocketChat/Rocket.Chat/issues/14305
- NodeJS Version: 
- MongoDB Version: 4.0.6

### Relevant logs:

> t_1  | LDAP ➔ Connection.info LDAP connected
rocketchat_1  | LDAP ➔ Bind.info Binding UserDN uid=rocketchat,cn=users,cn=accounts,dc=xx,dc=xx,dc=xxx,dc=xxxxxxx,dc=xxxxx,dc=fr
rocketchat_1  | {"name":"ldapjs","component":"client","hostname":"xxxxxxxxxx","pid":1,"clazz":"Client","ldap_id":"1__ldaps://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:636","level":20,"msg":"connected after 1 attempt(s)","time":"2019-05-29T13:05:51.299Z","v":0}
rocketchat_1  | LDAP ➔ Search.info Searching user user1
rocketchat_1  | LDAP ➔ Search.debug searchOptions { filter: '(&(&(objectClass=comptetec)(actif=OUI))(uid=user1))',
rocketchat_1  |   scope: 'sub',
rocketchat_1  |   sizeLimit: 10000 }
rocketchat_1  | LDAP ➔ Search.debug BaseDN cn=accounts,dc=xx,dc=xx,dc=xxx,dc=xxxxxxx,dc=xxxxx,dc=fr
rocketchat_1  | LDAP ➔ Search.info Search result count 1
rocketchat_1  | LDAP ➔ Auth.info Authenticating uid=user1,cn=users,cn=accounts,dc=xx,dc=xx,dc=xxx,dc=xxxxxxx,dc=xxxxx,dc=fr
rocketchat_1  | LDAP ➔ Auth.info Authenticated uid=user1,cn=users,cn=accounts,dc=xx,dc=xx,dc=xxx,dc=xxxxxxx,dc=xxxxx,dc=fr
rocketchat_1  | LDAPHandler ➔ info Querying user
rocketchat_1  | LDAPHandler ➔ debug userQuery { 'services.ldap.id': 'xxxxxxxxxxxx' }
rocketchat_1  | LDAPHandler ➔ debug userQuery { username: 'user1' }
rocketchat_1  | LDAPHandler ➔ info User does not exist, creating user1
rocketchat_1  | LDAPSync ➔ debug user.name changed to: user1
rocketchat_1  | LDAPSync ➔ debug New user data { username: 'user1', email: 'user1@domain.fr' }
rocketchat_1  | Meteor ➔ method joinDefaultChannels -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ undefined ]
rocketchat_1  | Integrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated
rocketchat_1  | Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated { event: 'userCreated',
rocketchat_1  |   user: 
rocketchat_1  |    { _id: 'xxxxxxxxxxxxxxxxx',
rocketchat_1  |      createdAt: 2019-05-29T13:05:51.420Z,
rocketchat_1  |      services: { password: [Object] },
rocketchat_1  |      username: 'user1',
rocketchat_1  |      emails: [ [Object] ],
rocketchat_1  |      type: 'user',
rocketchat_1  |      status: 'offline',
rocketchat_1  |      active: true,
rocketchat_1  |      _updatedAt: 2019-05-29T13:05:51.421Z } }
rocketchat_1  | Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any
rocketchat_1  | Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
rocketchat_1  | LDAP ➔ Search.info Idle
rocketchat_1  | LDAP ➔ Connection.info Disconecting
rocketchat_1  | LDAP ➔ Search.info Closed
rocketchat_1  | LDAPSync ➔ info Syncing user data
rocketchat_1  | LDAPSync ➔ debug user { email: 'user1@domain.fr', _id: 'xxxxxxxxxxxxxxxxx' }
rocketchat_1  | LDAPSync ➔ debug ldapUser undefined
rocketchat_1  | LDAPSync ➔ debug user.name changed to: user1
rocketchat_1  | LDAPSync ➔ debug setting {
rocketchat_1  |   "name": "user1",
rocketchat_1  |   "emails": [
rocketchat_1  |     {
rocketchat_1  |       "address": "user1@domain.fr",
rocketchat_1  |       "verified": true
rocketchat_1  |     }
rocketchat_1  |   ],
rocketchat_1  |   "services.ldap.id": "xxxxxxxxxxxx",
rocketchat_1  |   "services.ldap.idAttribute": "uidNumber",
rocketchat_1  |   "ldap": true
rocketchat_1  | }
rocketchat_1  | Meteor ➔ publish stream-importers -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'progress', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'app/added', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'app/removed', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'app/updated', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'app/statusUpdate', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'app/settingUpdated', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'command/added', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'command/disabled', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'command/updated', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish stream-apps -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'command/removed', { useCollection: false, args: [] } ]
rocketchat_1  | Meteor ➔ publish null -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ method autoTranslate.getSupportedLanguages -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 'en' ]
rocketchat_1  | Meteor ➔ method listCustomSounds -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ method listEmojiCustom -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ method apps/is-enabled -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ publish webdavAccounts -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ publish userData -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ publish activeUsers -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | Meteor ➔ method getUserRoles -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | API ➔ debug GET: /api/v1/commands.list
rocketchat_1  | Meteor ➔ method rooms/get -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | API ➔ debug Success { statusCode: 200,
rocketchat_1  |   body: 
rocketchat_1  |    { commands: 
rocketchat_1  |       [ [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object],
rocketchat_1  |         [Object] ],
rocketchat_1  |      offset: 0,
rocketchat_1  |      count: 23,
rocketchat_1  |      total: 23,
rocketchat_1  |      success: true } }
rocketchat_1  | Meteor ➔ method subscriptions/get -> userId: xxxxxxxxxxxxxxxxx , arguments:  []
rocketchat_1  | API ➔ debug GET: /api/apps/languages
rocketchat_1  | API ➔ debug Success { statusCode: 200, body: { apps: [], success: true } }
rocketchat_1  | Meteor ➔ method userSetUtcOffset -> userId: xxxxxxxxxxxxxxxxx , arguments:  [ 2 ]

>

**Comment by cmota-ac-dijon** [comment]
Hi,

I have the same thing in version 1.1.1.

Thanks

**Comment by cmota-ac-dijon** [comment]
I have the same things in 1.2.1 versions ...
Help me please.....

**Comment by daftaupe** [comment]
Hello, issue is still happening. It's really slow to synchronise all the users in our LDAP too if we want to do it beforehand (~500 users -> several hours). Or it's really slow on the first connection of each users if we don't sync in advance (~ several minutes to successfully login).

The server is a Red Hat Directory Server, but we're not admin of it, just using it. So hard to tell what's going on on the directory side.

**Comment by cmota-ac-dijon** [comment]
To get around the problem, I had to enable account synchronization with LDAP but it's not a solution.....

**Comment by cmota-ac-dijon** [comment]
Is there anyone who can help me?
