### ISSUE TITLE
No scrollbar in composer window when max-height is reached

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#14679]
### Description:

There's no option to scroll within the composer window when it contains a big message that exceeds the max height of it.

### Steps to reproduce:

1. Write a very long message in the composer
2. Try to scroll up to change something in the message

### Expected behavior:

Scrollbar should be visible and working.

### Actual behavior:

No scrollbar at all.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Additional context

<img width="642" alt="Bildschirmfoto 2019-05-29 um 20 23 48" src="https://user-images.githubusercontent.com/944459/58581651-641b0e00-8250-11e9-9846-3ee629ac5d36.png">

**Comment by MarcosSpessatto** [comment]
@frdmn I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14668) should solve this.

**Comment by frdmn** [comment]
@MarcosSpessatto It does indeed :)
