### ISSUE TITLE
"Jump to message" missing in "Starred Messages" message actions

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#14681]
### Description:

As stated in title, "Jump to message" is missing when clicking the message action button in "Starred Messages"

### Steps to reproduce:

1. Open "Starred Messages"
2. Click the action button on any of the messages
3. No "Jump to message" option

### Expected behavior:

"Jump to message" option should be available

### Actual behavior:

It's not there anymore.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud 
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Additional context

<img width="385" alt="Bildschirmfoto 2019-05-29 um 21 24 18" src="https://user-images.githubusercontent.com/944459/58585230-6da87400-8258-11e9-8744-5255d042a995.png">

**Comment by novacrazy** [comment]
It's also still missing from Pinned Messages on 1.3.0-develop.
