### ISSUE TITLE
Allow change of case in username

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1468]
To make notifications easier we've decided to change our usernames to lowercase but the one user which has capitalised his username cannot change it to lowercase. Whenever an attempt is made, by the user or an admin, an error is thrown saying '_username_ is already in user :(' where _username_ is the entered new username (lowercase).

I think it should be possible to modify the case of a username and not have an error thrown.

**Comment by tanc** [comment]
We got around the problem by changing the user's name to something completely different and then changing it back to a lowercase version of the original.

**Comment by geekgonecrazy** [comment]
This might be relatively easy to fix.  Technically the characters are the same, so we might need just to check this and just allow it

**Comment by ahmedsoliman64** [comment]
Is this mean we can have two account
With same user name but different case ?

**Comment by geekgonecrazy** [comment]
@ahmedsoliman64 not at all.  This just means that we don't care about case at all.

We do a match on the characters themselves to prevent anyone from having the same username.

`TESTing` and `testing` are the exact same.  It does character match not case match.  So this simply needs an exception to allow the change of casing in a username maybe if its them changing it.
