### ISSUE TITLE
Cannot edit last message using up arrow

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#14688]
Cannot do that if the last message is not mine.

**Comment by dmoldovan123** [comment]
Hello,
  You can edit with up arrow before receiving a message. If your the last who write message you can edit with up arrow.

**Comment by sampaiodiego** [comment]
yes, that's the issue.. you should be able to edit your message using the arrow up key even if it is not the last message on the channel

**Comment by AlexanderBartash** [comment]
This might me the reason https://github.com/RocketChat/Rocket.Chat/pull/14369/files
