### ISSUE TITLE
Rate limiter is set too high on the shields.svg API + Shield logo doesn't display correctly

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14696]
### Description:

We use multiple shields on a single web page to display links to common channels. On rare occasions, the shields don't display because the user has hit the rate limit on the shields API from viewing too many shields in a period of time.

The shield image is also not working correctly. It looks like it's pulling from "/assets/favicon.svg" in the actual SVG which won't work. It needs to have a full URL of the system. 

### Steps to reproduce:

1. Create an html web page with multiple shields
2. Reload the page
3. Shields break

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/58647618-f44f6680-82d5-11e9-81e6-03d68fcb23b7.png)
**Note, the shield favicon isn't showing, but this is as close to expected as I could get**

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/58647591-e699e100-82d5-11e9-80db-2fb1335dd15f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2 abf67ce98521b115c4c85d2ff86394098c92bbf3

**Comment by wreiske** [comment]
I'm trying to reproduce this here https://jsfiddle.net/154f06ar/ but I'm not having any luck. Maybe the rate limiting was fixed since 1.0.2??

That URL shows the favicon issue, however, is still a problem.

**Comment by wreiske** [comment]
https://www.sitepoint.com/add-svg-to-web-page/
>You’re probably wondering why img isn’t #1 in this list. For security reasons, browsers will disable SVG scripts, linking and other types of interactivity when they’re added to your page with an img tag. In addition, IE9, Chrome and Safari won’t apply stylesheet rules to the SVG if they’re defined in a separate CSS file.

Instead of using an <img> tag, users will have to use an object tag. 

```
<object type="image/svg+xml" data="https://open.rocket.chat/api/v1/shield.svg?type=channel&channel=general"></object>
```

**Comment by rodrigok** [comment]
@wreiske did you try to change the rate limiter params at `Admin > Rate Limiter > API Rate Limiter`?

**Comment by wreiske** [comment]
> @wreiske did you try to change the rate limiter params at `Admin > Rate Limiter > API Rate Limiter`?
That's more generic for all user methods.. I'm not sure if I want to set the defaults for everything higher just so the shields work. The pull request in seems like a much better idea! Thanks, guys. 👍
