### ISSUE TITLE
Custom oAuth2 bug with accounts

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [RocketChat/Rocket.Chat#1469]
Hi Everyone,

I have found a bug i believe. When adding a custom oAuth2 account, and later removing it. It does not disappear from the login screen. It indicates that it saves fine. However when logging out, it is still on the login screen, and the link for it still works.

Has anyone else had this issue? How can we force remove a custom oAuth account?

Thanks

**Comment by geekgonecrazy** [comment]
@phillip-white-sociomantic does it go away if you restart Rocket.Chat?

**Comment by phillip-white-sociomantic** [comment]
Unfotunatly not. I tried that too

**Comment by geekgonecrazy** [comment]
Does it still show up under custom oauth in administration?

**Comment by phillip-white-sociomantic** [comment]
No. When i remove it in the Accounts admin page, it does go away from there. But still remains on the login screen.

I have also tried to get OAuth working with Github. And have run into this error:
```
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with GitHub. redirect_uri_mismatch","time":{"$date":1448638560043},"level":"warn"}
Exception while invoking method 'login' { stack: 'Error: Failed to complete OAuth handshake with GitHub. redirect_uri_mismatch\n    at getAccessToken (packages/github/github_server.js:53:1)\n    at Object.userAgent [as handleOauthRequest] (packages/github/github_server.js:5:1)\n    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)\n    at middleware (packages/oauth/oauth_server.js:173:1)\n    at packages/oauth/oauth_server.js:146:1',
  source: 'method' }
```

Possibly, is this because i use nginx as a reverse proxy? Rocketchat is running on `https://<dns-name>.com` so without the port number 3000. And i then configure under General, the `Site URL` appropriately.

Does the OAuth handshake expect to resolve it with the port number included in the web link?

**Comment by engelgabriel** [comment]
The problem seems to be at `/packages/rocketchat-ui-login/login/services.coffee`

There is only a `added` method on the observer.. no `updated` or `deleted`

@rodrigok is that something hard to fix?

**Comment by rodrigok** [comment]
@engelgabriel done!
