### ISSUE TITLE
Developer Custom Code Changes in RocketChat

### ISSUE THREAD

**Issue by pnandhini11** [RocketChat/Rocket.Chat#14693]
We need to work on RocketChat code changes that suit our business need. Can we install the full developer source code( for our changes)  and use the same for our enterprise business like a manual installation on Ubuntu 18.04?  Will it work same as manual installation of Ubuntu as mentioned in the RocketChat Documentation? It would be great if you respond as we need to make quick decision for our Business Need.

**Comment by nopynoop** [comment]
I believe your question is not well specified and it's hard to give an answer based on your input points.
MIT License allows you to fork the project and you can modify it to be suitable for your needs.

**Comment by reetp** [comment]
@rocket-cat close

This is a support question, not a bug.

I think you already asked this question in open.rocket.chat and I gave you the answer there:

Just read the documentation

https://rocket.chat/docs/developer-guides/quick-start/

https://github.com/RocketChat/Rocket.Chat
