### ISSUE TITLE
threads icon shown although threads are deactivated by admin

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#14708]
### Description:

Although deactivated by admin the threads icon is shown beside the room info icon.

### Steps to reproduce:

1. Deactivate Threads
2. Go to chat window / enter a channel
3. Thread icon is show beside room info icon

### Expected behavior:

No threads icon when threads are deacticated.

### Actual behavior:

Threads icon shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version: 8.12
- MongoDB Version: 4.0

**Comment by flantascience** [comment]
Have the exact same issue....
Would be really great if we could actually replace this icon with the video chat icon :)

**Comment by MartinSchoeler** [comment]
Closed By https://github.com/RocketChat/Rocket.Chat/pull/14956
