### ISSUE TITLE
[1.1.1] sslv3 alert handshake failure with S3 minio storage

### ISSUE THREAD

**Issue by DJeremyy** [RocketChat/Rocket.Chat#14705]
### Description:

After upgrading from version 0.60.x to 1.1.1, I can not get storage to work on S3 with Minio. When I upload a file, in the logs is indicated "sslv3 alert handshake failure".

When I test in the container with Curl, no certificate problem is encountered.

In S3 settings I use FileUpload_S3_SignatureVersion: v4

Thank you in advance for your help.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.10

### Relevant logs:

`I20190531-09:10:38.601(0) Exception while invoking method 'ufsComplete' { Error: write EPROTO 139922965187456:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:      at _errnoException (util.js:992:11)     at WriteWrap.afterWrite (net.js:864:14)   message: 'write EPROTO 139922965187456:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:<br>',   code: 'NetworkingError',   errno: 'EPROTO',   syscall: 'write',   region: 'us-east-1',   hostname: 's3.xxxx-xxxx.fr',   retryable: true,   time: 2019-05-31T09:10:38.599Z }`

**Comment by DJeremyy** [comment]
I updated to version 1.1.2. The problem still occurs. Here is a new piece of logs

{ Error: write EPROTO 140305478634368:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:

     at _errnoException (util.js:992:11)
     at WriteWrap.afterWrite (net.js:864:14)
     message: 'write EPROTO 140305478634368:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:\n',
   code: 'NetworkingError',
   errno: 'EPROTO',
   syscall: 'write',
   region: 'us-east-1',
   hostname: 's3.xxxx-xxxx.fr',
   retryable: true,
   time: 2019-06-20T08:51:15.009Z }

**Comment by mfominov** [comment]
faced same issue but with crowd auth.
try this:
edit programs/server/boot.js
require("tls").DEFAULT_ECDH_CURVE = "auto"
this worked for me.

**Comment by geekgonecrazy** [comment]
Please reopen if still an issue on latest
