### ISSUE TITLE
z-index issue with tooltips showing under thread side menu

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#14704]
### Description:

The z-index on tooltips is too low for the thread side menu.

### Steps to reproduce:

1. Open thread
2. Hover over icons above thread

### Expected behavior:

Tooltips should show above everything.

### Actual behavior:

![z-index-tooltips](https://user-images.githubusercontent.com/6295044/58690358-5f8d4d00-8357-11e9-876c-2fca8f386580.gif)

### Server Setup Information:

![image](https://user-images.githubusercontent.com/6295044/58690413-75027700-8357-11e9-95f3-07a39ab4f135.png)

**Comment by ggazzo** [comment]
thanks for reporting, its not an issue anymore ;)
