### ISSUE TITLE
Chrome doesn't load additional search results when bottom is reached

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#14706]
### Description:

When using the search function of Rocket.Chat in Chrome, it doesn't seem to load additional search results when the bottom of the view is reached and the endless spinner should actually show up to load more.

### Steps to reproduce:

1. Go to our open instance (https://open.rocket.chat)
2. Join "#support" room
3. Search for `from:frdmn`
4. Notice how it stops after showing messages from "20th February 2019"

### Actual behavior:

![demo_bug](https://user-images.githubusercontent.com/944459/58702620-8c1c8580-83a6-11e9-9788-2bb01a0d8327.gif)

### Expected behavior:

On Electron, the spinner shows up and loads additional results (at least including "4th Feburary 2019":

![demo_bug_working](https://user-images.githubusercontent.com/944459/58702633-950d5700-83a6-11e9-856e-2b068b7f811b.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Additional information

- Chrome Version: 74.0.3729.169 (official build) (64-bit)

Apparently this also happens in Firefox.

**Comment by engelgabriel** [comment]
@ggazzo @tassoevan can you guys take a look?
