### ISSUE TITLE
Anonymous Read/Write Version 1.1.0 Not Working

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#14712]
Anonymous Read/Write is no longer working in Version 1.1.0

No rooms are listed in the sidebar, which has never worked as an Anonymous user. I used to be able to go to siteurl.com/channel/roomname and it would ask the Anonymous user to create a name and allow them to join the chat. 

This no longer happens it just now shows loading dots on a white screen. The console is dumping a bunch of errors but the main error seems to be a "Invalid User Id".

Has something changed with how Anonymous users should be handled now?

**Comment by ubergeekzone** [comment]
forgot to say i am using the iframe method for my setup.

**Comment by Cymity** [comment]
Same issue as #14701 and #14497 
Just have to be patient and wait for a fix.

**Comment by sampaiodiego** [comment]
are you guys able to test https://github.com/RocketChat/Rocket.Chat/pull/14717 ?
I can provide a Docker image if that makes it easy for testing. thx

**Comment by ubergeekzone** [comment]
@sampaiodiego i will drop changes into my dev code base and test.

**Comment by ubergeekzone** [comment]
@sampaiodiego it kinda works, not showing messages when room is picked and not allowing them to chat.

**Comment by ubergeekzone** [comment]
@sampaiodiego any updates? Anything needed from me? Your fix is not working 100%

**Comment by ubergeekzone** [comment]
nvm, all is well now. ty @sampaiodiego
