### ISSUE TITLE
How to specify custom chat URL within from the mobile client? 

### ISSUE THREAD

**Issue by tenzan** [RocketChat/Rocket.Chat#1471]
I have installed android version of the client but don't see any settings where I could specify my own install of the chat.

Regards.

**Comment by geekgonecrazy** [comment]
@tenzan check out the beta version: https://play.google.com/apps/testing/com.konecty.rocket.chat

**Comment by tenzan** [comment]
Thanks, Aaron,

How about iOS?

**Comment by geekgonecrazy** [comment]
@tenzan iOS is invite only to beta I believe.  Both are built from https://github.com/RocketChat/Rocket.Chat.Cordova/

**Comment by tenzan** [comment]
Thanks, Aaron.
