### ISSUE TITLE
unread-changed-by-subscription event result has no fname attribute 

### ISSUE THREAD

**Issue by vitocarpentieri** [RocketChat/Rocket.Chat#14721]
### Description:

The result object returned by unread-changed-by-subscription event doesn't include fname attribute

### Steps to reproduce:

 1) user receives a new discussion message
 2) my realtime-api (get Subscriptions) catch unread-changed-by-subscription events
 3) Result attribute name has got Alphanumerical value of discussion and not effective name that is in fname attribute

### Expected behavior:

result object to be return example:
{
	_id: "KHDDg39Kp9ZW87q9f"
	alert: false
​	ls: Date 2019-06-03T08:12:26.807Z
	name: "ZGpNpdbMgAhx7f4ZB"
	fname: "DiscussionName"
​	rid: "SjZtwprKisZJoHta6"
​	t: "p"
​	unread: 0
	.....
}

### Actual behavior:

result object returned example:
{
	_id: "KHDDg39Kp9ZW87q9f"
	alert: false
​	ls: Date 2019-06-03T08:12:26.807Z
	name: "ZGpNpdbMgAhx7f4ZB"
​	rid: "SjZtwprKisZJoHta6"
​	t: "p"
​	unread: 0
	.....
}

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0 
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Yes
- NodeJS Version: 6.4.1
- MongoDB Version: 4.0

**Comment by MarcosSpessatto** [comment]
@vitocarpentieri Can you share the stream object here? I tried to simulate and could not see why it does not return the attribute. :thinking:

**Comment by vitocarpentieri** [comment]
This is the snippet that i am using

```
window.removeEventListener('message', manageMessages);
window.addEventListener('message', manageMessages);
var manageMessages = function(e) {	
 switch (e.data.eventName) {	
  case "unread-changed-by-subscription":
   var sender = e.data.data.name,
         newMessage = e.data.data.alert,
         type = e.data.data.t,
         unread = e.data.data.unread;
   break;	
  default:
   break;
 }
}
```
and this is returned stream object(e.data.data)  console log
![object](https://user-images.githubusercontent.com/35836137/58890253-931aff00-86ea-11e9-8000-bb3850fe889c.png)


I hope that is what you need
Thank you so much

**Comment by vitocarpentieri** [comment]
Hi @MarcosSpessatto , Could I have a feedback? 
I have yet this issue.
In my Server Setup Information section I have wrongly reported server version 1.1.0
But I'm using the 1.1.1 version
Sorry and thank you so much
