### ISSUE TITLE
Change the DNS entries protocol

### ISSUE THREAD

**Issue by alansikora** [RocketChat/Rocket.Chat#14728]
Now, we should use:

`_rocketchat._https.<domain>`
or
`_rocketchat._http.<domain>`

`_rocketchat._tcp.<domain>` will still be valid, but it will work as `https`.

`rocketchat-protocol.<domain>` is going to be discontinued

**Comment by sinteur** [comment]
I'll get my dns settings updated :-)

**Comment by jh1995** [comment]
Please update https://rocket.chat/docs/administrator-guides/federation/ to reflect these changes!

**Comment by iMaciaveller** [comment]
Which DNS Record we should change SRV Record or Protocol TXT Record?

**Comment by scastromx** [comment]
To let you now that Cloudflare does not allow to create a SRV record with `_https` protocol, they only support either `_tcp`, `_udp` or `_tls`.
So maybe it is a good idea not to discontinue `rocketchat-protocol.<domain>` to provide support for providers that just decided to ignore RFC

**Comment by alansikora** [comment]
@scastromx you can use the old way as well, on earlier versions, I suggest upgrading to 3.6.3, closing this for now
