### ISSUE TITLE
RC application takes longer time to startup.

### ISSUE THREAD

**Issue by pnandhini11** [RocketChat/Rocket.Chat#14720]
I took github latest RC version to work on some customization today.  I have seen some discussions that it take approx. 10min first time to startup the application as it will compile all the files. When I started the application, its more than 15min and still in linking stage. Here is the screenshot of the same. Any help on this ? 

![image](https://user-images.githubusercontent.com/19807328/58786840-16165980-8606-11e9-8c81-fe9338f86d3a.png)

**Comment by pnandhini11** [comment]
And it was running after an hour and not finishing the linking step.

**Comment by aermike** [comment]
Hi
This I think depends on which hardaware install RC server, and internet connection to download packages.
I have same version of RC and put all toe

**Comment by fliptrail** [comment]
@pnandhini11 Were you able to build? I build it almost everyday and usually takes 10 min. Are you sure enough resources are alloted to your instance ?
Maybe try this, even though you aren't getting any error... https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory

**Comment by pnandhini11** [comment]
Now I am able to build in few minutes. I had issue even though I had 8GB RAM in the server. After increased to 10GB, now its working perfectly.  But even now free available is almost 5GB RAM in server.   As I needed a very small feature of RC, I didn't look more into it as the problem got resolved. 

@fliptrail Earlier I tried the way mentioned in the link you provided in your reply but not much of help with 8GB RAM.  I wanted to try allocating few memory to SWAP File but now the issue got resolved. I didn't dig further. 


@aermike @fliptrail  thanks for your reply!!!

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This seems more like a forum post, given that the performance of a server depends on a number of factors. Please move this to our [forums](https://forums.rocket.chat/). Thanks!
