### ISSUE TITLE
Maximum number of private rooms?

### ISSUE THREAD

**Issue by nullbio** [RocketChat/Rocket.Chat#14732]
Is there a limit to the number of private rooms/groups you can create, and if so what is it? Thank you.

**Comment by wreiske** [comment]
> Is there a limit to the number of private rooms/groups you can create, and if so what is it? Thank you.

There is no "hard-coded" maximum. It depends on your resources, power of the server, etc.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
