### ISSUE TITLE
Question: About Rocket.Chat.Cordova Deprecation (NOT A BUG)

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#14733]
I know it's not possible to use the latest Rocket.Chat version with Rocket.Chat.Cordova as it is, but is there a way to add the API calls that Rocket.Chat.Cordova used with Rocket.Chat (SERVER) to re-enable it? Is this something remotely possible or has the code base deviated too much? 

I know the Rocket.Chat.Cordova was not without its problems, but the Android and iOS client don't always keep pace.

**Comment by reetp** [comment]
@rocket-cat close

This is really now a feature request, and one that isn't going to get resolved.

You could open an issue here but don't expect a response:

https://github.com/RocketChat/feature-requests/issues

This tells you all you need to know.

https://github.com/RocketChat/Rocket.Chat.Cordova

"Cordova app will not be able to connect to Rocket.Chat server 0.72.0 and higher as support has been removed."

Of course you can go back and use an older version if you really want to, fork it, add back any code you want to a new version, or do whatever you like.

In the meantime I think there is a lot of work ongoing with the new apps to bring them all up to speed.
