### ISSUE TITLE
Auto-translate: Displaying message broken

### ISSUE THREAD

**Issue by FabianGoettl** [RocketChat/Rocket.Chat#14744]
### Description:
Auto-translate is displaying the translate message in rare cases (1 out of 10) only. 
The connection to the Google Translation API is fine and the translated message is stored without problems inside the database.

I guess, this is a display problem.

### Steps to reproduce:
1. Join a private group with two users.
2. Enable Auto-translate enabled and set to English.
3. Write a message.
4. The auto-translation icon appears next to the message.

### Expected behavior:
Message should be displayed translated.

### Actual behavior:
No translation is shown.

The translated message is stored inside the database in the rocketchat_message collection:

{ "_id" : "kE46HsP7YDqhfsKSc", "rid" : "tBcypiaqYEZNhri9X", "msg" : "Wieso will google nicht übersetzen?", "ts" : ISODate("2019-06-05T07:41:11.380Z"), "u" : { "_id" : "ExczKPebAroQnS2HD", "username" : "test", "name" : "Test" }, "_updatedAt" : ISODate("2019-06-05T07:41:11.761Z"), "mentions" : [ ], "channels" : [ ], "translations" : { "en" : "Why does google not translate?" } }

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Ubuntu Server
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.12

### Additional context

Rocketchat was upgrade from V0.4 to V1.1.1.

### Relevant logs:

No errors are present in logs.

**Comment by ear-dev** [comment]
I can confirm that I see the same bug using the web client.  However, refreshing the page always fixes the issue by showing all messages translated properly.

**Comment by vickyokrm** [comment]
This issue could be related to https://github.com/RocketChat/Rocket.Chat/issues/14868.

**Comment by Romain-P** [comment]
up problem still exists
