### ISSUE TITLE
Push Notification via HTTP Proxy

### ISSUE THREAD

**Issue by alvarow** [RocketChat/Rocket.Chat#14742]
### Description:

I am trying to setup iOS Push Notifications with my own certificates to use with my own compiled version of the React mobile app. I have to run Rocket inside a firewalled network with Internet access only via HTTP Proxy. I never see calls to APN on proxy logs, but I do see other types of calls (i.e. collector.rocket.chat). On logs I see that apn module times out.

### Steps to reproduce:

1. Disable Push Notification Gateway on a VPC/Subnet without direct access to Internet
2. Configure APN cert and key
3. Hit Test button

### Expected behavior:

Get push notifications

### Actual behavior:

No notifications are sent. Nothing on Squid proxy logs.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Docker on Amazon ECS Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.12

### Additional context

I was able to test the certificate using the openssl s_connect method. Certificate and key are ok.

I did check the documentation for the [apn](https://github.com/node-apn/node-apn#connecting-through-an-http-proxy) node.js module, and it states for it to work with HTTP Proxy an option need to be set.  I am wondering if Rocket code is testing for the presence of HTTPS_PROXY variable and setting the appropriate option for APN module.

### Relevant logs:

I20190604-18:47:11.066(0) Push: Send message "@alvaro.reguly" via query { userId: 'Pf89CzjjRnXxZcg7m' } 
I20190604-18:47:11.067(0) send to token { apn: '**************' } 

I20190604-18:47:11.071(0) Push: Sent message "@alvaro.reguly" to 1 ios apps 0 android apps 
I20190604-18:47:21.080(0) Exception in callback of async function: Error: Connect timed out     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/apn/lib/connection.js:193:36)     at ontimeout (timers.js:498:11)     at tryOnTimeout (timers.js:323:5)     at Timer.listOnTimeout (timers.js:290:5)

**Comment by magicbelette** [comment]
Check this one :
https://github.com/RocketChat/Rocket.Chat/issues/11404

It seems that the meteor lib doesn't use HTTPS_PROXY for https connection.

**Comment by alvarow** [comment]
> Check this one :
> #11404
> 
> It seems that the meteor lib doesn't use HTTPS_PROXY for https connection.

It seems so... my HTTPS_PROXY variable already declares http not https for the proxy address, so all the other requests work fine, just not the push notifications, and I think it is because the library used does not look for the problem variable, even though it supports it, if properly declared.

**Comment by alvarow** [comment]
I ended up writing my own gateway.

**Comment by farzadch** [comment]
> I ended up writing my own gateway.

Can you please share it? I need my own gateway too.

**Comment by alvarow** [comment]
Sure, you can fork it here [https://github.com/adplabs/rocket-push-gateway](https://github.com/adplabs/rocket-push-gateway), please feel free to send PRs with fixes or improvements.
