### ISSUE TITLE
Custom Emoji Admin Pane capped at 50

### ISSUE THREAD

**Issue by jagloro** [RocketChat/Rocket.Chat#14743]
### Description:

Custom Emoji Admin Pane capped at 50?

### Steps to reproduce:

1. Upload more than 50 Emoji.  (We have about 116 uploaded.)
2. Go to the Custom Emoji Pane in Admin Settings 
3. Try searching for emoji that are past the 50 limit

### Expected behavior:

**On the Admin -> Custom Emoji Pane**
The list should populate with all custom emoji.

### Actual behavior:

**On the Admin -> Custom Emoji Pane**
The list is capped at 50 out of 116 so anything past 50 is cannot be deleted or edited.
Emoji that are past the 50 cannot be searched for either in the admin pane.  

**In a channel, DM, Thread, Discussion, etc.**
All 116 do show up in the chat screen emoji menu.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 16.04
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.9

### Additional context

I'm not seeing any buttons for pagination so I'm assuming that it is a bug that only pulls 50 emoji.  We're on 1.0.3 but I checked the release logs and searched the issues but didn't see anything regarding this.

**Comment by whalehub** [comment]
I can confirm that this issue is still present in Rocket.Chat v1.1.3.

**Comment by novacrazy** [comment]
If you're on a custom fork, you can go to `app/emoji-custom/client/admin/adminEmoji.js` and change `this.limit = new ReactiveVar(50);` to something like `this.limit = new ReactiveVar(500);`

That's what I did for a quick and dirty solution.

**Comment by ggazzo** [comment]
@novacrazy PRs and fixes are very welcome, you don't need to keep dirty fixes in a fork :), look: #14951.

@jagloro please check if the fix solves all your problems ;)

**Comment by whalehub** [comment]
@ggazzo I updated to v1.3.0 today but the emoji limit is still capped at 50. Scrolling to the bottom of the list doesn't expand it either.

![2019-08-04 20 52 43 cb188c1178f8](https://user-images.githubusercontent.com/44198148/62427865-d816de00-b6f9-11e9-96da-319c4d5be1e8.png)
![2019-08-04 20 52 51 a953c12c4ee3](https://user-images.githubusercontent.com/44198148/62427866-d9e0a180-b6f9-11e9-8f37-8b00c7f24eb2.png)

**Comment by ggazzo** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/15119

**Comment by whalehub** [comment]
@ggazzo I can confirm that the issue has been resolved with that PR in v1.3.1. Thanks!
