### ISSUE TITLE
Feature: add a mode for server without internet access

### ISSUE THREAD

**Issue by sebastien-prudhomme** [RocketChat/Rocket.Chat#14748]
### Description:

I'm trying to install Rocket.Chat on a Kubernetes cluster with the help of this Helm Chart: https://hub.helm.sh/charts/stable/rocketchat

After having issues, i found that Rocket.Chat is trying to access Internet to check its version.
As my server has no Internet access this leads to timeouts and Kubernetes is always restarting the application container.

This issue is for asking a new running mode that prevent such Internet access.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Deployment Method: docker "official" image

**Comment by alvarow** [comment]
I am behind a proxy and the version check endpoint is not allowed, so it fails to start for me as well due to the same problem, ECS keeps restarting :-(

**Comment by alvarow** [comment]
@sebastien-prudhomme Did you find a workaround ?

**Comment by sebastien-prudhomme** [comment]
I had to setup our corporate proxy.
