### ISSUE TITLE
mongodb exception in callback $set empty

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#14755]
- Version of Rocket.Chat Server: 1.2.0 Develop
- Operating System: ubuntu
- Deployment Method: standalone
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.9

### Relevant logs:

`Exception in callback of async function: { MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}     at Function.create (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:43:12)     at toError (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:149:22)     at coll.s.topology.update (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)     at handler (/var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:1195:22)     at /var/www/rocketchat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   driver: true,   name: 'MongoError',   index: 0,   code: 9,   errmsg: '\'$set\' is empty. You must specify a field like so: {$set: {<field>: ...}}',   [Symbol(mongoErrorContextSymbol)]: {} }  `

**Comment by MarcosSpessatto** [comment]
@fifou17 Which action did you take that this error occurred?

**Comment by fifou17** [comment]
@MarcosSpessatto i think when users login or register using oauth
