### ISSUE TITLE
Make NextCloud Token Valid for RocketChat 

### ISSUE THREAD

**Issue by SibeeshVenu** [RocketChat/Rocket.Chat#14750]
### Description:

I have both @RocketChat and @NextCloud installed on my Virtual Machine. I understand that there is a mutual partnership between NextCloud and RocketChat, is there any way I can make the token I get from NextCloud valid for RocketChat as well. In this way I can make sure that user have to login only one time to my custom application. 

I tried to do [the SSO using SAML configuration](https://github.com/RocketChat/Rocket.Chat/issues/14672) but I was not able to achieve the same, that is the reason why I am trying this way. Any help is really appreciated. 

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.2
Operating System: Linux, UCS (4.4-0 errata0 (Blumenthal))
Number of Running Instances: 1
NodeJS Version: v8.11.4
MongoDB Version: 3.6.12

**Comment by reetp** [comment]
I think you might be after something like this:
https://github.com/RocketChat/Rocket.Chat/issues/12340

Please close this Issue if it helps your problem.

Note github is for actual breakages in Rocket.Chat rather than support - please ask for general help in open.rocket.chat or forums.rocket.chat

**Comment by SibeeshVenu** [comment]
I was able to login with Nextcloud by creating a custom OAuth in RocketChat, but the redirection from the Nextcloud after login is not happening the issue has been reported [here](https://github.com/nextcloud/server/issues/15962). Anyone else is facing the same problem?

**Comment by geekgonecrazy** [comment]
if you have in Rocket.Chat an oauth app for nextcloud and want to then use nextcloud to login to Rocket.Chat you should be able to login

https://docs.rocket.chat/api/rest-api/methods/authentication/twitter

replace twitter with your oauth provider name you added for nextcloud.

If this isn't what you're looking for maybe add in more detail so we can understand better what you are trying to do
