### ISSUE TITLE
Video Chat with Jitsi button stopped working in version 1.1.1, call ends immediately

### ISSUE THREAD

**Issue by jdavis7718** [RocketChat/Rocket.Chat#14756]
### Description:

We have successfully had Jitsi integrated into our on premise instance of rocketchat since we launched with rocketchat 0.75.  We have updated several time without issue but when we updated from 1.0.2 to 1.1.1 it seems to have broken a piece of the connectivity.  It will launch the Jitsi window, but the link in the rocketchat window instantly is broken and reports the call has ended.   After this has happened we also can attempt to start another Jitsi session as it just constantly will report call has ended and won't open a new window after the first attempt fails.   As a work around we 

### Steps to reproduce:

1. Start a chat, direct or group
2. Click the hamburger menu and click Video Chat, click Yes to the pop up
3. Jitsi will successfully launch
4.  The link "Click to Join!" is instantly broken and reports the "call has ended"

### Expected behavior:

That when we click the link it will connect the user to the ongoing Jitsi call

### Actual behavior:

It falsely reports the call has ended and will not join

### Server Setup Information:

- Version of Rocket.Chat Server:  1.1.1
- Operating System: CentOS Linux release 7.6.1810 (Core)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.12

### Additional context

We are running the latest stable release of Jitsi-meet 3387

**Comment by mikeaer** [comment]
Try restart jitsi Instanțe/server
I have same problem, Buț I don’t believe there îs an rocket chat Isuse.
Aftele restart jitsi server works.

**Comment by jdavis7718** [comment]
I restarted the jitsi server and receive the same error. I want to say it is an issue with rocketchat cause it was working normally just before upgrading rocketchat, immediately after the upgrade of rocketchat is when it broke 
Thanks for the suggestion

**Comment by jdavis7718** [comment]
This appears to be fixed after updating to version 1.3.0

**Comment by jdavis7718** [comment]
This behavior has returned with Rocketchat 2.0.0   Appears to work first the first time video chat, but follows up don't work anymore regardless of rebooting jitsi or rockethcat
