### ISSUE TITLE
Rasa Connector

### ISSUE THREAD

**Issue by pnandhini11** [RocketChat/Rocket.Chat#14769]
Hi, Do we have connector to connect Rasa for Chatbot?  It was in the road map some time back. Any update on this?  If we buy RC paid service, do we get Rasa connector done for us?

**Comment by reetp** [comment]
Not sure you really looked. Try here:

https://github.com/RocketChat/rasa-kick-starter

If there are Issues open them against that repo.

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.
