### ISSUE TITLE
[IMPROVE] Rename discussion

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#14767]
### Description:

There's no option "rename discussion"

### Steps to reproduce:
1. Start a discussion
2. Try to rename the discussion (I've tried it by editing creating "message" in a room but It doesn't change discussion name)

### Expected behavior:
 - Any option to change discussion name

### Server Setup Information:
- Version of Rocket.Chat Server: 1.0.3
- Operating System: Any (Linux, web client, android, etc.)
- Number of Running Instances: 1

**Comment by gdressman** [comment]
Yes, we would like this ability as well
