### ISSUE TITLE
cant  install apps  from marketplace

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat#14761]
### Description:

cant  install apps  from marketplace

### Steps to reproduce:

1. Go to Administration
2. Click on Marketplace
3.  choose  App
4- press  install

### Expected behavior:

App installed

### Actual behavior:

![image](https://user-images.githubusercontent.com/2346208/59096483-a533b200-8923-11e9-831a-cd6c58fcf02e.png)

### Server Setup Information:

![image](https://user-images.githubusercontent.com/2346208/59096524-b250a100-8923-11e9-8d7a-a78d7b659e38.png)

- Deployment Method: manual

**Comment by reetp** [comment]
Be handy if you tell us what version of Rocket you are using e.g. :

Admin->Info
Rocket.Chat:
   Version	1.1.1

Have you actually authorized your install?

Look under:

Admin->Connectivity Services

Yes, I know - why should you have to register for free apps??

I have raised that point myself as I can't see why it is required beyond marketing.

**Comment by gudge25** [comment]
![image](https://user-images.githubusercontent.com/2346208/59253598-43cb5600-8c37-11e9-8212-39c678698e65.png)

ok i am confused 

Look under:
Admin->Connectivity Services

i have created bronze  workspace  and  have  log   in 
![image](https://user-images.githubusercontent.com/2346208/59254406-c9033a80-8c38-11e9-982d-570af18cc208.png)
but i still  cant install   any app 
![image](https://user-images.githubusercontent.com/2346208/59254512-023baa80-8c39-11e9-86dc-a8ea0a738254.png)

in prev wersions there vere no such problems with install apps  from marketplace

**Comment by reetp** [comment]
If you have a paid subscription you should probably contact support @ rocket.chat

**Comment by reetp** [comment]
Please close this if your issue is resolved.

**Comment by gudge25** [comment]
i still  cant install any app  form marketplace
is there any instruction  ?

**Comment by reetp** [comment]
> i still cant install any app form marketplace
> is there any instruction ?

>i have created bronze workspace

See my comment above.

>If you have a paid subscription you should probably contact support @ rocket.chat

Please email them. You have 24/7 email support as per this:

https://rocket.chat/pricing#cloud

**Comment by geekgonecrazy** [comment]
Make sure the account you are logged into is the same as you registered with.

We’ve had a few sign up with one email to a cloud account and register with another.  If the workspace doesn’t belong to the account you registered to.. it will not allow you to make a purchase for it.  

If you sign out and back in to the right account and this persists please email support@rocket.chat we will get it sorted
