### ISSUE TITLE
Voice message option not shown

### ISSUE THREAD

**Issue by MathiasRenner** [RocketChat/Rocket.Chat#14766]
### Description:

Option for voice Message is not shown in Desktop app, on mobile and in browser of my self-hosted instance. 

### Steps to reproduce:

Open chat or channel, try to find voice message/recording option.

### Expected behavior:

Having a button for recording next to text message field.

### Server Setup Information:
-  Version of Rocket.Chat Server: 1.1.1
-  Operating System: Linux
-  Deployment Method: docker
-  Number of Running Instances: 1
-  DB Replicaset Oplog: Enabled
-  NodeJS Version: v8.11.4
-  MongoDB Version: 3.4.20

**Comment by yyicon** [comment]
Same issue for me too

**Comment by ggazzo** [comment]
try 
![image](https://user-images.githubusercontent.com/5263975/67044813-7a444080-f103-11e9-98a6-f8951f90d664.png)

**Comment by MathiasRenner** [comment]
@ggazzo this setting was enabled.
I found the feature in the new version (now called "experimental"). A first test worked fine for me:
https://play.google.com/store/apps/details?id=chat.rocket.reactnative&hl=en
