### ISSUE TITLE
Message Search unusable for Japanese (and presumably other languages)

### ISSUE THREAD

**Issue by enjp** [RocketChat/Rocket.Chat#14771]
### Description:

Message searching appears to be optimized only to languages that have spaces between words.
Message searching is nearly unusable in Japanese, which does not utilize spaces between words.
Presumably this also affects other languages with no spaces between words.

### Steps to reproduce:

1. Send the message "いちにさん" (Japanese for "one two three") in a channel.
2. Do a message search for "いち" in that channel.

### Expected behavior:

Although there is no space between the above characters, "いち" is a single (separate) word, and thus a person writing in Japanese would expect the message search to produce a hit.

### Actual behavior:

Search yields no hits. 

### Server Setup Information:

- Version of Rocket.Chat Server: Unknown (used at work, where I do not have administrator privileges. Presumably up to date or very recent, since implementation is very recent)
- Operating System: Windows 10 64 bit
- Deployment Method: Unknown
- Number of Running Instances: Unknown
- DB Replicaset Oplog: Unknown
- NodeJS Version: Unknown
- MongoDB Version: Unknown

### Additional context

I am using Rocket Chat from an up to date version of Firefox.
Channel search behaves as expected for Japanese (i.e., searches on a single-character basis)

**Comment by fliptrail** [comment]
I think that a fix for this certainly required, search should indeed be character by character
