### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by bitcubate** [RocketChat/Rocket.Chat#1477]
This is not a issue per se.

Where can I find a HOWTO for installation on FreeBSD?

**Comment by Sing-Li** [comment]
It is a work in progress.  What version of FreeBSD are you on?  Can you help?  (if you're a FreeBSD sysadmin or dev and like to tinker)

**Comment by bitcubate** [comment]
Yes I could help, in fact I want a rocket chat up tonight on FreeBSD 10.2 on a digital ocean instance.

Give me quick pointers, I'll try and get back to you with my progress.

**Comment by Sing-Li** [comment]
What is a good email to reach you at?     PM me on demo.rocket.chat for privacy.

I don't think tonight is going to be a realistic goal.  It is a group effort currently just to get node.js, fiber, mongo, and meteor working to support Rocket.Chat.

**Comment by Sing-Li** [comment]
Actually, thanks to the crew over at ixSystems (Matt, Cory, William and James) ... the early access instructions are ready-for-testing:

Install Rocket.Chat on FreeBSD 10.2 ..

https://ghostbin.com/paste/69waw

**Comment by bitcubate** [comment]
Thanks Li, will be checking shortly

Currently I am working on rocket chat and sloppy, after that I'll get back
to freebsd.

This is awesome news! Done so fast!

Kind Regards
Robert Nediyakalaparambil

**Comment by Sing-Li** [comment]
@bitcubate   Assuming you have some success.  Feel free to re-open if you need more info.

**Comment by gogosofta** [comment]
Hello,

As per https://rocket.chat/docs/installation/manual-installation/freebsd/universal/

I get this:
fetch: https://download.rocket.chat/build/rocket.chat-freebsd-develop.tgz: Not Found

Can anyone point the correct file location?
