### ISSUE TITLE
Channels do no scroll on IOS

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14773]
Channels do not scroll on IOS 12.3.1. the member list and conversations on the side scroll but the actual channels do not scroll on IOS.  This also happens on open.rocket.chat

Version of Rocket.Chat Server: 1.1.0
Operating System: Centos 7
Deployment Method: manual tar install
Number of Running Instances: 3
DB Replicaset Oplog: yes

**Comment by reetp** [comment]
This is most likely an Issue with the iOS app, not Rocket itself.
Please close this and reopen in the iOS repo.

https://github.com/RocketChat/Rocket.Chat.iOS

**Comment by reetp** [comment]
This is most likely an Issue with the iOS app, not Rocket itself.
Please close this and reopen in the iOS repo.

https://github.com/RocketChat/Rocket.Chat.iOS

**Comment by serviceman** [comment]
This is not an issue with the IOS app. I am not using the IOS app, I am referring to the browser version that is simply opened in Safari browser.

**Comment by reetp** [comment]
KK - I just updated one of the wifes phones to iOS 12.3.1 so presumed it was that in the absence of mention it was a Mac/Safari.

Any errors in noted dev tools in the browser (assuming it has them)?
