### ISSUE TITLE
ADMIN_PASS was written to log in plaintext

### ISSUE THREAD

**Issue by zhangyoufu** [RocketChat/Rocket.Chat#14774]
### Description:

The content of `ADMIN_PASS` environment variable is written to log in plaintext during first-time setup.

### Expected behavior:

Masked output or nothing at all.

### Actual behavior:

```
Inserting admin user:
Name: Administrator
Email: admin@example.com
Username: admin
Password: U9fgktsIGAwG3tZ0
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Deployment Method: docker

**Comment by zhangyoufu** [comment]
related line: https://github.com/RocketChat/Rocket.Chat/blob/80341ed12fbcd59b7d25b410467ae11a1c8b7c4e/server/startup/initialData.js#L113

**Comment by geekgonecrazy** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15307
