### ISSUE TITLE
From_Email NAME Setting gets ignored/overwritten

### ISSUE THREAD

**Issue by snoopotic** [RocketChat/Rocket.Chat#14789]
### Description:

If you have set up in /admin/Email your SMTP Settings and set an "From_Email" - especially an "noreply"-address - in the @mention and direct-message notifications the name is replaces by the "sender Username".
And in our corporate Environment with alot of users (~500-1000, getting more) the rate of directly answering to these E-Mails is getting to an abusive matter we need to mitigate.
In consequence - if you answered to such an E-Mail once with MS Outlook. This "E-Mail address" gets "stored" to the 'last used' ones. And it mostly accidently happens that people want to write private E-Mails to "Bob" and accidently choose the "Bob" that has the "rocket-chat"-E-Mail-Adress behind.

It's obviously the same described in  #13555 but for me it's an issue.

### Steps to reproduce:

1. Go to admin/Email
2. Set up your smtp and set an From_Email. E.g.: Rocket.Chat Noreply <rocketchat-noreply@example.com>
3. Send Test E-Mail works as expected. "From:"-Header is as set up
4. DM someone who is N/A or away
5. ask him to reply or forward you the notification E-Mail
6. Recognize in the header that "From:"- Header is manipulated

### Expected behavior:

"From:" Header is always the same as set up. If I want Names in it I can set up the BODY Template... or maybe use token for replacement in Header.

### Actual behavior:

"From:" Header in Notification-Mail gets manipulated to the name of the sender if a @mention or DM but the E-Mail-Adress stays to the one set up in /admin/Email

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.3
- Operating System: Centos 7 (Docker)
- Deployment Method: docker
- Number of Running Instances: 1 (2 nodes on 1 host)
- DB Replicaset Oplog: yes
- NodeJS Version: the docker one... xD
- MongoDB Version: 3.6.13 (currently undockered)

### Additional context

Well, we just got an issue in our servicedesk "cannot send E-Mail to user" leading us to this issue, as the sender was errorously sending E-Mails to the rocketchat-noreply-Email instead of the true E-Mail address.

### Relevant logs:

no relevant log entries.
But Pictures:
Outlook Inbox:
![2019-06-12_08h30_32](https://user-images.githubusercontent.com/1191720/59330408-ae40cc80-8cf1-11e9-8283-eaef82655b13.png)
Expected: "Von: RocketChat; Betreff: You have been direct m..."
Actual: "Von: Stefan; Betreff: You have been direct m..."
![2019-06-12_08h30_35](https://user-images.githubusercontent.com/1191720/59330514-f829b280-8cf1-11e9-9e1a-3d61abf0d9b8.png)

And if you want to write a new E-Mail:
![2019-06-12_08h40_01](https://user-images.githubusercontent.com/1191720/59330563-1e4f5280-8cf2-11e9-8a11-a039505c973c.png)
Although there IS a difference, the DAU does not see it. DAU sends Mails to noreply-adresses thinking it's addresseds to people.

**Comment by andreybrasil** [comment]
Hello,
I think there should be an option to disable sending the user's full name in the FROM: field.

Some email clients and collaboration services automatically add contacts from answered messages and sometimes even from received messages to the address book.

Once this happens all subsequent email messages sent by rocketchat begin to be identified with the name of an individual who was saved in the address book initially linked to the email address of the rocketchat.
