### ISSUE TITLE
getUserPreference not working for other users

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#14787]
getUserPreference works fine to view Preferences for logged in user, but if another users trys to view getUserPreference for another user it does not work. 

ex: getUserPreference(msg.u._id, 'messageColor');

**Comment by ubergeekzone** [comment]
To sum up my issue, i guess my question is below.

Why does Rocket.Chat lock down User.findOne() to only the logged in user? The logged in user would return a full result with their data, but another user trying to load data for another user would only get 

```json
{"_id": "", "username": "", "status": ""}
```

Where is this being locked down at?

**Comment by ggazzo** [comment]
@ubergeekzone at the client side `getUserPreference` should work only for your own user... I really dont like the first argument user on the client, but the function can be used in the both server/client...

so if you try access some info about other user, you will just find the public fields like name, username, status...etc... and sure only for online users... its a complicated case, but we keep users information on messages/subscriptions so we dont need user info for this cases usually only to check status...
