### ISSUE TITLE
Can the graphs in the Analytics be changed to the local time zone

### ISSUE THREAD

**Issue by Aishwarya-J-S** [RocketChat/Rocket.Chat#14788]
Currently in the Settings of Livechat, LiveChat ->Analytics , for today's filter, the conversations graph is showing the total conversations across the server time. Is it possible to change it to the local time zone.

**Comment by mayankbhanderi** [comment]
Yes, It is possible
first login as a root inside container docker exec -u 0 -it container_name bash

**Comment by mayankbhanderi** [comment]
Yes, It is possible & working in ubuntu
first login as a root inside container **_docker exec -u 0 -it container_name bash_**
run **_dpkg-reconfigure tzdata_** to configure timezone
