### ISSUE TITLE
same jitsi meet url every time when using rocket chat video conference

### ISSUE THREAD

**Issue by Sx3** [RocketChat/Rocket.Chat#14781]
### Description:

when creating new video conference it is having one video url all the time (no new room is generated )

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1

This happens in chrome and also the rocket chat electron client too.

### Steps to reproduce:

1. Create a new trial cloud workspace from https://rocket.chat/
2. Navigate to Administration > Video Conference > Jitsi and enable "Jitsi"
3. Create a "Video Chat" on a channel (save the jitsi meet url )and end the video chat. 
   then start a "Video Chat" for the second time" and notice the url again.

**Comment by reetp** [comment]
" Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues "

"2. Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

There is no guarantee it will resolve your Issue, but it is the first thing you should test.

There are a number of Issues with Jitsi as well. Please have a good read through them.

Just do a search with "is:issue jitsi"

**Comment by Sx3** [comment]
any one having the same issue ?

**Comment by reetp** [comment]
You are kind of shouting into a void here. Just follow the debugging guidelines.

Have you tested as requested?

**Comment by Sx3** [comment]
1. yes I have followed the guide for opening issues .and updated the issue.
2. yes the rocket chat is already the latest stable

**Comment by reetp** [comment]
You are on 1.0.3

Can you run a test version of latest v1.1.1 somewhere which is latest stable.

(snap will probably be updated in the next few days... it always lags behind for extra stability testing)

**Comment by AmShaegar13** [comment]
This seems to be intended. The Jitsi room is generated by a certain pattern. The pattern includes a configurable prefix, the server ID and the room ID. If you want the room name in Jitsi to be different you need to create it from another room in Rocket.Chat.

**Comment by andreybrasil** [comment]
Hi!
I have this problem with video calling and voice calling between two people.
I can make a video call or a voice call, but apparently Rocket Chat can't identify that the call has ended and don't have a button to finish it.
Then this happens to me: Via web browser, when I start a new call, it always sends to the same meet room in Jitsi which is a prefix followed by a random string. Independent of the person I am calling. Already in the app for android, a message appears that the call has been aborted, saying that already has another call in progress.
The other person I made the call has the same problem.
Here it is set in Rocket Chat for Jitsi to open in a new window.
Was it something I forgot to set up? How do I delete this finalized call in Rocket Chat?

Name               Version    Rev   Tracking  Publisher    Notes
rocketchat-server  2.1.1      1414  stable    rocketchat✓  -

**Comment by Sx3** [comment]
Issue is still same with 
Version 3.18.3
