### ISSUE TITLE
Running the same Rocket.Chat instance over several SSL-enabled domains

### ISSUE THREAD

**Issue by georgiosd** [RocketChat/Rocket.Chat#1478]
Hey guys,

Not exactly a bug but a behavior that is limiting to our scenario.

We essentially want our RocketChat instance to be available on several domains (e.g. https://www.x.com and https://www.y.com) so we have configured a meteor instance and have used nginx to reverse proxy it, through SSL, to the aforementioned domains.

However, what we are seeing is that Rocket.Chat will redirect to whatever is set as ROOT_URL and hence invalidates the configuration on all the other domains.

How would we go about changing this behavior and making RocketChat "stay"? :)

Thank you
Georgios

**Comment by marceloschmidt** [comment]
Sorry to ask, but what is your use case for this? I'm asking because I think we may think of a solution that will work for you, since what you are trying to do is not possible AFAICT. 

You could run two instances of rocket.chat, both pointing to the same database, and each with the correct ROOT_URL, or you could run rocket.chat inside an iframe on each of your domains, or you'd have to redirect all domains to a single domain...

**Comment by georgiosd** [comment]
We basically have multiple sites with different branding but similar user base which we may eventually merge. So it makes sense for a user that goes to many of them to be able to login with one username/password. 

Plus, having separate instances means more resources (hardware, configuration/maintenance etc).

Actually we changed some configuration today and I'm not sure what did it but it's not redirecting any more.

Let me reverse the question - what is the ROOT_URL used for? Any pointers to packages/sections/files would be very much appreciated.

**Comment by engelgabriel** [comment]
There are a few features of Meteor that will depend on having the ROOT_URL properly configured. Mobile apps will use this variable to download assets and create DDP connections. So even if users come from one domain, they will try to connect back to the server using the ROOT_URL.

Any feature dependend on http://docs.meteor.com/#/full/meteor_absoluteurl will have that behaivour.
