### ISSUE TITLE
Can't find livechat transcripts and logs in the linux server

### ISSUE THREAD

**Issue by Purunfii** [RocketChat/Rocket.Chat#14783]
Hello, I'm very new to both linux and JavaScript or coding in general, and in my internship I've got asked to see if rocketchat could be integrated into the system the company uses, specifically for the livechat feature.

Reading the documentation I could not find where the transcripts are saved on the server, and if it could be retrieved by API.

For the integration, i would need to retrieve and store those on the server,

EDIT: found the API to use for how many clients each agent is attending to and when beginning/ending, but cant find logs server side.

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug. Please note that Issues are for bugs in Rocket, not general help.

Please ask in the forums or open.rocket.chat #support 

You probably need to do some serious reading and get yourself a test machine set up to practice both Linux and Rocket.

For existing chats you can get them via the Livechat panel -> Current Chats

I am not sure if they are available via the API at the minute. Ask in #support the community support channel. If they really aren't available via API you can open a feature request, or if they are but not documented then a documentation issue.
