### ISSUE TITLE
Add APIs for auto-translate

### ISSUE THREAD

**Issue by Shailesh351** [RocketChat/Rocket.Chat#14793]
To implement auto-translate on other clients(android/ios) API is needed,

- To check if auto-translate is enabled for a room or not
- If auto-translate is for a room, which language is selected by user for that room
- To toggle auto-update preference of room
- To update language of auto-translate for particular room
- To get translations of message

**Comment by diegolmello** [comment]
We need Rest APIs for these methods: https://github.com/RocketChat/Rocket.Chat/tree/develop/app/autotranslate/server/methods

There's an open PR for React Native client here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1012
It's using method calls, but we should do it using Rest API as well.
