### ISSUE TITLE
directory search for channels should consider their topic

### ISSUE THREAD

**Issue by JanZerebecki** [RocketChat/Rocket.Chat#14794]
### Description:

The directory search should also search in the topic of channels / rooms, not only their name.

### Steps to reproduce:

1. Go to Directory (globe icon in top left)
2. type something to search for in channels

### Expected behavior:

Channels are found where the topic matches the search.

### Actual behavior:

The channel topic is not considered in the search, only the name.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3

**Comment by reetp** [comment]
Please note as per this you should always test on latest:

https://rocket.chat/docs/contributing/reporting-issues

As it happens I checked on open.rocket.chat and it doesn't appear to search as intimated.

However, it isn't a bug (nothing breaks) so it's a feature request.

Please close this and open an Issue here:
https://github.com/RocketChat/feature-requests/issues
