### ISSUE TITLE
How to Open Livechat

### ISSUE THREAD

**Issue by mredbishop** [RocketChat/Rocket.Chat#14790]
Hey all, sincere apologies, this is a question really but I didn't know where else to post it.

We are using the Snap install of Rocket.Chat and it's all setup and working fantastic, the only issue we have is we don't have a lot of freedom in the apps and sites we are inserting the livechat widget into.

We need to be able to **trigger the popup programmatically** rather than being stuck with the widget overlaying the UI of the parent app.

Is there any way at all to do this via message passing or some other method?

**Comment by reetp** [comment]
@rocket-cat close

This seems to be a setup/support/feature request issue in the first instance and not a bug/breakage in Rocket.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

Note there are already some open Issues on livechat widgets including one that may be similar to yours so search here, and more information on APIs etc in the documentation.

https://rocket.chat/docs/developer-guides/
