### ISSUE TITLE
WebRTC Not Working

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#14797]
I am just throwing a DOMException when trying to video or voice call.

**Comment by mouli106** [comment]
unable to chat or login as well.. are the auth servers working fine?

**Comment by ubergeekzone** [comment]
Issue was due to loading Rocket.Chat from within iFrame.

Ref: https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

**Solution**
```html
<iframe src="https://example.com" allow="geolocation; microphone; camera"></iframe>
```

**Comment by mouli106** [comment]
Thanks..
