### ISSUE TITLE
Issue with 1.2.0-develop meteor start from source files

### ISSUE THREAD

**Issue by Srinivasan2017** [RocketChat/Rocket.Chat#14791]
Hi Team

We are trying to build rocketchat from source files with latest version 1.2.0 and receiving  following error while doing meteor npm start.

[[[[[ /Rocket.Chat ]]]]]

=> Started proxy.
^CBrowserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
=> Errors prevented startup:

   While loading plugin `Livechat` from package `rocketchat:livechat`:
   child_process.js:601:13: Command failed: sh /Rocket.Chat/packages/rocketchat-livechat/plugin/build.sh
   Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

   at checkExecSyncError (child_process.js:601:13)
   at execSync (child_process.js:641:13)
   at build-livechat.js (packages/Livechat/plugin/build-livechat.js:26:2)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at <runJavaScript-49>:101:1
   at <runJavaScript-49>:106:3

=> Your application has errors. Waiting for file change.

We have enabled livechat on the application and this occur while restart of the application

**Comment by reetp** [comment]
Did you try doing what the error told you?

`npm update caniuse-lite browserslist`

**Comment by tassoevan** [comment]
Are running `meteor npm i` before `meteor`?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
