### ISSUE TITLE
Private Channels not visable in side bar for my users

### ISSUE THREAD

**Issue by Ph055a** [RocketChat/Rocket.Chat#14795]
Hello,
I have users complaining that they can't see the private channels on the navigation bar. This has only become an issue during the last update and I have not made any administrative changes in months. My users have found one workaround on this issue, if they favorite the channel they can then click and access the channel.

However I as the admin don't have this issue. According to my users the issue spans across different OS and web as well as the desktop version. I believe that a bug may have been introduced in the last update.

Server
Ubuntu 18.04
Rocket Chat Snap Package

**Comment by MartinSchoeler** [comment]
Not enough information provided. Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
