### ISSUE TITLE
Disabling Threads doesn't hide the "Threads" button

### ISSUE THREAD

**Issue by tassoevan** [RocketChat/Rocket.Chat#14796]
### Description:

When disabling threads, the "Threads" button keeps showing on room actions bar (top right).

### Steps to reproduce:

1. Disable threads going into `Administration > Threads > Enable` and setting it to `False`.
2. Open a room.

### Expected behavior:

Do not see "Threads" button on the room actions bar.

### Actual behavior:

The button is present. On clicking on it, the "Threads" tab is shown empty on the contextual bar and an error toast is triggered with "Not allowed" message.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0-develop
- Operating System: MacOS Mojave
- Deployment Method: source code
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.2

### Additional context

![Jun-12-2019 15-09-30](https://user-images.githubusercontent.com/2263066/59375275-2cb66200-8d24-11e9-9921-b66665750475.gif)

**Comment by himpierre** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14708
