### ISSUE TITLE
How to add multiple redirect URI in OAuth settings?

### ISSUE THREAD

**Issue by TheDreamSaver** [RocketChat/Rocket.Chat#14800]
To make our [Rocket.Chat Alexa Skill](https://github.com/RocketChat/alexa-rocketchat) run successfully, we need to complete authentication with a Rocket.Chat server.

For that, we need to add Redirect URI in the OAuth configuration,
![](https://i.ibb.co/NWmtfrW/tempsnip1.png)

Currently Rocket.Chat allows filling one Redirect URI in the above field.

But to make sure the Alexa Skill is available to all regions, Amazon provides us with three different Redirect URIs which correspond to three different regions (North America, India & Europe, Far East).

![](https://i.ibb.co/qgLYvtV/tempsnip2.png)

There is a need for that field to accept multiple values, something similar to how it is done on Auth0.com
![](https://i.ibb.co/qx0Yzyx/2.jpg)

This will help us authenticate our users successfully from around the globe without setting up different skills for different regions.

**Comment by engelgabriel** [comment]
@Hudell can you please take a look if we can do this quickly?

**Comment by engelgabriel** [comment]
Let's just turn the field into a textarea, and split the value per line.
