### ISSUE TITLE
not opening in IE 11

### ISSUE THREAD

**Issue by Srinivasan2017** [RocketChat/Rocket.Chat#14802]
Hi Team

We are unable to open rocketchat instance on IE 11. 
In chrome, same instance appears fine.

![IE 11](https://user-images.githubusercontent.com/11881505/59439254-8d23cd00-8e12-11e9-9215-5a9557690053.PNG)

rocket.chat version: 1.2.0

**Comment by Srinivasan2017** [comment]
@RocketChatApp  : any updates on this issues

**Comment by ggazzo** [comment]
@Srinivasan2017, please follow the issue template, let us know which version of rocket.chat you are using... if not we cant help you, thanks.

**Comment by Srinivasan2017** [comment]
Hi @ggazzo please let me know link for issues template will update accordingly

**Comment by ggazzo** [comment]
hey @Srinivasan2017 
do you have any log on your console?

**Comment by Srinivasan2017** [comment]
Hi @ggazzo  yes.. enabled the console and saw the below issues 

![image](https://user-images.githubusercontent.com/11881505/61608419-39599e80-ac70-11e9-9dd0-914255924f51.png)

**Comment by tntho** [comment]
Hi @ggazzo 
I've found this https://github.com/sindresorhus/mimic-fn/issues/4 . Since RocketChat use `men` package and this package use `mimic-fn`, I think it relate to this issue

**Comment by ggazzo** [comment]
@Srinivasan2017 could you try again? thx

**Comment by ggazzo** [comment]
closed by #15157 if not let me know :)
