### ISSUE TITLE
Cannot paste into password field on mobile.

### ISSUE THREAD

**Issue by MicahZoltu** [RocketChat/Rocket.Chat#14806]
### Description:
Rocket.Chat Experimental Android application does not support pasting into any of the server connection input boxes.  My password is managed by a password manager and almost impossible to actually type on a mobile keyboard, so being unable to paste into the password input box is a big problem.  Also, if the server URL is long/complicated or involves a hash in it, being unable to copy/paste it is problematic.

### Steps to reproduce:
1. Install Rocket.Chat experimental on Android.
2. Copy some text.
3. Long press on the server URL, username, or password input boxes.
4. Notice that no paste option pops up.

### Expected behavior:
To be able to paste into the input boxes.

### Actual behavior:
Cannot paste into input boxes.

**Comment by reetp** [comment]
@rocket-cat close

Please check in the correct repos for known Issues before opening a new one:

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/872
