### ISSUE TITLE
Obtaining the recipient's username in the conversation

### ISSUE THREAD

**Issue by pawelfrydrych** [RocketChat/Rocket.Chat#14818]
Hey, is it possible to obtain recipient username in the conversation? I'm creating a outgoing webhook, and I'm trying to find in documentation any informations about recipient data, but there is completly nothing about it. I need to create a bot, which will be started in conversation and say for example hello "receipent_username". 
Greetings.

**Comment by reetp** [comment]
Sorry but this is a support issue and not a bug.

Please read the documentation:

https://rocket.chat/docs/bots/
https://rocket.chat/docs/developer-guides/

You can ask for help https://forums.rocket.chat or https://open.rocket.chat #support or #bots

**Comment by reetp** [comment]
@rocket-cat close
