### ISSUE TITLE
Feature Request: API endpoint for blocking DM's from a user.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14817]
The Api is great, it has made me able to integrate the chat into my site nicely. I run a community site that already has it's own block list. It would be nice if I could integrate the blocking of DM's into my own block list as well.

If this option is already in the API I can't find where it would be.

**Comment by reetp** [comment]
For support ask in the forums or openrocket.chat #support

Kindly close this Issue and open one if appropriate here please:

https://github.com/RocketChat/feature-requests/issues
