### ISSUE TITLE
webrtc menu (right panel man figure icon click) is empty for direct messages

### ISSUE THREAD

**Issue by solo999** [RocketChat/Rocket.Chat#1481]
webrtc menu (right panel man figure icon click) is empty for direct messages
screenshot link: 
https://www.dropbox.com/s/hfc1hwnecbtk5jx/Screenshot%202015-11-24%2022.41.22.png?dl=0

**Comment by sampaiodiego** [comment]
thank you @solo999 the fix will be live soon :smile:
