### ISSUE TITLE
[Feature request] Implement @someone ping (different from @all)

### ISSUE THREAD

**Issue by jibe-b** [RocketChat/Rocket.Chat#14811]
## Current state

It happens quite a lot of time that a user uses the `@all` mention when the person only means "someone".

The all mention notifies everybody in a channel, and when the question/information/whatever-it-is only requires one person to read it and answer it, it makes a lot of notifications for a message which should not.

## Expected state

A `@someone` mention that notifies only the main contributors to a channel and possibly furthers rounds of people if nobody answers within, say by default, 24 hours – changed in configs.

## Suggestion of implementation

This feature requires to add: 
- [ ] an `@someone` mention
- [ ] (optional): rank users by number of messages in the chat
- [ ] a daemon to notify more users if no answer is given within _n_ hours

**Comment by reetp** [comment]
Please close this and re open here which is the correct place.

https://github.com/RocketChat/feature-requests/issues

**Comment by jibe-b** [comment]
thanks for pointing me to this repo. Here is the new issue: https://github.com/RocketChat/feature-requests/issues/132
