### ISSUE TITLE
No Way to Display Password Policy on Password Reset Screen

### ISSUE THREAD

**Issue by LibertyTalk** [RocketChat/Rocket.Chat#14825]
### Description:
When user attempts to reset a password on a RocketChat server with a defined password policy, there is no way to indicate to user on screen the minimum requirements of said password policy.

If a user attempts to reset a password and creates a non-compliant password, the only feedback is a red bubble that relays one of the policy metrics, with the other metrics of the password policy left as a mystery to end user.

### Steps to reproduce:

1. Go to Login Screen
2. Click 'Forgot Your Password?'
3. Attempt to create a password not compliant with defined policy.

### Expected behavior:

The minimum requirements of the defined password policy is displayed on screen so user may create an appropriate compliant password.

### Actual behavior:

User is left frustrated unable to create a password compliant with defined password policy as no indication of requirements therein are available on screen to guide in creation of password.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: CentOS 7
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.4

###

**Comment by tbhmogy** [comment]
I'll take this one

**Comment by carpecodeum** [comment]
is this issue still open?

**Comment by rohitkatlaa** [comment]
@ggazzo is this issue still valid ? If so can I take up on this issue?

**Comment by rohitkatlaa** [comment]
@MartinSchoeler if valid ? Can I take upon this issue?

**Comment by bajajvinamr** [comment]
I would like to work upon this issue

**Comment by carpecodeum** [comment]
hey is this issue open?

**Comment by aashaypalliwar** [comment]
@LibertyTalk  I wish to work upon this issue. Is it still open?

**Comment by ashwaniYDV** [comment]
I am working on it
