### ISSUE TITLE
Docker Permission denied

### ISSUE THREAD

**Issue by Boffice** [RocketChat/Rocket.Chat#14827]
https://rocket.chat/docs/installation/paas-deployments/aws/

I am stack on 6.4:
sudo -i curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose chmod +x /usr/local/bin/docker-compose exit

i did sudo usermod -aG docker ubuntu restarted ssh but still i get -bash: /usr/local/bin/docker-compose: Permission denied

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit those criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
