### ISSUE TITLE
Hitting Restart the Server button crashes the service

### ISSUE THREAD

**Issue by kevin-og** [RocketChat/Rocket.Chat#14821]
Running v1.1.1 and operating as a service in Ubuntu 18.04

When clicking on Restart the Server from under General settings, the output of systemctl status rocketchat is:

Jun 17 18:55:40 ip-10-0-0-165 rocketchat[15143]: Unloaded the Apps Framework.
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]: Call to process.exit() timed out, aborting.
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]:  1: node::Abort() [/usr/local/bin/node]
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]:  2: 0x8c2559 [/usr/local/bin/node]
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]:  3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]:  4: 0xad712c [/usr/local/bin/node]
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]:  5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
Jun 17 18:59:28 ip-10-0-0-165 rocketchat[15143]:  6: 0x37b9a7842fd
Jun 17 18:59:28 ip-10-0-0-165 systemd[1]: rocket.service: Main process exited, code=dumped, status=6/ABRT
Jun 17 18:59:28 ip-10-0-0-165 systemd[1]: rocket.service: Failed with result 'core-dump'.

**Comment by reetp** [comment]
What sort of install??

Filling out a template properly will help.

Use this link: https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by kevin-og** [comment]
Apologies.

### Server Setup Information:

- Version of Rocket.Chat Server:  1.1.1
- Operating System: Ubuntu 18.04.2
- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: no idea
- NodeJS Version: 8.4.1
- MongoDB Version: 3.6

**Comment by m4z** [comment]
I can still repro with 3.17.0.

### Relevant logs:

```
rocketchat[4001]: Meteor ➔ method restart_server -> userId: rooWv4XkF232RaLnA, arguments: []
rocketchat[4001]: Call to process.exit() timed out, aborting.
rocketchat[4001]:  1: 0xa093f0 node::Abort() [/usr/local/bin/node]
rocketchat[4001]:  2: 0xa7d9c9  [/usr/local/bin/node]
rocketchat[4001]:  3: 0xbf02a9  [/usr/local/bin/node]
rocketchat[4001]:  4: 0xbf2097 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
rocketchat[4001]:  5: 0x13cf199  [/usr/local/bin/node]
traefik[869]: time="2021-08-03T10:23:46Z" level=error msg="vulcand/oxy/forward/websocket: Error when copying from backend to client: websocket: close 1006 (abnormal closure): unexpected EOF"
systemd[1]: rocketchat.service: Main process exited, code=killed, status=6/ABRT
systemd[1]: rocketchat.service: Unit entered failed state.
systemd[1]: rocketchat.service: Failed with result 'signal'.
```


### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0 (Commit Hash: d4ce52e, Commit Branch: HEAD)
- Operating System: Debian GNU/Linux 9.13 (stretch)
- Deployment Method: rocketchatctl
- Number of Running Instances: 2 (one on this staging VM, one on a separate production VM)
- DB Replicaset Oplog: the startup log says "Enabled"
- NodeJS Version: v12.18.4 - x64
- MongoDB Version: 4.0.19 (mmapv1)


### Client Setup Information

- Desktop App or Browser Version: Firefox 78.12.0esr (64-Bit), but probably any
- Operating System: openSUSE Leap 15.2, but probably any


### Additional context

What's (maybe) special about our setup is that:
* it's behind a corporate proxy (or more precisely, two different proxies, for HTTP and HTTPS) and not reachable from the outside world, which caused and causes a couple of problems (f.e. `traefik` can't request a LetsEncrypt certificate and creates an invalid "`[0-9a-f.].traefik.default`" cert)
* the machine has both IPv6 and IPv4 addresses, not all of them connected to the Internet, which caused (and might cause) a couple of problems (see f.e. https://github.com/RocketChat/install.sh/issues/41)
