### ISSUE TITLE
not allow some users to type in the general chat room

### ISSUE THREAD

**Issue by anvers** [RocketChat/Rocket.Chat#1482]
Hi everyone

I wonder if there is some way to limit users not to write on certain chat rooms or in private rooms

Thanks

**Comment by graywolf336** [comment]
So, make it so users can only join as "read only"?

**Comment by anvers** [comment]
Hi Graywolf, 

Yes, just "Readonly"

Sorry for my bad english xD

**Comment by graywolf336** [comment]
No worries. Duplicate of #825.

**Comment by anvers** [comment]
Thanks!

**Comment by anvers** [comment]
Graywolf took the opportunity to make another Question

You know where the files store that are attached in chat rooms ?

I ask because I need to delete them but i dont know where is

**Comment by graywolf336** [comment]
They are located in the database:
![2015-11-24_14-30-48](https://cloud.githubusercontent.com/assets/850391/11379797/f8c1a050-92b7-11e5-8b57-b599d4e0557f.png)

**Comment by anvers** [comment]
thanks
