### ISSUE TITLE
Problems with OAuth since upgrading from v. 0.74 to v. 1.03, random logout, chat history not updated

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat#14824]
### Description:

1) We use OAuth via Keycloak to log in to our server. It worked well up to version 0.74. Then we upgraded to version 1.02 / 1.03 (and now 1.1.1) and the login fails, usually once. If you hit reload on the error page and try to login again, it's usually successful.
The first login attempt does not generate any logs whatsoever.

2) Additionally some of our users are logged out randomly, although the sessions should only be terminated after 72h (end session on window close is OFF). This happens especially if you're logged in on a desktop client / browser and a mobile device simultaneously.

3) Some users report that they're getting notifications about a new message, but the message is not shown in the chat history.

All these issues arose with the upgrade to v. 1.02. (Additionally the mobile Clients received another update and constantly complain that "you have to be logged in to do" ... anything. Clearing the app cache fixes this for a few hours until the bug occurs again.)

The combined amount of these issues renders our setup virtually unusable. If there are no fixes in the very near future, we're considering to abandon RC entirely.
Somewhere it was reported to start with an empty DB after upgrading to 1.02, but seriously, we can't start over every few days to get this working. Downgrading is aparently no option either, since the DB got modified.

### Steps to reproduce:
Issue 1:
1. Configure Oauth via Keycloak
2. Use the Oauth login button.
3. 
- Desktop Client (Windows): "Houston we have a Problem"
- Browser: same as on the desktop client.
- Android / IOS: white error page
4. Hit reload and login again. In most cases it only takes a second attempt. On the mobile devices the reload fails. You have to use the X button to get back to the login page.

Issue 2:
Use Rocketchat on a Desktop and mobile device simultaneously with the same account - no matter if it's Android or IOS. 

Issue 3:
completely random behaviour. Some are affected.

### Expected behavior:

Issue 1: Hit login and get logged in right away.
Issue 2: No session should be terminated.
Issue 3: The chat history should actually be updated if a new message arrives.

### Actual behavior:

Issue 1: Login occurs on second attempt (usually, but not always).
Issue 2: Sessions get terminated at random.
Issue 3: Message Popup, but no entry in the chat history.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Centos 7 x64
- Deployment Method: normal install on the system
- Number of Running Instances: 1
- DB Replicaset Oplog: ON (Had to be enabled after the upgrade for some reason, even if no replicaset is active.)
- NodeJS Version:  8.11.3
- MongoDB Version: 3.6.13

**Comment by aimador** [comment]
Does anyone have an idea how to fix these issues? Any help is much appreciated.

**Comment by geekgonecrazy** [comment]
No new reports on newer versions of Rocket.Chat.  Going to close please test again on latest version and if still an issue let us know

**Comment by kirei4ik** [comment]
> No new reports on newer versions of Rocket.Chat. Going to close please test again on latest version and if still an issue let us know

I have the same problem on latest version Rocketchat (((
