### ISSUE TITLE
Websockets + Apache 2.2 + HTTPS

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#1483]
After piecing together different types of documentation (e.g. https://github.com/RocketChat/Rocket.Chat/wiki/Run-Rocket.Chat-behind-a-SSL-Reverse-Proxy) to get Rocket.Chat finally running, I used the backported mod_proxy_wstunnel (https://gist.github.com/vitkin/6661683) to get websockets finally working.

However, when using the config from https://github.com/RocketChat/Rocket.Chat/wiki/Run-Rocket.Chat-behind-a-SSL-Reverse-Proxy I still get a 400 Bad request for the websocket request. Any ideas how to approach this? Websockets work fine when testing directly without the reverse proxy:

``curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: localhost:3000" -H "Origin:http://localhost:3000" http://localhost:3000/sockjs/717/2ox1ssjn/websocket``

**Comment by tholu** [comment]
I think I got it working with this configuration, at least Firefox does not complain anymore:

```
# Preserve Host header for correct subdomain resolving
 ProxyPreserveHost On

 <LocationMatch "^/sockjs/[0-9]+/[a-z0-9]+/websocket$">
        Order allow,deny
        Allow from all
        ProxyPassMatch ws://localhost:3000/
        ProxyPassReverse ws://localhost:3000/
 </LocationMatch>

 <Location />
        Order allow,deny
        Allow from all
        ProxyPass http://localhost:3000/
        ProxyPassReverse http://localhost:3000/
 </Location>
```

**Comment by tholu** [comment]
The configuration above did not work for me anymore in Apache 2.4.10, so I fixed it by using this:

```
 RewriteEngine on
 RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
 RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
 RewriteRule .* ws://localhost:3000%{REQUEST_URI} [P]
```

**Comment by zerOnepal** [comment]
anything equivalent for nginx we need ?
