### ISSUE TITLE
Federation join not working

### ISSUE THREAD

**Issue by pkolmann** [RocketChat/Rocket.Chat#14831]
### Description:
I want to join our rocket.chat instance into the federation.

I have setup all required SRV and TXT records:

_rocketchat._tcp.chat.tuwien.ac.at. 86400 IN SRV 1 1 443 chat.tuwien.ac.at.
_rocketchat._https.chat.tuwien.ac.at. 86057 IN SRV 1 1 443 chat.tuwien.ac.at.
rocketchat-public-key.chat.tuwien.ac.at. 19633 IN TXT "XPBnAgoYD/W8bGZvNPLHuOIFPw8vH+a+VhxF6P2aVWMpejWup1hxh7rzTFP7Cd5nyu8+pFLDnYp6oUa1YXZuJygjsyaHny+yuJKJHIAbMx7gS4elac2fe0I3QJYa2dKQ9WhexYyAGV3h7BkXVG3+ykBZbYpmQIDAQAB-----END PUBLIC KEY-----"
rocketchat-public-key.chat.tuwien.ac.at. 19633 IN TXT "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh/AHmxvOeppFwbetty/vWczHEITain7uwgG2N9Dy8RzQZyv1khO/LwOy05uLuXSLXgeVtD886tejojyEd72spQz9/xUv/3h5RMjT2q5Eu2hlRtf3HufdGdVgUwcBSNQrs0Sx9FfvdoTuuyJwLnRpFUfePPgbc323j+OlkQ1uS3ZiezZSmdvFa3Lrr"

When I want to join the federation I see the following info in the logfile:

Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ Peer Client.info#033[39m propagateEvent: png
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ DNS.info#033[39m searchPeer: @chat.tuwien.ac.at
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ DNS.info#033[39m updatePeerDNS: @chat.tuwien.ac.at
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ DNS.info#033[39m getPeerUsingDNS: @chat.tuwien.ac.at
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ DNS.info#033[39m getPeerUsingHub: @chat.tuwien.ac.at
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ HTTP.info#033[39m Sending request: GET - https://hub.rocket.chat/api/v1/peers?search=@chat.tuwien.ac.at
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ DNS.info#033[39m Could not find peer for domain @chat.tuwien.ac.at
Jun 19 09:13:31 web-d-1 RocketChat[23270]: #033[34mFederation ➔ Peer Client.info#033[39m Could not find valid peer:@chat.tuwien.ac.at

When trying to access the API by hand I receive a 404 error:

GET https://hub.rocket.chat/api/v1/peers?search=@chat.tuwien.ac.at
User-Agent: lwp-request/6.36 libwww-perl/6.36

404 Not Found
Connection: close
Date: Wed, 19 Jun 2019 07:19:58 GMT
ETag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
Content-Length: 9
Content-Type: text/plain; charset=utf-8
Client-Date: Wed, 19 Jun 2019 07:19:58 GMT
Client-Peer: 3.92.249.169:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
Client-SSL-Cert-Subject: /OU=Domain Control Validated/OU=EssentialSSL Wildcard/CN=*.rocket.chat
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
X-Powered-By: Express

### Steps to reproduce:

1. Go to Admin -> Federation
2. Fill out the requied fields and press test
      Domain: @chat.tuwien.ac.at
      Hub URL: https://hub.rocket.chat
      Discovery Method: DNS

3. get the error

### Expected behavior:

be joined in the federation

### Actual behavior:

I receive an error:

<img width="310" alt="Bildschirmfoto 2019-06-19 um 09 23 37" src="https://user-images.githubusercontent.com/2240760/59744970-fde44280-9273-11e9-8c14-04288aab6bd3.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Debian 8 Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
- Deployment Method: tar
- Number of Running Instances: 8
- DB Replicaset Oplog: 
- NodeJS Version: v8.16.0
- MongoDB Version: 3.2.11

**Comment by OliCat** [comment]
Hi,
I've exactly the same issue. 

**Server Setup Information:**

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Debian 9.9 4.15.18-4-pve #1 SMP PVE 4.15.18-23 x86_64 GNU/Linux
- Deployment Method: tar
- Number of Running Instances: 3
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.10

OliCat

**Comment by pkolmann** [comment]
Hi,

does federation work for anyone?

I still can't get the validation working for DNS.

Thanks
Philipp

**Comment by pkolmann** [comment]
After upgrading to 2.0.0 the federation test now works.

Thanks, Philipp
