### ISSUE TITLE
RocketChat Documentation 

### ISSUE THREAD

**Issue by tommycwleung** [RocketChat/Rocket.Chat#14835]
My Client tried to have a full copy of the RocketChat Documentation as the online viewing is slow and often led to off-line. 
Any chance to have the clone download of the Documentation?
OR
Is it in a working RocketChat Server,  say under  Rocket.Chat directory in Ubuntu OS ?

**Comment by reetp** [comment]
@rocket-cat close
This is not a bug in Rocket.Chat

Please read the manual.
https://github.com/RocketChat/docs

https://github.com/RocketChat/docs#how-to-run-rocketchat-docs-locally
