### ISSUE TITLE
Slow file uploads with snap install to FileSystem

### ISSUE THREAD

**Issue by bleomycin** [RocketChat/Rocket.Chat#14830]
### Description:

Uploading files to snap based rocket chat server behind nginx with file upload set to FileSystem tops out at ~23Mbit/s. Iperf testing to this same machine uploads at ~150Mbit/s single thread. Downloads happen at 200Mbit/s+ so no issue. Speeds were also slow with default GridFS which prompted the change to FileSystem.

### Steps to reproduce:

Upload file to rocket chat

### Expected behavior:

Upload file at maximum speed of connection

### Actual behavior:

File uploads significantly slower than network bandwidth should allow

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.3
- Operating System:  Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v8.11.3
- MongoDB Version: 3.4.20

**Comment by reetp** [comment]
First thing is to probably get a clean test install of latest and with no proxy/firewall and try direct to http://chat.local:3000 so you eliminate some factors.

Try with some different clients, and clean/restored dbs.

Try and narrow down the issue further.
