### ISSUE TITLE
How to Merge two rocket chat server to one server

### ISSUE THREAD

**Issue by stormanger** [RocketChat/Rocket.Chat#14841]
Rocket.Chat version: 1.0.3
Apps Engine Version: 1.4.2
OS : Ubuntu 16.04.2
Install way: snap

Dear all,
I have two question:
    1, I have run two rocket chat servers, How can I Merge two server in one? Like migrate data from one to another;
    2, How to export chat history or how to import?

**Comment by geekgonecrazy** [comment]
Please open a forum post or ask in a proper support channel
