### ISSUE TITLE
Direct reply via email functions but doesn't render properly.

### ISSUE THREAD

**Issue by stevenmcastano** [RocketChat/Rocket.Chat#14843]
I've got RocketChat 1.1.2 running on Ubuntu 18.04.2 and I'm having a problem with direct reply via email. The "functionality" works... as in, an email is sent to offline or idle users to tell them they've gotten a message, but when they reply from Outlook the messages comes through into chat with horrible rendering. It's broken up by lines, not decoded properly, includes the original email contents, etc...

The behavior I would expect is that only the actual reply from the user enters the messages/chat channel. If I reply with only one line without changing anything else in the email, only that line should come through. Below are screen shots of what the conversation looks like in chat and how the email reply was sent.

First is an HTML email reply which is how outlook defaults:
<img width="1382" alt="Screen Shot 2019-06-20 at 1 23 04 PM" src="https://user-images.githubusercontent.com/6171444/59869993-9658f080-9362-11e9-99c9-6777b3b7f8c2.png">
And this is how it looked when sent from outlook:
<img width="1417" alt="Screen Shot 2019-06-20 at 1 19 13 PM" src="https://user-images.githubusercontent.com/6171444/59870019-a07aef00-9362-11e9-95c6-d61c22a7c4b7.png">

Here is trying the same thing but setting outlook to reply with plain text:
<img width="1374" alt="Screen Shot 2019-06-20 at 1 24 47 PM" src="https://user-images.githubusercontent.com/6171444/59870044-ad97de00-9362-11e9-8c85-e7bf0d172615.png">
And here is the plain text reply as it looks from the outlook side:
<img width="1422" alt="Screen Shot 2019-06-20 at 1 24 11 PM" src="https://user-images.githubusercontent.com/6171444/59870058-bc7e9080-9362-11e9-8cb1-0903ddf9550a.png">

**Comment by reetp** [comment]
@rocket-cat close

This discussion originated in #support and concerns email clients formatting responses.

For now closing in favour of your feature request. Please don't 'crosspost' issues.

Please follow up there for now:

https://github.com/RocketChat/feature-requests/issues/134
