### ISSUE TITLE
Twitter native sdk login

### ISSUE THREAD

**Issue by BugsBunnyBR** [RocketChat/Rocket.Chat#1484]
Hi, I am trying to implement the twitter android native sdk login. The twitter/android part is working fine.
So I thought that I could just send the secret and token to the oauth login method, but it did not work as spectated. 
The oauth message the device sent:
```
{"msg":"method","id":"7574bf71-e557-461b-98c4-48caddce6345","params":[{"oauth":{"credentialToken":"TOKEN","credentialSecret":"SECRET"}}],"method":"login"}
````
What was received:
```
{"msg":"result","id":"7574bf71-e557-461b-98c4-48caddce6345","error":{"error":145546287,"reason":"No matching login attempt found","message":"No matching login attempt found [145546287]","errorType":"Meteor.Error"}}
```
I am new to meteor and I don't quite understand the oauth completely, so I let here what I got until now.
The twitter documentation  [here](https://docs.fabric.io/android/twitter/oauth-echo.html) says the mobile device should send
```
X-Auth-Service-Provider=https://api.twitter.com/1.1/account/verify_credentials.json
```
and
```
X-Verify-Credentials-Authorization=OAuth oauth_consumer_key="$OAUTH_CONSUMER_KEY", oauth_nonce="$OAUTH_NONCE", oauth_signature="$OAUTH_SIG", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1448418809", oauth_token="$MY_OAUTH_TOKEN", oauth_version="1.0"
```
to the server.
So the server should execute a GET int the "X-Auth-Service-Provider" parameter using "X-Verify-Credentials-Authorization" as the "Authorization" header to get the user info and login/register the user.
I don't think I am using the wrong CONSUMER_KEY or CONSUMER SECRET as the same values work in the oauth for the web chat. Is the twitter process not the same process used in the web version?
Thanks in advance doc.

**Comment by BugsBunnyBR** [comment]
I went to the meteor repo I had a look at the source, it seems this native integration would need a new login [oauth echo](https://dev.twitter.com/oauth/echo) package but I have no clue of how to build it.

**Comment by BugsBunnyBR** [comment]
I found [this](https://github.com/ManifestWebDesign/twitter-connect-plugin) which could be used in the cordova app and improve the twitter login process (by not having to execute the login in a webview) and it uses the same native android/ios sdk as I am using to execute the twitter login. So a oauth echo package would make more sense.

**Comment by rohanray** [comment]
Hi @BugsBunnyBR 

I have the same requirement of android/ios native twitter login. I have used [this cordova plugin](https://github.com/ManifestWebDesign/twitter-connect-plugin) as mentioned in your comment. I have been able to atleast do an oauth login using the plugin, but I'm not sure how to log the user into the meteor app using details retrieved from twitter viz. accesstoken, secret etc. Please can you help me here?

**Comment by BugsBunnyBR** [comment]
@rohanray I could not make it work...Rocket chat had not an API to allow it. Maybe nowadays it have...
Good lucky.

**Comment by geekgonecrazy** [comment]
Closing.  If this is still an issue can we move it over to our cordova repo: https://github.com/rocketchat/rocket.chat.cordova

Thanks :smile:
