### ISSUE TITLE
Invalid API response in subscription

### ISSUE THREAD

**Issue by httpsOmkar** [RocketChat/Rocket.Chat#14849]
### Description:

Subscriptions API doesn't work as specified in the documentation.
https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/ `Where the subcription_id is the unique id that was used when you initially made the call to subscription.`.
but in payload the id value always `id`

### Expected behavior:

```json
{
    "msg":"changed",
    "collection":"stream-room-messages",
    "id":"unique-id",
    "fields":{
        "eventName":"odATGNJX7a3woQ8hAtYEtHD2WBDbbq3bzb",
        "args": []
    }
}
```

### Actual behavior:

```json
{
    "msg":"changed",
    "collection":"stream-room-messages",
    "id":"id",
    "fields":{
        "eventName":"odATGNJX7a3woQ8hAtYEtHD2WBDbbq3bzb",
        "args": []
    }
}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.4.2
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.3

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/29942725/59936147-ef14b000-946c-11e9-9f57-44675da1b1cc.png)

**Comment by davie-robertson** [comment]
could it be related to https://github.com/RocketChat/Rocket.Chat/pull/14860

**Comment by sampaiodiego** [comment]
@httpsOmkar actually the data that you'll receive after subscribing will **not have** the `unique-id` specified when you subscribe with `"msg": "sub"`.. the `unique-id` will only be used for `"msg": "unsub"`..

the `id` you receive with `"msg":"changed"` is related to the document ID that was changed, and not to the subscription itself.

please look at the [DDP protocol specification](https://github.com/meteor/meteor/blob/master/packages/ddp/DDP.md#messages-2).. you'll have a better picture there.
