### ISSUE TITLE
Create Rocket.Chat plug-ins

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1485]
Meteor packages, while flexible and modular, has a severe limitation -- they must be configured at build time.

This means that a particular distribution binary cannot be easily re-configured for specific use case without re-building.

The actual 'interface' between core and plugins in Rocket.Chat is actually well defined (for example, rendering hooks or Tab Bar interface) AND lends itself to run-time loading/configuration if properly coded.

Design and create an alternate run-time loadable 'plug-in' system, independent of Meteor's Isobuild,  for Rocket.Chat.

**Comment by engelgabriel** [comment]
Let's close this and centralize the discussion at #1859
