### ISSUE TITLE
Filtering by username in member list doesn't find users if they haven't been loaded

### ISSUE THREAD

**Issue by novacrazy** [RocketChat/Rocket.Chat#14855]
### Description:

Attempting to find a user by username in the member list won't find them if they haven't been loaded. If you scroll down on the member list and "Load more" until that user shows up, then now the filter will find them.

### Steps to reproduce:

In a channel with more than a couple hundred users, go to the member list, (view all if necessary), and filter a user that hasn't been initially loaded in the member list (typically started with later alphanumeric characters). They won't show up.

### Expected behavior:

For it to search through *all* users, not just those that are loaded in the list.

### Actual behavior:

It doesn't search/filter beyond the hundred or so that are already loaded.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0-develop
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0

**Comment by rsimai** [comment]
This seems a (younger) duplicate to https://github.com/RocketChat/Rocket.Chat/issues/14537
