### ISSUE TITLE
Add support for tmid on rooms.upload api

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat#14854]
https://github.com/RocketChat/Rocket.Chat/blob/d53e264b83ccc971236123853e4b68c9eb6beeb4/app/api/server/v1/rooms.js#L61

this api route doesn't support tmid

**Comment by MarcosSpessatto** [comment]
@pranavpandey1998official the endpoint already provides support to `tmid` property, just the docs were outdated. Anyway, I [updated it now](https://github.com/RocketChat/docs/pull/1351).
