### ISSUE TITLE
Allow to make rooms accessible for people with no account

### ISSUE THREAD

**Issue by schiessle** [RocketChat/Rocket.Chat#14856]
Sometimes it can be really useful to invite external people to a chat. The idea is that a room marked as accessible for non-members could be shared as a direct link with other people. They could open the link, enter a name and start chatting the same way as they would have an account on the Rocket.Chat server, limitted to this one room.

**Comment by jonnytest1** [comment]
should be possible by settings allow anonymous read and allow anonymous write and making your room a default room

**Comment by MartinSchoeler** [comment]
as @jonnytest1 said, you can use the settings `allow anonymous read` and `allow anonymous write` for that. Furthermore, you can use the [permission grid]( allow anonymous read and allow anonymous write) to fine tune what do these users can do on your server. Thanks!
