### ISSUE TITLE
Auto Translate: Caching of rendered messages are not working as expected.

### ISSUE THREAD

**Issue by vickyokrm** [RocketChat/Rocket.Chat#14868]
### Description:

Rendered messages are cached for 5 secs and invalidated afterwards. The actions **Translate / View Original** on the context menu will not switch to the corresponding messages if the action is executed within 5 secs. In other words no re-rendering takes place until the cache for the message is invalidated.

This behaviour was introduced in the RC 1.03.

### Steps to reproduce:

1. Activate auto translate feature Message->Auto Translate.
2. Create a channel and add two users as members of the channel.
3. Activate auto translation in the channel for each user to individual language.
4. Post a message and on the translated user channel, click on the view original action from the context menu.

### Expected behavior:

The message should be displayed appropriately.

### Actual behavior:

The messages are not be re-rendered within 5 secs.

In the below case, the original message was written in English and translated to German.

![Message caching](https://user-images.githubusercontent.com/24695986/60098930-ecf56e80-9756-11e9-9e1a-80b6b18cffad.gif)

**Comment by vickyokrm** [comment]
The caching for the rendering behaviour was handled in renderMessageBody.js .

Here the caching limit for each message is set to 5000ms.

`export const renderMessageBody = mem((message) => {
	message.html = s.trim(message.msg) ? s.escapeHTML(message.msg) : '';

	const { tokens, html } = callbacks.run('renderMessage', message);

	return (Array.isArray(tokens) ? tokens.reverse() : [])
		.reduce((html, { token, text }) => html.replace(token, () => text), html);
}, 5000, ({ _id, _updatedAt }) => _id && _updatedAt && _id + _updatedAt);`

**Comment by MartinSchoeler** [comment]
Closed by #15295
