### ISSUE TITLE
RocketChat sending infinite amount of requests to my  app

### ISSUE THREAD

**Issue by xielinhui** [RocketChat/Rocket.Chat#14865]
I use websocket to listen to channel information, a user sends a message to the channel, but the websocket receives a number of channel information sent by this user.

**Comment by reetp** [comment]
@rocket-cat close

I can't see a bug here. I'm don't believe you should be accessing the websocket directly.

Use the API as intended.

https://rocket.chat/docs/developer-guides/

If you think that Rocket chat is broken please fill out a proper bug report.
 https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
