### ISSUE TITLE
Custom emojis no longer preferenced over defaults

### ISSUE THREAD

**Issue by jt28828** [RocketChat/Rocket.Chat#14864]
### Description:

Custom emojis with the same name as a default emojis used to appear instead of the defaults. They no longer do this, showing the default emoji instead

### Steps to reproduce:

1. Create a custom emoji with the same name or alias as a default emoji. eg: smile
2. Use the custom emoji in a channel. It will show the default emoji instead of the custom one as it did in the past.

### Expected behavior:

Custom emoji should be displayed instead of the default, as they did in the past

### Actual behavior:

Default emojis are now displayed instead of the custom created one.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 18.04
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4
- MongoDB Version: 3.4.20

**Comment by swagathaur** [comment]
Yeah I noticed this, I've lost some of emojis that were references to some pretty nice times in the companies history. Wont do to leave them out like this :(
