### ISSUE TITLE
Js and html files are not uploading

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#1486]
Im getting the error "This filetype is not accepted, close" message when uploading js files.

**Comment by k0nsl** [comment]
@geekgonecrazy gave me the tip of adding the appropriate file types (effectively whitelisting them), and when you've done that restart the instance and voilà! It works.

**Comment by pavankumarkatakam** [comment]
I have added application/* in file Uploadsection, but no result. regarding the restart instance im using docker, so is restarting  docker containers restart the instance?\?

**Comment by pavankumarkatakam** [comment]
Yes, it works.
