### ISSUE TITLE
Sudden I/O errors after a couple days of uptime

### ISSUE THREAD

**Issue by novacrazy** [RocketChat/Rocket.Chat#14873]
### Description:

I've only experienced this twice, so I'm not sure exactly what's happening yet.

Before we upgraded to post-1.0, our server would crash daily, like clockwork, because of a bug in the OEmbed cache cleanup job.

Now, a week after upgrading to 1.2.0-develop (latest as of a week ago), I've noticed that after 2 days of uptime, out of nowhere we start getting a ton of IO errors and files that won't load correctly. We have around 9k files on the server from the past four months.

This starts with this error many times:

```
Exception in added observe/observeChanges callback: TypeError: Cannot destructure property `username` of 'undefined' or 'null'.
    at added (server/lib/roomFiles.js:16:53)
    at runWithEnvironment (packages/meteor.js:1356:24)
    at packages/meteor.js:1369:14
    at packages/mongo/observe_multiplex.js:182:30
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:176:9)
    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:987:16)
    at packages/meteor.js:964:12
```

Followed by tens to hundreds of:

```
ufs: cannot read file "mJiMKJkmWqBjREqwm" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "Q2k5AZsK6wGNw45WY" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "b7XRwDjzH2bspybkr" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "x6As7LXhP9TcJjWnq" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "Rk3qqP6SMGT4ENSSo" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "7vLfD3H5QAARiGzTf" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "oFekXTFmv4eH9cyYo" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "ey5i3YirtkTuCKNam" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
ufs: cannot read file "W4z7diprCpeG2vAgg" (EIO: i/o error, read) { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
```

Then just as many or more of:

```
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }
Exception in callback of async function: { Error: EIO: i/o error, read errno: -5, code: 'EIO', syscall: 'read' }

```

and the only thing that stops this is restarting the Docker container.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0-develop
- Operating System: Linux/Ubuntu Server
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0.6

### Additional context

Our filesystem setup is rather complicated.

The server docker files are located on an encrypted ZFS virtual disk mounted as a regular folder on the VPS filesystem.

For upload file storage, we're using `rclone` to mount an encrypted and cached cloud storage provider as a regular folder inside that encrypted ZFS filesystem.

However, it's worked fine for four months now, and works fine immediately upon restarting Rocket.Chat. The only way it could be screwing up is either in Rocket.Chat, or in how Docker mounts/binds to that directory. The timing is too odd for me to think it's Docker's fault, which leaves only Rocket.Chat

### Relevant logs:

Shown above in the description.

**Comment by reetp** [comment]
A couple of things to check/test.

Currently recommended settings here.
https://github.com/RocketChat/Rocket.Chat/releases/tag/1.1.3
Node: 8.11.4 (you have 8.15.1)
NPM: 6.4.1
MongoDB: 3.2, 3.4, 3.6, 4.0

I had a look at this for rclone mount.

https://rclone.org/commands/rclone_mount/

> Limitations

> Without the use of “--vfs-cache-mode” this can only write files sequentially, it can only seek when reading. This means that many applications won’t work with their files on an rclone mount without “--vfs-cache-mode writes” or “--vfs-cache-mode full”. See the File Caching section for more info.

Wondering if that is related to `syscall: 'read'` ?

Also:
> rclone mount vs rclone sync/copy

> File systems expect things to be 100% reliable, whereas cloud storage systems are a long way from 100% reliable. The rclone sync/copy commands cope with this with lots of retries. However rclone mount can’t use retries in the same way without making local copies of the uploads. Look at the file caching for solutions to make mount more reliable.

So I am wondering if rclone might be worth looking at? There is plenty more in that page.

**Comment by novacrazy** [comment]
Well, while we were on Rocket.Chat pre-1.0, the Rocket.Chat server itself would crash daily, but Docker would automatically restart it. However, our `rclone` mount was stable for like an entire month straight once (that streak only stopped by other factors), with no other services having issues with it during that time. I thoroughly tested its ability to seamlessly move in/out new/old files. (It's honestly pretty awesome)

Even now, `rclone` is running the same daemon session started about a week ago.

However, what I found notably odd is that these I/O errors happen *after* the `TypeError`s. It's like that error poisoned something.

I may just have to set a cron job to restart the server every 24 hours.

**Comment by Hudell** [comment]
Does it continue to happen everytime Rocket.Chat is up for a few days?

The TypeError you mentioned is happening when a new file is added to the room with an invalid user id.

**Comment by novacrazy** [comment]
It does. Seems to be at around 60 hours of uptime, but still pretty random. 

Odd thing to note, is that last time it happened the process zombied and I had to restart the whole actual server machine, not just the process. However, not sure if that's Rocket or Docker's fault.

**Comment by novacrazy** [comment]
As it turns out, it really was `rclone mount` to blame. I'm still unsure why simply restarting the server process fixed things, but after six months or restarting it every other day, I finally moved off of `rclone mount` to a regular-ish disk, and it's been going fine for a week. Knock on wood.
