### ISSUE TITLE
Feature: Livechat, user name and email integration with system

### ISSUE THREAD

**Issue by nodje** [RocketChat/Rocket.Chat#14877]
What would be a good approach to be able to pre-fill Name and Email with the system logged in user's information?

**Comment by reetp** [comment]
@rocket-cat close

For support please ask in forums.rocket.chat or open.rocket.chat #support 

NFRs go here:
https://github.com/RocketChat/feature-requests/issues

**Comment by nodje** [comment]
Thanks, couldn't find it

**Comment by renatobecker** [comment]
> Thanks, couldn't find it

As @reetp described before, for this kind of question please ask in our forum.
But answering your question, please take a look at here:  https://rocket.chat/docs/developer-guides/livechat-api/#set-theme-options
