### ISSUE TITLE
Desktop notifications causing Chrome tab to freeze, no notifications for others

### ISSUE THREAD

**Issue by friiks** [RocketChat/Rocket.Chat#14875]
### Description:

We started to experience issues with RocketChat web version freezing on our Pixelbook/Chromebook/Chromebox devices as they're using the web-client version of RC.
I pinpointed the problem down to desktop notifications as once those are turned off in user settings no more crashes occur.
To give further information - desktop notifications are not working on the few win10 devices as well. We are using the official Windows client for these computers. No crashes occur, but no notifications are not shown as well.

### Steps to reproduce:

1. Log into web-client of rocketchat with a Chrome device
2. Get someone to send you a message to trigger desktop notification
3. Wait out the window freeze until "this tab has crashed" popup appears

### Expected behavior:

Desktop notification is shown.

### Actual behavior:

Desktop notification is not shown, window freezes.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 17.10
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.20

### Additional context

This is not an issue with the latest version of RC server - we have been experiencing this for about 1-2 months.

### Relevant logs:

I can't seem to find anything relevant to these errors.

**Comment by paulpopus** [comment]
This also happens with the electron wrapper, instead just the app freezes though as it's a separate instance. Very annoying and not sure how to fix it.
