### ISSUE TITLE
multiple different rocket chat instances  on one mongo db instance 

### ISSUE THREAD

**Issue by alnikitich** [RocketChat/Rocket.Chat#14874]
Can I run multiple instances of rocket chat (one for each project) with one instance of mongoDB (one oplog)?

And can I use one mongoDB instance on external hosting with multiple (different) Rocket Chat instances?

Thank you!

**Comment by aermike** [comment]
Hi
You can run multiple rockeetchat instances with an oplog instance MongoDB
In rocketcat.service you can specify IP for mongodb instance(internal or external)
Beware for acces on mongoDB

**Comment by reetp** [comment]
@rocket-cat close

This is a support Issue and not a bug.

Please ask in forums.rocket.chat or open.rocket.chat #support
