### ISSUE TITLE
Video message sent into wrong channel if recording was canceled before

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#14872]
### Description:

Video message can be sent into wrong channel when it was canceled in a different channel before uploaded in first place.
 
### Steps to reproduce:

1. Go to `#channel_first`
2. Record a new video message
3. Cancel out the video message popup
4. Switch active channel to `#channel_second`
5. Record a new video message and upload it

### Expected behavior:

Video message should have been sent to `#channel_second`, since this was the channel it was created from.

### Actual behavior:

Video message is sent to `#channel_first`.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Additional context

Demo video of the problem:

[![](https://up.frd.mn/Ldi56CtZQw.png)](https://up.frd.mn/hQPnG8h5YJ.mp4)

**Comment by orelinde** [comment]
It happens to me as well, without the cancel option (Step 3). In the Browser as well in the Electron Client.

The user/channel the video SHOULD go to, DO recevie a notification of 1 unread message. The video/message itself goes into another channel/user.

Version | 2.0.0-develop
Apps Engine Version | 1.5.2
Node Version | v8.16.2
Mongo Version | 4.0.13
