### ISSUE TITLE
Cannot view users list

### ISSUE THREAD

**Issue by caesarcxiv** [RocketChat/Rocket.Chat#14870]
### Description:

Users list does not display properly

### Steps to reproduce:

1. Administration
2. Users

### Expected behavior:

View users list

### Actual behavior:

![image](https://user-images.githubusercontent.com/13050060/60104662-ea335300-972f-11e9-9947-ed96181f74e7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.13
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by kevinfaguiar** [comment]
Does the javascript console log show anything? What about the Rocket.Chat server log?

**Comment by caesarcxiv** [comment]
> Does the javascript console log show anything? What about the RocketChat server log?

Nothing in error logs. Here is the html generated. User info is there, just not displayed properly.

![image](https://user-images.githubusercontent.com/13050060/60130622-9b081500-9765-11e9-9c6e-eeb4160d6713.png)

**Comment by MartinSchoeler** [comment]
@caesarcxiv What is the browser/version that is being used?

**Comment by caesarcxiv** [comment]
I would have tested sooner but the snap builds are 30-60 days behind. 

Server updated to 1.2.3

Table-wrapper has a computed width of 0px. Adjusting this manually in Chrome allows us to disable users. 

Tried edge and chrome - latest builds.

**Comment by ggazzo** [comment]
sorry @caesarcxiv but I'm  not able to reproduce your problem..
![image](https://user-images.githubusercontent.com/5263975/67043787-39e3c300-f101-11e9-8ef9-6a429fc36060.png)
if the problem persists please let me know
