### ISSUE TITLE
SAML: Logout not working

### ISSUE THREAD

**Issue by pkolmann** [RocketChat/Rocket.Chat#14881]
### Description:

I have SAML Login enabled for Rocket.Chat. If I have set the Logout Behavior to 'Terminate SAML Session' I will get logged out of the SAML Session properly, but when I return to my Rocket.Chat instance I am still logged in.

If I change the SAML Logout behavior to 'Only Log Out from Rocket.Chat' the rocket.chat session is terminated. 

### Steps to reproduce:

1. Have SAML Login enabled
2. login to rocketchat and set Logout behaviour to 'Terminate SAML Session'
3. logout
4. see that you are redirected to your SAML Provider and be logged out there
5. navigate back to rocket.chat and still be logged in

### Expected behavior:

At step 5 the expected behavior is to be logged out from rocket.chat.

### Actual behavior:

session is still active

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 8
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.16.0
- MongoDB Version: 3.2.11

**Comment by nickfroehl** [comment]
Having same/similar issue. My RocketChat server sits behind and nginx SSL reverse proxy. When attempting to log out (which queries https://<RC hostname>/_saml/logout/<SP name>?<SAMLResponse=...>), I land on an nginx error page indicating the requested page was unavailable; when I navigate back to RocketChat, the SAML session is still active. I am able to hit https://<RC hostname>/_saml/logout/<SP name> without issue when providing no data in the url. I am using ADFS as the IdP. Config as follows:

Rocket.Chat Version: 1.2.0
OS: Centos 7
Deployment: Manual
DB Replicaset Oplog: Enabled
NodeJS Version: v8.11.4
MongoDB Version: v4.0.10

RocketChat SAML Config:
  Custom Entry Point: https://<ADFS hostname>/adfs/ls/
  IDP SLO Redirect URL: https://<ADFS hostname>/adfs/ls/
  Custom Issuer: https://<RC hostname>/_saml/metadata/<SP name>
  Logout Behavior: Terminate SAML-session

ADFS Relying Party Trust Config:
  SAML Logout Endpoints: 
    Binding: Redirect
    Trusted URL: https://<RC hostname>/_saml/logout/<SP name>
    Response URL: https://<RC hostname>/_saml/logout/<SP name>
  Encryption Cert: not configured (RC seems unable to use encrypted SAML?)
  Signature Cert: Configured, seems to work just fine

**Comment by nickfroehl** [comment]
Having same/similar issue. My RocketChat server sits behind and nginx SSL reverse proxy. When attempting to log out (which queries https://\<RC hostname\>/_saml/logout/\<SP name\>?\<SAMLResponse=...\>), I land on an nginx error page indicating the requested page was unavailable; when I navigate back to RocketChat, the SAML session is still active. I am able to hit https://\<RC hostname\>/_saml/logout/\<SP name\> without issue when providing no data in the url. I am using ADFS as the IdP. Config as follows:

Rocket.Chat Version: 1.2.0
OS: Centos 7
Deployment: Manual
DB Replicaset Oplog: Enabled
NodeJS Version: v8.11.4
MongoDB Version: v4.0.10

RocketChat SAML Config:
  Custom Entry Point: https://\<ADFS hostname\>/adfs/ls/
  IDP SLO Redirect URL: https://\<ADFS hostname\>/adfs/ls/
  Custom Issuer: https://\<RC hostname\>/_saml/metadata/\<SP name\>
  Logout Behavior: Terminate SAML-session

ADFS Relying Party Trust Config:
  SAML Logout Endpoints: 
    Binding: Redirect
    Trusted URL: https://\<RC hostname\>/_saml/logout/\<SP name\>
    Response URL: https://\<RC hostname\>/_saml/logout/\<SP name\>
  Encryption Cert: not configured (RC seems unable to use encrypted SAML?)
  Signature Cert: Configured, seems to work just fine

**Comment by pierre-lehnen-rc** [comment]
Is this error still happening on the current version of Rocket.Chat? There have been a number of fixes on the logout behavior since the issue was first opened, so I assume it should be working properly now.

**Comment by 1rV1N-git** [comment]
I have version 3.1.1 with the same bug.
