### ISSUE TITLE
Using permalink in discussion to get back to parent channel not working when it was created from a direct message

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#14883]
### Description:

When you click the date/time next to the room name in a discussion to get back to the parent channel, Rocket.Chat returns a "Oops, page not found" error when the discussion was created from a direct messages room.

### Steps to reproduce:

1. Go to any direct message
2. Create a discussion from a message
3. Click the date/time next to the room name in the discussion

### Expected behavior:

To get back to the direct message room where the discussion was created from.

### Actual behavior:

"Oops, page not found" error message

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Additional context

![Ohne Titelnew mov](https://user-images.githubusercontent.com/944459/60282886-3e912b00-9908-11e9-8af2-01738bab4c05.gif)

**Comment by subham103** [comment]
Looking forward to work on this issue:)
