### ISSUE TITLE
Member list shows empty users that can't be deleted

### ISSUE THREAD

**Issue by ixlandia** [RocketChat/Rocket.Chat#14896]
The Members List in some channels is showing blank users that cannot be removed from the room. It may be due to users being deleted, but I can't really tell. Member count is also incorrect.
![image](https://user-images.githubusercontent.com/48101296/60360496-da26a800-99a9-11e9-8dc4-49942c767129.png)
![image](https://user-images.githubusercontent.com/48101296/60360636-240f8e00-99aa-11e9-8663-5e1f95a33b27.png)

**Comment by dennishenry** [comment]
@ixlandia Did you figure this out? We're having the same issue with our installation. The actual members are listed at the very bottom:

<img width="410" alt="Screen Shot 2020-01-29 at 9 17 55 AM" src="https://user-images.githubusercontent.com/4305001/73364294-52bf5100-4278-11ea-88f0-d4987fd24c4e.png">

**Comment by ixlandia** [comment]
I realized it had happened earlier on in our installation, when we were still experimenting with settings. The Active Directory integration had imported everyone, and we didn't want _all_ the users showing in there, especially not the ones that were service accounts. So we had cleared the **users** collection in mongodb.
Unfortunately, the entries remained in **rocketchat_subscription** and had to be cleared from there as well. I deleted all the entries from **rocketchat_subscription** where the value in **u._id** did not exist in the **users** collection.
I believe I had to manually edit the **usersCount** value in **rocketchat_room** as well.
