### ISSUE TITLE
1.2.0 never starts

### ISSUE THREAD

**Issue by mzch** [RocketChat/Rocket.Chat#14891]
### Description:
After updating 1.2.0, RocketChat doesn't start throwing an exceptioin.

### Steps to reproduce:

1. Get tar ball from https://releases.rocket.chat/latest/download
2.  Extract it and move contents to deployment directory.
3.  Tried to start Rocketchat but failed.

### Expected behavior:
Start successfully.

### Actual behavior:
Throw an exception.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0
- Operating System: Debian GNU/Linux 10 (Buster)
- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.16.0
- MongoDB Version: 4.0.10

### Relevant logs:

```
Jun 27 22:49:45 v14 systemd[1]: rocketchat.service: Succeeded.
Jun 27 22:49:45 v14 systemd[1]: Stopped The Rocket.Chat server.
Jun 27 22:50:24 v14 systemd[1]: Started The Rocket.Chat server.
Jun 27 22:50:25 v14 rocketchat[4286]: module.js:550
Jun 27 22:50:25 v14 rocketchat[4286]:     throw err;
Jun 27 22:50:25 v14 rocketchat[4286]:     ^
Jun 27 22:50:25 v14 rocketchat[4286]: Error: Cannot find module 'fibers'
Jun 27 22:50:25 v14 rocketchat[4286]:     at Function.Module._resolveFilename (module.js:5
48:15)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Function.Module._load (module.js:475:25)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Module.require (module.js:597:17)
Jun 27 22:50:25 v14 rocketchat[4286]:     at require (internal/module.js:11:18)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Object.<anonymous> (/srv/Rocket.Chat/programs/server/boot.js:1:75)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Module._compile (module.js:653:30)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Object.Module._extensions..js (module.js:664:10)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Module.load (module.js:566:32)
Jun 27 22:50:25 v14 rocketchat[4286]:     at tryModuleLoad (module.js:506:12)
Jun 27 22:50:25 v14 rocketchat[4286]:     at Function.Module._load (module.js:498:3)
Jun 27 22:50:25 v14 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Jun 27 22:50:25 v14 systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

**Comment by TwizzyDizzy** [comment]
Cannot confirm here...

![image](https://user-images.githubusercontent.com/179595/60331806-c7a27380-9995-11e9-9c66-5a8244880be2.png)

> Version of Rocket.Chat Server: 1.2.0
> Operating System: Oracle Linux 7
> Deployment Method: tar
> Number of Running Instances: 1
> DB Replicaset Oplog: Enabled
> NodeJS Version: 8.16.0
> MongoDB Version: 3.6.13

**Comment by himpierre** [comment]
@mzch Did you install the npm modules? If you grab the tarball you have to unpack it, change to bundle/program/server and issue the command `npm install`.

**Comment by reetp** [comment]
Make sure you follow the guide correctly:
https://rocket.chat/docs/installation/manual-installation/debian/

It is also worth sticking with recommened software versions:
https://github.com/RocketChat/Rocket.Chat/releases/tag/1.2.0


>     Node: 8.11.4
>     NPM: 6.4.1
>     MongoDB: 3.2, 3.4, 3.6, 4.0

**Comment by mzch** [comment]
Oh, sorry, I forgot it. Thanks!
