### ISSUE TITLE
when creating new user give me an error "You must be login to do this"

### ISSUE THREAD

**Issue by AhmadShahid** [RocketChat/Rocket.Chat#14899]
when i want to create new user then it's give me an error "You must be login to do this"

![create-user-error](https://user-images.githubusercontent.com/10240075/60388491-ddb25000-9acb-11e9-8ee4-a50d95d088be.png)

**Comment by reetp** [comment]
Unless you give a lot more information then no one can help you.

Use this link and provide the requested details.
 https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

I strongly suspect this is a supprt issue and not a bug.

Unless you have evidence to show an actual issue in Rocket please close this and ask here.

https://forums.rocket.chat/ or # support at https://open.rocket.chat/
