### ISSUE TITLE
rocketchat slow when switched from background tab

### ISSUE THREAD

**Issue by haosdent** [RocketChat/Rocket.Chat#1489]
In general case, Rocket chat runs well. But when I switch to another browser tabs. And then after a while, switch back to it. It sucks and slow at first several seconds, them back to normal. What is the possible problem of this?

**Comment by geekgonecrazy** [comment]
Lets ignore the sucks part ;)  cause obviously being slow sucks.  Can you give more details about what exactly is slow when you switch back to the tab?  Details are what help us look into this.  Thanks :+1:

**Comment by haosdent** [comment]
>Can you give more details about what exactly is slow when you switch back to the tab
Thank you. I could not operate the page include scroll, click in first several seconds after switch back. Maybe I should use "sucks" more excatly

**Comment by geekgonecrazy** [comment]
@haosdent so it completely locked up?

**Comment by haosdent** [comment]
yes, completely locked up

On Thu, Nov 26, 2015 at 1:23 AM, Aaron Ogle <notifications@github.com>
wrote:

> @haosdent <https://github.com/haosdent> so it completely locked up?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/1489#issuecomment-159679521>
> .
>



-- 
Best Regards,
Haosdent Huang

**Comment by Sing-Li** [comment]
@haosdent - can you please confirm that it happens both on Firefox latest and Chrome latest?  Or are you just experiencing this with Chrome?   TIA

**Comment by haosdent** [comment]
yes.
According my record, seems blocking at
```
  function onGlobalMessage(event) {
    // This will catch all incoming messages (even from other
    // windows!), so we need to try reasonably hard to avoid letting
    // anyone else trick us into firing off. We test the origin is
    // still this window, and that a (randomly generated)
    // unpredictable identifying prefix is present.
```
in setimmediate.js

**Comment by haosdent** [comment]
I use Chrome Timeline to record

**Comment by haosdent** [comment]
I think maybe cause Rocket.Chat have too much "Tracker.autorun"?

**Comment by Sing-Li** [comment]
Can you please try Firefox latest - and confirm that *IT DOES NOT* happen with Firefox?  Thanks.

**Comment by haosdent** [comment]
I try this in both Chrome and Safari.

**Comment by haosdent** [comment]
Because firefox seems not working well for rocket.chat

**Comment by Sing-Li** [comment]
We need some test on Firefox on this case.  Both Chrome and Safari are webkit based.  Thanks.

**Comment by haosdent** [comment]
I think when "loading more from history", the blocking behaviour also looks similar

**Comment by haosdent** [comment]
check this in this newest firebox, still exist.

**Comment by haosdent** [comment]
it also sucks when switch between channels.

**Comment by haosdent** [comment]
According trace, I found it is because Meteor render every message too waste time. Most times are blocking in `Template.message.onCreated`.

**Comment by haosdent** [comment]
Maybe just append few messages, but Rocketchat re render whole 
```
						{{#each messagesHistory}}
							{{#nrr nrrargs 'message' .}}{{/nrr}}
						{{/each}}
```
And not insert once, would insert every exists messages times.

**Comment by haosdent** [comment]
Sorry, it is my fault. My code
```
	messagesHistory: ->
		messages = ChatMessage.find { rid: this._id, t: { '$ne': 't' }  }, { sort: { ts: 1 } }
                messages = messages.fetch()
		return messages
```
so as same as RocketChat current code. It cause Meteor rebuild all every time.
