### ISSUE TITLE
Very narrow input field in python's WebKit

### ISSUE THREAD

**Issue by mk-pmb** [RocketChat/Rocket.Chat#14897]
### Description:

The text input below the chatroom is very narrow.

### Steps to reproduce:

1. Use Ubuntu 16.04.6 LTS xenial, kernel 4.4.0-154-generic,
  machine/CPU/platform: x86_64 x86_64 x86_64,
  Xfce 4.12, Python 2.7.12, libgtk-3-0 (version 3.18.9-1ubuntu3.3), libwebkitgtk-3.0-0 (version 2.4.11-0ubuntu0.1)
1. Make a simple python app that renders a webkit frame holding
  https://open.rocket.chat/ or use [my example script](https://github.com/mk-pmb/pywebkitapp-pmb/blob/master/docs/examples/rocket_chat.sh) (see Readme for how to install).
1. Try to chat with people.
1. In my case, it looks like this: [screenshot](http://l.proggr.de/?19565t5se)

### Expected behavior:

Much space is used for my text, while the buttons on the side are narrow.

### Actual behavior:

Exact opposite. [Screenshot.](http://l.proggr.de/?19565t5se)

### Server Setup Information:

Dunno, whatever https://open.rocket.chat/ ran on 2019-06-25, 22:50 UTC.

**Comment by reetp** [comment]
You asked this in open.rocket.chat a few days ago.

Can you describe what the bug is in Rocket because there is no evidence so far? This is for bugs, not general coding support.

This seems to either an issue with your coding (notabug - ask in open.rocket.chat or the forums) or asking Rocket to do something it was not designed to do, in which you may look at a new feature request if you can define what is you would like Rocket to do.

https://github.com/RocketChat/feature-requests/issues

**Comment by mk-pmb** [comment]
> Can you describe what the bug is in Rocket because there is no evidence so far?

I assumed the UI of the webpage that provides the chat was part of Rocket.Chat. Was I mistaken?

> This is for bugs,

Yeah, I know. I considered the suboptimal layout a bug. Is it not?

> not general coding support.

I did not mean to request any. My intent was to help improve Rocket.Chat so it renders correctly in a WebKit WebView as described, without requiring additional features from the app that instantiates the WebView. Have you tried a WebView with said versions? Did it render narrow buttons and a wide text input for you?

> This seems to either an issue with your coding

Nah, I strongly believe this is about rendering inside the WebView.
In case you tried with just WKA and have doubts whether the bug might be introduced by WKA code, here's [a screenshot](http://l.proggr.de/?195ad4pur) of how it looks in Epiphany 3.10.3, albeit with an even older WebKit 2.4.10. Feel free to test any other methods of instantiating the WebView; maybe it's just a very unfortunate case where the Gnome Devs and I made the exact same mistake in displaying the WebView.

Unfortunately, WKA doesn't have debug features yet and my epiphany crashes when trying to "Inspect element", so I can only guess that it's about CSS.

> or asking Rocket to do something it was not designed to do,

Not sure what you mean. Are you saying rendering in these versions of WebKit is outside project scope?

**Comment by mk-pmb** [comment]
Originally I forgot to mention the versions of `libgtk-3-0` and `libwebkitgtk-3.0-0`. I've added them to the opening post just now.

**Comment by geekgonecrazy** [comment]
This does seem like something is up with rendering there.  However it’s not an officially supported browser or client. 

Our other WebKit based browser that we do support (safari) doesn’t seem to have this issue.  

I’ll leave this open maybe another dev here in the community will be able to track this down and open a Pr to fix.

**Comment by mk-pmb** [comment]
I'll just abandon this issue because it's no longer relevant for me.
