### ISSUE TITLE
SAML new username issue

### ISSUE THREAD

**Issue by makhoff** [RocketChat/Rocket.Chat#14895]
### Description:

Hello.
When I configured SAML with settings from [this issue](https://github.com/RocketChat/Rocket.Chat/issues/2770), new user created in format "Display Name, login" and I can't manage him from RocketChat console(only via REST API) .

In logs I see that parameter username received as "username":["XXX, YYY","TSTDMN\\xxx.yyy"]" instead of ""username":["XXX, YYY"]"

### Steps to reproduce:

1. Configure SAML with ADFS
2. Set "Generate Username" = false
3. Sign in with new SSO user

### Expected behavior:

Got username in  format ""username":["XXX, YYY"]"

### Actual behavior:

![rch1](https://user-images.githubusercontent.com/52325340/60352169-f3424f80-99cf-11e9-9681-185757bba3e2.jpg)
![rch2](https://user-images.githubusercontent.com/52325340/60352170-f3424f80-99cf-11e9-8840-f50f93572952.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0
- Operating System: RHEL 7
- Deployment Method: on premise
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

### Relevant logs:

RESULT :{"profile":{"inResponseToId":"id-JPKNNNsuCovo5t8CD","issuer":"http://MYDOMAIN.com/adfs/services/trust","nameID":"USER@MYDOMAIN.com","nameIDFormat":"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress","sessionIndex":"_921934bf-672a-4364-b281-432732f36c6e",**"username":["DISPLAY NAME","DOMAIN\\sAMAccountaname"],"**email":"MY_EMAIL","http://schemas-xmlsoap-org/ws/2005/05/identity/claims/name":"DISPLAY NAME",

**Comment by routerino** [comment]
Any progress on this? Encountering this identical issue and it's making me tear my hair out.

**Comment by 1rV1N-git** [comment]
@makhoff Change in this place to "cn"
![image](https://user-images.githubusercontent.com/34376228/79453040-c6f4cf80-7ff1-11ea-990e-14e8f5a7c9ce.png)
