### ISSUE TITLE
Channel Anouncements not working

### ISSUE THREAD

**Issue by mikeaer** [RocketChat/Rocket.Chat#14905]
### Steps to reproduce:

1. room info
2. edit
3. write announcement

### Expected behavior:

Announcement appear on top of channel room

### Actual behavior:

Announcement NOT appear on top of channel room
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: CentOS
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.9

**Comment by reetp** [comment]
You missed out your Rocket version.
Please advise. Also please test on latest 1.2.x

**Comment by mikeaer** [comment]
Rocket.Chat 1.2.1

**Comment by novacrazy** [comment]
I get this on 1.3.0-develop. It does save, but it takes a page refresh to show up. I assume it doesn't immediately show up for other users, either, because it took three days after an announcement for users to notice #14346 was still a problem.

**Comment by MIKI785** [comment]
This is also an issue for me on 1.2.3 (snap).

**Comment by serviceman** [comment]
Also an issue on 2.0.0 rc2

**Comment by cyri11e** [comment]
same,  must CTRL+R to refresh, annoying

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15615
