### ISSUE TITLE
Create a Zoom Video Conference Integration

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#14908]

**Comment by d-gubert** [comment]
Version 1 for the app could be a simple slashcommand, such as `/zoom`, which accesses the Zoom API and creates a link for a meeting.

The server admin will need to get Zoom API credentials and configure them in the app's settings screen

**Comment by mkretzer** [comment]
Is there any work done on this?

**Comment by didacroyo** [comment]
I've purchased ($5) the Rocketchat official APP available in the Rocketchat marketplace, but it returns error 124. Not working.

**Comment by d-gubert** [comment]
hey @didacroyo ! have you reach out to our support team? the address is listed in the support link inside the app detail page - so we'll be able to help you out.

**Comment by d-gubert** [comment]
Closing this as the Zoom Rocket.Chat App is available at our Marketplace :)

**Comment by didacroyo** [comment]
I purchased a Zoom PRO license and associated a couple of rocketchat users (their emails) to the parent licensed email. Now it works, the problem I see is that the person who starts the zoom session is the host instead and, unless the user is also a licensed user, the 40min limit apply

**Comment by engelgabriel** [comment]
What would you suggest? being able to configure a preferred account to create all the meetings?

**Comment by didacroyo** [comment]
Yes, that is the idea. 

The Key and Secret configured in the app settings would be the preferred account for being the meeting host. The rest only have to join the meeting and enjoy the meeting with no 40min limit. 

The main issue I see  would be when there is an ongoing meeting, then the /zoom command should provide a feedback like this: 

"There is 1 ongoing meeting which started 50 min ago using the licensed account configured in the /zoom app settings. You can use this join link with you (xxxxxxx) as the host: https://yyyyyyy"

Does this make sense for you?

**Comment by urosino** [comment]
I appreciate the hard work you all have put into this integration. It's been incredibly useful.

However, I've been experiencing issues after the latest update of Rocket.chat to 6.1.7 where the Zoom integration seems to have stopped working. Is anyone else encountering this problem, or is it just on my end? 

Any assistance or advice on how to troubleshoot this would be greatly appreciated. 

![l8stele1X](https://github.com/RocketChat/Rocket.Chat/assets/25570106/c4f2c6d6-4163-4388-9209-88c7b9cef821)

Thank you in advance!
