### ISSUE TITLE
loadMissedMessages method giving empty response

### ISSUE THREAD

**Issue by ganesh2shiv** [RocketChat/Rocket.Chat#1490]
I am using [this Android DDP library](https://github.com/delight-im/Android-DDP)  in my app to communicate with the rocket chat app installed on my local machine. I am trying to access the unread messages on a channel/room by calling loadMissedMessages method like this:

        MeteorSingleton.getInstance().call("loadMissedMessages", obj, this);

and passing proper parameters (roomId and timestamp) and I get a success callback from it but when I check the body of the response (fieldsJson) it's completely empty.

    @Override
    public void onSuccess(String fieldsJson) {
        System.out.println("Success : " + fieldsJson);
    }

What could possibly be wrong here?

**Comment by geekgonecrazy** [comment]
@ganesh2shiv please find me on our demo server in [#support](https://demo.rocket.chat/channel/support) if you still have this issue.  I think your very specific implementation question would be easier answered in chat 👍
