### ISSUE TITLE
Canned responses in Livechat

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#14911]
Hi!

To increase the speed of processing requests in livechat it would be good to be able to insert canned responses.

For example, how it works in livechat https://www.livechatinc.com/help/canned-responses/

Maybe should add this feature in livechat? Thanks

**Comment by reetp** [comment]
@rocket-cat close

It's a feature request, not a bug.

Please open it here:
https://github.com/RocketChat/feature-requests

(You may also want to look at bots?)

**Comment by antkaz** [comment]
Ok! Thank you!

We need the ability to insert canned responses already in the process of dialogue with the user, so the bots here are not entirely appropriate

**Comment by renatobecker** [comment]
> Hi!
> 
> To increase the speed of processing requests in livechat it would be good to be able to insert canned responses.
> 
> For example, how it works in livechat https://www.livechatinc.com/help/canned-responses/
> 
> Maybe should add this feature in livechat? Thanks

This feature is already planned to be implemented as an **Enterprise feature**.
Thanks.

**Comment by antkaz** [comment]
@renatobecker 
This feature will be available only as an Enterprise feature?
