### ISSUE TITLE
Livechat triggers not working with registerGuest callback

### ISSUE THREAD

**Issue by sebudot** [RocketChat/Rocket.Chat#14919]
Description:
Routing method guest pool.
Trigger added with custom agent.

When using registerGuest callback instead of setGuestName,setGuestEmail... the trigger shows the message then the window refreshes and it disappears.
To be noted that it functions normally when we register the visitor using setGuestName,setGuestEmail...

Steps to reproduce:
Trigger added 
Register visitor with registerGuest callback

Expected behavior:
Trigger message should be visible when conversation is starting

Server Setup Information:

Version of Rocket.Chat Server: 1.0.3
Operating System: Ubuntu 16.04.4 x64
Deployment Method: snap
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: v8.11.4

**Comment by renatobecker** [comment]
@sebudot The Livechat triggers are only fired if the visitor is not yet registered.
Thanks.
