### ISSUE TITLE
Users cannot join readonly room

### ISSUE THREAD

**Issue by novacrazy** [RocketChat/Rocket.Chat#14910]
### Description:

Users cannot join a readonly room. The join button simply doesn't exist.

### Expected behavior:

For it to be joinable like any regular room, but read-only.

### Actual behavior:

Unable to do anything:

![literally nothing](https://user-images.githubusercontent.com/4708645/60484414-23535200-9c5f-11e9-896e-866b82917efc.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.0-develop (latest as of writing this)
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0.3

**Comment by regetskcob** [comment]
Additionally it's impossible to add a read-only channel to your favorites.

**Comment by Tirvanel** [comment]
I am also seeing this behavior on RocketChat 1.1.1. Is there any update to this issue. I need users to be able to join read-only channels for my use case of an announcement channel.

**Comment by novacrazy** [comment]
@Tirvanel You should set your announcement room as a default room in the meantime, and manually join existing users. Standalone read-only rooms may as well not exist.

**Comment by mes85** [comment]
Affects my installation on 1.3.2 and 2.1.2

I think it is an interesting fact, that if you set a channel to read-only and default, a completly new user will auto-join the channel on registration and be muted. This would in my opinion be the default behavior if someone [an already existing user] joins a read-only channel.

**Comment by mohanbabubb** [comment]
Additionally it's impossible to add a read-only channel to your favorites.

> Additionally it's impossible to add a read-only channel to your favorites.

Its other way, 
1. The channel owner should invite you or you can ask for the channel owner to invite you . so you can see favorite

**Comment by mohanbabubb** [comment]
if we CHANGE sentence from 'you must join to view messages' to 'you must be invited to view messages' , make more sense.
Because invited users can able to join and also add the channel to favorite list

This is kind of clumsy logic,. -1, we should change it

**Comment by localguru** [comment]
Do do see this bug on versions 2.1.1, 2.2.0 and 3.0.0-develop (open.rocket.chat). 

We have a lot of public read-only channels here where we post news via hubot. In the past e.g. in version 0.69.2 it was still possible to join these channels as "normal" users and read messages there. Now the "Join" button is missing, which is extremely unfortunate. Since the bug has been known since the beginning of July, I would be happy about a soon fix.

**Comment by rsimai** [comment]
I can confirm this for 2.2.0, also https://github.com/RocketChat/Rocket.Chat/issues/14910#issuecomment-546602317 and that auto-join works for new users when it's a default read-only channel. Unfortunately that's not the level of self service users expect. It IMO renders announcement channels not usable :-(

**Comment by novacrazy** [comment]
I’m going to try today to see if a bot with near-admin powers can invite users to read-only channels. At least then we don’t have to do it by hand.

**Comment by novacrazy** [comment]
Update: Bots can indeed join users to read-only rooms via the `add-user-to-any-c-room` permission. Just implemented a simple `!join #channel` command for my users.
