### ISSUE TITLE
Suggestion: NodeInfo2 support or ability to join The-Federation

### ISSUE THREAD

**Issue by sunjam** [RocketChat/Rocket.Chat#14913]
Join [The-Federation](http://the-federation.info/), [as mentioned in this request](https://github.com/thefederationinfo/the-federation.info/issues/191#issuecomment-507428669).  This would also make it easy to optionally find out about federated rocket.chat instances via fediverse.network & fediverse.party

> Would be happy to list Rocket.chat instances if either they implement [NodeInfo2](https://git.feneas.org/jaywink/nodeinfo2) (the Diaspora NodeInfo wont be compatible in this case) for federated servers, or if someone contributes a parser for some Rocket.chat specific server metadata that is exposed from federated servers. The parser should be contributed preferably to the [federation library](https://git.feneas.org/jaywink/federation/blob/master/federation/hostmeta/parsers.py) where all the other parsers used live.

**Comment by alansikora** [comment]
Closing it for now, please update to the latest version, 3.6.3
