### ISSUE TITLE
Livechat safari mobile options menu not in view

### ISSUE THREAD

**Issue by sebudot** [RocketChat/Rocket.Chat#14928]
Description:
On safari for mobile and ipad the livechat window seems to need an extra 20px at the bottom for the options menu to be visible

Server Setup Information:

Version of Rocket.Chat Server: 1.0.3
Operating System: Ubuntu 16.04.4 x64
Deployment Method: snap
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: v8.11.4

![rocketchat](https://user-images.githubusercontent.com/22764793/60671223-5114e280-9e7b-11e9-9676-4a6e5489041e.png)

**Comment by renatobecker** [comment]
@sebudot Are you implementing the Livechat widget through a Webview?

**Comment by sebudot** [comment]
@renatobecker No and it works normally on the rest of the browsers.

**Comment by renatobecker** [comment]
The old Livechat version will be deprecated very soon. I suggest you testing the new one.
Thanks.
