### ISSUE TITLE
Autocomplete missing real name

### ISSUE THREAD

**Issue by Antairez** [RocketChat/Rocket.Chat#14927]
### Description:

Autocomplete is missing user's real name in certain group chats.
![image](https://user-images.githubusercontent.com/7032726/60663674-782ade80-9e92-11e9-8777-ca34ab1159ea.png)

### Steps to reproduce:

1. Go to any groupchat
2. Type @ and start looking for users
3. Observe the missing real names

### Expected behavior:

Autocomplete should have every user's real names, disregard any chat room the user is in.

![image](https://user-images.githubusercontent.com/7032726/60663814-d3f56780-9e92-11e9-88fa-a9e8c5819f6a.png)

### Actual behavior:

Getting mixed results in different chat rooms. In some chatrooms you can see user's real name inside autocomplete, in other chat rooms you can't.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Relevant logs:

```
I20190704-19:57:33.559(8) server.js:207 LDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
I20190704-20:00:37.885(8) server.js:207 LDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
I20190704-20:03:38.022(8) server.js:207 LDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
```

**Comment by dganic** [comment]
We have the same problem.

`I20190731-15:51:00.383(3) server.js:207 System ➔ error Error sending message: { Error: [error-not-allowed]     at canSendMessage (app/authorization/server/functions/canSendMessage.js:15:9)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:80:17)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:62:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at resolve (packages/ddp-server/livedata_server.js:1683:36)     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)     at Server.apply (packages/ddp-server/livedata_server.js:1621:26)     at Server.call (packages/ddp-server/livedata_server.js:1603:17)     at DDPCommon.MethodInvocation.Meteor.runAsUser (app/api/server/v1/chat.js:174:59)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at Object.post (app/api/server/v1/chat.js:174:23)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:268:31)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9   isClientSafe: true,   error: 'error-not-allowed',   reason: undefined,   details: undefined,   message: '[error-not-allowed]',   errorType: 'Meteor.Error' } `

`I20190731-16:50:44.340(3) server.js:207 LDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TCP.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } `
