### ISSUE TITLE
Trying to deploy multiple instance in Kubernetes + legacy deploy

### ISSUE THREAD

**Issue by reymonlu** [RocketChat/Rocket.Chat#14923]
Hi,

We deployed multiple instances of rocketchat in our Kubernetes cluster and these instances are connected to a replicaset of MongoDB which is on a dedicated servers. 
We wanted to deploy another Rocketchat instances outside of our cluster in case of Kubernetes going down (we are new in Kubernetes deployments).
We face a problem about INSTANCE_IP variable because in Kubernetes, this IP is not reachable from outside (10.x.x.x) and legacy deployment try to reach those instances.

Is there any workaround to make Rocketchat working in "hybrid" mode ?

Thanks for your help

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit those criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support). If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
