### ISSUE TITLE
LDAP Error Timeout

### ISSUE THREAD

**Issue by perpetuaIwar** [RocketChat/Rocket.Chat#14936]
I20190705-14:04:26.256(-7) server.js:199 LDAP ➔ Connection.error connection time out 1000 
I20190705-14:04:26.292(-7) server.js:199 LDAPHandler ➔ error Error: Timeout     at Timeout.setTimeout (app/ldap/server/ldap.js:179:14)     at ontimeout (timers.js:498:11)     at tryOnTimeout (timers.js:323:5)     at Timer.listOnTimeout (timers.js:290:5) 
I20190705-14:07:51.033(-7) Unloaded the Apps Framework. 
I20190705-14:08:18.022(-7) server.js:199 LDAP ➔ Connection.error connection time out 1000 
I20190705-14:08:18.022(-7) Error: Timeout     at Timeout.setTimeout (app/ldap/server/ldap.js:179:14)     at ontimeout (timers.js:498:11)     at tryOnTimeout (timers.js:323:5)     at Timer.listOnTimeout (timers.js:290:5) 

Rocket.Chat Version: 1.0.3        
NodeJS Version: 8.11.4 - x64                       
MongoDB Version: 3.6.12                               
MongoDB Engine: mmapv1                          
Platform: linux 

I had a previous instance of RocketChat that was running perfectly fine til one day, I had someone complain they could not log on to OwnCloud (Rocketchat / Owncloud running as apps on a Univention Corporate Server). The tcp and host A DNS entries were missing for the Univention server on our domain DNS. I recreated the DNS entries above. Owncloud issue was resolved however I've had issues ever since with RocketChat. I uninstalled RocketChat from the Univention server and reinstalled. Now I cannot get LDAP to connect at all. Using DNS names and IP addresses do not work. In RocketChat, I get "Error Timeout" each time I test the connection. Above are the logs are I receive when I "view logs" in the GUI. OwnCloud runs on the same server and connect to LDAP fine. RocketChat seems to have an issue talking to servers internally on the same network. 

What exactly went wrong here?

**Comment by RSchlaeger** [comment]
Having the same problem.. worked fine for a while buit then stopped working all of a sudden...

**Comment by rodrigok** [comment]
Are your servers working now?

If not, which version and installation method you used?

**Comment by RSchlaeger** [comment]
Hey the worked for a while yes. 😊
Project was buried after all sadly…

Thanks for asking though!

Von: Rodrigo Nascimento <notifications@github.com>
Gesendet: Donnerstag, 27. Februar 2020 12:39
An: RocketChat/Rocket.Chat <Rocket.Chat@noreply.github.com>
Cc: Robert Schlaeger <schlaeger@medialesson.de>; Comment <comment@noreply.github.com>
Betreff: Re: [RocketChat/Rocket.Chat] LDAP Error Timeout (#14936)


Are your servers working now?

If not, which version and installation method you used?

**Comment by rodrigok** [comment]
I'll close this issue then. Please open a new issue if the problem persists.
