### ISSUE TITLE
How to upload file (real-time API)?

### ISSUE THREAD

**Issue by fralau** [RocketChat/Rocket.Chat#14939]
While the call to the [sendMessage](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message/) method was fairly straightforward, the documentation for [uploading a file](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message/#sending-a-file) is sketchy, and possibly incomplete. I looked for information on forums or tried to make sense of the code, but without success.

What I understand is that
  1. a `slingshot/uploadRequest` method must be invoked.
  2. the response must be used to
  3. call the `sendFileMessage`

But it is unclear which information from the response must be used in the sendFileMessage and how. In particular, when is the actual file information (the content) actually uploaded?

Could someone give a real-life example of these three messages, possibly with some explanation of the semantics, and how the fields should fit together?

**Note**
For info, I am working on a python implementation based on [python-meteor](https://github.com/hharnisc/python-meteor), taking the cue from [python-rocketchat-bot](https://github.com/maxux/python-rocketchat-bot) written by @maxux. So far the bot can subscribe, receive messages, answer, and even download files (I had to use a normal https call, with cookies)

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

This seems to be a setup/support issue.
Please ask in the forums https://forums.rocket.chat/ or #dev at
 https://open.rocket.chat/
