### ISSUE TITLE
LiveChat - does not close automatically

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat#14938]
### Description:

When a client is disconnected on the site, the chat remains open.

### Expected behavior:
Chat closes automatically if the client has closed the tab with the chat on the site or is idle in it.

### Actual behavior:

When the settings are set to 60 seconds, the chat does not close automatically when the client closes the chat on the site.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: On
- NodeJS Version: v8.11.4
- MongoDB Version:  3.2.20

**Comment by renatobecker** [comment]
The setting you're mentioning is to close the open chats when the agent goes offline, not when the visitor closes its session.

Thanks.
