### ISSUE TITLE
Create discussion dialog allows to query users outside of parent room

### ISSUE THREAD

**Issue by ggruber4711** [RocketChat/Rocket.Chat#14931]
### Description:
When trying to setup a multi-org Rocket.Chat instance using permission-removal of `view-outside-room` it correctly hides users when trying to search for them in the groups.
When you however add a new discussion to an existing group, it will allow you to invite users **outside of the parent group**.

### Steps to reproduce:

1. Remove permissions these permissions from role `User`
    - view-outside-room
    - view-c-room
    - create-c
    - create-p
2. Create users A1 and A2 and put them into private group A-General
3. Create users B1 and B2 and put them into new private group B-General
4. Login with user A1
5. Start a discussion in group A-General
6. Start typing to invite users

### Expected behavior:
Only users A1 and A2 can be seen

### Actual behavior:
All users can be queried (including B1 and B2)

![image](https://user-images.githubusercontent.com/3330414/60687975-a4565780-9eb2-11e9-855c-b722665d2aca.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

**Comment by ggruber4711** [comment]
Seems to be duplicate of #15212

**Comment by ggazzo** [comment]
actually @ggruber4711 it is duplicated, please test again (2.0.0) any problem let me know

**Comment by ggruber4711** [comment]
I can confirm that this problem is now solved with 2.0.0
