### ISSUE TITLE
Mobile notificatios using direct connection

### ISSUE THREAD

**Issue by cyberb** [RocketChat/Rocket.Chat#14947]
Like many people I am running my personal RC server for my family.

I am a bit concerned aboit privacy of Apple/Google push services.

Is it possible to have an option to allow mobile client to check for new messages using direct server connection?

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

You are effectively talking about 'pull' notifications and the answer is not unless you code it yourself...

If you are really concerned you should probably build your own app and message gateway. See the documentation.

Alternatively you get DM email notifications?

This is really a NFR. If you wish to pursue it please do so here:

https://github.com/RocketChat/feature-requests/issues
