### ISSUE TITLE
Per-User/Room sound notification does not play

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#14946]
### Description:

When setting the per user notification preferences and selecting a different sound, and saving, the sound does not play. It also does not play even if set back to "User Account Preference".

### Steps to reproduce:

1. Update to latest develop docker.
2. Select a user dm conversation.
3. Select notification preferences from the room's menu.
4. Choose a different sound, and save.
5. Try to get messages from contact.
6. No sound will play.

### Expected behavior:
Custom sound selected should play.

### Actual behavior:
No sound plays, even when reset back to User Account Preference. Not sure if this is relevant, but the console shows
```
TypeError: 'name' member of PermissionDescriptor 'microphone' is not a valid value for enumeration PermissionName.
```

![image](https://user-images.githubusercontent.com/14616851/60905794-63a46880-a23b-11e9-8202-b72b66c5f570.png)

### Rocket.Chat

| Version                 | 1.3.0-develop                                             |
| ----------------------- | --------------------------------------------------------- |
| Apps Engine Version     | 1.4.2                                                     |
| Database Migration      | 147                                                       |
| Database Migration Date | Tue Jul 09 2019 05:22:24 GMT-0500 (Central Daylight Time) |
| Installed at            | Mon Jan 29 2018 16:02:11 GMT-0600 (Central Standard Time) |
| Uptime                  | 5 hours, 14 seconds                                       |
| Deployment ID           | JAELT9iyADPbKEGbG                                         |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | da42a954bfee046aebdeff595f9e71af24b376f4                     |
| ------- | ------------------------------------------------------------ |
| Date    | Thu Jul 4 17:40:42 2019 -0300                                |
| Branch  | develop                                                      |
| Tag     | 1.2.0                                                        |
| Author  | Renato Becker                                                |
| Subject | Adds a new setting to prevent Livechat agents from activating service status when office hours are closed. (#14921) |

**Comment by bkraul** [comment]
Tested with previous commit 3661c63, same issue. I am trying to find out if this has never worked (I just recently started using per room notification prefs), or if it has been recently introduced.

**Comment by novacrazy** [comment]
I've been experiencing this since 0.74, seemingly at random. Some channels work with custom sounds, others not, even when switched back to the default sound. Switching it multiple times seems to be the trigger, sometimes. Notifications (desktop and mobile) still work in those channels (at least after a relatively recent fix for notifications). I haven't been able to see any notable logs on either the client or server. Quite the enigma.

**Comment by DanielShvartsmanSA** [comment]
We've been having this issue consistently. Before you change the sound, it looks blank and works (with the default sound for your account. After you change the sound, nothing happens. 

Works when:
![image](https://user-images.githubusercontent.com/50330791/62704901-b9139700-b9ec-11e9-92ce-ce76a3045115.png)

Doesn't work when: 
![image](https://user-images.githubusercontent.com/50330791/62704888-af8a2f00-b9ec-11e9-802b-1d8f6f875e32.png)

**Comment by bkraul** [comment]
Is there any update on this? I am seeing that it is affecting newly-created rooms, where no sound is played at all, and it shows up as what @DanielShvartsmanSA shows on screenshot. It is making communication with the teams a little bit difficult 😃 .

**Comment by FixitMad** [comment]
We are also having this issue as well. Uploaded some custom sounds in .mp3 format and RocketChat will not play the changed sound for a room or an individual. We are on both Windows 7 x64 and Windows 10 x64 systems. Still no go when using 2.15.5 version. Do we know when this issue will be resolved or some type of update?
