### ISSUE TITLE
localhost testing - sending postMessage to iframe does not work

### ISSUE THREAD

**Issue by whytspace** [RocketChat/Rocket.Chat#14987]
### Description:

I tried to implement rocket.chat using an iFrame, which worked just fine. But I'm struggling with automatically authorizing the users with a token. I have a small backend service that calls the rocket.chat API (https://open.rocket.chat/api/v1/login) and returns the token. Now I want to send this token to the iFrame via postMessage, as [described in the docs](https://rocket.chat/docs/developer-guides/iframe-integration/commands/).

I also tried to use the `event` parameter instead of `externalCommand` as mentioned in #9019.

Even though I did "Enable Send" and "Enable Receive" in Admin > General > Iframe integration, **rocket.chat does not respond to any of my commands**. I tried it both, my local rocket.chat instance (running on `localhost:3010`) and the `open.rocket.chat` server.

Also, when I [add an event listener for outgoing events](https://rocket.chat/docs/developer-guides/iframe-integration/events/), I can see that all messages that I send in are being sent back out. I can also see all the other messages, such as "room-opened".

Am I doing something wrong? Did I miss one of the settings? Or is it a bug?

If you need more details, let me know.

Thanks,
David

### Steps to reproduce:

1. Implement Rocket.Chat via iframe
```html
<iframe src="https://open.rocket.chat/" id="rocketchat"></iframe>
```
2. Open the page in your browser
3. Open your console and try to run the login command
```js
document.getElementById('rocketchat').contentWindow.postMessage({
  externalCommand: 'login-with-token',
  token: 'my-token-from-rocket-chat-api'
}, '*')
```
4. Log into Rocket.Chat
5. Open your console and try to run another command
```js
document.getElementById('rocketchat').contentWindow.postMessage({
  externalCommand: 'go',
  path: '/channel/general' // also tried 'direct/{username}'
}, '*')
```

### Expected behavior:

Command should work.

### Actual behavior:

Rocket.Chat does not respond to any of the commands sent to the iframe.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1 (via [docker image](https://hub.docker.com/_/rocket-chat))
- Operating System: MacOS host system
- Deployment Method: docker (local)
- Number of Running Instances: 1?
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 4.0.10

It is a new instance with a clean database. Only settings I changed are "Enable Send" and "Enable Receive" in "Admin > General > Iframe integration"

Log from docker:
```bash
| ➔ +----------------------------------------------+
| ➔ |                SERVER RUNNING                |
| ➔ +----------------------------------------------+
| ➔ |                                              |
| ➔ |  Rocket.Chat Version: 1.2.1                  |
| ➔ |       NodeJS Version: 8.11.4 - x64           |
| ➔ |      MongoDB Version: 4.0.10                 |
| ➔ |       MongoDB Engine: mmapv1                 |
| ➔ |             Platform: linux                  |
| ➔ |         Process Port: 3000                   |
| ➔ |             Site URL: http://localhost:3010  |
| ➔ |     ReplicaSet OpLog: Enabled                |
| ➔ |          Commit Hash: 7475d7628a             |
| ➔ |        Commit Branch: HEAD                   |
| ➔ |                                              |
| ➔ +----------------------------------------------+
```

**Comment by reetp** [comment]
| ➔ |             Site URL: http://localhost:3010 

Any good reason why it runs on 3010?

**Comment by en-davidh** [comment]
I used 3010 because 3000 is already in use by react. Could that be the cause of the problem?

**Comment by en-davidh** [comment]
> | ➔ | Site URL: http://localhost:3010
> 
> Any good reason why it runs on 3010?

I just tried it with port 3000. same result: nothing happens after I send the command

**Comment by mhoedl** [comment]
I have the same problem. I would be very happy about a solution!

**Comment by AlekseiBorsenko** [comment]
Also having the same issue.

**Comment by whytspace** [comment]
@mhoedl, @AlekseiBorsenko: great to see that I am not the only one. which port are you running it on? the default one (`3000`)?

**Comment by reetp** [comment]
Note that:

- By default node/meteor runs on 3000 unless modified
- Site URL is the URL that remote sources use to access your server..... which will not be localhost
- Even with a reverse proxy your server should answer as the remote URL name

Please check your settings. I think most of the comments here are due to poor setup and not due to a bug in Rocket.

I also asked a dev for a comment on this and received the following response:

>testing iFrame post back on a local server is going to be problematic (niche case requiring a creative solution that may change with time and server/browser releases)

I suggest this be closed notabug and discussion moved to the appropriate channels:

https://forums.rocket.chat
https://open.rocket.chat #support or #dev

**Comment by whytspace** [comment]
@reetp I didn't know that there are any differences when running Rocket.Chat locally compared to running it on a remote server. I tend to try / test all things locally before I trigger/setup any deployments. That's why I only tried it locally and with the official https://open.rocket.chat/ server.

Now that you mentioned this, I deployed Rocket.Chat to my remote server and, well, what can I say: **It simply works**. I tried both commands, they do exactly as they should.

Thank you very much for the help.

One suggestion though: You should consider adding a hint to the docs, saying that the post-message feature might not work when using a local (testing) instance of Rocket.Chat.

@mhoedl, @AlekseiBorsenko: You might want to try the same.

**Comment by skahwaji** [comment]
May be you need to delay the sendMessage until the iframe loaded, I have used the following solution and it worked on localhost :):

<script>
    function authenticateIFrame() {
        document.getElementById('your_iframe_id').contentWindow.postMessage({
            externalCommand: 'login-with-token',
            token: '@authToken'
        }, '*');
    }

    window.onload = function () {
        authenticateIFrame();
    };
</script>

**Comment by rose-m** [comment]
Maybe it helps someone - I tried to figure out all the settings necessary but couldn't do it. You _have to run on the standard port!_ Otherwise I could not get it to work. Tried everything from the docs but no luck...

**Comment by davidblanco-m** [comment]
In case this helps anyone, I was missing this from the docs:

```
To listen to events while embedding Rocket.Chat in your app inside an iframe,
Navigate to Administration > Settings > General > Iframe Integration.

Enable send (events) or receive (commands) depending on your needs.
```
