### ISSUE TITLE
Add ability to delete (all) own messages from channel, group, direct message

### ISSUE THREAD

**Issue by Perflyst** [RocketChat/Rocket.Chat#14986]
Currently it is not possible to delete own messages as a normal user with the `rooms.cleanHistory` API endpoint nor through the webinterface.

It would be nice if the `rooms.cleanHistory` at least can delete all own messages and also some kind of "Prune messages" for normal users. There is no endpoint for channels and `chat.delete` can only delete single messages.

For the moment I also could not find a good workaround, if there is any, I would like to hear one.

**Comment by Perflyst** [comment]
I wrote a small script to do this via the REST API: https://github.com/Perflyst/rocketchat-purge-messages

Still having this in the core and web UI would be nice.

**Comment by mano87** [comment]
How can we ensure in terms of data protection that everyone can delete their own messages, including direct messages? This is such a marginal function that should be added urgently.
