### ISSUE TITLE
File Upload via Federation throws TypeError

### ISSUE THREAD

**Issue by r3dsn0w** [RocketChat/Rocket.Chat#14983]
### Description:

When sending a file to a another federated user the receiving server throws a TypeError.
Tested with pdf file

### Steps to reproduce:

1. Open a chat to a federated user
2. Send a file

### Expected behavior:

The file gets send to the federated user and he/she is able to view/download it.

### Actual behavior:

The receiving server throws following error:

`TypeError: Cannot read property 'replace' of undefined`

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Ubuntu Server 18.04
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: v3.6.12

### Relevant logs:

Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]: #033[34mFederation ➔ DNS.info#033[39m searchPeer: *HOSTNAME*
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]: #033[34mFederation ➔ HTTP.info#033[39m Sending request: GET - https://chat.*HOSTNAME*:443/api/v1/federation.uploads?upload_id=QGpXrHLALxPiR5H2G
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]: TypeError: Cannot read property 'replace' of undefined
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at FederatedMessage.create (app/federation/server/federatedResources/FederatedMessage.js:203:50)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at PeerServer.handleMessageCreatedEvent (app/federation/server/PeerServer/PeerServer.js:284:20)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at Object.post (app/federation/server/PeerServer/routes/events.js:82:28)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:268:31)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at packages/nimble_restivus/lib/route.coffee:59:33
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at packages/simple_json-routes.js:98:9
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]: #033[34mAPI ➔ debug#033[39m post federation.events threw an error: TypeError: Federation.peerServer.error is not a function
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at Object.post (app/federation/server/PeerServer/routes/events.js:110:26)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:268:31)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at packages/nimble_restivus/lib/route.coffee:59:33
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:     at packages/simple_json-routes.js:98:9
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]: #033[34mAPI ➔ debug#033[39m Failure { statusCode: 400,
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:   body:
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:    { success: false,
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:      error: 'Federation.peerServer.error is not a function',
Jul 11 10:27:25 rocket-chat-nits rocketchat[9674]:      stack: undefined } }

**Comment by geekgonecrazy** [comment]
are both ends using the same server version?

**Comment by r3dsn0w** [comment]
yes, both are using the same server, mongodb and nodejs version

**Comment by vishur98** [comment]
Hi, I am getting the same problem, only images are getting relayed as an attachment not otter file & not even jitsi meet link for video/audio call.

TypeError: Cannot read property 'replace' of undefined     at FederatedMessage.create (app/federation/server/federatedResources/FederatedMessage.js:203:50)     at PeerServer.handleMessageCreatedEvent (app/federation/server/PeerServer/PeerServer.js:284:20)     at Object.post (app/federation/server/PeerServer/routes/events.js:82:28)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:268:31)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9

**Comment by vishur98** [comment]
I20190724-13:01:09.810(0) Exception while invoking method 'jitsi:updateTimeout' TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined     at new FederatedMessage (app/federation/server/federatedResources/FederatedMessage.js:74:34)     at Function.loadOrCreate (app/federation/server/federatedResources/FederatedMessage.js:262:9)     at PeerClient.afterSaveMessage (app/federation/server/PeerClient.js:494:45)     at PeerClient.<anonymous> (app/federation/server/PeerClient.js:109:20)     at callbacks.runItem (app/callbacks/lib/callbacks.js:73:9)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:94:36     at Array.reduce (<anonymous>)     at callbacks.run (app/callbacks/lib/callbacks.js:91:31)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:42:14)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:62:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43
