### ISSUE TITLE
Allow adding Giphy gifs to threads

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#14988]
Currently, it is not passing the ID of the thread.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14621

**Comment by wreiske** [comment]
https://github.com/wreiske/Rocket.Chat.App-Giphy/issues/9

**Comment by d-gubert** [comment]
Almost there! https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/164

**Comment by wreiske** [comment]
This can be closed now!

https://github.com/wreiske/Rocket.Chat.App-Giphy/commit/82cd8dc79653db3903281df09b7fd0e3970957dc

**Comment by geekgonecrazy** [comment]
This is true!  Now useable on open.

If anyone else is trying to do this on a slash command.  You can grab from the slashcommand context and then using the builder set the threadId for the response.

```
const tid = context.getThreadId();
if (tid) {
    builder.setThreadId(tid);
}
```
