### ISSUE TITLE
Random logout for some users

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat#14997]
This is part of a longer post ([here](https://github.com/RocketChat/Rocket.Chat/issues/14824)) I was told that splitting it up into the separate issues would be more helpful for you guys.

### Description:

Some of our users are logged out randomly, although the sessions should only be terminated after 72h (end session on window close is OFF). Similar issue: [here](https://github.com/RocketChat/Rocket.Chat/issues/14619)
Some of our users reported, that they were using the Windows desktop client and the Android app simultaneously with the same account. 
Yet others reported that they were only using the browser or desktop client.
One specific user reported a time frame of more or less 24h. His logout seems to occur every day at the same time - more or less.

I get only logged out over night, despite the 72h being set.

### Steps to reproduce:

Use Rocketchat with a client of your choice.

### Expected behavior:

No logout while chatting or idle / afk.

### Actual behavior:

Users get logged out randomly.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Centos 7 x64
- Deployment Method: normal install on the system
- Number of Running Instances: 1
- DB Replicaset Oplog: ON (Had to be enabled after the upgrade for some reason, even if no replicaset is active.)
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.13

**Comment by guilhermecfviana** [comment]
I still have this problem, any news?

**Comment by TheMrZZ** [comment]
We still have this problem. Any idea?
