### ISSUE TITLE
Chat history not updated

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat#14998]
This is part of a longer post ([here](https://github.com/RocketChat/Rocket.Chat/issues/14824)) I was told that splitting it up into the separate issues would be more helpful for you guys.

### Description:

Some users report that they're getting notifications about a new message, but the message is not shown in the chat history. Only after reconnecting to the server the user gets the updated chat history.

### Steps to reproduce:

Random behaviour affecting all clients (Win10 / Win7 / MacOS desktop clients & browser clients, IOS & Android)

### Expected behavior:

Chat history should be updated properly.

### Actual behavior:

Message arrives, info popup appears -> no chat history update upon opening the client.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Centos 7 x64
- Deployment Method: normal install on the system
- Number of Running Instances: 1
- DB Replicaset Oplog: ON (Had to be enabled after the upgrade for some reason, even if no replicaset is active.)
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.13

**Comment by PiLoT650** [comment]
Hi, same here - i don't know the reason - and it`s not like this everytime.
