### ISSUE TITLE
Hi ,I need to develop an extension (or app) for reserving lunch in Rocketchat

### ISSUE THREAD

**Issue by cygnusm** [RocketChat/Rocket.Chat#14993]
I need to develop an extension (or app) for reserving lunch in Rocketchat. By using this feature users should be able to pick dates that they are in company. I have got a few question on how to add it in Rocketchat:

    Is it possible to add such functionality to rocketchat?
    Should I use MeteorJs and Nodejs?
    Is there any documentation about where should I start?
    Is it similar to developing an app for Rocketchat?

thanks.

**Comment by reetp** [comment]
@rocket-cat close

This is a support request not a bug.

Please ask in the forums https://forums.rocket.chat/ or # support or #dev at https://open.rocket.chat/

Apps use typescript (why? I have no idea.....)

There is a sample app here in github I think. Have a browse.
