### ISSUE TITLE
Unable to edit last message using arrow up when my message is not the last

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#14990]
![image](https://user-images.githubusercontent.com/1000217/61149972-be96c380-a4b8-11e9-8ddc-a81474f256f2.png)

**Comment by ahuret** [comment]
seems that this commit cause this issue: https://github.com/RocketChat/Rocket.Chat/commit/0617b3f35537aae8bc31d9c56b349d479bb55539#diff-5bebe7c40bcea4379fa014eb545a85b5 @ggazzo & @sampaiodiego

**Comment by sampaiodiego** [comment]
closing as duplicated of https://github.com/RocketChat/Rocket.Chat/issues/14688
