### ISSUE TITLE
Custom OAuth issue since upgrading from 0.74 to 1.02

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat#14996]
This is part of a longer post ([here](https://github.com/RocketChat/Rocket.Chat/issues/14824)) I was told that splitting it up into the separate issues would be more helpful for you guys.

### Description:

We use OAuth via Keycloak to log in to our server. It worked well up to version 0.74. Then we upgraded to version 1.02 / 1.03 (and now 1.1.1) and the login fails, usually once. If you hit reload on the error page and try to login again, it's usually successful.
The first login attempt does not generate any logs whatsoever.

### Steps to reproduce:

1. Configure Oauth via Keycloak
2. Use the Oauth login button.
3.
   - Desktop Client (Windows): "Houston we have a Problem"
   - Browser: Sometimes it works, but sometimes it will give you a white page with the error: "An error has occured", "Invalid code, please sign in again via the application", "Click here to return to the application" -> new error page "Login completed. Click here to close this window" (doesn't work)
   - Android / IOS: similar white error page

4. Hit reload and login again. In most cases it only takes a second attempt. On the mobile devices the reload fails. You have to use the X button to get back to the login page.
On the browser: reload the main page without the keycloak auth paths.

### Expected behavior:

Hit login and get logged in right away.

### Actual behavior:

 Login occurs on second attempt (usually, but not always).

### Server Setup Information:

Version of Rocket.Chat Server: 1.1.1
Operating System: Centos 7 x64
Deployment Method: normal install on the system
Number of Running Instances: 1
DB Replicaset Oplog: ON (Had to be enabled after the upgrade for some reason, even if no replicaset is active.)
NodeJS Version: 8.11.3
MongoDB Version: 3.6.13

### Logs when attempting to login via Windows client (1st attempt)
`I20190722-10:22:04.153(2) server.js:207 Meteor ➔ method loadLocale -> userId: null , arguments:  [ 'de-IN' ] `

### Logs when attempting to login via Android app (old session, app complaining to login)
`I20190722-10:25:55.858(2) server.js:207 Meteor ➔ method canAccessRoom -> userId: null , arguments:  [ 'K2HNvNR2SyxnXc5vLuwDytkN6KatcYWH37', null, undefined ] `

### Logs when attempting to login via Android app (new login; loading the page)
` I20190722-10:28:47.430(2) server.js:207 API ➔ debug GET: /api/info 
I20190722-10:28:47.431(2) server.js:207 API ➔ debug Success { statusCode: 200, body: { version: '1.1.1', success: true } } 
I20190722-10:28:47.580(2) server.js:207 API ➔ debug GET: /api/v1/settings.public?count=0&fields=%7B%22type%22%3A%201%7D&query=%7B%22_id%22%3A%20%7B%22%24in%22%3A%20%5B%22uniqueID%22%2C%22LDAP_Enable%22%2C%22CAS_enabled%22%2C%22CAS_login_url%22%2C%22Accounts_RegistrationForm%22%2C%22Accounts_ShowFormLogin%22%2C%22Accounts_PasswordReset%22%2C%22Accounts_CustomFields%22%2C%22Accounts_OAuth_Google%22%2C%22Accounts_OAuth_Facebook%22%2C%22Accounts_OAuth_Github%22%2C%22Accounts_OAuth_Linkedin%22%2C%22Accounts_OAuth_Meteor%22%2C%22Accounts_OAuth_Twitter%22%2C%22Accounts_OAuth_Gitlab%22%2C%22API_Gitlab_URL%22%2C%22Accounts_OAuth_Wordpress%22%2C%22API_Wordpress_URL%22%2C%22Jitsi_Enabled%22%2C%22Jisti_Enable_Channels%22%2C%22Jitsi_SSL%22%2C%22Jitsi_Domain%22%2C%22Jitsi_URL_Room_Prefix%22%2C%22Site_Url%22%2C%22Site_Name%22%2C%22Assets_favicon_512%22%2C%22Assets_favicon_192%22%2C%22UI_Use_Real_Name%22%2C%22UI_Allow_room_names_with_special_chars%22%2C%22Favorite_Rooms%22%2C%22FileUpload_Storage_Type%22%2C%22FileUpload_MaxFileSize%22%2C%22FileUpload_MediaTypeWhiteList%22%2C%22Message_HideType_uj%22%2C%22Message_HideType_ul%22%2C%22Message_HideType_au%22%2C%22Message_HideType_mute_unmute%22%2C%22Message_HideType_ru%22%2C%22Message_AllowDeleting%22%2C%22Message_AllowEditing%22%2C%22Message_AllowPinning%22%2C%22Message_AllowStarring%22%2C%22Message_ShowDeletedStatus%22%2C%22Message_ShowEditedStatus%22%2C%22Assets_tile_310_wide%22%2C%22Store_Last_Message%22%2C%22Message_Read_Receipt_Enabled%22%2C%22Message_Read_Receipt_Store_Users%22%5D%7D%7D 
I20190722-10:28:47.589(2) server.js:207 API ➔ debug Success { statusCode: 200,   body:     { settings:        [ [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object] ],      count: 47,      offset: 0,      total: 47,      success: true } } 
I20190722-10:28:47.742(2) server.js:207 API ➔ debug GET: /api/v1/settings.oauth 
I20190722-10:28:47.743(2) server.js:207 API ➔ debug Success { statusCode: 200,   body: { services: [ [Object] ], success: true } }  `

### Logs when attempting to login via Android app or browser (Firefox, Chrome) (upon clicking the Keycloak login button)
No logs, but a white error page: "An error has occured", "Invalid code, please sign in again via the application". "Click here to return to the application"

``I20190722-10:46:16.503(2) server.js:207 Meteor ➔ method loadLocale -> userId: null , arguments:  [ 'de-IN' ] ``

Using the return link generates this on the server:
`Unable to base64 decode state from OAuth query: undefined
W20190722-10:31:34.810(2) (oauth_server.js:69) Unable to base64 decode state from OAuth query: undefined
W20190722-10:31:34.811(2) (oauth_server.js:392) Error in OAuth Server: Failed to complete OAuth handshake with keycloak at http://[mydomain]/auth/realms/[myrealm]/protocol/openid-connect/token. failed [400] {"error":"invalid_grant","error_description":"Code not valid"} `

Now you get another page stating that the login was completed and a link "Click here to close this window" (doesn't work).

**Comment by aimador** [comment]
``

**Comment by sampaiodiego** [comment]
@Hudell is this fixed on the latest changes included on 1.2.x or 1.3.x?

**Comment by Hudell** [comment]
Probably not. I'll have to take a better look.

**Comment by sampaiodiego** [comment]
ok @Hudell .. I've scheduled this to the next release then.

**Comment by tassoevan** [comment]
Can it be causing https://github.com/RocketChat/Rocket.Chat.Electron/issues/1163? There is a [workaround](https://github.com/RocketChat/Rocket.Chat.Electron/pull/1275), but I need confirmation if it's a Rocket.Chat web client issue.
