### ISSUE TITLE
Add option to make all DM's encrypted by default

### ISSUE THREAD

**Issue by Perflyst** [RocketChat/Rocket.Chat#14994]
As someone else mentioned here https://forums.rocket.chat/t/end-to-end-encryption/204/9 an admin option to encrypt all direct messages with e2e by default would be nice to have and is also required by some

**Comment by reetp** [comment]
@rocket-cat close

At best this is a feature request and should be opened there

https://github.com/RocketChat/feature-requests/issues

I think you will find other conversations on this is you search here.

**Comment by reetp** [comment]
For others asking the same please read the documentation.

> Note: This feature is currently in alpha. Its also not yet supported on mobile

https://rocket.chat/docs/user-guides/end-to-end-encryption/

**Comment by Perflyst** [comment]
Well, thanks for linking it but this kind of feature request is not added yet.

**Comment by reetp** [comment]
> Well, thanks for linking it but this kind of feature request is not added yet.

Hence you can open a 'feature-request' as suggested above and hope that the developers decide to progress it further.

I would imagine mobile E2E will come in due course, though whether they will implement a default 'encrypt all' is another matter.

If you want it that badly then you can open a pull request with your code which will be greatly appreciated. Or possibly contact support or another developer and ask how much they will charge to implement it.

It is Open Source. You have lots of choices.
