### ISSUE TITLE
Login hang on "Please wait..." after enter credential 

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#14999]
### Description:

After logout in whole of client latest version can't login back until reload server in client menu

### Steps to reproduce:

1. Logout/Close client/Close webpage
2. Start client/Open webpage 
3. Enter server url/try to login provide user credential

### Expected behavior:

Rapidly sign-in

### Actual behavior:

Some times login hand on Plase Wait... and no any login atempt until reload page or tap reload Server on view menu

### Server Setup Information:

- Version of Rocket.Chat Server: 121
- Operating System: centos 7.1
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.13

**Comment by mikeaer** [comment]
It’s for my same problem. Diferences between instalation are:
Method: tar
Mongodb: 3.6.9
