### ISSUE TITLE
OS free memory is counting down day by day

### ISSUE THREAD

**Issue by mikeaer** [RocketChat/Rocket.Chat#15011]
### Description:

At INFO panel, I see OS free memory is reduced constantly. Even no more users (about 7) is logged, memory still counting down

### Steps to reproduce:

1. Administration
2. Info
3. OS Free Memory

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: centOS
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.9

![rocket](https://user-images.githubusercontent.com/34124588/61375533-c9ca6480-a8a7-11e9-8d29-a4fc55dba608.PNG)

**Comment by novacrazy** [comment]
That's not unusual. AFAIK it only counts the truly free unused memory. The OS often uses unallocated memory for caching and so forth. You can check what is being used by caches by running `free -mh`

For example, on my server:

```
              total        used        free      shared  buff/cache   available
Mem:           7.8G        5.2G        155M        5.6M        2.5G        3.0G
Swap:            0B          0B          0B
```

You can see the raw `free` memory is very low, but the OS can easily get rid of some of the caches and buffers to use up to 3GB at any time, as seen in the `available` column.
