### ISSUE TITLE
WebRTC echo while talking

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#15018]
### Description:
When make audio call via webrtc on desktop client there are some echo on both side

### Steps to reproduce:

1. Login to RC
2. Choose buddy to  make audiocall
3. Hear you-self voice

### Expected behavior:

We do not hear any echo as as-self voice

### Actual behavior:

we hear selfs echo 

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Centos 7
- Deployment Method: docker
- Number of Running Instances:  3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

**Comment by reetp** [comment]
If you can make a connection then this is most likely down to your connection or other hardware/software/configuration related issues and not Rocket.Chat

Please have a search on the interwebs for "voip echo"

**Comment by Shaverdoff** [comment]
What Configuration you mean? Software configuration of any voip server or client has echo canselation, Vad or else. ThEn i start videochat from jitsi there are no echo.. so...

--
Gerasim Shaverdov | Deputy CTO | Altarix
Mobile: +7 937 070 66 84<tel:+7%20937%20070%2066%2084> | Skype/email: gerasim@altarix.ru<mailto:gerasim@altarix.ru>
Lenina av.25, Samara, Russia, 443068

20 июля 2019 г., в 17:40, John Crisp <notifications@github.com<mailto:notifications@github.com>> написал(а):


If you can make a connection then this is most likely down to your connection or other hardware/software/configuration related issues and not Rocket.Chat

Please have a search on the interwebs for "voip echo"

**Comment by kooroshh** [comment]
have the same problem too 


Version 1.2.1
Apps Engine Version 1.4.2
OS : Ubuntu 19

**Comment by franckadil** [comment]
I can reproduce on Windows, Ma,c and Linux.

**Comment by JohnnyRahul** [comment]
We too have it. Can reproduce on Windows 7 and 10. Is there a fix for this?

**Comment by moofen** [comment]
Same issue, both in client and in webinterface.

**Comment by franckadil** [comment]
I can confirm the issue in web interface with One to One and One to many users across different zones.

**Comment by arslan95** [comment]
Same issue :/

**Comment by Shaverdoff** [comment]
Version 2.1.1 – still echo on any webrtc

 

 

 

--

Gerasim Shaverdov | Deputy CTO | Altarix 

Mobile:  <tel:+7%20937%20070%2066%2084> +7 937 070 66 84 | Skype/email:  <mailto:gerasim@altarix.ru> gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by lightweight** [comment]
Still hearing the echo on 2.3.1

**Comment by Routhinator** [comment]
Yeah this isn't the users hardware, You need to mute the local audio stream. You are playing the users local audio input back to them along with the audio output. This is a common mistake with webrtc implementation. Even if one person mutes, the other person hears themself talk.

https://stackoverflow.com/questions/18406193/how-to-avoid-echo-and-noise-in-javascript-for-webrtc

**Comment by Routhinator** [comment]
Unforutnately there's no way to fix this from the current version of the ui. You'd have to hack it with extra JS or wait for the dev team to fix the Rocketchat issue here.

**Comment by Routhinator** [comment]
To be clear this is not an echo. It is the audio input stream being played back to the sender.

**Comment by Shaverdoff** [comment]
Its call - echo;)) all that you explained;) user who hear echo get it on hiself side:)

--
Gerasim Shaverdov | Deputy CTO | Altarix 
Mobile: +7 937 070 66 84 | Skype/email: gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by Routhinator** [comment]
This isn't echo in my case. Echo is when your voice exits the other persons speaker and is picked up by their mic, feeding back to you via their audio.

If the other person mutes their mic or I mute them, I can hear myself. I hear myself louder and clearer than the other person. That's not echo, it's the local audio stream.

**Comment by Shaverdoff** [comment]
Now clear to understood

--
Gerasim Shaverdov | Deputy CTO | Altarix 
Mobile: +7 937 070 66 84 | Skype/email: gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by corecache** [comment]
Workaround in FIrefox:
- Right click on the video element and choose show controls
- Either use the audio slider to reduce volume to 0 or click on the sound icon to mute/unmute the element

**Comment by corecache** [comment]
Possible solution in RocketChat:
Simply deliver the video element with muted="muted" element or any other sane and proper way to muted the sound of the video element

**Comment by Shaverdoff** [comment]
Already trying.. no effect, still echo

Отправлено с iPhone

**Comment by corecache** [comment]
Updated workaround description to clarify which mute is meant (to many mutes available)

**Comment by Shaverdoff** [comment]
in desktop this does not show, in web is tu bugged

**Comment by Bengrunt** [comment]
Having a fix to this annoying issue would be awesome.

Particularly with the pandemic going on, we need more audio contact with fellow coworkers :)

Thanks !

**Comment by Shaverdoff** [comment]
No pandemic. Only artificial panic;)! Use jitsi instead. Ot may work localy

Отправлено с iPhone

**Comment by Bengrunt** [comment]
> 
> No pandemic. Only artificial panic;)! Use jitsi instead. Ot may work localy Отправлено с iPhone
> […](#)
> 16 марта 2020 г., в 12:49, Benjamin Guillon ***@***.***> написал(а): ﻿ Having a fix to this annoying issue would be awesome. Particularly with the pandemic going on, we need more audio contact with fellow coworkers :) Thanks ! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Ok will try again with Jitsi, but I recall we encountered other issues there.

We got stuck on remote work anyway so ... :) Gotta make it work.

Thanks!

**Comment by ndroo** [comment]
If anyone wants to help fix this i'm willing to fund your work. Feel free to ping me.

**Comment by franckadil** [comment]
We need a way to make the team acknowledge and prioritize this issue. In my understanding this issue is not really acknowledged yet. It have a direct impact for many on their choice to use Rocket Chat. @sampaiodiego

**Comment by ndroo** [comment]
So i actually fixed it, i'll submit a PR to address it for everyone else (tomorrow?).

**Comment by franckadil** [comment]
@ndroo Thanks for helping out, that's surely going to help!

**Comment by douglasmcqoy** [comment]
> So i actually fixed it, i'll submit a PR to address it for everyone else (tomorrow?).

can you share with me how you did?

**Comment by PatAgglo** [comment]
Hi,

I have the same problem ans it's so difficult to find any documentation about WebRtc configuration on rocket.chat. 
If you have any solution for this, I am interested!

Regards

**Comment by PatAgglo** [comment]
> If anyone wants to help fix this i'm willing to fund your work. Feel free to ping me.

Have you any solution?

**Comment by kvasko** [comment]
Yesterday I installed our new rocket.chat server but we are facing with the same problem and we can't start to use it till this problem will be not solved. As I see ndroo mentioned that he fixed the issue but I don't find any related description. I tested the BETA version too but it has the same problem. Any fix for this?

**Comment by ndroo** [comment]
Here is the PR: https://github.com/tophatblue/slatechat/pull/10

**Comment by ndroo** [comment]
:) man everyones after me. Sorry, big push on our side trying to support others working remote right now. PR coming shortly...

**Comment by franckadil** [comment]
@ndroo you're officially promoted to the rank of Super Hero :champagne:  ! Thank you for your contribution! O7

**Comment by PatAgglo** [comment]
Hi,

I don't find the file videocall.html on my rocketchat 3.0.9...

Where is it?

Regards
