### ISSUE TITLE
Rate limit incoming webhooks - DoS vulnerability

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#15029]
# Motivation

As a provider of a ChatServer, I need to be safe against Denial Of Service attacks.
For this purpose, all APIs exposed by RC are rate-limited, which is fine.
Webhooks of incoming integrations however are not rate limited at all: Simply by `POST`ing to a webhook URL with unlimited rate will result in a huge load and render the system unusable.

# Solution Proposal 

Rate limit all incoming integration calls with the standard HTTP rate limit as defined in the existing settings.

**Comment by mrsimpson** [comment]
@sampaiodiego Rate limiting integrations seems a bit tricky since it does not re-use anything of the `APIClass` with which all other APIs are limited. I started to work on this one, but I was a bit slowed down by refactoring.
Do you prefer this to be solved with the integrations-API inheriting from the `APIClass` or should I just copy code?

**Comment by sampaiodiego** [comment]
@mrsimpson thanks for stepping in =)

I see how tricky it can be.. Maybe we should create another class with only the rate-limited `addRoute` method. So the [APIClass](https://github.com/RocketChat/Rocket.Chat/blob/5ef81257efd2b2f951e2fbd3a54922d116e33619/app/api/server/api.js#L25) can extend from it and the [integration API](https://github.com/RocketChat/Rocket.Chat/blob/5ef81257efd2b2f951e2fbd3a54922d116e33619/app/integrations/server/api/api.js#L19) can implement it. wdyt?

**Comment by mrsimpson** [comment]
@sampaiodiego I had a deeper look. 
I'd favor to extract some part of the `APIClass` and to overwrite some methods in the Integration API.  Also, I do think that changing `addRoute` would be quite a change. I'd prefer to extract and overwrite [shouldVerifyRateLimit](https://github.com/RocketChat/Rocket.Chat/blob/5ef81257efd2b2f951e2fbd3a54922d116e33619/app/api/server/api.js#L242-L260): The integration API would then hold an own dictionary for each integration.
Sounds like a plan?

**Comment by sampaiodiego** [comment]
that could work, but let me try explain better what I thought initially:

- Create a new class, let's say `RateLimitedAPI`:
```javascript
class RateLimitedAPI extends Restivus {
  addRoute() {
    // copy current code from APIClass
  }
}
```
- Change `APIClass` to extend from `RateLimitedAPI` and then remove the `addRoute` from it:
```javascript
class APIClass extends RateLimitedAPI {
  // keep everything except addRoute
}
```
- Change [integration API](https://github.com/RocketChat/Rocket.Chat/blob/5ef81257efd2b2f951e2fbd3a54922d116e33619/app/integrations/server/api/api.js#L19) to instantiate `RateLimitedAPI` class instead of `Restivus`:
```javascript
const Api = new RateLimitedAPI({
	enableCors: true,
	apiPath: 'hooks/',
	auth: {
		// keep everything else
	}
});
```

I think this way one can still chose whether to use a rate limited API by just choosing the right class to implement. Additionally extracting `shouldVerifyRateLimit` to it's own method as you described would be cool as well to change the rules for being rate limited :+1:

**Comment by mrsimpson** [comment]
@sampaiodiego I understood it this way and in fact, I would think this is the best way to go.
However, when looking at the webhooks in particular, I feel that changing the way routes are registered (absolute URLs instead of one generic `:integrationId/:token`) would change a lot with respect to lifecycle: Everytime a route would be added or removed, the routes would have to be updated as well.

Thus, I decided to dynamically add limiters for the generic route and then implement a custom validation in the integration API.

In order to do that, I extracted a couple of methods which needed to be reusable in the subclass. 

Please have a look at it.
