### ISSUE TITLE
CRITICAL: Fatal error starting develop - 69dd012: Exception in callback of async function: TypeError: Cannot read property 'isEnabled' of undefined

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#15023]
### Description:
Upon downloading the latest docker:develop image, (based on 69dd102) the container fails on startup with the following error:

```
Exception in callback of async function: TypeError: Cannot read property 'isEnabled' of undefined
    at Object._getStatistics [as get] (app/statistics/server/functions/get.js:148:17)
    at syncWorkspace (app/cloud/server/functions/syncWorkspace.js:17:27)
    at app/cloud/server/index.js:20:2
    at Function.time (/app/bundle/programs/server/profile.js:309:28)
    at /app/bundle/programs/server/boot.js:427:13
    at /app/bundle/programs/server/boot.js:472:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11
```
The concerning part, is that I cannot go back to a previous version. (errors out with `cannot find migration 148`). This seems to be a critical issue.

### Steps to reproduce:

1. Download latest docker rocketchat:devel image (based on 69dd102)
2. Attempt to start it with your docker-compose, etc.
3. Server will halt upon startup with error mentioned above.

### Expected behavior:
Server should start as normal.

### Actual behavior:
Server halts on startup.

### Server Setup Information:
- Docker develop tag.

**Comment by reetp** [comment]
First this is a development version. Errors should be expected....

> The concerning part, is that I cannot go back to a previous version. (errors out with cannot find migration 148 ). This seems to be a critical issue.


This not unusual when you upgrade any database, and I believe particularly so with mongo.

https://rocket.chat/docs/administrator-guides/database-migration/#database-migration

The answer is to always make a backup before trying to upgrade.

**Comment by bkraul** [comment]
@reetp I am aware this is a development version. That is why I actively report on it. Second, as stated, my environment is a testing environment for this very reason.

That aside, my suspicion is that the migration to 148 is not included in the current image. I went back to one that does have it and was able bring the server up. Will attempt to upgrade to latest again and report.

**Comment by bkraul** [comment]
After the 148 migration, provided by docker build based on 422669fa29, I attempting moving up to 69dd102, to no avail. It failed with the same error described about. Tried latest build based on tag c4127e6, with same results. Have reverted back to 422669fa29.
