### ISSUE TITLE
Messages push  don't support in channel ？

### ISSUE THREAD

**Issue by davewang** [RocketChat/Rocket.Chat#15024]
I test message push ok in one to one conversation  but in the channel offline users down't receive push messages.

### Steps to reproduce:

1. eable push and push debug ,and config is ok!
2. test send message to channel 
3. offline user is not receive push message  （but is one to one room is ok!)
### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: darwin
- Deployment Method: tar
- Number of Running Instances: 1000
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4 - x64 
- MongoDB Version: 3.2

**Comment by reetp** [comment]
If you don't fill in all the Server Setup information no one can help you.

You can ask support questions here https://forums.rocket.chat/ or # support at https://open.rocket.chat/

**Comment by davewang** [comment]
@reetp ok!Already added！Help me. Thx!

**Comment by reetp** [comment]
You are out of date and need to upgrade to latest - currently 1.2.1

There are a huge amount of fixes since 0.74.x and no one is going to help you fix an outdated version.

You might want to upgrade mongo as 3.2 will be deprecated soon.

**Comment by davewang** [comment]
I 'm upgrade to latest version 1.2.1 is same bug!In Channel offline users don't received push messages.

**Comment by reetp** [comment]
Please remember that lots of people use Rocket and have no issues.

You have provided absolutely no evidence of any problems with Rocket.Chat, so this currently looks like a configuration /support issue rather than a bug and should probably be opened in the appropriate channels - https://forums.rocket.chat or https://open.rocket.chat #support

What do your logs tell you?

What about your push notification settings in Rocket?

admin/Push
admin/General/Notifications
admin/Accounts Default User Preferences

Check Individual User Preferences under My Account
account/preferences/Notifications

What about your configurations - reverse proxy/firewall etc. 

Anything else non standard?

**Comment by davewang** [comment]
``` java
I20190722-15:53:00.384(8) Setting default file store to FileSystem 
I20190722-15:53:12.993(8) (migrations.js:120) Migrations: Not migrating, already at version 147
I20190722-15:53:13.782(8) Using GridFS for custom sounds storage 
I20190722-15:53:13.789(8) Using GridFS for custom emoji storage 
I20190722-15:53:13.988(8) Updating process.env.MAIL_URL 
I20190722-15:53:17.090(8) Push: configuring... 
I20190722-15:53:17.091(8) Push.Configure { sendTimeout: 60000,   apn: undefined,   gcm: undefined,   production: true,   sendInterval: 5000,   sendBatchSize: 10 } 
I20190722-15:53:17.116(8) Push: Send worker started, using interval: 5000 
I20190722-15:53:17.292(8) ➔ System ➔ startup 
I20190722-15:53:17.293(8) ➔ +--------------------------------------------------+ 
I20190722-15:53:17.293(8) ➔ |                  SERVER RUNNING                  | 
I20190722-15:53:17.293(8) ➔ +--------------------------------------------------+ 
I20190722-15:53:17.293(8) ➔ |                                                  | 
I20190722-15:53:17.293(8) ➔ |  Rocket.Chat Version: 1.2.1                      | 
I20190722-15:53:17.293(8) ➔ |       NodeJS Version: 8.11.4 - x64               | 
I20190722-15:53:17.293(8) ➔ |      MongoDB Version: 4.0.10                     | 
I20190722-15:53:17.293(8) ➔ |       MongoDB Engine: mmapv1                     | 
I20190722-15:53:17.294(8) ➔ |             Platform: linux                      | 
I20190722-15:53:17.294(8) ➔ |         Process Port: 3000                       | 
I20190722-15:53:17.294(8) ➔ |             Site URL: http://192.168.31.96:3000  | 
I20190722-15:53:17.294(8) ➔ |     ReplicaSet OpLog: Enabled                    | 
I20190722-15:53:17.294(8) ➔ |          Commit Hash: 7475d7628a                 | 
I20190722-15:53:17.294(8) ➔ |        Commit Branch: HEAD                       | 
I20190722-15:53:17.294(8) ➔ |                                                  | 
I20190722-15:53:17.295(8) ➔ +--------------------------------------------------+ 
I20190722-15:54:07.141(8) Push: send message "082DE18639C7B1705255AEDEBFBF6307" via query { userId: 'wqqKirotMkTnbnxQe' } 
I20190722-15:54:32.177(8) Push: send message "082DE18639C7B1705255AEDEBFBF6307" via query { userId: 'kpeXzyFDyKnCFjWYT' } 
```

private chat push is ok. But on channel offline users don't received push messages.

**Comment by davewang** [comment]
I‘m get it.Because in channel need @user or @all  be to push messages. Ok ！Thx！@reetp

**Comment by davewang** [comment]
Is there a way to send a notification configuration without typing @all or @user?

**Comment by reetp** [comment]
> Because in channel need @user or @ALL be to push messages

Please read the documentation and look at the settings. Note that a mobile device will NOT receive push messages if the user has not logged out from other locations or marked themselves away

> Is there a way to send a notification configuration without typing @ALL or @user?

You'll have to send every message.

(Note that if you are going to be sending a high volume of notifications you might want to consider running your own push gateway. Eventually Rocket.Chat are liable to start charging for higher volumes - notifications are not a zero cost exercise.)

**Comment by reetp** [comment]
@rocket-cat close

As far as I can tell there is no bug here - just configuration. If there are actually any errors then post back and someone may reopen it.

If Rocket functions without errors, but does not do exactly what you want, then open a feature request:

https://github.com/RocketChat/feature-requests

For general community support please ask here:

https://forums.rocket.chat or https://open.rocket.chat #support
