### ISSUE TITLE
Nginx proxy on location different than /

### ISSUE THREAD

**Issue by asarubbo** [RocketChat/Rocket.Chat#15037]
The doc (https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/) about the proxy configuration with nginx shows how to proxy on location '/'

We would like to make accessible rocket on another location (like /rocket). We tried to adapt the example on /rocket with a related rewrite but we are seeing a blank page.

Is there a way to do so? Is documented somewhere?

Thanks

**Comment by reetp** [comment]
@rocket-chat close

Github is for bugs in Rocket, not support requests.

Please search githuib for previous comments on 'subdirectory' or ask here:

https://rocket.chat/docs/getting-support/#community-support

https://forums.rocket.chat
https://open.rocket.chat #support
