### ISSUE TITLE
Override global retention policy with edit-room-retention-policy not possible

### ISSUE THREAD

**Issue by rook59** [RocketChat/Rocket.Chat#15036]
### Description:

It is not possible to enable "Override global retention policy" even if a user is owner in a channel and the role owner has the permission `edit-room-retention-policy`

### Steps to reproduce:

1. Give permission edit-room-retention-policy  to role owner
2. Login as normal user and enable Automatically prune old message
3. Switch to "Override global ..." is greyed out

### Expected behavior:

Switch should not greyed out and global policy should be overwrite-able.

### Actual behavior:

Global policy cannot be overwritten as normal user.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 1.3.0-rc.0 (was also in 1.2.0)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  < doesnt matter >
- NodeJS Version: < doesnt matter >
- MongoDB Version:  < doesnt matter >

**Comment by TheGr8Wonder** [comment]
Dug into the PR for this - #11236 - and there is another setting that is required to enable the override of the global retention - `edit-privileged-setting` (From the PR notes: Can override global policy with a switch that requires `edit-privileged-setting`). Once I added that to the same group I enable for `edit-room-retention-policy`, the option was no longer grayed out. Working in v3.0.2
