### ISSUE TITLE
room.forward no works

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#15040]
Version of Rocket.Chat Server: 1.1.1
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.15.0
MongoDB Version: v3.6.10

I need to send a message to a specific agent the steps I used are:
1- Create Visitor
2- Create room
3- Discover userid
4- room.forward

TOKEN
curl -X POST http://localhost:3000/api/v1/login -H 'Content-Type: application/json; charset=utf-8' -d '{"username": "admin","password": "rocketchat"}'

VISITOR
curl -X POST -H "Content-type:application/json" http://localhost:3000/api/v1/livechat/visitor -d '{"visitor": {"name": "Eu","token": "12345678","phone": "12345678"}}'

Room id
curl http://localhost:3000/api/v1/livechat/room?token=12345678

userid AGENT
curl -H 'X-Auth-Token: tcan35ZpQNcaOlPAK9wILV69wNEmNaXbTEYTk527UAX' -H 'X-User-Id: MkJKxLBkuX3ujK8AJ' -X POST -H Content-type:application/json http://localhost:3000/api/v1/livechat/users/agent -d '{"username":"Jose"}'

room.forward
curl -H 'X-Auth-Token: tcan35ZpQNcaOlPAK9wILV69wNEmNaXbTEYTk527UAX' -H 'X-User-Id: MkJKxLBkuX3ujK8AJ' -H 'Content-type: application/json' http://localhost:3000/api/v1/livechat/room.forward -d '{"roomId": "AKsNcfM5zDGDewmvF", "userId": "xiubo8kffucffbKnv"}'

The problem is, I need it to work in a guest pool but with this option it doesn't work, is there anything that can be done?

**Comment by reetp** [comment]
@rocket-cat close

Please note that github is for bugs in Rocket.Chat and this seems to be a support issue.

Please ask your questions here  - but please make sure you have tested on the latest Rocket with the correct engine versions eg

Engine versions
Node: 8.11.4
NPM: 6.4.1
MongoDB: 3.4, 3.6, 4.0


https://rocket.chat/docs/getting-support/#community-support

https://forums.rocket.chat
https://open.rocket.chat #support 

If you feel that Rocket is really missig something then please open a feature request here
