### ISSUE TITLE
Hubot private group listening

### ISSUE THREAD

**Issue by kakerduu** [RocketChat/Rocket.Chat#15044]
Greetings,

Is there a way now in 2019 for the hubot to listen on commands from a private group, even if he is not part of it?

As an alternative, my hubot used the RC API to add the bot from a public channel to the private channel, via the groups.invite call, but it won't work either.

Any answers and suggestions please?

**Comment by reetp** [comment]
@rocket-cat close

This is a support issue, not a bug. Please follow up here:

https://rocket.chat/docs/getting-support/#community-support

https://forums.rocket.chat
https://open.rocket.chat #support 

> Is there a way now in 2019 for the hubot to listen on commands from a private group, even if he is not part of it?

Hmm - if anyone could listen to a private group if you aren't part of it, it wouldn't be private.....
So this isn't going to happen in 2019, or any other year.

> As an alternative, my hubot used the RC API to add the bot from a public channel to the private channel, via the groups.invite call, but it won't work either.

I'd suggest you look at Permissions and who/cannot add users to a private group
