### ISSUE TITLE
Mailer unsubscribe - invisible text after unsubscribe

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#15043]
### Description:
In mail sent by "mailer" feature users recieve link to unsubscribe this type of notifications . When user go this link unsubscribe information is invisble (white font) and visible after mark it. Details in screens below.

### Steps to reproduce:

1. Send emails via mailer option
2. Go to unsubscribe link from recieved mail
3. On unsubscribe page text is invisible and visible after mark it

### Expected behavior:

Unubscribe text is visible

### Actual behavior:
![image](https://user-images.githubusercontent.com/50440047/61785542-32679300-ae0c-11e9-961e-481a5f338046.png)

![image](https://user-images.githubusercontent.com/50440047/61785552-398ea100-ae0c-11e9-815d-6deddcb9e4b8.png)

### Server Setup Information:

Version of Rocket.Chat Server: 1.2.1
Operating System: Centos 7
Deployment Method: docker compose
Number of Running Instances: 9
DB Replicaset Oplog: yes
NodeJS Version: 8.11.4 - x64
MongoDB Version: 4.0

**Comment by ozata** [comment]
I want to solve this problem, do you have any suggestions?

**Comment by emikolajczak** [comment]
Hi, I think only issue here is font colour on /mailer/unsubscribe page.
So change it to visible.
