### ISSUE TITLE
[NEW] Add Microsoft Translator as translation service

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#15048]
Microsoft Translator is a translation service and an alternative to Google Translate. It supports a large amount of languages, for instance  German <-> Czech. 

It would be beneficial to add Microsoft Translator to the list of translation services in Rocket.Chat. Therefore we should integrate the Microsoft API into RocketChat based on the existing Google Translate implementation.

Acceptance criteria

- Add ability to AutoTranslate messages with Microsoft Translator
- Add global setting to turn the translation on/off
- Add ability to choose between different translation service providers

For reference, please have a look on our implementation of DeepL: https://github.com/RocketChat/Rocket.Chat/pull/12174

**Comment by regetskcob** [comment]
Deepl.com would be a way more precise option.
