### ISSUE TITLE
Livechat triggers: Enable custom parameter for triggers

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#15049]
Instead of relying on the visited page URL, I want to pass a custom parameter to the livechat that I can use in the triggers.

Ideally this can be used as an URL parameter to the `/livechat` endpoint, as this makes embedding the livechat possible in a custom integration script.

**Comment by reetp** [comment]
@rocket-cat close

Feature requests go here please:

https://github.com/RocketChat/feature-requests/issues

**Comment by tholu** [comment]
https://github.com/RocketChat/feature-requests/issues/171
