### ISSUE TITLE
unable to upload image from browser

### ISSUE THREAD

**Issue by 3piccode** [RocketChat/Rocket.Chat#15042]
Show 0% and never load.
Issue in happing on both desktop chrome browser and mobile chrome browser.

**Comment by reetp** [comment]
Read this on how to report an Issue:
https://rocket.chat/docs/contributing/reporting-issues

Check your proxy is using websockets.

Fill in this template:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by ggazzo** [comment]
please reopen the issue with more infos, thanks
