### ISSUE TITLE
Incoming WebHook Post to Channel can be overridden 

### ISSUE THREAD

**Issue by kendrickluong** [RocketChat/Rocket.Chat#15057]
### Steps to reproduce:

1. Create Incoming Webhook
2. Post to channel specified e.g. @user
3. Using curl command including channel parameter specify #channel
4. Message is posted to #channel

### Expected behavior:

If a channel is specified it should not be overridden. We experienced a user abusing abusing a web hook and sending message to private channels

### Actual behavior:

The channel parameter should be ignored in the curl request

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1

**Comment by reetp** [comment]
Please show some code.
The webhook + curl command.

**Comment by kendrickluong** [comment]
New incoming webhook integration:
post to channel: #testchannel
post as: rocket.cat
script enabled: false

curl command:
`curl -X POST -H 'Content-Type: application/json' --data '{"icon_emoji":":ghost:","text":"Example message","channel":"#ldap_tests""attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' https://<url>`

**Comment by MarcosSpessatto** [comment]
Hi @kendrickluong, this behavior is expected. The channel that you define in the webhook panel, is the **default** chanel to post to. If you send a channel in your request to the webhook url, then yes, it will be override.

**Comment by mes85** [comment]
Hi all,

I agree with @kendrickluong that the naming in the admin panel is misleading. It is not mentioned in the admin interface, that another channel might by specified.
Only by going through the issues here I realized that a channel parameter can be given. Until then I expected the channel to be enforced, if not changed within a script part of a webhook.

I vote to have settings in the webhook configuration to enforce the channel, but also Alias and Avatar/Emoji.
I could also image a paramter to limit message length.

I would agree with you, that this kind of settings will make the webhook interface look overengineered. In that case, and also as an solution for @kendrickluong right now, a good script example that filters everything unintended would be helpful for administrators.

**Comment by mes85** [comment]
Using the following script you will only allow icon_emoji, text and attachments to come through. The channel can no longer be overwritten. In addition the IP of the sender is shown.

```
class Script {
  process_incoming_request({ request }) {
    return {
      content: {
        "icon_emoji": request.content.icon_emoji,
        "text": String.prototype.concat(request.content.text, ' (from IP: ', request.headers["x-real-ip"], ')'),
        "attachments": request.content.attachments
      }
    };
  }
}
```
