### ISSUE TITLE
One of RC instances crushed

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#15055]
### Description:

We have 3 instances of RC 1.2.1 with almost zero load (ready for HA). Few minutes ago one of instances crushed. Can you look at log, what happend? Thanks

### Actual behavior:

[There is the incident log](https://github.com/RocketChat/Rocket.Chat/files/3432924/rocket_fail.log)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Debian 9.9
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Mongo with 3 replicated instances
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.13

**Comment by dusatvoj** [comment]
It happend again on another instance of load balancer

**Comment by dusatvoj** [comment]
Nobody cares

**Comment by reetp** [comment]
No. It is open source. Developers priorities may not be the same as yours.

If you have paid support you can contact support@rocket.chat

There is no log attached that I can see....
 
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

You need to test on 'latest'

Provide some proper logging and someone may possibly take a look.
