### ISSUE TITLE
Reactions not allowed in read only rooms

### ISSUE THREAD

**Issue by sean-pop** [RocketChat/Rocket.Chat#15051]
### Description:

When in a read-only channel, reactions are not allowed, even when set to "allow". 

### Steps to reproduce:

1. Log in as admin user
2. Make a room "Read Only"
3. Enable "Allow Reacting"
4. Log in as normal user
5. Navigate to read-only room
6. Attempt to react to a message

### Expected behavior:

Users should be able to react.

### Actual behavior:

Reaction option is not displayed.

Here is "Allow Reacting" setting set:

![image](https://user-images.githubusercontent.com/53309271/61889182-cf343a00-aeb9-11e9-9ee5-5a7d915629a6.png)

And here is what a normal user sees while in the channel:

![image](https://user-images.githubusercontent.com/53309271/61889162-be83c400-aeb9-11e9-8f95-d8c0748b64f3.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Linux 4.4.0-137-generic
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Unsure
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.20

### Additional context

We have a couple of channels used for announcements which only admins can post to. The channels are read only but want to allow non-admins to react to the messages.

**Comment by Hudell** [comment]
This was fixed by #14960 
The labels of the "Allow reaction" setting were inverted, so if you don't want to update the Rocket.Chat yet you can just set the setting as disabled instead.
