### ISSUE TITLE
Last release for Snap is 1.1.3

### ISSUE THREAD

**Issue by Para0234** [RocketChat/Rocket.Chat#15059]
Hi,

It seems that Snap hasn't been updated to the latest versions.

The last stable version is the 1.1.3 and the last beta is the 1.0.3 according to both https://snapcraft.io/rocketchat-server and my personnal tests.

Has Snap been discontinued?

Thanks

**Comment by reetp** [comment]
@rocket-cat close

Please read the FAQ. It will get released when the team feel it is ready.

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

**Comment by Para0234** [comment]
Wasn't the date for the 1.2.0 supposed to be the 15 june according to that FAQ?

**Comment by reetp** [comment]
"usually released"

Nothing definitive in that statement.

**Comment by Para0234** [comment]
Maybe, but was there any news about this release? Any announcements?

**Comment by reetp** [comment]
No. It will be released when ready, and an announcement will be made at the time.

In the meantime you will just have to be patient. Nothing you can say will change that.

If you want to see faster releases in the future then get involved here coding or otherwise helping out.

Thank you.

**Comment by Para0234** [comment]
Alright, thanks for the answer
