### ISSUE TITLE
openshift template problem

### ISSUE THREAD

**Issue by yeganx** [RocketChat/Rocket.Chat#15058]
hi
my openshift vesion is 
```
oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://lb.example.com:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```
rocket chat pods just have readiness problem , and stop with error 
I believe there is problem in the tempelate

**Comment by vvanouytsel** [comment]
Is this related to https://github.com/RocketChat/Rocket.Chat/issues/14670 ?

**Comment by tntho** [comment]
Hi @yeganx 
Have you ever tried increasing the time and the threshold ( maybe 15 mins :D ). In our case it took more than 5 mins at the first bootstrap time. It lead to OpenShift `livenessProbe` and `readinessProbe` make false positive judgement.

**Comment by yeganx** [comment]
no I think Its just True negative one
