### ISSUE TITLE
API URL endpoint is called twice at the same time

### ISSUE THREAD

**Issue by JunyiYang0925** [RocketChat/Rocket.Chat#15065]
### Description:

API URL endpoint is called twice at the same time, when user logout and refresh the page imediately

### Steps to reproduce:

1. Set an endpoint in admin->account->iframe->api url
2. open rocket chat in browser
3. logout the currently logged in user, and refresh the page right away. 

### Expected behavior:

rc call the API URL once 

### Actual behavior:

rc call the API URL twice 

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: centos7
- Number of Running Instances: 1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.9

**Comment by JunyiYang0925** [comment]
![image](https://user-images.githubusercontent.com/16327217/62053632-b2349980-b220-11e9-9cf2-89e386c8e43a.png)

**Comment by reetp** [comment]
@rocket-cat close

Please note that github is for bugs in Rocket.Chat and there is no evidence to suggest there is in this instance.

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

* Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

Latest is currently 1.2.1 with 1.3.0 due for release any day.

Have discussed this with the user in openrocket.chat and given them some ideas to test.

**Comment by tchukuchuk** [comment]
Hi @JunyiYang0925 ,

Did you find a solution ? I have the same behavior with the 3.4.1 release.
