### ISSUE TITLE
LDAP Connection Error | v1.2.1

### ISSUE THREAD

**Issue by robinreinhardt** [RocketChat/Rocket.Chat#15061]
### Description:

Following message appears every few minutes in the log file:

server.js:207 LDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:992:11)     at TLSWrap.onread (net.js:618:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### Steps to reproduce:

1. Go to Adminstration
2. Click on View Logs

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: CentOS 7.6
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: active
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.13

### Additional context

The configuration of the LDAP server hasn't been changed.

**Comment by kokotko1337** [comment]
what was solution ?

**Comment by robinreinhardt** [comment]
It seems the update to version 1.2.2 solved the problem

**Comment by kokotko1337** [comment]
Thanks , ill test it ... got 1.1.1
