### ISSUE TITLE
Rest API login localstorage issue

### ISSUE THREAD

**Issue by rajm** [RocketChat/Rocket.Chat#15064]
$.post( 
                  "https://ccc.chat.net/api/v1/login",
                  { user: email, password: "1234567" },
                  function(data) {
				   $("{loginToken: "+ data.data.authToken + "}").appendTo(document.body);
				   localStorage.setItem('Meteor.loginToken', data.data.authToken);
				localStorage.setItem('Meteor.userId', data.data.userId);
               }
            );

rest api login return sucess but does not reset the localstorge...how to reset the localstorage to login a new user..

Right now since the accesstoken does not clear.. iframe login rest api call opens with the previous user though the new user api login returns sucess

**Comment by nullbio** [comment]
@rajm Did you ever find a solution to this?
