### ISSUE TITLE
Rocket.Chat doesn't include support for payloads buttons (quick_replies) from Botkit

### ISSUE THREAD

**Issue by refai2016** [RocketChat/Rocket.Chat#15062]
Hello,

I have managed to connect (Botkit to Rocket.Chat) successfully, however, I have noticed that the Rocket.Chat doesn't include support for payloads buttons (quick_replies) from Botkit. Can you please help me resolve this issue?

P.S. I am attaching some screenshots for further explanation

--------------------------------------------------------------------

![2019-07-25_17-03-00](https://user-images.githubusercontent.com/22276530/62003516-df9a1e00-b120-11e9-9675-4fdf9c0ce4e5.png)

--------------------------------------------------------------------

![2019-07-25_17-02-30](https://user-images.githubusercontent.com/22276530/62003525-f771a200-b120-11e9-8174-b913f3346f9c.png)

**Comment by reetp** [comment]
@rocket-cat close

At best this would be a feature request but there is already stuff open around this eg.

https://github.com/RocketChat/Rocket.Chat/issues/9937

For support you should ask about this at open.rocket.chat #bots where you likely get some assistance.

You might also want to search for something like 'botkit quick replies'

https://github.com/howdyai/botkit/issues/1679

**Comment by xkungfu** [comment]
> Hello,
> 
> I have managed to connect (Botkit to Rocket.Chat) successfully, however, I have noticed that the Rocket.Chat doesn't include support for payloads buttons (quick_replies) from Botkit. Can you please help me resolve this issue?
> 
> P.S. I am attaching some screenshots for further explanation
> 
> ![2019-07-25_17-03-00](https://user-images.githubusercontent.com/22276530/62003516-df9a1e00-b120-11e9-9675-4fdf9c0ce4e5.png)
> 
> ![2019-07-25_17-02-30](https://user-images.githubusercontent.com/22276530/62003525-f771a200-b120-11e9-8174-b913f3346f9c.png)

hello.
did you find a solution?

**Comment by Alhuzaifah** [comment]
Hi, did you find a solution?
