### ISSUE TITLE
Latest tag is not latest downloadable build

### ISSUE THREAD

**Issue by robopossum** [RocketChat/Rocket.Chat#15072]
The repo's latest tag is listed as 1.0.4 when navigating to https://github.com/RocketChat/Rocket.Chat/releases/latest, but latest version available from https://releases.rocket.chat/latest/download is 1.2.3

**Comment by reetp** [comment]
@rocket-cat close 

Latest tag is on 1.3.0 which has just been released.

Docker tags may be a little behind if you use 'latest' - better to use a specific version eg 1.3.0

Snaps can be a long way behind. Usually 2 weeks or so, but it depends on testing. The team only release when they consider it stable and secure enough.

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

"Snap releases are always delayed from regular releases for additional QA"

**Comment by ronnicek** [comment]
But it was somehow strange.. I have script which is checking latest and then updating server automagically :). And yes, I am not checking if latest is "greater" then previous :)

30.6.: New version of RocketChat (1.2.1) has been released.. will update it in 5 mins!
30.7. - 2.8.: New version of RocketChat (1.0.4) has been released.. will update it in 5 mins!
3.8.: New version of RocketChat (1.3.0) has been released.. will update it in 5 mins!
