### ISSUE TITLE
Wrong redirect from the rocket banner

### ISSUE THREAD

**Issue by asarubbo** [RocketChat/Rocket.Chat#15070]
I'm on rocket-1.2.1 and rocket is supposed to be on /rocket instead of /

Everything works fine except the rocket banner in the lower left, that is pointing on /home instead on /rocket/home and gives a a 403.

**Comment by reetp** [comment]
If you don't fill in the template properly no one can help you. Server type, proxy details etc etc please

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
