### ISSUE TITLE
Port 3000 SSL

### ISSUE THREAD

**Issue by shadowsberg** [RocketChat/Rocket.Chat#15085]
Good morning, I have a problem and I ask for your help, I do not speak English, help me with a translator, forgive any error, the case is that I have a server with ubuntu 18.04 and install via snap rocketchat, which runs on port 3000, there I also have a website in Laravel, when trying to implement the chat it tells me that it is blocked by mixed content, my website has SSL but in port 3000 it is without ssl, if you could give me a light of what I can do I would appreciate it.

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

This seems to be a setup/support issue.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/


Please also read the snap and caddy documentation

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/
