### ISSUE TITLE
Rocket.Chat LDAP User Search Filter not working 

### ISSUE THREAD

**Issue by princy-patel** [RocketChat/Rocket.Chat#15081]
### Description:
I have a group in AD named "rocketchat" which has some users in it. I want to allow only this group users to connect to Rocket.Chat. Therefore I am using **User Search** Filter.
I have tried different strings given below but none of them worked for me.   

1. CN=rocketchat,OU=XXX+OU=XXX,DC=XXX,DC=XXX,DC=com

2. &(memberOf=CN=rocketchat,OU=XXX+OU=XXX,DC=XXX,DC=XXX,DC=com)

3.(&(&(objectCategory=person)(objectclass=user)(memberOf=CN=rocketchat,OU=XXX+OU=XXX,DC=XXX,DC=XXX,DC=com))(sAMAccountName=username))

### Steps to reproduce:

1. Login Rocket.Chat using Admin account. 
2. Go to LDAP settings
3. Scroll down to **User Search**.
4. In **Filter** : tried all above given filters
**Scope** : sub
**Search Field** : sAMAccountName

### Expected behavior:
Only users that belong to "rocketchat" group should e allowed to Login.

### Actual behavior:

All users of AD can login

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.2
- Operating System: RHEL7.5
- Deployment Method: Manual Installation
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: 4.0.9

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

There is no evidence of a bug and it seems to be a setup/support issue.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

Also before opening an issue please read this:

https://rocket.chat/docs/contributing/reporting-issues

Always test on latest as your Issue may be fixed.

Note there are a number of open issues on LDAP so please read them too. Eg #14278
