### ISSUE TITLE
Change the channel topic from an input to a textarea to support markdown better

### ISSUE THREAD

**Issue by brendanheywood** [RocketChat/Rocket.Chat#15089]
We extensively use the channel topic to add links to wikis, github issues, file storage etc, and all of these can be multiple lines of markdown but only render as a single line of nice links.

So I would like this to be a textarea which defaults to a single lineheight but then resizes as you add more content to it.

**Comment by reetp** [comment]
@rocket-cat close

Thank you for your comment.

This repo is for bugs in Rocket.Chat

Please note that all new feature requests should be opened here:
https://github.com/RocketChat/feature-requests/issues
