### ISSUE TITLE
Allow admins to create users

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#1509]
Optionally make it so that new users must change their password on first login.

**Comment by AdrianoCahete** [comment]
Create batch users (from a csv file, f.e.) it's good too.

**Comment by shtefcs** [comment]
:+1:

**Comment by cperrin88** [comment]
:+1 That feature is really useful.

**Comment by jclabaugh** [comment]
+1 would definitely be useful

**Comment by tholu** [comment]
+1

**Comment by mide** [comment]
More information on forcing a password change here: #689

**Comment by soenkef** [comment]
+1

**Comment by Againstreality** [comment]
+1

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/13233993/3b5c8a14-d995-11e5-91c4-36e959fedbee.png)
