### ISSUE TITLE
Make user status more visible (want to contribute)

### ISSUE THREAD

**Issue by pepjo** [RocketChat/Rocket.Chat#15091]
Hi all,

first of all thanks for this amazing product, it is a pleasure to use every day.

The issue I have is that I find **hard to tell at a glance the status of a user**. At my company, we started using them to tell wheater someone is working from home or off. However, since they are hard to see people starting changing their names instead adding the status in brackets after their first name.

To solve this I would like to make the user status more visible at a glance. There are four places I think this could be done:
- In the **left lateral bar**
  - The easiest to achieve. Would be the first one I would try.
- In the **username when someone speaks**
- In the **username when someone is tagged**
  - I think that these two could be achieved by some sort of hover element that displays user details.
- In the **dropdown menu** when trying to **tag** someone
  - Added directly in the dropdown menu

My intention would be to contribute these solutions starting by the simplest, provide a Pull Request and once it is accepted move to the next one.

Before starting I would like feedback on how do you think could be best implemented.

Best,
Pep

**Comment by zdumitru** [comment]
@pepjo Great idea! Implement it to be visible in the **left bar** and make it go into release. Everything else you may do later or in different PRs. No need to do huge tasks, work in small increments.

**Comment by wreiske** [comment]
There's been some good discussion about this here: https://github.com/RocketChat/feature-requests/issues/138

**Comment by pepjo** [comment]
This is a shame especially because I made a [PR](https://github.com/RocketChat/Rocket.Chat/pull/15187) for it that never got reviewed. We would have benefited from this feature.

**Comment by wreiske** [comment]
I hate you, stalebot.
