### ISSUE TITLE
LDAP Sync does not delete users

### ISSUE THREAD

**Issue by disaster123** [RocketChat/Rocket.Chat#15103]
### Description:

LDAP Sync is enabled and also syncronize user data.

### Steps to reproduce:

Sync with LDAP.

### Expected behavior:

No longer existing Users in LDAP should be deleted.

### Actual behavior:

Users stay forever.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.0

**Comment by reetp** [comment]
@rocket-cat close

This isn't really a bug as Rocket.Chat doesn't actually break.

It is more of a feature request - it just doesn't do what you want it too. Feature requests go here.

https://github.com/RocketChat/feature-requests/issues

In any event, there needs to be some thought on whether a user is just disabled, or deleted completely.

You may want to actually follow up on something like this:

https://github.com/RocketChat/Rocket.Chat/pull/14260

Some other references here:

https://github.com/RocketChat/Rocket.Chat/pull/14278
