### ISSUE TITLE
Rocket chat client scan networks for server

### ISSUE THREAD

**Issue by aermike** [RocketChat/Rocket.Chat#15100]
Hi
I have an RocketChat server with 3 instances as an chat server and locally I have an rocketchat server with livechat.
Rocket chat client installed from 2.14.x to 2.15.3
Locally server appear as server in client UI but never was added from me

**Comment by geekgonecrazy** [comment]
Source code for desktop clients can be found here:  https://github.com/RocketChat/Rocket.Chat.Electron/tree/develop/src

There is no code to automatically discover servers and especially not add them.  Your sysadmin or who ever set things up may have set up to add.  Maybe even clicking a rocketchat:// link that would be handled by the client.

If you find steps to reproduce or an actual error in the code please let us know.  If true we definitely would address it.  But reading through the code I don’t see anything that would automatically discover and with out asking add the server
