### ISSUE TITLE
"Snippet message" button missing context menu

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#15101]
### Description:

When activating the snippet feature (Admin UI → Message → Allow Message Snippeting), there is no way to actually snippet a message.

### Steps to reproduce:

1. Enable snippeting feature
2. Try to snippet a message

### Expected behavior:

Option to "Snippet" should be visible

### Actual behavior:

No button visible. Not possible to snippet a message.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.0
- Operating System: Docker
- Deployment Method: Docker
- Number of Running Instances: Docker
- DB Replicaset Oplog: Docker
- NodeJS Version: Docker
- MongoDB Version: Docker

### Additional context

<img width="245" alt="Bildschirmfoto 2019-08-04 um 12 43 05" src="https://user-images.githubusercontent.com/944459/62422629-e04d2a00-b6b5-11e9-895c-23f8aaa48e28.png">

**Comment by Fogha** [comment]
Hello, i am interested in this issue. So i have to ask, what should the snippet button do when clicked

**Comment by Fogha** [comment]
i am wondering if i have to add some other functionality to the snippet message button

**Comment by kdre** [comment]
I have the same problem. Any solution?

**Comment by torwag** [comment]
I have to add there is no difference in any of the possible roles and snippet access was given to all users. Thus, it seems not to be a permission problem

**Comment by jasoncscott** [comment]
I believe it was commented out several versions ago:
* https://github.com/RocketChat/Rocket.Chat/pull/14268

and is intended to be revisited as an attachment:
* https://github.com/RocketChat/feature-requests/issues/99

**Comment by EnCz** [comment]
Anything new on this ?
