### ISSUE TITLE
LDAP - after PW change in LDAP user can log into RC only with old PW

### ISSUE THREAD

**Issue by kokotko1337** [RocketChat/Rocket.Chat#15110]
### Description:

After password change in AD users can not login into RC with new password only with old password.

### Steps to reproduce:

1. User change his Windows PW - policy change PW in 3 Month
2. User try to login into RC - it is not wokring with new password only with old PW

### Expected behavior:

After change PW in AD should be able to login with new password.

### Actual behavior:

User can login into RC only with old PW - which means that is somewhere stored locally on Rocketchat server

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Ubuntu 16
- Deployment Method: manual
- Number of Running Instances:  1
- DB Replicaset Oplog: y
- NodeJS Version: v8.15.0

- MongoDB Version: 
MongoDB shell version v3.6.10
git version: 3e3ab85bfb98875af3bc6e74eeb945b0719f69c8
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64

### Additional context

RC Config:
 - Users can change their PW in RC
- Test connection to Ldap working
- Authentification - service acc read only

If Login Fallback is set to FALSE - NO ONE can log into RC.

Background Sync Now - not working - Passwords are not synced with LDAP

**Comment by reetp** [comment]
Please read the guide in the bug template:
https://rocket.chat/docs/contributing/reporting-issues

"Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

At the very least please test this on a VM using 1.3.0 which as just been released.

> Background Sync Now - not working - Passwords are not synced with LDAP

That will most likely be why the new passwords are not accepted. Why is it disabled?

**Comment by kokotko1337** [comment]
thanks for help, i got RC in VM so i can do snapshot and try to update it to latest... 

Backround sync is eabled, but it is not working/syncing ....

**Comment by kokotko1337** [comment]
This behavior is really strange. He is saying that LDAP PW is wrong then he use fall back and accept old PW ...




Log is saying:

Connecting ldap://server.local:389
LDAP connected 
Searching user
Search result count 1 
 Authenticating CN=USER .....
Not authenticated CN=USER .....
error { InvalidCredentialsError....
Wrong password for USER
Fallback to default account system { username: USER ....
Success
