### ISSUE TITLE
Livechat widget: allow users to send emojis

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#15112]
Both livechat widget versions (old and 1.0.0) do not allow to send emojis. However, we have a use case where anonymous livechat users should be able to express emotions easily. Thus emoji support would be nice to have, ideally as a generic option in the livechat admin menu, as there may be application fields where emojis are not appreciated.

Same for reading #8236 - emojis sent by an agent are not shown in livechat widgets.

**Comment by reetp** [comment]
@rocket-cat label add duplicate

Duplicate of #8326 

Please just +1 the original bug - don't open a duplicate as it just makes unnecessary noise.

**Comment by reetp** [comment]
@rocket-cat close

**Comment by rasos** [comment]
#8236 was an issue for _displaying_ emojis in livechat. 

I created this new issue for _writing_ emojis in livechats. Okay to merge these two issues and rephrase #8236 accordingly.
