### ISSUE TITLE
OTR - Not working with multiple instances

### ISSUE THREAD

**Issue by raziel900** [RocketChat/Rocket.Chat#15126]
### Description:

We have a 3 node cluster with instances on each node. They are behind a loadbalancer and the setup is round-robin to share the load. Each node is offloading SSL using a local certificate which is CA signed. The issue we have is that when a user starts and OTR session with a user on a different node, the prompt for OTR doesn't appear.

![otr](https://user-images.githubusercontent.com/49512131/62605090-b08e6400-b8f9-11e9-8599-cdb3fa7d873c.jpg)

### Steps to reproduce:

1. Start OTR with a user
2. if on same instance, user gets prompt
3. if on separate instance, user doesn't get any prompts

### Expected behavior:

User gets prompt to accept OTR message even on separate nodes

### Actual behavior:

User does not get OTR prompt when on a different node

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Centos 7
- Deployment Method: Manual install
- Number of Running Instances: 3 on seperate nodes
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.4.11
- MongoDB Version: 4.0.10

### Additional context

We think it could be related to the local certificates, maybe there is a simple fix for this like shared certificate or multiple SANs

### Relevant logs:

Could not find any complaints in the logs

**Comment by reetp** [comment]
If nothing else I'd upgrade to at least 1.2.3 soonest if I was you....

Next, check for other OTR issues here.

e.g.

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+OTR

And then test on latest as per this please:

https://rocket.chat/docs/contributing/reporting-issues

**Comment by raziel900** [comment]
We have upgraded to 1.3.0 which is the latest version with the same results. We can reproduce it with multiple instances each time. Please let me know if I can somehow give more information or help

**Comment by emikolajczak** [comment]
Hi,
I have multpile instances configurations on number of machines and OTR works fine.
Please check if your instnaces are connected each other. You can check it in administration -> info. Detail on screen below.

![image](https://user-images.githubusercontent.com/50440047/62932230-0d898e80-bdc0-11e9-95dd-354efd108cfc.png)

**Comment by raziel900** [comment]
Hi @emikolajczak  Thanks so much for your update.

When I saw your screenshot i realised I was missing some configuration as I didn't have the Broadcast Connected Instances. I figured out I needed the **IP_ADDRESS** environment variable. After adding it, the instances could see each other and OTR is working cross instance. 
Thanks again!

Closing issue

**Comment by Poklop77** [comment]
Hi
