### ISSUE TITLE
Update Meteor to 1.8.1

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#15128]
[Meteor 1.8.1](https://github.com/meteor/meteor/releases/tag/release%2FMETEOR%401.8.1) has been out in the wild for a longer time fixing some issues which may cause performance issues operating on large collections. (e. g. https://github.com/meteor/meteor/issues/10359).

Is there any reason not to bump to the latest fix version?

**Comment by ggazzo** [comment]
there is 😞 
https://github.com/RocketChat/Rocket.Chat/pull/14462
we cant build on circleci for memory reasons

**Comment by mrsimpson** [comment]
Dann it. We also had something similar until we removed some dependency. 
CircleCI asked us to request `Ressource_class`, nur as I can see from the commit history, you already tried without success 😥
Have you also been in touch with CircleCI or are you focusing your efforts on moving to another CI?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ggazzo** [comment]
@sampaiodiego 🔝

**Comment by sampaiodiego** [comment]
right.. we tried with a larger resource class successfully, but it'd be way too expensive.. 

I haven't tried using SSH to see what happens.. I'll give it a try and maybe contact CircleCI again.

I was trying is to remove some dependencies too, but still got no luck.. I still have some ideas on which dependencies to remove, let's see how that goes as well.

We really like CircleCI so we were trying stick with it. But we also tried drone.io which worked great.. if we can't find a way to keep using CircleCI we're considering going on-premise with drone.io 

@geekgonecrazy @rodrigok just to keep you guys posted as well =)

**Comment by tassoevan** [comment]
Is it failing always in the same step of the build process?

**Comment by sampaiodiego** [comment]
well, it always fails on the `meteor build` command.. not sure which internal step.

**Comment by mrsimpson** [comment]
If you have profiling activated you’ll see that it (probably) always fails at the same step (which is still quite coarse)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rodrigok** [comment]
It always fail on JS minify what uses a lot of memory :(

**Comment by mrsimpson** [comment]
@rodrigok we( @sampaiodiego and myself) figured yesterday the issue can be mitigated by better making use of the meteor build cache. 
Even bluntly building three times in a row will eventually succeed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ggazzo** [comment]
closed  by https://github.com/RocketChat/Rocket.Chat/pull/15358
