### ISSUE TITLE
non-admin users can't see custom fields in `users.list`

### ISSUE THREAD

**Issue by humancatfood** [RocketChat/Rocket.Chat#15138]
### Description:

I've successfully added custom fields to the users in my RC installation. I can retrieve the custom fields when calling the `users.list` endpoint. But only when logged in as an administrator.

How do I see custom fields as any user?

### Steps to reproduce:

1. As an administrator, go to `/admin/Accounts`
2. Under `Registration` set `Custom Fields` to
```json
{
	"test": {
		"type": "text",
		"defaultValue": "",
		"required": true,
		"public": true
	}
}
```
(I've only found out about the 'public' field [here](https://github.com/RocketChat/docs/pull/1174/files))
3. goto `/account/profile` and set your `test` field to some value
4. Make an authenticated API request to `/api/v1/users.list` (note how `customFields.test` is included in the returned data)
5. Log out and back in again as a non-admin user
6. Make an authenticated API request to `/api/v1/users.list` (note how `customFields.test` is **not** included, breaking everything that depends on custom fields)

### Expected behavior:

the `customFields` entry should consistently be returned when asking for `users.list`

### Actual behavior:

it isn't, unless you're logged in as an admin. 
To display custom fields in my list of users, I have to either

- hit the `users.info`endpoint for each user individually, or
- enable the `view-full-other-user-info` permission for normal users meaning that *everything*, even private information gets sent to everybody

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Darwin 16.7.0
- Deployment Method: cloned `https://github.com/RocketChat/Rocket.Chat.git` and run locally
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.2

**Comment by humancatfood** [comment]
related: https://github.com/RocketChat/Rocket.Chat/issues/13934

**Comment by humancatfood** [comment]
Commenting out `/app/api/server/api.js`, line 49 does the trick.

Arguably, custom fields that are `public=true` should be returned when listing users.

**Comment by MarcosSpessatto** [comment]
Hi @humancatfood, to be able to retrieve the full user info, there is a permission on permissions panel called: `view-full-other-user-info`. Can you please try to enable it and try again?

**Comment by humancatfood** [comment]
> enable the view-full-other-user-info permission for normal users meaning that everything, even private information gets sent to everybody

I tried that, but that shows _everything_, emails, password, etc.

**Comment by ggazzo** [comment]
actually @MarcosSpessatto the customFields with "public: true" should be returned even for ordinary users... `view-full-other-user-info` is a "high" permission and as @humancatfood said it will return more info than we should expose
