### ISSUE TITLE
RocketChat Failed to Start

### ISSUE THREAD

**Issue by chimsue245** [RocketChat/Rocket.Chat#15137]
[root@localhost ~]# systemctl status rocketchat.service
â rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/usr/lib/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-08-07 22:49:46 EDT; 5s ago
  Process: 10441 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 10441 (code=exited, status=1/FAILURE)

Aug 07 22:49:45 localhost.localdomain systemd[1]: Started The Rocket.Chat server.
Aug 07 22:49:46 localhost.localdomain systemd[1]: rocketchat.service: main process exited, code=exited, status=1/FAILURE
Aug 07 22:49:46 localhost.localdomain systemd[1]: Unit rocketchat.service entered failed state.
Aug 07 22:49:46 localhost.localdomain systemd[1]: rocketchat.service failed.

how can i fix this TIA. beginner in Centos .

**Comment by reetp** [comment]
@rocket-cat close

I don't see any evidence of a bug.

> how can i fix this TIA. beginner in Centos 

Github is reserved for bugs in Rocketchat, not support.

Please ask your well researched and documented question in:

https://forums.rocket.chat or https://open.rocket.chat #support

If you do want to create an Issue then use a proper template:

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Also see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
