### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#1513]
Can I haz access? Plz! :wink: 
![2015-11-27_16-41-20](https://cloud.githubusercontent.com/assets/850391/11448779/b6c82884-9525-11e5-855a-6bfd877b0f2e.png)

**Comment by graywolf336** [comment]
This happens on any channel, direct messages, and private group.

**Comment by geekgonecrazy** [comment]
@RocketChat/core 

Also looks like its doing something heavy on the page, it locks up if you try and navigate much.  Or at least did on mine.  ;)

**Comment by engelgabriel** [comment]
I am trying to fix.. i'll revert.

**Comment by engelgabriel** [comment]
deploying
