### ISSUE TITLE
Secret URL page empty

### ISSUE THREAD

**Issue by haceru** [RocketChat/Rocket.Chat#1514]
I have been testing the "Secret URL" registration method, but when going to http://mydomain.com/secreturl it just comes up with an empty page (correct title, correct background color, just no registration form)

**Comment by marceloschmidt** [comment]
This has not been implemented yet. I'll report here when it's done.

**Comment by marceloschmidt** [comment]
Actually, will report on #1508, which is the main issue. Closing this.
