### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by chimsue245** [RocketChat/Rocket.Chat#15143]
Hi guys. Good day. I just want to ask how can i backup my database and restore to another fresh installed rocketchat server? I want to backup all messages , configuration , group channel and the users if it is posible ?

Im using centOS7 and Mongodb
TIA.

**Comment by wreiske** [comment]
I would start by reading https://docs.mongodb.com/manual/tutorial/backup-and-restore-tools/

Since this is not an issue and more of a question, I would recommend checking https://forums.rocket.chat/

@rocket-cat close

**Comment by reetp** [comment]
And note that you should avoid restoring between different Rocket versions.

So don't try to backup on say 0.74.x and restore to 1.2.x Always use the same versions

**Comment by reetp** [comment]
@rocket-cat close
