### ISSUE TITLE
IE11 is stuck on loading screen

### ISSUE THREAD

**Issue by matzexcom** [RocketChat/Rocket.Chat#15152]
### Description:

When opening Rocket.Chat web interface the page stucks on loading with the three loading dots.

### Steps to reproduce:

1. Start IE11
2. open https://open.rocket.chat
3. stuck on the loading animation

### Expected behavior:

It should load the login form like the other browsers.

### Actual behavior:

Page stucks loading with the three loading dots (animated).

![console Error](https://user-images.githubusercontent.com/25659904/62773747-40bbdd00-baa3-11e9-8a6c-3dc7932b9b8c.jpg)
![marked semicolon](https://user-images.githubusercontent.com/25659904/62773751-444f6400-baa3-11e9-9d52-3e2af982bb5b.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: our server v1.3.0; open.rocket.chat 2.0.0-develop
- Operating System: Debian
- Deployment Method: Manual install
- Number of Running Instances: 1
- NodeJS Version: v8.16.0
- MongoDB Version: 4.0.11

### Additional context

Related Issue #13989, #9385
Maybe related with #14802 but there is an other console log
should have been solved with PR #14422

IE11 support worked with Rocket.Chat v1.1.0, seems to be a regression.

**Comment by reetp** [comment]
Discussed this with the OP in open.rocket.chat

https://open.rocket.chat/channel/support?msg=2PArmctCg36HQneux

They had done some pretty good testing so not sure what has happened here but looks like a regression somewhere - it seemed to be working up to about 1.1.x

> I first tested it in Dec 2018 and it worked with a lot of design bugs, these bugs were mostly fixed with PR #14422. so it worked with 1.1.0.
> Next check was today with 1.3.0, with the stucking loading animation

Further info - they are using (still supported):

Win7 IE11 and Win10 (1703) IE11 and EDGE

Also note this comment - I think this is a more up to date version of Windows but not sure which - perhaps the OP can advise

> I can reproduce IE11 loading issue with private pc, EDGE is working

I am pretty sure there are a lot of companies that do not want to be Beta testers and run the latest and greatest so just saying 'update your OS' isn't always the solution for many. They are are on older _supported_ versions and can't necessarily upgrade overnight.

**Comment by matzexcom** [comment]
@reetp 
Private windows pc is on the latest version 1903

**Comment by matzexcom** [comment]
v1.3.2 solved the loading issue in IE11,
thanks a lot :)
