### ISSUE TITLE
GitHub login returns 404

### ISSUE THREAD

**Issue by jianlianggao** [RocketChat/Rocket.Chat#15151]
### Description:

I am using rocket.chat:1.2 docker container with mongo 3.2 on Ubuntu 18.04. Because my old rocket chat db and history were on mongo3.2, I tried the latest rocketchat but failed to load chat history. So I have to stay with mongo3.2. When I set enable GitHub login in the OAuth option, I found when clicking on GitHub login, it returns 404 page not found error. My chat domain is https:// 

### Steps to reproduce:

1. https://chat.biomedia.doc.ic.ac.uk
2. github login  (same issue to gitlab.doc.ic.ac.uk )
3. 

### Server Setup Information:

- Version of Rocket.Chat Server:  1.2
- Operating System:  Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: mongo 3.2
- NodeJS Version: 
- MongoDB Version: 3.2

**Comment by reetp** [comment]
https://rocketchat.github.io/docs/contributing/reporting-issues

"Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

You should be on a minimum of 1.2.4

https://github.com/RocketChat/Rocket.Chat/releases/

Also test on latest 1.3.1 - it will still run on mongo 3.2 I believe.

However this doesn't bode well:

> github login (same issue to gitlab.doc.ic.ac.uk )

And neither does this - you need to fix your proxy and get your websockets working first I think:

```
Request URL:https://chat.biomedia.doc.ic.ac.uk/sockjs/041/3np3nboq/websocket
Request method:GET
Remote address:146.169.22.11:443
Status code:
400
```

**Comment by jianlianggao** [comment]
Thank you very much. Let me try to work out the websocket.

**Comment by jianlianggao** [comment]
Hi,
I added into my config

```
location /socket.io/ {
        proxy_pass http://websocket;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";

         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forward-Proto http;
         proxy_set_header X-Nginx-Proxy true;

    }

  location /socket.io/socket.io.js {
        proxy_pass http://websocket;
    }
```

my websocket is
```
upstream websocket {
    server <my host>:3000;
  }

```

Still got same error. What shall I do?

Best wishes,
Jianliang

**Comment by reetp** [comment]
This still looks like a configuration/support issue and not a bug and you should be asking these questions in https://forums.rocket.chat or https://open.rocket.chat #support

You have made no attempt to explain what happened to your old install or what settings you have used on your new install. There isn't much help that can be given.

And we have no idea of the relevance of this:

> github login (same issue to gitlab.doc.ic.ac.uk )

I'd suggest first you make sure you are on at LEAST v1.2.4 https://github.com/RocketChat/Rocket.Chat/releases/ which includes a change here https://github.com/RocketChat/Rocket.Chat/pull/15141

I'd also suggest you go get some logs to see if there is a real issue in Rocket, and check your github OAuth settings.

**Comment by geekgonecrazy** [comment]
Our github login still works on our open server last I checked: open.rocket.chat

Maybe go through and verify all values again?

**Comment by jianlianggao** [comment]
Thanks for the hint. But honestly, I haven't got clues. I only checked enable GitHub login in the OAuth option. Should I set client id and secret? And how?

Best wishes,
Jianliang

**Comment by reetp** [comment]
Did you have this working on your old Rocket.Chat?

> I only checked enable GitHub login in the OAuth option. Should I set client id and secret? And how?

Please read the documentation. 
https://rocket.chat/docs/administrator-guides/authentication/oauth/

**Comment by geekgonecrazy** [comment]
Ah yes if you are missing client Id and client secret GitHub will reject.

https://github.com/settings/applications Create a new application at this address.  And copy the Id and secret over.  Also make sure to format the url there like suggested in that document @reetp sent

**Comment by jianlianggao** [comment]
@geekgonecrazy @reetp Thank you very much for your instructions. I have my rocket chat instance working properly with GitHub and GitLab login.
