### ISSUE TITLE
Right-side tab for in-chat browser / frame window

### ISSUE THREAD

**Issue by haceru** [RocketChat/Rocket.Chat#1515]
First, please allow me to say a big THANK YOU ! for a great project.

Second, my question is if it would be possible to activate a tab for a fly-in panel that would act like a browser (or at least like a frame) in order to access a web-site from within the chat.

I am asking this because I would love to integrate Liquidfeedback (an on-line voting platform) with Rocket Chat. For the moment the only way to access Liquidfeedback is through a browser (there is no API yet).

Any suggestion would be greatly appreciated.
##

**Comment by graywolf336** [comment]
I believe it would be possible. Create a package for it and then maybe use an iframe or webview in the side panel.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
