### ISSUE TITLE
how to post image onto rocketchat through stackstorm

### ISSUE THREAD

**Issue by vageesh7** [RocketChat/Rocket.Chat#15163]
I am not finding any document on how to post image onto rocketchat through stackstorm. could anyone help me on this?

**Comment by reetp** [comment]
@rocket-cat close

This repo is for bugs in Rocket.Chat, not support requests.

Please look at the API in the documentation:

https://rocket.chat/docs/developer-guides/

Ask questions in the forums or open.rocket.chat #support after you have read all the documentation.
