### ISSUE TITLE
Regitration of user not working

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#1516]
I got many complains about how people can't register on chat. 

I didn't realize it's really not working until I tested my sefl now.

After filling registration info, its just say *waiting*

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/b1649a11-6a18-49aa-94a8-d9a600c63428/2015-11-28_2052.png)

In admin side it's say that username is empty

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/a74762a5-f38b-4e26-a79d-81b90e485f22/2015-11-28_2055.png)

Anyone encountered this problem as well ?

**Comment by wtsarchive** [comment]
I also have this issue, though I'm using OAuth. In only some cases the registration seems to fail, and I have and account record with blank `Name` and `Username` fields, only with E-mail. Any thoughts on how to debug this?

**Comment by shtefcs** [comment]
Additionaly,  I need to manualy add **username** so people can login at the end.

**Comment by marceloschmidt** [comment]
Can you reproduce this with ease? If you can, can you also check the console for errors or the network traffic on the websocket?

**Comment by marceloschmidt** [comment]
Another question, under Administration -> Accounts -> Registration, is Registration with Authentication Services disabled? Thank you.

**Comment by marceloschmidt** [comment]
I think I fixed it in `develop` branch. Please test and if it doesn't work, we may reopen this issue.

**Comment by shtefcs** [comment]
On my settings `Registration with Authentication Services` is **True** .

What that option mean Marc ?

Will update my chat soon and let you know if its fixed.

Tnx

**Comment by marceloschmidt** [comment]
That option means that if the user tries to login via Facebook, but the e-mail is not yet registered on RocketChat, if the option is set to false (disabled), then the user won't be able to login, as the user won't be created.

**Comment by wtsarchive** [comment]
@marceloschmidt 
I have a reproducible case.
User registration fails in one of these two cases:
* chosen username contains a space
* chosen username contains non-latin characters (in my case, polish accented characters like: ł)

By chosen username I mean the one you pick as the last step of registration.
