### ISSUE TITLE
Escaped brackets are removed from code blocks

### ISSUE THREAD

**Issue by pavel-sedek** [RocketChat/Rocket.Chat#15161]
### Description:

When an escaped bracket is pasted in code block, it disappears

### Steps to reproduce:

1. Open any chat
2. Paste a code block containing `\(.\)`

### Expected behavior:

The code block should be pasted unchanged.

### Actual behavior:

The backslash and brackets are removed from code block. Just the dot retains.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.3
- Operating System: Linux 4.19.0-5-amd64
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.13

### Additional context

Also the instance on https://open.rocket.chat is affected

Pasting brackets without backslash works correctly. `(.)` Pasting brackets with backslashes but without any content also works correctly. `\(\)`

### Relevant logs:

N/A

**Comment by ggazzo** [comment]
duplicated of https://github.com/RocketChat/Rocket.Chat/issues/15160
