### ISSUE TITLE
Rocket Chat Message date/time format

### ISSUE THREAD

**Issue by jdavis7718** [RocketChat/Rocket.Chat#15170]
### Description:  Ability to customize the format of date/time on the message output

Our users would like to copy messages from rocketchat to put into other applications, text files, e-mails etc.  Currently only the time appears on the original message, you must hover over the time to reveal the date of the message.  When copying/pasting to another application only the time is copied and not the date.   For tracking reasons it is important for them to be able to capture the date as well as the time.  Is it possible to make this something that can be altered by the user or globally to all users to reveal the date and the time without hovering? 

### Steps to reproduce:

1. Send message, you will notice only the time is revealed
2. Copy the text
3. Past into any other application

### Expected behavior:

To be able to capture the full date as well as the time

### Actual behavior:

Only the time is captured in the copy/paste

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.0 
- Operating System:  CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.13

**Comment by MartinSchoeler** [comment]
Actually, if you go to `Administration -> Message`  you can change the time formatting on your server.
![Uploading Screen Shot 2019-10-22 at 11.10.51.png…]()
