### ISSUE TITLE
Enable all kind of mime type for file upload

### ISSUE THREAD

**Issue by eclickhu** [RocketChat/Rocket.Chat#1518]
We would like to enable all kind of mime type beceause we are sending a lot of different file types e.g. .apk, .zip, .csr. I added these to admin image/*,audio/*,application/* but nothing happened. 

Could anyone help us to enable all mime type?

**Comment by k0nsl** [comment]
Hi @eclickhu 

This is what I currently have on my instance: `image/*,audio/*,application/*,video/*,text/*`

You may have to restart your instance after adding the new mime types.

**Comment by eclickhu** [comment]
Thanks!

**Comment by sajtdavid** [comment]
Still can't upload *.sql

**Comment by redgang** [comment]
@k0nsl  I added these to admin image/*,audio/*,application/*,video/*,text/*, and restart my instance ,but `.apk` also can't upload, why?
