### ISSUE TITLE
Missing numbers in multi line code

### ISSUE THREAD

**Issue by comander192** [RocketChat/Rocket.Chat#15180]
### Description:

We share a lot of config/code lines via Rocket.Chat which is really appreciated btw. Yesterday we encountered what seems like a bug where the multi line code input is missing some numbers in the visual output under certain circumstances. We couldnt recreate that problem yet, but we have one output that triggers that behaviour consistently. When I edit my comment all numbers are there bit if I copy the multi line formatted output the numbers are also missing.

We also updated Rocket.Chat to the latest version after seeing this but the problem still exists.

### Steps to reproduce:

1. Add multi line code
2. Insert following text without the *:

** # Min/start heap size
** java.memory.min=128M
** 
** # Max heap size
** java.memory.max=1024M
** 
** # Max Permgen size, default=64M
** java.memory.perm=64M**

### Expected behavior:

All Numbers will be shown correctly in formatted output

### Actual behavior:

![image](https://user-images.githubusercontent.com/26652586/63080620-d3e09100-bf41-11e9-8016-76cb888b446c.png)

First number is cut in formatted output. If i want to edit the last comment all numbers are shown correctly in the editing window.

When I copy from the formatted output the numbers are also missing in the copied part.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: RedHat7 3.10.0-957.10.1.el7.x86_64
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled rs01
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.6

### Additional context

none

### Relevant logs:

Log output shows all numbers:
`msg: '```<br># Min/start heap size<br>java.memory.min=128M<br><br># Max heap size<br>java.memory.max=1024M<br><br># Max Permgen size, default=64M<br>java.memory.perm=64M<br>```',      ts: 2019-08-15T07:53:02.448Z`

**Comment by comander192** [comment]
I just saw something interesting. The same behaviour seems to happen here on github, as soon as I only use 1 # at the beginning of the comment line it will be formatted as a headline. When I change it to 3 ### it will be formatted correctly. 

Using this knowledge to edit the text in Rocket.Chat it will be formatted correctly:

![image](https://user-images.githubusercontent.com/26652586/63081973-4acb5900-bf45-11e9-8625-a618a316732e.png)

Is this expected behaviour? For us it seems very strange and could be very bad when we share code/config parts where we dont know the exact numbers. For memory parameters like in the example this is not as bad because one can guess the error. Other numbers could be problematic though.

**Comment by reetp** [comment]
It may be a limitation of the markdown parser Rocket uses rather than a direct issue with Rocket.

**Comment by reetp** [comment]
There were a couple of other recent markdown issues. Are they related?

Can't see from here.

**Comment by geekgonecrazy** [comment]
if this is still an issue for you please drop the exact block of text so we can copy it and test it out. This will make it much easier for a dev to reproduce

**Comment by comander192** [comment]
Hi @geekgonecrazy 

thanks for the help, we will update to the latest version tomorrow and test it again.

**Comment by comander192** [comment]
Hi @geekgonecrazy 

the problem seems to be fixed with Version 3.6.2 running in Docker and connected to MongoDB 4.0.6.

Thanks for the help!
