### ISSUE TITLE
How i can disable ember preview pdf file

### ISSUE THREAD

**Issue by bhdung** [RocketChat/Rocket.Chat#15181]
Hi everyone
I'm newbee, im running with rocket chat on permise with version 1.3.2 . I'm using rocket chat desktop app in my company. But problem the app always go blank when user upload pdf file, the problem just only in this user and with who recieve pdf file. I think the problem is ember preview first page of pdf file
My question how i can disable ember preview pdf file. User just only download don't need see preview.
I hope someone can help me do that. Thank so much

**Comment by reetp** [comment]
@rocket-cat close

Github is for bugs, not support requests. There is no evidence anything is broken - it just doesn't work the way you want (which is a https://github.com/RocketChat/feature-requests)

Make sure you give proper details of your setup as per these:

https://rocket.chat/docs/contributing/reporting-issues
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Please make sure that any reverse proxy and websockets are working correctly

A workaround for your situation is here:

https://github.com/RocketChat/Rocket.Chat/issues/15082

Or ask in community support in open.rocket.chat #support but note this is community support so you might need to be patient with your questions.
