### ISSUE TITLE
unread message marker sometimes doesn't show

### ISSUE THREAD

**Issue by JanZerebecki** [RocketChat/Rocket.Chat#15189]
### Description:

Sometimes the unread message marker doesn't show. Note that this sometimes works as expected, but not always.

This worked before on version 0.74.3.

This looks similar to https://github.com/RocketChat/Rocket.Chat/issues/12938 but with a normal public room instead of a livechat.

### Steps to reproduce:

1. Have a channel that has unread messages, but not more then perhaps 1 or 2 pages of unread ones.
2. Click on the channel to view its messages
3. See no unread message marker nor the Jump to first unread bar.
4. Channel is marked as read.

### Expected behavior:

The unread message marker should be visible. Even better would be that a previous unread message marker (different color?) remains after the channel was marked read so that one doesn't miss it.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: 
- Deployment Method: docker on kubernetes
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 
- Browser: Firefox 68

### Relevant logs:
Not sure if it is related, but this appears in the browser console from time to time.
```
TypeError: 'name' member of PermissionDescriptor 'microphone' is not a valid value for enumeration PermissionName.
```

**Comment by dannysauer** [comment]
FWIW: using the Windows client v. 2.15.2 (at the same site as @JanZerebecki), I'm seeing the indicator flash quickly and then disappear as the room becomes all read upon simply entering a room that has unread messages.

So I suspect this isn't browser-dependent.

**Comment by zdumitru** [comment]
Could be that one - #14869

**Comment by JanZerebecki** [comment]
This happens also without threads. Yes, the underlying bug could the same as #14869.

**Comment by mddvul22** [comment]
We are having this problem is 2.2.1.  We are experiencing it in the desktop clients, in Firefox and in Chrome.

**Comment by rgembalik** [comment]
Actually I have several different behaviours reported form our team - some say it disappears too quickly, for others it stays there for a long time (or until cleared manually from the channel list). I think the first issue is on browsers, the second when using the windows app, although I am not sure. Some channels tend to have more problems with the marker disappearing or appearing for too long. There is a big difference for example between a large channels (in terms of messages count) and small channels, the first having unread messages line hanging for longer.

**Comment by mddvul22** [comment]
Is it possible to place a monetary bounty on this issue so that we can help fund resolution?

**Comment by mddvul22** [comment]
This problem still exists.  This should not have been closed.
