### ISSUE TITLE
livechat widget cannot establish connection through wss protocol

### ISSUE THREAD

**Issue by nsdev0** [RocketChat/Rocket.Chat#15191]
### Description:
After installed update v1.2.3 livechat widget cannot establish connection through wss protocol.
Firefox says something like:
> The connection to wss://rocketchat/sockjs/415/ep2wtnjr/websocket was interrupted while the page was loading.

### Steps to reproduce:

0. Set up bundled in snap web proxy Caddy
`rocketchat
proxy / localhost:3000 {
  websocket
  transparent
}`
1. Set up new version of Rocket.Chat Livechat in your website
2. Go to the web page with embedded livechat widget

### Expected behavior:
Wss should work.

### Actual behavior:
Wss doesn't work.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.3
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: On
- NodeJS Version: v8.15.0
- MongoDB Version: 3.4.20

**Comment by renatobecker** [comment]
@nsdev0 can you please share the link of the website where the Livechat widget is installed?

**Comment by siteleas** [comment]
@renatobecker Hey there, we have our Rocket.Chat server up and running and worked through several configuration issues, but all-in-all the server is working well.

However, we are having a couple of problems with the LiveChat Widget.

1. Delay in showing is too long
2. Though the widget appears and though we have users assigned to livechat, when a website visitor fills in the information form and submits it, the form goes away, but there is no welcome message in the popup window, there is no text history after sending messages, and rocketchat only sounds a notification, but our livechat users don't actually get the message.

You can see our sample site at sitelease.ca

**Comment by renatobecker** [comment]
> @renatobecker Hey there, we have our Rocket.Chat server up and running and worked through several configuration issues, but all-in-all the server is working well.
> 
> However, we are having a couple of problems with the LiveChat Widget.
> 
> 1. Delay in showing is too long
> 2. Though the widget appears and though we have users assigned to livechat, when a website visitor fills in the information form and submits it, the form goes away, but there is no welcome message in the popup window, there is no text history after sending messages, and rocketchat only sounds a notification, but our livechat users don't actually get the message.
> 
> You can see our sample site at sitelease.ca

Hi @siteleas you need to enable CORS on the Rocket.Chat admin area to get the Livechat working properly.
If you check the browser console, you'll see some errors related to the CORS stuff.

Thanks.

**Comment by renatobecker** [comment]
@nsdev0 any news on this issue or can we close it?
