### ISSUE TITLE
Channel search does not include threads/thread titles

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15200]
- Version of Rocket.Chat Server: open.rocket.chat - 19/08/2019

Search for a word in channel. See result below.

Also, if you click to show threads you cannot search them.

![Screenshot_2019-08-19_16-50-42](https://user-images.githubusercontent.com/3800384/63275360-b1cc7300-c2a1-11e9-9636-a54bb468360d.png)

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15094 :)

**Comment by reetp** [comment]
FYI this is still doesn't work very well as per 15884

It kind of works, but the output is messy.
