### ISSUE TITLE
[FR] Status next to username

### ISSUE THREAD

**Issue by Teqashi** [RocketChat/Rocket.Chat#15208]
Latelty, in PR https://github.com/RocketChat/Rocket.Chat/pull/12710/ you've added ability to set status. Right not you have to click on users name or go into DM with him to see it. Could you add ability to see it in `Direct Messages` group in sidebar, next to username?

eg
![dd](https://user-images.githubusercontent.com/37269807/63333023-f22b0000-c338-11e9-8ec8-6340db083714.png)

Would be awesome!

**Comment by reetp** [comment]
@rocket-cat label add duplicate

FRs go here https://github.com/RocketChat/feature-requests

Please have a through search before posting a new Issue:

https://github.com/RocketChat/feature-requests/issues/138
https://github.com/RocketChat/Rocket.Chat/issues/15091
https://github.com/RocketChat/Rocket.Chat/pull/15187

**Comment by reetp** [comment]
@rocket-cat close
