### ISSUE TITLE
DeadSimpleScreenSharing screen share is not working when initiated from Rocket.chat

### ISSUE THREAD

**Issue by ktnaane** [RocketChat/Rocket.Chat#15210]
I have issues with screen sharing using deadsimplechreensharing integration. 
The integration works fine, and creates a meeting. But when in a meeting, no one can see the shared screen, even if I share the screen, I don't become 'presenter', I remain a guest.  
However, when the meeting is created from the WebBrowser extenstion(not via rocketchat), attendees can see the shared screen. 

Rocket chat version 1.3.1. Running on a k8s cluster v1.14.0.

**Comment by reetp** [comment]
If you had waited for a response in open.rocket.chat you might have got an answer or told where to open and Issue, and here is not it.

Please close this and re-open in the Electron app repo.

**Comment by ktnaane** [comment]
I asked the same thing 2 weeks ago with no response. Hence the issue.
