### ISSUE TITLE
does not work specific symbols in url 

### ISSUE THREAD

**Issue by vdvas** [RocketChat/Rocket.Chat#15213]
### Description:

User can't follow url in conversation if it have specific symbols like "{".
If I send or receive message with url link, like http://example.com/asd{asd and then follow this link it's open in browser link http://example.com/asd and don't work.
when symbol "{" became in url after this not recognize like url part.
### Steps to reproduce:

1.  Go to 'chat' and choose user to conversation. 
2.  Tape  "http://example.com/asd{asd" and send message 
3.  See only "http://example.com/asd" like url and  blue letters and other part is black  letters.

### Expected behavior:

All url "http://example.com/asd{asd" must be blue letters and follow in browser as "http://example.com/asd{asd"
### Actual behavior:

Only part of url is recognized as a link.
### Server Setup Information:

- Version of Rocket.Chat Server:  1.2.3
- Operating System: Ubuntu 18.04
- Deployment Method:  snap
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.20

**Comment by wreiske** [comment]
Possibly related to https://github.com/gregjacobs/Autolinker.js/issues/268

Looks like the URL doesn't parse correctly here: http://greg-jacobs.com/Autolinker.js/examples/index.html

To be fair, { should be http://example.com/asd%7Basd if you're trying to share a link. If you use http://example.com/asd%7Basd it will work.
