### ISSUE TITLE
Highlighting breaks links

### ISSUE THREAD

**Issue by sybrenstuvel** [RocketChat/Rocket.Chat#15220]
### Description:

Highlighting of key words breaks linkifying URLs. For example, `https://cloud.blender.org/` turns into `https://`**cloud**.[blender.org/](https://blender.org/). The highlighted word is not made part of the URL.

### Steps to reproduce:

1. Go to My Account
2. Scroll to Highlights
3. Add 'cloud'
4. Type https://cloud.blender.org/ in a channel

### Expected behavior:

I expect the link to be pointing to https://cloud.blender.org/, the entire link to be clickable, and the word 'cloud' to be highlighted.

### Actual behavior:

The word 'cloud' is highlighted, but the link points to blender.org and the word 'cloud' is not part of the link text.

![image](https://user-images.githubusercontent.com/1092128/63413451-0420a780-c3fa-11e9-97c4-bc37f40b8e19.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Linux x64 4.4.0-141-generic
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.2.18

**Comment by mariaeduardacunha** [comment]
Tested in the latest version (3.0.0-develop) and this issue doesn't happen anymore. Also, links shouldn't be highlighted. If you happen to experience this issue again, please reopen this with updated details. Thanks!
