### ISSUE TITLE
Server icon no longer shows on server bar

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#15227]
### Disclaimer:
I am having to attach this disclaimer due to previous situations I'd rather avoid: The whole point of reporting on this is for it to hopefully be useful. If you are not one of the developers, please refrain from comments making the point that this is a development version, etc.: I am fully aware.

### Description:

The icon for the server that usually displays in the server bar in a multi-server client config no longer shows. Initials show instead.

### Steps to reproduce:

1. Update to latest develop docker image (a75e0f5).
2. Refresh client.
3. No icon will be shown.

### Expected behavior:
The regular icon (whether the RocketChat asset icon, or the custom icon) should be showing.

### Actual behavior:
No icon is shown and only the initials are shown. I even tried installing a brand new instance, and the result was the same. I am using the latest Electron client version (because this only started happening with the latest tag, I am not sure this is a client issue, and the other instances that I have not upgraded do not have that issue).

![image](https://user-images.githubusercontent.com/14616851/63445328-c45bbf00-c3fd-11e9-9f18-333db322cf30.png)

### Rocket.Chat
|                 Version | 2.0.0-develop                                             |
| ----------------------: | --------------------------------------------------------- |
|     Apps Engine Version | 1.5.2                                                     |
|      Database Migration | 154                                                       |
| Database Migration Date |                                                           |
|            Installed at | Wed Aug 21 2019 10:08:14 GMT-0500 (Central Daylight Time) |
|                  Uptime | 46 seconds                                                |
|           Deployment ID | 6or2LhcyaFaX25XC5                                         |
|                     PID | 1                                                         |
|       Running Instances | 1                                                         |
|                   OpLog | Enabled                                                   |

### Commit

|    Hash | a75e0f514535945a8a1dc57c10896c3170a8001a |
| ------: | ---------------------------------------- |
|    Date | Wed Aug 21 00:48:52 2019 -0300           |
|  Branch | develop                                  |
|     Tag | 1.3.0                                    |
|  Author | Pierre H. Lehnen                         |
| Subject | [NEW] Custom message popups (#15117)     |

**Comment by bkraul** [comment]
Something seems funky with the assets. I tried uploading assets to those new instances, and the assets do not load/show up in the assets admin page.

**Comment by bkraul** [comment]
It appears @sampaiodiego has fixed this on 63a57fb, as I can now see the asset server icon:

![image](https://user-images.githubusercontent.com/14616851/63526976-e7ea3c80-c4c5-11e9-954c-44e2699f9a9c.png)

Thanks guys!

**Comment by sampaiodiego** [comment]
:hugs:
