### ISSUE TITLE
FileReader function ignores orientation of images uploaded from mobile.

### ISSUE THREAD

**Issue by mitchrosu** [RocketChat/Rocket.Chat#1522]
For example, log in from your phone, in my case I'm using an iPhone, upload a picture you took in portrait and in the preview it will be rotated to display landscape. It also uploads in landscape view to the server, storing it with the wrong rotation permanently. I looked through the code and online and found this stackoverflow answer that seems to be the solution but I'm not entirely sure how to implement it: http://stackoverflow.com/questions/19463126/how-to-draw-photo-with-correct-orientation-in-canvas-after-capture-photo-by-usin

I'm pretty sure it involves the fileUpload.coffee file, something to do with readAsDataURL needing to be readFromBinaryFile to read the orientation properly.

I'll keep working on it but I'm still learning about meteor and coffeescript so if anyone has any ideas or manages to figure it out let me know!

**Comment by AdrianoCahete** [comment]
It's isn't a total RC's problem. I have this problem in my work:

When iOS save image as JPG, they put a info on image's header (or EXIF) who says the (wrong) orientation. Some softwares have internal fixes for that, but it's a iOS bug.

For more info:
http://stackoverflow.com/questions/10600613/ios-image-orientation-has-strange-behavior
http://stackoverflow.com/questions/22308921/fix-ios-picture-orientation-after-upload-php

**Comment by geekgonecrazy** [comment]
Looks like this is ios issue like mentioned above.  Closing

**Comment by mide** [comment]
This looks very much related to #5404. (I found this issue searching for my problem, and wanted to help the next searcher).
