### ISSUE TITLE
[BUG] Role obtained from oauth login are not updated at each connection

### ISSUE THREAD

**Issue by lmopi** [RocketChat/Rocket.Chat#15225]
### Description:

The roles of a logged in user from SSO are not updated if the user has a new idp role

### Steps to reproduce:

1. Configure a custom Oauth with `merge roles from SSO: true`
2. Sign in for the first time with user1
3. Add on the idp, a role to the user1
4. Reconnect with user1

### Expected behavior:

The roles of the user must be updated at each connection

### Actual behavior:

Only the roles of the first connection are taken into account
The groups are correctly seen in the debug logs but the user is not updated
The role already exists on rocketchet

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.12

**Comment by lmopi** [comment]
@Hudell ?

**Comment by col-panic** [comment]
Does this feature even work at all? I try this using a custom oauth for keycloak, and have added the client-specific role "Admin" and "livechat-agent" - I also have enabled "Merge roles from SSO" but on register they never get attributed to the user. I also tried removing the user and doing a full logoff on keycloak site, re-registering the user - nothing is merged.

![grafik](https://user-images.githubusercontent.com/1679857/64677396-c1da0b80-d477-11e9-8afe-4742bae63f5f.png)

**Comment by lmopi** [comment]
Yes the feature works for the first connection. Have you correctly filled the mapper tab in your rockechat client from Keycloak side ?

**Comment by col-panic** [comment]
@lmopi I'm sorry I don't understand what tab you mean?! In Rocket.Chat I have `Roles/Groups field name` set to `roles`. In keycloak, I have no mappers. Do I need to set one here?

![grafik](https://user-images.githubusercontent.com/1679857/64684293-218ae380-d485-11e9-8d27-712e62745a02.png)

**Comment by lmopi** [comment]
Yes, you need to push your keycloak roles to rocketchat with a mapper like bellow but with roles
![1](https://user-images.githubusercontent.com/53495096/64686540-189c1100-d489-11e9-871b-dd32edf3bcc4.png)

-------

![2](https://user-images.githubusercontent.com/53495096/64686551-1c2f9800-d489-11e9-9305-d74a8b50ec6c.png)

**Comment by col-panic** [comment]
Thanks for the help!! 

The solution you show is specific to LDAP stored users (I assume!).

The mapping from the role info within rocketchat itself does not seem to work. I created a non-ldap user in keycloak, and manually assigned it the client-specific roles, and even this is not being taken into account. 

Could you maybe verify, that your role mapping solution is working for a non-ldap-keycloak-provided user?

**Comment by col-panic** [comment]
I've managed to get it working for my basic scenario. I have added the required roles to the client, and the client-specific roles to the user. Mapping it to roles as shown in the images finally makes it working (for non-ldap).

![grafik](https://user-images.githubusercontent.com/1679857/64692052-75e98f80-d494-11e9-82de-5ba9d5524d75.png)

![grafik](https://user-images.githubusercontent.com/1679857/64692072-7f72f780-d494-11e9-95b2-1d1b9cfa48b6.png)

**Comment by DRLDoom** [comment]
Is there any chance that of role syncing, post initial user creation, is ever going to be implemented?

**Comment by col-panic** [comment]
I managed to realize this via SAML, where i provided a patch for role syncing.

**Comment by ShellyXueHan** [comment]
Also wondering if there are plans to implement role syncing in OAuth post initial user creation? Thx!

**Comment by pierre-lehnen-rc** [comment]
This seems to be working properly for custom OAuths, in what OAuth server are the roles not being synced?

**Comment by pierreozoux** [comment]
I just tried with RC 3.9.3, keycloack and group sync, it works on first login, but then I logout, I remove the group, login again, and it is not synced.

**Comment by reda-alaoui** [comment]
Tested on RC master with Keycloak, it works. 
Roles are correctly synced on each authentication.

**Comment by d3hof** [comment]
> Tested on RC master with Keycloak, it works.
> Roles are correctly synced on each authentication.

What version are you using?

**Comment by reda-alaoui** [comment]
The master at that time was 3.11 I guess.

**Comment by JustDevNull** [comment]
Any update abouth this? I'm currently using 3.13.0-rc.2 with Docker and the roles still are not updated.

**Comment by brendan-mccoy** [comment]
Any updates? Alternatively, can the SAML docs [here](https://github.com/RocketChat/docs/blob/master/guides/administrator-guides/settings/saml/keycloak.md) be updated to be a little less ambiguously written? Following that I just get constant "Invalid request" messages from Keycloak.

**Comment by arunodhayam1998** [comment]
Hi Guys... I want to integrate keycloak with rocket chat, Pls help me. Both applications are in docker and hosted with domain name...
Pls help with this
