### ISSUE TITLE
[Bug] Leave Room Button is not placed correctly 

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#15235]
### Description:

The leave room button is not placed correctly, please see screenshot below. It may only occur in some system languages, e.g. in German.

![image](https://user-images.githubusercontent.com/3596824/63590602-98327080-c5ac-11e9-962e-d5a6133a8805.png)

### Steps to reproduce:

1. Set system language to German
2. Open the info panel in any channel 
3. Experience the misplacement 

### Expected behavior:

Line break before leave button

### Actual behavior:

Leave button is not visible.

### Server Setup Information:

- Version of Rocket.Chat Server: current open.rocket.chat version (2.0.0-develop)

### Additional context

We already fixed this issue in our branch last year: https://github.com/assistify/Rocket.Chat/issues/479

**Comment by mrsimpson** [comment]
@ggazzo You as "the" front-ender: How should this be fixed? On our branch, we resolved it in the [html](https://github.com/assistify/Rocket.Chat/pull/498/files)

**Comment by legmartini** [comment]
I'm new in Github and i have a question. Where is the code of this problem?
olá, sou novo no Github e tenho uma dúvida. Aonde está o código que contém esse problema, para que eu possa tentar consertá-lo.
