### ISSUE TITLE
[BUG] invalid object in lastMessage property

### ISSUE THREAD

**Issue by arminfelder** [RocketChat/Rocket.Chat#15243]
affected Versions: 1.2.1
in sometimes happens, that the lastMessage property of a room only contains the reactions e.g.:
`
"lastMessage" : {
                "reactions" : {
                        ":thumbsup:" : {
                                "usernames" : [
                                        "demouser"
                                ]
                        }
                }
        }
`
which then will cause getRooms to fail, because there is no username property in this lastMessage object

**Comment by sschueller** [comment]
I am seeing this also in version 1.1.3. 

Calls to 
```curl -H "X-Auth-Token: mytoken" -H "X-User-Id: myuserid" -H "Content-type: application/json" "https://myhost/api/v1/rooms.get``` 
fail until a new message is posted in the "bad" room. What exactly causes it I can not determine. The last message block only contains the ```reactions```key and is missing everything else.

The last message I had in the "bad" room was ```Danke!``` with a ```:heart_eyes:``` reaction. But trying to reproduce the error fails.

related: https://github.com/RocketChat/Rocket.Chat.Android/issues/2433

**Comment by reetp** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> Before reporting a new issue
> 
> 1.  Read the Documentation carefully all the way through.
> **2.  Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.**

You are both quite out of date and your versions are not going to get fixed if they have an issue.

You need to test this on latest - currently v2.2.1

**Comment by reetp** [comment]
Also note regarding Android native:

https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first
