### ISSUE TITLE
Support multiple ECDH curves on older versions of Node

### ISSUE THREAD

**Issue by dlundgren** [RocketChat/Rocket.Chat#15245]
### Description:

Snaps & Docker images that are using Node < 10.0.0 cannot connect to servers with TLS or SSL certs that use ECDH curves that are not `prime256v1`. With #11016 being obsolete, I'm willing to step in and make a PR to get this support added, but I need some direction on the best place to add the tls/semver checks on the server side. My initial inclination is to add it to app/settings/server, but I'm not familiar enough with how the project is laid out if there is a better location to code similar to #11016 in.

The DEFAULT_ECDH_CURVE has been set to `auto` in Node 10 and higher, so we'd have to target this towards nodejs < 10.0.0.

### Steps to reproduce:

Launch an existing Docker or snapd image, attempt to use LDAP that has a non `prime256v1` certificate issued to it.

### Expected behavior:

The system should be able to connect.

### Actual behavior:

I receive `ECONNRESET`

### Server Setup Information:

- Version of Rocket.Chat Server:  1.3.2
- Operating System: Ubuntu
- Deployment Method: snapd
- Number of Running Instances: 1
- NodeJS Version: 8.11.3

**Comment by sampaiodiego** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/15365
