### ISSUE TITLE
[sandstorm] Cull administrator options

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1527]
Not all administrator options should be exposed to a sandstorm admin user.

For example, LDAP or oauth settings do not make sense.
##

**Comment by marceloschmidt** [comment]
LDAP settings can be removed by removing the LDAP package. 
Is there some way to remove packages in sandstorm? 
Maybe the other oauth settings should also be triggered by custom packages?

**Comment by Sing-Li** [comment]
Actually, it is probably OK to leave the package code in.  The issue is centered around conditionally showing certain settings in the UI  (when it is detected to be running under Sandstorm)

Please see this PR for an example --  https://github.com/RocketChat/Rocket.Chat/pull/1473/files

The UI is rendered depending on whether the code is running Sandstorm.  And so the admin UI should show only the settings that are meaningful to Sandstorm users.

**Comment by engelgabriel** [comment]
Depends on https://github.com/RocketChat/Rocket.Chat/issues/2250

**Comment by sampaiodiego** [comment]
with #2361 this is now possible just have to `block` or `hidden` some settings when in sandstorm environment

**Comment by engelgabriel** [comment]
We just need a full list of settings to block :)

**Comment by asthomasdk** [comment]
I have been trying to use the hidden settings - but they do not seem to have any effect. 

Trying to browse through the source code, I can see how the block settings are translated into `isDisabled` - which is used in a few places in the UI. But I don't see anything using the hidden settings. 

Unless I am missing something...

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat.Docs/issues/163

**Comment by marceloschmidt** [comment]
Sandstorm is not supported anymore.
