### ISSUE TITLE
Federation registration Not Found

### ISSUE THREAD

**Issue by hugglesfox** [RocketChat/Rocket.Chat#15275]
When accessing the URL emailed to `webmaster@mydomain.com` to confirm setup, it just returns `Not Found`. I tried various times and constantly got the same error.

**Comment by alansikora** [comment]
@hugglesfox can you please send me e-mail, so I can check the link? alan.sikora@rocket.chat

**Comment by hugglesfox** [comment]
Hey sorry I no longer run the rocket chat sever therefore will close this PR. Thanks for getting back to me though, keep up the good work!
