### ISSUE TITLE
server upgrade

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat#15286]
Hi I've installed the server application with the docker compose from here:  https://rocket.chat/docs/installation/docker-containers/docker-compose/

but this installes only the 1.2.3 version not the current one. how can I fix this?

**Comment by holzfelix** [comment]
any help?

**Comment by reetp** [comment]
@rocket-cat close

Please note that this isn't a help forum.

>Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
>If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support
>If you are experiencing a bug please search our issues to be sure it is not already present: https://github.com/RocketChat/Rocket.Chat/issues


https://forums.rocket.chat
https://open.rocket.chat #support

Answer is in the documentation - use a specific tag as latest is not always reliable.

https://rocket.chat/docs/installation/docker-containers/available-images/
