### ISSUE TITLE
Sending a message via REST API to private groups

### ISSUE THREAD

**Issue by ukastens** [RocketChat/Rocket.Chat#1528]
It would be great if one could send messages via API to private groups too.

**Comment by engelgabriel** [comment]
Will be done via https://github.com/RocketChat/Rocket.Chat/issues/1501

**Comment by bidhan-a** [comment]
Hello,

It doesn't seem like it's possible to post messages to private groups via the REST API. 

I can post to public channels using the following API -  https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/ . But I when I try to post to a private group, it returns an `[invalid-channel]` error. 

Is there a separate route that allows posting messages to private groups?

Thanks
