### ISSUE TITLE
Better to Move the localizations to transifex.com

### ISSUE THREAD

**Issue by Raddah** [RocketChat/Rocket.Chat#1529]
Dear all, 

- I suggest to move the localizations to http://www.transifex.com it has more members and more professional and free 

Regards,

**Comment by marceloschmidt** [comment]
We've tried using them before and we prefer Lingohub for their Github integration...

**Comment by engelgabriel** [comment]
yes, github integration made our work a lot easier.

**Comment by Raddah** [comment]
they have also integration with Github 
### have you try it ?
- http://docs.transifex.com/integrations/github/
- https://github.com/transifex/txgh
- https://www.transifex.com/blog/2013/github-transifex-integration/

**Comment by engelgabriel** [comment]
I looked at the first, and the others look very cumbersome... Lingohub works out of the box. Do you have any complains about Lingohub? Have you used it?I know some language have a gender specification not supported that I am not sure is supported by LIngohub... but maybe I just didn't  look for it enough.
