### ISSUE TITLE
Images not being displayed

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#15291]
### Description:

My installation is currently having issues with displaying images. When getting the image I get a 403 (forbidden) error, see image below.

The issue only occurs sporadically, it occurs around 80% of the time, while the other times I actually see the images. All my users are having the issue as well.

I'm using S3 for storage and the error persists even if I allow public access, sometimes a blurry preview of the image is shown and sometimes nothing at all.

Any assistance would be much appreciated!

### Steps to reproduce:

1. Have a user upload an image in either a channel och private message.
2. Try to view the image with the receiving user.
3. Receive error.

### Expected behavior:

The images should be downloaded/displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Ubuntu
- Deployment Method: Docker-compose
- Number of Running Instances: 1
- MongoDB Version: 3.4
- CDN: Cloudflare

### Relevant logs:

Screenshot of the console error: https://imgur.com/a/xZvuv4v

**Comment by cchbr** [comment]
I have realised that this is most likely due to the CDN I'm using, Cloudflare.

How does Rocket chat handle this for S3, why do I get a 403 error when requesting images just because I use a CDN? I have not applied the CDN to Rocket chat or the S3 bucket itself, but simply to the domain name.

Interestingly I only receive these errors for uploaded images, not for avatars, and both are hosted in the same bucket.

**Comment by sylvaint** [comment]
I have the exact same issue using Cloudflare...

**Comment by cchbr** [comment]
Have you configured anything under the CDN Domain setting in the Rocket chat setting for Amazon S3?

**Comment by sylvaint** [comment]
No I did not.  I fixed the issue by bypassing both caching and security for that sub domain on Cloudflare.  Security would prevent file upload and caching created the sporadic image viewing 403 error.

**Comment by cchbr** [comment]
When so bypass caching on Cloudflare I can’t reach my website for some reason.

**Comment by sylvaint** [comment]
Did you bypass it in a page rule ?

**Comment by cchbr** [comment]
Yes it’s in a page rule, I have tried with both the sub domain that the chat is hosted on and the whole domain. 

Like this: *domain.com/*

The same thing happens if I activate development mode which should disable all caching. I also have a dedicated server for the RC instance, the DB is on that server as well.
