### ISSUE TITLE
Ldap Sync whiout email

### ISSUE THREAD

**Issue by lucassmacedo** [RocketChat/Rocket.Chat#15293]
Hello. On my LDAP server the users has no email. I Need config rocket chat to sync users only with username and ignore email. How do this?

**Comment by pierre-lehnen-rc** [comment]
You can use the "Default Domain" LDAP setting under "Sync / Import".

**Comment by jtorrex** [comment]
> Hello. On my LDAP server the users has no email. I Need config rocket chat to sync users only with username and ignore email. How do this?

Hi @lucassmacedo,

You should to configure only the attributes that are interesting for you in the LDAP section: (Administration > LDAP > Sync/Import > User Data Field Map).

In your case, you only need to put the cn attribute to save only the name for the user in RocketChat:

![Sync-users-rocketchat](https://user-images.githubusercontent.com/53188139/64952954-f0922080-d881-11e9-891e-9cb3e7cde34c.png)

In case that you don't wan't to sync anything extra, you can leave it blank.

Regards!
