### ISSUE TITLE
Websockets not always connecting right away in Chrome.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#15290]
### Description:

Websockets in chrome do not always connect right away and falls back to xhr, once a websocket connection is finally connected it switches to websocket. This seems to happen more often when you have a lot of private messages open with other users. In chrome this error appears. "failed: WebSocket is closed before the connection is established." This only happens in chrome and not in any other browser that I have been able to test.

### Steps to reproduce:

1. Login into Rocket Chat
2. Start a private conversation with a lot of users. 100 or more.
3. View browser debug console in Chrome. Watch as websockets have a hard time connecting and fall back to xhr.

### Expected behavior:

Websockets to work regardless of how many resources the chat has to load.

### Actual behavior:

Websockets fail and finally connect seconds or minutes later.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.2
- Operating System: Centos
- Deployment Method: tar
- Number of Running Instances: 6
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.14

**Comment by serviceman** [comment]
This issue seemed to have resolved it's self when I upgraded to 2.0.0-rc.2. I have a feeling there was an error in one of my config files for one of my rocket chat instances that caused this. I'll reopen if the issue comes back up.

**Comment by codeneno** [comment]
NO!
It is still here in 3.9.4 version

**Comment by codeneno** [comment]
NO!
It is still here in 3.9.4 version
@ankar84

**Comment by ankar84** [comment]
Yeap, issue is still here
https://github.com/RocketChat/Rocket.Chat/issues/17559

**Comment by codeneno** [comment]
@ankar84  My email qsmy_qin@163.com,may I have your email sir?

How many users online do you have now

**Comment by codeneno** [comment]
@ankar84  My email qsmy_qin@163.com,may I have your email sir?

How many users online do you have now

**Comment by ankar84** [comment]
> How many users online do you have now

![image](https://user-images.githubusercontent.com/4023037/104152308-3caa9200-53f0-11eb-9b64-88070651aac2.png)

**Comment by codeneno** [comment]
@ankar84 Hi sir,Do you still have to restart RC  manually every week?

**Comment by ankar84** [comment]
> @ankar84 Hi sir,Do you still have to restart RC manually every week?

Yeap, now twice a week - Wednesday and Sunday

**Comment by codeneno** [comment]
@ankar84 we have 4K users,but we come across xhr flood sometimes,and RC will stop work (high cpu)  still we restart all instances.

**Comment by codeneno** [comment]
@ankar84 you have only 2k online users  at same time ,so you may  think you have resolved this problem.but it is waiting for you when you have more users online users.
