### ISSUE TITLE
Push gateway error

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#15296]
than desktop client go away on idle timeout and some bady post message - in logs wehave this error

> I20190903-18:48:41.317(0) server.js:212 System ➔ error Error sending push to gateway (2 try) -> { Error: failed [500] {"code":109,"error":"internal error trying to send apn notification","errorId":"cdedf4a4-7eff-4efd-9118-6bf7983de265","status":500}     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   response:     { statusCode: 500,      content: '{"code":109,"error":"internal error trying to send apn notification","errorId":"cdedf4a4-7eff-4efd-9118-6bf7983de265","status":500}',      headers:        { 'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With',         'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',         'access-control-allow-origin': '*',         'access-control-expose-headers': 'Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by',         'cache-control': 'private, no-cache, no-store, must-revalidate',         'content-length': '131',         'content-type': 'application/json; charset=utf-8',         date: 'Tue, 03 Sep 2019 18:48:41 GMT',         expires: '-1',         pragma: 'no-cache',         'x-powered-by': 'Rocket Fuel and Rocketeers',         connection: 'close' },      data:        { code: 109,         error: 'internal error trying to send apn notification',         errorId: 'cdedf4a4-7eff-4efd-9118-6bf7983de265',         status: 500 } } } 
we use a https://gateway.rocket.chat
no push on mobile are worked. after restart rocketchat push return to normal work but in week or two it will again break..
may be we can use different gateway if rocketchat gateway permanentmly bugged?

**Comment by justinGML** [comment]
I'm seeing the same errors in our logs at the moment.  Maybe it's an issue with RocketChat's gateway?

**Comment by GrayZhang** [comment]
we have the same errors,  someone has  resolvee  it ?

**Comment by maxk11** [comment]
We're having the same problems, on three different servers. Seems to be only an iOS issue.

**Comment by Shaverdoff** [comment]
Not only ios. My colleges on andro tell me that seems bug appears

--
Gerasim Shaverdov | Deputy CTO | Altarix
Mobile: +7 937 070 66 84<tel:+7%20937%20070%2066%2084> | Skype/email: gerasim@altarix.ru<mailto:gerasim@altarix.ru>
Lenina av.25, Samara, Russia, 443068

4 сент. 2019 г., в 12:15, maxk11 <notifications@github.com<mailto:notifications@github.com>> написал(а):


We're having the same problems, on three different servers. Seems to be only an iOS issue.

**Comment by eeldwin** [comment]
this happened with me as well.

**Comment by Shaverdoff** [comment]
sometimes mobile-push send me a very old message.... and after that push original may crash or may work for a while

**Comment by dusatvoj** [comment]
Also affected
`I20190904-09:59:17.308(2) server.js:212 System ➔ error Error sending push to gateway (5 try) -> { Error: failed [500] {"code":109,"error":"internal error trying to send apn notification","errorId":"66e53978-72c6-4323-bca0-a1d0640d738a","status":500}     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   response:     { statusCode: 500,      content: '{"code":109,"error":"internal error trying to send apn notification","errorId":"66e53978-72c6-4323-bca0-a1d0640d738a","status":500}',      headers:        { 'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With',         'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',         'access-control-allow-origin': '*',         'access-control-expose-headers': 'Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by',         'cache-control': 'private, no-cache, no-store, must-revalidate',         'content-length': '131',         'content-type': 'application/json; charset=utf-8',         date: 'Wed, 04 Sep 2019 07:59:17 GMT',         expires: '-1',         pragma: 'no-cache',         'x-powered-by': 'Rocket Fuel and Rocketeers',         connection: 'close' },      data:        { code: 109,         error: 'internal error trying to send apn notification',         errorId: '66e53978-72c6-4323-bca0-a1d0640d738a',         status: 500 } } } `

**Comment by Shaverdoff** [comment]
we do no any investigations, and push notify gateway now worked... maybe support make some tuning/restarting the gate?

**Comment by babrums** [comment]
Same issue here, but with code  401

```
 server.js:212 System ➔ error Error sending push to gateway (4 try) -> { Error: failed [401] {"error":"unauthorized"}
     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
     at Request._callback (packages/http.js:140:24)
     at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
     at emitTwo (events.js:126:13)
     at Request.emit (events.js:214:7)
     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
     at emitOne (events.js:116:13)
     at Request.emit (events.js:211:7)
     at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
     at Object.onceWrapper (events.js:313:30)
     at emitNone (events.js:111:20)
     at IncomingMessage.emit (events.js:208:7)
     at endReadableNT (_stream_readable.js:1064:12)
     at _combinedTickCallback (internal/process/next_tick.js:139:11)
     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
   response: 
    { statusCode: 401,
      content: '{"error":"unauthorized"}',
      headers: 
       { 'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With',
         'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',
         'access-control-allow-origin': '*',
         'access-control-expose-headers': 'Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by',
         'cache-control': 'private, no-cache, no-store, must-revalidate',
         'content-length': '24',
         'content-type': 'application/json; charset=utf-8',
         date: 'Fri, 11 Oct 2019 12:39:03 GMT',
         expires: '-1',
         pragma: 'no-cache',
         'x-powered-by': 'Rocket Fuel and Rocketeers',
         connection: 'close' },
      data: { error: 'unauthorized' } } }

```

**Comment by sampaiodiego** [comment]
this looks to be a momentarily issue.. I'll close this issue for now.. if you guys still have problems please let me know.

**Comment by starryskadi** [comment]
@sampaiodiego Still got this issue. 
server.js:204 System ➔ error Error sending push to gateway (5 try) -> Error: failed [400] {"code":108,"error":"bad request sent to apn","requestId":"5d65403d-4499-48ae-b825-3025a6ba1ce0","status":400}
    at Object.exports.makeErrorByStatus (packages/http.js:176:10)
    at Request._callback (packages/http.js:140:24)
    at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  response: {
    statusCode: 400,
    content: '{"code":108,"error":"bad request sent to apn","requestId":"5d65403d-4499-48ae-b825-3025a6ba1ce0","status":400}\n',
    headers: {
      'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With',
      'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by',
      'cache-control': 'private, no-cache, no-store, must-revalidate',
      'content-length': '111',
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 13 Jun 2020 06:05:46 GMT',
      expires: '-1',
      pragma: 'no-cache',
      'x-powered-by': 'Rocket Fuel and Rocketeers',
      connection: 'close'
    },
    data: {
      code: 108,
      error: 'bad request sent to apn',
      requestId: '5d65403d-4499-48ae-b825-3025a6ba1ce0',
      status: 400
    }
  }
}

**Comment by mahdigholipoor** [comment]
i have this log in own server and don't receive the notification on mobile 

`I20201211-13:31:23.042(3.5) server.js:204 Push ➔ error Error sending push to gateway (2 try) -> Error: failed [502] Bad Gateway     at Object.exports.makeErrorByStatus (packages/http.js:177:10)     at Request._callback (packages/http.js:141:24)     at Request.self.callback (/snap/rocketchat-server/1446/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:315:20)     at Request.EventEmitter.emit (domain.js:483:12)     at Request.<anonymous> (/snap/rocketchat-server/1446/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:315:20)     at Request.EventEmitter.emit (domain.js:483:12)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1446/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:421:28)     at IncomingMessage.emit (events.js:327:22)     at IncomingMessage.EventEmitter.emit (domain.js:483:12)     at endReadableNT (_stream_readable.js:1220:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21) {   response: {     statusCode: 502,     content: 'Bad Gateway',     headers: {       date: 'Fri, 11 Dec 2020 10:01:22 GMT',       'content-length': '11',       'content-type': 'text/plain; charset=utf-8',       connection: 'close'     },     data: null   } } 
I20201211-13:31:34.880(3.5) server.js:204 Push ➔ error Error sending push to gateway (2 try) -> Error: ESOCKETTIMEDOUT     at ClientRequest.<anonymous> (/snap/rocketchat-server/1446/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:816:19)     at Object.onceWrapper (events.js:421:28)     at ClientRequest.emit (events.js:315:20)     at ClientRequest.EventEmitter.emit (domain.js:483:12)     at TLSSocket.emitRequestTimeout (_http_client.js:709:9)     at Object.onceWrapper (events.js:421:28)     at TLSSocket.emit (events.js:327:22)     at TLSSocket.EventEmitter.emit (domain.js:483:12)     at TLSSocket.Socket._onTimeout (net.js:482:8)     at listOnTimeout (internal/timers.js:549:17)     at processTimers (internal/timers.js:492:7) {   code: 'ESOCKETTIMEDOUT',   connect: false } `
