### ISSUE TITLE
user unable to change username

### ISSUE THREAD

**Issue by sylvaint** [RocketChat/Rocket.Chat#15308]
### Description:
User is unable to change username.
Popup error:  "Your rocket chat administrator has disabled the changing of status messages"
- Account Allow username change is set to true
- Permissions Manage status is set to true
Not using LDAP

### Steps to reproduce:

1. Go to my account
2. select profile
3. change username and press save

### Expected behavior:
User should be allowed to change username

### Actual behavior:
Getting error message: "Your rocket chat administrator has disabled the changing of status messages"

### Server Setup Information:
- Rocket chat 1.3.2
- Operating System: CENTOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 4.0.12

**Comment by MartinSchoeler** [comment]
@sylvaint We are not able to reproduce this in v 2.0.0 Can you give us more info on this issue?
1. What is the browser that you are using?
2. Is the setting "Allow Custom Status Message" set to false?
3. Can you post a screenshot of your account page when that error happens?

Thanks!

**Comment by sylvaint** [comment]
@MartinSchoeler I can not reproduce with v 2.0.0 either.
Thanks !
