### ISSUE TITLE
`chat.syncMessages` returning empty `deleted` object

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat#15309]
This request should have returned a record inside `deleted` object:
```
# Request

### Endpoint

`GET` http://localhost:3000/api/v1/chat.syncMessages?roomId=Waur2rrA8kfcJP2Nm&lastUpdate=2019-09-05T19%3A48%3A58.840Z

### Duration

`50` ms

### Headers

key          | value                                      
------------ | -------------------------------------------
content-type | application/json                           
x-auth-token | SMs9kI219tEcrki-udJGvFSeQGBHczufXGyWTZI8GSx
x-user-id    | Txfdr6rieenNk5SGY                          

# Response

### Status Code

`200`

### Data Received

```json
{
  "result": {
    "updated": [],
    "deleted": []
  },
  "success": true
}
```

### Headers

key                          | value                                                                  
---------------------------- | -----------------------------------------------------------------------
x-ratelimit-limit            | 10                                                                     
x-instance-id                | LcdthkYLuHKEkBHQb                                                      
Content-Encoding             | gzip                                                                   
Pragma                       | no-cache                                                               
Cache-Control                | no-store                                                               
x-ratelimit-reset            | 1567713005850                                                          
Access-Control-Allow-Origin  | *                                                                      
Transfer-Encoding            | Identity                                                               
Content-Type                 | application/json                                                       
access-control-allow-headers | Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token
Date                         | Thu, 05 Sep 2019 19:49:05 GMT                                          
x-ratelimit-remaining        | 9                                                                      
Vary                         | Accept-Encoding                                                        
Connection                   | keep-alive                                                             

```

Rocket.Chat server version: 2.0.0-develop

**Comment by MarcosSpessatto** [comment]
Closing this issue, as talked to @diegolmello, if the setting `Message_KeepHistory` is active, then the behavior when a message is deleted is set a property: `_hidden: true`. And then the message will not return in `deleted` array.
