### ISSUE TITLE
Enabling selfsigned HTTPS on Caddy for RocketChat

### ISSUE THREAD

**Issue by tcustan** [RocketChat/Rocket.Chat#15304]
I installed Rocket.Chat on Ubuntu 19.04 using snaps according to the official documents.

I need to enable HTTPS in order to use web hooks and API integration for other systems.

Since this server is in intranet I would like to use selfsigned SSL.

Snaps installation comes with Caddy, and Caddy has support for built-in selfsigned ssl mode only for 5 days.

I created a selfsigned PEM file but I cannot use it in caddy config file. It simply won't run.

Browser gets no response from server, for caddy's own cert or HTTP it works fine.

How can I configure my own selfsigned SSL for Caddy in order for Rocket.Chat to use?

Following caddyfile works with 5 days of selfsigned ssl:

https://rocket.local
tls self_signed
proxy / localhost:3000 {
  websocket
  transparent
}
Change to following and it does not respond:

https://rocket.local
tls ../cert.pem ../key.pem
proxy / localhost:3000 {
  websocket
  transparent
}

**Comment by reetp** [comment]
@rocket-cat close.

There is no evidence of a bug here.

Note Rocket usually recommends using LTS for stability usually - so 18.04 currently.

Please see here for how to get support:

https://rocket.chat/docs/getting-support/

https://forums.rocket.chat/

https://open.rocket.chat #dev
