### ISSUE TITLE
Posting 5,000 emojis will crash the tab and prevent the tab from being reopened

### ISSUE THREAD

**Issue by granttoday** [RocketChat/Rocket.Chat#15300]
### Description:

If someone posts 5,000 emojis, it will crash the tab and prevent anyone from opening the page again, until deleted.

### Steps to reproduce:

1. post 5,000 emojis
2. reload

### Expected behavior:

not to crash

### Actual behavior:

crash

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: v8.16.0
- MongoDB Version: 3.4.21

### Relevant logs:

unable to get logs, as devtools will disconnect

**Comment by henryfok** [comment]
This might be related to your server's "Maximum Allowed Characters Per Message" setting. It is set to 5000 by default.
Administration -> Message

**Comment by granttoday** [comment]
yes, it's in my settings, but rocket.chat will attempt to render characters off the screen. In large messages, may crash low-end computers.

**Comment by tholu** [comment]
Is the "Maximum Allowed Characters Per Message" setting enforced when posting via Webhook?

**Comment by tholu** [comment]
This is not stale, please keep it open.
