### ISSUE TITLE
Google-Tag-Manager-ID setting has no effect

### ISSUE THREAD

**Issue by robbsie** [RocketChat/Rocket.Chat#15305]
### Description:

The setting has no effect. Imho it should add Googles JS include `www.googletagmanager.com/ns.html?id=GTM-XXX` to the chat and/or livechat. We need this for tracking our livechats as conversion goals.

Also there seems to be no documentation of  this setting, so it is unclear where the Google JS will be injected.

### Steps to reproduce:

1.  open admin backend
2.  go to settings
3.  add custom Google-Tag-Manager-ID & save settings

### Expected behavior:

JS include from google www.googletagmanager.com/ns.html?id=GTM-XXX should appear in the chat sourcecode.

### Actual behavior:

Nowhere in the chats code oder JS the Google Tag Manager JS can be found.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System:  CentOS 7
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v8.16.1
- MongoDB Version: v3.6.14

**Comment by reetp** [comment]
Bit of a wide assumption that everyone wants Google spyware built in everywhere. I don't thanks. Neither do my users.

Use search. You will find there is a difference between Rocket and Livechat

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+google+tag

eg
https://github.com/RocketChat/Rocket.Chat/issues/5955#issuecomment-279731402

**Comment by robbsie** [comment]
> Bit of a wide assumption that everyone wants Google spyware built in everywhere. I don't thanks.

With cookie consent i see no problems here.

The bug exists, so it should be fixed or the setting has to be removed.

**Comment by reetp** [comment]
> > Bit of a wide assumption that everyone wants Google spyware built in everywhere. I don't thanks.
> 
> With cookie consent i see no problems here.
> 

You might not. I do. I don't want their spyware anywhere near thanks. So, if anything if included it should toggle on and off. Off means no JS, period.

> The bug exists, so it should be fixed or the setting has to be removed.

No, you are conflating issues.

You have a link on how to do it for Rocket itself as above. You can add the code yourself as designed and per the link. So there is no bug there.

Livechat would be a feature request (because it isn't broken, just not working how you want it)

https://github.com/RocketChat/feature-requests
https://github.com/RocketChat/Rocket.Chat.Livechat/issues

"Add custom JS" or similar.

**Comment by robbsie** [comment]
I know how to do it manually with "Custom Scripts", but why is there a setting in RocketChat for the Google tag Manager ID?

![Bildschirmfoto 2019-09-05 um 16 46 26](https://user-images.githubusercontent.com/1869450/64352686-c2e4e600-cffc-11e9-9e2d-4d1b7c9a3412.png)


So for what exists the "Google-Tag-Manager-ID" setting and what does it do? 
Still unclear for me and your comments are not helpful at all.

**Comment by reetp** [comment]
> Still unclear for me and your comments are not helpful at all.

Sorry - this is a Issue tracker, not a help forum. For help you should visit the forums or open.rocket.chat

If you do a search of the code then the $var is in:

`app/ui-master/client/main.js`

If you add your code and enable it, which requires a restart, if you then use something like Chrome/Inspect then you will see something like this (you cannot see it in view source):

`<script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-MLJ76N"></script>`

And I just tested it and it appears when enabled.

What it does and how you then use it is up to you.

Note the differences with Google Analytics vs Google Tag, and Rocket vs Livechat.

(note until you opened this I had **absolutely no idea** about it - this is just being bothered to do a bit of research)

I don't believe there is an Issue here - possibly add some documentation, and a feature request for custom scripts in Livechat.
