### ISSUE TITLE
post-readonly permissions not enforced server-side

### ISSUE THREAD

**Issue by humancatfood** [RocketChat/Rocket.Chat#15303]
### Description:

In a read-only room, unless you have a role that has the permission to post messages in that room, the message input is replaced by a message 'This room is read only'.

However this is not enforced by the backend. I can still post to read-only rooms via the rest-api.

### Steps to reproduce:

1. Log in as `User A`, create a new read-only channel.
2. Log in as `User B` and enter that channel. Note how there's no message input available.
3. Post a message via `v1/chat.postMessage` to the channel. Note how the message is added to the conversation nonetheless.

The fastest way to test this is like this:
1. refresh the page with the network tab open
2. select an authenticated xhr request and copy it as fetch
3. paste it back into the console
4. set 
  - url to `v1/chat.postMessage`
  - method to `POST`
  - body to `{\"roomId\":\"<the read-only channel's id>\",\"text\":\"Some Text\"}"`
5. send it off

### Expected behavior:

I expect such a request to fail with a 403 error or at least a 400

### Actual behavior:

The message is added to the conversation, posing a security leak

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Darwin 16.7.0
- Deployment Method: cloned https://github.com/RocketChat/Rocket.Chat.git and run locally
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.2

### Additional context

<img width="1678" alt="Screen Shot 2019-09-05 at 11 16 14" src="https://user-images.githubusercontent.com/537807/64333682-fdd02500-cfce-11e9-9e7b-875c58bcf3a0.png">

### Relevant logs:

Nothing specific is getting logged

**Comment by reetp** [comment]
https://rocketchat.github.io/docs/contributing/reporting-issues/

>2. Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

So at the very least 1.3.2

Please test and revert with your commenst.
