### ISSUE TITLE
Changing Assets for livechat

### ISSUE THREAD

**Issue by Sx3** [RocketChat/Rocket.Chat#15301]
### Description:

Is there any option to change the icon of the livechat popup also the Powered by Logo on the chatbox ?
### Actual behavior:

![image](https://user-images.githubusercontent.com/3599933/64273905-e73eb500-cf5f-11e9-93d6-321b419f50df.png)
![image](https://user-images.githubusercontent.com/3599933/64273953-fd4c7580-cf5f-11e9-89bc-64183c1abe9e.png)

- Version of Rocket.Chat Server: 1.2.3
- Operating System: Ubuntu 18.04
- Deployment Method: snap

**Comment by renatobecker** [comment]
We have plans to provide more settings on Livechat Appearance, it's in our mid-term roadmap already.
I'm closing this issue, I suggest to move this kind of question to our forum, okay?
Thanks.
