### ISSUE TITLE
How to overwrite Chatpal settings?

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#15314]
### Description:

Normally, I can [overwrite settings by defining environment variables](https://rocket.chat/docs/administrator-guides/settings-via-env-vars/).

This doesn't work for Chatpal settings, because they use dots instead of underlines, like in `Search.chatpalProvider.HTTP_Headers` and environment variable names (at least on Linux or OSX) doesn't allow dots.

I recommend to change the settings to use underscore characters instead.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Linux

**Comment by geekgonecrazy** [comment]
https://unix.stackexchange.com/a/93533 unfortunately looks like the workaround might be something like:
env "Search.chatpalProvider.HTTP_Headers=value" bash

**Comment by jschirrmacher** [comment]
Thanks for your reply and the hint of a workaround!
While this actually might help, I would propose to change the setting name nevertheless to make this workaround obsolete.
