### ISSUE TITLE
Usernames not returned from *.info endpoints

### ISSUE THREAD

**Issue by humancatfood** [RocketChat/Rocket.Chat#15318]
### Description:

When calling any of the `/groups.info`, `/channels.info` or `/rooms.info` endpoints the usernames are not included.

### Steps to reproduce:

1. Make a request to `v1/rooms.info?roomName=<A Valid Room Name>`
2. Check the response  in the network tab. Note how there is no entry `usernames`

### Expected behaviour:

I expect there to be an array with usernames as detailed in [the Schema Definition](https://rocket.chat/docs/developer-guides/schema-definition/)

### Actual behaviour:

There isn't..

### Server Setup Information:

Version of Rocket.Chat Server: 1.2.1
Operating System: Darwin 16.7.0
Deployment Method: cloned https://github.com/RocketChat/Rocket.Chat.git and run locally
Number of Running Instances: 1
DB Replicaset Oplog: enabled
NodeJS Version: v8.11.4
MongoDB Version: 4.0.2

**Comment by reetp** [comment]
@rocket-cat close

https://rocketchat.github.io/docs/contributing/reporting-issues/

>Before reporting a new issue
>`Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.`

Try on at least 1.3.2

However, having done a quick test myself it seems that the .list call does not return the users and you need to use .members to do that. Something probably changed at some stage that hasn't been documented.

You may want to read these:

https://rocket.chat/docs/developer-guides/rest-api/groups/info/
https://rocket.chat/docs/developer-guides/rest-api/groups/list/
https://rocket.chat/docs/developer-guides/rest-api/groups/members/

https://rocket.chat/docs/developer-guides/rest-api/channels/info/
https://rocket.chat/docs/developer-guides/rest-api/channels/list/
https://rocket.chat/docs/developer-guides/rest-api/channels/members/

https://rocket.chat/docs/developer-guides/rest-api/rooms/info/
https://rocket.chat/docs/developer-guides/rest-api/rooms/get/

I don't think that Rocket is broken.

It just some of the documentation updating and you are better creating either a Issue here https://github.com/RocketChat/docs or better still a pull request against each page that is wrong.
