### ISSUE TITLE
Announcement not showing on 2.0.0 rc2

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#15324]
### Description:

Announcements are not showing on 2.0.0 rc2. I upgraded from 1.3.2 and announcements stopped showing even if I deleted them and recreated them.

### Steps to reproduce:

1. Create announcement
2. View room and announcements don't show.
3. Announcements still don't show even after refreshing the page or leaving and reentering the room.

### Expected behavior:

Announcements to show as a bar across the top as they do in 1.3.2.

### Actual behavior:

Announcements don't show even if they previously worked in 1.3.2.

### Server Setup Information:

Version of Rocket.Chat Server:2.0.0 rc2
Operating System: Centos
Deployment Method: tar
Number of Running Instances: 6
DB Replicaset Oplog: yes
NodeJS Version: v8.11.4
MongoDB Version: 3.6.14

**Comment by jwhiteman36** [comment]
I'm seeing this same issue in the latest version 2.0.0. We just updated from 1.3.2 last night.

**Comment by Gummikavalier** [comment]
Confirming. No announcement bar with 2.0.0. In 1.3.2 a page refresh was required to get it visible, but now that does not help either.

**Comment by serviceman** [comment]
I switched over to the latest 2.0.0 release and I am still experiencing this same issue.

**Comment by jwhiteman36** [comment]
I updated our test server to the 2.1.0 release, and announcements still are not displaying in channels where they are set.

**Comment by Wirone** [comment]
Confirmed on 2.1.0 - updated today and announcements are not displayed.

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/15615
