### ISSUE TITLE
Docker compose from doc cannot work

### ISSUE THREAD

**Issue by DerpDarako** [RocketChat/Rocket.Chat#15323]
Hello,

I installed rocket chat today but it's not possible to make it work from your docker-compose.

You use the lastest version of mongo in your docker compose. You have 2 choices:
- Fix the mongo version 3.x.x
- Change your command

Since mongo 4 mmapv1 and --smallfiles are not supported anymore.
BR

**Comment by gillbates** [comment]
we are stopped at the first screen of wizzard.
Nothing happens after clicked continue in Admin info.

**Comment by reetp** [comment]
> I installed rocket chat today but it's not possible to make it work from your docker-compose.
> 

Which document did you follow?

**Comment by reetp** [comment]
> we are stopped at the first screen of wizzard.
> Nothing happens after clicked continue in Admin info.

Don't leap onto a Issue unless it is completely the same as your situation.

Fill out a proper bug template if you have an error:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Please ask for support:
https://rocket.chat/docs/getting-support/

**Comment by DerpDarako** [comment]
> 
> 
> > I installed rocket chat today but it's not possible to make it work from your docker-compose.
> 
> Which document did you follow?

I followed this one:

https://rocket.chat/docs/installation/docker-containers/

As you can see the mongo service didnt set a specific version to use. Thus, the command is:
mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1

--smallfiles is unrecognized and mmap is not supported from mongo 4.2 as you can read there:
https://docs.mongodb.com/manual/release-notes/4.2/

**Comment by reetp** [comment]
Not sure which version it pulls with just

```
  mongo:
    image: mongo
```

Yes they are aware about mmap being deprecated, but there are still issues with wiredtiger in certain instances (read elsewhere here)

Suggestion is to use 3.6 or 4.0 currently

**Comment by geekgonecrazy** [comment]
Its looking like with recent versions of Rocket.Chat its less of an issue (wiredtiger vs mmapv1).  So the recommendation against it will hopefully be lifted soon.

Closing as no further comment from comment author.  If any changes need made to doc please feel free to open a PR ( can start the process by clicking edit on the doc page ).  Or open an issue on the docs repo.
