### ISSUE TITLE
Rocket.Chat Live Chat error with WordPress SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by alebeta90** [RocketChat/Rocket.Chat#15326]
### Description:

I installed latest version of rocket.chat with Docker and when I add the JS code in my wordpress site it does not work. It shows message in the dev console

SyntaxError: expected expression, got '<'

Because of that the chat window is not showing,

### Steps to reproduce:

1. Go to livechat dashboard and the installation section and copy the installation of the new version.
2. Paste the code in wordpress

### Expected behavior:

show chat window

### Actual behavior:

![image](https://user-images.githubusercontent.com/11571266/64529520-5f63fc80-d30b-11e9-8461-74b6ef05ea65.png)

### Server Setup Information:
Docker deployment

+--------------------------------------------------+ 
|                  SERVER RUNNING                  | 
+--------------------------------------------------+ 
|                                                  | 
|  Rocket.Chat Version: 1.3.2                      | 
|       NodeJS Version: 8.11.4 - x64               | 
|      MongoDB Version: 4.0.12                     | 
|       MongoDB Engine: mmapv1                     | 
|             Platform: linux                      | 
|         Process Port: 3000                       | 
|             Site URL: https://rocket.dinain.com  | 
|     ReplicaSet OpLog: Enabled                    | 
|          Commit Hash: 22894861c5                 | 
|        Commit Branch: HEAD                       | 
|                                                  | 
+--------------------------------------------------+  

thanks!

**Comment by Lawri-van-Buel** [comment]
To diagnose this we would need to know what that file actually is (it seems to be an html file).
I suspect its a misconfguration somewhere but the files contents would show this likely.

**Comment by alebeta90** [comment]
the error seems to be coming from rocketchat-livechat.min.js as it appears in the screenshot.

I was checking it, but could no find the error.

**Comment by v1adimir** [comment]
I have the same problem. 

As I see the scripts https://chat.vash-stomatolog.com/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000 and https://chat.vash-stomatolog.com/livechat?version=1.0.0 return HTML-files not the JavaScript as expected.

Test Rocket.Chat installation — https://chat.vash-stomatolog.com/
Test Livechat installation — https://system-e.ru/rocket-test.html

**Comment by renatobecker** [comment]
Did you guys enable CORS on Rocket.Chat admin area?
<img width="391" alt="Screen Shot 2019-09-09 at 23 26 28" src="https://user-images.githubusercontent.com/2067649/64579428-46823800-d359-11e9-9971-eedcc1db6558.png">

**Comment by alebeta90** [comment]
Hi @renatobecker ,

thanks for your answer, Yes CORS is enable and configured. Still showing SyntaxError: expected expression, got '<'

thanks for your time

**Comment by renatobecker** [comment]
> Hi @renatobecker ,
> 
> thanks for your answer, Yes CORS is enable and configured. Still showing SyntaxError: expected expression, got '<'
> 
> thanks for your time

You shared this link -> https://rocket.dinain.com where the Rocket.Chat was supposed to be running, is that correct?

**Comment by renatobecker** [comment]
> Hi @renatobecker ,
> 
> thanks for your answer, Yes CORS is enable and configured. Still showing SyntaxError: expected expression, got '<'
> 
> thanks for your time

We removed the `1.0.0.` from the public path, You need to remove it from the paths inside the Javascript snippet installation.

**Comment by alebeta90** [comment]
Hi @renatobecker that solved the mistery. Thanks for your support.

I think it would be good to set the right path in the installation section where the snippet javascript code is.

Thanks for the help
