### ISSUE TITLE
[BUG] RocketChat HA does not work without "master" instance

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#15325]
### Steps to reproduce:

1. Create single instance rocket.chat server
2. Install and connect more rocket.chat instances to existing server and balance them by proxy
3. Try to stop and delete from load balancer the instance that has been created first

### Expected behavior:

Rocket.Chat starts with `n - 1` instances

### Actual behavior:

RocketChat won't start

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Debian 9, Debian 10
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.13

### Relevant logs:

Logs are empty, instances seems working.

**Comment by alebeta90** [comment]
Hi @dusatvoj ,

Did you add the env INSTANCE_IP=$$(hostname -i) ? it is important for the startup of the service, that it can be announce the each different IP of the instances in order to work as a HA.

**Comment by dusatvoj** [comment]
Hi @alebeta90 ,
I have INSTANCE_IP env set up manually as an external IP of each server instance. `hostname -i` tells me `127.0.1.1`

**Comment by alebeta90** [comment]
Hi @dusatvoj,

yes the env INSTANCE_IP has to point to the IP address of each rocket.chat instance inside of their network. In my case I use `hostname -i` command. But basically the IP address that has to be use, is the one is configure in your network interface. that you could see in each VM/Machine with the command `ifconfig`.

In my case I run the rocket.chat cluster in my Docker Swarm cluster.
https://gonkar.com/how-to-install-docker-swarm-in-centos-7/

All the best

**Comment by dusatvoj** [comment]
Found errors on balancer
