### ISSUE TITLE
If you're seeing this Grafana has failed to load its application files!

### ISSUE THREAD

**Issue by pesarkhobeee** [RocketChat/Rocket.Chat#15330]
Suddenly out of nowhere, our rocket chat is displaying this error:

>  If you're seeing this Grafana has failed to load its application files
>  1. This could be caused by your reverse proxy settings.
>  2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath
>  3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build
>  4. Sometimes restarting grafana-server can help

and it is adding 

> /-/grafana/login

To the end of website url too!
Our server is Ubuntu 16.04.6 LTS and we installed rocket chat via snap:

```
root@tube:/etc/apache2/sites-available# snap find rocketchat-server
Name               Version  Publisher    Notes  Summary
rocketchat-server  1.3.2    rocketchat✓  -      Group chat server for 100s,  installed in seconds.
root@tube:/etc/apache2/sites-available# sudo snap refresh rocketchat-server
snap "rocketchat-server" has no updates available
```

And again we didn't touch our server and this problem appeared! are you using grafana inside of rocket chat?

**Comment by pesarkhobeee** [comment]
The problem was a conflict with our Gitlab, according to their [documentation](https://docs.gitlab.com/omnibus/settings/grafana.html):

> Starting with GitLab 12.0, Grafana is enabled by default and SSO with GitLab is automatically configured.

**Comment by mehrdadjavidan** [comment]
> The problem was a conflict with our Gitlab, according to their [documentation](https://docs.gitlab.com/omnibus/settings/grafana.html):
> 
> > Starting with GitLab 12.0, Grafana is enabled by default and SSO with GitLab is automatically configured.

It saved me a lot of time :)

/etc/gitlab/gitlab.rb
grafana['enable'] = false
sudo gitlab-ctl reconfigure

Thanks a lot
