### ISSUE TITLE
Replica set for MongoDB not working 

### ISSUE THREAD

**Issue by sophornsna** [RocketChat/Rocket.Chat#15335]
Dear Rocket Chat team,

I have a problem with MongoDB after I configured Replica set. It shows
 > rs.initiate()
{
	"ok" : 0,
	"errmsg" : "This node was not started with the replSet option",
	"code" : 76,
	"codeName" : "NoReplicationEnabled"
} 
I have enabled it in MongoDB: **/etc/mongod.conf** and add 
#snmp:
replication:
  replSetName: "rs01"

The environment in server:
Debain: V9.9
MongoDB: v4.0.10
node: v8.11.3

Thanks

**Comment by ledlamp** [comment]
did you indent replSetName?

**Comment by sophornsna** [comment]
I just follow from the document: https://rocket.chat/docs/installation/manual-installation/mongo-replicas/

**Comment by sophornsna** [comment]
I have tested it in ubuntu 18.04 it works

**Comment by DoM1niC** [comment]
I use Replica set with Version 4.2.0 & before, already works init the replSet & add the 2 Secondary Mongos to Primary one.

**Comment by battosai30** [comment]
I had this issue, it's just a "timing" problem. rs.initiate() should not be called to quicly, and rocketchat launch too.

**Comment by geekgonecrazy** [comment]
Closing. Looks like question was sufficiently answered.
