### ISSUE TITLE
Cannot add underscores in urls

### ISSUE THREAD

**Issue by llacroix** [RocketChat/Rocket.Chat#15347]
### Description:

A url with underscores will be split in 2 at the underscore

### Steps to reproduce:

1. type an url like this in the chat https://x_x_x.com

### Expected behavior:

Map the link the whole set of char up the next whitespace.

### Actual behavior:

The url parser parse `https://x` then consider `_x_` to be text then parse `x.com` as a second url

### Server Setup Information:

- Version of Rocket.Chat Server:  1.3.2
- Operating System: not sure
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.12

**Comment by cdhowie** [comment]
We have also hit this behavior. Note that the "link preview" function _does_ correctly parse the URL, so clicking on the preview below a message (if enabled) will take one to the correct destination.
