### ISSUE TITLE
Cannot run in wd meteor-dev-bundle@ node npm-rebuild.js 

### ISSUE THREAD

**Issue by LogiEx7** [RocketChat/Rocket.Chat#15343]
Hello, 
I'm trying to install RocketChat. Actually i have node : v8.11.1 & npm : 6.11.3. 
I try to install RocketChat like this : 
```  
curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server 
npm install
 ```

But it's the first time i have this error and i can't fix it. 

``` 
npm install
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)
audited 319 packages in 1.411s
found 0 vulnerabilities
 ```
Someone have a tip for fix that ? 
Thanks

**Comment by reetp** [comment]
@rocket-cat close.

There is no evidence of a bug here. Please see here for how to get support.

https://rocket.chat/docs/getting-support/
https://rocket.chat/docs/contributing/reporting-issues (assuming it is an issue and not a support request)
https://open.rocket.chat #dev 

Checks the tags for required engine versions. At least node 8.11.4 in your case.

https://github.com/RocketChat/Rocket.Chat/releases

**Comment by karl-in-office** [comment]
This issue was already closed, but let me comment for future reference. 
It will be happened if we execute `npm install` as root user. 
Please see also:
https://github.com/meteor/meteor/issues/9696
