### ISSUE TITLE
File uploading stacks at 0%

### ISSUE THREAD

**Issue by 6bI4oK** [RocketChat/Rocket.Chat#15345]
### Description:

Hi, everyone! I'am trying to upload file into a channel. But nothing works. File uploadings stacks as 0% and not progress more. 

### Steps to reproduce:

1. Open any channel
2. Upload any file or files
3. Click submit button

### Expected behavior:

File completely uploaded and successfully send message

### Actual behavior:

Stacks at 0% of file uploading

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: CentOS Linux release 7.6.1810 (Core)
- Deployment Method:  https://rocket.chat/docs/installation/manual-installation/centos/
- Number of Running Instances: 1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.12

### Additional context

I'm trying to upload files using API. All it's done. But using web browser I have the problem

### Relevant logs:

сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: === UnHandledPromiseRejection ===
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: { Error: Match error: Expected string, got undefined
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at check (packages/check/match.js:36:17)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at GridFSStore.Store.self.checkToken (packages/jalik:ufs/ufs-store.js:139:17)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at WebApp.connectHandlers.use (packages/jalik:ufs/ufs-server.js:149:24)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: message: 'Match error: Expected string, got undefined',
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: path: '',
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: sanitizedError:
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: { Error: Match failed [400]
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at errorClass.<anonymous> (packages/check/match.js:91:27)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at new errorClass (packages/meteor.js:725:17)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at check (packages/check/match.js:36:17)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at GridFSStore.Store.self.checkToken (packages/jalik:ufs/ufs-store.js:139:17)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at WebApp.connectHandlers.use (packages/jalik:ufs/ufs-server.js:149:24)
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: isClientSafe: true,
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: error: 400,
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: reason: 'Match failed',
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: details: undefined,
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: message: 'Match failed [400]',
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: errorType: 'Meteor.Error' },
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: errorType: 'Match.Error' }
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: ---------------------------------
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: Errors like this can cause oplog processing errors.
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the proce
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: Future node.js versions will automatically exit the process
сен 11 17:45:03 cmnp-app-1 rocketchat[1098]: =================================

**Comment by JeroenAdam** [comment]
I have had the same issue, solved here: Administration settings -> General -> Site Url 
In my cased I added the port number (3000) and a trailing /

**Comment by geekgonecrazy** [comment]
This would definitely do it. 👍 

Closing since no further comment from author of issue
