### ISSUE TITLE
SMTP mails limitation

### ISSUE THREAD

**Issue by juliensl** [RocketChat/Rocket.Chat#15342]
Hi everybody ! :smile: 

First, I think that I didn't choose the good way to propose a new feature, but I didn't find the good way to do this... I searched in the doc ( https://rocket.chat/docs/contributing/reporting-issues/ ), I found how to post an issue but not how to post a feature, sorry :disappointed: 
I'm able to move this post in the good section.

### Description of problem:
I'm using office 365 to manage my email addresses.
I linked my mailbox with Rocket Chat by SMTP.
The problem is that office 365 has a limit of 30 mails sent per minutes and 10 000 per days.
But I've channel with more than 30 people.

### Solution proposed:
Add a configurable temporization for sending email.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Ubuntu 
- Deployment Method: snap
- Number of Running Instances: 1

Sorry again if I'm in the wrong place :/ 
And thank you very much for your wonderful work ! :tada:

**Comment by reetp** [comment]
https://github.com/RocketChat/feature-requests

Someone should add that more prominently in the documentation.

Not sure if this is a NFR or bug so leaving it open for a dev to consider.

**Comment by localguru** [comment]
For me this sounds more like the wrong SMTP provider.  ;) Or to put it another way: a normal mail account might not be the right approach to use it as smtp relay for a multi user service.

**Comment by juliensl** [comment]
Hi localguru,

Yes, maybe you right, I switch to **mailgun** SMTP provider and now it works well.
Outlook, gmail, etc are not the good services for this.

We can close this issue I think.

Have a good day !
