### ISSUE TITLE
Uploaded files not browseable on docker host

### ISSUE THREAD

**Issue by Nemental** [RocketChat/Rocket.Chat#15359]
### Description:

Run Rocket.Chat server as docker-compose and set file upload to filesystem. Uploaded files are not browseable on docker host.

### Steps to reproduce:

1. Start RC server as docker-compose
2. Set file upload to filesystem
3. As you can see - if you upload a file you cant browse it on the docker host
4. Short look in the container, the files are located in the directory "/app/bundle/programs/server/uploads" and not "/app/uploads"
5. The owner of /app/uploads directory in the container is root, not rocketchat

### Expected behavior:

Browseable files on the docker host in ./uploads

### Actual behavior:

Empty directory 🤓 

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 4.0.12 

### Additional context

-

### Relevant logs:

-

**Comment by reetp** [comment]
This seems more like a configuration error and not a bug.

You haven't posted your compose file path maps.

e.g
```
# Specify an absolute path mapping
    volumes:
    - /opt/uploads/:/opt/uploads/
```

What have you set the File System System Path to?

In the above case it should be

`/opt/uploads`

You need to make sure that /opt/uploads on the docker host has RW permissions for docker itself:

`
drwxr--r-- 3 dockerroot dockerroot 12288 Sep 12 19:16 uploads
`

**Comment by Nemental** [comment]
Okay, so here is the path mapping
```
volumes:
  - ./uploads:/app/uploads
```

The system path in Rocket.Chat settings is `./uploads`

Host uploads directory is set to 755 and owner is the docker-user...

I can upload pictures and after compose down and up they are still there in the chat, but not browsable on docker host 😄

**Comment by reetp** [comment]
I'd try and make sure you use absolute paths, not relative ones, just to be sure.

(don't forget if you change the docker config you will have to pull it again)

**Comment by Nemental** [comment]
`
Exception while invoking method 'ufsComplete' { Error: EACCES: permission denied, open '/app/uploads/CezYy7WFCHRPoBG6K.jpg'   errno: -13,   code: 'EACCES',   syscall: 'open',   path: '/app/uploads/CezYy7WFCHRPoBG6K.jpg' } 
`
- Absolute path
- System path in RC settings is /app/uploads

`/app` permissions:
```
-rw-r--r-- 1 rocketchat rocketchat  596 Sep 12 21:16 Dockerfile
drwxr-xr-x 1 rocketchat rocketchat 4096 Sep 12 21:17 bundle
drwxr-xr-x 2       1002        999 4096 Sep  9 10:24 uploads
```

**Comment by Nemental** [comment]
I think there is a problem with the uploads directory permissions...

**Comment by reetp** [comment]
Think you are right.....

**Comment by Nemental** [comment]
Workaround/Fix:
Set uID 99999 as owner of uploads directory on the docker host. Thats the uID of the rocketchat user in the container.

**Comment by reetp** [comment]
Not sure how or why but I think this is related:

https://github.com/RocketChat/Rocket.Chat/issues/15388

**Comment by Nemental** [comment]
I dont think this is related, but I will try to help him...

**Comment by reetp** [comment]
Both have issues with uID of 99999
