### ISSUE TITLE
In "Directory" view, channel names and usernames are clipped at the bottoms of descending characters

### ISSUE THREAD

**Issue by dholbert** [RocketChat/Rocket.Chat#15354]
### Description:

In the "Directory" view, channel names and usernames that have descending characters (e.g. "g", "y") are clipped on the bottom, due to the site using `overflow:hidden` on their immediate tightly-wrapping container element, `.rc-table-title`. If I remove that declaration, the issue goes away.

### Steps to reproduce:

1. Go to the `directory` page (e.g. click the globe icon at top left)
2.Look for a channel name or a username that has a descending character like "g" or "y"

### Expected behavior:
The bottom edge of the descending character should be visible.

### Actual behavior:

The bottom edge of the descending character is clipped.

### Server Setup Information:

I'm not sure about  this info -- it's not my own deployment. It's a deployment that some folks at Mozilla are evaluating, currently at https://rocketchat-test.allizom.org

**Comment by nstseek** [comment]
I tried to replicate your problem here but it seems normal to me, take a look at this screenshot: 
![Screenshot_2019-10-06_19-23-53](https://user-images.githubusercontent.com/41304108/66277016-f2427900-e86e-11e9-8221-6604e9f2394e.png)
Is this bug still there?

**Comment by dholbert** [comment]
Yes, I can still reproduce.  Here's a screenshot:
![image](https://user-images.githubusercontent.com/426803/66430917-df938580-e9cf-11e9-8ae0-7cdfdc26a957.png)

As noted above, the issue goes away if I set `line-height:normal` on a `.rc-table-title` CSS rule, though.

**Comment by dholbert** [comment]
Note that my installation is going away tomorrow, so I won't be able to test in this particular installation from that point on.

However, I just found https://open.rocket.chat/ and I confirmed that I do see the bug there as well. Here's a screenshot there (I used devtools to rename the second channel to "gggyyy" to make the problem more obvious):
![image](https://user-images.githubusercontent.com/426803/66431386-c3dcaf00-e9d0-11e9-96a3-d5f19b232e08.png)

**Comment by nstseek** [comment]
That's strange, I went to https://open.rocket.chat/ and the "Directory" view seems normal in my browser, look

![Screenshot from 2019-10-10 17-57-04](https://user-images.githubusercontent.com/41304108/66606031-9b4ae580-eb87-11e9-9637-4ea30d771d66.png)

I'm using Firefox Quantum 69.0.1 (64-bit), which browser are you using?

**Comment by dholbert** [comment]
It's broken for me, using Firefox 69.0.2 (64-bit) as well as in Firefox Nightly (71.0a1).  Perhaps we have subtly different versions of the Ubuntu font, or some other subtly different OS setting that's contributing to the behavior difference?

One thing that might help, that I noticed when testing on another machine -- if I download and install the "Segoe UI" Microsoft font from https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#fonts (via the "Segoe UI and MDL2 icon fonts (Mac only)" link on that site), I get a significantly-worse experience, where the curvy-bottom-descender of the "g" is **clipped entirely**, so it looks like a "q":
![image](https://user-images.githubusercontent.com/426803/66611574-db07d200-eb73-11e9-8aef-f953b2342fc2.png)

This font gets used preferentially if you've got it, because Rocket.Chat lists it earlier (and hence higher-priority) as compared to the "Ubuntu" font, in the font-family CSS declaration:
```css
.global-font-family {
    font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Meiryo UI',Arial,sans-serif;
}
```

I verified that this is still fixed by my suggested `.rc-table-wrapper { line-height:normal }` workaround.

**Comment by dholbert** [comment]
If you end up testing with Segoe UI font (which makes the issue more severe & perhaps more reproducible I'm hoping), you would want to:
 (1) visit https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#fonts
 (2) Click the link for the "Segoe UI" font zip file there 
 (3) open the downloaded zip and double-click `segoeui.ttf` and choose "install" in the Ubuntu font-viewer program
 (4) restart Firefox
 (5) visit https://open.rocket.chat/directory

You can verify that the font is active in Firefox devtools (if you like) right-clicking the text `#general` and choosing "Inspect", and then picking the "Fonts" subtab in the devtools inspector. ("Fonts" is a few tabs to the right of the "Rules|Layout|Computed|..." devtools-inspector subtabs.)  That should show "Fonts used   Segoe UI" to indicate that the font is active.

**Comment by nstseek** [comment]
I did tried to replicate this issue in windows and it did work. The 'g' looks like a 'q'. It just does not happen on Linux Mint, the system that I was working on. I'll try to fix it, thank you.

**Comment by dholbert** [comment]
Good to hear.  Thanks!
