### ISSUE TITLE
Name already exists!

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1536]
On a freshly installed rocket chat server with few test rooms, and enabled arabic characters in the naming regex. When I try to rename the room from any english name to *any* other name in arabic I get this error message:
![rocketchat-bug9](https://cloud.githubusercontent.com/assets/432460/11512702/6c1b881a-983d-11e5-997e-b2f9e5a14ec9.png)

I have seen a similar bug when I wanted to register my name on Rocket chat demo server, it complained that the name is already in use but it wasn't since I tried many weird names and finally @engelgabriel confirmed that the name was actually available. (using English names) 
Also the same thing happened on our test server, as some users reported the problem when selecting user names while the server is new and no one has registered with these names yet.

**Comment by marceloschmidt** [comment]
This is fixed with UTF8 Names Validation setting under Administration / General / UTF8
