### ISSUE TITLE
API endpoint users.list -- 404

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#15366]
### Description:

The `users.list` endpoint is returning HTTP status 404 in some (seemingly random, but reproducible) cases.

### Steps to reproduce:

1. make an authenticated API call to `users.list?query={"username":"InHjufs"}` -- note that the query fails with an 404 status code -- no results are returned
2. make the same API call but remove the final "s" from the query, e.g. `users.list?query={"username":"InHjuf"}` -- note that the query returns a 200 status code with a correct JSON response (no results, but the response payload is correct)
3. make the same API call but replace the "s" with another character, e.g. `users.list?query={"username":"InHjuff"}` -- note that the result is the same as in step 2 -- success

### Expected behavior:

This endpoint should _never_ return 404. It should return 401 if the user is not authenticated, but otherwise it should return 200.

### Actual behavior:

This endpoint sometimes return 404, but the reason is unclear and not predictable.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.0
- Operating System: RHEL
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes?
- NodeJS Version: 8.11.4
- MongoDB Version: 3.2.21

### Additional context

I realize that the queries are specific to my environment, but regardless, for some reason 404 is returned when it shouldn't be.

### Relevant logs:

Nothing shows up in the logs regarding this issue.

**Comment by reetp** [comment]
First please always test on latest

"Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

Probably not, but needs testing.


Similar to mine.... (probably repeatable on v2 but not have only just updated my test box) the error handling should be accurate an consistent.

https://github.com/RocketChat/Rocket.Chat/issues/15313

**Comment by JoshMcCullough** [comment]
Yep, this seems to be working fine in RC 1.3.2. Closing.
