### ISSUE TITLE
Assets not found

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15362]
Version 2.0.0
Install Docker
Mongo 4.0
OpLog enabled
Storage WiredTiger
Proxy nginx

After pulling the new v2.0.0 I noticed that the logo was failing to show in the lower left corner of the screen

It shows on the login page with the URL:
`https://chat.mydomain.com/assets/logo.svg`

But in the main Rocket panel this is the URL:
`https://chat.mydomain.com/assets/logo`

But the logo does not show and I get a 403 error:
`GET https://chat.mydomain.com/assets/logo 403 (Forbidden)`

If I mod the link in the browser console to `assets/logo.svg` it appears.

If we look at open.rocket.chat then the link is:
`<a href="/home"><img src="assets/logo.png"></a>`

And while we are about it there is an issue with URLs on Livechat you should look at as well.

Various assets are not 404 not found in the browser inspector:
https://chat.mydomain.com/assets/icons/android-chrome-192x192.png

Ahh. Hidden here.
https://chat.mydomain.com/livechat/assets/icons/android-chrome-192x192.png

You can try it on your own server too.
https://open.rocket.chat/livechat/assets/icons/android-chrome-192x192.png

Nothing was touched on my server. I literally stopped docker, backed up the DB and then  docker-compose pull / up -d rocketchat

**Comment by sampaiodiego** [comment]
hi @reetp 

looks like something was different on your layout setting that prevented [the migration](https://github.com/RocketChat/Rocket.Chat/pull/15088/files#diff-1f4306b1ec37923e6dda00e50d8b13e0) from updating to the new correct value.

You just need to add an extension to the img `src` and it is [mandatory now](https://github.com/RocketChat/Rocket.Chat/pull/15088/)

**Comment by reetp** [comment]
> You just need to add an extension to the img src

It had an extension. I can still see it if I go to:
https://chat.mydomain.com/assets/logo.svg

It's been been dead standard ever since way back when. Only thing I ever did was add a permitted svg logo. There are no fancy hacks.

That should not break surely??

These were the migrations. Why didn't they check for svg, which was permitted?

`Settings.update({ _id: 'Layout_Sidenav_Footer' }, { $set: { value: '<a href="/home"><img src="assets/logo.png"/></a>' } });`

`return this.add('Layout_Sidenav_Footer', '<a href="/home"><img src="assets/logo.png"/></a>'`

And exactly how do I fix this??

**Comment by sampaiodiego** [comment]
I'm sorry I meant you have to add an extension to `<img />` tag attribute. So the setting **Side Navigation Footer** should look like this:
```javascript
<a href="/home"><img src="assets/logo.png"/></a>
```

And what I meant by extensions are now mandatory is to request/see assets.. So *before* 2.0 the following URL worked just fine: https://chat.mydomain.com/assets/logo

but *now on 2.0*, you **have** to provide the file extension, like: https://chat.mydomain.com/assets/logo.png or https://chat.mydomain.com/assets/logo.svg

**Comment by reetp** [comment]
OK - think I get that all now.

Adjusted the Side Navigation Footer to add 'svg'

`<img src="/assets/logo.svg" />`

The logo always was logo.svg
