### ISSUE TITLE
cannot login rocketchat by always  reload login page after a machine restart 

### ISSUE THREAD

**Issue by beanslee2011** [RocketChat/Rocket.Chat#15373]
Server Setup Information:
Version of Rocket.Chat Server: 1.0.3【new install and not upgraded from old version】
Operating System: centos 7.4
Deployment Method: Manual by official doc
Number of Running Instances: 1
DB Replicaset Oplog: true
NodeJS Version: 8.11.3
MongoDB Version: 3.6.12

=====
After a server machine reboot, I started rocketchat by this command( also set env varible):
 /usr/local/bin/node /opt/Rocket.Chat/main.js

and I got this infomation:
{"line":"121","file":"migrations.js","message":"Migrations: Not migrating, already at version 144","time":{"$date":1568616267114},"level":"info"}
Loaded the Apps Framework and loaded a total of 0 Apps!
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Updating process.env.MAIL_URL
➔ System ➔ startup
➔ +--------------------------------------------------+
➔ |                  SERVER RUNNING                  |
➔ +--------------------------------------------------+
➔ |                                                  |
➔ |  Rocket.Chat Version: 1.0.3                      |
➔ |       NodeJS Version: 8.11.3 - x64               |
➔ |      MongoDB Version: 3.6.12                     |
➔ |       MongoDB Engine: wiredTiger                 |
➔ |             Platform: linux                      |
➔ |         Process Port: 3000                       |
➔ |             Site URL: http://x.x.x.x:3000  |
➔ |     ReplicaSet OpLog: Enabled                    |
➔ |          Commit Hash: f19473c626                 |
➔ |        Commit Branch: HEAD                       |
➔ |                                                  |
➔ +--------------------------------------------------+

======
And I can not login rocketchat, the login page is  always auto reloaded .
I tried this command in mongodb but not worked for me:
db.migrations.update({"_id": "control"}, {"version": 144, "locked": false})

thanks~~

**Comment by reetp** [comment]
https://rocket.chat/docs/contributing/reporting-issues

> Before reporting a new issue
> 
>    1 Read the Documentation carefully all the way through.
>    2 **Make sure you are running the latest version of Rocket.Chat**. It’s very likely simply updating will resolve your issue.

What does this mean?
> Deployment Method: Manual by office doc

I'd go back and follow the documentation. Use 'latest'  - currently v2.0.0
https://rocket.chat/docs/installation/manual-installation/centos/

**Comment by beanslee2011** [comment]
sorry ,it's my fault. 
Deployment Method should be : Manual by official doc  
i use this doc(with 1.0.3 version):
https://rocket.chat/docs/installation/manual-installation/centos/

Can I upgrade from 1.0.3 to 2.0.0?

**Comment by beanslee2011** [comment]
the proble m still exists....
I have upgraded rocketchat   to 2.0.0
