### ISSUE TITLE
Existing customFields data will be disappeared or showing only changed data at customFields if there is any update data at customFields on Active Directory

### ISSUE THREAD

**Issue by ybshin** [RocketChat/Rocket.Chat#15374]
### Description:

If there is any update or changing data on Active directory, the existing data will be disappeared or showing only changed data at customFields.

Accounts -> Custom Fields to Show in User info
[{"Office": "Office"}, {"Department": "Department"}, {"Position": "Position"}, {"Extension": "Extension"}]

My configuration for CustomFields

Accounts -> Registration
{
	"Office": {
		"type": "text",
		"required": false,
		"public": true
	},
	"Department": {
		"type": "text",
		"required": false,
		"public": true
	},
	"Position": {
		"type": "text",
		"required": false,
		"public": true
	},
	"Extension": {
		"type": "text",
		"required": false,
		"public": true
	} 
}

LDAP -> Sync / Import -> User Data Field Map
{"cn":"name", "mail":"email", "physicalDeliveryOfficeName":"customFields.Office", "department":"customFields.Department", "title":"customFields.Position", "ipPhone":"customFields.Extension"}

### Steps to reproduce:

1.  LDAP -> Sync / Import
2.  Execute Synchronization Now
3. 

### Expected behavior:

Update customFields data for All user
![image](https://user-images.githubusercontent.com/10042091/64938388-ebd06b00-d887-11e9-8d36-5b281dbd8c2e.png)

### Actual behavior:

I edited Department data on Active Directory and then click 'execute Synchronization Now' on Rocket Chat server and the Department data is empty.

![image](https://user-images.githubusercontent.com/10042091/64944823-68b81080-d899-11e9-8db0-69757ac1e677.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: CentOS 7.6
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.10

### Additional context

For New account on AD, the customFields work properly but If there is any changing data at customFields the data will be disappeared or empty.

### Relevant logs:

This is updated log on server but other customFields gone only updated changed data.

I20190916-15:30:26.916(7) LDAPSync ➔ info Syncing user data 
I20190916-15:30:26.917(7) LDAPSync ➔ debug user { email: undefined, _id: '8R5Q5jjhXoX2Jpmxm' } 
I20190916-15:30:26.917(7) LDAPSync ➔ debug ldapUser undefined 
I20190916-15:30:26.918(7) LDAPSync ➔ debug user.customFields.Department changed to: testDE2 
I20190916-15:30:26.919(7) LDAPSync ➔ debug setting {   "customFields": {     "Department": "testDE2"   } } 

![image](https://user-images.githubusercontent.com/10042091/64943979-5937c800-d897-11e9-9eec-9ae32b860ed0.png)

**Comment by magicbelette** [comment]
Hi, 

Same problem with OpenLDAP Server and Rocket.Chat version 2.2.0.
