### ISSUE TITLE
rocket.chat not in android "share to" menu

### ISSUE THREAD

**Issue by reaseno** [RocketChat/Rocket.Chat#15371]
### Description:

When I want to share links or such, rocket.chat isn't in the "share to" menu of different apps.

I tried to find an android system setting and also looked up in the the issues here and on the internet.

### Expected behavior:

rocket.chat should be in the "share to" menu.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: CyanogenMod 12.1 / Android 5.1.1
- rocket.chat Client: 3.5.0 (2074)

**Comment by reetp** [comment]
Please close this and re open in the correct repo

https://github.com/RocketChat/Rocket.Chat.Android

As Rocket are moving to the React native client you may get better mileage testing that and then adding an issue in the React Native repo.
