### ISSUE TITLE
Can not disable slackbridge

### ISSUE THREAD

**Issue by stefan-enway** [RocketChat/Rocket.Chat#15381]
### Description:

Slackbridge still works even if all settings are set to false

### Steps to reproduce:

1. Go to administration -> SlackBridge
2. set everthing to "false"
3. go to Slack and do something

### Expected behavior:

Slack Input gets ignored

### Actual behavior:

Slack Input is still accepted

### Server Setup Information:

- Version of Rocket.Chat Server: hosted @ rocket.chat

**Comment by MarcosSpessatto** [comment]
Hi @stefan-enway. What version are you running?

**Comment by stefan-enway** [comment]
0.74.3
Support suggested upgrading (what only they can do its @rocket.chat) but it takes ages for them to respond.
