### ISSUE TITLE
assets/logo gives 403

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#15386]
### Description:

After Upgrade to 2.0 access to assets/logo is denied by both nginx and rocketchat node servers.

curl -I  https://chat.example.net/assets/logo
HTTP/1.1 403 Forbidden
Server: nginx
Date: Mon, 16 Sep 2019 20:50:36 GMT
Connection: keep-alive
X-Instance-ID: hhkh9jd2igACsMzC5

curl -I http://127.0.0.1:3003/assets/logo
HTTP/1.1 403 Forbidden
X-Instance-ID: uDWwZnH5ra9Qq8bS4
Date: Mon, 16 Sep 2019 20:5

Note: This happens on all 4 instances.

### Steps to reproduce:

I am unsure if this an inherited issue due to the age of the instance (installed 2016). What I did was simply to upload an svg as logo, does not show.

### Expected behavior:

Logo does show.

### Actual behavior:

403 on all queries to assets/logo; no matter from where or on what.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.12

### Additional context

---

### Relevant logs:

There are no logs even in debug mode related to this issue on rocketchat.

**Comment by reetp** [comment]
Always have a thorough Search for issues first.

Something like this with the 'is open" removed:

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+logo

You  may find these.

https://github.com/RocketChat/Rocket.Chat/issues/15362

https://github.com/RocketChat/Rocket.Chat/issues/15266

**Comment by christianreiss** [comment]
You are right; fixed and closed.
