### ISSUE TITLE
Docker pull failing due to userns-remap enabled on docker daemon file

### ISSUE THREAD

**Issue by mohanbabubb** [RocketChat/Rocket.Chat#15388]
### Description:

Docker pull failing due to userns-remap attribute  on the  /etc/docker/daemon.json file 
### Steps to reproduce:

1. Set the below config on the docker daemon.json file and restart the docker service
2. Pull the rocketchat latest ( 2.0.0 ) from the dockerhub
docker pull rocketchat/rocket.chat:2.0.0

### Expected behavior:

It should work wihtout any issues.

### Actual behavior:

Trying to pull repository registry.access.redhat.com/rocketchat/rocket.chat ...
Trying to pull repository docker.io/rocketchat/rocket.chat ...
2.0.0: Pulling from docker.io/rocketchat/rocket.chat
bc9ab73e5b14: Pull complete
3f117e0d3349: Pull complete
29f0971335c1: Pull complete
a717aa7e730b: Pull complete
0a2d97db0648: Pull complete
0ebf10fa60cb: Pull complete
33614e586d73: Extracting [==================================================>] 147.3 MB/147.3 MB
Trying to pull repository registry.fedoraproject.org/rocketchat/rocket.chat ...
Trying to pull repository quay.io/rocketchat/rocket.chat ...
Trying to pull repository registry.centos.org/rocketchat/rocket.chat ...
Trying to pull repository docker.io/rocketchat/rocket.chat ...
2.0.0: Pulling from docker.io/rocketchat/rocket.chat
bc9ab73e5b14: Pull complete
3f117e0d3349: Pull complete
29f0971335c1: Pull complete
a717aa7e730b: Pull complete
0a2d97db0648: Pull complete
0ebf10fa60cb: Pull complete
33614e586d73: Extracting [==================================================>] 147.3 MB/147.3 MB
failed to register layer: Error processing tar file(exit status 1): Container ID 99999 cannot be mapped to a host ID

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Centos 7.6.1810
- Deployment Method:  Docker 1.13
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

Suspects ,this might be the cause, https://circleci.com/docs/2.0/high-uid-error/

**Comment by Nemental** [comment]
https://github.com/RocketChat/Docker.Base.Image/issues/6#issuecomment-289157482
He has the same error message and fixed it by pulling the image from hub.docker.com... As I can see, you pull from "docker.io/rocketchat/rocket.chat"

**Comment by mohanbabubb** [comment]
> [RocketChat/Docker.Base.Image#6 (comment)](https://github.com/RocketChat/Docker.Base.Image/issues/6#issuecomment-289157482)
> He has the same error message and fixed it by pulling the image from hub.docker.com... As I can see, you pull from "docker.io/rocketchat/rocket.chat"

Yep. that link is dead now. and only using this. 
ITS fixed,  [https://github.com/RocketChat/Docker.Base.Image/commit/68611f86faa871264ab25210ae5d6b1fc0554dc1](https://github.com/RocketChat/Docker.Base.Image/commit/68611f86faa871264ab25210ae5d6b1fc0554dc1)

**Comment by Nemental** [comment]
So its fixed? You can close this issue :)

**Comment by mohanbabubb** [comment]
No. i found way to fix it, i would recommend it should be fixed here [->](https://github.com/RocketChat/Docker.Official.Image/blob/master/Dockerfile)/ or on the docker hub.
Dont know who does this.!! or dont know whom to contact. do you know, whom to contact?!

**Comment by Nemental** [comment]
Share your solution in this issue, so somebody can fix the code
