### ISSUE TITLE
Incompatible with Firefox Private Network

### ISSUE THREAD

**Issue by Yoric** [RocketChat/Rocket.Chat#15396]
### Description:

With Firefox Private Network, I can connect once, but I cannot reconnect.

### Steps to reproduce:

1. Connect to https://rocketchat-test.allizom.org/ . Might work with other instances.
2. Chat a bit.
3. Click on the "update Firefox" arrow on the hamburger menu.
4. Visit https://rocketchat-test.allizom.org/ once again.

### Expected behavior:

I expected to see Rocketchat.

### Actual behavior:

Any attempt to visit https://rocketchat-test.allizom.org/ shows a throbber, endlessly.

### Server Setup Information:

(no idea)

### Additional context

The problem does not show up with Firefox Private Network disabled.

### Relevant logs:

Browser logs: [logs.txt](https://github.com/RocketChat/Rocket.Chat/files/3623073/logs.txt)

**Comment by geekgonecrazy** [comment]
Taking a look at this.. it seems that this is a bug somewhere between the server running rocket.chat and your browser / plugin.  I can confirm you are getting this error when visiting that specific instance.  But tried several others as well as open.rocket.chat and Rocket.Chat its self is not bothered by this at all.

So this is more of a support issue than a product bug.

It looks like your proxy/server/isp is causing it to not even respond to the main request:

![image](https://user-images.githubusercontent.com/51996/67225492-f8049680-f3f8-11e9-8fcc-155c3a9c9068.png)

Actually oddly enough even after I disabled I couldn't connect.  Seems like something deeper might be going on with that server
