### ISSUE TITLE
Webdav error 500 in RocketChat, file has successfully uploaded.

### ISSUE THREAD

**Issue by ParkHost** [RocketChat/Rocket.Chat#15390]
### Description:

Webdav upload still gives errors

### Steps to reproduce:

1. Upload File
2. Error 500 when finished
3. The file has been uploaded to webdav, except RC gives a 500 error.

### Expected behavior:

Files upload succesvol without a RC error

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Debian 9
- Deployment Method: LXC
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.14

### Relevant logs:

Internal server error [500]
statusCode: 404,         statusMessage: 'Not Found',

**Comment by Adam212** [comment]
Hello,

You can try changing line 281 in programs/server/npm/node_modules/follow-redirects/index.js with:
maxBodyLength: 500 * 1024 * 1024,

It worked for me also in previous versions.

**Comment by ParkHost** [comment]
seems to me it is already looking for the file while it is still uploading, maybe a async await mismatch?
