### ISSUE TITLE
Auto login with MS AD in desk.app.

### ISSUE THREAD

**Issue by kampolwampir** [RocketChat/Rocket.Chat#15402]
Good day!
There is really a lack of the possibility of automatic authorization in a desktop application with MS AD synchronization turned on.
Is it planned to implement this function or is there a possible solution to this problem?
There are no suitable solutions on the Internet, only OAuth is recommended, but it is not suitable for a desktop application.

**Comment by reetp** [comment]
@rocket-cat close

This repo is reserved for bugs in Rocket.Chat

There is no evidence of breakage here - it just doesn't seem to do what you want, which is a feature request and goes here https://github.com/RocketChat/feature-requests/issues

If you are reporting an issue then use the template, but first please read these:

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Also note that you possibly want to look at the Electron app:
https://github.com/RocketChat/Rocket.Chat.Electron
