### ISSUE TITLE
Rasa chatbot pass bot commands

### ISSUE THREAD

**Issue by alebeta90** [RocketChat/Rocket.Chat#15419]
### Description:

Hello friends,

I'm using Rasa as chatbot framework. And it is already integrated in RocketChat and working, so far all good. There is just one problem when users need to send a command to the bot. For example Rasa bot has the commando `/restart` to start over the conversation. As it is starting with `/` RocketChat process this message as an internal Rocket command. 

I'm able to use such a command in Slack for example, just adding a whitespace in front of the command and it will send it to the bot as a message, for example: ` /restart`

Which would be the best practice to include this capability of sending commands to the bot?

Thanks in advance

**Comment by reetp** [comment]
Closing notabug.

This seems to be a setup/support issue.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

You might need to be patient for a response as it is community support.

**Comment by reetp** [comment]
@rocket-cat close
