### ISSUE TITLE
LDAP and OAth merged accounts don't work with Group/Channel mappings

### ISSUE THREAD

**Issue by hpvb** [RocketChat/Rocket.Chat#15410]
### Description:

My Rocket.Chat instance has an LDAP sync as well as oauth users. When setting up an LDAP group membership <> Channel membership rule this works for the initial sync of the user. However when the user then signs in using Oauth subsequent channel membership changes in LDAP won't work until the user logs in with LDAP username/password. As long as the user is still logged in using Oauth no changes to channel memberships happen, even after an LDAP sync.

### Steps to reproduce:

1. Setup LDAP backend and setup a group to channel mapping. Enable `Merge Existing Users`
2. Setup an Oauth login method. Enable `Merge users`
3. Synchronize LDAP users and groupd.
4. Login with LDAP username/password combination, notice that the channel memberships are correct.
5. Change LDAP user group memberships, notice that the logged in LDAP users' channel memberships change.
6. Login with Oauth (same user), notice that the channel memberships are correct.
7. Change LDAP user group memberships, notice that the Oauth logged in session is not updated.

The user's groups will never update until the user logs in with LDAP username/password.

### Expected behavior:

User's session behavior should be identical regardless of actual login method used.

### Actual behavior:

Oauth logged in users don't get their channel memberships updated.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Fedora 30
- Deployment Method: Docker official (on Podman)
- Number of Running Instances: 1
- DB Replicaset Oplog: 128
- NodeJS Version: in container
- MongoDB Version: 4.2.0

**Comment by hpvb** [comment]
It appears that this same behavior happens with the avatar (jpegPhoto) setting a new avatar does not take effect until the user has logged in using LDAP once.

**Comment by ankar84** [comment]
It is very important issue for us.
We use LDAP to create users in RC and fill their info + Avatar + channels membership + RC roles.
And we use custom oauth (KeyCloak) to users to authenticate to RC.
