### ISSUE TITLE
Change Login Form transparency

### ISSUE THREAD

**Issue by Artapel** [RocketChat/Rocket.Chat#15417]
How do i change the transparency of the "/home" login form?

Currently it's white, which i assume is the same color as "Content Background Color"

When i change the "Content Background Color" the login form background change aswell.

I would like to have the login form to be about 20% transparent on top of the "login background (svg, png, jpg)" picture

How can I achieve this goal?

**Comment by Artapel** [comment]
Hi Guys, Any ideas on this?

**Comment by Artapel** [comment]
Hi Guys, Any ideas on this?

**Comment by reetp** [comment]
@rocket-cat close 

Closing notabug.

This seems to be a setup/support issue.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
