### ISSUE TITLE
Unified channel creation?

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1541]
Just an idea, curious what people think.  

Would it make sense to make a unified channel creation?  On the screen being able to choose the channel type "Channel" / "Private". 

Like if in the future we have private channels that are accessible via a special url.  Or if we make it pass code entry.  Seems like it'd make sense to have one place to quickly go.
##

**Comment by thejae** [comment]
Do you mean something like MMORPGs? I'd totally love something like WoW's implementation? Probably with predefined commands/ shortkeys and on top of that user-customizable cmds.

Cmd  | Channel
------------- | -------------
/1 | General
/2  | Trade
/p  | Party
/g  | Guild
/y  | Yell
/w  | Whisper (Private msg)

**Comment by geekgonecrazy** [comment]
@thejae Not really what I had in mind.  That is interesting though.

I was thinking more of one button you click to create a new channel instead of two.  Clicking it brings up a creation screen.  You can choose invite only / password required / public / associated with a team etc.

**Comment by engelgabriel** [comment]
+1

I agree with @geekgonecrazy, and I know that the rest of the team agrees too.

Even the routes should be unified for all channel, independent of type.

**Comment by MartinSchoeler** [comment]
This feature has been already added
