### ISSUE TITLE
Registration page not mobile friendly

### ISSUE THREAD

**Issue by Nemental** [RocketChat/Rocket.Chat#15422]
### Description:

I cant scroll on the registration page, either on desktop (small windows size) or iPhone.

### Steps to reproduce:

1. Activate secret registration
2. Open the secret registration page

### Expected behavior:

The expected behavior is to be able to scroll the registration page and to fill in all fields. The last form-field is not clickable.

### Actual behavior:

![2019-09-23 09-09-32-1](https://user-images.githubusercontent.com/15136847/65407486-fdaf9200-dde2-11e9-9b3b-97d9b4a675b1.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Ubuntu 18.04
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: activated
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.12

### Additional context

/

### Relevant logs:

/

**Comment by nstseek** [comment]
Hello! I tried to replicate your bug, the registration and login page really does not allow the user to scroll when the screen is too small, I did fix that as you can see in this gif below, but I was able to click in each field without any problems, maybe you can try again and see if the field click bug is still there?

I also tried non-matching passwords and invalid mail, the web app still allowed me to click and change every field in the page.

![ezgif-2-afb4324f6d0a](https://user-images.githubusercontent.com/41304108/66277332-11dba080-e873-11e9-9218-d2d94a9c89fc.gif)

**Comment by Nemental** [comment]
I will try again with your workaround, thanks! @nstseek

**Comment by nstseek** [comment]
You're welcome! Please, let me know if it's working just fine

**Comment by Nemental** [comment]
On desktop it works, but if I test on my iPhone XS its still the same behavior :(
RC-Server 2.3.2
@nstseek
