### ISSUE TITLE
Reset password does not work properly 

### ISSUE THREAD

**Issue by xjtufjj** [RocketChat/Rocket.Chat#1542]
I forgot my password for demo.rocket.chat, and then I click the "forgot my password" button on the login page. Then I received a email with a hype link, I click the hyperlink, it did not guide me to the password reset page, it guided me to the account verify page. for the email content, please see the attachment.
![2015-12-02 9 56 27](https://cloud.githubusercontent.com/assets/2138665/11520104/fe7b7ae2-98da-11e5-92d8-b2fdc02c3587.png)

**Comment by k0nsl** [comment]
Please see #1502

**Comment by xjtufjj** [comment]
thanks for that, do we have a schedule when the issue is fixed ?

**Comment by Sing-Li** [comment]
Not typically for open source projects. 

Most of the time, the more people in the community report a problem, the faster it gets fixed.  

Closing this for duplication.
