### ISSUE TITLE
Collect RocketChat Logs in Sumo Logic

### ISSUE THREAD

**Issue by pageb018** [RocketChat/Rocket.Chat#15425]
### Description:

I am looking to see if I can collect RocketChat logs into Sumo Logic. Sumo has direct integration with Slack 

https://help.sumologic.com/07Sumo-Logic-Apps/18SAAS_and_Cloud_Apps/Slack/Collect_logs_for_the_Slack_App

And I wonder if I could use this in RocketChat. 

### Steps to reproduce:

NA

### Expected behavior:

Use an outgoing webhook (maybe) for allow Sumo to collect RocketChat logs.

### Actual behavior:
NA

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.9

### Additional context
NA

### Relevant logs:

NA

**Comment by reetp** [comment]
@rocket-cat close

This repo is for bugs in Rocket.Chat

This seems to be a support issue or possibly new feature request.

Take a look at the API:

https://rocket.chat/docs/developer-guides/

Please ask in the forums: https://forums.rocket.chat/ or # support at https://open.rocket.chat/

Feature requests should be opened here:
https://github.com/RocketChat/feature-requests/issues
