### ISSUE TITLE
Permission users-generate-access-token not working

### ISSUE THREAD

**Issue by daniel-van-niekerk** [RocketChat/Rocket.Chat#15429]
I'm trying to generate a user access token using this API endpoint:

/api/v1/users.createToken

My headers for X-Auth-Token and X-User-Id is correctly set, I can perform other actions such as registering users etc. I have the Admin role and the Admin role has the users-generate-access-token permission.

However it returns this error message:

`{
  "success": false,
  "error": "Not authorized [error-not-authorized]",
  "errorType": "error-not-authorized"
}`

I've tried creating a new role and giving it the users-generate-access-token permission and then assigning that role to my account but still the same issue. Is there some other permission or settings that would prevent this from working?

**Comment by MarcosSpessatto** [comment]
Hi @daniel-van-niekerk, What version of the server you are running? If it is the latest `v2.1.0`, we added a ENV VAR on that endpoint, that means you won't be able to create tokens without this ENV VAR defined.
Please take a look on: https://github.com/RocketChat/Rocket.Chat/pull/15334

**Comment by johannel00** [comment]
@daniel-van-niekerk I corrected it by following this direction and changed the ENV VAR: [https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-change-other-environmental-variables-in-my-snap](url)

Thank you @MarcosSpessatto for pointing me in the right direction!

**Comment by hexus** [comment]
This is actually quite a big breaking change for us at Claromentis, as we depend on this endpoint to log in users synchronised with our platform. The documentation does not make it clear that the value of the environment variable needs to be set to exactly `yes` or `true`.

This can be seen in the code of the merge request you linked, @MarcosSpessatto:
- https://github.com/RocketChat/Rocket.Chat/pull/15334/files#diff-f301626592d6eba70764a04d241aa8c5R8

Please document this more clearly here:
- https://rocket.chat/docs/developer-guides/rest-api/users/createtoken/

**Comment by hexus** [comment]
@MarcosSpessatto and @sampaiodiego, would either of you care to comment on this?

**Comment by justinscottroman** [comment]
this worked for us:

1.	Put CREATE_TOKENS_FOR_USERS=true in /lib/systemd/system/rocketchat.service 
(/etc/environment does not take effect)
2.	Reboot the OS 
(just restarting the node process it does not take effect)
