### ISSUE TITLE
Database support roadmap

### ISSUE THREAD

**Issue by bkmgit** [RocketChat/Rocket.Chat#15433]
MongoDB has changed its licensing policy, https://www.mongodb.com/licensing/server-side-public-license. Will Rocket Chat continue to use MongoDB exclusively in future or are there plans to allow for use of other databases?

**Comment by bkmgit** [comment]
Possible additional databases include [Cassandra](http://cassandra.apache.org/), [CouchDB](https://github.com/apache/couchdb) and [Scylla](https://github.com/scylladb/scylla).

**Comment by antkaz** [comment]
We started using [Percona server for Mongo](https://www.percona.com/doc/percona-server-for-mongodb/4.0/index.html) as an alternative for MongoDB

**Comment by bkmgit** [comment]
This also seems to use [Server Side Public license](https://github.com/percona/percona-server-mongodb/blob/master/LICENSE-Community.txt)

**Comment by reetp** [comment]
Related thread:

https://forums.rocket.chat/t/legal-implications-of-mongodb-licensing-change/2332/5
 
There have been other similar questions asked before about other dbs eg postgresql but I can't find them at the minute. Have a hunt here.

I believe for technical reasons mongo is good to develop with for easy schema changes.

I haven't heard of any plans to move away from it but devs may have more input.

This is not a bug in Rocket.Chat and should be closed and potentially added as a feature request.

Search first....

https://github.com/RocketChat/feature-requests/issues

**Comment by bkmgit** [comment]
Thanks, there are a number of related discussions #533 #639, no definite answers.

Meteor had some work on Postgres which was [deprecated](https://github.com/meteor/postgres-packages),but has the intention of using other database as indicated on their [roadmap](https://github.com/meteor/meteor/blob/devel/Roadmap.md).

Can make this a feature request, though may need further discussion.

**Comment by geekgonecrazy** [comment]
#533 - yes this is a super long running desire to be flexible.  I believe it is something we are working steadily towards.  The dependence on Meteor and Meteor not supporting it for sure made this harder.  As we move further away from Meteor this will become a bit more feasible.  I'd recommend staying tuned to issues like this so we don't have the issues fragmented
