### ISSUE TITLE
Users cannot login from web and mobile at the same time.

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#15434]
**This is likely a configuration issue rather than a bug.**

I could not find any setting to change this functionality to allow users to be logged in from more than one "device" at a time. Please point me toward the appropriate setting/configuration to enable this functionality.

We are using RC v1.3.2 on RHEL, Node 8.11.4, MongoDB 3.4.23.

1. user logs into the RC mobile app
2. user logs into RC via their browser
3. user attempts to send a message (or perform any action) in the mobile app
4. user receives the following messages; app shows "Disconnected" status:

>Your session is invalid. Please sign in again.
>Sorry, an error has occurred, please try again.

1. user logs in again in the mobile app
2. user immediately receives the same messages; app shows "Disconnected" status

**Note:** We are proxying RC through NGINX -- not sure if this could potentially make a difference. All RC functionality appears to work fine in the app, including websockets.

**Comment by reetp** [comment]
@rocket-cat close

> **This is likely a configuration issue rather than a bug.**

In which case this is the appropriate route for support:

https://rocketchat.github.io/docs/contributing/reporting-issues/
https://rocketchat.github.io/docs/getting-support/

Most likely a configuration or an app issue. (We have users logged in with both at the same time without an issue on both Android and iOS with Nginx)

Note you have made no mention of any details regarding the mobile app version/OS

It may make more sense to do some further testing to try and narrow down your issue and follow up in the appropriate app repo.
