### ISSUE TITLE
Too easy to accidentally leave channels

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#1543]
I and my coworkers have been finding that it's too easy to accidentally leave a channel in Rocket. The 'exit' button is right inside the channel bar where one would naturally click to view the channel, it's at the far right end which is a natural place to click to bring the channel up, AND it doesn't appear until your mouse is right on top of it, so you don't realize you're going to hit it.

This is _especially_ bad with private channels, where you can accidentally remove yourself with one click and it's not possible to undo. (This is made double-extra bad by #1414 which means that you can't even get someone else from the channel to invite you back in -- if the channel owner is on a two-week vacation, say, you're REALLY screwed.)

Leaving a private channel should DEFINITELY require confirmation since you cannot undo it. Leaving any channel should probably take more than one click, but it's not as urgent. (On Slack, leaving a channel is in the channel menu, it's not available in the main view at all -- this makes sense to me because it's not something you'd expect to do frequently.)

Thanks!

**Comment by gwillen** [comment]
Update: I'm not even making this up, I didn't do this on purpose: The creator of a private channel just accidentally left it. Now we seem to be really stuck because nobody has invite powers... what do we do :-(

**Comment by rustyrussell** [comment]
+1.  I just tried to click on the [1] notification number to dismiss it (despite multiple scrollback, it didn't clear), and left my own private group!  So, +1 from me while I unscrew myself.

**Comment by marceloschmidt** [comment]
I completely agree! Let's have the leave room in the channel settings tab, what do you think?

**Comment by graywolf336** [comment]
@marceloschmidt Both of those sound good to me. The leave room in the channel settings tab will pave the way for using it to promote people to channel moderators (if we get to that eventually), channel notifications preferences, and maybe other things as well.

**Comment by marceloschmidt** [comment]
Yes! And we'll call that Channel Info instead of Channel Settings. Makes more sense.

**Comment by graywolf336** [comment]
:+1: even display who the current channel owner is just for having that information there.

**Comment by richardwlu** [comment]
:+1:

**Comment by soenkef** [comment]
I'm new here and I'm excited testing rocket.chat. I''ve installed my own rocket server and tried many features. It makes me crazy leaving my own room. In this case the next member in that group may be chosen as new admin with rights to add users.

**Comment by rockneverdies55** [comment]
:+1:

**Comment by fduraibi** [comment]
:+1: 

i just clicked on the Unread counter, and poof.... :(

![acc-bug3](https://cloud.githubusercontent.com/assets/432460/12076139/65881fc4-b16d-11e5-921f-c84f6b8f231b.png)

**Comment by magro** [comment]
+1

**Comment by graywolf336** [comment]
Should we move this to the settings tab of the channel?

**Comment by soenkef** [comment]
It would be great when you would be asked and must confirm whean leaving the channel or group. I think it is a feature for templates.

**Comment by magro** [comment]
Yes, a confirmation would be great. The same applies to "hide room". Moving these options to the settings tab might be a pragmatic solution if it's much easier than adding the confirmation.
