### ISSUE TITLE
Ubuntu deployment behind reverse proxy issue

### ISSUE THREAD

**Issue by dariuske** [RocketChat/Rocket.Chat#15431]
### Description:
Hi, I'm new to rocket chat and I recently tried deploying the server on an Ubuntu 18.04 server behind nginx as a proxy. I followed the guidelines from [Rocket.Chat Ubuntu](https://rocket.chat/docs/installation/manual-installation/ubuntu/) and [Configuring SSL](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/)

### Steps to reproduce:

1. Rocket chat conf
`
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://localhost:3000 PORT=3000
[Install]
WantedBy=multi-user.target

`
2. Nginx conf
`

# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

# HTTPS Server
server {
    listen 443;
    server_name mysite.com;

    # You can increase the limit if your need to.
    client_max_body_size 200M;

    error_log /var/log/nginx/rocketchat.access.log;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}

`

### Expected behavior:

With this configurations, I expect to visit https://mysite.com and be able to setup the server

### Actual behavior:
When I open https://mysite.com, I get an error during setup https://mysite.com/setup-wizard/
![Screenshot from 2019-09-24 09-21-36](https://user-images.githubusercontent.com/23254732/65487120-da521900-deae-11e9-8142-48728e46fe4e.png)
![Screenshot from 2019-09-24 09-16-24](https://user-images.githubusercontent.com/23254732/65487135-e0e09080-deae-11e9-9c46-a7bafc0eab55.png)
blurred **https://mysite**

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Ubuntu 18.04.3, 2GB RAM, 10GB, Nginx 1.14.0
- Deployment Method: Manual installation
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4
- MongoDB Version:  4.0.12

### Additional context
I tried to add open-wide cors headers to the nginx conf to no success.

**Comment by reetp** [comment]
V2.2.0? Are you sure?

How did you setup your mongo db?

What is in your rocketchat log?

**Comment by dariuske** [comment]
Sure. I even updated to the latest version. Still same error.

**Comment by reetp** [comment]
Hmmmmm. I strongly suspect this is a configuration/support issue and not a bug and you should probably following this:

https://rocket.chat/docs/getting-support/

> I even updated to the latest version.

Hang on. You originally said you were on 2.2.0

Care to show me where you can see 2.2.0 here?

https://github.com/RocketChat/Rocket.Chat/tags

And then you say you even updated to the latest version. Which is 2.0.0 (2.1.0 is still RC)

So I think that we may be missing some accurate details.

Please go back to the start and describe carefully exactly what you have done, step by methodical step and the output form each.

You really need to provide some logs so we can see if you have any errors that might suggest a problem.

Please don't paste long logs here - use pastebin or a gist so you don't block up this issue and make it hard to read thanks.

**Comment by dariuske** [comment]
My bad. The version I installed was 2.0.0, slighlty over a week ago. Nevertheless, there's a chance another newbie to rocket chat will run into an issue. Following the manual deployment guides didn't work for me.
I opted for docker, which I managed to have an instance up and running in less than 5mins.

**Comment by reetp** [comment]
Glad you have it sorted.

> For instance changing the mongodb engine and replication stops stops mongod from running; at least for vs 4.0.12 amongst many more issues.

Not sure what you mean here. You need to setup the engine and then replication as per the documentation, but it shouldn't 'stop' Mongo which should not be running until **after** you configure it.

Can you please explain carefully what you did so the documentation can be modified if necessary?

**Comment by dariuske** [comment]
In this [install guide](https://rocket.chat/docs/installation/manual-installation/ubuntu/), when you set the mongo engine `sudo sed -i "s/^#  engine:/  engine: mmapv1/"  /etc/mongod.conf` and **mongod** service would stop on restarting. Leaving the default conf worked, at least for me.

**Comment by reetp** [comment]
@rocket-cat close

This seems likely to have been a configuration issue, not a bug.

> In this [install guide](https://rocket.chat/docs/installation/manual-installation/ubuntu/), when you set the mongo engine `sudo sed -i "s/^# engine:/ engine: mmapv1/" /etc/mongod.conf` and **mongod** service would stop on restarting. Leaving the default conf worked, at least for me.

All that does is change the mongo engine from WiredTiger back to MMAPv1, which is the current recommended default for the time being. In itself that change won't do anything, so it has to be something else.

i.e. If you had started mongo BEFORE you had made that change, and then restarted it again AFTER then you may well have an issue (I had this once myself). Mongo initialises itself, and you can't then go back. You have to start over with a clean install of mongo.

As there are no logs, it is hard to tell more.
