### ISSUE TITLE
Url capturing is not working properly in markdown text

### ISSUE THREAD

**Issue by ThangHuuVu** [RocketChat/Rocket.Chat#15438]
### Description:
When send messages that contain markdown link, the urls captured in the payload is incorrect. They have a ")" character which is suppose to be a part of the markdown.

### Steps to reproduce:

1. Go to rocket.chat instance, send a markdown text like:

- Title: [test]
- Url: (http://example.com/example)

2. Check on the returned object payload's urls

### Expected behavior:

```
{
  ...
  "msg": "[test](http://example.com/example)",
  "urls": [
      {
        "url": "http://example.com/example"
      }
  ],
  ...
}
```
### Actual behavior:
```
{
  ...
  "msg": "[test](http://example.com/example)",
  "urls": [
      {
        "url": "http://example.com/example)"
      }
  ],
  ...
}
```

Screenshot: 
<img width="359" alt="Screen Shot 2019-09-25 at 5 58 52 PM" src="https://user-images.githubusercontent.com/31528554/65596726-aca9c480-dfc1-11e9-92a3-32eccf0ecfd6.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.0
- Operating System: Mac OS Mojave 10.14.4
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 10.15.3
- MongoDB Version: 4.0.11
--

### Additional context
NA

### Relevant logs:
NA

**Comment by reetp** [comment]
Please follow the reporting guidelines.

https://rocket.chat/docs/contributing/reporting-issues/

Test on latest - currently at least v2.0.x and even better on the dev version.

If you are using docker the node version should be 8.11.4 via Admin/Info ??

**Comment by ThangHuuVu** [comment]
@reetp I will try again for the latest version, thank you for the quick response.

**Comment by meomay503** [comment]
I've tested on the develop branch and this issue still appears.
