### ISSUE TITLE
No notification in parent channel on new discussions

### ISSUE THREAD

**Issue by nicowiggersiv** [RocketChat/Rocket.Chat#15430]
When I am in channel A and create a new discussion channel in there by using the plus sign in the text input:

![image](https://user-images.githubusercontent.com/25098345/65486841-d372d880-dea5-11e9-85c6-5f876e6af7e7.png)

users in channel A, that are not added to the new discussion, don't get a notification. Only by watching channel A a user is able to see that there is a new discussion and may join it. From my point of view a new discussion should be handled as a message from the notifications point of view.

Rocketchat version: 1.3.2

**Comment by MartinSchoeler** [comment]
Currently, the discussions are treated like normal messages without any mentions, maybe there should be a preference to notify me if anyone starts a discussion on a channel I belong to?

**Comment by nicowiggersiv** [comment]
Can't confirm that new discussions are treated like messages without mentions. At least for version 1.3.2. If someone creates a new discussion via the "+" button no new message is shown on the parent channel (I'm in this channel) and no web notification is generated. Of course I get notification from the new discussion channel if I have been invited there. However, I would expect to get a notification similar to if someone would just have posted a message in the parent channel.

**Comment by nicowiggersiv** [comment]
We are now on 2.1.1. Same issue here.
