### ISSUE TITLE
MeteorJS DDP with RocketChat

### ISSUE THREAD

**Issue by neilakoh** [RocketChat/Rocket.Chat#1544]
Hi, I am currently creating a Meteor DDP login page that allows user to login to rocket chat via that login page I created. Here is my code:

var conn = DDP.connect('http://localhost:3000');
Accounts.connection = conn;
Meteor.users = new Meteor.Collection("users", conn);
Accounts.users = Meteor.users;

if (Meteor.isClient) {
  conn.subscribe("users");
}

if (Meteor.isServer) {
	Meteor.startup(function () {
      Meteor.publish("users", function () {
        return [Meteor.users.find(), Accounts.users.find()];
      });
  });
}

localhost:3000 is where my login app is located. I have successfully sync the user to the rocket chat; however, all I can see is the history, I have no permission to change the settings, and the other features are gone. Please help. I added the code above inside the rocket chat app folder. Thank you.

**Comment by marceloschmidt** [comment]
I didn't understand your actual question. Is this Rocket.Chat related issue, or is this a general meteor programming question?

**Comment by neilakoh** [comment]
Not really a meteor issue. My goal is, I am going to use my meteor login application to login to rocket chat.

Using the Meteor DDP I am now able to link my Meteor login app to rocket which means I can now login to rocket chat via my meteor login application.

The issue is, there are features missing and the permission to change the settings are gone in rocket chat after logging in via DDP.

The code above is what I used to integrate my user collection to rocket chat so that rocket chat will use my user to collection to authenticate login.

**Comment by engelgabriel** [comment]
hi @neilakoh

Please ask for this kind of support at our https://demo.rocket.chat/ as we try to keep this issue list as a todo list.
