### ISSUE TITLE
Rocket.Chat v2.1 wont run on new build of Ubuntu 18.04

### ISSUE THREAD

**Issue by ealbers** [RocketChat/Rocket.Chat#15440]
### Description:

After I follow the developer installation instructions I get the following when I do a meteor npm start:

Killedcessing files with rocketchat:vers...  |
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! Rocket.Chat@2.1.0-rc.0 start: `meteor`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the Rocket.Chat@2.1.0-rc.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Killedcessing files with rocketchat:vers...  |
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! Rocket.Chat@2.1.0-rc.0 start: `meteor`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the Rocket.Chat@2.1.0-rc.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Steps to reproduce:

Install fresh Unbuntu 18.04
Follow developer instructions

### Expected behavior:

Rocket.Chat to run

### Actual behavior:

Error

### Server Setup Information:

- Version of Rocket.Chat Server: Rocket.Chat-2.1.0-rc.0
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 6.11.3
- MongoDB Version: 4.0.6

**Comment by reetp** [comment]
Please list the steps you took.

Are they exactly the same as here?

https://rocket.chat/docs/developer-guides/quick-start/

What output did you get after each command? (Put long log snippets on pastebin or a gist please).

"Note that there is no need to install mongo, nodejs, or npm on the base operating system."

So I'm not sure where your node version comes from?

**Comment by ealbers** [comment]
Ok, I will start from scratch and redo based on the document and send outputs to pastbin

**Comment by reetp** [comment]
Cool. Just be slow and methodical and write it all down as you go so we can see exactly what you  did.

**Comment by ealbers** [comment]
See Below:

Install tools required

sudo apt install g++ build-essential git curl python-minimal
https://pastebin.com/YsCjpJCP

Install meteor

curl https://install.meteor.com/ | sh
https://pastebin.com/6LGyFyW4

There is no need to install node or npm, as meteor already includes them. Verify by:

meteor node -v
v8.15.1
meteor npm -v
6.9.0

Get rocket.chat code

git clone https://github.com/RocketChat/Rocket.Chat.git

sysadmin@ubuntu:~$ git clone https://github.com/RocketChat/Rocket.Chat.git
Cloning into 'Rocket.Chat'...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 188074 (delta 48), reused 50 (delta 14), pack-reused 187936
Receiving objects: 100% (188074/188074), 133.50 MiB | 7.70 MiB/s, done.
Resolving deltas: 100% (124657/124657), done.
sysadmin@ubuntu:~$


Install modules

cd Rocket.Chat

meteor npm install
https://pastebin.com/3JLgKJGx

Start building (can take 5 minutes, please be patient)

meteor npm start
https://pastebin.com/SjXQuL54

contents of log file
https://pastebin.com/cjJFtGF7

**Comment by sampaiodiego** [comment]
The error seems to be `ENOMEM` .. and indeed the memory requirements for building Rocket.Chat since we updated Meteor to 1.8.1 has increased.. We couldn't build on CircleCI anymore, which has 4GB of RAM.

To circumvent that we added a step to build [an almost empty project](https://github.com/RocketChat/Rocket.Chat/blob/develop/.circleci/config.yml#L136) then after we can build the entire project.

**Comment by ealbers** [comment]
yes I had not had an issue building previous versions, is there a step I need to do to create the "empty" project first?

**Comment by sampaiodiego** [comment]
basically what we did was:
```
            echo "" > server/main.js
            echo "" > client/main.js
            meteor build --server-only --debug --directory /tmp/build-temp
            git checkout -- server/main.js client/main.js
```

you can see what we do to build on CircleCI at https://github.com/RocketChat/Rocket.Chat/blob/develop/.circleci/config.yml

**Comment by ealbers** [comment]
That resolved it, thank you.

**Comment by reetp** [comment]
@rocket-cat close

And closing.
