### ISSUE TITLE
email confirmation not working

### ISSUE THREAD

**Issue by adrianb88** [RocketChat/Rocket.Chat#1545]
Hi all.

As an admin I activated the email confirmation function. I logged out but afterwards I couldn't log in again:
1. It requests from me an email for verification
2. I am not receiving any email confirmation although I typed in my correct email address (also checked my spam)
3. which means I cannot login in again as an admin :( 
I have no access at all...

Any ideas or help? 
Regards.

**Comment by k0nsl** [comment]
Hi @adrianb88 

Please see this issue discussed here: #1502

**Comment by tholu** [comment]
And especially here to regain access: https://github.com/RocketChat/Rocket.Chat/issues/766#issuecomment-139656453

This can be closed as duplicate then.
