### ISSUE TITLE
[Android v3.5.2] App crashing on start

### ISSUE THREAD

**Issue by nikolatasikj** [RocketChat/Rocket.Chat#15454]
### Description:

Application can't be opened, it's crashing. Version is 3.5.2 updated from play store as beta tester. First time after update it worked, but after closing it and starting it again it's crashing. Also, when i delete cache and data and open it it's okay, but after closing not working anymore.

### Steps to reproduce:

1. Just click the icon to open app

### Expected behavior:

Application to be opened with shown list of channels

### Actual behavior:

White screen appear for 2 seconds, after that application is crashing and every background activity is closed (or it's not even started).

### Server Setup Information:

- Version of Rocket.Cha: 3.5.2 - beta 
- Operating System: Android EMUI 9.1.0

**Comment by reetp** [comment]
Please close this and open in the appropriate repo

https://github.com/RocketChat/Rocket.Chat.Android
