### ISSUE TITLE
Open file on extension rule after download

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#15453]
This not issuie, this feature request... i do not know how it make here.

### Description:

able to open downloaded files in direct private and channel

### Steps to reproduce:

1. tap on file that buddy upload
2. tap save on save-dialog
3. have to go in explorer(finder,or different file manager) were file save and open it

### Expected behavior:

Add second button to open file after it already downloaded

### Actual behavior:

After tap on file twice open save dialog again

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Centos 7
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.x

**Comment by MartinSchoeler** [comment]
Please reopen this in the appropriate repository, https://github.com/RocketChat/feature-requests Thanks!
