### ISSUE TITLE
S3 fileupload and "Message too long. Send it as an attachment instead?" functionality leads to "SignatureDoesNotMatch"

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#15450]
### Description:

When trying to write a very long message, the mechanism "Message to long, send it as attachement instead?" applies. So the message is uploaded as an attachment and ends up in S3. If I now click on this file in the chat, I get the error message: "SignatureDoesNotMatch".

### Steps to reproduce:

1. Enter a long text message
2. Click upload as attachement (S3 file upload backend)
3. Click on message
4. xml error message appears

### Expected behavior:

Uploaded Attachement should be readable.

### Actual behavior:

Error Message.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Yes
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

### Additional context

Complete error message:

`
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided.</Message><Resource>/rocketchat/aLeJfu9uZyEHc4agi/uploads/HxSazvfL5T6vRHP8KHxSazvfL5T6vRHP8K/HxSazvfL5T6vRHP8K/FsXc56rCCZPDPMvzY</Resource><RequestId>8413230980982811309</RequestId></Error>
`

**Comment by MrPoint1400** [comment]
+1
