### ISSUE TITLE
Username or Email not updated from SAML.

### ISSUE THREAD

**Issue by BarnumD** [RocketChat/Rocket.Chat#15456]
### Description:

This is similar to Issue #6481, and PR #14275.  However, those did not quite fix the issue for me.
We have connected our SAML environment to rocket chat to allow users to log in.  However, the current configuration doesn't allow us to choose a globally unique and/or immutable identifier as primary ID (perhaps it's called Immutable field name) in Rocket.Chat.  The latest implementation in #14275 allows you to choose between username and email for Immutable field name, but both of those can change at times - and should.

We have a staff ID that is unique across all of our organizations and I believe many other organizations would have this as well.  This ID doesn't change even if someone gets married or changes their name.  Is there a way to use that identifier to identify the rocket chat user account?  

### Steps to reproduce:

1. Sign in with saml.
2. change your username or email in saml environment.
3. Sign in with saml.

### Expected behavior:

A user should be tied to an immutable user id.  That field should be the Immutable field name.  Username and email should update from field taken from saml.  This is because usernames and emails are expected to change when a person changes their name or marries.

### Actual behavior:

Right now If I manually change both the username and email field to 'foo' and 'bar', only the field that is NOT in Immutable field name (whether username or email) updates from SAML to the correct value.  I would expect the same thing to happen if I actually change my name in our personnel system which backs our SAML.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Official Docker Container on Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: unknown
- NodeJS Version: unknown
- MongoDB Version: 4.0

### Additional context

One of my concerns is that I don't want our users to see other user's staff ID - especially when they type @ to look up a person.  I would like that value to remain as the username.

**Comment by Karreg** [comment]
@BarnumD was the issue fixed for you? This issue is closed with version 3.4, but I still can't choose any field other than email and username as immutable field in version 3.10.
So I'm still facing this issue...
Also, field mapping is not working as expected... :/

**Comment by BarnumD** [comment]
I don't currently have a rocket chat instance running to test.
