### ISSUE TITLE
set proxy for fcm

### ISSUE THREAD

**Issue by cygnusm** [RocketChat/Rocket.Chat#15468]
Hi,our server's location is  iran and we can not use fcm service without proxy,
I appreciate if you can tell me how can i set proxy for fcm in Rocket.chat.
we build our own android app ,set enable gateway to false and add  push gcm project number and gcm api key
**server info**
server version:2.0.0
os:ubuntu 18

**Comment by reetp** [comment]
@rocket-cat close

Github is for issues, not support.

Search here for information eg:
https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+proxy+fcm

Read here for how to get support:
https://rocket.chat/docs/getting-support/
