### ISSUE TITLE
using rocketchat livechat with multiple bots

### ISSUE THREAD

**Issue by aermike** [RocketChat/Rocket.Chat#15463]
Hi 
This is not an issue
I ask if it's possible to implement livechat with multiple domains.
Example: I want to implement an boot for shoe and another boot for parfums, on same rocketchat server, or on 2 sessions (live help has only one link, in generic room for visitors)
I want, if it,s possible to have multiple room, or posibility to declare multiple domains for livechat), or implement livechat session/server session(if i have 2 servers ruun on port 3000 and 3001) make posibility to have 2 livechat session (with port 3000 and 3001)
Thank you

**Comment by reetp** [comment]
@rocket-cat close

Github is only for issues/bugs.

Please read this on how to get support.

https://rocket.chat/docs/getting-support/
