### ISSUE TITLE
Documentation for Federation needs an update

### ISSUE THREAD

**Issue by navigateitservices** [RocketChat/Rocket.Chat#15467]
### Description:

The current Documentation describes adding an SRV Record as _rocketchat._tcp
The actual code requires _rocketchat._https or _rocketchat._http.
( Rocket.Chat/app/federation/server/lib/dns.js )

### Steps to reproduce:

View RocketChat Documentation on Federation
[https://rocket.chat/docs/administrator-guides/federation/#federation](url)

### Expected behavior:

View the correct information 

### Actual behavior:

See outdated information on how to set up srv dns entry.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Ubuntu 
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.12

**Comment by reetp** [comment]
@rocket-cat close

Please open a documentation bug (or even better do a PR from the link at the bottom of the relevant page)

https://github.com/RocketChat/docs
