### ISSUE TITLE
Can't connect to livechat wss after v2.1.0

### ISSUE THREAD

**Issue by Gedmcq** [RocketChat/Rocket.Chat#15466]
After upgrade to last version I can't use live chat (both widget and /livechat interfaces) with
502 response by wss:
WebSocket connection to 'wss://*domainName*//websocket' failed: Error during WebSocket handshake: Unexpected response code: 502.

Maybe you know about some breaking changes in domain/cors/access policy in last release?

**Comment by mdpolasek** [comment]
We have the same issue. the livechat cannot connect to the websocket. Error code 502 in web console.

**Comment by mdpolasek** [comment]
I noticed that the websocket URL looks like this wss://<domain>**//**websocket. Please notice the two slashes. I changed the ROOT_URL from http://localhost to http:///localhost:3000 and the issue went away.

Note: I'm running rocket chat 2.1 in docker using the official image from here: https://hub.docker.com/r/rocketchat/rocket.chat
