### ISSUE TITLE
chat.delete not working with direct chat

### ISSUE THREAD

**Issue by Perflyst** [RocketChat/Rocket.Chat#15464]
### Description:

REST API chat.delete not working with direct chats

### Steps to reproduce:

1. Get roomId of direct chat via im.list
2. Get msgId of direct chat via im.history

`curl -H "X-Auth-Token: AUTH TOKEN" -H "X-User-Id: myID" https://rc.domain.tld/api/v1/chat.delete -d '{ "roomId": "room ID of direct chat", "msgId": "a message ID" }`

### Expected behavior:

`{"success":true}`

### Actual behavior:

`{"success":false,"error":"Match error: Missing key 'msgId'"}`

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0
- Operating System: Debian 10
- Deployment Method: tar

**Comment by MarcosSpessatto** [comment]
Hey @Perflyst, probably what are causing this error is, you are not send with your request the JSON headers: `-H "Content-type:application/json"`. Can you please try with this header? More info you can find [here](https://rocket.chat/docs/developer-guides/rest-api/chat/delete/).

**Comment by Perflyst** [comment]
There we go... Yes, sorry, was the issue.
