### ISSUE TITLE
Audio Video call button not working and microphone button is missing for browsers in windows and mac os.

### ISSUE THREAD

**Issue by AliyevH** [RocketChat/Rocket.Chat#15479]
### Steps to reproduce:

1. Settings
2. Message
3. Audio Message 
4. Audio Recorder Enabled
5. True or False
### Expected behavior:
Expected to see microphone button in direct messaging

### Actual behavior:

1. not working for windows os and mac os. and doesn't show microphone button in browser (chrome, firefox, ie, safari)
2. in browser site settings permissions are greyed out 

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: centos 7
- Deployment Method: fresh install on centos 7
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: v4.0.12

### Additional context
Relevant logs:

<img width="529" alt="Screen Shot 2019-10-01 at 10 51 02 PM" src="https://user-images.githubusercontent.com/5507950/65991228-09175300-e49e-11e9-852c-734dc7ad448f.png">
<img width="895" alt="Screen Shot 2019-10-01 at 10 51 15 PM" src="https://user-images.githubusercontent.com/5507950/65991230-09175300-e49e-11e9-93b7-cb1c36c4da7b.png">
<img width="1387" alt="Screen Shot 2019-10-01 at 10 52 11 PM" src="https://user-images.githubusercontent.com/5507950/65991269-22200400-e49e-11e9-81d3-50811517e4d7.png">
<img width="705" alt="Screen Shot 2019-10-01 at 10 52 50 PM" src="https://user-images.githubusercontent.com/5507950/65991325-37952e00-e49e-11e9-8bf2-85b42de71fca.png">
<img width="680" alt="Screen Shot 2019-10-01 at 10 50 49 PM" src="https://user-images.githubusercontent.com/5507950/65991227-09175300-e49e-11e9-9680-0eb2cdc298f6.png">

make audio video call shows error in browser console (Uncaught TypeError: navigator.getUserMedia is not a function)

**Comment by anuwan94** [comment]
I have the same issue on an updated Arch Linux host : 
```

Nov 25 19:07:52 arch rocketchat[1098]: ➔ +-------------------------------------------+
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |               SERVER RUNNING              |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ +-------------------------------------------+
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |                                           |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |  Rocket.Chat Version: 2.2.1               |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |       NodeJS Version: 8.16.2 - x64        |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |      MongoDB Version: 4.2.1               |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |       MongoDB Engine: wiredTiger          |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |             Platform: linux               |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |         Process Port: 3000                |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |             Site URL: https://localhost/  |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |     ReplicaSet OpLog: Enabled             |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |          Commit Hash: e7334ab4da          |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |        Commit Branch: HEAD                |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ |                                           |
Nov 25 19:07:52 arch rocketchat[1098]: ➔ +-------------------------------------------+
```

Verified already on Firefox / chrome latest versions on multiple clients.
Strangely enough , the only client that works is the one in Android.
Of course both Audio/Video recorders are enabled.

**Comment by flazeh** [comment]
Hello, 
I was having similar issue. 
It was solved checking the Files upload section. Try to reset or clear the media file type. It seems to be connected with the send/receive of the audio/video messages. 
If you clear the field, careful with the security involved.

**Comment by BoJackBR** [comment]
Hi guys.

I have the same issue. 
I have a new installation of Rcketchat and even enabled, does not show the voice message icon
![image](https://user-images.githubusercontent.com/35930902/94151833-3c8e8280-fe51-11ea-97a5-eff4ef88b05f.png)
![image](https://user-images.githubusercontent.com/35930902/94151891-4fa15280-fe51-11ea-9de5-72c6866d1948.png)

**Server Setup Information**
Version of Rocket.Chat Server: 3.6.2
Operating System: Ubuntu 20.04.1 LTS
Deployment Method: snap
Number of Running Instances: 1
NodeJS Version: v12.16.1
MongoDB Version: 3.6.14

**Comment by patrickdriva** [comment]
Hi there. Same here! Any tips how to solve it?

**Comment by BoJackBR** [comment]
The audio button only appears when the server is **HTTPS**. As HTTP the button does not appear.
I discovered by chance

**Comment by patrickdriva** [comment]
> The audio button only appears when the server is **HTTPS**. As HTTP the button does not appear.
> I discovered by chance

Thanks! That was the problem. Now its working fine!!
