### ISSUE TITLE
rocket chat stops 

### ISSUE THREAD

**Issue by aermike** [RocketChat/Rocket.Chat#15474]
After Upgrade at last version of server I have this error, and server stops

### Description:

 Exception while invoking method 'ignoreUser' { Error: Match error: Expected string, got undefined     at check (packages/check/match.js:36:17)     at MethodInvocation.ignoreUser (server/methods/ignoreUser.js:8:3)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:62:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43   message: 'Match error: Expected string, got undefined',   path: '',   sanitizedError:     { Error: Match failed [400]     at errorClass.<anonymous> (packages/check/match.js:91:27)     at new errorClass (packages/meteor.js:655:17)     at check (packages/check/match.js:36:17)     at MethodInvocation.ignoreUser (server/methods/ignoreUser.js:8:3)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:62:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43      isClientSafe: true,      error: 400,      reason: 'Match failed',      details: undefined,      message: 'Match failed [400]',      errorType: 'Meteor.Error' },   errorType: 'Match.Error' } 

### Steps to reproduce:

1. Administration
2. Logs
3. 

### Expected behavior:

My expectation is server working
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: CentOS
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.9

### Additional context

We use AD for authenticate users
<img width="569" alt="rocket" src="https://user-images.githubusercontent.com/4247309/65949490-f7559180-e444-11e9-83c3-295b307cc666.PNG">

**Comment by reetp** [comment]
https://rocketchat.github.io/docs/contributing/reporting-issues/

Read the whole of the above document. Upgrade from what version to what version? What steps did you take? Please be far more accurate.  No one will help you otherwise.

Check your engine versions:

https://github.com/RocketChat/Rocket.Chat/releases/

2.1.0 - Engine versions

Node: **8.15.1**
NPM: **6.9.0**
MongoDB: 3.4, 3.6, 4.0

**Comment by aermike** [comment]
update from 1.3.1 to 2.1.0
No push notification
Steps to upgrade are:
curl -L https://releases.rocket.chat/latest/download -o rocket.chat.tgz
tar zxvf rocket.chat.tgz
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install

**Comment by aermike** [comment]
Version | 2.1.0
-- | --
1.6.0
161
October 1, 2019 1:01 PM
May 2, 2018 11:54 AM
4 hours, 7 seconds
tPxYzmQq3EbZPsFxG
10008
3
Enabled

**Comment by aermike** [comment]
<img width="538" alt="rocket" src="https://user-images.githubusercontent.com/4247309/65958732-caab7500-e458-11e9-94dc-4e129b44bfef.PNG">

**Comment by aermike** [comment]
I will update node to 8.15
And post message
