### ISSUE TITLE
MongoError: ns not found

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#15485]
### Description:

Upgraded to our Rocket Chat to version 2.0.0, this morning.  When starting up the two Rocket Chat instances, I noticed several instances of this error in the logs:

Oct  2 05:44:42 chat rocketchat1: === UnHandledPromiseRejection ===
Oct  2 05:44:42 chat rocketchat1: { MongoError: ns not found
Oct  2 05:44:42 chat rocketchat1: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
Oct  2 05:44:42 chat rocketchat1: at authenticateStragglers (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:504:16)
Oct  2 05:44:42 chat rocketchat1: at Connection.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:540:5)
Oct  2 05:44:42 chat rocketchat1: at emitMessageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:310:10)
Oct  2 05:44:42 chat rocketchat1: at Socket.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:453:17)
Oct  2 05:44:42 chat rocketchat1: at emitOne (events.js:116:13)
Oct  2 05:44:42 chat rocketchat1: at Socket.emit (events.js:211:7)
Oct  2 05:44:42 chat rocketchat1: at addChunk (_stream_readable.js:263:12)
Oct  2 05:44:42 chat rocketchat1: at readableAddChunk (_stream_readable.js:250:11)
Oct  2 05:44:42 chat rocketchat1: at Socket.Readable.push (_stream_readable.js:208:10)
Oct  2 05:44:42 chat rocketchat1: at TCP.onread (net.js:597:20)
Oct  2 05:44:42 chat rocketchat1: ok: 0,
Oct  2 05:44:42 chat rocketchat1: errmsg: 'ns not found',
Oct  2 05:44:42 chat rocketchat1: code: 26,
Oct  2 05:44:42 chat rocketchat1: codeName: 'NamespaceNotFound',
Oct  2 05:44:42 chat rocketchat1: operationTime: Timestamp { _bsontype: 'Timestamp', low_: 16, high_: 1570013082 },
Oct  2 05:44:42 chat rocketchat1: '$clusterTime':
Oct  2 05:44:42 chat rocketchat1: { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 16, high_: 1570013082 },
Oct  2 05:44:42 chat rocketchat1: signature: { hash: [Object], keyId: [Object] } },
Oct  2 05:44:42 chat rocketchat1: name: 'MongoError',
Oct  2 05:44:42 chat rocketchat1: [Symbol(mongoErrorContextSymbol)]: {} }
Oct  2 05:44:42 chat rocketchat1: ---------------------------------
Oct  2 05:44:42 chat rocketchat1: Errors like this can cause oplog processing errors.
Oct  2 05:44:42 chat rocketchat1: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Oct  2 05:44:42 chat rocketchat1: Future node.js versions will automatically exit the process

### Steps to reproduce:

1.Upgrade from 1.3.2 to 2.0.0
2. Restart the Rocket Chat instances
3. tail  the logs

### Expected behavior:

No mongo errors should be presented

### Actual behavior:

MongoError: ns not found

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.14

### Additional context

It might be interesting to add that we have two Rocket Chat instances running on this server.  The services are called rocketchat1 and rocketchat2.  All of the mongo errors about "ns not found" occurred on the rocketchat1 service.  This did not happen on the rocketchat2 service. 

Also, both services did start up.  And it looks like Rocket Chat is working correctly.

**Comment by dcorrigangoempyrean** [comment]
Same error, not seeing any strange behavior that suggests a failure.
Happens on 2 nodes out of 3.

=== UnHandledPromiseRejection ===
{ MongoError: ns not found
    at /var/www/Rocket.Chat3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/var/www/Rocket.Chat3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/var/www/Rocket.Chat3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/var/www/Rocket.Chat3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/var/www/Rocket.Chat3/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  ok: 0,
  errmsg: 'ns not found',
  code: 26,
  codeName: 'NamespaceNotFound',
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 261, high_: 1570651719 },
  '$clusterTime': 
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 261, high_: 1570651719 },
     signature: { hash: [Object], keyId: 0 } },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================

Previous version 1.3.2 - no error
RC 2.1.0
OS Ubuntu Server 16.04
Method: Tar/manual
Number of instances: 3
Oplog enabled
Node 8.11.4
MongoDB: 3.6.12

**Comment by LuluGO** [comment]
Does this change if you add the other members of the replicaset to the hosts files?

**Comment by McpCyber** [comment]
Hello . i have the same problem in my Rocket Chat server and MongoDB. the main problem is file upload . i can't find workaround.
https://github.com/RocketChat/Rocket.Chat/issues/16000

**Comment by McpCyber** [comment]
Hello . i have the same problem in my Rocket Chat server and MongoDB. the main problem is file upload . i can't find workaround.

**Comment by McpCyber** [comment]
Hey the Problem has been fixed.
in General Settings , URL must not be localhost

**Comment by mddvul22** [comment]
In our General Settings, the url is not localhost.

**Comment by 564064202** [comment]
> workaround

hi,what's your version. I met this bug too with 2.4.11,is it fatal?

**Comment by mddvul22** [comment]
Maybe the RC devs can make an official statement here whether this error can be ignored, or not?  I will check on our next upgrade, to be sure, but I believe we continue to get this error message on every upgrade.  Having a bot close it, just because the devs haven't yet addressed it, doesn't seem the right course of action.

**Comment by ceefour** [comment]
I'm also getting this issue with v3.5.4, running on AWS Fargate (Docker)

**Comment by cuixiaotu** [comment]
I have the same problem and do not know how to deal witeh it,mongo oplog or just General Settings ,let`s have a try.

**Comment by sennewood** [comment]
Error still exists with version 3.8.1

**Comment by PhilThurston** [comment]
Error still exists with 3.9.1

**Comment by ankar84** [comment]
Still exist in 3.18.1

**Comment by ankar84** [comment]
I found in related issues, that this problem occurs only on massive instance load, for example rebuild of all server instances.
If you rebuild 1 instance in a moment - no such error.
Could be related to some connection pool that exceeds of a few instances restart/rebuild. 
Related https://github.com/RocketChat/Rocket.Chat/issues/11692
