### ISSUE TITLE
Read receipts not working

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat#15484]
### Description:

After updating to 2.1.0 the read receipts are not displayed anymore. No checkmark in browser, and only grey checkmarks in the app. No blue checkmarks after a message is read.

Also when showing message info, only the person who send the message is shown in the list.

### Steps to reproduce:

1. Direct chat or group chat
2. open message context menu, select info
3. only the person who wrote the message is shown, no one else, even if the message has been read

### Expected behavior:

* message read receipt shown in info
* blue checkmark in direct chat

### Actual behavior:

* In group chats: only the person who wrote the message is shown, no one else, even if the message has been read
* in direct chats no blue checkmark appears
 
### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.0
- Operating System: 4.19.72-gentoo, Ubuntu 18.04 LTE (tested on two systems)
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.2.0

### Additional context

* could be related to changes in #15316
* **could be a problem on our end because using MongoDB 4.2.0**

### Relevant logs:

Server log when accessing "info":

```
Meteor ➔ method getReadReceipts -> userId: RQySce2mbjTpGyxGt , arguments:  [ { messageId: '4cce12f2-60f4-443f-b253-46043a799eae' } ]
Meteor ➔ method canAccessRoom -> userId: RQySce2mbjTpGyxGt , arguments:  [ 'THG8ez3NKvCi9WoYv', 'RQySce2mbjTpGyxGt' ]
```

**Comment by robopossum** [comment]
I am also experiencing this on
- OS : Debian 9.9
- MongoDB Version : 4.0.11
- NodeJS Version : v8.16.0

**Comment by Yures** [comment]
Same issue.
RC docker 2.1.0
Mongo docker 4.0.11

**Comment by dca-adam** [comment]
I am also experiencing this issue on both my test and prod environments.

- Version of Rocket.Chat Server: 2.1.0
- Operating System: CentOS 7.7.1908
- Deployment Method: tar
- Number of Running Instances: 1 (test and prod are independent instances)
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.14

**Comment by johnbrown-yoti** [comment]
Same issue here.

- Rocket.Chat Version: 2.1.0
- NodeJS Version: 8.11.3 - x64
- MongoDB Version: 3.6.14
- Deployment Method: tar
- Number of Running Instances: 3
- ReplicaSet OpLog: Enabled

**Comment by gennari-dkt** [comment]
Same issue for me.

- Version of Rocket.Chat Server: 2.1.0
- Operating System: Debian 9.9
- Deployment Method: tar
- Number of Running Instances: 1 (test and prod are independent instances)
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

**Comment by bkraul** [comment]
Same issue here with develop (da6025e)

**Comment by bkraul** [comment]
In my case, this problem only happens in *one* DM channel. All the other channels appear to show the read receipts. Any idea how to troubleshoot this?

**Comment by reetp** [comment]
This works in Custom CSS

```
.color-component-color {
    color: red !important;
}

```
Just curious. Why is it seeming to use use the 'Old' Colors and not the 'New' ones?

**Comment by geekgonecrazy** [comment]
@ggazzo @tassoevan just making sure this is on your radar. Seems like css issue

**Comment by bkraul** [comment]
>The reason the blue check isn't showing is that all users haven't read the message.
I am positive all users in the DM conversation have read all messages that should be showing "read" but are not.

**Comment by wreiske** [comment]
> > The reason the blue check isn't showing is that all users haven't read the message.
> 
> I am positive all users in the DM conversation have read all messages that should be showing "read" but are not.

Technically, they have not read the messages because RocketChat isn't saving that they read them. That is what I meant.

**Comment by bkraul** [comment]
Oh I got you. Apologies.

**Comment by phriedrich** [comment]
Thanks to anyone involved fixing this. I can confirm it's working again.

**Comment by wreiske** [comment]
Ahh I think the read receipts are still not working 100% of the time because we have rocket.cat in the channels. rocket.cat isn't reading the messages like it used to :'(

**Comment by reetp** [comment]
> I am only getting the owner of the message showing on the new read receipts in the database.

On 2.1.1 

Is that still true?

"Info" only shows the owner having read a group message even though they must have all read it.

**Comment by Wirone** [comment]
We've updated to 2.1.1 and read receipts are working properly (information modal displays list of users who read the message), but as @wreiske said, bots cause that blue tick is not shown because they don't mark messages as read. Minor issue, but would be great if this could be fixed (maybe just ignore users with `bot` role when determining if tick should be displayed?).

**Comment by rodrigok** [comment]
Good catch @Wirone we will check this.

@wreiske are you sure that your rocket.cat was reading the messages before? The only way I can see this happening today is if you use the APIs to call the readMessages for the rocket.cat user manually via some integration or so.

**Comment by wreiske** [comment]
As it is right now with the latest 2.1.1 update.

When I go back to older messages that were sent during the 2.1.0 read brokenness, I only see one person, the original author. The check is blue.
![dQtmfkIXPF](https://user-images.githubusercontent.com/6295044/67392894-58b5df80-f56f-11e9-993b-a854f68c9dde.gif)

When I go back to older messages, BEFORE 2.1.0 read brokenness, I see everyone that had read the message. The check is blue.
![jaSlWXe8dx](https://user-images.githubusercontent.com/6295044/67393070-a6324c80-f56f-11e9-810b-d47914cd58c1.gif)

In a channel where rocket.cat has been invited in, BEFORE 2.1.0 read brokenness, rocket.cat read all messages after they were sent
![Rocket Chat_ejtNBaILPO](https://user-images.githubusercontent.com/6295044/67393834-302ee500-f571-11e9-9bbf-7d18f1303672.jpg)


-----
Here's a message on 2.1.1 that shows the blue check, however, not everyone has read the message... or at least, the UI isn't showing everyone that has read it.

![image](https://user-images.githubusercontent.com/6295044/67393500-84859500-f570-11e9-97a4-0e92d17cf91b.png)
![image](https://user-images.githubusercontent.com/6295044/67393569-a7b04480-f570-11e9-9401-27a0337ba0d6.png)

There are 16 users in this channel. Why is the check blue?
![image](https://user-images.githubusercontent.com/6295044/67393605-b860ba80-f570-11e9-8849-6c68eb8e1fd4.png)

**Comment by rodrigok** [comment]
@wreiske not sure if [this](https://github.com/RocketChat/Rocket.Chat/pull/15656) will help. I could not reproduce your case of having a message marked as read with just a few participants.

**Comment by GoetheG** [comment]
Shouldn't this issue be merged with all the other same isses? Cause this error still occurs with the latest version.
#4957 
#15656
#15484

**Comment by gerroon** [comment]
I do not see readd receipts with my setup. This used to work but when I do not remember.

```
3.0.12
Apps Engine Version	1.12.0
Database Migration	174
Database Migration Date	April 13, 2020 5:50 PM
Installed at	June 16, 2019 10:29 PM

OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	5.4.0-4-amd64
Node Version	v12.14.0
Mongo Version	4.0.12
Mongo Storage Engine	mmapv1

```

**Comment by kgdemir** [comment]
Read Receipts is Broken again, when we go before 3.6.0 update I can see individual receipts, but after the update it is just showing receipts for sender and current logged in account

**Comment by phriedrich** [comment]
There's already a ticket for the new error: #18689
