### ISSUE TITLE
Create oEmbed Whitelist and Blacklist 

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#1548]
Create an admin setting with the Whitelist and Blacklist for the OEmbed features? Just blocking localhost would not cover all the possible use cases. We can have an default behaviour of blocking localhost ONLY if different from ROOT_URL, so we don't break development servers.

**Comment by WhiteHatTux** [comment]
I would very much like to selectively ignore websites for oEmbed. I want to keep it for most websites, but our hubot posts bitbucket-pushes and vor every commit in the push (which is linked to bitbucket) oembed will try to fetch the sites information filling our chat with always the same link (showing nothing of interest)
![screenshot - 06 02 2016 - 18 54 18](https://cloud.githubusercontent.com/assets/1330544/12868266/34e3062a-cd03-11e5-860f-8db3f543e057.png)

**Comment by rodrigok** [comment]
@WhiteHatTux You can pass `parseUrls: false` within your message from hubot to prevent this.

**Comment by WhiteHatTux** [comment]
Thanks @rodrigok Works like a charm.
