### ISSUE TITLE
Code markdown corruption

### ISSUE THREAD

**Issue by Nepoxx** [RocketChat/Rocket.Chat#15491]
### Description:

Text in code markdown (between 6 backticks) is corrupted (modified) sometimes. I have found a case that corrupts every time.

### Steps to reproduce:

1. Send the following in a code markdown block to another user
```
git index-pack .git/objects/pack/pack-9bdaea249c07c366ad239deed27969d8e6d30baf.pack
```
2. Notice how the `9` after `pack-` is missing.

### Expected behavior:

The code send should never, ever, be modified.

### Actual behavior:

The code is modified (in my case a character is stripped), this is the output with the above text:
```
git index-pack .git/objects/pack/pack-bdaea249c07c366ad239deed27969d8e6d30baf.pack
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.20

### Additional context

This does not happen if we use a markdown syntax highlight like \`\`\`json or \`\`\`plaintext, so this is very likely the default highlight that is wonky.

**Comment by MartinSchoeler** [comment]
Tested on develop 2.1.0 and the issue still exists, only when using three backticks (```)
<img width="671" alt="Screen Shot 2019-10-17 at 13 17 43" src="https://user-images.githubusercontent.com/20868078/67027819-a26e7800-f0e0-11e9-867e-d95e9c2e74b2.png">

**Comment by sveatlo** [comment]
i cannot reproduce this anymore using `3.3.3`
