### ISSUE TITLE
Live chat after update 2.0

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat#15499]
### Description:

After updating to version 2.0 live chat stopped working

### Steps to reproduce:

When sending a message in live chat, an error appears in both versions
![image](https://user-images.githubusercontent.com/40425622/66150046-cf755200-e62d-11e9-9a83-8b5b5b017d27.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/40425622/66150157-05b2d180-e62e-11e9-871a-cbe136f1746b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0
- Operating System: Ubuntu 18
- Deployment Method: tar
- Number of Running Instances: 50
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4

Help fix, please.

**Comment by reetp** [comment]
Have you checked the livechat setup?
The old widget is deprecated and code+paths updated.

**Comment by CH1PSET1** [comment]
Compare the code that stood before and the code in the new version. They are exactly the same, but replaced anyway. The error remained.

**Comment by CH1PSET1** [comment]
![image](https://user-images.githubusercontent.com/40425622/66308067-8a983680-e91f-11e9-8141-d40f2d52c1ea.png)

**Comment by renatobecker** [comment]
@CH1PSET1 

Your server is still supporting the old livechat widget, as you can see below:

![Screen Shot 2019-10-07 at 11 16 21](https://user-images.githubusercontent.com/2067649/66319736-02e90280-e8f4-11e9-9fc5-73f912a1600b.png)

This means that the update process did not succeed. After updating the server(The latest version is 2.1) you'll need to replace the `Javascript snippet installation` as described before.

**Comment by CH1PSET1** [comment]
Everything worked, thanks.!

**Comment by reetp** [comment]
@rocket-cat close
