### ISSUE TITLE
Push Notification Logic

### ISSUE THREAD

**Issue by gyverchang** [RocketChat/Rocket.Chat#15492]
We have been using Rocket Chat for close to a year and until today it seems like the push notifications got a lot of bad name from most of my colleagues.

I would just like to highlight a few points regarding notifications and would like to know how notifications from rocketchat works, so that I can explain to my colleagues in detail and so they won't uninstall their rocketchat apps on their phones :(

1. Notifications still sent even though you are on the present channel actively engaged in the conversation(Mostly through Rocket Chat Experimental App)

2. When using rocketchat on Web & on Rocket Chat Experimental App, when you unlock your PC, you still get notifications from past messages that has been already read on the Rocket Chat Experimental App.

3. Notifications received while using Rocket Chat Experimental App, however, message on the app still does not show and takes seconds to load(lag). 

Does all these Push Notification issues originate from our own self hosted rocketchat server or this is due to how the logic of Push Notification works?
 
Thank you in advance!

**Comment by reetp** [comment]
@rocket-cat close

This isn't actually bug. At best a 'feature-request’ as a discussion point.

If you have specific Issues then please read all the links here:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

I'd suggest starting with this:
https://rocket.chat/2019/09/27/push-notification/

A lot of issues are down to configuration - either defaults via the admin, or individual preferences.
Logged in status will affect things as well. Please check them thoroughly.

Experimental app is what it says. It is still being developed rapidly and is set to replace the native Android and iOS apps soon. Any issues (and make sure they are actually issues) should be reported in the https://github.com/RocketChat/Rocket.Chat.ReactNative repo

> Does all these Push Notification issues originate from our own self hosted rocketchat server or this is due to how the logic of Push Notification works?

Your Rocket.Chat server sends notifications via the Rocker.Chat gateway. You can use your own gateway:

https://rocket.chat/docs/administrator-guides/notifications/push-notifications/#push-notifications
