### ISSUE TITLE
Add existing message to thread

### ISSUE THREAD

**Issue by thawn** [RocketChat/Rocket.Chat#15502]
Users (myself included) often forget to use the "reply in thread" feature. Therefore, it would be very useful to be able to add an existing message to a thread (or to attach it to another message to start a new thread).

**Comment by reetp** [comment]
@rocket-cat close

Thank you for your comment.

This repo is for bugs.

Please note that all new feature requests should now be opened here:
https://github.com/RocketChat/feature-requests/issues

**Comment by thawn** [comment]
Opened new feature request [here](https://github.com/RocketChat/feature-requests/issues/197).
