### ISSUE TITLE
Issue with Facebook Omnichannel Setup

### ISSUE THREAD

**Issue by benjsicam** [RocketChat/Rocket.Chat#15501]
### Description:

When setting up Facebook Omnichannel Integration, an error occurs saying, "Login Failed: You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook login."

### Steps to reproduce:

1. Go to Livechat configuration.
2. Click Facebook Messenger.
3. Login to Facebook on the pop-up window.

### Expected behavior:

Facebook Omnichannel should be setup properly.

### Actual behavior:

An error occurs saying, "Login Failed: You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook login."

![facebook-login-issue](https://user-images.githubusercontent.com/1850054/66177869-cd46de00-e695-11e9-950b-91bd31d70312.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Linux
- Deployment Method: Official Docker Image
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.12

**Comment by brocgailit** [comment]
Same here.  Any luck?

**Comment by rabbihossain** [comment]
I have tried this on my server. I am also facing the same issue. If there any solution to this?

**Comment by Gtlng** [comment]
Same here.

**Comment by geekgonecrazy** [comment]
I believe we have been having some issues with Facebook and our oauth app.  I believe they have re-enabled it for us.  Please try again

cc: @renatobecker

**Comment by renatobecker** [comment]
Yes, as @geekgonecrazy described, we were facing some issues with the Facebook integration, but now it's supposed to be working fine.

Please, try again.
