### ISSUE TITLE
Make `chat.update` accept `tmid`

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat#15505]
Related to https://github.com/RocketChat/Rocket.Chat/issues/15504

`updateMessage` accepts `tmid` in this case, but `chat.update` doesn't.

**Comment by ggazzo** [comment]
why do you need the thread id to update a message?

**Comment by diegolmello** [comment]
@ggazzo Check the related issue: https://github.com/RocketChat/Rocket.Chat/issues/15504
I'm trying to add the message to a thread by editing it.

**Comment by zdumitru** [comment]
Should not be closed
