### ISSUE TITLE
Firefox registration autocomplete validation error on login

### ISSUE THREAD

**Issue by doits** [RocketChat/Rocket.Chat#1551]
This might be firefox specific, but anyway:

I've enabled autocomplete of username and password on login in firefox. This means firefox automatically fills out my username and password. But the logic of firefox not only fills out the login fields but also the registration fields. And since my username is not an email address (but that is what the registration field expects), I get a validation error on clicking `login` for the hidden field. I then have to manually unhide the registration form (with developer tools), clear the username from the registration email, and then click on login again.

The registration items should not be sent on login (it should be a separate form) or they should be disabled at least, so they do not get autofilled (hopefully).
##

**Comment by fallc0nn** [comment]
This is affecting me as well.

**Comment by MarauderXtreme** [comment]
Same for me.
+1 subscribe

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
