### ISSUE TITLE
Arrange/sort channels manually

### ISSUE THREAD

**Issue by ledlamp** [RocketChat/Rocket.Chat#15518]
There should be an option to arrange the order of channels manually, by dragging. Arranging alphabetically results in channels not being where I'd like them to be, and arranging by activity causes the order of channels to constantly change, making it messy and hard to find the channels I want. I wish I could just put each channel where I want them.

**Comment by reetp** [comment]
@rocket-cat close

Thank you for your comment.

This repo is for bugs.

Please note that all new feature requests should now be opened here:
https://github.com/RocketChat/feature-requests/issues

**Comment by ledlamp** [comment]
o
