### ISSUE TITLE
oauth without require authorization

### ISSUE THREAD

**Issue by georgeos** [RocketChat/Rocket.Chat#15524]
**Description:**

When using an oauth provider for authentication, is it possible to send the access_token to Rocket chat or use grant_type=password instead of authorization_code. 

**Steps to reproduce:**

Actual behavior is working.

**Expected behavior:**

We want to integrate rocket chat as part of our web application. If our users get logged in to our web application (which generates an access_token), we want to add some link to our rocket chat installation (on premise) without requiring an authorization (authorization code) because they have the access_token generated from the login.

**Actual behavior**

Always use grant_type=authorization_code

**Server Setup Information:**

Version of Rocket.Chat Server: 1.3.2
Operating System: Ubuntu 16.04
Deployment Method: on premise, docker
Number of Running Instances: 1
DB Replicaset Oplog: n/a
NodeJS Version: 8.11.4 - x64
MongoDB Version: 4.2.0

**Additional context**

We need this in order to avoid an additional authorization, as we want to integrate to our web application.

**Comment by reetp** [comment]
@rocket-cat close

This repo is for bugs.

Please note that all new feature requests should now be opened here:
https://github.com/RocketChat/feature-requests/issues


For setup/support please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
