### ISSUE TITLE
No avatar in the app, just a little box

### ISSUE THREAD

**Issue by buwzim** [RocketChat/Rocket.Chat#15526]
### Description:

In the Android and iOS app are all avatar pictures broken.
![Screenshot_20191007-125903](https://user-images.githubusercontent.com/25976173/66306983-67f82480-e903-11e9-95f6-db592f3419aa.png)
The service runs fine in a browser.

### Steps to reproduce:

1. Open the app.

### Expected behavior:

There should be an "A" for our channel "Allgemein" and so on.

### Actual behavior:

A little box is shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.1
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 8
- DB Replicaset Oplog: Yes
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.11

### Relevant logs:

I didn't see anything related in the log file.

**Comment by reetp** [comment]
First it would be worth you following this:

https://rocketchat.github.io/docs/contributing/reporting-issues/

"Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue"

That includes the apps as well. There are major ongoing changes with mobile apps with upgrades to the core database plus changing the code base.

It worth testing the Beta versions on both Android and iOS.

You can try logging out and logging back in again as a starter.

**Comment by stbc** [comment]
Still suffering from that bug as well. Running 2.2.0, latest Android app version.
