### ISSUE TITLE
rocketchat_1 | private group user statistic not found

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#1552]
I get this log message with the latest docker image. Should this be fixed?

**Comment by p1rox** [comment]
Same thing, I'm currently trying to link Rocket with my personal GitLab

**Comment by marceloschmidt** [comment]
What image are you building from?
I just started mine and it all went fine: http://pastebin.com/1h45kSEP
Here's my startup line: `docker run --name rocketchat2 --net=rc_nw -e MONGO_URL=mongodb://172.18.0.2:27017 -p 8080:3000 rocketchat/rocket.chat`

**Comment by tholu** [comment]
@marceloschmidt I used ``docker-compose`` and the latest image from today. It does not occur on startup, but later:

```
rocketchat_1 | {"line":"71","file":"percolate_synced-cron.js","message":"SyncedCron: Starting \"Generate and save statistics\".","time":{"$date":1449082800006},"level":"info"}
rocketchat_1 | private group user statistic not found
rocketchat_1 | {"line":"71","file":"percolate_synced-cron.js","message":"SyncedCron: Finished \"Generate and save statistics\".","time":{"$date":1449082800095},"level":"info"}
```

**Comment by geekgonecrazy** [comment]
@marceloschmidt i've seen this also.  It doesn't seem to effect anything, other then stats maybe.  But it does show up in the logs.

**Comment by marceloschmidt** [comment]
Ah, ok... I'll let it run for a while and will track it down later on then ;) thanks!

**Comment by p1rox** [comment]
I was using 0.7 version. I switch to `develop` and now it works.

**Comment by tholu** [comment]
@p1rox Strange, since I'm using develop and still get the log message (things seem to work however). Could this be related to enabling/disabling the sending of statistics in the settings?

**Comment by marceloschmidt** [comment]
I just searched the code now and this is not a bug, though it should probably be removed. This was some debugging info regarding statistics generation.
