### ISSUE TITLE
Cannot send file with extension *.cfg

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#15527]
### Description:

There is no possibilty to send files with .cfg extension. I have set "plain/text" in  "Accepted Media Types" but still not working. When I leave empty "Accepted Media Types" is possible to send .cfg files.

### Steps to reproduce:

1. Add "plain/text" in  "Accepted Media Types"
2. Try to send .cfg file
3. Is not possible to send .cfg files

### Expected behavior:

Sending .cfg file is possoble with "text/plain" "Accepted Media Types"

### Actual behavior:

![image](https://user-images.githubusercontent.com/50440047/66312865-a98fcc00-e911-11e9-9a93-c640c7b476ab.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Centos 7
- Deployment Method: Docker Compose
- Number of Running Instances:  9
- DB Replicaset Oplog: YES
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 4.0

**Comment by rasos** [comment]
So `.cfg` is not a plain/text media type and it is not listed here: http://www.iana.org/assignments/media-types/media-types.xhtml .

**Comment by emikolajczak** [comment]
So question is how to configure "Accepted Media Types" whit list to allow upload ".cfg" files? I try with many types and only works with empty list (not secure in this case).
