### ISSUE TITLE
Add integrated pastebin for multiline pastes

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#1553]
This is a feature suggestion, after playing around with inline_code styles and the problem of multiline-code-pastes. Could work as following:
- Detect multline paste before pasting
- Save the multiline paste and automatically create a link to the paste content, post link instead of multiline paste (or "upload" the multiline paste as a .txt-file instead)
- Link/file should only be accessable to logged in users of the chat

What do you think?
##

**Comment by geekgonecrazy** [comment]
@tholu I think if uploading to a provider, we'd for sure want it to be modular as to not limit peoples options.

But I do agree multi-line paste maybe we have a different message type?  Maybe we could detect that its large, and create a message type that is collapsed by default and you click "show more" and it'd expand the message?

**Comment by tholu** [comment]
@geekgonecrazy I actually don't need an external provider to upload it to (I would not use it), I would prefer to upload it to the Rocketchat instance.

Different message type sounds nice as well, add some syntax highlighting and it would be really great :+1:

**Comment by geekgonecrazy** [comment]
Ok good!  I wouldn't want to use it either, especially for anything even remotely sensitive

**Comment by tholu** [comment]
@geekgonecrazy Exactly! That's one of the reasons why we are using RocketChat instead of Slack in the first place :)

**Comment by zgana** [comment]
+1 I would love to see this.  Collapsable pastes for code and logs would be really useful for my team (and so a key selling point if I am going to convince them to migrate from Slack...).

**Comment by silentwarrior** [comment]
Id be extremely happy if it works exactly like Slack, if you can make it even better, great!

IMHO. Integration with pastebin might not be the best option however. Having it save locally to the rocket chat instance by default and then have an integration option to "Export" it as a pastebin would actually be the best option here.
