### ISSUE TITLE
Facebook Messenger failed integration with Live Chat

### ISSUE THREAD

**Issue by pmjunior** [RocketChat/Rocket.Chat#15530]
### Description:

I follow the steps to enable Facebook Messenger with LiveChat, when I click on "Facebook Messenger" on Live Chat Guide, open a pop-up where I use my credencials from facebook and after I receive a message: "Login Failed: You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook Login." and "{"success":false,"error":{"message":"Internal Server Error"}}" when I click OK.

### Steps to reproduce:

1. Go to LiveChat Menu.
2. Click on Facebook and insert Key and Secret Omni. Save configuration.
3. Access LiveChat Menu e click on Facebook Messenger, you will receive the pop-up from Facebook, insert your credencials, after this you will see the errors.

### Expected behavior:

Finally the integration and receive messages from Facebook messenger

### Actual behavior:

Login Failed: You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook Login.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.0
- Operating System: CentOS 7
- Deployment Method: Ansible
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.15.1 - x64
- MongoDB Version: 4.2.0

**Comment by renatobecker** [comment]
@pmjunior 
Can you, please, share the server log after trying to activate the integration?

Thanks.

**Comment by pmjunior** [comment]
Hi @renatobecker 
This is the logs generated after enable Facebook Messenger on Live chat:

I20191007-18:11:14.761(-3) Meteor ➔ method saveSettings -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ [ { _id: 'Livechat_Facebook_Enabled', value: true } ] ] 
I20191007-18:11:14.821(-3) Meteor ➔ method private-settings/get -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ 2019-10-07T21:10:53.093Z ] 
I20191007-18:11:34.241(-3) Meteor ➔ publish livechat:rooms -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ {}, 0, 20 ] 
I20191007-18:11:34.388(-3) Meteor ➔ publish livechat:departments -> userId: YfyDgfWEyD2ysoPzX , arguments:  [] 
I20191007-18:11:34.409(-3) Meteor ➔ method livechat:getCustomFields -> userId: YfyDgfWEyD2ysoPzX , arguments:  [] 
I20191007-18:11:37.972(-3) Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'initialState' } ] 
I20191007-18:11:38.013(-3) Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'list-pages' } ] 
I20191007-18:11:38.711(-3) Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'enable' } ] 
I20191007-18:11:51.827(-3) Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'list-pages' } ] 
I20191007-18:11:52.478(-3) Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'enable' } ]

**Comment by dudanogueira** [comment]
+1. Just got the credentials from the awesome rocketchat team and had this exact problem. Posting here to get notified :)

**Comment by renatobecker** [comment]
Hey guys!

We were facing an issue with our Facebook integration, but now the integration is supposed to be okay.

Thanks.

**Comment by dudanogueira** [comment]
Ok, I tried with another page I have, and it worked. However, with the page I want, it's not working. Looks like it doesnt subscribe to the page messenger...

**Comment by bytefact** [comment]
@renatobecker Tested and now I can connect our facebook page to live chat. Text messaging is okay, but photo's are not working, both sending and receiving. So this is the first time that we are testing the facebook integration and we are not sure if that ever worked or is related the bug. Can you please confirm?

**Comment by dudanogueira** [comment]
Ok! I was able to setup. The problem was on the page settings:
![image](https://user-images.githubusercontent.com/1761174/66943113-e5691680-f020-11e9-9bfb-ed3a711c2a3f.png)

I also can confirm that neither audio or image is working and also not sure if it is supposed to work

**Comment by dudanogueira** [comment]
Interestingly, emojis will work from facebook to Rocket.Chat, but not the other way around. It will set :sweat_smile: instead. I also noticed that the same is true for the livechat. If the livechat user sends an emoji, it will arrive ok to the agent. But if the agent send an emoji to the user, it will appear as text reference, just like :sweat_smile:

**Comment by renatobecker** [comment]
> @renatobecker Tested and now I can connect our facebook page to live chat. Text messaging is okay, but photo's are not working, both sending and receiving. So this is the first time that we are testing the facebook integration and we are not sure if that ever worked or is related the bug. Can you please confirm?

We're not supporting file sharing through the Facebook integration yet, so for sure it's not a bug.
Thanks.

**Comment by pmjunior** [comment]
@renatobecker Tested and now I can't receive or send messages between FB and RC, any ideia?

**Comment by dudanogueira** [comment]
@pmjunior , were you able to list your page under the Live Chat > Facebook Messenger Option? If positive, make sure that the toggle button is marked to "on". Also, the option under Administration > Live Chat > Facebook (Expand the tab) should be on.

Another tip is to go to Administration > Logs, and set the log level to a more verbose option. Then you go to Administration > Show Logs and monitor them.

When you toggle your page to on/off, you should see something like this:

I20191017-21:41:38.307(0) Meteor ➔ method livechat:facebook -> userId: Pz132Hj&asm , arguments:  [ { action: 'subscribe', page: '123123091872398123' } ] 

which probably means that Rocket.Chat was able to subscribe to your page.

On your facebook page go to Options, and try to set it up as I showed above. On my case, there was another App that was receiving the messages instead of the Rocket.Chat facebook app.

Hope to have helped somehow :) É nóis!

**Comment by pmjunior** [comment]
I follow all steps, but don't worked for me, there is not logs from facebook, I copied logs, follow below:

I20191018-14:21:45.353(-3) livechat:facebook { id: 'r8uRfCG8FZtX3k6MC',   clientAddress: '200.143.192.70',   httpHeaders:     { 'x-forwarded-for': '200.143.192.70',      'x-real-ip': '200.143.192.70',      'x-forwarded-proto': 'https',      host: 'rocket.rnp.br:443',      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',      'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' },   userId: 'YfyDgfWEyD2ysoPzX' } 
I20191018-14:21:45.356(-3) server.js:212 Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'initialState' } ] 
I20191018-14:21:47.817(-3) livechat:facebook { id: 'r8uRfCG8FZtX3k6MC',   clientAddress: '200.143.192.70',   httpHeaders:     { 'x-forwarded-for': '200.143.192.70',      'x-real-ip': '200.143.192.70',      'x-forwarded-proto': 'https',      host: 'rocket.rnp.br:443',      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',      'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' },   userId: 'YfyDgfWEyD2ysoPzX' } 
I20191018-14:21:47.819(-3) server.js:212 Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'enable' } ] 
I20191018-14:21:48.739(-3) private-settings/get { id: 'hE68xvC5HYiuXNa7t',   clientAddress: '200.143.192.70',   httpHeaders:     { 'x-forwarded-for': '200.143.192.70',      'x-real-ip': '200.143.192.70',      'x-forwarded-proto': 'https',      host: 'rocket.rnp.br:443',      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',      'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' },   userId: 'YfyDgfWEyD2ysoPzX' } 
I20191018-14:21:48.741(-3) server.js:212 Meteor ➔ method private-settings/get -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ 2019-10-18T14:51:08.656Z ] 
I20191018-14:21:48.747(-3) livechat:facebook { id: 'r8uRfCG8FZtX3k6MC',   clientAddress: '200.143.192.70',   httpHeaders:     { 'x-forwarded-for': '200.143.192.70',      'x-real-ip': '200.143.192.70',      'x-forwarded-proto': 'https',      host: 'rocket.rnp.br:443',      'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36',      'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' },   userId: 'YfyDgfWEyD2ysoPzX' } 
I20191018-14:21:48.750(-3) server.js:212 Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments:  [ { action: 'list-pages' } ] 

I have only this.. :(

**Comment by renatobecker** [comment]
> I follow all steps, but don't worked for me, there is not logs from facebook, I copied logs, follow below:
> 
> I20191018-14:21:45.353(-3) livechat:facebook { id: 'r8uRfCG8FZtX3k6MC', clientAddress: 'x.x.x.x', httpHeaders: { 'x-forwarded-for': 'x.x.x.x', 'x-real-ip': 'x.x.x.x', 'x-forwarded-proto': 'https', host: 'rocket.x.x:443', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36', 'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' }, userId: 'YfyDgfWEyD2ysoPzX' }
> I20191018-14:21:45.356(-3) server.js:212 Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments: [ { action: 'initialState' } ]
> I20191018-14:21:47.817(-3) livechat:facebook { id: 'r8uRfCG8FZtX3k6MC', clientAddress: 'x.x.x.x', httpHeaders: { 'x-forwarded-for': 'x.x.x.x', 'x-real-ip': 'x.x.x.x', 'x-forwarded-proto': 'https', host: 'rocket.x.x:443', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36', 'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' }, userId: 'YfyDgfWEyD2ysoPzX' }
> I20191018-14:21:47.819(-3) server.js:212 Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments: [ { action: 'enable' } ]
> I20191018-14:21:48.739(-3) private-settings/get { id: 'hE68xvC5HYiuXNa7t', clientAddress: 'x.x.x.x', httpHeaders: { 'x-forwarded-for': 'x.x.x.x', 'x-real-ip': 'x.x.x.x', 'x-forwarded-proto': 'https', host: 'rocket.x.x:443', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36', 'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' }, userId: 'YfyDgfWEyD2ysoPzX' }
> I20191018-14:21:48.741(-3) server.js:212 Meteor ➔ method private-settings/get -> userId: YfyDgfWEyD2ysoPzX , arguments: [ 2019-10-18T14:51:08.656Z ]
> I20191018-14:21:48.747(-3) livechat:facebook { id: 'r8uRfCG8FZtX3k6MC', clientAddress: 'x.x.x.x', httpHeaders: { 'x-forwarded-for': 'x.x.x.x', 'x-real-ip': 'x.x.x.x', 'x-forwarded-proto': 'https', host: 'rocket.x.x:443', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36', 'accept-language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' }, userId: 'YfyDgfWEyD2ysoPzX' }
> I20191018-14:21:48.750(-3) server.js:212 Meteor ➔ method livechat:facebook -> userId: YfyDgfWEyD2ysoPzX , arguments: [ { action: 'list-pages' } ]
> 
> I have only this.. :(

My suggestion is to disable the whole integration in both Rocket.Chat admin area as well on the Livechat Menu and then install it again, starting from the Rocket.Chat admin area.

Please, leave new comments here after running the full installation again.

**Comment by rsgodinez** [comment]
Hi - tried many times but the integration is still now working. Both Rocket.Chat admin and Livechat Menu show that the connections is succesful. 

![image](https://user-images.githubusercontent.com/62675312/77591991-ca93ab80-6eb6-11ea-9ba0-4965c2c334ff.png)

![image](https://user-images.githubusercontent.com/62675312/77592017-d7180400-6eb6-11ea-8248-b237c1146fc7.png)


We also see logs as

I20200325-16:30:08.833(-6) server.js:204 Meteor ➔ method livechat:facebook -> userId: w4NLHGaaqBK6wP6TS, arguments: [{"action":"unsubscribe","page":"107471310896694"}]
I20200325-16:30:14.699(-6) server.js:204 Meteor ➔ method livechat:facebook -> userId: w4NLHGaaqBK6wP6TS, arguments: [{"action":"subscribe","page":"107471310896694"}]

And even at the facebook page, Rocket.Chat is selected as primary. But we still don't see the messages arriving at Rocket Chat. 

![image](https://user-images.githubusercontent.com/62675312/77592041-e9923d80-6eb6-11ea-80da-46ed3165f231.png)
