### ISSUE TITLE
Architecture of Rocketchat

### ISSUE THREAD

**Issue by lequy1010** [RocketChat/Rocket.Chat#15543]
Hi ad,
Rocket chat is a good application for chatting,
We want to use it to custom to use for internal company.
But to be able to customize smoothly, you need to understand the architecture of Rocket.
If have any documentations about architecture please help to share to everyone.

Thank all.

**Comment by rodrigok** [comment]
Hi @lequy1010 

You may find the information you need on our [docs](https://rocket.chat/docs/).
Our source code is open, any other information needed you can check the code.

Thanks
