### ISSUE TITLE
CORB blocking new livechat version

### ISSUE THREAD

**Issue by PatrickFreitas** [RocketChat/Rocket.Chat#15545]
**Description:**
When import script from Rocket Chat (_Live Chat_) in his new version, the response has been blocked by Cross-Origin Read Blocking (_CORB_) from google chrome.

**Example of script:**
> <script type="text/javascript">
> (function(w, d, s, u) {
> 	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
> 	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
> 	j.async = true; j.src = 'https://....../livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000';
> 	h.parentNode.insertBefore(j, h);
> })(window, document, 'script', 'https://....../livechat?version=1.0.0');
> </script>

**Error message:**
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://......./livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000 with MIME type text/html.

**Error Explanation:**
In the new version of live chat, the request response made by the script mentioned above has the "Content-Type" key inserted as "text/html". The request response contains a script within the HTML content, resulting in the request blocking by CORB.

**Comment by reetp** [comment]
You have failed to add any information from here. Please read the links there.
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Nonetheless check the livechat URL in the Installation section. It has been changed.

>https://....../livechat/1.0.0/rocketchat-livechat.min.js

Is now

https://....../livechat/rocketchat-livechat.min.js

https://github.com/RocketChat/Rocket.Chat/issues/15499

Also look at:

Livechat Allowed Domains
"Comma-separated list of domains allowed to embed the livechat widget. Leave blank to allow all domains."

**Comment by PatrickFreitas** [comment]
> https://....../livechat/rocketchat-livechat.min.js

The livechat URL in the installation documentation still appears wrong in my application, but **removing the version was enough to solve the problem**. Thanks.



> You have failed to add any information from here. Please read the links there.

Sorry for that.

**Comment by engelgabriel** [comment]
@renatobecker can you please update https://www.drupal.org/project/rocket_chat ?

**Comment by renatobecker** [comment]
> @renatobecker can you please update https://www.drupal.org/project/rocket_chat ?

@engelgabriel the new version of Drupal is out:
https://www.drupal.org/project/rocket_chat/releases/8.x-2.2
