### ISSUE TITLE
When User Joins a Call, Mark Them as Busy

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#1554]
Whenever a user joins a webrtc call, their status is marked as busy and then when they leave it their status goes back to the previous one.
##

**Comment by engelgabriel** [comment]
To be done as part of https://github.com/RocketChat/Rocket.Chat/issues/933

**Comment by louisemessage** [comment]
Not completed in https://github.com/RocketChat/Rocket.Chat/issues/933 so closing for now.
