### ISSUE TITLE
RoomReader getMessages is not implemented

### ISSUE THREAD

**Issue by seanhostdime** [RocketChat/Rocket.Chat#15551]
### Description:

We are building an app for Rocket.Chat and we need the method `getMessages` documented here : https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/iroomread.html#getmessages

When we call this method, an exception is thrown with the message "Method not implemented"

### Steps to reproduce:

1. Create a Rocket.Chat.App and call the IRoomReader getMessages method

### Expected behavior:

A `Promise<IterableIterator<IMessage>>` is returned containing all Messages set in the Room

### Actual behavior:

Not implemented exception is thrown

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1
- Operating System: MacOS
- Deployment Method: meteor npm start
- Number of Running Instances: 1
- NodeJS Version: 10.15.3

### Additional context

We forked the repo and implemented a fix for this. I'll submit a pull request to both this repo and the Rocket.Chat.Apps-engine repo

### Relevant logs:

![Screen Shot 2019-10-10 at 12 02 43 AM](https://user-images.githubusercontent.com/54182260/66538195-51afbb80-eaf1-11e9-90d3-7458e99ba28d.png)

**Comment by d-gubert** [comment]
Hi @seanhostdime! Yes, unfortunately, we are unable to implement such method at the moment, as it would load all messages from a room in memory, and rooms are very likely to have thousands of messages - which means that would enable apps to make Rocket.Chat unresponsive.

We are working on a "cursor" strategy, that would enable apps to iterate over such a large set of data without loading it all to memory, but it is at a very early stage right now.

**Comment by seanhostdime** [comment]
Okay, I see the issue. I think I can wrap the cursor that gets returned from a database query in a class which supports pagination on the Rocket.Chat side. When I do this, I will also need to change the interface type on the Rocket.Chat Apps engine side. Currently it expects an `IterableIterator` which, as far as I can tell, doesn't expose any kind of pagination methods. So, even if the concrete type under the interface supports paging, there would be no way for the app developer to get at the pages because the TypeScript type checker wouldn't recognize the methods exist. I'll update my pull request with a draft that could get us started in the right direction.

I don't know if we need to change this pull request to a breaking change or not. I think changing this interface would be considered safe as the method isn't technically implemented yet, and therefore we know no one can be using it
