### ISSUE TITLE
Can't add new users with both user and livechat-agent role

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#15553]
### Description:
Can't create new users whn selcting live-chat-agent role. The submission form doeans't process users creation.
But can create normal user with the "user" role instead.

### Steps to reproduce:

1.  Go to Administration 
2. Click on Users
3. and so on Add User with livechat-agent role and user role.

### Expected behavior:
Creating new users.

### Actual behavior:

![image](https://user-images.githubusercontent.com/42721509/66540603-ba685980-eb2c-11e9-9b43-ca8151ddf430.png)

### Server Setup Information:

Version | 2.1.0
-- | --
Apps Engine 1.6.0
Database Migration 161
Commit: 
Hash: c95663d2cae44464573c20a824c40a9328c29d09
Date: Fri Sep 27 20:47:47 2019 -0300
Branch: Head
Subject: Merge pull request #15459 from RocketChat/release-2.1.0
Tag: 2.1.0
Author: Diego Sampaio

**Comment by renatobecker** [comment]
@franckadil Can you, please, check your log in both browser and server-side when you attempt to create the user?
