### ISSUE TITLE
Confirm sending a message that notifies many users

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#15558]
As soon as there are more than 6 active users in a channel, Slack will ask you to confirm sending your message. This prevents that unnecessarily many people are notified unintentionally.

Such a feature would also be useful for Rocket.chat.

**Comment by reetp** [comment]
@rocket-cat close

This may be a good idea but it is a feature request and should be opened here please:
https://github.com/RocketChat/feature-requests
