### ISSUE TITLE
Livechat Webhooks no working version 2.1.0

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#15557]
Description:
Livechat Webhooks is not working when a file is sent by livechat and when you log out, it only works if you send messages

Server Setup Information:

Version of Rocket.Chat Server: 2.1.0
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.16.0
MongoDB Version: v3.6.12

**Comment by renatobecker** [comment]
@josep112 Did you notice any error on the server-side logs?

**Comment by josep112** [comment]
@renatobecker  yes
Exception in defer callback: TypeError: Cannot read property '_id' of undefined     at normalizeMessageFileUpload (app/utils/server/functions/normalizeMessageFileUpload.js:7:86)     at messages.forEach.message (app/livechat/server/hooks/sendToCRM.js:64:27)     at Array.forEach (<anonymous>)     at sendToCRM (app/livechat/server/hooks/sendToCRM.js:39:12)     at app/livechat/server/hooks/sendToCRM.js:115:2     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at constants (app/callbacks/lib/callbacks.js:45:45)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (app/lib/server/functions/sendMessage.js:224:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by renatobecker** [comment]
> @renatobecker yes
> Exception in defer callback: TypeError: Cannot read property '_id' of undefined at normalizeMessageFileUpload (app/utils/server/functions/normalizeMessageFileUpload.js:7:86) at messages.forEach.message (app/livechat/server/hooks/sendToCRM.js:64:27) at Array.forEach () at sendToCRM (app/livechat/server/hooks/sendToCRM.js:39:12) at app/livechat/server/hooks/sendToCRM.js:115:2 at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70) at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20) at app/callbacks/lib/callbacks.js:39:35 at constants (app/callbacks/lib/callbacks.js:45:45) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at constants (app/callbacks/lib/callbacks.js:45:47) at callbacks.run (app/callbacks/lib/callbacks.js:126:9) at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17) at Meteor.defer (app/lib/server/functions/sendMessage.js:224:32) at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12) at packages/meteor.js:550:25 at runWithEnvironment (packages/meteor.js:1286:24)

Hey! We were facing an issue with our Facebook Integration, but now you're supposed to be able to activate it again.

Thanks.

**Comment by josep112** [comment]
Hi, @renatobecker 
Facebook seems to work now but I can't upload the image yet this log is current


12:30:45.695(-3) Exception in defer callback: TypeError: Cannot read property '_id' of undefined     at normalizeMessageFileUpload (app/utils/server/functions/normalizeMessageFileUpload.js:7:86)     at messages.forEach.message (app/livechat/server/hooks/sendToCRM.js:64:27)     at Array.forEach (<anonymous>)     at sendToCRM (app/livechat/server/hooks/sendToCRM.js:39:12)     at app/livechat/server/hooks/sendToCRM.js:115:2     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at constants (app/callbacks/lib/callbacks.js:45:45)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (app/lib/server/functions/sendMessage.js:224:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by renatobecker** [comment]
> Hi, @renatobecker
> Facebook seems to work now but I can't upload the image yet this log is current
> 
> 12:30:45.695(-3) Exception in defer callback: TypeError: Cannot read property '_id' of undefined     at normalizeMessageFileUpload (app/utils/server/functions/normalizeMessageFileUpload.js:7:86)     at messages.forEach.message (app/livechat/server/hooks/sendToCRM.js:64:27)     at Array.forEach ()     at sendToCRM (app/livechat/server/hooks/sendToCRM.js:39:12)     at app/livechat/server/hooks/sendToCRM.js:115:2     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at constants (app/callbacks/lib/callbacks.js:45:45)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at constants (app/callbacks/lib/callbacks.js:45:47)     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at Meteor.defer (app/lib/server/functions/sendMessage.js:224:32)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

I'll take a look at this issue ASAP.
