### ISSUE TITLE
Feature Request - Allow groups to be invited to channels/private groups.

### ISSUE THREAD

**Issue by Tom-Development** [RocketChat/Rocket.Chat#15566]
Similar to Slack & Discord, I think a feature where you can assign a group to a channels permissions could speed up administration in larger servers and communities. 

For example, say I had two private channels set up, one called #art-2d and another called #art3-d. If I wanted to add my team of artists to these channels, all the artists are in a role called "Artists", with this feature I could then simply add this role to both channels and then anyone with this role can see both channels instead of manually inviting each of our artists. 

I feel like this system should work similar to the default channels, where channels that they are added to are displayed down the side and they do not have to join them or be invited when a new account is created. 

Similarly, when their role is removed they should no longer have access to any chats with that permission.

**Comment by reetp** [comment]
@rocket-cat close

This isn't a bug in Rocket.

Please open this in

https://github.com/RocketChat/feature-requests
