### ISSUE TITLE
Change password should not accept the current user password. 

### ISSUE THREAD

**Issue by Tom-Development** [RocketChat/Rocket.Chat#15569]
### Description:

When a user is forced to change their password, they can enter their current password, therefor not changing it at all. Furthermore on the user account settings page change password has the same behaviour. 

### Steps to reproduce:

1. Go to account page, on the change password screen.
2. Change password, enter your current password.

Or

1. From the admin panel, force a user to change their password.
2. Login as that user and enter the current password on the change password screen.

### Expected behavior:

The system should check to ensure the current password has not been entered and confirm it does not match the current password.

### Actual behavior:

It allows me to enter the current password, so effectively not changing the password, even if an admin has clicked the force password reset button. 

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Ubuntu 18.04.3 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: 8.11.4
- MongoDB Version: 3.4.20

### Additional context

As a security caution, an admin may want to force the user to change their password if their old password has been compromised. This feature would allow them to set the current password as the new one, potentially allowing that user account to be compromised again. 

Another feature which may also be handy would be to have a password history stored in the database, so they can't chose their last X amount of passwords they had, if enabled in the password policy. This should be a customisation option.

**Comment by reetp** [comment]
"Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

In this case it probably won't, but as a matter of course you should test anyway.
 
> Another feature which may also be handy would be

You know where NFRs go now....

**Comment by Tom-Development** [comment]
As I had placed in the bug, I am using the snap version so am currently unable to update till you release the next version...

**Comment by reetp** [comment]
> As I had placed in the bug report above, I am using the snap version so am currently unable to update till they release the next snap version...

Snaps are frequently some way behind - and a lot right now because of a big leap to 2.x.

If you are going to report bugs you really need to try an up to date version as per the documentation. It is always the first thing to do because thing s move so fast.

With VM technology at your disposal this is trivial. You can easily spool up a test version in minutes to test this sort of thing, and always worth it so you know what changes are coming.

It is just good admin.

**Comment by Tom-Development** [comment]
I thought this may be the case, I have tested using the actual open rocketchat server also, since I understand snaps are behind. This was tested _before_ I had submit the bug report, although I am unsure to what version the live server uses, I assume it is the latest.

**Comment by reetp** [comment]
>  although I am unsure to what version the live server uses, I assume it is the latest.

Never makes assumptions when you are debugging or reporting issues. Stick with facts.
So check the version and put it in the Issue so everyone knows - saves a lot of wasted time.

**Comment by Tom-Development** [comment]
Unfortunately not all of us have time to spend setting up a new instance just to test a bug, I did my bit by reporting it in the first place. 

Also, I couldn't do anything more than assume when I tested that, that is also why I _didn't_ include it in the original bug report because I did not know the definite version....

**Comment by reetp** [comment]
> Unfortunately not all of us have time to spend setting up a new instance just to test a bug, I did my bit by reporting it in the first place.
> 

I'm a volunteer here. I don't make any money out of Rocket. My time is actually pretty precious as well.

If you are administering a server you should keep a test machine in your back pocket at all times. It is effortless with today technology.

> Also, I couldn't do anything more than assume when I tested that, that is also why I _didn't_ include it in the original bug report because I did not know the definite version....

If you don't follow the bug reporting guidelines you are going to get ignored. Like an awful lot of other 'bugs' here.

https://rocketchat.github.io/docs/contributing/reporting-issues/
> Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.
> Try to narrow it down to reproducible steps. If we can reproduce it, we will be able to fix the issue a lot quicker.

I am trying to help you to write better bugs so you will get listened to, and get things fixed faster. 
Simple basic testing that you can do yourself helps the developers and speeds things up enormously.

Assumptions and guesswork just get ignored. They cannot be replicated so cannot be tested. No replication, no bug - it's the first rule of debugging.
