### ISSUE TITLE
Feature Request - Add recapture to login/register screen.

### ISSUE THREAD

**Issue by Tom-Development** [RocketChat/Rocket.Chat#15565]
I think adding recatphca to the login & sign up screens could be a very easy and simple way to secure an instance of RocketChat without requiring complex configuration or settings.

This feature should be optional from the administration interface, since some people may not want to include this. I think there should be 2 different options, one for login screen and one for the register screen. 

This would then prevent automated bots from trying to login to the server.

**Comment by reetp** [comment]
@rocket-cat close

Had already pointed this out in your last NFR.

This isn't a bug in Rocket.

Please open this in

https://github.com/RocketChat/feature-requests 

But make sure you gave checked for duplicates as this has been asked before.
