### ISSUE TITLE
Use First Name and Last Name Initials For Generating Avatar

### ISSUE THREAD

**Issue by WolfieeifloW** [RocketChat/Rocket.Chat#15562]
### Description:
The option of "Use Full Name Initials to Generate Default Avatar" only seems to use the First Name initial instead of First Name and Last Name initials.

### Steps to reproduce:
1. Go to Administration
2. Go to Layout
3. Select "Use Full Name Initials to Generate Default Avatar"

### Expected behavior:
The avatar should use the First Name and Last Name initial (eg "John Smith" should be "JS").

### Actual behavior:
The avatar only uses First Name intiail (eg "John Smith" shows "J").

### Server Setup Information:
- Version of Rocket.Chat Server: 1.0.3
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by reetp** [comment]
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

"Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue."

You are a long way out of date.

Please test on 2.1.x

**Comment by photoninger** [comment]
This is still the case with 3.3.0.
I think the function in https://github.com/RocketChat/Rocket.Chat/blob/a9872957180059094e50678ec311b2fcef8f61ad/server/routes/avatar/utils.js#L70
should be changed to something like:
```
const getFirstLetter = (name) => name.match(/\b(\w)/g).join('').toUpperCase();
```
If I found a good example on stackoverflow... ;) I am not a JS expert...
