### ISSUE TITLE
Feature request: area with recent chats

### ISSUE THREAD

**Issue by PFight** [RocketChat/Rocket.Chat#15560]
I have decades of contacts and chats. Someone have written me a message, I have read it, and toggled to another chat, to read another new messages. Then I suppose to answer to first contact, but I have forgotten - who was writting me just few seconds ago. 

Suggestion: add area, similar to "Favorites", where last n chats would be shown.

![image](https://user-images.githubusercontent.com/198847/66643531-95a4dc80-ec27-11e9-9dc3-fb5c29580237.png)

**Comment by reetp** [comment]
@rocket-cat close

Feature requests go here:
https://github.com/RocketChat/feature-requests/issues

No idea what Rocket version you are on but....

Set the Channel as a favourite:

![Screenshot_2019-10-11_13-19-39](https://user-images.githubusercontent.com/3800384/66647712-ee757480-ec29-11e9-932b-8d7bd3e10c1c.png)

Group your Favourites:

![Screenshot_2019-10-11_13-18-24](https://user-images.githubusercontent.com/3800384/66647718-f2a19200-ec29-11e9-8fbc-5300a33700ba.png)
