### ISSUE TITLE
Read Receipts are not showing on 2.1.0

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#15578]
# Description:

After upgrading to 2.1.0, **NEW** message read receipts do not show. Existing messages prior to the upgrade show the correct blue check.
https://open.rocket.chat/channel/support?msg=a8cgxeno7RhmbMDMf

### Steps to reproduce:

1. Enable read receipts
2. Read the messages
3. No blue checkmark

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/66771894-71e0d100-ee89-11e9-8fa7-994ea0197d1e.png)

### Actual behavior:

![m8YU0t5mit](https://user-images.githubusercontent.com/6295044/66771709-fa12a680-ee88-11e9-9836-9c7c07517629.gif)

### Server Setup Information:

Key | Value
-- | --
Version | 2.1.0
Apps Engine Version | 1.6.0
Database Migration | 161
Hash | c95663d2cae44464573c20a824c40a9328c29d09

**Comment by reetp** [comment]
Same here on 2.1.0

This works in Custom CSS

```
.color-component-color {
    color: red !important;
}
```

**Comment by reetp** [comment]
I think this may be a duplicate of

https://github.com/RocketChat/Rocket.Chat/issues/15484

Just curious. Why is it seeming to use use the 'Old' Colors and not the 'New' ones?

**Comment by wreiske** [comment]
Yeah this is a duplicate of: #15484
