### ISSUE TITLE
'From address' missing on email for verify email address from profile page ( 1.3.2 )

### ISSUE THREAD

**Issue by mohanbabubb** [RocketChat/Rocket.Chat#15576]
### Description:

From address missing for verify email address , by using the option to send email from the user profile page

### Steps to reproduce:

1. Go to 'My Account' -> Profile -> Update email box
2. Click on Save changes
3. Click on Resend verification email

### Expected behavior:

1. Should receive email with 'from address'

### Actual behavior:

1. From address is blank on the email

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: linux 3.10.0-693.2.2.el7.x86_64 , node- v8.11.4 , os  release - 4.15.0-1043-aws
- Deployment Method: Docker container
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4 
- MongoDB Version: 4.0.5

### Additional context

Nil

### Relevant logs:
Nil

**Comment by mohanbabubb** [comment]
any improvement is appreciated. or some one point the location on code. so i could contribute.

**Comment by mohanbabubb** [comment]
+1 if any one fixes!

**Comment by ritwizsinha** [comment]
Working on it
