### ISSUE TITLE
The cancel button in the popup dialog has weird background

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#15588]
### Description:
In the web version of Rocket chat , the style of the cancel button in the dialog window which appears on leaving the room seems unprofessional and weird because of having no container and grey background .
![Screenshot from 2019-10-15 20-13-50](https://user-images.githubusercontent.com/43509699/66843426-66c19a00-ef8a-11e9-8ed0-4a77fb0a88ed.png)

### Steps to reproduce:

1. Any channel options button
2. Click on Leave Room .
3. Observe the dialog box that appears

### Expected behavior:

It would be better if there was some container for that cancel button . 
For example https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiQ76Tqwp7lAhXKRo8KHVDUA6UQjRx6BAgBEAQ&url=https%3A%2F%2Fcrossbrowsertesting.com%2Fblog%2Ftest-automation%2Fautomated-test-pop-ups-alerts%2F&psig=AOvVaw1JPL-rC92NcU5ASl7Rrvjt&ust=1571237735380175

### Server Setup Information:

- Version of Rocket.Chat Server: 2  .1 .0
- Operating System:  Ubuntu 18.04.3
  on  Google Chrome .

**Comment by ritwizsinha** [comment]
In this reference I would like to say that the ui of all of the popup boxes are like this for example
![Screenshot from 2019-10-19 11-31-51](https://user-images.githubusercontent.com/43509699/67138628-184f1c80-f264-11e9-84da-5b80ebf6e76e.png)
Is it a problem or the design scheme ?

**Comment by ritwizsinha** [comment]
@MartinSchoeler  can I work on this ?

**Comment by ritwizsinha** [comment]
@tassoevan  can I work on this ?

**Comment by ritwizsinha** [comment]
Can anyone please tell me where the file for this modal is located ? 
I have been able to find a file named fullModal but it doesn't seem to be the same

**Comment by ggazzo** [comment]
`/app/ui-utils/client/lib/modal.html`

**Comment by ritwizsinha** [comment]
@ggazzo @MartinSchoeler Please review

**Comment by ritwizsinha** [comment]
@ggazzo @MartinSchoeler @tassoevan please review

**Comment by reetp** [comment]
> @ggazzo @MartinSchoeler @tassoevan please review

You do not need to "@" people all the time.

The devs get all the issue reports - they don't need extra pings. It just gets annoying, especially if you ping the wrong people.

Also note that their priorities may not be the same same as yours so you might have to be patient.

**Comment by ritwizsinha** [comment]
I am very sorry for this , I was used to pinging others for reviews in projects. Will take care next time
