### ISSUE TITLE
Existing threads behaviour when threads are disabled

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#15587]
### Steps to reproduce:

1. Start a thread somewhere.
2. Disable threads
3. Open the created thread

### Expected behavior:

In my opinion the thread should open, but it should be read only

### Actual behavior:

A toast with the error "Not allowed" shows up and the thread sidebar loads indefinitely
![image](https://user-images.githubusercontent.com/20868078/66836866-80d28c80-ef38-11e9-8619-588925740b7c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0-develop

**Comment by carpecodeum** [comment]
i want to work on it

**Comment by carpecodeum** [comment]
i want to work on this

**Comment by carpecodeum** [comment]
hey @MartinSchoeler i was thinking to remove the message box when threads are disabled. does that sound fine?

**Comment by abhishuraina** [comment]
I am working on it.

**Comment by subham103** [comment]
The current behavior is, if the thread is already open and we disable thread, we can see the messages on that thread plus can add replay on that thread, but those messages (after disabling the thread) comes with a grey color.

![Rocket Chat(1)](https://user-images.githubusercontent.com/43502196/75488642-be5f2000-59d6-11ea-86fc-80a34258df1a.png)

But if the thread is closed and we disable the thread, then it shows not allowed as mentioned above. Will try to work on this issue:)

**Comment by subham103** [comment]
The thread's side-bar can be easily shown by removing the check. The big question is Should we give the option to write on the thread after it is disabled? I think it should be read-only as mentioned by MartinSchoeler, and we should remove the input box inside the side-bar if the threads are disabled.

@MartinSchoeler , guide us to the intended behavior
