### ISSUE TITLE
Rocket Chat fails to load channels in IE10

### ISSUE THREAD

**Issue by pickinmachine** [RocketChat/Rocket.Chat#1558]
Noticed that Rocket Chat is failing to load content with IE 10.  The demo site loads properly but the channel stream is empty.  I didnt see any list of supported browsers, but from older threads it seemed like IE10 worked at some point.  

Appreciate if you could take a look and let me know.  Thanks!

**Comment by adampk90** [comment]
Here's the debug console I'm getting in IE10 mode: 
![ie10_fail](https://cloud.githubusercontent.com/assets/2799877/11570699/7107df56-99ad-11e5-9072-c02246d80b76.jpg)

**Comment by adampk90** [comment]
Here's the console output I'm getting while in IE10 mode:
![ie10_fail](https://cloud.githubusercontent.com/assets/2799877/11571545/c49e6dca-99b1-11e5-8295-a7aa5d2bc7b3.jpg)

**Comment by mnt** [comment]
@RocketChat/core @marceloschmidt @pickinmachine 

No problems for me. 
Currently on 0.34.0

**Comment by adampk90** [comment]
Yep, looks like it's resolved now
