### ISSUE TITLE
Access to admin info page

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#15584]
### Description:

I think the information page should not be accessible if there is no permission

### Steps to reproduce:

1. Login to Rocket.Chat as a User (not Admin)
2. Open https://open.rocket.chat/admin/info

### Expected behavior:

I should get an error 404 Not Found

### Actual behavior:

![image](https://user-images.githubusercontent.com/19654261/66825758-5c8ca500-ef64-11e9-9fad-85025345e37f.png)

**Comment by reetp** [comment]
Wasn't this opened before somewhere?

Someone asked if it was a security risk or similar?

**Comment by ggazzo** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/11721
