### ISSUE TITLE
Duplicate label name 'Hide Avatars' in Accounts

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15585]
Rocket v2.1.0
(tested on two different installs)

Duplicate label name 'Hide Avatars' in Accounts

![Screenshot_2019-10-15_12-55-11](https://user-images.githubusercontent.com/3800384/66826126-00b62200-ef4c-11e9-9277-3067fca8dc37.png)

These are the two settings concerned:

Accounts_Default_User_Preferences_hideAvatars
Accounts_Default_User_Preferences_sidebarHideAvatar

**Comment by rajvaibhavdubey** [comment]
@ggazzo are these two settings `Accounts_Default_User_Preferences_hideAvatars` and `Accounts_Default_User_Preferences_sidebasrHideAvatars` supposed to perform different tasks?
From what I found, I think these are duplicate variables for the same feature.

**Comment by ggazzo** [comment]
its a little bit messy buy yep, they are different, one is to hide avatars on the sidebar, the other hides on the room view
