### ISSUE TITLE
GUI for channel custom fields

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#15590]
Since RC 0.62 there is an API hook for channel custom fields: https://rocket.chat/docs/developer-guides/rest-api/channels/setcustomfields/ It allows e.g. to define a relation of a channel to a project or an organisation.

However, there is no GUi yet to enter or display channel custom field values.  We think the best place is the info area of a channel. Any alternative proposals?

We would like to contribute to this feature, as one of our customers might sponsor this.

Related to #11982

**Comment by CitizenDev** [comment]
Good to see this feature is getting some interest. I've been running my own custom fork because of lack of this feature for a while now.

**Comment by engelgabriel** [comment]
@renatobecker has this been closed by the latest improvements in custom fields?

**Comment by renatobecker** [comment]
> @renatobecker has this been closed by the latest improvements in custom fields?

@engelgabriel I just noticed that this issue/feature request isn't related to the Omnichannel/Livechat custom fields, this is a requirement for custom fields from regular channels other than Omnichannel, which have a purpose and architecture totally different from Omnichannel's custom fields.

**Comment by rasos** [comment]
This is still a desired feature and may be very useful when assigning team related metadata to channels or groups #658.

**Comment by CitizenDev** [comment]
Agreed, we have waited for this feature since 2018. Because of that we are running custom version of quite old rocket.chat.
Now since you are dropping support for legacy versions this is more relevant than ever.
