### ISSUE TITLE
Replies in thread unreadable

### ISSUE THREAD

**Issue by hramrach** [RocketChat/Rocket.Chat#15605]
### Description:

"Reply in thread" option produces unreadable messages in the UI.

### Steps to reproduce:

1. Go to a channel that has messages.
2. In the menu of the message select "Reply in thread"
3. Write a moderately long message.

### Expected behavior:

Message displayed as normal with link for opening the thread.

### Actual behavior:

Message displayed in tiny font, truncated to one line of text.

### Server Setup Information:

- Version of Rocket.Chat Server: {"version":"1.3.2","success":true}
- Operating System: Linux, Chromium

**Comment by reetp** [comment]
I think this is a more a support issue, not a bug.

> * Version of Rocket.Chat Server: Unknown - don't know how to determine

Admin/Info - and this sort of info is really important as per the bug template
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> Message displayed in tiny font, truncated to one line of text.

If you click on a line it will open a window on the right so you can see it full size.

I believe the idea is that threaded conversations don't take too much space in the main window and to differentiate them from non threaded messages.

I believe there is a feature request open somewhere to have the ability to open/close a thread the way you can with file previews etc. Please have a good search.

**Comment by hramrach** [comment]
> > Message displayed in tiny font, truncated to one line of text.
> 
> If you click on a line it will open a window on the right so you can see it full size.
> 
> I believe the idea is that threaded conversations don't take too much space 
but makes them unusable
> in the main window and to differentiate them from non threaded messages.
you can differentiate without making them unusable
> 
> I believe there is a feature request open somewhere to have the ability to open/close a thread the way you can with file previews etc. Please have a good search.
You can. That does not make them usable.

As in you open a channel and what you get is a bunch of messages in tiny font. They are even truncated so you cannot read them even if you eyesight is brilliant. If there are multiple conversations going on an d you want to know what is new you do that how, exactly?

**Comment by reetp** [comment]
@rocket-cat close

As suggested a brief search shows there are already open issues on this.

Please follow the links.
 https://github.com/RocketChat/feature-requests/issues/150

**Comment by yaxu** [comment]
@reetp Requesting the option to minimise threads seems like a different issue to using an unreadably tiny font.
