### ISSUE TITLE
No UI for determining RocketChat version.

### ISSUE THREAD

**Issue by hramrach** [RocketChat/Rocket.Chat#15608]
### Description:

https://rocket.chat/docs/contributing/reporting-issues gives instructions on obtaining RocketChat version.

However, many other web applications manage to present support information in the UI so users do not need to search for it when reporting issues.

**Comment by rasos** [comment]
If you have admin rights you see the version here https://mychatserver.net/admin/info 
End users probably use other 1st level support channels than reporting issues here. 

But why not, the RC version could be displayed e.g. also at https://mychatserver.net/account/preferences visible for any logged in user.

**Comment by MartinSchoeler** [comment]
As @rasos commented, admins can find this info under the admin/info URL.
