### ISSUE TITLE
Audio/Video player stops playing when someone 'reacts' to it

### ISSUE THREAD

**Issue by scrivna** [RocketChat/Rocket.Chat#15604]
### Description:

When listening to an audio clip, if I or another user reacts to the message, the audio stops playing. 
Possibly caused by the message being re-rendered?

### Steps to reproduce:

1. Upload an audio clip and start listening
2. While listening, add an emoji - 'react' to the message
3. My audio stops playing

### Expected behavior:

Audio playback should not be affected by the reaction.

### Actual behavior:

Audio stops playing

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.2

**Comment by MartinSchoeler** [comment]
This is true for youtube links as well

**Comment by ritwizsinha** [comment]
Can I work on it ?

**Comment by ritwizsinha** [comment]
I noticed that except for sending reacts , replying in thread and replying directly also stops the audio clip

**Comment by ritwizsinha** [comment]
@MartinSchoeler can I work on this ?

**Comment by scrivna** [comment]
Hi @MartinSchoeler - any update on when this might get looked at, it's a daily issue we face in our chat room as we regularly share audio clips. Thanks!
