### ISSUE TITLE
Improve the release cycle

### ISSUE THREAD

**Issue by acidicX** [RocketChat/Rocket.Chat#1561]
We currently use RC with up to 10 people for quite a while to evaluate it. One thing we don't really get is the release model, e.g.: why is 0.7 > 0.7.1862?
![bildschirmfoto vom 2015-12-03 13-13-46](https://cloud.githubusercontent.com/assets/1297454/11560311/dbfdce12-99bf-11e5-9edc-9cddeb8851e3.png)

We cannot install ````latest```` every day and see what works and what doesn't.
Is there a plan to move to a better release model that includes:
* major releases are at least smoke tested
* database upgrades are no issues
* ...

?

The GitHub milestones are also incomprehensible...

**Comment by sampaiodiego** [comment]
hey @acidicX , actually @Sing-Li and @engelgabriel are working on realease the model..
trying to automate build generation and documentation.

I hope we'll have it well defined soon.. =)

**Comment by acidicX** [comment]
@sampaiodiego :+1: can't wait! Thanks for the quick answer.

**Comment by engelgabriel** [comment]
@acidicX you are right.. we do know it is messy at the moment. 

We are implementing Atom's automated way of tagging versions and releases based on the results of the CI.

This will be done soon.

**Comment by acidicX** [comment]
@engelgabriel cool thing! You didn't mention testing though - are there going to be tests (and also extended manual testing for major releases)?

I don't know how well you can do database upgrade tests with jasmine or mocha, but that should also be done for major releases.

**Comment by Sing-Li** [comment]
@acidicX  YES - when Meteor is ready.  We jumped into the deep-end with velocity and almost drowned.  MDG is working on 'official test platform' for 2016 and when ready we'll join the rest of the Meteor community and whole-heartedly commit to extensive testing as part of the pipeline.

**Comment by geekgonecrazy** [comment]
I think this is pretty much addressed.  We release pretty much weekly and a consistent version scheme.

Closing..
