### ISSUE TITLE
On resizing the screen the chat screen is hidden under the other sidebar

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#15617]
### Description:
On opening any option present on the chat box and resizing the window to a sufficient size the chat box hides under the options tab opened

### Steps to reproduce:

1. In the channel click on any of the options present in the upper right corner(Like room Info, search etc. )
2. Now resize the screen <=900px
3. The channel box goes behind the options .

### Expected behavior:

This can be corrected in two ways:-
1. Either hide the sidebar containing channel names etc. a little before it is hidden in the current case.
2. Instead of text going behind the options sidebar , it should resize with it .

### Actual behavior:

![image](https://user-images.githubusercontent.com/43509699/67139096-b1ccfd00-f269-11e9-8a7a-18fdf20e1a4b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 18.04

**Comment by ritwizsinha** [comment]
I am a new contributor to RocketChat ,can I work on this issue

**Comment by ggazzo** [comment]
I dont see it as a bug, its how the rocketchat works since we built it ...

**Comment by ritwizsinha** [comment]
Ok, fine then closing this issue
