### ISSUE TITLE
Cannot read property 'username' of undefined 

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#15613]
### Description:
After installing the latest `develop` docker image, the Administration -> Log no longer displays, and the stdout shows the following repeatedly:
```
TypeError: Cannot read property 'username' of undefined
    at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
    at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```
### Steps to reproduce:
1. Deploy latest docker `develop` image (commit 699e6fe as of initial report).
2. Attempt to check logs from app (nothing will display).
3. Multiple errors will be logged to stdout.

### Expected behavior:
No errors should be logged, and log should be displayed.

### Actual behavior:
Constant errors are logged to stdout, and no log page displays.

**Constant errors in docker stdout**
![image](https://user-images.githubusercontent.com/14616851/67059101-4118ca00-f11d-11e9-9202-e26ee8e8869d.png)

**No in-app log!**
![image](https://user-images.githubusercontent.com/14616851/67059048-129aef00-f11d-11e9-8771-d889b474f235.png)

### Rocket.Chat

|                 Version | 2.2.0-develop            |
| ----------------------: | ------------------------ |
|     Apps Engine Version | 1.6.0                    |
|      Database Migration | 162                      |
| Database Migration Date | October 17, 2019 7:05 PM |
|            Installed at | January 25, 2019 5:44 PM |
|                  Uptime | 1 hours, 32 seconds      |
|           Deployment ID | dwPkHnPwaKuHALm6b        |
|                     PID | 1                        |
|       Running Instances | 1                        |
|                   OpLog | Enabled                  |

### Commit

|    Hash | 699e6fe320d66f9b0307b403a8261598182e01f3                     |
| ------: | ------------------------------------------------------------ |
|    Date | Thu Oct 17 23:03:27 2019 +0200                               |
|  Branch | develop                                                      |
|     Tag | 2.1.0                                                        |
|  Author | Mohamed Raafat                                               |
| Subject | [FIX] adjustments for tooltips to show room name instead of id (#14084) |

**Comment by ggazzo** [comment]
@bkraul there are two issues here, abou the empty log: https://github.com/RocketChat/Rocket.Chat/pull/15614

**Comment by reetp** [comment]
Can confirm this is also on two servers I just updated to 2.1.1
```
TypeError: Cannot read property 'username' of undefined
    at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
    at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
SyncedCron ➔ info Not running "Generate download files for user data" again.
SyncedCron ➔ info Not running "Generate download files for user data" again.
SyncedCron ➔ info Not running "Generate download files for user data" again.
SyncedCron ➔ info Not running "Generate download files for user data" again.
Meteor ➔ method readMessages -> userId: FPXrCBzhmd8g7H7cf , arguments:  [ 'JBabXZJW8PBnZbPch' ]
Meteor ➔ method UserPresence:online -> userId: FPXrCBzhmd8g7H7cf , arguments:  [ null ]
Meteor ➔ method UserPresence:away -> userId: 9A8ZQ4nto62NgFsNn , arguments:  [ null ]
SyncedCron ➔ info Starting "Generate download files for user data".
SyncedCron ➔ info Finished "Generate download files for user data".

```

**Comment by reetp** [comment]
(On 2.1.1 I can see View Logs)

**Comment by ggazzo** [comment]
sure because the Log view bug was introduced on 2.2.0-develop, so on  version < 2.2.0 the  log should be working fine...

**Comment by reetp** [comment]
So two different bugs then, and this username defined issue is unrelated to the log issue. Do you know where that bug is?

We ought to split this up?

**Comment by ggazzo** [comment]
sure, but we don't have to split because I already fixed the view log.

and I asked @pierre-lehnen-rc to check the `username` problem

@bkraul pay attention, the 2.1.1 is supposed to be before than develop branch , its not very recommended/healthy downgrade the version... avoid develop and latest release tags, use the version numbers and check the CHANGELOG.md before, thanks :)

**Comment by bkraul** [comment]
@ggazzo I am not sure I understand. Per my report, I am using 2.2.0-develop, not 2.1.1. I understand the develop branch is for the most part unstable, but I use it in order to test fixes and new features.

**Comment by ggazzo** [comment]
SORRY @bkraul , my mistake I thought wrote that... sorry
![image](https://user-images.githubusercontent.com/5263975/67103733-14f05e00-f19c-11e9-9f7d-7b1c640e3565.png)

**Comment by bkraul** [comment]
The issue appears resolved in develop commit 7d29c68, both log view and undefined error. Only message showing is:
```
Checking: checkPreMessageSentPrevent 
Checking: checkPreMessageSentPrevent 
Checking: checkPreMessageSentPrevent 
```
Which I understand to be informational. Thanks for the lightning-fast action, guys!

**Comment by ggazzo** [comment]
Please ignore this log, it's a console.log inside of a dependency, I gonna fix soon as possible

**Comment by bkraul** [comment]
commit 7ef5395 (or any of the commits after 7d29c68) appears to reintroduce this issue:
```
TypeError: Cannot read property 'username' of undefined
    at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
    at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by bkraul** [comment]
By the way, I do not know for sure if this is related, but this seems to be affecting clipboard pastes, where they show as broken/empty images.
