### ISSUE TITLE
The "save changes" button in the profile section of My Account shifts to the left 

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#15626]
### Description:

On clicking the "save changes " in the profile section the button text moves to the left and the loading sticks to the left end .

### Steps to reproduce:

1. Go to My Account
2. Click on Profile on the left
3. Click on the Save changes button

### Expected behavior:

The "save changes" should not move to the left

### Actual behavior:

![Screenshot from 2019-10-22 01-17-23](https://user-images.githubusercontent.com/43509699/67213933-7df60100-f43c-11e9-85be-436479d2685a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 18.04

**Comment by rohitkatlaa** [comment]
Hi, I am Rohit.
@MartinSchoeler  Can I try solving this issue?

**Comment by ritwizsinha** [comment]
I am already working on this issue when I created it , could you please find some other issue @rohitkatlaa ?

**Comment by rohitkatlaa** [comment]
Ok, Since no one was assigned I thought it was unclaimed. My bad.

**Comment by ritwizsinha** [comment]
@MartinSchoeler  please review

**Comment by ritwizsinha** [comment]
@MartinSchoeler please review

**Comment by ritwizsinha** [comment]
@MartinSchoeler please review

**Comment by ritwizsinha** [comment]
@MartinSchoeler please review

**Comment by ritwizsinha** [comment]
Sorry for so many pings

**Comment by igarg2001** [comment]
Hi, I am Ishan. If the bug still persists, could I try solving it?

**Comment by ritwizsinha** [comment]
I am still trying @igarg2001, will surely ping you if I can't do it

**Comment by ritwizsinha** [comment]
This issue is fixed in the current version so closing this
