### ISSUE TITLE
error: 'Can\'t find migration version 162',

### ISSUE THREAD

**Issue by J0kerFace** [RocketChat/Rocket.Chat#15627]
Our Rocket Chat Server doesn´t come up after auto Update to 2.1.1 

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 18.04
- Deployment Method: snap edge

### Relevant logs:

 error: 'Can\'t find migration version 162',

**Comment by geekgonecrazy** [comment]
@J0kerFace please don't use the edge.. use at least the beta channel.  The edge is not meant for production usage

**Comment by geekgonecrazy** [comment]
`snap refresh rocketchat-server --beta` to switch

**Comment by J0kerFace** [comment]
We just try this. But same error.

**Comment by geekgonecrazy** [comment]
looks like maybe you had 2.2.0-develop on edge and then we published 2.1.1 to edge.  Please use one of the community support methods for help.  [#ubuntu-snap](https://open.rocket.chat/channel/ubuntu-snap) being the easiest of these.

**Comment by LuluGO** [comment]
rocketchat-server.mongo
rs0:PRIMARY> use parties
rs0:PRIMARY> db.migrations.update({}, {$set: {version: 161, locked: false}})

and restart rocketchat-server
