### ISSUE TITLE
custom fields text area is not visible in the admin to enter

### ISSUE THREAD

**Issue by rajm** [RocketChat/Rocket.Chat#15637]
### Description:

I am trying to add custom fields in the admin section for the user. but the text area is not being displayed when i check the css, display: none is set, also if i try the full screen mode also i am not the text area is not visible.

I have attached the screenshot below.

### Actual behavior:

![image](https://user-images.githubusercontent.com/72109/67261034-55ade700-f4bc-11e9-913d-306b2e2c3d48.png)

**Comment by MartinSchoeler** [comment]
Not enough information provided. Please follow our issue template, knowing the server version would help a lot.

**Comment by rajm** [comment]
this is the rocketchat version installed on the server

{"version":"2.1.0-rc.0","success":true}

**Comment by antkaz** [comment]
@rajm check settings https://github.com/RocketChat/Rocket.Chat/issues/15497#issuecomment-541310377
This problem may occur in such a case.

**Comment by rajm** [comment]
> @rajm check settings [#15497 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/15497#issuecomment-541310377)
> This problem may occur in such a case.

Thankyou it solved the issue... my bad
