### ISSUE TITLE
[Suggestion] List of users: show also current user (remove exception)

### ISSUE THREAD

**Issue by Wikinaut** [RocketChat/Rocket.Chat#15660]
As a new user of RC, I am very annoyed that my own user name is not listed. Other messenger systems like Slack and Mattermost do not suppress the own name in the list of users (purpose: quick access to one own's handle).

Therefore I suggest to remove the exception:
https://github.com/RocketChat/Rocket.Chat/blob/7164a2db7a6c8fec63ac2941fa762bdabab9af5c/server/methods/browseChannels.js#L103

and to replace that line with

```const exceptions = [];```

**Comment by reetp** [comment]
Please fill in a bug template to properly describe the issue.
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Which version are you on? And where does this occur?? Searching in a channel list?

> As a new user of RC, I am very annoyed that

Don't get annoyed. It doesn't help any one.

Remember, it may be annoying to you, but not necessarily to others. So making things switchable, and not forcing a change for people who are happy the way things are (like me), is a much better idea.

**Comment by Wikinaut** [comment]
@reetp Where can I find the version information, it's not apparent on https://rocket.events.ccc.de .

Regarding where the (own) account is not shown for the owners themselves:
It's the "Verzeichnis" list of users:

![grafik](https://user-images.githubusercontent.com/1151915/67478656-c1c75100-f65c-11e9-86ad-f8a362bcf8c0.png)

![grafik](https://user-images.githubusercontent.com/1151915/67478663-c68c0500-f65c-11e9-824c-66bfb80a7a88.png)

**Comment by reetp** [comment]
> @reetp Where **exactly** can I find the version information, it's not apparent on https://rocket.events.ccc.de ?

You need to be an admin. It is the first page in Administration.

> Regarding where the (own) account is not shown for the owners themselves:
> It's the "Verzeichnis" list of users:
 
Not something I was ever aware of or needed personally.

As I said, make it 'switchable' but also note there may be a good reason why it is the way it is.

**Comment by ggazzo** [comment]
closed at 3.1.0 (:
