### ISSUE TITLE
Channel name does not support Chinese char

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#15668]
When I wanted to create a chat room, I found that I could not input Chinese；
Hope PM could improve as soon as possible, thanks!

 
![image](https://user-images.githubusercontent.com/12368358/67537519-52119e80-f70e-11e9-84cd-d3d053c39414.png)

**Comment by tassoevan** [comment]
We can't help you because you have not filled in a proper bug template.

First read this:
https://rocket.chat/docs/contributing/reporting-issues

Then use this as a template:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Thanks!
