### ISSUE TITLE
Proper names reverting to username in thread

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15662]
Rocket.Chat 2.1.1 Docker (checked on two instances)

Just noticed this morning when I click on a thread the 'Real' names are getting changed to usernames.

The name of the thread creator stays the same, but any one else in the thread gets changed to username.

Bit of video to demonstrate - notice in the right pane when I click on Replies - you can see the name change (I hope)

Seems to have occurred after updating from 2.1.0 to 2.1.1

Once it has changed it will not revert back.

![animation](https://user-images.githubusercontent.com/3800384/67473511-1cf44600-f653-11e9-95df-5c043512389f.gif)

**Comment by rajvaibhavdubey** [comment]
@MartinSchoeler @reetp I would like to take this up. 
Thankyou :smile:

**Comment by reetp** [comment]
Clearly a regression. Hopefully you can find it.

**Comment by localguru** [comment]
@reetp John, exactly the same problem I have here on my live server (version 2.2.0) too. The `name` of the creator of the thread is displayed (first message). For all further messages either the `username` is displayed directly or after a reload the `name` changes to the `username`. Strangely enough, my test system, which should be configured identically and runs on the same version, does not behave like this. On another live system with version 2.1.1 the problem does not occur either.

**Comment by reetp** [comment]
See 15734

I have a feeling someone has been messing about with defaults???
