### ISSUE TITLE
Custom emoji name and alias cannot use utf-8 encoded characters

### ISSUE THREAD

**Issue by ppcat** [RocketChat/Rocket.Chat#15669]
### Description:
I cannot upload custom emoji file in utf-8 encoded characters(Chinese for example), but it used to be worked before. The name and alias will be translated to some encoded string automatically.

### Steps to reproduce:

1. Go to 'Administration -> Custom Emoji'
2. Click on 'Add New Emoji' button
3. Fill in the name and alias field in Chinese ('火箭' for example)
4. Click on 'Choose File' button and select the emoji file
5. Click on 'Save' button

### Expected behavior:
<img width="746" alt="expect" src="https://user-images.githubusercontent.com/776439/67546175-403ff380-f72e-11e9-8ba4-38e2d2242f24.png">

### Actual behavior:
<img width="746" alt="actual" src="https://user-images.githubusercontent.com/776439/67545924-6f099a00-f72d-11e9-84e0-b484941a1e5b.PNG">

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 14.04.06
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.12

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 77
- Operating System: Windows 10

### Additional context
I'm not sure if auto translation of emoji name/alias is a new feature or not. I just want to use `:火箭:` to use custom emoji, not `:huo3_jian4:`.  Thank you for great effort.

**Comment by kuroneko0441** [comment]
Any update here?
