### ISSUE TITLE
When uploading a file in rocket-chat, it does not load. V 2.1.0

### ISSUE THREAD

**Issue by silvaalves03** [RocketChat/Rocket.Chat#15665]
![rocket chat](https://user-images.githubusercontent.com/40240946/67515873-eed42d80-f675-11e9-8fb9-0ada8cc16458.png)

**Comment by reetp** [comment]
Please follow all thid and write out your server details and some log details as per the template.  Help the developers to help you, assuming it isn't a configuration issue.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

Before going too far I would check your proxy settings and your websocket.

You can find out how to do that here:
https://open.rocket.chat/channel/support

Follow this link:
https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98
