### ISSUE TITLE
rocke-chat local Não deixa alterar foto do avatar. Versão 2.1.0

### ISSUE THREAD

**Issue by silvaalves03** [RocketChat/Rocket.Chat#15664]
Não estou conseguindo alterar foto do avatar. Faz duas semana que isso ocorreu. 

@sampaiodiego

**Comment by silvaalves03** [comment]
Problema foi resolvido. Atualizei o aplicativo resolveu.

**Comment by d-gubert** [comment]
Please post issues in English - not everyone in this community understands Portuguese :)

**Comment by silvaalves03** [comment]
Sorry!
