### ISSUE TITLE
Unicode regex support

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1566]
Currently `UTF8_Names_Validation` by default supports English letters only. Similarly when creating an avatar based on username initials in `avatar.coffee` it only allow characters in this range `A-Za-z0-9`.

However, instead of finding every regex possible for all supported languages there are Unicode regular expressions that handles all letters: [source](http://www.regular-expressions.info/unicode.html)

> You can match a single character belonging to the "letter" category with \p{L}
> You can match a single character not belonging to that category with \P{L}

so the regex can be written as `[\p{L}0-9]` instead of `[A-Za-z0-9]`. However, javascript does not have native support for these unicode regex. 

I see two solutions for such problem:
1- Include an addon js library that supports unicode regex (such as https://github.com/slevithan/xregexp)
2- Change all hard-coded regex to variables that can be set from the Administration page just like `UTF8_Names_Validation`
##

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
