### ISSUE TITLE
Does Community Version support 1W+ pepole,and why ?

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#15670]
Does Community Version support 1W+ pepole,and why ?

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

This seems to be a setup/support issue.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
