### ISSUE TITLE
Feature Request: Message Action Button for Threads and more?

### ISSUE THREAD

**Issue by goaround** [RocketChat/Rocket.Chat#15672]
The threads feature is extremely helpful to respond to a message but its always a pain for me that I need two clicks to start a new thread. I think it would be a helpful feature to add an Action Button beside the current emoji button (and more?) like slack does it:

![grafik](https://user-images.githubusercontent.com/5927337/67572130-e04d4b00-f735-11e9-950a-928824309e0c.png)

![grafik](https://user-images.githubusercontent.com/5927337/67572164-f5c27500-f735-11e9-9ae6-d3bfecbd7dab.png)

**Comment by antkaz** [comment]
I can do it

**Comment by goaround** [comment]
@antkaz awesome!

**Comment by antkaz** [comment]
![threads](https://user-images.githubusercontent.com/19654261/67660494-b8055c80-f980-11e9-8436-b4bf4ae57ffc.gif)

**Comment by carpecodeum** [comment]
is this still open?

**Comment by reetp** [comment]
> is this still open?

Please read the comments and follow the links. There is already a PR for this but it hasn't been merged yet.
