### ISSUE TITLE
Endless RangeError: Maximum call stack size exceeded in logs

### ISSUE THREAD

**Issue by bmduarte** [RocketChat/Rocket.Chat#15686]
Lately rocketchat keeps crashing and requires a reboot to work again.
After checking the logs, this error keeps appearing:

RangeError: Maximum call stack size exceeded

Out 28 10:51:17 rocketchat rocketchat-server.rocketchat-server[2540]: Exception in setInterval callback: SwitchedToQuery {}
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]: Exception in defer callback: RangeError: Maximum call stack size exceeded
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at appendToResult (packages/minimongo/common.js:1043:14)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/minimongo/common.js:1049:5
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/minimongo/common.js:1049:20
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at doc (packages/minimongo/common.js:607:32)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at match.result.subMatchers.every.fn (packages/minimongo/common.js:515:25)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at Array.every (<anonymous>)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at Matcher.docOrBranches [as _docMatcher] (packages/minimongo/common.js:514:32)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at Matcher.documentMatches (packages/minimongo/matcher.js:62:17)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/mongo/oplog_observe_driver.js:389:48
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at Object.Meteor._noYieldsAllowed (packages/meteor.js:848:12)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at OplogObserveDriver._handleDoc (packages/mongo/oplog_observe_driver.js:388:12)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/mongo/oplog_observe_driver.js:874:14
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at _IdMap.forEach (packages/id-map/id-map.js:51:35)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/mongo/oplog_observe_driver.js:873:18
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at Object.Meteor._noYieldsAllowed (packages/meteor.js:848:12)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at OplogObserveDriver._publishNewResults (packages/mongo/oplog_observe_driver.js:851:12)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at OplogObserveDriver._runQuery (packages/mongo/oplog_observe_driver.js:758:10)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/mongo/oplog_observe_driver.js:699:14
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at packages/meteor.js:620:25
Out 28 10:51:18 rocketchat rocketchat-server.rocketchat-server[2540]:     at runWithEnvironment (packages/meteor.js:1356:24)

Is it normal?

**Comment by ggazzo** [comment]
@bmduarte could you provide your server version , OS and how you deployed(docker, snap) ? thanks

**Comment by bmduarte** [comment]
Hi @ggazzo 

It's a snap based deploy:

Version - 1.3.2
App Engine Version - 1.5.2
DB Migration - 149
