### ISSUE TITLE
Channel name does not support Chinese char

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#15684]
### Steps to reproduce:

Create a channel name with Multibyte character just like Chinsese

### Actual behavior:

![image](https://user-images.githubusercontent.com/12368358/67645208-343c7780-f962-11e9-9b4a-1ca89b242815.png)

### Server Setup Information:

lastest snap version

### Client Setup Information

chrome lastest  version

### Additional context
no

### Relevant logs:

no

**Comment by 564064202** [comment]
why nobody

**Comment by 564064202** [comment]
any body here?

**Comment by 564064202** [comment]
someone here?

**Comment by MartinSchoeler** [comment]
This is more likely a setting not set properly set than a bug, please make sure that the setting `UTF8 Names Validation` under `Administration -> General -> UTF8` has a valid regexp value.

Thanks!
