### ISSUE TITLE
LiveChat client end not updating automatically

### ISSUE THREAD

**Issue by rrader92** [RocketChat/Rocket.Chat#15682]
Hello, I have installed RocketChat on Centos 7.7 and have it on an Apache SSL Reverse Proxy. Regular chat works just fine but I am having issues with LiveChat. On the client side I get the following issue.

WebSocket connection to 'wss://chat.commercialloandirect.com//websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

and then

WebSocket is already in CLOSING or CLOSED state.

When I type on the client side and hit send nothing appears on the client side but the admin side does update and I can see the client's message. If I type a response on the admin side, the admin side updates but I don't see the response on the client's side. If I reload or scroll to the top of livechat on the client side it will load the response. Any idea of a solution to fix the issue?

https://www.commercialloandirect.com/test.html
![test3](https://user-images.githubusercontent.com/52583084/67640626-250de900-f8d2-11e9-92ba-f0abfc1bbdc4.gif)

![Capture](https://user-images.githubusercontent.com/52583084/67640664-571f4b00-f8d2-11e9-96a9-ad0e53a8e518.PNG)

**Comment by rrader92** [comment]
figured it out, It was an issue with my apache config. Closing now.

**Comment by grestrepo** [comment]
Hello, how did you solve the problem? I have exactly the same problem and I have not been able to solve it.
