### ISSUE TITLE
The emojis doesn't show up when used with a dot after a sentence 

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#15695]
### Description:
Whenever I write a sentence and end it with a full stop and try to attach an emoji to it then the emoji
doesn't render and only the the text emoji shows up . 

### Steps to reproduce:

1. Write a sentence and end it with a  "." 
2. Attach an emoji without a space
3. Send the message and observe that the emoji doesn't render on the chat

### Expected behavior:

The emoji should render normally

### Actual behavior:

![image](https://user-images.githubusercontent.com/43509699/67785643-8fba5280-fa93-11e9-85ae-12cf6892793f.png)

### Client Setup Information

- Desktop App or Browser Version: Browser :- Version 77.0.3865.120 (Official Build) (64-bit)
- Operating System: Ubuntu 18.04

**Comment by gabriellsh** [comment]
sure, go ahead

**Comment by ritwizsinha** [comment]
Could you direct me to the relevant files

**Comment by ritvikjain99** [comment]
@ritwizsinha you still working ? I wanna take up the issue!

**Comment by ritwizsinha** [comment]
@ritvikjain99 feel free to take up the issue if I dont make a pr in 2 days, I was not actually able to make progress due to not being able to find the file for the change, which I found yesterday
