### ISSUE TITLE
OAuth pulled info.

### ISSUE THREAD

**Issue by tammer123** [RocketChat/Rocket.Chat#15693]
Hello,

Is there a way to get both first name and family name to the Name field? OAuth I'm using gives me both, but I can't find a way to get them both.
And another things is : Is there a way to get E-Mail field added or filled by itself as well. Again, my OAuth gives the info.

**Comment by benkroeger** [comment]
once #15690 landed, this can be achieved like so:
`nameField: '{{first_name}} {{last_name}}'`
`emailField: '{{first_name}}.{{last_name}}@foo.com'` or e.g. `emailField: 'upn'` (if your email value is provided in the `upn` property

**Comment by tammer123** [comment]
But right now in the Custom OAuth section I only see 3 fields : Username, Name Field and Avatar Field, but no email field. How can I get the emailField in there?

**Comment by benkroeger** [comment]
you can't. #15690 also adds the emailField feature
