### ISSUE TITLE
make file:/// urls show up as links

### ISSUE THREAD

**Issue by acomputerwiz** [RocketChat/Rocket.Chat#15692]
For example https://example.com will show up as a link but:

`file:///P:\Phones\Bills\1222.pdf`

For example does NOT show up as a clickable link, even though it is valid syntax for a link.

**Comment by ankar84** [comment]
I think, if it will be imlpemented, Lotus Notes link like notes:// will work too. It would be great!

**Comment by engelgabriel** [comment]
This may cause a security issue, so I don't think we should implement it.
