### ISSUE TITLE
Manual config push notification

### ISSUE THREAD

**Issue by qhu91it** [RocketChat/Rocket.Chat#15696]
I have a question about config key for push notification, in ios generator key string like
```
-----BEGIN ENCRYPTED PRIVATE KEY-----
... key ...
-----END ENCRYPTED PRIVATE KEY-----
or
-----BEGIN CERTIFICATE-----
... cer ...
-----END CERTIFICATE-----
```
Do I need copy all?
![Rocket chat push config](https://i.imgur.com/dLIxeCs.png "Rocket chat push config")

**Comment by reetp** [comment]
@rocket-cat close

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

This seems to be a setup/support issue.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/
 
 Please also be aware of this:

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

**Comment by cronberry** [comment]
@qhu91it 

Please see demo video for better push notifications services: https://www.youtube.com/watch?v=7F9XUshJTKo
This will resolve all issues of push notification.
For more details, please visit, www.cronberry.com
