### ISSUE TITLE
Problem: How to integrate Active Directory LDAP users in rocketchat

### ISSUE THREAD

**Issue by haprodev** [RocketChat/Rocket.Chat#15701]
After the sync process is approved, the usernames in LDAP or Active Directory will not sync with the Chat Rocket Users Panel, and no Users in ldap(active directory) will be transferred to the Chat Rocket Users Panel.

**According to this guide:**
https://www.youtube.com/watch?reload=9&v=H8C5_ujWm2c
Rocket.Chat #10 How to integrate Active Directory LDAP users in rocketchat

**information ROCKET.CHAT:**
rocket.chat version : 2.0.0-develop
Engine : 1.5.2

**Related Error:**

**> I20191030-14:26:38.245(3.5)** server.js:212 LDAP ➔ Search.error { NoSuchObjectError: No Such Object     at messageCallback (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20) lde_message: 'No Such Object', lde_dn: 'dc=ictsg,dc=com' } 

**> I20191030-14:26:38.246(3.5)** Exception in callback of async function: { NoSuchObjectError: No Such Object     at messageCallback (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1419:45)     at Parser.onMessage (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1089:14)     at emitOne (events.js:116:13)     at Parser.emit (events.js:211:7)     at Parser.write (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/messages/parser.js:111:8)     at Socket.onData (/home/jb/Desktop/Rocket.Chat/node_modules/ldapjs/lib/client/client.js:1076:22)     at emitOne (events.js:116:13)     at Socket.emit (events.js:211:7)     at addChunk (_stream_readable.js:263:12)     at readableAddChunk (_stream_readable.js:250:11)     at Socket.Readable.push (_stream_readable.js:208:10)     at TCP.onread (net.js:597:20) lde_message: 'No Such Object', lde_dn: 'dc=ictsg,dc=com' }

**Comment by reetp** [comment]
@rocket.cat close

This appear to be a configuration/support issue rather than a bug.

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> **Before reporting a new issue**
> Read the Documentation carefully all the way through.
> Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

Latest is 2.2.0 - please test there first.

If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support
