### ISSUE TITLE
Integrate into Firebase and Angularfire

### ISSUE THREAD

**Issue by warain** [RocketChat/Rocket.Chat#1570]
I would like to integrate this application into Angularfire to take advantage of what google and firebase has to offer, anybody looking to join this process?
##

**Comment by adinorteylawerteh** [comment]
Well. That will be a good thing. Am in

**Comment by warain** [comment]
I am not formular with mentor, I can take a look at the code, anywhere in particular we can star?

**Comment by graywolf336** [comment]
This application isn't built with Angular, so I don't see how this would work?

**Comment by warain** [comment]
is there any way to integrate firebase REST api

**Comment by adinorteylawerteh** [comment]
I would have to dive deep into the code to see how it works

**Comment by Sing-Li** [comment]
Firebase :+1:    Angularfire :-1:  Reactfire :+1:

**Comment by geekgonecrazy** [comment]
What exactly would be the purpose of integrating Firebase?  As a replacement for our database or what?

**Comment by a7medo778** [comment]
well using firebase as a backbone can almost eliminate the need for a server, i mean you can basically scale infinitely without worrying about scaling the infrastructure
that and slew of ready to be used features

**Comment by Sing-Li** [comment]
So a thought exercise just so I understand the line of thought.

I get into a chat  with 1,000,000 users just to direct message with @geekgonecrazy.   

With firebase and eliminate the need for the server, are you saying every single browser client copy should maintain information on 1,000,000 users so that two can direct message?

**Comment by a7medo778** [comment]
kinda yes
because you would've arranged your database in a way to accommodate all
chats
so you can update the 1,000,000 "room" in the db without even feeling any
kind of load or latency because of the nature of the service

**Comment by Sing-Li** [comment]
Then everyone with more than 1GB of storage requirements will have to pay
$50 a month?


*Sing Li*Core Contributor

sing.li@rocket.chat

+ 55 51 30855151 <+555130855151>

@ <https://demo.rocket.chat/direct/sing.li>sing.li

https://rocket.chat

**Comment by warain** [comment]
@Sing-Li is pricing with firebase you reservation?

**Comment by warain** [comment]
I think what firebase allows us to do is integrate other firebase hosted application well with rocket since,

**Comment by a7medo778** [comment]
chats doesn't really take that much space, images and voice and video are offloaded to s3 anyways 
The ability to have a scalable app with minimum cost and self growing infra is really good for some use cases

Regards
Ahmed

**Comment by Sing-Li** [comment]
Agreed for some use cases. 

Why do they charge $150 a month minimum for _private backup_?  Does it mean that to export data, you need the minimum $150/month plan?  tia

**Comment by Sing-Li** [comment]
@warain I would conservatively estimate that monthly recurring cost is a concern for over 60% of our FOSS user base.  

Just need to understand more before we can even begin considering the priority of this work.

Thanks for all the help and information.

**Comment by MartinSchoeler** [comment]
As this feature will hardly be implemented in the near future, as seen that is not on our roadmap. I will close this. This will be reopened when we reconsider adding this feature. Thanks for all the feedback!

**Comment by geekgonecrazy** [comment]
Feel free to propose in detail on our [forums](https://forums.rocket.chat) for future consideration as a feature
