### ISSUE TITLE
can't log in with Ldap users

### ISSUE THREAD

**Issue by davisbra** [RocketChat/Rocket.Chat#15708]
I configure Ldap on rocket chat and my LDAP users sync correctly by my rocket chat users but I can't log in to rocket chat with LDAP user.
what can I do?

**Comment by reetp** [comment]
@rocket-cat close

This repo is for issues/bugs in Rocket.Chat not support.
https://rocketchat.github.io/docs/contributing/reporting-issues/

You should read this.
https://rocket.chat/docs/getting-support/

https://forums.rocket.chat/
https://open.rocket.chat/channel/support
