### ISSUE TITLE
Add more API to Rocket chat

### ISSUE THREAD

**Issue by longtqdayma** [RocketChat/Rocket.Chat#15714]
I would like to customize and supplement some data query APIs for my own purposes, please help me further.
Thanks.

**Comment by reetp** [comment]
@rocket-cat close

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

For help/support please see: https://rocket.chat/docs/getting-support

New features go here:

https://github.com/RocketChat/feature-requests
