### ISSUE TITLE
Question about NSFW content.

### ISSUE THREAD

**Issue by DillFrescott** [RocketChat/Rocket.Chat#15712]
It says in Rocket Chat's ToS that basically no NSFW (Pornographic) content is allowed. Is this a do all end all or would it be allowed in a DM if both parties consent?

**Comment by MartinSchoeler** [comment]
If you are talking about the code of conduct, it only aplies to our community channels (open server, forums, GitHub, etc...). For other servers you should follow the rules set by its admins, if you own a server you are free to decide the content that should be allowed (apart from illegal stuff obviously). Thanks!
