### ISSUE TITLE
Retention Policy Causes CPU Usage To Grow Out Of Control.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#15724]
### Description:

On busy site, auto pruning is causing heavy cpu usage. The usage grows over time until rocket chat eventually becomes unusable and instances of rocketchat and mongodb need to be restarted. I have a rather active install with up to 200 active users at once and about 6,000 total users. This was not an issue until I upgraded from version 1.3.2 to version 2.2.0. I use a short retention policy to keep the database small. 1 day for room and 7 days for channels.

It may be relevant that I also upgraded mongodb from 3.6 to 4 during this install.
Upgraded npm from 6.4.1 to 6.9.0 during this install as well.

### Steps to reproduce:

1. Have large install with many messages.
2. Use retention policy.
3. Wait while CPU usage grows.

### Expected behavior:

Cpu usage should remain stable.

### Actual behavior:

CPU usage slowly grows to 100% on each instance, almost as if something is hanging.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Centos
- Deployment Method: Tar, manual install
- Number of Running Instances: 5
- DB Replicaset Oplog: yes
- NodeJS Version: 8.15.1
- MongoDB Version:4.0.13

**Comment by reetp** [comment]
What platform/hardware have you got (just so we know)?
What version of CentOS (just so we know)?
What do you see in your logs - both system and rocket?

**Comment by serviceman** [comment]
What platform/hardware have you got (just so we know)?
I'm not understanding what you mean by this question. I am running on an SSD with 8 cores and 32GB of ram.
What version of CentOS (just so we know)?
Centos 7

What do you see in your logs - both system and rocket?
I don't see anything unusual.

**Comment by ggazzo** [comment]
The main problem here is the oplog, for each message deleted we have an event from the mongodb, and the server tries to update each user with this room opened, its quite hard handle a lot of messages... You just found the problem, after the update because the retention policy was not working properly...

**Comment by serviceman** [comment]
This really is something that is required for larger communities. I have 1000's of messages posted daily and my database is quickly growing. Is there any update on a solution for this?

Perhaps a solution to this, for larger communties, when a message is removed due to the retention policy, the messages are not removed from user view until the Rocket Chat client is reloaded. 

With that being said, the retention policy was working on my installs until I did the upgrades listed above. Not sure if it a change due to the rocket chat version, mongodb or npm not playing nicely with each other.

**Comment by serviceman** [comment]
Update, it looks like this issue happens if private messages have a retention policy enforced. There seems to be no problem if it is just for the main channels.

**Comment by serviceman** [comment]
After thinking about what you said regarding oplong I made these changes and things seem to be doing much better. I see no increase in memory/cpu over the last 24 hours. I reduced the size of the oplong, mine was very large. I also updated from mongdb 4.0.13 to 4.0.14, there is a reported memroy leak in 4.0.13. I also included discussions in the punning, discussions are not included by default.

I will keep you updated if I see any increase in cpu or memory. I have a feeling this not so much a rocket chat issue, but more of how mongodb oplong behaves when you combine a large oplong, retention policy and a very active database.

**Comment by serviceman** [comment]
I have discovered the actual issue. I had the retention policy to execute every 30 minutes. Because there were so many messages, it couldn't complete in the 30 minutes, so the processes fired up by the retention policy keeps building up until it overtakes all the available cpu, etc. Seems like there could be a better way to handle the retention policy by auto expiring the documents in the database using a TTL index, instead of the rocketchat client it's self doing the actual deletion.
