### ISSUE TITLE
How can I relaunch Rocket on the server?

### ISSUE THREAD

**Issue by LeCoupa** [RocketChat/Rocket.Chat#1572]
I made a few changes (like replacing the favicons on `/var/www/rocket.chat/public/images/logos`) and I was wondering how I could relaunch the server to take them into account?

Running `meteor build --server "$HOST" --directory .` does not work.

**Comment by engelgabriel** [comment]
You need to run `pm2 restart all`

Did you see the new Assets area on the admin panel?

You can set your favicon there.

![image](https://cloud.githubusercontent.com/assets/1000217/11590164/7d1b42ec-9a75-11e5-97ab-263f8b26ffa4.png)

**Comment by LeCoupa** [comment]
Thank you @engelgabriel! How can I update Rocket? I haven't find something in the wiki.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker#5-update-an-existing-installation-with-the-latest-code

Mind you that this feature is not yet merged into master, it is only on the develop branch.
