### ISSUE TITLE
Iframe Integration can't with http (chrom parent.window.postmessage not work)

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#15726]
### Description:

Iframe Integration can't with http (parent.window.postmessage not work),our site can't support 
https alo

### Steps to reproduce:

no

### Expected behavior:
work with http but chrome not work

### Actual behavior:

can't work

### Server Setup Information:

- lastest Version of Rocket.Chat Server: 
 
### Client Setup Information

no
### Additional context

no

### Relevant logs:

 a08a280a9070db491a2a059a6ea4aff4cd88f19a.js?meteor_js_resource=true:273 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
getDesktopPermission @ a08a280a9070db491a2a059a6ea4aff4cd88f19a.js?meteor_js_resource=true:273
 
 Permission for the Notification API may no longer be requested from a cross-origin iframe. You should consider requesting permission from a top-level frame or opening a new window instead. See https://www.chromestatus.com/feature/6451284559265792 for more details.

**Comment by 564064202** [comment]
any body?

**Comment by reetp** [comment]
> You should consider switching your application to a secure origin, such as HTTPS

This is really an issue with browser support than an issue with Rocket.Chat itself,

If your site can't support https you should move. Browsers are going to refuse to support http at all before long, or at least make it extremely difficult to use.

https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/marking-http-as-non-secure

You might as well sort out https support - with free Letsencrypt certificates there is no reason not too.

**Comment by 564064202** [comment]
I think you can  url? token=balabala

**Comment by MartinSchoeler** [comment]
As @reetp said, this is an issue with browser support, I suggest you move this to the support forums, since github is for bugs and features request, for now I will be closing this. Thanks!
