### ISSUE TITLE
How to run latest version on Raspberry Pi

### ISSUE THREAD

**Issue by Bart1909** [RocketChat/Rocket.Chat#15725]
Hi,

I‘m trying to run RocketChat on a Raspberry Pi 4. I installed via Snaps which runs fine, but this seems to be version 1.0.3 only.

If I try to install manually there seems to be a problem with the sharp package. It installs fine, but when starting RocketChat it throws an error that some sources could not found for armv6...

Is there a way to update the snaps version to >2.x? Or have someone installed from source on a raspberry Pi?

Best wishes

**Comment by Sing-Li** [comment]
@Bart1909  Please see the detailed instructions here:

https://github.com/RocketChat/Rocket.Chat.RaspberryPi

The issue should be posted there as well.  BUT you can just join our open server and get the answer immediately in the https://open.rocket.chat/channel/raspberrypi   channel.

Essentially, you can run a Release 2.x  with a 64bit ARM Linux today.  

Thanks for your question I am closing this.
