### ISSUE TITLE
connect skype with rocket chat

### ISSUE THREAD

**Issue by Vahid-Peivandi** [RocketChat/Rocket.Chat#15735]
I am a beginner and wanna connect my skype channel or group to my rocket.chat channel, that is possible?

if yes please guide me step by step and simple

thanks a lot

**Comment by reetp** [comment]
@rocket-cat close

 Closing notabug.

This seems to be a setup/support issue.
Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

**Comment by reetp** [comment]
At best this would be a NFR.

https://github.com/RocketChat/feature-requests/issues

Skype uses closed protocols so this won't get fixed.
