### ISSUE TITLE
My sign in to RocketChat Marketplace is stuck and cannot install apps

### ISSUE THREAD

**Issue by jwhitewick** [RocketChat/Rocket.Chat#15731]
When I try to install an app i am not able to give me the following error.
{"error":"[Unauthorized] a339a921-b898-4a59-933a-dca24277e53c: %!s(\u003cnil\u003e)\r\n","requestId":"a339a921-b898-4a59-933a-dca24277e53c","status":401}

I try to signout but it keeps me signed in
i tried to login to a completely new account but i am not able to.
i tried to write support no luck.

**Comment by LuluGO** [comment]
Hello, I replied in the ticket.
