### ISSUE TITLE
Username used instead of real name in the quoted message

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#15734]
### Description:

**Login** not convert to **Name** in a quoted message

### Steps to reproduce:

1. User1 write message
2. User2 quotes User1 message
3. You see User1 login instead User1 name in quoted message

### Expected behavior:

I expect to see User1 Name in quoted message

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/68180094-70e02280-ffa3-11e9-954e-24283561d073.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.0
- Operating System: linux
- Deployment Method:
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.12

### Client Setup Information

- Desktop App or Browser Version: 2.16.0
- Operating System: WIndows 10

Same on RN mobile application.

**Comment by reetp** [comment]
Is this related to #15662 ?

Seems similar issues with losing Real Names

**Comment by ankar84** [comment]
Set **Set a User Name to Alias in Message** option  (Message_SetNameToAliasEnabled) to True fixed my problem.
And it is also fixed https://github.com/RocketChat/Rocket.Chat/issues/15662
![image](https://user-images.githubusercontent.com/4023037/69527637-c8a7f300-0f7d-11ea-8a79-77ffc26dc3f6.png)
![image](https://user-images.githubusercontent.com/4023037/69527683-dcebf000-0f7d-11ea-83b3-55ad0f498933.png)
![image](https://user-images.githubusercontent.com/4023037/69527731-f7be6480-0f7d-11ea-8caa-7eb017f2e31f.png)

**Comment by reetp** [comment]
Ahhh - so, was this default changed? Mine is false and I don't see why?

> Set a User Name to Alias in Message
> True  False
> 
> "Only if not already set alias. The old messages alias not changed if user has changed the name."

**Comment by ankar84** [comment]
> Mine is false and I don't see why?
Mine was false too, I think it was default option.

**Comment by Gummikavalier** [comment]
Does anyone know what this alias setting is called in the database and what collection it could be found in?

Aliases not showing in replies issue is still lurking with new installs (three so far for me) and I could not find anything related to this under collection rocketchat_settings in the DB.

**Comment by vanquang9387** [comment]
I can not find the setting `Set a User Name to Alias in Message`

RC Version
4.5.4

**Comment by julienchabanon** [comment]
I can't find Message_SetNameToAliasEnabled on RocketChat 4.3.2 either.
