### ISSUE TITLE
Livechat Avatar URL is worng

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15730]
### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0.12

I was testing the enabling/disable User avatars "Show agent information" and notice the avatar shows a black square.

It seems like the code is adding an extra 'livechat' in the URL

Should be:
https://chat.domain.info/livechat/0895129be54432f826ae14f75a0a9eb4.png

Actual:
https://chat.domain.info/livechat/livechat/0895129be54432f826ae14f75a0a9eb4.png

Agent information enabled:

![Screenshot_2019-11-04_15-04-18](https://user-images.githubusercontent.com/3800384/68126648-83f7e180-ff14-11e9-8c46-0726c82d1310.png)

Agent information enabled:

![Screenshot_2019-11-04_15-02-19](https://user-images.githubusercontent.com/3800384/68126670-91ad6700-ff14-11e9-8ebd-854bec50c606.png)

Links:
![Screenshot_2019-11-04_14-57-24](https://user-images.githubusercontent.com/3800384/68126854-f963b200-ff14-11e9-93e0-349430c26fdf.png)

**Comment by renatobecker** [comment]
Hi @reetp 
The implementation related to the widget-side was not merged yet, because of this you were facing the issue when testing the new setting(`Show agent information`).
Now, it has been merged, as you can see here -> https://github.com/RocketChat/Rocket.Chat.Livechat/pull/279.
