### ISSUE TITLE
Ldap new user Error

### ISSUE THREAD

**Issue by Ufoton** [RocketChat/Rocket.Chat#15739]
Hello,

After upgrade to latest version new users can not login to rocket chat

Nov  5 14:13:38 rocket-chat rocketchat: server.js:204 LDAPSync ➔ error Error creating user { Error: [error-invalid-domain]
Nov  5 14:13:38 rocket-chat rocketchat: at server/lib/accounts.js:308:10
Nov  5 14:13:38 rocket-chat rocketchat: at _validateNewUserHooks.forEach.hook (packages/accounts-base/accounts_server.js:1094:13)
Nov  5 14:13:38 rocket-chat rocketchat: at Array.forEach (<anonymous>)
Nov  5 14:13:38 rocket-chat rocketchat: at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1093:32)
Nov  5 14:13:38 rocket-chat rocketchat: at AccountsServer.<anonymous> (server/lib/accounts.js:180:28)
Nov  5 14:13:38 rocket-chat rocketchat: at executeBound (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:762:67)
Nov  5 14:13:38 rocket-chat rocketchat: at AccountsServer.bound [as insertUserDoc] (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:793:14)
Nov  5 14:13:38 rocket-chat rocketchat: at createUser (packages/accounts-password/password_server.js:1078:25)
Nov  5 14:13:38 rocket-chat rocketchat: at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)
Nov  5 14:13:38 rocket-chat rocketchat: at addLdapUser (app/ldap/server/sync.js:452:29)
Nov  5 14:13:38 rocket-chat rocketchat: at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)
Nov  5 14:13:38 rocket-chat rocketchat: at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)
Nov  5 14:13:38 rocket-chat rocketchat: at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
Nov  5 14:13:38 rocket-chat rocketchat: at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)
Nov  5 14:13:38 rocket-chat rocketchat: at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
Nov  5 14:13:38 rocket-chat rocketchat: at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)
Nov  5 14:13:38 rocket-chat rocketchat: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Nov  5 14:13:38 rocket-chat rocketchat: at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Nov  5 14:13:38 rocket-chat rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Nov  5 14:13:38 rocket-chat rocketchat: at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Nov  5 14:13:38 rocket-chat rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Nov  5 14:13:38 rocket-chat rocketchat: at Promise (packages/ddp-server/livedata_server.js:715:46)
Nov  5 14:13:38 rocket-chat rocketchat: at new Promise (<anonymous>)
Nov  5 14:13:38 rocket-chat rocketchat: at Session.method (packages/ddp-server/livedata_server.js:689:23)
Nov  5 14:13:38 rocket-chat rocketchat: at packages/ddp-server/livedata_server.js:559:43
Nov  5 14:13:38 rocket-chat rocketchat: isClientSafe: true,
Nov  5 14:13:38 rocket-chat rocketchat: error: 'error-invalid-domain',
Nov  5 14:13:38 rocket-chat rocketchat: reason: undefined,
Nov  5 14:13:38 rocket-chat rocketchat: details: undefined,
Nov  5 14:13:38 rocket-chat rocketchat: message: '[error-invalid-domain]',
Nov  5 14:13:38 rocket-chat rocketchat: errorType: 'Meteor.Error' }

Version | 2.2.0
1.7.0
166

**Comment by reetp** [comment]
Not much to go on there so can you please be a bit more descriptive.

Rocket redeployment type eg snap, manual etc?
Mongo version?
Upgrading from what version?

Follow this guide properly please.
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Note:
**A clear and concise description of what the bug is**

Also what happened here?

Error: [error-invalid-domain]

**Comment by Ufoton** [comment]
- Version of Rocket.Chat Server: 2.2.0
- Operating System: Linux
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.3

New user can not login to the chat. No problem for exithing user. Upgrade done from version 1.3.1

**Comment by reetp** [comment]
As per my previous

What happened here?

>LDAPSync ➔ error Error creating user { Error: [error-invalid-domain]

Have you checked your LDAP logs?

**Comment by Ufoton** [comment]
User can authorize on ldap. On Ldap we see succseful login. Ldap type is AD

**Comment by reetp** [comment]
> User can authorize on ldap. On Ldap we see successful login. Ldap type is AD
Yes that is obvious.

What is in your logs when you get a failure.....? There will be something to tell you what has gone wrong.

**Comment by Ufoton** [comment]
In ldap everything is ok. IN rocket.chat 

Nov  5 14:10:39 rocket-chat rocketchat: server.js:204 LDAPSync <E2><9E><94> error Error creating user { Error: [error-invalid-domain]
Nov  5 14:10:39 rocket-chat rocketchat: at server/lib/accounts.js:308:10
Nov  5 14:10:39 rocket-chat rocketchat: at _validateNewUserHooks.forEach.hook (packages/accounts-base/accounts_server.js:1094:13)
Nov  5 14:10:39 rocket-chat rocketchat: at Array.forEach (<anonymous>)
Nov  5 14:10:39 rocket-chat rocketchat: at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1093:32)
Nov  5 14:10:39 rocket-chat rocketchat: at AccountsServer.<anonymous> (server/lib/accounts.js:180:28)
Nov  5 14:10:39 rocket-chat rocketchat: at executeBound (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:762:67)
Nov  5 14:10:39 rocket-chat rocketchat: at AccountsServer.bound [as insertUserDoc] (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:793:14)
Nov  5 14:10:39 rocket-chat rocketchat: at createUser (packages/accounts-password/password_server.js:1078:25)
Nov  5 14:10:39 rocket-chat rocketchat: at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)
Nov  5 14:10:39 rocket-chat rocketchat: at addLdapUser (app/ldap/server/sync.js:452:29)
Nov  5 14:10:39 rocket-chat rocketchat: at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:150:17)
Nov  5 14:10:39 rocket-chat rocketchat: at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)
Nov  5 14:10:39 rocket-chat rocketchat: at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
Nov  5 14:10:39 rocket-chat rocketchat: at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)
Nov  5 14:10:39 rocket-chat rocketchat: at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)
Nov  5 14:10:39 rocket-chat rocketchat: at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)
Nov  5 14:10:39 rocket-chat rocketchat: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Nov  5 14:10:39 rocket-chat rocketchat: at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Nov  5 14:10:39 rocket-chat rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Nov  5 14:10:39 rocket-chat rocketchat: at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Nov  5 14:10:39 rocket-chat rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Nov  5 14:10:39 rocket-chat rocketchat: at Promise (packages/ddp-server/livedata_server.js:715:46)
Nov  5 14:10:39 rocket-chat rocketchat: at new Promise (<anonymous>)
Nov  5 14:10:39 rocket-chat rocketchat: at Session.method (packages/ddp-server/livedata_server.js:689:23)
Nov  5 14:10:39 rocket-chat rocketchat: at packages/ddp-server/livedata_server.js:559:43
Nov  5 14:10:39 rocket-chat rocketchat: isClientSafe: true,
Nov  5 14:10:39 rocket-chat rocketchat: error: 'error-invalid-domain',
Nov  5 14:10:39 rocket-chat rocketchat: reason: undefined,
Nov  5 14:10:39 rocket-chat rocketchat: details: undefined,
Nov  5 14:10:39 rocket-chat rocketchat: message: '[error-invalid-domain]',
Nov  5 14:10:39 rocket-chat rocketchat: errorType: 'Meteor.Error' }

**Comment by Ufoton** [comment]
Hi,
This is some how related to tls. I will continue my investigation

**Comment by Ufoton** [comment]
Hi,
After our investigation: 
This is not related to TLS. Even this not related to new user or system upgrade. For some user we recive this error. For other not. We can not find any relation.

**Comment by shaihulud-eu** [comment]
Resolved:
You should use trim() or something like that while creating users

**Comment by shaihulud-eu** [comment]
problem was in additional tabulation after .com in mail object in AD
