### ISSUE TITLE
Livechat Script points to old URL

### ISSUE THREAD

**Issue by AdriWild** [RocketChat/Rocket.Chat#15749]
### Description:

Yesterday I installed the standard version of Livechat (somehow the new version doesn't work), but **TODAY** it is available only the new one, and I've checked that the script, and it is pointing to my **old URL**.

I have changed from new to old address, everywhere, but somehow internally still asking to the old url.

![image](https://user-images.githubusercontent.com/17620379/68289196-fcca7b00-0085-11ea-9f20-ab11987c2182.png)

shomehow urls are different ( On installation, new, on script old ones)

![image](https://user-images.githubusercontent.com/17620379/68288850-731aad80-0085-11ea-98fd-9db89f54fee2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Linux Debian
- Deployment Method: snap

### Client Setup Information

- Desktop App or Browser Version: Chrome

**Comment by renatobecker** [comment]
Hi @AdriWild. We changed the `publicPath` of the Livechat bundle so I suggest you update your server to `2.2.0` release, then check the script installation.
You'll probably need to update the script on your website or where Livechat the installed.

**Comment by AdriWild** [comment]
I have 2.1.1 Version and I get "snap rocketchat-server has no updates available"

How can I update to version 2.2.0 ?

**Comment by ashwaniYDV** [comment]
@renatobecker-zz Is this issue stiil relevant?

**Comment by renatobecker** [comment]
We don't support the old livechat widget anymore, so please update your script according to the `Installation` page.

Thanks.
