### ISSUE TITLE
Footer logo not showing up after update

### ISSUE THREAD

**Issue by larsziegelmann** [RocketChat/Rocket.Chat#15753]
After updating to versions 2.1.1 and 1.6.0 on the 6th of November, the footer logo stopped working in our chat. I get this symbol showing: 
![image](https://user-images.githubusercontent.com/54264704/68372307-e2a1a300-0140-11ea-9e91-6d3a4465f261.png)

I checked the image file in _Assets -> logo_ and it was still in the right place like it was before. 
When clicking the logo, you should be redirected to our Rocket.Chat homepage. That still happens. :)

Does anybody have a solution for this? Does this have anything to do with the new version?

We're using rocket.chat as a snap.

**Comment by larsziegelmann** [comment]
Advancements: I've removed the logo, but the icon is still showing up with the link. 
I've reuploaded the logo, but still the same error.
I've deleted the cache of my browser, but it didn't help.

**Comment by reetp** [comment]
You haven't actually said what the actual image URL that is failing.

Most likely it is due to changes in Rocket as this has been reported before.

https://github.com/RocketChat/Rocket.Chat/issues/15386#issuecomment-532115486
