### ISSUE TITLE
Messages/channels are randomly not set to "read" automatically.

### ISSUE THREAD

**Issue by rsimai** [RocketChat/Rocket.Chat#15750]
As follow up to https://github.com/RocketChat/Rocket.Chat/issues/12743 which I can not reopen.

### Description:

Messages/channels are randomly not set to "read" automatically. 

### Steps to reproduce:

* Sidebar sorted by unread on top
* click the channel when it's bright/bold and has a new message

I couldn't see a pattern, it just happens randomly.

### Expected behavior:

The channel should be marked read after changing to it and when all unread messages were seen.

### Actual behavior:

The channel randomly shows as unread, even after accessing the channel and scrolling up to the first unread, or if there's only one new message and it's fully displayed. ESC works as expected and sets it to read immediately.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Linux
- Deployment Method: k8s
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.11

### Client Setup Information

- Desktop App or Browser Version: various, e.g. Chrome, Firefox
- Operating System: mostly Linux

### Additional context

We experience this massively after an upgrade from 1.x to the current 2.2.0

### Relevant logs:

Need advise on which logs you want to see.

**Comment by dcermak** [comment]
I can confirm this issue on the same server with the Rocket.chat App from Flathub.

**Comment by zdumitru** [comment]
Could be related to #15471 .

**Comment by rsimai** [comment]
Seems I had missed #15471 and it seems in fact the same symptom. Good to close this one.
