### ISSUE TITLE
iOS Push Notification is not working

### ISSUE THREAD

**Issue by Shing-Ho** [RocketChat/Rocket.Chat#15759]
### Steps to reproduce:

1. I customize the rocket.chat web app and mobile app. I am testing the push notification, in android it is working well, but in ios it is not working.
2. I set enable gateway in the /administration/push to false.
3. I set the APN Passphrase as the password of the key file. And APN Key starts from 
`-----BEGIN ENCRYPTED PRIVATE KEY-----` and ends with `-----END ENCRYPTED PRIVATE KEY-----` and also APN Cert starts from `-----BEGIN CERTIFICATE-----` and ends with `-----END CERTIFICATE-----`.
But one thing I misunderstood is when I generate Key.pem using `openssl pkcs12 -nocerts -out key.pem -in cert.p12` I could see two patterns of private key.

### Expected behavior:

`
I20191110-06:37:11.307(-5) Got error code 513 for token a689f82c9c678dac22165bb2eb32e1bbf576c0bebb47c527056e8530abb7de57 
I20191110-06:37:11.308(-5) Got error code 513 for token 2b23451106fcea6734da396bf4973cf71e031dce5f19e24efa8d0c00a7f31a38 
I20191110-06:37:11.309(-5) Exception in callback of async function: { Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt     at Object.createSecureContext (_tls_common.js:104:17)     at Object.exports.connect (_tls_wrap.js:1062:48)     at apnSocket (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/apn/lib/socket.js:60:19)     at Connection.<anonymous> (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/apn/lib/connection.js:175:17)     at /home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:1249:26     at _fulfilled (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:854:54)     at self.promiseDispatch.done (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:883:30)     at Promise.promise.promiseDispatch (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:816:13)     at /home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:570:49     at runSingle (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:137:13)     at flush (/home/raspicks/bundle1/bundle/programs/server/npm/node_modules/meteor/rocketchat_push/node_modules/q/q.js:125:13)     at _combinedTickCallback (internal/process/next_tick.js:132:7)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   opensslErrorStack:     [ 'error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib',      'error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error',      'error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error' ] } 
`
This is the issue that I get

### Actual behavior:
Push notification should work.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: centos
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 8.15.1
- MongoDB Version: 4.2.1

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by reetp** [comment]
@rocket-cat close

This looks like a support issue and not a bug in Rocket.Chat 

You haven't filled in the details properly as requested as per the template here:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

These details are really important to try and help diagnose issues.

Also please read these:

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

Also read this:
https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

You should probably be working with the React Native client.

If you can show there is an actual bug in Rocket then please re open.
