### ISSUE TITLE
Rocketchat socket Error

### ISSUE THREAD

**Issue by t-g-kim** [RocketChat/Rocket.Chat#15758]
Hi, I use Rockect-chat

failed : Error during Websocket handshake : Unexpected response code :400

My setting.
I installed Rocketchat as a sanp on Ubuntu on an AWS EC2 server.
Loadbalancer <-https ------- nginx ----- rocketchat configuration.

Nginx setting

```
# Upstreams

upstream backend {

    server 127.0.0.1:3000;

}



server {

    listen 80;

    server_name allthatsneakers.com;



    # You can increase the limit if your need to.

    client_max_body_size 200M;



    error_log /var/log/nginx/rocketchat.access.log;



    location / {

        proxy_pass http://backend/;



    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection "upgrade";

    proxy_set_header Host $http_host;



    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Forward-Proto http;

    proxy_set_header X-Nginx-Proxy true;



proxy_redirect off;

    }

}
```

Thank you.

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

This seems to be a setup/support issue.
This repo is for bugs, not help requests.

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

Please ask for help in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/


>  listen 80;

Suggest you also sort out your SSL and follow this:

https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/
