### ISSUE TITLE
Rocket Chat forgets login data

### ISSUE THREAD

**Issue by Dirk23** [RocketChat/Rocket.Chat#15761]
Hello,
since short the Rocket Chat Desktop App always starts with the request to enter the login data. Before that the software started and still had the login data, so you didn't have to log in manually. This behavior can be seen with all users and is therefore in my opinion on the server and not on the client software.

Rocket chat server (via snaps): 2.1.1
Rocket Chat Server OS: Ubuntu 16.04.6

Rocket Chat Desktop Client: 2.16.2
Rocket Chat Desktop Client OS: Windows 10

**Comment by reetp** [comment]
Please close this and re-open in correct repo

https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by Dirk23** [comment]
> Please close this and re-open in correct repo
> 
> https://github.com/RocketChat/Rocket.Chat.Electron

As i mentioned, it is no matter wich client or if i use the Website. The Login will not be safed on any Computer. I dont think that the client is the problem.

**Comment by reetp** [comment]
> As i mentioned, it is no matter wich client or if i use the Website. The Login will not be safed on any Computer. I dont think that the client is the problem.

No, you didn't mention this. You just mentioned the Desktop app. You said this:

>  the Rocket Chat Desktop App always starts with the request to enter the login data
> Rocket Chat Desktop Client: 2.16.2

Saving passwords is usually a local function, not that of the server.

So, does this occur with a completely clean browser? (Not the Electron client)

Test with Firefox and a new clean profile and no plugins to make sure nothing affects it.

**Comment by Dirk23** [comment]
Hi,

sorry. I wrote the text in an texteditor and copied it here. Maybe i missed that part. I just went to a brand new machine and logged into the Rocketchat via Google Chrome Browser ( i had no FF on this machine), i saved the Login in the Browser. Closed the browser, reopend the Browser an i was ask for my login data by the Rocketchat Server

**Comment by reetp** [comment]
Yes, you completely missed it and talked about the Electron client with no mention of Chromium.

I don't think the rocket.chat has any control over your browser saving your passwords.

That is a function of your browser, and possibly your server administrator via say GPO policies.

I guess there is a remote possibility that your server admin could have hacked some code in that might prevent this occurring but I can't see it eg

https://stackoverflow.com/questions/41217019/how-to-prevent-a-browser-from-storing-password

So I can't see any bug on rocket.chat itself.

**Comment by ggazzo** [comment]
@Dirk23 you now if this setting is enabled?
![image](https://user-images.githubusercontent.com/5263975/68639071-2cdca880-04e2-11ea-8de0-226a7602f266.png)
Admin > accounts

**Comment by Dirk23** [comment]
> @Dirk23 do you now if this setting is enabled?
> ![image](https://user-images.githubusercontent.com/5263975/68639071-2cdca880-04e2-11ea-8de0-226a7602f266.png)
> Admin > accounts

That was the Problem. I dont know how and why this setting was set, but disabling solved the Problem. Thank you very much!
