### ISSUE TITLE
Cannot find modules when scaffolding a new rocket.chat app

### ISSUE THREAD

**Issue by frozeneffigy** [RocketChat/Rocket.Chat#15760]
### Description:

I've followed the steps to install the rocket.chat apps CLI, but I'm getting the following error when trying to scaffold a new app using the given rc-apps create command

### Steps to reproduce:
1. install node
2. install npm
3. sudo npm install -g @rocket.chat/apps-cli
4. rc-apps create

### Expected behavior:

A new (contentless) app

### Actual behavior:

```
 ›   Error: /home/ubuntuuser/addchannels/AddChannelsApp.ts (4,8): 
 ›     Cannot find module '@rocket.chat/apps-engine/definition/accessors'.
 ›   Error: /home/ubuntuuser/addchannels/AddChannelsApp.ts (5,21): 
 ›     Cannot find module '@rocket.chat/apps-engine/definition/App'.
 ›   Error: /home/ubuntuuser/addchannels/AddChannelsApp.ts (6,26): 
 ›     Cannot find module '@rocket.chat/apps-engine/definition/metadata'.
Creating a Rocket.Chat App in /home/ubuntuuser/addchannels... !
Error: invalid.
```

### Server Setup Information:

- Version of Rocket.Chat Server: na
- Operating System: na
- Deployment Method:  na
- Number of Running Instances: na
- DB Replicaset Oplog: na
- NodeJS Version: na
- MongoDB Version: na

### Client Setup Information

- Desktop App or Browser Version: na
- Operating System: na

### Additional context

Running Ubuntu 18.04 on Virtualbox 6.
Using App CLI version 1.5.2 linux-x64
Using Node version node-v8.10.0

**Comment by reetp** [comment]
I would say the first thing is to make sure your node version matches the current release version
https://github.com/RocketChat/Rocket.Chat/releases

> Engine versions
> Node: 8.15.1
> NPM: 6.9.0
> MongoDB: 3.4, 3.6, 4.0

Note in the docs it demonstrates with an even newer version v10.15.3

https://rocket.chat/docs/developer-guides/developing-apps/getting-started/

I'd start there and see what happens.

**Comment by Numblesix** [comment]
Im having the same issue i did the exact same thing 

### Server Setup Information:

- Version of Rocket.Chat Server:  3.0.3
- Operating System: Rhel 7.7
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.16
