### ISSUE TITLE
Cannot unfollow message from thread's panel

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#15765]
If you open the thread panel and click on actions buttons of the first message (the one that started the thread) there is no unfollow option.

but if you click on the same message at message's list, the unfollow option is there.

**Comment by ashwaniYDV** [comment]
I would like to work upon it

**Comment by subham103** [comment]
The issue is actually with the toggle option for {unfollow, follow} which is present for all the massages except the one on which the thread started. I would like to work on this issue:)

**Comment by sampaiodiego** [comment]
please do =)
