### ISSUE TITLE
Manage users in group ; group !=roles

### ISSUE THREAD

**Issue by Sicoval31** [RocketChat/Rocket.Chat#15778]
not a bug, but a feature for the future ;)
it's seems that no chat software have this option. I don't understand why .. so many chat-users want to manage users in groups to separate some of them and manage them easyly. Nor a AD's group ;)

For example, i want to have :
- VIP group with president, director, etc
- user group with all the other user
- admin_software group for administrator of many software we use
- etc ...

I don't want that lambda user can contact president and other VIP user in the chat. So permissions will be manage groups by groups by the RC administrator (Me :) ) and other options.

It'll be a great feature that only RC have ;)

**Comment by reetp** [comment]
@rocket-cat close

There are various issues already open on this sort of thing. Please search before opening Issues.

eg
https://github.com/RocketChat/feature-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+group

At best this is a feature request and should be opened here https://github.com/RocketChat/feature-requests
