### ISSUE TITLE
Data still retained in rocketchat__trash

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#15779]
Rocket.Chat v2.2.0
Docker

Following a conversation on #support a user mentioned that data could still be found in rocketchat__trash following pruning and wanted to know if it could be recovered.

I took a look and could see manually deleted data was in there as well. Why?

Is there a 'Restore messages' method, and if so, where is the 'Empty Trash' method' ?

There should be some way to purge this data.

https://github.com/RocketChat/feature-requests/issues/135

**Comment by Gummikavalier** [comment]
As a workaround for the lack of option for cleaning up messages in the trash automatically we run this command daily on our server:

> mongo rocketchat --eval 'db.rocketchat__trash.deleteMany({})' --quiet | grep -v '^WriteResult' || true

Thank you for martinvonwittich for the original command in his/her issue discussing the size of rocketchat_integration_history.
