### ISSUE TITLE
Avoid using font icons that have a mirror property

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1577]
Some Unicode characters like "Greater than" `>` has a [mirror property](http://www.fileformat.info/info/unicode/char/003E/index.htm) which means if the display direction is changed from RTL to LTR or visa verse that character will be replaced by its mirror.
E.g.
lets say we have this written in LTR language like English
`3 > 1`
when changing that to RTL it becomes:
`1 < 3`
since the browser will replace that character from `&gt;` to `&lt;`

So how is this related to Rocket Chat, well, most if not all of the used icons here come from a special font characters called `fontello` and when the font was created the settings icon got the same Unicode as the greater than character, so the browser is treating it as it treats that sign, so when switching the interface to RTL, it replaces that sign with whatever sign that is placed in the Less than character location (see the picture)

![acc-bug2](https://cloud.githubusercontent.com/assets/432460/11604826/ab70645c-9abf-11e5-9076-260be6a12485.png)

The exact opposite happens in the search box under "Administration > Rooms" where the rotating circular symbols turns into a rotating settings symbol!

These two symbols need to be moved to other locations that does not have the mirror feature, and also avoid using such mirror locations for other symbols unless it is intended.

**Comment by geekgonecrazy** [comment]
This is interesting... So solution in this case would be what change the icon?

**Comment by fduraibi** [comment]
No, only change their location in the Unicode address space.
The settings and round icons are located at addresses `003c` and `003e` and the default symbols atat these addresses are the greater and smaller than sign which have the mirror property.
The solution is to simply update the icons font and move the affected icons into other locations that doesn't have a mirror property and update the html/css with the new address.

**Comment by geekgonecrazy** [comment]
The problem with that is if we make changes to the fontello characters we have something we then have to remember and maintain if we decide to upgrade the fontello font set in the future.

**Comment by fduraibi** [comment]
@geekgonecrazy Check my proposed solution, which simply to set those icons to always be LTR

**Comment by fduraibi** [comment]
Fixed: https://github.com/RocketChat/Rocket.Chat/pull/1594
