### ISSUE TITLE
Allow room creator to delete that room

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1578]
Currently only admins can delete rooms, but it will be nice if the person who created the room becomes like a room admin and can delete that room from the "Room Settings" tab.

In the case of the rocket chat demo server, we see many many rooms that users created mostly for testing but never used again. They cannot delete it, and it is hard for the admins to delete since they don't know if will be used in the future or not.

In production environment a group of people can start a room use it for sometime and be done with it, or they might leave it unused but they can still come back for the message history. So they are the ones who decides if the room is still needed or not. It can be added as an option in the admin settings, so the admin can allow such feature or not.

**Comment by soenkef** [comment]
Important feature! +1

**Comment by gwillen** [comment]
+1 to this. I didn't know that I couldn't delete rooms until someone on our work Rocket server complained about one of the dozen-or-so test rooms I've created. I had to tell him I couldn't do anything about it and he'd need to contact an admin, whoops! This makes playing around with the system a lot more annoying, which is an antipattern (people play around when learning software, and they should be able to undo trivial errors they make while doing that.)

**Comment by soenkef** [comment]
+1 - if possible as solution by permission settings.

**Comment by geekgonecrazy** [comment]
This should be possible with our permissions.  Does this issue still exist?

**Comment by fduraibi** [comment]
I think the permissions do solve it, however, some permission names are not clear!

what is:

- delete-p
- delete-c
- delete-d

**Comment by geekgonecrazy** [comment]
Those translate to:

* delete-p -- Delete Private Group
* delete-c -- Delete Channel
* delete-d -- Delete Direct Message Conversation

**Comment by fduraibi** [comment]
Why it doesn't show the full name over their? missing translation entry?

**Comment by geekgonecrazy** [comment]
@fduraibi this is just the variable name or the short name, we need to actually add i18n entries maybe to our permission names 😄

**Comment by mcescalante** [comment]
I've allowed `delete-p` for the role `owner` but cannot find where to actually delete the private chat group on my server. Should it be under "state" in Room Info?

**Comment by reyman** [comment]
Any news on this button ?
