### ISSUE TITLE
Custom authentication service creates accounts, although this is prohibited by the settings

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#15787]
### Description:
Custom authentication service creates accounts, although this is prohibited by the settings.
It is security issue for us, because we create users in Rocket.Chat by native LDAP with Active Directory security group filter. That creation allows you to bypass this filter.

### Steps to reproduce:

1. Setup **Custom OAuth** provider (**KeyCloak\LDAPS** in our case)
2. In Rocket.Chat **Accounts** settings **Accounts_Registration_AuthenticationServices_Enabled** set to **NO**
3. Login with user, that does not exist in Rocket.Chat
4. User successfully created in Rocket.Chat

### Expected behavior:

If user does no already created in Rocket.Chat he should not be able to enter with Custom OAuth.
Custom OAuth should not create account for that user.

### Actual behavior:
Settings:
![image](https://user-images.githubusercontent.com/4023037/68826999-821ae480-06b1-11ea-8505-84f14e09606d.png)
User created by Custom OAuth:
![image](https://user-images.githubusercontent.com/4023037/68827105-fa81a580-06b1-11ea-8ba3-79b63a9249c0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: CentOS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: On
- NodeJS Version: v8.15.1
- MongoDB Version:4.0.13

### Client Setup Information

- Desktop App 2.16.0
- Operating System: Windows 10

### Relevant logs:
`CustomOAuth ➔ debug Identity response {   "sub": "424c0e25-b3f0-4912-b1a3-01b6c4646739",   "email_verified": false,   "displayName": "Карлан Антон Андреевич (Test2)",   "roles": [     "offline_access",     "uma_authorization"   ],   "name": "Karlan Anton Карлан",   "preferred_username": "karlanaat02",   "given_name": "Karlan Anton",   "family_name": "Карлан" } 
I20191114-04:38:28.760(0) Meteor ➔ method joinDefaultChannels -> userId: Sg5oEhbeuyM9FNE26, arguments: [null] 
I20191114-04:38:28.778(0) Integrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated 
I20191114-04:38:28.778(0) Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated { event: 'userCreated',   user:     { _id: 'Sg5oEhbeuyM9FNE26',      createdAt: 2019-11-14T04:38:28.755Z,      services: { keycloak: [Object] },      type: 'user',      status: 'offline',      active: true,      name: 'Карлан Антон Андреевич (Test2)',      username: 'karlanaat02',      _updatedAt: 2019-11-14T04:38:28.756Z } } 
I20191114-04:38:28.779(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any 
I20191114-04:38:28.780(0) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. `

**Comment by kdre** [comment]
I have the same issue. I configured Google OAuth service and disabled registration for new users a few days ago. Anyway, never before seen users can still register using Google OAuth. This is a highly critical security problem and it is already 6 month open.

Expected behavior:
If registration for new users is disabled, then only existing users in the rocket.chat database should be able to log in, no matter if it is a local account or someone who registered before using Google.

**Comment by micleclickme** [comment]
Same here on v. 3.7.0
Account registration from account services is disabled. I have to set empty list for default roles via oauth.
![image](https://user-images.githubusercontent.com/7793751/99403812-ee02df00-28fb-11eb-9f92-72b4050ccb25.png)
But user still able to login.
![image](https://user-images.githubusercontent.com/7793751/99403871-02df7280-28fc-11eb-904a-1d155a69bedd.png)

**Comment by dvydruk** [comment]
This problem can be mitigated by creating a separated realm in Keycloak wich accepts only correct users.

**Comment by LouisSung** [comment]
Does anyone still tracking on or fixing this ?
This is indeed a critical security issue _(;3
I'll take a survey anyway _(:3

**Comment by LouisSung** [comment]
Hi all,

I've raised a pull request #22564 to fix this issue.
Does any can help on verifying if my change also fixes your problem? There might be something I didn't think of, but at least it fixes our case.
Feel free to leave the comments and refine the PR, thanks : )

LS

**Comment by xxxmadxxx** [comment]
Hi,

I have tested this issue and seems that has been fixed as you can see in the print bellow. I'll proceed and close this issue and if you find anything else, let me know.
<img width="1080" alt="Captura de Tela 2022-04-08 às 14 46 14" src="https://user-images.githubusercontent.com/38704234/162494612-32b0261c-cf88-4fac-bef6-4da34807c634.png">
