### ISSUE TITLE
Users have to login every time they use the iOS/android app

### ISSUE THREAD

**Issue by drflngr** [RocketChat/Rocket.Chat#15797]
Good day,

### Description:

There are some users who experience the problem that they are getting logged out from our server every time they don't use the app for a second. This happens everytime they go back to the homescreen or switch off their phone (not shutting it down, but only blacking out the screen). It is independent accross iOS and Android with the latest version of the app.
These problems only occured on one device while we were on RC version 0.74.0. Since the upgrade to 2.2.0 there are a lot of other useres with the same problem.

### Steps to reproduce:

1. Don't really know how to reproduce this. It's just happening.

### Expected behavior:

To don't log out users.

### Actual behavior:

It's logging out the users.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: some linux distribution (I didn't set up the server)
- Deployment Method: don't know that either
- Number of Running Instances: 1
- DB Replicaset Oplog: activated
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.13

### Client Setup Information

- App Version: the latest, both from the App- and Play-Store, but NO Beta-Version
- Operating System: iOS and Android

The Login Expiration is set to 90 days, the Forget User Session on Window Close is set to 'no'.

I'm not quite sure what else to add to this description, please feel free to point it out to me.

Thanks in advance,

Simon

**Comment by reetp** [comment]
First, please properly fill out an issue template. Some server history may help too.
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Second, you give no information on what versions of the apps that you are using. They are not necessarily the same software, though they may be:
https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

Next have you checked settings in your admin section that might affect this eg Login Expiration, Forget User Session on Window Close etc?

A lot more detail may help in diagnosing this.
