### ISSUE TITLE
Docker develop image is built from an old commit

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#15790]
### Description:

There seems to be another instance of the develop docker image being built from an older commit. This was reported on #13264 (for a different set of commits). I believe @sampaiodiego  found it was linked to an end-to-end tests issue. 

So just giving the heads up that the current image is based on a commit dated Oct 31, when the most current one (per my last backup) is Nov, 11. My thought is that this could cause some really nasty regressions. And again, I understand this is a develop version, but if it is being published, it would probably be something to check 😄 .

### Steps to reproduce:

1. Pull the latest rocketchat/rocket.chat:develop image
2. Check the commit hash.

### Expected behavior:

Should contain a far more recent develop commit.

### Actual behavior:

And old commit is being used.

### Rocket.Chat

|                 Version | 2.3.0-develop              |
| ----------------------: | -------------------------- |
|     Apps Engine Version | 1.7.0                      |
|      Database Migration | 166                        |
| Database Migration Date | November 13, 2019 11:45 PM |
|            Installed at | November 7, 2018 7:08 AM   |
|                  Uptime | 6 hours, 34 seconds        |
|           Deployment ID | ZMnphP2xrSgdJk4FK          |
|                     PID | 1                          |
|       Running Instances | 1                          |
|                   OpLog | Enabled                    |

### Commit

|    Hash | 7461a1fb68a2fefc9836bef0ba6bf96f25a13714                     |
| ------: | ------------------------------------------------------------ |
|    Date | Thu Oct 31 11:49:13 2019 -0300                               |
|  Branch | develop                                                      |
|     Tag | 2.1.2                                                        |
|  Author | Martin Schoeler                                              |
| Subject | Regression: Fix hide avatars in side bar preference (#15709) |

### Rocket.Chat

|                 Version | 2.3.0-develop               |
| ----------------------: | --------------------------- |
|     Apps Engine Version | 1.7.0                       |
|      Database Migration | 166                         |
| Database Migration Date | November 11, 2019 9:31 PM   |
|            Installed at | July 3, 2018 10:28 AM       |
|                  Uptime | 2 days, 9 hours, 24 seconds |
|           Deployment ID | wecGmPkstnsm2e7ge           |
|                     PID | 8                           |
|       Running Instances | 1                           |
|                   OpLog | Enabled                     |

### Commit

|    Hash | a8ad42b34fb7f8918b7b48e9eb8df4ebfa8a6bc4                     |
| ------: | ------------------------------------------------------------ |
|    Date | Mon Nov 11 18:35:35 2019 -0300                               |
|  Branch | develop                                                      |
|     Tag | 2.1.2                                                        |
|  Author | Marcos Spessatto Defendi                                     |
| Subject | [IMPROVE] Replace livechat:visitorInfo publication by REST (#15639) |

**Comment by bkraul** [comment]
Please disregard this issue. I am an idiot. Was looking at a different RC instance.

**Comment by sampaiodiego** [comment]
Don't be so hard at you :joy: thanks anyway for letting us know.. :+1:
