### ISSUE TITLE
Push notification delayed after upgrade to 2.1.1

### ISSUE THREAD

**Issue by kakcept** [RocketChat/Rocket.Chat#15791]
### Description:

We are currently running a RC server for our 400 delegates in Sharm El-Sheik on the World Radio Conference.  Rocket chat is installed with the SNAP subsystem. Until friday last week we were running version 1.3.2, friday night the SNAP updated the RC server to version 2.1.1

Unfortunately our experience is that push notifications to mobile devices now are delayed anywhere from a few seconds up to 15 minutes.

### Steps to reproduce:

Users chats, and messages are submitted to push

### Expected behavior:

Push notification to arrive within a short timing interval.

### Actual behavior:

Push messages to mobile devices arrives with considerable delays up to 15 minutes
Push messages on desktop arrives instantly

No difference whether its an Direct Message, Private group or public channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 18
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14
- Proxy: nginx
- Firewalls involved: Cisco ASA

### Client Setup Information

- Mobile devices: Apple iOS and Android
- Desktop App or Browser Version: 
- Operating System:

### Additional context

Problem was detected after upgrade from 1.3.2 to 2.1.1 on SNAP

### Relevant logs:

Logs don't show any errors, messages seems to get pushed. Due to the volume its not quite possible to count them on screen.

**Comment by sampaiodiego** [comment]
hi @kakcept .. not sure you're already aware but we changed how push notifications are sent on version `2.1.0` as you can see in this blog post https://rocket.chat/2019/09/27/push-notification/

having that said, have you tried reverting the changed introduced on `2.1.0` by changing the affected settings? (the settings can be found at Admin > Accounts > Default User Preferences.. The settings are "Desktop Notifications Default Alert" and "Mobile Notifications Default Alert")

This delay you're seeing can be caused to the new high volume of notifications.. To check if that is the case, you can query the collection that stores the notifications queue by running the following command on MongoDB Shell:
```javascript
db.getCollection('_raix_push_notifications').count()
```

Ideally that collection should have no records (the above command should return zero).. that means all notifications were sent and the server is ready to send more.

if the number returned it too high (let's say over 500) you might notice some delay indeed. Rocket.Chat take off the queue 10 notifications at a time, on intervals of 5 seconds.. so it roughly takes 4 minutes to clear a queue with 500 notifications to be sent.

you can also try clearing the queue and see if notifications are faster from that time on (keep in mind you'll permanently lose those notifications).

let me know what you think..

**Comment by reetp** [comment]
Can this be closed with the merge?

**Comment by kakcept** [comment]
Yes, thx a lot for response .....

**Comment by w4rc0n** [comment]
I would like to re-open this topic. I am having an identical issue, but our userbase is 30, and very low usage at the moment. 1 message sent on the entire server, and it takes 15-30 minutes to get the push notification. The only difference between the original posters set up and mine is that ours is a docker deployment.

**Comment by sampaiodiego** [comment]
@w4rc0n have you checked your notifications queue collection?

```
db.getCollection('_raix_push_notifications').find()

**Comment by lcharette** [comment]
Instead of querying the db manually, could the queue size be displayed somewhere? I'm seeing delays in push notifications too, an I'm pretty sure that the batch size issue, but before thinkering with the settings, I would like to see the extend of the damage.
