### ISSUE TITLE
Change in notification defaults not reflected in the UI

### ISSUE THREAD

**Issue by willstott101** [RocketChat/Rocket.Chat#15793]
### Description:

The Account setting UI still claims that `Mentions` are the default however https://rocket.chat/2019/09/27/push-notification/ and experience suggests otherwise.

### Steps to reproduce:

1. Go to account settings on a new default account.
2. See that the settings claim Mentions only.
3. Have someone send a message in a random channel without a mention.

### Expected behavior:

I expect to not receive a notification **as-per my settings page**.

### Actual behavior:

I receive a notification.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 18
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Google Chrome | 78.0.3904.97 (Official Build) (64-bit)
- Operating System: Ubuntu 18

![Screenshot from 2019-11-14 16-20-32](https://user-images.githubusercontent.com/335152/68875771-46a50800-06fb-11ea-9781-089f4d1af2e0.png)

**Comment by willstott101** [comment]
As an aside is it possible to change the default on a per-server basis? As we very much liked the old default of `Mentions` only.

**Comment by reetp** [comment]
The behaviour you noticed is most likely a bug - I think @sampaiodiego  had noticed this.

> As an aside is it possible to change the default on a per-server basis? As we very much liked the old default of `Mentions` only.

Yes you can normally set it per server via Admin->Accounts->Default User->Preferences->Mobile Notifications Default Alert (note 'Mobile Notifications' vs 'Push Mobile Notifications' in Account Settings  - should be called the same name)

But the My Account setting might not be working correctly as above.

They made the decision to convert the server default with no choice to be like other messaging apps eg Whatsapp etc. Users 'expected' notifications for every message. Apparently.

https://rocket.chat/2019/09/27/push-notification/

Not that anyone ever reads that................

Shifting an important default like this without any real advice it was happening was mad IMHO.

Perhaps enable it on a new install, but the existing should have been left as is. Never change a core setting without a really good reason.

**Comment by willstott101** [comment]
I mean the use cases for WhatsApp vs a self-hostable slack-like messaging app seem kinda monumental to me. The idea they serve the same goals is weird. Thanks for the point to the Default User account, that corresponds to what I saw i the code but I didn't quite appreciate it was an actual account.

**Comment by reetp** [comment]
> I mean the use cases for WhatsApp vs a self-hostable slack-like messaging app seem kinda monumental to me. The idea they serve the same goals is weird. 

Yup I agree. And the idiosyncrasies and flaws in the notifications system here are revealing themselves right now.... suddenly converted with no warning to send every message?? Good luck with that:

https://github.com/RocketChat/Rocket.Chat/issues/15791

> Thanks for the point to the Default User account, that corresponds to what I saw i the code but I didn't quite appreciate it was an actual account.

NP - glad it helped.

**Comment by willstott101** [comment]
![Screenshot from 2019-11-18 10-27-14](https://user-images.githubusercontent.com/335152/69045142-2ec8cf00-09ee-11ea-80b9-271c257794c7.png)

I actually can't see any push notification options. I found this slightly odd setting about Audio notifications and there is an `Audio Notifications Default Alert` which is set to `Mentions` already.

It's as though I'm only seeing a subset of the preferences?

**Comment by sampaiodiego** [comment]
@RocketChat/frontend can you please take a look on this?

**Comment by sampaiodiego** [comment]
let me ping @ggazzo

**Comment by MartinSchoeler** [comment]
@willstott101 Can you test this with the latest version (3.7.0 as it is now) Since when I tested with it the default values on the preference menus were correct and the admin default options were correct too. BTW these are the settings you are looking for in admin: 
<img width="718" alt="Screen Shot 2020-10-14 at 11 49 14 AM" src="https://user-images.githubusercontent.com/20868078/96008079-8f86a480-0e15-11eb-825b-9a8179647afa.png">
<img width="649" alt="Screen Shot 2020-10-14 at 12 03 59 PM" src="https://user-images.githubusercontent.com/20868078/96008088-92819500-0e15-11eb-9436-31552dc8c877.png">

**Comment by MartinSchoeler** [comment]
Closing this due lack of response, if you still face this issue please reopen this. Thanks!
