### ISSUE TITLE
error 404 for links and iframes, but URL works when I type it

### ISSUE THREAD

**Issue by raltmiks** [RocketChat/Rocket.Chat#15808]
Hi,
I installed Rocket Chat 2.2 on Ubuntu 14.08.
When I am trying to use an ifram or an link (new tab), I get an 404 error page.

### Steps to reproduce:

1. Click on the link https://"mydomain"/livechat
2. get 404 error page in new tab
3. click on the URL and press ENTER
4. livechat is loaded correctly

### Expected behavior:
Link should work directly, link URL https://"mydomain"/livechat seems to be correct.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Ubuntu 18:04
- Deployment Method: 
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Tested for Chrome and Firefox
- Operating System: Windows 10, Android

### Additional context

https is enabled over Apache

**Comment by raltmiks** [comment]
![404 error](https://user-images.githubusercontent.com/49163116/69047687-0ea00c80-09fc-11ea-9230-f3d26825d648.png)

**Comment by raltmiks** [comment]
Links and iframes to the main directory work, but as soon as I want to link a suddir/suburl, I get 404-error

**Comment by reetp** [comment]
@rocket-cat close

Please read this fully.

https://rocketchat.github.io/docs/contributing/reporting-issues/

> Deployment Method:

Deployed.... how?

There doesn't seem to be any error in Rocket.Chat itself - you have provided no logs.

This is most likely a web server configuration issue and looking in your webserver logs may give you some ideas where this is going wrong.

For help/support please see: https://rocket.chat/docs/getting-support

**Comment by raltmiks** [comment]
The webserver logs are normal, no errors.
