### ISSUE TITLE
RocketChat slows and high disk read usage after upgrade to 2.2.0

### ISSUE THREAD

**Issue by maciej87pl** [RocketChat/Rocket.Chat#15800]
Hello,
I migrated rocketchat to new server with rocketctl and i upgraded it to the last version, after upgrade I have problem with read data from disk. Mongodb reads from disk with all available resources. Disk is SSD. 
This causes that I cannot do anything in rocketchat for few minutes, also I cannot upload files bigger than 50 mb, before upgrade I was uploading in messages 200 mb files - there is no limit in configuration. I find that this situation is when we are trying to show image in messages. Info about rocketchat service log and log from mongo db from long queries in the attachement. 
Thank you for support
[mongodbLog.txt](https://github.com/RocketChat/Rocket.Chat/files/3851608/mongodbLog.txt)
[systemctlLogs.txt](https://github.com/RocketChat/Rocket.Chat/files/3851609/systemctlLogs.txt)
[RocketChatInfo.txt](https://github.com/RocketChat/Rocket.Chat/files/3851618/RocketChatInfo.txt)

**Comment by reetp** [comment]
What are you using for file store? GridFS? Local File Store?

**Comment by maciej87pl** [comment]
Gridfs. Temporarly I disabled auto loading images, when i use "click to load" disk is going to read by 4 mongo db processes 300-400 mb/s. In v 2.0 this work ok, in 2.2 I have problem with this. Maybe this is caused by many and big files in gridfs? or maybe this is problem with some index on table updates.chunk?

**Comment by reetp** [comment]
For reference, how did you deploy this please? Docker, manual?

I can't comment specifically on Mongo indexes etc. Needs one of the devs to look but a lot are away today I believe. I think there may be some other comments here and at open.rocket.chat on adding indexes etc.

GridFS is not really up for large amounts of storage. It makes your DB far bigger then necessary, and will everything will slow down as a consequence.

You really should look at either Local File Storage or some other method that is better equipped.
Someone has written a script to remove files from your DB and migrate them elsewhere.

This may help.
https://github.com/RocketChat/Rocket.Chat/issues/9349

**Comment by maciej87pl** [comment]
In the first option was manual instalation, in last week it was move to the new linux serwer with installed by rocketctl version 2.2. I check and rebuild indexes with google manuals etc. It is posible that I have to many files in gridfs and then everthing slows?

**Comment by himpierre** [comment]
We have a similar issue here after upgrading to 2.2.0. From time to time Rocketchat stops responding for 30s or so. Reason seems to be high i/o. We use S3 as storage backend. So i guess the problem has nothing to do with uploading stuff. On the other hand, we just switched to S3 recently so there might be a lot of stuff still in gridfs. 

@maciej87pl did disabling autoload images fix your issue?

**Comment by maciej87pl** [comment]
> We have a similar issue here after upgrading to 2.2.0. From time to time Rocketchat stops responding for 30s or so. Reason seems to be high i/o. We use S3 as storage backend. So i guess the problem has nothing to do with uploading stuff. On the other hand, we just switched to S3 recently so there might be a lot of stuff still in gridfs.
> 
> @maciej87pl did disabling autoload images fix your issue?

Autoload temporarly help me, if i click image to load the disk i/o read went to max ssd parameters. For now probably I resolve issue by adding index to collection rocketchat_uploads.chunks, after upgrade and migrating to new server index files_id_1_n_1 was missing. I will test it tomorrow when i have full load of users.

**Comment by stefanandres** [comment]
We are also experiencing this issue.
We're using s3 now, but have old data in gridfs.

**Comment by himpierre** [comment]
@maciej87pl The indexes seem to exist on my installation

```
rs0:PRIMARY> use rocketchat
switched to db rocketchat
rs0:PRIMARY> db.rocketchat_uploads.chunks.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "rocketchat.rocketchat_uploads.chunks"
        }
]
rs0:PRIMARY> 
```

do you have another index created somewhere?

**Comment by equinoxefr** [comment]
Hi,

I think you could have a look to #15005 . It works for us !

Regards
