### ISSUE TITLE
failed start SNAP rocketchat-mongo

### ISSUE THREAD

**Issue by rodrigossimoes** [RocketChat/Rocket.Chat#15805]
After update Ubuntu 18.04.3 LTS, service **snap.rocketchat-server.rocketchat-mongo** not starting.

Below is the error (sudo journalctl -f -u snap.rocketchat-server.rocketchat-mongo):

-- Logs begin at Tue 2018-08-21 13:44:14 UTC. --
Nov 17 14:36:23 nectunt-rocket-01 rocketchat-server.rocketchat-mongo[3256]: 2019-11-17T14:36:23.090+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 -31802: WT_ERROR: non-specific WiredTiger error, terminating
Nov 17 14:36:23 nectunt-rocket-01 rocketchat-server.rocketchat-mongo[3256]: 2019-11-17T14:36:23.090+0000 I CONTROL  [initandlisten] dbexit:  rc: 100
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=100/n/a
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 5.
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Start request repeated too quickly.
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
Nov 17 14:36:23 nectunt-rocket-01 systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-mongo.

What may be the procedures to adjust this problem?

**Comment by geekgonecrazy** [comment]
Please see: https://rocket.chat/docs/getting-support the #ubuntu-snap channel on community server is probably best bet.
