### ISSUE TITLE
Unable to use Amazon S3 in 1.2.4 and 1.3.2

### ISSUE THREAD

**Issue by stardude900** [RocketChat/Rocket.Chat#15810]
### Description:

We currently use Rocketchat and want to start using the S3 functionality of Rocketchat for uploads.  We've enabled it according to the instructions at https://rocket.chat/docs/administrator-guides/file-upload/amazon-s3/ and have filled in the requisite fields but it always generates this error:
https://rocket.chat/docs/administrator-guides/file-upload/amazon-s3/

### Steps to reproduce:

1. Go to Administration
2. Go to File Upload
3. Set the Storage Type drop down to Amazon S3
4. Fill out the relevant fields in the Amazon S3 section.
5. Upload an image
6. Error: Non-file stream objects are not supported with SigV4

### Expected behavior:

Image to finish uploading, display in the GUI and show up in the bucket

### Actual behavior:

Upload bar stays green and at 100% but never finishes and the above error appears in the log.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.4 (also tried 1.3.2)
- Operating System:  CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: Repliacaset with oplog
- NodeJS Version: 8.4.11
- MongoDB Version: 3.2

### Client Setup Information

- Desktop App or Browser Version: Chrome 78 and Firefox 70
- Operating System: Fedora 30

### Relevant logs:
Relevant server log below.  No errors generated from the browser.
Nov 18 09:57:12 rc1-tst rocketchat: { Error: Non-file stream objects are not supported with SigV4
Nov 18 09:57:12 rc1-tst rocketchat: at Object.computeSha256 (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/util.js:716:23)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.COMPUTE_SHA256 (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:143:18)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.callListeners (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.emit (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.emit (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.transition (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Nov 18 09:57:12 rc1-tst rocketchat: at AcceptorStateMachine.runTo (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Nov 18 09:57:12 rc1-tst rocketchat: at /opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Nov 18 09:57:12 rc1-tst rocketchat: at Request.<anonymous> (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.<anonymous> (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.callListeners (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.emit (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.emit (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.transition (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Nov 18 09:57:12 rc1-tst rocketchat: at AcceptorStateMachine.runTo (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Nov 18 09:57:12 rc1-tst rocketchat: at /opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
Nov 18 09:57:12 rc1-tst rocketchat: at Request.<anonymous> (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:38:9)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.<anonymous> (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:685:12)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.callListeners (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
Nov 18 09:57:12 rc1-tst rocketchat: at callNextListener (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
Nov 18 09:57:12 rc1-tst rocketchat: at /opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:86:9
Nov 18 09:57:12 rc1-tst rocketchat: at finish (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/config.js:348:7)
Nov 18 09:57:12 rc1-tst rocketchat: at /opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/config.js:366:9
Nov 18 09:57:12 rc1-tst rocketchat: at Credentials.get (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/credentials.js:126:7)
Nov 18 09:57:12 rc1-tst rocketchat: at getAsyncCredentials (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/config.js:360:24)
Nov 18 09:57:12 rc1-tst rocketchat: at Config.getCredentials (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/config.js:380:9)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.VALIDATE_CREDENTIALS (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/event_listeners.js:81:26)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.callListeners (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.emit (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.emit (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:683:14)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.transition (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:22:10)
Nov 18 09:57:12 rc1-tst rocketchat: at AcceptorStateMachine.runTo (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.runTo (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:403:15)
Nov 18 09:57:12 rc1-tst rocketchat: at Request.send (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/request.js:367:10)
Nov 18 09:57:12 rc1-tst rocketchat: at features.constructor.makeRequest (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/service.js:205:27)
Nov 18 09:57:12 rc1-tst rocketchat: at features.constructor.svc.(anonymous function) [as putObject] (/opt/rocketchat/rocketchat-1.3.2/programs/server/npm/node_modules/aws-sdk/lib/service.js:653:23)
Nov 18 09:57:12 rc1-tst rocketchat: at AmazonS3Store.getWriteStream (app/file-upload/ufs/AmazonS3/server.js:140:7)
Nov 18 09:57:12 rc1-tst rocketchat: at AmazonS3Store.Store.self.write (packages/jalik:ufs/ufs-store.js:241:31)
Nov 18 09:57:12 rc1-tst rocketchat: at MethodInvocation.ufsComplete (packages/jalik:ufs/ufs-methods.js:96:23)
Nov 18 09:57:12 rc1-tst rocketchat: at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
Nov 18 09:57:12 rc1-tst rocketchat: at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
Nov 18 09:57:12 rc1-tst rocketchat: at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
Nov 18 09:57:12 rc1-tst rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Nov 18 09:57:12 rc1-tst rocketchat: at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
Nov 18 09:57:12 rc1-tst rocketchat: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
Nov 18 09:57:12 rc1-tst rocketchat: at Promise (packages/ddp-server/livedata_server.js:715:46)
Nov 18 09:57:12 rc1-tst rocketchat: at new Promise (<anonymous>)
Nov 18 09:57:12 rc1-tst rocketchat: at Session.method (packages/ddp-server/livedata_server.js:689:23)
Nov 18 09:57:12 rc1-tst rocketchat: at packages/ddp-server/livedata_server.js:559:43
Nov 18 09:57:12 rc1-tst rocketchat: message: 'Non-file stream objects are not supported with SigV4',
Nov 18 09:57:12 rc1-tst rocketchat: code: 'Error',
Nov 18 09:57:12 rc1-tst rocketchat: time: 2019-11-18T15:57:12.046Z }

**Comment by reetp** [comment]
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue.

Search the interwebs for your error.

> Error: Non-file stream objects are not supported with SigV4
 
I think you should first test with current 2.2.x

**Comment by geekgonecrazy** [comment]
Is it actual s3 or s3 compatible.  Try adjusting the signature version to 2 or 3

**Comment by stardude900** [comment]
@reetp - I'll report back.  

@geekgonecrazy - good idea, but instead of the non-file stream error we get access denied, but we've validated that the settings are correct with another application.

To be clear it's s3 compatible as we are using rados gateway

**Comment by stardude900** [comment]
Same error using 2.2.1 and mongo 3.6
Non-file stream objects are not supported with SigV4

I should note that using s3cmd i do not get the error message and it uploads the same test file as expected.

**Comment by geekgonecrazy** [comment]
if it was me I would try signature version 2 and 3.  I would also check the region.  I think its picky.. it may require an s3 compatible region name (a quirk of the package we use).

**Comment by stardude900** [comment]
Sorry for the delay, i tried that, but it didn't help.  Is there anything i can provide to help this or is the version so old i just need to upgrade and if so, what is the recommended upgrade path?
