### ISSUE TITLE
Custom fields are not displayed in user profiles

### ISSUE THREAD

**Issue by Aldekein** [RocketChat/Rocket.Chat#15817]
### Description:

After setting up custom fields in admin panel they appear while editing own profile but not visible to anyone in the team, including administrators.

### Steps to reproduce:

1. Open chat admin -> Accounts -> scroll to Custom Fields to Show in User Info input
2. Enter Role,Telegram,Phone in input
3. Scroll down to Registration -> Custom Fields
4. Enter following JSON in textarea:

```
{
	"Role": {
		"type": "text",
		"required": true,
		"public": true,
		"defaultValue": "Chief Procrastination Officer",
		"minLength": 3,
		"maxLength": 30
	},
	"Telegram": {
		"type": "text",
		"required": true,
		"public": true,
		"minLength": 3,
		"maxLength": 30
	},
	"Phone": {
		"type": "text",
		"required": true,
		"public": true,
		"minLength": 8,
		"maxLength": 30
	}	
}
```
5. Press Save changes button

### Expected behavior:

User can edit their profile to fill in the custom fields. Anyone on the team can view values of custom fields for user by opening User Info.

### Actual behavior:

User can edit their profile to fill in the custom fields. Only Email, Created at, Last login, Timezone are visible in user profiles. No custom fields are visible, though they are saved and can be seen while editing the profile again.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.1
- Operating System: Linux x64 4.9.0-7-amd64
- Deployment Method: K8s
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.12

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- Operating System: macOS 10.15

### Additional context

Reproducable both in Desktop App and Browser. 

### Relevant logs:

Nothing relevant could be found in logs. No errors happen, just the fields are not displayed.

**Comment by reetp** [comment]
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> Make sure you are running the latest version of Rocket.Chat. It’s very likely simply updating will resolve your issue. 

Can you please test this on the current latest 2.2.x

**Comment by Aldekein** [comment]
We plan to upgrade. But the repository for K8s deployment using helm charts offers 2.1.1 as the latest version https://github.com/helm/charts/commit/025d607308daf4ac722f9b9209ff6bc9f10b9cf6

**Comment by reetp** [comment]
There's little point in reporting a bug on an old version as per reporting Issues.
Just spin up a test VM somewhere - it isn't that hard?
A lot of stuff changed between 1.3.x and 2.2.x

**Comment by frostbtn** [comment]
@Aldekein 
Your **step 2** might be "too simple". See [this comment](https://github.com/RocketChat/Rocket.Chat/issues/7610#issuecomment-392265799) for a working example. There's also a [PR to the docs](https://github.com/RocketChat/docs/pull/1174/files), not yet accepted though.

**Comment by Aldekein** [comment]
@reetp I'm sorry, I didn't realise our version was so old. We did an upgrade overnight and now are using RocketChat/release-2.2.0. The bug is still there, custom fields are not visible in profile. Though @frostbtn offered a solution that worked. I would like to express my gratitude, it fixed the problem. I searched for open issues before creating this one and didn't find #7610 because it's closed.

The correct value for _Custom Fields to Show in User Info_ in our case is:

`[{"Role":"Role"}, {"Telegram":"Telegram"}, {"Phone":"Phone"}]`

**Comment by Aldekein** [comment]
Can I help to merge the PR https://github.com/RocketChat/docs/pull/1174 into main codebase? It says "This branch has conflicts that must be resolved".

**Comment by coyotespike** [comment]
Turns out, almost 8 years later this bug has not been fixed.

The culprit is `app/lib/server/functions/validateCustomFields`.

```
		if (field.required && fieldValue === '') {
			throw new Meteor.Error('error-user-registration-custom-field', `Field ${ fieldName } is required`, { method: 'registerUser' });
		}

		if (field.type === 'select' && field.options.indexOf(fields[fieldName]) === -1) {
			throw new Meteor.Error('error-user-registration-custom-field', `Value for field ${ fieldName } is invalid`, { method: 'registerUser' });
		}

		if (field.maxLength && fieldValue.length > field.maxLength) {
			throw new Meteor.Error('error-user-registration-custom-field', `Max length of field ${ fieldName } ${ field.maxLength }`, { method: 'registerUser' });
		}

		if (field.minLength && fieldValue.length > 0 && fieldValue.length < field.minLength) {
			throw new Meteor.Error('error-user-registration-custom-field', `Min length of field ${ fieldName } ${ field.minLength }`, { method: 'registerUser' });

```

If you haven't set the field, then `fields[fieldName]` is `undefined`, and naturally is not present in `field.options`, and its index is `-1`, returning an error.

You may patch it with:
```
		if (fieldValue === '') {
			return;
		}

```

This is also weird but works because `const fieldValue = s.trim(fields[fieldName]);` turns `undefined` into an empty string. Or you could be more explicit which is not a bad idea.

Anyway there you go.
