### ISSUE TITLE
SetupWizard checkbox layout bug

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#15812]
### Description:

Checkbox layout text bug

### Steps to reproduce:

1. Run and open Rocket.Chat
2. Go to 4 step in Setup-Wizard

### Expected behavior:

The text is moved to a new line

### Actual behavior:

![image](https://user-images.githubusercontent.com/19654261/69078452-c57ea580-0a59-11ea-9fa8-5bce227fb7cd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 78.0.3904.97
- Operating System: MacOS 10.14.6

**Comment by ritwizsinha** [comment]
@tassoevan  I would like to work on it but I don't know how to open setup wizard if I have already done that process

**Comment by tassoevan** [comment]
@ritwizsinha You should reset the `Show_Setup_Wizard` setting to `pending`. It might be done when booting up the process: `OVERWRITE_SETTING_Show_Setup_Wizard=pending meteor`.

**Comment by ritwizsinha** [comment]
I am not able to reproduce this error in English, @antkaz which language is this ?

**Comment by antkaz** [comment]
@ritwizsinha Russian language

**Comment by antkaz** [comment]
I check this bug in 2.3.0. Bug fixed. I close this issue
![image](https://user-images.githubusercontent.com/19654261/70407207-43d0d500-1a65-11ea-9d91-d732ce3ca016.png)
