### ISSUE TITLE
LDAP sync is  slower on ubuntu 18.04 than 16.04

### ISSUE THREAD

**Issue by saszhuqing** [RocketChat/Rocket.Chat#15821]
### Description:

I install ubuntu 18.04 use ubuntu-18.04.3-live-server-amd64.iso,then run "snap install rocketchat-server" and " snap start rocketchat-server".
After set up LDAP setting,I click on 'Execute Synchronization Now',and I click on 'Users',the speed of add users is about **2 person per minute**,but in ubuntu 16.04,the speed is about **10 person per second.**
I am sure that the application setting is same in both 18.04 and 16.04, also the OS.
version:2.1.1

**Comment by reetp** [comment]
This is not a supported installation method.

The only way to really test this is with a proper installation - there are too many unknowns running a live ISO.

**Comment by saszhuqing** [comment]
> This is not a supported installation method.
> 
> The only way to really test this is with a proper installation - there are too many unknowns running a live ISO.

Thanks for your relay. I download a new ISO from http://cdimage.ubuntu.com/ubuntu/releases/18.04/release/ubuntu-18.04.3-server-amd64.iso,and install the OS.
After set up LDAP,the speed of add users is OK,but there are some person has no Role.I click "Edit" and then"Select a Role",but is empty. I try to delete these users,but the server give me a error "Internal Server Error" at the right top.

**Comment by reetp** [comment]
@rocket-cat close

There is no evidence of a bug here. It looks like a configuration/support issue.

Please follow links for support below.

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support:
> If you are experiencing a bug please search our issues to be sure it is not already present: https://github.com/RocketChat/Rocket.Chat/issues
