### ISSUE TITLE
White Labeling (admin pages)

### ISSUE THREAD

**Issue by shreekarade** [RocketChat/Rocket.Chat#15839]
![screenshot-ctsichat mvoipctsi com-2019 11 21-14_54_04](https://user-images.githubusercontent.com/36290412/69324649-dc4a1580-0c6e-11ea-9cd8-5c23ebcb4026.png)
I have installed rocket. chat (Version 0.65.2) and want to change rocket.chat word with my brand name from administration pages. Please help.

**Comment by reetp** [comment]
@rocket-cat close

This is a support question, not a bug.

Your version is also way out of date and you are not going to get any help with it.

See https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

**Comment by shreekarade** [comment]
Thanks
