### ISSUE TITLE
Can't start RocketChat service after reboot

### ISSUE THREAD

**Issue by annvt-dl** [RocketChat/Rocket.Chat#15838]
### Description:
I installed RocketChat recently in Ubuntu 18LTS and it worked until I restarted server.

### Server Setup Information:
- Version of Rocket.Chat Server: 2.2.1
- Operating System: Ubuntu 18.04 64 bits
- Deployment Method: tar (manual install follow https://rocket.chat/docs/installation/manual-installation/ubuntu/)
- Number of Running Instances: 01
- DB Replicaset Oplog: 
- NodeJS Version: v8.16.2
- MongoDB Version: db version v4.0.13

### Additional context

`sudo systemctl status rocketchat`

Result:
```
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-11-21 04:42:11 UTC; 3s ago
  Process: 10447 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=203/EXEC)
 Main PID: 10447 (code=exited, status=203/EXEC)

Nov 21 04:42:11 rocket.chat systemd[1]: Started The Rocket.Chat server.
Nov 21 04:42:11 rocket.chat systemd[10447]: rocketchat.service: Failed to execute command: Permission denied
Nov 21 04:42:11 rocket.chat systemd[10447]: rocketchat.service: Failed at step EXEC spawning /usr/local/bin/node: Permission denied
Nov 21 04:42:11 rocket.chat systemd[1]: rocketchat.service: Main process exited, code=exited, status=203/EXEC
Nov 21 04:42:11 rocket.chat systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

I checked the /usr/local/bin/node folder but it didn't exist so I tried to make the folder and give permission:
`sudo mkdir /usr/local/bin/node`

`sudo chown -R rocketchat:rocketchat /usr/local/bin/node`

Only for testing:
`sudo chmod 777 -R /usr/local/bin/node`

`sudo chmod +x /opt/Rocket.Chat/main.js`

After try to start RocketChat service again, I still have almost same issue:
```
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-11-21 04:50:06 UTC; 7s ago
  Process: 11535 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=203/EXEC)
 Main PID: 11535 (code=exited, status=203/EXEC)

Nov 21 04:50:06 rocket.chat systemd[1]: Started The Rocket.Chat server.
Nov 21 04:50:06 rocket.chat systemd[1]: rocketchat.service: Main process exited, code=exited, status=203/EXEC
Nov 21 04:50:06 rocket.chat systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```

This is my RocketChat.service's contents:
```
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://chat.unit.vn:3000/ PORT=3000
[Install]
WantedBy=multi-user.target
```

**Comment by reetp** [comment]
@rocket-cat close

There is no evidence of a bug here. It looks like a support/configuration issue. Please follow the support options below.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> 
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support
>

**Comment by TranKhanhToan** [comment]
hello @annvt-dl . Did you resolve this issue ? i had same issue and i can't resolve this.

**Comment by ibshafique** [comment]
@annvt-dl and @TranKhanhToan 
were you able to solve the problem?
I am also stuck at the same stage.

![image](https://user-images.githubusercontent.com/48373106/92207651-633d4700-eeab-11ea-911a-663f17e461a5.png)

**Comment by bradhutson** [comment]
The problem is that your exec script is pointing to the wrong place , you can fix by providing a symlink to the actual location like this 
ln -s /usr/bin/node /usr/local/bin/node or simple change it in the exec script

**Comment by j-menter** [comment]
I also got this problem, but am using ubuntu 20.04 Latest version
Could anyone already solve the problem? 

![image](https://user-images.githubusercontent.com/74477633/161969937-d7ef4a50-bd2b-47f7-b37e-b2050bf85cd7.png)

**Comment by C0uchP0tat0** [comment]
> I also got this problem, but am using ubuntu 20.04 Latest version Could anyone already solve the problem?
> 
> ![image](https://user-images.githubusercontent.com/74477633/161969937-d7ef4a50-bd2b-47f7-b37e-b2050bf85cd7.png)

Try installing node version 14.18.3.
Rocket.Chat 4.6.0
OS: Ubuntu 18.04 LTS, Ubuntu 19.04 and Ubuntu 20.04(Latest)
Mongodb 5.0
NodeJS 14.18.3

**Comment by C0uchP0tat0** [comment]
I have another problem. The chat server starts, runs for 30 seconds, and gives the same error.

**Comment by ahmedhosnypro** [comment]
this solves it

run
```sudo apt update
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt -y install nodejs


"/usr/bin/node"
and in /lib/systemd/system/rocketchat.service
ExecStart=/usr/bin/node /opt/Rocket.Chat/main.js

reload demon
sudo systemctl daemon-reload```
