### ISSUE TITLE
LiveChat not working on WordPress  ("Cross-Origin Read Blocking")

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#15834]
### Description:

LiveChat doesn't show up on my website, instead I  am getting this message in my browser console:

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://pun-chat.peerunschooling.net/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

LiveChat WordPress plugin is installed on this domain:  jfwebdev.com

RocketChat is installed at pun-chat.peerunschooling.net

### Steps to reproduce:

Go to jfwebdev.com.

### Expected behavior:

I expect to see the Rocket.Chat livechat widget in the lower right-hand corner.

### Actual behavior:

It doesn't show up.  Instead there is an error in the Console.

### Server Setup Information:

- Version of Rocket.Chat Server:  2.2
- Operating System:  Linux
- Deployment Method: Heroku
- Number of Running Instances: 1 
- DB Replicaset Oplog:  Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.8

### Client Setup Information

- Desktop App or Browser Version:  Chrome
- Operating System:  Windows

### Additional context

Just recently updated from v1.1.1 to v2.20

### Relevant logs:

Browser Console:
b5cc3d8f202c27740a02d0167e663de4.js:8 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://pun-chat.peerunschooling.net/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ b5cc3d8f202c27740a02d0167e663de4.js:8
(anonymous) @ b5cc3d8f202c27740a02d0167e663de4.js:8
tag_assistant_compiled.js:117 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://pun-chat.peerunschooling.net/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by reetp** [comment]
I think you will find you should have kept up with breaking changes

Your URL needs fixing. See Livechat/Installation

**Comment by flantascience** [comment]
Thank you for the reply!   Got it working

Is the chat bubble the only front-end layout option available?    I preferred how it was before where it was more visible and clearly a chat window.

![image](https://user-images.githubusercontent.com/12577122/69263398-3a092f80-0b93-11ea-93db-66d23969feaa.png)

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

Probably not unless you want to hack the livechat code. 

Ask in the forums or open.rocket.chat #support or #livechat
