### ISSUE TITLE
Missing message content for thread reply search results 

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#15833]
### Description:

When search for messages and the results contain thread replies, said replies are empty and their message content is missing.

### Expected behavior:

Thread results should be populated.

### Actual behavior:

![Annotation 2019-11-20 134800](https://user-images.githubusercontent.com/6803105/69240365-9886db80-0b9c-11ea-8cda-a98bd97dcc3f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 71
- DB Replicaset Oplog: yes
- NodeJS Version: 8.12.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 78.0.3 & Firefox 60, 68
- Operating System: Linux & Windows

### Additional context

Seems to be closed by #15094 but the problem still present.

**Comment by reetp** [comment]
On open.rocket.chat 2.3.x develop as well.

You can click a result and it will take you to the relevant message.

![Screenshot_2019-11-20_14-31-44](https://user-images.githubusercontent.com/3800384/69243165-c53df180-0ba2-11ea-9059-8ce16514bb84.png)
