### ISSUE TITLE
package JSON contains deprecated modules

### ISSUE THREAD

**Issue by prasadareddy21** [RocketChat/Rocket.Chat#15845]
![image](https://user-images.githubusercontent.com/39421816/69403695-38da1e80-0cc9-11ea-908b-af7b495b31c5.png)

What do I do to set up the project? Please suggest.

**Comment by reetp** [comment]
@rocket-cat close

This is a support question, not a bug.

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

Try https://open.rocket.chat #dev
