### ISSUE TITLE
Sidebar Header size

### ISSUE THREAD

**Issue by larsziegelmann** [RocketChat/Rocket.Chat#15848]
Me and my team are working on customizing Rocket.Chat via the custom CSS option.
Our goal is to recolor the ".sidebar__header" class and we noticed a small block sticking out of the header. You can reproduce this "issue" by recoloring the "sidebar__header".
What purpose does this "block" have and is there a way to remove it?

![image](https://user-images.githubusercontent.com/54264704/69430361-ba679600-0d35-11ea-89d2-0a9a31aaf40f.png)

Sorry if this is a dumb question, none of us is really good at CSS.

Rocket.Chat Version: 2.1.1
Apps Engine Version: 1.6.0
Browser: Google Chrome

**Comment by reetp** [comment]
@rocket-cat close

I can't see any actual bug here.

If you want support please follow these links from the bug report template - always make sure you test on the latest current version as well:

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support
