### ISSUE TITLE
When choosing S3 or WebDAV , how the uploads are routed ?

### ISSUE THREAD

**Issue by TechRova** [RocketChat/Rocket.Chat#15847]
I selected S3 and WebDAV in file uploads and it's successful

Now my confusion is , when I go through the react native code , the `sendFileMessage` seems to be uploading to the RocketChat server 

Is it uploading to the Rocket Chat server first and then the RC server reupload the file to S3 / Webdav ? 

Please explain

**Comment by reetp** [comment]
@rocket-cat close

This is a support question, not a bug.

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

Try https://open.rocket.chat #react-native
