### ISSUE TITLE
Wrong link preview image src url

### ISSUE THREAD

**Issue by nebulade** [RocketChat/Rocket.Chat#15843]
### Description:

The images in the link previews are broken due to the `src` attribute of those `img` tags missing the original origin. To give an example like jitsi, posting a jitsi channel url like `https://meet.jit.si/foobar` should result in src url within the preview of `https://meet.jit.si/images/jitsilogo.png?v=1` however it only has `/images/jitsilogo.png?v=1` set. Which leads to broken preview links. The android app works fine, the web version has the issue.

### Server Setup Information:

- Version of Rocket.Chat Server:  2.2.1
- Operating System: Linux
- Deployment Method: Cloudron
- Number of Running Instances: 1
- Oplog: Enabled
- NodeJS Version:  v8.12.0
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: Firefox 70/71
- Operating System: Linux

**Comment by machester4** [comment]
It's also happening in the latest version, I'm going to take this.
