### ISSUE TITLE
Video chat sends users into separate video calls

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#15844]
### Description:

I'm testing the video chat after updating from v1.1.1 to v2.2.0.   I setup a conversation between two users, on on desktop and one on mobile.  When the two users go into the video chat, they are actually in separate chat sessions.  Not able to see one another, though on each persons screen, everything looks fine.

### Steps to reproduce:

1. Start a conversation between two users
2. Click on Start video call on desktop
3. Click on join video call on mobile  (iOS)

### Expected behavior:

I expect them to be joined together in one video call

### Actual behavior:

The two users are in video calls but in separate video conference rooms.  They can't see eachother at all.

### Server Setup Information:

- Version of Rocket.Chat Server:  2.2.0
- Operating System: Linus
- Deployment Method:  Heroku
- Number of Running Instances: 1 
- DB Replicaset Oplog:  Enabled
- NodeJS Version: v8.15.1
- MongoDB Version:  3.6.8

### Client Setup Information

- Desktop App or Browser Version:  Chrome
- Operating System:  Windows

Mobile App:  iOS Rocket.Chat
Says the mobile app is version 3.5.2 (262)

Including this screenshot... it appears both have the same text at the top of the chat even though we're in separate rooms:
![image](https://user-images.githubusercontent.com/12577122/69375917-541c3e00-0c77-11ea-91aa-e523379dfeda.png)

**Comment by flantascience** [comment]
NOTE: I am able to get into the video call when both users are on desktop.... but not when one user is desktop and one is mobile.

**Comment by geekgonecrazy** [comment]
Try the rocket.chat experimental app on iOS.  This version will soon be the one upgraded to stable

**Comment by flantascience** [comment]
> Try the rocket.chat experimental app on iOS. This version will soon be the one upgraded to stable

That works.... though I guess that means that app we were about to launch using the old code won't work.  That is a frustrating waste of time and money.

**Comment by geekgonecrazy** [comment]
For sure important to keep an eye on our blog / webinars etc to keep up with announcements.  Its been coming for a while now.  

Might be worth getting in contact with our team.  I know a few others with custom apps have been migrating so might have advice for you.

**Comment by gabriellsh** [comment]
As you guys mentioned this has been fixed in a later version of the app, this issue is being closed. In any case, if you experience this again, please reopen.

Thanks!
