### ISSUE TITLE
Post a chat message payload avatar don't have persistence

### ISSUE THREAD

**Issue by tribeiros** [RocketChat/Rocket.Chat#15851]
Rocket.chat have persistence for images in chat, but not for avatar ?
when i use my rocket.chat server on a public domain , my image avatar needs a public to, why ?

when i use `"avatar" : "http://10.129.179.195/avatar.png"` works on my local network, but use a public domain `https://mydomain.com.br/channel/mych` the avatar does not appear

So, i need my avatar.png outside my local-network like https://imgbb.com/

**Comment by reetp** [comment]
@rocket-cat close

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

I can't see any evidence of a bug. This is most likely a configuration issue.

You have provided no details on your server.

> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

My avatar works perfectly well:

https://open.rocket.chat/avatar/reetp

You should see yours at https://your.server.com/avatar/yourusername

You probably want to look at your file upload settings. Please follow the above link for asking for help on this.
