### ISSUE TITLE
KaTeX is prioritized over Code

### ISSUE THREAD

**Issue by Crayder** [RocketChat/Rocket.Chat#15864]
### Description:

KaTeX is drawn even when the KaTeX is in a code block.

### Steps to reproduce:

1. Make KaTeX.

>\[\boxed{\Huge t\Bigg(-.-t\Bigg)\text{  fak u}}\]

2. It works. Good.
3. Put it in a code block, so you can show others how to do KaTeX.

>'''
>\[\boxed{\Huge t\Bigg(-.-t\Bigg)\text{  fak u}}\]
>'''

4. That didn't work, instead it just puts the KaTeX inside the code box and does the light gray background.

### Expected behavior:

Show the KaTeX code including the `\[` and `\]` inside the code block instead of showing generated KaTeX.

### Actual behavior:

![image](https://user-images.githubusercontent.com/9919010/69695543-57ae2b80-10a2-11ea-8135-5a4866ba06de.png)

### Client Setup Information

- Desktop App or Browser Version: 2.15.2 (I cant upgrade to 2.16, that's a separate issue, RC just never updates or says the update is ready)
- Operating System: Win10 Pro

**Comment by mnazarov** [comment]
See also 
https://github.com/RocketChat/Rocket.Chat/issues/8640
https://github.com/RocketChat/Rocket.Chat/issues/12336
https://github.com/RocketChat/Rocket.Chat/issues/13538

**Comment by gabriellsh** [comment]
Closed by #16012
