### ISSUE TITLE
Android 8 & 10 mobile app - ldap - invalid credentials

### ISSUE THREAD

**Issue by CarlJKashnier** [RocketChat/Rocket.Chat#15868]
Server is using ldap auth. I am attempting to login via Android App 4.0.X (current version on play store). 

It returns credentials invalid.

I can log in using android app 3.5.0 - I can log in with desktop app, I can log in via web access using the same credentials.

We have the latest snap (it seems to be about a month old).

It would seem that it is likely in the login authentication on the latest version of the app maybe not using the certificates correctly.

### Steps to reproduce:

Attempt to login to a rocket chat with ldap server using current android client.

### Expected behavior:

Being able to log in

### Actual behavior:

Returning credentials invalid

### Server Setup Information:

- Version of Rocket.Chat Server: Latest
- Operating System: Linux
- Deployment Method: Snap
- Number of Running Instances: 1 
- DB Replicaset Oplog:  ?
- NodeJS Version: ?
- MongoDB Version: ?

### Client Setup Information

- Desktop App or Browser Version: Android App 4.0.X (current version on play store). Android App 4.0.X (current version on play store). 
- Operating System: Android

**Comment by reetp** [comment]
Can you please move this to the React Native repo as I think that is where it should be.

Close this, open a new one, and reference it back.

Also, please provide some logs - Rocket.Chat, LDAP, Server etc etc.

https://github.com/RocketChat/Rocket.Chat.ReactNative
