### ISSUE TITLE
Configurable behavior of threads' messages

### ISSUE THREAD

**Issue by Wirone** [RocketChat/Rocket.Chat#15867]
Threads are useful BUT right now they are making too much noise in main channel:

![image](https://user-images.githubusercontent.com/600668/69719434-c88c2c80-1110-11ea-8d58-52d90a1379aa.png)

Every message replied in thread is added as notification to main channel along with initial message's content. As you can see on screenshot above, regular messages on the channel are mixed with thread notifications resulting with a mess (you could, in fact, do not use thread since all messages are in main channel anyway).

On the other hand, Slack (as far as I know Rocket's threads were inspired by it) have ability to decide if message should be added to main channel or simply replied only in thread:

![image](https://user-images.githubusercontent.com/600668/69719738-6aac1480-1111-11ea-836d-cc4e326f2fdf.png)

I see benefits of both threads and discussions, but I don't want to make discussion all the time when I want to separate messages from main channel. Discussion is - in my opinion - good when you know the topic to discuss and invite specific group of channel's users. Sometimes you just want to answer to some question or comment shared link and threads are much better for that. But not with current implementation, which is frustrating for our users and prevents them from using threads.

**Comment by zdumitru** [comment]
Might be related to #14719

**Comment by Wirone** [comment]
@zdumitru I searched `thread` in issues, checked 4 pages of results and somehow missed it :man_facepalming: Yeah, definitely it's related.

**Comment by MartinSchoeler** [comment]
Thanks for the feedback. We are planning to do something like this on the next version of threads. Please, let's concentrate all the feedback and ideas on a single issue: RocketChat/Rocket.Chat#14719

Thanks!
