### ISSUE TITLE
Pressing Cancel while 'deleting by edit' message blocks sending messages

### ISSUE THREAD

**Issue by Mesysz** [RocketChat/Rocket.Chat#15862]
## My Setup
- Operating System: Ubuntu 18.04.3 LTS x86_64 
- App Version: 2.16.2 (and also 2.14.x, so it's not new bug)
- Installation type: snap install rocketchat-desktop (if this is what I had to post here)

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

If you send text to someone and after second thought you want to delete it so you edit message, remove all text and press enter BUT then you have third thought that this message was okay so you press Cancel, then you are done. You can't write anymore to this person/group unless you restart the app.
- Send message to someone
- RMB->Edit/ArrowUp to edit
- Remove all characters
- Press Enter (window with "are you sure?" pops up)
- Press Cancel
- Done

### Current Behavior
You can't write to this person/group anymore, unless you restart the app. Anything you type and press enter just disappears. You can't edit or delete anything.

### Expected Behavior
You can.

**Comment by ritwizsinha** [comment]
I'll have a go at it

**Comment by ritwizsinha** [comment]
@tassoevan I have found the files for message actions ,pin,mark -as-read,etc but not able to find edit message . Could you please let me know the location of the message edit feature

**Comment by ritwizsinha** [comment]
@tassoevan I am not able to find the message edit feature in the code, could you please direct me where it is located?
