### ISSUE TITLE
Can't get user 'Custom fields' from OAuth server

### ISSUE THREAD

**Issue by mohsen2hasani** [RocketChat/Rocket.Chat#15865]
Hi,
We have our own OAuth server and need to get some user information from OAuth (like phone and customer id) and display it on the user info page.
I set 'custom fields' in 'registration' and 'account' and that fields in 'scope' of my OAuth setting, but it's not working for me.
Is this possible? Or should it be developed to achieve this?
my scopes in OAuth:
`openid email profile groups offline_access phone`
Custom Fields to Show in User Info:
`[{"phone":"#{phone}"}]`
Custom Fields:
`{
    "phone": {
        "type": "text",
        "required": true,
        "minLength": 0,
        "maxLength": 12
    }
}`

**Comment by MartinSchoeler** [comment]
Not enough information provided. Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
