### ISSUE TITLE
WHMCS integration isn't working after latest update

### ISSUE THREAD

**Issue by fasalsh** [RocketChat/Rocket.Chat#15877]
Hello Guys,

We had an integration between WHMCS and RocketChat to alert whenever an even occur on it. This isn't working after updating to the latest 2.3.0 version for some reason. The calls are coming from the WHMCS module same as before, however, the RocketChat always throwing "400 Bad Request" to those calls. Was there anything changed on this webhook treating part? 

This is the RC log:
`I20191127-19:46:28.243(5.5) API ➔ debug POST: /hooks/Z69xeq/iRRnsHBg3QvvsBG229jJv25ZAwPrMJAC678jP5 
I20191127-19:46:28.246(5.5) Integrations ➔ Incoming WebHook.info Post integration: Orders 
I20191127-19:46:28.248(5.5) Integrations ➔ Incoming WebHook.debug @urlParams: { integrationId: 'Z69xeq',   token: 'iRRnsHBg3QvvsBG229jJv25ZAwPrMJAC678jP5' } 
I20191127-19:46:28.250(5.5) Integrations ➔ Incoming WebHook.debug @bodyParams: { text: '[Order #690751](https://DOMAIN/admin/orders.php?action=view&id=22) <br> A new order has been accepted.',   attachments:     [ { title: 'Client',        text: 'XXXXX',        title_link: 'https://DOMAIN/admin/clientssummary.php?userid=20' },      { title: 'Amount', text: '$1.00 USD', title_link: '' },      { title: 'Invoice #',        text: '14',        title_link: 'https://DOMAIN/admin/invoices.php?action=edit&id=14' },      { title: 'Payment Method',        text: 'PayPal',        title_link: '' },      { title: 'Status', text: 'Active', title_link: '' } ] } 
I20191127-19:46:28.257(5.5) API ➔ debug Failure { statusCode: 400,   body:     { success: false,      error: 'Invalid href value provided',      stack: undefined } }`

This is the error I'm getting on WHMCS:
`GuzzleHttp\Exception\ClientException:` Client error: `POST https://CHAT>DOMAIN/hooks/Z69xeq/iRRnsHBg3QvvsBG229jJv25ZAwPrMJAC678jP5` resulted in a `400 Bad Request` response:
{"success":false,"error":"Invalid href value provided"}`

Can anyone shed some light on this to resolve this? This is a crucial part in our business. 

Thanks :)

**Comment by digitalsparky** [comment]
Sure, will check it out shortly and get back to you with a fix asap.

Matt
