### ISSUE TITLE
Add custom OAuth

### ISSUE THREAD

**Issue by tammer123** [RocketChat/Rocket.Chat#15876]
### Description:

In new Administration UI under OAUTH button "Add Custom oAUTH" not working.

### Steps to reproduce:

1. Go to Administration -> OATUH
2. Click on Add Custom oAUTH
3. 

### Expected behavior:

Should open a window/tab to add new OAUTH.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.0
- Operating System: Ubuntu 18.04
- Deployment Method: Manual Install
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: In both version
- Operating System: Every OS.

**Comment by ankar84** [comment]
I confirm that bug. **Add custom oauth** button just do nothing.

**Comment by reetp** [comment]
@rocket-cat label add "type: bug"

**Comment by mbassiouny33** [comment]
I have the same issue running rocket.chat with docker using  `mage: rocketchat/rocket.chat:latest`

**Comment by ankar84** [comment]
Fixed at 2.3.1
Good job!

**Comment by gitwittidbit** [comment]
For this is (still?) happening in 5.4.1 (docker):

When I press "Add custom OAuth account", it asks me for a name. I provide a name and it says "added". 

But the new account doesn't appear anywhere. 

And when I try to add it again, it does not complain that an account of the same name already exists. (And it still is not added.)

Any ideas?
