### ISSUE TITLE
Need rocketchat send a message to origin page

### ISSUE THREAD

**Issue by tai-pd** [RocketChat/Rocket.Chat#15874]
I have app with iframe rocketchat
when command 'login-with-token', i need a message from rocketchat iframe to confirm user logined, then i can user callback in my app after user login:

	'login-with-token'(data, ...args) {
		if (typeof data.token === 'string') {
			Meteor.loginWithToken(data.token, function() {
				console.log('Iframe command [login-with-token]: result', [data, ...args]);
                                // need postMessage send to origin
			});
		}
	},

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
