### ISSUE TITLE
URGENT: Emoji Parsing in URL breaks URL

### ISSUE THREAD

**Issue by jcatarino** [RocketChat/Rocket.Chat#15882]
### Description:

URL with possible emojis is breaking the url and transforming part of the URL to emoji.

### Steps to reproduce:

Send the following message: http://myFakeLinkedInUrl/url:li:page

### Expected behavior:

The link should not break parsing of emoji should not happen.

### Additional context

Please see related issues, all report the same problem. This is breaking business as usual in my company, therefore the urgency. Thank you for your attention.

https://github.com/RocketChat/Rocket.Chat/issues/11989
https://github.com/RocketChat/Rocket.Chat.iOS/issues/2734

**Comment by reetp** [comment]
@rocket-cat label add duplicate

**Comment by reetp** [comment]
@rocket-cat close

Closing duplicate.

> This is breaking business as usual in my company, therefore the urgency. 

Please note that Rocket.Chat is Open Source.

For urgent support if you have a paid account please contact support@rocket.chat

If not you will just have to be patient. Obviously your Pull Request with a fix will be most welcome.
