### ISSUE TITLE
Broken message search

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#15884]
### Steps to reproduce:

1. Write a message with thread replies
2. Try to search something in this test messages

### Expected behavior:

Search works

### Actual behavior:

Search is broken

![image](https://user-images.githubusercontent.com/11560794/69876844-eef0ca00-12c0-11ea-92eb-83ff18e5e824.png)
![image](https://user-images.githubusercontent.com/11560794/69876878-0334c700-12c1-11ea-8b90-5cc9448ee98a.png)
![image](https://user-images.githubusercontent.com/11560794/69876895-0760e480-12c1-11ea-9244-6fb30d4ce4fa.png)

OR

Search works but empty window shown when clicking on "X replies" button
![image](https://user-images.githubusercontent.com/11560794/69877180-c74e3180-12c1-11ea-8fde-02ac44e9a8e3.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.3
- Operating System: linux
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.15

### Client Setup Information

- Desktop App or Browser Version: Browser and desktop app
- Operating System: Linux / MacOS

### Relevant logs:

N/A

**Comment by reetp** [comment]
Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
 
Test on 'latest' or 'develop' first please. Currently 2.3.0
 
Then search for 'search' in open and closed issues as I think this has been raised before.

**Comment by reetp** [comment]
Search "is:issue search thread"

#15200

Should be fixed in PR 15094 

Test on latest.

**Comment by zdumitru** [comment]
Still happening in 2.3.0.

**Comment by dusatvoj** [comment]
Thank's for testing @zdumitru . I wanted to test it on latest but I haven't any time to upgrade cluster

**Comment by reetp** [comment]
> Thank's for testing @zdumitru . I wanted to test it on latest but I haven't any time to upgrade cluster

You can test on open.rocket.chat and easily spin up a testing instance via docker. It just isn't that hard, and doesn't take long, especially if you keep a test instance running......

You can see it occurring on open.rocket.chat easily enough. I think it is finding the relevant message, but showing other messages in the thread, but without the message content:

![Screenshot_2019-12-02_13-41-40](https://user-images.githubusercontent.com/3800384/69960445-c4de1880-1509-11ea-991d-a212e497e1d1.png)

**Comment by MartinSchoeler** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/15841 Thanks!
