### ISSUE TITLE
Owner of a room cannot add a user to the room

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat#15883]
### Description:

User list is not available to the owner of a room

### Steps to reproduce:

1. Create a new room and set yourself as an owner
2. Open Member List and perss "Invite Users" button
3. Try to type username

### Expected behavior:

Users should be shown in search results

### Actual behavior:

Users list is not available and the owner of a room is not able to add anyone

![issue](https://user-images.githubusercontent.com/58329905/69868286-f9579780-12b1-11ea-80b5-6f9f04c28da4.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Windows 10 Pro
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.15

**Comment by reetp** [comment]
Can you please test on 'latest' as per this:
https://rocket.chat/docs/contributing/reporting-issues/

Currently 2.3.0 

Thanks

**Comment by carpecodeum** [comment]
im on it!

**Comment by gabriellsh** [comment]
Couldn't reproduce in 2.5.0-develop. Please try on latest and reopen if necessary. Thanks for the help!
