### ISSUE TITLE
Problem installing!

### ISSUE THREAD

**Issue by bixmatech** [RocketChat/Rocket.Chat#15899]
#Description:

I installed ubuntu 18.04 with plesk control panel on my vps, i then installed snapd and isntalled rocket chat. rocketchat and mongodb started successfully but caddy is failed.
sudo journalctl -f -u snap.rocketchat-server.rocketchat-caddy
-- Logs begin at Mon 2019-12-02 16:52:14 CET. --
Dec 02 22:02:03 vmi311898.contaboserver.net systemd[1]: Started Service for snap application rocketchat-server.rocketchat-caddy.
Dec 02 22:02:04 vmi311898.contaboserver.net rocketchat-server.rocketchat-caddy[4458]: 2019/12/02 22:02:04 loading Caddyfile via flag: open /var/snap/rocketchat-server/1414/Caddyfile: no such file or directory
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Scheduled restart job, restart counter is at 5.
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
Dec 02 22:02:04 vmi311898.contaboserver.net systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.

### Expected behavior:

To start without problem

### Actual behavior:

Caddy fails to start

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- Operating System: Ubuntu 18.04
- Deployment Method: snapd
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: latest

### Client Setup Information

- Desktop App or Browser Version: Chrome latest
- Operating System: Windows 10

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
