### ISSUE TITLE
Auto load images not working

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#15890]
### Description:

After updating Rocket.Chat from 2.2.0 to 2.3.0 none of the new or old uploaded images are not shown automatically anymore. The issue begun immediately after the first reload of pages after the upgrade.

Please comment or give a thumbs up if you have the same issue.

### Steps to reproduce:

1. Make sure you have `Auto Load images` option `True` under your user profile.
2. Upload an image (png or jpg) on any channel.

### Expected behavior:

Image should be visible automatically without prompt `Click to load`

### Actual behavior:

The image placeholder is shown instead of the actual image.

![Screenshot from 2019-11-30 17-48-50](https://user-images.githubusercontent.com/6958942/69902759-c557a180-1399-11ea-8df2-84d1000b5507.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 3.6

### Client Setup Information

Firefox, Chrome or Chromium web browsers

### Additional notes

The issue could be related to https://github.com/RocketChat/Rocket.Chat/pull/15716
However while our two separate instances have the issue, it seems that open.rocket.chat is not suffering from this. The reason could be related to the setup, for instance whether the attachments are saved under GridFS or filesystem.

We use GridFS for attachments.

**Comment by johnyb0y** [comment]
Just upgrade to 2.3.0 from 2.1.1. Seeing this issue as well.

**Comment by johnyb0y** [comment]
[Found this.](https://github.com/RocketChat/Rocket.Chat/pull/15716/commits/e6da5c098a4ee187a09a797cdb1278c9af9b302b#r352303068)

If I understand the code correctly the state of "saveMobileBandwidth" gets checked instead of "autoImageLoad". 
This would result in autoImageLoad beeing turned off if saveMobileBandwith is turned off.

**Disclaimer:** It's possible I'm totally wrong here :)

**Comment by Gummikavalier** [comment]
I failed in creating working custom CSS for this. Other possibly related change:
https://github.com/RocketChat/Rocket.Chat/commit/3c94b0bd1ba0467a1a0d75a2e3ee1a5a0ace5816

**Comment by johnyb0y** [comment]
I just tried to enable "saveMobileBandwith" in my Client which according to my theory would have re-enabled "autoImageLoad" as well. 
Didn't work, so probably I'm wrong.

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/70115931-3e235b80-162f-11ea-9a74-bc592c9432e2.png)

I can't click to load images in thread replies.

**Comment by wreiske** [comment]
I noticed this was closed, should I create a new issue on the image-to-download not working in threads? @sampaiodiego

**Comment by sampaiodiego** [comment]
yes @wreiske , please.. so we don't forget to fix it.. thanks

**Comment by wreiske** [comment]
> yes @wreiske , please.. so we don't forget to fix it.. thanks

https://github.com/RocketChat/Rocket.Chat/issues/15917

👍
