### ISSUE TITLE
Can't upload files due to timeout in browser

### ISSUE THREAD

**Issue by typorian** [RocketChat/Rocket.Chat#15893]
### Description:

I can not upload files to the newly installed rocket.chat that I installed via snapd. Doesn't matter if I use gridfs or filesystem.

### Steps to reproduce:

1. click on + in the chat
2. select a file from computer
3. click upload

### Expected behavior:

file is uploaded

### Actual behavior:

it is stuck at 0%, with no useful information in the server log. I only see that there is a timeout. I changed nothing from the snap install basically.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: fedora 31
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: ?
- NodeJS Version: v8.15.1
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version: latest google chorme
- Operating System: win 10

### Relevant logs:
server:
I20191202-15:02:42.653(1) Setting default file store to FileSystem 
I20191202-15:03:00.176(1) Setting default file store to FileSystem 
I20191202-15:05:43.765(1) Setting default file store to FileSystem 
I20191202-15:07:47.407(1) Setting default file store to GridFS 
I20191202-15:16:51.427(1) Setting default file store to FileSystem 
I20191202-15:22:43.474(1) Setting default file store to GridFS 
browser: (this error repeats over and over again)
weirdnumbersc.js?meteor_js_resource=true:187 POST http://server.ip.address.removed/ufs/FileSystem:Uploads/nuuSdBJsH3A3sGoBq?token=98f888687a&progress=0.25797918405265396 net::ERR_CONNECTION_TIMED_OUT

**Comment by typorian** [comment]
After some additional testing, I want to add that this seems to be completely independent of what kind of storage is set for file uploads. Even if I set it to webdav with a known working remote webdav server, I get errors in the browser and nothing happens.

**Comment by apacoco9861** [comment]
I have similar problem on latest helm chart (chart verion: rocketchat-1.1.12, app version: 1.3.1) installation (with latest rocketchat 2.2.0 image updated). User also use Chrome/Firefox, can't upload image as they can before.
I ask them to use IP instead of DNS URL. Problem resolved.
Rocketchat use Admin>General>Site URL to upload the file. While I first update Site URL to IP, it works fine, however, some user cannot resolve this Site URL DNS in their browser some how. OR their original access DNS URL been replaced as file upload URL causing a mis-match.
Anyway, ask them to use IP and make sure the Site URL in IP. While chat no impact, file upload should be ok.

**Comment by typorian** [comment]
@apacoco9861 my website URL has been set to the IP all along, because this was supposed to be a quick and easy interim solution. Does not work regardless.

**Comment by apacoco9861** [comment]
we deployed rocketchat for 2 months, experience lots of file upload problem. we tried to delete pod, redeploy, reboot server, install desktop client. Almost every 8 days would have user report problem. Install desktop client help make our environment calm and stable 5 days since last file upload problem report.

**Comment by typorian** [comment]
@apacoco9861 I just tried out the desktop client, exactly the same problem.

**Comment by EdiDD** [comment]
I have the same problem on desktop client 2.16.2 and via web browser. Any fix ?

**Comment by reetp** [comment]
Seems this is more likely to be poor configuration and not an Issue.

You are running SSL with a reverse proxy for security as per the docs?
You have got your DNS resolving correctly?
You have checked your websockets are working?

Have a read here:
https://rocket.chat/docs/getting-support/

Then here - look for Read This First at the top:
https://open.rocket.chat/channel/support

Here's the Read This First link - for testing websockets:
https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

**Comment by apacoco9861** [comment]
some users report problem over web client and some report on desktop.
we just make sure they connect via IP and use desktop client and we keep monitoring the situation. so far so good. those users able to connect without problem, were able to send file, but some how failed to upload. text msg no impact, remaining users to impact, just affected randomly partial user. Still can't find out the root cause.
we are supporting around 200 users.

**Comment by typorian** [comment]
We are using this on a local network only. We don't need SSL, we don't need DNS, we don't need a reverse proxy. The issue even occurs when I use the web client on the same machine the server runs on (a freshly installed fedora 31 workstation).
-------- Original message --------From: John Crisp <notifications@github.com> Date: 12/4/19  23:45  (GMT+01:00) To: "RocketChat/Rocket.Chat" <Rocket.Chat@noreply.github.com> Cc: typorian <eidorian@posteo.de>, Author <author@noreply.github.com> Subject: Re: [RocketChat/Rocket.Chat] Can't upload files due to timeout in browser (#15893) Seems this is more likely to be poor configuration and not an Issue.
You are running SSL with a reverse proxy for security as per the docs?
You have got your DNS resolving correctly?
You have checked your websockets are working?
Have a read here:
https://rocket.chat/docs/getting-support/
Then here - look for Read This First at the top:
https://open.rocket.chat/channel/support
Here's the Read This First link - for testing websockets:
https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RocketChat/Rocket.Chat/issues/15893?email_source=notifications\u0026email_token=AEQGAXT6CUHETRPOPC6NEQDQXAXG3A5CNFSM4JTW3RC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF6YLIA#issuecomment-561874336",
"url": "https://github.com/RocketChat/Rocket.Chat/issues/15893?email_source=notifications\u0026email_token=AEQGAXT6CUHETRPOPC6NEQDQXAXG3A5CNFSM4JTW3RC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEF6YLIA#issuecomment-561874336",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by typorian** [comment]
@reetp I can confirm that I do have a websocket connection (albeit ws:// and not wss://, for obvious reasons) and I also do get status code 101. This is on both a remote and the local machine that runs the server in Chrome and Chromium respectively.

**Comment by typorian** [comment]
Fixed it. The Site URL in the settings needs to contain the port as well, which is not indicated by the example written below it (at least in the German translation). I'm also relatively certain that this is not indicated in an obvious manner in the documentation, and maybe should also be added to the default setup when installing via snap.

**Comment by EdiDD** [comment]
Thank you. I can confirm that adding port fixed issue.
