### ISSUE TITLE
mail leaks in log

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [RocketChat/Rocket.Chat#15892]
### Description:

Recently we tried to use email for our self hosted rocketchat. Anyway, this was not possible and email settings are removed. However Rocketchat now tries to sent notification emails, but fails and logs them into log file. This means that all admins are able to read private messages by looking at message log. 

### Steps to reproduce:

1. Enable email.
2. Remove email setitngs.
3. Check the logs.

### Expected behavior:

Message body of an email should not be part of log. We can disable "Show message in email notification" but this is not sufficient because an admin can enable it again.

### Actual behavior:

![image](https://user-images.githubusercontent.com/41470536/69952250-1630dc80-14f7-11ea-9f5d-708f612cba84.png)

### Server Setup Information:

Version 2.30
Apps Engine Verison 1.7.0
OS type: GNU/Linux centos7
Node verison: v8.11.4
Mongo verison 3.6.15

**Comment by craig** [comment]
Isn't this fixed via #15928?

**Comment by makibras** [comment]
it was indeed fixed by https://github.com/RocketChat/Rocket.Chat/pull/15928 :)
