### ISSUE TITLE
[BUG] Losing login frequently

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#15904]
### Description:
Both on the desktop app and browse I losing login frequently.
Example: In one day, I losing about 10 times.

Login iframe: Enabled

### Steps to reproduce:
With time, losing login.

### Expected behavior:

Stay login

### Actual behavior:
Losing login frequently, both on the desktop app and browser

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.1
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 1.6.0
- MongoDB Version: 161

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows and linux Ubuntu 18.04

### Additional context

![image](https://user-images.githubusercontent.com/17053653/70142121-4a330b80-1677-11ea-8075-b5e537f70669.png)

### Relevant logs:

Server logs:
`I20191203-08:45:55.565(-3) Exception while invoking method 'login' { Error: Match error: Expected string, got undefined     at check (packages/check/match.js:36:17)     at MethodInvocation.<anonymous> (app/iframe-login/server/iframe_server.js:11:2)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43   message: 'Match error: Expected string, got undefined',   path: '',   sanitizedError:     { Error: Match failed [400]     at errorClass.<anonymous> (packages/check/match.js:91:27)     at new errorClass (packages/meteor.js:655:17)     at check (packages/check/match.js:36:17)     at MethodInvocation.<anonymous> (app/iframe-login/server/iframe_server.js:11:2)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43      isClientSafe: true,      error: 400,      reason: 'Match failed',      details: undefined,      message: 'Match failed [400]',      errorType: 'Meteor.Error' },   errorType: 'Match.Error' } 
I20191203-08:45:55.565(-3) Sanitized and reported to the client as: { Error: Match failed [400]     at errorClass.<anonymous> (packages/check/match.js:91:27)     at new errorClass (packages/meteor.js:655:17)     at check (packages/check/match.js:36:17)     at MethodInvocation.<anonymous> (app/iframe-login/server/iframe_server.js:11:2)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43   isClientSafe: true,   error: 400,   reason: 'Match failed',   details: undefined,   message: 'Match failed [400]',   errorType: 'Meteor.Error' } 
I20191203-08:45:55.566(-3) undefined undefined `

Browser Logs:
![image](https://user-images.githubusercontent.com/17053653/70056606-83f20c80-15ba-11ea-9e3f-8920484d1988.png)

![image](https://user-images.githubusercontent.com/17053653/70056642-92402880-15ba-11ea-9006-b129965e6cb8.png)

![image](https://user-images.githubusercontent.com/17053653/70056664-9a986380-15ba-11ea-87be-b50e91d408b5.png)

![image](https://user-images.githubusercontent.com/17053653/70056681-a126db00-15ba-11ea-8205-a5e5d59e3fd1.png)

![image](https://user-images.githubusercontent.com/17053653/70056710-ab48d980-15ba-11ea-878d-5cf81bbe98f6.png)

**Comment by dusatvoj** [comment]
I'm using RC v2.3.0 and 2.3.2 on one project and login is lost very frequently for some users. Without errors syslog.

**Comment by guilhermecfviana** [comment]
I still have this problem, any news?

**Comment by dusatvoj** [comment]
I've upgraded to latest `v2.4.x` RC and it seems solved now :open_mouth:
