### ISSUE TITLE
Question: Mandatory 2fa for role feature

### ISSUE THREAD

**Issue by akinb85** [RocketChat/Rocket.Chat#15906]
Hello All,

Which versions+ of the rocketchat supports 'Mandatory 2fa for role (#9748)'? I could not find out any information in the release notes that contains Mandatory 2fa for role information.

Thank you in advance for your support.

**Comment by MartinSchoeler** [comment]
In release [0.73.0](https://github.com/RocketChat/Rocket.Chat/pull/13040) Also, please use our [forum](https://forums.rocket.chat/) for future questions. Thanks
