### ISSUE TITLE
Auto deleting messages

### ISSUE THREAD

**Issue by lipe1966** [RocketChat/Rocket.Chat#1591]
I looked around and did not saw anything like.
My idea is to have the ability to send a direct message where the receiver will be able to read the message only one time, and after that the message would auto delete.

The case works like this.

1 sender chose to send a auto delete message to an specific receiver.
2 sender types the message and send it
3 the receiver see the notification of the message and is not able to read it. The message will show only while the receiver keeps the message clicked
4 after the receiver release the click or touch the message will be deleted in both ends
##

**Comment by 9203948** [comment]
+1

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
