### ISSUE TITLE
rocket chat server crashed randomly

### ISSUE THREAD

**Issue by sailfish009** [RocketChat/Rocket.Chat#15914]
### Description:

rocket chat server seg-faulted

### Expected behavior:

no crash rocket chat server.

### Actual behavior:

rocket chat server stopped working suddenly.

### Server Setup Information:

- Version of Rocket.Chat Server:  2.3.0
- Operating System: ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.10.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: firefox 68
- Operating System: ubuntu 18.04 

### Relevant logs:
/var/log/syslog:

systemd[1]: rocketchat.service: Main process exited, code=dumped, status=11/SEGV
systemd[1]: rocketchat.service: Failed with result 'core-dump'

**Comment by reetp** [comment]
> • NodeJS Version: v8.10.0


Suggest you first check the engine versions here:
https://github.com/RocketChat/Rocket.Chat/releases

Node: 8.15.1
NPM: 6.9.0

**Comment by sailfish009** [comment]
@reetp , how do i install nodejs v8.15.1? i have upgraded it to v8.11.4.

**Comment by reetp** [comment]
This is a bug tracker, not a support forum

Please ask for assistance in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

**Comment by sailfish009** [comment]
to update Node v8.11.4 solved the problem.
