### ISSUE TITLE
Permissions/Option to remove "Disable Auto-Away" from User's Preferences

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat#15911]
### Description:

The Auto Away functionality present in RocketChat works great; however, we would like the ability to prevent users from disabling/modifying these values.  Much to my confusion, our management team is using the online-state of their subordinates as a running attendance (to make sure everyone is working); including for our remote users.  At this time, if anyone is savvy enough to go looking into the settings, they can disable the auto-away status change entirely; making it appear as though they are working, when they really are not.

It would be nice to, if possible, have a user-permission, or option within the Accounts settings to disable access to these settings.

### Expected behavior:

Ideally, we're looking for either a permission that can be adjusted for a particular role; or a global option within the "Accounts" configuration; allowing access to the Auto-Away settings to be disabled.

### Server Setup Information:

- Version of Rocket.Chat Server: `1.3.2` (we'll be updating in the coming weeks, when I have time to babysit it)
- Operating System: `CentOS 7.6.1810 (Core)`
- Deployment Method: Manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled (?)
- NodeJS Version: `8.11.4 - x64`
- MongoDB Version: `4.0.12`

### Client Setup Information

- Desktop App or Browser Version: `Rocket.Chat.Electron 2.16.2 & 2.17.0`
- Operating System: `Windows 7 Professional x64 & Windows 10 Pro x64`

### Additional context

I'm aware we're running an older version of both the application, as well as the client.  At this time, we're looking to manually upgrade the server and, by extension, have someone (me) sit around to babysit and keep an eye on that process...even though it should be relatively plug-and-play, so to speak.  Still, I'll have some time to deal with this in the coming weeks--hopefully Saturday (2019-11-07) will yield 15-30min to handle this.

If any additional options suddenly present themselves post upgrade, I will update this post.

**Comment by lorek123** [comment]
I totally understand your point of having such option but there is so many ways to mimic that you are working so auto-away won't kick in. Especially if you consider tech savvy people. https://www.zhornsoftware.co.uk/caffeine/ is one example, but there are many more.
