### ISSUE TITLE
Custom user information is not received from OAuth

### ISSUE THREAD

**Issue by mohsen2hasani** [RocketChat/Rocket.Chat#15912]
### Description:

We have our own OAuth server and need to get some user information from OAuth (like phone and customer id) and display it on the user info page.

### Steps to reproduce:

1. Go to 'Accounts' and set this items in 'Custom Fields to Show in User Info':
`[{"CustomId":"#{CustomId}"}, {"phone":"#{phone}"}]`
2. Go to 'Accounts > Registration > Custom Fields'
3. Set this json :
`{"phone" :{"type": "text","required": true,"minLength": 0,"maxLength": 12},"CustomId": {"type": "text","required": true,"minLength": 0,"maxLength": 10}}`
4. Set 'Registration Form' to 'Disabled'
5. Go to 'OAuth'
6. Create 'Custom OAuth' and set this items in 'Scope':
`openid email profile groups offline_access phone CustomId`

### Expected behavior:

I was expecting to get phone and CustomId from OAuth and record details in user information.

### Actual behavior:

None of the values listed are recorded in user information.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Apps Engine Version: 1.7.0
- Operating System: CentOS 7 x64
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- Operating System: Windows 10

### Additional context

We want only our customers can register and login in Rocket chat so i set 'Accounts > Show Default Login Form' to 'false' and set 'Accounts > Registration >Registration Form' to 'Disabled'

**Comment by carpecodeum** [comment]
I'm on it

**Comment by carpecodeum** [comment]
@mohsen2hasani models of accounts?

**Comment by mohsen2hasani** [comment]
> @mohsen2hasani models of accounts?

what do you mean of account model?

**Comment by carpecodeum** [comment]
> > @mohsen2hasani models of accounts?
> 
> what do you mean of account model?

i mean to say is there a folder called accounts? and is customfields a model? because i couldn't locate these files

**Comment by rehaankhan1** [comment]
Sir, @mohsen2hasani 
Are you sure, that your OAuth code is correctly written?

**Comment by rehaankhan1** [comment]
> > > @mohsen2hasani models of accounts?
> > 
> > 
> > what do you mean of account model?
> 
> i mean to say is there a folder called accounts? and is customfields a model? because i couldn't locate these files

Go to Accounts > Scroll Below > Registration > AT last you will see a big text container which is Custom Fields
x-special/nautilus-clipboard
copy
![Screenshot from 2019-12-04 21-41-43](https://user-images.githubusercontent.com/20107730/70168938-0f64be00-16df-11ea-89f6-b1c01ee5e5e5.png)


@carpecodeum

**Comment by mohsen2hasani** [comment]
> Sir, @mohsen2hasani
> Are you sure, that your OAuth code on your end is correctly written?

Yes, i used this oauth in other projects and get data.

**Comment by mohsen2hasani** [comment]
> > > > @mohsen2hasani models of accounts?
> > > 
> > > 
> > > what do you mean of account model?
> > 
> > 
> > i mean to say is there a folder called accounts? and is customfields a model? because i couldn't locate these files
> 
> Go to Accounts > Scroll Below > Registration > AT last you will see a big text container which is Custom Fields
> x-special/nautilus-clipboard
> copy
> ![lol](https://user-images.githubusercontent.com/20107730/70169045-4509a700-16df-11ea-9fe9-e05c300b21a1.png)
> 
> @carpecodeum

**Comment by rehaankhan1** [comment]
I will try it tomorrow by creating a dummy OAuth API.

**Comment by carpecodeum** [comment]
@mohsen2hasani i am sorry but i am already working on it i hope you understand :)

**Comment by msisskin** [comment]
Any traction on this? We have a similar use case.
