### ISSUE TITLE
How do I make it so the chat message are encrypted so that even someone with admin database access cannot read them?

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#15920]
Not sure where else to post this question.... but how do I make it so that everything is secure for my users?    As it is now, it appears that an admin could go in and read messages between people.  Even though I'm the only person with admin access to the database, I'd prefer that even I were unable to read messages between users.  How do I configure this?

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

This seems to be a setup/support issue.

Please read the documentation.

Questions should be asked in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

**Comment by makibras** [comment]
@flantascience 
End to Encryption might be help for your case. While it does not make "everything secure", it is targeted at your goal to prevent admins from reading plaintext messages between users that use this feature. The admin can only see an encrypted string, the encryption keys are generated client side and cannot be accessed by the admin. Just make sure to activate the global setting in the admin settings so your users can start using this.
https://rocket.chat/docs/user-guides/end-to-end-encryption/

**Comment by flantascience** [comment]
Thank you @makibras 
This may be a good solution.... does it require every user to go through this 'one time passcode' type proccess?   Or is that something I do as an admin?   It seems like it'd be a pain to put that on the users.... but would love to be able to make everything encrypted globally.

**Comment by makibras** [comment]
@flantascience 
the code (actually the encryption key) is generated client-side at the user and only shown to him. Users need to save/remember that key as they will need it for all clients they use. They enter it one time per client and from there on it works on that client. As it is stored in the cache, clearing the cache or browsing as "incognito" requires re-entering the key. It is functioning almost like a second password. You as admin just need to enable the global setting and then users are free to choose if they want to encrypt their channel or not. New channels are not encrypted by default but it is choice of the channel admin or moderator.
I would suggest that before you enable the setting in your system, you announce via broadcast to your users that they can start using it and maybe you enable it for a couple of channels you are using yourself. Once the global setting is enabled, all users will after their next login see the blue ribbon on top with their key. They can reset their key in their user account settings themselves.
One caveat: end-2-end encryption has yet to come to the mobile clients. But it is coming soon
