### ISSUE TITLE
Transferring a LiveChat room with an empty-named visitor from a Bot to a department return error in version 2.3.0

### ISSUE THREAD

**Issue by TeraMind244** [RocketChat/Rocket.Chat#15923]
### Description:

After upgrading Rocket.Chat to version 2.3.0, if a LiveChat room with an empty-named visitor is transferred to a department, the `/api/v1/livechat/room.transfer` request returns an error `Match error: Expected string, got undefined in field name` with status code 400 Bad request.

**Note:** This bug appears in version 2.3.0. I tested with version 2.2.0, it does not happen.

### Steps to reproduce:

1. A visitor creates a LiveChat room without specifying a name.
2. A bot takes the LiveChat.
3. The visitor gives a transfer-to-another-department command to the bot.
4. The bot calls `/livechat/room.transfer` request.

### Expected behavior:

With proper arguments, the LiveChat room should be transferred successfully.

### Actual behavior:

An error is returned with status code 400 Bad request.

### Server Setup Information:

- Version of Rocket.Chat Server: **2.3.0**
- Operating System: Windows 10
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v10.16.3
- MongoDB Version: v4.0

### Client Setup Information

- Desktop App or Browser Version: Chrome v78.0.3904.108
- Operating System: Windows 10

### Additional context

To provide a better context, below are my request `/api/v1/livechat/visitor/:token` using Postman.

If a visitor has a specific name
```
{
    "visitor": {
        "_id": "Zk8d7yt5d254jFPcf",
        "username": "guest-11",
        "_updatedAt": "2019-12-05T10:23:13.842Z",
        "department": "sCXDpqqvQzsKczKLw",
        "name": "my user name",
        "token": "my user name-1575541393760"
    },
    "success": true
}
```
Then the request to `/api/v1/livechat/room.transfer` will be successful.

If a visitor doesn't have a specific name
```
{
    "visitor": {
        "_id": "uqSkC6zTgdvtz52ua",
        "username": "guest-9",
        "_updatedAt": "2019-12-05T09:25:26.607Z",
        "department": "sCXDpqqvQzsKczKLw",
        "token": "guest-1575537926541"
    },
    "success": true
}
```
Then the request to `/api/v1/livechat/room.transfer` will be fail, with the error.
```
{
    "message": "Match error: Expected string, got undefined in field name",
    "path": "name",
    "sanitizedError": {
        "isClientSafe": true,
        "error": 400,
        "reason": "Match failed",
        "message": "Match failed [400]",
        "errorType": "Meteor.Error"
    },
    "errorType": "Match.Error",
    "success": false
}
```

**Comment by carpecodeum** [comment]
can i work on this?
