### ISSUE TITLE
Expand/Collapse button in the Admin menu not working - IE 11

### ISSUE THREAD

**Issue by Srinivasan2017** [RocketChat/Rocket.Chat#15925]
Hi Team

We are using the IE 11 for rocketchat and noticed and Expand/Collapse button in the Admin menu not working - IE 11.

Kindly help us to resolve this 

![image](https://user-images.githubusercontent.com/11881505/70233924-88b6ec00-1785-11ea-98f8-c5ba5df72e83.png)

**Comment by MartinSchoeler** [comment]
@Srinivasan2017 Not enough information provided. Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by tassoevan** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.Fuselage/issues/105?

**Comment by gabriellsh** [comment]
We're still waiting for more details, please refer to the guidelines (martin sent its link above) so you can figure out what is needed. Thanks for the collaboration.
