### ISSUE TITLE
Keycloak integration - name not changed in Rocket.Chat when changed in Keycloak

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#15938]
### Description:

We have integrated Rocket.Chat with Keycloak as Oauth. Where user "name" is being changed in Keycloak is not updated in Rocket.Chat mongo collection field "users.name", which is being shown in app, but only "users.services.keycloak.username".

### Steps to reproduce:

1. Integrate Rocket.Chat with Keycloak as a Oauth
2. For existed user change "name" in keycloak
3. In Rocket.Chat name is not changed in field "users.name"

### Expected behavior:

"users.name" is being changed when changed in Oauth.

### Actual behavior:

In Rocket.Chat name is not changed in field "users.name" when changed in Oauth.

### Server Setup Information:

Version of Rocket.Chat Server: 2.3.0
Operating System: Centos 7
Deployment Method: Docker Compose
Number of Running Instances: 9
DB Replicaset Oplog: YES
NodeJS Version: 8.15.
MongoDB Version: 4.0.12

### Additional context

```json
{
        "_id" : "xxx",
        "createdAt" : ISODate("2019-05-21T05:48:43.383Z"),
        "services" : {
                "keycloak" : {
                        "_OAuthCustom" : true,
                        "accessToken" : "xxx",
                        "idToken" : "xxx",
                        "expiresAt" : 1575894715791,
                        "refreshToken" : "xxx",
                        "sub" : "xxx",
                        "email_verified" : false,
                        "name" : "Emilian xxx",
                        "preferred_username" : "xxx",
                        "given_name" : "Emilian",
                        "family_name" : "xxx",
                        "email" : "xxx",
                        "id" : "xxx",
                        "username" : "xxx",
                        "locale" : "pl",
                        "serverURL" : "https://xxx"
                },
                "resume" : {
                        "loginTokens" : [
                                {
                                        "when" : ISODate("2019-12-09T11:55:47.260Z"),
                                        "hashedToken" : "xxx"
                                },
                                {
                                        "when" : ISODate("2019-12-09T12:26:57.660Z"),
                                        "hashedToken" : "xxx"
                                }
                        ]
                }
        },
        "type" : "user",
        "status" : "online",
        "active" : true,
        "name" : "Emil xxx",

**Comment by sress** [comment]
This still seems to be an issue at least up to RC version 6.0.8.
Not only name changes, but also email changes don't show in Rocketchat and you can't even login anymore to RC after the changes in Keycloak.
