### ISSUE TITLE
Huge rocketchat_statistics and userSessions collections

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#15945]
### Description:

Hi,

Just to know, is it normal to have such sizes for rocketchat_statistics and userSessions collections ?
1,7G rocketchat_sessions.bson
4,3G rocketchat_statistics.bson

Servers are running since 2017 with 3 days session, 1500 active users on 71 instances.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 71
- DB Replicaset Oplog: yes
- NodeJS Version: 8.12.0
- MongoDB Version: 4.0

**Comment by reetp** [comment]
@rocket-cat close

Github is reserved for bugs.

https://rocket.chat/docs/contributing/reporting-issues
https://rocket.chat/docs/getting-support/

> Just to know, is it normal to have such sizes for rocketchat_statistics and userSessions collections ?

How long is a piece of string? What is 'normal'? It all depends on usage.

Ask in the forums or open.rocket.chat
