### ISSUE TITLE
lost change password functionality in. 2.3.0

### ISSUE THREAD

**Issue by villadalmine** [RocketChat/Rocket.Chat#15952]
After update to version 2.3.0 and also 2.3.1 i can not assign password to new user also my own  user.

**Comment by villadalmine** [comment]
I start with 2.2.0 then 2.3.0 , problem appear, and then 2.3.1

I have self host rocketchat, and used with compose . of oficial page.

**Comment by reetp** [comment]
Search for both open AND closed Issues

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+password

I think this may be the issue:

https://github.com/RocketChat/Rocket.Chat/issues/15880

**Comment by villadalmine** [comment]
Thanks duplicated issues i will follow there. Thansk!
