### ISSUE TITLE
Missing login button on default landing page when Allow anonymous read is enabled.

### ISSUE THREAD

**Issue by eliotb** [RocketChat/Rocket.Chat#15951]
### Description:

A UI or UX problem:

When  "Allow Anonymous Read" is enabled, there is no way to log in from the default landing page.  It is necessary to log in to see e.g. direct chats or private rooms.
To log in, one must visit a visible room, and use the provided login button.

### Steps to reproduce:

1. Enable "Allow Anonymous Read".
2. Log out of chat. (or visit from a clean session)
3. You'll be dropped back to https://[server]/home
4. Notice lack of login link or button
5. Click on a visible channel
6. Observe [sign in to start talking] button at the bottom of the channel.

### Expected behavior:

A login button is present somewhere in the UI on the home page.

### Actual behavior:

No way to login from the home page.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Firefox, or chrome
- Operating System: Debian 10

**Comment by NitinBhasneria** [comment]
@MartinSchoeler I want to claim this issue?

**Comment by NitinBhasneria** [comment]
@eliotb @MartinSchoeler I want to claim this issue. Can I?

**Comment by ashwaniYDV** [comment]
@MartinSchoeler I have made the pull request. Please review :)

**Comment by eliotb** [comment]
This is still an issue in 3.1.1.
Also could do with same login button on the screens that are shown when trying to visit a private group or direct message thread when not logged in.

**Comment by luixxiul** [comment]
> This is still an issue in 3.1.1.

Obviously this is because the PR which should address the issue is not merged yet, #16235.
