### ISSUE TITLE
Change user password in Admin Side

### ISSUE THREAD

**Issue by chimsue245** [RocketChat/Rocket.Chat#15958]
Hi guys please help me how to see the input text box for password im using in admin so i want to change username for my user but the change password box not appear . please help me TIA,

![Capture](https://user-images.githubusercontent.com/17686420/70703573-5c621900-1d0b-11ea-8f8c-fa4be8a712c3.PNG)

**Comment by OPARA-PROSPER** [comment]
To Change your password you'd need to locate the `require password change` on the right side:

![rocket](https://user-images.githubusercontent.com/30195980/70706803-fc517f80-1cd6-11ea-96b9-d22f096e7aee.png)

click the toggle button (should turn green when you do), when you hit the save button, you'd be prompted for a new password.

**Comment by makibras** [comment]
Hi @chimsue245 

this change was on purpose in the most recent version to prevent admins from knowing user passwords which is not something to happen in the first place and therefore a security fix.

You can find a more elaborate discussion here where I explain this change here:
#15880 

To reset a password, toggle "set random password" and "request password change" and click save. Your user will receive an email with a temporary password and can set himself a new one.

In case you are locked down in the password reset, please reopen this issue again and explain your setup, so we can look for a resolution.

**Comment by rj11** [comment]
Umm yeah, my users have no idea how to even check their email.  There needs to be a way to turn this off.

**Comment by guillecorrea** [comment]
> Hi @chimsue245
> 
> this change was on purpose in the most recent version to prevent admins from knowing user passwords which is not something to happen in the first place and therefore a security fix.
> 
> You can find a more elaborate discussion here where I explain this change here:
> #15880
> 
> To reset a password, toggle "set random password" and "request password change" and click save. Your user will receive an email with a temporary password and can set himself a new one.
> 
> In case you are locked down in the password reset, please reopen this issue again and explain your setup, so we can look for a resolution.
Hi @makibras 
This change is valid when all users have a  valid email and in a public service .  In my case , only private use,  some users do not have email because they do not need it for  work ,they only need to chat. There needs to be a way to turn this off.  Please consider it.

**Comment by barrydegraaff** [comment]
Yeah this is annoying...

**Comment by djpavlo** [comment]
I want to reset password by admin panel too. work in my chat stopped :(

**Comment by yaserhosseini** [comment]
**Hi there**

**Unfortunately, the ability to directly change the password in the admin section has been removed in the new version**

> ### **But there is still a way!** 

The Rocket Chat team gives us a lot of opportunities through EPA Restrictions
You can quickly change your users' password by using up to 5 of these web services.
The first step is to log in through the following web service
`http://*****:3000/api/v1/login`
The above service will be sounded by Post Action with the following wind values ​​and your personal information
`{"user": "*****", "password": "****"}`
At the outlet of the service there is your own Token and Users ID
Then the service
`http://****: 3000/api/v1/ users.info?username=*****`
With get action and body values
`X-Auth-Token` and `X-User-Id` you received from the previous service and
`X-Requested-With: XMLHttpRequest`
Submit to show you the user ID of the user you want to change the password

> And finally

With service
`http://****:3000/api/v1/users.update`
`{"userId": "***", "data": {"password": "***"}}`

Change your user information

**Pay attention**
In all services
`Content-Type: application/json` Must be sent.

### **more information**
[https://rocket.chat/docs/developer-guides/rest-api/](https://rocket.chat/docs/developer-guides/rest-api/)

**Comment by johnburkhard** [comment]
This change needs to be reverted because not everyone runs an email notification server. Admin of a rocket chat server should be left up to the admins of the server, not Rocket Chat developers and the workflow that they feel is best.

I literally can't reset user passwords for a team of over 300 people now with this change.

**Comment by reetp** [comment]
Don't follow up here. This a duplicate bug and closed.

Check https://github.com/RocketChat/Rocket.Chat/issues/15880

This change has been reverted.
