### ISSUE TITLE
MongoDB license issue for commercial use

### ISSUE THREAD

**Issue by chatdemoman** [RocketChat/Rocket.Chat#15950]
Hi Team,

It would be great to know whether the rocket chat support other DBs rather than mongoDB since its no more pure open source. And what are all the options  ?

**Comment by antkaz** [comment]
This question has already been raised more than once. You can find the answer here:
https://github.com/RocketChat/Rocket.Chat/issues/533

**Comment by reetp** [comment]
@rocket-cat close

https://forums.rocket.chat/t/legal-implications-of-mongodb-licensing-change/2332/5
