### ISSUE TITLE
No message-dropdown in the flex-tab

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1596]
The cog for starred and pinned messages doesn't always work. It works in some servers but not others. Out of 4 servers I use, only 1 has it working. Here is the result from using Firefox Inspect Element and you see the `<div class="message-dropdown" ...` is totally missing.

![acc-chat0](https://cloud.githubusercontent.com/assets/432460/11662313/eddb25c0-9da3-11e5-8349-d09d68bb00d6.png)

It doesn't even work on the official https://demo.rocket.chat server:
![acc-chat1](https://cloud.githubusercontent.com/assets/432460/11662372/4d3ec18e-9da4-11e5-9721-476fafb8a50e.png)

However, it works on a test server deployed under http://fad.rocket.chat 
![acc-chat2](https://cloud.githubusercontent.com/assets/432460/11662440/93d3a7d6-9da4-11e5-8fe6-ddbc8073d2d9.png)

* Note: it is possible that the working server is running an old version of rocket chat, and some new changes broke the implementation.

**Comment by jjayala1** [comment]
I agree.   I can star messages but I can't pin. I update my deploy via docker last week.

**Comment by fduraibi** [comment]
@jjayala1 what you are describing is actually a different issue that I also face on some servers even though I have admin permission.

**Comment by marceloschmidt** [comment]
This is most probably fixed now, as there has been major improvements on starred and pinned message panels. If you find it still has a bug, please advise and we'll reopen it.
