### ISSUE TITLE
Loss of configuration mongo db

### ISSUE THREAD

**Issue by raabeer** [RocketChat/Rocket.Chat#15964]
Good Morning.

I have been facing a problem that unfortunately I found nothing related in the community.

I installed Rocket Chat on top of Docker.
The Docker-based installation has greatly improved our performance, but I have been facing a problem with external DNS pointing.

My problem is not really in Docker but in the database (Mongo DB). Because there we have a documment called "db.rocketchat_settings.find", as the image below.
![print mongo 1](https://user-images.githubusercontent.com/58339703/70736311-d59f4300-1cee-11ea-9c60-ca7f85f3db70.PNG)

As I have ip and dns, I have to update these settings in the database, by the command
"db.rocketchat_settings.update({"_id":"Site_Url"}, {$set: {"value": "http://chat.ids.inf.br"}})".
This works, but some time later the database itself updates this setting, changing the "VALUE" field to the internal IP address instead of leaving DNS.
![print mongo 2](https://user-images.githubusercontent.com/58339703/70736343-e51e8c00-1cee-11ea-933b-87002c4e4a27.PNG)
![print mongo 3](https://user-images.githubusercontent.com/58339703/70736345-e8197c80-1cee-11ea-8bd4-b40ccae6530b.PNG)

Facing this problem for 10 days and I don't know what else to do, I tried to update the database, the rocket version, but nothing solved it.

Rocket-chat version: 2.0
Mongo version: 4.0

additional image docker-compose.yml.
![print docker-compose yml](https://user-images.githubusercontent.com/58339703/70736403-02ebf100-1cef-11ea-88c5-730909bbd8f4.PNG)

**Comment by rodrigok** [comment]
@raabeer did you try to pass the environment variable `ROOT_URL=your.url.here` to your docker when starting the container?

**Comment by rodrigok** [comment]
@raabeer you can check this docs for more info https://rocket.chat/docs/installation/docker-containers/index.html#6-create-the-docker-composeyml-file--local-directories

**Comment by raabeer** [comment]
Bom dia Rodrigo, vou responder em português para facilitarmos a comunicação.
Então, esse DNS é apontado pra meu ip externo, ele nao roda no server do rocket, então se eu apontar ele na ROOT_URL, vou causar um loop nos usuários que utilizam interno.

**Comment by rodrigok** [comment]
@raabeer can you please call me at https://open.rocket.chat? My username there is `rodrigo.nascimento`. Then we can talk in Portuguese and I update this issue with our conclusions.
