### ISSUE TITLE
OAuth2 token failed for custom OAuth

### ISSUE THREAD

**Issue by jwillmer** [RocketChat/Rocket.Chat#15960]
I try to setup a custom OAuth 2 provider but the login process always fails. Both applications (RocketChat and UserMgm) are running on the same server in docker containers. Internally user mgm is reachable by `http://usermanagement:5001`. Externally only by HTTPS and a FQDN (using traefik as proxy).

RockeChat Configuration:
![image](https://user-images.githubusercontent.com/1503577/70707873-8569b600-1cd9-11ea-8da2-934b55389130.png)

RockeChat Log:
```
Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with usermanagement at http://usermanagement:5001/OAuth2/Token. failed [415]
    at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:132:18)
    at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:189:26)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
    at middleware (packages/oauth/oauth_server.js:161:5)
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
  message: 'Failed to complete OAuth handshake with usermanagement at http://usermanagement:5001/OAuth2/Token. failed [415]',
  response:
   { statusCode: 415,
     content: '',
     headers:
      { connection: 'close',
        date: 'Thu, 12 Dec 2019 11:12:13 GMT',
        server: 'Kestrel',
        'content-length': '0',
        'content-security-policy': 'default-src \'self\';script-src \'self\' ... ;frame-src \'self\'' },
     data: null } }
```

HTTP code 415 refers to `Unsupported Media Type`. And we believe RocketChat fails to sent the right media type to the OAuth token endpoint of the user mgm:

```
        [HttpPost(nameof(Token)), Consumes("application/x-www-form-urlencoded")]
        [ProducesResponseType(typeof(OAuthTokenResponse), (int)HttpStatusCode.OK)]
        [Produces("application/json")]
        public IActionResult Token([FromBody] OAuthTokenRequest data)
```

RocketChat version:
![image](https://user-images.githubusercontent.com/1503577/70709475-40e01980-1cdd-11ea-9174-30cb7e73b0b9.png)

Based on the logs I believe RocketChat is not sending the payload in the `x-www-form-urlencoded` format. Is this assumption correct and how can we support RocketChat in our user mgm?

**Comment by alexandrtovmach** [comment]
@jwillmer did you find a solution?

**Comment by jwillmer** [comment]
Yes, we switched to Mattermost and are very happy with the switch :)

**Comment by alexandrtovmach** [comment]
I see, thanks =)
