### ISSUE TITLE
Anyone figure out how to get Amazon DocumentDB working with Rocket.Chat?

### ISSUE THREAD

**Issue by blharveymi** [RocketChat/Rocket.Chat#15963]
Was wondering if anyone as relooked at using Amazon DocumentDB for rocket.chat. I know they have made some improvements to it and looks like you could use changestreams in place of oplogs.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
