### ISSUE TITLE
Custom emojis are being replaced with an internal with similar name

### ISSUE THREAD

**Issue by JakubJachym** [RocketChat/Rocket.Chat#15973]
### Description:

When using a custom emoji, it gets replaced with an internal emoji with similar name. For example `:ga:` emoji (Google Analytics icon) is replaced with `:flag-ga:` (flag of Gabon). Or `:facepalm:` is replaced with `:person_facepalming:`

### Steps to reproduce:

1. Create a custom emoticon (Administration --> Custom Emoji) with name or alias `ga`
2. Go to a chat and use the custom emoji, type `:ga:` and send the message.
3. The actual sent message contains `:flag_ga:` emoticon instead.

### Expected behavior:

The `:ga:` emoji should be displayed.

### Actual behavior:

![record_191213_141518](https://user-images.githubusercontent.com/3509811/70804151-0f874c80-1db6-11ea-8d2c-1e2ed0df74f7.gif)

Or this:

![record_191213_142556](https://user-images.githubusercontent.com/3509811/70804294-6856e500-1db6-11ea-90aa-83b3f6cefd65.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.2
- Operating System: Ubuntu 18.04.3 LTS
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version:  8.11.3 - x64
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: App, version 2.17.1
- Operating System: Windows 10 Pro

**Comment by Amagon96** [comment]
Hi! Can I work on this?

**Comment by macrozone** [comment]
this was not the case in previous versions. This regression has been introduced recently

@Amagon96 would be great if someone could fix this!

**Comment by macrozone** [comment]
no, bad stale bot!

**Comment by macrozone** [comment]
its still the case, stalebot, shoo shoo!
