### ISSUE TITLE
The fields in the email are not changing from english when changed language

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#15976]
### Description:
The description boxes, as well as the title boxes, don't change from English when language is changed to any other, even though the translations exist

### Steps to reproduce:

1. Being an administrator change language to any other
2. Go to the email settings
3. The description boxes and title boxes don't change

### Expected behavior:
They should change

### Actual behavior:

![image](https://user-images.githubusercontent.com/43509699/70812773-4416fa80-1dee-11ea-8e9b-321f3d586414.png)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context
I am working on this

**Comment by MartinSchoeler** [comment]
Could you please tell us the version this error is happening, thanks!

**Comment by ritwizsinha** [comment]
@MartinSchoeler I am building the application from source, so I guess it is the 2.3.2 version

**Comment by MartinSchoeler** [comment]
@ritwizsinha  I see, probably this string has not been translated to that language yet, you can probably fix this by finding the string key and adding it to the language i18n file

**Comment by ritwizsinha** [comment]
![image](https://user-images.githubusercontent.com/43509699/70844204-d4dbed80-1e63-11ea-8e78-c7372ef6b258.png)
@MartinSchoeler  I have been unable to use the string key in the short HTML snippet in this.add( ) function. I have done it the normal way variables are inserted in HTML, but it's giving an error

**Comment by sampaiodiego** [comment]
I didn't get exactly what is expected to change/translate.. can you give an example pls? if you're talking about the string `{Your_email_address_has_changed}`, it will not show translated on the value of the input, it will be translated during the email sending process to the language of the user that will receive the given email. does it makes sense?
