### ISSUE TITLE
snap install failed on ubuntu18.04/plesk, caddy failed to start

### ISSUE THREAD

**Issue by bixmatech** [RocketChat/Rocket.Chat#15983]
Dear,
snap install failed on ubuntu18.04/plesk, caddy failed to start, any idea?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
