### ISSUE TITLE
Typo in bug report issue creation template

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#15984]
### Steps to reproduce:

1. See this issue template

### Additional context
I want to correct the bug issue template typo.

**Comment by aKn1ghtOut** [comment]
"Behavior" is American English, while "Behaviour" is British English.
Might be intended to be the way it is.

**Comment by MartinSchoeler** [comment]
As @aKn1ghtOut said, this is intended. Thanks!
