### ISSUE TITLE
Add "more" to show a window of more emojis

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1599]
Add a "more..." link at the bottom of the basic emoji list that opens up a tabbed window with all available emojies, similar to how Discourse does it:

![cqmh7lpuaaefk-a](https://cloud.githubusercontent.com/assets/432460/11664265/b7152dbe-9dae-11e5-9dcd-43aca5662b91.png)

**Comment by wtsarchive** [comment]
Isn't this a duplicate of #480?

**Comment by sampaiodiego** [comment]
yes =\
I'll copy @fduraibi suggestion to that #480 
thanks @wtsarchive
