### ISSUE TITLE
AD password changes do not replicate to Rocket.Chat

### ISSUE THREAD

**Issue by pramsky** [RocketChat/Rocket.Chat#15990]
### Description:

When using LDAP authentication against an Active Directory Server, changing the AD password does not sync to Rocket.Chat.

### Steps to reproduce:

1. Login as an AD user. This should work
2. Log out
3. Change your AD password.
4. Attempt to login with new password, this will fail.
5. Login with old password, this will work.

### Expected behavior:

Login with new password should work.

### Actual behavior:

Login with old password works, but new password does not.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.1
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 4.0.8

### Client Setup Information

- Desktop App or Browser Version: 2.16.2
- Operating System: Mac OSX 

### Additional context

This causes issues when desktop users are required to change their password within reasonable intervals.

**Comment by spanchy** [comment]
Hello, check please option "Login_LDAP_Fallback". Set False for this and try. I think a problem with ad login sync settings.
