### ISSUE TITLE
PUSH notifications in Away status

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#15995]
**Rocket.Chat Version 2.3.1
Rocket.Chat Electron Version 2.16.0
Rocket.Chat ReactNative Version 4.1.0.2095**
User has Rocket.Chat installed on his desktop and smartphone.
Now PUSH notifications are sent to smartphone only when desktop application is totally off.
It is not so conveniently, because if user out of computer (in a meeting, or just out of office) and his desktop application is launched - he will never know is someone wrote him a message unless it open Rocket.Chat ReactNative.
In my opinion, the solution to this problem could be sending a PUSH notification if the desktop client status is **Away**.
**Away** means user not near his desktop and good idea to send him PUSH notification to his smartphone.
PS. I saw [this](https://rocket.chat/2019/09/27/push-notification/) article.

**Comment by rodrigok** [comment]
@ankar84 I wasn't able to reproduce the issue.

I've tested at open.rocket.chat and received all the messages via push as soon my user on the desktop app goes to the away status (yellow).

I'll close this issue. Please check your settings and be sure you have a low time to enter in the away status defined and you didn't disabled the auto away.

**Comment by ankar84** [comment]
> @ankar84 I wasn't able to reproduce the issue.

@rodrigok I agree with you. I downgraded to **RC.Electron version 2.15.5** and **all works fine** - after away timeout my user went to **Away** status, and when I send a message to my user from test user - **I got push notification**! So, I think it is not RC bug, but **only RC.Electron grater then 2.15.5 version bug**.
