### ISSUE TITLE
Chat window "jumps" down when messages arrive

### ISSUE THREAD

**Issue by joepie91** [RocketChat/Rocket.Chat#160]
When a new message arrives in the channel, the entire channel view jumps back down. This is rather annoying when trying to read chat history.

A solution would probably be to only make it 'stick' to the bottom if the page is scrolled down entirely.

**Comment by joepie91** [comment]
Was this fixed? I didn't see a commit reference.

**Comment by rodrigok** [comment]
We can't reproduce anymore, was fixed in some moment in the past :)

If you can reproduce, please reopen this issue.
