### ISSUE TITLE
Custom OAuth is not deleted

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat#16008]
-> Operating System / Version / Architecture (64 bit?)

Linux x64 (Ubuntu)

-> Browser type and version, including any add-ons. (e.g. AdBlocker, NoScript, etc.)

Chrome Version 70.0.3538.77 / Firefox 61.0.1

-> Rocket.Chat version

2.1.2

-> Expected behavior

Custom Oauth to de beleted

-> Actual behavior

Custom Oauth should be removed after clicking on "Remove custom oauth" button

-> Can the bug consistently be reproduced? If so, how?

Yes, I could test in my test trial. 

Step to reproduce:

1. Create a custom OAuth
2. Try to remove it 

-> Relevant errors and other log output

No event is triggered after clicking Yes in the "Are you sure" Popup

![custom_oauth_2](https://user-images.githubusercontent.com/11891939/71033759-b93c4580-20f6-11ea-9cd6-eabe6dd932ac.png)

**Comment by rodrigok** [comment]
@rsjr I can’t reproduce this error in the latest version, can you?

**Comment by rsjr** [comment]
@rodrigok Indeed in the latest version it is not happening. Thanks for the heads-up.

**Comment by tassoevan** [comment]
Fixed by #15934.
