### ISSUE TITLE
Missing/delayed messages

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#16007]
### Description:

We have had a few reports from our employees, where they have looked at a channel, and didn't see any updated messages. Then, a couple of hours later, they looked at the channel again, and see content that should have shown up the previous time they looked at it, but didn't. In other words, it seems like some messages are arriving late.  Furthermore, one user reports that they recall once where they actually posted and their own post later showed up in the middle of a different discussion.   So far this is being reported in the Firefox web browser client.  Not sure if this is a RC server or client issue.

### Steps to reproduce:

This is really difficult to reproduce.  It isn't happening all of the time.

### Expected behavior:

Messages should show up immediately.

### Actual behavior:

Messages sometimes show up late.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Firefox 71.0
- Operating System: Fedora 31

### Relevant logs:

Not sure what logs to supply here.  But I can supply logs if needed.

**Comment by rodrigok** [comment]
@mddvul22 are you seeing any error in your logs?
Can you define better this delay? Are we talking about seconds, some minutes or hours?
Can you check if your web clientes have a valid websocket connection or if they are relaying on the fallback pooling?

**Comment by mddvul22** [comment]
Hours.  A few times, even a day or more.  Web socket connections are valid.
