### ISSUE TITLE
Profile setting security menu not disappearing 

### ISSUE THREAD

**Issue by multimill** [RocketChat/Rocket.Chat#16003]
Hello,

we have configured our Rocket.Chat instance for our company and disabled all features like changing password because we use LDAP. 

We would like to hide the security menu as its completly empty and might irritate some users. Is there any way to remove it? 

![17-12-_2019_17-08-44](https://user-images.githubusercontent.com/24725624/71012803-f3eeaf80-20ef-11ea-990a-095c25d132b7.png)

We do use the newest version 2.3.2. We would like to remove the "security" and only have the preferences there.

**Comment by MartinSchoeler** [comment]
@multimill  This seems like a bug to me, can you tell us what settings you have deactivated exactly? Thanks!

**Comment by multimill** [comment]
@MartinSchoeler Thanks for the fast reply. I did take a look at a fresh install and this tab seems to have only one purpose: setting up the 2 factor authentication as seen in this screenshot:

![1](https://user-images.githubusercontent.com/24725624/71032410-99684a00-2115-11ea-9396-7151b8f4ac44.PNG)

We would like to remove the "security" panel and have it look like in the following screenshot. It seems to be a bug when disabling 2 factor authentication in the admin panel. Its found at Accounts >> Two Factor Authentication.

![2](https://user-images.githubusercontent.com/24725624/71032412-99684a00-2115-11ea-87ad-5daedaa95cbf.PNG)

Do you need any more information?
