### ISSUE TITLE
File Upload Stock 0%

### ISSUE THREAD

**Issue by McpCyber** [RocketChat/Rocket.Chat#16000]
Hi there
i deployed Rocketchat ver 2.3.0 with MongoDB 4.2 Replicaset,
Rocketchat install on 2 VM and Number of Instances is 10
Deployment is Clean and i want to use MinIO on Kubernetes  for S3 File Uploads.
at this time file upload settings set to GridFS , But i can't upload any file .
erreoe code is :
 Error: FileNotFound: no file with id 2KAYQa2DwEhtkCqyC found
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/gridfs-stream/index.js:188:25
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at result (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:414:17)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at session.endSession (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:401:11)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at ClientSession.endSession (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sessions.js:129:41)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at executeCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:397:17)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at deleteCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:349:17)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at removeDocuments (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:364:54)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at handleCallback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:128:55)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at coll.s.topology.remove (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/collection_ops.js:1208:5)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at handler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:1197:22)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:532:18
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
Dec 17 14:09:55 sv252003001 RocketChat[5312]:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

How can fix this problem?
Thanx alot

**Comment by himpierre** [comment]
Yeah had that too. The upload succeeded after a very long time (1-2min). That's why we switched to s3. It's working there.

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since GitHub is not the best place to ask for support. For now, I will be closing this issue, as it does not fit our issue guidelines

**Comment by McpCyber** [comment]
Hey the Problem has been fixed.
in General Settings , URL must not be localhost
