### ISSUE TITLE
Start audio and video buttons without functionality

### ISSUE THREAD

**Issue by rsimai** [RocketChat/Rocket.Chat#16015]
### Description:

"Start audio call" and "Start video call" buttons appear when looking at the user info in a direct chat. They don't appear when looking at the user info from a channel.

### Steps to reproduce:

0. disable BigBlueButton and Jitsi under Admin/Video Conference
1. go into a direct chat with another user
2. click "user info" (top right)
3. see the non working buttons, compare to the screenshot

### Expected behavior:

There should be no audio and video call buttons, unless the service is configured.

Buttons appear in this view nonetheless.

- Version of Rocket.Chat Server: 2.2.0
- Operating System: SUSE Linux
- Deployment Method: k8s
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.11

### Client Setup Information

Can be duplicated in any browser.

### Additional context

There's no error or crash, but it's causing confusion for the users and creates unnecessary helpdesk work.

### Relevant logs:

Please advise, if required.

**Comment by rsimai** [comment]
![Screenshot_20191218_153748](https://user-images.githubusercontent.com/6737491/71096041-eac41800-21ad-11ea-871b-753010b3a1e8.png)

**Comment by RhnSaxena** [comment]
I will have a go at this.

**Comment by MartinSchoeler** [comment]
On firefox I also get these errors in the console
![image](https://user-images.githubusercontent.com/20868078/71264038-f89aaa00-2321-11ea-811e-6058cfc5f4af.png)

@rsimai Can you check your browser console for errors as well?  Thanks!

**Comment by rsimai** [comment]
I can't confirm this, sorry. There are no messages in my console (Firefox and Chrome) after I allow camera usage. My UC camera becomes active, I see myself, the other person gets a notification and can also activate their camera. It wouldn't work that callers can see each other which is as expected, as the services are not configured.

**Comment by cs-1** [comment]
The problem seems to be the fact that BBB is included as an iFrame. If you right-click the iFrame and open it in a new tab it will properly ask you for permissions for your camera etc. and after you granted those it'll work in the iFrame as well. Of course this is not a way to solve this problem in production deployments

**Comment by einhirn** [comment]
I'd rather guess that these Buttons are for RocketChat's own WebRTC-Implementation and have nothing to do with either Jitsi or BBB. See if there's something enabled under https://your-chat-server-here/admin/WebRTC
Our Chat server has all of the switches turned off and there aren't any of these Icons, with or without BBB enabled. BBB has it's own button in the dots menu.

**Comment by danger89** [comment]
Duplicate of: https://github.com/RocketChat/Rocket.Chat/issues/8256

**Comment by danger89** [comment]
> 
> 
> ![Screenshot_20191218_153748](https://user-images.githubusercontent.com/6737491/71096041-eac41800-21ad-11ea-871b-753010b3a1e8.png)

This is only one-on-one calls, what about channel or private groups?

**Comment by sknorr** [comment]
This is still an issue in newer versions of Rocket.chat (currently using RC 3.5). Could you please reopen?
