### ISSUE TITLE
Killedlding for web.browser on Ubuntu 14.04 clean install

### ISSUE THREAD

**Issue by BackIsBachus** [RocketChat/Rocket.Chat#1601]
Hello,

I tried this [installation tuto for Ubuntu 14.04](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker) on a fresh Ubuntu 14.04 VM and when I run :
```
meteor build --server "$HOST" --directory .
```
I get the following output :

```
rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...
rocketchat:assets: updating npm dependencies -- image-size...
rocketchat:ldap: updating npm dependencies -- ldapjs...
rocketchat:theme: updating npm dependencies -- less, less-plugin-autoprefix...
rocketchat:tutum: updating npm dependencies -- redis...
rocketchat:ui-sidenav: updating npm dependencies -- less, less-plugin-autoprefix...
steffo:meteor-accounts-saml: updating npm dependencies -- xml2js, xml-crypto, xmldom, connect, xmlbuilder,
querystring, xml-encryption...
Currently, it is only possible to build iOS apps on an OS X system.

WARNING: The output directory is under your source tree.

Killedlding for web.browser
```
I previously had to install fiber globally (as suggested on [#1340](https://github.com/RocketChat/Rocket.Chat/issues/1340)) to be able to get the command to run this far.

Any pointers ?

**Comment by engelgabriel** [comment]
Did you see this issues?
https://github.com/RocketChat/Rocket.Chat/issues/1348 
https://github.com/RocketChat/Rocket.Chat/issues/1350

**Comment by BackIsBachus** [comment]
I saw them but I couldn't reproduce the problem I had yesterday because now I have:
```
=> Errors while initializing project:

While building package steffo:meteor-accounts-saml:
error: couldn't install npm packages from npm-shrinkwrap: Command failed: npm WARN package.json
packages-for-meteor-steffo-meteor-accounts-saml@0.0.0 No description
npm WARN package.json packages-for-meteor-steffo-meteor-accounts-saml@0.0.0 No repository field.
npm WARN package.json packages-for-meteor-steffo-meteor-accounts-saml@0.0.0 No README data
npm WARN package.json packages-for-meteor-steffo-meteor-accounts-saml@0.0.0 No description
npm WARN package.json packages-for-meteor-steffo-meteor-accounts-saml@0.0.0 No repository field.
npm WARN package.json packages-for-meteor-steffo-meteor-accounts-saml@0.0.0 No README data
```
I manually installed
```
 steffo:meteor-accounts-saml
```
But it didn't work out when I tried to rebuild.

I'm trying to bring myself up to date with Meteor and npm to try and understand these errors but I'm really new a this for now ^^ (so my questions may seem really noobish ^^)

Note that except on some cases for a new installation I delete the failed build and extract again the archive.

**Comment by engelgabriel** [comment]
Can you do?

```
# node -v
v0.10.40
# npm -v
1.4.28
```

**Comment by BackIsBachus** [comment]
Ok looks like I need to redo the step when I tell node to be at v0.10.40 because it got reset:
```
# npm -v
3.3.6
# node -v
v5.0.0
```
I re-ran
```
# nave usemain 0.10
# npm -v
1.4.29
# node -v
v0.10.41
```
And now I'm back to my initial problem, I'm am going to ask at [#1348](https://github.com/RocketChat/Rocket.Chat/issues/1348) how he solved this particular issue.

**Comment by engelgabriel** [comment]
@BackIsBachus please reopen if this is still an issue with the latest version.

**Comment by d4nyll** [comment]
This happens when your server does not have enough memory to run the application. Add some swap memory or upgrade your server.

**Comment by stefanocudini** [comment]
really? :o how can I check if the problem is caused by the lack of ram?

**Comment by d4nyll** [comment]
@stefanocudini check how much memory your machine is using. What is the output of `free -m` on the machine you are running RocketChat on?

**Comment by stefanocudini** [comment]
my server has only 2GB total, and free some mbytes.. I solved the problem and it run!
but the problem is that I do not know how much RAM my meteor application needs
There is a way to calculate it before?

**Comment by reetp** [comment]
@stefanocudini Please don't continue on with Closed bugs unless you have the specific issue reported, and it is actually a bug.

Support queries should be opened in the forums https://forums.rocket.chat/ or chat https://open.rocket.chat/channel/support

Thank you.
