### ISSUE TITLE
There is no description of fields for administrator settings

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#16019]
### Description:

After the update administration UI the description of the fields in admin settings is not displayed

### Steps to reproduce:

1. Go to administration
2. Open settings page

### Expected behavior:
For example (2.2.0)
![image](https://user-images.githubusercontent.com/19654261/71166874-65a43600-2275-11ea-97da-e3a354d95a7a.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/19654261/71166893-7359bb80-2275-11ea-90f5-e6d17b909737.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.0

**Comment by rodrigok** [comment]
Thanks @antkaz. That's a known issue internally, we are already working to solve.
