### ISSUE TITLE
JWT Token for Jitsi not generated from mobile Android and iOS app

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#16028]
Hi,
I've enabled JWT Token authentication on Jitsi and properly configured with RocketChat (appid, secret). It works fine on the browser web app and desktop app, but on mobile apps  seems that the token is not generated, and when the user joins the video call Jitsi reverts to basic authentication, which happen when the user doesn't have a token.

### Steps to reproduce:

Having setup Rocketchat and Jitsi for JWT authentication, simply try starting a video call to a user or a channel from the mobile app

### Expected behavior:

Users coming from RocketChat have their token and can join the Jitsi videocall without being prompted for authentication

### Actual behavior:

Jitsi basic authentication prompts appear and prevents user from accessing the Jitsi videocall

### Server Setup Information:

- Version of Rocket.Chat Server:  2.1.3
- Operating System:  18.04.3 LTS
- Deployment Method:  tar
- Number of Running Instances:  
- NodeJS Version:  8.16.2
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: 
4.1.0.2095 for Android
4.1.0.268 for iPhone
- Operating System: Android and iPhone

**Comment by ankar84** [comment]
I think related https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1356
