### ISSUE TITLE
[BUG] Reply in Thread button hovers the text

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#16029]
### Description:

Reply in Thread button in the threads panel could hover the text.

### Steps to reproduce:

1. Go to the thread replies panel
2. Find a thread reply that is one line long.
3. Hover a mouse over that line

### Expected behavior:

Reply in thread button should not hover the text (same way like emoji and three dots menu buttons don't).

### Actual behavior:

![image](https://user-images.githubusercontent.com/11751017/71245384-da7a7d00-2314-11ea-8969-48241cc6090b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v8.16.2
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: web version
- Operating System: -

### Additional context

Related to #15685

**Comment by zdumitru** [comment]
@ggazzo On that note, probably `Reply in Thread` button shouldn't be visible on the thread replies at all.

**Comment by antkaz** [comment]
Oh... In the main chat the same problem.
![image](https://user-images.githubusercontent.com/19654261/71247903-820aa600-233b-11ea-836d-6f12809af8d1.png)

Maybe do something like that? And hide this button in threads

![image](https://user-images.githubusercontent.com/19654261/71248144-ffceb180-233b-11ea-9d07-1d410fea1ea2.png)

**Comment by ritwizsinha** [comment]
Working on this

**Comment by ritwizsinha** [comment]
I would like to start working on this

**Comment by ritwizsinha** [comment]
If the problem is in the main chat also then either we could limit the range of the message or hide the options altogether. 
We can also set up an opacity so that the messages are not hidden under the optiions.
For example if the text overlaps with the options we can set the options opacity to zero and only set it one if it is hovered.

**Comment by aviral243** [comment]
@MartinSchoeler  Can we have the buttons placement as shown below?

![oie_CW46GFKprcaS](https://user-images.githubusercontent.com/44023445/72278048-2b9e3800-3659-11ea-899c-e20984b4a71f.png)

**Comment by zdumitru** [comment]
Related to #16083

**Comment by abhishuraina** [comment]
![Screenshot from 2020-02-04 14-29-50](https://user-images.githubusercontent.com/45932588/73729564-4a28b800-475b-11ea-8c11-1c5f49fb826b.png)
Does this solve the issue? or any further changes ?
@ggazzo

**Comment by abhishuraina** [comment]
![Screenshot from 2020-02-04 15-33-41](https://user-images.githubusercontent.com/45932588/73734585-de971880-4763-11ea-9f5d-d0d5f19073b9.png)
Changes reflected in the replies section too.

**Comment by ritwizsinha** [comment]
> If the problem is in the main chat also then either we could limit the range of the message or hide the options altogether.
> We can also set up an opacity so that the messages are not hidden under the optiions.
> For example if the text overlaps with the options we can set the options opacity to zero and only set it one if it is hovered.

@gabriellsh can this be done

**Comment by engelgabriel** [comment]
We need to move them up a bit, and add a border and background like other chat apps.

![image](https://user-images.githubusercontent.com/1000217/81510014-35713880-92e5-11ea-84fc-5e1a892cf52a.png)
![image](https://user-images.githubusercontent.com/1000217/81510032-4ae66280-92e5-11ea-9d5f-c6bd8c645ef4.png)

**Comment by zdumitru** [comment]
![image](https://user-images.githubusercontent.com/11751017/85384554-8bbad380-b541-11ea-9c51-fdc78e3b6007.png)
Still the case.

**Comment by ggazzo** [comment]
fixed :)
