### ISSUE TITLE
Node.js 8: EOL on 2019-12-31

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat#16024]
### Description:

Hi folks, Hi @sampaiodiego,

as of 2019-12-31, `Node.js 8` will [be end of life](https://nodejs.org/en/about/releases/). This means no security releases anymore. Hence, from now on, every Rocket.Chat instance will be in potential danger as nobody will search, find and fix security issues `Node.js 8`.

### Additional context

It might make sense to first upgrade to `v12` which will be supported until 2022-04-30, and then - from 2020-04-21 on - plan the switch to `v14`, which will be supported until 2023-04-30.

Maybe the maintenance period for `v12` even overlaps the release of `v16` so one could skip `v14`. But I guess most of that will be determined by the Meteor Node.js support anyway.

Cheers & greetings to everybody in the office
Thomas

**Comment by sampaiodiego** [comment]
we are looking close to https://github.com/meteor/meteor/pull/10527 which will upgrade Node to v12.. 

it is already on `rc.0` so I assume it will be launched in next months.. we'll try to update as soon it is launched :+1:

**Comment by antkaz** [comment]
Meteor 1.9 released https://github.com/meteor/meteor/blob/devel/History.md#v19-2020-01-09

**Comment by TwizzyDizzy** [comment]
Seems like [3.0.0-rc0](Upgrade to Meteor 1.9 and NodeJS 12 ) incorporates the upgrade to nodejs 12 :)

Cheers
Thomas

**Comment by sampaiodiego** [comment]
yes, thanks for the reminder @TwizzyDizzy .. I'll close this =)
