### ISSUE TITLE
forward message in rocket.chat webhook script?

### ISSUE THREAD

**Issue by Khodesaeed** [RocketChat/Rocket.Chat#16038]
i want to check some fields on incoming webhooks and if its true forward message to a list of user in rocket.chat. can you suggest any solution for this scenario?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
