### ISSUE TITLE
Docker Deployment Update

### ISSUE THREAD

**Issue by ephemeraleclipse** [RocketChat/Rocket.Chat#1603]
Hi all, I just updated my docker deployment of rocketchat... which I thought, since it uses a separate Mongo container, I should just delete the rocketchat container and redeploy with new image while keeping my data.. However it turned out to not be the case.. I lost all the accounts and settings
I was just wondering what is the expected way to update the rocketchat docker deployment?

I'm using the official image from Docker Hub

**Comment by sampaiodiego** [comment]
that's exactly what you have to do.
I think what happened was a change in mongodb database name on dockerfile: https://github.com/RocketChat/Rocket.Chat/commit/d4839952f8067e0301e1efe12c5b95a9742d6e80
probaly if you connect to your mongodb container you'll see two databases (`show dbs`): _meteor_ (the old one with your whole data) and _rocketchat_ (the new one).

to recover your data you should do (**warning**: you'll lose all your new data):

* stop rocketchat container
* connect to your mongo with mongoshell and execute this commands:
  * `use rocketchat`
  * `db.dropDatabase();`
  * `db.copyDatabase('meteor', 'rocketchat');`

now you can start rocketchat container again and see if the data has been restored, if so you can drop the old database:

* connect to your mongo with mongoshell and execute this commands:
  * `use meteor`
  * `db.dropDatabase();`

We're sorry for that. Let me know if you need anything else.

**Comment by ephemeraleclipse** [comment]
I see, thank you very much

It would be nice if these kind of breaking changes were documented somewhere :/

**Comment by engelgabriel** [comment]
@ephemeraleclipse I am really sorry for that.

You are right. The only reason we did that change is that we thought that all production deployments would be overwriting the mongodb url with their own server settings.
