### ISSUE TITLE
[BUG] Replying breaks screen max width in smaller screens

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#16034]
### Steps to reproduce:

1. Write a Huge message
3. Reply the huge message

### Expected behavior:

It should not break the screen

### Actual behavior:

![image](https://user-images.githubusercontent.com/20868078/71262364-444b5480-231e-11ea-96ee-e817e0127d6d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: Tested on open server

**Comment by ritwizsinha** [comment]
Working on it
@MartinSchoeler  could you guide me to the relevant files ?

**Comment by ritwizsinha** [comment]
Found the files , fixed it by using word-break css property
@MartinSchoeler review plz
