### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Vova-cpu** [RocketChat/Rocket.Chat#16031]
### Description:
After updating to version 2.3.1, it became impossible to change the user password, how to fix it?

![image](https://user-images.githubusercontent.com/59089028/71257135-98186680-233b-11ea-8c6a-bcc80af33b39.png)

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by MuuNU** [comment]
Similar problem. Fix it please

**Comment by zdumitru** [comment]
Readh this - #15880

**Comment by MartinSchoeler** [comment]
Please refer to https://github.com/RocketChat/Rocket.Chat/issues/15880 Thanks!
