### ISSUE TITLE
User avatar not showing in private messages

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16045]
### Description:

If I get a private message for a wrong command the avatar doesn't load

### Steps to reproduce:

1. Type // in the message box(or any slash command that doesn't exist)
2. View the rendered message "No such command"
3. The avatar is missing

### Expected behavior:

The avatar image should load correctly

### Actual behavior:

![Selection_004](https://user-images.githubusercontent.com/43509699/71342146-f040aa00-2581-11ea-9107-06893c668c21.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0-develop
- Operating System: ubuntu
- Deployment Method:meteor

**Comment by aviral243** [comment]
Should we remove the avatar all over or debug it to show the profile image?

**Comment by ritwizsinha** [comment]
I'm already working over it , will try to show the rocketchat bot avatar

**Comment by ashwaniYDV** [comment]
I think this is the issue with undefined InternalHubot_Username
