### ISSUE TITLE
The increase/decrease counter in livechat office hours is misplaced

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16040]
### Description:

The counter is pushed above from its normal position

### Steps to reproduce:

1. Enable Livechat as administrator
2. Click on Livechat settings as administrator
3. Go to office hours

### Expected behavior:

The counter should be properly placed

### Actual behavior:
![image](https://user-images.githubusercontent.com/43509699/71317136-56560000-24a2-11ea-9fa9-2873e7fe53fc.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0-develop
- Operating System: Ubuntu
- Deployment Method: meteor
- Number of Running Instances:  1

### Are you working on this 
Yes

**Comment by mariaeduardacunha** [comment]
Tested in the latest version (2.5.0-develop) and this issue doesn't happen anymore. If you happen to experience this issue again, please reopen this with updated details. Thanks!

**Comment by ritwizsinha** [comment]
ok
