### ISSUE TITLE
PC version don't upload file

### ISSUE THREAD

**Issue by qwclytmd** [RocketChat/Rocket.Chat#16044]
I based “Configuring SSL Reverse Proxy” doc ，prompt 

4c4f931e91f8f7ac9113c06e34fc734b8a61a88d.js?meteor_js_resource=true:187 Mixed Content: The page at 'https://rocket.wildduck.top/channel/general' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://35.220.207.134:3000/ufs/GridFS:Uploads/q5mHzDQ3p2fBxQH9v?token=8aB8D94bF9&progress=1'. This request has been blocked; the content must be served over HTTPS.

How do I fix it.

**Comment by Lawri-van-Buel** [comment]
Did you follow the instructions on [Ssl-reverse-proxy](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/)  to the letter?

Specifically the note regarding the url?

It seems that your rocketchat thinks it’s not using https but plain http. 

If you did could you add your vhost snippet as to check if that’s correct? (You should sanitize it first though, to not leak secrets)

**Comment by qwclytmd** [comment]
this is my vhost of nginx.conf：
`server
{

    listen         443 ssl;
    server_name    rocket.wildduck.top;

    client_max_body_size 200M;

    ssl on;
    ssl_certificate      /usr/local/nginx/cert/wildduck.top/rocket.crt;
    ssl_certificate_key  /usr/local/nginx/cert/wildduck.top/rocket.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_pass http://35.220.207.134:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}
`
If I use the IP address (http://35.220.207.134:3000/), I can upload the file normally.

**Comment by sampaiodiego** [comment]
@qwclytmd please always fill in the bug report template when opening an issue (if it is a bug report :stuck_out_tongue: ).

looks like the your `Site_Url` setting (you find on Admin > General > Site URL) is wrong.. it should point to the external HTTPS address (in your case `rocket.wildduck.top`) and not to the internal IP.

**Comment by qwclytmd** [comment]
Think You,I am Fix it from you step.
