### ISSUE TITLE
Password is updated even if the password and confirm password are not equal

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16057]
### Description:

A user can update the password from Update Profile section even if the password and confirm password fields are not equal. It takes the newly updated password as the input password field ignoring the value of input confirm-password field.

### Gif for the issue:
![11](https://user-images.githubusercontent.com/43786728/71480707-94e01780-2820-11ea-887e-596bab7cddc3.gif)

### Steps to reproduce:

1. Go to My accounts.
2. Click on Profile 
3. Enter different values of password and confirm password.
4. Click "Save Changes" button.
5. Enter current password.
6. Click Save.
7. Boom. You get password updated toast message and your password is updated.

### Expected behavior:
It should not be able to update profile if password and confirm mismatch occur.

### Actual behavior:
It's updating the password even if the password and confirm password fields are not equal.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0-develop
- Operating System: ubuntu
- Deployment Method: meteor
- NodeJS Version: 8.16.2 - x64
- MongoDB Version: 4.0.6

### Additional context
I am working on it.

**Comment by yashrajbothra** [comment]
Hey @sampaiodiego  ,Can i work on this issue?

**Comment by ashwaniYDV** [comment]
@yashrajbothra I have already made the pull request.

**Comment by yashrajbothra** [comment]
Okay @ashwaniYDV  Thanks, I will keep that in mind.

**Comment by ashwaniYDV** [comment]
@sampaiodiego I have made the pull request for this issue.
https://github.com/RocketChat/Rocket.Chat/pull/16060

**Comment by ashwaniYDV** [comment]
@gabriellsh Hello sir. I have already made the pull request. Would you please review this.
