### ISSUE TITLE
Quotation in chat does not have a "continous" left border

### ISSUE THREAD

**Issue by haakonnessjoen** [RocketChat/Rocket.Chat#1605]
![image](https://cloud.githubusercontent.com/assets/416667/11683494/71c92734-9e6b-11e5-9b82-d08b3bb18fcf.png)
Using the quotation markup `> `, the border is not completely continous. As opposed to information from hubot:
![image](https://cloud.githubusercontent.com/assets/416667/11683511/912bb222-9e6b-11e5-9b94-c3c01d03b812.png)

**Comment by sampaiodiego** [comment]
this thing was annoing me for a while =P
