### ISSUE TITLE
Https only in Heroku?

### ISSUE THREAD

**Issue by ywecur** [RocketChat/Rocket.Chat#1606]
Is there a way to make rocket.chat only accept https when deployed to Heroku?

**Comment by engelgabriel** [comment]
You could add the package https://atmospherejs.com/meteor/force-ssl

**Comment by ywecur** [comment]
Thanks, so how do you do that in Heroku?

**Comment by engelgabriel** [comment]
You'd have to fork the project, add the package and deploy to heroku from your own fork.

In the future we could ask Meteor to change the package so it can be turned on/off via settings, so the package could be added by default.
