### ISSUE TITLE
Pinned message are not removed from Pinned message section when unpinned

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16061]
### Description:

When a pinned-message is unpinned it is not removed from the pinned message section.

### Steps to reproduce:

1. Open any chanel or direct-message
2. Pin a message
3. Click on "more" button dropdown
4. Click "Pinned Messages"
5. Unpin the pinned message

# Expected behavior:
The pinned message should get removed from the pinned-messages-section

# Actual behavior:
### Case 1 (When messages are pinned first and then pin message section is opened [pinning unpinning is done then])
![pin1](https://user-images.githubusercontent.com/43786728/71542841-7188aa00-2991-11ea-8dd2-755c8e699c8b.gif)

### Case2 (When pinned message section is opened first and then messages are pinned and unpinned)
![pin2](https://user-images.githubusercontent.com/43786728/71542846-7f3e2f80-2991-11ea-8190-81ab3919ff38.gif)

**Comment by manosriram** [comment]
Are you still working on this? Because it looks interesting and I would like to get into it. @ashwaniYDV

**Comment by ashwaniYDV** [comment]
@manosriram I am working on it.

**Comment by gabriellsh** [comment]
Hey @manosriram feel free to do it, this is open source, everyone can contribute, no need to ask or to say you're doing it. Thank for your help!
