### ISSUE TITLE
Translation function does not work when pressing the "Translate" the first time

### ISSUE THREAD

**Issue by lequy1010** [RocketChat/Rocket.Chat#16075]
Translation function does not work when pressing the "Translate" the first time. 
Since the 2nd time it's Ok.

**Comment by lequy1010** [comment]
19 days ago, please confirm @jwilkins

**Comment by mariaeduardacunha** [comment]
Not enough information provided. Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
