### ISSUE TITLE
Settings are being showed duplicated

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#16079]
### Description:

Settings are showing duplicated.

### Steps to reproduce:

Not sure exactly how to reproduce, but I've done this:

1. Go to Admin
2. Navigate into multiples sub menus
3. Scroll down open some sections

### Expected behavior:

Shows only one field per section.

### Actual behavior:

Sometimes the settings are showed duplicated:

![image](https://user-images.githubusercontent.com/8591547/71483689-ba046400-27e7-11ea-8594-ee93f4a77c32.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: yes

### Client Setup Information

- Desktop App or Browser Version: Chrome 79
- Operating System: Ubuntu

**Comment by subham103** [comment]
while reproducing this issue I didn't come across duplicate settings. I think this might be solved in some pr or I am not in the correct version to reproduce it.
![Rocket Chat](https://user-images.githubusercontent.com/43502196/74265611-dcffbe80-4d28-11ea-91e5-7df57d730536.png)

please tell us whether this issue still persists

**Comment by subham103** [comment]
@sampaiodiego Is there any other way to reproduce this issue because, in my case, there is no duplication of settings??

**Comment by sampaiodiego** [comment]
I haven't seen it anymore.. maybe @tassoevan or @ggazzo can say if it was fixed already

**Comment by ggazzo** [comment]
Me neither, I can't reproduce anymore...

**Comment by pierre-lehnen-rc** [comment]
You can cause this error by adding a Custom Oauth on the OAuth settings. It duplicates every setting on the screen.
