### ISSUE TITLE
Error in oplog callback : Cannot read property 'isEmitAllowed' of undefined

### ISSUE THREAD

**Issue by robiiinos** [RocketChat/Rocket.Chat#16082]
### Description:

Logs are being spammed by an oplog callback error.

### Steps to reproduce:

1. Could not determine a way to reproduce the issue; most likely happening on timed interval when someone goes on a room to read the messages.

### Expected behavior:

No error in logs.

### Actual behavior:

<img width="1416" alt="rocket chat_logs" src="https://user-images.githubusercontent.com/16455953/71514254-20e45480-289e-11ea-9944-9256d6fcd689.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.2
- Operating System: Linux x64 4.4.0-170-generic
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.16.2
- MongoDB Version: 3.6.16

### Client Setup Information

- Desktop App or Browser Version: Safari 13.0.4
- Operating System: macOS 10.15.2

### Additional context

Docker deployed with ~ 50 users, 7 channels; 350k+ total messages (including direct messages).
Dual core w/ 4Gb ram server.

### Questions

Could be related to #12719 (but way older RC version); with this commit https://github.com/RocketChat/Rocket.Chat/commit/980e29a267328746fd8c73c48edece40246e5377

Should we try to upgrade mongodb to 4.0 ?

### Relevant logs:

```Error in oplog callback TypeError: Cannot read property 'isEmitAllowed' of undefined     at isEmitAllowed (server/stream/rooms/index.js:8:30)     at emitRoomDataEvent (server/stream/rooms/index.js:35:6)     at BaseDb.Rooms.on (server/publications/room/emitter.js:41:2)     at emitOne (events.js:121:20)     at BaseDb.emit (events.js:211:7)     at BaseDb.processOplogRecord (app/models/server/models/_BaseDb.js:207:9)     at packages/mongo/oplog_tailing.js:108:7     at runWithEnvironment (packages/meteor.js:1286:24)     at Object.callback (packages/meteor.js:1299:14)     at packages/ddp-server/crossbar.js:114:36     at Array.forEach (<anonymous>)     at Function._.each._.forEach (packages/underscore.js:139:11)     at DDPServer._Crossbar.fire (packages/ddp-server/crossbar.js:112:7)     at handleDoc (packages/mongo/oplog_tailing.js:320:24)     at packages/mongo/oplog_tailing.js:346:11     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)```

**Comment by Floflobel** [comment]
Same problem with snap install:
Rocket.Chat Version: 2.1.1
MongoDB Version: 3.6.14
Number of Running Instances: 1
Numbers of users: 1
Numbers of channel: 1

**Comment by sampaiodiego** [comment]
I believe this was fixed by #15968 , [here](https://github.com/RocketChat/Rocket.Chat/pull/15968/files#diff-677cfa9c2fa27e3828d48a0d6ccc55f9L31) to be more specific.

looks like the issue was happening when removing livechat rooms, in that case there was no `t` property, causing the error.. 

pls upgrade to latest version and let me know if you still see any issue 😉
