### ISSUE TITLE
[question] Updating Docker HA setup with no downtime?

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#16081]
Hi, I'm quite new to docker and the documentation and related issues/questions couldn't help me with following question.

My (test) setup is created by this guide:
https://rocket.chat/docs/installation/docker-containers/high-availability-install/
3 Mongo Nodes / 3 Rocket.Chat Nodes / HaProxy as Frontend, connecting to an available Rocket.Chat node

The updating guide just saying "pull the new image":
https://rocket.chat/docs/installation/updating/

Do I have to shutdown all running Rocket.Chat nodes or is it possible to updating one after another? I guess there will be database issues for the "older" Rocket.Chat nodes in case I updated to a newer version? If there is a "backwards compatibility" it would be nice to knew!
The proper question would be: Do I need a downtime with this setup when updating Rocket.Chat?

Same thing with the mongo docker replica set. I guess here it is mandatory to stop all nodes before pulling new images?

**Comment by tars21** [comment]
I've just tried it now from 2.3.2 to 2.4.0 in my staging area.
3 containers are running -> shutdown 1 of them and updating to 2.4.0
Accessing all nodes seperately, the Admin -> Info shows me version 2.4.0, although 2.3.2 docker images are running there.

during the "version missmatch" I've had following messages spamming the log
`
rocketchat_1  | server.js:204 StreamBroadcast ➔ Stream.error Stream broadcast from '172.2.1.201:3000' to│2.4.0: Pulling from rocketchat/rocket.chat
 '172.2.1.202:3000' with name stdout does not exist                                                     │844c33c7e6ea: Already exists
rocketchat_1  | server.js:204 StreamBroadcast ➔ Stream.error Stream broadcast from '172.2.1.201:3000' to│dbd99ef5fd64: Pull complete
 '172.2.1.203:3000' with name stdout does not exist                                                     │af3c17477222: Pull complete
rocketchat_1  | server.js:204 StreamBroadcast ➔ Stream.error Stream broadcast from '172.2.1.201:3000' to│46d0c2f56ba9: Pull complete
 '172.2.1.202:3000' with name stdout does not exist  
`
After updating the two other nodes those messages disappear.
In the end it worked and I was able to chat all the time.
Anyway, I guess the recommendation is to shutdown all nodes and updating then?

**Comment by geekgonecrazy** [comment]
When doing docker I typically start an additional instance with the new version and then remove one of the old.  Repeating until fully updated.

The logs about broadcast are normal and will go away.  Basically means the instances notice the old instance become unreachable and takes it a few to realize.

On start up each instance registers a unique id in the db to represent its self.  Those expire after a while if not reachable I believe

**Comment by tars21** [comment]
thank you very much for sharing your procedure!
