### ISSUE TITLE
The true false option can be replaced with a simple checkbox

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16092]
I don't know whether it is intended or serves some purpose but most of the settings which end in 2 results, yes or no, are shown with a checkbox with true and false options. I don't understand why this was done as  a simple checkbox could serve the purpose and would also be better for the UI
![Selection_011](https://user-images.githubusercontent.com/43509699/71538437-01f2ca80-2951-11ea-9f0d-b90d41b4c459.png)

**Comment by MartinSchoeler** [comment]
This was already fixed, the new UI for the admin has toggle buttons 🙂 
![Screen Shot 2020-01-02 at 10 38 23](https://user-images.githubusercontent.com/20868078/71669642-203f3880-2d4c-11ea-9c3e-20fbaaad4050.png)
