### ISSUE TITLE
The messages are not respecting the spaces in between after sending 

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16090]
### Description:
On sending any message if we set multiple spaces before any word, the message renders as having just one space

### Steps to reproduce:

1. Write any message with a different number of spaces 
2. Send the message
3. Observe the message now has only one space between any two words

### Expected behavior:

It should have spaces as described by the user

### Actual behavior:

![Selection_009](https://user-images.githubusercontent.com/43509699/71537809-60b34680-2947-11ea-9c1b-62c09b4f4039.png)

**Comment by manosriram** [comment]
I would like to work on this issue.

**Comment by manosriram** [comment]
I would like to work on this issue.

**Comment by ggazzo** [comment]
it's working as we planned, if you check, github has the same behavior... you can use, `text` or ```text``` if you want spaces being preserved
