### ISSUE TITLE
The UI of "This room is blocked" is not satisfactory.

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16100]
### Description:
The "This room is blocked" heading is not looking good and is also somewhat not seperated from the messages. 

### Steps to reproduce:

1. Go to any room
2. Block that user

### Expected behavior:
It would be nice if some background and border is given to the "This room is blocked" heading so that it is clear to read and seperated from other messages.

### Actual behavior:
Open the image to view the bottom text - "This room is blocked".
![image](https://user-images.githubusercontent.com/43786728/71556309-ec6ac700-2a5c-11ea-8836-f3d4c0dfc21a.png)

**Comment by serviceman** [comment]
If possible, I'd like for it to say if the user blocked the room, or if the room has been blocked by the other user in the private chat or the admin, etc.

**Comment by mariaeduardacunha** [comment]
Any major changes to the design of the UI needs to be approved by our design team. We will raise this issue to our design team, so please be patient. Thanks for the feedback!
