### ISSUE TITLE
Comments on message

### ISSUE THREAD

**Issue by ProdigyMaster** [RocketChat/Rocket.Chat#1610]
Is it possible to do the same in Rocket.Chat?
![image](https://cloud.githubusercontent.com/assets/528501/11692408/98484ece-9e9f-11e5-82c6-de31b72544e1.png)
##

**Comment by jjzhangg** [comment]
+1

**Comment by MartinSchoeler** [comment]
This will be added when threads are developed. I will close this issue for now.
