### ISSUE TITLE
[BUG] Cannot create Outgoing Webhook

### ISSUE THREAD

**Issue by mhaluska** [RocketChat/Rocket.Chat#16109]
### Description:

Cannot create new Outgoing Webhook, giving me message `No integration found by the provided id.` Same problem on another instance.

### Steps to reproduce:

I've currently no Outgoing WebHook.

1. Go to `Administration -> Integrations -> New integration`
2. Click on `Outgoing WebHook`

### Expected behavior:

Open `Outgoing WebHook` configuration (incoming works).

### Actual behavior:

Received error message `No integration found by the provided id.`

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: CentOS 8
- Deployment Method: https://releases.rocket.chat/2.4.0/download
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: 8.17.0
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: App 2.17.2, Firefox 71.0
- Operating System: Windows 10, macOS Catalina 10.15

### Relevant logs:

Actually with debug logging enabled, there are no server side error logs from this action.

**Comment by greenhats2110** [comment]
Hi
I'm also facing same issue.. kindly assist us
Thanks in advance

**Comment by tung93st** [comment]
I'm also facing same issue

**Comment by guydepauw** [comment]
Same

**Comment by nonameexist** [comment]
Same

Rocket.Chat
* Version	2.4.1
* Apps Engine Version	1.11.0
* Running Instances	1
* OpLog	Enabled

Installed from dockerhub

**Comment by mhaluska** [comment]
Outgoing webhook creation is fixed in 2.4.2. Thanks

**Comment by nonameexist** [comment]
> Outgoing webhook creation is fixed in 2.4.2. Thanks

When docker image will be available?

**Comment by mhaluska** [comment]
So, incoming webhook creating works, but...
- when webhook is created and entries filled, cannot be changed (user, alias, ...)
- if you leave webhook configuration, you'll loose script definition (not visible)
