### ISSUE TITLE
[BUG] Can't send messages anymore (2.4.0)

### ISSUE THREAD

**Issue by adrianrobotka** [RocketChat/Rocket.Chat#16102]
### Description:

I updated my docker container to 2.4.0 - now users can't send messages anymore.

Similar issue: #16097

But I can not send messages as an admin (or in any way).

### Environment

I hava an environment like: https://rocket.chat/docs/installation/docker-containers/index.html#6-create-the-docker-composeyml-file--local-directories

I run this script every night:
```
docker pull rocketchat/rocket.chat:latest
docker-compose up -d
```

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: linux
- Deployment Method: docker: rocketchat/rocket.chat:latest
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.17.0 - x64
- MongoDB Version: 3.6.5
- Commit Hash: 097c7c04f7

### Relevant log

```text
rocketchat            | server.js:204 System ➔ error Error sending message: Error: You are not authorized to change message properties
rocketchat            |     at validateUserIdentity (app/lib/server/functions/sendMessage.js:164:9)
rocketchat            |     at sendMessage (app/lib/server/functions/sendMessage.js:174:2)
rocketchat            |     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:86:11)
rocketchat            |     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:67:34)
rocketchat            |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
rocketchat            |     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
rocketchat            |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat            |     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
rocketchat            |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
rocketchat            |     at Promise (packages/ddp-server/livedata_server.js:715:46)
rocketchat            |     at new Promise (<anonymous>)
rocketchat            |     at Session.method (packages/ddp-server/livedata_server.js:689:23)
rocketchat            |     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by alexleosumy** [comment]
Same problem.  Fix it ASAP, please

**Comment by ksuquix** [comment]
Ditto

**Comment by soundstorm** [comment]
@ksuquix that's why a mongodump before an update is mandatory (learned the hard way too)

Duplicate of #16097

**Comment by adrianrobotka** [comment]
Worked wor me (as a temporary solution): https://github.com/RocketChat/Rocket.Chat/issues/16097#issuecomment-569624761
