### ISSUE TITLE
invite url on 2.4.0

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#16105]
### wrong token after proceed invite url: i wonder... what ttl in default of invite-url-token? is setting some how?

![изображение](https://user-images.githubusercontent.com/43804710/71579681-2a2c2600-2b17-11ea-98f3-dc5d4a6f4f31.png)

### Steps to reproduce:

1. generate invite url on pv
2. transfer url to user
3. user must be login and after new user has proceed to url we looking a error

### Expected behavior:

no error appear and user has invited to pv

### Actual behavior:
error of invalid or expired token. but user inveted.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Centos
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: last from docker
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: 2.4.0 Web
- Operating System: windows, linux,

after press to rocket-logo we enter on buddy list... but than user logout it proceed to create account windows, in my configuration create users is disabled.

**Comment by serviceman** [comment]
Not sure if I should start a new ticket for this or not. Invite url duplicates the directory when running in sub directory mode. 

https://domain.com/subdirectory/subdirectory/invite/SSBmcX

**Comment by pierre-lehnen-rc** [comment]
The invite expiration date is displayed under the generated URL when you click on the invite button.

**Comment by Shaverdoff** [comment]
But why error appear? 

--
Gerasim Shaverdov | Deputy CTO | Altarix 
Mobile: +7 937 070 66 84 | Skype/email: gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by cjhille** [comment]
I'm having the same issue here. Expire date is set to "never". Using latest Docker Image and nextcloud for OAUTH (if that's of any relevance). 
On the error page rocket.chat seems to hang and sends potentially hundreds of POST requests (about 12 per second) every to `/api/v1/useInviteToken`, which all return `{"room":{"rid":"REDACTED","fname":"off-topic","name":"off-topic","t":"c"},"success":true}`

**Comment by cjhille** [comment]
UPDATE: Found the culprit for the error. 
If you disable the registration form for new users, channel invite links don't seem to work (even for current users). 
If you enable the registration form the invite links work, **however** afterwards the page still performs this enormous amount of request spamming the server until the user changes channels.

**Comment by AmShaegar13** [comment]
Still present in v2.4.8.

**Comment by rasos** [comment]
Not present in v3.0.

**Comment by wc3717** [comment]
Still having this issue in the latest version.

**Comment by robinreinhardt** [comment]
still present in v2.4.11

**Comment by robinreinhardt** [comment]
nice, will this fix also be available in version 2.x.x?

**Comment by pierre-lehnen-rc** [comment]
It'll be added to 3.2.0
