### ISSUE TITLE
It's got error message when I enable random password.

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#16104]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Debian 9
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

I login admin user.  I set user password to random password.But when I enable random password and save it.It's will show "Password does not meet the server's policy of at least one special character". How to fix it?

**Comment by mhaluska** [comment]
Try this, go to `Administration -> Accounts -> Password Policy`, disable `At Least One Symbol`

**Comment by apaarfus** [comment]
Sure, but what's the point in having a strong password policy if the random password generator doesn't pay attention to those rules?

**Comment by mhaluska** [comment]
I agree, random password generator should reflect Password Policy settings.

**Comment by jaroslavmraz** [comment]
Problem with password generator is more then year... I used to do it manualy but now you cant set password on your own as admin...

**Comment by reetp** [comment]
> Problem with password generator is more then year... I used to do it manualy but now you cant set password on your own as admin...

https://github.com/RocketChat/Rocket.Chat/issues/15880

**Comment by apaarfus** [comment]
Worst case, it appears manually setting a password (random or otherwise) is still exposed in the API (for now); so until this issue is addresses, there's still a way forward...albeit, a little convoluted.

**Comment by gabriellsh** [comment]
I see you skipped "Steps to reproduce" and other sections and added all the information under relevant logs. Irrelevant, badly organised or missing information could prevent your issue from being fully understood and makes the process harder for all contributors.

Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

Anyway, thanks a lot for your help!

**Comment by fleaz** [comment]
The problem is, that the "Generate random password" function does not adhere to the password policy of the server and generates invalid passwords. This is an old and known bug. See #12494
