### ISSUE TITLE
A channel/group cannot have zero owners once it has had one owner.

### ISSUE THREAD

**Issue by aviral243** [RocketChat/Rocket.Chat#16117]
### Description:

When a new channel or group is made, it has no owners. After you set one of the users as owner, you cannot remove him from this postion until you set someone else as the owner. ( You can set yourself as the owner to make this work. )

### Steps to reproduce:

1. Click on user and make him the owner.
2. Try removing him from the owner position.
3. You will get an error message saying, This is the last owner, please set a new owner before removing this one. 

### Expected behavior:

Either there should be flexibility to have zero owners like when the channel or group is initially created.
An alternative approach can be to set the Admin as owner as soon as the channel/group gets created, if one owner is needed at all times.

### Actual behavior:

You cannot have zero owners, once you've had an owner for your group/channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 19.10
- Deployment Method: meteor
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.17.0 
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 79
- Operating System: Ubuntu 19.10

### Additional context

Working on this.

### Relevant logs:

**Comment by MartinSchoeler** [comment]
@aviral243 How are you creating the channels? It should make the creator as owner.

**Comment by aviral243** [comment]
Yes. I just checked. It is happening for all other groups/channels, but not for the #general channel. Is that intented?

**Comment by serviceman** [comment]
I was forced to create a "fake/bot" account and hand over ownership to that account. I have other reasons to need a fake/bot account, so it worked for me.
