### ISSUE TITLE
How to set my own MONGO_URL

### ISSUE THREAD

**Issue by sinray** [RocketChat/Rocket.Chat#16119]
After I  clone this repo.
And i want to do something else by my own.
I changed `package.json`
{
"start": "MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local meteor",
}

But it didnt work.

Is there a config.js file to set my own MongoDB url ?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by ashishchauhan1** [comment]
Hi @MartinSchoeler @sinray i need to change my mongodb connection in rocket chat. Is there any solution for that?
