### ISSUE TITLE
No margin between add-users and invite-userrs in members-list

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16112]
### Steps to reproduce:

1. Any Channel
2. Click on member list
3. No margin between the buttons

### Expected behavior:

There should be margin

### Actual behavior:

![Selection_004](https://user-images.githubusercontent.com/43509699/71591447-5dd87180-2b52-11ea-8197-5bfea3e0ac8e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0 -develop 
- Operating System: Ubuntu
- Deployment Method: meteor
- Number of Running Instances: 1

**Comment by MartinSchoeler** [comment]
It seems to be working fine on the development version, please make sure to run the latest version, and check if you dont have any custom css, since the color of your buttons seems off. Thanks!
