### ISSUE TITLE
Assets >> logo (svg, png, jpg) stoppd working

### ISSUE THREAD

**Issue by zetahoq** [RocketChat/Rocket.Chat#16116]
### Description:

We are using a PNG logo under Administration >> Assests >> logo (svg, png, jpg). The image is currently showing as a broke HTML image icon. Browser Dev Tools is showing "Failed to load resource: the server responded with a status of 403 ()"

### Steps to reproduce:

1. Open Rocket.Chat and logo is not there. Rinse.Repeat

### Expected behavior:

Image should show up as it normally does.

### Actual behavior:

![image](https://user-images.githubusercontent.com/34850716/71647231-7a86bd80-2ca8-11ea-9982-6ee95855d48d.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  2.3.1
- Operating System:  Ubuntu
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version:  v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows 10, Ubuntu 18

**Comment by aviral243** [comment]
I'm not experiencing the issue on the development server.
I deployed using `meteor npm start`
![Screenshot from 2020-01-02 10-16-13](https://user-images.githubusercontent.com/44023445/71652145-48796800-2d49-11ea-8e94-a2ff02faf932.png)

**Comment by zetahoq** [comment]
It was a mistake on our end.

**Comment by ttosbt** [comment]
Sooo, what was the mistake on your end?  We'd like to know.  :^)
