### ISSUE TITLE
Add a list of reserved usernames

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1612]
Rocket Chat should have a list of reserved names than no one can use (cannot use them to create a new account or even change the username to them later).

Currently I can change my username to `all` and anyone who wants to mention me, well, is going to mention every one! :) (i just tested this on a server that allows renaming)

Also keep it possible to add other names/words to that list, in case someone wants to translate `all` to a local language or prevents misleading names like `admin` and such.

**Comment by engelgabriel** [comment]
+1

**Comment by alayek** [comment]
Interested in working on this. I already have some familiarity with the process, but need some guidance with the implementation aspect of it.

**Comment by fduraibi** [comment]
@alayek I believe you need to do two thing:
1- Add in the settings some field that has default names (like "all") and also allow admins to add more, maybe comma separated list or something like that. (comma is good since it is not allowed in the default naming regex)

2- check in the corresponding files to make sure the name that need to be created or renamed to is not in that list.
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/functions/setUsername.coffee

**Comment by alayek** [comment]
Thanks @fduraibi. I checked the file you have linked here - I am assuming we need to add an extra layer of check right after the RegEx validation with something like `RocketChat.settings.get("csv_BlackList").split(",").indexOf(userName) === -1`

But how do we add this list to `RocketChat.settings`? As in, which file does the abstraction resolves to? 
Also, how to make sure only admins can edit this list? 

I noticed the function at the bottom of the file that you have linked to:
```
RocketChat.setUsername = RocketChat.RateLimiter.limitFunction RocketChat._setUsername, 1, 60000,
	0: (userId) -> return true; return not RocketChat.authz.hasPermission(userId, 'edit-other-user-info') # Administrators have permission to change others usernames, so don't limit those
```

Here, admin privileges would be checked using `RocketChat.authz.hasPermission()`. Are we looking for something like that?

**Comment by marceloschmidt** [comment]
@alayek here are a few examples of how you add stuff to the admin settings page: `packages/rocketchat-lib/server/startup/settings.coffee`. You'd probably add that under Accounts group, and probably under Registration section. Then you'd have to check if desired username is on that list. I think the best place for checking is in `packages/rocketchat-lib/server/functions/checkUsernameAvailability.coffee`, this way  it would work on all places at once, as this function is called prior to setting the new username.
