### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by Mohammed-Deifallah** [RocketChat/Rocket.Chat#16133]
Hello all,
I found a bug in Rocket.chat Desktop application. Here's the relevant information:
Operating System: Windows 10 Pro
Version	10.0.17763 Build 17763
Rocket Version: 2.17.1
System Type: 64-bit Operating System, x64-based processor
Expected Behavior: When choosing any option from the context menu, it should do the same thing as its corresponding keyboard shortcut.
Actual Behavior: Keyboard shortcuts are working well, but the context menu doesn't work at all.
Reproducibility: It can be reproduced easily by right-clicking in any area and try any option from the pop-up menu.

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by Mohammed-Deifallah** [comment]
@MartinSchoeler I'm sorry for inconvenience. I've just edited my issue to meet your standards.

**Comment by MartinSchoeler** [comment]
Thanks!

**Comment by Borda** [comment]
I have a similar issue, clicking on a text with underline typo crash whole application!
- version: 2.17.3
- OS: LightDM Distro: Linux Mint 19.3 Tricia ; base: Ubuntu 18.04 bionic

**Comment by Gesalat** [comment]
@Borda: Thank you for adding this comment, I often had crashes after selecting text in a chat and right clicking for context menu. I just could not reproduce it every time, because I did not figure out it only happened on misspelled words. 

But: IMHO the issue reported above is a bit different to this one - only "Desktop application" and "context menu" are common ground. Did you think about opening a new issue describing exactly how to reproduce the crash?

**Comment by Borda** [comment]
yes, only misspell words and only in the textbox...
this is the console, but there is no error message...
```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/rocketchat-desktop --file-forwarding chat.rocket.RocketChat @@u %U @@
[bugsnag] Loaded!
(rocketchat-desktop:2): Gdk-WARNING **: 14:01:47.053: gdk_window_set_user_time called on non-toplevel
(rocketchat-desktop:2): Gdk-WARNING **: 14:01:47.183: gdk_window_set_user_time called on non-toplevel
(rocketchat-desktop:2): Gdk-WARNING **: 14:01:47.406: gdk_window_set_user_time called on non-toplevel
(rocketchat-desktop:2): Gdk-WARNING **: 14:01:47.534: gdk_window_set_user_time called on non-toplevel
```
