### ISSUE TITLE
Css doesn't refresh in development mode

### ISSUE THREAD

**Issue by soeyi** [RocketChat/Rocket.Chat#16136]
I've changed the `.sidebar`  css attribute `z-index` to `3` like the photo below;

![image](https://user-images.githubusercontent.com/38489160/71824343-46f6c980-30d4-11ea-9402-85544695988d.png)

However after i refresh my Chrome window.The css attribute is still what i wrote before;
![image](https://user-images.githubusercontent.com/38489160/71824464-89b8a180-30d4-11ea-9cce-aef0d0289232.png)

I run this with `meteor npm start`  on my macOs;
So I have to exit and restart with `meteor npm start `, and this is kind of  disturbing.

Thanks for ur time ~

**Comment by soeyi** [comment]
any one ?

**Comment by nxa127** [comment]
Same issue here, any solution ?
