### ISSUE TITLE
Settings for server default language

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1614]
Add the ability to set the default language for new users.

**Comment by engelgabriel** [comment]
+1

**Comment by djeber** [comment]
+1 really need this one

**Comment by sweetvvck** [comment]
Adding a language selection after registering?
I'll handle it. :p

**Comment by fduraibi** [comment]
@sweetvvck not after registering. We want an administrator setting that will allow the admin to select a default language for  the server.
Currently, the server defaults to English, so a new user will be greeted by a login page in English language. Instead it should load the language that was set by the admin.

**Comment by sweetvvck** [comment]
Ok, i got it.

**Comment by fduraibi** [comment]
@sweetvvck AWESOME WORK. :+1: but.... you broke my solution :'(

Now when I login it keeps the server's default and I have to refresh the page to get RTL, like it was before my patch

**Comment by fduraibi** [comment]
You need to add the `Tracker.autorun (c) ->` back, since the language change happens after the startup file got executed so it will never get to this line `$('html').addClass "rtl".

On a fresh machine `Meteor.user()?.language` is always null since no user is logged in. And once the user logs-in their language will be available but won't execute the change.

**Comment by sweetvvck** [comment]
@fduraibi , I'm sorry, its my mistake. You mean add `Tracker.autorun(c) -> back` like this:

```
	Meteor.subscribe("userData", () ->
		userLanguage = Meteor.user()?.language
		userLanguage ?= defaultUserLanguage()
		Tracker.autorun (c) ->
			if localStorage.getItem('userLanguage') isnt userLanguage
				localStorage.setItem('userLanguage', userLanguage)
				if isRtl localStorage.getItem 'userLanguage'
					$('html').addClass "rtl"
```

**Comment by fduraibi** [comment]
Hmmm, I don't think so but I am not sure. So previously we have this:
```
Tracker.autorun (c) ->
		if Meteor.user()?.language?
			c.stop()
			if localStorage.getItem('userLanguage') isnt Meteor.user().language
			(...rest of code)
```
So as I understand it the [tracker](http://docs.meteor.com/#/full/tracker_autorun) will keep track of `Meteor.user()?.language?` and when its value changes will run the function. So the first time before a user login that variable will be null. but it will change after the login so the tracker will rerun that code and add rtl if the user's language needs it.

And `c.stop()` is to stop the tracking since it is not needed any more after we have the user's language. But to be honest I don't know which variable does it track and based on what.

**Comment by fduraibi** [comment]
@sweetvvck what does `Meteor.subscribe` do? since right now it doesn't even change the language. it always shows the menu in English even though I set the lang to Arabic!

**Comment by sweetvvck** [comment]
Meteor only response email, name and some other build-in fields by default, which means user's language won't be got by Meteor.user()?.language until Meteor.subscribe('userData') was called.

And you mean you set user language(or the app language) to Arabic, but still got english? Can you post a snapshot?

**Comment by fduraibi** [comment]
Ok, now I understand what subscribe does, but if you look into the `userData.coffee` publish asks for the userId, however, when the startup file is run the user is not logged in yet so no `userId`.

So we need a way to read the language after the user login.

![rocket_lang](https://cloud.githubusercontent.com/assets/432460/11960162/3e1b63b4-a89f-11e5-972b-603e41bcb319.png)

**Comment by fduraibi** [comment]
@sweetvvck any updates?

**Comment by sweetvvck** [comment]
@fduraibi I got a lot of work this week, I'll handle the issue this weekend.
I got what you mean and I'll do some updates, lets talk again then.

**Comment by sweetvvck** [comment]
@fduraibi I have created a new pr to handle this issue, and you can try my branch to check if it satisfies you.

**Comment by sweetvvck** [comment]
@fduraibi is my updates make sense?

**Comment by engelgabriel** [comment]
@marceloschmidt can you test this?

**Comment by fduraibi** [comment]
@sweetvvck Yes it works, thanks

I believe it is already merged in the develop branch right?

**Comment by marceloschmidt** [comment]
Yes, this is in the develop branch now.
