### ISSUE TITLE
snap server part fails to autostart after server reboot

### ISSUE THREAD

**Issue by Tupsi** [RocketChat/Rocket.Chat#16149]
### Description:

I have installed rocket.chat on my ubuntu 18.04 LTS from the documentation over at https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/
The software itself works perfect, but I have an issue with the starting procedure after a reboot of my server. From the logs it seems, that the rocketchat-server part does not wait long enough for the mongo part to start as one of the messages clearly states:
"Mongo is not available, can't start. Waiting 10 seconds and trying again"
But it seems, even the 10s do not help (or the script does not wait, I don't know).

Anyway, when I came back after a reboot after a few minutes and simple start the server part manually by using

systemctl start snap.rocketchat-server.rocketchat-server.service

everything goes up nicely and works until a new reboot.

I dirty fixed the problem for me by adding

ExecStartPre=-/bin/sleep 30

into snap.rocketchat-server.rocketchat-server.service but of course this is gone once I get an update for the snap, so I am looking for a more permanent solution.
Maybe you can make the snap.rocketchat-server.rocketchat-server.service startscript dependent on 
snap.rocketchat-server.rocketchat-mongo.service? Which imo it should be anyway.

### Steps to reproduce:

1. Install rocket.chat via snap method on a ubuntu 18 LTS
2. reboot the server

### Expected behavior:

service should be running correctly

### Actual behavior:

mongodb service is not starting fast enough, so the server part fails to start, rocket.chat service is not usable until a manuel start.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: ubuntu 18.4 LTS (4.15.0-74-generic)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

**Comment by abmyii** [comment]
Same issue - otherwise works perfectly.

**Comment by mohammedragabsoftxpert** [comment]
@Tupsi Did you find any permanent solution for this issue?, facing same issue!

**Comment by Tupsi** [comment]
> @Tupsi Did you find any permanent solution for this issue?, facing same issue!

I did, but it is most likely no solution for you, as I switched to a different chat server and removed rocket.chat from my server. So sorry, nothing really helpful from me.
