### ISSUE TITLE
[BUG] API "Create Token" always returning FALSE, even with correct credentials

### ISSUE THREAD

**Issue by litabe** [RocketChat/Rocket.Chat#16159]
### Description:
The END POINT /api/v1/users.createToken is always returning "[error-not-authorized]" even with correct  X-Auth-Token and X-User-Id

### Steps to reproduce:

1. from comand line:
`curl -H "X-Auth-Token: TOKEN-HERE" \
     -H "X-User-Id: ID-HERE" \
     -H "Content-type:application/json" \
     http://localhost:3000/api/v1/users.createToken \
     -d '{ "username": "usernameHere" }'`

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Ubuntu 18.04.3 LTS
- Deployment Method: manual install
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.3

**Comment by MarcosSpessatto** [comment]
Hi @litabe, in the last versions, 2.1.0 to be exact, we put a ENV var to be guard this endpoint, then  you need to set that to be able to create new tokens, as you can see [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/lib/server/methods/createToken.js#L8).

**Comment by litabe** [comment]
Thanks @MarcosSpessatto,
Adding "CREATE_TOKENS_FOR_USERS" to ENV works...

**Comment by matikucharski** [comment]
@MarcosSpessatto 
But how can I add this env variable to RocketChat app installed on cloudron? I don't want to fork docker image and chanage its env vars. Is there any good solution for this?
