### ISSUE TITLE
Add documentation on user and group end to end encryption

### ISSUE THREAD

**Issue by jmpsf** [RocketChat/Rocket.Chat#16153]
Hi,

I've read the docs and the following issues: https://github.com/RocketChat/Rocket.Chat/issues/9999, https://github.com/RocketChat/Rocket.Chat/issues/36, https://github.com/RocketChat/Rocket.Chat/issues/15095 and the description of the PR: https://github.com/RocketChat/Rocket.Chat/pull/10094 and found no documentation on how e2e encryption is handled either in groups or single chats.

I think this information should be easily reachable for anyone trying to decide to use the application.

**Comment by Gummikavalier** [comment]
More documentation is needed indeed.

These are my own speculations on the subject:

- Both public and private keys of users are saved into the database (I checked both can be found in the database)
- Private key is protected by a password (you are asked for this with a new clean browser session)
- In group chats particularly the messages are encrypted with the public keys of all members (for all members to be able to see their contents)

I suppose the need to save the private keys into server database stems from usability standpoint;
It is used to distribute the keys between all client devices of the user.
If the keys were saved only in the client end, the users would have to move these keys manually between their devices using cameras (QR-code), USB-sticks etc. Now client can simply query them directly from the server (in password protected format) instead.

The private key is encrypted in the database and is opened with the password in the client end browser using the password provided by the user. The password gets saved only into the cache of the browser and is not transferred to the server.

In group chats all messages are encrypted by all members' public keys separately. If one is removed from the group, they cannot see any new messages in clear text as his/her key has not been used in encrypting it anymore.

In case that the server database gets compromised, and regardless whether a chat is direct or group one (does not matter; two persons is practically a group already), effective encryption is as strong as is the weakest password in the whole chain of trust.

**Comment by GoetheG** [comment]
I had a similar issue bus it was closed. I think your issue and mine should be merged:
https://github.com/RocketChat/Rocket.Chat/issues/14829
