### ISSUE TITLE
First access for user- Change password

### ISSUE THREAD

**Issue by domenicocosta** [RocketChat/Rocket.Chat#16156]
At the first access with password change, once the password has been changed, a pop-up will appear with the word "Not allowed" and the password will be changed regularly.

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by domenicocosta** [comment]
Hi Gabriell,
the steps taken to repeat are:
* install version 2.4 on Centos 7
* log in with Admin and create user B, with random password and password change request at first access
* User B receives the email to access in Rocket, after having entered the password attached to the email asks him to change the password.
* inserts the new password, and the system responds with an alert popup the word "Not allowed", but the password is changed (1).
* In fact, userB logs in from another browser with the new password.

The problem lies in task 1, because the system gives an error.

I hope I have clarified the problem.

Thanks for the good work you are doing.

**Comment by fleaz** [comment]
The same bug popped up over a year ago. Maybe something similar: #12820

**Comment by domenicocosta** [comment]
Hello
the popup I am referring to is not the one from the old bug.

Exactly the steps are:
once the email with the password has been received, a change is requested.

On this mask, once a new password has been added, I would expect to log in, instead a pop-up appears in red at the top "not allowed" and I remain with the possibility of returning the password.

In fact, the first password change was successful, and I log in with another browser.

if necessary, I simulate the problem and make a video.

Waiting for a confirmation
thanks

**Comment by didierm** [comment]
Confirmed in v2.4.0.
This may have been addressed in https://github.com/RocketChat/Rocket.Chat/pull/16184 (fixed in v2.4.2) ?

**Comment by didierm** [comment]
Tested with 2.4.11 ; confirmed fixed.
-> this issue should be closed.
