### ISSUE TITLE
Compact View Mode Indentation Question

### ISSUE THREAD

**Issue by MatthiasHertel** [RocketChat/Rocket.Chat#16163]
### Description:
wrong identation of messages
![image](https://user-images.githubusercontent.com/8426566/71997677-922ceb80-323e-11ea-9a9b-2d3484de634b.png)

### Steps to reproduce:
fill the text below
foooo 
```
fffoooooo
```
![image](https://user-images.githubusercontent.com/8426566/71997764-b8528b80-323e-11ea-893d-0498df45b3c8.png)

### Expected behavior:
no indentation in messages
### Actual behavior:
see steps to reproduce above

### Server Setup Information:
![image](https://user-images.githubusercontent.com/8426566/71998012-2303c700-323f-11ea-9633-4aa63dbd79d7.png)

### Client Setup Information

Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by MartinSchoeler** [comment]
Hey, @MatthiasHertel This is when using the `compact` view mode, right? For now, this is the default behavior, we found having all messages in the same indentation was less confusing, of course, this can be discussed and changed if needed. Since the `compact` view is used by a specific part of the userbase we should ask more people what they think.

**Comment by MatthiasHertel** [comment]
Hey @MartinSchoeler,

whoops sorry my fail, you are right , i forget that i setup this.

for me: i love the compact mode but this indent looks not so nice. i think a linebreak after the username looks nice and is less confusing  but an indent of the whole message makes the message/information more difficult to consume. the metadata line (username, userrole, timestamp,etc) does not look intrusive and can end with a new line. i think the typical gridlayout should in all view modes the same.

compact means for me:
- smaller thumbnails
- more contrast 
- maybe bold fonts

kind regards
matthias

**Comment by engelgabriel** [comment]
Looking at Discord, I agree with @MatthiasHertel 

![image](https://user-images.githubusercontent.com/1000217/81509683-be3aa500-92e2-11ea-8188-74040927de11.png)
