### ISSUE TITLE
disable / enable registration form 

### ISSUE THREAD

**Issue by gstlouisgit** [RocketChat/Rocket.Chat#16162]
I have two rocket chats going, one was test and other is live.

on my test Version: 1.2.1 ( all specs below ) in admin -> Accounts -> Registration Form I can see the dropdown.

on my live Version 2.3.2 in admin -> Accounts -> Registration Form I could not see the same dropdown.  Turns out it is there was but like not very visible, it looks like a progress line just under "Registration Form" and above "Registration Form Secret URL"

actually I just realized that this problem is with the APP.  I just tried with chrome and everything is fine on the browser.  So not sure if I should report this here...

**dev server:**
Rocket.Chat
Version	1.2.1
Apps Engine Version	1.4.2
Database Migration	147
Database Migration Date	Sun Jan 05 2020 11:41:26 GMT-0500 (GMT-05:00)
Installed at	Tue Jun 11 2019 10:11:41 GMT-0400 (GMT-04:00)
Uptime	2 days, 23 hours, 9 seconds
Deployment ID	ZbfAdKQaXEBCo9RqN
PID	1057
Running Instances	1
OpLog	Enabled
Commit
Hash	7475d7628a4e41e0c25a7e131d46b596465ae859
Date	Fri Jun 28 18:40:11 2019 -0300
Branch	HEAD
Tag	1.2.1
Author	Diego Sampaio
Subject	Merge pull request #14898 from RocketChat/release-1.2.1

**production server**
Rocket.Chat
Version	2.3.2
Apps Engine Version	1.7.0
Database Migration	169
Database Migration Date	January 5, 2020 8:30 AM
Installed at	December 26, 2019 3:32 PM
Uptime	3 days, 1 hours, 59 minutes, 34 seconds
Deployment ID	zY4v5BXtivttdoybP
PID	8800
Running Instances	1
OpLog	Enabled
Commit
Hash	ffb478f88f75dab281f24f10660687814479312a
Date	Thu Dec 12 18:15:05 2019 -0300
Branch	HEAD
Tag	2.3.2
Author	Diego Sampaio
Subject	Merge pull request #15967 from RocketChat/release-2.3.2

**Comment by pierre-lehnen-rc** [comment]
Can you share a screenshot of what it looks like?

**Comment by gstlouisgit** [comment]
Sorry for the delay.

Here is a before and after screenshot of what it looks like.  When you carefully click on the little grey line it opens up and you can get your dropdown.  hope this helps.

 <img width="963" alt="Screen Shot 2020-01-28 at 9 48 50 AM" src="https://user-images.githubusercontent.com/20375753/73274485-a025ba80-41b3-11ea-8e0e-20ea983b86cf.png">
<img width="898" alt="Screen Shot 2020-01-28 at 9 49 06 AM" src="https://user-images.githubusercontent.com/20375753/73274483-a025ba80-41b3-11ea-9399-0fda04341408.png">
