### ISSUE TITLE
If there is `ufs` somewhere in url the request to api always returns 404

### ISSUE THREAD

**Issue by lastsecondsave** [RocketChat/Rocket.Chat#16174]
### Description:

We have one user for which requests to `users.info` fail with 404 even if the user is in the database. After some experiments we found that if url contains `ufs` string the Rocket.Chat always returns 404 with no body. In out case userId contains `ufs`. We checked open.rocket.chat and it has the same behavior. Any api request fails when `ufs` is somewhere in the url.

### Steps to reproduce:

1. Query this endpoints:
```
https://open.rocket.chat/api/v1/users.info?userId=123
https://open.rocket.chat/api/v1/users.info?userId=ufs
```

### Expected behavior:

They behave the same, either ask you to log in or return "bad request".

### Actual behavior:

For the second endpoint you will always get 404.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2, 2.4.0

**Comment by MarcosSpessatto** [comment]
Hello @lastsecondsave, first of all, thanks for investigating the problem and let us know.
Seeing the problem that you described, I noticed that this problem occurs inside one of our external dependencies, as you can [see here](https://github.com/jalik/meteor-jalik-ufs/blob/master/ufs-server.js#L77-L81). Basically that code verify if there is a `ufs` string inside the url and if it is true, the package understands as if it were a request to the the package (file-upload/store in this case). We are under many improvements on our code base and starting to change these Meteor's packages to npm packages is a priority.

**Comment by sistason** [comment]
Has there been any progress yet? 
Or a rough estimation, if that is more a "nice to have" or more a "fixed when X happend, which will be in feature Y"? :)

**Comment by tomplaskon** [comment]
Any update here? This is creating some serious problems for us.

**Comment by sampaiodiego** [comment]
we'll be working on a fix for this as soon the next release cycle begins..
