### ISSUE TITLE
[NEW] Support of ICAP

### ISSUE THREAD

**Issue by nredko** [RocketChat/Rocket.Chat#16175]
Implement embedded support of Internet Content Adaptation Protocol (ICAP) RFC3507 as client.

As major feature, it will allow to connect third-party services for bad-words filtering, antivirus scan of attachments, detection of policy violations etc.

Also it will make possible to provide transparent translation, remote chat logging and any possible content processing performed by connected ICAP service.

https://tools.ietf.org/html/rfc3507

```
   ICAP, the Internet Content Adaption Protocol, is a protocol aimed at
   providing simple object-based content vectoring for HTTP services.
   ICAP is, in essence, a lightweight protocol for executing a "remote
   procedure call" on HTTP messages.  It allows ICAP clients to pass
   HTTP messages to ICAP servers for some sort of transformation or
   other processing ("adaptation").  The server executes its
   transformation service on messages and sends back responses to the
   client, usually with modified messages.  Typically, the adapted
   messages are either HTTP requests or HTTP responses.
```

**Comment by ankar84** [comment]
Thumbs up for ICAP support!

**Comment by crazylive** [comment]
you are welcome

**Comment by darky** [comment]
Feel free to add PR please
