### ISSUE TITLE
Heroku build fails (timeout)

### ISSUE THREAD

**Issue by jonyhayama** [RocketChat/Rocket.Chat#16179]
### Description:

Fails to build app on Heroku.

### Steps to reproduce:

1. Got to https://rocket.chat/docs/installation/paas-deployments/heroku/
2. Click 'Deploy to Heroku'
3. Go to 'Build Log' and check the app failed to build (after 60 minutes)

I have also tried to build it following the steps on 'Customized command line for developers' session, changing the buildpack and using older versions (2.3.2 and 2.3.1).

Always get the same output.

### Expected behavior:

Build successfully.

### Actual behavior:

App doesn't build.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1, 2.3.2 and 2.4.0
- Heroku

### Relevant logs:

```
> Rocket.Chat@2.4.0 postinstall /tmp/build_f1ca573a41fb59074114f735a668d587
> node .scripts/npm-postinstall.js
Running npm-postinstall.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
added 3612 packages from 3424 contributors and audited 61731 packages in 202.563s
39 packages are looking for funding
  run `npm fund` for details
found 1303 vulnerabilities (14 low, 112 moderate, 1177 high)
  run `npm audit fix` to fix them, or `npm audit` for details
 => Errors while parsing arguments:
While adding package rocketchat:lib:
error: no such package
-----> Running before bundling
-----> Installing phantomjs.
-----> Building Meteor app with ROOT_URL: https://prod-distrito-rocket-chat.herokuapp.com/
Livechat: updating npm dependencies -- uglify-js...
WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
 - postcss@7.0.6 installed, postcss@^6.0.22 needed
 - postcss-load-config@2.0.0 installed, postcss-load-config@^1.2.0 needed
Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Node#moveTo was deprecated. Use Container#append.
-----> Timed out running buildpack Node.js
 !     Timed out compiling app (60 minutes)
 !     See https://devcenter.heroku.com/articles/slug-compiler#time-limit
```

**Comment by GoaGit** [comment]
@jonyhayama do you have prior, successful experiences with this 'one-click Heroku install'? When I manually deploy the repo to Heroku, it gives (naturally) a timeout as well.

**Comment by jonyhayama** [comment]
@GoaGit absolutelly. First time I tried it (for staging purposes) worked like a charm. Deployed Dec 11, 2019 at 9:41 AM). I had to upgrade the database as stated in some other issue and it all went well. 

When I tried a second time (now for production) it simply failed. I struggled a few days with it before posting this issue. The first failed attempt was on Dec 27 2019. 

To be more specific, I tried:

- The button a couple of times
- The button changing to Meteor buildpack
- The 'Customized command line for developers' with versions 2.4.0, 2.3.2, 3.2.1 with RocketChat buildpack
- The 'Customized command line for developers' with versions 2.4.0, 2.3.2, 3.2.1 with Meteor buildpack

**Comment by GoaGit** [comment]
@jonyhayama I tried the option to deploy to Scalingo. It timed out as well, after 30 minutes (probably their maximum time). I just looked into Rocket.Chat last week, so I have no prior experience. The logs are not detailed enough to figure out which task is being worked on.

**Comment by GoaGit** [comment]
@jonyhayama have you tried this solution https://github.com/RocketChat/Rocket.Chat/issues/13198#issuecomment-535469428 already?

**Comment by jonyhayama** [comment]
@GoaGit I just tried to build it on Heroku. 

Regarding this solution https://github.com/RocketChat/Rocket.Chat/issues/13198#issuecomment-535469428 :
I think it's a solution for a different problem. First I build the app, then I get a DB error, then I apply the metioned solution. This is what I did on my staging app (that worked just fine)...

**Comment by jonyhayama** [comment]
@GoaGit just o my own piece of mind, I've tried to build the app with a paid db version, still no go... :(

**Comment by GoaGit** [comment]
@jonyhayama I will try deploying to AWS. Probably somewhere next week. I will use a configuration similar to the Heroku setup. Maybe the logs will be more detailed about certain issues. I do have a strong preference for deploying to Heroku though.

**Comment by GoaGit** [comment]
@FriendlyUser @rtarantelli sorry to bother, you seem to have faced a similar issue when deploying Rocket.Chat to Heroku in the past (https://github.com/RocketChat/Rocket.Chat/issues/12588). Were there any obvious reasons for the deploy to fail? Did you manage to get working in the end?

**Comment by jhonny2pamp** [comment]
Good afternoon Gentlemen, I managed to upload rocketchat on amazon, they have a tutorial to do that, just beware!

In the docker-compose.yml file these lines look like this:
mongo:
    image: mongo

should look like this:
mongo:
    image: mongo: 4.0

And I commented the whole replica snippet to save memory

That is all

**Comment by GoaGit** [comment]
I need to work with the server locally. I deployed via docker-compose and it works.

**Comment by frontvu** [comment]
I'm facing this same issue. Nothing as worked so far.

**Comment by jasonbarry** [comment]
Still an issue

**Comment by aakatev** [comment]
That's the issue with most recent build:

```
-----> Compressing...

 !     Compiled slug size: 534.9M is too large (max is 500M).

 !     See: http://devcenter.heroku.com/articles/slug-size

 !     Push failed```
