### ISSUE TITLE
WebRTC Distorted sound

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#1617]
When having a Video Call between a Windows machine and a Mac the sound on the Mac coming from windows is far to loud and overdriven(distorted). The Mac sound on the Windows machine is fine. When the windows user reduces his mic level it's fine for a few seconds but the volume increases back to a really unpleasant sound quality automatically after a short while.
##

**Comment by engelgabriel** [comment]
Should be fixed as part of https://github.com/RocketChat/Rocket.Chat/issues/933

**Comment by flashguy22** [comment]
@engelgabriel I have a very current release(updated two days ago) of the server running with mobile push notifications working and we have this issue constantly. Maybe you could investigate...

**Comment by engelgabriel** [comment]
We will. The webrtc traffic doesn't go via the server, it is a p2p only and the encoding is all done by the browser. We need an expert on WebRTC to help us with this one.

**Comment by flashguy22** [comment]
ok, thanks for the update. We are using the native apps if this helps

**Comment by MartinSchoeler** [comment]
Hey @flashguy22 , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
