### ISSUE TITLE
[BUG] Images still loaded with 'Auto load images' setting disabled

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#16177]
### Description:

There is a global setting "Auto load images". When it is disabled (grey toggle), all the images are displayed without having to click on them.

### Steps to reproduce:

1. As an admin go to Administration -> Accounts -> Default User Preferences -> Auto Load Images
2. Set the toggle to disabled state (grey color)
3. Save changes
4. Go to any channel that contains image attachments

No need to click on images to display them.

### Expected behavior:

Having to click on each new image before displaying it.

### Actual behavior:

Setting:
![image](https://user-images.githubusercontent.com/11751017/72075031-3a9c8780-32f3-11ea-9210-97949ecb5a79.png)

Result:
![image](https://user-images.githubusercontent.com/11751017/72075358-e04ff680-32f3-11ea-9fb8-989746303bd3.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: browser version
- Operating System: Windows

### Additional context

The setting got broken after #15895 got released.

**Comment by ozata** [comment]
I am checking this out, any suggestions?
