### ISSUE TITLE
RocketChat.Info  is not available on local dev build

### ISSUE THREAD

**Issue by flourishing** [RocketChat/Rocket.Chat#1618]
same branch ,same code . when i run meteor  int the directory, Chrome client console can run RocketChat.Info  and shows the version ,  but if i build it ,start the service by pm2 , doesn't show RocketChat.Info, which lead the rocket chat. codova  can't works always report my rocket chat version is too old.
![1](https://cloud.githubusercontent.com/assets/5078097/11711696/4ab3cc78-9f63-11e5-8db9-c8f2d68ff7ed.png)
![2](https://cloud.githubusercontent.com/assets/5078097/11711697/4b0f039a-9f63-11e5-8746-d2398746ee66.png)
![3](https://cloud.githubusercontent.com/assets/5078097/11711698/4b125ca2-9f63-11e5-83c7-12424e7a6e10.png)

**Comment by Sing-Li** [comment]
@flourishing   Deploy your server via our binary tgz to bypass the problem... https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

**Comment by engelgabriel** [comment]
Are you 100% sure that you are pointing pm2 to the right bundle folder?

**Comment by flourishing** [comment]
ROOTPATH=/var/www/fans12306_2

cd $ROOTPATH
meteor build --server "$HOST" --directory $ROOTPATH

cd $ROOTPATH/bundle/programs/server
npm install

....

![2015-12-10 11 03 17](https://cloud.githubusercontent.com/assets/5078097/11718794/a955b6e0-9f92-11e5-956f-01ed163d9f56.png)
![2015-12-10 11 03 41](https://cloud.githubusercontent.com/assets/5078097/11718795/a95788e4-9f92-11e5-9191-6d70f8d3d2a7.png)

**Comment by engelgabriel** [comment]
do you use a pm2 json file?

**Comment by flourishing** [comment]
thanks for engelgabriel's help.
on my laptop it's working , server ,not ok.  
delete all the file,re clone the code, and build it again , after update all packages, now it works .
