### ISSUE TITLE
Client's livechat returns an error on close if the department requires a tag

### ISSUE THREAD

**Issue by henryfok** [RocketChat/Rocket.Chat#16191]
### Steps to reproduce:

1. Client starts a new livechat and selects a department that has the "Request tag(s) before closing conversation" setting set to "Yes"
2. Client attempts to close the livechat by clicking "Options" and "Finish this chat"
3. Chat returns error
4. Toggle the "Request tag(s) before closing conversation" setting  to "No"
5. Repeat step 1 and 2, but this time chat closes successfully

### Expected behavior:

Conversation should end / ask client for tag

### Actual behavior:

![image](https://user-images.githubusercontent.com/9781557/72118278-793b3d80-3305-11ea-87fc-6ca15aa29e76.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Centos 7
- Deployment Method: Manual install
- Number of Running Instances: 4
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.12

### Client Setup Information

- Desktop App or Browser Version: Chrome Browser Version 79.0.3945.88 (Official Build) (64-bit)
- Operating System: Centos 7

### Additional Information

Google Chrome console returns the following when client clicks the "Finish this chat" button
`Failed to load resource: the server responded with a status of 400 (Bad Request) /api/v1/livechat/room.close:1`

**Comment by subham103** [comment]
I want to work on this issue. One doubt is if the client ends the chat, whom should we ask to give this conversation a tag, client or the agent assigned? Imo It should be the agent whom we should bother for things like tags. What say?

**Comment by renatobecker** [comment]
> I want to work on this issue. One doubt is if the client ends the chat, whom should we ask to give this conversation a tag, client or the agent assigned? Imo It should be the agent whom we should bother for things like tags. What say?

Hi @subham103, I'm working on this issue, it'll be available on our next release -> `3.1`.
Thanks.
