### ISSUE TITLE
Custom OAuth not migrated properly to 0.8.0

### ISSUE THREAD

**Issue by wtsarchive** [RocketChat/Rocket.Chat#1619]
I had two custom OAuth services set up few weeks ago. I've now to 0.8.0 branch and when I go to Accounts settings page the services are not there. Also, the login buttons ARE present on login form in the browser, but they are actually missing from the iOS app.

**Comment by sampaiodiego** [comment]
Is it working when you add a new one?

**Comment by wtsarchive** [comment]
Yes, I could create a new one and it was shown on the list.

**Comment by wtsarchive** [comment]
I've inspected `meteor_accounts_loginServiceConfiguration` collection and it does contain the old services, so they're not lost, they are just not shown.
And here's one of the items in `rocketchat_settings`:
```
{ "_id" : "Accounts_OAuth_Custom_Reddit_token_path", "value" : "ssl.reddit.com/api/v1/access_token", "i18nLabel" : "Accounts_OAuth_Custom_Token_Path", "type" : "string", "group" : "Accounts", "section" : "Custom OAuth: Reddit", "ts" : ISODate("2015-11-24T17:00:05.220Z"), "hidden" : true }
```

Maybe the issue is the `hidden`: `true` parameter? I didn't set that though.

**Comment by sampaiodiego** [comment]
yes.. certainly is the `hidden` flag.
the guys touched the code around this flag in these days.

@marceloschmidt or @engelgabriel , can you help here? do you guys know why this setting was set to `hidden`?
