### ISSUE TITLE
Blocked autofocusing on a form control in a cross-origin subframe

### ISSUE THREAD

**Issue by uChanning** [RocketChat/Rocket.Chat#16192]
### Description:

I am currently trying to get iFrame integration to work. I am using Google oAuth for my authentication on rocket.chat and my main page. I am using Google Chrome and I am getting the following error:
![Screenshot_3](https://user-images.githubusercontent.com/52388029/72129156-e2897380-333a-11ea-8182-849a3bdab9c1.png)
on my main page when logging in.

The domain layout:
example.com (main page that I'm trying to get rocket.chat to authenticate through)
chat.example.com (rocket.chat page)

Both are using the same google ClientID.

I am using a reverse proxy for rocket.chat and am using the reverse proxy link to open up the iFrame and attempt to authenticate. 

### Steps to reproduce:

1. https://rocket.chat/docs/developer-guides/iframe-integration/authentication/#google
Followed exact steps from documentation except for the iFrame, which is:
`<iframe id="chatiFrame" style="height:600px;width:600px;" src="https://chat.example.com/channel/general"></iframe>`

### Expected behavior:

Rocket.Chat to login when logging into the main page.

### Actual behavior:

Does not login, displays error.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: Ubuntu 16.04 (Server)
- Deployment Method:  Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 79.0.3945.117
- Operating System: Windows 10 Pro

### Relevant logs:

![Screenshot_3](https://user-images.githubusercontent.com/52388029/72129156-e2897380-333a-11ea-8182-849a3bdab9c1.png)
I am not getting any logs when accessing the main page. Don't think any other logs will be relevant but I may be wrong.

**Comment by santoshsingh94** [comment]
I am also getting the same issue

**Comment by Yambr** [comment]
+1

**Comment by ed1nh0** [comment]
+1

**Comment by usamamashkoor** [comment]
@channing-teh can you please let me know how I can access Meteor Object, so that I can login with token to?

            **Meteor.loginWithToken(googleToken);**

**Comment by channing-teh** [comment]
> @channing-teh can you please let me know how I can access Meteor Object, so that I can login with token to?
> 
> ```
>         **Meteor.loginWithToken(googleToken);**
> ```

You can have it automatically log you in by following the steps I provided in my solution.

If you're wanting to do it manually, just go to the developer console and enter:
`Meteor.loginWithToken(YOUR_TOKEN);`

You can get your token by getting the value of the Google cookie you set (assuming you set one).
