### ISSUE TITLE
Clicking enter on the edit room info does not save the settings

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16199]
### Description:
For saving the settings on the edit room info flexTab you have to manually click on the
 save button

### Steps to reproduce:

1. Go to Room Info
2. Click Edit
3. Change Name and press Enter

### Expected behavior:

The settings should be saved

### Actual behavior:
![Selection_010](https://user-images.githubusercontent.com/43509699/72170930-cdbee580-33f7-11ea-921e-d3e324fd78cf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0 develop
- Operating System:  ubuntu
- Deployment Method:  Meteor

## Additional
I am working on it

**Comment by ritwizsinha** [comment]
@sampaiodiego please review

**Comment by mariaeduardacunha** [comment]
Tested in the latest version (2.5.0-develop) and this issue doesn't happen anymore. Also, links shouldn't be highlighted. If you happen to experience this issue again, please reopen this with updated details. Thanks!
