### ISSUE TITLE
Knwl.js integration

### ISSUE THREAD

**Issue by udnaan** [RocketChat/Rocket.Chat#162]
Integrate Knwl.js so a user message contains actionable links for plugins. As in a map plugin can intercept an entered address or a calendar plugin can intercept dates. 

I know it's a bit early to be talking about it but it would be a cool think to have and would make this a true Slack alternative. 
Just leaving it here for reference. I may come back on work on it if someone else doesn't pick it up before that. 
##

**Comment by engelgabriel** [comment]
This does looks cool.

I've just added the issue https://github.com/loadfive/Knwl.js/issues/85 offering to help them to build an offial meteor packdege. If anyone think it would be useful, please give a :+1: there!

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by FranzSkuffka** [comment]
@engelgabriel are you aware of [retext](https://github.com/wooorm/retext)? Seems more alive than this.

**Comment by engelgabriel** [comment]
I'll take a look!

**Comment by engelgabriel** [comment]
The project is no longer maintained https://github.com/benhmoore/Knwl.js/issues/97
