### ISSUE TITLE
Bad ui for unauthorized page 

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16204]
### Description:

Currently, the 403, unauthorized page doesn't have a good UI. 

### Steps to reproduce:
Navigate to any unauthorized page in rocketchat

### Expected behavior:

Good ui is needed

### Actual behavior:

![Selection_012](https://user-images.githubusercontent.com/43509699/72202882-93eaef00-348a-11ea-9cb3-a4c331d4b0d0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0 develop
- Operating System: ubuntu

### Additional context
I am working on it

**Comment by mariaeduardacunha** [comment]
Any major changes to the design of the UI needs to be approved by our design team. We will raise this issue to our design team, so please be patient. Thanks for the feedback!

**Comment by ruKurz** [comment]
related with https://github.com/RocketChat/Rocket.Chat/issues/11294
