### ISSUE TITLE
Custom emoji is not deleted from UI

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16203]
#### When a custom emoji is deleted by admin, it's state is still persisted in the UI and it causes many errors such as:-
(1) After deleting the emoji, it is not removed from UI
![12](https://user-images.githubusercontent.com/43786728/73112474-790d8580-3f34-11ea-9dd5-5afda87bc883.gif)

(2) After deleting a emoji, try to create a new custom emoji. It will give success message editing the previous deleted emoji (on the UI only).
![13](https://user-images.githubusercontent.com/43786728/73112536-b8d46d00-3f34-11ea-9638-2ce43c92fab1.gif)

(3) Clicking Edit emoji gives error on console if emoji is null
![14](https://user-images.githubusercontent.com/43786728/73112466-7579fe80-3f34-11ea-8bda-a566b71e7390.gif)

(4) HeaderData of flexTabBar is null initially and does not have default value.
![11](https://user-images.githubusercontent.com/43786728/73112487-80cd2a00-3f34-11ea-8ff1-4c9bf4902776.gif)

### Steps to reproduce:

1. Got to admin panel
2. Go to custom emoji section
3. Delete a custom emoji

### Expected behavior:
The custom emoji must not be persisted in the UI

### Actual behavior:
![issue1](https://user-images.githubusercontent.com/43786728/72201064-49f80e00-3476-11ea-8331-c8c2e461620d.gif)

### Additional context
I am working on it.

**Comment by MartinSchoeler** [comment]
Hello @ashwaniYDV we just rewritten the admin pages in react, and this issue don't happen anymore, if you see this problem again, please open a new issue with updated details. 

Thanks!
