### ISSUE TITLE
Proper way to update/upgrade (Docker)

### ISSUE THREAD

**Issue by felixwidjaja** [RocketChat/Rocket.Chat#1621]
Hello,

I'm following the guide from https://github.com/RocketChat/Rocket.Chat/wiki . Can anyone teach me how to update/upgrade Rocket to the latest version?
I saw the Update section in https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker but chicken out since I saw some "remove" commend in: docker-compose rm rocketchat

Thanks in advance

**Comment by Sing-Li** [comment]
If you followed those instructions, you would not be running docker-compose in production :smiley: 

In any case, keep mongo up, and follow the update instruction to update the rocketchat server only.  That _should_ work.

**Comment by felixwidjaja** [comment]
Hi Sing-Li,

Sorry wrong URL. I followed this guide: https://github.com/RocketChat/Rocket.Chat/wiki/Docker-Ubuntu-14.04-%2864-bit%29-VPS-with-Nginx-SSL-and-Hubot

Is it wrong?
