### ISSUE TITLE
[IMPROVEMENT] Focus is not on search box of directory component, when user clicks on Directory button

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16216]
### Description:
When you click on "Directory" button on top bar, the focus should be automatically on the search box.
 This will allow users to just start typing for any quick search. I have created this issue to keep the search functionality consistent with the other components of Rocket.Chat

### Steps to reproduce:

1. Click Directory
2. Start typing

### Expected behavior:
For good user experience the focus should be on the search box.

### Actual behavior:
The focus is not on the search box.

### Additional context:
I am working on it.

**Comment by ankar84** [comment]
It is useful improvement!
