### ISSUE TITLE
Password field is rendered as plain text when it is set on some room

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16219]
### Description:
Password is displayed as plain text when a admin/user sets it in some group, discussion etc.

### Steps to reproduce:

1. Go to a channel created by you
2. Edit the channel by clicking the edit option from menu
3. Set a password.

### Expected behavior:
Password should not be visible.

### Actual behavior:
It is visible.

![roompass](https://user-images.githubusercontent.com/43786728/72209999-2fa44b80-34db-11ea-9a8c-6d321fae6294.gif)

### Additional context
I am working on it.

**Comment by ashwaniYDV** [comment]
@ishriom53tyagi I have already mentioned that I am working on it. It is a good practice to mention the issue which you are working on so that other people may know the status. You have made the PR on it. Great! But please follow contributing guidelines :) Cheers!

**Comment by ishriom53tyagi** [comment]
@ashwaniYDV  I am sorry for this, next time I ask for the same.

**Comment by ashwaniYDV** [comment]
> @ashwaniYDV I am sorry for this, next time I ask for the same.

@ishriom53tyagi No need to sorry :) Chill!

**Comment by gabriellsh** [comment]
Guys, this is open source, anyone can contribute, even if there are PRs open. Opening a PR doesn't mean it'll be accepted, so don't take other's opportunity to tackle an issue, please.
