### ISSUE TITLE
No margin in the ui of create new role 

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16212]
### Description:
The create new role page has no margin which makes it inconsistent with the current ui

### Steps to reproduce:

1. Open administration settings
2. Go to permisisons
3. Click on new role

### Expected behavior:
The UI should be consistent

### Actual behavior:

![Selection_015](https://user-images.githubusercontent.com/43509699/72208043-61f67e80-34c4-11ea-9a7a-72b41dc6a78d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0 -develop
- Operating System: ubuntu

### Additional context
I am working on it

**Comment by mariaeduardacunha** [comment]
This issue was fixed as a part of a bigger fix, so this issue can be closed, thank you for taking the time to report this issue!
