### ISSUE TITLE
Weird dropdown ui

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16226]
### Description:

The dropdowns in the administration settings don't have enough padding

### Steps to reproduce:

1. Administration settings
2. Go to any dropdown
3. Click on it

### Expected behavior:
There should be some padding
### Actual behavior:

![image](https://user-images.githubusercontent.com/43509699/72218337-12fe2700-3560-11ea-9afe-bd7117a1bf0d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0 -develop
- Operating System: ubuntu

### Additional context
I am working on it

**Comment by ankar84** [comment]
There is more:
![image](https://user-images.githubusercontent.com/4023037/72233099-4e3b3d00-35d6-11ea-811f-bcda5d6b71f0.png)
![image](https://user-images.githubusercontent.com/4023037/72233105-55624b00-35d6-11ea-99d7-3dfc68ea3c7c.png)
![image](https://user-images.githubusercontent.com/4023037/72233110-5c895900-35d6-11ea-87eb-0e49203cd248.png)
![image](https://user-images.githubusercontent.com/4023037/72233130-7460dd00-35d6-11ea-9a3e-314895763792.png)

**Comment by ritwizsinha** [comment]
Yeah so the dropdown's basic template is flawed

**Comment by ggazzo** [comment]
@ankar84 @ritwizsinha  could you provide which browser both are using?

btw, we are replacing this select

**Comment by ritwizsinha** [comment]
I am using google chrome

Google Chrome | 79.0.3945.88 (Official Build) (64-bit)

**Comment by ggazzo** [comment]
@ankar84 please your browser....

**Comment by ankar84** [comment]
> @ankar84 please your browser....

I think I did that screenshot from RC.Ekectron app version 2.15.5
But now I can check that UI in latest Chrome and on 2.3.4 RC server version.

**Comment by gabriellsh** [comment]
This has been fixed since. If you still face this issue please provide additional details so we can reproduce it. Thanks for the help.
