### ISSUE TITLE
Users often disconnected

### ISSUE THREAD

**Issue by VoidAndAny** [RocketChat/Rocket.Chat#1622]
I installed Rocket.chat in our LAN on a Ubuntu 14.04 LXC container, Rocket Chat is available from WAN through a NGINX reverse proxy which handle SSL.
We use Rocket.chat from website and Mac OS app depending of users.
We are 16 users max and we are often disconnected from rocket.chat
When Rocket chat is accessed through web UI we can see 502 errors.

The server which host LXC container is not specially busy (0,5 / 1 of load average, 4GB of free RAM)
Can we check something ?
Can Rocket Chat installation be optimized ? (hidden parameter somewhere, network configuration, I don't know)

Thanks a lot.

**Comment by engelgabriel** [comment]
please share the json response of you `/api/info` ?

**Comment by VoidAndAny** [comment]
Sorry, but how to do that ?
Just adding /api/info to my Rocket Chat URL ?

The GET info call return HTML (Firebug console) containing this (excerpt) : 
```
<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease
%22%3A%22METEOR%401.2.1%22%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fclavardage
.mydomain.fr%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22accountsConfigCalled%22%3Atrue%2C%22autoupdateVersion
%22%3A%22843422b651782a9716d1921b531f5f836b2c545a%22%2C%22autoupdateVersionRefreshable%22%3A%222f807f4ce334e8677812d8305d36ef60862e5303
%22%2C%22autoupdateVersionCordova%22%3A%2217390d8b0708758f2a0806fac5cffc0450fa891a%22%7D"));</script
>
```

Is it what you need ?

**Comment by engelgabriel** [comment]
This must be a very old version :)

**Comment by engelgabriel** [comment]
Should be something like: https://demo.rocket.chat/api/info

```json
{
  "version": "0.8.0",
  "compile": {
    "date": "2015-12-10T13:56:44.030Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-52-generic",
    "totalMemmory": 8373084160,
    "freeMemmory": 241123328,
    "cpus": 4
  },
  "commit": {
    "hash": "c3cfb051e8e8fabe4449ed4505dfc8f169813159",
    "date": "Thu Dec 10 11:42:51 2015 -0200",
    "author": "Marcelo Schmidt",
    "subject": "Fixes issue #1619 persistent custom oauth."
  },
  "tag": "v0.8.0",
  "branch": "develop"
}
```

**Comment by VoidAndAny** [comment]
Argh
I installed Rocket chat the 25/11/2015, using this instruction https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker (before they change).
So I download Rocket Chat with URL : https://github.com/RocketChat/Rocket.Chat/archive/master.tar.gz

I will try to update my installation.

**Comment by VoidAndAny** [comment]
Update done (develop version), here is the json : 
```
{
  "version": "0.8.0",
  "compile": {
    "date": "2015-12-10T21:15:22.554Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 5086568448,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2579",
    "branch": "develop",
    "tag": ""
  },
  "commit": {
    "hash": "3bb885ae17dc6d02b5c4c005c0e23e271660ff89",
    "date": "Thu Dec 10 19:04:12 2015 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1626 from fduraibi/patch-10"
  },
  "tag": "v0.8.0",
  "branch": "HEAD"
}
```

Apparently, I still have disconnection (3 since the update)

**Comment by Againstreality** [comment]
same here. version is the same

**Comment by marceloschmidt** [comment]
Is your instance running as a Replica Set? Does anything show up on developer console when users are disconnected? Is your server on a public accessible URL we could join to test also? Thanks.

**Comment by VoidAndAny** [comment]
No it isn't possible our Rocket chat instance is connected on our company LDAP...
By the way since the update, it seems that the connection is really really more stable.

Only thing I often have the Rocket "gif" over the channel, what does it mean ?

**Comment by VoidAndAny** [comment]
One more thing, it seems disconnection occurs always just after file upload.

**Comment by engelgabriel** [comment]
Thanks for the info @VoidAndAny , this helps.

**Comment by tpetrosy** [comment]
Is this case related with this one ? https://github.com/RocketChat/Rocket.Chat/issues/1491

**Comment by engelgabriel** [comment]
I dont think so @tpetrosy 

I seems to be a "flood" of requests to the DB and its OpLog after upload... the first thing to test this hypothesis would be to move the file storage to the filesystem or S3.

We will do that soon.

**Comment by engelgabriel** [comment]
This depends on #369

**Comment by engelgabriel** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/commit/1e83b4d200f0ac5d6a303c407e004c439ae2890d
