### ISSUE TITLE
Feature-Request: More directly seeable options for posts (beside emojis) in Browser view

### ISSUE THREAD

**Issue by mespotine** [RocketChat/Rocket.Chat#16228]
I often stumble over the problem, that using threads in RChat is quite inconvenient.

I usually use RChat in browser and when I try to edit, thread, quote, I often have to use the ...-options-menu, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/4251851/72222374-4b9fff80-3564-11ea-8729-048e2d760b80.png)

I would love to have the option to show somehow additional "buttons" beside the emoji button, like "edit", "reply as thread" and "quote" as they are probably the most commonly needed ones in every day's life.

This is also one of the main problems in our RChat-instance, that, especially new users, don't use threads as they never look into the additional options and therefore not know, that these exist.
Even though, I could tell them RTFM, I think having these additional buttons would make using RChat much more intuitive to these users.
As I said, having this as option would be nice, preferably in the settings for my personal taste, with the option for the administrator to globally enable this as default.

Thank you :)

Edit: I noticed, that the create-issue-option here "Feature Request" is missing, so I used "Bug Report". Maybe adding that would be cool as well, including a small template.

**Comment by ggazzo** [comment]
@mespotine what version of rocket.chat are you using, we inserted the reply on thread as you mentioned 
![image](https://user-images.githubusercontent.com/5263975/72345558-d858d380-36b2-11ea-928c-2c7a6391f1c9.png)

**Comment by mespotine** [comment]
2.3.1 via Snap.

Is there an option, I have missed to turn that feature on?

**Comment by mespotine** [comment]
Ok, it's now there, after the update. So I close this issue.

Thanks :)
