### ISSUE TITLE
[BUG] Can't set "Show Read Receipts" on version 2.4.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16229]
### Description:
When try to turn on **Show Read Receipts** option in **Message** section of **Administration** all message page is disapeared.

### Steps to reproduce:

1.  Go to **Administration**
2. Go to **Message**
3. Click on **Show Read Receipts** to enable it

### Expected behavior:

**Show Read Receipts** sets to **True**

### Actual behavior:
![Show_read](https://user-images.githubusercontent.com/4023037/72233937-416d1800-35db-11ea-818b-74e664728829.gif)
### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: CentOS 7
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: 2.15.5 and Chrome 78.0.3904.87
- Operating System: Windows 10

**Comment by aviral243** [comment]
I am looking into this.

**Comment by sampaiodiego** [comment]
This has been fixed in version 2.4.2 https://github.com/RocketChat/Rocket.Chat/releases/tag/2.4.2 .. More specifically on https://github.com/RocketChat/Rocket.Chat/pull/16147

**Comment by ankar84** [comment]
@sampaiodiego I can't confirm fix:
![unread2](https://user-images.githubusercontent.com/4023037/73230402-2af3be80-418e-11ea-8afd-6d356af0cf45.gif)

**Comment by ankar84** [comment]
I confirm fix!
Good job!
