### ISSUE TITLE
[BUG] enable google-vision in branch master

### ISSUE THREAD

**Issue by pkonnov** [RocketChat/Rocket.Chat#16239]
### Description:

I'm trying to turn on google-vision in admins panel

### Steps to reproduce:

1. Go to http://127.0.0.1:3000/admin/FileUpload
2. Turn on Storage Type to Google Cloud Storage
3. In google-vision click turn on

### Expected behavior:

Field with settings google-vision do not hidden

### Actual behavior:

[bug screen](https://lh3.googleusercontent.com/3hpy7KNU-khRodkUyISxBLiskdzkWmBUwOmbucK0fGVtgmOWLLdednjclIpw3YdxCzqAOnUYyTAGAAFtBu8B50TG09vEjj6LsTPfDieIICgdccUdbccBqn7pbZzw6IQ0N6kPnZylU3fHBpFm_J0WyB9RBpCYlB4aQ3cPBiE4NrZbzZc2vWoZwbkSCvxsKglRTF4V0o9cInaSo95v2q0PdZq1g8lP2pDcv5kuvffaxbkWAzlAoiQLeVebt28EIfIhpJZ11b00K6cOPBlp7eE_0OW8AmdS6HhylsaX2CHft1M-tgUvU4gv1BeCWpMpdcP6zTjMQfhHUkKSClcC_KSaLFN59FKM2yPLwr7w78MYBUDM2q8bkGcl266he5Dnh2yXH9JsmaWi2jN1kwQJXEWoc9W8OK58vGfZcAF9-YCgcEX4Sl3M2o0IRKiNScPn6y_eWe5RecaA_lOfOVNQ_eNHGmOmr6-3SflHeXFpSdjbXYHklfk0e0fdAVwfOgEtwnJK3z6AI92UTib-ecGveVmVsvSbHmw1ba8b5w6K_cjMFypKTPyxh1F7ZQkhNhOszYVazv-EszUf7pgOZmtIvt4SZohJIGSASoFbnjczFAkJ1S65qynE12BKVBL_8A8wz_CRRKSfQ_T0UF0Ix7q4c3zcleHg27eRtHlP-PbTEI7ZeIaPHqxRtCpF=w764-h921-no)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1
- Operating System: linux
- Deployment Method: https://releases.rocket.chat/2.4.1
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.17.0 - x64
- MongoDB Version: 4.0.6 

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Version 79.0.3945.117 (Official build), (64 bit)
- Operating System: Linux 5.0.0-37-generic 40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gabriellsh** [comment]
I tested and could enable google vision in 2.5.0-develop. Could you test again or maybe be a little more specific about what is going on?

Maybe try also changing storage to google cloud and saving, refreshing the page and see if it is still selected, then turn google vision on.

**Comment by spermspace** [comment]
@gabriellsh I noticed this problem with many checkboxes. But there is no problem on the master branch

**Comment by gabriellsh** [comment]
@pkonnov Sorry if I'm misunderstanding, but is it fixed then?

**Comment by pkonnov** [comment]
@gabriellsh yes)
