### ISSUE TITLE
Ability to give customer survey/feedback opportunity follwing the livechat session

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#1624]
![screen shot 2014-12-04 at 16 44 58](https://cloud.githubusercontent.com/assets/1000217/11723824/71aa4322-9f57-11e5-9971-640494bafc64.png)
![screen shot 2014-12-04 at 16 45 12](https://cloud.githubusercontent.com/assets/1000217/11723822/71a5b49c-9f57-11e5-962c-53a82d4edbb7.png)
![screen shot 2014-12-04 at 16 45 29](https://cloud.githubusercontent.com/assets/1000217/11723823/71a62c88-9f57-11e5-8d60-703bb97cce16.png)
![screen shot 2014-12-04 at 16 45 35](https://cloud.githubusercontent.com/assets/1000217/11723821/719fd4a0-9f57-11e5-9de3-5fb0d8de2ab8.png)
![screen shot 2014-12-04 at 16 45 44](https://cloud.githubusercontent.com/assets/1000217/11723820/719f287a-9f57-11e5-825f-fb69ba13a58f.png)

**Comment by sampaiodiego** [comment]
closed by #1641
