### ISSUE TITLE
2.4.0 : Create invite link not working as channel owner

### ISSUE THREAD

**Issue by menardorama** [RocketChat/Rocket.Chat#16242]
Steps to reproduce : 
- Create a new channel
- Create an invite link

Debug output
`
server.js:204 Meteor ➔ method roomNameExists -> userId: BTHTzcHhhguXpXpBS, arguments: ["coincoin"]
server.js:204 Meteor ➔ method createPrivateGroup -> userId: BTHTzcHhhguXpXpBS, arguments: ["coincoin",{},false,{},{"broadcast":false,"encrypted":false}]
server.js:204 Integrations ➔ Outgoing WebHook.debug Execute Trigger: roomCreated
server.js:204 Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: roomCreated { event: 'roomCreated',
  owner: { _id: 'BTHTzcHhhguXpXpBS', username: 'xxxxx' },
  room: 
   { name: 'coincoin',
     fname: 'coincoin',
     t: 'p',
     msgs: 0,
     usersCount: 0,
     u: { _id: 'BTHTzcHhhguXpXpBS', username: 'xxxxx' },
     customFields: {},
     broadcast: false,
     encrypted: false,
     ts: 2020-01-14T11:14:54.992Z,
     ro: false,
     sysMes: true,
     v: undefined,
     departmentId: undefined,
     servedBy: undefined,
     closedBy: undefined,
     members: undefined,
     default: false,
     waitingResponse: undefined,
     open: undefined,
     _updatedAt: 2020-01-14T11:14:55.004Z,
     closedAt: undefined,
     lm: undefined,
     _id: 'hvcx9Hq6LaHwper2z' } }
`

`
server.js:204 API ➔ debug POST: /api/v1/findOrCreateInvite
server.js:204 API ➔ debug post findOrCreateInvite threw an error: Error: [not_authorized]
    at findOrCreateInvite (app/invites/server/functions/findOrCreateInvite.js:30:9)
    at Object.post (app/api/server/v1/invites.js:20:18)
    at DDP._CurrentInvocation.withValue (app/api/server/api.js:343:82)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
server.js:204 API ➔ debug Failure { statusCode: 400,
  body: 
   { success: false,
     error: '[not_authorized]',
     stack: undefined,
     errorType: 'not_authorized' } }
`

**Comment by ggazzo** [comment]
@pierre-lehnen-rc 
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/invites/server/functions/findOrCreateInvite.js#L29

missing scope argument

**Comment by pierre-lehnen-rc** [comment]
Already fixed on #16176
