### ISSUE TITLE
BigBluebutton integration doesn't work

### ISSUE THREAD

**Issue by Mystikal57** [RocketChat/Rocket.Chat#16248]
### Description:

BigBluebutton configured and enabled, but isn't working
When i click on start meeting, nothing happened
our BBB server works with moodle very fine

### Steps to reproduce:

1. click on start meeting

### Expected behavior:

open room

### Actual behavior:

nothing happened

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: ubuntu 18.04.6
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 2
- Operating System: windows

### Relevant logs:

Logs:

Exception while invoking method 'bbbJoin' { Error: unable to verify the first certificate     at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)     at emitNone (events.js:106:13)     at TLSSocket.emit (events.js:208:7)     at TLSSocket._finishInit (_tls_wrap.js:643:8)     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } 

**without HTTPS:**

Exception while invoking method 'bbbJoin' { Error: failed [404] <Map><timestamp>1579081799043</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1418/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1418/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1418/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:139:11)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   response:     { statusCode: 404,      content: '<Map><timestamp>1579081799043</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>',      headers:        { server: 'nginx/1.10.3 (Ubuntu)',         date: 'Wed, 15 Jan 2020 09:49:59 GMT',         'content-type': 'application/xml;charset=UTF-8',         'transfer-encoding': 'chunked',         connection: 'close',         'x-application-context': 'application:production:8090' },      data: null } }

**Comment by TheZLabs** [comment]
Having the same issue here. This is the only thing I seemingly cannot get to work with RocketChat. I am using the Greenlight front end for BBB if it matters. BBB works fine on its own as does RocketChat. 

Error Log:

I20200122-03:08:30.215(0) Exception while invoking method 'bbbJoin' { Error: failed [404] <Map><timestamp>1579662510114</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:139:11)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   response:     { statusCode: 404,      content: '<Map><timestamp>1579662510114</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>',      headers:        { server: 'nginx/1.10.3 (Ubuntu)',         date: 'Wed, 22 Jan 2020 03:08:30 GMT',         'content-type': 'application/xml;charset=UTF-8',         'transfer-encoding': 'chunked',         connection: 'close',         'x-application-context': 'application:production:8090' },      data: null } } 
I20200122-03:08:33.500(0) Exception while invoking method 'bbbJoin' { Error: failed [404] <Map><timestamp>1579662513454</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:139:11)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   response:     { statusCode: 404,      content: '<Map><timestamp>1579662513454</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>',      headers:        { server: 'nginx/1.10.3 (Ubuntu)',         date: 'Wed, 22 Jan 2020 03:08:33 GMT',         'content-type': 'application/xml;charset=UTF-8',         'transfer-encoding': 'chunked',         connection: 'close',         'x-application-context': 'application:production:8090' },      data: null } } 
I20200122-03:08:41.903(0) Exception while invoking method 'bbbJoin' { Error: failed [404] <Map><timestamp>1579662521841</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1420/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:139:11)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   response:     { statusCode: 404,      content: '<Map><timestamp>1579662521841</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>',      headers:        { server: 'nginx/1.10.3 (Ubuntu)',         date: 'Wed, 22 Jan 2020 03:08:41 GMT',         'content-type': 'application/xml;charset=UTF-8',         'transfer-encoding': 'chunked',         connection: 'close',         'x-application-context': 'application:production:8090' },      data: null } }

**Comment by einhirn** [comment]
You probably need to install "bbb-webhooks" on your BBB-Server. That's why you get a 404 error.

**Comment by q16marvin** [comment]
Hi, did someone fixed it? i got the same:

`Apr 03 19:14:24 rocketchat rocketchat-server.rocketchat-server[2292]: Exception while invoking method 'bbbJoin' { Error: unable to verify the first certificate
Apr 03 19:14:24 rocketchat rocketchat-server.rocketchat-server[2292]:     at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
Apr 03 19:14:24 rocketchat rocketchat-server.rocketchat-server[2292]:     at emitNone (events.js:106:13)
Apr 03 19:14:24 rocketchat rocketchat-server.rocketchat-server[2292]:     at TLSSocket.emit (events.js:208:7)
Apr 03 19:14:24 rocketchat rocketchat-server.rocketchat-server[2292]:     at TLSSocket._finishInit (_tls_wrap.js:643:8)
Apr 03 19:14:24 rocketchat rocketchat-server.rocketchat-server[2292]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
`

**Comment by karthikindia** [comment]
i am getting the same error too
any one solved this ?

**Comment by karthikindia** [comment]
I got this error fixed, when realized that web hooks are needed to installed for BBB

After running

sudo apt-get install bbb-webhooks

on my BBB installation, I was able to start a Video Conference in Rocket Chat

also the url in the rocket chat should be this - https://pix.cobrasoftwares.org/images/2020/04/06/bbberror-fixed.png

**Comment by q16marvin** [comment]
okay i got it... this error message is confusing ^^ however my routing was wrong... now i can start a bbb session... is there a way to start in a extra window?

**Comment by einhirn** [comment]
Not as of yet. You can just "right-click -> this frame -> open in new tab/window" on the "Do you want to use your microphone or just listen"-dialogue...

**Comment by Askotion** [comment]
RocketChat is still giving me an 404 error after installing bbb-webhooks. 

` </html>nter>nginx/1.10.3 (Ubuntu)</center>oking method 'bbbJoin' Error: failed [404] <html>
rocketchat_1          |     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
rocketchat_1          |     at Request._callback (packages/http.js:140:24)
rocketchat_1          |     at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
rocketchat_1          |     at Request.emit (events.js:311:20)
rocketchat_1          |     at Request.EventEmitter.emit (domain.js:482:12)
rocketchat_1          |     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
rocketchat_1          |     at Request.emit (events.js:311:20)
rocketchat_1          |     at Request.EventEmitter.emit (domain.js:482:12)
rocketchat_1          |     at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
rocketchat_1          |     at Object.onceWrapper (events.js:417:28)
rocketchat_1          |     at IncomingMessage.emit (events.js:323:22)
rocketchat_1          |     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
rocketchat_1          |     at endReadableNT (_stream_readable.js:1204:12)
rocketchat_1          |     at processTicksAndRejections (internal/process/task_queues.js:84:21)`

Is there any other solution?

**Comment by einhirn** [comment]
There's a 404 in that error message. Go check your BBB server's nginx logs to see what was asked for Maybe you can figure out what you need to change to make it work, then.

**Comment by Askotion** [comment]
@einhirn So i used the bash script installer to install it on a whole new server and there it worked fine! So i guess i did something wrong with my manual installation.
So one thing that doesnt seem to work is the screensharing. It does nothing when i click the button.

**Comment by einhirn** [comment]
Right, that's why this issue exists.

**Comment by Askotion** [comment]
@einhirn But that only works in browser doesn't it? Im using the App for mac. Microphone is working great.

**Comment by TheZLabs** [comment]
So I installed webhooks on the bbb server and added the proper information on Rocketchat side for secret, etc. I then ran into a permission issue when trying to launch which was resolved by editing permissions to initiate a call. BBB now launches for me.

**Comment by ali-alhaidary** [comment]
Had the same issue, solved by sudo apt-get install bbb-webhooks
It should be stated in the BigBlueButton configuration that bbb-webhooks should be installed as it is not installed by default
