### ISSUE TITLE
無法登入

### ISSUE THREAD

**Issue by asdfg20905** [RocketChat/Rocket.Chat#16245]
After download login failed

Cannot log in with the original account

Change the password too

Verify phone and mailbox still can't login normally

Web page display [Oops, an error occurred.]

Phone display [challenge_required]

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
