### ISSUE TITLE
Why can't I set the topic and favorite the group when I create it via REST 

### ISSUE THREAD

**Issue by smcardle** [RocketChat/Rocket.Chat#16257]
Hi.

Why do the REST API's seem to lack the ability to set multiple values at the same time ?

For instance, I first need to create a group using /api/v1/group.create
I then need to use /api/rooms.favorite to favorite the room ?? But wait.... wasn't it a "group" I just created ???
Still, the DB just has rooms anyway !!!

After these steps I then want to set the topic so I call /api/v1/rooms.setTopic

That's three separate  REST end points that need to be called here... That's just madness.

Why can't I just create the room and pass any parameter that can be set in the same create POST body ???

**Comment by gabriellsh** [comment]
You opened this issue already, and I moved it to https://github.com/RocketChat/feature-requests/issues/273. Please, don't open duplicate issues, it only slows them down.
