### ISSUE TITLE
Integrate in-line forms to chat.

### ISSUE THREAD

**Issue by mindey** [RocketChat/Rocket.Chat#16267]
In Telegram messenger, in-line forms enables us to interact with users by letting them click buttons and fill out consecutive forms. We would like this capability in RocketChat, to be able to fill out in-line forms directly in the chats.

For example, a use-case would be bot surveys, or in-chat payments and invoicing directly as part of chat (like in WeChat messenger).

Given in-line forms capability, those features could easily be implemented as in-chat form plugins.

**Comment by lorek123** [comment]
This will be done via UIKit, which is right now in development.
