### ISSUE TITLE
Invite user to channel with API.

### ISSUE THREAD

**Issue by Khodesaeed** [RocketChat/Rocket.Chat#16260]
I want to automate adding user into rocket.chat with ansible, and i need to work with API or ansible instead for create and send welcome message  to new user i used rocket.chat API.
the  [`/api/v1/channels.invite`](https://rocket.chat/docs/developer-guides/rest-api/channels/invite/) only gets `roomId` and `userId`, its bring more compexity is there any API that gets username and room name for adding user to channel or private group?

**Comment by MarcosSpessatto** [comment]
@Khodesaeed did you try send roomName and username instead roomId and userId? Actually the endpoint support the roomName and username.

**Comment by Khodesaeed** [comment]
@MarcosSpessatto sry for my late response, thank you by the way, the API dosnt work with username and room name, i had to get the ids before adding user to room...
