### ISSUE TITLE
Offline Email Notifications are sent during the user is away but connected

### ISSUE THREAD

**Issue by tmatthaeus** [RocketChat/Rocket.Chat#16272]
### Description:

User is connected to Rocket.Chat and the user status was set automatically to away after the idle time is reached. User got a new direct message, now a email notification is sent to the user. Offline Email Notifications is set to "Every Mention/DM". 

Regarding to the documentation < https://rocket.chat/docs/administrator-guides/notifications/ > the user should not receive an email. Because he is connected, just away.

### Steps to reproduce:

1. Login to Rocket.Chat with two users, let one of this users reach the idle time. The user status changed to away
2. Use the second user to send a message to the first one, who is away

### Expected behavior:

There should be no email in the inbox of the user who is connected and has the status away

### Actual behavior:

User will receive an email notification about new messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1
- Operating System: Linux Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 8.17
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Desktop App, Version 2.17.2
- Operating System: macOS Cataline

**Comment by sampaiodiego** [comment]
although this issue is older, since https://github.com/RocketChat/Rocket.Chat/issues/17492 had more attraction, I'll be closing this as duplicated. let's keep the conversation at https://github.com/RocketChat/Rocket.Chat/issues/17492 .. thx
