### ISSUE TITLE
Sending a message should scroll to the lastest message

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16278]
### Description:

Currently, when a user writes a message the room messages stay there. It would be better after the message is entered the message list jumps to the current typed message

### Steps to reproduce:

1. Write a message 
2. Enter the message
3. The message list stays there

### Expected behavior:

The message list should move to the currently entered message

### Actual behavior:

![out](https://user-images.githubusercontent.com/43509699/72666819-b016ff00-3a3b-11ea-93ba-fe4dd561275c.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0 develop
- Operating System: ubuntu

**Comment by ritwizsinha** [comment]
@MartinSchoeler could you please guide me on how to proceed

**Comment by ritwizsinha** [comment]
@MartinSchoeler please review

**Comment by vipulsaraf** [comment]
Can I work on this issue, As it is not assigned to anybody .

**Comment by ashwaniYDV** [comment]
@ritwizsinha I think this will be more precise solution to this issue since send ToBottom is already defined. So we can use that function instead of creating new reacting vars and checks.
