### ISSUE TITLE
Image uploads (thumbnails) out of threads are not visible in regular message view 

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#16276]
### Description:

If you upload a image into a thread, the image is only visible in the left thread sidebar when certain thread is currently opened. In the main conversation view there is just an empty message without any thumbnail or indicator that there should be an image embedded.

#### Thread view

<img width="383" alt="Bildschirmfoto 2020-01-18 um 09 18 19" src="https://user-images.githubusercontent.com/944459/72663648-c8ebca00-39d3-11ea-96cd-9b31f8fd6a22.png">

#### Main conversation view

<img width="742" alt="Bildschirmfoto 2020-01-18 um 09 18 29" src="https://user-images.githubusercontent.com/944459/72663654-d3a65f00-39d3-11ea-9a5b-a21023abcf36.png">

### Steps to reproduce:

1. Go to an channel and find an existing thread
2. Upload an image into the thread
3. Notice how it's missing in the main conversation view

### Expected behavior:

There should be should be some kind of indicator that there was an image uploaded. 

### Actual behavior:

Just an empty message / placeholder

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Yes
- NodeJS Version: Docker
- MongoDB Version: Docker

**Comment by ritwizsinha** [comment]
I am working on this, @frdmn could you please point me to the relevant files

**Comment by gabriellsh** [comment]
If you downgrade to older versions of rocket.chat, thread messages with images just show the users name. I guess we could make it so that when someone replies to a thread with an image it says "username Sent an Image" or something like that?

**Comment by ritwizsinha** [comment]
We could also add the image description or name

**Comment by McpCyber** [comment]
i have the same issue , but when i logout from rockectchat and login again , thumbnail are displayed...

**Comment by localguru** [comment]
Some problem on server version 2.4.2.

**Comment by ashwaniYDV** [comment]
@gabriellsh There was a simple true/false mismatch :) Would you please review
