### ISSUE TITLE
Rocket Chat Livechat Plugin error

### ISSUE THREAD

**Issue by ednamaeG** [RocketChat/Rocket.Chat#16270]
**Problem description:**
Rocketchat gives livechat plugin error when building it from source using Windows and meteor npm start command

**Steps to Reproduce**
 - Clone repo from github
- open project
- run meteor npm install
- run meteor npm start
![image](https://user-images.githubusercontent.com/49261930/72589599-abb4ee00-3936-11ea-9623-0acb7431c05a.png)

**Comment by wabbit187** [comment]
could you try running the .bat files without directories that include spaces like "...\Edna Mae....
