### ISSUE TITLE
Ability to go to Home page

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1628]
Is there a way to have a button to take you back to home page vs logging out? 
goal is to make home page sort of a dashboard, trending messages, embeded video, welcome message, social media, list of available rooms (clickable) etc.  
##

**Comment by marceloschmidt** [comment]
I don't see why not... As long as you'll be doing dashboards, trending messages and all of this, I think you could include that button as part of your PR. Thanks.

**Comment by IQ2022** [comment]
Thanks,

would love to include one day something like this.. https://wrapbootstrap.com/theme/origin-admin-webapp-dashboard-WB08N77TC

**Comment by maxlinux2000** [comment]
+1

**Comment by alexmsierra** [comment]
+1

**Comment by OrdinaryGuy** [comment]
Wouldn't it be practical to make logo clickable with the link to homepage?
I caught myself clicking it several time)

**Comment by jbarrere** [comment]
@OrdinaryGuy, just add a link in the Side Navigation Footer
`<a href="/home"><img style="left: 10px; position: absolute;" src="/assets/logo.png" /></a>`

**Comment by marceloschmidt** [comment]
Let's add a "home" link to the three dots menu. If the menu is not available, use an icon to go to "home"

**Comment by JanZerebecki** [comment]
Adding it to the 3-dots-menu would be inconsistent, as that is all for the context of the currently open channel. An incon in the list of icons that also has the one that goes to the directory would not have that inconsistency.

**Comment by gabriellsh** [comment]
This was added on #9366 (Weirdly, one day off to exactly 2 years ago). Just click the logo at the bottom left of the screen:

![image](https://user-images.githubusercontent.com/40830821/71980518-021b8180-31ff-11ea-9e71-052f6ecb996d.png)

Anyway, if ever need be, just reopen this issue.
