### ISSUE TITLE
In threads sending a message should scroll to latest thread message

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16280]
### Description:
In threads the new messages are not automatically previed if the chat becomes more than the display area. It is lacking auto scroll behaviour

### Steps to reproduce:

1. Create a new thread or reply in an existing thread
2. Just make the chat long

### Expected behavior:
Like the normal message area it should automatically scroll to bottom.

### Actual behavior:
It is not automatically scrolling to bottom

![asasasasa](https://user-images.githubusercontent.com/43786728/72680075-aa70f600-3adb-11ea-8045-01e5de741eac.gif)

### Additional context:
I am working on it

**Comment by vipulsaraf** [comment]
,Can i work on this issue as it is not assigned to anybody and i am interested to solve  this issue.

**Comment by ashwaniYDV** [comment]
> ,Can i work on this issue as it is not assigned to anybody and i am interested to solve this issue.

@vipulsaraf I have already made the Pull Request :)

**Comment by vipulsaraf** [comment]
Okkk okkk

**Comment by gabriellsh** [comment]
@vipulsaraf You can work on anything, even if someone is assigned or there is already a pull request. In the end what matters is to collaborate in any way you can :D
