### ISSUE TITLE
[BUG] Comma containting phrases are not supported correctly in user preferences highlight

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16282]
### Description:
We are supposed to highlight words and phrases seperated by [enter] click. But it may contain commas in the phrases. So the criteria to seperate words and phrases should be [enter] key (or new line)

### Steps to reproduce:

1. Go to user preferences
2. Add some phrases containing commas

### Expected behavior:
Eg. `Hey, how are you` should highlight the full phrase

### Actual behavior:
`Hey` and `how are you` are highlighted seperately

**Comment by engelgabriel** [comment]
Hi, @ashwaniYDV 

I understand your description of the issue, but I am not sure I am convinced this is a real use case. I believe more people would prefer to be able to list the highlight words with a comma, than people wanting to add a highlighted string that contains a comma.

I'll close the issue for now, as we think that the current behavior is correct. Please reopen with an example of a real use case if you think we should reevaluate this decision.

Regards,

Gab
