### ISSUE TITLE
MMAPv1 is removed in mongodb 4.2 + mongodb 4.0 cannot be installed on Debian Buster = No Rocket.Chat on Buster possible

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [RocketChat/Rocket.Chat#16285]
This is the first time me trying to install this or use Rocket.Chat or use MongoDB, but I'm familiar with Linux and I'm a developer. Please excuse me if something I did down there is very wrong.

### Description:

It's basically not possible to install Rocket.Chat on Debian Buster. The instructions that I used [from here](https://rocket.chat/docs/installation/manual-installation/debian/) do not work on Debian Buster. If I follow these instructions, I arrive at this error:
```
 mongodb-org-server : Depends: libcurl3 (>= 7.16.2) but it is not installable
```
On the other hand, if I try to install the appropriate version of mongodb, I get the error on start:
```
 exception in initAndListen: Location18656: Cannot start server with an unknown storage engine: mmapv1, terminating
```
### Steps to reproduce:

1. Follow the instructions given [here](https://rocket.chat/docs/installation/manual-installation/debian/)
2. Realize that you can't install MongoDB 4.0 on Debian Buster.
3. Try to install 4.2, then realize you can't run with the engine mmapv1. The page there from Rocket.Chat says that mmapv1 is required.

- Version of Rocket.Chat Server: 
- Operating System: Debian Stretch (10.2)
- Deployment Method: From [here](https://rocket.chat/docs/installation/manual-installation/debian/)
- Number of Running Instances: 1
- NodeJS Version: 12.x
- MongoDB Version: 4.0 and 4.2, both don't work for the reasons explained up there.

**Comment by Gummikavalier** [comment]
We've been running Mongo 3.6 using wiredTiger since last summer without noticeable problems, so I think it should be good.

But good point anyway. WiredTiger should be officially supported since MMAPv1 is being phased out.

**Comment by TheQuantumPhysicist** [comment]
Are there instructions on how to use WiredTiger on Debian Buster to install MongoDB and Rocket Chat?

**Comment by Gummikavalier** [comment]
I'm not very familiar with Debian, but I'd assume that MongoDB 3.2 and onwards would be set up to use wiredTiger engine on it by default, as is mentioned here in official Mongo docs:
https://docs.mongodb.com/manual/core/storage-engines/

MongoDB docs have also instructions how to change engine to wiredTiger here:
https://docs.mongodb.com/manual/tutorial/change-standalone-wiredtiger/

Regarding Rocket.Chat itself, our installations and one that I made just recently directly on top of Mongo 3.6 did not require any special steps regarding engine. I just used the default what was provided. So I did not do any changes in mongod.conf regarding engine part in it; all engine options are commented out. I added only replication/replicationset part, and checked that DB port and that it listens only in localhost 127.0.0.1.

(During the start RC mentions that DB engine is wiredTiger and also admin info page says the same.)

**Comment by northway** [comment]
We've been running MongoDB 4.0 with WiredTiger, so far so good. We've been using WiredTiger since MongoDB 3.2 came out without noticeable problems.

On the other hand, you still have use Debian Stretch for MongoDB 4.0. The folks at MongoDB are very inflexible when it comes to supported Linux Distributions.

**Comment by TheQuantumPhysicist** [comment]
@northway All my servers use Debian Buster. I moved on from stretch a long time ago. I think RocketChat should provide something within the tutorial for installation to solve this problem.

**Comment by nicexe2e4** [comment]
Just use WiredTiger. It works. The mongodb documentation says how. It does not depend on your operating system, the database works the same in all environments.
