### ISSUE TITLE
I am not able to import any react native library

### ISSUE THREAD

**Issue by anjanaNewput** [RocketChat/Rocket.Chat#16283]
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[34], "react-native-tts").Tts')

**Comment by anjanaNewput** [comment]
@ggazzo I don't get solution yet, Why are you closing this.

**Comment by ggazzo** [comment]
Because the issue doesn't follow the templates issues, it's hard to understand and I'm quite sure its on the wrong repo,but feel free to open again, sorry...
