### ISSUE TITLE
Android push notifications are not being recieved

### ISSUE THREAD

**Issue by tonymmm1** [RocketChat/Rocket.Chat#16295]
### Description: 
Android push notifications are not being received and iOS notifications are working. 

### Steps to reproduce:

1. Latest docker-compose setup running behind a traefik reverse proxy running v1.7
2. Latest rocketchat client and rocketchat experimental from google play store

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2 
- Operating System: debian 9
- Deployment Method: docker
- Docker image: rocket.chat:latest
- Docker image digest: sha256:e016b4d9e8fbae30de7050b0654769ca1627b6ffc7c6f71eee59acf6dc9c5e28
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version 4.0.14

### Client Setup Information

- Operating System: Lineage OS 15.1(Android 8.1) with opengapps and play certified device. 

### Additional context
All settings pertaining to push were left to default using the RocketChat gateway.

Android Clients:
- Stable(4.2.3.2099): Not Working
- Experimental(4.2.4.13691): Not Working

iOS Clients:
- Stable(4.2.3): Working

**Comment by apaarfus** [comment]
As far as I know, we're not seeing that in our deployment; however, I did notice the official/stable android client isn't pushing notifications.

### Server Setup Information
* Version of RC Server: 2.4.2
* OS: CentOS 7
* Deployment Method: Manual Install
* Push Settings: Default, using RC Gateway
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* NodeJS Version: v8.11.4
* MongoDB Version 4.0.14

### Client Setup Information
* OS: One UI 2.0 (Android 10, 2020-01-01 patch)
* OS Kernel: 4.14.117

### Android Client Information:
* Stable (4.2.3.2099): Not Working
* Experimental (4.2.4.13691): Working

I don't have any iOS devices to test with, so sorry for that lacking of comparison.

**Comment by sampaiodiego** [comment]
is this still an issue? please test with newer rocket.chat server and mobile app versions.

I'll be closing the issue for now.. let me know how it goes so can I can re-open it if still happening.
