### ISSUE TITLE
Existing integrations missing in the Integrations list

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#16296]
### Description:

Depending on screen size, resolution and browser window shape and size, integrations list under admin console does not show all existing integrations.

### Steps to reproduce:

1. Create about 60 inbound and outbound webhooks. Name them logically so that you can spot missing ones easily.
2.  When you have enough integrations, clean up the browser cache, load the site, and check that all integrations are still listed in admin console.
3. Look for especially the name of the last inbound integration name. It should be somewhere in the middle of the list.
4. Try also with different browser window sizes and hopping away from the list between these changes.
5. Also open up some random integration and then go back to list to try to trigger the list to update.
6. Also keep refreshing the browser window.

### Expected behavior:

All integrations should be listed.

### Actual behavior:

Some integrations are missing from the list.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6

### Client Setup Information

At least Chrome, Chromium and Firefox browsers

### Additional information:
This bug has been around at least for a year, but only now I had time to take a closer look at it. It probably affects only instances with lots of integrations.

You can find the integrations IDs, names and other info by running this command directly in the bash shell:
`mongo rocketchat --eval "db.rocketchat_integrations.find({},{'name':1,'_id':1,'type':1,'token':1}).sort({'name':1}).forEach(function(x){print(x.name + \" | Id: \" + x._id + \" | Type: \" + x.type + \" | Token: \" + x.token);})"`

You can edit integration missing from the list by using its ID in the url in browser:
`https://rc.csc.fi/admin/integrations/incoming/[id]`
`https://rc.csc.fi/admin/integrations/outgoing/[id]`

**Comment by ShellyXueHan** [comment]
Having the same issue on the app. Looks like the page for integration does not have proper pagination.

@Gummikavalier for now you could list all integrations with the api: https://rocket.chat/docs/developer-guides/rest-api/integration/list/ with add the `count` query parameter: https://rocket.chat/docs/developer-guides/rest-api/offset-and-count-and-sort-info/

**Comment by Gummikavalier** [comment]
This is likely to have been fixed now in
https://github.com/RocketChat/Rocket.Chat/pull/16838

**Comment by Gummikavalier** [comment]
Updated to RC 3.0.4. The issue seems to be fixed now.

Closing this one.
