### ISSUE TITLE
/api/v1/chat.sendMessage returns error "Cannot read property 'starred' of undefined" when setting the alias attribute

### ISSUE THREAD

**Issue by mlowton** [RocketChat/Rocket.Chat#16291]
### Description:

Sending a chat message returns a 400 http status when including an alias. The issue was noticed following an update on  January 17, 2020.

The api request was working before the update.
The request is successful without the 'alias' attribute.

### Steps to reproduce:
1. Using the api path '/api/v1/chat.sendMessage', send a request body with an alias

### Expected behavior:

The message should be created successfully.

### Actual behavior:

![image](https://user-images.githubusercontent.com/34066209/72738570-db026f80-3b6f-11ea-8fd9-03f316833300.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: 8.17.0
- MongoDB Version: 3.6.14

**Comment by MarcosSpessatto** [comment]
Hi @mlowton, [we implemented](https://github.com/RocketChat/Rocket.Chat/pull/15887) a validation on v2.4.0 to avoid users to impersonate other users. This validation does not allow you to send `alias` or `avatar` properties anymore, unless your user has the `bot` role, or if you set the alias as your own real name.
I opened a PR to update the [docs](https://github.com/RocketChat/docs/pull/1573). I forgot to update the docs before, my bad.

**Comment by mlowton** [comment]
@MarcosSpessatto I understand. However in our app, we needed a way to add an extra meta data to a message and as a hack we were using the alias to do so. Will there be any future updates that allows adding extra info to a message?

**Comment by AndrewLewis83** [comment]
Using this same API, I'm getting this same error without an alias. I'm sending 
`{ "message" : {"msg": msg, "rid": _rid}}`

What is it telling me?

**Comment by sampaiodiego** [comment]
what rocket.chat version @AndrewLewis83 ?

**Comment by AndrewLewis83** [comment]
api/v1

**Comment by sampaiodiego** [comment]
sorry I mean the server version.. what rocket.chat release are you running?

**Comment by AndrewLewis83** [comment]
Sorry about that. I’m checking with our server guy. I probably should have commented on this or deleted it, but I found that I stopped getting the error by using a different roomId. I’m using this api call to send messages in an existing IM. I was trying to use the roomID that the IM belonged to and not the one from the IM.

**Comment by AndrewLewis83** [comment]
I’m no longer getting the error.
