### ISSUE TITLE
Docker RocketChat Push Notification not work on all devices

### ISSUE THREAD

**Issue by volodymyroliinyk** [RocketChat/Rocket.Chat#16292]
-Ubuntu 18.x server
-Nginx
-ssl configured, https works fine
-Docker(RocketChat) latest version
-Push enabled, APN, GCM configured, Gateway disabled, server restarted after each changes
-Google Firebase configured and work fine with another (web app + mobile push notifications)
-web RC + mobile RC(ios , android) configured and work fine but without push notification
-websocket works fine
-RC logs in admin panel shows messages about 'Push' but without Errors + Google Firebase dont seen incoming request for push notifications

How I can solve this problem?

Thanks

**Comment by apaarfus** [comment]
Probably related to #16295.

**Comment by volodymyroliinyk** [comment]
I want migrate installed RC (with configured database) from docker to this server without docker.
Is it possible?
Can I install concrete RC  version and replace empty database with my configured?
How I can do it ?

I think that push notifications not working because it is Docker, and I tried fixed that ,but without good result.

**Comment by apaarfus** [comment]
I don't see a huge red-flag as to why that wouldn't be doable, AFAIK the database contains all of your server's settings, chat logs, etc (by default).  I would making sure the following are configured the same on your Docker instance as on your non-docker instance--though, I'm not a developer of the project, nor do I have Docker to-hand for testing:

* If you're using a non-GridFS storage type for any file uploads, you'll need to ensure this is configured to match on both instances
* If you've uploaded any files (like profile pictures), custom sounds, custom emoji or other non-standard data for your instance to access, these will need the be replicated in the same locations on the non-docker install
* Use the built-in `mongodb` tools to dump and restore your database, respectively.

Finally, you'll need to follow the [manual install documentation](https://rocket.chat/docs/installation/manual-installation/) for your host environment.  If you're using a remote proxy, or any other tools that integrate with RC in some way, you may need to reconfigure them depending on your setup.
