### ISSUE TITLE
Login self-hosted Rocket chat using self-hosted Gitlab.

### ISSUE THREAD

**Issue by linuxserver2016** [RocketChat/Rocket.Chat#16299]
### Steps to reproduce:

1.  On Rocket chat self-hosted version Go to OAuth > Gitlab > enable OAuth for Gitlab (also I do have a Doubt here, My gitlab is self-hosted should I add Custom OAuth or use the built-in one?) I used built-in and provided my self-hosted gitlab URL 
2.  On gitlab I've provided the Callback URL provided by Rocket Chat application, Generated the client Id and Secret ID, 
3.  Provided the Client & Secret ID,   set the identity path to `/api/v4/user` , enable `merge users` options, save the Changes

### Expected behavior:

 login gets successful while login using the Gitlab button enabled on the login page of Rocket chat 

### Actual behavior:

 Gets redirected to Gitlab, shows authorization page, on clicking the authorize, exits by throwing 500 Internal server error.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System:  Centos 7.6
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 10

### Relevant logs:

 
```
Jan 21 10:18:29 localhost rocketchat: {"line":"392","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with gitlab at http://self_hosted_gitlab_URL/oauth/token. failed [401] {\"error\":\"invalid_grant\",\"error_description\":\"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"}","time":{"$date":1579619909584},"level":"warn"}
Jan 21 10:18:30 localhost rocketchat: Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with gitlab at http://self_hosted_gitlab_URL/oauth/token. failed [401] {"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
Jan 21 10:18:30 localhost rocketchat: at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:132:18)
Jan 21 10:18:30 localhost rocketchat: at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:189:26)
Jan 21 10:18:30 localhost rocketchat: at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)
Jan 21 10:18:30 localhost rocketchat: at middleware (packages/oauth/oauth_server.js:161:5)
Jan 21 10:18:30 localhost rocketchat: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 21 10:18:30 localhost rocketchat: message: 'Failed to complete OAuth handshake with gitlab at http://self_hosted_gitlab_URL/oauth/token. failed [401] {"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}',
Jan 21 10:18:30 localhost rocketchat: response:
Jan 21 10:18:30 localhost rocketchat: { statusCode: 401,
Jan 21 10:18:30 localhost rocketchat: content: '{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}',
Jan 21 10:18:30 localhost rocketchat: headers:
Jan 21 10:18:30 localhost rocketchat: { server: 'nginx',
Jan 21 10:18:30 localhost rocketchat: date: 'Tue, 21 Jan 2020 09:47:59 GMT',
Jan 21 10:18:30 localhost rocketchat: 'content-type': 'application/json; charset=utf-8',
Jan 21 10:18:30 localhost rocketchat: 'content-length': '213',
Jan 21 10:18:30 localhost rocketchat: connection: 'close',
Jan 21 10:18:30 localhost rocketchat: 'cache-control': 'no-store',
Jan 21 10:18:30 localhost rocketchat: pragma: 'no-cache',
Jan 21 10:18:30 localhost rocketchat: 'www-authenticate': 'Bearer realm="Doorkeeper", error="invalid_grant", error_description="The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."',
Jan 21 10:18:30 localhost rocketchat: 'x-request-id': 'etKj6800gE2',
Jan 21 10:18:30 localhost rocketchat: 'x-runtime': '0.014029' },
Jan 21 10:18:30 localhost rocketchat: data:
Jan 21 10:18:30 localhost rocketchat: { error: 'invalid_grant',
Jan 21 10:18:30 localhost rocketchat: error_description: 'The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.' } } }

```

**Comment by doremio** [comment]
### Hi!
I have some troubles here too, but my set is a little differ:

Version of Rocket.Chat Server: **2.4.8** running on **Docker**

I've created an application with Redirect URI "https//chatsub-mydomain-com/_oauth/gitlab" in it on 
Gitlab's Applications page. And on Rocket chat side under OAuth > Gitlab section  i've configured  like this:

**Gitlab URL**    "https//gitsub-mydomain-com"
**Gitlab ID**        "Application ID generated by gitlab"
**Client Secret** "Secret generated by gitlab"
**Identity Path**  "/api/v4/user"
**Merge users**  "Disabled"
**GitLab Callback URL** "https//chatsub-mydomain-com/_oauth/gitlab"

And now on login page when i click on gitlab icon this happens
> Gets redirected to Gitlab, shows authorization page, on clicking the authorize, exits by throwing 500 Internal server error.

**Here is my Rocket chat log:**

`W20200210-16:55:21.320(0) (oauth_server.js:392) Error in OAuth Server: Failed to complete OAuth handshake with gitlab at https//gitsub-mydomain-com/oauth/token. connect ECONNREFUSED _web-server-ip_:443
I20200210-16:55:21.749(0) Exception while invoking method 'login' { Error: Failed to complete OAuth handshake with gitlab at https/gitsub-mydomain-com/oauth/token. connect ECONNREFUSED _web-server-ip_:443     at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:132:18)     at Object.OAuth.registerService.query [as handleOauthRequest] (app/custom-oauth/server/custom_oauth_server.js:189:26)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:10:33)     at middleware (packages/oauth/oauth_server.js:161:5)     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40   message: 'Failed to complete OAuth handshake with gitlab at https//gitsub-mydomain-com/oauth/token. connect ECONNREFUSED _web-server-ip_:443' } `

**Comment by doremio** [comment]
Well... I did find out that the reason was about "hairpin nat" issue on my router.
