### ISSUE TITLE
[BUG] Thread quote appear in main channel

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16297]
### Description:

Thread quote appear in main channel, but not in thread.

### Steps to reproduce:

1. Make a channel port
2. Reply to post in Thread
3. Go to Thread
4. Quote any message in Thread
5. Quote appears in Channel, not in Thread

### Expected behavior:

Quote appear in thread, not in main channel

### Actual behavior:
![quote](https://user-images.githubusercontent.com/4023037/72775459-7d2d6080-3c1f-11ea-94c0-6a4ad32973fc.gif)
### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: RC.Electron 2.15.5 and Google Chrome 79.0.3945.117 (64 bit)
- Operating System: Windows 10

**Comment by ritwizsinha** [comment]
Related to #16297

**Comment by ankar84** [comment]
Fixed in https://github.com/RocketChat/Rocket.Chat/pull/16925
