### ISSUE TITLE
[BUG] Remove hardcoded texts

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16303]
### Description:
Remove some hardcoded texts.

### Steps to produce:
I noticed it in app/message-attachments/client/messageAttachment.html

### Expected behavior:
It should not be hardcoded.

### Actual behavior:
They are hardcoded.

**Comment by gabriellsh** [comment]
Hey, I see you made the PR for this, but don't forget to follow the [guidelines](https://rocket.chat/docs/contributing/reporting-issues) when opening issues.

Thanks for the contribution!

**Comment by ashwaniYDV** [comment]
@gabriellsh Sure. :)
