### ISSUE TITLE
Frequently Used reactions are lost when closing Firefox

### ISSUE THREAD

**Issue by fabioperrella** [RocketChat/Rocket.Chat#16317]
### Description:

In the previous versions, the "Frequently Used" reactions used to be saved for a long period, but in the last versions, it started to clean when closing Firefox.

### Steps to reproduce:

1. Add a reaction

![image](https://user-images.githubusercontent.com/302303/73010618-7bb39200-3df1-11ea-9c26-19b28edbf998.png)

2. Close Firefox (all tabs)

3. Open Firefox and log into Rocketchat

4. Try to list the "frequently used reactions", they disappeared!

### Expected behavior:

To not lose the "frequently used reactions" when logging in again.

### Actual behavior:

![image](https://user-images.githubusercontent.com/302303/73011232-9b978580-3df2-11ea-962f-a9646007cd69.png)

### Server Setup Information:

![image](https://user-images.githubusercontent.com/302303/73011337-c5e94300-3df2-11ea-892b-038b3c5c76fa.png)

### Client Setup Information

- Desktop App or Browser Version: Firefox 72.0.1
- Operating System: Ubuntu 16.04

### Additional context

I'm using a hosted version of Rocketchat

I'm not using the Firefox option to clean the cookies when Firefox closes:

![image](https://user-images.githubusercontent.com/302303/73011555-385a2300-3df3-11ea-87ac-be4e155f2ca7.png)

**Comment by pmnhaes** [comment]
Same thing with me. I use it on chrome (Version 79.0), but it started about a month ago, so maybe in another version.

**Comment by rafaelbpcrespo** [comment]
It used to works fine for me, but lately it started to happen too. 

I'm using on Chrome (Version 79.0.3945.79).

**Comment by gabrielmsf** [comment]
Same for me, I'm using the desktop application on Ubuntu

**Comment by Wynteres** [comment]
Any news on this? I'm having the same issue with Chrome at Ubuntu

Chrome Version 81.0.4044.138 (Official Build) (64-bit)

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
