### ISSUE TITLE
[BUG] Users can't change Unread Tray Icon Alert setting

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16314]
### Description:
#UI #bug
Users can't change Unread Tray Icon Alert setting

### Steps to reproduce:

1. Go to My Account Preferences
2. Change **Unread Tray Icon Alert** setting

### Expected behavior:

*Unread Tray Icon Alert** setting is changed by User

### Actual behavior:
![unread](https://user-images.githubusercontent.com/4023037/72979328-24112880-3de9-11ea-9f2d-7a134c9b8579.gif)
### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: RC.Electron 2.15.5 and Google Chrome 79.0.3945.117 (64 bit)
- Operating System: Windows 10

**Comment by ishriom53tyagi** [comment]
I am working on this issue

**Comment by ankar84** [comment]
My issue is duplicate of https://github.com/RocketChat/Rocket.Chat/issues/16288

**Comment by gabriellsh** [comment]
Closing, duplicate issue.
