### ISSUE TITLE
Upload 4MB file will "crash" the server

### ISSUE THREAD

**Issue by felixwidjaja** [RocketChat/Rocket.Chat#1631]
Hi guys,

My team usualy exchanges psd around. And here's what I got after transfer a psd (it's just a 4MB file):
![screen-shot-2015-12-11-at-7 26 15-am](https://cloud.githubusercontent.com/assets/4198376/11732644/bd4dcfd4-9fd8-11e5-88e4-d2d746e8d4d4.jpg)

Thanks in advance.

Here's from error log:
```
2015/12/10 19:26:09 [error] 1122#0: *117 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 111.94.80.75, server: xxxxxx, request: "GET /sockjs/info?cb=nll8qafdbu HTTP/1.1", upstream: "http://127.0.0.1:3000/sockjs/info?cb=nll8qafdbu", host: "xxxxxxx", referrer: "xxxxxxx"
```

**Comment by Sing-Li** [comment]
Are you proxying through NGINX?  If so, please check config for websocket timeout.

**Comment by felixwidjaja** [comment]
@Sing-Li thank you.
Should I put 
```
websocket_connect_timeout 7d;
websocket_send_timeout 7d;
websocket_read_timeout 7d;
```
somewhere in:

```
# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

    # HTTPS Server
    server {
        listen 443;
        server_name chat.stucel.com;

        error_log /var/log/nginx/rocketchat.error.log;

        ssl on;
        ssl_certificate /etc/nginx/certificate.crt;
        ssl_certificate_key /etc/nginx/certificate.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

        location / {
            proxy_pass http://chat.stucel.com:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forward-Proto http;
            proxy_set_header X-Nginx-Proxy true;

            proxy_redirect off;
        }
    }
```

?

Sorry I'm beginner.

**Comment by MuhClaren** [comment]
@felixwidjaja Have you edited the value for "Maximum file upload size" in your rocketchat admin panel? 

Admin--> File Upload--> Maximum file upload size (in bytes) 2097152

By default, it's set for 2MB. For 4MB you should change it to 4194304

**Comment by felixwidjaja** [comment]
Yes sir @MuhClaren I put: 200000000 there.
I just changed it to 31457280 (30MB) and the problem stil arise.

**Comment by Sing-Li** [comment]
Time your transfer before it gets cut off.  If it is about 60 seconds, then read this ....  http://nginx.org/en/docs/http/websocket.html   

You'll need something like `proxy_read_timeout 600s;` right after all the `proxy_set_header` stmts.

**Comment by MuhClaren** [comment]
Also maybe try one or more of these:

**Comment by felixwidjaja** [comment]
@Sing-Li the "nginx bad gateway error" comes after 20 seconds file transfer.
That ```proxy_read_timeout 600s;``` didn't help.

Also, is your MongoDB local on a LAN? Or remote and slow <-- local. I'm using 1 droplet at DigitalOcean. The server is speedy. Located in SG. I live in Indonesia. Ping is 50ms.

@MuhClaren I tried them all. But ```websocket_``` prefix command won't pass the ```sudo service nginx configtest```

**Comment by MuhClaren** [comment]
Yeah, sorry, I just read that those directives aren't supported in the current versions.

Usually the "nginx bad gateway" is because nginx is not able to talk to the (chat) backend in this case, which makes sense because it crashed.

Unrelated, but helpful sometimes, is the command:
`nginx -t`
Which makes analysis of your config and tells you where specifically the problem is.

I think Sing-Li is on the right track. I will see if I can replicate your issue on my test machine.

**Comment by MuhClaren** [comment]
Still trying to replicate the issue. As you may have noticed, I stopped by your chat, created a testing channel, and was able to crash it (sorry) with an image upload of 1.7 MB, but the first upload which was 586KB was successful. On my instances (both docker, and straight meteor) I cannot replicate the crash. Both test platforms are using the same nginx configuration.

Have you modified your nginx.conf file? /etc/nginx/nginx.conf

Are there any errors in the nginx error log aside from the one you posted in your first post?

**Comment by felixwidjaja** [comment]
Hi @MuhClaren can you relogin there? I replied the answers there.

**Comment by felixwidjaja** [comment]
Solved! @MuhClaren tested everything. Even deploy rocketchat in his droplet at DO. What a guy! I can't be more thankful to him.
Anyways, the problem was lack of memory. Was using 512MB. Upgrade to 1GB solved everything.
