### ISSUE TITLE
[BUG] Declining to send a message as an attachment destroys its content

### ISSUE THREAD

**Issue by grzebo** [RocketChat/Rocket.Chat#16312]
### Description:
When a typed message exceeds the length limit, it cannot be sent to a channel. In that case the user sees a pop-up window with a message: "Message too long. Send it as an attachment instead?" When the user accepts - everything works fine. But when user declines (i.e. to shorten the message manually, so it fits within the limit), the entire typed up message disappears and is irretrievably lost.

Since this bug applies only to very long messages (which exceed the limit) - it's extremely annoying.

### Steps to reproduce:

1. Open any channel.
2. Type a long message (longer than the allowed message length).
3. Press [enter] or click "send".
4. A pop up window appears: "Message too long. Send it as an attachment instead? No / Yes"
5. Click "No".
6. The entire message that was typed is gone.

### Expected behavior:
User is returned to the editing window, with full typed text still available, so it can be edited (or copied and saved).

### Actual behavior:
The message is gone and cannot be retrieved. The pop up windows doesn't mention that clicking "No" causes the entire text to be lost.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: 
- Deployment Method: pre-built DigitalOcean instance
- Number of Running Instances: 1 
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.3

### Client Setup Information

- Desktop App or Browser Version: confirmed under latest Chrome and Firefox
- Operating System: Windows 10 and Kubuntu 18.04 LTS

**Comment by ishriom53tyagi** [comment]
I am working on this issue

**Comment by Kayoku** [comment]
Hey. Any news here ? I think it's an important fix because it's very very very **frustrating** like behavior....

**Comment by jazztickets** [comment]
It also gets destroyed (or at least you have to manually decrypt it somehow) if you have E2E enabled and click Yes to make it an attachment.
