### ISSUE TITLE
How to enable whiteboard etherpad functionality

### ISSUE THREAD

**Issue by ugintl** [RocketChat/Rocket.Chat#16316]
I want to enable multi-users whiteboard functionality. How can I enable it?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by ugintl** [comment]
I respect the rules, but I have posted it in the forum and received no reply https://forums.rocket.chat/t/how-to-integrate-whiteboard/5582
