### ISSUE TITLE
[BUG] headerData is null when flexTabBar is rendered

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16326]
### Description:
Header Data is initially null till we click on any of the flexTabBar added butons. The headerData is set from the added buttons to the flexTabBar. But initially it is null. There should be a default headerData for flexTabBar.

### Steps to reproduce:

1. Go to admin secton
2. Click on rooms, users, custom sounds, custom emojis tabs etc. and click on a particular list item

### Expected behavior:
Header Data should be displayed.

### Actual behavior:
![4444](https://user-images.githubusercontent.com/43786728/73113065-b45d8380-3f37-11ea-815c-7aa010c0c385.gif)

### Additional context
I am working on it.

**Comment by MartinSchoeler** [comment]
Hello @ashwaniYDV we just rewritten the admin pages in react, and this issue doesn't happen anymore, if you see this problem again, please open a new issue with updated details. 

Thanks!
