### ISSUE TITLE
Deleting messages that have replies continues to show replies button

### ISSUE THREAD

**Issue by lisa761** [RocketChat/Rocket.Chat#16320]
### Description:
When a message that has replies is deleted, the message is lost but the number of replies continues to be visible. However clicking on this button, the thread channel reproduces no replies. The thread is lost.

### Steps to reproduce:
1. Write a message, and reply to the said message (even a single reply will do).
2. Now delete the message you just replied to.
3. Click on the button that will show number of replies to said removed message.

### Expected behavior:
If the message is deleted, all the replies to it lose context so either they should also be removed or the **number of replies** button should not be visible anymore for the deleted message.

### Actual behavior:

On clicking the **replies** button, the main channel shows nothing.
![ezgif-1-83e2bf2d0f6b](https://user-images.githubusercontent.com/52909743/73056241-900c9300-3eb4-11ea-893c-1c626c12c74b.gif)

### Client Setup Information
- Desktop App or Browser Version: Google Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by gabriellsh** [comment]
@ggazzo @tassoevan Tested, when the page is refreshed, replies become regular messages. Is this intended?

**Comment by lisa761** [comment]
I was wondering how we'd go about this, would it be okay to just remove the button when the corresponding message is deleted or should we delete the entire thread from the database?

**Comment by ritvikjain99** [comment]
@lisa761 I don't think just deleting the button would be a good fix because with time our database would be containing useless messages replies !

**Comment by lisa761** [comment]
@ritvikjain99 yeah I thought so too, but it also comes down to whether it is okay to completely remove the replies without the permission of the user who has written them (If this goes against the policy).

**Comment by engelgabriel** [comment]
@ggazzo is this still the case?

**Comment by ggazzo** [comment]
it is but we are preparing a fix at the rewrite pr
