### ISSUE TITLE
Audio record stop button bug

### ISSUE THREAD

**Issue by meteorplus** [RocketChat/Rocket.Chat#1633]
Hi

I stumlbed upon this small bug,

to reproduce it: make a private channel then start recording then stop then it will ask if you want to upload click cancel.

that's when you will see that the stop button is still there and wasn't changed to record button and you can still stop the empty recording and upload nothing!

Thanks 
##

**Comment by MartinSchoeler** [comment]
@meteorplus I think that issue has already been fixed, if not, please reopen this. Thanks!
