### ISSUE TITLE
Avatars are not browser cache save

### ISSUE THREAD

**Issue by ojsoft** [RocketChat/Rocket.Chat#16334]
### Description:

We set fresh Avatars during login by REST Api and this new Avatar is set correctly, but is not usually not visible to the logged in user, due to fact, that the old image is served from browser cache, because the url doesn't change. This is confusing for users that have deleted their old avatar and do not want to see that one again of course.

### Expected behavior:

If a new avatar gets set by REST API, it should be visible immediately.

### Actual behavior:

The old Avatar is still visible for the profile owner.

### Server Setup Information & Client Setup Information:

all irrelevant, the problem is very well known, as browser cache problem.

### Possible solution

Keep an avatar change counter and make this counter part of the Avatar URL. Like

URL?c=COUNTER

to trick out the browser cache.

**Comment by sampaiodiego** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/17925
