### ISSUE TITLE
[BUG] Unable to send message when press ESCAPE key during message as an attachment pop up arrive

### ISSUE THREAD

**Issue by ishriom53tyagi** [RocketChat/Rocket.Chat#16339]
### Description:

When we tried to send a long message. A window pop up opens said if you wish to send as an attachment if you click yes that's alright
but if you press ESCAPE button and tried to send another Message, Message can't be Send.

### Steps to reproduce:

1.  Go to any channel 
2.  Send a long message
3.  when window pop up seen press ESCAPE Button
4.  Now tried to send Message without refreshing the page

### Expected behavior:

When press ESCAPE bar after that we could be able to send another message.

### Actual behavior:

After pressing the ESCAPE bar we cannot be able to send any message Until we refresh the page.

**Comment by ashwaniYDV** [comment]
@ggazzo Can we please close this issue too as it is fixed now :)
