### ISSUE TITLE
Live Chat Web-Page Button Space / Place

### ISSUE THREAD

**Issue by buschmann** [RocketChat/Rocket.Chat#16342]
The button is exact on the same place where normal on most web pages the "BackToTop" button sit. :(

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
