### ISSUE TITLE
LiveChat config endpoint sends customFields

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#16354]
The `/api/v1/livechat/config` endpoint leaks custom fields. These may contain private, identifiable information about an agent. 

Please remove the custom fields object from the livechat config endpoint, or make it configurable and OFF by default.

**Comment by renatobecker** [comment]
@wreiske Here we will do the same action that we did in the CRM integration.
Please, take a look at https://github.com/RocketChat/Rocket.Chat/pull/16286

**Comment by ashwaniYDV** [comment]
@wreiske I'm not able to reproduce this issue. Can you please help.
I've added custom fileds `http://localhost:3000/livechat-manager/customfields`.
Now when I called the api `/api/v1/livechat/config`, there was no customFileds property.

**Comment by wreiske** [comment]
The custom fields are not the livechat custom fields, they are custom fields on normal users in Rocket.Chat. You'll have to add the custom fields from the admin, not the livechat settings.

**Comment by engelgabriel** [comment]
@renatobecker any updates on this one?

**Comment by renatobecker** [comment]
> @renatobecker any updates on this one?

@engelgabriel I'll work on this issue and I'll make sure that we'll fix it on the next `3.3`.
Thanks for bringing it up.
