### ISSUE TITLE
Textarea for adding custom CSS/JS

### ISSUE THREAD

**Issue by capensisma** [RocketChat/Rocket.Chat#1635]
Hi 

Can we please have a textarea for adding custom CSS/JS i the setting panel ? 

Thanks a lot :)

**Comment by drastik** [comment]
Yes :+1: 

Or just documentation on how to add our own custom file without excessive integration steps required.

**Comment by LeCoupa** [comment]
:+1:

**Comment by agentirons** [comment]
:+1:

**Comment by rankun203** [comment]
How to trigger an auto-login by auto-click on the 3rd-party SSO button?

In my case, I can't get managed to auto-click the 「加入討論」button.

![image](https://cloud.githubusercontent.com/assets/2988555/18408889/ef6afd48-776e-11e6-89ed-410c5809c320.png)
