### ISSUE TITLE
Edited message indicator no longer appears

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#16359]
### Description:
After editing a message, the edited message indicator (little gray pencil) no longer appears, therefore making it looked like an edited message was never edited. Previous edit indicators (for messages edited before install of current build) are not affected.

### Steps to reproduce:

1. Get latest docker build (9054f0d as of this issue report)
2. Make sure **Allow Message Editing** is enabled, and **Show Edited Status** is also enabled.
3. Type a message and submit it.
4. Attempt to edit the message and submit it again.

### Expected behavior:
The edited message indicator should appear to show the message has been edited. I have gone and tried to disable **Show Edited Status** and re-enable it to see if the indicator would come back, but it does not.

### Actual behavior:
No indicator appears:
![Edit indicator](https://user-images.githubusercontent.com/14616851/73299399-bdb74c00-41d4-11ea-90e2-330a13b133d4.gif)

## Rocket.Chat

|                 Version | 2.5.0-develop                    |
| ----------------------: | -------------------------------- |
|     Apps Engine Version | 1.12.0-beta.2452                 |
|      Database Migration | 171                              |
| Database Migration Date | January 27, 2020 9:45 PM         |
|            Installed at | January 25, 2019 5:44 PM         |
|                  Uptime | 13 hours, 39 minutes, 22 seconds |
|           Deployment ID | dwP----aKuHALm6b                |
|                     PID | 1                                |
|       Running Instances | 1                                |
|                   OpLog | Enabled                          |

## Commit

|    Hash | 9054f0dba996d3c2a653756542f374153443a670                     |
| ------: | ------------------------------------------------------------ |
|    Date | Tue Jan 28 05:29:10 2020 +0800                               |
|  Branch | HEAD                                                         |
|     Tag | 2.4.0                                                        |
|  Author | Shiqi Mei                                                    |
| Subject | [NEW] Create a user for the Apps during installation (#15896) |

**Comment by ashwaniYDV** [comment]
I want to work on it.

**Comment by manosriram** [comment]
I want to work on this issue. Will that be okay? @ashwaniYDV @bkraul

**Comment by ashwaniYDV** [comment]
@manosriram Go ahead :+1:
