### ISSUE TITLE
[2.4.2] Account creation and email login/creation possible from IOS/Android App even if it's disable on rocketchat

### ISSUE THREAD

**Issue by menardorama** [RocketChat/Rocket.Chat#16367]
### Description:

On a rocketchat instance we have enabled SAML auth and disable email registration.

This was working fine until... Rocketchat 2.4.0 or Rocketchat client (observed on 4.2.3.2099).

Now on the mobile app we have again the ability to create an account et login using email/password.

On the web interface this option don't appear.

Worse, users are able to create an account and login.

Accessing 
### Steps to reproduce:

1. Rocketchat 2.4
2. IOS or Android App
3. Alternative auth (oauth, SAML)
4. Disable login form
5. Create a login on the mobile app

### Expected behavior:

Even if the mobile app is buggy or customzed, Rocketchat server should enforce security.

### Actual behavior:

Already explained

### Server Setup Information:

- Version of Rocket.Chat Server:  2.4.2
- Operating System: Ubuntu 18.04
- Deployment Method: kubernetes
- Number of Running Instances: 4

### Client Setup Information

- Desktop App or Browser Version: 4.2.3.2099
- Operating System: Android/IOS

**Comment by localguru** [comment]
Did you disable `Accounts / Registration / Registration Form` ?

I can't reproduce the bug on my server, RC 2.4.2 and SAML only.

![grafik](https://user-images.githubusercontent.com/8544984/73399878-4d99ea80-42e8-11ea-8ceb-8a41ba2ab54e.png)

![grafik](https://user-images.githubusercontent.com/8544984/73399540-b3d23d80-42e7-11ea-9810-887d498c0e01.png)

**Comment by localguru** [comment]
@menardorama  Did you check it? If it is just a wrong configuration on your site, please close the ticket. The error you describe is too serious to be left uncommented here.

**Comment by menardorama** [comment]
Hi
I have Checked the settings and it was already configured correctly.

Upgraded to latest minor version and the issue disappeared 

I’ll try to gather some logs and upload them 



Thomas Menard
