### ISSUE TITLE
Folder Upload

### ISSUE THREAD

**Issue by suresh0890** [RocketChat/Rocket.Chat#16366]
I can abel to upload a file with rocket chat. But, how can i upload a folder ( Non zipped )

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
