### ISSUE TITLE
/giphy command stops appearing after some time

### ISSUE THREAD

**Issue by maurice-schleussinger** [RocketChat/Rocket.Chat#16374]
### Description:
See https://github.com/wreiske/Rocket.Chat.App-Giphy/issues/12. Basically, the Giphy command stops being presented to the user after some time (minutes).

### Steps to reproduce:

1. Install Giphy App from the marketplace
2. Enable it
3. Wait some time (5 min to a few hours)
4. Try to use the command

### Expected behavior:

See the command in the command box and autocomplete and be able to use it.

### Actual behavior:

The command doesn't appear.
![image](https://user-images.githubusercontent.com/1615089/73363394-f0cb0f80-42a8-11ea-838b-13b15feaf9ce.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1
- Operating System: CentOS 7.6
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.16

### Client Setup Information

- Desktop App or Browser Version: Any Browser or Desktop App
- Operating System: Any 

### Relevant logs:

**SERVER** (log for the App)
```
debug: 2020-01-29T12:44:32.917Z (Caller: anonymous OR constructor)
[
  "onSettingUpdated is being called..."
]
debug: 2020-01-29T12:44:32.920Z (Caller: anonymous OR constructor)
[
  "'onSettingUpdated' was successfully called! The result is:",
  null
]
```

**BROWSER**
This error appears as the page is loading and is likely unrelated.
```
Error parsing header X-XSS-Protection: 1, 1; mode=block: expected semicolon at character position 2. The default protections will be applied.
```

**Comment by wreiske** [comment]
@maurice-schleussinger is the app getting disabled?

**Comment by robinreinhardt** [comment]
@maurice-schleussinger and i working on the same issue.
The app is still active even if the command no longer works.

**Comment by antgel** [comment]
@robinreinhardt When you say "working" on it, you mean you're investigating and hoping to fix?

**Comment by antgel** [comment]
Weird one here. Last night it was working after initial install, this morning it had stopped, then it started again without any intervention. :man_shrugging:
