### ISSUE TITLE
Zapier integration Error "You are not authorized to change message properties"

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat#16382]
Hi,

All Zapier integrations started returning the error bellow after update to 2.4.2.

  | Rocket.Chat: The app returned "You are not authorized to change message properties". This usually happens when your Zap is missing a required field or a field value isn't in a recognized format.
-- | --

![image](https://user-images.githubusercontent.com/42721509/73444592-2c251700-4359-11ea-9a52-b66239e5c7e0.png)

# RocketChat Setup:

Version | 2.4.2
-- | --
Apps Engine Version | 1.11.0
Database Migration | 170
January 27, 2020 9:41 AM
Database Migration Date | April 10, 2019 2:24 AM
Uptime | 3 days, 1 hours, 31 minutes, 53 seconds
Deployment ID | Jvqn2LLSEkfF36vup
PID | 1
Running Instances | 1
OpLog | Enabled

Hash | d57a64dee62fbf8abff75006903628a1001312ec
-- | --
Date | Fri Jan 17 14:11:10 2020 -0300
Branch | HEAD
Tag | 2.4.2
Author | Diego Sampaio
Subject | Merge pull request #16274 from RocketChat/release-2.4.2

# Logs

```
I20200130-10:53:27.289(0) [OAuth2Server] in getAccessToken (bearerToken: Redacted ) 
I20200130-10:53:28.014(0) [OAuth2Server] POST /oauth/token 
I20200130-10:53:28.016(0) [OAuth2Server] in getClient (clientId: zapier , clientSecret: Redacted ) 
I20200130-10:53:28.024(0) [OAuth2Server] in grantTypeAllowed (clientId: zapier , grantType: refresh_token) 
I20200130-10:53:28.030(0) [OAuth2Server] in getRefreshToken (refreshToken: Redacted) 
I20200130-10:53:28.036(0) [OAuth2Server] in saveAccessToken (token: Redacted , clientId: zapier , user: { id: 'jdZodaFoWrRjPZmeC' } , expires: 2020-01-30T11:53:28.015Z ) 
I20200130-10:53:28.043(0) [OAuth2Server] in saveRefreshToken (token: Redacted , clientId: zapier , user: { id: 'jdZodaFoWrRjPZmeC' } , expires: 2020-02-13T10:53:28.015Z ) 
I20200130-10:53:28.337(0) [OAuth2Server] in getAccessToken (bearerToken: Redacted ) 
```

Best regards,

**Comment by franckadil** [comment]
Tested on 2.4.3 with same error.

**Comment by nikaro** [comment]
Also affected, on 2.4.5. It started with 2.4.2.

**Comment by rodrigok** [comment]
Thanks for your report. We are evaluating the issue and will have a solution ASAP.

**Comment by rodrigok** [comment]
The issue was fixed on version 2.4.6, please upgrade your installations.

**Comment by rodrigok** [comment]
Just a note, the release is in progress, the image may take about one hour to be available.

**Comment by franckadil** [comment]
@rodrigok Thank you for the update. I'll update our installation. Have an excellent weekend!

**Comment by heubles** [comment]
Version 2.4.6 seems unavailable via snap...

**Comment by channing-teh** [comment]
@heubles [Read here](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#when-will-my-snap-installation-get-the-latest-release)

> Updated Snaps are usually released around the 15th of the month - around 2 weeks after a new release. This gives us time to look for issues so you don’t have to.


I have been trying to get zapier to work with Rocket.Chat as well and it's not working, I guess we'll need to wait another 4 days to get the update.
