### ISSUE TITLE
Starred and Followed messages have no indication

### ISSUE THREAD

**Issue by ritvikjain99** [RocketChat/Rocket.Chat#16383]
**Problem**:
There is absolutely no indication of a message being **starred** or **following** . You have to see the options to check whether this message is starred or not.
**Proposed Solution**:
We can add icons depicting these just like we mark an edited message.
**Status** :
Working on it!
@gabriellsh please let me know if this is intentional.

**Comment by manosriram** [comment]
I would like to work on this. Will that be okay?

**Comment by manosriram** [comment]
@ritvikjain99  You still working on this ?

**Comment by ritvikjain99** [comment]
@manosriram sorry for late reply .
Yeah I am working, had to face random installation problems that's why go late!

**Comment by gabriellsh** [comment]
Hey guys, this is open source, there is no dibs on who does what. Feel free to work on what you want.

**Comment by manosriram** [comment]
@gabriellsh Thank you, sir. Appreciate that.

**Comment by ritvikjain99** [comment]
@manosriram 
Hey brother, I think you dint test that if message is edited then pencil is gone if your solution is considered.
Correct me if I am wrong.
Cheers!

**Comment by manosriram** [comment]
@ritvikjain99 No brother, I have tested it. It doesn't overlap.

**Comment by ritvikjain99** [comment]
@manosriram 
__With your code__:
![issue](https://user-images.githubusercontent.com/34532173/73773727-af56ca80-47a8-11ea-9d8f-789f6d959093.png)
This is how it looks if both icons are always visible. So I thought to show star on hover.
Don't know which is more feasible

**Comment by engelgabriel** [comment]
May be fixed by #16445 or #16461

**Comment by engelgabriel** [comment]
@ggazzo can you look at the possible fixes and choose one?
