### ISSUE TITLE
Restart multiple RC instances in Admin Panel

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16381]
In **Administration => General** there is a button **Restart the server**
![image](https://user-images.githubusercontent.com/4023037/73424845-03912300-4341-11ea-8078-5a4c77a05dfc.png)
If I have **muliple instances**, e.g. 3 - is that button restart all 3 RC instances?
If not - please a**dd that functionality to RC Admin Panel**.
I mean button to restart all instances.
Thanks!

**Comment by geekgonecrazy** [comment]
IMO... I think this actually would be a wontfix. 

Process management is beyond the scope of this project.  Our job I think ends at making sure we can gracefully be restarted.  It’s up to your process manager to actually perform the restart.

This is a hack to kill the process so your process manager will start it back up again.  We actually can’t restart our selves.  This would require a bootstrap program as part of Rocket.chat

Maybe we can add a note about it only terminating existing instance instead.

**Comment by ankar84** [comment]
wontfix
