### ISSUE TITLE
[BUG] Existing Users Can Have Password That Doesn't Meet The Policy

### ISSUE THREAD

**Issue by karimelghazouly** [RocketChat/Rocket.Chat#16384]
### Description:

When a server admin change the password policy to be enabled his / her password and the existing users password stays the same.
2 solutions that I can think of
1) I think all existing users should be asked to change their password to meet the requirements of server.
OR
2) We can have a password policy enabled by default for any account created in rocket.chat

### Steps to reproduce:

1. Create server
2. Enable password policy

**Comment by ashwaniYDV** [comment]
@karimelghazouly This is intentional.
I was going through the password policy enabling and found it there.

**Comment by karimelghazouly** [comment]
@ashwaniYDV ohh okay, but i think this might be useful in some cases as the admin might not be aware of that setting after some users have joined.

Maybe we can ask the server admin if you want to notify existing users and make them change their password?
