### ISSUE TITLE
Input field placeholders are hard to see.

### ISSUE THREAD

**Issue by manosriram** [RocketChat/Rocket.Chat#16385]
### Description:

Currently, the login and register page's input field placeholders can hardly be seen.  It's color can be changed for better visibility.
### Steps to reproduce:

1. Go to login-page
2. Empty the Fields (if not) to see the placeholders.

### Expected behavior:
Placeholders must have better visibility.

<img src="https://i.imgur.com/8Hg5TPf.png" />

### Actual behavior:
Placeholders are hardly visibile.
<img src="https://i.imgur.com/0zBINbG.png" />

### Server Setup Information:
<img src="https://i.imgur.com/TLgP6hD.png" />

### Client Setup Information

- Desktop App or Browser Version: Browser Version.
- Operating System: macOS

Would you like to work on this issue: YES

I'll revert this Issue if this behaviour is intentional.

**Comment by dougfabris** [comment]
Hey @manosriram thank you for your suggestion! We already have a great job done by our design team to make an entire replacement of this screen and very soon it will be implemented by the engineering team.
