### ISSUE TITLE
Ability to quote from previous messages

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#164]
It would be nice to be able to quote from earlier messages? 

It's very helpful feature when referring to something that's said earlier in long conversations...

**Comment by joepie91** [comment]
+1

I'm personally a fan of the way a Vanilla forum plugin does it; you select a snippet of text, it pops up a small 'Quote' button right below your selection, and you can click it to quote that specific snippet with the username and such prefixed.

**Comment by chrisidefix** [comment]
also quoting yourself via `>` should be possible (you can even do this in this chat)

`> This is a quote`

> This is a quote

**Comment by sampaiodiego** [comment]
a link to quote a message that simply copy the message to "textbox" with the `>` character, is something easy to do. is it enough? or do you think it should link to the quoted message or something like that?

**Comment by rockneverdies55** [comment]
@sampaiodiego - as my opinion it can be thought of as 2 steps process. Of course linking quoted texts to the originals would be very nice. 
However, if basic quoting functionality is easy enough to implement, then let's get that in asap. 
Then later, linking quoted texts to their originals can be done as an additional enhancement.

**Comment by sampaiodiego** [comment]
ok. I think we may change the pencil edit icon to an 'cog' icon with extra options, like edit, quote.. what you think?

**Comment by rockneverdies55** [comment]
Sounds very good!..

**Comment by joepie91** [comment]
Sounds good as initial implementation. I'd still support implementing "selection quotes" at a later point as well, though :)

**Comment by engelgabriel** [comment]
We've implemented the basic > quote 

So I'll move the issue to a later milestone as it is not a priority now.

**Comment by AntouanK** [comment]
@engelgabriel Is the "quote" feature implemented in v0.5.0?

**Comment by elwayman02** [comment]
@engelgabriel I can't pick a *best* implementation, as I think they could all be improved on; Gitter and PureCloud both take very different approaches to the UX of this type of feature. I think PureCloud's is a bit more efficient, though.

**Comment by engelgabriel** [comment]
@elwayman02 the Gitter implementation is very simple, it only adds a button on the message that copies it to the textarea with a ">" in front. Is that enough? We can do that right now.

![image](https://cloud.githubusercontent.com/assets/1000217/10484083/762c5c62-7259-11e5-943f-764742f70467.png)

![image](https://cloud.githubusercontent.com/assets/1000217/10484093/8532595a-7259-11e5-977a-d6f7991cee59.png)

![image](https://cloud.githubusercontent.com/assets/1000217/10484098/8bfc5a6a-7259-11e5-88c7-7173a4751b8b.png)

**Comment by mitar** [comment]
And puts a cursor into a new line afterwards without the `>`. I think that would be enough.

**Comment by engelgabriel** [comment]
Ok, let's do that. 

- I mean, let's ask Diego to do that :smile:

**Comment by AntouanK** [comment]
I think I was misunderstood.
If I go in https://demo.rocket.chat and post this:
```
foo
> bar
```
I see this as expected:
<img width="78" alt="screen shot 2015-10-14 at 15 03 47" src="https://cloud.githubusercontent.com/assets/4569111/10485966/b2b1d6dc-7284-11e5-99cb-502731db70f1.png">

But, in the rocket.chat I deployed in my own server ( by cloning the repo and using the docker deployment ) I see that:
<img width="64" alt="screen shot 2015-10-14 at 15 04 43" src="https://cloud.githubusercontent.com/assets/4569111/10485986/d2aabb3e-7284-11e5-9d9a-8ceb8244f3c2.png">

So apparently there is a version mismatch...
How can I inspect the versions on both of them and see what's what and what's implemented in each version?

**Comment by gmsecrieru** [comment]
@AntouanK looks like you are running an outdated version. Can you just pull an updated version from GitHub?

**Comment by AntouanK** [comment]
@gmsecrieru I'll do that.

Since I'll have to remove/restart the containers in the docker compose set up, that's brings another thing I would add in the README: How to update/restart without losing data. As in, mount a file-system directory, or a container as a volume, in order for data to persist even if you had to remove/restart the 2 basic containers ( meteor and mongo ).
I got this problem yesterday when I restarted and I lost everything when I killed docker-compose ( users/message etc ).
Now I got a FS directory mounted for the mongo files and the upload/avatars to persist.

I can help by making a PR for that, if you point out to me what exactly we want people to be aware of when they remove/restart containers.

**Comment by engelgabriel** [comment]
Sorry about you losing your data @AntouanK 

@Sing-Li can you point him on the right direction on how to do the PR for that?

**Comment by AntouanK** [comment]
@engelgabriel It's alright, I was just testing it anyway. But it's an important thing to point out for other people.

**Comment by fduraibi** [comment]
It would be nice also if the quoted person gets a mention/alert. Since I think it is mostly used to reply to an old message. 

So quoting the old message or a snippet if it was long maybe whit a link to the original if someone wants to see the whole thing or catch up with the conversation.

**Comment by leifkb** [comment]
I added a simple quote button to my RocketChat instance with the following script (you can paste it in the "layout" section of the admin section):

    Meteor.startup(function() {
      RocketChat.MessageAction.addButton({
        id: 'quote-message',
        icon: 'icon-quote-left',
        i18nLabel: 'Quote Message',
        context: ['message', 'message-mobile'],
        action: function(event, instance) {
          var m = this._arguments[1];
          $('.message-dropdown').hide();
          var input = instance.find('.input-message');
          var text = input.value;
          if (text) {
            text += '\n\n';
          }
          text += '@' + m.u.username + ' said:\n';
          var lines = m.msg.split(/\r\n|\r|\n/);
          for (var i = 0; i < lines.length; i++) {
            text += '> ' + lines[i] + '\n';
          }
          input.value = text;
          input.focus();
          $(input).keyup();
        }
      })
    });

**Comment by engelgabriel** [comment]
Hi @leifkb why dont you submit a Pull Request for us?

**Comment by leifkb** [comment]
Sure, I can try. Not really familiar with the codebase -- is there a specific correct place for this code to live?

**Comment by marceloschmidt** [comment]
Hey @leifkb thanks for your support!
I think you can add your code based on this code here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-lib%2Fclient%2FMessageAction.coffee#L169-L184 
You could create your message action there.

**Comment by fduraibi** [comment]
@leifkb Great work, but shouldn't the user message be below the quoted message? Since naturally it is a response to the quoted text!

**Comment by engelgabriel** [comment]
We agree.. and we will add that option later..
