### ISSUE TITLE
Users registered via SAML have no role

### ISSUE THREAD

**Issue by synotna** [RocketChat/Rocket.Chat#1640]
The current SAML implementation does not assign new users a RocketChat role, so users are left in a funny state - sidebar with only history, no access to channels etc

I imagine roles just need to be defined at https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-accounts-saml/saml_server.js#L87-L92

**Comment by rodrigok** [comment]
@synotna is fixed in our develop branch

**Comment by synotna** [comment]
Similar/related, #2195 :)
