### ISSUE TITLE
Logo slightly to the left in sidebar.

### ISSUE THREAD

**Issue by manosriram** [RocketChat/Rocket.Chat#16418]
### Description:

Rocket Chat logo is slightly to the left which looks a bit odd in the sidebar bottom.
### Steps to reproduce:

1. Open the app.
2. At the bottom of the sidebar, the logo is not centered.

### Expected behavior:
The logo must be centered.

![Expected](https://i.imgur.com/QNO59Je.png)
### Actual behavior:
The logo is not centered, looks odd.
![Actual](https://i.imgur.com/R6VzHI2.png)

## Status: Working on it.

**Comment by aknrg77** [comment]
i would like to fix this issue

**Comment by engelgabriel** [comment]
Hi @manosriram,

I am sorry but this is a case of taste and our designer has aligned the logo to the left on purpose. 

Users can change the logo aliment using the custom CSS setting on the admin if they prefer. 

:)
