### ISSUE TITLE
[BUG] Deleting messages while searching causes the whole room chat to disappear

### ISSUE THREAD

**Issue by karimelghazouly** [RocketChat/Rocket.Chat#16413]
### Description:

I have attached a gif for the bug 
![Screencast 2020-02-01 16_57_07](https://user-images.githubusercontent.com/24472871/73594368-920acd80-4516-11ea-84a0-e69d47dae3d6.gif)

### Expected behavior:

Do nothing

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0 develop
- Operating System: Ubuntu
- NodeJS Version: 8.17
- MongoDB Version: 4.0.6

**Comment by karimelghazouly** [comment]
Currently working on it

**Comment by ritvikjain99** [comment]
@karimelghazouly I am taking up this issue!!??

**Comment by karimelghazouly** [comment]
@ritvikjain99  I already made a PR for this issue not sure if it's the best approach you can look into it and give me feedback if you can think of another solution
