### ISSUE TITLE
[BUG] DDP Rate Limiter floods the log file

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#16410]
### Description:

DDP Rate Limiter floods the log file, because DDP Rate Limiter logging comes with log level "error".

The logging itself is legitimate, but should not be classified as "error", but rather as "info" or "debug". 

### Steps to reproduce:

1. check logfiles for DDP Rate Limiter entries

### Expected behavior:

With logfile Level 0 (errors only) there should be no DDP Rate Limiter entries in the logfile.

### Actual behavior:

DDP Rate Limiter floods the log file partially with several hundred entries within one second. This is then based on the log file a kind of built-in DOS on system level. Especially since the log file takes on a significant size within a day, depending on the activity of the server.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.5
- Operating System: Linux (Ubuntu 16.04 LTS)
- Deployment Method: bundle (self built)
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 8.17.0
- NPM Version: 6.13.4
- MongoDB Version: 3.6.17

**Comment by Rishgod** [comment]
Can I work on this bug?
