### ISSUE TITLE
[BUG] If "Collapse Embedded Media by Default" is set to true then also pdf are displayed expanded

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16424]
### Description:
When Collapse Embedded Media by Default is set to true, then also pdf files are shown expanded

### Steps to reproduce:

1. Enable Collapse Embedded Media by Default
2. Send a pdf to any room

### Expected behavior:
Like images and youtube video embedded links pdfs should also be shown collapsed

### Actual behavior:
They are expanded

### Additional context
I am working on it

**Comment by MartinSchoeler** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/16188 Fixes this issue
