### ISSUE TITLE
Able to mention user not a member of private channel

### ISSUE THREAD

**Issue by xgdgsc** [RocketChat/Rocket.Chat#16427]
### Description:

Currently it is possible to mention(@) a user not a member of current private channel. This would make me think the user is already inside the channel.

### Steps to reproduce:

1. go to a private channel
2. @ a user not a member of this channel
3. It works but the user cannot access the message.

### Expected behavior:

Not able to mention user not a member of private channel

### Actual behavior:

mention works

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1
- Operating System: Linux centos 3.10.0-957.el7.x86_64
- Deployment Method:  docker compose
- Number of Running Instances:  1
- DB Replicaset Oplog:  enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 4.0.10

### Client Setup Information

- Desktop App or Browser Version: linux desktop 2.17.2
- Operating System: Ubuntu 16.04

**Comment by fleaz** [comment]
This only happens to you when you have the `view-outside-room` permission, so depending on your setup not all users are affected by this.
But yes, this is super annoying and I regularly mention random people in our customer chatrooms because I type to fast and the suggestbox wont update fast enough and I hit the wrong user. So a clear `+1` from me for fixing this :)

**Comment by subham103** [comment]
@fleaz @xgdgsc  I am working on this issue. One small doubt is should we need to remove the non-member users from the suggestion box only, or we also have to treat that message as a normal message (not a mention)?
![Rocket Chat(3)](https://user-images.githubusercontent.com/43502196/76907576-8e67b600-68cc-11ea-93ea-6587ea62d5c8.png)

**Comment by xgdgsc** [comment]
I' m for remove.

**Comment by gabriellsh** [comment]
This is currently intended behaviour. It's supposed to allow users to tag other users so people can access it directly. As @fleaz said, this can be disabled through the `view-outside-room` permission.

We won't remove this, but, we're already discussing a new search system, so we can improve the currently not reliable one. For now, this will be closed. Thanks for everyone's help.
