### ISSUE TITLE
[BUG] Search in Member list do not search all channel users

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16428]
### Steps to reproduce:

1. Go to any channel with more then 100 members 
2. Click **Members List** icon
3. Try to search someone not in first 100 shown users - result not found
4. Click **Show more** button till user you search apears
5. Search user - result user is found

### Expected behavior:

Search all channes users, not only that shown in member list

### Actual behavior:

![manyUsers](https://user-images.githubusercontent.com/4023037/73642316-8f2ceb80-4682-11ea-9425-fe0f96da899d.gif)

### Server Setup Information:

open.rocket.chat has that bug

### Client Setup Information

- Desktop App or Browser Version: RC.Electron 2.15.5 and Chrome latest
- Operating System: Windows 10

**Comment by ankar84** [comment]
@ggazzo is #17110 fix that issue?

**Comment by ggazzo** [comment]
thanks @ankar84 
closed by #17110
