### ISSUE TITLE
Error message spam in private chat

### ISSUE THREAD

**Issue by Evgeniy185** [RocketChat/Rocket.Chat#16426]
Client version 2.15.5
Rocket.Chat Version: 2.4.2           
NodeJS Version: 8.17.0 - x64  
MongoDB Version: 3.6.14        
MongoDB Engine: wiredTiger 

Some users in some private chats start getting error messages: 

> rocket.cat
> 16:42
> Only you can see this message
> Error
> Error
> Error
> Error
> Error

User do not make any activities to get this error. Rocket.cat spams "error" message every 10 minutes. User still can send and recieve messages in this chats.

We are using LDAP auth (Microsoft AD), no anonymous logins allowed. 
In logs we get a few of this:

> server.js:204 LDAPSync ➔ error Error creating user { Error: Email already exists. [403]     at handleError (packages/accounts-password/password_server.js:107:17)     at checkForCaseInsensitiveDuplicates (packages/accounts-password/password_server.js:241:7)     at createUser (packages/accounts-password/password_server.js:1076:3)     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)     at addLdapUser (app/ldap/server/sync.js:452:29)     at ldapUsers.forEach.ldapUser (app/ldap/server/sync.js:518:5)     at Array.forEach (anonymous)     at app/ldap/server/sync.js:485:13     at runWithEnvironment (packages/meteor.js:1286:24)   isClientSafe: true,   error: 403,   reason: 'Email already exists.',   details: undefined,  ,   message: 'Email already exists. [403]',   errorType: 'Meteor.Error' }

and a lot of this:

> server.js:204 System ➔ error Error sending message: Error: You are not authorized to change message properties     at validateUserIdentity (app/lib/server/functions/sendMessage.js:164:9)     at sendMessage (app/lib/server/functions/sendMessage.js:175:3)     at executeSendMessage (app/lib/server/methods/sendMessage.js:76:10)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:104:10)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1689:15)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at resolve (packages/ddp-server/livedata_server.js:1687:36)     at new Promise (anonymous)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at DDPCommon.MethodInvocation.Meteor.runAsUser (app/api/server/v1/chat.js:175:59)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at Object.post (app/api/server/v1/chat.js:175:23)     at DDP._CurrentInvocation.withValue (app/api/server/api.js:343:82)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 

> server.js:204 API ➔ debug post chat.sendMessage threw an error: TypeError: Cannot read property 'starred' of undefined     at filterStarred (app/utils/server/lib/normalizeMessagesForUser.js:6:14)     at messages.map.message (app/utils/server/lib/normalizeMessagesForUser.js:17:36)     at Array.map (<anonymous>)     at normalizeMessagesForUser (app/utils/server/lib/normalizeMessagesForUser.js:17:19)     at Object.post (app/api/server/v1/chat.js:177:21)     at DDP._CurrentInvocation.withValue (app/api/server/api.js:343:82)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 

> server.js:204 API ➔ debug Failure { statusCode: 400,   body:     { success: false,      error: 'Cannot read property \'starred\' of undefined',      stack: undefined } } 

> server.js:204 API ➔ debug POST: /api/v1/chat.sendMessage 

> server.js:204 API ➔ debug post chat.sendMessage threw an error: Error: Error, too many requests. Please slow down. You must wait 59 seconds before trying this endpoint again. [error-too-many-requests]     at APIClass.enforceRateLimit (app/api/server/api.js:202:10)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:324:11)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9

**Comment by MarcosSpessatto** [comment]
Hey @Evgeniy185, [this PR](https://github.com/RocketChat/Rocket.Chat/pull/16395) "fixes" this problem. Can you please test with the v.2.4.6?

**Comment by Evgeniy185** [comment]
Hmm, we are using snap. Snap refresh says "All snaps up to date.", but still 2.4.2

**Comment by Evgeniy185** [comment]
after update to 2.4.9 problem is gone.
