### ISSUE TITLE
[BUG] If a pdf is collapsed then its canvas is not rendered again when expanded

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16423]
### Description:
When collapsed state is toggled then the pdf canvas is not rerendered.

### Steps to reproduce:

1. Upload a pdf in a room
2. Collapse it
3. Expand it

### Expected behavior:
Canvas should be visible again

### Actual behavior:
No canvas is shown

### Additional context
I am working on it.

**Comment by MartinSchoeler** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/16188 Fixes This
