### ISSUE TITLE
Allow SAML Auth when email attributes is empty

### ISSUE THREAD

**Issue by menardorama** [RocketChat/Rocket.Chat#16431]
Hi
We are using SAML authentication to anthenticate our users.

Our idp is bound against an Active Directory and some users don't have email adresses.

I'm trying to figure out how can we be able to authenticate using only one auth Mecanism and ask for a valid email adress at first logon if email attribute is empty.

Is this is possible ?

Thanks a lot

**Comment by localguru** [comment]
If a central IDP is used, the core attributes should also be taken from there. I would personally count the e-mail address among these core attributes, especially if you want to prevent a company from storing e.g. the private e-mail address. But it is possible that despite authentication with SAML the user can change his profile in Rocket.Chat himself.

**Comment by menardorama** [comment]
Hi
The thing is that for some users the email attribute is not present at all.
It prevent Rocket.Chat to pass the auth.

Thomas Menard

**Comment by pierre-lehnen-rc** [comment]
You can change the `Immutable field name` setting to username instead of email.
