### ISSUE TITLE
Admin pinned messages have no indication

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#16447]
### Description:
There should be a pin icon for pinned messages when admin pins a message

### Additional context
I am working on it.

**Comment by ritvikjain99** [comment]
@ashwaniYDV you should also add a pin icon if a child message is pinned.

**Comment by ashwaniYDV** [comment]
@ritvikjain99 Can you please explain child message. Do you mean thread messages

**Comment by ashwaniYDV** [comment]
@ritvikjain99 Can you please explain child message. Do you mean thread messages

**Comment by ashwaniYDV** [comment]
> @ashwaniYDV you should also add a pin icon if a child message is pinned.

It is working fine for child messages too.
