### ISSUE TITLE
chat, evolved - option to move chat center window to a fly-in panel

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#1645]
motivation: work groups do something, along with their chatting. Indeed the chatting is intended to be in support of some business activity. And that activity might likely also  require screen real estate.

So, one could have two apps open, one for the chat, and one for the work. Sure. But one might alternatively have common log-in etc provided by RC, such that RC hosts the business app.

So in support of that scenario I request consideration of a admin panel option to switch the chat window to be a fly-in panel.
##

**Comment by MartinSchoeler** [comment]
I believe today this can be done with the iframe integration https://rocket.chat/docs/developer-guides/iframe-integration/#iframe-integration . If this doesn't solve your issue please open a new issue with updated details. Thanks!
