### ISSUE TITLE
How to change backup destination?

### ISSUE THREAD

**Issue by long-nguyenxuan** [RocketChat/Rocket.Chat#16459]
### Description:
My server is almost out of storage, so backup always failed 
How could I change backup destination to other dir? 

### Steps to reproduce:

Trigger backup follow [the guide](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-backup-my-snap-data)

### Expected behavior:

It should have option to change backup destination instead of `/var/snap/rocketchat-server/common/backup/*.tar.gz` 

### Actual behavior:

It always trigger a backup to `/var/snap/rocketchat-server/common/backup/rocketchat_backup_YMDHMS.tar.gz`

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Ubuntu 1604 
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.20

### Relevant logs:

```log
2020-02-04T21:03:33.742+0700	[#######.................]  parties.rocketchat_uploads.chunks  54745/178225  (30.7%)
2020-02-04T21:03:33.742+0700	Failed: error writing data for collection `parties.rocketchat_uploads.chunks` to disk: error writing to file: write /var/snap/rocketchat-server/common/backup/dump/parties/rocketchat_uploads.chunks.bson: no space left on device
[*] Packing archive with "tar czvf /var/snap/rocketchat-server/common/backup/rocketchat_backup_20200204.2101.tar.gz /var/snap/rocketchat-server/common/backup/dump"
```

**Comment by localguru** [comment]
https://github.com/RocketChat/rocketchat-server-snap/blob/develop/bin/backupdb.sh

```
backup_dir="${SNAP_COMMON}/backups/${backup_date}"
backup_file="${SNAP_COMMON}/backups/rocketchat_backup_${backup_date}.tgz"
```
