### ISSUE TITLE
users -> "user info" tab never loads

### ISSUE THREAD

**Issue by vvolas** [RocketChat/Rocket.Chat#16453]
### Description:
This happened in 3 rocketchat ( all I use) instances. All have similar configuration.

### Steps to reproduce:

As admin user.

go to users tab -> user info -> never loads.
 

### Server Setup Information:

Ubuntu18
Snap
Users are from LDAP + hand made.

RocketChat Version | 2.4.2

### Client Setup Information

- Desktop App or Browser Version: App + Firefox
- Operating System: Linux

![image](https://user-images.githubusercontent.com/1449064/73722092-619d7c00-472e-11ea-8ae3-29dff5b80ee7.png)

### Relevant logs:
Sadly there is no relevant logs, browser shows same logs on all pages, while in server there is also nothing.

The only type of errors I have.
I doubt this is relevant, because trying to view user info doesnt trigger additional messages.

`I20200203-08:30:53.483(2) server.js:204 LDAPHandler ➔ error Error: User not Found     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:60:10)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43`

**Comment by ankar84** [comment]
Do not confirm for RC version 2.4.3
![image](https://user-images.githubusercontent.com/4023037/73812579-50b43f80-47ee-11ea-8f02-0cfbdaacc5d5.png)

**Comment by sampaiodiego** [comment]
cannot reproduce on 3.0.0-rc.2 as well.. it shows:

![image](https://user-images.githubusercontent.com/8591547/74068627-da286500-49da-11ea-8891-dc410d2f7f01.png)

any additional steps to reproduce @vvolas ?

**Comment by vvolas** [comment]
Its probably some setting, since all instances are almost identical. I
tried to look at it but didint had much time. I will setup additional
instance and will try to figure it out.

**Comment by sampaiodiego** [comment]
ok.. please let me know if you find something.

**Comment by vvolas** [comment]
Hello again sorry I couldnt reply faster.

So when I to open the user info I get this error in rocketchat client dev console
`webview: Uncaught (in promise) Error  webview.js:52 `

In fresh installation there is no such error.

I did setup new test instance and configured LDAP and everything works fine. I m kinda lost.

OK this is probably unrelated but maybe it will, in old logs there was spam of this error:
```
Dec 24 21:54:00 rocketchatrb rocketchat-server.rocketchat-server[1500]: TypeError: Cannot read property 'username' of undefined
Dec 24 21:54:00 rocketchatrb rocketchat-server.rocketchat-server[1500]:     at generateUserAvatarFile (app/user-data-download/server/cronProcessDownloads.js:477:62)
Dec 24 21:54:00 rocketchatrb rocketchat-server.rocketchat-server[1500]:     at Promise.asyncApply (app/user-data-download/server/cronProcessDownloads.js:503:4)
Dec 24 21:54:00 rocketchatrb rocketchat-server.rocketchat-server[1500]:     at /snap/rocketchat-server/1414/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

```
And this error was replaced with new one which continues now.
Feb 27 14:00:00 rocketchatrb rocketchat-server.rocketchat-server[42858]: { Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/Ej66WmuJFEJ3EKuYL.zip'
Feb 27 14:00:00 rocketchatrb rocketchat-server.rocketchat-server[42858]:   errno: -2,
Feb 27 14:00:00 rocketchatrb rocketchat-server.rocketchat-server[42858]:   code: 'ENOENT',
Feb 27 14:00:00 rocketchatrb rocketchat-server.rocketchat-server[42858]:   syscall: 'stat',
Feb 27 14:00:00 rocketchatrb rocketchat-server.rocketchat-server[42858]:   path: '/tmp/zipFiles/Ej66WmuJFEJ3EKuYL.zip' }
```

**Comment by vvolas** [comment]
I cloned whole rocketchat virtual machine, and setuped it on different IP that damn user tab works! I tried restarting original machine but it didint help. Things are weird. 

Ok now I accessed original rocket chat machine via IP directly and now I can access that damn tab so something is wrong with nginx configuration. But everything works except that damn tab, things are really weird :)

**Comment by vvolas** [comment]
OK nginx it is. I had setuped nginx bad bots filter and forgoten about it and 1 rule did match that special request to user tab.

Thanks for help! My bad.

**Comment by sampaiodiego** [comment]
thanks for letting us know.. great you found the issue 🤗
