### ISSUE TITLE
Users get logged out when page is manually refreshed

### ISSUE THREAD

**Issue by ndroo** [RocketChat/Rocket.Chat#16463]
### Description:

User gets logged out on page refresh, but if they dont manually refresh, everything else seems normal and fine.

### Steps to reproduce:

1. Log into rocketchat on web
2. Refresh the screen by pressing command+r
3. User is redirected back to login screen

### Expected behavior:

At step 3, user is still logged in.

### Actual behavior:

User gets logged out and returned to login screen.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: ubuntu 18
- Deployment Method: docker build
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 4.0.16
### Client Setup Information

- Desktop App or Browser Version: chrome 79 (also occurs on safari - verified on my computer and others in the office)
- Operating System: mac 10.14.6

### Additional context

Was not happening until the other day, no idea what I've done to deserve this...no server settings have been changed. 

Video of the situation: https://www.youtube.com/watch?v=2bXvOi_eb6o&feature=youtu.be

**Comment by localguru** [comment]
@ndroo I can't reproduce the behavior with server version 2.4.5, but I seem to remember that server version 2.4.2 behaved like this. But I am not sure. I would update to 2.4.5 and check again.

**Comment by ndroo** [comment]
It seems to happen randomly. Our sandbox server (one we just use for configuration testing before pushing something live) started doing this yesterday, and without any changes it's stopped all on its own. I guess feel free to close this if it's not a big deal, but it's for sure weird.

**Comment by ianmclinden** [comment]
This is happening again on a 3.1.0 test server, but only for users authenticated via LDAP
