### ISSUE TITLE
[BUG]: Message action popup doesn't adjust itself on screen resize.

### ISSUE THREAD

**Issue by ritvikjain99** [RocketChat/Rocket.Chat#16462]
__BUG__:
After opening message action popup, resizing screen doesn't affect the position of popup's origin i.e. the action menu icon.
__IDEAL BEHAVIOUR__:
It should change it's origin.
__STATUS__:
On it.
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/34532173/73772083-88e36000-47a5-11ea-8095-3faabc6575f4.gif)

**Comment by gabriellsh** [comment]
Also the sidebar search behaves the same way 
![image](https://user-images.githubusercontent.com/40830821/73940859-fb019500-48ca-11ea-9361-bbf5cd0fe0bf.png)

**Comment by gabriellsh** [comment]
The thing is, should we close them or resize? For example the Image that I posted above, that search will close if you click anywhere outside (even if you click out of the window), but won’t close when resizing the window.

**Comment by ritvikjain99** [comment]
Actually after some fight with code came to know that the position of origin of popup(the action button here), is fed to template on it's creation, remains constant for whole life of template. Also it's distance deciding calculations **don't** take into account the **width of screen**. That's what creates this mess.
For you image it's I suppose is due to javascript bubbling I have already reported this in 16436, when you resize, the event isn't bubbled to the sideBarItem, which is responsible for closing it!
