### ISSUE TITLE
Internal Server Error incorrectly triggered when installing/opening an app

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat#16460]
### Description:

'Internal Server Error' error is incorrectly triggered when installing or opening an App (example: JIRA Server App)

### Steps to reproduce:

1. Go to MarketPlace and install JIRA Server or JIRA Cloud app (make sure you are logged on to Cloud Admin with valid credentials)
2. "Internal Server Error" is displayed in the screen, however the App is installed succesfully and working fine.

### Expected behavior:

No error to be displayed, as the app installation was succesful.

### Actual behavior:

![error_1](https://user-images.githubusercontent.com/11891939/73763526-493e5900-4750-11ea-8cdc-8f47c88bec9b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0-develop
- Operating System: All
- Deployment Method: All
- Number of Running Instances: N/A
- DB Replicaset Oplog: Yes
- NodeJS Version: latest
- MongoDB Version: latest

### Client Setup Information

- Desktop App or Browser Version: All
- Operating System: All

### Relevant logs:

error log:

server.js:204 Rocket.Chat Apps ➔ error Error getting the Bundle's Apps from the Marketplace: {   code: 319,   error: 'no bundle found by the provided id',   requestId: 'a661dd80-4c63-41af-a4c8-efb7718fc10c',   status: 400 }

**Comment by sergzuko** [comment]
Same problem with intranet installation (without internet)

**Comment by geekgonecrazy** [comment]
Is this still an issue?

**Comment by thassiov** [comment]
This is not a problem anymore. It happened because the server was trying to get information about the bundle the app belonged to, and at the time it wasn't possible. This was fixed at the marketplace's side
