### ISSUE TITLE
OTR issues

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16478]
### Description:

Currently, the OTR has many issues 
![out](https://user-images.githubusercontent.com/43509699/73848856-ef708880-484e-11ea-8fe9-f890bab4f92b.gif)
1. The sidebar shows a cryptic message when a message is sent, It should be better if  a consistent message is shown like "encrypted message sent" 
2. When a message is sent through the threads it doesn't appear normally on the room. 
There can be two options : 
a. We don't want to show the thread replies on screen, then a message like "Message is encrypted" can be shown
b. We want to show the content on the screen like normal thread replies . I think this is more preferrable because after OTR is established there is no further need for more abstraction.
3. File uploads still works but on on uploading file doesn't show in the OTR but instead is sent in the normal messages. 
4. when OTR is finished then they should immediately dissapear from screen or screen should be automatically reloaded and there should be no need for user sided reload
If file upload is not allowed in OTR we should disable those buttons
![OTR](https://user-images.githubusercontent.com/43509699/73848864-f1d2e280-484e-11ea-8f54-2eb73781a725.png)
After OTR is finished and page is reloaded the images appear, and are in expanded form even if setting is set to be collpased
![out](https://user-images.githubusercontent.com/43509699/73848875-f7302d00-484e-11ea-9e26-e9064e81c1ee.gif)
When page is reloaded before stopping the OTR then all messages dissapear and only encrypted image keys are shown

**Comment by ritwizsinha** [comment]
I am working on it and certainly would like suggestions from @gabriellsh @sampaiodiego

**Comment by localguru** [comment]
@ritwizsinha 

on points 3 and 4: this is 3 years old bug, which makes OTR completely insecure, see https://github.com/RocketChat/Rocket.Chat/issues/7507

Users rely on the fact that files uploaded during an OTR session are transmitted encrypted. The fastest solution would be to disable file upload during an OTR session.

**Comment by ritwizsinha** [comment]
@localguru ok i'll try to do it

**Comment by ritwizsinha** [comment]
@gabriellsh Because the user is in OTR conversation when he ends it we can even show the last message as the message that wasn't an OTR because there shouldn't be any trace of an OTR message. This would require storing the last message differently. For any user when OTR is going on his last message shown would be the one he typed/received last in the OTR conversation but when OTR is switched off the last message should be the message which wasn't in OTR. For this we need to store 2 types of last messages. Could you help me as to where the code for the storage of last message is in the codebase
