### ISSUE TITLE
enroll-account

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#16482]
Rocket 2.4.6 on docker

There seems to be an odd link in the 'welcome' email that I can't find where it comes from, despite grepping all the code:

```
Date: Fri, 31 Jan 2020 15:06:11 +0000
MIME-Version: 1.0

----_NmP-ad58ed4e399fe5a1-Part_1
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

Hello,

To start using the service, simply click the link below.

https://chat.rocketchat.com/#/enroll-account/wmXs737KHU5nDTF6nogH-yBASQ2jb=
erJSeD6WtYcUQe

Thanks.

----_NmP-ad58ed4e399fe5a1-Part_1
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html style=3D"font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',=
Roboto,Oxygen,Ubuntu,Cantarell,'Helvetica Neue','Apple Color Emoji','Segoe =
UI Emoji','Segoe UI Symbol','Meiryo UI',Arial,sans-serif;"><table =
border=3D"0" cellspacing=3D"0" cellpadding=3D"0" width=3D"100%" =
```

This server does not allow public registration. Manually created users by admin only.

What is 'enroll-account' about?

Why is it in the 'Welcome' email?

Why does this URL not appear as visible or a link in the html version?

**Comment by TheoKouzelis** [comment]
Not sure if this will help you. But in Rocket 3.0.2 (it may be in earlier versions as well) it allows you to edit the email html via the admin UI in /admin/Email.

There you can edit the messages for both Public Registration and Registration via Admin. It allows you to add and remove placeholders such as [password]  [Site_URL] .....

![password-email](https://user-images.githubusercontent.com/4980126/75766493-26946580-5d39-11ea-8953-3e754e37be14.png)

**Comment by sampaiodiego** [comment]
right, in the newer rocket.chat versions the enrolment email is configurable as well.
