### ISSUE TITLE
profile update : no status colors present while updating status

### ISSUE THREAD

**Issue by anirudhsingh20** [RocketChat/Rocket.Chat#16499]
### Description:
while updating profile there is no status colors preset on update status 

### Steps to reproduce:

1.go to profile page
2. see update status input
3. status colors are not present

### Actual behavior:
![Screenshot from 2020-02-06 20-51-03](https://user-images.githubusercontent.com/49402380/73951593-c0781680-4923-11ea-8b72-8a3a1c83a159.png)

### Expected behavior:
similar to this
![Screenshot from 2020-02-06 20-52-53](https://user-images.githubusercontent.com/49402380/73951576-b9510880-4923-11ea-9d7d-1926bd427877.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: ubuntu
- NodeJS Version: 8.10.0

### Client Setup Information

- Desktop App or Browser Version: chrome
- Operating System: ubuntu

### Additional context

I want to work on this

**Comment by ritwizsinha** [comment]
I want to work on it
