### ISSUE TITLE
Feature Request: Add support for RTL 

### ISSUE THREAD

**Issue by shahar3012** [RocketChat/Rocket.Chat#165]
Rocket.Chat should support RTL in order to display the following languages properly:
Hebrew and Arabic. 
Please consider adding this support. It should not take a lot of time to finish it.

**Comment by sampaiodiego** [comment]
Can you help us with that @shahar3012 ? We don't know exactly what to change.. It has to be all the interface? Logo, room list position or what? We need some help to do this =)

thanks

**Comment by Schniz** [comment]
@shahar3012 will help you (I know this guy....) and so do I.
the basic thing that should be implemented is that every `input`/`textarea`/message holder/username should be

```html
<some-tag dir="auto">my text</some-tag>
```

this should set the direction automatically based on the language. no extra work needed on the alignment and directions and stuff. new browsers yay.

**Comment by Schniz** [comment]
but it makes me wonder about the whole layout, should it be RTLed too?
from what I understand, you guys are working on translating the product (I can't see it, maybe it will be under the new settings page when it will come?), maybe if the user is on Arabic/Hebrew the whole layout should be RTL?

(that, of course, doesn't hurt the `dir="auto"`, it helps for writing english/hebrew/arabic in one sentence)

**Comment by shahar3012** [comment]
I'm working on RTL support. Will create pull request when finished.

**Comment by Schniz** [comment]
@shahar3012 If I were you I'd create the PR with [WIP] at the beginning of the title.
this could help all of us comment and discuss about the pull request :smile:

**Comment by engelgabriel** [comment]
Please let me know if all works for you now.
