### ISSUE TITLE
Disable Push notifications for Omnichannel

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat#16500]
### Description:

When a livechat message comes in, push message is being sent to mobile clients. Since mobile apps do not support Omnichannel yet it would be nice to not receive push messages since they are confusing a lot of users. 

### Steps to reproduce:

1. Send a message in the livechat (make sure you are assigned to the department and can accept livechats).
2. Push message comes in on your mobile - tap to open. 
3. It opens an empty room, which is also not being updated even though there is an active conversation  in the livechat.

### Expected behavior:

No push messages until mobile apps support Omnichannel.

### Actual behavior:

Tapping on a push message opens an empty room; you can still respond from the notification itself, but your response will not be save in the chat room. 

![Push](https://user-images.githubusercontent.com/47217833/73952572-c95aef00-4907-11ea-8584-c96b291ba018.png)

![emty_room](https://user-images.githubusercontent.com/47217833/73952576-cb24b280-4907-11ea-8d23-cca91eeae2c5.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  not relevant
- Operating System:  not relevant
- Deployment Method: cloud
- Number of Running Instances:  not relevant
- DB Replicaset Oplog:
- NodeJS Version:  not relevant
- MongoDB Version: not relevant

### Client Setup Information

- Desktop App or Browser Version:  not relevant
- Operating System:  not relevant

**Comment by rsjr** [comment]
closing this one as the ominichannel is now supported in mobile (in beta)
