### ISSUE TITLE
Cannot use Gmail SMTP

### ISSUE THREAD

**Issue by jmeeter** [RocketChat/Rocket.Chat#16519]
### Description:

Cannot get email verification to work using Gmail SMTP.

### Steps to reproduce:

Click send test email.

### Expected behavior:

Expect to receive test email.

### Actual behavior:

>  I20200207-21:30:39.448(1) Meteor ➔ method sendSMTPTestEmail -> userId: GBL3Tq6aHYtwDmsWn, arguments: [] 
I20200207-21:30:39.461(1) Exception in defer callback: { Error: getaddrinfo ENOTFOUND http http:587     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)   errno: 'ENOTFOUND',   code: 'ECONNECTION',   syscall: 'getaddrinfo',   hostname: 'http',   host: 'http',   port: 587,   command: 'CONN' }  

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by frdmn** [comment]
> `getaddrinfo ENOTFOUND http`

It's trying to to connect (and resolve) the hostname `http` which obviously fails. Double check your SMTP configuration again.

**Comment by jmeeter** [comment]
Hm, I may have been entering smtp.google.com instead of smtp.gmail.com - either way, it's working now.
