### ISSUE TITLE
Console Errors after latest pull

### ISSUE THREAD

**Issue by ravimallya** [RocketChat/Rocket.Chat#1651]
![image](https://cloud.githubusercontent.com/assets/2795843/11776354/70481e06-a26c-11e5-84ef-a92c5c3ea1bd.png)

Full of errors after doing latest git pull and cannot login as the page is blank. I did a pull request just 1 hour ago. URL is at: http://206.80.45.80:3000/ 

Update:
I tried to revert `git reset --hard 506bdeacf912749bf433fbf3eb015641cbba7826` and `git update` to https://github.com/RocketChat/Rocket.Chat/commit/506bdeacf912749bf433fbf3eb015641cbba7826  commit but the issue still there.

Update 2:
Tried https://github.com/RocketChat/Rocket.Chat/commit/827032390689f01895ed402e1a359b0e81c19feb commit without any luck... @marceloschmidt Can you please look into this ASAP.
 
Update 3:
I can see following log:

	I20151214-05:22:41.801(-5)? stop rendering 3275  // what is this?
	I20151214-05:22:41.996(-5)? Updating login service SAML_Custom_default
	I20151214-05:22:42.236(-5)? Kadira: completed instrumenting the app
	I20151214-05:22:42.237(-5)? configuring push
	I20151214-05:22:42.326(-5)? Using GridFS for Avatar storage
	I20151214-05:22:42.192(-5) (migrations_server.js:80) Migrations: Not migrating,
	already at version 25
	I20151214-05:22:42.328(-5)? startStreamBroadcast
	I20151214-05:22:42.237(-5) (percolate_synced-cron.js:71) SyncedCron: Scheduled "
	Generate and save statistics" next run @Mon Dec 14 2015 05:22:42 GMT-0500 (Easte
	rn Standard Time)
	I20151214-05:22:42.329(-5)? ufs: created tmpDir /tmp/ufs
	=> Started your app.

	=> App running at: http://localhost:3000/
	   Type Control-C twice to stop.

	I20151214-05:22:44.666(-5)? stop rendering 1819  // what is this?
	I20151214-05:22:44.667(-5)? Updating login service SAML_Custom_default
	I20151214-05:22:44.667(-5)? Updating login service Accounts_OAuth_Facebook
	I20151214-05:22:44.768(-5)? Updating login service Accounts_OAuth_Facebook_id

Can see couple of `stop rendering` but not in a local environment after doing a git pull over here also.

Thanks a lot.

**Comment by ravimallya** [comment]
Update:
I tried to revert `git reset --hard 506bdeacf912749bf433fbf3eb015641cbba7826` and `git update` to https://github.com/RocketChat/Rocket.Chat/commit/506bdeacf912749bf433fbf3eb015641cbba7826  commit but the issue still there.

**Comment by marceloschmidt** [comment]
You shouldn't be fetching from develop unless you absolutely know what you're doing and are able to fix errors. You should instead fetch from master. I don't know what happened, but I'll take a look, although it was probably a temporary error, since our demo will usually run from develop branch. But I repeat, you should be fetching from *master* only, if you don't want to run into problems like these.

**Comment by ravimallya** [comment]
I didn't tried to fetch intentionally from develop branch. Just i did a `git pull` today and then run `meteor` I don't know which branch currently it has. I just installed as mentioned in Docs and did git update today again. Later I tried to restore from a previous commit to see weather issue can be fixed or not. 

Later I did a `git reset --hard HEAD` and `git pull`. Now also same issue. 

Is it possible to reinstall without losing users and other settings? 

Thanks again.

**Comment by marceloschmidt** [comment]
I see... well, the fact that you're running `meteor` in a production environment is not a good thing either. I've reached that URL now and it seems to me that it's working. I don't have a login there, but as far as getting to the login page, all went fine. Are you still experiencing it? Have you also tried clearing cache?

**Comment by ravimallya** [comment]
Yes. Found something strange. Now, the page is loading fine in other systems. I tried to access the same in Incognito Window (Chrome) and fine, but not when in the same window after clearing browser cache and cookies. When I closed all browser windows, restarted the browser, cleared cache and then the site loads fine.

Btw, When I tried to login as an Admin, with proper password, I'm being asked to provide email address and can't login. This started after Updating SMTP settings and after enabling email confirmation in latest release. How can I get into the Admin page? 

And you've mentioned that  **the fact that you're running meteor in a production environment is not a good thing either.**. If we're not supposed to use meteor in production, how we can run the application in Windows server? I found no proper guides, and I'm new to meteor. Please guide us.

Thanks.

**Comment by marceloschmidt** [comment]
OK, so the main problem in this issue is solved, good! I'll close the issue.
As for logging in after enabling email confirmation, it's a known bug. Check this for solution: https://github.com/RocketChat/Rocket.Chat/issues/1454
You should never run `meteor` in production. You should build your app and run through node. Check this tutorial for windows deployment:  https://github.com/RocketChat/Rocket.Chat/wiki/Windows-Deployment

**Comment by ravimallya** [comment]
Okay. Thanks a lot for your help. Now, I can login to the Admin Panel.

However, when I try to register a new user an `Internal Server Error` message pops up, and I see that the user already registered. Here is the log:

	I20151214-07:27:27.648(-5)? [method] checkRegistrationSecretURL RegMeVGChTM
	I20151214-07:28:09.468(-5)? [publish] settings
	I20151214-07:28:09.474(-5)? [publish] permissions
	I20151214-07:28:09.490(-5)? [methods] hasPermission ->  arguments: { '0': '5KbQ4
	4FY8vjyKtSo7', '1': 'manage-integrations' }
	I20151214-07:28:09.490(-5)? [methods] getRolesForUser ->  arguments: { '0': '5Kb
	Q44FY8vjyKtSo7', '1': undefined }
	I20151214-07:28:09.493(-5)? [publish] subscription
	I20151214-07:28:09.494(-5)? [publish] userData
	I20151214-07:28:09.494(-5)? [publish] activeUsers
	I20151214-07:28:09.494(-5)? [publish] admin-settings
	I20151214-07:28:09.495(-5)? [methods] hasPermission ->  arguments: { '0': '5KbQ4
	4FY8vjyKtSo7', '1': 'view-privileged-setting' }
	I20151214-07:28:09.495(-5)? [methods] getRolesForUser ->  arguments: { '0': '5Kb
	Q44FY8vjyKtSo7', '1': undefined }
	I20151214-07:28:09.629(-5)? [publish] activeUsers
	I20151214-07:28:10.497(-5)? [methods] hasPermission ->  arguments: { '0': '5KbQ4
	4FY8vjyKtSo7', '1': 'view-full-other-user-info' }
	I20151214-07:28:10.497(-5)? [methods] getRolesForUser ->  arguments: { '0': '5Kb
	Q44FY8vjyKtSo7', '1': undefined }
	I20151214-07:28:10.523(-5)? [publish] fullUserData  50
	I20151214-07:28:13.382(-5)? [methods] hasPermission ->  arguments: { '0': '5KbQ4
	4FY8vjyKtSo7', '1': 'view-other-user-channels' }
	I20151214-07:28:13.382(-5)? [methods] getRolesForUser ->  arguments: { '0': '5Kb
	Q44FY8vjyKtSo7', '1': undefined }
	I20151214-07:28:13.391(-5)? [publish] userChannels qBQqGxiGJjs6JyTnb
	I20151214-07:28:16.225(-5)? [methods] hasPermission ->  arguments: { '0': '5KbQ4
	4FY8vjyKtSo7', '1': 'delete-user' }
	I20151214-07:28:16.226(-5)? [methods] getRolesForUser ->  arguments: { '0': '5Kb
	Q44FY8vjyKtSo7', '1': undefined }
	I20151214-07:28:26.882(-5)? [methods] addUserToRoles ->  arguments: { '0': '6bW8
	fvvKn3d4D6tqN', '1': 'user' }
	I20151214-07:28:26.958(-5)? Exception while invoking method 'registerUser' AuthE
	rror: Invalid login - 535 Authentication failed: Bad username / password
	I20151214-07:28:26.959(-5)?     at Object.Future.wait (C:\Users\Administrator\Ap
	pData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\
	server-lib\node_modules\fibers\future.js:398:15)
	I20151214-07:28:26.959(-5)?     at smtpSend (packages/email/email.js:86:1)
	I20151214-07:28:26.959(-5)?     at Object.Email.send (packages/email/email.js:18
	5:1)
	I20151214-07:28:26.959(-5)?     at Object.Email.send (packages/meteorhacks_kadir
	a/lib/hijack/email.js:10:1)
	I20151214-07:28:26.959(-5)?     at AccountsServer.Accounts.sendVerificationEmail
	 (password_server.js:781:9)
	I20151214-07:28:26.960(-5)?     at [object Object].Meteor.methods.registerUser (
	server/methods/registerUser.coffee:18:13)
	I20151214-07:28:26.960(-5)?     at [object Object].methodMap.(anonymous function
	) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
	I20151214-07:28:26.960(-5)?     at maybeAuditArgumentChecks (livedata_server.js:
	1698:12)
	I20151214-07:28:26.961(-5)?     at livedata_server.js:708:19
	I20151214-07:28:26.961(-5)?     at [object Object]._.extend.withValue (packages/
	meteor/dynamics_nodejs.js:56:1)
	I20151214-07:28:26.961(-5)?     - - - - -
	I20151214-07:28:26.961(-5)?     at SMTPClient._actionAUTHComplete (C:\Users\Admi
	nistrator\AppData\Local\.meteor\packages\email\1.0.8\npm\node_modules\simplesmtp
	\lib\client.js:826:23)
	I20151214-07:28:26.962(-5)?     at SMTPClient._onData (C:\Users\Administrator\Ap
	pData\Local\.meteor\packages\email\1.0.8\npm\node_modules\simplesmtp\lib\client.
	js:329:29)
	I20151214-07:28:26.962(-5)?     at CleartextStream.emit (events.js:95:17)
	I20151214-07:28:26.962(-5)?     at CleartextStream.<anonymous> (_stream_readable
	.js:765:14)
	I20151214-07:28:26.962(-5)?     at CleartextStream.emit (events.js:92:17)
	I20151214-07:28:26.963(-5)?     at emitReadable_ (_stream_readable.js:427:10)
	I20151214-07:28:26.963(-5)?     at _stream_readable.js:420:7
	I20151214-07:28:26.963(-5)?     at process._tickDomainCallback (node.js:492:13)


And email never reached us. Previously we can see the following error:

	I20151214-02:32:52.050(-5)? [method] checkRegistrationSecretURL RegMeVGChTM
	I20151214-02:33:26.298(-5)? [methods] addUserToRoles ->  arguments: { '0': 'oHRo
	rG59BcSN67roG', '1': 'user' }
	I20151214-02:33:26.322(-5)? ====== BEGIN MAIL #10 ======
		I20151214-02:33:26.323(-5)? (Mail not sent; to enable sending, set the MAIL_URL
		environment variable.)
	I20151214-02:33:26.324(-5)? MIME-Version: 1.0
	I20151214-02:33:26.324(-5)? To: ravimallya@gmail.com
	I20151214-02:33:26.324(-5)? Subject: How to verify email address on VoiceGlance
	Chat
	I20151214-02:33:26.324(-5)? Content-Type: text/plain; charset=utf-8
	I20151214-02:33:26.325(-5)? Content-Transfer-Encoding: quoted-printable
	I20151214-02:33:26.325(-5)?
	I20151214-02:33:26.325(-5)? Hello,
	I20151214-02:33:26.326(-5)?
	I20151214-02:33:26.326(-5)? To verify your account email, simply click the link
	below.
	I20151214-02:33:26.326(-5)?
	I20151214-02:33:26.326(-5)? http://206.80.45.80:3000/login/#/verify-email/oA-UMB
	3nWRyvRKrlPZjLDXOrjD4n5jmOimoZzozHtmn
	I20151214-02:33:26.327(-5)?
	I20151214-02:33:26.327(-5)? Thanks.
	I20151214-02:33:26.327(-5)?
	I20151214-02:33:26.328(-5)? ====== END MAIL #10 ======

How to fix the issue?

Thanks a lot.
