### ISSUE TITLE
user mentions in code blocks lead to auto-join the channel

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#16510]
### Description:

From time to time users paste a codeblock containing user mentions like that:
`
@user1
@user2
@user3
`

and so on. Now all that users are auto-joining the channel the codeblock was pasted to.

### Steps to reproduce:

1. Paste a codeblock with user mentions to channel x
2. All users in the codeblock are dragged into the channel x

### Expected behavior:

No auto-join for mentions in codeblocks.

- Version of Rocket.Chat Server: 2.4.7
- Operating System: Linux
- Deployment Method: docker

**Comment by subham103** [comment]
Currently, the user is extracted from the code-block or any expression and is dragged to the channel. Will try to fix this issue:)
