### ISSUE TITLE
Username not displayed if the first message of consecutive messages is deleted

### ISSUE THREAD

**Issue by lisa761** [RocketChat/Rocket.Chat#16538]
### Description:
If we send consecutive messages and then delete the first message, the coming messages do not show the username anymore.

### Steps to reproduce:

1. Send at least two messages consecutively
2. Delete the first message

### Expected behavior:
The username of the person who sent the message should be displayed.

### Actual behavior:
Refreshing the page does seem to work and the username is displayed again but refreshing should not be required.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.5.0-develop
- Operating System: Ubuntu 18.04 LTS x64
- NodeJS Version: 8.17.0 - x64
- MongoDB Version: 4.0.6

### Client Setup Information

- Desktop App or Browser Version: Firefox Browser 72.0.2 (64-bit)
- Operating System: Ubuntu 18.04 LTS x64

### Additional context

![Screenshot from 2020-02-10 00-27-44](https://user-images.githubusercontent.com/52909743/74108080-5cac5280-4b9c-11ea-9731-0ee657173efd.png)
![Screenshot from 2020-02-10 00-27-54](https://user-images.githubusercontent.com/52909743/74108082-5ddd7f80-4b9c-11ea-84f7-cc2b8f12ea11.png)

**Comment by ritvikjain99** [comment]
Already been opened, and solved, but saying it's a copy of your previous issue, it was closed ! 
#16406

**Comment by lisa761** [comment]
Okay yes, I will close this issue then, I apologize for missing it.

**Comment by ritvikjain99** [comment]
No don't apologise, it's actually an issue, which app can't run with, but no one is acknowledging it!
