### ISSUE TITLE
[BUG] File uploads in Rocket Chat are incredibly slow, but there is a simple solution for it.

### ISSUE THREAD

**Issue by recklessnl** [RocketChat/Rocket.Chat#16542]
### Description:
See this thread for a lot more information: https://forums.rocket.chat/t/file-uploads-are-super-slow-because-theyre-sent-in-many-small-post-requests-wtf/4600

In Rocket chat, apparently the files are uploaded via many small sequential POST requests. For example, a 100KiB file (dd’d from /dev/zero) takes four requests to upload! And a 6.05mb jpeg took about 160 requets to upload. And each request takes around 300ms before the next one will be sent, causing the upload to take a stupidly long time. See this gif: https://owyf.qonq.gq/ 18

Why does it do this? It’s incredibly inefficient and causes file uploads to be super slow, especially for those with high latency.

Rocket.chat uses this for uploads https://github.com/jalik/meteor-jalik-ufs#uploading-files 8 and the uploader can be configured with custom chunk sizes as well as disabling adaptive mode which will make chunks large enough to upload at 80% of bandwidth up to a certain chunk size limit.

And this is the only use of UploadFS.Uploader i’ve found in rocket chat codebase using github search https://github.com/RocketChat/Rocket.Chat/blob/d53e264b83ccc971236123853e4b68c9eb6beeb4/app/file-upload/lib/FileUploadBase.js#L56-L67 2 and it doesn’t specify anything so looking in the code, the default chunk size is 32KiB and default max size for adaptive is 4K(i?)B (4 * 1024 * 1000). So I think I can just disable adaptive thing as it doesn’t seem to help at all and set the chunk size to whatever is the highest upload limit for the gateways (i.e. 1MB for nginx or 50MB for cloudflare) and it’ll use just one request if the file is smaller, or split it into chunks if larger, which is actually useful in this case.

**The solution would be to allow admins to set a much higher chunk size, so that upload speed can be MUCH increased.** A user (that I quoted the above from) in the forums already did it to great success. The problem is that every time snaps updates, I lose this edit. **This should be a setting in the Administration panel.**

### Steps to reproduce:
Upload any larger file on a LAN connection and observe the incredibly slow upload speeds.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version:  3.6.14

### Client Setup Information

- Desktop App or Browser Version: Firefox version 72
- Operating System: Any

**Comment by recklessnl** [comment]
Can anybody fix this? It should be fairly simple. @MarcosSpessatto @ritvikjain99 @manosriram

**Comment by geekgonecrazy** [comment]
I think will be fixed by: https://github.com/RocketChat/Rocket.Chat/pull/16617

**Comment by sampaiodiego** [comment]
agreed @geekgonecrazy . @recklessnl may you test our current `develop` version? `3.1.0-develop` actually. since we're now using a single POST request to send files you should be able to use total bandwidth available.

**Comment by recklessnl** [comment]
@sampaiodiego I have a snaps install - what's the best way to update to that version? And in case things break, how do I get back to this stable version?

Once I know how to I will definitely test it out as soon as I can.

**Comment by sampaiodiego** [comment]
@recklessnl this is already available via snaps on `3.x/stable` channel, starting on rocket.chat version 3.0.4. you can install doing  `sudo snap install rocketchat-server --channel=3.x/stable`

**Comment by PvUtrix** [comment]
I'm still experiencing this on 3.18.3. It's strange as I didn't have this on a previous server.
I've began experiencing this after backing up and restoring on a new server with identical specs

**Comment by shyokinmv** [comment]
aggree with PvUtrix
Also have reinstalled rocket server via snap with previous backup and later restore.
and after that even small files ex. png image 2x2 pixels i have created for testing are uploading extreemly slow.
During that proccess i noteced very high disk activity with iotop
`Total DISK READ :     218.32 M/s | Total DISK WRITE :       3.67 K/s`
`Actual DISK READ:     218.54 M/s | Actual DISK WRITE:     117.60 K/s`
`  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND`
` 1666 be/4 root      218.30 M/s    0.00 B/s  0.00 % 78.32 % mongod --bind_ip 127.0.0.1 --pidfilepath /var/snap/rocketchat-server/common/mongod.pid --smallfiles --journal --dbpath=/var/snap/rocketchat-server/common --replSet rs0 [conn26]`
` 1514 be/4 root        0.00 B/s    3.67 K/s  0.00 %  5.24 % mongod --bind_ip 127.0.0.1 --pidfilepath /var/snap/rocketchat-server/common/mongod.pid --smallfiles --journal --dbpath=/var/snap/rocketchat-server/common --replSet rs0 [WTJourn.Flusher]`
` 1551 be/4 root       14.70 K/s    0.00 B/s  0.00 %  3.21 % mongod --bind_ip 127.0.0.1 --pidfilepath /var/snap/rocketchat-server/common/mongod.pid --smallfiles --journal --dbpath=/var/snap/rocketchat-server/common --replSet rs0 [rsSync]
`
