### ISSUE TITLE
Search in directory by custom field "select"

### ISSUE THREAD

**Issue by moriccelli** [RocketChat/Rocket.Chat#16554]
## My Setup
- Operating System: Windows
- App Version: 2.17.1
- Installation type: exe

- [ ] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
1. Create custom field
"role": {
  "type": "select",
  "defaultValue": "student",
  "options": ["teacher", "student"],
  "required": true,
  "modifyRecordField": {
   "array": true,
   "field": "roles"
  }
2. Put the custom field in "Fields to cosider in search"
3. Select some teachers and students for several accounts.
4. Go to directory and search for "teacher"

### Current Behavior
no records found

### Expected Behavior
Find some records. Like you search the text field.

**Comment by cdce8p** [comment]
It does work for me. I'm using v3.2.0
