### ISSUE TITLE
sending a message to slack doesn't work after renaming a channel and restarting the server

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#16563]
### Description:

When SlackBridge enabled and work then after renaming a channel to Rocket.Chat and restarting the server messages are not sent to Slack. It is breaking because populateMembershipChannelMap searches channels by name, even if importId was added

### Steps to reproduce:

1. set up and enable SlackBridge
2. check that it works
3. rename channel to rocket.chat
4. restart the server
5. send message from slack (the message will be sent)
6. send message from rocket.chat

### Expected behavior:

the message will be sent to slack 

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.17
- MongoDB Version: 4.0

**Comment by caesarcxiv** [comment]
Running 3.7 with slack bridge - issue reappeared. Only way to resolve was to uninvite bot from slack and invite to create a new channel.
