### ISSUE TITLE
LDAP at 2.42

### ISSUE THREAD

**Issue by abdalamariano** [RocketChat/Rocket.Chat#16567]
Hi guys, i have a issue with ldap sync
conection ok... and on sync button a message appear "internal server error"

I20200212-03:38:55.547(-8) Exception while invoking method 'ldap_sync_now' Error:  “scope”: “sub”=* is invalid     at _buildFilterTree (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldap-filter/lib/index.js:200:13)     at _buildFilterTree (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldap-filter/lib/index.js:163:28)     at _buildFilterTree (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldap-filter/lib/index.js:158:28)     at _parseString (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldap-filter/lib/index.js:411:17)     at Object.parse (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldap-filter/lib/index.js:422:12)     at Object.parseString (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldapjs/lib/filters/index.js:176:25)     at Client.search (/snap/rocketchat-server/1420/programs/server/npm/node_modules/ldapjs/lib/client/client.js:769:30)     at LDAP.searchAllPaged (app/ldap/server/ldap.js:391:15)     at LDAP.searchUsersSync (app/ldap/server/ldap.js:244:16)     at importNewUsers (app/ldap/server/sync.js:480:7)     at MethodInvocation.ldap_sync_now (app/ldap/server/syncUsers.js:24:3)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by talheim-it** [comment]
@abdalamariano can you provide the ldap config?
Do you use ldap or ldaps?

**Comment by abdalamariano** [comment]
ehm can share u the rocket chat setting
ADDC is on windows server 2012 r2
rocketchat on ubuntu 18.04
im newbie on this.
i could make sync the security groups but .... use that to make the users...
[https://aws1.discourse-cdn.com/business4/uploads/rocketchat/optimized/2X/b/b0704c8c1e4c22a1e08ff5c0e9530e7c9ab5a5ba_2_638x500.png](url)

**Comment by abdalamariano** [comment]
ADDC Windows Server 2012 r2
RocketChat Server on Ubuntu 18.04

im junior, how can i provide you the ldap config?

**Comment by matthewbassett** [comment]
@abdalamariano Couple of things for you to try here...
- Your base DN doesn't look right to me... You have uid=#{username},cn=users,dc=bernal it should look more like this I think: ou=users,dc=bernal
- Your User DN (Not sure if this format is an issue or not) But in mine I used the UPN so for your case maybe marianoabdalaadm@bernal probably doesn't make a difference, but worth a shot.
- try switching off sync user avatar (This has given me issues in the past and my guess is you aren't using that feature)
- Search  Field: I think you want sAMAccountName or userprincipalname (Or both separated by a comma)
- You may have some issues in your Enable LDAP User Group Filter, you could try turning that off temporarily to see if that is it as well.

**Comment by abdalamariano** [comment]
ok, i will try tomorrow at work 00:27 here

**Comment by abdalamariano** [comment]
the problems is my AD is order by an OU call = users -> with subOU. one time, the rocketchat takes rare users with extrange name and sync ok, but not the OU that i need.

**Comment by abdalamariano** [comment]
how can i provide you a LDAP cfg file to be more easy solve the problem

**Comment by KrisJohnstone** [comment]
Did you make the above changes? Otherwise why no provide the config file the same way you did before?

**Comment by matthewbassett** [comment]
@abdalamariano what is the path of sub ou's? I can write that path for you if you tell me each OU starting with the top and working down.

**Comment by abdalamariano** [comment]
OU = usuarios
sub ous are a lots of do you need the list?

**Comment by matthewbassett** [comment]
So basically I need the path of OU's down to the OU that you actually need to sync. Sorry, somehow missed your response on this. So if you have a top OU called Users then inside of that another OU called testing then inside it another OU called FinalOU. and FinalOU is the actual OU that you want to sync to RC. so the path would be Users-->testing-->FinalOU If you can give it to me like that I can show you what that should look like.
