### ISSUE TITLE
Regression: admin users table not reactive anymore

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#16564]
### Description:

Once I as an admin manually create a new user, the user is not immediately appearing on the users list.
I need to refresh the page to see it.

### Steps to reproduce:

1. Go to `/admin/users`
2. Use the tab bar to create a new user
 
### Expected behavior:

The newly created user shall appear in the main list

### Actual behavior:

The toast confirmation appear, but you need to refresh the page to see it.

### Server Setup Information:

- Version of Rocket.Chat Server: `3.0-develop` (3abc887e7507a901609b751b72fcc9dd50075015)

**Comment by mrsimpson** [comment]
@ggazzo this may be one for you

**Comment by adrianovieira** [comment]
I also have similiar behaviour on other administrator pages, such as:

- integrations
- incoming webhooks -> scripts field.

For those pages we need to refresh it to get that page rendered correctly.

But, in our case the Server Setup Information: `2.4.7`

**Comment by mrsimpson** [comment]
Also nasty: create a new role in permissions. After saving and going back, the page needs to be refreshed before you can see the new role in the permissions table.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
