### ISSUE TITLE
Inactive users in Members List of channels.

### ISSUE THREAD

**Issue by muditjuneja** [RocketChat/Rocket.Chat#16574]
### Description:
Deactivating users will make any direct channels with those read-only. But these users should not be visible in public channels when the "Members List" option is clicked.

### Steps to reproduce:

1. Add a demo user to any public channels
2. Deactivate that demo user via Users setting (Options -> Administration -> Users -> Find the user -> Click User -> Click **...** (three dots in the popup) -> Click Deactivate
3. Go back to that channel.
4. Click the "Members List" option on the right-top sidebar
5. You will be able to view the deactivated user

But if you try to create a direct room with him, you will be redirected to a read-only room which is fine.

### Expected behavior:

Deactivated users should not be visible in the "Members List" option of a public channel or any private group.

I looked in code and found that the query that is returning users is not considering the "active" field in the User model. I do have a fix. How do I contribute?

### Actual behavior:

<img width="1168" alt="Screenshot 2020-02-12 at 10 04 56 PM" src="https://user-images.githubusercontent.com/15162221/74356341-337e0300-4de4-11ea-9cdb-270693076e46.png">
<img width="397" alt="Screenshot 2020-02-12 at 10 05 42 PM" src="https://user-images.githubusercontent.com/15162221/74356590-9d96a800-4de4-11ea-9cb2-5e1b80b63a41.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3
- Operating System: Mac OS Mojave
- Deployment Method: npm start

**Comment by ashwaniYDV** [comment]
I would like to take this up

**Comment by gabriellsh** [comment]
Hey @muditjuneja, you can refer to our [Developing Guide](https://rocket.chat/docs/contributing/developing/), there you'll find the information you need. Thanks for your contribution.

**Comment by ashwaniYDV** [comment]
@muditjuneja Feel free to contribute by submitting PR's even if someone has already solved it. Maybe you have a better solution :)
