### ISSUE TITLE
Invite links uses count even if the user is already in the room.

### ISSUE THREAD

**Issue by gabriellsh** [RocketChat/Rocket.Chat#16573]
### Description:

Users can open invite links multiple times, even if they joined the room already. This should not happen, as invite links can have limited uses.

### Steps to reproduce:

1. Go to any room.
2. Click on the users icon then invite users.
3. Copy the link and access it multiple times on the same account.
4. Go to Admin->Invites: Check your invite link, it should have counted every time you entered the room through it.

### Expected behavior:

Count only new users to the room.

### Actual behavior:

It counts every single attempt.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0-develop
- Operating System: macOS Catalina 10.15.2
- Deployment Method: Development
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 13.5.0
- MongoDB Version: 4.0.6

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 80.0.3987.87 (Official Build) (64-bit)
- Operating System: macOS Catalina 10.15.2

**Comment by ritvikjain99** [comment]
I wanna work on this, can I @gabriellsh  ?

**Comment by ritwizsinha** [comment]
@gabriellsh please review

**Comment by ritwizsinha** [comment]
@gabriellsh please review

**Comment by ritvikjain99** [comment]
Oh don't we have to ask before taking up an issue? 
Please confirm so that next time I won't wait!

**Comment by gabriellsh** [comment]
No we don't :) . Feel free to take whatever you want.

**Comment by ritwizsinha** [comment]
@ritvikjain99 you don't have to ask to work just inform that you are working on it so that someone else doesn't make a pr.

**Comment by ritwizsinha** [comment]
Also sorry I made a pr on this , I didnt see your comment.

**Comment by gabriellsh** [comment]
No, you don't need to inform anything. There's no such thing as taking issues. There can be multiple PR's per issue.

**Comment by ritvikjain99** [comment]
@ritwizsinha no brother it's fine I just wanted to be sure about protocol. 
@gabriellsh sure I would follow that!
