### ISSUE TITLE
getting localhost as upload domain

### ISSUE THREAD

**Issue by mikkeschiren** [RocketChat/Rocket.Chat#1657]
When uploading files in the chat I am getting localhost as path, like http://localhost:3000/ufs/rocketchat_uploads/FZ6YyqcTrQBqyLC2R.png instead of https://mydomain.net/ufs/rocketchat_uploads/FZ6YyqcTrQBqyLC2R.png

I did not use the docker image for the install of rocket chat.

**Comment by engelgabriel** [comment]
Did you configure the Site URL on the admin panel?

**Comment by mikkeschiren** [comment]
Hm. Now I feel stupid, did not realize that I needed to do that, added an admin user, configured site URL and now it works.
