### ISSUE TITLE
Cannot find module UIKitIncomingInteractionContainer

### ISSUE THREAD

**Issue by bhardwajaditya** [RocketChat/Rocket.Chat#16577]
### Description:

I just updated my local Rocket.Chat repository with upstream develop and I encountered an apps-engine error.

### Steps to reproduce:

1. Clone the repository
2. run **meteor npm i**
3. run **meteor npm start**

### Expected behavior:

Rocket.Chat application

### Actual behavior:

![apps-engine error](https://user-images.githubusercontent.com/23612313/74367692-4d294580-4df8-11ea-93bd-0cf6229da97e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3
- Operating System: Ubuntu
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.6

**Comment by d-gubert** [comment]
I haven't been able to reproduce this error.

What version of the Apps-Engine is installed on your server?

**Comment by bhardwajaditya** [comment]
> I haven't been able to reproduce this error.
> 
> What version of the Apps-Engine is installed on your server?

1.12.0

**Comment by d-gubert** [comment]
This is the official version that contains all UIKit APIs, this error should not occur.

Have you tried removing your `node_modules` folder and reinstalling your dependencies?

**Comment by bhardwajaditya** [comment]
> This is the official version that contains all UIKit APIs, this error should not occur.
> 
> Have you tried removing your `node_modules` folder and reinstalling your dependencies?

No not yet, will try and let you know.

**Comment by bhardwajaditya** [comment]
> This is the official version that contains all UIKit APIs, this error should not occur.
> 
> Have you tried removing your `node_modules` folder and reinstalling your dependencies?

Same error even after trying this

**Comment by d-gubert** [comment]
When does this error occur?

**Comment by bhardwajaditya** [comment]
> When does this error occur?

When I start the application using **meteor npm start**. It shows in the server terminal as well as in the browser console (as shown in the screenshot).

**Comment by d-gubert** [comment]
Have you modified the code? Do you have any app installed? I'm trying it with the `develop` branch and can't see this error, so it's probably some kind of change on your environment 😞
