### ISSUE TITLE
MULTI LDAP 2.42

### ISSUE THREAD

**Issue by abdalamariano** [RocketChat/Rocket.Chat#16593]
HI GUYS. i can finally get worked rocketchat on my domain, but the boss is asking to add another domain with another ip diferent range... is it possible?

**Comment by robinreinhardt** [comment]
Hey @abdalamariano , do you mean a second LDAP Host or just a IP for accessing into RC?

**Comment by abdalamariano** [comment]
> Hey @abdalamariano , do you mean a second LDAP Host or just a IP for accessing into RC?

i need to put 2 differents domains on the same rocket server chat.
2 ldaps
firstcampany.domain 192.168.1.18 own AD
secondcompany.domain 10.10.10.5 own AD

**Comment by frdmn** [comment]
Multiple LDAP backends are currently not possible.

Duplicate of #5058.
