### ISSUE TITLE
Documentation error in the administration-inline-documentation

### ISSUE THREAD

**Issue by mc** [RocketChat/Rocket.Chat#16592]
(version 2.4.2, commit d57a64dee62fbf8abff75006903628a1001312ec)

goto 
 - Administation
 - Menu, Settings: LDAP 
 - Group, Synchronise / Import
 - Option, Field for username

In the description it says that (German):

Es können auch Template-Tags wie `#{givenNamen}.#{sn}` verwendet werden.

It needs to read:

Es können auch Template-Tags wie `#{givenName}.#{sn}` verwendet werden.

If you dont pay attention and copy&paste this, username will be undefined.(surname), as LDAP has no attribute givenName_n_, it is givenName.

-mc

**Comment by geekgonecrazy** [comment]
https://rocket.chat/docs/contributing/translating/#translating

**Comment by frdmn** [comment]
I've just updated the string on LingoHub. Should be fixed next time we pull the latest changes from there.
