### ISSUE TITLE
[BUG] Video message send to wrong user

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16590]
### Description:

Second Video message send to wrong user (User1 instead User2)

### Steps to reproduce:

1. Send **Video message** to **User1**
2. Go to **User2** DM and send **another one Video message to User2**
3. **Video message send to User1**, **but not to User2** as it should.

### Expected behavior:

**Video message to User1 should be send to User1 and Video message to User2 should be send to User2 and not User1**

### Actual behavior:

**Video message for User2 send to User1, but not to User2 as it should.**

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: RC.Electron 2.17.5 and Google Chrome 80
- Operating System: Windows 10

**Comment by ankar84** [comment]
Could be fixed in https://github.com/RocketChat/Rocket.Chat/pull/16113

**Comment by ggazzo** [comment]
it was fixed actually, please update your server... any problem, please let me know
