### ISSUE TITLE
Possible to turn off link preview?

### ISSUE THREAD

**Issue by mikkeschiren** [RocketChat/Rocket.Chat#1659]
Are there a setting to turn off link preview? (can not find that in the admin panel)

**Comment by marceloschmidt** [comment]
Yes. Go to API -> Embed.

![image](https://cloud.githubusercontent.com/assets/1986378/11808874/5b568930-a30a-11e5-8fc6-b85a3b39165d.png)

**Comment by mikkeschiren** [comment]
Not really what I want to achieve, I want to keep embed, but not having the preview of the site - with title and the short text from it.

/mikke

**Comment by miscs** [comment]
maybe this could help: https://github.com/RocketChat/Rocket.Chat/issues/1664 ?

**Comment by Syirrus** [comment]
How can you disable link preview?  There is no API settings under the admin panel.

**Comment by graywolf336** [comment]
@Syirrus `Administration -> Message -> Embed`
