### ISSUE TITLE
Can't send Apple keynote files through the Upload File feature.

### ISSUE THREAD

**Issue by Bengrunt** [RocketChat/Rocket.Chat#16594]
### Description:

I'm trying to allow users to send Apple keynote files through the file upload feature.
I managed to do it for Apple `pages` and `numbers` files, allowing the following MIME types:
 * application/x-iwork-pages-sffpages
 * application/x-iwork-keynote-sffkey
 * application/x-iwork-numbers-sffnumbers
 * application/vnd.apple.numbers
 * application/vnd.apple.pages
 * application/vnd.apple.keynote

The first 3 types seem to be for an older version of the application, but whatever.
I also allowed the `application/zip` MIME type which is the type given by the linux `file` command:
```
$ file benjamin.key
benjamin.key: Zip archive data, at least v2.0 to extract
```

### Steps to reproduce:

1. Click on the `+` sign in a chat window, select `Add files from computer` and choose Apple Keynote file on computer 
__OR__
1. Just drag and drop an Apple keynote file into the conversation.

The file is called `something.key` by the way.

### Expected behavior:

Get the file transferred to the other user. :)

### Actual behavior:

Get `Unaccepted file type` error: `*.key`.

![rocketchat-keynote-upload-bug](https://user-images.githubusercontent.com/5541437/74440910-278b5300-4e6f-11ea-915b-4a5c87cdd991.png)

If I zip it, it works (since I allowed the `application/zip` MIME type).
If I rename it, it only works if it's a well known and accepted file extension, such as `.pages`, `.numbers`, `*.txt` or `.zip`. 
Otherwise it does not work, for instance I tried `.k`, `.toto` and even no extension at all.

So I assume there's some kind of a second file filter that I can't configure via the admin console or something? There's some logic in preventing `.key` files from being exchanged since they could be private keys or something like that but my last test makes me think that this is not the reason why it does not work.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0
- Operating System: Linux CentOS 7 
- Deployment Method: docker compose
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled (not sure that's what you want though)
- NodeJS Version: 8.17.0
- MongoDB Version: 4.2.2

### Client Setup Information

- Desktop App or Browser Version: both mobile, desktop and browser clients experience this, to the best of my knowledge.
- Operating System: Both Windows and MacOSX and quite probably Linux as well, but I didn't check.

Thanks for the help :)

**Comment by mar-v** [comment]
Same issue with .cs files (despite adding text/plain MIME type to the accepted media files, .cs files are not being uploaded, giving the same error. [https://github.com/RocketChat/Rocket.Chat/issues/16836](url)

**Comment by Bengrunt** [comment]
> 
> 
> Same issue with .cs files (despite adding text/plain MIME type to the accepted media files, .cs files are not being uploaded, giving the same error. #16836

That looks very much like the same issue indeed.

**Comment by ggazzo** [comment]
unfortunately, the browser doesn't provide the mime type... so we receive a generic mime `application/octet-stream`, with our current logic its impossible cover all mime types...

I'm proposing allow the admin install (using rocketchat apps) file validators, so you could install an app that knows the how to indentify your file....


in your case would be something like 

```javascript
import { Buffer } from 'buffer';
import {
    IAppAccessors,
    ILogger,
} from '@rocket.chat/apps-engine/definition/accessors';
import { App } from '@rocket.chat/apps-engine/definition/App';
import { IAppInfo } from '@rocket.chat/apps-engine/definition/metadata';
import { IPreFileUploadAllow } from '@rocket.chat/apps-engine/definition/messages';

export class ImageFilesApp extends App implements IPreFileUploadAllow {
    constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
        super(info, logger, accessors);
    }

    public async executePreFileUploadAllow({ file, stream: buffer }: any) {
        const KEYNOTE_HEADER = Buffer.from([0x50, 0x4b, 0x03, 0x04, 0x14]);

        if (/\.(key|numbers|pages)$/.test(file.name) && buffer.compare(KEYNOTE_HEADER, 0, 5)){
            return false;
        }

        return true;
    }
}
```
https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/239

**Comment by JohnLukeP** [comment]
Hi, are tthere any updates on this? Problem is still present on Rocketchat 3.6.1
