### ISSUE TITLE
Route to get updated and deleted roles after a date

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat#16599]
We only have a REST API to list roles: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/api/server/v1/roles.js#L8

We should have another route to fetch `updated` and `deleted` roles after a date, so it'll be easier to maintain a local database on mobile.

**Comment by ashwaniYDV** [comment]
I am working on it.

**Comment by ashwaniYDV** [comment]
@diegolmello I have added a route to get updated roles after a date
