### ISSUE TITLE
Route to get updated and deleted slash commands after a date

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat#16600]
We only have a REST API to list slash commands: https://github.com/RocketChat/Rocket.Chat/blob/develop/app/api/server/v1/commands.js#L26

We should have another route to fetch updated and deleted slash commands after a date, so it'll be easier to maintain a local database on mobile.

**Comment by ritwizsinha** [comment]
I am woeking on it

**Comment by MarcosSpessatto** [comment]
@ritwizsinha how is it going? Are you working on that?

**Comment by ashwaniYDV** [comment]
@MarcosSpessatto There is no date field in the slashcommands.
Please guide.

![Screenshot from 2020-03-16 05-09-25](https://user-images.githubusercontent.com/43786728/76713039-fa6ae280-6743-11ea-8446-86e9518a67a7.png)

**Comment by MarcosSpessatto** [comment]
@ashwaniYDV yes you are right, we can't do that for now, because we don't have this Date field to be able to filter. I'm closing the issue for now.
