### ISSUE TITLE
Cannot close chats

### ISSUE THREAD

**Issue by jdaviescoates** [RocketChat/Rocket.Chat#16602]
It seems only the visitor who initiates the LiveChat can end a chat (but they often don't because to do so they have to click the tiny options word bottom left which is easily missed).

This leaves lots of "current chats" open which are actually no longer live at all.

Could we make the guest closing their browser window automatically close the chat?
And make it possible for agents to end chats too?

Thanks!

**Comment by renatobecker** [comment]
Hi @jdaviescoates 
Yes, the agents can close conversations from their side, they just need to open the contextual bar and then close the chat.

![Screen Shot 2020-02-14 at 09 42 26](https://user-images.githubusercontent.com/59577424/74532658-8358e900-4f0e-11ea-8971-854319ed9a29.png)

**Comment by jdaviescoates** [comment]
Hmz, great, makes sense! But I don't actually see any of that in my contextual bar:

![missing_context_options](https://user-images.githubusercontent.com/2113743/74533034-8660d300-4f28-11ea-8540-f12f7518b3c5.png)

Aha, doh! I was clicking on the three little dots of the right instead of the (i) button on the left. Found it, thanks! :)

![it_works!](https://user-images.githubusercontent.com/2113743/74533130-c922ab00-4f28-11ea-8be1-518ba96068cf.png)
