### ISSUE TITLE
How to remove unwanted homosexual emojis?

### ISSUE THREAD

**Issue by standev** [RocketChat/Rocket.Chat#16616]
Whenever I begin to type`:` in the intention of typing something as ordinary as `:+1:`, emoji popups opens with default suggestion of some homosexuals kissing. There's ton of such emojis, like homosexual "families" and so on. I never intend to use them. How can I remove the whole rainbow package please?
![image](https://user-images.githubusercontent.com/3965564/74649380-b35af300-517f-11ea-9547-297fcc48d550.png)

**Comment by mauricemeyer** [comment]
My suggestion would be to stop using Rocket.Chat as you’re clearly not in line with the [Code of Conduct](https://github.com/RocketChat/Rocket.Chat/blob/develop/CODE_OF_CONDUCT.md).

**Comment by localguru** [comment]
It's open source. Forke it, create a community that is compatible with your confused ideas and stay there.

**Comment by MartinSchoeler** [comment]
As it was mentioned @mauricemeyer this issue goes against our code of conduct, as well as going against our guidelines for GitHub Issues. I will be closing this.
