### ISSUE TITLE
Files do not disappear after deletion

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#16614]
### Description:

After deleting a file from the files list, the file doesn't disappear

### Steps to reproduce:

1. Open room
2. Open room menu, go to files list
3. Select delete file

### Expected behavior:

File disappear from list

### Actual behavior:

![delete-file-bug](https://user-images.githubusercontent.com/19654261/74642368-ab597e00-5194-11ea-8037-1e906a02278f.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.7
- MongoDB Version: 4.0

**Comment by ritwizsinha** [comment]
@antkaz this issue is fixed in my version of rocketchat. Here is my version specifics 
![image](https://user-images.githubusercontent.com/43509699/74645345-bb299000-519d-11ea-9375-7d9ae1a12ca1.png)

**Comment by antkaz** [comment]
hmmm.... Yes, it works. Maybe the problem is on my side. I close this issue. Thanks @ritwizsinha

**Comment by antkaz** [comment]
I found the problem. If "Show Deleted status" is enabled, the file does not disappear. I reopen this issue.
![image](https://user-images.githubusercontent.com/19654261/75240000-762cdb80-57e5-11ea-92da-a5ea4c605813.png)

**Comment by subham103** [comment]
This issue might be because of updating the storage for the file but not sending the response to the frontend, which upon refresh get fetched by the frontend and is updated. I will try to investigate and try to solve this issue:)

**Comment by antkaz** [comment]
It doesn't work in 3.5.0-develop
