### ISSUE TITLE
API info shows tag of wrong version

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1661]
{
  "version": "0.9.0",
  "compile": {
    "date": "2015-12-14T13:02:12.661Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 5097484288,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2626",
    "branch": "master",
    "tag": ""
  },
  "commit": {
    "hash": "0ea50588e3b899d4d8e1173da4a661cf3654749b",
    "date": "Mon Dec 14 10:55:53 2015 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1655 from RocketChat/develop"
  },
  "tag": "v0.8.0",
  "branch": "HEAD"
}

**Comment by engelgabriel** [comment]
The TAGs happens after the PR.. so we need to think how to do it differently... not sure it is possible to change both at the same time. The iead was to stop building assets on master form PRs, and only build from TAGs.. that would fix this problem.

**Comment by geekgonecrazy** [comment]
![image](https://cloud.githubusercontent.com/assets/51996/15203100/ec0f5300-17c5-11e6-8ef8-b1055c4026aa.png)

Now that our api info is like this, is this what we were aiming for?
