### ISSUE TITLE
I use trad.chinese.

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#16615]
I update Rocket.chat to 3.0
I use language is trad.chinese. I upgrade to 3.0.0 it's use simp.chinese.
Trad.Chinese is use by Taiwan.
Simple.Chinese is use by PRC.
Please check attachment.
![2020-02-17_181353](https://user-images.githubusercontent.com/6081927/74644578-74459580-51b1-11ea-852e-804fd78dd5d7.png)

**Comment by gabriellsh** [comment]
Hey @akong77, could you make a PR on this? Our translations are mostly made by contributors, we'd love to get your help on this. Thank you for your contribution.
