### ISSUE TITLE
customer can't use Chinese as name

### ISSUE THREAD

**Issue by zhanggaoxuan** [RocketChat/Rocket.Chat#16628]
customer can't use Chinese as name, I found that only support English, hope can solve this issue

**Comment by gabriellsh** [comment]
Hey, You can try and go to Administration -> General -> UTF8 and change UTF8 Names Validation to `.+`. This will allow any character to be used. You can also formulate another RegEx so there are more limits (using `.+` allow people to use some character that can display text in strange ways).

If you still face this issue, please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
