### ISSUE TITLE
Option to send conversations via email with offline notifications email

### ISSUE THREAD

**Issue by ravimallya** [RocketChat/Rocket.Chat#1662]
We need an option to send entire a channel chat or a public/private group chat, or an individual chat to the email address that we provided when registering or to a provided email Address.

I think this option is not there at present. Also, we need to get a notification email with offline messages to the users who are offline.

**Comment by geekgonecrazy** [comment]
The first part has been implemented recently.

Refer to #741 for the offline email notification.
