### ISSUE TITLE
Remove 'Reply in Thread' button from thread replies

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#16620]
### Description:

Since there is no multi-level threads in Rocket Chat, it doesn't make sense to have 'Reply in Thread' buttons under thread replies in the right hand side panel. 'Reply in Thread' button should only be visible under messages posted in the main channel.

### Steps to reproduce:

1. Go to a message that has thread replies
2. Click on the blue button
3. On the right hand side panel hover a mouse over a thread reply.
4. 'Reply in Thread' button is visible. --> should not

### Expected behavior:

'Reply in Thread' button should not be shown on the thread replies.

### Actual behavior:

'Reply in Thread' button is shown on any message.

### Server Setup Information:

Hash | ea3a31afe6084d3a7593cad3ae6055c3b01744a2
Date Fri Feb 14 22:58:46 2020 -0300
Branch HEAD
Tag 3.0.0
Author Diego Sampaio
Subject Merge pull request #16608 from RocketChat/release-3.0.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ritwizsinha** [comment]
@gabriellsh please review
