### ISSUE TITLE
It's will show undefined when I choose language to trad.chinese(Taiwan)

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#16627]
Rocket.chat server version is 3.0.0
I upgrade to 3.0.0 but language is simple chinese.I switch language to trad.chinese(Hong Kong) or trad.chinese(Taiwan) it's will show undefined.Please fix it.

**Comment by gabriellsh** [comment]
Thanks for the help.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by akong77** [comment]
OS: Debian 9.12
Browers: Firefox 73.0.1
Rocket.Chat version:Server 3.0.0 Client:2.17.5
![2020-02-21_082242](https://user-images.githubusercontent.com/6081927/74992639-a9890680-5483-11ea-833e-2f30e3063716.png)
