### ISSUE TITLE
GitHub API: Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by ramsey** [RocketChat/Rocket.Chat#16638]
### Description:

I'm running Rocket.Chat 2.4.9 with OAuth enabled for GitHub, and today, I received the following email message from GitHub:

> On February 18th, 2020 at 19:58 (UTC) your application used an access token (with the User-Agent Meteor/METEOR@1.8.3) as part of a query parameter to access an endpoint through the GitHub API.
>
> https://api.github.com/user
>
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
>
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis.
>
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

### Steps to reproduce:

1. Using Rocket.Chat 2.4.9, enable OAuth for GitHub under Administration > Settings > OAuth; provide a valid client ID, client secret, and callback URL
2. Login to Rocket.Chat using your GitHub account
3. GitHub should (at some point, within 24 hours maybe?) send an email message to the email address on file for the client ID used in step 1; the email message will be similar to that shown above

### Expected behavior:

Rocket.Chat should use the `Authorization` header for OAuth with GitHub, rather than query string parameters, which are deprecated in the GitHub API.

### Actual behavior:

Rocket.Chat uses query string parameters for OAuth with the GitHub API.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 80.0.3987.106
- Operating System: macOS Catalina

### Additional context

n/a

### Relevant logs:

n/a

**Comment by g5pw** [comment]
I'm still hitting this on rocket chat 3.2.2...
