### ISSUE TITLE
How to embed livechat?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#1663]
Hi,

I asked this in the demo chat hosted by Rocket.Chat developers. However, it may interest others as well. So I will create this issue instead.

The old code for embedding the livechat "widget" was something like this:

What's the new code to include on a page or blog for the live chat? The old one is defunct.
This is what I used prior to the new commits:
```
<script type="text/javascript">
	(function(w, d, s, f, u) {
		w[f] = w[f] || [];
		w[f].push(u);
		var h = d.getElementsByTagName(s)[0],
			j = d.createElement(s);
		j.async = true;
		j.src = 'https://myapp.tld/packages/rocketchat_livechat/livechat.js';
		h.parentNode.insertBefore(j, h);
	})(window, document, 'script', 'initRocket', 'https://myapp.tld/livechat');
</script>
```
This doesn't work any longer due to new changes. What is the new embed code?

Thanks in advance.

**Comment by sampaiodiego** [comment]
hello.. yeah, the code has changed..
Please use the code bellow (changing the domain entries):
```javascript
	<script type="text/javascript">
	(function(w, d, s, f, u) {
		w[f] = w[f] || [];
		w[f].push(u);
		var h = d.getElementsByTagName(s)[0],
			j = d.createElement(s);
		j.async = true;
		j.src = 'https://demo.rocket.chat/packages/rocketchat_livechat/assets/rocket-livechat.js';
		h.parentNode.insertBefore(j, h);
	})(window, document, 'script', 'initRocket', 'https://demo.rocket.chat/livechat');
	</script>
```
The file `/packages/rocketchat_livechat/assets/rocket-livechat.js` has ES6 code and won't work on Safari. I'll fix this later today.

In the future, you'll be able to get this embed code ( updated :smile: ) in Livechat Settings on your Rocket.Chat instance. =)

**Comment by ungentilgarcon** [comment]
hello, were are you supposed to paste this code in fact? 

regards

**Comment by sampaiodiego** [comment]
@ungentilgarcon in the place you want the livechat widget appears.
usually on your website.

**Comment by Zhangzhiyue** [comment]
Hello,  How to open user Admin's setting? livechat

regards

**Comment by mikhail-gaponov** [comment]
Hi @Zhangzhiyue, 
1) enable LiveChat
- Login as Admin and click at your name at top left corner
- Click "Administration" -> "Live Chat". Here is common part of configuration. Switch on "Enable"
- Save changes and close "Administration"
2) Сlick at your name at top left corner - Click "Live Chat" (above "Administration") -> here is "Live Chat" management (including Live Chats users).

**Comment by rishantagarwal** [comment]
@mikhail-gaponov  - 
![image](https://cloud.githubusercontent.com/assets/2218422/18836451/16d7ee30-843b-11e6-88c3-fa9e3791d24a.png)

I do not see Livechat option here . I have already enabled Live Chat from Admin Panel.

**Comment by sampaiodiego** [comment]
@rishantagarwal please double check and refresh the page.. the procedure described by @mikhail-gaponov is correct.

**Comment by YuniSocial** [comment]
Hi. I customized the styling for the embedded chatbox, how would I apply it to my own Rocket.Chat installation?

**Comment by YuniSocial** [comment]
Hi. I customized the styling for the embedded chatbox, how would I apply it to my own Rocket.Chat installation?

**Comment by guoxiangke** [comment]
Hi. I customized the styling for the embedded chatbox, how would I apply it to my own Rocket.Chat installation?

**Comment by rahul7471** [comment]
@YuniSocial @guoxiangke How to customise live chat window to something like chat button.
Also is there any way to use this embedded live chat for android app.
Need urgent help.
Thanks in advance .

**Comment by k0nsl** [comment]
A helpful GIF to the rescue!

[![0x0f.su image hosting](https://f.0x0f.su/X6utDoMueUgx2Wo_2017-06-07_12-37-03.gif)](https://0x0f.su/)

**Comment by rahul7471** [comment]
@k0nsl thanks for quick reply.
I tried this earlier, but could not change rectangular live chat icon that appears on lower right to a button like 
![chat](https://user-images.githubusercontent.com/16912580/26875601-463b0e32-4ba0-11e7-924b-19db78b34263.jpg)

**Comment by k0nsl** [comment]
@rahul7471: You're welcome. Do you mean the `livechat-room` class? In effect, this:
[![0x0f.su image hosting](https://f.0x0f.su/8cufFqFHj6a3xaC_2017-06-07_14-34-18.png)](https://0x0f.su/)

**Comment by rahul7471** [comment]
@k0nsl Instead of this rectangular red box, i want to make it as a chat button.

**Comment by ikamran** [comment]
i tried to us live chat plugin on wordpress but it just show on windows browser in visitors from mobile devices or tables can not see live chat support on right corner of my website, what is the problem?

**Comment by vikas0121** [comment]
How can we embed livechat iframe in some mobile apps to provide a good experience?

**Comment by renatobecker** [comment]
> How can we embed livechat iframe in some mobile apps to provide a good experience?

You can do this using `WebView`.
BTW, you can use our `forum` to ask such questions.

Thanks.
