### ISSUE TITLE
Unread messages red line lingers, esc key won't clear it

### ISSUE THREAD

**Issue by ryguy222** [RocketChat/Rocket.Chat#16635]
### Description:

This is likely a duplicate of #15471 however that issue was closed with 3.0.0. However the issue partially remains with us. 

When entering a channel after receiving a new message the counter on the left goes up to indicate a new message, and once entering the message (either DM / Public / Private channel) the red "New message" line remains.  Pressing ESC key does not work. 

### Steps to reproduce:

1. Receive new message either via DM / Private / Public channel
2. User clicks into the channel or DM and see's the new message. 
3. User presses ESC key to clear unreads.  

### Expected behavior:

The horizontal red "New Message" bar should go away when entering or when pressing esc, and the counter on the left side also goes away. 

### Actual behavior:

The unread message red horizontal line remains. The left side counter clears correctly. 
![unnamed (1)](https://user-images.githubusercontent.com/2319171/74756080-44d66d80-5231-11ea-922f-9409e5afbeb9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0
- Operating System: Debian Stretch
- Deployment Method: Docker
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.14.0
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Chrome 80.0.3987.106
- Operating System: Windows 10

### Additional context

This issue was present in 2.4.x 
This issue has been noted in the latest Rocket Chat app for windows 10 
The issue has been noted in Firefox / Brave browsers. 
It may be best to re-open #15471

**Comment by ggazzo** [comment]
are you sure the room is not marked as read? the read line doesn't mean the room as not read ... check the sidebar ... we keep the red line because we cant decide if you already read the messages or not .. (in your case that you sent, when you open the room, the room is marked as read and the line will disappear, then somebody will complain that its impossible to see the read line ... thats why we wait until you make some interaction (like send a message) then we are sure we already saw the read line since you are write something

**Comment by ryguy222** [comment]
The room is being marked as read, the red line  -- unread messages is what lingers. 
Previously you could use the esc key to clear the red line (as seen in the screenshot) that does not work.

**Comment by ggazzo** [comment]
ok if you are asking to remove only if you pressed the esc, but for entering event I dont think so... what do you think?

**Comment by ryguy222** [comment]
I would just like a means of removing the "unread messages" red line that does not require responding to the message. Not all messages need to be responded to. 

In RocketChat 1.0.3 you could use ESC as a shortcut to mark messages as read. That functionality was either removed or is not working properly.

**Comment by ankar84** [comment]
> are you sure the room is not marked as read? the read line doesn't mean the room as not read ... check the sidebar ... we keep the red line because we cant decide if you already read the messages or not .. (in your case that you sent, when you open the room, the room is marked as read and the line will disappear, then somebody will complain that its impossible to see the read line ... thats why we wait until you make some interaction (like send a message) then we are sure we already saw the read line since you are write something

Totally agree with @ggazzo 
Red line it is a marker that shows user what he already saw and what he didn't.
Removing Red line by pressing ESC - no problem.
But removing Red line right after user opened a chat - not make sense. In that case Red line functionality disappear.
And I think that issue not related to #15471 any way. It was about sidebar and unread chats.
But @ryguy222 wants to broke Red line functionality. I don't agree with that.

**Comment by ryguy222** [comment]
@ankar84 I think you misunderstand me. I do not want the red line to go
away upon entering a Channel. I want it to go away when hitting escape key.
That is the functionality that is broken currently in 3.0.0

**Comment by ankar84** [comment]
> I want it to go away when hitting escape key.

Ok, as I wrote early removing Red line by hitting ESC - it is OK, no problem. It is may be useful to implement.

**Comment by HugoHeneault** [comment]
> are you sure the room is not marked as read? the read line doesn't mean the room as not read ... check the sidebar ... we keep the red line because we cant decide if you already read the messages or not .. (in your case that you sent, when you open the room, the room is marked as read and the line will disappear, then somebody will complain that its impossible to see the read line ... thats why we wait until you make some interaction (like send a message) then we are sure we already saw the read line since you are write something

This is weird as clicking/reacting to a message below the red line doesn't remove it anyway...

So if I don't reply to the message the red line will never go? 🤔
