### ISSUE TITLE
npm WARN deprecated request@2.88.2: request has been deprecated

### ISSUE THREAD

**Issue by Attack44** [RocketChat/Rocket.Chat#16632]
- Version of Rocket.Chat Server: 2.4.7
- Operating System: Debian 10
- NodeJS Version: v12.14.0
- MongoDB Version: v4.0.16

I can't update Rocket.Chat to version 3.0.0. Currently there is always an error message:
https://forums.rocket.chat/t/getting-error-when-running-a-command-cd-tmp-bundle-programs-server-npm-install/5836

**Comment by kevinprogramador** [comment]
i have the same error when I try to create a ionic project

**Comment by chienbinhso14** [comment]
I have same errror

**Comment by karthikgibbi** [comment]
same error

**Comment by xuxiang32** [comment]
same error

**Comment by worteepz** [comment]
Same error
