### ISSUE TITLE
Emoji search is inconsistent 

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat#16636]
### Description:

Searching for emojis produces inconsistent results. Should be able to discover all emojis via searching their terms within the pop-up box.

### Steps to reproduce:

1. In a new message click the emoji icon
2. Start searching for emojis with dual names (fire/flame)
3. Same emojis will not be found under additional names
4. If you start typing the name/alias of impacted emoji within the regular message box, they are found without issue

### Expected behavior:

Searching for emojis should be consistent 

### Actual behavior:

![image](https://user-images.githubusercontent.com/29238486/74765035-d5707600-5250-11ea-8b48-5632628267de.png)

![image](https://user-images.githubusercontent.com/29238486/74765066-e6b98280-5250-11ea-9c52-c5e4c4e0047f.png)

![image](https://user-images.githubusercontent.com/29238486/74765217-27b19700-5251-11ea-89d7-4d60314f3854.png)

![image](https://user-images.githubusercontent.com/29238486/74765239-3435ef80-5251-11ea-9c47-bdf1ceb1f302.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0
- Operating System: CentOS 8
- Deployment Method: Manual CentOS Install
- Number of Running Instances: 5
- DB Replicaset Oplog: 
- NodeJS Version: 12.14
- MongoDB Version: 4.0.X

### Additional context

Behavior is experienced on latest windows app and web clients

**Comment by abhiandthetruth** [comment]
working on this one :-)

**Comment by subham103** [comment]
I would like to solve this issue :smile:
