### ISSUE TITLE
Integration with Keycloak: cannot get username

### ISSUE THREAD

**Issue by shilu911** [RocketChat/Rocket.Chat#16647]
### Description:

When use Keycloak as the IDP, and set `preferred_username` as the username field, I am getting `401: Username field "preferred_username" not found in data` when call the login rest api.

### Steps to reproduce:

1. Go to the admin page, create a custom OAuth, follow the instructions of integration with Keycloak on the RC website, set `preferred_username` as username field and save.
2. Call /login with the access token from Keycloak
3. getting `401: Username field "preferred_username" not found in data`

### Expected behavior:

The login action should be successful. 

### Actual behavior:

Getting error that says preferred_username not found in data

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.14

### Relevant logs:

I20200219-08:20:31.885(0) server.js:204 API ➔ debug POST: /api/v1/login 
I20200219-08:20:31.906(0) server.js:204 CustomOAuth ➔ debug Identity response {   "sub": "b2db7e48-3866-45ba-8a9e-7983fb547916",   "email_verified": false,   "preferred_username": "john_doe777_abc.com",   "email": "john_doe777@abc.com" }

**Comment by MagnaibayarMN** [comment]
I also faced on this problem. 
so i solved by create new client scope named "**user_name**", it must points to username attribute of user. you can choose mapper type to **user property**.

then you can configure user name field to **username** property of token.

**Comment by dschmidt** [comment]
I'm not using keycloak, but kopano konnect and I had a similar (the same?) issue.

I solved it by requesting `openid profile` scope instead of only `openid`.
