### ISSUE TITLE
File Upload Drag & Drop not working

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#16657]
### Description:

Not possible to add a file via drag and drop to a channel or direct chat.

### Steps to reproduce:
Go to any channel or direct chat and drag and drop a allowed file (e.g. jpg) into the room.

### Expected behavior:

File will be uploaded into the room

### Actual behavior:

No file get uploaded. No error message shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.1
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 3 
- DB Replicaset Oplog:  Enabled
- NodeJS Version:  12.16.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App: 2.17.7
- Operating System: Fedora 31

**Comment by ggazzo** [comment]
hey @TimmiORG  could you provide more info, like a gif, please? its too weird use are used to send a lot of files every day, and we had no problems about that... thanks

**Comment by TimmiORG** [comment]
Hi @ggazzo,
I just updated to 3.0.2 and I can't reproduce the issue anymore.
So I will close the ticket.
Best regards
Timmi
