### ISSUE TITLE
Unread count for all messages - not counting when mentioning another user

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat#16658]
### Description:

When the 'Unread count" is set to "all messages", the counter is not taking into account messages which mentions another user

### Steps to reproduce:

1. Set "Unread Count" to "all messages"
2. Log on to Rocket.Chat as user A
3. In a different session, logon on to Rocket.Chat as user B
3. Go to a channel/private room and send message mentioning user C. This message won't be counted.

![unread_2](https://user-images.githubusercontent.com/11891939/74878570-58272d00-5346-11ea-9a2b-ce34e87349e0.gif)

### Expected behavior:

All messages to be count, for any mention.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop
- Operating System: All

### Client Setup Information

- Desktop App or Browser Version: All
- Operating System: All

**Comment by ashwaniYDV** [comment]
@rsjr The problem here is that if another user(USER c) is mentioned ny current users A and B then unreadCount is increased for that mentioned user only(USER C) and USER A and USER B didn't get the notification and their nuread counter is not increased.
