### ISSUE TITLE
Heroku one-click deploy fails due to image size

### ISSUE THREAD

**Issue by ryjones** [RocketChat/Rocket.Chat#16659]
### Description:

Using the one-click build button from the [here](https://github.com/RocketChat/Rocket.Chat/blame/develop/README.md#L155), the build fails as the image size is 506 megs, and Heroku only allows 500 megs.

### Steps to reproduce:

1. [go here](https://github.com/RocketChat/Rocket.Chat/blame/develop/README.md#L155)
2. click "Deploy" button
3. name app, let install proceed

### Expected behavior:

App builds and runs

### Actual behavior:

Heroku fails to build with an error that the image is too large

### Server Setup Information:

Default Heroku free setup.

**Comment by LakesideMiners** [comment]
i'm having this issue as well. exact same conditions.

**Comment by goraksha** [comment]
```
-----> Adding PATH environment
-----> Running extras
-----> Adding MONGODB_URI -> MONGO_URL env
-----> Adding profile script to resolve MONGO_URL from mongolab addon
-----> Adding profile script to resolve ROOT_URL from heroku app name
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
 !     Compiled slug size: 504.3M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed
```
Logs be precise.
Built with 1-click option today.

Following _Customized command line for developers_ from the docs, it's the same, but `509.1M is too large (max is 500M).`

**Comment by vishnumg** [comment]
Same issue here

**Comment by bersimao** [comment]
Here too.

I tried ir from the one click to deploy button and the CLI, both with the same error.

**Comment by AndreiJirohHaliliDev2006** [comment]
Same issue here.

I tried it, but it still failed due to the same issue.

**Comment by skermiebroTech** [comment]
I have this problem too

**Comment by thiagovilla** [comment]
Me too. Any way to make it leaner?
