### ISSUE TITLE
change status Length size make more than 200 character. I have not able to write 142 character in status.

### ISSUE THREAD

**Issue by ansalok** [RocketChat/Rocket.Chat#16660]
## My Setup

- Operating System:
- App Version:
- Installation type: 

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

**Comment by gabriellsh** [comment]
I think this is the intended behaviour. I tested and could add only 120 chars at one time. Even being limited, having this much characters in the status makes the UI buggy in some parts. This means that either we need some UI/UX design change so we can fit more in the status or it'll stay like that.
