### ISSUE TITLE
[BUG] Auto logout frequently on web, app desktop and app android - ios (react)

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#16666]
### Description:

Rocket.Chat auto logout on web, app desktop and app android - ios (react)

### Steps to reproduce:

1. Login;

Please watch the video:
https://drive.google.com/file/d/1xbQ9ZAi6hE8kccRJCXnV9nOUE9kb1VXE/view?usp=sharing

- go to minute 1'40

### Expected behavior:

Stay connected

### Actual behavior:

Auto logout frequently

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Ubuntu (Linux x64) 4.4.0-1101-aws
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows, linux(ubuntu) and android

### Relevant logs:

https://drive.google.com/file/d/1Rcz_x4TVw0-kSNCQPqx8f_b0MeCSgWl9/view?usp=sharing

**Comment by guilhermecfviana** [comment]
I found out the reason. My user was being used to authenticate with the rest API.

**Comment by gabriellsh** [comment]
So is it really a bug? Do you have any additional info so we can reproduce it?

**Comment by guilhermecfviana** [comment]
To solve the problem here I created another user with administrator permission and use it to authenticate the REST API
