### ISSUE TITLE
RestAPI MessageHistory TS QueryParams is not honnered

### ISSUE THREAD

**Issue by alexmontoanelli** [RocketChat/Rocket.Chat#16664]
### Description:

The REST-API of LiveChat, has method to load the history messages for a room [1].

There is a params called TS (in the docs),  that allow us to load only messages from this TimeStamp to now..

But this is not honored.

After digging a little, i can't see the param TS begin used , just the undocumented 'ls'. [2] 

### Steps to reproduce:

1 - Call Rest API Method to load message history for a room, with ts params:
/api/v1/livechat/messages.history/GLPpYcJeSRxhsgWxM?token=31029add2feba58af429603ad8503515&ts=2021-02-02

2 - Get the response

### Expected behavior:

Whith the ts as 2021-02-02 a future date, I expected no messages in reply request.

### Actual behavior:

All the messages in that room are sent in reply.

### Server Setup Information:

- Version of Rocket.Chat Server:  2.2.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 1
- NodeJS Version: 
- MongoDB Version:

[1] - https://rocket.chat/docs/developer-guides/rest-api/livechat/message/index.html#load-livechat-messages-history

[2] - https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/api/v1/message.js#L200

**Comment by Syn3rman** [comment]
Hey @alexmontoanelli,
I'm running into the same issue, were you able to figure out how to get it to work?
