### ISSUE TITLE
My Rocket.chat setup is not working on ubuntu server

### ISSUE THREAD

**Issue by ashishchauhan1** [RocketChat/Rocket.Chat#16676]
My Rocket.chat setup is not working on ubuntu server as rocket.chat has already mentioned in their  docs
documentation that the minimum requirement (https://rocket.chat/docs/installation/minimum-requirements/) is 
    Single core (2 GHz)
    1 GB RAM
    30 GB of SSD

my server specification is

    Node 12.14.0
    Meteor 1.9.2
    Rocket chat 2.4.2
    Platform: linux
    MongoDB v4.0.16
    1 GB RAM and 1 CPU 

i don't know what is happening , is it the mongodb who is utilising the server memory? 
can anyone help me out for this

thanks

**Comment by lisa761** [comment]
Rocket.Chat requires a lot of RAM while building. Are you running this on a Virtual Machine? If yes then try to increase the allotted RAM, then add some extra space for swap file.
