### ISSUE TITLE
Notifications don't work on Firefox

### ISSUE THREAD

**Issue by andreabolognani** [RocketChat/Rocket.Chat#1667]
Fedora 23, standard installation.

Notifications work on Chrome but not on Firefox. I tested

  https://developer.mozilla.org/en-US/demos/detail/html5-notifications

on both browsers to make sure notifications were not broken on Firefox altogether, but the demo works consistently on both. I have also made sure that notifications are allowed, and restarted Firefox a couple of times for good measure.
##

**Comment by geekgonecrazy** [comment]
What version of Firefox?

**Comment by Sing-Li** [comment]
@andreabolognani   Please re-open if you still have problem --- and PLEASE specify the version of Firefox , the OS that it is running on, and the hardware configuration.   Thanks.

**Comment by andreabolognani** [comment]
Sorry, didn't check my GitHub account for a while :)

I just tried again and the problem is still there: desktop notifications
don't work in Firefox but work just fine in Chrome.

The OS is Fedora 23 x86_64, and the system is up-to-date as of this
morning. I'm using the default desktop environment, GNOME 3.18.

The Firefox version is 43.0.3, more specifically:

    firefox-43.0.3-1.fc23.x86_64

The machine itself is a ThinkPad T440s.

If you need more information, just let me know.

**Comment by andreabolognani** [comment]
Apparently commenting to the issue doesn't automatically reopen it,
and I'm not allowed to reopen it explicitly because I didn't close
it myself. So, please reopen it :)

**Comment by marceloschmidt** [comment]
Apparently notifications aren't working on Firefox 42.0 on Mac OSX 10.11 (El Capitan) either.

**Comment by marceloschmidt** [comment]
Updated to 43.0.4 and it still doesn't work.

**Comment by ltoscano-rh** [comment]
The situation improved, but not completely. Some of the notifications are simply lost, with not clear pattern if it is only the first one missed in a sequence, or if the foreground/background status is enabled. Up-to-date Fedora 24, firefox-48.0-5.fc24.x86_64, running under Plasma 5.7.3.

**Comment by mmizera** [comment]
Hi, problem still persist, I have Win10 & FF 56.0.1 (64-bit), notifications are allowed for rocket chat (both FF and in account settings), no notification is displayed, not even via "Test desktop notification" button.

In chrome everything works fine.

**Comment by sampaiodiego** [comment]
notifications are working for me (Ubuntu 17.04 + Firefox 56.0).

you guys should make sure your status is not set to **busy**, otherwise you'll not receive any desktop notification (this is a designed behavior)

**Comment by maxsdw** [comment]
I tested with my status sen to Online, and it still not working (macOS High Sierra + FireFox 57.0.4 )

**Comment by SeanPackham** [comment]
I tested this bug on open.rocket.chat and Rocket.Chat Cloud on OSX 10.13.3, Firefox 58.0.2 (64-bit), Chrome 64.0.3282.186 (Official Build) (64-bit) desktop notifications were enabled for both browsers.

Audio notifications work and the tab unread message icon is updated but no desktop notifications are show.

**Comment by heltonritter** [comment]
For me still does not work in firefox 67.04 in Linux Mint
if I open f12 from browser no javascript error is happening.

**Comment by gabriellsh** [comment]
Just tested on firefox 64.0 and 72.0, macOS Version 10.15.2, RC Version: 2.5.0-develop, notifications work fine.

Make sure that notifications are enabled both on the browser and on the OS.

If possible, test this again and report if it works.

**Comment by gabriellsh** [comment]
Tested again on Firefox 72.0.2, is working fine. I'm closing this. If there is need please reopen.
