### ISSUE TITLE
3.0.1 not working with internet explorer.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#16677]
### Description:

When loading rocket chat in IE 11, it gets stuck at the 3 dots and never fully loads. I believe this is important because there are some older computers that still use IE 11 as it's default browser.

### Expected behavior:

Rocket Chat to load on IE 11.

### Actual behavior:

Hangs at the 3 dots loading screen.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.1
- Operating System: Centos
- Deployment Method: Tar
- Number of Running Instances: 6
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Yambr** [comment]
https://github.com/RocketChat/Rocket.Chat/releases/tag/3.3.0-rc.3
- this version work for me 

but 3.2.2 - not working now
