### ISSUE TITLE
Dropdown not properly opening in wizard setup page

### ISSUE THREAD

**Issue by Subhang23** [RocketChat/Rocket.Chat#16687]
### Steps to reproduce:

1. Enter ```meteor reset``` in the terminal and go to the wizard setup.
2. Press on the downward arrow

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 18.04
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.6.1
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Ubuntu 18.04

**Comment by ashwaniYDV** [comment]
@Subhang23 You don't have to clone the repo again and again if you are reproducing this error(if it is there). You can simply run command `meteor reset`. It cleans the database and creates a fresh instance. So this way it will be easy for you to solve this issue. :)

**Comment by Subhang23** [comment]
Thanks a lot for that @ashwaniYDV . Will edit it.
