### ISSUE TITLE
Script block is empty in "Integrations / Incoming Webhooks"

### ISSUE THREAD

**Issue by galenski** [RocketChat/Rocket.Chat#16692]
The "Script" block is empty in "Integrations / Incoming webhooks". If i edit a incoming webhook the script block is empty. But if i save my changes to other fields it already works! (Version 3.0.1)

**Comment by melikesofta** [comment]
I have the same issue. My existing incoming hook stopped working after I upgraded to 3.0.3 today and I cannot fill in the 'script' field, says it successfully saved but it's empty when I refresh or close and open the integration details.

**Comment by avionbg** [comment]
Same here ...

**Comment by jheiselman** [comment]
Same issue continues with 3.0.7
