### ISSUE TITLE
Custom OAuth issue since upgrading to 3.0.0

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat#16694]
### Description:

Since the Update to 3.0.0 we have issues logging into our Server.
We use Keycloak for OAuth and when the redirect to keycloak happens it should use HTTPS. If that is enabled it throws errors because the TLS handshake fails and no user can login anymore. The Clients simply show an internal server error.

If we set HTTP, the logins are successful (nginx has an internal redirect to 443). BUT some clients show weird behaviour (see: [RC Electron #1531](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1531). ~~The IOs app refuses to connect at all.~~ One IOs Client does not connect showing an error "1022", which apparently happens because "the app transport security policy requires the use of a secure connection". Others could not confirm this problem.

Anyone else experiencing this?

### Steps to reproduce:

1. Setup RC to use Keycloak
2. Set the login URL to https
3. try to log in with a standard user via Keycloak
4. see it fail

### Expected behavior:

Login sucessfully, as in pre-3.0.0

### Actual behavior:

Login fails; see the logs

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.1
- Operating System: CentOS 7
- Deployment Method: tar / normal install
- Number of Running Instances:  1
- DB Replicaset Oplog: on, but not used
- NodeJS Version: 12.16.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Windows Client 2.17.2 - 2.17.7, most recent Firefox and Chrome
- Operating System: Win10, MacOS

### Additional context

In the Logs multiple error types are generated. TLS handshake errors for failed logins, push gateway errors over and over again, and webhook integrations fail (Giphy, see: [#16649](https://github.com/RocketChat/Rocket.Chat/issues/16649) ).

### Relevant logs:

Handshake error:
` W20200224-09:25:40.105(1) (oauth_server.js:392) Error in OAuth Server: Failed to complete OAuth handshake with keycloak at https://my-server/auth/realms/blah/protocol/openid-connect/token. error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command
I20200224-09:25:40.292(1) Exception while invoking method 'login' Error: Failed to complete OAuth handshake with keycloak at https://my-keycloak/auth/realms/blah/protocol/openid-connect/token. error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command     at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:233:18)     at Object.handleOauthRequest (app/custom-oauth/server/custom_oauth_server.js:290:26)     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)     at middleware (packages/oauth/oauth_server.js:161:5)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   message: 'Failed to complete OAuth handshake with keycloak at https://my-keycloak/auth/realms/blah/protocol/openid-connect/token. error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command' }  `

Push gateway error:
`
I20200224-09:36:14.176(1) server.js:204 System ➔ error Error sending push to gateway (5 try) -> Error: error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command     at Object.createSecureContext (_tls_common.js:217:13)     at Object.connect (_tls_wrap.js:1559:48)     at Agent.createConnection (https.js:130:22)     at Agent.createSocket (_http_agent.js:265:26)     at Agent.addRequest (_http_agent.js:224:10)     at new ClientRequest (_http_client.js:296:16)     at Object.request (https.js:314:10)     at Object.request (/opt/Rocket.Chat/programs/server/npm/node_modules/agent-base/patch-core.js:23:20)     at Request.start (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:751:32)     at Request.write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1497:10)     at end (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:549:18)     at Immediate._onImmediate (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:578:7)     at processImmediate (internal/timers.js:456:21)     at process.topLevelDomainCallback (domain.js:137:15) {   opensslErrorStack: [     'error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command'   ],   library: 'SSL routines',   function: 'ssl_cipher_process_rulestr',   reason: 'invalid command',   code: 'ERR_SSL_INVALID_COMMAND' } `

**Comment by ankar84** [comment]
> The IOs app refuses to connect at all.

Just now I tested login process using **KeyCloak** in **Rocket.Chat.ReactNative** application version **4.4.0.282** with **RC server version 3.0.1** at **iPhone 8 on iOS 13.3.1** without any problems

**Comment by aimador** [comment]
Thx for the info. I had other IOs users double check on that. Turns out it's one specific user with that problem. Can't say which IOs version it is, since the user did not report back yet.

**Comment by aimador** [comment]
Problem solved. Turns out it was an old entry in the systemd service file. Don't use "--tls-cipher-list"... 🙄
