### ISSUE TITLE
Ability to select specific messages to reply to

### ISSUE THREAD

**Issue by rkb81** [RocketChat/Rocket.Chat#167]
Will be nice if we can reply a single message or group messages, share this message or group, comment message or group, in group case just shift-cick to select multiple messages.

Using icons or just text to Reply, Share, Comment, Private contact.
##

**Comment by rickbenetti** [comment]
This it's an example of my idea with Grouped to comment and links to Replay and Share.
![rocket_chat_group](https://cloud.githubusercontent.com/assets/1049908/8025932/81298248-0d3c-11e5-8d0a-87927ef6ef5d.png)

**Comment by geekgonecrazy** [comment]
Is this essentially threads? #1112

**Comment by engelgabriel** [comment]
MOst of the features have been done, the missing part is indeed #1112
