### ISSUE TITLE
3.0.2 not loading in older versions of safari/ipad

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#16702]
### Description:

I am getting reports that the chat is not loading in older versions of safari on ipad. This is the ipad specs I received from the end user. Please keep in mind that these ipads are on a few years old and there are a lot of them still in use. Report is that it hangs at the 3 loading dots.

Ipad info: Version 9.3.5(13G36) , model MD531LL/A

### Steps to reproduce:

1. Attempt to load chat on Ipad.
2. Hangs at 3 loading dots.

### Expected behavior:

For rocket chat to load.

### Actual behavior:

rocket chat  hangs at 3 loading dots.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: Centos
- Deployment Method: Tar
- Number of Running Instances: 6
- DB Replicaset Oplog: yes
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Ipad

**Comment by ggazzo** [comment]
hey @serviceman, do you know the safari version they are using? please check again if you are not running 3.0.1, because we released a fix for old browsers in 3.0.2

**Comment by serviceman** [comment]
I have confirmed that I am running version 3.0.2. I do not know the exact version of safari. I am assuming it is whatever version of safari that is supported by the ipad mentioned above. I am however getting this error in chrome and sometimes the fails to load as a result. I wonder if it is related.

TypeError: Cannot read property 'uid' of undefined
    at cb1059d25c0cbf8d4a9df85876ce23b4452bce92.js?meteor_js_resource=true:971
    at t._compute (cb1059d25c0cbf8d4a9df85876ce23b4452bce92.js?meteor_js_resource=true:679)
    at t._recompute (cb1059d25c0cbf8d4a9df85876ce23b4452bce92.js?meteor_js_resource=true:679)
    at Object.o._runFlush (cb1059d25c0cbf8d4a9df85876ce23b4452bce92.js?meteor_js_resource=true:679)
    at a (cb1059d25c0cbf8d4a9df85876ce23b4452bce92.js?meteor_js_resource=true:1)

This error also appears on open.rocket.chat

**Comment by gabriellsh** [comment]
I think that log was fixed by #16704 and is probably not related.

We still need the browser versions so we can reproduce this. Could you arrange that? thanks!

**Comment by serviceman** [comment]
My instance of rocket  chat is used by the general public, so this is not easy information to get from these users, most are non techie people. I did manage to get two users to report and both stated they used Safari OS 9.3.5

**Comment by serviceman** [comment]
> I think that log was fixed by #16704 and is probably not related.
> 
> We still need the browser versions so we can reproduce this. Could you arrange that? thanks!

When will that be included in a release so I can test it?
