### ISSUE TITLE
Layout color changes are not applied on cloud instances. 

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat#16701]
### Description:

Changing primary color (or other colors) under Admin -> Layout -> Colors makes no difference to the interface. Selecting Color (instead of Epression) does not work eaither as once you click on a color palette, the field value is rolled back to Expression. 

### Steps to reproduce:

1. Admin -> Layout -> Colors.
2. Click on Primary color -> Color
3. Choose any colot on the palette, see the selection changing back to expression.
4. Save changes (you will have to close the palette dialog window, as it stays when you close the Colors section).
5. Refresh the page, no visible changes done.

### Expected behavior:

The background color shold change accordingly. Same with button colors. 

### Actual behavior:

![Layout_colors](https://user-images.githubusercontent.com/47217833/75169858-eaa64280-5731-11ea-873c-7659c80a5d61.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 
The issue is confirmed on Cloud instances of 3.1.0, 2.4.9, 2.4.7 versions;
self-hosted instance of 2.4.6 version.
- Operating System: Linux
- Deployment Method: Cloud and manual instal on Ubuntu 
- Number of Running Instances: 1 per each server
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4, 8.17.0, 12.14.0
- MongoDB Version: 4.0.10, 4.0.4, 4.0.16

### Client Setup Information

- Desktop App or Browser Version: browsers (GH, Brave) and desktop 2.17.7 
- Operating System: MacOS

### Additional context

A cloud instance on 3.0.0 does not have this bug.

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/16706
