### ISSUE TITLE
Azure AD SAML auth context mismatch

### ISSUE THREAD

**Issue by therealhanlin** [RocketChat/Rocket.Chat#16713]
This issue presented here is the RocketChat server is unable to carry different SAML auth contexts to Azure AD for authentication. 

By default, the SAML auth context is set to urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport, which is working fine by itself if it's a new login. Although we do observe issues when the auth context is different like Windows integrated authentication. 

Error message: AADSTS75011: Authentication method 'WindowsIntegrated' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'.

I'm wondering if there is a way to specify multiple auth contexts on RocketChat for SAML or just simply disabling specifying auth context. 

Thanks in advance!

**Comment by pierre-lehnen-rc** [comment]
You can change the auth context in the `Custom Authn Context` setting, under SAML.
