### ISSUE TITLE
[FEATURE] Granular pruning permissions

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat#16727]
Allow the separation of pruning/cleaning permissions

**Comment by gabriellsh** [comment]
Although we can have an idea about what you're talking, there's too little information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information next time. Thanks!

**Comment by TheGr8Wonder** [comment]
I apologize! I'll do it better next time. However in this case for those that are reading...

This feature is to introduce the breaking out of pruning permissions from a single permission option that includes all 3 -  channels, groups, direct, into 3 separate ones that may be applied at different role levels. 

This would partially allow for closing of #14986, by putting the groundwork in place for future development.
