### ISSUE TITLE
Changing Working days or Working hours fails when made in the same day. 

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat#16722]
Steps to reproduce:

1. It's Monday. Livechat -> Working hours -> Set Tuesday as a non-working day.
2. Try to visit the widget on Tuesday. It shows the offline form. 
3. Change your mind, set Tuesday as a working day.
4. The livechat will still be off (offline form).
5. Same with working hours - if the working hours are set to, say, 10-16 today, but you want to change it to 10-20, you change - and the widget will still show the offline form, unless you allow to show online agents outside working hours and enable the livechat (the green toggle). 

<img width="1127" alt="Screenshot 2020-02-18 at 22 28 07" src="https://user-images.githubusercontent.com/47217833/74775492-82bdab00-529e-11ea-9071-7d28ad22ed8e.png">
<img width="1150" alt="Screenshot 2020-02-18 at 22 40 43" src="https://user-images.githubusercontent.com/47217833/74776149-bb11b900-529f-11ea-947a-50dde44a8c02.png">
<img width="1438" alt="Screenshot 2020-02-18 at 22 36 35" src="https://user-images.githubusercontent.com/47217833/74775958-5f473000-529f-11ea-840a-848981abfc71.png">

Environment details:
RC version: 2.4.9
Client: web and desktop on MacOS.
Deployment: Rocket.Chat Cloud instance.

**Comment by renatobecker** [comment]
Hi @mar-v, after releasing the `3.4` version, this issue is supposed to be fixed.
