### ISSUE TITLE
Mongo seg fault generating statistics

### ISSUE THREAD

**Issue by jeansnkicks** [RocketChat/Rocket.Chat#1673]
So I will say that I am not sure if this is a mongo or Rocket.chat issue. On a clean install (using the Ansible role for CentOS 7 https://github.com/RocketChat/Rocket.Chat.Ansible), you can:

1) register an account, login
2) click administration, click statistics, and crash mongo.

Once crashed in this manner, I am unable to get Rocket.chat to start again.

Let me know what additional details would help in troubleshooting this issue. Truncated log details below.

[err-0.txt](https://github.com/RocketChat/Rocket.Chat/files/63292/err-0.txt)
[mongod.txt](https://github.com/RocketChat/Rocket.Chat/files/63293/mongod.txt)

**Comment by rodrigok** [comment]
@jeansnkicks which version of MongoDB and NodeJS are you using?

**Comment by jeansnkicks** [comment]
$ node --version
v0.10.40

$ mongo --version
MongoDB shell version: 2.6.11

**Comment by jeansnkicks** [comment]
Good news all, I've confirmed this is an issue with Mongo and SE Linux in CentOS 7. It would appear CentOS 7 now defaults (this is 7.2.1511) to "Enforcing" by default, which, without tweaks to the profile for mongo will crash mongo. Setting SE Linux to "Permissive" resolves the issue. Still a bad issue, but not a Rocket.Chat issue, rather a CentOS/Mongo issue.
