### ISSUE TITLE
rocket.chat does not start on ubuntu

### ISSUE THREAD

**Issue by vidyabuddhiraju** [RocketChat/Rocket.Chat#16734]
I just installed rocket chat with the instructions here.

https://rocket.chat/docs/installation/manual-installation/ubuntu/

I typed in every one of the commands exactly in the order mentioned.

Here is my linux version output of uname -a

Linux mediamachine 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lubuntu 18.04 is my version running in headless mode.

mongodb 
db version v4.0.16
git version: 2a5433168a53044cb6b4fa8083e4cfd7ba142221
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

node --version
v12.14.0

I try to start the rocketchat server with 

sudo systemctl start rocketchat

this is what it produces in syslog.

Feb 27 20:50:41 mediamachine systemd[1]: Started The Rocket.Chat server.
Feb 27 20:50:41 mediamachine rocketchat[951]: internal/modules/cjs/loader.js:800
Feb 27 20:50:41 mediamachine rocketchat[951]:     throw err;
Feb 27 20:50:41 mediamachine rocketchat[951]:     ^
Feb 27 20:50:41 mediamachine rocketchat[951]: Error: Cannot find module '/opt/Rocket.Chat/main.js'
Feb 27 20:50:41 mediamachine rocketchat[951]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
Feb 27 20:50:41 mediamachine rocketchat[951]:     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
Feb 27 20:50:41 mediamachine rocketchat[951]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
Feb 27 20:50:41 mediamachine rocketchat[951]:     at internal/main/run_main_module.js:17:11 {
Feb 27 20:50:41 mediamachine rocketchat[951]:   code: 'MODULE_NOT_FOUND',
Feb 27 20:50:41 mediamachine rocketchat[951]:   requireStack: []
Feb 27 20:50:41 mediamachine rocketchat[951]: }
Feb 27 20:50:41 mediamachine systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 20:50:41 mediamachine systemd[1]: rocketchat.service: Failed with result 'exit-code'.

What can I do to get the thing going?

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by lisa761** [comment]
Why don't you try this https://rocket.chat/docs/developer-guides/quick-start/ and see if it helps?

**Comment by talheim-it** [comment]
@vidyabuddhiraju well the issue is clear:
Feb 27 20:50:41 mediamachine rocketchat[951]: Error: Cannot find module '/opt/Rocket.Chat/main.js'

Please check all, maybe one step didn't pass correctly or is missed.

Yours,
Mathias

**Comment by ebaioni** [comment]
hitting the same problem

**Comment by paul-dest** [comment]
The same problem after having installed RocketChat according to https://docs.rocket.chat/installation/manual-installation/centos/

**Comment by paul-dest** [comment]
The cause of the problem is the wrong/changed path of the `main.js`: it's not `/opt/Rocket.Chat/main.js`, but `/opt/Rocket.Chat/bundle/main.js`. After changing the corresponding line in `/lib/systemd/system/rocketchat.service` and repeating of starting steps, everything runs fine.
