### ISSUE TITLE
submitted PR without attention for four months

### ISSUE THREAD

**Issue by benkroeger** [RocketChat/Rocket.Chat#16731]
Dear Maintainers,
I submitted  PR #15690 end of october 2019 and am since waiting to get any sort of feedback.
It was supposed to help my company evaluate Rocket.Chat as their new messaging tool - in combination with login from Azure AD and picking custom user names.
It also helps closing several other issues (listed in PR description).

Can anyone please tell me what is missing to get this thing processed (even a rejection would be a valid response).

Thanks in advance!

**Comment by gabriellsh** [comment]
We're sorry for the delay, we acknowledge that this is not supposed to happen and constantly try to improve on our community interaction. Unfortunately sometimes things get kind of buried.

Once again, as said in #15690, thank you very much for your effort, your review is on the way.
