### ISSUE TITLE
Error message in name input when no name provided.

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16747]
### Description:
When in the require name for signup is disabled the name input is always in error state

### Steps to reproduce:

1. Go to settings in account and then in registration
2. Disable require name for signup
3. Create a new user and dont give a username

### Expected behavior:

The name input should not be in error state

### Actual behavior:
![image](https://user-images.githubusercontent.com/43509699/75553549-9fa46c00-5a5e-11ea-81e7-787d96d777a3.png)

I20200228-18:49:20.313(5.5)? ➔ +----------------------------------------------+
I20200228-18:49:20.313(5.5)? ➔ |                SERVER RUNNING                    |
I20200228-18:49:20.313(5.5)? ➔ +----------------------------------------------+
I20200228-18:49:20.314(5.5)? ➔ |                                                                     |
I20200228-18:49:20.314(5.5)? ➔ |  Rocket.Chat Version: 3.0.0-develop          |
I20200228-18:49:20.314(5.5)? ➔ |       NodeJS Version: 12.14.0 - x64             |
I20200228-18:49:20.314(5.5)? ➔ |      MongoDB Version: 4.0.6                        |
I20200228-18:49:20.314(5.5)? ➔ |       MongoDB Engine: wiredTiger               |
I20200228-18:49:20.315(5.5)? ➔ |             Platform: linux                                 |
I20200228-18:49:20.315(5.5)? ➔ |         Process Port: 29533                           |
I20200228-18:49:20.315(5.5)? ➔ |             Site URL: http://localhost:3000       |
I20200228-18:49:20.315(5.5)? ➔ |     ReplicaSet OpLog: Enabled                   |
I20200228-18:49:20.315(5.5)? ➔ |          Commit Hash: a056afb191                |
I20200228-18:49:20.315(5.5)? ➔ |        Commit Branch: Issue#16428

**Comment by gabriellsh** [comment]
Related to #16740. Actually, thats the same issue, and slightly different consequences. Please don't forget to search for issues before opening them. Thanks! :)
