### ISSUE TITLE
Blank page in several options when setting up LDAP

### ISSUE THREAD

**Issue by vyngur** [RocketChat/Rocket.Chat#16743]
**Description:**
Selecting Sync User Data from the LDAP (Sync/Import) configuration page returns a black page with no error (also checked browser console).
The same behavior was observed with the Background Sync button.
Pushing back in the browser and forward reveals the button with the expected state.

**Steps to reproduce:**
See attached gif

**Expected behavior:**
Button goes to enable and generates the sync request to the server

**Actual behavior:**
See attached gif

**Server Setup Information:**
Version of Rocket.Chat Server: 2.4.1
Operating System: Ubuntu 18.04.4
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 8.15.1 - x64                  | 
MongoDB Version: 4.0.14
Client Setup Information

**Client Setup Information:**
Desktop App or Browser Version: Chrome/Firefox
Operating System: Windows 10

**Relevant logs:**
Not applicable.

![BESjBbVLAG](https://user-images.githubusercontent.com/34929790/75543597-19fecd00-5a1a-11ea-8a52-198059f59df8.gif)

**Comment by ankar84** [comment]
It is fixed in newer versions of RC, in 2.4.3 for example.
You need to update.

**Comment by vyngur** [comment]
Thanks! Will check the new version
PS Dislexia :)
