### ISSUE TITLE
integrate STRIPE payments 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1674]
add stripe payment, if ADMIN want to make some private rooms paid version..

https://github.com/stripe/stripe-node

https://stripe.com/ca/features

**Comment by Joshua-Anderson** [comment]
Would it be cleaner instead to have a payment form on your website? You could then use the api to invite and kick users from the channel when they pay.

There are so many different ways for payments to be implemented (one time fee, recurring fee, charge by minute). It would be hard for rocket.chat to build a one size fits all solution. In addition, it puts rocket.chat on the hook for making sure their payment system is secure, requiring the overhead to audit the code and make certain there aren't any vulnerabilities, raising the stakes from worst case scenario passwords are leaked to somebody stealing thousands of dollars.

I'm also confused about why somebody would pay to join a room. After all, if you have open registration on your chat server people could still DM you or talk to you in another channel you are in. What is the use case for paid rooms?

**Comment by Joshua-Anderson** [comment]
This is also an duplicate of #900

**Comment by rodrigok** [comment]
Closing in favor of #900
