### ISSUE TITLE
V3.0.2: Direct Messages - No pinning option

### ISSUE THREAD

**Issue by talheim-it** [RocketChat/Rocket.Chat#16758]
### Description:

Options to pin messages in direct messages is not available.

### Steps to reproduce:

Mark any message, click on options and look for "pin".

### Expected behavior:

To pin messages in direct conversations.

### Server Setup Information:
Rocket.Chat: v3.0.2
MongoDB: 
Nodejs: v12.14.0

### Client Setup Information

- Desktop App or Browser Version: 2.17.7 / Brave Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
- Operating System: Fedora31 Workstation

### Additional context
--
### Relevant logs:
--

**Comment by ritwizsinha** [comment]
@gabriellsh please review
