### ISSUE TITLE
Accepted file upload. Can not send .xlsx

### ISSUE THREAD

**Issue by felixwidjaja** [RocketChat/Rocket.Chat#1675]
Accepted file: image/*,audio/*,application/*,text/*
But we can't send .xlsx
Please help.
Thanks in advance!

**Comment by felixwidjaja** [comment]
Nevermind. Had to restart rocket.chat process and problem is gone.

**Comment by ravimallya** [comment]
You can use the following mime type to upload:

`application/msword` **- for .doc**
`application/vnd.openxmlformats-officedocument.wordprocessingml.document` **- for .docx**
`application/vnd.ms-excel` **- for xls**
`application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` **- for .xlsx**
`application/vnd.ms-powerpoint` **- for .ppt**
`application/vnd.openxmlformats-officedocument.presentationml.presentation` **- for .pptx**

**Comment by javaning** [comment]
As @rafaelks said, it works, thanks.

**Comment by aaronhagopian** [comment]
I'm actually having this issue as well, not restart combo fixes.  Cannot upload XLSX or even CSV?  Why limit by mime-type in the first place?

**Comment by felixwidjaja** [comment]
@aaronhagopian try this: `image/*,audio/*,application/*,text/*`
And don't forget to restart rocket server to apply changes.

**Comment by aaronhagopian** [comment]
Thanks, new to rocketchat, didn't realize the settings were so restrictive to start.  Working now.

**Comment by linuxmangr** [comment]
Hello,
I have the same Problem and I try to set 
`image/*,audio/*,video/*,application/zip,application/pdf,text/plain, text/csv,application/ms-powerpoint,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/vnd.oasis.opendocument.spreadsheet,application/vnd.ms-excel`
And now I can upload .xlsx , xls, .ods 
If you need some other format set it to end of line.
