### ISSUE TITLE
[BUG] Message read status in active chat

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16765]
### Description:

Now we are using in test mode option Admin -> General -> Notifications -> **Always notify mobile** and I see some not comfortable behavior of that function in active chats.
I get mobile notification even for active chats where I'm actively writing messages

### Steps to reproduce:

1. Enable **Always notify mobile** in Admin -> General -> Notifications
2. Go to any chat to talk with someone
3. Chat window is active, cursor in message area, I'm looking on the screen and reading everything
4. You get new message in active chat with red line (unread messages) and immediately you get push notification on mobile client 

### Expected behavior:

Mobile notification should send only for totally unread messages.
Messages in active chat (RC.Electron or Browser on focus, on top, chat is opened) shouldn't be mark as unread.

### Actual behavior:
In screenshot you can see cursor in message area and RC.Electron 2.17.7 is on top, is on focus, chat is open, I intently looking at chat and reading all new messages immediately.
![image](https://user-images.githubusercontent.com/4023037/75644616-eb6c3680-5c53-11ea-98d8-e29f3923d315.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: 2.17.7 and Chrome 80.0.3987.122
- Operating System: Windows 10 1809

### Additional context

I understand, that if user walked away from his computer, locked his session with open active chat and then came back, it is conveniently to see all unread messages. But you can add a condition if user status was changed - chat not active anymore and unread messages may appear on all new messages.

**Comment by aleadco** [comment]
This error was also reported in https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1794

**Comment by ankar84** [comment]
Closed with https://github.com/RocketChat/Rocket.Chat/pull/17357
