### ISSUE TITLE
Improve new user experience

### ISSUE THREAD

**Issue by Somtozech** [RocketChat/Rocket.Chat#16760]
This was my first time using Rocket Chat and I found it difficult for a moment navigating around. Am suggesting a guide that shows new users what to do (like a guided tour or something similar)

**Comment by talheim-it** [comment]
@Somtozech can you describe it a bit?

Do you mean just "User" or do you mean "Admin"?

**Comment by Somtozech** [comment]
Ok. I meant for the user. I just created an account with Rocket.chat and I was kind of confused about what to do. For example, I was looking for the pinned messages that took me a while but I finally found it after clicking on almost all the buttons on the navigation. I suggest a guided tour be added for first-time users (to show how the most important things are done).

**Comment by GoetheG** [comment]
Great idea. I second it!
