### ISSUE TITLE
External mongodb instance

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#1676]
Hello. How can I configure RocketChat to use the external instance of MongoDB instead of minimongo.js? I have tried to correct parameter:

MONGO_URL=mongodb://localhost:3001

in /Rocket.Chat/packages/rocketchat-livechat/app/run.sh, but this does not help...

**Comment by sampaiodiego** [comment]
hey @zxweed =)

you don't have to touch that file, it's only for developing purpose and related only to livechat features.

if what you want is to run rocket.chat using an external mongodb, you can follow any of these docs:

* https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker
* https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker
