### ISSUE TITLE
messages window does not scroll to bottom after adding emoji

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#16774]
Hello Devs.

With 3.0.x releases adding emojis to messages seems to be a bit buggy. A new message appears completely but an emoji is only partly shown. Please see the gif. It explains the issue best.

![scroll](https://user-images.githubusercontent.com/40269193/75769091-d40d7600-5d45-11ea-8eb8-9bb35c43e975.gif)

thanks and cheers, t.

**Comment by ankar84** [comment]
Same with messages with link preview
![link](https://user-images.githubusercontent.com/4023037/75845637-c827bf80-5dea-11ea-9ba6-f14ed134e642.gif)

**Comment by ankar84** [comment]
I think it's related to #16071

**Comment by himpierre** [comment]
Quoted messages are affected by this bug too.

**Comment by foss-** [comment]
This is no longer happening here with 3.4.1 and 2.17.9.

**Comment by foss-** [comment]
As mentioned this no longer seems to be a problem. Can you test and confirm @himpierre ?

**Comment by himpierre** [comment]
No, it's all good. Thanks.
