### ISSUE TITLE
Manual app install issue

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat#16778]
### Description:

After enabling dev mode access for app installs, after selecting the ZIP and clicking install, the button does not do anything. No errors are displayed on the page and no refresh occurs. 

### Steps to reproduce:

1. Enable Dev mode for local app install
2. Admin -> Apps -> Upload App
3. Install from file -> Browse/select
4. Click Install

### Expected behavior:

Some sort of progress/page action upon clicking 

### Actual behavior:

Nothing

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox
- Operating System: Win10

**Comment by d-gubert** [comment]
This behavior had been seen before, I honestly thought it had been fixed 🤔 

There are 2 workarounds you can try while this is not properly fixed:
1 - Try to do the same in a non-windows machine
2 - Use `curl` (or even Postman) to upload the file to the server, e.g.:
`$ curl '{YOUR_SERVER_URL}/api/apps' -H 'X-Auth-Token: {TOKEN}' -H 'X-User-Id: {USERID}' -F 'app=@path/to/app/zip'`

**Comment by AgentTNT** [comment]
Worked fine on macOS 10.15.3 with both Chrome and Firefox via the app upload
