### ISSUE TITLE
Unable to connect to marketplace

### ISSUE THREAD

**Issue by mr-karan** [RocketChat/Rocket.Chat#16788]
### Description:

Unable to login to marketplace after registering workspace on Rocket.Chat Cloud Connect.

### Steps to reproduce:

1. Go to https://my.domain.com/admin/cloud and connected workspace to `Rocket.Chat Cloud`.

![image](https://user-images.githubusercontent.com/5689132/75961779-9d239580-5ee8-11ea-8856-3a98df8988ac.png)

2. Click on `Login to Rocket.Chat Cloud` to enable marketplace.

3. The redirect is stuck on `Authorization`.

![image](https://user-images.githubusercontent.com/5689132/75965917-80d72700-5eef-11ea-9fc7-26680f6538ee.png)

### Expected behavior:

To login to marketplace, normally.

### Actual behavior:

Browser redirect never finishes due to an error in the `JS` script.

### Server Setup Information:

- Version of Rocket.Chat Server:  2.4.9
- Operating System: Linux (4.15.0-1060-aws)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Firefox 74.0b6 (64-bit)
- Operating System: Arch Linux (Manjaro)

### Additional Context

- Self hosted workspace.

### Stack Trace

```
main.abb3865b.js:sourcemap:1 Uncaught (in promise) TypeError: Cannot read property 'client_id' of undefined
    at t.e (main.abb3865b.js:sourcemap:1)
    at t.<anonymous> (main.abb3865b.js:sourcemap:1)
    at t.authorizeOAuthClient (main.abb3865b.js:sourcemap:1)
    at t.<anonymous> (main.abb3865b.js:sourcemap:1)
    at r (main.abb3865b.js:sourcemap:1)
    at Generator._invoke (main.abb3865b.js:sourcemap:1)
    at Generator.e.<computed> [as next] (main.abb3865b.js:sourcemap:1)
    at r (main.abb3865b.js:sourcemap:1)
    at main.abb3865b.js:sourcemap:1
    at new Promise (<anonymous>)
```

**Comment by stefanandres** [comment]
I have the same behavior with 3.0.1

**Comment by geekgonecrazy** [comment]
Thanks for reporting.  Taking a look at it now.  Looks like its something on our side

**Comment by geekgonecrazy** [comment]
@mr-karan @stefanandres this should now be resolved.  Please let me know if its doesn't go away for you.

**Comment by mr-karan** [comment]
@geekgonecrazy This is fixed. Thanks a lot :)

**Comment by stefanandres** [comment]
Thanks, it works!
