### ISSUE TITLE
Blaze 2 React ?

### ISSUE THREAD

**Issue by tvld** [RocketChat/Rocket.Chat#1678]
Now MDG has indicated that Blaze is a dead end street and React the future, what will Rocket do?

Also Coffee seems to be overshadowed by ES6.

Both choices have big impact. What is the plan from the Rocket team? And how can we contribute?

**Comment by geekgonecrazy** [comment]
We have a discussion about ES6 here: https://github.com/RocketChat/Rocket.Chat/issues/796

But I think we are seriously considering moving over to ES6. I think we just have to make that decision and see what help we can get from our community.

On React... I know at least a few of us, are fans.  I think it would drastically improve the performance of our UI.

With both of these, if going forward.  We'd like to do it in a way that isn't going to halt our speed.  We are adding features at a pretty quick rate.

Please pipe in on the ES6 ticket.  Also maybe we need a ticket to discuss React.

**Comment by tvld** [comment]
ES6, I piped in
React: not a fan myself but mainly because MDG is going all over the place with their "core" choices. Who will create this "Move over to React"  ticket?

**Comment by sampaiodiego** [comment]
I think we should wait for Blaze 2 (or there is something new about Blaze 2 I'm not aware of? :smile:) which MDG already said might be something like an "interface" for React.
This way we could take the advantages of React with minor efforts, since Blaze template should keep working (or almost working).

**Comment by sampaiodiego** [comment]
follow: https://forums.meteor.com/t/next-steps-on-blaze-and-the-view-layer/13561

**Comment by geekgonecrazy** [comment]
@tvld https://github.com/RocketChat/Rocket.Chat/issues/1680
