### ISSUE TITLE
Drops connections to LDAP server

### ISSUE THREAD

**Issue by bakaut** [RocketChat/Rocket.Chat#16789]
### Description:

Drops connections to LDAP server

### Steps to reproduce:

Check rocket chat logs, docker logs -f 

### Expected behavior:

No error logs

### Actual behavior:

Error logs

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0 (docker image)
- Operating System: Centos 7
- Deployment Method: docker-compose (app in docker, mongo on host)
- Number of Running Instances: 4
- DB Replicaset Oplog: 
- NodeJS Version: 12.01
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: web client, Chrome last

### Relevant logs:

```
server.js:204 LDAP ➔ Connection.error connection Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
server.js:204 LDAP ➔ Search.info Closed
server.js:204 LDAP ➔ Connection.info LDAP connected

```

**Comment by homberger** [comment]
@bakaut: Did you find the cause of the error? I get this error every some minutes. The ldap server is perfectly reachable for other scripts and services.
