### ISSUE TITLE
Multiple servers all-in-one view

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#1679]
Instead of switching from server to server to be able to see channels of the other server(s), it would be useful and convenient to display channels of all the servers I'm connected to in a combined view mode.

So in this combined view mode, channel names under Favorites, Channels, or Direct Messages categories in the left panel will be displayed as "# general @server1.com" instead of "# general".

**Comment by geekgonecrazy** [comment]
My brain hurts just thinking how that would be implemented..  If we had all the servers under the *.rocket.chat umbrella like slack does this wouldn't be as bad.  But we don't.

Maybe someone clever has ideas.

**Comment by Sing-Li** [comment]
Ummm.

Someone stupid has a question:

"WHY?"

_Scrolling finger needs more exercise?_       [community input/flame solicited]

**Comment by rockneverdies55** [comment]
@Sing-Li - One quick example user story:  
Let's say I would like to chat with you over the demo server while simultaneously chatting with my colleague over the corporate server. I would like to see (and quickly catch up with) new messages and notifications from both conversations simultaneously. Don't want to switch between servers over and over...

**Comment by thedoozer** [comment]
Let's say I'm a services company, and I want to have a RocketChat install/site/something for each of my clients. 

I cannot allow client-name/user-name leakage between these 'client' sites so I really do want them to be independent (and not just invite only channels). But: I have a number of internal staff that will sit on one or more of these 'client' sites in addition to our own internal chat. 

My staff would love to be able to access the channels from the 'client' sites they are working with without having to have n open tabs (and more importantly having to monitor n open tabs)

**Comment by geekgonecrazy** [comment]
I think this should be handled at some sort of client level.  Doing this directly in the application is extremely complicated.

However that being said... There is actually a way to accomplish the same results, with out actually making Rocket.Chat connect and show all channels from each client.

Check out #601 

So we are actually starting some work with the guys over at Matrix.org.  This will give us the ability to have federation.  So if you want a channel shared with your clients you would simply join a channel on their server via federation.

So vs actually connecting all channels from that server, you have a channel that is shared between servers.

**Comment by engelgabriel** [comment]
I like @geekgonecrazy 's idea and this is already going to be implemented soon.
Merging all the different servers data on the client side would be really hard, not impossible, but close to it.

**Comment by geekgonecrazy** [comment]
@rockneverdies55 how does this approach sound?

**Comment by ninja-** [comment]
Uhh guys, it's already done at desktop APP level. Don't you like this?

**Comment by rockneverdies55** [comment]
@engelgabriel - what makes it impossible (or so close to impossible)?

**Comment by geekgonecrazy** [comment]
@ninja- he's talking something like:

![image](https://cloud.githubusercontent.com/assets/51996/12044301/96b5795a-ae54-11e5-9712-6b253f355333.png)

*Note: Only mock up*


@rockneverdies55 because the front end is very strongly tied to the backend.  The server its self would have to some how talk to the other server.  So the server would be relaying messages.  Which is why we suggest federation as a better approach to this.

**Comment by engelgabriel** [comment]
@rockneverdies55 you'd have to handle all connections to all different servers from a single client.

**Comment by rockneverdies55** [comment]
OK, what about something like this:

Assuming rocket.chat can receive unread message notifications from non active/current/selected servers...

1- let's say we decided to implement all in one view only in Favorites section in the left panel for the sake of simplicity. Which means user can have favorited channels from different servers only under Favorites section.
2- When user receives messages from channels, unread message alert badges etc in Favorites section will update as they normally do for all the channels.
3- when user clicks on a channel in Favorites section, app either directly loads the channel (if the clicked channel is in the current server) or switches to the server that owns the channel and then loads the channel.

Thanks.

**Comment by geekgonecrazy** [comment]
@rockneverdies55 again... This requires our web app to connect directly to multiple Rocket.Chat instances.  I don't think this is something we're really interested in doing.

That being said... Like I said earlier once we get federation added (which we are actively working on), you can join channels from remote instances locally.  But this will allow you to talk in channels from slack / irc etc... So this isn't Rocket.Chat specific.

So you would do something like: `/join someserver.com:#channel` and it would show up in your channel list.  That channel would be synchronized with their server.

This accomplishes your end goal.  Just maybe in a much more flexible way.

**Comment by rockneverdies55** [comment]
@geekgonecrazy still not 100% sure what you mean by channel sharing. However,

> So you would do something like: /join someserver.com:#channel and it would show up in your channel list. That channel would be synchronized with their server.

sounds like all I want. As long as I can follow up *(join easily, be notified when there are new messages, etc...)* with channels from all my servers (without keep switching between servers), that's it; that's all I'm asking for.

**Comment by engelgabriel** [comment]
@rockneverdies55 this https://github.com/RocketChat/Rocket.Chat/issues/601 will do what you want as @geekgonecrazy explained, so I'll close this issue here.
