### ISSUE TITLE
IRC federation not working, or settings unclear

### ISSUE THREAD

**Issue by mrtndwrd** [RocketChat/Rocket.Chat#16799]
### Description:

I'm trying to set up IRC federation with Freenode. My goal is to have our organisation's support IRC channel in our organisation's Rocket.Chat. I've tried to base my settings on what information was available in #216, but the issue is unclear on how to solve the `"SERVER","Not enough parameters"` problem that's also mentioned by others there.

### Steps to reproduce:

1. go to administration -> IRC Federation
2. My settings: 
   - Protocol: default 
   - Host: chat.freenode.net
   - Port: 6667
   - Name: chat.freenode.net (same as shown in https://github.com/RocketChat/Rocket.Chat/issues/216#issuecomment-499067668)
   - Description: IRC-bridge-freenode
   - local password: empty
   - peer password: empty
3. Save changes
4. Restart rocket.chat

### Expected behavior:

Connection to IRC works

### Actual behavior:

See [relevant logs](#relevant-logs)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Docker container on Kubernetes on Debian
- Deployment Method: docker (`docker.io/rocketchat/rocket.chat:2.4.9`)
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: from docker container
- MongoDB Version: `docker.io/bitnami/mongodb:4.0.12-debian-9-r5`

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Ubuntu

### Additional context

I've *really* tried reading all the issues about this. I've found a lot of information in #216, but it seems that that issue was closed without fixing the bug. The last comment suggests changing app.js, which I can not do in a Docker context.

It would really help me if somebody could tell me what the following fields are for:

- Name
- Description
- Local password
- Peer password

These don't seem to be common IRC terms and they are not explained in the interface nor in the documentation. I have the feeling that by changing one of these values I might be able to fix my issue, but I don't know what they mean, so I don't know what they should be. If somebody can point me in the right direction I wouldn't mind doing a PR with documentation improvements, because several people have asked for documentation in the issues I've found so far.

### Relevant logs:

Logs show: 

```
[irc][server] Connecting to @chat.freenode.net:6667
[irc][server] Connected! Registering as server...
[irc][server] Sending Command: PASS  0210 ngircd
[irc][server] Sending Command: SERVER chat.freenode.net :IRC-bridge-freenode
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Looking up your hostname..."]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Checking Ident"]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Couldn't look up your hostname"]}
...
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** No Ident response"]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"err_needmoreparams","rawCommand":"461","commandType":"error","args":["*","SERVER","Not enough parameters"]}
[irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: 127.0.0.1 (Connection timed out)"]}
[irc][server] Connection Closed
```

**Comment by dg-otrs** [comment]
Having the same "trouble".

Bit some more documentation would be awesome. So far I will try: https://github.com/RocketChat/Rocket.Chat/pull/10113

**Comment by dg-otrs** [comment]
> Having the same "trouble".
> 
> Bit some more documentation would be awesome. So far I will try: #10113

Was using #10113 recommendations. with same config file from 
#1 https://github.com/RocketChat/Rocket.Chat/pull/10113#issue-174534240

Still not able to get it working

I20200310-16:28:53.090(0) [irc][server] Connecting to @xxx.com:6667 
I20200310-16:28:53.132(0) [irc][server] Connected! Registering as server... 
I20200310-16:28:53.133(0) [irc][server] Sending Command: PASS  0210 ngircd 
I20200310-16:28:53.133(0) [irc][server] Sending Command: SERVER XXX.com :Rocket.Chat IRC Bridge 
I20200310-16:28:53.164(0) [irc][server] Unhandled peer message: {"prefix":"global.rocket.chat","server":"global.rocket.chat","command":"err_needmoreparams","rawCommand":"461","commandType":"error","args":["*","PASS","Syntax error"]} 
I20200310-16:28:55.167(0) [irc][server] Unhandled peer message: {"prefix":"global.rocket.chat","server":"global.rocket.chat","command":"err_needmoreparams","rawCommand":"461","commandType":"error","args":["*","SERVER","Syntax error"]}

**Comment by w4rc0n** [comment]
Can confirm, also having the same issues as the posters above. 

 I20200324-19:00:59.967(0) [irc][server] Connecting to @irc.redacted.com:6667 
I20200324-19:00:59.971(0) [irc][server] Connected! Registering as server... 
I20200324-19:00:59.971(0) [irc][server] Sending Command: PASS password 0210 ngircd 
I20200324-19:00:59.972(0) [irc][server] Sending Command: SERVER redacted :redacted IRC Bridge 
I20200324-19:00:59.972(0) [irc][server] Unhandled peer message: {"command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["AUTH","*** Processing connection to irc1.redacted.com"]} 
I20200324-19:00:59.973(0) [irc][server] Unhandled peer message: {"command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["AUTH","*** Looking up your hostname..."]} 
I20200324-19:00:59.973(0) [irc][server] Unhandled peer message: {"command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["AUTH","*** Checking Ident"]}
