### ISSUE TITLE
Public channel cannot be acessed via URL when 'Allow Anonymous Read' is active

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat#16791]
### Description:

Public channel cannot be acessed via URL when "Allow Anonymous Read" setting is active.

### Steps to reproduce:

1. Go to Settings -> Accounts -> Activate "Allow Anonymous Read" 
2. Try to access a public room using the URL path (example: http://YOURHOST/channel/general)
3. Room will be stuck (loading)

![screenshot_13](https://user-images.githubusercontent.com/11891939/75989970-e832ae00-5ed2-11ea-9b91-46d9f607e663.png)

### Expected behavior:

Rocket.Chat should allow the access of public rooms via URL when "Allow Anonymous Read" is set

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop
- Operating System: All

### Client Setup Information

- Desktop App or Browser Version: All
- Operating System: All

### Relevant logs:

Server logs:
_I20200305-11:11:37.059(-3)? Meteor ➔ method rooms/get -> userId: null, arguments: [{}]_

Browser console:

![screenshot_12](https://user-images.githubusercontent.com/11891939/75989588-4ad77a00-5ed2-11ea-95e1-bd92f84c7e4b.png)

**Comment by ashwaniYDV** [comment]
I'm onto it
