### ISSUE TITLE
Make possible to remove users from room

### ISSUE THREAD

**Issue by AdrianoCahete** [RocketChat/Rocket.Chat#168]
When you're admin, you need to remove (temporarily or definitely) some users sometimes (for many reasons, dismissals f.e.). 
Right button on name on user list with a small popup with actions will be good.

**Comment by diomed** [comment]
I completely agree. Banning them, and deleting their messages should be an option.

**Comment by jerdog** [comment]
Ban with option to delete messages is preferred. Also needs to be only available to creator of channel

**Comment by AdrianoCahete** [comment]
Not only to creator, but administrators or moderators (or some access rules to grant/deny).

**Comment by WikiCopter** [comment]
Yes. Like IRC, it would be also nice, in additon to a GUI, to have text commands (say //kick @example).

**Comment by engelgabriel** [comment]
Depends on #206

**Comment by WikiCopter** [comment]
Guys. I'm OCD. Please, someone, rename this thread to "Ability to..." rather than "Hability to..."
