### ISSUE TITLE
DeepL auto-translate broken? rocketchat 3.0.3

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#16800]
Hello Devs.

Just wanted to try deepl auto-translate. After finishing the setup for that I tried to test it but to no avail. No translation is made. Logfile:

`
I20200306-13:44:43.451(1) server.js:204 System ➔ error Error translating message Error: failed [403]     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/opt/rocketchat-3.0.3/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:311:20)     at Request.EventEmitter.emit (domain.js:482:12)     at Request.<anonymous> (/opt/rocketchat-3.0.3/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:311:20)     at Request.EventEmitter.emit (domain.js:482:12)     at IncomingMessage.<anonymous> (/opt/rocketchat-3.0.3/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:417:28)     at IncomingMessage.emit (events.js:323:22)     at IncomingMessage.EventEmitter.emit (domain.js:482:12)     at endReadableNT (_stream_readable.js:1204:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21) {   response: {     statusCode: 403,     content: '',     headers: {       server: 'nginx',       date: 'Fri, 06 Mar 2020 12:44:43 GMT',       'content-length': '0',       connection: 'close',       'access-control-allow-origin': '*'     },     data: null   } } 
`
So who is giving me this 403? I'm running Apache so this can't be my own server.

Rocketchat 3.0.3
NodeJS 2.16.1

**Comment by himpierre** [comment]
https://www.deepl.com/pro.html#developer subscription is needed. Now it works.

**Comment by raza2022** [comment]
@himpierre can you please give more details, because I have subscription too, but getting same error, did you altered the RC deepl implementation function?

**Comment by himpierre** [comment]
Did you change the API Key accordingly?

**Comment by raza2022** [comment]
![image](https://user-images.githubusercontent.com/5462788/90011962-f4aa0680-dcbb-11ea-8d12-a63c660293df.png)
yes all thing set up properly

**Comment by himpierre** [comment]
I see. No further ideas. Sorry.
