### ISSUE TITLE
Not showing Chinese characters on channel name in mobile app when language is set to Chinese

### ISSUE THREAD

**Issue by dickensdjj** [RocketChat/Rocket.Chat#16808]
### Description:

I've run the rocket chat on my own server and intend to use as the major team communication for China mainland team. Everything works perfect in desktop app and web app, but on the mobile app (both andriod and IOS), no chinese characters is shown in channel name. Instead, it translates to pinyin, which can be presented in English alphabet. 

### Steps to reproduce:

1. Go to Layout -> User Interface -> enable 'Allow special characters in room names'.
2. Go back to chat and click on New message -> Create Channel -> input channel name '测试', which is the same meaning as 'testing' -> click create
3. Go to user dashboard -> language -> choose 简体中文
4 Go back to the chat and see the created channel name is saved as ce4-shi4

### Expected behavior:

After Step 3, the channel name should be '测试'

### Actual behavior:

After Step , the channel name is 'ce4-shi4'

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.3
- Operating System: Centos 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Andriod app download from google app version 4.4.0
- Operating System: Andriod

- Desktop App or Browser Version: IOS app download from app store version 4.4.0
- Operating System: IOS 13.3.1 on IPAD

### Additional context

It works fine on both desktop and website.

**Comment by talheim-it** [comment]
@dickensdjj can you switch tthat to rocket.chat/reactnative client?

you posted into the server and not into the app version :)

Otherwise copy the content to the reactnative and close this one.

yours,
Mathias

**Comment by jamping** [comment]
slugify is true, so channel name of '测试'  is saved as ce4-shi4

**Comment by dickensdjj** [comment]
Since it is not a issue of webapp so I opened a new one [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1867).
I will close this issue.

**Comment by hermanlee1996** [comment]
> slugify is true, so channel name of '测试' is saved as ce4-shi4

布局-用户界面-允许Room名称中的特殊字符 关闭就能恢复正常
