### ISSUE TITLE
Feature Request : Poll App delete button feature

### ISSUE THREAD

**Issue by Sahil-Bhatt** [RocketChat/Rocket.Chat#16819]
As of now, a user can just create new choices in the **Rocket Chat Poll App**.
A button that can help a user delete/modify a previous choice would make the interface even better and more convenient.

Link to the repository: [https://github.com/sampaiodiego/rocket.chat.app-poll](ur)

**Comment by ggazzo** [comment]
Sorry, @Sahil-Bhatt but I don't think this is the right place...the poll app is not under our organization :(  ... Since you opened an issue there, I will close this one, feel free to contribute in both projects :)
