### ISSUE TITLE
“”Invite Link“ ,our users can only  use rocket.chat in our own network,we can't visit https://go.rocket.chat/invite

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16815]
“”Invite Link“ ,our users only can use rocket.chat in our own network,we can't visit https://go.rocket.chat/invite
so we can't use the Invite Url function

**Comment by reetp** [comment]
Buried, but there.

Admin/Accounts/Registration/Invite URL Type

It does make you wonder what happens to the data that is collected by go.rocket.chat? There is no notification that data gets sent there when you create a link.

**Comment by 564064202** [comment]
thks

**Comment by cryptobanana** [comment]
There are important privacy considerations involved with this default behavior for which the rocket chat project would strongly benefit from having them addressed: https://github.com/RocketChat/Rocket.Chat/issues/17467#issuecomment-631042099
