### ISSUE TITLE
Logout saml: ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by devwinner-sek** [RocketChat/Rocket.Chat#16817]
Rocketchat informations: 
Version: 3.0.3
Node: 12.4
Version Mongo : 4.2.3

I configured SAML with Rocketchat. I’m using WSO2 identity server

I created a service provider in WSO2, this is it’s informations :

**Issuer** :  https://rocketchat.domain.net/_saml/metadata/Roocketchat_dacrtech

**Assertion Consumer URL** : https://rocketchat.domain.net/_saml/validate/Roocketchat_dacrtech

Enable logout

**Logout url** :  https://rocketchat.domain.net/_saml/logout/Roocketchat_dacrtech

Enable attribute profile

Include Attributes in the Response Always

Configuration of SAML, Rocketchat side :

**Custom Provider**

Roocketchat_dacrtech

**Custom Entry Point**

https://wso2.domain.net:9443/samlsso

**IDP SLO Redirect URL**

https://wso2.domain.net:9443/samlsso

**Custom Issuer**

https://rocketchat.domain.net/_saml/metadata/Roocketchat_dacrtech

**Immutable field name**
**E-mail**

**List of user field**

{"http://wso2-org/claims/username":"username", "http://wso2-org/claims/emailaddress":"email", "http://wso2-org/claims/fullname": "name"}

**Role attribute Name :**

**http://wso2-org/claims/username**

The login with SAML on Rocketchat is working correctly. But i have a problem with logout. When a user logs out, he is redirected to his session page again. In the log files, i have this error:       

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined     at Function.from (buffer.js:305:9)     at new Buffer (buffer.js:265:17)     at SAML.validateLogoutResponse (app/meteor-accounts-saml/server/saml_utils.js:374:33)     at middleware (app/meteor-accounts-saml/server/saml_server.js:604:12)     at app/meteor-accounts-saml/server/saml_server.js:704:3 {   code: 'ERR_INVALID_ARG_TYPE' }

**Comment by pierre-lehnen-rc** [comment]
Can you enable debug mode and collect the Logout Response that is received by Rocket.Chat? based on this error I assume that we didn't receive the SAMLResponse param on the URL.

I'm making some changes now to ensure that the logout flow doesn't break when this happens, but the user will still not get logged out if that param is missing.
