### ISSUE TITLE
HIPAA Compliance

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#1681]
Useful links

https://www.mongodb.com/blog/post/making-hipaa-compliant-applications-mongodb

https://forums.meteor.com/t/hipaa-compliant-meteor-deployments-for-healthcare-applications/814/5

https://www.mongodb.com/blog/post/making-hipaa-compliant-applications-mongodb
##

**Comment by woakes070048** [comment]
@engelgabriel did you ever get this figured out? I would like to implement this for a mental health agency i work at.

**Comment by designgurudotorg** [comment]
@engelgabriel - does RC satisfy the compliance requirements for HIPAA (asides from the actual hosting config / data centre?)

**Comment by milan-markovic** [comment]
Any news on HIPAA compliance for Rocket Chat?

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
