### ISSUE TITLE
How to upgrade a 2.* version to 3.* version?

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16827]
I want to upgrade 2.4.11 to 3.*，could you give me a hand?

**Comment by talheim-it** [comment]
Hello @564064202,

what installation do you use? Non-docker?

If yes:
https://rocket.chat/docs/installation/updating/

I would prefer that way:

-  mongodump --out /opt/backups/rocketchatbackup
-  mv /opt/Rocket.Chat/ /opt/backup
-  systemctl stop rocketchat.service 
-  curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
-  tar -xzf /tmp/rocket.chat.tgz -C /tmp
-  cd /tmp/bundle/programs/server && npm install
-  sudo mv /tmp/bundle /opt/Rocket.Chat
-  cd /opt/
-  chown -R rocketchat:rocketchat Rocket.Chat/
-  systemctl start rocketchat.service

That should do it.

Docker is much simplier but not needed I guess :)

Yours,
Mathias

**Comment by 564064202** [comment]
thank you ,but I use snap ,how to upgrade?

**Comment by talheim-it** [comment]
@564064202 

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

sudo snap refresh rocketchat-server

**Comment by 564064202** [comment]
my version is 2.4.11,but this command result is:
snap "rocketchat-server" has no updates available

**Comment by talheim-it** [comment]
@564064202 there is no package yet for version 3.

I just tried in on a fresh installed vagrant box on ubuntu 18.04.

You have to wait till it become available.

So you can close this ticket and just wait.

**Comment by 564064202** [comment]
Thank you every much ,but could you tell me what's the diffrence between 2.* and 3.*

**Comment by talheim-it** [comment]
@564064202 ,
https://github.com/RocketChat/Rocket.Chat/releases

You can see the changes there. :)

Just read the changelogs.

**Comment by 564064202** [comment]
@talheim-it thank you.
"I just tried in on a fresh installed vagrant box on ubuntu 18.04." 
sir ,when you finish it,please tell me .bye....

**Comment by lent85** [comment]
sudo snap refresh rocketchat-server --channel=3.x/stable --classic
Just did upgrade from 2.4.11 to 3.0.10 without problem. 
Recommend to backup anyway.

**Comment by RonarPS** [comment]
> Hello @564064202,
> 
> what installation do you use? Non-docker?
> 
> If yes:
> https://rocket.chat/docs/installation/updating/
> 
> I would prefer that way:
> 
> * mongodump --out /opt/backups/rocketchatbackup
> * mv /opt/Rocket.Chat/ /opt/backup
> * systemctl stop rocketchat.service
> * curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
> * tar -xzf /tmp/rocket.chat.tgz -C /tmp
> * cd /tmp/bundle/programs/server && npm install
> * sudo mv /tmp/bundle /opt/Rocket.Chat
> * cd /opt/
> * chown -R rocketchat:rocketchat Rocket.Chat/
> * systemctl start rocketchat.service
> 
> That should do it.
> 
> Docker is much simplier but not needed I guess :)
> 
> Yours,
> Mathias

thanks a lot for those hints - upgrade has worked perfectly - after upgrading npm and nodejs and relinking the node vs. nodejs problematic. Now running on RC serer 3.12 :)

**Comment by duven87** [comment]
Hi, Im trying since days upgrating my rocketchat 2.2.0  to 4.5.x from  mongodb (mmapv1) 4.0 to mongodb 4.4 (wiredTiger) with Debian Buster + node.
I have tried a lot of ways but I always get errors either from mongo or rocketchat.

In the end I gave up with the original server and installed a new one with rocketchat 4.4 and mongodb 4.4. After some changes it started correctly.
Then I made a dump from the other server:
mongodump --archive=/root/rocketdb/mmapdump.gz --gzip
and sent it to the new one.
And on the new one:
mongorestore --drop --archive=/root/mmapdump.gz --gzip --noIndexRestore

The correct import but with "mongo --eval 'db.repairDatabase()'":

MongoDB server version: 4.4.13
uncaught exception: TypeError: db.repairDatabase is not a function :
@(shell eval):1:1
exiting with code -4

Then I tried to start rocketchat but I get this:

```
Mar 18 16:45:18 debian10 rocketchat[9770]: LocalStore: store created at
Mar 18 16:45:31 debian10 rocketchat[9770]: {"level":40,"time":"2022-03-18T15:45:31.026Z","pid":9770,"hostname":"[debian10.mycompay.com](http://debian10.mycompany.com/)","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Mar 18 16:45:31 debian10 rocketchat[9770]: /opt/[Rocket.Chat/programs/server/node_modules/fibers/future.js:280](http://rocket.chat/programs/server/node_modules/fibers/future.js:280)
Mar 18 16:45:31 debian10 rocketchat[9770]: #011#011#011#011#011#011throw(ex);
Mar 18 16:45:31 debian10 rocketchat[9770]: #011#011#011#011#011#011^
Mar 18 16:45:31 debian10 rocketchat[9770]: Error: Can't find migration version 166
Mar 18 16:45:31 debian10 rocketchat[9770]:     at migrateDatabase (server/lib/migrations.ts:246:9)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at module (server/startup/migrations/xrun.js:8:1)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.require (packages/modules-runtime.js:238:14)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.moduleLink [as link] (/opt/[Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22](http://rocket.chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22))
Mar 18 16:45:31 debian10 rocketchat[9770]:     at module (server/startup/migrations/index.ts:1:17)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.require (packages/modules-runtime.js:238:14)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.moduleLink [as link] (/opt/[Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22](http://rocket.chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22))
Mar 18 16:45:31 debian10 rocketchat[9770]:     at module (server/startup/index.ts:1:8)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.require (packages/modules-runtime.js:238:14)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.moduleLink [as link] (/opt/[Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22](http://rocket.chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22))
Mar 18 16:45:31 debian10 rocketchat[9770]:     at module (server/main.ts:1:41)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Module.require (packages/modules-runtime.js:238:14)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at require (packages/modules-runtime.js:258:21)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at /opt/[Rocket.Chat/programs/server/app/app.js:211889:15](http://rocket.chat/programs/server/app/app.js:211889:15)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at /opt/[Rocket.Chat/programs/server/boot.js:401:38](http://rocket.chat/programs/server/boot.js:401:38)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at Array.forEach (<anonymous>)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at /opt/[Rocket.Chat/programs/server/boot.js:226:21](http://rocket.chat/programs/server/boot.js:226:21)
Mar 18 16:45:31 debian10 rocketchat[9770]:     at /opt/[Rocket.Chat/programs/server/boot.js:464:7](http://rocket.chat/programs/server/boot.js:464:7)
Mar 18 16:45:31 debian10 systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 16:45:31 debian10 systemd[1]: rocketchat.service: Failed with result 'exit-code'.
```
could you tell me the best procedure please?
