### ISSUE TITLE
To much places to post feature requests

### ISSUE THREAD

**Issue by juliensl** [RocketChat/Rocket.Chat#16823]
Hi the team ! 

I think that there is a communication problem for feature requests (and maybe for issue too).

Today, you can post Feature request : 

- In the rocket chat forum : https://forums.rocket.chat/c/feature-requests/8 (depreciated since 2018 but still in activity)
- In the feature request repository : https://github.com/RocketChat/feature-requests/issues ( but lot's of discussions still with no answer, even after months )
- As an issue in each repository ( here Rocket.chat, Rocket.chat.ReactNative, ... )
- I'm pretty sure that some people post in the open chat too.

You should do something, because it looks like hard to send to you ideas from people like me, who use Rocket Chat but are not developing the app :'( 

I can recommend you to close the channel Feature Request in the forum, definitely, maybe close the repo Feature Request too, because you'll have a mix of too many different modules in the same repo. 
Add a #featureRequest tag in the issues for each repo looks like the better idea for me, this is the strategy used by other projects I think.

What do you think ? maybe I am wrong :thinking:

**Comment by talheim-it** [comment]
It depends on.

It makes sense to post them into github, since most active people have an github account.

The easiest way from my perspective to switch to github is to write the community manager or moderator to close the discourse channel and just link to the github repo :)

Yours,
Mathias

**Comment by juliensl** [comment]
Hi ! 

I'm coming back for this question.
I see that nothing change :'( 

If you want to still like this, could you tell me please, where should I post my feature requests ?

Thank you and have a good day ! :)

**Comment by talheim-it** [comment]
@juliensl did you read my answer? Did you proceed with it?

Or did you just wait for another answer without taking action?

As I wrote above:
"The easiest way from my perspective to switch to github is to write the community manager or moderator to close the discourse channel and just link to the github repo :)"

I think that is the easiest way to go.

**Comment by juliensl** [comment]
You right.... I didn't do any efforts 😆  

I just sent now a message to the team, let's wait now :)

**Comment by juliensl** [comment]
Hi @talheim-it !

I contacted Diego and they closed the forum section :tada: 

I close this issue.

Have a good day !
