### ISSUE TITLE
Room not found on first DM

### ISSUE THREAD

**Issue by pkavajin** [RocketChat/Rocket.Chat#16822]
### Description:
When trying to write a DM to a new user the very first time, an "broken" error page appears, showing "Room not found" as title and "Error, too many requests. Please slow down. You must wait 46 before trying again." When switching back to another screen and trying the same thing again after that, it's fixed for that user.
Sadly no error message or warning is logged on the server.

### Steps to reproduce:

1. Search for a new user who'm you never talked before to
2. Click on him to start a new DM
3. Badabang. You should see the error message right now.

### Expected behavior:

When trying to DM a new user, it should open the normal DM Screen.

### Actual behavior:

The very first time writing a DM to a new user you haven't wrote a message before to, an non-descriptive error page appears.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.9
- Operating System: Linux
- Deployment Method: Hem Chart / K8S
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.17.0
- MongoDB Version: 4.0.12-debian-9-r5

### Client Setup Information

- Desktop App or Browser Version: 2.17.7
- Operating System: macOS

### Screenshots

![image](https://user-images.githubusercontent.com/28445986/76234729-645a2800-622a-11ea-9672-6865ac04be3d.png)

**Comment by gabriellsh** [comment]
`Version of Rocket.Chat Server: 2.4.9` we're at version 3.0.3 already. Could you test this on latest? I couldn't reproduce it.

**Comment by lent85** [comment]
Same issue happen for RocketChat 4.5.0 by now
![image](https://user-images.githubusercontent.com/9914782/156982823-dcfaf45a-1401-4add-8101-62ea7936d81e.png)
