### ISSUE TITLE
How to edit files in snap (we used snap package)

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16828]
How to edit files in snap (we used snap package),
some words have not been translated,so we wan to edit.
some translation are wrong ,so we want to edit.

**Comment by gabriellsh** [comment]
You can't edit snap versions, it is meant for development.

But, if you want to help with translations, you can contribute here on github and if it gets merged, next release it'll be on snap too!

There's the option of cloning the repo and trying to build it for snap, but thats on your own.
