### ISSUE TITLE
Log in to the administrator account, and click any one of the management interfaces to fail to respond

### ISSUE THREAD

**Issue by yuhaihan** [RocketChat/Rocket.Chat#16839]
![image](https://user-images.githubusercontent.com/42633508/76402873-fdba4300-63be-11ea-85ac-8661de5da267.png)

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
