### ISSUE TITLE
Second video call in Lievechat with Jitsi Meet repeated refrash

### ISSUE THREAD

**Issue by inimatic** [RocketChat/Rocket.Chat#16830]
If I make second Video call using Jitsi Meet (JM) to Lievechat client then the JM web page hangs by continuous refreshing. 
First call goes well.

BTW. Client didn't receive a link to the JM video call but empty message showed.  So I had to copy the JM link and post it to the client chat.

Client:
Calling from: Google Chrome latest on Windows 10. 
Calling to: Latest chrome on Android or Google Chrome latest on Windows 10
RocketChat Server 
Version | 3.0.0
Apps Engine Version 1.12.0

**Comment by talheim-it** [comment]
Hello @inimatic,

bug is already fixed in a later version.

Please upgrade your installation to 3.0.3

Yours,
Mathias

**Comment by inimatic** [comment]
Sorry. I will upgrade the server.

вт, 10 мар. 2020 г., 14:41 Mathias Rumbold <notifications@github.com>:
