### ISSUE TITLE
starred messages in threads are not displayed

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#16831]
### Steps to reproduce:

1. Make a message in thread as starred
2. Open starred messages for room

### Actual behavior:

![image](https://user-images.githubusercontent.com/19654261/76286931-1c3c1380-62c5-11ea-894b-619b8be7ec59.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop

**Comment by ritwizsinha** [comment]
@gabriellsh please review

**Comment by antkaz** [comment]
@ritwizsinha thanks for your help!)

**Comment by ritwizsinha** [comment]
You welcome @antkaz
