### ISSUE TITLE
No duplicate firstname / lastname combination possible anymore

### ISSUE THREAD

**Issue by ssartorius** [RocketChat/Rocket.Chat#16834]
### Description:

In earlier versions we were able to create users with same firstname and lastname, as you can see in the screenshot (communication is over REST API).

![Screen_from_userlist](https://user-images.githubusercontent.com/57718460/76294805-d591ed80-62b3-11ea-9f49-a8f7faf64e3c.png)

If a username already exists, we append the ID from our system, to make sure the username is unique (it's also used in the email adress).

However we can't create new users anymore, when firstname and lastname combination is already in the database.

### Steps to reproduce:

Use Postman or a similar tool.
Create a user with firstname = x and lastname = y and username = "x_y".
Try to create another user firstname = x and lastname = y and username = "x_y-12345678".

My example was:

Request:
{
	"name": "Testi Tester", 
	"email": "30001234@webmail.sgd.de", 
	"password": "geheim", 
	"username": "Testi_Tester",
	"customFields" : {
		"wl-id": "30001234"
	}
}

Response:
{
    "user": {
        "_id": "xTSiHdoynrzW3LFRC",
        "createdAt": "2020-03-10T08:37:26.372Z",
        "username": "Testi_Tester",
        "emails": [
            {
                "address": "30001234@webmail.sgd.de",
                "verified": false
            }
        ],
        "type": "user",
        "status": "offline",
        "active": true,
        "_updatedAt": "2020-03-10T08:37:26.428Z",
        "roles": [
            "user"
        ],
        "name": "Testi Tester",
        "settings": {},
        "customFields": {
            "wl-id": "30001234"
        }
    },
    "success": true
}

--------------------------------------------------------------------------------------------------

Request:
{
	"name": "Testi Tester", 
	"email": "30001235@webmail.sgd.de", 
	"password": "geheim", 
	"username": "Testi_Tester-30001235",
	"customFields" : {
		"wl-id": "30001235"
	}
}

Response:
{
    "success": false,
    "error": "Testi_Tester-30001235 is not a valid username [error-input-is-not-a-valid-field]",
    "errorType": "error-input-is-not-a-valid-field"
}

### Expected behavior:

User will be created correctly.

### Actual behavior:

User isn't created.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2 and 3.0.3
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: nothing
- NodeJS Version: 12.14.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Browser: Firefox 68.5.0esr (64-Bit)
- Operating System: Debian 9

### Additional context

Tested with v3.0.2 and 3.0.3
The manual creation does not work either (same error).

### Relevant logs:

10.03.2020 08:38:58   STDERR: java.io.IOException: Error while reading from POST: [400] Bad Request
{"success":false,"error":"anonym_anonym-12345678 is not a valid username [error-input-is-not-a-valid-field]","errorType":"error-input-is-not-a-valid-field"}
	10.03.2020 08:38:58   STDERR: 	at us.monoid.web.AbstractResource.fill(AbstractResource.java:51)
	10.03.2020 08:38:58   STDERR: 	at us.monoid.web.Resty.fillResourceFromURL(Resty.java:432)
	10.03.2020 08:38:58   STDERR: 	at us.monoid.web.Resty.doPOSTOrPUT(Resty.java:394)
	10.03.2020 08:38:58   STDERR: 	at us.monoid.web.Resty.json(Resty.java:223)
	10.03.2020 08:38:58   STDERR: 	at us.monoid.web.Resty.json(Resty.java:228)
	10.03.2020 08:38:58   STDERR: 	at de.sgd.waveLearn.rocketChat.RocketChatClient.registerUser(RocketChatClient.java:458)

**Comment by ssartorius** [comment]
The problem was a regex for room and usernames. The unicode range I've defined should contain - sign, but it doesn't. After modification it works.

**Comment by ahmadaii** [comment]
@ssartorius where did you define this rejex. I have same issue no matter what username I choose.

**Comment by DyllasDek** [comment]
> @ssartorius where did you define this rejex. I have same issue no matter what username I choose.

You need to go to "Configure general workspace settings." and there will be UTF8 tab
