### ISSUE TITLE
How to add custom file type to Accepted Media Types

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#16836]
### Description:

There is no way to add custom file type to **Accepted Media Types**

### Steps to reproduce:

1. Try to send **text.cs** file
2. Get error **Media Types not Accepted** on type `*.cs`
3. Admins adds `*.cs` to **Accepted Media Types**
4. You still get the same error.

### Expected behavior:

When admin adds to **Accepted Media Types** particular type from **Media Types not Accepted** error to **Accepted Media Types** that file type is granted to send.

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/76304882-30880c80-62d5-11ea-8b2c-9a7459a67340.png)
Admin added `text/x-csharp,text/asp,*.cs` with no luck

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App Version: 2.17.7
- Operating System: Windows 10

### Additional context

The problem not in `*.cs` file type itself but in any file type, that not resolved to MIME type on uploading.
For example, if you try to upload a certificate `*.cer` file, you get error:
![image](https://user-images.githubusercontent.com/4023037/76306179-7ba31f00-62d7-11ea-894b-61c72664f00c.png)
And then in Admin adds `application/pkix-cert` to **Accepted Media Types** it works great, and now you can upload `*.cer` files
![image](https://user-images.githubusercontent.com/4023037/76306322-bc9b3380-62d7-11ea-8d7f-8b0d2f627c24.png)
But if MIME type doesn't recognized - there is way to add that custom file type to **Accepted Media Types**

**Comment by ggazzo** [comment]
related https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/239
