### ISSUE TITLE
send file

### ISSUE THREAD

**Issue by auqf** [RocketChat/Rocket.Chat#16832]
I use the lastest of the pc rocket.chat, I offen meetting the problem, I can not download the file of the others send to me? why? But I can get the file by the browser of the file's url

**Comment by talheim-it** [comment]
Hello @auqf ,

which rocket.chat version of the server and which client version?

Yours,
Mathias

**Comment by auqf** [comment]
![image](https://user-images.githubusercontent.com/8895540/76596860-2581e600-653a-11ea-8ed8-6afc628aca64.png)
![image](https://user-images.githubusercontent.com/8895540/76596876-2c105d80-653a-11ea-8a95-b45c84fbd828.png)

and I found that the rocketchat server is always connecting the server:"3.93.26.21:443", is it a hole?

**Comment by auqf** [comment]
![image](https://user-images.githubusercontent.com/8895540/76596971-6bd74500-653a-11ea-9cae-d03434d28ddc.png)

**Comment by auqf** [comment]
hi, can you find it? how can I fix it?

**Comment by auqf** [comment]
I found that when the people of the chat is online less, the file can download normally,is there a limit of the used users?
