### ISSUE TITLE
how to choose gridfs vs filesystem

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16833]
how to choose gridfs vs filesystem,which one is better?

**Comment by talheim-it** [comment]
@564064202 that is not an issue. 
Such things should be placed in the discourse channel of rocket.chat:
https://forums.rocket.chat/

Example/reason for:
https://docs.mongodb.com/manual/core/gridfs/

**Comment by gabriellsh** [comment]
Thanks @talheim-it ! You're right. Github is the place for bugs/features. I'll be closing this.
