### ISSUE TITLE
Login via Crowd fails with certain symbols

### ISSUE THREAD

**Issue by jamesbruce166** [RocketChat/Rocket.Chat#16840]
### Description:

Rocket.Chat authentication fails via Crowd, when using the following symbols within the user password - all have been tried and tested individually:
§ Ä Ö Ü ´ ° ß ä ö ü £ $

Tried and tested on:
Rocket.Chat <= 3.0.3
Crowd Version: 3.4.6

A list of all symbols tested individually are: 
! " £ $ % ^ & * ( ) _ + = @ : ; § Ä Ö Ü ´ ° ß ä ö ü ~ # < > \ / | ? 
 
### Steps to reproduce:

1. Add user in crowd with password containing one of the broken symbols (e.g. 'password£')
2. Try to authenticate against Rocket.Chat at the login screen
3. Error: User not found or incorrect password 
4. Repeat with working symbol (e.g. 'password%') 
5 Login successful

### Expected behavior:

I expect any ASCII symbol to be valid in a user password.

### Actual behavior:

Password cannot correctly sync with symbols described above.

### Server Setup Information:

- Version of Rocket.Chat Server: <= 3.0.3
- Operating System: Linux 
- Deployment Method: Docker deployment 
- Number of Running Instances: Tried 5 & 7
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: Tried 3.6 & 4.0

### Relevant logs:
(taken from older version) 
rocketchat_logger rocketchat_logger.js:377 CROWD ➔ info Init CROWD login $username
rocketchat_logger rocketchat_logger.js:377 CROWD ➔ info Going to crowd: $username
rocketchat_logger rocketchat_logger.js:377 CROWD ➔ error Crowd user not authenticated due to an error, falling back

Similar issue was raised almost 3 years ago but is incomplete.
https://github.com/RocketChat/Rocket.Chat/issues/7586

**Comment by ITSonixcdGmbH** [comment]
That problem is present since years. They did not bother to fix it, Its a big safety concern.
