### ISSUE TITLE
Failed to sync with Rocket.Chat Cloud error_updating_account_in_zoho_crm

### ISSUE THREAD

**Issue by adrianovieira** [RocketChat/Rocket.Chat#16842]
Hi!

After we upgraded from 2.4.7 to 3.0.3, we are facing this error on our on-premise Rocket Chat.

```
Failed to sync with Rocket.Chat Cloud.  Error: error_updating_account_in_zoho_crm
```

Please, can you explain what exactly this does and what are rocket chat  trying to do here?

**Comment by sizeg** [comment]
2.4.11 same errors
