### ISSUE TITLE
[FEATURE] Add a possibility to see everybody who reacted to the message. 

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat#16848]
Currently, when you are checking who reacted to the message with a certain emoji only 15 users are shown, so if you have 25 people reacted with a thumbs up to your message - you'll see names of only 15 of them + "and 10 more people" - would be good to be able see the whole list with the names of everybody.

**Comment by zdumitru** [comment]
This is still an issue. Should not be closed.
