### ISSUE TITLE
[FEATURE] Add a possibility to see people who read the message. 

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat#16847]
Currently, there is no way to see who were the users that read it - would be good to have it (Facebook Messenger like). 

![messenger](https://user-images.githubusercontent.com/45059765/76459130-53551680-63e4-11ea-8655-0ad27e5f7f41.png)

**Comment by ankar84** [comment]
It you enable in **Admin UI => Message** two options:
- **Show Read Receipts**
- **Detailed Read Receipts**
you will be able to see who read message in it's context menu:

![image](https://user-images.githubusercontent.com/4023037/76488693-3b5ab280-6437-11ea-8ce9-84c50b7d0803.png)
![image](https://user-images.githubusercontent.com/4023037/76488749-5fb68f00-6437-11ea-866e-3906ab588482.png)
![image](https://user-images.githubusercontent.com/4023037/76488789-8ecd0080-6437-11ea-86f6-16a334072b09.png)
