### ISSUE TITLE
Cannot add Marketplace Apps - Not Authorized

### ISSUE THREAD

**Issue by TheZLabs** [RocketChat/Rocket.Chat#16844]
![image](https://user-images.githubusercontent.com/59536236/76439831-625fa880-6393-11ea-90a8-f14ca966a417.png)

This happens with any app I try to install from the marketplace. I have made no changes to the server especially regarding permissions. This has not been an issue before.

**Comment by talheim-it** [comment]
@TheZLabs did you update the server latestly? 

Maybe that is an marketplace error with your account. I mean an issue on the marketplace side.

Just try again a bit later again

**Comment by franckadil** [comment]
Related to: https://github.com/RocketChat/Rocket.Chat/issues/16705

**Comment by Aldekein** [comment]
Same problem. I'm signed in https://cloud.rocket.chat/ and signed in our admin panel at https://chat.xxxxxxxxxxxxxxorgname.xxx/admin/marketplace and get the error:

```
Sorry, you aren't authorized to make this request. If you believe this is in error please try again.

Please be sure you are logged in with an account associated with this workspace

                    Request ID: ed8dbecb-ebf2-466f-b048-70417d528137
                
```

**Comment by Aldekein** [comment]
It was fixed after I disconnected from cloud in chat admin, logged out from cloud also, logged back in and did a sync.

**Comment by TheZLabs** [comment]
I will have to try the above and see if it resolves the issue for me as well though I am pretty sure I tried that a few times.
