### ISSUE TITLE
Weechat plugin

### ISSUE THREAD

**Issue by ywecur** [RocketChat/Rocket.Chat#1685]
I just came across [this plugin](https://github.com/rawdigits/wee-slack), which seems to mitigate the need for a XMPP backend. 

It would be awesome if this could be ported to Rocket.chat, then my whole team would be able to switch :smile: 
##

**Comment by sunng87** [comment]
+1 for this.

**Comment by demslam** [comment]
+1 for this

**Comment by fowlslegs** [comment]
+1

**Comment by ywecur** [comment]
Is there a way to connect via an API/Websocket?

**Comment by fractalf** [comment]
+1

**Comment by iooner** [comment]
+1

**Comment by igorline** [comment]
+1

**Comment by mstruebing** [comment]
+1

**Comment by zeysh** [comment]
+1

**Comment by koen92** [comment]
+1

**Comment by makixx** [comment]
+1

**Comment by engelgabriel** [comment]
Can you guys please explain the use case better? Our team does not use Weechat so it is hard for us to make a decision on this feature request.

**Comment by mstruebing** [comment]
@engelgabriel Weechat is an terminal IRC client. For Slack there is an plugin which (I think) communicates via sockets with slack so you can use slack inside weechat with usual weechat functionality.
https://github.com/wee-slack/wee-slack

We want be able to use rocketchat via weechat.

**Comment by tl87** [comment]
+1

**Comment by sampaiodiego** [comment]
the IRC Federation PR was merged already so you can bridge Rocket.Chat to any IRC server.

You can open a thread in the [Rocket.Chat Forums](https://forums.rocket.chat) to discuss any other usage/implementation for this, as we don't to be IRC compatible.

**Comment by spaceone** [comment]
+1

**Comment by truatpasteurdotfr** [comment]
any supported possibility to use a text based client ? non GUI

**Comment by suderio** [comment]
+1

**Comment by wokawoka** [comment]
+1
