### ISSUE TITLE
Push notification on mobile apps with self-hosted Rocket.Chat in local network without internet?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#16855]
Hi!

I have self-hosted Rocket Chat server in our private local network. 
Server does not have Internet access.

Users have desktop apps and mobile app.
Notifications on desktop app working good.
But i don't have push notification on mobile apps.
How push notification on mobile apps with self-hosted Rocket.Chat in local network without internet?

I disable gateway and when i try send test push i get in logs:

```
Push: Send message "@testuser" via query { userId: 'ts36asdsdjkkj87' } 
I20200312-12:01:12.689(0) send to token {   gcm: 'Ll6C29mHSsNmQlDUytMySW5sMPUkJ3s90bKLEpXoqcjJWTMvRWAzzBu1kCkxo2rePhmg4dfz2WYPPvLEXycZdoL9NmQTMvRWAzaU8qRl97Ck8hKNJDhuiTIP_Ll6C29mHSszBu1kCkxo2rkgq' }  
I20200312-12:01:12.689(0) Push: Sent message "@testuser" to 0 ios apps 1 android apps 
I20200312-12:01:12.691(0) Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet...
```

**Comment by ankar84** [comment]
@arpsyapathy you defiantly need internet access for your Rocket.Chat server if you plan to use Push Notifications.
If you are using official marketplace applications - you need access to https://gateway.rocket.chat (443\TCP)
If you are using your own mobile application - you need access to Google and Apple networks.
Apple:
- 17.0.0.0/8 ports 443,5223,2195,2196

Google:
- gcm-http.googleapis.com ports 443,5228
- fcm.googleapis.com ports 443,5228,5229,5230
