### ISSUE TITLE
TypeError: "'name' member of PermissionDescriptor 'microphone' is not a valid value for enumeration PermissionName."

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16854]
version：3.0.3 
firefox：74
TypeError: "'name' member of PermissionDescriptor 'microphone' is not a valid value for enumeration PermissionName."
how to fire: actually，I don't know ,I just changed some user's name and username,and change the 
#general channel to private readonly......

**Comment by gabriellsh** [comment]
Please, provide a way to reproduce this bug and versions for server/browser. Even if it's the latest, for future checks it helps, because versions change over time. Thanks!

Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by 564064202** [comment]
@gabriellsh hello sir,I can give you a account.
https://39.105.66.15:7777
test1
111111

**Comment by gabriellsh** [comment]
I won't be able to test without knowing what you did to get that error. Just complete the information missing so anyone can test it. Thanks again

**Comment by 564064202** [comment]
@gabriellsh  actually，I don't know to how to fire ,I just changed some user's name and username,and change the 
#general channel to private readonly......

**Comment by gabriellsh** [comment]
Did that prevent you from doing something? Or it just logged the message?

**Comment by 564064202** [comment]
I find the another thing. I 
![image](https://user-images.githubusercontent.com/12368358/76530603-ece8fa80-64ae-11ea-8861-c65d98489971.png)

**Comment by 564064202** [comment]
and I met a log : douplicate admin id.......

**Comment by gabriellsh** [comment]
As I can see you're probably with you RC version outdated. Can you send the whole server info?

**Comment by 564064202** [comment]
![image](https://user-images.githubusercontent.com/12368358/76530871-4b15dd80-64af-11ea-8f68-7aa5047553ec.png)
![image](https://user-images.githubusercontent.com/12368358/76530894-57019f80-64af-11ea-8b43-240bf974d74f.png)

**Comment by 564064202** [comment]
![image](https://user-images.githubusercontent.com/12368358/76530978-75679b00-64af-11ea-8366-d32d0994280d.png)

**Comment by 564064202** [comment]
at the same time ,anther bug :https://github.com/RocketChat/Rocket.Chat/issues/16856

**Comment by 564064202** [comment]
@gabriellsh Sir，how I can fix it?

**Comment by 564064202** [comment]
@gabriellsh Sir，how I can fix it?

**Comment by gabriellsh** [comment]
If we can't reproduce it, there's little chance on fixing it. Can you try to make this happen again? Also, when opening issues, please try to add all the information you can, that's why we have the template.

**Comment by IT-Hebk** [comment]
Im having the same error...  Users cant Reply to Broadcast Messages
Im using the latest UCS-Docker: 3.0.2

![rocket-Chat1](https://user-images.githubusercontent.com/62198321/76696762-06489d00-668f-11ea-87ed-dbd2378ff84f.PNG)
![rocket-Chat2](https://user-images.githubusercontent.com/62198321/76696765-08126080-668f-11ea-9a35-58fc0f814e3e.PNG)

**Comment by cmouse** [comment]
Hi! As a Rocket.Chat user I am experiencing this as well using Firefox 80.0.1 on Windows 10 64-bit.

When I open Rocket.Chat using my Browser, the console gets logged with

```
TypeError: 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    t https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
    i https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _withTemplateInstanceFunc https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    i https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    constructView https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    n https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    nonreactive https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:138
    _fireCallbacks https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _withCurrentView https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _fireCallbacks https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _createView https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _materializeView https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    t https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _materializeDOM https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _materializeDOM https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    _materializeView https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    nonreactive https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:138
    _materializeView https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    render https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
    getDomOfRoom https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
    currentTracker https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
    _compute https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:138
    _recompute https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:138
    _runFlush https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:138
    a https://chat.dom.int/2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:1
```

and after some while, it just floods this all the time. There is nothing particular action required, just need to use it.

**Comment by hoeck-cs** [comment]
Same here, hosted rocketchat (on rocket.chat), using Firefox 80.0.1 (64-bit) on Linux.

Its a warning that is logged with every sent message. Aside from that warning  - everything else seems to work.

Though the chat feels very sluggish, read notifications and sending messages takes some time >10s. But I doubt that this is caused by that logged warning alone.

Looking at the stacktrace, its [this](https://github.com/RocketChat/Rocket.Chat/blob/d247dbac3d8576d49d81392a2a2ea0231aecde1a/app/ui-message/client/messageBox/messageBoxAudioMessage.js#L32) warning that is getting logged.

```
TypeError: 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    t https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:886
    i https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _withTemplateInstanceFunc https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    i https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    constructView https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    n https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    nonreactive https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:606
    _fireCallbacks https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _withCurrentView https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _fireCallbacks https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _createView https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _materializeView https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    t https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _materializeDOM https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _materializeDOM https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    t https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    nonreactive https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:606
    t https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    n https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _withTemplateInstanceFunc https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    n https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _withCurrentView https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    n https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:677
    _compute https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:606
    _recompute https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:606
    _runFlush https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:606
    a https://heavygoods.rocket.chat/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:1
e49465247681928f62c29836b6a5fe7e1714f082.js:886:799913
```

The issue is that firefox does not support the `microphone` permission in [`navigator.permissions.query`](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query).

One solution may be to check for a `TypeError` explicitly and use that as a "permission denied" and then don't try to check for that permission again.

Do you want a PR for this?

**Comment by thw0rted** [comment]
Trackback to #13881 which had a PR that was supposed to fix it.  Since I'm getting a stackdump on the console, I assume  the call to the permissions API is not wrapped in a try/catch, which seems like the correct solution.

**Comment by lent85** [comment]
Same thing happen, but additional issue is I cannot find more than 10 users when Add User to channel. 
The error in console print continuously.
