### ISSUE TITLE
Broadcast Channel can't reply,I can supply a remote account

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16856]
version：3.0.3
Firefox: 74
Broadcast Channel can't reply
I can supply a account
how to fire: actually，I don't know ,I just changed some user's name and username,and change the
#general channel to private readonly......

![image](https://user-images.githubusercontent.com/12368358/76524713-7b587e80-64a5-11ea-836a-0283eda87efd.png)

**Comment by 564064202** [comment]
https://39.105.66.15:7777
test1
111111

**Comment by IT-Hebk** [comment]
Im having the same error
![Snag_7fc4204](https://user-images.githubusercontent.com/62198321/76696964-56c0fa00-6691-11ea-8e53-6a7b74fe5795.png)
...  Users cant Reply to Broadcast Messages
Im using the latest UCS-Docker: 3.0.2

![rocket-Chat2](https://user-images.githubusercontent.com/62198321/76696968-5f193500-6691-11ea-8567-9fdb431470bc.PNG)
![rocket-Chat1](https://user-images.githubusercontent.com/62198321/76696969-604a6200-6691-11ea-9d07-76e8630531eb.PNG)

**Comment by tntho** [comment]
Tested on https://open.rocket.chat/  at 10:25 27.4.2020, still can not reply a message. Here is the gif I recorded
![can-not-reply-broadcast-message](https://user-images.githubusercontent.com/6253075/77718382-5facb680-7015-11ea-86aa-11a4dc302e41.gif)

**Comment by ndroo** [comment]
We just upgraded from 2.4.2 > 2.4.11 > 3.0.7 and now have this issue too.

**Comment by yoerin** [comment]
Same problem here on version 3.2.2
