### ISSUE TITLE
Can not start Rocket.Chat server 3.0.3 Centos 7

### ISSUE THREAD

**Issue by nerotov** [RocketChat/Rocket.Chat#16850]
### Description:

Rocket version 3.0.3 can not start on Centos 7

### Steps to reproduce:

https://rocket.chat/docs/installation/updating/

### Expected behavior:

Rocket.Chat server started.

### Actual behavior:
`
node main.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'reify/lib/runtime'
Require stack:
- /opt/Rocket.Chat/programs/server/runtime.js
- /opt/Rocket.Chat/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/runtime.js:10:3)
    at Object.<anonymous> (/opt/Rocket.Chat/programs/server/runtime.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Rocket.Chat/programs/server/runtime.js',
    '/opt/Rocket.Chat/main.js'
  ]
}
`
### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.3
- Operating System: CentOS Linux release 7.7.1908 (Core)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
`nvm ls
        v8.17.0
       v12.13.1
->     v12.14.0
       v13.10.1
         system
default -> 12.14.0 (-> v12.14.0)
node -> 12.14.0 (-> v12.14.0)
stable -> 12.14.0 (-> v12.14.0)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0
lts/dubnium -> v10.19.0 (-> N/A)
lts/erbium -> v12.16.1 (-> N/A)`
- MongoDB Version: 4.0

### Relevant logs:

{
  "format": "site-archive-pre1",
  "builtBy": "Meteor METEOR@1.9",
  "programs": [
    {
      "name": "web.browser",
      "arch": "web.browser",
      "path": "programs/web.browser/program.json"
    },
    {
      "name": "web.browser.legacy",
      "arch": "web.browser.legacy",
      "path": "programs/web.browser.legacy/program.json"
    },
    {
      "name": "server",
      "arch": "os",
      "path": "programs/server/boot.js"
    }
  ],
  "meteorRelease": "METEOR@1.9",
  "nodeVersion": "12.14.0",
  "npmVersion": "6.13.4",
  "gitCommitHash": "ef1e0b3613772175717968fed444cd0db92ff72c"
}

**Comment by nerotov** [comment]
Found issue but now:

 Loaded: loaded (/usr/lib/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-03-12 03:59:11 +03; 4min 5s ago
  Process: 989 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 989 (code=exited, status=1/FAILURE)

Mar 12 03:59:09 mv-service-rocket.strikerz.corp systemd[1]: Started The Rocket.Chat server.
**Mar 12 03:59:11 mv-service-rocket.strikerz.corp rocketchat[989]: Meteor requires Node v12.0.0 or later.**


`nvm ls
        v8.17.0
        v10.0.0
        v12.0.0
       v12.13.1
       v12.14.0
->     v13.10.1
         system
default -> 13.10.1 (-> v13.10.1)
node -> 13.10.1 (-> v13.10.1)
stable -> 13.10.1 (-> v13.10.1)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0
lts/dubnium -> v10.19.0 (-> N/A)
lts/erbium -> v12.16.1 (-> N/A)`

**Comment by soeyi** [comment]
`mv-service-rocket.strikerz.corp rocketchat[989]: Meteor requires Node v12.0.0 or later.`

try to update your Nodejs version

**Comment by gabriellsh** [comment]
You can try and go to [our community Support Channel](https://open.rocket.chat/channel/support) to get some help.
