### ISSUE TITLE
There are so many bugs when I installed version 3.0.3,even if I reinstall it and do nothing.

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16865]
### Steps to reproduce:

1. on ubuntu 18.04,use manual install(https://github.com/RocketChat/docs/blob/master/installation/manual-installation/ubuntu/README.md )
2.when I have finished installation,on my admin account will see
![image](https://user-images.githubusercontent.com/12368358/76582603-b5f80080-6511-11ea-8949-253c65df87c3.png)

3.when I  used my admin account to create a broadcast room,and sent a message  to the room,
my another account can recevice the message in the room,but can't reply,with the error below:
![image](https://user-images.githubusercontent.com/12368358/76582761-27d04a00-6512-11ea-929c-dff68a7bdc79.png)

2. 
3. 

### Server Setup Information:

 Rocket.Chat Version: 3.0.3                      | 
I20200313-09:51:47.888(8) ➔ |       NodeJS Version: 12.16.1 - x64              | 
I20200313-09:51:47.888(8) ➔ |      MongoDB Version: 4.0.16                     | 
I20200313-09:51:47.888(8) ➔ |       MongoDB Engine: mmapv1                     | 
I20200313-09:51:47.888(8) ➔ |             Platform: linux                      | 
I20200313-09:51:47.889(8) ➔ |         Process Port: 3000                       | 
I20200313-09:51:47.889(8) ➔ |             Site URL: https://39.105.66.15:7777  | 
I20200313-09:51:47.889(8) ➔ |     ReplicaSet OpLog: Enabled                    | 
I20200313-09:51:47.889(8) ➔ |          Commit Hash: ef1e0b3613                 | 
I20200313-09:51:47.890(8) ➔ |        Commit Branch: HEAD                       | 
I20200313-09:51:47.890(8) ➔ |                                   

### Client Setup Information

- Desktop App or Browser Version: firefox 74 and chrome 73
- Operating System: win10

### Relevant logs:

in firefox 
![image](https://user-images.githubusercontent.com/12368358/76582979-e2604c80-6512-11ea-91ee-0c7342c66ea9.png)

**Comment by rodrigok** [comment]
@ggazzo can you check this?
