### ISSUE TITLE
Failed start app in rocketchat/rocket.chat:latest docker container

### ISSUE THREAD

**Issue by Anixceed** [RocketChat/Rocket.Chat#16866]
I've tried to install rocket.chat according to  [https://rocket.chat/docs/installation/docker-containers/docker-compose/](url)
**The rocketchat/rocket.chat:latest container can run,but can't start to listen 3000 port.**

**The node main.js log** 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 174","time":{"$date":1584071736477},"level":"info"}
Loaded the Apps Framework and loaded a total of 0 Apps!
Using GridFS for custom sounds storage
Updating process.env.MAIL_URL
Using GridFS for custom emoji storage

**When I kill "node main.js" process,and run "node main.js" manually.The app get started correctlly!
I've installed in ubuntu16 and ubuntu18.The same problem.**

How could I resove this?

**Comment by Anixceed** [comment]
Got it!

**Comment by SaurabhSSJ9000** [comment]
Can you help with this? I am still unable to connect rocketchat to mongodb. I have edited the ipbind in the mongodb of host ( digital ocean droplet in which Ubuntu 20.0 is setup ) but I am still getting this error in the portainer (using portainer to manage the docker containers) log.

`Setting default file store to GridFS

LocalStore: store created at 

LocalStore: store created at 

LocalStore: store created at 

bash: line 1:     9 Killed                  node main.js

Tried 1 times. Waiting 5 secs...
`
