### ISSUE TITLE
Loading animation on Open Rocket.Chat server

### ISSUE THREAD

**Issue by DinDev3** [RocketChat/Rocket.Chat#16860]
I feel like it would look more appealing and attractive if the loading of 3 dots of the Open Rocket.Chat server on the browser happens **inside the rocket chat logo** and once the loading is complete, to zoom it out and fade in all the content of the webpage. Because of the use of React components, the components can be faded in separately. as if they are falling into place.
This will give the user a feeling that he/ she is going into the rocket (diving in). The user experience will be more appealing.

_the following UI prototypes may give u an idea of the concept_

### Loading stage
![loading](https://user-images.githubusercontent.com/47103883/76532387-8c50c200-649c-11ea-8f66-54712ce8e349.png)
### Loading completed stage
![loading_complete](https://user-images.githubusercontent.com/47103883/76532392-8e1a8580-649c-11ea-8b68-6590507f7717.png)
### Opening server stage
![diving_in](https://user-images.githubusercontent.com/47103883/76532399-8fe44900-649c-11ea-9c69-0dd717712029.png)

**Comment by gabriellsh** [comment]
Prototypes? So you already coded this? Please open a Pull request so we can take a look.

**Comment by DinDev3** [comment]
No. Sorry for the misunderstanding. I drew the screens on Figma to convey the message with a better understanding.
This is my 3rd issue/ contribution to Open Source. Still trying to get the hang of everything.

I'll try to get the code done as well.

**Comment by gabriellsh** [comment]
Relax! I just thought you had made a prototype 😁. Thanks for your contribution, no need to do the code if you don't want to.
