### ISSUE TITLE
Encrypted messages not being delivered nor showed in a encrypted channel

### ISSUE THREAD

**Issue by nunoguerreiro** [RocketChat/Rocket.Chat#16888]
any time that try to send/or read a message in an encrypted channel nothing happens....
or a notification error appears...

![error-Untitled](https://user-images.githubusercontent.com/1771943/76713224-9393fc00-6738-11ea-8732-8d2bc352c005.png)

**Comment by ankar84** [comment]
I remember when I tested encrypted chats, when you set chat as encrypted, you must refresh client (CTRL+R of F5) before that actually works.

**Comment by nunoguerreiro** [comment]
> I remember when I tested encrypted chats, when you set chat as encrypted, you must refresh client (CTRL+R of F5) before that actually works.

But it's a confusing thing since if you have 2 different clients the keys are not the same (each device has it's one key)... and even so, is not working...

If I send 1 encrypted message from 1 device, the other cannot see it and every time he needs to reset is how key (that will imply a regeneration of the key in the 2nd device)
