### ISSUE TITLE
Run project on gitpod

### ISSUE THREAD

**Issue by SaiAshish9** [RocketChat/Rocket.Chat#16886]
![image](https://user-images.githubusercontent.com/43849911/76699718-3b2c1280-66d6-11ea-94fc-b7bd26ca9d37.png)

Can anyone provide me the command to run this project via gitpod?

**Comment by nisarhassan12** [comment]
Please add the following files to your fork and it'll hopefully work https://github.com/nisarhassan12/Rocket.Chat/tree/Rodriq/gitpod-setup
