### ISSUE TITLE
Hide system message pin/unpin message

### ISSUE THREAD

**Issue by etopit** [RocketChat/Rocket.Chat#16885]
Hello,
if unpin and remove the message, the System Messages is always visible

I did not find the option to hide this information. 

And so if there is an error in the message pin, this message always visible (system information) with this error.

**Comment by etopit** [comment]
it's not possible ?

**Comment by Kyogre** [comment]
@dudanogueira hi! Can you reopen this as and improvement ticket? It is very annoying that we still have not "hide system message feature" for messages "**some_user Pinned a message**" from room settings:

![image_2022-03-28_17-42-13](https://user-images.githubusercontent.com/2260980/161376202-c62506c9-f486-40f8-81c4-a0810e5aab0d.png)

**Comment by mikcsek** [comment]
This feature would be great.

**Comment by fahrnbergerg** [comment]
This thread is old but the desired features is still missing.

**Comment by darkufo** [comment]
Would love to have this. Seems strange that we can hide 20+ other messages but not the pinned ones

**Comment by suhanoves** [comment]
up

**Comment by tetesh** [comment]
up

**Comment by milton-rucks** [comment]
Hi all,

Thanks for the feedback and for the suggestion.

The concept of pinning a message is to give visibility to all in the room. Users would not be aware of newly pinned messages if the system message is hidden.

Unpinning removes the item from the Pinned messages contextual bar, but like any other system message, it's not possible to remove it from the main room.

We are introducing in 6.6 a confirmation modal for pinning messages, this way we eliminate pinning messages by mistake (that happens with some frequency), which helps to mitigate the problem.

https://github.com/RocketChat/Rocket.Chat/pull/31348
