### ISSUE TITLE
Incomplete support for running in a subdirectory

### ISSUE THREAD

**Issue by emengd** [RocketChat/Rocket.Chat#16880]
Hello,

I followed the instructions [here](https://rocket.chat/docs/installation/manual-installation/debian/) to install rocket.chat on Debian, and then [here](https://rocket.chat/docs/installation/manual-installation/running-in-a-sub-folder/) to make the service available under `mything.com/chat/` through Apache, even though it's actually running on `localhost:3000`. So I set ROOT_URL to `https://mything.com/chat/` as instructed. I run version 3.0.3.

For the most part it works fine, but I noticed two glitches related to being in a subdirectory.

1. The generated invite links for private groups point to `mything.com/chat/chat/invite/<code>` when the link that actually works is `mything.com/chat/invite/<code>`.

2. When clicking the Rocket.Chat logo in the bottom left, you are taken to `mything.com/home`, even though what would work is `mything.com/chat/home`(on my server `mything.com/home` is a 403).

Am I correct that these are bugs? Or did I set up something wrong?

**Comment by nunoguerreiro** [comment]
Have the same problem. Logo and invite are incorrect urls. I'm using NGINX also.

**Comment by PeGaSuS-Coder** [comment]
Can you provide the value in `Administration > Setup Wizard > Organization Info > Website`?

**Comment by emengd** [comment]
`Administration > Setup Wizard > Organization Info > Website` is a completely unrelated site.

`Admnistration > General > Site Name` is `mything.com/chat/`.

The Apache2 config looks like this (it so happens that I'm not running anything under the root url for now).
```
ServerName mything.com
DocumentRoot /var/www

<Directory /var/www/>
    Order deny,allow
    Deny from all
    AllowOverride all
</Directory>

<Location /chat>
    Order allow,deny
    Allow from all

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /var/www/(.*)           ws://localhost:23456/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /var/www/(.*)           http://localhost:23456/$1 [P,L]

    ProxyPassReverse http://localhost:23456
</Location>
```

**Comment by PeGaSuS-Coder** [comment]
Seems I'm able to reproduce the issue. Using `http://my.domain.tld:3000/` seems to work as expected. :man_shrugging:

**Comment by nunoguerreiro** [comment]
the same for NGINX (according the manual):

# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}

# HTTPS Server
server {
    listen 443 ssl;
    server_name _;
    ssl on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE
    # Self signed certs generated by the ssl-cert package
    include snippets/snakeoil.conf;

    location /chat/ {
        error_log    /var/log/nginx/rocketchat.error.log warn;
        access_log   /var/log/nginx/rocketchat.access_log;

        proxy_pass http://backend/chat/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}

and the rocketchat service:

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=http://localhost:3000/chat/ PORT=3000
[Install]
WantedBy=multi-user.target

works well, but the invites and the rocketchat logos are point to an url non-existent.

**Comment by serviceman** [comment]
Not really a fix, but you can hide the invite button with this css at Layout ->Custom CSS. This is what I had to do for my install in a sub directory.

.js-invite,[data-id="createinvitelink"]{
display:none; 
}

Also, you can manually change the url to include your sub directory url at Layout->Content->Side Navigation Footer. I would give you the exact html to use but I have heavily edited mine for use for other things besides just a logo/link.

**Comment by nunoguerreiro** [comment]
thanks ... found it - I modified both and the side navigation footer...

<a href="/url/home"><img src="assets/logo.png" alt="Home" /></a>
