### ISSUE TITLE
Invitation Link displays Error Page with SAML enabled and Registration disabled

### ISSUE THREAD

**Issue by HartwigFlamm** [RocketChat/Rocket.Chat#16890]
### Description:

We have enabled SAML to validate Users and do not maintain local Users. A new User is created as soon as new Persons log into the System Web Page and are positively validated by SAML.
The Registration Page is disabled because of this.
If a User wants to invite others to a private group and sends out invite links Errors happen:
- If the invited user has a valid User and is logged in the Web Client, the User is added to the Group but gets an error message.
- If the User has no valid User or is not logged into the Web Client, the User gets an Error and is not added to the Group.

The Error reads in both Cases reads: "Invalid or expired token"

### Steps to reproduce:

1. Select a "Private Group"
2. Click on '....' in the top right Corner
3. Select "Invite Users"
4. Copy the Invite Link and sent it to eMail Addresses you want to participate in the group

### Expected behavior:

- When a user is logged into the Web Client, she/he should be added to the Group and the Group opened in the Browser. 
- Otherwise, the Login Page should be displayed. After Login the user should be added to the Group and the Group should open in the Browser.

### Actual behavior:

In any case, an error Page is displayed stating: "Invalid or expired token"

![image](https://user-images.githubusercontent.com/51446457/76754233-0d040c80-6782-11ea-9159-5dee643c7c28.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.0.3.
- Operating System: Debian 10 Buster 4.19.0-8-amd64
- Deployment Method: tar
- Number of Running Instances: 2 Dev / 8 Production
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.2.3. (Dev) / 4.0.16 (Production)

### Client Setup Information

- Desktop App or Browser Version: 2.17.7 (All Versions)
- Operating System: Debian 10 Buster 4.19.0-8-amd64 (and all others)

### Additional context

It makes no difference when a new link is created with Expiration: Never and Max number of Users: No Limit or a Combination thereof. 

This Problem seems to appear across all OS and Versions in use here.

### Relevant logs:

Link : https://chat-dev.it.tuwien.ac.at/invite/567CdE

Generate Link : 

I20200313-15:14:28.905(1) Meteor ➔ publish null -> userId: null, arguments: [] 
I20200313-15:14:28.910(1) Meteor ➔ method public-settings/get -> userId: null, arguments: [{}] 
I20200313-15:14:59.498(1) API ➔ debug POST: /api/v1/findOrCreateInvite 
I20200313-15:14:59.505(1) API ➔ debug Success {   statusCode: 200,   body: {     _id: '567CdE',     days: 1,     maxUses: 0,     rid: 'BZwLiYcZLPAirW4R6',     userId: 'FmQnAeGZpNDbG5nrk',     createdAt: 2020-03-13T14:12:14.683Z,     expires: 2020-03-14T14:12:14.683Z,     uses: 0,     _updatedAt: 2020-03-13T14:12:14.683Z,     url: 'https://chat-dev.it.tuwien.ac.at/invite/567CdE',     success: true   } } 
I20200313-15:15:08.065(1) Meteor ➔ method instances/get -> userId: FmQnAeGZpNDbG5nrk, arguments: [] 
I20200313-15:15:10.246(1) API ➔ debug GET: /api/v1/stdout.queue 
I20200313-15:15:10.249(1) API ➔ debug Success {   statusCode: 200,   body: {     queue: [       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       ... 900 more items     ],     success: true   } } 

Call Link without Login

I20200313-15:16:13.511(1) API ➔ debug POST: /api/v1/validateInviteToken 
I20200313-15:16:13.515(1) API ➔ debug Success { statusCode: 200, body: { valid: true, success: true } } 
I20200313-15:16:14.538(1) Meteor ➔ publish null -> userId: null, arguments: [] 
I20200313-15:16:14.542(1) Meteor ➔ method checkRegistrationSecretURL -> userId: null, arguments: ["567CdE"] 
I20200313-15:16:14.572(1) Meteor ➔ method public-settings/get -> userId: null, arguments: [{}] 

Login

I20200313-15:16:51.898(1) Meteor ➔ publish null -> userId: null, arguments: [] 
I20200313-15:16:51.903(1) RESULT :{"profile":{"inResponseToId":"id-aQdxCuMiBfJRgYqhP","issuer":"https://idp.zid.tuwien.ac.at/saml2","nameID":"toni.tester","nameIDFormat":"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress","sessionIndex":"_2fca79871eb5533548b6874ff444b19543330efc9c","username":"toni.tester","mail":"toni.tester@tuwien.ac.at","displayName":"Toni Tester","email":"toni.tester@tuwien.ac.at","urn:oid:0-9-2342-19200300-100-1-3":"toni.tester@tuwien.ac.at","urn:oid:2-16-840-1-113730-3-1-241":"Toni Tester"}} 
I20200313-15:16:51.915(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:51.906Z"},"type":"updated"}}] 
I20200313-15:16:51.924(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:51.911Z","services.saml":{"provider":"chat-dev","idp":"https://idp.zid.tuwien.ac.at/saml2","idpSession":"_2fca79871eb5533548b6874ff444b19543330efc9c","nameID":"toni.tester"}},"type":"updated"}}] 
I20200313-15:16:51.936(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:51.914Z"},"type":"updated"}}] 
I20200313-15:16:51.942(1) Meteor ➔ publish null -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:51.950(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:51.921Z","lastLogin":"2020-03-13T14:16:51.921Z"},"type":"updated"}}] 
I20200313-15:16:51.959(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:51.925Z","services.resume.loginTokens":[{"when":"2020-03-13T14:16:51.925Z","hashedToken":"HWDOBfzrGPFFBQ8zY77JE93A0x65Q4r4rU4Qy2J67iQ="}]},"type":"updated"}}] 
I20200313-15:16:51.963(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-logged","user-status",{"0":["gEAEof722NJsRkBjq","toni.tester",1,""]}] 
I20200313-15:16:51.965(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:51.954Z","status":"online","statusConnection":"online"},"type":"updated"}}] 
I20200313-15:16:51.977(1) Meteor ➔ publish stream-importers -> userId: gEAEof722NJsRkBjq, arguments: ["progress",{"useCollection":false,"args":[]}] 
I20200313-15:16:51.980(1) Meteor ➔ method autoTranslate.getSupportedLanguages -> userId: gEAEof722NJsRkBjq, arguments: ["en"] 
I20200313-15:16:51.981(1) API ➔ debug GET: /api/v1/emoji-custom.list 
I20200313-15:16:51.985(1) Meteor ➔ method autoTranslate.getProviderUiMetadata -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:51.987(1) API ➔ debug Success {   statusCode: 200,   body: { emojis: { update: [], remove: [] }, success: true } } 
I20200313-15:16:51.992(1) Meteor ➔ method listCustomSounds -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:51.995(1) Meteor ➔ method apps/is-enabled -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:51.998(1) Meteor ➔ method getUserRoles -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.002(1) Meteor ➔ method e2e.fetchMyKeys -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.006(1) Meteor ➔ method listCustomUserStatus -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.009(1) Meteor ➔ method rooms/get -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.012(1) API ➔ debug GET: /api/apps/languages 
I20200313-15:16:52.014(1) API ➔ debug Success { statusCode: 200, body: { apps: [], success: true } } 
I20200313-15:16:52.016(1) Meteor ➔ method subscriptions/get -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.066(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/added",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.068(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/removed",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.069(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/updated",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.070(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/statusUpdate",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.071(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/settingUpdated",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.072(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/added",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.072(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/disabled",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.073(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/updated",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.079(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/removed",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.203(1) Meteor ➔ method public-settings/get -> userId: gEAEof722NJsRkBjq, arguments: [{}] 
I20200313-15:16:52.412(1) Meteor ➔ publish null -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.421(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:52.408Z","lastLogin":"2020-03-13T14:16:52.407Z"},"type":"updated"}}] 
I20200313-15:16:52.436(1) Meteor ➔ publish stream-importers -> userId: gEAEof722NJsRkBjq, arguments: ["progress",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.437(1) Meteor ➔ method autoTranslate.getSupportedLanguages -> userId: gEAEof722NJsRkBjq, arguments: ["en"] 
I20200313-15:16:52.439(1) Meteor ➔ method autoTranslate.getProviderUiMetadata -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.441(1) Meteor ➔ method listCustomSounds -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.444(1) API ➔ debug GET: /api/v1/emoji-custom.list 
I20200313-15:16:52.446(1) API ➔ debug Success {   statusCode: 200,   body: { emojis: { update: [], remove: [] }, success: true } } 
I20200313-15:16:52.449(1) Meteor ➔ method apps/is-enabled -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.451(1) Meteor ➔ method getUserRoles -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.455(1) Meteor ➔ method e2e.fetchMyKeys -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.457(1) Meteor ➔ method listCustomUserStatus -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.461(1) Meteor ➔ method rooms/get -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.464(1) Meteor ➔ method subscriptions/get -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:16:52.472(1) API ➔ debug GET: /api/apps/languages 
I20200313-15:16:52.472(1) API ➔ debug Success { statusCode: 200, body: { apps: [], success: true } } 
I20200313-15:16:52.509(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/added",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.510(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/removed",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.511(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/updated",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.512(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/statusUpdate",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.513(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/settingUpdated",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.520(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/added",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.525(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/disabled",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.526(1) API ➔ debug POST: /api/v1/useInviteToken 
I20200313-15:16:52.528(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/updated",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.530(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/removed",{"useCollection":false,"args":[]}] 
I20200313-15:16:52.539(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:16:52.531Z","inviteToken":"567CdE"},"type":"updated"}}] 
I20200313-15:16:52.540(1) API ➔ debug Success {   statusCode: 200,   body: {     room: {       rid: 'BZwLiYcZLPAirW4R6',       prid: undefined,       fname: 'fl_test_1',       name: 'fl_test_1',       t: 'p'     },     success: true   } } 
I20200313-15:16:52.553(1) Meteor ➔ method loadHistory -> userId: gEAEof722NJsRkBjq, arguments: ["BZwLiYcZLPAirW4R6",{},50,{}] 
I20200313-15:16:52.555(1) Meteor ➔ method canAccessRoom -> userId: gEAEof722NJsRkBjq, arguments: ["BZwLiYcZLPAirW4R6","gEAEof722NJsRkBjq"] 
I20200313-15:16:52.565(1) Meteor ➔ method canAccessRoom -> userId: gEAEof722NJsRkBjq, arguments: ["BZwLiYcZLPAirW4R6","gEAEof722NJsRkBjq",null] 
I20200313-15:16:52.572(1) Meteor ➔ method getRoomRoles -> userId: gEAEof722NJsRkBjq, arguments: ["BZwLiYcZLPAirW4R6"] 
I20200313-15:16:53.213(1) API ➔ debug GET: /api/v1/users.presence?ids=e9rarkyxg2Lp9RdsW 
I20200313-15:16:53.216(1) API ➔ debug Success { statusCode: 200, body: { users: [], full: false, success: true } } 

Call Link while Logged in

I20200313-15:18:45.029(1) API ➔ debug GET: /api/v1/commands.list 
I20200313-15:18:45.033(1) API ➔ debug Success {   statusCode: 200,   body: {     commands: [       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object]     ],     offset: 0,     count: 24,     total: 24,     success: true   } } 
I20200313-15:18:45.255(1) API ➔ debug GET: /api/v1/emoji-custom.list 
I20200313-15:18:45.257(1) API ➔ debug Success {   statusCode: 200,   body: { emojis: { update: [], remove: [] }, success: true } } 
I20200313-15:18:45.278(1) API ➔ debug POST: /api/v1/validateInviteToken 
I20200313-15:18:45.281(1) API ➔ debug Success { statusCode: 200, body: { valid: true, success: true } } 
I20200313-15:18:45.759(1) Meteor ➔ publish null -> userId: null, arguments: [] 
I20200313-15:18:45.767(1) Meteor ➔ publish null -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:45.775(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:18:45.764Z","lastLogin":"2020-03-13T14:18:45.764Z"},"type":"updated"}}] 
I20200313-15:18:45.779(1) Meteor ➔ publish stream-importers -> userId: gEAEof722NJsRkBjq, arguments: ["progress",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.191(1) Meteor ➔ method autoTranslate.getSupportedLanguages -> userId: gEAEof722NJsRkBjq, arguments: ["en"] 
I20200313-15:18:46.194(1) Meteor ➔ method autoTranslate.getProviderUiMetadata -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:46.197(1) Meteor ➔ method listCustomSounds -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:46.198(1) API ➔ debug GET: /api/v1/me 
I20200313-15:18:46.201(1) Meteor ➔ method getUserRoles -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:46.204(1) API ➔ debug Success {   statusCode: 200,   body: {     _id: 'gEAEof722NJsRkBjq',     name: 'Toni Tester',     active: true,     emails: [ [Object] ],     username: 'toni.tester',     status: 'online',     _updatedAt: 2020-03-13T14:18:45.764Z,     roles: [ 'user' ],     services: { totp: [Object] },     statusConnection: 'online',     utcOffset: 1,     settings: { preferences: [Object] },     language: '',     statusText: '',     requirePasswordChange: false,     email: 'toni.tester@tuwien.ac.at',     avatarUrl: 'https://chat-dev.it.tuwien.ac.at/avatar/toni.tester',     success: true   } } 
I20200313-15:18:46.208(1) Meteor ➔ method apps/is-enabled -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:46.209(1) Meteor ➔ method listCustomUserStatus -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:46.211(1) Meteor ➔ method e2e.fetchMyKeys -> userId: gEAEof722NJsRkBjq, arguments: [] 
I20200313-15:18:46.260(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/added",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.262(1) API ➔ debug POST: /api/v1/useInviteToken 
I20200313-15:18:46.264(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/removed",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.266(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/updated",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.268(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/statusUpdate",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.270(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["app/settingUpdated",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.321(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/added",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.324(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/disabled",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.326(1) Meteor ➔ method stream -> userId: null, arguments: ["notify-user","gEAEof722NJsRkBjq/userData",{"0":{"diff":{"_updatedAt":"2020-03-13T14:18:46.269Z"},"type":"updated"}}] 
I20200313-15:18:46.329(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/updated",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.333(1) Meteor ➔ publish stream-apps -> userId: gEAEof722NJsRkBjq, arguments: ["command/removed",{"useCollection":false,"args":[]}] 
I20200313-15:18:46.339(1) API ➔ debug Success {   statusCode: 200,   body: {     room: {       rid: 'BZwLiYcZLPAirW4R6',       prid: undefined,       fname: 'fl_test_1',       name: 'fl_test_1',       t: 'p'     },     success: true   } } 
I20200313-15:18:46.341(1) Integrations ➔ Outgoing WebHook.debug Execute Trigger: roomJoined 
I20200313-15:18:46.342(1) Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: roomJoined {   event: 'roomJoined',   user: {     _id: 'gEAEof722NJsRkBjq',     createdAt: 2018-10-18T18:27:53.598Z,     name: 'Toni Tester',     active: true,     emails: [ [Object] ],     username: 'toni.tester',     type: 'user',     status: 'online',     _updatedAt: 2020-03-13T14:18:45.764Z,     roles: [ 'user' ],     services: { resume: [Object], totp: [Object], saml: [Object] },     lastLogin: 2020-03-13T14:18:45.764Z,     statusConnection: 'online',     utcOffset: 1,     e2e: {       public_key: '{"alg":"RSA-OAEP-256","e":"AQAB","ext":true,"key_ops":["encrypt"],"kty":"RSA","n":"jyLEgLbcxg7K6QB7IgaXliRBb86sxAJxFNDmiC-yBzra5lsY7Q6wHjaFSDSNoE7lKn8IexsyvMBastDMTR0IDw8QjB5xgVe8J5vR-H3VczpDjKwRjXwXSvKHpA81szDF6p8NpgYvXrggUPe4zXIqtgp8bceOgSYmEzNJeusyOe5EeX2S7gJa_qOFWtQph8lAWifbuIsBqtHgFFuC90mwegScpHbbMfe_CFVWmOrYBb9GEexed8YYvkV1wt0cXcPMNunDJ1IRSnE9mG9TBjw9dpJimG8wkeO2g_1DXtDOztdnYDL8JGh-4RXSzf-2-bSD6IM2oegtHjpS7x_AKm78-Q"}',       private_key: '{"$binary":"FrHnUD9Btf5nbT1A8m00yiy3a5+zp6AIFuVJc2HvfsqcdepLiUfQgE5sv5yv80wlCLEPDCk7q4gEUEfG2eQzBMf1bicXceQtLAIQzhOi57CaonBwRukfpyHCeVlW1YREqGPt9IYmUAkT8GElN7zXfGhPr6dgIRi+F9m8PaWSsp75/c3U5YjFyoqfWNGJaSSFiW2FOMlNo19/VTjmEd7zxGdVGJ5ZR7KT8VFQrxXSdesYPch/nWM3sGxWzhEfvr5i5L7ZksOP+giOrDw0G0Qs45DX3kwmGoxPEbSwRbHhvT+2aDID/XaTjhs2pJYWVoeZkJ1mi1e9NKdNSwEq+GgVX/2PeSIebYHbf9OmmvMbAptwAtgvjepjrGcOGpvhpzKK0pzbY+h8ML6SjCqPqA1dz5/+IQf6yMhAmU3qT/j27zrn6q5It5JEbFgbWGHERJuxBXKbDaMAWfskIhwtU4uNk0RCRUQBsQ8tVbSXU0nM8BremCOQTurOvvvj71DGCtNLcBF88PPdbulfLS7hjRvmOFmAbJrC4wDoTqJ2dKd+V2v5PZRcldCjLRrzZqDKBqP1fkmmpZLFTYhjzWXmmFABCqgK9PLA4oPWeBKrOw6xPuUisx7Teuz1C9VftGxpvW35txMClS1eTPGgFmekM8vdlAmJCTZkoRYylEWqOp8L5MAQ2kiZATTsrda/gaHoQPkr8FfPP3QPkRopPLU2Zfpti1y+lReqkmA7GQK/htajfI35TqRjzF7suEdcCIIQ/P4ThSZq7s7bUwaBh6lcNNKsw6hMr0pWRHH5L5LsmFwjCAMqCkDxrcaauPlDKLqtKTAsP9wfHjUdDaIxz0AwS2/pfGeOjrS2xlH35uHTAYzt15cbbRcozv7yI73mVaVodCNv5mpnxPPnAfmta5xs9dNsnCuAUSOK9Dzc3mMSzYC+smSQY9RUezaPwxpYVcMeVp3l9LfxvBOFv9nLjeG41VB7pbwoGYarbc9ZYzlVgnaNv3ajVG2tf8SEON3iGUrjb4TKecEnN37gl4Xqe8hs9asKeeqvjklod5KPTxzHr+6ZmdhuFZMY9ZHm+twlHRoX0JGv1adXM1lCjMLf6Hm8ve33RDz9rOjgQhc5vxHmT5ga3RQGiQVXrpN0uZfSRsqeHgpLhQjVcE3R4I4Jp2HY4LvTu2PeJJR0vdA+LZ2FRanxZ2gH0QH6RIozXYcl1txRSjN+jlhpDaJNWv6lBxsNH300J4I5GLpDtUO/WrrCksyEnxd2U/V2he8Xyb4fwxPD3wxXmcnrd7PddYuoCYdRrH/dxRhaGoiFqPD3cPcdw6cqQu3aYFZYWcxZJDA7jnWunTrobwxvUyRw28PbSCmsDSz4po1NTr2KspOJaBfwQ4sKchsRmbg0PU3Dp42G9Yxvup8AKsaSSP7iuDKlNxShmLnh5AUbYNjxcNy+VeO5Mnr1siVrmww1AyVGdDFO5EJVcMzvooIKSy1nijRacaZa+ESRPIRmjUAhwiayaPB0oDHQN6n2lkFQk8pw3eQRDx4drFb6aM+ww4bgOtqfPtYKQLzQol+UrMuj4ZpESSmhq+99bZewzV6MSwkT1ZbTS+BA98Lde3aPwqYgxv8aL5DI8BU8LsXgvIzu6wiBA7WDb+R/QsDdDom+CODO43btUd001mc6DiyMsaAdhGxkAGVRP3fnhs0S/qDlJnnAQcdUvC54tQ+v9lJMF6xl3b6PrrCxHdAqtltqJyKTuP+Sr44UqYQJsZ/8joB9XDTPZYe3YLrBwZoa7eUbR+dFvfALCZyMpy78yL9fvzfv7ssdupWCoeWddNk5YwIhaPB+zEhZOqozXpWeQwqHXsOtKKsdomDZveyew3Igbvi84qmr6BButruIq4z2qjuuKRyk3UNT3KXqY/HgbbIy2E2ZKZuSTxPg/JfLpoG9yp+JJzS7QOadNAEPoXUiXXLuWEk7vgG0myrSWYD8coKa8O7mKsVXwpm1Iiy1Nifgf0NZz4PzNf6QXtlzNtPX/fSMlP8LTBTinwwjrvNjShBaKe/rQWBQ5+k6XtTpqoAQkN+Gc3AfzfKqjt2YiTzdrIdAbvJHSnjipTRU7mDgS5IgXI1Alucb47DHCjgwZVjVSUqOnrqNR6Uo1WqRJpBAcNtQe4g+BdABT83FZYUuakSIX9/0l/AL2bWY0cBbEMO3PS6y8y4KOI+e2OgZ0NGvUAPgJpNwX7hvYJy+BIWFOn4AIyb52wUOMsir3PhpgCq0o4qoPsZ2yJ1tQZ2qUw=="}'     },     settings: { preferences: [Object] },     language: '',     statusText: '',     requirePasswordChange: false,     inviteToken: '567CdE'   },   room: {     _id: 'BZwLiYcZLPAirW4R6',     name: 'fl_test_1',     fname: 'fl_test_1',     t: 'p',     msgs: 5,     usersCount: 2,     u: { _id: 'FmQnAeGZpNDbG5nrk', username: 'hartwig.flamm' },     customFields: {},     broadcast: false,     encrypted: false,     ts: 2019-08-09T09:25:37.924Z,     ro: false,     default: false,     _updatedAt: 2020-03-13T14:18:28.426Z,     lastMessage: {       _id: 'kH2JFQu9WeZkp9ACa',       rid: 'BZwLiYcZLPAirW4R6',       msg: 'Hallo?',       ts: 2020-01-22T10:37:15.455Z,       u: [Object],       _updatedAt: 2020-01-22T10:37:15.475Z,       mentions: [],       
channels: []     },     lm: 2020-01-22T10:37:15.455Z   } } 
I20200313-15:18:46.343(1) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: BZwLiYcZLPAirW4R6 
I20200313-15:18:46.343(1) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20200313-15:18:46.345(1) Meteor ➔ method public-settings/get -> userId: gEAEof722NJsRkBjq, arguments: [{}] 
I20200313-15:18:46.738(1) Meteor ➔ method rooms/get -> userId: gEAEof722NJsRkBjq, arguments: [{}] 
I20200313-15:18:46.759(1) Meteor ➔ method subscriptions/get -> userId: gEAEof722NJsRkBjq, arguments: [{}] 

URL after Link was called

https://chat-dev.it.tuwien.ac.at/group/fl_test_1

**Comment by ankar84** [comment]
Looks like #16852

**Comment by pkolmann** [comment]
Yes it's the same issue. Thanks @ankar84 for pointing this out.

**Comment by pierre-lehnen-rc** [comment]
Closing in favor of #16852
