### ISSUE TITLE
Functionality to share contacts

### ISSUE THREAD

**Issue by DinDev3** [RocketChat/Rocket.Chat#16908]
I have noticed that the Rocket.Chat web and mobile versions don't give the option to share contacts. It would be good if this option is implemented especially in the mobile version since it's something that users usually use a messaging service for.

**Comment by DinDev3** [comment]
According to the issue #11557, there's no API implementation to share contacts either. Therefore, both front end & back end will have to be developed to implement this option.

**Comment by WillGoGithub** [comment]
This feature is necessary. 👍
