### ISSUE TITLE
Undefined url for incoming webhook

### ISSUE THREAD

**Issue by martinszy** [RocketChat/Rocket.Chat#16901]
### Description:

Hi, I've just updated to 3.0.4 and everything is great.

I decided to add a webhook following this tutorial: https://rocket.chat/docs/administrator-guides/integrations/gitlab/

The issues is that on step for, this is what I get:
```
curl -X POST -H 'Content-Type: application/json' --data '{"username":"Gitlab","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' https://chat.projectpoder.org/hooks/undefined/undefined
```

Other than the tutorial claiming that the field will contain only the URL and not a full curl command, which is a small issue, the generated url contains undefined variables. The normal log output shows nothing.

I don't know what might be happening, can you help?

### Steps to reproduce:

1.    In Rocket.Chat go to “Administration”->”Integrations” and create “New Integration”
2.    Choose Incoming WebHook
3.    Follow all instructions like Enable, give it a name, link to channel etc. Set “Enable Script” to true and enter the javascript in the “Script” box
4.    Press Save changes and copy the Webhook URL (added just below the script box)
### Expected behavior:
An hook id should be generated

### Actual behavior:
Undefined id is generated

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.4
- Operating System: Ubuntu
- Deployment Method: Kubernetes StatefulSet
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Firefox 69
- Operating System: Ubuntu

### Additional context
When I save the hook, it says it's been saved, but I don't think that's happening. They are not listed in the integrations list in admin.
### Relevant logs:
None produced I think.

**Comment by martinszy** [comment]
Don't worry, it was our cache messing things up.

**Comment by creaux** [comment]
@martinszy how do you mean cache? We have exactly same issue.

What have you done to make it work?

**Comment by creaux** [comment]
It is a bug.

But there is a workaround. Close it, then open created integration again. I think it should be listed.
