### ISSUE TITLE
Allow users to hide "user joined/left channel" messages on a per-user, per-channel basis

### ISSUE THREAD

**Issue by RavuAlHemio** [RocketChat/Rocket.Chat#16906]
SUBJECT: Allow users to hide "user joined/left channel" messages on a per-user, per-channel basis

### Description:

It is currently not possible for a user to set a preference whether to show or hide "user joined/left channel" messages for a specific channel.

### Steps to reproduce:

1. Join (or be joined) to a channel with high join/leave traffic.
2. Read lots of join/leave messages.
3. Miss a normal message due to lots of join/leave messages.

### Expected behavior:

The UI should make it possible for users to set a per-channel preference whether to show or hide system messages such as "user joined/left channel".

### Actual behavior:

Currently, it is only possible for administrators to globally show or hide "user joined/left channel" messages (issue #2959, pull request #4760), affecting all users and all channels.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.3
- Operating System: linux-x64
- Deployment Method: unsure (I am not the administrator)
- Number of Running Instances: unsure (I am not the administrator)
- DB Replicaset Oplog: unsure (I am not the administrator)
- NodeJS Version: v12.14.0
- MongoDB Version: unsure (I am not the administrator)

### Client Setup Information

- Desktop App or Browser Version: Rocket.Chat Desktop 2.17.9, Google Chrome 80.0.3987.132 (64-bit)
- Operating System: Windows 10 version 1909 (OS Build 18363.720)

### Additional context

(I assume no additional context is necessary for this feature request.)

### Relevant logs:

(I assume no logs are relevant for this feature request.)

**Comment by and7ey** [comment]
Has it been implemented?
