### ISSUE TITLE
Video conference not working with guests

### ISSUE THREAD

**Issue by PedroPretto** [RocketChat/Rocket.Chat#16909]
Hello Guys!

We are trying to have a video conference using RocketChat via jitsi.

The feature works just fine while both the participants are using rocketchat interface.

Although, when we try to start a video conference with a external guest, he only receives a blank message like the example below:
![rocket](https://user-images.githubusercontent.com/38132954/76865992-40a66b80-6842-11ea-9fd6-d3ec6179d6f6.png)

Would you guys have any suggestion to fix this?

We are using rocketchat 3.0.2 and all the video conference options and webrtc are enabled.

Looking forward for your answer, 

My best regards,

Pedro.

**Comment by geekgonecrazy** [comment]
@renatobecker is this something that is supposed to work in new livechat widget?

**Comment by renatobecker** [comment]
> @renatobecker is this something that is supposed to work in new livechat widget?

Unfortunately, it's not working yet.
But, the good news is that we have a GSoC project this season that aims to implement it, as well as voice messages.

Thanks.

**Comment by PedroPretto** [comment]
Thanks guys!

Also, do you have any idea when its going to be avaible?

**Comment by renatobecker** [comment]
> Thanks guys!
> 
> Also, do you have any idea when its going to be avaible?

If all goes well with the GSoC project, we will have this feature available in August.

**Comment by PedroPretto** [comment]
Thanks guys, closing this issue!
