### ISSUE TITLE
User Limit for private Groups

### ISSUE THREAD

**Issue by kaffeeknecht** [RocketChat/Rocket.Chat#16904]
### Description:

Private Groups are limited to 100 Users. The admin-Interface prvides no configuration option to change this.

### Steps to reproduce:

1. Create Private group
2. Invite more than 100 Users (via Invitation Link without Limits)

### Expected behavior:

More users can join or better a config option to choose for yourself

### Actual behavior:
the 101st user can't join the channel (so because at least you are member of the channel 99 others can join)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: Ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: 	v12.14.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Browser, Electron Clients, Andorid, iOS etc.
- Operating System: All

### Additional context

User registration is disabled on our server

**Comment by ankar84** [comment]
I don't know:
![image](https://user-images.githubusercontent.com/4023037/76852451-68a2c880-685c-11ea-97f6-79dd42b8e3bd.png)

**Comment by kaffeeknecht** [comment]
Hi. great, but not here.
Perhaps something snap-specific?

> I don't know:
> ![image](https://user-images.githubusercontent.com/4023037/76852451-68a2c880-685c-11ea-97f6-79dd42b8e3bd.png)

**Comment by ankar84** [comment]
> Perhaps something snap-specific?

May be. We use Docker.
