### ISSUE TITLE
[BUG] Confusing verification email

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat#16911]
### Description:

I changed a user email and received an email asking to verify my account, but the writing is confusing.
It says "You have successfully created an account..." although I didn't create a new account.

### Steps to reproduce:

1. Enable "Verify email" on server
2. Change a user email

### Expected behavior:

Maybe verification emails shouldn't assume it's a new user.

### Actual behavior:
![image](https://user-images.githubusercontent.com/804994/76881583-211a3d80-6858-11ea-99c6-e2ea2edc989c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop on open server

**Comment by sampaiodiego** [comment]
we could change `Verification_email_body` i18n key by removing the "successfully created an account" part. but then we should add something similar to `Visit_Site_Url_and_try_the_best_open_source_chat_solution_available_today` i18n key, which is used for welcome/enrolment email.

**Comment by ozata** [comment]
I think we need an if condition whether the mail is creation verification mail or email reset verification mail.
