### ISSUE TITLE
[BUG] incoming webhook script is blank after saving and reloading.

### ISSUE THREAD

**Issue by cjpit** [RocketChat/Rocket.Chat#16917]
### Description:
Script text is blank after saving and reloading

### Steps to reproduce:

![rocket chat](https://user-images.githubusercontent.com/3469512/76930586-cbaa6300-6921-11ea-8dc7-c609e3de5853.gif)

### Expected behavior:

Script text should be visible

### Actual behavior:

Script text is empty

### Server Setup Information:

- Version of Rocket.Chat Server: 3.03
- Operating System:  centos 7
- Deployment Method: manual
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Desktop app/browser
- Operating System: linux

**Comment by cjpit** [comment]
#16692 for previous version as well

**Comment by joshmartintv** [comment]
Looks like this has been an issue for a while.  I'm on 2.4.11 (snap) and am experiencing this.  Seems like if you save the webhook script and never go back into it you're fine, but even if you go back in to edit and don't save, it breaks the webhook.

**Comment by jasonkuehl** [comment]
Yep, same issue

**Comment by GitFromTheInternet** [comment]
We are experiencing this as well.

**Comment by corrigac** [comment]
Also experiencing the same issue, additionally errors in script are only visible after saving  switching administration context and switching back (client 2.17.9 -MacOS)

**Comment by mariohamann** [comment]
Same here.

**Comment by frdmn** [comment]
This should be resolved since 3.3.0 with the new admin components. Can someone else confirm?

**Comment by jnach** [comment]
Still a problem.
