### ISSUE TITLE
Group Message by Time Issue

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#1691]
Ever since #1672 got merged I've noticed a bad side effect:
![2015-12-17_10-09-57](https://cloud.githubusercontent.com/assets/850391/11874689/a0467f4e-a4a6-11e5-8919-41071021e61b.png)
After you scroll up a ways, the chats are separated out even though the messages were sent within a minute of each other.

**Comment by rodrigok** [comment]
Yes I saw that too, I will try to solve ASAP.
