### ISSUE TITLE
Relogin after refresh

### ISSUE THREAD

**Issue by crltzn** [RocketChat/Rocket.Chat#16916]
When you refresh the page it will logout and login again this only occurs using web browser

**Comment by gabriellsh** [comment]
I think this is kind of intended. If you refresh a page, it's like you're leaving the page and going back to it, so connection is lost. It's not necessarily a logout, but you will appear as being offline.

The main problem is, how can we differentiate a user reloading a page from a user that closed the page?  Once page is reloaded/left we have nothing related to rocket.chat running in the browser anymore, so we can't check for anything.

**Comment by frdmn** [comment]
I don't think that's what @crltzn meant, but correct me if I'm wrong of course!

I just upgraded to 3.1.0 as well and noticed the same, as soon as you refresh the page you see the login mask and have to put in credentials again (i.e. relogin on each refresh).

**Comment by gabriellsh** [comment]
Closing due to lack of interaction. Feel free to reopen if you have any info to add.
