### ISSUE TITLE
Group/person conversation selection doesn't mark as read. 

### ISSUE THREAD

**Issue by Malachiasz** [RocketChat/Rocket.Chat#16920]
Version: 2.16.2.
The most annoying thing about RocketChat is that often, after I select a group, its status in the list on the left doesn't become "read", so the grup name is still white. 
Sometimes when I minimize app, go again and select the same group again, then it gets marked.
Going to menu and choosing select as read also helps.

1. I want INSTANT marking as read.
2. I also want option to make a group never inform me about new messages and still be in the list.

**Comment by gabriellsh** [comment]
You can click the three dots on the room and go to notification preferences to customize individual rooms preferences.

**Comment by Malachiasz** [comment]
@gabriellsh I think you relate to my point 2. Which setting in the room settings will cause room never to be marked as unread? Also on Macos I don't see preferences. Under 3 dots I see only:
- hide room
- mark as read
- vaforuite 
- leave room

**Comment by gabriellsh** [comment]
You have to open the room and click on the 3 dots on the header :)

**Comment by gabriellsh** [comment]
Closed in favor of #16921
