### ISSUE TITLE
Volunteer contributor says HI 👋 

### ISSUE THREAD

**Issue by talktopri** [RocketChat/Rocket.Chat#16927]
Hello!

I am interested in helping an Open Source project with their documentation, API, etc and I just came across Rocket Chat! 
I already requested to be added to the Translating Project and I hope to be helpful here! 

I checked open issues with "Documentation: needed" labels, but I wanted to say hi here too, in case there are more Documentation/translation things I can get involved and help with.

Thanks/Obrigada/Gracias!

**Comment by talktopri** [comment]
Ah, found this: https://rocket.chat/docs/contributing/documentation/contribution-guidelines/

**Comment by gabriellsh** [comment]
Hello @talktopri! How's it going?

You can go to [our Rocket.Chat open Server](https://open.rocket.chat/) if you wish to join other contributors. We welcome all help!

This issue area is reserved for bugs, feature requests, etc, so I'll be closing this. See you on Rocket.Chat!
