### ISSUE TITLE
[Feature request]: Obtain ignored users

### ISSUE THREAD

**Issue by LucasFsc** [RocketChat/Rocket.Chat#16924]
Can't get ignored users from RestAPI, apparently there's no endpoint for such request. It just possible to get ignored users through **stream-notify-user**, containing the ignored users, which answers:

`{"msg":"changed","collection":"stream-notify-user","id":"id","fields":{"eventName":"rJGcz5ht9QvDrigkg/subscriptions-changed","args":["updated",{"_id":"s8wSTsaYFTG5a7FXs","open":true,"alert":true,"unread":1,"userMentions":0,"groupMentions":0,"ts":{"$date":1582305083622},"rid":"tAhWePnQup5PkJx8F","name":"asdasdnh989","fname":"asdasdnh989","t":"c","u":{"_id":"rJGcz5ht9QvDrigkg","username":"lucas2k"},"ls":{"$date":1584559198051},"_updatedAt":{"$date":1584561046608},"roles":["owner"],"ignored":["dSHjAeFFBPf7CZoB7","rJGcz5ht9QvDrigkg"]}]}}` 

Also there is a websocket method not described into the API Docs to ignore users:

`{"msg":"method","method":"ignoreUser","params":[{"rid":"tAhWePnQup5PkJx8F","userId":"rJGcz5ht9QvDrigkg","ignore":false}],"id":"17"}`

Using version 2.4.1 of Rocket Chat

**Comment by aryankoul** [comment]
I would like to work on this issue.
