### ISSUE TITLE
Add a switch option to create a channel private or public

### ISSUE THREAD

**Issue by mathben** [RocketChat/Rocket.Chat#16929]
### Description:
Hability to switch option in configuration if by default we want to create a private a public channel.

### Steps to reproduce:
1. Create a new channel and by default, the option is private channel.

### Expected behavior:

The option can be public by default if choose this option in settings.

### Actual behavior:
The default option is private. We cannot switch to public by default.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0
- Operating System: Debian stretch
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: Arch Linux

### Additional context
Thank you for your time!

**Comment by gabriellsh** [comment]
Hey!

Sorry, but I don't really like this idea. It's one more option to clutter the admin UI, and if you really don't want users to be creating private/public channels, you can block it through permissions.

Below is a print of a user without permission to create private channels:

![image](https://user-images.githubusercontent.com/40830821/77072506-8c851c00-69cc-11ea-823d-450b0b78441d.png)

Feel free to argument and make your point though. Thanks for your contribution!

**Comment by mathben** [comment]
Ok thank for you opinion, I will try to do it by myself :-).
From my point of view, there's already a lot of thing in the admin UI, one more won't really make a difference. 
Do you forsee other problems than cluttering the admin UI if I do it?
Thanks

**Comment by gabriellsh** [comment]
Well, I don't really see much value for it. For this to make a difference in workflow you'd have to be creating many many channels per day. Even then, we're currently adding support for multiple user direct messages, which would suffice needing to create multiple channels.

That's my personal opinion at least.

**Comment by marco-websource** [comment]
I think the reason for this wouldn't be an improved workflow but to encourage users to create public channels in environments where transparency is important. (This has been mentioned here already: https://forums.rocket.chat/t/option-to-have-the-public-setting-on-by-default-when-creating-a-channel/1491)

Particularly inexperienced users tend to leave default settings as they are. Therefore they might create private channels even in situations where a public channel would be more appropriate. The option to change the default channel type to public would help in those situations, i.e. users should still be able to create private channels if the wish to do so, but the default should be public.
