### ISSUE TITLE
Clear all unreads modal should take focus from the chat dialog

### ISSUE THREAD

**Issue by dcermak** [RocketChat/Rocket.Chat#16932]
### Description:

The clear all unreads modal dialog does not always take the focus out of the chat area. This has the disadvantage, that you cannot reliably do a quick `shift-esc enter` to clear all unreads and sometimes have to use the mouse to click the dialog.

### Steps to reproduce:

1. Press `shift-esc`
2. Press `enter`. If you had the text enter area active, then now nothing happens.

### Expected behavior:

When pressing `shift-esc` the chat text area should automatically loose focus so that the input is sent to the "clear all unreads" dialog.

### Actual behavior:

When the chat area is active, pressing `shift-esc` opens the modal dialog, but pressing enter does nothing as this is sent to the text area instead.

A possible workaround is `esc shift-esc ret`.

### Server Setup Information:

- Version 2.2.0
- Apps Engine Version 1.7.0
- OS Type Linux
- Deployment Method k8s
- Number of Running Instances 3
- OpLog Enabled
- Node Version v8.15.1
- Mongo Version 3.6.11

### Client Setup Information

- Desktop App or Browser Version: Firefox 73
- Operating System: openSUSE Tumbleweed

### Relevant logs:

None in the Browser. Since this is a frontend issue, server logs shouldn't matter.

**Comment by gabriellsh** [comment]
You're talking about this?

![image](https://user-images.githubusercontent.com/40830821/77211177-dc093c00-6ae1-11ea-9790-2d86a9d881a0.png)

If not, I don't know about what modal you're talking about, pressing `shift-esc` automatically removes the unread messages for me. (Your server is outdated BTW, I'm using 3.1.0-develop). Can you send a gif/video of this happening?

**Comment by dcermak** [comment]
> You're talking about this?
> 
> ![image](https://user-images.githubusercontent.com/40830821/77211177-dc093c00-6ae1-11ea-9790-2d86a9d881a0.png)
> 

No, I'm talking about this dialog that is displayed when you press `shift-esc`:
![Screenshot_2020-03-23 (•) Rocket Chat](https://user-images.githubusercontent.com/45594031/77309390-dc315380-6cfc-11ea-8814-f7ec1d78c57c.png)

> If not, I don't know about what modal you're talking about, pressing `shift-esc` automatically removes the unread messages for me.

Yes, it does that **after** confirming the dialog. That is **not** my issue though, clearing unreads works.

The issue (it's actually more of an inconvenience) is that the modal does not automatically get the focus. I can reproduce it as follows:
- click into the chat text entry box
- press `shift-esc`
- hammer enter (nothing happens, because the text entry box has the focus and **not** the modal dialog)
- clicking on "Yes, clear all" clears all unreads, but I have to click it, I can't use the enter key

>  (Your server is outdated BTW, I'm using 3.1.0-develop). 

Could be, but that is unfortunately out of my control.

> Can you send a gif/video of this happening?

Unfortunately not, the server is internal only and I'd have to cover up essentially every part of the screen.

**Comment by gabriellsh** [comment]
I'm sorry if I wasn't clear: That window didn't appear to me, even after pressing `shift+esc`.

For some reason, testing now, it shows up. I was able to press enter and it worked as expected, but, even pressing `Cancel` made it mark all messages as read.

I'm sorry to inform, but if you can't change the server version, you'll probably not be able to fix this. But, there is a couple of ways you can try to tackle this:

1. If you're admin, you can add custom scripts in Admin > Layout > Custom scripts. You can make a script to listen to the shortcut and use a selector to focus the button.

2. If you're not admin, you can install a browser extension that runs scripts based on URL, and do the same as above.

I can't really think of anyway else you could fix this without having access to the server files.

**Comment by dcermak** [comment]
> For some reason, testing now, it shows up. I was able to press enter and it worked as expected, but, even pressing `Cancel` made it mark all messages as read.

Did you put your cursor into the chat text input field before pressing `shift-esc`?

**Comment by gabriellsh** [comment]
Not actually, why?

**Comment by dcermak** [comment]
> Not actually, why?

Because then you cannot reproduce the issue that I am reporting. If the text entry field has the focus, then the modal will not get it. And that the is the reason why I opened this issue in the first place.

**Comment by gabriellsh** [comment]
When I click the message box and press shift+esc, it clears messages without showing the modal (the first behaviour I talked about). I think in the newer versions of RC that doesn't happen anymore, but other issues do occur, like the modal not showing up. If you think I'm still doing something different than you, you can test this on https://open.rocket.chat/, we keep it always up to date.

**Comment by dcermak** [comment]
It shows the modal for me, but the modal appears to gain focus on open.rocket.chat. So this is caused by the outdated server.

Sorry for the noise.

**Comment by gabriellsh** [comment]
No problem! We're here to help. If you can't update the server, you can still use the custom scripts I talked about, they'll probably work fine.
