### ISSUE TITLE
Video/Voice Chat bug 

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#16934]
### Description:

When We use Video/Voice Chat,the pople who speak can hear own voice （very loudly）,
and the communication may crashe Suddenly...

### Steps to reproduce:
use Video/Voice Chat,

### Expected behavior:

the pople who speak should not  hear own voice.

the communication may crashe Suddenly,we don't know why?

 

### Server Setup Information:
 
 
![image](https://user-images.githubusercontent.com/12368358/77060396-7a7a9c00-6a13-11ea-9b15-d19d7184c10e.png)

![image](https://user-images.githubusercontent.com/12368358/77060433-85353100-6a13-11ea-99aa-605f2e7e25a5.png)

### Client Setup Information

- Desktop App or Browser Version: PC Chrome 80 
- Operating System:Win10

**Comment by ankar84** [comment]
I think it is more related to **Video/Voice Chat** itself, but not Rocket.Chat.
Or you using **Admin UI** - **WebRTC** for that?
If you are using Jitsi, better place to create issue is [here](https://github.com/jitsi/jitsi-meet/issues)

**Comment by mhow2** [comment]
I observed that too, with WebRTC.

**Comment by gabriellsh** [comment]
This could be due to someone's microphone (it usually is). Can you tell us what video chat you're using? (Jitsi, etc) Thanks.

**Comment by 564064202** [comment]
with WebRTC.

**Comment by franckadil** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/15018
