### ISSUE TITLE
Cannot start 

### ISSUE THREAD

**Issue by iMezooo** [RocketChat/Rocket.Chat#16935]
Running npm-postinstall.js
'cp' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:669
    throw err;
    ^

Error: Command failed: cp node_modules/katex/dist/katex.min.css app/katex/
'cp' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (C:\Users\Moaaz\Rocket.Chat\.scripts\npm-postinstall.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 27 63 70 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 6c 20 ... 43 more bytes>
  ],
  pid: 7648,
  stdout: <Buffer >,
  stderr: <Buffer 27 63 70 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 6c 20 ... 43 more bytes>
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@3.1.0-develop postinstall: `node .scripts/npm-postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@3.1.0-develop postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Moaaz\AppData\Roaming\npm-cache\_logs\2020-03-19T10_40_02_126Z-debug.log
PS C:\Users\Moaaz\Rocket.Chat> meteor npm start

> Rocket.Chat@3.1.0-develop start C:\Users\Moaaz\Rocket.Chat
> meteor

npm ERR! code ELIFECYCLEol@1.9.2...          -
npm ERR! errno 3221225477
npm ERR! Rocket.Chat@3.1.0-develop start: `meteor`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the Rocket.Chat@3.1.0-develop start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Moaaz\AppData\Roaming\npm-cache\_logs\2020-03-19T10_51_33_398Z-debug.log

**Comment by 2yue** [comment]
same question~

**Comment by 2yue** [comment]
try to annotation the code  in .scripts/npm-postinstall.js from the line 6 ， some
css files.

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

Also, by reading your error log, this probably is not a problem with rocket.chat. This area is reserved for bugs and related, if you need help, please, go to our [support channel](https://open.rocket.chat/channel/support). Thanks.
