### ISSUE TITLE
Service down? https://hub.rocket.chat/api/v1/peers?search=DOMAIN returns 503

### ISSUE THREAD

**Issue by putt1ck** [RocketChat/Rocket.Chat#16945]
In trying to unsuccessfully setup federation I noticed the error was consistently "server.js:204 Federation ➔ dns.error Error: failed [503] Service Unavailable" regardless of setting changes. On research found out about the manual test using the api and got the same 503 response from the hub server, regardless of URL. Service down deliberately?

**Comment by tomdwyer3003** [comment]
I'm seeing exactly the same error when trying to set this up. New installation on Ubuntu 18.04 of version 2.4.11

**Comment by schaary** [comment]
Same for me - I get `server.js:204 Federation ➔ dns.error Error: failed [503] Service Unavailable`

**Comment by Toking42** [comment]
Same for me - Does anyone have a clue?

**Comment by geekgonecrazy** [comment]
this service is up and fully operational
