### ISSUE TITLE
Heading still visible when the appsWhatIsIt is loading

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#16947]
![Screenshot from 2020-03-20 16-31-00](https://user-images.githubusercontent.com/43509699/77157913-4dd48c00-6ac8-11ea-98d3-c8d143c4d47b.png)

**Comment by gabriellsh** [comment]
Hey @ritwizsinha, please, try to follow at least the issue template. Although you have opened the PR already, there is not enough information provided so other people can understand this. Thanks for your help!

**Comment by gabriellsh** [comment]
Fixed by #17906
