### ISSUE TITLE
Button to add users to ROOM

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1694]
I had an issue with my ADMIN user, ( wasnt able to type more than one message), ended up deleting the user and recreating admin (same username) ..
the challenge now is that ADMIN (User) can not view all the created rooms (Private) even though he is still part of them, I can click on remove user, but we need an add user to join room
##

**Comment by geekgonecrazy** [comment]
I think this is implemented:

![image](https://cloud.githubusercontent.com/assets/51996/15203006/0fe0d6c4-17c5-11e6-8133-382ca70df986.png)

Unless i'm mis-understanding. In which case maybe include pictures.  We like those :grin:

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I think in the end he didn't mean the actual button, but seems to have deleted/re-created the admin account (which probably fucked up the subscriptions).

Cheers
Thomas
