### ISSUE TITLE
markdown doesn't work in channel or discussion name

### ISSUE THREAD

**Issue by wizofaus** [RocketChat/Rocket.Chat#16943]
We're using Rocketchat discussions per JIRA as part of our development process. We have the JIRA hyperlink in the discussion name/title, but there appears to be no way to make it clickable using markdown or otherwise.  It's clickable via an announcement but it's rather too prominent and requires one click to "open" the announcement then another to browse to the link.
But surely markdown should just work in discussion names/titles like other fields? (it doesn't work in 'topic' either).
I did try putting it in the description too, but you can't even see that anywhere?

**Comment by gabriellsh** [comment]
I put it in topic and announcement: 

![image](https://user-images.githubusercontent.com/40830821/77195969-478ee180-6ac1-11ea-8a78-7e4b4789049f.png)

**Comment by gabriellsh** [comment]
We had discussed this, and titles will be kept plain text. Thanks for your concern 😄
