### ISSUE TITLE
Error sending push to gateway

### ISSUE THREAD

**Issue by Sys-Admin889** [RocketChat/Rocket.Chat#16961]
Hello everyone,

- I think this error related to push notifications.

![Capture](https://user-images.githubusercontent.com/59320357/77226045-c47f9100-6b7d-11ea-836b-149e7fa32625.JPG)

- I'm currently using push gateway way to setup push notifications with Rocket.Chat.

- If any user not use the official Rocket.Chat mobile applications, that will cause this error?
   or there are other reasons? 
 
![Capture](https://user-images.githubusercontent.com/59320357/77226613-4f628a80-6b82-11ea-964f-2dc30b1a87e6.JPG)

**Comment by gabriellsh** [comment]
Hello! We always recommend that you try to reproduce errors on the latest version of Rocket.Chat. You're currently using version 2.4.11, and we're currently in 3.0.4 - lot's of things have changed.

What do you mean by `If any user not use the official Rocket.Chat mobile applications`?

**Comment by Sys-Admin889** [comment]
Thanks for your reply.
My Rocketchat server has been installed by snap. 
When trying to update there are no updates available as the bellow command:

administrator@ubuntu:~$ sudo snap refresh rocketchat-server
snap "rocketchat-server" has no updates available

**Comment by gabriellsh** [comment]
It should work just fine with the experimental app. BUT, it is experimental, right? Could be it. Although I think it's not related.

Do notifications work in general? Is any specific user having a problem with it?

**Comment by Sys-Admin889** [comment]
@gabriellsh Yes it is experimental, there is an user having problem with notifications.
I checked his notification prefrences for desktop notification, its value is "all messages".

**Comment by gabriellsh** [comment]
I found this https://forums.rocket.chat/t/introducing-snap-tracks/5890, You have to change snap tracks if you wan't to upgrade to 3.x.x (currently 3.0.2). I'm not sure if it'll fix it, I HIGHLY recommend that you backup everything before update, as from 2.x to 3.x there have been breaking changes. (Should be fine though).

**Comment by Sys-Admin889** [comment]
Solved after upgrading Rocketchat server
