### ISSUE TITLE
Run Docker image in domain / subdir

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#1696]
Hi Guys,

i want to run the docker image in a subdirectory of my domain, for example:

https://domainxyz.com/rocket/

On Reverse Proxy site its all fine, but what parameters i have to change on the application site? The Rocket.Chat Logo and some other things are at the moment not displayed correctly in cause of malformed links..

I tryed the following:

 sudo docker run --name rocket.chat -p 3000:3000 --env ROOT_URL=http://domainxyz.com/rocket/ --link db -d rocket.chat

Anyone has an idea?

Thx!

-> Edit: It seems all after the / in the "root_url" is not recognized. In the settings general it displays only "http://domainxyz.com" not /rocket/

**Comment by TheReal1604** [comment]
No idea ? ;-(

**Comment by philipphoffmann** [comment]
I am having the same issue. Unfortunately, I don't have enough confidence in my js skills to fix it :(

**Comment by TheReal1604** [comment]
As a workaround i think i configure this service as a subdomain. (chat.domainxyz.com) But subdirs are useful, too. Dont need to check several certificates in the homelab, just one ;-)

**Comment by philipphoffmann** [comment]
exactly

**Comment by marceloschmidt** [comment]
We'll have to run a few tests too, I don't know the right answer to this... I know a few people tried running on subfolders, but I'm not sure anyone's had any success.

**Comment by TheReal1604** [comment]
I now deployed it like I explained above. Works wonderfull for family and friends. :+1:

**Comment by howdoicomputer** [comment]
Oh man, super relevant to a project idea I have.

**Comment by TheReal1604** [comment]
@howdoicomputer Done that with subdomains. Works Great.
