### ISSUE TITLE
<br /> Tags do not work in Firefox

### ISSUE THREAD

**Issue by rapliu** [RocketChat/Rocket.Chat#16964]
![QQ图片20200322161727](https://user-images.githubusercontent.com/58632405/77245326-ab97de00-6c58-11ea-9bc9-3e227dc385d4.png)

Version | 3.0.2
-- | --
Apps Engine Version | 1.12.0
Database Migration | 174
Running Instances | 2
OpLog|Enabled
OS Type | Linux
-- | centos7 x64
Node Version | v12.14.0
-- | --

**I want Firefox to display exactly like Google <br />,
Maybe it's a problem with Firefox, if I'm wrong, I'm sorry**

![QQ图片20200322161709](https://user-images.githubusercontent.com/58632405/77245329-b2beec00-6c58-11ea-89cb-2a89a8fe3993.png)
![QQ图片20200322161723](https://user-images.githubusercontent.com/58632405/77245331-b6eb0980-6c58-11ea-8f32-88d358f3a0cc.png)

**Comment by mariaeduardacunha** [comment]
Hi! This happens because the code you wrote is thrown inside a <div> with display: flex, so if you add a <div> around your code, it'll work as expected.

**Comment by rapliu** [comment]
> 嗨！发生这种情况是因为您编写的代码被抛到了
> 
> 带有display：flex，所以如果您添加一个
> 围绕您的代码，它将按预期工作。

你好，谢谢，怎么做?

**Comment by rapliu** [comment]
> Hi! This happens because the code you wrote is thrown inside a
> 
> with display: flex, so if you add a
> around your code, it'll work as expected.

hello,thank you,plaese how to do it?
