### ISSUE TITLE
Cannot write to read-only channels with Android app even if authorized

### ISSUE THREAD

**Issue by tbigot** [RocketChat/Rocket.Chat#16970]
I am member of a read-only channel, and I’ve been authorized to talk. It works perfectly on the web app (I can send messages), but using my up-to-date Android Rocket.Chat app, I have the message “This room is read only” in place of the input text box at the bottom of the screen. No way for me to send any message to this channel using my phone.

**Comment by danger89** [comment]
Maybe it's a bug for..

https://github.com/RocketChat/Rocket.Chat.Android

?

**Comment by tbigot** [comment]
Maybe. How to figure out if it is an API problem or a client one?

**Comment by danger89** [comment]
Can you reproduce the same issue with the web-client? :confused: I think. If that is true, its most likely a server-side API problem. Otherwise it could be Android only related.

**Comment by tbigot** [comment]
@danger89 You’re totally right (I cannot reproduce with the web client). I was about to move this bug on the Android client project, but it has just been labelled by a developer. :thinking:
