### ISSUE TITLE
Slow server self-hosted

### ISSUE THREAD

**Issue by lucasOlivio** [RocketChat/Rocket.Chat#16988]
Description
I have a self hosted Rocket.Chat server on amazon instance, the instance is already on type t3.large and the chat is very slow, to type and on rocketchat react-native app is slow to load big audios too, but the bigger issue is the typing on the channel too slow. I have others websites bigger on other instances with type t3.medium and is not that slow, so I’m not very sure the server config is the problem.
Need urgent help, my boss is on me because of this typing thing, please!

Server Setup Information
Version of Rocket.Chat Server: 2.2.0
Operating System: Ubuntu “18.04.4 LTS (Bionic Beaver)”
Deployment Method: Manual (https://rocket.chat/docs/installation/manual-installation/ubuntu/)
Number of Running Instances: 1
DB Replicaset Oplog: What?
NodeJS Version: 8.11.4
MongoDB Version: 4.0.13
Proxy: nginx 1.14.0
Firewalls involved: Amazon security groups
Any additional Information
Number of users on channel: 252
Number of registered users: 724

RAM: 8gb
CPU: (lscpu output)
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 2
On-line CPU(s) list: 0,1
Thread(s) per core: 2
Core(s) per socket: 1
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 85
Model name: Intel® Xeon® Platinum 8175M CPU @ 2.50GHz
Stepping: 4
CPU MHz: 2499.998
BogoMIPS: 4999.99
Hypervisor vendor: KVM
Virtualization type: full
L1d cache: 32K
L1i cache: 32K
L2 cache: 1024K
L3 cache: 33792K
NUMA node0 CPU(s): 0,1

Don't known wich kind of logs I can look to understand the cause of the problem, just looked htop and seems ok (17% RAM usage)

**Comment by rsjr** [comment]
Dear @lucasOlivio,
Can you please provide more details on this performance issue?
You mentioned:

_"chat is very slow, to type and on rocketchat react-native app is slow to load big audios too, but the bigger issue is the typing on the channel too slow." But we will need more details about this slowness?

Also, you can contact us on support@rocket.chat as we try to keep github for product issues/bugs and feature requests. I will be glad to help you.

Regards,

Rogerio

**Comment by lucasOlivio** [comment]
Hi @rsjr . Sorry for posting in the wrong place. 
I will send a ticket to the email you mentioned and answer there to close this issue, sorry.
