### ISSUE TITLE
Edited text resets to origin text

### ISSUE THREAD

**Issue by sgohl** [RocketChat/Rocket.Chat#16985]
### Description:

9/10 times when you edit your last chat message, hitting enter will not save your edit.
Instead, the original message stays unchanged.
Mostly happens with the desktop app.
Running mongo:3 replicaSet as recommended. I feel that this perhaps has something to do with this, client-app not being synchronized with the actual/current updated message. 

### Server Setup Information:

```
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ +-----------------------------------------------------+
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |                    SERVER RUNNING                   |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ +-----------------------------------------------------+
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |                                                     |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |  Rocket.Chat Version: 3.0.4                         |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |       NodeJS Version: 12.14.0 - x64                 |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |      MongoDB Version: 3.6.17                        |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |       MongoDB Engine: wiredTiger                    |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |             Platform: linux                         |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |         Process Port: 3000                          |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |             Site URL: https://chat.acme.corp   |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |     ReplicaSet OpLog: Enabled                       |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |          Commit Hash: 4f845d16a5                    |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |        Commit Branch: HEAD                          |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ |                                                     |
rocketchat_app.1.ytpc8o8l9vuo@swarm2    | ➔ +-----------------------------------------------------+
```

**Comment by gabriellsh** [comment]
Can you provide the OS in which the Desktop app is running and its version? I use the message edit a lot and this never occurred to me.

Can you test the same app in https://open.rocket.chat ? This server doesn't present any error related to message editing for me. I use the latest app build, macOS Catalina. (if it's an app problem, will probably happen there too).

**Comment by port22** [comment]
I'm running the https://snapcraft.io/rocketchat-desktop v2.17.9 on Manjaro Linux (i3)
but this happens on other OS also.

**Comment by port22** [comment]
for the record: This is repeatingly reported happening with the web application, also.

**Comment by port22** [comment]
I begin to wonder if this is perhaps caused by Traefik .. Does anyone have RocketChat also running behind traefik (v1.7) and is using special configuration?

**Comment by sgohl** [comment]
since I seem to be the only one, I close
