### ISSUE TITLE
client starts jitsi calls

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat#16992]
Hi Together, the rocket client starts jitsi calls again and again at irregular intervals. it is not reproducible, it is sporadic and it always calls other participants. 

does anyone know the problem?

**Comment by Levesque7** [comment]
Same issue here. When an active call is going on, the users in the call are constantly triggering new calls.

**Comment by holzfelix** [comment]
Is there a solution for this? Or any other Voice call System to ingetrage?

**Comment by mreitinger** [comment]
Probably a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/14106

**Comment by gabriellsh** [comment]
Duplicate of #14106
