### ISSUE TITLE
submitted PR without attention (again)

### ISSUE THREAD

**Issue by benkroeger** [RocketChat/Rocket.Chat#16996]
Dear Maintainers,
I submitted PR #15690 end of october 2019 and am since waiting to get any sort of feedback.
It was supposed to help my company evaluate Rocket.Chat as their new messaging tool - in combination with login from Azure AD and picking custom user names.
It also helps closing several other issues (listed in PR description).

Can anyone please tell me what is missing to get this thing processed (even a rejection would be a valid response).

You might be wondering that this text sounds familiar... that is because I opened a similar issue (#16731) before... after which the review was officially started - and not is dragged along for 22 days without any comment from repo maintainers again.

I regularly rebase and adopt my modifications to other PRs that have been merged in the meantime - In case you guys are not interested in the changes I proposed (which seem valuable to a couple of users at least), please let me know - so I can stop maintaining this PR and focus my valuable time on other efforts.

Thanks in advance!

@gabriellsh @pierre-lehnen-rc

**Comment by rodrigok** [comment]
I'm reviewing the pull request
