### ISSUE TITLE
Automatically close code tags

### ISSUE THREAD

**Issue by joepie91** [RocketChat/Rocket.Chat#170]
When using &#96;&#96;&#96; to open a block of code, it's easy to forget to close it again. It'd be helpful if a missing closing &#96;&#96;&#96; would be automatically inserted upon sending a message.

**Comment by chrisidefix** [comment]
Also, it should be possible to quote in test `like this` == \`like this\` and you shouldn't have to start a new line for a block of code - that's just annoying!

**Comment by joepie91** [comment]
Potential complication; you need to be able to add a language directly after the code-block opening tags, for syntax highlighting. Not sure if that'd become a potential edge case in the no-newline scenario.

**Comment by chrisidefix** [comment]
I don't see any complications with that - it's a question of implementation. All you have to do is parse the text right after \`\`\` and if it's a key-word (e.g. `javascript`) then just parse it as that (or do it the way github does and simply render it as code.

**Comment by esambo** [comment]
I like the inline `code` syntax of Slack a lot. Fixed width font in red is great.
Syntax highlighting should be optional, even for:
```
code blocks
like this
```
GitHub renders it just fine right here!
Why not just use [GitHubFlavoredMarkdown](https://help.github.com/articles/github-flavored-markdown/)?

**Comment by joepie91** [comment]
@esambo Isn't that already what Rocket.Chat is using anyway? The language specification method I described is from GitHub Markdown also.

**Comment by engelgabriel** [comment]
Tested with ```js var a = b; window.alert('test'); ```
 
and
 
```js
var a = b;
window.alert('test');
``` 

or
 
```js window.alert('test'); var a = b;
```

even
 
```js var a = b;
window.alert('test');
```
