### ISSUE TITLE
Browser has to be refreshed to see new direct messages

### ISSUE THREAD

**Issue by mimurrayy** [RocketChat/Rocket.Chat#17002]
### Description:

We recently deployed a RocketChat instance. However, one user was unable to access direct messages. The user received notifications about direct messages, but they would not show up in the left pane. When the user tried to start a direct message herself, she received a rate limit error:
"Error, too many requests. Please slow down. You must wait 60 seconds before trying again."
The error would reappear whenever the user tried to create a direct message again (after waiting multiple minutes in between, doing nothing). I then disabled the rate limiter and set the permission "api-bypass-rate-limit" to try and solve the problem. 

Now, direct messages appear for the user and sending direct messages works fine. However, new direct messages sent to the user will only cause a notification. The new message will not appear for the user until she has refreshed the webpage using the Webbrowser. Sending out direct messages works fine, even while the user has outstanding direct messages that do not arrive.

As far as I can tell, only one user has this problem. We use LDAP for user authentication. As far as I can tell, the user is no different to any other user.

A similar issue has been reported in the past but seems unconnected to me:   #5693

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Debian 10
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6.14 (snap)

Server is behind an apache reverse proxy to a sub folder (example.com/chat):
```
<Location /chat>
    Order allow,deny
    Allow from all

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /var/www/(.*)           ws://localhost:3000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /var/www/(.*)           http://localhost:3000/$1 [P,L]
    
    ProxyPassReverse http://localhost:3000
</Location>
```

### Client Setup Information

- Webclient, Safari 
- Operating System: MacOS

### Relevant logs:

Serverlogs for mongodb and rocketchat are completely clean. Nothing gets logged when the problem occurs. Not even the initial rate limit was logged.
On server start, no errors are logged either:
```
I20200325-07:56:08.005(1) Setting default file store to FileSystem 
I20200325-07:56:09.042(1) Setting default file store to FileSystem 
I20200325-07:56:12.628(1) (migrations.js:120) Migrations: Not migrating, already at version 170
I20200325-07:56:15.902(1) Loaded the Apps Framework and loaded a total of 0 Apps! 
I20200325-07:56:16.070(1) Using GridFS for custom sounds storage 
I20200325-07:56:16.076(1) Using GridFS for custom emoji storage 
I20200325-07:56:16.390(1) Updating process.env.MAIL_URL 
I20200325-07:56:17.412(1) ➔ System ➔ startup 
I20200325-07:56:17.412(1) ➔ +------------------------------------------------------+ 
I20200325-07:56:17.412(1) ➔ |                    SERVER RUNNING                    | 
I20200325-07:56:17.412(1) ➔ +------------------------------------------------------+ 
I20200325-07:56:17.413(1) ➔ |                                                      | 
I20200325-07:56:17.413(1) ➔ |  Rocket.Chat Version: 2.4.11                         | 
I20200325-07:56:17.413(1) ➔ |       NodeJS Version: 8.17.0 - x64                   | 
I20200325-07:56:17.413(1) ➔ |      MongoDB Version: 3.6.14                         | 
I20200325-07:56:17.413(1) ➔ |       MongoDB Engine: wiredTiger                     | 
I20200325-07:56:17.413(1) ➔ |             Platform: linux                          | 
I20200325-07:56:17.413(1) ➔ |         Process Port: 3000                           | 
I20200325-07:56:17.413(1) ➔ |             Site URL: [redacted]                     | 
I20200325-07:56:17.413(1) ➔ |     ReplicaSet OpLog: Enabled                        | 
I20200325-07:56:17.414(1) ➔ |          Commit Hash: 8bc295e01e                     | 
I20200325-07:56:17.414(1) ➔ |        Commit Branch: HEAD                           | 
I20200325-07:56:17.414(1) ➔ |                                                      | 
I20200325-07:56:17.414(1) ➔ +------------------------------------------------------+ 

```

**Comment by mimurrayy** [comment]
Switching to the Electron App for Mac solves the issue for us. No idea why Safari might make such problems.

**Comment by sumitsrv** [comment]
I have this issue coming up on my RC deployment. In my case, a direct message works until the users are sent a message on their team channel. The users receive the notifications but their message pane is not updated with the new messages. The users have to refresh their browser tab to see the messages.

Host server: Ubuntu 20.04 (Behind a proxy)
Rocket Chat version: 4.8.1
Browser: Firefox, Chrome
