### ISSUE TITLE
rocket.chat docker can't use thrid party mongoserver

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#17001]
this is my docker-compose.yml

**version: "3.3"
services:
    rocketchat-3000:
        image: rocket.chat:2.4.11
        environment:
            - PORT=3000
            - INSTANCE_IP=172.17.117.62
            - ROOT_URL=http://172.17.117.62:7777
            - MONGO_URL=mongodb://mongoserver.com:27017/rocketchat?replicaSet=rocketchatReplicaSet
            - MONGO_OPLOG_URL=mongodb://mongoserver.com:27017/local?replicaSet=rocketchatReplicaSet
        ports:
            - 3000:3000
        extra_hosts:
            - "rocket-7777:172.17.117.62"
            - "mongoserver.com:172.17.117.61"
        networks:
            - outside
    rocketchat-7777:
        image: rocket.chat:2.4.11
        environment:
            - PORT=7777
            - INSTANCE_IP=172.17.117.62
            - ROOT_URL=http://172.17.117.62:7777
            - MONGO_URL=mongodb://mongoserver.com:27017/rocketchat?replicaSet=rocketchatReplicaSet
            - MONGO_OPLOG_URL=mongodb://mongoserver.com:27017/local?replicaSet=rocketchatReplicaSet
        ports:
            - 7777:7777
        extra_hosts:
            - "rocket-3000:172.17.117.62"
            - "mongoserver.com:172.17.117.61"
        networks:
            - outside
networks:
  outside:
    external: true**

but the result is so bad and amazing ! 127.0.0.1.....................my God

![image](https://user-images.githubusercontent.com/12368358/77501928-5fd17880-6e94-11ea-8a26-697e33a0ab90.png)

**Comment by bbrauns** [comment]
not a rocket.chat bug, check if your mongodb server is reachable.

**Comment by gabriellsh** [comment]
If you have any trouble setting up your Rocket.Chat instance, please goto [our open Support Channel](https://open.rocket.chat/channel/support). Issues are reserved for bugs and feature requests/improvements. Thanks for your comprehension!
