### ISSUE TITLE
diffrent instance can't sync user status (docker-compose)

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#17006]
![image](https://user-images.githubusercontent.com/12368358/77538436-b8c3ff80-6eda-11ea-8603-f91cb243192e.png)

![image](https://user-images.githubusercontent.com/12368358/77538249-61be2a80-6eda-11ea-9fdb-1f71019c129e.png)
**version: "3.3"
services:
    rocketchat-3000:
        image: rocket.chat:2.4.11
        environment:
            - PORT=3000
            - INSTANCE_IP=172.17.117.62
            - ROOT_URL=http://nginxall.local:7777
            - MONGO_URL=mongodb://mongoserver.com:27017/rocketchat?replicaSet=rs0
            - MONGO_OPLOG_URL=mongodb://mongoserver.com:27017/local?replicaSet=rs0
        ports:
            - 3000:3000
        depends_on:
            - "rocketchat-7777"
        extra_hosts:
            - "mongoserver.com:172.17.117.61"
            - "rocketchat-7777:172.17.117.62"
            - "rocketchat-3000:172.17.117.62"
    rocketchat-7777:
        image: rocket.chat:2.4.11
        environment:
            - PORT=7777
            - INSTANCE_IP=172.17.117.62
            - ROOT_URL=http://nginxall.local:7777
            - MONGO_URL=mongodb://mongoserver.com:27017/rocketchat?replicaSet=rs0
            - MONGO_OPLOG_URL=mongodb://mongoserver.com:27017/local?replicaSet=rs0
        ports:
            - 7777:7777
        extra_hosts:
            - "mongoserver.com:172.17.117.61"
            - "rocketchat-7777:172.17.117.62"
            - "rocketchat-3000:172.17.117.62"
**

**Comment by gabriellsh** [comment]
Can you describe better how that happens? Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
