### ISSUE TITLE
Wrong link to room in "New message" email for agent

### ISSUE THREAD

**Issue by nico13051995** [RocketChat/Rocket.Chat#17007]
### Description:
When agent has status "Away" or "Offline" and in the same moment customer send message to Agent in already active Live Chat, he will get email with subject "[customer] has posted a message in [room name]".
This email should contain link to room, but link is broken (don't contain room id)
As result after redirect get:

Error:404
Oops, page not found
Sorry, page you requested does not exists or was deleted!

### Steps to reproduce:

1. Start new live chat on the site and write first message
2. Operator/Agent clicks on new live chat from Incoming Livechats section.
3. Operator/Agent send message to customer
4. Operator/Agent move to other browser tab or another way to get status "Away" or "Offline"
5. Customer send new message when operator has status "Away" or "Offline"
6. Operator/Agent get email with new message information and link to messages
7. Click button to see room with messages. Error 404 appears instead of chat room.

### Expected behavior:

Redirect to room with customer and see sent messages

### Actual behavior:

![image](https://user-images.githubusercontent.com/11478884/77541105-ded2ab00-6eac-11ea-92dc-9405781308ae.png)

Broken link => https://[domain]/live

![image](https://user-images.githubusercontent.com/11478884/77541386-4852b980-6ead-11ea-8015-182cbbf9479f.png)

### Server Setup Information:
Please check log info

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows

### Relevant logs:

I20200324-21:47:43.492(0) Setting default file store to FileSystem 
I20200324-21:47:45.416(0) Setting default file store to FileSystem 
I20200324-21:47:48.163(0) (migrations.js:120) Migrations: Not migrating, already at version 174
I20200324-21:47:52.689(0) Loaded the Apps Framework and loaded a total of 0 Apps! 
I20200324-21:47:53.009(0) Using GridFS for custom sounds storage 
I20200324-21:47:53.017(0) Using GridFS for custom emoji storage 
I20200324-21:47:53.178(0) Updating process.env.MAIL_URL 
I20200324-21:47:54.389(0) ➔ System ➔ startup 
I20200324-21:47:54.389(0) ➔ +-------------------------------------------------+ 
I20200324-21:47:54.393(0) ➔ |                  SERVER RUNNING                 | 
I20200324-21:47:54.394(0) ➔ +-------------------------------------------------+ 
I20200324-21:47:54.399(0) ➔ |                                                 | 
I20200324-21:47:54.399(0) ➔ |  Rocket.Chat Version: 3.0.5                     | 
I20200324-21:47:54.399(0) ➔ |       NodeJS Version: 12.16.1 - x64             | 
I20200324-21:47:54.400(0) ➔ |      MongoDB Version: 4.0.17                    | 
I20200324-21:47:54.400(0) ➔ |       MongoDB Engine: mmapv1                    | 
I20200324-21:47:54.401(0) ➔ |             Platform: linux                     | 
I20200324-21:47:54.401(0) ➔ |         Process Port: 3000                      | 
I20200324-21:47:54.402(0) ➔ |             Site URL: https://  | 
I20200324-21:47:54.402(0) ➔ |     ReplicaSet OpLog: Enabled                   | 
I20200324-21:47:54.402(0) ➔ |          Commit Hash: 26094592f8                | 
I20200324-21:47:54.409(0) ➔ |        Commit Branch: HEAD                      | 
I20200324-21:47:54.410(0) ➔ |                                                 | 
I20200324-21:47:54.410(0) ➔ +-------------------------------------------------+ 
I20200325-09:13:09.207(0) Updating process.env.MAIL_URL 
I20200325-09:13:09.679(0) Starting Email Intercepter...

**Comment by andrey56097** [comment]
I have the same issue

**Comment by sampaiodiego** [comment]
@renatobecker can you please check if this is still happening? thanks

**Comment by renatobecker** [comment]
> @renatobecker can you please check if this is still happening? thanks

Sure thing, @sampaiodiego. Thanks for bringing it up.
