### ISSUE TITLE
Notification mail may confuse recipients due to misleading From-Field

### ISSUE THREAD

**Issue by abelbabel** [RocketChat/Rocket.Chat#17008]
Notification mails show names of participants that sent a chat-message while using configured global mail from address. Users may get confused and they may reply to those notification mails, because it appears to them that they got the mail from the participant whose name is part of the From-Header ...

**Possible solution**: Remove name from From-Header-Field.

Instead of

https://github.com/RocketChat/Rocket.Chat/blob/54b55236187987bb47a0759c07c8f6999bdcb42d/app/lib/server/functions/notifications/email.js#L141

use

``email.from = `${ settings.get('From_Email') }`;``

**Comment by abelbabel** [comment]
Any comments from Rocket.Chat-devs on this simple issue? @rodrigok @sampaiodiego @engelgabriel ...

**Comment by sampaiodiego** [comment]
closing as duplicated of https://github.com/RocketChat/Rocket.Chat/issues/12176

there is also a PR that tries to fix the issue https://github.com/RocketChat/Rocket.Chat/pull/15767

**Comment by abelbabel** [comment]
Thank you!
