### ISSUE TITLE
Changing from a 2.0.0 Rocket server to latest release

### ISSUE THREAD

**Issue by LucasPanaro** [RocketChat/Rocket.Chat#17013]
Hey guys,

I have 3 rocket chats version 2.0.0 running on 3 different machines and I need to change them to another virtual server while upgrading to the latest stable release of Rocket.
Is there any way to do that without risk to loose any data/configuration and with the least stop time possible?

Thanks

**Comment by gabriellsh** [comment]
Please, go to https://open.rocket.chat/channel/support, they'll help you there. We reserve issues for bugs and feature requests. Thanks for your comprehension!
