### ISSUE TITLE
Intial random password email is never sent when adding new user

### ISSUE THREAD

**Issue by didierm** [RocketChat/Rocket.Chat#17027]
### Description:

When creating a new user via the `Administration > Users > Add User` interface, the default settings are (see screenshot) : 
* `Set random password and send by email`
* `Send welcome email`

![image](https://user-images.githubusercontent.com/989004/77656774-a72f3600-6f74-11ea-91f2-5c07d0fcdfe9.png)

The welcome email is sent & received, but the random password email is never sent (confirmed by MTA logs), hence it is impossible for the new user to log in.

### Steps to reproduce:

1. `Administration > Users > Add User`
2. `Set random password and send by email` : this option is already enabled by default
3. `Save`

### Expected behavior:

The new user receives a random password email, and uses this password to log in.

### Actual behavior:

The new user does not receive a random password email, and therefore cannot log in.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: CentOS 7.7
- Deployment Method: tar

### Additional context

Disabling & re-enabling the `Set random password and send by email` option while creating the user does not fix the issue.

For the new user to receive a random password, the admin has to subsequenty `[Edit]` the newly created user, and enable for a second time the `Set random password and send by email` option, after which a password email is sent : 

![image](https://user-images.githubusercontent.com/989004/77656858-c62dc800-6f74-11ea-9fdc-828ee33adfd3.png)

![image](https://user-images.githubusercontent.com/989004/77656932-dcd41f00-6f74-11ea-860f-36c6ad049ba8.png)

**Comment by nico13051995** [comment]
@didierm I've the same issue, but maybe this flow is correct.
I found solution, I've add special line in email HTML template.

> \<p>{Your_temporary_password_is_password}\</p>

![image](https://user-images.githubusercontent.com/11478884/77662785-fa10e980-6f84-11ea-88cf-20a530fb297f.png)

**Comment by didierm** [comment]
@nico13051995 That is a nice temporary fix, but : 
- we do not like to send passwords together with other credentials information in one email ;
- the UI specifically has a separate option to send the password (which is contradictory to an assumed/implied requirement of including a password template in the registration email).

If I remember well, it worked this way in the past (separate welcome & password email messages), so I'd consider this a regression.

**Comment by sampaiodiego** [comment]
fixed by #17249
