### ISSUE TITLE
MongoDB High CPU usage

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#17023]
#13913 # Description:

Migrating to Rocket.Chat v2.3.1 we see a high CPU usage for mongodb with unusual long request. It seems that an index is missing on `rocketchat_sessions`.
`2020-03-25T23:04:59.321+0100 I COMMAND  [conn131] command rocketchat.rocketchat_sessions command: find { find: "rocketchat_sessions", filter: { sessionId: "E4c5duMed9mskaKkN" }, limit: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1585173854, 74), signature: { hash: BinData(0, E4CD21E8F74F00AF955BAC52AF4B174FC8D16200), keyId: 6768909496908513281 } }, $db: "rocketchat" } planSummary: COLLSCAN keysExamined:0 docsExamined:3794049 cursorExhausted:1 numYields:29645 nreturned:0 reslen:228 locks:{ Global: { acquireCount: { r: 59292 } }, MMAPV1Journal: { acquireCount: { r: 29736 }, acquireWaitCount: { r: 13 }, timeAcquiringMicros: { r: 257558 } }, Database: { acquireCount: { r: 29646 }, acquireWaitCount: { r: 3 }, timeAcquiringMicros: { r: 5372 } }, Collection: { acquireCount: { R: 29646 }, acquireWaitCount: { R: 87 }, timeAcquiringMicros: { R: 183458 } } } protocol:op_msg 45227ms`

Adding an index on `sessionId` did the trick.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 99
- DB Replicaset Oplog: yes
- NodeJS Version: 8.12
- MongoDB Version: 3.6

**Comment by eidermar** [comment]
I think we are having the same issue. We do have a Snap installation, how would we go about adding an index on sessionID? I have never bothered with mongoDB so far at all. But our system seems rather unstable and some basic actions like uploading/downloading attachments takes a very long time. I can see the exact same entries in the mongoDB logs whenever some file actions are performed by users.

**Comment by bbrauns** [comment]
probably related to #17095
