### ISSUE TITLE
room info name custom bug

### ISSUE THREAD

**Issue by rapliu** [RocketChat/Rocket.Chat#17029]
**hello!admin 
I used UTF-8 ". +", When I added a Chinese channel “——公共大厅——” for the first time, its name was successfully displayed as “——公共大厅——”, which is convenient for Chinese users to search and search, but it is not known how long ago, when I added a Chinese channel “火箭” again, it actually displayed as “huo3-jian4 ”, I have checked for a long time and can't find the reason, so I come for help! Thank!
**and logs view`I20200325-12:14:45.854(8) Warning: language  is not supported in this project, fallback language (en) `
`I want to know what affected it, and I want it to display in Chinese correctly`
![001](https://user-images.githubusercontent.com/58632405/77663123-acfa3b00-6fb7-11ea-82d7-a036153df780.png)
![002](https://user-images.githubusercontent.com/58632405/77663140-b2f01c00-6fb7-11ea-93da-91517e06da49.png)

```
Version: 3.0.5  
NodeJS Version: 12.14.0 - x64
MongoDB Version: 4.2.3
MongoDB Engine: wiredTiger
Platform: linux
ReplicaSet OpLog: Enabled
```
```

**Comment by rapliu** [comment]
I think this is a bug after running for a long time, because there was no error at the beginning, I can't find the reason

**Comment by rapliu** [comment]
@gabriellsh The same problem happens again, and then in my other test case, it happens again

**Comment by Bruce-Ming** [comment]
布局->用户界面->允许Room名称中的特殊字符开启,会导致room的url变成huo3-jian4这种形式,关闭的话就会变成中文的转码形式.
layout->userInterface->Allow Special Characters in Room Names,it change room url

**Comment by rapliu** [comment]
> 布局->用户界面->允许Room名称中的特殊字符开启,会导致room的url变成huo3-jian4这种形式,关闭的话就会变成中文的转码形式.
> layout->userInterface->Allow Special Characters in Room Names,it change room url

thank you very much!you are great!
