### ISSUE TITLE
video chat on readonly channel

### ISSUE THREAD

**Issue by JohannesKarlUniDuE** [RocketChat/Rocket.Chat#17021]
### Description:

we created a readonly channel. All user are joined to this chnanel after registration. One user started a videocall (we enabled it even as it's a beta feature) on this channel. Everybody was able to see this invite.

### Steps to reproduce:

1. enable video chats
2. create a readonly channel
3. start a video chat

### Expected behavior:

Video Chat is unavailable from menu

### Actual behavior:

Video Chat is possilbe

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.5
- Operating System: ubunut 18.04 latest
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: ?
- MongoDB Version: latest

### Client Setup Information

- Desktop App or Browser Version: firefox, chrome, windows client, android app
- Operating System: windows, android

Thanks for all your work

**Comment by GoetheG** [comment]
I'm wondering how secure is the video tool?

**Comment by JohannesKarlUniDuE** [comment]
we use our own jitsi server. As we trust them it's a secure video chat for our need right now

**Comment by ankar84** [comment]
Related or duplicate #16905
