### ISSUE TITLE
Video Chat (Jitsi) not working on Android

### ISSUE THREAD

**Issue by jakub2503** [RocketChat/Rocket.Chat#17051]
**Description:**
I am trying to join/start video chat (Jitsi) on Android client. Joining/creating video chat via Desktop App / Internet Browser is working properly

**Steps to reproduce:**
1. Go to private channel.
2. Click participant's name (at the top of the window).
3. Click "Video call".
4. A screen with information: "Connecting to Your meeting" is being displayed (translated from my language, might differ from original translation).

**Expected behavior:**
User gets connected to video chat room.

**Actual behavior:**
I see a continuous loading icon, with dimmed camera preview in background. User is not getting connected to video chat. Video chat via Jitsi works properly via Desktop App (Windows/Linux) and via Web Browsers (Firefox/Chrome)

**Server Setup Information:**
Version of Rocket.Chat Server: 3.0.4
Operating System: Ubuntu kernel 4.18.0-25-generic
Deployment Method: Docker
Number of Running Instances: 1
MongoDB Version: v4.0.17

**Client Setup Information**
Android app: v 4.5.2.2110

**Comment by ApolloLV** [comment]
I observe the behavior that it claims to have loaded the video chat, and I see myself with the usual jitsi icons, but it does not actually connect properly to the server. The chat messages are not delivered to the actual jitsi call and the video&audio connection is not actually established.
This happened both on the official meet.jit.si server as well as a "vanilla" private one.

**Comment by jakub2503** [comment]
Any updates on this? Thank You in advance.

**Comment by luixxiul** [comment]
To use Jitsi on Android basically you would need Android app so I think the practical way to handle the situation is to share the room name with those who are on Android and ask them to search for that on their app.

**Comment by luixxiul** [comment]
What do you get on the log?

**Comment by jakub2503** [comment]
No errors and warnings in the logs.
