### ISSUE TITLE
Incoming Webhooks post without username and avatar the first time they join a channel

### ISSUE THREAD

**Issue by Morgul** [RocketChat/Rocket.Chat#1705]
The first time the user for an Incoming Webhook posts a message, it posts without an avatar or username:

<img width="317" alt="screen shot 2015-12-18 at 9 45 24 pm" src="https://cloud.githubusercontent.com/assets/770655/11911128/0888c190-a5d1-11e5-896e-35acfa37d4bf.png">

That is a join message, the first post ("Testing!") and a second post ("More tests!"). The styling also seems broken, but probably because the elements are missing.

**Comment by engelgabriel** [comment]
Thank for the report @Morgul 

The grouping of the message should be now fixed, can you test that?

I dont think we would/should be able to support the join message with the alias tho.

The bot will only join the channel once anyway. And if is that important to be "Grevious" from the JOIN message, than you can always create the "Grevious" bot.

**Comment by Morgul** [comment]
@engelgabriel That sounds reasonable to me; the join message should be the bot's default name and avatar.

I will test this again tomorrow, and report back.

**Comment by Morgul** [comment]
I can confirm this is now working with the latest code on develop.
