### ISSUE TITLE
[BUG] IMessageAttachment is not collapsed

### ISSUE THREAD

**Issue by JuzSer** [RocketChat/Rocket.Chat#17063]
### Description:

I'm developing app on version 3.1.0-rc.1, and see the IMessageAttachment is not collapsed even I set the `collapsed: true`.
**It's still working when I used version 3.0.x.**

### Steps to reproduce:

1. IMessageAttachment
2. Set `collapsed:true`
3. The attachment is not collapsed on 3.1.0

### Expected behavior:

The message's attachment should be collapsed, both as default and when refresh the platform.

### Actual behavior:

It works well (collapsed) on 3.0.x but it's expanded on 3.1.0. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-rc.1
- Operating System: MacOS
- Deployment Method: Development, git
- Number of Running Instances: 1
- NodeJS Version: 10.16
- Meteor: 1.10

### Client Setup Information

- Desktop App or Browser Version: Chrome 80
- Operating System: MacOS

**Comment by ggazzo** [comment]
closed by: 16994
