### ISSUE TITLE
Add "Jump to Date" action on Channel

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#17069]
![image](https://user-images.githubusercontent.com/1000217/77838536-3db55000-714b-11ea-852b-ad60fd9bc42c.png)

![image](https://user-images.githubusercontent.com/1000217/77838561-6fc6b200-714b-11ea-8f93-1b2de8bcfcaf.png)

The user should choose a date, and the server will return the channel history from the first message after that date.

**Comment by michnovka** [comment]
If we start a bounty on this, any chance it will make it sooner than in 4.1.0 release?
