### ISSUE TITLE
Flag on App Marketplace if a local app is using the same App ID

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#17066]
If you deploy an app locally with the same ID of an app from the marketplace, it will show an UPDATE button on both apps rather than flagging the conflict.

**Comment by d-gubert** [comment]
I'm not sure this is viable. For instance, if you're developing a new version for your app that is already published in the Marketplace, this will prevent you from installing via the CLI.

It is kind of difficult to come up with a "conflict detection" routine that wouldn't cause problems with the above situation, really 😕

**Comment by engelgabriel** [comment]
OK, but we need to FLAG this, and maybe turn off the UPGRADE? Because it did not even work when I clicked it.
