### ISSUE TITLE
[IMPROVEMENT] Option to not show thread messages in channel

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#17082]
Currently, messages typed in a chat are also shown in the channel, where the thread originates.

It would be nice if this could be optional, at least as a global option, best if on a per-thread basis.

Slack, for example, uses a checkbox to "also send to" the originating channel.

![Bild 30 03 20 um 14 49](https://user-images.githubusercontent.com/2821879/77914105-b32d3780-7295-11ea-9dbb-4cc9f100d867.jpg)

**Comment by zdumitru** [comment]
This is a duplicate of #14719

**Comment by pierre-lehnen-rc** [comment]
Closing in favor of #14719
