### ISSUE TITLE
dropdown bug

### ISSUE THREAD

**Issue by keanu-stitch8** [RocketChat/Rocket.Chat#17097]
### Description:
dropdown visual bug. The option is moved to the left so it's cutout

### Steps to reproduce:

1. Go to Administration
2. Choose CAS
3. CAS Version select

### Expected behavior:

normal dropdown

### Actual behavior:

![2020-03-31 00_16_42-Rocket Chat](https://user-images.githubusercontent.com/62930684/78002001-b93c1a80-7360-11ea-839e-d8b7ccf7068e.png)

### Client Setup Information

- Desktop App or Browser Version: Desktop
- Operating System: Windows 10

**Comment by talheim-it** [comment]
@keanu-stitch8 checked with Firefox latest on Fedora 31 Workstation. No problems.

Which version of Rocket.Chat do you use?

**Comment by keanu-stitch8** [comment]
native app desktop on windows 10 version 2.17.1

**Comment by talheim-it** [comment]
@keanu-stitch8 tested with Desktop version 2.17.7, no problems.
Rocket.Chat 3.0.9 

Please upgrade.

**Comment by keanu-stitch8** [comment]
2.17.7 fixed the problems, thank you @talheim-it !!

**Comment by talheim-it** [comment]
@keanu-stitch8 great, can you close the issue? :)
