### ISSUE TITLE
Rocket.Chat 3.0.5 - lack of index on rocketchat_sessions

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#17095]
### Description:

After upgrade to 3.0.5 version and start Rocket.Chat mongo processor load is 100%. In mongo logs a lot of entries as decribed in logs section

There is lack of index on collection `rocketchat_sessions` on field `sessionId`

After add this index Rocket.Chat is usable again.

### Steps to reproduce:

1. Upgrade Rocket.Chat to 3.0.5
2. A lot of long during queries on `rocketchat_sessions` caused lack of index

### Expected behavior:

Typical load on Mongo.

### Actual behavior:

Mongo load is very high

### Server Setup Information:

- Version of Rocket.Chat Server: 8.0.5
- Operating System: Centos 7
- Deployment Method: Docker Compose
- Number of Running Instances: 30
- DB Replicaset Oplog: YES
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: All clients
- Operating System: All

### Relevant logs:

`2020-03-31T08:16:30.083+0200 I COMMAND  [conn48149] command rocketchat.rocketchat_sessions command: find { find: "rocketchat_sessions", filter: { sessionId: "RZoFQskCmjiwfHHWj" }, limit: 1, returnKey: false, showRecordId: false, $clusterTime: { clusterTime: Timestamp(1585635389, 3), signature: { hash: BinData(0, A871C23168F0CA0513B43B8BD71F3580654101EF), keyId: 6778075279240724481 } }, $db: "rocketchat" } planSummary: COLLSCAN keysExamined:0 docsExamined:876434 cursorExhausted:1 numYields:6847 nreturned:1 reslen:674 locks:{ Global: { acquireCount: { r: 6848 } }, Database: { acquireCount: { r: 6848 } }, Collection: { acquireCount: { r: 6848 } } } storage:{} protocol:op_msg 796ms`

**Comment by 564064202** [comment]
Sir,please give us your docker-compose.yml file,and we can try to analyze it

**Comment by ankar84** [comment]
@bbrauns please explain in details how to add additional index to `sessionId` for `rocketchat_sessions` collection?
And did you find a way how to clean that collection?

**Comment by bbrauns** [comment]
https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/
I don't remember exactly but something like that:
```
use rocketchat
db.rocketchat_sessions.createIndex( { sessionId : 1 })
```

**Comment by ankar84** [comment]
> I don't remember exactly but something like that:

Thanks a lot for command!
