### ISSUE TITLE
Duplicate mentions.

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#1709]
It appears if someone edits a message with a mention in it, you see both the edited and the un-edited message in "Mentions":
![selection_024](https://cloud.githubusercontent.com/assets/2517921/11914732/39b051be-a687-11e5-9290-837116526893.png)

**Comment by marceloschmidt** [comment]
Mmmm, right... I'm guessing you have the Keep Message History option enabled? I'll work on fixing that now. Thanks!
