### ISSUE TITLE
Option to enable/disable notification sound/message

### ISSUE THREAD

**Issue by SN4T14** [RocketChat/Rocket.Chat#171]
The notification sound (which appears to be taken from Facebook?) gets quite annoying after a while because every time I hear it I instinctively check Facebook. It'd be nice to be able to either turn it off entirely, or set which channels play a notification sound. Additionally, being able to choose another notification sound (or you switching away from the Facebook one entirely) would probably be good, to prevent the instinctive Facebook checking that I mentioned above.
##

**Comment by sampaiodiego** [comment]
what do you think about the sounds proposed in #71 ?

**Comment by joepie91** [comment]
I'd personally say that regardless of new sound, there should be a mute setting :)

**Comment by SN4T14** [comment]
I agree with what joepie91 said both here and in #71, a lower-pitched sound, more of a "bloop" sound would be nicer than the ones suggested in #71, and of course with a compatible license.

**Comment by engelgabriel** [comment]
Depends on #249

**Comment by shtefcs** [comment]
Any plans when u gonna implent this ? :). I know you have more important things to do, just wondering about this feature, cause I really find its missing. It's causing alot of delay in communication between my team, cause none getting any notifications of messages in private rooms.

**Comment by geekgonecrazy** [comment]
Going to reference: #1268 as it has a bounty attached.

**Comment by circa1977** [comment]
+1 for more notification settings, including enabling icon bounce/color change with sound disabled in native desktop apps.
