### ISSUE TITLE
Maybe use control-mergebox instead of meteor-streams

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#1710]
I made a [package](https://github.com/peerlibrary/meteor-control-mergebox) which allows one to disable Meteor's mergebox in publish functions, but keep all other functionality intact. I think it is cleaner and easier to use it then custom code around meteor-streams.

But, I have not tested it really much, so maybe it does not work as advertised. ;-)
##

**Comment by engelgabriel** [comment]
I like the idea. We are studying your package already :)

**Comment by Charuru** [comment]
Hows it going?

**Comment by engelgabriel** [comment]
We liked the approach, but I haven't had time to implement and test it.

I believe this kind of ability to turn off the mergebox if coming to Meteor official release soon anyway.

**Comment by mitar** [comment]
> I believe this kind of ability to turn off the mergebox if coming to Meteor official release soon anyway.

Not to my knowledge?

**Comment by engelgabriel** [comment]
As they move to GraphQL, they said the reactivity all the way from the DB will become optional...

**Comment by mitar** [comment]
Oh, yes. But that will not be so soon? But yes. :-)
