### ISSUE TITLE
v3.1.0  - Sidebar does not show avatars anymore

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#17104]
# Description:

Sidebar does not show avatars of users any more.

### Steps to reproduce:

Login to Rocket chat

### Expected behavior:

Sidebar does show avatars of users

### Actual behavior:

Sidebar does not show avatars of users. This was working in 3.0.6

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.0 rc5
- Operating System:  CentOS 7
- Deployment Method: tar
- Number of Running Instances:  3
- DB Replicaset Oplog:  Enabled
- NodeJS Version:  v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Firefox and Desktop 2.17.9
- Operating System: Fedora

**Comment by TimmiORG** [comment]
@ggazzo do you need more information from my side?

**Comment by PrinzMonty** [comment]
Yes and when i upload files i receive a 400 (Bad Request) Error.

Can you confirm this?

My Version 3.0.9 with Docker.

**Comment by bkraul** [comment]
This is happening on aa79e0f docker:develop as well.

**Comment by PrinzMonty** [comment]
I cannot say exactly why all this happened after an update, but here is my solution.

1. Go to my rocketchat container `docker exec -it CONTAINER_NAME bash`
2. Find the UID and GID from user rocketchat with `id rocketchat`
3. Go to host and set the permissions of my mounted volume "uploads/" with `chown -R UID:GID uploads/`

And thats is it. Finaly i can upload files and change avatars etc.

**Comment by bkraul** [comment]
Is this being looked at? Seems it's kinda getting stale. 🙂

**Comment by bkraul** [comment]
@PrinzMonty your solution does not address existing avatars. Even after setting the folder permissions as per your instructions, existing avatars still don't show up on sidebar. @ggazzo a little help here...
