### ISSUE TITLE
Rocket chat not loading on ie 11

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#17119]
### Description:

Rocketchat is not loading on IE 11, Hangs at 3 dots.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

rocketchat to load

### Actual behavior:

rocketchat hangs at 3 dots.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0 RC 6
- Operating System: Centos
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: yes
- NodeJS Version: 12.16.1
- MongoDB Version:4.0.17

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by gabriellsh** [comment]
Closed by #17125
