### ISSUE TITLE
Option to switch menu's position

### ISSUE THREAD

**Issue by Thames97** [RocketChat/Rocket.Chat#1711]
So, I was just thinking,can you please create a feature that allows the users/admins to set in what place do they want to put the menu? For example, in this case: 
http://i.imgur.com/2Wymp9X.png

We could have an option where we could change the menu's position to the right, thanks in advance!
##

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
