### ISSUE TITLE
About install Rocket.Chat in a subfolder

### ISSUE THREAD

**Issue by uebian** [RocketChat/Rocket.Chat#17122]
### Description: 
I want to install Rocket.Chat in a subfolder.I'm using ubuntu,snap to install Rocket.Chat and using nginx as proxy server

### Steps to reproduce:

1. set the ROOT_URL environment variable
2. set the nginx config file:

location /chat {
	proxy_pass http://127.0.0.1:3000;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "Upgrade";
	proxy_set_header Host $http_host;
	proxy_set_header X-Real_IP $remote_addr;
	proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forward-Proto http;
	proxy_set_header X-Nginx-Proxy true;
	proxy_redirect off;
}

### Expected behavior:
be able to use rocket.chat in https://xxxxxxx/chat

### Actual behavior:
Can login in and send and receive message,but there is some mistakes in the browser's console 
![图片](https://user-images.githubusercontent.com/18532671/78138216-1cd44f80-7416-11ea-8681-0c82c4a99114.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version:Chromium
- Operating System:Archlinux

**Comment by Sing-Li** [comment]
@uebian   Please see our announcement : https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371
