### ISSUE TITLE
some user not available by _id

### ISSUE THREAD

**Issue by sistason** [RocketChat/Rocket.Chat#17134]
### Description:

I stumbled upon a user in my rocket.chat not accessible by _id.
-> The user is available via members.list, has all attributes, is present in the db like everyone else, but Rocketchat cannot access it by id, neither per API, nor per App/Browser

### Steps to reproduce:

```
1. users_list ->
{'users': [
[...]
{'_id': 'XZnDj97GMJPk6SaZY',
  'username': 'myself',
   [...]
},
{'_id': 'ufsFsXYcvP93b8PxG',
  'createdAt': '...',
  'emails': [{'address': '<redacted>', 'verified': False}],
  'type': 'user',
  'status': 'offline',
  'active': True,
  '_updatedAt': '...',
  'roles': ['user'],
  'name': 'XYZ',
  'lastLogin': '...',
  'statusConnection': 'offline',
  'utcOffset': 1,
  'username': 'XYZ'},
[...]
},
'count': 38,
'success': True
}
```

2. user per ID does not work on the XYZ-user, but everyone else
```
users.info(userId="XZnDj97GMJPk6SaZY")
-> {'_id': 'XZnDj97GMJPk6SaZY',
  'username': 'myself',
   [...]
}

users.info(userId="ufsFsXYcvP93b8PxG")
-> 404
```

3. user per username does work on everyone
```
users.info(userName=XYZ)
-> {'user': {'_id': 'ufsFsXYcvP93b8PxG',
   'username': 'XYZ',
   [...]}

users.info(userName=myself)
-> {'_id': 'XZnDj97GMJPk6SaZY',
  'username': 'myself',
   [...]
}
```

4. This is reproduceable in the Admin-Interface of the Electron app and in the browser, I see the user in Administration->Users, but it never finishes loading.when I click on it to show infos (as it also calls the API).

5. The database itself is fine:
```
rs0:PRIMARY> db.users.find({username: "XYZ"})
{ "_id" : "ufsFsXYcvP93b8PxG", "username": "XYZ", [...]}
rs0:PRIMARY> db.users.find({_id: "ufsFsXYcvP93b8PxG"})
{ "_id" : "ufsFsXYcvP93b8PxG", "username": "XYZ", [...]}
```

### Expected behavior:

users_info(userId=$ID) should give me the user.

### Actual behavior:

As above, _EVERY_ call involving that users _id fails, returning 404.
This includes:
- users_info(userId)
- users_get_avatar(userId)
etc.

The user is perfectly accessible by username, though, which is my workaround calling 
`get_by_id -> if 404 -> get_by_username`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.3, but observed since 2.XX
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 128
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Both, + API
- Operating System: API

### Relevant logs:

None

**Comment by ankar84** [comment]
@sistason I think that is your problem - https://github.com/RocketChat/Rocket.Chat/issues/16174
It's in **ufs** part of your problem user.
But please clarify one thing - do you successfully use users.info REST API endpoint with username input?
I always get 400 Bad request error - https://github.com/RocketChat/Rocket.Chat/issues/17395

**Comment by sistason** [comment]
I see you found the username out for yourself, yeah it worked :)

... wtf is that ticket o.O I don't even... sigh. I wait for upstream fixes, lol. Thanks for the link to that ticket
