### ISSUE TITLE
Push notification settings not working as expected / privacy issue

### ISSUE THREAD

**Issue by rcadmin19** [RocketChat/Rocket.Chat#17135]
### Description:

We analyzed at server side the push notification content which is sent when options:
"Show Channel/Group/Username in Notification" and "Show Message in Notification" are disabled.
We noticed that even if those are disabled, sender, receiver and channel name is sent. Documentation (https://rocket.chat/docs/administrator-guides/notifications/push-notifications/) says that "Show Channel/Group/Username in Notification: Default is “TRUE”, disabling this setting prevents the Channel, Group, Discussion and Username being sent to the push notification gateway"

### Steps to reproduce:

1. Administration/Push/Privacy: Disable "Show Channel/Group/Username in Notification" and "Show Message in Notification". Reboot server.
2. Rocket.Chat populates the "config" variable with a message before sending push notification so we printed "config" variable to console.log(config) and then got the information what was sent.

### Expected behavior:

Push notification should not contain channel/group/usernames in notification content with these settings.

### Actual behavior:
Push notification message contained all of these information:

{
from: 'push',
badge: 3,
sound: 'default',
priority: 10,
title: '',
text: ' ',
payload: {
host: 'https://rocketchatservername',
rid: 'xxxxxxxxxxxxxx',
sender: {
_id: 'xxxxxxxxxxxxxx',
username: 'myuser',
name: 'My User'
},
type: 'p',
name: 'Myprivatechannel',
messageType: undefined,
messageId: 'xxxxxxxxxxxxxx'
},
query: { userId: 'xxxxxxxxxxxxxx' },
notId: -1111111111111,
gcm: {
style: 'inbox',
summaryText: '%n% new messages',
image: 'https://rocketchatservername/images/logo/android-chrome-192x192.png'
},
apn: { category: 'MESSAGE' }
}

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.4
- Operating System: Centos
- Deployment Method: tar
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.14.1
- MongoDB Version: 4.0.16

**Comment by sampaiodiego** [comment]
duplicated of https://github.com/RocketChat/Rocket.Chat/issues/17135

**Comment by JoshMcCullough** [comment]
Working correctly in 3.1.1.

**Comment by vplb** [comment]
It is still affecting us in 3.5.0
The buttons do not change anything. Tried resetting buttons to on, restarting, setting to off, and restarting, the push notifications are still populated with user information.

**Comment by rcadmin19** [comment]
vplb: I can confirm this. It's still sending user and room names on version 3.5.2. This case should be re-opened.
