### ISSUE TITLE
Use new Emoji One icons

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1713]
Emoji One have released their 2016 collection which look a lot nicer than the current emoji. It would be great to see this used in Rocket.Chat.

http://emojione.com

**Comment by k0nsl** [comment]
The new emoji icons look horrible; they are way too yellow. Each and every user on my personal instance said the same thing. I will personally be reverting back.

**Comment by engelgabriel** [comment]
We are using the offiel meteor package, and we and to use the new features of emojione, so we will upgrade this week, once they fix the problem below. 

![image](https://cloud.githubusercontent.com/assets/1000217/11930583/e5b06d56-a7cb-11e5-8bf5-bfeb8475a746.png)

https://github.com/Ranks/emojione/issues/173

We've contributed to this new version to be able to make the dependency on the CDN optional, and allow the use of sprites too. We will also add the feature for searching emojis.

So @k0nsl , I'd advice on not reverting this update. People just need time to get used to the new design. The benefits and new features far outweigh the hassle of keeping an outdated lib.
