### ISSUE TITLE
LiveChat Guest cannot see notification/message when LiveChat Agent initiates video chat

### ISSUE THREAD

**Issue by jimDKE** [RocketChat/Rocket.Chat#17144]
### Description:

Agent starts video chat (we've enabled Jitsi on our server) and the blue "Click to join!" button appears in the agent's electron client, but the guest's livechat window doesn't show anything.  Additionally, I don't see a button in the guest's livechat window to initiate a video call from their end.

So far this doesn't seem to be the same bug that was encountered by these other users in #6529

### Steps to reproduce:

1. Enable Jitsi video conference, test it out between two of our users to verify the video conferencing features works between them.
2. Enable LiveChat and enable the "Video Call Enabled" feature.
3. Add the installation javascript to our public test webpage.
4. Test that basic features of livechat are working (guest can initiate chat, agents see the chat, etc).
5. Use Firefox and Chrome to test whether guest or agent can initiate video chat and whether the other person sees the video chat initiation.

### Expected behavior:

Expected behavior (IMHO) is that a guest should be able to see that an agent has initiated video chat and be able to join that video chat.

### Actual behavior:

In our case, guest couldn't initiate.  Agent could initiate, but guest never saw any message or indication that this had occurred).

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Linux x64 5.3.0-42-generic
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: RocketChat Electron 2.17.7
- Operating System: Windows 10 Enterprise 2016 LTSB x64 Build 14393

### Additional context
LiveChat guest tested on:
Firefox x64 v74.0
Chrome v80.0.3987.149

### Relevant logs:

(I'm looking at gathering relevant logs and will add those soon.)

**Comment by shimisnow** [comment]
I have the same issue.

**Server Setup Information:**

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Linux x64 4.15.0-99-generic
- Deployment Method: manual
- Number of Running Instances: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.3

**Comment by viiy** [comment]
I have same problem.

Current version 3.6.2
Jitsy and bbb activated and tested.

After pressing "call" on operator side, live chat show empty message from operator

**Comment by trialsin** [comment]
Same here! Rocket 3.10.5 over snap

![image](https://user-images.githubusercontent.com/35371595/110140809-3e228600-7db3-11eb-9991-ee5bdf47f6f3.png)

![image](https://user-images.githubusercontent.com/35371595/110140840-467ac100-7db3-11eb-8807-307f8c32399f.png)
