### ISSUE TITLE
Voice notes not visible in threads

### ISSUE THREAD

**Issue by martinszy** [RocketChat/Rocket.Chat#17140]
### Description:
When a voice note is sent from within a thread, the message is invisible and the user has to click into the thread to see there's an audio.

The message was sent forom rocket android and received in rocket web.

### Steps to reproduce:

1. From rocket android start a thread on a text message and reply with a voice note (click the microphone in the bottom)
2. From rocket web see the thread adding a blanck space at the bottom

### Expected behavior:

There should be a representation of the audio message in the thread.

### Actual behavior:

There's a blank space instead of the voice note.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.3
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.14.0
- MongoDB Version: 3.6.15

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Android + Ubuntu

**Comment by 3ter** [comment]
The same _invisibility_ happens for me when somebody answers with an **image**. Only the name of the sender is shown in the chat history.
