### ISSUE TITLE
File Upload Error "Bad Request"

### ISSUE THREAD

**Issue by jwilczek** [RocketChat/Rocket.Chat#17156]
### Description:

After upgrading from 3.0.3 to 3.0.11 we are seeing an issue with file uploads with certain extensions (note extension). Despite having the proper value in the  **Accepted Media Types** filter, certain file extensions generate a "Bad Request" error when dropped  into the chat window for sharing. A good example of this is files with the extension "CSV". As a test, I created a random text file with the extension ".txt". This file will transfer fine. If I take that exact same file and change the extension to ".csv" and retry the upload, I will get a "Bad Request" error. This has nothing to do with the content of the file  as I've tried numerous files with varying content. All work great if the extension is ".txt"  (even executable files), all fail if the extension is ".csv". I see this exact same problem with other file extensions as well, ".7z" for example. There are also others.

### Steps to reproduce:

1. Drag a file with the extension ".csv" onto the Rocket.Chat desktop app or web app to share.

### Expected behavior:

The file to be shared.

### Actual behavior:

"Bad Request" erorr.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.11
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version:4.0.17

### Client Setup Information

- Desktop App or Browser Version: Desktop=2.17.1, Browser=Chrome 80
- Operating System: Windows 10

**Comment by rmaksimov** [comment]
I have the same behavior with 3.0.7. Restarting the rocketchat service has solved the problem

**Comment by gabriellsh** [comment]
The accepted media types does not accept extensions per say, it has to be in a "mimetype" style. I added `text/csv,` to the start of the string and it worked fine. In any case, comment here that I'll reopen this.

**Comment by jwilczek** [comment]
I have "text/*" allowed in my config and am still seeing this error.

**Comment by gabriellsh** [comment]
Can you send the whole setting string so we can take a look?

**Comment by jwilczek** [comment]
Sure!. For what it's worth, this exact string worked perfect prior to upgrading to 3.0.11.

`image/*,audio/*,vidimage/*,audio/*,video/*,application/zip,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/*,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/x-7z-compressedeo/*,application/zip,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document`

**Comment by jwilczek** [comment]
See any issues there?

**Comment by gabriellsh** [comment]
You got `text/plain` before `text/*`. Also, this is duplicated `image/*,audio/*,vidimage/*,audio/*`. You got `text/plain` close to the end too. I don't now if this is the problem, but try removing all invalid formats and duplicated ones, and put `text/*` on the start of the string, just for test reasons.

**Comment by jwilczek** [comment]
Ok, i'm not sure how that happened. Must have been a copy/paste error.

**Comment by gabriellsh** [comment]
Is it working now?
