### ISSUE TITLE
When I run the meteor run ios  , xcode simulate programming blank， ios 9.2

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#1716]
![Uploading Screen Shot 2015-12-21 at 2.52.45 PM.png…]()
![Uploading Screen Shot 2015-12-21 at 2.51.38 PM.png…]()

**Comment by engelgabriel** [comment]
I are not supporting the meteor built of mobile apps anymore, we moved the mobile apps code to https://github.com/RocketChat/Rocket.Chat.Cordova

PS. next time you have to wait for your "Uploading" to complete before submitting the issue :)

![image](https://cloud.githubusercontent.com/assets/1000217/11931015/fdc77c78-a7cf-11e5-9b9c-99c3e183c395.png)
