### ISSUE TITLE
the running instances (count) is not right when we shutdown one instance

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#17165]
### Description:
We used docker-compose to run multiple instances of rocket.chat,but when we docker-compose down one instance ,the runnining instances (count) don't change.
But Broadcast Connected Instances info  is right
### Steps to reproduce:

docker-compose to run multiple instances of rocket.chat, then  docker-compose down one instance

### Expected behavior:

running instances (count) is right

### Actual behavior:
![image](https://user-images.githubusercontent.com/12368358/78467571-9636af80-7740-11ea-961e-37ac5b9bccb6.png)

 

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: ubuntu
- Deployment Method: docker-compose
- Number of Running Instances: 
- DB Replicaset Oplog: true
- NodeJS Version: 8.*
- MongoDB Version: 4.0
![image](https://user-images.githubusercontent.com/12368358/78467585-bcf4e600-7740-11ea-8629-0925baccc9a7.png)

![image](https://user-images.githubusercontent.com/12368358/78467578-a5b5f880-7740-11ea-8fae-62f2f2ceaa0d.png)

**Comment by sampaiodiego** [comment]
this info is generated hourly via a cron job.. you can get updated data by hitting the "refresh" button on the right top corner.
