### ISSUE TITLE
Jitsi call shows click to join even after it has ended

### ISSUE THREAD

**Issue by aryankoul** [RocketChat/Rocket.Chat#17168]
### Description:
Even after a jitsi call is ended, the chat window still shows click to join. This is kind of misleading 

### Steps to reproduce:

1. Start a jitsi call
2. End a jitsi call

### Expected behavior:

It should show that the call has ended in chat window.

### Actual behavior:

It shows click to join in chat window and then shows a toast  displaying the call has already ended if we click on the join icon.

![Screenshot from 2020-04-06 02-38-50](https://user-images.githubusercontent.com/14865238/78510005-cec1a200-77af-11ea-8790-a54d424a8332.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0-develop
- Operating System: Ubuntu
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 4.0.6

**Comment by lequy1010** [comment]
That's a right issues. why does boot auto closed it :(
