### ISSUE TITLE
Can't enable ReplicaSet OpLog

### ISSUE THREAD

**Issue by Gill-Bates** [RocketChat/Rocket.Chat#17164]
Hi there,

this error drives me crazy. I am not able to enable the ReplicaSet. I've followed the manual.

Debian Buster x64, lastest RocketChat Version
MongoDB v4.2.5

```
|             Site URL: http://SLD.TLD:3000/                                |
|     ReplicaSet OpLog: Disabled                                            |
|          Commit Hash: 15ac7670be                                          |
|        Commit Branch: HEAD                                                |
|                                                                           |
|  OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:  |
|  https://go.rocket.chat/i/oplog-required                                  |

```
```
nano /etc/mongod.conf

replication:
  replSetName: rs01

```

> curl -I localhost:3000
> curl: (7) Failed to connect to localhost port 3000: Connection refused

```
sed -i "s/^#  engine:/  engine: wiredTiger/"  /etc/mongod.conf
sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf

```
**Mongo output:**

`rs01:PRIMARY> rs.initiate()
{
        "operationTime" : Timestamp(1586039709, 1),
        "ok" : 0,
        "errmsg" : "already initialized",
        "code" : 23,
        "codeName" : "AlreadyInitialized",
        "$clusterTime" : {
                "clusterTime" : Timestamp(1586039709, 1),
                "signature" : {
                        "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
                        "keyId" : NumberLong(0)
                }
        }
}`

**My Service Config:**

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target mongod.target mongod.service
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=LD_PRELOAD=/opt/Rocket.Chat/programs/server/npm/node_modules/sharp/vendor/lib/libz.so
Environment=NODE_ENV=production
MONGO_OPLOG_URL=mongodb://localhost:27017/local?replSet=rs01
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat
Environment=ROOT_URL=http://SLD.TLD
Environment=PORT=3000
[Install]
WantedBy=multi-user.target

**Comment by robinreinhardt** [comment]
Hey Gill-Bates,

how many members do you have/should have your Replica Set?

**Comment by sampaiodiego** [comment]
you can set an environment variable called `BYPASS_OPLOG_VALIDATION` to use rocket.chat without a replica set, even though this is not recommended and you should use at your own risk..

there are plenty tutorials out there, please try following one of them https://docs.mongodb.com/manual/tutorial/deploy-replica-set/
