### ISSUE TITLE
CloudFront as CDN to S3 upload setting is not working

### ISSUE THREAD

**Issue by kaji-bikash** [RocketChat/Rocket.Chat#17162]
### Description:
This is regarding CDN configuration when RocketChat is configured to have S3 upload settings. The documentation on this is here - https://rocket.chat/docs/administrator-guides/file-upload/amazon-s3/#amazon-s3

### Steps to reproduce:

1. Go to "Administration" settings.
2. Locate "File Upload" and set storage type to be S3 to active "Amazon S3" panel
3. Fill in valid bucket configuration so that uploads are successful and put your CDN URL that already has S3 as backend storage.

### Expected behavior:

- Avatars are served via CDN URL
- User uploads are now served via CDN URL

### Actual behavior:
- Avatars are served via S3 URL
- User uploads are served via S3 URL

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.3
- Operating System: Ubuntu 16.04
- Deployment Method: tar
- Number of Running Instances: 2 processes in the same machine
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.17
- MongoDB Version: 3.6.13

### Relevant screenshot:
![rocketchat_CDN](https://user-images.githubusercontent.com/722803/78450259-522aa880-7675-11ea-8b27-399ac9c78ade.jpg)

**Comment by gabriellsh** [comment]
Have you tried this in a newer version of RC?

**Comment by ceefour** [comment]
I also have this issue: (unfortunately not yet able to test with RC version)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Ubuntu 18.04
- Deployment Method: helm
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.2.6

### Client Setup Information

- Desktop App or Browser Version: Chrome 81
- Operating System: Ubuntu 18.04

**Comment by ceefour** [comment]
BTW @kajisaap are you really using Rocket.Chat 1.3.3 ? Currently Rocket.Chat is 3.1.x so it'd a very old version. Also you're using NodeJS 8 which was already EOL in 2019.

**Comment by ceefour** [comment]
@gabriellsh Issue still reproducible on Rocket.Chat 3.2.0, App engine version: 1.14.0-beta.3119

**Comment by kajisaap** [comment]
@ceefour thanks for confirming the issue and testing it out in a newer version. 

Yes, we are aware of EOL but when things are in production and serving live customers, it is tricky been to be pushing the latest changes as often we like. We also do light theming and integration with other apps so there is an increased risk of change too.

**Comment by gabriellsh** [comment]
I think in the admin rewrite there was a fix for the Avatars to be served through the CDN, not sure what PR though. Also thanks for triaging @ceefour !

**Comment by kiwinesian** [comment]
can confirm that this is still an issue 3.4.2

I can see the file in the S3 (not with the right extension though, just some random filename), but when I copy the "download" link, the download link is still pointing to the registered address, https://subdomain.domain.com instead the CDN link

**Comment by ceefour** [comment]
I second @kiwinesian here.

The **wrong extension** is related, but I think a different bug. It is confusing for users because users expect to download e.g. png, jpg, or pdf, but then the file is not recognized on their computer.

@github-actions @gabriellsh please reopen the bug

**Comment by kiwinesian** [comment]
> I second @kiwinesian here.
> 
> The **wrong extension** is related, but I think a different bug. It is confusing for users because users expect to download e.g. png, jpg, or pdf, but then the file is not recognized on their computer.
> 
> @github-actions @gabriellsh please reopen the bug

ours actually still download the file as is - kinda wondering if I configure it properly.
