### ISSUE TITLE
Error configuring SMTP server with SSL

### ISSUE THREAD

**Issue by jmaister** [RocketChat/Rocket.Chat#17163]
### Description:

Configure SMTP server and sending a test email.

### Steps to reproduce:

1. Go to Administration - Email
2. Configure SMTP parameters with:

smtps
smtp.mail.yahoo.com
port: 587
IgnoreTLS: false
pool: false

3. Send a test email

### Expected behavior:

Expected to receive the test email.

### Actual behavior:

Test email is not sent.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.7
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  12.14.0 - x64  
- MongoDB Version:  4.0.17 

### Client Setup Information

- Desktop App or Browser Version: Browser, Firefox
- Operating System: Windows 10

### Relevant logs:

    rocketchat_1          | Exception in defer callback: [Error: 139794816321344:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
    rocketchat_1          | ] {
    rocketchat_1          |   library: 'SSL routines',
    rocketchat_1          |   function: 'ssl3_get_record',
    rocketchat_1          |   reason: 'wrong version number',
    rocketchat_1          |   code: 'ECONNECTION',
    rocketchat_1          |   command: 'CONN'
    rocketchat_1          | }

**Comment by himpierre** [comment]
Yeah, had that too. Switching to port 465 solved that problem for me for now.
