### ISSUE TITLE
Error: vips2png: unable to write to buffer

### ISSUE THREAD

**Issue by bendem** [RocketChat/Rocket.Chat#17178]
### Description:

I have finally updated our instance from 0.x to 3.0.11 and I've been getting this error in the logs:

```
Error: vips2png: unable to write to buffer
```

### Steps to reproduce:

I have no idea what causes this and there is no stacktrace in the logs, just that error message.

### Expected behavior:

No errors

### Actual behavior:

Well, the error

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Debian 10
- Deployment Method: modified official ansible role (https://github.com/LgHS/Rocket.Chat.Ansible)
- Number of Running Instances: 1
- DB Replicaset Oplog: I don't know what this is
- NodeJS Version: 12
- MongoDB Version: 4.2

### Client Setup Information

- Desktop App or Browser Version: not relevant
- Operating System: not relevant

### Relevant logs:

```
Apr 06 09:07:05 RocketChat[25400]: Exception in callback of async function: [Error: vips2png: unable to write to buffer
Apr 06 09:07:05 RocketChat[25400]: ]
```

**Comment by gabriellsh** [comment]
I did a quick little search and found that this could be related to Sharp (image resizing dependency). You could try to reproduce it by uploading an image. Try to upload different formats of images and see if has any difference (if this is even the cause for it).

**Comment by bendem** [comment]
I have not seen nor been able to reproduce this error since then. I'm going to wild guess that it was due to old images being loaded and that since they have now all been loaded, I won't see the problem ever again.
I'll drop by if it happens again.

**Comment by gabriellsh** [comment]
Thanks for coming back and keeping our issue tracker updated! Hope this doesn't show up again..

**Comment by bendem** [comment]
It has happened again. I still have no idea what's up or why it happens.
![image](https://user-images.githubusercontent.com/2681677/80202720-59b2f100-8626-11ea-9ee4-57d397cdccb5.png)
There are no reverse proxy logs for that time which makes me think it's either an internal process or something triggered by a websocket.

**Comment by sennewood** [comment]
This happend now on 3.11.2 too.
