### ISSUE TITLE
RocketChat server startup CDN environment vars not getting applied

### ISSUE THREAD

**Issue by kajisaap** [RocketChat/Rocket.Chat#17171]
### Description:
This is regarding CDN setting behavior for the RocketChat server.  Looking through the genesis of this configuration in this PR https://github.com/RocketChat/Rocket.Chat/pull/11779 and current state on this affair
- https://github.com/RocketChat/Rocket.Chat/blob/master/app/lib/server/startup/settings.js
- https://github.com/RocketChat/Rocket.Chat/blob/master/app/lib/server/startup/settingsOnLoadCdnPrefix.js

We have rocketchat server in AWS EC2 instances and we have set user upload type to S3. In order to deliver static resources as fast as possible, we are trying to use AWS cloudfront(CDN) service (_with same S3 bucket backend_). To put this in effect, we set the environment variable as follows

```ini
CDN_PREFIX_ALL=xxxxxxxxxx.cloudfront.net
```

### Expected behavior:
This is supposed to work as follows 

"CDN_PREFIX_ALL": "Use CDN Prefix for all assets",

### Actual behavior:

Even with CDN prefix environment variable set, RocketChat still uses signed S3 bucket URL for avatar, user uploads and user rocketchat domain name for meteor's bundled assets.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.3
- Operating System: Ubuntu 16.04
- Deployment Method: tar
- Number of Running Instances: 2 processes in the same machine
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.17
- MongoDB Version: 3.6.13

### Client Setup Information

- Desktop App / Latest Chrome version

### Additional context

How does would it behave in relation to administrative settings in S3 upload setting. I have put a separate issue on this here https://github.com/RocketChat/Rocket.Chat/issues/17162

**Comment by lucasbasquerotto** [comment]
Is this issue solved? I'm using version 3.18 and still seeing the url as the S3 bucket URL for uploaded files, instead of the url defined in the setting **CDN Domain for Downloads** (under the **AmazonS3** subsection in the **File Upload** section).

**Comment by hibobmaster** [comment]
Same here.
Version: 3.18.3
