### ISSUE TITLE
I am always seen as online even if I logout of the app

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#17176]
### Description:

- I am always seen as online even if I logout of the app. My coworker thinks I am online. This gives me very bad impression of not replying to them.

### Steps to reproduce:

1. Login
2. Logout
3. I should be offline to other user.

### Expected behavior:

- I should be offline.

### Actual behavior:

- I am always seen as online even if I logout of the app

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.3
- Operating System: Ubuntu 16.04
- Deployment Method: tar
- Number of Running Instances: 6 EC2 instances
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.17
- MongoDB Version: 3.6.13

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: both mac and window

**Comment by ankar84** [comment]
> * Version of Rocket.Chat Server: 1.3.3

It is too old, try to upgrade first.
