### ISSUE TITLE
Live Chat Feature not updating

### ISSUE THREAD

**Issue by Josh-Riggs** [RocketChat/Rocket.Chat#17179]
We set up a rocketchat server internally with the whole company going home, and it works fairly well. There are a few bugs we are hunting down, but likely a fresh install with other features enabled in a few weeks will fix 99%. In the mean time, it was requested that we spin up the Live Chat feature. This is to be used for some internal queued chat for employees to submit questions to managers while not having to worry about which manager are available. In this process, we have hit a wall.

We got the script to apply to a page. When we attempted to modify the form, it doesn’t update. it wont even change things like color. When we have an agent go live, the form stays on the stuck broken offline form. No text boxes, just the title. While the live chat is disabled, same thing still shows on the widget. I reset all settings to default, still the same thing. At first I thought it was the widget, but when I go to the page listed in the script I get the same broken form. 

Troubleshooting done:
 - We disabled the live chat feature, enabled
 - Reapplied the script on the entirely different servers, hosted and internal. 
 - Restarted rocketchat service
 - Reset all Livechat features to default 
 - Checked the page on the script directly

Version of Rocket.Chat Server: 3.0.2
Debian 9
Number of Running Instances: 1
NodeJS Version: v12.14.0
MongoDB Version: 4.0.16
Proxy: IIS

I don’t know what logs to pull for Live chat. If you know, please tell me and I will gladly pull them

**Comment by renatobecker** [comment]
You just need to enable CORS.

**Comment by Josh-Riggs** [comment]
I enabled it under General > REST API. I am still seeing the same behavior. Is there any other settings I should be looking for?

I checked the rocket.chat documentation, and didn't really see much in the way of it in there. Is there any logs or information I can help provide? I really appreciate your help.

**Comment by renatobecker** [comment]
Do you get any log error on your browser?

**Comment by Josh-Riggs** [comment]
I do not get any errors. The widget pops up, but does not update any of the information. Here is what I see:
![image](https://user-images.githubusercontent.com/61468055/78562586-a35aa980-77e7-11ea-90aa-5345ac873ca9.png)

**Comment by renatobecker** [comment]
> I do not get any errors. The widget pops up, but does not update any of the information. Here is what I see:
> ![image](https://user-images.githubusercontent.com/61468055/78562586-a35aa980-77e7-11ea-90aa-5345ac873ca9.png)

I can't see your console log. Please, share a screenshot of your console log here.

**Comment by Josh-Riggs** [comment]
This is from local source

![image](https://user-images.githubusercontent.com/61468055/78564299-372d7500-77ea-11ea-99b7-16bf8d5fb8e7.png)

**Comment by Josh-Riggs** [comment]
Also, just so it is clear, the script is pointing to the host, not localhost. Internally, we have tried the local hostname, and externally to the proxied name. Both get the same result with localhost being the direction error.

**Comment by renatobecker** [comment]
You need to check the reason to get those errors, like the first `GET` that didn't succeed.

**Comment by Josh-Riggs** [comment]
Sorry for sounding foolish, I'm really a network and Telephony engineer breaking into more dev stuff slowly.  Since this is a prebuilt script inside of the rocketcaht live chat feature, is there a place I can edit to force it to point at the correct location without breaking rocketchat itself?

You had me enable CORS, would setting the CORS orign to proxied hostname name help?

**Comment by renatobecker** [comment]
To get more context about your issue, you'll need to share here your CORS configuration and your server URL.

**Comment by Josh-Riggs** [comment]
hkt-chat.influentinc.com


![image](https://user-images.githubusercontent.com/61468055/78573296-91ccce00-77f6-11ea-85cb-ecaa380a6208.png)

**Comment by renatobecker** [comment]
![Screen Shot 2020-04-06 at 13 41 29](https://user-images.githubusercontent.com/59577424/78582868-5a691c00-780c-11ea-9689-54e1cc45c7c4.png)

What is defined in the `Site URL` setting?

**Comment by Josh-Riggs** [comment]
Site URL:
https://hkt-chat.influentinc.com

**Comment by renatobecker** [comment]
Did you set the `SERVER_URL` environment variable before starting the server?

**Comment by Josh-Riggs** [comment]
If server_url is different from site url, I don't know if it has been set to something different. Checking the site documentation, I only see a piece on overwriting the Site_URL, but not where it is. If it is different, where would be a good place to look?

**Comment by Josh-Riggs** [comment]
Thank you Renatobecker. I ensured all setting were matching with site_url and restarted the service after hours. That seemed to solve the issue, and it is now working.

Thank you again.
