### ISSUE TITLE
MinimongoError: Duplicate _id 'admin'

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#17170]
### Description:
we will meet this error when we logon success.
Uncaught (in promise) MinimongoError: Duplicate _id 'admin'
    at _ (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:133:12683)
    at w.insert (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:133:18215)
    at e.Collection.insert (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:155:6371)
    at e.Collection.o.each.c.Collection.<computed> [as insert] (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:300:2181)
    at e.Collection.<anonymous> (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:302:4773)
    at e.Collection.c.each.r.<computed> [as insert] (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:302:1763)
    at https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:423:406434
    at Array.forEach (<anonymous>)
    at S.<anonymous> (https://39.105.66.15:7777/122ee58274de31e07ceec73f7ff46da8a20cc1b3.js?meteor_js_resource=true:423:406421)

### Steps to reproduce:

we do nothing.

### Expected behavior:

no this bug.

### Server Setup Information:
![image](https://user-images.githubusercontent.com/12368358/78527622-06603680-7810-11ea-870a-48a71d37a96e.png)

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: snap and docker
- Number of Running Instances: 1 and 3
- DB Replicaset Oplog: true
- NodeJS Version: v8.17.0
 

- MongoDB Version:3.6.14 and 4.*

### Client Setup Information

- Desktop App or Browser Version: firefox and chrome
- Operating System:

### Additional context
 GET https://im.icbf.com.cn/api/v1/users.info 400 when we open userlist in a channel (all roles)
{"status":"error","message":"You must be logged in to do this."}

**Comment by pierre-lehnen-rc** [comment]
Do you use LDAP for login?

**Comment by pierre-lehnen-rc** [comment]
Introduced by #15910

**Comment by pierre-lehnen-rc** [comment]
I'll work on this.

**Comment by Totalus** [comment]
I am observing this error as well on an account that was previously `admin` and has been changed to the `user` role.
It prevents the user to read direct messages (message thread is empty).

This applies to the browser app and also observed on the Windows app.
The server is running `rocketchat/rocket.chat:3.3.0` docker image.

**Comment by domhacking** [comment]
Hi @pierre-lehnen-rc Were you able to look into this issue? If so when do you think it will be resolved. Thank you for your help!

**Comment by dkoo761** [comment]
+1

It appears that after signing out, the Minimongo "users" collection on the client is not emptied:

Meteor.users.find().count() // === 1 after signing out

So when the user then tries to login again, Meteor tries to insert their user into the "users" collection, but it's already there.

I think a simple solution would be to remove all documents from the "users" collection on sign out? But maybe there's a reason why that's not desired.

**Comment by Lotfull** [comment]
I am having this issue when trying to login with token to account while already logged to account.
Please, resolve this issue.

**Comment by thorsteinssonh** [comment]
this issue also prevents my first user admin user to change his profile... but no problem doing other activities, changin settings elsewhere than profile and changing password by email.   The profile dialog for this user refuses to change profile quoting wrong password.  Maybe best to create another admin user and use that one instead....?

**Comment by thealek0** [comment]
+1

**Comment by MuhClaren** [comment]
Did anyone fix this one their own, and care to share how?
