### ISSUE TITLE
Making RocketChat Load faster

### ISSUE THREAD

**Issue by kajisaap** [RocketChat/Rocket.Chat#17175]
## Description
We consider ourselves a large installation(**Total connected users peaked** -> 1500,**Messages per minute peaks**  -> 257, **Total users** ->10,000 and increasing).

- Version of Rocket.Chat Server: 1.3.3
- Operating System: Ubuntu 16.04
- Deployment Method: tar
- Number of Running Instances: 6 EC2 instances
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.17
- MongoDB Version: 3.6.13

We have a service-oriented architecture for one of the platforms whereby RC gets called in such a way that DM channel is open in addition to usual channels with high participation(long chat messages, search, etc). One observation we consistently confirm is meteor bundle is too large and too slow to load even from the cache. 

I read in RC forums that the core developers are contemplating moving away from meteor so that the system is much more scalable for larger installation too. In the newer version, it is great that RC does not use subscriptions anymore and has moved some methods from DDP methods to REST endpoints and stop using the Meteor Collections to use Raw Collections for performance reasons. This is a great sign.

![Screen Shot 2020-04-06 at 11 00 32 AM](https://user-images.githubusercontent.com/722803/78550037-4cf76600-77fb-11ea-8acc-5e0f1d5386f6.png)
Fig. Meteor bundle assets

Thanks to Nginx, we are able to serve gzip assets to the clients with proper caching headers and 6.2MB gets reduced to 1.6MB. Yes, it's a significant reduction but still it's a large bundle to download when you have a not so good connection.

![Screen_Shot_2020-04-06_at_10_57_08_AM](https://user-images.githubusercontent.com/722803/78550143-7b754100-77fb-11ea-8c97-e0e9a67fc31b.png)

Fig. Google results on critical paths

Even with bundled assets in cache, RC still takes 2-3 seconds to load stuff because JS is blocking the critical path. All these point to the direction that an effort needs to get directed into slimming the bundle itself. 

I know meteor app is generally considered to be suitable for app scenario where it's okay to load heavy but then provide very good reactivity - _apologies, this could be a novice statement_. Can we re-adjust the scale here by sliming the initial bundle? Have we looked into initiatives like following?
https://www.ninjapixel.io/meteor-bundle-size.html

I think efforts like this will keep current installations(older versions) happy while they start upgrading to the newer/ better versions of the server.

### Additional context

- CDN setting for S3  https://github.com/RocketChat/Rocket.Chat/issues/17162
- CDN environment vars https://github.com/RocketChat/Rocket.Chat/issues/17171

**Comment by sampaiodiego** [comment]
hey.. so we have started already moving some parts of the client code to different bundles. and even though on the most recent version we have added so many new features and even added big libraries like React, the bundle itself is lighter: **5.6MB**
![image](https://user-images.githubusercontent.com/8591547/78799626-c1afd900-7990-11ea-8e00-d9072db2b8ea.png)

we're constantly moving things away from the main bundle while we're moving the UI to React. so expect even more reductions from now on =)

let me ping @ggazzo and @tassoevan so they can give you even more details

**Comment by gabriellsh** [comment]
Hey man, I noticed you've been active recently here and opened a few issues.

Just to reinforce what Diego said, the problems you're facing may be resolved by updating your server to the most recent version, also there's a lot of new features since the version you're in. Feel free to join https://open.rocket.chat/ and take a peak!

**Comment by kajisaap** [comment]
Thanks, @gabriellsh, and @sampaiodiego 

We do a little bit of skinning over vanilla RC and there is also API integration with services so the roll-out bears a risk for us but admittedly not being able to keep up with new releases has been our shortcomings and we are working to improve on that part. Thanks for this and DM support in open.rocket.chat

I will test/validate the bugs reported in other threads using latest version and report back there.
