### ISSUE TITLE
Rocketchat server error

### ISSUE THREAD

**Issue by epurpose917** [RocketChat/Rocket.Chat#17181]
root@chatserver:/home/itadmin# sudo systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor prese
   Active: failed (Result: exit-code) since Mon 2020-04-06 13:43:47 UTC; 6min ag
   Process: 1000 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exi
   Main PID: 1000 (code=exited, status=1/FAILURE)

Apr 06 13:43:47 chatserver rocketchat[1000]:     at Socket.emit (events.js:210:5
Apr 06 13:43:47 chatserver rocketchat[1000]:     at emitErrorNT (internal/stream
Apr 06 13:43:47 chatserver rocketchat[1000]:     at emitErrorAndCloseNT (interna
Apr 06 13:43:47 chatserver rocketchat[1000]:     at processTicksAndRejections (i
Apr 06 13:43:47 chatserver rocketchat[1000]:   name: 'MongoNetworkError',
Apr 06 13:43:47 chatserver rocketchat[1000]:   errorLabels: [ 'TransientTransact
Apr 06 13:43:47 chatserver rocketchat[1000]:   [Symbol(mongoErrorContextSymbol)]
Apr 06 13:43:47 chatserver rocketchat[1000]: }
Apr 06 13:43:47 chatserver systemd[1]: rocketchat.service: Main process exited,
Apr 06 13:43:47 chatserver systemd[1]: rocketchat.service: Failed with result 'e
lines 1-16/16 (END)...skipping...

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
