### ISSUE TITLE
Federation public key TXT record … results in syntax error.

### ISSUE THREAD

**Issue by fooness** [RocketChat/Rocket.Chat#17184]
I’d like to activate Federation on my self-hosted instance and I tried to follow the official docs. What does adding a [Public Key TXT Record](https://rocket.chat/docs/administrator-guides/federation/#public-key-txt-record) mean?

Could you please provide any examples on how to do this? Is this about DKIM records? Or SRV records? Because the TXT record and how it’s described in the docs results in a syntax error …

`rocketchat-public-key.mydomain.com. IN TXT "-----BEGIN PUBLIC KEY-----key123key456…key123key456-----END PUBLIC KEY-----"`

**Comment by alenorcy** [comment]
You need to split.. 

example (bind 9.8) :

rocketchat-public-key.mydomain.com. IN TXT ("-----BEGIN PUBLIC KEY-----XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-----END PUBLIC KEY-----")

**Comment by AlessandroFavretto** [comment]
I Just trying to configure a federated environment and i have same problem on TXT record. I just put:

rocketchat-public-key.chat.dominio01.com       -----BEGIN PUBLIC KEY-----XXX-----END PUBLIC KEY-----

I'm using BIND 9.11.4-P2-RedHat-9.11.4-16.P2.el7_8.6 and i replaced original key with XXX

Just for information, my SRV record has been created like: 
_rocketchat._http IN SRV 1 1 80 chat.dominio01.com.

Regards
