### ISSUE TITLE
Multi-level messaging

### ISSUE THREAD

**Issue by ProdigyMaster** [RocketChat/Rocket.Chat#1718]
What do you think about multi-level messages and reply option? 
![bez tytulu](https://cloud.githubusercontent.com/assets/528501/11929291/fb2fb5d4-a7d9-11e5-895e-9e8fc70624ed.png)

**Comment by engelgabriel** [comment]
We are thinking about this indeed.

The discussion is here https://github.com/RocketChat/Rocket.Chat/issues/1112

Please repost your comment there.

Thanks!
