### ISSUE TITLE
User Data Download disabled - cron still working

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#17199]
### Description:

Hi,
I have disable `User Data Download` via admin settings, but in log every two minutes I see `SyncedCron ➔ info Not running "Generate download files for user data" again.`
It look like it is launched by default `Processing Frequency (Minutes)` = `2`
Change this `Processing Frequency (Minutes)` parameter to other value does not any effect.
In my opinion after disable `User Data Download` cron should not be launched.

### Steps to reproduce:

1. Disable `User Data Download`
2. Check logs
3. `SyncedCron ➔ info Not running "Generate download files for user data" again.` is printed every two minutes

### Expected behavior:

Checking `User Data Download` should be switched off.

### Actual behavior:

`SyncedCron ➔ info Not running "Generate download files for user data" again.` is printed every two minutes

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Centos 7
- Deployment Method: docker compose
- Number of Running Instances: 30
- DB Replicaset Oplog: YES
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.14

**Comment by ankar84** [comment]
FYI,here is my conversation from chat https://open.rocket.chat/channel/support?msg=6LvcEQhjYnxHPiNyY about that problem

**Comment by emikolajczak** [comment]
Hi,
As you said in this conversation. I have enabled `User Data Download`, change `Processing Frequency (Minutes)` and disabled again. I still see every two minutes `SyncedCron ➔ info Not running "Generate download files for user data" again`
