### ISSUE TITLE
Connection unsecure after delay

### ISSUE THREAD

**Issue by juliensl** [RocketChat/Rocket.Chat#17197]
Hi everybody,

### Description:

I installed RocketChat with snap and I am using Caddy to manage the SSL ( refer to this documentation : https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/ )

My problem is, I have a secure connection when I am logging in, I have a secure connection during a time, but after minutes or hours ( I do not know exactly ) with my tab opened, the app switch to an unsafe connection : 
![SSL](https://user-images.githubusercontent.com/43228020/78648954-0c602100-78bd-11ea-8b96-68f6c6cffeff.png)

I do not know why, but if I reload my page, it is secure again.
![sslok](https://user-images.githubusercontent.com/43228020/78649404-b17af980-78bd-11ea-991a-dd0c6d1eb232.png)

### Steps to reproduce:

1. Open your online chat
2. Wait times with the tab opened (maybe hours)
3. See the secure or unsecured locker on your browser

### Expected behavior:

Keep the connection secured all times

### Actual behavior:

Loosing the SSL after time

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: 8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Firefox web browser
- Operating System: Ubuntu

Thank you for your work !

**Comment by gabriellsh** [comment]
Hello! Can you try to run the client for a while with devTools open on the network tab? Then, when the warning appears, try to filter the results by `http:`, it'll show you what is being downloaded without encryption. Please add that info here if possible.

Thanks!
