### ISSUE TITLE
users.setStatus results in 'Cannot read property'

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#17213]
### Description:

Setting the user(s own) status via setStatus results in the error "Cannot read property".

### Steps to reproduce:

1. Install RocketChat Version 3.0.12 or 2.4.2 (others might be affected, too)
2. Create a user auth token,
3. Create a curl request according to the official docs at https://rocket.chat/docs/developer-guides/rest-api/users/setstatus/:

curl -H "X-Auth-Token: XXYYZZ" \
     -H "X-User-Id: specialuseruuid" \
     -d '{"message":"teststatus", "status": "online"}' \
     https://chat.example.com/api/v1/users.setStatus

### Expected behavior:

The users own status changes to online, status message reads "teststatus", curl returns 200 OK.

### Actual behavior:

User status unchanged, curl returns 400 with error:

{"success":false,"error":"Cannot read property 'length' of undefined"}

### Server Setup Information:

- Version of Rocket.Chat Server: Tested on 3.0.12 and 2.4.2 
- Operating System: CentOS7
- Deployment Method: Manual / release package.
- Number of Running Instances: 4
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: cli/curl
- Operating System: Fedora, Debian

### Additional context

*getStatus*  does work, however.

### Relevant logs:

---

**Comment by pierre-lehnen-rc** [comment]
The error was fixed on #17036

In your case you forgot to set the content-type to json, so the API is not receiving the status message.

**Comment by christianreiss** [comment]
You are right, this fixed it. Maybe update the documentation to help others?
