### ISSUE TITLE
Dont show D: as smily 

### ISSUE THREAD

**Issue by lhpitn** [RocketChat/Rocket.Chat#17211]
Hi,

what you see:
![grafik](https://user-images.githubusercontent.com/45788285/78752537-961ef580-7974-11ea-81f3-b7c25f35a82d.png)

What you should see:

PROBLEM: Free disk space is less than 5% on volume D:

thanks in advance

**Comment by lhpitn** [comment]
:D as smily is ok, but D: is sure very very little used as Smiley but as drive letter very common. also you have already :fearful: as a designation for that icon

**Comment by gabriellsh** [comment]
We have plans to completely refactor message rendering, but this could still happen even then. Maybe we need a setting to disable this kind of parsing?
