### ISSUE TITLE
Discusson from direct message fail

### ISSUE THREAD

**Issue by Raboo** [RocketChat/Rocket.Chat#17229]
### Description:

Creating a discussion from a direct message between someone fails.

### Steps to reproduce:

1. Start a direct message with someone. 
2. Press + and create a new discussion.
3. Fill in Name, invite someone, add a message and create.

Boom error!

### Expected behavior:

A discussion is created. Or if a discussion from direct messages are not supported. Then it should not be an option to do so.

### Actual behavior:
Get a red notification box that says `Internal server error`

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.0-rc.11
- Operating System: Lunux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.6

### Client Setup Information

- Desktop App or Browser Version: Firefox 74.0, MacOS client 2.17.9
- Operating System: MacOS

### Relevant logs:

```
I20200408-23:57:37.815(0) Exception while invoking method 'createDiscussion' Error: Meteor requires document _id fields to be non-empty strings or ObjectIDs     at ns.Collection.insert (packages/mongo/collection.js:470:15)     at ns.Collection.Mongo.Collection.<computed> [as insert] (packages/dispatch_run-as-user.js:325:19)     at BaseDb.insert (app/models/server/models/_BaseDb.js:230:33)     at Rooms.insert (app/models/server/models/_Base.js:157:19)     at createDirectRoom (app/lib/server/functions/createDirectRoom.js:43:33)     at createRoom (app/lib/server/functions/createRoom.js:16:10)     at create (app/discussion/server/methods/createDiscussion.js:89:21)     at MethodInvocation.createDiscussion (app/discussion/server/methods/createDiscussion.js:137:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by pierre-lehnen-rc** [comment]
Similar to #17246, may be the same issue.

**Comment by Raboo** [comment]
Could be, except I don't use LDAP, I use Google Oauth.

**Comment by ddxnet** [comment]
the same issue

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/17282

we'll ship a hotfix release including the fix by today
