### ISSUE TITLE
File uploads with 0kb

### ISSUE THREAD

**Issue by ricardoteixeiraduarte** [RocketChat/Rocket.Chat#1722]
Files uploaded to chat are 0kb when downloaded.

**Comment by internalfx** [comment]
Also seeing problems with file uploads...

All the existing uploads are gone too.

on `v0.10.0`

**Comment by engelgabriel** [comment]
Found the problem... we will release 0.10.1 in 5 minutes

**Comment by buckyball** [comment]
+1
0Kb uploads here also, I'm getting a: 

`stream.permissions.read {} `

output when running in console. I have "Protect uploaded files" set to false and everything was working great before I updated to v0.10.0.

Can confirm that already uploaded files could also not be previewed nor downloaded.

Ubuntu 14.04 - deployed without docker, but behind nginx proxy.

**Comment by engelgabriel** [comment]
Should be fixed now.
