### ISSUE TITLE
Custom emoji

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#1723]
It would be nice to be able to add custom emoji, just like how it's done on slack: 
![](http://i.imgur.com/2V8PWHY.png)

**Comment by ywecur** [comment]
:+1:

**Comment by Grinsens** [comment]
Cool :+1: :+1:

**Comment by geekgonecrazy** [comment]
This would be really cool!

**Comment by royalaid** [comment]
+1

**Comment by rebeld** [comment]
:+1:

**Comment by patoupatou** [comment]
This would be awesome!

**Comment by Laisky** [comment]
👍

**Comment by danielclasen** [comment]
+1

**Comment by Lochemage** [comment]
+1

**Comment by Danathus** [comment]
+1 (and with a sizeable team between 50-100 people looking to switch from slack that would much enjoy this feature)

**Comment by edbrady** [comment]
:+1:

**Comment by somerovi** [comment]
:+1:

**Comment by alaroche** [comment]
:+1:

**Comment by tferreira** [comment]
:+1:

**Comment by mattbk** [comment]
+1

**Comment by pluma** [comment]
Dear +1'ers: GitHub now has a "reaction" feature. Just click the "thumbs up" counter below the issue description. If you want to subscribe to update notifications use the subscribe button in the sidebar. Spamming +1 or :+1: only clutters up everyone's inbox.

**Comment by lvh1** [comment]
That would be great @pluma

**Comment by gcassel** [comment]
Since Rocket Chat has emoji now-- thanks so much!--  how about adding a custom emoji function?  

Some people in my teams would especially love that!  

Any word from devs would be greatly appreciated.  :)

**Comment by bazarnew** [comment]
very good tnx
<a href="http://doorgoo.chat">دورگو</a>

**Comment by geekgonecrazy** [comment]
@gcassel custom emoji will require a bit more work.  We'll for sure keep it in mind.   If you'd like to open a Pull Request to add this functionality, it would get done faster :)

**Comment by mikeubis** [comment]
+1

**Comment by bazarnew** [comment]
@geekgonecrazy  it would get done faster

**Comment by heydonfaber** [comment]
Going to try and take a crack at this!

**Comment by pcarn** [comment]
+1

**Comment by nokobon** [comment]
I have come up with a solution. Pull request coming soon if I don't find any issues with my code.

Both custom and default emoji work seamlessly in webhook avatars, reactions, autocomplete, and the emoji picker.

![image](https://cloud.githubusercontent.com/assets/828413/18131644/39c2bf7a-6f59-11e6-9c81-458829c15562.png)

**Comment by tanc** [comment]
Great! Look forward to trying this

**Comment by alexweissman** [comment]
Yesss!  I have so many things I need to emote!

**Comment by geekgonecrazy** [comment]
@nokobon awesome!  Looking forward to testing your changes.  This has been a much desired feature by many!

**Comment by jhagberg** [comment]
Yes we would also like to try this out! Very good for team spirit!

**Comment by 78c59635bdd8** [comment]
We have upgraded to 0.39.  According to the change log, it looks like this version includes the custom emoji code.  However, we are not seeing a custom emoji section in the Admin settings.
![2016-09-09-071637_912x393_scrot](https://cloud.githubusercontent.com/assets/6833993/18386568/7eb8edce-765d-11e6-8cad-939a01a037da.png)

Am I doing something incorrectly?

**Comment by geekgonecrazy** [comment]
Check Permissions and make sure the manage-emoji permission is added to your admin user.  Its possible for some reason it didn't get added.

**Comment by 78c59635bdd8** [comment]
Thanks for the reply.  I don't have a manage-emoji permission option:

![2016-09-09-135058_877x713_scrot](https://cloud.githubusercontent.com/assets/6833993/18398985/ade8f4ae-7694-11e6-989b-280fc9bc3270.png)

**Comment by royalaid** [comment]
I just want to say I am also experiencing problems with custom emoji permissions not appearing

**Comment by geekgonecrazy** [comment]
@rocketchat/core ideas? did a migration not get added?

**Comment by Jan-Ra-wlec** [comment]
Our Server does not have the manage-emoji permission, too. Any solution?

**Comment by cttibbetts** [comment]
This functionality is not in v0.39, it's going to be in v0.40, once that is released, as far as I can tell by looking at release notes and such.

**Comment by Jan-Ra-wlec** [comment]
Uhm... okay. I was already wondering. Thank you. Do you already know a release date for 0.40.0?

**Comment by sampaiodiego** [comment]
It's confirmed missing the permission on 0.39.. the 0.40 should be released on monday.

**Comment by 78c59635bdd8** [comment]
This is working now in 0.40.  Thanks! One question, if we give all users the ability to manage custom emoji, is there a way to track who uploaded what emoji?  Some type of log?  I looked in the rocketchat_custom_emoji mongo collection, but it doesn't seem to show the userid of the person uploading the emoji.

**Comment by royalaid** [comment]
Can also confirm this is now working. Thanks for all the great work guys!

**Comment by Jan-Ra-wlec** [comment]
Same here, already configured our most important Emojis
