### ISSUE TITLE
Docker tag for 3.0.12 not on Docker Hub

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#17236]
### Description:

We're looking to upgrade to the latest non-release-candidate release, which appears to be 3.0.12, but do not see this tag/release on Docker Hub. 

### Steps to reproduce:

1. https://hub.docker.com/_/rocket-chat?tab=tags
2. note that the latest 3.x tag is 3.0.7, but 3.0.12 is the latest release here on GitHub

### Expected behavior:

Non-release-candidate releases on GitHub have a matching tag on Docker Hub, so we can keep up to date with all of the great changes and bug fixes!

### Actual behavior:

Docker Hub is missing tags.

**Comment by gbouthenot** [comment]
You have to use this docker hub account: https://hub.docker.com/r/rocketchat/rocket.chat
The one you use only show tags approved by the docker commitee.

**Comment by JoshMcCullough** [comment]
Wow, my bad -- thanks!
