### ISSUE TITLE
Design similar to Slack

### ISSUE THREAD

**Issue by knokio** [RocketChat/Rocket.Chat#17232]
Hi all. This thread is to discuss/engage in a conversation as if the direction of RocketChat is to be similar in UI/UX to Slack or if the layout is going in other direction?

We are avid users in our organisation but some simple UX/UI issues arise from time to time and I could/want to contribute to solve that.

**Comment by gabriellsh** [comment]
We have a design and lots of things are changing lately. If you have any problem, just open an issue and if you're not sure how to solve it, we can give you a direction through there. Thanks for you concern!
