### ISSUE TITLE
Push Notifications are not working properly

### ISSUE THREAD

**Issue by djschilling** [RocketChat/Rocket.Chat#17233]
Some users are reporting for my rocket chat installation that push notifications are not working for them.
In the log i see this error:

<pre>
Apr 09 15:44:20 chat102 rocketchat[2612]: server.js:204 System ➔ error Error sending push to gateway (5 try) -> Error: failed [400] {"code":108,"error":"bad request sent to apn","requestId":"cb3cd50a-a569-434b-99cf-3d63b95aae88","status":400}
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request._callback (packages/http.js:140:24)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request.self.callback (/var/lib/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request.emit (events.js:311:20)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request.EventEmitter.emit (domain.js:482:12)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request.<anonymous> (/var/lib/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request.emit (events.js:311:20)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Request.EventEmitter.emit (domain.js:482:12)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at IncomingMessage.<anonymous> (/var/lib/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at Object.onceWrapper (events.js:417:28)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at IncomingMessage.emit (events.js:323:22)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at endReadableNT (_stream_readable.js:1204:12)
Apr 09 15:44:20 chat102 rocketchat[2612]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Apr 09 15:44:20 chat102 rocketchat[2612]:   response: {
Apr 09 15:44:20 chat102 rocketchat[2612]:     statusCode: 400,
Apr 09 15:44:20 chat102 rocketchat[2612]:     content: '{"code":108,"error":"bad request sent to apn","requestId":"cb3cd50a-a569-434b-99cf-3d63b95aae88","status":400}\n',
Apr 09 15:44:20 chat102 rocketchat[2612]:     headers: {
Apr 09 15:44:20 chat102 rocketchat[2612]:       'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'access-control-allow-origin': '*',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'access-control-expose-headers': 'Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'cache-control': 'private, no-cache, no-store, must-revalidate',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'content-length': '111',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'content-type': 'application/json; charset=utf-8',
Apr 09 15:44:20 chat102 rocketchat[2612]:       date: 'Thu, 09 Apr 2020 13:44:20 GMT',
Apr 09 15:44:20 chat102 rocketchat[2612]:       expires: '-1',
Apr 09 15:44:20 chat102 rocketchat[2612]:       pragma: 'no-cache',
Apr 09 15:44:20 chat102 rocketchat[2612]:       'x-powered-by': 'Rocket Fuel and Rocketeers',
Apr 09 15:44:20 chat102 rocketchat[2612]:       connection: 'close'
Apr 09 15:44:20 chat102 rocketchat[2612]:     },
Apr 09 15:44:20 chat102 rocketchat[2612]:     data: {
Apr 09 15:44:20 chat102 rocketchat[2612]:       code: 108,
Apr 09 15:44:20 chat102 rocketchat[2612]:       error: 'bad request sent to apn',
Apr 09 15:44:20 chat102 rocketchat[2612]:       requestId: 'cb3cd50a-a569-434b-99cf-3d63b95aae88',
Apr 09 15:44:20 chat102 rocketchat[2612]:       status: 400
Apr 09 15:44:20 chat102 rocketchat[2612]:     }
Apr 09 15:44:20 chat102 rocketchat[2612]:   }
Apr 09 15:44:20 chat102 rocketchat[2612]: }
Apr 09 15:44:20 chat102 rocketchat[2612]: System ➔ info Trying sending push to gateway again in 10000000 milliseconds
</pre>

How can i fix this issue?
I am using the default push gateway.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 1

**Comment by ghalestrilo** [comment]
Can you reproduce this with your own device?
Do you have info on what platform the affected users are using?

**Comment by djschilling** [comment]
With my device it works.

The affected user uses the android app.
If i understand it correctly apn is the Apple Push Service, so this is probably not related to android push problems right?

**Comment by kenkendk** [comment]
I am also running a single instance. Push messages (android+ios) and email notifications stop working after a little while (appx 24h). After this time, I cannot get a single push notification nor email sent. Restarting the RocketChat instance (running in Docker) fixes the problem for a new appx. 24h.

**Comment by sampaiodiego** [comment]
we've revamped push notifications logic a little bit and how they're schedule to be sent on #17357 launched on 3.2.0 release.

I'll close this issue for now, please let me know if you update your server to 3.2+ and keep having this issues.
