### ISSUE TITLE
[BUG] User Avatars broken in 3.1.0 if User Real Name in enabled

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17243]
### Description:

We have on-premise RC deployment with user created from corporate LDAP (Active Directory) where **UserName** it's a **samaccuntname** from LDAP and **Name** it's **Surname Middle-name Name** in LDAP
So we need to use option Admin UI - Layout - User Interface - **User Real Name** enabled, so our users can find each other by normal name or lastname.
After upgrade to 3.1.0 all user avatars in a sidebar was broken.
That because all user avatars are located in `https://rc.company.com/avatar/username` but after upgrade to 3.1.0 and with User Real Name enabled avatars are requested by `https://rc.company.com/avatar/Surname Middle-name Name` which is a obviously wrong URL.

### Steps to reproduce:

1. Set User Real Name to true on pre 3.1.0 version
2. Set user avatard from LDAP
3. Upgrade to 3.1.0
4. No avatars in sidebar

### Expected behavior:

Avatars should by requested by `https://rc.company.com/avatar/username` despite of **User Real Name** setting. 

### Actual behavior:

When User Real Name enabled
![image](https://user-images.githubusercontent.com/4023037/78971276-dc5e8b00-7b13-11ea-8e0c-15da3a69c2dc.png)
![image](https://user-images.githubusercontent.com/4023037/78971301-ea141080-7b13-11ea-9192-bc44062d90b7.png)
![image](https://user-images.githubusercontent.com/4023037/78971317-f6986900-7b13-11ea-99a4-bf072a23f2e7.png)

When User Real Name is disabled
![image](https://user-images.githubusercontent.com/4023037/78971365-1039b080-7b14-11ea-9b53-2fe474800675.png)
![image](https://user-images.githubusercontent.com/4023037/78971390-221b5380-7b14-11ea-914b-e217751e3004.png)
![image](https://user-images.githubusercontent.com/4023037/78971406-29426180-7b14-11ea-9fcd-eca7ab6a61e8.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Ebabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: Windows 10

**Comment by phillipplum** [comment]
This also happens without LDAP. The whole thing happens in the sidebar and top bar. It works in the message list.
When I look in the source code this happens:

Sidebar avatar-url: `/avatar/Phillip%20Plum` (wrong)
Message list: `/avatar/plum` (correct & working)

**Comment by Shaverdoff** [comment]
agree. the same bug.
version the lates as on topicstarter

**Comment by luixxiul** [comment]
FYI #17200 #17252

**Comment by sephentos** [comment]
I can confirm this. Only when the said option is active.

**Comment by aleadco** [comment]
Note that it only happens in the web version and specifically in the sidebar, in any other place where the avatar is displayed there is no error. Also, the android application correctly shows the avatar even after having deleted the cache.
