### ISSUE TITLE
Create an OAuth2 server package

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#1724]
References 

https://github.com/thomseddon/node-oauth2-server

**Comment by engelgabriel** [comment]
https://forums.meteor.com/t/creating-an-oauth2-server/7278

**Comment by engelgabriel** [comment]
https://github.com/awatson1978/hl7-argonaut-fhir/

**Comment by engelgabriel** [comment]
https://www.npmjs.com/package/oauth2orize

**Comment by engelgabriel** [comment]
https://github.com/khanghoang/oauth2-provider/

**Comment by engelgabriel** [comment]
https://github.com/t1msh/node-oauth20-provider

**Comment by graywolf336** [comment]
@engelgabriel don't we already have this right now?

**Comment by SeanPackham** [comment]
We already have this feature https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-oauth2-server-config
