### ISSUE TITLE
404 on click to user in private group to direct message on 3.1.0 RC

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#17247]
### Steps to reproduce:

1. Login
2. Go to private group and click on username
3. get 404 error with rocketchat site

### Expected behavior:

must open direct messages

### Actual behavior:

![изображение](https://user-images.githubusercontent.com/43804710/78986900-6ec75480-7b3d-11ea-8396-dc505c7f1b7b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Centos
- Deployment Method: docker compose
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: Windows, Linux, Mac os

**Comment by himpierre** [comment]
Works for me. Tried in Firefox only.

**Comment by himpierre** [comment]
Also Rocketchat 3.1.0 final.

**Comment by Shaverdoff** [comment]
> 
> 
> Works for me. Tried in Firefox only.

you want to say that you havent this bug? with ldap users?

**Comment by talheim-it** [comment]
@Shaverdoff works for me too. Upgraded now. 

No issues. Would be good to get some log infos.

**Comment by pierre-lehnen-rc** [comment]
Can you replicate this issue consistently? I couldn't replicate it, but I managed to end on the same invalid URL through another process.

**Comment by talheim-it** [comment]
@Shaverdoff do you have any log infos? that can help.

**Comment by himpierre** [comment]
By the way. No LDAP involved on my setup.

**Comment by Shaverdoff** [comment]
I have ldap. Just wait. What and where logs should i collect? From admin pannel? 

Отправлено с iPhone

**Comment by Shaverdoff** [comment]
Set log level to 2. After click on user display name must shown direct but.. we have error 404

I20200410-17:49:06.695(0) server.js:204 Meteor ➔ method createDirectMessage -> userId: 9P8e55njxn2NDMpqX, arguments: ["username"]

May be disable this option click to direct…

 

 

--

Gerasim Shaverdov | Deputy CTO | Altarix 

Mobile:  <tel:+7%20937%20070%2066%2084> +7 937 070 66 84 | Skype/email:  <mailto:gerasim@altarix.ru> gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by Shaverdoff** [comment]
Was Disable setting in Layout/User interface - Click to Create Direct Message and now its ok. But is not right. 

In 3/0/7 there was no such behavior

 

 

--

Gerasim Shaverdov | Deputy CTO | Altarix 

Mobile:  <tel:+7%20937%20070%2066%2084> +7 937 070 66 84 | Skype/email:  <mailto:gerasim@altarix.ru> gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by sephentos** [comment]
I can confirm this bug. It only happens when you activate the option that the direct message channel opens instead of the info panel when clicking on a @tagged user name
