### ISSUE TITLE
Rocket.Chat displays 'You must join to view messages in this channel' for guest users on Discussions

### ISSUE THREAD

**Issue by luixxiul** [RocketChat/Rocket.Chat#17244]
### Description:

The bug is similar to https://github.com/RocketChat/Rocket.Chat/issues/14425.

> Rocket.Chat displays the 'You must join to view messages in this channel' banner for guest users even though they're subscribed to the channel and can view and send messages.

This one happens on **Discussions** to which the channel, where the guest user was added, links.

### Steps to reproduce:

The bug is similar to https://github.com/RocketChat/Rocket.Chat/issues/14425.

1. Create a guest user.
2. Make sure that `allow anonymous read` is not globally enabled and that the guest group does not have the `preview-c-room` permission.
3. Add the guest user to a channel.
4. Open Discussions.
5. Select any one.

### Expected behavior:

The discussion should either be hidden based on a setting or the banner should not be displayed

### Actual behavior:

![Clipboard01](https://user-images.githubusercontent.com/3362943/78975739-466f3400-7b04-11ea-8f80-0c011bbf7b6c.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.7 f69d16950d87bbae4991498889b86fa5ed014feb
- Operating System: Debian 10
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Desktop App 2.17.7
- Operating System: Windows 10

**Comment by luixxiul** [comment]
I am not quite if the issue consistently can be reproduced. It might be just related with cache.

**Comment by gabriellsh** [comment]
Were you able to reproduce this?

**Comment by luixxiul** [comment]
I have not tried again as it is on production site and I do not want to use that for reproducing the issue if it exists.

**Comment by luixxiul** [comment]
It looks the issue has not been reproduced. I will reopen if I start to see this again.
