### ISSUE TITLE
Can't use direct URLs if not logged in

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#17251]
### Description:

Accessing any resource on the chat through a direct URL does not work if the user isn't logged in yet. Only "https://domain.com" and "https://domain.com/home" works. If a direct URL is visited such as "https://domain.com/channel/employees" or "https://domain.com/direct/user", it keeps loading and never loads the page.

### Steps to reproduce:

1. Be logged out and use a fresh browser session.
2. Visit a direct URL on the chat as described above that is not the home URL.
3. The page will not load.

### Expected behavior:

The page should load successfully, if the user does not have permission to view the page an error message should be displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Ubuntu
- Deployment Method: Docker-compose
- Number of Running Instances: 1
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6

### Relevant logs:

The server only outputs the following log:

`rocketchat_1          | Meteor ➔ publish null -> userId: null, arguments: []
rocketchat_1          | Meteor ➔ method loadLocale -> userId: null, arguments: ["sv"]
rocketchat_1          | Meteor ➔ method public-settings/get -> userId: null, arguments: []
rocketchat_1          | Meteor ➔ method rooms/get -> userId: null, arguments: []
`

**Comment by pierre-lehnen-rc** [comment]
I couldn't replicate the issue. Do you have any logs on the client side that may help identify the problem?

**Comment by cchbr** [comment]
I set up v.3.1.0 on a dev server to test it there and for channels it loads as it should and offers the user to log in at the bottom. I'll test it some more but it could be solved in the latest version for channels. 

For users though I get the page "Invalid room", and "Invalid user" popup messages. Perhaps there isn't support for accessing users/direct messages for logged out users yet. It would be preferable if it prompted the user to log in, instead of all the error messages.
