### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by mfa777** [RocketChat/Rocket.Chat#17253]
### Description:

The instance runs well, but there is a same error in the log.

```
 I20200411-03:19:31.260(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: 2tsCvq9r2AZPHnLSPTZaGDMJWcdau8uwPj 
I20200411-03:19:31.263(0) Exception in defer callback: TypeError: Cannot read property 'filter' of undefined     at RocketChatIntegrationHandler.getTriggersToExecute (app/integrations/server/lib/triggerHandler.js:505:16)     at RocketChatIntegrationHandler.executeTriggers (app/integrations/server/lib/triggerHandler.js:576:34)     at _wrapperFunction (app/integrations/server/triggers.js:6:38)     at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at app/callbacks/lib/callbacks.js:45:45     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at app/lib/server/functions/sendMessage.js:243:32     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)  
```

### Steps to reproduce:

I am not sure what step make this error. it seems related with some broken room which i don't know. When there is many users login, it happened frequently.

### Expected behavior:

No error log.

### Actual behavior:

https://i.imgur.com/66N7nks.png

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.0
- Operating System: ubuntu 16.04
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: 1
- NodeJS Version: v12.16.1
- MongoDB Version:4.0.17

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Windows

### Additional context

I run a test instance using the same database dump, but only me was logged in. it didn't show error.

This instance run years, it keep updating begin from very old version.

### Relevant logs:

Above showed

**Comment by ggazzo** [comment]
look at your collections, again the same problem related [here](https://github.com/RocketChat/Rocket.Chat/issues/17260), somehow your direct messages are missing `uids` field, do you remember if everything went well with your migrations? migration number 179 should be responsible for creating this field
