### ISSUE TITLE
Visitor Information triggered in omnichannel

### ISSUE THREAD

**Issue by jstemplewski** [RocketChat/Rocket.Chat#17255]
### Description:

Every message from livechat/omnichannel triggers visitor information window.

### Steps to reproduce:

1. Send message from livechat widget
2. Close visitor information window
3. Send response or get another message

### Expected behavior:

Closed window shouldn't appear after subsequent messages.

### Actual behavior:

Visitor information window shows after every message.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Ubuntu Linux 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: Desktop App 2.17.9
- Operating System: Windows 10

**Comment by renatobecker** [comment]
@jstemplewski It would be nice if you share a video recording describing this case.
I just can't reproduce it, thanks.

**Comment by jstemplewski** [comment]
Video attached.

![visitorinfo](https://user-images.githubusercontent.com/58255240/79048501-c4732e00-7c1d-11ea-916d-1485d63f234b.gif)

**Comment by renatobecker** [comment]
Closes by https://github.com/RocketChat/Rocket.Chat/pull/17348.
