### ISSUE TITLE
All other users are offline when login

### ISSUE THREAD

**Issue by mfa777** [RocketChat/Rocket.Chat#17260]
### Description:

After I upgrade to 3.1.0, All other users show offline. There is two way I can show online back:

1. click the others name to check user info, the status will turn from offline to online
2. click members list in a channel, then all the online users will turn from offline to online

Then If I refresh website from browser, all the users become offline again.

**This GIF show the problem:** https://imgur.com/2T7Egor

### Steps to reproduce:

1. login
2. all others is offline
3. click member in any channel
4. the online users come out

### Expected behavior:

After login, all the users show the correct status.

### Actual behavior:
After login, all others is offline

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: ubuntu 16.04
- Deployment Method: Docker
- Number of Running Instances: 1 or 2
- DB Replicaset Oplog: true
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome, Firefox, Windows APP all the same
- Operating System:Windows

### Additional context
This instance was updated from a very old version.

### Relevant logs:
no Error logs shows.

**Comment by ggazzo** [comment]
hey @mfa777 could you check on the DB the room collection if your dms have 'uids' field?
