### ISSUE TITLE
Notification to members in new private group

### ISSUE THREAD

**Issue by jinnear** [RocketChat/Rocket.Chat#1727]
If a user creates a new private group and chooses to add other users to the group in the group creation dialog, these users don't receive a notification. The room is only added to their list of private groups (-> "More private groups ..") so they can manually open it. If a user is invited into an existing private group however, they do get notified.

I think there should be notifications in both cases, otherwise a user might not even notice that they were added to a group. Maybe there's a better solution but I think that the behaviour should probably be the same in both cases. Any thoughts on that?

**Comment by graywolf336** [comment]
This has become an increasing problem with one of my instances of Rocket.Chat

**Comment by yumben-yf** [comment]
The workaround is to perform a 'mention all members' in that group after creating it.

**Comment by rodorgas** [comment]
Notification received by adding a member to an existing group is due to a new message sent to group:

<img width="546" alt="captura de tela 2017-10-25 as 17 42 32" src="https://user-images.githubusercontent.com/8618619/32019501-38d3e956-b9ac-11e7-97c6-544014e137bc.png">

It wouldn't be nice throw this messages on group creation (e.g. if you add 20 members on creation, you'd spam 20 messages). I believe we should have a type of message that is only displayed to a specific user. Is there something like that? So we could send "You were added to this conversation", that would trigger a notification, but only the user added could see this message.

An easier fix would be send a message " @/all: You were added to this channel" and keep the current behaviour for added users after creation.

**Comment by engelgabriel** [comment]
@sampaiodiego @alansikora @ggazzo @rodrigok We will need to do this when turning all the room events into system messages. We should probably have an option to have an ADD TO ROOM message that accepts an ARRAY of users, to keep it into a single message on the start of the channel.

**Comment by engelgabriel** [comment]
After discussing with the team, I think that this is actually a feature and not a bug. 😃 

I'd hate to be added to a channel and get a notification, only to go to the channel and see that it is empty and there is nothing for me to read. If the user that created the channel believes it is important for me to know that the channel exists and what it is about, they SHOULD send a message like `@all  let's talk about the new logo` and get the conversation started.

**Comment by smcardle** [comment]
Hi everybody....
Just wanted to chip in here regarding this functionality as we have a specific use-case where it is pretty much required......

Why is this closed ???

The following comment, in my opinion, is your "opinion" not a solution. (pun intended by the way)

> After discussing with the team, I think that this is actually a feature and not a bug. 😃
> 
> I'd hate to be added to a channel and get a notification, only to go to the channel and see that it is empty and there is nothing for me to read. If the user that created the channel believes it is important for me to know that the channel exists and what it is about, they SHOULD send a message like `@all let's talk about the new logo` and get the conversation started.

You may well hate this functionality but we would like it, and in one case probably need it....
This ability to notify a user when they are added to a room/group should be a configuration option by an admin and selectable by each user.... something like "DON'T notify me when I'm added to a private group"

We have a use-case that pretty much needs this exact functionality to implement....
In our case we have an outgoing webhook that fires each time a messages is added to a private group.
If it's the FIRST message in the group then a specified set of users are ADDED to the group. How these users are retrieved is via a completely different REST API to another part of our stack.

However, none of the added users are notified at this point and thus do not get alerted via the mobile app.

The reason we do it this way is precisely to STOP the private group showing up in the "invited" users private groups list until there is AT LEAST one message for them to be interested in.

I also cannot find any RC REST API endpoint that will allow me to force a notification without needing to add a NEW message AFTER the invite has been done.

As I said, forcing your opinions on how you 'think" a feature should work isn't always a good approach. 
Candidates for notifications are system events that people MAY be interested in and should have configurable defaults setup by the admin user and then each user can select WHICH notifications they are either interested or not interested in.


Steve
