### ISSUE TITLE
Avatar display error in version 3.1.0

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#17271]
### Description:

Avatar not displayed correctly after upgrading to 3.1.0

### Actual behavior:

Each user can view their own avatar on the web interface but not that of other users. This error appears after having updated to version 3.1.0

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome, Firefox

### Additional context

It was tested by clearing the cache. An attempt was made to load a new avatar and there are also display errors in this process.

![Anotación 2020-04-12 141400](https://user-images.githubusercontent.com/35962168/79077266-4f136600-7cce-11ea-9215-fc13be3d0564.jpg)

**Comment by aleadco** [comment]
![Anotación 2020-04-12 141400](https://user-images.githubusercontent.com/35962168/79077203-b977d680-7ccd-11ea-9d42-214709265d13.jpg)

**Comment by robinreinhardt** [comment]
If you have User Real Name enabled maybe it's related to #17243

**Comment by aleadco** [comment]
yes @robinreinhardt I have checked it and it is exactly that error, hopefully it can be solved soon.

**Comment by aleadco** [comment]
Note that it only happens in the web version, the android application correctly shows the avatar even after having deleted the cache.

**Comment by luixxiul** [comment]
so maybe this issue should be closed in favor of #17243?
