### ISSUE TITLE
SAML assertion signature required after 3.1.0

### ISSUE THREAD

**Issue by Exordian** [RocketChat/Rocket.Chat#17277]
### Description:

SAML responses can be signed in multiple different ways:
* Sign the whole message (only)
* Sign only the assertions
* Sign the assertions and the message afterwards

We used to have "sign the whole message" since the assertions are part of the message anyway. This behaviour was fine before 3.1.0. After https://github.com/RocketChat/Rocket.Chat/pull/16922 it is required to have signed assertions.

This behaviour was quite nasty to find:
* The PR https://github.com/RocketChat/Rocket.Chat/pull/16922 does not mention what has been fixed. It only states it fixed something or what was wrong (i'm missing the issue).
* I expect the FIX not to break fine behaviour (from a security perspective). If breaking changes are required (since the behaviour was bad/broken before from a security perspective) I would suggest adding such fixed to the "breaking changes" section. Since it may break existing (insecure) environments.
* The error message is quite misleading:
```
Apr 13 15:05:31 chat docker[12420]:     at app/meteor-accounts-saml/server/saml_server.js:710:3
Apr 13 15:05:31 chat docker[12420]:     at middleware (app/meteor-accounts-saml/server/saml_server.js:663:11)
Apr 13 15:05:31 chat docker[12420]:     at SAML.validateResponse (app/meteor-accounts-saml/server/saml_utils.js:649:10)
Apr 13 15:05:31 chat docker[12420]:     at app/meteor-accounts-saml/server/saml_server.js:665:13
Apr 13 15:05:31 chat docker[12420]: Error: Unable to validate response url: TypeError: Cannot read property 'toString' of null
```
It's not the response url which is invalid, it's the missing signture.

### Steps to reproduce:

1. Install RocketChat 3.1.0
2. Add a SAML IdP that signs the document but not the assertions
3. see the error message above

### Expected behavior:

Login works fine

### Actual behavior:

redirect to login page without any error (for the user) and a stacktrace in the server logs (see above)

### Fix possibilities (IMHO)
* https://github.com/RocketChat/Rocket.Chat/pull/16922/files#diff-454fb2bc258d50f4e0f0966458ea35d7R575 - ignore assertion signature if the document signature is fine (as well as the other way round)
* update the documentation to require always a signed document and signed assertions (this may break compatibility with some SAML servers. i'm using keycloak which supports all three behaviours)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.0
- Operating System: offical container
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes

### Client Setup Information

- Desktop App or Browser Version: unrelated
- Operating System: unrelated

**Comment by cb3inco** [comment]
I to have this problem and trying to back down my install, but seems to be some trouble in doing this.
