### ISSUE TITLE
Twillio Whatsapp (sms) integration wouldn't send PDFs and other important formats

### ISSUE THREAD

**Issue by richieri** [RocketChat/Rocket.Chat#17270]
Hi!

Analysing the following code, it seems to be impossible to the "visitor" send PDFs since mime is application/pdf

https://github.com/RocketChat/Rocket.Chat/blob/a102c6fb4b023c0970d4306ef0442a69757264b8/app/livechat/imports/server/rest/sms.js#L86

I'm currently developing a similar integration for other provider and I'm facing this issue as well.

**Comment by jersonjunior** [comment]
I'm also implementing another provider, I can already receive messages. I'm looking for the sending part, could you help me where can I find the sending part of the messages?

**Comment by antkaz** [comment]
It doesn't work now
