### ISSUE TITLE
Snap update to Version 3

### ISSUE THREAD

**Issue by Vkat14** [RocketChat/Rocket.Chat#17279]
Hi Team,

Snap install is currently on 2.4.11(February 27th). Are there any issues with updating this to Version 3? In general, i am finding the snap updates happen very late.

**Comment by stewmystre** [comment]
You could always change snap tracks to 3.x stable which is currently at 3.0.10, check this out if you haven't already https://forums.rocket.chat/t/introducing-snap-tracks/5890

**Comment by Vkat14** [comment]
> 
> 
> You could always change snap tracks to 3.x stable which is currently at 3.0.10, check this out if you haven't already https://forums.rocket.chat/t/introducing-snap-tracks/5890

stewmystre, thank you for this share. I was not aware of it. Will try it out

Doesn't this defeat the purpose of traditional snap though? If there is a stable release, snap repo should just be updated to show that version. I do like the flexibility they are offering for people who are interested in trying Candidate versions but for people who want to set it and forget, stable releases should be pushed to snap as they happen without having to go the tracks route. Right now, i see Rocket chat is on version 3.1.0(released 5 days ago)

3.0 came out in Feb and 2 months later snap repo still shows 2.4.11. At a minimum snap should just be one or two Verified versions behind the latest release.

**Comment by stewmystre** [comment]
Hey Vkat14, I'm with you on this, I only know about the snap-tracks because I was asking the same question and found this question on the forums: https://forums.rocket.chat/t/why-is-the-snap-image-so-out-of-date/6394 which led to the snap track knowledge. Since I last looked at the forum question, it has had a response from one of the rocket,chat team that provides some brief reasoning for the delay. I'm interested to see what their response to this issue is as you make some good points.

**Comment by geekgonecrazy** [comment]
We will be releasing 3.0 to the latest.  We’ve been trying to give people a chance to start using tracks first.  We’ve had lots of requests to be able to prevent refreshes.  So for those people this is their chance to switch to 2.x track to prevent auto updating to 3.0.
  

Unfortunately a lot of people I guess consume and never look at community so probably won’t know until they come back to complain about being auto updated to 3.x :) oh well still we want to have given them that chance.

Don’t fear though.. it will come back to being pushed on latest channel.

**Comment by BO41** [comment]
any ETA?
This week, this month, with `3.2.2`?

**Comment by Maqsyo** [comment]
Could you say any date when the auto-update will happen?
