### ISSUE TITLE
Cannot invite user to federated room

### ISSUE THREAD

**Issue by ndroo** [RocketChat/Rocket.Chat#17273]
Using RC 3.0.10

Unless I've first had a direct message conversation between two users across federated servers, i cannot invite users into my federated channels.

Steps to reproduce:

1. Setup 2 servers via federation (Server A and Server B. Server A must contain 1 User, Server B must contain 2 users)
2. Log onto Server A using User 1
3. From Server A, lookup User 1 from Server B and create a private conversation
4. Create a new private channel on server A and invite User 1 from Server B

>> At this point you should have two channels in server A
* Direct message between User 1 from Server A and User 1 from Server B
* Private Channel between User 1 from Server A and User 1 from Server B

5. Log onto Server B using User 1
6. Go to the Federate Private channel that has been created between User 1 from Server B and User 1 from Server A
7. Try and invite User 2 from Server B into the federated channel (This will fail, this is the bug!)

You will see in the logs

>>
server.js:204 Federation ➔ client.error afterAddedToRoom => Could not add user: TypeError: Cannot read property 'origin' of undefined
    at app/federation/server/hooks/afterAddedToRoom.js:48:58
    at Array.map (<anonymous>)
    at app/federation/server/hooks/afterAddedToRoom.js:48:34
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

This is because User 2 from Server B does not exist on Server A.

To make it work anyway... 
1. Log onto Server A
2. Lookup User 2 on Server B and create a direct message conversation
3. Redo Steps 5-7 from above, it now works.

I think we just need step 7 from above to create the user on the peer server(s) when doing the invite in order to resolve this issue.

**Comment by ndroo** [comment]
I think this is related to #16396

**Comment by 1rV1N-git** [comment]
Hello.
Use 3.0.10 
https://github.com/RocketChat/Rocket.Chat/pull/16878

**Comment by ndroo** [comment]
The fact i'm using 3.0.10 is literally the first line of my bug report @1rV1N-git.

**Comment by 1rV1N-git** [comment]
@1rV1N-git 
sorry 3.1.0

**Comment by ndroo** [comment]
Oh? if this is actually fixed there ill work towards merging that in on our side. I couldn't find any indication that the upgrade would help though?

**Comment by 1rV1N-git** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/16878

**Comment by ndroo** [comment]
Can you point at the specific commit? If you're talking about the typo commit (https://github.com/RocketChat/Rocket.Chat/commit/ccec1027fd223ccdcc8bc1e48fc2e3e90411b461) this is already merged into 3.0.10. So i still think i'm reporting a new issue.

**Comment by 1rV1N-git** [comment]
hm. Maybe it is another bug.

**Comment by ndroo** [comment]
Yeah agreed.

**Comment by ndroo** [comment]
So i looked into this, the issue is the user being added (Server B, user 2) doesnt have the federation attribute on their user object, because they're just a local (non federated) user at this time.

This is happening on this line.
>> const domainsAfterAdd = users.map((u) => u.federation.origin);

I wrote a bit of code that deals with this and resolves the issue i've encountered, i'll submit a PR shortly.

**Comment by gnmancini** [comment]
@ndroo 
I have two servers and one dedicated dns for test purposes. The Federation Test works fine but I can not invite users from the federated domain, is this the same error you reported?
My tests domains are configured in the same way and I have the same result on each way.

![Screenshot from 2020-04-15 17-00-04](https://user-images.githubusercontent.com/22837075/79359709-d36a2100-7f3a-11ea-8d17-c179acf968ac.png)
![Screenshot from 2020-04-15 17-00-39](https://user-images.githubusercontent.com/22837075/79359724-d82ed500-7f3a-11ea-9fc1-be03664efc16.png)
![Screenshot from 2020-04-15 17-00-47](https://user-images.githubusercontent.com/22837075/79359735-db29c580-7f3a-11ea-84e9-c7aa49cf14f9.png)

**Comment by ndroo** [comment]
This has been solved in a PR we're going to be sending over in a few days. Please see my comments in the rocketchat federated room channel for more info (messages dated april 18th 2020).
