### ISSUE TITLE
[3.1.0] error-invalid-room after room creation with LDAP logged admin

### ISSUE THREAD

**Issue by CodazziS** [RocketChat/Rocket.Chat#17296]
### Description:

After creating a new private room, we can't open the room. We need to logout / login for join the room.

### Steps to reproduce:

1. With an admin *LDAP* account, create new private room.
2. When room is created, the url change for open the room, and an error message invalid room appear.
2. With a logout / login, we can join the room

### Expected behavior:

The room must appear without error. Room creation work with a regular admin (non-ldap logged).

### Actual behavior:

- step 1:
![image](https://user-images.githubusercontent.com/8134250/79223695-1e603780-7e5a-11ea-9838-fd658ef16099.png)
- step 2: 
![image](https://user-images.githubusercontent.com/8134250/79223802-4f406c80-7e5a-11ea-918a-0cef7b0bca62.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.2
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Ubuntu

### Additional context

Admin user is logged with LDAP

### Relevant logs:

- client console error:
```{isClientSafe: true, error: "error-invalid-room", reason: "Invalid room", details: {…}, message: "Invalid room [error-invalid-room]", …}
details: {method: "canAccessRoom"}
error: "error-invalid-room"
errorType: "Meteor.Error"
isClientSafe: true
message: "Invalid room [error-invalid-room]"
reason: "Invalid room"```
- No error for server

**Comment by rodrigok** [comment]
@CodazziS this will be solved by https://github.com/RocketChat/Rocket.Chat/pull/17282 on version 3.1.1
