### ISSUE TITLE
Error with federation search user

### ISSUE THREAD

**Issue by Stanymanman** [RocketChat/Rocket.Chat#17293]
### Description:

There is an error in federation user search.
In log we have 503 "service unavalaible" for federation and an error in red on screen on search "can't find user via HUB or DNS" in 3.1.0 (I don't have the exact message because I do a rollback quickly).
But the user search seems to be working.

### Server Setup Information:

Server Setup Information:
Version of Rocket.Chat Server: 3.0.12
Operating System: Ubuntu Server 18.04
Deployment Method: Manual Install
Number of Running Instances: 2
NodeJS Version: 12.14.0
MongoDB Version: 4.0.17

### Log

server.js:204 Federation ➔ dns.error Error: failed [503] Service Unavailable     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:210:5)     at Request.EventEmitter.emit (domain.js:475:20)     at Request.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:210:5)     at Request.EventEmitter.emit (domain.js:475:20)     at IncomingMessage.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:299:28)     at IncomingMessage.emit (events.js:215:7)     at IncomingMessage.EventEmitter.emit (domain.js:475:20)     at endReadableNT (_stream_readable.js:1184:12)     at processTicksAndRejections (internal/process/task_queues.js:80:21) {   response: {     statusCode: 503,     content: 'Service Unavailable',     headers: {       date: 'Tue, 14 Apr 2020 10:14:27 GMT',       'content-length': '19',       'content-type': 'text/plain; charset=utf-8',       connection: 'close'     },     data: null   } }

**Comment by ankar84** [comment]
Is Federation test is successful?

**Comment by Stanymanman** [comment]
Yes federation test is OK and I can find users in remote instance.

**Comment by gnmancini** [comment]
Look like the same issue I've reported... https://github.com/RocketChat/Rocket.Chat/issues/17314
