### ISSUE TITLE
Video call push notification get null body

### ISSUE THREAD

**Issue by shreekarade** [RocketChat/Rocket.Chat#17292]
I have using RC version  3.0.9 and recently upgraded. 

When I initiate jitisi video call from RC, then I will get body null in the push notification. Please somebody help me.

Please check attachment 
![1585657978566](https://user-images.githubusercontent.com/36290412/79201534-d93a0680-7e55-11ea-9ad3-98c116b32327.JPEG)

**Comment by gabriellsh** [comment]
We need some more info so we can help. Like what smartphone you're using, app version, etc.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
