### ISSUE TITLE
Feature Request: Define personal working hours in the app

### ISSUE THREAD

**Issue by sennewood** [RocketChat/Rocket.Chat#17301]
We use Rocket.Chat in our organisation and it would be nice to be able to define a personal time window, when it's okay to recieve push notifications. Most of the time, messages send after 8 p.m. are fine to be read the next day.

**Comment by pedropilla** [comment]
Yes, I miss this control too.

**Comment by Maroin** [comment]
I need it too :)

**Comment by krumelmonster** [comment]
We need it too and it's as well been much requested in https://github.com/RocketChat/Rocket.Chat/pull/8806 also with regard to teams of multiple timezones.
I would suggest to introduce a "Do Not Disturb" mode that when active postpones all notifications (Desktop, Mobile, Email). This mode could be controlled manually from the status menu and using a timetable configured in the user preferences. It should be possible to configure DND-times by weekday.

Please reopen
