### ISSUE TITLE
Build and Test on Github fails at build-image-pr

### ISSUE THREAD

**Issue by qwertiko** [RocketChat/Rocket.Chat#17306]
### Description:

build-image-pr on github fails repeatedly at "Build Docker image for PRs" with error:
denied: Resource not accessible by integration
##[error]Process completed with exit code 1.

### Steps to reproduce:

1. Create new pull request
2. Let the auto build and test suite run

### Expected behavior:

The integration test finishes successfully

### Actual behavior:

The integration test fails with access failure.

### Relevant logs:

Except from build-image-pr at step "Build Docker image for PRs":

 Step 9/10 : EXPOSE 3000
 ---> Running in 72b4c20236c1
Removing intermediate container 72b4c20236c1
 ---> e417fffc4b50
Step 10/10 : CMD ["node", "main.js"]
 ---> Running in 515050a66bf0
Removing intermediate container 515050a66bf0
 ---> 3dc481828a45
Successfully built 3dc481828a45
Successfully tagged docker.pkg.github.com/rocketchat/rocket.chat/rocket.chat:pr-16430
The push refers to repository [docker.pkg.github.com/rocketchat/rocket.chat/rocket.chat]
a7acdaba9313: Preparing
2c4edf051dec: Preparing
430c0c0c04ea: Preparing
a60dd2539360: Preparing
30e8a2fe960c: Preparing
2c995a2087c1: Preparing
2c995a2087c1: Waiting
a60dd2539360: Layer already exists
430c0c0c04ea: Layer already exists
30e8a2fe960c: Layer already exists
2c995a2087c1: Layer already exists
denied: Resource not accessible by integration
##[error]Process completed with exit code 1.

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/17370
