### ISSUE TITLE
Performance problem using Gridfs

### ISSUE THREAD

**Issue by lazyants** [RocketChat/Rocket.Chat#17309]
### Description:

We are using GridFS as file storage and get huge performance problems. The size of rocketchat_uploads.chunks is around 12.5 GB and the table has more than 28k entries.
However It can be fixed by just adding the following index:

```
db.rocketchat_uploads.chunks.createIndex( { files_id: 1, n: 1 }, { unique: true } )
```

### Upload with the added index 

<img width="1150" alt="Bildschirmfoto 2020-04-15 um 13 13 59" src="https://user-images.githubusercontent.com/249065/79331350-4ebbda80-7f1b-11ea-968a-2149dea40ebe.png">

### Upload without index

<img width="1150" alt="Bildschirmfoto 2020-04-15 um 13 15 03" src="https://user-images.githubusercontent.com/249065/79331383-57acac00-7f1b-11ea-8856-759e473d5c9d.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.10
- Operating System: Ubuntu 18.4
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: macOS Catalina

**Comment by progressify** [comment]
Hi, I have the same problem.
You know how I can access in Mongo console with snap installation?

**Comment by lazyants** [comment]
yes, just run:
```
rocketchat-server.mongo

**Comment by progressify** [comment]
ok, I have tested your solution, but.. after some test I see this [issue](https://github.com/RocketChat/Rocket.Chat/issues/6979)

and [this](https://developerslogblog.wordpress.com/2019/11/27/mongodb-sort-how-to-fix-maximum-ram-exceeded-error/comment-page-1/?unapproved=2345&moderation-hash=660d21f4cbc9a6f0eb346fa94f5d2e0d#comment-2345) parameter to set into mongodb.

after these changes my problem is solved.

**Comment by lazyants** [comment]
yeah, but this way you just allow to use more resources, what actually is not needed, because after adding a proper index mongodb will not have to create an index on the fly by each request

**Comment by lazyants** [comment]
why it was closed? the problem still exists
