### ISSUE TITLE
OAuth login - Users are occasionally forced to change their password

### ISSUE THREAD

**Issue by bbrauns** [RocketChat/Rocket.Chat#17307]
### Description:

We use keycloak as our OAuth login provider. Occasinally users are forced to change their password with the message:  `This email has already been used and has not been verified. Please change your password.`.

The setting: `Accounts` - `Allow password change` is disabled.

The main problem is, that the users mail address can be different in upper and lower case characters when the data comes from the identity provider or from the mongodb user document.

The bug can be traced to back to this method: 

https://github.com/RocketChat/Rocket.Chat/blob/8e6fa4a051ab4f3080f7e45ae967e8000ae14087/server/configuration/accounts_meld.js#L35-L45

1.  The user object is searched and found with the method `findOneByEmailAddress` which uses the mail address given by the identity provider case-insensitive.
1. Afterwards the user object is searched again with `findWhere` which does it case-sensitive.
1. If the user object in mongodb user collection is saved with upper and lower characters like the following example it can not be found with `findWhere` and the flag `requirePasswordChange` is set by the method `resetPasswordAndSetRequirePasswordChange`.

```
rs0:PRIMARY> db.users.find({username: 'myuserid'}).pretty()
{
        "_id" : "6tJT3iSxJJ2SPqhuS",
        "createdAt" : ISODate("2019-02-14T07:23:33.968Z"),
		"services" : {
                "keycloak" : {
                        "id" : "9be870c7-ed02-47bc-b1c4-ab00487562b8",
                        "_OAuthCustom" : true,
						"email" : "john.doe@mycorp.com", <--- lowercase from IDP
                        "email_verified" : true,
                        "expiresAt" : 1586398122060,
                        "family_name" : "Doe",
                        "given_name" : "John",
                        "name" : "John Doe",
                        "preferred_username" : "0165553",
                        "serverURL" : "https://keycloak.mycorp.com/auth",
                        "sub" : "9be870c7-ed02-47bc-b1c4-ab00487562b8",
                        "uid" : "myuserid",
                        "username" : "myuserid"
                },
				"emails" : [
                {
                        "address" : "John.Doe@mycorp.com", <--- uppercase
                        "verified" : true
                }
        ],
		...
}
```

### Expected behavior:

An external auth provider is configured so the user must not be shown the dialog to change their password.

### Actual behavior:

![Clipboard - April 14, 2020 10_56 AM](https://user-images.githubusercontent.com/6813310/79308358-bc0a4400-7ef8-11ea-838d-3f7c3cc4f070.png)

### Server Setup Information:

Version | 2.4.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by mtcoliveira** [comment]
Has this been resolved?
I have the same problem.
