### ISSUE TITLE
Crash when pasting an "empty" clipboard

### ISSUE THREAD

**Issue by ducher** [RocketChat/Rocket.Chat#1730]
When copy pasting something from Outlook on Windows to Rocket.Chat, the paste won't really work but you can still click on "OK" and if you do so, it will make the server crash indefinitely even if you restart it. It will look for the temporary file corresponding to what you uploaded, which does not exist as you didn't upload anything. Only solution to fix this is to create a file with the same name, e.g. "touch /tmp/Bj9GtZAM8CvX77u7h" in the small interval of time where the server is starting but did not try accessing this file yet.

Here is what it looks like when I paste from Outlook (sorry, screenshot taken in French):
![bad_paste](https://cloud.githubusercontent.com/assets/3705741/11961469/1f5c88d8-a8d9-11e5-9060-1428fda7d535.PNG)

That's quite an annoying issue as we use rocket.chat as well as Outlook at work, and this kind of crash can happen quite often.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/1722

Was fixed, I will close this issue, can you update your Rocket Chat and try again?

Please reopen this issue if the problem persists.

**Comment by ducher** [comment]
Thanks a lot! Is it possible to know in which version this has been fixed? So that I can update my Docker image. Thanks.

**Comment by rodrigok** [comment]
Was fixed via this commit https://github.com/RocketChat/Rocket.Chat/commit/f4da73e6e899537076622729c820091bdf24d6a0

Is available since version 0.10.0 https://github.com/RocketChat/Rocket.Chat/releases/tag/v0.10.0

**Comment by ducher** [comment]
Great! Thanks again. I'll wait for an image of 0.10 then :+1:

**Comment by rodrigok** [comment]
@ducher our official docker images is always up to date, you can get the dev version or the master (default) version that is from 7 days ago (version 0.11.0).

**Comment by rodrigok** [comment]
@ducher https://hub.docker.com/r/rocketchat/rocket.chat/

**Comment by Sing-Li** [comment]
@ducher the 'official' image at hub.docker.com is always slightly behind.  it needs approval from the Docker folks, and tends to be from master releases that are more tested and stable.
