### ISSUE TITLE
Sensitive server data exposed for non logged in users.

### ISSUE THREAD

**Issue by maxsdw** [RocketChat/Rocket.Chat#1731]
When accessing to "/api/info", some data like server OS, kernel version, cpu and ram, as well as other sensitive data is exposed, this could represent a security issue. All sensitive information should be remove from this response.

**Comment by djeber** [comment]
i can confirm this on https://demo.rocket.chat/api/info

**Comment by matthias-brun** [comment]
Perhaps make the information visible somewhere on the administration pages and disable "/api/info" for production systems?

**Comment by engelgabriel** [comment]
we use the `/api/info` on the Mobile and Desktop clients.. to validate the version of Rocket.Chat before they attempt to login.

**Comment by matthias-brun** [comment]
Right, but is there a reason for information such as kernel version or available ram also being publicly exposed?

**Comment by engelgabriel** [comment]
it was mainly to help us give better support, but you are right, we will remove that.

**Comment by Sing-Li** [comment]
we might want to public-key encrypt a sysinfo-blob for support  ?

**Comment by geekgonecrazy** [comment]
Maybe we just make this route only available to admin?  Because I do think some points the info could be good for troubleshooting.

I also like the idea of pub-key encrypt

**Comment by MartinSchoeler** [comment]
Today you only get the chat version from api/info. If there is still something relevant in this issue, please reopen this with updated details. Thanks!

**Comment by localguru** [comment]
Question: would it be a problem to block "/api/info" on nginx proxy side, e.g.:

```
	location ~ ^/apt/info {
		deny all;
	}
```

Or has it still to be public for mobile desktop clients?

**Comment by geekgonecrazy** [comment]
@localguru I believe the new Android app uses this.  The iOS app possibly uses this as well.
