### ISSUE TITLE
Rocketchat Federation with multiple rocketchat dedicated instances hosted on the same domain

### ISSUE THREAD

**Issue by menardorama** [RocketChat/Rocket.Chat#17326]
As using rocketchat federation using Hub is not working anymore, I have setup the DNS part successfully on our main rocketchat instance.

Now I need to deploy dedicated rocketchat instances for specific use cases.

The two instances will share the same domain (ex: rocketchat.mycompany.com and public-chat.mycompany.com), with this setup I don't see how to manage DNS records.

Is there a way to do it or is it not implemented yet ?

Thanks

**Comment by ndroo** [comment]
We're doing exactly this already, works perfectly fine.

You just need to setup all your dns entries as subdomains of the chat domain i.e.

_rocketchat-public-key.rocketchat.mycompany.com

and

_rocketchat-public-key.chat.mycompany.com

etc

If you do need specific help, you can ping me here and I'd be happy to explain further.

**Comment by klepptor** [comment]
> 
> 
> We're doing exactly this already, works perfectly fine.
> 
> You just need to setup all your dns entries as subdomains of the chat domain i.e.
> 
> _rocketchat-public-key.rocketchat.mycompany.com
> 
> and
> 
> _rocketchat-public-key.chat.mycompany.com
> 
> etc
> 
> If you do need specific help, you can ping me here and I'd be happy to explain further.

hi @ndroo ,

I'm trying to build the same setup in our lan with chat1.mycompany.com and chat2.mycompany.com but I can't get it to work at all.

I'm using Windows Server 2016 as DNS and added the SRV and TXT records as described [here](https://docs.rocket.chat/guides/administrator-guides/federation). I also tried the legacy method with SRV _tcp instead of _https but without success.

So maybe you can describe your setup a bit more!?

![grafik](https://user-images.githubusercontent.com/3921511/86008025-8c0f0f00-ba18-11ea-83fb-158679c16239.png)

![grafik](https://user-images.githubusercontent.com/3921511/86008340-e7410180-ba18-11ea-9108-e14367d6c0e5.png)

**Comment by ndroo** [comment]
Hey there,

I'm not super familiar with the Windows Server 2016 DNS interface, but these records do seem a bit unusual to me. Here's what we're doing:

![image](https://user-images.githubusercontent.com/709085/86012693-43d9f780-b9ec-11ea-9314-c2c5037276fe.png)

One thing I'd point out is that you need to ensure all the supporting records (The SRV, the TXT for the public key etc) need to be in the same format as the instance you're hosting. i.e. chat.domain.com needs to have a https locator record of _rockethchat._https.chat.domain.com 

If that doesn't make sense feel free to let me know and i'd gladly get on a zoom call to help you set it up.

**Comment by klepptor** [comment]
Thx for your help.

I really had the TXT records in the wrong place. Now at least these are correct and can be looked up correctly, e.g. using dig. But the SRV records still can't. :( I will have a deeper look in this tomorrow.

**Comment by klepptor** [comment]
@ndroo I still can't get it to work. There must be something wrong with my SRV entries, but I can't figure it out.

server.js:204 Federation ➔ dns.error Error: failed [404] Not Found     at Object.exports.makeErrorByStatus (packages/http.js:177:10)     at Request._callback (packages/http.js:141:24)     at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:311:20)     at Request.EventEmitter.emit (domain.js:482:12)     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:311:20)     at Request.EventEmitter.emit (domain.js:482:12)     at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:417:28)     at IncomingMessage.emit (events.js:323:22)     at IncomingMessage.EventEmitter.emit (domain.js:482:12)     at endReadableNT (_stream_readable.js:1204:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21) {   response: {     statusCode: 404,     content: 'Not Found',     headers: {       'content-length': '9',       'content-type': 'text/plain; charset=utf-8',       date: 'Tue, 30 Jun 2020 12:00:18 GMT',       etag: 'W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"',       'x-powered-by': 'Express',       connection: 'close'     },     data: null   } }

**Comment by ndroo** [comment]
Can you post your SRV record, without any information about the record its pretty hard for me to provide any useful guidance.

**Comment by klepptor** [comment]
@ndroo I got it "working", but now I'm stuck with a self signed certificate in the cert chain. Grr... Don't know yet how to solve this in Docker...

I will again look into it tomorrow and then also post the correct SRV and TXT entries for windows DNS.

Thx!!

**Comment by klepptor** [comment]
Today I got the federation working! 

**Federation entries on Windows Server 2016**

- open admin cmd on Windows DNS/DC:

- SRV entries (example):
`    dnscmd <dnsserver> /RecordAdd <domain> "_rocketchat._https.<servername>" 600 srv 1 1 443 <fqdn_of_your_server>`

TXT entries (example):
    dnscmd <dnsserver> /RecordAdd <domain> "rocketchat-public-key.<servername>" 600 txt <public key>

The public key has to be split in multiple parts or you can change it later in the windows DNS console and use several lines, I used 3 for example.

See here for a Powershell example: https://forums.rocket.chat/t/federation-problems/6892/8

I had to add 

 - NODE_TLS_REJECT_UNAUTHORIZED=0

to the docker-compose.yml to avoid the "self signed cert" errors. Here I'm still searching for a solution to add my root ca cert to the docker file.
