### ISSUE TITLE
Can't enter channel name or members

### ISSUE THREAD

**Issue by larsziegelmann** [RocketChat/Rocket.Chat#17329]
### Description:

When creating a channel with an admin, I can't enter a name for the channel or the members. No matter what key I press, the letters don't show up in the input box.

### Steps to reproduce:

1. Create new channel
2. Name or members can't be entered

### Expected behavior:

Name or members can be entered.

### Actual behavior:

No matter what is pressed on the keyboard, it doesn't show up.
![image](https://user-images.githubusercontent.com/54264704/79454058-e3413e00-7fea-11ea-9ecd-00a2e5c79c06.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 5-10
- NodeJS Version: v8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: version 80.0.3987.163 64-Bit
- Operating System: Windows 10 Pro x64

### Additional context

I've checked the permissions and as an admin I should have the right privileges to create a channel.
Also tried creating a private and a public group, which had the same result.

**Comment by ankar84** [comment]
Try type **channel name in English** or enable **Admin UI - Layout  - User Interface- Allow special characters in Room names**
![image](https://user-images.githubusercontent.com/4023037/79529652-dc134200-8075-11ea-9460-5496e5947a62.png)

**Comment by larsziegelmann** [comment]
The issue has been solved by enabling **Admin UI - Layout - User Interface- Allow special characters in Room names**.
Thanks for your help!
