### ISSUE TITLE
REST API, Error 400 calling after Login

### ISSUE THREAD

**Issue by Sammuel-Miranda** [RocketChat/Rocket.Chat#17334]
I have a program that interacts with a chat, and we now just started using Rocket Chat, so i'm changing the calls to use it's API so send a message to a user from a bot.

So far i read the documentation and made the Login call to api/v1/login (with user and password), that returns to me with sucess and a "authToken" key and "userid" key (the user id key for some reason, unlike the example on the login page documentation, is the same as the username provided).

My next call, any that may be, returns with 400. I'm assuming i must call the api/v1/directory to get the user rid for the sendmessage tag, but any call (even im.create - my other try) returns the same, an empty response with 400 http code.

**Comment by Sammuel-Miranda** [comment]
Verified that works, and followed the path to login, im.create, chat.sendmessage, logout.
The problem is that i'm using the rocket.cat account (bot rule) and it stops at login; a normal user account has no issues.

**Comment by Sammuel-Miranda** [comment]
So, my use of Rocket Chat is very recent, and i don't know what might be going wrong here, but the sequence i use to send a message to a user is working when i log in with the first account i created in rocket chat (my user, with admin role); but when i log with any other account (admin, bot or user role), it fails after login (at the im.create call). It's the same program, just used a different user and password to login.

If that account is rocket.cat for example (a bot) the login returns with the "userid" equals "rocket.cat" (instead of the "random code" i get with any other user). If i log in with another admin role user, the login comes "correct" (just like my own account), but i get HTTP 400 error on im.create; not even a JSON with error, just an empty response, with code 400.

Please help! I created the server on a linux system, via snap (rocket chat version 2.4.11), and i don't know what other configurations i can look to "enable an account to use the API", because it works on my account as source, to any destination, but any other account fails after the login!

**Comment by Sammuel-Miranda** [comment]
So, as it turns out it was something that i didn't know about causing this error - the recipient address is case-sensitive, and a account name "user" and "User" are not found by the API unless it matches the exact case. Althought it passes on the login API (wich is case-insensitve), the im.create is not, so the sender name doesn't need to mach, but any recipient must.

This kind of information would be useful in the API documentation.

**Comment by KheireddineAzzez** [comment]
Can you explain more ?
