### ISSUE TITLE
User-Defined Order of Sidebar

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat#17337]
I will preface that this is a feature request, _not_ a bug report.

### Description:

Sidebar Sorting options are pretty limited -- while the inclusion of a "Favorites" section is great to have, several users have requested the ability to sort "Private Groups" above "Public Channels"; or similar.  While a true drag-and-drop interface may not be possible with the current way the UI is drawn; something to allow "similar" sidebar sections to be reorganized would be nice.

### Steps to reproduce:

N/A

### Expected behavior:

N/A

### Actual behavior:

N/A

### Server Setup Information:

- Version of Rocket.Chat Server: `2.4.2`
- Operating System: `CentOS 7.7.1908 (Core)`
- Deployment Method: `tar`
- Number of Running Instances: `1`
- DB Replicaset Oplog: `rs01`
- NodeJS Version: `8.11.4 x64`
- MongoDB Version: `4.0.14`

### Client Setup Information

- Desktop App or Browser Version: `Desktop App`
- Operating System: `Windows 10 Pro x64, 1903/1909`

### Additional context

I'm _well_ aware our server version is outdated.  Unfortunately, all updates to "critical" system services have been frozen until our local "stay-at-home" order has been lifted, and we can all return to the office.  With that in mind, I'm not currently aware that this feature exists in the current server builds.

That said, it may be worth tying into the unified menu proposal (#14335); or, possibly defined within a user theme (#1887).

### Relevant logs:

N/A

**Comment by sk044** [comment]
The idea is good .. can i work on this issue..??
