### ISSUE TITLE
you can add hubot, agent user and visitor in a live chat room, is it possible?

### ISSUE THREAD

**Issue by arsevys** [RocketChat/Rocket.Chat#17345]
I have been able to link in a livechat, the visitor and agent, or visitor and bot, but I have not been able to integrate all three at the same time in a livechat room

**Comment by chris-aeviator** [comment]
Currently I forward the conversation as soon as I want to take over

**Comment by chris-aeviator** [comment]
_stalebots are the worst for software quality_
