### ISSUE TITLE
Messages don't load

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat#17349]
why are some messages loaded with such a delay that they are not seen during the conversation?
why don't other messengers have this problem? what is the reason for this?
during a conversation with a bad Internet one of the ten messages is not loaded

**Comment by giterium** [comment]
during a conversation with a bad Internet one of the ten messages is not loaded

**Comment by giterium** [comment]
rocket chat is a great app but problems loading messages spoil everything 😖

**Comment by ankar84** [comment]
Similar behaviour was on a previous versions of rocket chat, but definitely fixed in fresh >3.0.0 versions.
Do, please provide full necessary information, that was in bug report template, such as server version.

**Comment by giterium** [comment]
what exactly did you do to fix it?

**Comment by ankar84** [comment]
> what exactly did you do to fix it?

Obviously - upgrade to most fresh and stable server version (3.0.3 for now, but 3.1.1 in plans)

**Comment by giterium** [comment]
I ask what changes in the system fixed the message delivery error?

**Comment by ankar84** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/16474

**Comment by giterium** [comment]
Thanks :)
