### ISSUE TITLE
Rocket not properly gauging users idle-ness

### ISSUE THREAD

**Issue by anolis** [RocketChat/Rocket.Chat#17344]
I have received reports from members of my organization that rocket is displaying them as away even when they have been sitting at their computer working on stuff. 

It seems that the idle-ness is being checked from within the context of the rocket app itself. Is it feasible to use system based idle counters to provide a more accurate idle-ness representation to the app?

**Comment by sampaiodiego** [comment]
@tassoevan please correct me if I'm wrong.

on Windows and Mac OS when using the desktop app it uses the available APIs to check the system idle status, but either on Linux or on any browser the idle status is triggered after a period of time the user is not interacting with rocket.chat tab. is that your case @anolis ?

**Comment by ankar84** [comment]
@sampaiodiego I can tell for modern desktop application (2.17.9) on Windows 10 - idle behaviour is great! System lock with WIN+L and time-out idle both works perfectly.
