### ISSUE TITLE
Install from code: https://rocket.chat/docs/developer-guides/quick-start/

### ISSUE THREAD

**Issue by longtqdayma** [RocketChat/Rocket.Chat#17340]
Install tools required
sudo apt install g++ build-essential git curl python-minimal
Error 
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/bin/apt" (-1)

Use  Oracle JDK 8, 12, 14.
macOS Catalina 10.15.4

Thanks

**Comment by ashwaniYDV** [comment]
This isn't a problem in docs I guess. I have tested it and its working fine.

**Comment by luixxiul** [comment]
@longtqdayma maybe there is an issue with your PATH?

**Comment by ndroo** [comment]
MacOS doesn't have apt (thats a linux command). The docs are wrong as they don't explain this, they say they're for Mac and Linux, but really that step is Linux specific.

The solution: For Mac you need to run this through code: xcode-select --install (https://stackoverflow.com/questions/38086451/how-to-install-build-essential-on-mac)

Someone should update that page for sure.

**Comment by luixxiul** [comment]
yeah right macOS does not have APT. I have overlooked that.

**Comment by ndroo** [comment]
Should this really be closed? The docs have not been fixed...

**Comment by gabriellsh** [comment]
Sorry, closed by accident. Thanks for the warning.
