### ISSUE TITLE
Attempting to update apps from the App list fails

### ISSUE THREAD

**Issue by sketch242** [RocketChat/Rocket.Chat#17358]
### Description:

Clicking Update from App list generates "Error: App already exists" popup.  If you click on the app and then click upgrade, it works.  This isn't a major issue since you can still update the apps, but I figured I'd report it.

### Steps to reproduce:

1. Go to Administration -> Apps.
2. See an app that is not up to date, click Update
3. Receive error: "App already exists".  App is not updated

### Expected behavior:

1. Go to Administration -> Apps.
2. See an app that is not up to date, click Update
3. App is updated.

### Actual behavior:

App is not updated.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS 7.7
- Deployment Method: ansible
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18
 
### Client Setup Information

- Desktop App or Browser Version: 2.17.7
- Operating System: macOS 10.14.6

### Additional context

No logs were generated until enabling debug mode.  With debug enabled, I get the log below.

### Relevant logs:

Apr 19 09:51:45 vdrc01 RocketChat[8070]: API ➔ debug POST: /api/apps/
Apr 19 09:51:48 vdrc01 RocketChat[8070]: API ➔ debug post  threw an error: Error: App already exists.
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at app/apps/server/storage/storage.js:23:19
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at new Promise (<anonymous>)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at AppRealStorage.create (app/apps/server/storage/storage.js:10:10)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at AppManager.<anonymous> (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:339:48)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at Generator.next (<anonymous>)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at fulfilled (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/AppManager.js:4:58)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at /var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Apr 19 09:51:48 vdrc01 RocketChat[8070]: => awaited here:
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at Function.Promise.await (/var/lib/rocket.chat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at Object.post (app/apps/server/communication/rest.js:231:25)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at app/api/server/api.js:368:82
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at Object._internalRouteActionHandler [as action] (app/api/server/api.js:368:39)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at packages/nimble_restivus/lib/route.coffee:59:33
Apr 19 09:51:48 vdrc01 RocketChat[8070]: at packages/simple_json-routes.js:98:9
Apr 19 09:51:48 vdrc01 RocketChat[8070]: API ➔ debug Failure {
Apr 19 09:51:48 vdrc01 RocketChat[8070]: statusCode: 400,
Apr 19 09:51:48 vdrc01 RocketChat[8070]: body: { success: false, error: 'App already exists.', stack: undefined }
Apr 19 09:51:48 vdrc01 RocketChat[8070]: }

**Comment by sampaiodiego** [comment]
this should have been fixed on version 3.3.x

can you please update and test again? thx
