### ISSUE TITLE
Icons dissapearing 

### ISSUE THREAD

**Issue by mhenninghaus77** [RocketChat/Rocket.Chat#17359]
### Description:
When switching between chats or rooms suddenly some icons are broken.
The missing Icons are the ones for emojis but for all actions inside this chat/room

### Steps to reproduce:

1. Select a Room or Chat
<img width="1333" alt="Bildschirmfoto 2020-04-20 um 07 41 46" src="https://user-images.githubusercontent.com/26816009/79718085-817b1f80-82db-11ea-9466-34ca1d0ed24f.png">
2. Select another Room/Chat
3. Switch back to previous Room/Chat
<img width="1333" alt="Bildschirmfoto 2020-04-20 um 07 41 57" src="https://user-images.githubusercontent.com/26816009/79718088-83dd7980-82db-11ea-9b59-71e65fe59078.png">
### Expected behavior:

The icons won't dissaperar
### Actual behavior:

icons are dissapperaring, tooltips too

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.4/Apps Engine Version 1.12.0
- Operating System: Debian 10
- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: set
- NodeJS Version: 12.16.1
- MongoDB Version: 4.2.5 

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by sk044** [comment]
can i work on this issue??

**Comment by gabriellsh** [comment]
@sk044 please take a look here https://rocket.chat/docs/contributing/developing/

**Comment by gabriellsh** [comment]
`Version of Rocket.Chat Server: 3.0.4` we're already at 3.1.0. I tested this on develop and I couldn't reproduce. In case you upgrade and this still persists, please, comment down.
