### ISSUE TITLE
Blank line in channel when user posts image in thread

### ISSUE THREAD

**Issue by tannn** [RocketChat/Rocket.Chat#17352]
### Steps to reproduce:

1. Post in image in a channel thread

### Expected behavior:

The main channel would show that someone posted an image in the thread

### Actual behavior:

A blank line is posted in the channel

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows

![image](https://user-images.githubusercontent.com/831788/79615661-ed396e80-80c8-11ea-94ac-5ec97cc6846a.png)

**Comment by ashwaniYDV** [comment]
@tannn This issue is fixed in the newer version of RC

**Comment by ashwaniYDV** [comment]
hi @gabriellsh 
This issue is already solved by one of my PR. Can you please have a look/close it?

**Comment by tannn** [comment]
> hi @gabriellsh
> This issue is already solved by one of my PR. Can you please have a look/close it?

Link?

**Comment by ankar84** [comment]
> > hi @gabriellsh
> > This issue is already solved by one of my PR. Can you please have a look/close it?
> 
> Link?

https://github.com/RocketChat/Rocket.Chat/pull/16416

**Comment by tannn** [comment]
Thanks @ankar84
