### ISSUE TITLE
[Bug] Automatic logout by oauth2 when switching between browser, desktop app, mobile app

### ISSUE THREAD

**Issue by michaelflohr** [RocketChat/Rocket.Chat#17369]
### Description:
Users are automatically logged out when a login (via OAuth) is made via another instance (browser, desktop app, mobile phone app). The problem occurs because of OAuth. If OAuth is disabled and normal login settings with mail and password are enabled, this automatic logout does not happen.

The problem persists even after updating Rocket.Chat to 3.0.10.

### Steps to reproduce:

1. Use the Oauth2 authentication.
1. desktop app logged in -> then log in in the browser: automatic log out in desktop app
1. desktop app logged in -> then log in to mobile phone app: automatic log out to desktop app
1. mobile app logged in -> then log in in browser: automatic log out in mobile app
1. mobile phone app logged in -> then log in to desktop app: automatic log out to mobile phone app
1. Browser logged in -> then log in mobile phone app: automatic logout in browser
1. Browser logged in -> then log in desktop app: automatic logout in browser

### Expected behavior:
The user is logged into his account on all devices.

### Actual behavior:
The user is logged in only on the device they most recently logged in, and logged out of all other devices.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.10
- Operating System: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: (default)
- NodeJS Version: v8.17.0
- MongoDB Version: v3.6.3

### Client Setup Information

- Desktop App or Browser Version: (multiple, bug occurs on any modern version)
- Operating System: (multiple, bug occurs on any modern version)

### Additional context

* Whenever any device/browser logs into rocketchat using oauth2 with our django user authentication as provider, any previously existing oauth2 authenticated connections are *immediately* logged out and disconnected. If for example, a browser window with rocketchat is open, and I log in to the rocketchat android app using oauth2 on the same django user account, the browser window rocketchat immediately goes to the rocket welcome-login screen.
* We are using django-oauth-toolkit 1.3.2 as Oauth2 provider in our django app (settings for the oauth app are Authorization grant type: "Authorization code", Skip authorization: True)
  * On every new login on a different device, we can obvserve one new authorization token and one new refresh token being generated in the oauth provider DB tables for that django user.
* We are running the exact same setup in our django app to connect to a Nextcloud server using Oauth2, and there we do NOT encounter this bug! Multiple devices can log in to nextcloud with the same django user authentication at the same time.

#### Server when logging into browser (logging out the Android App connection) 

I20200420-12:30:53.009(2) server.js:204 API ➔ debug GET: /api/v1/users.info?userId=75dbzgrLBvw5TxBt5 
I20200420-12:30:53.019(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     user: {       _id: '75dbzgrLBvw5TxBt5',       createdAt: 2019-07-15T14:41:05.224Z,       services: [Object],       username: 'sascha.narr1',       emails: [Array],       type: 'user',       status: 'online',       active: true,       roles: [Array],       name: 'Sascha Narr',       lastLogin: 2020-04-20T10:29:09.559Z,       statusConnection: 'online',       utcOffset: 2     },     success: true   } } 
I20200420-12:30:53.083(2) server.js:204 API ➔ debug POST: /api/v1/users.update 
I20200420-12:30:53.191(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     user: {       _id: '75dbzgrLBvw5TxBt5',       createdAt: 2019-07-15T14:41:05.224Z,       username: 'sascha.narr1',       emails: [Array],       type: 'user',       status: 'online',       active: true,       _updatedAt: 2020-04-20T10:30:53.179Z,       roles: [Array],       settings: {},       name: 'Sascha Narr',       avatarOrigin: 'url',       lastLogin: 2020-04-20T10:29:09.559Z,       statusConnection: 'online',       utcOffset: 2     },     success: true   } } 
I20200420-12:30:53.408(2) server.js:204 API ➔ debug POST: /api/v1/users.setAvatar 
I20200420-12:30:53.428(2) server.js:204 API ➔ debug post users.setAvatar threw an error: Error: Change avatar is not allowed [error-not-allowed]     at Object.post (app/api/server/v1/users.js:271:10)     at app/api/server/api.js:343:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20200420-12:30:53.435(2) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: {     success: false,     error: 'Change avatar is not allowed [error-not-allowed]',     stack: undefined,     errorType: 'error-not-allowed'   } } 
I20200420-12:30:53.798(2) server.js:204 CustomOAuth ➔ debug Identity response {   "success": true,   "id": "1",   "email": "saschanarr@gmail.com",   "name": "Sascha Narr",   "avatar": "https://plattformn.staging.wechange.de/media/cosinnus_portals/portal_default/avatars/user/3ad4956e5757b57bf602ff25f74700ff186bf8be.png" } 
I20200420-12:30:54.194(2) server.js:204 Meteor ➔ publish stream-importers -> userId: 75dbzgrLBvw5TxBt5, arguments: ["progress",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.225(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["app/added",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.228(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["app/removed",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.235(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["app/updated",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.238(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["app/statusUpdate",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.247(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["app/settingUpdated",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.249(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["command/added",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.252(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["command/disabled",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.254(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["command/updated",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.262(2) server.js:204 Meteor ➔ publish stream-apps -> userId: 75dbzgrLBvw5TxBt5, arguments: ["command/removed",{"useCollection":false,"args":[]}] 
I20200420-12:30:54.277(2) server.js:204 Meteor ➔ publish null -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.365(2) server.js:204 API ➔ debug GET: /api/v1/roles.list 
I20200420-12:30:54.369(2) server.js:204 API ➔ debug GET: /api/v1/emoji-custom.list 
I20200420-12:30:54.371(2) server.js:204 API ➔ debug GET: /api/v1/commands.list 
I20200420-12:30:54.378(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     commands: [       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object]     ],     offset: 0,     count: 24,     total: 24,     success: true   } } 
I20200420-12:30:54.383(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     roles: [       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object]     ],     success: true   } } 
I20200420-12:30:54.388(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: { emojis: { update: [], remove: [] }, success: true } } 
I20200420-12:30:54.399(2) server.js:204 Meteor ➔ method autoTranslate.getSupportedLanguages -> userId: 75dbzgrLBvw5TxBt5, arguments: ["en"] 
I20200420-12:30:54.402(2) server.js:204 Meteor ➔ method autoTranslate.getProviderUiMetadata -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.410(2) server.js:204 Meteor ➔ method listCustomSounds -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.415(2) server.js:204 Meteor ➔ method apps/is-enabled -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.419(2) server.js:204 Meteor ➔ method getUserRoles -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.426(2) server.js:204 Meteor ➔ method listCustomUserStatus -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.438(2) server.js:204 Meteor ➔ method rooms/get -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.453(2) server.js:204 Meteor ➔ method subscriptions/get -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:30:54.474(2) server.js:204 API ➔ debug GET: /api/apps/languages 
I20200420-12:30:54.476(2) server.js:204 API ➔ debug Success { statusCode: 200, body: { apps: [], success: true } } 
I20200420-12:30:54.538(2) server.js:204 API ➔ debug GET: /api/v1/me 
I20200420-12:30:54.543(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     _id: '75dbzgrLBvw5TxBt5',     services: { password: [Object] },     username: 'sascha.narr1',     emails: [ [Object] ],     status: 'online',     active: true,     _updatedAt: 2020-04-20T10:30:54.294Z,     roles: [ 'user' ],     settings: { preferences: [Object] },     name: 'Sascha Narr',     avatarOrigin: 'url',     statusConnection: 'online',     utcOffset: 2,     email: 'saschanarr@gmail.com',     avatarUrl: 'https://chat.staging.wechange.de/avatar/sascha.narr1',     success: true   } } 

#### Server when logging into Android app (logging out the browser connection) 

I20200420-12:35:19.254(2) server.js:204 API ➔ debug GET: /api/info 
I20200420-12:35:19.259(2) server.js:204 API ➔ debug Success { statusCode: 200, body: { version: '3.0.10', success: true } } 
I20200420-12:35:20.633(2) server.js:204 Meteor ➔ publish null -> userId: null, arguments: [] 
I20200420-12:35:20.760(2) server.js:204 API ➔ debug GET: /api/v1/settings.oauth 
I20200420-12:35:20.769(2) server.js:204 API ➔ debug Success { statusCode: 200, body: { services: [ [Object] ], success: true } } 
I20200420-12:35:21.178(2) server.js:204 API ➔ debug GET: /api/v1/settings.public?query={%22_id%22:{%22$in%22:[%22Accounts_CustomFields%22,%22Accounts_EmailOrUsernamePlaceholder%22,%22Accounts_NamePlaceholder%22,%22Accounts_PasswordPlaceholder%22,%22Accounts_PasswordReset%22,%22CROWD_Enable%22,%22FEDERATION_Enabled%22,%22LDAP_Enable%22,%22Jitsi_Enabled%22,%22Jitsi_SSL%22,%22Jitsi_Domain%22,%22Jitsi_URL_Room_Prefix%22,%22Message_AllowDeleting%22,%22Message_AllowDeleting_BlockDeleteInMinutes%22,%22Message_AllowEditing%22,%22Message_AllowEditing_BlockEditInMinutes%22,%22Message_AllowPinning%22,%22Message_AllowStarring%22,%22Message_GroupingPeriod%22,%22Message_TimeFormat%22,%22Message_TimeAndDateFormat%22,%22Site_Name%22,%22Site_Url%22,%22Store_Last_Message%22,%22uniqueID%22,%22UI_Use_Real_Name%22,%22Assets_favicon_512%22,%22Message_Read_Receipt_Enabled%22,%22Message_Read_Receipt_Store_Users%22,%22Threads_enabled%22,%22FileUpload_MediaTypeWhiteList%22,%22FileUpload_MaxFileSize%22,%22API_Gitlab_URL%22,%22AutoTranslate_Enabled%22,%22CAS_enabled%22,%22CAS_login_url%22]}} 
I20200420-12:35:21.200(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     settings: [       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       [Object], [Object], [Object]     ],     count: 35,     offset: 0,     total: 35,     success: true   } } 
I20200420-12:35:21.447(2) server.js:204 Meteor ➔ publish null -> userId: null, arguments: [] 
I20200420-12:35:24.420(2) server.js:204 API ➔ debug GET: /api/v1/users.info?userId=75dbzgrLBvw5TxBt5 
I20200420-12:35:24.429(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     user: {       _id: '75dbzgrLBvw5TxBt5',       createdAt: 2019-07-15T14:41:05.224Z,       services: [Object],       username: 'sascha.narr1',       emails: [Array],       type: 'user',       status: 'online',       active: true,       roles: [Array],       name: 'Sascha Narr',       lastLogin: 2020-04-20T10:31:11.203Z,       statusConnection: 'online',       utcOffset: 2     },     success: true   } } 
I20200420-12:35:24.495(2) server.js:204 API ➔ debug POST: /api/v1/users.update 
I20200420-12:35:24.603(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     user: {       _id: '75dbzgrLBvw5TxBt5',       createdAt: 2019-07-15T14:41:05.224Z,       username: 'sascha.narr1',       emails: [Array],       type: 'user',       status: 'online',       active: true,       _updatedAt: 2020-04-20T10:35:24.595Z,       roles: [Array],       settings: {},       name: 'Sascha Narr',       avatarOrigin: 'url',       lastLogin: 2020-04-20T10:31:11.203Z,       statusConnection: 'online',       utcOffset: 2     },     success: true   } } 
I20200420-12:35:24.665(2) server.js:204 API ➔ debug POST: /api/v1/users.setAvatar 
I20200420-12:35:24.683(2) server.js:204 API ➔ debug post users.setAvatar threw an error: Error: Change avatar is not allowed [error-not-allowed]     at Object.post (app/api/server/v1/users.js:271:10)     at app/api/server/api.js:343:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:343:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
I20200420-12:35:24.687(2) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: {     success: false,     error: 'Change avatar is not allowed [error-not-allowed]',     stack: undefined,     errorType: 'error-not-allowed'   } } 
I20200420-12:35:24.747(2) server.js:204 CustomOAuth ➔ debug Identity response {   "success": true,   "id": "1",   "email": "saschanarr@gmail.com",   "name": "Sascha Narr",   "avatar": "https://plattformn.staging.wechange.de/media/cosinnus_portals/portal_default/avatars/user/3ad4956e5757b57bf602ff25f74700ff186bf8be.png" } 
I20200420-12:35:24.956(2) server.js:204 Meteor ➔ publish null -> userId: null, arguments: [] 
I20200420-12:35:24.992(2) server.js:204 Meteor ➔ publish stream-importers -> userId: null, arguments: ["progress",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.004(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["app/added",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.009(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["app/removed",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.014(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["app/updated",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.022(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["app/statusUpdate",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.025(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["app/settingUpdated",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.028(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["command/added",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.030(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["command/disabled",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.033(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["command/updated",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.036(2) server.js:204 Meteor ➔ publish stream-apps -> userId: null, arguments: ["command/removed",{"useCollection":false,"args":[]}] 
I20200420-12:35:25.059(2) server.js:204 API ➔ debug POST: /api/v1/login 
I20200420-12:35:25.224(2) server.js:204 Meteor ➔ publish null -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:35:25.231(2) server.js:204 Meteor ➔ method public-settings/get -> userId: null, arguments: [{}] 
I20200420-12:35:25.302(2) server.js:204 Meteor ➔ method rooms/get -> userId: null, arguments: [{}] 
I20200420-12:35:25.343(2) server.js:204 API ➔ debug POST: /api/v1/login 
I20200420-12:35:25.362(2) server.js:204 Meteor ➔ method subscriptions/get -> userId: null, arguments: [{}] 
I20200420-12:35:25.535(2) server.js:204 Meteor ➔ publish null -> userId: 75dbzgrLBvw5TxBt5, arguments: [] 
I20200420-12:35:25.657(2) server.js:204 API ➔ debug GET: /api/v1/roles.list 
I20200420-12:35:25.666(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     roles: [       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object]     ],     success: true   } } 
I20200420-12:35:25.722(2) server.js:204 API ➔ debug GET: /api/v1/commands.list 
I20200420-12:35:25.726(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     commands: [       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object],       [Object], [Object], [Object]     ],     offset: 0,     count: 24,     total: 24,     success: true   } } 
I20200420-12:35:25.729(2) server.js:204 API ➔ debug POST: /api/v1/push.token 
I20200420-12:35:25.734(2) server.js:204 API ➔ debug GET: /api/v1/users.presence 
I20200420-12:35:25.737(2) server.js:204 API ➔ debug GET: /api/v1/subscriptions.get 
I20200420-12:35:25.739(2) server.js:204 Meteor ➔ method subscriptions/get -> userId: 75dbzgrLBvw5TxBt5, arguments: [null] 
I20200420-12:35:25.743(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     users: [ [Object], [Object], [Object] ],     full: true,     success: true   } } 
I20200420-12:35:25.754(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     update: [       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object]     ],     remove: [],     success: true   } } 
I20200420-12:35:25.784(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     result: {       _id: 'mFeNtLt9hSuhEgcYC',       token: [Object],       appName: 'chat.rocket.android',       userId: '75dbzgrLBvw5TxBt5',       enabled: true,       createdAt: 2020-04-19T12:14:40.621Z,       updatedAt: 2020-04-20T10:28:25.583Z     },     success: true   } } 
I20200420-12:35:25.794(2) server.js:204 API ➔ debug GET: /api/v1/rooms.get 
I20200420-12:35:25.801(2) server.js:204 Meteor ➔ method rooms/get -> userId: 75dbzgrLBvw5TxBt5, arguments: [null] 
I20200420-12:35:25.864(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     update: [       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object]     ],     remove: [],     success: true   } } 
I20200420-12:35:25.875(2) server.js:204 API ➔ debug GET: /api/v1/permissions.listAll 
I20200420-12:35:25.949(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     update: [       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object], [Object], [Object],       [Object], [Object], [Object], [Object],       ... 887 more items     ],     remove: [],     success: true   } } 
I20200420-12:35:25.964(2) server.js:204 API ➔ debug GET: /api/v1/emoji-custom.list 
I20200420-12:35:25.967(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: { emojis: { update: [], remove: [] }, success: true } } 

#### Client  (Browser, being logged out by a login in the Android App)

1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1 Exception from Tracker recompute function:
1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1 TypeError: Cannot read property 'uid' of undefined
    at s.autorun (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971)
    at t._compute (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679)
    at t._recompute (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679)
    at Object.o._runFlush (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679)
    at a (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1)
1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971 E2E -> Stop Client
1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55 GET https://chat.staging.wechange.de/api/v1/me 401
send @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55
ajax @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55
n @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971
_jqueryCall @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971
get @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971
get @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971
d @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:973
async function (async)
d @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:973
(anonymous) @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:973
_compute @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
_recompute @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
o._runFlush @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
a @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1
postMessage (async)
u @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1
_ @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
invalidate @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
changed @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
statusChanged @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
_connected @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
socket.onopen.t @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
r.dispatchEvent @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
k._dispatchOpen @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
k._didMessage @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
o.ws.onmessage @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971 Uncaught (in promise) Error
    at Object.t [as error] (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971)
    at s (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55)
    at Object.fireWith [as rejectWith] (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55)
    at T (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55)
    at XMLHttpRequest.<anonymous> (1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55)
t @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:971
s @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55
fireWith @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55
T @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55
(anonymous) @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:55
async function (async)
(anonymous) @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:973
_compute @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
_recompute @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
o._runFlush @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
a @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1
postMessage (async)
u @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:1
_ @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
invalidate @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
changed @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:679
statusChanged @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
_connected @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
socket.onopen.t @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
r.dispatchEvent @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
k._dispatchOpen @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
k._didMessage @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693
o.ws.onmessage @ 1dbc9657c3bc49bef3fd69c16651486b31d6b74a.js?meteor_js_resource=true:693

**Comment by michaelflohr** [comment]
@gabriellsh Can you estimate if and when there might be a solution for this bug?

**Comment by michaelflohr** [comment]
@gabriellsh I have sent a mail to the support mail address and hope there for an assessment of the problem and an answer.

**Comment by rodrigok** [comment]
@michaelflohr can you contact me at https://open.rocket.chat/direct/rodrigo.nascimento?

**Comment by michaelflohr** [comment]
@gabriellsh The problem is solved thanks to @rodrigok 

The problem was: "Probably you are saving the password into the Rocket.Chat user via API on every OAuth login, making the existant sessions invalid."
