### ISSUE TITLE
E2E Encryption messages not decrypting between users/on a channel unless you refresh page

### ISSUE THREAD

**Issue by Pajellen** [RocketChat/Rocket.Chat#17371]
### Description:
E2E encryption doesn't seem to be working on on 3.0.1X versions of RocketChat consistently, confirmed the issue using a trial server along with a server I am administrating. The issue is identical to this issue below, marked as [fixed](https://github.com/RocketChat/Rocket.Chat/pull/14580). Trial Server is [here](https://afinia2.rocket.chat/admin/info)

[e2e messages not decrypting in message threads](https://github.com/RocketChat/Rocket.Chat/issues/14512)

### Steps to reproduce:

1.Ensure e2e encryption is on/password saved
2.Enter a private DM/Start an Encrypted Thread
3.Message thread or user directly
4.Message will show up as blank on the receivers end, replies from receiver never show up on sender's end. The message you just sent is shown as ***** in the thread panel
5. Refresh page
6. Messsages show up properly

### Expected behavior:

The message is displayed in the thread and the main chat without a Refresh.

### Actual behavior:

![image](https://user-images.githubusercontent.com/12768295/79793305-f408f100-8315-11ea-86df-e1f57694db54.png)

![image](https://user-images.githubusercontent.com/12768295/79793362-0d11a200-8316-11ea-95a9-54b8140e69d0.png)

![image](https://user-images.githubusercontent.com/12768295/79793447-33374200-8316-11ea-94d2-59dac16354b4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System:  Linux 4.14.138
- Deployment Method: Trial Version (unknown)
- Number of Running Instances: 1
- Deployment ID: Mc28MoFEQWR2vZRRZ
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.11
--

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox/Official Client
- Operating System: Windows 10

**Comment by maxfiedler** [comment]
We are facing the same issue on encrypted channels.
We are using both Firefox and Chrome browser applications as well as iOS and Ubuntu 20.04 desktop apps

**Comment by maxfiedler** [comment]
when i try to type sth myself i get `can not read property 'slice' of undefined`

**Comment by maxfiedler** [comment]
this happens currently on the browser application for me
