### ISSUE TITLE
Where can I find the method for Meteor.call('login', args)

### ISSUE THREAD

**Issue by Godman-quake** [RocketChat/Rocket.Chat#17373]
app/api/server/api.js:
line 362: auth = DDP._CurrentInvocation.withValue(invocation, () => Meteor.call('login', args));
If someone can tell me where can I find the 'login' method, I want do something in it.
Thanks a lot!

**Comment by Godman-quake** [comment]
Ok, I found this method in accounts-base, it's fine.

**Comment by nilsonivano** [comment]
Hey @Godman-quake , can you point to me exactly where did you find the login method on accounts-base? Thanks!

**Comment by Godman-quake** [comment]
> Hey @Godman-quake , can you point to me exactly where did you find the login method on accounts-base? Thanks!

accounts_server.js:
methods.login = function (options) {
      // Login handlers should really also check whatever field they look at in
      // options, but we don't enforce it.
      check(options, Object);

      const result = accounts._runLoginHandlers(this, options);

      return accounts._attemptLogin(this, "login", arguments, result);
    };
