### ISSUE TITLE
Increasing RAM usage

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#17376]
### Description:

Hi, in our installation we are using Docker containers. We are observing that RAM usage is 
daily increasing. At start usage was about 700-800 MB per container. During 12 days increased to about 1,5 GB per container and grow. Could you check what causing this behaviour. I have attached graph with RAM usage.

### Steps to reproduce:

1. Check grow of RAM usage on containers

### Expected behavior:

RAM usage not increase day by day

### Actual behavior:

RAM usage increase day by day

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Centos 7
- Deployment Method: docker compose
- Number of Running Instances: 30
- DB Replicaset Oplog: YES
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.14

### Additional context

![image](https://user-images.githubusercontent.com/50440047/79847657-4e5e8c00-83c0-11ea-9a60-8e6c31c4d9f0.png)

**Comment by ankar84** [comment]
We see that too
![image](https://user-images.githubusercontent.com/4023037/79937112-b5804d00-8461-11ea-996d-22c5e920ab1c.png)

**Comment by sampaiodiego** [comment]
thanks guys.. please join the conversation at https://github.com/RocketChat/Rocket.Chat/issues/16586

there is a memory leak, but we couldn't find yet.. please keep sending as much details as possible.. thx
