### ISSUE TITLE
rocket.chat-v.latest.tgz: 404 Not Found 

### ISSUE THREAD

**Issue by ChristianKniep** [RocketChat/Rocket.Chat#1737]
Hey guys,

somehow the tgz is not available anymore...
```
$ wget https://s3.amazonaws.com/rocketchatbuild/rocket.chat-v.latest.tgz
--2015-12-23 13:20:46--  https://s3.amazonaws.com/rocketchatbuild/rocket.chat-v.latest.tgz
Resolving s3.amazonaws.com... 54.231.81.131
Connecting to s3.amazonaws.com|54.231.81.131|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-23 13:20:46 ERROR 404: Not Found.
```

**Comment by Sing-Li** [comment]
It has been changed for a few weeks now.

Use  rocket.chat-develop.tgz  for the develop branch, and rocket.chat-master.tgz for the master branch.

**Comment by ChristianKniep** [comment]
I was looking into the files in the PR... :)

**Comment by Sing-Li** [comment]
:)   I see.  You caught us in transition. Hmm... that root level Dockerfile was used only for Heroku deploys; the image building ones are in the `.docker` directory.

**Comment by ChristianKniep** [comment]
It caught my atention since my docker image was broke, now it's green again: https://hub.docker.com/r/qnib/rocketchat/builds/
