### ISSUE TITLE
i18n missing for LDAP connection test success message

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#17382]
### Description:

When using the "Test Connection" to check if a configured LDAP connection is working properly, the success message is missing from i18n.

### Steps to reproduce:

1. Setup working LDAP connection
2. Click "Test Connection"

### Expected behavior:

Should have a proper translation

### Actual behavior:

![Bildschirmfoto 2020-04-21 um 18 56 39](https://user-images.githubusercontent.com/944459/79892072-36a7f780-8402-11ea-88c1-441d02122b0c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Docker
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: Docker
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: 2.17.9 Electron
- Operating System: macOS 10.15.4

**Comment by AbhinavTalari** [comment]
Hey Can i work on it ?

**Comment by AbhinavTalari** [comment]
Hey Can I work on it ?

**Comment by AbhinavTalari** [comment]
@frdmn  could you please tell me , what do you mean by "Should have a proper translation ?"
