### ISSUE TITLE
Jitsi: Add option to make jitsi room name the same as the channel it started from

### ISSUE THREAD

**Issue by mickymiek** [RocketChat/Rocket.Chat#17389]
Hi!

We'd like to have an option in Video Conference > Jitsi that when enabled, if a conference is started in a channel, would create the Jitsi conference with the same room name as the Rocketchat channel it started from instead of an hash.

What do you guys think? If it sounds good, we're ready to contribute.

Thanks :)

**Comment by jbguerraz** [comment]
Since rocket chat now supports JWT auth on jitsi that must be possible.
Ideally there would be an option to choose  "obscure" / "plain" since one could use some auth on jitsi (jwt or any other auth supported by prosody) or not.

**Comment by lightngn** [comment]
> Since rocket chat now supports JWT auth on jitsi that must be possible.
> Ideally there would be an option to choose "obscure" / "plain" since one could use some auth on jitsi (jwt or any other auth supported by prosody) or not.

That would be awesome as a feature. I would really like plain room names as I would need it to map sip t the room...

Cheers
Keep up the great work

**Comment by jbguerraz** [comment]
@gabriellsh I just opened a PR (first contribution :partying_face: ) that implements that feature :) I will be glad to get your review!

**Comment by jbguerraz** [comment]
actually not stale but waiting for merge :)

**Comment by lightngn** [comment]
I agree with @jbguerraz still waiting for the merge as this is important to complete my install....

Cheers and thanks for the great work
