### ISSUE TITLE
Ubuntu 18.04.4 LTS Snap Install Not Working

### ISSUE THREAD

**Issue by wsteven-son** [RocketChat/Rocket.Chat#17383]
Unable to snap install on Ubuntu 18.04.4 LTS bionic server. 

`sudo snap install rocketchat-server`
```
error: snap "rocketchat-server" is not available on stable but is available to install on the
       following channels:

       candidate  snap install --candidate rocketchat-server
       beta       snap install --beta rocketchat-server
       edge       snap install --edge rocketchat-server

       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info rocketchat-server'.

```
the candidate, beta nor edge also do not install. 
Thanks

**Comment by gabriellsh** [comment]
If you have any trouble setting up your Rocket.Chat instance, please goto [our open Support Channel](https://open.rocket.chat/channel/support). You can also try contacting support@rocket.chat.

Issues are reserved for bugs and feature requests/improvements. Thanks for your comprehension!
