### ISSUE TITLE
Show popular channels to new users

### ISSUE THREAD

**Issue by sk044** [RocketChat/Rocket.Chat#17399]
When a user signups then we can present some of the popular channels to join ... it can be convinient for a user..

**Comment by sk044** [comment]
@Sing-Li is it a good idea??

**Comment by ankar84** [comment]
> When a user signups then we can present some of the popular channels to join ... it can be convinient for a user..

**Default channels** functionality is presented in Rocket Chat and works perfect.

**Comment by sk044** [comment]
Ya that's ok ... But I meant based on user's intrests .. if we can suggest some more ...

**Comment by sk044** [comment]
Yes .. that's a bit better..

**Comment by sk044** [comment]
Should I work on it ?

**Comment by gabriellsh** [comment]
We already have a `featured` setting that displays channels at the top on Directory. Also, this is open source man, feel free to work on whatever you want. Do you think this feature suffices what you intend?

**Comment by gabriellsh** [comment]
Please try to keep titles informative so searching is easier.

**Comment by sk044** [comment]
Sure !!! Yes i think that's good .. some changes can be done ... i'll try
