### ISSUE TITLE
Invalid file type in latest release?

### ISSUE THREAD

**Issue by spanchy** [RocketChat/Rocket.Chat#17401]
When trying to upload archive .rar (and some others, sample .jpeg, .txt - work normally) I get an error message (attached screenshot), it is file type allowed (attached screenshot). And before there was a notification that showed exactly what type don't like (or don't have it in the allowed ones).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: 12.16.2
- MongoDB Version: 4.0.18

![error_file_type_archive_rar](https://user-images.githubusercontent.com/562733/80074835-72ea6d80-8552-11ea-846a-37feb4d003a8.JPG)
![list_file_type](https://user-images.githubusercontent.com/562733/80074857-7aaa1200-8552-11ea-8b33-dd55c370821d.JPG)

**Comment by bbrauns** [comment]
you can try to check the mimetype on the commandline with the linux [file](https://linux.die.net/man/1/file) tool. Maybe it reports `application/vnd.rar` and you have to add that too.

**Comment by spanchy** [comment]
> you can try to check the mimetype on the commandline with the linux [file](https://linux.die.net/man/1/file) tool. Maybe it reports `application/vnd.rar` and you have to add that too.

Thank for answer, i tryed this.
Example:
root@chat:~# file --mime-type STS.rar
STS.rar: application/x-rar
root@chat:~#

i set this mime-type to settings and uploading this file to messages, and i see same error.

**Comment by sampaiodiego** [comment]
@spanchy what Operating System and browser are you using? mime types can be different depending on combination of both. some times the browser doesn't recognise the file format and send as `application/octet-stream`, so you might need to add that as allowed file types (but bare in mind many other files might be recognised as `application/octet-stream` not only `rar` files)

**Comment by spanchy** [comment]
> @spanchy what Operating System and browser are you using? mime types can be different depending on combination of both. some times the browser doesn't recognise the file format and send as `application/octet-stream`, so you might need to add that as allowed file types (but bare in mind many other files might be recognised as `application/octet-stream` not only `rar` files)

Hello @sampaiodiego, thank for answer. I now tryed upload from Mac OS + official rocketchat app 2.17.7, from Windows 10 + chrome browser - and see same error.

**Comment by sampaiodiego** [comment]
thanks @spanchy for the info.. have you tried adding `application/octet-stream` to allowed files type list?

**Comment by spanchy** [comment]
> thanks @spanchy for the info.. have you tried adding `application/octet-stream` to allowed files type list?

Hey again, i set up this application. I have now this:
`image/*,audio/*,video/*,application/octet-stream,application/zip,application/gzip,application/x-rar-compressed,application/xml,application/pdf,text/plain,application/vnd.ms-excel,application/msword,text/csv,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`

and test upload.. Congratulations, this is working! But "octet-stream" is not a good choise. Is there any way to fix this ?

**Comment by sampaiodiego** [comment]
> But "octet-stream" is not a good choise. Is there any way to fix this ?

right, `application/octet-stream` opens a wide range of files, but there is no other solution for this that you could do now. the technical reason behind this is that this information is provided by the client (either a web browser or an app).. we could try discover the mime type of a file by looking into his content, this will not cover all cases, but for sure will increase the number of known file types.

**Comment by Sys-Admin889** [comment]
I have the same problem.
