### ISSUE TITLE
Users/rooms failing to be marked up and interactable

### ISSUE THREAD

**Issue by Endareth** [RocketChat/Rocket.Chat#17408]
### Description:

When a message contains multiple tagged users/rooms, they're not being marked up as such. Single user or room works, but multiples don't. Happening across multiple client platforms, so assuming it's a server issue.

In addition, attempting to pull logs via the Admin menu is just timing out.
### Steps to reproduce:

1. In any room, type: `#general #general` and hit Return

### Expected behavior:

Message should show both instances of `#general` in blue and clickable

### Actual behavior:

Message shows `#general #general` as raw text, not clickable.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu 18.04.3
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 8.17.0
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Desktop 2.15.5
- Operating System: macOS

- Desktop App or Browser Version: iOS 4.6.4.295
- Operating System: macOS

### Additional context

Problem appeared in last couple of days. Persists over reboot.

### Relevant logs:

[rc.log](https://github.com/RocketChat/Rocket.Chat/files/4526387/rc.log)

**Comment by gabriellsh** [comment]
![image](https://user-images.githubusercontent.com/40830821/80262160-fc896080-8662-11ea-9231-480d999f1fbe.png)

I just tested this on open.rocket.chat (v 3.2.0-rc.1). Maybe take a look in you admin settings (Admin > Message > Markdown >  ), see if `Original` or `Markd` is enabled. I know that open server uses Original. If it says 'disabled', maybe that's your problem. I suggest you try both original & marked, then if you still face this, try a newer version.

Please, report back if you still face this. Thanks!

**Comment by Endareth** [comment]
Upgraded to latest 3.x stable, which is 3.1.1, no change.
Testing the different Markdown Parser settings, I get the following results:
Markdown Parser Disabled:
`@user.name`  -> **user.name**  (correct)
`@user.name  @user.name  -> @user.name`  (no markdown)

Markdown Parser Original:
`@user.name ` -> **user.name**  (correct)
`@user.name  @user.name  -> @user.name`  (no markdown)

Markdown Parser Marked:
`@user.name  -> @user.name` (no markdown)
`@user.name  @user.name`  -> `@user.name`  (no markdown)

And even with Original or Disabled, trying to use `@all` or `@here` is always failing.

**Comment by gabriellsh** [comment]
`@all` and `@here` have settings related to them if I remember correctly. They can even be disabled according to the number of users in the current room. But that's pretty much it, I'll reopen this then.

**Comment by Endareth** [comment]
Coming up to two weeks on this, no-one able to come up with any ideas, or at least point me at some source code to dig into?

**Comment by gabriellsh** [comment]
I'm not sure since I was unable to reproduce this bug @latest. You can try [our Support Channel](https://open.rocket.chat/channel/support) (go ahead and test it there too, but I think it'll work fine). Maybe someone there could have some insights into it.

**Comment by Endareth** [comment]
This is still an issue for us in v3.5.2.
