### ISSUE TITLE
Jitsi Meet (no usernames, the interface is unfriendly)

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#17410]
Hi all!

I try to use integrate Jitsi Meet for videoconference in Rocket.Chat.
but i want to solve 2 troubles:

1. usernames are not thrown from the chat to jitsi (i see just "me" and "fellow jitser")
2. interface is unfriendly. elements go out of bounds, they can't be closed, etc. the layout is terrible. Is there any way to solve this?

**Comment by flantascience** [comment]
Also experienceing issue #2.   When the video chat loads in the sidebar, it's cutting off part of the options like to go full screen.  I have to resize my desktop window manually to about 3/4 of the width of my screen and then it sort of adjusts/resizes and those controls become accessible.

**Comment by ankar84** [comment]
> 1. usernames are not thrown from the chat to jitsi (i see just "me" and "fellow jitser")

Try to implement jwt token authentication both in rc and Jitsi.
We have full names and avatar from rc in Jitsi.


> 2\. interface is unfriendly. elements go out of bounds, they can't be closed, etc. the layout is terrible. Is there any way to solve this?

Just try to set Jitsi in new window in rc settings, as @flantascience mentioned.

**Comment by flantascience** [comment]
Where do I find the JWT authorization token values?   I see where I can enter them inside of Admin -> Video Conference, but I'm not sure where to find the values.

**Comment by arpsyapathy** [comment]
@flantascience 
I configured JWT. It works thank you.
Tell me please can i use JWT and ldap too?
When i give url from Jitsi Meet another man (beyond the rocket chat) - he can't log in.

**Comment by flantascience** [comment]
I'm not really even sure how to configure this.  Not sure what 'JWT' even
is.

Jim Flannery

jim-flannery.com
p. 860-578-4966
e. jim@jim-flannery.com
s. jim_flannery

**Comment by ankar84** [comment]
> When i give url from Jitsi Meet another man (beyond the rocket chat) - he can't log in.

You need to configure 2 virtual host's - one with authorization (JWT in our case) and second for guests without authorization.
