### ISSUE TITLE
SMTP Errors

### ISSUE THREAD

**Issue by TheZLabs** [RocketChat/Rocket.Chat#17424]
Trying to use smtps for port 465 but whenever I send an email test this is the error I continue to get. I know these settings work because I am using them for SMTP on several other servers. Not sure what to do here and hoping for some suggestions.

Exception in defer callback: { Error: 140232797824832:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:  code: 'ECONNECTION', command: 'CONN' }

**Comment by sampaiodiego** [comment]
have you trying checking "IgnoreTLS" option? what rocket.chat version are you using?

**Comment by TheZLabs** [comment]
Yes I have tried literally every combination of settings without success. I have given up on this for now.
