### ISSUE TITLE
chat wont load through webbrowser

### ISSUE THREAD

**Issue by kilroyyy** [RocketChat/Rocket.Chat#17425]
i use rocket chat through a 3rd party business, however after clearing internet caches the chat room will no longer load? i can go through the same portal on my mobile and it works fine. just won't work on the laptop now...??

**Comment by TheZLabs** [comment]
You can't login? Or the chat itself won't display? Have you tried a different browser just to test?

**Comment by kilroyyy** [comment]
i go through the portal from a work website and the chat page thats supposed to load gets stuck on the 3 dots animation on a gray page. i can get through on internet explorer and on my phones chrome browser but this just started being an issue this morning randomly it seems.
