### ISSUE TITLE
Big Blue Button wont launch video chat - error enclosed

### ISSUE THREAD

**Issue by TheZLabs** [RocketChat/Rocket.Chat#17426]
I have installed webhooks on BBB server. Any suggestions or info would be appreciated.

Exception while invoking method 'bbbJoin' { Error: failed [404] <Map><timestamp>1587760578298</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton//bigbluebutton/api/create</path></Map>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1427/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1427/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1427/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:139:11)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)   response:     { statusCode: 404,      content: '<Map><timestamp>1587760578298</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton//bigbluebutton/api/create</path></Map>',      headers:        { server: 'nginx/1.10.3 (Ubuntu)',         date: 'Fri, 24 Apr 2020 20:36:18 GMT',         'content-type': 'application/xml;charset=UTF-8',         'transfer-encoding': 'chunked',         connection: 'close',         'x-application-context': 'application:production:8090' },      data: null } }

**Comment by TheZLabs** [comment]
Permissions issue related to calls.

**Comment by itsarectangle** [comment]
> 
> 
> I have installed webhooks on BBB server. Any suggestions or info would be appreciated.
> 
> Exception while invoking method 'bbbJoin' { Error: failed [404] 1587760578298404Not FoundNo message available/bigbluebutton//bigbluebutton/api/create at Object.exports.makeErrorByStatus (packages/http.js:176:10) at Request._callback (packages/http.js:140:24) at Request.self.callback (/snap/rocketchat-server/1427/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22) at emitTwo (events.js:126:13) at Request.emit (events.js:214:7) at Request. (/snap/rocketchat-server/1427/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10) at emitOne (events.js:116:13) at Request.emit (events.js:211:7) at IncomingMessage. (/snap/rocketchat-server/1427/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickDomainCallback (internal/process/next_tick.js:219:9) response: { statusCode: 404, content: '1587760578298404Not FoundNo message available/bigbluebutton//bigbluebutton/api/create', headers: { server: 'nginx/1.10.3 (Ubuntu)', date: 'Fri, 24 Apr 2020 20:36:18 GMT', 'content-type': 'application/xml;charset=UTF-8', 'transfer-encoding': 'chunked', connection: 'close', 'x-application-context': 'application:production:8090' }, data: null } }

Hi, i have the same problem.  How did you fix this?  Thanks
