### ISSUE TITLE
Powershell Invoke-RestMethod missing key email

### ISSUE THREAD

**Issue by rpelletierrefocus** [RocketChat/Rocket.Chat#17423]
I am trying to use powershell to create users but I keep getting the error. 

Creating a user does work just fine using curl, but there is no reason it should not wokr equally well using the code below.

ANy thoughts?

```
Invoke-RestMethod : {"success":false,"error":"Match error: Missing key 'email'"}
```
```
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("X-Auth-Token", "Px--4mkufQLWKSGft-Ys6BHog996-KQFVioabF12tNp")
$headers.Add("X-User-Id", "5KDj9pzEXpzAqNv6v")
$headers.Add("Content-type", "application/json")
$headers.Add("Content-Type", "text/plain")

$body = "{`"name`": `"Test Name`", `"email`": `"test@flmaine.com`", `"password`": `"anypassyouwant`", `"username`": `"uniqueusername`"}"

$response = Invoke-RestMethod 'https://chat.flmaine.com/api/v1/users.create' -Method 'POST' -Headers $headers -Body $body
$response | ConvertTo-Json
```

**Comment by 16bc** [comment]
I have same error when try POST request to /api/v1/users.create via python Requests lib.
Server return 400: {'success': False, 'error': "Match error: Missing key 'email'"}
User creator have 'create-user' permissions, but change it to Admin does not affect.
