### ISSUE TITLE
Packaging a Botpress module with Rocket.Chat SDK throw an error (Linux and MacOSX only - Windows is OK)

### ISSUE THREAD

**Issue by bollinim** [RocketChat/Rocket.Chat#17434]
Take a look at our [GitHub repository](https://github.com/metsrl/channel-rocketchat) for more details
Thank you in advance for any support

**Comment by bollinim** [comment]
Opened a bug fix on [Rocket.Chat GitHub](https://github.com/RocketChat/Rocket.Chat/issues/17434)

**Comment by yoshida-git-ai** [comment]
I'm running into the same issue in my CentOS 7 environment
