### ISSUE TITLE
After updating to 3.1.0 uploads to S3 larger than a couple KB fail

### ISSUE THREAD

**Issue by dimm0** [RocketChat/Rocket.Chat#17431]
### Steps to reproduce:
1. Set up uploads to S3
2. Try uploading a file

### Expected behavior:
The file uploads

### Actual behavior:
The upload stays at 0%.

For files smaller than 4K uplaods work fine.

### Server Setup Information:

- Version of Rocket.Chat Server: 
3.1.0
- Operating System: 
Centos 7.7
- Deployment Method: 
Docker
- Number of Running Instances: 
1
### Client Setup Information

- Desktop App or Browser Version:
Same in desktop app and browser
- Operating System:
Mac OS catalina

### Relevant logs:

From browser:

```
f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:517 POST https://rocket.nautilus.optiputer.net/api/v1/rooms.upload/4qfP9oFLxuCSsJyfX 413
send @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:517
ajax @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:517
e @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
_jqueryFormDataCall @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
upload @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
g @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
(anonymous) @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
confirm @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
click .js-confirm @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:973
(anonymous) @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
t._withTemplateInstanceFunc @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
(anonymous) @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
(anonymous) @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
h._withCurrentView @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
(anonymous) @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
delegatedHandler @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:750
dispatch @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:517
g.handle @ f0fdb1d5f46db47d60cfc7912a919a8d17f48fac.js?meteor_js_resource=true:517
```

**Comment by ankar84** [comment]
Not reproduced for me
RC 3.1.1
File storage S3 (Minio)
![image](https://user-images.githubusercontent.com/4023037/80276273-5421dd80-86f0-11ea-80fc-63028bc88f24.png)
![image](https://user-images.githubusercontent.com/4023037/80276281-5dab4580-86f0-11ea-8ca1-0e21b36f5372.png)

**Comment by antgel** [comment]
Happening for us as well in 3.1.0 and xxx. Maximum size set to 104857600 bytes (100MB). Would be great to get some resolution on this quickly, as it's a pretty critical feature. Happy to give the RC team access to our instance if that will help debugging. This is definitely a bug (see below for 413).

When trying to upload a 2MB PNG:
<img width="1430" alt="test-screenshot" src="https://user-images.githubusercontent.com/295571/80599008-e8fb4280-8a32-11ea-98c8-6c53f4a958f3.png">

At first it looks fine:
![image](https://user-images.githubusercontent.com/295571/80599096-0af4c500-8a33-11ea-9c6e-e10ff2cd6b4c.png)

Then I get the following (see red banner). Also note, a colleague gets a 413 on `/api/v1/rooms.upload` when trying to perform the same operation.
![image](https://user-images.githubusercontent.com/295571/80598762-8013ca80-8a32-11ea-92b5-fbb4e4a2e53c.png)

**Comment by dimm0** [comment]
Fixed by increasing file upload limit in NGINX proxy
