### ISSUE TITLE
LDAP User Group Filter

### ISSUE THREAD

**Issue by LogiEx7** [RocketChat/Rocket.Chat#17435]
Hello, 
I'm trying to import users from my LDAP but I have the impression my filter doesn't works in RocketChat. Can you tell me what the syntax for User Group Filter is. Or if you have ideas why it doesn't work.
Thank you in advance

The request I use from my RocketChat server in CLI : 

```
ldapsearch -x -H ldap://192.168.1.100 -D "CN=user1,OU=Utilisateurs,DC=ZZZ,DC=LOCAL" -b "DC=ZZZ,DC=LOCAL" -W "(&(|(memberOf=CN=ROCKETCHAT-Admins,OU=Groupes,DC=ZZZ,DC=
LOCAL)(memberOf=CN=ROCKETCHAT-Users,OU=Groupes,DC=ZZZ,DC=LOCAL)))"
```
The request I use in User Group Filter : 

```
(&(|(memberOf=CN=ROCKETCHAT-Admins,OU=Groupes,DC=ZZZ,DC=
LOCAL)(memberOf=CN=ROCKETCHAT-Users,OU=Groupes,DC=ZZZ,DC=LOCAL))
```

**Comment by ankar84** [comment]
**User group filter**:
`(&(sAMAccountName=#{username})(memberOf=CN=#{groupName},OU=RocketChat,OU=Applications,OU=Groups,DC=domain,DC=local))`
**User data group map**
```
{
	"APP_RocketChat_Role_admin": "admin",
	"APP_RocketChat_Role_moderator": "moderator"
}
```
We are also using AD group LDAP filter. 
Only members of **APP_RocketChat_ALL** group will sync to Rocket Chat
**User Search**
**Filter**:
`(memberOf=CN=APP_RocketChat_ALL,OU=RocketChat,OU=Applications,OU=Groups,DC=domain,DC=local)`

**Comment by LogiEx7** [comment]
Thank you very much for this return, it worked to import the users. But I have the impression that it doesn't take into account the **User data group map**. It adds all users with the user role.
