### ISSUE TITLE
Discussion names can't be edited to include special characters

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#17438]
### Description:

With the default setting of `Allow Special Characters in Room Names` (disabled): when discussions are created initially, you can use special characters (whitespaces for example) in the discussions name. As soon as it's created, the check is active and you can't use any special character anymore when editing the room name. 

### Steps to reproduce:

1. Make sure `Allow Special Characters in Room Names` is disabled (default state)
2. Create a new discussion
3. Name it `Whitespace test`

### Expected behavior:

It should not be possible to use special characters (according to `Allow Special Characters in Room Names` at least).

### Actual behavior:

It's possible to use special characters.

### Possible solution

We should not check for `Allow Special Characters in Room Names` when editing room names (just like we don't on initial creation)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: macOS

##### Demo

[<img width="999" alt="Bildschirmfoto 2020-04-27 um 10 51 20" src="https://user-images.githubusercontent.com/944459/80353040-0edae880-8875-11ea-8dec-dc9a9c202d05.png">](https://up.frd.mn/7oqALlH9Ua.mp4)

**Comment by sampaiodiego** [comment]
IMO that setting should not affect discussion names. the purpose of that setting is to not use special chars on the URL, and discussion names don't go to the URL.

so I'd say the bug actually at the room info panel that is restricting special chars even for discussions. wdyt? nice favicon btw 😅

**Comment by frdmn** [comment]
@sampaiodiego Okay, that way makes more sense. Thank you 😬!

**Comment by gabriellsh** [comment]
That screen was refactored recently, and this doesn't happen anymore
