### ISSUE TITLE
Log RocketChat events

### ISSUE THREAD

**Issue by GeorgianBadita** [RocketChat/Rocket.Chat#17436]
Hi,

I would like to intercept events regarding users (user created, user joined room.. etc) in RocketChat and send those events to some REST API endpoint. Does anyone know how to do that specifically? 
I'm thinking about: 
1. Webhooks
2. Creating a bot (but I'm not sure the bot has access to user data)
3. I've tried using Loggly but it didn't quite work

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
