### ISSUE TITLE
Input size font too small

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat#17447]
Hello, this picture demonstrate the rocket font size is too small than slack (or discord)
![image](https://user-images.githubusercontent.com/331816/79197497-1be9e780-7e32-11ea-8851-a7442ea39347.png)

Can you make-it bigger or add an option to configure rocketchat electron to change size ?

Thanks

**Comment by ankar84** [comment]
> This is not related to electron. But you can change it in `administration > layout > custom css` as a workaround.

Great advise, @gabriellsh 
I made it by adding this:
```
:root {
	--input-font-size: 1.2rem;
}
```
Default input-font-size was 0.895rem

**Comment by Xarkam** [comment]
Hi  @gabriellsh 
This is what I did after opening the issue.
I do not understand the reason for using a size so small by default.

**Comment by gabriellsh** [comment]
We are currently working in rewriting RC using our design system `Fuselage`. There's a lot of small 'problems' like this that will cease to exist in the mid-future.
