### ISSUE TITLE
More keyboard shortcuts if possible (dekstop and mobile)

### ISSUE THREAD

**Issue by rusty1281** [RocketChat/Rocket.Chat#17445]
This is not a bug, if anything its a plea for more features to make this greate platform even better. 

I use RC a lot with multiple servers, and I really don't like to use a mouse if I don't have to. Would it be possible to implement some more shortcuts?

For example, a quote and/or reply would be great. Editing my messages is great with UP key but clicking with a mouse to quote is really not. At least to be able to quote the last message if nothing else.

Also, if it would be possible to implement a quote/reply option on the mobile app as well as a gesture? Again not that calling up a menu on a mobile device breaks the method of usage like the mouse does on the desktop, but it would be nice if a swipe could be implemented to make communication a bit faster.

Thanks again for this great platform. Hope to see more features and improvments in the future.

**Comment by giterium** [comment]
And make it possible for the user to set the keyboard shortcut himself 😊
