### ISSUE TITLE
Feature Request: Set default notification settings for channels

### ISSUE THREAD

**Issue by abelbabel** [RocketChat/Rocket.Chat#17458]
Hi,

I want to set default notification settings for channels (for all channels in general and for a specific channel) as administrator. At the moment it's only possible that each user defines its own notification settings for each channel. This could be very uncomfortable if current default notification settings differ from personal notification needs.

Kind regards,
abelbabel

**Comment by tuxmartin** [comment]
@gabriellsh hi, do you have any news?
