### ISSUE TITLE
1000 limit push for Rocket.Chat free version

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#17461]
Hi all!

I see https://rocket.chat/pricing 1000 monthly for push notifications for free.
This is for public Rocket.Chat push gateway?

If i want used my custom apps with my FCM and APN - this is was unlimited or too 1000 limit?

**Comment by sampaiodiego** [comment]
this applies only when using our public push gateway. for your custom apps, rocket.chat will communicate directly to Apple and Google so the limit doesn't apply. 👍

**Comment by PhanSon95** [comment]
@sampaiodiego Hi, I have confused. As my understand by your answer above:
- If I build rocket chat and access to it via my custom domain. So the mobile app on Android & iOS doesn't limit push notification monthly. It's correct ? 
- And I have to configuration FCM and APN like question of @arpsyapathy ask above ? 
- Notifcation on rocket web also unlimited , right ? 
Thanks you.

**Comment by sampaiodiego** [comment]
@PhanSon95 on you rocket.chat, if you go to Admin > Push, you'll see a setting there called "Enable Gateway".. if you have that turned on, that's when the limits apply to you.

> If I build rocket chat and access to it via my custom domain. So the mobile app on Android & iOS doesn't limit push notification monthly. It's correct ?
if you're using our push gateway, the limits applies.. 

> And I have to configuration FCM and APN like question of @arpsyapathy ask above ?
if you have configured the FCM and APN keys for you custom app, you'll not be using our push gateway, so no limits applies to you

> Notifcation on rocket web also unlimited , right ?
right, these are push notification limits.. desktop notifications are not affected


please also take a look on the following docs
https://docs.rocket.chat/guides/administrator-guides/settings/push-notifications-admin-guide
https://docs.rocket.chat/guides/mobile-guides/push-notifications-1

**Comment by PhanSon95** [comment]
@sampaiodiego Yes, I cleared , thanks you so much about reply.
