### ISSUE TITLE
Desktop web browser client incorrectly escapes '&' (ampersand) as HTML entity

### ISSUE THREAD

**Issue by ceefour** [RocketChat/Rocket.Chat#17465]
### Description:

Ampersand incorrectly escaped by desktop web browser client

### Steps to reproduce:

Scenario 1:

1. Edit the channel description and include "&"

Scenario 2:

2. Post this message: [New RocketChat article: Introducing Rocket.Chat 3.1: Get To Know New Features & Updates](https://rocket.chat/2020/04/22/introducing-Rocket-Chat-3-1/)

### Expected behavior:

`&` is displayed as `&`

### Actual behavior:

In web client, `&` is displayed as `&amp;`

This does not happen with Android mobile app.

Scenario 1:

![image](https://user-images.githubusercontent.com/24123/80517724-b0665500-89af-11ea-8598-14823e87a522.png)

Scenario 2:

![image](https://user-images.githubusercontent.com/24123/80517572-7b5a0280-89af-11ea-813a-dc6f0e407f24.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Ubuntu 18.04
- Deployment Method: helm
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.2.6

### Client Setup Information

- Desktop App or Browser Version: Chrome 81
- Operating System: Ubuntu 18.04

### Additional context

Related to #6719, #6789, #10461

**Comment by gabriellsh** [comment]
I think this #16481 is supposed to fix it.

**Comment by gabriellsh** [comment]
Unfortunately that does not fix the system messages. We are planning on reworking the whole parsing system, as it's proved to cause some problems currently.
