### ISSUE TITLE
Can't add reaction in broadcast channels

### ISSUE THREAD

**Issue by horstepipe** [RocketChat/Rocket.Chat#17460]
### Description:

Hello

According to the documentation for broadcast channels
`https://rocket.chat/docs/user-guides/channels/`
`Users without permission won’t be able to react to messages.`

there should be a permission to react in broadcast channels? I'm admin and don't have the react button in these channels. Is this intended or just not implemented, yet?

### Steps to reproduce:

1. Create a broadcast channel
2. write a message
3. try to find the react button for this message (as admin)

### Expected behavior:

Seeing the react button besides the "start thread" button

### Actual behavior:

No react button besides the "start thread" button

### Server Setup Information:

- Version of Rocket.Chat Server:  3.1.1
- Operating System: Linux
- Deployment Method: Snap

### Client Setup Information

- Desktop App or Browser Version: 2.17.7
- Operating System: Win10

Thanks!

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/17687 any problem let me know
