### ISSUE TITLE
Old Edge and Firefox versions should be added to #17372

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat#17471]
Microsoft Edge 44.18362.449.0 can't load our ocket chat after upgrading from 3.0.12 to 3.2.0. 

_Note: This also applies to https://open.rocket.chat not only our server._

Console from Edge tells me:
```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
f7b399e7b4f55ca23796c5f5ffb38397508e176e.js (48,85068)
```

```
Version:                3.2.0
Database Migration:     188
Running Instances:      5
OpLog:                  Enabled
Deployment Method:      tar
OS Platform:            linux
OS Arch:                x64
OS Release:             4.9.0-12-amd64
Node Version:           v12.14.0
Mongo Version:          4.0.18
Mongo Storage Engine:   mmapv1
```

**Comment by antoine-roux** [comment]
Hello, I have the same behavior with my users.

Reported browser to fail are:
- Firefox 52.9.0
- IE 11.1039.17763.0
- Edge 44.17763.831.0

**Comment by antoine-roux** [comment]
The problem seems to have been introduced with this commit: d917c920e3a141ec2d32f8ce1eec121b3f4264cb

In the last https://www.npmjs.com/package/mimic-fn version, there is a use of the javascript spread operator which is not supported by Edge :(

Unfortunately, he commit has upgraded the mimic-fn.
"mimic-fn": "^1.0.0" -> "mimic-fn": "^3.0.0"

**Comment by AmatorPhasma** [comment]
Thanks @antoine-roux for this info.

My few Edge users will update to the newest or change the Brwoser to latest Firefox/Opera or use the Desktop App.

PS: Should I close here, because in my eyes this is not a bug or issue from rocketchat?

**Comment by antoine-roux** [comment]
It's not a but from Rocket.Chat, but I think you should leave the issue opened with a new title to let a chance to developers to add a condition on the new browser check webpage https://github.com/RocketChat/Rocket.Chat/pull/17372

For now, the only check made is IE>11
Maybe we can think to add others listed browser above ;)

I suggest to change the title to "Old Edge and Firefox versions should be added to #17372"

**Comment by klepptor** [comment]
From my point of view this issue should addressed asap! At least in big companies or government sites it's not that easy to switch to a new version of Edge! 

And that RC 3.2.0 would break the support for still supported (by MS) browser versions wasn't that clear for me. (ok, I know, there is https://rocket.chat/docs/getting-support/#supported-browser-versions)

**Comment by klepptor** [comment]
Thx a lot, RC 3.3.0-rc.x supports these browsers again! Not one day to early, I was about to kill a running server and start with RC 3.1.1 from scratch.

**Comment by tassoevan** [comment]
`mimic-fn` is now transpiled to ES5 and bundled, so it shouldn't be a problem anymore. Let us know about it otherwise.
