### ISSUE TITLE
RocketChat 3.2.0 API channels.addModerator

### ISSUE THREAD

**Issue by Reeply** [RocketChat/Rocket.Chat#17489]
### Description:

It seems that the channels.addModerator doesn't work as expected and always return error :

`{"success":false,"error":"The required \"roomId\" or \"roomName\" param provided does not match any channel [error-room-not-found]","errorType":"error-room-not-found"}`

Note : adding the user trough the web interface is working.

### Steps to reproduce:

1. Try to add a user as moderator for a private group with [channels.addModerator](https://rocket.chat/docs/developer-guides/rest-api/channels/addmoderator/)
2. Checking user exist with his ID :

`curl -H "X-Auth-Token: yXjC3v8u77OTJ6erzM10FzX-USQEgveZWD5knGMtXxA" -H "X-User-Id: quHi7SLWuve6AbB52" -H "Content-type: application/json" http://localhost:3000/api/v1/users.info?userId=L9DRPCgmicNohLEEs`

Response seem OK 
`{"user":{"_id":"L9DRPCgmicNohLEEs","createdAt":"2020-04-27T17:12:24.743Z","services":{"ldap":{"id":"fe5fdf4c0d914f449501836b1d63d146","idAttribute":"objectGUID"}},"username":"remi","emails":[{"address":"remi@doe.org","verified":true}],"type":"user","status":"busy","active":true,"roles":["user","admin"],"name":"Remi","lastLogin":"2020-04-30T09:56:27.407Z","statusConnection":"online","utcOffset":2},"success":true}`

3. Checking room exist with his ID : 

`curl -H "X-Auth-Token: yXjC3v8u77OTJ6erzM10FzX-USQEgveZWD5knGMtXxA" -H "X-User-Id: quHi7SLWuve6AbB52" -H "Content-type: application/json" http://localhost:3000/api/v1/rooms.info?roomId=uRhC26rkTtr5ujS2w`

Response seems OK 
`{"room":{"_id":"uRhC26rkTtr5ujS2w","name":"adminchannel","fname":"adminchannel","t":"p","msgs":5,"usersCount":2,"u":{"_id":"quHi7SLWuve6AbB52","username":"dimitri"},"customFields":{},"broadcast":false,"encrypted":false,"ts":"2020-04-30T09:46:19.672Z","ro":false,"_updatedAt":"2020-04-30T10:00:00.944Z","lastMessage":{"_id":"g6RcKBbkHZt7xdtJr","rid":"uRhC26rkTtr5ujS2w","msg":"Yes","ts":"2020-04-30T09:46:54.917Z","u":{"_id":"L9DRPCgmicNohLEEs","username":"remi"},"mentions":[],"channels":[],"_updatedAt":"2020-04-30T09:46:54.927Z"},"lm":"2020-04-30T09:46:54.917Z"},"success":true}`

4. Try to add the user as moderator on this room : 

`curl -H "X-Auth-Token: yXjC3v8u77OTJ6erzM10FzX-USQEgveZWD5knGMtXxA" -H "X-User-Id: quHi7SLWuve6AbB52" -H "Content-type: application/json" http://localhost:3000/api/v1/channels.addModerator -d '{ "roomId": "uRhC26rkTtr5ujS2w", "userId": "L9DRPCgmicNohLEEs" }'`

Response 

`{"success":false,"error":"The required \"roomId\" or \"roomName\" param provided does not match any channel [error-room-not-found]","errorType":"error-room-not-found"}`

I've try with the room name too, but with same result.
Can you please confirm that i'm using the right way and help me understand wath going wrong?

Thanks by advanced.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.0
- Operating System: Centos 8 / 4.18.0-147.8.1.el8_1.x86_64
- Deployment Method: packages with yum
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.33.0
- Operating System: Centos

### Relevant logs:

Curl return are with the command and there is no error in server logs
`
I20200430-08:16:35.882(2) LocalStore: store created at  
I20200430-08:16:36.037(2) LocalStore: store created at  
I20200430-08:16:36.037(2) LocalStore: store created at  
I20200430-08:16:40.921(2) Setting default file store to GridFS 
I20200430-08:16:40.944(2) LocalStore: store created at  
I20200430-08:16:40.944(2) LocalStore: store created at  
I20200430-08:16:40.944(2) LocalStore: store created at  
I20200430-08:16:41.942(2) Setting default file store to GridFS 
I20200430-08:16:55.586(2) (migrations.js:120) Migrations: Not migrating, already at version 188
I20200430-08:16:57.632(2) Using GridFS for custom sounds storage 
I20200430-08:16:57.707(2) Using GridFS for custom emoji storage 
I20200430-08:16:57.898(2) Updating process.env.MAIL_URL 
I20200430-08:16:59.141(2) ➔ System ➔ startup 
I20200430-08:16:59.141(2) ➔ +----------------------------------------------------+ 
I20200430-08:16:59.141(2) ➔ |                   SERVER RUNNING                   | 
I20200430-08:16:59.142(2) ➔ +----------------------------------------------------+ 
I20200430-08:16:59.142(2) ➔ |                                                    | 
I20200430-08:16:59.142(2) ➔ |  Rocket.Chat Version: 3.2.0                        | 
I20200430-08:16:59.142(2) ➔ |       NodeJS Version: 12.14.0 - x64                | 
I20200430-08:16:59.142(2) ➔ |      MongoDB Version: 4.0.18                       | 
I20200430-08:16:59.142(2) ➔ |       MongoDB Engine: mmapv1                       | 
I20200430-08:16:59.143(2) ➔ |             Platform: linux                        | 
I20200430-08:16:59.143(2) ➔ |         Process Port: 3000                         | 
I20200430-08:16:59.143(2) ➔ |             Site URL: https://something  | 
I20200430-08:16:59.143(2) ➔ |     ReplicaSet OpLog: Enabled                      | 
I20200430-08:16:59.143(2) ➔ |          Commit Hash: 9f732f5b56                   | 
I20200430-08:16:59.144(2) ➔ |        Commit Branch: HEAD                         | 
I20200430-08:16:59.144(2) ➔ |                                                    | 
I20200430-08:16:59.144(2) ➔ +----------------------------------------------------+ 
`

**Comment by gabriellsh** [comment]
The problem is that you're trying to add a moderator to a private room. Channels are public rooms, and thus uses the method `findChannelByIdOrName` which has this check:

```javascript
if (!room || (room.t !== 'c' && room.t !== 'l')) {
		throw new Meteor.Error('error-room-not-found', 'The required "roomId" or "roomName" param provided does not match any channel');
	}
```

You should be using `groups.addModerator`.
