### ISSUE TITLE
Disable viewing of all users in directory

### ISSUE THREAD

**Issue by huzaifahj** [RocketChat/Rocket.Chat#17491]
# Description

There needs to be a way to prevent users seeing other users. It's a big security / usability concern for my use case. It's okay if they're in the same private channel of course. Ideally they wouldn't be added to the General channel too.

# Steps to reproduce

Person can see all users in `Directory > All users` or in `General > Members List`.

# Expected behaviour

Permission to disable viewing of users in these areas, and any other I haven't thought of.

**Comment by huzaifahj** [comment]
Set `view-outside-room` to false.

**Comment by idominiki** [comment]
I unchecked "view-outside-room" for users. How can they see the users in there assigned groups  in Directory Tab?
