### ISSUE TITLE
Command to /ping a user (notify)

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#175]
I think we should have the ability to ping a user, sending him a notification. Notification shall not be repeated until the user has seen previous notification, as to not bother too much. Also, ping notifications must have the option of being disabled on user profile.

**Comment by rodrigok** [comment]
Why not just use mentions?

**Comment by marceloschmidt** [comment]
Yeah, I think that would be a better option :)
