### ISSUE TITLE
unable to create group direct messages - direct "message option" missing under "create"

### ISSUE THREAD

**Issue by narrington** [RocketChat/Rocket.Chat#17507]
users are unable to start direct messages with multiple users as the direct message option is not present under create. I have checked that users have create-d and create-p in permissions. This issue is not user or group specific as admin accounts are also unable to create DMs in this manner.

Note we are following the guide for creating multi user DMs (from here: [LINK](https://rocket.chat/docs/user-guides/direct-messages-between-multiple-users/) )

Users are able to create normal DMs by opening the directory and selecting a user. But this does not enable DMing multiple users which is a necessary function for us.

We are running rocket.chat version 2.4.11 on debian (buster) installed from snap.

**Comment by pierre-lehnen-rc** [comment]
The ability to create DMs with multiple users was introduced on version 3.1 of Rocket.Chat.
