### ISSUE TITLE
Can not login the iOS app, even with demo server

### ISSUE THREAD

**Issue by jjzhangg** [RocketChat/Rocket.Chat#1750]
I'm blocked by the Please wait message...

**Comment by Sing-Li** [comment]
@jjzhangg  - are you still experiencing this problem with the demo server?   Can you try uninstalling and installing the iOS app again?

**Comment by jjzhangg** [comment]
Hi, thanks for asking. I can now connect https://demo.rocket.chat with my iOS app now. I created a local server by docker, and I can access it correctly on my iOS Safari, but I can not get connected with the RocketChat app on the same iPhone. Do I need additional configuration to make it work?

**Comment by Sing-Li** [comment]
You need to make sure you're using the latest version of the code for your docker server - ideally the same as the demo.    Compare - https://demo.rocket.chat/api/info   with your server.  Closing this issue now.

**Comment by kxxoling** [comment]
@Sing-Li Same error here, the app I install on my server is version 0.18 while the online one is 0.19. But I've just installed it in docker a few hours ago, how should I upgrade it?

**Comment by Sing-Li** [comment]
Can you access demo server?

**Comment by kxxoling** [comment]
@Sing-Li Ah, I looked for the Dockerfile page, and found it just updated 9 hours ago which is about when I started installing RocketChat. So I pulled the newest image and restarted docker service, and cleared the cache of RocketChat app, and everything works fine now.

**Comment by Sing-Li** [comment]
Awesome.

**Comment by kxxoling** [comment]
@Sing-Li Really awesome work you've made!

**Comment by Sing-Li** [comment]
Thanks to the around the clock hard work of our globally distributed team of devs and contributors :grinning:
