### ISSUE TITLE
Uploading file error

### ISSUE THREAD

**Issue by Unsourire** [RocketChat/Rocket.Chat#17517]
Hello everyone,
When i want to upload a file i got the following error : 
`Error: EACCES: permission denied, open '/Whj3pGBqn8ePgdtc3' [ufs: cannot upload file]`

I installed ROcketchat in a docker.
Docker version 19.03.8,
Rocket.Chat 3.2.0
file sharing system : Filesystem

Part of my docker-conpose : 
----------------------------
```
services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: always
    volumes:
      - /uploadsRC:/app/uploads
    environment:
```
---------------------------------------

As i had a problem, I created on my host the /uploadsRC directory with the following permissions : `chmod ugo+wrx /uploadsRC`

here is the permissions in the container ( i changed the permissions for the uploads folder, because i had the problem):
```
-rw-r--r-- 1 rocketchat rocketchat  610 Apr 27 23:42 Dockerfile
drwxr-xr-x 1 rocketchat rocketchat 4096 Apr 27 23:24 bundle
drwxr-xr-x 2 rocketchat rocketchat 4096 Apr 29 21:17 uploads
```

Even with this configuration is not working. does anyone has an idea?
Thank you

**Comment by Unsourire** [comment]
i found it was necessary to add the path : /app/uploads
to the configuration in the upload files tab.

**Comment by KheireddineAzzez** [comment]
_### Error: EACCES: permission denied, stat ‘/home/dev/Projects/vendor-chat/data/db/_tmp/.meteorignore’_


**These two commands saved my life**
**

-  npm install --unsafe-perm


**

- And then ownership change command for current user.


sudo chown -R user:user path_to_rocketchat_codebase_directory 


   Example sudo chown -R **Alex** /myrocketchat

**Comment by nooblag** [comment]
How to fix this with a `snap` on Ubuntu Rocket Chat install?

**Comment by heroes1412** [comment]
on host machine, chmod 0777 to "/uploadsRC"

**Comment by Sx3** [comment]
> 
Run the below command
`sudo snap connect rocketchat-server:removable-media`

then create a folder on `/media/uploads`
configure the folder path on rocketchat server :)
