### ISSUE TITLE
Hide realname and username in compact layout breaks readability since 3.2.0

### ISSUE THREAD

**Issue by Exordian** [RocketChat/Rocket.Chat#17516]
### Description:
Before version 3.2.0 the compact layout could be configured to only have avatars shown instead of username and realname. This behavior was changed in [1] raised by the bug report [2].

While IMO this is fine for the layout described in the issue #16930 . I argue that for the compact layout the previous behavior was better. Typically I can identify people within channels with not too-many users by their avatar, while chanenls with a lot of users (>100), I just want to know that i'm writing with different individuals. The username/fullname is not that important and can be seen when hovering over the avatar.
However, it comes with the clear benefit that all chat lines start with the same vertical alignment. This makes the chat much more readable. 

I'd propose to preserve the old behavior for the compact layout only.

[1] https://github.com/RocketChat/Rocket.Chat/pull/16959
[2] https://github.com/RocketChat/Rocket.Chat/issues/16930

### Expected behavior:

Nice to read. Alignment is fine.

![](https://i.imgur.com/x0H6O0W.png)

### Actual behavior:

Eyes need to jump. A lot harder to read.

![](https://i.imgur.com/thl7lVU.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.1
- Operating System: Linux
- Deployment Method: Docker

**Comment by huzaifahj** [comment]
When I set `Accounts > Default User Preferences > MessageBox View Mode` to `Compact`, I get a 400 error, why?

Surely this would fix your issue. And then enable `Hide Usernames` in the same `Default User Preferences` area.

Another issue, when I enable `Hide Usernames` as above, it doesn't apply to the admin automatically, I have to enable it in my profile.
