### ISSUE TITLE
Fullname is replaced by account name in threads

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#17519]
### Description:

Since RC 3.2.1 the users are shown by their account names instead of user names in threaded replies.

On the main channel view the user names are resolved correctly.

### Steps to reproduce:

1. Set layout to show Real Names instead of account names (Admin -> Layout -> User Interface):
![Screenshot from 2020-05-04 14-25-48](https://user-images.githubusercontent.com/6958942/80963197-225af600-8e17-11ea-8a7a-4ab9d23a95dc.png)

2. Create a message on the channel.
3. Create a threaded reply to the message.

### Expected behavior:

Fullnames should be used in threaded replies.

### Actual behavior:

Account name is used instead of fullname in threaded replies:
![Screenshot from 2020-05-04 15-00-41](https://user-images.githubusercontent.com/6958942/80963652-1885c280-8e18-11ea-862f-7c3bf3e8d3b2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.1
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.18

### Client Setup Information

Firefox or Chrome

### Additional context

The issue started when we upgraded to RC 3.2.1. In RC 3.1.2 replies were still fine.

Out of two setups we have, only the one using Oauth-based accounts exhibits this issue. LDAP-populated does not.
However, the test message was created using a locally created account, and still has the same issue as the Oauth populated ones.

May be related to:
https://github.com/RocketChat/Rocket.Chat/issues/15662

**Comment by himpierre** [comment]
Maybe related to https://github.com/RocketChat/Rocket.Chat/pull/16343

My users complain about that missing option now. It's not possible anymore to have real name in the message window and username in the sidebar window. :(

**Comment by Gummikavalier** [comment]
Thanks @himpierre 

Also for the record that LDAP authentication based setup of ours that *does not* suffer from this issue currently *was* using the option `Set a User Name to Alias in Message` and `Use Real Name` when the previous option still existed.
I wonder if it now muddies the waters in the database for the working one.

The setup now with the issue was not using `Set a User Name to Alias in Message`.

**Comment by Gummikavalier** [comment]
I also could not find traces of the `Set a User Name to Alias in Message` under the settings collection in their databases on either RC instance. (I searched for the terms alias, full name, real name.)

I tested with new local accounts on both instances and only the newer instance has the issue.

I could not find any differences in the accounts themselves, apart from E2E parts that is enabled on the instance with issues.

I disabled E2E, but that did not help either.

**Comment by Gummikavalier** [comment]
Now we seem to get the thread names resolved in the threads, but very sporadically.

After refreshing the screen all resolved names change back to account names, and when the thread updates, some of the names get resolved, but not all.

I'm not a DB admin, but maybe this is issues with users collection (or whatever is used in threads) indexes?

**Comment by Gummikavalier** [comment]
Comparing `rocketchat_message` collection in the database for the both working and non-working instances shows that after the upgrade to RC 3.2.1 the non-working has stopped writing name attribute to the messages:

Working:
```
 	"u" : {
 		"_id" : "xxxxxxxxxxxxxx",
 		"username" : "testaccount",
 		"name" : "Test Account (temporary)"
 	},
```

Not working:
```
	"u" : {
		"_id" : "xxxxxxxxxxxxxx",
		"username" : "testaccount"
	},
```
However, as the messages posted directly on the channel still show the names correctly, there clearly is a method and purpose to resolve the Real Names from the account names in the code.

I don't know why our older and working instance still writes the name attribute to every message, nor do I know what would be the correct thing to do from 3.2.x onwards.

**Comment by Gummikavalier** [comment]
Aaand at least this part of the puzzle shows in that #16343 in @rodrigok 's change request.

Now I only wonder why the name attribute is still in use on our second instance.

**Comment by Gummikavalier** [comment]
@sampaiodiego This issue seems to be still active in RC 3.4.0 as depicted in the first post.

**Comment by Gummikavalier** [comment]
Additional note:

When the user writes a message to the thread, the account name is momentarily resolved into fullname. When you close the thread view and open it up again, all names have changed to account names, often even the first one.

**Comment by Gummikavalier** [comment]
We did a clean install with docker RC 3.3.3 image today, and the issue is replicated with LDAP-configuration enabled, so this seems to affect all or most new systems, and it is not related to Oauth config either.
We copied all settings from the old servers that didn't have issues to match 1:1, and we did not find any existing settings to be the triggering factor.

**Comment by jdsatava127** [comment]
We are experiencing the same issue using Docker image 3.5.4. Real Name displays fine everywhere outside of threads (normal messages and reactions), but displays username threads. I was able to manually edit a message in Mongo and set the "u.name" value for a message in a thread and that allowed the Real Name to display. Is the thread UI possibly expecting this value to be set rather than looking up the Real Name on the fly?

**Comment by Gummikavalier** [comment]
> Is the thread UI possibly expecting this value to be set rather than looking up the Real Name on the fly?

I think this is exactly how it is was supposed to work pre RC 3.2.1. It was removed on purpose in that release as can be seen in https://github.com/RocketChat/Rocket.Chat/pull/16343.

Our oldest, over 3 years old instance still writes `u.name` into the messages, and I suspect open.rocket.chat instance of the developers themselves does so too.

However, none of our newer installations do, even those pre-existing RC 3.2.1.

**Comment by Gummikavalier** [comment]
I created a new issue because the old one is likely to go unnoticed as closed one.
