### ISSUE TITLE
Theme is broken again 

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#17518]
The sidebar theme got broken again recently in the latest release. 

![image](https://user-images.githubusercontent.com/23088/80941869-7f23c580-8db1-11ea-9c71-7ebae1a664f0.png)

Should be orange with white text.

**Comment by MartinSchoeler** [comment]
Hello @robbyoconnor could you please give us more info on the issue? Like your specific server version and what variables have you changed. Thanks!

**Comment by Gummikavalier** [comment]
We had the same or similar issue as robbyoconnor.

In RC 3.1.2 the background color seemed to be derived from the `Primary` color.

In the latest release (3.2.x) there is a new color attribute `Primary Background` color that seems to overwrite the `Primary` color completely.

When we changed the Primary Background color to same as the Primary color, our old theme worked fine.

It is also confusing that some changes get applied immediately, but you still has to refresh the browser screen after changing any of the primary colors. If you don't, the font changes color too dark.

**Comment by robbyoconnor** [comment]
This happened once prior too...can you please stop doing these changes.
Just carry over values set prior...or even migrate them automatically
for us.

**Comment by robbyoconnor** [comment]
I literally can't get it to honor my old frame. 

Stop changing themes -- or at least ensure you honor the themes. You have like 3 sections where colors are specified and it's confusing as hell.

**Comment by robbyoconnor** [comment]
I'm on the latest -- 3.2.1

**Comment by robbyoconnor** [comment]
Okay going to close this. Please note in changelogs when theme modifications get affected.

**Comment by luixxiul** [comment]
how have you modified the theme?
