### ISSUE TITLE
Not able to setup cloud marketplace

### ISSUE THREAD

**Issue by gox-ai** [RocketChat/Rocket.Chat#17535]
I have setup chat for my website at flixcatalog.com/chat

I am trying to setup "Connectivity Services" but it fails. Clicking "Authorize" in https://cloud.rocket.chat/login?response_type=XXxxxxxx has no response.

Browser console has this error `oauth_workspace_client_different_account`.

I raised the issue in https://desk.rocket.chat/ but the issue is pending for 8 days.

Could you please link my account(paul@gox.ai) with cloud marketplace?

**Comment by thorin8k** [comment]
I'm having the same issue trying to connect my self-hosted instance to the cloud.

In DevTools, after login, it says:
400: oauth_workspace_client_different_account

**Comment by photoninger** [comment]
You are not alone... I have two instances which report themselves as connected to cloud but marketplace reports as not connected and I cannot install any apps.
Trying to disconnect and authorize again I get the same errors...
I also opend an issue in desk.rocket.chat, but after a first response nothing is happening anymore.
In the server logs I see:
 `RocketChat[70247]: Failed to sync with Rocket.Chat Cloud.  Error: internal_server_error`

**Comment by dredwilliams** [comment]
Same issue here.  Running new update to 3.2.2 server.  Same response from Linux client and web client.

**Comment by gox-ai** [comment]
Is there an alternative to installing Apps without the cloud connect?

**Comment by dredwilliams** [comment]
So ... did a complete reinstall, and it is now working.  The key difference is when I registered my (self-hosted) workspace.  Before, I'd just copied the token from the email into my app -- but this time I actually clicked the button in the email.  This actually completed the cloud side of the registration process which was missing before.  

Maybe a better wording in the email saying that clicking the button is REQUIRED would be useful here.

Not sure there is a way to re-start the registration process from scratch in a running workspace -- I did try to 'unregister' and start again, but it never sent me the email after the first time.

More data to consider ...

**Comment by gox-ai** [comment]
Hi @dredwilliams how did you get the token in the first place? I dint get any when I installed.

**Comment by dredwilliams** [comment]
When you do the install, in the setup wizard say that you want to register.  For me, that triggered an email from the cloud console with the link that you need to click (see above).  Below that link in the email is a token that can be pasted in the 'Connectivity Services' section of the admin menu.  This is the part that is unclear.  The email doesn't make it clear that you have to click the link in the email first -- the token is only in case something doesn't connect.

It seems, though, that you get one shot at registering your workspace -- if it doesn't work, you're toast.  I'd love to be wrong ...

**Comment by parannoide** [comment]
I'm having the same problem and cant afford to reinstall from _zero_.

**Comment by gox-ai** [comment]
hey @dredwilliams I dont see any place to paste the token code. Please see below. Strange, dint get the email either. Is this how your screen is aswell?
![image](https://user-images.githubusercontent.com/38753278/81955523-d3d40580-9627-11ea-8159-51ee537e1159.png)

**Comment by parannoide** [comment]
> hey @dredwilliams I dont see any place to paste the token code. Please see below. Strange, dint get the email either. Is this how your screen is aswell?
> ![image](https://user-images.githubusercontent.com/38753278/81955523-d3d40580-9627-11ea-8159-51ee537e1159.png)

Just like mine. This menas that you alread connected, and you can confirm that on https://cloud.rocket.chat/, but like here, you should fail to log in.

**Comment by dredwilliams** [comment]
@gox-ai @parannoide if you are at that screen, it is too late.  It wouldn't let me log into a cloud console, and it wouldn't add this instance to the login I'd already set up.

If you look in your cloud console and you see your workspace there, you might be able to hit Disconnect and then try to re-register -- but be sure you click on the link in the email that will hopefully be sent.  If I remember correctly, after you hit Disconnect, that button will be replaced by one that says 'Register' (or something like that).  When you hit that button, you will see a box to put in the token from the email.  Sorry I'm not more precise, but I tried a lot of things and it's all mushed together in my memory.

I can't confirm this will work ... and I'd rather not trash the workspace I have now that it is working!

**Comment by lichti** [comment]
I solved with these steps:

1. go to Connectivity Services, click in disconnect.

2. Stop the rocket.chat server - in my case systemctl stop rocketchat

3. connect in mongdb

3-1. db.rocketchat_settings.remove({"_id": "Cloud_Workspace_Id"})

3-2. db.rocketchat_settings.remove({"_id": "Cloud_Workspace_Client_Id"})

3-3. db.rocketchat_settings.remove({"_id": "uniqueID"})

4. start the rocket.chat server - in my case systemctl start rocketchat

5. go to Connectivity Services and make a new register to rocket.chat cloud

**Comment by parannoide** [comment]
I've used the snap installer, and I dont know how to access the mongodb.

**Comment by nmindz** [comment]
The fix proposed by @lichti just saved our workspace from a complete reset. It indeed works and resets the Connectivity Services panel back to a clean state. We were able to re-send the verification e-mail, click the link and finally validate the workspace with RocketCloud.

**Comment by IvanOpanasiuk** [comment]
Hello everyone . I try install plugin for my Rocketchat with marketplace (on localhost). But it doesn't work correctly. I connected to cloud by steps:
1.go to Connectivity Services, click in disconnect.
2.Stop the rocket.chat server - in my case systemctl stop rocketchat
3.connect in mongdb
3-1. db.rocketchat_settings.remove({"_id": "Cloud_Workspace_Id"})
3-2. db.rocketchat_settings.remove({"_id": "Cloud_Workspace_Client_Id"})
3-3. db.rocketchat_settings.remove({"_id": "uniqueID"})
4.start the rocket.chat server - in my case systemctl start rocketchat
5.go to Connectivity Services and make a new register to rocket.chat cloud
Thanks to @lichti. But I can't install plugin still. Rocketchat server console responded me: 
"
Failed to resolve module: net
Failed to resolve module: stream
Failed to resolved 2 modules for Hex v0.0.1!
"
And cliend console responded : 
"
Failed to load resource: the server responded with a status of 400 (Bad Request)
Request URL: http://localhost:3000/api/apps/
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:3000
Referrer Policy: origin-when-cross-origin
"
Maybe someone had problem like this and I can get some help
Could you please help me with this issue?

**Comment by DetoXicer** [comment]
i solved this issue with finding out the first registered email and logged in with that at the Connectivity Services

**Comment by parannoide** [comment]
> i solved this issue with finding out the first registered email and logged in with that at the Connectivity Services

That solved my problem too. Thanks.
