### ISSUE TITLE
Rocket.Chat not working in Microsoft Edge

### ISSUE THREAD

**Issue by klepptor** [RocketChat/Rocket.Chat#17530]
#### Description:

RC doesn't show login page in Microsoft Edge, it just stays at the 3 dots loading page. 

Works in Chrome, Opera and Firefox without any issues.

See also [here](https://forums.rocket.chat/t/rocket-chat-not-working-in-microsoft-edge/6807).

### Steps to reproduce:

1. Open RC in Browser, e.g. chat.server.local:3000

### Expected behavior:

Login page should be opened

### Actual behavior:

Keeps loading and loading and loading

![Unbenannt](https://user-images.githubusercontent.com/3921511/81054926-fd728b80-8ec7-11ea-9a1f-3428abfbe510.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.1
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Microsoft Edge 44.17763.831.0, Microsoft Edge 42.17134.1.0
- Operating System: Microsoft Windows 10 Enterprise 1809, 1803

### Relevant logs:

Edge Console
![grafik](https://user-images.githubusercontent.com/3921511/81054606-6279b180-8ec7-11ea-8652-3965ed6e7276.png)

**Comment by luixxiul** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/17471?

**Comment by klepptor** [comment]
Oh, your're right! I only checked the topics of the other open issues! Sorry!
