### ISSUE TITLE
Document self hosted server push notification set up

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1753]
I can't find any docs describing how to set up push notifications for Apple and Android devices running the App Store and Google Play versions of the apps.

The "Certificates and Keys" section of the settings is currently empty. Some guidance on how to configure this properly would be great.

**Comment by engelgabriel** [comment]
Are you going to recompile the Cordova apps yourself?

**Comment by engelgabriel** [comment]
If you are just using our current app at the store.. you can only turn on the gateway option on the admin panel.

**Comment by tanc** [comment]
I'm just using the current apps from the store. Is it possible to use push notifications without recompiling?

**Comment by engelgabriel** [comment]
yes.. just turn on the gateway

**Comment by tanc** [comment]
ok great! Will try and report back. Do I keep the default gateway (https://rocket.chat) or change it to my host?

**Comment by tanc** [comment]
oh! Easy. Its working! Thanks so much for the quick response.
