### ISSUE TITLE
Rocket Chat Freezes in Chrome On Mac When Deleting A Message

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#17543]
### Description:

Rocket Chat Freezes in Chrome on mac when deleting a message. Version of chrome on mac is Version 81.0.4044.138 (Official Build) (64-bit)

### Steps to reproduce:

1. Attempt to delete a message
2. Chrome freezes, and message isn't deleted.

### Expected behavior:

Chrome to not freeze and for message to be deleted.

### Actual behavior:

Chrome freezes and message is not deleted.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 3.0.12
- Deployment Method: Tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.14.0
- MongoDB Version:4.0.18

### Client Setup Information

- Desktop App or Browser Version: Desktop
- Operating System: MacOS

**Comment by gabriellsh** [comment]
Do you see any logs on the browse console or the server console?
