### ISSUE TITLE
Can any one help to provide the way to set up notification for Android Device?

### ISSUE THREAD

**Issue by souliyo** [RocketChat/Rocket.Chat#1755]
I download the source code Rocket Chat on Cordova platform. Now I can set up the notification on the iOS devices, how ever, I still can't get notification on Android device. I did try many way including getting the GCM and Project ID into the setting and there is still no luck. 

FYI: I am hosting my rocket.chat on Heroku server 

thank you

**Comment by lvh1** [comment]
if you use the rocket.chat gateway 
![](http://i.imgur.com/iAObxVT.png)
a GCM API key and project number is all you need. 
Don't know how it works without using the gateway, sorry.

**Comment by souliyo** [comment]
Thank you, it works now. I am wondering how can we use our own gateway like http://mywebsite.com

**Comment by lvh1** [comment]
I was wondering, can you actually set up the push notification for iOS devices without signing up for the (99 euro costing) developer program? Or did you already have that?

**Comment by souliyo** [comment]
I already have the developer account. I can't see the other ways.

**Comment by Sing-Li** [comment]
Closing this now.   Using your own gateway for mobile notifications  is a general android programming issue/topic. You can seek help in https://demo.rocket.chat/  from community members.
