### ISSUE TITLE
Directory tab images missing with Rocket Chat installed in subdirectory

### ISSUE THREAD

**Issue by raghav-khunger** [RocketChat/Rocket.Chat#17558]
### Description:

We are using RocketChat install on Docker (Ubuntu). We have installed RC in a sub-directory named "chatrc".  Screenshot of docker compose.yml:

![image](https://user-images.githubusercontent.com/904902/81263539-75be8580-905d-11ea-9676-d79c4cf1e197.png)

### Steps to reproduce:

1. Download RocketChat 3.1.1
2. Install it using Docker.
3. In the YML file, set the instance to run inside a subdirectory named "chatrc".
4. Run docker-compose.

### Expected behavior:
Images in directory>>channels, directory>> users should come:

![image](https://user-images.githubusercontent.com/904902/81264032-60962680-905e-11ea-827d-5e3be83fb71c.png)

### Actual behavior:

Images in directory>>channels, directory>> users are not coming

![image](https://user-images.githubusercontent.com/904902/81264157-920ef200-905e-11ea-8d63-c9fbafec1eeb.png)

### Server Setup Information:
Version of Rocket.Chat Server: 3.1.1
Operating System: Ubuntu 18.04
Deployment Method: Docker
Number of Running Instances: 1
### Client Setup Information

Desktop App or Browser Version: Chrome/FF
Operating System: Ubuntu/Windows

### Additional context

The issue is that the images are not having a subdirectory path here:

![image](https://user-images.githubusercontent.com/904902/81263594-925abd80-905d-11ea-8be3-9bc36948a7b4.png)

If there had been the subdirectory path in the images then the images should have been working like this:

![image](https://user-images.githubusercontent.com/904902/81263736-dcdc3a00-905d-11ea-9594-5c8be0ac85a4.png)

**Comment by JoshMcCullough** [comment]
Note: also an issue when you start a chat w/a new user -- see #17623.

**Comment by ggazzo** [comment]
hey @raghav-khunger and @JoshMcCullough I provided a fix, I made a small fix changing how we get the url base and it was enough ...BUT we are not supporting subfolders officially anymore :/ it means PRs are welcome, but I have no commitment in provide properly fixes for this situations

**Comment by JoshMcCullough** [comment]
Not supporting running in a subdir? That seems kind of nuts ... ??

**Comment by ggazzo** [comment]
@JoshMcCullough, believe me, I feel your pain...
Please there is a thread about, I'm quite sure they will listen/read your opinions :)
https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371

**Comment by JoshMcCullough** [comment]
@ggazzo I did post there -- thanks for the link and the heads up.

Also, does your PR also fix this, when viewing a direct message?

![image](https://user-images.githubusercontent.com/4859660/82273550-be264f00-994b-11ea-90e7-fa8de9c64ab5.png)
