### ISSUE TITLE
[BUG] Mouse move cancels modal windows

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17562]
### Description:

Users complain about when they manipulate mouse a little bit outside modal windows it's just disappeared with all unsaved changes.

### Steps to reproduce:

1. Open any modal window - Upload file as example
2. Move mouse left button pressed outside the window or just click outside the window
3. Modal windows canceled

### Expected behavior:

Every modal windows (Upload file, create channel, create discussion) must remain on screen until action button (process or cancel) is pressed.

### Actual behavior:
When user swipe mouse cursor or click outside the window - it disappears as if cancel was pressed

![modal](https://user-images.githubusercontent.com/4023037/81278427-55db9180-905e-11ea-9e9f-49ab3501b1ee.gif)

### Server Setup Information:
open.rocket.chat has that bug
And I experienced that bug for a long time (since 2.0.X versions definitely)

**Comment by ankar84** [comment]
Issue still here

**Comment by sarcXD** [comment]
Hi I can take a look at this issue, since this'll also be the first issue I work on, it'd help a lot if anyone could let me know if this is where I post any queries or any issues I may face during development (not just this feature but working on the codebase as a whole), or perhaps there's someplace else for that. 
Thanks in advance.

**Comment by ankar84** [comment]
Little update - 3.6.3 server version - issue still persist.

**Comment by tharzeez** [comment]
@ankar84  My PR will fix this issue

**Comment by ankar84** [comment]
> @ankar84 My PR will fix this issue

Wow! Great!
Wait to test it!

**Comment by ankar84** [comment]
Still an issue in 3.16.3
Strange, most of elements are written in React, but that problem still not fixed.
@johncrisp can you look at this?

**Comment by debdutdeb** [comment]
Present in 3.17.0

**Comment by tharzeez** [comment]
Below PR will close this issue, I can add this commit to latest tip and push
https://github.com/RocketChat/Rocket.Chat/pull/19152

**Comment by samad-yar-khan** [comment]
@ankar84  @debdutdeb  I am not able to replicate the issue, I think it has been fixed and should be closed. Let me know if you guys are still able to replicate the issue.

**Comment by ankar84** [comment]
Yes, looks like it fixed already in 4.3.1
