### ISSUE TITLE
Which docker image can I use?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#17564]
Hi all!
Which docker image can I use?

I configure by docker compose by official doc:
https://rocket.chat/docs/installation/docker-containers/
The documentation specifies the image "rocket.chat:latest" , but its Rocket.Chat version is very different (3.0.12) from the current version (3.2.1).
As I understand it, there is still an image of "rocketchat/rocket. chat". It is updated stably.
Which Docker image should I use?
https://hub.docker.com/_/rocket-chat
or
https://hub.docker.com/r/rocketchat/rocket.chat
?

**Comment by luixxiul** [comment]
Though this issue should be transferred to https://forums.rocket.chat/ I also would like to know about that.

**Comment by robbyoconnor** [comment]
Both are the same thing @arpsyapathy. Use `latest` tag for the latest release and `develop` tag for the bleeding edge (not recommended unless you want to deal with breakage occasionally)

**Comment by bbrauns** [comment]
They are not the same thing. The following could bite you if storage mode is "filesystem":
```
root@chat:~# docker run --rm -it rocket.chat:3.0.12 id
uid=999(rocketchat) gid=999(rocketchat) groups=999(rocketchat)
root@chat:~# docker run --rm -it rocketchat/rocket.chat:3.0.12 id
uid=65533(rocketchat) gid=65533(rocketchat) groups=65533(rocketchat)
```
