### ISSUE TITLE
Add support for jitsi-token-moderation-plugin

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17563]
[Jitsi integration in Rocket.Chat with JWT authorization](https://github.com/RocketChat/Rocket.Chat/pull/12259) works very good!
But we need that only first user in call (actually user who creates the room) is granted moderator rights.
But with JWT authorization enabled in Jitsi all JWT authenticated users gets moderator permissions.
There is a nice [jitsi-token-moderation-plugin](https://github.com/nvonahsen/jitsi-token-moderation-plugin) lua module that can help.
All we need is first user who start the call use URL with **moderator:true** encrypted in JWT token and channel blue button **Click to Join** should open regular URL with JWT token without moderator in it.

@alonelion1987 Roman, can it be done?
@geekgonecrazy Aaron, can you take a look?

PS I also [opened issue](https://github.com/jitsi/docker-jitsi-meet/issues/554) in Jitsi, but RC implementation could be more elegant, IMHO.

**Comment by geekgonecrazy** [comment]
Yup if you wanted to do this properly take a look at the code that generates the jwt.  Then if user has a role of owner/moderator of channel or admin could add that property in.

**Comment by alonelion1987** [comment]
Hi, I don’t know if this topic will help you? I have been asking a question about the moderator here for a long time:

[https://community.jitsi.org/t/how-to-make-a-single-moderator/15332](https://community.jitsi.org/t/how-to-make-a-single-moderator/15332)

**Comment by ankar84** [comment]
Please don't close that issue. 
Maybe someone from community will make a pr for that.

**Comment by geekgonecrazy** [comment]
Maybe this could be made more generic to do mapping of role and such to token.  Something customizable enough to fit multiple cases.  Especially since this particular solution proposed isn’t the only way you could do it

**Comment by ankar84** [comment]
Please don't close that issue.
Maybe someone from community will make a pr for that.

**Comment by laliluna** [comment]
@ankar84, @alonelion1987  Having only the first user be the moderator can be configured on the Jitsi side. Have a look in the prosody configuration. There are modules loaded from a plugin directory and one module is "muc_allowners". In that case, you don't want this.

The lua plugins allows to configure rooms based on the token information. This is how usernames and the like and even the avatar is fetched.  jitsi-token-moderation-plugin uses a flag, but to allow more flexible handling it would be better to include the user roles as well. This allows to configure the jitsi room very flexible.

I will have a look at the related code, to see if a pull request is easy to do.

**Comment by laliluna** [comment]
@geekgonecrazy a patch adding the field looks trivial. Is adding roles and the isModerator flag acceptable as default behaviour, or does this need to be configured.

**Comment by ankar84** [comment]
> Having only the first user be the moderator can be configured on the Jitsi side. Have a look in the prosody configuration. There are modules loaded from a plugin directory and one module is "muc_allowners". In that case, you don't want this.

It's not quite true for [secure domain](https://community.jitsi.org/t/how-are-modersators-selected/29100/28?u=anton_karlan) (when using JWT tokens for authentications).
I just test it (removed `muc_allowners` from folder, restart `prosody` and `jicofo` and nothing changed).

So, a little enhancements are needed in RC to support  **jitsi-token-moderation-plugin**

**Comment by ankar84** [comment]
I think with new Jitsi version 2.0.5765 (21-04-15) that feature implemented from Jitsi side.
I asked a question [here](https://community.jitsi.org/t/set-role-for-meeting-participants-with-api/72642/12?u=anton_karlan) but now all what I see is that only first call participant gets moderator role without any changes in Rocket Chat codebase.
I wait for Jitsi team answer, and if I'm right, I will close that issue.

**Comment by ankar84** [comment]
Solved that issue on Jitsi side with `enable-auto-owner = true` in `conference` section of `jicofo.conf` config.

**Comment by PlusaN** [comment]
@ankar84 Hi!
We have a similar problem, but we cannot solve it :(
Our Jitsi version 2.0.5963-1, installation without docker.

/etc/jitisi/jicofo/jicofo.conf:
```
# Jicofo HOCON configuration. See /usr/share/jicofo/jicofo.jar/reference.conf for
#available options, syntax, and default values.
jicofo {
  xmpp: {
    client: {
      client-proxy: focus.jitsi.oxagile.com
    }
  }
}
```
I tried change config file to
```
# Jicofo HOCON configuration. See /usr/share/jicofo/jicofo.jar/reference.conf for
#available options, syntax, and default values.
jicofo {
  conference: {
    enable-auto-owner: true
  }
  xmpp: {
    client: {
      client-proxy: focus.jitsi.oxagile.com
    }
  }
}
```
but it's not help me...
