### ISSUE TITLE
Document how to update the Rocket.Chat without losing data?

### ISSUE THREAD

**Issue by souliyo** [RocketChat/Rocket.Chat#1756]
Hello guys,

I couldn't find the document in wiki page about how to update the Rocket.Chat server side. Does any one have any tip or any way that you are using that work very well without losing the data? 

FYI: I am using heroku but if other people have the way for other server or cloud service I am willing to learn from you

Thank you

**Comment by Sing-Li** [comment]
@souliyo ... see the *deployment* section here and choose your cloud service:  https://github.com/RocketChat/Rocket.Chat/wiki

To keep data between updates, you will have to host and manage your own MongoDB instance, or use one of the many service providers - such as MongoLabs.

**Comment by synotna** [comment]
The heroku documentation does not explain how to update

**Comment by circa1977** [comment]
+1

**Comment by circa1977** [comment]
If you fork Rocket.Chat to your own GitHub account, you can authorize Heroku to access your GitHub account, and do a *manual deploy* of branch `master` to your Heroku app, all within the Heroku web UI. This is all under the Deploy tab in your Heroku app. @synotna

**Comment by synotna** [comment]
Good to know, for now I've come up with:

```
    git checkout master
    git fetch rc
    git pull rc _release-tag_
    git reset --hard _release-tag_
    git push -f heroku master
```

**Comment by vikramiyer** [comment]
Will the update and deployment via my cloned repo retain the branding customisation that I have done?

**Comment by dmoldovan123** [comment]
for update from source you need to run on ubuntu 16.04:
curl -L https://rocket.chat/releases/latest/download > rocket.chat.tgz
tar -xzvf rocket.chat.tgz
mkdir -p /var/www/
mv bundle Rocket.Chat
mv Rocket.Chat /var/www/
cd /var/www/Rocket.Chat/
cd programs/server/
npm install
cd /var/www/Rocket.Chat/
npm install -g forever
npm install -g forever-service
forever-service install -s main.js -e "ROOT_URL=https://localhost MONGO_URL=mongodb://localhost:27017/rocketchat MONGO_OPLOG_URL=mongodb://localhost:27017/local PORT=3001" rocketchat1
service rocketchat1 start

This is for one instance, if you whant to make multi instances put on port 3001...3005 and rocketchat1...5 to make 5 instances and off course use proxy(haproxy, nginx).
All settings for rocketchat is save on mongodb.
