### ISSUE TITLE
Setting profile bio shows <p> tags in user panel

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#17566]
### Description:

When you set a bio (new profile field introduced in 3.1.0) in your profile, it'll display the actual bio in the user panel wrapped within visible `<p>` tags.

### Steps to reproduce:

1. Set bio in profile
2. Open your profile in any channel
3. Notice how bio is wrapped in `<p>bio</p>`

### Expected behavior:

No visible HTML tags

### Actual behavior:

HTML tags shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Cloud
- Deployment Method: Cloud
- Number of Running Instances: Cloud
- DB Replicaset Oplog: Cloud
- NodeJS Version: Cloud
- MongoDB Version: Cloud

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: macOS 10.15.4

##### Bio set in profile

<img width="718" alt="Bildschirmfoto 2020-05-07 um 20 02 56" src="https://user-images.githubusercontent.com/944459/81329338-ad99ed00-909e-11ea-87eb-34a5caa4d323.png">

##### Bio shown in user panel

<img width="381" alt="Bildschirmfoto 2020-05-07 um 20 03 28" src="https://user-images.githubusercontent.com/944459/81329343-af63b080-909e-11ea-9fd0-c4dbed06569b.png">

**Comment by mariaeduardacunha** [comment]
Tested in the latest version (3.4.0-develop) and this issue doesn't happen anymore. If you happen to experience this issue again, please reopen this. Thanks!

**Comment by parannoide** [comment]
@frdmn and @mariaeduardacunha 

Still happening.

**Comment by parannoide** [comment]
Version of Rocket.Chat Server: 3.4.2
    Operating System: Linux
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: Habilitado
    NodeJS Version: v12.16.1
    MongoDB Version: 3.6.14

Client Setup Information

    Desktop App or Browser Version: 2.17.7
    Operating System: Ubuntu 20.04
