### ISSUE TITLE
Massive upadates on "rocketchat_permissions" durin Rocket.Chat start

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#17573]
### Description:

We are observing massive updates on collection `rocketchat_permissions`. During start of 9 Rocket.Chat instances cluster Rocket.Chat.Metrics shows 145000 updates. This collection has only 988 documents. I suspect that it might have impact on heavy load of Rocket and Mongo during start. Below attached screen from Rocket.Chat.Metrics

### Steps to reproduce:

1. Start Rocket.Chat on 9 instances
2. In rocket.Chat.Metrics check `oplog` graph

### Expected behavior:

No heavy load on Mongo and Rocket and no massive updates on collection `rocketchat_permissions` during start-up

### Actual behavior:

Massive updates on collection `rocketchat_permissions`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 9
- DB Replicaset Oplog: YES
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.16

### Additional context

![image](https://user-images.githubusercontent.com/50440047/81403937-c05f0100-9134-11ea-9a66-8c6c56cd3701.png)

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/17160
