### ISSUE TITLE
Jitsi Meet (button sign in Dropbox doesn't work)

### ISSUE THREAD

**Issue by HelenS93** [RocketChat/Rocket.Chat#17572]
Start Recording - Sign IN Dropbox - Antyhing changed

![image](https://user-images.githubusercontent.com/12817153/81394826-45451d00-912b-11ea-90b5-1fd428cb3524.png)

Version 2.2.0
Apps Engine Version 1.7.0

**Comment by luixxiul** [comment]
Is this an issue of Jitsi Meet, not RC, isn't it?
