### ISSUE TITLE
misbehaving of  "do not exclude discussion messages" option in prune room

### ISSUE THREAD

**Issue by mind74** [RocketChat/Rocket.Chat#17583]
### Description:

When pruning messages, discussion messages are pruned unless "Do not exclude discussion messages"
Maybe that checkbox must to say "Exclude discussion messages"

### Steps to reproduce:

1. Goto room options
2. Click on `Prune Messages`
3. uncheck "Do not exclude discussion messages"
4. Click `Prune`
### Expected behavior:
Discussion Messages must not be deleted

### Actual behavior:
Discussion Messages are deleted.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Linux
- Deployment Method: cloud
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System: Linus

**Comment by mind74** [comment]
in `cleanHistory.html` the `RetentionPolicy_DoNotExcludeDiscussion` label refers to `ignoreDiscussion`:
```
		<label class="rc-checkbox">
			<input type="checkbox" name="ignoreDiscussion" class="rc-checkbox__input">
			{{> icon icon="check" block="rc-checkbox__icon"}}
			<span class="rc-checkbox__text rc-text__small">{{_ "RetentionPolicy_DoNotExcludeDiscussion"}}</span>
		</label>
```
in `cleanRoomHistory.js`, the parameter `ignoreDiscussion` appears to ignore discussions in clean.

I think the error is in the translation of RetentionPolicy_DoNotExcludeDiscussion. Should it be "exclude discussion messages"?

Sorry for my english!

**Comment by gabriellsh** [comment]
I think the term `exclude` could have been misused in this case. I think changing the translations is good enough.
