### ISSUE TITLE
[Regression/feat] Importer no longer has button to unselect deleted users or channels

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat#17591]
### Description:

This is more a regression report / feature request than a bug. With the new import tool, unfortunately the button to deselect deleted users and channels is no longer there. It would be great to get this back. Especially, when importing large workspaces, this was a very useful feature.

**Comment by ggazzo** [comment]
please try to click on the checkbox located on the header... should work as the old button you are missing.... any problem let me know

**Comment by lpilz** [comment]
Cheers, was just not persistent enough I guess...
