### ISSUE TITLE
[BUG] Unintended behavior of "plus" button for Custom Emojis

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat#17592]
### Description:
When selecting a custom emoji and pressing plus, one does not add a new emoji, but rather updates the selected emoji.

Thus, one can accidentally overwrite an existing emoji while trying to add a new one via the plus button. 

### Steps to reproduce:

1. Add a custom emoji
2. Select said emoji
3. Press "plus" buttom to add new emoji

### Expected behavior:
A blank form for adding a new emoji appears.

### Actual behavior:
The form is filled with the information of the selected emoji.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.2

### Client Setup Information

- Desktop App or Browser Version: Firefox 76.0
- Operating System: Arch Linux

**Comment by ggazzo** [comment]
we changed the whole mentioned screen... please check 3.3.0-develop (:
