### ISSUE TITLE
[Slack incompatibility] Incoming Webhooks need to accept JSON payload with incorrect header

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#1759]
I've set up an incoming webhook for our project management app Taiga which has a slack plugin, but I'm only receiving empty messages in the channel when testing or when actual notifications are sent. I'd like to debug this but I'm unsure how to view the incoming payload in the logs.

I have set up verbose logging and I'm using PM2 to manage the rocket.chat processes. Using `pm2 logs` doesn't show me the incoming message data, it only shows me my user reading the message (as far as I understand it). I'm not sure yet where the issue is occurring, so I'm also trying to get some debug output from the other end. Can you provide any guidance on how to further debug the issue?

The empty messages look like: 
![fdefaeb2-abd7-11e5-9332-8513d91dd4fc](https://cloud.githubusercontent.com/assets/76320/12006728/77a66bc2-abda-11e5-86bc-b55945505777.jpg)

**Comment by Sing-Li** [comment]
@tanc  - when you setup the incoming webhook integration, the system provided a `curl` test URL.   You should run that command to test the webhook.   If that works ; and it should;  you need to make sure the caller is issuing the call in that format.

Otherwise, the production mode log in Rocket.Chat is not likely to be helpful.

**Comment by tanc** [comment]
Thanks, I tracked down the issue to the way the payload was being encoded at the other end. Supposedly the system is compatible with Slack so I'll feed back if I find there is some work to be done on the rocket end to make it 100% Slack compatible.

**Comment by Sing-Li** [comment]
@tanc Thank you.  That would be awesome.

**Comment by tanc** [comment]
@Sing-Li I've traced the issue to the request headers. In the Slack compatible software sending the payload there is no `'Content-Type': 'application/json'` and the message body fails to be added in RC. If I modify the code to add this header then RC accepts the message and all is well. As RC is supposed to be 100% Slack compatible and Slack works fine with the system sending the payload then I'm wondering whether RC needs to do something to allow JSON data without that header?

**Comment by tanc** [comment]
Related issue and more detailed info on the github repository dealing with the outgoing payload: https://github.com/taigaio/taiga-contrib-slack/issues/36

**Comment by Sing-Li** [comment]
@tanc Thank you  for your extra-mile effort!     The compatibility game is often played with _all in_, worts included.  Your detailed discovery is extremely valuable to us.   

I'll revive this ticket and update the heading to reflect the discovery.

**Comment by Sing-Li** [comment]
@tanc  - the compatibility problem has been fixed already!  

Please verify that it now works as expected when you get a chance.  

Thanks again for bringing it to our attention.

**Comment by tanc** [comment]
Fantastic! I can confirm this is now working when the content-type header is not sent. Thanks so much @Sing-Li and @engelgabriel
