### ISSUE TITLE
WebRTC can't use

### ISSUE THREAD

**Issue by Unsourire** [RocketChat/Rocket.Chat#17590]
Hello,
I have a problem with the integration of the WebRTC, when i activate the 3 options of the WebRTC module, I can't  make any call. There is not icone for making call.
But when i activate the jitsi videoconference, i have a phone icone and i can strat a videoconference.

How can we be able to strat a audio call with a stun server?

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2
- Operating System: debian stresh
- Deployment Method: docker
- Number of Running Instances:  1
- NodeJS Version:  v12.16.1
- MongoDB Version: 4.0.18

Thank you for your help.

**Comment by gabriellsh** [comment]
The icon for webRTC calls is inside the user info for some reason.
![image](https://user-images.githubusercontent.com/40830821/83059529-6b762280-a030-11ea-9a09-ae5ff0b4a8b3.png)

We're already plan to change that.
