### ISSUE TITLE
[IMPROVE] Remove isomorphic index files from folders

### ISSUE THREAD

**Issue by MarcosSpessatto** [RocketChat/Rocket.Chat#17608]
- [x] 2fa
- [x] accounts
- [x] action-links
- [x] analytics
- [x] api
- [x] apps
- [x] assets
- [ ] authorization
- [x] autolinker
- [x] autotranslate
- [x] bigbluebutton
- [x] blockstack
- [x] bot-helpers
- [ ] callbacks
- [x] cas
- [x] channel-settings
- [x] channel-settings-mail-messages
- [x] chatpal-search
- [x] cloud
- [x] colors
- [x] cors
- [x] crowd
- [ ] custom-oauth
- [x] custom-sounds
- [x] discussion
- [ ] dolphin
- [ ] drupal
- [x] e2e
- [ ] emoji
- [x] emoji-custom
- [ ] emoji-emojione
- [x] error-handler
- [x] favico
- [x] federation
- [x] file
- [x] file-upload
- [x] github-enterprise
- [x] gitlab
- [x] google-vision
- [x] highlight-words
- [x] iframe-login
- [x] importer
- [x] importer-csv
- [x] importer-hipchat
- [x] importer-hipchat-enterprise
- [x] importer-pending-files
- [x] importer-slack
- [x] importer-slack-users
- [x] integrations
- [x] invites
- [x] irc
- [x] issuelinks
- [ ] katex
- [x] lazy-load
- [x] ldap
- [ ] lib
- [ ] livechat
- [x] livestream
- [ ] logger
- [x] mail-messages
- [x] mailer
- [x] mapview
- [ ] markdown
- [x] mentions
- [x] mentions-flextab
- [x] message-action
- [x] message-attachments
- [x] message-mark-as-unread
- [x] message-pin
- [x] message-snippet
- [x] message-star
- [x] meteor-accounts-saml
- [x] meteor-autocomplete
- [x] metrics
- [ ] migrations
- [ ] models
- [x] nextcloud
- [x] notification-queue
- [ ] notifications
- [x] nrr
- [x] oauth2-server-config
- [x] oembed
- [x] otr
- [x] promises
- [x] push
- [x] push-notifications
- [x] reactions
- [x] retention-policy
- [x] search
- [ ] settings
- [x] slackbridge
- [x] slashcommands-asciiarts
- [x] slashcommands-archiverroom
- [x] slashcommands-create
- [x] slashcommands-help
- [x] slashcommands-hide
- [x] slashcommands-invite
- [x] slashcommands-inviteall
- [x] slashcommands-join
- [x] slashcommands-kick
- [x] slashcommands-leave
- [x] slashcommands-me
- [x] slashcommands-msg
- [x] slashcommands-mute
- [x] slashcommands-open
- [x] slashcommands-status
- [x] slashcommands-topic
- [x] slashcommands-unarchiverroom
- [x] slider
- [x] smarsh-connector
- [x] sms
- [x] spotify
- [x] statistics
- [x] theme
- [x] threads
- [x] token-login
- [x] tokenpass
- [x] ui
- [x] ui-account
- [x] ui-cached-collection
- [x] ui-clean-history
- [x] ui-flextab
- [x] ui-login
- [x] ui-master
- [x] ui-message
- [x] ui-sidenav
- [ ] ui-utils
- [x] ui-vrecord
- [x] user-data-download
- [x] user-status
- [ ] utils
- [x] version-check
- [x] videobridge
- [x] webdav
- [x] webrtc
- [x] wordpress
- [ ] ee

**Comment by ostapski** [comment]
@MarcosSpessatto 

Hi ... just a question - improving application is good
but will you guys fix the bugs ?
