### ISSUE TITLE
Set permission for a role with the API

### ISSUE THREAD

**Issue by cs35-owncloud** [RocketChat/Rocket.Chat#17601]
Hello everyone, 

I don't think it's a bug but more a way to use the API with permissions, sorry if I set it in "bug", there was nothing better.

I try to create a new role with several permissions from the API. I understood that if you want to add permission *A* to your new role, you have to set this permission to all the roles having the permission *A* before, else they would lose that permission.

This example:

`curl -H "X-Auth-Token: TOKEN" -H "X-User-Id: USERID" -d '{"permissions": [{"_id": "access-permissions", "roles": ["test"]}]}' 
 https://example.com/api/v1/permissions.update`

In this case, the role *test* would have *access-permissions* available, but the *admin* role would lose it.

Is it possible to create a role with some permissions without having to set these permissions to the previous roles ? It really is a hassle.

Thanks.

**Comment by akhayyat** [comment]
It is indeed a hassle to have to retrieve all existing permissions every time a role is to be updated. Any chances of this getting fixed?
