### ISSUE TITLE
Rocket.Chat installed via Ubuntu Snap no Websockets

### ISSUE THREAD

**Issue by khedrub** [RocketChat/Rocket.Chat#17603]
I installed Rocket.Chat via Snap on Ubuntu Server with SSL Cert from LetsEncrypt. 
Web-Client works perfectly, Desktop-(Windows)-Client works perfectly. But connecting via Android it tells me Websockets are not activated on this Server.

**Comment by ankar84** [comment]
1. Do web browser shows any errors in address bar? Certificate errors?
2. Do you actually see 101 response in Chrome DevTools Network?

**Comment by khedrub** [comment]
The certificate seems fine. 
When I open the site on my desktop via Chrome DevTools in the Network section I don't see a 101 response. 
The Installation in question is this one: https://team.tibet.de

**Comment by ankar84** [comment]
> The Installation in question is this one: https://team.tibet.de

Here is what I see in DevTools
![image](https://user-images.githubusercontent.com/4023037/82074778-79a97200-9705-11ea-99bf-03808d7d6d3d.png)
`Error during WebSocket handshake: Unexpected response code: 400`

**Comment by urmamb** [comment]
i am slso facing this issue. Has anyone solved it?

```WebSocket connection to ['wss://mydomain.com/sockjs/354/2jyit04h/websocket'](url) failed: ```

```
Version
6.2.2
Deployment ID
p6JqWMrLQceARxt4f
Apps Engine Version
1.39.1
Node Version
v14.21.2
Database Migration
294 (May 20, 2023 7:18 AM)
MongoDB
5.0.15 / wiredTiger (oplog Enabled
```

<img width="1437" alt="Screenshot 2023-05-29 at 4 09 32 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/25754081/91048aae-a681-44ee-8d47-c05de5cf9b78">

**Comment by tienhuynh17** [comment]
I am also facing this issue.
