### ISSUE TITLE
Disable Embed for Users not working for Bot

### ISSUE THREAD

**Issue by arsevys** [RocketChat/Rocket.Chat#17615]
Hi, en my platform rocketchat, In my rocketchat I try to put the username of the bot so that the preview is not used, but when I use the sdk of the rocketchat I receive two same messages, when I send a link

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
