### ISSUE TITLE
Issue with video call

### ISSUE THREAD

**Issue by gokul1989** [RocketChat/Rocket.Chat#1761]
I am seeing my own video in rocket.chat instead of the person whom I am chatting with.
Kindly help

**Comment by gokul1989** [comment]
I am not able to view the person who is chatting with me. I have verified that  cameras are working properly.

**Comment by geekgonecrazy** [comment]
Try a site like: http://iswebrtcready.appear.in/ make sure both ends are webrtc capable.

**Comment by vargasbo** [comment]
Seeing the same issue. One end point is Osx and other iOS. Is native app/safari iOS video chat not supported?

**Comment by Sing-Li** [comment]
@vargasbo @gokul1989 ... test both side here first ... https://test.webrtc.org/  - must pass all tests.

@vargasbo NO.  iOS will not work. Apple prefers FaceTime.

**Comment by vargasbo** [comment]
Everyone pref something; but doesn't violate agreement. [Tokbox] (https://tokbox.com/developer/sdks/ios/) support WebRTC on iOS. Tokbox wrote a native framework to handle this as their JS version has the same limitation. We should be able to do this same thing.

**Comment by saigop** [comment]
Hi,

Am using windows rocket chat client in windows 10, the other side is Acer Chromebook, my server is hosted in public network and it comes via SonicWALL firewall. 

In my firewall, 3000 port (TCP) is open. 

Where as am not able to do video or audio chat. Is there some port have to be opened up in the firewall for video chat? Any UDP ports to be opened? Please advice. 

The same setup i tested with NAT as well. 

More info: We have configured NAT for the server. 

Thanks.

**Comment by Sing-Li** [comment]
@vargasbo - your PR is certainly welcomed for this feature.  Let us know and we will create a new ticket for it.  Thanks in advance.   

@saigop -  (1)  have you tested BOTH SIDE here https://test.webrtc.org/  ?
                         IF NOT - please do.
                         IF SO - do they pass all tests.  If not, webrtc will not work with RC..

**Comment by Sing-Li** [comment]
Guys.  Closing this ticket.  For more timely response on support issues such as this, please use  the #support and #general channel on https://demo.rocket.chat

**Comment by gokul1989** [comment]
Hi,

Thank you for your update.
I have tested both sides and have passed all.
http://awesomescreenshot.com/0e05inuubc

**Comment by gokul1989** [comment]
Is this issue related to installation.?

**Comment by Sing-Li** [comment]
Yes. It might be.
Please get both sides to try it on https//demo.rocket.chat/

If it works, and it should, then troubleshoot your own server install.

**Comment by gokul1989** [comment]
Thank you for the information. All other options like audio, screen sharing etc are working fine except video call.I used the following steps to install the chat.RocketChat/Rocket.Chat

|   |
|   |  |   |   |   |   |   |
| RocketChat/Rocket.ChatRocket.Chat - Have your own Slack like online chat, built with Meteor. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


Can you please let me know if there is any other doc which I can follow for the installation.?
I have installed the master version from
RocketChat/Rocket.Chat
|   |
|   |  |   |   |   |   |   |
| RocketChat/Rocket.ChatRocket.Chat - Have your own Slack like online chat, built with Meteor. |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


 

    On Wednesday, December 30, 2015 8:16 PM, SingLi <notifications@github.com> wrote:
 

 Yes. It might be.
Please get both sides to try it on https//demo.rocket.chat/If it works, and it should, then troubleshoot your own server install.—

**Comment by gokul1989** [comment]
Thank you for the information. All other options like audio, screen sharing etc are working fine except video call.I used the following steps to install the chat.RocketChat/Rocket.Chat 

https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker

Can you please let me know if there is any other doc which I can follow for the installation.? I have installed the master version from

https://github.com/RocketChat/Rocket.Chat/tree/master

**Comment by ManoharPoreddy** [comment]
Hi @vargasbo ,

We have a hybrid app, video is not working.

Can you help please on detailing what you mean by "native framework" in the below?
Did you try this way? Can you share you input on this?
Is it a iOS/OSX library you created?
In which way, have you plugged it?

'Any' kind of details from you is appreciated.
(like, if you tried, or you know some details, or others)

It's a bit urgent for us.

Thank you

Manohar

---------
vargasbo commented on 29 Dec 2015

Everyone pref something; but doesn't violate agreement. Tokbox support WebRTC on iOS. Tokbox wrote a native framework to handle this as their JS version has the same limitation. We should be able to do this same thing.
---------
