### ISSUE TITLE
[BUG] Discussion filter is shown even though the functionallity is disabled

### ISSUE THREAD

**Issue by kaiiiiiiiii** [RocketChat/Rocket.Chat#17621]
Bug was introduced despite notice in the initial PR:
https://github.com/RocketChat/Rocket.Chat/pull/17103#issuecomment-617077043

<img width="506" alt="2020-05-12 13_41_14- NEW  Merge Sort List and View Mode menus and improve its UI_UX by ggazzo · Pull" src="https://user-images.githubusercontent.com/4711233/81683334-52794900-9456-11ea-8eaa-9e00858d6138.png">

Cheers

**Comment by ggazzo** [comment]
@kaiiiiiiiii as far I can see you are right about the bug, but not about the comment ...
> ... despite notice in the initial PR...
looking your image we can see a "pending" pending tag, that means you didn't finished your review
maybe you are used with comments over reviews and for some reason you clicked on the wrong place, I'm sorry if you felt ignored/alone but its not my fault(at least this time), feel free to comment/review any PR that I make and I will be happy to take it in consideration....

cheers
