### ISSUE TITLE
Directory / Profile avatars broken when hosted in subdirectory

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#17623]
### Description:

When viewing the directory, no avatars show up. The images are requested without the subdirectory (e.g. "/chat"). So the requested URL is "https://.../avatar/jim.smythe" instead of "https://.../chat/avatar/jim.smythe". Avatars work correctly in the sidebar and in chat.

The same issue exists when you start a new chat with someone, and are brought to the "You have joined a new direct message with" screen.

### Steps to reproduce:

1. with RC hosted in a subdomain (e.g. `/chat`)...
2. go to the Directory
3. notice that no avatars are displayed
4. right-click on an avatar and "Open Image in a New Tab" (or similar)
5. note that the URL is missing `/chat` after the domain

### Expected behavior:

Avatars should be visible, and should respect the configured hosting URL / subdirectory.

### Actual behavior:

Avatars do not show up.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: RHEL7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version:4.0.9

### Client Setup Information

- Desktop App or Browser Version: all browsers
- Operating System: N/A

**Comment by ggazzo** [comment]
duplicated of https://github.com/RocketChat/Rocket.Chat/issues/17558
