### ISSUE TITLE
API response inconsistency  

### ISSUE THREAD

**Issue by alonzzz** [RocketChat/Rocket.Chat#17620]
In some of the API endpoints, the response can include or not include a certain key. 
For example in `groups.listAll` the "Archived" key will be included for groups that are archived but will not appear at all for groups that are not.

I think that for the sake of API response consistency the same keys should always appear in a given response. e.g `{"archived": false}`.

Using the above example of `groups.listAll` and the missing "Archived" key, it will prevent the use of the query parameter to query unarchived groups.
Archived groups can be queried with `query={"archived": true}` but unarchived groups cannot be using `query={"archived": false} `since the key is missing instead of being with a value of false.

**Comment by gabriellsh** [comment]
Maybe take a look at https://docs.mongodb.com/manual/reference/operator/query/exists/. In my opinion this kind of behaviour is kinda expected when using mongodb, as it's a non relational database. I'll leave this open for now though.
