### ISSUE TITLE
rocketchat-server 2.4.12 w/ Nginx reverse proxy returns 502 Bad Gateway

### ISSUE THREAD

**Issue by mlanner** [RocketChat/Rocket.Chat#17633]
### Description:

Running rocketchat-server in a snap on Ubuntu 18.04.4 with Nginx as reverse proxy and certbot for Let's Encrypt certs. Certs are still good and valid. After upgrade to 2.4.12, Nginx returns 502 Bad Gateway.

I have errors in my `/var/log/nginx/rocketchat.access.log` saying:

```
2020/05/12 15:00:39 [error] 1043#1043: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 123.45.67.89, server: my.rocketchat.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "my.rocketchat.com"
```

I have three different instances running. Two of them are currently running 2.4.12 (with Nginx) in identical configs. Both these 2.4.12 instances return the same 502 Bad Gateway error. A third instance is running 2.4.11 and uses Apache as the reverse proxy. The server still on 2.4.11 is working as expected. All machines are fully patched.

### Steps to reproduce:

1. Snap updated itself (as designed)
2. 502 Bad Gateway
3. Server(s) has been rebooted for good measure

### Expected behavior:

2.4.12 shouldn't cause this problem.

### Actual behavior:

502 Bad Gateway

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.12
- Operating System: Ubuntu 18.04.4
- Deployment Method: snap
- Number of Running Instances: 3 (see explanation above)
- DB Replicaset Oplog: 
- NodeJS Version: embedded (in snap?)
- MongoDB Version: embedded (in snap?)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

Per above, errors in `/var/log/nginx/rocketchat.access.log`:

```
2020/05/12 15:00:39 [error] 1043#1043: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 123.45.67.89, server: my.rocketchat.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "my.rocketchat.com"
```

**Comment by mlanner** [comment]
One more thing ... it appears Mongo is not starting:

```
# systemctl status snap.rocketchat-server.rocketchat-server.service
● snap.rocketchat-server.rocketchat-server.service - Service for snap application rocketchat-server.rocketchat-server
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-12 15:57:24 PDT; 13s ago
 Main PID: 5517 (startRocketChat)
    Tasks: 2 (limit: 1092)
   CGroup: /system.slice/snap.rocketchat-server.rocketchat-server.service
           ├─5517 /bin/bash /snap/rocketchat-server/1436/bin/startRocketChat
           └─5563 sleep 15

May 12 15:57:24 chatter systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
May 12 15:57:25 chat rocketchat-server.rocketchat-server[5517]: Mongo is not available, can't start. Waiting 10 seconds and trying again
May 12 15:57:35 chat rocketchat-server.rocketchat-server[5517]: Mongo is not available, can't start. Waiting 15 seconds and trying again
```

**Comment by Neihn** [comment]
Did you try the resolution in this discussion? https://github.com/RocketChat/Rocket.Chat/issues/17628

**Comment by geekgonecrazy** [comment]
Closing in favor of #17628

**Comment by mlanner** [comment]
Thanks @Neihn ... great find. That subject title really didn't register for me as related to the problem.

Either way, by the time I woke up this morning and was ready to go revert, the snap had reverted by itself. Presumably this was done by the RC team issuing a new snap with the old 2.4.11 configs, @geekgonecrazy ?

Problem solved for now. :smile:
