### ISSUE TITLE
[SUGGESTION]: Add ability to mute threads

### ISSUE THREAD

**Issue by CC007** [RocketChat/Rocket.Chat#17638]
At the moment in public channels messages can be either read or unread and they can either be directed at you (through a mention or a thread that you are following).

At the moment it is not possible (or at least not easily unambiguously configurable) to set it so that you Get notifications for mentions, followed threads and normal messages in the channel, but not for threads that you don't want to be involved in, unless you are specifically mentioned. 

It is also not possible to make a channel not be marked as having unread messages when you get messages in a thread that you aren't following.

So to that extent, it would be nice if you could mute a thread and setting to set a thread to be de muted by default and be automatically unmuted if you are mentioned in that thread. 

It would also be nice if you could make this muting temporary.

**Comment by pjv** [comment]
One of the best little UI features of Signal on Android is an easy to find option that lets you mute a specific conversation for 1 hour, 2 hours, 1 day, 7 days, 1 year.

**Comment by CC007** [comment]
Any idea if this suggestion will ever be implemented?

**Comment by ggazzo** [comment]
I think we reached the desired behavior, you can unfollow the thread, then you will not receive notifications anymore unless somebody mentions you... if we gonna insert a better 'mute system notifications' like snooze we have properly issues/requests about, thanks for you time

**Comment by CC007** [comment]
I don't agree with this assessment. While you can prevent the notification number bubbles, you can't make a thread be automatically be marked as read. Therefore there could be threads that you want nothing to do with still causing a channel to be marked as having unread messages. It would be nice if you could disable that.
