### ISSUE TITLE
[CRITICAL BUG] Users are allowed to edit anyone message without option to disable this functionality

### ISSUE THREAD

**Issue by gabrielpetry** [RocketChat/Rocket.Chat#17639]
### Description:

Any user is allowed to edit anyone messages, and I there is no option to disable this functionality.
Also disabling the option to edit in the menu, does not disable this ability to edit message, only way to disable editing was to set it to -1 minute.

### Steps to reproduce:

1. Enable message edit, and set a time longer than 1 minute.
2. Ask a friend to send you a message
3. Click on the 3 dot in the right of his message, click edit
4. Edit the message and save

### Expected behavior:

Users only allowed to edit their own message or a explicitly option in the menu to disable this behavior.

### Actual behavior:

![bug](https://user-images.githubusercontent.com/24570030/81824651-1a344200-950c-11ea-89a3-b33727254c82.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: CentOs 7.7
- Deployment Method: docker # Oficial docker image
- Number of Running Instances: 3
- DB Replicaset Oplog: Activo
- NodeJS Version: v12.16.1 x64
- MongoDB Version: 3.6.15

### Client Setup Information

- Desktop App or Browser Version: Firefox 76 Both
- Operating System: Ubuntu 20.04 both

### Additional context

Disable editing does not work, time must be set to -1 to actually disable it.

The gif above was record if the configuration bellow:
![Captura de tela de 2020-05-13 10-34-16](https://user-images.githubusercontent.com/24570030/81825115-99c21100-950c-11ea-9b47-729e6dd12e3f.png)

### Relevant logs:

Nothing was said by the server

**Comment by gabriellsh** [comment]
Hey @gabrielpetry ! Long time no see...

Have you checked the `edit-message` permission? It is the one that allows to edit other peoples messages. See if it hasn't been mistakenly assigned to a role. It's usually only assigned to admins.

**Comment by gabrielpetry** [comment]
Hey-man,good seeing you again (that joke)

Yep, edit-message was assigned to **all the roles**, for some bizarre reason. I re-assigned to only the admin and now is working as expected \o|

Thanks for the help!
