### ISSUE TITLE
Attachments from the incoming webhook do not appear

### ISSUE THREAD

**Issue by antiseptikk** [RocketChat/Rocket.Chat#17636]
### Description:

Hi everyone, 
After upgrade instance to 3.x.x, the attachments from incoming webhook are not showed anymore.

I try to add the Github Action Notification from project and same problem.

Update : The attachments seems to be appear in android App 

### Steps to reproduce:

1. Create webhook
2. Test with postman or insomnia

```
{
  "channel": "@you",
  "text": "*Lint Check* Succeeded",
  "attachments": [
    {
      "color": "#2cbe4e",
      "fields": [
        {
          "short": true,
          "title": "ref",
          "value": "refs/heads/master"
        },
        {
          "short": true,
          "title": "event name",
          "value": "push"
        },
        {
          "short": true,
          "title": "workflow",
          "value": "Quality Assurance"
        },
        {
          "short": false,
          "title": "repository",
          "value": "***/***"
        },
        {
          "short": true,
          "title": "commit",
          "value": "Adding rocket.chat notification"
        },
        {
          "short": true,
          "title": "author",
          "value": "***"
        }
      ]
    }
  ]
}
```

### Expected behavior:

<img width="911" alt="Capture d’écran 2020-05-13 à 12 57 27" src="https://user-images.githubusercontent.com/1520152/81804453-66d24a00-9519-11ea-94d0-00cd0e9cd5dc.png">

### Actual behavior:

<img width="269" alt="Capture d’écran 2020-05-13 à 12 56 34" src="https://user-images.githubusercontent.com/1520152/81804444-63d75980-9519-11ea-9934-9246dbb8140b.png">

### Server Setup Information:

- Version of Rocket.Chat Server:  3.2.2
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: All
- Operating System: All

**Comment by EnCz** [comment]
Cannot reproduce on 3.2.0:

`curl -X POST -H 'Content-Type: application/json' --data '{"text":"*Lint check*: Succeeded","attachments": [{"color": "#2cbe4e","fields": [{"short": true,"title": "ref","value": "refs/heads/master"},{"short": true,"title": "event name","value": "push"},{"short": true,"title": "workflow","value": "Quality Assurance"},{"short": false,"title": "repository","value": "***/***"},{"short": true,"title": "commit","value": "Adding rocket.chat notification"},{"short": true,"title": "author","value": "***"}]}]}' [$ROCKETCHAT_INTEGRATIONS_URL]`

-> 

![image](https://user-images.githubusercontent.com/7642122/82038357-b6448180-96a3-11ea-902a-a60b7f4c318b.png)

Do you have your Integrations-Script activate?

**Comment by antiseptikk** [comment]
Hi @EnCz, integration script inactive
My version -> 3.2.2

**Comment by EnCz** [comment]
> Hi @EnCz, integration script inactive
> My version -> 3.2.2

Could you try to do it with the curl request I did?

Also you could try this:
- Activate Script in Webhook
- Paste this Logging-Script:
> class Script {
>   process_incoming_request({ request }) {
>     console.log('-----REQUEST-----');
>     console.log(request);
>     console.log('-----ATTACHMENTS-----');
>     console.log("attachments: %o", request.content.attachments);
>     return;
>   }
> }
- Go to "View Log"
- Request via Curl and watch Log what exactly is received

**Comment by antiseptikk** [comment]
Everything looks good

```
I20200518-08:08:47.369(0) -----ATTACHMENTS----- 
I20200518-08:08:47.370(0) attachments: [   {     color: '#2cbe4e',     fields: [       { short: true, title: 'ref', value: 'refs/heads/master' },       { short: true, title: 'event name', value: 'push' },       { short: true, title: 'workflow', value: 'Quality Assurance' },       { short: false, title: 'repository', value: '***/***' },       {         short: true,         title: 'commit',         value: 'Adding rocket.chat notification'       },       { short: true, title: 'author', value: '***' },       [length]: 6     ]   },   [length]: 1 ] 
```

**Comment by a-konyk** [comment]
Hi,
I'm experiencing the same problem аfter upgrade to 3.2.2.
I don't see attachments from any webhook, and I don't see text of quoted messages, only first line with username plus date and time.
Some users on our server see the same messages with attachments and quotes without issues, but some don't.
I haven't realize yet what is the difference between them.

**Comment by antiseptikk** [comment]
Same here, everything looks good in logs, it's very strange.
Some users see all the message, and some don't.

**Comment by a-konyk** [comment]
It looks like the cause of this problem is in "Collapse Embedded Media by Default" option. After setting it to False attachments are shown normal again.
