### ISSUE TITLE
No option to get a link to the file from the list of files

### ISSUE THREAD

**Issue by grzebo** [RocketChat/Rocket.Chat#17630]
### Description:

List of files in a given channel gives a user only the option to download or delete a file, but not to get a link to it. This causes the users to download and reupload older files that they would like to mention.

### Steps to reproduce:

1. In any channel, click on the "paperclip" icon in top right corner ("Files")
2. You see a list of files from that channel where you can search for files.
3. Hover over any file on that list.
4. A "three dot" menu appears, click it.
5. You have only two options: Download or Delete.

### Expected behavior:

There should be an option to "Get a link" so that users can mention an old file that was uploaded to a channel.

### Actual behavior:

Users can only download a file, what causes them to download and reupload old files, what wastes disk space.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: DigitalOcean Droplet
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox and Chrome
- Operating System: Linux, Windows

**Comment by gabriellsh** [comment]
You can right click the title and copy the link for now. I still think this should be in the context menu, so I'll keep it open.

**Comment by grzebo** [comment]
It doesn't work that way.

**Steps to reproduce:**

1. In any channel, click on the "paperclip" icon in top right corner ("Files")
2.   You see a list of files from that channel where you can search for files.
3. Right click on a file on that list, then click on "copy link" in the browser context menu.
4. Paste link inside a message on that same channel and send a message, the link looks like this: https:/[MY DOMAIN]/file-upload/Mj9o2bRrbnKQBYfsm/a.PNG
5. Click on the link in the posted message.

**Expected result:**

I see a file that was linked, can download it.

**Actual result:**
I get a 404 error page.

I've tested it multiple times, even with simple filenames (as you can see: "a.PNG"), never works.
