### ISSUE TITLE
improvement/idea: Webhook/Integration with dynamic destination channel/person

### ISSUE THREAD

**Issue by port22** [RocketChat/Rocket.Chat#17648]
I want automatisms linke pipelines and scripts to be able to directly notify users without actually needing to create an integration for EVERY user

There should be a generic integration where you can choose the "publish to channel" via payload.

**Comment by y377** [comment]
Allows users to add custom integrations, which increases user friendliness and reduces administrator work

**Comment by port22** [comment]
> reduces administrator work

exactly! But not only this – currently, I can not implement a strategy at all, where I want to notify a user who requested something, which is semi-confidential or just not anyone else's business.

And, hence it should have a separate Token as usually, this shouldn't be an issue, security-wise, I think.

For me, it would be absolutely fine, if only Rocketchat Administrators can create such an Integration!
