### ISSUE TITLE
User data downloads/exports do not run

### ISSUE THREAD

**Issue by deja-geek** [RocketChat/Rocket.Chat#17643]
### Description:
User data downloads/exports do not run or complete.  Error in log files about no such file or directory

### Steps to reproduce:
1. Go to "My Account"
2. Click on download data

### Expected behavior:
Receive link via email to download data

### Actual behavior:
Link never received
 
### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 16.04
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 3.2.21

### Additional context
Is there a patch and or a workaround for getting the downloads to work?  In lieu of a workaround, is there any scripts that can export all chats/messages from the database?  Upgrade to next major release of Rocket.Chat not possible as we are locked to the 3.2.x branch of Mongo.

### Relevant logs:
When attempting to do a user download, log file shows this error:
```
Error: ENOENT: no such file or directory, open '/tmp/userData/FpYSSi2WibFX9qonF/full/channels.json'
```

**Comment by sennewood** [comment]
Still a problem with 3.15.0
