### ISSUE TITLE
emoji-custom.list api call doesn't return full list

### ISSUE THREAD

**Issue by TBortels** [RocketChat/Rocket.Chat#17642]
### Description:

ref: https://docs.rocket.chat/developer-guides/rest-api/emoji-custom/list

Calling emoji-custom.list only returns 5 entries no matter how many custom emoji exist.

### Steps to reproduce:

1. Upload 6 custom emojis
2. call emoji-custom.list API call
3. only 5 emojis are returned. 

### Expected behavior:

I expect to see all 6 custom emoji (or some sort of paging mechanism if it's limiting results on purpose)

### Actual behavior:

Only 5 emoji are returned. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: 4.14.138-114.102.amzn2.x86_64
- Deployment Method: Hosted by rocketchat
- Number of Running Instances: unknown
- DB Replicaset Oplog: unknown
- NodeJS Version: unknown
- MongoDB Version:unknown

### Client Setup Information

- Desktop App or Browser Version: curl 7.64.1 (x86_64-apple-darwin19.0)
- Operating System: macos catalina

**Comment by TBortels** [comment]
Hmm. I uploaded a 7th emoji - and now emoji-custom.list is showing 6, including the one I just uploaded. The emoji picker shows all 7 custom emoji.

**Comment by gabriellsh** [comment]
Can you provide the call to the Api, response and maybe a screenshot from the custom emoji page in admin? thanks!

**Comment by TBortels** [comment]
The call was:
curl -s \
     -H "X-Auth-Token: my-pat-auth-token" \
     -H "X-User-Id: my-pat-user-id" \
     https://my-rc-url.rocket.chat/api/v1/emoji-custom.list

But as of today, I am unable to reproduce the behavior. I will close this and re-file if I can figure out how to reproduce it reliably.
