### ISSUE TITLE
Admin page to see server logs

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#1765]
We could have a admin page to see server logs using streams.

An implementation should be wrapping `console.log` function to send any message to a `stream` which clients could subscribe to.

**Comment by Megatronic79** [comment]
+1

**Comment by noregard** [comment]
:+1:

**Comment by Vidhyadharantechdays** [comment]
+1

**Comment by Bitti09** [comment]
:+1:

**Comment by Vidhyadharantechdays** [comment]
view-logs is available at  ** http://(host-name)/admin/view-logs** , go to **http://(host-name)/admin/General** and set the Debug Level to **all logs**
![image](https://cloud.githubusercontent.com/assets/534679/13824905/0b02959a-ebd6-11e5-8e44-293d395bd480.png)


![image](https://cloud.githubusercontent.com/assets/534679/13824797/a7670e3a-ebd5-11e5-8cac-1845de1a3b04.png)

**Comment by graywolf336** [comment]
Yes, as mentioned the above is now implemented. :+1:

**Comment by Alaa-23** [comment]
Where are these saved on the server?

**Comment by sampaiodiego** [comment]
they're sent to stdout..

**Comment by Alaa-23** [comment]
> they're sent to stdout..

Thanks for your reply! How can I save them, though?

**Comment by sampaiodiego** [comment]
it's up to you.. it depends entirely on how your set up is.. 

if you run just `node`, you could do for example: `node main.js > saved-logs.txt` got it?

**Comment by Alaa-23** [comment]
> 
> 
> it's up to you.. it depends entirely on how your set up is..
> 
> if you run just `node`, you could do for example: `node main.js > saved-logs.txt` got it?

Yes, that worked for me, many thanks! :)
