### ISSUE TITLE
Zoom App not working

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#17660]
### Description:

Zoom App does not work.

### Steps to reproduce:

1. Install Zoom App from Marketplace
2. add api key and secrect
3. `/zoom start`

### Expected behavior:

never seen it working, but I expect a link to a Zoom conference.

### Actual behavior:

```
error: 2020-05-15T17:00:04.084Z (Caller: anonymous OR constructor)
[
  "{\"stack\":\"TypeError: Cannot read property '_id' of undefined
    at Promise.asyncApply (app/apps/server/bridges/messages.js:20:22)
    at /home/rocketchat/RocketChat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Cannot read property '_id' of undefined\"}"
]
debug: 2020-05-15T17:00:04.084Z (Caller: anonymous OR constructor)
[
  "zoom's executor was unsuccessful."
]
```

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu 16.04 LTS
- Deployment Method: tarball
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v8.17.0
- MongoDB Version:3.6.17

### Additional context

may be dup of #14908

### Relevant logs:

```
May 15 19:11:38 testrocket rocket[1221]: server.js:204 System ➔ error Error sending message: Error: error-not-allowed
May 15 19:11:38 testrocket rocket[1221]:     at Promise.asyncApply (app/authorization/server/functions/canSendMessage.js:16:9)
May 15 19:11:38 testrocket rocket[1221]:     at /home/rocket/rocket/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
May 15 19:11:38 testrocket rocket[1221]:  => awaited here:
May 15 19:11:38 testrocket rocket[1221]:     at Function.Promise.await (/home/rocket/rocket/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
May 15 19:11:38 testrocket rocket[1221]:     at canSendMessage (app/authorization/server/functions/canSendMessage.js:38:70)
May 15 19:11:38 testrocket rocket[1221]:     at executeSendMessage (app/lib/server/methods/sendMessage.js:70:16)
May 15 19:11:38 testrocket rocket[1221]:     at Promise.asyncApply (app/apps/server/bridges/messages.js:18:23)
May 15 19:11:38 testrocket rocket[1221]:     at /home/rocket/rocket/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by Sing-Li** [comment]
@d-gubert  Can you please take a look at this.   Seems all the purchasers of the app are facing "does not work problem".     AND our support team seems to oblivious on how to handle it.

**Comment by Sing-Li** [comment]
We should really remove the app from the marketplace if it is confirmed not working.  fwiw

**Comment by localguru** [comment]
Give me the money back, Dude!  Haha!  

![grafik](https://user-images.githubusercontent.com/8544984/82079602-6685aa80-96e3-11ea-9048-b536b100e639.png)

**Comment by thassiov** [comment]
The problem was found and a patch for it is being reviewed. Thanks for reporting!

**Comment by localguru** [comment]
@thaiphv Thanks! Is that patch already available. App doesn't show "Update".

**Comment by thassiov** [comment]
@localguru there's an update available and you can download it

**Comment by localguru** [comment]
Update not working:

![image](https://user-images.githubusercontent.com/8544984/82256435-9ee0ef00-9956-11ea-8d82-e475a736baf1.png)

**Comment by localguru** [comment]
I removed the app and reinstalled it. It's working now thanks.
