### ISSUE TITLE
[Bug] able to send messages in readonly channels using REST API

### ISSUE THREAD

**Issue by AdarshNaidu** [RocketChat/Rocket.Chat#17676]
### Description:

I was able to use Rocket Chat REST API to send messages to a readonly channel. 
Which I think is not supposed to happen.

### Steps to reproduce:

Use postman to send messages to a readonly channel

### Expected behavior:

The message should not be sent

### Actual behavior:

The message is sent

**Comment by localguru** [comment]
Same as #12534 ?

**Comment by pierre-lehnen-rc** [comment]
It's the same as yours, but I think the other one was already fixed by #11311 last year. I'll review it to be sure.
