### ISSUE TITLE
High load on 'rocketchat_sessions' collection on 04:00 every day

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#17672]
### Description:

Hi, we are observing very high load on `rocketchat_sessions` collection every day on 04:00. There are about 1 million remove operations! It causing high load on rocket and mongo. 

### Steps to reproduce:

1. Check Rocket.Chat.Metrics "Oplog" graph on 04:00

### Expected behavior:

No high load on 'rocketchat_sessions' collection.

### Actual behavior:

Very high load on `rocketchat_sessions` collection.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 25
- DB Replicaset Oplog: YES
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.16

### Additional context

![image](https://user-images.githubusercontent.com/50440047/82197804-b3dc6480-98fb-11ea-9de5-8fc8559cbfb6.png)

**Comment by ankar84** [comment]
I have same at 5
![image](https://user-images.githubusercontent.com/4023037/82283157-36b5fb80-999e-11ea-9a98-cd125383ac91.png)

**Comment by sampaiodiego** [comment]
that's the "aggregate-sessions" task that runs once a day.. it runs that late trying to avoid a busy hour.

one workaround for this would be running this task hourly, so this load would be diluted in 24 parts. @rodrigok what is your opinion in this?
