### ISSUE TITLE
Another way to translate

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#1767]
Hello! I very happy to use your app it's very useful and beauty. But russian translate make me disapoint so i very want to help you. Few weeks ago i trying to help with translate and get invite from @marceloschmidt and login in my page, but unfortunately cant edit anything because of strange error after logining. So i try to write message with this issue on support of lingohub, but this does not help - error still appears Despite all attempts.  
So my question is - is there another way to translate?

**Comment by geekgonecrazy** [comment]
@vetash you might be able to open a PR and edit those translations manually... But I don't know if they sync back up to lingohub.  This is why we recommend everyone go that route.

@RocketChat/core any idea if changes made sync back up to lingohub?

Also hit us up on https://demo.rocket.chat and we'll try and get this specific issue figured out for you.

**Comment by engelgabriel** [comment]
It is supposed to sync back.. but I would not  trust it 100%

**Comment by geekgonecrazy** [comment]
That's what I thought.  I connected with him in #support we might need to investigate his issue with lingohub further.
