### ISSUE TITLE
MongoDB crash when using long database names

### ISSUE THREAD

**Issue by mkalam-alami** [RocketChat/Rocket.Chat#17673]
### Description:

When database names are above ~32 char long, the server fails to initialize. This is caused by an easily fixable issue related to default MongoDB index names.

### Steps to reproduce:

Install RocketChat on a database named with 40 characters or more.

### Expected behavior:

Server launch should succeed.

### Actual behavior:

Server launch fails (see log below).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12
- MongoDB Version: 3.6.0

### Client Setup Information

N/A

### Additional context

In the RocketChat sources, the MongoDB indexes are all created with their default names. When combining several columns this can lead to very long driver names, which make it easier to trigger a character limit on MongoDB.

There is one particular index in LivechatInquiry.js created with a 66 character long name. Naming it relaxes the limitation quite a lot:

```javascript
this.tryEnsureIndex({ queueOrder: 1, estimatedWaitingTimeQueue: 1, estimatedServiceTimeAt: 1 }); // fix: needs explicit { name: "xxx_index_name_xxx" } as second argument
```

### Relevant logs:

```
Error creating index: livechat_inquiry -> {
  queueOrder: 1,
  estimatedWaitingTimeQueue: 1,
  estimatedServiceTimeAt: 1
} MongoError: namespace name generated from index name "cxxxx-rocketchat-review-3-2-2-upgrade-ini.rocketchat_livechat_inquiry.$queueOrder_1_estimatedWaitingTimeQueue_1_estimatedServiceTimeAt_1" is too long (127 byte max)
```

**Comment by alex-adestech** [comment]
This also happens to me, any news about it?
