### ISSUE TITLE
Bugs are not handled at all

### ISSUE THREAD

**Issue by ostapski** [RocketChat/Rocket.Chat#17670]
### Description:

Any bugs reported - are handled like a party cake - only those that "I like" get attention
This whole project is a flop ... bad programmed and support is either none or at the level - "Let me see ..."

### Steps to reproduce:

1. Read this  
2. try to find a better solution for your need

Screw you guys - i'll either find a better one or i'll make one my self ...with black jack and hookers...

**Comment by serviceman** [comment]
I assume you are talking about your "bug report" here. https://github.com/RocketChat/Rocket.Chat/issues/17604

First off, this isn't a bug, it's a server setting. 

Second, if I could figure out the issue with a simple google search, you probably could have too. Especially when I'm not a a Webdav user. Any service that breaks upon an upload size of any set amount is generally an issue with the server settings blocking uploads beyond that size.

3rd, this is not a support forum, it's a bug/issue reporting system. If you want help with an install issue I'd suggest using the Forum at https://forums.rocket.chat/ or the support thread in https://open.rocket.chat/channel/support

4th, this is OPEN SOURCE, issues getting fixed will always be a the whim of it being important to at least one contributor, you could always fix the issue, if there is indeed one, and contribute it yourself.

I am not a developer of Rocket Chat, I am simply a user of the program, so if I over stopped in my response, I'm sorry. Hopefully someone with the power to do so will come a long and either delete or lock this thread.

My last note. Thank you for such a great program.

**Comment by ostapski** [comment]
nop :)
this isnt a server setting lets start from that ... have you actually checked it ? NO !!!

SECOND - now at least i got your attention - ...6 days after ... as i said - you are not handling bugs you are picking them up as ...like my colleague say - cherry picking ... i say - you are systematically ignoring bug reports !! 

Not only you are not responding to the reports - you are deleting them without notice !!!
and that is way unprofessional ...however you name your self ...or hide behind "Open source" 
if you signed up to distribute your soft - be prepare for what i'm writing right now - do not hide behind "we have no time ..." do not justify your self by any means - you are distributing your software for many people to use - be prepare for critics be prepare for bug reports. 
And you are absolutely NOT ... 
one of my bug reports got simply deleted by one of your members without notice 
this is just like in kindergarden - really !!

**Comment by luixxiul** [comment]
Pay the money to get the support. There is no free lunch out there.

**Comment by ostapski** [comment]
ah ... so here is the final :)
you might remove the "free" from the site after all then

**Comment by ostapski** [comment]
and i only reported already existing functionality bug - that had to work ...
are you not capable to fix it ? are you just lego builders who collect work of others and combine it under own name ?

**Comment by ostapski** [comment]
25- 35 year old ? i presume ?

**Comment by ostapski** [comment]
nothing made by your self - ? only what others did ?

**Comment by luixxiul** [comment]
You are so incapable of fixing the stuff that you could only shout like a crying kid. Please cry in your own room mate- don't involve adults here.

**Comment by ostapski** [comment]
this is your response ?
adult ?

**Comment by ostapski** [comment]
be professional - accept that there is a bug 
fix it  and then proudly report that you did it !

**Comment by ostapski** [comment]
you have't even look at it - you posted me some link - like "get lost ...search for your self"
while bug is not on the webdav - it is inside your code

**Comment by ostapski** [comment]
and ... before asking for money - get a programmer !!! ..not just a secretary girl ( although having one is always cool ...)

**Comment by Zlapsa** [comment]
I agree!
Not only the bugs are not handled, but improvements too! We use Livechat and we are waiting for annoying bugfixes, but even Improvements is blocked too, for example Livechat #399 and many others!

**Comment by Sing-Li** [comment]
With utmost respect and appreciation -  I like to thank our mature community, and especially @serviceman (sincerely sorry about the subdirectory deprecation !  😶  )   for supporting us through these groundless flame-bait  attacks.  😍
