### ISSUE TITLE
Duplicated "Placeholder for password login Field" 

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat#17679]
### Steps to reproduce:
Go to Administration, Accounts
You will see "Placeholder for password login field" twice.
![image](https://user-images.githubusercontent.com/5522389/82231309-5b10ca00-9903-11ea-8b24-f51bcd5cc68d.png)

- Version of Rocket.Chat Server:  3.2.2
- Operating System: 
- Deployment Method: docker
- Number of Running Instances:  1

**Comment by AbhinavTalari** [comment]
Can i Take up this issue ?

**Comment by y377** [comment]
The second is "confirm password" on the registration page
