### ISSUE TITLE
Force SSL by default

### ISSUE THREAD

**Issue by ywecur** [RocketChat/Rocket.Chat#1768]
Currently there is no way to force clients to connect via SSL, making communication insecure by default.

I'm not sure how this would be implemented, though I know of [this meteor package that forces SSL](https://atmospherejs.com/meteor/force-ssl), which might help.

And as @geekgonecrazy has pointed out to me: A toggle might be useful during the initial setup.

**Comment by geekgonecrazy** [comment]
Also as discussed maybe if the site url has https:// in it then we could force ssl by default.

**Comment by ywecur** [comment]
@geekgonecrazy Maybe add the `contrib: easy` lable?

**Comment by geekgonecrazy** [comment]
Going to tack on intermediate.  Because I assume easy, but it might throw a curve ball :)

**Comment by engelgabriel** [comment]
Meteor won't handle the SSL directly, the NGINX or other reverse proxy will do that. I think it makes more sense to configure the redirect there (like we do on the demo server) rather than on the app level. It's far more effective/secure and much faster.

**Comment by Megatronic79** [comment]
@engelgabriel  agree with you there, the reverse proxy should handle the SSL connection termination and can force all http to https easily. (as well as secure numerous other web security issues.)

**Comment by ywecur** [comment]
@Megatronic79 Will this also apply to the mobile apps?

**Comment by engelgabriel** [comment]
It will apply to ALL connections.

**Comment by Megatronic79** [comment]
The mobile apps connect to the same endpoint as the web services, if the reverse proxy is set to force all http to https then all traffic will be encrypted.

**Comment by ywecur** [comment]
Nevertheless, this is something that should be apparent in the tutorial. I found no mention of this before I deployed my instance to Heroku.

**Comment by vargasbo** [comment]
Agree. Maybe you can document this and issue the PR.

**Comment by ywecur** [comment]
@vargasbo How would one document this? I'd mostly prefer a tutorial or script that does this automatically.

**Comment by vargasbo** [comment]
You can add create a new wiki page (how to force SSL) add your 2 cents, and then link to the existing [wiki page] (https://github.com/RocketChat/Rocket.Chat/wiki/Run-Rocket.Chat-behind-a-SSL-Reverse-Proxy).

**Comment by Megatronic79** [comment]
SSL and reverse proxy is already part of the wiki here:

https://github.com/RocketChat/Rocket.Chat/wiki/Run-Rocket.Chat-behind-a-SSL-Reverse-Proxy

I guess a step on the Heroku page needs to point to this with a security note.

**Comment by engelgabriel** [comment]
I am not sure how you'd configure it at Heroku. They relay on the app to do that. So we may have to implement something on our side to support it at all.

**Comment by Sing-Li** [comment]
On Heroku ...

https://devcenter.heroku.com/articles/ssl-endpoint

... might have websocket or sticky sesssion problems ?

**Comment by engelgabriel** [comment]
@Sing-Li I've seen the article, but didn't find anything about *forcing* the SSL... form what I understand, they expect the app to do the redirect.

**Comment by mquandalle** [comment]
I also think that it is not the role of a Meteor application to handle http to https redirection. The `force-ssl` package from MDG was almost a hack to configure this redirection on Galaxy since at the time they didn’t have any Galaxy admin UI but this is kind of a weird package honestly.

Anyway even if the `force-ssl` package you still *need* to configure an server proxy like Nginx to handle the SSL certificate, and so it makes perfect sense to configure the redirection at Nginx level as well. Sure not everyone is configuring Nginx on top of Rocket.chat but these users will not be able to use https anyway.

**Comment by Sing-Li** [comment]
Perhaps add Nginx to front-end Rocket.Chat on Heroku?    https://github.com/ryandotsmith/nginx-buildpack

**Comment by mquandalle** [comment]
And maybe the docker-compose could also have a Nginx proxy? Although IIRC docker-compose doesn't advertise itself as ready for production use, so I’m not sure if there is a clean way to install and update a full stack of containers (database, application, Nginx proxy) on production with it.

**Comment by MuhClaren** [comment]
@mquandalle A deployment guide exists for rocketchat using docker-compose and nginx (SSL): https://github.com/RocketChat/Rocket.Chat/wiki/Docker---Ubuntu-with-Nginx-SSL-and-Hubot

In general, the official method for having nginx force http connections to https is to use the `return` directive in the http server block:
```
server {
    listen       80;
    server_name  example.org;
    return       301 https://www.example.org$request_uri;
}
```
source: http://nginx.org/en/docs/http/converting_rewrite_rules.html

Another option, if one doesn't mind using cloudflare, is to configure a cloudflare "page rule" to force HTTPS. The feature is available on the free account type, and works for your DNS entries even when they're not "orange clouded" or in other words, when they're not passing through the cloudflare proxy (just using cloudflare as a DNS). For example, my chat running at https://chat.inum.io uses cloudflare to force HTTPS via a page rule which looks like this in the cloudflare panel: `http://*inum.io/` (always use HTTPS).

**Comment by engelgabriel** [comment]
Just because Rocket.Chat is the most popular button at Heroku (see https://elements.heroku.com/), should we try to implement something like https://github.com/kfatehi/meteor-my-force-ssl but make it **ONLY** triggered/installed if the administrator turns it on the the admin panel?

What do you think @RocketChat/core ?

![image](https://cloud.githubusercontent.com/assets/1000217/12248507/16b98a5a-b8a1-11e5-9b91-aff6f1e2891e.png)

**Comment by mquandalle** [comment]
(Ah, Wekan is on the list! I wasn’t aware of that at all!)

**Comment by engelgabriel** [comment]
From the top 5, 3 are Meteor apps :)

**Comment by ywecur** [comment]
@engelgabriel I agree with this. Heroku users will have no idea about this issue otherwise and will deploy without knowledge.
