### ISSUE TITLE
Mobile icon for users logged in mobile app

### ISSUE THREAD

**Issue by jcardila** [RocketChat/Rocket.Chat#1769]
It would be nice to have the mobile icon📱displayed after the username in the Direct Messages list, that way someone could know that even when a user is offline it will be notified of their message.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
