### ISSUE TITLE
Creating anonymous user through API

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#17698]
There doesn't seem to be a way to create an anonymous user through the API. Iframe integrations for example are impossible to do through the API for a site which allows guest users if this can't be done.

The users.create endpoint requires both email and password which is not needed for an anonymous account.

**Comment by cchbr** [comment]
This is still an issue in the latest version, 3.4.2.

**Comment by KavinduAkash** [comment]
Is there any way to create an anonymous user?
