### ISSUE TITLE
⚠️ Update_user is not allowed when trying to set user as verified

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat#17696]
### Description:

When trying to mark/set a user with a valid/dummy email, we are presented with a `Update_user is not allowed`
### Steps to reproduce:

1. Go to Admnistration > Users > Select a user > Edit
2. Toggle the `Verified` button right below the user email
3. Click save
4. You'll be presented with a `Update_user is not allowed`

### Expected behavior:

When marking/setting a user as `Verified`, since I'm an admin, I'd expect the user to be marked/set as verified
### Actual behavior:

Small video of the error:

![RC_Error](https://user-images.githubusercontent.com/25697531/82390518-36ba0800-9a3f-11ea-88e7-5764fd8ccc18.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Ubuntu 19.10
- Deployment Method: manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: enaled
- NodeJS Version: 12.16.1
- MongoDB Version: v4.0.18

### Client Setup Information

- Desktop App or Browser Version: Firefox 76.0.1 (64-bit)
- Operating System: Ubuntu 20.04

### Relevant logs:

No errors on the log when I go to `Administration > View Logs`

**Comment by gabriellsh** [comment]
A few checks for you to make:

- [ ] User has a role with permission: `edit-other-user-info`

- [ ] Setting `Accounts_AllowUserProfileChange` is enabled

- [ ] Setting `Accounts_AllowEmailChange` is enabled

**Comment by PeGaSuS-Coder** [comment]
* [x]  User has a role with permission: `edit-other-user-info` - **this is true**
* [ ]  Setting `Accounts_AllowUserProfileChange` is enabled - **not enabled by default**
* [ ]  Setting `Accounts_AllowEmailChange` is enabled - **not enabled by default**

I've recently reinstalled everything, and it seems to work.

I had the issue when I was using one mongodb instance, with 2 Rocket.chat instances, each one with its own URL, mongodb database and port.

Since I've switched to a single instance, all seems to work

**Comment by gabriellsh** [comment]
Okay, since it doesn't happen anymore, I'll close this. If you face this again, please comment below.
