### ISSUE TITLE
Add temporary image and map embed to support bot writers

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#177]
We can't quite wait until 1.0.  Because bot writers need to do this now:

![embed](https://cloud.githubusercontent.com/assets/122633/8074725/d66c25f8-0f03-11e5-8e30-37fccd4936e9.png)

Propose to add temporary (hacky, throwaway) implementation of image and map embed to support bot writers.  PR follows.

In the PR, a modular implementation using the brand-new renderMessage callback hooks is also included in the packages directory.  BUT that doesn't work because there is currently no way to say 'run mines first, and  don't run any other in the chain after -- if I say so'.

**Comment by amazg** [comment]
cool，good job

**Comment by Sing-Li** [comment]
Closing.  PR was manually merged due to the 'slippery finger effect'  :)
