### ISSUE TITLE
ldap + outh leading to "email has already been used and has not been verified."

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat#17704]
### Description:

I have ldap set and working just fine. All users from ldap are also imported into rocket chat. After that I have configure OATH in rocketchat to point to my KeyCloak server to provide some additional authentication rules. When I login I can see the button to login using keycloak, after clicking it I get the username/password prompt from keycloak web and I can login, but i get the following message:

![image](https://user-images.githubusercontent.com/5522389/82487670-188eef00-9ab5-11ea-848f-13b6213b10f5.png)

I understand that the email from the keycloak matches the email from the user imported from ldap ( they are the same user anyways ), but I do not understand why it says it is not verified . It is an LDAP account, so that email is verified.

### Steps to reproduce:

1. Configure ldap and import users
2. Add Oauth provider that contains the same user as the ldap
3. Try to login ( The first one will suceed, all the others will require change the password )

### Expected behavior:

Should login just fine.

### Actual behavior:
Request to reset password which can not be done for LDAP accounts ( read only )

### Server Setup Information:

- Version of Rocket.Chat Server:  3.2.2
- Operating System:  Linux
- Deployment Method: Docker container

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Linux Mint on Google Chrome

**Comment by ankar84** [comment]
I confirm that.We have very same configuration and had same issue.
I think we fix that by removing email field from KeyCloack.
