### ISSUE TITLE
Hide email/username login [ for SSO-only systems ]

### ISSUE THREAD

**Issue by Shelnutt2** [RocketChat/Rocket.Chat#1771]
There should be a way to disable/hide the normal account login when SSO is enabled. I often have users trying to login with a username and password instead of clicking on the gitlab logo. I recommend a way to hide or disable non-sso login's.

Disabling might be troublesome if the SSO provider goes away, then there would be no way for an admin to log back in. At least a method to hide it, or make the SSO providers more prominent.

**Comment by Luceos** [comment]
+1

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Comment by osarrat** [comment]
On our side, we would also love to have this feature.

Is it better to reopen this issue, or to create a new one ?
