### ISSUE TITLE
Japanese characters facing wrong way in custom roles 

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat#17713]
### Description:

Creating a new custom role in Japanese makes its name look upside down and inside out. Japanese is written vertically from up to down. Currently the custom role on the Permissions screen turns the characters into opposite direction and places them from down to up. 

### Steps to reproduce:

1. Switch to the Japanese, create a custom role 顧客サービス
2. Save, go to Permissions
3. The role is hard to read. 

### Expected behavior:

The name should be rotated 180° altogether (eg.1) or all the characters should be rotated 90° and placed horizontally (eg.2). 

### Actual behavior:

Now it looks like eg.3
![image](https://user-images.githubusercontent.com/47217833/82552517-ec35aa00-9b6a-11ea-8159-6286953abd57.png)
<img width="420" alt="Screenshot 2020-05-21 at 13 38 07" src="https://user-images.githubusercontent.com/47217833/82552532-f3f54e80-9b6a-11ea-811a-c883ab716caf.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
### Client Setup Information

- Desktop App or Browser Version: latest Chrome and desktop app 2.17.9
- Operating System: Windows 10 and MacOS

**Comment by luixxiul** [comment]
A solution with CSS would be:

````
html[lang="ja"] .permissions-manager .permission-grid .rotator {
    transform: none;
    text-align: end;
    writing-mode: vertical-lr;
}
````

![Clipboard02](https://user-images.githubusercontent.com/3362943/82579900-f9a85f80-9b7d-11ea-8b08-345817bcd6dc.png)

The issue should be common among Chinese and Korean (also Mongolian if any) interface. See: https://www.w3.org/International/articles/vertical-text/
