### ISSUE TITLE
Read messages return as unread

### ISSUE THREAD

**Issue by port22** [RocketChat/Rocket.Chat#17729]
```
rocketchat_app.1.zp28e03f273i@swarm3    | ➔ |                    SERVER RUNNING                   |
rocketchat_app.1.zp28e03f273i@swarm3    | ➔ +-----------------------------------------------------+
rocketchat_app.1.zp28e03f273i@swarm3    | ➔ |                                                     |
rocketchat_app.1.zp28e03f273i@swarm3    | ➔ |  Rocket.Chat Version: 3.2.2                         |
rocketchat_app.1.zp28e03f273i@swarm3    | ➔ |       NodeJS Version: 12.16.1 - x64                 |
rocketchat_app.1.zp28e03f273i@swarm3    | ➔ |      MongoDB Version: 3.6.18                        |
```

It is repeatingly reported and affects me on a regular basis, too, that already read messages return unread when going offline/shutting down computer without quitting Rocketchat and going online later again.
To be more clear, an unread message is visualized by a circle'd `1` along the ***name*** in the channel list.
This happens when using Webapp as well as Rocketchat Desktop. Nevertheless I could imagine this could be a client-side issue caused by the unexpected shutdown

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
