### ISSUE TITLE
Custom emote overwritten

### ISSUE THREAD

**Issue by gr0ebi** [RocketChat/Rocket.Chat#17724]
### Description:

Custom emote will be overwritten, if old one is marked while creating a new custom emote

### Steps to reproduce:

1. Go to admin panel -> "Custom Emoji"
2. Click onto existing emote
3. Click the top-right "+" symbol to "Add new Emoji"
4. Fill in new name, choose new Emoji-file and "Save"
5. Old Emoji is gone, new Emoji is here

### Expected behavior:

Old Emoji is still here

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Linux 4.19.0-8-amd64 Debian 10 x86_64 GNU/Linux
- Deployment Method: Manual installation (https://docs.rocket.chat/installation/manual-installation/debian/)
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled (?)
- NodeJS Version: v12.16.1
- MongoDB Version: 4.2.6

### Client Setup Information

- Desktop App or Browser Version: Browser Chromium 81.0.4044.138
- Operating System: Win10

Couldn't find this issue on github elsewhere

**Comment by ggazzo** [comment]
duplicated https://github.com/RocketChat/Rocket.Chat/issues/17592
