### ISSUE TITLE
Docker auto-updating installation on CentOS 7

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#17720]
Hi,
for my company we are going to setup a RocketChat installation on a Centos 7 machine. The goal of this installation is to achieve seamless automatic updates of the RocketChat server bundle.
Which would be the most correct approach to do this?

Thanks in advance

**Comment by gabriellsh** [comment]
If you need help, please go to [our open Support Channel](https://open.rocket.chat/channel/support) or our forums [here](https://forums.rocket.chat/). Issues are reserved for bugs and feature requests/improvements. Thanks for your comprehension!
