### ISSUE TITLE
[Improvement] LDAP Sync Nested groups

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17723]
### Description:
First.
@pierre-lehnen-rc please implement support on nested LDAP groups for **Sync LDAP Groups** LDAP feature. 
I mean if LDAP group have another LDAP group in memberOf, it would be very nice, that nested group members were synced.
Like PowerShell commandlet `Get-ADGroupMember -Recursive`

And second. 
Sometime we have such message in logs while LDAP Sync:
`server.js:204 LDAPSync ➔ error Error creating user errorClass [Error]: Email already exists. [403]`
Please add actual problem email to resolve that problem. We don't see that information near error event.

**Comment by ankar84** [comment]
About email already exists. We have a lot of these lines, but really don't know problematic email
<details>

````
	May 26th 2020, 03:01:14.198	s-rc-srv-05	rocketchat_rocketchat_5_1	}
	May 26th 2020, 03:01:14.198	s-rc-srv-05	rocketchat_rocketchat_5_1	errorType: 'Meteor.Error'
	May 26th 2020, 03:01:14.198	s-rc-srv-05	rocketchat_rocketchat_5_1	message: 'Email already exists. [403]',
	May 26th 2020, 03:01:14.197	s-rc-srv-05	rocketchat_rocketchat_5_1	reason: 'Email already exists.',
	May 26th 2020, 03:01:14.197	s-rc-srv-05	rocketchat_rocketchat_5_1	error: 403,
	May 26th 2020, 03:01:14.197	s-rc-srv-05	rocketchat_rocketchat_5_1	isClientSafe: true,
	May 26th 2020, 03:01:14.197	s-rc-srv-05	rocketchat_rocketchat_5_1	details: undefined,
	May 26th 2020, 03:01:14.197	s-rc-srv-05	rocketchat_rocketchat_5_1	at runWithEnvironment (packages/meteor.js:1286:24) {
	May 26th 2020, 03:01:14.196	s-rc-srv-05	rocketchat_rocketchat_5_1	at Array.forEach (<anonymous>)
	May 26th 2020, 03:01:14.196	s-rc-srv-05	rocketchat_rocketchat_5_1	at app/ldap/server/sync.js:488:13
	May 26th 2020, 03:01:14.193	s-rc-srv-05	rocketchat_rocketchat_5_1	at app/ldap/server/sync.js:521:5
	May 26th 2020, 03:01:14.191	s-rc-srv-05	rocketchat_rocketchat_5_1	at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1147:10)
	May 26th 2020, 03:01:14.191	s-rc-srv-05	rocketchat_rocketchat_5_1	at addLdapUser (app/ldap/server/sync.js:455:29)
	May 26th 2020, 03:01:14.190	s-rc-srv-05	rocketchat_rocketchat_5_1	at handleError (packages/accounts-password/password_server.js:107:17)
	May 26th 2020, 03:01:14.190	s-rc-srv-05	rocketchat_rocketchat_5_1	server.js:204 LDAPSync ➔ error Error creating user errorClass [Error]: Email already exists. [403]
	May 26th 2020, 03:01:14.190	s-rc-srv-05	rocketchat_rocketchat_5_1	at createUser (packages/accounts-password/password_server.js:1076:3)
	May 26th 2020, 03:01:14.190	s-rc-srv-05	rocketchat_rocketchat_5_1	at checkForCaseInsensitiveDuplicates (packages/accounts-password/password_server.js:241:7)


````


</details>

**Comment by ankar84** [comment]
Here is a example of LDAP Sync with Trace log level
<details>

````
I20200527-15:12:58.059(0) LDAP ➔ Search.info Searching by id 01050000000000051500000035802cd4d3546e3adb9f2df298460100 
I20200527-15:12:58.060(0) LDAP ➔ Search.debug search filter (objectSid=\00\00\00\00\00\00\00\005�,��Tn:۟-�F\00) 
I20200527-15:12:58.061(0) LDAP ➔ Search.debug BaseDN OU=Users,DC=company,DC=local 
I20200527-15:12:58.063(0) LDAP ➔ Search.info Searching by id 01050000000000051500000035802cd4d3546e3adb9f2df2e87b0100 
I20200527-15:12:58.064(0) LDAP ➔ Search.debug search filter (objectSid=\00\00\00\00\00\00\00\005�,��Tn:۟-��{\00) 
I20200527-15:12:58.065(0) LDAP ➔ Search.debug BaseDN OU=Users,DC=company,DC=local 
I20200527-15:12:58.124(0) LDAP ➔ Search.info Search result count 1 
I20200527-15:12:58.125(0) LDAPSync ➔ info Syncing user data 
I20200527-15:12:58.125(0) LDAPSync ➔ debug user { email: undefined, _id: 'hDTATamx6zJQ5fABr' } 
I20200527-15:12:58.126(0) LDAPSync ➔ debug ldapUser undefined 
I20200527-15:12:58.127(0) LDAPSync ➔ info Syncing user avatar 
I20200527-15:12:58.133(0) LDAP ➔ Search.info Search result count 1 
I20200527-15:12:58.134(0) LDAPSync ➔ info Syncing user data 
I20200527-15:12:58.135(0) LDAPSync ➔ debug user { email: undefined, _id: 'ZkvuCzKL6DNKThtxN' } 
I20200527-15:12:58.135(0) LDAPSync ➔ debug ldapUser undefined 
I20200527-15:12:58.136(0) LDAPSync ➔ info Syncing user avatar 
I20200527-15:12:58.150(0) Meteor ➔ method stream -> userId: null, arguments: ["notify-logged","updateAvatar",{"0":{"username":"someusername"}}]

````
</details>
And I have another 3 questions. @pierre-lehnen-rc can you please answer
1. How LDAP filter forks with abracadabra `(objectSid=\00\00\00\00\00\00\00\005�,��Tn:۟-��{\00)` and how **objectSid** was converted to that string `01050000000000051500000035802cd4d3546e3adb9f2df2e87b0100` using **HEX** ?
2. For some reason **email** and **ldapUser** are **undefined** in that lines 
''''
LDAPSync ➔ debug user { email: undefined, _id: 'ZkvuCzKL6DNKThtxN' } 
LDAPSync ➔ debug ldapUser undefined
````
How it could be and what does it means? All of our user have **email** field is filled.
3. Does user somehow relogin to Rocket Chat while sync?
I'm asking about that line in logs
`Meteor ➔ method stream -> userId: null, arguments: ["notify-logged","updateAvatar",{"0":{"username":"someusername"}}]`

**Comment by jschewebbn** [comment]
For the email already exists error, dump your LDAP directory to a CSV file and check for 2 users with the same email address. I expect you'll find that's true and that is what is causing this error.

For handling of nested groups see my post at the end of https://forums.rocket.chat/t/ldap-group-channel-mapping/5067/3

**Comment by ankar84** [comment]
> For handling of nested groups see my post at the end of https://forums.rocket.chat/t/ldap-group-channel-mapping/5067/3

I tested your filter and can tell, that **nested AD groups solved** thanks to @jschewebbn 
`(&(sAMAccountName=#{username})(|(memberof:1.2.840.113556.1.4.1941:=CN=#{groupName},OU=rocketchat,DC=company,DC=com)(memberof:1.2.840.113556.1.4.1941:=CN=#{groupName},OU=rocketchat,DC=company,DC=com))(objectCategory=person)(objectClass=user))`
Works really good! 
I think that filter could be **recommended as default**, because it works with users in group and with groups in group.

And about `Email already exists. [403]` error, I figure out that was cause of the issue. It's old accounts of users, that were fired and returned again with same AD login and email. I renamed old account in RC (username and email).
But still, @pierre-lehnen-rc it would be much easier to determinate what users caused  `Email already exists. [403]` error if his or her username or email will be in log entry.
