### ISSUE TITLE
[BUG] an invalid invitation link/token leads to new user registration form despite disabled user registration

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#17733]
### Description:

Via an invitation link with an invalid token it is possible to display the registration form for new users although the user registration is deactivated.

### Steps to reproduce:

0. disable user registration in your rocket chat instance.
1. open an URL like `https://go.rocket.chat/invite?host=your.rocketchat.tld&path=invite%2FR6wAbJ` in your browser. Replace `your.rocketchat.tld` by your rocket URL.
2. On next site at question "Where do you want to open this link?" click on "Web application".
3. On next site "Invalid or expired invitation token" click on the rocket chat image/logo.
5. Full user registration form is displayed, even though user registration is disabled.

### Expected behavior:

user registration form must not be displayed, if user registration form is disabled.

### Actual behavior:

user registration form is displayed even though user registration is disabled. Fortunately, user registration is not performed.

### Server Setup Information:

- Version of Rocket.Chat Server: tested with 2.4.11 and 3.1.1 
- Operating System: Ubuntu
- Deployment Method: snap and tarball

### Client Information:

- Firefox 76.0.1 (64-Bit) and Chrome  83.0.4103.61 (64-Bit)

### Additional context

Apart from the error, invitation links do not work at all. You always get a "Invalid or expired invitation token". 

Furthermore, the invitation link should not be `go.rocket.chat` by default. This is a problem for privacy reasons, but also for security reasons.

**Comment by photoninger** [comment]
I can reproduce this with 3.1.1 but not with 3.2.2.
With 3.2.x we got some fixes for invite links and disabled registration form: https://github.com/RocketChat/Rocket.Chat/pull/17226

**Comment by pierreozoux** [comment]
@photoninger on the latest 3.11.1 there is a regression of this exact same bug, can you reopen?
