### ISSUE TITLE
bug: Got a "Cannot read property 'data' of undefined" error when deploying app from zip file

### ISSUE THREAD

**Issue by lolimay** [RocketChat/Rocket.Chat#17737]
On version 3.2.0:
When I try zip file i don't get any response, but when i use url i see "Cannot read property 'data' of undefined".

I understand that they want me to pay for the subscription but this isn't funny any more. Is there any other way to install free apps on "free rocketchat" ?

_Originally posted by @danielraq in https://github.com/RocketChat/Rocket.Chat/issues/14466#issuecomment-627856475_

**Comment by CyrilVanErsche** [comment]
Any chance to re-open this issue?

How are we supposed to install free apps without having a rocket.chat cloud account ?
