### ISSUE TITLE
Unable to download Rocket.Chat

### ISSUE THREAD

**Issue by jdurand67** [RocketChat/Rocket.Chat#17736]
### Description:

Rocketchat download address returns error code 503 - Service Unavailable

### Steps to reproduce:

1. Go to https://releases.rocket.chat/latest/download

### Expected behavior:

Download begins

**Comment by LogiEx7** [comment]
I have the same problem since this morning...
Problem on their server in my opinion we must wait

**Comment by lucassmacedo** [comment]
Same Problem

**Comment by smb** [comment]
see #17264 - broken for >24h now...

**Comment by sauberfred** [comment]
The URL is working again.
