### ISSUE TITLE
Chat goes down whenever a ReplicaSet re-elects a new primary 

### ISSUE THREAD

**Issue by obonyojimmy** [RocketChat/Rocket.Chat#17743]
I have noted this bug twice now, the chat server always goes down whenever the mongoDb replica-sets upgrades and elects a primary .

**Comment by geekgonecrazy** [comment]
in your connection string do you have ?replicaSet=replicasetName?

example: `mongodb://mongo1,mongo2,mongo3:27017/rocketchat?replicaSet=rs01`

This will allow the mongo driver to talk to any node and ask it questions about the replicaset.  Things like: "who is primary".  Which will allow it to recovery in a case where the primary changes. 

Also you omitted all of the rest of the issue template.  If you would have filled out the rest I could probably help you more.

**Comment by vinogradovia** [comment]
see https://github.com/RocketChat/Rocket.Chat/issues/13178

**Comment by ndroo** [comment]
To elaborate on @vinogradovia's comment, people using replicaSet (including me) still experience this issue: https://github.com/RocketChat/Rocket.Chat/issues/13178
