### ISSUE TITLE
How to decrease user sessions amount

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17744]
# Description:

[Forum thread](https://forums.rocket.chat/t/decrease-user-sessions-amount/6999)
We use **KeyCloack** as OAuth for authentication in Rocker Chat with **SSO using Kerberos** on domain joined computers. So, users **don’t even need to enter their user name and password** at office.
And I did everyday logoff from office computer (for sometime, week or two), and I think that lead to increase of my user sessions.
Can I **clean that user sessions** somehow?
In MongoDB for my user I see
````
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"iodE4TwMg4i729GoH"}).count()
1398
````
I think it’s **too much**.
How to clean it?
Did try to **Logoff from all other device**s - no luck.
Right after that command
````
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"iodE4TwMg4i729GoH"}).count()
1400
````
Next day early morning
````
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"iodE4TwMg4i729GoH"}).count()
1420
````
After **aggregate_session** task was done
````
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"iodE4TwMg4i729GoH"}).count()
1386
````
Here is examples of other users sessions:
````
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"pfb6DduXne7szJnN9"}).count()
331
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"eHdJn2agKebvNnnYb"}).count()
413
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"v2te7tXk4DSg6MkPZ"}).count()
173
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"ddRErmoDRMohuQ2d2"}).count()
463
rs0:PRIMARY> db.rocketchat_sessions.find({"userId":"B4SsyfkyfJ289BLNx"}).count()
577
````
How to force **aggregate_session** to clean most of sessions and leave only most recent?

### Steps to reproduce:

Just login to RC with KeyCloack and sometime logoff from office computer (with SSO by Kerberos)

### Expected behavior:

Decent amount of user sessions. For example, user login RC from office computer, home computer and smartphone. In that case I expect to see 3 sessions for that user. But not 300 or 500 (or 1400 in my case).

### Actual behavior:

A lot of sessions created for each user.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17
- Proxy: Nginx

### Client Setup Information

- Desktop App or Browser Version: 2.17.7, Chrome 83
- Operating System: Windows 10, Android 10
- Mobile client: 4.6, 4.7

**Comment by rodrigok** [comment]
Hi @ankar84 the data there is aggregated and removed after 45 days, so you should stabilize in a certain amount of data if you don't increase the number of users.

We use that data to provide data for the engagement dashboard (enterprise-only) and some reports we are planning for the community in the future as well.

Since each access represents a session, if users use mobile they may accumulate a good amount of records there. Let's say that a user opens the rocket.chat 10x a day, for 45 days it represents 450 sessions per user, we aggregate them daily and monthly, keeping it there for more 15 days to and them they are deleted by the database index.

Does it helps?

**Comment by ankar84** [comment]
Hi, @rodrigok and first of all, Rodrigo, thanks for your attention and time.


> Does it helps?

Yes, now I understand that **sessions** collection is for informational and reporting purposes, and it very useful for me (here I can find installed or not latest mobile version particular user).
But where I can find technical information about current users sessions like I described here

> user login RC from office computer, home computer and smartphone. In that case I expect to see 3 sessions for that user

**Comment by rodrigok** [comment]
@ankar84 I'm not sure I understood your question, which exactly technical info you want? There you will find info about every connection (not login).

**Comment by ankar84** [comment]
> @ankar84 I'm not sure I understood your question, which exactly technical info you want? There you will find info about every connection (not login).

I want to see all current user sessions (not connections) in MongoDB or Admin UI.
User session I mean client where user successfully authenticated. For example. I login to Rocket Chat from office computer (first session), home computer (second session) and smartphone (third session). So, I assume to see 3 sessions for me. 
Is there somewhere that information.
