### ISSUE TITLE
RTL in the Android app

### ISSUE THREAD

**Issue by yarons** [RocketChat/Rocket.Chat#1774]
Besides the fact the app is not fully translated there are many visual glitches.

![screenshot_2015-12-29-11-44-06](https://cloud.githubusercontent.com/assets/406826/12032901/09bca5e2-ae26-11e5-8a82-c3eba647e343.png)
Preferences screen misaligned

![screenshot_2015-12-29-11-44-31](https://cloud.githubusercontent.com/assets/406826/12032902/0b8df308-ae26-11e5-9c0e-5cd7ce23cd93.png)
Chat windows, the dots are not at the end of the text so does the parenthesis.
Notice the title is aligned to the right and so does the Hash sign, should be left aligned if the room name is in English.

![screenshot_2015-12-29-11-44-50](https://cloud.githubusercontent.com/assets/406826/12032903/0da357e6-ae26-11e5-90b8-829474b52016.png)
Friend list, I don't think it should be aligned to the right if it can only be in English.

**Comment by geekgonecrazy** [comment]
Please post Mobile specific issues on the Cordova project.

https://github.com/RocketChat/Rocket.Chat.Cordova/issues

**Comment by yarons** [comment]
Thank you, posted as: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/55
