### ISSUE TITLE
Avatar for channels use AvatarExternalProviderUrl that's meant for users

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [RocketChat/Rocket.Chat#17747]
### Description:

It's great that avatars for channels are added via #3582,
however, if there's an instance that gets users avatars from external provider:
`https://somesite.com/api/get_user_avatar/{username}`

for channels like #general it tries to get avatar from
`https://somesite.com/api/get_user_avatar/{username}`
which is obviously unexpected as it's meant for users

**Comment by rodrigok** [comment]
@Gandalf-the-Grey we don't have that feature yet, it's planned for version 3.4 (next month) so I didn't get your issue.

**Comment by Gandalf-the-Grey** [comment]
Well, I'm running version 3.2.1 and yet, I clearly see the broken image icon next to channel avatar that's trying to open url according to AvatarExternalProviderUrl

Key | Value
-- | --
Hash | 485be3ba12080d3eec495affb3be219df14261a8
Date | Fri May 1 13:29:46 2020 -0300
Branch | HEAD
Version | 3.2.1
Author | Diego Sampaio
Subject | Merge pull request #17506 from RocketChat/release-3.2.1

**Comment by rodrigok** [comment]
@Gandalf-the-Grey can you provide a screen shot and inspect the element to check the URL used for the image?

**Comment by Gandalf-the-Grey** [comment]
Can't provide screenshot atm, but with AvatarExternalProviderUrl variable set to: `https://images.hive.blog/u/{username}/avatar` it ends up with:
```
<img data-src="https://images.hive.blog/u/@general/avatar" src="https://images.hive.blog/u/@general/avatar" alt="@general" class="avatar-image lazy-img">
```
