### ISSUE TITLE
No username field on the registration page

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat#17759]
### Description:

When a user registers, there's no `Username` field to set the username. The issue can be reproduced also in the official [Rocket.chat](https://open.rocket.chat) server

My instance has the following changes:
`Allow Username Change` - *false* (which disallow the user to set a username after login)
`Manually Approve New Users` - *true*

### Steps to reproduce:

1.  Go to the official Rocket.chat server
2.  Click on `Register a new account`
3.  No `Username` field is displayed

### Expected behavior:

There should be a `Username` field for the user to specify the username to use.

### Actual behavior:

There's no `Username` field, so users can't specify the username to use.

**Official server screenshot (mobile):**
![Screenshot_20200527_211336_com android chrome](https://user-images.githubusercontent.com/25697531/83062452-f53ce480-a05e-11ea-8fb8-533da8fc60d3.jpg)

**Personal instance screenshot (mobile):**
![Screenshot_20200527_204228_com android chrome](https://user-images.githubusercontent.com/25697531/83062495-0d146880-a05f-11ea-9193-d3dc8f46529a.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Ubuntu 19.10
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled (rs01)
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: **Mobile:** 4.7.0.17188 | **Desktop:** Firefox 7.60
- Operating System: **Mobile:** Android 9 | **Desktop:** Ubuntu 20.04

### Relevant logs:
No relevant logs to show

**Comment by ggazzo** [comment]
did you try to submit the form? it will show you the field to set your user name...

**Comment by PeGaSuS-Coder** [comment]
I've done that in the official server. after submitting the form you're presented with a:
```
REGISTRATION SUCCEEDED
We have sent you an email to confirm your
registration. If you do not receive an email
shortly, please come back and try again.
```

**Comment by PeGaSuS-Coder** [comment]
I see that's only possible to set the username *after* the first login.
Those users must have skipped that inadvertently.
I believe that the username setting should be `on register` and not `after first login`.

**Comment by y377** [comment]
I think the first username of the initial installation of rocketchat is 0. If username id = n, the second username is 1, and the third username is 2. In fact, there is an additional "-" in the middle, such as 1-0, 1-1, 1-2，Removing "-" is the perfect thing
