### ISSUE TITLE
Toggle for URL previews

### ISSUE THREAD

**Issue by dysphie** [RocketChat/Rocket.Chat#1775]
URL previews are often useless and take up too much space. It would be nice to have an option to turn them off or customize them.

Something like Slack has:

![slack](http://i.imgur.com/xkrlDjJ.png)

**Comment by geekgonecrazy** [comment]
This would be a very nice addition.

**Comment by engelgabriel** [comment]
see https://github.com/RocketChat/Rocket.Chat/issues/1187

**Comment by brakhane** [comment]
implemented as part of #2763

**Comment by lucasvanhalst** [comment]
@engelgabriel I wouldn't close this issue just yet, you cannot close/disable URL previews yet, only images/embedded media.
The OP wanted to disable this: 
![ ](https://i.imgur.com/Zx3Omcr.png)

**Comment by MicahZoltu** [comment]
A feature with slack that I find quite valuable is the ability for the message author to be able to delete the preview.  This lets the author of the message make a judgement call as to whether the link preview is useful or not, rather than having every user have to make a global decision on the matter.

**Comment by Frankstar** [comment]
i think it would be ok to have a "enable emded preview for given urls" -> "regex, comma seperated"
something like you do in "AutoLinker URL Regular Expression"

so we can enable the preview only for youtube, as example

**Comment by xsoft** [comment]
Is it possible to send http and https links that DONT get preview?
(yes I checked an open issue with /colapse /expand request for slack).

Just note that checking URL for TITLE actually OPENS that url.
Aka, you CANT send "delete links" or any other "perform action" links at rocket chat.
You can just make something like h**p or h**ps:// links. Its kinda .. awkward.

Idea:

http://secret.api/?delete_id=123
vs
#http://secret.api/?delete_id=123
or
|http://secret.api/?delete_id=123

h**p://secret.api/?delete_id=123
(sure works, but its not clickable)

**Comment by TwizzyDizzy** [comment]
Just closed #10606 that also wants to this option implemented. The motivation there is privacy, yet the outcome would be the same.

Cheers
Thomas

**Comment by sometoby** [comment]
Please reopen that issue, @TwizzyDizzy. You misunderstood the suggested feature.

**Comment by aradhya-gupta** [comment]
I would like to work on this issue.

**Comment by aradhya-gupta** [comment]
@engelgabriel Please review #19360 . I have added the option to toggle URLs along with media.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

This feature already exists on the latest releases >5.4

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
