### ISSUE TITLE
Disabling push messages

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#17765]
### Description:

Push messages are disables but still I see in the logs the following messages

```
server.js:204 Push ➔ debug Sent message "#channelname" to 3 ios apps 1 android apps
```

I.e. it's seems like push messages are still active, or at least some parts of it. No custom APN or FCM is set and the gateway has been disabled too.

### Expected behavior:

When disabling `Push`, no push messages are sent via the push gateway or via the native push implementation (APN/FCM).

### Actual behavior:

Push is disabled but still "push sent" log messages are generated.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Deployment Method: docker

**Comment by geekgonecrazy** [comment]
Have you tried restarting the server? This might be one of those changes that needs a restart to change

**Comment by subesokun** [comment]
Yes, I've restarted the app after applying the change.

**Comment by geekgonecrazy** [comment]
Your use of the word app has me uncertain of your response.  You did a docker stop and docker stop?

**Comment by geekgonecrazy** [comment]
@rodrigok @sampaiodiego based on what i'm reading around that log line it looks like with the change to using queues and dispursing if idle.. maybe these are getting added to the queue even though they shouldn't be?

Could this also lead to a full queue later?  Or is it removing them from the queue just not actually sending them?

**Comment by sampaiodiego** [comment]
looks like that is it @geekgonecrazy .. it still adds to the queue but fails to send (due the lack of configuration)..

we could skip adding to the queue if no valid push configuration is found 👍
