### ISSUE TITLE
Login hangs at Please Wait unpredictably

### ISSUE THREAD

**Issue by Blackclaws** [RocketChat/Rocket.Chat#17766]
### Description:

The login process hangs at Please wait... unpredictably for an infinite time. Reloading the page sometimes fixes the problem allowing login.

### Steps to reproduce:

1. Enter username and password
2. Click login

### Expected behavior:

Login Works or I get an Error

### Actual behavior:

Hangs at Login showing Please Wait and no further changes

### Server Setup Information:

- Version of Rocket.Chat Server:  3.3
- Operating System: Docker Container using Rocket.Chat Official Dockerfile
- Deployment Method: Docker
- Number of Running Instances: 1 

### Client Setup Information

- Desktop App or Browser Version: Firefox 76.0.1/Chrome 83.0.4103.6
- Operating System: Linux/Windows

### Additional context

We are using LDAP Authentication to provide user accounts. LDAP Trace logs look identical between failed and not failed login attempts.

### Relevant logs:

Firefox:

Sometimes this happens:

Firefox can’t establish a connection to the server at wss://REDACTED/sockjs/334/_t7snzwn/websocket. 2bafe4f78b03b63711c998260272d12bc1f316fc.js:152:22896
The connection to wss://REDACTED/sockjs/334/_t7snzwn/websocket was interrupted while the page was loading. 2bafe4f78b03b63711c998260272d12bc1f316fc.js:152:22896

Debugging WS Contents in Chrome it seems to hang here on failed attempts:

0: "{"msg":"method","method":"login","params":[{"ldap":true,"username":"REDACTED","ldapPass":"REDACTED","ldapOptions":{}}],"id":"4"}"

Afterwards pings and pongs still happen. But apparently no further communication regarding login takes place.

I'd be happy to provide further logs. In general LDAP works very well and access is not intermittent or otherwise problematic.

Once login is done everything works fine as well.

The problem has been around for a bit but it appears to have gotten worse.

**Comment by Blackclaws** [comment]
The bug still exists though.

**Comment by Schluggi** [comment]
This bug still exists in Version 3.10.0.

**Comment by GunnerBasil** [comment]
still exists

**Comment by itsarectangle** [comment]
I'm having the same issue, makes the platform completely unusable if a user can't even register right.  Is there really no fix or workaround for this?  This same issue has popped up going on some 3-4 years it seems.  Thx
