### ISSUE TITLE
Username is static in reactions

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat#17773]
### Description:
After importing messages from Slack, the usernames in reactions are not properly connected to the user._ids and thus don't change with differing `UI_use_real_name` setting or changing usernames.

### Steps to reproduce:
1. Do Slack import with reactions
2. Change RC username of one of the reacting users

### Expected behavior:
Username in mentions changes with the respective new username and also heeds the `UI_use_real_name` setting.

### Actual behavior:
Username stays the same from import and shows even if `UI_use_real_name` is true.
![RC_issue](https://user-images.githubusercontent.com/14276158/83160276-47394500-a107-11ea-8232-276288f044e7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information
This is client independent

**Comment by gabriellsh** [comment]
## First reaction:
![image](https://user-images.githubusercontent.com/40830821/83160663-d92c5800-a0dd-11ea-8a0a-a2ab3ff5342d.png)

## After editing username
![image](https://user-images.githubusercontent.com/40830821/83160855-1690e580-a0de-11ea-97f6-a44262dd1894.png)


This has nothing to do with slack import. Currently reactions are kept based on their usernames.

**Comment by lpilz** [comment]
You're completely right. Improving this would require changing the save reactions routine as well as the renderer I guess?

**Comment by gabriellsh** [comment]
Yeah, probably. Would have to save based on userId and the get the username from the userId on the renderer.

**Comment by lpilz** [comment]
Great, that doesn't sound too complicated :D One would of course also have to change the importers to reflect this. I currently have a project, but if this is still open when I'm finished, I'd love to take a crack at it...

**Comment by dossantg** [comment]
The problem is still present in 3.8.0. When UI_use_real_name is true, the username field is always displayed instead of the name field
