### ISSUE TITLE
3.3.0 stylesheet overwritten

### ISSUE THREAD

**Issue by juzser** [RocketChat/Rocket.Chat#17777]
### Description:

There are some css lines define the stylesheet of the UI Kit Block Builder, and mark them all as `important` and it's hard to overwritten, and break my custom stylesheet. 

The issue happens when you use `addSectionBlock` of UI Kit Block Builder.

I see the `span` is missing some classes to define text styles `rcx-box--text-color-default rcx-box--text-style-paragraph` and the actual css is added `important` (see screenshot)

### Steps to reproduce:

1. Use addSectionBlock with `text: block.newMarkdownTextObject`
2. Inspect and there are some css lines as screenshot

### Expected behavior:

Can you please keep the stylesheet minimal and be able to overwrite?
You can compare with the version 3.2.0 to see the diff. 

I can overwrite by make the selector higher priority, but I think the actual css lines are not neccessary and... should not be there. I think it should be `inherit` or something. 

### Actual behavior:

Lines:
<img width="329" alt="Screen Shot 2020-05-29 at 10 13 16" src="https://user-images.githubusercontent.com/5735071/83217977-2e787000-a197-11ea-9129-c0f156a61f71.png">

Break the custom stylesheets
<img width="562" alt="Screen Shot 2020-05-29 at 10 21 41" src="https://user-images.githubusercontent.com/5735071/83217983-320bf700-a197-11ea-87c1-7fa0adbdb350.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Deployment Method: Manual - Development localhost
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: MacOS

**Comment by agepilar** [comment]
same for "Direct message you have joined" headline:

> .rcx-box.rcx-\@1noonzv {
> color: var(--rcx-color-foreground-default,#2f343d) !important;
> font-size: 1.375rem !important;
> font-weight: 400 !important;
> line-height: 2rem !important;
> letter-spacing:` 0rem !important;
> -moz-box-flex:` 1 !important;
> flex-grow: 1 !important;
> }

Need to change the color.

**Comment by ggazzo** [comment]
sorry @juzser but I think you didnt get the point, these classes are autogenerated by the props... I suggest you to check https://github.com/RocketChat/Rocket.Chat.Fuselage repository

you will should never win against `.rcx-box.rcx-@something` because it is how the component was built....

did you try overwrite `--rcx-color-any-variable` ?

I'm really sorry, we are in the middle of one transition... soon as possible we gonna solve this problem

are you using a custom css right? post here, maybe I can find a workaround for you

**Comment by juzser** [comment]
Thank you @ggazzo, actually I overwritting the css by select higher level of the selectors, I know it's messy but fine for now. 

Hopefully this problem can be solved soon.
