### ISSUE TITLE
Login via SMTP auth

### ISSUE THREAD

**Issue by joubertredrat** [RocketChat/Rocket.Chat#1777]
Hi guys,

I liked this app a lot and I'm looking here that have support to LDAP. I know another project that uses SMTP as auth and looks fine, then I think that can be good idea to Rocket Chat support auth my smtp too.

Thanks

**Comment by geekgonecrazy** [comment]
@joubertredrat we support auth for smtp.  

SMTP url: smtp://username:password@host  Can be set via environment variable MAIL_URL or through interface.  I think this is one of those things that require restarting after setting through the UI.

**Comment by engelgabriel** [comment]
@geekgonecrazy he meant for login into Rocket.Chat, using SMTP like an LDAP server.

**Comment by joubertredrat** [comment]
Hi guys,

@engelgabriel exactly, one open source project that have this feature as example is [Gogs](https://gogs.io)

**Comment by renothing** [comment]
does this feature in plan now?

**Comment by duderino416** [comment]
Nextcloud has a similar feature for IMAP, came upon this request by way of google while looking for similar to RocketChat. This is their solution for IMAP https://github.com/nextcloud/apps/blob/master/user_external/lib/imap.php, not sure if applicable/usable on RocketChat

**Comment by ftoledo** [comment]
yes i like this too. Maybe think in more plugueable authenticators like pop3, samba, ftp,  and simple external protocol (just like prosody as example https://modules.prosody.im/mod_auth_external.html)

**Comment by JSzaszvari** [comment]
SMTP isn't really designed at all, even in the slightest to be a authentication provider.

**Comment by ftoledo** [comment]
Yes i agree with @JSzaszvari , i think that another protocols are more auth friendly.

**Comment by SeanPackham** [comment]
We won't be implementing this feature.
