### ISSUE TITLE
RocketChat app scales to maximum pods number in the deployment when HPA is enabled on Kubernetes

### ISSUE THREAD

**Issue by ilchebedelovski** [RocketChat/Rocket.Chat#17788]
### Description:

I am experiencing some resource issues when the application is deployed on Kubernetes and the Horizontal Pod Autoscaler is enabled for that specific deployment.

This is happening when a new pod needs to be initialized, on every pod initialization, database migration is scheduled inside the container, during the database migration process, because of the CPU load a new pod is initialized, that new pod initializing process start new database migration, this loop is repeating until the maximum number of pods is reached.

My question is: is the database migration action required to be part of the main container where the application lives or there is another way how we can avoid the database migration to be executed on every new pod initialization in Kubernetes?

### Steps to reproduce:

1. Deploy the Rocket.Chat application on Kubernetes
2. Enable the Horizontal Pod Autoscaler
3. Monitor the resources when the number of pods is increasing

### Server Setup Information:

- Rocket.Chat 3.0.9
- Kubernetes v1.16.8-gke.15

**Comment by geekgonecrazy** [comment]
I would recommend basing the auto scale based on a custom metric just based on cpu isn’t really a good one alone.  Especially on scale.

One strategy to also handle this would be to start a single pod let it run the migration and then update your main deployment
