### ISSUE TITLE
[Bug] Setting room topics with single or double quotes leads to HTML escaping

### ISSUE THREAD

**Issue by zdelanofw** [RocketChat/Rocket.Chat#17797]
### Description:

Whenever I create a room and set the topic to contain single and double quotes, HTML escaping occurs when the channel sends a message saying what the user set the topic to.

### Steps to reproduce:

1. Create a room that can have a topic set (channel or private group).
2. Edit the room info.
3. Set the topic to `This room can't handle single quotes? How about "double quotes"?`.

### Expected behavior:

I expect to see a message like:

>Zach Delano @zdelano
>9:34 AM
>`Room topic changed to: This room can't handle single quotes? How about "double quotes"? by zdelano`

### Actual behavior:

The message displayed is (observe the HTML escaping of the single and double quotes):

>Zach Delano @zdelano
>9:34 AM
>`Room topic changed to: This room can&#39;t handle single quotes? How about &quot;double quotes&quot;? by zdelano`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: Linux
- Deployment Method: Helm
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.2.3

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu 20

### Additional context

N/A

### Relevant logs:

N/A

**Comment by EnCz** [comment]
Same problem btw with the user bio in righter sidebar:
![image](https://user-images.githubusercontent.com/7642122/83559078-4132d200-a514-11ea-9eb4-2aaf38571a5c.png)

**Comment by MartinSchoeler** [comment]
Hello! This issue seems to be solved in the latest develop version.

![image](https://user-images.githubusercontent.com/20868078/88396500-007b6a80-cd99-11ea-86ea-7857d87eb286.png)

So I will be closing this issue, if you see this problem again, feel free to reopen this issue. Thanks!
