### ISSUE TITLE
Rocket.Chat Macros

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1779]
An executable script that can 'send messages', 'click button' and 'flick menus' using Rocket.Chat's UI.

Macros can be:
- dragged and dropped into the UI for execution
- be driven by higher level script or programs (say, from an ES6 master script executing on the browser)
- stored and retrieved by name or ID
- written by anyone who knows the syntax
- generated by AI due to its regular syntax

Macros are useful for:
- integrating apps that requires 'canned sequences of RC UI interactions'
- support - imagine "How do you configure mobile notifications?  Just drag and drop this macro into your RC session..."
- automated testing and distributed remote testing
- instant ad-hoc fixes for problems such as #885

**Comment by Megatronic79** [comment]
+1 for this - would be great for the testing phases of RC to be able to deploy a script that tests each of the core components before migrating dev to master.

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.
