### ISSUE TITLE
Push notifications broken with SSL cerificate expirary for https://gateway.rocket.chat/

### ISSUE THREAD

**Issue by thebrooder** [RocketChat/Rocket.Chat#17798]
I have talked to some colleagues who also have an instance of rocket.chat running at their organization and its affecting them as well.   We have 2 instances of rocket.chat and both are affected.   Push notifications are failing as of May 30th with a certificate expired error on rocket.chat's public push gateway...  https://gateway.rocket.chat

Looks like the issue may be related to AddTrust Root Expiration expiring on May 30th?
https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

We are running the snap package installation of rocketchat-server, version 2.4.11, revision 1427

```
Jun 01 08:38:06 rchattst rocketchat-server.rocketchat-server[23532]: server.js:204 System ➔ error Error sending push to gateway (4 try) -> { Error: certificate has expired
Jun 01 08:38:06 rchattst rocketchat-server.rocketchat-server[23532]:     at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
Jun 01 08:38:06 rchattst rocketchat-server.rocketchat-server[23532]:     at emitNone (events.js:106:13)
Jun 01 08:38:06 rchattst rocketchat-server.rocketchat-server[23532]:     at TLSSocket.emit (events.js:208:7)
Jun 01 08:38:06 rchattst rocketchat-server.rocketchat-server[23532]:     at TLSSocket._finishInit (_tls_wrap.js:643:8)
Jun 01 08:38:06 rchattst rocketchat-server.rocketchat-server[23532]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'CERT_HAS_EXPIRED' }
```

**Comment by graywolf336** [comment]
Closing as this is now resolved, see #17790
