### ISSUE TITLE
BUG: As admin, I cannot open the "users" interface if there are users with blank emails

### ISSUE THREAD

**Issue by ryjones** [RocketChat/Rocket.Chat#17806]
### Description:

If I visit the admin UI, having a user with a blank email causes UI to not render.

### Steps to reproduce:

1. go to https://chat.whatever/ as admin
2. click on administration
3. click on users

### Expected behavior:

I expect to be able to administer my users

### Actual behavior:

The UI is blank.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0 (commit a9872957180059094e50678ec311b2fcef8f61ad)
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.17.0
- MongoDB Version: 3.6.18

### Additional context
001-rs:PRIMARY> db.getCollection('users').find( { "emails": { $exists: true, $eq: []} }).count()
23164
001-rs:PRIMARY> db.getCollection('users').find( { "emails": { $exists: true, $gt: []} }).count()
2165
001-rs:PRIMARY> db.getCollection('users').find( { "emails": { $exists: false} }).count()
4
001-rs:PRIMARY> db.getCollection('users').find().count()
25333

**Comment by ggazzo** [comment]
Ok its small bug we gonna fix, but just to be sure how did you create these users? empty emails are not expected actually

**Comment by ryjones** [comment]
they are created with SAML logins vi LFID - https://identity.linuxfoundation.org/

**Comment by mariaeduardacunha** [comment]
Can you send the error(s)?

**Comment by ryjones** [comment]
there are no errors, nothing renders. I don't see anything in the log.

**Comment by mariaeduardacunha** [comment]
When the UI is blank, what appears on the console?

**Comment by ryjones** [comment]
@mariaeduardacunha https://gist.github.com/ryjones/4a67504fe1159cc338787fd8178ddb43

**Comment by mariaeduardacunha** [comment]
@ryjones send me the mongo logs, please

**Comment by ryjones** [comment]
I don't have access to those

**Comment by ggazzo** [comment]
@ryjones gonna provide a workaround, but after I want to ask you to help us to understand whats going on... its not an empty email the problem, its some different email schema... I checked the code and we should prepared for empty emails...
