### ISSUE TITLE
Seeking large production site deployment advice

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#1780]
what is the most recommended  and secure way to deploy rocket.chat for a live site

**Comment by k0nsl** [comment]
Hi @djeber !
The most recommended route is likely deployment via docker. I don't follow that route myself, but I'm sure others would say docker is the preferred method of deployment on a production site.

**Comment by djeber** [comment]
thanks @k0nsl yeah docker is good but i dont know how to back-up using docker or how to modify a file or how to update thats why i dont want to use it

**Comment by k0nsl** [comment]
@djeber,
You can try the method I've been doing since the very beginning. It's apparently not recommended, but it works fine for me in production ;)
https://github.com/RocketChat/Rocket.Chat/issues/724#issuecomment-166584099
Best wishes,
-k0nsl

**Comment by Sing-Li** [comment]
It depends on so many factors ...hardware/VM  you have, your expected user/loading, your familiarity with the platform tech, size of your maint crew, your budget, and many many more.  It is not possible for a single reccomendation.

**Comment by djeber** [comment]
currently i have vps server  2cores and 4gb ram and 50gb ssd i'm expecting at the first month to get at least 10,000 user with average of 3000 to 5000 user online and it will expand by time, i think i will go with the tutorial that i fount on the wiki for ubuntu vps is it good or shall i consider something else @Sing-Li  !!

**Comment by Sing-Li** [comment]
@djeber I wish I can give you better news.  But that VPS configuration will not handle the described load.  Assuming those are real hard number, you'll need to cluster multiple larger instances. Ideally,  you should be running on managed bare-metal hardware that you control - if the site/project is very important to you.  Also you need to be familiar with whatever clustering technology you decide to use, and be prepare to manage such a cluster with a 24 x 7 crew.  If all of this sounds alien to you, best to seek professional help.
