### ISSUE TITLE
Improvement - error-user-is-last-owner

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat#17805]
### Description:

Currently, it is not possible to delete an user when he is the last owner of a room. This behavior is set on [deleteUser.js](https://github.com/RocketChat/Rocket.Chat/blob/6f041baa25e14f45d43d77698db216c14815d294/app/lib/server/functions/deleteUser.js#L61).

### Steps to reproduce:

1. End user is the only owner of a room
2. Admin tries to delete him (via API or Users panel)
3.Error is triggered

### Expected behavior:

The error explanation itself is not clear, and sometimes an admin should have an 'override' to delete the user anyway.

Two suggestions in order to improve this scenario:

1. Add a special parameter in the API method call so the admin can delete the user even if he is the only owner of a room. The logic should add the oldest room user as the owner (or add the possibility for the admin himself to select who should be the owner)

OR

2. At least improve the error message and display the rooms which the user is the owner so the admin can go there and adjust it manually instead of having to look for it,.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0-develop

**Comment by sampaiodiego** [comment]
the PR https://github.com/RocketChat/Rocket.Chat/pull/16088 closes this issue
