### ISSUE TITLE
Active chat still triggering push notifications 

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat#17817]
### Description:

Push notification are being sent to the mobile even if it is read in the web.
According to 3.2.0 change log , when the user reads a channel all the notifications for that user are removed (clear queue), but this is not the behave I am seeing. When I am online and actively talking to someone, sometimes I just receive the push in my mobile even though I have already read the message and even replied to it on the web version.
```


Better Push and Email Notification logic (#17357)

We are still using the same logic to define which notifications every new message will generate, it takes some servers' settings, users's preferences and subscriptions' settings in consideration to determine who will receive each notification type (desktop, audio, email and mobile push), but now it doesn't check the user's status (online, away, offline) for email and mobile push notifications but send those notifications to a new queue with the following rules:

    When the user is online the notification is scheduled to be sent in 120 seconds

    When the user is away the notification is scheduled to be sent in 120 seconds minus the amount of time he is away

    When the user is offline the notification is scheduled to be sent right away

    **When the user reads a channel all the notifications for that user are removed (clear queue)**

    When a notification is processed to be sent to a user and there are other scheduled notifications:
        All the scheduled notifications for that user are rescheduled to now
        The current notification goes back to the queue to be processed ordered by creation date

```

### Steps to reproduce:

1. Talk to someone on the web browser
2. After a couple of minutes, push is received on the mobile

### Expected behavior:

Message already seen on the web should not be sent to the mobile.

### Actual behavior:

I receive the 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System:  Docker container
- Number of Running Instances: 3

### Client Setup Information

- Desktop App or Browser Version: Web on Chrome and Firefox
- Operating System: Linux

**Comment by rodrigok** [comment]
@jsalatiel we did some tweaks on this lately, would you be able to test version 3.4.1 and let us know if you still see the problem?

Thanks

**Comment by jsalatiel** [comment]
Have 3.4.1 been released already ? I would be glad to test it. I am on 3.3.3 right now.

**Comment by jsalatiel** [comment]
btw, I have just read 3.4.0 change log and i see :
```
NOTIFICATIONS_SCHEDULE_DELAY_ONLINE
NOTIFICATIONS_SCHEDULE_DELAY_AWAY
NOTIFICATIONS_SCHEDULE_DELAY_OFFLINE
``` 
1) Are this variable in seconds or minutes ?
2)  Seconds == 0  means send right away ?
