### ISSUE TITLE
DesktopApp and self-signed certificate

### ISSUE THREAD

**Issue by Papyruse** [RocketChat/Rocket.Chat#1781]
Hi guys,

We need to use use a self-signed certificate on our own server, but  in this case desktop app cannot connect with issue "Not a valid instance url". No problem with a signed certificate (use for test) on the same server. Is there a workaround ? Seems need an option on client to accept connexion to ignore/accept any certificate...

Thanks

**Comment by henres** [comment]
Same problem here.
When use http, it's work like a charm, when use self signed certificate: "Not a valid instance url"

**Comment by afoard** [comment]
Same issue here. Self-signed cert behind Apache reverse-proxy. Port 80 works fine, 443 gives the "Not a valid instance url"

**Comment by Shelnutt2** [comment]
The issue is electron/chromium by default does not allow for invalid certificates. Launch the desktop app with --ignore-certificate-errors and it will launch.

The "Allow invalid self-signed certs" is only for previews of links posted in chat.

**Comment by prohde** [comment]
It is the same with the Android application and certificates signed by CAcert.org.

**Comment by matthias-brun** [comment]
If you're using a self-signed certificate just make sure to mark it as trusted in your OS' certificate store. (e.g. keychain on os x) Then the desktop client should be able to connect just fine. Along with that your browser is also gonna stop giving you invalid cert warnings.

**Comment by llitfkitfk** [comment]
docker image version 0.16 works correctly: #2284

**Comment by brylie** [comment]
We are experiencing this issue with a [LetsEncrypt](https://letsencrypt.org/) certificate.

**Comment by Shelnutt2** [comment]
@brylie Let's Encrypt certificates should work fine. Did you get your certificate from the staging CA by chance? Only the production LE certificates are cross signed.

You also need to make sure you are using the fullchain.pem.

**Comment by brylie** [comment]
OK, thanks @Shelnutt2. We will look further into the LE issue.

**Comment by philipwhiuk** [comment]
> The issue is electron/chromium by default does not allow for invalid certificates. Launch the desktop app with --ignore-certificate-errors and it will launch.

Please don't suggest this as a workaround @Shelnutt2 . What you've done here is remove all point to running over SSL.

**Comment by prohde** [comment]
@philipwhiuk: What exactly removes all points of running Rocket.Chat over SSL?
For me it is not clear if you meant using the `fullchain.pem` or launching the application with `--ignore-certificate-errors`.

**Comment by philipwhiuk** [comment]
And yes, just to clarify, installing the PEM file is fine from a security standpoint. The issue I have with --ignore-certificate-errors is that it means any certificate will be accepted. See posts by Chromium developers on this here: https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/mB2KJv_mMzM

For testing it's abhorrent but slightly understandable. For production it's a disaster waiting to happen.

**Comment by llitfkitfk** [comment]
update client to version 1.0.0, works fine

**Comment by alfrescoo** [comment]
I setup a server https://dingding.so, It doesn't work with 1.0.0 version client.

**Comment by llitfkitfk** [comment]
@alfrescoo u need a [LetsEncrypt](https://letsencrypt.org/) certificate.

**Comment by alfrescoo** [comment]
@llitfkitfk  ok, thanks.

**Comment by MartinSchoeler** [comment]
Closing this issue due lack of updates in a long time
