### ISSUE TITLE
BigBlueButton step by step and the problem.

### ISSUE THREAD

**Issue by runawaydevil** [RocketChat/Rocket.Chat#17812]
So I just installed on AWS the BBB.
When I tried to integrate with rocketchat I just set my URL and SECRET. It does not work.
So I installed webhooks and tried again. Not worked. I didn't change a line.
So I get the Link to the API-Mate and joined in he API Mate website and put there the url and secret, I'm not sure if I did right because english is not my main language and sometimes I do mistakes.
Well, the website shows tons of links and I don't know what to do since now. I tried to put all of them on rocketchat and nothing worked. What should I look for? What an webhook bbb looks like for rocket chat?

What should I do? 

Thank you buddies.

**Comment by runawaydevil** [comment]
Anyone? :(

**Comment by Karting06** [comment]
Did you set your root url as url? 

Example: https://bbb.example.com
