### ISSUE TITLE
Outgoing WebHook doesn't work when Trigger Words is empty

### ISSUE THREAD

**Issue by kto2038** [RocketChat/Rocket.Chat#17820]
### Description:

With empty "Trigger Words" setting, Outgoing WebHook doesn't work.
Debug log says:
Integrations ? Outgoing WebHook.debug The trigger word which "test webhook" was expecting could not be found, not executing.

When I set "Trigger Words" as empty, triggerWords value is
* in RC 3.2.2: []
* in RC 3.3.0: [""]

### Steps to reproduce:

1. Administration -> Integrations -> +New
2. Make a new Outgoing WebHook with settings:
Event Trigger: Message Sent
Name: test webhook
Channel: all_public_channels
Trigger Words: (empty)
URLs: http://127.0.0.1/
Post as: admin
3. Send a message to any public channel

### Expected behavior:

The WebHook is executed.

### Actual behavior:

The WebHook isn't executed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: CentOS 8.1
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Firefox 77.0.1
- Operating System: Windows 10

### Relevant logs:

Created WebHook:
I20200604-16:30:02.068(9) Meteor ➔ method addOutgoingIntegration -> userId: ZBnqdxKMCfHbLWTCn, arguments: [{"alias":"","avatar":"","channel":"all_public_channels","emoji":"","enabled":true,"event":"sendMessage","impersonateUser":false,"name":"test webhook","retryCount":6,"retryDelay":"powers-of-ten","retryFailedCalls":true,"runOnEdits":true,"script":"","scriptEnabled":false,"targetRoom":"","token":"xkzfaj95iur","triggerWordAnywhere":false,"triggerWords":[""],"type":"webhook-outgoing","urls":["http://127.0.0.1"]}] 

Sent message:
I20200604-16:32:19.651(9) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: GENERAL
I20200604-16:32:19.664(9) Integrations ➔ Outgoing WebHook.debug Found 1 to iterate over and see if the match the event.
I20200604-16:32:19.670(9) Integrations ➔ Outgoing WebHook.debug Is "test webhook" enabled, true, and what is the event? sendMessage
20200604-16:32:19.685(9) Integrations ➔ Outgoing WebHook.debug Starting to execute trigger: test webhook (WFP4iHYxG6XbRGgLq)
I20200604-16:32:19.689(9) Integrations ➔ Outgoing WebHook.debug The trigger word which "test webhook" was expecting could not be found, not executing.

**Comment by twkrol** [comment]
Got the same, installed RocketChat today.

**Comment by JakobFerdinand** [comment]
I got the same experience. Many of my webhooks stopped working after updating to the new version. :/

I hardly ever use trigger words because i parse the needed information from the text.

**Comment by Vinutha-Garimella** [comment]
Even I got the same issue, for RocketChat version:v3.3.3

**Comment by mk0116** [comment]
can someone please fix this issue..?

**Comment by mk0116** [comment]
confirmed working fine on v3.5.0
