### ISSUE TITLE
Channel scrolls to random message

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#17834]
### Description:

Our users have reported that RC will seemingly scroll to a random message when entering a channel. This is happening for users who are already in a channel, e.g. channel "A". If they are currently viewing channel "B", and then switch to "A", they may be sent back in time to a very old message (but not every time). They will then scroll to the current message and the channel will behave correctly from that point on, unless they leave the channel and come back.

If they leave "A" and then come back to "A" later (e.g. in the same session, without reloading the browser), it is possible that they will get jumped up again, but not to the same message. It tends to jump to several weeks prior.

This has been happening for a while now, since we upgraded to v3.1.1.

It was noticed that, with the developer tools / network tab open, there may be a pattern. 

### Steps to reproduce:

1. Jill is actively using RC in channel "A" and has an unread chat in channel "B"
2. Tim signs on to RC
3. Jill has the developer tools / network tab open and notices Tim's avatar was downloaded
3. Jill switches to channel A to view her unread messages _from the last day_
4. RC scrolls _a month back_ in channel A and seems to stop at a post from Tim
5. Jill is highly confused, since she has already seen all of these messages -- she scrolls back to the current message and marks all messages as read

This may repeat the next time Jill moves between channels.

### Expected behavior:

RC should scroll to the first unread message, not a "seemingly random" message, when switching to a channel with unread messages.

### Actual behavior:

RC scrolls to a "seemingly random" message when switching to a channel with unread messages -- perhaps linked to a user having just logged in, who has posted in that channel in the past.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: RHEL7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.9

### Client Setup Information

- Desktop App or Browser Version: Chrome current/latest; Firefox current/latest; Edge current/latest; IE latest
- Operating System: Windows; Mac

### Additional context

Hard/impossible to reproduce, cause is unknown but best lead we have is that it is somehow related to a user logging in to RC.

**Comment by JoshMcCullough** [comment]
We're still seeing this issue so I'd like it to be kept open, please.

**Comment by NicolasDionB** [comment]
I experience it a lot and it's a pain! Maybe I'll switch back to an older version, it's really frustrating. Everytime I swtich conversation, the scroll goes back up to an older message, I then have to scroll all the way down to see the new message. I don't understand that there doesn't seem to be a lot of people experiencing that. It's a major thing.

**Comment by Ishrat1401** [comment]
This issue can't be reproduced in the current version of Rocket chat. Now when you switch between the conversations, the scroll goes to the latest message at the bottom and you have an option to scroll to the first unread message at the top.

**Comment by mrsadko** [comment]
We still have such behavior in the latest version.

**Comment by NicoHaase** [comment]
Could this be the same as https://github.com/RocketChat/Rocket.Chat/issues/20570?
