### ISSUE TITLE
Starred message bug

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#1784]
When someone else than you stars a message and you click on the little cog from said message, it shows 'remove star' whilst _you_ never starred it.

**Comment by geekgonecrazy** [comment]
@lucasvanhalst is this still an issue?

**Comment by marceloschmidt** [comment]
@geekgonecrazy it is. This happens on messages that are received via stream only. When someone stars that message, everyone that received that message from stream will also see the message as starred (even the person who sent the message).

**Comment by marceloschmidt** [comment]
I was trying to come up with a fix, but then the progress was lost... we should try to fix that again anytime soon ;)

**Comment by geekgonecrazy** [comment]
Makes sense!  I just hadn't seen it. 😄

**Comment by lucasvanhalst** [comment]
Couldn't reproduce this anymore
