### ISSUE TITLE
Unable to enter a channel name for offlineMessageChannelName

### ISSUE THREAD

**Issue by Mystikal57** [RocketChat/Rocket.Chat#17846]
Description:
unable to enter a channel name in "Send this department's Livechat offline messages to a channel
"
Location: Omnichannel settings -> departments -> edit department -> "Send this department's Livechat offline messages to a channel"

Steps to reproduce:
Entering a channel name or trying to select a channel

Actual behavior:
Channel not found or unable to select a channel
-> save
Channel name not saved

Server Setup Information:
Version of Rocket.Chat Server: 3.3
Operating System: ubuntu 18.04.6
Deployment Method: 
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version:12.16.1
MongoDB Version:4.0.16

Client Setup Information
Desktop App or Browser Version: 2.17.7 or chrome
Operating System: windows

### Relevant logs:

Server log:
I20200608-11:29:00.942(2) server.js:204 API ➔ debug GET: /api/v1/livechat/department/MrDT2PEBn2uhuyHaS 
I20200608-11:29:00.950(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     department: {       _id: 'MrDT2PEBn2uhuyHaS',       enabled: true,       name: 'Info',       description: '',       showOnRegistration: true,       showOnOfflineForm: true,       requestTagBeforeClosingChat: false,       email: '****@***.***',       chatClosingTags: [Array],       offlineMessageChannelName: '',       numAgents: 1,       _updatedAt: 2020-06-08T09:19:32.569Z     },     agents: [ [Object] ],     success: true   } } 
I20200608-11:29:01.094(2) server.js:204 Meteor ➔ method public-settings/get -> userId: 66n6kZhvuevG8w64d, arguments: [{}] 
I20200608-11:29:01.098(2) server.js:204 Meteor ➔ method livechat:getTagsList -> userId: 66n6kZhvuevG8w64d, arguments: [] 
I20200608-11:29:01.169(2) server.js:204 Meteor ➔ method rooms/get -> userId: 66n6kZhvuevG8w64d, arguments: [{}] 
I20200608-11:29:01.185(2) server.js:204 Meteor ➔ method subscriptions/get -> userId: 66n6kZhvuevG8w64d, arguments: [{}] 
I20200608-11:29:05.668(2) server.js:204 API ➔ debug GET: /api/v1/rooms.autocomplete.channelAndPrivate?selector={%22term%22:%22test%22} 
I20200608-11:29:05.673(2) server.js:204 API ➔ debug Success {   statusCode: 200,   body: {     items: [       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object],       [Object], [Object]     ],     success: true   } } 
I20200608-11:29:07.279(2) server.js:204 API ➔ debug GET: /api/v1/rooms.info?roomId=K4WLbgaZJ9b99sJhk 
I20200608-11:29:07.283(2) server.js:204 Meteor ➔ method canAccessRoom -> userId: 66n6kZhvuevG8w64d, arguments: ["K4WLbgaZJ9b99sJhk","66n6kZhvuevG8w64d",{}] 
I20200608-11:29:07.289(2) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: {     success: false,     error: 'not-allowed',     stack: undefined,     errorType: 'Not Allowed'   } } 

Browser log:
2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48 GET https://****.***/api/v1/rooms.info?roomId=K4WLbgaZJ9b99sJhk 400 (Bad Request)
send @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48
ajax @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48
l @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
_jqueryCall @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
get @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
get @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
r.livechatDepartmentForm.onCreated.onSelectOfflineMessageChannel @ /app/livechat/client/views/app/livechatDepartmentForm.js:1
processSelection @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
onItemClick @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418
click .rc-popup-list__item @ /app/livechat/client/views/app/livechatAutocompleteUser.js:1
(anonymous) @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
t._withTemplateInstanceFunc @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
(anonymous) @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
(anonymous) @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
h._withCurrentView @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
(anonymous) @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
delegatedHandler @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:209
dispatch @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48
g.handle @ 2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48
2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418 Uncaught (in promise) Error: Bad Request
    at originalCallback (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418)
    at u (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418)
    at Object.processTwoFactorError (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418)
    at Object.a [as error] (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:418)
    at c (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48)
    at Object.fireWith [as rejectWith] (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48)
    at w (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48)
    at XMLHttpRequest.<anonymous> (2bafe4f78b03b63711c998260272d12bc1f316fc.js?meteor_js_resource=true:48)

**Comment by renatobecker** [comment]
Hi @Mystikal57 

As you can see in the log you shared:

**I20200608-11:29:05.668(2) server.js:204 API ➔ debug GET: /api/v1/rooms.autocomplete.channelAndPrivate?selector={%22term%22:%22test%22}
I20200608-11:29:05.673(2) server.js:204 API ➔ debug Success { statusCode: 200, body: { items: [ [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object] ], success: true } }**

The endpoint that search channels returned 10 items(array of **[Object]**) as a result, so it's weird that those results aren't being displayed.
Can you share a gif (or something) demonstrating your UI when selecting the channel?

Thanks.

**Comment by Mystikal57** [comment]
![rocketchat](https://user-images.githubusercontent.com/8256583/84031050-4d47e500-a995-11ea-8ecc-84778676ff76.gif)

**Comment by Mystikal57** [comment]
Hi, any idea ?

**Comment by renatobecker** [comment]
> Hi, any idea ?

Can you please share the details about the channel you're trying to find?
Like, is the channel private?

I'm asking because other channels are listed, so it seems like the channel doesn't exist or has some restrictions.

**Comment by Mystikal57** [comment]
Hi, thanks
Seems theses channels have sames parameters:
![rc](https://user-images.githubusercontent.com/8256583/85264512-167fcd80-b471-11ea-86ec-4d73072ebe5a.png)

**Comment by renatobecker** [comment]
Hi @Mystikal57 this issue has been fixed by https://github.com/RocketChat/Rocket.Chat/pull/17970.
Please, test it out as soon as then release `3.4` is out.
Thanks.
