### ISSUE TITLE
SAML and LDAP configs disallow mapping the same attribute twice

### ISSUE THREAD

**Issue by pitchum** [RocketChat/Rocket.Chat#17847]
### Description:

The parameter *User Data Field Map* in both LDAP and SAML config is in a format that disallows complex setup. Since it is expressed in JSON format, keys need to be unique. Thus it prevents using the same attribute twice.

### Steps to reproduce:

For example, it is not possible to use the mail LDAP attribute in order to fill both *email* and *username* fields in RC.

```json
{"mail": {"field" :"username", "regex": "(.*)@.+$"}, "mail":"email", "displayName": "name"}
```

It would be more appropriate to swap keys and values to allow the following syntax instead:

```json
{"username": {"field" :"mail", "regex": "(.*)@.+$"}, "email":"mail", "name": "displayName"}
```
Or did I miss something?

**Comment by pierre-lehnen-rc** [comment]
Version 3.4 fixed that for the SAML mapping, but the LDAP hasn't changed.
