### ISSUE TITLE
Room type in edit room panel is inverted

### ISSUE THREAD

**Issue by cking-vonix** [RocketChat/Rocket.Chat#17851]
### Description:

When administering rooms the radio buttons for room type of public / private are inverted.

### Steps to reproduce:

With a fresh default install:

1. Open Administration
2. Click Rooms
3. Click on General
4. Notice the "Private" radio button is checked
 
1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: 12.16.1
- MongoDB Version: 4.2.5

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Ubuntu 20.04

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/17853
