### ISSUE TITLE
Primary background color set for UI has no effect

### ISSUE THREAD

**Issue by fir3bird** [RocketChat/Rocket.Chat#17858]
### Description:

The background and primary colors set in the layout settings have no effect on the acutal UI appearance.

### Steps to reproduce:

1. Administration
2. Layout in the left menu
3. Colors
4. Set primary and primary background to color of choice
5. See that after saving the changes nothing happens

### Expected behavior:

Setting primary and primary background color will change the background color of channel list on the left.

### Actual behavior:

The background color stays in a dark gray instead of the chosen dark blue.

![image](https://user-images.githubusercontent.com/33957373/84148195-e68efe00-aa5e-11ea-99c2-06b55563c360.png)

![image](https://user-images.githubusercontent.com/33957373/84148254-01fa0900-aa5f-11ea-9a6e-c42b523762fe.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Deployment Method: docker

### Client Setup Information

- Desktop App or Browser Version: Desktop App and Chrome Browser
- Operating System: Windows 10

**Comment by mariaeduardacunha** [comment]
Tested in the latest version (3.4.0-develop) and this issue doesn't happen anymore. Also, try to hard refresh the browser (Command + Shift + R on macOS / Ctrl + F5 on windows), or open on anonymous tab. If you happen to experience this issue again, please reopen this with updated details. Thanks!
