### ISSUE TITLE
Users.list does not return all users

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat#17869]
### Description:

When using `users.list` via the API, only 50 users are returned of a total >191

### Steps to reproduce:

1. Call 
```
curl -s -G -H "X-Auth-Token: <token>" -H "X-User-Id: <id>" <url>/api/v1/users.list
```

### Expected behavior:

Return all users.

### Actual behavior:

Only 50 of 191 users are returned:
```
{"users": [....],"count":50,"offset":0,"total":191,"success":true}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

**Comment by ankar84** [comment]
Check these two settings:
**Admin UI - General - REAT API - Default Count**
**Admin UI - General - REAT API - Allow Getting Everything**
![image](https://user-images.githubusercontent.com/4023037/84345837-181add00-abb7-11ea-9cc4-d0fb96859eb8.png)

**Comment by lpilz** [comment]
That solved it! Cheers :)
