### ISSUE TITLE
Integrations / Gitlab

### ISSUE THREAD

**Issue by felixwidjaja** [RocketChat/Rocket.Chat#1787]
Hi, 

I'm trying to set any gitlab push event relayed into #git in our rocketchat.
To do that I set Administration / integrations / New.
I copy paste webhook URL into gitlab project but it's not working. No push event ever relayed to #git 

I have used this before to relay in Slack. And still using webhook in Gitlab to communicate with http://deploybot.com

Anything that I missed? Thanks in advance.

**Comment by sampaiodiego** [comment]
I just tested and it works @felixwidjaja .. what rocket.chat version are you running?
also, in GitLab I configured it in: `Project Settings > Services > Slack` .. Is it the same place you configured yours?

**Comment by felixwidjaja** [comment]
Thanks @sampaiodiego never thought about it before.
I was a `Project Settings > Web hooks`

**Comment by felixwidjaja** [comment]
@sampaiodiego 
My version is: 0.11.0
I just tested and it doesn't work.
I have make sure everything is setup. I have "bot" username and "#git" channel, entered the correct webhook in Slack service. But the push event never come. Any tips?

**Comment by sampaiodiego** [comment]
do you really have a user called `bot` in your instance? it must exists!
is any other webhook working on your rocket.chat? did you tested the `curl` command provided in incoming webhook configuration page at rocket.chat?
are you using gitlab.com or self-hosted?
you can test if gitlab is sending the webhook using a http://requestb.in/

**Comment by sampaiodiego** [comment]
another thing I just noticed when testing it again, have you activated the service in gitlab?
you must see a green dot after activating:
![image](https://cloud.githubusercontent.com/assets/8591547/12063941/74bacf94-af9e-11e5-94f2-0411db2c4892.png)

**Comment by felixwidjaja** [comment]
Hi @sampaiodiego 

Thank you for helping me.

> do you really have a user called bot in your instance? it must exists!
Yes I do.
<img width="358" alt="screen shot 2015-12-31 at 6 36 57 pm" src="https://cloud.githubusercontent.com/assets/4198376/12064114/7cfa4d48-afed-11e5-9ade-9cd4b151a280.png">

> is any other webhook working on your rocket.chat? 
None. Just this incoming webhook
<img width="868" alt="screen shot 2015-12-31 at 6 37 43 pm" src="https://cloud.githubusercontent.com/assets/4198376/12064118/9e9ba924-afed-11e5-838d-66982370825b.png">

> did you tested the curl command provided in incoming webhook configuration page at rocket.chat? 
How to test curl?

> you can test if gitlab is sending the webhook using a http://requestb.in/
here's the result: http://requestb.in/1lt0x5b1?inspect

> are you using gitlab.com or self-hosted?
gitlab.com

> another thing I just noticed when testing it again, have you activated the service in gitlab?
Yes I do
<img width="971" alt="screen shot 2015-12-31 at 6 38 47 pm" src="https://cloud.githubusercontent.com/assets/4198376/12064127/c647d9d4-afed-11e5-9b45-d40268dde0b5.png">

**Comment by sampaiodiego** [comment]
your requestb.in is private :disappointed:

you can found the `curl` command just above the example request in webhook configuration at rocket.chat:
![image](https://cloud.githubusercontent.com/assets/8591547/12064203/175bc348-afa4-11e5-8a99-50c62fdc48f7.png)

are you on our demo server? we can talk there

**Comment by felixwidjaja** [comment]
Woops sorry. Here's the new test url http://requestb.in/1a90v3t1?inspect
Where should I paste the curl to test?
I'll contact you in the demo chat.

**Comment by felixwidjaja** [comment]
The solution was to delete the incoming web hook and create again. The bot field changed to rocket.cat.
Solved.
