### ISSUE TITLE
Users can't pin Direct Messages

### ISSUE THREAD

**Issue by sandrotanner** [RocketChat/Rocket.Chat#17871]
Normal users cannot use pinning in direct messages. Giving them the "pin-message" permission allows them to pin in channels too (which is normally not wanted). -> There seems to be no way to allow users to pin Direct Messages but not any Channel Message.

Admins are able to pin messages in direct messages (they have said "pin-message" permission).

### Steps to reproduce:

1. Write a direct message as a non-admin user
2. try to pin it

### Expected behavior:

The context menu option for pinning the message is there. The message gets pinned like normally in a channel.

OR

There is a special permission like "pin-direct-message" which decides whether a user can pin direct messages.

### Actual behavior:

The user cant pin any message (the option to do so does not show up). However the global administrator can do so in any direct messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Tested on MacOS and Linux
- Deployment Method: docker

### Client Setup Information

Desktop app v 2.17.9 on macOS and 2.17.7 on Ubuntu
Web App on Firefox 77.0.1 on macOS and Linux.

### Additional context

- https://docs.rocket.chat/guides/developer-guides/realtime-api/method-calls/pin-message
- https://docs.rocket.chat/guides/administrator-guides/permissions

Seems like this case was not considered and the behavior (admin being able to pin in in DMs but not users) is unintentional.

Any information if this is the case or if I am overseeing an option are greatly appreciated. 
Thanks :)

---
`*edit: moving something to the correct heading`

**Comment by sandrotanner** [comment]
> #16758

@zdumitru 

Thanks but that is not my issue. 
My issue is, that I can't permit users to pin direct messages without them being able to pin messages in _any_ channels they are in (which obviously isn't desired in almost any case).

**Comment by aKn1ghtOut** [comment]
@ggazzo what would be the best approach? The few options appear to be 
1. To have a site-wide setting to enable/disable pin messages in direct messages.
2. Have a separate permission for "pin message in direct messages"
3. Enable pinning in direct messages by default for all

I'm mostly on board with **3** as this seems like a feature that should be always included.

**Comment by dudanogueira** [comment]
Hi!
This feature is already present on latest version (tested in 5.2-develop).
Thanks for your contribution!

**Comment by sandrotanner** [comment]
cool thanks
