### ISSUE TITLE
API - Add / Remove User

### ISSUE THREAD

**Issue by zbmowrey** [RocketChat/Rocket.Chat#1788]
I'd like the ability to add, modify, or remove users using the REST API. Is this something on the road map?

**Comment by gkarmas** [comment]
Anyone? Still?

**Comment by jmls** [comment]
https://rocket.chat/docs/developer-guides/rest-api/

there seems to be an add/update but not delete ...

**Comment by jmls** [comment]
according to this https://github.com/RocketChat/Rocket.Chat/pull/3525 there is a delete user api call

**Comment by graywolf336** [comment]
This has been added and the documentation is updated, [create](https://rocket.chat/docs/developer-guides/rest-api/users/create) and [delete](https://rocket.chat/docs/developer-guides/rest-api/users/delete).
