### ISSUE TITLE
2.4.11 and 2.4.12 can't buid,it seems that it miss something important

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#17880]
![image](https://user-images.githubusercontent.com/12368358/84369259-27c31180-ac09-11ea-9eb8-f8712864686c.png)

we download two versions package from 
https://github.com/RocketChat/Rocket.Chat/releases

and then we use 
meteor npm install

we meet this bug:
 
![image](https://user-images.githubusercontent.com/12368358/84371919-f5b3ae80-ac0c-11ea-88e9-41eec11b4c5e.png)

when use:
 npm install
![image](https://user-images.githubusercontent.com/12368358/84372648-fef14b00-ac0d-11ea-86e4-da3ea8a4464c.png)

**Comment by geekgonecrazy** [comment]
Doesn’t appear to still be an issue on latest releases.  I just did fresh install on my Ubuntu laptop and didn’t get this issue.  

For sure make sure to use meteor npm install and not just npm install.  So forces the right version of node
