### ISSUE TITLE
Message Snippeting doesn`t work

### ISSUE THREAD

**Issue by arascheuski** [RocketChat/Rocket.Chat#17883]
**Application details:**
Version | 3.2.2 (docker version)
**Steps to reproduce:** 
1.  Go Settings -> Message
2. Turn on "Allow Message Snippeting"

**Expected result:** watch extra button somewhere  in chat UI
**Current behavior:** no button appear in chat UI
**Workaround:** don`t know

**Comment by EnCz** [comment]
Duplicate -> https://github.com/RocketChat/Rocket.Chat/issues/15101
