### ISSUE TITLE
Can't edit user profile in v3.3.0 or v3.3.3

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat#17894]
### Description:
When trying to edit a user profile, now I see a classic pagination in the user list, instead of the lazy loading approach of v3.2.2. The fact is that when I select a user and click the edit button, a blank page is displayed. 

### Steps to reproduce:
1. RocketChat v3.3.3, as admin user, go to Administration > users
2. in the list of users (with classic pagination), select a user
3. click edit and the blank page is displayed due to javascript error

### Expected behavior:
Same as v3.2.2, user list with lazy loading approach (instead of classic pagination) and when I click the edit button the user profile is in edit mode in the right sidebar.

### Actual behavior:
Blank page

### Server Setup Information:

- Version of Rocket.Chat Server: v3.3.3 (in v.3.3.0 also this happens) 
- Operating System: Ubuntu 18
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog:  yes
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: MACOS

### Relevant logs:

This is the error in console:
![image](https://user-images.githubusercontent.com/35463401/84533362-46e4a080-ace8-11ea-8346-d6e879b04c71.png)

In network, this request: 
https://myrocketdomain.com/api/v1/users.info?userId=xy7ZpM5cWxfTTJiGP

gives this JSON response:
`{"user":{"_id":"xy7ZpM5cWxfTTJiGP","createdAt":"2020-05-05T10:59:23.256Z","services":{},"username":"myusername","emails":[{"address":"name@domain.com","verified":true}],"type":"user","status":"offline","active":true,"roles":["guest"],"name":" surname name","lastLogin":"2020-06-11T09:38:29.779Z","statusConnection":"offline","utcOffset":2},"success":true}
`

**Comment by Venomen** [comment]
Same here, at 3.3.3 debian9. Can't use it in any browser/mobile app. This is kinda serious bug ;)

**Comment by ggazzo** [comment]
@didacroyo sorry about that, we gonna fix asap, are you using custom fields? I think there's something wrong on your son definition

**Comment by Venomen** [comment]
> @didacroyo sorry about that, we gonna fix asap, are you using custom fields? I think there's something wrong on your son definition

How we can trace that? While rocketchat is starting I can see this error:
`Invalid Custom Fields SyntaxError: Unexpected token , in JSON at position 37
    at JSON.parse (<anonymous>)
    at app/api/server/api.js:682:29
    at app/settings/lib/settings.ts:81:37
    at Array.forEach (<anonymous>)
    at app/settings/lib/settings.ts:81:15
    at Array.forEach (<anonymous>)
    at Settings.load (app/settings/lib/settings.ts:78:14)
    at Object.added (app/settings/server/functions/settings.ts:335:17)
    at _CachingChangeObserver.added (packages/minimongo/local_collection.js:1307:28)
    at added (packages/minimongo/local_collection.js:709:29)
    at runWithEnvironment (packages/meteor.js:1286:24)
    at packages/meteor.js:1299:14
    at packages/mongo/observe_multiplex.js:204:9
    at _IdMap.forEach (packages/id-map/id-map.js:51:35)
    at ObserveMultiplexer._sendAdds (packages/mongo/observe_multiplex.js:196:22)
    at packages/mongo/observe_multiplex.js:50:12`

but where/how I can find this?

**Comment by didacroyo** [comment]
Thanks ggazzo!

I removed this customfields configuration and the issue disappeared! 

(Administration > Accounts > Registration > Custom Fields) 

```
{
 "departamento": {
  "type": "text",
  "required": true,
  "minLength": 2,
  "maxLength": 10
 }
}
```

**Comment by Venomen** [comment]
> Thanks ggazzo!
> 
> I removed this customfields configuration and the issue disappeared!
> 
> (Administration > Accounts > Registration > Custom Fields)
> 
> ```
> {
>  "departamento": {
>   "type": "text",
>   "required": true,
>   "minLength": 2,
>   "maxLength": 10
>  }
> }
> ```

Confirmed, now it's working fine

**Comment by didacroyo** [comment]
I don't need any customfield right now, so at this point of time I can close this issue. Thanks
