### ISSUE TITLE
Integrate the PhotoDNA CSAM-scanning API to flag and block child abuse images

### ISSUE THREAD

**Issue by qirtaiba** [RocketChat/Rocket.Chat#17897]
I would like to have a plugin that checks uploaded images against a database of CSEM (child pornography) hashes using Microsoft's PhotoDNA API. This would involve creating a hash of the uploaded image (I already have a Java or C# library to do this) and sending it to Microsoft's web service (which I also have ready) for comparison. If it reports a match, the upload should be quarantined and a log created for the administrator. I plan to post this issue on [bountysource.com](https://bountysource.com) with a bounty.

**Comment by OliverViking** [comment]
Documentation for Microsoft's PhotoDNA is available here: https://developer.microsoftmoderator.com/docs/services/57c7426e2703740ec4c9f4c3/operations/57c7426f27037407c8cc69e6/console?ref=mktg

**Comment by brymut** [comment]
Hi, I would like to have a go at this. Is it available for anyone to tackle?

**Comment by qirtaiba** [comment]
Yes! Thanks @brymut, let's talk more about what's involved. We're connected on keybase now.

**Comment by col-panic** [comment]
I started analysing the problem today, and would require the following feedback

* Do you require a native integration of the feature in rocketchat, or are you okay with an installable app in the beginning? (An app could extend the functionality to already existing installations without requiring a system update, also it has a much shorter time-to-market as one is not bound to the formal rocketchat release cycle)
* What do you mean by _quarantining an image_? Should it be instantly deleted or replaced with a mockup image (or should it be configurable what happens to the image)?

thanks
* Could you provide a link to the code that creates the hash of the uploaded image?

**Comment by qirtaiba** [comment]
Hi @col-panic. If you and @brymut both want to work on this then I'm not sure how splitting the bounty would work, but for now let me just answer your questions:

1. I was assuming it would be a plugin that could use the Rocketchat web interface so that the administrators (who are non-technical) have a way to enable scanning per forum (eg. they may want to limit the scanning to certain channels, especially during rollout when it will be enabled for testing only). 
2. It shouldn't be deleted, it needs to be moved so it won't be visible, but where it can be preserved for law enforcement. This is a legal requirement.
3. Yes, I've created a repository where I'll drop the files and I've invited you to join.
4. No need, we are already registered with the PhotoDNA system and I will share the API login details privately when needed.

**Comment by brymut** [comment]
Hi @qirtaiba @col-panic, I think it'll work best if one of us works on it for a certain set period in exchange for the bounty. Just to give some fair time to work on it without having any overlap of work.

I'm in favour of @col-panic having a go at it for a certain period, say 3 weeks for something of this scope, since I'm the one suggesting the 'one-at-a-time' window of work and it looks like they have more experience working with Rocketchat as a contributor. Then after I could give it a shot if there isn't a solution yet.

**Comment by col-panic** [comment]
Available as App in https://github.com/prostasia/rocketchatcsam
