### ISSUE TITLE
Add user to room

### ISSUE THREAD

**Issue by jscruz** [RocketChat/Rocket.Chat#179]
When I created a new room, I clicked on the right corner to display the room options. Then, rocket found the user successfully but I can not add it to the channel. This has been tested in the following browsers:
- Google Chrome Version 43.0.2357.124 m
- Internet Explorer 11.0.9600.17801
- Mozilla Firefox 37.0.2

**Comment by Wloa** [comment]
I also like to add, when create a new room/channel and "Add Member" during add new channel. Rocket did not notify other user and not shown in the other user channels list as well so other user did not know that he/she is invited to a channel.
