### ISSUE TITLE
Add the ability to send Livechat offline messages to a channel [NOT WORKING]

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat#17902]
### Description:

According to this: https://github.com/RocketChat/Rocket.Chat/pull/17442
and to this: https://github.com/RocketChat/Rocket.Chat/releases/tag/3.3.0

The feature "Add the ability to send Livechat offline messages to a channel" is available. And it is, but it is not working as expected. Not all the private groups are available in the list (search results). 

When a private group is specified it is seems it is not saved (because it is not there the next time you open the configuration and because the expected behavior doesn't accour)

### Steps to reproduce:

1. Go to Omnichannel configuration
2. Select a department
3. Search the private group to forward the incoming messages when all agents are offline.
4. Not all private groups are available (issue1)
5. The selected private group is not saved after clicking the save button (issue2)

### Expected behavior:

1. All the private groups are available for the message forwarding.
2. After clicking the save button and closing the Omnichannel configuration the configuration is saved.
3. The exepected behaviour of this feature is the following: 
When a new incoming Omnichannel message, if all agents of the department are offline, the incoming message is forwarded to the configured private group, so that the agents which are also members of the group are notified in the mobile app! and can see the message, then can somehow start chatting  with the "livechat-guest" from the mobile app. In case this is not possible, the agens can go to a workstation to continue with the conversation.. 

### Actual behavior:

Not all groups are available for the message forwarding.
The selected group is not saved.

### Server Setup Information:

- Version of Rocket.Chat Server:  v3.3.0 and v3.3.3
- Operating System: Ubuntu 18
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog:  enabled
- NodeJS Version:  v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: MacOS

### Additional context

![image](https://user-images.githubusercontent.com/35463401/84564975-3246ed80-ad66-11ea-9a7d-ed171f9d2f78.png)

**Comment by renatobecker** [comment]
Hi @didacroyo 
I just can't reproduce this issue, I tried many ways to reproduce it but I couldn't, the feature is working fine.

Can you, please, share a video recording of your environment during your test?
Also, can you share the data sent through the Web Socket after you click to save the `Department` data?

I'll be waiting for your feedback.
Thanks.

**Comment by didacroyo** [comment]
Hi Renato, thanks for your prompt answer. 

The search results is always showing a few channels only, regardless the search string, the search results are always the same in my case (some matching results are not listed and some non-matching results are listed).

Now I can save the selected channnel! (not the one I want, but it's ok, since I want to see the feature working somehow). But the feature is now working as expeted. When all agents are offline I exect the incoming livechat message to be forwared to the configured channel, but this is not hapening.  In the section Administration>Omnichannel I've tried switching on/off, but nothing happens...

The routing configuration should be configured in a particular way? 

this is how I have the routing configured..

![image](https://user-images.githubusercontent.com/35463401/84752554-2e150d00-afbe-11ea-8887-19aae3528392.png)

**Comment by didacroyo** [comment]
Hi, I have more information. The target group is not being displayed in the search results, BECAUSE the listed groups (search results) are always the same 10 groups, alphabetically ordered (ASC-ending), and irrespective of the "search string".

**Comment by didacroyo** [comment]
More information. I renamed the target group, from test_s4 to A_test_s4 (because I see capital letters have priority in the ASC order to ensure the group will appear in the elegible list). 
Now I can select this group (A_test_s4) and I can save changes. The error I see now, when editing again the target department is the follwing. It seems is related with the capital letter A, not matching the value stored. 

![image](https://user-images.githubusercontent.com/35463401/85001507-0ce62500-b154-11ea-95c9-49145bc4fd1e.png)

**Comment by didacroyo** [comment]
So, to sum up, 3 issues:

1. elegible groups always the same 10, ordered alphabetically

2. the previous error (error: "The required "roomId" or "roomName" param provided does not match any channel [error-room-not-found]")

3. expected behaviour not occurring, when I receive a new liveChat message to the target department (with no online agents) I don't see the incoming message in the target group

**Comment by renatobecker** [comment]
Duplicated #17914
