### ISSUE TITLE
Trending channels indicator for busy chat server

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1791]
On a busy chat server with thousands of public channels, it is impossible for users to find and join currently trending discussions.

Keep an updated  _recent post count indicator_ (say, for the last 30 minutes) with each channel.   Allow color-code on the channel label (Red=hot, orange=trending, and so on), or a new `setting` to dynamically sort by count-indicator -- to assist users in locating active public channels to join.

**Comment by MartinSchoeler** [comment]
I belive that our `discover channel` upcoming feature will resolve this issue, closing this.
