### ISSUE TITLE
Bug SAML login/logout

### ISSUE THREAD

**Issue by Guile17** [RocketChat/Rocket.Chat#17919]
@pierre-lehnen-rc
The first image is the error event that appears on my ADFS. The second one is the request from RC.
I have no idea what the NameQualifier value is on the error.

![image](https://user-images.githubusercontent.com/58185841/84677755-2ccfdb80-aefd-11ea-96bb-d26285c41260.png)
![image](https://user-images.githubusercontent.com/58185841/84677770-30636280-aefd-11ea-825b-0127df3d4d10.png)

**Comment by pierre-lehnen-rc** [comment]
Previous discussion on: #17319

**Comment by pierre-lehnen-rc** [comment]
Can you try again on version 3.4 once it's out? Even if that version doesn't fix the problem by itself, the new settings it includes will let us modify the login request to include any extra data it needs.

**Comment by Guile17** [comment]
As soon as I see it released, I'll test it and let you know.
Thank you.

**Comment by Guile17** [comment]
Hi @pierre-lehnen-rc 
I updated to 3.4.0 and played with the logout request, but still not working.
I removed NameQualifier and SPNameQualifier from the logout request, and I got success on the response, but when the page refreshes, I'm still logged in.

Here is the Request:
![image](https://user-images.githubusercontent.com/58185841/86380950-b94aff80-bc5a-11ea-9890-7a04d4b7c8b3.png)

Here is the Response:
![image](https://user-images.githubusercontent.com/58185841/86381012-cd8efc80-bc5a-11ea-8db8-355f973707d7.png)

Any ideas about what could be?

**Comment by Guile17** [comment]
@pierre-lehnen-rc
I've noticed that the first time that I try to do the logout it says Successful, but the second time I get the Requester message (samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester").
I even tried to trace the debug logs on the ADFS side, but there is nothing there.

**Comment by JohnPetr2** [comment]
@pierre-lehnen-rc Did you figure that out? I'm having the same problem.

**Comment by pierre-lehnen-rc** [comment]
I'm working on something else now but I'll take another look at this later this week.

**Comment by JohnPetr2** [comment]
Thank you.

**Comment by Guile17** [comment]
Hi @pierre-lehnen-rc did you have a chance to take a look into it?
sorry to bother again.

**Comment by pierre-lehnen-rc** [comment]
Hi @Guile17 , can you also share an authn request and response with the matching logout request and response?

I did some googling on this specific problem and found this thread that may have been a similar issue:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/dba7dabe-8797-429c-8d5b-6c830705ad82/error-8211-saml-single-logout-request-does-not-correspond-to-the-loggedin-session-participant?forum=Geneva

**Comment by Guile17** [comment]
Second time doing the logout.

Logout Request:
![image](https://user-images.githubusercontent.com/58185841/87826632-3bd0e300-c847-11ea-99ac-b87f57fd82f3.png)


Logout Response:
![image](https://user-images.githubusercontent.com/58185841/87826736-6a4ebe00-c847-11ea-8681-10ff9e9e7a03.png)

**Comment by pierre-lehnen-rc** [comment]
The first logout request returns success but doesn't disconnect the user?

**Comment by Guile17** [comment]
No, If I refresh the page the user still logged in.

**Comment by pierre-lehnen-rc** [comment]
Can you enable the SAML debug logs on Rocket.Chat and send me that as well (for the first logout response).

**Comment by Guile17** [comment]
It's enabled, but on the view logs tab, I don't see anything.

**Comment by pierre-lehnen-rc** [comment]
It doesn't show anything only for the Logout Response or anything related to SAML?

**Comment by Guile17** [comment]
Anything for the Logout Response.

**Comment by pierre-lehnen-rc** [comment]
Wild guess, but do you have any other service connected to the same SAML server? If you have something that doesn't support Single Logout, it may break the whole logout flow.

**Comment by Guile17** [comment]
No, this SAML is specific to RC.

**Comment by pierre-lehnen-rc** [comment]
So it is probably sending the LogoutResponse to the wrong URL. Is there any way to check on the logs what URL it is sending it to?

**Comment by Guile17** [comment]
If that was the case, I wouldn't be able to login as well.
Also, the fact that RC is getting Success as response, seems like it not killing the session, doesn't it?

**Comment by pierre-lehnen-rc** [comment]
Login response should go to `/_saml/validate/` and logout response should go to `/_saml/logout/`
It was my understanding that the ADFS was sending a success response and that Rocket.Chat didn't receive it, as you said that nothing showed up on the logs on our side.

**Comment by Guile17** [comment]
I see, in this case the RC is using the wrong URL to do the request. Correct if I'm wrong.
But as I can see, it's using https://rc.../_saml/metadata/adfs

<samlp:LogoutRequest Destination="https://auth.../adfs/ls/"
    ID="_id-14fdb6e86f0e72cc0cfa" IssueInstant="2020-07-20T19:53:16.972Z" Version="2.0"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <**saml:Issuer** xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://rc.../_saml/metadata/adfs</**saml:Issuer**>
    <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">g...@...</saml:NameID>
    <samlp:SessionIndex xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">_9c11d630-7bc4-41ca-a1e0-431f511c6050</samlp:SessionIndex>
</samlp:LogoutRequest>

**Comment by pierre-lehnen-rc** [comment]
When you access that `/metadata/adfs` url, it should display a xml with a `SingleLogoutService` tag linking to `/_saml/logout`

**Comment by Guile17** [comment]
Yes, it's there.

**Comment by pierre-lehnen-rc** [comment]
If you enable the SAML logs on Rocket.Chat, every request we get on `/_saml/` will be logged as an object with an `actionName` attribute. Can you check again if at least that object is logged when the ADFS sends the logout response?

For the full workflow, there should be 4 objects like that.
```
{ actionName: 'authorize', serviceName: 'adfs' ... } 
{ actionName: 'validate', serviceName: 'adfs' ... }
{ actionName: 'sloRedirect', serviceName: 'adfs' ... }
{ actionName: 'logout', serviceName: 'adfs' .... }
```
But there will also be several other logs between those.

**Comment by Guile17** [comment]
This is what I'm seeing on logout action:
`server.js:204 steffo:meteor-accounts-saml ➔ info {   actionName: 'logout',   serviceName: undefined,   credentialToken: undefined } `

**Comment by pierre-lehnen-rc** [comment]
So the request is going to `/_saml/logout` instead of `/_saml/logout/adfs`
Did the Logout URL on the metadata xml include the `adfs` part at the end?

**Comment by Guile17** [comment]
This is the metadata content, if that what you are asking.

<?xml version="1.0"?>
<EntityDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:SAML:2.0:metadata https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd" xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="https://rc..../_saml/metadata/adfs">
  <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">    <KeyDescriptor>
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509Certificate>...</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
      <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
      <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
      <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"/>
    </KeyDescriptor>
    <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://rc..../_saml/logout/adfs/" ResponseLocation="https://rc..../_saml/logout/adfs/"/>
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService index="1" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://rc.../_saml/validate/adfs"/>
  </SPSSODescriptor>
</EntityDescriptor>

**Comment by Guile17** [comment]
@pierre-lehnen-rc  I just tested again the whole process, and I didn't see the logout action.
The request and response are there, but not the action.
Do you have any idea why?

**Comment by Guile17** [comment]
@pierre-lehnen-rc Here is the [ADFS Log](https://github.com/RocketChat/Rocket.Chat/files/4957197/ADFS.Log.txt) from RC since the logon until logout. Please help.


I found this link also https://stackoverflow.com/questions/51131106/adfs-cookies-not-getting-clear-after-successful-logout

**Comment by pierre-lehnen-rc** [comment]
So the only thing we can be sure at this point is that the logout response is not reaching the right url (`/_saml/logout/adfs`), but I don't know if there's any setting on adfs that can change this or if it's a problem with the request/metadata we send.

**Comment by Guile17** [comment]
I've changed the logout URL on ADFS to post it to `/_saml/logout/adfs ` and now I'm getting the following error.

`I20200722-13:27:18.056(-4) server.js:204 steffo:meteor-accounts-saml ➔ error Invalid LogoutResponse, missing SAMLResponse {} 
I20200722-13:27:18.056(-4) Error: Invalid LogoutResponse received.     at Function.processLogoutResponse (app/meteor-accounts-saml/server/lib/SAML.ts:309:10)     at Function.processLogoutAction (app/meteor-accounts-saml/server/lib/SAML.ts:225:15)     at Function.processRequest (app/meteor-accounts-saml/server/lib/SAML.ts:45:17)     at middleware (app/meteor-accounts-saml/server/listener.ts:61:8)     at app/meteor-accounts-saml/server/listener.ts:79:3`

Here is my SAML Logout configuration.

![image](https://user-images.githubusercontent.com/58185841/88208609-7d82d480-cc1f-11ea-8c82-1520d510375f.png)

**Comment by Guile17** [comment]
Also, here is the SAML request and response.

Request
![Request](https://user-images.githubusercontent.com/58185841/88210089-9db39300-cc21-11ea-8b31-5e3750571c66.png)

Response
![Response](https://user-images.githubusercontent.com/58185841/88209967-70ff7b80-cc21-11ea-98ad-04e26a86301e.png)

**Comment by pierre-lehnen-rc** [comment]
What are the options available in the "Binding" setting in that screenshot?

**Comment by Guile17** [comment]
Post and Redirect.

**Comment by pierre-lehnen-rc** [comment]
Do you get the same error with Redirecŧ?

**Comment by Guile17** [comment]
Let me try.

**Comment by Guile17** [comment]
No, it worked. Thank you @pierre-lehnen-rc for your time and patience :). 

Below is the proper way of doing it using ADFS and Rocket Chat SAML.

- You need to create your Logout Endpoint as per the image below
![image](https://user-images.githubusercontent.com/58185841/88212118-b96c6880-cc24-11ea-9f5c-22194a2e9ddd.png)

- The Logout Template Request needs to be as below, without  NameQualifier and SPNameQualifier.

`<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="__inResponseToId__" Version="2.0" IssueInstant="__instant__" Destination="__idpSLORedirectURL__">
  <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">__issuer__</saml:Issuer>
  <samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>
</samlp:LogoutResponse>`

**Comment by pierre-lehnen-rc** [comment]
Glad it worked! 
Not sure why ADFS didn't load the endpoint data from the metadata automatically, but now we know how to configure it manually, so thank you for sharing the result!
In normal circumstances this shouldn't be needed, but if anyone runs into this same issue again in the future I'll point them here.
