### ISSUE TITLE
rocket.chat 2.4.* we want to  commit code,but we can't build ,what's  the meter's version?

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#17915]
rocket.chat 2.4.* we want to commit code,but we can't build ,what's  the meter's version we should  use?

**Comment by geekgonecrazy** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/release

https://github.com/RocketChat/Rocket.Chat/blob/2.4.12/.meteor/release
