### ISSUE TITLE
Add the ability to send Livechat offline messages to email (department) [NOT WORKING]

### ISSUE THREAD

**Issue by tboulogne** [RocketChat/Rocket.Chat#17914]
### Description:
The feature the ability to send Livechat offline messages to an email is available in department setting. And it is, but it is not working as expected. 
### Steps to reproduce:

1. Omnichannel, add a department and fill and address
2. From offline live chat,  send a message

### Expected behavior:
Message sent to address into department settings.

### Actual behavior:
Nothing append.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System:  linux x64 4.15.0-106-generic
- Deployment Method: manuel
- Number of Running Instances: 1
- DB Replicaset Oplog: Activé
- NodeJS Version: v12.18.0
- MongoDB Version: 4.0.19

### Client Setup Information
Browser

Thanks for help.

Regards, 

Thierry

**Comment by renatobecker** [comment]
Hi @tboulogne, thanks for reporting this issue.
I'll need your help to look into it, can you please share a print screen of the department form you're expecting the offline messages?

I need to check how your department is configured.

Thanks.

**Comment by tboulogne** [comment]
Hello @renatobecker ,

Thanks for your reply.

Hope it could help.

![form](https://user-images.githubusercontent.com/6205275/84675401-7be13500-af2c-11ea-8cdd-3b2588c74592.png)


regards

**Comment by renatobecker** [comment]
Duplicated #17902

**Comment by renatobecker** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/17970.

**Comment by didacroyo** [comment]
Hi @renatobecker!

Is this issue still open or fixed and released in the 3.4.0 ?

Thanks

**Comment by tboulogne** [comment]
@didacroyo sadly, i see this switch to 3.5.0. Perhasp @renatobecker will help us to fix it in 3.4.0

**Comment by tboulogne** [comment]
hello @renatobecker, 
This still not working. Could us expect a fix about this please ? (as you removed it from 3.5.0)

Regards

**Comment by itsarectangle** [comment]
> 
> 
> Hi @renatobecker!
> 
> Is this issue still open or fixed and released in the 3.4.0 ?
> 
> Thanks

hi there, did this ever get fixed?  Why was this closed and the last message ignored?  I'm having the same issue.

**Comment by renatobecker** [comment]
> > Hi @renatobecker!
> > Is this issue still open or fixed and released in the 3.4.0 ?
> > Thanks
> 
> hi there, did this ever get fixed? Why was this closed and the last message ignored? I'm having the same issue.

What is your server version?

**Comment by itsarectangle** [comment]
> 
> 
> > > Hi @renatobecker!
> > > Is this issue still open or fixed and released in the 3.4.0 ?
> > > Thanks
> > 
> > 
> > hi there, did this ever get fixed? Why was this closed and the last message ignored? I'm having the same issue.
> 
> What is your server version?

3.12.1
