### ISSUE TITLE
live chat not being edited custom fields

### ISSUE THREAD

**Issue by farzadha2** [RocketChat/Rocket.Chat#17922]
### Description:
Currently trying to change the chat field for the customer to put in 
Name
Email
Phone number
and the color

### Steps to reproduce:
Went to the config of live chat  appearance 

![image](https://user-images.githubusercontent.com/62571297/84707036-9cf15800-af23-11ea-88dc-c79c53303bc6.png)

but its appearing this 

![image](https://user-images.githubusercontent.com/62571297/84707093-b2668200-af23-11ea-85dc-4894fd5ef304.png)

I have checked the https://github.com/RocketChat/Rocket.Chat.Livechat/pull/407

and it seems that it should work but not sure if im not looking correctly 
![image](https://user-images.githubusercontent.com/62571297/84707242-fbb6d180-af23-11ea-9a23-cc747b65c667.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: 18.08 LTS
- Deployment Method:  TAR
- Number of Running Instances: 1

Thank you

**Comment by renatobecker** [comment]
Hi @farzadha2 

Did you get any error on your browser console? You probably need to enable CORS on the admin panel.

Regarding the `custom fields`,  as you can see on the [issue title](https://github.com/RocketChat/Rocket.Chat/pull/17581) it's an `Enterprise` feature, so you'll need to get an `Enterprise` license to be able to use it.

Thanks.

**Comment by farzadha2** [comment]
Thanks for the reply, as for the error i have not gotten any, i also did see the live chat api modification? 

Yes the CORS is enabled

![image](https://user-images.githubusercontent.com/62571297/84711432-f78eb200-af2b-11ea-993a-d7653c74fb81.png)


So what i need would not be possible without the enterprise? 
to add the phone number name and stuff like that?

Thank you

**Comment by renatobecker** [comment]
Is the registration form enabled? Have you tried on an anonymous page, also?

As I explained before, the ability to add custom fields on the Livechat registration form is an Enterprise feature, so it's not available on the `Community` version, you need to get a license if you want to use the Enterprise features.

Thanks.

**Comment by farzadha2** [comment]
Thank you

**Comment by homberger** [comment]
So this is the end of Rocket.Chat that we loved so much. This is really sad.
