### ISSUE TITLE
Hierarchical "Members List"

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#1792]
I wanted to suggest something I had been thinking about for awhile now: making the members list hierarchical, not quite unlike the way IRC handles it — where opers are on top of the list in the client and the rest of the users build up below.

This is just a suggestion I wanted to write down in the event I forgot about it :)

**Comment by 9203948** [comment]
+1 - Great idea!

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
