### ISSUE TITLE
Can't direct message

### ISSUE THREAD

**Issue by idominiki** [RocketChat/Rocket.Chat#17928]
### Description:

Can't direct message between users.

### Steps to reproduce:
With klick on "new" I can't select direct message

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System:  Univention Corporate Server
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.3

### Client Setup Information

- Desktop App or Browser Version: Browser Safari
- Operating System: macOS 10.15.5
<img width="309" alt="Bildschirmfoto 2020-06-16 um 16 03 33" src="https://user-images.githubusercontent.com/62521486/84784742-f53f5d00-afea-11ea-80d9-c25b8f76c92d.png">

**Comment by ggazzo** [comment]
there is no such feature(I mean there is DMs, but not the button you are looking for)  on 3.0.x versions, use (cmd + p) or (cmd + k) to search OR use the directory feature.. or update your server to >3.2

![image](https://user-images.githubusercontent.com/5263975/84978537-8e619700-b103-11ea-9e46-2260d06678ef.png)

**Comment by idominiki** [comment]
Understand thanks! 
I uncheck the right "view-outside-room" for our users to . So the users can't see all users in the directory. How can they see users from groups they're in? 

Question for v.3.2. When comes this version to UCS AppCenter?
