### ISSUE TITLE
App uninstalls/disables etc not working

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat#17932]
### Description:
On the installed apps package an app is not getting uninstalled.

### Steps to reproduce:

1. Apps section as admin
2. Uninstall an app
3. No uninstall happening

### Actual behavior:
![out](https://user-images.githubusercontent.com/43509699/84845355-12674080-b06a-11ea-8cf2-07efb42b8627.gif)

### Server Setup Information:
![image](https://user-images.githubusercontent.com/43509699/84845390-2ad75b00-b06a-11ea-8e4e-b38823db01e8.png)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by murtaza98** [comment]
I'm facing this issue as well. Is there a workaround until there is a fix?

**Comment by ritwizsinha** [comment]
It has been fixed in the latest version

**Comment by ritwizsinha** [comment]
@murtaza98 for any reason if it is still not working you could simply set the boolean variable in the confirmation modal for this page to true

**Comment by murtaza98** [comment]
> It has been fixed in the latest version

Are u referring to the latest version of `develop` branch?

**Comment by murtaza98** [comment]
I updated my server to the latest commit on the `develop` branch and it solved this issue. Thanks :v:
