### ISSUE TITLE
[Request] Thumbnail for images

### ISSUE THREAD

**Issue by BugsBunnyBR** [RocketChat/Rocket.Chat#1794]
Hi, I would like to have an option to specify in the url of an image the size in pixels of it.
Something like:

/ufs/rocketchat_uploads/upl-file145139724827639/runner-stretching.jpg?**w=200&h=150**

or just

/ufs/rocketchat_uploads/upl-file145139724827639/runner-stretching.jpg?**w=200**
and it would keep the aspect ratio of the image.

It would help mobile versions of Rocket Chat to reduce network bandwidth.

**Comment by Sing-Li** [comment]
This will:
* increase load on server (how often will this be called - it will fork and start imagemagik for each call)
* increase the latency of request

Need to balance the tradeoffs.

Are they fixed size versions of certain assets? If so, we should consider generating them at source ...similar to how Android and iOS handle the problem.

**Comment by BugsBunnyBR** [comment]
How about work with buckets and use caches? 
Android has 5 primary densities for images and RC could use something similar.
Suppose RC buckets are defined as
mdpi 360px
hdpi 480px
xhdpi 720px
xxhdpi 1080px
xxxhdpi  1440px

So the server chooses what image to return.
Example: client requests w=400, the hdpi could be used.
If the original file has 800px width and the client requests a w=1200, return the original image with no scaling.

PS: the values I presented are just a "good guess".

**Comment by lvh1** [comment]
IMO if you cache the thumbnails, they should be cleaned up after a certain amount of time (e.g. a month) so images that will likely never be shown again don't take up disk space.

**Comment by nikashitsa** [comment]
I think one thumbnail for message attachment is enough to reduce network bandwidth.
With aws s3 + lambda thumbnails can be created in cloud. Here are [examples of lambda functions](https://github.com/nikashitsa/aws-lambda-thumb).
Official s3 thumbnails [tutorial](http://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html) 

But there is issue with Invocation Types. If use Event invocation type, thumbnail is generated asynchronous and client doesn't know when thumbnail is ready (so onerror callback trick has place). If use RequestResponse invocation type, thumbnail can be generated synchronous but a) user should wait for function callback, b) current peerlibrary:aws-sdk@2.0.17_2 doesn't have AWS.Lambda() method to invoke lambda function. Need to decide which way is better.

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap so we will revisit once other priorities have been addressed.

**Comment by geekgonecrazy** [comment]
I believe this is also possible with 0.62.0
