### ISSUE TITLE
[Bug] Thread with unreachable link created not correctly

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17945]
### Description:

Thread with unreachable link creates not correctly

### Steps to reproduce:

1. Create private chat
2. Make thread answer with URL (e.g. https://yyy.qqq.rrr) 
3. Thread not fully created - no blue button with amount of answers
4. Make plain text answer to thread - it created correctly

### Expected behavior:

Thread should create despite of URL and other text content

### Actual behavior:

My server version 3.1.1
![thread-link2](https://user-images.githubusercontent.com/4023037/85008555-cdc0cf80-b165-11ea-8995-12e7e0ab1dd6.gif)

open.rocket.chat version 3.4.0 with completely rewrited threads system 
![thread-link](https://user-images.githubusercontent.com/4023037/85008537-c8fc1b80-b165-11ea-9d8e-96269a2edbe6.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOC7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome 83
- Operating System: Windows 10

**Comment by ggazzo** [comment]
nice catch! actually the problem is related with `callbacks.run` there are a lot of potencial places that will be "pending" waiting for the previous step...

~btw: we didnt rewrite completely threads :x more frontend stuff~
