### ISSUE TITLE
error in department empty - create room

### ISSUE THREAD

**Issue by arsevys** [RocketChat/Rocket.Chat#17943]
I use the rocketchat api to create a room setting the visitor's token as a parameter, but sometimes when the salt is created, it returns me without department, why is it, does it have to do with the visitor? I currently only have 1 department ..

![image](https://user-images.githubusercontent.com/22304618/84972628-e63cd580-b0e4-11ea-8876-7460e47f9586.png)

Other example

![image](https://user-images.githubusercontent.com/22304618/84972819-4c295d00-b0e5-11ea-9e00-55e793f7edf6.png)

**Comment by renatobecker** [comment]
@arsevys can you please share here an example of the payload requests you're sending to the server?

**Comment by arsevys** [comment]
Onlys is  GET https://XXXXXX.rocket.chat/api/v1/livechat/room?token=XXXXXXXXX
Steps :
- Create Visitor(I generate a token with uuid)
- Create Room with the token visitor 

currently i have an instance  PRO of in rocketchat in rocketchat cloud and in a project we have filed complaints about the problem that the department does not appear
-------------------------------------
other quesion ?
Is there a possibility that I can close a room as an agent, through an api rest?

**Comment by renatobecker** [comment]
@arsevys Did you set the `department` field before registering the visitor?
It's an optional field, but when a new omnichannel room is created, we get the department from the visitor, so you need to set this information when you register the visitor.

**Comment by arsevys** [comment]
currently these are the data to send to create a visitor....
`https://XXXXX.rocket.chat/api/v1/livechat/visitor
{
  "visitor": {
    "email": "9999999@mail.com",
    "phone": "99999999",
    "token":"XXXX-XXXXX-XXX",
    "tipo":"Facebook",
    "customFields": [{
      "key": "Canal",
      "value": "Facebook",
      "overwrite": true
    },{
      "key": "Name",
      "value": "XXXXX",
      "overwrite": true
    }]
  }
}
`
Then I would be missing some information, or how can I get the visitor to be assigned to some department?

**Comment by renatobecker** [comment]
> currently these are the data to send to create a visitor....
> https://XXXXX.rocket.chat/api/v1/livechat/visitor
> {
> "visitor": {
> "email": "[9999999@mail.com](mailto:9999999@mail.com)",
> "phone": "99999999",
> "token":"XXXX-XXXXX-XXX",
> "tipo":"Facebook",
> "customFields": [{
> "key": "Canal",
> "value": "Facebook",
> "overwrite": true
> },{
> "key": "Name",
> "value": "XXXXX",
> "overwrite": true
> }]
> }
> }
> Then I would be missing some information, or how can I get the visitor to be assigned to some department?

You need to set the `department` field when you register the visitor, otherwise, the room will be created without any room.
