### ISSUE TITLE
Rocketchat 3.3.0 and LDAP: Question about Password Storage Scheme

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#17946]
Hi,
I would like to integrate RocketChat authentication with my company's LDAP server, which uses OpenDJ. Due to compatibilities with other applications and software we use, the password storage  scheme in OpenDJ is MD5.
I would like to know:

1. Is this password storage scheme compatible with RocketChat?

2.  Most important: does RocketChat rewrites the data fields (password etc) on LDAP when using it?

We're concerned about this because if RC rewrites the passwords in another scheme such as SHA2, all of our other applications that use LDAP will stop working correctly. So we want to be really sure that no rewrites at all will happen, or at least if there's a way to properly set RocketChat to use LDAP as "read only".

Thanks very much

**Comment by pierre-lehnen-rc** [comment]
LDAP integration of Rocket.Chat is read only, we never send any updates.

**Comment by JohnLukeP** [comment]
> LDAP integration of Rocket.Chat is read only, we never send any updates.

Hi, thanks very much for your reply. It does never send updates not even when enabling Sync / Import functions or if a user changes its password directly from Rocket?

**Comment by pierre-lehnen-rc** [comment]
Yes, if they change their password on Rocket.Chat, it'll only affect their local account and it'll be changed back the next time they log in using LDAP.

**Comment by JohnLukeP** [comment]
Thanks very much for the info.
