### ISSUE TITLE
Problem with viewing thread after search

### ISSUE THREAD

**Issue by viktoriya666** [RocketChat/Rocket.Chat#17951]
### Description:

You can’t proceed to viewing the thread after the desired message is found in the search

### Steps to reproduce:

1. Go to "Search Messages" 
2. I enter a message in the search bar
3. Click on ".. replies"
3. Everything disappears, an empty window

### Expected behavior:

A thread opens for viewing!!

### Actual behavior:

![Clipboard - June 18, 2020 8_42 AM](https://user-images.githubusercontent.com/61913288/85046877-b26fb780-b199-11ea-8bd9-ca9d1cfa7655.jpeg)
![Clipboard - June 18, 2020 8_41 AM](https://user-images.githubusercontent.com/61913288/85046880-b4397b00-b199-11ea-90bb-1f048c61e7b8.jpeg)

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10

**Comment by frdmn** [comment]
Just tried to reproduce on 3.1.1 but was able to view the thread content just fine. Can you try the desktop version and see if the problem can be reproduced there as well? Might be related to the client/browser in use.

**Comment by ggazzo** [comment]
please check on open.rocket.chat if you can... we are testing a new thread behavior and we changed how we open threads.. thanks :)

**Comment by viktoriya666** [comment]
Hello! The problem still persists. I open chrome through Google. I can not view the thread (
What else can you try? Can update?

**Comment by frdmn** [comment]
@viktoriya666 Did you contact @ggazzo already on open? Also as I wrote in my earlier comment, have you tried the desktop client - does the problem occur there as well?
