### ISSUE TITLE
Formatting Response via Hubot

### ISSUE THREAD

**Issue by danny-waite** [RocketChat/Rocket.Chat#1795]
Guys, great app!

I'm trying to make my responses a little more pretty so I'm examining my options.  I see mentions of Slack style attachments by returning a json structure but I've not been successful so far. Also markdown looks like an option but I've had limited success.

Is there anywhere that explains my options fully?

Thanks in advance.

**Comment by Sing-Li** [comment]
@danny-waite:  please come into https://demo.rocket.chat  ... into the #general channel to see a family of bots that use formatted output.

Also on the same demo chat , you will find members of our core team and community members (likely after the holiday weekend) who can assist you further.

FYI  code  for the bots with formatted output is here.... 

https://github.com/RocketChat/Rocket.Chat.Ops/tree/develop/hubots
