### ISSUE TITLE
Not working "Jump to message"

### ISSUE THREAD

**Issue by viktoriya666** [RocketChat/Rocket.Chat#17953]
### Description:

After searching for the desired message, for example, from June 01, 11:00 a.m., I click "Jump to message" and I am thrown to the first message BUT the next day, June 2!
Throws to the desired message only if you double-click "Jump to message"

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10

**Comment by ankar84** [comment]
I confirm that bug.
But you go to message that you need after **clicking Jump to message second time**, but not double-clicking it.
So first click will go to first message of next day. And than you click to **Jump to message** again and get message you want.

**Comment by viktoriya666** [comment]
Yes that's right. not a double-click!

**Comment by ggazzo** [comment]
I know that looks a different issue but actually they are the same, so I will close this one ..
Duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/17953
