### ISSUE TITLE
Add message editting timeout to preserve old messages

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1796]
Editing previous messages is great specially to correct spelling mistakes, however, after a certain time it becomes useless or undesirable. (it can also be used to make fun of someone :) )

```
Me: Would you like a free coffee?
Victim: Sure I would love that.
```
Sometime later:
```
Me: Would you like to hack and destroy Rocket Chat?    *Edited by me 
Victim: Sure I would love that.
```
This is just an example, and someone can argue that the victim can also see the change, but it won't be easy if those lines are few pages away from the current page. Since no one gets notifications about edits.
Also editing something old is not useful and most people who have read the old message will not see the change, while they will see the change if the writer wrote the corrected version again.

That can be mitigated with a timeout timer that can be set by the admin at the server level, or maybe room level.
Very active rooms may need a short timeout, while other rooms might need to allow edits all the time to update e.g. project progress/ updates ...etc

**Comment by Megatronic79** [comment]
+1 also falls into QA and compliance when discussions between clients should be kept for legal and compliance reasons and should not be ableto be edited - compliment the proposed auditing and logs and can possibly be merged with

https://github.com/RocketChat/Rocket.Chat/issues/795
https://github.com/RocketChat/Rocket.Chat/issues/752
https://github.com/RocketChat/Rocket.Chat/issues/722

**Comment by k0nsl** [comment]
isn't this already available through `Block Message Editing After (n) Minutes`, or did I misunderstand you?

**Comment by fduraibi** [comment]
@k0nsl :1:

Shame on me hahaha
