### ISSUE TITLE
Push and Email Notifications stopped working after upgrade to 3.3.0

### ISSUE THREAD

**Issue by fasalsh** [RocketChat/Rocket.Chat#17965]
Hello,

We have recently upgraded our RocketChat instance to v3.3.0, and everything works fine except the Android popup and email notifications of DMs. The settings are same as before, and nothing changed on that part but these are still not working.

I've updated the Android app, and log out and back in with no luck. Can someone shed some light on this situation.

**Comment by sampaiodiego** [comment]
can you please elaborate a bit more on what "Android popup" means? maybe the correct place to report this is in mobile app's repo https://github.com/RocketChat/Rocket.Chat.ReactNative

regarding email notifications of DMs, we have changed a little bit how notifications are queued to be sent, but this is the first report of this kind.. can you please describe the exact actions and expectations you have to when receive an email?

**Comment by fasalsh** [comment]
@sampaiodiego 

First issue is RocketChat Android application push notification issue. This was working fine before the upgrade, but unfortunately after the upgrade to v3.3.0 the notification is not displaying on none of the staffs phones when someone message him/her. The settings are set to push the notifications, but this isn't working. Can you help me to look over anything specific to troubleshoot this situation further. I'll also create an issue thread in mentioned RocketChat ReactNative repo.

The second issue is with the offline email notifications. This was also working fine before the upgrade where the users were receiving an email notification when they were offline. This isn't working now. Any insight on this too you could give?

Thanks :)

**Comment by sampaiodiego** [comment]
thanks @fasalsh for the info, I changed the issue title to better illustrate the situation.

**Comment by fir3bird** [comment]
We are facing the same issue regarding E-Mail notifications. Push Notifications were disabled for us, since they were disturbing users that had the app installed and browser open simultanously.

I checked our `rocketchat_notification_queue` and it is empty.
But if there is a discussion created within a channel with  "@all" nobody gets notified by email. 

Furthermore the channel neither is marked as unread nor does one get a desktop notification by the desktop app.

**Comment by sampaiodiego** [comment]
@fir3bird there was a bug with discussion creation fixed by https://github.com/RocketChat/Rocket.Chat/pull/17959 and will be available on 3.4.0

@fasalsh just to make sure, is the setting `Disable Notifications` under `Admin > Troubleshoot` disabled?

**Comment by fasalsh** [comment]
I have this resolved after a server reboot, I guess there might had a kernel update or something which might have solved after reboot.

Anyway, everything works fine as before. Thanks all :)

**Comment by sampaiodiego** [comment]
interesting, good to know @fasalsh .. thanks

**Comment by dstaykov** [comment]
I confirm. We had exactly the same problem.
RC 3.3 with Centos 8. After kernel update end server reboot notifications are working fine.
We tried to reboot the server before the kernel update but notifications were not working.
