### ISSUE TITLE
API call groups.files does not retrieve the whole list of files

### ISSUE THREAD

**Issue by stormyordos** [RocketChat/Rocket.Chat#17969]
### Description:

I am trying to get a complete list of files posted to a private channel ("group") on RocketChat 2.4.7, however the list I receive contains only 50 items, where it should contain more than 150 items.

### Steps to reproduce:

Curl query:
curl -H "X-Auth-Token: AUTHTOKEN" -H "X-User-Id: USERID" https://rocket.ifred.team/api/v1/groups.files?roomName=ROOMNAME

### Expected behavior:

a JSON listing all files (clipboard images, txt files, applications, etc) since the creation of the channel.

### Actual behavior:

a JSON listing a list of 50 files maximum with dates all over the place (same list every time).

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.7
- Operating System: Linux 5.3.0-1023-aws
- Deployment Method: /usr/local/bin/node /opt/Rocket.Chat/main.js, registered as a service on systemd
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: API
- Operating System: Linux

### Relevant logs:

I20200617-19:58:12.563(0) ➔ +--------------------------------------------------+ 
I20200617-19:58:12.563(0) ➔ |                  SERVER RUNNING                  | 
I20200617-19:58:12.563(0) ➔ +--------------------------------------------------+ 
I20200617-19:58:12.563(0) ➔ |                                                  | 
I20200617-19:58:12.564(0) ➔ |  Rocket.Chat Version: 2.4.7                      | 
I20200617-19:58:12.564(0) ➔ |       NodeJS Version: 8.11.4 - x64               | 
I20200617-19:58:12.564(0) ➔ |      MongoDB Version: 4.0.16                     | 
I20200617-19:58:12.564(0) ➔ |       MongoDB Engine: mmapv1                     | 
I20200617-19:58:12.564(0) ➔ |             Platform: linux                      | 
I20200617-19:58:12.565(0) ➔ |         Process Port: 1337                       | 
I20200617-19:58:12.565(0) ➔ |             Site URL: https://rocket.ifred.team  | 
I20200617-19:58:12.565(0) ➔ |     ReplicaSet OpLog: Enabled                    | 
I20200617-19:58:12.565(0) ➔ |          Commit Hash: 3b1fdd1d70                 | 
I20200617-19:58:12.566(0) ➔ |        Commit Branch: HEAD                       | 
I20200617-19:58:12.566(0) ➔ |                                                  | 
I20200617-19:58:12.566(0) ➔ +--------------------------------------------------+

**Comment by stormyordos** [comment]
I found the problem, and an issue:

in https://github.com/RocketChat/Rocket.Chat/blob/35a8949501706005b6fe19c670fd9426783b2e98/app/api/server/settings.js

it says that count is by default at 50, and maximum is set to 100. 
by adding a parameter &count=0 to the end of the query, like this:

curl -H "X-Auth-Token: AUTHTOKEN" -H "X-User-Id: USERID" https://rocket.ifred.team/api/v1/groups.files?roomName=ROOMNAME&count=0

everything works as intended.
Hope this is useful for someone.

**Comment by sampaiodiego** [comment]
good to know you found it by yourself.

here a link on how pagination works on our REST API https://docs.rocket.chat/api/rest-api/offset-and-count-and-sort-info
