### ISSUE TITLE
Wrong API URL on Apps page

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/Rocket.Chat#17978]
I've created a simple webhook(API). The webhook is working perfectly fine. However, on the Apps page, the `curl` URL displayed has `an extra character`. Have a look.
![image](https://user-images.githubusercontent.com/34130764/84517077-5ebe2380-acec-11ea-9e63-ed22bf7dc9f1.png)

**Note there is an Extra `backslash` after http://localhost:3000**

I guess it should be http://localhost:3000/api/apps......

**My Setup:**

Server
![image](https://user-images.githubusercontent.com/34130764/84519423-b611c300-acef-11ea-9f0e-d53a3e0a0d6b.png)

**Comment by lolimay** [comment]
Hey, @murtaza98 this bug has been fixed in the latest commit. Please update your local branch.

**Comment by murtaza98** [comment]
> Hey, @murtaza98 this bug has been fixed in the latest commit. Please update your local branch.

Awesome, Thanks @lolimay :tada:
