### ISSUE TITLE
Removable-media plug cannot be installed

### ISSUE THREAD

**Issue by MaxVRAM** [RocketChat/Rocket.Chat#17980]
### Description:

Removable:media plug cannot be installed.
Unable to use removable media as a file system in Rocket.Chat.

### Steps to reproduce:

1. Install fresh, "snap install rocketchat-server"
2. Use command "snap connect rocketchat-server:removable-media"

### Expected behavior:

Removable-media plug should be installed. Mounted drive can be used as file system in Rocket.Chat.

### Actual behavior:

Returns the message "error: snap "rocket-chat" has no plug named "removable-media"".
Does not complete installation.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2 (1437)
- Operating System: Linux 5.4.0-1012-raspi aarch64
- Deployment Method: Snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Additional context

This problem doesn't occur on an installation I was using on another server. This was running 3.2.2 (1433). I was able to use a mounted drive as Rocket.Chat's file storage in this instance.

**Comment by MuhClaren** [comment]
Same problem, fresh install via snap on raspberry pi 4...

"error: snap "rocket-chat" has no plug named "removable-media"".
