### ISSUE TITLE
Federation Setup Error

### ISSUE THREAD

**Issue by rodentskie** [RocketChat/Rocket.Chat#17987]
### Description:
I want to have a common channel for both my RC instances. Both are installed on a local server but running on different port.

Instance 1: http://localhost:3000
Instance 2: http://localhost:2000

### Steps to reproduce:
You must be an Admin.

1. Options -> Administration
2. Search Federation and Click
3. Below is the screenshot of my configuration.

### Expected behavior:
The configuration is straightforward and I just follow the instructions, but somehow an error returned, maybe I miss something.

### Actual behavior:

Setup return this error.

![image](https://user-images.githubusercontent.com/49242131/85259796-3c6e9780-b49c-11ea-8a55-4bca62e1d866.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: Linux
- Deployment Method:  docker
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18    

### Client Setup Information

- Desktop App or Browser Version: Browser Version (Google Chrome)
- Operating System: Windows 10

### Additional context

I followed the steps here on the official site: https://docs.rocket.chat/guides/administrator-guides/federation

### Relevant logs:
This is the logs in the admin

server.js:204 Federation ➔ dns.error Error: ETIMEDOUT     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:849:19)     at listOnTimeout (internal/timers.js:549:17)     at processTimers (internal/timers.js:492:7) {   code: 'ETIMEDOUT',   connect: true }

**Comment by rodentskie** [comment]
![image](https://user-images.githubusercontent.com/49242131/85260430-3f1dbc80-b49d-11ea-8b29-9da88218f1e5.png)

These are the containers.

**Comment by klepptor** [comment]
@rodentskie please have a look here. seems also a dns problem. or a problem because you don't use dns.

**Comment by klepptor** [comment]
funny, just saw that you were the op in the forums...

**Comment by rodentskie** [comment]
Thanks sir, yea it's me too. :D

**Comment by rodentskie** [comment]
I'll try the solution gonna contact the Net Ads of the company regarding the DNS config.
