### ISSUE TITLE
Users allowed to post in read-only channels can't post with browser or desktop app - but with mobile app

### ISSUE THREAD

**Issue by fir3bird** [RocketChat/Rocket.Chat#17988]
### Description:

Users that are allowed to post within read-only channels, cannot post to these channels within browser or desktop app.
While using the mobile App, users can post within read-only channels.

### Steps to reproduce:

1. Create read-only channel
2. Give user the right to post in read-only channel 
3. See that user is not able to do so in browser

### Expected behavior:

The user that is allowed to post in read-only channel can post messages within the read-only channel. In browser, desktop app and mobile app.

### Actual behavior:

The user can only post in read-only channels with mobile app.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.3.3
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Desktop App 2.15.5 and Chrome Latest
- Operating System: Windows 10

**Comment by pierre-lehnen-rc** [comment]
Fixed by #17709 on 3.4.0
