### ISSUE TITLE
Remove :ok_hand: since it is now considered a symbol for the white power movement

### ISSUE THREAD

**Issue by kubicgruenfeld** [RocketChat/Rocket.Chat#17996]
### Description:

Since the 👌 emoji is now considered a symbol for the white power movement and therefore promoting hate speech i would like to see it removed .

### Steps to reproduce:
use 👌 

### Expected behavior:
emoji not present

### Actual behavior:
promoting hate speech

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: k8s
- Deployment Method: helm
- Number of Running Instances: 2
- DB Replicaset Oplog: -
- NodeJS Version: -
- MongoDB Version: -

### Client Setup Information

- Desktop App or Browser Version: -
- Operating System: -

### Additional context

https://en.wikipedia.org/wiki/OK_gesture#White_power_symbol
https://www.adl.org/education/references/hate-symbols/okay-hand-gesture

### Relevant logs:
-

**Comment by MartinSchoeler** [comment]
Hello @kubicgruenfeld This emoji is part of a package from [Joypixels](https://www.joypixels.com/) so I would suggest opening this issue in their [repository](https://github.com/joypixels/emoji-toolkit). Closing this issue for now. Thanks!

**Comment by kubicgruenfeld** [comment]
Done: https://github.com/joypixels/emoji-toolkit/issues/27
