### ISSUE TITLE
User friendly URLS with room names and usernames instead of IDs

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#18]
Create slugs and use them to link to rooms

**Comment by Hosseinamraji** [comment]
how download?

**Comment by rodrigok** [comment]
@Hosseinamraji how download what?

**Comment by scottyallen** [comment]
So, it's not immediately obvious what a room link should look like, based on what's here.  As a straw man, how about:

http://rocket.chat/room/57om6EQCcFami9wuT/general

Sound reasonable?

Another option is to just use the room name, ie:

http://rocket.chat/room/general

However, this suffers the problem that if the room is renamed, the link no longer works, whereas the former you can still look up by id.

I'm going to take a crack at implementing the first suggestion, and we can tweak it in the PR if needed.

**Comment by engelgabriel** [comment]
We already stated to work on this, so please wait a couple is days and you
will see your second option implemented :)



-- 
Sent from Mobile
