### ISSUE TITLE
User is prompted to reset their password when logging in with OAuth provider

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#18000]
### Description:
User is prompted to reset their password when logging in with OAuth provider

### Steps to reproduce:

1. Setup OAuth like GitHub or Google
2. Have an account that already exists and is verified (this could be from a previous OAuth login predating version 3.3.0, or a manually created account, or an LDAP synced account)
3. Try to login with OAuth

![Clipboard - June 22, 2020 11_30 AM](https://user-images.githubusercontent.com/6295044/85308870-c9572800-b47f-11ea-93f9-867a67524d01.png)

### Expected behavior:

Log in without issue.

### Actual behavior:
![Clipboard - June 22, 2020 11_25 AM](https://user-images.githubusercontent.com/6295044/85308888-d116cc80-b47f-11ea-9d17-5feedf8356a9.png)

Users are being prompted that the email is duplicated and is not verified. They are required to reset their password even when we have password resets disabled. If they try to type in their current correct password, it shows the password can't be changed.

![Clipboard - June 22, 2020 11_31 AM](https://user-images.githubusercontent.com/6295044/85308883-ce1bdc00-b47f-11ea-9e32-1c9ca6600b4b.png)

![Clipboard - June 22, 2020 11_54 AM](https://user-images.githubusercontent.com/6295044/85308390-29999a00-b47f-11ea-97ee-5dea62239bdc.png)

### Server Setup Information:

- Version of Rocket.Chat Server: Issue has been seen on 3.0.3 (ef1e0b3613772175717968fed444cd0db92ff72c) and 3.3.0 (a9872957180059094e50678ec311b2fcef8f61ad)

### Additional Information
![image](https://user-images.githubusercontent.com/6295044/85309563-c7da2f80-b480-11ea-93a5-a9b6bfd1b487.png)

**Comment by wreiske** [comment]
IMO if the allow password change setting is OFF, there's probably a good reason for it, and the user should never be able to change their password in Rocket.Chat.

It should maybe prompt the user to contact their administrator to unlock their account, or it should refuse to allow the user to log-in at all if the email isn't verified. It looks like possibly it logs the user in but keeps them on that screen. They may be able to see incoming messages, use "Router.go" to change their route to a DM, etc.

**Comment by pierre-lehnen-rc** [comment]
The setting exists to protect the user in case someone tried to use their email in the past. In that case when they log in through OAuth they will be taking over the account that used their email and by changing the password they'll me locking out the old user.
