### ISSUE TITLE
Users can still write in Write Protected channels via discussions.

### ISSUE THREAD

**Issue by Rhywden** [RocketChat/Rocket.Chat#18018]
### Description:

Basically, when I set a channel to "Write Protected" I expect it to be actually thus - namely, only users with the specific and explicit right to write in such channels.

However, I found out that my users can circumvent the write protection by simply starting a discussion in such channels - which is then promptly visible for all in the channel thus rendering the write-protection completely moot. When you have 1800+ users in a channel intended solely for announcements this is not ideal.

The only way for me to stop this behaviour is to take away the ability to start discussions completely which is a rather large hammer to swing around.

### Steps to reproduce:

1. Set channel to "Write Protected"
2. Write a message in said channel

### Expected behavior:

No one but people with the proper rights being able to write in this channel

### Actual behavior:

Users can still write in the channel by using discussions.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows

### Additional context

n/a

### Relevant logs:

n/a

**Comment by pierre-lehnen-rc** [comment]
This was fixed on version 3.4, which is currently in release candidate stage.
