### ISSUE TITLE
Unable to access the service via iOS/Android

### ISSUE THREAD

**Issue by gfranzen** [RocketChat/Rocket.Chat#1801]
Started using Rocket.Chat in our environment recently and have had a pleasant experience so far. Got a user who wanted to get the client set up on his android phone, had him install the app and I got the iOS version.  Tried feeding the app the URL that we use to access our instance but get "Failed to connect to server: error".  Made sure that I was connected to our local/internal wireless connection.  Got confirmation from the person that set up our instance did use docker to do so, and that "nginx is set up in front of it for SSL".  The person who set our instance up also raised the concern that our phones possibly must be set to trust our local/internal Certificate Authority.  Any help in working through this integration task would be greatly appreciated.

**Comment by engelgabriel** [comment]
Hi,

For security reasons, the mobile and desktop apps cannot open servers with self sign certificates.

Please consider using https://letsencrypt.org/ to secure your server for free or buying a cheap certificate like https://www.namecheap.com/security/ssl-certificates/comodo/essentialssl-wildcard.aspx
