### ISSUE TITLE
Modals shouldn't dismiss within first say 500 ms after appearing

### ISSUE THREAD

**Issue by NickBusey** [RocketChat/Rocket.Chat#1802]
Just had a dialog popup at the same time I was clicking something else. It disappeared before I could even read it. I know it was a call invite, but wouldn't have known if I wasn't sitting next to the person who initiated it at the time.

I'll look into seeing if this is a fix I can implement myself, just thought it should be tracked.

**Comment by MartinSchoeler** [comment]
Hey @{name}, I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
