### ISSUE TITLE
Can't invite other agent to the omnichannel room

### ISSUE THREAD

**Issue by antkaz** [RocketChat/Rocket.Chat#18023]
### Description:

After added a Multi DMs I can't invite others agents to OmniChannel (Livechat) room via `/invite @username`

### Steps to reproduce:

1. Open Omnichannel room
2. Take it
3. execute command `/invite @username`

### Expected behavior:

the user added to omnichannel room

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.3
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

I think that roomTipe for Livechats not added and a method `allowMemberAction` always returns `false`

**Comment by renatobecker** [comment]
Hi @antkaz, thanks for reporting it.
It was supposed to be accepting invites for Omnichannel managers(not other agents), I'll look into it, probably something changed and affected the feature.

**Comment by antkaz** [comment]
Hi @renatobecker! Thanks

**Comment by antkaz** [comment]
Any updates?

**Comment by renatobecker** [comment]
> Any updates?

Yeah, We're going look into this issue over the next week.
Thanks.

**Comment by antkaz** [comment]
@renatobecker thank you!
