### ISSUE TITLE
LiveChat: Unable to assign offline messages to any agent when automatic routing is enabled, and someone become available. 

### ISSUE THREAD

**Issue by glyphCezilleSantillan** [RocketChat/Rocket.Chat#18041]
### Description:

Unable to take inquiry when (office hours enabled: not sure if related, and) all agents are offline. We've allowed offline messages but can't assign them to agents once someone sets their LiveChat status to available again.

We can see the conversations in Current Chats as `Served by (empty)`. The endpoint `livechat/inquiries.list` returns an empty array, so this kind of makes sense. But when using the `livechat/rooms` endpoint to get the `open: true` and `waitingResponse: true` rooms, there is a confusing response `error-not-allowed`, `reason: Inquiry already taken` when it's clearly not taken by anybody yet. 

However, since the routing is automatic, agents can't "Take it" from the pool of available conversations. At the same time, LiveChat managers also can't `Close` them, there are no controls whatsoever when viewing chat details.

Maybe we're going about this the wrong way... Need advice please.

### Steps to reproduce:

0. Set to automatic routing.
1. Set all agents to "Unavailable".
2. Send a new LiveChat message to the instance. 
3. Agent comes back online.
4. Using the `livechat/rooms` API, we look for any unassigned rooms (as described above) and try to assign that room to the newly-available agent with the `livechat/inquiries.take` endpoint.

Sample code:

    const instance= require('axios').create({
      baseURL: `https://${process.env.ROCKET_WORKSPACE}/api/v1`,
      headers: {
        'X-Auth-Token': process.env.ROCKET_AUTH,
        'X-User-Id': process.env.ROCKET_USER
      }
    });
    const axios = (config) => instance(config).then(r => r.data).catch(CustomErrorLoggerFunction);
    
    const rooms = await axios({
      url: '/livechat/rooms',
      method: 'GET',
      params: {
        open: true
      }
    }).then(r => r.rooms);  // This will return at least one open room if steps above were done
    const filtered = rooms.filter(r => r.waitingResponse);
    if (filtered.length) {
      const online = [{ _id: 'initialuser' }]; // Actual user will be from POST data using Custom Script
      const r = await axios({
        url: '/livechat/inquiries.take',
        method: 'POST',
        data: {
          inquiryId: filtered[0]._id, // Just the first one as a test
          userId: online[0]._id
        }
      });
    }
    

### Expected behavior:

No 400 error—an agent who comes online can be assigned to an unassigned (offline) conversation even if automatic routing is enabled. 

### Actual behavior:

There is an HTTP 400 error with the response: 

```
{
  isClientSafe: true,
  error: 'error-not-allowed',
  reason: 'Inquiry already taken',
  details: { method: 'livechat:takeInquiry' },
  message: 'Inquiry already taken [error-not-allowed]',
  errorType: 'Meteor.Error',
  success: false
}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: (Unsure where to get this info, sorry)
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version:  
- Operating System: Windows

**Comment by glyphCezilleSantillan** [comment]
Update: It turns out I needed to have the `Livechat Manager` role to be able to _Forward_ messages to other agents. Instead of using the `/livechat/inquiries.take` API I changed it to use the `/livechat/rooms.forward` API instead, and it seems to do what we want it to do for now.

That role issue though was confusing. I was already an Admin and yet there were multiple "not-allowed-error"s when attempting to forward manually.

**Comment by johncordeiro** [comment]
I've experienced the same behavior here @glyphCezilleSantillan. @renatobecker I noticed that it's possible to enable `Show Queue List to All Agents` as you can see in the routing config:

![image](https://user-images.githubusercontent.com/6073075/85928774-ff344c00-b885-11ea-898b-4b100f4a0eef.png)

However, when the agent gets online and open the queue, no chat is available on the list:

![image](https://user-images.githubusercontent.com/6073075/85928728-86cd8b00-b885-11ea-8b80-617c11aa7c92.png)

What about showing the open chats with no agents in this list and make it available to any agent to `Take it`?
