### ISSUE TITLE
Multiple File Upload

### ISSUE THREAD

**Issue by chevalierv** [RocketChat/Rocket.Chat#18054]
### Description:

We frequently share multiple pictures and, on web version, the server ask for confirmation with a modal for each picture. That's impossible to handle when you upload more than 10 pictures. Worse, on iPhone, you have to select the pictures one-by-one. 

A previous issues was opened but doesn't really seem to have been implemented: #11444

Also, you might want to check iOS14's file picking mechanisms because Apple has restricted this functionality.

### Steps to reproduce:

1. In any channel
2. Try to upload a dozen files at once

### Expected behavior:

Select multiple files and confirm them all at once.

### Actual behavior:

On desktop, you have to confirm each files one by one. On ios, you can't even select multiple files

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: Google Chrome, Mobile Apps
- Operating System: Windows 10, iOS

### Additional context

N/A

### Relevant logs:

N/A

**Comment by ankar84** [comment]
Might be resolved for mobile client in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2162

**Comment by Conrado916645** [comment]
Any updates?
