### ISSUE TITLE
No setting to disable editing custom fields

### ISSUE THREAD

**Issue by Rhywden** [RocketChat/Rocket.Chat#18056]
### Description:

I added a custom field wherein every user's info about the course/department he/she belongs to is contained. As this info is obtained from LDAP and set through a script, I do not want it to be editable. Currently there is no way to do this save for disabling editing the profile completely which also disables Avatar upload.
A dropdown is not an option as the courses change regularly.

### Steps to reproduce:

Create a custom field. 

### Expected behavior:

Since we're already using JSON to define settings for the custom field, there should also be a "roles-editable" setting.

### Actual behavior:

The field can be edited by the user at any time with no way to prevent this, as far as I can see.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.0
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.18

### Client Setup Information

n/a

### Additional context

n/a

### Relevant logs:

n/a

**Comment by Alexdc-12** [comment]
I think this should be implemented, its handy to store extra info on a user but you dont want them changing that

**Comment by robincafolla** [comment]
I also would find this useful.
