### ISSUE TITLE
Hardcoded 'aud' parameter on Jitsi JWT Authentication

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat#18075]
### Description:

When configuring Jitsi JWT Authentication on Rocke.Chat, there are only two parameters available

![screenshot_383](https://user-images.githubusercontent.com/11891939/86059621-7231f400-ba39-11ea-9a87-c091b4c9384e.png)

This is an issue when setting up a self hosted Jitsi server with JWT authentication, as there are other parameters which are necessary for the JWT token to be correctly validated. 

'aud' field is checked in the JWT validatation, and currently this field is hardcoded with "RocketChat" value:

https://github.com/RocketChat/Rocket.Chat/blob/cc42193fdb09565b68233ba01384c8e7a753256b/app/videobridge/server/methods/jitsiGenerateToken.js#L59

### Steps to reproduce:

1. Set self hosted up Jitsi with JWT
2. Try to validate the scenario
3. Following error is triggered:

![image](https://user-images.githubusercontent.com/11891939/86060149-8c200680-ba3a-11ea-86d2-27ae3a47f07b.png)

### Expected behavior:

'aud' should be a configuration parameter for this scenario to work properly.

### Actual behavior:

Parameter is hardcoded, invalidating the JWT authentication

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0-develop

### Relevant logs:

Further info -> https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

**Comment by ankar84** [comment]
We now configured integration with self-hosted Jitsi server with JWT authentication and all works perfect. I don't see any `aud` errors in logs, users from Rocket Chat are authenticated correctly - avatars and usernanes in Jitsi from RC and guest are fellow jitster without avatar.

**Comment by rsjr** [comment]
@ankar84 Do you mind sharing with us the steps you made to make it work? In specific the JWT setup on Jitsi side (the json generation, the config file and the prosody setup)? This way we can enhance our docs, as we didn't have that much of users using this setup. Thanks in advance!

**Comment by ankar84** [comment]
> Do you mind sharing with us the steps you made to make it work?

Actually there was no extra steps. We just configured our Jitsi deployment with authentication (with token) and configured guest Virtual host for anonymous users (external to Rocket Chat). That is done by that config:
````
VirtualHost "meet.jitsi"
    authentication = "token"
    app_id = "Application ID from rocket"
    app_secret = "Application Secret from rocket"
    allow_empty_token = false

VirtualHost "guest.meet.jitsi"
    authentication = "token"
    app_id = "Application ID from rocket"
    app_secret = "Application Secret from rocket"
    allow_empty_token = true
````
By the way we decoded you JWT token and indeed there is a `"aud": "RocketChat"` 
But still, we don't have any problems with Jitsi with JWT authentication. 
All Rocket Chat users can start new Jitsi call (guest can't) and all have avatar and user name from Rocket chat, which are encoded in JWT token in context.user (there are name, email, avatar, id).

Here is a all our **jitsi-meet.cfg.lua** with sensitive information skipped or replaced
````
admins = { "focus@auth.meet.jitsi" }
plugin_paths = { "/prosody-plugins/", "/prosody-plugins-custom" }
http_default_host = "meet.jitsi"

VirtualHost "meet.jitsi"
    authentication = "token"
    app_id = "Application ID from rocket"
    app_secret = "Application Secret from rocket"
    allow_empty_token = false

    ssl = {
        key = "/config/certs/meet.jitsi.key";
        certificate = "/config/certs/meet.jitsi.crt";
    }
    modules_enabled = {
        "bosh";
        "pubsub";
        "ping";
    }
    c2s_require_encryption = false

VirtualHost "guest.meet.jitsi"
    authentication = "token"
    app_id = "Application ID from rocket"
    app_secret = "Application Secret from rocket"
    allow_empty_token = true

    c2s_require_encryption = false

VirtualHost "auth.meet.jitsi"
    ssl = {
        key = "/config/certs/auth.meet.jitsi.key";
        certificate = "/config/certs/auth.meet.jitsi.crt";
    }
    authentication = "internal_plain"

Component "internal-muc.meet.jitsi" "muc"
    modules_enabled = {
        "ping";
    }
    storage = "memory"
    muc_room_cache_size = 1000

Component "muc.meet.jitsi" "muc"
    storage = "memory"
    modules_enabled = {
        "token_verification";
    }

Component "focus.meet.jitsi"
    component_secret = "secret string"
````

**Comment by rsjr** [comment]
Thanks @ankar84 !
