### ISSUE TITLE
When async function is used in condition it always returns true

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat#18073]
### Description:
messageBox.actions condition statement does not work correctly when using async function
```
messageBox.actions.add('Screen_Sharing', 'Request_Screen_Sharing', {
	id: 'request-screen-sharing',
	icon: 'video',
	condition: async () => {
               // some async call...
 	        return settings.get('Livechat_enabled') && settings.get('Livechat_screen_sharing_enabled');
	},
});
```
More example:
This statement will also return true
```
condition: async () => {
 	        return 0;
	},
```
But if async is removed. It returns false
```
condition: () => {
 	        return 0;
	},
```

### Steps to reproduce:

1. change condition to async

### Expected behavior:
It should check the current set settings

### Actual behavior:
It always returns true

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: ubuntu 18.04
- Number of Running Instances: 1
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 4.2.5

### Client Setup Information
- Operating System: Ubuntu 18.04

**Comment by ggazzo** [comment]
doest not return `true`, returns a promise... `promise` is !== `false`

**Comment by ashwaniYDV** [comment]
@ggazzo Can you please tell me how to check for this condition 
```
Meteor.call('livechat:getActiveSessionStatus', rid).then((booleanVal) => {
			return booleanVal && settings.get('Livechat_screen_sharing_enabled');
		});
```
