### ISSUE TITLE
Live chat web interface

### ISSUE THREAD

**Issue by ryc065** [RocketChat/Rocket.Chat#1807]
Hi.
I've compiled rocketchat live support plugin on my centos 7 server, and it is working, but when I paste your script to my sample webpage it is not. When i click on chat window it don't expand or if i open it directly it did not respond to any written text like on your sample webpage.

Unfortunately almost all docs are WIP and I'm beginner so i might made mistakes during compilation.
 

Thanks

**Comment by sampaiodiego** [comment]
hey @ryc065 .. did you check the console on your browser?
did you get any errors?
what browser are you using?

**Comment by ryc065** [comment]
hi
I'm using firefox 43 and errors are
Unknown property 'webkit-transition'.  Declaration dropped. livechat.css:2:1164
Unknown property 'webkit-transition'.  Declaration dropped. livechat.css:2:1321
Unknown property 'speak'.  Declaration dropped. livechat.css:5:217
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. livechat.css:5:445
Error in parsing value for 'left'.  Declaration dropped. livechat.css:5:22846

**Comment by sampaiodiego** [comment]
hmm.. I've tested with Firefox 43 and seems that it is working fine.

Can you please test on our website ( https://rocket.chat/ ) or provide the address of your sample webpage so I can test it? If you don't want to make this info public, please contact me at https://demo.rocket.chat ..  my user name is: diego.sampaio.rocket.chat 

Also, can you please tell me the version of your instance? You can access: http://your.instance/api/info
