### ISSUE TITLE
Reset password email not sent

### ISSUE THREAD

**Issue by haceru** [RocketChat/Rocket.Chat#1808]
Hello,

I have just built the latest version of Rocket Chat and tested the mail functionality. I have set up the SMTP to use a Gmail account, and the "send invitation" part works OK (I actually received the invitation by email)

However, the Reset Password emails are not send. When checking the logs, this is the error I get:

**_Exception while invoking method 'sendForgotPasswordEmail' SenderError: Mail from command failed - 555 5.5.2 Syntax error. 84sm29732749ioh.3 - gsmtp_**

**_at Object.Future.wait (/var/www/Rocket.Chat/bundle/programs/server/node_modules/fibers/future.js:398:15)_**

The same error occurs for Confirmation Email (when registering a new user)

While searching the Internet for something similar, I found this: http://stackoverflow.com/questions/4321346/555-5-5-2-syntax-error-gmails-smtp

Maybe it is related? But if so, I don`t know how to verify or where to look for a fix

Any suggestions would be greatly appreciated
Thank you

**Comment by haceru** [comment]
I have also found this:
http://stackoverflow.com/questions/28619056/meteor-accounts-failing-with-gmail-while-email-send-works-why

**Comment by marceloschmidt** [comment]
Can you please try with the latest version? Thanks.

**Comment by lepetitjan** [comment]
I run the latest version and also have this problem. Can someone point me where to check?

**Comment by engelgabriel** [comment]
What version to you run @lepetitjan ?

**Comment by lepetitjan** [comment]
0.49.2

**Comment by engelgabriel** [comment]
What is the error in the logs?

**Comment by lepetitjan** [comment]
Nothing...no errors...You mean at /admin/view-logs right?
