### ISSUE TITLE
Video Calling Breaking-Bug (When using Jitsi)

### ISSUE THREAD

**Issue by HiveMindNet** [RocketChat/Rocket.Chat#18099]
### Description:

When starting a new Jitsi video call in RC 3.4.0 in the browser or desktop app, using the admin option to 'Always Open in new Window', the video and audio call starts twice, which is unusable (echoing audio and unnecessary extra video streams). It starts within the expected new window, but also starts within the RC app across the bottom 50% of the acc screen. It's basically now starting using both methods, (within and poppet window). The only change to cause this bug was updating from 3.3.3 to 3.4.0.

### Steps to reproduce:

1. Set Jitsi video calling to 'Always Open in new Window'
2. Start a new video call using the desktop app
3. Double video is started.

### Expected behavior:

Video should just start in new window.

### Actual behavior:

Video starts in 2 windows.
<img width="1368" alt="Screenshot 2020-07-01 at 10 22 37" src="https://user-images.githubusercontent.com/19346725/86227401-df05d500-bb84-11ea-8091-346269ede613.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Latest Docker
- Deployment Method: Latest Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

Any browser or OS X desktop app.

### Additional context

Unable to simply downgrade as DB has changed and can't run within app/browser as then desktop sharing does not work! :(

**Comment by 73** [comment]
It is the same with us.

**Comment by HiveMindNet** [comment]
For others 'stuck' without video calling this morning, a poor emergency workaround is to start the call with new window setting, then end the call in the bottom pane in the screen/app. The poppet window call seems to still work but you must disable the option 'Limit token to Jitsi Room' if you use JWT - Pretty bad position though :(

**Comment by EnCz** [comment]
Such an obvious bug should not happen in a stable release :/ Hope this gets fixed asap

**Comment by danielfariati** [comment]
You guys probably know this, but it is also happening for the Linux and Windows apps.

**Comment by gramakri** [comment]
We hit this in the Cloudron package. Do we know which commit caused this regression?
