### ISSUE TITLE
Why is rocket.chat emailing update notifications (this is obnoxious)? 

### ISSUE THREAD

**Issue by likewhatevs** [RocketChat/Rocket.Chat#18092]
### Description:
Why is rocket.chat emailing update notifications (this is obnoxious)? 

![image](https://user-images.githubusercontent.com/12107998/86195957-155d3900-bb20-11ea-9bf8-b12eaa91fc2d.png)

### Steps to reproduce:

1. Rocket chat has a release, maybe?

### Expected behavior:
No Email.

### Actual behavior:
Email.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: oplog
- NodeJS Version: docker
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: desktop app
- Operating System: windows

### Additional context
None

### Relevant logs:
No logs.

**Comment by LeeThompson** [comment]
I got it as a direct message on my private server, I'm currently hoping my users didn't get it too.

This is *really* lame guys.

**Comment by likewhatevs** [comment]
![image](https://user-images.githubusercontent.com/12107998/86424375-61d77e80-bcb0-11ea-9ef4-478085cffc71.png)

Minor updates too?

**Comment by likewhatevs** [comment]
Per https://github.com/RocketChat/Rocket.Chat/issues/6293 I tried to disable this.

The page to disable this is broken:

![image](https://user-images.githubusercontent.com/12107998/86424556-e5916b00-bcb0-11ea-8e7f-6e91df2b8109.png)

How can I disable this spam?

**Comment by LeeThompson** [comment]
And another one... whee.

@likewhatevs I tried looking under administration/permissions for 'bots' but I couldn't find anything to block direct messages.   It would be best if rocketchat just had options for updates (and if you enable it, who gets them, etc)

**Comment by geekgonecrazy** [comment]
Closing in favor of #18113
