### ISSUE TITLE
Blab or Hangout Features - Enhanced Video Conference features 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1809]
I know we have webrtc available, and i think it can support multiple viewers at the same time (never tested that - each with their own cam).. would it be possible to book calls or a schedule meeting option for upcoming interviews or discussions..?? 
Other questions,

1- can we broadcast ? lets say into Youtube or even stand alone.
2- Option to save the interview or webinar for reproduction? 
3- is it possible to have users to use multiple cams on same Machine? i.e one for face and other could be for showing other items?. 
4- Creation a link for the session to be posted on main site or any other medium for people to join the meeting sort of (gotomeeting style).

**Comment by Sing-Li** [comment]
Definitely.  See #1118.  Maybe @maxlinux2000 has some updates.

**Comment by Sing-Li** [comment]
Please continue discussion on #1118
