### ISSUE TITLE
Users cannot send attachments without filename extension

### ISSUE THREAD

**Issue by WenhaiLin** [RocketChat/Rocket.Chat#18098]
### Description:

Users cannot send attachments without filename extension

### Actual behavior:

![image](https://user-images.githubusercontent.com/5234286/86218360-3c187f80-bbb3-11ea-9e74-b18c4f487622.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.4.0
- Operating System:  Centos 7
- Deployment Method:  tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  
- NodeJS Version:  v12.16.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Chrome 83
- Operating System: Mac 10.15.5

**Comment by emikolajczak** [comment]
Same issue on our server. Accepted media types is set blank

![image](https://user-images.githubusercontent.com/50440047/86346717-9c63fb80-bc5d-11ea-82e4-516f6bc85b0a.png)

**Comment by pehlert** [comment]
Sorry I couldn't discover this one as it didn't have the error message in the text anywhere. Just stumbled across it. I have opened another one here: https://github.com/RocketChat/Rocket.Chat/issues/18122

I'll leave it up to the RocketChat team which one they prefer to keep for now.
