### ISSUE TITLE
[3.4.0] Custom User Status Icon missing

### ISSUE THREAD

**Issue by EnCz** [RocketChat/Rocket.Chat#18104]
### Description:

Hey, since the update to 3.4.0 the message-icons for the custom-user status aren't correctly displayed anymore:
![image](https://user-images.githubusercontent.com/7642122/86246788-daa0e280-bbab-11ea-8868-16c5948b9024.png)

I'm running on Manjaro Linux, before the update on 3.3.0 they worked though.

### Steps to reproduce:

Look at Screenshot.

### Expected behavior:

See a custom user status icon

### Actual behavior:

Don't see one.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Manjaro Linux
- Deployment Method: docker

### Client Setup Information

- Desktop App or Browser Version: WEB
- Operating System: Manjaro Linux

**Comment by HiveMindNet** [comment]
Strange - they show ok for me on 3.4.0

**Comment by EnCz** [comment]
Got it working again by installing fonts on my machine, so it seems to be a client problem.
Didn't check that the first time because it worked till now but maybe the icon was an image before and now switched to ascii? That could be the difference.
Anyway: Closed
