### ISSUE TITLE
3.4.0 no longer allows access to administration

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#18105]
### Description:

After updating to 3.4.0 container tonight, when you click on administration, you are redirected back to home.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

You should be able to use administration with 3.4.0.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Ubuntu 2.004
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Oplog
- NodeJS Version: the one from 3.4.0 container
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: current Chrome and Firefox
- Operating System: Windows, Linux and MacOS

**Comment by EnCz** [comment]
My administration panel works but this happens on my instance, maybe these effects are somehow related code-wise:

### Steps to reproduce:

1. Go to random channel
2. Open Administration
3. Close Administration by clicking the [X]

### Expected behavior:

You're back at the random channel from before

### Actual behavior: 

You land on the "Home"-Screen

**Comment by mranderson56** [comment]
I have the same issue here.
After update to the last version, when i try to go on administration page, disappear !

**Comment by didacroyo** [comment]
same as reported by @EnCz

**Comment by ggazzo** [comment]
what @EnCz reported is something different than @ralfbecker mentioned, both are bugs, but one is just little annoying... the first one is quite important.. but I cant reproduce 😢 ...

**Comment by ralfbecker** [comment]
With the docker-compose installation it's easy to reproduce. 
The docker log shows nothing.
Would it help to give you access to a public machine showing the error?
Ralf

**Comment by ralfbecker** [comment]
Btw. one of our users made a video of it:

https://help.egroupware.org/t/administration-menu-appears-for-a-short-moment-and-the-disappears-again/74851

Maybe that gives an idea about the possible cause ...

Ralf

**Comment by mranderson56** [comment]
Thanks @ralfbecker ! Exactly the same issue.

**Comment by EnCz** [comment]
@ralfbecker any JS errors in the developer console when reproducing this error in e.g. Chrome ?

**Comment by johnsyd** [comment]
@EnCz I have the same issue of the admin immediately disappearing when invoked. I am getting no js errors. I am running in an iFrame FYI.

**Comment by ralfbecker** [comment]
Only JS error I have in the console is a not loadable Favicon, as my Rocket.Chat runs under /rocketchat and the manifest states it should be from /assets/favicon_192.png (missing /rocketchat prefix). But I don't think this is an issue, as it happens on first load, now when I click on the administration.

We also embed RC in an iframe, but I can reproduce the problem in a regular tab too. Thought roughly one out of ten tries I get the administration after reloading the whole page (without being redirected back to home). When that happens the first (Info) paragraph stays on the top, even when I select an other part of administration. Not sure that is related or an other glitch.

All our users use OAuth for authentication, thought I don't see how this should affect. 

These is what happens on the websocket, when I click on Administration:
```
["{\"msg\":\"method\",\"method\":\"instances/get\",\"params\":[],\"id\":\"19\"}"]
["{\"msg\":\"updated\",\"methods\":[\"19\"]}"]
["{\"msg\":\"result\",\"id\":\"19\",\"result\":[]}"]
```
The first is the request to the server, the two others are responses.

Ralf

**Comment by ggazzo** [comment]
@ralfbecker please try to access by url `https://yourserver/admin/users`... maybe the problem is related with the info page...

**Comment by ralfbecker** [comment]
Redirects to /rocketchat/home immediatly :(

Ralf

**Comment by johnsyd** [comment]
FYI: I have a manual install on CentOS and, thankfully, I have not put RC into production yet. I spun up a new server and installed the previous version. To get the 'bundle' package for a previous version just substitute the version number for the 'latest' in the download url: 
curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz -> curl -L https://releases.rocket.chat/3.3.3/download -o /tmp/rocket.chat.tgz

**Comment by CarstenHager** [comment]
i have the same error, no error in the console

https://recordit.co/xBuNtF0bIo

**Comment by hnategh** [comment]
I have tested this with 3.4.0 and 3.4.1, same issue happens and after looking deeper into it I found out that the following condition goes wrong in https://github.com/RocketChat/Rocket.Chat/blob/53effb32d41ee3df34fb77a2973e565d1b517f61/client/admin/sidebar/AdminSidebar.js#L180
What I have as currentPath is "/rocketchat/admin/info" then obviously the condition  currentPath.startsWith('/admin/') is false since the path is not starting with /admin/. Any major changes on path navigation with this new version?

**Comment by ralfbecker** [comment]
Ok, so to reproduce it, you have to run Rocket.Chat with a path-prefix, like /rocketchat/ which we use.
