### ISSUE TITLE
System restart required after upload MIME type change

### ISSUE THREAD

**Issue by ferrolux** [RocketChat/Rocket.Chat#1811]
Hello,

I wanted to add zip files to the accepted media types and added "application/*" to the comma separated list in the admin file-upload dialog. Yet i still get the following error while i see the upload dialog before.

![image](https://cloud.githubusercontent.com/assets/9134501/12129405/b5067a9e-b403-11e5-979c-d4691b5be7d5.png)

**Comment by k0nsl** [comment]
Did you try restarting the instance after changing the accepted media types?

**Comment by ferrolux** [comment]
Adding the mime and restarting the server did the trick

**Comment by Sing-Li** [comment]
I do believe we want to ensure that changing settings never require reboot to take effect.  

If not, please close again.

**Comment by marceloschmidt** [comment]
Yes, we want to ensure that. There's an open issue for tracking those: #1492
