### ISSUE TITLE
[Information Disclosure] Users avatars names could lead to sensitive information leak

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#18117]
### Description:

In Rocket Chat deployments where **users are imported from LDAP** (for example Microsoft Active Directory) user avatar names could lead to LDAP information disclosure - **AD samAcconuntName could be guessed**.
User avatar URL in Rocket Chat has **no protection or authorization**, so malicious user can easy pick up AD usernames.
When username is **valid** (for example https://open.rocket.chat/avatar/ankar84) user get **proper avatar** (photo)
When username is **invalid** (for example https://open.rocket.chat/avatar/invaliduser) user get **generated SVG** (colored square with some symbol - user initial)
So, malicious user **can get users photos and AD usernames**, which is a security Information Disclosure issue.

To fix that issue I propose 2 options:
1. Use for user avatar name **not username**, but for example Rocket.Chat **internal ID** (**userId**). **userId** is pretty abstract
2. Use some kind of **protection** to /avatar/ URL. In that case it is very important not to broke avatar appearance in Rocket.Chat and other systems like Jitsi.

### Steps to reproduce:

1. Malicious user start brute force attack to URLs like `https://open.rocket.chat/avatar/[brute forced string]`
2. Malicious user gets AD usernames and users photos

### Expected behavior:

Malicious user can't brute force avatars of Rocket Chat users

### Actual behavior:

Malicious user can brute force avatars of Rocket Chat users

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1 (I believe it's applied to 3.4.0 too)
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 83
- Operating System: Windows 10

### Additional context

If Rocket Chat team will decide to protect /avatar/ URL, please don't hurt avatars for other systems like Jitsi.

**Comment by jschanz** [comment]
We discussed this behavior a few minutes before ... You could disable unauthorized access to the avatar url as admin in server settings.

![grafik](https://user-images.githubusercontent.com/5750462/87013061-63320b00-c1ca-11ea-8561-ccaa897e0d09.png)

Access is forbidden now

![grafik](https://user-images.githubusercontent.com/5750462/87013180-89f04180-c1ca-11ea-84e0-5a225aa71810.png)

**Comment by ankar84** [comment]
Closed thanks to @jschanz
