### ISSUE TITLE
Error 400: Push Notifications Not Working for iOS

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#18124]
### Description:

Push Notification for iOS result in an error: 400

### Steps to reproduce:

1. Go to 'PUSH in the administration section'
2. Add 'APN Dev and APN Pro Certs and Keys'
3. Send a test push notification and receive and error in debug

### Expected behavior:

Receive a push notification to my iOS device

### Actual behavior:

Debug Log:

Push _ debug send message "@John" to userId somehGwwHnDADeoj6
Push _ debug send to token {
  apn: '33022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959e'
}
Push _ debug send to token {
  apn: '33022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959e'
}
Push _ debug Sent message "@John" to 1 ios apps 0 android apps
Push _ debug GUIDE: The "appTokensCollection" - No GCM clients have registered on the server yet...
Push _ debug Got error code 400 for token 33022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959e
Push _ debug Removing token 33022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959e

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Linux (Ubuntu)
- Deployment Method: Manual (Baremetal)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14.0
- MongoDB Version: v4.0.19

### Client Setup Information

- Desktop App or Browser Version: Chrome (latest)
- Operating System: Mac OSX 10.15.5

### Additional context

Push notification work great on Android. Also I test both the dev.cer and production.cer via openssh. They return 0 status "ok"

openssl s_client -connect gateway.sandbox.push.apple.com:2195  -cert PushChatCert.pem -key PushChatKey.pem 
https://github.com/raix/push/blob/v3.x/docs/IOS.md

### Relevant logs:

Push _ debug Got error code 400 for token 33022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959e

**Comment by ntfchris** [comment]
Have you changed the private key's p12 to pem?

**Comment by Syirrus** [comment]
@ntfchris I did. I exported individually the private keys for production and development APN. Then I used the following commands to convert the p12 keys respectively to pem.

FOR DEV PEM
openssl x509 -in aps_development.cer -inform der -out DevPushCert.pem
openssl pkcs12 -nocerts -out DevPushKey.pem -in yourP12File.p12

FOR PRODUCTION PEM
openssl x509 -in aps.cer -inform der -out PushCert.pem
openssl pkcs12 -nocerts -out PushKey.pem -in yourP12File.p12

I even set the passwords as instructed to do so.

**Comment by ntfchris** [comment]
@Syirrus  For my case I put only the pem format of p12 to all four boxes.
no need to take care of the .cer to .pem

**Comment by hadiidbouk** [comment]
Same problem, @ntfchris did you solve it?

**Comment by ntfchris** [comment]
> Same problem, @ntfchris did you solve it?

Yes, I change the cert and p12 into pem form and copy the text in pem to admin panel
