### ISSUE TITLE
Download "My Data" second time

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#18137]
### Description:
We are testing the function "Download my Data". Yesterday it works and I get a E-Mail to download the data. After that and today I would to export the data again, because there are many new conversations, that would I save. 
Then I click on "Download My Data" I get the message: "Your data file was already generated. Click here to download it."
Then I click on the link I get the data from yesterday again but no new data. How can I get new data? 

### Steps to reproduce:

1. My Account
2. Preferences
3. Download My Data (HTML)
4. Download the data. 
5. Write some new conversations
6. Do 1-4 again

### Expected behavior:
Get the full data actually.

### Actual behavior:
Get only the data from my first export

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Client 2.17.7
- Operating System: Windows 10

### Relevant logs:
eteor ➔ method requestDataDownload -> userId: xxxxxxxxxxxx, arguments: [{"fullExport":false}]

**Comment by pierre-lehnen-rc** [comment]
You can request data once every 24 hours.
