### ISSUE TITLE
Change "GCM API Key" in Push for "Firebase Server Key"

### ISSUE THREAD

**Issue by danfelbm** [RocketChat/Rocket.Chat#18139]
### Description:

GCM was replaced long ago. However, the GCM locale string remains as the setting option for the API keys, when in fact, it requires the Firebase Server Key. 

I honestly think this can cause confusion to some people that don't have much experience with these deployments and are trying to set up push notifications. They may end up using the google-services.json API key instead of the server key in the firebase console.

### Steps to reproduce:

1. Go to admin
2. Click on Push
3. Go to Certificates and keys

### Expected behavior:

It should say "Firebase Server Key" instead of "GCM API Key"

### Actual behavior:

It says "GCM API Key" although it has been deprecated already.

**Comment by bkdev98** [comment]
+1 for this issue. It took me half a day to figure out it was Firebase Server Key instead of GCM API Key.
I will try to make a PR later when have more time.
