### ISSUE TITLE
WebRTC buttons not doing anything

### ISSUE THREAD

**Issue by haceru** [RocketChat/Rocket.Chat#1813]
Hello,

Most likely there is something I am missing, but please can you guide me on how to setup the WebRTC ? When in Direct Message for example, the buttons show up OK, but when I click on them nothing happens. I have checked the browser compatibiliy and settings with the online tool from the Wiki post, everything passed as described (tried on different computers, different browsers)

The Rocket.Chat instance is running behind a firewall; are there any extra ports requirements besides the main app port ?

Any suggestions would be greatly appreciated

Thank you

**Comment by IQ2022** [comment]
I have same issues, WebRTC doesnt work..

**Comment by marceloschmidt** [comment]
To be on the safe side, could you join https://demo.rocket.chat and give it a try on our instance? @IQ2022 is your instance also behind a firewall?

**Comment by haceru** [comment]
I have just tested the demo instance, with username edos.online and everything works OK

**Comment by haceru** [comment]
I found the answer .... 

740dbe125ddc1d6ed03fd91bbf0e5a15353024b3.js?meteor_js_resource=true:290 **getUserMedia() no longer works on insecure origins**. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

740dbe125ddc1d6ed03fd91bbf0e5a15353024b3.js?meteor_js_resource=true:290 NavigatorUserMediaError {}constraintName: ""message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."name: "PermissionDeniedError"__proto__: NavigatorUserMediaErrorconstraintName:

**Comment by haceru** [comment]
As an update, I managed to install the https://letsencrypt.org/ client on a NGINX server and thus my Rocket.Chat instance runs on a secure site, with WebRTC fully functional. I suppose you can update the Wiki to let others know about the HTTPS requirement and the free workaround (even though still in public beta)

**Comment by engelgabriel** [comment]
To be done as part of #933

**Comment by IQ2022** [comment]
any wiki's on how to enable https (via NGIX) on dockers?

**Comment by capensisma** [comment]
@haceru in the wiki it is told that you need to use https and *ssl* for the best results!!

@IQ2022 read the wiki in how to install ssl on nginx!

Here it is [Docker Ubuntu with Nginx SSL and Hubot](https://github.com/RocketChat/Rocket.Chat/wiki/Docker---Ubuntu-with-Nginx-SSL-and-Hubot)

**Comment by haceru** [comment]
@capensisma I am not a native English speaker, but to my knowledge "best results" is not similar to "only". If you read the WebRTC documentation, it says that it "only" works on https and ssl, not "gives best results"

**Comment by capensisma** [comment]
@haceru bro it works on none http but you will get a lot of problems like the webrtc things or on other things...
you can try running it on your localhost and see!

Anyway, anyone should use HTTPS to have a secure app with the best results.

**Comment by geekgonecrazy** [comment]
closing in favor of #933 lets track webrtc progress there.
