### ISSUE TITLE
Omnichannel "LivechatSession" webhook not working

### ISSUE THREAD

**Issue by johncordeiro** [RocketChat/Rocket.Chat#18132]
### Description:

Version 3.4.0 was introduced and the webhook call for closed omnichannel room is not working at all, the closing message is working but the `LivechatSession` type is never triggered.

### Steps to reproduce:

1. Omnichannel > Webhooks
2. Setup any URL and check "Send Request on Chat Close"
3. Close any Livechat room

### Expected behavior:

Receiving a webhook request with type "LivechatSession"

### Actual behavior:

No closing request received.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Windows
- Deployment Method: docker
- Number of Running Instances: 2 
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.18

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: Windows

**Comment by lucams** [comment]
Me too. :-(

**Comment by renatobecker** [comment]
This issue has already been fixed and it's available on our latest release 3.4.1 -> https://github.com/RocketChat/Rocket.Chat/pull/18102.
