### ISSUE TITLE
Audio and video don't work on clients

### ISSUE THREAD

**Issue by joubertredrat** [RocketChat/Rocket.Chat#1814]
Hi guys,

I'm testing Rocket Chat here to replace Skype and I liked a lot, but I'm testing audio and video chat here and both don't work.

I tried on all browsers, desktop and android clients and don't work.

On demo Rocket Chat I have users extreme-go-t1 and extreme-go-t2. The conversation starts up, extreme-go-t2 can see your cam, but extreme-go-t1 can't, on audio chat is same issue.

**Comment by Sing-Li** [comment]
@joubertredrat  - first, with Firefox or Chrome browser - please check the machines on both side against this:    https://test.webrtc.org

The machines *must* pass all tests to be compatible.

**Comment by joubertredrat** [comment]
Hi @Sing-Li 

Firefox or Chrome need to pass in all tests to desktop clients and mobile clients work too? How to test this on desktop and android client?

Firefox linux = All pass (ipv6 ignore)
Chrome linux = All pass (ipv6 ignore)

Firefox windows = All pass (ipv6 ignore)
Chrome windows = Fail on Relay connectivity (ipv6 ignore)

Firefox android = Fail on Check resolution 640x480 and Check resolution 1280x720.
Chrome android = Fail on Check resolution 320x240, other resolutions works fine.

**Comment by Sing-Li** [comment]
@joubertredrat  Using TWO machines that are in the set of:

Firefox linux = All pass (ipv6 ignore)
Chrome linux = All pass (ipv6 ignore)

.. and are NOT on the same LAN, but connected over the Internet.  Create an account and logon to :+1: 

https://demo.rocket.chat

... and try video call.

**Comment by joubertredrat** [comment]
Hi @Sing-Li 

I'm using two machines on same LAN, but using 2 separated internet routes, but I will provide a test with total separated machines.

On my smartphone, I'm using 3G and worked fine.

About your comments, isn't good idea to add to documentation?
Thanks.

**Comment by capensisma** [comment]
you need to change and try other Turn Servers?!

**Comment by MartinSchoeler** [comment]
@joubertredrat is this still a issue?

**Comment by joubertredrat** [comment]
@MartinSchoeler for me this issue can be closed, I didn't do any more tests.
