### ISSUE TITLE
"false" is appened to all jitsi URLs

### ISSUE THREAD

**Issue by fthiery** [RocketChat/Rocket.Chat#18140]
### Description:

I wanted to deploy a custom configuration override to make jitsi calls audio-only by default (see #17950) ; this was achieved (in 3.4.0) by adding `#config.startAudioOnly=true` to the custom jisti room suffix option, but it seems that now "false" is added to the url now...  Which makes this feature unusable.

### Steps to reproduce:

Launch a jitsi call (with jwt disabled)

### Expected behavior:

url should be https://meet.jit.se/RANDOMID

With `#config.startAudioOnly=true` as the jisti room suffix, the url should be https://meet.jit.se/RANDOMID#config.startAudioOnly=true

### Actual behavior:

url is https://meet.jit.se/RANDOMIDfalse

With `#config.startAudioOnly=true` as the jisti room suffix, the url is https://meet.jit.se/RANDOMID#config.startAudioOnly=truefalse

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: chromium
- Operating System: Linux

### Additional context

A workaround is to add `&fake=` to the room suffix, for example `#config.startAudioOnly=true&fake=`

### Relevant logs:

Nothing special

**Comment by martinszy** [comment]
Thanks for the workaround. In my case I added `?fake=` because it didn't work with the `&`
