### ISSUE TITLE
API Login 

### ISSUE THREAD

**Issue by kreuzebek** [RocketChat/Rocket.Chat#1815]
I can't login using api. 

curl -d "password=senha2016&user=usuario01"  http://md.xxxx.com.br/api/login
Using Nginx, return time out.

curl -d "password=senha2016&user=usuario01"  http://localhost:3000/api/login
Using directly return:
curl: (52) Empty reply from server

 curl http://localhost:3000/api/version
/api/version works! Return:
{
  "status": "success",
  "versions": {
    "api": "0.1",
    "rocketchat": "0.5"
  }

Forgot something?

**Comment by rodrigok** [comment]
It is working for me.

Can you execute `curl http://localhost:3000/api/info` and paste the result here?

**Comment by kreuzebek** [comment]
curl http://localhost:3000/api/info
{
  "version": "0.11.0",
  "compile": {
    "date": "2015-12-30T15:51:53.829Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 5065953280,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2828",
    "branch": "develop",
    "tag": ""
  },
  "commit": {
    "hash": "147ce2d626a37c462de8592c39d2d8ca54e4067e",
    "date": "Wed Dec 30 13:28:37 2015 -0200",
    "author": "Marcelo Schmidt",
    "subject": "Button to test SMTP settings; No need to reload server for SMTP settings to take effect; Closes #1246 Checks SMTP Settings in #1492"
  },
  "tag": "v0.11.0",
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": true,
    "version": "GraphicsMagick 1.3.20 2014-08-16 Q8 http://www.GraphicsMagick.org/\nCopyright (C) 2002-2014 GraphicsMagick Group.\nAdditional copyrights and licenses apply to this software.\nSee http://www.GraphicsMagick.org/www/Copyright.html for details.\n\nFeature Support:\n  Native Thread Safe       yes\n  Large Files (> 32 bit)   yes\n  Large Memory (> 32 bit)  yes\n  BZIP                     yes\n  DPS                      no\n  FlashPix                 no\n  FreeType                 yes\n  Ghostscript (Library)    no\n  JBIG                     yes\n  JPEG-2000                yes\n  JPEG                     yes\n  Little CMS               yes\n  Loadable Modules         no\n  OpenMP                   yes (201307)\n  PNG                      yes\n  TIFF                     yes\n  TRIO                     no\n  UMEM                     no\n  WebP                     no\n  WMF                      yes\n  X11                      yes\n  XML                      yes\n  ZLIB                     yes\n\nHost type: x86_64-pc-linux-gnu\n\nConfigured using the command:\n  ./configure  '--build' 'x86_64-linux-gnu' '--enable-shared' '--enable-static' '--enable-libtool-verbose' '--prefix=/usr' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--docdir=${prefix}/share/doc/graphicsmagick' '--with-gs-font-dir=/usr/share/fonts/type1/gsfonts' '--with-x' '--x-includes=/usr/include/X11' '--x-libraries=/usr/lib/X11' '--without-dps' '--without-modules' '--without-frozenpaths' '--with-perl' '--with-perl-options=INSTALLDIRS=vendor' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-Wall -g -fno-strict-aliasing -O2' 'LDFLAGS=' 'CXXFLAGS=-Wall -g -fno-strict-aliasing -O2'\n\nFinal Build Parameters:\n  CC       = gcc -std=gnu99\n  CFLAGS   = -fopenmp -Wall -g -fno-strict-aliasing -O2 -Wall -pthread\n  CPPFLAGS = -I/usr/include/X11 -I/usr/include/freetype2 -I/usr/include/libxml2\n  CXX      = g++\n  CXXFLAGS = -Wall -g -fno-strict-aliasing -O2 -pthread\n  LDFLAGS  = -L/usr/lib/X11 -L/usr/lib -L/usr/lib\n  LIBS     = -ljbig -llcms2 -ltiff -lfreetype -ljasper -ljpeg -lpng12 -lwmflite -lXext -lSM -lICE -lX11 -llzma -lbz2 -lxml2 -lz -lm -lgomp -lpthread\n"
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-05 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib\n\n"
  }
}

**Comment by rodrigok** [comment]
@kreuzebek I tested your version and the problem happened to me.

But the latest stable and develop versions are working ok, can you update?

As the latest versions are working I will close this issue.

**Comment by kreuzebek** [comment]
@rodrigok I'm using Docker tagged Develop, and this tag no longer exists. Using tag "latest" works fine. Thanks!

**Comment by rodrigok** [comment]
@kreuzebek which docker are you using? This one https://hub.docker.com/r/rocketchat/rocket.chat/tags/?

**Comment by kreuzebek** [comment]
@rodrigok  This one:
https://hub.docker.com/r/library/rocket.chat/tags/

**Comment by rodrigok** [comment]
@kreuzebek this one is the official image from docker, is a little bit outdated, we are working to solve this.

You can use our own image https://hub.docker.com/r/rocketchat/rocket.chat/tags/ that is always up to date.

**Comment by tuananhhedspibk** [comment]
How can i start rocketchat/rocket.chat images ? Thanks, when i run it by command 
docker run --name rocketchat -p 8000:3000 --env ROOT_URL=http://localhost --link db -d rocketchat/rocket.chat

-> it's suddenly exited 
Thanks you very much
