### ISSUE TITLE
Autoscroll in threads not scrolling down appropriately

### ISSUE THREAD

**Issue by sephwalker56** [RocketChat/Rocket.Chat#18150]
### Description:

Occasionally, autoscroll doesn't scroll all the way down to the bottom when in thread view. Instead, it scrolls to 1 line above the bottom. Often this occurs when typing a message that spans more than one line, or when sending a custom emoji that is larger than a standard emoji, or when sending a photo.

### Steps to reproduce:

1. Use thread view to discuss something.
2. After a while, you'll find the autoscroll doesn't scroll down all the way.

I'd love to give better reproduction steps, including a video, but this only happens _sometimes_ which makes it very difficult to give exact instructions. That said, it most frequently occurs when the messagebox expands upwards when adding a new line.

### Expected behavior:

Autoscroll goes down to the bottom of the message.

### Actual behavior:

Autoscroll goes down to one line above the bottom of the message.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Unraid OS
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Desktop App & Fully Updated Firefox & Chrome
- Operating System: Windows 10 64-bit, as well as others (every user on server is having this issue)

### Additional context

This has been an ongoing issue with threads for a while. In versions prior to 3.4.0, rather than scrolling to 1 line above the bottom, occasionally it would just stop scrolling. In addition, clicking into a thread resulted in being shown the top of the thread, not the bottom, and it would not scroll down appropriately. 3.4.0+ is much better, but it's still not great, because often people will double-post or not see a message because their autoscroll bugged up.

**Comment by sephwalker56** [comment]
If anyone wants to investigate this and can't reproduce it, I'm happy to provide video. That said, I've a feeling this is not an uncommon issue. If it does turn out to be, I'm happy to spend the time recording a video of it in action.

**Comment by MartinSchoeler** [comment]
@sephwalker56 Hello! By auto-scroll you mean when a new message is received or sent? If so, can you test again with the latest release, as I couldn't reproduce this issue? Thanks!

**Comment by HoldOffHunger** [comment]
Same issue here, thanks.

**Comment by jml4903** [comment]
I concur.  I've been a member of a SeekingAlpha Group which uses RocketChat and it does force you to click a down arrow next to "New Messages" to scroll.  

Would be beyond lovely if there was a simple option would, indeed, just scroll it automatically with new messages.
