### ISSUE TITLE
Deployment error: Direct installation of an App is disabled

### ISSUE THREAD

**Issue by SimonTheCat** [RocketChat/Rocket.Chat#18153]
### Description:

Can't deploy self-created app.

### Steps to reproduce:

```
~/zero# rc-apps deploy --url http://localhost:3000 --username rocket_admin --password password123
packaging your app... packaged!
deploying your app... !
    Error: Deployment error: Direct installation of an App is disabled.

```
### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.0
- Operating System: Debian 10
- Deployment Method: https://docs.rocket.chat/installation/manual-installation/debian

### Additional context

How to enable installation apps for server?

**Comment by clebsonsantos** [comment]
I'm with the same problem. 

`   Starting App Deployment to Server

   Getting Server Info... ✓
[info] using TypeScript v4.5.4
   Packaging the app... ✓
   Uploading App... ✖
 ›   Error:    ⟿  Error: Deployment error: Direct installation of an App is disabled.`
