### ISSUE TITLE
Custom OAuth stopped working with 3.4(.1?)

### ISSUE THREAD

**Issue by awunder** [RocketChat/Rocket.Chat#18163]
### Description:

version 3.4(.1?) kills custom oauth, the remote oauth service throws an error:

"error": "redirect_uri_mismatch",
"error_description": "The redirect URI provided is missing or does not match",
"error_uri": "http://tools.ietf.org/html/rfc6749#section-3.1.2"

the entire setup worked fine for years (before 3.4)
### Steps to reproduce:

just try to authenticate via oauth

### Expected behavior:

it works

### Actual behavior:

it doesnt.. error is:

"error": "redirect_uri_mismatch",
"error_description": "The redirect URI provided is missing or does not match",
"error_uri": "http://tools.ietf.org/html/rfc6749#section-3.1.2"

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Ubuntu 18.04
- Deployment Method: direct install
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: 12.16
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: chrome / firefox
- Operating System: win / linux

### Relevant logs:

there is nothing in the logs.

**Comment by aleadco** [comment]
Please check this https://github.com/RocketChat/Rocket.Chat/issues/18128#issuecomment-654416625

**Comment by awunder** [comment]
thx @aleadco but it doesnt fix it, unfortunately

**Comment by rodrigok** [comment]
@awunder can I have access to your instance or can we chat at https://open.rocket.chat/direct/rodrigo.nascimento?

Thanks

**Comment by awunder** [comment]
it seems to have been a layer 8 issue.. when trying to login from an http connection with the redirect url set to https it obviously complains..

sry guys and shout out to @rodrigok for his help
