### ISSUE TITLE
Not bug:But it's an important thing about RC,  notification is not displayed on windows 

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#18174]
### Steps to reproduce:

1.see the picture

### Expected behavior:

display notification window

### Actual behavior:

1.see the picture

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
Operating System:  ubuntu 
- Deployment Method: docker 
- Number of Running Instances: 11
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.*
- MongoDB Version:4.* 

### Client Setup Information

- Desktop App or Browser Version: chrome 
- Operating System:window 10

### Additional context
![image](https://user-images.githubusercontent.com/66900278/86585667-67d3a500-bfb9-11ea-98d2-39ddc4f6b78b.png)

**Comment by sephwalker56** [comment]
As far as I am aware, if you are running in a browser, your browser controls the notifications and doesn't show them with the Windows notification center. This is the behaviour that I see when I receive notifications in RocketChat on both Firefox and Chrome. If I use the Desktop RocketChat app, then I receive notifications in the Windows notification center, which is what your image is pointing to. But again, as far as I am aware, Chrome and Firefox do not use the Windows notifications, they display custom notifications that are written in JavaScript.

**Comment by codeneno** [comment]
@sephwalker56 Hi，sir I met this issue only once(ONLY ONE DAY),I think it's windows10's problem.
occurs: Desktop RocketChat app & Chrome
