### ISSUE TITLE
Not possible to activate/deactivate/delete user from GUI

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#18175]
### Description:

In 3.4.0 version is not possible to activate/deactivate/delete user from "Users" in administration panel. Detail on pictures below.

### Steps to reproduce:

1. Go to "Adinistration -> User" and select user
2. Is not possible activate/deactivate/delete

### Expected behavior:

Possible to activate/deactivate/delete

### Actual behavior:

Is not possible activate/deactivate/delete

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 25
- DB Replicaset Oplog: YES
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.16

### Additional context

Version 3.4.0 (no option to activate/deactivate/delete user)
![image](https://user-images.githubusercontent.com/50440047/86589141-5d9bb180-bf8d-11ea-86fa-88e60a7d596f.png)

Version 3.0.12 
![image](https://user-images.githubusercontent.com/50440047/86589196-83c15180-bf8d-11ea-8383-234e0de4be90.png)

**Comment by MartinSchoeler** [comment]
Hello @emikolajczak This seems to be working on 3.4.1 

<img width="373" alt="Screen Shot 2020-07-06 at 11 01 18 AM" src="https://user-images.githubusercontent.com/20868078/86601819-2e2e7a00-bf78-11ea-8dad-95685c418fcd.png">

Can you update and try testing out again? If you experience this again please reopen this. Thanks!

**Comment by xkungfu** [comment]
same issue. why closed?
