### ISSUE TITLE
When set to debug, debugger prints out entire byte array for file upload

### ISSUE THREAD

**Issue by jpopesculian** [RocketChat/Rocket.Chat#1817]
If you set `Debug_Level` to `debug`, on a file upload, the debugger prints out the entire byte array argument in the `ufsWrite` method and hangs up the server trying to print thousands of lines into the stdout. I can send a pull request that either specifically limits the `ufsWrite` from printing or limits arrays over a certain size from printing in the terminal.

**Comment by sampaiodiego** [comment]
I think the best approach would be if `ufsWrite` doesn't display the file data arrays..

**Comment by sampaiodiego** [comment]
fixed by #1820
