### ISSUE TITLE
Details link in the README goes to a 404.

### ISSUE THREAD

**Issue by steveharman** [RocketChat/Rocket.Chat#18178]
### Description:

"NEW! Rocket.Chat Moving to a Single Codebase" results in a 404 at https://github.com/RocketChat/Rocket.Chat

### Steps to reproduce:

1. Visit https://github.com/RocketChat/Rocket.Chat
2. Click on "NEW! Rocket.Chat Moving to a Single Codebase"
3. Click on "Details"

### Expected behavior:

Details

### Actual behavior:

404 at https://rocket.chat/2020/03/28/moving-to-a-single-codebase/

### Server Setup Information:

n/a

### Client Setup Information

n/a - well, Firefox Mac

**Comment by dudanogueira** [comment]
Hi! If you landed here wanting to know more about the mono repo changes we are doing, check out this contents:

Link to the refered blog post:
https://rocket.chat/blog/rocket-chat-is-moving-to-a-single-codebase

Also, we had a Community Open Call about this monorepo change here:

https://www.youtube.com/watch?v=zhPF9LpTR94
