### ISSUE TITLE
3.4.1 not working

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#18189]
### Description:

3.4.1 is not working in any way for me. When deploying through docker-compose using an existing DB I'm met with a white box when trying to load the app. See screenshot below.

I've also tried starting a fresh development server without any prior data and the app is struck on the loading screen.

### Steps to reproduce:

1. Update to 3.4.1.
2. Start the app either through docker-compose or the development server.

### Expected behavior:

It should load the app.

### Actual behavior:

Screenshot of deployed app through docker-compose with console log included:
![rc-error](https://user-images.githubusercontent.com/36848317/86626960-c9027500-bfc7-11ea-9fe0-e8c169e5c2d1.PNG)

Server log:
`rocketchat_1          | API ➔ debug POST: /api/v1/method.callAnon/loadLocale
rocketchat_1          | Meteor ➔ method loadLocale -> userId: undefined, arguments: ["sv"]
rocketchat_1          | API ➔ debug Success {
rocketchat_1          |   statusCode: 200,
rocketchat_1          |   body: {
rocketchat_1          |     message: `{"msg":"result","id":"2","result":"//! moment.js locale configuration\\n//! locale : Swedish [sv]\\n//! author : Jens Alm : https://github.com/ulmus\\n\\n;(function (global, factory) {\\n   typeof exports === 'object' && typeof module !== 'undefined'\\n       && typeof require === 'function' ? factory(require('../moment')) :\\n   typeof define === 'function' && define.amd ? define(['../moment'], factory) :\\n   factory(global.moment)\\n}(this, function (moment) { 'use strict';\\n\\n\\n    var sv = moment.defineLocale('sv', {\\n        months : 'januari_februari_mars_april_maj_juni_juli_augusti_september_oktober_november_december'.split('_'),\\n        monthsShort : 'jan_feb_mar_apr_maj_jun_jul_aug_sep_okt_nov_dec'.split('_'),\\n        weekdays : 'söndag_måndag_tisdag_onsdag_torsdag_fredag_lördag'.split('_'),\\n        weekdaysShort : 'sön_mån_tis_ons_tor_fre_lör'.split('_'),\\n        weekdaysMin : 'sö_må_ti_on_to_fr_lö'.split('_'),\\n        longDateFormat : {\\n            LT : 'HH:mm',\\n            LTS : 'HH:mm:ss',\\n            L : 'YYYY-MM-DD',\\n            LL : 'D MMMM YYYY',\\n            LLL : 'D MMMM YYYY [kl.] HH:mm',\\n            LLLL : 'dddd D MMMM YYYY [kl.] HH:mm',\\n            lll : 'D MMM YYYY HH:mm',\\n            llll : 'ddd D MMM YYYY HH:mm'\\n        },\\n        calendar : {\\n            sameDay: '[Idag] LT',\\n            nextDay: '[Imorgon] LT',\\n            lastDay: '[Igår] LT',\\n            nextWeek: '[På] dddd LT',\\n            lastWeek: '[I] dddd[s] LT',\\n            sameElse: 'L'\\n        },\\n        relativeTime : {\\n            future : 'om %s',\\n            past : 'för %s sedan',\\n            s : 'några sekunder',\\n            m : 'en minut',\\n            mm : '%d minuter',\\n            h : 'en timme',\\n            hh : '%d timmar',\\n            d : 'en dag',\\n            dd : '%d dagar',\\n            M : 'en månad',\\n            MM : '%d månader',\\n            y : 'ett år',\\n            yy : '%d år'\\n        },\\n        ordinalParse: /\\\\d{1,2}(e|a)/,\\n        ordinal : function (number) {\\n            var b = number % 10,\\n                output = (~~(number % 100 / 10) === 1) ? 'e' :\\n                (b === 1) ? 'a' :\\n                (b === 2) ? 'a' :\\n                (b === 3) ? 'e' : 'e';\\n            return number + output;\\n        },\\n        week : {\\n            dow : 1, // Monday is the first day of the week.\\n            doy : 4  // The week that contains Jan 4th is the first week of the year.\\n        }\\n    });\\n\\n    return sv;\\n\\n}));"}`,
rocketchat_1          |     success: true
rocketchat_1          |   }
rocketchat_1          | }
rocketchat_1          | Meteor ➔ publish null -> userId: null, arguments: []
rocketchat_1          | TIMEOUT QUERY OPERATION {
rocketchat_1          |   observeKey: '{"ordered":false,"collectionName":"rocketchat_settings","selector":{"_id":"Accounts_OAuth_Dolphin_URL"},"options":{"transform":null}}',
rocketchat_1          |   writesToCommitWhenWeReachSteadyLength: 0,
rocketchat_1          |   cursorDescription: '{"collectionName":"rocketchat_settings","selector":{"_id":"Accounts_OAuth_Dolphin_URL"},"options":{"transform":null}}'
rocketchat_1          | }
rocketchat_1          | Exception in setInterval callback: SwitchedToQuery {}
`

Screenshot of app started with development server, including console error log:
![rc-error2](https://user-images.githubusercontent.com/36848317/86627931-63af8380-bfc9-11ea-8392-f098e9aeba3f.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Ubuntu
- Deployment Method: Docker compose and RC development server
- Number of Running Instances: 1
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

### Relevant logs:

See the "Actual behavior".

**Comment by rodrigok** [comment]
@cchbr can you change the setting `API_Use_REST_For_DDP_Calls` to false and check if solves your problem?

You can do it via database:
```
db.getCollection('rocketchat_settings').update({_id: 'API_Use_REST_For_DDP_Calls'}, {$set: {value: false}})
```

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/18128

**Comment by cchbr** [comment]
This is the response I get when attempting to change the setting:

**Comment by Dizzle397** [comment]
You have to go into the db.

```
$ mongo
rs01:PRIMARY> use rocketchat
rs01:PRIMARY> db.getCollection('rocketchat_settings').update({_id: 'API_Use_REST_For_DDP_Calls'}, {$set: {value: false}})
```

**Comment by cchbr** [comment]
Changing that setting solved it for me as well.

**Comment by TomaszDom** [comment]
This solves the issue, but this version is broken anyway, admin pages are inaccessible (upgrade/clean manual installation on Ubuntu 18.04 with correct mongo and node).

**Comment by adocampo** [comment]
@Dizzle397  That worked for me also, thank you a lot.

my admin settings are visible and accesible @TomaszDom,I'm on Debian 9

**Comment by rodrigok** [comment]
Version 3.4.2 is out and fixes this issue, please check it and let us know if you keep experiencing some problem.

I'll close this issue meanwhile.

Thanks
