### ISSUE TITLE
New integration is not working until re-enabled

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [RocketChat/Rocket.Chat#18197]
### Description:

It seems that due to wrong apparent of "Enabled" setting for integration, when I set up a new one and save, it's not working right away even though Enabled is ON. 

### Steps to reproduce:

1. Create new Integration (I checked ongoing only)
2. Expect it to work because it's Enabled 
3. Be surprised because it isn't.
4. Have you tried to turn it off and on again?
5. You are welcome.

### Expected behavior:

Integration with Enabled ON should be, in fact, enabled.

### Actual behavior:

Integration with Enabled ON isn't enabled, it just pretend to be.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: irrelevant
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: irrelevant
- NodeJS Version: irrelevant
- MongoDB Version: irrelevant

### Client Setup Information

- Desktop App or Browser Version: irrelevant
- Operating System: irrelevant

### Additional context

AFAIR it used to be disabled by default.

### Relevant logs:

No logs.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
