### ISSUE TITLE
Channel not loading after login

### ISSUE THREAD

**Issue by cchbr** [RocketChat/Rocket.Chat#18204]
### Description:

After a user has logged in, the channel does not load. It's stuck on the loader. I've had to do a manual fresh of the window for the channel to load the messages. This is the case both for guest and registered users.

### Steps to reproduce:

1. Visit a channel.
2. Log in as either a regular user or guest.
3. The channel messages does not load.

### Expected behavior:

The messages should be loaded and displayed.

### Actual behavior:

The loader is displayed indefinitely.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Ubuntu
- Deployment Method: Docker compose
- Number of Running Instances: 1
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Latest version of Firefox and Chrome.
- Operating System: Windows 10

### Relevant logs:

`rocketchat_1          | Meteor ➔ method setUsername -> userId: CJQkYvGafaYEthgvt, arguments: ["36178"]
mongo_1               | 2020-07-07T18:13:04.089+0000 I COMMAND  [conn5] command rocketchat.rocketchat_uploads command: aggregate { aggregate: "rocketchat_uploads", pipeline: [ { $group: { _id: "total", total: { $sum: "$size" } } } ], cursor: {}, lsid: { id: UUID("133fc897-c5ba-4c9f-be79-0d769346fdcf") }, $clusterTime: { clusterTime: Timestamp(1594145582, 1), signature: { hash: BinData(0, 0000000000000000000000000000000000000000), keyId: 0 } }, $db: "rocketchat" } planSummary: COLLSCAN keysExamined:0 docsExamined:176844 cursorExhausted:1 numYields:1381 nreturned:1 reslen:265 locks:{ Global: { acquireCount: { r: 2780 } }, MMAPV1Journal: { acquireCount: { r: 1390 } }, Database: { acquireCount: { r: 1390 } }, Collection: { acquireCount: { R: 1390 } } } protocol:op_msg 251ms
mongo_1               | 2020-07-07T18:13:04.100+0000 I COMMAND  [conn16] command rocketchat.users command: find { find: "users", filter: { username: { $regex: /^36178$/i } }, projection: { _id: 1 }, limit: 1, returnKey: false, showRecordId: false, lsid: { id: UUID("e61a62b3-2ba0-4338-8273-72051a7bf042") }, $clusterTime: { clusterTime: Timestamp(1594145582, 1), signature: { hash: BinData(0, 0000000000000000000000000000000000000000), keyId: 0 } }, $db: "rocketchat" } planSummary: IXSCAN { username: 1 } keysExamined:179186 docsExamined:0 cursorExhausted:1 numYields:1399 nreturned:0 reslen:214 locks:{ Global: { acquireCount: { r: 2800 } }, MMAPV1Journal: { acquireCount: { r: 1400 } }, Database: { acquireCount: { r: 1400 } }, Collection: { acquireCount: { R: 1400 } } } protocol:op_msg 209ms
rocketchat_1          | SyncedCron ➔ info Finished "Generate and save statistics".
mongo_1               | 2020-07-07T18:13:04.299+0000 I COMMAND  [conn7] command rocketchat.users command: find { find: "users", filter: { username: { $regex: /^36178$/i } }, projection: { _id: 1 }, limit: 1, returnKey: false, showRecordId: false, lsid: { id: UUID("e61a62b3-2ba0-4338-8273-72051a7bf042") }, $clusterTime: { clusterTime: Timestamp(1594145582, 1), signature: { hash: BinData(0, 0000000000000000000000000000000000000000), keyId: 0 } }, $db: "rocketchat" } planSummary: IXSCAN { username: 1 } keysExamined:179186 docsExamined:0 cursorExhausted:1 numYields:1399 nreturned:0 reslen:214 locks:{ Global: { acquireCount: { r: 2800 } }, MMAPV1Journal: { acquireCount: { r: 1400 } }, Database: { acquireCount: { r: 1400 } }, Collection: { acquireCount: { R: 1400 } } } protocol:op_msg 187ms
rocketchat_1          | Meteor ➔ method joinDefaultChannels -> userId: CJQkYvGafaYEthgvt, arguments: [null]
rocketchat_1          | Integrations ➔ Outgoing WebHook.debug Execute Trigger: userCreated
rocketchat_1          | Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: userCreated {
rocketchat_1          |   event: 'userCreated',
rocketchat_1          |   user: {
rocketchat_1          |     _id: 'CJQkYvGafaYEthgvt',
rocketchat_1          |     createdAt: 2020-07-07T18:12:54.759Z,
rocketchat_1          |     type: 'user',
rocketchat_1          |     status: 'online',
rocketchat_1          |     active: true,
rocketchat_1          |     _updatedAt: 2020-07-07T18:13:04.300Z,
rocketchat_1          |     roles: [ 'anonymous' ],
rocketchat_1          |     services: { resume: [Object] },
rocketchat_1          |     lastLogin: 2020-07-07T18:12:55.427Z,
rocketchat_1          |     statusConnection: 'online',
rocketchat_1          |     utcOffset: 2,
rocketchat_1          |     username: '36178'
rocketchat_1          |   }
rocketchat_1          | }
rocketchat_1          | Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: __any
rocketchat_1          | Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
`

**Comment by rasos** [comment]
Observed a similar behaviour with anonymous users on some instances https://github.com/RocketChat/Rocket.Chat/issues/16756

**Comment by cchbr** [comment]
This is still an issue on 3.4.2.
