### ISSUE TITLE
Bot can't invite user to private channel

### ISSUE THREAD

**Issue by desser-code** [RocketChat/Rocket.Chat#18208]
### Description:

I've created private channels and added the Rocket.Cat bot as an owner.
In my Role as an admin I'd like to add an user to a private channel with an direct message to the bot e.g:
(/invite @username privatechannelname) - Unfortunately it doesn't seem to work, rocket.cat returns "User can not be invited to Direct Messages".
Also i'd prefer if an admin has the option to invite a user directly to a private Channel witout being a member.

### Steps to reproduce:

1. Create a private channel
2. Add the Rocket.Cat bot as an owner
3. Try to invite an user with direct message to bot -> /invite @username privatechannelname

### Expected behavior:

Add user to channel member list.

### Actual behavior:

Rocket.Cat returns an error message: "User can not be invited to Direct Messages".

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Debian 9.12
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.2
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Linux and Windows

**Comment by sephwalker56** [comment]
/invite is a command that AFAIK is completely unrelated to Rocket.Cat. If you read the text describing /invite, it says: "Invite one user to join this channel" meaning, /invite @someuser will invite @someuser to the channel that you issued this command in, not a channel of your choice.

What you want is to go to the channel that you intend to invite @someuser to, and then type /invite @someuser. As long as this room isn't a DM and you have permission to invite them, it should do so.

Rocket.Cat, from what I can tell, simply reports back to you when you use commands, and messages admins on software upgrades.

Please do correct me if I'm wrong about the Rocket.Cat stuff, this is all to the best of my knowledge.

**Comment by desser-code** [comment]
yes you are right, however the user has the right to add other users to each private channel. But this doesn't work, the error message appears

**Comment by desser-code** [comment]
Can everyone open this again?
