### ISSUE TITLE
/tmp/ufs directory permissions of jalik:ufs-gridfs incorrect for my case

### ISSUE THREAD

**Issue by ericvrp** [RocketChat/Rocket.Chat#1821]
I installed Rocket.chat with mup on a DigitalOcean server. These were the created temp directory permissions: drwxr-xr-x 2 root root 4096 Jan 6 03:59 ufs

Rocket.Chat runs in this setup as meteoruser so could not write here. Not sure if this is a Rocket.chat or jalik-ufs bug

For those needing to fix the /tmp/ufs permissions (after each server reboot) in cases similar to mine:

su -
cd /tmp
chown meteoruser:meteoruser ufs
chmod og-rwx ufs

**Comment by ratan12rk** [comment]
I'm facing this same issue,

Thanks to @ericvrp for temporary solution.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Comment by dullahan8** [comment]
I figured out this issue. If ssh to my rocketchat server and mkdir /tmp/ufs, then uploads start working.

**Comment by hifihedgehog** [comment]
> This is still happening on version 1.2.1. If ssh to my rocketchat server and `mkdir /tmp/ufs` and `chown to rocketchat.rocketchat`, then uploads start working. Thank you @ericvrp

This issue still persists. Why?

**Comment by hifihedgehog** [comment]
Resolved. The issue arises if you already had created a previous RocketChat installation and in removing the rocketchat user, forget to remove the /tmp/ufs folder. If this folder is not deleted in the uninstall process, it will not be given permissions when you reinstall RocketChat. So you either (1) delete the folder /tmp/ufs prior to reinstalling or (2) set rocketchat as owner to the folder /tmp/ufs again.
