### ISSUE TITLE
Admin Panel Opening & Closing Quickly, Can't access in 3.4.1

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#18214]
### Steps to reproduce:

1. Install 3.4.1
2. Attempt to view admin panel
3. Admin panel open's and closes quickly, causing invalid json errors inconsole.

### Expected behavior:

Admin console to stay open.

### Actual behavior:

Admin panel opens and closes so quickly that you can not access any of the admin panel.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 2.16
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Operating System: Windows 10

### Relevant logs:

These are the console logs I get.

![Capture](https://user-images.githubusercontent.com/40190297/86980764-ba949480-c152-11ea-90cf-8f8773f3606e.PNG)

On the rare occasion that the admin panel does stay open, anything you open is spit screen like this. As you see, the Rocket Chat info never loads and the /api/v1/method.call/instances/get returns a 404 page.

![Capture2](https://user-images.githubusercontent.com/40190297/86980793-cc763780-c152-11ea-877b-b100388c6142.PNG)

**Comment by ggazzo** [comment]
are running under subdiretory?  the discarding messages should not be related...

**Comment by serviceman** [comment]
The discarded message errors have stopped once I applied the fixes that I posted at the end of this ticket. https://github.com/RocketChat/Rocket.Chat/issues/18128 

Still can't access the admin panel though. Info has been sent to Rocket Chat team via open.rocket.chat and they are helping me debug as much as I can from my end.

**Comment by TomaszDom** [comment]
This looks similar to https://github.com/RocketChat/Rocket.Chat/issues/18203

**Comment by serviceman** [comment]
This is nothing like #18203, that is in reference to missing packages, which this ticket is not. My ticket is a UI issue, not a missing packages issue.

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/18147
