### ISSUE TITLE
Admin > Users > Profile - buttons outside of screen in Polish Language (to long button text)

### ISSUE THREAD

**Issue by kolorafa** [RocketChat/Rocket.Chat#18219]
### Description:
Translation or layout error

When editing user, the 3dot menu is outside of screen because "Direct Message" button is probably to long in Polish Language.

You need to scroll that box to right or click on the right border to hit the button.
![obraz](https://user-images.githubusercontent.com/921517/87031515-86b57f80-c1e3-11ea-953b-175ecb68762d.png)

https://youtu.be/Wu6hFtRb0Ms

### Steps to reproduce:

1. Install rocketchat
2. Go to Admin
3. Go to Users
4. Click on user
5. Try to delete/activate user - don't see button as dots are outside screen, with barely visible scroll on bottom

### Expected behavior:

I think - Buttons go to second line, because other stuff like ellipsis on text button might result in strange result?

### Actual behavior:

don't see button as dots are outside screen, with barely visible scroll on bottom

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Linux
- Deployment Method: Docker

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: Linux

**Comment by UAnton** [comment]
Have same problem on Russian localization
