### ISSUE TITLE
Beta tarball "blue screen"

### ISSUE THREAD

**Issue by infinitnet** [RocketChat/Rocket.Chat#1822]
I wanted to test your live chat feature and therefore went ahead updating the code from the lastest stable tarball release to the beta tarball that you uploaded 5 hours ago. I restarted the the node server several times, cleared my browser cache and tried different browsers, but the result was the same:

On my workstation in every browser I'd just get a blue page, meaning just a blue background and nothing else. No errors in logs. Now the weird part is that while it didn't work in any browser, it did work fine with the Android app. I had to revert to the latest stable tarball and it worked again instantly (just like any other previous release).

**Comment by marceloschmidt** [comment]
We also experienced a failed deployment yesterday. Would you mind fetching the latest beta again and give it another try? Thanks.

**Comment by infinitnet** [comment]
I'm using the beta tarball from releases which doesn't seem to have been updated since I opened this report.

**Comment by marceloschmidt** [comment]
Ah, I see. Our beta release process is not working very well. I have just manually generated a new beta. You can download the new tarball in a few minutes.

**Comment by infinitnet** [comment]
Thanks but it's only showing the source code tarball so far, not the compiled release code tarball that it had before and that I'm using.

**Comment by geekgonecrazy** [comment]
Since this is related to a release long ago going to close.
