### ISSUE TITLE
[BUG] Changes in admin interface are discarded / not saved

### ISSUE THREAD

**Issue by alexander-potemkin** [RocketChat/Rocket.Chat#18228]
### Description:

Can't save role's names update - after the update & save the change is discarded

### Steps to reproduce:

1. Open Rocket.Chat admin
2. go to permissions
3. click on the pen sign next to the role name (to edit it)
4. enter new description value
5. click 'save', see 'saved successfully' message
6. click back to permissions, close it
7. after some time (like a day or two) see in the chats list, that the description is back to the original name, I gave it first time.

### Expected behavior:

My settings to preserve

### Actual behavior:

it's discarded after a while

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System:  Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.2
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: two latest desktop apps
- Operating System: MacOS Catalina

### Additional context

Can't see anything else to add, actually.

### Relevant logs:

Nothing in the logs

**Comment by alexander-potemkin** [comment]
I faced that again - I can't rename user, which is used for integration. I rename it, click save, see green message saying 'saved', and it's just ignored.

Script part of the form is not.

And I still can't rename the roles, as raised originally.

<img width="662" alt="Screenshot 2020-07-31 at 20 44 09" src="https://user-images.githubusercontent.com/2323840/89062143-981b2300-d36e-11ea-9668-351434dfa541.png">

**Comment by alexander-potemkin** [comment]
P.S. That is now on web interface, latest Rocket.Chat, latest Chrome.

**Comment by badkaktus** [comment]
Up. I also observe this problem.
