### ISSUE TITLE
OAuth and Iframe Authentication

### ISSUE THREAD

**Issue by Nenillo** [RocketChat/Rocket.Chat#18234]
### Description:

We are using Iframe SSO Authentication and we want to call the Google OAuth configured in RocketChat, the documentaion here https://docs.rocket.chat/guides/developer/iframe-integration/authentication#using-oauth-configured-on-rocket-chats-end says we can do that using postMessage:

```window.parent.postMessage({
  event: 'call-google-login',
  //  scopes:
  //  webClientId:
}, 'http://your.rocket.chat.url');
```

We tried this but it does nothing. Searched the source code and I don't see any reference to this. Is this implemented?

### Steps to reproduce:

1. Configure Iframe Authentication

2. Create a page with a button and make it call postMessage on click:

```
$(document).ready(function() {
    $('#google').on('click', function () {
    console.log('send event');
    window.parent.postMessage({
        event: 'call-google-login',
    }, 'https://our.chat.domain');
})
```

3. Click on the button, it does nothing, the console log gets printed

### Expected behavior:

Calls the RocketChat Google OAuth integration and logs the user in

### Actual behavior:

Does nothing

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Linux 3.13
- Deployment Method: docker image
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Chromium 83.0.4103.116
- Operating System: Ubuntu 20.04

**Comment by justincohan** [comment]
The docs appear to be outdated.

The actual command to login with google would look like this. But when using this the popup gets blocked.  

```
      document.getElementById('iframe').contentWindow.postMessage({
        externalCommand: 'call-custom-oauth-login',
        service: 'google'
      }, '*');
```
