### ISSUE TITLE
Undefined instead of "user Info" in 3.4.2

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#18243]
### Description:

When viewing the user info panel by clicking on a username in a channel, or by clicking members -> username, "undefined" appears instead of "User Info". This seems to only happen on my Iphone with Safari. IOS 13.5.1. This also happens at open.rocket.chat, but you can't see it unless you are viewing in landscape mode, due to the blue banner on top that covers it up.

<img width="414" alt="rocketchat" src="https://user-images.githubusercontent.com/40190297/87211779-1bee6c00-c2e9-11ea-85d0-db1eef531132.png">

### Steps to reproduce:

1. Enter Channel
2. Click a username from the list of people in the room, or by clicking a username in a message a user posted.
3. User Info panel shows "Undefined" instead of "User Info" with a back arrow.

### Expected behavior:

for navigation to work correctly, show "user info" and back arrow.

### Actual behavior:

Shows as undefined.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Centos
- Deployment Method: Tar
- Number of Running Instances: 6
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.16
- MongoDB Version:4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

![Capture](https://user-images.githubusercontent.com/40190297/87214623-50b7ee80-c2fc-11ea-8a77-76127374c1b3.PNG)

**Comment by dkoo761** [comment]
This bug is still happening in 3.7.1, however there is no longer an error in the console log.

**Comment by dkoo761** [comment]
It appears that 2 headers are overlapping each other with the incorrect header appearing on top.

A simple workaround for now is to hide the 2nd header on mobile screen sizes:

```
@media (max-width: 768px) {
  /* Hide incorrect header on flex tab for User Info */
  .messages-container-wrapper .contextual-bar__header {
    display: none;
  }
}
```
