### ISSUE TITLE
Blocked autofocusing on a form control in a cross-origin subframe. (Iframe Cross Issue)

### ISSUE THREAD

**Issue by usamamashkoor** [RocketChat/Rocket.Chat#18249]
Rocket Chat Version:  3.3.3
Node Version | v12.16.1
Mongo Version | 4.0.19
OS Release | 5.3.0-1023-aws
Created it using: PaaS for AWS
React App Url: https://front.ipyra.com/
API Backend Url: https://api.ipyra.com/
Rocket Chat Url: https://chat.ipyra.com/
Kindly note our front end is on a separate server and the backend is on a separate server and rocket chat is also on a separate server.

Hi, we are trying to integrate Rocket Chat into our Single Page Application built using React.js using Iframe Auth, But we are facing problems on integrating it, After user logs into our website we are logging the user inside the rocket chat to using Rest API of Rocket Chat using this URL **"https://chat.ipyra.com/api/v1/login"** and then we are getting the rocket chat user token, and then on the page, we are adding the Iframe, inside the iframe we are giving our chat general channel layout embed URL.

```

<iframe
      ref={getRef}
      src='https://chat.ipyra.com/channel/general?layout=embedded'
      onLoad={onIframeLoad}
      width="100%"
      height="350px"
      name="rocketChat"
      id="rocketChat"
/>
```

When the Iframe is loaded then we are sending the login token to the Iframe using postMessage API of the Iframe, I have tried two methods for sending the token but none of them worked out for us.
```
const onIframeLoad = () => {
    //Method 1
    iframeRef.contentWindow.postMessage({
      externalCommand: 'login-with-token',
      token: rocket_chat_auth_token
    }, '*')
    //Method 2   
    iframeRef.contentWindow.postMessage({
      event: 'login-with-token',
      loginToken: rocket_chat_auth_token
    }, 'https://chat.ipyra.com/')
}
```

but after we send these post messages with a login token to the IFrame, we are getting these messages inside the console.
`**Blocked autofocusing on a form control in a cross-origin subframe.**`

 we also got this message too.
**`Refused to display 'https://api.ipyra.com/api/rocket_chat_iframe_login' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`**

**Access to XMLHttpRequest at 'https://api.ipyra.com/api/sso' from origin 'https://chat.ipyra.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.**

**https://api.ipyra.com is our Node.js and Expess.js API Server** 

Here is Rocket Chat Admin panel Configuration: 

![Screenshot - 2020-07-12T183652 024](https://user-images.githubusercontent.com/8676339/87247764-25094580-c46f-11ea-8640-68b12421fda6.png)

also, can anyone let us know what is the purpose of 
**"Iframe URL" and "API URL" inside the Account => Iframe Settings** 

I have added the URLs and I have just written post methods for them inside my code.

Here are our general Settings, We have tried Following Option for the 
**Options to X-Frame-Options**
Options which we have tried
1)*
2)SAMEORIGIN
3)https://front.ipyra.com
4)Access-Control-Allow-Origin:  https://front.ipyra.com
But none of them worked for us

![Screenshot - 2020-07-12T184439 191](https://user-images.githubusercontent.com/8676339/87247861-c42e3d00-c46f-11ea-988b-1d1d40cb0da0.png)

We have also enabled the Iframe Integrations to.

![Screenshot - 2020-07-12T184812 596](https://user-images.githubusercontent.com/8676339/87247969-50d8fb00-c470-11ea-9ae7-e085aa631052.png)

Inside the Rest API, we have also enabled the CORS to.

![Screenshot - 2020-07-12T184940 083](https://user-images.githubusercontent.com/8676339/87248027-9dbcd180-c470-11ea-9099-71f1e5ed6c85.png)

But still, we are facing the above-mentioned errors.

kindly help us solving this issue.

**Comment by obonyojimmy** [comment]
On dashboard iframe integration settings you'd need to disable CORS , and you can use *sandbox* attribute on the `Iframe` tag to enable browser restricted privallage to the Iframe , https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
