### ISSUE TITLE
Blocked autofocusing on a form control in a cross-origin subframe. (Iframe Cross Issue)

### ISSUE THREAD

**Issue by usamamashkoor** [RocketChat/Rocket.Chat#18250]
### Server Setup Information:
Version of Rocket.Chat Server::  3.3.3
Operating System:Ubuntu
Node Version | v12.16.1
Mongo Version | 4.0.19
OS Release | 5.3.0-1023-aws
Deployment Method:: PaaS for AWS
Number of Running Instances:1
DB Replicaset Oplog:Enabled 

### Steps to reproduce:

1.    Implement Iframe Authentication
2.     Login the user using the rest api get the token from the api response
3.     Log in the user using Iframe post message api 
4.     Go back to RocketChat

### Expected behavior:
The user should be logged in to the Rocket App.

### Actual behavior:
The rocket Chat is giving us a cross error 
**tryLogin
Blocked autofocusing on a form control in a cross-origin subframe.**

### Additional context
React App Url: https://front.ipyra.com/
API Backend Url: https://api.ipyra.com/
Rocket Chat Url: https://chat.ipyra.com/
Kindly note our front end is on a separate server and the backend is on a separate server and rocket chat is also on a separate server.
Client Setup Information

    Desktop App or Browser Version: React App (Chrome) Latest
    Operating System: Ubuntu

### Relevant logs:
![Untitled](https://user-images.githubusercontent.com/8676339/87248441-dc538b80-c472-11ea-9ec3-60b4f3d1e5ca.png)

### Description:
Hi, we are trying to integrate Rocket Chat into our Single Page Application built using React.js using Iframe Auth, But we are facing problems on integrating it, After user logs into our website we are logging the user inside the rocket chat to using Rest API of Rocket Chat using this URL **"https://chat.ipyra.com/api/v1/login"** and then we are getting the rocket chat user token, and then on the page, we are adding the Iframe, inside the iframe we are giving our chat general channel layout embed URL.

```

<iframe
      ref={getRef}
      src='https://chat.ipyra.com/channel/general?layout=embedded'
      onLoad={onIframeLoad}
      width="100%"
      height="350px"
      name="rocketChat"
      id="rocketChat"
/>
```

When the Iframe is loaded then we are sending the login token to the Iframe using postMessage API of the Iframe, I have tried two methods for sending the token but none of them worked out for us.
```
const onIframeLoad = () => {
    //Method 1
    iframeRef.contentWindow.postMessage({
      externalCommand: 'login-with-token',
      token: rocket_chat_auth_token
    }, '*')
    //Method 2   
    iframeRef.contentWindow.postMessage({
      event: 'login-with-token',
      loginToken: rocket_chat_auth_token
    }, 'https://chat.ipyra.com/')
}
```

but after we send these post messages with a login token to the IFrame, we are getting these messages inside the console.
`**Blocked autofocusing on a form control in a cross-origin subframe.**`

 we also got this message too.
**`Refused to display 'https://api.ipyra.com/api/rocket_chat_iframe_login' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`**

**Access to XMLHttpRequest at 'https://api.ipyra.com/api/sso' from origin 'https://chat.ipyra.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.**

**https://api.ipyra.com is our Node.js and Expess.js API Server** 

Here is Rocket Chat Admin panel Configuration: 

![Screenshot - 2020-07-12T183652 024](https://user-images.githubusercontent.com/8676339/87247764-25094580-c46f-11ea-8640-68b12421fda6.png)

also, can anyone let us know what is the purpose of 
**"Iframe URL" and "API URL" inside the Account => Iframe Settings** 

I have added the URLs and I have just written post methods for them inside my code.

Here are our general Settings, We have tried Following Option for the 
**Options to X-Frame-Options**
Options which we have tried
1)*
2)SAMEORIGIN
3)https://front.ipyra.com
4)Access-Control-Allow-Origin:  https://front.ipyra.com
But none of them worked for us

![Screenshot - 2020-07-12T184439 191](https://user-images.githubusercontent.com/8676339/87247861-c42e3d00-c46f-11ea-988b-1d1d40cb0da0.png)

We have also enabled the Iframe Integrations to.

![Screenshot - 2020-07-12T184812 596](https://user-images.githubusercontent.com/8676339/87247969-50d8fb00-c470-11ea-9ae7-e085aa631052.png)

Inside the Rest API, we have also enabled the CORS to.

![Screenshot - 2020-07-12T184940 083](https://user-images.githubusercontent.com/8676339/87248027-9dbcd180-c470-11ea-9099-71f1e5ed6c85.png)

But still, we are facing the above-mentioned errors.

kindly help us solving this issue.

**Comment by bosukas97** [comment]
Looking forward to the solutions to this.

**Comment by rodrigok** [comment]
@usamamashkoor your problem is not related to auto focus, but your API (https://api.ipyra.com/) not accepting calls from your chat (https://chat.ipyra.com/) URL, you need to configure your API CORS to accept those calls.

**Comment by bosukas97** [comment]
Hi guys, we have followed your shared link, https://github.com/RocketChat/iframe-auth-example/blob/master/index.js

We are creating a single page application, and after user logs in, into our website then we are calling the rocket chat rest api to login the user to rocket chat and then rocket chat gives us the rocket chat auth token and we save that inside the database.

in your example Iframe Auth you said we can return the login token inside the json response.

using like this,

// since this endpoint is loaded within the iframe, we need to communicate back to rocket.chat using `postMessage` API
				res.set('Content-Type', 'text/html');
				res.send(`<script>
				window.parent.postMessage({
					event: 'login-with-token',
					loginToken: '${ response.data.data.authToken }'
				}, 'http://localhost:3000'); // rocket.chat's URL
				</script>`);

but when your rocket chat calls our urls which we have given in Account => Iframe settings 
Iframe URL : https://api.ipyra.com/api/rocket_chat_iframe_login
API URL : https://api.ipyra.com/api/sso

then inside that api calls we are logging the data of the req.body and we are not getting any data inside the req.body inside node.js of the request.

this req.body is empty when you call our apu urls which we have given above.

so kindly let us know how we can login using those url and return the token to that urls, if we dont get any data from you to identify the user inside the database.

**Comment by rodrigok** [comment]
@bosukas97 can you check this new guide https://docs.rocket.chat/guides/administrator-guides/authentication/single-sign-on-iframe and see if you can understand your problem better?
