### ISSUE TITLE
OAUTH Regression Regarding Logins

### ISSUE THREAD

**Issue by ddorato** [RocketChat/Rocket.Chat#18255]
### Description:

When using any OAUTH source a user is greeted with an error: “This email has already been used and has not been verified. Please change your password.

### Steps to reproduce:

Logging into the app via an OAUTH source (GitHub, Google, Okta, etc)

### Expected behavior:

Successful login

### Actual behavior:

Error dialog

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Mongo
- NodeJS Version: 12.6.2
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: ALL
- Operating System: ALL

### Additional context

User was successfully created with OAUTH.  In the Users UI the user has an email as well as marked as verified.  IN OAUTH integrations Merge users is enabled.

### Relevant logs:

No debug logging created

**Comment by tammer123** [comment]
This has been happening a lot to my users after 3.2.x update.
