### ISSUE TITLE
Omnichannel/Sessions chat closed not working

### ISSUE THREAD

**Issue by rsgodinez** [RocketChat/Rocket.Chat#18259]
### Description:

Omnichannel/Sessions chat closed not working.
![image](https://user-images.githubusercontent.com/62675312/87443763-876f5c80-c5bb-11ea-8c52-fbf18cbb6a09.png)

### Steps to reproduce:

1. In Admin/Omnichannel/Sessions, we have Livechat_agent_leave_action_timeout configured at 10 or 600 seconds.
2. We start a Livechat conversation between Guest1 and Agent1 (bot).
3. Guest1 closes Livechat (closes browser) so the conversation remains open.
4. We force a logout-login in Agent1, expecting that after 10 or 600 seconds, the conversation closes.

### Expected behavior:

After 10 or 600 seconds, Agent1 closes the conversation, so in Omnichannel/Chat History we will see:

![image](https://user-images.githubusercontent.com/62675312/87441880-3cece080-c5b9-11ea-9f75-33506784de6e.png)

### Actual behavior:

Expected behavior was working until Rocket.Chat 3.3.3. Since Rocket.Chat 3.4.0, nothing happens. The conversation reamains open:

![image](https://user-images.githubusercontent.com/62675312/87442238-a836b280-c5b9-11ea-9c9d-467873cf2521.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 18.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Chrome 83.0.4103.116
- Operating System: Windows 10

### Additional context

As I mentioned before, this issue happens with 3.4.0, 3.4.1 and 3.4.2. We still have another server with 3.3.3 where we still have the expected behavior.

We also think that maybe this could be something similar to another issue https://github.com/RocketChat/Rocket.Chat/issues/18132 which started in 3.4.0 but was resolved in 3.4.1.

### Relevant logs:

N/A

**Comment by renatobecker** [comment]
@rsgodinez thanks for reporting this issue.
I'll look into this case ASAP.

Thanks.

**Comment by dennishenry** [comment]
Is there any update on this? We're having the same issue on our instance.
