### ISSUE TITLE
User Interface changes to accommodate sidebar features that need more horizontal space

### ISSUE THREAD

**Issue by garg** [RocketChat/Rocket.Chat#1826]
I'm going to use the Screensharing/Webcam feature as an example --- currently this feature shows up in the flextab column on the right. Another viewing option is the full screen mode and that hides the chat contents. 

I was wondering if we could make two other UI modes 

1) Something that allows a flextab to be popped out into it's own window. In that case a user would click on 'popout' and the Screenshare/cam tab would break off into another window that the user can position and resize and they see fit.

2) A horizontal view where the screenshare/cam window would be a horizontal row above the chat messages. This way the screenshare/cam window would have more space (greater width and also height).

I created a custom package for an application that uses canvas and allows chatters to collaboratively alter the canvas contents. Right now, the canvas appears just like the screenshare/cam window but I think it would be better if I could have it above the chat contents, or in its own window all while not breaking the UI on mobile devices etc.

I am posting this here to get some feedback and thoughts on this just in case a change like this is already planned for the future. 

Thanks!

**Comment by garg** [comment]
Adding samples of what I was suggesting. 

Sidebar-1.jpg
Notice the narrow column on the left of the fly-in sidebar. Clicking this would initiate a resize.

![sidebar-1](https://cloud.githubusercontent.com/assets/16932/12372047/13a22ae2-bc17-11e5-83bd-ebac6bb9b9c6.jpg)

Sidebar-2.jpg
Now the right column is expanded giving more space to the custom plugin.

![sidebar-2](https://cloud.githubusercontent.com/assets/16932/12372048/2b6230fa-bc17-11e5-9f72-57ff291a86ad.jpg)

Clicking the column again would return to the default view. 

Any thoughts?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
