### ISSUE TITLE
Fix the bug when action menu is hovered by "unread messages" text

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#18267]
![bug](https://user-images.githubusercontent.com/11751017/87534017-c70a7700-c695-11ea-8b9e-212b5afe6f15.png)

### Steps to reproduce:

1. Open open.rocket.chat
2. Go to a channel with unread messages
3. Hover a mouse over the first unread message

### Expected behavior:

All buttons are visible

### Actual behavior:

Menu buttons are hovered by "unread messages" text

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: 

OS Platform: linux
OS Arch: x64
5.3.0-1031-azure
v12.16.1
July 15, 2020 1:03

### Client Setup Information

- Desktop App or Browser Version: browser version
- Operating System: Windows 10 on Brave

### Additional context

Related to #18190

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/18273
