### ISSUE TITLE
User ID clash between instances affects app use

### ISSUE THREAD

**Issue by lkraider** [RocketChat/Rocket.Chat#18275]
### Description:

I have two instances of Rocket Chat that have been split. Since they come from the same "source", they have shared users that have the same user id in both instances.

This is not a problem in the desktop/web version, but causes issues with the RN Mobile App, that indexes servers by user ID, and causes issues when switching servers. (see https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1487#issuecomment-644380342)

Could the ID be changed on db restore? Maybe as a function accessing mongodb directly?

### Steps to reproduce:

1. Create a Rocket server, add some users, and create a mongodb dump
2. Restore the mongodb dump into a new Rocket instance
3. With the same user, login on both instances using the RN app, and try changing servers

### Expected behavior:

User should be able to use both instances.

### Actual behavior:

User is logged out of the instances when trying to use the app.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2, 2.4.0, 2.3.0, or any version really
- Operating System: unix
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.10

### Client Setup Information

- Desktop App or Browser Version: web app works fine
- Operating System: macOS

### Additional context

It seems to be some architectural decision on the RN app, maybe this could be "fixed" by having some docs on how to change user ID when restoring mongoDB into a new instance.

### Relevant logs:

Server 1:
![Screen Shot 2020-06-15 at 17 31 41](https://user-images.githubusercontent.com/52256/87576118-46ed0d00-c6a7-11ea-8628-217e5890e6ab.png)

Server 2:
![Screen Shot 2020-06-15 at 17 32 28](https://user-images.githubusercontent.com/52256/87576125-49e7fd80-c6a7-11ea-88b6-eac945b46148.png)

**Comment by geekgonecrazy** [comment]
Ouch.. this is super duper edge case.  Because cloning dbs and continuing both on is for sure not intended or expected.

Can you make sure uniqueId is different on both?  That might be at play


@RocketChat/reactnative this might be more for you guys?

**Comment by diegolmello** [comment]
@geekgonecrazy Yep. Can you transfer it? Thanks.

**Comment by geekgonecrazy** [comment]
This is way too edge case.  Adding code or instructions to change a userId is probably something you alone would use and would be super expensive to DB.

For your info you’d need to change in users and subscriptions and all messages at very least..  but also room IDs for all dms would have to be updated as well as all message objects.  

It’s an insane amount of work

**Comment by lkraider** [comment]
@geekgonecrazy would it be the case that a search/replace in the DB of the userId with a new random one *could* work? I am thinking something along these lines: https://github.com/andyfry01/mongo-find-replace

Or maybe some other way to create a new user, but transfer old convos to the new one? (like an ID alias?)
