### ISSUE TITLE
Quoting another user doesn't work in 3.4.2

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#18278]
### Description:

When quoting a user, the user you are quoting's message should be featured under your reply. Currently the reply shows after posting, but there is no reference to the original post you are quoting.

### Steps to reproduce:

1. Attempt to quote a user.
2. Reply is shown, quote doesn't appear.

### Expected behavior:

For quote to appear on reply.

### Actual behavior:

Quote doesn't show on reply.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.4.2
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: yes
- NodeJS Version: 12.16.1
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
> Quote doesn't show on reply.

I don't know. All seams to work fine at 3.4.2
![image](https://user-images.githubusercontent.com/4023037/87634291-a1d54180-c745-11ea-8f4d-9ac6779ff7d7.png)

**Comment by serviceman** [comment]
I have 7 installs of rocket chat on 3.4.2 and it doesn't work on any of them.

**Comment by TimmiORG** [comment]
Working with 3.4.2 for me as well.

**Comment by MartinSchoeler** [comment]
@serviceman can you test on version 3.5.0? Also did you change any user preferences? Thanks!

**Comment by pwit** [comment]
I have the similiar issue, actually there is two issues:
1. Quoting for normal user not working - the original message is not showing. However, it works for the admin.
2. Quoting not working at all on the Mac app - the original message is not showing.

Using Rocket.Chat 3.5.0.

**Comment by robinreinhardt** [comment]
Same issue here on 3.4.2

**Comment by MartinSchoeler** [comment]
Could not reproduce in 3.7.0 If you still experience this issue please open a new issue with updated details. Thanks!

<img width="241" alt="Screen Shot 2020-10-21 at 10 55 45 AM" src="https://user-images.githubusercontent.com/20868078/96729990-1db9d800-138c-11eb-87cd-1ab8aa470111.png">
