### ISSUE TITLE
OAUTH + LDAP + MERGE Real name wrongly cached

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat#18270]
### Description:

I have both OAUTH and LDAP set and merge is enabled. We had a problem where the fullname/realname in our oauth provider was wrongly set. After fixing those, we noticed that rocketchat somehow cached that name for parts of the chat screen.

### Steps to reproduce:

1. Enable LDAP and some OAUTH provider
2. Enable merge
3. Change the fullname/realname in the oauth provider
4. Login rocketchat and check your profile. ( It will reflect the change  as expected )
5. Start chatting with someone you never talked before
6. Change again the fullname/realname in the oauth provider  and login again in rocketchat. (  The profile  will reflect the change  as expected )
7. Ask the user you were talking what's you full name displayed in  his chat window
8. You will notice you name is correct on the chat window, but incorrect ( old one ) on the top bar and left bar. ( see screenshot below )

### Expected behavior:

After the realname is updated, it should be updated everywhere to reflect that change

### Actual behavior:

The new name is not updated on top bar and left bar. In the screenshot, the green square is the name correctly fixed on the auth provider, and the redsquares are the old name cached somewhere else.
Reload clearing cache does not fix that.

![image](https://user-images.githubusercontent.com/5522389/87544073-33787c80-c67c-11ea-82f0-0e698de4f1dd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System:  Docker

### Client Setup Information

- Desktop App or Browser Version: Both desktop and Webversion
- Operating System:

**Comment by jthomae1** [comment]
We have exactly the same problem.
Our authentication setup is a bit different, we only use OAuth with the "Merge Users" option. 

The steps to reproduce are the same.

**Comment by jsalatiel** [comment]
up

**Comment by jthomae1** [comment]
The issue still exists in RC Version 3.7.1

**Comment by jsalatiel** [comment]
Still exists on 3.11
