### ISSUE TITLE
Sort contacts in "Direct Messages" by activity changes daily with bubbling up contacts we didn't chat for a long time!

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [RocketChat/Rocket.Chat#18281]
### Description:

I am making rocket to sort contacts in direct messages by activity, but daily the sorting changes, and i find people that we didn't talk for a long time, bubbled up on top of the list!

### Steps to reproduce:

1. Set Rocket to sort contacts by activity
2. Check the list the following morning

### Expected behavior:

Expected to sort contacts by activity, the last person that i talked with, to be on top of the list and older one next...etc

### Actual behavior:

Very old conversations, shows up on top of the contact list

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2 and also happened in 2.4.11
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: One
- NodeJS Version: v12.16.1
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version: Desktop 2.17.9
- Operating System: Ubuntu 16.04
Also in browser and Android versions

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/18639

**Comment by mohammedragabsoftxpert** [comment]
@ggazzo Thank you
How to upgrade to 3.6.0 on snap installation?
