### ISSUE TITLE
user activation disappeared after update

### ISSUE THREAD

**Issue by KraMorK** [RocketChat/Rocket.Chat#18303]
### Description:

user activation disappeared after update
![image](https://user-images.githubusercontent.com/15525334/87922296-f9f1a800-caa5-11ea-890d-5815d030c5cd.png)

### Steps to reproduce:

1)snap update
2) done

### Expected behavior:

There must be a button or other way to activate the user

### Actual behavior:

No button

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v12.16.1
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version:  windows app 2.17.7
- Operating System:Win10x64

### Additional context

There used to be a button here
It was possible to activate a user or make him an administrator
today my server has been updated to version 3.4 and the button is gone
the server requires manual user activation
I also can not delete this account, there are also no "Delete" buttons
tried different clients, Windows application, Android app and web version, everything is the same everywhere
how to activate? maybe the command in the console
or how to downgrade?
I tried to "snap revert", but the server refused to work at all

### Relevant logs:

server
https://pastebin.com/BXMtFfY9

**Comment by KraMorK** [comment]
UPD
There is a button, but it is invisible
![image](https://user-images.githubusercontent.com/15525334/87926059-5b684580-caab-11ea-9162-0d91d1534bf5.png)
It turns out that you just need to correct the display
thank

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/18194 :)

**Comment by KraMorK** [comment]
thx great man:)
