### ISSUE TITLE
Implementation of SIP calls - PBX

### ISSUE THREAD

**Issue by LeonardOliveros** [RocketChat/Rocket.Chat#1830]
It would be a great idea to implement SIP calls would give a different orientation and open other avenues Rocket.Chat :smiley:

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by codefist** [comment]
This SHOULD align with the current roadmap.

**Comment by neutrolino** [comment]
A very necessary feature. Integration with SIP/Asterisk needed. And/Or client Rocket.Chat as client SIP/Asterisk.
