### ISSUE TITLE
Can't send text when is too long

### ISSUE THREAD

**Issue by Cancer-zern** [RocketChat/Rocket.Chat#18304]
### Description:

I've upgraded and got one bug
When I sending a long text, app showing me that "Message too long. Send it as an attachment instead?" I click "yes" and nothing (web/desktop)

### Steps to reproduce:

1. Copy long text from the web site/file/etc
2. Open Desktop App/ Web browser and put this text
3. Click to Send

### Expected behavior:

The text should convert to the file and sending

### Actual behavior:

Message too long. Send it as an attachment instead?

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu Server 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

Tried in Windows Desktop App, both desktop app and firefox, chrome 

### Additional context

I've upgraded from 2.4.11 to 3.4.2

root@ntchat:~# snap switch rocketchat-server --channel=3.x/stable
"rocketchat-server" switched to the "3.x/stable" channel

root@ntchat:~# sudo snap refresh rocketchat-server
rocketchat-server (3.x/stable) 3.4.2 from Rocket.Chat (rocketchat✓) refreshed

### Relevant logs:

I20200720-09:48:59.721(4) LocalStore: store created at  
I20200720-09:48:59.783(4) LocalStore: store created at  
I20200720-09:48:59.783(4) LocalStore: store created at  
I20200720-09:49:00.837(4) LocalStore: store created at  
I20200720-09:49:00.837(4) LocalStore: store created at  
I20200720-09:49:00.838(4) LocalStore: store created at  
I20200720-09:49:01.608(4) Setting default file store to GridFS 
I20200720-09:49:10.553(4) (migrations.js:120) Migrations: Migrating from version 170 -> 197
I20200720-09:49:10.556(4) (migrations.js:120) Migrations: Running up() on version 171
I20200720-09:49:10.598(4) (migrations.js:120) Migrations: Running up() on version 172
I20200720-09:49:10.658(4) (migrations.js:120) Migrations: Running up() on version 173
I20200720-09:49:10.729(4) (migrations.js:120) Migrations: Running up() on version 174
I20200720-09:49:10.766(4) (migrations.js:120) Migrations: Running up() on version 175
I20200720-09:49:10.957(4) (migrations.js:120) Migrations: Running up() on version 176
I20200720-09:49:10.982(4) (migrations.js:120) Migrations: Running up() on version 177
I20200720-09:49:10.991(4) (migrations.js:120) Migrations: Running up() on version 178
I20200720-09:49:11.011(4) (migrations.js:120) Migrations: Running up() on version 179
I20200720-09:49:11.218(4) DM rooms schema migration 0/1177 
I20200720-09:49:11.892(4) (migrations.js:120) Migrations: Running up() on version 180
I20200720-09:49:11.902(4) (migrations.js:120) Migrations: Running up() on version 182
I20200720-09:49:11.943(4) (migrations.js:120) Migrations: Running up() on version 183
I20200720-09:49:11.978(4) (migrations.js:120) Migrations: Running up() on version 184
I20200720-09:49:11.987(4) (migrations.js:120) Migrations: Running up() on version 185
I20200720-09:49:12.013(4) (migrations.js:120) Migrations: Running up() on version 186
I20200720-09:49:12.023(4) (migrations.js:120) Migrations: Running up() on version 187
I20200720-09:49:12.123(4) (migrations.js:120) Migrations: Running up() on version 188
I20200720-09:49:12.137(4) (migrations.js:120) Migrations: Running up() on version 189
I20200720-09:49:12.174(4) (migrations.js:120) Migrations: Running up() on version 190
I20200720-09:49:12.188(4) (migrations.js:120) Migrations: Running up() on version 191
I20200720-09:49:12.243(4) (migrations.js:120) Migrations: Running up() on version 192
I20200720-09:49:12.366(4) (migrations.js:120) Migrations: Running up() on version 193
I20200720-09:49:12.382(4) (migrations.js:120) Migrations: Running up() on version 194
I20200720-09:49:12.406(4) (migrations.js:120) Migrations: Running up() on version 195
I20200720-09:49:12.614(4) (migrations.js:120) Migrations: Running up() on version 196
I20200720-09:49:12.630(4) (migrations.js:120) Migrations: Running up() on version 197
I20200720-09:49:12.653(4) (migrations.js:120) Migrations: Finished migrating.
I20200720-09:49:22.655(4) Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds. 
I20200720-09:49:22.663(4) (migrations.js:120) Migrations: Not migrating, already at version 197
I20200720-09:49:53.030(4) Loaded the Apps Framework and loaded a total of 0 Apps! 
I20200720-09:49:53.684(4) Updating process.env.MAIL_URL 
I20200720-09:49:53.906(4) Using GridFS for custom sounds storage 
I20200720-09:49:53.921(4) Using GridFS for custom emoji storage 
I20200720-09:49:59.396(4) ➔ System ➔ startup 
I20200720-09:49:59.397(4) ➔ +------------------------------------------------------+ 
I20200720-09:49:59.397(4) ➔ |                    SERVER RUNNING                    | 
I20200720-09:49:59.398(4) ➔ +------------------------------------------------------+ 
I20200720-09:49:59.398(4) ➔ |                                                      | 
I20200720-09:49:59.399(4) ➔ |  Rocket.Chat Version: 3.4.2                          | 
I20200720-09:49:59.399(4) ➔ |       NodeJS Version: 12.16.1 - x64                  | 
I20200720-09:49:59.400(4) ➔ |      MongoDB Version: 3.6.14                         | 
I20200720-09:49:59.400(4) ➔ |       MongoDB Engine: wiredTiger                     | 
I20200720-09:49:59.401(4) ➔ |             Platform: linux                          | 
I20200720-09:49:59.401(4) ➔ |         Process Port: 3000                           | 
I20200720-09:49:59.402(4) ➔ |             Site URL: https://ntchat.example.net  | 
I20200720-09:49:59.402(4) ➔ |     ReplicaSet OpLog: Enabled                        | 
I20200720-09:49:59.403(4) ➔ |          Commit Hash: e5f93d3f5e                     | 
I20200720-09:49:59.403(4) ➔ |        Commit Branch: HEAD                           | 
I20200720-09:49:59.404(4) ➔ |                                                      | 
I20200720-09:49:59.404(4) ➔ +------------------------------------------------------+

**Comment by geekgonecrazy** [comment]
This isn't specific text right?  Have you tried with multiple text examples?  Can you maybe attach or link to example of text used that can be used to quickly reproduce.  Easier to reproduce easier to get a fix :)

**Comment by Cancer-zern** [comment]
https://pastebin.com/KAkqcAqq

**Comment by Cancer-zern** [comment]
Hi geekgonecrazy,
I've tried other text messages like text from the newspaper or sql query if it's too long it's not working.
If you need i can make a video.

**Comment by zdumitru** [comment]
The bug happens when exceeding amount of characters defined in settings (Administration -> Message -> Maximum Allowed Characters Per Message & "Allow converting long messages to attachment" need to be checked ) that converts message to an attachment.
