### ISSUE TITLE
Jitsi, new link gets an false at the end of the link

### ISSUE THREAD

**Issue by Bob-Olsen** [RocketChat/Rocket.Chat#18305]
### Description:
Hey together,

after updateing the server, the new invitation link to open jitsi gets an "false" at the end. 

If you open the this link via android app the "false" part is not take into account.

That mean if i start a jitsi seassion via laptop, windows 10 app the link looks like :

 https://aaa.aaa.com/XQgxJKmsjNAdPqZsm9DpBRofalse

The mobile user can try to join via the join button but joins another room, its the room ID without the false. 

If you manual remove the the "false" at the end you can join the mobile user with the normal windows 10 client.

So mobile somehow doesnt get the false but windows 10 client get him.

If i activte the suffix feature in the admin panel the suffix is is set before the "false"

https://YYY.CCCCC.de/prefix +random + suffix +"false" like that

### Steps to reproduce:

1. click the phone icon within an conversation
2. click the click to join button

### Expected behavior:

If you prees Join Button the link should not have an "false" at the end

### Actual behavior:

the link gets an false at the end

 https://aaa.aaa.com/XQgxJKmsjNAdPqZsm9DpBRofalse

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Linux x64 3.10.0-1127.13.1.el7.x86_64
- Deployment Method: manual install
- NodeJS Version:  v12.18.2
- MongoDB Version:3.6.18
- Number of Running Instances: 1

### Client Setup Information

- Desktop App: Windows 10 64 bit - 2.15.2
- Operating System:Windows 10 x64 [Version 10.0.17763.1282]
- Latest Rocketchat and Jitsi Version on Android 10

https://github.com/RocketChat/Rocket.Chat/issues/18140#issuecomment-654994832

**Comment by EnCz** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/18140

**Comment by Bob-Olsen** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/18140#issuecomment-654994832 works but doesnt fix the issue
