### ISSUE TITLE
Attached files are rendered as text

### ISSUE THREAD

**Issue by nmagedman** [RocketChat/Rocket.Chat#18312]
### Description:

PR #16232 introduced a BREAKING CHANGE even though it was labelled as a bugfix.
That PR adds the HTTP header `x-content-type-options: nosniff` which is a good security move, however it breaks installations that do not yet set the Content-Type.   Had it been labelled a BREAKING CHANGE, I could have ensured that we were setting our MIME types properly before upgrading.

### Steps to reproduce:

1. Upload an image to a chat room (or find a pre-existing one)
2. Click on the image **title** (not the image itself).
3. The image will load in a new tab.

### Expected behavior:

The image to be displayed properly in the new browser tab.

### Actual behavior:

The contents of the image file are displayed as plain text.  e.g. a PNG file is displayed as

```
‰PNG

���
IHDR����_���
...
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 15
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Chrome 83.0.4103.116
- Operating System: MacOS Catalina 10.15.5

**Comment by milton-rucks** [comment]
@rodrigok , I believe we can close this one. @damian-centrone tested and now it's working fine.
