### ISSUE TITLE
Missing message field in thread side bar

### ISSUE THREAD

**Issue by balert** [RocketChat/Rocket.Chat#18311]
### Description:

In some channels the text field for entering a message as a reply inside the thread view is missing, so no reply can be written.
Unfortunately not happening in every channel. The text field seems to disappear very quickly while opening the thread view, as it can be seen for a fraction of a second before it disappears. 

### Steps to reproduce:

1. open right side bar of a reply thread
2. text field for entering a new reply inside this thread is missing.

### Expected behavior:

Text field for new replies in this thread is expected.

### Actual behavior:

Text field is missing.
Screenshot: https://ibb.co/fNR8614

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Linux

**Comment by gabriellsh** [comment]
I've been trying to pay attention to this bug since you posted this, but couldn't get it to happen. Is it still happening? And does it appear again after closing and reopening the thread?

**Comment by balert** [comment]
yes still happens. Only in one channel, while all other channels I've tested didn't show the problem. It appears to me as if <div class="rc-message-box rc-new"> is emptied very shortly after (or during) loading the channels thread side bar.

**Comment by b90g** [comment]
I can confirm the issue by a user on the instance I use and provide support for.
Also on 3.4.2

**Comment by gabriellsh** [comment]
Can you get access to that channel's config and send it here?

**Comment by b90g** [comment]
unfortunately i cannot find the ticket which i posted the github issue in, so i cant find the channel where it happend. :/ with channel config you ask if it is a public/private channek broadcast etc?

**Comment by gabriellsh** [comment]
Yes, exactly. Sorry for the delay btw. I haven't been able to reproduce your issue yet. The room config (private, public, read only, broadcast, etc) is essential for debugging, since I don't know the state the room was in order for the issue to occur.

We've just released 3.7.0, it's a good idea to update if possible. If you're not a fan of being on the edge with updates, at least consider 3.6.3, which might already have fixed this bug.
