### ISSUE TITLE
MS Edge not showing images.

### ISSUE THREAD

**Issue by kreuzebek** [RocketChat/Rocket.Chat#1831]
Before Microsoft Edge showed saved images. Now isn't showing. 

When I click on the image, browser returns forbidden (403)

This is the only way to access Rocket.Chat in Windows Mobile(10).

![upload](https://cloud.githubusercontent.com/assets/9173505/12178967/7d5490dc-b55b-11e5-93d2-12721e8a8419.PNG)

Link preview works fine.

**Comment by marceloschmidt** [comment]
@kreuzebek are you testing this on your own instance? have you tried it on https://demo.rocket.chat?

**Comment by kreuzebek** [comment]
In both!
Chrome and Edge:
![image](https://cloud.githubusercontent.com/assets/9173505/12201077/79d17a84-b609-11e5-9f91-926eaaa3e58a.png)

**Comment by dotnetneile** [comment]
Getting the same issue with the latest version 0.18. Uploaded images aren't shown and a 403 when trying to open them. No amount of emulation or agent string changes make a difference from IE. Also seems to be the same issue see on issue 2242 (https://github.com/RocketChat/Rocket.Chat/issues/2242).

Any update on a fix or workaround?

**Comment by renexu** [comment]
got same issue here, uploaded image all returns 403

**Comment by uhillig** [comment]
same issue here, for Edge and Internet Explorer

**Comment by hunterua** [comment]
Same issue for local installation

**Comment by engelgabriel** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/4014

**Comment by geekgonecrazy** [comment]
It doesn't appear to still be an issue.  I've checked on several instances and images are showing properly
