### ISSUE TITLE
Hebrew translation missing

### ISSUE THREAD

**Issue by ohadetsion** [RocketChat/Rocket.Chat#18329]
### Description:

After change the language to Hebrew, there are a lot of missing translation.
I Already added the translation in the file - he.i18.json.
After open this issue i want to open pull request to add my translation, if you will allow :)

### Steps to reproduce:

1. change the language to Hebrew.
2. See a lot of missing translation.

### Expected behavior:

See correct translation.

### Actual behavior:

See a lot of missing translation.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: docker
- NodeJS Version: 12
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: chrome
- Operating System: ubuntu

### Additional context

I Already added the translation in the file - he.i18.json.
After open this issue i want to open pull request to add my translation, if you will allow :)

### Relevant logs:

None.

**Comment by gabriellsh** [comment]
Please, take a look [here](https://docs.rocket.chat/contributors/contributing/translating). Thanks!

**Comment by ohadetsion** [comment]
@gabriellsh I did saw it. But in the project i notice there is still the " he.i18.json ".
So can you explain please ?
Thank's :)

**Comment by gabriellsh** [comment]
Lingohub updates those files automatically for us :)

**Comment by sampaiodiego** [comment]
@ohadetsion feel free to submit a pull request if that works better for you, we accept both. thanks
