### ISSUE TITLE
Add unread message count to channel pane

### ISSUE THREAD

**Issue by np-trivial** [RocketChat/Rocket.Chat#1832]
I think this is a new feature request

Mock up:
<img width="176" alt="rocketchat-unread-new" src="https://cloud.githubusercontent.com/assets/16595428/12180395/ec7c293a-b541-11e5-88d5-7266655c97d5.png">
Would like to see not only the number of unread @ mentions (1 in this mockup), but also just number of unread messages (2 in this mockup). Otherwise, I have to flip into each channel separately to see if there are any new messages.

**Comment by tuudik** [comment]
Would love it (Y)!!!

**Comment by vetash** [comment]
+1

**Comment by marceloschmidt** [comment]
You can see if there are new messages by checking the channel name, that is highlighted when there are new messages.

**Comment by np-trivial** [comment]
yes, but the difference is pretty subtle (just bolding the text from what I can tell.) This seems to stand out more.

**Comment by kkachura** [comment]
+++++1

**Comment by Fenr1r90** [comment]
And what about this feature? Any progress?

**Comment by Rivenhall** [comment]
+1 I would find this a massive improvement. One of the biggest complaints I have from migrating my team from a skype chat room is that they dont see the number of messages unless they are directly mentioned. Having this as an option for all unread messages would make certain rooms pop out more from our lists than they currently do

**Comment by sampaiodiego** [comment]
what you thought about https://github.com/RocketChat/Rocket.Chat/pull/7589?

**Comment by exhuma** [comment]
I just found this in the "General" tab of the settings:

![image](https://user-images.githubusercontent.com/65717/37658376-ab8fb84e-2c4d-11e8-9ad6-efe6e948a256.png)

Does that solve this issue? If yes, I suppose this issue could be closed?

**Comment by sampaiodiego** [comment]
thanks @exhuma .. I think it solves the issue.
