### ISSUE TITLE
Invalid dates on Omnichannel Analytics

### ISSUE THREAD

**Issue by PedroPretto** [RocketChat/Rocket.Chat#18338]
### Description:

I'm having some trouble with the omnichannel analytics session.

When I try to filter by a custom date, the error "invalid_dates/Error_in_custom_dates" shows up.

It happens whatever the date a try to search for.

In the logs:
I20200721-12:41:24.210(0) livechat:getAnalyticsOverviewData => Invalid dates
I20200721-12:41:24.223(0) livechat:getAnalyticsChartData => Invalid dates
I20200721-12:41:24.229(0) livechat:getAgentOverviewData => Invalid dates

### Steps to reproduce:

1. Omnichannel
2. Analytics
3. Set a custom date

### Expected behavior:

Retrieve the data captured in the time interval setted.

### Actual behavior:

![bugrc](https://user-images.githubusercontent.com/38132954/88069281-a5066e00-cb47-11ea-8f0f-88bcec57a8e8.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Debian 9
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Relevant logs:
**Server**
I20200721-12:41:24.210(0) livechat:getAnalyticsOverviewData => Invalid dates
I20200721-12:41:24.223(0) livechat:getAnalyticsChartData => Invalid dates
I20200721-12:41:24.229(0) livechat:getAgentOverviewData => Invalid dates

**Browser**
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 19/07/2020, _f: undefined, _strict: undefined, _locale: [object Object]
N/<@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:30259
Ua@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:55280
Ha@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:57090
qa@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:56957
za@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:56676
Va@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:57417
Wa@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:57451
r@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:61:26703
click .lc-custom-daterange-submit@/app/livechat/client/views/app/analytics/livechatAnalyticsCustomDaterange.js:1:975
e/t.prototype.events/r[i]</</<@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:38722
e/t._withTemplateInstanceFunc@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:38048
e/t.prototype.events/r[i]</<@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:38673
i/</</</<@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:27139
t/h._withCurrentView@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:23216
i/</</<@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:27099
o/this.delegatedHandler<@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:202:9217
dispatch@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:48:39315
add/g.handle@https://rocketchat2.confirmationcall.com.br:8443/325e89158f684bf2880b7902f410ef266f2cddb9.js?meteor_js_resource=true:48:37310
325e89158f684bf2880b7902f410ef266f2cddb9.js:61:29852

​

**Comment by paulobernardoaf** [comment]
Tested the #18766 branch, and the problem was solved. Waiting for it to be merged.
