### ISSUE TITLE
Scrolling to new messages sometimes jumps back to the bottom

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#1833]
Happens sometimes when people are writing new messages and you're scrolling to the top, or when you scroll by clicking the mouse wheel and moving your cursor up.
Also happens when you scroll up by using page-up.
I noticed that when scrolling as described above is started when not at the bottom of the message box, this bug does not occur.

**Comment by MartinSchoeler** [comment]
I didn't see this bug in a while,  so i will close this. If you see this bug again, please reopen this issue. Thanks!
