### ISSUE TITLE
LDAP import identities - Not work

### ISSUE THREAD

**Issue by No0btower** [RocketChat/Rocket.Chat#18330]
### Description:

When we make the synchronization for importing the contact, we get an error for each import, the user is created without a role.

### Steps to reproduce:

Make a synchronization in the LDAP section, and see the user.

### Expected behavior:

Each user have the user role.

### Actual behavior:

Users have no role.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4
- Operating System: macOs
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Browser (Chrome: 84.0.4147.89)
- Operating System: macOs

### Relevant logs:

`LDAPSync ➔ error Error creating user BulkWriteError: E11000 duplicate key error index: rocketchat.rocketchat_subscription.$_id_ dup key: { : "TdR5FEnCa6eRhAxMf" }     at OrderedBulkOperation.handleWriteError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1210:11)     at resultHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:519:23)     at handler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:1204:22)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:404:18     at processTicksAndRejections (internal/process/task_queues.js:75:11)  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at DDPCommon.MethodInvocation.<anonymous> (app/authentication/server/startup/index.js:247:19)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:246:11)     at executeBound (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:762:67)     at AccountsServer.bound [as insertUserDoc] (/opt/Rocket.Chat/programs/server/npm/node_modules/underscore/underscore.js:793:14)     at createUser (packages/accounts-password/password_server.js:1119:27)     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1188:10)     at addLdapUser (app/ldap/server/sync.js:460:29)     at app/ldap/server/sync.js:526:5     at Array.forEach (<anonymous>)     at app/ldap/server/sync.js:493:13     at runWithEnvironment (packages/meteor.js:1286:24) {   index: 0,   code: 11000,   errmsg: 'E11000 duplicate key error index: rocketchat.rocketchat_subscription.$_id_ dup key: { : "TdR5FEnCa6eRhAxMf" }',   op: {     open: true,     alert: true,     unread: 1,     userMentions: 1,     groupMentions: 0,     ts: 2020-07-21T08:42:06.113Z,     rid: 'GENERAL',     name: 'general',     fname: undefined,     customFields: undefined,     t: 'c',     u: {       _id: 'pizJXiYN7HP869yzN',       username: 'niederkorn.raymond',       name: undefined     },     _updatedAt: 2020-07-21T08:42:06.113Z,     _id: 'TdR5FEnCa6eRhAxMf'   },   name: 'BulkWriteError',   driver: true,   err: {     index: 0,     code: 11000,     errmsg: 'E11000 duplicate key error index: rocketchat.rocketchat_subscription.$_id_ dup key: { : "TdR5FEnCa6eRhAxMf" }',     op: {       open: true,       alert: true,       unread: 1,       userMentions: 1,       groupMentions: 0,       ts: 2020-07-21T08:42:06.113Z,       rid: 'GENERAL',       name: 'general',       fname: undefined,       customFields: undefined,       t: 'c',       u: [Object],       _updatedAt: 2020-07-21T08:42:06.113Z,       _id: 'TdR5FEnCa6eRhAxMf'     }   },   result: BulkWriteResult {     result: {       ok: 1,       writeErrors: [Array],       writeConcernErrors: [],       insertedIds: [Array],       nInserted: 0,       nUpserted: 0,       nMatched: 0,       nModified: 0,       nRemoved: 0,       upserted: [],       lastOp: [Object]     }   },   [Symbol(mongoErrorContextSymbol)]: {} }`

**Comment by ZeroPoke** [comment]
Any word on this Im also having this issue on a clean snap install?

**Comment by dieug** [comment]
we have the same problem with rocketchat versions: 3.5.1, 3.5.2, 3.5.3, 3.5.4.
and much another with ldap. 

p.s.:
i didn't remember exactly, but with 3.5.0 ldap did work better.

**Comment by No0btower** [comment]
I can add that this issue is not present on version 3.3.3.

**Comment by semack** [comment]
The same problem, LDAP is required, but we can not start using RC on the latest version.

> I20201005-14:06:17.178(0) LDAPSync ➔ debug userQuery { 'services.ldap.id': '23a71f8bdd49c44ab67675063be645fa' } 
I20201005-14:06:17.179(0) LDAPSync ➔ debug New user data {   username: 'test.test',   email: 'test.test@test.com' } 
I20201005-14:06:17.187(0) Meteor ➔ method joinDefaultChannels -> userId: DieNN2Tfd6QwLijyu, arguments: [null] 
I20201005-14:06:17.193(0) server.js:204 LDAPSync ➔ error Error creating user BulkWriteError: E11000 duplicate key error index: rocketchat.rocketchat_subscription.$_id_ dup key: { : "dzidQ3tcF6R2y9W9v" }     at OrderedBulkOperation.handleWriteError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:1257:9)     at resultHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/bulk/common.js:521:23)     at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18     at processTicksAndRejections (internal/process/task_queues.js:79:11)  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at DDPCommon.MethodInvocation.<anonymous> (app/authentication/server/startup/index.js:247:19)     at packages/dispatch_run-as-user.js:211:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     at AccountsServer.<anonymous> (app/authentication/server/startup/index.js:246:11)     at executeBound (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:758:67)     at AccountsServer.bound [as insertUserDoc] (/app/bundle/programs/server/npm/node_modules/underscore/underscore.js:789:14)     at createUser (packages/accounts-password/password_server.js:1128:27)     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1197:10)     at addLdapUser (app/ldap/server/sync.js:472:29)     at app/ldap/server/sync.js:538:5     at Array.forEach (<anonymous>)     at app/ldap/server/sync.js:505:13     at runWithEnvironment (packages/meteor.js:1286:24) {   driver: true,   code: 11000,   writeErrors: [ WriteError { err: [Object] } ],   result: BulkWriteResult {     result: {       ok: 1,       writeErrors: [Array],       writeConcernErrors: [],       insertedIds: [Array],       nInserted: 0,       nUpserted: 0,       nMatched: 0,       nModified: 0,       nRemoved: 0,       upserted: [],       lastOp: [Object]     }   } }

**Comment by semack** [comment]
#19058
