### ISSUE TITLE
Image Assets (Admin > Settings > Assets) not properly being pushed through to all necessary locations.

### ISSUE THREAD

**Issue by BizClimb** [RocketChat/Rocket.Chat#18344]
### Description:

When saving assets in the admin panel, they don't properly get saved in all necessary locations. Specifically /programs/web.browser/app/images/logo on the server. This causes the rendering of "default rocket chat logos" instead of the uploaded logos in workspace views in the app and possibly other locations.

### Steps to reproduce:

1. Go to Admin > Settings > Assets and save a logo as the android-chrome 512x512 (png)
2. Save Changes.
3. Go to https://YOURWORKSPACEURL/images/logo/android-chrome-512x512.png

### Expected behavior:

It should show your uploaded 512 asset.

### Actual behavior:

It shows default 512 rocket chat logo.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.2.7

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

I'm not sure where else the logos might not be set properly but I am sure at minimum locally on the server at: /Rocket.Chat/programs/web.browser/app/images/logo and /Rocket.Chat/programs/web.browser.legacy/app/images/logo

### Relevant logs:

None

**Comment by gabriellsh** [comment]
Those urls are "fixed". The assets page doesn't overwrite those images.

For example, I changed the logo:
![image](https://user-images.githubusercontent.com/40830821/88588457-f625ce80-d02d-11ea-9154-e7a6fcc72e05.png)

And it shows the changes, but when I enter `http://localhost:3000/images/logo/logo.png`, It still shows the default rocket.chat logo.

Did you find somewhere in your application where the custom assets are missing? Disregarding those URLs we just talked about. If possible, it would be nice if you could help us reproduce this. Thanks!

**Comment by BizClimb** [comment]
Yes, when I using the app compiled from the Rocket.Chat.ReactNative repo - single server branch. The initial view (WorkspaceView) loads https://YOURWORKSPACEURL/images/logo/android-chrome-512x512.png which shows the default RocketChat logo instead of the 512x512 icon in assets. So no matter what your custom assets are the workspace view shows the default RocketChat logo. I'm not sure where else that is incorrect, might be other references, but that's all I've noticed so far.

See my initial issue in that repo: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2327

**Comment by gabriellsh** [comment]
Oh okay, now it makes sense. I'll see if this is something to do with the app itself. Thanks!

**Comment by diegolmello** [comment]
Hey, @gabriellsh.
This issue is going to be fixed by https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2376
Thanks!
