### ISSUE TITLE
SAML Error after update to RocketChat 3.4.2 (prior 3.1.1)

### ISSUE THREAD

**Issue by shakalandy** [RocketChat/Rocket.Chat#18368]
### Description:

After upgrading our RocketChat Instance the SAML Auth does not work, user gets redirected to RocketChat Frontpage after clicking "Use SSO".

### Steps to reproduce:

1. Go to RocketChat Startpage
2. Click "Login with SSO"
3. User gets redirected to Startpage

### Expected behavior:

Redirect to SSO Provider

### Actual behavior:

RocketChat loggs the following error:

```
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]: server.js:204 steffo:meteor-accounts-saml ➔ error Error: Status is: urn:oasis:names:tc:SAML:2.0:status:Responder
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at ResponseParser.validate (app/meteor-accounts-saml/server/lib/parsers/Response.ts:51:20)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at SAMLServiceProvider.validateResponse (app/meteor-accounts-saml/server/lib/ServiceProvider.ts:188:17)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at Function.processValidateAction (app/meteor-accounts-saml/server/lib/SAML.ts:379:19)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at Function.processRequest (app/meteor-accounts-saml/server/lib/SAML.ts:51:17)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at middleware (app/meteor-accounts-saml/server/listener.ts:61:8)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at app/meteor-accounts-saml/server/listener.ts:79:3
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]: server.js:204 steffo:meteor-accounts-saml ➔ error Error: Unable to validate response url
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at app/meteor-accounts-saml/server/lib/SAML.ts:383:12
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at ResponseParser.validate (app/meteor-accounts-saml/server/lib/parsers/Response.ts:51:11)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at SAMLServiceProvider.validateResponse (app/meteor-accounts-saml/server/lib/ServiceProvider.ts:188:17)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at Function.processValidateAction (app/meteor-accounts-saml/server/lib/SAML.ts:379:19)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at Function.processRequest (app/meteor-accounts-saml/server/lib/SAML.ts:51:17)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at middleware (app/meteor-accounts-saml/server/listener.ts:61:8)
Jul 24 10:24:28 rocket-chat-8m0bxa0j rocketchat[986]:     at app/meteor-accounts-saml/server/listener.ts:79:3
```

### Server Setup Information:

- Version of Rocket.Chat Server:  3.4.2
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.3
- MongoDB Version:4.0.19

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Chrome/Mac

### Additional context

maybe related: #9545

worker before like a charm. 
added logs above.
Nothing else was changed on the system.
Added "Allowed clock drift from Identity Provider" as well, didn't help

**Comment by pierre-lehnen-rc** [comment]
Can you enable the SAML debug logs under the SAML settings to get the response XML from the logs?

**Comment by ddbrandonb** [comment]
We are also experiencing this same issue intermittently but only with the desktop client (tested v2.17.7 and v2.17.11).
With SAML debugging enabled the log @shakalandy posted is all that is logged. We have the exact same issue and logs on RC Server 2.5.0-rc4.

**Comment by pierre-lehnen-rc** [comment]
Try also setting the log level to `1. Errors and Information` on the Logs category of the admin. The SAML XML should then be logged.

**Comment by PatriceG** [comment]
Hello,
We have the same issue, with RocketChat 3.13.0
SAML Auth stopped working after upgrading from 3.10.5
Any help is very welcome!

**Comment by justinscottroman** [comment]
we are having this too. Does anybody know how to fix this?
