### ISSUE TITLE
Not getting push notifications after enabling them in self-hosted server

### ISSUE THREAD

**Issue by ajibarra** [RocketChat/Rocket.Chat#18361]
### Description:

Hi, I have enabled push notifications today, using https://gateway.rocket.chat as gateway. I have restarted the server (3.4.2) and tried to send the test push notification and I got it in my mobile (iOS). For some reason I am not getting notifications from channels/users. I have changed mobile notification to ALL and also logout and login in mobile. It does not work. I also enabled debug logs and I do see the test push being sent in the logs but any other message is not pushed to devices. When I check rocketchat_notification_queues I see more than 100 notifications pending, most of them with schedule as null but I am not sure about what process this queue. I am not sure if anybody else has faced the same issue and can help me with this. Thank you!

### Steps to reproduce:

1. Enable push notifications
2. Send test notification. It works
3. Ask to somebody to send you messages and you wont get push notifications

### Expected behavior:

I would expect getting push notifications in mobile

### Actual behavior:

I dont get push notifications

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu (Linux)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 3.6.14
- MongoDB Engine: wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Mobile app
- Operating System: iOS

### Additional context

No additional context

### Relevant logs:

No relevant logs

**Comment by gabriellsh** [comment]
Could you send the logs? Thanks!
