### ISSUE TITLE
Why RocketChat can mentions all people outside room????

### ISSUE THREAD

**Issue by anduonghien** [RocketChat/Rocket.Chat#1836]
Hey Team.
I'm testing function Mentions on server demo (https://demo.rocket.chat/)
When I am Direct Room or Private with Room with my friend, I using Mentitons function, All user on system will be load, and I can mentions them, but they not member in my room?

**Comment by geekgonecrazy** [comment]
You should no longer be able to actually mention anyone outside of the room.  You can do: `@username` but they will not be alerted.  As far as removing the ability to see users outside of the private group we're tracking that here: #2802 with a bit more activity.
