### ISSUE TITLE
2FA / Two-factor authentication via TOTP

### ISSUE THREAD

**Issue by dawdad** [RocketChat/Rocket.Chat#18362]
### Description:

When we try to add the TOTP function to the user account via  "My Account => Security => Enable two-factor authentication via TOTP" the code what is provided is always wrong. 

### Steps to reproduce:

1. Login to Rocketchat
2. Click onto your username and then in the sub menu My Account
3. Select Security
4. Selet Enable two-factor authentication via TOTP
5. Use the QR Code via APP e.g. FreeOTP or Google Auth. 
6. Enter die given OTP into the Auth Code Line and press Verify

### Expected behavior:

Accept the Code and set TOTP as required login method

### Actual behavior:
![grafik](https://user-images.githubusercontent.com/703281/88367290-b6d85300-cd8b-11ea-9314-180e3f5cafc5.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.4.2
- Operating System: Linux CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: 2.17.11
- Operating System: Windows 10

### Relevant logs:

- No logs needed

**Comment by gabriellsh** [comment]
I just tried it with `Authy` app at latest develop, and it's working fine. Could you maybe look into the browser/server console and see if there's something weird going on there? If so, logs would be really helpful. Don't forget that the OTP code has a time limit to be used after generated (30s I guess).

**Comment by geekgonecrazy** [comment]
Also make sure your server time and device time are correct.  If your server time is delayed or any time is off you will never be able to have matching code

**Comment by gcommit** [comment]
could it be related to this? 
https://github.com/RocketChat/Rocket.Chat/issues/18823

**Comment by ShamimIslam** [comment]
Having this problem on v4.00 of RocketChat. Unable to add 2FA via Google Authenticator - always comes back with invalid code on numbers typed after using QR code or using the key.
