### ISSUE TITLE
Mailing messages is only available to admins

### ISSUE THREAD

**Issue by matthias-brun** [RocketChat/Rocket.Chat#1837]
I noticed that a feature was introduced which allows admins to select and then email messages in a room to other users. (or arbitrary e-mail addresses) On the Rocket.Chat instance I manage there are users who use their email client to manage and organize their tasks and it would be quite helpful for them to be able to access this function so they can quickly forward certain messages to their email account. Managing the permissions as to who should be able to access this function is currently not possible via the permissions interface in the administration panel, which I think it should be. Or is there a reason it is only available to admins?

For this exact use case it would also be helpful to have such a feature freely available to everyone with the restriction of only being able to send emails to themselves. Any thoughts on that?

**Comment by tuudik** [comment]
Which version are you using?

I can see from Permissions, that it is possible to enable mail-messages function for users.

Using 0.12.1 version.

**Comment by matthias-brun** [comment]
`mail-messages` actually is in the permissions, I'm not really sure how I missed that. Thanks for pointing it out!
