### ISSUE TITLE
Desktop Audio "Account Preference" missing

### ISSUE THREAD

**Issue by nmagedman** [RocketChat/Rocket.Chat#18387]
### Description:

A channel's Notification Preferences pane includes a "Desktop > Audio" preference, controlling which messages should trigger a sound: All messages, Mentions, or Nothing.   There is also the option "Default" (aka "Use Account Preference").  **However,** there does not seem to be any way of setting this Account Preference within /account/preferences.
In the Notifications section, there are:

* Show Desktop Notifications For
* Push Mobile Notifications For
* Offline Email Notifications

but I see nothing for Audio Notifications.  The "Desktop Notifications" seems to be just for a visual box that appears, without an sound event to go with it.

![Screen Shot 2020-07-27 at 21 55 55](https://user-images.githubusercontent.com/1042298/88580199-f638c500-d053-11ea-88a5-b3f2751acbb4.png)

### Steps to reproduce:

1. Enter a channel.
2. Click on the Bell icon ("Notifications Preferences")
3. Set Desktop > Audio to "Use Account Preference" aka "Default".  Click Save.
4. Click the Avatar menu > My Account > Preferences.

### Expected behavior:

There should be a setting in the My Account > Preferences page for setting Desktop Audio notifications across all channels.

### Actual behavior:

No such setting exists.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 15
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Chrome 83.0.4103.116
- Operating System: MacOS Catalina 10.15.5

**Comment by aradhya-gupta** [comment]
I would like to work on this issue. @rodrigok

**Comment by rodrigok** [comment]
@aradhya-gupta that's great, your contribution is very welcome. 🎉
