### ISSUE TITLE
Left sidemenu doesn't resize while searching

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#18382]
### Description:

While searching, the left side menu doesn't resize.

Possibly also related/causing https://github.com/RocketChat/Rocket.Chat/issues/15720

### Steps to reproduce:

1. Click search
2. Resize the window

### Expected behavior:

Sidemenu should resize 

### Actual behavior:

![jl0YEvPwS0](https://user-images.githubusercontent.com/6295044/88545657-49c1f900-cfe9-11ea-99e2-90f7af32af50.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: open 3.5.0-rc.3

**Comment by gabriellsh** [comment]
We'll be rewriting that sidebar soon enough. But thanks for the tip! I'll be adding a link to this on the project.

**Comment by wreiske** [comment]
This is no longer an issue on the latest react sidebar implementation :)

**Comment by gabriellsh** [comment]
Thanks for checking @wreiske ! 🚀
