### ISSUE TITLE
Per-Channel Desktop Alerts preference will not remain at Default

### ISSUE THREAD

**Issue by nmagedman** [RocketChat/Rocket.Chat#18388]
### Description:

A channel's Notification Preferences pane includes a "Desktop > Alerts" preference, controlling which messages should trigger a notification popup: All messages, Mentions, or Nothing.   There is also the option "Default" (aka "Use Account Preference").  **However,** if that preference is set to Default, then when the droplist is first rendered it will be set to one of the non-Default options (matching whatever the "Show Desktop Notifications For" Account Preference is set to).

### Steps to reproduce:

1. Enter a channel.
2. Click on the Bell icon ("Notifications Preferences")
3. Set Desktop > Alerts to "Use Account Preference" aka "Default".  Click Save.
4. Click the Avatar menu > My Account > Preferences
5. Set "Notifications > Show Desktop Notifications For" to All Messages.  Click Save.
6. Return to the channel's Notification Preferences (steps 1 and 2)

### Expected behavior:

The Desktop Alerts should be set to Use Account Preference

### Actual behavior:

The Desktop Alerts is set to All Messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 15
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Chrome 83.0.4103.116
- Operating System: MacOS Catalina 10.15.5

**Comment by aradhya-gupta** [comment]
I would like to work on this issue.

**Comment by rodrigok** [comment]
@aradhya-gupta I don't think it's the correct way to fix this. Need to understand why it's not persisting the choice first and solve this specific issue because default doesn't mean a specific option there, but the option selected in the user's preferences panel or at the admin area.

**Comment by aradhya-gupta** [comment]
Agreed! The value should persist.

**Comment by aradhya-gupta** [comment]
I've been working on this issue. I have some questions:

1) Does changing the values from the User's preferences panel changes/sets the default values or does it change/update the preferences for each channel( which seems to be happening currently)?

2) What happens in a case when we are the user and the admin sets the default as suppose "All Messages" and we set it to "Mentions" in our preferences pannel? What should ideally happen in case of a conflict between the default values set by the admin and the user?

It would be a great help if someone could please explain the ideal behaviour!
Thanks in advance.
@rodrigok

**Comment by sampaiodiego** [comment]
Closing as invalid since the rewrite of the Notification Preferences screen to React.
