### ISSUE TITLE
Rocketchat default Server

### ISSUE THREAD

**Issue by TKroniger** [RocketChat/Rocket.Chat#18381]
### Description:

I installed RocketChat on an Ubuntu Server and now i want to share it with some people. Moste of the people are just using a smartphone and are not that familiar typing adresses. Now I want my Serveradress as default adresse, so no one has to type it therself. So when they start the app all they have to do is login.

### Steps to reproduce:

1. Checked Code
2. was confused
3. need help

### Expected behavior:

Default Server preinstalled.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Android
- Deployment Method: Mobil
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: RocketChat.apk
- Operating System: Android

**Comment by gabriellsh** [comment]
I suggest you go to `Administration > Users > Invite` and invite the users by their emails. You could also enter a channel, an go to `Members > Invite` and copy the invite link, then send it to the user by their preferred method.

You COULD change the string in the mobile app, rebuild the whole app and then release it to your users somehow, but I think that's too much trouble to avoid just typing/copying a simple URL. Anyway, I hope I could help!
