### ISSUE TITLE
Default incoming WebHook doesn't work

### ISSUE THREAD

**Issue by akopitsa** [RocketChat/Rocket.Chat#1839]
I istalled RocketChat (cloned from git and run with docker-compose)

Then, I try to  run my default webhook

curl -X POST --data-urlencode 'payload={"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' http://192.168.0.127:3000/hooks/geKr7aGbQGRzTpBLF/tKbmNK3j4CATFy29c/FfmHUT%2FgCxoy3hK297BFKbXknY%2Fi3hepKp33%2BB6EI1Q%3D

But always I have an error
curl: (52) Empty reply from server

Whats wrong ?

**Comment by engelgabriel** [comment]
What does the log of the server says?

**Comment by akopitsa** [comment]
I run docker-compose logs, then enter in the browser Webhook URL
http://192.168.0.127:3000/hooks/geKr7aGbQGRzTpBLF/tKbmNK3j4CATFy29c/FfmHUT%2FgCxoy3hK297BFKbXknY%2Fi3hepKp33%2BB6EI1Q%3D

Anything on logs and blue screen in Browser

**Comment by akopitsa** [comment]
I got error

{"status":"error","message":"API endpoint does not exist"}

**Comment by bsdcon** [comment]
I get a similar behaviour when I try the default suggested curl command: after the request is sent, there is a long timeout waiting for the reply and then just that "Empty reply from server" error.

**Comment by rodrigok** [comment]
@akopitsa @bsdcon which version are you using?

To get the version go to `YOUR_SERVER_URL/api/info`

**Comment by akopitsa** [comment]
@rodrigok 
{
  "version": "0.11.0",
  "compile": {
    "date": "2015-12-30T15:51:53.829Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 5065953280,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2828",
    "branch": "develop",
    "tag": ""
  },
  "commit": {
    "hash": "147ce2d626a37c462de8592c39d2d8ca54e4067e",
    "date": "Wed Dec 30 13:28:37 2015 -0200",
    "author": "Marcelo Schmidt",
    "subject": "Button to test SMTP settings; No need to reload server for SMTP settings to take effect; Closes #1246 Checks SMTP Settings in #1492"
  },
  "tag": "v0.11.0",
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": true,
    "version": "GraphicsMagick 1.3.20 2014-08-16 Q8 http://www.GraphicsMagick.org/\nCopyright (C) 2002-2014 GraphicsMagick Group.\nAdditional copyrights and licenses apply to this software.\nSee http://www.GraphicsMagick.org/www/Copyright.html for details.\n\nFeature Support:\n  Native Thread Safe       yes\n  Large Files (> 32 bit)   yes\n  Large Memory (> 32 bit)  yes\n  BZIP                     yes\n  DPS                      no\n  FlashPix                 no\n  FreeType                 yes\n  Ghostscript (Library)    no\n  JBIG                     yes\n  JPEG-2000                yes\n  JPEG                     yes\n  Little CMS               yes\n  Loadable Modules         no\n  OpenMP                   yes (201307)\n  PNG                      yes\n  TIFF                     yes\n  TRIO                     no\n  UMEM                     no\n  WebP                     no\n  WMF                      yes\n  X11                      yes\n  XML                      yes\n  ZLIB                     yes\n\nHost type: x86_64-pc-linux-gnu\n\nConfigured using the command:\n  ./configure  '--build' 'x86_64-linux-gnu' '--enable-shared' '--enable-static' '--enable-libtool-verbose' '--prefix=/usr' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--docdir=${prefix}/share/doc/graphicsmagick' '--with-gs-font-dir=/usr/share/fonts/type1/gsfonts' '--with-x' '--x-includes=/usr/include/X11' '--x-libraries=/usr/lib/X11' '--without-dps' '--without-modules' '--without-frozenpaths' '--with-perl' '--with-perl-options=INSTALLDIRS=vendor' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-Wall -g -fno-strict-aliasing -O2' 'LDFLAGS=' 'CXXFLAGS=-Wall -g -fno-strict-aliasing -O2'\n\nFinal Build Parameters:\n  CC       = gcc -std=gnu99\n  CFLAGS   = -fopenmp -Wall -g -fno-strict-aliasing -O2 -Wall -pthread\n  CPPFLAGS = -I/usr/include/X11 -I/usr/include/freetype2 -I/usr/include/libxml2\n  CXX      = g++\n  CXXFLAGS = -Wall -g -fno-strict-aliasing -O2 -pthread\n  LDFLAGS  = -L/usr/lib/X11 -L/usr/lib -L/usr/lib\n  LIBS     = -ljbig -llcms2 -ltiff -lfreetype -ljasper -ljpeg -lpng12 -lwmflite -lXext -lSM -lICE -lX11 -llzma -lbz2 -lxml2 -lz -lm -lgomp -lpthread\n"
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-05 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib\n\n"
  }
}

**Comment by rodrigok** [comment]
@akopitsa can you update your server to the latest version an try again?

**Comment by akopitsa** [comment]
@rodrigok 
I updated but nothing changed. Default incoming WebHook doesn't work

**Comment by rodrigok** [comment]
@akopitsa can you provide a print of your webhook config page?

**Comment by akopitsa** [comment]
@rodrigok 
how can I make it better ? Maybe screenshot ?

**Comment by rodrigok** [comment]
@akopitsa yes

**Comment by engelgabriel** [comment]
@akopitsa are you sure you have updated? Can you please go to `YOUR_SERVER_URL/api/info` and confirm that you are using "version": "0.13.0"?

**Comment by akopitsa** [comment]
@engelgabriel 
I did git pull from master branch and then rebuilt containers or I need to use develop branch ?

**Comment by akopitsa** [comment]
@rodrigok 
![Image 1]
(http://storage5.static.itmages.com/i/16/0111/h_1452520893_7213053_f782f8c5a4.png)


![Image 2]
(http://storage1.static.itmages.com/i/16/0111/h_1452521010_9255381_c208c77036.png)

**Comment by engelgabriel** [comment]
It *should* be enough, but we go to YOUR_SERVER_URL/api/info and confirm that you are using "version": "0.13.0"?

**Comment by akopitsa** [comment]
@engelgabriel 
You are right. still 0.11.0
How can I update without lost data ?
I clonned from git and run docker-compose up -d

**Comment by akopitsa** [comment]
@engelgabriel 
@rodrigok 
I got new version

{
  "version": "0.13.0",
  "compile": {
    "date": "2016-01-11T14:27:49.945Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 4943417344,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2936",
    "branch": "0.13.0",
    "tag": "0.13.0"
  },
  "commit": {
    "hash": "15d3e44efb14f51419291738944707b459d9a0c5",
    "date": "Mon Jan 11 12:09:58 2016 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1854 from RocketChat/lingohub"
  },
  "tag": "0.13.0",
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-05 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib\n\n"
  }
}

**Comment by engelgabriel** [comment]
Is the problem still happening? The URL on your screenshot is different from the one on your curl example on the top.

**Comment by akopitsa** [comment]
@engelgabriel 
Yes, also container with hubot can't start

**Comment by engelgabriel** [comment]
Logs?

**Comment by akopitsa** [comment]
@engelgabriel 
can't connect to mongo:27017

**Comment by akopitsa** [comment]
@engelgabriel 
I did full reinstall
And now command with curl works fine , I get message, but if I use Webhook URL without curl only http/https url I get error {"status":"error","message":"API endpoint does not exist"}

**Comment by rodrigok** [comment]
@akopitsa what do you means with "without curl"? Are you trying to open the URL in your browser?

The URL exists for the method **POST**, if you open via your browser you are doing a **GET** request.

**Comment by akopitsa** [comment]
@rodrigok 
Yes, I mean I tried to open URL in my browser
Does webhook work only with POST method ?

**Comment by rodrigok** [comment]
@akopitsa yes, you need to pass the message data in the body of the request, you can't do that using GET.
