### ISSUE TITLE
Disabling User Data Download does not seem to disable at least the background job on the server side

### ISSUE THREAD

**Issue by Gerporgl** [RocketChat/Rocket.Chat#18409]
### Description:

Going into the User Data Download under the Administration web interface and disabling the "Enable User Data Download" does not appear to disable the background server job according to server side logs.

Also, as an extra thing related to this issue, I could not find much information or documentation about what the user data download does and what is the purpose of it (like who has access to it, what it contains, etc.). With backups every day and less than 10 users, I do not see the point of this functionality (at least the way I understand it) for my use case.

### Steps to reproduce:

As an admin user, go in the Administration panel in rocket chat web interface
Locate User Data Download
Disable it
Save
Restart the server on the server side to be sure all settings are applied

### Expected behavior:

In the server log, you should no longer see every 2 minutes these kind of logs:
SyncedCron ➔ info Starting "Generate download files for user data".
SyncedCron ➔ info Finished "Generate download files for user data".

### Actual behavior:

The server keeps logging the messages as if it is still doing the user data download stuff

Alternatively, keeping the User Data Download enabled but with a Processing Frequency set at 200000000 (minutes) seems to disable those logs, at least for a long time I suspect.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu Server 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enable (oplog enable)
- NodeJS Version: 12.6.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Kubuntu 20.04

**Comment by piotrkochan** [comment]
I can confirm
