### ISSUE TITLE
Deploy Rocket.chat on Shared VPS

### ISSUE THREAD

**Issue by VincentSurelle** [RocketChat/Rocket.Chat#1840]
Hi,
I'm currently having a VPS with PleskPanel on Ubuntu 14.4.
I'm made a new domain (and it's document root) in plesk panel, then connect thought SSH to the server. I tried the Ansible way to install Rocket.chat on it but it made it crash since it tried to overwrite my previously installed nginx.
On the manual way. It's clearly, remove Plesk packages. I don't know why :/
So Why Shared VPS ? It's like I'm on a shared hosting. But I can't install what I want (Node.js...)
I'm a little confused on what I have to do to make it work. Or if even it's possible.
Can someone give me hand ?
Thanks.

**Comment by MuhClaren** [comment]
Hi Vincent,

If it's a test server running plesk and is OK if plesk gets smoked, you could always try a containerized instance of Rocket.Chat using docker, or docker-compose. The wiki has several guides for deploying via docker: https://github.com/RocketChat/Rocket.Chat/wiki

No idea if docker will interfere with plesk or not, and I make no assertion that to try such a thing won't screw up your plesk integrity, so please only consider doing such testing on a non-production / lab server which can be re-imaged if necessary.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this due to inactivity.  Please reach out to us on our demo server in the [#support](https://demo.rocket.chat/channel/support) channel for assistance.
