### ISSUE TITLE
Trying to play around with local API.

### ISSUE THREAD

**Issue by antsmartian** [RocketChat/Rocket.Chat#18403]
### Description:

Local API redirects always. 

### Steps to reproduce:

I just installed Rocket chat on my local machine. I cloned the code and ran it as `meteor` application. I could able to login to the site using the browser, but if I want to test few API's, things doesn't work. 

For example, I'm trying to create a user:

```
curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJF8V47U3QHXSq"     
 -H "X-User-Id: aobEdbYhXfu5hkeqG"     
 -H "Content-type:application/json"      
http://localhost:3000/api/v1/users.create      
-d '{"name": "name", "email": "email@user.tld", "password": "anypassyouwant", "username": "uniqueusername"}'
```

### Expected behavior:

User is created. 

### Actual behavior:

I'm getting an HTML response:

```
<HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>
```

### Server Setup Information:

- Version of Rocket.Chat Server: Latest git clone. 
- Operating System: Ubuntu
- Deployment Method: `meteor npm start`
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1 (came up with meteor)
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
