### ISSUE TITLE
invite-all-from and invite-all-to commands don't work with multibyte room names.

### ISSUE THREAD

**Issue by tk-suzuki** [RocketChat/Rocket.Chat#18413]
### Description:

The invite-all-from and invite-all-to commands do not work when I create a room with multi-byte characters, such as Japanese.
Also, if these commands are executed against a room name containing multi-byte characters (e.g. group_開発部, random_ガジェット), they will be executed as the operations for the rooms which are not multi-byte characters only.

### Steps to reproduce:

1. Create public room with name "g_システム管理" and invite some users.
2. Create public room with name "g_Web管理".
3. execute _/invite_all_from #g_システム管理_ in g_Web管理.

### Expected behavior:

All users in g_システム管理 to be invited to g_Web管理.

### Actual behavior:

![invite-all-from](https://user-images.githubusercontent.com/48782652/88750750-246fef00-d191-11ea-9a31-c910c0a0916a.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 20.04.1 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Firefox 78
- Operating System: Windows 10

### Relevant logs:

when I execute /invite_all_from 確認用ルーム:
Exception while invoking method 'slashCommand' TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))     at Object.inviteAll [as callback] (app/slashcommands-inviteall/server/server.js:22:23)     at Object._runningSlashCommand [as run] (app/utils/lib/slashCommand.js:27:42)     at MethodInvocation.slashCommand (app/utils/lib/slashCommand.js:82:24)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 I20200729-11:24:14.634(9) Exception while invoking method 'slashCommand' TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))     at Object.inviteAll [as callback] (app/slashcommands-inviteall/server/server.js:22:23)     at Object._runningSlashCommand [as run] (app/utils/lib/slashCommand.js:27:42)     at MethodInvocation.slashCommand (app/utils/lib/slashCommand.js:82:24)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:719:19     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:717:46     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:715:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by FelipeParreira** [comment]
Hi @tk-suzuki! Thank you for the issue 👍 

I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/18919) should fix it.

Let us know what you think of it, and maybe we can move the discussion to the PR itself.
