### ISSUE TITLE
user profile for internal bot break when change username without adding e-mail

### ISSUE THREAD

**Issue by frossmant** [RocketChat/Rocket.Chat#18435]
### Description:

When changing the username of the default Rocket.Chat bot Rocket.Cat without adding an e-mail it somehow breaks the bot's user profile. That means editing the user in the UI won't work and you can't remove the user.

I was forced to do a mongodb restore to get back to a working profile.

Afterwards i've added an e-mail to the Rocket.Cat before changing it's name, that did work correctly and did not break it's profile.

### Steps to reproduce:

1. Go to administration
1. Click on Users
2. Click on Rocket.Cat
3. Click on Edit
4. Change username from Rocket.Cat to eg. Rocket.Hamster
5. Click Save (when e-mail is blank for the user)

Try again and it will fail when editing the user profile

1. Go to administration
1. Click on Users
2. Click on Rocket.Cat
3. Click on Edit
### Expected behavior:

You should be able to edit the bot's user profile.

### Actual behavior:

The bot's user profile will break and cannot be displayed in the UI.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: OpenSUSE Leap 15.2 | 5.3.18-lp152.20.7-default
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.0
- MongoDB Version:3.6.8

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: macOS

### Additional context

NA

### Relevant logs:

No logs related to this was displayed when trying to edit the user profile. I have not tried to enable debugging mode.

**Comment by frossmant** [comment]
I was successfully able to solve this by doing a full restore of rocket.chat before the change and then added an e-mail to the bot user before changing it's name.

**Comment by MichaelSluydts** [comment]
Also got this after editing some slack-imported users without email. Now get a blank page when trying to edit account both as user and admin. JS error below.

TypeError: e.find is not a function
    at eval (/client/admin/users/UserInfo.js:1)
    at Object.useMemo (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)
    at n.useMemo (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:449)
    at x (/client/admin/users/UserInfo.js:1)
    at po (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)
    at Ho (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)
    at Zo (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)
    at us (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)
    at ds (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)
    at Xs (98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473)

**Comment by frossmant** [comment]
it seems like i get the same issue for users that register a new account on my rocket.chat installation.

I have "Manually Approve New Users" set on my server.

**Comment by hipoloco** [comment]
I have the same problem. When I try to edit the profile of any user without email, this message appears in the browser console:

`TypeError: e.emails[0] is undefined
    A /client/admin/users/EditUser.js:1
    T /client/admin/users/EditUser.js:1
    po https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Zo https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    us https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    ds https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Xs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Qs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Hs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    hs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    To https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    n /client/hooks/useEndpointDataExperimental.js:1

    ki https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    callback https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    xi https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    vi https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    is https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    fs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Js https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    unstable_runWithPriority https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:491
    Js https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Xs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Qs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    Hs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    hs https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    To https://domain.com/98cbd60f7c9f791e528b7293c7741c4255338a15.js?meteor_js_resource=true:473
    n /client/hooks/useEndpointDataExperimental.js:1`

**Comment by xalunda** [comment]
Same issue.

**Comment by qxpat** [comment]
It seems like various functions of Rocket.Chat break when a user doesn't have an email address, but this can happen for bots or when using an OAuth provider that doesn't return email addresses.

I was able to work around this issue by editing the data in the DB directly. First list all the users (you might need a more precise query if you have a lot of users):

```
> db.users.find({}, {emails: 1, username: 1})
{ "_id" : "rocket.cat", "username" : "rocket.cat" }
{ "_id" : "omitted", "emails" : [ { "address" : "abc@example.org", "verified" : false } ], "username" : "abc" }
{ "_id" : "omitted", "emails" : [ { "address" : "def@example.org", "verified" : false } ], "username" : "def" }
{ "_id" : "omitted", "username" : "ghi", "emails" : { "0" : { "verified" : false } } }
{ "_id" : "omitted", "username" : "jkl" }
```

In this example the first 3 users are fine, but the last two are having problems editing their profile. One of these users has a hash instead of an array for the `emails` property, and the other is missing the `emails` property.

To fix this:

```
> db.users.updateOne( {username: 'ghi'}, {$set: {emails: [{address: 'ghi@example.org', verified: false}]}} )
```

and so on for each user affected.

**Comment by robertfromont** [comment]
Seeing this too, while trying to update the avatar of a bot (version 3.7.0)

Looking in the database, I can see:

```
{
	"_id" : "...",
	"username" : "poll.bot",
	"emails" : {
		"0" : {
			"verified" : false
		}
	}
}
```

If I execute the following with `mongo`:

```
db.users.update( { username : 'poll.bot' }, { $unset : { emails : true } })
```

...then the problem goes away.

**Comment by qxpat** [comment]
On version 3.6.2 at least, I need to actually set an email address, unsetting `emails` does not fix the issue.
