### ISSUE TITLE
Send long message as attachment does not work anymore

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#18431]
### Description:

When a certain message exceeds the character limit, the user is asked if they want to rather send that message as an attachment. When accepting this prompt, nothing happens anymore.

### Steps to reproduce:

1. Try to send a message that exceeds current character limit
2. Click "yes" on dialog prompt
3. Notice how no message is sent

### Expected behavior:

Message with attachment should be sent.

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server:  3.5.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: Docker
- MongoDB Version: Docker

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: macOS 10.15

### Additional context

Nothing in client console at all.

##### Demo video

[![](https://up.frd.mn/nTdIf6VT5O.png)](https://up.frd.mn/uy9eSJcaPN.mp4)

**Comment by zdumitru** [comment]
Related to #18304 and #18355

**Comment by frdmn** [comment]
@zdumitru Ah, didn't catch those. Thx!

**Comment by zdumitru** [comment]
@frdmn That have been fixed in 3.4.3 . If it's still failing in later versions, that issue shouldn't be closed.

**Comment by frdmn** [comment]
@zdumitru There will be an upcoming 3.4.3 release for the 3.4 version retroactively that will include the linked PR/fix above. For users of the 3.5 version, version 3.5.1 will probably include this.
