### ISSUE TITLE
Sound settings are ignored since 3.5.0

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#18441]
### Description:

The user sound settings are ignored and a sound is played everytime a direct message is received.

### Steps to reproduce:

1. Unfocus any private conversation
2. Set sound volume to 0 or use a silent MP3 as custom sound
3. Get a direct message

### Expected behavior:

No sound is played

### Actual behavior:

A sound is played regardless of the user account settings:

![Bildschirmfoto 2020-07-30 um 23 19 36](https://user-images.githubusercontent.com/316763/88976398-43b76b00-d2bc-11ea-84c0-2b24e109fc36.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: Debian 10
- Deployment Method: Docker
- Number of Running Instances: 1 

### Client Setup Information

- Desktop App or Browser Version: 2.17.11 / Google Chrome
- Operating System: MacOS

### Additional context

Started happening after update to 3.5.0

### Relevant logs:

No relevant logs

**Comment by beranPro** [comment]
Same here
https://github.com/RocketChat/Rocket.Chat/issues/18458
