### ISSUE TITLE
Desktop notifications don't work at newest version (3.5.0)

### ISSUE THREAD

**Issue by beranPro** [RocketChat/Rocket.Chat#18458]
### Description:

Simple Push Notification to the Browser don't work on a fresh 3.5.0 install.

### Steps to reproduce:

Log in from two different locations with two different users. Send a direct message from user A to user B.
Also send a message from user B to A.

### Expected behavior:

Get a desktop notification

### Actual behavior:

User B receives a new message and don't get notified. No sound is played and no desktop notification is send out. Only the page title switches from "(•) Chat" to "(1) Chat).

The same for the other way round (B to A).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Operating System: Linux
- Deployment Method: Docker Swarm
- Number of Running Instances: 25
- DB Replicaset Oplog: yes
- MongoDB Version: 4.2

### Client Setup Information

- Browser Version: Chrome 84.0.4147.105 && Firefox 79.0 
- Operating System: Windows

Client Settings:

UserA:
![image](https://user-images.githubusercontent.com/15611411/89130096-84082a80-d502-11ea-9ee4-93a10318aef8.png)

User B:
![image](https://user-images.githubusercontent.com/15611411/89130099-87031b00-d502-11ea-9459-5cf92ed27926.png)

The Button "Test Desktop Notifications" works fine.

### Relevant logs:

`I20200802-18:48:50.337(0) API ➔ debug Success {   statusCode: 200,   body: { message: '{"msg":"result","id":"25"}', success: true } } 
I20200802-18:48:50.339(0) API ➔ debug POST: /api/v1/method.call/sendMessage 
I20200802-18:48:50.387(0) API ➔ debug Success {   statusCode: 200,   body: {     message: '{"msg":"result","id":"26","result":{"_id":"oCeEQRxcgkMYsyKbP","rid":"9fkaNjm4ruqk423JbDKHJPojbRtNrC2Jr6","msg":"test zurück","ts":{"$date":1596394130344},"u":{"_id":"DKHJPojbRtNrC2Jr6","username":"admin","name":"Chat Admin"},"_updatedAt":{"$date":1596394130379},"mentions":[],"channels":[]}}',     success: true   } } 
I20200802-18:48:50.396(0) Integrations ➔ Outgoing WebHook.debug Execute Trigger: sendMessage 
I20200802-18:48:50.399(0) Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: sendMessage {   event: 'sendMessage',   message: {     _id: 'oCeEQRxcgkMYsyKbP',     rid: '9fkaNjm4ruqk423JbDKHJPojbRtNrC2Jr6',     msg: 'test zurück',     ts: 2020-08-02T18:48:50.344Z,     u: { _id: 'DKHJPojbRtNrC2Jr6', username: 'admin', name: 'Chat Admin' },     tmid: undefined,     _updatedAt: 2020-08-02T18:48:50.379Z,     editedBy: undefined,     editedAt: undefined,     emoji: undefined,     avatar: undefined,     alias: undefined,     customFields: undefined,     groupable: undefined,     attachments: undefined,     reactions: undefined,     parseUrls: undefined,     blocks: undefined,     token: undefined,     mentions: [],     channels: []   },   room: {     _id: '9fkaNjm4ruqk423JbDKHJPojbRtNrC2Jr6',     t: 'd',     usernames: [ 'admin', '00509946' ],     usersCount: 2,     msgs: 10,     ts: 2020-08-02T18:30:49.788Z,     uids: [ '9fkaNjm4ruqk423Jb', 'DKHJPojbRtNrC2Jr6' ],     default: false,     ro: false,     sysMes: true,     _updatedAt: 2020-08-02T18:48:31.126Z,     lastMessage: {       _id: 'jaPQdv9xy2fTGBCjj',       rid: '9fkaNjm4ruqk423JbDKHJPojbRtNrC2Jr6',       msg: 'test',       ts: 2020-08-02T18:48:31.016Z,       u: [Object],       _updatedAt: 2020-08-02T18:48:31.115Z,       mentions: [],       channels: []     },     lm: 2020-08-02T18:48:31.016Z   } } 
I20200802-18:48:50.400(0) Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: 9fkaNjm4ruqk423JbDKHJPojbRtNrC2Jr6 
I20200802-18:48:50.402(0) Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20200802-18:49:06.199(0) API ➔ debug POST: /api/v1/method.call/readMessages 
I20200802-18:49:06.203(0) Meteor ➔ method readMessages -> userId: DKHJPojbRtNrC2Jr6, arguments: ["9fkaNjm4ruqk423JbDKHJPojbRtNrC2Jr6"] 
I20200802-18:49:06.208(0) API ➔ debug Success {   statusCode: 200,   body: { message: '{"msg":"result","id":"27"}', success: true } } 
I20200802-18:49:21.385(0) API ➔ debug GET: /api/v1/statistics?refresh=false 
I20200802-18:49:21.391(0) API ➔ debug POST: /api/v1/method.call/instances%3Aget 
I20200802-18:49:21.393(0) Meteor ➔ method instances/get -> userId: DKHJPojbRtNrC2Jr6, arguments: []`

**Comment by beranPro** [comment]
i just checked the mobile push notification and they are working fine.

**Comment by beranPro** [comment]
See also https://github.com/RocketChat/Rocket.Chat/issues/18441

**Comment by d3hof** [comment]
I am observing the same issue for Chromium on Linux Ubuntu 20.04. Same issue for Chrome, Edge on Windows 10. Firefox works fine for some reason, as well as notifications on android and ios. We are using rocket.chat 3.0.0.
