### ISSUE TITLE
Snap stuck to 3.4.2

### ISSUE THREAD

**Issue by Ecphrasis** [RocketChat/Rocket.Chat#18451]
### Steps to reproduce:

1. Go to `snap refresh rocketchat-server`
2. `snap "rocketchat-server" has no updates available`
3. It should update to 3.5.0

### Expected behavior:

snap updates to 3.5

### Actual behavior:

snap stays to 3.4.2, snapstore semms to be stuck to 3.4.2 
![000088](https://user-images.githubusercontent.com/11899009/89060140-c98df180-d362-11ea-8a40-f18a4d57b4c1.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: nothing special
- NodeJS Version: nothing special
- MongoDB Version:nothing special

### Client Setup Information

- Desktop App or Browser Version: nothing special
- Operating System:nothing special

**Comment by iammattmartin** [comment]
It isn't stuck. Snaps always follow a release for testing/Q&A and this can be a week or two.

**Comment by theoneandonly-vector** [comment]
why is latest/stable not 3.4.2 but 2.4?

**Comment by alyandon** [comment]
Why is my snap package managed rocketchat instance displaying a huge banner telling me I should upgrade to 3.5.1 when the latest snap package on the 3.x/stable channel is 3.4.2?  That seems unnecessarily confusing.

**Comment by iammattmartin** [comment]
Because snaps always follow the releases.

If you want to avoid this, upgrade manually.

Snaps carry more risk and they come from the same code base so adding an alert just for that is more work. You can get the current status by running the expected command.

Please expect a lot for something that is free.

**Comment by alyandon** [comment]
> If you want to avoid this, upgrade manually.

If I really desired to manually manage software installs I would not be using package managers to install software.

> Snaps carry more risk and they come from the same code base so adding an alert just for that is more work. You can get the current status by running the expected command.

I value working software and snap packages appear to be one of the most popular install methods so I greatly appreciate the caution in not rushing them out the door.

> People expect a lot for something that is free.

I've spent plenty of my own time helping others install, run and troubleshoot RocketChat for free.  I don't think that me expressing my honest confusion over a banner message displayed prominently in my server instance (once for 3.5.0 and then again for 3.5.1) informing me to upgrade when no upgrade is actually available somehow equates to me having unreasonable expectations of a FOSS project.

Surely you can agree with me that a banner explicitly telling users to upgrade when an upgrade isn't actually available via the chosen method of install is non-optimal UX?  If you don't want to consider a code change to avoid displaying those messages in system packaged versions of RocketChat then perhaps consider altering the content of the messages themselves to make them potentially less confusing for users?
