### ISSUE TITLE
Search Messages - links containing the exact search term become corrupted

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat#18456]
### Description:
When links from search results contain the exact searched term, they become corrupted.

### Steps to reproduce:
1. Open some channel or direct message
2. Paste some URL like https://search.google.com/
3. Click on Search Messages
4. Search for google
5. Click on the link
6. Link is not properly formatted and will contain `https://search.%3Cmark%3Egoogle%3C/mark%3E.com/` due to search term

### Expected behavior:
1. The link should not change

### Actual behavior:
This is how the link is now formatted
![avloft8R](https://user-images.githubusercontent.com/25570106/89096741-17ddd780-d3d9-11ea-9089-1630752c5562.png)

### Server Setup Information:
* Version of Rocket.Chat Server: 3.5.0
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 2
* DB Replicaset Oplog: rs0
* NodeJS Version: Unknown - see rocketchat:3.4.1 image.
* MongoDB Version: 4.2.8

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 2.17.11

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

**Comment by TBG-FR** [comment]
Further discussions in #18770
