### ISSUE TITLE
Rocket.Chat push notifications slow

### ISSUE THREAD

**Issue by larsziegelmann** [RocketChat/Rocket.Chat#18477]
### Description:

Is there a specific reason why the notifications on an Android 10 device is very slow compared to Nextcloud Talk?

### Steps to reproduce:

1. Keep phone idle for 30 minutes after closing Rocket.Chat
2. Send message
3. Receive late notification

### Expected behavior:

Android phone gets notification instantly.

### Actual behavior:
When app closed, notification received after 6 minutes.

![Screenshot_20200804-154308_RocketChat](https://user-images.githubusercontent.com/54264704/89301065-71f4cc00-d669-11ea-905d-b32ffa726244.jpg)

![20200804_154642](https://user-images.githubusercontent.com/54264704/89301302-d2840900-d669-11ea-89bd-704a06d7380d.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: linux
- Deployment Method: docker / UCS
- Number of Running Instances: 5-10
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 84.0.4147.105
- Operating System: Windows 10
- Mobile app version: 4.9.0.2132

**Comment by geekgonecrazy** [comment]
Do you have any other devices connected?  If there is another device like web connected and that device was active it won’t send direct to phone.  Gives a few before sending.

**Comment by larsziegelmann** [comment]
We have PCs connected via web, but when this scenario took place they were disconnected.

**Comment by jmessy919** [comment]
I have a similar issue, here: https://github.com/RocketChat/Rocket.Chat/issues/18559

**Comment by geekgonecrazy** [comment]
I know the bot closed.  But between the PR to change the priority on notifications and our change to the gateway this should also be resolved
