### ISSUE TITLE
[NEW] Provide /api/v1/channels.setRetention method for channels retention policy

### ISSUE THREAD

**Issue by col-panic** [RocketChat/Rocket.Chat#18472]
### Description:

The channels api currently misses a method to update a channels retention policy. Getting the
retention policy of a channel is already part of the default channel info, as the following response shows

```
...
"_updatedAt":"2020-08-04T08:03:21.541Z",
"retention":{"enabled":true,"overrideGlobal":true,"maxAge":10,"excludePinned":true},
"description":"elexis-server"
...
```

### Steps to reproduce:

1. Go to https://docs.rocket.chat/api/rest-api/methods/channels
2. Try to find a way of updating retention settings via API

### Expected behavior:

A means to perform the update via API

### Actual behavior:

None

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System:

### Additional context

None

### Relevant logs:

None

**Comment by leManu** [comment]
This functionality is needed for https://github.com/EsupPortail/esup-mod_rocketchat. We are planning to implement such functionality in the Moodle plugin (see https://github.com/EsupPortail/esup-mod_rocketchat/issues/21), but whithout a proper method in the Rocket.Chat API this would be hard.

**Comment by bseclier** [comment]
Agreed, it would be a nice feature to have in the API !

**Comment by johncrisp** [comment]
Does this still exist on 3.14 ?

**Comment by col-panic** [comment]
@johncrisp According to https://developer.rocket.chat/api/rest-api#channels there is not yet an option to get/set the retention on a channel.  If I retrieve the channel information on 3.14 (the following snipped) i don't see any values transmitted that seem to relate to the retention policy: 

```
{
    "channel": {
        "_id": "QCKqN3c5Gu87q2ywo",
        "name": "name",
        "fname": "name",
        "t": "c",
        "msgs": 1203,
        "usersCount": 2,
        "u": {
            "_id": "9gLYMGwAt7NzH3W8B",
            "username": "SomeUser"
        },
        "customFields": {},
        "ts": "2020-08-26T12:28:56.613Z",
        "ro": false,
        "default": false,
        "sysMes": true,
        "_updatedAt": "2021-04-02T07:20:30.422Z",
        "lastMessage": {
            "alias": "ALIAS",
            "msg": ":warning: 02.04.2021 08:20:30.050 _Task  _",
            "attachments": [
                {
                    "color": "#FFDB00",
                    "text": "state = FAILED, result = [{=jcifs.smb.: Failed to : 0.0.0.0<00>/}]",
                    "ts": "1970-01-01T00:00:00.000Z"
                }
            ],
            "parseUrls": false,
            "bot": {
                "i": "PNxfwTeRTLvYitBEo"
            },
            "groupable": false,
            "ts": "2021-04-02T07:20:30.352Z",
            "u": {
                "_id": "m4FPvfxAtDC2kJCLa",
                "username": "name",
                "name": "name"
            },
            "rid": "QCKqN3c5Gu87q2ywo",
            "_id": "srt5taq5MrfLAaHTZ",
            "_updatedAt": "2021-04-02T07:20:30.415Z",
            "mentions": [],
            "channels": []
        },
        "lm": "2021-04-02T07:20:30.352Z"
    },
    "success": true
}
```

**Comment by leManu** [comment]
There is an undocumented method available in the REST API (big thanks to @cperves for the tip) : `rooms.saveRoomSettings` (https://github.com/RocketChat/Rocket.Chat/blob/f53825557cbf760e42c315f43faf8b8a950250e1/app/api/server/v1/rooms.js#L356)

You can POST to this method all the room settings : https://github.com/RocketChat/Rocket.Chat/blob/b4cd0b84f2b653b14ee2ee1e3c47438c9da0ab76/app/channel-settings/server/methods/saveRoomSettings.js

It is possible to update all the retention settings by this way through the API.

Be warned, it seems you have to update some parameters on a second pass after setting `retentionEnabled` and `retentionOverrideGlobal` fro the room.

Maybe a REST API doc maintainer should be glad to update the documentation ?

**Comment by col-panic** [comment]
Thanks for the info, I don't see however, what the format of the settings is I would have to set here. As the settings are not
part of the channels info (as documented in my previous post). Is this https://github.com/RocketChat/Rocket.Chat/blob/f53825557cbf760e42c315f43faf8b8a950250e1/app/models/server/models/Rooms.js the model of a room?

**Comment by cperves** [comment]
theses are the two consecutives requests I sent to set retention in rooms:
* first to declare rententionOverride
```shell
curl -H "X-Auth-Token: XXXX"      -H "X-User-Id: XXX"      -H "Content-type: application/json"     https://myrocketchat.instance.fr/api/v1/rooms.saveRoomSettings      -d '{"rid": "roomid",  "retentionOverrideGlobal": true, "retentionEnabled":true}'
```
second to mix maxage and other retention parameters since in line 307 of saveRoomSettings.js there is a delete for other parameters
```shell
curl -H "X-Auth-Token: XXX"      -H "X-User-Id: XXX"      -H "Content-type: application/json"     https://myrocketchat.instance.fr/api/v1/rooms.saveRoomSettings      -d '{"rid": "roomid",  "retentionExcludePinned": false, "retentionMaxAge": "365", "retentionFilesOnly" : false}'
```

**Comment by col-panic** [comment]
@cperves thanks a lot - works as expected for 3.18.3!
