### ISSUE TITLE
Bug(?): livechat guests can join public channels

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#1848]
I'm not sure if it's intentional or not (I'm guessing it's not because the channel list is not visible), but as a livechat guest I can join public channels by directly typing in the url myserver.com/channel/general for example.

**Comment by sampaiodiego** [comment]
thanks for the input @lvh1 
we already know about this behavior. the problem is, the guest is a real logged in user on the rocket.chat with almost no permissions.. but since channels are public, he can join them if he knows how to do it.

but we will fix that soon.

**Comment by nmolinski** [comment]
Really hoping this gets fixed soon as it prevents RocketChat from being used for commercial use. Can't have guests access the chat page.

**Comment by DaBlitzStein** [comment]
This is not fixed as today and that make it unusable for us.
