### ISSUE TITLE
Upload from NextCloud WebDAV stuck at 0%

### ISSUE THREAD

**Issue by KamyarP** [RocketChat/Rocket.Chat#18482]
### Description:

I can successfully add the WebDAV server and view my files in nextcloud from rocketchat. But the upload progress stays stuck at 0%.
using developer tools, I can see I get a 400 bad request when calling https://[rocketchataddress]/api/v1/method.call/ufsCreate

### Steps to reproduce:
1. open a chat. under WebDAV click on Add Server
2. Add a nextcloud WebDAV account
1. Add + in a chat
2. Click on the defined WebDAV server 
3. Choose a file and click send

### Expected behavior:

The file should be uploaded and sent successfully

### Actual behavior:

The upload progress is stuck at 0% and the ajax call fails:
![screenshot](https://user-images.githubusercontent.com/720436/89328438-a3d65480-d6a2-11ea-9b42-6b0d7c54e6b1.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.5.1
- Operating System: centos-release-7-8.2003.0.el7.centos.x86_64
- Deployment Method:  tar (exact steps from https://docs.rocket.chat/installation/manual-installation/centos) except for the reverse proxy site
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.19

### Client Setup Information

- Browser Version: Google Chrome v84.0.4147.105
- Operating System: Windows 10

### Additional context

rocketchat  is hosted behind an nginx reverse proxy. both nextcloud and rocket are set up with valid SSL certificates.
normal uploads work fine.
Storage type is set to file system. Storage system path is set to (/tmp/ufs).  "Protect Uploaded Files" is disabled. The upload directory's (/tmp/ufs) owner is rocketchat user and is chmod to 777. Site Url is set correctly to https://[rocketchataddress].
nginx config: 
[default.conf.txt](https://github.com/RocketChat/Rocket.Chat/files/5023795/default.conf.txt)
Also, port 80 is redirected (301) to port 443 in nginx.conf

### Relevant logs:
There is no entry in Administration->View Logs

**Comment by KamyarP** [comment]
Update: normal uploads are not working too

**Comment by matthieu637** [comment]
Same issue here, after a clean snap installation on Ubuntu 18.04 Rocket.Chat Server 3.5.2 with nginx reverse proxy.
File uploading from computer is working, but if I upload from Nextcloud or another WebDAV server it is stuck at 0%.

Client: Linux client or browser (Firefox).

```
XML Parsing Error: no root element found
Location: https://IP_ADDR:PORT/api/v1/method.call/ufsCreate
Line Number 1, Column 1: ufsCreate:1:1
Error: Bad Request
    originalCallback https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:886
    processTwoFactorError https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:886
    a https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:886
    c https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:433
    fireWith https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:433
    T https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:433
    n https://IP_ADDR:PORT/e49465247681928f62c29836b6a5fe7e1714f082.js?meteor_js_resource=true:433
e49465247681928f62c29836b6a5fe7e1714f082.js:888:213916
```

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/18883
