### ISSUE TITLE
/api/v1/livechat/visitor deprecated -> endpoint does not exist ?!

### ISSUE THREAD

**Issue by andredanner** [RocketChat/Rocket.Chat#18498]
### Description:

Hi all,

maybe quite a simple topic, but I was not able to find any information of what's wrong with the API here. I tried to call
the above mentioned api, like documented here: https://docs.rocket.chat/api/rest-api/methods/livechat/visitor

I got the following response

{"status":"error","message":"API endpoint does not exist"}

Any ideas ?

BR Andre

### Steps to reproduce:

1. call of api accordingly

### Expected behavior:

Getting visitors data, e.g.

{
  "visitor": {
    "name": "Livechat Visitor",
    "email": "visitor@rocket.chat",
    "token": "iNKE8a6k6cjbqWhWd",
    "phone": "55 51 5555-5555",
    "customFields": [{
      "key": "address",
      "value": "Rocket.Chat street",
      "overwrite": true
    }]
  }
}

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.2
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.15.1
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: chrome Version 84.0.4147.105 (Offizieller Build) (64-Bit)
- Operating System: WIN 10

**Comment by gabriellsh** [comment]
Would be really nice if you sent the curl call you made. I checked the code and indeed the endpoint does exist. Can you provide that bit of information? Thanks!

**Comment by andredanner** [comment]
Thanks a lot for the fast reaction :-) It seems I have misinterpreted the error message as it is indicating the endpoint is missing, so I have overseen a mistake in the json body ..

Maybe a short question regarding the use case that I am currently in and where I do not see documentation of how to solve it.
What I basically wanted to implement is an integration from telegram(bot) to rocket.chat, but the incoming webhook configuration does not allow to address messages into livechat - only #channels and @users are allowed.

So I came along thinking of using the REST API methods to implement my own bot-client logic - starting with registration of visitors and so on ....

**Comment by renatobecker** [comment]
> Thanks a lot for the fast reaction :-) It seems I have misinterpreted the error message as it is indicating the endpoint is missing, so I have overseen a mistake in the json body ..
> 
> Maybe a short question regarding the use case that I am currently in and where I do not see documentation of how to solve it.
> What I basically wanted to implement is an integration from telegram(bot) to rocket.chat, but the incoming webhook configuration does not allow to address messages into livechat - only #channels and @users are allowed.
> 
> So I came along thinking of using the REST API methods to implement my own bot-client logic - starting with registration of visitors and so on ....

Yeah, you can easily integrate external systems to Omnichannel through the REST API endpoints.
To achieve that, you will need to:
- Register the visitor(If it's registered yet) - Remember to use the correct HTTP verb -> POST
- Get an Omnichannel Room
- Send messages to the room

To receive the messages sent by agents, you can rely on the Omnichannel Webhooks.

**Comment by gabriellsh** [comment]
Closing this since it's no longer an issue.
