### ISSUE TITLE
Screensharing feature doesn't work on Firefox

### ISSUE THREAD

**Issue by maxsdw** [RocketChat/Rocket.Chat#1850]
Screensharing feature doesn't work on Firefox, instead I'm having this error inside the console log. (Rocket.Chat plugin was installed correctly and the browser was relaunched).

<img width="1280" alt="screen shot 2016-01-07 at 9 47 52 am" src="https://cloud.githubusercontent.com/assets/4491025/12234539/b5a98888-b83b-11e5-9ea4-0310796331dd.png">

**Comment by engelgabriel** [comment]
Did you install the Firefox addon? and did you grant it the permission it requested?

**Comment by maxsdw** [comment]
Yes, the Firefox addon was installed correctly, the browser was re-launched, but the permission confirmation is never showed and instead I have the console error attached in the previous comment.

**Comment by MartinSchoeler** [comment]
@maxsdw is this still a issue?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates in a long time, if this bug still exists, please reopen this with updated details. Thanks!
