### ISSUE TITLE
Release for snap

### ISSUE THREAD

**Issue by SDAdham** [RocketChat/Rocket.Chat#18511]
Hello,

Any plans for snap releases? I see snap's latest release is on 3.4.2. See https://snapcraft.io/rocketchat-server

Thanks,
Adham

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by geekgonecrazy** [comment]
https://docs.rocket.chat/installation/snaps#when-will-my-snap-installation-get-the-latest-release
