### ISSUE TITLE
Can't search a Japanese username

### ISSUE THREAD

**Issue by SakuraiHiroki** [RocketChat/Rocket.Chat#18529]
### Description:

Can't search a Japanese username in the username search.

### Steps to reproduce:

1. Set "[^\x00-\x7F]+" to "UTF8 Names Validation" in Administration / General.
2. Create a user whose user name is Japanese (eg 田中花子), , join some channel or direct message, and send a message.
3. Click on Search Messages
4. Enter Japanese user name

### Expected behavior:

Japanese user names can be searched for.

### Actual behavior:

No results found

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: CentOS 7.5.1804
- Deployment Method: SNAP
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

<img width="873" alt="1" src="https://user-images.githubusercontent.com/58501106/89983816-48642200-dcb3-11ea-8195-772ca0e5ad45.png">

### Relevant logs:

I hope someone can advice on this.

Thank you!

**Comment by Benshi** [comment]
If you use `from:` command, you should not specify _Name_ (ex,. `田中花子`), but _Username_ (ex., `hanako.tanaka`) or `me` .
https://docs.rocket.chat/guides/user-guides/channel-actions#search-messages

🆖 `from:田中花子`
🆗 `from:hanako.tanaka`
🆗 `from:me`

**Comment by damian-centrone** [comment]
already fixed. Tested on 3.8.0
