### ISSUE TITLE
Endless loop at cloud.rocket.chat

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#18522]
### Description:
Trying to connect to cloud.rocket.chat using Connectivity Services results in endless loop.

### Steps to reproduce:

1. Click on login in Connectivity Services
2. Asks for login to cloud.rocket.chat
3. Login with correct credentials, endless loop occurs.

### Expected behavior:
Login to cloud.rocket.chat as expected.

### Actual behavior:
Screencast of login loop: https://file.io/hKzbsDX1rw3v

### Server Setup Information:

- Version of Rocket.Chat Server: 
```
Version | 3.2.2
Apps Engine Version | 1.14.0
Database Migration | 188
Database Migration Date | August 11, 2020 4:28 PM
Installed at | July 31, 2020 5:15 AM
```
- Operating System:  Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1015-raspi aarch64)
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Don't know (Snap default?)
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.17

### Client Setup Information

- Desktop App or Browser Version: Firefox/Chrome/Vivaldi
- Operating System: Windows 10/Linux Mint/Ubuntu

**Comment by nooblag** [comment]
This was fixed by disconnecting all connections and mentions to instance in `cloud.rocket.chat` and removing these entries in database, and re-establishing:

```
db.rocketchat_settings.remove({"_id": "Cloud_Workspace_Id"})
db.rocketchat_settings.remove({"_id": "Cloud_Workspace_Client_Id"})
db.rocketchat_settings.remove({"_id": "uniqueID"})
```

Perhaps this could be prevented by adding better error handling at `cloud.rocket.chat` end?

**Comment by geekgonecrazy** [comment]
Likely a redirect uri mismatch.  Sync helps often in this case.

We’ve also added support to delete registration on. Cloud.rocket.chat.  If you do sync after that it’ll realize it’s not registered
