### ISSUE TITLE
Video/Audio calls doesn't work on mobile devices.

### ISSUE THREAD

**Issue by maxsdw** [RocketChat/Rocket.Chat#1853]
Video/Audio calls doesn't work on mobile devices.

When using the mobile app on an Android phone, the video call is initialized, but the video doesn't work, seems like the application can't access the device camera. 

On iOS, the "START" video call button doesn't do anything.

**Comment by maxsdw** [comment]
We found this plugin that may help us to enable WebRTC on iOS:

https://github.com/eface2face/cordova-plugin-iosrtc

**Comment by maxsdw** [comment]
https://github.com/contra/rtc-everywhere

**Comment by goobersmooch** [comment]
Same problem here. In the iOS app the call and video call buttons do not work. When you click them nothing happens.

**Comment by ManoharPoreddy** [comment]
Hi
@maxsdw ,
@goobersmooch ,

were you successful to find a solution? or the problem on how to go ahead?

if you tried, or found/concluded on something

'Any' help is appreciated.
for us, it's a bit urgent

Thank you
Manohar

**Comment by goobersmooch** [comment]
@ManoharPoreddy Nope, sorry.

**Comment by ManoharPoreddy** [comment]
Same result for us. Thanks for reply, will help others.

**Comment by geekgonecrazy** [comment]
Closing since video calls do work on mobile
