### ISSUE TITLE
Does not send pdf files, image larger than 999kb

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#18554]
Description:

Livechat does not send pdf files, image larger than 999kb, Any file that I send over 999kb is stopped, I can't see any error in the logs either,

Steps to reproduce:

With a livechat conversation open click on + to send the file select a pdf file with more than 999kb

### Actual behavior:

 Server Setup Information:

Version of Rocket.Chat Server: 3.5.2
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v12.18.2
MongoDB Version: v4.0.19

Client Setup Information

- Desktop App or Browser Version: Firefox/Chrome/Opera
- Operating System :Windows 10/Macosx 10.14.5

### Additional context

Relevant logs:
<img width="948" alt="Captura de Tela 2020-08-13 às 19 00 25" src="https://user-images.githubusercontent.com/12038013/90192047-7bccac80-dd98-11ea-9b91-48c60333568a.png">

**Comment by renatobecker** [comment]
What's your `Maximum File Upload Size` setting value?

![Screen Shot 2020-08-13 at 19 24 18](https://user-images.githubusercontent.com/59577424/90193086-9b64d480-dd9a-11ea-874c-714e9677f69c.png)

**Comment by josep112** [comment]
Hi @renatobecker 
This with 104857600, already put -1 also does not work

**Comment by josep112** [comment]
@renatobecker I apologize only now that I saw that I put it wrong in the description, I'm not using debian9 but with docker version: 19.03.12, this is correctly configured at url in Administration> General> Site URL, I can send a file but only up to 999KB

**Comment by josep112** [comment]
I found the problem was not on rocketchat but on nginx I decided by adding the client_max_body_size 100m line;
