### ISSUE TITLE
 Mobile Push Notifications Delayed for 2 minutes

### ISSUE THREAD

**Issue by antoniomorais360** [RocketChat/Rocket.Chat#18556]
### Description:

The push notification in official rocket.chat Android apps (including experimental) is delayed for more than 2 minutes.

### Steps to reproduce:

1. Send a message from user A to user B

### Expected behavior:

A instantly push notification in mobile phone
### Actual behavior:

The push notification comes after 2 minutes or more.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 20.04.1 LTS
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: No information with this name in server information
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome / Opera / Rambox
- Operating System: Windows 10

### Additional context

Device Name: Delayed in Galaxy A30, Working ok in Galaxy A50
When send the test from Administration > Push works fine.

**Comment by ankar84** [comment]
Hi!
I think it could be related to overloaded cloud infrastructure of Rocket Chat https://github.com/RocketChat/Rocket.Chat/issues/18496#issuecomment-673581707
Now it's back to normal I guess..

**Comment by antoniomorais360** [comment]
Hello @ankar84. Now it is working fine. I will close this issue. Thanks for your help again.

**Comment by eengstrom** [comment]
As currently implemented, there is a 120 second delay in sending push notifications if the user is active/online in some client.  See: https://github.com/RocketChat/Rocket.Chat/pull/17357
