### ISSUE TITLE
Broken REST API Endpoint /api/v1/statistics or invalid documentation

### ISSUE THREAD

**Issue by mpdbl** [RocketChat/Rocket.Chat#18605]
### Description:

Calling the API Endpoint /api/v1/statistics with a GET does not provide the expected result.

### Steps to reproduce:

1. Login user with permission `view-statistics`
2. GET call to https://{yourInstanceURL}/api/v1/statistics

### Expected behavior:

According to documentation /api/v1/statistics
>`{ "statistics": { "_id":"wuLkRmSrjmSMhBdTN", [...] }, "success":true }`

### Actual behavior:

> `{ "_id": "wuLkRmSrjmSMhBdTN", "wizard": { [...] }, "uniqueId": "XyEdrQ7gybrj2zURn", "installedAt": "2020-08-17T07:55:24.216Z", "version": "3.5.1", "totalUsers": 2500, "activeUsers": 1497, "activeGuests": 0, "nonActiveUsers": 0, "appUsers": 0, "onlineUsers": 20, "awayUsers": 1, "totalConnectedUsers": 20, [...] "_updatedAt": "2020-08-17T09:18:54.219Z", "success": true }`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.1
- Operating System: Linux
- Deployment Method:  Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Version 84.0.4147.105
- Operating System:

**Comment by FelipeParreira** [comment]
Hi, @mpdbl! Thank you for the issue 👍 

It seems to have been an error in our docs, and we are already fixing it [here](https://github.com/RocketChat/docs/pull/1786).

I am closing this issue.
