### ISSUE TITLE
Cannot deactivate a user when he is owner of a room

### ISSUE THREAD

**Issue by monfardineL** [RocketChat/Rocket.Chat#18616]
### Description:
When you try to deactivate a user and he is the owner of a room, the screen with the button to confirm the action appears grayed out. It is not possible to perform any other action than reload the tab.

### Steps to reproduce:

1. Go to Users list
2. Select a user
3. Click on three vertical dots
4 . Click deactivate
5. Screen gets grayed out with confirmation message on background. No further action is possible.

### Expected behavior:

Be able  to confirm the deactivation action and user get logged out.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.3

- Operating System: Kubernetes 1.17.2
- Deployment Method: Helm Chart
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 4.2.1

### Client Setup Information

- Desktop App or Browser Version: Chrome 84.0.4147.125
- Operating System: Windows 10

### Additional context

Example print attached.

### Relevant logs:

No relevant logs from server. Javascript error from browser attached.

![2020-08-19 23_44_28-Chat BRy Tecnologia](https://user-images.githubusercontent.com/9057896/90711336-d2ddf000-e276-11ea-90cb-1e85e45b5f72.png)
[chat.bry.com.br-1597891758186.log](https://github.com/RocketChat/Rocket.Chat/files/5100402/chat.bry.com.br-1597891758186.log)

**Comment by Gummikavalier** [comment]
I noticed this too when I was deleting a user. Workaround currently is that when the screen turns grey, you can still use keyboard. Press tab twice and then space, and that selects and that confirms the choice.

(Not sure if the amount of tab-presses was two or three.)

**Comment by ankar84** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/18557

**Comment by monfardineL** [comment]
> I noticed this too when I was deleting a user. Workaround currently is that when the screen turns grey, you can still use keyboard. Press tab twice and then space, and that selects and that confirms the choice.
> 
> (Not sure if the amount of tab-presses was two or three.)

Thanks. Mine worked with 4 tabs.

@ankar84 sorry, I took a quick look at issues and didn't found any that seems to be related. Should've looked better.
