### ISSUE TITLE
bug : re-create a private group

### ISSUE THREAD

**Issue by thomasphilibert** [RocketChat/Rocket.Chat#1862]
Hi !

If I delete a private group and then I create a new private group with the same name, this group does not work.

Thomas

**Comment by geekgonecrazy** [comment]
@thomasphilibert the group does not work as in it won't create the group?  Or it creates it but you can't get into the group?

**Comment by thomasphilibert** [comment]
The group not work.
Exemple :  I have created the private group "network". 6 days after, i delete this group and recreate a new group called "network". previous messages reappear (while the popup delete validation indicates that they have been removed) and the textarea is not displayed
<img width="1185" alt="capture d ecran 2016-01-13 a 08 32 14" src="https://cloud.githubusercontent.com/assets/4984828/12287967/dfdacdba-b9d0-11e5-8363-cfb50a8cee8f.png">

**Comment by marceloschmidt** [comment]
@thomasphilibert I assume you deleted it by going to administration / rooms, right?

**Comment by marceloschmidt** [comment]
I just confirmed this is a bug, probably related to deleting rooms via administration.

**Comment by thomasphilibert** [comment]
I Marcelo, yes i have deleted the rooms in admin.
Thomas

**Comment by ledainam** [comment]
i have same bug.
When i delete a private group and re-create with a same name,
It always display room not found
i should reload page to access this room
i attached screenshot for this bug. 
i used rocket chat version 0.52 
![bug](https://cloud.githubusercontent.com/assets/25676833/23346891/eff44566-fcd0-11e6-8069-0e2b76c3bfe2.png)

**Comment by louisemessage** [comment]
Created a private room both as a user and administrator in Rocket.Chat 2.10.5. Deleted this group and then successfully created another group with the same name, again both as an admin and a user.
