### ISSUE TITLE
UI inconsistencies

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#18636]
# Description:

'improvements' have been made to mentions to make them clickable. The colours are a horrendous p*ke yellow as mentioned elsewhere ( https://github.com/RocketChat/Rocket.Chat/issues/18135 ) and as this is based on the alert colour it is not easy to JUST change the mention colour without affecting everything else.

Oddly enough if you @ yourself it is in red. See screenshot.

Just to add to the bad UI you can click on a username/real Name, but they are just plain text colour and the only way you know they are clickable is if you hover over them and a hand appears. 

This is contrary to other clickable links in Rocket eg URLs. They should be coloured or underlined etc.

### Steps to reproduce:

Looks at any Mention. Colour is awful and not easy to change.

Hover over any Real Name/username and see the hand. It also highlights the whole line, not just the link.

### Expected behavior:

Mention colours should be easy to change and not the same colour as the Alert colour.

Real Name/username links should be highlighted with a contrast colour and hover colour the same as any other type of link, and it should be selectable as per the mention colours above.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.x/checked on open.rocket.chat dev version as well (presumably 3.6.x)
- Operating System: N/A
- Deployment Method: N/A
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: Browsers and Rocket.Chat desktop client
- Operating System: Linux

### Additional context

None

### Relevant logs:

None applicable.

### Images 

No Hover - should be underlined or a contrasting colour to indicate clickable

![Highlight1](https://user-images.githubusercontent.com/3800384/90881680-edb18100-e3aa-11ea-84a1-269c03c8de59.png)

Hover - should change colour and ONLY highlight name/username

![Highlight2](https://user-images.githubusercontent.com/3800384/90881691-f30ecb80-e3aa-11ea-916c-adb75b99791e.png)

Mention colours :-(

![Highlight3](https://user-images.githubusercontent.com/3800384/90881702-f86c1600-e3aa-11ea-95f4-2b2d3a523274.png)

**Comment by engelgabriel** [comment]
We will add the same fade on hoover for username and real names as we have on other links. We don't want a different color for usernames as it will make it messier. Also, the different colors for mentions have a logic, that's why they are different for each type of mention.
