### ISSUE TITLE
SAML login return undefined toastr error

### ISSUE THREAD

**Issue by galshiff** [RocketChat/Rocket.Chat#18648]
### Description:

When there is something wrong with the SAML login, for some errors the user get message error of undefined...

### Steps to reproduce:

1. Enable SAML auth on the admin panel settings
2. Choose user without 'email' field provided by the SAML auth
3. Try to login with this user

### Expected behavior:

The user should get an error that explains the real problem with the login.

### Actual behavior:

The user get toastr error of undefined..

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Linux

**Comment by pierre-lehnen-rc** [comment]
Closed by #18649
