### ISSUE TITLE
Can't start UIKit

### ISSUE THREAD

**Issue by AhmedNageh08** [RocketChat/Rocket.Chat#18651]
I don't know how i can activate or use UIKit in livechat .. Thanks in advance 

### Expected behavior:

need to show buttons in livechat

### Actual behavior:

nothing appear i don't know if uikit is already activated by updating rocketchat or should i activate it ?! .. if should i activate it ,  how can i do that ? 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0-rc.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version:4.0.20

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by renatobecker** [comment]
@AhmedNageh08 You're not describing an issue, so please use our forum for questions like this.
Thanks.
