### ISSUE TITLE
Integrating with Jarvis

### ISSUE THREAD

**Issue by modist** [RocketChat/Rocket.Chat#1865]
Hi

Would it be possible to integrate Rocket.chat with https://github.com/kengz/jarvis or similar ?

If so - what is the needed step ?

Currently I have rocketchat running using sandstorm on a local ubuntu-instance - and I have installed Jarvis using npm - but are currently stuck when it comes to the configuration as described in https://github.com/kengz/jarvis#setup

Kind regards

Morten

**Comment by geekgonecrazy** [comment]
@modist this looks to be using hubot under the hood.  So you would just need to include the rocketchat adapter.

Looks like to start with replace slack inside `bin/.env` with `rocketchat`

Then in package.json include: hubot-rocketchat instead of hubot-slack

**Comment by engelgabriel** [comment]
Probably the best idea is to take a good look at Jarvis code and incorporate into Rocket.Cat, and make it a package + BOT installed by default

**Comment by modist** [comment]
Thank you for the advice :+1: 

Will look into hubot - have it running now thanks to https://github.com/RocketChat/Rocket.Chat/wiki/Docker---Ubuntu-with-Nginx-SSL-and-Hubot

Currently trying to integrate with LDAP...
