### ISSUE TITLE
Removing 'Avatar External Provider URL' setting is being ignored

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat#18657]
### Description:

I initially enabled 'Avatar External Provider URL' in Settings -> Accounts. Later on, I deleted the URL and I am syncing the avatars via the REST API now (users.setAvatar).

When I check the nginx access logs of my server, that used to provide the external avatar images, I still see GET requests coming in from the rocket.chat instance. My server responds with 404 status code now, as it's no longer providing the images. When I test the avatar behavior on the rocket.chat instance, I can see that they initially get set correctly, after the REST API call, but soon after get deleted - I assume this is due to rocket.chat still trying to update/retrieve the avatar via the old, deleted, URL that was set in the Settings (and again, is now deleted from that setting entry).

### Steps to reproduce:

1. Enable 'Avatar External Provider URL' setting by providing URL that serves avatar images
2. Reset that setting by deleting the entry in 'Avatar External Provider URL'
3. Check the webserver logs of the previously used avatar provider server and see ongoing GET requests to the deleted avatar url
4. See that avatars in rocket.chat get deleted/overwritten when it tries to retrieve the avatar image from the now deleted old external avatar url

### Expected behavior:

After removing the 'Avatar External Provider URL' setting from the Admin settings, the rocket.chat instance should no longer try to retrieve avatars from that external URL. And the rocket.chat instance should keep the new avatars that are set for example via the REST API.

### Actual behavior:

Avatars get overwritten by failed GET requests to the initially provided 'Avatar External Provider URL'.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.3
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

**Comment by pbenkoe** [comment]
In fact, even if I enter a static URL in 'Avatar External Provider URL' to have a placeholder for all users, I still get requests for old url. Are these queued jobs by any chance? They stay in the queue when they fail and get tried over and over again? How can I flush this queue?

**Comment by MartinSchoeler** [comment]
@pbenkoe can you test again with the 3.7.0 or higher version? We did some heavy work on the avatar displays lately and this issue could be fixed. Thanks!

**Comment by pbenkoe** [comment]
hey @MartinSchoeler, i ended up deleting this rocket.chat instance and setting up a new one, there was no other way to fix this issue. I changed my avatar sync behavior now, unfortunately there is no way to test this now, sorry - thank you for getting back to me though!
