### ISSUE TITLE
After user/guest login, stays on 3 loading dots. Does not redirect to correct chatroom.

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#18652]
# Description:

When a user login's or a guest user login's, they do not get redirected to the chatroom. Sits on 3 loading dots until they visit away and then enter chatroom. This was not an issue in older versions of RC

### Steps to reproduce:

1. Visit a direct room url. ex: channel/public
2. Login as a guest or user

### Expected behavior:

Should take guest or user into the chatroom specified as in the url.

### Actual behavior:

Logged In Users see guest page and then logs them into chat and stays on 3 loading dots, Guest users see 3 loading dots. The only way to get into the chatroom is to click on another action and then go back into the room.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.3
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: v12.14.0
- MongoDB Version: v3.6.12

### Client Setup Information

- Desktop App or Browser Version: Browser (Chrome)
- Operating System: MacOS

### Additional context

happens on 3.5.3 and 3.6.0-rc0, i have tried fresh clean installs using the mongo with RC and using my own RC db server and nothing fixes this. Seems like a code issue.

### Relevant logs:

Server Reports: `Exception while invoking method autoTranslate.getSupportedLanguages Error: Auto-Translate is not allowed [error-action-not-allowed]`

Browser Reports:  `Exception in template helper: TypeError: Cannot read property '_id' of undefined app/app.js?hash=892a31989cbba9a171ffa9c3615080e0ee17a7ac:55020:34` and `Uncaught (in promise) undefined client.js:118`

**Comment by ubergeekzone** [comment]
Update: this issue seems to only happen when guest access is enabled.

**Comment by ubergeekzone** [comment]
@sampaiodiego any idea here?

**Comment by sampaiodiego** [comment]
let me ping @ggazzo

**Comment by ubergeekzone** [comment]
> let me ping @ggazzo

thanks

**Comment by ubergeekzone** [comment]
@ggazzo if you can point me in the right direction, I don't mind contribution of the patch.

**Comment by y377** [comment]
i agree

**Comment by ubergeekzone** [comment]
@ggazzo any assistance would be much appreciated.

**Comment by ubergeekzone** [comment]
@sampaiodiego I really need a fix or the direction to take to fix this issue.

**Comment by ubergeekzone** [comment]
@ggazzo and @sampaiodiego this issue has been here since v3 from what I can tell so far.

**Comment by ggazzo** [comment]
hey sorry for the delay, I'm currently working on this issue... if its something you can help us I will inform/guide you, other case I will open a pr :)

**Comment by ubergeekzone** [comment]
@ggazzo yes I will help on this issue. What do you need me to do?

**Comment by ubergeekzone** [comment]
@ggazzo awaiting your guidance. Thanks

**Comment by ggazzo** [comment]
@ubergeekzone  Please check if the pr solves the problem :v:

**Comment by ubergeekzone** [comment]
@ggazzo so this fixes half the login issue but only fixes guest login, but on iframe login-with-token it takes the user to the guest login and then logins them in and sits on 3 loading dots instead of loading the chatroom. it should take them directly into chatroom and not sit spinning with 3 loading dots.

**Comment by ubergeekzone** [comment]
@ggazzo any luck?

**Comment by ggazzo** [comment]
sorry, not yet ..a busy day here... but I will fix it until the end of the day... You didn't mention the iframe, so I didn't check the case my bad =/

**Comment by ubergeekzone** [comment]
@ggazzo np, ill look for the fix today.

**Comment by ubergeekzone** [comment]
@ggazzo I was taking a look at the iframe login-with-token code and did not fully understand what is going on. I know when I visit the page with the iframe it pops up and says invalid user and then logs the user in and takes them to the room. The proper function should be taken directly to the room as the previous version of RC did in v2.

**Comment by ubergeekzone** [comment]
@ggazzo any luck?

**Comment by ubergeekzone** [comment]
@ggazzo I really need this fixed.. this has been broke since v3 came out... What's the hold up?

**Comment by ubergeekzone** [comment]
@ggazzo PR fixed these issues.
