### ISSUE TITLE
Using Ignore sometimes results in "Undefined" error.

### ISSUE THREAD

**Issue by DNRStudiosTech** [RocketChat/Rocket.Chat#18653]
### Description:

Some users are attempting to open a user profile for username "George S." in our common chat room. However, they are receiving a red background popup "Undefined".

### Steps to reproduce:

1. Click the username in chat room.
2. Click the icon for "Ignore" function.

### Expected behavior:

The user would be ignored, for the user who selected that option.

### Actual behavior:

<img width="848" alt="rocketchat-unidentified" src="https://user-images.githubusercontent.com/70107758/90984594-eb365f00-e543-11ea-877d-ea30c57d71b4.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: Ubuntu 18.04.3 (LTS) x64
- Deployment Method: SNAP
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Desktop Chrome 84.0.4147.125
- Operating System: Max OSX 10.14.6 Mojave

### Additional context

I'm guessing there is an issue when usernames have a space in them, as opposed to no space? Just a guess. But I have not tested that theory yet.

### Relevant logs:

I20200823-16:53:52.588(0) Exception while invoking method ignoreUser Error: Match error: Expected string, got undefined     at check (packages/check/match.js:36:17)     at MethodInvocation.ignoreUser (server/methods/ignoreUser.js:8:3)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:388:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/snap/rocketchat-server/1440/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:388:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9

**Comment by serviceman** [comment]
I am experiencing the same issue and I don't use spaces in usernames.

**Comment by serviceman** [comment]
Issue still present in 3.6.0 on open.rocket.chat
