### ISSUE TITLE
irc-bridge: Catching errors in queue

### ISSUE THREAD

**Issue by glunardi** [RocketChat/Rocket.Chat#18654]
### Description:

The irc bridge queue breaks frequently because of unhandled errors.

### Steps to reproduce:

1. Send messages between IRC and RocketChat users
2. Seems sending a blank line message in a block from RocketChat reproduces
3. The failure would happen to us every few minutes

### Expected behavior:

All supported messages should be forwarded both ways between irc and RocketChat without crashing. 

### Actual behavior:

The queue fails and never recovers. Leaving the two sides disconnected and messages not going through.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: Ubuntu 20.04
- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Google Chrome	84.0.4147.105 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04

### Additional context

This helped with reliability of the irc bridge some. Does not solve everything but we are considering using it this week.

**Comment by glunardi** [comment]
We did not have time to build nicely so we applied our changes directly into our production deployed app.js.

This is the change that James applied:

```
--- app.js~     2020-07-10 14:21:14.000000000 -0700
+++ app.js      2020-08-23 09:42:53.337194456 -0700
@@ -108513,7 +108513,7 @@

       const item = this.queue.dequeue();
       this.logQueue("Processing \"".concat(item.command, "\" command from \"").concat(item.from, "\"")); // Handle the command accordingly
-
+   try {
       switch (item.from) {
         case 'local':
           if (!localCommandHandlers[item.command]) {
@@ -108531,7 +108531,9 @@
           Promise.await(peerCommandHandlers[item.command].apply(this, item.parameters));
           break;
       } // Keep the queue going
-
+   } catch (e) {
+      this.logQueue(e);
+   }

       setTimeout(this.runQueue.bind(this), this.queueTimeout);
     });
```

**Comment by jejb** [comment]
I should add that this is the exception we got that caused runQueue to halt in the irc-bridge:

Aug 23 11:52:33 chat rocketchat[190846]: [irc][bridge][queue] Processing "onJoinRoom" command from "local"
Aug 23 11:52:33 chat rocketchat[190846]: [irc][server] Handling local command: joinedChannel
Aug 23 11:52:33 chat rocketchat[190846]: === UnHandledPromiseRejection ===
Aug 23 11:52:33 chat rocketchat[190846]: TypeError: Cannot destructure property `irc` of 'undefined' or 'null'.
Aug 23 11:52:33 chat rocketchat[190846]:     at RFC2813.joinedChannel (app/irc/server/servers/RFC2813/localCommandHandlers.js:29:20)
Aug 23 11:52:33 chat rocketchat[190846]:     at RFC2813.onReceiveFromLocal (app/irc/server/servers/RFC2813/index.js:172:34)
Aug 23 11:52:33 chat rocketchat[190846]:     at RFC2813.emit (events.js:210:5)
Aug 23 11:52:33 chat rocketchat[190846]:     at RFC2813.EventEmitter.emit (domain.js:475:20)
Aug 23 11:52:33 chat rocketchat[190846]:     at Bridge.sendCommand (app/irc/server/irc-bridge/index.js:136:15)
Aug 23 11:52:33 chat rocketchat[190846]:     at Bridge.handleOnJoinRoom (app/irc/server/irc-bridge/localHandlers/onJoinRoom.js:2:7)
Aug 23 11:52:33 chat rocketchat[190846]:     at app/irc/server/irc-bridge/index.js:84:46
Aug 23 11:52:33 chat rocketchat[190846]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug 23 11:52:33 chat rocketchat[190846]: ---------------------------------
Aug 23 11:52:33 chat rocketchat[190846]: Errors like this can cause oplog processing errors.
Aug 23 11:52:33 chat rocketchat[190846]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Aug 23 11:52:33 chat rocketchat[190846]: Future node.js versions will automatically exit the process
Aug 23 11:52:33 chat rocketchat[190846]: =================================
