### ISSUE TITLE
what happened to hide "user leave" and "user join"

### ISSUE THREAD

**Issue by gstlouisgit** [RocketChat/Rocket.Chat#18663]
Description:
I literally recall and have written down from a post I saw in rocket chat issues that we were able to hide the user join or user left etc comments in channels. This was under admin->message toggle buttons.

I upgraded rocket chat on the server, all these user join and left messages show up now in my channels when they were gone before and now in admin->message these toggles are gone. What happened? I wish I kept the link to that issue...

Steps to reproduce:
create a channel and have several people join

Expected behavior:
in admin->message these toggles are gone now but they were there before 

Actual behavior:
in admin->message these toggles are gone

Server Setup Information:
Version of Rocket.Chat Server:
Version	3.5.2
1.16.0	
202	
August 15, 2020 9:31 AM	
December 26, 2019 3:32 PM	
3 days, 6 hours, 41 minutes, 6 seconds	
zY4v5BXtivttdoybP	
22576	
1	
Enabled	
Operating System:
Centos7
Deployment Method: https://docs.rocket.chat/installation/manual-installation/centos
Number of Running Instances: only one RC server on this
DB Replicaset Oplog: I have no idea what you are talking about
NodeJS Version: v12.18.3
MongoDB Version: MongoDB server version: 4.0.19
Client Setup Information
Desktop App or Browser Version: both on Mac
Operating System: high sierra 10.13.6
Additional context
Relevant logs:
nothing relavent

**Comment by fdellwing** [comment]
![Screenshot_20200825_084903](https://user-images.githubusercontent.com/22813377/91140630-fad2b680-e6af-11ea-8d6d-c95b22df03b4.png)

You can now much more precisely configure this.

**Comment by gstlouisgit** [comment]
@fdellwing Thanks for showing me this.  I can now see it in admin->Message.  It took me a second to find where you can actually hide these things seperatly per channel from what your image hinted.  I can now see it is not in admin it is in the room info on the on the front of app.

Thanks
