### ISSUE TITLE
Use MacOS Notifications

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#1866]
I would like to get notified about new messages via the built in Notification Center of MacOS:
https://support.apple.com/en-us/HT204079

**Comment by rodrigok** [comment]
The desktop notification is working ok via Safari and our Electron App.

Can you explain better your problem?

**Comment by geekgonecrazy** [comment]
@rodrigok sounds like wants to show up in the OSX notification center.  on the web app I don't think this is possible.  But in electron it might be... So this would for sure be an issue for the electron app.

https://github.com/rocketchat/rocket.chat.electron

**Comment by ahosking** [comment]
As far as I can see from both Webapp and RocketChat client, notifications in OSX notification center work only for direct messages.
Channels and Private groups do not show up in the notification center.

**Comment by rodrigok** [comment]
![captura de tela 2016-01-12 as 15 49 13](https://cloud.githubusercontent.com/assets/234261/12271806/26f05004-b944-11e5-90aa-44de323ccce7.png)

@ahosking are you talking about the notification or to keep the notification at the notification center after the notification hide?

**Comment by ahosking** [comment]
@rodrigok I have never seen a notification for Channels or private groups outside of the WebApp/Electron itself.

We are on OS X 10.10.5, RocketChat is on version 0.9.0 according to /api/info

**Comment by rodrigok** [comment]
@ahosking are you using which browser? Works for me on Chrome, Firefox and Safari. Chrome do not use the OS X notification system, but works.

**Comment by ahosking** [comment]
Primarily our OS X users are using the Meteor App.
WebApp use is limited to Chrome.

I'll give Safari a try to confirm.

**Comment by rodrigok** [comment]
With "Meteor App" are you meaning "Electron App" right?

When you use the Electron App you get notifications out of the box, but in browsers you need to accept to receive the notifications, maybe you didn't accept.

You can go to `/account` at your server to see if the notifications are granted, if not there will be a button to active.

**Comment by ahosking** [comment]
Apologies, I meant the "Electron App".
I've got notifications enabled in all clients but still only see direct message notifications in message center.

**Comment by rodrigok** [comment]
@ahosking you do not see the Notification balloon or the history in the "OS X Right Panel"?

**Comment by ahosking** [comment]
I only see the Notification balloon for direct messages.

**Comment by Julime** [comment]
I dont get Notification via Safari nor the Mac Client. Even not for direct messages. In settings, desktop notifications are activated

**Comment by rodrigok** [comment]
Guys, can you record a video about that, we can't reproduce.

**Comment by Julime** [comment]
works now for me. no idea what i've done to get it working =D
