### ISSUE TITLE
Logo Doesn't Update in Adminstration > Assets

### ISSUE THREAD

**Issue by akkari93** [RocketChat/Rocket.Chat#18678]
### Description:

When you go to Assets in the control panel and try to update the logo, it says uploading, uploaded but then nothing happens. The logo resets to the rocket chat one. If you try to update anything else on the page, it updates correctly.

Here's a loom video showing exactly what happens:

https://www.loom.com/share/3190eebf8f2b4919a59070e1ed54b7fa

### Steps to reproduce:

1. Administration > Assets
2. Try uploading a logo as shown in the video above.

### Expected behavior:

Should successfully upload and appear on screen. What happens is that it says uploaded but nothing updates.

### Actual behavior:

Video posted above.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.4
- Operating System: Ubuntu 18.04
- Deployment Method: Cloudron
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: v12.16.2
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Chrome 84.0.4147.135
- Operating System: Windows 10

### Additional context

N/A

### Relevant logs:

N/A

**Comment by pierreozoux** [comment]
I can confirm the same issue. It is not always, but some instances seem broken :/

We do use s3, I don't know if it is important, I think theses assets are still in mongodb..

**Comment by dudanogueira** [comment]
Hi, closing this as it's working in 5.2.0-rc4

If necessary, we can repoen this.
