### ISSUE TITLE
Blank/extra names under Read Receipt message info modal

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#18689]
### Description:
It looks like that the "Info" dialogue does not show any more when a message got read by someone.
Since release 3.6.0 rc0 the Read By list is containing only the avatar of your self (own name is not shown anymore) and the creator of the message.

### Steps to reproduce:

1. Go to a new message which was send with >= 3.6.0 rc0.
2. Click on the three dots and select "Info"
3. You will see your self without name and in case that there are more people in the room only you and the creator.

### Expected behavior:

Possibility so see the list when people read the message

### Actual behavior:

See description.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.6.0 rc2
- Operating System:  CentOS 7
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version:  12.18.3
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App:  2.17.11
- Operating System: Fedora 32

Please let me know if you need additional information.

**Comment by phriedrich** [comment]
I can confirm this behaviour. Attached are three screenshots:

1. Showing the "info" dialogue:

![1_message_info](https://user-images.githubusercontent.com/470153/92084292-7840aa00-edc7-11ea-80bb-524a3d106652.png)

2. The message in the MongoDB

![2_message](https://user-images.githubusercontent.com/470153/92084411-a3c39480-edc7-11ea-97c2-f8002cabadbc.png)

3. Read receipts for the message

![3_read_receipt](https://user-images.githubusercontent.com/470153/92084470-be960900-edc7-11ea-91c3-d00d8f20e1d0.png)

Note the second receipt doesn't have a userID.

**Comment by dieg00uy** [comment]
Same here on version 3.6.0.
Please we need urgent a solution to fix it; is an important functionality for the team.

**Comment by wreiske** [comment]
We are having this issue, too. Tons of reports of messages not being marked as read.
![Clipboard - September 10, 2020 1_14 PM](https://user-images.githubusercontent.com/6295044/92770486-fd980180-f367-11ea-8df2-dada9fe5d095.png)

**Comment by tec-J** [comment]
This problem has been resolved.
`imports/message-read-receipt/server/hooks.js`

`callbacks.add('afterReadMessages', (rid, _ref) => {
  let {
    userId,
    lastSeen
  } = _ref;
  ReadReceipt.markMessagesAsRead(rid, userId,lastSeen);
}, callbacks.priority.MEDIUM, 'message-read-receipt-afterReadMessages');`
　↓
`callbacks.add('afterReadMessages', (rid, _ref) => {
  let {
    userId,
    lastSeen
  } = _ref;
  ReadReceipt.markMessagesAsRead(rid, userId,lastSeen);
}, callbacks.priority.MEDIUM, 'message-read-receipt-afterReadMessages');`

**Comment by binarydad** [comment]
Anyone know if this is fixed in 3.6.1?

**Comment by phriedrich** [comment]
Still broken in 3.6.1

**Comment by spanchy** [comment]
i have same problem. version 3.6.0

**Comment by tec-J** [comment]
Can you support it with the 3.6.2 update?

**Comment by alvarow** [comment]
I don't use read receipts, but users are reporting their channels, DM and discussions are all lit up with unread messages they already read.

I wonder if it is related...

**Comment by binarydad** [comment]
I was able to resolve my issues with read receipts temporarily by going to /opt/Rocket.Chat/programs/server/app/app.js and modifying the line mentioned above by @tec-J. I have a native install, so not sure how this would work with other installations. 

![image](https://user-images.githubusercontent.com/1760607/93238273-3ad90680-f74f-11ea-870b-83193268877f.png)

**Comment by wreiske** [comment]
I fixed it in this PR: https://github.com/RocketChat/Rocket.Chat/pull/18918
