### ISSUE TITLE
Question - Memory usage normal?

### ISSUE THREAD

**Issue by scornet256** [RocketChat/Rocket.Chat#18680]
### Description:

I just migrated our instance like this, with approximate 50 active users:

1) Ubuntu 16.04 / RC 2.4.11 (snap) => 2) Ubuntu 16.04 / RC 3.5.2 (snap) => 3) Ubuntu 20.04 / RC 3.5.2 (snap)

We started with 2c/4gb of memory and all was running well at stage 1... After migrating we saw huge memory pressure and we had to upgrade the VM to *16GB* of memory to keep RC usable ... We still see a lot of memory pressure on the host... Luckily all is running fine, so my question is not to bother anyone, but is this normal behaviour or can we fix something?

### Steps to reproduce:
Follow upgrade plan using backupdb and restoredb functionality of the snap.
(https://docs.rocket.chat/installation/snaps)

### Expected behavior:
I dont know, asking you.

### Actual behavior:
Does this memory usage make sense after upgrading?

### Server Setup Information:

Stage 1:
- Version of Rocket.Chat Server: 2.4.11
- Operating System: Ubuntu 16.04 LTS (patched)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: ?
- MongoDB Version: ?

Stage 2:
- Version of Rocket.Chat Server: 3.5.2
- Operating System: Ubuntu 16.04 LTS (patched)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: ?
- MongoDB Version: ?

Stage 3:
- Version of Rocket.Chat Server: 3.5.2
- Operating System: Ubuntu 20.04 LTS (patched)
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: ?
- MongoDB Version: ?

### Client Setup Information
- Browser Version: Chrome / Firefox
- Operating System: Windows / Linux

### Additional context
Just wondering if 16GB of memory usage is normal.

### Relevant logs:
Memory usage yesterday (Ubuntu 16.04 / RC 2.4.11 (snap):
![memory_before](https://user-images.githubusercontent.com/41006695/91300168-1c609a80-e7a3-11ea-8ff0-8426d4cd470d.png)
Memory usage today (Ubuntu 20.04 / RC 3.5.2 (snap):
![memory_after](https://user-images.githubusercontent.com/41006695/91300174-1ec2f480-e7a3-11ea-9334-9cc26efc02f1.png)

**Comment by alvarow** [comment]
I noticed at upgrading it takes a huge toll on the server... but once it is done, things are back to normal for my instances... I run 3 of them, with session affinity (elb cookie), each docker container hovers around 1gb, and the mongodb (not docker) on a separate machine runs around 2gb, for the primary. I have similar user count... active is more like 30, but there's some timezeone overlap, where it reaches high 50s

**Comment by damian-centrone** [comment]
Nothing to fixe here, tested memory usage on 3.8.0 and its normal.
