### ISSUE TITLE
Run port 3000 on localhost instead of external interface

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#1868]
How does run node/Rocket.Chat on localhost instead of the external interface (which is open to attackers)? 
I have nginx running as a reverse SSL proxy in front of it.

**Comment by geekgonecrazy** [comment]
@improvethings try setting the environment variable `BIND_IP`

So if running via our supported method listed [here](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker)

You would do something like:

```
export BIND_IP=127.0.0.1
``` 

or if inline something like:

```
ROOT_URL=http://your-host-name.com-as-accessed-from-internet/ \
    MONGO_URL=mongodb://localhost:27017/rocketchat \
    PORT=80 \
    BIND_IP=127.0.0.1 \
    node main.js
```

**Comment by improvethings** [comment]
Thanks, this worked. 

For anyone else reading this with an nginx SSL reverse proxy, you also want to change the proxy_pass line in /etc/nginx/conf.d/default.conf to proxy_pass http://127.0.0.1:3000/ instead of your IP/domain name.

**Comment by geekgonecrazy** [comment]
:+1: cool glad this worked for you :smile:

**Comment by aellert** [comment]
It would be great to do the same for mongodb port (default listen to *:27017). I'd ilke to get Mongo listen only on localhost. Where is document environment variables list please ?
