### ISSUE TITLE
Livechat JS setDepartment() not working at all

### ISSUE THREAD

**Issue by echantigny** [RocketChat/Rocket.Chat#18699]
### Description:

I'm trying to use the functionality described here: https://docs.rocket.chat/api/livechat-api#assign-chats-to-a-specific-department but it doesn't work at all.  Tried it with the department name and the department id and it doesn't assign a department at all.

### Steps to reproduce:

1. Create 2 departments and choose not to have them show up on the registration page
2. Add the javascript to a webpage
3. Add the code to set the department like described in the docs (link above)
4. Start a chat and you'll see that the department is not selected at all. Goes to a random agent and doesn't show any department in the Info sidebar

### Expected behavior:

Using the setDepartment JS function should tie the chat to that specific department.

### Actual behavior:

No department is selected at all

### Server Setup Information:

- Version of Rocket.Chat Server:  3.5.3
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog:  ??
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version:  Chrome
- Operating System: Windows 10

### Additional context

Found #9421 that dealt with this exact same issue back in 2018.

**Comment by echantigny** [comment]
For anyone stumbling on this, my temporary fix is to use the onPrechatFormSubmit hook.  When the form is submitted, the department seems to be reset to undefined.  Anything you do to department before the form is subitted is overwritten.

Here's my code
`RocketChat(function() {
    this.onPrechatFormSubmit(function(data) {
        data.department = "Support";
    });
});`

**Comment by shimisnow** [comment]
I can confirm this using either the department label and id.

**Server Setup Information:**

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Debian
- Deployment Method: Manual Installation
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.22.1 - x64
- MongoDB Version: 4.0.3

**Client Setup Information**

- Desktop App or Browser Version: Chrome 91.0.4472.77 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by tiagoevanp** [comment]
Tested at Rocket.Chat 3.17
The problem doesn't happen.

**Comment by maxguru** [comment]
I have the same problem on the latest version. `this.registerGuest()` workaround seems to be working. `this.setDepartment()` and `this.initialize({department: "....." }` does not.

**Comment by maxguru** [comment]
By the way, the problem with `registerGuest()` is that it registers ALL visitors of your website with info passed to the function. This is not what we want. We want to register guests only if they filled out their information themselves.

Anyway, after screwing around with this bug for a while, I came up with the following workaround that seems to work ok:
```
RocketChat(function() {
	this.initialize({department: "department"});
	this.setDepartment("department");
	var rc = this;
	this.onPrechatFormSubmit(function(data) {
		data.department = "department";
		rc.registerGuest({department: "department"});
	});
});
```

One thing to note here is that I've noticed that the bug occurs only for NEW visitors to your website and only on the FIRST page load of them visiting your website. The way to replicate this is to create a new browser profile for every page load. Private/incognito browser window doesn't work due to some other bug making RocketChat JS crash.

This issue should be reopened and the bug should be fixed.

**Comment by maxguru** [comment]
By the way, a little bit better version of the workaround would be the following:
```
RocketChat(function() {
	this.initialize({department: "department"}); // this department setting is lost somewhere
	this.setDepartment("department"); // this department setting is lost somewhere
	var rc = this;
	this.onPrechatFormSubmit(function(data) {
		// data.department = undefined here for brand new website visitors
		data.department = "department";
		rc.registerGuest(data);
	});
});
```

**Comment by maxguru** [comment]
I saw the following error in console that might be related:

```
hooks.js:37 Uncaught TypeError: Cannot read properties of null (reading '_id')
    at pageVisited (hooks.js:37:26)
    at Hn (hooks.js:185:23)
hooks.js:65 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'department')
    at hooks.js:65:49
    at l (5.chunk.e6ee8.js:1:150561)
    at Generator._invoke (5.chunk.e6ee8.js:1:150314)
    at Generator.next (5.chunk.e6ee8.js:1:150924)
    at Fn (5.chunk.e6ee8.js:1:156499)
    at a (5.chunk.e6ee8.js:1:156703)
    at 5.chunk.e6ee8.js:1:156764
    at new Promise (<anonymous>)
    at 5.chunk.e6ee8.js:1:156643
    at setDepartment (hooks.js:64:29)
```

Please note that I am only having the problem described in this issue on a completely blank browser profile on the very first page load.

@tiagoevanp, please reopen this issue.
