### ISSUE TITLE
Invite from url user not join to private group on desktop client

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#18695]
### Description:
after some user follow by invite url (with ldap auth ofcouse) and choose Desktop version, no invite was made. still need to manual add user to PG
### Steps to reproduce:

1. Create invite and send it via somethig
2. Follow by url, tap Desktop, start rockerchat client enter address server, enter login credentials.
3. no invite group appear.
4. if in that moment follow by Web-client invite url group appear in desktop client too.

### Expected behavior:

invite must works from desktop version if we follow by it with choose desktop version

### Actual behavior:

Desktop-client not invited to PV

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: Centos 7
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: 12.16.1
- MongoDB Version:4.0.19

### Client Setup Information

- Desktop App or Browser Version: latest 2.17.11
- Operating System: Windows (all supported version), Linux (ubuntu), Macos latest

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
