### ISSUE TITLE
Email activation link is sent before a self-registered user was activated

### ISSUE THREAD

**Issue by major-mayer** [RocketChat/Rocket.Chat#18693]
### Description:
Using the registration form in combination with email verification and manually activation of new users doesn't work.

### Steps to reproduce:

1. Activate the registration page for new users
2. Activate Email Verification
3. Activate that new users must be activated manually before they can login
4. Use the registration form 

### Expected behavior:

The user gets the email, that says that his account must be activated first.
He gets the verification email either:
- When it's not necessary to be activated to verify the email
- Or only when he was already activated by the admin

### Actual behavior:

He instantly gets the email that prompts him to activate his email, which is not possible because he is not activated.
Even worse, he gets an error message and his email verification link expires, so even if he tries it later (when the account was activated) it won't work anymore.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.4
- Operating System: Linux Docker
- Deployment Method: docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version:4.0.18

### Client Setup Information

- Desktop App or Browser Version: not relevant
- Operating System: not relevant

### Relevant logs:

Does not produce any logs

**Comment by FelipeParreira** [comment]
Hi, @major-mayer! Thank you for the issue 👍 

I was not able to reproduce the supposed bug locally. :(

Let me ask you something: did you actually save the settings after you changed them? 
When you go to the admin panel (`Settings > Accounts`) and change some of the settings you need to hit the `Save Changes` button in the top-right corner of the screen for the changes to take effect.

**Comment by major-mayer** [comment]
Yeah actually i'm not quite sure anymore if it's really a bug or if I have something wrong with my setup.
I just enabled email verification again using this settings (and yes i really pressed save changes, otherwise they wouldn't be still the same after a reload :smile:) :
![grafik](https://user-images.githubusercontent.com/17907799/93665975-d97ca480-fa7a-11ea-830c-c55e757abec6.png)

A few things that i noticed now:
- When I use the registration form the user doesn't get any email until the account was activated manually by the admin - Good! I don't know what was wrong with my config before
- I can actually activate a user without giving hime a username? Is this by design? He can only login with his email then...
- When the user tries logging in, he gets the normal form that requests him to confirm his email. But when I enter my email, there is no email actually sent

I thought the last error could be because of a wrong SMTP setup, but that doesn't makes any sense, because the user get's the notification (via email) that his account was activated, but not for the email verification.

Instead i found this in the logs:
```
I20200919-11:32:28.099(0) Exception in defer callback: Error: Data command failed: 554 5.7.1 Database error. / This is not one of your allowed aliases     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)     at SMTPConnection._actionDATA (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1362:34)     at SMTPConnection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1334:26)     at SMTPConnection._processResponse (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)     at SMTPConnection._onData (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)     at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:462:47)     at TLSSocket.emit (events.js:311:20)     at TLSSocket.EventEmitter.emit (domain.js:482:12)     at addChunk (_stream_readable.js:294:12)     at readableAddChunk (_stream_readable.js:275:11)     at TLSSocket.Readable.push (_stream_readable.js:209:10)     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {   code: 'EENVELOPE',   response: '554 5.7.1 Database error. / This is not one of your allowed aliases',   responseCode: 554,   command: 'DATA' } 
```

It looks like some alias in the email verification email template is wrong, so i've resetted it and now it looks like this:
![grafik](https://user-images.githubusercontent.com/17907799/93666247-e1d5df00-fa7c-11ea-8bff-284b5371c22b.png)

Do you know what's going wrong here?
