### ISSUE TITLE
Large markdown images overflow on chat agent view

### ISSUE THREAD

**Issue by ThangHuuVu** [RocketChat/Rocket.Chat#18694]
### Description:

Title. Markdown images seem to be displayed incorrectly in the agent view if the image is large.
Screenshot:
![Screen Shot 2020-08-27 at 4 54 00 PM](https://user-images.githubusercontent.com/31528554/91426447-be0ce800-e886-11ea-9d3d-15a5f30d3bc7.png)
### Steps to reproduce:

1. Go to setting, set Markdown parser to Marked
2. Send a markdown image. Example image: 

> ![example](https://via.placeholder.com/1920)
! [example] (https://via.placeholder.com/1920)

### Expected behavior:

The image is contained in its message and can be fully observed.

### Actual behavior:

The image overflows.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.4
- Operating System:  Linux
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- Operating System: MacOS Mojave 10.14.4

**Comment by TeraMind244** [comment]
This happens to me as well. We use a lot of big size images in our system. This looks annoying.

**Comment by ThangHuuVu** [comment]
A current workaround for us is adding custom css for the message wrapper and the attachment (because quoted message for a markdown image also use attachment):
```
/* FIX Markdown overflow issue */
.message-body-wrapper img {
    max-width: 100%;
}

.attachment img {
  	max-width: 100%;
}
```

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
