### ISSUE TITLE
Admin options for default avatar (if available)

### ISSUE THREAD

**Issue by acamarata** [RocketChat/Rocket.Chat#1870]
When someone creates a new account, especially via OAuth, they often have an avatar but RC defaults to their initials as an avatar.  Proposing an option in the Admin section to over-ride that if Gravatar or something else finds a match.

**Comment by geekgonecrazy** [comment]
:+1:

**Comment by onigoetz** [comment]
Gravatar is a good idea

**Comment by plus500s** [comment]
I would also like this feature

**Comment by Schniz** [comment]
Gravatar can be a good idea, but the OAuth providers can also be in this list

**Comment by alisalaah** [comment]
The suggestion was not to limit what is already there but have an "if
gravatar exists" use that by default rather than the letters.  Could use
any avatar that exists at all (Facebook, etc.) before using the letters as
an "only if no avatar exists" as the default behavior.  People can disable
the avatar for letters by choice though.

**Comment by marceloschmidt** [comment]
As requested in #3175, also suggest username from the OAuth account.

**Comment by AndrewMontagne** [comment]
Perhaps it is worth supporting OpenID Connect as a part of this, in order to have a common place from which to derive credentials?

**Comment by wohali** [comment]
Two thoughts here:

1. If the OAuth profile returns an avatar field that includes a URL, download and use that.
2. Else, look for a gravatar and use that.

Many OAuth server implementations include additional data (such as an avatar URL) in their profile response.

**Comment by alexbrazier** [comment]
It would be good to have a setting to use full name instead of the username for the avatar initials

**Comment by Mte90** [comment]
Any hope to have it? I think that have gravatar as default can improve the UX

**Comment by engelgabriel** [comment]
@marceloschmidt is working on this right now.

**Comment by alexbrazier** [comment]
@engelgabriel will #5045 also be merged at some point as part of this, as this will be more useful than username for us

**Comment by engelgabriel** [comment]
it will eventually. We still need to finishing some some work on the caching layer before it.
