### ISSUE TITLE
"Ignore" a user returns Match failed 400 error

### ISSUE THREAD

**Issue by scrivna** [RocketChat/Rocket.Chat#18713]
### Description:

If you have muted or ignored a user, when you try to unignore them, a "Match failed [400]" error is displayed.

### Steps to reproduce:

1. In a chat window, open a user card and try to "Ignore" the user

### Expected behavior:

User is unignored

### Actual behavior:

Error
![image](https://user-images.githubusercontent.com/53125/91581521-61034780-e903-11ea-96af-fc5df39f9322.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2 
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 2

**Comment by serviceman** [comment]
This could be related to https://github.com/RocketChat/Rocket.Chat/issues/18653

**Comment by serviceman** [comment]
Issue still present in 3.6.0 on open.rocket.chat

**Comment by serviceman** [comment]
Is there any update on this feature. I can't upgrade without this feature functioning for my community. Thank you for all your hard work on this project.

**Comment by scrivna** [comment]
@rodrigok hey, would you mind taking a look at this please, seems a pretty serious bug here and nobody has looked at it for 2 weeks. 
In general what is the best way to contact RC about issues like this, as it doesn't seem like you monitor these issues at all? Thanks!
