### ISSUE TITLE
Admin able to edit or remove user Avatar

### ISSUE THREAD

**Issue by acamarata** [RocketChat/Rocket.Chat#1871]
This is needed incase a user wants to set an inappropriate avatar, such as pornography.  Should be able to remove the avatar and admin "lock" his avatar to a picture or the initials so they can not change it.  This could be done via "/admin/users" where we can currently edit name, username and password.  If too complex just a button to remove avatar (then they get the default initials), and another option to forbid setting the avatar so they're stuck with that.

**Comment by dandv** [comment]
Another use case: many users are too lazy to setup an avatar.

**Comment by geekgonecrazy** [comment]
Related to #1870

**Comment by polyakoff** [comment]
Would be very useful indeed

**Comment by Flitterkill** [comment]
Bump

**Comment by logankoester** [comment]
Additional use case: managing the avatar for a robot account such as Hubot.

**Comment by justechn** [comment]
Bump

**Comment by m-toyoda** [comment]
poke

**Comment by geekgonecrazy** [comment]
Just FYI you can do this via rest API.  Permission is in place just no UI way of doing so yet

**Comment by SeanPackham** [comment]
We won't be implementing this feature in the near future.
