### ISSUE TITLE
Mobile notifications not sent after disabling email notifications

### ISSUE THREAD

**Issue by andreas-it-dev-llc** [RocketChat/Rocket.Chat#18714]
### Description:

mobile notifications stop working after disabling email notifications.

enabling the email notifications, results in mobile notifications being sent again, disabling email notifications again also stops mobile notifications again.

so there seems to be a settings issue

### Steps to reproduce:

set notification settings to:

![image](https://user-images.githubusercontent.com/13486613/91592956-4fcf3080-e92d-11ea-9baf-4344ca12ab88.png)

and for the channel:

![image](https://user-images.githubusercontent.com/13486613/91592986-5d84b600-e92d-11ea-9b0b-156cb7e41a8b.png)

### Expected behavior:

send out mobile notifications even with disabled email notifications

### Actual behavior:

no mobile notifications are sent once you disable email notifications

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.4
- Operating System: Ubuntu 
- Deployment Method: manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.14
- MongoDB Version: 4.2

### Client Setup Information

- latest chrome
- Operating System: windows / linux doesnt matter

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
