### ISSUE TITLE
[3.6.0] Manual channel purging and the retention policy does not delete threads.

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat#18738]
### Description:

Manual purging and the retention policy does not delete threads

### Steps to reproduce:

1. create a channel
2. write a msg, then create a answer as thread
3. trigger Prune Messages (make sure that Do not prune Threads is not active)
4. reload page on webbrowser with [F5] or in desktop app with CTRL+R

### Expected behavior:

Threads are gone/deleted

### Actual behavior:

Thread still there after reloading.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.6.0
- Operating System: GNU/Debian 10 alias Buster
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Both (Webbrowser Firefox/Opera)
- Operating System: Windows / Linux

### Relevant logs:
`
Meteor ➔ method cleanRoomHistory -> userId: xxxxx, arguments: [{"roomId":"xxxxxx","latest":"9999-12-31T23:59:59.000Z","oldest":"0001-01-01T00:00:00.000Z","inclusive":false,"limit":2000,"excludePinned":false,"ignoreDiscussion":false,"filesOnly":false,"fromUsers":[],"ignoreThreads":false}]
`

**Comment by PeGaSuS-Coder** [comment]
I can confirm the issue with exactly the same server, node and mongodb version.

Attached small GIF video from mobile browser to show the behaviour:
 
![manual_prune](https://user-images.githubusercontent.com/25697531/91932917-e6ae3b00-ece7-11ea-948d-6c4caf2258a0.gif)

**Comment by EnCz** [comment]
This issue gets really annoying because we heavily rely on retention policy automatically deleting old stuff.
Would be cool if this gets fixed because those dead threads keep on piling up and it is no fun do delete them all manually.
@pierre-lehnen-rc ?
