### ISSUE TITLE
Customizing labels and orders in main Side Nav

### ISSUE THREAD

**Issue by acamarata** [RocketChat/Rocket.Chat#1873]
Currently the sections on the left are:

LiveChat
Channels
Direct Messages
Private Groups

What if someone wanted to change the labels and order to be:

Rooms
Groups
Messages
Support

Seems like something simple enough in theory.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
