### ISSUE TITLE
Can't deactivate user

### ISSUE THREAD

**Issue by tonipenya** [RocketChat/Rocket.Chat#18745]
### Description:

When deactivating a user, a confirmation dialog appears but the confirmation button cannot be clicked since there is an element on top of it blocking it.

### Steps to reproduce:

1. Go to administration
2. Select the user
3. Click on three dots button
4. Click on deactivate

### Expected behavior:

User is deactivated or, given a confirmation dialog the deactivation option can be clicked.

### Actual behavior:

There is an element blocking the confirmation button.

<img width="631" alt="Screenshot 2020-08-31 at 10 58 04" src="https://user-images.githubusercontent.com/191486/91703271-35d65d80-eb7a-11ea-9274-b16b1c07a686.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 

- Version of Rocket.Chat Server: 3.5.2
- Operating System: Managed by rocket.chat
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Firefox, Chrome and Safari
- Operating System: macOS

### Additional context

The blocking element can be deleted by inspecting the source code (not practical for non-dev users).

### Relevant logs:

The following error appears in the browser's log when clicking the deactivate button.

```
XHRPOSThttps://<redacted>.rocket.chat/api/v1/users.setActiveStatus
[HTTP/2 400 Bad Request 189ms]

	
POST
	https://<redacted>.rocket.chat/api/v1/users.setActiveStatus
Status400
Bad Request
VersionHTTP/2
Transferred443 B (147 B size)

    	
    cache-control
    	no-store
    content-encoding
    	gzip
    content-length
    	129
    content-type
    	application/json
    date
    	Mon, 31 Aug 2020 09:04:12 GMT
    pragma
    	no-cache
    vary
    	Accept-Encoding
    x-content-type-options
    	nosniff
    X-Firefox-Spdy
    	h2
    x-instance-id
    	<redacted>
    x-xss-protection
    	1
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	51
    Content-Type
    	application/json
    Cookie
    	<redacted>
    DNT
    	1
    Host
    	<redacted>.rocket.chat
    Origin
    	https://<redacted>.rocket.chat
    Referer
    	https://<redacted>.rocket.chat/admin/users/info/<redacted>
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0
    X-Auth-Token
    	<redacted>
    X-Requested-With
    	XMLHttpRequest
    X-User-Id
    	<redacted>
```

**Comment by isality** [comment]
+1 same issue. Version 3.5.3.

**Comment by ankar84** [comment]
Fixed in https://github.com/RocketChat/Rocket.Chat/pull/18596

**Comment by ggazzo** [comment]
thanks @ankar84
