### ISSUE TITLE
Purge All Avatars From Mongo

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#1874]
Hi,

Would removing avatars from the mongo database directly cause any issues? We noticed that avatar resizing was not set as default and we have users uploading 6 MB avatars and are trying to determine if this is causing issues with crashing our mongo database.

We set resizing to true and switched to FileSystem storage. Should Rocketchat automatically convert these over? Because I don't see anything in our new FileSystem storage location (/opt/rocketchat/avatars/)

**Comment by rodrigok** [comment]
RC does not migrate avatars between storages.

I think you can delete the content of collections `avatars.files` and `avatar.chunks` with no problems.

I will close this issue, please reopen if you need.
