### ISSUE TITLE
Whitespace not perserved in codeblocks

### ISSUE THREAD

**Issue by dennishenry** [RocketChat/Rocket.Chat#18747]
### Description:

Non-defined codeblocks do not preserve whitespace

### Steps to reproduce:

1. Create codeblock (using triple `) and do not define a language
2. Use whitespace in the codeblock
3. Send and see whitespace doesn't matter

### Expected behavior:

Preserve whitespace, as is done in defined codeblocks (php, python, etc.)

### Actual behavior:

No whitespace preserved

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.3
- Operating System: CentOS Linux release 7.8.2003 (Core)
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: 2.17.11
- Operating System: macOS Catalina 10.15.5

**Comment by lostgirljourney** [comment]
Is this issue is still active?

**Comment by ggazzo** [comment]
please go ahead, I'm afraid we already fixed this issue (if you enable the personal setting to use message parser), any problem let me know

**Comment by lostgirljourney** [comment]
@ggazzo thank you! 😀
I'll check & let you know.

**Comment by sidmohanty11** [comment]
I tried to reproduce it, seems to work well for me. I think it's fixed.

**Comment by hugocostadev** [comment]
It was already fixed
