### ISSUE TITLE
Avatars do not work when using Rocket-Chat in a subpath (subfolder)

### ISSUE THREAD

**Issue by Roemer** [RocketChat/Rocket.Chat#18759]
### Description:

I am using a Docker / Nginx setup where Rocket.Chat is in a subpath (/chat). Everything works except the avatars in some places (for example in the profile view or in the Users list).
looking at the urls, it just does not use the subpath and just goes plain to `/avatar`. If I add another nginx rule
```
location /avatar/ {
    proxy_pass http://rocketchat:3000/chat/avatar/;
}
```
It works. I did not have to do the same with file-uploads or anything else. The only other nginx config I have is:
```
location /chat/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
        proxy_pass http://rocketchat:3000/chat/;
}
```

### Steps to reproduce:

1. Install with docker
2. Install nginx and add the rules
3. Upload an avatar image

### Expected behavior:

The avatar is shown everywhere.

### Actual behavior:

The avatar is only shown in the chat itself.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.4
- Operating System: Docker Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 10

**Comment by guillaumerybak** [comment]
Hello, I've noticed the same issue. Do you have a release target for this ?

**Comment by MrEscaGreenwing** [comment]
Hi, we have the same problem on our site with an Apache setup.

**Comment by JPaulMora** [comment]
Confirmed not working yet.

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/22290
