### ISSUE TITLE
Real names are not shown inside threads

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#18769]
### Description:

I'm recreating this issue because the existing one did not get resolved in the threads rewrite, yet it was marked resolved.

In short: New installations of Rocket.Chat, tar or docker based, ignore Use Real Names server setting under threads. Instead usernames are shown.

Original issue:
https://github.com/RocketChat/Rocket.Chat/issues/17519

### Steps to reproduce:

1. Activate Administration -> Layout -> User Interface -> Use Real Name
2. User writes a reply in thread. The real name is shown correctly in the message.
3. Close the thread view and open it again.

### Expected behavior:

Names inside the thread should be real names.

### Actual behavior:

Names inside the thread are usernames.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.4
- Operating System: CentOS7
- Deployment Method: tar and docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Any browser

### Additional context

When looking at the database `u.name` is not written into the message. Supposedly it was removed on purpose in https://github.com/RocketChat/Rocket.Chat/pull/16343 . This issue has existed since this pull, yet it is not visible on (very) old instances that still write u.name into the messages for an unknown reason.

**Comment by ipikiiskinen** [comment]
We have this same issue with version 3.5.0, MongoDB 4.0.19. Installation uses rocket.chat from docker container (rocket.chat:3.5.0). 
We get the user data from AD (LDAP).
This issue is in thread messages, quotes and email notifications.

**Comment by jdsatava127** [comment]
We are having the same issue as well. Real name is not showing properly in threads and emails. We are using Docker image 3.5.4 with users from LDAP.

**Comment by beranPro** [comment]
same here

**Comment by immaro** [comment]
Same here, the problem still persists in v 3.7.1

**Comment by bseclier** [comment]
Same here, a fix would be great !
Thanks.

**Comment by mbdwa** [comment]
Which version will feature this fix? Can't login to our instance anymore because of this bug.

**Comment by Gummikavalier** [comment]
This issue seems to have been resolved in RC 3.11.0. I checked that it is not using the solution provided by magicbelette, but the original issue of failing to resolve the username as name on the fly.

**Comment by Gummikavalier** [comment]
Correction: according to the database the name _is_ written into DB but by some other part of the code.

**Comment by Gummikavalier** [comment]
The similar issue with reactions remains though: https://github.com/RocketChat/Rocket.Chat/issues/20501

Anyway, I'm closing this one.
