### ISSUE TITLE
New view of Threads makes it impossible to see new messages

### ISSUE THREAD

**Issue by GoetheG** [RocketChat/Rocket.Chat#18778]
Rocket Chat 2.17.11 for Windows
Windows 10 Pro 2004

The view of Threads has been changed on the desktop version Windows. New messages in Threads aren't visible in the main chat anymore. If I write somethin in an old Thread for axample, nobody can see that I did. There used to be the chat  of a Thread in the main chat area but with  smaller user icon and smaller font.

**Comment by PeGaSuS-Coder** [comment]
Side note: there's a checkbox that's says `Send to channel` when you're replying to a thread at the bottom left.

Check it and the message will also be sent to the channel.

The idea behind the new threaded messages stay display is to keep the main channel less cluttered.

Hope this helps!
