### ISSUE TITLE
Unable to select Closing TAG(s) in the Closing Chat window

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat#18788]
### Description:

The configured closing TAG(s) are not visible in the LiveChat "Closing Chat" window and, since they are configured as mandatory, the chat cannot be closed (see screenshot).

### Steps to reproduce:

1. Go to Omnichannel configuration
2. Select a department
3. Configure some closing TAG(s)
4. Confiugure the closing TAG(s) as required
5. As a LiveChat agent, close a conversation
6. The Closing Chat require the agent to TAG the conversation
7. Unable to select Closing TAG(s).

### Expected behavior:

The agent can see/search the available Closing TAG(s) defined in the department configuration. 

### Actual behavior:

Unable to see / select the Closing TAG(s) defined in the department configuration.

### Server Setup Information:

- Version of Rocket.Chat Server: v3.6.0 (never seen this feature working. In v3.5.4 also this bug was also there)
- Operating System: Ubuntu 18
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: MacOS Catalina

### Additional context

![image](https://user-images.githubusercontent.com/35463401/92095052-767de300-edd5-11ea-8697-5773378fabf3.png)

### Relevant logs:

none

**Comment by renatobecker** [comment]
- The `Closing tags` defined in a department will be assigned to the room automatically when the conversation ends regardless your department requires tags on closing or not.
So, they won't be available in the `Closing chat` window, that's the reason you can't select them.

As I can see, your department requires tags on closing, so the agent needs to set at least one tag to be able to close the chat.

**Comment by didacroyo** [comment]
I see... the way to set (at least one) tag (to be able to close the chat) is to type whatever I want and to press enter. Good to know! Thanks Renato!
