### ISSUE TITLE
Messages not visible when UIKit Actions Buttons are attached

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/Rocket.Chat#18806]
### Description:

I'm sending a Livechat message from an app. In this message, I'm adding the normal `text` and `action-buttons`. Both the message and action-blocks gets rendered properly on the Livechat widget, however, on the server-side, I can only see the `action-buttons`.
The screenshot below should give you a better idea about the issue
![Screenshot from 2020-09-04 21-14-17](https://user-images.githubusercontent.com/34130764/92259930-049cbb00-eef5-11ea-947c-191cdd3c7ce1.png)

### Steps to reproduce:

1. Send a message with `ActionsBlock` and `text` together

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0-develop (Latest from `develop` branch of this Repo)
- Operating System: Ubuntu 18.04
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: NA
- NodeJS Version: 12.18.3 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Ubuntu 18.04

**Comment by ggazzo** [comment]
thanks for your report, but actually the LiveChat widget is rendering the text inappropriately, we defined the `msg` field will be used as a fallback only, it will be not rendered with uikit blocks. Please use a `section + text`.
