### ISSUE TITLE
Uploading CSV File Breaks Upon Download

### ISSUE THREAD

**Issue by jmessy919** [RocketChat/Rocket.Chat#18805]
### Description:

When I upload a CSV to RocketChat, users end up being provided a `.csv.xls` file instead. The source file does not have this issue.

### Steps to reproduce:

1. Create a CSV file in Excel
2. Upload to RocketChat
3. Download from RocketChat
4. Open it and see the corruption.

### Expected behavior:

I expect to get an exact replica of the file which I uploaded to RocketChat.

### Actual behavior:

The CSV gets changed to a broken file with an `.csv.xls` file extension.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: Digital Ocean Image
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12.18.3
- MongoDB Version: 4.0.3

### Client Setup Information

- Desktop App or Browser Version: 2.17.9 (2.17.11 Refuses to Install)
- Operating System: Windows 10

### Relevant logs: Not sure what to share for this issue.

**Comment by jmessy919** [comment]
Can confirm this is still an issue with latest RocketChat. Any ideas?

**Comment by damian-centrone** [comment]
already fixed. tested on 3.8.0
