### ISSUE TITLE
[Improvement] Do not store private E2E keys on server

### ISSUE THREAD

**Issue by cremfert** [RocketChat/Rocket.Chat#18810]
Dear Rocket.Chat-Team,

first of all, thanks for your effort to develop this great product.

I'm currently working on a feature, which might be of interest for integrating to Rocket.Chat. From a security perspective, storing private keys on a server - even if they are encrypted - is not recommended. Although I understand that this is done for the sake of comfort to the user, we currently enhance Rocket.Chat with a settings flag to not upload private keys to the server. Instead, the private key is only stored in ```localStorage``` and can be downloaded as a text file by a JS method. Furthermore, this text file can also be imported to ```localStorage``` with a JS method utilizing the FileReader-API. To easily transfer the key to a mobile phone, the key contents saved in the ```localStorage``` are depicted in Rocket.Chat profile settings as a QR code. In the mobile client, we currently work on an enhancement to scan this barcode and store the key.

Doing it this way, the private keys are never stored on the server, which - from our point of view - would further increase security.

My question is: Are you interested in such a feature? Is something like this on your roadmap or should I prepare the code in a way that it can be merged via pull request to the official Rocket.Chat (and mobile) repo?

Thanks again and best regards
Chris

**Comment by Sing-Li** [comment]
@cremfert    Please post this idea on our Feature Requests Repository for discussions.   https://github.com/RocketChat/feature-requests/issues
