### ISSUE TITLE
Omnichannel Analytics - Wrong dates in chart view

### ISSUE THREAD

**Issue by gaurangsbits** [RocketChat/Rocket.Chat#18820]
In Omnichannel Analytics when we filter by either "This week", "Previous week", "This Month" or "Previous Month". We see wrong dates in analytics chart. For example when we select "This Month". Then Graph should show start date as 9/1 and end date as 9/30. But instead it shows 8/31 as start date and 9/29 as end date.  This is also affecting the week view. 

### Steps to reproduce:

1. Go to Omnichannel 
2. Click on analytics
3. Select "This Month" from top right corner

### Expected behavior:

Then Graph should show start date as 9/1 and end date as 9/30. 

### Actual behavior:

It shows 8/31 as start date and 9/29 as end date.

![analytics dates](https://user-images.githubusercontent.com/70897075/92388539-12408380-f135-11ea-884f-4a688537c5e8.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.2.2
- Operating System: Linux
- Number of Running Instances: 1

**Comment by MartinSchoeler** [comment]
Hey @gaurangsbits  we recently refactored this page in React. can you test this with the latest edition to see if it still happens? Thanks!
