### ISSUE TITLE
"success":false,"error":"TOTP Invalid [totp-invalid]"

### ISSUE THREAD

**Issue by gcommit** [RocketChat/Rocket.Chat#18823]
### Description:

The new version 3.6.0 is working fine when i update an existing instance. But i am not able to start new ones. I am running automated scripts to build up my docker container whenever i want to. But it fails since 2FA is forced (if i understand it right) it fails at the point, where i want to change things like SiteURL or Admin user
https://rocket.chat/all-aboard-rocket-chat-3-6-is-here/
"If you’re changing an important setting on your Admin panel or resetting an E2E Key, our system will now ask you for a 2-Factor Authentication code to proceed with the changes."

This breaks the whole automatism thing... Correct me if i am wrong.

### Steps to reproduce:
1. Start RC in 3.6
2. try to create Admin user or reset settings like SiteURL
3. enjoy TOTP errors

### Expected behavior:

No 2FA forced - because i think a lot of people are using automated setups, you can't use 2FA that way ...

### Actual behavior:
RC does not start.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: node:12.18-slim docker
- Deployment Method: docker
- Number of Running Instances: >10
- DB Replicaset Oplog: 
- NodeJS Version: 12.18
- MongoDB Version: v3.6.13

### Relevant logs:

```
infos of customer-admin:
rocketchat_1  | {"user":{"_id":"XXXXXXXXX","createdAt":"2020-09-08T08:41:14.283Z","name":"Administrator","username":"admin","status":"offline","utcOffset":0,"active":true,"emails":[{"address":"example@mail.de","verified":false}],"type":"user","services":{},"roles":["admin"]},"success":true}

update customer-admin:
rocketchat_1  | {"success":false,"error":"TOTP Required [totp-required]","errorType":"totp-required","details":{"method":"password","codeGenerated":false,"availableMethods":[]}}

infos of general channel:
rocketchat_1  | {"channel":{"_id":"GENERAL","ts":"2020-09-08T08:41:13.861Z","t":"c","name":"general","usernames":[],"msgs":0,"usersCount":0,"default":true,"_updatedAt":"2020-09-08T08:41:13.861Z"},"success":true}

invite admin to general channel:
rocketchat_1  | {"channel":{"_id":"GENERAL","ts":"2020-09-08T08:41:13.861Z","t":"c","name":"general","usernames":[],"msgs":1,"usersCount":1,"default":true,"_updatedAt":"2020-09-08T08:41:20.709Z"},"success":true}

reset Site_Url:
rocketchat_1  | {"success":false,"error":"TOTP Required [totp-required]","errorType":"totp-required","details":{"method":"password","codeGenerated":false,"availableMethods":[]}}

rocketchat_1  | Customer admin could not be created - Aborting!
```

### Additional: 

If i login via 2FA password like this:

```
    loginInfo=$(curl -H "Content-type:application/json" -H "x-2fa-code: passw0rd" -H "x-2fa-method:password" http://localhost:3100/api/v1/login \
    -d '{"user": "admin", "password": "passw0rd"}')
    userId=$(echo $loginInfo | jq -r ".data.userId")
    authToken=$(echo $loginInfo | jq -r ".data.authToken")
```
Result:
`rocket.chat rest api login info: {"status":"success","data":(...)}`

the login is ok but this fails due to 

"`{"success":false,"error":"TOTP Invalid [totp-invalid]","errorType":"totp-invalid","details":{"method":"password"}}`":

```
    return_msg=$(curl -H "X-Auth-Token: $authToken" \
         -H "X-User-Id: $userId" -H "x-2fa-code:passw0rd" -H "x-2fa-method:password"\
         -H "Content-type:application/json" \
         http://localhost:3100/api/v1/settings/Site_Url \
         -d '{"value": "'$ROOT_URL'"}')
```

**Comment by sampaiodiego** [comment]
looks like we're missing a documentation on how to use `password` for 2FA.. the `x-2fa-code` needs to be a `sha256` hash of the actual password, that's why your request was failing. I'll add this information there.

But I'd like to mention that some of your automations could be performed via environment variables only, please take a look at https://docs.rocket.chat/guides/administrator-guides/settings-via-env-vars .. for example for `Site_Url` you can define an environment variable with same name and on the first run it will use the environment variable value as the setting value.

having that information, you could then set an environment variable called `Accounts_TwoFactorAuthentication_Enforce_Password_Fallback` set to `false` to disable this new behavior of asking the password as 2FA introduced at 3.6.0.. Doing that it will work as it used to work.

**Comment by gcommit** [comment]
Thank you a lot ! i already started to get rid of api commands and push it directly to the mongo database. I will change the scripts back to "normal" 👍

**Comment by gcommit** [comment]
just to let u know: 
using a sha256 hash of my admin passwort resulted in "TOTP Invalid [totp-invalid]" again

So i used the method with the ENV var "Accounts_TwoFactorAuthentication_Enforce_Password_Fallback" which disabled it fine

**Comment by sampaiodiego** [comment]
@gcommit can you provide the whole request pls? I tried with the following request and it worked fine:
```
curl --request POST 'http://localhost:3000/api/v1/settings/Accounts_CustomFields' \
--header 'Content-Type: application/json' \
--header 'X-Auth-Token: 9GV24NW69PUj...vwo1YGV' \
--header 'X-User-Id: QJQxjZ...GKFf' \
--header 'x-2fa-method: password' \
--header 'x-2fa-code: 00e48a815525....15cf791c482ed99ecc' \
--data-raw '{
	"value": "{\"type\":\"text\",\"required\":true,\"minLength\":2,\"maxLength\":123}"
}'

**Comment by gcommit** [comment]
Sure, i tried this: 

```
sha256password=$(echo "MyAdminPassword" -n | sha256sum)

curl -H "X-Auth-Token: $authToken" \
         -H "X-User-Id: $userId" \
         -H "x-2fa-code: $sha256password" \
         -H "x-2fa-method:password"\
         -H "Content-type:application/json" \
         http://localhost:3100/api/v1/users.update \
         -d '{"userId": "'$adminId'", "data": {"name": "'$ROCKETCHAT_USER'", "email": "'$ROCKETCHAT_MAIL'", "password": "'$ROCKETCHAT_PASSWORD'", "username": "'$ROCKETCHAT_USER'", "roles": ["admin", "user", "livechat-manager"], "verified": true, "joinDefaultChannels": true}}'
```

**Comment by sampaiodiego** [comment]
you have some issues with your `sha256password` in this case.. 

doing that way it will have an additional dash ` - ` at the end, which will cause it to fail.. also the `-n` parameter to `echo` should be *before* the actual password.. 

this is what I got from your code:
```
diego.sampaio@n05:~$ sha256password=$(echo "MyAdminPassword" -n | sha256sum)
diego.sampaio@n05:~$ echo $sha256password
e5ede49cfee8969a5d7a92ee68c198af32578bea9657a29d75fe0469ec07e490 -
```

but the expected value for `sha256password` is actually `04e6a0d0fd65de4869be263fc7d049e64dedad31b1a32f934f1f835f9e1a9937` (you can check with this tool https://emn178.github.io/online-tools/sha256.html )

**Comment by gcommit** [comment]
thank you, i think this one can be closed - at least everything is clear on my side here :)

**Comment by robincafolla** [comment]
I took a stab at adding the docs [here](https://github.com/RocketChat/docs/pull/1799) if anyone could review it?

**Comment by sampaiodiego** [comment]
that's awesome @robincafolla .. thank you
