### ISSUE TITLE
Can't deactivate user who is owner for one or more groups

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [RocketChat/Rocket.Chat#18833]
### Description:

When i try to deactivate user who is owner to one or more groups, i receive a pop up window like the below one, and everything gets freezed:

![image](https://user-images.githubusercontent.com/47364489/92509744-07f0b900-f20b-11ea-821d-f1915c2b33c4.png)

And then i have to close the app/ reload the browser to activate the dashboard again!!

Then i have to find out the user's owned groups "**Manually**" going to the channels admin page >> for each channel, check its owner >> go to owner role >> for each channel pick up a user to be the new owner (this story is another issue that needs a real clear/ smooth solution!!)

### Steps to reproduce:

1. Create any user
2. Make him as owner to one or more channels
3. Try to deactivate it

### Expected behavior:

1. Simply at least, just deactivate it and re-assign to another one automatically (as the message says)!!
2. List/ Show all owned groups at the pop window, i don't have to look for it manually
3. **A smooth way** to change groups ownership

### Actual behavior:
Freezed app/ browser

![image](https://user-images.githubusercontent.com/47364489/92510310-ed6b0f80-f20b-11ea-87d9-22cad5a76f89.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: Ubuntu LTS 18.04
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog:  Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: app 2.17.11, chrome Version 85.0.4183.83
- Operating System: Ubuntu 16.04 and Ubuntu 18.04 and Windows 10

### Relevant logs:

No logs!!

**Comment by ankar84** [comment]
Same as https://github.com/RocketChat/Rocket.Chat/issues/18745
And fixed by https://github.com/RocketChat/Rocket.Chat/pull/18596

**Comment by mohammedragabsoftxpert** [comment]
@ankar84 How to upgrade from 3.5.2 to 3.6.0 using snap?

`# snap refresh rocketchat-server
snap "rocketchat-server" has no updates available`

**Comment by ggazzo** [comment]
> Same as #18745
> And fixed by #18596

🤷
