### ISSUE TITLE
Custom_Script_Logged_In - Import error

### ISSUE THREAD

**Issue by l-baszak** [RocketChat/Rocket.Chat#18847]
### Description:

CustomScriptLoggedIn trigger error after trying to import RocketChat module.

### Steps to reproduce:

1. Layout -> CustomScripts -> Custom Script for Logged In Users
2. Input simple import statement:
```
import { FlowRouter } from 'meteor/kadira:flow-router';
```
### Expected behavior:

Nothing should happen, just import given module. 

### Actual behavior:

```
Exception in template helper: executeCustomScript@https://...
```

### Server Setup Information:

- Version of Rocket.Chat Server: 2.1.0
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v8.15.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Linux Mint

**Comment by hugocostadev** [comment]
Import does not work, scripts should just add simple js
