### ISSUE TITLE
Audio and video stops when screen sharing starts

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#1884]
As the subject mentions, audio and video seems to stop when screen sharing starts. When we end the screen sharing, the other side can hear and see me, but I can't see them. 

If they do a full reload in their browser, we can start a new video/voice session. 

Also, does the screen sharing (plugin) also go through the https/SSL connection? Does the video/audio as well?

**Comment by Sing-Li** [comment]
Yes. webrtc screen sharing is implemented as a one-way video+audio stream.

**Comment by yneha** [comment]
Is there any way to change this? Make audio and screen sharing available at the same time????
