### ISSUE TITLE
Is Rocket.Chat for me?

### ISSUE THREAD

**Issue by Silvenga** [RocketChat/Rocket.Chat#1885]
Would you say Rocket Chat is ready for production at this time for internal communications or would it be better to wait until Rocket is a bit more mature? When I say production ready I really mean the following:

* Stable (where updates can occur at most twice a year)
* Generally bug free (Most users won't have issues using any client)
* Can support hundreds of concurrent users in multiple geo regions
* Production ready mobile apps

**Comment by Sing-Li** [comment]
@Silvenga .... (where updates can occur at most twice a year) .... in FOSS world translates to *mature end-of-life project* with almost no active contributors left

Rocket.Chat is definitely stable, generally MAJOR bug free, supports hundreds of users, and have multiple mobile apps available   --- by any real modern software standards

And yes, thousands of installations around the world are already running Rocket.Chat in production as we speak. 

But of course, only **you** can decide if Rocket.Chat is good enough for _your requirements_ :)

**Comment by Silvenga** [comment]
Thanks for your response, I do appreciate your passion for this project @Sing-Li. 

What would you recommend as an optimistic upgrade cycle for a Rocket.Chat instance?

And what mobile clients would you recommend for production at this time?

**Comment by Sing-Li** [comment]
Thanks for your understanding, @Silvenga  :+1:

We release 'stable' here once a week - 
https://github.com/RocketChat/Rocket.Chat/releases

IF your selected release contains the features that you need already, you can actually just upgrade "twice a year" if you wish; or whenever one or more minor bugs in your release is deemed MUST_BE_FIXED by your users.  Most 'basic' features have been stable for some time already.

For mobile, at this time, I would recommend the Cordova based hybrid mobile clients (available in PlayStore and AppStore).  

The native versions for Android and iOS show a lot of promise, but are definitely work-in-progress.

**Comment by k0nsl** [comment]
Hi @Silvenga 
I just wanted to say it was nice to see you here, you're the same @Silvenga I'm thinking of :smirk: . This project is really nice and with fast-paced development.

**Comment by Silvenga** [comment]
Thanks @Sing-Li and @k0nsl!
