### ISSUE TITLE
Missing build.sh files

### ISSUE THREAD

**Issue by AlexTr** [RocketChat/Rocket.Chat#1886]
`.gitignore` has entry for `build.sh` file. 

But there are some build.sh files which are necessary, for example:

```
.sandstorm/build.sh
packages/rocketchat-livechat/plugin/build.sh
```

**Comment by marceloschmidt** [comment]
Can you explain better what the problem is? Indeed build.sh is ignored in .gitignore, and those two files were added to the repository, so they skip the .gitignore check.

**Comment by AlexTr** [comment]
I've copied Rocket.Chat to own repository, and discovered that these files was missing since they weren't committed to the repository. Generally, if files are necessary for the package, they shouldn't be ignored.

**Comment by marceloschmidt** [comment]
You manually copied Rocket.Chat files to your repository? You did not create a fork?

**Comment by AlexTr** [comment]
Yes, it's necessary for the special setup.

**Comment by MartinSchoeler** [comment]
This file can be found here https://github.com/RocketChat/Rocket.Chat/blob/develop/.sandstorm/build.sh . If your problem persists please open a new issue with updated details. Thanks!
