### ISSUE TITLE
API livechat/visitors.search only filter visitors with name starts with query term

### ISSUE THREAD

**Issue by galiazzi** [RocketChat/Rocket.Chat#18868]
### Description:

In release 3.6.0 was introduced the api `livechat/visitors.search` (#18514)

There is a reason for filter by name only with string starts with? Maybe can be with `contains`?

https://github.com/RocketChat/Rocket.Chat/blob/bd550af1f0260e914a0de3d3d37b3a64bd7e47fe/app/models/server/raw/LivechatVisitors.js#L68

### Steps to reproduce:

1. Call api `/livechat/visitors.search?term=value`

### Expected behavior:

Search all visitors with name contains `value`

### Actual behavior:

List visitors with name starts with `value`

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 4.2.8

### Client Setup Information

- Browser Version: Chrome 85
- Operating System: Linux

**Comment by leolage** [comment]
This is very good! awesome! Thanks!

If I need can I delete a visitor? I'm trying to update user details, but in a lot of cases I need to delete the visitor to recreate them, its possible?

Thanks

**Comment by galiazzi** [comment]
This was fixed in version 3.9.0 #19577
