### ISSUE TITLE
"Read by" (seen) no longer works

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat#18884]
### Description:
Read by no longer shows all users who have seen/read the message.

### Steps to reproduce:
1. Open some channel or direct message
2. Write a message
3. Let other users read the message
4. Click on Message Info
5. Check "Read by"

### Expected behavior:
1. It should contain information from all the people who read it

### Actual behavior:
This is how information is displayed
![a7tepid0q](https://user-images.githubusercontent.com/25570106/92995247-3966ce80-f502-11ea-812d-942ca09f7066.png)

### Server Setup Information:
* Version of Rocket.Chat Server: 3.6.1
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: Unknown - see rocketchat:3.4.1 image.
* MongoDB Version: 4.0.12

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 2.17.11

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

**Comment by degodfather** [comment]
I think the read receipts are only available to the paid versions.

**Comment by wreiske** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/18689

**Comment by MartinSchoeler** [comment]
Should be fixed by https://github.com/RocketChat/Rocket.Chat/pull/18918 If you come across this issue again, please reopen this. Thanks!
