### ISSUE TITLE
How to create Favicon.ico

### ISSUE THREAD

**Issue by tuudik** [RocketChat/Rocket.Chat#1888]
Hi,

I have tried creating favicon with GIMP.
I have three different layers with icon sizes: 16, 32, 48.

Everytime I try to upload, error message Invalig File Type appears. Nothing in Debug log.

Help pls:)

**Comment by marceloschmidt** [comment]
Hey @tuudik we have identified what we think is a problem on our File Upload. Would you mind sending us the file you are creating to support@rocket.chat, so we can improve and fix this for everyone else? Thanks!

**Comment by tuudik** [comment]
Favicon sent:) One question more, when in iOS safari, sending shortcut to homescreen, it will use Rocket.Chat icon, is it expected behaviour?

**Comment by rodrigok** [comment]
@tuudik there is a difference between browsers to detect the file mime type, if you try to upload your icon using chrome will work.

I fixed this problem, watch this PR #1893

**Comment by tuudik** [comment]
Hmm but I used chrome:(

**Comment by rodrigok** [comment]
@tuudik OS X, Windows or Linux?

**Comment by haceru** [comment]
Hello, I had the same problem yesterday using Opera (Chrome based engine) and Windows 7 pro. The browser identified correctly the file as a .ico type, but the chat instance would not accept it due to "Invalid file type"

**Comment by tuudik** [comment]
Windows 8.1 Pro

**Comment by LeCoupa** [comment]
I have the same problem with .ico extension. It says : Invalid file type : image/vnd.microsoft.icon

**Comment by rodrigok** [comment]
@LeCoupa Which Rocket.Chat version are you using?

**Comment by LeCoupa** [comment]
I just used one week ago.
```
curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz
```

**Comment by rodrigok** [comment]
@LeCoupa can you go to `/api/info` to get the exact version you are using?

**Comment by LeCoupa** [comment]
@rodrigogs :  "version": "0.15.0"

**Comment by rodrigok** [comment]
@LeCoupa which browser and OS are you using? I can't reproduce your problem

**Comment by rodrigok** [comment]
@LeCoupa Ok, the problem is that this mime type doesn't have extension in the library that we are using https://github.com/jshttp/mime-db/blob/master/db.json?ts=2#L5522-L5525

I will try to solve that

**Comment by rodrigok** [comment]
@LeCoupa My latest commit solve your problem https://github.com/RocketChat/Rocket.Chat/commit/d7900901ead676e12adfccbc6344adf0054adeec?ts=2

**Comment by alvarow** [comment]
Can we add mime types for Apple Keynote, Pages and Numbers? I am unable to upload those.

**Comment by rodrigok** [comment]
@alvarow for favicon? :smile_cat: 

This verification is only for assets like favicon, logo, etc.

For normal uploads you can change the list of acceptable file types for upload in admin area under "File Uploads" section.

**Comment by alvarow** [comment]
Well. on File  uploads... there's a white list of mime types too ... I added those, yet I still can't upload

**Comment by rodrigok** [comment]
@alvarow can you create a new issue with more details about your problem?

**Comment by alvarow** [comment]
sure can.

**Comment by LeCoupa** [comment]
@rodrigok I reinstalled Rocket with `curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz`

But it seems that I still got this error:
<img width="343" alt="screen shot 2016-01-28 at 7 02 02 pm" src="https://cloud.githubusercontent.com/assets/1658644/12653881/ca9413d0-c5f1-11e5-9b82-3ae51f400d10.png">

**Comment by rodrigok** [comment]
@LeCoupa you are downloading the latest release that is from our master, we do a new release every monday.

To get the fix you need to download our development version https://github.com/RocketChat/Rocket.Chat/archive/develop.zip

**Comment by LeCoupa** [comment]
It is working on my side! Thank you @rodrigok :-)

**Comment by rodrigok** [comment]
@LeCoupa ur welcome :smile:

**Comment by canphaz** [comment]
Hi, I am still having this issue with 0.57.2. 
Whatever type of .ico file I upload, I get the same error about "Invalid file type : image/vnd.microsoft.icon".
<img width="418" alt="screen shot 2017-07-24 at 21 22 33" src="https://user-images.githubusercontent.com/203897/28540614-44c3916a-70b6-11e7-9852-28f6675d73c4.png">


What am I doing wrong?
Thanks,

Ralph

**Comment by Zaraka** [comment]
0.57.2 linux chrome, firefox, desktop client with same result
invalid file type

**Comment by dancorrigan1** [comment]
Even trying to re-upload the default favicon.ico that comes with Rocketchat fails with the same error.

**Comment by 2E0PGS** [comment]
indeed same issue here still persistent for over a year

**Comment by Supermathie** [comment]
Indeed, us as well on commit 65e06c283226ddb56f2d3a592dfc31df09115421. Here's a file I'm having trouble with: [rocket-chat-discourse.ico.gz](https://github.com/RocketChat/Rocket.Chat/files/1580898/rocket-chat-discourse.ico.gz)

Created using:

```
convert rocket-chat-discourse.png -define icon:auto-resize=128,64,48,32,16 rocket-chat-discourse.ico
```

**Comment by Hugo14453** [comment]
Any tips on creating a file that _does_ work?

**Comment by Supermathie** [comment]
Not really; the file does work it's the software that's broken.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: February 24, 2018 12:34To: Rocket.Chat@noreply.github.comReply to: reply@reply.github.comCc: michael@mikeandgen.ca; comment@noreply.github.comSubject: Re: [RocketChat/Rocket.Chat] How to create Favicon.ico (#1888)  Any tips on creating a file that does work?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by navigosgroupjsc** [comment]
I'm having the same issue, any solution?

**Comment by ooguz** [comment]
Hello everyone,

I was getting this error and there is no real solution on the web.

The solution is:

- Go to "Administration"
- Enter "File Upload" section
- Append the file type which you get error at the end of "Accepted Media Types" field

Screenshot is on the link:

[https://hackerspace.ist/ico_problem_solution.png](https://hackerspace.ist/ico_problem_solution.png)

Have a nice day!
