### ISSUE TITLE
Mobile Push Notification stopped working after upgrade to 3.6.1

### ISSUE THREAD

**Issue by superseby2** [RocketChat/Rocket.Chat#18895]
### Description:

No push notifications get trough. 

### Steps to reproduce:

1 - Just upgraded to 36.1 from 3.2.1
2 - On RC restart, I have been asked to register to cloud services while I was already registered
3- I re-register successfully. 
4 - Got a banner stating that Push Notifcation needed to be enabled in Administration > Push
5 - In Admin > Push : Push notif were enabled already. 
6 - I Disabled > Save then Enabled > Save + Restart RC
7 - Push test does not work anymore and any other notification from the chat as well. 

### Expected behavior:

Push notification to work

### Actual behavior:

Push notification does not show up on mobiles

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  Linux Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 68.0.3440.106 (Developer Build) (64-bit)
- Operating System: Linux

**Comment by ankar84** [comment]
Could be related to https://github.com/RocketChat/Rocket.Chat/issues/18844 and https://github.com/RocketChat/Rocket.Chat/issues/18891

**Comment by k-ahn** [comment]
> Could be related to #18844 and #18891
These issues both reference issues after upgrade to 3.6. I have not upgraded - I'm running 3.2.2

**Comment by alvarow** [comment]
I use white label app as well, I got a warning from Rocket (red bar on top) telling me it was disabled for all users, that I had to enable it again after going through setup wizard, once I did the steps, it works fine again.

**Comment by superseby2** [comment]
Thx @alvarow . I double checked and realized the gateway was not setup properly to use rocket.chat's one. 

Sorry for the noise & thx for your help all !
