### ISSUE TITLE
Channel names in threads are not rendered correctly on main message view

### ISSUE THREAD

**Issue by stranljip** [RocketChat/Rocket.Chat#18896]
### Description:

When replying in a thread with a mention of a channel `#channel-name` the rendering of this in the main view is broken 

### Steps to reproduce:

1. Reply in a thread to a message
2. Include a channel in your reply (`#foo-channel`)

### Expected behavior:

The channel link is rendered as usual with the channel name and as a link to the channel

### Actual behavior:

The link is rendered fine if viewed in the thread view, but in the main view, only `[object Object]` is being shown

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0
- Deployment Method: Docker

### Client Setup Information

- Desktop App or Browser Version: Firefox 80.0.1, Chrome 85.0.4183.102
- Operating System: macOS 10.15.6

### Additional context

Same effect as with emojis in #18352

**Comment by Bengrunt** [comment]
I confirm we experience the same issue on our 3.5.0 deployment.

**Comment by faxm0dem** [comment]
here's a screenshot
![18896](https://user-images.githubusercontent.com/112638/94113151-bf5e1000-fe46-11ea-8eb6-842025125db1.png)

**Comment by Bengrunt** [comment]
Seems like the issue was fixed in between 3.5.0 and 3.6.2.  
We upgraded yesterday.

**Comment by MartinSchoeler** [comment]
Yep, this should be fixed on the latest version, if you experience it again, please reopen this with updated details.  Thanks!
