### ISSUE TITLE
Mobile App - cannot establish secure connection

### ISSUE THREAD

**Issue by plociu84** [RocketChat/Rocket.Chat#18908]
### Description:

After changing tls certificate to wildcard type, mobile app cannot conect to server.

### Steps to reproduce:

1. Changing certificate to wildcard type.
2. Changing configuration on caddy file.
3. Deskto App works fine, www works fine.
4. Mobile App cannot conect.

### Expected behavior:

Secure connection to server.

### Actual behavior:

Cannot establishe secure connection.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.1
- Operating System: Ubuntu 18.04
- Deployment Method: Clean install.
- Number of Running Instances: 1
- DB Replicaset Oplog: 205
- NodeJS Version: 12.18.3
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 4.10.0
- Operating System: Androind 8,9,10

**Comment by ankar84** [comment]
We are using wildcard certificate for Rocket Chat on-premise server without any issues on mobile, desktop or web client.
I think that issue should be transferred to RC RN repo https://github.com/RocketChat/Rocket.Chat.ReactNative/issues

**Comment by plociu84** [comment]
Please close the issue. Problem was in my cert. Lack of intermaediate cert insiede. Sorry for the noise.
