### ISSUE TITLE
install hang during run of main.js when updating WordPress_secret table

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1891]
Went through the setup of the recent version on a freshly set up und updated Ubuntu 14.04 LTS. 
During the setup while running main.js the console operations  stuck at table WordPress_secret. Don't know if setup completed successfully anyway. However, the website was showing a login screen. So I tried to register the first user through the website. But that action stucked also.
After rebooting the system, I tried to start the Rocket.Chat process again by running $meteor in a console window, as written in the documentation - but seems to have no effect anyway. 
Is it me who is doing wrong? I thought I was just precisely following every step of the documentation...

**Comment by marceloschmidt** [comment]
Please share the docs you followed, so we can see if there's a missed step? Thanks.

**Comment by finius** [comment]
Sure - here you are: 
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

**Comment by marceloschmidt** [comment]
OK, I fired up a Ubuntu 14.04 on Digital Ocean to follow this tutorial and see if I run into any problems. I'll let you know as soon as I finish deploying.

**Comment by finius** [comment]
cool - Thnx!

**Comment by marceloschmidt** [comment]
@finius, when you say that the server is stuck at Wordpress_secret, that is normal. It is not stuck, it's just that it finished loading... 
![image](https://cloud.githubusercontent.com/assets/1986378/12297669/56c6b5dc-b9f5-11e5-9c1d-b4372b0dd91e.png)
Then you said you couldn't create an account. What happened? Did you get to this screen?
![image](https://cloud.githubusercontent.com/assets/1986378/12297697/78999aee-b9f5-11e5-968c-2fa10bacc317.png)
What about this one?
![image](https://cloud.githubusercontent.com/assets/1986378/12297707/82599746-b9f5-11e5-9770-7198efe8f92e.png)
After choosing your username, you should be logged in.

**Comment by finius** [comment]
ok, then indeed the "hang" at WordPress_secrets is a normal behaviour - check. ;-) So, how do I cleanly quit this process? Just terminate the terminal?

Account creation was the same as you showed with the exception of not getting your second "REGISTER USERNAME" screen. The browser just kept on loading the page - maybe because I terminated the installation terminal (that seemed to stuck at the "WordPress_secret") a moment ago before creating the first user using the webpage.

However, I still wasn't able to restart the Rocket.Chat process after a reboot. Following https://github.com/RocketChat/Rocket.Chat/wiki/Creating-the-First-Admin I would guess, that I have to open a terminal and run "$ Meteor" inside the Rocket.Chat root directory. But this has no effect - neither a Website Shows up on localhost:3000 nor is any output shown in the terminal.

Although I would really appreciate a similar step-by-step guide how to add Rocket.Chat to be autostarted after a reboot. This would be quite essential to a server service and is imho not less part of the installation procedure.

Anyway, thank you very much so far for your support in this matter!

**Comment by marceloschmidt** [comment]
Aha! By killing the "installation" process, you also killed your running application. I agree, we should probably make an effort to unify all tutorials on how to install Rocket.Chat. To run your instance again, you should not call `$ meteor`, as that works only when you're running it through meteor, which is not your case. You're running it through node, by running a compiled version of Rocket.Chat. So, to restart, you should just call 
```
export ROOT_URL=http://your-host-name.com-as-accessed-from-internet:3000/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3000

node main.js
```
The wiki https://github.com/RocketChat/Rocket.Chat/wiki/Creating-the-First-Admin assumes you're running it through meteor, which is just wrong for any production development... 
To make it autostarted after a reboot, there are many options out there. We use pm2, but you could use anything that suits you, although I agree we should have something in the wikis regarding this.

**Comment by finius** [comment]
That starting method worked like a charm! Thnank you very much!
I will try to find out how to add Rocket.Chat to Ubuntu autostart using pm2. However, if you could provide any hint in this case I would really appreciate that!

Unfortunately., the problem now is the login. Because of my failed registration of the first user before (you know, I killed the process during my first try for registration) I am neither able to register my user (again) nor to login. 
You told me already not to use meteor in my Scenario. But how am I able to edit database entries beside the documented method? How can I reset my failed logiin registration/user?
