### ISSUE TITLE
first user should be auto admin

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1892]
Wouldn't it be useful if the first created user in the system/db is automatically flagged with admin privileges? I found it very geeky to have to manually edit the database to set an admin flag.

**Comment by marceloschmidt** [comment]
That's exactly what happens! First registered user is set as admin. Did this not work for you?

**Comment by marceloschmidt** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/server%2Flib%2Faccounts.coffee#L83-L85

**Comment by finius** [comment]
Ah, okay... maybe the same issue as the meteor thing, cause I was up to follow this guide:
https://github.com/RocketChat/Rocket.Chat/wiki/Creating-the-First-Admin
