### ISSUE TITLE
Deactivating user confirm windows bug

### ISSUE THREAD

**Issue by Shaverdoff** [RocketChat/Rocket.Chat#18926]
### Description:
Then choose to deactivate user pop configrm windows and cant tap on button. screen appear to gray out.
### Steps to reproduce:

1. go to Administration
2. click&search user
3. click tripod and choose deactivating

![изображение](https://user-images.githubusercontent.com/43804710/93331950-1c980700-f832-11ea-9b2c-c0f81f005580.png)

### Expected behavior:

able to confirm action

### Actual behavior:

Gray window with out posibilities to cancel or some action until reload page on web or close&open client

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: centos 7.2
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: v12.16.1
- MongoDB Version: 4/0/19

### Client Setup Information

- Desktop App or Browser Version: any
- Operating System: any

**Comment by ankar84** [comment]
Fixed in #18596
