### ISSUE TITLE
Cannot block a user

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat#18930]
### Description:

We recently upgraded to server 3.6.0, and I'm having trouble understanding the new rules surrounding "block user". I can see that it's in the code still (userActions.js), but I can never seem to re-create the circumstances that allow me to block someone now. In our old server (2.4.9), we had the option to block users right from the user info panel...it doesn't seem to be there anymore. As I mentioned, I do see it in userActions.js, but it never seems to appear as an option when I click the three dots menu next to a user. I have tried in public, private, and DMs.

Perhaps not a bug, but a lack of understanding on how I can get this to work now.

### Steps to reproduce:

1. Go to any channel's members list
2. Click the three dots button to reveal options
3. "Block User" never appears for anyone
4. A DM is probably the place where this *should* appear, but there is no button or option there anymore (as far as I can see).

### Expected behavior:

I should be able to block a user

### Actual behavior:

I do not see the option to block a user like I did in previous server versions.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
It was fixed for private chats, but I think it should remain for DMs but I don't how to block a user.
First issue https://github.com/RocketChat/Rocket.Chat/issues/17400
