### ISSUE TITLE
RocketChat verison 3.5.1 not working on IE11

### ISSUE THREAD

**Issue by cindy-codeli** [RocketChat/Rocket.Chat#18935]
**Steps to reproduce:**
1. start rocketchat server 3.5.1
2. load rocketchat on IE11 and it gets stuck at the 3 dots. 

**Expected behavior:**
Rocket Chat 3.5.1 loads correctly on IE 11.

**Actual behavior:**
Running RocketChat version 3.5.1 on IE11. it it gets stuck at the 3 dots. 

**Server Setup Information:**
Version of Rocket.Chat Server: 3.5.1
Operating System: Centos
Deployment Method: Tar
NodeJS Version: 12.16.1
MongoDB Version: 4.2.5

**Comment by ankar84** [comment]
Don't use IE, use Chrome or other modern browser, even Edge (it based on Chrome).
[MS calls IE a compatibility solution](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/the-perils-of-using-internet-explorer-as-your-default-browser/ba-p/331732) (not a browser)

**Comment by ggazzo** [comment]
please update do 3.6.0, should be working, but its not the best experience =/
