### ISSUE TITLE
Livechat trigger configuration page don't load... I'm geting blank page

### ISSUE THREAD

**Issue by adolfombarros** [RocketChat/Rocket.Chat#18949]
### Description:

The original omnichannel trigger configuration page has only one addition icon and it worked !

After I added a trigger, the page doesn't load... It's always showing a blank page

### Steps to reproduce:

1. Go to 'Omnichannel - Livechat trigger'
2. Click on 'add icon' and fill in the fields according to the desired trigger'
3. Click on 'save(add)' so get a blank page and nothing happens, no error message and no trigger added.

### Expected behavior:

Display the added trigger

### Actual behavior:

Display a blank page !

When I click on livechat trigger, the trigger information is not loaded and a blank page is displayed.

No error is displayed.

![Screenshot from 2020-09-17 21-23-34](https://user-images.githubusercontent.com/59097749/93552412-d08ab680-f946-11ea-99a4-93480e933b40.png)

![Screenshot from 2020-09-17 21-24-34](https://user-images.githubusercontent.com/59097749/93552133-1abf6800-f946-11ea-90cb-2c5a04e81d72.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0 and 3.6.1
- Operating System: Linux x64 4.15.0-115-generic
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Ativado
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: RocketChat Snap stable/latest (2.17.11), Google Chrome 85 and Firefox 80 
- Operating System: Ubuntu 20.04 and Windows 10

### Relevant logs:

BROWSER LOGS
Error: Minified React error # 130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ug (/node_modules/react-dom/cjs/react-dom.production.min.js:283)
    at eval (/node_modules/react-dom/cjs/react-dom.production.min.js:156)
    at R (/node_modules/react-dom/cjs/react-dom.production.min.js:181)
    at Rj (/node_modules/react-dom/cjs/react-dom.production.min.js:273)
    at Qj (/node_modules/react-dom/cjs/react-dom.production.min.js:254)
    at Kj (/node_modules/react-dom/cjs/react-dom.production.min.js:254)
    at yj (/node_modules/react-dom/cjs/react-dom.production.min.js:247)
    at eval (/node_modules/react-dom/cjs/react-dom.production.min.js:131)
    at exports.unstable_runWithPriority (/node_modules/scheduler/cjs/scheduler.production.min.js:27)
    at cg (/node_modules/react-dom/cjs/react-dom.production.min.js:130)
Ci @ /node_modules/react-dom/cjs/react-dom.production.min.js:217

SERVER LOGs

LocalStore: store created at ,
LocalStore: store created at ,
LocalStore: store created at ,
Setting default file store to GridFS,
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 205","time":{"$date":1600393972265},"level":"info"},
ufs: temp directory created at "/tmp/ufs",
Updating process.env.MAIL_URL,
Using GridFS for custom sounds storage,
Using GridFS for custom emoji storage,
Loaded the Apps Framework and loaded a total of 7 Apps!,
Browserslist: caniuse-lite is outdated. Please run next command `npm update`,
➔ System ➔ startup,
➔ +---------------------------------------------------+,
➔ |                   SERVER RUNNING                  |,
➔ +---------------------------------------------------+,
➔ |                                                   |,
➔ |  Rocket.Chat Version: 3.6.1                       |,
➔ |       NodeJS Version: 12.16.1 - x64               |,
➔ |      MongoDB Version: 4.0.20                      |,
➔ |       MongoDB Engine: mmapv1                      |,
➔ |             Platform: linux                       |,
➔ |         Process Port: 3000                        |,
➔ |             Site URL: https://chat.cbm.al.gov.br  |,
➔ |     ReplicaSet OpLog: Enabled                     |,
➔ |          Commit Hash: 6a4f474edb                  |,
➔ |        Commit Branch: HEAD                        |,
➔ |                                                   |,
➔ +---------------------------------------------------+,
(node:9) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.,

**Comment by rsgodinez** [comment]
Same issue for us! Started sin 3.6.0.

**Comment by cur1ou5soul** [comment]
Same issue for me.

**Comment by alexherdt** [comment]
Same issue for me on 3.6.2. (fresh installation)

**Comment by cur1ou5soul** [comment]
If I use my browser I can see this error wenn clicking on the livechat tab

Error: Minified React error #130;

**Comment by leofass** [comment]
same issue on 3.6.1

**Comment by cur1ou5soul** [comment]
Same Issue on 3.6.3
