### ISSUE TITLE
Livechat error when closing chat

### ISSUE THREAD

**Issue by sebudot** [RocketChat/Rocket.Chat#18952]
Description:

Multiple javascript errors when closing a livechat conversation.

Steps to reproduce:

1. Open livechat from client
2. Close chat (by any visitor,agent,api)
3. Multiple console errors sometimes requiring a page refresh

Expected behavior:
Closing chats should not bug the agent page

Actual behavior:
![error1](https://user-images.githubusercontent.com/22764793/93570801-3e150200-f99c-11ea-9959-c23e4b84810a.PNG)
![error2](https://user-images.githubusercontent.com/22764793/93570803-3ead9880-f99c-11ea-94e7-a4e5c00b68c8.PNG)
![error3](https://user-images.githubusercontent.com/22764793/93570797-3ce3d500-f99c-11ea-8bc6-bb374bb4feeb.PNG)
![error4](https://user-images.githubusercontent.com/22764793/93570800-3e150200-f99c-11ea-9c21-054d4982b574.PNG)

 Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0 and 3.6.1
- Operating System: Debian 9
- Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: 12.16.1
MongoDB Version: 4.0.20

 Client Setup Information

Desktop App or Browser Version:  Google Chrome 85 and Firefox 80
Operating System: Debian 9 and Windows 10

Additional context

Whenever a livechat is closed we see the console spammed with these errors. The behaviour is replicated both in dev and production environments. Usually it does not affect functionality but sometimes it bugs users status - is shown as active but actually busy and only gets fixed after a refresh

Relevant logs:

Exception in delivering result of invoking 'livechat:getTagsList': TypeError: "tagsList is undefined"
    module closeRoom.js:185
    process2faReturn callWithTwoFactorRequired.js:25
    call callWithTwoFactorRequired.js:74
    bindEnvironment meteor.js:1234
    _maybeInvokeCallback MethodInvoker.js:52
    receiveResult MethodInvoker.js:71
    _livedata_result livedata_connection.js:1508
    onMessage livedata_connection.js:1667
    processResult meteorCallWrapper.ts:46
    _DDPSendOverREST meteorCallWrapper.ts:51
    bindEnvironment meteor.js:1234
meteor.js:1061:23
Exception in template helper: getUserStatus@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10174:3
userStatus@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10288:12
bindDataContext/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2850:16
module/Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1566:16
wrapHelper/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2903:66
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
wrapHelper/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2902:27
Spacebars.call@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:172:18
Spacebars.mustacheImpl@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:106:25
Spacebars.mustache@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:110:39
class@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:9903:87
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
visitAttribute@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2041:52
visitAttributes@http://localhost:3000/packages/htmljs.js?hash=c52d96e73a36896980b68a9b66c659292f8e393f:223:44
visitAttributes@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2036:63
module/Blaze._expandAttributes@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2064:6
updateAttributes@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1451:33
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1776:18
_compute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
meteor.js:1059:23
Exception in template helper: getUserStatus@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10174:3
userStatus@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10288:12
bindDataContext/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2850:16
module/Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1566:16
wrapHelper/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2903:66
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
wrapHelper/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2902:27
Spacebars.call@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:169:51
Spacebars.mustacheImpl@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:106:25
Spacebars.mustache@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:110:39
title@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:9906:30
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
visitAttribute@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2041:52
visitAttributes@http://localhost:3000/packages/htmljs.js?hash=c52d96e73a36896980b68a9b66c659292f8e393f:223:44
visitAttributes@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2036:63
module/Blaze._expandAttributes@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2064:6
updateAttributes@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1451:33
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1776:18
_compute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
meteor.js:1059:23
Exception in template helper: getUserStatusText@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10179:3
userStatusText@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10292:24
bindDataContext/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2850:16
module/Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1566:16
wrapHelper/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2903:66
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
wrapHelper/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2902:27
Spacebars.call@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:172:18
Spacebars.mustacheImpl@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:106:25
Spacebars.mustache@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:110:39
module/Template.headerRoom</</</</<@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:9911:28
doRender@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1925:25
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1776:18
_compute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
meteor.js:1059:23
Exception in template helper: isDirect@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10191:18
bindDataContext/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2850:16
module/Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1566:16
wrapHelper/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2903:66
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
wrapHelper/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2902:27
Spacebars.call@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:172:18
module/Template.headerRoom</<@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:9850:22
module/Blaze.If/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2535:44
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1776:18
_compute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
meteor.js:1059:23
Exception in template helper: hasPresence@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:10187:12
bindDataContext/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2850:16
module/Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1566:16
wrapHelper/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2903:66
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
wrapHelper/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2902:27
Spacebars.call@http://localhost:3000/packages/spacebars.js?hash=6f2be25813c793c0b363a6a91ebb029723f294ec:172:18
module/Template.headerRoom</<@http://localhost:3000/app/app.js?hash=b5a2705f71c0066c9d466640d274ec6208bf0af0:9891:22
module/Blaze.If/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2535:44
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
module/Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
module/Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1776:18
_compute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
meteor.js:1059:23

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
