### ISSUE TITLE
[Bug] 'Custom Fields to Show in User Info' is broken since version 3.6.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#18953]
### Description:

I'm currently on version 3.1.1 in product environment and now testing 3.6.0 in test environment.
And I see, that **Custom Fields to Show in User Info** is broken in 3.6.0
Maybe it was broken early, I don't know that.

### Steps to reproduce:

1. Go to **Admin UI - Account** and set **Custom Fields to Show in User Info** like this `[{"Телефон":"#{telephoneNumber}"},{"Почта":"#{email}"}, {"Должность":"#{Title}"},{"Отдел":"#{Department}"},{"Город":"#{l}"}]`
2. That settings works good in 3.1.1
3. That settings do nothing in 3.6.0

### Expected behavior:

Custom Fields to Show in User Info should continue work as expected.

### Actual behavior:

3.1.1
![image](https://user-images.githubusercontent.com/4023037/93588931-c43d4280-f9b4-11ea-975a-4444712173e8.png)
3.6.0
![image](https://user-images.githubusercontent.com/4023037/93589130-0cf4fb80-f9b5-11ea-9eeb-d05a1f9c6dca.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 2.17.8
- Operating System: Windows 10

### Additional context

In test environment I changed a little couple custom fields, but even non changed fields now broken

Here is a custom fields from 3.1.1

````
{
	"telephoneNumber": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 12,
		"public": true
	},
    "email": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 50,
		"public": true
	},
	"Title": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 50,
		"public": true
	},
	"Department": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 50,
		"public": true
	},
	"l": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 20,
		"public": true
	}
}
````
Here is a Custom Fields to Show in User Info from 3.1.1
`[{"Телефон":"#{telephoneNumber}"},{"Почта":"#{email}"}, {"Должность":"#{Title}"},{"Отдел":"#{Department}"},{"Город":"#{l}"}]`
Here is a User data field map from 3.1.1
`{ "displayName": "name","mail": "email" ,"telephoneNumber":"customFields.telephoneNumber","title":"customFields.Title","department":"customFields.Department","l":"customFields.l"}`

Custom fields from 3.6.0
````
{
	"telephoneNumber": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 12,
		"public": true
	},
    "email": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 50,
		"public": true
	},
	"title": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 50,
		"public": true
	},
	"department": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 50,
		"public": true
	},
	"city": {
		"type": "text",
		"required": false,
		"minLength": 0,
		"maxLength": 20,
		"public": true
	}
}
````

Here is a Custom Fields to Show in User Info from 3.6.0
`[{"Телефон":"#{telephoneNumber}"},{"Почта":"#{email}"}, {"Должность":"#{title}"},{"Отдел":"#{department}"},{"Город":"#{city}"}]`

Here is a User data field map from 3.6.0
`{ "displayName": "name","mail": "email" ,"telephoneNumber":"customFields.telephoneNumber","title":"customFields.title","department":"customFields.department","l":"customFields.city"}`

### Relevant logs:

No logs

**Comment by robertfromont** [comment]
I also see this in version 3.6.2.

I have also tried specifying the _Custom Fields to show in User Info_ in the style that I _think_ the [manual](https://docs.rocket.chat/guides/administrator-guides/custom-fields#show-custom-fields-on-the-users-info) implies, i.e.

```
[{"Телефон":"telephoneNumber"}
``` 

To no avail.

**Comment by ankar84** [comment]
@pierre-lehnen-rc can you take a look at that issue?

**Comment by ankar84** [comment]
> I have also tried specifying the _Custom Fields to show in User Info_ in the style that I _think_ the [manual](https://docs.rocket.chat/guides/administrator-guides/custom-fields#show-custom-fields-on-the-users-info)

Yeap, I did that test too, with no luck

**Comment by ankar84** [comment]
Same of 3.6.3

**Comment by ankar84** [comment]
Same in 3.10.0
![image](https://user-images.githubusercontent.com/4023037/104880089-08931c00-5970-11eb-80c7-eb10bcaa62e9.png)
![image](https://user-images.githubusercontent.com/4023037/104880113-1183ed80-5970-11eb-905b-8a9a3e665886.png)

**Comment by ankar84** [comment]
Still an issue in 3.12.
![image](https://user-images.githubusercontent.com/4023037/111408372-41d4d780-86e6-11eb-802d-cc158c7670aa.png)

**Comment by dougfabris** [comment]
@ankar84 We already have a PR to fix it. Thanks for reporting and helping us!
