### ISSUE TITLE
[Bug] Since 3.6.x, role with "archive-room" permission cannot archive discussions

### ISSUE THREAD

**Issue by luixxiul** [RocketChat/Rocket.Chat#18967]
### Description:

Since 3.6.x (I assume 3.6.0) those who with `archive-room` permission cannot archive discussions, while `admin` can (with that permission).

For me the issue can be reproduced on 3.6.2. I have not tried on either 3.6.0 or 3.6.1 as I have updated directly from the latest 3.5.x.

On the 3.5.x the issue has not been experienced.

### Steps to reproduce:

1. Create a user
2. Apply `moderator` role to the user
3. Open `/admin/permissions`
4. Apply `archive-room` permission to `moderator`
5. Switch to the user
6. Start a discussion
7. Open details pane
8. Click `Edit`

### Expected behavior:

`Archived` toggle should be available

### Actual behavior:

The toggle is not available with disabled state.

![Clipboard01](https://user-images.githubusercontent.com/3362943/93667042-63743f80-fa72-11ea-8120-bf159bf22c4c.png)

The user with `admin` role can archive the discussion anyway, but the error message `Invalid settings provided [error-invalid-settings]` appears:

![Clipboard01](https://user-images.githubusercontent.com/3362943/93667153-278daa00-fa73-11ea-9712-490d862b29c0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Vivaldi
- Operating System: Windows 10

**Comment by jordan808** [comment]
I'm having a similar issue. Users with "Archive Room" permissions can't archive the room, only admin with that permission can. Currently running 3.6.2

**Comment by adam-bapm** [comment]
I am also having his issue.  I have noticed that using the /archive command in the room does work as expected however the toggle is still greyed out.

**Comment by luixxiul** [comment]
@adam-bapm Thanks for confirming the version. The issue still persists on 3.7.x on my side too. Haven't tested 3.8.x yet.

**Comment by MJPGPleasant** [comment]
Have confirmed same behaviour in 3.8.0

**Comment by frostbtn** [comment]
The bug is still active in 3.12.1.

**Comment by tk-suzuki** [comment]
I think my RC server has same trouble.

Room owner cannot archive his own rooms on Windows 10 app (3.1.1) and Chrome browser, but can archive them on iPhone app (4.16.0).
My server is Rocket.Chat 3.12.1 (stable) on Snappy @ Ubuntu LTS.

**Comment by tmartincpp** [comment]
It seems fix in 3.16.1 as far as I can see.

**Comment by frostbtn** [comment]
Yep, looks like it's gone. I can't reproduce the behavior on Server 3.15.0 (latest snap) / Windows-client 3.2.1.

**Comment by luixxiul** [comment]
OK I'm closing the issue. Let me know if the issue appears again.
