### ISSUE TITLE
How to restrict non admin user from creating a new channel/room/group/discussion

### ISSUE THREAD

**Issue by RYG81** [RocketChat/Rocket.Chat#18970]
Hi,

I have installed RocketChat on my server, created some default channel/rooms for my teammates to chat on related topics, and disabled DM so that they can not discuss internally and all their discussion is available to everyone. But how I stop a non-admin user from creating a new channel/discussion as I do not want any member to discuss anything off topics and anything that I don't know. Please suggest.

**Comment by RYG81** [comment]
My issue is not related to any bug its for knowing how to do something.

**Comment by luixxiul** [comment]
I supect that should be handed over to the forum then: https://forums.rocket.chat/
