### ISSUE TITLE
Email Direct Reply only works with Debug Direct Reply enabled

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#18985]
### Description:

Direct Reply does not work without "Debug Direct Reply" enabled. If the switch "Debug Direct reply" is disabled there are no login attempts from Rocketchat to the IMAP Server. As soon as I switch debug on Rocketchat logs in and all messages get processed.

### Steps to reproduce:

1. Enable Email Direct Reply
2. Answer to a rocketchat email
3. Nothing happens.
4. Enable Debuf Direct Reply
5. Rocketchat logs in to IMAP and message shows up in channel

### Expected behavior:

Direct Reply works without debug enabled.

### Actual behavior:

Direct Reply only works with debug enabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Linux
- Deployment Method: docker / tar
- Number of Running Instances: 4 (error happens with one instance too)
- DB Replicaset Oplog: yes
- NodeJS Version: 2.16
- MongoDB Version: 4.0

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
