### ISSUE TITLE
Channels and groups do not show unread numbers?

### ISSUE THREAD

**Issue by louislivi** [RocketChat/Rocket.Chat#18989]
### Description:

![image](https://user-images.githubusercontent.com/23403807/93869179-0bea0400-fcfe-11ea-9f75-f5d0950dd2ea.png)

### Steps to reproduce:

...

### Expected behavior:

Number of unread messages

### Actual behavior:

...

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: -
- MongoDB Version: -

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Web

### Additional context

...

### Relevant logs:

...

**Comment by Cherkasik** [comment]
There is check box in Administration -> General Settings -> Number of unread. Have you enabled it?
If no, that's why it can happen

**Comment by louislivi** [comment]
Yes,only direct messages show this badge.
