### ISSUE TITLE
query without index 

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#18982]
Description:
Steps to reproduce:
Expected behavior:
Actual behavior:
Server Setup Information:
Version of Rocket.Chat Server: 3.3.3
Operating System: ubuntu
Deployment Method: docker
Number of Running Instances: 18
DB Replicaset Oplog: enabled
NodeJS Version: v12.16.1
MongoDB Version:4.2.1
Client Setup Information
Desktop App or Browser Version: chrome 81
Operating System: windows
Additional context
 

sql:

{"op":"query","ns":"rocketchat.rocketchat__trash","command":{"find":"rocketchat__trash","filter":{"hidden":{"$ne":true},"public":true,"__collection__":"settings","_deletedAt":{"$gt":{"$date":"2020-08-27T10:12:24.605+0800"}}},"projection":{"_id":1,"_deletedAt":1},"returnKey":false,"showRecordId":false,"lsid":{"id":{"$binary":"kI1ZTXeZTLSrnb+e4e30Vw==","$type":"04"}},"$clusterTime":{"clusterTime":{"$timestamp":{"t":1600650675,"i":2}},"signature":{"hash":{"$binary":"h1+OSc7I4viN/i5O/xUFkUgWOSE=","$type":"00"},"keyId":{"$numberLong":"6823956134236258307"}}},"$db":"rocketchat"},"keysExamined":756443,"docsExamined":756443,"cursorExhausted":true,"numYield":5909,"nreturned":0,"queryHash":"D1556815","planCacheKey":"80104137","locks":{"ParallelBatchWriterMode":{"acquireCount":{"r":{"$numberLong":"1"}}},"ReplicationStateTransition":{"acquireCount":{"w":{"$numberLong":"5911"}}},"Global":{"acquireCount":{"r":{"$numberLong":"5911"}}},"Database":{"acquireCount":{"r":{"$numberLong":"5910"}}},"Collection":{"acquireCount":{"r":{"$numberLong":"5910"}}},"Mutex":{"acquireCount":{"r":{"$numberLong":"1"}}}},"flowControl":{},"storage":{},"responseLength":242,"protocol":"op_msg","millis":1529,"planSummary":"IXSCAN { _deletedAt: 1 }"} |  
-- | --

**Comment by codeneno** [comment]
scan too many rows

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by codeneno** [comment]
@MartinSchoeler 
`{
	"op": "query",
	"ns": "rocketchat.rocketchat__trash",
	"command": {
		"find": "rocketchat__trash",
		"filter": {
			"__collection__": "permissions",
			"_deletedAt": {
				"$gt": {
					"$date": "2020-10-12T09:53:35.002+0800"
				}
			}
		},
		"projection": {
			"_id": 1,
			"_deletedAt": 1
		},
		"returnKey": false,
		"showRecordId": false,
		"lsid": {
			"id": {
				"$binary": "AOtLpSusQrqaVoiB+zG2Lw==",
				"$type": "04"
			}
		},
		"$clusterTime": {
			"clusterTime": {
				"$timestamp": {
					"t": 1602656341,
					"i": 29
				}
			},
			"signature": {
				"hash": {
					"$binary": "WBOha3neuKycZo7IOMuHamqbsvg=",
					"$type": "00"
				},
				"keyId": {
					"$numberLong": "6823956134236258307"
				}
			}
		},
		"$db": "rocketchat"
	},
	"keysExamined": 86691,
	"docsExamined": 86691,
	"cursorExhausted": true,
	"numYield": 677,
	"nreturned": 0,
	"queryHash": "A45C52CD",
	"planCacheKey": "6E25C2CC",
	"locks": {
		"ParallelBatchWriterMode": {
			"acquireCount": {
				"r": {
					"$numberLong": "1"
				}
			}
		},
		"ReplicationStateTransition": {
			"acquireCount": {
				"w": {
					"$numberLong": "679"
				}
			}
		},
		"Global": {
			"acquireCount": {
				"r": {
					"$numberLong": "679"
				}
			}
		},
		"Database": {
			"acquireCount": {
				"r": {
					"$numberLong": "678"
				}
			}
		},
		"Collection": {
			"acquireCount": {
				"r": {
					"$numberLong": "678"
				}
			}
		},
		"Mutex": {
			"acquireCount": {
				"r": {
					"$numberLong": "1"
				}
			}
		}
	},
	"flowControl": {},
	"storage": {},
	"responseLength": 242,
	"protocol": "op_msg",
	"millis": 227,
	"planSummary": "IXSCAN { _deletedAt: 1 }"
}
`

**Comment by codeneno** [comment]
![Uploading image.png…]()

**Comment by codeneno** [comment]
@MartinSchoeler please reopen this issue,please tell us what's the reson why it too slow
