### ISSUE TITLE
"There are no tokens for this user" push notifications 

### ISSUE THREAD

**Issue by Angrik** [RocketChat/Rocket.Chat#18999]
### Description:

Push notifications to mobile clients not working. User logged in both at desktop and mobile app through LDAP-authorizathion, but im getting "There are no tokens for this user [error-no-tokens-for-this-user]" with test push message.
We are using https://gateway.rocket.chat as gateway.

### Steps to reproduce:

Send test push notification

### Expected behavior:

Push notification to appear at mobile client

### Actual behavior:

Getting error  "There are no tokens for this user [error-no-tokens-for-this-user]" 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: CentOs 7
- Deployment Method: manual installation
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: windows 10, android, iOS

### Relevant logs:

I20200923-08:06:37.491(-4) Meteor ➔ method push_test -> userId: bhPRDRJDA7kNyh5CJ, arguments: []
I20200923-08:06:37.494(-4) Exception while invoking method push_test Error: There are no tokens for this user [error-no-tokens-for-this-user] at MethodInvocation.push_test (server/lib/pushConfig.js:51:10) at MethodInvocation.methodsMap. (app/lib/server/lib/debug.js:67:34) at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12) at packages/ddp-server/livedata_server.js:1689:15 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12) at packages/ddp-server/livedata_server.js:1687:36 at new Promise () at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12) at Server.apply (packages/ddp-server/livedata_server.js:1625:26) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:262:26) at app/api/server/api.js:388:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9 => awaited here: at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12) at Server.apply (packages/ddp-server/livedata_server.js:1638:22) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:262:26) at app/api/server/api.js:388:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js🔢12) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9
I20200923-08:06:37.497(-4) API ➔ debug Success { statusCode: 200, body: { message: '{"msg":"result","id":"94","error":{"isClientSafe":true,"error":"error-no-tokens-for-this-user","reason":"There are no tokens for this user","details":{"method":"push_test"},"message":"There are no tokens for this user [error-no-tokens-for-this-user]","errorType":"Meteor.Error"}}', success: true } }

**Comment by Angrik** [comment]
Ok, nevermind, i didnt connect my server to cloud service.

**Comment by SebastGG** [comment]
Hi all, i've the same problem. Does anyone know how to fix this?

**Comment by SebastGG** [comment]
i'm using lineage os without GAPPS. So, with my mobile phone it doesnt works! Same error as mentioned above! I've tested it with a google mobile phone and it works! 

So this might be the problem for me. Is there a way to use it without GAPPS?
