### ISSUE TITLE
Error when viewing a thread in a channel you haven't joined

### ISSUE THREAD

**Issue by dkoo761** [RocketChat/Rocket.Chat#19008]
### Description:

When previewing a channel (ie. they haven't joined yet), users can open a thread by clicking Reply button or clicking on a threaded reply that was posted to the main channel.

However, currently when they do this, instead of the thread pane loading, they get an "Undefined" error.

This seems like quite critical functionality since people will often browse a thread before joining or visit a thread to read something in it without actually joining.

### Steps to reproduce:

1. Go to Directory
2. Find a channel you want to preview and clicking on it to open
3a. Find any thread and click Reply OR
3b. Find any threaded reply that was also posted to the channel and click on it)

### Expected behavior:

Thread opens in right pane and threaded conversation is displayed.

### Actual behavior:

"Undefined" error

### Server Setup Information:

This is reproducible on open.rocket.chat.

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Linux / Ubuntu 18.04.3 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.16.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 85.0.4183.83 (Official Build) (64-bit)
- Operating System: Mac OSX High Sierra 10.13.6

**Comment by jordan808** [comment]
Running into similar problem. When I click a thread in a discussion of a channel I haven't joined, I get "Internal Server Error 500". After I join the channel, I try to see the thread, and I get the same error. There is no join button for the discussion, so the only way to see the thread is to send a message. The errors for this in the logs looks like this:

<img width="1375" alt="Screen Shot 2020-09-28 at 2 41 10 PM" src="https://user-images.githubusercontent.com/44143999/94489072-b055c580-0198-11eb-97c2-bb83cb55c52f.png">
