### ISSUE TITLE
Oauth error access url oauth/authorize : get Redirect URL does not match

### ISSUE THREAD

**Issue by otnansirk** [RocketChat/Rocket.Chat#19004]
### Description:

When I access url /oauth/authorize always redirect to /oauth/error/invalid_redirect_uri and get text message Redirect URL does not match.
What is happening ?

### Steps to reproduce:

1. Go to setting
2. Click on Oauth Apps
3. Iam create oauth app for get client id and key
4. Use that for login to my app with rocket chat.
5. And when click button login with rocket chat . BOOM get error like description above

### Expected behavior:

I hope it works

### Actual behavior:

error is:
"error": "Redirect URL does not match",
"error_description": "The redirect URI provided is missing or does not match",
"error_uri": "MY-DOMAIN.COM/oauth/error/invalid_redirect_uri"

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.1
- Operating System: Ubuntu Server 18.04
- Deployment Method: direct install
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.6

### Client Setup Information

- Desktop App or Browser Version: chrome / firefox
- Operating System: Win, Mac and Linux

### Additional context

N/A

### Relevant logs:

Nothing log

**Comment by krisnantobi** [comment]
Make sure you have entered the URL correctly in the oAuth Apps rocketchat settings.
