### ISSUE TITLE
PDF preview not working

### ISSUE THREAD

**Issue by plmorpheus** [RocketChat/Rocket.Chat#19010]
### Description:

None of preview of attached pfd are showing.

### Steps to reproduce:

1. Open desired channel
2. Add pdf as attachment
3. Click send

### Expected behavior:

After upload the pdf's preview should appear.

### Actual behavior:

Nothing happened, the file uploads but loading circle is infinitely appearing.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome  85.0.4183.121 / Windows Desktop App ver. 2.17.9
- Operating System: Windows

### Additional context

In server logs there is no any errors.

### Relevant logs:

Browser's console:
**Uncaught (in promise) Error: /node_modules/pdfjs-dist/build/pdf.js:23 Uncaught (in promise) Error:
Removed API method: PDFDocumentLoadingTask.then, use the `promise` getter instead.
    at r.then (/node_modules/pdfjs-dist/build/pdf.js:23)**

**Comment by ankar84** [comment]
Hello, @plmorpheus 
That issue was fixed in [3.7.0-rc.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.7.0-rc.0) via https://github.com/RocketChat/Rocket.Chat/pull/18956
You need to upgrade to [3.7.0-rc.1](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.7.0-rc.1) or wait until release 3.7.0.

**Comment by sampaiodiego** [comment]
the fix is also on 3.6.3
