### ISSUE TITLE
Bug API: Maximum number of guests reached

### ISSUE THREAD

**Issue by dlkuzmichev** [RocketChat/Rocket.Chat#19019]
### Description:
Send:
curl --location --request POST 'https://mydomain.rocket.chat/api/v1/users.create' \
--header 'X-Auth-Token: XXX' \
--header 'X-User-Id: XXX' \
--header 'Content-Type: application/json' \
--header 'Cookie: _51c14=http://10.42.79.58:3000' \
--data-raw '{"name":"Дима Тест","email":"test@gmail.com","password":"1231231231231231231231","username":"test","roles":["guest"],"joinDefaultChannels":false,"verified":true,"active":false}'

Error:
{
    "success": false,
    "error": "Maximum number of guests reached. [error-max-guests-number-reached]",
    "errorType": "error-max-guests-number-reached",
    "details": {
        "method": "insertOrUpdateUser",
        "field": "Assign_role"
    }
}

### Steps to reproduce:
up
### Expected behavior:

Create new user

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by gabriellsh** [comment]
I'd like to see the server setup filled up, also, are you an enterprise user?
