### ISSUE TITLE
Bug: No feedback messages when inviting users from Administration -> Users -> Invite

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#19021]
### Description:
No success or failure message provided when inviting email addresses from Administration -> Users -> Invite

![Screenshot from 2020-09-25 13-16-09](https://user-images.githubusercontent.com/1122344/94222658-54d5ce80-ff31-11ea-9316-fc4095b3e7c3.png)

### Steps to reproduce:
1. Open Administration, go to Users
2. Click on "Invite" top right
3. Add an email address
4. Click Send

### Expected behavior:
Message should display as to whether email successfully sent or not.

### Actual behavior:
No feedback is provided, although emails seem to send.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method:  TAR, manual
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Firefox 80.0.1 and Vivaldi 3.3.2022.45 (Stable channel) (64-bit)
- Operating System: Linux Mint 19.3 and Windows 10

### Relevant logs:

No console errors or server logs regarding this issue.

**Comment by wraith-0** [comment]
@MartinSchoeler @gabriellsh Hey guys, I am working on this issue, but while testing the changes, when I send an invite using my local workspace i am unable to do it, I have already registered with rocket chat cloud is there anything I have to do ??
Thanks

**Comment by gabriellsh** [comment]
Did you set up your smtp server correctly? I recommend using `maildev` for testing purposes.

**Comment by jdiegosierra** [comment]
@wraith-0 are you still working on this issue, can I take it?

**Comment by gabriellsh** [comment]
@jdiegosierra feel free to take it

**Comment by lightweight** [comment]
Yes, the complete lack of feedback on the form is very off-putting. And it doesn't appear to be sending the emails in my instance's case (3.7.1) either...

**Comment by nooblag** [comment]
Issue persists in 3.9.3.

**Comment by nooblag** [comment]
Issue persists in 3.10.3.
