### ISSUE TITLE
 Error in oplog callback TypeError: Cannot read property 'u' of undefined

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#19023]
Description:
Steps to reproduce:
Expected behavior:
Actual behavior:
Server Setup Information:
Version of Rocket.Chat Server: 3.3.3
Operating System: ubuntu
Deployment Method: docker
Number of Running Instances: 18
DB Replicaset Oplog: enabled
NodeJS Version: v12.16.1
MongoDB Version:4.2.1
Client Setup Information
Desktop App or Browser Version: chrome 81
Operating System: windows
Additional context
 Error in oplog callback
TypeError: Cannot read property 'u' of undefined

Relevant logs:

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
