### ISSUE TITLE
cannot send invitations when SMTP is configured without authentication 

### ISSUE THREAD

**Issue by pescobar** [RocketChat/Rocket.Chat#1902]
my smtp doesn't require authentication so I only configured ```SMTP Host``` and ```SMTP Port``` and I left username and password empty. When doing this I can send emails using the ```send a test email``` button but when I try to send invitation in admin >> users I get his error message:

```In order to send invitation e-mails, you must first configure SMTP settings```

If I try to add a fake smtp user and password the webui allows me to send invitations but I get this error in the logs:

```
Exception while invoking method 'sendInvitationEmail' AuthError: Invalid login - 503 5.5.1 Error: authentication not enabled
```

I found this error in latest docker image, I think version 0.9

**Comment by Sing-Li** [comment]
Duplicate #1883

**Comment by grassbl8d** [comment]
I get this error. .... 

I have SMTP Connecting to an SMTP Relay Server. I pass my username and password.
I think this is related to SMTP Auth which I need to specify plain....

Invalid login - 503 5.5.1 Error: authentication not enabled
rocketchat_1 |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat_1 |     at smtpSend (packages/email/email.js:86:1)
rocketchat_1 |     at Object.Email.send (packages/email/email.js:185:1)
rocketchat_1 |     at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:10:9)
rocketchat_1 |     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
rocketchat_1 |     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
rocketchat_1 |     at livedata_server.js:708:19
rocketchat_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
rocketchat_1 |     at livedata_server.js:706:40
rocketchat_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
