### ISSUE TITLE
Can't connect to self-hosted server from android app

### ISSUE THREAD

**Issue by hyahm** [RocketChat/Rocket.Chat#19034]
### Description:

Can't connect to self-hosted server from android app
### Steps to reproduce:

1.  Join a workspace
2. Enter url:  https://chat.hyahm.com
3. Connect

### Expected behavior:

Websocket is disabled for this server

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  centos 7.2
- Deployment Method:   Each application is installed separately 
- Number of Running Instances:  
- DB Replicaset Oplog: 
- NodeJS Version:   v12.14.0
- MongoDB Version: 4.4.1-rc0

### Client Setup Information

- Desktop App or Browser Version:  4.10.0.2135
- Operating System:  android

### Relevant logs:

![Screenshot_20200925_230921_chat rocket android](https://user-images.githubusercontent.com/22030094/94283883-2fbe7b80-ff84-11ea-86a2-568aba78f9b6.jpg)

**Comment by piotrkochan** [comment]
I think that You have to configure nginx properly 
https://stackoverflow.com/questions/17014969/meteor-websocket-handshake-error-400-with-nginx

**Comment by hyahm** [comment]
@piotrkochan   Yes, the problem with nginx has been solved, thank you

**Comment by anhhtz** [comment]
> @piotrkochan   Yes, the problem with nginx has been solved, thank you

Can you share your nginx conf, please ?
I am facing same problem.

**Comment by Kyogre** [comment]
FYI Same issue goes for iOS application.

We have nginx too, and, if I am correct, but we found [this post](https://stackoverflow.com/a/22750356/8874665). Adding this lines to config helped us:
```
         #websocket support
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
```

Thus way our config became like this:
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}


server {
    listen 443 ssl http2;
    server_name your_rocketchat_domain_url.com;
    client_max_body_size 1000M;

    ssl_certificate         "/etc/letsencrypt/live/our_rocketchat_domain_url.com/fullchain.pem";
    ssl_certificate_key     "/etc/letsencrypt/live/our_rocketchat_domain_url.com/privkey.pem";
    ssl_ciphers our_ciphers_list;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/our_rocketchat_domain_url.com.access.log;
    error_log /var/log/nginx/our_rocketchat_domain_url.com.error.log warn;

        location / {
         proxy_buffers 16 4k;
         proxy_buffer_size 2k;
         proxy_set_header Host $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_http_version 1.1;
         proxy_pass http://ip_of_our_rocketchat:3000/;
         #websocket support
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
    }
}
```
