### ISSUE TITLE
It's no flash window when public channel or private channel have incoming message.

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#19049]
### Description:

I can't see flash window if message incoming from public channel or private channel.It's only flash window when use direct message.It's only notification from windows right side.But if the channel users not see this notification.He always don't know have anybody send message to channel forever. 

### Steps to reproduce:

1. Choose any public channel or private channel
2. I write any message and send to channel
3. The channel users will not see any flash window.It's only show notification.

### Expected behavior:

I hope have a flash window when incoming message to any channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: v12.16.0
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 2.17.11
- Operating System: win10

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
