### ISSUE TITLE
3.6.3 User detail user image errror

### ISSUE THREAD

**Issue by col-panic** [RocketChat/Rocket.Chat#19040]
### Description:

Showing the user detail with 3.6.3 seems to have a problem correctly showing the user image, please see the following screenshot 

![grafik](https://user-images.githubusercontent.com/1679857/94402043-cac57a00-016b-11eb-8f1c-6e984909fbea.png)

### Steps to reproduce:

1. Create a new user in 3.6.3
2. Open user detail

### Expected behavior:

The icon and image should show correctly

### Actual behavior:

See above screenshot

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Safari/Firefox/Chrome
- Operating System: OS X

**Comment by piotrkochan** [comment]
It works on my instance (3.6.3)
![](https://i.imgur.com/C5z8ifk.png)

**Comment by col-panic** [comment]
@piotrkochan Did you create a new user, or have a first time login for this user?

**Comment by piotrkochan** [comment]
I've created new test user, logged in and it seems working 

![image](https://user-images.githubusercontent.com/5632761/94525458-64f0f500-0234-11eb-9267-30141766f9e2.png)

**Comment by ankar84** [comment]
Yeap, think all works fine in 3.6.3
![image](https://user-images.githubusercontent.com/4023037/94529617-9f618e80-0242-11eb-8d25-3856ffb8c8fd.png)

**Comment by col-panic** [comment]
weird - so this must be a problem with my installation!
