### ISSUE TITLE
Unable to edit user in Admin panel

### ISSUE THREAD

**Issue by willoughby** [RocketChat/Rocket.Chat#19054]
### Steps to reproduce:

1. Adminstration
2. Users
3. Search for my user
4. Click user 

### Expected behavior:

The user edit form

### Actual behavior:

White screen

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7 Digital Ocean deployment
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

User has User Role and Moderator role

### Relevant logs:
![image](https://user-images.githubusercontent.com/158088/94528708-ac758200-0230-11eb-83fe-317b37e1c8b7.png)

**Comment by Ats1999** [comment]
I would like to work on this.
I'm first timer. So, if anyone could guide me, then I'll move on.

**Comment by dougfabris** [comment]
@willoughby could you provide more info in **Server Setup Information**, **Client Setup Information** and your user info tab screenshot?
