### ISSUE TITLE
Messages encryption

### ISSUE THREAD

**Issue by mikonoid** [RocketChat/Rocket.Chat#1905]
Hello! In mongoDB messages storage in open format. How can I encrypt messages? May be there is any plugins for this? And how can I delete history on request or timing? 
sorry for my English)

**Comment by marceloschmidt** [comment]
We haven't implemented message encryption yet. There are quite a few issues requesting this, check them out: https://github.com/RocketChat/Rocket.Chat/labels/feat%3A%20anonymity%20%2F%20privacy. 
As for deleting history, if you delete a user, all their messages will also be gone. We currently don't support deleting a portion of messages.
