### ISSUE TITLE
Can't find which user in deactivate status

### ISSUE THREAD

**Issue by Cancer-zern** [RocketChat/Rocket.Chat#19051]
### Steps to reproduce:

1. Open web panel https://chat.example.net/admin/users/
2. Open account
3. Can find it on the menu only. Activate <-> Deactivate

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu Server 18.04 x64 LTS 
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: any browser
- Operating System:

### Relevant logs:

![image](https://user-images.githubusercontent.com/68541237/94517390-ddf24b80-0238-11eb-9142-7d121bea7445.png)

**Comment by ankar84** [comment]
Confirm that on 3.6.3
On activated user shows Activate.
When you Activated that already activated user - looks like nothing changes
When you then Deactivate that user - there is a message on green background that user was deactivated, but user status in user list not changed to deactivated, it remains offline or online.
![image](https://user-images.githubusercontent.com/4023037/94528920-bbb0fb80-0241-11eb-8221-ac63db51fb1b.png)
![image](https://user-images.githubusercontent.com/4023037/94528949-c8cdea80-0241-11eb-8a94-a7eb264c480e.png)

**Comment by ankar84** [comment]
Fixed in 3.7.0
![image](https://user-images.githubusercontent.com/4023037/94535652-7d6c0a00-024a-11eb-8e8d-d115089449f4.png)
