### ISSUE TITLE
Universal Windows Platform app

### ISSUE THREAD

**Issue by Morgy93** [RocketChat/Rocket.Chat#1907]
How about some Universal Windows Platform app, so you can use this across desktop and mobile devices?
With Apache Cordova this is really easy to implement. :)

**Comment by Sing-Li** [comment]
Done!
https://rocket.chat/
https://github.com/RocketChat/Rocket.Chat.Electron
https://github.com/RocketChat/Rocket.Chat.Cordova

**Comment by Morgy93** [comment]
That's not exactly what I meant.
I was wondering why the "official" RocketChat app is not an Universal Windows app?
It's really easy with some javascript universal Windows app and Project Westminster: https://channel9.msdn.com/Blogs/One-Dev-Minute/Creating-Hosted-Web-Apps-with-Project-Westminster (Creating Hosted Web Apps with Project Westminster)

**Comment by OdinWynd** [comment]
@Morgy93 Any luck with your suggestion?
@Sing-Li An official UWP SDK would be amazing, it goes beyond PC's and Phones... It also brings Hololens, Xbox One, Surface, and IoT. It is worth looking into..
