### ISSUE TITLE
Name changes (sidebar) keep reverting back to member's username

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat#19079]
### Description:
Display names changes are not permanently shown in the sidebar. After you exchange a couple of messages with this user, his display name gets switched back to his username.

### Steps to reproduce:
1. Change someone's name in the admin panel
2. Watch his display name being updated in your existing private chat (sidebar)
3. Write him a message
4. After some short time period his recent "Name" gets ignored and the sidebar shows his "Username" instead

### Expected behavior:
1. After you update someone's name, the change should be permanent and it should be reflected across all Rocket.chat environment.

### Actual behavior:
After you change a "Name", this new "Name" it's only temporarily shown in the direct messages (sidebar). After some short time member's "Username" it's shown instead of his newly set "Name.

### Server Setup Information:
* Version of Rocket.Chat Server: 3.7.0
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: Unknown - see rocketchat:3.4.1 image.
* MongoDB Version: 4.0.12

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 2.17.11

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

**Comment by benks-io** [comment]
It's not actually the Username that reappears but the previous "Display Name".
Also: When disabling "Allow Username Change" in Admin Menu the Display Name cannot be changed with the Error "Username cannot be Changed"... there seems to be some confusion about those two fields/labels in the code.

**Comment by bhdung** [comment]
Same my issue. Same my issue. when this will get fix sir?

Thank you!

**Comment by dougfabris** [comment]
@urosino Thank you for reporting! It's already fixed. Tested on 3.12.0-develop
