### ISSUE TITLE
[3.6.3] REST API groups.kick not working

### ISSUE THREAD

**Issue by fabiiretro** [RocketChat/Rocket.Chat#19081]
### Description:

Using groups.kick REST API fails remotely and locally with a room-not-found

### Steps to reproduce:

1. Get the userId and roomId in the admin panel
2. Use groups.kick example from the documentation with the respective parameters

### Expected behavior:

groups.kick should kick the given user out of the given room.

### Actual behavior:

groups.kick fails and delivers an The required \"roomId\" or \"roomName\" param provided does not match any group [error-room-not-found]","errorType":"error-room-not-found". groups.invite with the same parameters and especially the same room id works!
Also, why does it say roomName, when this isn't documented? Is this just a generic error message?

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: Brave Browser based on Chromium
- Operating System: Fedora Linux 32

**Comment by bhavayAnand9** [comment]
Hi! @fabiiretro  I tested the `group.kick` API locally, it worked for me.
Request
```
curl --location --request POST 'http://localhost:3000/api/v1/groups.kick' \
--header 'X-Auth-Token: 49AepRstsQwdp6pqVuxw7w2zfEfnkN9G12dqieF08fl' \
--header 'X-User-Id: bGttg5sDFR675h4GX' \
--header 'Content-type: application/json' \
--data-raw '{ "roomId": "KH97wzCvpp8aF7Snx", "userId": "mAvLrtnZFrpXtv4ro" }'
```
Response
```
{
    "success": true
}
```
and yes, I agree with that error message issue, API accepts `roomName` but it isn't documented.
I've started exploring rocket.chat just today, so please correct me If I'm wrong or not making sense.
Thanks

**Comment by fabiiretro** [comment]
Thanks for your feedback! On which version are you? 3.6.3 or 3.7 already?

Your call does look different from the documentation though.

But as I said, it doesn't work neither remotely or locally. groups.invite
works just fine.

**Comment by bhavayAnand9** [comment]
Hi! @fabiiretro Sorry, I didn't realize that I was on a much older version.
I'm testing `group.kick` now on the develop branch (version `3.8.0-develop`), it seems to be working & generating the same response.
```
{
    "success": true
}
```

**Comment by fabiiretro** [comment]
I finally got to test your version of the command, but that also gives me `{"success":false,"error":"The required \"roomId\" or \"roomName\" param provided does not match any group [error-room-not-found]","errorType":"error-room-not-found"}`
I'm quite surprised it doesn't seem to be a widespread problem though. The room (id) definetely exists, as I added some users to it beforehand. Also, I don't use some kind of wrong command or spelling mistake, as I use a literal copy from the `groups.invite` call and replace it with `.kick`

**Comment by fabiiretro** [comment]
Thanks for the suggestion but still the same error.

**Comment by fabiiretro** [comment]
Just a heads-up: 3.7.0 still gives me this error. 

We found out that our bot (roles bot and admin) can join rooms freely `(groups.invite)` and can leave them via `groups.kick` but for other users, it throws room-not-found.

We're on the official docker image, not the rocketchat one if that matters. I forgot to mention that in the original post.

**Comment by pythoneer** [comment]
I can confirm this behavior on a rocket.chat 3.14.0 installation. Is this intended behavior that should be documented?

**Comment by fabiiretro** [comment]
Not sure whether this is still a thing; closing it to get it off my dashboard
