### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1909]
When trying to repeat my Rocket.Chat installation on a Hyper-V Machine running a freshly set up Ubuntu 14.04.2 LTS, I ran into the following error when trying to install RocketChat following the install guide https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker:
![unbenannt](https://cloud.githubusercontent.com/assets/5287181/12320597/c9f2a6c4-baa9-11e5-9e14-6ed44c0903c2.JPG)
regardless of runnig "npm install" as root or not - error 127 occurs every time and I don't know why or how to fix it. (What means "the use of binary node" ins this case??)

**Comment by marceloschmidt** [comment]
Can you check your node version, please? `node -v`.

**Comment by finius** [comment]
results in this
![node](https://cloud.githubusercontent.com/assets/5287181/12323656/99ffdd06-babd-11e5-9b88-5c39b24f85b4.JPG)

**Comment by tuudik** [comment]
Seems like you dont have node installed:
```
# SYSTEM CONFIGURATION
sudo apt-get update
sudo apt-get install -y npm 
sudo npm install -g n
sudo n 0.10.40
```

**Comment by finius** [comment]
Thanks - that worked for me! I could bet it had already been installed in the vm snapshot I reverted that time. Anyway - thanks for your support!
