### ISSUE TITLE
Admin user loses role when custom register fields write on roles and admin edit his profile. 

### ISSUE THREAD

**Issue by alfonsolsl** [RocketChat/Rocket.Chat#19090]
### Description:
Admin user loses role when custom register fields write on roles without including admin on it and admin edit his profile. 

### Steps to reproduce:

1. On Accounts setting go to register
2. On custom field add (for example): 
```
{
 "role": {
  "type": "select",
  "defaultValue": "padre/madre",
  "options": ["profesor", "estudiante","padre/madre"],
  "required": true
   "modifyRecordField": {
     "array": true,
     "field": "roles"
  }
 },
 "Código de Familia:": {
  "type": "text",
  "required": true,
  "minLength": 1,
  "maxLength": 5,
  "private": true
 }
}
```
save
3. edit the profile of an admin, like maybe changing passw or bio.
4. the Role option will be blocked at one of the last 3 on the custom fields.
5. When you save the profile also change role, losing admin **PLUS** in this case when try to enter in a browser version you get a white screen.

### Expected behavior:

As admin, the role list have to be full with all the roles on the domain.

Plus the "defaulvalue" should be only for the register screen, the user should see the actual role when access to profile editing.

### Actual behavior:

On the profile appears a "new" role select and the "old" role select disappears, the new select options are limited to the custom fields of the register section of the Account preferences.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: ubuntu 16.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: chrome, firefox, safari.
- Operating System: windows / mac

**Comment by alfonsolsl** [comment]
BTW the "defaultValue" does not work.

i use this from he example on the same page:

```
{
 "role": {
  "type": "select",
  "defaultValue": "student",
  "options": ["teacher", "student"],
  "required": true,
  "modifyRecordField": {
   "array": true,
   "field": "roles"
  }
 },
 "twitter": {
  "type": "text",
  "required": true,
  "minLength": 2,
  "maxLength": 10
 }
}

```

**Comment by gabriellsh** [comment]
Can you send a video/screenshot of this happening? My roles field doesn't disappear under any circumstances. I can confirm the defaultValue field is not being accounted for. Also I haven't seen any roles be lost when saving custom fields.

**Comment by dougfabris** [comment]
@alfonsolsl The behavior you mentioned about losing others roles and the default value not working it's fixed. Thanks for the report, it showed other errors for us
