### ISSUE TITLE
Screen Sharing Error

### ISSUE THREAD

**Issue by 5an1ty** [RocketChat/Rocket.Chat#1910]
I receive this error when trying to enable screen sharing. I see no window to select a screen to share. It seems like there is something blocking the add on from working?

This is using firefox 38.5

```
12:06:14.040 MediaStreamError { name: "PermissionDeniedError", message: "The user did not grant permission f…", constraintName: "" }1 rocketchat_webrtc.js:313:11
WebRTCClass.prototype.onError() rocketchat_webrtc.js:313
WebRTCClass.prototype.getLocalUserMedia/onError</<() rocketchat_webrtc.js:629
WebRTCClass.prototype.getUserMedia/getScreen</<() rocketchat_webrtc.js:561
WebRTCClass.prototype.getUserMedia() rocketchat_webrtc.js:582
WebRTCClass.prototype.getLocalUserMedia() rocketchat_webrtc.js:632
WebRTCClass.prototype.setScreenShareEnabled() rocketchat_webrtc.js:731
WebRTCClass.prototype.enableScreenShare() rocketchat_webrtc.js:721
["click .enable-screen-share"]() rocketchat_ui.js:7270
Template.prototype.events/eventMap2[k]</</<() blaze.js:3697
Template._withTemplateInstanceFunc() blaze.js:3671
Template.prototype.events/eventMap2[k]</<() blaze.js:3696
attached_eventMaps/</</</<() blaze.js:2557
Blaze._withCurrentView() blaze.js:2211
attached_eventMaps/</</<() blaze.js:2556
HandlerRec/this.delegatedHandler</<() blaze.js:833
jQuery.event.dispatch() jquery.js:4690
jQuery.event.add/elemData.handle() jquery.js:4359
```

**Comment by marceloschmidt** [comment]
Please share a little more details:
Operating System / Version / Architecture (64 bit?)
Have you installed the Browser Extension? (did RC offer you an extension?)
Are you testing this in the demo server or own deployment?
Thanks.

**Comment by 5an1ty** [comment]
The Client is Windows 7 64 Bit.

Own deployment, it did offer to install the extension and I installed it.

Using the demo server I can share my screen with Rocket.Cat and I get a popup in firefox asking me what window to share.

I however do not get that message on my own server (windows 32 bit). And it's running in dev mode (meteor).

Video sharing works in both environments.

**Comment by engelgabriel** [comment]
To be done as part of #933

**Comment by capensisma** [comment]
@5an1ty it seems you didn't allow the screensharing your browser! that is why it's throwing this error : `PermissionDeniedError` though it should be handled in a nicer why!

Can you try again and see if it works?

**Comment by 5an1ty** [comment]
@capensisma That's the strange thing. When I try it out on the Rocket.Chat demo server, I get a popup in firefox asking me if I want to share my screen. If I accept the screen sharing works as expected.

The problem is that this does not seem to work on my own server. I get a popup asking me if I want to share my webcam (Then video chat will work). Then if I click screen sharing, nothing happens, no popup, nothing, just the error message in the console.

**Comment by engelgabriel** [comment]
Are you using SSL?

**Comment by 5an1ty** [comment]
@engelgabriel Yes, self signed.

**Comment by engelgabriel** [comment]
This may be a problem.. some browsers have security webrtc restrictions for non-SSL and self signed SSL

**Comment by capensisma** [comment]
@5an1ty You just didn't allow the screen sharing permission from firefox! did you install the extension too?

**Comment by 5an1ty** [comment]
@capensisma I am 200% sure that if there would have been a popup asking me I would  have known. On the test website I do get the notification to allow screen sharing. But on my own Rocket.Chat instance I don't.

**Comment by capensisma** [comment]
@5an1ty are you using the latest version? and do you see anything errors on the logs besides this one?

**Comment by MartinSchoeler** [comment]
Hey @5an1ty , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
