### ISSUE TITLE
Federation Dashboard hangs indefinitely

### ISSUE THREAD

**Issue by tauame** [RocketChat/Rocket.Chat#19103]
### Description:

After applying the 3.6.3 patch (which fixed Federation messages not being delivered), the "Federation Dashboard" in Admin page hangs when opened.

From what I gathered, the browser loops sending requests to the server. This happens both on Chrome and Firefox.

### Steps to reproduce:

1. Go to Admin page
2. Click on "Federation Dashboard" on the sidebar

### Expected behavior:

Federation dashboard showing up.

### Actual behavior:

The page just hangs, sending infinite requests to the server until the browser gets blocked for sending too many requests.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Firefox 78.3.0esr (32-bits) and Google Chrome 85.0.4183.83 64 bits

- Operating System: Windows 10 OS Version 1903 (Build 18362.959)

### Additional context

This only happens after applying 3.6.3 Rocket Chat patch. It was working as intended before that.

### Relevant logs:

![image](https://user-images.githubusercontent.com/1528610/94606967-a48a0200-0271-11eb-9069-bb9a6be8529c.png)

_Originally posted by @tauame in https://github.com/RocketChat/Rocket.Chat/issues/18432#issuecomment-700938972_

**Comment by ankar84** [comment]
Confirm that bug

**Comment by binboum** [comment]
#19007

**Comment by sampaiodiego** [comment]
thanks guys, I'll close this one as duplicated of https://github.com/RocketChat/Rocket.Chat/issues/19007 since the other has more attraction and info already.
