### ISSUE TITLE
REST API Upload Methods

### ISSUE THREAD

**Issue by EvilCode01** [RocketChat/Rocket.Chat#19119]
### Steps to reproduce:

1.  Upload the image via the chat interface
2.  Upload the same image via the API
3.  ...

### Expected behavior:
Same width and height

### Actual behavior:
api confuses width with height or vice versa

### Server Setup Information:

- Version of Rocket.Chat Server:  3.7.0-develop
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.3
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Linux

### Additional context
<img width="425" alt="Снимок экрана 2020-10-03 в 20 41 59" src="https://user-images.githubusercontent.com/53563024/94998584-77b05480-05bb-11eb-84b5-340087617b3a.png">

**Comment by Tanu1201** [comment]
@dougfabris 
I try to reproduce this bug, tried to upload image from interface from here 
![image](https://github.com/user-attachments/assets/6ed3f2b0-7003-4aa8-bc00-07e8449e414b)

Width: 663 Height: 830

and if I uploaded from api width and height is same 
Width: 663 Height: 830

so any specific step I am missing?

**Comment by reetp** [comment]
> @dougfabris I try to reproduce this bug, tried to upload image from interface from here 

Please do not @ people - it is not necessary. It may be the wrong person, and it gets very annoying. 

Just post a comment and leave it there. Thanks.

Note this issue is 4 years old and Rocket.Chat has changed massively.


> Width: 663 Height: 830

> and if I uploaded from api width and height is same
> Width: 663 Height: 830

Looks fixed. Closing.
