### ISSUE TITLE
User is unknown or wrong password ...to many requests ....shall i continue?

### ISSUE THREAD

**Issue by ostapski** [RocketChat/Rocket.Chat#19123]
Crap ..crap crap and crap again ...
Installed it year ago ...deleted ...
Tried again ...this is even worse than year ago ...
Is someone in your team specifically destroying this project ? - it seems like that 
coz the more you work on this project - the less stable it gets 

if year ago only few parts were not working 
now its infected with bugs ...login - fail 
change avatar - user not found
upload fail - user not found
update account - fail ...- too many requests
change password - user not found

rebooting server ...
ahahahah ... everyone is screwed ... no updates .in chanels
everyone has to reboot their application to get it fixed ..

CRAP CRAP CRAP ...and once more - CRAP !!!!
amateurs  !!!!

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by crowzer0** [comment]
Very constructive contribution :-(. 
But at least the issue template is used.

**Comment by Alexdc-12** [comment]
Should try reading the manual...

**Comment by MartinSchoeler** [comment]
Closing this as it does not follow our guidelines...
