### ISSUE TITLE
enabling of LDAP authentification results in locking out the local admin

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1912]
When LDAP is activated, a user has only left the oppertunity to log in using LDAP authentification. But for that there only exists one firstly created local admin, it seems to be impossible for the (only) admin to log in again, since the moment the ldap auth had been enabled. So the admin seemed to be locked out.

**Comment by 5an1ty** [comment]
+1, LDAP should not be exclusive.

**Comment by tuudik** [comment]
:+1:

Fortunately, before I logged out with my admin user, I let other user log in using LDAP and made him admin.

**Comment by finius** [comment]
ok, nice workaround for the moment - I'll give it it try!

But in general this behaviour should IMHO be fixed and hardened soon.

**Comment by tuudik** [comment]
Or, if it would be possible to login in using LDAP user with same username or e-mail.
Or, if you could define right after configuring LDAP, who will be the admin.

**Comment by finius** [comment]
Yeah. Indeed, I would prefer the 2nd suggestion

**Comment by bsdcon** [comment]
See also #1900 -- if you prefer to have a local admin account that will keep working even after LDAP is enabled.

**Comment by finius** [comment]
That would also be a solution. It's the way "ownCloud" deals with this issue.

**Comment by engelgabriel** [comment]
LDAP now uses regular accounts as fallback by default, but you can also turn this off on the admin panel.
