### ISSUE TITLE
no settings for SMTP sendings without authentification possible

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1913]
The admin Interface has no option to choose a smtp configuration that requires no authentification. 
Furthermore it should exist a field to enter a dedicated reciepient of a test mail, to also enable test sendings to non-RC-users or external email adresses, insted of sending testmail to all users.

**Comment by tuudik** [comment]
Seems to be fixed in: https://github.com/RocketChat/Rocket.Chat/issues/1883

But regarding send test mail to non-RC user :+1:
