### ISSUE TITLE
Add back to top feature in Readme.md

### ISSUE THREAD

**Issue by Alphasaurs** [RocketChat/Rocket.Chat#19158]
### Description:

Add back to top feature and update structure in Readme.md.

### Steps to reproduce:

1. Go to [Rocket.Chat GitHub repo](https://github.com/RocketChat/Rocket.Chat)

2. Scroll through the readme.md

### Expected behavior:

Should have back to top feature

### Actual behavior:

Just scroll 

### Server Setup Information:

1. Version of Rocket.Chat Server: N/A
2. Operating System: N/A
3. Deployment Method: Layershift
4. Number of Running Instances: N/A
5. DB Replicaset Oplog: N/A
6. NodeJS Version: N/A
7. MongoDB Version: N/A

### Client Setup Information

1. Desktop App or Browser Version: Firefox 
2. Operating System: Win 10

### Additional context

N/A

### Relevant logs:

N/A

**Comment by ankar84** [comment]
It could be for docs repo https://github.com/RocketChat/docs/issues

**Comment by frdmn** [comment]
Not sure if I understood correctly, but if you are speaking of browsing through _this_ repositories [`README.md`](https://github.com/RocketChat/Rocket.Chat/blob/develop/README.md) through GitHub then you can just hit TAB to display a "Skip to content" accessibility button on the very top left. This also makes the whole page to scroll to the top:

![](http://up.frd.mn/Sj3f7b.gif)

**Comment by Alphasaurs** [comment]
I have implemented direct redirection to table of content as when understanding readme.md it becomes handy to direct access rather than skip to content, as shown below:

![Untitled Project](https://user-images.githubusercontent.com/50196057/95471732-dd2b8900-099f-11eb-885a-f615538e5bcb.gif)

#19159
