### ISSUE TITLE
no SMTP setting available to send test emails to any reciepient (also non-RC users)

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1915]
It should exist a field to enter a dedicated reciepient for test emails, to also enable test mailings to non-RC-users or external email adresses, insted of sending testmails to all users.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
