### ISSUE TITLE
oplog bug:Error in oplog callback TypeError: Cannot read property 'u' of undefined

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#19155]
### Description:

Error in oplog callback TypeError: Cannot read property 'u' of undefined

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

no this bug

### Actual behavior:

we will get this bug from log sometimes.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: ubuntu
- Deployment Method:docker 
- Number of Running Instances: 18
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.*
- MongoDB Version:4.*

### Client Setup Information

- Desktop App or Browser Version:chrome  83
- Operating System: wiindows 10

**Comment by dougfabris** [comment]
@564064202 Thanks for opening an issue. Unfortunately, the information you provided it's not enough to found what's happening and how to reproduce it. If you provide more info we can re-open the issue to discuss it. I recommend you to check our [contribute guide](https://docs.rocket.chat/contributors/contributing/reporting-issues) contribute guide before opening an issue next time.
