### ISSUE TITLE
PDF Files run into 403 error or just download

### ISSUE THREAD

**Issue by HueDa90** [RocketChat/Rocket.Chat#19162]
### Description:

if clicking on a pdf file, it downloads it, instead of opening

### Steps to reproduce:

1. upload pdf file in rocket chat w10 app 3.0.2
2. view the uploaded file --> 
![image](https://user-images.githubusercontent.com/55594684/95302884-cfccac80-0882-11eb-8e9f-4554c4cd93f1.png)

3. click on the file
4. chrome wants to download it
5. paste manual link 
6. wants to download aswell, not showing it

### Expected behavior:

1. pdf should be in rocket chat in mini format
2. pdf should be shown after click, not downloaded

### Actual behavior:

pdf wants to download
![image](https://user-images.githubusercontent.com/55594684/95303177-2b973580-0883-11eb-9963-82468307b44b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Linux
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Desktop APP 3.0.2
- Operating System: W10 Prof 64bit

**Comment by ankar84** [comment]
Update to RC server version 3.6.3 where that bug fixed

**Comment by HueDa90** [comment]
snap "rocketchat-server" has no updates available

how can i do it with snap?

**Comment by frdmn** [comment]
You need to be patient until the version got released to Snapcraft then. Should be released soon.

**Comment by MartinSchoeler** [comment]
Fixed by #18956
