### ISSUE TITLE
"Send to Channel" send automatically disables checkbox

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#19167]
### Description:

Also Send to Channel tick box in thread does not persist 

### Steps to reproduce:

Set Send to Channel globally
Administration -> Accounts -> Default User Preferences -> Show thread messages in the main thread

Set Send to Channel individually
Account -> Preferences -> Show thread messages in the main thread

Reply to create a new thread. 'Also Send to Channel' is ticked.

Close thread box.

Open Thread box.

'Also Send to Channel' not ticked.

Tick box and send and the box unchecks again.

### Expected behavior:

If the setting is enable the 'Also Send To Channel' tick box should be checked at all times unless the user deselects it.

### Actual behavior:

When you close and the reopen the thread box the 'Also Send To Channel' is not checked.

Check the box and send and it unchecks again.

It does appear that messages are sent to the thread.

However, this is confusing a lot of users.

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat - probably 3.7.x or 3.8.dev + tested on 3.5.4 
- Operating System: Yours
- Deployment Method: unknown
- Number of Running Instances: multiple 
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: Chromium
- Operating System: Xubuntu 18.04

### Additional context

None

### Relevant logs:

None

Probably related:

https://github.com/RocketChat/Rocket.Chat/issues/18347
https://github.com/RocketChat/Rocket.Chat/pull/17416

**Comment by immaro** [comment]
Same here (v 3.7.1).

Reverse case is also "valid" :
1. Unset "Send to Channel" globally;
2. Unset "Send to Channel" individually;
3. Start a new thread. The checkbox is still in place, the first message is sent to the thread anyway.

**Comment by chetas411** [comment]
@dougfabris @renatobecker  I have made a PR for this can you review it ?

**Comment by pagocs** [comment]
Same with 4.3.0

**Comment by Kyogre** [comment]
as a workaround for now we use this script: https://github.com/RocketChat/Rocket.Chat/issues/20695#issuecomment-1079636142
