### ISSUE TITLE
Last Message doesn't update in Extended View Mode

### ISSUE THREAD

**Issue by Karatemango** [RocketChat/Rocket.Chat#19175]
### Description:

In Extended View, the last message of the chat/channel doesn't get updated. The Time of the last message does however get updated. A reload of the webpage doesn't update it either.

### Steps to reproduce:

Enable Extended View, which can be found after clicking the "Sort-Symbol".
Afterwards this bug can be checked by messaging yourself.
Happens in any kind of chat.

### Expected behavior:

Below each Channel/Group/Person it should show the last messagetext, which should update almost immediately.

### Actual behavior:

 It's stuck on the last message after I enabled Extended View.
In my case one message was from the day before.
Doesn't fix itself after multiple days days.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- OS: Ubuntu 16.04 LTS
- Deployment Method: snap

### Client Setup Information

- Desktop App or Browser Version: Any Browser (Chrome and Firefox tested), No App tested

**Comment by hugocostadev** [comment]
Hi there!

Sorry, this error does not happen on the latest releases.

[Rocket.Chat](https://rocket.chat/) provides support for 6 months to the latest releases of each major version.

I would suggest you update your [Rocket.Chat](https://rocket.chat/) version to the latest stable version, which you can find it here: [https://github.com/RocketChat/Rocket.Chat/releases](https://github.com/RocketChat/Rocket.Chat/releases)

For more information about your support: [https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions](https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions)
