### ISSUE TITLE
Grey-out messages for up to 30 seconds without high system load

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19173]
### Description:

On a regular basis I have an issue with messages a grey-out for some time.
That's really bad for user experience. Users complaining that Rocket Chat is freezing, or stuck of holded.
In Grafana I see, that **afterSaveMessage** and **beforeSaveMessage** hooks take too much time.
Whole Rocket Chat system with a very low load in that moment.

How can I avoid that? How can I fix that? What could cause that?

### Steps to reproduce:

1. Write a message or a few messages
2. That messages are grey-out for a second or so

### Expected behavior:

Messages should be sent immediately without high load

### Actual behavior:

Here is an example of messages are grey-out for a second or so
![freeze](https://user-images.githubusercontent.com/4023037/95417292-5c3ba580-093d-11eb-92d6-8d61d0736a3e.gif)

Here is a Hooks Total Times graph - afterSaveMessage and beforeSaveMessage take too long time, I guess
![image](https://user-images.githubusercontent.com/4023037/95417123-e8999880-093c-11eb-8ff6-9ea92cea25e8.png)

Network, CPU and Memory in time of tests
![image](https://user-images.githubusercontent.com/4023037/95417680-4ed2eb00-093e-11eb-8ac6-6c6d3379ccae.png)

MongoDB graphs in test time
![image](https://user-images.githubusercontent.com/4023037/95417739-6c07b980-093e-11eb-80f4-58c5f74039c6.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 3.0.2 and Chrome 85
- Operating System: Windows 10

### Additional context

No

### Relevant logs:

No logs for that

**Comment by ankar84** [comment]
Today is much better
![image](https://user-images.githubusercontent.com/4023037/95699415-09b7fd00-0c4d-11eb-878c-f113ff106c77.png)
But why? What affect this hooks?

**Comment by sampaiodiego** [comment]
that's odd. so, `afterSaveMessage` should not be the cause of the delay you're seeing since it runs asynchronously **after** the message is saved on db.. lots of things runs on this hook, like federation, email and push notifications, read receipts, webhooks and so on.

`beforeSaveMessage` in the other hand could cause a delay, but looks like it was much faster than the delay you were actually seeing.

how often that happens? did you change anything on the system when that started to happen? is it possible that the client connection was bad (high latency, low bandwidth)?

**Comment by ankar84** [comment]
Hi, @sampaiodiego  and thanks for a fast reply!

> `afterSaveMessage` should not be the cause of the delay you're seeing since it runs asynchronously **after** the message is saved on db.. lots of things runs on this hook, like federation, email and push notifications, read receipts, webhooks and so on.

Ok, thanks for information, will know that from now on.

> `beforeSaveMessage` in the other hand could cause a delay, but looks like it was much faster than the delay you were actually seeing.

Yeap. I'm not actually sure, that one of that hooks or both are the cause fro that issue, I just saw they have pretty big time of executing.

> how often that happens?

This is a most strange thing. I experienced that at my morning with a very low load on APPs and DBs servers. Most of the time, there is no that delay on message appearing, even on a normal daily load (about 30-35% CPU for APP servers and 10-15% CPU for DB server). Sometimes that happens at day time, but not so often. 

> did you change anything on the system when that started to happen?

Actually, not think so. Two weeks ago we upgraded to 3.6.3, but I think I saw that before on 3.1.1

> is it possible that the client connection was bad (high latency, low bandwidth)?

Definitely not - powerful PC with 1Gb to LAN and Rocket Chat in that LAN too (in different network segment obviously, but still same Intranet). I will add a ping to server result in a near future (when I will on my work)

And my goal with that issue was to get what's going on. What else could cause such delay? What else graph you interested to see in that perspective? (I could give you all from [RC.Mertics](https://github.com/RocketChat/Rocket.Chat.Metrics)) What server or user settings could affect that behavior ?

**Comment by ankar84** [comment]
Actually we are now on 3.7.1 and set log level to errors only and I didn't see that delay nor `afterSaveMessage` and `beforeSaveMessage` hooks in top in any graph, so I'm closing that issue.

**Comment by sampaiodiego** [comment]
that's good to know @ankar84 .. thank you

**Comment by ankar84** [comment]
@sampaiodiego I must reopen that issue, because lot of users comply that messages appears grey for up to 30 seconds.
But afterSaveMessage and beforeSaveMessage on average values.
We need to find the root cause for that situation.
![image](https://user-images.githubusercontent.com/4023037/105807774-ae213d80-5fb7-11eb-9555-bf78d23b180c.png)

**Comment by ankar84** [comment]
Here is a graph in a normal daily load
![image](https://user-images.githubusercontent.com/4023037/105834380-74622e00-5fdb-11eb-9cd4-8f9375ad19e0.png)
That grey-out messages issue experiencing not all users. 
For example, my messages becomes bold in moments (sometimes a second or two, but rarely)
But some users (mostly same users) see that issue very often.
We have 30 instances and HAProxy in front of them.
Maybe users with problem are connected to same buggy instance.
But how can I see it? All instances looks good and pretty same:
![image](https://user-images.githubusercontent.com/4023037/105837488-d02eb600-5fdf-11eb-8309-5622f2c16800.png)

**Comment by ankar84** [comment]
Moment ago I saw about 5-6 seconds grey-out message with this metrics
![image](https://user-images.githubusercontent.com/4023037/105935716-85568200-6063-11eb-8067-e3217108829e.png)
So, I believe it's not representative and wee need to find one.

**Comment by emikolajczak** [comment]
Hi, how looks your Oplog Queue during greyed out messages?

**Comment by ankar84** [comment]
> Hi, how looks your Oplog Queue during greyed out messages?

Here is Oplog for 6 hours. Now all looks good and I don't get grey-out messages, but Oplog usage much intensive.
![image](https://user-images.githubusercontent.com/4023037/105956036-3b33c780-6088-11eb-96eb-8889e6b23e80.png)

And here the same hour when I got 5 sec grey-ot message
![image](https://user-images.githubusercontent.com/4023037/105956140-69b1a280-6088-11eb-941d-884fa10baac9.png)

**Comment by emikolajczak** [comment]
Oplog Queue you can find in Rocket.Chat Metrics dashboard below Oplog graph
![image](https://user-images.githubusercontent.com/50440047/105956505-349d5400-6078-11eb-8c7b-35d31c577b44.png)

**Comment by ankar84** [comment]
> Oplog Queue you can find in Rocket.Chat Metrics dashboard below Oplog graph

Unfortunately I don't have that Oplog Queue graph in Rocket.Chat Metrics 
May be because of our RC version (3.7.1) or may be I deleted it long time ago, IDK

**Comment by emikolajczak** [comment]
This graph exists from begin (I started on vesrion 3.0.12). In past i have observed corelation greyed out messages and long oplog queues. I think you can easily add it

![image](https://user-images.githubusercontent.com/50440047/105958750-53e9b080-607b-11eb-9fad-e1db4b71caac.png)

**Comment by ankar84** [comment]
> This graph exists from begin (I started on vesrion 3.0.12). In past i have observed corelation greyed out messages and long oplog queues. I think you can easily add it

Thanks for idea!
I just imported new dashboard from https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Metrics/master/config/grafana/provisioning/dashboards/json-exports/rocketchat-metrics.json

But anyway, I think queue is always 0 for us now.
Even on LDAP sync
![Uploading image.png…]()

**Comment by ankar84** [comment]
> This graph exists from begin (I started on vesrion 3.0.12). In past i have observed corelation greyed out messages and long oplog queues. I think you can easily add it

I think we always have 0 there for all instances
![image](https://user-images.githubusercontent.com/4023037/106097243-08e99f00-6148-11eb-8e06-9081f4ee2dfa.png)
![image](https://user-images.githubusercontent.com/4023037/106097268-16068e00-6148-11eb-95af-2d0c6784eb19.png)
![image](https://user-images.githubusercontent.com/4023037/106097297-2159b980-6148-11eb-98ad-5ebf84d23b5e.png)

**Comment by ankar84** [comment]
Saw discussions by @ggazzo and @rodrigok about that issue [here](https://youtu.be/D7ah1icux7E)
I think we are using `change streams` as Oplog alternative, because we are on WiredTiger database engine.
But still, what metric we need to monitor to get this grey-out messages issue?

@emikolajczak Oplog queue for us always 0, I did not saw it more then that.

And last week a this week is more good in gray-out messages topic. I didn't saw large delays and users to spot comply about that.

**Comment by ankar84** [comment]
Now I see opposite situation - beforeSaveMessage is about 1.5 sec, but my messages are received fast (appears black in chat history fast)
![image](https://user-images.githubusercontent.com/4023037/106844842-b0bc1b00-66ba-11eb-8b01-e965046c1328.png)

**Comment by ankar84** [comment]
Now I think it's could be a `MongoDB page faults` metric - it is pretty much corelated to grey-out messages
![image](https://user-images.githubusercontent.com/4023037/107019190-6f0e9b80-67b2-11eb-8f49-07bdcbbadf51.png)
I see on graphs that peaks appears almost every hour (starts couple of minutes before 9.00, 10.00m 11.00 and so on)
May be some cron job can do that load?
I see that `Remove users from Token Channels` launches every hour, but accurate at hour starts (9.00, 10.00 and so on)
@emikolajczak can you take a look at that metric - does it correlates to gray-out messages in your deployment?
Now we plan to add more RAM to MongoDB servers and take a look for a while.

**Comment by emikolajczak** [comment]
We have this problems in past. In our environment problem was high disk I/O waits values on MongoDB. Solution was add fast disks and increase CPU.

**Comment by ankar84** [comment]
[That great advices](https://github.com/RocketChat/Rocket.Chat/issues/21182#issuecomment-821142212) by @geekgonecrazy lead me to idea that we need more RAM to our mongodb server and we added it. And that grey-out messages now in past!

I think that **grey-out messages** problem pretty correlates with `mongodb:page faults` metric
Here is a graph of that metric before and after we added more RAM to db servers
![image](https://user-images.githubusercontent.com/4023037/116393444-4d113c00-a82a-11eb-8431-3c6ebef40fa3.png)

So, I'm closing that issue.

And I think, that some of Aaron's advices about db servers sizing can be added as recommendations to official documentation to avoid problems like this.

**Comment by geekgonecrazy** [comment]
I'm glad this helped!  Yeah I think page faults is a sign that what I'd call cache churn is happening in mongo. 

I'd be curious how you approached increasing memory.  Did any of the sizing estimations help?  Also if you can what did you change from and too.  Just to get an idea. Kind of need a case like this to help build a doc.  🙏

**Comment by ankar84** [comment]
> I'd be curious how you approached increasing memory. Did any of the sizing estimations help? Also if you can what did you change from and too. Just to get an idea. Kind of need a case like this to help build a doc.

Sure!

We had 16Gb of RAM on both DB servers (we have PSA architecture) and now we have 64Gb RAM each.
Here is our sizes:
```
rs0:PRIMARY> db.stats(1024*1024)
{
        "db" : "rocketchat",
        "collections" : 69,
        "views" : 1,
        "objects" : 159631159,
        "avgObjSize" : 189.83344150874706,
        "dataSize" : 28899.50970172882,
        "storageSize" : 14936.87890625,
        "numExtents" : 0,
        "indexes" : 326,
        "indexSize" : 14398.37109375,
        "fsUsedSize" : 39293.7578125,
        "fsTotalSize" : 151034,
        "ok" : 1,
        "operationTime" : Timestamp(1618636447, 4),
        "$clusterTime" : {
                "clusterTime" : Timestamp(1618636447, 4),
                "signature" : {
                        "hash" : BinData(0,"Dm/4kdgZPitg2TaVZJRkxnvn818="),
                        "keyId" : NumberLong("6920770581193293826")
                }
        }
}
```
So, 14Gb only for indexes! So, I guess 16Gb of total RAM it's a really not enough for normal operations.
We increased to 64Gb of RAM because [mongodb will use half of RAM minus 1Gb](https://docs.mongodb.com/v4.0/reference/configuration-options/#storage.wiredTiger.engineConfig.cacheSizeGB).
