### ISSUE TITLE
[BUG] Admin can change the username, email and even password of an existing user.

### ISSUE THREAD

**Issue by aradhya-gupta** [RocketChat/Rocket.Chat#19178]
### Description:
The admin has the power to modify a participants username, email, password etc. when the admin should only have the power to assign a role to a person or remove/delete his account under necessary circumstances.

### Steps to reproduce:

1. Go to Administration panel > Users
2. Select an existing user.
3.  Click on the Edit button and you can edit all the details of the user without the permission of that user.

### Expected behavior:
The Admin should only be able to assign a role/ deactivate/delete a user.

### Actual behavior:
The Admin can change even the username and password of an existing user!

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: WSL2 Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by MartinSchoeler** [comment]
Hello, this is not a bug and this behavior is defined by the `edit-other-user-info` permission. For more info please check our [documentation on permissions](https://docs.rocket.chat/guides/administrator-guides/permissions). Thanks
