### ISSUE TITLE
oembed metadata request User-Agent should specify a Rocket.Chat identifier

### ISSUE THREAD

**Issue by gabek** [RocketChat/Rocket.Chat#19188]
### Description:

When URLs are sent in Rocket.Chat the oembed request uses a spoofed User-Agent.  This value is configurable in the Admin settings, but the default should be tweaked to specify it's coming from Rocket.Chat.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: the one in docker
- MongoDB Version: 4.x

### Steps to reproduce:

1. Send a message with a URL in it.
2. Rocket.Chat makes a request to that URL with the default setting of User-Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36`.

### Expected behavior:

The default setting should allow this request to be made with a User-Agent that specifies that it is Rocket.Chat making the request.

### Actual behavior:

Due to the spoofed User-Agent the destination web server is unable to know that this is Rocket.Chat making the request, and cannot determine it should be treated as a bot.

### Server Setup Information

This is a hosted install.

**Comment by geekgonecrazy** [comment]
@sampaiodiego how do we make the pesky bot leave the issue open?  In this case if it’s hosted they don’t necessarily know the details.

**Comment by geekgonecrazy** [comment]
There.. gotta say not a fan that it wouldn’t let me reopen

**Comment by sampaiodiego** [comment]
`<offtopic>`

> @sampaiodiego how do we make the pesky bot leave the issue open? In this case if it’s hosted they don’t necessarily know the details.

only the server version is required (hopefully this will help https://github.com/RocketChat/Rocket.Chat/pull/19078 )


> There.. gotta say not a fan that it wouldn’t let me reopen

the only current way to let it open is if the issue has all the required info. we can add some maintainers to the config file that would skip it though.

`</offtopic>`

talking about the issue itself, we used that user-agent because some websites don't send proper HTML to scrap when using "non-browser" user-agent (like Twitter for example).. but maybe we can append some rocket.chat info to the user agent? 🤔  need to test how to still make it valid though

**Comment by Abhirup-99** [comment]
@sampaiodiego I would like to work on this issue.

**Comment by tyz98** [comment]
How can I check the header of the request that Rocket.Chat makes to that URL? It cannot be seen in browser.

**Comment by sampaiodiego** [comment]
> @sampaiodiego How can I check the header of the request that Rocket.Chat makes to that URL? It cannot be seen in browser.

oembed requests are done server side.

**Comment by iraj465** [comment]
@sampaiodiego How I can see the oembed request log on the server side? Is there any Meteor logger or equivalent to check the headers for this request?

**Comment by sampaiodiego** [comment]
these are the request
https://github.com/RocketChat/Rocket.Chat/blob/791002413f803765d4d6a8613b18ee0bc9d373a3/app/oembed/server/server.js#L98

**Comment by iraj465** [comment]
@sampaiodiego I was thinking of adding a separate setting for User Agent header that also takes into account the RocketChat version, say something like API_Embed_Rocket_UserAgent and not mess up the default API_Embed_UserAgent , but adding a separate setting in the admin settings is a big change. Can you please suggest some workaround?

**Comment by sampaiodiego** [comment]
@iraj465 I'm sorry I didn't get why you create an additional setting? isn't there a way to append the rocket.chat version info one the current one?
