### ISSUE TITLE
Tip: Change the design Rocket.Chat with Material-Admin

### ISSUE THREAD

**Issue by LeonardOliveros** [RocketChat/Rocket.Chat#1918]
[material.zip](https://github.com/RocketChat/Rocket.Chat/files/90722/material.zip)

Want to work with the template material-Admin for Rocket.Chat, I think a very cool template for implementation in the Rocket.Chat

![captura de pantalla de 2016-01-14 12 51 00](https://cloud.githubusercontent.com/assets/6960313/12331745/2bc9306c-babd-11e5-9501-03943fa2ce84.png)

**Comment by engelgabriel** [comment]
Hi, thanks for the interest.

For performance/theming/technical reasons, we don't use templates on Rocket.Chat

You can make changes to our design to make it more material like, but we won't add a full template lib itself.

I like the material design, and we will probably move a few things in that direction, but going to do our own implementation (inspired by templates anyway).

**Comment by MartinSchoeler** [comment]
I will close this since we are already doing a redesign on rocket.chat
