### ISSUE TITLE
Omnichannel Analytics: filter with custom dates / invalid_dates in pt-BR

### ISSUE THREAD

**Issue by cbridi** [RocketChat/Rocket.Chat#19187]
### Description:

When the administrator or livechat manager chooses custom dates, it seems to be in a wrong date format, because it changes day and month.

### Steps to reproduce:

As administrator or livechat manager
1. Go to 'My Account / Preferences / Localization / Language' choose Português do Brasil
2. Go to 'Omnichannel / Analytics' 

### Expected behavior:

Filter Analytics with custom dates

### Actual behavior:

![Peek 08-10-2020 15-49](https://user-images.githubusercontent.com/988755/95518725-09dca200-099a-11eb-86bb-a39faae25fa5.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.5

### Client Setup Information

- Desktop App or Browser Version: Firefox 81.0
- Operating System: Linux Mint 20

**Comment by MartinSchoeler** [comment]
Hey @cbridi we just finished a big refactor on the omnichannel pages, if you update your server you will see that this issue no longer happens 🙂 Thanks!
