### ISSUE TITLE
[BUG] Bot user info is invisible

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat#19193]
### Description:

When trying to view or edit the default Rocket.Chat bot Rocket.Cat user information - getting the blank page and an error in the console. Because the bot doesn't have an email in its info.

### Steps to reproduce:

1. Go to administration
2. Click on Users
3. Click on Rocket.Cat

### Expected behavior:

Admin should be able to view or edit bot user info

### Actual behavior:

Admin is unable to view or edit bot user info and gets the blank page and an error in the console. 

![Screenshot_3](https://user-images.githubusercontent.com/58329905/95560766-6388af00-0a22-11eb-9268-a1a81a2f12c2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: Windows, Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.0
- MongoDB Version: 3.6.20

**Comment by dougfabris** [comment]
@johnypeterson Can you check if this bug persists? I'm trying to reproduce, but no error is firing in 3.7.0 version

**Comment by Darshilp326** [comment]
Not able to reproduce this issue!
