### ISSUE TITLE
[Federation] Member List is empty to federated user

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19198]
### Description:

https://github.com/RocketChat/Rocket.Chat/issues/17828 fixed but some issues is remain unfixed here. Same problem chat, same federated user can't see Member List of that chat.

@alansikora please take a look

### Steps to reproduce:

1. Add federated user to chat
2. As federated user try to open Member List
3. No users in Member List for federated user

### Expected behavior:

Member List shows all chant users

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/95584245-930dda80-0a67-11eb-89b8-9fae14132cdf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 2.17.7 and Chrome 85
- Operating System: Windows 10

### Additional context

No

### Relevant logs:

No

**Comment by g-thome** [comment]
Is this still happening in latest release?

**Comment by ankar84** [comment]
> Is this still happening in latest release?

Yes, still same
![image](https://user-images.githubusercontent.com/4023037/127101423-55c13bfe-b665-4f61-bd2f-fa5255c725f1.png)

We are on 3.16.3 now. But I don't know current version of federated server.

**Comment by ankar84** [comment]
Closing that in favor of matrix federation
