### ISSUE TITLE
How to avoid "Invalid user error"

### ISSUE THREAD

**Issue by haosdent** [RocketChat/Rocket.Chat#192]
Hello, I try to write a third part plugin like packages/rocketchat-hubot. But I meet this error when I call `Meteor.call "sendMessage"`.
```
Exception in callback of async function: Error: [methods] sendMessage -> Invalid user [invalid-user]
```
I check the code of [rocketchat-hubot](https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-hubot/hubot.coffee#L57-L61), but seem it also don't set userid. I am confuse here, how could I avoid this error. Thank you in advance.

**Comment by haosdent** [comment]
My code snippet is 
```js
		Meteor.call "sendMessage",
			u:
				username: name
			to: target
			msg: content
			rid: 'EtomNKRwxp6mELsGGLHa4ybHScj2WZoo3K'
```
I have already wrap this function by `Meteor.bindEnvironment` before.

**Comment by sampaiodiego** [comment]
maybe @Sing-Li can answer this?

**Comment by engelgabriel** [comment]
@haosdent did you create a user for Hubot? You need to register yourself as Hubot, and set the login credentials on the hubot server via environment variables.

**Comment by engelgabriel** [comment]
We need to add a default Hubot user and generate a random token, visible to the admin

**Comment by haosdent** [comment]
Thank you for your reply. @Sing-Li @engelgabriel .
In fact, I try to write a irc plugin for rocket.chat. https://github.com/haosdent/rocketchat-irc/blob/master/irc.server.coffee

And it could works although it only have the basic communicate function.

Channel message:
![_haosdentd___hadoop__153__n__hadoop_-_http___hadoop_ap](https://cloud.githubusercontent.com/assets/950759/8225675/13ec4bde-15ca-11e5-9d84-1c2cb69588ae.png)
![rocket_chat](https://cloud.githubusercontent.com/assets/950759/8225680/244e257e-15ca-11e5-8aac-318da832249f.png)

Direct message:
![_haosdentd_](https://cloud.githubusercontent.com/assets/950759/8225704/6207dafe-15ca-11e5-933e-8fc14fd75f3a.png)
![rocket_chat](https://cloud.githubusercontent.com/assets/950759/8225696/4c509e12-15ca-11e5-8f28-03e612f7c88d.png)

**Comment by haosdent** [comment]
I add a receiveMessage to Meteor.methods in server directory. But I am not sure whether it is the best way or not.

**Comment by engelgabriel** [comment]
That looks cool! Lets me try it and I'll give you some feedback. About the receiveMessage, I had a similar idea... let's talk about it after I have had read the code.

**Comment by haosdent** [comment]
Thank you for your great help.

**Comment by engelgabriel** [comment]
@haosdent do you want make a pull request with yous script? I'd be glad to accept it. We just need to turn all the configuration loaded form the DB... so we can setup using an admin interface.

**Comment by haosdent** [comment]
Sure and very gladful you want to accept it. Let me fix some minor issue of my scripts and create a merge request.

**Comment by Sing-Li** [comment]
Cool!  Now we can 'bridge in' mainstream OSS project IRC channels :+1:

**Comment by engelgabriel** [comment]
@haosdent 

I've split the `/server/methods/sendMessage.coffee` method into the server method that can be called by the client (that has to pass all auth/permissions check) and the rest main functionality is now on a function in `/packages/rocketchat-lib/server/sendMessage.coffee`  that can only be called by server side scripts (without auth/permissions checks)

This should eliminate the need of your `/server/methods/receiveMessage.coffee`

Can you please review it? And send a PR migrating to the new method?

**Comment by haosdent** [comment]
Thank you very much! I see it, let me migrate.
