### ISSUE TITLE
Wordpress !

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1920]
Now that we have Livechat feature in beta, we are looking for community members familiar with Wordpress development and APIs to create the absolute best live chat integration plugin in the entire universe.

If you are familiar with Wordpress plugin development and have some time to help, please add a comment.

**Comment by liveitpros** [comment]
I will help... this would be a great feature.

**Comment by Sing-Li** [comment]
Something similar to this : https://en-ca.wordpress.org/plugins/zopim-live-chat/

**Comment by liveitpros** [comment]
I will come on rocket.chat Sing-Li

**Comment by Sing-Li** [comment]
Yes.  Please join us at https://demo.rocket.chat/channel/wordpress

**Comment by djsteveb** [comment]
I'd like to suggest that https://en-ca.wordpress.org/plugins/wise-chat/ the wise chat and av-chat ( https://en-ca.wordpress.org/plugins/avchat-3/  )
plugins have a very nice setup to consider integrating.
you can embed a full on chat room in a page or post - and if a web site visitor is registered and logged in via your wordpress (or better wordpress with buddypress) system - then the Auth is automatic - it can pull "real name" or "nicename", (options) - user avatar - and can even incorporate user roles - so you can have admins and moderators all synced up with the userlist in the wordpress backend.

I use the pro versions of these and would be glad to show screen shots or screen share of backend options which are very nice imho.
I think the wise chat has an option to be a sidebar kind of chatbox as well, like the zopim one you guys mentioned up thread - and that is a nice use case too.. but a good wp plugin could do so much more.

I hope this direction is interesting to the group, I would like to support this - still learning to code though.. I can chip in money and suggestions though.

**Comment by MattWeatherford** [comment]
How would the mechanism for this work?  I have a wordpress site that is fully https://  and I have rocket chat running on another machine on my network, on Port 3000 but not encrypted.  Would the wordpress plugin put a window on a wordpress page then proxy the chat in from the service running on port 3000 on my other host?  Or is the intent to have a complete wordpress plugin that packages the entire rocket.chat app in and runs it on the same host ?

**Comment by djsteveb** [comment]
@MattWeatherford - I imagine a wordpress plugin could give you the option to embed the rocket chat into any page on your site (is suppose sidebar would be an option or minimized tab fbook like also) - but the way I use something similar is to have the chat system embedded on a page - and when user come to that page - they can choose to login using the username credentials that are stored in the wordpress site.

This is especially powerful if using a membership plugin with wordpress - as you can pull user avatars from the wp into the chat - and you can associate username in the chat with a profile in the wordpress. If using something like buddypress within wordpress, or s2 or similar - it's very nice.

the avchat wordpress plugin has a very nice set of permissions you can select in the backend that change depending on "wordpress user role" - so you can assign many options and different roles as well.

the avchat plugin is free in the wordpress plugin repo - but to get the chat to work you need the nusoft chat room system and running chat server aka media server.

I posted a video example of how some of this works here: http://globaladvancedmedia.com/team/add-chat-permissions-one/

This kind of pluging, combined with the upcoming options for guest access for the rocket chat ( https://github.com/RocketChat/Rocket.Chat/pull/5647 ) - admins could make the chat room "registered in this wordpress only" - or registered in this wordpress and you get more options, but not registered you can still enter as a guest.

I can provide advice on this and will offer some funding for the creation. I can't write the code yet - doing some classes now though!

ps - there is a plugin in the wordpress repo right now that is supposed to connect a separate rocket chat instance with wordpress somehow - but I think that just embeds the chat - it doesn't get into user authorizations, avatars, permissions, stuff like that.

**Comment by liveitpros** [comment]
Sing Li... could you contact me please

**Comment by Sing-Li** [comment]
@liveitpros is back with us now. Really looking forward to some progress.  It is really difficult to find WordPress dev pros who can also do modern JavaScript and are interested in open source.

**Comment by Suman360** [comment]
I am a student our team have developed an awesome social network using wordpress but our network is lacking a Facebook like chat system so I want to know to can I integrate rocket chat with Buddy press so it only show the online friends only online friends if I could get help regarding this we could launch the social network please help us.

**Comment by Suman360** [comment]
My email is wrightabd@gmail.com please reply here

**Comment by wandersonmaceds** [comment]
Hi! I'm from Brazil, my english isn't so good, but...
The idea of a WordPress plugin sounds great! Have you found someone who can do it?

**Comment by beatelite** [comment]
I know this is built in Meteor but I work in Angular and JS as well as PHP and have been following the progress on this and the multiple instances feature for some time. Maybe I can help out somehow. The rocketchat channel for wp seems to be down https://demo.rocket.chat/channel/wordpress

Who's the lead on this and where is it right now?

**Comment by devhaoy** [comment]
Hi, do we have any solution / tuto to use rocket chat on a wordpress website?

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by laet4x** [comment]
Can we help for Rocket Chat Wordpress Development?

**Comment by ArjonBu** [comment]
Is this issue going anywhere? There are a lot of interested people willing to work on this.
