### ISSUE TITLE
Wrong user status in sidebar

### ISSUE THREAD

**Issue by mr-dandy** [RocketChat/Rocket.Chat#19209]
### Description:

When someone becomes online/away/offline their status is not changed until you refresh a webpage or reopen the application. Also, user status is incorrect in sidebar and at the top of the dialogue when you chat for a while (and the user is still online, typing back and replying, but is showing as _away_). But if you click on user's info, the status on sidebar on right side is showing correctly.

<img width="1438" alt="wrong_status" src="https://user-images.githubusercontent.com/26023557/95663187-bc049d00-0b45-11eb-9ca2-459dbfc58440.png">

P. S. There is a forum thread with the same issue, but in our case the field "uids" in rooms is present:

https://forums.rocket.chat/t/wrong-user-status-in-sidebar/8616

### Steps to reproduce:

1. Set up Rocket.Chat 3.7.0
2. Import/sync users from AD/LDAP.
3. Start messaging with someone for a while and watch for their status **or** start a dialogue with someone, they become away or offline, but the status does not.

### Expected behavior:

User status is showed correctly.

### Actual behavior:

User status is showed incorrectly.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: CentOS Linux release 7.5.1804 (Core)
- Deployment Method: manual installation
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled, 3 replica set members
- NodeJS Version: v12.18.4
- MongoDB Version: v4.0.19

### Client Setup Information

- Desktop App or Browser Version: Firefox 81, Google Chrome 86; but happens on latest desktop version as well
- Operating System: macOS Catalina 10.15.7, Ubuntu 18.04/20.04, Windows 10 2004

### Relevant logs:

No relevant logs produced.

**Comment by ankitpal1029** [comment]
Can i try working on this? I am new to open source and i am familiar with reactjs

**Comment by foss-** [comment]
Seeing the same problem. users have to actively switch back to online when presence is automatically set to `away` after set time. This regression seems to have been introduced with 3.7.0.

**Comment by ankar84** [comment]
@ggazzo @MartinSchoeler @gabriellsh 
That issue still persist on open.rocket.chat on a 3.8.0-rc.9
![image](https://user-images.githubusercontent.com/4023037/98811839-84ce2800-2432-11eb-8333-10b83c40d6be.png)
![image](https://user-images.githubusercontent.com/4023037/98811862-8ef02680-2432-11eb-9749-40e8b755966d.png)
![image](https://user-images.githubusercontent.com/4023037/98812071-e7272880-2432-11eb-9ed9-9209688b0b33.png)
Only refresh set current status in sidebar and in header.

**Comment by ankar84** [comment]
@MartinSchoeler looks like https://github.com/RocketChat/Rocket.Chat/pull/19474 totally fixed that issue in 3.0.8-rc.10
I checked all users in my sidebar and all statuses are same in sidebar and chat header.
Let's take a look for statuses for next couple days, and if all fine, we can be sure that issue is gone.

**Comment by MartinSchoeler** [comment]
@ankar84 please let me know if you see this issue again. Thanks!

**Comment by dev-manager-uk** [comment]
Does anyone have an eta for 3.0.8 please?  This bug has been going on for a while and it would be AMAZING to have reliable status for all users again!!  Thank you for all your great work :-)
