### ISSUE TITLE
Drupal !

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1921]
Now that we have Livechat feature in beta, we are looking for community members familiar with Drupal development and APIs to create the absolute best live chat integration plugin in the entire universe.

If you are familiar with Drupal plugin development and have some time to help, please add a comment.

**Comment by rjsteinert** [comment]
Hi @Sing-Li - I was thinking this would be a great combo as well. When I say integration, I mean I'm thinking being able to have a chat wigdet similar to Google Chat/IFlyChat while browsing a Drupal site. That wouldn't actually have to be Drupal specific, it could just be a JS widget you include on a page. Anyways, are you thinking other features for an integration?

**Comment by JelX7ouss** [comment]
Hey folks, I've been coding the earlier days for something similar, see [this](https://github.com/JelX7ouss/drockchat), check README for more. I will continue to make it more flexible, it still under dev and tested only on local server. Also the next days I will focus on how to build the /raspberrypi slach command, I've never used meteor before, but I guess it won't be that hard If I get a better idea on how you guys made the slach commands...

**Comment by Sing-Li** [comment]
@JelX7ouss  That is amazing work.  Yes,  slash command should be very straightforward to create.

Please come into https://demo.rocket.chat/channel/contributors  and ping one of us if you need help.  There is where we hang out most of the time while coding  :grin:

**Comment by engelgabriel** [comment]
This is very good news!

**Comment by Sing-Li** [comment]
> Custom Rocket.Chat slash command for the admin, to offer the ability to communicate 
> with a Raspberry Pi/Beaglebone (will create another separate repo for this)

This is genius!  Advancing state-of-art for IoT.    For example ..

```
/talk2pi    picbot@SingLiPi3AtHome:  snap
```
... and

*  `SingLiPi3AtHome` is resolved via federation; over connected Rocket.Chat servers - not necessarily via Internet services  (we already have a unique address for every Rocket.Chat server deployed)
*  the picbot on the pi at home, running on a Pi3,  is requested to take a picture (of my living room)
*  the picbot (hubot) then uses the camera on the Pi to capture an image and upload it 
* the preview link is sent back to the requesting Pi

Although it _**is**_ off topic (OT).

**Comment by JelX7ouss** [comment]
Thanks guys! 
Yeah @Sing-Li  good ideas! at the moment I will see how to start building the connection part with the card! I think I'll use Beaglebone and an Arduino Mega or even UNO, I'll create the repo for more code reviewing the next days.. I am currently still focusing on the Drupal part...

**Comment by thebennos** [comment]
Drupal 8 is nice, but Drupal 7 is the most used version and a D7 version would push it to more active / production installations.

**Comment by stevepurkiss** [comment]
Just noticed @jelhouss sandbox is now a full project:

https://www.drupal.org/project/rocket_chat

**Comment by jelhouss** [comment]
Yup. I made the first initial commit for the project for version 8 of Drupal. Pushed it on drupal.org and since then it seems ppl are contributing. It still has the same github repo link https://github.com/jelhouss/rocket_chat

Drupal community will make it more good I hope.
I guess Lawri on the Drupal module project made a version for Drupal 7!

**Comment by stevepurkiss** [comment]
@jelhouss awesome, thanks for your work and getting the ball rolling!

**Comment by jelhouss** [comment]
Also thanks to Angry Cactus (Drupal Startup) for pushing me to do it!

**Comment by thebennos** [comment]
And there is also a Drupal 7 version now.  Cool and thanks to Angry Cactus.

**Comment by engelgabriel** [comment]
@Sing-Li can you please add info about all this into our Docs?

**Comment by Sing-Li** [comment]
Gladly.  This is exciting development!   Thanks @jelhouss and Angry Cactus!

**Comment by Lawri-van-Buel** [comment]
Workng on Drupal 7 oAuth Login integration. I got a workign proto just finsihing up on documentation
For Rocketchat I got a [PR:6632](https://github.com/RocketChat/Rocket.Chat/pull/6632) to enable a unified expierience and make the integration easy for everyone and especially new comers to oAuth login scheme'

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas
