### ISSUE TITLE
Be Blocked when Register a new user 

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#19219]
### Description:

When We register a new user on register page or using (/api/v1/users.register) 
it will be blocked with too long time.......
![image](https://user-images.githubusercontent.com/66900278/95738932-9cdc4b80-0cbc-11eb-8846-817980276c02.png)

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: ubuntu
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.*
- MongoDB Version:4.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by codeneno** [comment]
@jwilkins @Oliver84 @geekgonecrazy

**Comment by codeneno** [comment]
@ankar84 how to resolve this bug?Be Blocked when Register a new user,

When We register a new user on register page or using (/api/v1/users.register)
it will be blocked with too long time.......

**Comment by ankar84** [comment]
> @ankar84 how to resolve this bug?Be Blocked when Register a new user,
> 
> When We register a new user on register page or using (/api/v1/users.register)
> it will be blocked with too long time.......

We don't have that bug. Almost all of our users created from LDAP Sync.
We have invited users in similar situation, but no one complain about such timeouts on register process.

**Comment by MartinSchoeler** [comment]
Please take a look at our [community support section](https://docs.rocket.chat/getting-support#community-support) as this looks more of a support request than a bug report. Thanks!
