### ISSUE TITLE
[FEATURE] Show the list of all users who have viewed your message with the time of viewing

### ISSUE THREAD

**Issue by aradhya-gupta** [RocketChat/Rocket.Chat#19217]
### Description:
Right now in Rocket.Chat we cannot see who has already read our message and thus there is uncertainity and a user has no way to be sure if his message has been read by the respective persons. Thus the user has to wait without knowing whether his message has been read or not. Introducing this feature will help the user to know if his/her message has been read by the person concerned and thus improve collaboration and convenience.

### Expected behavior:
Option to see who has read the message.

### Actual behavior:
No such option available

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
> Right now in Rocket.Chat we cannot see who has already read our message and thus there is uncertainity and a user has no way to be sure if his message has been read by the respective persons.

This is not true actually, you need to enable **Detailed Read Receipts** in **Messages** section of **Admin UI**
![image](https://user-images.githubusercontent.com/4023037/95709583-92dc2d80-0c67-11eb-8c34-515910d804e6.png)

That option do exactly what you want
![image](https://user-images.githubusercontent.com/4023037/95709605-a38ca380-0c67-11eb-8c7b-eda7fe338984.png)
