### ISSUE TITLE
Input empty on message modification

### ISSUE THREAD

**Issue by xi67** [RocketChat/Rocket.Chat#19224]
### Description:

The input does not get previous message text when you want to modify it
If you press echap the message appear.

### Steps to reproduce:

1. write a message
2. press up arrow inorder to modify it
3. the input doas not contain the message

### Expected behavior:

the input contain the message

### Actual behavior:

![image](https://user-images.githubusercontent.com/12096081/95760452-56cabc00-0cab-11eb-93bc-a0692fcfa851.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12.14.0
- MongoDB Version: 4.2.9

### Client Setup Information

- Desktop App or Browser Version: desktop app 3.0.2 or chrome 86.0.4240.75
- Operating System: Windows 10

**Comment by aKn1ghtOut** [comment]
Fixed in the latest version. Can be closed @MartinSchoeler

**Comment by MartinSchoeler** [comment]
Indeed it was fixed! Closing this. Thanks!
