### ISSUE TITLE
writing math

### ISSUE THREAD

**Issue by jotwin** [RocketChat/Rocket.Chat#1922]
First, Rocketchat is great! I'm slowly convincing my research group to use it.
It would be very useful to be able to write latex style math. Mathjax seems to be a stable solution (although I'm no expert). 
http://mathjax.readthedocs.org/en/latest/misc/mathjax-in-use.html

**Comment by eean** [comment]
You could add a new command to https://github.com/RocketChat/hubot-rocketchat

**Comment by engelgabriel** [comment]
We were looking into this yesterday... @rodrigok how much time you'd it take you to add the lib you were testing this week?

**Comment by rodrigok** [comment]
I was studying this, the better solution is https://github.com/Khan/KaTeX

**Comment by laserroger** [comment]
Is the Tex support done? I cannot use Tex with my phone.
