### ISSUE TITLE
Users are duplicating in auto completes and searches

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#19225]
### Description:

Users are autocompleting in searches twice.

### Steps to reproduce:

1. Start typing a name in search or in an autocomplete
2. See duplicated users.

### Expected behavior:

1 user, no duplicate.

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/95784936-a5fff500-0c89-11eb-957e-b754bc27f96d.png)
![image](https://user-images.githubusercontent.com/6295044/95785139-0db64000-0c8a-11eb-8821-09678bc653d4.png)
![image](https://user-images.githubusercontent.com/6295044/95785342-6dace680-0c8a-11eb-837d-f1a14960b031.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0 (2c82cd9cee8d1acf39b6cdf15de38e60965263cf)
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 4
- NodeJS Version: 	v12.14.1
- MongoDB Version: 3.6.20 mmapv1

### Client Setup Information

- Desktop App or Browser Version: 3.0.2
- Operating System: macOS & Windows

**Comment by ankar84** [comment]
Confirm search duplicate bug
![image](https://user-images.githubusercontent.com/4023037/95807954-15222b80-0d14-11eb-8843-ce01a884be21.png)

**Comment by Weuxel** [comment]
Same here.

**Comment by Gummikavalier** [comment]
I think one of them, as stated in the end of the line of hover buble on top of the name, is `suggestion from the recent messages`, and the second is a general search result. But the third, `not in channel` is shown even when the person is a already member on the channel.

**Comment by alvarow** [comment]
I see similar behavior on 3.7.1 as well... the person is in "not in channel" list even when they are.

**Comment by xbiafra** [comment]
Same issue here  - 3.7.1

**Comment by ankar84** [comment]
Some more info about that issue.
You get duplicate in search only users, that you have conversations with.
If you a search user that you have not chat before - that user appears once, no duplicate.
So, I guess - one entry is from servers search result, and one entry from local cache.
@ggazzo @tassoevan please take a look at that issue.

**Comment by tauame** [comment]
Same here (v3.7.1). Sometimes the user shows 3 or 4 times on private group mentions.
My guess for the sources of duplication would be:

- From recent messages
- From DM conversation
- From the private group user list
- From global user list

**Comment by danel1** [comment]
Same here..
- Server: v3.7.1 
- Client: v3.0.3 (Mac App Store)

**Comment by pbenkoe** [comment]
Same here.

- Server: 3.7.1
- Client: any

**Comment by hpvb** [comment]
This is still happening in 3.8.0

**Comment by Opa-** [comment]
Still happening in `3.8.1`

**Comment by JustinTimperio** [comment]
Also getting this issue in 3.8.1

**Comment by Nono-m0le** [comment]
Still happening in 3.8.2 / Client 3.0.7

**Comment by KraMorK** [comment]
server 3.8.3, still happening

**Comment by hpvb** [comment]
Still happening on 3.9.1

**Comment by amezioud** [comment]
Still happening on 3.9.3

**Additional information :**
Version du moteur d'applications | 1.21.0-alpha.4235
Mise à jour de la base de données | 212
Date de mise à jour de la base de données | 28 décembre 2020 20:44

**Comment by rustamsh** [comment]
Still happening on 3.10.0

Version	3.10.0
Apps Engine Version	1.21.0-alpha.4235
Database Migration	212

**Comment by hans4rc** [comment]
Same in 
Version 3.10.4
Apps Engine Version 1.21.0-alpha.4235
Database Migration 213

**Comment by dmitriy-olhovsky** [comment]
I confirm - we have the same problem.

Version 3.10.4
Apps Engine Version 1.21.0-alpha.4235
Database Migration 213

**Comment by fcoppolani** [comment]
Indeed, same on 3.10.4

**Comment by dusatvoj** [comment]
@MartinSchoeler any news about this issue? Some ETA / ...?
Thank's

**Comment by Nissulya** [comment]
The same problem with: 
Version: 3.9.7 (Ubuntu 18, snap installation)
Apps Engine Version: 1.21.0-alpha.4235
Database Migration: 212
Database Migration Date: February 2, 2021 2:48 PM

**Comment by dusatvoj** [comment]
@ggazzo / @MartinSchoeler / @rodrigok / @engelgabriel ... there's an assignee for almost 3 months and there's no change or reply or whatever. :confused: _(It's very annoing issue, btw)_
Is there a possibility to set a milestone or write any ETA / progress / anything else?

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/20484

the fix will be release on version 3.12.0 later this month
