### ISSUE TITLE
Probable memory leak in server

### ISSUE THREAD

**Issue by yuppox** [RocketChat/Rocket.Chat#19241]
### Description:

RocketChat server uses ever-increasing amounts of virt RAM. Res RAM seems more stable.

Over the course of ~30 days, virt RAM usage went from 6.2 GiB to 11.0 GiB.

Res RAM has gone up but it has also gone down.

### Steps to reproduce:

1. Launch RocketChat server
2. Observe RAM usage over time

### Expected behavior:

RAM usage remains within reasonable bounds.

### Actual behavior:

Virt. RAM usage steadily increases over time and never goes down.

Eventually, it will crash with an out-of-memory error.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.7
- Operating System: Debian 10.3
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.14.0 - x64
- MongoDB Version: 4.2.5
- Proxy: nginx

### Client Setup Information

N/A

### Additional context

We have a small installation with 10-20 users.

### Relevant logs:

N/A

**Comment by ankar84** [comment]
Definitely there is a memory leak
https://github.com/RocketChat/Rocket.Chat/issues/16586
https://github.com/RocketChat/Rocket.Chat/issues/13602

**Comment by yuppox** [comment]
I suppose I should upgrade to the latest version. Are there any other steps to address the issue?

**Comment by ankar84** [comment]
> I suppose I should upgrade to the latest version

That's a good idea.


> Are there any other steps to address the issue?

Weekly instances restart for now.

**Comment by yuppox** [comment]
Thanks. That's what I was thinking - restarting weekly. I'll limit restarting to RC for now and see how it goes.

**Comment by ankar84** [comment]
> That's what I was thinking - restarting weekly

In my case I do full RC restart without any downtime.
I restart every single instance one-by-one in a 5 minute period.
Users from rebooting instances are spread across other instances.
And I do it in a most low traffic time (late night)

**Comment by claures** [comment]
Hello
I think this is part of the Memory leak as well #19065

**Comment by sampaiodiego** [comment]
closing this in favor of old issues regarding the same subject, such as  #16586 #13602
