### ISSUE TITLE
Rocket Chat Website Integration

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1924]
What is the best way to integrate this great chat tool? right now i have it in frame inside the wordpress site, not sure if wordpress users would be able to login to this chat without haveing to see this screen..
![image](https://cloud.githubusercontent.com/assets/12454319/12337654/3c987260-bad9-11e5-8099-b4096470d9d5.png)

any recommendations to whats best way to add this site, without losing the top Menu ? also can we leverage the real estate on this front sign up page?

**Comment by engelgabriel** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/322

**Comment by geekgonecrazy** [comment]
Closing this issue.  We've had several conversations on the demo server 1:1 about integrating.
