### ISSUE TITLE
OAuth login fails with undefined error

### ISSUE THREAD

**Issue by firlevapz** [RocketChat/Rocket.Chat#19250]
### Description:

The OAuth2 login with nextcloud fails, probably after the last snap-upgrade. No users are able to login anymore. After clicking on "Grant access" in nextcloud it loads way longer than usual until the page returns to rocketchat. 

It's probably no nextcloud-issue because other services are still able to login via OAuth there.

### Steps to reproduce:

1. Setup OAuth login via nextcloud
2. Try to login via OAuth
3. See errors in javascript-console and logs

### Expected behavior:

User should be able to login

### Actual behavior:

User cannot login

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: default
- NodeJS Version: default
- MongoDB Version: default

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: any

### Additional context

![image](https://user-images.githubusercontent.com/12501952/96054127-45d3a380-0e81-11eb-9b85-ac2f0f0056df.png)

### Relevant logs:

Browser-Log:

```
{"isClientSafe":true,"message":"[undefined]","errorType":"Meteor.Error"}
```

Server-Log:

```
W20201015-00:58:30.609(2) (oauth_server.js:403) Error in OAuth Server: Failed to complete OAuth handshake with nextcloud at https://nextcloud-instance/index.php/apps/oauth2/api/v1/token. ESOCKETTIMEDOUT
I20201015-00:58:30.925(2) Exception while invoking method login Error: Failed to complete OAuth handshake with nextcloud at https://wir.treibhausdonaufeld.at/index.php/apps/oauth2/api/v1/token. ESOCKETTIMEDOUT     at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:134:18)     at Object.handleOauthRequest (app/custom-oauth/server/custom_oauth_server.js:191:26)     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)     at middleware (packages/oauth/oauth_server.js:170:5)     at /snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Promise.await (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

**Comment by firlevapz** [comment]
It is working now, i cannot tell what has changed, i also see the same version 3.6.2 still, but the login works now, thanks!!

**Comment by relikd** [comment]
I can tell you exactly why this happend and why it will probably happen again. Please feel free to reopen the issue if you can confirm it.

The issue is that every login attempt, successful or not, is logged as a failed login attempt in nextcloud. If you have the brute-force app enabled, it will kick in and rate-limit the login procedure. At some point it will take to long to log in and the handshake will throw the `ESOCKETTIMEDOUT`. You can verify that by looking at your nextcloud console / log. If you logout and log back in into your RocketChat instance it will print a new line

```
Login failed: 'kSkFJAkasfi...ASkjfia9a72' (Remote IP: '10.10.10.320')
```

after a few tries it will take longer to login. After a few more it will block this IP for 24 hours. If that is the case, please reopen the ticket.

One workaround is to remove the IP address from the block list:
```
sudo nextcloud.occ security:bruteforce:reset 10.10.10.320
```

You could also add the IP to the whitelist but I would not suggest doing so as it will allow any adversary to try out indefinitely many logins. Btw. the IP you are seeing is the IP of the RC server. (at least if you are running this behind a nginx proxy). The brute-force app should block external IPs instead.

Currently I dont know if this is an issue of RocketChat (mishandling the oauth connection) or nextcloud (misclassifying the login attempts). Maybe even both. Anyway, I've also posted a shorter version of the issue here https://github.com/RocketChat/Rocket.Chat/issues/18391#issuecomment-750888331

**Comment by firlevapz** [comment]
hey @relikd - thanks for your support on this issue! you are right, the nextcloud failed login attempts were the reason for this timeout problems here! 

I solved it by setting `127.0.0.1` as `trusted_proxies` in the nextcloud `config.php`, then the actual external IP of the user was properly stored in the login attempts table and the problem with the wrong login-attempts was solved!

so for me this issue is no problem anymore, although I think that there's still a bug somewhere because this oauth login fails completely when the IP is in the bruteforce login attempts table... but i cannot tell if it's on the nextcloud or the rocketchat-side

**Comment by relikd** [comment]
Hi @firlevapz sounds great, though I am not there yet. Can you help me? I already had the trusted proxies set to include localhost

```
'trusted_domains' => 
  array (
    0 => 'nextcloud.myserver.com',
    1 => 'nextcloud.myotherserver.com',
  ),
'trusted_proxies' => 
  array (
    0 => '127.0.0.1',
  ),
```

But it still logs the server ip address. Did you change anything else? Or can you post your relevant configuration? This is my nginx config 

```
server {
        server_name rcchat.myserver.com;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        
        client_max_body_size 200M;
        
        #ssl on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        location / {
            proxy_pass http://rocketchat_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Nginx-Proxy true;

            add_header Content-Security-Policy "frame-ancestors nextcloud.myserver.com";
            add_header X-Frame-Options "ALLOW-FROM https://nextcloud.myserver.com/";

            proxy_redirect off;
        }
        # certificates
    }
```

**Comment by shukon** [comment]
This is still an issue for me - setting the trusted_proxies in Nextcloud didn't work for me - is there a workaround or another issue? Otherwise I think this should be reopened.

**Comment by derspotter** [comment]
This is also happening for me. I don't see any corresponding failed login attempts.
