### ISSUE TITLE
[Bug] Custom Fields are cutoff in User Info

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19259]
### Description:

Long Custom Fields values are cut-off in full user profile (User Info)

### Steps to reproduce:

1. Setup Custom Fields
2. Fill custom field with long string
3. See that in User Info

### Expected behavior:

Custom Field Value should be full in User Info (in 2 or 3 lines if need)

### Actual behavior:
![image](https://user-images.githubusercontent.com/4023037/96105032-3d5f8500-0ee2-11eb-921f-6099b2831cf5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: 3.0.3 and Chrome 85
- Operating System: Windows 10

### Additional context

No

### Relevant logs:

No

**Comment by kraken-coder** [comment]
Hi, Can i take on this one?

**Comment by frdmn** [comment]
@kraken-coder feel free to raise a PR!

**Comment by Bestoloch** [comment]
@ankar84 Hello. Please, can you share you CustomFields config? Is it synching from AD?

**Comment by ankar84** [comment]
> @ankar84 Hello. Please, can you share you CustomFields config? Is it synching from AD?

Yeap, It's from AD.
All details can be found here https://github.com/RocketChat/Rocket.Chat/issues/18953

**Comment by Bestoloch** [comment]
> All details can be found here #18953

@ankar84 I think there are same configuration but my customFields is empty :(
* LDAP map:
{"cn":"name","mail":"email","OfficePhone":"customFields.OfficePhone","Department":"customFields.Department","Title":"customFields.Title"}

* Accounts custom fileds:
[[{"OfficePhone": "#{OfficePhone}"}, {"Department": "#{Department}"}, {"Title": "#{Title}"}]

* Accounts registration custom fields:
{
  "OfficePhone": {
    "type": "text",
    "required": true,
    "minLength": 1,
    "maxLength": 6,
    "public": true
  },
  "Title": {
    "type": "text",
    "required": true,
    "minLength": 1,
    "maxLength": 50,
    "public": true
  },
  "Department": {
    "type": "text",
    "required": true,
    "minLength": 1,
    "maxLength": 50,
    "public": true
  }
}

**Comment by ankar84** [comment]
>{"cn":"name","mail":"email","OfficePhone":"customFields.OfficePhone","Department":"customFields.Department","Title":"customFields.Title"}


Do you have `cn, mail, OfficePhone, Department, Title` in attributes of your LDAP accounts?

**Comment by Bestoloch** [comment]
> > {"cn":"name","mail":"email","OfficePhone":"customFields.OfficePhone","Department":"customFields.Department","Title":"customFields.Title"}
> 
> Do you have `cn, mail, OfficePhone, Department, Title` in attributes of your LDAP accounts?

Yes, shure. "Mail" is ok for example

**Comment by ankar84** [comment]
> "Mail" is ok for example

In that case you should see that value in email field of RC user.
Most important thing in filling RC users custom fields from LDAP users is `LDAP map`, so double check it.

**Comment by ankar84** [comment]
Still an issue in 3.10.0
![image](https://user-images.githubusercontent.com/4023037/104879554-257b1f80-596f-11eb-8518-f54c4269e359.png)
![image](https://user-images.githubusercontent.com/4023037/104879574-2ca22d80-596f-11eb-9b73-2f01e4424def.png)
And long status message is cutoff
![image](https://user-images.githubusercontent.com/4023037/104879623-43488480-596f-11eb-8701-14404180c046.png)

**Comment by ankar84** [comment]
Still an issue in 3.12.0
![image](https://user-images.githubusercontent.com/4023037/111413582-8dd84a00-86ef-11eb-9bc3-b6a7b01e29ac.png)
