### ISSUE TITLE
Livechat -  allow disabling of exit survey

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1926]
Right now, when the agent exit the room, the incoming gets a survey.   There is no current way of disabling it.

Add a setting to enable/disable this survey.

**Comment by Lochemage** [comment]
+1
Also, the survey doesn't fit in the window when your guest chat is a slide out drawer at the bottom of your website.

**Comment by marceloschmidt** [comment]
Survey is gone from livechat. We'll re-implement in the future.
