### ISSUE TITLE
LDAP-settings seem to be cached

### ISSUE THREAD

**Issue by Furragen** [RocketChat/Rocket.Chat#19270]
# Description:

When we change the ldap-host in RocketChat the settings is saved. And the new host seems to be set.
But when we look at the logs, we can see that often/random old settings are used.
Therefor users experience errors when logging in.

### Steps to reproduce:

1. Configure ldap and confirm that it works.
2. Change the ldap host to a different one.
3. Confirm that ldap still works.
4. Look at the logs of RocketChat. You should see cases where RocketChat uses the old ldap host.

### Expected behavior:

RocketChat always uses the host that is currently set.

### Actual behavior:

RocketChat randomly uses a ldap host from old settings.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.19.0
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Client 2.15.1
- Operating System: Fedora 32

### Additional context

The version/platform of the client does not matter.
Also note, how in the logs it seems like RocketChat tries to connect via normal ldap (not ldaps) to port 636. We checked that with tcpdump: it actually always used ldaps (which is correct by the config). So the logs seem to be buggy.

The connections to the ldap-server in the logs happend without us changing the setting.
The first one was correct, the second one is not correct.

### Relevant logs:
```
Okt 16 10:57:35 rocketchat-01 RocketChat[13460]: {"name":"ldapjs","component":"client","hostname":"rocketchat-01","pid":13460,"clazz":"Client","ldap_id":"198__ldap://192.168.0.10:636","level":20,"msg":"connected after 1 attempt(s)","time":"2020-10-16T08:57:35.410Z","v":0}
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: server.js:204 LDAP ➔ Connection.error connection Error: read ECONNRESET
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: at TCP.onStreamRead (internal/stream_base_commons.js:208:20)
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: errno: 'ECONNRESET',
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: code: 'ECONNRESET',
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: syscall: 'read'
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: }
Okt 16 10:58:05 rocketchat-01 RocketChat[13460]: {"name":"ldapjs","component":"client","hostname":"rocketchat-01","pid":13460,"clazz":"Client","ldap_id":"199__ldap://192.168.0.15:636","level":20,"msg":"connected after 1 attempt(s)","time":"2020-10-16T08:58:05.429Z","v":0}
```

Any help or feedback is much appreciated.

**Comment by aleadco** [comment]
A similar problem happens to us and I am going to cite it here as it may be related to this error. It is evident that when some values are modified in the LDAP configuration, everything is not updated correctly.
#19046

**Comment by Furragen** [comment]
The problem disappeared for us.
