### ISSUE TITLE
No link preview for certain HTTPS links

### ISSUE THREAD

**Issue by matthias-brun** [RocketChat/Rocket.Chat#1928]
Some https links don't generate a preview. For example the two links below:
* https://code.google.com/p/google-security-research/issues/detail?id=693
* https://www.youtube.com/user/defconswitzerland

There seems to be some logic as to which ones do work and which ones don't. For example it appears that all youtube user or channel pages do not generate a preview whereas all links to youtube videos do. Only specific pages on some websites seem to be affected. E. g. while the Google Code link above links to a specific project and doesn't generate a preview linking directly to https://code.google.com does generate a preview.

I have tested this issue with multiple users on the rocketchat instance I manage (which runs behind an Nginx reverse proxy) as well as on the public demo server and a local dev instance and got consistent results. I have also tried enabling the `Allow Invalid Self-Signed Certs` option which didn't have any effect.

Has anyone else had this issue?

**Comment by marceloschmidt** [comment]
We use the information provided on meta tags to display the relevant information from the page. If the page provides no meta, we don't generate any preview. In the case of youtube, oddly enough, youtube responds with 404, which we won't process, as it's the code for Not Found.

**Comment by marceloschmidt** [comment]
There was a slight bug with multi-line titles, which I just fixed.
