### ISSUE TITLE
one or more red notifications "invalid user" after logout

### ISSUE THREAD

**Issue by photoninger** [RocketChat/Rocket.Chat#19308]
### Description:

After clicking on logout when the login page is loaded, I get one or more red notifications on the upper right corner wiht "invalid user".

### Steps to reproduce:

1. rocket.chat web interface with browser (chrome, firefox, safari, does not matter)
2. login in
3. logout again
4. get one or more red notifications on the upper right corner wiht "invalid user [error-invalid-user]".

### Expected behavior:

after logout login page is shown without "invalid user" notifications

### Actual behavior:

after logout login page is shown with one ore more "invalid user" notifications

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Debian 9
- Deployment Method: ansible playbook
- Number of Running Instances: 2
- DB Replicaset Oplog: active
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Firefox-81, Chrome-85, Safari-14.0
- Operating System: MacOS 10.15.7

### Additional context

No difference between internal user or LDAP user.

### Relevant logs:

nginx logs some 401 after logout:
"GET /api/v1/me HTTP/2.0" 401
"GET /api/v1/users.presence?ids[]=y8huP9Y6aeb9iRbjT

and rocket.chat logs:
 RocketChat[80410]: Failed login detected - Username[unknown]

**Comment by pierreozoux** [comment]
I also get this error on 3.6.x, with the anonymous read/write feature enabled.

**Comment by damian-centrone** [comment]
This is already fixed. Tested on 3.8.0

**Comment by RedCanti** [comment]
I am going to bump this. 
I am having the same issue as described above on version 3.8.1, as well as when user tries to log out it takes a good amount of time to get login page again if ever. 

of note, anonymous read/write is not enabled. 

Version of Rocket.Chat Server: 3.8.1
Deployment Method: cloud formation (AWS)
Number of Running Instances: 1
DB Replicaset Oplog: active
NodeJS Version: v12.18.4
MongoDB Version: 3.6.8
