### ISSUE TITLE
User images in Active Directory LDAP are no longer syncing to the users in Rocket Chat

### ISSUE THREAD

**Issue by 88fingerslukee** [RocketChat/Rocket.Chat#19300]
### Description
User images in Active Directory LDAP are no longer syncing to the users in Rocket Chat. This used to work but has been slowly breaking. Not all users lost their images right away.

I have double checked that the images still exist in AD, they do.

Thoughts?

###Steps to reproduce:

Hook up AD

###Expected behavior
Images sync to users

###Actual behavior
images don't sync to users

###Server Setup Information

Version of Rocket.Chat Server: 3.6.2
Operating System: Ubuntu 18.04
Deployment Method: snap
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version: 12.16.1
MongoDB Version: 3.6.14
Proxy: apache
Firewalls involved: none

**Comment by ankar84** [comment]
We now on 3.6.3 and all avatars from AD are fine.
I suggest you to update to 3.6.3 or 3.7.1

**Comment by pierre-lehnen-rc** [comment]
Fixed by #18994 on 3.6.3

**Comment by 88fingerslukee** [comment]
Thanks! Snap hasn't updated to 3.6.3 yet so I'll wait.
