### ISSUE TITLE
Official support channel on every server - federated

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1930]
Add a federated support channel that can be enabled optionally.

Allow us to offer official support - either in the form of formal on-contract support, or informal "regular service or update announcements".

**Comment by IQ2022** [comment]
thats were premium options for the formal " on-contract support"  work :) https://github.com/RocketChat/Rocket.Chat/issues/900

**Comment by Sing-Li** [comment]
Jackpot!      

Optional **_in-app purchase_**  of Rocket.Chat server  maintenance/support contract  ;-)      

Thanks @IQ2022  -  brilliant !

**Comment by louisemessage** [comment]
Closing for now as there hasn't been activity on this issue for more than two years and we're working to clear the issue backlog.
