### ISSUE TITLE
LDAP added users from Active Directory can't login with their AD passwords

### ISSUE THREAD

**Issue by DEREKMD1992** [RocketChat/Rocket.Chat#19319]
### Description:

After I add new user in Active Directory and do a sync in RC the new user is added in RC users list but cannot log in until I manually give him a password or the user reset it from the login page.

### Steps to reproduce:

1. Create a new user in AD
2. In Administration -> LDAP -> Synchronization now
3. Try to log in using the new created user and fail to log in (until I reset password or change it manually from any admin account)

### Expected behavior:

Log in normally with the user credentials from active directory

### Actual behavior:

An error "Username and password are incorrect"

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu server 20.04
- Deployment Method: snaps
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Google Chrome  86.0.4240.75
- Operating System: Windows 10

### Relevant logs:

I20201021-17:03:52.708(3) Exception while invoking method login Error: User has no password set [403]     at handleError (packages/accounts-password/password_server.js:110:17)     at MethodInvocation.<anonymous> (packages/accounts-password/password_server.js:318:5)     at packages/accounts-base/accounts_server.js:462:31     at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at fallbackDefaultAccountSystem (app/ldap/server/loginHandler.js:34:18)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:77:10)     at packages/accounts-base/accounts_server.js:462:31     at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9

**Comment by DHCrafty** [comment]
I had the same exact issue, I had to get rid of the default channel or change code in the function `addUserToDefaultChannels`

`Meteor.runAsUser(_id, function() {
    return Meteor.call('joinDefaultChannels', options.joinDefaultChannelsSilenced);
});`

**Comment by ankar84** [comment]
Please update to 3.6.3 or 3.7.1 (better choice)
It fixed in that new versions

**Comment by DHCrafty** [comment]
It still didn't work in 3.7.1 without me disabling the default channel.

**Comment by DEREKMD1992** [comment]
> Please update to 3.6.3 or 3.7.1 (better choice)
> It fixed in that new versions

to me it says that my snap "rocketchat-server" has no updates available

**Comment by DEREKMD1992** [comment]
> I had the same exact issue, I had to get rid of the default channel or change code in the function `addUserToDefaultChannels`
> 
> `Meteor.runAsUser(_id, function() { return Meteor.call('joinDefaultChannels', options.joinDefaultChannelsSilenced); });`

I have to change this in packages/rocketchat-ldap/server/sync.js ?

**Comment by cassiojj** [comment]
Hello, in my case was resolved, uncheckeding the value **Find user after login**, in LDAP Configurations.

**Comment by DEREKMD1992** [comment]
> Please update to 3.6.3 or 3.7.1 (better choice)
> It fixed in that new versions

I have update my server to 3.7.1 and the problem was resolved

**Comment by battosai30** [comment]
@cassiojj 
> Hello, in my case was resolved, uncheckeding the value **Find user after login**, in LDAP Configurations.

Thank you very much, I spent hours finding why I got "Wrong user password" and disabling "Find user after login" made the trick. But I clearly don't know if it's a bug or not because it worked well for months before ...

**Comment by cassiojj** [comment]
> @cassiojj
> 
> > Hello, in my case was resolved, uncheckeding the value **Find user after login**, in LDAP Configurations.
> 
> Thank you very much, I spent hours finding why I got "Wrong user password" and disabling "Find user after login" made the trick. But I clearly don't know if it's a bug or not because it worked well for months before ...

Its OK
