### ISSUE TITLE
NOT a RocketChat BUG but a FEATURE REQUEST

### ISSUE THREAD

**Issue by GitHub-GLM** [RocketChat/Rocket.Chat#19315]
It would be really nice to include a STATUS schedule (I'm constantly forgetting to change status when I leave).  That way if I forget change my status from 'online' to 'away' I won't be thought of as being at work all night!
Thank you!

**Comment by damian-centrone** [comment]
hello, would you please open this request on https://github.com/RocketChat/feature-requests/issues
thanks
