### ISSUE TITLE
Update list of users in group/channel after delete users

### ISSUE THREAD

**Issue by TitovIG** [RocketChat/Rocket.Chat#19323]
### Steps to reproduce:

1. Description
2. Open group/channel
3. Open Members
4. Right esur name - 3 points, choose Delete fron channel
5. Take "Yes"

### Expected behavior:
The list is automatically updated and the member is removed

### Actual behavior:

Members not removed. If update list, membel removed.

### Server Setup Information:

- Version of Rocket.Chat Server: actual
- Operating System:  win10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
@TitovIG Thanks for reporting! It is already fixed at least from the version `3.12`
