### ISSUE TITLE
Logo of Rocket.chat is not visible in community section of readme.md on badges.

### ISSUE THREAD

**Issue by SARVESHKHANDELWAL** [RocketChat/Rocket.Chat#19332]
### Description:
**In Readme.md file there is bug in Community Section as the image/logo of Rocket.chat  is not coming there.**

### Steps to reproduce:

1.  Readme.md File.
2. Go to community Section.
3. Image on Badges of #dev and #support is not visible.

### Expected behavior:
Logo on the badges  should be there instead of no logo.

### Actual behavior:
Logo of Rocket.chat should be their on the badges of #dev and #support .

##Bug Screenshot
<img width="932" alt="3" src="https://user-images.githubusercontent.com/62640264/96876660-5b0a8c80-1496-11eb-87fb-cf1d02ef315e.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by shridharke** [comment]
I have solved the bug and opened a pull request.
#19434

**Comment by dougfabris** [comment]
Closing this one because we replace the entire readme and this issue doesn't make sense anymore. Thanks for contributing guys!
