### ISSUE TITLE
Custom Emoji can be empty

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#19343]
### Description:

When creating an custom emoji, only the name field is required. Not the emoji itself

### Steps to reproduce:

1. Set name for new emoji
2. save

### Expected behavior:

Maybe disallow empty emojis?
![image](https://user-images.githubusercontent.com/67187266/96970792-7c11c280-1514-11eb-9ae4-3c8b6de75406.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/67187266/96970749-6bf9e300-1514-11eb-8a09-7ec9dfd74af0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by feliqueres** [comment]
Hey!
Can you assign me this issue?
