### ISSUE TITLE
Messages leak to syslog

### ISSUE THREAD

**Issue by oyxnaut** [RocketChat/Rocket.Chat#19346]
### Description:

Sometimes, single messages, whole threads, or DMs end up in the syslog.

### Steps to reproduce:

I'm not sure how to reproduce this. Some messages end up logged, others don't, and I was unable to provoke logging.
The only thing all the leaked messages have in common is
```json
"msg": "Slow query"
```

### Expected behavior:

Messages aren't logged.

### Actual behavior:

Some messages end up in syslog.

### Server Setup Information:

- Version of Rocket.Chat Server: rocketchat/rocket.chat:3.7.1@sha256:158f25a09c5382d6461bdbf26e895e5416b3ba01a041ef051d744c765649b0fa
- Operating System: Ubuntu 18.04 host for dockerd
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: mongo:4.4.1@sha256:31f6433f7cfcd2180483e40728cbf97142df1e85de36d80d75c93e5e7fe10405

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

```json
{                                              
  "t": {    
    "$date": "2020-10-23T08:51:45.597+00:00"
  },                    
  "s": "I",
  "c": "COMMAND",
  "id": 51803,        
  "ctx": "conn272",
  "msg": "Slow query",
  "attr": {                                              
    "type": "command",
    "ns": "rocketchat.rocketchat_message",
    "command": {       
      "insert": "rocketchat_message",
      "documents": [     
        {                   
          "_id": "AihSJ9aa3PPsrh4tg",
          "rid": "kwA59bsZB9HEjFiDt",
          "msg": "sometimes the chat leaks messages to syslog :(",                                                  
          "ts": {           
            "$date": "2020-10-23T08:51:44.648Z"
          },
          "u": {    
            "_id": "eL9Yaoe7S4GBNraG3",
            "username": "oxynaut",
            "name": "oxynaut"
          },
          "_updatedAt": {
            "$date": "2020-10-23T08:51:45.213Z"
          },       
          "mentions": [],
          "channels": []
        }                         
      ],                 
      "ordered": true,
      "lsid": {
        "id": {
          "$uuid": "4c9485f5-48d8-443f-8f92-26bcf1019b41"
        }
      },
      "$clusterTime": {
        "clusterTime": {
          "$timestamp": {
            "t": 1603443104,
            "i": 1
          }
        },
        "signature": {
          "hash": {
            "$binary": {
              "base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=",
              "subType": "0"
            }
          },
          "keyId": 0
        }
      },
      "$db": "rocketchat"
    },
    "ninserted": 1,
    "keysInserted": 66,
    "numYields": 0,
    "reslen": 230,
    "locks": {
      "ParallelBatchWriterMode": {
        "acquireCount": {
          "r": 1
        }
      },
      "ReplicationStateTransition": {
        "acquireCount": {
          "w": 1
        }
      },
      "Global": {
        "acquireCount": {
          "w": 1
        }
      },
      "Database": {
        "acquireCount": {
          "w": 1
        }
      },
      "Collection": {
        "acquireCount": {
          "w": 1
        }
      },
      "Mutex": {
        "acquireCount": {
          "r": 1
        }
      }
    },
    "flowControl": {
      "acquireCount": 1
    },
    "storage": {
      "data": {
        "bytesRead": 373496,
        "timeReadingMicros": 230707
      }
    },
    "protocol": "op_msg",
    "durationMillis": 375
  }
}
```

**Comment by himpierre** [comment]
This actually seems to be a mongodb issue. Per default mongodb is logging all slow queries.

**Comment by geekgonecrazy** [comment]
Yes this is a mongo thing.  Try this out: https://docs.mongodb.com/manual/reference/configuration-options/#security.redactClientLogData

**Comment by oyxnaut** [comment]
> Yes this is a mongo thing. Try this out: https://docs.mongodb.com/manual/reference/configuration-options/#security.redactClientLogData
Thank you, but unfortunately that's only available for mongo enterprise customers.

If I can figure out what's causing the slow queries, I'll add another comment to this issue, sharing my solution.
In any case, I think it's fair to say it's not an issue with rocket.chat per so, so I'll close this issue.

**Comment by geekgonecrazy** [comment]
Dedicated mongo node following mongo recommendations are where I would start.  If you haven't already.  Check disk IO and make sure it's not a bottleneck also
