### ISSUE TITLE
Update list of users in group/channel after delete users

### ISSUE THREAD

**Issue by TitovIG** [RocketChat/Rocket.Chat#19345]
## My Setup

- Operating System: Windows 10
- App Version: last Web versions
- Installation type: 

- [ y ] I have tested with the latest version
- [ y ] I can simulate the issue easily

## Description
1. Open group/channel
2. Open Members
3. Right esur name - 3 points, choose Delete fron channel
4. Take "Yes"

### Current Behavior
Members not removed. If update list, membel removed.

### Expected Behavior
The list is automatically updated and the member is removed

**Comment by tassoevan** [comment]
@TitovIG Please update the issue description as requested by **close-issue-app**, following our [template](https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/.github/ISSUE_TEMPLATE/bug_report.md), and reopen the issue.
