### ISSUE TITLE
Chrome - mic recording

### ISSUE THREAD

**Issue by FinFrn** [RocketChat/Rocket.Chat#1935]
Chrome browser will not work the mic end and only after refresh the page it will stop recording ..

**Comment by FinFrn** [comment]
Mozilla Firefox 43.0.4 version of the browser , this mic - the recording should work so that the Chrome browser version Version 47.0.2526.106 is not working properly ..

**Comment by graywolf336** [comment]
I believe this is fixed by 3a82beb8ef46540199cfc69e1c9c7bfbda534f9f, please report back if you are still having the issue.

**Comment by FinFrn** [comment]
Yes thats is work now thanks...

2016-01-24 6:29 GMT+02:00 Bradley Hilton <notifications@github.com>:

> Closed #1935 <https://github.com/RocketChat/Rocket.Chat/issues/1935>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/1935#event-524102742>.
>



-- 
Mika Ruohomäki ( Paukku )
http://tarh.fi <http://www.pemari-turku.net> ( TARH - radioharrastajat )
http://frn.fi   ( FreeRadioNetwork - Finland )
http://joirc.net ( Rocket.Chat - Finland keskustelu chat )
Gsm 041 4877195
