### ISSUE TITLE
Broken links in "Search Messages"

### ISSUE THREAD

**Issue by tiagoevanp** [RocketChat/Rocket.Chat#19369]
### Description:

The link in "Search Messages" open to a 404 page.
The URL is opened with \<mark\> tags.

### Steps to reproduce:

1. Click in lookup icon to open "Search Messages" box in chat.
2. Find some link in chat.
3. Click to open the highlighted link.

### Expected behavior:

Link opens correctly.

### Actual behavior:

Link opens a 404 page.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0-develop (open.rocket.chat)
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Ubuntu 20.4

**Comment by damian-centrone** [comment]
could not reproduce the issue, tested on 3.8.0
