### ISSUE TITLE
[Bug] Show unread threads filter issue

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19377]
### Description:

Unread filter in Threads could not show really unread threads

### Steps to reproduce:

1. Threads in some chat
2. Set filter to **Unread**
3. Get an unread message in chat
4. Get no unread in that filter

### Expected behavior:

Unread filter shows only unread threads

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/97294595-3ed46a00-185f-11eb-86dc-8c47bd91c0d3.png)
When user change Filter to All - there is an unread threads shown with blue dot

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: CentOS 7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 3.0.4
- Operating System: MacOS

### Additional context

When user change Filter to **All** - there is an unread threads shown with blue dot

### Relevant logs:

No logs

**Comment by ankar84** [comment]
3.7.1 - bug persist

**Comment by ggazzo** [comment]
I believe we fixed that long time ago , please reopen if not
