### ISSUE TITLE
Self DM contact not showing online after New Sidebar Layout

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#19372]
### Description:

After the new Sidebar Layout change done with 3.8.0-develop (commit edda351), the status for self on the DM list does not reflect the status on the top bar or the DM channel.

### Steps to reproduce:

1. Update to 3.8.0-develop (commit edda351)
2. Make sure your own name shows up on the list of DMs by searching for it.

### Expected behavior:

The DM self contact should reflect the status at the top and in the DM room.

### Actual behavior:

The DM item shows offline.

![image](https://user-images.githubusercontent.com/14616851/97248442-cf636980-17cf-11eb-8421-64688c8bd562.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0-develop (commit edda351)
- Operating System: Ubuntu
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.0.4
- Operating System: Windows 10 2004

### Additional context

No additional context.

### Relevant logs:

No relevant logs.

**Comment by ankar84** [comment]
Confirm that issue https://open.rocket.chat/channel/support/thread/yzyn9rWHpb2xFc7Ao

**Comment by bkraul** [comment]
Seems a subsequent commit has partially re-introduced this issue:

![image](https://user-images.githubusercontent.com/14616851/98112567-0c7eca00-1e68-11eb-9b91-7b76b324dc6a.png)

This is with commit aacbdd9 (latest develop)
