### ISSUE TITLE
[Improve] Focus should be in search fields or in input text box of modal windows

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19378]
### Description:

After user go to Directory now focus is not on search field and one more move is necessary. 
In general - if any new window appeared with search field or new modal window with input text box - focus should be there

### Steps to reproduce:

1. Go to Directory
2. Start type search query
3. Nothing happens because focus is not in search field

### Expected behavior:

Focus should be in a search filed right after user opens Directory

### Actual behavior:

No text cursor
![image](https://user-images.githubusercontent.com/4023037/97296110-45fc7780-1861-11eb-99d8-0d144d8c1443.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: 3.0.4
- Operating System: Windows 10

### Additional context

Issue could be here
https://github.com/RocketChat/Rocket.Chat/blob/833cb1ef1eaf3b69108de494a5e61f71cf03ccb2/app/ui/client/views/app/components/Directory/DirectoryTable.js#L82-L84

### Relevant logs:

No

**Comment by wolfcreative** [comment]
Do the same, but only for the description field when a person uploads (for example) an image

![image](https://user-images.githubusercontent.com/29209797/97314267-558fb680-1889-11eb-88e0-85bd5d1bbc89.png)

**Comment by ricknjacky** [comment]
hey @ankar84 , I want to contribute to this issue, however the /components folders doesn't exist on the version of the repository I have cloned

I am new to the codebase, can you tell me where did i commit mistake

ps:- the screenshot with valid proof here,
![Screenshot (247)](https://user-images.githubusercontent.com/50985033/97343264-4884be80-18ad-11eb-8947-cd454459fce0.png)

and i cloned using the 
`git clone https://github.com/RocketChat/Rocket.Chat.git ` command

**Comment by ricknjacky** [comment]
![Screenshot (248)_LI](https://user-images.githubusercontent.com/50985033/97397753-02ad1200-1910-11eb-8b47-0bb6864194b7.jpg)
as i was trying to find my mistake, i skimmed through the previous commits, i found this, apparently the components folder isn't there in the "develop" branch we clone upon cloning 

further proof:-
![Screenshot (250)](https://user-images.githubusercontent.com/50985033/97398147-b44c4300-1910-11eb-8f9d-590984ed6590.png)


can someone tell me how to approach this further?

**Comment by Ashray123** [comment]
I want to work on this issue if this is still incomplete .. it would be very kind if someone guides me on how to do it!

**Comment by manpoffc** [comment]
Is this issue resolved?

**Comment by wolfcreative** [comment]
@manpoffc no

**Comment by ankar84** [comment]
> Is this issue resolved?

Unfortunately not.
There is a 2 fixed, but they not merged for some reason.

**Comment by Darshilp326** [comment]
@ankar84 No review till now:/

**Comment by wolfcreative** [comment]
@ankar84 Unfortunately, this is not the first time we have observed the irresponsibility of developers. When you need to fix bugs, they introduce new functionality.

And what passions were boiling about push notifications on the forum, and how they evaded the answer - it is impossible to convey in words.

_Я аж английский свой подтянул пока в пикировках с ними был_

**Comment by ankar84** [comment]
@rodrigok @engelgabriel hello!
Please take a look at that issue and whole situation.
Issue with two fixes but no attention from team.
