### ISSUE TITLE
cannot set "default-url-scheme-handler" setting to invalid value "rocketchat"

### ISSUE THREAD

**Issue by bringmetheaugust** [RocketChat/Rocket.Chat#19376]
### Description:

App crashed during the opening.

### Steps to reproduce:

Open the app by terminal using `rocketchat-desktop` command.

### Actual behavior:

![Screenshot from 2020-10-27 13-00-14](https://user-images.githubusercontent.com/40362626/97293404-4b53c500-1855-11eb-960f-0189b10ecdea.png)

### Client Setup Information

- Desktop App: **3.0.1**
- Operating System: **Ubuntu 20.04.1 LTS**

### Additional info

Other apps (browser and mobile versions) with the same account and server work fine.

**Comment by fdellwing** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by bringmetheaugust** [comment]
@fdellwing, damn..
thanks!!!
