### ISSUE TITLE
Google Adsense integration

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#1938]
it would be nice if you provide a google adsense integration so chat owners can monetize their projects

**Comment by Jack-Collins** [comment]
+1 Would also like to see this.

**Comment by pletchman** [comment]
Definitely would like to see this. The rocket.chat environment is awesome within our social website. There we are able to monetize the chat experience. But if user logs in directly to the chat server or rocket chat app then there is no way to easily monetize it

**Comment by phuyem** [comment]
I love to have this feature added as well. Thumbs up

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by FaizanZahid** [comment]
Totally want this feature. It's a must for our case. +1. Would love to have this out of the box

**Comment by Sessa93** [comment]
Old issue but, what about the current plans about Adsense?

**Comment by Tayyaba03** [comment]
Any update on this one?

**Comment by reetp** [comment]
Current policy is that New Feature Requests should be opened as a thread here:
https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close

**Comment by FaizanZahid** [comment]
still waiting to have this, so we can put ads in our web version and react native apps.
