### ISSUE TITLE
Button to scroll to the last message on a channel

### ISSUE THREAD

**Issue by aradhya-gupta** [RocketChat/Rocket.Chat#19399]
### Description:
This is a feature request for a button which when clicked, takes the user to the latest message. When we scroll up to some previous message in the channel, we have to scroll back down to reach the last message in the channel. A button instead would improve user experience. 

Eg-> WhatsApp has this feature
![scrollToLast](https://user-images.githubusercontent.com/55157178/97462903-37978400-1965-11eb-8e4f-a3c5252ad551.jpg)

### Steps to reproduce:

1. Go to an old message way up in the chats. 
2. To come back to the last message again, you have to scroll down

### Expected behavior:
There should be a button to achieve this.

### Actual behavior:
There is no button and we have to manually scroll down.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
There is such button, but in RC it's work when you search something in chat history and get far from last chat message
![image](https://user-images.githubusercontent.com/4023037/97523957-8d474d00-19b4-11eb-9c2a-3507d3bb4b45.png)
And yes, I agree that button behave like WhatsApp or Telegram when that button appeared when you just moved up from last message would be a good improvement to RC.
