### ISSUE TITLE
login to rocket.chat cloud do not work

### ISSUE THREAD

**Issue by gioppoluca** [RocketChat/Rocket.Chat#19396]
Want to try the RASA application so registered to rocket cloud.
Followed the flow to register the workspace that result to be correctly registered
I have to login to the cloud from the admin settings (since it pretends to have a login to make the install in the marketplace)
Click the button, land in the login of the cloud, enter the login data, for a brief moment an "autorization" blue button appears, but i'm redirected immediately to the login again.

### Description:
see above

### Steps to reproduce:

see above
### Expected behavior:
to make the login and be able to install the rasa app

### Actual behavior:
cloud continue to redirect to login

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: chrome, firefox
- Operating System:

**Comment by geekgonecrazy** [comment]
@gioppoluca this typically happens when you are attempting to login to an account different then the one the workspace is registered to.

The login is required so that you can authorize purchases on your account for that workspace.  So if you logged in with another account you would not have authority to purchase an app for that workspace since it doesn't belong to that account.

Another possibility is that you modified site url after registering and it hadn't yet synced.  The login uses oauth.  So if your workspace address changed the redirect_uri would be incorrect and it would behave the same. To fix that scenario goto cloud services and click the sync button at the bottom.

**Comment by gioppoluca** [comment]
You mean that the mail address of the admin of the rocketchat site have to be the same as the one used in the cloud?

**Comment by gioppoluca** [comment]
I've created an account in cloud and registered the workspace with the same account.
I've also changed the admin mail to be the same as the account (even if should not be necessary in my opinion)
I used both the offline and online method, but same results.
I login and see the "authorization" blue button for a fraction of second and than redirected to login.
Really have difficulty in understanding the error.
Could it be for the fact that my rocketchat installation is in docker with traefik in front and lets encrypt certificates (only unusual configuration that could be)
Another problem is that I registered initially the site urs with http and not https, but changed afterwards.
Could there be some other "http" left around?

**Comment by geekgonecrazy** [comment]
> You mean that the mail address of the admin of the rocketchat site have to be the same as the one used in the cloud?

No this is for sure not needed.  Its only about which email you used to register on cloud.  If only a single account then this isn't the issue.

> Another problem is that I configured initially the site url with http and not https, but changed afterwards.
Could there be some other "http" left around?

This is more than likely the issue.  Like I said hit sync in connectivity services and that should solve that one.

> Really have difficulty in understanding the error.

Yes we are working to make it deliver more clear alerts here.  Hopefully will update it soon with better errors here

**Comment by gioppoluca** [comment]
I did press the synch button and it stated that synch was correct, but when I press the login to cloud I get redirected to the cloud login page, enter the credentials, credentials get accepted, i see the "authorize" button for a moment and than be redirected to the login page.
No message whatsoever.
Is like there is some wrong session information around, like it is not happy with some data on its own or like those oauth errors that sometimes happen when you try to get the auth from google and it do not trust the app.
Really difficult to debug, let me know what can I do to better test it.

**Comment by damian-centrone** [comment]
couldnt reproduce the issue, tested on 3.8.0 cloud app version

**Comment by geekgonecrazy** [comment]
also a note.. if happens again it should give much more clear reason as to why it didn't work or at the very least a requestid that we can reference to find out what happened
