### ISSUE TITLE
Invite new users by email

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#194]

**Comment by nrunde** [comment]
+1

**Comment by engelgabriel** [comment]
:+1:

**Comment by stefanffsx** [comment]
+1

**Comment by pixelpoesie** [comment]
+1

**Comment by steedos** [comment]
+1

**Comment by christophwolff** [comment]
+1

steedos <notifications@github.com> schrieb am Di., 15. Sep. 2015, 13:22:

**Comment by JuanMiguelBG** [comment]
+1

Our users use email as identifier,
I want to invite a user to a channel, if I execute de commnad:

/invite @identifier
or
/invite identifier

where identifier is for example: pepito@umus.esx

I got the next  error

No user exists by the name of `@pepitoumus.esx`.

the @ of the email was removed

**Comment by sudoman** [comment]
If email invites are ever implemented, they would need to _not_ bypass SSO.

**Comment by FaizanZahid** [comment]
+1

**Comment by sunjam** [comment]
Wait, it isn't possible to invite a new user by email?
