### ISSUE TITLE
Mime type */* does not work for file uploads

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#1940]
To allow all files to be uploaded.

**Comment by k0nsl** [comment]
Hi,

Try this, it covers quite a lot: `image/*,audio/*,application/*,video/*,text/*`.

**Comment by mitar** [comment]
Yes, I am using that as a workaround.

**Comment by marceloschmidt** [comment]
@mitar the accepted file types are exactly the same as in the `<input type="file">` `accept` parameter. Check https://html.spec.whatwg.org/multipage/forms.html#attr-input-accept for the allowed options.

**Comment by mitar** [comment]
So then it should be allowed to not specify any value?

Also, then `,application/*` and `text/*` are not really valid strings at all by the standard? But it seems they are accepted?

**Comment by marceloschmidt** [comment]
If you leave it blank, it will accept all file types. I'll check on the second information and report back in a few minutes.

**Comment by marceloschmidt** [comment]
So, application/* and text/* work because they are valid mime types, with wildcards, eg. text/plain, application/octet, and so on.

**Comment by mitar** [comment]
By the standard `application/*` is not a valid value. Check the link you provided above. It might work, but it is not in the standard.

**Comment by marceloschmidt** [comment]
Well, apparently browsers are accepting all top-level media types: application, audio, example, image, message, model, multipart, text, video, and so are we
