### ISSUE TITLE
User search keeps loading when trying to add user to group or channel

### ISSUE THREAD

**Issue by Hossayno** [RocketChat/Rocket.Chat#19406]
### Description:

When adding new users to new or existing private groups or channel, it keeps on showing  "Loading." But works well when trying to create new Direct Messages 

### Steps to reproduce:

1. Create New
2. Channel
3. Type something in Invite Users
4. It only shows "Loading."

### Expected behavior:

Show list of users like when I try to DM someone:
![image](https://user-images.githubusercontent.com/73643180/97559139-576a8e80-19dd-11eb-8785-1d37cbe1e7d7.png)

### Actual behavior:
![image](https://user-images.githubusercontent.com/73643180/97559241-779a4d80-19dd-11eb-9729-6fde2e0c21b6.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Ubuntu 20.04
- Deployment Method: SNAP
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.13.1 - x64
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: 2.17.7
- Operating System: Windows 10

**Comment by Hossayno** [comment]
![image](https://user-images.githubusercontent.com/73643180/97561418-6d2d8300-19e0-11eb-9cb8-6eb8a95441c0.png)
in LDAP configuration with these checked, it works well. If "NAME" is empty in user profile, loading will show indefinitly while that user is in the search.

**Comment by damian-centrone** [comment]
This is already fixed. Tested on 3.8.0

**Comment by brtptrs** [comment]
We are still seeing this problem in 3.8.1
