### ISSUE TITLE
Jump back to mention

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#1942]
is it possible to have a jump back to where you were mentioned?

sometimes we have 400 unread messages in a channel and i need to scroll 300 just for an "@all i am off"

**Comment by lvh1** [comment]
I guess you could just check the 'Mentions' tab at the right side of the page

![](http://i.imgur.com/iTH767M.png)

**Comment by boisletterink** [comment]
That's a good start! I'd also like to see the context of the lines I'd be mentioned in, though. So something similar to #1550 and #827 would be nice.

**Comment by geekgonecrazy** [comment]
@boisletterink this is already implemented..

![image](https://cloud.githubusercontent.com/assets/51996/12375295/185f151c-bc81-11e5-9d9d-934de09d6af0.png)

@sinteur had you seen this ^

**Comment by geekgonecrazy** [comment]
Going to go ahead and close, as this was implemented by @marceloschmidt
