### ISSUE TITLE
Click to Join button does not work if a user joins late

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat#19420]
### Description:

If I join a discussion room after another user has joined and started a Jitsi video conference, and I then click the blue "Click to Join" button, I am unable to join the video conference until I type some text in the discussion room. The telephone icon in the upper right does not have this problem.

### Steps to reproduce:

1. User 1 create a discussion and then launch a video conference in that discussion.
2. User 2 join the discussion
3. User 2 click "Click to Join" button and nothing will happen.
4. User 2 types something into the discussion.
5. User 2 now clicks "Click to Join" and they join the video conference.

### Expected behavior:

Clicking the button should open the video.

### Actual behavior:

I click the button and nothing happens.

![image](https://user-images.githubusercontent.com/4001792/97755732-1606db80-1ad0-11eb-852b-3ab35334e256.png)

### Server Setup Information:

1. - Version of Rocket.Chat Server: 3.7
2. - Operating System: Linux
3. - Deployment Method: Kubernetes docker iimage
4. - Number of Running Instances: 3
5. - DB Replicaset Oplog: ?
6. - NodeJS Version: ?
7. - MongoDB Version: ?

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Mac

### Additional context

None

### Relevant logs:

None

**Comment by rasos** [comment]
Tested on RC  3.9.3:  Confirmed, the `Click to join` button does not work as long as the (guest) user hasn't sent a first message. Instead, users can press the phone symbol to launch a call.
