### ISSUE TITLE
Push notifications for all group messages

### ISSUE THREAD

**Issue by SudoHenk** [RocketChat/Rocket.Chat#1943]
Is it possible to enable push notifications for all messages within a private group? Currently I only get mobile notifications if the chat message mentions my username, but it would be nice to get a notification based on every message that is put in the group.

**Comment by prohde** [comment]
I would also like push notifications for channels.

**Comment by soenkef** [comment]
+1. Nicer to set up the "@all"-function to default and other ways in the setttings. Same like whatsapp. By default: notification for all and through settings the possibiliy to mute e.g. for 8 hours, one week.

**Comment by prohde** [comment]
@soenkef Nice idea!

**Comment by damienmollard** [comment]
+1

**Comment by engelgabriel** [comment]
This is now possible 
![image](https://cloud.githubusercontent.com/assets/1000217/13362263/03da5b10-dca2-11e5-93e4-05ac2f49795e.png)

**Comment by dandv** [comment]
Nice!

**Comment by soenkef** [comment]
Great!
