### ISSUE TITLE
Leave room popup don't close automatically on leaving room

### ISSUE THREAD

**Issue by RohitKumar-200** [RocketChat/Rocket.Chat#19437]
### Description:

After clicking "Leave" on alert popup after leaving room, popup don't close automatically

### Steps to reproduce:

1. Go to open.rocket.chat
2. Leave any room by clicking on option menu
3. Click Leave on popup

![gif](https://user-images.githubusercontent.com/55583961/97895161-6cd31600-1d59-11eb-8ba3-fa48557855f6.gif)

### Expected behavior:

Popup should close automatically on leaving room.

### Actual behavior:

Popup is not closing automatically after leaving any room.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Google Chrome browser Version 86.0.4240.111
- Operating System: Windows 10

**Comment by damian-centrone** [comment]
this is already fixed. tested on 3.8.0
