### ISSUE TITLE
[Bug] Integration History is broken in Admin UI

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19442]
### Description:

Integration History is broken in Admin UI

### Steps to reproduce:

1. Go to Admin UI - Integration
2. Choose any Outgoing integration
3. Click History button
4. Get blank screen

### Expected behavior:

Integration History is opened and I can clear it.

### Actual behavior:

![integr](https://user-images.githubusercontent.com/4023037/97946145-88124580-1d9a-11eb-8b63-761ae3ace255.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.17wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chrome 86 and desktop 3.0.5
- Operating System: Windows 10

### Relevant logs:

No errors in DevTools console or in RC server

**Comment by gabriellsh** [comment]
Hi @ankar84! Are you sure that integration has history? I just tested with one of mine, and it works:

![image](https://user-images.githubusercontent.com/40830821/98037061-c8ed7700-1df9-11eb-9f06-f68e7ebe264f.png)

Can you try to get them via the api endpoint `integrations.history`? https://docs.rocket.chat/api/rest-api/methods/integration/history#example-call

Waiting for your return, thanks!

**Comment by ankar84** [comment]
> Can you try to get them via the api endpoint `integrations.history`? https://docs.rocket.chat/api/rest-api/methods/integration/history#example-call


Hi, @gabriellsh 
Just checked history for one of our outgoing integrations, here is bottom of answer:
```
offset  : 0
items   : 60
total   : 81473
success : True
```

So yeah, there is a history, a lot of history, and I want to clear it in proper way, but can't - it shows blank page instead of history.

**Comment by gabriellsh** [comment]
I've made this PR not too long ago: #19114. It isn't in a release yet though, and I cannot assure it's gonna fix this too.

I really couldn't reproduce this yet. I'd ask for you to place a few logs, but I figured you're probably in a production env, so that's not so straight forward.

Would you be able to test that PR or maybe run that database or a copy of it in a dev environment? If so, please tell me and I'll provide you a few lines I wan't you to log for me. Thanks for you comprehension.

**Comment by ankar84** [comment]
> I really couldn't reproduce this yet. I'd ask for you to place a few logs, but I figured you're probably in a production env, so that's not so straight forward.

Hi, @gabriellsh and thanks for your help!
For sure I can give you needed logs (maybe with some corrections in names and addresses) despite my env is a production env.



> Would you be able to test that PR or maybe run that database or a copy of it in a dev environment?

Actually I can do that in a near future when we enable Retention Policy and DB size will decrease, that I can try it in test env.

**Comment by ankar84** [comment]
Fixed by dropping integration history collection
`db.rocketchat_integration_history.drop()`
I created on first integration launch, and now history is fixed.
![image](https://user-images.githubusercontent.com/4023037/120270738-c16c4e80-c2b2-11eb-9e1f-98282868e396.png)

**Comment by ankar84** [comment]
Still an issue

```
TypeError: l is not a function
    at Qo (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:39)
    at ja (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at di (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at Mf (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at rs (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at $f (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at Zf (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at Lf (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
    at t.unstable_runWithPriority (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416)
Di @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Mi.t.callback @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Tc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Hi @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
os @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
t.unstable_runWithPriority @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
gc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
ns @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Lf @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
(anonymous) @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
t.unstable_runWithPriority @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
gc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
_c @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
bc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
ss @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
t.unstable_runWithPriority @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
gc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
as @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
(anonymous) @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
T @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
x.port1.onmessage @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:39 Uncaught TypeError: l is not a function
    at Qo (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:39)
    at ja (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at di (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at Mf (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at rs (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at $f (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at Zf (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at Lf (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398)
    at e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
    at t.unstable_runWithPriority (e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416)
Qo @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:39
ja @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
di @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Mf @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
rs @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
$f @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Zf @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
Lf @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
(anonymous) @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
t.unstable_runWithPriority @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
gc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
_c @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
bc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
ss @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
t.unstable_runWithPriority @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
gc @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
as @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
(anonymous) @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1398
T @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
x.port1.onmessage @ e177d5862cf172f23aca8a03b48a72e8321dd699.js?meteor_js_resource=true:1416
```

**Comment by ankar84** [comment]
Still an issue in 3.16.3

**Comment by ankar84** [comment]
still an issue in 3.18.1

**Comment by ankar84** [comment]
Still on 4.2.2
But not interface try to load date for some time and then crashes...
I guess that all about amount of data, so fix should be in that aspect @ggazzo @gabriellsh

**Comment by vinogradovia** [comment]
Still on Version 5.1.4

Apps Engine Version 1.34.0
Node Version v14.19.3
Database Migration 281 (October 31, 2022 10:55 PM)
MongoDB 5.0.13-mdb-26cf0d36 / wiredTiger (oplog Enabled)

I also have one integration with broken history. Others are ok. I have 199 rows in collection  db.rocketchat_integration_history.  I think there is problematic data in the fields, such as characters or field size

**Comment by vinogradovia** [comment]
I reduced the number of entries in the history collection to 49 and the log is working , can anyone check this?
