### ISSUE TITLE
Theme issues

### ISSUE THREAD

**Issue by DevBrent** [RocketChat/Rocket.Chat#1944]
I noticed a number of theme issues when using the administration panel's color configuration options.

There are a many buttons, texts, and background colors that are using two different sets of colors (primary/secondary/tertiary/quaternary) rather than always using primary bg with primary font color and secondary bg with secondary font color. This makes altering the theme very difficult.
- Right-hand bar uses primary font color with secondary or tertiary background color.
- Buttons often use primary font color and then button/action background color.

A number of elements on the page are not adjustable.
- Channel title background.
- Message composition bar area, the input itself, and buttons.
- Right-hand quick-menu.

Some of these seem easy to fix while others represent more of a challenge. My question is how are colors added to theme.css? They aren't in base.less for .button at least.

My situation is I'm trying to build a darker theme, but the closest we've come is to use a grey primary background color that doesn't look so bad against the white header/message bar. During the process I had to make several compromises due to how many inappropriate font/bg combinations of primary/secondary/tertiary there were.

**Comment by marceloschmidt** [comment]
Colors are set at the `_colors.import.less` file.

**Comment by Sing-Li** [comment]
related to #2102

**Comment by timkinnane** [comment]
also related #2347

**Comment by MartinSchoeler** [comment]
I will close this, since we are doing a complete ui redesign.
