### ISSUE TITLE
Dedicated Channel for emailing out or send SMS to phone

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1945]
Is there a way to convert/create a channel to be dedicated for emailing out to subscribers? So anything typed in there is going to be sent out. as an email or alert.. ?
again this could be an add-on feature - users can request to order it (i.e it falls under premium) to monetize from chat.

**Comment by Sing-Li** [comment]
YES.   It is already possible today.  Take a look at Adminstration -> Integrations -> Outgoing Webhook.

All you need is a service with an incoming webhook API that sends email or SMS.  

The 'premium' part belongs to (and exists as) another ticket.
