### ISSUE TITLE
Menu styling

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1946]
Can we change the look of the left hand side (menu),a lot of people when they join they don't know where to go, unless they read that splash main page, also not many are aware that they have to click on more and hit the Join channel button.. (at least its not so clear, may make it bolder? or shine out).. 
I think it should be more visible, or to let them know how many channels are available.. .

like now I want to find #support channel on demo.rocket.chat, I basically have to scroll down the list (which is not alphabetical), unless I type / join in here..

**Comment by marceloschmidt** [comment]
Yes! We are accepting PRs for this one, if you are interested in writing one. Thanks!

**Comment by MartinSchoeler** [comment]
Closing this due the new design, if you have this issue with the new design, please open a new issue.
