### ISSUE TITLE
5 Results limited to global search, change limits of search results on 3.7.1

### ISSUE THREAD

**Issue by HRJG** [RocketChat/Rocket.Chat#19469]
### Description: change limits of search results to random amount. 

 When searching for user Jessica I'm only be able to get a result of 5 same names Jessicas, if I had 10 Jessica it will only display 5 Jessica.
### Steps to reproduce: in global search the return result is returned only by 5.

1. 
2. 
3. 

### Server Setup Information:
![55e619abdfaa2ec0fa8d24393917404](https://user-images.githubusercontent.com/72213730/98309441-6da5bb00-1f98-11eb-9ee7-cd9ed880923e.png)
![7ed58d78725110c4a5478aae7aec313](https://user-images.githubusercontent.com/72213730/98309445-6f6f7e80-1f98-11eb-82b9-f81fc78f59c8.png)

- Version of Rocket.Chat Server: 3.7.1
- Operating System: ubuntu 1.8.0.4
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:4.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
It would be nice if that amount of result was configurable by RC admin.

**Comment by HRJG** [comment]
Found the solution, I was able to accomplish the result by changing the settings under  **Administrator - Layout - Number of users' autocomplete suggestions** change that amount to get results.

**Comment by damian-centrone** [comment]
This is already fixed. tested on 3.8.0
