### ISSUE TITLE
Setup wizard (page 1) : when correcting wrong username, it still show an error

### ISSUE THREAD

**Issue by olafleur** [RocketChat/Rocket.Chat#19476]
### Description:

On the first page of the setup wizard, when you enter a wrong username, you have a validation error (good!). But if after that you correct the username, the form won't let you submit.

### Steps to reproduce:

1. Enter informations in setup wizard, but wrong username
2. Click on Continue button
3. There is an error
4. Fix the wrong username
5. Click on Continue button
6. There is still an error

### Expected behavior:

6. It goes to the next page

### Actual behavior:

<img width="370" alt="Capture d’écran, le 2020-11-06 à 21 23 37" src="https://user-images.githubusercontent.com/1068290/98429783-cd729380-2076-11eb-9dac-e78c3d2ad49b.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0-develop
- Operating System: macOS Catalina
- Deployment Method: local
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 86
- Operating System: macOS Catalina

**Comment by stevenvu** [comment]
This error still happens....

url:3000/setup-wizard/1

Use the username @admin and press next. Enter a valid username and it is not accepted.
