### ISSUE TITLE
Integrating with LDAP

### ISSUE THREAD

**Issue by modist** [RocketChat/Rocket.Chat#1947]
have a strange issue integrating with LDAP.

my Bind Search is 
{"filter": "(&(objectCategory=person)(objectclass=user)(sAMAccountName=#{username}))", "scope": "sub",   "userDN": "XXX", "password": " YYY"}
 - and I have validated the filter to work using ldp.exe - a search return the correct user.

I try to log in using an accountname and the proper pw at "/home" - but after clicking the button named "LOGIN (LDAP)" the text in the button changes to "PLEASE WAIT...." - but nothing happens.

the log says :
Bind before search XXXX  YYYY
Client Error: { '0': { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' } }

(XXXX= ldap-user, YYYY=ldapuser-pw)

Any form for advice will be appreciated highly :-)

Kind regards

**Comment by rodrigok** [comment]
Can you paste a Screenshot of your settings?

**Comment by modist** [comment]
![image](https://cloud.githubusercontent.com/assets/3015942/12400448/75d57664-be20-11e5-8bd3-ab0be401718b.png)

**Comment by modist** [comment]
let me know if you need anything else :-)

**Comment by rodrigok** [comment]
@modist are you sure your server is reachable from your rocketchat server?

I tried to connect to your server with no success.

**Comment by modist** [comment]
the server is not reachable outside our firewall

**Comment by rodrigok** [comment]
@modist ok, but the server that your RC is installed can talk to your LDAP? Can you confirm that somehow?

**Comment by modist** [comment]
I can confirm that  - I have used ldp.exe from same location succesfully  - furthermore if I change the user/password (xxxx/yyyy) to something illegal -> "Bind before search XXXX YYYY" fails according to the logs.

**Comment by rodrigok** [comment]
Can you update to latest development version? We did some improvements

**Comment by modist** [comment]
sure - will do that 2morrow .

Being a *nix newbee - I have followed https://github.com/RocketChat/Rocket.Chat/wiki/Docker---Ubuntu-with-Nginx-SSL-and-Hubot  - can you advice me on how to upgrade to latest development version ?

**Comment by modist** [comment]
no issues with latest version :-)
