### ISSUE TITLE
Desktop notifications and sounds not working with multiple rocket instances/nodes

### ISSUE THREAD

**Issue by bseclier** [RocketChat/Rocket.Chat#19492]
### Description:

Hello,
We have 12 rocketchat docker instances (behind an apache reverse proxy, all linked with one mongodb docker instance). The 12 instances are well shown in the admin menu (Exécution d'instances : 12 ; Oplog : Enabled).

We are using the sticky session method in order for a user to always be redirected to the same instance. This is done by a cookie (ex : route.1 or route.12).

When 2 users are chatting with rocketchat, desktop notifications and sounds don't work if they're not on the same instance (same cookie, ex: route.10). In fact, only sounds works when a user is invited in a new room (not when he's DM or mentionned).
If they are on the same instance, all desktop notifications and sound work perfectly. 
Server 3.7.1, Google Chrome or Firefox, Windows 10.

Do you have any idea where this problem could come from ?

Thanks for you help !

### Steps to reproduce:

1. Just 2 users chatting from different rocketchat instances.

### Expected behavior:

Sounds and desktop notifications should work.

### Actual behavior:

They don't, except for a sound when a user joins a new channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS 7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.17

### Client Setup Information

- Desktop App or Browser Version: Tried with google chrome 86 and firefox 82 : same problem.
- Operating System: Windows 10 and Mojav (MacOS)

**Comment by emikolajczak** [comment]
HI,
Do you have set `http_proxy`, `https_proxy` and `no_proxy` variables in docker containers?
If yes, it could be potentially an issue.

**Comment by bseclier** [comment]
Hi, I don't have any of it, here is my docker-compose file :

> version: '2'
> services:
>   rocketchat:
>     image: rocketchat/rocket.chat:3.7.1
>     restart: unless-stopped
>     volumes:
>       - /xxxx/xxx/:/app/uploads
>     ports:
>             - "6003:3000"
>     environment:
>       - MONGO_URL=mongodb://xxx/rocketchat
>       - MONGO_OPLOG_URL=mongodb://xxx/local
>       - ROOT_URL=https://chat.xxx.fr
>     external_links:
>       - chat-mongo
> 
> networks:
>   default:
>     external:
>       name: ul_chat

And here is my variables in a docker container :

> rocketchat@b67623f665e3:/app/bundle$ env
> HOSTNAME=b67623f665e3
> YARN_VERSION=1.22.4
> PWD=/app/bundle
> PORT=3000
> NODE_ENV=production
> Accounts_AvatarStorePath=/app/uploads
> DEPLOY_METHOD=docker
> HOME=/tmp
> TERM=xterm
> SHLVL=1
> ROOT_URL=https://chat.xxx.fr
> MONGO_OPLOG_URL=mongodb://xxx/local
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> MONGO_URL=mongodb://xxx/rocketchat
> NODE_VERSION=12.18.4
> _=/usr/bin/env

**Comment by emikolajczak** [comment]
Check in `Admin -> Info` panel if in `Brodcasr Connected Instances` 
![image](https://user-images.githubusercontent.com/50440047/98675884-1ff3ce80-235b-11eb-9057-cfd0a5665000.png)
for all instances.

**Comment by bseclier** [comment]
I don't have this part in the Admin / Info panel.
My guess is this is not shown because I don't have "extra_hosts:" in my docker-compose file. Am I correct ?
I thought this extra_hosts docker variable was not necessary because the 12 rocketchat instances are on the same VM.

**Comment by ankar84** [comment]
@bseclier you need to set **INSTANCE_IP** for every instance
https://docs.rocket.chat/installation/manual-installation/multiple-instances-to-improve-performance#ensure-nodes-can-communicate

**Comment by bseclier** [comment]
Thank you @ankar84, our problem seems to be that our nodes can't communicate each other, indeed, even if they are on the same host. We have any of these events working (Two different events are fired: 1. The user (you) is typing 2. Notify user (friend)).
We'll try to modify our docker infrastructure and let you know.
Thank you for your help.

**Comment by ankar84** [comment]
> our problem seems to be that our nodes can't communicate each other, indeed, even if they are on the same host.

Indeed that is. We had same issue when we only start using RC and `INSTANCE_IP` fixed that problem

**Comment by bseclier** [comment]
You're right, it solved our problem !
Thank you both for your help :)
Cheers.
