### ISSUE TITLE
Block new registations to rocketchat

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#195]
In our team we would like to block the registration of external users. New users should only join with an invite (#194)

**Comment by nrunde** [comment]
+1
There should be an option to toggle this behavior in a global settings section.

**Comment by engelgabriel** [comment]
:+1: thats right!

We need the admin config page ASAP. I'll bump the priority on that!

**Comment by Julime** [comment]
Maybe there should be an admin account for settings like this?

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by marceloschmidt** [comment]
Copying over a comment from #224:

@graywolf336 
When adding users, will it be an invite style? As that's how I'm used to it but also just being able to add people without them confirming an invite would help for temporary users. Maybe even ability to add users and make them valid for one week only and expire their login until an admin/person with permissions extends their stay.

**Comment by graywolf336** [comment]
Invites are kind of covered in #194, but the temporary users feature would still be a nice addition.

**Comment by marceloschmidt** [comment]
Can this be closed now that we have Accounts_ManuallyApproveNewUsers settings? I think we might need to send an e-mail when new accounts are created, though.

**Comment by graywolf336** [comment]
I would still like the option to fully disable new registration for my instance, that way people aren't even given the option to do it.

**Comment by marceloschmidt** [comment]
Okay! Let's do that and keep this issue open, then.


--
Marcelo Schmidt

**Comment by Theaxiom** [comment]
I agree with this, especially since all of my accounts are managed via LDAP.

**Comment by 42robots** [comment]
Is it possible to disable the "Register new Account" on the login page?

Otherwise, i agree that this must be possible, because right know everyone could enter the chat
if mail confirmation is disabled.

**Comment by Theaxiom** [comment]
This is a critical issue if you are managing accounts via LDAP, is there anyone who can focus on completing this? We are running Rocket.Chat in a corporate environment and they will not let it pass through security approval if we are not able to manage the accounts strictly via LDAP.

**Comment by yonkeltron** [comment]
Agreed that this is a must-have feature for users in corporate environments and beyond.

**Comment by pioneer903** [comment]
(thumb)

**Comment by 42robots** [comment]
Would make sense to just disable the public registration page?
Or are the dependencies to strong to separate that from the registration code?

**Comment by deviousgeek** [comment]
+1

**Comment by lademone** [comment]
+1

**Comment by miscs** [comment]
+1 Must have for coorparate usage

**Comment by rockneverdies55** [comment]
+1

**Comment by 42robots** [comment]
Would really like to integrate that. If there is a hint where to hook into the code, that would
be great :-). I could make a modification and contribute back if things work out .

Best,
Christian

**Comment by Spirotot** [comment]
+1, this would be a great feature/ability to have...

**Comment by icode** [comment]
+1

**Comment by engelgabriel** [comment]
Let's move this to the top of the queue

**Comment by TinajaLabs** [comment]
+ 1 

* disable public registration, or
* have admin confirm/complete registration, or
* admin must register new user, send confirming email to new user

**Comment by doits** [comment]
:+1:  Critical for LDAP management of users

**Comment by lottietoday** [comment]
+1

**Comment by gt50** [comment]
+1

**Comment by graywolf336** [comment]
To everyone who's gave a plus one, what would be your ideal way to handle this?

**Comment by gt50** [comment]
I would be happy with an "Allow new user registration" true/false option in the administrative area which would disable the "Register a new account link" on the main page and the submit button on the registration page (if they manage to get there somehow).

LDAP or having the administrator create the accounts would be used in lieu of this. I want to use rocketchat for my small business. In its current form I could use it, but I could not make it available on the internet because anyone could register a new account.

**Comment by doits** [comment]
I'd see it same like @gt50, to summarize:

- Option "Disable local user registration" in admin area "Settings - Accounts - Registration"
- If enabled:
  - "Register a new account link" on login page is gone
  - Registration action in backend does not create a new account, even when it receives some data
  - As a bonus: The "Register a new account link" is replaced by a disabled link saying "New user registration currently disabled" and that msg can be customized or left blank, too (maybe over engineering for now)

**Comment by joubertredrat** [comment]
+1 this is a very nice feature

**Comment by engelgabriel** [comment]
Let's create the following settings:

```
Registration Form [Public, Disabled, Secret URL]
Registration Form Secret (string)
Registration with Authentication Services (boolean)
Registration Explanation Message (string)
```

**Comment by Theaxiom** [comment]
Great idea!

Thanks,
Travis Rowland
http://travisrowland.com
http://linkedin.com/in/travisrowland
http://about.me/travisrowland

-----------------------------------------------

This e-mail is privileged and confidential.  Do not forward, copy or print
without authorization.  If you are not the intended recipient of this
E-mail, you are hereby notified that any dissemination, distribution or
copying of this message is strictly prohibited. If misdirected, please
delete and notify the sender by e-mail at travis.rowland@gmail.com.

CAUTION: E-mail sent through the internet is not secure and could be
intercepted by a third party. For your protection, avoid sending
identifying information, such as account numbers or social security numbers.

**Comment by engelgabriel** [comment]
Done via https://github.com/RocketChat/Rocket.Chat/pull/1510/

Please test and let me know if we can close this issue.

**Comment by himbeere** [comment]
Hello.

Has this been fixed? I'm asking because i do not find the setting where i can disable registration.

thanks and cheers
t.

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/12555841/4040b0aa-c36a-11e5-8631-ee3d0b115155.png)
