### ISSUE TITLE
Push via email?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1950]
HI all,
very soon I want to install a server rocket.chat with wordpress, where wordpress already has a service push message on an app for android, to warn the user that has published a new article. 

So I will not need the service of internal push to rocket.chat, although it is very useful. 

instead I wonder if it is possible that when a user writes in the in the chat box, for example "@robert: This is a message for you," named user "robert" receive an email with something like:

Sujet: Notice from chat.example.com
message: max sends you this message: "This is a message for you"
If you answer click on this link

You like the idea?
You rocket.chat already have something similar?

**Comment by geekgonecrazy** [comment]
Notify of mention by email was recently added.  Closing this.
