### ISSUE TITLE
Cannot read property 'getFilter' of undefined during file uploading

### ISSUE THREAD

**Issue by dumka** [RocketChat/Rocket.Chat#19515]
### Description:

A file can't be uploaded. The header with the text "Cannot read property 'getFilter' of undefined" appears at the top of a chat.
The same error appears in both desktop and web clients. Several weeks after updating the server it has been working fine then this error appeared. Reboot didn't help.

### Steps to reproduce:

1. Drag and drop a file to a chat.
2. Press "Send" in the appeared window.

### Expected behavior:

File should be uploaded to the chat.

### Actual behavior:

![image](https://user-images.githubusercontent.com/3381914/98930148-46e20a00-24ed-11eb-85dd-b01bfa49461d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Ubuntu 18.04.2 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.10

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Win 10 Pro

**Comment by dumka** [comment]
Update to 3.8.0 didn't help.

**Comment by dumka** [comment]
For some reason Storage Type changed to Google Cloud by itself. Having changed it back resolved the issue. Closed.

**Comment by iFloris** [comment]
Hi, I ran into a similar issue just now using S3 (wasabi). The problem for me was that there was no folder inside the bucket yet. Just in case that helps someone.
