### ISSUE TITLE
Sending attachment fails

### ISSUE THREAD

**Issue by LazyBoot** [RocketChat/Rocket.Chat#19521]
### Description:

Sending attachment fails with references to temp files

### Steps to reproduce:

1. attempt to upload file (drag and drop or + followed by "add from computer"
2. click send

### Expected behavior:

Message with attachment gets sent

### Actual behavior:

After a quick processing this error appears, and no message is sent
![image](https://user-images.githubusercontent.com/3827482/99006215-648d8e80-2542-11eb-98a7-2cc9ea18362f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: desktop app version 3.0.7
- Operating System: Windows 10 (2004)

**Comment by damian-centrone** [comment]
couldnt reproduce, tested with 3.8.0 browser and dektop app versions.
