### ISSUE TITLE
Upgrade is broken.

### ISSUE THREAD

**Issue by mattmarich** [RocketChat/Rocket.Chat#1952]
When attempting to upgrade rocket.chat server I follow the Ubuntu VPS installation instructions but whem I do a 'node main.js' I receive the following error:

{"line":"80","file":"migrations_server.js","message":"Migrations: Not migrating, control is locked.","time":{"$date":1453074551771},"level":"info"}

I am unable to upgrade the server so need to roll back to the previously installed version of rocket.chat.

**Comment by marceloschmidt** [comment]
This is not a problem with this upgrade, but something that didn't run as expected on another prior upgrade. Can you please tell us what version you are currently using? Go to http://your_server/api/info and see it there. Also, if you can, please go to your database and check the record in `migrations` collection. Tell us what version is it locked at. Thanks.

**Comment by mattmarich** [comment]
Ok, thanks for the update! Here's the information:

api/info - "version": "0.11.0"

001-rs:PRIMARY> db.migrations.find().pretty()
{ "_id" : "control", "version" : 23, "locked" : true }

**Comment by marceloschmidt** [comment]
Can you please set locked to false and reboot your server? This will make the migration 23 and the next ones run. Then you can let us know if any other fails. Thanks.

**Comment by engelgabriel** [comment]
Please reopen if the problem persists.
