### ISSUE TITLE
Failure to start rocketchat 3.8 after update

### ISSUE THREAD

**Issue by MichaelSluydts** [RocketChat/Rocket.Chat#19535]
I tried updating rocketchat today and it failed to start with the new version, downgrading fixed it again. Is there some kind of package incompatibility?

Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]: /opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:280
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:                                                 throw(ex);
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:                                                 ^
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]: TypeError: AsyncLocalStorage is not a constructor
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at module (server/sdk/index.ts:23:34)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at Module.require (packages/modules-runtime.js:238:14)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_module>
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at ee/server/broker.ts:1:80
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at module (ee/server/broker.ts:345:2)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at Module.require (packages/modules-runtime.js:238:14)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_module>
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at module (server/main.js:1:8)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at Module.require (packages/modules-runtime.js:238:14)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at require (packages/modules-runtime.js:258:21)
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at /opt/Rocket.Chat/programs/server/app/app.js:191678:15
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Nov 14 03:54:53 ip0.ip-51-178-4.eu rocketchat[4845]:     at Array.forEach (<anonymous>)
Nov 14 03:54:53 ip0.ip-51-178-4.eu systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE

**Comment by jacotec** [comment]
Had the same issue, update node to 12.18.4!
