### ISSUE TITLE
Deploy on ubuntu problem

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#1953]
Hello
i Do this steps on my ubuntu server :
http://stackoverflow.com/questions/31737086/how-to-install-rocket-chat-to-server-via-ssh
after that i get this error :

root@hostname:/home/123/Rocket.Chat-master/bundle# MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://xyz.com PORT=80 node main.js
Updating process.env.MAIL_URL
stop rendering 676
Updating process.env.MAIL_URL
ufs: created tmpDir /tmp/ufs
configuring push
Using GridFS for Avatar storage
{"line":"80","file":"migrations_server.js","message":"Migrations: Not migrating, already at version 27","time":{"$date":1453110137172},"level":"info"}
startStreamBroadcast

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:492:13)

**Comment by tlhadar** [comment]
hi,
you didn't set the environment variables:

sudo su
export ROOT_URL=http://your-host-name.com-as-accessed-from-internet/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=80

node main.js

**Comment by marceloschmidt** [comment]
The error suggests that you are trying to use an allocated port. I can see you're trying to run it at port 80. Are you sure you don't have apache or nginx listening on that port?

**Comment by hooramin** [comment]
Yes,Exactly!
i have nginx that listening port 80 ! and i searched issues for web-server configs here, but nothing found ! 
i wanna run rocket chat on my main domain without  any port  (like domain.com/) ! and i cant stop nginx too ,because i have some other hosts on that server !
what should i do then ?

**Comment by marceloschmidt** [comment]
You should not be running rocket.chat on port 80 then. 
This line `MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://xyz.com PORT=80 node main.js` you should change PORT to something else (say port 3000).

**Comment by hooramin** [comment]
oh ! i got it ! :+1: 
Thank You @marceloschmidt
