### ISSUE TITLE
RocketChat fails to start after upgrading from 3.7.1 to 3.8.0.

### ISSUE THREAD

**Issue by BizClimb** [RocketChat/Rocket.Chat#19545]
### Description:

Followed the standard upgrade procedure I use, manually each time on my server. Usually on first startup there are some migrating outputs, but this time it just immediately failed to start.

### Steps to reproduce:

Start with 3.7.1 server, then manually upgrade by using the following commands:
1. curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
2. tar -xzf /tmp/rocket.chat.tgz -C /tmp
3. cd /tmp/bundle/programs/server && npm install
4. sudo mv /tmp/bundle /opt/Rocket.Chat
5. sudo chown -R rocketchat:rocketchat /opt/Rocket.Chat
6. sudo systemctl start rocketchat

### Expected behavior:

RocketChat starts are normal.

### Actual behavior:
sudo systemctl status rocketchat shows:

● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-11-15 15:43:08 UTC; 1s ago
  Process: 16043 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 16043 (code=exited, status=1/FAILURE)

Nov 15 15:43:08 my-box rocketchat[16043]:     at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
Nov 15 15:43:08 my-box rocketchat[16043]:     at module (server/main.js:1:8)
Nov 15 15:43:08 my-box rocketchat[16043]:     at fileEvaluate (packages/modules-runtime.js:336:7)
Nov 15 15:43:08 my-box rocketchat[16043]:     at Module.require (packages/modules-runtime.js:238:14)
Nov 15 15:43:08 my-box rocketchat[16043]:     at require (packages/modules-runtime.js:258:21)
Nov 15 15:43:08 my-box rocketchat[16043]:     at /opt/Rocket.Chat/programs/server/app/app.js:191678:15
Nov 15 15:43:08 my-box rocketchat[16043]:     at /opt/Rocket.Chat/programs/server/boot.js:401:38
Nov 15 15:43:08 my-box rocketchat[16043]:     at Array.forEach (<anonymous>)
Nov 15 15:43:08 my-box systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 15:43:08 my-box systemd[1]: rocketchat.service: Failed with result 'exit-code'.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Linux (Debian Buster)
- Deployment Method: tar (manual)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.2.7

### Client Setup Information

N/A

### Additional context

Database Migration: 206
Database Migration Date: November 15, 2020 9:46 AM

I've upgraded many times now so this isn't a fresh 3.7.1 install but many many versions back, this is the first time I've had an issue with upgrading though.

### Relevant logs:
See Above output.

**Comment by BizClimb** [comment]
Might be a duplicate of #19537 but I will check.

**Comment by Safemode** [comment]
I was also on 3.7.1 with NodeJS at version 12.14.0. I've also had this server install since Jan2019, and have just been continually upgrading without any issues previously. After doing a specific node install to v12.18.4 from the referenced issue above, everything started right up for me.

**Comment by Redleks** [comment]
Check node version:

`/usr/local/bin/node -v`

It's should be 12.18.4

**Comment by desser-code** [comment]
`sudo n install 12.18.4` worked for me

**Comment by MartinSchoeler** [comment]
> Might be a duplicate of #19537 but I will check.

Yep it is, please use that issue for discussion. Thanks!

**Comment by Marsalys** [comment]
need help, i don't find solution

root@rocketchat:~# systemctl status rocketchat.service
● rocketchat.service - Rocket.Chat server
     Loaded: loaded (/etc/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-01-24 19:51:42 UTC; 3h 28min ago
    Process: 20626 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
   Main PID: 20626 (code=exited, status=1/FAILURE)

janv. 24 19:51:42 rocketchat rocketchat[20626]:     stale: false,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     compatible: true,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     heartbeatFrequencyMS: 10000,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     localThresholdMS: 15,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     setName: 'rs01',
janv. 24 19:51:42 rocketchat rocketchat[20626]:     logicalSessionTimeoutMinutes: undefined
janv. 24 19:51:42 rocketchat rocketchat[20626]:   }
janv. 24 19:51:42 rocketchat rocketchat[20626]: }
janv. 24 19:51:42 rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
janv. 24 19:51:42 rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.


how can i fix it
