### ISSUE TITLE
Rocket Chat website fails to load on CentOS Chrome v42

### ISSUE THREAD

**Issue by philipwhiuk** [RocketChat/Rocket.Chat#1954]
All you get is the 'Welcome To Rocket Chat' loading bar.

**Comment by philipwhiuk** [comment]
Of course there's no Rocket Chat client for CentOS either :(

**Comment by marceloschmidt** [comment]
Can you open the browser console and see if there are any errors there? Thanks

**Comment by philipwhiuk** [comment]
There are no errors or other logging in the console.
