### ISSUE TITLE
Rocket.Chat menu bar icon should have a white outline, not a black outline in light mode

### ISSUE THREAD

**Issue by andylin2004** [RocketChat/Rocket.Chat#19541]
### Description:

Rocket.Chat icon in light mode shows up as Rocket.Chat icon with black outline

### Steps to reproduce:

1. Set appearance system-wide to light mode.
2. Go launch Rocket.Chat from either the launchpad, dock, or finder.
3. Rocket.Chat menu bar item should appear in the menu bar

### Expected behavior:

Rocket.Chat outline icon to appear in white outline on menu bar in light mode.

### Actual behavior:

Rocket.Chat outline icon to appear in black outline on menu bar in light mode.
<img width="1440" alt="Screen Shot 2020-11-14 at 11 06 30 AM" src="https://user-images.githubusercontent.com/60021592/99151476-774eb300-2669-11eb-9cc3-bca9ac315acd.png">

### Server Setup Information:

- Version of Rocket.Chat Server: N/A
- Operating System: N/A
- Deployment Method:  N/A
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: Desktop App version 3.0.3 (from Mac App Store)
- Operating System: macOS Big Sur 11.0.1/10.16.1

### Additional context

N/A

### Relevant logs:

N/A

**Comment by phriedrich** [comment]
This ticket should probably be moved to: https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by andylin2004** [comment]
Ok, thank you. This will be closed and moved.
