### ISSUE TITLE
Can delete google account

### ISSUE THREAD

**Issue by faab007** [RocketChat/Rocket.Chat#19557]
### Description:

When a user logs in with google they can't delete there account.
To confirm it asks for the username but the input box is a password box and when submitted it gives an error.
I used snaps to install Rocket.chat

**Error:** _Invalid username [error-invalid-username]_

### Steps to reproduce:

1. Account settings
2. Delete account
3. Enter info
4. click button
5. get error

### Expected behavior:

Delete the account

### Actual behavior:

Get error **Invalid username [error-invalid-username]**

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 86.0.4240.198 
- Operating System: Windows 

### Additional context

none

### Relevant logs:

I20201116-13:26:41.541(1) Exception while invoking method deleteUserOwnAccount Error: Invalid username [error-invalid-username] at MethodInvocation.deleteUserOwnAccount (app/lib/server/methods/deleteUserOwnAccount.js:38:10) at MethodInvocation.methodsMap. (app/lib/server/lib/debug.js:67:34) at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12) at packages/ddp-server/livedata_server.js:1689:15 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js: 1234:12) at packages/ddp-server/livedata_server.js:1687:36 at new Promise () at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12) at Server.apply (packages/ddp-server/livedata_server.js:1625:26) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:262:26) at app/api/server/api.js:394:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js: 1234:12) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9 => awaited here: at Promise.await (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12) at Server.apply (packages/ddp-server/livedata_server.js:1638:22) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:262:26) at app/api/server/api.js:394:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js: 1234:12) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9

**Comment by wolbernd** [comment]
The same problem occurs when a user has logged in via SAML
