### ISSUE TITLE
Emoji in firefox very slow to show

### ISSUE THREAD

**Issue by wadouk** [RocketChat/Rocket.Chat#19558]
### Description:
When clicking on emoji selector, it's quite slow, the tab is freezing

### Steps to reproduce:

1. Compose a message
2. Add an emoticon/emoji
3. Wait for displaying it

### Expected behavior:

Instantly shown

### Actual behavior:

10s to display it

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0 (was OK 3 versions behind)
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: Docker
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: 82.0.3
- Operating System: Manjaro

### Relevant logs:

Doesn't seen to be relevant

**Comment by wadouk** [comment]
Much better in 3.9 but still 1 seconds or 2 seconds

**Comment by ArneBab** [comment]
I see a 3 second delay when opening the emoji flyout for the first time on Firefox. Subsequent operation is fast, but the initial opening is very slow — only in Firefox.

Version: 	"6.5"

**Comment by mremptypants** [comment]
Yeah same, phone they load great.  I think it sorts them weird.

**Comment by reetp** [comment]
It is pretty well pointless commenting on issues that were opened 4 years ago on a way old version. No one is going to read it.

I will close this. 

Please open a new bug with a fully completed bug template and make sure you have tested this on the latest code.

You can mention this bug in a link to tie them together.

Thanks.
