### ISSUE TITLE
https://releases.rocket.chat/3.8.0/download sends version 3.7.2.

### ISSUE THREAD

**Issue by bjozet** [RocketChat/Rocket.Chat#19553]
### Description:
Our deployscript tries to download specific versions of rocket.chat when deploying. When we want to upgrade to 3.8.0, we try to get the latest .tar.gz from https://releases.rocket.chat/3.8.0/download, however this redirects to version 3.7.2.

### Steps to reproduce:
```
$ curl https://releases.rocket.chat/3.8.0/download
...
location: https://cdn-download.rocket.chat/build/rocket.chat-3.7.2.tgz?f6f96f77816914e9ffc3af4197396a8a-21
...
```

### Expected behavior:
I expect to receive version 3.8.0 from that url.

### Actual behavior:
Server sends 3.7.2.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.2 
- Operating System: ubuntu
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: N/a 
- NodeJS Version:  N/a
- MongoDB Version: N/a

### Client Setup Information

- Desktop App or Browser Version: N/a
- Operating System: N/a

### Additional context
N/a

### Relevant logs:

N/a

**Comment by adrianovieira** [comment]
Same behaviour here

**Comment by meomay503** [comment]
`docker pull rocket.chat:latest` returns version 3.7.2 as well

**Comment by sampaiodiego** [comment]
thanks @bjozet .. https://releases.rocket.chat/3.8.0/download will now provide the correct release..

@meomay503 official Docker image will be updated with 3.8.1
