### ISSUE TITLE
Question - MongoDB version

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#19551]
### Description:

Hi, I have a question about supported MongoDB versions.
In docs you recommend 3.6.9 version but this version is EOL next april.
We have 4.0.14 and working with it without any issues.
Do you tested and recommend newer version 4.2 or 4.4 or we should stay with 4.0?

### Steps to reproduce:

1. Check MongoDB version.

### Expected behavior:

n/a

### Actual behavior:

n/a

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Centos7
- Deployment Method: docker compose
- Number of Running Instances: 30
- DB Replicaset Oplog: YES
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
