### ISSUE TITLE
High CPU usage in Safari caused by status bullets in sidebar

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat#19568]
### Description:

Happens only in Safai not in Firefox on same system, maybe a bug in the browser. In this case we can leave it, but a workaround is noted below.

### Steps to reproduce:

1. open Rocket.Chat
2. wait and do nothing
3. high CPU usage (increases with number of contacts in the sidebar)

### Expected behavior:

Low CPU usage.

### Actual behavior:

![High load](https://user-images.githubusercontent.com/470153/99382503-f0017980-28cc-11eb-8af6-d086b7e02e5d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.0

### Client Setup Information

- Desktop App or Browser Version: Safari 14.0.1
- Operating System: macOS 11.0.1

### Additional context

Disabling CSS transitions for the status bullet solved the problem:

```CSS
.rcx-status-bullet {
  transition: none !important;
}
```

![Bildschirmfoto 2020-11-17 um 11 58 16](https://user-images.githubusercontent.com/470153/99382680-2c34da00-28cd-11eb-82af-6a4a709c1770.png)

**Comment by bdonfouet** [comment]
@phriedrich can you please explain how to apply the fix (where to put the CSS changes)?
 we have also a high CPU usage using the last version of the client, both in Linux and MacOS.

Rgards

**Comment by phriedrich** [comment]
It’s fortunately very simple: open the admin panel and go to the Layout page. There’s a section for CSS. Add it there, save, and then reload the page in the browser. 

So it’s not only Safari?

**Comment by bdonfouet** [comment]
that is how i did it, but it doesn't change cpu load of clients. what effect this modification is it supposed to disable? because i don't see any difference (on linux) on the ui with and without the tweak.

on our side it not only safari.

**Comment by phriedrich** [comment]
Not sure what exactly triggered this, but there's an SVG background in this element.

But if the above didn't work, you probably see something else. I used the browser's web inspektor to remove several elements from the page until the load dropped.

**Comment by felipetomm** [comment]
We have the same problem on MacOS Big Sur 11.0.1 with Safari 14.0.1.
After apply this CSS, the situation has normalized.

**Comment by ggazzo** [comment]
hey @phriedrich could you test at open.rocket.chat?

**Comment by phriedrich** [comment]
@ggazzo Nothing to see, but I have only two channels in my contacts and this problem increases with the number of contacts in the sidebar.

**Comment by ggazzo** [comment]
I will close this issue since we removed all the transitions by default here: https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/336

any problem please let me know :)

btw: open.rocket.chat is currently running develop (3.10.0-develop)  :v:

**Comment by phriedrich** [comment]
Great, thanks!
