### ISSUE TITLE
Origin https://exemple.com is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by kangyili** [RocketChat/Rocket.Chat#19560]
### Steps to reproduce:

1. deploy rocket chat by helm
2. upload file

### Expected behavior:

file uploaded

### Actual behavior:

every type of file can be uploaded except .pdf file

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Linux
- Deployment Method: helm
- Number of Running Instances: 2
- DB Replicaset Oplog: 2 replicasets
- NodeJS Version: 
- MongoDB Version:lastest

### Client Setup Information

- Desktop App or Browser Version:Browser Version
- Operating System:ubuntu
![IMG_5911](https://user-images.githubusercontent.com/42437228/99285702-2e992480-2838-11eb-8adb-55c20b36c6dd.JPG)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
