### ISSUE TITLE
Minor Sort Bug

### ISSUE THREAD

**Issue by teak421** [RocketChat/Rocket.Chat#19574]
### Description:

Sorting Issue on USERS page

### Steps to reproduce:

1. Go to admin
2. Click on USERS
3. Click on STATUS (or any column)

### Expected behavior:

Items are sorted correctly.

### Actual behavior:

![image](https://user-images.githubusercontent.com/13898029/99430050-ad847080-28bd-11eb-93ef-df26a04c6122.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Ubuntu 20.04.1
- Deployment Method: Manual;
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: Browser (Chrome Edge)
- Operating System:  Windows 10

**Comment by Cancer-zern** [comment]
Confirm, I have the same issue
Version of Rocket.Chat Server: 3.8.1
Deployment Method: Snap

**Comment by teak421** [comment]
Looks like this has been resolved in #19898.

**Comment by sampaiodiego** [comment]
yes! thanks @teak421 for pointing it out..
