### ISSUE TITLE
Moving up when entering a open an chat thread

### ISSUE THREAD

**Issue by malajisi** [RocketChat/Rocket.Chat#19589]
### Description:

When I entering a thread detail of a conversation, the page jump out of the window like...

![](https://user-images.githubusercontent.com/1553205/99520469-18bd6800-29ce-11eb-9693-7e6d35855c74.png)

It can't back until restart Rocket.Chat.
### Steps to reproduce:

1. Open Rocket.Chat
2. Go through a channel to find a conversation with thread 
3. Open the tread then the page will move out of the window

### Expected behavior:

Not moving the whole page.

### Actual behavior:

Content leaving the window

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method:
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version:3.0.3
- Operating System: macOS 

### Additional context

Not yet

### Relevant logs:

Not yet

**Comment by tassoevan** [comment]
Please fill more server details in your report. It was a bug fixed some releases ago.

**Comment by malajisi** [comment]
> Please fill more server details in your report. It was a bug fixed some releases ago.

Thanks. I don't know the server since I login in with Linux Foundation account. It's related to the LF server?
