### ISSUE TITLE
[Improvement] Update only changed user avatars on LDAP sync

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#19584]
### Description:

We have LDAP set and avatar synchronization enabled with update of existing users.
All avatars for our users are from LDAP. User not able to set own avatar.
Users avatars are changed very rare (almost never). I believe, that many organizations have similar avatar regulation.
Now on a synchronization process if user in LDAP have photo - it will be updated in RC user account without any conditions, despite user already have that same photo. And that process creates a high load on file server (we use minio as Amazon S3 storage). This is really unnecessarily load.
My suggestion here is to update avatar only if it was changed. You can check size, or hash of file, compare it to LDAP photo file and if they different - then delete avatar in RC account and load it from LDAP.
In a recent podcast @sampaiodiego said that next release will focus on LDAP fixes and performance. I think, that is a good improvement for that.
So, @sampaiodiego @pierre-lehnen-rc please take a look at that issue.

### Steps to reproduce:

1. Set **Admin UI - LDAP - Sync/Import** `Merge Existing Users` on, `Sync User Data` on, `Sync User Avatar` on, `Background Sync` on (once a day), `Background Sync Import New Users` on, `Background Sync Update Existing Users` on
2. Wait for sync or start it manually
3. Watch high resources consumption by file server which holds update of every single users avatar

### Expected behavior:

Update of changed avatars only

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/99490814-a3c14280-297b-11eb-9f7e-01adf6d63510.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome 87 and desktop client 3.0.7
- Operating System: Windows 10

### Additional context

No

### Relevant logs:

`LDAPSync ➔ info Syncing user avatar`

**Comment by pierre-lehnen-rc** [comment]
Implemented on 4.0
