### ISSUE TITLE
Localized Time Format

### ISSUE THREAD

**Issue by Silvenga** [RocketChat/Rocket.Chat#1959]
To my understanding, Rocket.Chat displays times in the 24-hour clock format. For United States users, 24-hour timestamps are confusing as we are accustomed to the 12-hour clock. 

Some points made by Microsoft on globalization:

> The use of either a 12-hour or 24-hour clock.
> Most European and Asian locales use the 24-hour clock instead of the 12-hour A.M./P.M. model used in the United States. Also, A.M./P.M. can be rendered in the language of the country, and in some languages comes before the time and not after it.

> The character used to separate hours, minutes, and seconds.
> Although the colon (:) is the character most used in separating the hours, minutes, and seconds, some Asian languages use ideographic characters. In addition, some locales require "h," "m," and "s" as part of the display.

> https://msdn.microsoft.com/en-us/goglobal/bb688125.aspx?f=255&MSPPError=-2147217396

It would be nice if Rocket.Chat would display times based on a per user basis or based on the localization of the browser.

**Comment by marceloschmidt** [comment]
I never realized we were using 24h format everywhere. Thanks for letting us know. The fix is here #1960 and will be accepted sometime soon.
