### ISSUE TITLE
Chat scrolldown after images are loaded

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#196]
If i change to a chat where images are going to be loaded this happens:
- chat messages are loading
- viewpoint is scrolling down to the last message
- image is now loaded
- viewpoint is now too high

**Comment by Julime** [comment]
this happens also with smileys ;)

**Comment by engelgabriel** [comment]
Maybe we need to always load placeholders for images, and fix the height of the preview to 400px
