### ISSUE TITLE
QA-Regression: The Invite users dropdown is not auto-adjustable, the dropdown hides fully on the small screens.

### ISSUE THREAD

**Issue by Ishrat-Manzoor** [RocketChat/Rocket.Chat#19605]
### Description:

The Invite users dropdown is not auto-adjustable, the dropdown hides fully on the small screen.

### Steps to reproduce:

1. Login to Rocketchat
2. Click on the Add option in the sidemenu.
3. Add a new channel
4. Enter Channel name
5. Start typing in the invite input field
Issue: 1. Observe the dropdown remains hidden when the screen is not maximized on the browser.
The dropdown should be auto-adjustable, when there is no space from the bottom it should open from the top as drop-up."
2. On the desktop app, the dropdown doesn't open at all.

### Expected behavior:

Dropdown should be opened and visible to the user.

### Actual behavior:

Dropdown remains hidden.
![image](https://user-images.githubusercontent.com/24873115/99645812-8ab0a400-2a04-11eb-8e1e-6fb164b0c744.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: mac
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
