### ISSUE TITLE
QA-Regression: Starred messages can't be unstarred.

### ISSUE THREAD

**Issue by Ishrat-Manzoor** [RocketChat/Rocket.Chat#19608]
### Description:

Starred messages can't be unstarred

### Steps to reproduce:

1. Go to a message window.
2. Hover over any of the sent message and click on the 3 dots icon.
3. Click on the star option, a star is added on the right side of a message.
4. Now unstar the message.

### Expected behavior:

Message should be unstarred.

### Actual behavior:

Issue: Star is removed as long as the feedback message remains on the screen and then the star reappears.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
This issue was fixed in #19645
