### ISSUE TITLE
Real_name feature do not work correctly for discussion

### ISSUE THREAD

**Issue by dsisysteme** [RocketChat/Rocket.Chat#19619]
### Description:

We use "real_name" feature on 'layout / user interface'.
Inside Discussion this option appear to do not work correctly. Name (real_name) and username appears alternatively when we open/reopen a discussion.

### Steps to reproduce:

1. Enable "real_name" feature on 'administration / layout / user interface'.
2. Click to Create new Discussion or enter inside Discussion already existing.
3. We can see here some user display name (real_name) and other username ; And in fact some messages from a single user can be name and username inside same Discussion

### Expected behavior:

When "real_name" feature on 'layout / user interface' is enabled , view only name (real_name) in DIscussion everytime (and of course other channels and directs messages)

### Actual behavior:

When "real_name" feature on 'layout / user interface' is enabled , user display , name or username alternatively, in Discussion, without apparent logic.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Linux debian buster
- Deployment Method: from source
- Number of Running Instances:  3
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.10

### Client Setup Information

- Desktop App or Browser Version: Chrome / Firefox / Desktop app
- Operating System: Linux

**Comment by Gummikavalier** [comment]
Probably related to same original cause as this thread issue #18769

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
