### ISSUE TITLE
Channel Option doesn´t work Version 3.8.0

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#19617]
### Steps to reproduce:

1.  Own Channel List
2.  three dots for the Channel or Direct Message
3.  nothing happens

### Expected behavior: 

 but it should open the hide/favorite/unread menu

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Ubuntu 18.04 LTS
- Deployment Method:  install without docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: Desktop App Version 3.0.2, Chrome Browser 86.0.4280.66
- Operating System: Windows 10

**Comment by MartinSchoeler** [comment]
Please move the discussion to https://github.com/RocketChat/Rocket.Chat/issues/19544 Thanks!
