### ISSUE TITLE
Whitespace stop search for tag('@') a user in 'Message' input 

### ISSUE THREAD

**Issue by dsisysteme** [RocketChat/Rocket.Chat#19623]
### Description:

Whitespace stop search when we search a user to tag (@firstname lastname) inside 'Message' input
We use "real_name" feature on 'layout / user interface' so search (in field 'name') with whitespace is imperative for us.
On large directory it is a problem to find a user.

### Steps to reproduce:

1. Enter inside 'Direct Message' or 'Channel'
2. Use input 'Message' to search a user to Tag ('@firstname lastname') including whitespace.
3. Search stop after whitespace.

### Expected behavior:

Permit search with Whitespace in input "Message" to find a user to Tag ('@') on large Directory

### Actual behavior:

Stop search when enter a Whitespace in search input "Message" to Tag a user

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Linux debian buster
- Deployment Method: from source
- Number of Running Instances:  3
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.10

### Client Setup Information

- Desktop App or Browser Version: Chrome / Firefox / Desktop app
- Operating System: Linux

**Comment by hugocostadev** [comment]
Mention only works with usernames
