### ISSUE TITLE
LIvechat user activation

### ISSUE THREAD

**Issue by andrzejwp** [RocketChat/Rocket.Chat#1963]
I'm running the current develop (0.14.0) with livechat turned on. It took me a while to figure this out and I'm not sure it is the expected behavior - when I have user registration turned on, with "manually aprove new users" turned on - my livechat guests receive "User not active" message when they try to write something in chat.
Everything works fine, when I change the registration options to "manually aprove users" turned off. 
I understand this is because the livechat users are "standard" rocket.chat users, but I think this is wrong in the first place and should be stated in large typeface in the docs, because it's not obvious.

**Comment by marceloschmidt** [comment]
Yes, that makes sense, and is definitely not the expected behavior. We'll work on fixing that! Thanks for reporting it.

**Comment by zaubererty** [comment]
If you have activated manual activation you get following error:
"User is not activated"
When you continue and activate the guest user manually then following message appears:
"Token already exists"

To work around this issue just disable the manual user activation (Settings -> Accounts -> Registration)
May be you need to change the registration behavior as well. 

Running current Dev

**Comment by jots** [comment]
I ran into this problem.  I turned off "manually approve users"  but I still get "Token already exists"  after restarting the server even.  Not sure how to get rid of the token.

**Comment by matrunchyk** [comment]
Same issue for me. How to workaround that?

**Comment by matrunchyk** [comment]
I'm using 0.24.0

**Comment by morlbo** [comment]
Same here,
I turned off "manually approve users" but I still get "Token already exists".

**Comment by jmls** [comment]
yup - just hit this as well. I was hoping that livechat would enable me to allow visitors to the website to open a "support" chat - there are 2 things stopping me from doing that

#1 having to have a user defined (what if I get 10000 support calls ? ;) ) 
#2 having the agents real name shown on the chat window - I would expect that an administrator could have an option to set up an alias for the agent when adding them, so that "Mark" or "Steve" or "Julie" would be shown instead of the real agent name

**Comment by unixfox** [comment]
Is it planned to be fixed ?

**Comment by mixrat** [comment]
[Similar Issue](https://github.com/RocketChat/Rocket.Chat/issues/2276#issuecomment-230713338)

**Comment by hardway** [comment]
A simple patch:
```
diff -r 2d0e5fa5bf4a packages/rocket_livechat/app/client/lib/_visitor.coffee
--- a/packages/rocket_livechat/app/client/lib/_visitor.coffee    Tue Sep 27 07:39:16 2016 +0000
+++ b/packages/rocket_livechat/app/client/lib/_visitor.coffee    Tue Sep 27 14:10:24 2016 +0000
@@ -6,6 +6,9 @@
        roomToSubscribe = new ReactiveVar null
 
        register = ->
+               if not localStorage.getItem 'Meteor.userId'
+                       localStorage.clear()
+
                if not localStorage.getItem 'visitorToken'
                        localStorage.setItem 'visitorToken', Random.id()
```
