### ISSUE TITLE
Editing message fails after jumping to an older chat 

### ISSUE THREAD

**Issue by maik28** [RocketChat/Rocket.Chat#19664]
### Description:

Editing and sending a message fails after jumping to an older message in the chat. The bug appears just in public channels yet. 

Example: While I'm editing a message I was thinking about a chat with a colleague some days ago in the same channel. So im going to the search bar and search for the chat we had. Now I want to jump to the message by clicking on "Show this message in chat". After that I want to send my edited message, but it doesn't work. On the top right corner a red field appears with the message "Cannot read property of undefined msg.". The prompt is still yellow in "Edit mode". 

### Steps to reproduce:

1. Join a public channel
2. Choose a message and click on "Edit" (don't send the message)
3. In the channel click on the loupe and search for a message you want to look after
4. Chose the message and click on "show this message in chat"
5. Try to send your edited message which is still in your prompt

### Expected behavior:

The message should be sent and edited. 

### Actual behavior:

Message was sent but not edited. The message prompt ist still yellow like in "edit mode". 
On the right of the top the message "Cannot read property of undefined msg." appears.

The "edited" message 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System: Debian Buster
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 12.19.1
- MongoDB Version: 4.2

### Client Setup Information

- Desktop App or Browser Version: Chrome 80.0.3987.132 (Offizieller Build) (64-Bit)
- Operating System: Debian Buster

### Relevant logs:

Rocketchat log shows:
server.js:204 API ➔ debug POST: /api/v1/method.call/readMessages
server.js:204 Meteor ➔ method readMessages -> userId: TdBQMBvS9Gox5S5iu, arguments: ["qiJbxnT2qLtfhKMo9"]
server.js:204 API ➔ debug Success {
  statusCode: 200,
  body: { message: '{"msg":"result","id":"910"}', success: true }
}

Browser console says:
Uncaught TypeError: Cannot read property 'msg' of undefined
    at U.resetToDraft (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:438)
    at U.keydown (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:438)
    at Object.onKeyDown (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:438)
    at Object.keydown .js-input-message (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:438)
    at 5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:233
    at Function.t._withTemplateInstanceFunc (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:233)
    at h.View.<anonymous> (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:233)
    at 5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:233
    at Object.h._withCurrentView (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:233)
    at h._DOMRange.<anonymous> (5e685ec8dd2044c19e0e91af6048e3c6066caa70.js?meteor_js_resource=true:233)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
