### ISSUE TITLE
Since v3.8.1 channel column full of symbols if font "Inter" installed

### ISSUE THREAD

**Issue by mjunghanns** [RocketChat/Rocket.Chat#19662]
### Description:

On (Windows) PC having the font "Inter" installed, the channel column is not readable anymore as it is full of symbols.

### Steps to reproduce:

1. Log into rocket.chat
2. Once logged in, the problem is present

### Expected behavior:
Everything should be readable, localization should be considered (what it still does).

### Actual behavior:
On (Windows) PC having the font "Inter" installed, the channel column is not readable anymore as it is full of symbols. This was not the case with versions < 3.8.1.
Parts of the chat are displayed in the set language as expected, some parts are only showing symbols. The main chat section is fine. The settings page is all messed up.

![image](https://user-images.githubusercontent.com/22636982/100080081-b0470e80-2e45-11eb-91b3-9bd7dc53e96d.png)

![image](https://user-images.githubusercontent.com/22636982/100080171-cf45a080-2e45-11eb-8268-9422163f895b.png)

The problem seems to be caused by the CSS definition that addresses the "Inter" font in the very first position.
![image](https://user-images.githubusercontent.com/22636982/100080414-1b90e080-2e46-11eb-956c-7296bf26f32c.png)

Upon disabling this definition resp. deleting the font "Inter" the site loads without any display issues.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System:  Linux
- Deployment Method: docker
- Number of Running Instances:  1 
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Browser (Chrome, Firefox, Edge)
- Operating System: Windows 7 / Windows 10

### Additional context

Afore mentioned existence of font "Inter"

**Comment by ggazzo** [comment]
did you instal some custom font on your windows? the prop: font-face, should follow the order until finding some valid font...in your case, would be Helvetica or Segoe... but if you installed some custom Inter font...there is nothing that we can do...(is the user choice see apples and animals instead of letters 🤷 ).. please give me some more info, and I will check if there is anything wrong on our side. but I'm quite confident that there is no 'problem'

**Comment by mjunghanns** [comment]
Yes, on the affected PC are indeed some custom fonts installed. This computer belongs to our marketing department and unfortunately they depend on some awkward fonts that I have a hard time imagining what they could possibly be good for... anyway - I know what you mean, yet I don't understand why, in the mentioned section of the CSS, the font "Inter" is situated in the very first position. For my understanding it does not make sense at all to use this font anywhere in rocket.chat in the first place. At least I think it should yield to Helvetica or Segoe or any other default font that users are most likely to have on their PC as fail-over fonts.
The consequences, if the stylesheets would stay the way they are, would mean, that our marketing department would not be able to use Rocket.Chat. In other words - they could either chat OR do what they were hired for....
Do you think there would be a way to move the "Inter" font to some other class (if the font is really needed) so that usergroups would not become excluded just for the required setup of their fonts?

**Comment by ggazzo** [comment]
do you know which browsers they are using? 
if you are not using IE this code (inserted on the layout -> custom css) should work
```
:root {
 --rcx-font-family-sans: PUT YOUR FONT HERE;
}
