### ISSUE TITLE
The user can't set hide contact or mark as unread. 

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#19660]
### Description:

My user respond click like attachment image three dot.In the normal it's will show "hide and mark as unread and set favorite". But when I upgrade to 3.8.1 the user click three dot. It's can't  show it. I tested admin permission can see it. I has search permission options. I can't see any about this permission options. Could is this bug? 

### Steps to reproduce:

1. Show all contacts or room
2. click contact three dot
3. It's no show "hide and mark as unread and set favorite"

### Expected behavior:

It's will show hide and mark as unread and set favorite at every users.

### Actual behavior:

![3dot](https://user-images.githubusercontent.com/6081927/100035969-3bbaa280-2e3a-11eb-89be-854c94083a08.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System: Debian 9.13
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 3.0.7
- Operating System: Win10

**Comment by ggazzo** [comment]
I'm quite sure this one is the same problem related here: https://github.com/RocketChat/Rocket.Chat/issues/19544
please let me know if I'm wrong, thanks for your report (:
