### ISSUE TITLE
"Don't ask again" - Checkbox

### ISSUE THREAD

**Issue by desser-code** [RocketChat/Rocket.Chat#19675]
### Description:

The checkbox to suppress a message in the future has disappeared.

### Steps to reproduce:

1. For example, click on the menu button of a chat in the sidebar and select "hide".

![image](https://user-images.githubusercontent.com/67997088/100196094-ac27f900-2ef8-11eb-8656-0f4a0a521c1d.png)

2. The message "Are you sure" is shown, but the checkbox to remember the decision is missing.

![image](https://user-images.githubusercontent.com/67997088/100196959-ecd44200-2ef9-11eb-9400-6351a09a2344.png)

### Expected behavior:

Show the checkbox to remember the choice.

### Actual behavior:

Don't show the checkbox to remember the choice.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Linux
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: all

**Comment by Gummikavalier** [comment]
Also if you had this enabled already, it is still visible in the user profile settings, but the dialog is still presented for the user regardless.

**Comment by aKn1ghtOut** [comment]
@Gummikavalier could you please provide a screenshot of where it is present in the profile settings for you. That would help a lot.

**Comment by Gummikavalier** [comment]
@aKn1ghtOut Yes, it is shown like this under personal settings

![Screenshot from 2021-01-18 08-32-34](https://user-images.githubusercontent.com/6958942/104880264-e85f5f00-5967-11eb-8175-1c4e2daea5c9.png)

When I click that setting it shows a scrollbox with only one setting for the existing hide room option. This is with account that had hide room confirmation messages disabled. With a new account this field is empty and I cannot select anything from there. I suppose it has been designed to be used from the confirmation box directly and this would let people just reset specific messages.

**Comment by aKn1ghtOut** [comment]
I could track down what changed and add the checkboxes back if that's a bug and not a conscious decision the team made to remove that feature.
What do you think should be done @ggazzo
