### ISSUE TITLE
How can we have the push notification limit increased to 15k?

### ISSUE THREAD

**Issue by studentsforfalungong** [RocketChat/Rocket.Chat#19688]
Hello,

We became sponsors ~10 days ago, and would like to see our PN limit increased to 15k. Our workspace URL is https://chat.studentsforfg.org/

Although we opened a support ticket with all the required information, the response we received was the following:

_"We could not identify your email contact in our customer database, so Rocket.Chat Support team will check your request on a best effort basis."_

Although our contribution may be small, but we are a group of students working to raise awareness about human rights issues and teach meditation for free. We love your platform but the PN limit increase is necessary for us to keep our communication smooth.

Thank you!

**Comment by Sing-Li** [comment]
@studentsforfalungong please continue the conversation with the support team.  They definitely will help you to apply your credit.

**Comment by mar-v** [comment]
@studentsforfalungong We are checking your issue at this very moment. We will reply to you in the ticket you have created with us. Thanks!

**Comment by studentsforfalungong** [comment]
Thank you Sing-Li and mar-v for responding!
