### ISSUE TITLE
After enabling Force SSL, redirect loop

### ISSUE THREAD

**Issue by tuudik** [RocketChat/Rocket.Chat#1968]
Hi, I upgrade to 0.14.0 and enabled force ssl, my rocket chat is in redirect loop.
I have configured my apache also to run rocket chat with https.
Here's my apache configuration:
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@rocket
		ServerName rocket
		ProxyPreserveHost On
		ErrorLog ${APACHE_LOG_DIR}/rocket-ssl-error.log
        CustomLog ${APACHE_LOG_DIR}/rocket-ssl-access.log combined

        SSLEngine on
		SSLProtocol all -SSLv2 -SSLv3
		SSLCipherSuite ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA
		SSLHonorCipherOrder on
		SSLCompression off
		SSLCertificateFile /etc/apache2/ssl/rocket.crt
		SSLCertificateKeyFile /etc/apache2/ssl/rocket.key
		SSLCertificateChainFile /etc/apache2/ssl/root_bundle.crt

		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>

		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		BrowserMatch "MSIE [2-6]" \
		nokeepalive ssl-unclean-shutdown \
		downgrade-1.0 force-response-1.0
		BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
        #ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket

		DocumentRoot /srv/www/rocket/
		<Directory "/srv/www/rocket">
			AllowOverride None
			Require all denied
			Options Indexes FollowSymLinks
			DirectoryIndex index.html
		</Directory>


		<Location /custom/>
			Require all granted
			Options -Indexes
		</Location>
		ProxyPass /custom !

		ProxyPass /websocket ws://localhost:3000/websocket
		ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket
		ProxyRequests Off
		ProxyPass / http://127.0.0.1:3000/
		ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
</IfModule>
```

**Comment by tuudik** [comment]
Also, can someone please provide as a temporary workaround, how to set Force SSL back to false?

**Comment by tuudik** [comment]
Additional question, when Forcing SSL, as I understand this also will use SSL for ws?
Where to define the certificate that will be used?

**Comment by marceloschmidt** [comment]
@tuudik you'll have to access your database and run `db.rocketchat_settings.update({ _id: "Force_SSL" }, { $set: { value: false } });`

**Comment by marceloschmidt** [comment]
@tuudik can you fetch from `develop` and see if it works for you? apparently there has been a fix after 0.14.0 release.

**Comment by marceloschmidt** [comment]
@tuudik answering your second question, Force SSL is only advisable for people who *don't* have access to a reverse proxy. So if you have a reverse proxy, there's no need to turning that on.

**Comment by tuudik** [comment]
Hi, thanks, the fix worked for me. I guess, it's not actually a bug then. Maybe a warning near to "Force SSL" option to not turn on when using reverse proxy?

**Comment by marceloschmidt** [comment]
No, it is indeed a bug. We are working on fixing it.

**Comment by tuudik** [comment]
Do you want me to try fetch from ```develop``` ? Or is it okay for me to wait 0.14.1 release regarding LDAP issue?

**Comment by marceloschmidt** [comment]
If you could fetch it from develop and test again, that would help us a lot.

**Comment by tuudik** [comment]
Could you give me quick guide to build it drom develop? I usually use https://rocket.chat/releases/latest/download for updating

**Comment by marceloschmidt** [comment]
Just download from https://rocket.chat/releases/develop/download and do exactly as you do with the released versions.

**Comment by tuudik** [comment]
I started the develop version and unfortunately the issue still remains:/ Anything I can do to help you debug the issue?

**Comment by marceloschmidt** [comment]
Not at the moment, unfortunately. We appreciate your time and effort. This issue is now top priority and will be fixed any time soon. Thanks!

**Comment by rodrigok** [comment]
@tuudik you can use Force_SSL with reverse proxy, but you should pass the header `x-forwarded-proto` with value `https`, this is the only way to RC know that the connection is HTTPS, because the reverse proxy get the HTTPS connection and send HTTP to RC.

**Comment by tuudik** [comment]
Force_SSL with reverse proxy? Do I need it still? What does it give me? Just asking, perhaps I dont understand correctly what Force_SSL does.

Regarding: ```x-forwarded-proto with value https``` any hints how to do it with apache?

**Comment by rodrigok** [comment]
@tuudik Force_SSL will redirect users that access RC from non SSL connections to HTTPS.

You can do that in your Apache configuration redirecting users from HTTP to HTTPS, so you don't need the Force_SSL activated, but if you can't or don't want to do that in your Apache you should pass the `x-forwarded-proto` so RC can do that for you.

This is more important for services like `heroku` where users can't change the reverse proxy to force ssl.

**Comment by tuudik** [comment]
Alright then all clear:) I use Apache to forward all traffic via SSL, so I'll keep it switched off. Thank you!

**Comment by tuudik** [comment]
Alright then all clear:) I use Apache to forward all traffic via SSL, so I'll keep it switched off. Thank you!

**Comment by timothyparez** [comment]
The latest 'develop' image still has this issue.

**Comment by engelgabriel** [comment]
Fixed and tested on Heroku and our own hosting nodes.

**Comment by taybin** [comment]
I just encountered this with 0.16.0 on my own ec2 install.  (Using rocket.chat.ansible and then turning on ForceSSL.)

**Comment by msklywenn** [comment]
Encountered this on 0.24.0 too. I don't even remember setting ForceSSL but disabling it re-enabled access to rocketchat.

**Comment by Lochemage** [comment]
I had this same problem, I think it was related to what @tuudik said about Apache, except mine is using nginx to do the redirection.

not sure if this is fixable at all, but maybe it might be nice for it to come with some kind of warning label just in case. I was lucky that I was already logged in on my mobile and was able to toggle the force SSL option off from there, otherwise everyone would have been permanently locked out.

**Comment by stavros-liaskos** [comment]
Same problem here, after enabling "Force SSL", I was locked out. I use Docker for both Mongo db and Rocketchat and Nginx for SSL. All these in a Vagrant box

**Comment by rodrigok** [comment]
Now we have a warning below the input field saying that you should not use that option if you are using a reverse proxy (apache, nginx, etc)

![image](https://cloud.githubusercontent.com/assets/234261/14817489/03a9590a-0b8e-11e6-850e-ba8a50f91189.png)

**Comment by duohost** [comment]
I have revers proxy on my server. I have enabled Force SSL. How to disable ? I dont know how to edit this
@tuudik for a temporary fix, you'll have to access your database and run db.rocketchat_settings.update({ _id: "Force_SSL" }, { $set: { value: false } });

What is command in root ssh ?
