### ISSUE TITLE
lingohub 

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#1969]
when i opened lingohub today i got this message

Sadly, we had to disable this organization and its projects temporarily.
It is currently disabled as the organization's subscription has expired. You can access the projects as soon as the subscription is active again. Don't worry, no data is lost. All of your work is safe!

**Comment by marceloschmidt** [comment]
Yes, we are aware and this is a problem with Lingohub. We are waiting for them to fix it. Please try again in a couple hours. Thanks.

**Comment by marceloschmidt** [comment]
It's fixed now.
