### ISSUE TITLE
Avatar upload/login does not work

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#197]
if i choose facebook/google/... i get the error "Service not configured"
if i choose "select file" nothing happens

**Comment by engelgabriel** [comment]
Have you created the apps on facebook/google and got the credentials to configure the service?

**Comment by Wloa** [comment]
"select file" only work in Chrome.

**Comment by Wloa** [comment]
@engelgabriel - I don't think we have documentation to configure the service for FB, Google, and other.

**Comment by Julime** [comment]
i did not create any apps or configured anything

**Comment by engelgabriel** [comment]
You need your own credentials to use any OAuth service.

I'll create some documentation about it.

**Comment by jerdog** [comment]
Adding a manual icon / avatar via the provided upload your own option does not work.

**Comment by engelgabriel** [comment]
@jerdog What browser and OS?

**Comment by jerdog** [comment]
Chrome (both Incognito and regular) and Firefox. Linux 15.04. Firefox doesn't even provide the file select prompt.

**Comment by nrunde** [comment]
In chrome the thumbnail of the image is shown in the avatar dialog but nothing happens if you chose that option.

**Comment by mhkeller** [comment]
The "select file" is not working for me either in FF 39.0, OS X 10.10.4

**Comment by wolfika** [comment]
Does anyone have any details about the manual avatar upload problem? The demo seems to work just fine, but I can't get it to work on my own installation of Rocket.Chat. Could it possibly be that some file permissions are not set correctly?

**Comment by rodrigok** [comment]
Have you changed your settings to save avatar in File System?
As I remember ,if you didn't, all avatars are saved in MongoDB, so, no problem with file permissions.

**Comment by xjtufjj** [comment]
I also encountered this problem. Can you tell me how to change the settings to save avatar to local file system? 

BTW, I use the latest image.  ALso I found the avatar uploaded to mongoDB:
{ "_id" : "test.jpg", "filename" : "test.jpg", "contentType" : "image/jpeg", "length" : 148655, "chunkSize" : 261120, "uploadDate" : ISODate("2015-08-19T14:18:47.865Z"), "aliases" : null, "metadata" : null, "md5" : "6d30ae0b02ae0d36a7cd7629f12f2238" }

**Comment by rodrigok** [comment]
@xjtufjj you can access the settings of your rocket.chat and go to API menu (admin/API), in the option **avatarStore_type** change to **FileSystem**, save changes and restart your server.

Let me know if it works

**Comment by indiggio** [comment]
Avatars still seem to not be working, at least for me they're not.
I tried uploading a new one, which failed.
I opened up permissions on the destination directory to 777 and it finally uploaded an avatar file successfully, however it refuses to display the avatar in chat.
Even after it says it successfully uploaded the image, a subsequent refresh of the upload avatar page doesn't show the newly uploaded avatar?

**Comment by royalaid** [comment]
+1 I am also experiencing problems with avatars on my installation

**Comment by unquietwiki** [comment]
Recommend default setting for Avatar Storage Type be changed from GridFS to FileSystem. Also believe the issue is related to being assigned to a non-existent directory on startup: if its temporary storage, maybe use /tmp instead? Otherwise, may want to create the avatar subdirectory as part of the install.

**Comment by unquietwiki** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/993
