### ISSUE TITLE
3.8.0: [DEP0097] Using a domain property in MakeCallback is deprecated

### ISSUE THREAD

**Issue by deogracia** [RocketChat/Rocket.Chat#19704]
### Description:

Following an upgrade from 3.1.14 to 3.8.0, in rocket log, some  `[DEP0097] Using a domain property in MakeCallback is deprecated`. I don't understand what generates them
I don't see yet any malfunction in rocket.

### Steps to reproduce:

1. upgrade from 3.1.14 to 3.8.0
2. go to rocket's logs

### Expected behavior:

no exception

### Actual behavior:

```bash
Nov 27 22:25:39 chat RocketChat[18476]: (node:18476) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ok
- NodeJS Version: v12.18.4
- MongoDB Version: 6.14.8

### Client Setup Information

non relevant

### Additional context

* exception appears just after upgrade from 3.1.14 to 3.8.0

### Relevant logs:

```bash
Nov 27 22:25:39 chat RocketChat[18476]: (node:18476) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
```

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
