### ISSUE TITLE
dark mode ignored on MacOS 11

### ISSUE THREAD

**Issue by harridu** [RocketChat/Rocket.Chat#19716]
\### Description:
I have enabled dark mode in MacOS 11 settings, but the message pane of the rocket chat app is still black chars with a white background. The list of channels and contacts on the left side has a dark background, as expected. 

How can I enable dark mode for the messages?

### Steps to reproduce:
start rocket chat app 3.0.3 on MacOS 11 and login

### Expected behavior:
dark mode should be used

### Actual behavior:
dark mode is ignored for the message pane

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information
- rocket chat app 3.0.3
- MacOS11

**Comment by fabiiretro** [comment]
You might want to comment in [RocketChat/Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron). Besides that, does Rocket.Chat even have support for themes? As far as I know, there's _one global_ theme you can define in the admin panel.

**Comment by graywolf336** [comment]
Closing as this pertains to the Electron repository and @fabiiretro is correct, there is technically no dark theme inside Rocket.Chat that is officially supported. It's in the pipeline but nothing is officially supported as of now.
