### ISSUE TITLE
Image preview stopped working - 3.9.0

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat#19714]
### Description:
Prior to the upgrade (3.9.0), when someone posted a link to the image, either direct domain.com/image.png/jpg or via shorturl.com/random there was an image preview showing.

### Steps to reproduce:
1. Go to any channel or DM
2. Paste an image 
3. There is no preview displaying, just a link

### Expected behavior:
1. There should be a preview of the image

### Actual behavior:
This is how information is displayed
![i4elate3K](https://user-images.githubusercontent.com/25570106/100540664-e0742000-323e-11eb-98dd-f79d99c2e874.png)

### Server Setup Information:
* Version of Rocket.Chat Server: 3.9.0
* Operating System:  Docker image
* Deployment Method: Azure Kubernetes Pod
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: Unknown - see rocketchat:3.4.1 image.
* MongoDB Version: 4.0.12

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 3.0.7

- Operating System: Windows 10

### Additional context
 - No additional context

### Relevant logs:
 - No other logs

**Comment by jacotec** [comment]
I can confirm the issue!

**Comment by urosino** [comment]
@g-thome - I just noticed that PDF preview doesn't work anymore either.
