### ISSUE TITLE
ddp failed to listen to  messages

### ISSUE THREAD

**Issue by uwittygit** [RocketChat/Rocket.Chat#1971]
HI, I tried to use ddp client to fetch instant messagses:
my code in client:

con = DDP.connect("http://localhost/");
  DDP.loginWithPassword(con, {username: 'client8@null.com'}, '123', function (error) {
    if (!error) {
      console.log("Logged in!");
      con.call('methodTheRequiresBeingLoggedIn', function () {
        console.log(arguments);
      });
    } else {
      console.log(error);
    }
});

  messages = new Meteor.Collection('messages', con);
  con.subscribe("messages","A9GnPz4TXsPG3xH7xdLa3wBQxh3dgwzenG", new Date())
  //con.subscribe("testMessages");
  messages.find({}).observe({
    added: function(item){
        console.log(item)
    }
});
  msgObject = {rid: "A9GnPz4TXsPG3xH7xdLa3wBQxh3dgwzenG", msg: "HI THERE!"};
  con.call('sendMessage',msgObject);

login sucessed, send messages is ok too, but it can not receive messages. con.subscribe("messages","A9GnPz4TXsPG3xH7xdLa3wBQxh3dgwzenG", new Date()) corrected invoked the function in Rocket.Chat/server/publications/messages.coffee which published messages.
can you help me?

**Comment by uwittygit** [comment]
you can forget this issue, 
messages = new Meteor.Collection('messages', con); the name should be identical to rocketchat_message

**Comment by juliomac** [comment]
@uwittygit know this is long closed. I have used your solution. Thanks! Have you been able to use sendMessage method with this kind of DDP connection? I am struggling with it.
