### ISSUE TITLE
Custom UI hard to achieve?

### ISSUE THREAD

**Issue by tvld** [RocketChat/Rocket.Chat#1972]
We need a simplified UI for a specific target group. We did not find directions how to override the default UI.  What is best way to proceed to use something like this, without running into forking/upgrading hassles?
![1 resized](https://cloud.githubusercontent.com/assets/986182/12418698/18ea729c-beb1-11e5-8527-a4deeb1b7240.png)
![3 resized](https://cloud.githubusercontent.com/assets/986182/12418697/18e6a70c-beb1-11e5-81b1-a03903eac526.png)

**Comment by Sing-Li** [comment]
@tvld   question ...  are ALL your users on mobile, and ONLY interacts via the above UI ?

Or ... are you looking for (on the same server)  a mix of conventional Rocket.Chat browser/desktop UI users PLUS mobile users on current Rocket.Chat UI   PLUS mobile users on above UI?

**Comment by tvld** [comment]
Currently, about 70% of the users are on mobile, this will only increase so we develop mobile first.  Our current solution uses some responsiveness and we would do this here as well, not to leave desktop users completely in the cold. But again... we develop for mobile.

**Comment by geekgonecrazy** [comment]
Seems like overriding the UI to this level might be best going something the route of our PWA efforts.  - https://github.com/RocketChat/rocket.chat.pwa

Seems like adding the ability to allow complete UI swap won't be possible until we make the move to another UI framework.

**Comment by engelgabriel** [comment]
Depends on https://github.com/RocketChat/Rocket.Chat/issues/277

**Comment by andpiazza** [comment]
Hello @tvld, curious how you personalized the RC+ app to the screenshots that opened this thread.

And what's the alternative you suggest to the Hamburger icon. Thanks!

**Comment by tvld** [comment]
@andpiazza  The alternative would have been the bigger buttons at the top/bottom as you can see in the mockup. We never got to the real implementation on Rocker though, so sorry but cant help you much there...

**Comment by geekgonecrazy** [comment]
Going to close this in favor of #277 

Although I feel the true nature of this request was how hard it would be to implement your own UI, not customize ours.

I think now with the improvements to our Rest API and hopefully our documentation.  This wouldn't be so hard.

A good example of this is our Rocket.Chat+ applications.  They are 100% native.  They can only use the api's to communicate.  They use our REST api for all actions, and they use our realtime api to subscribe to events.

So making your own UI is getting easier.

I'd also say that Android as well as potentially iOS have their SDK that communicates with Rocket.Chat seperate from the code base.  So you can now take that SDK and implement your own UI even easier.
