### ISSUE TITLE
TabBar/Flex Column 'width' not persisting between rooms

### ISSUE THREAD

**Issue by garg** [RocketChat/Rocket.Chat#1973]
I noticed that there is a tabbar width option when creating custom packages for RocketChat. I used it like so:

```
RocketChat.TabBar.addButton({
    id: 'paint',
    i18nTitle: 'Paint',
    icon: 'fa fa-paint-brush',
    template: 'drawingBoardMain',
    width: 675, # <------
    order: 11 })
```

Now when I click the button, it does open and the width of the flex column is 675, however, when I change channels while the flex column is opened, all the other rooms show the default width (325?).

I think the correct behavior should be that all rooms should always show the flex column with the correct width.

**Comment by garg** [comment]
Examples:

When button is pressed it shows the correct width:
![image](https://cloud.githubusercontent.com/assets/16932/12424688/421863c0-be9f-11e5-944f-b3d578994f9d.png)

When channel is changed with the same button active, the new channel has the default width:
![image](https://cloud.githubusercontent.com/assets/16932/12424735/6c84c8ce-be9f-11e5-8694-1cec2672a7c6.png)

**Comment by marceloschmidt** [comment]
Yes, that happens because the code that sets the width is attached to the click event and nothing else. Let's think about a solution for this.

**Comment by marceloschmidt** [comment]
I don't think the width should be set on the button, but each template could set their own width upon rendering... so 
```javascript
Template.myCustomTemplate.onRendered(function() {
  $('.flex-tab').css('max-width', "my custom width in px")
});
```
but that would leaves us with a problem that any other template with default width should unset that property `$('.flex-tab').css('max-width', "")`.

Maybe we should have a template for rendering the flexTemplates, this way we could run that upon rendering this template holder...

**Comment by garg** [comment]
That sounds good. I removed the width setting from the button. 

For now I've done:
~~~
Template.myCustomTemplate.onRendered(function() {
	$('.flex-tab').css('max-width', "675px");
});
~~~

and 

~~~
Template.myCustomTemplate.onDestroyed(function() {
	$('.flex-tab').css('max-width', "");
});
~~~

And it works as expected.

**Comment by marceloschmidt** [comment]
Yes, that works as expected, I just wouldn't want everyone developing a new package to have to reset max-width on destroyed. But for now, that's good :) thanks.

**Comment by MartinSchoeler** [comment]
@marceloschmidt is this still a issue or it has been resolved by now?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
