### ISSUE TITLE
Read Receipt for first message in a private channel is not working

### ISSUE THREAD

**Issue by dtvu94** [RocketChat/Rocket.Chat#19733]
### Description:

I am using Rocket.Chat for a small private group.
I discover a bug which doesn't show read receipt status on 'info' tag of the first message of private group.

I discover in the source and figure out root cause:

- Step 3 below, added users' subscriptions hasn't had property `ls`
- Step 6 below, run the function `markRoomAsRead`
- Due to `undefined ls`, `lastSeen` property in callback `afterReadMessages` will be `undefined` too.
- Leads to a consequence, In function `markMessagesAsRead` of object `ReadReceipt`, `storeReadReceipts` cannot be run until the second message.

### Steps to reproduce:

1. Start Rocket.Chat in an account which has permissions to create a private channel, called **admin1**
2. Turn on setting **Show Read Receipts** and **Detail Read Receipts** in /admin/Message
3. Create a private channel, called **p1** with an added user **u1** (or anyone you has in the database with role _user_)
4. Send a message
5. Login to user **u1**
6. Open channel **p1**
7. Logout user **u1**
8. Use account **admin1**, send a message
9. Login to user **u1**
10. Open channel **p1** and see the read receipt working for the second message.

### Expected behavior:

Click on info status of a message should show read receipt of added user **u1**

### Actual behavior:

Only showing read receipt of the creator of the private channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0-develop
- Operating System: Linux Mint 20 ulyana
- Deployment Method: Running meteor directly on the source
- Number of Running Instances: 1
- DB Replicaset Oplog: Default of Meteor npm start, Enable
- NodeJS Version: 12.18.4 x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Operating System: Linux Mint 20 ulyana

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
