### ISSUE TITLE
Retention Policy not deleting Threads

### ISSUE THREAD

**Issue by EnCz** [RocketChat/Rocket.Chat#19731]
### Description:

It seems like the retention policy doesn't delete threads even though administration is configured correctly.

**Our Retention Policy settings in Admin:**
![image](https://user-images.githubusercontent.com/7642122/100802407-b3d02c00-3429-11eb-884f-2d4f08399793.png)
![image](https://user-images.githubusercontent.com/7642122/100802438-c6e2fc00-3429-11eb-98ef-0386be663afd.png)

### Steps to reproduce:

1.  Create new private room
2. Open Room-Info
3. Click Edit -> Prune
4. Tick "Automatically prune old messages" and "Override global retention policy"
5. Set "Maximum message age in days (default: 30)" to 1
6. Click "Save"
7. Write something in this Channel
8. Answer with Thread
9. Wait 1 day

### Expected behavior:

Thread gets deleted

### Actual behavior:

Thread doesn't get deleted.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Deployment Method: docker

**Comment by cprice-kgi** [comment]
check my comment over here:
https://github.com/RocketChat/Rocket.Chat/issues/19730

I think it will help point you in the right direction.

**Comment by TheDom42** [comment]
Same problem here! 
We even performed the workaround described by @cprice-kgi (which finally triggered the correct pruning for regular messages).
However, threads older than the `maxAge` are still there. It would also be great to have a setting for the thread pruning in the room info pruning section.
