### ISSUE TITLE
Zapier could not activate

### ISSUE THREAD

**Issue by Sx3** [RocketChat/Rocket.Chat#19743]
### Description:
We are using self-hosted rocket chat 3x channel ,
and trying to connect tawk.io with rocket chat so that when tawk.io created a new chat then it appears on rocket chat
it seems the Zappier integration test works (it creates a new chat on the rocket chat) but when activating the Zap it shows Error 500

### Steps to reproduce:

1. Activate the Zap
https://zapier.com/apps/tawk-to/integrations/rocketchat

### Expected behavior:
Activate the Zap successfully

### Actual behavior:

throws Error 500
### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.2
- Operating System: Ubuntu 18.04
- Deployment Method: snap
### Relevant logs:
![image](https://user-images.githubusercontent.com/3599933/100976709-ebdc8980-3565-11eb-867a-68423bd635b9.png)

is it possible rocket chat server cause this issue ?

**Comment by dudanogueira** [comment]
Hi!

We just updated our Zapier docs and confirmed it working on 4.5.X, please, check it out:
https://docs.rocket.chat/guides/administration/admin-panel/integrations/zapier

let us know if this issue persists.
