### ISSUE TITLE
Sidebar in mobile webapp doesn't automatically close anymore

### ISSUE THREAD

**Issue by Robbilie** [RocketChat/Rocket.Chat#19755]
### Description:

On mobile when using the PWA, opening the sidebar and selecting a channel doesn't close the sidebar automatically anymore, you have to manually close it. The channel is beeping selected correctly.

### Steps to reproduce:

1. Open Rocket Chat Website on Mobile
2. Open Sidebar
3. Select channel
4. Observe sidebar not closing

### Expected behavior:

Just as before, the sidebar should automatically close itself on selecting a channel to be read.

### Actual behavior:

The sidebar stays open until manually closed.

### Server Setup Information:

- Version of Rocket.Chat Server: 
Whatever runs on open.rocket.chat

### Client Setup Information

Android latest, Pixel 5, Chrome latest

**Comment by Darshilp326** [comment]
@Robbilie Can you guide me to solve this issue?

**Comment by Robbilie** [comment]
What exactly do you need? Happy to help

**Comment by Robbilie** [comment]
@Darshilp326 this should be fairly easy to reproduce yourself :)

**Comment by tpayen** [comment]
Any news on this issue ? The old behavior was imo way better

**Comment by dougfabris** [comment]
@tpayen This issue was fixed here: #22271
Thanks for contributing guys!
