### ISSUE TITLE
Add Push Notification for Chrome browser

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#1976]
Rocket.Chat 0.14

admin/Push

"Send a test push to my user" outputs: 

There are no tokens for this user

**Comment by marceloschmidt** [comment]
Did you save your settings before trying to send a test push?

**Comment by improvethings** [comment]
There is no save option in /admin/Push, and I made no changes there, I just clicked the "Send a test push to my user" option.

**Comment by engelgabriel** [comment]
This message means that your Mobile app did not register the authorization token for you mobile to your user. Please try:
- Deleting the mobile app
- Installing it again
- Login into your server using the mobile app
- Go to the admin panel and use the test push notificaiotn again

**Comment by improvethings** [comment]
I am using Chrome browser on the desktop (osx).

**Comment by engelgabriel** [comment]
So there will be no push notifications, as they are only for Mobiles at this point.

**Comment by Kc57** [comment]
I am currently having this problem and I am using the mobile client for Android. I can see in my server logs a line suggesting the app is registering the client token.

`CLIENT token [ { gcm: 'fvGVFw...removed...KJTy-uHb' } ]`

However when I attempt to send a test message I get this error as well. I am following the below steps:

1. Wipe all app data and re-install
2. Log in as user rob on android
3. Log into server as rob
4. Click on "Send a test push to my user" (says it is successful but notification never occurs)
5. Click on "Send a test push to my user" again. Error: There are no tokens for this user

I have configured the GCM API Key and GCM Project Number. I have also tried enabling/disabling the Enable Gateway setting and setting it to point to https://rocket.chat

**Comment by marceloschmidt** [comment]
@Kc57 that's a different issue from what the user is requesting here. Can you please open a new issue with that information, if that's still happening to you? Anyway, that's a weird behavior. If it says it sent you a notification, it means you have a successful key registered. You could check your database and see if the collection _raix_push_app_tokens has your record there.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this issue due to inactivity.  Please feel free to reach out to us on the demo server in the [#support](https://demo.rocket.chat/channel/support) channel if you have more issues with this.

**Comment by Oliver84** [comment]
I know this issue has been closed for a while but I'm experiencing the same thing. I registered everything, uninstalled and reinstalled the app but still have this issue. After I reinstall the app, I click on "Send a test push to my user" and I get the success message saying that 1 notification was sent. But I don't receive anything on my mobile (I'm signed in as the same user). Then I click the button again and get the same success message. The third time I click the button to send a test push to my user, I get the error saying, "There are no tokens for this user"...

**Comment by lucasvanhalst** [comment]
I too have had the same issue for over a year now. I can uninstall as many times as I want, it just removes my push token after testing it. Gave up on using the mobile app since it's loads way slower than just having it open in the browser.

**Comment by geekgonecrazy** [comment]
This particular issue is related to desktop notifications.  

Things to check for mobile push notifications...
* enable push gateway
* make sure set to https://gateway.rocket.chat
* clear app data on mobile and re-add server
* can also go in and clear out tokens in the database for the user if you want to take it a step further.  I believe there are a few issues related to push notifications for mobile that will contain exact mongo commands to do that.

**Comment by Oliver84** [comment]
I don't understand, if the error says, "There are no tokens for this user" how would clearing out tokens help? I've tried all your steps except the clearing of tokens because I thought it was already cleared according to the message. 

I wonder how people that have notifications are building the mobile app. Are you guys using the play store app, cordova repo, or something else?

**Comment by geekgonecrazy** [comment]
If you are building your own mobile app then none of the above applies.  The above only applies if you are using our app from the app store

**Comment by Oliver84** [comment]
Yes, I think that's the issue. I've been trying to build my own app and it's hard to distinguish the documentation that's meant for building your own app vs docs that pertain to using your app from the app store.
