### ISSUE TITLE
Text is not displayed at the same time with UiKit blocks

### ISSUE THREAD

**Issue by JargeZ** [RocketChat/Rocket.Chat#19771]
### Description:
Adding actions to a message from an rc.app with buttons does not display the text of the message itself

### Steps to reproduce:

1. Send message via RC App with code like this
```
const bt = block.newButtonElement({
    actionId: 'push-button',
    style: ButtonStyle.PRIMARY,
    text: block.newPlainTextObject('Button text'),
    value: 'button-text-action',
});
block.addActionsBlock({elements: [bt]});
message.setBlocks(block);
message.setText('Example text');
await modify.getCreator().finish(message);
```

### Expected behavior:

Actios Block are rendered in addition to the text from the message and other content

### Actual behavior:

Text appear in notify
![img](https://i.imgur.com/yJelFfD.png)
But in chat renders only message actions
![img](https://i.imgur.com/Aeogg1B.png)
### Server Setup Information:

- Version of Rocket.Chat Server:  3.9.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Chrome/85.0.4183.102
- Operating System: Ubuntu-based

### Additional context

The text appears if you remove the added blocks

The text does not overlap. If there are more lines, the behavior is the same

### Relevant logs:
None or don't know which ones are needed

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
