### ISSUE TITLE
 cloud.rocket.chat is unable to reset passwords

### ISSUE THREAD

**Issue by PH-Bluechain** [RocketChat/Rocket.Chat#19774]
### Description:

After my login for cloud.rocket.chat stopped working for no apparent reason, attempting to reset password then following the email link results in a non-functional page.

### Steps to reproduce:

1. Go to cloud.rocket.chat
2. Click on Forgot Password
3. Enter email of existing account and click Continue
4. On receiving email, click on provided link

### Expected behavior:

Page which allows setting a new password for the account

### Actual behavior:

![image](https://user-images.githubusercontent.com/20894725/101297977-cf02c780-387f-11eb-887c-ed4724ba21ad.png)

Page with no working controls, nothing can be clicked on or is interactable in any way.
Developer tools shows the following error, but nothing else obvious:
`in error before res.json 2`

### Server Setup Information:
 (n/a, but bot autocloses issue if I don't include something)
- Version of Rocket.Chat Server: n/a
- Operating System:  n/a
- Deployment Method:  n/a
- Number of Running Instances:  n/a
- DB Replicaset Oplog:  n/a
- NodeJS Version:  n/a
- MongoDB Version: n/a

### Client Setup Information

Browser: Firefox, Chrome, and Safari all identical result
OS: macOS, iOS

### Additional context

Unsure if it's relevant, but I noticed that the password on the account in question doesn't pass current password requirements validation due to a bug in the validation process. Password includes a `{` as special character, but this didn't get detected by the validator as a "special character". Could relate to why the account no longer allows log in with this password.

### Relevant logs:
Firefox:

TypeError: currentNode is null
    canMutationImpactCurrentStyles resource://devtools/client/inspector/shared/style-change-tracker.js:66
    onMutations resource://devtools/client/inspector/shared/style-change-tracker.js:84
    _emit resource://devtools/shared/event-emitter.js:226
    emit resource://devtools/shared/event-emitter.js:172
    emit resource://devtools/shared/event-emitter.js:324
    getMutations resource://devtools/client/fronts/walker.js:405
event-emitter.js:241:21
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:107
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.10.18
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 555 OpenGL Engine
FBO Texture Target: TEXTURE_2D
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved ConduitsParent.jsm:297
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 298"  data: no] FaviconLoader.jsm:298:24
Warning processing windowTypes: This property is deprecated global.min.js:250
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-3.10.18
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 555 OpenGL Engine
FBO Texture Target: TEXTURE_2D 2
debuggee 'resource://devtools/shared/base-loader.js:289' would run builtin-modules.js:196:11

**Comment by geekgonecrazy** [comment]
Can you give this another shot?  If persists shoot me a DM on open.Rocket.chat with email trying to use and I can take a look at account and figure out what’s happening

**Comment by PH-Bluechain** [comment]
Resolved after help from @geekgonecrazy

**Comment by geekgonecrazy** [comment]
Going to close this.  I think it was an issue with our login system that has now been resolved
