### ISSUE TITLE
Context Menus won't open

### ISSUE THREAD

**Issue by tibetischeszentrum** [RocketChat/Rocket.Chat#19779]
### Description:

Channel and conversation menus do not open.
This is only the case on our main windows terminal server. This happens in Firefox and the electron app. Everything is up to date. 
I worked before. After the rocket chat server updated one day it stopped working.
Video to illustrate what I am talking about: https://www.youtube.com/watch?v=y8JcCQNOe9Q

### Steps to reproduce:

The bug is not reproducible for me outside of that one server.

1. Click on the channel context menu in latestest Firefox or latest Electron app

### Expected behavior:

Menu should show up.

### Actual behavior:

Menu does not open.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.3 
- Operating System: Ubuntu 20.04.1 LTS
- Deployment Method: snap
- Number of Running Instances: 1 

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.0.6 and Firefox 83.0
- Operating System: Windows Server 2019 Standard

### Additional context

Reinstalling Firefox and the Electron App did not help.
Using a completely fresh Firefox profile did not help.
Restarting Client and Server did not help.
Updating everything did not help.

In Internet Explorer the problem does not show up.

**Comment by ggazzo** [comment]
fixed here: https://github.com/RocketChat/Rocket.Chat/pull/19638
