### ISSUE TITLE
JSON payload transformer for incoming webhook

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1977]
a) 90%+ of the reported problems with incoming webhook showing blank message is because of payload incompatibility

b) what we can and will display in an incoming webhook 'tile' is finite and limited in variations

Implement a simple _**JSON2RCWebhook transformer 'language'**__ (a DSL), and optionally allow the insertion of a transformer program in this language associated with an incoming webhook

**Comment by engelgabriel** [comment]
We have created a whole class handler for that.
