### ISSUE TITLE
Audio and video files cannot skip forward or back

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#19786]
### Description:

Uploaded audio and video files cannot skip forward or back in the client version of Rocketchat. In the browser version skipping is possible.

### Steps to reproduce:

1. Upload a .mp3 or .mp4
2. Attempt to skip forward on the playbar

### Expected behavior:

You can freely skip to random times in the audio or video file player

### Actual behavior:

Audio and video files are not skippable

### Server Setup Information:

- Version of Rocket.Chat Server:  3.9.0
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: v3.6.3

### Client Setup Information

- Desktop App or Browser Version: 3.0.7
- Operating System: Fedora, Windows 10

**Comment by Ashray123** [comment]
I would like to work on this issue .. someone pls guide me if possible

**Comment by ozergul** [comment]
Issue still persists somehow.

**Comment by dougfabris** [comment]
@ozergul could you share more details, please? 

If possible, could you open a new issue with the details? This PR was closed 2 years ago.
