### ISSUE TITLE
Unable to edit profile because non password created

### ISSUE THREAD

**Issue by Ecphrasis** [RocketChat/Rocket.Chat#19780]
### Description:

I create user by importation of users.csv, and this user logs in successfully with CAS method. So he has no password in his profile. When he wants to edit his profile (email address), he can't, because a security pop-up asks for his password, but he hasn't password...

### Steps to reproduce:

1. create user with csv : user,mail,name
2. This user has no password
3. This user logs in by CAS, his account is good and functional
4. He can't edit his email, because of security pop-up

### Expected behavior:

User can edit his profile

### Actual behavior:

He can't because the security popup prevents him to do that.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.3
- Operating System: Ubuntu server 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Browser or desktop
- Operating System: whatever

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
