### ISSUE TITLE
Incorrect package download (https://releases.rocket.chat/latest/download)

### ISSUE THREAD

**Issue by karl-in-office** [RocketChat/Rocket.Chat#19798]
### Description:

https://releases.rocket.chat/latest/download
I noticed that the above page provides ancient release (version 2.4.13) somehow.
I think this might cause confusions.

### Steps to reproduce:

1. Download from the official latest release page:
 https://releases.rocket.chat/latest/download
2. The result is not latest one. It seems version 2.4.13. 

### Expected behavior:

The official latest release page provides a latest package as stated. At this time, it should be version 3.9.1.

### Actual behavior:
The official latest release page provides a version 2.4.13 package. 

### Server Setup Information:

- Version of Rocket.Chat Server: (N/A)
- Operating System: (N/A)
- Deployment Method: (N/A)
- Number of Running Instances: (N/A)
- DB Replicaset Oplog: (N/A)
- NodeJS Version: (N/A)
- MongoDB Version: (N/A)

### Client Setup Information

- Desktop App or Browser Version: (N/A)
- Operating System: (N/A)

### Relevant logs:

```bash
wget https://releases.rocket.chat/latest/download
--2020-12-08 16:34:42--  https://releases.rocket.chat/latest/download
(snip)
Proxy request sent, awaiting response... 307 Temporary Redirect
Location: https://cdn-download.rocket.chat/build/rocket.chat-2.4.13.tgz?1b7c5f3313cbefc1d026ea9b7ca003ad-10 [following]
--2020-12-08 16:34:43--  https://cdn-download.rocket.chat/build/rocket.chat-2.4.13.tgz?1b7c5f3313cbefc1d026ea9b7ca003ad-10
(snip)
```

**Comment by hever** [comment]
I understand how this was happened (you have updated also 2.4.x rocket chat because of security). But this stupid problem needs to be solved quicky. I was spending couple of hours today to find this problem - I starting search whats wrong on in a deep of error messages and this was absolutely useless. Thanks.

**Comment by karl-in-office** [comment]
To download 3.9.1, use the following link instead.
https://releases.rocket.chat/3.9.1/download

**Comment by karl-in-office** [comment]
I noticed that the latest link has been corrected. 
I'll close this ticket. 
Thank you, Rocket.Chat team!
