### ISSUE TITLE
Disk usage increases significantly when dragging client #19799

### ISSUE THREAD

**Issue by nhh** [RocketChat/Rocket.Chat#19800]
### Description:

Install rocket chat as a windows app. Move window around. You will see that the window stutters slightly and in Taskmanager you will see an increased disk usage when moving the window.

(My guess is that the window position triggers some handler that writes back logs or tracking things...)

### Steps to reproduce:

1. Install Rocket Chat
2. Open Rocket Chat
3. Open Task Manager
4. Move window slightly and check for increased disk usage.

### Expected behavior:

No tracking of window location AND no disk usage when dragging the window.

### Actual behavior:

Lagging, up to 3MB/s disk usage when moving.

### Client Setup Information

- Desktop App
- Operating System: Windows 10

### Server Setup Information
Does not belong here, its a client only issue

### Version of Rocket.Chat Server
Does not belong here, its a client only issue

![Screenshot 2020-12-08 102327](https://user-images.githubusercontent.com/13472382/101464813-6f6bf100-393f-11eb-8fae-f2fe721d71c0.png)

**Comment by ankar84** [comment]
Right place for that issue is https://github.com/RocketChat/Rocket.Chat.Electron/issues

**Comment by nhh** [comment]
I do work a lot with electron apps, this issue is unique to rocket chat.

**Comment by nhh** [comment]
Sorry didnt read properly, was on the rush. Will move the issue.
