### ISSUE TITLE
Christmas decoration feature

### ISSUE THREAD

**Issue by SamirSaidani** [RocketChat/Rocket.Chat#19824]
### Description:

In these uncertain times, when sometimes the only contact with human beings during the lockdown is through chat and video-conferencing, we badly need the christmas magic touch to comfort our souls and hearts.

That's why I'm asking to Santa Claus the possibility in RocketChat to have a special christmas message associated with my favorite christmas sound I could send in a channel, so that each time someone is clicking on the sprite, my short christmas music is played. I'm also asking to Santa Claus a way to put an animated background so that we could decorate our discussion channel, with Christmas trees and garlands.

Thanks in advance, Santa Claus, 
ho🎅! ho🎅! ho🎅! 

### Steps to reproduce:

None, the feature does not exists.

### Expected behavior:

see the description.

### Actual behavior:

Not christmas friendly.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.2

PS: I know that this is not a bug report, but it's definitely not clear how to post a feature request. The Contributing doc states that "If there's a feature you'd like, there's a bug you'd like to fix, or you'd just like to get involved please raise an issue and start a conversation.". I tried to start a conversation and my mouth was immediately shut down by an unfriendly bot. It's my first contribution here, so that's not what I would call a warm welcome. Although perfectly consistent with the christmas theme and icy winter winds...

**Comment by johncrisp** [comment]
Closing this as an issue in favour of the feature request here:

https://github.com/RocketChat/feature-requests/issues/478
