### ISSUE TITLE
incomming OmniChannel not shown to agents until Website or Client is reloaded

### ISSUE THREAD

**Issue by Corinari** [RocketChat/Rocket.Chat#19837]
### Description:
Incoming LiveChats are not shown to Agents on the Incoming LiveChat section until Website or Client is refreshed. 
Also, there is a Bug if you take a Livechat from the incoming queue and return it, it is read-only even for Admin and/or LC Manager User. 

### Steps to reproduce:

1. Select Manual Routing
2. Only have Agent role
3. Start an LiveChat

### Expected behavior:

New Livechat pops up into the incoming LiveChat section

### Actual behavior:

As long as you dont reload it, no sign of new LiveChats

### Server Setup Information:

- Version of Rocket.Chat Server:  3.9.1
- Operating System: node:12.18-slim (Docker Image)
- Deployment Method: Docker
- Number of Running Instances: 1 with this case, probably more that dont use that setup 
- NodeJS Version:  v12.18.4
- MongoDB Version: 3.6.13

### Client Setup Information

- Desktop App or Browser Version: Snap Client of Ubuntu, Firefox, Chrome
- Operating System: Windows, Ubuntu

**Comment by gcommit** [comment]
+1

**Comment by jupiterzhuo** [comment]
same issue +1

**Comment by RehavistaGmbH** [comment]
same here +1

**Comment by diego219** [comment]
same here +1

**Comment by AlenaVorobiova** [comment]
+1

**Comment by Corinari** [comment]
It should be soved with the latest updates, at least in my tests it worked

**Comment by johnypeterson** [comment]
We are still experiencing the same issue on version 3.10.5
Only admins and Livechat Managers can see a new request

**Comment by renatobecker** [comment]
> ### Description:
> Incoming LiveChats are not shown to Agents on the Incoming LiveChat section until Website or Client is refreshed.
> Also, there is a Bug if you take a Livechat from the incoming queue and return it, it is read-only even for Admin and/or LC Manager User.
> 
> ### Steps to reproduce:
> 1. Select Manual Routing
> 2. Only have Agent role
> 3. Start an LiveChat
> 
> ### Expected behavior:
> New Livechat pops up into the incoming LiveChat section
> 
> ### Actual behavior:
> As long as you dont reload it, no sign of new LiveChats
> 
> ### Server Setup Information:
> * Version of Rocket.Chat Server:  3.9.1
> * Operating System: node:12.18-slim (Docker Image)
> * Deployment Method: Docker
> * Number of Running Instances: 1 with this case, probably more that dont use that setup
> * NodeJS Version:  v12.18.4
> * MongoDB Version: 3.6.13
> 
> ### Client Setup Information
> * Desktop App or Browser Version: Snap Client of Ubuntu, Firefox, Chrome
> * Operating System: Windows, Ubuntu

Does the `livechat-agent` role has `view-livechat-queue` permission?
The issue has been fixed here: https://github.com/RocketChat/Rocket.Chat/pull/20022

Perhaps a migration is missing to add the permission to the role.

**Comment by RehavistaGmbH** [comment]
Meanwhile i installed a fresh RocketChat Server 3.10.4
I could not reproduce the problem anymore.

**Comment by renatobecker** [comment]
`livechat-agent` role must have `View Omnichannel Queue` permission.
