### ISSUE TITLE
Dear Rocket.Chat team, STOP DOING THIS.

### ISSUE THREAD

**Issue by iamyevgeny** [RocketChat/Rocket.Chat#19835]
Hello. Stop changing the markup out of blue every new release.
Every time a new version of Rocket.Chat is out, I have to wake up in the middle of the night because my users complain that the UI is broken and I have to figure out how to "fix" the styling rules in accordance with the new markup.
Please stop "fixing" what isn't broken, you're creating a ton of problems for people who run Rocket.Chat in production environments.

Not only these markup updates are absolutely unnecessary and destroy the UI because they're not backwards-compatible, these updates are also half-cooked. For example, some buttons on the sidebar panel (home, search, directory, order, create channel) have [data-qa] that makes targeting these elements convenient, while some don't.

**Comment by ggazzo** [comment]
@iamyevgeny sorry for your inconvenience, I understand your pain, and we have already discussed a lot here within the team, for now, it was defined that changes in the frontend are not considered break changes, and we are free to modify/improve.

`data-qa` are used for testing, without interfering in style or code, not all elements must have this attribute.

the changes may seem 'useless', but in reality, they are not. We are migrating our code, from blaze to React, We are building components based on our framework and most classes are generated, as well as new components with new classes have been developed. all this to offer a more consistent, semantically correct, and more performative interface for you all;

As soon as we finish the migration we have plans to start a project focused on customization and themes. Until then, there will potentially be other breaks, (and if it were 100% fair, you should agree that it is not possible for us to guarantee the support of all your changes).

Anything I can help with, please just let me know. And again, I'm sorry, it will still happen a few times.

**Comment by ggazzo** [comment]
@iamyevgeny for production environments we recommend some staging server before you update, so you can prevent unexpected changes for your users
