### ISSUE TITLE
Scrollback triggers refresh to end of page

### ISSUE THREAD

**Issue by kenmarsh8** [RocketChat/Rocket.Chat#19848]
### Description:

When catching up on dozens or hundreds of messages, I use the scrollbar or mouse scrollwheel in Chrome or Firefox. When I get back to a date boundary, or at some arbitrary point, the screen refreshes and I am at the bottom of the list again. Then I can back scroll past that point, but it may happen again when there is a lot of messages.

### Steps to reproduce:

1.Go to a busy channel with hundreds of messages. 
2. Scroll backwards
3. Watch as eventually you get dumped at the end of messages, and have to start over again.

### Expected behavior:

Just keep scrolling back.

### Actual behavior:

Messages refresh with user/cursor placed at most recent messages.

### Server Setup Information:

- Version of Rocket.Chat Server: Commit tag 2.4.11
- Operating System: Linux x64
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: N/A
- NodeJS Version: v8.17.0
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: Chrome 87.0.4280.88 (Official Build) (64-bit) and previous
- Operating System: Linux x64

### Additional context

N/A

### Relevant logs:

N/A

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by kenmarsh8** [comment]
That ship has sailed.
