### ISSUE TITLE
Migrate local user to LDAP

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#19847]
### Description:

Is there a way to migrate a local user to a LDAP ? At least to remap local user data to LDAP user ?
I have seen only one ticket mentioning it #2952 but I'm not sure this is what I'm looking for.

### Steps to reproduce:

None

### Expected behavior:

Easy way to migrate ;)

### Actual behavior:

No solution to migrate.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Debian 10
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Desktop
- Operating System: Win10

### Additional context

None

### Relevant logs:
None

**Comment by pierre-lehnen-rc** [comment]
If the username is the same, yours users just need to use their LDAP password to login on Rocket.Chat and the LDAP data will overwrite the old password-based user.
