### ISSUE TITLE
For accounts auto-provisioned from LDAP, the user cannot set initial fallback password

### ISSUE THREAD

**Issue by bsdcon** [RocketChat/Rocket.Chat#1984]
For a RC instance with LDAP activated an working, if a user logs first time with LDAP credentials the the account is auto-provisioned.

However, the user is unable to set another fallback password -- the Profile page will not allow him to use the current LDAP password nor an empty password.

On the other hand, an administrator can set a password to the account and from this point the user is able to change his fallback password himself.

**Comment by andrzejwp** [comment]
This is tightly related to #1982 that I reported yesterday.
