### ISSUE TITLE
Livechat agent gets set available randomly

### ISSUE THREAD

**Issue by RehavistaGmbH** [RocketChat/Rocket.Chat#19846]
### Description:

Omnichannel agents get set to active/available seemingly randomly.
When our agents login they are automatically set available. Now they are instructed to set themselves to unavailable after login if is not their shift to operate livechat.
But at some point people get set available again arbitrarily.

### Steps to reproduce:

1. Log into account with role livechat-agent
2. Set availability to unavailable
3. At some point in time recheck if user is still set to unavailable in livechat

### Expected behavior:

User stays unavailable until he sets himself available manually.

### Actual behavior:

User is set to available at some point

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System:  Debian 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.20.0
- MongoDB Version: 4.2.11

### Client Setup Information

- Desktop App or Browser Version: 2.16, 3.0.2 and Firefox 83.0
- Operating System: Windows

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
