### ISSUE TITLE
New sidebar layout - Not display the "New Messages" notice

### ISSUE THREAD

**Issue by scebryan** [RocketChat/Rocket.Chat#19855]
### Description:

Previously, If you have many conversations in the sidebar (more than what you see on the screen) a pop-up appeared indicating "New Messages" in the sidebar.

### Steps to reproduce:

Open many conversations until they disappear from the screen.
A new message arrives in one of those conversations you don't see (it's below).
There is nothing to indicate that you have new messages in those conversations.

### Expected behavior:

As was the case in versions prior to 3.8.0, a pop-up appears indicating "New Messages".

### Actual behavior:

The pop-up indicating "New Messages" does not appear.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: CentOS 8
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.4.1

### Client Setup Information

- Desktop App or Browser Version: Firefox 75.0 
- Operating System: Linux

### Additional context

I think that it happens since: https://github.com/RocketChat/Rocket.Chat/pull/19089

### Relevant logs:

No logs.

**Comment by stardude900** [comment]
Same as https://github.com/RocketChat/Rocket.Chat/issues/19573 ?

**Comment by scebryan** [comment]
Same as #19573 

Sorry! I close it.
