### ISSUE TITLE
Scroll bar resets to very top of room after switching rooms and back.

### ISSUE THREAD

**Issue by mlongmiresqa** [RocketChat/Rocket.Chat#19868]
### Description:

If the scroll bar is not left at the very bottom of a room it will be set to the very stop of the room after switching to another room and back. This forces people to have to scroll all the way to the very bottom of the room to see new messages and can be somewhat laggy as all of the messages and attachments are loaded as you scroll down. See the screencast below.

This occurs on the desktop applications as well as in browsers. I don't believe this is an electron issue as it occurs in browsers like Firefox and Safari.

### Steps to reproduce:

1. Choose a room that has several pages of messages.
2. Scroll up from the bottom, but don't go all the way to the top. 
3. Change to a different room
4. Change back to the room in step 1
5. Observe the scroll bar has been reset to the very top of the room

### Expected behavior:

The scroll bar should either remember where it was left in a given room or default to the bottom where the most recent messages are displayed.

### Actual behavior:

If a channels scroll bar is not left at the very bottom of the room it will reset to the very top after changing to a different room and back forcing the user to scroll through the entire history of the channel.

Screencast of this behavior: https://www.screencast.com/t/ak88G7PGo

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1 and 3.9.0
- Operating System: Centos7 and Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1 per server
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20 and 4.0.13

### Client Setup Information

- Desktop App or Browser Version: Reproduced on 3.0.3, 3.0.6 and 3.0.7
- Operating System: Windows 10 and MacOS Catalina

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/19945

**Comment by mlongmiresqa** [comment]
Hi @ggazzo. I tested this on 3.10.4/3.10.3 and still see this issue. Checked using the webapp as well as the electron app and everything is the same as the screencast in the ticket.
