### ISSUE TITLE
Delete Room is not working properly

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#19869]
### Description:
After deleting room from administration,room still appears in list of rooms.

### Steps to reproduce:

1. Go to administration
2. Select Rooms
3. Click on room to be deleted
4. Scroll down room info and click delete.

### Expected behavior:
Updated room list after deleting room

### Actual behavior:
Deleted room is still listed.

### Server Setup Information:

- Version of Rocket.Chat Server:3.10.0 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Google Chrome
- Operating System:Ubuntu 20.04

### Additional context
![Peek 2020-12-16 00-14](https://user-images.githubusercontent.com/55157259/102259902-b5274b80-3f35-11eb-8b49-edc3c4fea7d6.gif)

**Comment by Darshilp326** [comment]
Can anyone guide me for solving this issue?

**Comment by scebryan** [comment]
@Darshilp326 Hi man,

I think that is for the refresh of the interface. I think it is because of the refresh of the interface. Try clicking on another section and going back to the "Rooms" section.

I can't check it in version 3.10.0 because I don't see that release in the github.

**Comment by MJPGPleasant** [comment]
I have it repoed in 3.9.1, it is a refresh issue. <ctrl><F5> or "Reload ignoring cache" in the client makes the item go away. Same issue exists for deleting users.

**Comment by Darshilp326** [comment]
> @Darshilp326 Hi man,
> 
> I think that is for the refresh of the interface. I think it is because of the refresh of the interface. Try clicking on another section and going back to the "Rooms" section.
> 
> I can't check it in version 3.10.0 because I don't see that release in the github.

Yes it goes on refreshing.
But don't you find it confusing?
@scebryan

**Comment by scebryan** [comment]
Yes, it would be appropriate to do an automatic refresh of the screen when a room is deleted or modified.

As @MJPGPleasant says, it also happens in the user section.

**Comment by aditya-mitra** [comment]
Thanks for pointing out this issue.
I have made a PR which resolves this issue. :smile:

**Comment by dougfabris** [comment]
@Darshilp326 fixed here: #23795
