### ISSUE TITLE
Since Unread Rooms Mode is false by default, users not notified of messages

### ISSUE THREAD

**Issue by pcarn** [RocketChat/Rocket.Chat#1986]
Updated to 0.14.0, and users had "Unread Rooms Mode" false by default. This means that a user will never see a direct message, unless he happens to choose that person from their history.

Is there any way to show the Channels like they used to be?

**Comment by engelgabriel** [comment]
"Unread Rooms Mode" was always false by default. Maybe you are experiencing and upgrade problem. Can you check if you DB migrations is looked?

**Comment by pcarn** [comment]
Perhaps there was an upgrade problem. On the left, only History is shown, for all our users. Even when receiving a direct message, nothing shows. Is this not normal behavior? Channels, Direct Message, and Private Groups disappeared.

**Comment by engelgabriel** [comment]
Can you open the db and do the following?

`db.migrations.find()`

You should see something like:
```
{
"_id": "control",
"version": 27,
"locked": false,
"lockedAt": new Date(1453211085388)
}
```

**Comment by engelgabriel** [comment]
You need to unlock the DB for the upgrades, setting `"locked": false` on your `migrations` collection. On Rocket.Chat 0.14.0 all the permissions have been moved, so if your server have not migrated the DB schema, it won't be able to show the channels on the left.

**Comment by pcarn** [comment]
Waiting on getting the passwords to access this, then I'll give that a try. Thanks

**Comment by geekgonecrazy** [comment]
@pcarn also take a look at #1997 I walk through checking the version.   if it says version 16 then let us know.  Otherwise the solution in that issue should work fine.  :)
