### ISSUE TITLE
Livechat - fill the offline form

### ISSUE THREAD

**Issue by ricardojlrufino** [RocketChat/Rocket.Chat#19881]
### Description:

I use livechat, where I already have the data of the users already registered. But when all agents are offline, he ends up having to fill out the form manually (which causes some problems in my case).

So the ideal would be to use the user registration, and fill in the offline form

Use registerUser to prefill offline form:

```
  RocketChat(function() {
    this.registerGuest({
      name: 'visitor Name',
      email: 'sample@rocket.chat',
      department: 'Another'
    });
  });
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System: Linux
- Deployment Method: Kubernetes
- Number of Running Instances: 1

**Comment by ismabvbbr** [comment]
I have the same problem!!

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
