### ISSUE TITLE
Match Failed [400]

### ISSUE THREAD

**Issue by cassiobastos** [RocketChat/Rocket.Chat#19896]
Steps to reproduce
1 - Go to My Account - Preferences - Highlight - Highlight Words (I don't know if this is the correct option name because I use the Portuguese version, whose translation is "Destaques - Destacar Palavras").
2 - Put some words in the field and save
3 - Clear the field and try to save again
4 - it throws the error "Match Failed [400]"

Expected behavior
To be able to save the field empty

Actual behavior
It prevents me to save until I put some content on it.

Server Setup Information
What kind of information?

Version of Rocket.Chat Server
3.9.1

**Comment by aKn1ghtOut** [comment]
The problem that causes this is that the **initialValue** of the TextAreaInput element(fuselage) does not change after clicking save. There is another issue that happens on the server if you try to enter an empty "highlights" entry after reloading the page which I have solved.
The frontend issue however might have to be dealt with a little differently, as the usage of the initialValue is causing the same issue on every other textfield as well.
