### ISSUE TITLE
Telegram App problem

### ISSUE THREAD

**Issue by Colobon** [RocketChat/Rocket.Chat#19891]
### Description:

I using Telegram App from Rocket Chat marketplace. 
After setup i'm correctly recieving messages from Telegram Bot, but messages from Omnichannel to Telegram are not sending.

### Steps to reproduce:

1. Administration -> Marketplace -> Install Telegram App
2. Administration -> Application -> Setup Telegram App
3. Join to Telegram bot(in Telegram App) -> Send Message
4. Recieve that message in Omnichannel -> Join as agent -> Reply
5. Do not get answer in Telegram bot

### Expected behavior:

User in Telegram see messages from Omnichannel conversation

### Actual behavior:

Telegram
![image](https://user-images.githubusercontent.com/25530861/102634198-8c37ce00-4162-11eb-829c-5b6e66bec719.png)
Rocket
![image](https://user-images.githubusercontent.com/25530861/102634574-1122e780-4163-11eb-87d3-676ba82eea42.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 3.6

### Client Setup Information

- Browser Version:
- Operating System: Windows

### Additional context

None

### Relevant logs:

Logs from Telegram App Logs page
![image](https://user-images.githubusercontent.com/25530861/102635438-5dbaf280-4164-11eb-916b-15a48dbd8666.png)

**Comment by murtaza98** [comment]
Hey @Colobon 

I tried to run the telegram app with same configuration you have specified, however I'm sorry I couldn't reproduce the error you are facing. The app was able to exchange messages in both directions.

Could u confirm if u are still facing this error?

**Comment by Colobon** [comment]
Yes, it still here

Well, i've created a new bot just now. Set the bot's privacy to "Disable"(just in case...), changed the "Telegram Bot Token" in the Rocket to the new one.
After it, i joined to the new bot in Telegram and recieved(!) "Welcome Message" from Rocket. But now i see same problem - messages go only from the Telegram to the Rocket, but not back

**Comment by Colobon** [comment]
So, testing with my colleagues have shown that everithng is working fine. Almost. Because messages do not sending only to my Telegram account.

This is probably my local problem. I think this issue can be closed. Thanks.

**Comment by ArtemKobz** [comment]
I have exactly the same issue and do not see any ways to troubleshoot it. 
I see requests coming in to nginx from Telegram servers. And I see "200 OK" response to it. But messages does not appear in the UI. 
Application log was not showing anything useful. 
After a while - I saw new error message, but still have to idea why is it here and how to fix  it.
Here is the snippet: 

[
  "Error occurred while processing the request. Details:- ",
  "{\"stack\":\"Error: No permission checker found for the bridge method \\\"AppLivechatBridge.isOnlineAsync\\\"\\nPlease create a new cheker one under the permissionChekers folder to fix the issue.\\n    at Function.checkPermission (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppPermissionManager.js:47:19)\\n    at Proxy.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/managers/AppPermissionManager.js:18:68)\\n    at LivechatRead.isOnlineAsync (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/accessors/LivechatRead.js:18:36)\\n    at IncomingMessages.processRequest (evalmachine.<anonymous>:46:62)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at IncomingMessages.post (evalmachine.<anonymous>:22:13)\",\"message\":\"No permission checker found for the bridge method \\\"AppLivechatBridge.isOnlineAsync\\\"\\nPlease create a new cheker one under the permissionChekers folder to fix the issue.\"}"
]

Any ideas?

**Comment by dudanogueira** [comment]
Same here. This was previously working.

**Comment by dudanogueira** [comment]
I have searched everywhere and this is the only place around that has some reference for this error....
