### ISSUE TITLE
Option to delete Channels in Channel list

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#199]
Every old channel will stay in the channel list, regardless if it is empty or unused. I would like to delete those channels.

**Comment by engelgabriel** [comment]
:+1:

**Comment by engelgabriel** [comment]
Depends on #206

**Comment by marceloschmidt** [comment]
It's still on an early stage, but it's already possible to delete a channel if you go to Administration -> Rooms

**Comment by dstaykov** [comment]
Channel deletion is missing in 0.59.3
1. May be interface  (visual) related.
2. Room/channel edition in "Administratoion\Rooms" is possible only if I change the name of the room/channel

**Comment by zedar187** [comment]
Rocket.Chat 0.59.3

It seems, that the buttons has been hidden by css in the adminstration panel (admin->rooms). If you deactivate the rule "visibility: hidden" in `.flex-tab .channel-settings .button`, the action buttons appear again.

![screenshot](https://user-images.githubusercontent.com/5468685/32606983-94e0386a-c557-11e7-9225-408ba06b4667.jpg)

**Comment by mgroff2** [comment]
@zedar187 Can you please explain further about what you did to make that appear. I am not quite putting it together, but I am experiencing the same issue you solved for. 

What do you mean by "deactivate the rule "visibility: hidden" in .flex-tab .channel-settings .button"? Where do i actually go to make these changes? Sorry if this is a dumb question...

**Comment by dclemmon** [comment]
I tossed the following CSS into our Custom CSS panel as a quick hack to show the buttons without using the browser dev tools.
```css
.button.cancel, .button.primary.save, .button.danger.delete{
  visibility: visible !important;
}
```
