### ISSUE TITLE
Tooltip for SideNav Header Icons

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Rocket.Chat#19908]
### Description:

It would be helpful to have a tooltip corresponding to the icons in the sidenav header similar to the ones displayed for all other icons within Rocket Chat. Some users might find the icons in the sidenav header ambiguous and may realise what it does only after clicking on it.

### Steps to reproduce:

1. Hover over the icons in the sidenav header.

### Expected behavior:

Tooltip to appear similar to the ones for the below shown icons.

![Screenshot from 2020-12-19 22-29-44](https://user-images.githubusercontent.com/28918901/102694947-52da8d80-424a-11eb-9180-d4395c3a6bd3.png)

### Actual behavior:

No tooltip for sidenav header icons.

![Screenshot from 2020-12-19 22-30-02](https://user-images.githubusercontent.com/28918901/102694954-64bc3080-424a-11eb-9418-27ff3241753d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Ubuntu
- Deployment Method:
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.20.0
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Google Chrome
- Operating System: Ubuntu 18.04

**Comment by RonLek** [comment]
I'd love to raise a PR for this and would be grateful if someone could point me to it in the code :)

**Comment by dougfabris** [comment]
@RonLek you can simply pass the title prop to the header action components of the sidebar. Feel free to create your branch and send a PR.

**code locale hint**: client/sidebar/header/actions

**Comment by RonLek** [comment]
Thanks @dougfabris. I'm on it!
