### ISSUE TITLE
fix security patch regression

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1990]
Recent changes have caused regression.

![screen shot 2016-01-20 at 9 35 32 am](https://cloud.githubusercontent.com/assets/122633/12451830/68bbd81c-bf59-11e5-9884-c2a72eec91ba.png)

**Comment by engelgabriel** [comment]
We should have a blacklist of IPs and domains for the previews

**Comment by samhocevar** [comment]
This is tagged security, but there is no description of the bug. How does this affect users?

**Comment by engelgabriel** [comment]
If you have a web service running on the same machine as Rocket.Chat, that does't have password, and a user sends a message with a URL like https://localhost:3000 the system will do a HTTP GET on that address and display the title of the response.

**Comment by Sing-Li** [comment]
👍    or for the security researcher types ....

vulnerability :   bot port scanner against the underlying server or virtualization host
