### ISSUE TITLE
Cant connect to server with mobile apps

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#1991]
I'm running a rocketchat server deployed with docker. i'm using a nginx proxy (jwilder/nginx-proxy) to forward port 80/443 (https: lets encrypt cert) to the rocketchat container. 
acces via browser and via desktop apps is working well, but as it comes to mobile apps, no device (ios, windows phone, android) can get connected. 
"error connecting to the server: error"

**Comment by DmitriyLyalyuev** [comment]
I have same issue, but without error.
I have blank box on centre of screen and text "English Version". 

That's all.

Version of Rocket.Chat 0.13.0 started in docker. Nginx started in docker too.

**Comment by Sing-Li** [comment]
@Julime  - check your connection 

@DmitriyLyalyuev - you have a different problem ... have you changed your ROOT_URL via settings and/or via the system popup detection box  recently?

**Comment by Julime** [comment]
@Sing-Li no problem accessing my rocketchat server via mobile browser, or accessing the demo server

**Comment by Julime** [comment]
https://gist.github.com/Julime/60e7838db5b9bd5fc2f2

**Comment by DmitriyLyalyuev** [comment]
@Sing-Li Sorry, I have an error in Nginx config. Resolved successful.

**Comment by Sing-Li** [comment]
@Julime - on both your iPhone and Android devices - the same one you have trouble with - install Chrome and test to see if you can access the server.

**Comment by Julime** [comment]
@Sing-Li Sorry, I have an error in Nginx config. Resolved successful.

No im serious. selected the wrong cert file. incomplete certificate chain.
