### ISSUE TITLE
Custom OAuth not removed on pressing "remove custom OAuth"

### ISSUE THREAD

**Issue by mvanderwoerd** [RocketChat/Rocket.Chat#19910]
### Description:

Custom OAuth not removed on pressing "remove custom OAuth"

### Steps to reproduce:

1. Go to settings> OAuth section (/admin/OAuth)
1. Click: "add custom OAuth" & add placeholder text "test" into available fields & click "enable"
1. Click: Save Changes
1. Click: refresh OAuth Services
1. Open newly added service named "test" by expanding it and click "remove custom OAuth"
1. Click "save changes" (top of the page)
1. Click: refresh OAuth Services

### Expected behavior:

Newly added OAuth Service named "test" is no longer available

### Actual behavior:

1. Newly added OAuth Service named "test" is still available
1. Any newly added Oauth Service added later, will break (e.g.: no login button displayed on login page)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1  
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Firefox - 83.0 / Chromium - 87.0.4280.66
- Operating System: Linux

### Additional context

Related issue #9920

**Comment by mvanderwoerd** [comment]
@geekgonecrazy 
**This also seems to be broken on version 3.9.2**

### Server Setup Information:
Version of Rocket.Chat Server: **3.9.2**
Operating System: linux
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: enabled
NodeJS Version: v12.18.4
MongoDB Version: 4.0.20

I believe this means that **none of the Open-ID Connect solutions** are working:  
1. [Okta](https://docs.rocket.chat/guides/administrator-guides/authentication/open-id-connect/okta)
1. [Keycloak](https://docs.rocket.chat/guides/administrator-guides/authentication/open-id-connect/keycloak)
1. [Gluu](https://gluu.org/docs/gluu-server/4.0/integration/saas/rocketchat/)

**side note:** 
@Sing-Li It looks like the last 2 images are missing in this article, so I am not sure what those settings are supposed to look like. :)


> Now in order to grant the Rocket.Chat role to a user, we have to modify the users Role Mappings.
> ![User Role Mapping][User Role Mapping]
> The roles are only synced on first login, and not being refreshed on each login. Please see the bug report for current state.
> [User Role Mapping]: user_role_mapping.png

**Comment by mvanderwoerd** [comment]
This hasn't been triaged/ looked at for 18 days, 
so I'll close this and switch to Mattermost.

**Comment by OdinWynd** [comment]
This is still a bug, it has only been partially fixed.
