### ISSUE TITLE
Email notfication link not working

### ISSUE THREAD

**Issue by fabiiretro** [RocketChat/Rocket.Chat#19917]
### Description:

When opening the link (not via deep link gateway) from the email notification, the client shows an error overlay

### Steps to reproduce:

1. enable email notifications
2. click on link

### Expected behavior:

link should redirect to the right message

### Actual behavior:

link redirects to the correct channel/group but does not jump to the correct message and shows a big "room not found" overlay
![Screenshot 2020-12-20 at 21 04 20](https://user-images.githubusercontent.com/4579653/102723230-01dc9f00-4307-11eb-81e7-b85087ba01c9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.2
- Operating System: linux
- Deployment Method: official docker image
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: nA
- Operating System: nA

### Additional context

none

### Relevant logs:

none

**Comment by Gummikavalier** [comment]
Confirming that we are experiencing this issue too at least with direct and private rooms.

**Comment by fabiiretro** [comment]
not sure when and how, but it got fixed since opening this issue
