### ISSUE TITLE
Settings menu doesn't work on Safari 9.0.1

### ISSUE THREAD

**Issue by MaxKK** [RocketChat/Rocket.Chat#1992]
The navigation entries are not loading, it just shows the header "SETTINGS". Clicking on it also doesn't work. 

Chrome works fine.

**Comment by Sing-Li** [comment]
Works on Safari Version 9.0.2 (11601.3.9)     El Capitan

**Comment by graywolf336** [comment]
Along with what @Sing-Li said, are there any errors in the console @MaxKK?

**Comment by MaxKK** [comment]
@Sing-Li I updated and it's working again. Thank you. :) 

@graywolf336 As I updated I can't take a look anymore. 


Problem solved. I will close this thread.
