### ISSUE TITLE
snap install doesn't upgrade

### ISSUE THREAD

**Issue by sneakyx** [RocketChat/Rocket.Chat#19921]
### Description:

The snap install doesn't update the security fix.

### Steps to reproduce:
none-message shows directly

### Expected behavior:

upgrade to min 2.4.14

### Actual behavior:
We're still on version 2.4.11

### Client Setup Information

- Desktop App or Browser Version: Crome/Chromium/Firefox, newest version on OSes
- Operating System: Windows/Mac/Linux

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.11
- Operating System: ubuntu server
- Deployment Method: 
- Number of Running Instances: 1 

Our server is still on 2.4.11 - and we can't install the security fix. This morning I got the "Security alert message".
I thought snap is the recommend way to install rocket.chat, so we installed it that way 2 years ago. Could You please update the snap packages- or do we have the possibility to update ourselves?
Thanks, sneakyx

**Comment by gik000** [comment]
We also are experiencing problems in upgrading rocketchat from version 2.4.11 to version 2.4.14.

Any ideas of how to unstuck this situation?

**Comment by gotton** [comment]
hello,
Are you using a raspberry pi ?
The snap packages on rapsberry pi doesn't received update.

**Comment by sneakyx** [comment]
No, it's a regular ubuntu server.

**Comment by sneakyx** [comment]
our server is now on v2.4.14 - thanks guys for upgrading the snap package!
