### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#1993]
"version": "0.14.0",
  "compile": {
    "date": "2016-01-18T17:22:42.147Z",
    "nodeVersion": "v0.10.40"

A user has created an account, and is still waiting on their initial email. 

SMTP settings are set, but we just tested a user requesting a password change, and they didn't get their email either. 

How can I verify the email was sent from RocketChat?

Has anyone tested with gmail's SMTP settings? (Do ports 465 or 587 work? They don't seem to be with my tests, I've tried both)

My SMTP settings don't require a username and password currently on the local machine, but that doesn't seem to be working either for Rocket.Chat.

When I go into /admin/users and click the + in the top right, I get
"In order to send invitation emails, you must first configure SMTP settings", however this is noted in issue #1883

**Comment by royalaid** [comment]
I too am having issue with SMTP, changing it via the web ui doesn't seem to affect anything, the error returned always seems to be 500 even when other error codes are thrown and the configuration seems to act extremely funny.

**Comment by Sing-Li** [comment]
After changes, try rebooting the server.

**Comment by royalaid** [comment]
Okay, that seems to work for reloading the configs.
