### ISSUE TITLE
Embed video and preview URL's

### ISSUE THREAD

**Issue by lukehinds** [RocketChat/Rocket.Chat#1994]
I have embed set to True under Admin > API, and yet when I post a URL, there is no preview text and also if I post a video URL (from youtube) it just posts the hyperlink.

Am I missing something here, and this is not yet supported or I need to otherwise configure elsewhere?

version: 3.13.0-68-generic

**Comment by Sing-Li** [comment]
Where or how did you install the server?   Does the server have outbound Internet access without proxy?

**Comment by djeber** [comment]
i am having the same problem using apache as a reverse proxy

**Comment by djeber** [comment]
its fixed now by setting it to false and saved than turn it to true and saved than restarted the server

**Comment by Sing-Li** [comment]
yes, many settings currently require restart of the server.

**Comment by lukehinds** [comment]
So the fix is to restart the whole server, and issue is closed. 

I don't mind a workaround, that's ok, but I am guessing you still have a bug here.

**Comment by Sing-Li** [comment]
Definitely dup - at least #1492  work in progress  - also several others.

**Comment by lrodriguezc** [comment]
> I have embed set to True under Admin > API, and yet when I post a URL, there is no preview text and also if I post a video URL (from youtube) it just posts the hyperlink.
> 
> Am I missing something here, and this is not yet supported or I need to otherwise configure elsewhere?
> 
> version: 3.13.0-68-generic

Hello, you have to be sure that the rocket chat server have youtube access allowed on the firewall.

In my case, that whas the solution ;)
