### ISSUE TITLE
[BUG] Pinned Message menu doesn't lose focus

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Rocket.Chat#19952]
### Description:

The menu for the pinned message doesn't lose focus causing it not to close when seen from the Pinned Messages section for a channel. This results in the entire screen getting unscrollable, with the only way out being a screen refresh. Even unpinning the message itself doesn't change anything.

The menu should automatically lose focus and close if the user clicks anywhere outside the menu area or clicks on an action within the menu (similar to what happens for normal messages in any channel).

### Steps to reproduce:

1. Go to the menu for a channel ('...') 
2. Click on 'Pinned Messages'
3. Hover over any pinned message to get the menu ('...') and click on it.
4. Try getting out of there :P

### Expected behavior:

The menu should lose focus either after an action is selected or the user cllicks anywhere outside the menu area.

### Actual behavior:

The screen becomes 'frozen' with only the menu in focus.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/28918901/103013810-c2f75500-4563-11eb-90ab-403bcb49f88f.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Ubuntu
- NodeJS Version: 12.20.0
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Google Chrome
- Operating System: Ubuntu 18.04

**Comment by RonLek** [comment]
I would love to work on this. Any leads would be really appreciated :)

**Comment by Darshilp326** [comment]
@RonLek  i think #19526  would fix this issue!

**Comment by RonLek** [comment]
Thanks @Darshilp326 . On implementing the changes in the mentioned PR, it sure does unpin the messages but the menu doesn't lose focus and close away resulting in the screen to 'freeze' as mentioned in the issue description. Check it out below.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/28918901/103097447-44ff8080-462d-11eb-8151-e5128c721da4.gif)

**Comment by aKn1ghtOut** [comment]
The answer was staring at me right in my face. Had another PR with a similar issue and that helped. The events handling the menu button were bound twice, and the second "rc-popover" element that blocked the page couldn't be removed. Removed the duplicate event binding, and everything works well now!

**Comment by dougfabris** [comment]
@aKn1ghtOut I think the PR solves our problem here. Thank you mate!
