### ISSUE TITLE
I want to change the color of alert based on the type of the message

### ISSUE THREAD

**Issue by mohjam2004** [RocketChat/Rocket.Chat#19963]
### Description:

I use a script to send alerts to rocketchat webhook. All messages have the same side line orange color in rocketchat messages.
How can I change the color based on the type of the message? for example orange for warning and green for info

### Steps to reproduce:

1. I use this script:

![image](https://user-images.githubusercontent.com/59224403/103095660-a405cb00-4616-11eb-8a69-233163fe616e.png)

2. use the flags to send my messages to rocket chat webhook. for example:

-b: text message
-u; webhook url

 rocketchat.sh -b "Info: my text message." -u https://my_rocketchat_webhook_url

### Expected behavior:

The messages with info alerts has green color and warning messages has orange color.

### Actual behavior:

The info message has orange color:
![image](https://user-images.githubusercontent.com/59224403/103095300-66ed0900-4615-11eb-85e1-11412910d58e.png)

The warning message has has orange color:
![image](https://user-images.githubusercontent.com/59224403/103095355-93088a00-4615-11eb-9c80-09c626e56b01.png)
 
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
