### ISSUE TITLE
Embed a rocket chat stream of a channel into a webpage.

### ISSUE THREAD

**Issue by Superhearing** [RocketChat/Rocket.Chat#1996]
The idea would be to enable viewers of a page such as mysite.com/topic2 to view what is happening in channel #topic2. 

The div layout would look something like:

| menu |
| --- |
| page content |
| rocket chat room stream |

In other words, the ability to embed a rocket chat channel into a webpage.

It would not require full functionality as the idea would be that when the user clicks the channel div then they are taken to the full app such as chat.mysite.com

If anyone has any ideas on how this might be implemented please let me know.

Cheers

**Comment by IQ2022** [comment]
:+1: so basically like having twitter feed (like  a widget).. perhaps we can also measure what is trending if enough hash tags used or CASH tags ;) in case of stocks

**Comment by Superhearing** [comment]
I am still looking for this functionality, anyone know how it could be achieved?

**Comment by Perksls** [comment]
I think you can add ?layout=embedded to the end of the channel url and wrap it in an iframe, right?

**Comment by c-thomasFR** [comment]
Does anyone know how to automatically login a user in the iframed rocket.chat, ?

I have used "https://xxx.xxx.xx:3000/api/v1/login" and getting the success in response
stdClass Object ( [status] => success [data] => stdClass Object ( [authToken] => BPT8Gt4k2fbUZjtQDfENtKawa41ZwwwmbV6KH-_kL8akvT [userId] => dSZ38wjgPD33irls4L6Y ) )

how should i use this response further to achieve above goal.

Thanks for your help

**Comment by ENEUE** [comment]
Any news on this? I'm interested in doing the same as @Superhearing

**Comment by Superhearing** [comment]
@ENEUE you might want to add to this bounty https://www.bountysource.com/issues/26280752-allow-anonymous-use-of-the-chat

**Comment by wmzy** [comment]
Is this what you're looking for?

![image](https://user-images.githubusercontent.com/5526525/33010036-f5a833f4-ce13-11e7-95b5-e0a5d5a8fc89.png)

**Comment by geekgonecrazy** [comment]
This is actually possible via iframe.  You can use the layout query param to restrict to embedded which wouldn't have the channel list, instead just the channel

**Comment by Superhearing** [comment]
@geekgonecrazy but the a viewer would need an account and to login right?

**Comment by geekgonecrazy** [comment]
Not if you enable anonymous read
