### ISSUE TITLE
[BUG] Inconsistency in number of replies to a message after deletion of replies

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Rocket.Chat#19964]
### Description:

If a user deletes the replies to a message in thread the number of replies shown for the message remain the same even if replies are deleted. Either a "Message Removed" should be shown for the reply deleted or the count of replies should by updated after a reply is deleted.

### Steps to reproduce:

1. Hover over a message and click on "Reply in thread".
2. Type anything and reply to the message.
3. Hover over your reply and click on Delete from the menu.

### Expected behavior:

The number of replies to the message should be decremented by one or a "Message removed" in place of the deleted reply should be displayed in the thread.

### Actual behavior:

The number of replies is neither decremented nor a "Message removed" is shown causing inconsistent behavior.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/28918901/103098154-bd674100-462f-11eb-8d34-447110e3b7c7.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Ubuntu
- NodeJS Version: 12.20.0
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Google Chrome
- Operating System: Ubuntu 18.04

**Comment by adrianovieira** [comment]
This error also happens here for server version 3.10.4

![image](https://user-images.githubusercontent.com/5561794/104919348-ddf79200-5974-11eb-912a-8b679ad18be6.png)

**Comment by yash-rajpal** [comment]
@dougfabris Please review my PR linked for this issue. It resolves it.
