### ISSUE TITLE
TypeError: Cannot set property 'subscriptionInfo' of undefined

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#19972]
### Description:

Why do I have this error in exceptions channel?

### Steps to reproduce:

1. Nothing. Just Have enabled exceptions to channel

### Expected behavior:

Nothing in exceptions channel

### Actual behavior:

![image](https://user-images.githubusercontent.com/11560794/103172876-f9301f80-4856-11eb-92c4-c4f2d5ea477d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.3 but it started some versions ago.
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 3 
- DB Replicaset Oplog: yes
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.19

### Client Setup Information

- Desktop App or Browser Version: any
- Operating System: any

**Comment by sampaiodiego** [comment]
Looks like an old issue related to Apps.

I'll close the issue.. Please let me know if still happening on newer versions, I can re-open the issue then.
