### ISSUE TITLE
No translations for error message.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#19973]
### Description:

Error messages are not translated into preferred language
### Steps to reproduce:

1. Go to User Profile
2. Select Preferences
3. Select  your preferred language

### Expected behavior:
Error message should be translated into preferred language.

### Actual behavior:
Error messages are in english language only.

https://user-images.githubusercontent.com/55157259/103174888-da984b80-488b-11eb-8fb5-04c4e4e8d748.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

**Comment by Darshilp326** [comment]
Please help me to solve this issue!

**Comment by yash-rajpal** [comment]
I am not able to play the video you uploaded.
