### ISSUE TITLE
Update Rocket.Chat

### ISSUE THREAD

**Issue by 123qwealex** [RocketChat/Rocket.Chat#19970]
Unable to update the Rocket version.Chat up to 3.1.1. Where to find links to download the current version.On the Rocket website.Chat has a version for windows 3.0.6.

Steps to reproduce - Runs on the update screen.
Expected behavior - It should go to the site where you can download the latest version or the latest version should immediately download and install itself and at the same time it should be written in the application that you need to restart the application so that you can use the latest version of Rocket.Chat
Actual behavior - When you click on install update, nothing happens at all.
Server Setup Information - The Server is configured and works correctly on other versions of Rocket.Chat
Version of Rocket.Chat Server - Version 3.1.0

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Hyperion2400** [comment]
I use the Windows App and also have the problem that the update dialog just keeps popping up.
If I click on 'Install Update' it says it will notify me after the update is downloaded but it never does.
If I click on 'Skip Version' it keeps asking me again after a restart.

![image](https://user-images.githubusercontent.com/34254020/103751165-2a9fac80-5008-11eb-878b-57296ae21160.png)

**Comment by MartinSchoeler** [comment]
Hey, I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
