### ISSUE TITLE
When upgrading from 0.11 to a newer version (docker) the sidebar is empty

### ISSUE THREAD

**Issue by timothyparez** [RocketChat/Rocket.Chat#1997]
When upgrading from 0.11 to a newer version using `docker pull rocketchat/rocket.chat:develop`  
the sidebar will be empty except for the 'history' link. Which we can then use to find previous  
conversations and talk to others.

So far I tried upgrading to 0.13 and 0.14 with the same result.
When reverting back to the older docker image, everything works as expected again.

While typing this I just found this in the chat:

![image](https://cloud.githubusercontent.com/assets/2060470/12473454/20856a46-c04d-11e5-881e-9a1376d2bd67.png)

Would be great if someone could post that "fix" here.

**Comment by pcarn** [comment]
I am experiencing this as well.

**Comment by pcarn** [comment]
@geekgonecrazy

**Comment by geekgonecrazy** [comment]
@timothyparez yes this is an issue with the migration process.  I haven't had a chance to write up a troubleshooting guide... 

You need to run this against your mongo database.

```
db.migrations.find().sort({"_id":1}).skip(0).limit(30)
```

Is your mongodb running in docker as well?

If so you can connect like this:
```
docker run -it --link db:db mongo /bin/bash
```

Replace the first the first db in the link with the name of your mongo container.

Then run:
```
mongo db:27017
```

Bringing you into a mongo shell:

```
use meteor
```

replace meteor here with the name of the database you use in your `MONGO_URL=mongodb://host/{database} when starting Rocket.Chat`

Then... run the query above.  :)  We need to know what it spits out.

**Comment by timothyparez** [comment]
Hi,

The output is as follows:

     > db.migrations.find().sort({"_id":1}).skip(0).limit(30)
     > { "_id" : "control", "version" : 26, "locked" : true }

**Comment by geekgonecrazy** [comment]
@timothyparez ok so your migration failed the last time.  We need to remove the lock.

Do:

```
db.migrations.update(  { _id: "control"} , { $set: { locked : false  } })
```

Then restart the container.

Take a peek at the logs while it starts up and make sure no errors happen.  Also recheck the lock after to make sure its not locked again.  :)

To check log output of the docker container do:

```
docker logs -f {name of your rocket.chat container}
``` 

We're going to look at adding some UI to inform people of this happening.  Hopefully this fixes it for you.  If you need help troubleshooting too, feel free to hit me up on the [demo server](https://demo.rocket.chat).

**Comment by timothyparez** [comment]
That worked like a charm!
Thank you for the detailed explanation, really helped.

**Comment by geekgonecrazy** [comment]
@timothyparez no problem, glad I could help!
