### ISSUE TITLE
[BUG] Profile picture changes with change in username for a user

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Rocket.Chat#19975]
### Description:

As and when the username for a user is changed, the user's corresponding profile picture also changes automatically. In case the user justs wants to change her username she would have to re-upload her profile picture back again unless she selects her current profile picture from the right every time before changing the username.

Moreover, if an existing username is typed, that user's profile picture appears. Only a message saying "Username already exists" would suffice without changing the profile picture. 

### Steps to reproduce:

1. Click on your profile picture on the top-left.
2. Select My Account.
3. Edit your username.

### Expected behavior:

The profile picture remains the same and only the username changes. If an already taken username is entered, the profile picture of that user shouldn't appear.

### Actual behavior:

The profile picture changes as and when the username changes. On clicking "Save Changes" the changed profile picture appears.

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/28918901/103178608-4be6f700-48aa-11eb-943a-92d218fd3544.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Ubuntu
- NodeJS Version: 12.18.2
- MongoDB Version: 4.4.2

### Client Setup Information

- Desktop App or Browser Version: Google Chrome
- Operating System: Ubuntu

**Comment by b2pacific** [comment]
Can I work on this issue?

**Comment by iamtushar324** [comment]
Sir, Should the suggestion avatar image change with the change in the username or it should also be fixed.

**Comment by MJPGPleasant** [comment]
Looks like it may be addressed in Rocket.Chat 3.10. Noted that the default avatar changes letter (not colour) as appropriate only after saving, and custom avatars are left intact.

**Comment by iamtushar324** [comment]
> Looks like it may be addressed in Rocket.Chat 3.10. Noted that the default avatar changes letter (not colour) as appropriate only after saving, and custom avatars are left intact.
Ok Got it

**Comment by iamtushar324** [comment]
Please Review My fix https://github.com/RocketChat/Rocket.Chat/pull/19991

**Comment by iamtushar324** [comment]
https://user-images.githubusercontent.com/54494629/103301796-2122ad00-4a28-11eb-937f-03b8731e9f45.mov

**Comment by gabriellsh** [comment]
I believe the Default avatar "suggestion" should always show the color and letter changing, but the actual profile pic should only change when one of the buttons is clicked.
