### ISSUE TITLE
Github login requires email to be public

### ISSUE THREAD

**Issue by est31** [RocketChat/Rocket.Chat#200]
The log in with github button requires that the e-mail is public. The application should rather ask for the e-mail through the github API, then users with non-public e-mails can log in, too.

**Comment by engelgabriel** [comment]
:+1: 

We will make the whole email "thing" optional.

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by engelgabriel** [comment]
Depends on #250

**Comment by marceloschmidt** [comment]
Closed by PR #515
