### ISSUE TITLE
Improve push notifications by not forward content to third parties (Google/Apple)

### ISSUE THREAD

**Issue by litewhatever** [RocketChat/Rocket.Chat#2000]
Please improve Rocket.Chat in a way that the content of the message isn't going through third parties (e.g Google, Apple etc) when push notification is enable.

For some of us this might be important as we may have rules which prohibit sending data to third parties.

I shared some thoughts about this issue with @Sing-Li 

> sing.li 3:21 PM 
@kristjan.kullerkann: you are correct on all counts. Do I understand correctly that Rocket.Chat is using Google Cloud Messaging for Android and Apple Push Notification Service for IOS? yes
And there is also a possibility to use Rocket.Chat gateway which in the end uses also Google Could Messaging and/or Apple Push Notification Service? yes
Does this mean that messages them self are also going through Google/Apple? the content of the message (at least the first part) is the subject of the notification
Or this is not the case - GCM is just notifing the device to pull new messages? the content of the message (at least the first part) is the subject of the notification ... for your requirement - please open a new issue to have an option to _not send the actual message content
 the content of the message (at least the first part) is the subject of the notification ... for your requirement - please open a new issue to have an option to _not send the actual message content_

**Comment by tuudik** [comment]
:+1:

**Comment by engelgabriel** [comment]
Thats should be relatively easy to have a setting to define the format/content of the push notifications.
