### ISSUE TITLE
Jitsi does not work in latest update

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#20002]
### Description:

Before I could only get jitsi to work if open in new window was enabled (See: https://github.com/RocketChat/Rocket.Chat/issues/19782 ) but now as of 3.10.0 calls do not work at all. 

### Steps to reproduce:

1. Enable Jitsi
2. Attempt to place calls

### Expected behavior:
Jitsi calls function as before
### Actual behavior:

Placing a call does nothing, a blank white "call" tab opens, no "click to join" notification appears. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version:  v3.6.3

### Client Setup Information

- Desktop App or Browser Version:  3.0.7
- Operating System: Fedora and Windows 10

**Comment by Ismaw34** [comment]
Just to add some logs here:
On Firefox 84.0.1 it gives this error on the javascript side:

`TypeError: 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    t https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1637
    i https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _withTemplateInstanceFunc https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    i https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    constructView https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    n https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    nonreactive https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1357
    _fireCallbacks https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _withCurrentView https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _fireCallbacks https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _createView https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _materializeView https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    t https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _materializeDOM https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _materializeDOM https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    _materializeView https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    nonreactive https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1357
    _materializeView https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    render https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    renderWithData https://localhost/027988dc7bd96e79e89997a5652bdb13cb80a2e7.js?meteor_js_resource=true:1432
    l /client/views/room/components/BlazeTemplate.js:1
027988dc7bd96e79e89997a5652bdb13cb80a2e7.js:1637:550779
`

**Comment by Attack44** [comment]
I have the same problem with this version.

**Comment by drummer73** [comment]
Same here with Rocket.Chat Server 3.10.0

**Comment by kalexnolasco** [comment]
I have the same problem with this version.!!!

**Comment by lemmings67** [comment]
Same issue here !

**Comment by samouraiwallet** [comment]
We are also seeing this issue on the latest version (3.10.0)

We do not see any javascript errors in the debug console

**Comment by adolfombarros** [comment]
Same issue here (Firefox and Chrome)
RocketChat 3.10.0
MongoDB 4.0.20

**Comment by aminvakil** [comment]
Same issue here running both rocketchat and jitsi on docker.

**Comment by riantasolutions** [comment]
Same issue:

Rocket.Chat v3.10.0
Node v12.18.4
Mongo v4.0.17
Manual install under CentOS 7
Problem exists in Desktop client 3.0.9, 3.1.0, 3.1.1, Firefox, Chrome (normal and icognito)
- checked both Firefox and Chrome permissions to allow popups, notifications, etc.

**Comment by pmp02** [comment]
Same issue (Chrome, Windows Desktop client)

Electron Client 3.1.0
Rocket.Chat v3.10.0
Node v12.18.4
Mongo 4.0.22
Docker installation

**Comment by samir-s** [comment]
Same here. 

Anyone knows how to add unit testing for this use case in the coverage test ? 

It's the second time we're experiencing this feature break and using jitsi through RC is critical for our crew since all our videoconference meeting are managed through RC/jitsi. It definitely breaks our workflow.

**Comment by riantasolutions** [comment]
Hi all,

v3.9.4 seems to work fine.  I downgraded two days ago and issue is resolved.

FYI.

**Comment by martinszy** [comment]
Same here. 

Rocket Serve version 3.10.0
Rocket Snap 3.0.1.

Please fix.

**Comment by EnCz** [comment]
> Same here.
> 
> Anyone knows how to add unit testing for this use case in the coverage test ?
> 
> It's the second time we're experiencing this feature break and using jitsi through RC is critical for our crew since all our videoconference meeting are managed through RC/jitsi. It definitely breaks our workflow.

Same here, pretty annoying.

**Comment by martinszy** [comment]
Downgrading worked fine 3.9.4 does not have the issue. I Think we can't upgrade until this is fixed. Too bad.

**Comment by aminvakil** [comment]
@riantasolutions @martinszy are you sure downgrading doesn't break something?

**Comment by riantasolutions** [comment]
I always back up first.  😁 

No issues so far, with 100+ users who use Jitsi integration extensively.

FYI.

**Comment by aminvakil** [comment]
I can confirm downgrading to 3.9.4 fixed the issue for me too.

**Comment by mmgoilf** [comment]
3.10.3 seems to have fixed this issue. But #19782 is still an issue. Closing for now.

**Comment by reboot523** [comment]
这个问题在7.0.0再次出现.
