### ISSUE TITLE
Docker 3.10.0 image showing as 3.9.2 in image

### ISSUE THREAD

**Issue by distek** [RocketChat/Rocket.Chat#20001]
### Description:
Not sure if I'm just doing something wrong, but from what I can tell, the docker image is showing the incorrect version number.

Showing: 3.9.2
Expected: 3.10.0

Docker logs output at end of issue

### Steps to reproduce:

```
docker container stop rocketchat
docker container prune
docker image prune
docker pull rocketchat/rocket.chat:3.10.0
docker run --name rocketchat -p 127.0.0.1:3000:3000 --link db --env ROOT_URL=https://redacted.domain.tld --env MONGO_OPLOG_URL=mongodb://db:27017/local -d rocketchat/rocket.chat:3.10.0
```

### Expected behavior:

Server reflects version 3.10.0 and rocket.cat stops yelling at me.

### Actual behavior:

Server reflects version 3.9.2 and rocket.cat continues to yell at me.
### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0 _supposedly_ ;)
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Unsure on how to get this
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

### Relevant logs:

```
[root@redacted ~]# docker run --name rocketchat -p 127.0.0.1:3000:3000 --link db --env ROOT_URL=https://redacted.domain.tld --env MONGO_OPLOG_URL=mongodb://db:27017/local -d rocketchat/rocket.chat:3.10.0
7e65b653ca554a201bcb5a08a539145f2832769457118b64b913b4111c54873f
[root@redacted ~]# docker logs rocketchat --follow
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 212","time":{"$date":1609279499522},"level":"info"}
Loaded the Apps Framework and loaded a total of 1 Apps!
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Updating process.env.MAIL_URL
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
➔ System ➔ startup
➔ +---------------------------------------------------+
➔ |                  SERVER RUNNING                   |
➔ +---------------------------------------------------+
➔ |                                                   |
➔ |  Rocket.Chat Version: 3.9.2                       |
➔ |       NodeJS Version: 12.18.4 - x64               |
➔ |      MongoDB Version: 4.0.21                      |
➔ |       MongoDB Engine: wiredTiger                  |
➔ |             Platform: linux                       |
➔ |         Process Port: 3000                        |
➔ |             Site URL: https://redacted.domain.tld |
➔ |     ReplicaSet OpLog: Enabled                     |
➔ |          Commit Hash: 1f55d43ac8                  |
➔ |        Commit Branch: HEAD                        |
➔ |                                                   |
➔ +---------------------------------------------------+
```

**Comment by MJPGPleasant** [comment]
Try `docker pull rocketchat/rocket.chat:latest`

I did this this morning and updated to 3.10 using `docker-compose` without issue.

**Comment by distek** [comment]
@MJPGPleasant Should have mentioned that. Tried with `latest` and `3.10.0`, same result. If you're getting it to show `3.10.0` though, it's probably something I'm doing.

Gunna keep fighting it for a bit. I'll close this if I happen to resolve the issue myself.

**Comment by distek** [comment]
Somehow managed to make just everything worse. DB's now screwed and I currently hate MongoDB. Closing this.
