### ISSUE TITLE
Best Practices to add Rocket Chat to any Website

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2001]
Hello, Would like to your feed back on what is the best way to add/integrate Rocket chat to any website, wordpress or non-word press. without losing the responsiveness and no impact to mobile experience? Currently i have it embedded with ifram but what is the best size? Just wanted some feed back.. :)

We can also have POP up windows but then we need people to still see main site - like right now with rocket.chat with a separate domain URL, users wont have access to the main page links, blogs  etc..

Anyone have examples, on how they added rocket.chat to their sites?

**Comment by IQ2022** [comment]
another idea to probably bypass embedding rocket.chat inside a website with iframe, is to utilize the left corner!! and create multiple assignable buttons?  

![image](https://cloud.githubusercontent.com/assets/12454319/13437687/7f15a442-dfb3-11e5-9c5d-5d6fd4086157.png)

**Comment by notsoluckycharm** [comment]
Hey @IQ2022 

You embedded it in an iframe, but did you master SSO? Or you didn't bother? I'm trying to integrate it into an iframe within my site, but I'd like to bypass the user login portion of it because I'll already have a user I can use.

What was your approach?

**Comment by IQ2022** [comment]
Yes i did embedded it, however given my website is running on http (shared www.bluehost.com/track/iqlinx/bluehost ).. so voice/video wont be working as it require https.. so probably in the end we need to have the SSO or wordpress login integrated with rocket.chat -I will be working on getting that setup.. here is how it looks so far, i welcome any feedback.. seekingoptions.com

**Comment by IQ2022** [comment]
maybe one strategy if we don't use iframe is to have the session closes once someone log out or close browser and must come back to site to login?

**Comment by zxy30** [comment]
I have the same problem: I already have a userid and password in my site, I'd like to skip the login portion.

**Comment by chodges** [comment]
Has anyone figured out how to bypass the login portion seamlessly?  I'm at the same point you guys are.  Great platform except for seamless integration.

**Comment by notsoluckycharm** [comment]
Yeah,

We create a meteor method that we called when the application first loads (
/login ) that would call the following functions in the
client/routes/router.coffee

FlowRouter.route '/login',
name: 'login'
action: ->
readToken = (name) ->
// YOUR CODE HERE
Meteor.call('dojoAuth', readToken(), (err, x) ->
localStorage.setItem('Meteor.userId', x.userId )
localStorage.setItem('Meteor.loginToken', x.token.token )
localStorage.setItem('Meteor.loginTokenExpires', new Date(x.token.when).
toString() )
return FlowRouter.go 'home'
)
On the server side the MeteorMethod would determine if the user should be
authenticated. This could be as easy as setting a localStorage token that
you pass from your main app to the meteor app. This token then gets passed
to meteor and you can check if the token is valid and send the user session
back to the meteor font end.

Meteor.methods({
dojoAuth: function (cookie) {
// GET YOUR USER HERE


Accounts._insertHashedLoginToken(user._id, hashStampedToken);
future.return({
token: stampedLoginToken,
userId: user._id
});
}).run();

**Comment by chodges** [comment]
Hi notsoluckycharm!  Thanks so much for the feedback.  I'm a total novice when it comes to Meteor development.  Can you tel me where I would put the code you listed:

FlowRouter.route '/login',
name: 'login'
action: ->
readToken = (name) ->
// YOUR CODE HERE
Meteor.call('dojoAuth', readToken(), (err, x) ->
localStorage.setItem('Meteor.userId', x.userId )
localStorage.setItem('Meteor.loginToken', x.token.token )
localStorage.setItem('Meteor.loginTokenExpires', new Date(x.token.when).
toString() )
return FlowRouter.go 'home'
)

Does this go in my own Javascript or would I have to modify the RocketChat code itself?

Thanks

**Comment by notsoluckycharm** [comment]
client/routes/router.coffee

**Comment by chodges** [comment]
Thank you!

**Comment by neha1deshmukh** [comment]
Hey hi,

Could you please elaborate little bit more with short example how i can fix below issue

Goal: using Rocket.Chat inside my website inside an iframe.
Issue: how to login a user simultaneously on my website and in iframed rocket.chat, without having them to log-in two times ( one in my website and one in the iframe )?

What I want to accomplish is: a user login in in my website and in a transparent way it gets logged in inside the iframe too. 

I have used "https://xxx.xxx.xx/api/v1/login" and getting the success in response 
stdClass Object ( [status] => success [data] => stdClass Object ( [authToken] => BPT8Gt4k2fbUZjtQDfENtKawa41ZwwwmbV6KH-_kL8akvT [userId] => dSZ38wjgPD33irls4L6Y ) )  

how should i use this response further to achieve above goal.  

An i am not able to locate client/routes/router.coffee also :(

**Comment by c-thomasFR** [comment]
@neha1deshmukh I have the same problem, does anyone have a solution ? Thanks for your help

**Comment by j2ro** [comment]
I'd really like to know how to do this too.

If anyone has any help or a guide it would be massively appreciated.

**Comment by deanjansen** [comment]
I'm similarly curious if this is possible, thanks!

**Comment by jerrykwn** [comment]
Please share the solution if you got it. Thanks

**Comment by jerrykwn** [comment]
@notsoluckycharm  , Could you please take a look again? Rocket.Chat was converted to JS, no more Coffee script. I tried to convert your CS to JS, seems it has syntax error. Thanks for help.

**Comment by kieran-rocks** [comment]
+1

**Comment by jerrykwn** [comment]
Actually, 1. please take a look this comment https://github.com/RocketChat/Rocket.Chat/issues/8781. it will help to understand what those fields should be filled. 
2. Then implement code (I am using Rest call to Rocket.Chat) in your API side to grab/return login token from Rocket.Chat. it works.  (Still do not understand it?, you may have to read Login Code in Rocket.Chat)
Of course. then others CROSS DOMAIN issues will follow up.

**Comment by geekgonecrazy** [comment]
Not much discussion on this one in a while.  We are moving all discussions over to the forums where discussions are more appropriately suited.  Please feel free to resume there:  https://forums.rocket.chat
