### ISSUE TITLE
Change stream does not need db admin priviledge

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#20017]
### Description:

Currently:
 - it is stated in the log that change stream requires db admin
 - it is stated [here](https://docs.rocket.chat/installation/manual-installation/mongo-versions) in the doc that it requires clusterMonitor

but these requirements are too much, readWrite should actually be enough.

The code defining this is here:
https://github.com/RocketChat/Rocket.Chat/blob/master/app/models/server/models/_oplogHandle.ts#L31
With this line, it actually needs clusterStatus action, this is true, but it is only needed to detect engine and version. Where as chage stream is available with readWrite role only.

To have changeStream, Actions needed are `find` and `changeStream`
https://docs.mongodb.com/manual/changeStreams/#access-control

And they are available in the read role (which is embeded in the readwrite role)
https://docs.mongodb.com/manual/reference/built-in-roles/#read

### Steps to reproduce:

1. Have a rocketchat with readWrite and oplog user with read roles 
2. start rocket chat

### Expected behavior:

It should setup and use change stream.

### Actual behavior:

Log is saying:
`Change Stream is available for your installation, give admin permissions to your database user to use this improved version`

And it uses oplog which is currently [broken](https://github.com/RocketChat/Rocket.Chat/issues/19905).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Deployment Method: k8s
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- MongoDB Version: 4.2.3-4

### Workaround

https://github.com/RocketChat/docs/pull/1853

**Comment by codeneno** [comment]
may be 'Change stream' is a bad design
https://github.com/RocketChat/Rocket.Chat/issues/20027
