### ISSUE TITLE
Inviting users is not possible with simple SMTP settings!

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#2002]
This issue I think is related to https://github.com/RocketChat/Rocket.Chat/issues/1883
 when an admin is trying to invite users they will get a message saying they cannot since SMTP is not set and that because `emailEnabled` is false. SMTP works fine but I use a local server with no username and password.

![rocket](https://cloud.githubusercontent.com/assets/432460/12495510/19504456-c05e-11e5-8336-51db9a966b12.png)

That value is set here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-admin/admin/users/adminInviteUser.coffee#L4

```coffeescript
emailEnabled: ->
		console.log 'emailEnabled', RocketChat.settings.get('MAIL_URL') or (RocketChat.settings.get('SMTP_Host') and RocketChat.settings.get('SMTP_Username') and RocketChat.settings.get('SMTP_Password'))
		return RocketChat.settings.get('MAIL_URL') or (RocketChat.settings.get('SMTP_Host') and RocketChat.settings.get('SMTP_Username') and RocketChat.settings.get('SMTP_Password'))
```
It still mandates the username and password but I thought the fix in https://github.com/RocketChat/Rocket.Chat/pull/1904 will at least set the "MAIL_URL" value and that would be enough but it seems both sides return false or nothing!

* The console returns "emailEnabled" only without false or true

So what do you guys think? 
Should we just remove the username & password from this check?
but why MAIL_URL is not seen here? or does this file get executed before that value is set!

**Comment by fduraibi** [comment]
@marceloschmidt can I get your feedback on this?

**Comment by marceloschmidt** [comment]
You're right @fduraibi I'll check other places requiring username for smtp server.
Thanks.
