### ISSUE TITLE
Pushing Content to Forum/Blog

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2003]
Not sure if the current Rocket.Chat has the feature to enable one room to post whats written on there to a forum or a blog post (we would need to set a title inside rocket chat) and with that a new topic is opened up and posts directly to a forum like - https://nodebb.org/, https://www.discourse.org/, Flarum, Vanilla etc.

**Comment by graywolf336** [comment]
If you used outgoing webhooks, you could do something like this with your own integration.

**Comment by engelgabriel** [comment]
Depends on #2426

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this because, quite obviously, this is something that can be done via integrations (at least today, not sure if this was the case in January 2016).

Cheers
Thomas
