### ISSUE TITLE
Status and info is only shown for the first user in direct message between multiple users

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#20040]
### Steps to reproduce:

1. Go to https://open.rocket.chat/
2. Click on pen button in the left panel, choose `Direct messages`
3. Choose several users
4. Click `Create` blue button
5. In the top right corner click `User info` button
6. See that despite having multiple users, the info is shown only for the first user in the list.

### Expected behavior:

See avatars, usernames and statuses for all users in the conversation.

### Actual behavior:

![image](https://user-images.githubusercontent.com/11751017/103538465-88ac8280-4e96-11eb-8210-efb53cfd9c62.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: browser version
- Operating System: Windows

**Comment by diegolmello** [comment]
Also, it looks like `getUsersOfRoom` doesn't return anything for Group DMs.

Private group:
![image](https://user-images.githubusercontent.com/804994/103676910-6da64500-4f60-11eb-8154-9810ab46b599.png)

Group DM:
![image](https://user-images.githubusercontent.com/804994/103676954-7c8cf780-4f60-11eb-82e7-f82b19152f78.png)

**Comment by dougfabris** [comment]
@zdumitru Thanks for reporting, this issue was fixed here: #21452 and introduced in the 3.16.0 version
