### ISSUE TITLE
Unable to upload files (w/ extended "Valid metadata types")

### ISSUE THREAD

**Issue by jasperla** [RocketChat/Rocket.Chat#2004]
Uploading an `.odt` file failes with the "unsupported media type" error (which could also show the actual metadata type?).
Through `file(1)` I see that that metadata type of the file is: `application/vnd.oasis.opendocument.text`. Adding it to the list of valid metadata types in `File Upload` still doesn't allow me to upload it and I keep getting the initial error.

*edit*: uploads are enabled, the filesize doesn't exceed the set maximum and uploading a `.txt` works fine.

**Comment by Sing-Li** [comment]
After changing the settings.  Please try rebooting the server and upload. 

If it works - please close this issue.

**Comment by jasperla** [comment]
Hi, indeed it requires a restart of the application. I'd rather not just close this issue as it's completely non-obvious that a service restart is required for that change to take effect.
Shouldn't this be made clear somehow in the `File Upload` pane? Perhaps after the "Comma-separated list of media types"?

**Comment by Sing-Li** [comment]
Dup #1492. And various others.

**Comment by jasperla** [comment]
Ah, thanks. Is there perhaps (other) documentation where I could have found this?

**Comment by Sing-Li** [comment]
No sorry. We are moving miles a minute with limited resources. 

You are, as with all open source projects, encouraged to search open issues before submitting new ones; and search closed issues for quick support answers.
