### ISSUE TITLE
Can't remove users from channels

### ISSUE THREAD

**Issue by EnCz** [RocketChat/Rocket.Chat#20058]
### Description:

Since one of the last updates (3.9.3 / 3.10.0) we cannot remove users from channels / private groups anymore.
We use LDAP and sync accounts from ldap-groups to Channels but we can reproduce this error even on manually created private groups.

### Steps to reproduce:

1. Create new private group with another person
2. Open "Members"
3. Click on other person
4. 3-Dot -> Remove from room

### Expected behavior:

User gets removed

### Actual behavior:

User doesn't get removed and:
![image](https://user-images.githubusercontent.com/7642122/103628787-c74a4780-4f3f-11eb-8e5c-74f0698b3e83.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Everywhere
- Operating System: All

**Comment by EnCz** [comment]
FYI: I just kicked the person succesfully via curl:
curl -H "X-Auth-Token: [insert_your_token]"      -H "X-User-Id: [insert_your_id]"      -H "Content-type: application/json"      https://rocketchat.bz-medien.de/api/v1/groups.kick      -d '{ "roomId": "[insert_room_id]", "userId": "[insert_user_id]" }'

So it seems like the problem is within the sidebar itself (which probably isn't using this API call correctly)

**Comment by EnCz** [comment]
FYI: I just kicked the person succesfully via curl:
`curl -H "X-Auth-Token: [insert_your_token]"      -H "X-User-Id: [insert_your_id]"      -H "Content-type: application/json"      https://[insert_url_here].de/api/v1/groups.kick      -d '{ "roomId": "[insert_room_id]", "userId": "[insert_user_id]" }'`

So it seems like the problem is within the sidebar itself (which probably isn't using this API call correctly)

**Comment by EnCz** [comment]
2nd FYI: This is 100% reproducible even on open.rocket.chat

**Comment by EnCz** [comment]
And here is the reason. The userId doesn't get sent to the api:

![image](https://user-images.githubusercontent.com/7642122/103665658-f5497f00-4f73-11eb-8919-bcdbfb692982.png)

**Comment by Darshilp326** [comment]
Working on it!

**Comment by northway** [comment]
I'm also having this issue, even though my instance is on version `3.12.3`.

We're using SAML instead of LDAP!

<img width="414" alt="Screenshot 2021-04-06 at 16 01 40" src="https://user-images.githubusercontent.com/3431401/113723792-fcf2fe00-96f1-11eb-8e21-614f2bddbc13.png">
