### ISSUE TITLE
Logo does not render in Shields badge 

### ISSUE THREAD

**Issue by HariAcidReign** [RocketChat/Rocket.Chat#20056]
### Description:

The Official RocketChat logo does not render on the Shields.io badge in the "Community" section of readme.md

### Steps to reproduce:

1.  Go to Readme.md 
2.  Scroll down to the Community subheading. 
3.  The RocketChat icon is not loading.

### Expected behavior:

 The icon to be displayed on the left side of the badge
![image](https://user-images.githubusercontent.com/58134096/103604022-fa87d900-4f35-11eb-9f2c-2017f95342f7.png)

### Actual behavior:

The icon is not getting displayed on all web browsers, even in incognito mode. Does not show in the Github mobile app as well.

![image](https://user-images.githubusercontent.com/58134096/103603094-bf84a600-4f33-11eb-9129-8c0dbfddc373.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.4
- Operating System: Windows 10
- Deployment Method:  Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version:  v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Latest Chrome Version 87.0.4280.88 
- Operating System: Windows 10

### Additional context

This is my first contribution to Rocketchat 😄  , and I would love to learn and improve my contributions here. If this is a legitimate issue, I would like to be assigned to resolve this issue. Do let me know of any suggestions or changes and I will implement them immediately.

**Comment by wreiske** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/14820

**Comment by HariAcidReign** [comment]
@wreiske Thanks for pointing it out, but the problem still exists right? Wouldn't this PR fix it? I'll close this issue soon

**Comment by wreiske** [comment]
This pr is just masking the problem with the shields not displaying correctly in the documentation.  The underlying problem with the shields not working correctly is still an issue and fixing that would also fix this issue. 

E.g. If you can resolve the duplicate issue linked above, this issue would no longer exist.

**Comment by HariAcidReign** [comment]
Understood. But there seem to be some hiccups in resolving that issue, and this PR would solve the issue for now. I'll close this issue now, but let the PR be.
