### ISSUE TITLE
How can I hide users in chat?

### ISSUE THREAD

**Issue by mikonoid** [RocketChat/Rocket.Chat#2005]
When I try add direct chat for different user, I enter in find form any symbol and I see users list. How to make hide all users in rocket chat and make private chat open when I entered full username?

**Comment by graywolf336** [comment]
I don't follow what you're asking, mind rephrasing it? Thanks

**Comment by mikonoid** [comment]
I want to see a list of users not all users in finding form. I mean hide userlist for all users.

**Comment by geekgonecrazy** [comment]
Please reach out in our [#support](https://demo.rocket.chat/channel/support) and we'll see if we can help you out.
