### ISSUE TITLE
rich messages from rasa abandoned by rocket.chat api client

### ISSUE THREAD

**Issue by xkungfu** [RocketChat/Rocket.Chat#20069]
### Description:

rasa response message:

`[{"recipient_id":"z37Ar5whqGRebn7K7","text":"rasa text replaced","test":"rasa message new item test","alias":"xxxxxxxxxxxxxxxxxx","attachments":[{"audio_url":"http:\/\/www.w3schools.com\/tags\/horse.mp3","author_icon":"https:\/\/avatars.githubusercontent.com\/u\/850391?v=3","author_link":"https:\/\/rocket.chat\/","author_name":"Bradley Hilton","collapsed":"false","color":"#ff0000","fields":[{"short":"true","title":"Test","value":"Testing out something or other"},{"short":"true","title":"Another Test","value":"[Link](https:\/\/google.com\/) something and this and that."}],"image_url":"http:\/\/res.guggy.com\/logo_128.png","message_link":"https:\/\/google.com","text":"Yay for gruggy!","thumb_url":"http:\/\/res.guggy.com\/logo_128.png","title":"Attachment Example","title_link":"https:\/\/youtube.com","title_link_download":"true","ts":"2016-12-09T16:53:06.761Z","video_url":"http:\/\/www.w3schools.com\/tags\/movie.mp4"}]}]`

the format of the response on rasa side designed according to this post in DOCS:

**https://docs.rocket.chat/api/rest-api/methods/chat/postmessage#attachments-detail**

on rocket.chat side, only text field left.

how to write a correct response for rocket.chat?
### Steps to reproduce:

send a message then get response.

### Expected behavior:

how to write a correct response for rocket.chat?

### Actual behavior:

can't receive rich message fields ,such as: attachments,,, etc...

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 4
- NodeJS Version: 6
- MongoDB Version:4

### Client Setup Information

- Desktop App or Browser Version:web
- Operating System:web

### Additional context

no
### Relevant logs:
where is the log can find response from rasa?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
