### ISSUE TITLE
[BUG] Error message is displayed while archiving a room.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20079]
### Description:
When we try to archive a room an error message is displayed on screen with success message.

### Steps to reproduce:

1. Room info from contexual bar.
2. Select edit
3. Scroll down and toggle archived button.

### Expected behavior:
No error message sould be displayed on screen

### Actual behavior:
Error message is displayed with success message which can confuse user.

https://user-images.githubusercontent.com/55157259/103775638-5ba5ce80-5054-11eb-9afa-5c609e4f2c03.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

**Comment by Darshilp326** [comment]
Working on it!

**Comment by Darshilp326** [comment]
Can anyone explain me what are we actually doing by archiving any room?

**Comment by Darshilp326** [comment]
@aKn1ghtOut Hey man, i was working on it :/

**Comment by Darshilp326** [comment]
@aKn1ghtOut  Can you explain what are we actually doing by archiving rooms?

**Comment by aKn1ghtOut** [comment]
Hey, it was just changing the "archived" key in the "Rooms" mongo collection by id. You can find more details about the exact error from the PR I made. The description and the file itself I made the edit in should be a good descriptor for what needed to be changed, and why.
