### ISSUE TITLE
User Actions don't work from UserInfo page.

### ISSUE THREAD

**Issue by yash-rajpal** [RocketChat/Rocket.Chat#20086]
### Description:

The user actions like set users as owners or moderators from user info section of any room, does'nt work

### Steps to reproduce:

1. Open Members list of any room
2. Select any member and open the User Info page
3. Try and set any user as owner or moderator, we recieve an error

### Expected behavior:

No errors when clicking on User actions from the user info page

### Actual behavior:

![userActions](https://user-images.githubusercontent.com/58601732/103796562-628d0b00-506d-11eb-9fd6-0e39e3945db9.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.66 
- Operating System: Linux (Ubuntu)

### Additional context

I will be working on it!

**Comment by yash-rajpal** [comment]
I would be working on it after 2-3 days. Thanks.

**Comment by Darshilp326** [comment]
@yash-rajpal #20073 would solve this issue.

**Comment by yash-rajpal** [comment]
@Darshilp326 Ohh I see. Np I will close this.
