### ISSUE TITLE
Example docker-compose.yml does not target current / latest release

### ISSUE THREAD

**Issue by apiening** [RocketChat/Rocket.Chat#20081]
### Description:

My RocketChat installation is based on the provided **docker-compose.yml** example from this repository.
The referenced image is **rocketchat/rocket.chat:latest** but this does not seem to be the latest release.

https://github.com/RocketChat/Rocket.Chat/blob/5769cec0f4188195bac005602a3b940ca8be41e4/docker-compose.yml#L5

After pulling the image I'm on **Rocket.Chat Version: 3.10.0** and the web interface complains that there is a newer version (3.9.0) which I should upgrade to.

From the **Docker Hub** page (https://hub.docker.com/_/rocket-chat) I can see that there is a **3.8.5** and a **3.9.4** release.

### Steps to reproduce:

1. Download the linked / provided **docker-compose.yml** file an save it to a local directory.
2. From within this directory, run: `docker-compose up -d && docker-compose logs -f`
3. Watch the log output: **Version 3.10.0** is running, even though the image tag is `:latest`.

### Expected behavior:

The current / latest image should be tagged with `:latest` or the provided **docker-compose.yml** should be updated to point to the latest release.

### Actual behavior:

An old / outdated release is pulled / installed when the provided **docker-compose.yml** file is used.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Mozilla Firefox 84.0.1
- Operating System: Mac OS X 11.1 Big Sur

### Additional context

Is it safe to switch to one of this releases, or is there an update path?
Should the **docker-compose.yml** example file be updated to this release?
Is there a reason why **:latest** does not target the latest release of **Rocket.Chat**?

### Relevant logs:

```
rocketchat_1          | ➔ +-----------------------------------------------+
rocketchat_1          | ➔ |                 SERVER RUNNING                |
rocketchat_1          | ➔ +-----------------------------------------------+
rocketchat_1          | ➔ |                                               |
rocketchat_1          | ➔ |  Rocket.Chat Version: 3.10.0                  |
rocketchat_1          | ➔ |       NodeJS Version: 12.18.4 - x64           |
rocketchat_1          | ➔ |      MongoDB Version: 4.0.22                  |
rocketchat_1          | ➔ |       MongoDB Engine: mmapv1                  |
rocketchat_1          | ➔ |             Platform: linux                   |
rocketchat_1          | ➔ |         Process Port: 3000                    |
rocketchat_1          | ➔ |             Site URL: https://my.instance.com |
rocketchat_1          | ➔ |     ReplicaSet OpLog: Enabled                 |
rocketchat_1          | ➔ |          Commit Hash: 3a13cead22              |
rocketchat_1          | ➔ |        Commit Branch: HEAD                    |
rocketchat_1          | ➔ |                                               |
rocketchat_1          | ➔ +-----------------------------------------------+
```

**Comment by nikolas-digitalBabylon** [comment]
...To add to this, using "latest" tag, doesn't result in the latest "release" built, but to RC. For example, while 3.9.3 was stable release, "latest" docker tag would download 3.10.0 which was RC and was causing issues.

**Comment by sampaiodiego** [comment]
the `latest` docker tag always points to our latest stable release. if you're running an outdated version you should do run `docker-compose pull` to pull the updated images and then restart with `docker-compose up -d`
