### ISSUE TITLE
Automatic drop down of sidemenu on clicking elements

### ISSUE THREAD

**Issue by HariAcidReign** [RocketChat/Rocket.Chat#20091]
### Description:

Sidemenu automatically drops down to the "Settings" section on clicking an element.

### Steps to reproduce:

1. Go to the Administration tab
2. Click on any item
3. After clicking, the user is taken to the Settings Search tab instead of staying at the same place

### Expected behavior:

The item should be chosen and the menu shouldn't go down. 

### Actual behavior:

https://user-images.githubusercontent.com/58134096/103883674-8a2eb280-5103-11eb-82f8-17e8a46d972f.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Linux
- Deployment Method:  Gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8
--

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 10

### Additional context

I personally feel that it is not a good UI experience, but if it like that for a reason, do let me know. 
Also, I am working on this issue!

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
