### ISSUE TITLE
[BUG] Starring a message stars it for all users of the channel, unstarring doesn't change icon.

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Rocket.Chat#20099]
### Description:

Starring any message stars it for all users across a channel. On unstarring it the star icon next to the message doesn't disappear and the message still appears starred for all users even if the original user who starred the message has unstarred it.

### Steps to reproduce:

1. Click on the message menu for any message.
2. Click on "Star Message". (The star icon appears here.)
3. Click on "Unstar Message". (The star icon doesn't disappear.)
4. Log out.
5. Log in as different user, part of the channel.
6. Unstarred message by original user appears starred.

### Expected behavior:

1. Messages should only be starred for respective users.
2. Unstarring a message should make the star icon disappear.

### Actual behavior:

1. Starring a message, stars it for all users across the channel.
2. Unstarring the message doesn't make the star icon disappear for anyone (including the original user).

https://user-images.githubusercontent.com/28918901/103914343-af391a80-512f-11eb-888b-b50df530321d.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.4
- Operating System: Ubuntu 18.04 LTS
- NodeJS Version: 12.18.2
- MongoDB Version: 4.4.2

### Client Setup Information

- Desktop App or Browser Version: Chromium
- Operating System: Ubuntu

**Comment by dougfabris** [comment]
After the implementation of the new message template using React this issue became stale.  
Thanks for reporting it!
