### ISSUE TITLE
[BUG] Ignore button in User info returns undefined when clicked

### ISSUE THREAD

**Issue by chetas411** [RocketChat/Rocket.Chat#20095]
### Description:
When we click ignore button in full profile mode of a user , it doesn't work and returns  an undefined instead.

### Steps to reproduce:

1.  Go to any room and click on any user.
2.  Click on show full profile.
3.  Click on ignore button.

### Expected behavior:
A success message or notification should popup.

### Actual behavior:
Undefined is returned

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

https://user-images.githubusercontent.com/65273718/103894311-c4548000-5114-11eb-93ab-256d74a29a39.mp4

**Comment by chetas411** [comment]
I am willing to solve this issue on my own , can anyone help me in telling which files should I begin to look at ?

**Comment by yash-rajpal** [comment]
This is a duplicate issue from #20086 and I am already working on this.
