### ISSUE TITLE
Archive\Unarchive button shows up in not owner user panel

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#2009]
Button on channel appears in room info panel for user that not actualy owner or admin, so as @marceloschmidt (i gues) in support room says is not big problem because of room deos not actualy archived for that users, but should be hidden for all except realy owner or admin users. 
![bug button](https://cloud.githubusercontent.com/assets/8321589/12523084/16cf6c6e-c187-11e5-8da7-64a319802a28.png)

**Comment by graywolf336** [comment]
Closing, please be sure to search issues/pull requests before creating issues. There is a proposed fix by #2008.

**Comment by marceloschmidt** [comment]
Sorry, I didn't know there was one, so I instructed @vetash to open one. Good catch @graywolf336! Thanks.
