### ISSUE TITLE
Inconsistency in how channels avatars behave

### ISSUE THREAD

**Issue by bdelwood** [RocketChat/Rocket.Chat#20103]
### Description:

Uploading a channel avatar from `dot menu > Room Info > edit > upload` works as expected. When returning to the `Room Info` page the image is the same default. 

When one goes to `Administration > Rooms > <Room name> > Room Info` panel, the uploaded picture is not reflected either. 

Using `Administration > Rooms > <Room name> > Room Info > upload` accepts an upload but it is not reflected on the `Room Info` page, but the change is reflected back in `dot menu > Room Info > edit`

This may be some caching issue. It only appears when trying to change _to_ or _from_ the **default** avatar. After playing around for a bit (logging in and out, restarting service), the avatar updated across all three panels. Once the default avatar had been changed, any further avatar updates behaved as expected. 

However, the update takes a page refresh. 

### Steps to reproduce:

0. Clean install using official `docker-compose.yaml`
1. Upload a channel avatar using `dot menu > Room Info > edit > upload`, then `save`. Observe photo persists on this page. 
2. Return to `Room Info`, notice default avatar is still on this page. 
3. Go to `Administration > Rooms > <Room name> > Room Info`, notice image is not reflected here either. 
4. Use `Administration > Rooms > <Room name> > Room Info > upload` to upload another image.
5. Return to `dot menu > Room Info > edit > upload` to see the new upload present. 
.....
6. ? At some point the default avatar will be replaced with the upload. After this point things behave as expected. 

### Expected behavior:

All three panels `dot menu > Room Info`,  `dot menu > Room Info > edit`, and `Administration > Rooms > <Room name> > Room Info` should reflect the same information. 

### Actual behavior:

`dot menu > Room Info > edit` reflects `Administration > Rooms > <Room name> > Room Info > upload`, but this is not reproduced in `dot menu > Room Info` or `Administration > Rooms > <Room name> > Room Info`.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: Arch Kernel 5.10
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Win10

### Additional context

This might be related to [#14618](https://github.com/RocketChat/Rocket.Chat/pull/14618).

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
