### ISSUE TITLE
Meteor build broken after I changed code

### ISSUE THREAD

**Issue by scheung38** [RocketChat/Rocket.Chat#2010]
Just did a git clone and running meteor update followed by
$ meteor
/Rocket.Chat

=> Started proxy.                             
   Building package rocketchat:livechat      -
WARNING: The output directory is under your source tree.

and cannot build? 

This is Mac OSX:

I20160123-00:14:02.483(0)? Exception in queued task: Error: [CustomOAuth: Options.serverURL is required and must be String]
I20160123-00:14:02.483(0)?     at CustomOAuth.configure (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:28:21)
I20160123-00:14:02.483(0)?     at Object.RocketChat.models.Settings.find.observe.added (packages/rocketchat_github-enterprise/common.coffee:19:22)
I20160123-00:14:02.483(0)?     at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
I20160123-00:14:02.483(0)?     at self.applyChange.added (packages/minimongo/observe.js:53:1)
I20160123-00:14:02.484(0)?     at packages/mongo/observe_multiplex.js:183:1
I20160123-00:14:02.484(0)?     at Array.forEach (native)
I20160123-00:14:02.484(0)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160123-00:14:02.484(0)?     at Object.task (packages/mongo/observe_multiplex.js:177:1)
I20160123-00:14:02.484(0)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20160123-00:14:02.485(0)?     at packages/meteor/fiber_helpers.js:125:1
I20160123-00:14:02.624(0)? ufs: temp directory created at /tmp/ufs
I20160123-00:14:02.649(0)? configuring push

**Comment by graywolf336** [comment]
Are you building on Windows or Linux or Mac?

**Comment by scheung38** [comment]
Hi Bradley, Mac OSX, I get tons of exceptions while starting, even though it is now running

**Comment by graywolf336** [comment]
I've never heard of Pycharm IDE, so I wouldn't know. But I have made several changes inside of the `rocketchat-lib` packages, so not sure why you're having trouble. Although, the settings piece won't be reflected after it's ran once since it creates a record in the database and if the setting exists it won't change unless the user changes it.

**Comment by scheung38** [comment]
Pycharm is just another IDE from IntelliJ, but no different to any other IDE as I simply use its command line prompt.
My question is can settings.coffee or any of the content within rocketchat-lib be changed so I can customise it or not? As changes does not seem to be reflected in chrome browser?

**Comment by Sing-Li** [comment]
@scheung38 Yes,  everything can be changed.     Yes, Meteor rebuild can be slow after you modify code.    Suggestion is to study Meteor, and learn how to remove packages you don't need during development.    Also, if you have a FASTER machine with more memory, faster network, and/or SSD will help the speed a lot.   Rebuilds are generally quite quick AFTER the first time - because some results are cached.

**Comment by scheung38** [comment]
Thanks Sing-Li much appreciated, made some textual changes,for example, in the rocketchat-lib settings.coffee file and expecting the changes to be reflected in login page but even restarting meteor on the command line, I do not see anything changes and instead the same text as before.

**Comment by scheung38** [comment]
Have already done course in coursera on meteor so have good understanding of meteor, but this is using coffeescript so I am not sure whether it is coffeescript not compiled into JavaScript or something else. Telling someone to study guide.meteor.com is not helpful right? Guide covers coffeescript? Even the initial build before changing anything had quite a number of exception as noted above.

**Comment by Sing-Li** [comment]
No problem.   :)

Changing code anywhere can cause the build to fail.  Even in areas that you deemed to be text.

All our new development is done in JavaScript.   But if you modify existing code - yes, Meteor was completely based on CoffeeScript only a few months ago.

**Comment by scheung38** [comment]
Hi Sing-Li

Your first response was "Yes everything can be changed" and second response "Changing code anywhere can cause the build to fail, even in areas deemed to be text". That seems like two contradictions. How can these two mutually exclusive statement both be true. Either one could or couldn't.

**Comment by scheung38** [comment]
I was very specific in saying settings.coffee when I added text to add Layout Login Terms to Hello there is no change in output, how could you say I was not specific enough when I opened issue with name of file and line number? Not sure if you read the first time i tried to point it out.

**Comment by Sing-Li** [comment]
@scheung38  I am trying my best to help you move forward and solve your problem. Hope you understand. :smile: 

Yes. Please open an issue with the subject - exactly with line number and what you're trying to achieve with your changes. Let's not digress.

**Comment by scheung38** [comment]
Hi SingLi I already mentioned twice in thread that changes in rocketchat-lib/settings.coffee @add Layout Login Terms text is not reflected in browser. Not sure how else or what else I can do.

**Comment by Sing-Li** [comment]
Please feel free to re-open issue. :smile:

**Comment by Sing-Li** [comment]
@scheung38  is your end goal to change the *Login Terms* text?

**Comment by scheung38** [comment]
No, but just by going what you said that everything can be changed, but even adding a simple Hello doesn't get reflected seem odd in settings.coffee. If it can't be changed then it is fine, just confusing that's all.

**Comment by Sing-Li** [comment]
Ah.  It *is* very confusing.  Even for us devs :(

Settings, the places where they may be modified (env var, GUI, .settings file) and which one overrides the other.    That code is undergoing rapid change.   See this ticket for some tidy up  work-in-progress https://github.com/RocketChat/Rocket.Chat/issues/1492

**Comment by shrop** [comment]
I have this issue the first run, before I add any accounts. Once I add an account, it seems to be fine.

**Comment by amadou009** [comment]
Hello, I have the same issue. I can't do " meteor build ".
I had juste modify : /Rocket.Chat/packages/rocketchat-ui-login/login# gedit form.html.
![capture d ecran de 2016-07-26 12 45 01](https://cloud.githubusercontent.com/assets/18334094/17153003/4afe7cc0-532f-11e6-837c-dd48f5f217f9.png)

Someone could help me
