### ISSUE TITLE
Ability to customize the loading indicator logo

### ISSUE THREAD

**Issue by mhndm** [RocketChat/Rocket.Chat#2011]
Ability to customize the loading indicator logo : the content of the loading.html

**Comment by k0nsl** [comment]
:+1:

**Comment by RichardFoxworthy** [comment]
I can't find the file containing the 'loading' animation. Does not seem to live in the /public/images/ directory?

**Comment by k0nsl** [comment]
@RichardFoxworthy 
https://github.com/RocketChat/Rocket.Chat/blob/152aabd035f1befca019b8bb342274ade739fda7/public/images/logo/icon-loader.svg

**Comment by RichardFoxworthy** [comment]
thanks @k0nsl - I already tried replacing that file, and I still see the RocketChat spaceship loading animation. It must live somewhere else

**Comment by mrplow** [comment]
Its animated, I think it may be embedded in some js or something because I can't find it either.

**Comment by RichardFoxworthy** [comment]
@mrplow @k0nsl @mhndm  I found this: #1634. Would be nice to have an Admin interface control to modify this.

**Comment by engelgabriel** [comment]
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/613

**Comment by wathmal** [comment]
you can customize the css if want. just override the `.rocket-loader` class in custom css field.
```
.rocket-loader {
    display: none;
}
```

**Comment by yuchaozh** [comment]
@wathmal Where is the css file?

**Comment by wathmal** [comment]
@yuchaozh you have to add the custom css via Administration section.
`Administration -> Layout -> Custom CSS`

**Comment by yuchaozh** [comment]
@wathmal It works, Thanks!

**Comment by DavePS** [comment]
My solution if you want a custom url

`.rocket-loader {
	display: block;
  	-moz-box-sizing: border-box;
  	box-sizing: border-box;
  	background: url(CUSTOM_IMG_URL) no-repeat;
  	width: 180px;
  	height: 236px;
  	padding-left: 180px;
}`

**Comment by rtest12** [comment]
Apparently, in the latest versions something has changed, these methods did not work for me on 4.1. Does anyone have a solution?

**Comment by rtest12** [comment]
```
.loading-animation {  
  background: url(https://example.com/images/preloader.gif)
  background-repeat: no-repeat;
  background-position: 50% 50%
}

#react-root .page-loading .loading-animation .bounce {
  display: none;
  height: 0px;
}
```
What am I doing wrong?
