### ISSUE TITLE
[BUG] Ubuntu 16.04 in readme.md

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20112]
### Description:

By clicking on Ubuntu 16.04 in deployments in README.md doesn't take to that section.
### Steps to reproduce:

1. README.md
2. Deployment section
3. Click on Ubuntu 16.04

### Expected behavior:
User should be navigated to that section.

### Actual behavior:
User is not navigated to that section.

https://user-images.githubusercontent.com/55157259/103996079-54e79a80-51bf-11eb-83c0-13a1d758e55b.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

**Comment by Darshilp326** [comment]
Working on it!

**Comment by Darshilp326** [comment]
Should i delete that Ubuntu 16.04 as i was not able to find any related section of it?

**Comment by abhinav-TB** [comment]
I think this issue is already dealt with in #20126

**Comment by Darshilp326** [comment]
@abhinav-TB Yes he made a new issue for his pr :)

**Comment by HariAcidReign** [comment]
Hey man! There were many other broken links like that, so I made it into a separate issue and fixed it. Thanks for pointing it out :)

**Comment by Darshilp326** [comment]
@HariAcidReign No problem :)
