### ISSUE TITLE
Redundant tooltip in kebab menu options

### ISSUE THREAD

**Issue by HariAcidReign** [RocketChat/Rocket.Chat#20111]
### Description:

The exact same tooltip appears above the options in the kebab menu inside a channel

### Steps to reproduce:

1. Go to channel
2. Click on the "More Options" kebab icon
3. On hover over an item, the same name is shown in the tooltip (redundant)

### Expected behavior:

On hover, there should be no tooltip, as it offers no extra information

### Actual behavior:

https://user-images.githubusercontent.com/58134096/103995405-7431f800-51be-11eb-802c-613c2c9e79b3.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Linux
- Deployment Method: Gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 10

### Additional context

I personally feel that it is not a good UI experience, but if it like that for a reason, do let me know.

**Comment by aKn1ghtOut** [comment]
I do agree with the suggestion. The tooltips are redundant.

**Comment by HariAcidReign** [comment]
Awesome! Working on it

**Comment by HariAcidReign** [comment]
![image](https://user-images.githubusercontent.com/58134096/105859840-f9b50500-6012-11eb-85fa-ca4cb25e8f5d.png)


`clients/views/Header/ToolBox/Toolbox.tsx`
I'm pretty sure this is the section of code I should change to not make the tooltip title pop up on hover. But I need some guidance/hint to figure out what to change 😅 @gabriellsh @sampaiodiego Can anyone guide me on this one alone, please?
