### ISSUE TITLE
Android app does not login after update

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#2012]
i updated to the new Android version and since then i can't login. It's the same for everyone who updated.

iOS works fine but on Android i have the following:

- if i try via https i get an error
- if it's over http it redirect to an empty blue page with a white rectangle in the middle

Do you guys have a clue? All other platform work great

screens attached

![screenshot_2016-01-23-13-20-07](https://cloud.githubusercontent.com/assets/11820636/12530139/ad9fa472-c1d4-11e5-853c-e1867d500026.png)
![screenshot_2016-01-23-13-20-26](https://cloud.githubusercontent.com/assets/11820636/12530140/af913fac-c1d4-11e5-9348-5dadaa849291.png)

**Comment by prohde** [comment]
What is your currently running Rocket.Chat version? You can find this by going to http(s)://your-rocket.chat-domain-and-port/api/info.

**Comment by raulfiru** [comment]
i tried various..

{
  "version": "0.13.0",
  "compile": {
    "date": "2016-01-13T20:33:37.518Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 4916600832,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2971",
    "branch": "develop",
    "tag": ""
  },
  "commit": {
    "hash": "54c4ee4107fa8124c2b5a269413599a0f8cb61ee",
    "date": "Wed Jan 13 17:10:46 2016 -0200",
    "author": "Gabriel Engel",
    "subject": "Merge pull request #1897 from RocketChat/fix-flex-cog-dropdown"
  },
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-05 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib\n\n"
  }
}

**Comment by prohde** [comment]
I am on 0.14.0 and my users are able to log in with the Android app.

**Comment by raulfiru** [comment]
updated to latest dev... still the same..however in the screen with the white box now i get a notification that it can't connect to server.

could it be connected to the ROOT_URL? i changed it to the public domain... HTTPS...

**Comment by raulfiru** [comment]
ok, i got it... the TLS certificate chain/root somehow is not trusted on android... but works everywhere else... strange

**Comment by Sing-Li** [comment]
This is a known problem.  See rocketchat/Rocket.Chat.Cordova#59

**Comment by raulfiru** [comment]
i fixed my issue... it was a certificate problem...

i used let's encrypt and created a specific subdomain one. i used *.domain certificate before..and apparently android as issues with it.

**Comment by prohde** [comment]
I am glad you could fix this.
Android does not have any issues with my let's encrypt cert, maybe it's the change from the wildcard cert to the subdomain specific one.
