### ISSUE TITLE
[BREAKING!!] New user registration screwed sidebar for *all* users!

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat#20133]
### Description:

A new user has registered on my server running 3.10.1. Once the user was approved, all private chats for **all users** are screwed now! Every private chat is showing the username of the new registered user.

<img width="286" alt="grafik" src="https://user-images.githubusercontent.com/3321655/104105827-47124200-52b1-11eb-869e-fbb82735efad.png">

Update to 3.10.3 did not solve the issue!

### Steps to reproduce:

1. A new user registered on the server
2. The new user was approved by the admin
3. All 1:1 chats for all users on the server are showing the name of the new user in the sidebar (see screenshot above)

### Expected behavior:

The new user should be available, but the chat list for all users should not break

### Actual behavior:

The chat list for all users are screwed, in browser and all mobile apps

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.1 (updated to 3.10.3 now, did not fix it)
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: All Apps, all browsers are affected
- Operating System: All OS

### Additional context

Need advice how to fix this ASAP as my server is fully broken now!

**Comment by yash-rajpal** [comment]
Do you have a backup of the database before you updated?

**Comment by jacotec** [comment]
No, just my nightly VM backups. The issue was not the update, it was triggered by the registration of a new user.
Reverting to 3.9.4 does also not solve the issue, is there a command to repair the database?
Only other solution would be to take the backup from last night, but all users will loose all messages from today in this case.

**Comment by plustigahl** [comment]
Having the same issue.  Albeit, on latest version (upgraded today), new user accounts show correct name and avatar with corresponding letter.  It also shows all the other users as normal.  Seems like this is only affecting users that were created before 3.10.1 as my admin account is showing them with all the same username/initial on avatar.  Sigh.

**Comment by jacotec** [comment]
The only action I could do right now on a Saturday night to get my server back online was to revert the VM to my last night's backup. Unfortunately users lost all their messages from today, but this is better than the mess caused by the issue.
I've updated to 3.10.3 then and registered a test user which did not cause any issue. Maybe it was related to 3.10.1 (hopefully), but it should be definitely checked / confirmed by the RC devs. I'm pretty nervous right now ...
@diegolmello @sampaiodiego

**Comment by plustigahl** [comment]
@jacotec, pretty certain was related to 3.10.1 and maybe 3.10.2.  Was losing my mind last night as well.  No backup, but the workaround aforementioned will do for now until a fix can be rolled out for this.

**Comment by ankar84** [comment]
I think that issue is fixed by https://github.com/RocketChat/Rocket.Chat/pull/20128

**Comment by salehi** [comment]
I didn't find a good way to recreate the subscription names via mongo shell, May be its better for rocketchat developers to provide one solution!

**Comment by sampaiodiego** [comment]
I'm very sorry about this guys.. It was indeed happening on 3.10.1 and 3.10.2 but it was fixed on 3.10.3 a few hours later.. 

you can use the following mongodb shell script to fix them (I recommend shutting rocket.chat down before running it)
```javascript
db.getCollection('rocketchat_subscription').find({t:'d'}, { rid: 1, u: 1 }).forEach((sub) => {
	const room = db.getCollection('rocketchat_room').findOne({ _id: sub.rid }, { usernames: 1 });
	if (!room) {
		print('ROOM NOT FOUND: '+sub.rid);
		return;
	}

	if (!room.usernames || room.usernames.length === 0) {
		print('NO USERNAMES: '+sub.rid);
		return;
	}

    const name = room.usernames.filter(u => u !== sub.u.username).sort().join(', ') || sub.u.username;

	if (!name) {
		print('NO NAME '+sub._id);
		return;
	}

	db.getCollection('rocketchat_subscription').update({ _id: sub._id }, { $set: { name, _updatedAt: new Date() } });
});
```

I tried releasing a fix as fast as I could so I didn't ship a migration to fix it.. I can work on a migration to automatically fix it without the need of running an external script today.

**Comment by salehi** [comment]
Thank you @sampaiodiego 
I used your base and here is my final script which fixed the problem:
```javascript
directs = db.rocketchat_subscription.find({t: 'd'}).forEach(function (direct_row) {
    rooms = db.rocketchat_room.find({_id: direct_row.rid});
    rooms.forEach(function (room_row) {
        const name =
            room_row.usernames.filter(u => u !== direct_row.u.username).sort().join(', ')
            ||
            direct_row.u.username;
        db.rocketchat_subscription.update({ _id: direct_row._id }, { $set: { name, _updatedAt: new Date() } });
    });
});
```

I also need to change the url so that I can debug it in my machine first, may be useful to someone else.
```javascript
db.rocketchat_settings.update({"_id" : "Site_Url"},{$set:{value:"http://localhost:3000"}});```

**Comment by plustigahl** [comment]
> I'm very sorry about this guys.. It was indeed happening on 3.10.1 and 3.10.2 but it was fixed on 3.10.3 a few hours later..
> 
> you can use the following mongodb shell script to fix them (I recommend shutting rocket.chat down before running it)
> 
> ```js
> db.getCollection('rocketchat_subscription').find({t:'d'}, { rid: 1, u: 1 }).forEach((sub) => {
> 	const room = db.getCollection('rocketchat_room').findOne({ _id: sub.rid }, { usernames: 1 });
> 	if (!room) {
> 		print('ROOM NOT FOUND: '+sub.rid);
> 		return;
> 	}
> 
> 	if (!room.usernames || room.usernames.length === 0) {
> 		print('NO USERNAMES: '+sub.rid);
> 		return;
> 	}
> 
> 	const name = room.usernames.filter(u => u !== sub.u.username).sort().join(', ') || sub.u.username;
> 
> 	if (!name) {
> 		print('NO NAME '+sub._id);
> 		return;
> 	}
> 
> 	db.getCollection('rocketchat_subscription').update({ _id: sub._id }, { $set: { name, _updatedAt: new Date() } });
> });
> ```
> 
> I tried releasing a fix as fast as I could so I didn't ship a migration to fix it.. I can work on a migration to automatically fix it without the need of running an external script today.

running this via mongo shell worked perfectly.  Thank you!

**Comment by plustigahl** [comment]
@sampaiodiego, one thing i did notice, my admin user, when clicking on my own profile in a DM, it shows me as rocket.cat bot user, any idea?  All the other users are showing their corresponding user.

**Comment by ggazzo** [comment]
@plustigahl 
> @sampaiodiego, one thing i did notice, my admin user, when clicking on my own profile in a DM, it shows me as rocket.cat bot user, any idea? All the other users are showing their corresponding user.
> 
> EDIT: This only happens on my macos rocketchat client. iOS shows correctly.

My bad :x fixing as soon as possible
