### ISSUE TITLE
[BUG] Wrong information in user info page for non-admin users.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20138]
### Description:
While opening user info from list of members gives wrong information of Last Login and Created at if you are a non-admin user.

### Steps to reproduce:

1. Register as a non-admin user
2. Join any room and open members list from contexual bar
3. Click on any of the member

### Expected behavior:
Correct information should be displayed for both admin as well as non-admin users.

### Actual behavior:
Correct information is only displayed when a user is an admin.

https://user-images.githubusercontent.com/55157259/104119939-20a7e180-5359-11eb-9bd4-b4e78ac185d2.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:3.11.0-develop 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
I am working on it :)

**Comment by Darshilp326** [comment]
Working on it!

**Comment by yash-rajpal** [comment]
I think this is a setting to enable this for all, I am not sure though.

**Comment by Darshilp326** [comment]
@yash-rajpal Where you able to find?
If there is setting then we should not show these details to non-admin users on user-info page instead of showing wrong details.

**Comment by Darshilp326** [comment]
@yash-rajpal Found any setting for this issue?

**Comment by Darshilp326** [comment]
@dougfabris Do you feel this issue is relevant? :smile:

**Comment by dougfabris** [comment]
> @dougfabris Do you feel this issue is relevant? 😄

Sure! I'll take a look asap, thanks for reporting!
