### ISSUE TITLE
Pages in the Admin Panel can't be scrolled in Safari

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat#20136]
### Description:

The admin panel can't be used anymore with Safari browsers (MacOS, iPhone, iPad). The content of the right frame can't be scrolled anymore.

### Steps to reproduce:

1. Open the admin panel in any Safari Browser
2. Open a topic where the config page on the right side exceeds the screen height (i.e. "Layout" or "Users")
3. You can't scroll the content of the right frame, so anything which is not right on the screen can't be accessed

### Expected behavior:

You should be able to scroll the content of the right frame

### Actual behavior:

The conetent of the right frame can't be scrolled and the content not visible on the page can't be accessed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Any Safari browser and the IOS app
- Operating System: MacOS, IOS

### Additional context

Workaround: Using Firefox or Chrome

**Comment by Simon2046** [comment]
Same.
Can NOT access admin items from iOS client and iOS web browser. 
I think it happens from Server version 3.9.0 when I upgrade from version 2.4

**Comment by UAnton** [comment]
Have the same problem.

**Comment by matchsp** [comment]
I'm experiecing the same problem. This starts today morning after upgrading RC Server to 3.10.5

On the Iphone I'm running RC 4.14.1

**Comment by rcsilvadev** [comment]
Still an issue on RC server 3.11.1.
