### ISSUE TITLE
[Improvement] Reply to thread icon is inconsistent and redundant.

### ISSUE THREAD

**Issue by TarunTomar122** [RocketChat/Rocket.Chat#20144]
### Steps to reproduce:

1. Check the thread icon in the messages having replies.
2. Click on the thread icon. Nothing happens.

### Expected behavior:

Either by clicking on the thread icon the thread of the replies shall open up or the icon itself can be merged with the reply button like in case of mobile app.

### Actual behavior:

Right now the thread icon is sort of useless and inconsistent with the mobile app design.

Web app  -
![web](https://user-images.githubusercontent.com/54112921/104150297-7cc54100-53ff-11eb-83b0-4e926134b47e.PNG)
Mobile app - 
![mobile](https://user-images.githubusercontent.com/54112921/104150303-80f15e80-53ff-11eb-94a0-6aa1b9e6f42e.PNG)

### Server Setup Information:

-Version of Rocket.Chat Server: 3.10.0
-Operating System: CentOS7
-Deployment Method: docker
-Number of Running Instances: 12
-DB Replicaset Oplog: Enabled
-NodeJS Version: v12.18.4
-MongoDB Version: 4.0.16 WiredTiger

### Client Setup Information

-Desktop App or Browser Version: 3.1.1
-Operating System: Windows 10

### Additional context

I can fix this issue. I can change the icon to become inconsistent to mobile app or I can make it clickable with corresponding action to open the thread.

### Relevant logs:

None

**Comment by TarunTomar122** [comment]
Can I work on this issue?

**Comment by ankar84** [comment]
Looks like now mobile behave like web https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2686

**Comment by TarunTomar122** [comment]
Yeah right so I should probably close this issue and find some other one to work on :(
