### ISSUE TITLE
A live demo route for users not logged in?

### ISSUE THREAD

**Issue by garg** [RocketChat/Rocket.Chat#2014]
A live demo route that does not require account creation or logging-in would makes guest more motivated to sign-up. Example, a guest user goes to https://domain.chat/try and they are shown a 'demo' channel. The user is able to type messages, open and close the flex tab. This room could either reset every 24 hours, or it could just use the localstore or minimongo and never sync up with the server database. 

Eventually #604 will allow us to create public channels, but in the mean time I was wondering if there was a workaround that could allow developers to provide an anonymous use channel for demo purposes.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
