### ISSUE TITLE
Hovering over thread in channel view shows tooltip 'Open_thread' instead of 'Open Thread'

### ISSUE THREAD

**Issue by bubonicfred** [RocketChat/Rocket.Chat#20145]
### Description:
Minor UI bug
Tooltip for hovering over thread entry in channel window shows 'Open_thread' instead of 'Open Thread'

### Steps to reproduce:

1. Make a thread in a channel
2. Mouse over blue thread link in channel
3. Look at tooltip

### Expected behavior:

Tooltip should show as 'Open Thread' in line with other tooltips

### Actual behavior:
Tooltip shows as 'Open_thread'
![rocketchat bug](https://user-images.githubusercontent.com/1294298/104151048-ab571200-5427-11eb-90be-a28bff1aa211.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Ubuntu 20.04
- Deployment Method: docker on Cloudron
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Firefox 84.0.2 
- Operating System: Windows 10 Home 20H2 build 19042.685

**Comment by yash-rajpal** [comment]
Working on it. Would raise a PR in few hours.
