### ISSUE TITLE
[BUG] Broken empty search results

### ISSUE THREAD

**Issue by Pictor13** [RocketChat/Rocket.Chat#20153]
### Description:

The channel search (with regular expression or not) finds results but doesn't display them.
This, in my experience, is happening since months.

### Steps to reproduce:

1. just try to search something in a channel

### Expected behavior:

Get the results **AND** have the results displayed correctly.

### Actual behavior:

![Screenshot 2021-01-11 at 15 29 48](https://user-images.githubusercontent.com/6748874/104194832-6a292700-5454-11eb-9b65-205a5315aa51.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 🤷‍♂️  I'm not the admin
### Client Setup Information

- Desktop App or Browser Version: latest Chrome
- Operating System: macOS

### Additional context

It's pretty unclear whether results are found but are not displayed, or if no results are found but some results are displayed anyway (because there's just the date and no detail).

This doesn't happen for *every* search, but just on some of them.
I couldn't identify any sensible pattern about when the bug kicks in.
Sometimes it show results, sometimes it behaves like in the screenshot.

**Comment by Manas502** [comment]
Hey, are you talking about the irc channel search results?

**Comment by Pictor13** [comment]
I'm not aware of any related irc channel. 🤷‍♂️

I am talking about the search functionality of the RocketChat web user interface (see screenshot above).

**Comment by notatallshaw** [comment]
I see this issue frequently as well, I asked out Admins and we are currently on version 3.5.3.

**Comment by Pictor13** [comment]
I found out indeed that the version installed is 3.5.4, instead of the fixed 3.6.0.
(you can find it via  **https://*ROCKETCHAT_URL*/api/info** )
