### ISSUE TITLE
Changes in rocketchat-lib/settings.coffee @add Layout Login Terms text is not reflected in browser. 

### ISSUE THREAD

**Issue by scheung38** [RocketChat/Rocket.Chat#2015]
Changes in rocketchat-lib/settings.coffee @add Layout Login Terms text is not reflected in browser.

**Comment by Sing-Li** [comment]
Thanks.  @scheung38 !     

Just as background  - Administration -> Layouts -> Login is typically how *Layout Login* text is changed by s server adminsitrator.

@marceloschmidt  should be able to shed some light on this.

Thanks again for your understanding. @scheung38

**Comment by graywolf336** [comment]
Are you changing it via the website or code?

**Comment by scheung38** [comment]
Code : @add Login Layout Term for example append with simple "Hello World" doesn't get reflected in browser?

**Comment by graywolf336** [comment]
Correct. Any changes for settings should be done via the website as that
requires a database update.

**Comment by scheung38** [comment]
In that case it is not true that one can change whatever it is in setttings.coffee then.

**Comment by graywolf336** [comment]
If you can get a list of things which can't be changed via the website,
that would help us out tremendously! Thanks

**Comment by graywolf336** [comment]
![2016-01-23_22-06-25](https://cloud.githubusercontent.com/assets/850391/12534402/9902da04-c21d-11e5-9e24-0a66c840102c.png)
@scheung38 here's where to change those settings. The values in the source files is *only* for when that setting is first ran, any other changes to that setting's values should be modified via the website or via the database.
