### ISSUE TITLE
[BUG] Cannot remove emoji reaction

### ISSUE THREAD

**Issue by mmebsout** [RocketChat/Rocket.Chat#20151]
### Description:

It' s now impossible to remove an emoji reaction by clicking on it.

### Steps to reproduce:

1. go to a message
2. mouse over the message
3.  click on ' add a reaction'  (the smiley with the ' +' icon)
4. click on any smiley
5. the emoji appear below the message with a counter
6. click on the emoji
7. => the emoji isn't removed nor the counter decremented. 

### Expected behavior:
The emoji should be removed or the counter decremented

### Actual behavior:

The emoji blinks but nothing else happens (no console error)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3

### Client Setup Information

- Browser : Firefox 84.0.2 (64 bits) or Chrome 87.0.4280.88 (x86_64)

### Relevant logs:

Nothing in the browser's console. No request sent.

**Comment by ksarink** [comment]
Can confirm

**Comment by Deelight-fr** [comment]
The emoji can be cancelled by clicking on it again the emoji list, but indeed, it's not intuitive.

**Comment by aKn1ghtOut** [comment]
> The emoji can be cancelled by clicking on it again the emoji list, but indeed, it's not intuitive.

No need though. There was a bug that'll be easily fixed by the above PR. Clicking on the reaction itself should work again with it merged.

**Comment by Bengrunt** [comment]
> 
> 
> > The emoji can be cancelled by clicking on it again the emoji list, but indeed, it's not intuitive.
> 
> No need though. There was a bug that'll be easily fixed by the above PR. Clicking on the reaction itself should work again with it merged.

Hello, I'm wondering whether this will solve the very similar issue of not being able to increment another user's emoji reaction by clicking on it ? Or should I open a separate and dedicated issue to this problem?

Here is what this looks like:
![Jan-14-2021 08-59-33](https://user-images.githubusercontent.com/5541437/104564754-98248c00-564b-11eb-8745-52f8304f7eda.gif)

Thanks!

**Comment by aKn1ghtOut** [comment]
> > > The emoji can be cancelled by clicking on it again the emoji list, but indeed, it's not intuitive.
> > 
> > 
> > No need though. There was a bug that'll be easily fixed by the above PR. Clicking on the reaction itself should work again with it merged.
> 
> Hello, I'm wondering whether this will solve the very similar issue of not being able to increment another user's emoji reaction by clicking on it ? Or should I open a separate and dedicated issue to this problem?
> 
> Here is what this looks like:
> ![Jan-14-2021 08-59-33](https://user-images.githubusercontent.com/5541437/104564754-98248c00-564b-11eb-8745-52f8304f7eda.gif)
> 
> Thanks!

I haven't tested it for that yet but from what I can gather from the GIF, yes. This should solve that issue as well.

**Comment by wreiske** [comment]
![jYcGngxMTv](https://user-images.githubusercontent.com/6295044/104775498-a64ed700-5735-11eb-89f2-7d66450e3721.gif)

Seeing the same behavior. Glad to see there's already an issue open for it.

**Comment by chaperonRose** [comment]
Same behavior with 3.10.4 : 

- no iteration by clicking on a reaction added by someone else (need to add it by typing the name of the emoji).
- no removal of a reaction by clicking on it.
