### ISSUE TITLE
[BUG] Add .png extension to pictures pasted from clipboard

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#20165]
### Description:

Rocket Chat have a great feature to paste picture from clipboard into any chat, and that is really awesome!
But name for that pasted picture generates without any extension, so if user try to save it, it will not be saved as picture. So, just add ".png" to generated name and that problem will be solved in moment.

### Steps to reproduce:

1. Get a screenshot in clipboard (with WIN+Shift+S on Windows 10)
2. Paste with CTRL+V in any Rocket.chat chat
3. Try to save that picture pressing little blue cloud icon
4. That file saved not as graphical file

### Expected behavior:

Pasted images saved as PNG files

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/104309358-144f9000-54e3-11eb-9f52-3f0ab39d5b38.png)
![image](https://user-images.githubusercontent.com/4023037/104309397-23ced900-54e3-11eb-8366-82a864a3ff93.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 3.1.1 and Chrome 87
- Operating System: Windows 10

### Additional context

Easy to fix

### Relevant logs:

No

**Comment by ankar84** [comment]
I think fix will be in that line
https://github.com/RocketChat/Rocket.Chat/blob/119028b17f71df8797a46234cfee7cc6c8ee9217/app/ui-message/client/messageBox/messageBox.js#L389
@ggazzo what do you think?

**Comment by aKn1ghtOut** [comment]
Sounds like a good idea to me. No reason to not have an extension?

**Comment by aKn1ghtOut** [comment]
Just tried it using Chrome on Ubuntu 20.10, with the server on the same machine.
It does include the png extension for me while downloading. I'll give it a try on a different machine

**Comment by ankar84** [comment]
> Just tried it using Chrome on Ubuntu 20.10, with the server on the same machine.
> It does include the png extension for me while downloading. I'll give it a try on a different machine

Not in my case
![image](https://user-images.githubusercontent.com/4023037/104429500-bb413400-5596-11eb-87d8-1843e0a7999b.png)
Downloaded that file in Chrome 87 on Windows 10

**Comment by mynameisankit** [comment]
May I resolve this issue?

**Comment by Devansh-Trivedi** [comment]
In Ubuntu 20.04 it consists .png extension, is the error OS specific ? ,and the bug encountered in which OS ?

**Comment by ankar84** [comment]
> In Ubuntu 20.04 it consists .png extension, is the error OS specific ? ,and the bug encountered in which OS ?

Maybe you are right, I experience this bug on Windows in both Chrome and desktop application and can't check it for different OS.

**Comment by didacroyo** [comment]
I experience the same bug on mac OS with Google Chrome. Missing .png extension when downloading an image pasted from clipboard

**Comment by AvivBenShoham** [comment]
@dougfabris I'd like to work on this issue

**Comment by pinkman7009** [comment]
Can I work on this issue?

**Comment by batchu** [comment]
I'm unable to replicate this. I do see a .png extension on Windows/Chrome.

**Comment by ankar84** [comment]
> I'm unable to replicate this. I do see a .png extension on Windows/Chrome.

Please give us more info about your environment - RC server version, Windows version, Chrome version.
Because I just did a test on open.rocket.chat (I believe it's on 3.13.-rc0) on Windows 10 1809 in Chrome  89.0.4389.90 and no png extension
![image](https://user-images.githubusercontent.com/4023037/113466696-664ee480-9446-11eb-96a4-d54d571ac145.png)

**Comment by dougfabris** [comment]
@ankar84 As we're rewriting messages we changed the approach on this download button, I made a bunch of tests and it's working properly. Can you check it, please? Thank you!

**Comment by ankar84** [comment]
> Can you check it, please?

I do not confirm that issue is totally fixed.
I tested on recent stable 3.14.0 and on open.rocket.chat (to exclude any configurations of own server) in recent Google Chrome and most recent RC.Electron version 3.2.2
Here is a proof
![pmg](https://user-images.githubusercontent.com/4023037/118219387-0f472100-b482-11eb-8e6e-b0ce09a86b1a.gif)

**Comment by dougfabris** [comment]
> > Can you check it, please?
> 
> I do not confirm that issue is totally fixed.
> I tested on recent stable 3.14.0 and on open.rocket.chat (to exclude any configurations of own server) in recent Google Chrome and most recent RC.Electron version 3.2.2
> I also try to change my language from Russian to English - same result - no png extension.
> Here is a proof
> ![pmg](https://user-images.githubusercontent.com/4023037/118219387-0f472100-b482-11eb-8e6e-b0ce09a86b1a.gif)

@ankar84 I have to say you won't be able to see the changes on the stable neither on the open. The fix will be present just on the next release, I believe. You could check the fix on our latest develop branch.

**Comment by ankar84** [comment]
> @ankar84 I have to say you won't be able to see the changes on the stable neither on the open. The fix will be present just on the next release, I believe. You could check the fix on our latest develop branch.

Hey, @dougfabris 
I'm om **3.15.0** which is obviously next to 3.14.0 release and that **issue still not fixed**!
![image](https://user-images.githubusercontent.com/4023037/121983713-6f3f2900-cd9a-11eb-9851-6a8615e002e6.png)
![image](https://user-images.githubusercontent.com/4023037/121983726-77976400-cd9a-11eb-97a9-e23a737c5e8c.png)

**Comment by gabriel-henriq** [comment]
Same problem here, and i don't want to say to my users how to fix this problem manually. 

 Version 3.15.0

**Comment by dougfabris** [comment]
@ankar84 I really can't reproduce it anymore as the gif attached (WIN10 & Chrome). I don't know what is going on please share more details, DM me if you want and we can check more deeper on that
![svg-screen](https://user-images.githubusercontent.com/27704687/122241568-0a1e2d00-ce99-11eb-8266-59ab8f22c32b.gif)

**Comment by dougfabris** [comment]
@ankar84 I really did a bunch of tests and I'm not able to reproduce anymore on the web, as you can see in the gif attached (WIN10 & Chrome).
Please check if it still happening on chrome web browser or just on the Electron App and DM me if you want, we can check it deeper to understand the case

![svg-screen](https://user-images.githubusercontent.com/27704687/122252071-73a23980-cea1-11eb-9ef4-654e2be66e46.gif)

**Comment by ankar84** [comment]
Test 3.18 and now finally I see that bug is really resolved for me too!
![image](https://user-images.githubusercontent.com/4023037/131619938-d532246f-d16f-4a62-8e81-1a535fadb0fe.png)

**Comment by AndreySemenov1** [comment]
3.18.1 - 

> I think fix will be in that line
> https://github.com/RocketChat/Rocket.Chat/blob/119028b17f71df8797a46234cfee7cc6c8ee9217/app/ui-message/client/messageBox/messageBox.js#L389
> 
> 
> @ggazzo what do you think?

Mechanism for converting is very inconvenient when using (location, specific file types for files) restrictions from nginx.

But with the help of the changes, it turned out to achieve the correct result - add extension to all images from clipboard.

**Comment by ankar84** [comment]
I'm on 3.18.1 and again see that problem both in web client and Electron client 3.5.6
![image](https://user-images.githubusercontent.com/4023037/135602971-a91cee41-b79c-4dc5-b915-2dcc6f80435e.png)

@dougfabris can you test?
Maybe some server settings affect that behavior? 
[That result](https://github.com/RocketChat/Rocket.Chat/issues/20165#issuecomment-909926323) I have on my test server. But on my prod server I don't have file extension added to pictures from clipboard.

**Comment by yash10019coder** [comment]
Hi I would like to work on this issue also I'm a newcomer so please guide me

**Comment by dougfabris** [comment]
> I'm on 3.18.1 and again see that problem both in web client and Electron client 3.5.6 ![image](https://user-images.githubusercontent.com/4023037/135602971-a91cee41-b79c-4dc5-b915-2dcc6f80435e.png)
> 
> @dougfabris can you test? Maybe some server settings affect that behavior? [That result](https://github.com/RocketChat/Rocket.Chat/issues/20165#issuecomment-909926323) I have on my test server. But on my prod server I don't have file extension added to pictures from clipboard.

@ankar84 I'm going to check it again, thanks for helping mate!

**Comment by ankar84** [comment]
> > I'm on 3.18.1 and again see that problem both in web client and Electron client 3.5.6 ![image](https://user-images.githubusercontent.com/4023037/135602971-a91cee41-b79c-4dc5-b915-2dcc6f80435e.png)
> > 
> > @dougfabris can you test? Maybe some server settings affect that behavior? [That result](https://github.com/RocketChat/Rocket.Chat/issues/20165#issuecomment-909926323) I have on my test server. But on my prod server I don't have file extension added to pictures from clipboard.
> 
> @ankar84 I'm going to check it again, thanks for helping mate!

Yeap! Always glad to help improve that great product.
I still see on vanila 4.0.0 test server that png extension works perfect. 
But on my production server on 3.18.1 still no extension for some reason.

**Comment by dougfabris** [comment]
@ankar84 Could you take a look on this PR: #23833
I did some tests in windows and it seems to treat the files completely different with and without the .png in the name of the file, even not showing it as part of the name.

**Comment by ankar84** [comment]
Thanks Douglas!! I tested original docker image 4.2.0 and all save files are correct and with png extension! But I don't know when I can uograde my production environment to 4.2 version...
