### ISSUE TITLE
No official docker image for latest image 3 days after release

### ISSUE THREAD

**Issue by xavierpriour** [RocketChat/Rocket.Chat#20163]
### Description:

My rocket.chat instance is self hosted and deployed using docker, pulling the official image from docker hub.
A new version 3.10.3 was released 3 days ago, and I am getting a header warning "new version available, please update to 3.10.3" in rocket.chat.

But when I went to docker hub to perform the update, the latest version was still 3.10.0, pushed to docker 11 days ago (and released 14 days ago).

It would be great if a new official image was built (automatically?) right after tagging a new release.

### Steps to reproduce:

1. go to https://github.com/RocketChat/Rocket.Chat/releases/ latest release is 3.10.3
2. go to https://hub.docker.com/_/rocket-chat?tab=tags latest tag is 3.10.0

### Expected behavior:

When a new release is created on github, a new official docker image should be built and pushed to hub.docker.com at the same time.

### Actual behavior:

Official docker image is updated at least several days later, so there is a period of several days when people with docker version are left with an out-of-date version.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Debian
- Deployment Method: docker official image

**Comment by EnCz** [comment]
We use this repository: https://hub.docker.com/r/rocketchat/rocket.chat/tags?page=1&ordering=last_updated

Seems to be up2date all the time

**Comment by ankar84** [comment]
Here is an answer for your question in official documentation https://docs.rocket.chat/installation/docker-containers/available-images
`The Official Docker Images Repository is where Rocket.Chat's Official, stable image **is maintained and controlled by Docker**, and reviewed by the Docker committee.`

**Comment by sennewood** [comment]
Do Rocket.Chat has some influence to the build process of the official docker images?

**Comment by xavierpriour** [comment]
Oh I see, thanks so much for the answer, and sorry for not RTFMing.
I've switched to rocketchat/rocket.chat instead of rocket.chat and everything works.
It doesn't help that the "right" solution is only third entry when searching for rocket.chat on docker, but I guess there's nothing you can do about that.

And rocket.chat is an awesome product, thanks for all your time and dedication!

**Comment by sennewood** [comment]
The "right" solution for us is to wait till the image is curated by docker.
So ... it depends what "right" is :)
