### ISSUE TITLE
Star Icon doesn't disappear after unstarring a message

### ISSUE THREAD

**Issue by yash-rajpal** [RocketChat/Rocket.Chat#20187]
### Description:
Even after the message is unstarred, the star icon appears with the message. 

### Steps to reproduce:

1.  Goto any room and star a message.
2.  Now unstar the message.
3.  Even after the message is unstarred, it appears as starred.

### Expected behavior:
Unstarring a message should remove the star icon

### Actual behavior:
Unstarring the message doesn't remove star icon 

![before-star-message](https://user-images.githubusercontent.com/58601732/104435872-e76aae00-55b2-11eb-99ef-05b73cd5a2ed.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0 - develop
- Operating System: Ubuntu 20.10
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 
- Operating System: Ubuntu

### Additional context

The message gets unstarred in the backend, the problem lies within the UI part.

**Comment by Darshilp326** [comment]
@yash-rajpal  #19645 solves this :)

**Comment by yash-rajpal** [comment]
@Darshilp326 , Right, I didn't noticed.
