### ISSUE TITLE
[BUG] starredMessages screen menu doesn't close

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat#20184]
### Steps to reproduce:

1. Make sure the channel has at least one starred message
2. Go to the menu for the channel ('...')
3. Click on 'Starred Messages'
4. Hover over any starred message to get the menu ('...') and click on it.
5. Click anywhere. The menu just doesn't go away.

### Expected behavior:

For the menu to disappear on clicking on either one of the actions or elsewhere.

### Actual behavior:

The menu is stuck in place, and the user can't interact with any elements on the screen.

https://user-images.githubusercontent.com/38764067/104406792-20405e00-5586-11eb-8959-1c2af446f980.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop 
- Operating System: Ubuntu 20.10
- Deployment Method: Development
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.88 
- Operating System: Ubuntu 20.10

### Additional context

Solved the same issue for Pinned Messages earlier. Putting up a similar PR for this too.

### Relevant logs:

No relevant logs

**Comment by ankitpal1029** [comment]
@aKn1ghtOut  Isn't this the regular behaviour for any sidebar messages on the app. Like say if i try replying to a message the sidebar doesn't just go away by clicking i have to close it by pressing the x. Am i missing something here?

**Comment by aKn1ghtOut** [comment]
You're talking about something different. Look at the "steps to reproduce"
