### ISSUE TITLE
[BUG] In administration on selecting Info gives white screen.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20194]
### Description:

When we open administration, screen appears blank.
### Steps to reproduce:

1. Administration
2. Info
3. 

### Expected behavior:
Info should be displayed on screen

### Actual behavior:
Screen doesn't shows anything.

https://user-images.githubusercontent.com/55157259/104490024-55849480-55f6-11eb-9be6-20ef0cf852df.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
Is it happening with everyone?

### Relevant logs:
![Screenshot from 2021-01-13 23-14-40](https://user-images.githubusercontent.com/55157259/104490121-777e1700-55f6-11eb-979f-6c8d6d01eaf1.png)

**Comment by Darshilp326** [comment]
Can anyone guide me to solve this issue?

**Comment by Darshilp326** [comment]
![Screenshot from 2021-01-13 23-32-23](https://user-images.githubusercontent.com/55157259/104490998-9e891880-55f7-11eb-833d-76e410e1fb35.png)
This gives undefined:/

**Comment by yash-rajpal** [comment]
I am not sure, but works for me.
![image](https://user-images.githubusercontent.com/58601732/104494556-9e3f4c00-55fc-11eb-8ff0-4d191254b41e.png)

**Comment by Darshilp326** [comment]
Can anyone confirm the issue?

**Comment by ggazzo** [comment]
closed by: https://github.com/RocketChat/Rocket.Chat/pull/20180. this bug was never released, only on development

**Comment by Darshilp326** [comment]
@ggazzo Okay:)
