### ISSUE TITLE
User's Custom Statuses no longer displayed in Direct Chat

### ISSUE THREAD

**Issue by jdavis7718** [RocketChat/Rocket.Chat#20197]
### Description:

Custom User statuses don't appears in the windows at the top by Username on Direct Message Windows.   If you click the User Info button it appears in there, but that is not helpful.   It was helpful to see Custom Status Messages next to a user's name when direct messaging.    It use to appear much like how Topics appears in Rooms.
Request to reinstate the ability for Custom Status messages to be displayed in a direct message windows.

### Steps to reproduce:

1. Have any user set a custom status
2. Start a direct message with them

### Expected behavior:

Custom Status should appear by user's name in a direct message window

### Actual behavior:

No custom status appears, it is listed under user info only

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  3.10.0-1160.6.1.el7.x86_64
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.20.1
- MongoDB Version:3.6.21

### Client Setup Information

- Desktop App or Browser Version:  Both the latest desktop client and Chrome/Brave Browsers were used
- Operating System: Win 10 1909

**Comment by Manas502** [comment]
Hey, @jdavis7718 can you attach a screenshot to elucidate it a bit more?

**Comment by MJPGPleasant** [comment]
![image](https://user-images.githubusercontent.com/73244744/104630665-446c6f80-5658-11eb-8262-f60dac37e375.png)

Issue is reproducible in both 3.10.0 and 3.10.3. Although status is in the detailed information, it is missing in the conversation title bar.

**Comment by jdavis7718** [comment]
@MJPGPleasant thanks for supplying those screenshots.  That is exactly what I am referring to.

**Comment by Manas502** [comment]
@ggazzo Can I take up this issue?

**Comment by wreiske** [comment]
I was sad to see this regression :(.

**Comment by ggazzo** [comment]
> Thanks for the screenshot mate. @ggazzo Can I take up this issue?

Sure, I think it will be a little hard, but still feel free to try

Btw this is temporary only, we have plans to put this feature back soon as possible
