### ISSUE TITLE
Slack Compatible API for external integration

### ISSUE THREAD

**Issue by udnaan** [RocketChat/Rocket.Chat#202]
The external integration/plugin API should be slack compatible. That way, most of the available slack integrations don't need to be rewritten and can be simply reused.

**Comment by engelgabriel** [comment]
:+1:  that's the plan!

**Comment by Sing-Li** [comment]
@whitebeatle please detail your proposed plan-of-implementation, or add a link to your GitHub work in progress - thanks!   We can start the discussion here once we hear back from you.

**Comment by whitebeatle** [comment]
I have detailed them <a href="https://github.com/RocketChat/Rocket.Chat/issues/1175#issuecomment-150488531">here</a>

**Comment by graywolf336** [comment]
Can this be closed since it was implemented?
