### ISSUE TITLE
Error with created Message Links

### ISSUE THREAD

**Issue by Kulfadir** [RocketChat/Rocket.Chat#20204]
### Description:

When using the function 'Get Link' an Error appears.
![grafik](https://user-images.githubusercontent.com/44830091/104578101-9615f980-565a-11eb-9f59-11230bb25d40.png)
### Steps to reproduce:

1. Go into room.
2. Click on the 3 Points behind an Message
3. Click on 'Get Link'
4. Use this Link.

### Expected behavior:

No Error

### Actual behavior:

![grafik](https://user-images.githubusercontent.com/44830091/104577985-6a930f00-565a-11eb-9588-c6205b0965f5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Centos 8
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Desktop App and Browser (Firefox)
- Operating System: Windows

**Comment by Darshilp326** [comment]
@Kulfadir It's working fine for me:)

**Comment by Kulfadir** [comment]
> 
> 
> @Kulfadir It's working fine for me:)

Unfortunately not for me.

When i reload the page in the Browser (Strg+R), sometimes it happens sometimes not.

**Comment by jazztickets** [comment]
I get the same thing on 3.10.4, but also for direct messages and rooms. It also happens when you click the link in the notification email (the ones that say "You have been direct messaged by ______")

Seems to work fine in 3.7.4 though.

**Comment by Darshilp326** [comment]
@Kulfadir Are you present in that private group of which the message link is shared?

**Comment by Kulfadir** [comment]
> @Kulfadir Are you present in that private group of which the message link is shared?

Yes I am present in this group. 
Both pictures above  are my account. I used the private group 'zeiterfassung* for testing.

**Comment by jazztickets** [comment]
Upgrading to 3.11.0 fixed this for me.

**Comment by KevLehman** [comment]
This is working fine for me in 3.12 (latest). @Kulfadir , can you try updating and see if the error goes away? 
If so, don't forget to close this issue 😄

**Comment by Kulfadir** [comment]
@KevLehman, i use the snap version, so i can't update to 3.12. Snap is on 3.9.7.
I will test as soon as possible.

**Comment by andreybrasil** [comment]
Same problem here:

This problem has an influence in email notifications to messages sent offline since the links in the notification and those obtained via ‘Get Link’ follow the same pattern.

If I paste the link into a RocketChat conversation and click on it, it works. The problem is when it comes from outside of RocketChat or copied directly into the address bar of the browser.

    Version of Rocket.Chat Server: 3.9.7
    Operating System: Ubuntu 18.04.2 LTS
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: Enabled
    NodeJS Version: v12.18.4
    MongoDB Version: 3.6.14
    Proxy: ngnix
    Firewalls involved: no

**Comment by Kulfadir** [comment]
Tested new Snap-Version 3.10.5: problem still exists.

**Comment by andreybrasil** [comment]
Fixed for me in version 3.12.1. snap deploy.

**Comment by Kulfadir** [comment]
Fixed in snap 3.12.1.
