### ISSUE TITLE
unconfigure ldap setting

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#2021]
Hello.

I accidently enabled ldap authentication on a fresh rocket.chat installation. It seems there is no way to unconfigure that. Is there a configfile somewhere where i can unset this setting? To my big surprise even deletion of the Rocket.Chat directory and fresh install does not fix my issue. Thanks for any hints.

cheers
t.

**Comment by graywolf336** [comment]
You will need to update the database and/or delete the database if you haven't done anything major that you don't want to loose.

**Comment by himbeere** [comment]
Okay. Thanks.
