### ISSUE TITLE
@ - Mention can hide the users "Not in Channel" ?

### ISSUE THREAD

**Issue by StefanGan** [RocketChat/Rocket.Chat#20211]
### Description:
When type @ the list will show the user even no in the channel, can I hide it ?

### Steps to reproduce:
Go to a channel or private group
@username (which not in channel)
![image](https://user-images.githubusercontent.com/23218839/104675749-0dae5c00-5721-11eb-980f-2c22ad26c724.png)
it will show out

### Expected behavior:
Not in Channel user will not been show.

### Actual behavior:
it shows up on public channel and private group

### Server Setup Information:
Version of Rocket.Chat Server: 3.10.0-develop
Operating System: Ubuntu 16.04
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: 0
NodeJS Version: v812.20.1
MongoDB Version: 4.2.8
### Client Setup Information

- Desktop App or Browser Version: All include ReactNative
- Operating System: Window 10 pro

**Comment by StefanGan** [comment]
closed you may disable the permission "View Outside Room" to get this

**Comment by thekingbk90** [comment]
However, when you disable the permission "View Outside Room", you cannot search user on quick search view (Ctrl+K)
this permission should be separated
![image](https://github.com/RocketChat/Rocket.Chat/assets/9191227/61596d75-85b4-4225-8e5c-99e2f1ae2822)

**Comment by Conrado916645** [comment]
up
