### ISSUE TITLE
Code markdown is not showing syntax highlight

### ISSUE THREAD

**Issue by williamjamir** [RocketChat/Rocket.Chat#20218]
### Description:

Code markdown is not showing syntax highlight

### Steps to reproduce:

Type a code markdown, informing the language

![image](https://user-images.githubusercontent.com/5083518/104768545-a27a7f00-574c-11eb-8e8d-921c1e9aa318.png)

### Expected behavior:

The code with syntax highlight for python, without showing the language name

### Actual behavior:

![image](https://user-images.githubusercontent.com/5083518/104768444-73fca400-574c-11eb-9012-e1753f4f1e60.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version:  v12.18.4
- MongoDB Version: 3.6.14
--

### Client Setup Information

- Desktop App or Browser Version: Chrome 87.0.4280.141
- Operating System: Windows

**Comment by Karting06** [comment]
It's linked to this issue: https://github.com/RocketChat/Rocket.Chat/issues/19933

**Comment by ggazzo** [comment]
duplicated of https://github.com/RocketChat/Rocket.Chat/issues/19933
