### ISSUE TITLE
Threads and Discussion have white background in Dark mode.

### ISSUE THREAD

**Issue by calra123** [RocketChat/Rocket.Chat#20239]
### Description:

Threads and Discussions have a white background in Dark mode.

### Steps to reproduce:

1. On website version, click on the "moon" like icon on top left to Open Dark mode.
2. Click on Threads icon on the top right
3. The threads dialog will open with white background.

### Expected behavior:
In Dark mode, the Threads and Discussions dialog should have a Dark background. Similar to what we see, when we click on the Search icon.

### Actual behavior:
Threads is displayed with white background.

![image](https://user-images.githubusercontent.com/32410407/104845083-9da6fe00-58f9-11eb-94ec-52f3e6a04155.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Firefox 84.0.4 and Chrome  87.0.4280.141
- Operating System: Windows 10, 64 bit

### Additional context

I am using blender.chat

**Comment by aKn1ghtOut** [comment]
I don't believe a default dark mode is bundled yet with Rocket.chat. The good folks over at blender.chat would probably have to add additional css for the tabs to change the colors there.
If the administrators of the chat board believe this is a bug in Rocket.Chat, we could investigate further.
Right, @ggazzo @dougfabris ?

**Comment by JapneetSingh5** [comment]
I'll love to work on this!

**Comment by ankar84** [comment]
Look like that issue for that repo https://github.com/pbaity/rocketchat-dark-mode/issues

**Comment by sennewood** [comment]
It's another repo. True, but sad ^^

**Comment by dougfabris** [comment]
@calra123 Unfortunately we don't have an official dark mode theme. If it's an issue from a fork, please send the issue to the proper repository. Thanks for supporting us =)
