### ISSUE TITLE
Time and Date format not respected in Message Info panel

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#20247]
### Description:
When clicking on (i) info panel for a message, the time and date format remains in United States format, not localised settings.

### Steps to reproduce:

1. Click on : menu for message
2. Select Info

### Expected behavior:
Info panel dates and times should reflect settings set in Administration -> Message:

![Captur2](https://user-images.githubusercontent.com/1122344/104915036-28642780-59e4-11eb-8577-48eeda79fd6f.PNG)

### Actual behavior:
Dates and times remain in United States format.

![Capture](https://user-images.githubusercontent.com/1122344/104914870-df13d800-59e3-11eb-899d-99906df673f7.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Ubuntu 18.0.4 LTS
- Deployment Method: Manual, TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Firefox 84.0.2
- Operating System: Windows 10

### Additional context

Not yet.

### Relevant logs:

None relevant.

**Comment by sushant52** [comment]
Can you please elaborate on how do you find that 'Info' box containing list of all people who have read the message? I am unable to find it.

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.
