### ISSUE TITLE
High CPU Usage 

### ISSUE THREAD

**Issue by saigop** [RocketChat/Rocket.Chat#2024]
I have Ubuntu 14.04 with RocketChat installed. When multiple users log's in the CPU load is high, where the node application uses more CPU which is about 102%. 

CPU core - 8
RAM - 9 GB - only 1 GB utilized. 

Any comments would be much appreciated.

Thanks.

**Comment by Sing-Li** [comment]
Please post a screenshot of `top`  with the `1` key clicked ... displaying all the loads of the different cores.

**Comment by k0nsl** [comment]
What CPU model is it? I'm running my instance on two L5420 CPUs, albeit via KVM virtualization. My CPU usage is very low, but my memory usage is rather high (over 5GB). That's likely because I run it in "development mode" (e.g `git pull` followed by `meteor`).

How are you running your instance? Docker?

**Comment by jeffrapp** [comment]
https://i.imgur.com/Gv3TLqj.png

**Comment by saigop** [comment]
![rocketpeak](https://cloud.githubusercontent.com/assets/16423728/12573011/8a44d3b6-c419-11e5-9f80-f65c52a28e92.PNG)

Attaching the top screen shot

**Comment by saigop** [comment]
I have installed Rocket Chat wihtout docker, and running the application by settting up the environment variables with ROOTURL, MONGOURL and PORT post that nohup node manin.js & to capture the log in a out file.

**Comment by Sing-Li** [comment]
@saigop - just for our information.     You mentioned ...  _then moved back to the source package running under pm2_  ... how were you starting Rocket.Chat when the 100% CPU incident occurred?

**Comment by saigop** [comment]
I generally used to start nohup node main.js & form the RocketChat folder.

**Comment by jeffrapp** [comment]
@Sing-Li - I think you were referring to my post.  We were using the Docker container, both latest and develop were showing this issue.  I grabbed from source as a last-ditch effort - I had the PM2 config set up from a pre-docker experimentation - and it was experiencing the same issues.

Haven't had any serious issues with this since then, unless the service is restarting due to #1967

**Comment by Sing-Li** [comment]
Thanks @saigop and @jeffrapp.  This is likely a difficult to reproduce bug or config related one. Please try to gather as much console log as possible should this happen again.  Thanks again for all the help!

**Comment by Sing-Li** [comment]
@saigop and @jeffrapp  -- Can you please post the version info from:

`https://your-rocketchat-host/api/info`

Similar to:

```
{
  "version": "0.15.0",
  "compile": {
    "date": "2016-01-28T15:51:11.777Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-52-generic",
    "totalMemmory": 8373084160,
    "freeMemmory": 193224704,
    "cpus": 4
  },
  "commit": {
    "hash": "cd829c3f92ab6ef2bca8270afbfddadf2ad7eacc",
    "date": "Thu Jan 28 13:46:48 2016 -0200",
    "author": "Rodrigo Nascimento",
    "subject": "Disable WebRTC broadcastStatus"
  },
  "tag": "0.15.0",
  "branch": "develop",
```

Thanks!

**Comment by jeffrapp** [comment]
```
{
  "version": "0.15.0",
  "compile": {
    "date": "2016-01-29T21:46:05.147Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.16.0-59-generic",
    "totalMemmory": 8363171840,
    "freeMemmory": 4472664064,
    "cpus": 4
  },
  "commit": {
    "hash": "b5c9a8a45ed4faf9314ccfebf0ce2a2ca4d64fb0",
    "date": "Fri Jan 29 16:52:37 2016 -0200",
    "author": "Rodrigo Nascimento",
    "subject": "Add sort for all queries with limit"
  },
  "tag": "0.15.0",
  "branch": "develop",
  "GraphicsMagick": {
    "enabled": true,
    "version": "GraphicsMagick 1.3.18 2013-03-10 Q8 http://www.GraphicsMagick.org/\nCopyright (C) 2002-2013 GraphicsMagick Group.\nAdditional copyrights and licenses apply to this software.\nSee http://www.GraphicsMagick.org/www/Copyright.html for details.\n\nFeature Support:\n  Thread Safe              yes\n  Large Files (> 32 bit)   yes\n  Large Memory (> 32 bit)  yes\n  BZIP                     yes\n  DPS                      no\n  FlashPix                 no\n  FreeType                 yes\n  Ghostscript (Library)    no\n  JBIG                     yes\n  JPEG-2000                yes\n  JPEG                     yes\n  Little CMS               yes\n  Loadable Modules         no\n  OpenMP                   yes (201107)\n  PNG                      yes\n  TIFF                     yes\n  TRIO                     no\n  UMEM                     no\n  WMF                      yes\n  X11                      yes\n  XML                      yes\n  ZLIB                     yes\n\nHost type: x86_64-pc-linux-gnu\n\nConfigured using the command:\n  ./configure  '--build' 'x86_64-linux-gnu' '--enable-shared' '--enable-static' '--enable-libtool-verbose' '--prefix=/usr' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--docdir=${prefix}/share/doc/graphicsmagick' '--with-gs-font-dir=/usr/share/fonts/type1/gsfonts' '--with-x' '--x-includes=/usr/include/X11' '--x-libraries=/usr/lib/X11' '--without-dps' '--without-modules' '--without-frozenpaths' '--with-perl' '--with-perl-options=INSTALLDIRS=vendor' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-Wall -g -fno-strict-aliasing  -fPIE  -fstack-protector --param ssp-buffer-size=4  -D_FORTIFY_SOURCE=2  -Wformat -Wformat-security -Werror=format-security  -O2' 'LDFLAGS=  -fPIE -pie  -Wl,-z,relro  -Wl,-z,now ' 'CXXFLAGS=-Wall -g -fno-strict-aliasing  -fPIE  -fstack-protector --param ssp-buffer-size=4  -D_FORTIFY_SOURCE=2  -Wformat -Wformat-security -Werror=format-security  -O2'\n\nFinal Build Parameters:\n  CC       = gcc -std=gnu99\n  CFLAGS   = -fopenmp -Wall -g -fno-strict-aliasing -fPIE -fstack-protector --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -O2 -Wall -pthread\n  CPPFLAGS = -I/usr/include/X11 -I/usr/include/freetype2 -I/usr/include/libxml2\n  CXX      = g++\n  CXXFLAGS = -Wall -g -fno-strict-aliasing -fPIE -fstack-protector --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -O2 -pthread\n  LDFLAGS  = -fPIE -pie -Wl,-z,relro -Wl,-z,now -L/usr/lib/X11 -L/usr/lib -L/usr/lib\n  LIBS     = -ljbig -llcms2 -ltiff -lfreetype -ljasper -ljpeg -lpng12 -lwmflite -lXext -lSM -lICE -lX11 -llzma -lbz2 -lxml2 -lz -lm -lgomp -lpthread\n"
  },
  "ImageMagick": {
    "enabled": false
  }
}
```

**Comment by jeffrapp** [comment]
Had this happen again today.  Nothing specific in the logs - is there a way to turn up the verbosity?

**Comment by Sing-Li** [comment]
Thanks, @jeffrapp.  This is very useful information.   Unfortunately no way to change the verbosity at the moment.

**Comment by saigop** [comment]
Sorry for my delayed reply, mine is,

{
  "version": "0.10.2",
  "compile": {
    "date": "2015-12-22T21:49:50.737Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-63-generic",
    "totalMemmory": 7844462592,
    "freeMemmory": 5134458880,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "2769",
    "branch": "master",
    "tag": ""
  },
  "commit": {
    "hash": "99403fed7028093fed8f54f49690f78d80ff7f36",
    "date": "Tue Dec 22 19:45:02 2015 -0200",
    "author": "Gabriel Engel",
    "subject": "bump version to 0.10.2"
  },
  "tag": "v0.10.2",
  "branch": "HEAD",
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": false
  }
}

**Comment by saigop** [comment]
one more update, for last 48 hours, i didn't expect CPU load, since i have killed the service and started the rocket via pm2 and moreover not much user online. But my RAM usage is high, rocket chat node service uses 3 GB.

**Comment by Sing-Li** [comment]
@saigop and @jeffrapp   ... did either (or both) of you enabled the  optional `rocketchat-hubot` package?

**Comment by saigop** [comment]
no hubot was added in mine.

**Comment by jeffrapp** [comment]
I do have hubot installed, unsure if it was running at the time as we've been more or less testing with that aspect of the system.

**Comment by saigop** [comment]
From this morning, I noticed, my CPU usage and RAM usage got reduced automatically, not sure what happened, I not even restarted, but let me keep monitoring. By the way only few members are using, anyways let me keep monitoring.

**Comment by engelgabriel** [comment]
Is anyone still experiencing this kind of problem? Can we close this issue?

**Comment by saigop** [comment]
At this moment, I guess we can close this, not able to judge on anything, at times I see RAM is very high and automatically it comes down to utilization of 1 to 2 GB. In total i have 9 GB of RAM. Thinking to put in production, but at this moment, the ticket can be closed. Thanks for all your support.

**Comment by rauhmaru** [comment]
Hi, I have the same problem:

```
{
  "version": "0.45.0",
  "build": {
    "date": "2016-11-01T02:17:27.764Z",
    "nodeVersion": "v4.6.1",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.19.0-66-generic",
    "totalMemory": 7843983360,
    "freeMemory": 2162630656,
    "cpus": 2
  },
  "travis": {
    "buildNumber": "6317",
    "branch": "0.45.0",
    "tag": "0.45.0"
  },
  "commit": {
    "hash": "a9de8a40ce1c82be56fb6ace00ad91fab57deace",
    "date": "Tue Nov 1 00:08:40 2016 -0200",
    "author": "Gabriel Engel",
    "subject": "version bump to 0.45.0",
    "tag": "0.45.0",
    "branch": "HEAD"
  },
```

![image](https://cloud.githubusercontent.com/assets/2289237/19889251/a1b226ea-a012-11e6-9e65-95fba2d55483.png)

**Comment by DerTomm** [comment]
Same problem with a fresh installation of 0.45.0 on a CentOS 7 system.

**Comment by litewhatever** [comment]
Unfortunately seeing the same issue on CentOS 7. First I thought there was just heavy load and I added noded processes but this dosn't seem to help.
Could anyone advice how to debug what are those processes doing?

**Comment by borishinzer** [comment]
Same issue here with 0.48.2 and CentOS7. We can run RC for about a day and then it gets slow. Even a restart doesn't solve the issue only a reinstall "solves" it.

**Comment by Sing-Li** [comment]
@rauhmaru    @litewhatever   @DerTomm   @borishinzer     Please add as much information about your installation as possible to this new issue / thread :  

https://github.com/RocketChat/Rocket.Chat/issues/5379

**Comment by DerTomm** [comment]
Hi everyone.
For me the solution of issue [#4543](https://github.com/RocketChat/Rocket.Chat/issues/4543) solved the high CPU usage. My problem was that I had to install nodejs properly first to get the "n" binary running on CentOS. Now RocketChat works like a charm.
