### ISSUE TITLE
Unable to reset the list `AllowedDomainsList` to allow all domains for the livechat

### ISSUE THREAD

**Issue by dlecan** [RocketChat/Rocket.Chat#20251]
### Description:

I used to use the livechat for a specific list of allowed domains.
Now, I want to allow all domains, so the list `AllowedDomainsList` is now empty.
But the `content-security-policy` is wrong for most of the domains: these not included in the previous list).

### Steps to reproduce:

- Configure a first list of domains in `AllowedDomainsList`: `a.com`
- Check the CSP header for these domains:

`a.com`: ✅
```
$curl -v https://myinstance.rocket.chat/livechat -H "Referer:https://a.com/" 2>&1 | grep content-security-policy
< content-security-policy: frame-ancestors https://a.com
```
`c.com`, a domain not included in the list: ✅
```
$curl -v https://myinstance.rocket.chat/livechat -H "Referer:https://b.com/" 2>&1 | grep content-security-policy
< content-security-policy: frame-ancestors 'none'
```
So this domain is not allowed to load the livechat, as expected

- Now, clear the list `AllowedDomainsList` in the admin console
I double-checked through the API: the list is empty

- Check the CSP header for these domains:

`a.com`: ✅
```
$curl -v https://myinstance.rocket.chat/livechat -H "Referer:https://a.com/" 2>&1 | grep content-security-policy
< content-security-policy: frame-ancestors https://a.com
```
`b.com`, a domain not included in the list: ❌
```
$curl -v https://myinstance.rocket.chat/livechat -H "Referer:https://b.com/" 2>&1 | grep content-security-policy
< content-security-policy: frame-ancestors 'none'
```
So this domain is not allowed to load the livechat, although it should be.

### Expected behavior:

The CSP header should allow any domain because `AllowedDomainsList` is empty, but it doesn't allow any domains.
Strange, the domains of the previous list of allowed domains are working perfectly!

### Actual behavior:

Although the list of `AllowedDomainsList` is empty, domains not included in the previous list of `AllowedDomainsList` don't get the right CSP header.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Linux
- Deployment Method: Cloud instance
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: snap `rocketchat-desktop       3.2.0-snapshot`
- Operating System: Ubuntu 20.04

### Additional context

I encounter the same issue if I update the list of allowed domains (add or remove domains): only the "legacy" list of domains is considered :-(

**Comment by dlecan** [comment]
Sorry, the bug report was sent too early. It is now updated with the correct information.

**Comment by kingdsand** [comment]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> fibers@4.0.3 install /tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-72-glibc` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)
added 146 packages from 122 contributors and audited 147 packages in 5.726s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by dlecan** [comment]
Solved by asking the Rocket.chat support to restart our instance
