### ISSUE TITLE
"Error, too many requests. Please slow down" on channel's add user

### ISSUE THREAD

**Issue by adrianovieira** [RocketChat/Rocket.Chat#20263]
### Description:

Error trying to add user on a channel.
It appears on UI as you can see below.

### Steps to reproduce:

1.  open a channel
2.  Members
3.  Add users
4. Choose users field
5. fill it with letters of an user that doesn't exists
6. hit backspace

### Expected behavior:

None of that red banner be shown

### Actual behavior:

![Captura de tela de 2021-01-19 12-09-29](https://user-images.githubusercontent.com/5561794/105056365-de665a80-5a52-11eb-8365-7bac40f274b3.png)

The error happens and it doesn't matter if we use desktop app or a browser (e.g.: firefox)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: redhat-7
- Deployment Method:  manual/tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: desktop 3.1.1 / firefox 84.0.2
- Operating System: anyone

**Comment by adrianovieira** [comment]
This error also happens if we copy and paste the username to search for and try to add.

**Comment by Darshilp326** [comment]
@dougfabris Any leads? The API rate-limit limit is getting reached.
![Uploading Screenshot from 2021-01-20 01-40-59.png…]()

**Comment by Darshilp326** [comment]
@dougfabris Any lead? The API rate-limit limit is being reached.
![Screenshot from 2021-01-20 01-40-59](https://user-images.githubusercontent.com/55157259/105087659-d6450400-5ac0-11eb-8a6a-6f3c3618c8db.png)

**Comment by dougfabris** [comment]
@Darshilp326 Not yet. I'm going to find out

**Comment by Darshilp326** [comment]
@dougfabris have you fixed this issue?

**Comment by dougfabris** [comment]
> @dougfabris have you fixed this issue?

Not yet, do you have any guess? Please, send me a message on our open server!

**Comment by Darshilp326** [comment]
@dougfabris Your username?

**Comment by dougfabris** [comment]
@Darshilp326 The same
