### ISSUE TITLE
Generate a package like rocket.chat.cordova.

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#2026]
I  made ​​some changes to rocket.chat, adding a few pages and css styles , and I have a question: how can I generate a package like rocket.chat.cordova.

**Comment by Micjoyce** [comment]
Due to the css styles built in server, when I run 'meteor run ios', it can't load styles and shows me the blank screen.

**Comment by geekgonecrazy** [comment]
@Micjoyce if you have a style change, you should just be able to do a build, the mobile app will pull those down.

Please reach out on the demo server on the [#support](https://demo.rocket.chat/channel/support) and we'll see if we can help you out.
