### ISSUE TITLE
User/Channel mention markdown fails

### ISSUE THREAD

**Issue by Endareth** [RocketChat/Rocket.Chat#20268]
### Description:
When mentioning a user or channel within a message, the markdown fails to work for the object unless it's the end of line

### Steps to reproduce:
1. Start a message in any channel/dm
2. Send something like: "Test message to @username about something"

### Expected behavior:
Resultant message shows clickable and coloured display name for @username

### Actual behavior:
Resultant message still just shows @username raw text

### Server Setup Information:
- Version of Rocket.Chat Server: 3.9.3 (has been happening since at least 3.7)
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: All Windows/macOS desktop apps, browsers, mobile clients
- Operating System: Window 10, Server 2016, macOS 10.14+, iOS 12+

### Additional context

If the object is at the end of the line, it gets displayed/marked up correctly. User/Channel lookup while type works fine.

### Relevant logs:
Nothing in the browser/client logs. Attempting to get server logs via web interface just results in a frozen browser window.
Server log when test message sent:
```
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]: server.js:204 Meteor ➔ method readMessages -> userId: rij4meNzbZgZxojtp, arguments: ["rij4meNzbZgZxojtprij4meNzbZgZxojtp"]
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]: server.js:204 Integrations ➔ Outgoing WebHook.debug Execute Trigger: sendMessage
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]: server.js:204 Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: sendMessage {
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:   event: 'sendMessage',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:   message: {
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     _id: 'txnEznYMDQLk7RPvt',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     rid: 'rij4meNzbZgZxojtprij4meNzbZgZxojtp',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     msg: 'test @username dasasd',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     ts: 2021-01-20T01:54:12.159Z,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     u: {
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:       _id: 'rij4meNzbZgZxojtp',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:       username: 'username',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:       name: 'User Name'
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     },
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     tmid: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     _updatedAt: 2021-01-20T01:54:12.180Z,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     editedBy: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     editedAt: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     emoji: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     avatar: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     alias: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     customFields: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     groupable: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     attachments: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     reactions: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     parseUrls: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     blocks: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     token: undefined,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     mentions: [],
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     channels: []
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:   },
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:   room: {
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     _id: 'rij4meNzbZgZxojtprij4meNzbZgZxojtp',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     usernames: [ 'username', 'username' ],
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     _updatedAt: 2021-01-20T01:53:28.195Z,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     t: 'd',
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     msgs: 27,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     ts: 2018-02-19T06:10:44.972Z,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     usersCount: 1,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     lm: 2021-01-20T01:53:28.170Z,
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:     uids: [ 'rij4meNzbZgZxojtp', 'rij4meNzbZgZxojtp' ]
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]:   }
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]: }
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]: server.js:204 Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: rij4meNzbZgZxojtprij4meNzbZgZxojtp
Jan 20 01:54:12 **REDACTED** rocketchat-server.rocketchat-server[943]: server.js:204 Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event.
```
Can try to dig up further logs if needed.

**Comment by aditya-mitra** [comment]
Hey @Endareth, thanks for raising this issue.

I tried to reproduce your issue.

**what I did**
- I mentioned the user in message body
- I sent the message by pressing enter key in the beginning, middle and end of the text message
- I also tried mutli-line mentions
- I tried this in both as an admin and normal user

![image](https://user-images.githubusercontent.com/55396651/105312434-ae01f600-5be3-11eb-9174-92012a00a716.png)

If I am doing something wrong, you can tell me how to redo it correctly

**Comment by Endareth** [comment]
Thanks for looking into this. Your attempts to reproduce are fine, seems likely that whatever is going wrong is a result of either config or user/channel data in our system. Most likely config, seems unlikely the same weirdness would be in both user and channel data. The issue has been happening for us for at least 4-5 months now, so it's not anything recent. I've included a screenshot of how it looks. There were no config changes that triggered it as far as I can tell, it just started happening out of the blue. Best guess from me is that there's some server call that's made for each object, and something in that call is failing and the markdown aborts.

![image](https://user-images.githubusercontent.com/6863373/105322308-cf330880-5c1c-11eb-8081-dd5badb1c833.png)

**Comment by aditya-mitra** [comment]
You are right @Endareth .
It must be some config issue. It does not happen in the official [Rocket.Chat Server](https://open.rocket.chat/).

Maybe you can try to upgrade your Rocket.Chat server to 3.10.4 and see if the issue still persists.

If it's gone, don't forget to close this issue :D

**Comment by Endareth** [comment]
Still waiting for that version to be deployed to snap, but unless you have some particular reason to expect that to fix the issue, I'm not hopeful (given this has been happening to us since Apr 2020).

**Comment by dext0r** [comment]
It seems that a whitespace character in the UTF8_Channel_Names_Validation setting causes the issue. See https://github.com/RocketChat/Rocket.Chat/issues/7488#issuecomment-624247512

**Comment by hugocostadev** [comment]
It was already fixed and there is already a Release Candidate. Soon we will be released the official Release.
