### ISSUE TITLE
White bar divider is not properly placed between profile pictures

### ISSUE THREAD

**Issue by andylin2004** [RocketChat/Rocket.Chat#20269]
### Steps to reproduce:

1.  Go create a new direct message with multiple people in them (create -> direct message)
2.  Press create.
3.  The issue will pop up with the profile picture bar over the "you have created a new direct message with"

### Expected behavior:

White divider lines are placed such that part of group chat members' profile picture "bleeds" through the line to the left of the line

### Actual behavior:

White divider line are placed such that it divides profile pictures cleanly and there is no "bleed"
![image](https://user-images.githubusercontent.com/60021592/104782603-7d890a80-5752-11eb-909f-6cbf5f393ca7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Unknown
- Deployment Method:  Unknown
- Number of Running Instances: Unknown
- DB Replicaset Oplog: Unknown
- NodeJS Version: Unknown
- MongoDB Version: Unknown

### Client Setup Information

- Desktop App or Browser Version: Desktop App (3.1.1) and Microsoft Edge on Chromium (87.0.664.75)
- Operating System: Windows 10 20H2

### Relevant logs:

N/A; this is a UI bug

**Comment by yash-rajpal** [comment]
I don't think its a UI bug, Its only happening when we zoom to 125% or 175%. Not happening at any other zoom levels.
I tested on chrome browser at 100, 110,125,150,175,200,400,500 percents of zoom level.

**Comment by andylin2004** [comment]
Hmm. In this case, it’s an issue for users that have screens scaled to 125% (I have a 15.6 inch display that outputs 1080p but is at 125% scaling)

**Comment by yash-rajpal** [comment]
Yes, I am not sure what can be done for this.
@dougfabris Can you have a look and tell us if anything can be done for it?

**Comment by dougfabris** [comment]
@yash-rajpal @andylin2004 I don't think it's a bug in UI since it just happens when zooming 125%. Closing because it's very cosmetic to concern for now. Thanks for the report.
