### ISSUE TITLE
Several users can't increase or reduce counter of emoji at the bottom of the message

### ISSUE THREAD

**Issue by SLRover** [RocketChat/Rocket.Chat#20275]
### Description:

When a user tries to append existing emoji at the bottom of the message, nothing happens. And when the user adds a new emoji, he can't remove it.

### Steps to reproduce:

1. Adding a new emoji at the bottom of the message
2. Trying to remove it
3. Trying to append emoji, which was added by another user

### Expected behavior:

Counter of emoji at the bottom of the message would be increase or reduce

### Actual behavior:

Nothing happens. Counter stays the same.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: Latest Chrome or Firefox, Desktop clients v3.0.7 or 3.1.1
- Operating System: Windows, Linux, MacOS

**Comment by aKn1ghtOut** [comment]
Can you please try with the updated build. Should be solved by #20159

**Comment by SLRover** [comment]
Thank you! We updated our stage to dev build and it's works! Now we are waiting for the new release with this bugfix.

**Comment by aKn1ghtOut** [comment]
This can be safely closed @dougfabris @ggazzo

**Comment by dougfabris** [comment]
@aKn1ghtOut Thank you mate!
