### ISSUE TITLE
Add hook to gracefully shutdown rocketchat

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#2027]
Hello Devs.

How am i supposed to stop rocketchat? I'm trying to write an initscript but it's not clear to me how to stop the application. Do i really have to work with ps auxx and kill?

thanks and cheers
t.

**Comment by k0nsl** [comment]
Are you running Rocket.Chat simply via `meteor`? If so, I usually just `kill -9 [pid]` when I need to restart it, stop it, or pull new code.

**Comment by Sing-Li** [comment]
@himbeere - thanks, I've converted this ticket to a feature request for a shutdown hook.

We already have a restart button; we need a hook (via a route and shared secret token?) to gracefully shutdown the server.

**Comment by mikrobyte** [comment]
if i try doing the kill option it keeps coming back up, even if i kill it as root.

**Comment by mikrobyte** [comment]
sudo pm2 stop 0

**Comment by geekgonecrazy** [comment]
Are you wanting a route to call or just for Rocket.Chat to handle shutdown gracefully?

Because to do that we'd just need to handle SIGTERM and maybe SIGHUP (windows)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
