### ISSUE TITLE
[BUG]  User cannot change password via the profile page

### ISSUE THREAD

**Issue by NCDemonic** [RocketChat/Rocket.Chat#20274]
### Description:

Users cannot set a new password via the profile page (neither in the client nor in the browser).
After entering two idenitical new passwords there is always the error "invalid-password-password"

I tested the behaviour with various settings combinations (enabled/disabled password policy, allowed/disallowed different profile change settings)

### Steps to reproduce:

1. Use Broswer or Deskop App
2. Go to Profile
3. Enter new password
4. Second field appears for password repetetion
5. Click on save
6. Error "error-invalid-password" is shown

### Expected behavior:

The password should be changed, so that the user can use the new password to login.

### Actual behavior:

An error "error-invalid-password" is shown and the password is not changed

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: Debian 10.7 (4.19.0-13-cloud-amd64)
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v12.18.4
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: 
     * Desktop Client 3.0.7; 
     * Google Chrome 87.0.4280.141
     * Firefox 87.0.4280.141
- Operating System: Windows 10, Debian 10.7 KDE

### Relevant logs:
There is nothing in the browser Log.
The server log shows no exceptions.

Please tell me which logs I could provide?

**Comment by MJPGPleasant** [comment]
Possible duplicate of https://github.com/RocketChat/Rocket.Chat/issues/19604?

**Comment by NCDemonic** [comment]
Yes, seems it is a duplicate. Did not find this bug during my search. Sorry fur double open

**Comment by HLFH** [comment]
@NCDemonic I confirm it is duplicate, you can close the issue, thanks :)

**Comment by NCDemonic** [comment]
Duplicate

**Comment by billynoah** [comment]
Affects me / v3.10.5 installed via snaps on Ubuntu 20.04
