### ISSUE TITLE
Room leader always displayed as offline

### ISSUE THREAD

**Issue by NateScarlet** [RocketChat/Rocket.Chat#20270]
### Description:

status of room leader on top always offline, never updated when actual status change.

### Steps to reproduce:

1. Create a room
2. Set other user as leader
3. Login other user
4. See leader status

### Expected behavior:

leader has correct status

### Actual behavior:

![image](https://user-images.githubusercontent.com/21083014/105148009-d8e53f00-5b3c-11eb-9fba-044adcab3660.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: linux
- Deployment Method: docker (rocket.chat@sha256:fe64485e67923134f53a51c742ec6ec90ccf47539c54bab82a9c9d1241eda93b)
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: crhome 87.0.4280.141, rocket.chat desktop 3.1.1
- Operating System: Windows 7 7601

**Comment by TimmiORG** [comment]
Same for we with 3.10.4.

**Comment by aditya-mitra** [comment]
I guess the problem is here:

Only the current user model is accessible in the client. 
So, this line always return `undefined` - [app/ui/client/views/app/room.js#L245](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/ui/client/views/app/room.js#L245)

I could not figure a workaround (I tried to look for `utils` which could get the `userStatus` but found none).

**Comment by TimmiORG** [comment]
Still the same in 3.18.1.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and it was fixed here: #27576

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
