### ISSUE TITLE
[BUG] Wrong name in Room Info with special characters on

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat#20278]
### Description:

The Room Info panel shows the wrong name.
When the setting "Allow Special Characters in Room Names" is enabled, the panel show the normalized name instead of those that contain the special characters.

### Steps to reproduce:

1. Login as administrator
2. Go to Administration
3. Under "Layout", check "Allow Special Characters in Room Names"
4. Change the name of a room to "The Room ;;"
5. The Room Info panel shows the name to be "the-room" instead of "The Room ;;"

### Expected behavior:

For the room to be called "The Room ;;"
![Expected](https://user-images.githubusercontent.com/38764067/105181456-d3deba80-5b51-11eb-91aa-77719748c745.png)

### Actual behavior:

The room is called "the-room"
![Actual](https://user-images.githubusercontent.com/38764067/105181465-d7724180-5b51-11eb-8033-0ab1572b3972.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.10
- Deployment Method: develop
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.88
- Operating System: Ubuntu 20.10

### Additional context

This is the only other instance I could spot where the wrong name is still being used.
Solution PR is about ready to go.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
