### ISSUE TITLE
"show thread messages in the main thread" will be disabled in a few days.

### ISSUE THREAD

**Issue by uni-infra** [RocketChat/Rocket.Chat#20289]
### Description:

Enabled "show thread messages in the main thread". But the next day it will be invalid.

### Steps to reproduce:

1. Enabled "show thread messages in the main thread".
 Administration > Accounts > Default User Preferences > Show thread messages in the main thread

2. Thread messages are successfully displayed on the main thread.

3. The next day I notice that the thread message is not showing up in the main thread.

4. "show thread messages in the main thread" was disabled.

### Expected behavior:

Keep "show thread messages in the main thread" enabled.

### Actual behavior:

The next day I notice that the thread message is not showing up in the main thread.
"show thread messages in the main thread" was disabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: CentOS 7.9 2009
- Deployment Method: https://docs.rocket.chat/installation/manual-installation/centos
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version:4.0.22

### Client Setup Information

- Desktop App or Browser Version:
RocketChat Client 3.0.6
Chrome 87.0.4280.141

- Operating System:
Windows 10

### Additional context

none

### Relevant logs:

none

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
