### ISSUE TITLE
[BUG] Improper rendering of bio in UserCard

### ISSUE THREAD

**Issue by pratyaksh123** [RocketChat/Rocket.Chat#20283]
### Description:

When you click on a user, while the user card is loading,` MarkdownText.js` renders [ Object Object ] in place of bio ( after a few sec then correct bio shows up ).
![Screenshot from 2021-01-20 17-07-56](https://user-images.githubusercontent.com/55044774/105186072-5453ea00-5b57-11eb-8cc8-3f55dcad1897.png)

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:
It should just show a skeleton view.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method:
- Number of Running Instances:
- DB Replicaset Oplog:
- NodeJS Version: 12.18,4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Darshilp326** [comment]
@pratyaksh123 Hello! Is it happening still?
