### ISSUE TITLE
[BUG] Inconsistency in embedded view messageBox

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat#20293]
### Description:

The messageBox shows the formattingTips in thread view but is specifically/intentionally suppressed in roomView, when using the embedded layout.

### Steps to reproduce:

1. Open any thread in a channel
2. Add "?layout=embedded" at the end of the URL.
3. With room and thread view sided by side, the inconsistency is apparent.

### Expected behavior:

For both of them to use the same ruleset for embedded layouts

### Actual behavior:

Embedded room:
![Screenshot from 2021-01-21 15-20-00](https://user-images.githubusercontent.com/38764067/105337518-866d5680-5c00-11eb-878f-cf9a2757c52a.png)

Embedded thread: 
![Screenshot from 2021-01-21 15-19-39](https://user-images.githubusercontent.com/38764067/105337549-8c633780-5c00-11eb-9890-db2d74409d48.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.10
- Deployment Method: develop
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.88
- Operating System: Ubuntu 20.10

### Additional context

Also worth exploring: #20254

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
