### ISSUE TITLE
highlight keywords block emojis from appearing

### ISSUE THREAD

**Issue by dcermak** [RocketChat/Rocket.Chat#20295]
### Description:

When the user has a highlight keyword configured that is included in the name of an emoji, then the keyword will take precedence over the emoji:

![Clipboard - January 21, 2021 11 44 AM](https://user-images.githubusercontent.com/45594031/105341486-72652d00-5bdf-11eb-9a3b-cf18c55a0261.png)

### Steps to reproduce:

1. Add a highlight word in your account settings under Preferences, e.g. `thinking`.
2. Reload RC
3. Enter the text `:thinking:`
4. Instead of :thinking: you'll see:
![image](https://user-images.githubusercontent.com/45594031/105341840-df78c280-5bdf-11eb-94b3-aa7f48b3c5d2.png)

### Expected behavior:

Emojis should not trigger highlight keywords, or at least they should be still rendered (but that will be very confusing UX).

### Actual behavior:

![image](https://user-images.githubusercontent.com/45594031/105341840-df78c280-5bdf-11eb-94b3-aa7f48b3c5d2.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.10.4
- Operating System: Linux
- Deployment Method: k8s
- Number of Running Instances: 4
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.11

### Client Setup Information

- Desktop App or Browser Version: Firefox 84
- Operating System: Fedora/openSUSE Tumbleweed

### Additional context

This issue is also present on https://open.rocket.chat.

### Relevant logs:

No logs found in the browser.

**Comment by im-adithya** [comment]
Yes. I'll work on this.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
