### ISSUE TITLE
the letter "ş"

### ISSUE THREAD

**Issue by turkasoft** [RocketChat/Rocket.Chat#203]
" ş " letter appears to be corrupt 

![sharfi](https://cloud.githubusercontent.com/assets/4641951/8245937/96387a08-163e-11e5-916d-a85e726fcb6a.png)

**Comment by engelgabriel** [comment]
What language file is this?

**Comment by turkasoft** [comment]
Turkish

**Comment by marceloschmidt** [comment]
@turkasoft is this an isolated case or all "ş" are corrupt? 

"Yeni bir kanal oluştur"
"Geçmiş"
"Giriş yap"

Are those also corrupt on Rocket.Chat? 

Thanks.

**Comment by marceloschmidt** [comment]
BTW, we are not using that phrase anymore, so if it was an isolated case, we can close this issue.

**Comment by turkasoft** [comment]
There are now only uppercase letter trouble. I think the font does not support Turkish characters

![](http://i.imgur.com/EDDJ8f1.png)

**Comment by marceloschmidt** [comment]
I don't think I get what the problem looks like to you... Here's how it shows up to me if I choose Turkish language: 

![image](https://cloud.githubusercontent.com/assets/1986378/8336315/f08e0c36-1a79-11e5-9c28-961f7ec94ea4.png)

Do you think this might be a wrong encoding? My encoding is set to UTF-8, what's yours?

![image](https://cloud.githubusercontent.com/assets/1986378/8336347/2c9b3e4c-1a7a-11e5-8066-a211210b05c9.png)

**Comment by turkasoft** [comment]
the problem is that it's not the side menu. http://rocket.chat/room/8DKrxMs3YJqMQjWrq in the field of chat

**Comment by marceloschmidt** [comment]
We found out this is a problem with Roboto font under Linux. Please @rcaferati, could you change it to something else?

**Comment by sampaiodiego** [comment]
seems to be a font render issue.. changing font-size to 17px, it seems ok:
![image](https://cloud.githubusercontent.com/assets/8591547/8338665/af9d8ea4-1a88-11e5-855a-95836933f3d8.png)

**Comment by marceloschmidt** [comment]
Is this still a problem? If so, we may reopen.
