### ISSUE TITLE
Mongo DB is reaching 100% of CPU every day on 11am. 

### ISSUE THREAD

**Issue by abraaobarros** [RocketChat/Rocket.Chat#20302]
### Description:
We are heavy user of rocket.chat and, after 2000 users we start to be unstable just in the same time every day. 
We always have to scale de mongo db and come back after this period. Profiling the mongo database we can see much effort on rocketchat__trash scheme. sometimes achieve 100% of cpu only with this entity. 

Seems to be some cron job or garbage collector in this time. Any one could help me to understand what's is happening?

### Expected behavior:

 This kind of operation has to occur only after hours of working.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0-develop
- Operating System: Linux
- Deployment Method:  docket
- Number of Running Instances: 4
- DB Replicaset Oplog: 
- NodeJS Version: v12.16.1
- MongoDB Version: 4.2.11

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System:

**Comment by 564064202** [comment]
just a job delete history meesage. 
but an evil is waiting for you:more users 3.5k eg. will crash your docker instance every day

**Comment by abraaobarros** [comment]
Do you know how can I shift this job to another time?
