### ISSUE TITLE
[BUG] Notification sound tooltip position obstructs volume level text

### ISSUE THREAD

**Issue by sushant52** [RocketChat/Rocket.Chat#20309]
### Description:

The tooltip position under accout->preferences->sound->notification sound voulme obstructs the text telling the current sound volume.

### Steps to reproduce:

1. Go to My Account->Preferences->Sound->Notifications sound volume
2. The text showing volume level is obstructed by some black box.

### Expected behavior:

![Screenshot from 2021-01-22 16-51-17](https://user-images.githubusercontent.com/54909147/105485672-488d3280-5cd3-11eb-97a5-18f92a58ddfa.png)

### Actual behavior:

![Screenshot from 2021-01-22 16-50-46](https://user-images.githubusercontent.com/54909147/105485698-504cd700-5cd3-11eb-9a1c-cfbed1b53f6e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 18.04
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Working on this.

**Comment by yash-rajpal** [comment]
similar to #20236

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
