### ISSUE TITLE
Images from paste, upload and app operations display with incorrect ratio.

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#20307]
### Description:

Images that are added to the message window as a result of a paste, upload or an app operation (such as `/giphy`, `/tenor`) are showing up with incorrect ratio.

### Steps to reproduce:

1. Add an image to the message list, or:
2. Use the `/giphy` or `/tenor` apps to add a GIF.

### Expected behavior:
The image displayed should have the proper aspect ratio.

### Actual behavior:
The image appears distorted until you click on it.
![image](https://user-images.githubusercontent.com/14616851/105419218-f3ceb680-5c03-11eb-92d4-003bfc1947b8.png)
![image](https://user-images.githubusercontent.com/14616851/105419433-4f993f80-5c04-11eb-89f1-f49726e772c2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.04 (docker deployment)
- Deployment Method: docker 
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10 20H2

**Comment by aditya-mitra** [comment]
@bkraul Thanks for opening this issue.

The GIF images are smaller as shown using the `/tenor` or `/giphy` command. When they are sent, they appear much larger in size.

Is that what you meant to say? Please correct me if I am wrong.

**Comment by aditya-mitra** [comment]
![image](https://user-images.githubusercontent.com/55396651/105494898-79746400-5ce1-11eb-810d-c6a3ba737366.png)

**Comment by bkraul** [comment]
No. The problem is that they do not show up with the correct ratio. They appear distorted to fit the rectangle in which they are shown. This was not so before.

**Comment by aditya-mitra** [comment]
### In the Channel

![image](https://user-images.githubusercontent.com/55396651/105495344-13d4a780-5ce2-11eb-80b8-57058ea1cfe9.png)



### When Clicked and Opened

![image](https://user-images.githubusercontent.com/55396651/105495235-ef78cb00-5ce1-11eb-80dc-8ed7f89e7cba.png)


@bkraul Am I correct?

**Comment by bkraul** [comment]
Yes, when you click on it it shows the correct ratio. What should be happening is that the preview ratio should match the image ratio, even if scaled. Here is another example with the **imgur** app:

**Comment by bkraul** [comment]
![image](https://user-images.githubusercontent.com/14616851/105495730-23240880-5c82-11eb-9c3e-955c4eaaa937.png)

**Comment by bkraul** [comment]
![image](https://user-images.githubusercontent.com/14616851/105495813-3afb8c80-5c82-11eb-80fa-350c7b082eec.png)

**Comment by mmgoilf** [comment]
We have the same issue, was going to open a new issue but good to see someone else already did.

**Comment by bkraul** [comment]
This behavior is partly back on develop 8abc78e2e . Giphy app is back to this:

![image](https://user-images.githubusercontent.com/14616851/116439079-c3a33f00-a814-11eb-9397-493f4fb741bd.png)

**Comment by Bengrunt** [comment]
I confirm this is back in v3.14.0.

**Comment by matthias4217** [comment]
This is still an issue on Rocketchat 4.2.0.

**Comment by WLR86** [comment]
Still happening.

**Comment by bkraul** [comment]
That is correct, persists on 4.4.0-develop:

![image](https://user-images.githubusercontent.com/14616851/149516676-149519b7-f62b-4cc2-81b8-db83ca59465a.png)
![image](https://user-images.githubusercontent.com/14616851/149516782-4a3dc1cc-7237-4341-91a8-d59cfbb2f188.png)

**Comment by thrakks** [comment]
Still broken as of 4.7.0. This is ridiculous.

Server Version:
![image](https://user-images.githubusercontent.com/7259522/166853262-4d39a45e-4a1b-4a13-b244-f2bfb33d6aac.png)

Expected Ratio:
![image](https://user-images.githubusercontent.com/7259522/166853336-b49058eb-7a2f-4004-9ae1-8dc0df49fbb3.png)

Actual Ratio:
![image](https://user-images.githubusercontent.com/7259522/166853302-7e4e2c28-2a47-4f97-9ced-fdc81333fe50.png)

**Comment by thrakks** [comment]
Still Broken as of 4.8.0 
Server Version:
![image](https://user-images.githubusercontent.com/7259522/171790297-be1c7cdf-81ab-49a6-beb5-dc068e002572.png)

Expected Ratio:
![image](https://user-images.githubusercontent.com/7259522/166853336-b49058eb-7a2f-4004-9ae1-8dc0df49fbb3.png)

Actual Ratio:
![image](https://user-images.githubusercontent.com/7259522/166853302-7e4e2c28-2a47-4f97-9ced-fdc81333fe50.png)
