### ISSUE TITLE
[BUG] upvote reaction 

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat#20304]
On Rocket chat 3.10.4 it is not possible to upvote reactions on messages. Single upvote is possible but upvote existing reatcion is not possible.

### Steps to reproduce:

1. go to a message ad a reaction and upvote an existing reaction

### Expected behavior:

counter adds the reaction

### Actual behavior:

no addition 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: latest
- NodeJS Version: latest
- MongoDB Version: latest

### Client Setup Information

Browser / W10 / Mac / chrome latest

**Comment by aKn1ghtOut** [comment]
Solved by #20159. This can be closed. It should be corrected in the next release
