### ISSUE TITLE
Multiple users unable to reply to a message with the same emoji

### ISSUE THREAD

**Issue by youvegotmoxie** [RocketChat/Rocket.Chat#20319]
### Description:

After upgrading to Rocket.Chat 3.10.4 we noticed users are now unable to use the same emoji when replying to a channel message.

### Steps to reproduce:

1. Type a message in any channel
2. Use the add reaction button to add an emoji reply to the above message
3. Have another user attempt to click the added emoji and observe that the number of emojis does not increment

### Expected behavior:

More than one user should be able to use the same emoji as a response to a message

### Actual behavior:

The number of the same emoji per message does not increment

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: CentOS 7.8.2003
- Deployment Method: Docker
- Number of Running Instances: 4
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: Desktop app
- Operating System: macOS Big Sur and Windows 10

**Comment by aKn1ghtOut** [comment]
Solved by #20159. This can be closed. It should be corrected in the next release
