### ISSUE TITLE
[BUG] Custom emoji name/aliases cannot be updated without uploading a new file.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20316]
### Description:
Admin cannot update name/aliases without uploading a new emoji file.

### Steps to reproduce:

1. Administration.
2. Custom Emoji.
3. Any existing custom emoji.

### Expected behavior:
Admin should be able to update name/aliases without uploading a new emoji file.

### Actual behavior:
Admin has to upload a new emoji file for updating name/aliases.

https://user-images.githubusercontent.com/55157259/105524025-1e546880-5d05-11eb-87d2-406c5c500bc0.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working on it!

**Comment by Teak-Rosewood** [comment]
Hey! im looking to contribute @hugocostadev, is this issue still open?
