### ISSUE TITLE
[BUG] New custom emoji can be added without uploading file.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20317]
### Description:
Admin can make a new custom emoji without uploading a file.

### Steps to reproduce:

1. Administration
2. Custom Emoji
3. Add a new emoji

### Expected behavior:
The error message should be displayed.

### Actual behavior:
Admin can create new custom emoji without adding the file.

https://user-images.githubusercontent.com/55157259/105524664-f1548580-5d05-11eb-9543-a0daae2dc3ec.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working on it!

**Comment by sushant52** [comment]
I think issue #20316 is the same as this one?

**Comment by Darshilp326** [comment]
@sushant52 No
