### ISSUE TITLE
Save/log all messages for SOX/SEC compliance etc

### ISSUE THREAD

**Issue by dupree972** [RocketChat/Rocket.Chat#2032]
Is there any way to keep a running backup of messages or log all the messages out to a file to be sent to a service like smarsh. We need to keep archives of all messages in some kind of restorable/searchable form for compliance as do many businesses in financial or health care. Has anyone done this or know how to approach this with rocket.chat.

**Comment by graywolf336** [comment]
What exactly are the requirements for being 100% compliant? As we are extremely interested in making sure Rocket.Chat is compliant so everyone can use it.

**Comment by dupree972** [comment]
I work for a financial company which is regulated by SEC and CFTC and FINRA. Mostly what is necessary is a way to export all chats in a easily searchable/readable format for Compliance. In general companies often use a service like SMARSH, IRON Mountain or some other provider to archive these are they are not really looked at except in the case of a compliance query. We use SMARSH which has integration with Lync and Slack. I believe in the case of slack they just send a JSON file formatted to SMARSH's requirements for them to injest. It does not need to happen real-time (it does in the case of the way LYNC works) it just needs to be able to be stored and readily accessible if there is an inquiry. Think of it as an extension of the call recording archiving that started to be mandated on brokers phones in the 1990's

**Comment by jonbaer** [comment]
I am also wondering about this case and it's my understanding that the route would be to upgrade your MongoDB to EE (ie: https://www.mongodb.com/blog/post/making-hipaa-compliant-applications-mongodb) but the issue is the search ability part, where usually FTS is offloaded to either Elastic(search) or Solr in some way (not ideal for ease of use).  Exporting to SMARSH is that done daily?

**Comment by dupree972** [comment]
I don’t have the separation/HIPPA concerns, just journalling/archiving, however I can see where HIPPA compliance would help a lot of use cases.

**Comment by graywolf336** [comment]
Do you happen to have a link to the json format SMARSH expects?

**Comment by Sing-Li** [comment]
API with their "partners program"   -   http://www.smarsh.com/developers

Will need a sponsor if we take this on.

**Comment by cyberinvasion** [comment]
Supporting this, we have a use case that would need a public archive available without having to join the chat, having a JSON export option (Preferably with a schedule and export to S3 bucket if I was being greedy) would make me a very happy person!

**Comment by dupree972** [comment]
Does anyone have a solution for compliance logging? I started a bounty on this, this functionality I think would really help platform adoption as many businesses have this regulatory issue. It can be simple as long as it can be ingested into some kind of archive and easily searched. The info appears to all be in Mongo so all that is needed is to somehow get all of it out in a usable format real time and insure things are logged before they can be deleted.
