### ISSUE TITLE
Allow Reacting - Editing Read Only Public Room - Clears Settings, Doesn't Save.

### ISSUE THREAD

**Issue by BizClimb** [RocketChat/Rocket.Chat#20323]
Note: I'm putting multiple bugs in the same bug report because I feel like they are all related.

Bug 1: When editing a "read only" public channel, the Allow Reacting option does not show when toggling the Read Only option, you need to save it then reload the edit room form to see it (the same goes for when un-toggling private, it does not disappear).

Bug 2: If you attempt to turn on Allow Reacting in a read only public room and save, then re-edit the room, the option is still un-toggled, and it also clears out the "Hide System Messages" toggled options you had checked before.

### Steps to reproduce:

1. Create a public read only channel.
2. Click Edit Room.
3. Toggle Allow Reacting.
4. Toggle Hide System Messages and Check various Hide System Message options.
5. Click Save
6. Edit the room again, options are not set as desired.

### Expected behavior:

Allow Reacting should be hidden/shown based on Read Only option being toggled on or off.

Allow reacting should turn on when you clicked save if it was toggled on, and the checked items in Hide System Messages should be retained and not cleared out.

### Actual behavior:

Allow Reacting does not stay on and it also clears the Hide System Messages settings.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: Debian Buster (Linux)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.7

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: Windows 10

### Additional context

Not sure if relevant but my server has been continuously upgraded from much older versions, and not a fresh install.

### Relevant logs:

N/A

**Comment by Darshilp326** [comment]
Working!

**Comment by Darshilp326** [comment]
@BizClimb System messages toggle button is saved if you select any of mentioned options from select-box.

**Comment by benwick** [comment]
Same bug on
Server: 4.3.1
Client: 3.7.5
