### ISSUE TITLE
ctrl+p direct messages not open chat with this person

### ISSUE THREAD

**Issue by johniak** [RocketChat/Rocket.Chat#2033]
When I type name in CTRL+P box it found a person, but when I  press enter key nothing changes.

**Comment by argenisleon** [comment]
![image](https://cloud.githubusercontent.com/assets/37144/13097302/0eb063de-d4f2-11e5-9872-787ef01c4d08.png)

When I press enter to select the person I get a white page

**Comment by olafleur** [comment]
Was not able to reproduce. Which version of Rocket.Chat are you using?

**Comment by marceloschmidt** [comment]
I can confirm this feature works as expected on our Demo server. Please reopen if it is not working and confirm your version number.
