### ISSUE TITLE
[BUG] Max age for retention policy in room edit resets after realod

### ISSUE THREAD

**Issue by yash-rajpal** [RocketChat/Rocket.Chat#20348]
### Description:
In room edit settings, when we try to set max Age more than global default, it shows settings saved but after we reload instead of new value of days field, it shows default value.

### Steps to reproduce:

1. Go to any room
2. open edit room settings panel
3. change maximum age under override message retention policy settings.

### Expected behavior:
Correct value should be displayed always

### Actual behavior:
After reload default value is shown if new value is more than default value
![maxAge-retention-before](https://user-images.githubusercontent.com/58601732/105631830-71016200-5e76-11eb-8eae-31f5e0132a9b.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.11-develop
- Operating System: Ubuntu 20.10
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome version 87
- Operating System: Ubuntu 20.10

### Additional context
Working on it.

**Comment by sennewood** [comment]
In 3.17.1 this also happens when the value is lower then in the global policy.
