### ISSUE TITLE
Bad parsing of markdown formatted URLs

### ISSUE THREAD

**Issue by jf-guillou** [RocketChat/Rocket.Chat#2034]
`[Stream](https://www.twitch.tv/stream)` is parsed as `https://www.twitch.tv/stream)` by the server.
Thus, the url embed is incorrect :(

This is due to #1857, changes to the regex are too large

**Comment by jf-guillou** [comment]
Easier to understand with a screenshot :
![urlparsemarkdown](https://cloud.githubusercontent.com/assets/9655409/12579018/f32f63b8-c424-11e5-8d50-9525825a980c.png)

**Comment by rodrigok** [comment]
Fixed via #2036
