### ISSUE TITLE
[BUG] Cancel button fails to close suggestion box.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20367]
### Description:
The cancel button fails to close the autocomplete suggestion box.

### Steps to reproduce:

1. Select any room
2. Prune messages
3. Enter usernames.

### Expected behavior:
That suggestion box should be closed when the cancel icon is clicked.

### Actual behavior:
The suggestion box is still displayed.

https://user-images.githubusercontent.com/55157259/105666145-a0f44800-5efe-11eb-9de6-b744b1383aa3.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working!

**Comment by RonLek** [comment]
@Darshilp326 this is actually happens with every multiselect. It's an [issue](https://github.com/RocketChat/Rocket.Chat.Fuselage/issues/252) within Fuselage.

**Comment by Darshilp326** [comment]
@RonLek Yes exactly!

**Comment by dougfabris** [comment]
As @RonLek it's a Fuselage's component issue. We're working to fix it asap and already have an [issue](https://github.com/RocketChat/Rocket.Chat.Fuselage/issues/252)!
Thanks for helping, guys!
