### ISSUE TITLE
Descriptions are left unset for some roles

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Rocket.Chat#20362]
### Description:

The Descriptions are left unset
### Steps to reproduce:

1. Go to Administration > Permissions
2. You can observe on clicking few roles that they are not set by default.

### Expected behavior:

The Descriptions should be set.
### Actual behavior:
They aren't.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by im-adithya** [comment]
Working on it!

**Comment by ggazzo** [comment]
this is how we 'hide' roles currently. they are 'default' roles that we dont want to show actually (by default) thats why they have no description).
