### ISSUE TITLE
[BUG] Cannot edit custom emoji without uploading new image

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat#20371]
### Description:

The EditCustomEmoji administration page should allow editing of the custom emoji name and aliases without necessarily uploading a new file. Right now, the save button activates if you change the alias or the name but the button does not do anything unless you choose a new image.

### Steps to reproduce:

1. Edit Custom Emoji
2. Change alias
3. Click save [ Nothing happens ]

### Expected behavior:

The emoji will be updated to have the new alias.

### Actual behavior:

Nothing happens.

https://user-images.githubusercontent.com/38764067/105688782-03117500-5f20-11eb-9da1-b722e7c3d0af.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.10
- Deployment Method: develop
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 87.0.4280.88
- Operating System: Ubuntu 20.10

### Additional context

FIX PR ready.

**Comment by Darshilp326** [comment]
@aKn1ghtOut Hey,#20316 solves this issue already:)

**Comment by aKn1ghtOut** [comment]
Ohh, missed that somehow. Closing this. Thanks!
