### ISSUE TITLE
 While sending more than one emojis we need to click on emoji picker icon again .

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20378]
### Description:
When a user wants to send more than one emoji he/she needs to click emoji-picker for every single emoji. 

### Steps to reproduce:

1. Message box
2. Click emoji-picker.
3. 

### Expected behavior:
Users only need to click once.

### Actual behavior:
Users need to click more than once.

https://user-images.githubusercontent.com/55157259/105715393-8d1f0500-5f43-11eb-87da-62994dc3be4a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
PR is ready!

**Comment by hugocostadev** [comment]
Not an issue, it's suppose to behave like that
