### ISSUE TITLE
push notifications not received / send

### ISSUE THREAD

**Issue by prohde** [RocketChat/Rocket.Chat#2037]
On 0.11.0 I received push notifications on my Android phone but on 0.14.0 I do not.
Was there a change so I have to update my configurations (server / client side)?

**Comment by Sing-Li** [comment]
Please try 0.15.0

**Comment by prohde** [comment]
@Sing-Li Did not try it up to now because there is no list of the changes made in 0.15.0 here on GitHub.

**Comment by prohde** [comment]
I'm on 0.16.0 now and it works again.

Is `https://rocket.chat/` still the only working gateway?

**Comment by sampaiodiego** [comment]
yes, the only at the moment.
