### ISSUE TITLE
Failed to send test mail in the SMTP menu

### ISSUE THREAD

**Issue by LeonardOliveros** [RocketChat/Rocket.Chat#2038]
![captura de pantalla de 2016-01-26 08 37 09](https://cloud.githubusercontent.com/assets/6960313/12581258/ad91a874-c407-11e5-9cb4-ec5d372dd885.png)

Mail is sent and observing the console gives this error

**Comment by geekgonecrazy** [comment]
Many things related to SMTP have changed since 01/26  If you still have this issue with latest release please let us know
