### ISSUE TITLE
Dropdown issue and Improve User Experience while Creating Channels

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Rocket.Chat#20398]
### Steps to reproduce:

1. Go to Create in SideNav > Create Channel
2. Click on Invite Users

### Expected behavior:
The input fields generally are on top followed by controls of the channel.
And also the invite users dropdown must be completely visible.

### Actual behavior:
The reverse is present and also the dropdown is partially visible.

![Screenshot (59)](https://user-images.githubusercontent.com/64399555/105818523-0b7bb580-5fdd-11eb-8925-68bc814499cb.png)
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

This will also solve issue #19605

**Comment by im-adithya** [comment]
Working on it!

**Comment by ericlambelet** [comment]
Hello.

We have the same issue on our company's installation.
@im-adithya, do you have an idea when this can be merge into a production release?

Thanks
Eric

**Comment by im-adithya** [comment]
@ericlambelet, the fix is ready and will be merged in a few weeks or so.
Thanks!

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
