### ISSUE TITLE
list of all members for simple chat

### ISSUE THREAD

**Issue by mhndm** [RocketChat/Rocket.Chat#2040]
Hello
how the user find list of all members to click on the user name to start chat ?
I need something simple
the method to enter the general channel is difficult for some users

**Comment by asmartin** [comment]
+1

**Comment by graywolf336** [comment]
Mind providing some clarification? Not 100% sure I follow what you're wanting...

**Comment by asmartin** [comment]
Is there a way to see a list of all registered users, like a buddy list on a traditional desktop chat client? This global list of all users is a nice way to see who is online/offline, and also useful to find someone if you can't remember their username (e.g. by looking for their avatar)

**Comment by tuxBurner** [comment]
+1

**Comment by ericlakich** [comment]
+1

**Comment by Noxionx** [comment]
+1

**Comment by graywolf336** [comment]
There is now a link on the member list "Show All" which will list all of the users in the channel.

**Comment by graywolf336** [comment]
@ToeBee That is a different item than the issue is describing, at least in my opinion..

**Comment by ToeBee** [comment]
I guess we disagree on the parsing of the initial request. I see "how the user find list of all members to click on the user name to start chat" and see the desire for (as @asmartin said) a buddy list in Jabber that lists every user registered on the system. From that list you can click on a user to start a private chat. 

Also "the method to enter the general channel is difficult for some users" indicates to me that the request does **not** apply to a single channel. We discussed this very thing in our test instance. "Well, we could just have everyone join a 'default' channel so they appear in the list of users of that channel" but that won't really scale if we try to roll this out to a larger team.

I'm happy to open another issue with this request more explicitly spelled out I guess. I just read through this one and thought it was exactly what we were wanting.

**Comment by asmartin** [comment]
@ToeBee - you're correct - what I was requesting is the ability to see all users in a list, not just users who are in the current channel
