### ISSUE TITLE
user can see admin permissions page

### ISSUE THREAD

**Issue by 4li-ra** [RocketChat/Rocket.Chat#20400]
### Description:

A typical user can visit permissions page by call admin/permissions url directly although users do not have permission to view Permissions

### Steps to reproduce:

1. user login
2. user type https://XXX/admin/permissions url directly
3. user can see this page!

### Expected behavior:

Users restrict from seeing permission page in admin section when they do not have permission to view Permissions

### Actual behavior:

user can ses permissions page (can not edit)

### Server Setup Information:

I use rocket.chat demo cloud 

- Version of Rocket.Chat Server: 3.9.4
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: firefox and chromium
- Operating System:  fedora 33

**Comment by sushant52** [comment]
It is made to be that way so that users can see the permission of other users. It shows different page depending on if you are admin or not. Only admins can change the permissions while others can only see what permissions different roles have.

**Comment by inscrutable0** [comment]
@sushant52 it's the exact page view that admin see as you can see in this image and user can see all other roles permissions

![Screenshot from 2021-01-26 13-10-21](https://user-images.githubusercontent.com/5882577/105828132-08ca9180-5fd8-11eb-932d-81b75340ebeb.png)

**Comment by sushant52** [comment]
@inscrutable0 If you hover over it, it says "Modify permissions for various roles". If you check a box for member, it will allow him to change the permissions. 
This setting currently works as "who has access to change the permissions", not "who can access the permission screen", despite of its name. You can actually access this screen on open.rocket.chat server as well. I am sure this was meant to be this way, the title of the setting can be changed to a better one however. 
@gabriellsh @ggazzo Can you confirm/deny this setting's working?

**Comment by yash-rajpal** [comment]
If this was intended for everyone I think there would have been an easier way for normal users to access this page. 

Also whats the point of showing this page to normal users?

**Comment by sushant52** [comment]
@yash-rajpal  I guess to show what permissions different users have. In the code, instead of showing unauthorized access page, they show the same page but without access to make changes.

The unauthorized access page is included in all other settings so it is unlikely they just "missed" to include it in this one. Moreover, one can easily go to open.rocket.chat/admin/permissions which is the official working site.
I think they must have thought this out. Afterall, unwanted changed permissions can be a major vulnerability in the system.

**Comment by yash-rajpal** [comment]
@sushant52 Maybe you are right, but seems an un-intuitive way of showing something which is available for all.

**Comment by danel1** [comment]
@sampaiodiego should this really be public visible?

**Comment by yash-rajpal** [comment]
@danel1 PR #20403 fixes this if it shouldn't be publically visible.

**Comment by sushant52** [comment]
@danel1 PR #20420 as well I think. The logic seems better here and uncovers some labelling problem as well.

**Comment by gabriellsh** [comment]
access-permissions: allows regular permissions to be edited.
access-setting-permissions: allows for setting specific permissions to be edited.

This means there should be 2 checks ->
1. One for the whole page checking if the user has at least one of them
2. One for each tab.
