### ISSUE TITLE
Hide messages from stream

### ISSUE THREAD

**Issue by srocke** [RocketChat/Rocket.Chat#2041]
I need a way to hide incoming messages from the stream so I can do other things with the messages without any users seeing them (eg, open tabs, show notifications, etc...)

Perhaps an additional parameter like "hidden" for a MessageType?

**Comment by rodrigok** [comment]
Why not use the `Notification` system? https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/client/Notifications.coffee?ts=2

You car send notifications for a user, a room or for all users.

**Comment by srocke** [comment]
Good point. I will give this a shot. How could I add my own notification type from my own package?

**Comment by rodrigok** [comment]
@srocke are you trying to send notifications from server to client? To a room or to a single user?

As an example

```javascript
// CLIENT
var handler = function(value1, value2) {
  console.log(value1, value2);
};

// Add listener
RocketChat.Notifications.onRoom(room_id, 'your-notification-name', handler);

// You can remove the listener too
// RocketChat.Notifications.unRoom(room_id, 'your-notification-name', handler);
``` 

```javascript
// SERVER
RocketChat.Notifications.notifyRoom(room_id, 'your-notification-name', 'value1', 'value2');
```

I prefer to passa only 1 value as object like:
```javascript
RocketChat.Notifications.notifyRoom(room_id, 'your-notification-name', {
  value1: 'value1',
  value2: 'value2'
});
```

**Comment by srocke** [comment]
I want to send it to a single user or to a set of specific users

**Comment by rodrigok** [comment]
OK. You can send notifications to a single user, so you can do a loop and send to each user of your set.

**Comment by srocke** [comment]
I want to do it regardless of the room. I want it to find them wherever they are and notify them (this will actually be opening their FlexTab, so I don't want it to hit their stream)

**Comment by rodrigok** [comment]
Ok, so you can use the Notification system without problems.

**Comment by rodrigok** [comment]
Can we close this issue?

**Comment by srocke** [comment]
how can i notify a user regardless of what room they are in?

**Comment by rodrigok** [comment]
@srocke sure, you can send notifications to:
- A Single User
- A Single Room
- All users

**Comment by srocke** [comment]
How do i send a notification to a single user, regardless of what room they are in?

**Comment by rodrigok** [comment]
@srocke

```javascript
// CLIENT
var handler = function(value1, value2) {
  console.log(value1, value2);
};

// Add listener
RocketChat.Notifications.onUser('your-notification-name', handler);

// You can remove the listener too
// RocketChat.Notifications.unUser(handler);
``` 

```javascript
// SERVER
RocketChat.Notifications.notifyUser(user_id, 'your-notification-name', 'value1', 'value2');
```
