### ISSUE TITLE
Broken link in Home Page (documentation link)

### ISSUE THREAD

**Issue by HariAcidReign** [RocketChat/Rocket.Chat#20417]
### Description:

The link does not redirect the user to the documentation page, as the link for it is broken. 

### Steps to reproduce:

1. Go to home page
2. Click on documentation icon
3. 404 Page not found error

### Expected behavior:

The documentation page to show up

### Actual behavior:

https://user-images.githubusercontent.com/58134096/105859454-8ad7ac00-6012-11eb-8e04-a8914fcc9f23.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by HariAcidReign** [comment]
Working on it!

**Comment by HariAcidReign** [comment]
Please review :)

**Comment by im-adithya** [comment]
Hey, this was already done and was also approved by @gabriellsh!
Refer to #20409 and PR #20410

**Comment by HariAcidReign** [comment]
> Hey, this was already done and was also approved by @gabriellsh!
> 
> Refer to #20409 and PR #20410

Yes. I realise that. Thank you

**Comment by gabriellsh** [comment]
Different links @im-adithya.

**Comment by im-adithya** [comment]
Oopsie! 😅

**Comment by yash-rajpal** [comment]
@gabriellsh My pr linked #20351 already fixes this.

**Comment by gabriellsh** [comment]
Closing in favor of #20351

**Comment by gabriellsh** [comment]
I'll also ask you guys to try to deliver more quality PRs. Your help is great, but having to review 10 different PRs that fix a single translation or string each is a waste of time.
