### ISSUE TITLE
[IMPROVE] User Card

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Rocket.Chat#20413]
### Description:

The present user card looks dull and boring, so I thought of styling it a bit.

![Screenshot (62)](https://user-images.githubusercontent.com/64399555/105852333-565ff200-600a-11eb-9b1e-b56f8ce7d577.png)

![Screenshot (61)](https://user-images.githubusercontent.com/64399555/105852153-18fb6480-600a-11eb-8c51-1dc7a2e41a0a.png)

### Steps to reproduce:

NA

### Expected behavior:

NA

### Actual behavior:

NA

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Sorry, I forgot to change the color of the cross to white but I'll make the changes and create a PR if you guys allow me.

**Comment by im-adithya** [comment]
@gabriellsh @ggazzo @dougfabris What do think about this? 👀

**Comment by dougfabris** [comment]
@im-adithya Thanks for your suggestion! We cannot move forward with your PR because it doesn't fit with our design consistency. We have custom CSS for individual preferences.
