### ISSUE TITLE
Can't change owner,moderator and leader of private and prublic group

### ISSUE THREAD

**Issue by lbouquinUniv** [RocketChat/Rocket.Chat#20411]
### Description:

We can't change group owner, moderator or leader. I change it in interface admin but doesn't work in canal inteface

### Steps to reproduce:

1. create canal 
2. add multiple user with different role 
3.  try to change the owner or moderator
![image](https://user-images.githubusercontent.com/57000474/105848180-ea1bc900-5fde-11eb-90f1-ce29e05734a4.png)
![image](https://user-images.githubusercontent.com/57000474/105848312-146d8680-5fdf-11eb-856d-7af1d681be4c.png)

![image](https://user-images.githubusercontent.com/57000474/105848023-b5a80d00-5fde-11eb-9164-923a436a20a6.png)

### Expected behavior:
The moderator list must be change and user will be notify. 

### Actual behavior:

![image](https://user-images.githubusercontent.com/57000474/105848582-775f1d80-5fdf-11eb-9e37-9f763f1deb75.png)

user-id or username not provied.  

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0 
- Operating System:  linux 5.4.0-1032-azure 
- Doyment Method: docker ( rocket.chat 3.10.0 and I try with 3.9.4 also ) 
- Number of Running Instances:  4 
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.4.3 

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by yash-rajpal** [comment]
This was fixed in 3.10.3 :).

**Comment by gabriellsh** [comment]
This is no longer a bug on the latest version. I'll be closing this now. Thanks for your contribution!
