### ISSUE TITLE
jpegPhoto LDAP Integration

### ISSUE THREAD

**Issue by asmartin** [RocketChat/Rocket.Chat#2042]
Rocket.Chat with LDAP integration works great, however it would be really nice if you could automatically populate avatars from the `jpegPhoto` LDAP field. Is this possible?

**Comment by engelgabriel** [comment]
It should be possible.

**Comment by asmartin** [comment]
Fantastic! I'd be happy to help beta test this feature. I could see it being useful to allow other LDAP attributes to be displayed in a person's profile in RocketChat, such as `telephoneNumber` or `mobile` too
