### ISSUE TITLE
Read-only channels, mandatory channels, etc

### ISSUE THREAD

**Issue by asmartin** [RocketChat/Rocket.Chat#2043]
It would be useful to have some special types of channels for particular use cases:
-    transient channels - these would be used for temporary messages that don't need to be retained over the long term; you could configure a persistence period for them but after that period old messages in said channels would be purged (not logged)
-    read-only channels - e.g for a leader to send out important messages to everyone but not allow discussion
-    mandatory channels - a channel that all users are automatically subscribed to and that they are not allowed to unsubscribe from (e.g for site-wide announcements). It seems `#general` already does this?

Perhaps these could be options that can be toggled or adjusted on the channel settings page? I could see it being useful to be able to combine them too, e.g making a read-only, transient, mandatory stream for announcing site-wide maintenance. Thoughts on this proposal?

**Comment by RichardFoxworthy** [comment]
#825 covers the read-only channel concept. 
Mandatory/auto-subscribe is a very nice idea
Ability to combine these features also very nice

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap and so we are currently unable to consider implementation.
