### ISSUE TITLE
[BUG] Highlights don't work when quoted/starred/pinned message is clicked.

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Rocket.Chat#20436]
### Description:
The highlights don't work as they **do** for **mentions in a thread**

### Steps to reproduce:
1) Click on any quoted message
<or>
1) Go to Starred/Pinned messages and click on any message's Jump to message button
### Expected behavior:
It must take you to the message and highlight it (like it does for mentions)

### Actual behavior:
It just takes you to where the message is but doesn't highlight the message.

This issue is present in https://open.rocket.chat as well

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by im-adithya** [comment]
Working on it!

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
