### ISSUE TITLE
Option to join/start call as voice only

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2044]
1- Not sure what is the future enhancement for the UI for the voice and VIDEO/Screen Share.  People don't know how to find it or even operate it. - Also stop Button doesn't work to end chat on both ends.

2- Can we have the voice chat button added next to the audio recording? or even replace it or drop down? to select option.?Sometimes people just want to discuss voice vs typing. if its an issue we can dedicate a channel on the left. - we shouldn't forget the option to mute - in case someone wants to talk forever :).. or limit this to certain channels.. 

i know this was mentioned before, but lets consider use of Jitsi for the video share capability it has hangout features + Many thanks
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

 :smile:

**Comment by valessiobrito** [comment]
Lib JS SIP -  http://jssip.net/

**Comment by giray** [comment]
:+1:

**Comment by Sing-Li** [comment]
New solution testing this week.

On https://demo.rocket.chat

When you are in a Direct Message or Private Group. You will notice a new video button on the toolbar , just click it anytime to start a video conference with all those in the room

**Comment by compuguy** [comment]
@Sing-Li this new solution, I'm guessing we would have to run a jitsi-meet server as well (plus configure rocketchat to open a conference)?

**Comment by designgurudotorg** [comment]
Ref: https://github.com/RocketChat/Rocket.Chat/issues/6239 (I'm suggesting we look at an integration with TokBox)

**Comment by compuguy** [comment]
@designgurudotorg If TokBox requires connecting to a remote server or service, that is a no go for a lot of corporations. That and that that service is useless on a airgapped network as well.

**Comment by engelgabriel** [comment]
<img width="274" alt="Screenshot 2019-07-11 at 15 46 18" src="https://user-images.githubusercontent.com/1000217/61076630-0eab5280-a3f3-11e9-92f5-22360edbf7b8.png">

We should change "Video Chat" to "Video Call" and "Voice Call"

**Comment by geekgonecrazy** [comment]
For who ever works on this.  The jitsi query string to start the the call audio only is: https://meet.jit.si/{ID}#config.startAudioOnly=false

config.startWithAudioMuted and config.startWithVideoMuted for audio and video respectively when joining

**Comment by Tom-Development** [comment]
Do we have anymore updates on this functionality?

**Comment by danger89** [comment]
So Jitsi can already support audio calls only? .. why not implement a second button with the additional `startAudioOnly=true` parameter added to the Jitsi URL?

**Comment by aminvakil** [comment]
My Jitsi server is using jwt authentication method and it's been set on rocketchat which is working well.

> For who ever works on this. The jitsi query string to start the the call audio only is: [https://meet.jit.si/{ID}#config.startAudioOnly=false](https://meet.jit.si/%7BID%7D#config.startAudioOnly=false)
> 
> config.startWithAudioMuted and config.startWithVideoMuted for audio and video respectively when joining

But when I add ```/{ID}#config.startAudioOnly=false``` to my domain, it starts asking username password.

I suppose it doesn't work with jwt(?).

Any ideas how to work it out with jwt authentication?

**Comment by fthiery** [comment]
My goal is to startAudioOnly all calls on rocketchat globally (by default). I i tried to set this up into the rocketchat jitsi settings (without any jwt) and it cannot find any way to have the #config.startAudioOnly=false as trailing argument, rocketchat always appends the random id...

![Capture d’écran de 2020-06-18 16-31-59](https://user-images.githubusercontent.com/87642/85033661-7f212e80-b181-11ea-87a9-ced1e7ca4b40.png)

![Capture d’écran de 2020-06-18 16-32-32](https://user-images.githubusercontent.com/87642/85033677-821c1f00-b181-11ea-924d-deff33783756.png)

Is that even doable right now ?

**Comment by fthiery** [comment]
Tried all combinations but i think it's not possible in the current state. I think that a "Custom suffix" field would do the trick and would allow for passing custom jitsi options simply.

**Comment by fthiery** [comment]
Indeed:
```
room: rcSettings.get('Jitsi_URL_Room_Prefix') + rcSettings.get('uniqueID') + rid,
```

https://github.com/RocketChat/Rocket.Chat/blob/6ed0e44722b5c5cdbf4a3dbc7e785423c082f7e6/app/livechat/server/api/v1/videoCall.js#L44

**Comment by fthiery** [comment]
FYI the latest release -3.4) should make this possible now. Just set `#config.startAudioOnly=false` to the newly added Jitsi room suffix.

I think this ticket can be closed

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
