### ISSUE TITLE
[BUG] Messages sent/received after opening Export aren't being selected 

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Rocket.Chat#20451]
### Description:

The messages sent/received after one opens Export Messages tab are not being selected..
### Steps to reproduce:

See video

### Expected behavior:

All messages must be selected.
### Actual behavior:
Recent ones aren't being selected

https://user-images.githubusercontent.com/64399555/106039312-0020ab00-60ff-11eb-9f86-526f37172738.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
