### ISSUE TITLE
IDN support

### ISSUE THREAD

**Issue by mitjajez** [RocketChat/Rocket.Chat#2045]
It would be nice if Unicode characters become recognized in URLs and email addresses.
I find that this could be done with [punycode.toUnicode](https://github.com/bestiejs/punycode.js/#punycodetounicodeinput) and punycode.toASCII

If i paste link to chat https://mitja.jež.si/2016/01/error-unexpected-mongo-exit-code-1-restarting/ it is "catched" as https://mitja.je domain.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
