### ISSUE TITLE
Ability to add more fields to User Profile Info

### ISSUE THREAD

**Issue by jcardila** [RocketChat/Rocket.Chat#2046]
Additional fields for user profiles that allows information such as Role, Phone, Extension. It would be great that an admin could be able to create custom fields, but if that is not feasible, having Role, Phone, and Extension fields would do the job for completing the profile.

**Comment by cbrummitt** [comment]
It would also be useful to have these "About me"/"Role" fields be searchable from a system-wide search feature that searches among all chats and user profiles, so that I could search for expertise within my organization using the search feature.

**Comment by acaronmd** [comment]
I would also like this feature, synced from ldap. Essentially, the additional fields could be added to 'User Data Field Map' under Admin -> LDAP. Any hints on where to start?

**Comment by engelgabriel** [comment]
@jcardila @acaronmd @cbrummitt lets use the issue https://github.com/RocketChat/Rocket.Chat/issues/2304 to track this.

**Comment by engelgabriel** [comment]
@cbrummitt, @VirtuaCreative, @estadtherr, @meilinger, @joetm, @Schoaf, @svenschumacher, @gongled, @jcardila @acaronmd lets use the issue #2304 to track this.

**Comment by FaizanZahid** [comment]
atleast a bio or about me section must exist for each user profile page, this will let users write and introduce each other.
