### ISSUE TITLE
Custom status in the status section gets overridden by default values.

### ISSUE THREAD

**Issue by Ashray123** [RocketChat/Rocket.Chat#20468]
### Description:

After setting up a **Custom Status** in the status bar, the value gets changed by the default values present i.e online, away , busy, invisible. According to me , Custom status should be something that remains active with the profile even if the user is not available (away, busy, invisible).

### Steps to reproduce:

1. Hover over to your profile picture,
2. Click on it.
3. Now, you will see a dropdown menu, now click on "Custom Status" from it at the end.
4. Set your custom status.

### Expected behavior:

The custom status that is once set should not be changed until the user doesn't change it. Only the status Symbols should be updated not the Status in the status bar.

### Actual behavior:

https://user-images.githubusercontent.com/40429213/106096956-7acbe380-615c-11eb-82f9-6750ef945f36.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Mac os
- Deployment Method: Local 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64 
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Mac os

**Comment by Ashray123** [comment]
I am working on it .

**Comment by yash-rajpal** [comment]
I think this is the it was intended to be used.

If you want to keep your custom status and also want to change the status online or away or busy, then instead of directly selecting the status you want, you can click on custom status and just changes the status bullet.

This will keep your custom status text intact and will only change status bullet.

**Comment by Ashray123** [comment]
@yash-rajpal  I agree with you but that will only be a one-time solution, now what if I change the status to default values again i.e online, away, busy or invisible ? . You will see that custom set status is overridden again. Therefore according to me, Custom Status should be something that remains constant.

**Comment by wreiske** [comment]
Ouch. This new behavior has bit be a few times! My original implementation would respect whatever status you previously had there, like "Working from home today" or "PTO March 5th - 10th" or "Free cookies in my office, come and get some!". You might want to change your status to "busy" or "away" while keeping your status message the same. The only time your status message should ever clear is if you open the custom status and delete it, **IMO**!

**Comment by ggazzo** [comment]
I think this was already fixed, please let me know if not ;)
