### ISSUE TITLE
Single Rocket App with multiple databases based on subdomain

### ISSUE THREAD

**Issue by Joey-Nguyen** [RocketChat/Rocket.Chat#20466]
### Description:
Hi everyone,

I want to deploy Rocket Chat like the architecture image below. How would you set up one app which connects to a database depending on the subdomain?
![Architecture1](https://user-images.githubusercontent.com/64880211/106088699-00e62b00-6159-11eb-9664-4578732b1566.PNG)
Can someone help me to solve this issue? Thanks

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by johncrisp** [comment]
Hi, 

You haven't completed any of the information as asked so we can't help.

This also appears to be a support request and not a bug.

Please ask for assistance in:

https://open.rocket.chat/channel/support
https//forums.rocket.chat
