### ISSUE TITLE
How to make user search to search only full names?

### ISSUE THREAD

**Issue by VerusK** [RocketChat/Rocket.Chat#2047]
I'm talking about this search - https://www.dropbox.com/s/ti5yp7sqlygqnkm/Screenshot%202016-01-27%2010.13.52.png?dl=0

I would like to show users in hint only when full name matches rather than "starts with". Can you show me where can I find this code. I'm a noobie in programming but really want this functionality. Thank you.

**Comment by VerusK** [comment]
Anyone? Please? :)

**Comment by mikonoid** [comment]
I am interesting this feature too. How to do this?

**Comment by marceloschmidt** [comment]
That is not possible. For servers with 100+ users, it becomes impossible to know the exact username of all users you want to add. Type hinting is necessary.
