### ISSUE TITLE
Users must use Two Factor Authentication - doesn`t work for new users (white screen after login)

### ISSUE THREAD

**Issue by EvgenGematogen** [RocketChat/Rocket.Chat#20475]
### Description:

When you enable "Users must use Two Factor Authentication" in Administration - Permissions - "user" role, new users cannot login to server, only white screen is showing.

### Steps to reproduce:

1. Go to Administration - Permissions - "user" role and turn on "Users must use Two Factor Authentication" option
2. Register new account and activate it
3. Log in with new account via browser 

### Expected behavior:

I expect to see some kind of account settings form with the requirement to enable two-factor authentication.

### Actual behavior:

White screen and error in browser console: Cannot find module '../../../client/account/security/AccountSecurityPage'
![Clipboard - 28 января 2021 г , 13_29](https://user-images.githubusercontent.com/34194469/106129226-1b2c0300-6171-11eb-9d29-ffbaca388d63.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: MS Edge 88
- Operating System: Windows 10 Pro 1909

**Comment by PlusaN** [comment]
I am observing the same problem on server version 3.10.4

**Comment by PlusaN** [comment]
I don't see this issue anymore after upgrading to new server version 3.11.0. Tnx :)

**Comment by EvgenGematogen** [comment]
3.11.1 - everything is fine, thank you!
