### ISSUE TITLE
[BUG]While mentioning channel,user subscribed rooms are shown twice.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20483]
### Description:
While mentioning the channel in the message, user subscribed rooms are shown twice.

### Steps to reproduce:

1. Select any channel
2. Message box
3.  Type #

### Expected behavior:
All channels should be shown only once.

### Actual behavior:
User subscribed channels are shown twice.

https://user-images.githubusercontent.com/55157259/106182396-c0bc9200-61c4-11eb-8d32-5353c6de4295.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working!

**Comment by C1ean** [comment]
Reproduced on 4.11.0

**Comment by Darshilp326** [comment]
@C1ean Hello, #20484 solves this issue:)
