### ISSUE TITLE
Double click a messege to reply in thread

### ISSUE THREAD

**Issue by sk044** [RocketChat/Rocket.Chat#20486]
### Description:

This feature can be useful for users.

### Steps to reproduce:

1. Go to a channel .
2.  Click on a thread to reply

### Expected behavior:

Double clicking a message triggers reply in thread.

### Actual behavior:

To reply a message we have to go to the reply in thread icon or three dot menu and then the same.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version:  12.18.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

**Comment by dougfabris** [comment]
@sk044 I'm closing the issue because there is no bug or problem here. This kind of change needs to be verified on our design team's process first, where they will check if it fits our user's needs. I'll share your thoughts with them, thanks for contributing!

**Comment by ivans-netto** [comment]
Hey @sk044 Thanks for your feedback, we'll be continuing the messaging redesign and implementation soon in the future. A quick access to threaded messages is a good idea.

Again, thanks for reaching out and sharing your suggestion.
