### ISSUE TITLE
Docker registry?

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#205]
Hi!

FIrst of all, great job guys!

Then, a quick question, do you plan to publish your docker file to the registry as an automated build?
I did publish one in the mean time: https://registry.hub.docker.com/u/indiehosters/rocket.chat/

It would be great if you could publish it "officaily".

If you need, I run it with this folder: https://github.com/indiehosters/Rocket.Chat

Cheers!

**Comment by engelgabriel** [comment]
I'd be glad to publish it officaily.

@Sing-Li can you help?

**Comment by Sing-Li** [comment]
@pierreozoux @engelgabriel   Sure.  Actually, I've been working on several Docker images for Rocket.Chat deployment to popular cloud services such as AWS, Bluemix, and Google Compute.   
We can definitely merge Pierre's work in.  

@engelgabriel - please create a DockerImages repos.

@pierreozoux , is it okay with you if your work is merged into an MIT licensed project (ala Rocket.Chat)?

**Comment by pierreozoux** [comment]
Totally fine :) I still don't have strong opinions about licensing.

**Comment by Sing-Li** [comment]
Cool.   @pierreozoux  How do you like Docker Compose beta so far?  

I've been trying to convince them to include support for   YML + [image-1, image-2, ... image-n]  on their new hub 'product'  -   docker/hub-beta-feedback#57    :)

**Comment by pierreozoux** [comment]
I find it cool :)

I don't who will win among:
 - procfile
 - unit/fleet file
 - panamax
 - app container pod

I think docker-comnpose is simple and nice to use but fall short on some issue (how to describe multiprocess container, how to apply 'layers' at execution time) and app container pod looks like to solve it.

Anyway, it is a really exciting time!

**Comment by engelgabriel** [comment]
Created https://registry.hub.docker.com/repos/rocketchat/

What should I do next?

**Comment by Sing-Li** [comment]
Thanks! 

We also need a github repos for our reference "Dockerfiles".

Perhaps:

https://github.com/RocketChat/DockerImages

Then, under there, we will have directories like:

/GCP
/Bluemix
/AWS
/Heroku
/GenericLinux
/CoreOS

... and so on ...  @pierreozoux  -  pls let me know if this organization of directory makes sense to you

... and each directory will have a Dockerfile

Then, we can link each of those Dockerfile to an "automated build" , where the docker hub will pull from github repos and build our image for us (everytime we change any dockerfile).

**Comment by engelgabriel** [comment]
Done

https://github.com/RocketChat/DockerFiles

**Comment by Sing-Li** [comment]
Cool.  I'll add the first set of 'rough-in' top level directories now.   I think we can take it from here.  Thanks, @engelgabriel .

**Comment by pierreozoux** [comment]
I just have experience with CoreOS, and wouldn't know what to say for the rest.

I hope there is a way to have just one Dockerfile. But I just know the names from other systems.

I can provide you a unit file for that, at least the one I'm using. I don't have fleetctl file yet.
I think this is amazing what you are trying to do! Really lookign forward to the outcome! No/not a lot of app developper take the problem of hosting these apps seriously. So thanks to tackle this!

**Comment by Sing-Li** [comment]
@pierreozoux   Thanks!    

Can you please submit a PR for your current work into the GenericLinux directory? 

I think we can evolve it. 

One thing that I'll do though, as much as I respect what Arunoda and the MeteorHack gang is doing, is to replace the all-purpose base with a specialized 'slim' image that I've been tuning (https://registry.hub.docker.com/u/singli/meteor/).

CoreOS!  Very very cool.  etcd and rkt are wonders of modern software engineering  :)

**Comment by pierreozoux** [comment]
@engelgabriel can you create an automated build from https://registry.hub.docker.com/repos/rocketchat/rocketchat pointing to this repo. (as there is already a dockerfile, this should work just fine!)

**Comment by Sing-Li** [comment]
systemd support  (thanks @pierreozoux )   is vital in getting Rocket.Chat into Linux distros.

I think we may want to rename the "Dockerfiles" registry to "Deployments and Linux packages".

**Comment by pierreozoux** [comment]
Yes, it would make more sense! And maybe we'll see a need for other dockerfiles in the future, we'll see at this moment!

**Comment by engelgabriel** [comment]
https://registry.hub.docker.com/u/rocketchat/rocket.chat/ created... is that ok? With the . on the name?

@pierreozoux If it is not, please, reopen the issue and let me know.

**Comment by pierreozoux** [comment]
Looks amazing!
