### ISSUE TITLE
[BUG] Starred/Pinned messages menu doesn't disappear on clicking outside/on options

### ISSUE THREAD

**Issue by im-adithya** [RocketChat/Rocket.Chat#20503]
### Description:

The kebab options while choosing starred or pinned messages don't disappear on 'off click'
(This issue can be reproduced in open.rocket.chat as well)

### Steps to reproduce:

See video

### Expected behavior:

The options should disappear.

### Actual behavior:

They don't.

https://user-images.githubusercontent.com/64399555/106279163-00858700-6262-11eb-9604-6712a0baac3b.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
