### ISSUE TITLE
Integration with Keycloak: Users not matching by email

### ISSUE THREAD

**Issue by paulobernardoaf** [RocketChat/Rocket.Chat#20505]
### Description:

When trying to login with Keycloak service using the `/login` API endpoint, if a user that already exists in both databases (Keycloack and Rocket.Chat) tries to log in, the response is: `{"status":"error","error":403,"message":"Email already exists."}`
The `merge users` option is enabled on the Keycloak configuration page.

### Steps to reproduce:

1. Have a user with different accounts usernames, but the same email, in each database.
2. Try to get the Rocket.Chat authentication token with the `/login` API, using the Keycloak service as login method

### Expected behavior:

Successful login 

### Actual behavior:

- /login API returns:
```
{"status":"error","error":403,"message":"Email already exists."}
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.21

### Client Setup Information

- Desktop App or Browser Version: Chrome, Postman
- Operating System: Linux

### Additional context

After an initial digging on the source code, I've found that the default way to check if a user already exists at Rocket.Chat is by his username [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/custom-oauth/server/custom_oauth_server.js#L337). If no match is found, a new account will be made, causing the issue `Email already exists`.
I believe this is causing the issue, and if users were searched by email besides the username, they would be matched and the login would be successful.

**Comment by Exordian** [comment]
You can change the user identiifer (which also works for merging users) within the SAML settings (if you're using SAML, since keycloak would also support OIDC)
