### ISSUE TITLE
Cannot upload room icon with 3.11.0-rc.2 / 3.11.0-rc.3

### ISSUE THREAD

**Issue by jacobsenj** [RocketChat/Rocket.Chat#20502]
### Description:

Uploading a room icon is not working in RC 3.11.0-rc.2/3

### Steps to reproduce:

1. Create Room
2. Edit room
3. Select a png to upload
4. Try to save the edited room

### Expected behavior:

Room icon has been saved and applied

### Actual behavior:

Error after saving the edited room:

![image](https://user-images.githubusercontent.com/399303/106259536-afed3a00-621f-11eb-962a-a23e1aaf38be.png)

Console output:
![Bildschirmfoto 2021-01-29 um 10 55 45](https://user-images.githubusercontent.com/399303/106260363-a1535280-6220-11eb-8d66-e0fe165cc0b3.png)

Response of POST:
```
{"success":false,"error":"TypeError: Cannot read property 'rid' of undefined [ufs: cannot upload file]","errorType":"ufs: cannot upload file"}
```

Uploading the exactly same file in a room chat works.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-rc.3
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: Manual installation (https://docs.rocket.chat/installation/manual-installation/ubuntu)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.16 / mmapv1 (oplog Aktiviert)

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 88.0.4324.96 (Offizieller Build) (x86_64)
- Operating System: macOS Big Sur 11.1 (20C69)

### Relevant logs:

Console error message see above; No server log entry was written.

**Comment by yash-rajpal** [comment]
PR #20433 already solves this error :)

**Comment by jacobsenj** [comment]
@yash-rajpal nice, thank's for the info
