### ISSUE TITLE
 Regression: Real name not shown anymore in reactions (Until page reloaded)

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#20501]
### Description:

In RocketChat 3.9 reactions look like this:

![Capture d’écran du 2021-01-29 10-28-18](https://user-images.githubusercontent.com/57196916/106257668-263c6d00-621d-11eb-868a-4e02fb17dea0.png)

In RocketChat 3.10 reactions look like this:

![Capture d’écran du 2021-01-29 10-28-31](https://user-images.githubusercontent.com/57196916/106257707-32282f00-621d-11eb-85b6-3d84cd84225e.png)

In our University, student usernames look like **e193849k** so not really cool for teachers :-)

### Steps to reproduce:

1. Send a reaction
2. 
### Expected behavior:

Real name in tooltip

### Actual behavior:

Username in tooltip

Reloading the pages fixes the issue so looks like an AJAX issue.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System:  Linux
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Linux

**Comment by yash-rajpal** [comment]
You can select between the username or real name in admin panel.
Just go to admin panel -> Layout -> User Interface and turn on the Use real name setting.

After that real names would be used for reactions and many other places.

**Comment by bellegarde-c** [comment]
Already on here. Does not work.

**Comment by Gummikavalier** [comment]
We've had this issue for a longer period of time along with the one with the names in threads. Latter seems to be fixed now in 3.11.0.

**Comment by bellegarde-c** [comment]
Not fixed here with 3.11.0.

**Comment by bellegarde-c** [comment]
It only shows the real name after reloading the page.

**Comment by Gummikavalier** [comment]
Yup. On ours even refresh does not help to resolve names in reactions.

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/20841

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
