### ISSUE TITLE
OS X Client crashes when downloading the same file twice

### ISSUE THREAD

**Issue by Steibock** [RocketChat/Rocket.Chat#2050]
Hi

A file uploaded by a user can not be downloaded twice in a row using the native OS X client. The first attempt succeeds, when downloading the file a second time, the client crashes.

**Comment by matthias-brun** [comment]
This is an issue with the OS X client, not Rocket.Chat itself. I have posted an issue for this concerning links to local files ( [here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/62) ) but I wasn't aware that it happens with all links.

**Comment by marceloschmidt** [comment]
Duplicate on Rocket.Chat.Electron project.
