### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2051]
Not sure if this a bug or not, i have a username (admin) and i have setup under registration, to request email verification (set to True).  
i log out and tried to log back in, it asked me to put my email address, send submit and its successful.. 

guess what i dont have SMTP setup, so its sending the email to no where - successfully 
second why am verifying an existing user, specially if its an ADMIN?

i had to go to DB to disable email verification.

**Comment by doomdance** [comment]
I was in the same boat at one time. See issues #924 and #766.

**Comment by marceloschmidt** [comment]
Closing, duplicate.
