### ISSUE TITLE
Meteor Crash when upgrading from 2.4.2 -> 3.10.5

### ISSUE THREAD

**Issue by apaarfus** [RocketChat/Rocket.Chat#20526]
### Description:

After a year or so of being stuck with v2.4.2, it was _finally_ approved to update our RC instance to the latest stable release; in this case, 3.10.5.  Following the typical update steps for a manual install went smoothly....however, _right_ after the server finished the initialization process, it crashed immediately after.  Stacktrace provided below, in the 'Relevant Logs' section.

Now, I realize 2.4.2 -> 3.10.5 is a _huge_ jump, and a lot has changed over the past year...so, _maybe_ I need to upgrade a few versions at a time, and eventually get back up to date; but I'm not sure if that's the solution here.

### Steps to reproduce:

1. Stop & Backup server/data
2. Perform a manual update/install to the latest version
3. Start server
4. Check `journalctrl -xe` to await initialization to complete
5. After initialization, server crashes

### Expected behavior:

This should go without saying, but I'd expect it _not_ to crash after upgrading.

### Actual behavior:

As mentioned in the description, server is crashing after finishing the initialization process.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.2
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10 Pro x64

### Additional context

I'll be setting up a local copy of our server _somewhere_ this coming week, to see if I can reproduce the issue on another VM.  Additionally, I'll see if I can do some incremental updates to eventually land on the latest release version.

### Relevant logs:

Stacktrace from `journalctl -xe`

![image](https://user-images.githubusercontent.com/38731016/106376758-2d22c700-6366-11eb-8bf9-a7e786387167.png)

**Comment by Sing-Li** [comment]
@apaarfus   Meteor is required, and should **ONLY BE USED** by developers for RC development purposes.

Meteor should not be used in any production deployment.  Please check our documentation for the numerous production deployment methods that are available.    https://docs.rocket.chat/installation

**Comment by apaarfus** [comment]
> 
> 
> @apaarfus Meteor is required, and should **ONLY BE USED** by developers for RC development purposes.
> 
> Meteor should not be used in any production deployment. Please check our documentation for the numerous production deployment methods that are available. https://docs.rocket.chat/installation

Please note that we are not using Meteor outright -- whatever is included in the [release bundles](https://releases.rocket.chat/latest/download) is what we're using.  Additionally, as you've noted, we have followed (and continue to) the [manual installation method for CentOS](https://docs.rocket.chat/installation/manual-installation/centos).  When updating, we _effectively_ follow this tutorial for replacing `/opt/Rocket.Chat` with the latest build.

Still, I'll see if I can track down what the actual issue is -- it may not be anything to do with Meteor at all...frankly, this is an _**assumption**_, based on the errors we were receiving...but again, I'm not super clear on the startup procedures of the server, or otherwise...

**Comment by apaarfus** [comment]
Just wanted to mention that I was able to get a local instance of RC 3.11.1 running in a test environment.  When restoring the database from file, I was _once again_ met with the same stack trace as I was back in January:

![image](https://user-images.githubusercontent.com/38731016/109344163-5f77f500-783c-11eb-8ec5-8a601bff5a6d.png)

Looking at this again with a more fresh set of eyes...it looks like this has _something_ to do with an "invalid user".

It should also be noted that on 3.11.1, we're not getting a crash after restoring the DB -- so, hoping that we can get by for the time being...unsure _which_ user's messages is generating that error, though.
