### ISSUE TITLE
OAuth - put the call back URL in the UI

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#2052]
It would be a lot easier to configure!

**Comment by IQ2022** [comment]
is this for the SSO? i can't get the SSO work for any of the social media sites? i must be doing something wrong.

**Comment by pierreozoux** [comment]
OAuth login is for Facebook login or twitter login for instance. (Is it
what you call SSO?)
In the callback URL, you should put:
`https://yoursiteurl/_oauth/twitter` for twitter OAuth, but replace
twitter accordingly.

On 27-01-2016 21:41, Ahmad Abbas wrote:
> is this for the SSO? i can't get the SSO work for any of the social media sites? i must be doing something wrong.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/RocketChat/Rocket.Chat/issues/2052#issuecomment-175870286
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by fduraibi** [comment]
:+1:  It should be shown in a copy-able field each service

I found the URL through the error message from google :)

**Comment by jspeigner** [comment]
How to set this up should be in the Documentation

**Comment by IQ2022** [comment]
i can't get it figured it out? any examples on how to setup this SSO for all available options (Wordpress, Twitter, Facebook, Google, etc? ) nothing works

also if URL is an ip address would that works?

**Comment by engelgabriel** [comment]
@marceloschmidt, this one should be easy :)

**Comment by IQ2022** [comment]
@engelgabriel if you say so :+1: but bu but you know :)
