### ISSUE TITLE
Incorrect Uri , oAth open id keycloack oAuth integration 

### ISSUE THREAD

**Issue by JonCSgr** [RocketChat/Rocket.Chat#20522]
### Description:

Can't set up oAuth with openID using keycloack.
### Steps to reproduce:

1.   homepage
2.  Log in using keycloack
3.   the keycloack page sign in pop up comes and you fill the username/password 

### Expected behavior:

User to be logged in rocketchat.
### Actual behavior:

I am getting a undefinied on the top right corner.
### Server Setup Information:

- Version of Rocket.Chat Server:  1
- Operating System:  ubuntu 16.04 on localhost
- Deployment Method:  snaps
- Number of Running Instances: 1
- DB Replicaset Oplog:  snaps
- NodeJS Version: snaps
- MongoDB Version:snaps

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

 The logs say that the  redirect uri is not valid.
I tried http:localhost:3000/* (keycloack complains on this uri and can't even put username/password)
           http://localhost:3000/* getting error Incorrect Uri on the logs
           http://locahost:3000/_oauth/keyclock  also getting error incorrect uri on the logs

The error log on keycloack says error= invalid code but it's a WARN
I have every setting set up correctly what is the issue ,

Also i am testing keycloack with nextcloud and it works just fine !

**Comment by JonCSgr** [comment]
i found this one https://github.com/RocketChat/Rocket.Chat/issues/14134

I used snaps not docker though

**Comment by JonCSgr** [comment]
The error log on keycloack says   error= invalid code but it's a WARN 
I have every setting set up correctly what is the issue ,

**Comment by JonCSgr** [comment]
I googled everything and i can't seem to find a solution to this problem . The configuration is 100% correct .

It's driving me crazy.

**Comment by JonCSgr** [comment]
I am still facing this issue , it's driving me crazy every setting is correct.

I set this up on a real env as well to test if it's cause of localhost and i face the same issue .

HELP!

**Comment by JonCSgr** [comment]
![image](https://user-images.githubusercontent.com/61245954/106497639-fb754180-64c6-11eb-97a9-b6a98f456fce.png)
![image](https://user-images.githubusercontent.com/61245954/106497713-12b42f00-64c7-11eb-9a91-ede9e62e7c8f.png)
![image](https://user-images.githubusercontent.com/61245954/106497788-29f31c80-64c7-11eb-8159-c095c1cfecda.png)
![image](https://user-images.githubusercontent.com/61245954/106497799-2d86a380-64c7-11eb-904a-19272f425f46.png)

**Comment by sschueller** [comment]
I believe you need to enable implicit flow in keycloak.

**Comment by JonCSgr** [comment]
> I believe you need to enable implicit flow in keycloak.
> 
> For redirect URL I have a * at the end of the rockchat server URL, no path just /

Tried with * as well , tried with implicit flow as well . still doesn't work .

**Comment by JonCSgr** [comment]
I am def doing something wrong because it doesnt work on my localhost neither on my server and i am getting the same error.

**Comment by sschueller** [comment]
I also have "Direct Access Grants Enabled" Enabled.

In rocketchat I have username field as ```preferred_username``` but that might be my specific setup. Email field is ```email``` and name field is ```name```. Everything else looks similar to yours. Is your realm called "test"?

**Comment by enzyro** [comment]
Hi,
I just did the exact same SSO setup 1 month ago on a VM and it worked, tried again today with the latest release of RocketChat and I got the same error as OP. Not sure where it's comming from, here is the error I'm getting in the new install :
```
2021-02-02 01:23:36,957 WARN  [org.keycloak.events] (default task-77) type=CODE_TO_TOKEN_ERROR, realmId=Rocketchat, clientId=rocket-chat-client, userId=XXX, ipAddress=127.0.0.1, error=invalid_code, grant_type=authorization_code, code_id=XXX, client_auth_method=client-secret
```

**Comment by sschueller** [comment]
Hi, sorry, I noticed I am still on ```3.8.0```.

**Comment by JonCSgr** [comment]
Solved: I bet your General → Site URL is http://localhost (or some similar value) and not http://55.43.234.23:3000.
https://forums.rocket.chat/t/help-setting-up-oauth-with-keycloack/10202/19
