### ISSUE TITLE
Markdown rendering of messages from GitHub integration broken

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#20539]
### Description:

We are using the first github integration example in the documents of RC for rendering messages incoming from GitHub.
Docs: https://docs.rocket.chat/guides/administrator-guides/integrations/github

Rendering of messages works in RC 3.9.7 but not in RC 3.11.0.

### Steps to reproduce:

1. Create an incoming webhook for GitHub project in RC
2. Add the webhook at GitHub in the project's webhooks.
3. Create a new issue in GitHub for the project

### Expected behavior:

Markdown rendering of message works (in 3.9.7):
![Screenshot from 2021-02-01 12-23-15](https://user-images.githubusercontent.com/6958942/106446761-4ff9cc00-6489-11eb-8381-16caed8eab04.png)
 * Ignore the name Octocat and the avatar, the screenshot is from a different system than actual behavior screenshot below.

### Actual behavior:

Markdown rendering message is broken in RC 3.11.0.
![Screenshot from 2021-02-01 12-19-54](https://user-images.githubusercontent.com/6958942/106446822-64d65f80-6489-11eb-8df4-03baef777221.png)

Rendering at least the full message content as is would be minimum functionality to be usable, but there is not enough space for that.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Any browser

**Comment by yash-rajpal** [comment]
Can you check this on open workspace of Rocket chat? This doesn't seems to be an issue there. Check the general channel, it has github integration.

**Comment by Gummikavalier** [comment]
Yes, I checked general there. I'm not sure but I assume that the devs are using different integration code of their own there, and not the one listed in the docs. So it may transmit the data differently.

But yes, maybe the issue is not markdown itself but the example script in the docs would require something to separate it as to be rendered with markdown.

**Comment by Gummikavalier** [comment]
Ah, the second example still works. However it lacks some functionality (actually both do). But at least the issue is not markdown itself.

**Comment by Gummikavalier** [comment]
@yash-rajpal Thanks. I'll close this one. Have to start developing changes based on the latter example. :)

**Comment by yash-rajpal** [comment]
If you successfully develop the first example with correct markdown, can you please share with us?

**Comment by Gummikavalier** [comment]
Sorry, I switched to the second example. It also seems to have nicer output generally.
