### ISSUE TITLE
Rocket.Chat doesn't redirect to log-in screen when logged out / session ends

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#20547]
### Description:

Rocket.Chat does not redirect you to the login screen when your session ends / when you are logged out. This leaves your client in a weird state where you can browse around, send messages (grayed out), and it looks like the server is broken. You have to restart Rocket.Chat or hit View / Reload and it will then redirect you to login again.

1. Why are users getting logged out when sessions are set to never expire?
2. Why is it not redirecting to the login screen when you're logged out?

### Steps to reproduce:

Method 1:
1. Login
2. Wait
3. ????
4. Nothing works

Method 2:
1. Login
2. Clear E2E keys in profile
3. Nothing works

### Expected behavior:

The moment a session ends or a user is deactivated, logged out by server, etc., you should be directed to the login screen.

### Actual behavior:

(Gif attached in #mie-rocket channel on open)

Desktop client looks like it's having connection issues to the server but still lets you navigate around, send messages (grayed out), etc.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by wreiske** [comment]
@hugocostadev - Good to see some of these old tickets get some attention.

It might be good to change the wording of your replies a bit. Obviously a ticket from 2021 would show a version that is no longer maintained 😆. 

I can confirm it does seem to be fixed in the latest releases though! 🙏

Thank you!

**Comment by hugocostadev** [comment]
Thank you @wreiske , you are right, I'll adapt the copy of my saved replies haha
