### ISSUE TITLE
Regression: Real name not shown anymore in citations

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#20540]
### Description:

Since RocketChat 3.10, citation does not show real username (even if option is on in settings)

![Capture d’écran du 2021-02-01 13-44-18](https://user-images.githubusercontent.com/57196916/106460455-ae2bac80-6493-11eb-852e-7ce62453e1ba.png)

### Steps to reproduce:

1. Add a citation
2. 
### Expected behavior:

Real name in citation

### Actual behavior:

Username in citation

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System:  Linux
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Linux

### Additional context

Related issue: https://github.com/RocketChat/Rocket.Chat/issues/20501

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/23051

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
