### ISSUE TITLE
Links open in internal browser

### ISSUE THREAD

**Issue by LenryNmQ** [RocketChat/Rocket.Chat#20543]
### Description:

If I got a URL in a message, I'll have the link itself, and a preview. If I click on the preview, it will open in my default browser, like it always did. But if I click on the link itself, it opens within the Rocket.Chat window.

### Steps to reproduce:

1. Send a URL in a message
2. Click on the URL itself - not the preview
3. It will open in the client

### Expected behavior:

Open links in default browser

### Actual behavior:

It opens inside the client
![Screenshot_20210201_162727](https://user-images.githubusercontent.com/26275827/106479261-6b290380-64aa-11eb-8e7c-08ed11b6009f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 3.11
- Operating System: Tried on Windows 10, Arch Linux and macOS

**Comment by DC7IA** [comment]
Can confirm, same desktop version.

**Comment by pkev777** [comment]
the same for me

**Comment by rhikura** [comment]
And same for me

**Comment by nickbroon** [comment]
Dup of #20460 ?

**Comment by kaffeeknecht** [comment]
Same in 3.9.7

**Comment by PaulVerhoeven1** [comment]
this is quite annoying 😐

**Comment by brunobertoldi** [comment]
A workaround I found is to click using the middle mouse button!

Version `3.11.0`

**Comment by Vkat14** [comment]
Cntrl Key + click opens it in the Browser
Shift Key + Click opens it in a new Rocket Chat Window(using the Internal Browser)

6 out 10 times, i forget to use the cntrl key and end up having to reload the app to clear it. I also noticed the Chat client now lags. You can see it if you try to move the window around. When the app is brought to view from the Minimized or Background state, it take a few seconds for the app the display the contents. You either get a White/Black screen. 

We do not manually update the Server and if version 3.11 contains the same problems with links then this may stretch itself out for the whole month of Feb. I am hoping 3.11 resolves performance issues.

**Comment by Silimilikim** [comment]
> 6 out 10 times, i forget to use the cntrl key and end up having to reload the app to clear it.

Instead of reloading the app, you can use Alt+left to go back to the previous screen. More convenient but still...

**Comment by Vkat14** [comment]
> 
> 
> > 6 out 10 times, i forget to use the cntrl key and end up having to reload the app to clear it.
> 
> Instead of reloading the app, you can use Alt+left to go back to the previous screen. More convenient but still...

Thank you for sharing this.

**Comment by cool-tiger** [comment]
> > 6 out 10 times, i forget to use the cntrl key and end up having to reload the app to clear it.
> 
> Instead of reloading the app, you can use Alt+left to go back to the previous screen. More convenient but still...

or `CMD+[` on mac os

**Comment by andreas-monday** [comment]
the problem continues in the version 3.11.1

**Comment by robbyoconnor** [comment]
This is weird -- because it does *NOT* happen on chat.rocket.chat but it *DOES* occur on my instance :(

**Comment by lelvisl** [comment]
but it happens on self-hosted instances. 3.10.5 and higher have this problem.

**Comment by ggazzo** [comment]
I think that was closed by https://github.com/RocketChat/Rocket.Chat/pull/20651

**Comment by xmedeko** [comment]
@ggazzo Which version is the fix scheduled to release?

**Comment by ggazzo** [comment]
> @ggazzo Which version is the fix scheduled to release?

at least 3.12.0 but since its quite annoying, probably at 3.11.2 as well

**Comment by marwin1991** [comment]
5.4 and still getting this error

**Comment by marwin1991** [comment]
@ggazzo
