### ISSUE TITLE
Since 3.10.5 user status is not displayed anymore below username in Header

### ISSUE THREAD

**Issue by sgohl** [RocketChat/Rocket.Chat#20541]
### Description:

Bevore 3.10.5, a user status was displayed below the username in the top header of the direct chat with the user.

![image](https://user-images.githubusercontent.com/8873017/106463626-f5b43780-6497-11eb-8dee-5d3ec1692c0a.png)

Although it is still displayed under User Information via top right icon, for convenience (and habit, after all), users expect status message below the peer's username at the top

**Comment by wreiske** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/20197
