### ISSUE TITLE
Cannot deploy livechat to Bluemix

### ISSUE THREAD

**Issue by rophy** [RocketChat/Rocket.Chat#2054]
Version: 0.13 to 0.15.

The error is very similar to issue #2019:

`/tmp/node-meteor-8RRp/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
throw(ex);
at Builder.write (/tools/isobuild/builder.js:225:13)
Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
at /tools/isobuild/isopack.js:1346:27
`

The deployment success after disabling livechat (as described in #2019), but #2019 specifically talks about Windows, and in this case, it's Bluemix which backend VM should be linux.

Steps to deploy to bluemix basically follows [official doc](https://github.com/RocketChat/Deploy.to.Cloud/tree/master/Bluemix), although I have used MONGO_URL instead of creating a MongoLab service (which shouldn't matter for this issue).

**Comment by geekgonecrazy** [comment]
@rophy do you know if this is still an issue with our newer releases?  We just released 0.30.0 Monday

**Comment by rophy** [comment]
@geekgonecrazy let me give it a try and get back to you.

**Comment by rophy** [comment]
I tried on latest build and the error is different, but still failed. 

commit 8a2a7676093e32f19e62c59db4ef0667d87032cd

```
       Meteor installed
Ignoring build of mobile platforms
       Building meteor bundle
       /tmp/node-meteor-WD7e/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
             throw error;
                   ^
       Error: ENOSPC, open '/tmp/node-meteor-WD7e/.meteor/packages/meteor-tool/.build328676..1.1.10.cr5gzd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js.map'
       Installing meteor bundle
/tmp/buildpacks/bluemix-buildpack-meteor/bin/compile: line 127: cd: /tmp/staged/app/.meteor/meteor_build/app/bundle/programs/server: No such file or directory
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed

```

I'll later try disabling livechat and see if it helps.

**Comment by geekgonecrazy** [comment]
That's odd...
`ENOSPC` is a node.js error that means that there is no space on the drive.

I know nothing about bluemix, is there a really tiny amount of space at your disposal?

**Comment by rophy** [comment]
Disabled livechat with same result. 
I think there is a 1GB space limit on bluemix apps, is this not enough?

**Comment by geekgonecrazy** [comment]
It should be.. I'm actually not sure how much space all of the meteor dependencies take up.

@RocketChat/core any ideas?  Shouldn't 1GB disk space be enough to download meteor and compile Rocket.Chat?

**Comment by rophy** [comment]
Anyway I can confirm this? Will disabling all non-necessary features from the package help? If you could provide me a list of features to disable, I can give it a try again.

**Comment by geekgonecrazy** [comment]
@rophy disabling features isn't really going to free up disk space.  Have you tried running one of our releases?  Looks like it's Linux x86 so one of our releases should run just fine.  Then you wouldn't even need to install meteor, you would just need Node.js

**Comment by rophy** [comment]
0.15 on bluemix works fine after disabling live chat. I can try a few newer versions and see when does the deployment starts failing.

**Comment by rophy** [comment]
Update:

- ENOSPC turns out to be a bug between bluemix and meteor 1.3: https://github.com/cloudfoundry-community/cf-meteor-buildpack/issues/20. I managed to fix the error by patching the cf-meteor-buildpack to explicitly use meteor 1.2.1 instead of the default 1.3.2.4.

- With meteor 1.2.1, Rocket.Chat 0.15 works (without livechat), but 0.30.0 doesn't work, with or without livechat. I couldn't see any useful info in the bluemix deployment logs, but it seems with livechat, deployment fails somewhere at build stage; and without livechat, the deployment looks to be success, but the app failed to run.



[rocket.chat.0.30.0.with.livechat.error.txt]
(https://github.com/RocketChat/Rocket.Chat/files/264649/rocket.chat.0.30.0.with.livechat.error.txt)

[rocket.chat.0.30.0.without.livechat.error.txt](https://github.com/RocketChat/Rocket.Chat/files/264650/rocket.chat.0.30.0.without.livechat.error.txt)

**Comment by geekgonecrazy** [comment]
@RocketChat/core any ideas?  I know livechat is like a mini meteor app.  Any thoughts?

**Comment by Sing-Li** [comment]
@rophy  I don't think we have ever had a successful livechat deploy with any CF cloud - Heroku, Bluemix, and so on.   My suggestion is, if you need LiveChat, to move to containers, VPS, VM,  and or bare-metal installs.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
