### ISSUE TITLE
3.11.0 Attachments and embed are cut off / limited in length

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#20556]
### Description:

The new embeds for messages have broken a lot of functionality we previously relied on. The new format is much larger and doesn't show the full message body.

### Steps to reproduce:

1. See below

### Expected behavior:

- [ ] Favicons shouldn't show if they don't exist or if they fail to load
- [ ] Messages shouldn't cut off with elipsis. 

#### Broken embed favicons shouldn't show if they don't exist

![image](https://user-images.githubusercontent.com/6295044/106578613-ef0bdb80-64fc-11eb-8159-68c3d00eb675.png)

#### Embeds have a ton of padding between words and don't show the full message body (cut off with ...)

![image](https://user-images.githubusercontent.com/6295044/106578774-22e70100-64fd-11eb-80d3-2a14fd1de57f.png)

Another example of a message getting cut off.
![image](https://user-images.githubusercontent.com/6295044/106578962-5a55ad80-64fd-11eb-847b-fe0edfd976cd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0

**Comment by wreiske** [comment]
#20555 was auto-closed by a robot, so I'm duplicating this ticket.

**Comment by aditya-mitra** [comment]
Can you point out the previous implementation (if you remember the file)?

I guess instead of wrapping the text with ellipsis, we can display the full text in multiple lines. Any suggestions?

**Comment by yash-rajpal** [comment]
Can you please elaborate on steps to reproduce?

Also this feels similar to #20539 , I don't know if this is same or different. Please check and confirm.
Thanks :)

**Comment by wreiske** [comment]
> Can you please elaborate on steps to reproduce?
> 
> Also this feels similar to #20539 , I don't know if this is same or different. Please check and confirm.
> Thanks :)

Steps to reproduce would be to setup an incoming webhook and send a long message to it. Try adding a few fields, etc...

This issue does not look like it is the same. The issue you listed is a markdown formatting issue. This ticket is more for the regression of embeds since the move to react from blaze.

**Comment by zpavlig** [comment]
after updating to version 3.11.0, the hooks also began to work like this:
![Снимок](https://user-images.githubusercontent.com/35609094/106588188-b27bc680-6574-11eb-9ad8-7df79f47bab3.JPG)

**Comment by fdellwing** [comment]
Can confirm this. Our social media webhooks are now limited to a very small text snippet.

**Comment by aditya-mitra** [comment]
**This also happens with `url embeds`.**

![url embed problem](https://user-images.githubusercontent.com/55396651/106614892-e0bbcf00-6591-11eb-8b81-15d3d4b91a71.png)

**Comment by websvcPT** [comment]
Plus one with version 3.11.0

![image](https://user-images.githubusercontent.com/1758961/106732743-f6201000-6608-11eb-8242-f0be9d392208.png)

**Comment by NargiT** [comment]
I do confirm that new version of attachments broke the rendering.

- Markdown are not supported in attachment anymore
![image](https://user-images.githubusercontent.com/3153333/106856735-3cd04180-66bf-11eb-989e-609f68294a66.png)
- text is cut

**Comment by aditya-mitra** [comment]
@wreiske Just a question.
Does #20606 fix the second part of your issue - ***Message are cutoff*** ?

**Comment by svrnwnsch** [comment]
will this be fixed in version 3.11.1?

**Comment by aditya-mitra** [comment]
@wreiske 
Can you please change the title of this issue? This is because it not related to `OEmbeds` but to `DefaultAttachments`. That created a confusion which led to *the wrong PR which would have closed this issue (my mistake)*. 
More on this here at [#20560 comment](https://github.com/RocketChat/Rocket.Chat/issues/20560#issuecomment-773176388). Thanks you very much @dannielpotthast for pointing it out.

A better title would be **`3.11.0 DefaultAttachments - Text is cutoff and Improper Layout`**

But, thanks to you we could figure out another significant bug that there was problem in **URL Embed** as pointed out in #20628 .

However, I am sure #20606 and #20618 will be able to resolve the last 2 problems in this issue. (The Favicon Issue can be tackled in Rocket.Chat.Fuselage where I have put up [this issue of broken images](https://github.com/RocketChat/Rocket.Chat.Fuselage/issues/393)

If am missing anything, please help me by pointing them out.

Thanks a lot again.

**Comment by wreiske** [comment]
@aditya-mitra amazing work fixing these so quickly! I will change the title to something better.

**Comment by Karting06** [comment]
I'm using an integration that sends multiple fields with short param true. In previous versions, it uses the whole width. Now, it seems to be limited to 480 px (limited by CSS parameter `max-width`). 

This PR changes it back to using whole width: #20645

**Comment by RealJTG** [comment]
Attachment fields now looks really clumsy 

![_2021-02-12-010856_1519x544_scrot](https://user-images.githubusercontent.com/930399/107711402-444fa600-6cd0-11eb-9c10-a5a579cd0650.png)

**Comment by aditya-mitra** [comment]
@RealJTG Will #20618 solve the problem indicated by you by any chance?

**Comment by Karting06** [comment]
@RealJTG For the width, that should be fixed with #20645

**Comment by Exordian** [comment]
we'd love to see a minor version bump with a fix included. this change broke the view of a lot of integrations on our instance

**Comment by phil-davis** [comment]
Here is a "simple" example of how the chat message is cut off and also does not wrap:
![Screenshot_2021-02-16 Chat](https://user-images.githubusercontent.com/1535615/108052749-ad3e7180-7074-11eb-90fc-29c044a85df3.png)

**Comment by immanuelfodor** [comment]
@phil-davis You're lucky that you get clickable links at the cutoff, I'm stuck with unformatted markdown with broken links 😅

**Comment by svrnwnsch** [comment]
> 
> 
> @phil-davis You're lucky that you get clickable links at the cutoff, I'm stuck with unformatted markdown with broken links 😅

we have this too it is very annoying and frustating please fix this soon 🙏

**Comment by ggazzo** [comment]
@wreiske are you sure about the embed avatar? We didnt change the embeds yet. I'm not saying thats ok, but maybe its not related with 3.11.0 🤔

**Comment by DerDanilo** [comment]
Same here. Is there some seeting that can be changed?

**Comment by fdellwing** [comment]
There is #20569 and #20606 for this.

**Comment by wreiske** [comment]
After upgrading to 3.14.0, the padding between the fields from my initial report looks to be fixed. 

![image](https://user-images.githubusercontent.com/6295044/116728624-fbd48a00-a99a-11eb-96f7-7309d0cf5a62.png)

Also, it looks like the text now properly wraps instead of being hidden by an ellipsis.
![image](https://user-images.githubusercontent.com/6295044/116728873-52da5f00-a99b-11eb-965f-80422fa20fca.png)

I'm going to mark this ticket as resolved/closed as this is now fixed in the 3.14.0 release. If anyone has a specific issue that doesn't relate exactly to the initial issue I opened, please feel free to create a new issue! 

Thanks :)
