### ISSUE TITLE
PDF-Preview not working / file not found

### ISSUE THREAD

**Issue by Attack44** [RocketChat/Rocket.Chat#20559]
### Description:

Image upload works without problems, but to PDF files there is no preview and when clicking the file is not found (404) although anonymous users have access to the file.

### Steps to reproduce:

For example, if I call the link directly in the browser, the message 404 also appears, but the file is downloaded.
![Unbenannt3](https://user-images.githubusercontent.com/19206966/106591706-e2b06e80-654e-11eb-9f1f-bd8034bf4371.PNG)

### Actual behavior:
![Unbenannt](https://user-images.githubusercontent.com/19206966/106591723-e7752280-654e-11eb-87c7-160625ba2a11.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/19206966/106591731-e8a64f80-654e-11eb-9d5c-3feab99cd6a8.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.20.1
- MongoDB Version: 4.0.10

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10 x64 20H2

**Comment by kalexnolasco** [comment]
I have the same problem for this realease! :( 
![image](https://user-images.githubusercontent.com/45315260/106598037-81d96400-6557-11eb-9f5f-8887b4dd5a84.png)

**Comment by Darshilp326** [comment]
@Attack44 What is your expected behavior? Do you need the file to get downloaded on clicking that title?

**Comment by Darshilp326** [comment]
@Attack44 What do you think should be the expected behaviour?

**Comment by Attack44** [comment]
@Darshilp326 That the PDF document can be opened in the Rocket.Chat application and a preview of it is displayed in the chat. And in the browser no error page 404 is displayed, that you can also display it directly in the browser.

**Comment by AlexanderNeumann** [comment]
I have the same issue.. 
When I try to open a pdf file via the link on the filename I get this 404 page and if I return to the chat I get blank page... I have to refresh the client in order to get the chat history back.

**Comment by yash-rajpal** [comment]
I think all attachments are being re-written in react. They are implementing preview thing and we will get to see that soon in next releases. :)

**Comment by adocampo** [comment]
Preview of PDF was working on former versions, and I'm missing office previews as well, currently, just a tiny link that often goes unnoticed and users misses the attachment.
It would be great to have a preview of every file, or at least, emphasize somehow there is an attachment (like the name of the filename in a huge typo inside a square, and all the square clickable)

**Comment by lascapi** [comment]
Hi! we have the same error.

When we click on this link we get the 404 error:  `<a href="/file-upload/rsrs/AngularForms.pdf" >Angular Forms.pdf</a>`

When we click on this one, we can download the file: `<a target="_blank" download="AngularForms.pdf" href="/file-upload/rsrs/AngularForms.pdf"> 🔽  </a>`

At least we want to be able to download the file with both links. Or the preview with one of them. 🙂

**Comment by chubber147** [comment]
Hi there,
we have the same error in ubuntu installation version 3.11 and a docker installation  in latest version 3.12. Download of pfs is working though.

**Comment by ken8848** [comment]
I have the same problem with version 3.12.3

**Comment by ggazzo** [comment]
I believe this issue was closed here: https://github.com/RocketChat/Rocket.Chat/pull/21096 check the version 3.13.0. Any problem let me know
