### ISSUE TITLE
Sound Notifications Do Not Work for Omnichannel New Chat Queue

### ISSUE THREAD

**Issue by ryand00** [RocketChat/Rocket.Chat#20554]
### Description:

Agents are not notified by sound notification that there is new chat in queue. Once agent takes chat, then sound notifications work - but not during initial chat entry into queue to let agents know there is a new chat waiting.  Web browsers' sound notifications are enabled, so problem is not with web browser settings.  Windows sound notifications are also enabled.

### Steps to reproduce:

1. Set Omnichannel routing method to Manual.
2. Start new chat from widget.
3. New chat shows up in agent queue but there is no sound notification.
4. Once agent takes chat, then sound notification works.

### Expected behavior:

Agents are notified by sound notification that there is new chat in queue.

### Actual behavior:

Agents are not notified by sound notification that there is new chat in queue.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.7
- Operating System: Linux (Ubuntu)
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox
- Operating System: Windows 10

**Comment by igmarketing** [comment]
Yes please fix this... it's critical to make it work.

**Comment by brunohl91** [comment]
Anything on this one?

**Comment by diego219** [comment]
same here.

**Comment by PiotrMichalski1987** [comment]
The sound does not work
