### ISSUE TITLE
logging with oauth destroys current account

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#2055]
Step to reproduce:

- register with your email
- have some chats
- logout
- register with oauth (which contains the same email, in my case, I tried with GitHub)
- logout
- login with your email again: you can't the oauth registration just destroyed your previous account.

expected behaviour:
The oauth login should not create a new account but attach it to your current account (same email).

**Comment by marceloschmidt** [comment]
I can confirm this is happening!

**Comment by sampaiodiego** [comment]
just explaining: this was the expected behaviour because the first user have not confirmed their email address.. 

imagine if a unkown user register using your email address.. what would be the expected result when you (the real owner of that email address) log in?

@pierreozoux you'll get your _expected behaviour_ if you confirm the email address of the first registered user, ok?

**Comment by philipwhiuk** [comment]
Is there a warning that this occurs @sampaiodiego ?

**Comment by sampaiodiego** [comment]
@philipwhiuk no.. this is done silently..

**Comment by engelgabriel** [comment]
I guess we should have a warning.

**Comment by rodrigok** [comment]
@engelgabriel should we show this warning before or after the login?

**Comment by engelgabriel** [comment]
I believe after.. would that be possible?

**Comment by rodrigok** [comment]
Maybe we can set a flag inside the user's record to show this warning.

**Comment by marceloschmidt** [comment]
This is how we plan on fixing it: when logging in via OAuth, if the e-mails already exists but is not verified, the accounts will be merged, the password of the existing account will be reset and the user will be requested to input a new password. If the e-mail was verified, account will be merged as usual.

**Comment by royalaid** [comment]
Will this provide the option to merge the old account messages into the new account?
