### ISSUE TITLE
New message indicator overlaps "hide room" button

### ISSUE THREAD

**Issue by jasperla** [RocketChat/Rocket.Chat#2056]
When there's a new message in a _direct message_ or _private_ group, the green indicator is positioned on the right side of the group name. However this overlaps the `hide room` button, but clicking on the green "new message indicator" does hide the room. This is confusing and the green indicator should be positioned further to the left so as not to overlap visually.

**Comment by brakhane** [comment]
This is fixed as part of #2113

**Comment by jasperla** [comment]
Great, thanks!
