### ISSUE TITLE
[3.10.5] Emoji reaction to posts can not be deleted

### ISSUE THREAD

**Issue by qchn** [RocketChat/Rocket.Chat#20566]
### Description:

If you react to someones post with an emoji, you're unable to delete the emoji by clicking on it.

### Steps to reproduce:

1. go to a room
2. click on the burger menue of someones post
3. click "add reaction"
4. react with some emoji
5. click on your reaction in order to remove it
6. nothing happens

### Expected behavior:

the emoji react should be deleted when clicking on it

### Actual behavior:

see attached video: https://youtu.be/2gNyW0oyHkM

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Debian Linux
- Deployment Method: tar
- Number of Running Instances: 8
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.18

### Client Setup Information

- Desktop App or Browser Version: Firefox, Chrome latest Version, native Client latest Version
- Operating System: Mac, Windows, Linux

### Additional context

none

### Relevant logs:

see attached video: https://youtu.be/2gNyW0oyHkM

**Comment by aKn1ghtOut** [comment]
Closed by #20179. Should be fixed in 3.12, or whatever the next release will be
