### ISSUE TITLE
[3.10.5] Markdown in a channels description is no longer displayed

### ISSUE THREAD

**Issue by qchn** [RocketChat/Rocket.Chat#20565]
### Description:

markdown language in a channel description is no longer interpreted and will be displayed as plain text

### Steps to reproduce:

1. Go to channel
2. look at description in markdown format
3. see it's just plaintext

### Expected behavior:

markdown language should be interpreted and displayed as formatted text

### Actual behavior:

it's just plaintext

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Debian Linux
- Deployment Method: tar
- Number of Running Instances: 8
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.18

### Client Setup Information

- Desktop App or Browser Version: Firefox, Chrome latest Version, native Client latest Version
- Operating System: Mac, Windows, Linux

### Additional context

-

### Relevant logs:

see screenshot attached
![Bildschirmfoto 2021-02-02 um 14 22 55](https://user-images.githubusercontent.com/747735/106606813-d7673e00-6562-11eb-8e5b-fed8cb7ab5a7.png)

**Comment by aKn1ghtOut** [comment]
Fixed by #20021. Should be in 3.11

**Comment by qchn** [comment]
Thank you, @aKn1ghtOut
