### ISSUE TITLE
Tooltip of star icon for making channel favorite/unfavorite shows wrong title.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20571]
### Description:
The tooltip of the star icon for making channel favorite/unfavorite shows wrong information.

### Steps to reproduce:

1. Any Room
2.  Header
3. Tooltip of star icon.

### Expected behavior:
It should show the correct information.

### Actual behavior:
The tooltip title doesn't get updated.

https://user-images.githubusercontent.com/55157259/106643424-ba0c9100-65af-11eb-9cc0-ad115ce7fcaa.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
Why are the tooltip titles shown twice?
Please help me!

**Comment by yash-rajpal** [comment]
I also faced this issue, wasn't able to fix this.
Thanks for reporting. :)
