### ISSUE TITLE
Clicking on username not open user card

### ISSUE THREAD

**Issue by Igloczek** [RocketChat/Rocket.Chat#20572]
### Description:

After clicking username in channel messages, nothing happens.

### Steps to reproduce:

1. Open any channel with messages
2. Click on username

### Expected behavior:

Open user card.

### Actual behavior:

Error in console appears:
```
Error: marked(): input parameter is of type [object Object], string expected
```

After short debugging with breakpoints, I can confirm that `marked` gets object looking like a React component, not a string.

![image](https://user-images.githubusercontent.com/5119280/106654070-ec11f900-6597-11eb-9571-42755e528514.png)

https://user-images.githubusercontent.com/5119280/106655131-43fd2f80-6599-11eb-9595-b019e5c339ae.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Linux 5.4.0-1029-aws
- Deployment Method: I'm not sure, but if it will be relevant I can get more information
- Number of Running Instances: I'm not sure, but if it will be relevant I can get more information
- DB Replicaset Oplog: I'm not sure, but if it will be relevant I can get more information
- NodeJS Version: v12.18.2
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: Not related, every app and browser behaves the same
- Operating System: Not related, tested on multiple OS

**Comment by kenkirito** [comment]
can I work on it

**Comment by tensor5g** [comment]
Appears to be resolved in 3.11.1

**Comment by Igloczek** [comment]
@tensor5g Did you find some related issue / pull request? I don't find anything similar in the changelog of 3.11.0 and 3.11.1.

**Comment by tensor5g** [comment]
@Igloczek I did not, however it is working for me now. Are you still having the same issue after upgrading?

**Comment by wolfcreative** [comment]
3.9.7 and 3.10.5 - there is an error.
3.11.1 - there is no error.

Checked just now.

**Comment by Igloczek** [comment]
Thanks for checking out, I'll give it a try too 🙇

**Comment by Igloczek** [comment]
I can confirm it works on 3.11.1, closing.
