### ISSUE TITLE
[Federation][Bug] FEDERATION_Error_user_is_federated_on_rooms error on delete some users

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#20577]
### Description:

It is now impossible to delete via Admin some users with error `FEDERATION_Error_user_is_federated_on_rooms`
I think, that users was added to some chats at federated server.

### Steps to reproduce:

1. Setup Federation with another server
2. Create Private Group at federated server
3. Add user from origin server to that Private Group
4. Try to delete that user in Admin Panel of origin server
5. Get error `FEDERATION_Error_user_is_federated_on_rooms`

### Expected behavior:

Any user should be deleted from Admin Panel without any error

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/106706119-37f88880-6600-11eb-9c30-2840dbeac6ff.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 30
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.17 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.1.1 and Chrome 88
- Operating System: Windows 10

### Additional context

@alansikora please take a look. I think that situation not handled in codebase.

### Relevant logs:

```
POST https://rc.company.com/api/v1/users.delete 400 (Bad Request)
send @ 74924189af13495727b0dc731bc9c7f662fde1a0.js?meteor_js_resource=true:48
ajax @ 74924189af13495727b0dc731bc9c7f662fde1a0.js?meteor_js_resource=true:48
l @ 74924189af13495727b0dc731bc9c7f662fde1a0.js?meteor_js_resource=true:423
_jqueryCall @ 74924189af13495727b0dc731bc9c7f662fde1a0.js?meteor_js_resource=true:423
post @ 74924189af13495727b0dc731bc9c7f662fde1a0.js?meteor_js_resource=true:423
post @ 74924189af13495727b0dc731bc9c7f662fde1a0.js?meteor_js_resource=true:423
c @ /client/providers/ServerProvider.js:1
eval @ /client/contexts/ServerContext.ts:1
eval @ /client/admin/users/UserInfoActions.js:1
eval @ /client/admin/users/UserInfoActions.js:1
ba @ /node_modules/react-dom/cjs/react-dom.production.min.js:22
ja @ /node_modules/react-dom/cjs/react-dom.production.min.js:22
ka @ /node_modules/react-dom/cjs/react-dom.production.min.js:22
oa @ /node_modules/react-dom/cjs/react-dom.production.min.js:23
lc @ /node_modules/react-dom/cjs/react-dom.production.min.js:60
jc @ /node_modules/react-dom/cjs/react-dom.production.min.js:59
mc @ /node_modules/react-dom/cjs/react-dom.production.min.js:60
sc @ /node_modules/react-dom/cjs/react-dom.production.min.js:64
Ia @ /node_modules/react-dom/cjs/react-dom.production.min.js:295
Ma @ /node_modules/react-dom/cjs/react-dom.production.min.js:27
Rc @ /node_modules/react-dom/cjs/react-dom.production.min.js:78
id @ /node_modules/react-dom/cjs/react-dom.production.min.js:77
exports.unstable_runWithPriority @ /node_modules/scheduler/cjs/scheduler.production.min.js:27
cg @ /node_modules/react-dom/cjs/react-dom.production.min.js:130
Ga @ /node_modules/react-dom/cjs/react-dom.production.min.js:295
gd @ /node_modules/react-dom/cjs/react-dom.production.min.js:76
```

**Comment by ankar84** [comment]
Hey, @alansikora 
Can you take a look at that issue?

**Comment by ankar84** [comment]
Still an issue in 3.16.3

**Comment by hkpanchani** [comment]
Same issue in 3.17.1

Unable to delete federated user..
It would be great if we can limit the users from specific server at least.
After enabling federation list in my users got so dirty and also unable to remove them.

**Comment by ankar84** [comment]
Still at 3.18.2

**Comment by tmatthaeus** [comment]
I have this issue in Rocket.Chat Version 4.2.2 too.

**Comment by olemsi** [comment]
Same issue in 3.8.0

**Comment by ankar84** [comment]
Closing that in favor of Matrix federation
