### ISSUE TITLE
Unpinning a message in a thread doesn't unpin the message notification in channel

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#20576]
### Description:

Unpinning a message in a thread doesn't unpin the message notification in the channel.

### Steps to reproduce:

1. Pin a message in a thread.
2. Notification appears in the main channel that message has been pinned.
3. Unpin the message in the thread.

### Expected behavior:

The message notification in the channel disappears as the message has been unpinned.

### Actual behavior:

The notification that a message has been pinned remains and is not deletable. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Occurs in both Desktop App (3.1.1) and Browsers (Firefox 85.0, etc)
- Operating System: Windows 10 and Linux Mint 19.3 and 20.1

### Additional context

Not at the moment.

### Relevant logs:

Unsure of relevant Rocket Chat logs.

No Browser logs.

**Comment by AvivBenShoham** [comment]
@nooblag I would like to work on this bug

**Comment by nooblag** [comment]
Great!

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.
