### ISSUE TITLE
[3.10.5] Sync to cloud.rocket.chat does not work

### ISSUE THREAD

**Issue by qchn** [RocketChat/Rocket.Chat#20587]
### Description:

I tried to install the Poll plugin through the Marketplace, whenever it sends me to cloud.rocket.chat, I get an error and can not login. 
Syncing my Rocket.Chat instance – as recommended – does not bring any change.

### Steps to reproduce:

1. Go to Admin Interface on Rocket.Chat Setup
2. Select Plugin in the Marketplace
3. Click on Install
4. Click on "Marketplace Login Required" 
5. Get redirected to cloud.rocket.chat 
6. Error: "Invalid redirect uri. If you are attempting to login to your workspace, please go back and click the "Sync" button"

### Expected behavior:

The installation process should work :-)

### Actual behavior:

![Bildschirmfoto 2021-02-03 um 17 39 06](https://user-images.githubusercontent.com/747735/106779228-166ebf80-6647-11eb-818d-729e9d86bb18.png)
![Bildschirmfoto 2021-02-03 um 17 38 47](https://user-images.githubusercontent.com/747735/106779237-179fec80-6647-11eb-9a4b-f94a43f5a019.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Debian Linux
- Deployment Method: tar
- Number of Running Instances: 8
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.18

### Client Setup Information

Google Chrome 88.0.4324.96 on MacOS (latest)

### Additional context

/

### Relevant logs:

/

**Comment by qchn** [comment]
Hi @ggazzo, @geekgonecrazy, @engelgabriel, @rodrigok 

can someone help me with this, please? 

Best
Robert

**Comment by geekgonecrazy** [comment]
@qchn did you happen to use the offline install registration method when registering?  If so this might have been the problem.  Try hitting sync and then try again.  If it still doesn't work.. looks like you DM'd me already just follow up there with your workspace address and I can check things out for you on the cloud side

**Comment by qchn** [comment]
Yes, I sent you the details via DM at open.rocket.chat 

Thanks in advance!

**Comment by qchn** [comment]
This issue has been resolved, special thanks to @geekgonecrazy ⭐

**Comment by geekgonecrazy** [comment]
When tried again it worked.  A bug was fixed related to offline install.

a lot of people chose offline install even though the workspace still has internet access.  When we created we tested fully airgapped. It didn’t set proper oauth redirect, now it does
