### ISSUE TITLE
"Jump to message" does not work for thread messages

### ISSUE THREAD

**Issue by NoUsername** [RocketChat/Rocket.Chat#20581]
### Description:

When searching for a message from a thread, the results are shown like they would come from a different channel and navigating there doesn't work

### Steps to reproduce:

1. Go to global search from another room, lets say direct-chat with user "@dummy"
2. Search for a message you know comes from a thread inside another channel let's say from "#thatChannelWithThreads"
3. The message will be found but it will show as if it appeared in "@dummy"
4. Try "jump to message"

### Expected behavior:

at 3. you would expect to see "#thatChannelWithThreads"
at/after 4. you would expect to go to that channel and that thread is open where the message was posted

### Actual behavior:

at 3. the message looks like it appeared in the room "@dummy"

at/after 4. You get to an error-screen showing "invalid room"

![image](https://user-images.githubusercontent.com/494584/106719583-c4a44600-6602-11eb-85b5-d6a6fb05381e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.4
- Operating System: unknown
- Deployment Method: unknown
- Number of Running Instances: unknown
- DB Replicaset Oplog: unknown
- NodeJS Version: unknown
- MongoDB Version: unknown

### Client Setup Information

- Desktop App or Browser Version: 3.0.7
- Operating System: Windows 10

### Additional context

-

### Relevant logs:

-

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
