### ISSUE TITLE
SMTP Fixes Require Two-Factor Authentication, which cannot work because if SMTP needs updating.

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#20591]
Description:  SMTP Fixes Require Two-Factor Authentication, which cannot work because if SMTP is broken ...

Steps to reproduce:

1. Go to Administration
2. Go to Settings
3. Go to Email
4. Go to SMTP
5. Put in corrected SMTP settings.
6. Click on Save Changes
7. Get:  Verify your email for the code we sent
8.  ¯\\_(ツ)_/¯

Expected behavior:
Saves the settings so that email 2FA works and you can continue working.

Actual behavior:
Asks for two-factor code to save the settings for the thing that needs to be sent to have a two-factor element.

I'm sure that you can probably fix this CLI side, but .... that feels like shouldn't be that way.

Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Linux Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: n/r
- NodeJS Version: n/r
- MongoDB Version: n/r

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
