### ISSUE TITLE
the message shows only part of the content in room(webhook)

### ISSUE THREAD

**Issue by bamboo0915** [RocketChat/Rocket.Chat#20599]
### Description:

The message is folded without showing all on pc , but can show all on phone, the message is come from webhook

### Steps to reproduce:

1. webhook message in room

### Expected behavior:

Display all messages

### Actual behavior:

A message shows only part of the content

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: macos

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by svrnwnsch** [comment]
This bug is probably already tracked with #20556.
