### ISSUE TITLE
"Exception in defer callback: TypeError: dompurify.sanitize is not a function" when using Auto-Translate feature

### ISSUE THREAD

**Issue by ThangHuuVu** [RocketChat/Rocket.Chat#20598]
### Description:

My Auto-Translate provider is DeepL. Here is how the error manifests itself:
```
Exception in defer callback: TypeError: dompurify.sanitize is not a function
at Object.marked (app/markdown/lib/parser/marked/marked.js:115:23)
at MarkdownClass.parseMessageNotEscaped (app/markdown/lib/markdown.js:45:11)
at DeeplAutoTranslate.tokenizeCode (app/autotranslate/server/autotranslate.js:196:22)
at DeeplAutoTranslate.tokenize (app/autotranslate/server/autotranslate.js:131:18)
at app/autotranslate/server/autotranslate.js:277:26
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at packages/meteor.js:550:25
at runWithEnvironment (packages/meteor.js:1286:24)
```
### Steps to reproduce:

1. Go to Administration -> Message -> Auto-Translate and enable Auto-Translate.
1.1. If using DeepL, insert the API key 
2. Open a chat window, choose Auto-Translate in the Options menu.
3. Select a language to translate. For example: German
4. Begin to chat. For example "Guten morgen". 

### Expected behavior:

The chat is translated.
### Actual behavior:

The error shows in the Docker log.
### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0 
- Operating System: Linux
- Deployment Method:  Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 88.0.4324.96 (Official Build) (x86_64)
- Operating System: Mac OS Catalina 10.15.7

### Additional context

This is also happening on 3.9.7.
From my observation this bug is related to this [security fix](https://github.com/RocketChat/Rocket.Chat/commit/14c2acf4f62162240d5893b8bdd7b1760bf2bcee)

**Comment by Karting06** [comment]
It also happens with incoming WebHooks when using Marked Markdown.
I think that it happens due to DOMPurify not supporting server side rendering?

**Comment by ThangHuuVu** [comment]
@Karting06 most probably. If I get it right from the dompurify page we would also need `jsdom` here

**Comment by Karting06** [comment]
Yeah or using another sanitizer? 
Do you use Marked?
Is the autotranslate function completely broken?

**Comment by ThangHuuVu** [comment]
> Yeah or using another sanitizer?
Do you have any suggestion for other sanitizer?
> Do you use Marked?
Yes, my parser is Marked
> Is the autotranslate function completely broken?
From my testing it is 100% broken

**Comment by ThangHuuVu** [comment]
@Karting06 Thanks for the suggestion, I checked again with another parser (Original) and the translation feature works. I guess this is one way to work this issue around. However in our case we cannot apply this fix because on one of our client we are using markdown-it, a different parser. Therefore, the markdown text will just break on our client side. Still in dire need for help here.

**Comment by MartinSchoeler** [comment]
Hey @Karting06 @ThangHuuVu [This PR should resolve the issue](https://github.com/RocketChat/Rocket.Chat/pull/20665), I couldn't get a deepl api key for testing this one as of now, so feel free to test out these changes in your local instances. Thanks!
