### ISSUE TITLE
Proper media types for uploading all file types (mediaType)

### ISSUE THREAD

**Issue by popiolek** [RocketChat/Rocket.Chat#2059]
Just a quick question: to what value should I set mediaType property to accept all files for upload? I've tried `*` and `*/*` as the value but it didn't work.

I mean the field:
<img width="638" alt="zrzut ekranu 2016-01-28 13 57 34" src="https://cloud.githubusercontent.com/assets/3855610/12645010/3756704c-c5c7-11e5-8a48-b1260c50ae6a.png">

**Comment by marceloschmidt** [comment]
Leave it empty and it will accept all media types. I'll add that to the text below the input.

**Comment by popiolek** [comment]
Just a suggestion: maybe instead of `Accepted Media Types` it should be called `Filter Media Type to` or something like that so that the title is consistent with that empty value.

**Comment by DmitriyLyalyuev** [comment]
I set Media types to empty as described but Rocket not upload any file:
http://shrt.pp.ua/f8

**Comment by graywolf336** [comment]
@DmitriyLyalyuev Have you restarted your Rocket.Chat instance? This change requires that.

**Comment by DmitriyLyalyuev** [comment]
Thank you. I disable file upload and enabled it again. It works now perfectly.
