### ISSUE TITLE
[BUG] Global search not turned off by default

### ISSUE THREAD

**Issue by RonLek** [RocketChat/Rocket.Chat#20595]
### Description:

When global search is turned on the default behaviour **is** of global search which should **not** be the case as addressed [here](https://github.com/RocketChat/Rocket.Chat/pull/19777)

### Steps to reproduce:

1. Enable Global Search from Administration.
2. Click on search icon in a channel.
3. Search for any string without checking the global search checkbox.

### Expected behavior:

The search shouldn't be global since the global search checkbox is checked off initially.

### Actual behavior:

The search is a global search.

https://user-images.githubusercontent.com/28918901/106859375-f2fc5100-66e8-11eb-9889-d1041c007dc2.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu 18.04 LTS
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chromium
- Operating System: Ubuntu 18.04 LTS

**Comment by ankar84** [comment]
Confirm that issue
