### ISSUE TITLE
Create Admin User

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#206]
I see form the logs that there is an admin user that is automatically created.

Is it the excepted behavior for production environment?
Can I set it up from ENV variable?
How can I delete it from a production environment?
How can I change the password?

Thanks for your answers :)

**Comment by engelgabriel** [comment]
If a ADMIN_PASS is provided during the installation, we should create an admin user with that password, otherwise, the first user to register should be the admin user.
Depends on #222

**Comment by pierreozoux** [comment]
I'm totally fine with first user registered is the admin.
But yeah, the best way would be to create the admin on the first run with ADMIN_PASS, ADMIN_EMAIL.

**Comment by marceloschmidt** [comment]
I've created this. If you run with ADMIN_PASS and ADMIN_EMAIL, server will look for an admin user or another user with provided e-mail. If none is found, admin user is inserted. We need to update README accordingly.
