### ISSUE TITLE
Url with Whitespace send by Webhook failed

### ISSUE THREAD

**Issue by SimFirehawk** [RocketChat/Rocket.Chat#20600]
I use the webhook from Rocket.Chat to send messages to a Rocket.Chat channel.

I want to post a message, which contains a link.
Part of the message content ist [LinkName](https://myurl.org/some space/index.html) interpreted by Rocket.Chat as markdown.

The problem is, that the Url contains a whitespace. 
In the past, it was possible to encode the url and send it to the Rocket.Chat in the way, that the markdown looked like: [LinkName](https://myurl.org/some%20space/index.html)

It looks like this is no longer possible. As I understand the Url ist encoded again from Rocket.Chat. The result I get, when I use the encoded URL is: [LinkName](https://myurl.org/some%2520space/index.html)
because the % sign is encoded again by Rocket.Chat.

When I do not encode the url by myself, Rocket.Chat does not encode the Url by itself. So sending [LinkName](https://myurl.org/some space/index.html)  will still result in [LinkName](https://myurl.org/some space/index.html), means no encoding happened.

Any suggestions?

**Comment by yash-rajpal** [comment]
I am not able to reproduce this on new version 3.11.0. The % symbol for me is not being encoded again.
