### ISSUE TITLE
How to upload Apple Office suite files?

### ISSUE THREAD

**Issue by alvarow** [RocketChat/Rocket.Chat#2061]
Hello, 

Can we add mime types for Apple Keynote, Pages and Numbers? I am unable to upload those. I have tried appending the below list to File Upload -> Accepted Media Types:

`image/vnd.microsoft.icon, application/keynote, application/x-iwork-keynote-sffkey, application/vnd.apple.keynote, application/vnd.apple.pages, application/vnd.apple.numbers`

But still not allowed to upload.

Thanks

**Comment by graywolf336** [comment]
Have you restarted your server after putting those values in? If not, try
to and see if it allows you to then.

**Comment by alvarow** [comment]
I did, I am running 0.15.0... no joy :-1:

**Comment by marceloschmidt** [comment]
Could you please try `application/x-iwork-pages-sffpages`, `application/x-iwork-keynote-sffkey` and `application/x-iwork-numbers-sffnumbers`?
Don't forget to restart your server, as this is still required for changes to take effect.
Thanks.

**Comment by alvarow** [comment]
That seem to work. Thanks for the help.
