### ISSUE TITLE
[BUG] Message attachments not showing in the interface by any of the integrations or Rocket Chat itself

### ISSUE THREAD

**Issue by ruvenss** [RocketChat/Rocket.Chat#20615]
### Description:

All the Integrations using the REST API and sending structures like 
`{
	"alias": "'.$subject.'",
	"avatar": "https://rgwit.be/images/atm.svg",
	"roomId": "asff849df4e98f4sd",
	"text": "@Booking Data",
	"attachments": [{
		"author_icon": "https://rgwit.be/images/atm.svg",
		"author_link": "#",
		"author_name": "Annuler la Vente ",
		"collapsed": false,
		"color": "#fff",
		"fields": [{
				"short": true,
				"title": "Total à payer",
				"value": "18000 EUR"
			},
			{
				"short": true,
				"title": "Réservation",
				"value": "18558"
			},
			{
				"short": false,
				"title": "____________________________________________________",
				"value": ""
			},
			{
				"short": true,
				"title": "Goods",
				"value": "'.$message.'"
			},
			{
				"short": true,
				"title": "Destination",
				"value": "'.$pod.'"
			},
			{
				"short": false,
				"title": "____________________________________________________",
				"value": ""
			},
			{
				"short": true,
				"title": "Goods category",
				"value": "Category"
			},
			{
				"short": true,
				"title": "Departure",
				"value": "Morning Calm"
			}
		],
		"message_link": "#'",
		"text": "Booking ID",
		"title": "To cancel the sale, please click here",
		"title_link": "#",
		"title_link_download": false,
		"ts": "timestamp"
	}]
 `

### Steps to reproduce:

1.  `curl -X POST -H "Content-type: application/json" -H "X-Auth-Token: your-token" -H "X-User-Id: your-user-id" rocketchathost/api/v1/chat.postMessage -d @file.json`

### Expected behavior:

4 columns with data  

### Actual behavior:

just the subject

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian 10
- Deployment Method: Manual
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.0.3  
- Operating System: Mac OS

### Additional context

No additional context

### Relevant logs:

No relevant logs please try the json structure in the code

**Comment by ggazzo** [comment]
I'm closing this issue, what happened here is the misuse of the `message_link` parameter, which should only be used with 'quotes' 

Anything please, let me know

**Comment by adolfombarros** [comment]
> ### Description:
> All the Integrations using the REST API and sending structures like
> `{ "alias": "'.$subject.'", "avatar": "https://rgwit.be/images/atm.svg", "roomId": "asff849df4e98f4sd", "text": "@Booking Data", "attachments": [{ "author_icon": "https://rgwit.be/images/atm.svg", "author_link": "#", "author_name": "Annuler la Vente ", "collapsed": false, "color": "#fff", "fields": [{ "short": true, "title": "Total à payer", "value": "18000 EUR" }, { "short": true, "title": "Réservation", "value": "18558" }, { "short": false, "title": "____________________________________________________", "value": "" }, { "short": true, "title": "Goods", "value": "'.$message.'" }, { "short": true, "title": "Destination", "value": "'.$pod.'" }, { "short": false, "title": "____________________________________________________", "value": "" }, { "short": true, "title": "Goods category", "value": "Category" }, { "short": true, "title": "Departure", "value": "Morning Calm" } ], "message_link": "#'", "text": "Booking ID", "title": "To cancel the sale, please click here", "title_link": "#", "title_link_download": false, "ts": "timestamp" }] `
> 
> ### Steps to reproduce:
> 1. `curl -X POST -H "Content-type: application/json" -H "X-Auth-Token: your-token" -H "X-User-Id: your-user-id" rocketchathost/api/v1/chat.postMessage -d @file.json`
> 
> ### Expected behavior:
> 4 columns with data
> 
> ### Actual behavior:
> just the subject
> 
> ### Server Setup Information:
> * Version of Rocket.Chat Server: 3.11.0
> * Operating System: Debian 10
> * Deployment Method: Manual
> * Number of Running Instances: 1
> * DB Replicaset Oplog: Enabled
> * NodeJS Version: v12.18.4
> * MongoDB Version: 4.0.22 / mmapv1 (oplog Enabled)
> 
> ### Client Setup Information
> * Desktop App or Browser Version: 3.0.3
> * Operating System: Mac OS
> 
> ### Additional context
> No additional context
> 
> ### Relevant logs:
> No relevant logs please try the json structure in the code

I have the same issue

**Comment by adolfombarros** [comment]
I tried even with the example in the documentation (https://docs.rocket.chat/api/rest-api/methods/chat/postmessage), but it also didn't work !!

{
  "alias": "Gruggy",
  "avatar": "http://res.guggy.com/logo_128.png",
  "channel": "#general",
  "emoji": ":smirk:",
  "roomId": "Xnb2kLD2Pnhdwe3RH",
  "text": "Sample message",
  "attachments": [
    {
      "audio_url": "http://www.w3schools.com/tags/horse.mp3",
      "author_icon": "https://avatars.githubusercontent.com/u/850391?v=3",
      "author_link": "https://rocket.chat/",
      "author_name": "Bradley Hilton",
      "collapsed": false,
      "color": "#ff0000",
      "fields": [
        {
          "short": true,
          "title": "Test",
          "value": "Testing out something or other"
        },
        {
          "short": true,
          "title": "Another Test",
          "value": "[Link](https://google.com/) something and this and that."
        }
      ],
      "image_url": "http://res.guggy.com/logo_128.png",
      "message_link": "https://google.com",
      "text": "Yay for gruggy!",
      "thumb_url": "http://res.guggy.com/logo_128.png",
      "title": "Attachment Example",
      "title_link": "https://youtube.com",
      "title_link_download": true,
      "ts": "2016-12-09T16:53:06.761Z",
      "video_url": "http://www.w3schools.com/tags/movie.mp4"
    }
  ]
}

**Comment by TimAnthonyAlexander** [comment]
any updates?

**Comment by TimAnthonyAlexander** [comment]
> I'm closing this issue, what happened here is the misuse of the `message_link` parameter, which should only be used with 'quotes'
> 
> Anything please, let me know

for me this also does not work with quotes. This should not be closed.
