### ISSUE TITLE
[BUG] URL OEmbeds are cut off

### ISSUE THREAD

**Issue by aditya-mitra** [RocketChat/Rocket.Chat#20628]
### Description:

The `og:description` in the URL embeds are cutoff and not fully shown.

### Steps to reproduce:

1. Send a link to any channel (or direct message)
Make sure the *description of the link is long*. Try `https://95nyn.csb.app/` or `https://github.com`.
2. You will find that the text is being wrapped and not fully shown

### Expected behavior:

The full text is shown.

### Actual behavior:

The text is being cutoff with ellipsis.

![earlier](https://user-images.githubusercontent.com/55396651/107110825-00dcde00-6871-11eb-866e-13cabc5b0d05.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox
- Operating System: Ubuntu

### Additional context

This is not related to issue #20556 because it is related to `DefaultAttachments` and not `OEmbeds`.

**Comment by ishansinghal9810** [comment]
If this issue is open I would love to help

**Comment by aditya-mitra** [comment]
Thank you @ishansinghal9810 very much for trying to solve this issue.
But, you see there is already a pull request attached to this issue which would close it once merged.
However, you can always look for another issue.

Happy Hacking!
