### ISSUE TITLE
Files without a file extenstion break the chat interface

### ISSUE THREAD

**Issue by AnianZ** [RocketChat/Rocket.Chat#20622]
### Description:

If I upload a (video) file without a file extension into a chat and then click on it rocketchat shows a 404 page and the chat to which the file was uploaded only works after an application restart or browser reload.

### Steps to reproduce:

1. Create a file without a file extension (e.g. `myvideo` instead of `myvideo.mp4`)
2. Upload the file to a chat
3. Click on the filename after the upload completes
4. On the 404 page click on any of the two buttons and navigate back to the chat you uploaded the file to

### Expected behavior:

Either files without file extensions work like normal files or at least the 404 page and the buttons there does not break the chat.

### Actual behavior:

File does not open, 404 page instead and blank chat window on return

![image](https://user-images.githubusercontent.com/20282950/107068819-5cf82180-67e1-11eb-91d6-82670853bda1.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.12

### Client Setup Information

- Desktop App or Browser Version: Firefox 85.0
- Operating System: Linux (Fedora 32)

### Relevant logs:

No log messages at the same time as the error

**Comment by yash-rajpal** [comment]
This issue is not due to missing extension. This is an issue with downloading attachments in version 3.11.0, also checkout issue #20583 #20559. Also checkout PR #20585 , it fixes this issue. :)

**Comment by AnianZ** [comment]
@yash-rajpal Ahh ok. Then I was just confused by the missing preview without the file extension and assumed that was what was causing the issue. I will wait for the fix in #20585 to get merged and then test my issue again.

**Comment by AnianZ** [comment]
Can confirm it's fixed with the new release. Thanks :)
