### ISSUE TITLE
@ - symbol is not suitable to select user to chat in other locales

### ISSUE THREAD

**Issue by lexnov** [RocketChat/Rocket.Chat#2062]
Add the ability to change the symbol (@-symbol) to select user to chat.   @ - symbol is not suitable in other locales (eg Russian). 
otherwise use another method to select user to chat (selecting his nickname on chat) and so.

**Comment by prohde** [comment]
I am not from the team but in my opinion the @ symbol is very common for this. Do other applications provide the ability to change this symbol? And what would you suggest e.g. for Russian?

**Comment by engelgabriel** [comment]
I'd be interested in the suggestion too. This is not a trivial change.

**Comment by lexnov** [comment]
I am not sure about other layouts, but in russian keyboard layout there is no "@" symbol. So username choice is not convenient, because one needs to change keyboard layout to Eng (by pressing SHFIT+ALT) then type "@" symbol, after that go back to russian layout (by pressing SHIFT+ALT again), and only then enter username. 
Google Plus for example uses "+" symbol, which is common for many keyboard layouts and it is more convinient.
**Google Plus:**
![google_like](https://cloud.githubusercontent.com/assets/16919406/12675377/e3a1e4f2-c69a-11e5-9a3b-06cbc33f498f.png)
**Rocket.Chat:**
![default](https://cloud.githubusercontent.com/assets/16919406/12675366/c50eb43e-c69a-11e5-9709-0d24e05c67ba.PNG)

**Comment by tuudik** [comment]
Off-topic: Are you telling that everytime when writing e-mail address to you have to change to english keyboard? :D

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
