### ISSUE TITLE
LDAP Users do not display full name

### ISSUE THREAD

**Issue by asmartin** [RocketChat/Rocket.Chat#2063]
The LDAP attribute I use that contains a user's first and last name is `displayName` (e.g `John Smith`). I have configured the User Data Field Map field on the LDAP configuration page to contain the following:
````
{"displayName:"name", "mail":"email"}
````

However, all users still show up as their LDAP username in the list of Direct Messages, in chats, and when typing @-mentions. How can I get users real names to show up in RocketChat?

**Comment by marceloschmidt** [comment]
Somewhat related to #1325

**Comment by marceloschmidt** [comment]
Duplicate of #324
