### ISSUE TITLE
Empty "Don't ask me again" list

### ISSUE THREAD

**Issue by dionatan1989** [RocketChat/Rocket.Chat#20638]
### Description:

I'm trying to configure "Don't ask me again list" on Account Preferences, but it's empty.

### Steps to reproduce:

1. Go to 'My Account'
2. Click on 'Preferences' > 'Global'
3. Try to select 'Don't ask me again list'

### Expected behavior:

Is expected a list of messages to be selected to not warn the user when some action is done. For example, "Hide a Room"

### Actual behavior:

![image](https://user-images.githubusercontent.com/11030322/107155716-b59dfa80-6958-11eb-8e9c-59bf123371a3.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Ubuntu 18
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.14 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 88.0.4324.146
- Operating System: Windows 10

**Comment by shubhamkmr04** [comment]
Can you assign this issue to me?

**Comment by ggazzo** [comment]
thanks for your report, I will close this one since https://github.com/RocketChat/Rocket.Chat/issues/19675 covers your problem. I hope have better news soon as possible ;)
