### ISSUE TITLE
Upload Lifetime

### ISSUE THREAD

**Issue by asmartin** [RocketChat/Rocket.Chat#2064]
How long are file uploads stored on the server? Can the uploader go in and delete them later? I could see this being a problem both for storage space on the server and also for scaling the list of uploaded files in a very active channel. Can we configure a lifetime for uploads, or at least let users delete them manually?

**Comment by marceloschmidt** [comment]
This will be covered by #2086. Currently, files are stored forever.

**Comment by klatys** [comment]
Automatic prune is defined in #1133 as well

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Manual deletion is possible, automatic pruning not (as of yet). So I'm closing this issue and refer to #1133 for the automatic pruning.

Cheers
Thomas
