### ISSUE TITLE
Unpinning the message freezes the server

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat#20642]
### Description:

When unpinning a pinned message in any channel from the list of pinned messages the server becomes unresponsive

### Steps to reproduce:

1. Pin message in any room or channel
2. Open a list of pinned messages
3. Press the "Unpin" button

### Expected behavior:

The message should be unpinned without any issues

### Actual behavior:

The system message "The message has been unpinned" appears. But the server becomes unresponsive

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Windows 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version:  v12.18.0
- MongoDB Version: 3.6.20

**Comment by neonardo1** [comment]
It doesn't impact the server for me, but it definitely freezes the client.  Hard refresh fixes it (or restarting client completely).

**Comment by im-adithya** [comment]
Hey @johnypeterson! I think you are referring to this issue #20503. Will be fixed by #20504!

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
