### ISSUE TITLE
No thread reply notification in the tab title

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#20646]
### Steps to reproduce:

1. Open https://open.rocket.chat/ in the browser
2. Open another tab
3. Receive a private message from someone or a mention in a channel --> in the first tab title red number 1 will appear
4. Receive a thread reply from someone or a mention in a thread reply --> no red number 1 appears

### Expected behavior:

Red number 1 appears in the tab title no matter if it is a mention in a thread reply (followed) or a channel/private message.

### Actual behavior:

No red sign in the tab name.
![image](https://user-images.githubusercontent.com/11751017/107221115-7f718100-6a13-11eb-9dca-6bf97b060f52.png)

P.S. Red number is correctly shown in the channel list left panel.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.7
- Operating System: Linux
- Deployment Method:  Snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Browser version
- Operating System: Linux

### Additional context

Red number is correctly shown in the channel list left panel in all cases. But not in the tab title.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
