### ISSUE TITLE
Google is a cake when the interface is RTL

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#2065]
This is not a new issue and it is simply caused by placing symbols at locations that has Bidi Mirroring property. See https://github.com/RocketChat/Rocket.Chat/issues/1577

In this case the g logo on google for the oauth login appears as a cake.

![rocket](https://cloud.githubusercontent.com/assets/432460/12668622/8a1f2cb0-c626-11e5-8de5-f5628b1c4312.png)

**Comment by marceloschmidt** [comment]
Hi @fduraibi could you provide a solution like you did for #1594 ? Thank you!

**Comment by fduraibi** [comment]
@marceloschmidt here is the PR https://github.com/RocketChat/Rocket.Chat/pull/2186
i was too busy and didn't have time to do it before :)
