### ISSUE TITLE
Administration page not showing

### ISSUE THREAD

**Issue by aclw** [RocketChat/Rocket.Chat#20668]
### Description:

I navigated to the administrative settings, and all the pages (e.g. info) do not show anything.

### Steps to reproduce:

1. Clone the latest code on github onto a clean docker container running Ubuntu 18.04.
2. Follow the instructions on https://docs.rocket.chat/guides/developer/quick-start to set up Rocket Chat.
3. Point my browser to the Rocket Chat server.
4. Go through the required setup steps.
5. Navigate to the admin page (e.g. http://localhost:3100/admin/General).
6. The page doesn't show anything.

### Expected behavior:

The admin pages should show the appropriate settings for that page.

### Actual behavior:

The pages appear ### blank.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu 18.04
- Deployment Method: Check out from github and build by myself (using snap actually works fine)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- Operating System: Ubuntu 16.04

**Comment by yash-rajpal** [comment]
This is not reproducible by, I can use admin panel as always.
![image](https://user-images.githubusercontent.com/58601732/107568040-78fa2980-6c0c-11eb-9f9c-4f2b742f1932.png)

**Comment by aclw** [comment]
I have debugged deeper into this issue. What I found is that when the Scrollbars is displayed, it's supplied with a style of {width: "100%", height: "100%", flexGrow: 1, willChange: "transform", overflowY: "hidden"}. I have problem with the height: "100%" part. If I change that to height: 600 manually, then that works fine.

I also switched to use FireFox, and the problem went away as well. So it seems that this has something to do with Chrome together with Scrollbars being set to 100% height.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
