### ISSUE TITLE
duplicated js file download

### ISSUE THREAD

**Issue by flourishing** [RocketChat/Rocket.Chat#2066]
since i access the website feel a little slow  .  so i use chrome page speed to test it and see what is the reason;
page speed report , download  1.8M file 4 times , and so first page load will load 7.3M js.  this caused the slow access.
how to solved this ?
![2016-01-29 3 57 25](https://cloud.githubusercontent.com/assets/5078097/12670244/a22cfe38-c6a1-11e5-9dce-36de6bfc6c06.png)

**Comment by marceloschmidt** [comment]
Can you run those tests again, but on https://demo.rocket.chat and see if you still experience multiple files download? This could be happening for many reasons. It would help us identify if we can run this on a controlled instance. Thanks.

**Comment by geekgonecrazy** [comment]
Closing this should no longer be an issue.
