### ISSUE TITLE
add chat button bside the name of the member

### ISSUE THREAD

**Issue by mhndm** [RocketChat/Rocket.Chat#2067]
in the administration -> admin/users list
I cant find chat button to start chat with this member 
can you add new column chat like this :
Name | Username | E-mail | chat

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
