### ISSUE TITLE
Rocket.Chat not respecting CDN Domain for Downloads option

### ISSUE THREAD

**Issue by td512** [RocketChat/Rocket.Chat#20674]
### Description:

CDN Domain for Downloads is not respected if Force Path Style is turned on. 

### Steps to reproduce:

1. Go to Administration
2. Click on File Upload
3. Set type to S3
4. Fill everything out as you would expect
5. Turn on Force Path Style
6. Fill out CDN Domain for Downloads

### Expected behavior:

We run a split MinIO setup, where `s3.example.com` is not behind a CDN due to CloudFront not passing on headers that we need, but `*.s3.example.com` is. We're expecting Rocket.Chat to respect the CDN Domain for Downloads option when Force Path Style is set.

### Actual behavior:

Rocket.Chat does not respect the CDN domain and uses the URL not behind the CDN.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian Buster
- Deployment Method: OpenShift
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Firefox 85.0.1
- Operating System: macOS Catalina (10.15.7)

**Comment by rcsilvadev** [comment]
Same behavior on 3.11.1.

I noticed that the CDN const is commented out on /app/file-upload/server/config/AmazonS3.js:74
`// const CDN = RocketChat.settings.get('FileUpload_S3_CDN');`

**Comment by hibobmaster** [comment]
Still not work in version: 3.18.3
