### ISSUE TITLE
Broken retention policy warning shown in all rooms

### ISSUE THREAD

**Issue by audouts** [RocketChat/Rocket.Chat#20685]
### Description:

Retention policy warning appears in all channels, even though no policy is defined for that channel. The warning is also malformed, only showing "30" - not "30 days" etc.

### Steps to reproduce:

1. Enable retention policy
2. Make sure the three "applies to" settings are disabled
3. Apply
4. Check room info for a channel

### Expected behavior:

Room info does not show a warning.

### Actual behavior:

All rooms show a warning:

![image](https://user-images.githubusercontent.com/76459197/107617621-16e9f600-6c05-11eb-87fa-5c54daede351.png)

The warning shows an unspecified "30" value (no indication of days, etc.).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 12.20.2
- MongoDB Version: 4.2.12

**Comment by audouts** [comment]
@yash-rajpal 

Thanks for your help!

Is it possible for me to apply this fix? Or is there an ETA on it making into an official version?

**Comment by yash-rajpal** [comment]
@audouts if you want this fix asap you can make these changes yourself. But I don't know how to bundle the release after that maybe you can find info on this in the docs.

This fix will make into an official release if this pr gets merged, you can ask the Rocket chat team to review this pr.

Sorry man, I don't know what else can be done.

**Comment by audouts** [comment]
@yash-rajpal I notice that there is a check error for a missing comma:

```
Check failure on line 71 in client/views/room/contextualBar/Info/RoomInfo/RoomInfo.js
GitHub Actions / build

client/views/room/contextualBar/Info/RoomInfo/RoomInfo.js#L71

Missing trailing comma
```

Can you fix that?
