### ISSUE TITLE
Hotchillee - “Follow” button in thread overwrites “+” add icon

### ISSUE THREAD

**Issue by tom-gouldson** [RocketChat/Rocket.Chat#20697]
Context
Hotchillee is looking to move its Digital cycling club communications from Slack to a Rocketchat based app. In doing so it hopes to maintain the user experience as much as possible so as not to confuse its user base while using Rocketchats white labelling capability to give it Hotchillee brand and feel. As part of this Hotchillee looks to retain all the historic chat from Slack to make it as seamless as possible for users transferring to the new platform (similar to when Facebook does a major UX overhaul - all the data remains but the look and feel is different and new features are added but it’s still familiar enough not to alienate users).

### Description:

In desktop browser (also seen on desktop app), when you are first person to add to a thread, the “follow” button overwrites the “+” so you cannot add an image/file/audio/location

### Steps to reproduce:

1. Go to https://community.hotchillee.cc/channel/general_chat
2. Click on 'Thread' anywhere
3. Should only be able to see Follow button and not +
4. Send a message
5. Click on the same thread
6. Should be able to see the + sign and follow

### Expected behavior:

Should be able to see the + sign and follow

### Actual behavior:

Follow covers the + sign on the first thread message. Then only the + sign can be seen. (see screenshots)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: 
- Deployment Method: Docker on Kubernettes via Helm
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.12
- Apps Engine Version. 1.22.1

### Client Setup Information

- Desktop App or Browser Version: Chrome, Safari - latest versions
- Operating System: Mac OS

### Additional context

Not applicable though could be related to bug 20695 as that also has a first message in thread issue.

### Relevant logs:

Not applicable
<img width="907" alt="Screenshot 2021-02-11 at 11 41 30" src="https://user-images.githubusercontent.com/78903354/107632238-23e70380-6c5e-11eb-9c9a-6c0257b86a2e.png">
<img width="916" alt="Screenshot 2021-02-11 at 11 41 43" src="https://user-images.githubusercontent.com/78903354/107632260-29444e00-6c5e-11eb-9a0c-9f77d4f8d823.png">

**Comment by Darshilp326** [comment]
@dougfabris @ggazzo  Should we remove that follow button from the message box? Your thoughts?

**Comment by sven-thiele** [comment]
@Darshilp326 @dougfabris @ggazzo - i think makes sense to remove button - as the "follow message" function is already an option for the message.

**Comment by dougfabris** [comment]
> @dougfabris @ggazzo Should we remove that follow button from the message box? Your thoughts?

@Darshilp326 I had a discussion with our design team and we agreed that we can remove the follow button in this case. Are you able to help us with that?

**Comment by Darshilp326** [comment]
> > @dougfabris @ggazzo Should we remove that follow button from the message box? Your thoughts?
> 
> @Darshilp326 I had a discussion with our design team and we agreed that we can remove the follow button in this case. Are you able to help us with that?

Yes working on it! :+1:
