### ISSUE TITLE
Hotchillee - 'Also send to channel' Default On issue.

### ISSUE THREAD

**Issue by tom-gouldson** [RocketChat/Rocket.Chat#20695]
Context
Hotchillee is looking to move its Digital cycling club communications from Slack to a Rocketchat based app. In doing so it hopes to maintain the user experience as much as possible so as not to confuse its user base while using Rocketchats white labelling capability to give it Hotchillee brand and feel. As part of this Hotchillee looks to retain all the historic chat from Slack to make it as seamless as possible for users transferring to the new platform (similar to when Facebook does a major UX overhaul - all the data remains but the look and feel is different and new features are added but it’s still familiar enough not to alienate users).

### Description:

When writing in threads there is a checkbox for ‘Also send to channel’. As admins we have selected to have this unchecked by default. In the app this works as expected but on desktop, when writing the first message in a thread this is checked by default. When someone goes up to write the second or subsequent message in those threads it is turned off as expected. It is just in the browser that this issue occurs.

### Steps to reproduce:

1. Visit our clean test instance https://community.hotchillee.cc/channel/general_chat and click on any thread “reply” button to see for yourselves
2. Write a reply
3. Click on the same thread again to reply
4. See the checkbox has now defaulted to off

### Expected behavior:

The 'Also send to Channel' checkbox should be defaulted to Off at all times

### Actual behavior:

The 'Also send to Channel' button is defaulted to 'On' for the first thread reply (see video).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: 
- Deployment Method: Docker on Kubernetes via Helm
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.12
- App builder version: 1.22.1

### Client Setup Information

- Desktop App or Browser Version: Chrome and Safari - Latest versions
- Operating System: Mac OS

### Additional context

Not applicable

### Relevant logs:

Not applicable.

https://user-images.githubusercontent.com/78903354/107631382-c8684600-6c5c-11eb-8719-ef52591f693a.mov

**Comment by Exordian** [comment]
btw we patched that using custom scripts for logged in users
```

Template.thread.onCreated(() => {
const instance = Template.instance();
instance.state.set('sendToChannel', false);
});```

**Comment by Kyogre** [comment]
FYI final script would be without ``` at the end:
```
Template.thread.onCreated(() => {
const instance = Template.instance();
instance.state.set('sendToChannel', false);
});
```

**Comment by SufiSR** [comment]
Thank you, this was very helpful. I was using a similar approach with setting up a MutationObserver and then setting the value of the checkbox to false. However, with the most recent update the implementation was changed and it would not work properly anymore (one would have to put a javascript .click() to trigger the unchecking event.

However, your solution is a lot shorter and cleaner. Again - much appreciated!

**Comment by maluhub** [comment]
In our scenario it stopped working since 6.x.x. I reported it here:
https://github.com/RocketChat/Rocket.Chat/issues/29621
Please support.
