### ISSUE TITLE
"/api/v1/users.register" Not Reponding

### ISSUE THREAD

**Issue by omidnasiri** [RocketChat/Rocket.Chat#20702]
### Description:

Requesting to endpoint: "/api/v1/users.register" is not responding on my self-hosted Rocket.Chat server running on docker.
The rest of the APIs seem to be fine and only this one is not sending back 200 OK HTTPS response and I face the request timed out.

Although the requested JSON data has been sent to the server and the requested user has been registered cause if I try to send the same request again I get the 400 Bad Request with the error: "Username is already in use".

### Steps to reproduce:

curl -H "Content-type:application/json" \
     http://localhost:3000/api/v1/users.register \
     -d '{ "username": "rogersmith", "email": "roger@example.com", "pass": "passw0rd", "name": "Roger Smith"}'

### Expected behavior:

HTTP status code: 200 Ok
JSON result:
{
  "user": {
    "_id": "nSYqWzZ4GsKTX4dyK",
    "type": "user",
    "status": "offline",
    "active": true,
    "name": "Example User",
    "utcOffset": 0,
    "username": "example"
  },
  "success": true
}

### Actual behavior:

Literally nothing!

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Ubuntu Linux 18.04.2
- Deployment Method: docker-compose
- MongoDB Version: 4.0.0

**Comment by KevLehman** [comment]
Hey! Thanks for reporting this.
I tried the same payload you were trying and worked without any issues (in version 3.11 and 3.12)

Do you have more context (logs, data, screenshots, etc) so I can dig deeper in the issue? Thanks!

**Comment by mikechesterwang** [comment]
I got the same issue on my server. The version of Rocket Chat server is 3.16.2

**Comment by mikechesterwang** [comment]
Hi! I got the same issue on my server. When I registered account via REST API and through direct registration on the website, the server gave no response. But the account is successfully registered.

The version of Rocket Chat server is 3.16.2.

Here is the error log:
```
Exception in defer callback: Error: Connection timeout
    at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:235:22)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```
