### ISSUE TITLE
Channel name is "undefined" in RoomInfo

### ISSUE THREAD

**Issue by yash-rajpal** [RocketChat/Rocket.Chat#20700]
### Description:
Channel name shown as undefined in roomInfo and modals.

### Steps to reproduce:

1.  Goto any channel
2.  Click on Room info
3. Channel name is not shown and when modals appear on hide and leave contains room name as undefined.

### Expected behavior:
Room name should be visible.

### Actual behavior:
Room name not visible or is undefined.

![image](https://user-images.githubusercontent.com/58601732/107635137-a983a700-6c90-11eb-8d67-9feeb75528e9.png)

![image](https://user-images.githubusercontent.com/58601732/107635154-b1dbe200-6c90-11eb-8fce-07a39b4383fe.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0 - develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome browser
- Operating System: ubuntu

**Comment by aKn1ghtOut** [comment]
Fixed in #20459, I believe

**Comment by yash-rajpal** [comment]
@aKn1ghtOut I am sorry, didn't saw that.
Thanks :)
