### ISSUE TITLE
Upload date is cropped

### ISSUE THREAD

**Issue by leitmori** [RocketChat/Rocket.Chat#20703]
### Description:

Upload date in "Files" tab is cropped

### Steps to reproduce:

1. Open a channel
2. Click on "Files"

### Expected behavior:

Upload date is not cropped

### Actual behavior:

Upload date is cropped (e.g. "Mav" instead of "May")
<img width="480" alt="Screen Shot 2021-02-11 at 13 25 07" src="https://user-images.githubusercontent.com/29522608/107637821-01a9b180-6c6f-11eb-85ae-8bd88b99bdc4.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App Version: 3.1.1
- Operating System: macOS Big Sur

**Comment by yash-rajpal** [comment]
#20454 fixes this. :)
