### ISSUE TITLE
Replace GCM with MQTT?

### ISSUE THREAD

**Issue by jdbaldry** [RocketChat/Rocket.Chat#2071]
Rocket.Chat is great but sends all push notifications through proprietary services like GCM for Android devices.

Would it be possible to replace this functionality any of the following?
- [MQTT](http://stackoverflow.com/questions/21336808/is-it-possible-to-use-gcm-without-google-account-and-google-play-services-on-the)
- [parse-server](https://github.com/ParsePlatform/parse-server)
- [Comparison of Kinto with alternatives](http://kinto.readthedocs.org/en/latest/overview.html#comparison-with-other-solutions)

**Comment by engelgabriel** [comment]
On Parse Server for PUSH:

> Not supported
> Push - We did not rebuild a new push delivery system for parse-server, but we are open to working on one together with the community.

https://github.com/ParsePlatform/parse-server?ts=2#not-supported

**Comment by prohde** [comment]
+1

@engelgabriel: Maybe MQTT?

**Comment by benmaynard11** [comment]
+1

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by sampaiodiego** [comment]
pushy.me runs a push service over MQTT.. we could do the same.

**Comment by marceloschmidt** [comment]
Future architecture has encryption and potentially MQTT support.

**Comment by MarPiRK** [comment]
@marceloschmidt could you elaborate what is the future architecture and where can I track its development (ie. issue, or sth)?
