### ISSUE TITLE
Characters are parsed to HTMLEntityCodes in System Messages

### ISSUE THREAD

**Issue by aditya-mitra** [RocketChat/Rocket.Chat#20716]
### Description:

Certain Characters are displayed as HTMLEntityCodes like `&lt;` or `&gt;` in the room chat as soon as the topic is changed to text which contains specific special characters.

This happens when we change any of Topic or Announcement or Description of the Room.

### Steps to reproduce:

1. Go to Edit Room Settings

2. Type something in the description like *schrondinger's cat*.

3. Click the Save Button.

4. Check that there is message in the Room Chat which says *Room topic changed to: schrodinger&#39;s cat by *

### Expected behavior:

To display the exact Description/Topic/Announcement as entered in the settings.

### Actual behavior:

Displays the HTMLEntitiyCode

![earlier](https://user-images.githubusercontent.com/55396651/107646305-d4292c00-6c9f-11eb-9390-1385b6d2d794.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop

- Operating System: Ubuntu (Linux)

- Deployment Method: 

- Number of Running Instances: 1

- DB Replicaset Oplog: enabled

- NodeJS Version: v12.18.4

- MongoDB Version: 4.2.8 (WiredTiger)

### Client Setup Information

- Desktop App or Browser Version: any

- Operating System: any

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
