### ISSUE TITLE
Reactions (inline) are behaving weird

### ISSUE THREAD

**Issue by mluex** [RocketChat/Rocket.Chat#20734]
### Description:

Reactions to a message that are submitted via inline form (directly below the message) are no longer saved. It does not matter whether you add a new emoji or click on an existing emoji to increase the counter or try to remove your own reaction to decrease the counter. Sometime the change is just displayed briefly and then disappears again or, in the case of already existing emojis, the counter is reset. Sometimes it's working, sometimes it's not or it's only possible to add emojis but not remove them.
![inline](https://user-images.githubusercontent.com/20678805/107770322-806b2100-6d39-11eb-943e-6aae85fdd5b4.gif)

Only reactions that are added on the right via the context menu (which is displayed by hovering) work correctly.
![context](https://user-images.githubusercontent.com/20678805/107770392-9b3d9580-6d39-11eb-998f-28595bfd6c25.gif)

The problem has been occurring since yesterday. The last update was also yesterday. I therefore suspect it has something to do with the latest release.

### Steps to reproduce:

Check out the gif above.
Add new reactions, remove existing ones via the inline reactions function below a message.

### Expected behavior:

The deselected reactions should be permanently removed or the counter should decrease. New reactions should be permanently visible or the counter should increase.

### Actual behavior:

The expected result occurs for 1-2 seconds. After that, the change made is reverted. See Gif.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

Occurs with several users with different setups. Tested on: Mac OS Big Sur with Chrome 88, Windows 10 Pro with Chrome and in Rambox in the current version.

### Relevant logs:

No errors are visible in the log, nor in the browser console.

**Comment by aditya-mitra** [comment]
I had 2 questions which would be helpful if you could help me with them :
- Are you setting/unsetting the **reactions very fast** (like within a second or two)? 
- If you refresh the page, are you seeing the **reverted changes** or **the changes you made**?

**Comment by mluex** [comment]
Nope, it doesn't matter how fast or slow I click it. Changes will be reverted anyway. 

After page reload I see the reverted changes, not the expected result.

**Comment by aKn1ghtOut** [comment]
#20159 fixed this. Check with current develop

**Comment by Darshilp326** [comment]
@aKn1ghtOut Not fixed!

**Comment by aKn1ghtOut** [comment]
Can't recreate the bug on latest develop :/

**Comment by aKn1ghtOut** [comment]
The PR was also included in the 3.11 release. You can check with that too

**Comment by Darshilp326** [comment]
https://user-images.githubusercontent.com/55157259/107815158-feaae000-6d98-11eb-9283-4883c66ce6f5.mp4

@mluex Are you facing this issue?

**Comment by aKn1ghtOut** [comment]
>  Untitled_.Feb.13.2021.1_13.AM.mp4 
> @mluex Are you facing this issue?

Apologies. Can confirm this issue
