### ISSUE TITLE
[Enhancement] Better presentation of blockquotes

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#20748]
### Description:
Currently when `<blockquote>` is invoked from markdown (and also when quoting a message?) the formatting becomes messy when there is a lot of text.

### Steps to reproduce:

1. Post a message with multiple lines and also using blockquotes

### Expected behavior:
Display could be prettier and more easy to read.

### Desirable example:
![example_after](https://user-images.githubusercontent.com/1122344/107846830-04590200-6e3b-11eb-89c4-6bb92ebff12e.png)

### Actual behavior:
The line break after the blockquote is too close to the blockquote/could be improved:

![example_before](https://user-images.githubusercontent.com/1122344/107846963-15eed980-6e3c-11eb-9265-9c36b2f605be.png)

![editing](https://user-images.githubusercontent.com/1122344/107846947-f952a180-6e3b-11eb-94bc-66bdc8549653.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Firefox 85.0.2
- Operating System: Windows 10

**Comment by aditya-mitra** [comment]
@nooblag Thanks for pointing out this improvement!

I have made the above pull request where I have increased the spacing. 
Can you please confirm if it looks fine? Or should I *decrease/increase* it?

**Comment by nooblag** [comment]
Hi @aditya-mitra Thanks for your fast reply. I checked your pull request and maybe it's a misunderstanding? Cos I'm talking about the margins at the *top* and *bottom* of the `<blockquote>`s:

![example_after](https://user-images.githubusercontent.com/1122344/107854750-2d48b980-6e72-11eb-949a-87095083206a.png)


I don't know much about the CSS, but this fixes the space at the _start_ of the blockquotes, but we still have a problem with the bottoms:

```
.rc-old blockquote:first-child {
    margin-top: 15px;
}
```

I don't know how to fix the problem with the `<br>`s not being properly handled though (the sentence starting with "_... and then olores..._" Perhaps `<blockquote>`s need to be wrapped in a `<div>` and then apply `margin-top` and `margin-bottom` to that?

**Comment by aditya-mitra** [comment]
@nooblag I will certainly fix the margin issue. But I am unclear with what you meant by `<br>`😅. Can you please it help me with that?

**Comment by Devansh-Trivedi** [comment]
I think I can fix these issue, can u pls guide me how can i switch between different version of Rocket.Chat server.

**Comment by Devansh-Trivedi** [comment]
> @nooblag I will certainly fix the margin issue. But I am unclear with what you meant by `<br>` sweat_smile. Can you please help me with that?

Removing `<br>` tag (break line) should fix the issue ig.

**Comment by nooblag** [comment]
> @nooblag I will certainly fix the margin issue. But I am unclear with what you meant by `<br>` 😅. Can you please help me with that?

Apologies about the confusion.

The `<br>`s I'm talking about is this one:

![br1](https://user-images.githubusercontent.com/1122344/107880685-9db80f00-6f34-11eb-9130-5c0f5e4b9910.PNG)

I can see there are two actually, with the text posted at the start of this thread. Both are "ignored" (i.e. no whitespace rendered):

![br2](https://user-images.githubusercontent.com/1122344/107880686-a01a6900-6f34-11eb-8cac-140881dc0521.PNG)

Again, this is what I wish it would look like:

![br2](https://user-images.githubusercontent.com/1122344/107880752-fc7d8880-6f34-11eb-8fb4-5e3911d6b858.PNG)

This is the dummy text and formatting of my test message, if that's any help?

```
Testing post. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Ea est ut tempore deserunt itaque ipsum vitae est. Sint qui odit dolore. Voluptatibus quo aut error consequuntur sit quae exercitationem eos. Vel velit neque voluptas eos sunt ut suscipit et. Quia veniam ut beatae debitis nesciunt. Ad veritatis quam aliquid.

>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Ut iure voluptatem sit illo exercitationem. Nisi laboriosam consequatur sequi expedita natus. Qui consequatur doloremque alias fuga sunt. Quia molestiae in consequatur aut deleniti ratione omnis nam. Maxime dolores enim inventore dicta nihil. Error voluptas itaque qui.
>Placeat aut laudantium autem omnis libero non aspernatur. Hic fuga necessitatibus voluptas praesentium. Facere consequatur repudiandae enim autem deserunt.

... and then olores ullam minima facere animi quas. Eos dolorem omnis veniam omnis maxime.

Placeat aut laudantium autem omnis libero non aspernatur. Hic fuga necessitatibus voluptas praesentium. Facere consequatur repudiandae enim autem deserunt.
```

**Comment by aditya-mitra** [comment]
> > @nooblag I will certainly fix the margin issue. But I am unclear with what you meant by `<br>` sweat_smile. Can you please help me with that?
> 
> Apologies about the confusion.
> 
> The `<br>`s I'm talking about is this one:
> 
> ![br1](https://user-images.githubusercontent.com/1122344/107880685-9db80f00-6f34-11eb-9130-5c0f5e4b9910.PNG)
> 
> I can see there are two actually, with the text posted at the start of this thread. Both are "ignored" (i.e. no whitespace rendered):
> 
> ![br2](https://user-images.githubusercontent.com/1122344/107880686-a01a6900-6f34-11eb-8cac-140881dc0521.PNG)
> 
> Again, this is what I wish it would look like:
> 
> ![br2](https://user-images.githubusercontent.com/1122344/107880752-fc7d8880-6f34-11eb-8fb4-5e3911d6b858.PNG)
> 
> This is the dummy text and formatting of my test message, if that's any help?
> 
> ```
> Testing post. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Ea est ut tempore deserunt itaque ipsum vitae est. Sint qui odit dolore. Voluptatibus quo aut error consequuntur sit quae exercitationem eos. Vel velit neque voluptas eos sunt ut suscipit et. Quia veniam ut beatae debitis nesciunt. Ad veritatis quam aliquid.
> 
> >Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Ut iure voluptatem sit illo exercitationem. Nisi laboriosam consequatur sequi expedita natus. Qui consequatur doloremque alias fuga sunt. Quia molestiae in consequatur aut deleniti ratione omnis nam. Maxime dolores enim inventore dicta nihil. Error voluptas itaque qui.
> >Placeat aut laudantium autem omnis libero non aspernatur. Hic fuga necessitatibus voluptas praesentium. Facere consequatur repudiandae enim autem deserunt.
> 
> ... and then olores ullam minima facere animi quas. Eos dolorem omnis veniam omnis maxime.
> 
> Placeat aut laudantium autem omnis libero non aspernatur. Hic fuga necessitatibus voluptas praesentium. Facere consequatur repudiandae enim autem deserunt.
> ```

Thank you for clear that out!

I guess #20750 should be able to fix this issue.

Here is how it looks.
![image](https://user-images.githubusercontent.com/55396651/107881913-8533fe80-6f0c-11eb-9205-818496c897ab.png)

**Comment by nooblag** [comment]
This is great. Thank you!!!

**Comment by nooblag** [comment]
Regression of these changes in 3.14.x
