### ISSUE TITLE
Missing "download" property in <a href /> tag for user uploaded files results in 404 error

### ISSUE THREAD

**Issue by bratelefant** [RocketChat/Rocket.Chat#20749]
### Description:

If a user uploads a file (storage system: S3) in a channel or direct message, a click on the posted file-name link leads to a 404 error using a web browser or electron apps. If you edit the DOM and add a "download"-propery to the corresponding <a href...> tag, the problem is resolved. Also, using the download icon is working normally (has also a "download" property).

### Steps to reproduce:

1. Upload a file, eg. pdf (not an image), using s3 for user uploads, in a conversation
2. click on the text-link to the file in a browser

### Expected behavior:

Download the file, just like when you click on the download icon

### Actual behavior:

404 error

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 6
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Safari 14.0.2, Chrome 88.0.4324.150, Firefox 85.0.2
- Operating System: macOS Big Sur

### Additional context
``<a href="/file-upload/KSf9mzpvEjZ2JJNN8/test-file.pdf" class="rcx-box rcx-box--full rcx-css-1rdemzp">test-file.pdf</a>`` is giving 404

``<a href="/file-upload/KSf9mzpvEjZ2JJNN8/test-file.pdf" download="test-file.pdf" class="rcx-box rcx-box--full rcx-css-1rdemzp">test-file.pdf</a>`` is working

### Relevant logs:

n/a

**Comment by bratelefant** [comment]
Fixed with 3.11.1

**Comment by g-giordano** [comment]
Hi, I have the same problem with 3.11.1 , deployment Method: docker
Can yuo help me?
Tks

**Comment by bratelefant** [comment]
Update to 3.11.1 solved the issue for me.
