### ISSUE TITLE
Domain Restriction doesn't seem to work with Google auth

### ISSUE THREAD

**Issue by wpnzach** [RocketChat/Rocket.Chat#2074]
Allows any Google user to create an account regardless of domain restriction settings.

**Comment by marceloschmidt** [comment]
Should `Allowed Domains List` be taken into consideration when registering with an OAuth Application? @RocketChat/core ?

**Comment by engelgabriel** [comment]
Most definitely.

**Comment by marceloschmidt** [comment]
Ok, so I debugged this and found out that you have to restart your server after you change the domain whitelist setting. Please check if that will solve this issue.

**Comment by engelgabriel** [comment]
@marceloschmidt can we make it update without restart?

**Comment by marceloschmidt** [comment]
I think we can! We need server side reactivity on RocketChat.settings though... any thoughts on wether we should use the observes, or maybe that package from mitar? We'd need to update this code
```
accountsConfig = { forbidClientAccountCreation: true, loginExpirationInDays: RocketChat.settings.get 'Accounts_LoginExpiration' }

if RocketChat.settings.get('Accounts_AllowedDomainsList')
	domainWhiteList = _.map RocketChat.settings.get('Accounts_AllowedDomainsList').split(','), (domain) -> domain.trim()
	accountsConfig.restrictCreationByEmailDomain = (email) ->
		ret = false
		for domain in domainWhiteList
			if email.match(domain + '$')
				ret = true
				break;

		return ret

Accounts.config accountsConfig
```

**Comment by marceloschmidt** [comment]
I think using observes is the easiest right now (we already use for LDAP, for example):
```
RocketChat.models.Settings.find().observe
	added: (record) ->
		if /^LDAP_.+/.test record._id
			updateServices()

	changed: (record) ->
		if /^LDAP_.+/.test record._id
			updateServices()

	removed: (record) ->
		if /^LDAP_.+/.test record._id
			updateServices()
```

**Comment by engelgabriel** [comment]
No, you should use the callback API for that. We want to remove ALL observers.

**Comment by marceloschmidt** [comment]
Mmm, ok, let me check on that.

**Comment by marceloschmidt** [comment]
We can't run it again without restarting the server, as meteor disallows it:
https://github.com/meteor/meteor/blob/devel/packages%2Faccounts-base%2Faccounts_common.js#L134

**Comment by rodrigok** [comment]
@marceloschmidt you can clear the object `Accounts._options`

**Comment by rodrigok** [comment]
@marceloschmidt about the settings reactivity you can use the settings onload

```coffeescript
	RocketChat.settings.onload 'Force_SSL', (key, value) ->
		Meteor.absoluteUrl.defaultOptions.secure = value
```

**Comment by marceloschmidt** [comment]
Yes, I'll try to do that now. Thanks

**Comment by marceloschmidt** [comment]
Done via https://github.com/RocketChat/Rocket.Chat/commit/286058e78d63f84be34046fe23ad6441aea8a3bd
