### ISSUE TITLE
!sending 7zip archives does not work

### ISSUE THREAD

**Issue by Noidart** [RocketChat/Rocket.Chat#20746]
### Description:

it is impossible to send a 7zip archive to another interlocutor using the chat window

### Steps to reproduce:

1.transfer the 7zip archive to the program window (or browser) to send this archive to the interlocutor
2.get error

### Expected behavior:

I look forward to fixing this bug, so that at last there is the most efficient use of the client in our enterprise

### Actual behavior:

The archive cannot be sent because a sending error appears

### Server Setup Information:

Version of Rocket.Chat Server: 3.9.1
Operating System: CentOS Linux release 8.3.2011
Deployment Method: nknown
Number of Running Instances: 1
DB Replicaset Oplog: nknown
NodeJS Version: v12.18.4
MongoDB Version: 4.2.11-1

### Client Setup Information

Desktop App or Browser Version:the problem is in both the desktop application and the browser version (Google Chrome ver. 88.0.4324.150; Firefox Browser ver.85.0.2).
desktop application version 3.1.1
Operating System:Windows 10 Pro (ver. 1803, Build 17134.1304 ; ver. 20H2, Build 19042.804)
![image001](https://user-images.githubusercontent.com/78079902/107843861-5cb6e200-6df0-11eb-906c-7c99f81345b0.png)

**Comment by KevLehman** [comment]
Good morning! There's an administrative configuration that controls the media types that can be uploaded. You can find it by looking at `Administration -> FileUpload_MediaTypeBlackList`. If the media type is there (in this case `application/x-7z-compressed` try removing it and saving changes.

![image](https://user-images.githubusercontent.com/11577696/107972545-9d8e3280-6f79-11eb-8236-f042c2fff4cb.png)

**Comment by Noidart** [comment]
Thank! The problem was solved with this instruction.
