### ISSUE TITLE
Users page blank

### ISSUE THREAD

**Issue by j-stahl** [RocketChat/Rocket.Chat#20758]
### Description:

The users page in adminstration is completely blank.
- no heading "Users".
- no searchbar.
- no "+new" button. No invite button.
- no users table is shown.

### Steps to reproduce:

1. Click on Administration
2. Users

### Expected behavior:

I expect to see the users for managing them.

### Actual behavior:

There is no user shown. Not even the default user admin. No buttons or other control elements are shown (in the submenu).
The control panel on the left side is still visible. It is possible to open and configure all the other settings. For example: "Info"
This behaviour is not new. We hoped it will be fixed in any further version. But we still hang on it since Rocket.Chat 2.x, so I decided to report it.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 16.4 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: oplog active
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.9

### Client Setup Information

- Desktop App or Browser Version: Desktop App + Browser FireFox 85.0, Google Chrome 
- Operating System: MacOS + Windows

### Additional context

Users are synchronised by an external LDAP server.
LDAP user synchronisation works. New users can be added by our LDAP server and they synchronize correctly. They can be found by the user search function (outside administration). Login and usage for those new users is possible.

### Relevant logs:

The logs do not output any relevant information. Standard logs + LDAP logs don't show new lines on opening the administration users panel.

**Comment by yash-rajpal** [comment]
I am not able to reproduce this on latest develop branch.

But I haven't tried with a LDAP server.

**Comment by j-stahl** [comment]
I am also not able to reproduce this on a different rocket.chat instance, which is not running with LDAP. So this error might be in any relation to the LDAP authentication.

**Comment by j-stahl** [comment]
I did not try out 3.12.0. But in version 3.14.0 it is already fixed. Users are visible again. Good work. Thank you.
