### ISSUE TITLE
Depreciation of attachment.actions

### ISSUE THREAD

**Issue by Karting06** [RocketChat/Rocket.Chat#20751]
### Description:
I noticed that `attachment.actions is deprecated` while reading the [KNOWN_ISSUES.md](https://github.com/RocketChat/Rocket.Chat/blob/develop/KNOWN_ISSUES.md#attachmentactions-is-deprecated) file. 
I just started to use those action buttons for automatically sending a chat message when clicking on the button (`sendMessage` method). 
I can imagine that some of those actions could open security holes. However, I don't really see how the `sendMessage` method could?

### Steps to reproduce:
N/A

### Expected behavior:

Being able to continue to use `attachment.actions` with the `sendMessage` method in the future.

### Actual behavior:
Deprecated

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian 10
- Deployment Method:  tar (custom build)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.9

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Additional context
N/A

### Relevant logs:
N/A

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
