### ISSUE TITLE
iframe integration externalCommand 'go' no longer works

### ISSUE THREAD

**Issue by hnategh** [RocketChat/Rocket.Chat#20759]
### Description:
I have a rocketchat instance, the base path is mydomain.com/rocketchat. I have an iframe integration to the instance using iframe postMessage externalCommand 'go' which it supposed to open up admin panel, but instead it ends up with a none existing path.
 

### Steps to reproduce:

1. Try iframe integration to an instance where the base path is not the docroot. e.g.: mydomain.com/rocketchat
2. try sending following 'go' externalCommand to the instance via postMessage. e.g.:  document.querySelector('iframe').contentWindow.postMessage({
  externalCommand: 'go',
  path: '/admin/info'
}, '*');
this will end up to mydomain.com/rocketchat/rocketchat/admin/info which is obviously wrong.

### Expected behavior:
It should resolve base path correctly and route to the requested path.

### Actual behavior:
Adds an extra base path into route the actual path.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 20.04
- Deployment Method:  docker
- Number of Running Instances: multiple
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information
iframe integration.
- Desktop App or Browser Version:
- Operating System:

**Comment by guijun13** [comment]
It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. Thank you very much!
