### ISSUE TITLE
Emoji in a field does not render

### ISSUE THREAD

**Issue by shollander** [RocketChat/Rocket.Chat#20766]
### Description:

Emojis used in a `field` (when using the API) do not render. Other types of markdown do seem to be working.

### Steps to reproduce:

POST https://foo.rocket.chat/api/v1/chat.postMessage
```
{
 "channel": "@username",
  "text": "Example message",
  "attachments": [
    {
      "title": "Message title",
      "text": ":smile: This works",
      "color": "#efcc96",
            "fields": [{
              "short": false,
              "title": ":frown: This does **not** work",
              "value": ":frown: This too"
            }]      
    }
  ]
}
```
### Expected behavior:

All emojis and markdown should be rendered.

### Actual behavior:

Markdown is rendered properly, but emojis in the field (both `title` and `value` sections) are not rendered. Only the raw emoji text is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.2
- Operating System: Linux
- NodeJS Version: 12.18.1
- MongoDB Version: 4.0.11

### Additional context

This issue occurs with both the REST API and webhooks.

Note: This issue was previously reported under #17760, but was never fixed,

**Comment by yash-rajpal** [comment]
Hey can you test this on latest 3.11.1 version.
The team has re written attachments in React in new version, so maybe it was fixed there.

**Comment by shollander** [comment]
Unfortunately, I don't administer our server. I can try to get our admins to upgrade the server to see if it works with the new version, but it may take some time.

**Comment by juzser** [comment]
Still occur on 3.12.0

**Comment by markgharvey** [comment]
Also not able to render emoji by entering their label in RC channel topic description. 

openSUSE Leap 15.2
Chomium ... Version 2020.11 (Iridium Build) (64-bit)
You're on Rocket.Chat 3.12.0, using Hubot 3.3.2.
Adapter version 2.0.0-development, using version 0.2.9 of the SDK.

**Comment by zakhar-petrov** [comment]
The same on 3.12.1

**Comment by sthuber90** [comment]
Tested with RC 3.12.1 on Docker as well. For me not even the text within the attachment gets a rendered markdown icon

**Comment by smartie2076** [comment]
The emojis are also not rendered in the desktop app (`Rocketchat 3.1.1`, `Windows10`):
![grafik](https://user-images.githubusercontent.com/44204527/113289704-dba8a100-92f0-11eb-9af5-9cfac8d1fd49.png)
Weirdly, only this category is rendered:
![grafik](https://user-images.githubusercontent.com/44204527/113289745-ec591700-92f0-11eb-9704-d98d1deb114b.png)

**Comment by aboire** [comment]
The same on 3.14.0

**Comment by Janfy** [comment]
The same on 3.17.2
