### ISSUE TITLE
Pin Icon should not be shown for messages in Pinned messages Context

### ISSUE THREAD

**Issue by yash-rajpal** [RocketChat/Rocket.Chat#20764]
### Description:
When we star a message and look that message in Starred message context, star icon next to message is not rendered. It is understood that this message is starred as we are viewing from starred messages context, but same doesn't follow for pinned messages in pinned message context.
When we see pinned messages in Pinned messages context we can see pin icon

### Steps to reproduce:

1.  Star and Pin a message in any room
2.  Check for message in starred and pinned context.
3.  We dont see star Icon in starred context but can see pin icon in pinned context

### Expected behavior:
Pin icon should not be shown next to message in pinned context.

### Actual behavior:
Pin Icon is shown next to message in Pinned context.

We don't see star icon in starred context.
![image](https://user-images.githubusercontent.com/58601732/107939213-700eac80-6fac-11eb-89de-7819348488bc.png)

But we see Pin icon in Pinned context.
![image](https://user-images.githubusercontent.com/58601732/107939120-50778400-6fac-11eb-9d59-0d735f1a4988.png)

The behaviour should be consistent.
### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0 - develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome Browser version 87
- Operating System: Ubuntu

**Comment by hugocostadev** [comment]
Not really an issue
