### ISSUE TITLE
"Jump to message" button shown twice for starred messages in a thread

### ISSUE THREAD

**Issue by yash-rajpal** [RocketChat/Rocket.Chat#20762]
### Description:
If we star a thread message then "jump to message" button is shown twice for that message.

### Steps to reproduce:

1. Go to any thread
2. Star any thread message
3. Hover on message or click on all options, we see "jump to message" button twice.

### Expected behavior:
jump to message button should be shown once

### Actual behavior:
Jump to message button shown twice.

![jump-message-before](https://user-images.githubusercontent.com/58601732/107936316-8155ba00-6fa8-11eb-8507-4a9ca94e4b96.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
