### ISSUE TITLE
QA-Regression: Channel selected is not visible in the input field, while creating a discussion.

### ISSUE THREAD

**Issue by Ishrat-Manzoor** [RocketChat/Rocket.Chat#20777]
### Description:

Channel selected is not visible in the input field, while creating a discussion.

### Steps to reproduce:

1. Login to Rocketchat
2. Click on the Add icon in the left pane.
3. Click option "Discussion"
4. In the "Parent Channel or group" input field, add the channel name- say "general".
5. Wait few seconds till the channel name appears in the dropdown.
6. Select the channel name by either pressing Enter/return Key on the keyboard or by clicking on the channel name in the dropdown.

### Expected behavior:

Selected channel name should be displayed in the input field.

### Actual behavior:

The channel name doesn't appear in the input field, however the message "You are creating a discussion in "general" " appears below the field.
Same issue exists for Invite users field.
Issue exists on both web and the desktop app.
![image](https://user-images.githubusercontent.com/24873115/108029826-2e394100-7054-11eb-9eef-12719b83b1d1.png)

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by yash-rajpal** [comment]
This issue would be fixed by #20772 or #20773
