### ISSUE TITLE
When user is mentioned in threads, the mentions option of contexual bar has unusual UI. 

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20787]
### Description:
When a user is mentioned in thread messages, UI of the mentions option is weird.

### Steps to reproduce:

1. Any thread and tag yourself
2. Mentions from contextual bar

### Expected behavior:

UI should be clear.
### Actual behavior:
UI seems unusual.

https://user-images.githubusercontent.com/55157259/108108654-e697d100-70b6-11eb-9aad-6d8008eda51c.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context
Working!

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
