### ISSUE TITLE
Weird times expressed in Prune Messages panel

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#20784]
### Description:

Weird times expressed in Prune Messages panel

### Steps to reproduce:

1. Enter Prune Messages panel
2. Enter date and time ranges

### Expected behavior:

Date and time ranges as entered should be matched.

### Actual behavior:

Rocket Chat advises different dates and times that are incorrect:

![Weirdprune](https://user-images.githubusercontent.com/1122344/108082074-c9b6ca00-70c5-11eb-9d33-fd899d7e4372.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Occurs in both Desktop App (3.1.1) and Browsers (Firefox 85.0, etc)
- Operating System: Windows 10 and Linux Mint 19.3 and 20.1

### Additional context

Not at the moment.

### Relevant logs:

No errors in Rocket Chat logs.

No errors in browser logs.

**Comment by Darshilp326** [comment]
@nooblag Seems working fine for me
![Screenshot from 2021-02-16 21-50-22](https://user-images.githubusercontent.com/55157259/108090780-0623ff00-70a1-11eb-8173-2a4774a8e298.png)

**Comment by yash-rajpal** [comment]
Works fine for me as well, I event tried same date and time as yours.
![image](https://user-images.githubusercontent.com/58601732/108091738-007ae900-70a2-11eb-9161-ccbb09ac2b8b.png)

**Comment by nooblag** [comment]
Would it make a difference that my server is UTC+11?

And also, does the behaviour stay consistent if you type the dates and times and add "extra keystrokes"? I noticed mine started playing up more consistently when trying to correct typos...

I hope that's some help!

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.
