### ISSUE TITLE
Cannot clear a user's Nickname in Administration -> Users

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#20783]
### Description:

Cannot clear an existing set Nickname in Administration -> Users.

### Steps to reproduce:

1. Find user with existing Nickname you wish to clear
2. Delete all text in Nickname box and click Save.
3. Rocket Chat says "User updated successfully" but the Nickname is not cleared and remains what it was.

### Expected behavior:

Nickname is deleted/cleared.

### Actual behavior:

Nickname is not cleared and remains what it was.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Occurs in both Desktop App (3.1.1) and Browsers (Firefox 85.0, etc)
- Operating System: Windows 10 and Linux Mint 19.3 and 20.1

### Additional context

Not at the moment.

### Relevant logs:

No errors in Rocket Chat logs.

No errors in browser logs.

**Comment by Darshilp326** [comment]
Working on it!

**Comment by yash-rajpal** [comment]
Same issue is with removing user's bio. PR #20785 fixes for both.
Is there any other field that suffers with same problem?

**Comment by nooblag** [comment]
Hi there, I checked the pull request but I just want to clarify that I'm trying to *delete* existing data in a field--i.e. clear it to empty and save the field as empty. I hope this is covered in the pull request to fix? I could not be sure.

**Comment by yash-rajpal** [comment]
Yes @nooblag It works perfectly for Bio and Nickname. The problem with my setup is that if that field is empty, chrome tries to autofill it, If the field is filled then chrome won't interfere.

That's why I Showed in GIF that after emptying data from those fields the save button and reset buttons are disabled, which means data was saved.

You can also check by seeing User info display, nickname is not shown after I remove it.

**Comment by nooblag** [comment]
Ah okay, I misinterpreted. Thank you.
