### ISSUE TITLE
OTR Not working without error message in Console

### ISSUE THREAD

**Issue by TomaszDom** [RocketChat/Rocket.Chat#20791]
Description:

Bug report #20684 was closed, but the issue is still present in 3.11.1. 

If I start OTR I will get a timeout. No errors in debug console.  No sign of the OTR invitation on the receiving end.

Steps to reproduce:

    Click on OTR
    Start OTR
    Wait ~10 secounds
    Timeout message

Expected behavior:

Start OTR

Actual behavior:

I get a timeout and the other person doesn't see anything. After the timeout on the OTR tab the 3 dots won't go away so I have to reload the Browser/Client to resend an OTR request.

Server Setup Information:

    Version of Rocket.Chat Server: 3.11.1
    Operating System: Ubuntu 16.04
    Deployment Method: manual
    Number of Running Instances: 2
    DB Replicaset Oplog: yes
    NodeJS Version: v12.18.4
    MongoDB Version: 4.0.22

Client Setup Information

    Desktop App or Browser Version: Client and all browers
    Operating System: Windows 10

Additional context

Upgraded from 3.9.3, it worked fine up until that version.

Relevant logs:

**Comment by TomaszDom** [comment]
Does it work for you @yash-rajpal ?

**Comment by fbreckle** [comment]
This does not work for me either. Live setup is 3.10.5 and I tested on a dev setup with 3.11.1.
I get the described behavior on both servers.

**Comment by bombaata** [comment]
Exactly same behavior here with RC 3.11.0

**Comment by vidlb** [comment]
Same here with 3.11.1

**Comment by marcinpakula** [comment]
I also have same problem with RC 3.10.5 (latest snap version)

**Comment by Farfaday** [comment]
I confirm it got fixed with version 3.12.0 :)

**Comment by sennewood** [comment]
We still have this issue with 3.14.0

**Comment by matthias4217** [comment]
Hello, it seems that this has been fixed in the past, but with `4.2.0`, the problem has reappeared.

**Comment by TomaszDom** [comment]
It is indeed a blocker for us, thanks for the info, we're skipping yet another release.
