### ISSUE TITLE
Broken and truncated links in message attachments

### ISSUE THREAD

**Issue by TomaszDom** [RocketChat/Rocket.Chat#20806]
### Description:

I have many integrations configured and message attachments coming from integrations are all broken in 3.11.1, it worked fine up until 3.9.3, instead of clickable links we now have truncated raw text.

### Steps to reproduce:

Send message with attachments containing links in markdown like this:

```
<http://some.url|URL Text>

[URL Text](http://some.url)
```

### Expected behavior:

Rendered clickable links with "URL Text".

### Actual behavior:

Raw truncated text, no links.

![obraz](https://user-images.githubusercontent.com/9348532/108334349-20112f00-71d2-11eb-9032-69d427a32085.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu 16.04
- Deployment Method: manual
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: all

**Comment by aKn1ghtOut** [comment]
Could you attach the message object you're using for this, please

**Comment by TomaszDom** [comment]
After manually sending payloads itt turns out that maybe 3.11.1 broke the JIRA integration script I am using for JIRA integration found here:

https://raw.githubusercontent.com/malko/rocketchat-jira-hook/master/jira-rocketchat-hook.js

I have it definitely enabled in integration settings and messages coming through this integration and this script do not render markdown links as links. 

I did not modify this integration configuration or script in years, it worked fine on 3.9.3, now it's broken.

**Comment by aKn1ghtOut** [comment]
I think #20606 will have solved this for you now. Fix should be in the next release.
You could try with latest develop, and if it's something else, we can give it a look.
