### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by rm234179** [RocketChat/Rocket.Chat#2080]
I would like to suggest adding the ability to send email notifications to users if they are sent messages but are not currently logged in.  Similar to Slack.

![screen shot 2016-01-29 at 12 44 08 pm](https://cloud.githubusercontent.com/assets/6712253/12686281/08663082-c686-11e5-98d8-2ce3039cc0b7.png)

**Comment by engelgabriel** [comment]
Closed as duplicate of https://github.com/RocketChat/Rocket.Chat/issues/854 and https://github.com/RocketChat/Rocket.Chat/issues/741
