### ISSUE TITLE
Auto Translation - No translation for Message Action Labels

### ISSUE THREAD

**Issue by cuonghuunguyen** [RocketChat/Rocket.Chat#20803]
### Description:

Currently, there's only attachment descriptions are translated by the Auto Translation feature. The message actions are also a part of the attachment but they do not get translated. This makes the attachment Translation not consistent.

This issue also breaks the experience with bot integration since the message text and the message action will not be in the same language.

### Steps to reproduce:

1. Enable Auto Translation with proper settings
2. Send a message with some message actions
3. Translate the Message with Auto Translation feature

### Expected behavior:

Message action labels are translated

### Actual behavior:

Only Attachment descriptions are translated

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
