### ISSUE TITLE
Error hiding individual deletion in current chats

### ISSUE THREAD

**Issue by Jonathan-juc** [RocketChat/Rocket.Chat#20813]
**Description:**

The button to delete chat by chat in current chats is not hidden when removing the permission: Delete closed rooms from LiveChat. 

**Steps to reproduce:**

1. Go to Administration - permissions
2. Click on the Remove Closed Omnichannel Rooms permission in the admin role
3. Go to Omnichannel - Current Chats

**Expected behavior:**

The option to delete in the chat list is hidden
![image](https://user-images.githubusercontent.com/62675467/108391995-e0e5dc80-71d7-11eb-813c-88d25f4fe69b.png)

**Actual behavior:**

The delete option in the chat list is still displayed
![image](https://user-images.githubusercontent.com/62675467/108392512-68335000-71d8-11eb-8c74-d61937694f34.png)

only this new option is hidden _Delete all closed chats_
![image](https://user-images.githubusercontent.com/62675467/108396682-b9454300-71dc-11eb-9573-73880c756341.png)

**Server Setup Information:**

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.18.4
- MongoDB Version: v4.0.13

**Client Setup Information**

- Browser Version: Versión 88.0.4324.150
- Operating System: Windows 10

**Additional context**

This is a problem for our agents as they may misuse the button to delete conversation by conversation.

### Relevant logs:
N/A

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
