### ISSUE TITLE
[BUG] Reactions in Threads do not enforce Real Name Setting

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat#20841]
### Description:

While reactions in rooms and discussions are served with the real name setting enforced, those in the thread aren't. In the Threads, the usernames are **always** used for display.

### Steps to reproduce:

1. Set Real Names setting on for the server, or use one where it is turned on(Ex: Open.Rocket.Chat).
2. Open any thread with replies where at least one person other than the current user has reacted to a reply.
3. Hover over the reaction to look at the names.

### Expected behavior:
For the real name to be used.

### Actual behavior:

With use real name turned on.
![Screenshot from 2021-02-21 00-15-18](https://user-images.githubusercontent.com/38764067/108605403-e743a680-73d9-11eb-8ca0-c7c421188e5c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu 20.10
- Deployment Method: develop
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Firefox Latest
- Operating System: Ubuntu 20.10

### Additional context

Fix PR ready.

**Comment by gsckoco** [comment]
What's the craic with this now? There are 2 other issues that were closed as duplicates but one of them had a PR merged from what I can tell. Is it fixed or is it intended on being fixed in the near future?

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and it was fixed here: #30069

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
