### ISSUE TITLE
Need support for reply to a particular message using REST API

### ISSUE THREAD

**Issue by beulahpt** [RocketChat/Rocket.Chat#20858]
I need rest api to reply to a particular message. But nothing is mentioned about this in documentation. I really need this feature. Is this possible?

**Comment by Rodriq** [comment]
> I need rest api to reply to a particular message. But nothing is mentioned about this in documentation. I really need this feature. Is this possible?

Hey!
  Have you tried what's explained here => https://docs.rocket.chat/api/rest-api/methods/chat/sendmessage 

If you specify the `message.tmid`,  you should be able to start a thread.

**Comment by beulahpt** [comment]
Yes it works. thanks @Rodriq
