### ISSUE TITLE
Unpredictable behaviour of burgermenu in iframe

### ISSUE THREAD

**Issue by dmtrhfr** [RocketChat/Rocket.Chat#20859]
### Description:

We are embedding a channel on a site and the user are coming as guest users. The guests get a dm by a moderator of the channel. In this case the burger menu should get visible so the guest user realizes that he got a dm, but unfortanatly it doesn't work. Sometimes it is visible and sometimes it's not, we even observed that on some computers with firefox it's not visible at all.  In chrome it seems to work AFTER the guest joins the dm with the moderator manually in the iframe.
Same thing for logged in users.
Is there a way to enforce the burgermenu with custom css, so it is always visible?

### Steps to reproduce:

Embed RocketChat in an iframe.
Create a channel and allow guest users to join that channel or join the channel as a logged in user.
DM the guest/user as a logged in user.

### Expected behavior:

Burgermenu should get visible as soon as you get a dm even as a guest.

### Actual behavior:

Nothing happens, burgermenu is not shown, but you get a sound notification for a new message.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Debian
- Deployment Method: docker on k8s
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 12.18.4 - x64             
- MongoDB Version: 4.0.19

### Client Setup Information

- Browser Version: Firefox 85.0 , Chromium Version 88.0.4324.182 (Official Build) snap (64-bit)
- Operating System: Ubuntu 20.04

**Comment by yash-rajpal** [comment]
Please look at PR #20736. The burger menu icon disappears at a certain window width. If window width is set between 600px and 780 px the burger icon is not shown. The above mentioned pr solves this issue.

**Comment by yash-rajpal** [comment]
@dougfabris @ggazzo Please have a look. Thanks :)

**Comment by d3hof** [comment]
We realized that when we remove the embedded layout for the iframe, we always have a burgermenu.

**Comment by guijun13** [comment]
It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. Thank you very much!
