### ISSUE TITLE
RocketChat not updated 

### ISSUE THREAD

**Issue by NamDick** [RocketChat/Rocket.Chat#20851]
Steps to reproduce: Just open the app and be prompted by the update window
Expected behavior: It gets updated without a problem
Actual behavior: Not updating and keeps on showing update window
Server Setup Information: this is a company's property, I do not have the right to see this.
Version of Rocket.Chat Server: this is a company's property, I do not have the right to see this.

Every time I open RocketChat for work. It says 'New Update is Available", a new version of the app is available showing me an option to update from my current version 3.0.6 to 3.1.1 , there are 3 buttons, Skip this version, Remind me later, and Install Update. When I press on 'Install Update', it gives me a dialogue box saying "Downloading Update" as the title, the text " YOu will be notified when the update is ready to be installed" 

This process has been like this for more than 2 months now, it's like the exe installation file never gets downloaded properly. It's just so irritating, so I decided to go online and download from the website, unfortunately it's still the old version. So I tried to find a way and came across the path "C:\Users\Panther\AppData\Local\rocketchat-updater" - I could get the installation file out of it and installed it then indeed, it was the new version, on startup I did not have to press the buttons anymore as it did not ask for anything. Yay, yay yay until I just restored my system and all data got rolled back to previous state, NOW, once again I am stuck with the irritating prompt asking me to update every time I open the app.

Is there any solution for this ?
I also would like to report, notifications don't work as expected, most of the time, no sounds whatsover, I did try changing the setting to let it sound for all messages coming but sometimes it did not work at all, the same happens on my Android too.
![108621595-ce67df00-7433-11eb-99c9-60f7eebb68c7](https://user-images.githubusercontent.com/62629167/108665569-826d7680-74d5-11eb-8f18-75668918d13d.png)

**Comment by apaarfus** [comment]
Note that this is a [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron) bug for Windows users specifically, not the mainline server (which is this repository).  And additionally, there's a long, long list of issues related to it:

- [#1932](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1932)
- [#1916](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1916)
- [#1871](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1871)
- [#1876](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1876)
- [#1865](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1865)
- [#1837](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1837)
- [#1807](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1807)
- [#1788](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1788)
- [#1733](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1733)
- [#1683](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1683)
- [#1674](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1674)
- [#1670](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670)
- [#1665](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1665)
- [#1205](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1205)

And many more, unfortunately.  This issue has been around for quite some time -- at the time, the best solution to update RocketChat is to _either_ push out an update via Group Policy with the MSI release; or have your end-users manually upgrade by downloading & installing the latest release.

Essentially what is happening here -- as soon as the new installer is downloaded, it gets instantly deleted.  Its honestly like the updater code _skips_ the installation, and jumps straight to the cleanup stage; but I've not looked that far into that issue...just _watched_ the updater directory manually.

**Comment by ankar84** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
