### ISSUE TITLE
LDAP Avatar sync not working

### ISSUE THREAD

**Issue by r4nc0r** [RocketChat/Rocket.Chat#20856]
## Description:
On LDAP Sync the Avatars are not syncing / already existing ones are removed!

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: linux
- Deployment Method: docker swarm
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Steps to reproduce:

1. Setting -> LDAP -> sync now
2. view logs

### Expected behavior:

Working Avatar sync and not deleting existing ones

### Actual behavior:
the Avatars are not syncing / already existing ones are removed!

### Client Setup Information

- Desktop App or Browser Version: App/Broswer
- Operating System: windows/linux

### Additional context

nothing to add

### Relevant logs:

"Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined     at app/ldap/server/sync.js:367:51     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24) "

**Comment by torygg** [comment]
Same issue here after updating to 3.12.1

**Comment by ankar84** [comment]
We have same on 3.16.3
`Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined`

That means one or more user will with broken avatar until next sync (without that error).
@johncrisp please take a look.

**Comment by pierre-lehnen-rc** [comment]
Fixed on 4.0
