### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#2087]
hi, 

In chrome, 

1).  I am able copy table formats data and paste into chat as image

![image](https://cloud.githubusercontent.com/assets/16605816/12695222/189a2926-c76d-11e5-954b-bb0d0c084462.png)

But the same not able in Firefox browser 44.

Any settings has to be change in our server?

**Comment by MFQ** [comment]
I am also facing same problem, have you found any solution @sureshdba2003  ?

**Comment by engelgabriel** [comment]
I can't paste any image into FireFox at version 0.49.0

![image](https://cloud.githubusercontent.com/assets/1000217/21630159/e08fb1cc-d215-11e6-8f12-6e1f116d3ac7.png)
