### ISSUE TITLE
Editing a room in Administrator menu breaks that room's integration (special chars name used instead of safe name)

### ISSUE THREAD

**Issue by BizClimb** [RocketChat/Rocket.Chat#20885]
### Description:

Editing a room through the admin panel (not in the regular edit room interface) resets the name of the room in INTEGRATIONS, specifically using the "pretty name" with spaces as opposed to the clean name with dashes (in turn breaking the integration).

### Steps to reproduce:

Editing a room through the admin panel (not in the regular edit room interface) resets the name of the room in INTEGRATIONS, specifically using the "pretty name" with spaces as opposed to the clean name with dashes (in turn breaking the integration).

1. Turn on "Allow special chars on room names"
2. Create a room with a space in it. Example: "Test Room" which has a clean name of #test-room
3. Create an outbound integration and set channel to: #test-room
4. Go to Administration -> Rooms
5. Find your test room and edit something (I believe anything really as long as some kind of change to save).
6. Save
7. Check integration, the "special chars" name (#Test Room) was used instead of the "clean name" (#test-room)

### Expected behavior:

Integration's channel should retain safe name (and not break).

### Actual behavior:

Integration's channel gets the special character name and breaks. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Linux (Debian)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.7 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Desktop App
- Operating System: Windows 10

### Additional context

None

### Relevant logs:

None

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest version and it was fixed here: #29019

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
