### ISSUE TITLE
[UI Improvement Suggestion] Please, distance off "Pin/Unpin" button from "Edit" button

### ISSUE THREAD

**Issue by joaogolias** [RocketChat/Rocket.Chat#20903]
## Description:
Probably, I might be very "anxious", but I always misclick the "Pin/Unpin" button when I want to "Edit" a message. There isn't any strange behavior about it, but, when I click on "Pin/Unpin" a message saying that I have pinned the message is sent in channel at hand and cannot be deleted. 
I don't know the best option:
1. Distancing both buttons; or
2. When a message is unpinned, the message sent to channel (about the "pinning" it self) should be deleted as well;

**Steps to reproduce**:

- Open RocketChat chat box.
- Send a message
- You will see two buttons one below another when you click in "three dots" button in the message

**Expected behavior**: 
The behavior is right, and I know I might be a "bad" user, but, please, it's really anoying and might not be too hard to be solved. 

Thanks guys! ;)

**Comment by yash-rajpal** [comment]
@joaogolias you can always turn off pin message system messages, then the message for pinning message won't be shown.

Distancing a button from another is not the solution for this problem. Also if you want to edit a just sent message you can use keyboard shortcut and press up arrow key, it would allow you to edit previously sent message.
