### ISSUE TITLE
[ UI ]: Two separate timestamps appear on hovering over the time on the side of the username.

### ISSUE THREAD

**Issue by ahtrahdis7** [RocketChat/Rocket.Chat#20902]
### Steps to reproduce:

1. Open RocketChat chat box.
2. Hover over the time adjacent to the username of anyone having sent a message in the chat box.
3. You will see two separate timestamps visible.

### Expected behavior:

Only the upper/bigger timestamp should appear.

### Actual behavior:

<img width="1680" alt="Screenshot 2021-02-25 at 11 18 57 AM" src="https://user-images.githubusercontent.com/44672399/109109885-1fd9dc00-775c-11eb-85a5-52d8a96738e6.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: MacOs BigSur
- Deployment Method: Localhost
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.20.2
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: Safari [ Version 14.0.2 (16610.3.7.1.9) ]
- Operating System: MacOs BigSur

**Comment by Rodriq** [comment]
@ahtrahdis7 do you have hands on this?

**Comment by ahtrahdis7** [comment]
Hi @Rodriq , you can take the issue, I currently am not working on this.

**Comment by Darshilp326** [comment]
@Rodriq @ahtrahdis7 I think this is the case with every hover.

**Comment by ahtrahdis7** [comment]
It didn't occur while I was using Chrome. I think this issue is specific to Safari.

**Comment by sauravrajleaf** [comment]
@ahtrahdis7 It's happening in Firefox web browser too but it's not occurring al the time.

**Comment by aswinidev** [comment]
I think this issue is fixed @dudanogueira  please close this.
