### ISSUE TITLE
Need One on One chat (which online status)

### ISSUE THREAD

**Issue by ankesh27** [RocketChat/Rocket.Chat#2091]
Hello, 

We are building a website that needs C2C chat. One customer can chat to other customer If he/she is online(online status should be available). For example, check www.quikr.com It has a decent chat feature that allows one customer to chat with the seller if he sees that the seller is online. We need this ASAP. 

Reply awaited.

Ankesh

**Comment by blastoffchat** [comment]
User to user chat is already available in Rocket.Chat.

**Comment by ankesh27** [comment]
Is there is online Status available, i.e I(my system) can set the status of user as online/offline so that people visiting my profile can see my availability(online/offline).

Thanks

**Comment by marceloschmidt** [comment]
So, let me get this straight. What you need is that when a customer visits your site, he/she can chat with another customer, also visiting your site? 
Do they join a specific room or something? Maybe have a SSO with your site?

**Comment by ankesh27** [comment]
Right so, "when a customer visits your site, he/she can chat with another customer, also visiting your site" is absolutely right, but for this feature they will not have to join a specific room.

SSO is right, we will have to incorporate the same if this feature is available.

Let me know if something like this is possible.

**Comment by geekgonecrazy** [comment]
Users can see other users status's already.  closing this
