### ISSUE TITLE
Sticker Feature Like Line/Facebook/Wechat

### ISSUE THREAD

**Issue by jefflau76** [RocketChat/Rocket.Chat#2092]
Sir,
I would like to inform that is good to have sticker something like available in other messenger Line/Facebook/WeChat. It able to make rocket chat to be their hobbies and attractive and a part of their life time spend

Hope suggestion able to be accepted

**Comment by subesokun** [comment]
Would love to see this feature as well. Also it would be great if you could upload your own sticker set...! And last but not least stickers are very important for the asian market :)

**Comment by rasos** [comment]
+1 even in business environments Stickers are used heavily, not only with private users.

**Comment by muus84** [comment]
+1

**Comment by graywolf336** [comment]
Can someone show a screenshot of how this would be used and what the result would be? Can it not be an integration like giffy?

**Comment by thiesschneider** [comment]
it is integrated in our giffy integration https://github.com/FinndropStudios/GifRocket

**Comment by graywolf336** [comment]
Closing this in favor of that then, thanks :+1:

**Comment by rasos** [comment]
We have produced a set of custom emojis (available since RC ~0.42), which fulfill all our needs for stickers.
