### ISSUE TITLE
RocketChat shows "undefined" when sharing pictures from Nextcloud/Webdav

### ISSUE THREAD

**Issue by thomsenle** [RocketChat/Rocket.Chat#20939]
### Description:

Files from Webdav/Nextcloud can't be shared in the chat.

### Steps to reproduce:

After connecting a Nextcloud-Server to Rocket.chat and clicking the (+) button the file list of the Webdav folder appears.
Then i select a file. In the next dialog i enter a description and press "send". 
The file does not appear in the chat - it only displays a error on top "undefinded".

![2021-02-28 18_18_00-Window](https://user-images.githubusercontent.com/2514930/109427224-a9560c00-79f1-11eb-82a5-d5ced0128527.png)
![2021-02-28 18_18_15-Window](https://user-images.githubusercontent.com/2514930/109427228-ad822980-79f1-11eb-8dd4-af33c3efcfd3.png)
![2021-02-28 18_18_27-Window](https://user-images.githubusercontent.com/2514930/109427229-af4bed00-79f1-11eb-8b55-1cfea35cd4a1.png)

### Expected behavior:

The file should appear in the chat.

### Actual behavior:

A error message on the top.

![2021-02-28 18_18_45-Window](https://user-images.githubusercontent.com/2514930/109427232-b115b080-79f1-11eb-89f0-47e01256e313.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1 / 3.12.0-rc.0
- Operating System: Debian Buster
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.23 / mmapv1 (oplog Aktiviert)

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 88.0.4324.190 
- Operating System: Win10

### Relevant logs:
In the logs i can see that the file is successfully send from the webdav server to rocketchat.

![2021-02-28 18_24_03-Rocket Chat - Brave](https://user-images.githubusercontent.com/2514930/109427354-56308900-79f2-11eb-8398-b43863af97eb.png)

Then there is a message with following error:

Exception while invoking method ufsCreate TypeError: Cannot read property 'rid' of undefined     at Filter.validateFileUpload [as onCheck] (app/file-upload/server/lib/FileUpload.js:62:24)     at Filter.check (packages/jalik:ufs/ufs-filter.js:107:51)     at MethodInvocation.ufsCreate (packages/jalik:ufs/ufs-methods.js:155:12)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:262:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 

![2021-02-28 18_24_45-Window](https://user-images.githubusercontent.com/2514930/109427406-8b3cdb80-79f2-11eb-88f4-2d88e7bdec68.png)

**Comment by fabiosurrage** [comment]
I got exactly the same error. Any help ? I think we are missing something...

**Comment by MonsieurKoZo** [comment]
Same error here too.
RC 3.12 under snap (Raspberry Pi 4) and Nextcloud 21 on the same machine.

**Comment by falkiy** [comment]
something new here?

**Comment by OneTwoBarbecue** [comment]
Same error here: Snap 3.13.2 and Nextcloud 21/various WebDAV-servers

**Comment by ConsultorML** [comment]
I have the same error. Snap Versión 3.14.4 and Nextcloud 21.

**Comment by sampaiodiego** [comment]
the fix is included in 3.15.0 version.. I'll see if we can publish it to snaps as well
