### ISSUE TITLE
Markdown Style is not working for Room Info (topic)

### ISSUE THREAD

**Issue by Cancer-zern** [RocketChat/Rocket.Chat#20932]
### Steps to reproduce:

1. Open Room info
2. Edit
3. Add `[Text](https://example.net/)`

### Actual behavior:

![image](https://user-images.githubusercontent.com/68541237/109411256-3a10f580-79ba-11eb-95b1-75a8a84eafb4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.5
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10 20H2 x64
- Google Chrome Version 88.0.4324.182 (Official Build) (64-bit)

### Additional context

if am doing for the message like `[Text](https://example.net/)` it is working, but for the topic is not working properly.

**Comment by Cancer-zern** [comment]
[Markdown Style Guide](https://docs.rocket.chat/contributors/contributing/documentation/markdown-styleguide)

![image](https://user-images.githubusercontent.com/68541237/109411323-aa1f7b80-79ba-11eb-8186-33f4f7506caa.png)

**Comment by shrinish123** [comment]
I think this is a OS related issue . Because this works fine for me on Windows (WSL2)

**Comment by Cancer-zern** [comment]
I've checked for another 3 workstations and they have the same issue.
Also, I've checked on Android 11 via Google Chome and have the same issue.

**Comment by yash-rajpal** [comment]
Please upgrade server version and check. This bug was fixed in 3.11.0 release.

Thanks :)

**Comment by Cancer-zern** [comment]
Hi,

Currently for the SNAP installation is available Rocket.Chat 3.10.5 only.
Just waiting for this update for the SNAP installation.
