### ISSUE TITLE
[BUG] Room roles are not deleted when user lefts/removed from room.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#20951]
### Description:
When any user is kicked/removed from room, room-roles are not deleted. So when a user joins again we can't change his/her role. 

### Steps to reproduce:

1.  Room
2. Give any user owner role and then remove him from the room.
3. Add that user again and go to make the user owner again.

### Expected behavior:
Room roles should be refreshed when the user is removed from the room.

### Actual behavior:
Room-roles are not refreshed.

https://user-images.githubusercontent.com/55157259/109503844-c86f9f00-7ac0-11eb-96e4-2e69aee8b218.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Additional context
When we go again to make that user owner the text shows 'Remove as Owner' but actually the user is not an owner. So we cannot make the user owner again.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
