### ISSUE TITLE
Color scheme: Bug at changing font colors of side navbar

### ISSUE THREAD

**Issue by XxXHerrHXxX** [RocketChat/Rocket.Chat#20953]
### Description:

Our team has been using Rocket Chat for quite some time and we have now upgraded to version 3.11.1. Because of this we had the problem that a big part of our custom script didn't work anymore. 
After reading up on the new color scheme (at https://docs.rocket.chat/guides/developer/ui-and-theming/colors#:~:text=of%20rocketchat%2Dtheme%20.-,Color%20Scheme,and%20not%20exposed%20to%20settings.) , we wanted to change the font color of the sidebar (tertiary-font-color). The problem is that this change is not displayed that way. It seems that the color class --rcx-color-foreground-hint overrides the change.

### Steps to reproduce:

1. Go to the administration panel
2. Search after Layout
3. Open the dropdown of "Old Colors (Minor)"
4. Change the first input field (tertiary font color)

### Expected behavior:

The font color of of the sidebar should now be the new color. 

### Actual behavior:

The font color doesn't change. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: SUSE Linux Enterprise Server 12 Sp3
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.20.0
- MongoDB Version: v4.2.11

### Client Setup Information

- Browser Version:
- Windows 10

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
