### ISSUE TITLE
The bot's avatar is not displayed in the channel.

### ISSUE THREAD

**Issue by Aleksei-Badyaev** [RocketChat/Rocket.Chat#20950]
![Снимок экрана от 2021-03-01 16-24-04](https://user-images.githubusercontent.com/6613001/109504431-948a7e80-7aac-11eb-8d3c-a43825f126d6.png)
### Description:

The bot's avatar is not displayed in the channel.

### Steps to reproduce:

1. Create new user with role "bot".
2. Assign image as avatar of newly created user with role "bot".
3. Post message from new user (through integration web-hook for example).
4. Look into channel with message from new user.

### Expected behavior:

The user's messages are displayed with their avatar.

### Actual behavior:

The user's messages are displayed with default (square with letter) avatar.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: debian 10 buster
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 218 (1 марта 2021 г., 14:19
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: desktop app
- Operating System: Ubuntu 20.04

### Additional information

See screenshot for more information.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
