### ISSUE TITLE
rocketchatctl restore doesn't work

### ISSUE THREAD

**Issue by jorueda** [RocketChat/Rocket.Chat#20962]
### Steps to reproduce:

1. Do a backup using rocketchatctl backup.
2. At the end rocketchatctl backup says: "Backup done successfully, check for the backup file in /tmp/dump_1605621405.gz. You can restore using # mongorestore --host localhost:27017 --db rocketchat --archive --gzip </tmp/dump_1605621405.gz"
3. Executing mongorestore --host localhost:27017 --db rocketchat --archive --gzip </tmp/dump_1605621405.gz restore incomplete, lacks of some images and configuration files.

### Expected behavior:

Expected full and complete restore.

### Actual behavior:

All files not complete restored.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Linux
- Deployment Method: rocketchatctl
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: Google Chrome
- Operating System: Linux Ubuntu 20.04

### Additional context

No additional information.

### Relevant logs:

No additional information

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
