### ISSUE TITLE
LDAP broken when using meteor deploy

### ISSUE THREAD

**Issue by alisalaah** [RocketChat/Rocket.Chat#2096]
Deploying to ***.
Loading plugin `minifyStd` from packa...
WARNING: The output directory is under your source tree.
Errors prevented deploying:
While linking the program:
error: rocketchat:ldap is not compatible with architecture 'os.linux.x86_64'

**Comment by engelgabriel** [comment]
Hi @alisalaah can you try the latest develop branch?

**Comment by rodrigok** [comment]
@alisalaah It's fixed in our developing version now.

Thanks.
