### ISSUE TITLE
Github integration visual bug 

### ISSUE THREAD

**Issue by kkhanh** [RocketChat/Rocket.Chat#20960]
### Description:

Hi,

We ran into a visual bug after an update (3.11.1)

The notifications is still working though, we are using the following script : https://docs.rocket.chat/guides/administrator-guides/integrations/github

The visual result is very different from what It used to be, no more profile photo, description and link to the commit

Any help would be appreciated

Thanks

### Steps to reproduce:

tar update to 3.11.1

### Expected behavior:

![Selection_054](https://user-images.githubusercontent.com/14584194/109641831-7414ff80-7b52-11eb-8f47-458f9ae00434.png)

### Actual behavior:

![Selection_052](https://user-images.githubusercontent.com/14584194/109637440-17631600-7b4d-11eb-8ff4-3ed948004437.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v12.18.4
- MongoDB Version:4.0.19

### Client Setup Information

- Desktop App or Browser Version: Tested on multiple browser Chrome and Firefox
- Operating System: Debian

**Comment by fdellwing** [comment]
This is fixed in 3.12.0 but be aware that you should not update if you rely on the Jitsi integration.

**Comment by kkhanh** [comment]
Thank you very much, all good
