### ISSUE TITLE
Admin rights per group/per channel

### ISSUE THREAD

**Issue by patoupatou** [RocketChat/Rocket.Chat#2097]
Maybe I missed the options, but (myself as an admin) can I give admin rights to somebody ONLY for one channel/private group? i.e this group admin could kick members but not have global admin privileges.

**Comment by marceloschmidt** [comment]
It's called a moderator, and you can give them this access by going to the channel, clicking on the user list, then on a user and click on `Set as moderator`.

![image](https://cloud.githubusercontent.com/assets/1986378/12780911/0d74d990-ca58-11e5-9628-c7d44ddee001.png)
