### ISSUE TITLE
Channel listing last entry is not visible

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#20983]
### Description:

In RC 3.12.0, depending on the channel list view settings, some entries may get cut from the view or be only partly visible.

### Steps to reproduce:

1. Have lots of channels and contacts
2. Scroll to the bottom

### Expected behavior:

All entries are fully visible

### Actual behavior:

Last entry or part of it is missing.

![Screenshot from 2021-03-03 12-51-53](https://user-images.githubusercontent.com/6958942/109795713-f0c1df80-7c1f-11eb-81d7-e7d72510957a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: any browser

### Additional context

Workaround to the issue is to set .teste element margin-bottom to 0px in Layout custom CSS settings:

```
.teste {
   margin-bottom: 0px !important;
}
```

The default was -14px.

**Comment by Darshilp326** [comment]
@Gummikavalier Hello! Can you give more information/video?

**Comment by Gummikavalier** [comment]
@Darshilp326 Regarding the issue? Generally there is no more into it than just scrolling down in channel list and contacts list.When you reach the last entry it gets cut more or less depending on your view settings. This happens because margin of that .eteste CSS element is outside of the visible area. The margin value without any custom CSS edits is -14px, so it looks like it gets under the logo.

The actual element is this:
![Screenshot from 2021-03-03 18-43-59](https://user-images.githubusercontent.com/6958942/109840222-95f4ac00-7c50-11eb-9cc6-fb5914ecf954.png)

**Comment by Gummikavalier** [comment]
Linking here as related:
https://github.com/RocketChat/Rocket.Chat/pull/21014
