### ISSUE TITLE
Multiple instances of Jitsi open when placing call

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#20989]
### Description:
When placing Jitsi calls the window pops out multiple times (and when window pop out is disabled it also has appeared multiple times on the panel). Sometimes it opens 2 windows, sometimes it even opens up to about 5 or 6.

### Steps to reproduce:

1. Enable Jitsi under video conference 
2. Enable always open in new window 
3. Attempt to place calls with someone

### Expected behavior:

Window pops out a single time, as it did before.

### Actual behavior:

Window pops out multiple times.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: v3.6.3

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10, Arch Linux, Fedora

**Comment by fdellwing** [comment]
Probally same issue as #20946

**Comment by mmgoilf** [comment]
> 
> 
> Probally same issue as #20946

Yes you're right, and I see they said it should be fixed in the next update.
