### ISSUE TITLE
Please wait  message stuck while try to login

### ISSUE THREAD

**Issue by Jimitest0303** [RocketChat/Rocket.Chat#20982]
Not able to login.

had tried many time uninstall and install new version again and again.

Username: -Jaimini.Kanhasoft@gmail.com

System windows

**Comment by Jimitest0303** [comment]
Steps to reproduce
Expected behavior
Actual behavior
Server Setup Information
Version of Rocket.Chat Server:- rocket chat 3.1.1

**Comment by ndarilek** [comment]
Please don't randomly ping people. I have nothing to do with this other 
than having filed some issues a long time ago. Pinging random people you 
see in the issue history is rude.
