### ISSUE TITLE
[v3.11.1] Slow loading of Channels: Up to 10 seconds. Safari browser.

### ISSUE THREAD

**Issue by voroyam** [RocketChat/Rocket.Chat#20999]
### Description:

When I want to enter a channel it takes from 6-10 seconds until the channel loads.

### Steps to reproduce:

1. go to server url and login
2. click on a chat channel
3. wait for the channel to be opened

### Expected behavior:

channel is opened and I can see the contents

### Actual behavior:

nothing happens for 6-10 seconds

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.1
- Number of Running Instances: 1
- 
### Client Setup Information

- Desktop App or Browser Version: Safari [14.0.3] 
- Operating System: macOS [11.2.1]

**Comment by adocampo** [comment]
that was solved on 3.12.0, but beware, on that version there is a jitsi error making spawing jitsi windows every few seconds

**Comment by ankar84** [comment]
It fixed in 3.12 by https://github.com/RocketChat/Rocket.Chat/pull/20860

**Comment by voroyam** [comment]
if this is fixed, I will close the issue and wait for the 3.12.1. Thanks all. :]
