### ISSUE TITLE
Add unread messages counter on favicon

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#21]
- [x] Ttile indication
- [x] Favicon indication
- [x] Sum the unread messages from all rooms

**Comment by engelgabriel** [comment]
thanks @scottyallen

**Comment by scottyallen** [comment]
Sure thing:)  Sounds like it has a bug though, where there's unread messages across multiple rooms.  I'll send a second PR to fix that.  I misunderstood the ChatSubscription data model, I think.

**Comment by engelgabriel** [comment]
Cool! Looking forward for that!

**Comment by scottyallen** [comment]
Can we close this issue now or is there something still unfinished?
