### ISSUE TITLE
Searching for group members in private chanel causes an error "to-many-requests"

### ISSUE THREAD

**Issue by redRolf** [RocketChat/Rocket.Chat#21001]
### Description:

When searching for members in a private group/channel after typing some letters to search for a group member the page blanks and an error message "to-many-requests" is displayed.

### Steps to reproduce:

1. Go to a private group/channel 
![image](https://user-images.githubusercontent.com/42872307/109952764-7fe1fc80-7cdf-11eb-9e79-c14533dc4b8d.png)

2. Click on members: 
![image](https://user-images.githubusercontent.com/42872307/109952824-92f4cc80-7cdf-11eb-8259-bf1430ce9590.png)

3. Start typing in the search field: 
![image](https://user-images.githubusercontent.com/42872307/109952900-adc74100-7cdf-11eb-8c3d-378e5b02bee8.png)

4. After rapidly entering a name the following error occurs. It is not always consistent how many characters or how fast I have to type to force the error but 9/10 time I get the error. (Copy and past does not produce the error only manual typing): 
![image](https://user-images.githubusercontent.com/42872307/109953085-dfd8a300-7cdf-11eb-806f-8258371309ea.png)

### Expected behavior:

The search not to produce an error

### Actual behavior:

The search produces an error, and the page has to be re-loaded with CMD+R

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Fedora Core OS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: (oplog Enabled)
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.23 / wiredTiger 

### Client Setup Information

- Desktop App: 3.0.3
-  Browser Version: 88.0.4324.192 Google Chrome
- Operating System: macOS

### Additional context

This issue only occurs in private channels/groups. Also, the problem only occurs when manually typing. My hunch would be, that when searching and typing each character that is entered causes a new search in order to display the users matching the substring of what I am in the process of typing. Now depending on the typing speed and the speed at which theses searches are triggered some sort of limit is hit fairly quickly resulting in this error.

### Relevant logs:

Browser Logs:
[rocket.intra.redguard.ch-1614856245390.log](https://github.com/RocketChat/Rocket.Chat/files/6083124/rocket.intra.redguard.ch-1614856245390.log)
Server Logs: Unfortunately there are no log entries in the server log at the time where the error occours.

**Comment by Darshilp326** [comment]
@dougfabris Should we increase debounce time?

**Comment by dougfabris** [comment]
> @dougfabris Should we increase debounce time?

Please, let's try it!

**Comment by Darshilp326** [comment]
Onto it!
