### ISSUE TITLE
The Reactions option doesnt show who have reacted what emoji on the message

### ISSUE THREAD

**Issue by shrinish123** [RocketChat/Rocket.Chat#21002]
### Description:

If we try to see the reactions on a particular message to check which users reacted what emoji, it just shows an empty modal

### Steps to reproduce:

1. Hover over any message
2. Click on the 3 dots option and then go to last option 'Reactions'
3. Click on Reactions 

### Expected behavior:

The modal should actually show who have reacted

### Actual behavior:

![issue 3](https://user-images.githubusercontent.com/56491104/109957973-b03f9000-7d0b-11eb-81fa-004a7f879711.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Windows (WSL)
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.x
- MongoDB Version: 4.x

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows

**Comment by Darshilp326** [comment]
@shrinish123 Hello! #20753 would fix the issue :smiley:

**Comment by shrinish123** [comment]
@Darshilp326 oh sorry ,didn't see that. Thanks for helping :)
