### ISSUE TITLE
gitlab WebHook messages are not displayed correctly

### ISSUE THREAD

**Issue by flablog** [RocketChat/Rocket.Chat#21009]
### Description:

Hi

When using the current gitlab webhook, the messages are displayed truncated in rocket.chat in webbrowsers or desktop clients, but are displayed well on android and iOS apps.

This is on desktop (windows) or web (chrome, firerefox for windows and safari for ios):
![image](https://user-images.githubusercontent.com/870195/110103141-e3366200-7da5-11eb-881a-9fab29e69e8d.png)

This is the same message on the same server and channel on iOs (android is the same)
![image](https://user-images.githubusercontent.com/870195/110103961-db2af200-7da6-11eb-97db-5970d1f34725.png)

I can't find someone else having the issue. I can't find a setting that explains that. Maybe it's a dumb option. But I can't find it.
Hi tried again with a different user doing the Post As (but this parameter doesn't look to be used)

### Steps to reproduce:

1. Use the webhook available here : https://docs.rocket.chat/guides/administrator-guides/integrations/gitlab
2. Make the integration from gitlab

### Expected behavior:

The message should be fully displayed in any case

### Actual behavior:

Messages are truncated on desktop or broswers (that includes also safari on ios instead of the rocket.chat app)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: Tested on windows rocket.chat app 3.1.1 (latest), safari ios 14.4), firefox/chrom on windows (latest), ios app and android app latest (working on this cases)
- Operating System: windows/ios/android

Thanks !

**Comment by pjsft** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/20606

The bug has already been reported multiple times. It has been fixed in version 3.12.

**Comment by flablog** [comment]
Ok, we'll update the server.
Sorry I wasn't lookinf for the right terms and thought it was just with the gitlab hook. 

Thanks !

**Comment by liugddx** [comment]
I have the same problem.My version is 3.12.

**Comment by minix-it** [comment]
3.13.2 installed and the problem remain the same
