### ISSUE TITLE
Default accepted file uploads

### ISSUE THREAD

**Issue by aaronhagopian** [RocketChat/Rocket.Chat#2101]
Running the latest docker image, I cannot upload Excel or CSV files.  Not sure why the system is setup to reject any mime types (unless there is some security thoughts i'm missing).  

I noticed an older issue where restarting fixed for them but i have restarted and the issue has not gone away.

**Comment by aaronhagopian** [comment]
Figured it out but seems like not sane defaults for people new to rocketchat.  I suggest instead changing this issue to address common file types to be allowed by default like excel, zip etc.

**Comment by twhiting** [comment]
Status on this issue?

**Comment by engelgabriel** [comment]
What do you guys suggest for the default value?

**Comment by twhiting** [comment]
The reason I bring this up is we cannot upload .zip files even when the setting is specifically set to allow all types of uploads.  This was marked as an improvement a month ago and seemed to be a dead issue.  Thanks for adding it to the milestone @engelgabriel 

Ideally, I think that when all types of uploads are allowed that should be taken literally to allow all types.  Including ZIP / CSV / EXCEl etc.  Then a separate toggle switch could be made to limit some hazardous file types if desired.

**Comment by engelgabriel** [comment]
@twhiting do you mean the **Accepted Media Types**?

![image](https://cloud.githubusercontent.com/assets/1000217/13717110/11caba68-e7be-11e5-8a0a-101dd02440f7.png)

**Comment by twhiting** [comment]
Yes, as stated if I "Leave it black for accepting all media types" I still cannot upload any file-types that I want.  So a zip file for example, I am unable to insert.  Is this by design?

**Comment by engelgabriel** [comment]
Did you try restarting the server after changing the setting?

**Comment by twhiting** [comment]
Yes

**Comment by twhiting** [comment]
To add to this.  I currently have my file upload type set to: 

image/*,audio/*,application/*,text/*,video/*,*/*

And I still cannot upload file types such as: .sys .dmp .LOG .inf

**Comment by engelgabriel** [comment]
You can now leave it blank or just put a single "*" as on the settings to allow all.
This should be fixed on version 0.23.0
Please reopen otherwise.

**Comment by ulope** [comment]
This should really be explained better in the UI. Especially since there now seem to be two kinds of "all". Empty means some ill-defined subset of all while `*` means really-yes-I-want-all.

**Comment by engelgabriel** [comment]
Strange, that shouldn't be the case. Empty and * should be the same.

@sampaiodiego can you investigate this?

**Comment by souhaib22** [comment]
For CSV file add 
`text/csv` or my configuration `
image/*,audio/*,application/zip,application/pdf,text/plain,
text/csv,application/ms-powerpoint,application/msword,application/ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.presentationml.presentation` 
Word(.doc & docx)
Excel(.xls & xls)
Powerpoint(.ppt & .pptx)

**Comment by lightweight** [comment]
Would be great to include Open Document formats by default, too... `application/vnd.oasis.opendocument.*`

**Comment by lightweight** [comment]
I note that manually specifying `application/vnd.oasis.opendocument.*` (and restarting the server) does not seem to successfully allow `application/vnd.oasis.opendocument.text`- am I misunderstanding how "*" (wildcards) work? I'm on 0.59.4

**Comment by craig** [comment]
Also text/yaml and application/json would be helpful.

**Comment by andrewbrooke72** [comment]
if you have a popup saying that text/csv not allowed.. add it to access media types with comma at the end of the line ",text/csv"
