### ISSUE TITLE
Searching setting in sidebar from admin account

### ISSUE THREAD

**Issue by ABHAYJAIN2601** [RocketChat/Rocket.Chat#21029]
### Description:

It doesn't show the correct sequence according to the word that type in the search field

### Steps to reproduce:

1. Go to administration in sidebar option search for any setting in the search bar 
2. you will see that it produce the wrong sequence.

### Expected behavior:

At least the first letter that matches any setting name need to come first

### Actual behavior:

![regrex](https://user-images.githubusercontent.com/51324264/110241527-53481200-7f77-11eb-8fd0-22fa74a4aef6.JPG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64 
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chorme
- Operating System:linux

**Comment by Darshilp326** [comment]
@ABHAYJAIN2601 Hello! I dug into the issue and found out that our text searches for inner setting also but returns its parent setting name(Eg. If any setting is listed into accounts and you search for that it would return 'Accounts' instead of that inner setting)

**Comment by yash-rajpal** [comment]
I agree with @Darshilp326 , this is not a bug but a feature. Lets say you are searching for setting `UI_Use_Real_Name` or `use real name` and you don't know where this setting is located, you can directly search for this setting and you will be shown `Layout` option as this setting is in Layout section.

I think this is a good thing to have to easily search desired settings and this issue can be safely closed.

**Comment by ABHAYJAIN2601** [comment]
@Darshilp326  @yash-rajpal  thanks for looking into this Yeah! you guys are correct
