### ISSUE TITLE
Allow to move message into thread

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#21023]
Occasional users often do not answer in threads, but in the channel. Sometimes you get answers mixed in the channel and in the thread which makes following a thread difficult.

It would be great to be able to move selected messages to a thread (and maybe also to a discussion, see also #14016). This would require a separate permission, which could be given by default o all users, but may be restricted to moderators or owners of a channel.

**Comment by hitblackjack** [comment]
I need this feature, as a  team admin , I want to tidy up  the threads.
