### ISSUE TITLE
Theming - Ability to redesign the interface

### ISSUE THREAD

**Issue by Johann-Snapp** [RocketChat/Rocket.Chat#2102]
Hi there,

I've try for 2 days to redesign a part of the Rocket.Chat interface.
To be clean and not have to merge some huges commits each time I do an update, I tried to override default templates from a local custom Meteor package.
The problem is, I can't override anything. I've reproduced the file architecture of the part I wanted to override, I set up correctly the package.js, etc.
As a last try, I played with the packages inclusion order and noticed something I don't understand: if I include my package before `rocketchat:livechat`, my JS file related to the template is included but impossible to display the view associated (talking about `home.coffee` & `home.html`here).

So, as asked in #1972, is it hard to achieve to permit custom UI ?
Is there already a way to do it ?
Why is my approach bad ?

Thancks for answers.

**Comment by Sing-Li** [comment]
@Johann-Snapp the fact that it requires someone with your skill level to ask the 'right' questions in order to _try to install_ a theme - is evidence enough that we need to re-visit our 'theme' system.   

Re-opened #277  And thanks.

**Comment by Johann-Snapp** [comment]
@Sing-Li In short term, it won't be possible for me but we're discussing about this possibility in my company. I'll let you know once I've got a definitive answer.

**Comment by engelgabriel** [comment]
I am closing this to keep the conversation centralized at https://github.com/RocketChat/Rocket.Chat/issues/277
