### ISSUE TITLE
Selecting avatar in user profile

### ISSUE THREAD

**Issue by ABHAYJAIN2601** [RocketChat/Rocket.Chat#21024]
### Description:

When we select different avatar option in the profile section problem arise when we select the link option and go back to default or image option save changes works

https://user-images.githubusercontent.com/51324264/110232562-68f01400-7f44-11eb-8e66-47f298a33772.mp4

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by apurb-coder** [comment]
Hey, @dougfabris can I work on this issue?

**Comment by dougfabris** [comment]
@apurb-coder This issue doesn't happen anymore, because currently, there's no way to click on the link button if the input is empty. But we do have an issue that breaks the avatar if you hit the button adding an invalid link, if you could take a look at that would be more than welcome

**Comment by apurb-coder** [comment]
@dougfabris  , **is this behavior ok ? ...**

**Before:** 

[screen-capture.webm](https://github.com/RocketChat/Rocket.Chat/assets/55659698/6325b61d-bb10-4532-8711-1151ea174e95)

**After:**

[screen-capture (2).webm](https://github.com/RocketChat/Rocket.Chat/assets/55659698/ce6d182d-073b-4407-aeb2-22a46adf48b3)

**Comment by dougfabris** [comment]
@ABHAYJAIN2601 would be better to check if it is a valid URL and just change the profile picture if it is valid, if not we should display a toast error message

**Comment by apurb-coder** [comment]
@dougfabris , Is this okey?

[screen-capture (3).webm](https://github.com/RocketChat/Rocket.Chat/assets/55659698/6329ce1a-78b0-4796-ab88-2ea10e122b97)

**Comment by dougfabris** [comment]
@apurb-coder seems great, raise a PR 🚀

**Comment by apurb-coder** [comment]
Hey, @dougfabris , can Please check PR: https://github.com/RocketChat/Rocket.Chat/pull/31467
