### ISSUE TITLE
How to update Rocket chat version without any lose?

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#2103]
I am in need to update "version": "0.14.0" to "version": "0.16.1"? by manually with out any lose?

**Comment by k0nsl** [comment]
@sureshdba2003: it would be helpful to know _how_ you deployed your instance in order to give a reasonable answer to your question.

**Comment by sureshdba2003** [comment]
Deployed instance without docker

**Comment by sureshdba2003** [comment]
{
  "version": "0.14.0",
  "compile": {
    "date": "2016-02-01T03:06:22.019Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "linux",
    "osRelease": "3.13.0-32-generic",
    "totalMemmory": 6259113984,
    "freeMemmory": 5251227648,
    "cpus": 4
  },
  "commit": {
    "hash": "72a8b0ca4257eb9b08ccdb06871381469ad8c18b",
    "date": "Wed Jan 20 19:28:08 2016 -0200",
    "author": "Rodrigo Nascimento",
    "subject": "Bind starttls correctly"
  },
  "tag": "0.14.0",
  "branch": "develop",
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": false
  }
}

**Comment by k0nsl** [comment]
Backup your working instance, then I suppose a simple `git pull` is all you would need in order to get the latest code.

**Comment by sureshdba2003** [comment]
What are the instance have to backup? Mongo DB is enough & anything else to take?

**Comment by marceloschmidt** [comment]
Yes, MongoDB backup should be enough, as by default files are also saved on your database. Do a backup and update your code, either by downloading the new release, or by `git pull` if you cloned the repository.
