### ISSUE TITLE
Alert Box's overlap with background due to less background opacity 

### ISSUE THREAD

**Issue by endurance21** [RocketChat/Rocket.Chat#21037]
### Description:

When we copy the invite link , we usually get a alert box on the top to acknowlege us saying  "Copied to clipboad ", the problem is when there is a banner or some other element just behind that alert box , the alert box seems transparent and the content on it seems mixed with content behind it.

### Steps to reproduce:

1. Go to any channel 
2. Go to Members section 
3. click on `Invite Link` 
4. click on copy icon 
5. bug shall be discovered if there is another banner present like " Enter you E2E password banner"
### Expected behavior:
I think the background opacity of alert boxes must be 1 , so that it wont seem to overlapping content beneath them.
### Actual behavior:
Alert Box is overlapping with content(banner)  beneath it.
![Screenshot from 2021-03-08 19-22-29](https://user-images.githubusercontent.com/43696525/110330360-adaea480-8043-11eb-82c9-5adaa601778b.png)
 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 3.12.0
- Operating System:Pop-os

### Additional context
WEB UI

**Comment by endurance21** [comment]
as i was using live website , i was not able to retrieve the server info!

**Comment by endurance21** [comment]
Also i would like to work on this

**Comment by endurance21** [comment]
@Sing-Li can I raise a pr for this ?

**Comment by Sing-Li** [comment]
@endurance21   this is by design.  Thanks.
