### ISSUE TITLE
File Upload using GridFS on Snap install 3.12.1 doesn't work anymore

### ISSUE THREAD

**Issue by Nono-m0le** [RocketChat/Rocket.Chat#21042]
### Description:

- It's not possible to download file uploded BEFORE 3.12.1
- It's not possible to upload file since (auto) installation of 3.12.1

### Steps to reproduce:

1. try to upload a file by using drag-and-drop
2. Get 'error empty file'
3. Try to upload a file from the "+" then "From computer", 
4. Got the file uploaded (at least, the progress bar) but the download link is wrong (at least, the server port is missing)
5. Try do download a previously uploaded file
6. Got a new instance of browser openning an empty page (no error 404)

### Expected behavior:

Be able to upload & download files.

### Actual behavior:

During upload *using drag-and-drop*:
![image](https://user-images.githubusercontent.com/3726435/110470525-3f1d2580-80db-11eb-8229-be3964c9a9aa.png)

During upload using the menu "+ / From computer", the file is uploaded, but download link is wrong.
=> the link point to the good server name but without port. Adding the port manually help to download the file.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: 3.11.1
- Operating System: Windows 10

**Comment by Nono-m0le** [comment]
Our Site URL didn't include the port (as managed by Caddy)
We fixed it by adding a `.env` file in `/var/snap/rocketchat-server/common` as suggested by the [documentation](https://docs.rocket.chat/guides/administrator-guides/troubleshooting)

**Comment by marcuszani** [comment]
Not only in the gridfs, but also with filesystem, the uploaded files are no longer accessible.

In my case it occurred after upgrading from version 3.11.2 to 3.12.1

**Comment by Nono-m0le** [comment]
Feel free to reopen a ticket, for me the issue was the missing port.
