### ISSUE TITLE
WebDav [undefined] Error on Upload from NextCloud 

### ISSUE THREAD

**Issue by falkiy** [RocketChat/Rocket.Chat#21045]
### Description:

[undefined] - Error on Upload from Nextcloud 

### Steps to reproduce:

Enable webdav
Config Webdav
Check config, username password and URL 
Choose File and try Upload to chat

### Expected behavior:

Upload File from Nextcloud-WebDav Location

### Actual behavior:

Mar 09 15:52:02  rocketchat[471]: Exception while invoking method ufsCreate TypeError: Cannot read property 'rid' of undefined
Mar 09 15:52:02 rocketchat[471]:     at Filter.validateFileUpload [as onCheck] (app/file-upload/server/lib/FileUpload.js:62:24)
Mar 09 15:52:02 rocketchat[471]:     at Filter.check (packages/jalik:ufs/ufs-filter.js:107:51)
Mar 09 15:52:02 rocketchat[471]:     at MethodInvocation.ufsCreate (packages/jalik:ufs/ufs-methods.js:155:12)
Mar 09 15:52:02 rocketchat[471]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Mar 09 15:52:02 rocketchat[471]:     at packages/ddp-server/livedata_server.js:1689:15
Mar 09 15:52:02 rocketchat[471]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Mar 09 15:52:02 rocketchat[471]:     at packages/ddp-server/livedata_server.js:1687:36
Mar 09 15:52:02 rocketchat[471]:     at new Promise (<anonymous>)
Mar 09 15:52:02 rocketchat[471]:     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
Mar 09 15:52:02 rocketchat[471]:     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
Mar 09 15:52:02 rocketchat[471]:     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Mar 09 15:52:02 rocketchat[471]:     at Object.post (app/api/server/v1/misc.js:263:26)
Mar 09 15:52:02 rocketchat[471]:     at app/api/server/api.js:394:82
Mar 09 15:52:02 rocketchat[471]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Mar 09 15:52:02 rocketchat[471]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Mar 09 15:52:02 rocketchat[471]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Mar 09 15:52:02 rocketchat[471]:     at packages/nimble_restivus/lib/route.coffee:59:33
Mar 09 15:52:02 rocketchat[471]:     at packages/simple_json-routes.js:98:9
Mar 09 15:52:02 rocketchat[471]:  => awaited here:
Mar 09 15:52:02 rocketchat[471]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Mar 09 15:52:02 rocketchat[471]:     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
Mar 09 15:52:02 rocketchat[471]:     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
Mar 09 15:52:02 rocketchat[471]:     at Object.post (app/api/server/v1/misc.js:263:26)
Mar 09 15:52:02 rocketchat[471]:     at app/api/server/api.js:394:82
Mar 09 15:52:02 rocketchat[471]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Mar 09 15:52:02 rocketchat[471]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
Mar 09 15:52:02 rocketchat[471]:     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
Mar 09 15:52:02 rocketchat[471]:     at packages/nimble_restivus/lib/route.coffee:59:33
Mar 09 15:52:02 rocketchat[471]:     at packages/simple_json-routes.js:98:9

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Debian 10 64bit
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4  - x64
- MongoDB Version: 4.4.4
- NextCloud 20.0.5.2

### Client Setup Information

- Desktop App or Browser Version: appears in Firefox and Chrome
- Operating System: Debian 10

Thank You!

**Comment by thomsenle** [comment]
Seems like the same problem 
https://github.com/RocketChat/Rocket.Chat/issues/20939
