### ISSUE TITLE
Oauth based users cannot delete their accounts

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#21043]
### Description:

Users are requested to type in their username in their own account deletion dialog under the profile.

Account name is not accepted, and password is required instead.

Oauth / OpenID Connect and SAML based users cannot delete their accounts because the password is not provided as by design in these authentication and provisioning methods.

### Steps to reproduce:

1. Log in as normal user with Oauth based account
2. Go to under your profile
3. Try to delete your account

### Expected behavior:

User is requested to type in their account name. After typing their account name the account is deleted.

### Actual behavior:

User is shown with field that looks like (and actually is) meant for password. Using password with locally generated account works, but it is not possible with Oauth or SAML derived ones. Latter would require typing in username instead of password.

When typing in username
![Screenshot from 2021-03-09 14-48-50](https://user-images.githubusercontent.com/6958942/110472981-b1dfce00-80e6-11eb-998b-a5e0accd90c6.png)

it is considered invalid
![Screenshot from 2021-03-09 14-49-11](https://user-images.githubusercontent.com/6958942/110472997-b6a48200-80e6-11eb-9b05-2fdd8da797d4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox

### Additional context
-

### Relevant logs:
-

**Comment by sampaiodiego** [comment]
fixed by https://github.com/RocketChat/Rocket.Chat/pull/21119
