### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by petschni** [RocketChat/Rocket.Chat#21049]
### Description:

In our Rocket.Chat instance push notifications are not working. When testing push notifications using the admin UI I get the error "Not allowed" - although I have admin rights. 

### Steps to reproduce:

1. Administration
2. Push
3. Send a test push to my user

### Expected behavior:

Would expect to send a push notification to my mobile device

### Actual behavior:

I get the a modal with "Not allowed" 

<img width="328" alt="Screenshot 2021-03-09 at 20 45 45" src="https://user-images.githubusercontent.com/4078440/110528477-7b22ab80-8118-11eb-862c-40d3f7ea44d9.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Debian GNU/Linux 10 (buster)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  mmapv1 (oplog Enabled)
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.13-83-gcf49ae8 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.0.7
- Operating System: Mac OS 11.1

### Relevant logs:

No error output in the browser console.

Server logs
```
I20210309-20:47:01.987(1) Exception while invoking method push_test Error: Not allowed [error-not-allowed]     at MethodInvocation.push_test (server/lib/pushConfig.js:21:10)     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:76:34)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9  => awaited here:     at Promise.await (/usr/home/plausch/software/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

**Comment by ankar84** [comment]
Tell more about your environment.
Do you use official mobile apps or your own whitelabeled apps?
Do you use Push Gateway? Did you enabled Push in Admin UI?

**Comment by petschni** [comment]
@ankar84 sorry - forgot the obvious. We are using the official mobile app and your gateway. Config see below. It used to work in the past but I cannot tell if it broke with an update or "just sometime". 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/4078440/110592438-91615380-817a-11eb-9c95-3d12bb2dd20a.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/4078440/110592474-9c1be880-817a-11eb-82d3-ddd958c6c5b7.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/4078440/110592488-a211c980-817a-11eb-88d6-b8400246d32c.png">

**Comment by ankar84** [comment]
> We are using the official mobile app and your gateway. Config see below. It used to work in the past but I cannot tell if it broke with an update or "just sometime".

Yeap, that case should work, but it's not working for some reason.
I think someone like @geekgonecrazy from cloud team can help.

**Comment by petschni** [comment]
@geekgonecrazy any idea what the problem could be?

**Comment by geekgonecrazy** [comment]
If you had an http error or something I'd say it was the gateway.  But that exception alone doesn't give me enough context.  

As is I'd say some how your user doesn't have permission to execute the call.  But if admin that doesn't make sense unless you took one of your permissions away in permission manager

**Comment by petschni** [comment]
> If you had an http error or something I'd say it was the gateway. But that exception alone doesn't give me enough context.
> 
> As is I'd say some how your user doesn't have permission to execute the call. But if admin that doesn't make sense unless you took one of your permissions away in permission manager

I eventually got it fixed. After re-enabling push again it still did not work but one day later it did. So issue can be closed.
