### ISSUE TITLE
LDAP login with username or email. Display Name should be "first name last name"

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#2105]
Is it possible to use username or email from LDAP to login and have rocket.chat display the first name and last name stored in LDAP as username in all chats? 

Currently we have our users login in with "first name space last name" in the username field to achieve the correct display of the name. We would like to change this so the users can use either their username (which is an abbreviation) or email to login and keep the visual display of the display name  as first name.lastname

Thanks in advance!

**Comment by marceloschmidt** [comment]
Duplicate: #324
