### ISSUE TITLE
Updating Struggles Version 0.9.0 to 0.15.0

### ISSUE THREAD

**Issue by ahosking** [RocketChat/Rocket.Chat#2106]
Once getting all dependencies updated and getting the new source I hit a constant string of issues.

We have LDAP enabled.
When I tried to log into the server it crashed with an address error from event.js.
I fixed this issue by locating the migration in the DB and setting the locked value to false.
Once I had done that I could login with my LDAP credentials, but no admin access was available.
So I abstracted the documentation for adding the first admin user by applying the permissions to my LDAP user. Either the 0.9.0 database does not follow the documentation, or the upgrade to 0.15.0 is off. Regardless, I adapted to fit the schema that I was seeing and I could log in as Admin.

Once logged back in, none of my channels were still open, I had to rejoin each one. There were also no other users in the UI, despite them still being in the database.
Once they logged in, it seemed to re-connect some things. For example I could send direct messages to 20% of the people on our network. The other 80% would load the message history but I couldn't interact with them - the send message box wouldn't even load (both browser and electron app).

Further to that, it broke all of our existing integrations, despite maintaining the same url, a hook would fail for "violation of protocol".

Is there a better way to go about updating/upgrading without having to start fresh and to avoid the issues I mentioned above?

Thanks!

**Comment by engelgabriel** [comment]
Can you try updating to 0.16.0?

**Comment by engelgabriel** [comment]
Looks like the migration process didn't complete.From the version 0.16.0 onwards, the server will refuse to start if the migration had a problem. The previous default behaviors allowed for inconsistency that would break a lot of things silently.

**Comment by ahosking** [comment]
Thanks, I'll give that a try now and let you know!

**Comment by ahosking** [comment]
Wonderful, that did it!

Now, to sort out my CSS changes :+1:
