### ISSUE TITLE
[UI] Message Box icons don't have hover effect.

### ISSUE THREAD

**Issue by apurv-1** [RocketChat/Rocket.Chat#21068]
### Description:

If the user hovers over icons like Emoji picker or microphone or '+' icon, the cursor changes to pointer but the icon color remains the same.

### Steps to reproduce:

1. Open any room, and Try hovering over any of the mentioned icons.

### Expected behavior:

We can add a hover effect for changing the colour of the icon.

### Actual behavior:

Only cursor changes to pointer.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System:  linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 88.0
- Operating System: Windows 10

### Additional context

https://user-images.githubusercontent.com/53378650/110704844-8b6f7f00-821b-11eb-828a-753fe9d81027.mp4

**Comment by maansiii** [comment]
Use Font Awesome <i class="fas fa-plus"></i> and add this to your html element.

**Comment by maansiii** [comment]
<i class="fas fa-plus"></i>

**Comment by maansiii** [comment]
`<i class="fas fa-plus"></i>`

**Comment by apurv-1** [comment]
@maansiii You can check the PR I've mentioned in this issue. 
And if you think you have a better solution. Please go ahead and open a new PR for this. 😄

**Comment by Vishv07** [comment]
@apurv-1 can I work upon this?

**Comment by apurv-1** [comment]
I've already opened a PR and mentioned it, But if you have a better solution please go ahead! @Vishv07 .
