### ISSUE TITLE
pdf preview not working in snap 3.12.1

### ISSUE THREAD

**Issue by OneTwoBarbecue** [RocketChat/Rocket.Chat#21075]
### Description:

pdf preview of first page is not rendered at all. 

I guess this is due to the fact that there is a typo in the link generated by Rocket.Chat.
When hovering over the pdf-filename in the chat the ending of the filename is donwload instead of download which is probably not intended.

### Steps to reproduce:

1. Upload pdf-file to chat.
2. No pdf preview generated.

### Expected behavior:

pdf-preview should be generated correctly.

### Actual behavior:

pdf preview not generated.

### Server Setup Information:
* Version of Rocket.Chat Server: 3.10.5 snap
*Operating System: Debian 10 Buster
* Deployment Method: snap with LDAP
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* NodeJS Version: 12.18.4
* MongoDB Version: 3.6.14

### Client Setup Information
* Desktop App or Browser Version: 3.0.1
* Operating System: Ubuntu 20.04
* tested with up-to-date Vivaldi and Firefox and apps

### Additional context

I would kindly like to ask for a possibility to view pdf-files directly in Rocket.Chat which perhaps could be added to a wishlist for further versions.

Kind regards, 

  Marco

**Comment by aditya-mitra** [comment]
Hello @OneTwoBarbecue ,
Actually PDF Preview is disabled - [Known Issue#attachment-pdf-preview-is-no-longer-being-rendered](https://github.com/RocketChat/Rocket.Chat/blob/develop/KNOWN_ISSUES.md#attachment-pdf-preview-is-no-longer-being-rendered)
Also you can check PR #12632.
However, I will surely fix the spelling of `download`. Thanks for pointing that out :smile: 
Thank you.

**Comment by OneTwoBarbecue** [comment]
Hello @aditya-mitra ,
ok! Thanks for pointing that out. So I'll close this issue :)
Do you know if there are plans to fully integrate a pdf-viewer like pdf.js into Rocket.Chat?
Kind regards, Marco

**Comment by aditya-mitra** [comment]
Actually they were integrated in Rocket.Chat in #10519, until they were removed in #12375 and #12632 because they made the client slow and laggy. 
However, I will surely try to find out a way which can render the PDF effectively with minimal impact on performance. :D
