### ISSUE TITLE
Tab autocompletion is wrong in private groups

### ISSUE THREAD

**Issue by patoupatou** [RocketChat/Rocket.Chat#2107]
The tab completion works fine in private groups with me not having to add the @ (just like on irc), for instance, completing the name @george works with typing geo<tab> if he's online.

Let's say I have myself, @george and @Timmy in my private group, and @Sonia is on the server but not in that private group. George is online, Timmy is away and Sonia is away. Why does typing Ti<tab> autocompletes to @Sonia ? First of all, she's not on the group, so imo autocompletion should only work with people that are in the private group (just like irc channels). Secondly, Why didn't it autocomplete to Timmy first? 

I think I can understand autocompleting to everybody because it's easier to /invite people, but sometimes it just seems completely broken when you're only typing to someone. Would it be possible to have the global autocomplete with the /invite command, and only local autocomplete with any other command (or none at all)?

p.s Thank you guys for developing rocket.chat, it's been awesome for our team so far.

**Comment by engelgabriel** [comment]
The new version of the autocomplete prioritises users in the rooms and in order of last participation. Just typr @ and you will see.
