### ISSUE TITLE
Feature Idea / Request

### ISSUE THREAD

**Issue by bmcgonag** [RocketChat/Rocket.Chat#2108]
Ability to assign roles / sub-groups with managers / admins only capable of modifying channels / groups / users within that sub-group.  

A hierarchical structure to Users, Roles, Groups, and so on.  

This creates the ability to host a single Rocket Chat instance across a large, diverse group where not all members / groups need to interact, but some do.   Allows a Full admin to generate 'spaces' for smaller group breakdowns and assign an admin to oversee that group, or a few smaller groups only.

**Comment by garg** [comment]
Is this similar to the request for teams - #630 and #658 ?

**Comment by bmcgonag** [comment]
So, checked those two links, and not sure.  Would either of those options allow a sub-group and it's users to still access a globally (across all sub-groups) created channel for chat?

So, I'm in Group A, and you're in Group B.  Both private groups.  I can't chat in B, and you can't chat in A.  But a full admin creates Channel G and makes it available to both Group A and B, and now you and I could chat in G. 

Is this the concept of either of those?  If, so, then yes that's my concept / idea, and we can close this one.

**Comment by marceloschmidt** [comment]
Yes, this is what we plan on doing sometime in the future. Closing in favor of duplicate #658.
