### ISSUE TITLE
inconsistent presence status

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat#21090]
### Description

Presence status for contact inconsistent. The status at the top of the chat does not match the (correct) status in the left panel.

In this example the user has been `Away` for a while and yet status in the chat is still showign as `Online`.

### Steps to reproduce:

Switch status and notice how the information goes out of sync.

### Expected behavior:

Status should always be consistent.

### Actual behavior:

<img width="510" alt="inconsistent presence" src="https://user-images.githubusercontent.com/5708172/110936288-f2cb2300-8330-11eb-9c50-57f79c71a96f.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: macOS
- Deployment Method: docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App 3.1.1
- Operating System: macOS 11.2.3

**Comment by Gummikavalier** [comment]
We are seeing this too. Status in the topic field seems to get stuck while the one in the contact/channel-list updates correctly.

**Comment by mmgoilf** [comment]
Same problem for us.

**Comment by Gummikavalier** [comment]
This issue has been reported also here:
https://github.com/RocketChat/Rocket.Chat/issues/20957

**Comment by foss-** [comment]
Thanks closing as dupe.
