### ISSUE TITLE
The toolbar to format messages is not very accessible

### ISSUE THREAD

**Issue by PiyushDhamane** [RocketChat/Rocket.Chat#21108]
### Steps to reproduce:

1. Open any room and check the icons used for formatting text. 

### Expected behavior:

We can make the icons/options more easier to spot. Placeholder for the text area can be changed and the noticeable transitions can be added to easily spot. 

### Actual behavior:

The icon size is too small to spot for a new user. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Windows10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome 88.0
- Operating System:Windows 10

**Comment by ggazzo** [comment]
I closed your PR because we have a design for that, the implementation should follow the design. I will mark the design team here, but I dont think this is a real problem
