### ISSUE TITLE
Outgoing webhook is broken

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2110]
Recent test with the xmpp gateway worked only with incoming webhooks, outgoing did not fire.

Also our own `tutum list` no longer works.

**Comment by rodrigok** [comment]
@Sing-Li what is your problem with outgoing hooks?

There is a problem when you try to use an outgoing hook for a public channel that will be fixed via https://github.com/RocketChat/Rocket.Chat/pull/2120?ts=2

The problem with `tutum list` is just configuration, Gabriel changed the api url.

**Comment by engelgabriel** [comment]
I changed the api from  `instance/api` to `deployment/api` .. it is now updated on the webhook.

**Comment by Sing-Li** [comment]
@rodrigok  Thanks :smile:    I have switched the testing to a private channel for now.    In the public #xmpp_gateway channel , it just did not fire - and then completely locked up the channel.

**Comment by Sing-Li** [comment]
Outgoing now works on public channels.
