### ISSUE TITLE
[BUG]Notifications preferences doesn't appear of the discussions when opened from main chat room. 

### ISSUE THREAD

**Issue by sauravrajleaf** [RocketChat/Rocket.Chat#21102]
### Description:
Notifications prefrences not showing when opened from the discussions option from the main chat.

### Steps to reproduce:

1.  Go to https://open.rocket.chat
2.  Open any channel which contains discussion threads.
3.  Open the discussion threads from the main channel.
4. Click on notifications preferences of the discussion thread.

### Expected behavior:
Notifications preferences should appear.

### Actual behavior:
Notifications preferences doesn't appear.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Ubuntu Os 20.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Google Chrome  89.0.4389.82 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.2.0 LTS

https://user-images.githubusercontent.com/52833031/111028518-24b9b380-841d-11eb-9618-c2af24880ed5.mp4

**Comment by endurance21** [comment]
actually the `subscription` variable comes out to be undefined sometimes here https://github.com/RocketChat/Rocket.Chat/blob/978cd3a845b01a164e5b9fd7b82ad41d9a3ef4c8/client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.js#L66

maybe we need to make a check here to this undefined variable

**Comment by endurance21** [comment]
@KevLehman  any thoughts on this

**Comment by Darshilp326** [comment]
@endurance21 Were you able to reproduce on our localhost server?

**Comment by endurance21** [comment]
yes i did

**Comment by Darshilp326** [comment]
Can you share your video as I was not able to reproduce :cry:

**Comment by endurance21** [comment]
yea thats not very consistent , not every time it happens 
that is due to undefined behavour of subsription variable( i have checked this by using chrome breakpoints )
let me see if i can make one !

**Comment by lovesh12** [comment]
#21118 I've created a new issue containing the actual reproducing steps
