### ISSUE TITLE
Incomplete Email Validation 

### ISSUE THREAD

**Issue by Deepak-learner** [RocketChat/Rocket.Chat#21109]
### Description:

In rocket chat app , Email validation is wrong at all places . Email validation should be present and email must contain " . "(dot) and "@" in email field  with valid email address format . For valid email address format , visit this site : https://help.xmatters.com/ondemand/trial/valid_email_format.htm#:~:text=A%20valid%20email%20address%20consists,com%22%20is%20the%20email%20domain.

For example , below I have attached an image  of “new contact form” in "Omnichannel Contact Center" section , here email is not valid (as " . " is not included in email), then also it showing email is valid and adding new user to contact list .

### Steps to reproduce:

1. Go to "Omnichannel Contact Center" section and click "new contact '' button . 
2. Enter email without "."(dot)  in email text box.

### Expected behavior:

Email should be validated.

### Actual behavior:

Email is not validated .

### Server Setup Information:

Version of Rocket.Chat Server: 3.12.1
Operating System: Ubuntu
Deployment Method:
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version: v14.16.0
MongoDB Version: 4.4.3

### Client Setup Information

Desktop App or Browser Version: Chrome version 87
Operating System: Ubuntu

### Additional context

<img width="503" alt="Screenshot 2021-03-14 at 11 53 45 PM" src="https://user-images.githubusercontent.com/56799414/111080280-c0354c00-8523-11eb-8336-bf95125e0419.png">
Blue boundary colour of email text box show email is valid , but “ . “ is not included in email.

<img width="983" alt="Screenshot 2021-03-14 at 11 55 19 PM" src="https://user-images.githubusercontent.com/56799414/111080300-d4794900-8523-11eb-9582-e9ecdedc3e2b.png">
Once I click on "save" button in new contact form following details with invalid email is added to contact list .

**Comment by endurance21** [comment]
The regex being used here itself has this behavior. https://github.com/RocketChat/Rocket.Chat/blob/978cd3a845b01a164e5b9fd7b82ad41d9a3ef4c8/app/lib/server/lib/validateEmailDomain.js#L35
it matched for a email like ` rocket@chat` !

@KevLehman @Sing-Li  is this intentional to have domains without "." ?

**Comment by endurance21** [comment]
@Deepak-learner i just found out , the email addresses of format`example@localhost` is a valid type !
please have a look here https://en.wikipedia.org/wiki/Email_address#Examples .
