### ISSUE TITLE
Options doesn't disappear after clicking the 3 dots twice

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Rocket.Chat#21112]
### Description:

In any application, generally, 3 dots are provided for opening options, but when we click those dots again, the options dialog disappears, But it is not the case with Rocket.Chat

### Steps to reproduce:

1. Open any channel and click on the 3 dots on the top-right corner
2. You get an options box, and now again click on the three dots

### Expected behavior:
Upon clicking the 3 dots again, the options box should disappear, but it happens when we click somewhere else on the screen

### Actual behavior:
Options Box doesn't disappear
[Video](https://drive.google.com/file/d/19hHwfewQnwD2wj6Acz7XoXcrABPG7p6J/view)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Windows10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Edge Version 89.0.774.50
- Operating System: Windows 10

**Comment by ABHAYJAIN2601** [comment]
Hey @ak2783934 I think this [PR](https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/389#issue-564124356) will fix this issue

**Comment by ak2783934** [comment]
Yup, But I couldn't find any issue related to this 😅

**Comment by ak2783934** [comment]
@ABHAYJAIN2601 I am a little confused about how that repository will affect this one? I read somewhere that this repo contains the full system for rocket chat web client and server?
