### ISSUE TITLE
[BUG] Notifications preferences doesn't appear when user is not joined

### ISSUE THREAD

**Issue by lovesh12** [RocketChat/Rocket.Chat#21118]
### Description:
Notifications preferences doesn't appear when user is not joined, it shows blank white screen

### Steps to reproduce:
1. Go to a public channel or discussion link (make sure **you are not joined in it**, actually you need to message to join it) 
2. Click on Notification Preferences
3. It will show blank screen along with error in console

### Expected behavior:

Notifications Preferences tab should appear stating that user is not joined

### Actual behavior:

A blank screen appears and Notifications Preferences tab is not opened and there is an error in console

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Ubuntu 20
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 89.0.4389.82 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.2.0 LTS / Windows

### Additional context

Yes, basically it **happens when we open notification preferences tab of channel/discussion that we are NOT joined to.**
It is completely fine with the channels/discussions that we are joined in.

### Relevant logs:

#21120

**Comment by aswinidev** [comment]
I think this issue is fixed @dudanogueira please close this
