### ISSUE TITLE
Unexpected arrow with no use in https://open.rocket.chat/account/preferences sound tab besides the slider

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Rocket.Chat#21113]
### Description:
There is an unexpected arrow after the slider, where the percentage of the volume is shown in preferences under account 

### Steps to reproduce:

1. Login with the account, open profile, and then preferences 
2. go down and click on the sound option
3. besides the slider, there is a left arrow that doesn't disappear or do anything on sliding the slider

### Expected behavior:
That arrow looks unexpected there with no use

### Actual behavior:
Here is a video showing the arrow [Video](https://drive.google.com/file/d/1o63Kpf_bd0iuzUN84pFbMKaDEtApmJn2/view)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Windows10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Edge Version 89.0.774.50
- Operating System: Windows 10

**Comment by ABHAYJAIN2601** [comment]
Hello! @ak2783934 [ #20310](https://github.com/RocketChat/Rocket.Chat/pull/20310) will fixes the issue.
