### ISSUE TITLE
Sidebar doesn't disappear upon selecting in mobile view

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Rocket.Chat#21111]
### Description:

When we go on the mobile version of the web-app and select any channel after selecting clicking the hamburger, the side bar doesn't disappear

### Steps to reproduce:

1.  Set the view to mobile view using developers tool
2. Click on the hamburger sign and select any channel
3. After selecting the channel, the sidebar will not disappear

### Expected behavior:

It should have gone after selecting a channel and showed us the channel

### Actual behavior:

[video](https://drive.google.com/file/d/1GQ__UOsw-TK6KqBCIKFYs2oNsNX8QhPM/view?usp=sharing)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Windows10 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 - x64 
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Edge Version 89.0.774.50
- Operating System: Windows 10

**Comment by Jackent2B** [comment]
@ak2783934 I would like to work on it

**Comment by ak2783934** [comment]
@Jackent2B sure go-ahead

**Comment by jrgong420** [comment]
Same consistent issue here on iframe on all browsers that I tried with: Chrome, native app and in iframe embed. On MacOS and Android

**Comment by Kalpana200** [comment]
@ak2783934 Sir, I would like to work on it.
