### ISSUE TITLE
User info shows username instead of full name

### ISSUE THREAD

**Issue by billynoah** [RocketChat/Rocket.Chat#21129]
### Description:

The “Full Name” that’s shown when clicking “View Profile” on a user in a channel shows only their *username* instead of their *full name.* The correct full name is shown in the admin panel user info but not on the user front end.

I have tested or verified this in both the desktop app and the web ui.

### Steps to reproduce:

1. Click on a username in a channel
2. Click "See full profile"
3. A panel opens called "User Info".  Under "Full Name" it shows the username instead of the full name.

### Expected behavior:

The "*Full Name*" section should show the user's *full name*.

### Actual behavior:

The "*Full Name*" section wrongly shows the user's *username*.

![Screen Shot 2021-03-15 at 4 12 18 PM](https://user-images.githubusercontent.com/3309911/111222429-32ed0880-85b2-11eb-86a4-f87d31536394.png)

And here is a view of the same user from the admin panel which shows the correct *full name*:

![Screen Shot 2021-03-15 at 4 14 46 PM](https://user-images.githubusercontent.com/3309911/111223635-cbd05380-85b3-11eb-99fc-4adf00c8b812.png)

### Server Setup Information:

- Rocketchat Version 3.12.1
- Ubuntu 20.04
- Installed via snaps
- Desktop App v3.1.1 / All Browsers

### Version of Rocket.Chat Server

- Rocketchat Version 3.12.1

### Client Setup Information

- All browsers
- OS X / Windows 10

**Comment by Darshilp326** [comment]
@billynoah Hello! You need to turn ON the setting 'UI_Use_Real_Name' for displaying real names instead of usernames.

**Comment by billynoah** [comment]
@Darshilp326 - Where do I find this setting?

**Comment by shrinish123** [comment]
@Darshilp326 after looking at the code even I felt that there has to a setting to show real names, but not able to find it.

**Comment by Darshilp326** [comment]
@billynoah @shrinish123 Administration->Layout->User Interface

**Comment by Darshilp326** [comment]
@billynoah But sadly code is implemented by using this setting :disappointed:

**Comment by billynoah** [comment]
I see what you mean - in /client/views/room/contextualBar/UserInfo/index.js:

    name: showRealNames ? name : username

That really seems like the wrong use of that setting to me.  I'd propose we either need another setting or simply change the code to:

    name: name

It's nonsensical to display the username under "full name" since that's clearly not what it is.

**Comment by Darshilp326** [comment]
@dougfabris Can you look into this issue?

**Comment by yash-rajpal** [comment]
I feel like we should always show real names under `full names` section.

**Comment by WYGIN** [comment]
@dudanogueira looks like this issue has been resolved can you please check once and close this issue. Thanks you
![Screenshot_20230128-120048](https://user-images.githubusercontent.com/107541780/215250714-d5d9548e-fada-4f39-8c12-28c68ab1c407.png)

**Comment by WYGIN** [comment]
if not, in any case (if i am wrong) , i want to work on this issue, but looks like solved when i test this issue with open.rocket.chat

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
