### ISSUE TITLE
[Bug] Users self chat are duplicated

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#21138]
### Description:

User chat with himself (if it enabled in Admin UI) somehow duplicated with different entities.

### Steps to reproduce:

1. Enable **Admin UI - Message - Allow user direct messages to yourself** option
![image](https://user-images.githubusercontent.com/4023037/111302026-efeb6d80-8663-11eb-8637-df78a1a176f8.png)

2. Find your own user and chat with him
3. Somehow create another such chat

### Expected behavior:

Only one chat with myself should be.

### Actual behavior:

One chat looks correct - _id and _id - https://open.rocket.chat/direct/QcG3vkkEbdBYxrXeQQcG3vkkEbdBYxrXeQ
I think my internal _id at open server is `QcG3vkkEbdBYxrXeQ`
But second chat is strange - https://open.rocket.chat/direct/3azjkJqr86ZCvXpTc
![image](https://user-images.githubusercontent.com/4023037/111301575-6f2c7180-8663-11eb-9bac-d32a734bcbcf.png)
And statuses a really broken
Chant are different with different content.
![image](https://user-images.githubusercontent.com/4023037/111306987-ee24a880-8669-11eb-9fb7-46b89a133abe.png)
![image](https://user-images.githubusercontent.com/4023037/111307041-00064b80-866a-11eb-94bc-31483edbae92.png)

I have same bug on my server too
![image](https://user-images.githubusercontent.com/4023037/111301674-8b301300-8663-11eb-9930-e54e055446aa.png)
Correct - `https://rc.company.ru/direct/iodE4TwMg4i729GoHiodE4TwMg4i729GoH` My id is `iodE4TwMg4i729GoH`
Error - `https://rc.company.ru/direct/6tBbgFj6eHzyPs5Pn`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1 (and open.rocket.chat have that bug too)
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Chrome 89
- Operating System: Windows 10

### Additional context

I have that bug on my server on 3.7.1 but also on open.rocket.chat with 3.12.1 server version

### Relevant logs:
No

**Comment by shrinish123** [comment]
@ankar84  how do we create a duplicate chat with yourself, because after trying various ways to do it I am not able to create a duplicate chat

**Comment by ankar84** [comment]
> @ankar84  how do we create a duplicate chat with yourself, because after trying various ways to do it I am not able to create a duplicate chat 

I don't actually know how this happened. But I did it on my server and open server and today one of my users did the same, so I decided to make that issue.

**Comment by fdellwing** [comment]
I also dont know how it happened, but I can confirm that it is possible. Having this for some months now.

I can confirm the strange ids, but avatar and status works for me.

**Comment by mikemkm** [comment]
Same situation on our server for at least six months (or even longer but don't remember when noticed it)
Right now on 3.12.0 server version.

**Comment by fdellwing** [comment]
I have just found something interesting. Can you click on the "user info" Button in the DM with the longer ID? For me some user that was disabled in the past *and* I had a PM with is shown there. The user info of the DM with the short ID shows my own data.

**Comment by ankar84** [comment]
> I have just found something interesting. Can you click on the "user info" Button in the DM with the longer ID? For me some user that was disabled in the past _and_ I had a PM with is shown there. The user info of the DM with the short ID shows my own data.

Indeed, you are right!
![image](https://user-images.githubusercontent.com/4023037/111589185-91de9780-87d5-11eb-8a24-4bc94ff2b349.png)
User info for  `kane-3` opened!
Actually I didn't have conversations with that users at all.
It could be the key for the reason of that bug.

On my own server both chats open my user info, which is a little strange.

**Comment by ankar84** [comment]
Maybe fixed by https://github.com/RocketChat/Rocket.Chat/pull/21451
