### ISSUE TITLE
[Enhancement] Hamburger icon doesn't appear for width value from 778 to 600 

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Rocket.Chat#21135]
### Description:
When the screen size is about 778, the sidebar automatically disappears, but then there should be a button to bring the sidebar when necessary, but that is not present.

### Steps to reproduce:

1. open dev tools after opening the app
2. select the width range between 778 to 600, 
3. There won't be any option to change channels because there is no sidebar

### Expected behavior:
There a hamburger was expected which will bring the sidebar so that we can change the channel or go to settings if needed. 

### Actual behavior:
![no hamburger available](https://user-images.githubusercontent.com/54025079/111255574-57da8d80-863d-11eb-9525-550dafc1d3a9.JPG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Windows10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 2.18.4 - x64
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: edge
- Operating System: windows 10

**Comment by Darshilp326** [comment]
#20736 Fixes the issue! :smile:

**Comment by ak2783934** [comment]
hmm thanks, I couldn't find that one.  😅
