### ISSUE TITLE
Flex bar /  people tab /  UI breaks when you click on member then close tab and open tab

### ISSUE THREAD

**Issue by mckuchta** [RocketChat/Rocket.Chat#2114]

**Comment by marceloschmidt** [comment]
Can you be more specific as to what it looks like? Or any other condition that triggers this error?

![flextab](https://cloud.githubusercontent.com/assets/1986378/12819357/e20c7750-cb41-11e5-9f40-aba40d7b0f5e.gif)

**Comment by mckuchta** [comment]
Strange... This is what i am getting

https://youtu.be/GDBNWWDb6z8

**Comment by mckuchta** [comment]
I created two more accounts and did some testing.  It turns out it only breaks on the groups that the user has created

**Comment by geekgonecrazy** [comment]
This shouldn't be happening any more.  Please let us know if otherwise
