### ISSUE TITLE
No delete button for any chat. Only hide button is present 

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Rocket.Chat#21151]
### Description:
There is no option for deleting any chat with someone if we want. There is a hide button and no option for directly retrieving chat after hiding it. 

### Steps to reproduce:

1. Open the website, and open a chat (dm) with someone
2. Click on the  3dots in the sidebar for that chat
3. only hide button is present

### Expected behavior:
There should be a delete button for every chat or dm. There should be another button somewhere, from where can retrieve the hidden chats. 

### Actual behavior:
No delete button, No unhide button

![WhatsApp Image 2021-03-17 at 8 53 54 AM (1)](https://user-images.githubusercontent.com/54025079/111410278-75236080-86fe-11eb-9591-a6c2d6a756d5.jpeg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop 
- Operating System: Windows 10 (WSL2)
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.21.0 - x64 
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/17927

**Comment by ak2783934** [comment]
okay, looks like a lot of discussions already happened. Thanks

**Comment by ankar84** [comment]
> looks like a lot of discussions already happened.

Yeah, that feature ask a lot of users indeed.
Telegram and WhatsApp have it.

**Comment by ak2783934** [comment]
yess
