### ISSUE TITLE
the last channel of search list on the sidebar is not properly visible 

### ISSUE THREAD

**Issue by shrinish123** [RocketChat/Rocket.Chat#21159]
### Steps to reproduce:

1. Create many channels 
2. Go to search in the sidebar
3. Check the last channel is not properly visible

### Expected behavior:

The last channel should be properly visble
### Actual behavior:

![searchlist](https://user-images.githubusercontent.com/56491104/111470172-91022300-874d-11eb-8d94-b05f0ca5f3ac.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13
- Operating System: Windows
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.x
- MongoDB Version: 4.x

### Client Setup Information

- Desktop App or Browser Version:Browser
- Operating System: Windows

**Comment by Darshilp326** [comment]
Duplicate of #20983

**Comment by shrinish123** [comment]
Should i close this issue ,but atleast we need to keep the pull request to fix this ?

**Comment by Darshilp326** [comment]
@shrinish123 Yes close this issue but keep the PR open!

**Comment by shrinish123** [comment]
Ok Thanks
