### ISSUE TITLE
Option to DM yourself

### ISSUE THREAD

**Issue by ak2783934** [RocketChat/Rocket.Chat#21153]
### Description:
Whenever we search our own name in the member's tab, we get ourselves and also get to dm

### Steps to reproduce:

1. Open the website 
2. Open any channel and go to the member's tab and type your userId
3. You will find yourself and after that, you will also get the option to dm

### Expected behavior:
Searching myself is fine but the option to DM shouldn't be there 

### Actual behavior:

https://user-images.githubusercontent.com/54025079/111415815-b0c32800-8708-11eb-9148-a8a200cf8a35.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Windows 10 (WSL2)
- Deployment Method:
- Number of Running Instances:
- DB Replicaset oplog:
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

**Comment by Darshilp326** [comment]
@ak2783934 Hello! This is not a bug!

**Comment by ankar84** [comment]
This is option **Allow user direct messages to yourself** in **Admin UI - Message**
Try to disable it and look what happened.

**Comment by ak2783934** [comment]
@Darshilp326  But what is the need for texting yourself. And after that, you also get an option to call/video call yourself. And this shouldn't be there right? If we can just remove that button, then the user will never reach there and there will be no option for him to call himself.

**Comment by ankar84** [comment]
> But what is the need for texting yourself.
It's like favorites in Telegram.

**Comment by ak2783934** [comment]
ok but what about the option we are getting? Should that be removed? 
![selfcall](https://user-images.githubusercontent.com/54025079/111419984-69409a00-8710-11eb-9f59-77add0cf808b.JPG)

**Comment by ankar84** [comment]
> ok but what about the option we are getting? Should that be removed?

I think it's not really important in Jitsi+RocketChat world and that buttons can remain there.
It's not a telephone call to yourself, which is a crazy thing. It's just creation of Jitsi call with certain name.

**Comment by fdellwing** [comment]
The option to DM yourself is really important for an admin that needs to debug things. So obviously it should not be removed. Also there is no need to arbitrary remove options from the self-DM, it would just create more code complexity and possible things that can break.

**Comment by Darshilp326** [comment]
@fdellwing I completely agree!

**Comment by adocampo** [comment]
If you don't like it, why simply don't disable *Allow user direct messages to yourself* in admin settings?

**Comment by ak2783934** [comment]
Okay Thanks.
