### ISSUE TITLE
Status in sidebar out of sync

### ISSUE THREAD

**Issue by grthr** [RocketChat/Rocket.Chat#21163]
### Description:

The users status in the sidebar is not updated and therefor out of sync with the status in the rooms or the user profile.

### Steps to reproduce:

1. Open chat in browser.
1. Wait for the status of a user to change.

### Expected behavior:

The status indicator in the statusbar is updated if the status of a user changes and is in sync with other status indicators of the same user.

### Actual behavior:

The status indicator at the top updates but the status indicator in the sidebar remains unchanged.
![image](https://user-images.githubusercontent.com/5175544/111492362-e4b84080-873c-11eb-8a41-93c94ab87bfa.png)

If I reload the page, the status is updated.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- I am just a user

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 89.0.4389.90
- Operating System: Windows 10 19043.899

**Comment by ankar84** [comment]
Indeed I saw that issue on open.rocket.chat recently

**Comment by ankar84** [comment]
Could be related to https://github.com/RocketChat/Rocket.Chat/issues/20957

**Comment by foss-** [comment]
Not related but a dupe.

**Comment by grthr** [comment]
Duplicate of #20957
