### ISSUE TITLE
The options of audio call and video to yourself are not working and are illogical

### ISSUE THREAD

**Issue by shrinish123** [RocketChat/Rocket.Chat#21170]
### Description:

We see the option of auio call and video call to our ownself and the buttons also dont work 

### Steps to reproduce:

1. Go to create dm with yourself
2. Go to user info 
3. Check the option to video call and audio call yourself

### Expected behavior:

These options should not be there as they are illogical

### Actual behavior:

![action_intial](https://user-images.githubusercontent.com/56491104/111551927-4ca37100-87a7-11eb-95a3-ec5110fe0a84.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0
- Operating System: Windows
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.x
- MongoDB Version:4.x

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Windows

**Comment by ankar84** [comment]
Please check yesterday discussion on that topic https://github.com/RocketChat/Rocket.Chat/issues/21153

**Comment by Darshilp326** [comment]
I think discussion was done in #21153

**Comment by shrinish123** [comment]
I checked the discussion now , but the point is the buttons are not working for me at least, so why to keep them ?

**Comment by yash-rajpal** [comment]
It can be useful for others @shrinish123 

Lets say you want to make a jitsi call and want to send its link to your friend, one easy way can be to open self's user info and create a call, without disturbing someone else for making a call.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases. 
The buttons are not shown on user info anymore.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
