### ISSUE TITLE
User creation: Password required even if set random password is selected

### ISSUE THREAD

**Issue by PierreBon** [RocketChat/Rocket.Chat#21179]
### Description:

On this RocketChat version, When trying to create a new user, we have an error and we need to fill ourself the password field event if "set random password and send by email" is select.

We didn't have this behavior before.

### Steps to reproduce:

1. Go to 'Administration'
2. Click on 'Users' 
3. Then click on 'New'
4. Fill the User Creation form
5. Select "set random password and send by email"
6. Leave "Password" field empty
7. Click on "Save"

### Expected behavior:

When "set random password and send by email" is selected, we don't need to fill the "Password" field

### Actual behavior:

Error message "The field password is required"
![image](https://user-images.githubusercontent.com/7646273/111602985-3069f900-87d4-11eb-833f-4c750a06cb0c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: both App and all browser
- Operating System: Windows 10

### Additional context

--
### Relevant logs:

--

**Comment by iamparasbansal** [comment]
I will like to work on this issue

**Comment by steschuser** [comment]
Any time frame  on this?

**Comment by Joshua2504** [comment]
Any update on this? When will it be fixed?

**Comment by fleaz** [comment]
Still broken in `3.13.2` :(

**Comment by Joshua2504** [comment]
Can this be fixed soon?

**Comment by ulope** [comment]
I really appreciate how difficult it is to run a big open source project with tons of user created issues.

But having said that functionality regressions like this (which by far isn't the first time BTW) just are not acceptable when you claim your product is an "enterprise ready" solution.

There need to be integration tests preventing this kind of thing and also a way to escalate issues.

**Comment by fleaz** [comment]
3.17.2 and it's still broken...

This is not some "nice to have feature", creating a user is core functionallity imho.

**Comment by fleaz** [comment]
4.2.2 and it's still broken...

This is becoming a ridiculous joke.
Why exactly am I paying money every month to a company that is not able to fix a form validation bug in nearly a year?

**Comment by milton-rucks** [comment]
Hi @fleaz 
This fix is scheduled to be delivered in the next release.
did you try to contact support?
Please note this is the appropriate channel for reporting an issue.

**Comment by fleaz** [comment]
> Hi @fleaz 
> This fix is scheduled to be delivered in the next release.
> did you try to contact support?
> Please note this is the appropriate channel for reporting an issue.
> 
> 

Thank you!

Yes, I already have an open support ticket since months where I occasionally release my anger just like in this issue here.

This issue is just one of many problems we have with RC since about 4 years now, so please excuse prior language :/

**Comment by yederlv** [comment]
Hello everyone, I would like to know if this case has been reviewed and solved.
