### ISSUE TITLE
Last login always shows never when viewing profile

### ISSUE THREAD

**Issue by PriyaBihani** [RocketChat/Rocket.Chat#21175]
### Description:
When we select a profile to view by clicking on "view full profile "  Last Login date is always set to never.

### Steps to reproduce:

<img width="1440" alt="Screenshot 2021-03-18 at 1 29 36 PM" src="https://user-images.githubusercontent.com/69837339/111592997-7da79400-87ef-11eb-82a2-a00996197e10.png">

1. Select someones profile
2. Click on view full profile
3. Last Login shows never

### Expected behavior:

Last login should show the last login time /date instead of never

**Comment by yash-rajpal** [comment]
#20923 would fix this issue.
