### ISSUE TITLE
Percent (%) symbols in hyperlinks are escaped again

### ISSUE THREAD

**Issue by lanphiergm** [RocketChat/Rocket.Chat#21184]
### Description:

When using the `[text](address)` syntax for specifying a link, if the address contains encoded characters, the percent symbol gets re-encoded so that, for example, `%20` becomes `%2520`.

### Steps to reproduce:

1. Post the following message in a Rocket.Chat channel:
    `[cool story](https://foaas.com/cool/my%20name)`
2. Click the "cool story" link
3. When the browser opens, note that the URL that you go to is
    https://foaas.com/cool/my%2520name

### Expected behavior:

Properly encoded characters like %20 that appear in a hyperlink are unaltered

### Actual behavior:

Properly encoded characters like %20 are being re-encoded to an invalid value

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Fedora release 32
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: desktop app version 3.1.1, chrome version 89.0.4389.82
- Operating System: Windows 10 build 1909

**Comment by PriyaBihani** [comment]
I'm working on it

**Comment by Kartik18g** [comment]
Something might be wrong with the markdown creation

**Comment by PriyaBihani** [comment]
@Kartik18g  You're right while generating markdown it doesn't check if the url is already encoded or not, i've added a check that ensures only the unencoded url's encode. My PR in progress.

**Comment by DanielEckl** [comment]
@PriyaBihani I saw your PR and I asked myself if this would fix my occurrence of this issue. My problem is a URL in this original form:
`https://my.test.url/test.py?argument=something_with%3Fencoded_question_mark`
Now when you first urldecode and then urlencode it, where literal question marks are not encoded as of now, I will most probably end with this form:
`https://my.test.url/test.py?argument=something_with?encoded_question_mark`

So this would still lead to a differently broken result in my case.
