### ISSUE TITLE
KaTeX is not working

### ISSUE THREAD

**Issue by rashad101** [RocketChat/Rocket.Chat#21188]
### Description:

KaTeX is not working. Cannot format math notations with KaTeX

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:
Version of Rocket.Chat Server: 3.12.1
Operating System: Ubuntu 16.04.6
Deployment Method: docker
Number of Running Instances:
DB Replicaset Oplog:
NodeJS Version: v12.18.04
MongoDB Version: v4.0.18

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by SimonBin** [comment]
This seems to be a priority conflict between katex and markdown

**Comment by rashad101** [comment]
> This seems to be a priority conflict between katex and markdown
> 
> related issuess: #17531 #16129

Thanks. The roblem got solved mostly by the using $$ tag
