### ISSUE TITLE
User options dots icon close improvement

### ISSUE THREAD

**Issue by KashyapPavra** [RocketChat/Rocket.Chat#21191]
### Description:

The dot icon to open options for any chat is currently closes if we click anywhere except on clicking the icon again, I think as a good user-experience the menu should also close when clicking the dots icons
### Steps to reproduce:

1. Go to the main website
2. Click on the 3 dots icon besides any user or channel, it opens a number of options 
3. Again click on the dots, it won't close the options
4. Click anywhere else, it will close the options

### Expected behavior:

The options menu should close the same 3 dots icon is clicked again

### Actual behavior:

The options menu does not close when the same 3 dots icon is clicked again, whereas it closes when clicked anywhere else

https://user-images.githubusercontent.com/22401926/111682138-06531e00-884a-11eb-85c5-7e808d108e17.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: macOS Big Sur version 11.2.1
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 15.7.0
- MongoDB Version:

### Client Setup Information

- Browser Version:
- Operating System: macOS Big Sur version 11.2.1

**Comment by Darshilp326** [comment]
@KashyapPavra Hello! Please go through #20968

**Comment by KashyapPavra** [comment]
@Darshilp326 Ohh sorry I must have missed this. Thanks.
