### ISSUE TITLE
[UI] Message Box, Pop over text don't have hover effect.

### ISSUE THREAD

**Issue by apurv-1** [RocketChat/Rocket.Chat#21196]
### Description:

If the user hovers over popover text, the cursor changes to pointer without any hover effect.

### Steps to reproduce:

1. Open any room.
2. Click on `+`.
3. The popover modal appears, try hovering over those.

### Expected behavior:

It should have some hover effect which matches UI.

### Actual behavior:

https://user-images.githubusercontent.com/53378650/111692181-29cf9600-8855-11eb-8741-6e3f7648cf8a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-production
- Operating System:
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome 88.0
- Operating System: Windows 10

**Comment by frankie-njie** [comment]
I am trying to work on something for the popup...and alternative to what @apurv-1 had done, but am I finding difficulties in finding the styles for the class = "rc-popover__column"

**Comment by apurv-1** [comment]
Hey @frankie-njie, Its in directory app/theme/client/imports/components/popover.css at line 58.
