### ISSUE TITLE
Unable to delete rocket.chat account

### ISSUE THREAD

**Issue by MikeScotty** [RocketChat/Rocket.Chat#21233]
### Description:

Whenever I try to delete my rocket.chat account it says invalid username, Even after I copied and pasted the correct username into the dialog.

### Steps to reproduce:

1. Go to My Account
2. Click on delete my account
3. Enter username

### Expected behavior:

Account is deleted

### Actual behavior:

It tells me that the username I entered is Invalid

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Linux
- Deployment Method: N/A
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: LinuxMint

### Additional context

I signed up using Github.

### Relevant logs:

None

**Comment by shrinish123** [comment]
hi @MikeScotty can you try doing the same by entering your password instead of username ? please tell me if that works

**Comment by MikeScotty** [comment]
@shrinish123 Umm... I signed up using Github, I don't have a password and am unable to create one.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
