### ISSUE TITLE
[BUG]Multi Select isn't working in Export Messages

### ISSUE THREAD

**Issue by PriyaBihani** [RocketChat/Rocket.Chat#21235]
### Description:

While exporting chat messages,  ' To Users ' field  was supposed to accept multiple user names but it was accepting just a single user name.

### Steps to reproduce:

1. Create a Private Channel and send some messages.
2. Click on export messages.
3. Select the users from user field.

### Expected behavior:

We should be able to select multiple users.

### Actual behavior:

https://user-images.githubusercontent.com/69837339/111951536-d0dc5800-8b09-11eb-8363-2f4f9cea8d91.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
