### ISSUE TITLE
Marketplace install Dialogflow error failed [500] 

### ISSUE THREAD

**Issue by APPX-Studio** [RocketChat/Rocket.Chat#21234]
### Description:

failed [500] {"code":475,"error":"app not ready yet","errorId":"82c999c1-3ae5-4d9c-a824-4512a3afb636","status":500}

![image](https://user-images.githubusercontent.com/49307767/111931267-d3cd4d80-8af5-11eb-8feb-42ebeae08b82.png)

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

don't install google Dialogflow

### Actual behavior:
don't install google Dialogflow
![image](https://user-images.githubusercontent.com/49307767/111931417-1f7ff700-8af6-11eb-82f2-569ff213da94.png)
![image](https://user-images.githubusercontent.com/49307767/111931631-8d2c2300-8af6-11eb-8064-1ca0f3f47130.png)
![image](https://user-images.githubusercontent.com/49307767/111931729-d2505500-8af6-11eb-999d-eece7c20ac79.png)
other apps can installed.

### Server Setup Information:

- Version of Rocket.Chat Server: snap installed
- Operating System: snap installed
- Deployment Method: snap installed
- Number of Running Instances: snap installed
- DB Replicaset Oplog: snap installed
- NodeJS Version: snap installed
- MongoDB Version:snap installed

### Client Setup Information

- Desktop App or Browser Version: chrome newest
- Operating System: Ubuntu Server 18.04.1 LTS 64bit

### Relevant logs:I20210322-09:47:25.331(8) Setting default file store to GridFS 
I20210322-09:47:25.364(8) LocalStore: store created at  
I20210322-09:47:25.365(8) LocalStore: store created at  
I20210322-09:47:25.365(8) LocalStore: store created at  
I20210322-09:47:27.413(8) LocalStore: store created at  
I20210322-09:47:27.414(8) LocalStore: store created at  
I20210322-09:47:27.414(8) LocalStore: store created at  
I20210322-09:47:27.736(8) Setting default file store to GridFS 
I20210322-09:47:37.466(8) ufs: temp directory created at "/tmp/ufs" 
I20210322-09:47:38.883(8) LocalStore: store created at  
I20210322-09:47:38.883(8) LocalStore: store created at  
I20210322-09:47:38.883(8) LocalStore: store created at  
I20210322-09:47:39.110(8) Updating process.env.MAIL_URL 
I20210322-09:47:39.424(8) Setting default file store to GridFS 
I20210322-09:47:39.617(8) Starting Email Intercepter... 
I20210322-09:47:40.664(8) Loaded the Apps Framework and loaded a total of 0 Apps! 
I20210322-09:47:41.002(8) Updating process.env.MAIL_URL 
I20210322-09:47:41.165(8) Using GridFS for custom sounds storage 
I20210322-09:47:41.170(8) Using GridFS for custom emoji storage 
I20210322-09:47:44.549(8) ➔ System ➔ startup 
I20210322-09:47:44.549(8) ➔ +-----------------------------------------+ 
I20210322-09:47:44.550(8) ➔ |              SERVER RUNNING             | 
I20210322-09:47:44.550(8) ➔ +-----------------------------------------+ 
I20210322-09:47:44.550(8) ➔ |                                         | 
I20210322-09:47:44.550(8) ➔ |  Rocket.Chat Version: 3.12.1            | 
I20210322-09:47:44.551(8) ➔ |       NodeJS Version: 12.18.4 - x64     | 
I20210322-09:47:44.551(8) ➔ |      MongoDB Version: 3.6.14            | 
I20210322-09:47:44.551(8) ➔ |       MongoDB Engine: wiredTiger        | 
I20210322-09:47:44.551(8) ➔ |             Platform: linux             | 
I20210322-09:47:44.551(8) ➔ |         Process Port: 3000              | 
I20210322-09:47:44.552(8) ➔ |             Site URL: http://localhost  | 
I20210322-09:47:44.552(8) ➔ |     ReplicaSet OpLog: Enabled           | 
I20210322-09:47:44.552(8) ➔ |          Commit Hash: f2817c056f        | 
I20210322-09:47:44.552(8) ➔ |        Commit Branch: HEAD              | 
I20210322-09:47:44.552(8) ➔ |                                         | 
I20210322-09:47:44.553(8) ➔ +-----------------------------------------+ 
I20210322-09:49:46.686(8) Unloaded the Apps Framework. 
I20210322-09:49:59.729(8) Loaded the Apps Framework and loaded a total of 0 Apps!

**Comment by murtaza98** [comment]
Hey @APPX-Studio Could you try to install the app again? This issue should be fixed now

**Comment by APPX-Studio** [comment]
> Hey @APPX-Studio Could you try to install the app again? This issue should be fixed now

i have install scuseeed ,i am to test,if can running bots.i will to tell  you. thank you.
