### ISSUE TITLE
Option to video call or audio call with own self

### ISSUE THREAD

**Issue by nishant23122000** [RocketChat/Rocket.Chat#21249]
## Description:

When I open my own chat section (Direct message with own self) and open the user info option, it will show the start video call and audio call buttons.

## Steps to reproduce:

1.Search your own name inside the left section 
2. you will reach the chat section where you can send messages to yourself
3. click one user info icon on the top right of the chat section
4. you can find the voice and voice call option

## Expected behavior:

When user opens their own chat section, we should not give permission to start a video call, so we have to remove the start video and audio call button when user starts chatting with themself.

## Actual behavior:

Currently, Rocket.chat allows user to start voice and video call in own chat section

![image](https://user-images.githubusercontent.com/53515714/112003300-ca200600-8b46-11eb-9326-c61a22c6835f.png)

## Server Setup Information:

Version of Rocket.Chat Server: 3.13.0
Operating System: Windows 10
Deployment Method:
Number of Running Instances:1
NodeJS Version: 12.21.0
MongoDB Version: 4.0.23

## Client Setup Information

Desktop App or Browser Version: 89.0.4389.90
Operating System: Windows 10

## Relevant logs:

**Comment by yash-rajpal** [comment]
Please check earlier discussions on it, #21153 and #21170

**Comment by shrinish123** [comment]
Yep this issue can be fixed by #21172
