### ISSUE TITLE
Saving the room topic deletes "hide system messages" settings

### ISSUE THREAD

**Issue by sennewood** [RocketChat/Rocket.Chat#21241]
### Description:

Saving the room topic deletes "hide system messages" settings.

### Steps to reproduce:

1. Create a new room.
2. Define some hidden system messages.
3. Save and exit.
4. Refresh the page, just to be sure :)
5. Set a topic and click on save.
6. Refresh the page.
7. See "Hide System Messages".

### Expected behavior:

Topics and hidden system messages shouldn't interact.

### Actual behavior:

Topics and hidden system messages interact with each other.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Debian 9
- Deployment Method: Docker
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.23

### Client Setup Information

- Browser Version: Firefox 86.0.1
- Operating System: Win 10

### Additional context

No.

### Relevant logs:

No.

**Comment by Jeanstaquet** [comment]
I found the problem, I prepare the commit

**Comment by sennewood** [comment]
Still an isssue in 3.13.2

**Comment by sennewood** [comment]
Still an isssue in 3.14.0

**Comment by sennewood** [comment]
Still an isssue in 3.16.0

**Comment by sennewood** [comment]
I'm looking forward to the day when the changes will be applied by the Rocket.Chat-Team :)

**Comment by sennewood** [comment]
To clearify this issue a little bit more: The problem is the refresh (F5) of a page.

You can set or change the hidden system messages in a room at will, go into other rooms, chat, post and everything else you want. But as soon as you press F5 - even when you're in another room - the hidden system messages will reset to nothing.
