### ISSUE TITLE
OwnPush Support

### ISSUE THREAD

**Issue by chrisvella** [RocketChat/Rocket.Chat#2124]
A new open source alternative to GCM has been developed: [http://forum.xda-developers.com/android/apps-games/future-push-services-ownpush-t3306763](http://forum.xda-developers.com/android/apps-games/future-push-services-ownpush-t3306763)

Could rocket.chat possibly support it? Reliance on gcm put me off using rocket.chat on android.

**Comment by prohde** [comment]
Related to #2071 and #2000 ?

**Comment by jerdog** [comment]
Speaking from an OwnPush perspective, we would be happy to work with Rocket.Chat to provide an open source alternative - feel free to reach out via ownpush@fastbootmobile.com

**Comment by hirschnase** [comment]
:+1:

**Comment by engelgabriel** [comment]
Please also give your input at https://github.com/raix/push/issues/191

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
