### ISSUE TITLE
An easier way to make large quotes

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2125]
I often find an amusing quote or comment that I want to copy into chat. Currently the only way to indicate this is with quote marks at the start and end of the quote and it doesn't use Rocket.chat's built-in block quoting. It would be really nice to a multi-line quote syntax

**Comment by graywolf336** [comment]
How would you suggest implementing a multi-line quote syntax?

**Comment by royalaid** [comment]
You can recycle the the exsiting quote syntax and multiline code syntax with something like 
```
>>>
quote goes here
>>>
```

**Comment by RichardFoxworthy** [comment]
See #918

**Comment by Kyogre** [comment]
> You can recycle the the exsiting quote syntax and multiline code syntax with something like
> ```
> >>>
> quote goes here
> >>>
> ```

In current version of Rocket Chat it is realized with <<< in the end. This way:
```
>>>
multi line
quote
goes here
<<<
```

**Comment by billynoah** [comment]
@Kyogre - that doesn't work for me.  Is there something I'm missing?

**Comment by NoLooseEnds** [comment]
Same here. Tried multiple alternatives, but does not work.
