### ISSUE TITLE
Network Related issue

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#2126]
We have deployed a private RC server in our premises and have monitored last one week, there is heavy traffic during the night Time. (After office hours) It will be fully utilized our local Area network also and we cannot use our internal network too. herewith attached screenshot firewall logs for more info 
![chat-error](https://cloud.githubusercontent.com/assets/16605816/12805614/22e43f3e-cb23-11e5-8ef1-cf8576e0ef44.JPG)

**Comment by marceloschmidt** [comment]
Is this incoming? outgoing? Can you provide more details as to where those requests are going to or coming from? Also, can you confirm this is related to your rocket.chat instance?

**Comment by sureshdba2003** [comment]
Yes this is Rocket Chat instance issue. because once the server down & traffic was normal.  if it is up then traffic was unusual. Both Incoming & outgoing. 

FYI, we have deployed ubuntu 14.03 server.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
