### ISSUE TITLE
Allow selected users to invite others to private group

### ISSUE THREAD

**Issue by defib** [RocketChat/Rocket.Chat#2127]
Currently I can't find a way to allow someone else to invite users to a private group I made.  @paulproteus and I tried making a user a group moderator or owner and it did not work.

**Comment by jasperla** [comment]
Running into the same issue. It's confusing that even making someone else owner or moderator doesn't work.

**Comment by pcarn** [comment]
+1

**Comment by mrogaski** [comment]
+1 This is a big one for us.  The creator/owner of a channel should be able to assign moderator roles to allow others to invite.

**Comment by Lochemage** [comment]
+1 Absolutely critical, also an admin user should be able to control this even if they are not the creator of the channel.

**Comment by mrogaski** [comment]
Agreed, the fact that an admin must be a member of a channel to modify permissions is problematic.

**Comment by pcarn** [comment]
It's worse than that. The admin has to be the creator of the channel.

**Comment by Lochemage** [comment]
Right, the only user that can invite people to a channel is the creator of that channel, no way to change it once the channel has been created.

**Comment by mylesw-luma** [comment]
+1 This seems like an oversight to not have

**Comment by mylesw-luma** [comment]
This seems to be fixed in 0.26

**Comment by sampaiodiego** [comment]
Any user with the `add-user-to-room` permission (room owners and room moderators by default) can add an user to a room.

**Comment by oceatoon** [comment]
Hi I'm using the API to invite users to channels or groups
works fine on channels, but not on groups
I then ran into this post 
activated add-user-to-room permission
But I still don't have access to the roomId of the group using groups.info
 and cannot groups.invite through the api 
is this implemented for this usage ?

**Comment by ganesh-at-wiw** [comment]
Hi, I'm also facing same problem. Through API, I can add/remove users to and from channels, but not to private groups.
Our rocket chat version is: 2.10.5.

**Comment by ganesh-at-wiw** [comment]
I confirm now that the problem is resolved and that, that I can add/remove members to/from private groups via api.
