### ISSUE TITLE
Upload image freezes in channel edit section

### ISSUE THREAD

**Issue by nishant23122000** [RocketChat/Rocket.Chat#21284]
### Description:

When I change the room image and upload any other image file, it works fine but if I upload some other file format like .txt, .docx, etc then the upload screen freezes. And after that, if I try to upload a correct extension image format then it doesn't reflect. The image box goes into a permanent skeleton loading screen.

### Steps to reproduce:

1. Create your own channel or else try it in any of the existing channels
2. Then click on the menu icon at the top right corner
3. Then click on the room info option
4. Now click on the edit room button
5. then upload any file format other than image extensions
6. You will not receive any error message, will only see a loading animation
7. After that try uploading the image format
8. The loading screen still continues.
9. You will be prompted by the relevant error only when you proceed to save the changes.

### Expected behavior:

This exception is supposed to be handled by responding with the appropriate error message immediately when user tries to upload a wrong file, rather than when the modification is saved.

### Actual behavior:

If we upload another format file except for image formats and save the room then it gives a wrong file format error.
No error message prompts while uploading the wrong file format.

![image](https://user-images.githubusercontent.com/53515714/112269454-6577bf00-8c9e-11eb-942b-7a7c1ebedbc3.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0
- Operating System: Windows 10
- Deployment Method:
- Number of Running Instances:1
- NodeJS Version: 12.21.0
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: 89.0.4389.90
- Operating System: Windows 10

**Comment by PriyaBihani** [comment]
Working on it

**Comment by nishant23122000** [comment]
@PriyaBihani can i join with you?

**Comment by nishant23122000** [comment]
Can you mention the issue, So that I can understand it's already working?

**Comment by guijun13** [comment]
Fixed https://github.com/RocketChat/Rocket.Chat/pull/25912
