### ISSUE TITLE
Bug: Scrollbar is missing

### ISSUE THREAD

**Issue by himanshujaidka** [RocketChat/Rocket.Chat#21282]
### Description:
There is no scrollbar in the members section.

### Steps to reproduce:

1. web app or desktop app
2.  click on any channel
3. go to members option, here you will find that user is not able to scroll the list

### Expected behavior:
There should be a scrollbar so that the user is able to scroll the member's list

### Actual behavior:
Not able to do scrolling

![Screenshot (182)](https://user-images.githubusercontent.com/58654018/112253957-b0d1a380-8c85-11eb-88ef-fee7df3ae53d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: windows
- Deployment Method: found on web app
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: latest
- MongoDB Version:latest

### Client Setup Information

- Desktop App or Browser Version:latest
- Operating System: windows

**Comment by Kartik18g** [comment]
working on it

**Comment by himanshujaidka** [comment]
already working, FIFO

**Comment by Aakash2408** [comment]
Can I Work on this issue @himanshujaidka?

**Comment by shree675** [comment]
In the web app version, on clicking Members icon, the whole page is going blank, it is not just the scroll bar that is not appearing.
This is happening to me in the gsoc2021 channel.

Chrome OS Version: 89.0.4389.90

![Screenshot (23)](https://user-images.githubusercontent.com/58718144/112799524-1958c000-908c-11eb-931e-31b6c4cd347b.png)

**Comment by theamanjs** [comment]
Hey, @himanshujaidka I've looked into your issue and tried reproducing it. But I saw no problem. I was using the same version as you specified with the same platform. I think there must some issue with installation on your machine. I also tried the same on Linux as well and it was working smoothly. Can you please try reinstalling the desktop app I hope it will solve the issue? 

https://user-images.githubusercontent.com/38748298/112865808-c1937680-90d6-11eb-9a4b-cae8c186ab72.mp4

**Comment by theamanjs** [comment]
Hey, @shree675 I tried reproducing it on web app using the same version of Chrome you using. Everything seems fine to me. Not sure why it is showing you an issue you can check in the below video 

https://user-images.githubusercontent.com/38748298/112866772-c7d62280-90d7-11eb-8169-50a205e57dbf.mp4

**Comment by shree675** [comment]
@theamanjs Thank you for your showing the video. Unfortunately, it is still occurring on my browser. 
I guess we must dig deeper.

https://user-images.githubusercontent.com/58718144/112876300-f9082000-90e2-11eb-9de5-74f1f4e86ee7.mp4

**Comment by himanshujaidka** [comment]
@theamanjs , I think you are using pc?

**Comment by chaperonRose** [comment]
Hello,
tested in 3.12.x : no scrollbar in memberlist ; tested in 3.13.1 : scrollbar do appears but memberlist isn't full (i open a new issue).

**Comment by chaperonRose** [comment]
Hello,
This is strange bug.
In 3.12.x, no scrollbar except in random (?) moment, after performing an action in memberlist.
In 3.13.1, scrollbar appears after switching between connected/all (or reverse).

**Comment by dougfabris** [comment]
We had a little issue related to the scrollbar missing when the room has more than 25 members, it's already fixed =)

**Comment by dougfabris** [comment]
> @theamanjs Thank you for your showing the video. Unfortunately, it is still occurring on my browser.
> I guess we must dig deeper.
> 
>  Rocket.Chat.-.Google.Chrome.2021-03-29.22-56-06_Trim.mp4

This error was fixed on this PR: #21952
Thank you guys for reporting and helping us!
