### ISSUE TITLE
Remove (LDAP) string in login form

### ISSUE THREAD

**Issue by nebulade** [RocketChat/Rocket.Chat#2128]
Hi. We have a setup where LDAP is enabled, but external account signup is also allowed. This is good in our case. So after LDAP auth failed, it falls through to check other non ldap users. However this makes the login form UI confusing, since many people are not using LDAP then on this instance for login. Could that "(LDAP)" simply be removed from the login form. What was the idea behind showing it in the first place? 

The relevant line is https://github.com/RocketChat/Rocket.Chat/blob/ff44d4783a7969434a0aa2a595b9c530c0f4b301/packages/rocketchat-ui-login/login/form.coffee#L44

I can just put up a pull request if there is chance of this getting merged.

Thank you.

**Comment by compuguy** [comment]
To my knowledge @nebulade if ldap is enabled, only ldap logins are allowed. If the ldap connection fails, local accounts work (correct me if I'm wrong).

**Comment by nebulade** [comment]
This does not seem to be the case. Even if LDAP is enabled, users can still signup and are able to login. However if for example you add a new account with the same email or username like a later added ldap user, the ldap user will win the login. It is a bit muddy but I think this is there for admins to always be able to login.

**Comment by compuguy** [comment]
@nebulade I confirmed this as well. In early rocket.chat builds, this was not possible. What would be better is have a option to disable local accounts if ldap is operational. That and allow the admins to set the text on the login button.

**Comment by nebulade** [comment]
Ah, I see. But you are making a good point, that the login button (what that issue is mainly for) may simple be added to the customization options, instead of special case that for LDAP.

**Comment by engelgabriel** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/commit/f03327ebb1e0d2fc9fdd438836d14e1f8ad72644

Registration can be turned off individually.
