### ISSUE TITLE
Autocomplete search users issue

### ISSUE THREAD

**Issue by mikonoid** [RocketChat/Rocket.Chat#2129]
Hi!

How to disable autocompleting for search users? Can I search user only by full username?

**Comment by marceloschmidt** [comment]
You can't disable it. Usually you can look for either username or name (in some places). What part are you talking about?

**Comment by fabiomontefuscolo** [comment]
Uhm, I would like to report a different issue, but I want to use this title. So I will report here.

I think it would be nice if autocomplete try to match usernames at beginning of word. Explaining in a SQL way, to autocomplete @marceloschmidt, I should search `"marcel%"` or `~ "^marcel"`.

Currently, the autocomplete search for a substring in any part of username. So the autocomplete for "ariadne" should be "aria", but it brings "mariana" in first place.

Does it make sense?

**Comment by fabiomontefuscolo** [comment]
@marceloschmidt I don't know coffee script, but I'm inspecting the code at [userAutocomplete.coffee#L18](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/publications/userAutocomplete.coffee#L18), and I think the search term could be `'^' + selector.username`. What do you think?

Sorry, I can't do a pull request because I don't have the RocketChat running on my localhost.

**Comment by marceloschmidt** [comment]
@fabiomontefuscolo I agree that sometimes it is best to display users whose name **starts** with what you're typing. But I also think that being able to search parts of the username if very useful sometimes. 

So I'd suggest we search for users that start with what's typed and then do another search for contains, removing the former results from this search. This way, users that start with the text would show up first in results, but we'd still show the contained ones.

I'll close this issue in favor of #874. We need to work on that issue ASAP, as there are multiple issues referring to the same request.
