### ISSUE TITLE
Login or registration form Feature

### ISSUE THREAD

**Issue by royalterra** [RocketChat/Rocket.Chat#2130]
I see the login form only promote to centralized social networks can be more open with the community allow to login again Hubzilla, Diaspora or Status Net Hubs . I not understand this idea of only promote centralized social networks where your data is not safe

**Comment by marceloschmidt** [comment]
Can you be more specific as to what the issue is? I did not understand what you're requesting.

**Comment by blindingstars** [comment]
I think @royalterra might be referring to the OAuth networks supported for login, such as Facebook and Google, which are centralized. So, OAuth-esque integration for decentralized networks?

**Comment by royalterra** [comment]
yes I refer to oauth and openid for can be use in other social networks like Hubzilla Diaspora Status net . There millions of users are not in facebook or google and are using decentralized social networks like Hubzilla Diaspora etc

**Comment by engelgabriel** [comment]
@royalterra we support custom oAuth, SAML, LDAP, AD configurations, so you can add any platform you like.
