### ISSUE TITLE
Feature Request: Drag & Drop messages into a thread

### ISSUE THREAD

**Issue by sennewood** [RocketChat/Rocket.Chat#21300]
At our server it often happens, that users write into the main chat when they reply to a thread - mostly because somebody clicked on "post into main chat" (or whatever it is called in english ^^). To fix this, it would be awesome if the channel owners, moderators and the author of a post could move a message into the thread.

**Comment by sennewood** [comment]
Dear bot,

I updated my issue. Please re-open it :(

**Comment by sennewood** [comment]
Dann halt nicht! 😠

**Comment by devZer0** [comment]
i think it's totally fine how rocketchat does welcome volunteers reporting issues. NOT

**Comment by sschuberth** [comment]
Ping, how can this be reopened? @rodrigok maybe?
