### ISSUE TITLE
Upload filesize needs to be 1e+89

### ISSUE THREAD

**Issue by tdhz77** [RocketChat/Rocket.Chat#2131]
999999999999999999999999999999999999999999999999999999999999999999999999999999
= 1e+89 

However, rocket chat thinks this number is equal to 1, so we can't upload anything.
We use huge files here at work, bigger than your average company.

**Comment by graywolf336** [comment]
Maybe we need to change it to accept -1 which then means size is not a
restriction. But I will warn you, the current way Rocket.Chat handles file
uploads on the client is not very good for large files and needs to be
improved.

**Comment by tdhz77** [comment]
I may fork this and change it to use FS Collection and Dropbox. How is the current system handling uploads?

**Comment by rodrigok** [comment]
We are using https://github.com/jalik/jalik-ufs, Collection FS was deprecated.

**Comment by tdhz77** [comment]
Thanks, I didn't realize this.

**Comment by engelgabriel** [comment]
We would welcome contribution packages to use S3, Dropbox, etc

**Comment by tdhz77** [comment]
I'll take a look this weekend.

**Comment by engelgabriel** [comment]
@rodrigok can give you some directions.

**Comment by rodrigok** [comment]
@tdhz77 you can copy this implementation of the GridFS store for UFS to start your own adapters.

**Comment by engelgabriel** [comment]
@tdhz77 any progress on your side? We are planning to start the work on S3 support now.

**Comment by engelgabriel** [comment]
This depends on #369

**Comment by tdhz77** [comment]
@engelgabriel I didn't have time as our power is currently out here in the office.

**Comment by engelgabriel** [comment]
Hi @tdhz77 is this still an issue? Did you managed to work on this for your own needs?

**Comment by engelgabriel** [comment]
@MartinSchoeler Maybe we need to change it to accept -1 which then means size is not a
restriction.

**Comment by tdhz77** [comment]
I haven't been able to get this working.
