### ISSUE TITLE
embedded layout disappers after clicking somewhere

### ISSUE THREAD

**Issue by Schrammi** [RocketChat/Rocket.Chat#21321]
### Description:

When i load a channel with ?layout=embedded, the channel loads with the simplistic optic. This is ok. But when i click somewhere in the window, the query parameter dissapers and the full optic is shown.

### Steps to reproduce:

1. Open https://open.rocket.chat/channel/general?layout=embedded
2. Click somewhere in the window

### Expected behavior:

The view stays in layout=embedded

### Actual behavior:

The embedded disappears and the full layout loads

### Server Setup Information:
Setup from Rocket.Chat on https://open.rocket.chat

- Version of Rocket.Chat Server: 3.12.1
- Operating System: ...
- Deployment Method: ...
- Number of Running Instances: ...
- DB Replicaset Oplog: ...
- NodeJS Version: ...
- MongoDB Version: ...

### Client Setup Information

Desktop App or Browser Version: Chrome 89.0.4389.90
Operating System: Windows 10

**Comment by Schrammi** [comment]
As @davidecavezzi mentioned in the issue #13688 this seems to be a bug with the setting:
My account > Preferences > Messages > Hide right sidebar with click.

I will test it tomorrow.

**Comment by dholbrook86** [comment]
Any update on this issue? When pressing "Reply" and opening up a thread the url removes the sidebar panel.

**Comment by julienchabanon** [comment]
We are having this issue and this is the biggest issue we have so far with integrating rocketchat with our plateform.

**Comment by julienchabanon** [comment]
@Schrammi Enabling "Hide right sidebar with click" did not solve the issue for me. It still leaves the embedded mode!

**Comment by boxstyle22** [comment]
@Schrammi @julienchabanon I see the same issue happening, when running in embedding mode in an iframe. The app jumps out of the embedded mode in many places:

- When clicking on the profile, a user can click 'View Full Profile'. This is a setting that cannot be turned off.
- Threads and Discussions are opened in non-embedded mode
- When closing some popups, the embedded mode is closed

If I'm honest, this makes embedded mode almost unusable, especially as other tenants are being displayed in the sidebar which is a no-go (they are private, why are they displayed there in the first place??)

This is while "Hide right sidebar with click" is disabled, by the way. Enabling it also made things a lot worse for me.

**Comment by boxstyle22** [comment]
@julienchabanon A quick workaround is to hide the sidebar.

```
.sidebar {
   display: none
}
```

The layout holds up very well! If you have any ideas how to not have the same happen for the admin user, let me know!

**Comment by gabriellsh** [comment]
This could have been fixed somewhere, but has definitely been fixed here https://github.com/RocketChat/Rocket.Chat/pull/30137
