### ISSUE TITLE
Missing Pt-Br translation at admin/ConnectivityServices page

### ISSUE THREAD

**Issue by EduardoPicolo** [RocketChat/Rocket.Chat#21339]
### Description:
Connectivity Services page is missing some Pt-Br translation.

### Steps to reproduce:

1. Go to admin panel;
2. Go to Connectivity Services.

### Expected behavior:
All the dialog should be translated

### Actual behavior:

![Captura](https://user-images.githubusercontent.com/49292747/112733174-1be8d780-8f1d-11eb-9bca-20d855a78fcd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0-develop
- Operating System: Linux
- Deployment Method:  ...
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Brave 1.24.8
- Operating System: Debian 10

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
