### ISSUE TITLE
Security hotfix - possibility to merge into 3.9.7

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#21343]
### Description:

Hi, last weekend security hotfixes was released. Is there possibility to merge this hotfixes also to 3.9.7 version. For us is last stable version (3.12 has issues with Jitsi). 3.9 was ommited but 3.8 has this fix. Please consider it.

### Steps to reproduce:

1. 3.9.7 not fixed with security hotfix

### Expected behavior:

Release 3.9.8 with security hotfix

### Actual behavior:

3.9.7 not fixed

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.7
- Operating System: Centos 7
- Deployment Method: docker-compose
- Number of Running Instances: 33
- DB Replicaset Oplog: YES
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

**Comment by fdellwing** [comment]
I cannot say anything about the 3.9.x but you know there is also a 3.10.x and Jitsi works fine there (it broke completely in 3.11.x and kinda works in 3.12.x).

**Comment by Sing-Li** [comment]
Please see our published security fix back-port (support)   policy here:   https://docs.rocket.chat/getting-support#rocket-chat-versions

Community members that need exception can of course, back-port the fix themselves for the version that they must remain on.
