### ISSUE TITLE
Access to server logs from administration interface

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2134]
Optional remote files zip + retrieve ability - for config and logs (capped collection or TTL Index)

**Comment by skemb321** [comment]
This is a great admin feature. 
I was also thinking of having an integration using scalyr. Having scalyr would empower devs to have triggers and powerful log searches.

Thoughts?

**Comment by engelgabriel** [comment]
The integration with scalyr should not depend on configuration on Rocket.Chat. The NodeJS  process will log everything to the stdout, so you should be able to import the log with the regular agent.

If you are using a docker deployment, you should use the https://www.scalyr.com/help/monitors/docker-monitor
