### ISSUE TITLE
Admins/Owners/Moderators should be able to add a user to a channel created by someone else.

### ISSUE THREAD

**Issue by pcarn** [RocketChat/Rocket.Chat#2138]
Right now, only the creator of a channel or private group can add someone to it. An Admin can remove someone from the group, make someone the owner of moderator of it, but no one can seem to add someone to the group except the creator.

**Comment by andreas-bulling** [comment]
I noticed that as well - even as administrator I am not able to add users to a public channel created by somebody else. Not even for #general

**Comment by defib** [comment]
#2127

**Comment by pcarn** [comment]
Closing as duplicate of #2127
