### ISSUE TITLE
No strict SSL make redirect to 127.0.0.1

### ISSUE THREAD

**Issue by royalterra** [RocketChat/Rocket.Chat#2139]
Hi I have setup before a domain name I setup no strict SSL and force https and now always 
change the domain url to https://127.0.0.1/
Any ideas how to solve that
Thanks

**Comment by rodrigok** [comment]
Are you accessing via some reverse proxy?

Should work if you are accessing via `http://127.0.0.1` since the code https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-cors%2Fcors.coffee?ts=2#L70-L74 do not redirect if you are accessing from local.
