### ISSUE TITLE
Ability to mute user for set period of time 

### ISSUE THREAD

**Issue by jasonirwin** [RocketChat/Rocket.Chat#214]
Sometimes it is necessary to temporarily mute users who do not adhere to a chat site's rules. It is desirable to provide administrators/moderators with the ability to mute such users for set periods of time so that they can continue to view the chat but cannot post again until the mute period ends or they are explicitly unmuted.

**Comment by stefanffsx** [comment]
Good idea +1

**Comment by engelgabriel** [comment]
Depends on #249
