### ISSUE TITLE
Add support for more markup

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#2140]
It would be really nice for Rocket.Chat to support more markups, see for example gitter.im or GitHub itself.

**Comment by geekgonecrazy** [comment]
@andreas-bulling can you give some examples of some you think should be present?

**Comment by andreas-bulling** [comment]
all of them ;)

**Comment by geekgonecrazy** [comment]
@andreas-bulling we support most everything... So that doesn't really help much.

follow this if you just want general better markdown: #918

If you have something specific please post.  For now i'm closing this.
