### ISSUE TITLE
DDP and authentication

### ISSUE THREAD

**Issue by modist** [RocketChat/Rocket.Chat#2142]
How do you parse userid/password using ddp ?

I have read https://github.com/RocketChat/Rocket.Chat/wiki/Real-time-messaging-APIs - but there is no mentioning of this.

Furthermore : is ddp running on the same port as the chat ? We are running on port 80.

**Comment by sampaiodiego** [comment]
hey @modist what you mean by "parse userid/password"?
do you want to log in using a DDP client?

and yes, DDP is running on the same port.

**Comment by modist** [comment]
yes - trying develop a tray-client using c# - but I cannot subscribe to a stream without login in ?

**Comment by geekgonecrazy** [comment]
I don't know if you're still having this issue.  Please see this project: https://github.com/RocketChat/Rocket.Chat.Net if so
