### ISSUE TITLE
Disabled users in Microsoft Active Directory are still enabled and active in Rocket.Chat.

### ISSUE THREAD

**Issue by itegtdeb** [RocketChat/Rocket.Chat#21435]
Hi all I am writing here because I still beleave that the community of RC is a ways better than any paid support.
I am sure that I am not the only one with the problem in the title so it will be nice if we succeed to draw the attention of the RC developers.

Our environment:
Selfhosted: Debian 10
RocketChat version - always latest version
Integrated with: MS Active Directory
Licence: Paid Pro Licence for 1500 users

As most of you know RC can be integrated with Active Directory/LDAP servers but something is very wrong with the real implementation!
As it is known many reglaments demand to clear the users data and accounts after they leave the company. With current implementation of AD/LDAP integration this is simply not possible because the sync work only in one direction from - adding the users in RC. 
1. The main issue - there is an option in Enterprise Licence of RC called Advanced Sync - which should do the work. Well it doesnt. I had rised several support tickets to RC team and we ended with a trial Enterprice licence (to test the Advanced Sync option) and a reply from month ago:
 Quote: "the sync behavior on your server doesn't seem right (or, at least, it has some inconsistencies indeed), let me check these scenarios further, will circle back here shortly. "
Whats important here: Working or not the LDAP advanced sync feature should be available as core function for every licence level. Otherwise, because of **GDPR**, Rocket Chat can be used in Europe only in Enterprice variant, if the advanced sync function works ofcoruse.

2. Lets pretend that every RC clients agreed to pay for Enterprice Licence: 
What we can read in the RC Docs site is:
["**We're not experts on LDAP, so there might be lots of features we don't know about and we'd love to have your comments and feedback on what we can do to improve it.**"](https://docs.rocket.chat/guides/administrator-guides/authentication/ldap)
Why RC want us to pay money for something that they are not expert of?

3. What botthers me next affects the corporate security.
With broken full AD sync the deleted user remains active and enabled in RC until the user logoff from the client (desktop and mobile). This behavior affects the corporate security and put it on high risks of information leakage.

4. Some case when user status needs to be changed on disabled.
4.1.	If account is ldap synced, and exist in RC, but not exist in AD or is not found with ldap search filter
4.2.	If account is ldap synced, and exist in RC, but is locked in AD
4.3.	If account Is ldap synced and exist in RC, but is disabled in AD
4.4.	If account Is ldap synced and exist in RC, but password is expired in AD

All of these scenarios are defined by different values of a different attributes in MS Active Directory (I think that in the pure LDAP protocol the parameters are different from the mentioned bellow)

lockoutTime = 0 unlocked user,  if =1 the user is locked
useraccountcontrol

512=Enabled
514= Disabled

66048 = Enabled, password never expires
66050 = Disabled, password never expires
 
pwdLastSet=0 means the password is expired and user has to change the password at next logon. (not from RC interface)
PasswordExpired - true/false

5. Please write your experience with RocketChat (current and past versions) and user status sync from Active Directory. You can mention your licence (Community, Pro, Enterprise)

**Comment by MisterErwin** [comment]
As I'm currently also playing around with LDAP to onboard my org:

> The 'pwdAccountLockedTime' attribute will be used to determine if the user is disabled

from the [docs](https://docs.rocket.chat/guides/administrator-guides/authentication/ldap/settings).


In your setup (as described above) you are using different attributes - you might want to try adding a `pwdAccountLockedTime` on disabled LDAP users (as users with a LDAP entry of `pwdAccountLockedTime` or no LDAP entry at all are marked as disabled during the syncs (not during login, only during LDAP syncs(!))  - from what I can gather from the source. Any group or user filters specified do not matter for this case).

Also: If you modify your users LDAP entry to no longer match the login user/group filters or remove it will fallback to the default login (in case you have "Login Fallback" enabled), which will allow them to login despite being disabled on your LDAP server - so you might want to disable that.

While I can't speak for rocket.chat myself, but there are often more pressing issues which require attention and LDAP is not fun, but time consuming to debug - but thanks to being OpenSource you can always contribute and fix your issues with LDAP ;)

So regarding your fifth point: Dunno, made some PRs to improve it  :upside_down_face:

**Comment by ankar84** [comment]
Hey @dstaykov 
My advice to you is just disactivate user in RC in moment of disable that user in AD with that [script](https://forums.rocket.chat/t/ldap-auth-disabled-ad-users/1715/14?u=anton.karlan)

**Comment by dstaykov** [comment]
> Hey @dstaykov
> My advice to you is just disactivate user in RC in moment of disable that user in AD with that [script](https://forums.rocket.chat/t/ldap-auth-disabled-ad-users/1715/14?u=anton.karlan)

Yep, this is the best solution so far... until something change in the API requests.

**Comment by teak421** [comment]
Thank you for this script.  This has been an open issue for a long time and it's annoying for my HD.  I wish they fixed more simple bugs like this instead of working on new features.  Look at the recent release notes and see how many regressions they had to fix.

**Comment by dstaykov** [comment]
Hi all, 
Thank you for the script BUT If you agree this is not a solution that some of os paid for right?
According to the attribute pwdAccountLockedTime - there is no such attribute in Microsoft Active Directory.
I am pretty sure that this is the main reason of the problem!
