### ISSUE TITLE
Cannot Link With Discord

### ISSUE THREAD

**Issue by cyberdragon442** [RocketChat/Rocket.Chat#21443]
If I try to link my Discord account on 3.1.1, it just throws an [Undefined] error in the corner. It shows my account correctly (correct name, ID, and avatar), but when I hit "authorize" it just fails.

Note: This happens in both the Windows app and browser version.

**Comment by reetp** [comment]
Hi.

Can you please help the developers by filling out a proper bug report? They can't really help without this information.

Use this link: https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md 

Make sure you are running the latest version of Rocket.Chat when you test.

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues 

Thanks.
