### ISSUE TITLE
Demo not working. Returning 502 error.

### ISSUE THREAD

**Issue by sbdchd** [RocketChat/Rocket.Chat#2145]
There may already be an issue for this, but in my search I couldn't find one.

https://demo.rocket.chat

**Comment by engelgabriel** [comment]
I am fixing it. Tks.

**Comment by engelgabriel** [comment]
fixed

**Comment by makeitcount** [comment]
@engelgabriel I'm getting the same error "502 bad gateway".

Details:
I had it setup correctly on aws using docker image and it was working fine. Then I changed ssl certificate from letsencypt. Then started the server again. Certificate is working now but getting following error
"502 bad gateway error"

These are the processes that are running on system
`
$ ps aux|grep nginx
root      1156  0.0  0.3  90316  3144 ?        Ss   07:52   0:00 nginx: master process /usr/sbin/nginx
www-data  1581  0.0  0.1  90636  1960 ?        S    08:06   0:00 nginx: worker process
www-data  1582  0.0  0.1  90636  1960 ?        S    08:06   0:00 nginx: worker process
www-data  1583  0.0  0.1  90636  1960 ?        S    08:06   0:00 nginx: worker process
www-data  1584  0.0  0.3  90636  3168 ?        S    08:06   0:00 nginx: worker process
ubuntu    1597  0.0  0.0  10464   940 pts/0    S+   08:18   0:00 grep --color=auto nginx
ubuntu@ip-172-31-18-109:~$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
ubuntu@ip-172-31-18-109:~$ ps aux|grep docker
root       830  0.0  2.5 485112 26108 ?        Ssl  07:52   0:00 /usr/bin/docker daemon
root      1128  0.0  0.3  14572  3580 ?        Ss   07:52   0:00 /usr/local/bin/docker-compose up db
root      1130  0.0  0.3  14572  3580 ?        Ss   07:52   0:00 /usr/local/bin/docker-compose up rocketchat
root      1278  0.2  1.8 185864 18920 ?        Sl   07:52   0:03 /usr/local/bin/docker-compose up db
root      1279  0.1  1.8 185864 18968 ?        Sl   07:52   0:03 /usr/local/bin/docker-compose up rocketchat
root      1369  0.0  1.4 240656 14956 ?        Sl   07:52   0:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3000 -container-ip 172.17.0.3 -container-port 3000
ubuntu    1627  0.0  0.0  10464   940 pts/0    S+   08:20   0:00 grep --color=auto docker
ubuntu@ip-172-31-18-109:~$ sudo docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                    NAMES
cbad5779b333        rocketchat/rocket.chat:latest   "node main.js"           3 months ago        Up 33 minutes       0.0.0.0:3000->3000/tcp   rocketchat_rocketchat_1
35e9f8c005cc        mongo                           "/entrypoint.sh mongo"   3 months ago        Up 33 minutes       27017/tcp                rocketchat_db_1
`

**Comment by sharmapradeep** [comment]
@engelgabriel I'm getting the same error "502 bad gateway".

Details:
I had it setup correctly on aws using docker image and it was working fine. Then I change ssl certificate from letsencypt and reboot the machine. Then started the server again. Certificate is working now but getting following error
"502 bad gateway"

These are the processes that are running on system
`
$ ps aux|grep nginx
root 1156 0.0 0.3 90316 3144 ? Ss 07:52 0:00 nginx: master process /usr/sbin/nginx
www-data 1581 0.0 0.1 90636 1960 ? S 08:06 0:00 nginx: worker process
www-data 1582 0.0 0.1 90636 1960 ? S 08:06 0:00 nginx: worker process
www-data 1583 0.0 0.1 90636 1960 ? S 08:06 0:00 nginx: worker process
www-data 1584 0.0 0.3 90636 3168 ? S 08:06 0:00 nginx: worker process
ubuntu 1597 0.0 0.0 10464 940 pts/0 S+ 08:18 0:00 grep --color=auto nginx

ubuntu@ip-172-31-18-109:~$ sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

ubuntu@ip-172-31-18-109:~$ ps aux|grep docker
root 830 0.0 2.5 485112 26108 ? Ssl 07:52 0:00 /usr/bin/docker daemon
root 1128 0.0 0.3 14572 3580 ? Ss 07:52 0:00 /usr/local/bin/docker-compose up db
root 1130 0.0 0.3 14572 3580 ? Ss 07:52 0:00 /usr/local/bin/docker-compose up rocketchat
root 1278 0.2 1.8 185864 18920 ? Sl 07:52 0:03 /usr/local/bin/docker-compose up db
root 1279 0.1 1.8 185864 18968 ? Sl 07:52 0:03 /usr/local/bin/docker-compose up rocketchat
root 1369 0.0 1.4 240656 14956 ? Sl 07:52 0:00 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3000 -container-ip 172.17.0.3 -container-port 3000
ubuntu 1627 0.0 0.0 10464 940 pts/0 S+ 08:20 0:00 grep --color=auto docker

ubuntu@ip-172-31-18-109:~$ sudo docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
cbad5779b333 rocketchat/rocket.chat:latest "node main.js" 3 months ago Up 33 minutes 0.0.0.0:3000->3000/tcp rocketchat_rocketchat_1
35e9f8c005cc mongo "/entrypoint.sh mongo" 3 months ago Up 33 minutes 27017/tcp rocketchat_db_1
