### ISSUE TITLE
User cannot view public team channels as a non-team member 

### ISSUE THREAD

**Issue by andre-bergemann** [RocketChat/Rocket.Chat#21456]
### Description:

As a user who is not part of the team, I cannot view public team channels.

### Steps to reproduce:

1. Create a Public Team 
2. Create an additional public channel belonging to the team 
3. Try to view the channel with a user who is not part of the team 

### Expected behavior:

I can see and write in the Public Channel of the Team as non Team Member

### Actual behavior:

I can´t see the Channel Content (Header + Messages)
If the user is added to the channel, it won't work either.

![image](https://user-images.githubusercontent.com/18146564/113633666-a17f2c80-966d-11eb-98ea-1a5837a6d38d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0
- Operating System: Ubuntu 18.04
- Deployment Method: Docker (Image: rocketchat/rocket.chat:3.13.0)
- Number of Running Instances: 1 
- NodeJS Version: 12.21.0
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: Microsoft Edge 89.0.774.68 (64-Bit) + Firefox 87
- Operating System: WIndows 10 19042.867

### Additional context

- Server was migrated from version 3.11.0

### Relevant logs:

Log from MS Edge
```
ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411 TypeError: Cannot read property 'prid' of undefined
    at l (/client/hooks/useRoomIcon.tsx:1)
    at B (/client/views/room/Header/Header.js:1)
    at ma (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411)
    at rf (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411)
    at ji (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411)
    at Hi (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411)
    at Ui (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411)
    at Ri (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411)
    at ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411
    at r.unstable_runWithPriority (ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1429)
wf @ ea2f4ecb31064cbbb015aab6dabe8be062e2787a.js?meteor_js_resource=true:1411

```

**Comment by Gummikavalier** [comment]
Since there is no actual design document for the teams feature anywhere, I wonder whether this is on purpose to introduce "organization" style limits to RC. This would actually be preferable for some use cases.

**Comment by gabriellsh** [comment]
So, if the team is public, the user should be able to see the channel, no problem. If the team is private though, it shouldn't be showing up in the search or anywhere else. I just made a PR to fix this blank screen (for the first case)
