### ISSUE TITLE
Autocomplete does not show up on small screens

### ISSUE THREAD

**Issue by MikeAlhayek** [RocketChat/Rocket.Chat#21455]
### Description:

When running the web app on a small screen like 500px x 500px, the autocomplete suggestion box `.rc-popup-list` is not show up. In fact, for the popup container with the suggestion to show up correctly it required a min screen width of 800px anything smaller than 800px, the screen will show a model scrollbar causing the suggestion box to shift down until it no longer show up.

### Steps to reproduce:

 1. Go to the host of the rocket chat using a simulator, set the responsive page dimension to 500 x 500
 2. click on "Create New Channel"
 3. Select "Discussion" for the channel type.
 4. type someone's name in the "Invite Users" box, 

Now, repeat the previous step but change the dimension from 500x500 to 500x700, then 500x800. You'll notice how the suggestion box does not show up with the height is 500, but will show up "far from the input" when the height is 700. Lastly, if you set it 800px height, everything will show up as expected.

### Expected behavior:

I expect the suggestion box to show up immediately under the "Invite Users" regardless of the dimension. 

### Actual behavior:

![Screenshot_5](https://user-images.githubusercontent.com/24724371/113630098-35280d00-961c-11eb-829b-b6cd0a459371.png)
![Screenshot_6](https://user-images.githubusercontent.com/24724371/113630099-35280d00-961c-11eb-9500-819c351383f8.png)
![Screenshot_7](https://user-images.githubusercontent.com/24724371/113630094-33f6e000-961c-11eb-9522-a4321923d24b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version: Web version (FireFox v 87.0)
- Operating System: (Windows 10)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
