### ISSUE TITLE
Omnichannel > 3.13.0 > Comment is always required when closing Room

### ISSUE THREAD

**Issue by dudanogueira** [RocketChat/Rocket.Chat#21468]
### Description:

Starting at 3.13.0, even if Livechat_request_comment_when_closing_conversation is set to False, the dialog to fill the closing comment is always presented.

### Steps to reproduce:

1. Set the Option Livechat_request_comment_when_closing_conversation to False (Admin > Omnichannel)
2. Open a Rom
3. Close it

### Expected behavior:

The Room should be closed immediately. No Comment required.

### Actual behavior:

the comment dialog pops out

### Server Setup Information:

- Version of Rocket.Chat Server:  3.13.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v12.21.0
- MongoDB Version: 4.0.23 / mmapv1 (oplog Ativado)

### Client Setup Information

- Desktop App or Browser Version: Chrome Latest
- Operating System: Linux

**Comment by brunohl91** [comment]
Same problem here, even using 3.13.1
