### ISSUE TITLE
Verbatim messages in threads get their emojis rendered in the main channel view

### ISSUE THREAD

**Issue by dcermak** [RocketChat/Rocket.Chat#21477]
### Description:

When you have the option `Show thread messages in the main thread` enabled and write a message with verbatim text (i.e. in \`\`) that includes a emoji code, then the emoji is not rendered in the thread view but rendered as one in the main channel view.

### Steps to reproduce:

1. Enable `Show thread messages in the main thread` in your account settings
2. Open a new thread and type `:any_emoji_code:` (including the backticks)
3. observe the emoji being rendered in the main view

### Expected behavior:

the emoji should not be rendered in the main view

### Actual behavior:

![rc_thread_bug](https://user-images.githubusercontent.com/45594031/113866468-a945ea80-97ad-11eb-8cd2-ff744bd8488e.png)

### Server Setup Information:

Tested on open.rocket.chat on 2021-04-07

### Client Setup Information

- Desktop App or Browser Version: Firefox 87
- Operating System: Fedora Linux

### Additional context

Also tested on a internal rocket.chat server at version 3.12.3

**Comment by johncrisp** [comment]
This can be seen in open.rocket.chat

Create thread

Type in the thread  - I have substituted single quote for backticks

' :someemoji: '

Not rendered in the thread but it is in the main chat.

**Comment by hugocostadev** [comment]
It is fixed in the latest release > 5.4
