### ISSUE TITLE
Wrong domain in email

### ISSUE THREAD

**Issue by p1rox** [RocketChat/Rocket.Chat#2148]
I'm running Rocket in a Docker container with : `ROOT_URL=http://rocket.domain.com`
In Rocket settings the URL is set to : `http://rocket.domain.com`
But when I send an invitation email, I get : `http://127.0.0.1:3000` in the mail.

**Comment by dytec** [comment]
@p1rox you can change it under Administration -> SMTP -> Invitation

**Comment by p1rox** [comment]
Thanks

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/161283730-efe058f9-6c4c-4cfa-9332-0ebd8cfdc85f.png)

Where can i change the Site_URL Variable?
