### ISSUE TITLE
When I update our site, Rocketchat service stops!

### ISSUE THREAD

**Issue by BaseMax** [RocketChat/Rocket.Chat#21497]
### Description:

When I update our site, Rocketchat service stops!

### Steps to reproduce:

1.  go to website directory e.g: `cd /home/project/root/`
2. `$ npm run build`
3. my website updated, But **rocketchat** service stops!

### Server Setup Information:

```
Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
```

- Version of Rocket.Chat Server: 
- Operating System: Debian
- Deployment Method: I not sure, How can check? 
- Number of Running Instances: 10
- NodeJS Version: v12.18.4
- NPM Version: 7.7.5
- MongoDB Version: v4.4.4

**Comment by BaseMax** [comment]
I investigated the matter and I know the reason.
Our server has two gigs of RAM and two CPU cores.

When we want to re-build react-js based front-end project.
It consumes a lot of resources and causes the chat rocket to be cut even two or three times a minute.
But it connects automatically again.

At the end of the building site process, the chat rocket stops completely!
And I have to reset it manually.

```
npm run build
```

Seems npm need high of memory!
It takes several minutes and the process is very long! (SLOW)
Why should it be so slow!

https://stackoverflow.com/a/55758068

Does anyone have a suggested solution?
Thanks in advance.

**Comment by reetp** [comment]
Hi,

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

This seems to be a resource issue, not a bug.

You are effectively running a development build, not a normal install.

That requires a lot more RAM.

https://developer.rocket.chat/guides/developer/quick-start 

"During the build, memory usage will be nearly 8G, this is the minimum level of RAM recommended for development workstations"

For a normal installation you shouLd ne using this guide.

https://docs.rocket.chat/installation/manual-installation/debian

**Comment by johncrisp** [comment]
> My goal was just to announce this problem, maybe someone else will face this problem, not knowing the cause.

https://developer.rocket.chat/guides/developer/quick-start

"During the build, memory usage will be nearly 8G, this is the minimum level of RAM recommended for development workstations. (If you are not doing any development, and just deploying a Rocket.Chat server - the RAM required can be as low as 1G.)"

The solution is to either run a compiled version eg snap/docker or build from a VM that has 8Gb + ram.

If you need more support please ask in https://open.rocket.chat #support
