### ISSUE TITLE
Call alert

### ISSUE THREAD

**Issue by ikayar** [RocketChat/Rocket.Chat#21502]
When a call is initiated, an audible and visual alert should be generated to the other client.

**Comment by johncrisp** [comment]
Hi,

I'm not quite sure what is going on here.

Please help the developers by filling out a bug template. Use the ‘Bug report' button here:

https://github.com/RocketChat/Rocket.Chat/issues/new/choose

Or use the bug template here:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

This will help the developers find the bug and make Rocket.Chat a better experience.

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat

I am going to close this for now it will re-open if you provide any evidence of a bug.

Thanks.
