### ISSUE TITLE
Joining public teams fails with invalid room error

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#21500]
### Description:

Joining public teams fails in RC 3.13.1 with error `Invalid room`. Joining also fails with the same error when trying to access public teams using normal fast search.

### Steps to reproduce:

1. Create a public team
2. As an other user search for team under Directory view
3. Select and try to join the team

### Expected behavior:

You end up in the public team as a joined member

### Actual behavior:

You get an error `Invalid room`.

Searching public team:
![Screenshot from 2021-04-09 09-18-36](https://user-images.githubusercontent.com/6958942/114137936-92baa300-9915-11eb-8590-409238edff84.png)

Error after trying to join (using join button):
![Screenshot from 2021-04-09 09-25-18](https://user-images.githubusercontent.com/6958942/114137971-9e0dce80-9915-11eb-8496-5966cdebeab7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.21.0
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Any browser

**Comment by siva2204** [comment]
this works fine in version 3.14.0-develop, not getting **invalid room** error.

**Comment by Gummikavalier** [comment]
Thanks for confirming!

**Comment by tiagoevanp** [comment]
@Gummikavalier can you reproduce the error in 3.13.2 version?
I was trying to reproduce the error and I wasn't able to do that in latest version.

**Comment by Gummikavalier** [comment]
@tiagoevanp Thanks. I tested it now and it works when I choose public team under Directory.

But it stil fails when choosing one from channel search:
![Screenshot from 2021-04-19 09-13-13](https://user-images.githubusercontent.com/6958942/115189866-da98b180-a0ef-11eb-8b10-99d373f376a9.png)

The reason seems to be that the search result points at `/direct/publicteam` instead of `/channel/publicteam`.

**Comment by tiagoevanp** [comment]
Ok @Gummikavalier, this problem will be fixed in #21495 there is no necessity for search a channel not joined by user by search bar, just for the directory. (y)

**Comment by Gummikavalier** [comment]
@tiagoevanp Thanks, all good as then it won't be confusing users anymore. :+1: 

I'll close this original one as fixed in RC 3.13.2.
