### ISSUE TITLE
User shown as present but can't add or remove it from channel

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#21501]
### Description:

I've got a problem with a user inside a channel. He is mark as present but I can't add nor remove it.
I can add it indefinitely I've got the toast and the message inside the channel but he is not present.

![image](https://user-images.githubusercontent.com/1545450/114144230-643cc800-9915-11eb-944c-14ab5312d770.png)

### Steps to reproduce:

1. Go to members
2. Try to remove it
3. User is not remove

### Expected behavior:

User needs to be remove or added

### Actual behavior:

User in not added or remove

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1
- Operating System: Debian
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: Docker version
- MongoDB Version: Docker version

### Client Setup Information

- Desktop App or Browser Version: Desktop and web
- Operating System: W10

### Additional context

Active Directory based auth

### Relevant logs:

No logs

**Comment by siva2204** [comment]
I have tested this on version 3.14.0-develop, user will be removed as accepted and you will get the toast **error-user-not-in-room** when you try to remove the user again and again. updating may resolve this issue.

**Comment by avignat** [comment]
Bug still present in 3.14.0 please do something it's annoying

**Comment by avignat** [comment]
Still an issue in 3.15.0, maybe it is linked to an error with federation but federastion config test says everything is ok (DNS config)
