### ISSUE TITLE
Per channel notification preferences not all saved

### ISSUE THREAD

**Issue by chaperonRose** [RocketChat/Rocket.Chat#21503]
### Description:

In a channel, most notification preferences are not saved. Saving fire a confirmation message but when coming back to settings, they still are positioned to "défaut".

### Steps to reproduce:

1. In a channel, go to notification preferences.
2. In Desktop, select an option (not default) in "alert" or in "audio" menu.
3. Save. You get a confirmation message.
4. Go back to notification preferences and check your previous choices : they are not saved and are back to default. 

I can be reproduced with Mobile > alert and E-mail > alert options too.
NB. Desktop > Sound (to select the sound to play) works fine.

### Expected behavior:
All settings should really be saved and effective.

### Actual behavior:
see Steps to reproduce

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1
- Operating System: Linux

### Client Setup Information

- Desktop App or Browser Version: Firefox ESR and Chromium

**Comment by chaperonRose** [comment]
I see there was a similar issue 3 years ago : https://github.com/RocketChat/Rocket.Chat/issues/10787

**Comment by ECiurleo** [comment]
I can replicate this in the Mac App and Chrome

**Comment by siva2204** [comment]
I have looked into this, preferences were saved successfully in serverside (ps: reload the page), it's the frontend.
