### ISSUE TITLE
How to Use Custom Fields  in Email Content

### ISSUE THREAD

**Issue by MrR45001** [RocketChat/Rocket.Chat#21528]
hi
i add custom field in user registration like this : 

{
	"Mobile": {
		"type": "text",
		"required": true,
		"minLength": 11,
		"maxLength": 11,
		"public": true,
        "placeholder": "test",
        "class": "test"
	}
}

and i can see this field in profile

how can i use this custom field in email content???

i need sent this value in email body

thanks in advance

**Comment by ankar84** [comment]
> and i can see this field in profile

I guess you can see it right after add in Accounts - Registration.
But you need to fill that fields somehow.

I fill it during LDAP sync with `User Data Field Map` like this:

`{ "displayName": "name","mail": "email" ,"telephoneNumber":"customFields.Tel","title":"customFields.Title","department":"customFields.Department","l":"customFields.City"}`

**Comment by MrR45001** [comment]
> 
> 
> > and i can see this field in profile
> 
> I guess you can see it right after add in Accounts - Registration.
> But you need to fill that fields somehow.
> 
> I fill it during LDAP sync with `User Data Field Map` like this:
> 
> ```
> { 
> "displayName": "name",
> "mail": "email" ,
> "telephoneNumber":"customFields.Tel",
> "title":"customFields.Title",
> "department":"customFields.Department",
> "l":"customFields.City"
> }
> ```

thanks for your reply
i fill this field on registration form,
i want to send value in email content like [lname] or [fname] template.
for example use [Mobile] in email content and show value of this field in sent email

**Comment by johncrisp** [comment]
Hi,

can we move support queries to https://open.rocket.chat #support and keep github for actual bugs.

Thanks
