### ISSUE TITLE
Empty list item label and activity indicator displays together

### ISSUE THREAD

**Issue by sumukhah** [RocketChat/Rocket.Chat#21521]
### Description:
It should show only activity indicator while loading.

### Steps to reproduce:

1. Navigate to Starred messages, Mentions, Pinned messages
2. Use Network throttling, slow 3G for better view
3. It would show an empty item label and activity indicator together. 

### Actual behavior:

https://user-images.githubusercontent.com/23723464/114263340-882a0780-9a02-11eb-94ac-c0ca2f346e85.mov

### Client Setup Information
Can be reproducible in any server env, client env.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
