### ISSUE TITLE
PUsh Notification not working when embed the livechat widget in webview Android

### ISSUE THREAD

**Issue by MuhammaHamza** [RocketChat/Rocket.Chat#21532]
Hi there!

i have deployed the rocket chat instance on a separate domain and everything is working as is except the push notification. i use the live chat widget embed code and put it in a webview in android, as per the documentation the push notification should work if we disable the gateway and add the GCM project number and key. i did it exactly but still not able to get the push notifications.

any one facing the same issue?
anyone care to help me out its been 2 weeks and i am stuck at this point.

**Comment by johncrisp** [comment]
Hi, please note that Github is for issues with the core Rocket.Chat code itself and not for support requests. Your issue appears to be with your own gateway.

Please use https://forums.rocket.chat or https://open.rocket.chat for Community support.

There is also a link in the open.rocket #support channel with how to report your issue effectively.
