### ISSUE TITLE
Problems installing snap version Ubuntu - 18.04

### ISSUE THREAD

**Issue by gusarg81** [RocketChat/Rocket.Chat#21536]
### Description:

Fails to install snap version of rocketchat-server

### Steps to reproduce:

sudo snap install rocketchat-server

### Expected behavior:

To finish install like any other snap package.

### Actual behavior:

See logs below.

### Server Setup Information:

- Version of Rocket.Chat Server: latest, vía snap.
- Operating System: Ubuntu 18.04
- Deployment Method: snap

### Additional context

I don' t know if is related, but just in case: the only running snap app is wekan in the same server.

### Relevant logs:

```
...
Apr 12 16:24:36 server kernel: [5283307.281473] audit: type=1400 audit(1618255476.388:14753): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/13356/numa_maps" pid=13356 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] MongoDB starting : pid=13356 port=27017 dbpath=/var/snap/rocketchat-server/common 64-bit host=server
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] db version v3.6.14
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] git version: cbef87692475857c7ee6e764c8f5104b39c342a1
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] allocator: tcmalloc
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] modules: none
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] build environment:
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten]     distarch: x86_64
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten]     target_arch: x86_64
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManagement: { pidFilePath: "/var/snap/rocketchat-server/common/mongod.pid" }, replication: { replSet: "rs0" }, storage: { dbPath: "/var/snap/rocketchat-server/common", journal: { enabled: true }, mmapv1: { smallFiles: true } } }
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] now exiting
Apr 12 16:24:36 server rocketchat-server.rocketchat-mongo[13305]: 2021-04-12T16:24:36.402-0300 I CONTROL  [initandlisten] shutting down with code:48
Apr 12 16:24:36 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
Apr 12 16:24:36 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
Apr 12 16:24:36 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
Apr 12 16:24:36 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 5.
Apr 12 16:24:36 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
Apr 12 16:24:36 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Start request repeated too quickly.
Apr 12 16:24:36 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
Apr 12 16:24:36 server systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-mongo.
...
```

For now I've installed via docker, which works fine, but I want/need to use snap method.

Thanks in advance.

**Comment by gusarg81** [comment]
More info: as testing purposes, I've installed rocketchat-server snap into a another Ubuntu 18.04 server (which does not have any snap installed) and the install process works just fine.

Is possible that rocketchat-server snap conflics with wekan snap which uses mongodb as well?

**Comment by johncrisp** [comment]
I think the answer is most likely yes as they will both run on the same port - we can see 'port already in use'

With docker you are probably running on a bridged network making mongo only accesible to the internal rocket.chat instance.
 
You can modify snap environment variables to avoid this. Please see the documentation and close this issue accordingly.

**Comment by gusarg81** [comment]
Which snap variables does handle this? Because related to mongodb I only see these:

mongo-oplog-url                   mongodb://localhost:27017/local
mongo-url                         mongodb://localhost:27017/parties

Also, wekan uses mongodb in port 27019 so I don't see why rocketchat-server snap is conflicting here.

**Comment by gusarg81** [comment]
Also, I've tested by complete stop of wekan snap:

> snap services wekan
> Servicio       Encendido    Actual    Notas
> wekan.caddy    desactivado  inactivo  -
> wekan.mongodb  desactivado  inactivo  -
> wekan.wekan    desactivado  inactivo  -

No running mongodb instance:

> ps aux | grep mongo
> root     23726  0.0  0.0  13072  1040 pts/0    S+   11:23   0:00 grep --color=auto mongo

Still rocketchat-server snap fails to install with the same logging info:

> Apr 14 11:26:11 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:11 server kernel: [5438221.367903] kauditd_printk_skb: 268 callbacks suppressed
> Apr 14 11:26:11 server kernel: [5438221.367907] audit: type=1400 audit(1618410371.599:413631): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/24547/numa_maps" pid=24547 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten] MongoDB starting : pid=24547 port=27017 dbpath=/var/snap/rocketchat-server/common 64-bit host=server
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten] db version v3.6.14
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten] git version: cbef87692475857c7ee6e764c8f5104b39c342a1
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten] allocator: tcmalloc
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten] modules: none
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten] build environment:
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten]     distarch: x86_64
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.617-0300 I CONTROL  [initandlisten]     target_arch: x86_64
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.618-0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManagement: { pidFilePath: "/var/snap/rocketchat-server/common/mongod.pid" }, replication: { replSet: "rs0" }, storage: { dbPath: "/var/snap/rocketchat-server/common", journal: { enabled: true }, mmapv1: { smallFiles: true } } }
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.618-0300 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.618-0300 I CONTROL  [initandlisten] now exiting
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24499]: 2021-04-14T11:26:11.618-0300 I CONTROL  [initandlisten] shutting down with code:48
> Apr 14 11:26:11 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
> Apr 14 11:26:11 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
> Apr 14 11:26:11 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
> Apr 14 11:26:11 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 1.
> Apr 14 11:26:11 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:11 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:11 server kernel: [5438221.674602] audit: type=1400 audit(1618410371.903:413632): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/24612/numa_maps" pid=24612 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] MongoDB starting : pid=24612 port=27017 dbpath=/var/snap/rocketchat-server/common 64-bit host=server
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] db version v3.6.14
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] git version: cbef87692475857c7ee6e764c8f5104b39c342a1
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] allocator: tcmalloc
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] modules: none
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] build environment:
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten]     distarch: x86_64
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten]     target_arch: x86_64
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManagement: { pidFilePath: "/var/snap/rocketchat-server/common/mongod.pid" }, replication: { replSet: "rs0" }, storage: { dbPath: "/var/snap/rocketchat-server/common", journal: { enabled: true }, mmapv1: { smallFiles: true } } }
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] now exiting
> Apr 14 11:26:11 server rocketchat-server.rocketchat-mongo[24564]: 2021-04-14T11:26:11.919-0300 I CONTROL  [initandlisten] shutting down with code:48
> Apr 14 11:26:11 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
> Apr 14 11:26:11 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 2.
> Apr 14 11:26:12 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:12 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:12 server kernel: [5438222.167453] audit: type=1400 audit(1618410372.399:413633): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/24685/numa_maps" pid=24685 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] MongoDB starting : pid=24685 port=27017 dbpath=/var/snap/rocketchat-server/common 64-bit host=server
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] db version v3.6.14
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] git version: cbef87692475857c7ee6e764c8f5104b39c342a1
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] allocator: tcmalloc
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] modules: none
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] build environment:
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten]     distarch: x86_64
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten]     target_arch: x86_64
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.414-0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManagement: { pidFilePath: "/var/snap/rocketchat-server/common/mongod.pid" }, replication: { replSet: "rs0" }, storage: { dbPath: "/var/snap/rocketchat-server/common", journal: { enabled: true }, mmapv1: { smallFiles: true } } }
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.415-0300 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.415-0300 I CONTROL  [initandlisten] now exiting
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24635]: 2021-04-14T11:26:12.415-0300 I CONTROL  [initandlisten] shutting down with code:48
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 3.
> Apr 14 11:26:12 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:12 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:12 server kernel: [5438222.670352] audit: type=1400 audit(1618410372.899:413634): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/24756/numa_maps" pid=24756 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.916-0300 I CONTROL  [initandlisten] MongoDB starting : pid=24756 port=27017 dbpath=/var/snap/rocketchat-server/common 64-bit host=server
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] db version v3.6.14
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] git version: cbef87692475857c7ee6e764c8f5104b39c342a1
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] allocator: tcmalloc
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] modules: none
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] build environment:
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten]     distarch: x86_64
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten]     target_arch: x86_64
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManagement: { pidFilePath: "/var/snap/rocketchat-server/common/mongod.pid" }, replication: { replSet: "rs0" }, storage: { dbPath: "/var/snap/rocketchat-server/common", journal: { enabled: true }, mmapv1: { smallFiles: true } } }
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] now exiting
> Apr 14 11:26:12 server rocketchat-server.rocketchat-mongo[24706]: 2021-04-14T11:26:12.917-0300 I CONTROL  [initandlisten] shutting down with code:48
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
> Apr 14 11:26:12 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 4.
> Apr 14 11:26:13 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:13 server systemd[1]: Started Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:13 server kernel: [5438223.170788] audit: type=1400 audit(1618410373.399:413635): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/24823/numa_maps" pid=24823 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.415-0300 I CONTROL  [initandlisten] MongoDB starting : pid=24823 port=27017 dbpath=/var/snap/rocketchat-server/common 64-bit host=server
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] db version v3.6.14
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] git version: cbef87692475857c7ee6e764c8f5104b39c342a1
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] allocator: tcmalloc
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] modules: none
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] build environment:
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten]     distarch: x86_64
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten]     target_arch: x86_64
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1" }, processManagement: { pidFilePath: "/var/snap/rocketchat-server/common/mongod.pid" }, replication: { replSet: "rs0" }, storage: { dbPath: "/var/snap/rocketchat-server/common", journal: { enabled: true }, mmapv1: { smallFiles: true } } }
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Address already in use
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] now exiting
> Apr 14 11:26:13 server rocketchat-server.rocketchat-mongo[24772]: 2021-04-14T11:26:13.416-0300 I CONTROL  [initandlisten] shutting down with code:48
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=48/n/a
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Scheduled restart job, restart counter is at 5.
> Apr 14 11:26:13 server systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Start request repeated too quickly.
> Apr 14 11:26:13 server systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
> Apr 14 11:26:13 server systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-mongo.
>

I wonder if the problem is related to this line, about apparmor:

>  audit: type=1400 audit(1618410372.399:413633): apparmor="DENIED" operation="open" profile="snap.rocketchat-server.rocketchat-mongo" name="/proc/24685/numa_maps" pid=24685 comm="mongod" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

So, the problem seems not related to a mongodb instance running, since in this test there is None.

**Comment by johncrisp** [comment]
I do think this is really a support issue rather than a bug so I am going to close this for now. We can re-open it if we discover a bug later.

For documentation it is all here:

https://docs.rocket.chat/installation/snaps

Can you please visit https://open.rockert.chat and ask in #ubuntu-snap 

You will get more assistance there.
