### ISSUE TITLE
Distinguish between channels I'm in and the rest

### ISSUE THREAD

**Issue by jtimon** [RocketChat/Rocket.Chat#2154]
Distinguish between channels I'm in and the rest when seeing the full list of channels.
If I user is already in, say, 15 channels of a total of 18, it is not easy to see which channels you aren't in, to decide if you want to join or not.
The list of all the channels could just separate them in 2 groups.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
