### ISSUE TITLE
BigBlueButton not working

### ISSUE THREAD

**Issue by Whity07** [RocketChat/Rocket.Chat#21544]
### Steps to reproduce:

1. 
2. 

### Expected behavior:

I get redirected to BBB

### Actual behavior:

https://prnt.sc/11c4wh6

### Server Setup Information:

- Version of Rocket.Chat Server:  3.12.1
- Operating System: Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Mac OSX / Windows

### Relevant logs:

 //
 /

**Comment by johncrisp** [comment]
Hi,

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

You have not tested on the latest version of Rocket.Chat and have provided no logs or errors so this looks like a setup/support issue.

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat

Thanks.
