### ISSUE TITLE
Search by email in admin users list causes error 

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#21548]
### Description:

Searching users by email causes an error

### Steps to reproduce:

1. Go to the administration section
2. Click on Users
3. Type an email of a user you'd like to search

### Expected behavior:

I expect to have the user show up or be told no user is found

### Actual behavior:
![image](https://user-images.githubusercontent.com/23088/114618407-4f469880-9c77-11eb-99c7-ac36a3157a1b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: **3.13.1**
- Operating System: **Ubuntu 16.04.7 LTS** 
- Deployment Method: **Docker**
- Number of Running Instances: **1** 
- DB Replicaset Oplog: **yes**
- NodeJS Version: **12.2**
- MongoDB Version: **4.0**

### Client Setup Information

- Desktop App or Browser Version: **3.1.1**
- Operating System: Linux Mint

### Additional context

N/a

### Relevant logs:

```I20210413-20:49:34.072(0) server.js:204 API ➔ debug get users.list threw an error: TypeError: Cannot read property 'total' of undefined  at Object.get (app/api/server/v1/users.js:273:48)   at app/api/server/api.js:394:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 ```

**Comment by ARKEOLOGIST** [comment]
This might be due to some of the changes introduced in #21469. I will try and have a look when I can.

**Comment by Jeanstaquet** [comment]
I can look too
