### ISSUE TITLE
Aggregate method failing without any information

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat#21551]
### Description:

Before I start, I am working on an extremely old version of RocketChat (0.57.2) with the DB Migration 99; we plan on upgrading in the very near future but have an immediate bug that I need to fix until we upgrade. We have this custom function that retrieves the total number of unread messages by a user. To do this, we use this aggregate function

```
   console.log('Check 1');
   const result = RocketChat.models.Subscriptions.model.aggregate([
        {
          $match: {
            'u._id': user._id,
          },
        },
        {
          $group: {
            _id: "$u.username",
            unreadCount: {
              $sum: "$unread"
            },
            alert: {
              $sum: {
                $cond: [{$eq: ["$alert", true]}, 1, 0]
              },
            },
          },
        },
      ]);
      console.log('Check 2');
```

When I run this aggregate in the mongo console I get the expected outcome without error. When this code executes, the first log line is executed and then the code just stops executing and the second log line is never executed. I confirmed the user._id is a valid user ID and I used it in the console and it worked fine...

Is there something incorrect about my aggregate method in code? Why would this code just stop executing outright?

### Steps to reproduce:

1. Create an aggregate function
2. Watch it fail when it's ran

### Expected behavior:

I'd expect the aggregate function to run correctly and the second log line to be ran.

### Actual behavior:

Code just stops executing without an error or warning

### Server Setup Information:

- Version of Rocket.Chat Server: 0.57.2
- Operating System: Linux
- Number of Running Instances: 2
- DB Replicaset Oplog: Disabled
- NodeJS Version: v4.8.4
- MongoDB Version: 3.6.21

**Comment by johncrisp** [comment]
Hi,

This really seems to be an issue with your own code and not actually a bug in Rocket.Chat

Can you please ask your support questions in open.rocket.chat or forums.rocket.chat

Thanks
