### ISSUE TITLE
Tooltip appears outside viewport

### ISSUE THREAD

**Issue by billynoah** [RocketChat/Rocket.Chat#21566]
### Description:

Tooltip appears outside viewport

### Steps to reproduce:

Hover over unread threads in top nav bar and note the tooltip which reads "Threads" flies north of the viewport boundry and appears with the text offscreen.

### Expected behavior:

Tooltip text should remain visible.

### Actual behavior:

Tooltip text is not visible.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1
- Operating System: Ubuntu 20.04
- Deployment Method: Snap
- Number of Running Instances: 1
- NodeJS Version: v12.21.0
- MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 78.8.0esr 
- Operating System: OSX 10.11

![Screen Shot 2021-04-14 at 5 00 30 PM](https://user-images.githubusercontent.com/3309911/114779138-ba5da100-9d43-11eb-97f2-ceb3dd36481e.png)

**Comment by BadalSherpa** [comment]
@billynoah can you check after changing your screen dimensions as it looks okay at my end.
![2021-04-20](https://user-images.githubusercontent.com/62988743/115291377-4d4a7100-a172-11eb-853f-6c1ba87f0eef.png)

**Comment by billynoah** [comment]
@BadalSherpa - I'm not sure I understand.  I cannot resize my browser window with the tooltip active because I would have to move my mouse away from hovering over the tooltip.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
