### ISSUE TITLE
Markdown is not rendered in message attachments

### ISSUE THREAD

**Issue by fleaz** [RocketChat/Rocket.Chat#21574]
### Description:

Hey,
we use the hosted RocketChat.Cloud from you and just got upgraded to 3.11.4 last night. Ever since RocketChat stopped rendering markdown in message attachments. We have quite a few integrations in our company that send markdown styled text via message attachments  which are all broken now.

### Steps to reproduce:

1. Send a message via `/api/v1/chat.postMessage` and add a text attachment with markdown styled text

### Expected behavior:
I want the markdown in the text to be rendered.

### Actual behavior:
Markdown is not rendered
![Screenshot_2021-04-15_10:20:02](https://user-images.githubusercontent.com/2489598/114837603-2d165d00-9dd4-11eb-9522-09c2b8e3c166.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.4
- Operating System: -
- Deployment Method: Cloud Hosted Service
- Number of Running Instances: -
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.8 

### Client Setup Information

- Desktop App or Browser Version: App 3.1.1 and Website in Chromium 89 both broken
- Operating System: Linux

**Comment by johncrisp** [comment]
Hi,

thanks for contacting us. As you are a supported customer can you please contact support directly for assistance please?

You should be able to log a ticket through the portal here:

https://desk.rocket.chat/portal/en/home

Or the direct link is at the bottom:

https://desk.rocket.chat/portal/en/newticket

Thank you.

**Comment by johncrisp** [comment]
FYI - you can also email support (at) rocket.chat but please make sure you use the email that you have registered to your account otherwise you may not end up in the right support area!!

**Comment by fleaz** [comment]
Hey John, 
thanks for the reply.

a) This pretty much feels like a bug in RocketChat to me*  and not something that is related to the hosting platform. So yes, contacting the support will probably help me in regards of downgrading the version but nonetheless if this is actually a bug, this issue belongs here imho.

b) Not sure if you are in any way related to RC, but if yes, I would suggest to fill out your profile a bit more. A completly empty account which was created a week ago is not very trustworthy ;)

Best,
Felix

* While searching through the tickets earlier this morning I saw a reply from one of the devs that they have rewritten the attachment code, so this would match quite well with my issue.

**Comment by johncrisp** [comment]
> Hey John,
> thanks for the reply.
> 

NP :-)

> a) This pretty much feels like a bug in RocketChat to me* and not something that is related to the hosting platform. So yes, contacting the support will probably help me in regards of downgrading the version but nonetheless if this is actually a bug, this issue belongs here imho.
> 

Sorry - we may have wires crossed.

> Cloud Hosted Service

If you are a client and it is a bug in Rocket.Chat hosted on their cloud then it needs to go through support. It probably won't get picked up here. They can then work on a fix - at 3.11.x you are a few versions behind current so it may well be there is already a fix and they can apply it.

If you are self hosting you need to test on latest 3.13.x As you mentioned you saw a fix here already, and the answer will be to upgrade.

Let me know which it is please?

> b) Not sure if you are in any way related to RC, but if yes, I would suggest to fill out your profile a bit more. A completly empty account which was created a week ago is not very trustworthy ;)

Yes, I am the a new Community Manager here and still catching up with filling things out, and I literally did this 20 minutes ago !! I keep forgetting this is my new work account, and not my personal one...!

>     * While searching through the tickets earlier this morning I saw a reply from one of the devs that they have rewritten the attachment code, so this would match quite well with my issue.

Have you got the link to the bug? Just paste it here for reference.

**Comment by fleaz** [comment]
> Let me know which it is please?

Yes, our RC is hosted in their cloud. I already opened a ticket yesterday. Thanks for steering me in that direction :)

> Yes, I am the a new Community Manager here and still catching up with filling things out, and I literally did this 20 minutes ago !! I keep forgetting this is my new work account, and not my personal one...!

Ah, I see. Then I wish you a great start and have fun in your new position :tada: 
 
> Have you got the link to the bug? Just paste it here for reference.

I was talking about
https://github.com/RocketChat/Rocket.Chat/issues/20766#issuecomment-779265059
where Yash said that they have rewritten the attachment part. and the other issue looks pretty familiar to mine so I assumed that they are related.

**Comment by fleaz** [comment]
We have been upgraded to 3.13.2 and the problem is gone now.
