### ISSUE TITLE
The app does not prevent the user from uploading files that are not gif/png/jpg/jpeg in the custom emoji

### ISSUE THREAD

**Issue by Jeanstaquet** [RocketChat/Rocket.Chat#21576]
### Description:
The app does not prevent the user from uploading files that are not gif/png/jpg/jpeg in the custom emoji. 

### Steps to reproduce:

1. Have an admin account 
2. Go to custom emoji
3. Try to upload any file

### Expected behavior:
The app should prevent the user from uploading any 

### Actual behavior:
The app should prevent the user from uploading files that are not images

https://user-images.githubusercontent.com/45966964/114871873-0834e080-9dfa-11eb-8fef-8d64a4b69c99.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Linux
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Linux

**Comment by KevLehman** [comment]
Fixed by #21593
