### ISSUE TITLE
The create Channel button  in teams crashes the app

### ISSUE THREAD

**Issue by shrinish123** [RocketChat/Rocket.Chat#21585]
### Description:

Whenever you go to Teams to create a channel and press on 'create Channel button ' the app crashes.

### Steps to reproduce:

1. Go to Teams 
2. Go to Teams Channels 
3. Click on Create New Button 

### Expected behavior:

It should open the Create channel modal

### Actual behavior:
The app crashes

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13
- Operating System: Windows
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.4
- MongoDB Version:4.x

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows

**Comment by dudanogueira** [comment]
Thanks for your contribution! This is fixed in latest 5.2-develop. Closing for now.
