### ISSUE TITLE
Why 1k users recommended?

### ISSUE THREAD

**Issue by Jinn42** [RocketChat/Rocket.Chat#21582]
Hi, I would like to use the free version of rocketchat in my own project, but I saw 'Recommended 1k Users' on the official website 'https://rocket.chat/pricing/' . Just be curious, since it is an open source and we could compile it ourselves, why there is a user limit?

**Comment by CAberry** [comment]
Hello,

The only limit, like any open source project is your capability of clustering instances, HA and distributed file system.
Enterprise version of RC also provides more then the community edition (Documentations, features, support etc...)

Hope this helped you a bit or at least brings you to the right path.

Greetings,

**Comment by Jinn42** [comment]
So, if we build the services like DFS ourselves rather than adapting the one used in community version, there wouldn't be user limit?

**Comment by johncrisp** [comment]
Hi,

we like to keep github for bugs in Rocket.Chat

Can you take this conversation to https://open.rocket.chat and we can explain more there? You'll find me in #support and I'm happy to answer any queries

Thanks.
