### ISSUE TITLE
[Teams] Wrong user priviledges and locales

### ISSUE THREAD

**Issue by CAberry** [RocketChat/Rocket.Chat#21584]
### Description:

A new user can change public rooms to "Teams"

### Steps to reproduce:

1. Create a new user from an invite link
2. Join a public room
3. Click the little "room info" ("i" top left corner)
4. You can see two buttons "Move to Team" & "Convert to team"

![image](https://user-images.githubusercontent.com/35067345/114899785-8ea9ec00-9e13-11eb-8de2-40de82c28134.png)

### Expected behaviour:

Move and Convert should only be enable / visible for admins and room owner. 
Text is displayed in English instead of local language. Here, it should have been fr-FR

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1

**Comment by Jeanstaquet** [comment]
I'm working on it :)
