### ISSUE TITLE
Directory -> Users page crashes if a user has no emails

### ISSUE THREAD

**Issue by mgrybyk** [RocketChat/Rocket.Chat#21580]
### Description:

Directory -> Users page crashes if a user has no emails

### Steps to reproduce:

1. Make sure there is a user without emails
2. Go to Directory -> Users
3. Go to the page where the user from step 1 exists

### Expected behavior:

the page should be shown normally

### Actual behavior:

the page crashes
```
TypeError: Cannot read property 'address' of undefined
    at eval (/client/views/directory/UserTab.js:1)
```
![image](https://user-images.githubusercontent.com/25589559/114882720-872f1680-9e04-11eb-8696-868275383196.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1

### Client Setup Information

- Desktop App or Browser Version: Chrome 89

### Additional context

It happens here https://github.com/RocketChat/Rocket.Chat/blob/84d547055ea1ce08e55d7a95ed99dd9c0be852b9/client/views/directory/UserTable.js#L141

`{emails && emails[0].address}` should be changed to `{emails && emails[0] && emails[0].address}`

**Comment by johncrisp** [comment]
Hi and thanks for finding that!

Can you test it on the latest dev code to make sure it hasn't been fixed?

If it hasn't then please do a PR linked to this bug. It is exactly this sort of work that helps makes Rocket.Chat a better product!

**Comment by Jeanstaquet** [comment]
i'm working on it

**Comment by Jeanstaquet** [comment]
@mgrybyk I have not been able to reproduce it, even by deleting fields in the db for the user

**Comment by mgrybyk** [comment]
Make sure emails array exist but it's empty @Jeanstaquet

**Comment by mgrybyk** [comment]
![image](https://user-images.githubusercontent.com/25589559/114903858-805dcf00-9e17-11eb-8e4a-468c5acef257.png)

**Comment by Jeanstaquet** [comment]
@mgrybyk ok alright, i will try again

**Comment by mgrybyk** [comment]
it still fails for me in the latest develop branch. The error looks differently though
![image](https://user-images.githubusercontent.com/25589559/114908441-64a8f780-9e1c-11eb-8296-aecd9cd13f0f.png)

**Comment by Jeanstaquet** [comment]
@mgrybyk Without removing the db, how did you manage to get a user without an email address?

**Comment by siva2204** [comment]
@mgrybyk empty emails array will also crash when editing user!
btw how to register users without email?

**Comment by mgrybyk** [comment]
Good question, trying to figure out. I used OAuth for that but not sure.

**Comment by Jeanstaquet** [comment]
I also had a user who didn't have an email, we need to know how this is done
