### ISSUE TITLE
Restrict non-admin members create a new post or comment in a public channels

### ISSUE THREAD

**Issue by valessiobrito** [RocketChat/Rocket.Chat#2159]
Considering the behavior of a public channel for more than 2000 users.
Would you like to configure which users could make posts on this public channel.
So everyone could receive "notifications".
Could be other public channels, plus a specifically need a moderation of posts.

I'm evaluating the use RC by the Brazilian government, initially, only a small group of 50-100 users, but already imagining to 2000 users or more.

**Comment by defib** [comment]
#2132

**Comment by valessiobrito** [comment]
duplicate of #825
