### ISSUE TITLE
Close button at the header of chat in Omnichannel isn't working

### ISSUE THREAD

**Issue by Divyani18** [RocketChat/Rocket.Chat#21604]
### Description:

Can't close an opened chat by clicking on the close button.

### Steps to reproduce:

1. Go to Omnichannel --> Current chats
2. Click on any of the chats.
3. Click on Options --> Contact Chat History
4. Click on any of the chats from the list.
5. Try closing it by clicking on the close button.

### Expected behavior:

Clicking on the 'Close Button' should close the opened chat.  

### Actual behavior:

'Close Button' isn't responding.

https://user-images.githubusercontent.com/44610854/115016877-ab7e0800-9e83-11eb-8337-cf2916270773.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Linux (Ubuntu 18.04)
- Number of Running Instances: 1
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Browser Version: Google Chrome 90.0.4430.72
- Operating System: Linux (Ubuntu 18.04)

**Comment by MartinSchoeler** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/27302
