### ISSUE TITLE
File item doesn't get removed from the files list on deleting

### ISSUE THREAD

**Issue by Divyani18** [RocketChat/Rocket.Chat#21627]
### Description:
File item doesn't get removed from the files list on deleting. It continues to appear in the files list of the channel even after getting deleted.

### Steps to reproduce:

1. Go to a channel.
2. Click on 'Files'.
3. Delete a file. (Observe files list after deleting the item.)

### Expected behavior:

Deleted file should get removed (disappear)  immediately from the files list.

### Actual behavior:

Deleted file continues to appear in the files list of the channel, even after getting deleted. It disappears from the list only on refreshing the page or closing the files list and reopening it again.

https://user-images.githubusercontent.com/44610854/115113565-fd449200-9f58-11eb-8320-0d07a09326a0.mp4

https://user-images.githubusercontent.com/44610854/115113576-0c2b4480-9f59-11eb-95cb-edcc74ddcd63.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Linux (Ubuntu 18.04)
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Browser Version: Chrome 90.0.4430.72
- Operating System: Linux (Ubuntu 18.04)

**Comment by aditya-mitra** [comment]
Hello @Divyani18 ,
If you close and open the _files list_ again, you will that entry does not exist.

**Comment by Divyani18** [comment]
Hi @aditya-mitra, 
I did mention what you are saying in the 'actual behavior'.
The issue is that it doesn't immediately disappear from the files list on deleting and gets removed from the list only on refreshing the page or closing and opening the files list again.

**Comment by aditya-mitra** [comment]
If you are working on a fix, you might need to rerender the files rows when there is the `onClickDelete` function is called.
https://github.com/RocketChat/Rocket.Chat/blob/d433a1c5c00995adedcae5bc396c86aa497cf1de/client/views/room/contextualBar/RoomFiles/RoomFilesWithData.js#L17

**Comment by siva2204** [comment]
> If you are working on a fix, you might need to rerender the files rows when there is the `onClickDelete` function is called.
> https://github.com/RocketChat/Rocket.Chat/blob/d433a1c5c00995adedcae5bc396c86aa497cf1de/client/views/room/contextualBar/RoomFiles/RoomFilesWithData.js#L17

have to do the same if a file message is deleted from room chat
