### ISSUE TITLE
Cannot login with google account

### ISSUE THREAD

**Issue by khanhduong29** [RocketChat/Rocket.Chat#21620]
![image](https://user-images.githubusercontent.com/66000932/115099187-785c7700-9f5e-11eb-83dd-8523b8d5f2c6.png)

**Comment by johncrisp** [comment]
Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat

Thanks.
