### ISSUE TITLE
If an admin creates a custom status, it will not be taken into account 

### ISSUE THREAD

**Issue by Jeanstaquet** [RocketChat/Rocket.Chat#21630]
### Description:
The admin, can create custom status that should change ours when we use it. But currently when we choose a status created by an admin, it does not change our status. It only displays the status type. If the feature exists, it should change our status, otherwise it will be useless. 
I've seen the different issues and PRs on this subject, but I think that here we keep what was decided in these PRs, except that we take into account the feature

### Steps to reproduce:

1. Go to admin
2. Create a custom status 
3. Try to use this status

### Expected behavior:
When you use the custom status created by an admin, you should be able to use it

### Actual behavior:
When we use the custom status created by an admin, it does not change our status

https://user-images.githubusercontent.com/45966964/115128012-260d6b80-9fdb-11eb-9cf0-9dc9295c6181.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Linux
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Linux

**Comment by ghulamghousdev** [comment]
It works fine on my end.

**Comment by Jeanstaquet** [comment]
@ghulamghousdev Which part of the issue works fine for you ?

**Comment by xWyatt** [comment]
Wondering if there's been any update to that PR. We finally got our Rocket.Chat instance upgraded and starting running into this issue.

Is there a quick-fix other than patching with your PR?

**Comment by chrisi51** [comment]
any progress?!

Its really annoying to have those custom status set and nobody can use it for a really long time now because the status is not set properly.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
