### ISSUE TITLE
[UI] No hover effect on message box and icons in it

### ISSUE THREAD

**Issue by ghulamghousdev** [RocketChat/Rocket.Chat#21632]
### Description:
In Omnichannel, when a user hovers over the message box, emoji picker icon, audio message icon, and on file upload icon, there is no hover effect. When hovering over the message box, the cursor is changed to text but the border color remains the same. Similarly, for the emoji picker icon, audio message icon, and file upload icon, the cursor changes to a pointer but the color of the icons remains the same. 

### Steps to reproduce:

1. Open any channel in the Omnichannel.
2. Hover on any one of the mentioned icons.

### Expected behavior:
We can add a hover effect and change the color of the icons and border of the message box.

### Actual behavior:
While hovering on the above-mentioned icons, the cursor changes but no change in the colors of the icon.

https://user-images.githubusercontent.com/52177956/115130079-d4c6a180-a005-11eb-995a-bfcb7f78cfe5.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Windows 10
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

Desktop App or Browser Version: Chrome 88.0

**Comment by sumukhah** [comment]
Copy of #21068

**Comment by ghulamghousdev** [comment]
@sumukhah to be honest, I could find that issue opened earlier. but I thanks for pointing out and I guess there's no bad in improving something that's not been improved by a month or so.
