### ISSUE TITLE
Desktop notifications don't work in Chrome with 0.16.0 on Heroku

### ISSUE THREAD

**Issue by loop** [RocketChat/Rocket.Chat#2163]
I have 0.16.0 version of Rocket.Chat installed on Heroku and notifications don't work.

When I receive a message, direct message or a @ mention no notification is shown. I have tested to make sure that it is not Chromes fault and it isn't. WhatsApp and other notifications come through just fine.

Is there some kind of setting I need to enable?

![Install Details](http://i.imgur.com/ybFcla7.png)

**Comment by loop** [comment]
Just tested the https://demo.rocket.chat and desktop notifications seem broken there too. Tried it with Chrome (Windows and Mac) and Safari (Mac)

**Comment by marceloschmidt** [comment]
Notifications should be working on more recent versions. Could you test on latest, please? Thanks.
