### ISSUE TITLE
Room names are not displayed correctly in the admin's RoomAutoComplete 'users in roles'

### ISSUE THREAD

**Issue by Jeanstaquet** [RocketChat/Rocket.Chat#21639]
### Description:
When you go to the list of users of a role, and you want to see the list of rooms to choose one, you only see its rid. The placeholder in the input field is also incorrect

### Steps to reproduce:

1. Go to the admin
2. Go to preferences
3. Choose a role and see the users for this role

### Expected behavior:
The names of the rooms should be displayed normally

### Actual behavior:
The names of the rooms are not displayed normally

https://user-images.githubusercontent.com/45966964/115171106-97741980-a0c2-11eb-9093-b74ae5c63d95.mp4
### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Linux
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Linux

**Comment by Darshilp326** [comment]
@Jeanstaquet Hello! I was not able to reproduce the issue.

**Comment by Jeanstaquet** [comment]
Hello @Darshilp326, Interesting, so all the rooms are displayed correctly in the owner category ? Have you tried to search discussions too for example?
I will test again with a blank set up

**Comment by Darshilp326** [comment]
@Jeanstaquet Ohh my bad i missed the discussion channels :/

**Comment by dyogaharshitha** [comment]
.take
