### ISSUE TITLE
Permission reset on restart

### ISSUE THREAD

**Issue by lvh1** [RocketChat/Rocket.Chat#2164]
When restarting the server, all permissions reset to default. This is the case for both custom permission groups and the standard groups. 

Steps to reproduce:
- create a custom permission group 'test'
- assign all permissions to it
- reboot the server
- go to the permissions of that group, only the 'mail-messages' and 'access-mailer' permissions will be assigned.

**Comment by rajatkumarpati** [comment]
Same issue here.

**Comment by voxtobox** [comment]
+1

**Comment by rebeld** [comment]
Any status on this? This bug is biting us pretty hard, and we'd love to see it resolved.

**Comment by sampaiodiego** [comment]
I'm sry for the late response. I didn't get time to take a look at this before.
It's now fixed on `develop` branch.

**Comment by lvh1** [comment]
Thank you.
