### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by joaoantoniozerbielli** [RocketChat/Rocket.Chat#21646]
Good Morning,
i have an problem to access rocketchat, when i try to talk with some friends, it bug and pops up a black screen, but it just bug with a some users. I have tried to change to Rocket chat, but pops up the same problem.
what should i do? or what should my friend do?
![Screenshot_1](https://user-images.githubusercontent.com/82823326/115251379-e04ac300-a100-11eb-962d-5ac9ef7f38f0.png)
![Screenshot_2](https://user-images.githubusercontent.com/82823326/115251383-e0e35980-a100-11eb-918b-8a562c8b5118.png)

**Comment by Jeanstaquet** [comment]
I've seen this problem before, I always wonder why it appears

**Comment by Jeanstaquet** [comment]
Hello @joaoantoniozerbielli,  Did you by any chance see the log?

**Comment by johncrisp** [comment]
@joaoantoniozerbielli 

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

Can you please fill in the bug template correctly and please test this on the latest release?

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Thank you.
