### ISSUE TITLE
Page not found 404

### ISSUE THREAD

**Issue by lupael** [RocketChat/Rocket.Chat#21654]
### Description:

Wrong link from RocketChat website https://rocket.chat/bots/ 

### Steps to reproduce:

1. Go to https://rocket.chat/bots/
2. Click on Quick Start Guide Hubot , Botkit, Rasa bot and botpress bot
3. Those link goes to wrong page where shows page not found 404 errors https://docs.rocket.chat/bots/create-and-run-a-bot/hubot-bot

### Expected behavior:
Correct url is https://docs.rocket.chat/guides/bots/running-a-hubot-bot

### Actual behavior:

![Screenshot_2021-04-20-04-57-16-214_com android chrome](https://user-images.githubusercontent.com/43011721/115313347-e7bbac00-a194-11eb-8d5a-de876ff89400.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by johncrisp** [comment]
Can you please open this under documentation?

https://github.com/RocketChat/docs

Thanks.
