### ISSUE TITLE
Global Search with unchecked box

### ISSUE THREAD

**Issue by xi67** [RocketChat/Rocket.Chat#21659]
### Description:

When you click on the conversation search (the right one), the global search is unchecked but the search is global.
The global search box does not reflect the actual search.

### Steps to reproduce:

1. Click on the conversation search button
2. add some text
3. the search is global without checked it

### Expected behavior:

The box is checked by default as the default search is global or let the box unchecked but change the actual default search.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.2
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: wiredTiger
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.13

### Client Setup Information

- Desktop App or Browser Version: App 3.1.1 and bowser
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Can you try testing on https://open.rocket.chat as well just to see if it still exists in latest?

Thanks.

**Comment by aaa-a-a-a-aaa** [comment]
Global search appears to be disabled on open.rocket.chat so I don't see how that would be possible.

**Comment by danielfl** [comment]
**Workaround**: check and then uncheck the Global search checkbox.

**Comment by scrivna** [comment]
I can confirm that we also have this issue on our instance running 3.15.0 (current latest version)

**Comment by ankar84** [comment]
Hey, @johncrisp 
I can confirm that bug on latest 3.15.0 too
It's a front-end bug I guess.

**Comment by ankar84** [comment]
And still an issue in 3.16.0
![image](https://user-images.githubusercontent.com/4023037/123749915-9f201d80-d8be-11eb-9405-09b6c262ed60.png)

**Comment by xi67** [comment]
Stil present on 3.16.2

**Comment by ankar84** [comment]
Still an issue in 3.16.3

**Comment by debdutdeb** [comment]
Present in 3.17.0

**Comment by debdutdeb** [comment]
We had a meeting with the product team today. Good news, this should be fixed in the next September or October release. 

Thank you everyone here for keeping the issue updated 🙌🏼

**Comment by noobbbbb** [comment]
What's This?
https://github.com/RocketChat/Rocket.Chat/pull/20594

**Comment by ankar84** [comment]
> We had a meeting with the product team today. Good news, this should be fixed in the next September or October release.
> 
> Thank you everyone here for keeping the issue updated 🙌🏼

Still an issue in recent 4.2.0 release.

**Comment by ankar84** [comment]
> We had a meeting with the product team today. Good news, this should be fixed in the next September or October release.
> 
> Thank you everyone here for keeping the issue updated 🙌🏼

@debdutdeb please send a reminder to Product team about that issue

**Comment by ankar84** [comment]
Actually first report about that issue is https://github.com/RocketChat/Rocket.Chat/issues/20595
And it's already with community fix!!
And without any attention from team side.

**Comment by serjotaylor** [comment]
+1 fix from community.

**Comment by MightyGoldenOctopus** [comment]
+ 1 for the fix, pwweease merge

**Comment by vinogradovia** [comment]
Still an issue in 5.1.4

**Comment by vinogradovia** [comment]
#25568

**Comment by MightyGoldenOctopus** [comment]
1 year to fix, 9 months to merge, well I'm glad to have switched to Slack Pro ^^
