### ISSUE TITLE
Rooms and Users in administration not showing up in Safari

### ISSUE THREAD

**Issue by Kartik18g** [RocketChat/Rocket.Chat#21662]
### Description:

When you try to open users or rooms section within the administration on safari, nothing shows up.

### Steps to reproduce:

1. Open Rocket.Chat on safari
2. Navigate to administration>Rooms or administration/Users
3. Nothing will show up

### Expected behavior:
Rooms and Users should be visible

<img width="1440" alt="Screenshot 2021-04-20 at 3 30 42 PM" src="https://user-images.githubusercontent.com/70897225/115377571-62b0b100-a1ed-11eb-8663-8dca77e72b39.png">

### Actual behavior:
Blank screen shows up
<img width="1440" alt="Screenshot 2021-04-20 at 3 32 02 PM" src="https://user-images.githubusercontent.com/70897225/115377817-98559a00-a1ed-11eb-88e5-b4b2f1d03147.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/) provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

(Tested on Safari 16.4)
---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
