### ISSUE TITLE
Add custom sound form submits even without adding a file

### ISSUE THREAD

**Issue by PriyaBihani** [RocketChat/Rocket.Chat#21664]
### Description:
When we try to add a custom sound in admin panel, the submit button gets enabled as soon as we enter a name. Making it possible for user to submit without uploading a file which results in an error "can not read property name of undefined". 

### Steps to reproduce:

1. Go to the admin panel
2. Go to custom sounds
3. Try to add a custom sound without name.

### Expected behaviour:

Submit button should remain disabled until both name and file is added.

### Actual behavior:

Button gets enabled as soon as a name is added thus making it possible to submit form.
<img width="438" alt="Screenshot 2021-04-20 at 3 55 06 PM" src="https://user-images.githubusercontent.com/69837339/115382123-f2f0f500-a1f1-11eb-9dbe-15bd7fd6e456.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
Recently we did some refactoring in this section (#25128) and we added validation for the empty file as well.
Thanks a lot for your help @PriyaBihani
