### ISSUE TITLE
Volume Mixer icon is bugged

### ISSUE THREAD

**Issue by Wazanator** [RocketChat/Rocket.Chat#2166]
Opened up my volume mixer to adjust Rocket.Chat and discovered it appears to have a bugged icon that covers up the slider.

![image](https://cloud.githubusercontent.com/assets/2752911/12903059/75481510-ce8a-11e5-9583-e953c1d2ba77.png)

OS: Windows 8.1 (running classic shell as well if that matters)

Let me know if you need any other info!

**Comment by graywolf336** [comment]
Are you running the latest beta? If not, try that and report back

**Comment by dogatemycomputer** [comment]
I tested with the latest beta and this was corrected on Windows 7.

**Comment by engelgabriel** [comment]
@Wazanator if you are using the latest beta and this is still a bug, please reopen?
