### ISSUE TITLE
Impossible to create a jitsi conference inside a team

### ISSUE THREAD

**Issue by bseclier** [RocketChat/Rocket.Chat#21670]
### Description:

Inside a team, we can't create a new jitsi conference. We don't have the phone logo top right.

### Steps to reproduce:

1. Create a team
2. Be a member of it
2. You can't create a jitsi conference

### Expected behavior:

We can, like any other channel.

### Actual behavior:

We don't have the phone logo top right :
![image](https://user-images.githubusercontent.com/3954149/115392554-fcbe2c80-a1e0-11eb-8204-1af18f475f10.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.2
- Operating System: CentOS
- Deployment Method: docker
- Number of Running Instances: 6 
- DB Replicaset Oplog: 
- NodeJS Version: 12.21
- MongoDB Version: 3.6.17

### Client Setup Information

- Desktop App or Browser Version: both desktop and browser versions
- Operating System: any

**Comment by johncrisp** [comment]
Hi,

I'm not sure that Teams was meant to be used this way. They are a way of managing multiple users.

https://docs.rocket.chat/guides/user-guides/teams

The calls are meant to be via the Channels.

This is potentially feature request (Rocket isn't actually broken and there are no errors).

I'll leave this here for now for a dev to consider.

**Comment by bseclier** [comment]
Hi,
I understand your point of view, but we can do anything like a regular channel inside a team, except a jitsi call.
If calls are not meant to be done inside a team, neither chat or file sending should be possible, imho.

Cheers,

**Comment by matheusbsilva137** [comment]
Hey, @bseclier
It is currently possible to enable video conferences in teams by enabling the "Enable for Teams" setting under **Administration > Video Conference > Jitsi**. Feel free to reopen this issue if there's still anything missing 🙂 . Thanks for pointing this issue 🚀
