### ISSUE TITLE
Changing room info resets "Hide system messages" flag

### ISSUE THREAD

**Issue by mhaaz** [RocketChat/Rocket.Chat#21699]
### Description:
Whenever I change any of the room info (description, announcement, etc.) this resets the room setting which is supposed to hide system messages.

### Steps to reproduce:

1. Go to "Room info" in a channel where you have privileges to change the room info.
2. Toggle on the "Hide system messages" setting. Confirm that this change itself is not posted in the channel.
3. Close and reopen "Room info". The setting was persisted correctly and is still there.
4. Change an unrelated field in "Room info", e.g. add a letter into the room description (or announcement, or roomname... )
5. Click on "Save" in the Room info panel.

### Expected behavior:

The changed room info should be saved, but without triggering a system message to be posted in the chat.

### Actual behavior:

The room info is changed. BUT.
The change is posted as a system message, although they are supposed to be hidden.
The toggle control to "Hide system messages" stays enabled. Reopening the Room info shows that it is now actually disabled.

### Client Setup Information

- Desktop App or Browser Version: 2.15.3
- Operating System: Windows 10

### Server Setup Information:

I don't operate the server for my organization but I can investigate this specs **iff** they are relevant. This is however most probably a client-side issue.

- Version of Rocket.Chat Server: 
- Operating System:  
- Deployment Method: 
- Number of Running Instances:
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

> I can investigate this specs if they are relevant.

These details are **always** relevant. It is the first thing we look for. That tells us if your server is up to date as often an update/upgrade will fix your issue.

Hence we ask for that information in the bug template.

Two issues - one is the server version, the other is the app version. Make sure you test on the latest versions of both please. With the app you can try testing on https://open.rocket.chat - create your own channel.

You may want to speak to your system administrator and get them to follow up here.

Thanks.

**Comment by chaabdullah** [comment]
@saachaz

**Comment by Himangshu1086** [comment]
Can anyone guide me how to setup the repo locally to work on this issue ? I am new to open source..
