### ISSUE TITLE
Rocketchat data storage locations

### ISSUE THREAD

**Issue by dogatemycomputer** [RocketChat/Rocket.Chat#2169]
I would like to write some documentation on how to backup / restore Rocketchat.    All of the documentation I can find says we just need to dupe the MongoDB databases but this is incomplete.   Just migrating the DB did not include the Layout settings.  I'm not sure what else was missed. 

If the developers could just tell me where all the app data is stored then I could write a Wiki article and help others troubleshoot. 

I should note that I am much more familiar with linux.

**Comment by buggsdummy** [comment]
+1

**Comment by marceloschmidt** [comment]
@dogatemycomputer sorry for the delayed response! We're catching up with old issues now... 
Are you still interested in making that article? I can help you with some info, if you need. Thanks for the support.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

This is no actual issue. Since we have a forum now, I would suggest discussing this maybe over at: https://forums.rocket.chat/c/community-support

Thanks for your effort and understanding.

Cheers
Thomas
