### ISSUE TITLE
BBB is not working

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#21691]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.2
- Operating System: ubuntu 18.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version:4.0.24 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: FF latest
- Operating System: ubuntu, ms 10

### Relevant logs:

Exception while invoking method bbbJoin Error: failed [404] 1618959131608404Not FoundNo message available//bigbluebutton/api/hooks/create at Object.exports.makeErrorByStatus (packages/http.js:182:10) at Request._callback (packages/http.js:142:24) at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22) at Request.emit (events.js:315:20) at Request.EventEmitter.emit (domain.js:483:12) at Request. (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10) at Request.emit (events.js:315:20) at Request.EventEmitter.emit (domain.js:483:12) at IncomingMessage. (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:421:28) at IncomingMessage.emit (events.js:327:22) at IncomingMessage.EventEmitter.emit (domain.js:483:12) at endReadableNT (_stream_readable.js:1220:12) at processTicksAndRejections (internal/process/task_queues.js:84:21) => awaited here: at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12) at Server.apply (packages/ddp-server/livedata_server.js:1638:22) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:263:26) at app/api/server/api.js:394:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js123412) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9

**Comment by ali-alhaidary** [comment]
Exception while invoking method bbbJoin Error: failed [404] <Map><timestamp>1618959131608</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>//bigbluebutton/api/hooks/create</path></Map>     at Object.exports.makeErrorByStatus (packages/http.js:182:10)     at Request._callback (packages/http.js:142:24)     at Request.self.callback (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:315:20)     at Request.EventEmitter.emit (domain.js:483:12)     at Request.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:315:20)     at Request.EventEmitter.emit (domain.js:483:12)     at IncomingMessage.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:421:28)     at IncomingMessage.emit (events.js:327:22)     at IncomingMessage.EventEmitter.emit (domain.js:483:12)     at endReadableNT (_stream_readable.js:1220:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21)  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9

**Comment by ali-alhaidary** [comment]
https://almajlis.the5stars.org/bigbluebutton/

**Comment by johncrisp** [comment]
Hi,

You really need to fill out the bug template fully for us to have any chance of helping you.

We need to know how you actually got to your issue - what steps did you take to set this up?

You need to fill in the 'Steps to Reproduce' properly.

I'll leave this open for the minute pending further informatin but think that this is most likely a support issue.

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat

**Comment by ali-alhaidary** [comment]
Thank you, however, other fields in the template are not relevant, the 
issue is very simple, and logs and links are provided.

Ali

**Comment by johncrisp** [comment]
Hi Ali,

Please accept that those steps are relevant. We really wouldn't ask for them otherwise. (note the closebot would have closed this immediately without this information!!)

Lots of people use BBB without issue. So clearly there is an issue with your particular configuration.

Without knowing how you got to this point we can't tell anything.

Please complete these fields:

Deployment Method:
Number of Running Instances:

Is this a new install or upgrade? What steps did you take to set up BBB? Did you follow a guide?

What do you actually do to generate the error?

Please expand on the issue more so we can try and work out what is wrong.

Thanks.

**Comment by ali-alhaidary** [comment]
> Hi Ali,
> 
> Please accept that those steps are relevant. We really wouldn't ask for them otherwise. (note the closebot would have closed this immediately without this information!!)
> 
> Lots of people use BBB without issue. So clearly there is an issue with your particular configuration.
> 
> Without knowing how you got to this point we can't tell anything.
> 
> Please complete these fields:
> 
> Deployment Method:
> Number of Running Instances:
> 
> Is this a new install or upgrade? What steps did you take to set up BBB? Did you follow a guide?
> 
> What do you actually do to generate the error?
> 
> Please expand on the issue more so we can try and work out what is wrong.
> 
> Thanks.
Deployment Method: curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
Number of Running Instances: 1

Is this a new install or upgrade? What steps did you take to set up BBB? Did you follow a guide? New for RecketChat following https://docs.rocket.chat/installation/manual-installation/ubuntu, 
BBB is live production [https://almajlis.the5stars.org] for some time and used with our LMS moodle. the link that I used in the configuration https://almajlis.the5stars.org/bigbluebutton/ and certainly the secret string.

What do you actually do to generate the error? click on 'Start Meeting' button.

**Comment by ali-alhaidary** [comment]
I changed the link to https://almajlis.the5stars.org
But Still having the same error ...

**Comment by ali-alhaidary** [comment]
And followed:
https://docs.rocket.chat/guides/administrator-guides/setting-up-video-conferencing/big-blue-button-bbb-admin-guide

**Comment by ali-alhaidary** [comment]
Issue solved by installing bbb-webhooks, it should be stated in the BigBlueButton (BBB) Admin Guide as it does not install by default in BBB server.
https://docs.rocket.chat/guides/administrator-guides/setting-up-video-conferencing/big-blue-button-bbb-admin-guide

**Comment by ali-alhaidary** [comment]
Issue solved by installing bbb-webhooks, it should be stated in the BigBlueButton (BBB) Admin Guide as it does not install by default in BBB server.
https://docs.rocket.chat/guides/administrator-guides/setting-up-video-conferencing/big-blue-button-bbb-admin-guide
