### ISSUE TITLE
Allow disabling Google Analytics

### ISSUE THREAD

**Issue by nevson** [RocketChat/Rocket.Chat#217]
I know it's very important during early stage of development to get deep insight into how your app gets used so it's understandable that Google Analytics is activated by default. But as I want to run Rocket Chat within my own intranet I want to avoid any user behavior tracking as it might reveal sensitive data.

Would it be possible to add an option to disable GA as page admin or to exclude it during build time?

**Comment by engelgabriel** [comment]
You are right. I am building an ADMIN page, on /settings and that is one of the options we plan to have there. Not just to turn it off, but to add your own if you want.

**Comment by nevson** [comment]
Awesome, looking forward to it :)

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by mhkeller** [comment]
+1

**Comment by AdrianoCahete** [comment]
How about "if undefined = disabled"? I think it's disabled when you don't have anything set, is a little bit strange. Just UX things, you know.

**Comment by engelgabriel** [comment]
Google Analytics is now configured via Admin interface and the ID is stored on the DB

**Comment by Syirrus** [comment]
How do you enable Google Analytics from the Admin interface? Where do you put the code?

**Comment by engelgabriel** [comment]
Administration -> General -> Google Tag Manager Id

**Comment by Syirrus** [comment]
The Google Tag Manager field should accept the following?
GTM-XXXX

Is that correct?

**Comment by engelgabriel** [comment]
Yes

**Comment by Syirrus** [comment]
@engelgabriel Thank you very much. I was able to add it and I have verified that things are working. I notice that my analytics (real-time) don't update unless I refresh the pages with inside Rocket.Chat (I'm using the web version and hitting the refresh button to see real-time page views).

If you have an idea, please let me know and thank you again for helping me.
