### ISSUE TITLE
Require password strength for users

### ISSUE THREAD

**Issue by billy-hardy** [RocketChat/Rocket.Chat#2171]
Is there any way to require a certain level of password complexity for users? If so, exposing the functionality through the UI would be very nice.

**Comment by TwizzyDizzy** [comment]
Comment from @OsamaMahmood in #846:
> The password policy is not set properly and the user can set his/her user name as password

If this issue here is going to be tackled, the above remark should be taken into consideration.

Cheers
Thomas

**Comment by ruKurz** [comment]
https://github.com/assistify/Rocket.Chat/issues/47
