### ISSUE TITLE
Forget User Session on Window Close doesn't work

### ISSUE THREAD

**Issue by billynoah** [RocketChat/Rocket.Chat#21713]
### Description:
Setting "Forget User Session on Window Close" seems to do nothing.  Once a form is filled I cannot seem to make rocketchat forget the session.  I've tried clearing cookies, closing my browser and it still remembers who I am.

### Steps to reproduce:

Set "Forget User Session on Window Close" to "Yes"
Open a chat, fill in the form
Close the browser
Open the browser
Open a chat - the name and email form is no longer visible

### Expected behavior:
Rocket chat should forget my previous session

### Actual behavior:
Rocket chat does not forget my previous session

### Server Setup Information:

    Version of Rocket.Chat Server: 3.13.1
    Operating System: Ubuntu 20.04
    Deployment Method: Snap
    Number of Running Instances: 1
    NodeJS Version: v12.21.0
    MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

## Client Setup Information

    Desktop App or Browser Version: Firefox 78.8.0esr, Chrome Version 90.0.4430.85 (Official Build) (x86_64)
    Operating System: OSX 10.11

**Comment by billynoah** [comment]
Similar to: https://github.com/RocketChat/Rocket.Chat/issues/10328 / possibly a regression of the fix applied in https://github.com/RocketChat/Rocket.Chat/pull/15205

**Comment by billynoah** [comment]
Setting **Accounts_ForgetUserSessionOnWindowClose** is turned on:

![Screen Shot 2021-04-21 at 2 56 11 PM](https://user-images.githubusercontent.com/3309911/115607152-9d305180-a2b2-11eb-8cc9-46ddb29832b7.png)

If I close browser and re-open the chat window still remembers my name and email and my last message:

![Screen Shot 2021-04-21 at 3 03 32 PM](https://user-images.githubusercontent.com/3309911/115607272-c6e97880-a2b2-11eb-800b-5b964bb5d906.png)

**Comment by sumukhah** [comment]
Working on the issue 👍

**Comment by sumukhah** [comment]
Working on the issue 👍

**Comment by johncrisp** [comment]
I can confirm I have seen this on a test 3.13.2 as well

**Comment by renatobecker** [comment]
Hey @billynoah the setting you mentioned is not related to livechat sessions, it's designed for regular users.
In fact, we should support this feature for livechat as well.

Thanks.

**Comment by billynoah** [comment]
Ok that makes sense. Yes I think adding some controls for livechat sessions would be a good idea but as this issue is apparently unrelated I'll close it as not a bug.
