### ISSUE TITLE
NL translations not working.

### ISSUE THREAD

**Issue by Piet2001** [RocketChat/Rocket.Chat#21726]
### Description:

Translations for NL missing in app.

### Steps to reproduce:

1. open app on phone

### Expected behavior:

Dutch text

### Actual behavior:

![Screenshot_20210422-123623_RocketChat.jpg](https://user-images.githubusercontent.com/54183168/115701119-be06ae80-a367-11eb-9213-ef7ffbdff1e5.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- 
### Client Setup Information

- Desktop App or Browser Version: 4.16.1.23831
- Operating System: Android 10

**Comment by johncrisp** [comment]
If this is an app issue can you please close this and re-open n the react Native repo please?

https://github.com/RocketChat/Rocket.Chat.ReactNative

Thanks
