### ISSUE TITLE
Clickable URL in the topic

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2172]
is it possible to make the URL's in the Topic Section? can we somehow  we integrate HTML? 

Another issue i am finding is when I want to integrate Rocket Chat into a website using i-frame, HTTPS doesnt work since main site doesnt have the certificate.. is there a work around it? perhaps enable the site buttons into the topic bar to avoid using iframe?

**Comment by rchikballapur** [comment]
+1

**Comment by engelgabriel** [comment]
Let's accept MD at the topic and channel description.
