### ISSUE TITLE
[UI] delete my account asks username for non oauth users

### ISSUE THREAD

**Issue by siva2204** [RocketChat/Rocket.Chat#21752]
### Description:
**delete my account**  in user profile asks for the username for non-OAuth users but check for password and user is deleted when entering the password.

### Steps to reproduce:

1. my Account -> profile
2. click delete my account
3. check pop up modal

### Expected behavior:
should ask for password for non-oauth users and the text type should be password.

### Actual behavior:

https://user-images.githubusercontent.com/63258524/115778982-0314fa00-a3d5-11eb-86a1-a0a1968663b9.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
-Operating System: Linux
-Deployment Method: tar
-Number of Running Instances: 1
-DB Replicaset Oplog: enabled
-NodeJS Version: 12.18.4 - x64
-MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:88.0.4324.182
- Operating System:Ubuntu 20.04

### Additional context

https://github.com/RocketChat/Rocket.Chat/blob/c12296f46721f5d355da1d80920568cb0c910320/client/views/account/AccountProfilePage.js#L51
this is because the password object is not being sent by the server for non-oauth user.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
