### ISSUE TITLE
See offline users in member list

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#2175]
In various bugs I have seen a lot of discussion around who exactly is shown in the member list for a room, and the fact that showing offline users would break the demo server because it's got too many users in general. Fair enough.

But it's REALLY REALLY annoying on multiple levels to see "Showing 8 of 17 users" in a channel, and have NO WAY to find out who those other 9 users are. Can we please have some button that I can press, in a channel, to see the other users? You don't have to show them all the time, you can even disable the button if the channel is "too large", but can I -- as a user but NOT an admin -- have a way to work around this issue?

I don't know whether admins or channel owners already have a way to override this behavior, but because Rocket channels can't have more than one owner, and often nobody can even figure out who the owner is (especially if the owner has changed because the original owner left), and because hiding offline members is the default behavior, so it's going to be the current behavior in almost all channels -- this is going to be an issue for a long time to come. Can we get some sort of compromise workaround to allow ordinary users to see who's in their channels, even if it takes an extra click to reduce load?

Thanks!

**Comment by soenkef** [comment]
+1 It is an important feature to find ALL group members - unfortunately still missing.

**Comment by voxtobox** [comment]
+1

**Comment by jclabaugh** [comment]
+1

**Comment by maxsdw** [comment]
+1

**Comment by defib** [comment]
+1

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.24&pv=6.0.1&source=email_footer_2] On Wed, Feb 10, 2016 at 11:31 AM, Mauricio Sánchez < notifications@github.com [notifications@github.com] > wrote:
+1

—
Reply to this email directly or view it on GitHub
[https://github.com/RocketChat/Rocket.Chat/issues/2175#issuecomment-182464159] .[https://github.com/notifications/beacon/AAvmVMIyDdG9QAsVWM5eh3kuecOh9S02ks5pi11-gaJpZM4HWv6-.gif]

**Comment by wicked539** [comment]
+1

**Comment by skemb321** [comment]
This also confused me months ago so +1
