### ISSUE TITLE
Email notification to admin for new signups

### ISSUE THREAD

**Issue by stdjld34** [RocketChat/Rocket.Chat#2176]
If this exists I apologize, but I am not able to find it. Could you add the ability to notify admins when a new user signs up. I have selected the admin approval required options, and I have to manually check periodically because I don't get notified when a new account is created.

**Comment by rchikballapur** [comment]
+1

**Comment by mrplow** [comment]
This would be great!

**Comment by marceloschmidt** [comment]
Duplicate of #976.
