### ISSUE TITLE
Notifications in Omnichannel chat causes javascript error and white screen

### ISSUE THREAD

**Issue by billynoah** [RocketChat/Rocket.Chat#21777]
### Description:

Clicking the notifications icon in a queued chat in Omnichannel throws errors and results in white screen.

### Steps to reproduce:

1. Go to a queued chat in Omnichannel
2. Click the notifications icon:

![Screen Shot 2021-04-23 at 12 40 07 PM](https://user-images.githubusercontent.com/3309911/115903390-85330c00-a431-11eb-8a2d-18448c3468c2.png)

### Expected behavior:

Not sure what to expect since it's broken.  I guess maybe a notification preferences panel should appear?

### Actual behavior:

White screen of death.  This doesn't go away until I refresh my browser tab.  I can click around other areas of rocketchat but returning to the queued chat is a blank screen.  Also, there are errors in the console:

```
TypeError: i is undefined
        module /client/views/room/contextualBar/NotificationPreferences/NotificationPreferences.js:1
        ma https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        rf https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        ef https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        Ja https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        ji https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        Hi https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        Ui https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        Ri https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        _c https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        unstable_runWithPriority https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1429
        sc https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        _c https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        dc https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        D https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
        ar https://chat.example.com/13da2367791c877b19ed3b477f50333556da3853.js?meteor_js_resource=true:1411
```

### Server Setup Information:

Version of Rocket.Chat Server: 3.13.1
Operating System: Ubuntu 20.04
Deployment Method: Snap
Number of Running Instances: 1
NodeJS Version: v12.21.0
MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

## Client Setup Information

Desktop App or Browser Version: Firefox 78.8.0esr, Chrome Version 90.0.4430.85 (Official Build) (x86_64)
Operating System: OSX 10.11

**Comment by renatobecker** [comment]
The Notification icon is not available in omnichannel conversations anymore. Please, upgrade your server to the latest version and test it again.
