### ISSUE TITLE
Channel topics are not selectable, and links cannot be used

### ISSUE THREAD

**Issue by calebmeyer** [RocketChat/Rocket.Chat#2177]
Currently, the channel topics in rocket chat are grayed out, and cannot be selected. This means that links (such as in the support channel) are hard to use without going to the developer tools or typing them by hand.

Screenshot: 
![screen shot 2016-02-09 at 4 30 49 pm](https://cloud.githubusercontent.com/assets/3342777/12932819/7df6752e-cf4a-11e5-94ac-174a52bca940.png)

I would like to see the style `*:not(input):not(textarea), *:not(input):not(textarea):before, *:not(input):not(textarea):after` not be applied to channel topics. 

Also, it would be a nice enhancement if links in the channel topic were automatically converted to anchor tags.

**Comment by marceloschmidt** [comment]
Links are currently clickable.

**Comment by calebmeyer** [comment]
+1 Looks like this has been fixed since I opened it. Closing.

**Comment by marceloschmidt** [comment]
As for the links, yes. Are you not interested in text selection, anymore? I could not select the topic's text...
