### ISSUE TITLE
Rocket.chat no longer properly reconnects after outage

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#21783]
### Description:

Generally, after a network interruption or server update, the Rocket.chat will start a counter to attempt to reconnect, or at least provide a link to attempt manual re-connection. This is no longer the case, and while there is a "Connecting" message, nothing seems to be happening, as in my testing it has remained "connecting" indefinitely. One has to press "Ctrl + R" to cause it to refresh.

This causes obvious issues, because clients never come back online, and most people do not know to press Ctrl+R in their RC clients, or even press F5 if not told to do so.

### Steps to reproduce:

1. Upgrade server to at least 3.14-develop (47a61f252) (docker image)
2. Watch the server restart on the back end. (or just bring the server instance down and then back up)
3. Watch the client UI move to "Connecting..." but never reconnect again.

### Expected behavior:

Behaviour should have remained with reconnecting countdown and manual link to reconnect available.

### Actual behavior:

Shows "Connecting..." message, but it never reconnects:
![image](https://user-images.githubusercontent.com/14616851/115956196-0dacbd80-a4c1-11eb-9be6-06b261e8e878.png)

Server shows it is back up and ready for connections:
![image](https://user-images.githubusercontent.com/14616851/115956634-8280f700-a4c3-11eb-8066-c13fa7c5fa96.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14-develop (47a61f252)
- Operating System: Ubuntu (docker)
- Deployment Method:  docker
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: Desktop (3.1.1) / Browser: Firefox 88 64-bit
- Operating System: Windows 10 20H2

**Comment by emikolajczak** [comment]
Confirm. Occurs also on open.rocket.chat

**Comment by bkraul** [comment]
@emikolajczak huh...that's true. Hopefully that will cause this issue to be given priority. 🙂

**Comment by bkraul** [comment]
I just loaded develop 8abc78e2e and it seems the countdown and manual link are back. I believe this was handled by a3656b3 . Hopefully this will not regress.

**Comment by steffen-moser** [comment]
I see this problem again with 

Server Version: 8.0.1
Node-Version: v22.16.0
MongoDB: 8.2.4 / wiredTiger (oplog deactivated)

and Client 4.12.0 on Windows 11, Linux (OpenSUSE Tumbleweed), and macOS 26.2. Is there any possible regression? Has anyone else noticed it again, yet?
