### ISSUE TITLE
A non-admin user can't update user's information if it does not have full permissions

### ISSUE THREAD

**Issue by Jeanstaquet** [RocketChat/Rocket.Chat#21796]
### Description:
if a user is given the rights to modify users in the admin he will not be able to do so. Because each time the email address is hidden, we have to fill it in to validate the form. Moreover, if we cannot modify the email address, the form will never be validated because we will be blocked by the UI.
Moreover the user who modifies the data of another user will see only by validating the form what he can modify or not as information because the UI does not show it as elsewhere in the application.

### Steps to reproduce:

1. Gives one user the ability to modify the data of another user
2. Try to edit another user's info with the given user 
3. Validate the form

### Expected behavior:
The user can't modify data

### Actual behavior:
The user should be able to modify data

https://user-images.githubusercontent.com/45966964/116012436-c3dfe680-a62a-11eb-8130-fb7cad4cdaec.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Linux
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Browser 
- Operating System: Linux

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
