### ISSUE TITLE
Rocket JS possibly leaking event listeners?

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#2179]
I've been running the various profilers from Chrome Dev Tools in the Rocket.chat OS X app, trying to figure out why it seems to bog down on my machine, if left open for a long time (a couple of days).

The smoking gun I _seem_ to have found is on the Timeline tab of Dev Tools. I left it profiling for about an hour, and noticed that there was a monotonic rise in the number of event listeners over that time, from 857 at the start to 982 at the end, or just over two new event listeners registered per minute, over a pretty smooth straight-line progression for the whole hour.

(After I wrote that, the number appeared to drop again... but now in a trace captured a couple hours later, it's up to 1214, so I still think there's something to this.)

Let me know if you'd like my assistance debugging this, especially if it doesn't happen on your systems.

Thanks!

**Comment by glasspear** [comment]
I haven't done any debugging, but we are noticing slug-ish performance on some Mac systems after a couple days (Chrome and Mac App). Always solved by closing the app/tab and loading again, which would support your hypothesis that something is leaking.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
