### ISSUE TITLE
How to delete system message in channel?

### ISSUE THREAD

**Issue by rajatkumarpati** [RocketChat/Rocket.Chat#2180]
there are certain messages like "**user xxx added by yyyy**" in channels while adding a member to the channel by admin. how to remove those messages as it is taking a lot of screen real estate.

**Comment by DonMartin76** [comment]
Related also to #3450.

**Comment by MartinSchoeler** [comment]
For now you can disable them using the admin screen, unfortunately the feature to be able delete this kind of message is not on our roadmap and it will not be done in the near future, if this feature is planned to be added we will reopen this. Thanks.
