### ISSUE TITLE
Option to remove people from a private room is hidden uness you are Rocket Chat Admin

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#21811]
### Description:

We have discovered that people who are owners / leaders in private rooms no longer have the ability to remove users from a private room.  This is in spite of the fact that these people have the required permissions to do so.  We are running RC version 3.12.4 and are using SAML authentication.  The option to remove the user from the room, is completely missing.

### Steps to reproduce:

1. Make a non-admin a private room owner/leader.
2. Verify that these types of users have permission to remove users from the private rooms for which they are an owner/leader, in the Administration section.
3. Have them click on the people icon in a private room, select a user, click on the three vertical dots.  The red text to remove a user is missing.

### Expected behavior:

I would expect that they would be able to remove a user.  I still have this ability, as a RC administrator.

### Actual behavior:
Here is what I see, as an admin:
![image](https://user-images.githubusercontent.com/6833993/116136483-fb38ac80-a697-11eb-8f71-1007fcb2de32.png)

Here is what an owner sees:
![image](https://user-images.githubusercontent.com/6833993/116136565-13103080-a698-11eb-9cee-8abe5c9f9a7d.png)

Finally, here is a screenshot of our Remove user permissions:
![image](https://user-images.githubusercontent.com/6833993/116136776-62eef780-a698-11eb-8977-d29a0a8cbc73.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.12.4
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.21 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: linux/windows/mac

### Additional context

We are using SAML auth.

**Comment by Jeanstaquet** [comment]
Hello @mddvul22, on my side it works normally. However mine is hidden and you have to scroll to see it, wouldn't that be the case with you too? 
![image](https://user-images.githubusercontent.com/45966964/116138820-969c4280-a6d5-11eb-8aa0-b5d3b65a68b8.png)

**Comment by mddvul22** [comment]
Wow.  That is indeed the issue.  Thanks for pointing that out. My apologies for wasting everybody's time.  I will close this ticket.

**Comment by joseluisq** [comment]
It has caused me minutes of headache on `4.1.2` because of this stupid menu with scroll almost invisible.
I hope the team will fix that.
