### ISSUE TITLE
[Feature request] Forced username patterns

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [RocketChat/Rocket.Chat#21843]
It would be nice to have a filed where administrator can put some regex to force newly registered users to use username pattern.

**Comment by KevLehman** [comment]
Hey! Have you taken a look at the `UTF8_Names_Validation` setting? That setting is specifically to have a pattern new users (and current) should follow when typing their username.

(The setting is in General -> UTF8)

**Comment by ChevalierDeBalibari** [comment]
Hi, that should be useful! Thanks!
