### ISSUE TITLE
See full profile from user card not working after navigation to a different type of room

### ISSUE THREAD

**Issue by zaphod534** [RocketChat/Rocket.Chat#21846]
### Description:

If I click on "See full profile" from a user card, the user profile is not showed

### Steps to reproduce:

1. Click on a user in a channel, then "See full profile"
2. Navigate to a direct room do the same thing
3. Then navigate back to the previous channel and do the same thing

### Expected behavior:

User profile is shown

### Actual behavior:

User profile is not showed

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome 90.0.4430.85
- Operating System: MacOS Big Sur 11.2.3

### Additional context

After user profile is not showed, in the page url there is "members-list" instead of "user-info" and viceversa.
After some debug I notice that the room type [here](https://github.com/RocketChat/Rocket.Chat/blob/b226da3849212b3105dfedf36df77a325f0d27d5/client/views/room/providers/ToolboxProvider.tsx#L79) refers to the previously opened room.

Note: this also happens on open.rocket.chat.

**Comment by sumukhah** [comment]
Working on the issue 👍

**Comment by ankar84** [comment]
Confirm that issue. But it's a bit wide I think.
## Steps to reproduce:
1. Click on avatar of any chat user
2. Then click **See full profile** - nothing happens
3. Open thread in same chat
4. Click on avatar of any user in that thread
5. Then click **See full profile** - profile opened.

@sumukhah can you check your fix with that steps to reproduce to get if this also fixed or not.
And in not, please fix it.
Thanks!

**Comment by sumukhah** [comment]
Hey, Yes I believe it would fix that issue @ankar84 
One easy way to reproduce this issue is
1. Visit a channel, click on user avatar, click on see full profile
If you get the user profile then do 2.
2. Now visit a personal chat/ discussion/ thread and click on user avatar, see full profile. Now it won't open..

Vise versa is also possible(step 2 then step 1)..

**Comment by sumukhah** [comment]
For showing team user's profile, i have made a separate PR, #21894

**Comment by serviceman** [comment]
Can this PR please be looked at, this is very urgent for some of us. Thank you.

**Comment by dougfabris** [comment]
@serviceman @zaphod534 This issue was fixed here: #24098
Thanks for your help guys @ankar84 @sumukhah!
