### ISSUE TITLE
Add ability to change font colors

### ISSUE THREAD

**Issue by Eventyret** [RocketChat/Rocket.Chat#2184]
Is it possible to give users the ability to change their font color, (I know you can do bold, etc)
But let them change the colors of the individual message.

**Comment by corecache** [comment]
Would this feature be purely visual for the user to better recongize who wrote what?
or is this feature more of a "Look at my big fat bright red color font because what I say is important?

For the first type, I can imagine a simple visual overlay option which is switcheable for channels so that each user gets a color assigned and everything the user writes is shown in that specific color. These colors may vary for each new session/client.

**Comment by BackIsBachus** [comment]
I would see that as the "big red font" part. For example with bots and integrations: if you have a monitoring service speaking through a web-hook you may like to color its messages (service/server down in red, warning in orange, good in green, etc).
Again for bots it could help differentiate when a bot is speaking among regular users.
Lastly if you have to leave a message as an admin/moderator you may want to switch color to make it stand among the other messages.

**Comment by marceloschmidt** [comment]
I see why some people would like this, but I personally think this gives an idea of those IRC rooms, full of multi-colored texts which in the end were nothing but **very** annoying. But I'll leave the issue open, in case anyone wants to be held responsible for adding that "feature" :D haha. If someone does, **please** make it so an admin can enable/disable this functionality in admin settings.

**Comment by NickBusey** [comment]
I would like to see this ability just for our Chat Bot to be able to put green 'passed' banners and red 'failed' banners with build status and other things.

**Comment by engelgabriel** [comment]
@NickBusey you can set the color or the attachment of the message to make it call attention.

![image](https://cloud.githubusercontent.com/assets/1000217/21597102/efb0d892-d12b-11e6-8f0d-6e79a23c447d.png)


See https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage#attachment-field-objects

**Comment by maethor** [comment]
@engelgabriel I'm looking for the same feature than @NickBusey for my supervision bot.

Attachements are beautiful, but they are not embedding in the desktop notifications, so we can't the at the first glance what the notification is about.

**Comment by mpoullet** [comment]
@NickBusey @maethor We ended up using emojis instead of font colors for our CI notification bot, e. g.
- SUCCESS => ✅ 
- FAILURE => ❌

**Comment by spartygw** [comment]
Emojis is the solution, I guess. Sure wish it were possible to add color just to highlight important parts of a message. I routinely post notifications to a release channel and would like to be able to call out specific parts without having to use emojis
