### ISSUE TITLE
Connection issues on LTE on iOS

### ISSUE THREAD

**Issue by voroyam** [RocketChat/Rocket.Chat#21844]
### Description:

When I go outside my wifi and open the rocket chat app on my iPhone often I see "waiting for network" but it never actually finishes waiting or refreshing. In the past I could use the Clear Cache workaround to get the lastest updates from the server but yesterday I could not. I even tried log out and log in, but it would not let me log in after I logged out.

### Steps to reproduce:

1. Open Rocket Chat app while connected to a server and while being outside your wifi on LTE
2. wait for the "waiting for network" message to disappear

### Expected behavior:

my App get's the updates from the server

### Actual behavior:

message "waiting for network" never goes away.
Clearing cache or log out log in does not help

### Server Setup Information:

- Version of Rocket.Chat Server: v3.13.1

### Client Setup Information

- Desktop App or Browser Version: 4.16.1
- Operating System: iOS

**Comment by johncrisp** [comment]
Can you please close this and open it in the ReactNative repo please?

https://github.com/RocketChat/Rocket.Chat.ReactNative

And please ,make sure you fill out the template complete - it is impossible to debug without all this information.

Thanks.

**Comment by voroyam** [comment]
ah, thanks
