### ISSUE TITLE
Improve documentation about independent security audits

### ISSUE THREAD

**Issue by cyberflaneuse** [RocketChat/Rocket.Chat#21859]
I am an independent researcher and member of a digital rights community where we're researching a number of FOSS and secure team solutions in order to provide a comparison and advice. Someone recommended Rocket.Chat, but we noticed that it is not documenting the availability of independent security audits which is very important for our evaluation, as well as for the general peer-review. I kindly ask you if you could provide documentation about the existing recent security audits. Thank you.

**Comment by johncrisp** [comment]
Hi.

Please reach out directly to the security team, or contact me directly with your details and I will pass them on.

https://docs.rocket.chat/contributors/how-can-i-help/security
