### ISSUE TITLE
Change password doesn't work as expected

### ISSUE THREAD

**Issue by PriyaBihani** [RocketChat/Rocket.Chat#21857]
### Description:

When a user tries to change its password in the preferences section, the password change happens even if the user doesn't confirm his new password which renders the second input for password confirmation useless.

### Steps to reproduce:

1. Go to **My Account**
2. Go to profile
3. Change your password without confirming it. 

### Expected behavior:

Password shouldn't change unless the user confirms it .

### Actual behavior:

Password changes rendering the confirm password input useless.

https://user-images.githubusercontent.com/69837339/116538519-460b2c00-a905-11eb-9c74-ddf7e176f03c.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and it was fixed here: #30306

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
