### ISSUE TITLE
Details of message readings are not displayed.

### ISSUE THREAD

**Issue by sergeln** [RocketChat/Rocket.Chat#21850]
### Description:

Details of message readings are not displayed.

### Steps to reproduce:

1. Click info on a message.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14
- Operating System: ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.1.1
- Operating System: Windows 10

### Additional context

![2021-04-28_19-01-45](https://user-images.githubusercontent.com/6598339/116436395-0ab12480-a855-11eb-9842-84eebfe4f1d6.png)
![2021-04-28_19-02-15](https://user-images.githubusercontent.com/6598339/116436498-21577b80-a855-11eb-9cc2-5d7563532937.png)

**Comment by Jeanstaquet** [comment]
@sergeln thanks for your issue, i'm working on it

**Comment by mikesrus** [comment]
3.14.1 still not work

**Comment by fdellwing** [comment]
I can confirm this for 3.14.2, it worked in 3.13.x.

**Comment by johncrisp** [comment]
Unfortunately a fix missed 3.15 but I believe read receipts will be fixed in 3.16

**Comment by matheusbsilva137** [comment]
Thanks for pointing this issue 🙂 
This has been fixed in 3.16. Can this issue be closed?

**Comment by fdellwing** [comment]
Seems fixed.
