### ISSUE TITLE
Read receipts are broken....again

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#21861]
### Description:

Read receipts are broken....again. Can someone please make a unit/workflow test for read receipts?

### Steps to reproduce:

1. Upgrade from 3.11.0 to 3.14.0
2. Read receipts are broken

### Expected behavior:

Not broken

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/116594360-f7469d80-a8d6-11eb-9802-d0ec86de3fa8.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0 (1255c8f0c)
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.22 / mmapv1

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10

**Comment by wreiske** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/18689
https://github.com/RocketChat/Rocket.Chat/issues/15484
https://github.com/RocketChat/Rocket.Chat/pull/15656
https://github.com/RocketChat/Rocket.Chat/issues/4957

**Comment by Jeanstaquet** [comment]
Hello @wreiske thanks for your isssue, we are working on it.

**Comment by xi67** [comment]
Same here 3.14.0

**Comment by mikesrus** [comment]
3.14.1 still not work

**Comment by ankar84** [comment]
Showing Read Receipts in Web client is definitely broken in 3.14 and not be fixed in 3.15 (planed to fix it in 3.16).
But as a workaround user can still get that Read Receipts in mobile client!

**Comment by pierre-lehnen-rc** [comment]
Closed by #22203

**Comment by paderlol** [comment]
When release version of the 3.16?

**Comment by jmessy919** [comment]
Greetings - running a Ubuntu Snap with 3.14.4; same issue. Is the final say from dev that this issue has been closed out and a fix is now in place, or are you still holding off for 3.16? Thank you so much.

**Comment by ankar84** [comment]
> Greetings - running a Ubuntu Snap with 3.14.4; same issue. Is the final say from dev that this issue has been closed out and a fix is now in place, or are you still holding off for 3.16? Thank you so much.

Yeah, fix will be in upcoming releases
