### ISSUE TITLE
Unable to add members to team

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#21862]
### Steps to reproduce:

1. Install Rocket.Chat 3.14.0 (or just visit open.rocket.chat)
2. Try to create a new team
3. Type in a name
4. Type in another name
5. ????

### Expected behavior:

Type a name, select name.. type another name, select name.

### Actual behavior:

![BQQIC746da](https://user-images.githubusercontent.com/6295044/116596938-de8bb700-a8d9-11eb-960a-7d300a77b715.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat
- Operating System: N/A
- Deployment Method: N/A
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10

**Comment by Jeanstaquet** [comment]
Hello @wreiske, thanks for your issue i'm working on it.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
