### ISSUE TITLE
OTR broken with Release 3.14.0

### ISSUE THREAD

**Issue by tom666-debug** [RocketChat/Rocket.Chat#21873]
**Description:**

At least for me (tried on 2 test instances), it seems that the OTR function is broken with the newest release.

On version 3.13.3 it was still working and now right after the update to 3.14.0, OTR is running into a timeout (see attached screenshot):

![timeout](https://user-images.githubusercontent.com/78903224/116692907-672f5380-a9bd-11eb-856e-f934d2dd6588.JPG)

**Steps to reproduce:**
- Open a direct channel and select OTR from the menu

**Expected behavior:**
The other person in the channel will be asked to accept the OTR chat

**Actual behavior:**
OTR runs into a timeout 

**Server Setup Information:**
Version of Rocket.Chat Server: 3.14.0
Operating System: Debian 10.9
Deployment Method: docker-compose
Number of Running Instances: N/A
DB Replicaset Oplog: YES
NodeJS Version: v12.22.1
MongoDB Version: 4.0.21

**Client Setup Information**
Desktop App or Browser Version: all
Operating System: Windows 10 / Debian 10.5

**Comment by Gummikavalier** [comment]
I can confirm this happens on our RC 3.14.0 too.

**Comment by benedikt-wegmann** [comment]
happens with us as well with 3.14.0, I can already hear users typing support emails. :(

together with the ongoing user presence problems this another poor looking update, and my institution is a paying customer. very disappointing.

**Comment by vplb** [comment]
Confirming for 3.13.3 and then 3.14.0.  (both issues)

**Comment by hans4rc** [comment]
same here

Version of Rocket.Chat Server: 3.14.0
Operating System: CentOS 8
Deployment Method: tar in gz
Number of Running Instances: 1
DB Replicaset Oplog: 1G
NodeJS Version: v12.22.1
MongoDB Version: 4.0.24 / wiredTiger (oplog Enabled)

**Comment by tpat2** [comment]
If you need a work-around:  Having both users go to Help > Reset app data right before OTR seems to get OTR working for that session.

**Comment by tom666-debug** [comment]
![image](https://user-images.githubusercontent.com/78903224/118836048-d238bf80-b8c3-11eb-88d3-115728624362.png)

Not really an acceptable work-around for me, but thanks for having a look and your feedback.

**Comment by hans4rc** [comment]
thanks for your feedback, but unfortunately does not work in a browser

**Comment by tpat2** [comment]
Ok thanks.

**Comment by tom666-debug** [comment]
still broken with latest version (3.14.1)

**Comment by hans4rc** [comment]
**OTR in browser (Google Chrome and FireFox)**
If I activate OTR, a time-out occurs. However, the remote station receives an OTR request **after about 10 minutes** and accepts it.
Now OTR can be used, the green key symbol is displayed.
If the remote station restarts the browser, the OTR connection seems to remain active in my browser. If I now write messages, they are displayed in the browser of the remote station as an empty message without content.

**Comment by hans4rc** [comment]
Update to 3.14.1 = same

**Comment by czqrny** [comment]
Test with 3.15.0-rc.1 still not working

**Comment by Ashiroky** [comment]
Version 3.14.4 - not working. When will be fixed this bug?

**Comment by vplb** [comment]
I retract that, it seemed to work for the first attempt at OTR. 
Any subsequent attempts fail, usually by timing out. 
Occasionally, and i can't figure out what is different, after a few Reloads of the entire app, it'll allow 1 OTR session, then fail again.
