### ISSUE TITLE
add rocket.chat version to statistics page

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#2187]
It would probably be helpful to add `rocket.chat` version to Administration -> Statistics page (or on some other place in the client side).

**Comment by graywolf336** [comment]
This currently added in the development branch. :)

**Comment by engelgabriel** [comment]
It is currently on master, first page on the administration panel

![image](https://cloud.githubusercontent.com/assets/1000217/12967121/00383972-d04b-11e5-9ba3-869a1dc21057.png)
