### ISSUE TITLE
Export Messages not visible for room owners

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#21870]
### Description:

We have several RC instances and the Enterprise versions of them don't show `Export Messages` option for users or owners of the channel. The option is visible only to the admins.

Community editions show this option just below the `Pinned messages` option in the three dot menu.

We recall this still working in RC 3.9.7, but not anymore in 3.12.x.

### Steps to reproduce:

1. Create a new channel to ensure that you are owner in it
2. Click ...-menu top right
3. Look for option called `Export Messages`

### Expected behavior:

![yes-export](https://user-images.githubusercontent.com/6958942/116657889-d72ae300-a997-11eb-8ed6-490cf9f01279.png)

Export Messages option is visible to owner (at least)

### Actual behavior:

![no-export](https://user-images.githubusercontent.com/6958942/116657926-e578ff00-a997-11eb-89d6-ce14ddc89f6b.png)

Export Messages option cannot be found.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.4, 3.14.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.18.4 for RC 3.12.4, 12.22.1 for 3.14.0
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Any browser

### Additional context

I suspect this is a permission issue, but I cannot rule out bugs or differences in the schemas with older and newer versions of Rocket.Chat. The one with instance from all the way from 2017 does not have the issue, while newer ones don't.

Also notable is that Room Info button is in the different position between these instances possibly indicating such differences.

We haven't skipped any versions of RC, all upgrades have always been between consecutive major versions (y in x.y, we've skipped only minor z releases as in x.y.z).

**Comment by Gummikavalier** [comment]
We traced this issue to be in connection with `Mail Messages` permission for roles. Only `Admin` role has it on by default on our new instances.

The instance Export Messages work on has it enabled for the `User` role.

**Comment by Gummikavalier** [comment]
Before closing this issue, could anyone from the developers confirm whether enabling permission for channel owners or users will pose any security implications in the internal logic of RC?

Apart from the obvious ability for users to export messages of channels they belong into, of course... :)

**Comment by Jeanstaquet** [comment]
Hello @Gummikavalier, i'm not part of the RC team but i work a lot with the code, i can tell you that this permission is only to remove the sidebar functionality currently.

**Comment by Gummikavalier** [comment]
@Jeanstaquet Hi! Thanks for the confirmation. I'll close the issue. :+1:
