### ISSUE TITLE
Multiple quotes make chat area inaccessible

### ISSUE THREAD

**Issue by inaferando** [RocketChat/Rocket.Chat#21892]
### Description:

Cannot quote as many messages as I want, because quoted messages overlap the whole chat area.

### Steps to reproduce:

1. Try to write message containing multiple quotes. After N quotes are added to the new message you'll be unable to add N+1 quote because chat area is overlapped with quotes. See the screenshot. On 1st screenshot some chat area is still accessible, one the 2nd is is not accessible at all.

### Expected behavior:

Quotes should use only half (or less) of chat area regardless of their count. Scrolling is expected in quotes area.

### Actual behavior:

See the screenshot.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Ubuntu 20

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Ubuntu 20
![1](https://user-images.githubusercontent.com/1243824/116711826-e5025780-a9db-11eb-8fd8-51703d77713f.png)
![2](https://user-images.githubusercontent.com/1243824/116711830-e6338480-a9db-11eb-847e-ca941a29a03b.png)

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases and it was fixed here: #27604

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
