### ISSUE TITLE
Inconsistent Inline Link Preview when Feeding via Webhook

### ISSUE THREAD

**Issue by ma-karai** [RocketChat/Rocket.Chat#2189]
I feed RSS news into a news channel via webhook, py-feedparser, and py-html2text. Up until 0.16.0 the inline display was by default deactivated for this post method. With the built 0.17.0 some links preview automatically when posted via webhook.

To me it seems that links that end in ".htm" wont display (inline preview), e.g.  [German Article about Gravitational Waves](http://rss.feedsportal.com/c/33374/f/578068/p/1/s/254742c7/sc/3/l/0L0Sgolem0Bde0Cnews0Cgravitationswellen0Eab0Eheute0Ewird0Ealles0Eanders0E160A20E1190A580Erss0Bhtml/story01.htm)

For the sake of feeding RSS via webhook, I personally would prefer a checkbox to allow inline preview on webhooks.

cheers Kai

**Comment by marceloschmidt** [comment]
Does this still happen? I believe we have a property for enabling/disabling link previews.

**Comment by ma-karai** [comment]
well, i have not looked at this. thanks tho :D
