### ISSUE TITLE
The users list doesn't load 25 users by 25

### ISSUE THREAD

**Issue by Jeanstaquet** [RocketChat/Rocket.Chat#21896]
### Description:
In the users list, when scrolling to see all users, it does not load 25 users by 25. But instead it sometimes loads 23 22 or 25 users at each end of the list.

### Steps to reproduce:

1. Go to a room with at least 100 users
2. Scroll to the end of the list

### Expected behavior:
It should load 25 users by 25

### Actual behavior:
It doesn't load 25 more users each time

https://user-images.githubusercontent.com/45966964/116737269-54cf0d00-a9f1-11eb-8dfe-8da2a90dbdd9.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0-develop
- Operating System: Linux
- NodeJS Version: 12.21.0 - x64
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
actually now it loads 10 by 10 depending on the scroll deep that you have done

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
