### ISSUE TITLE
Channel not showing in the Channels list

### ISSUE THREAD

**Issue by Wloa** [RocketChat/Rocket.Chat#219]
Create a new Channels and add members during Add Channel. The new channel did not show in the other member's channels list (Pic 1). Refresh the browser still not showing up. However, the member is listed in the members list (pic2).

![pic 1](https://cloud.githubusercontent.com/assets/12832493/8321623/3cba06a6-19f7-11e5-99f4-7eb0ead479ff.jpg)

![pic 2](https://cloud.githubusercontent.com/assets/12832493/8321627/413b10e4-19f7-11e5-8a68-b497c5d10811.jpg)

**Comment by engelgabriel** [comment]
Did you send a msg on the room after adding him?

**Comment by Wloa** [comment]
No, I did not, In the previous version it automatically show in the Channel list. 

I also just find out that if I create new Channel other user could not see the channel when click "More Channel" and require refreshing the browser.

**Comment by engelgabriel** [comment]
We will fix this.

**Comment by engelgabriel** [comment]
Just to be clear.. can you test one thing or me? If you add the user when you are CREATING the channel.. it will not alert him until you send the first message... but if you create a channel, and add him later... it will alert him. I think this may be confusing, but it was the behaviour form the beginning, i believe.

**Comment by Wloa** [comment]
I think the logic make sense. 

Scenario 1 - When I add users during creation of the Channel, it will not alert them until the first message. 

Scenario 2 - When I add new user after the Channel exist, it will alert the other user. 

But the new release did not alert the other user for Scenario 1 after entering the first message.

**Comment by marceloschmidt** [comment]
I have tested this with current release and it seems to be fixed now. I'm closing this until further notice.
