### ISSUE TITLE
Emojis don't render in quoted messages

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#21900]
### Description:

Emojis don't render in quoted messages

### Steps to reproduce:

1. Type a message with an emoji in it
2. Quote it
3. No emoji

### Expected behavior:

Emojis should show up in quoted messages

### Actual behavior:

![image](https://user-images.githubusercontent.com/6295044/116748495-67772100-a9b4-11eb-8c31-4cc314229d6d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: open.rocket.chat (3.14.0)
- Operating System: N/A
- Deployment Method: N/A
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10

**Comment by Kunalvrm555** [comment]
I think this issue does not exist any longer.
I'd request @dudanogueira to close this issue.
![image](https://user-images.githubusercontent.com/67605729/156008837-94bd36ea-3201-4378-99d2-2e39629f37f5.png)
