### ISSUE TITLE
Notifications - Highlight Words

### ISSUE THREAD

**Issue by Johann-Snapp** [RocketChat/Rocket.Chat#2190]
Hi guys,

On Slack, we've got a feature called "Highlight Words".
Basically, you can set a coma-separed list of words from the settings.

![hightlight-words-settings](https://cloud.githubusercontent.com/assets/16921761/12973393/5bd03828-d0ac-11e5-9cce-e6d62399c49c.png)

And once you've configured it, you're notified each time someone write it.

![highlight-words-notifs](https://cloud.githubusercontent.com/assets/16921761/12973412/7bf98c26-d0ac-11e5-9c26-dcedca64a047.png)

Does this feature exist in Rocket.Chat ? If yes, where are the settings ? If no, is there someone else interested in ?

**Comment by damienmollard** [comment]
+1

**Comment by Johann-Snapp** [comment]
For information, I didn't find it annywhere so I'm working on it.

**Comment by Johann-Snapp** [comment]
Some minor bug fixes need to be done but it's almost done.

**Comment by mychecknix** [comment]
It would be nice if the highlight dose not only match " ruby ". I think it should be standard matching "*ruby*" (e.g.: asdfruby, rubyasdf, asdfrubyasdf -> should be highlighted).
A other was could be to enable regex to handle this, because ruby*,rocket*,*ruby*,... does not work.
