### ISSUE TITLE
Prevent mention form auto adding users to channels

### ISSUE THREAD

**Issue by Johann-Snapp** [RocketChat/Rocket.Chat#2194]
Actually, when you mention someone from a room he/she isn't, it moves the mentionned user to the room.

![magic](https://media.giphy.com/media/VHngktboAlxHW/giphy.gif)

![diego-mentionned-move](https://cloud.githubusercontent.com/assets/16921761/12980280/1086818a-d0dc-11e5-8b7e-d80aa6428455.png)

It seems to be a feature, not a bug:

![mentionned-move-code](https://cloud.githubusercontent.com/assets/16921761/12980295/2268f874-d0dc-11e5-9f79-eed043870038.png)

I think it would be great to have a setting entry that permits to disable that.
It would be perfect that we could whitelist some users so that nobody can move us by that way except whitelisted ones.

**Comment by morozRed** [comment]
Hi, I want to work on it.
Do we need to set permission for the role or a specific user?

**Comment by engelgabriel** [comment]
We should standardize the behavior of how we deal with the mentioned users. Rather than auto-inviting them on public groups and ignoring the mention on private ones, we should alert the sender with an "ephemeral" message that the user mentioned is not in the room, and the message should also have a button to invite that user.

**Comment by sudipt1999** [comment]
@engelgabriel  https://github.com/RocketChat/Rocket.Chat/pull/13962 This pr solves this issue, kindly review it please.

**Comment by Venomen** [comment]
This bug still exists in 3.0.2

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
