### ISSUE TITLE
Users registered via SAML do not automatically join default channels

### ISSUE THREAD

**Issue by synotna** [RocketChat/Rocket.Chat#2195]
Users registered via SAML do not automatically join default channels

**Comment by engelgabriel** [comment]
Need to double check https://github.com/RocketChat/Rocket.Chat/issues/2526 too, as apparently it was not fixed.

**Comment by rodrigok** [comment]
@synotna can you test with the latest version: 0.25.0?

**Comment by synotna** [comment]
Will do at the end of next week!

**Comment by synotna** [comment]
Tested with 0.26.0, still not working, sorry!
