### ISSUE TITLE
Required custom fields can be empty if registration is done using OAuth

### ISSUE THREAD

**Issue by amottier** [RocketChat/Rocket.Chat#21960]
### Description:

A required custom attribute value can be empty if user choose to use OAuth when doing is registration on Rocket.Chat.

### Steps to reproduce:

I defined under `Administration > Accounts > Registration > Custom Fields` the following custom field:
```
{
	"company": {
		"type": "text",
		"required": true,
		"minLength": 2
	}
}
```

As `required` is set to `true` I expect this field to be mandatory when a new user register. I get such behavior if user choose to create a new account using "Register a new account" link (authentication handled by Rocket.Chat):
![image](https://user-images.githubusercontent.com/5032635/117126698-6de21000-ad9b-11eb-8210-8dc2f1fdd79d.png)

But if I'm using OAuth to delegate the authentication for example to Google, user will only be asked to choose a Rocket.Chat username:
![image](https://user-images.githubusercontent.com/5032635/117125303-a680ea00-ad99-11eb-86cb-32e5696ed1a8.png)

When looking at user profile I can see that the required custom field is empty.

### Expected behavior:

I would expect the popup that prompt the user to choose for a username to also ask to provide value for required custom fields.

### Actual behavior:

A user account is created with empty value for required custom field.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Debian Buster 10
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.24 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 78.10.0esr (64 bits)
- Operating System: Debian Buster 10

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

I am not sure how Oauth behaves in this scenario. We need a dev to take a look and advise.

**Comment by nickvidal** [comment]
Hi Antoine,

I got a confirmation that will be solving this for Q3. Thanks for reporting!

Kind regards,
Nick
