### ISSUE TITLE
Transcripts not working in Omnichannel

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#21966]
### Description:

In one of our self-hosted instances of Rocket Chat, we have enabled Omnichannel.  The chatting part is working.  However, when the session ends, and the person requests a transcript, no transcript is sent.  This is on a linux server.  The server has a MTA installed and configured.  There are no messages being sent off the server, and there are none in the mail queue, either.  The logs don't show anything trying to be sent, either.  In an effort to troubleshoot this, we have given every type of user the "Send Omnichannel Conversation Transcript" permission.  Still nothing happens when transcripts are requested.

### Steps to reproduce:

1. Build Linux server, with selfhosted RC.
2. Configure Omnichannel
3. Try and request a transcript after chatting.

### Expected behavior:

I would expect an email to be crafted on the server and for the MTA on the server to at least try and send it.  I would also expect some type of error explaining why that it isn't working.

### Actual behavior:

It says that the transcript was sent, but it wasn't.  (See below.)  Nothing gets generated.
![image](https://user-images.githubusercontent.com/6833993/117178520-be576e80-ad97-11eb-9072-b89661e4b54e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.3
- Operating System: Centos Linux 7
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.21.0
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chromium/Firefox/Chrome
- Operating System: Linux/Windows

**Comment by johncrisp** [comment]
Hi.

First, does email send normally? Do email notifications work?

Can you please test this on 3.14, and preferably dev?

There were a lot of fixes in 3.14 and more coming so it might be fixed already.

Thanks.

**Comment by mddvul22** [comment]
We figure it out.  Another administrator had disabled email notifications, globally.  Thanks for the assist!
