### ISSUE TITLE
Support time-to-self-destruct  ephemeral storage for files and images

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2196]
It is popular, and highly demanded on both mobile and the web world.

Files uploaded, images, voice messages - that will self-destruct after a specified period of time.

Other than longer-term privacy,  it saves storage for the server operator too.

Likely need:
- a system wide default policy (optionally enabled)
- a per-file property

**Comment by bott0r** [comment]
I think it would be a great addition, maybe just incorporate the settings into the channel settings. So you can have long term channels and short term channels where everything that is older than X days will be auto-deleted

**Comment by jspeigner** [comment]
Yes this would be great to configure per channel

**Comment by gcassel** [comment]
Yes, I think this would be a great feature, as long as groups have the option to *not* self-destruct files.   I agree strongly with your suggestion @Sing-Li :

>*a system wide default policy (optionally enabled)
*a per-file property

**Comment by louisemessage** [comment]
Nice idea, and an important feature. To simplify the issue backlog for now, I'm going to close this issue, but we can revisit it in the future.
