### ISSUE TITLE
Webapp navigation breaks after visiting the integrations administration menu

### ISSUE THREAD

**Issue by rexzing** [RocketChat/Rocket.Chat#21972]
### Description:

After visiting the integration page in administration options navigation brakes. Check the video of the error

### Steps to reproduce:

1. Login as an admin
2. Goto administration page
3. Click integrations menu
4. Click close administration button

### Expected behavior:

Integration page should close and user should be able to navigate to the expected page.

### Actual behavior:

https://user-images.githubusercontent.com/25826165/117265832-4447e800-ae72-11eb-9125-260598ef9d4f.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0-develop  
- Operating System: UbuntuDDE 20.04 
- NodeJS Version: 12.22.1 - x64  
- MongoDB Version: 4.2.8  

### Client Setup Information

- Desktop App or Browser Version: Chrome/Firefox/Brave
- Operating System: UbuntuDDE 20.04

**Comment by sumukhah** [comment]
working on the issue 👍

**Comment by rexzing** [comment]
@sumukhah  did you started? I already did some research.

**Comment by sumukhah** [comment]
@rexzing, I have reproduced the issue, But not started working yet. If you want to work on this, pls go ahead and send a PR.

**Comment by rexzing** [comment]
I will raise a PR
