### ISSUE TITLE
Upload Android app to F-Droid

### ISSUE THREAD

**Issue by ywecur** [RocketChat/Rocket.Chat#2200]
F-Droid is the most popular and respected package manager for open source apps.

I strongly suggest we upload the Android app there!

**Comment by sujaysudheenda** [comment]
Yes this seems to be like a good idea!

**Comment by pierreozoux** [comment]
In the mean time, you can download directly from there: https://github.com/RocketChat/Rocket.Chat.Cordova/releases

I guess it is a better idea to open the issue there.

**Comment by amiryal** [comment]
Suggest you follow RocketChat/Rocket.Chat.Cordova#104 for updates on this.

**Comment by herbsmn** [comment]
https://github.com/RocketChat/Rocket.Chat.Cordova/issues/104#issuecomment-248840584
