### ISSUE TITLE
cordova app cannot connect to edited server

### ISSUE THREAD

**Issue by imane12** [RocketChat/Rocket.Chat#2201]
I edit server Rocket Chat and I run meteor, then I try to connect my android application (Rocket.Chat.Cordova) to our server  . it downloads all files but can't connect to server (it show waiting for server connection, trying again ...)

**Comment by rodrigok** [comment]
When you are running with the command `meter` you should pass the `--mobile-server` option to define where your phone will connect via DDP, example:
```
meteor --mobile-server http://192.168.1.10:3000
```

We are working to improve that.
