### ISSUE TITLE
Embed layout breaks on user action

### ISSUE THREAD

**Issue by allurco** [RocketChat/Rocket.Chat#22040]
### Description:

In embeded layout, when a user hovers another user he can see the user's full profile. Clickin on that link breaks the embed layout and the normal layout is shown.

### Steps to reproduce:

1. Open rocket chat using embed layout (in an Iframe)
2. Go to a channel and click on a user's name (username)
3. Click on View Full Profile

### Expected behavior:

It should not break from the embeded layout

### Actual behavior:

The normal layout is activated when you click on "View Full Profle" https://share.getcloudapp.com/ApuY04L9

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.2
- Operating System: Linux / Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 3.6.14 / wiredTiger (oplog Ativado)
- NodeJS Version: 12.21.0
- MongoDB Version: 3.6.14 / wiredTiger (oplog Ativado)

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Mac Os

### Additional context

https://share.getcloudapp.com/ApuY04L9

**Comment by johncrisp** [comment]
Hi.

 can you please test this on 3.14, and preferably dev?
 
There were a lot of fixes in 3.24 and more coming so it might be fixed already.\

Thanks.

**Comment by allurco** [comment]
Hi @johncrisp I will try to update today, and will let you know. Thanks
