### ISSUE TITLE
Display became to small to read

### ISSUE THREAD

**Issue by nollid566** [RocketChat/Rocket.Chat#22045]
Was using website with connection to Rocket Chat and when opened the text displayed was too small to read. Also receive message an update is available. Message comes up You will be notified when update is loaded to install? Nothing happens

**Comment by johncrisp** [comment]
Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

Without this information we can't help you

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat
 
There is a new Electron client v3.2.2 available.

https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by johncrisp** [comment]
Closing for now - if you have further information or specific errors please come back and we can re-open this.

Regarding the update issue please follow:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1932
