### ISSUE TITLE
User info displays blank panel

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#22047]
### Description:

When clicking on user info, the info panel flashes for a short second and then it disappears.

### Steps to reproduce:

1. Install latest develop (a157520f1)
2. Click on User Information in a DM
3. Panel will flash and show a blank section.

### Expected behavior:

Show user information

### Actual behavior:

A short flash, and then the section disappears.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.15.0-develop
- Operating System: Ubuntu 20.04 LTS (docker)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: Desktop: 3.2.2, Browser: Firefox 88.0.1
- Operating System: Windows 10 20H2

### Additional context

![image](https://user-images.githubusercontent.com/14616851/118371255-60820e00-b571-11eb-99a7-8be4e24f82e8.png)

**Comment by johncrisp** [comment]
I think this is a duplicate of this:

https://github.com/RocketChat/Rocket.Chat/issues/22035 

If it is then please close.

**Comment by bkraul** [comment]
No, I don't think it is related. I actually observed that bug also, but I believe it was corrected on one of the subsequent commits on develop. This actually looks like a regression of a bug I reported that was corrected sometime ago: #20667 .

**Comment by bkraul** [comment]
This appears to have been corrected on 3aff951
