### ISSUE TITLE
[Feat] Color nicknames.

### ISSUE THREAD

**Issue by tmartincpp** [RocketChat/Rocket.Chat#22055]
### Description:

In some cases it would be nice to have an option to color nicknames in chat rooms.

### Steps to reproduce:

Some enterprises policies force users to have an unique avatar by team: so all users from a team will have the same.

This make chatting kind of messy when multiple users of the same team are chatting with each other.

Also, it can be confusing when avatars are hidden.

### Expected behavior:

Ability to have a random color for each user (from a list of colors), to help with the reading.

### Actual behavior:

primary-font-color is always used.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.14.4
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App : 3.2.2
- Operating System: Linux

### Additional context

We made a quick&dirty patch for our own purpose, here it is if someone is interested :
[color_nickname.txt](https://github.com/RocketChat/Rocket.Chat/files/6495381/color_nickname.txt)

With this patch a random color (from an hardcoded list) will be picked by the client for each user (if there is more users than colors then the same color can be picked more than once).

Also, if RC's developers like the idea, we could work on a proper patch according to their needs.

**Comment by johncrisp** [comment]
Hi and thanks for this.

Normally we'd ask you to put this in the feature-requests repo.

I'll try and see if I can speak to a dev about this.

**Comment by tmartincpp** [comment]
Hi, I was thinking about a pull request but it would never been accepted in the current state; so I did a bug report to know if there is interest in this feature or not (and to see what could be the needs/requirements).

Thanks.

**Comment by gabriel-henriq** [comment]
I like the idea, i try yesterday to developer this feature but i failed and set only one color for everyone.

**Comment by tmartincpp** [comment]
I'm closing this one, RC already have way too many issues opened.
This one should be recreated in the feature-requests repo if anyone is interested.
