### ISSUE TITLE
Logs are unusable for debugging

### ISSUE THREAD

**Issue by robincafolla** [RocketChat/Rocket.Chat#22053]
### Steps to reproduce:

1. Go to Admin > Settings > Logs
2. Set Log Level to 2
3. Go to Admin > Logs

### Expected behavior:

You can view the logs in a stable fashion.

### Actual behavior:

If there is traffic to the machine the page will never load and your borwser may lock up. On a low traffic instance the logs refresh constantly as the requests to view the logs are themselves logged:

![broken-logs](https://user-images.githubusercontent.com/1263427/118501193-60744080-b720-11eb-8ace-80a8e33cb382.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: v12.18.4
- MongoDB Version: 4.4.6 / unknown (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 88.0.1
- Operating System: Ubuntu 20.04

### Additional context

This issue is occurring on my local machine; with only one user logged in; the admin user viewing the logs. On my production server opening the logs at Log Level 2 causes my browser to lock up.

**Comment by robincafolla** [comment]
I would very strongly recommend allowing the option of using file based logging. For sysadmins trying to get to the bottom of issues the logs are unusable at present.

**Comment by johncrisp** [comment]
Logs should go to your system logs?

So journalctl in your case? (Docker and snap are a little different but still don't need Rocket access to view logs)

Can you please confirm?

**Comment by Karting06** [comment]
Hi, 
On my Debian server, it's logged through syslog. I agree that it isn't the best solution though.

**Comment by robincafolla** [comment]
> Logs should go to your system logs?
> 
> So journalctl in your case? (Docker and snap are a little different but still don't need Rocket access to view logs)
> 
> Can you please confirm?

Ah. I knew the daemon's startup logs went there; I didn't realise everything did. I just checked and you're right; everything does seem to be getting dumped there.

Is there any way to separate them out to their own file?

**Comment by robincafolla** [comment]
Maybe this is something I can do with rsyslog; knowing that that is where the logs are being pushed to.

**Comment by robincafolla** [comment]
To split noisy rocket chat logs out from the rest of syslog you can use rsyslog:

```
# On Ubuntu 20.04; your mileage may vary
# permissions for /var/log/rocketchat can be found
# in /etc/rsyslog (see $FileOwner and $FileGroup)

sudo mkdir /var/log/rocketchat
sudo chown syslog:adm /var/log/rocketchat
```

```
# Add to /etc/rsyslog.conf
if $programname contains 'RocketChat' then /var/log/rocketchat/rocketchat.log
```
then restart rsyslog:

```
sudo service rsyslog restart
```

**Comment by robincafolla** [comment]
I still think it would make sense to make this configurable in the app, but I'm happy to close this out.

**Comment by johncrisp** [comment]
> I still think it would make sense to make this configurable in the app, but I'm happy to close this out.

But that isn't easy as each system has different logging systems. Standard way to do it is for the application to not care - just send it to the system logger and let the admin figure where they want it to go.

Rocket just sends it to whatever system logging is configured on your server. In your case normally systemd/journald, and there is the issue - you have set up to use rsyslog....

You should be able to separate out logs by service - just have a quick google for journalctl. I allows you to filter by service name without the need for separate logs.

Something like this for say mysql - just check your rocketchat service name.

`journalctl -f -u mysql.service`
