### ISSUE TITLE
Ticks mentions broken on right scrollbar ?

### ISSUE THREAD

**Issue by tmartincpp** [RocketChat/Rocket.Chat#22064]
Hello,

### Description:

Ticks mentions in scrollbar does not seems to work with 3.14.0.

### Steps to reproduce:

1. Go to a room
2. Send a few messages with a mention to yourself or anyone else
3. See that the tick mention is not displayed in the right scrollbar

### Expected behavior:

Tick mention should be displayed like in 3.12.4 for example.
![RC_3124_scrollbar_tick](https://user-images.githubusercontent.com/33619793/118645109-cf17d380-b7de-11eb-8bc4-b5c76e939a72.png)

### Actual behavior:

Tick mentions are not displayed in 3.14.0 (I haven't tried 3.13.x versions).
![RC_3140_scrollbar_notick](https://user-images.githubusercontent.com/33619793/118645226-f2428300-b7de-11eb-9c9d-89e56036b7c2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App : 3.1.1
- Operating System: Debian

Does not seems to work with browsers either.

### Additional context

I made quite some searches before posting this bug and havent found any bug report, which is surprising me.

I have been able to reproduce with some dockers clean installation (3.12.4 vs 3.14.0) but let me know if I'm missing something.

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Quite a bit has changed on the front end as we swapped to React.

The ticks are read receipts - has anything changed in your setup?

**Comment by tmartincpp** [comment]
Hi @johncrisp ,

I did my tests with fresh docker installations (starting with a new database).

Also, I'm a bit confused, "read receipts" are disabled by default in my tests (for both 3.12.4 and 3.14.0) : 
![RC_read_receipts](https://user-images.githubusercontent.com/33619793/118765456-6599d280-b87b-11eb-8d7f-98af2016fa32.png)

But still, the tick mention are displayed in 3.12.4 but not 3.14.0.

Enabling read receipts (and details) is only showing the blue check signs with 3.14.0 (but still not the mention signs) : 
![RC_tick_and_check](https://user-images.githubusercontent.com/33619793/118766919-5caa0080-b87d-11eb-9033-47bc1a165908.png)


Maybe I should not have used the "tick" word ? I meant the red "lines" in the right scrollbar, my english might be the issue here.

**Comment by tmartincpp** [comment]
I can reproduce with 3.15.0.

@johncrisp : does this bug can be considered as confirmed ?
If not, can I help to do so ?

**Comment by tmartincpp** [comment]
I can reproduce with 3.16.1. :disappointed:

**Comment by tmartincpp** [comment]
@hugocostadev : no explanation ?

**Comment by hugocostadev** [comment]
Sorry @tmartincpp this feature does not exist anymore, I closed it because of that, I should explained ...

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
