### ISSUE TITLE
sorting channel directory by lastMessage raises error

### ISSUE THREAD

**Issue by makaleta** [RocketChat/Rocket.Chat#22063]
### Description:

sorting a directory by lastMessage raises 400 error

request

'/api/v1/directory?query={%22type%22:%22channels%22,%22text%22:%22%22,%22workspace%22:%22local%22}&sort={%22lastMessage%22:1}&count=25' fails with 400: '{"success":false,"error":"Please verify the parameters"}'

### Steps to reproduce:

1. Go to '/directory/channels'
2. Click on 'Last Message in header'

### Expected behavior:

get channels ordered by last message

### Actual behavior:

get error message 'Please verify the parameters'

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.24 

### Client Setup Information

chrome 90.0

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Can you repeat this in another browser or the electron client?

**Comment by makaleta** [comment]
Hi,
it happens also in firefox 88.0.1.

**Comment by ankar84** [comment]
Electron app 3.2.2 have that issue too
![image](https://user-images.githubusercontent.com/4023037/118760268-308d8000-b87b-11eb-8edc-0c3971098ae8.png)

**Comment by makaleta** [comment]
after update to mongo 4.4.6 / wiredTiger works as expected

**Comment by ankar84** [comment]
> after update to mongo 4.4.6 / wiredTiger works as expected

That issue was fixed in 3.15.0

**Comment by makaleta** [comment]
> That issue was fixed in 3.15.0
thats great. closing
