### ISSUE TITLE
Missing Theme areas

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2206]
Hi ,

I am trying to create a dark theme.
But some of the areas are missing.

Right now it is impossible to create  a dark theme. Any suggestions?
I have attached a picture of it.

![image](https://cloud.githubusercontent.com/assets/17207375/13020311/132af130-d1ab-11e5-9ef4-d60ca2c4b3d0.png)

Btw I love the work you guys do with it..

Best Regards
Mathias

**Comment by valessiobrito** [comment]
It's possible put a 'textarea' with support for insert custom style code in CSS?

**Comment by lvh1** [comment]
You can temporarily (until they add a field for custom css) use the 'Side Navigation Footer', put a <style> tag in it and you can modify whatever you want

**Comment by lunitic** [comment]
@lvh1 to who was your answer,  me or valessiobrito

**Comment by davidh10** [comment]
I would also like to know this, it's really annoying :(

**Comment by lvh1** [comment]
@valessiobrito Both I guess? Since you're basically have the same goal as the lunitic

**Comment by valessiobrito** [comment]
The proposal textarea is duplicate on #1635

**Comment by lunitic** [comment]
This can now be archived by custom.css
