### ISSUE TITLE
Regression of not showing password policy for new registrations?

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#22072]
### Description:

Registration page does not show password policy conditions any longer.

![Capture](https://user-images.githubusercontent.com/1122344/118792388-f5bb3480-b8da-11eb-9b08-a3d64f39cfa3.PNG)

### Steps to reproduce:

1. Send invite
2. Click on link to register account

### Expected behavior:

Page shows password policy requirements/conditions as prior versions of Rocket Chat did.

### Actual behavior:

Error message displayed if conditions not met, but the user is not informed what they are.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.3
- Operating System: Ubuntu 18 LTS
- Deployment Method: Manual TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 12.21.0
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Additional context

None.

### Relevant logs:

Not Applicable

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

As per out guide here, can you please test this on the latest code - currently 3.14

There were quite a few fixes and this might have been one of them.

https://rocket.chat/docs/contributing/reporting-issues

**Comment by nooblag** [comment]
Yes, it's a bug for 3.13.3, hence ticket. Thanks.

Can someone confirm this issue persists in 3.14?

I'm on a production server and waiting for point release before upgrading. Also other Rocket Chat instances I have run from Snap and they're still on 3.13.2 as far as I can see.

Thank you.

**Comment by Thalos12** [comment]
Hi, just wanted to mention that I am probably having the same issue, but in addition the error message does not appear. I am self-hosting (server 5.4.0 from docker compose, client 3.8.14 from .deb) on Ubuntu 22.04.

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
