### ISSUE TITLE
[Improvement UI] Bubble message and not linear

### ISSUE THREAD

**Issue by eltrentin** [RocketChat/Rocket.Chat#22086]
Rocket.Chat has a linear mode to show chat message. Different from the standard of the chat message software (Skype, Telegram , WhatsApp). Would be great to have this kind of message rappresentation. Would be clearer having message LEFT and RIGHT to understand.

Lineare Message example (Rocket Chat)
----
![image](https://user-images.githubusercontent.com/10931327/118936679-0906e800-b94d-11eb-840c-64499c487513.png)

Bubble Message example (Skype)
----
![image](https://user-images.githubusercontent.com/10931327/118936744-19b75e00-b94d-11eb-8131-98f809183545.png)

**Comment by ankar84** [comment]
I agree with that!
Could be very good improvement in UI\UX!

**Comment by johncrisp** [comment]
Hi. This has been discussed before in feature-requests

I am closing it in favour of this - please follow up there

https://github.com/RocketChat/feature-requests/issues/114

Thanks.
