### ISSUE TITLE
[Regression] User status bubble tooltip no longer functions correctly

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#22089]
### Description:

I created the PR here (https://github.com/RocketChat/Rocket.Chat/pull/14892) that added a hoverable user status description to messages. It looks like this functionality is now broken. 😢 

### Steps to reproduce:

1. Set a status
2. Go to a DM or a room
3. Hover over the status bubble next to a person's name

### Expected behavior:

![image](https://user-images.githubusercontent.com/6295044/119024768-4cb31f00-b958-11eb-88f1-d0dd2ddb1130.png)

### Actual behavior:

![ZxyDtXNeut](https://user-images.githubusercontent.com/6295044/119025036-93087e00-b958-11eb-8ff1-7fc8abe09f17.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0-develop
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.1.1
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Was it still working in 3.14?

Any idea what might have changed?

**Comment by wreiske** [comment]
> Was it still working in 3.14?
> 
> Any idea what might have changed?

No. I believe this broke when they moved from blaze to react for the message rendering.

**Comment by wreiske** [comment]
It looks like this feature was completely removed in 3.15.0 :( 👎

**Comment by g-thome** [comment]
the status bubble not showing up for other users should be fixed once #22110 gets merged
