### ISSUE TITLE
Suggestion: omiting teams in favour of tabbed view of channels

### ISSUE THREAD

**Issue by janat08** [RocketChat/Rocket.Chat#2209]
You prolly could opt out of teams by introducing tabs in channels list and if you add comment and reply features where reply almost starts a private conversation while comment follows reddit strucutre you could push updates following those messages in the channels list from other tabs. Or instead of tabs you could add configuration for directory sort of view akin to private groups/conversations. If that helps with solving your problems with teams or even augumenting overall functionality.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
