### ISSUE TITLE
accessing chat server from iphone browser show blue screen only

### ISSUE THREAD

**Issue by eriksays** [RocketChat/Rocket.Chat#2210]
testing rocket.chat on my local network.
I can access the server via my iphone browser, however, it's a blue screen and not responsive.

**Comment by engelgabriel** [comment]
Can you please grab the console logs and reopen the issue with more information?

Please follow the link if you dont know how to get the logs from your mobile:
https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by engelgabriel** [comment]
Or 
https://developer.apple.com/library/safari/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html#//apple_ref/doc/uid/TP40007874-CH2-SW1
