### ISSUE TITLE
calling api endpoint /teams.addMembers does not reflect added users on UI

### ISSUE THREAD

**Issue by ecfghjp** [RocketChat/Rocket.Chat#22104]
### Description:

I tried adding members as suggested in here https://developer.rocket.chat/api/rest-api/methods/teams/add-members, I got a success response but no change on UI.
The api call isn't affecting the frontend, even though it returns a 200. The database is updated accordingly as well, checked.
Retrying the same endpoint is throwing a duplicate key error, no surprises there, but the user can be successfully added further from the UI/frontend without generating any form of error/warning.

### Steps to reproduce:

1. Go To Rocket chat UI
2. Click on Create teams
3. Create a team
4. Call API endpoint to add users to team(/api/v1/teams.addMembers)(https://developer.rocket.chat/api/rest-api/methods/teams/add-members)

### Expected behavior:

Members should get added to the team and get reflected on the Rocket chat UI
### Actual behavior:

Users not getting added to team and reflecting on UI
However invoking api/v1/teams.members api gives list of all members even the ones that have been added using above api.
### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.21.0
- MongoDB Version: v4.0.23

### Client Setup Information

- Desktop App or Browser Version:Desktop
- Operating System: Mac OS

**Comment by m7913d** [comment]
Problem is that the `teams.addMembers` API does not add the member to the main channel/group of the team. Work around is to manually add this new member to the corresponding main channel/group using the `groups.invite` or `channels.invite` API.
