### ISSUE TITLE
File uploads Cors problem

### ISSUE THREAD

**Issue by parsagholipour** [RocketChat/Rocket.Chat#22111]
I have enabled cors for Rest api.
Rest api is working fine but I don't know how to add cors headers for uploaded files as it needs auth headers and I'm requesting with ajax(from another domain) to preview the image.
![Screenshot (613)](https://user-images.githubusercontent.com/57809920/119203388-28665800-baa8-11eb-9e0f-f7a3ce9c6a9a.png)
File url: /file-upload/m5Z5PTTB9QJQPbzMz/Picture2.png
Error: CORS header 'Access-Control-Allow-Origin' missing

**Comment by johncrisp** [comment]
Hi,

Github is reserved for bugs in Rocket.Chat

For community support please visit https://open.rocket.chat #support or https://forums.rocket.chat
