### ISSUE TITLE
odd user screen behavior

### ISSUE THREAD

**Issue by eriksays** [RocketChat/Rocket.Chat#2211]
Admin > Users 
Click on + in right sidebar
Click cancel
get to a screen with "edit", "make admin", "activate", "delete" -- this seems like an issue.

**Comment by eriksays** [comment]
to clarify, "user management" sidebar that comes up when I click on a user shows up when I hit "cancel" on add new user

**Comment by marceloschmidt** [comment]
This has already been fixed.
