### ISSUE TITLE
Have to reconnect Zapier every now and then (Refresh token has expired)

### ISSUE THREAD

**Issue by fthiery** [RocketChat/Rocket.Chat#22119]
### Description:

Hello, we're using Rocketchat with Zapier to post messages from a third party data source (which does not trigger very often); while everything works fine for several days, after some time it fails with 500 error (here is the email Zapier sends when trying to post a message):

![Capture d’écran de 2021-05-24 09-36-10](https://user-images.githubusercontent.com/87642/119313156-82674900-bc73-11eb-994c-eec91e375468.png)

Logs indicate:
```
May 24 09:31:58 chat rocketchat[340]: [OAuth2Server] in getAccessToken (bearerToken: xxxxxxxxxxxxxxxxxx )
May 24 09:32:00 chat rocketchat[340]: [OAuth2Server] POST /oauth/token
May 24 09:32:00 chat rocketchat[340]: [OAuth2Server] in getClient (clientId: zapier , clientSecret: xxxxxxxxxxxxxxxxxxx )
May 24 09:32:00 chat rocketchat[340]: [OAuth2Server] in grantTypeAllowed (clientId: zapier , grantType: refresh_token)
May 24 09:32:00 chat rocketchat[340]: [OAuth2Server] in getRefreshToken (refreshToken: xxxxxxxxxxxxxxxxxxxx)
May 24 09:32:00 chat rocketchat[340]: OAuth2Error: Refresh token has expired
```

1) What should we do to avoid this ?
2) Should the error not be handled (instead of a 500 ?)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.23

### Client Setup Information

Zapier

**Comment by dudanogueira** [comment]
Do you, by any chance, use this user for another integration ou access?

I have experienced something like this when I used the same user for different scripts/integrations. What I suppose that happens is that a newly generated token will expiry the previous one. If the script/integration has some form of fallback, it can handle this, but not all integrations does it.

**Comment by fthiery** [comment]
Actually, yes i do also post some messages from a script, but that's not using an OAuth token (does that count ?)

**Comment by dudanogueira** [comment]
Probably does. Try creating, if possible, one user per script/integration.

**Comment by johncrisp** [comment]
Thanks for the report.

> Version of Rocket.Chat Server: 3.8.1

Please note that your version is quite a long way out of date.

There are updates for your version to 3.8.9 and one of which is a security issue you should really fix urgently.

As per this could you please test on the latest version of Rocket to see if it still occurs:

https://rocket.chat/docs/contributing/reporting-issues

As 3.8.x is really six months or more out of date any issues are not going to get back-ported to your version.

Thanks.

**Comment by fthiery** [comment]
> Probably does. Try creating, if possible, one user per script/integration.

Tried that, will let you know.

 
> > Version of Rocket.Chat Server: 3.8.1
> Please note that your version is quite a long way out of date.

Guilty as charged, because we have custom theming applied, we try not to upgrade too often... I guess we got too lazy, we'll upgrade.

> There are updates for your version to 3.8.9 and one of which is a security issue you should really fix urgently.

Would you mind pointing me to the security github issue ?

**Comment by dudanogueira** [comment]
Hi there! I just had this problem.

Are you using the newest version?

If you are, check if the user has the permission to impersonate users. This might be the case.

I am not sure what this zapier integration does, but I had a similar problem and after looking at the code, I was able to solve it.

I just release a new version (0.1.20) and now we are using the personal access token (https://developer.rocket.chat/api/rest-api/personal-access-tokens) for the user to avoid this kind of problem on our Rocket Connect Stack (https://github.com/dudanogueira/rocket.connect/tree/v0.1.20)

**Comment by fthiery** [comment]
Awesome, thanks, i applied the "bot" role to the user, and now it works again. I'm not sure how i could use the personal access token on zapier ?

**Comment by dudanogueira** [comment]
**If** it supports, it will have a place to fill for auth token and userid instead of username and password.

**Comment by fthiery** [comment]
Actually it's not asking for user/pass, it's using an oauth flow

**Comment by fthiery** [comment]
Just wanted to say that after creating a dedicated user and upgrading (and granting my dedicated user account the "bot" role) it does work around the problem. Thanks !

**Comment by sysfu** [comment]
> Just wanted to say that after creating a dedicated user and upgrading (and granting my dedicated user account the "bot" role) it does work around the problem. Thanks !

Can confirm. Our Zap stopped working immediately after the snap upgrade to 3.15.0. Edited the user account for the bot, removed 'user' role and added 'bot' role, saved, re-ran the failed zaps, and everything processed. Thanks for this tip @fthiery
