### ISSUE TITLE
Rocketchat push gateway not working

### ISSUE THREAD

**Issue by githubdeb** [RocketChat/Rocket.Chat#22112]
Hi guys,

I did not know where to report the issue I'm dealing with. Let me know if there is a different place.

1. I have installed Rocketchat from their official website
2. I have my own push gateway to push notifications to a Gotify client
3. On short the schema is Rocketchat ----> Push Gateway -----> Gotify client
4. Push Gateway -----> Gotify client works well
5. Rocketchat ----> Push Gateway does not work at all.
   Error  "Push ➔ debug Sending notification {   createdAt: ,   createdBy: '<SERVER>',   sent: false,   sending: 0,   from: 'push', "

Any ideas?
Thank you.

**Comment by johncrisp** [comment]
Hi,

Github is reserved for bugs in Rocket.Chat

For community support please visit https://open.rocket.chat #support or https://forums.rocket.chat

You can ask questions there about your using your own gateway.

Thanks
