### ISSUE TITLE
Push notifications for livechat channels

### ISSUE THREAD

**Issue by andrzejwp** [RocketChat/Rocket.Chat#2212]
I'm not receiving push notifications about messages sent in livechat channels, unless I use an @mention. It seems that livechat channels are treated as normal "public" channels, instead of as direct message channels. 

I believe it's  an undesired behavior, and livechat agents should receive push notificaftions whenever a guest writes a chat message.

**Comment by engelgabriel** [comment]
Well spotted, @sampaiodiego will fix that.

**Comment by andrzejwp** [comment]
Hi, any news on this? It's kind of a blocker for the whole livechat feature for us.
