### ISSUE TITLE
admin > users video screen

### ISSUE THREAD

**Issue by eriksays** [RocketChat/Rocket.Chat#2213]
admin > users
click on my username (i'm the admin)
see a camera icon, click it
opens webcam
can't seem to do anything beyond this (cannot take picture, cannot do anythign else)
attempt to close window
window goes away, camera stays on, cannot reopen camera (icon has gone away)
have to close browser to turn off camera

**Comment by MartinSchoeler** [comment]
Hey @eriksays , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
