### ISSUE TITLE
Incomplete Swedish Translation

### ISSUE THREAD

**Issue by bittin** [RocketChat/Rocket.Chat#2214]
Hello, i tried out RocketChat a couple of weeks ago when it was featured in Linux Action Show, and saw there was some stuff incomplete and wrong in the Swedish translation is there someone i can email to get a .po file or whatever you use and help edit it ? when i have some sparetime over

**Comment by engelgabriel** [comment]
Hi, we use https://www.lingohub.com for the translations.

Can you please create an free account and send it to me?

Talk to me at https://demo.rocket.chat/direct/gabriel.engel
