### ISSUE TITLE
[Bug] Sidebar context menu (hamburger) not working from search (magnifying glass)

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22146]
### Description:

Sidebar context menu (hamburger) not working from search (magnifying glass)

### Steps to reproduce:

1. Go to magnifying grass in sidebar
2. Search some chat
3. Try to make in unread or hide it via 3 dots (hamburger menu)
4. Instead of menu selected chat is open

### Expected behavior:

Menu works from search results

### Actual behavior:

![hamburger](https://user-images.githubusercontent.com/4023037/119655100-d91a8180-be31-11eb-9df6-d32c04046086.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 26
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: 3.2.2 and Chrome 90
- Operating System: Windows 10

### Relevant logs:

Nothing in DevTools

**Comment by johncrisp** [comment]
I can confirm that this occurs in open.rocket at the minute 3.15.RC (?)

**Comment by ankar84** [comment]
Still an issue in 3.16.3

**Comment by ankar84** [comment]
Still an issue in 3.18.1

**Comment by ankar84** [comment]
Still an issue in 4.2.0

**Comment by ankar84** [comment]
Still on 4.2.2

**Comment by ivans-netto** [comment]
@ankar84 Hey, thanks for the contribution
