### ISSUE TITLE
RockChat X Jitsi Meet - "Click to Join!" Button

### ISSUE THREAD

**Issue by theoprata** [RocketChat/Rocket.Chat#22156]
### Description:
When creating a new meeting, RocketChat won’t redirect the user to the created meeting. It would just get stuck on that pop window to join that meeting. For the users to join the meeting, they would have to click “Call” again; creating another alert of a new meeting. The expected response, from my understanding that is, should be that RocketChat will open a new pop up window (new tab) for Jitsi Meet.

### Steps to reproduce:
1. Create a new Jitsi Meeting using call button (Public|Private|Team|Direct)
1a. A message alert will come up for the other users to join
2. Click on the "Click to Join!" meeting
2a. A pop window will come up notifying users to join the meeting
3. Click on "Yes" button

### Expected behavior:
The integration is set so that the meeting starts on a new window. By clicking the button, the user is supposed to be redirected on a new window for the meeting. The same issue even if the "Always Open in New Window" is disabled.

### Actual behavior:
After the join user click "Yes" to join the meeting, it wouldn't do anything. The window flickers for a bit, but that's all the response I got.

### Server Setup Information:
- Version of Rocket.Chat Server: 3.14.0
- Operating System: Ubuntu 20.04
- Deployment Method: Docker | Self-Hosted
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App: 3.2.2
- Browser Version: Chrome 90.0.4430.212
- Operating System: Windows 10 | Linux Mint | Fedora 32

### Additional context
The same issue occurs on all platforms I've listed.

**Comment by ankar84** [comment]
> After the join user click "Yes" to join the meeting, it wouldn't do anything. The window flickers for a bit, but that's all the response I got.

I can't confirm that - when user clicks **Click to Join!** button new model windows appears **Video Conference Start video call** with **Cancel Yes** buttons. And after user press **Yes** new Jitsi window opens
![image](https://user-images.githubusercontent.com/4023037/119779262-2699fb80-bed1-11eb-8187-6afd8f095b59.png)

But actually I have a few users with similar symptoms - only for them **Click to Join!** button do nothing,

**Comment by theoprata** [comment]
> I can't confirm that - when user clicks **Click to Join!** button new model windows appears **Video Conference Start video call** with **Cancel Yes** buttons. And after user press **Yes** new Jitsi window opens

Interesting. I'll try creating an isolated instance following the same setup I have. I'll keep you posted on my findings.
 
> But actually I have a few users with similar symptoms - only for them **Click to Join!** button do nothing,

This happened to me as well. I thought it was just me, a fluke. The first attempt does nothing, and the second attempt gives me the pop-up window.

**Comment by theoprata** [comment]
I tried recreating the same server setup that I have, but I was unable to replicate the issue. As to what causes the it, I still don't have a clue. 

However, after updating my Docker image to version 3.15.0, the issue was gone. With that said, I'm marking this issue closed.
