### ISSUE TITLE
Username instead Full Name in search

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#22164]
### Description:

Hi, there is a bug with magnifying glass search. When you search for user who never Direct Messages, username instead Full name is presented. Bug in 3.14.0 and also on open.rocket.chat . Details in thread https://open.rocket.chat/channel/support/thread/mLe5KPwZNNTmtLSMc?jump=kE7Di7QPgXE7ZSWXe

### Steps to reproduce:

1. Use magnifying glass search
2. Search for user for user who never Direct Messages
3. Username instead Full Name is presented

### Expected behavior:

Full Name is presented

### Actual behavior:

Username is presented

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Centos 7
- Deployment Method: docker compose
- Number of Running Instances: 33
- DB Replicaset Oplog: YES
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.14 

### Client Setup Information

- Desktop App or Browser Version: all
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Thanks for reporting this.

Please keep an eye on open.rocket and see if this gets fixed.

**Comment by Aashimalik** [comment]
Hi, @johncrisp 

I would love to fix this bug.

**Comment by Gummikavalier** [comment]
Also reported here
https://github.com/RocketChat/Rocket.Chat/issues/21849

**Comment by debdutdeb** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/22602
