### ISSUE TITLE
How to trigger the ssl certificate renewal ?

### ISSUE THREAD

**Issue by chaddevomg** [RocketChat/Rocket.Chat#22166]
Hi I have a rocketchat standalone server installed as a snap on ubuntu
with caddy + Let's Encrypt certificate
following the docs here: https://docs.rocket.chat/installing-and-updating/snaps/auto-ssl-with-snaps

Unfortunately it was unable to renew the letsencrypt certificate (due to dns problems).

Is there a way to force the certificate renewal ?

Thank you,

**Comment by johncrisp** [comment]
Hi,

github is reserved for bugs in Rocket.Chat

For support please visit:

httrps://forums.rocket.chat 
https://open.rocket.chat/channel/support
https://open.rocket.chat/channel/ubuntu-snap

> Unfortunately it was unable to renew the letsencrypt certificate (due to dns problems).
> Is there a way to force the certificate renewal ?

Not until you fix your DNS as letsencrypt needs to use DNS to find your server.
