### ISSUE TITLE
severity vulnerability

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#22161]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'audit', 'fix' ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose config Skipping project config: /home/the5stars.servant/.npmrc. (matches userconfig)
5 verbose npm-session e689c31ceb1f59e5
6 verbose stack Error: No package.json found: Cannot audit a project without a package.json
6 verbose stack     at /usr/local/lib/node_modules/npm/lib/audit.js:164:19
6 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
6 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:514:35)
6 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
6 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
6 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
6 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
6 verbose stack     at PromiseArray._resolve (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
6 verbose stack     at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
6 verbose stack     at PromiseArray._iterate (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
6 verbose stack     at PromiseArray.init [as _init] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
6 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
6 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
6 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
6 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
6 verbose stack     at PromiseArray._resolve (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
7 verbose cwd /home/the5stars.servant
8 verbose Linux 4.15.0-143-generic
9 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "audit" "fix"
10 verbose node v12.22.1
11 verbose npm  v6.14.12
12 error code EAUDITNOPJSON
13 error audit No package.json found: Cannot audit a project without a package.json
14 verbose exit [ 1, true ]

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

You really need to fill out some more information so we know how you got to this point.

> Steps to reproduce:

This is really important.

Note if you search online there are lots of similar reports. It seems you found this common error:

> 13 error audit No package.json found: Cannot audit a project without a package.json

So I think whatever you are doing missed this:

https://github.com/RocketChat/Rocket.Chat/blob/develop/package.json

If you feel there is a bug then please come back with more details and we can re-open this. If you have discovered a real vulnerability then please follow the instructions here:

https://handbook.rocket.chat/company/security#vulnerability-reports-and-disclosure

For support please visit:

https://forums.rocket.chat
https://open.rocket.chat/channel/support
https://open.rocket.chat/channel/ubuntu-snap

**Comment by ali-alhaidary** [comment]
Thank you very much, however, there was not that much of steps taken, I was updating to a new release using the following script: 
sudo systemctl stop rocketchat
sudo mv /opt/Rocket.Chat /opt/Rocket.Chat.bak
sudo n install 12.22.1
curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server && npm install
sudo mv /tmp/bundle /opt/Rocket.Chat
sudo chown -R rocketchat:rocketchat /opt/Rocket.Chat
sudo systemctl start rocketchat
