### ISSUE TITLE
LDAP - display different name in chat then username used for login

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#2217]
Is it possible to have rocket.chat to show a different Name/Field in the chat then to login name? 

Our sAMAccountName is a char/number combination, which is fine for logging in. However it is not very handy to se that as a username while chatting. It would be good, if one would be able to choose a different field/combination of fields that are shown instead.

For me one thing that work would be, to login with the sAMAccountName and display the user part of the mail-address. Login with mail address does what I'm looking for, but we got some users with multiple user accounts and the same mail address - therefore the mail attribute is not unique.

**Comment by rodrigok** [comment]
@hhenkel at the new version (0.18.0 released today) you can define the field to use as username (this will work for new accounts only).

This solve your problem?

**Comment by hhenkel** [comment]
@rodrigok that might my issue - I tried to get the new version runnning, however I'm not completly sure where I could set that value. Could you walk me through?

I believe I was on 0.16.0 earlier, is there anything necessary to get the new features? I tried to delete and create a new user, but nothing changed.

**Comment by hhenkel** [comment]
Okay, I guess that was my bad. Let me retry the 0.18.0 ....

**Comment by hhenkel** [comment]
@rodrigok that works for us. However what would be kind of nicer would be chaining of attributes. For example if we could use something like  `givenName.sn`

Another issue I'm currently facing is the field where one could map name and email.
The given example {"cn: "name", "mail":"email"} does not work for me.

**Comment by rodrigok** [comment]
@hhenkel great, so, can you open new issues for theses problems? So we can close this issue and keep thinks more clear.

**Comment by hhenkel** [comment]
sure
