### ISSUE TITLE
[Security] Authentication session token leak via file sharing on mobile client

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22194]
### Description:

User can accidently disclosure his **userId** and **session token** when sharing a file in RCRN application.

### Steps to reproduce:

1. Upload some txt file to any chat in
2. Tap on that file in mobile client
3. Choose browser to open that file
4. Choose share option in WebView
5. URL to that file contains with **rc_uid** and **rc_token** that will be compromised

### Expected behavior:

File should be downloaded to client storage and then shared from there without any opportunity to user to share current link to file on RC server

### Actual behavior:

Upload
![image](https://user-images.githubusercontent.com/4023037/120143107-2e66e200-c1e8-11eb-8b6e-7a4b91372e0d.png)
Choose Chrome
![image](https://user-images.githubusercontent.com/4023037/120143233-63733480-c1e8-11eb-965d-2c55716e1e43.png)
TXT file opens in WebView
![image](https://user-images.githubusercontent.com/4023037/120143319-961d2d00-c1e8-11eb-8471-c0c78be9ab8c.png)
But user need to share it somehow and he press share button and send that link to other user

Shared Link will be like this tor TXT file
`https://rocketchat.company.com/file-upload/1ip9oCvbaw62yNzKFqr/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B9%20%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82.txt?rc_uid=<userId>&rc_token=<user token>`
Of like this for docx file, which was downloaded in mobile, but WebView with link still remain open and user can still share that link
`https://rocketchat.company.com/ufs/AmazonS3:Uploads/zuWcvBGz7pDt3kfWgSqc/Doc%20-%20%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%20%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82.docx?rc_uid=<userId>&rc_token=<user token>`

So `rc_uid` is actual RocketChat userId
And `rc_token` is actual and valid session token

We did try to send messages with that data using `curl` with success result.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: CentOS7
- Deployment Method: docker/
- Number of Running Instances: 26
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: 3.2.2 and RCRN 4.17.0
- Operating System: Windows 10 and Android 10

### Additional context

We have MinIO as Amazon S3 compatible file storage with this settings:
![image](https://user-images.githubusercontent.com/4023037/120143916-b39ec680-c1e9-11eb-84b2-380addf94641.png)
![image](https://user-images.githubusercontent.com/4023037/120143953-c1544c00-c1e9-11eb-9df0-2095aeeb257a.png)
![image](https://user-images.githubusercontent.com/4023037/120143983-d204c200-c1e9-11eb-9a81-acd7396a26aa.png)

### Relevant logs:

No

**Comment by johncrisp** [comment]
Thanks for reporting this.

For any security matters please always open an issue at security@rocket.chat

This is an issue in the react client and a fix is in progress.

**Comment by ankar84** [comment]
Fixed in mobile client 4.20 or newer (still and issue in 4.19)

New mobile versions shows this in browser address
`content://chat.rocket.reactnative.provider/files/%D0%A1%D1%82%D0%BE%D0%BF-%D1%81%D0%BB%D0%BE%D0%B2%D0%BE.txt` which is secure.

Thanks @diegolmello
