### ISSUE TITLE
resumeToken is ignored

### ISSUE THREAD

**Issue by afterlogic-support** [RocketChat/Rocket.Chat#22197]
We're integrating RocketChat in our application. We were able to use the Iframe authentication approach, but it's not exactly perfect for our needs, ideally we need authToken transmitted in the URL when opening RocketChat tab/window.

We're getting authToken via REST API, and we've attempted to use resumeToken approach mentioned at:
https://docs.rocket.chat/guides/administrator-guides/misc.-admin-guides/authentication

But that doesn't seem to work, we're only getting a login page. We're able to log in using the same token by entering this in console:

```
localStorage.setItem('Meteor.loginToken', '...');
```

So the token itself looks valid. Are we maybe missing a configuration option to enable the use of resumeToken?

We'd highly appreciate all the help you can provide.

**Comment by johncrisp** [comment]
Hi.

Github is for issues in Rocket.Chat rather than support.

Please ask your support questions in https://open/rocket/chat #support or https://forums.rocket.chat

If you find an actual bug after discussing it there then please complete this template:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Thanks.

**Comment by pythoneer** [comment]
@afterlogic-support did you found an answer to that problem? I have the same problem but i know the link and parameters are correct. I have a production system from a client which i can test against it and there its working. But on my test system rocket chat behaves like you mentioned. I would expect this is a configuration issue? Maybe it does not work without `https` i can't really tell. The documentation is not very verbose in that regard if there are any prerequisite for this to work.

**Comment by pythoneer** [comment]
this should be the issue or at least related https://github.com/RocketChat/Rocket.Chat/issues/22098  so its very possible that my client has an older version of rocket.chat where this regression was not introduced and on my development environment there is a newer version which includes that regression.
