### ISSUE TITLE
[Bug] Teams call possibilities in Web and Mobile versions differs

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22198]
### Description:

Web client don't have a call icon (and I guess call functionality)
![image](https://user-images.githubusercontent.com/4023037/120179008-c11c7680-c212-11eb-81e5-03398c80fda7.png)

Mobile client 4.17 (and older) have both Voice call and Video call buttons
![image](https://user-images.githubusercontent.com/4023037/120179499-5455ac00-c213-11eb-94dc-27886ad7df00.png)

So, mobile users can start Jitsi call in Team, but desktop users (Web client + Electron) can't joint it!

### Steps to reproduce:

1. Create Team
2. Open team on mobile client and start a voice call in Action menu
3. Try to join to that call at computer

### Expected behavior:

That call function in Teams should be consistent both in Web and on Mobile.
So, you need to **enable it in Web** or **disable it in Mobile**

### Actual behavior:

Web client users can't join calls started on mobile.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: CentOS7
- Deployment Method: <docker
- Number of Running Instances: 26
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: Windows 10 and Chrome 90 and RCRN 4.17.0 with full support for Teams
- Operating System: Windows 10 and Android 10

### Additional context

It's easy reproducible at open.rocket.chat

### Relevant logs:

No

**Comment by johncrisp** [comment]
Thanks for reporting this Anton.

I'm sure this will get attention.

**Comment by Cob0ld** [comment]
We have the same Problem and my report got sadly no attention

**Comment by Cob0ld** [comment]
#https://github.com/RocketChat/Rocket.Chat/issues/21855

**Comment by ankar84** [comment]
Fixed in 3.16.3 and RCRN 4.18.0
