### ISSUE TITLE
Cannot "Export messages" by email using "To Users" (using additional emails works).

### ISSUE THREAD

**Issue by tmartincpp** [RocketChat/Rocket.Chat#22199]
### Description:

Exporting messages by email through "To Users" does not work (while using "To additional emails" works).

![RC_export_by_email](https://user-images.githubusercontent.com/33619793/120195024-99cba680-c21e-11eb-95ac-315e46809c4c.png)

### Steps to reproduce:

1. Create a new RC installation using Docker,
2. Verify your email address for your account in the administration page (to prevent any issue),
3. Configure SMTP parameters in administration page and test it ("Send a test email to my user"),
4. Go to your mailbox, verify that you have verified the test email,
5. Go to any room, write a message and try to export it using "Export messages",
6. Select your own user in "To Users" and click "Send",
7. Go to your mailbox, you will not have receive the exported message.

If you want to verify that additional emails works :
8. Get back to RC, try to export the same message using "Export messages",
9. Manually add your account email address in "To additional emails", click "Send",
10. Go to your mailbox, you will have received the exported message.

### Expected behavior:

We should received emails using "To Users".

### Actual behavior:

We don't receive those emails.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App (3.1.1) and any tested browser (Firefox 78.10.0 and Chromium 90.0.4430.212)
- Operating System: Debian

### Additional context

AFAIK, this bug is not new, it appears at least since 3.14.0 (and probably even since 3.12.0 but not 100% sure about it).

I can confirm that RC does not even try to send the email when using "To Users" (no outgoing connection seen using tcpdump).

### Relevant logs:

I don't see any relevant log, despite putting logs to debug : using "To Users" or "To additional emails" is showing the same successful calls (despite emails not being sent using "To Users").

**Comment by johncrisp** [comment]
Thanks for reporting this.

Somone will look at it in due course.

**Comment by tmartincpp** [comment]
Same with 3.16.1.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
