### ISSUE TITLE
button userinfo does not work 

### ISSUE THREAD

**Issue by VickoF** [RocketChat/Rocket.Chat#22205]
### Steps to reproduce:

1. Go to any user
2.  Click on right button about user
3.   user card is my card information

### Expected behavior:

 Normal user card

### Actual behavior: 

![01-06-2021 104633](https://user-images.githubusercontent.com/53853606/120296721-1323d180-c2d1-11eb-8a3b-461b8cbeea44.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System:  Ubuntu 18
- Deployment Method:  tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  yes
- NodeJS Version:  v12.18.4
- MongoDB Version: 3.6.12

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows 10

**Comment by ankar84** [comment]
Can confirm that on open.rocket.chat at moment.

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

I can confirm some inconsistent usage here.

Using Chrome I went to a DM with another user, clicked the user info, and got my own info rather than the other user.

**Comment by ankar84** [comment]
> I went to a DM with another user, clicked the user info, and got my own info rather than the other user

That was because your userId was before another userId in URL

**Comment by johncrisp** [comment]
> > I went to a DM with another user, clicked the user info, and got my own info rather than the other user
> 
> That was because your userId was before another userId in URL

I'd actually clicked my own ID from a channel or something first, then went to a DM and selected the DM user ID, and mine came up.

**Comment by VickoF** [comment]
Yes, this bug does not persist for every user. This shows up in 90% of cases. But this is very inconvenient to work with.
Can you name when it will be profitable in terms of time?

**Comment by johncrisp** [comment]
> @johncrisp This bug does not persist for every user. This shows up in 90% of cases. But this is very inconvenient to work with.

Hi. You don't need to @ anybody thanks. The relevant people will see this.

It is indeed inconvenient.

> Can you tell me, when it will be fixed?

I have no idea at the minute. It will be assessed in due course.

Of course Rocket.Chat is open source so PRs with your fix are welcome!

**Comment by paulopera** [comment]
I can confirm I'm having the same issue both in the macOS Desktop App and using Chrome.
A coworker with the same environment as me is having less problems but still have problems loading the user info of some users.
If I'm not wrong I had the same problem between the version 3.14.X prior to 3.14.4 or older.

**Comment by ankar84** [comment]
While a [fix](https://github.com/RocketChat/Rocket.Chat/pull/22219) for that issue in WIP I found a workaround:
1. Click on other user avatar on username
2. Click **Show full profile**
3. Proper user information panel is open
Sometimes nothing opens (I thins it's another issue) - **CTRL+R** fix that

**Comment by serviceman** [comment]
Does anyone know when this will be put in an official release, this is a very important issue for some of us that is stopping us from upgrading to the latest version. thank you in advance.

**Comment by johncrisp** [comment]
> Does anyone know when this will be put in an official release, this is a very important issue for some of us that is stopping us from upgrading to the latest version. thank you in advance.

As normal, unless it is a security fix or extremely important we don't normally do point releases.

So expect this to land in 3.16.0

**Comment by ankar84** [comment]
Fixed in 3.16.0 https://github.com/RocketChat/Rocket.Chat/releases/tag/3.16.0

**Comment by paulopera** [comment]
It's fixed as @ankar84 mentioned.
