### ISSUE TITLE
Omnichannel issue, new live chat not appearing on department queue on UI

### ISSUE THREAD

**Issue by jarismar** [RocketChat/Rocket.Chat#22202]
### Description:

We noticed that sometimes new live chat rooms won't be added to agent queue list. We noticed this after some clients complaining that no agent enter the room.

This also seems related to routing mode being set to Manual.

We noticed these errors on browser console from agent browser (Chrome):

![rocket_live_chat_agent_ui_error](https://user-images.githubusercontent.com/1980614/119144881-7edb8400-ba1f-11eb-8c62-ace07f740172.jpeg)

### Steps to reproduce:

1. on omnichannel settings, ensure routing mode is set to manual.
2. ensure agent is online and available to attend new live chats.
3. start a new live chat, notice it does not appear on UI
4. sometimes it won't happen on first attempt

1. 
2. 
3. 

### Expected behavior:

New live chat should be seen under department queue on UI

### Actual behavior:

Sometimes the live chat is not present on department queue, agent have to reload the page.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.1 
- Operating System:  Linux
- Deployment Method: Docker 
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 - x64  
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 90.0.4430.212 (Official Build) (x86_64)
- Operating System: Mac OS

**Comment by renatobecker** [comment]
Hey @jarismar I just can't reproduce the issue you mentioned, can you record a video or a gift where we can see the issue taking place?

Regarding the errors on the browser console, they should not be related to the problem you just reported.

**Comment by jarismar** [comment]
I'm working on a mobile app and we are embedding rocket chat client on a webview.

I found the issue is our app cleaning up localStorage, we handle localStorage as a temporary cache, and it is removed after some period of inactivity, this is affecting rocket chat live client and causing the issues.

I would suggest if possible, in the future, to add some settings to allow the client app capturing the content that is currently send to localStorage getItem / setItem, so the client can customize the persistence in scenarios where localStorage is not available. Anyway, closing the case, as this is pertinent to my scenario only.

Thank you very much for your time.

**Comment by jarismar** [comment]
Closed: root cause, localStorage being removed by my mobile app.
