### ISSUE TITLE
502 Bad Gateway when trying to access via HTTPS

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat#2220]
On a fresh installation, via the Ansible option, we get a 502 Bad Gateway error from nginx. The Ansible script reports that all steps were successful:

```
ok=34   changed=0    unreachable=0    failed=0  
```
How can we make sure the Rocket.Chat instance is running for the nginx proxy?

**Comment by engelgabriel** [comment]
Please open this issue on the https://github.com/RocketChat/Rocket.Chat.Ansible project, please.
