### ISSUE TITLE
Single Inquiry Taken By Multiple Agents

### ISSUE THREAD

**Issue by vineetiotina** [RocketChat/Rocket.Chat#22206]
### Description:
I have facing an issue very frequently that if I have setting up the manual selection for the inquiry and multiple agents are logged-in in the application then if any new inquiry coming into the queue and both the Agents accepted it at the same time then both the agents are able to chat with the customer parallelly.
Is there any fix for that? 

### Steps to reproduce:

Normal chat between customer and agents.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.0
- Operating System: linux
- Deployment Method: Development
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.6

### Client Setup Information

- Desktop App or Browser Version: Chrome 89.0.4389.114
- Operating System: Linux

**Comment by johncrisp** [comment]
Please follow the bug reporting guides in the template

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

Your version is extremely old. Please test on 3.15 which is just being released.

Closing this for now - if this occurs on the latest please come back and we can re-open this.

For general support please ask in https://open.rocket.chat #support or #omnichannel or https://forums.rocket.chat

Thanks
