### ISSUE TITLE
LDAP Custom Domain Search gives "TypeError"

### ISSUE THREAD

**Issue by savikko** [RocketChat/Rocket.Chat#2221]
When I insert
`{"filter": "(uid=#{username})", "scope": "sub"}`
to LDAP Custom Domain search, Test Connection -button gives Error: TypeError.

Seems that even default (example) JSON gives TypeError.

Do I have some configuration problem?

**Comment by rodrigok** [comment]
@savikko is fixed in our branch **develop**, you can pass `userDN` and `password` as empty strings if you don't want to use the develop version:

```
{"filter": "(uid=#{username})", "scope": "sub", "userDN": "", "password": ""}
```
