### ISSUE TITLE
prevent new users from registering or logging in

### ISSUE THREAD

**Issue by KheireddineAzzez** [RocketChat/Rocket.Chat#22213]
![image](https://user-images.githubusercontent.com/59838139/120429518-6a777f80-c36d-11eb-998c-368c59ae067e.png)

**Comment by johncrisp** [comment]
Hi,

I'm afraid we can't help you unless you fill out this template.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Please bear in mind github is reserved for bugs. I can't see any errors here - it looks like a support issue.

https://rocket.chat/docs/contributing/reporting-issues

Ask your well documented questions in https://open.rocket.chat #support or https://forums.rocket.chat

If you can produce any errors please post back here and we can re-open this.

Thanks.
