### ISSUE TITLE
custom navigation

### ISSUE THREAD

**Issue by Merrick17** [RocketChat/Rocket.Chat#22231]
I would like to redirect in the login to a custom route depending on the user role , but i'm not understanding how i can achieve that , any example please ?

**Comment by johncrisp** [comment]
Hi.

Please note github is reserved for bugs in Rocket.Chat

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

Please ask you questions in https://open.rocket.chat #support or https://forums.rocket.chat and we can try and help you there.

Thanks.
