### ISSUE TITLE
[Bug] Direct Message chat not creating from Create new button

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22240]
### Description:

Direct Message chat not creating from Create new button

### Steps to reproduce:

1. Click **Create new** button
2. Click DM
3. Select user
4. Click **Create**\
5. Nothing happens

### Expected behavior:

DM with selected user created

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/120781042-58ded500-c531-11eb-9070-0964681bcc02.png)
![image](https://user-images.githubusercontent.com/4023037/120781173-79a72a80-c531-11eb-976b-e7e07404e8bf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.2.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

### Additional context

Creating DM from Directory search works fine

**Comment by johncrisp** [comment]
Thanks for reporting this Anton.

I can confirm this happens with a browser on https://open.rocket.chat

**Comment by ankar84** [comment]
Could be fixed by https://github.com/RocketChat/Rocket.Chat/pull/22209
