### ISSUE TITLE
Keyboard covers text input

### ISSUE THREAD

**Issue by frankechat** [RocketChat/Rocket.Chat#22252]
### Description:

Keyboard covers the input field and users can't see what they wrote.

### Steps to reproduce:
Open Chat
Click on input field
Keyboard opens and covers the input field

### Expected behavior:

input field to move up like on android/firefox
Right behavior:
![grafik](https://user-images.githubusercontent.com/85393569/120888823-c0ad2280-c5fa-11eb-9566-a822dcdfe5b1.png)

### Actual behavior:

Keyboard covers input field.
![grafik](https://user-images.githubusercontent.com/85393569/120888963-4f21a400-c5fb-11eb-836e-98925638c559.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: ubuntu 18.04.5. LTS
- Deployment Method: Tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  oplog activated
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.24 / mmapv1

### Client Setup Information

- Desktop App or Browser Version: Browser Safari
- Operating System: IOS

**Comment by ankar84** [comment]
Could be fixed it https://github.com/RocketChat/Rocket.Chat/pull/22212
