### ISSUE TITLE
Sidebar icon (hamburger) missing for direct messages view in mobile web

### ISSUE THREAD

**Issue by Cleod9** [RocketChat/Rocket.Chat#22266]
### Description:

In the mobile web browser version of the app direct messages do not have the sidebar icon in the top left next to the user icon in v3.15.0 while normal channels are fine. Workaround is to navigate to the previous page with the browser back button to return to a channel in order to regain access to the sidebar.

### Steps to reproduce:

1. Open a channel in any mobile web browser
2. Observe the side bar icon (hamburger) in the top left
3. Open a direct message
4. Observe no sidebar icon in the top left

### Expected behavior:

Sidebar icon should be visible in all conversation types.

![image](https://user-images.githubusercontent.com/3649914/121039073-c764a280-c77e-11eb-9f2b-99b34f6a92ca.png)

### Actual behavior:

No hamburger icon in direct messages:

![image](https://user-images.githubusercontent.com/3649914/121039119-d0ee0a80-c77e-11eb-9f78-0a89dee2ae2c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Debian 10
- Deployment Method: Docker
- Number of Running Instances: 8
- DB Replicaset Oplog:  Enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Android Chrome or any browser with mobile user agent active
- Operating System: Windows 10

### Additional context

n/a

### Relevant logs:

n/a

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

The devs will take a look in due course.

**Comment by tpat2** [comment]
I think this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22211

I have found a workaround: when I swipe right, the left sidebar shows.

**Comment by Cleod9** [comment]
> 
> 
> I think this is a duplicate of #22211
> 
> I have found a workaround: when I swipe right, the left sidebar shows.

Good catch, when i was searching the issues list my keywords didn't return any relevant results. After backtracking this seems to be the actual duplicate issue here:
https://github.com/RocketChat/Rocket.Chat/issues/22087

(https://github.com/RocketChat/Rocket.Chat/pull/22211 is the associated pull request to fix it)
