### ISSUE TITLE
Sorting directory by last message not possible

### ISSUE THREAD

**Issue by pascal1337** [RocketChat/Rocket.Chat#22285]
### Description:

When using the directory it is not possible any more to sort the results by last messages, error message "please verify the parameters" shows up

### Steps to reproduce:

1. go to directory
2. click on last message sorting

### Expected behavior:

results should be sorted by last message

### Actual behavior:

error message "please verify the parameters" shows up

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.5
- Operating System: ubuntu 20

### Client Setup Information

all clients

**Comment by ankar84** [comment]
> When using the directory it is not possible any more to sort the results by last messages, error message "please verify the parameters" shows up

Fixed in 3.15.0

**Comment by johncrisp** [comment]
Thanks for your report.

Kindly follow the bug reporting guidelines and always test on the latest version as things are moving very fast.

And have a good search here too - often bugs have already been logged.

Closed as per Antons comment.
