### ISSUE TITLE
Exporting Channel Data Fails

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#22283]
### Description:

I am trying to export the contents of an entire channel, from 2017 to today (8th June 2021). The channel includes data from Slack import from 2017. We started using Rocket Chat in 2020.

With the export process, Rocket Chat provides a ZIP file as HTML file and assets folder, but the HTML file does not include messages after 2020. The contents of the message it seems to fail on includes a HTML tag in markdown format like so:

> in the `<iframe>`

### Steps to reproduce:

1. With channel that has Slack imported data, export channel for entire date range
2. Click on email that links to ZIP file for HTML export

### Expected behavior:

Export contains all data and messages on requested date range.

### Actual behavior:

Not all data is exported, seems to fail at message that contains HTML tag in markdown.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.1
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Relevant logs:

No errors in logs to provide.

**Comment by johncrisp** [comment]
Hi and thanks for reporting.

Please make sure you upgrade to at least 3.14.4 - see the release notes.

Can you also please test this on the latest version. Bugs are getting fixed all the time so this one may have already been done.

Thanks.

**Comment by nooblag** [comment]
Hmmm yes saw that, but there's nothing in the release notes about bug fixes to export. 

Regardless, I just upgraded and confirm problem persists in 3.14.5.

**Comment by nooblag** [comment]
Hi there, just a friendly ping on this one, as not being able to export our data is really holding us up.

**Comment by nooblag** [comment]
Still broken in 3.15.1.

**Comment by nooblag** [comment]
Still broken in 3.16.1.

Any action on this from your end in terms of developers taking this on to fix? We'd really like to get our data please!

**Comment by nooblag** [comment]
Gave up and moved to another platform, complete with data loss.
