### ISSUE TITLE
Frequent disconnects on 3.15.0

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#22292]
### Description:
Frequent disconnects happening every few seconds with 3.15.0 Disconnect messages are so quick that the warning is more of a flash than anything. Online status of user also is updated and goes 'offline" for a quick second. This also coincides with XHR errors giving a 502 proxy error response.  Websockets are working correctly so XHR shouldn't even be used, proxy is setup correctly. Upgraded from 3.4.2. I have many other deployments on 3.4.2, including this one, and have experienced no issues.

### Steps to reproduce:

1. Install Rocket Chat version 3.15.0
2. Log in to Rocket Chat
3. Wait a few minutes and you will see frequent disconnect messages appearing.

### Expected behavior:

User to not be disconnected.

### Actual behavior:

User is disconnected for a brief second and reconnected. This happens over and over again, every few seconds.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- - Operating System: Centos
- Deployment Method: tar/manual install
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: Chrome 91.0.4472.77, also happening on latest Edge version.
- Operating System: Windows 10.

**Comment by ankar84** [comment]
Interesting!
So you have [RocketChat Metrics](https://github.com/RocketChat/Rocket.Chat.Metrics) deployed to show some graphs like websockets and other?

**Comment by serviceman** [comment]
I do not have RocketChat Metrics installed as I was not aware that it even existed. I'll install it and post some graphs. I have mutliple rocketchats on the server that run from different databases, will this monitor all of them, or should I only monitor the one I am currently seeing issues with?

**Comment by ankar84** [comment]
> should I only monitor the one I am currently seeing issues with?

This.

**Comment by serviceman** [comment]
I am going to leave this open for a bit, but I think I discovered the issue. The issue that I believe that is happening is if apache timeout is too short, it does not give the server where the proxy is hosted enough time to communicate with the host server of rocket chat & mongodb. I have them hosted on different sides of the US for security reasons so latency could be too much for the pings at times. If there are not other issues I will come back and close this. I will also install the Rocket Chat metrics as well for future bug reports.

**Comment by ankar84** [comment]
> f apache timeout is too short, it does not give the server where the proxy is hosted enough time to communicate with the host server of rocket chat & mongodb.

Yeah, you could be right! Timeouts for websocket connections should be larger then for regular HTTP connections. 
[Here is HAProxy example](https://lucjan.medium.com/investigating-websocket-haproxy-reconnecting-and-timeouts-6d19cc0002a1), but still illustrative

**Comment by serviceman** [comment]
I have resolved this issue. But this will be useful for others that have the same issue. Closing ticket.
