### ISSUE TITLE
[ddp] sending without open connection

### ISSUE THREAD

**Issue by karlos-silva2** [RocketChat/Rocket.Chat#22299]
### Description:

Não estou conseguindo utilizar o livechat no meu ambiente local. Acessando normal o Rockert:

![image](https://user-images.githubusercontent.com/85645175/121417314-23c2f000-c940-11eb-91eb-933d8c346684.png)

mais o livechat dá o erro abaixo 

Erro:
![image](https://user-images.githubusercontent.com/85645175/121416806-997a8c00-c93f-11eb-8f80-595aca724196.png)

### Server Setup Information:

![image](https://user-images.githubusercontent.com/85645175/121416894-b616c400-c93f-11eb-9459-21a3a2901f01.png)

### Client Setup Information

- Desktop App or Browser Version: Google Chrome
- Operating System: Windows

**Comment by johncrisp** [comment]
Hi.

You need to install the livechat widget on another website. The widget then connects to the Rocket.Chat server.

https://docs.rocket.chat/guides/omnichannel-guides/omnichannel-manger-guides/livechat-widget-installation

https://docs.rocket.chat/guides/omnichannel-guides/omnichannel-admins-guide

I don't think there is a bug here.

**Comment by karlos-silva2** [comment]
Boa tarde

Nessa versão do Rocket.chat 3.15.0, ainda continuo com o mesmo problema.

**Comment by ricardojohnny** [comment]
Isso deve ser algo relacionado a instanciar o RocketChat em mais tasks em Docker.

**Comment by karlos-silva2** [comment]
![image](https://user-images.githubusercontent.com/85645175/122290898-99900400-ceca-11eb-9e49-7eb7e369114e.png)

Tenho apenas um com Mongo e Rockect

**Comment by karlos-silva2** [comment]
![image](https://user-images.githubusercontent.com/85645175/122291080-cc39fc80-ceca-11eb-8a20-c29d1cf945b7.png)

Posso digitar qualquer coisa, que a mensagem é sempre está.

**Comment by karlos-silva2** [comment]
Não obtive solução.
