### ISSUE TITLE
User karthick-i2i is having some problems to access the demo site

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#223]
As he reported:
![print](https://cloud.githubusercontent.com/assets/3647767/8332784/50b87726-1aad-11e5-8bcf-757806416033.png)

**Comment by sampaiodiego** [comment]
@karthick-i2i seems meteor is trying to use XHR instead of websockets. are you behind a proxy? are your connection stable?

**Comment by karthick-i2i** [comment]
I am sure nothing is blocked here and i believe there is no problem with
internet connection

On Thu, Jun 25, 2015 at 12:03 AM, Diego Sampaio <notifications@github.com>
wrote:

> @karthick-i2i <https://github.com/karthick-i2i> seems meteor is trying to
> use XHR instead of websockets. are you behind a proxy? are your connection
> stable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/223#issuecomment-114974373>
> .
>



-- 
Regards
Karthick

**Comment by sampaiodiego** [comment]
when asked you by firewall, I don't mean there is something blocked. I asked this because websockets (used by Meteor) has some problems when using behind a firewall.. So this is a known problem with the technology.

I have to double check all the possibilities to realize how to fix this. Your help would be very helpful.

**Comment by sampaiodiego** [comment]
@karthick-i2i can you test now with https? https://rocket.chat

**Comment by karthick-i2i** [comment]
Its work fine now :)

On Tue, Jun 30, 2015 at 2:03 AM, Diego Sampaio <notifications@github.com>
wrote:

> @karthick-i2i <https://github.com/karthick-i2i> can you test now with
> https? https://rocket.chat
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/223#issuecomment-116835516>
> .
>



-- 
Regards
Karthick

**Comment by sampaiodiego** [comment]
:D good to hear it and thanks for your report.

**Comment by karthick-i2i** [comment]
welcome :)
