### ISSUE TITLE
[Bug] Chat avatar not updated immediately in client after it was set

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22307]
### Description:

I have admin role at RocketChat server and I can't set avatar to any channel. Owners can't do it too.
It looks like avatar is setup, but in fact it's not.

### Steps to reproduce:

1. Go to channels settings with **Edit** button
2. Click **Upload** button
3. Select correct picture (jpg, png)
4. Click **Save**
5. Get **Room updated successfully** balloon
6. Refresh channel
7. See no avatar

### Expected behavior:

Channel owners should be able to set avatars to their channels

### Actual behavior:

![avatar](https://user-images.githubusercontent.com/4023037/121509290-2c263400-c9ef-11eb-9c41-3df195a01385.gif)
You get this info, but it's not true
![image](https://user-images.githubusercontent.com/4023037/121508761-a2766680-c9ee-11eb-9227-14a7d8617b31.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2  and Chrome 91
- Operating System: Windows 10

### Relevant logs:

I don't see any errors in server logs or devtools when setting channels avatar

**Comment by johncrisp** [comment]
Hi Anton.

I know there have been a few different avatar issues, but are they related at all?

https://github.com/RocketChat/Rocket.Chat/issues?q=is%3Aissue+is%3Aopen+avatar

**Comment by ankar84** [comment]
> https://github.com/RocketChat/Rocket.Chat/issues?q=is%3Aissue+is%3Aopen+avatar

No, I don't see issues that related or looks like my issue.
I guess my issue was introduced in 3.15.0, because Emil test that on 3.14.0 and avatar appeared to be updated after clear cache in browser. I did try to clear cache - no luck, and on mobile client I don't see avatar to channel, that I did try to change avatar.

**Comment by ankar84** [comment]
And looks like issue is more complicated and maybe related to https://github.com/RocketChat/Rocket.Chat/issues/22218
I set to my admin user a bot role and I might to set avatar to one chat (but only on mobile client).
But other channel still without avatar - I did try to set avatar in Web app and mobile - both failed.
![image](https://user-images.githubusercontent.com/4023037/121666105-943d4e80-cab1-11eb-9f23-8c932be5dcb8.png)
![image](https://user-images.githubusercontent.com/4023037/121666185-a4edc480-cab1-11eb-9f05-e91b166cb0c6.png)
![image](https://user-images.githubusercontent.com/4023037/121666230-ae772c80-cab1-11eb-9958-43f0d00c0f9b.png)

**Comment by gabriel-henriq** [comment]
Same issue here.

**Comment by ankar84** [comment]
Today because of #22357 I was forced to set new avatar to chat and I did it!
![image](https://user-images.githubusercontent.com/4023037/122024361-06bf6e80-cdd1-11eb-9dd5-b9b454fa126d.png)
In 8 attempts.
Successful attempt was made from mobile client with these steps:
1. Delete current avatar
2. Click save
3. Choose new avatar (check if it not disappear, if needed choose again)
4. Click save
5. Check if new avatar remain in channel settings
So, maybe root cause of issue in changing current avatar?

**Comment by velamvela** [comment]
having same problem with 3.15

**Comment by ankar84** [comment]
It works better in 3.16.0 but still not perfect in web client and desktop client
![image](https://user-images.githubusercontent.com/4023037/123750610-777d8500-d8bf-11eb-9dfe-e4f27dca7a9a.png)
I did set avatar - and if I choose edit room settings I can see it's set.
But in a sidebar and in room header and in room info still old icon

**Comment by ankar84** [comment]
It looks like client cache related problem on 3.16.3 now.
I successfully set avatar for chat on RC Electron app, but it now shows there if I check chat settings. 
But it updated at my mobile app.
And vice versa - I did try to set avatar on mobile and get system message that all done successful but in mobile app was old avatar.

**Comment by Natilorens** [comment]
I'm contributing to the RC in a college course, and I would like to contribute to this issue.

**Comment by ankar84** [comment]
Still an issue in 3.18.1

**Comment by ankar84** [comment]
Looks like it fixed in 4.2.0
