### ISSUE TITLE
Support for Initial User Creation

### ISSUE THREAD

**Issue by leefaus** [RocketChat/Rocket.Chat#2231]
Many people want to automate the creation of their RC server deployments, just like we do.  We should pass in an option on initial setup to allow for an admin/password to be created as part of that process.  Maybe even passing in a csv file with login/password combinations to set them up through the API.  This is primarily for completely automated setups.

**Comment by Sing-Li** [comment]
Agreed.

At least for two users:

*admin
*bot

And ideally done ONLY with initial DB setup (if DB exists, no go) - so there is zero security risk.

**Comment by sampaiodiego** [comment]
I just found this: https://github.com/RocketChat/Rocket.Chat/blob/8da72776017a971bb02d27a6e1d602ec975eaf03/server/startup/initialData.coffee#L28

you can create the admin user by environment variables.

**Comment by engelgabriel** [comment]
@sampaiodiego, please add the options to pass also the Full Name and Username of the initial admin.

**Comment by RichardFoxworthy** [comment]
Is there any ability to automate creation of multiple user accounts on spin-up of a new Rocket.Chat instance? 

We'd like to automate all of the following:

- create new Rocket.Chat instances
- populate the instance with a set of standard public and private rooms (really need some public rooms to be announcement only)
- populate instance with a set of user accounts, wth ability to pre-configure permissions for appropriate per-account access to public and private rooms
- populate the instance with some templated customised content for Home page

**Comment by engelgabriel** [comment]
@RichardFoxworthy can you detail what you'd need on another issue?
Maybe have the ability to pass a JSON with some bootstrap data via environment variables? 
Maybe a JSON with a sequence of methods to call on first startup with respective arguments?

**Comment by RichardFoxworthy** [comment]
@engelgabriel see #2232
