### ISSUE TITLE
User not invited in Team chan (private or public) with auto-join feature

### ISSUE THREAD

**Issue by ImaCrea** [RocketChat/Rocket.Chat#22319]
### Description:

I try to use the "auto-join" feature built into Teams but either it doesn't work, either I don't understand how it is supposed to work.

### Steps to reproduce:

1. I'm user A and I create a team
2. I invite user B in the team
3. I create a chan (private or public) in this team and then set "auto-join" on it

### Expected behavior:

- user B should be added automatically to this team chan which has "auto-join" set

### Actual behavior:

- nothing happens for user B

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.5
- Operating System: Debian
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.8-8 / wiredTiger (oplog Activé)

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: firefox 89 / mac 10.14.6

### Additional context

- same behaviour wether it is a public or private team chan

**Comment by johncrisp** [comment]
This has been logged before here:

https://github.com/RocketChat/feature-requests/issues/463

This is fixed with this PR, and is in 3.15 (Why you should always test on the latest code)

https://github.com/RocketChat/Rocket.Chat/pull/22056

Closing as a duplicate.

**Comment by ImaCrea** [comment]
Thank you John :)
