### ISSUE TITLE
Initial Setup Script

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#2232]
We'd like to have scriptable automated setup and config of new Rocket.Chat instances:
- Populate the instance with a set of public and private rooms (we really need at least one of these public rooms to be announcement only) See #825 and #2043.
- Populate instance with a set of user accounts, including ability to pre-configure permissions for appropriate per-account access to the private rooms created in previous point, avatars, custom notifications etc
- Arbitrary ability to auto-populate any/all Administration console options with scripted values

Don't really mind what format for the script and what mechanism might be used to pass the script to the instance, but I quite like possible solution to use environment variable(s) to pass script(s) to the instance.

A nice touch would be to trigger a server restart after script completes - some Administration option require a restart before they take effect

Also ideally this scripted setup approach would be compatible with #658

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
