### ISSUE TITLE
[Bug] Thread or call buttons opens another chat sometimes

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22323]
### Description:

Now we are on 3.15.0, but I believe first I saw that bug on 3.14.0 (I may be wrong in that).
That issue is really hard to reproduce, I don't have proper steps to do that.
I don't know if that bug persist on Web version, so it could be Electron issue. But I'm not 100% sure, so making issue here.

Sometimes tread and call buttons opens another chat but not thread list or call modal.

### Steps to reproduce:

1. Go to some chat (DM, private group)
2. Click on thread button in top right (or call button)
3. Another chat opens instead of thread list (or call modal)

### Expected behavior:

Thread list should be open

### Actual behavior:

Actually I have screencast, but there is a private info, so I send it to @johncrisp at open.rocket.chat

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Anton has sent me a private screen video of this as it contains sensitive information.

I'll pass it to the devs.

**Comment by mhow2** [comment]
We have kind of a similar issue. Clicking on `Info` or `Members` buttons in the top right corner redirects/opens another channel. It seems to be the default channel (eg. `#general` by default).

**Comment by johncrisp** [comment]
@mhow2 I believe you are on 3.14.5

Can you just confirm that and any other relevant information please?

**Comment by mhow2** [comment]
> @mhow2 I believe you are on 3.14.5
> 
> Can you just confirm that and any other relevant information please?

We have two instances : 3.14.4 and 3.14.5 - we have been able to see the problem on both

**Comment by mjunghanns** [comment]
Same issue here on 3.15.0. We are using Jitsi  in combination with Rocket.Chat. Launching a new video call sometimes results in the "Invite"-button ending up in a different channel. It seems to be the default channel that these invitation links are pushed to.

**Comment by mhow2** [comment]
> We are using Jitsi in combination with Rocket.Chat.

I happened to me too, with one of our two instance having Jitsi enabled.

the other instance with version 3.14.5 does **not** use Jitsi and we stil observe the issue with channel buttons at the top-right corner.

**Comment by ankar84** [comment]
I don't know if it fixed in 3.16.3 but since update I didn't get that bug.
@johncrisp can you clarify if it really fixed in 3.16.3?

**Comment by ankar84** [comment]
> I don't know if it fixed in 3.16.3 but since update I didn't get that bug.
> @johncrisp can you clarify if it really fixed in 3.16.3?

Actually I saw that bug few times recently at our 3.16.3
So, it still not fixed there.
I don't know about 3.18.0, didn't test that heavily yet.

**Comment by ankar84** [comment]
Get it on recent 3.18.1 :(

**Comment by ankar84** [comment]
Still on 4.3.1

**Comment by ankar84** [comment]
That issue looks like https://github.com/RocketChat/Rocket.Chat/issues/24079 in it's behavior.
I guess there is some circumstances (like changing room types in mentioned issue) that lead to problems in that issue.

**Comment by pierreozoux** [comment]
@ankar84 yes, it looks related. Thanks!
I also have a screencast, but maybe with sensitive info as well, I'll check with the user if it is ok to put public, or I'll share privately.
I discussed with an other hoster, and he told me he also saw similar behavior, and recommended me to scale down app server from 2 replicas to 1 replica.
I'm not using the app, only firefox.
I opened my js console and net tab, so if it happens again, I'll have hopefully more substance to help debug this!

**Comment by ankar84** [comment]
> I also have a screencast, but maybe with sensitive info as well, I'll check with the user if it is ok to put public, or I'll share privately.

I have such screencast too and didn't post it here for a same reason ;)

**Comment by pierreozoux** [comment]
It has been more than a week now that we are running with 1 replica instead of 2, and I didn't experience this bug.

**Comment by ankar84** [comment]
Didn't see that bug since update to 5.3.1
