### ISSUE TITLE
NOT GETTING EXPECTED RESPONSE

### ISSUE THREAD

**Issue by mHassan20896** [RocketChat/Rocket.Chat#22334]
I want to communicate two client apps to each using rocket chat real time api,

I have implemented the flow as follows

Login using this api
{“msg”:“method”,“method”:“login”,“params”:[{“user”:{“email”:“xxx”},“password”:{“digest”:“xxxx”,“algorithm”:“sha-256”}}],“id”:“47”}

this api responds with:
{“msg”:“result”,“id”:“47”,“result”:{“id”:“xxxx”,“token”:“xxxxx”,“tokenExpires”:{"$date":1631366708063},“type”:“password”}}

Then I use this Api
{“msg”:“sub”,“name”:“stream-room-messages”,“params”:[“room-id”,false],“id”:“stream-room-messages-65RVqEc_16_MxJWZXbF1pw==”}

that gives this reponse

{“msg”:“nosub”,“id”:“stream-room-messages–s3KM9yYvRlMZuhAfooT6w==”}

then I call this api to send message
{“msg”:“method”,“method”:“sendMessage”,“params”:[{"_id":“user-id”,“rid”:“room-id,”,“msg”:“Hello Hassan!”}],“id”:“48”}

That responds me with

{“msg”:“result”,“id”:“48”}

But message I sent from client 1 is not received on client 2 stream.

I am hitting this url using socket: wss://open.rocket.chat/websocket

**Comment by johncrisp** [comment]
Hi,

Please note that gituhub is only for actual bugs in Rocket.Chat and not for general support.

Please stay with your topic in the forums.

https://forums.rocket.chat/t/communication-between-two-users-using-real-time-api/11392/6

Thanks.
