### ISSUE TITLE
View Full Profile link in user card stops working

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#22330]
### Description:

"View Full Profile" doesn't always work. It seems that view full profile link on the user card stops working randomly. This happens on 3.15.0 as well as the demo rocketchat at https://open.rocket.chat

### Steps to reproduce:
1.Use View Full Profile from user card in a channel.
2.Do step one a few times.
3. Enter a direct message, use "view full profile" from user card.
4. Do step 3 a few times.
5.Attempt step 1 again, it will randomly fail to load the user panel from "view full profile" in user card in a channel.

### Expected behavior:

For View Full Profile link to work correctly.

### Server Setup Information:

Version of Rocket.Chat Server: 3.15.0
Operating System: Centos
Deployment Method: tar/manual install
Number of Running Instances: 2
DB Replicaset Oplog: yes
NodeJS Version: 12.22.1
MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Isn't this related to this which you already commented on?

https://github.com/RocketChat/Rocket.Chat/issues/22205

**Comment by serviceman** [comment]
Not sure if it's related, or if I misunderstood what the issue report was about. I did notice that the user link is now showing the correct profile at https://open.rocket.chat, but the View Full Profile link is still not working as intended, so I created this report. I assumed that the pr release either did not address the above issue, or it didn't fully fix the issue.

**Comment by ankar84** [comment]
> Isn't this related to this which you already commented on?
> 
> #22205

It's not related to that issue, I guess.
As a workaround for #22205 advised users to click other user avatar in chat and click **View Full Profile** - and I see, it's not working sometimes. `CTRL+R` fixes that issue.

**Comment by serviceman** [comment]
I know you guys are busy, but I feel this really should be addressed. to have the user card not work correctly breaks a lot of usage for rocket chat. At the very least, we should be able to turn user cards off. Turning user cards off would be my first choice, as I don't really see the use for them anyway, at seems to just complicate sending a direct message. Is there a way to turn the user cards off, if this isn't going to be fixed?

**Comment by serviceman** [comment]
I have done more testing on open.rocket.chat and it seems that users with usernames that contain a period like user.name or first.last break the view profile link from working in the user cards. I would fix this myself but I am not that kind of programmer.
