### ISSUE TITLE
Exporting channel data: Handling message replies could be improved

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#22333]
### Description:

Two things:

1) When exporting a channel's messages, the replies are not sorted, they are just dumped into the HTML output. This is problematic when replies follow a different time line to the rest of the messages in the thread and hence the HTML export becomes unreadable (i.e. what message is this in response to?)

Here's what it looks like:

![1](https://user-images.githubusercontent.com/1122344/121794245-09dc2280-cc4a-11eb-88ce-97fe58a2ddae.PNG)

Exported:

![2](https://user-images.githubusercontent.com/1122344/121794246-0a74b900-cc4a-11eb-9907-9fda35081cf2.PNG)

But it could look something like this (with indentations to denote replies?)

![3](https://user-images.githubusercontent.com/1122344/121794248-0b0d4f80-cc4a-11eb-88c5-8c0af2f4e5d8.png)

Once the channel is full of messages and replies that span many different time scales, the export data becomes incoherent as the threads of conversations are lost.

2) Times in export data do not reflect times used in Rocket Chat settings. i.e. Note the channel screenshot above rightly shows message sent at 1:31pm on 11th June, but the export HTML says 3:31am. 

### Steps to reproduce:

1. Export channel data with replies

### Expected behavior:

Replies/threads are displayed as they are in the channel so conversations can be tracked; message times in export data correct 

### Actual behavior:

Export data is incoherent; times are incorrect.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.5
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Relevant logs:

No errors in logs to provide.

**Comment by johncrisp** [comment]
Thanks for reporting this.

Perhaps if you want a more detailed export then look at the APIs?

**Comment by nooblag** [comment]
Well, unless "the API" (which?) can do this (and how?), I'm not sure that's any help.

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.
