### ISSUE TITLE
When creating a new user, the message "Please wait" keeps appearing.

### ISSUE THREAD

**Issue by k-inoway** [RocketChat/Rocket.Chat#22342]
### Description:
When I create a new user, I get a "Please wait" message and am not notified that the creation is complete. It seems that the creation of the user itself is complete.

The message "Please wait" remains on the screen forever.

<img src="https://user-images.githubusercontent.com/40589931/121876888-fd88c000-cd44-11eb-9036-9b4e5efbd410.png" width="300">

### Steps to reproduce:

1. http://yourIP:3000/home
2. "Register a new account" click
3.  Enter registration
4. Make sure that "Please wait" is displayed and the screen does not transition.

### Expected behavior:
It is expected to show that the account creation is complete.

### Actual behavior:
When creating a new user, the message "Please wait" keeps appearing.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System:  Ubuntu 20.04.2 LTS (Focal Fossa)
- Deployment Method: 
I created it with docker-compose based on the following URL.
https://docs.rocket.chat/installing-and-updating/docker-containers/docker-compose
- MongoDB: 4.0.25
- Node: v12.22.1

### Client Setup Information

- Desktop App or Browser Version:  Chrome 91.0.4472.77
- Operating System: Windows10 20H2

### Relevant logs:
Neither the browser log nor the server log was output.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
