### ISSUE TITLE
[Bug] Avatars of other chats disappear when they located near chat with broken avatar

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22357]
### Description:

That issue related to https://github.com/RocketChat/Rocket.Chat/issues/22307
If some entity in sidebar have broken avatar (`#BCS FinTech` channel on my screenshots) then all other entities that located near that problem chat will lose their avatar (actually it's just not show, but still set)

### Steps to reproduce:

1. Have one user or chat with broken avatar
2. Look at other chats near that chat with broken avatar - their avatars disappears

### Expected behavior:

Chat with broken avatar should not influence other chats to avatar appearance 

### Actual behavior:

`#BCS FinTech` have broken avatar (look https://github.com/RocketChat/Rocket.Chat/issues/22307)
And chats (DM, channels and private groups) losses their avatars
You can see in series of screenshots that some chats first have avatar, then not
![image](https://user-images.githubusercontent.com/4023037/122015772-133fc900-cdc9-11eb-9ec4-255266c2a22f.png)
![image](https://user-images.githubusercontent.com/4023037/122015914-35d1e200-cdc9-11eb-85d9-82780809637c.png)
![image](https://user-images.githubusercontent.com/4023037/122016055-59952800-cdc9-11eb-89b4-0079bdee8304.png)
![image](https://user-images.githubusercontent.com/4023037/122017035-4898e680-cdca-11eb-9215-d6640df450c7.png)
![image](https://user-images.githubusercontent.com/4023037/122017133-60706a80-cdca-11eb-86dd-06e54835e6c7.png)
![image](https://user-images.githubusercontent.com/4023037/122018305-674bad00-cdcb-11eb-9059-60b860a17cc4.png)
![image](https://user-images.githubusercontent.com/4023037/122020350-60259e80-cdcd-11eb-88a3-27c63a512733.png)
Then I scroll down couple screens and all chats with avatars again
![image](https://user-images.githubusercontent.com/4023037/122021330-3f117d80-cdce-11eb-97f2-2bb62220e96b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0 (but I believe first I saw that issue on 3.14.0)
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 24
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

### Additional context

It would be nice if first problem with setting avatar to chat will be resolved

**Comment by velamvela** [comment]
I'm having this issue on 3.15 too

**Comment by ankar84** [comment]
Still an issue in 3.16.3
![image](https://user-images.githubusercontent.com/4023037/126261347-7b34d07e-4776-4ab7-ad1b-da7cfd1e9da4.png)

**Comment by ankar84** [comment]
Still an issue in 3.18.1
![image](https://user-images.githubusercontent.com/4023037/134287233-c7515d8a-6d8e-44f8-ba74-fca1aed937a0.png)

**Comment by ankar84** [comment]
Still on 3.6.3

**Comment by ankar84** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/26689
