### ISSUE TITLE
"Message Erasure Type" not working for direct messages

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#22360]
### Description:

Direct messages get deleted, even though "Message Erasure Type" is set to "Keep Messages and User Name".
"Message Erasure Type" not working for direct messages.

### Steps to reproduce:

1. As an admin, set "Message Erasure Type" to "Keep Messages and User Name" under "Message"
2. Create a User
3. Start a direct message with this user
4. Delete the User

### Expected behavior:

I'd expect all messages with the deleted account would remain.

### Actual behavior:

When an account is deleted, all direct messages with the user will be deleted.
Messages in channels or rooms will remain (as expected)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Centos 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.23

### Client Setup Information

Desktop App or Browser Version: Happens in both
Operating System: Windows / Linux / All

### Additional context

We need keep direct messages when user delete

### Relevant logs:

-

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

This is probably quite tricky. The idea of preserving messages in channel was to maintain context in a conversation.

If you want to retain direct messages as well you aren't really deleting the user, but just 'renaming' them as the data still has to be tied to a single ID no matter what the real name is.

Perhaps a dev will comment on this in due course.

**Comment by ulope** [comment]
This does not fix the issue. It merely documents the current insufficient state.
