### ISSUE TITLE
Sidebar does not update after name change

### ISSUE THREAD

**Issue by mhenninghaus77** [RocketChat/Rocket.Chat#22371]
### Description:

If we change a user name in our connected LDAP, then this changed name also appears correctly in the admin interface and for new chats. Old chats that are conducted with the user under his old user name are still displayed in the sidebar with the old name.

### Steps to reproduce:

1. Chat with a User
2. Change user name 
3. Chat again with the user, still the old username is displayed

### Expected behavior:

Changes to the user name are adopted consistently everywhere

### Actual behavior:

Username is correct in the admin interface and for new chats, for existing chats it remains the old name forever.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.14

### Client Setup Information

- Desktop App or Browser Version: All Browsers and Apps
- Operating System: -

### Additional context

This problem is not new but has always existed.

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

In the first instance please upgrade to at least 3.14.4 - see the release notes for more details.

Please also follow the issue reporting guidelines and test this on the latest version of Rocket.Chat

Fixes are being released with every version and it may be this issue has already been fixed.

https://rocket.chat/docs/contributing/reporting-issues

**Comment by mhenninghaus77** [comment]
Hi, I will do this, but the hope is low that something has been done, the bug is already present over an enormous number of versions.

Furthermore, I do not understand the reference to reporting bugs, which is exactly what I have done.

I will report after the update

**Comment by johncrisp** [comment]
> I will do this, but the hope is low that something has been done, the bug is already present over an enormous number of versions.

I can't tell say for sure. I can tell you that Rocket is growing fast and bug fixes and stability are now key, so I hope that issues like this will get resolved if they haven't been already.

> Furthermore, I do not understand the reference to reporting bugs, which is exactly what I have done.

You are on 3.14.0 - current is 3.15 which contains a lot of fixes, and 3.16 will contain more, so always please try the latest version possible.

**Comment by mhenninghaus77** [comment]
updated to 3.15.0, but the problem still occurs

**Comment by johncrisp** [comment]
> updated to 3.15.0, but the problem still occurs

The code was only just merged so should be in the next release - probably 3.16

**Comment by mhenninghaus77** [comment]
I installed 3.16 with the Fix for #22304 
So far, nothing has changed for usernames that have not yet been adjusted again in LDAP. The names remain incorrect in the sidebar
We will still check how it behaves when we change a name in ldap.

As things stand, I would say that the problem has not been fixed.

**Comment by mhenninghaus77** [comment]
Is it not possible to implement the functionality that the names in the sidebar are updated after each login?
That would be very very helpful

**Comment by mhenninghaus77** [comment]
Please reopen
