### ISSUE TITLE
Allow users to disable "no longer away" sound

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#2238]
Please, please let us disable this horrendously distracting and completely useless "ding, dong" airplane sound. We're running rocket.chat in a small team (~20 active users) and even now this sound is triggered many times an hour. I don't know how larger teams bear this.

**Comment by sampaiodiego** [comment]
this is a small bug that happens in specific situations (not so easy to track).
playing this sound when your status changes isn't the normal behavior.

I can help you make it stop for now, if it is so annoying ;)

**Comment by ulope** [comment]
> I can help you make it stop for now, if it is so annoying ;)

I would greatly appreciate this :)

**Comment by sampaiodiego** [comment]
can we talk on the demo server?
https://demo.rocket.chat/direct/diego.sampaio.rocket.team

**Comment by jmccaughey** [comment]
So, what was the solution? Thanks!

**Comment by jlgore** [comment]
Wondering this as well.

**Comment by joshua17** [comment]
Has anyone found a way around this yet?  We are using 1.3.1 and still getting the airplane noise.

**Comment by sampaiodiego** [comment]
@joshua17 the bug I described no longer exists.
if you want do disable the "airplane sound" for new chats, go to `My Account > Preferences` and set `New Room Notification` to `false`:
![image](https://cloud.githubusercontent.com/assets/8591547/15613880/1f2277a2-240c-11e6-8c34-0a4012cf7050.png)

**Comment by joshua17** [comment]
Thanks!  That did what we needed.

**Comment by maethor** [comment]
Sadly, I cannot do that, because I really need the new room notification for the livechat.
Do you have another way to fix this bug?

**Comment by engelgabriel** [comment]
@maethor please open an new issue asking for this feature.

**Comment by maethor** [comment]
So… I need to open a new issue with exactly the same subject, instead of reopening this one? OK :smile:
