### ISSUE TITLE
Accounts/Tokens: Page gets reloaded on pressing enter

### ISSUE THREAD

**Issue by aditya-mitra** [RocketChat/Rocket.Chat#22394]
### Description:

The page gets reloaded when one tries to add a new personal access token after typing the name of the token and pressing enter. 

### Steps to reproduce:

1. Go to My Account
2. Now, go to Personal Access Tokens
3. Type the name of a new token and then **press enter**
4. _The page get reloaded_

### Expected behavior:

Token gets added without the page being reloaded

### Actual behavior:

The page gets reloaded.

https://user-images.githubusercontent.com/55396651/122449733-d25fd400-cfc3-11eb-833d-26ed0cc0eae0.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.0-develop 
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
