### ISSUE TITLE
LDAP - user field map seems not to work

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#2240]
We're running 0.18.0 and I'm unable to get the example `{"cn: "name", "mail":"email"}` to work with our ldap.

**Comment by rodrigok** [comment]
At the current development version, this is working for me. Probably was fixed by https://github.com/RocketChat/Rocket.Chat/pull/2282

I will close this issue, if the problem persist on version 0.19.0, that will be released today, please reopen this issue.
