### ISSUE TITLE
Enterprise: Stuck on "Engagement Dashboard" on Administration

### ISSUE THREAD

**Issue by rcaldeiradev** [RocketChat/Rocket.Chat#22418]
### Description:

When you open the "Engagement Dashboard" in the Rocket.Chat Administration, it gets stuck there and it doesn't let you go to other administration items unless you close the administration tray and open it again.

### Steps to reproduce:

1. Go to "Administration"
2. Click on "Engagement Dashboard"
3. Click on any other admin menu item, like "Info".
4. The "Engagement Dashboard" will appear on top of the page you've clicked.

### Expected behavior:

Show only the page you've clicked.

### Actual behavior:

The "Engagement Dashboard" appears on top of the page you've clicked.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Debian GNU/Linux 9 (stretch)
- Deployment Method: PM2
- Number of Running Instances: 1
- NodeJS Version: 12.18.3
- MongoDB Version: 3.6.19

### Client Setup Information

Desktop App or Browser Version: Google Chrome 90.0.4430.212 (Official Build) (64-bit)
Operating System: Ubuntu 20.04.2 LTS

### Additional context

It also seems that the "Engagement Dashboard" button disappears when the page is refreshed from this path: /admin/info

### Relevant logs:

No relevant logs found.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
