### ISSUE TITLE
Unable to copy data from incomming webhooks page

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#2241]
Running Firefox 44.0.2 on Windows 7 I'm unable to copy the data from the incomming webhook page.

The actual data is not selectable and the link on the page has no effect for me.

![incomming_webhook_rocket chat](https://cloud.githubusercontent.com/assets/2813782/13075333/ab698522-d4aa-11e5-9466-3b5af77da1fb.png)

**Comment by hhenkel** [comment]
If I click on the link in IE11, I end up one the "Home" screen....

**Comment by vetash** [comment]
Ubuntu 14.04 FF 43. Same problem.

**Comment by engelgabriel** [comment]
What shows on the browser console
Can you make it selectable editing the CSS?

**Comment by vetash** [comment]
@engelgabriel problem is attribute disabled="disabled". I think better way is readonly="true" for these fields.

**Comment by engelgabriel** [comment]
Do you want to you make a PR?

**Comment by vetash** [comment]
Im sorry i dont know how to find file like on my server:
`/var/www/Rocket.Chat/programs/web.browser/<here long string>.js`
in github.
