### ISSUE TITLE
[BUG] Private group users can mention @all and @here despite not having this right

### ISSUE THREAD

**Issue by romansidorov** [RocketChat/Rocket.Chat#22423]
### Description:

Users of private group can mention **@all** and **@here** despite not having this right in the settings: http://joxi.ru/vAW8Rj5UOWpJdr

But when users compose a message they can mention **@all** and **@here**: http://joxi.ru/nAy1LRZSw18xjA

### Steps to reproduce:

1. Create a private group and set permissions as above
2. Compose message and mention **@all** and **@here**
3. You shall see suggestions

### Expected behavior:

I suggest users will not see any suggestions for **@all** and **@here**.

### Actual behavior:

They see :)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS 7

### Client Setup Information

- Desktop App or Browser Version: browser version in frame on website

**Comment by johncrisp** [comment]
Hi and thanks for reporting this. Looks like a definite issue.

Could you please test this on latest 3.16.x just to confirm it hasn't been fixed yet?

**Comment by romansidorov** [comment]
> Hi and thanks for reporting this. Looks like a definite issue.
> 
> Could you please test this on latest 3.16.x just to confirm it hasn't been fixed yet?

I upgraded it to 3.16.0, but the issue is still relevant.

**Comment by romansidorov** [comment]
@johncrisp John, and one more thing. I noticed that I have to type @@ (not just @) to get a list of group members. Is it an expected behavior?

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
