### ISSUE TITLE
error 403 when trying to access files that have been uploaded to a channel

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#2242]
When uploading any file (in my case to the channel #general) I get afterwards an error 403 when trying to access the previously uploaded file in the channel. 
Beside this, the website didn't respond for about 1 minute after selecting a 13MB pdf file to be uploaded. But in fact the time tthe IE was freezing hadn't been the time it took to upload the file to the server, because the upload progress itself (in percent) just began after the website came back to live. The upload itself took just some seconds because of a 25MBit upstream connection.

**Comment by renexu** [comment]
same issue, I am running rocket.chat Version: 0.19.0 on docker

**Comment by engelgabriel** [comment]
Lets close this issue and track progress on https://github.com/RocketChat/Rocket.Chat/issues/4014
