### ISSUE TITLE
Can't upload avatar

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#22427]
### Description:

I want change avatar.But it's will show not allow

### Steps to reproduce:

1. Click my account
2. Click upload and choose want change pic
3. It's can't change and show not allow.

### Expected behavior:

It's should change to new pic.

### Actual behavior:

![圖片](https://user-images.githubusercontent.com/6081927/122697349-be43fd00-d277-11eb-8f3f-a442bc05fbfa.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.2
- Operating System: Debain 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: WIN10

**Comment by ankar84** [comment]
Check **Admin UI - Account** for  **Allow User Avatar Change** option
![image](https://user-images.githubusercontent.com/4023037/122705520-98f6c500-d25e-11eb-95b2-a12af05694dc.png)

**Comment by akong77** [comment]
I have check Allow User Avatar Change is ON.But it's always not allow change it.

**Comment by ankar84** [comment]
> I have check Allow User Avatar Change is ON

Please also check **Allow User Profile Change** option

**Comment by akong77** [comment]
Yes,It's solved it.Thanks a lot.

**Comment by johncrisp** [comment]
Thanks Anton.

And closing.
