### ISSUE TITLE
Rocket.chat Desktop App not Working

### ISSUE THREAD

**Issue by ohsofoxyroxy** [RocketChat/Rocket.Chat#22436]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

Also you better report desktop client to it's own repo here https://github.com/RocketChat/Rocket.Chat.Electron/issues

**Comment by johncrisp** [comment]
I think you already have this open here so closing this in favour of this issue:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/2078
