### ISSUE TITLE
Desktop App Not Working

### ISSUE THREAD

**Issue by ohsofoxyroxy** [RocketChat/Rocket.Chat#22434]
Upon loading the rock.chat desktop app, selecting Sign In, selecting my correct CAC authentication certificate, rocket.chat just stays idle on that screen and does nothing. I am able to access the web version but would much rather use the standalone app if possible. 

![image](https://user-images.githubusercontent.com/11549214/122799816-328a9a80-d290-11eb-8933-86d11b99f483.png)

**Comment by johncrisp** [comment]
Can you please go back and fill in the template issue properly. We can't help you without that.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Also note that as you can login OK on the web, but not with the app this should probably be here.

https://github.com/RocketChat/Rocket.Chat.Electron

It would also be useful to know the app version and any customisations.

Thanks.

**Comment by johncrisp** [comment]
Closing this and please follow up on the Electron issue
