### ISSUE TITLE
How to change the font size of messages?

### ISSUE THREAD

**Issue by georgebezerra** [RocketChat/Rocket.Chat#22444]
Hi

 I'm trying to increase the font size of the messages, which are currently with 14px font to 16px. I've already changed several files, using the Inspect Browser element, but I haven't had success. 

Can anyone tell me where I make this change ? 

Any kind of help would greatly appreciate 

![image](https://user-images.githubusercontent.com/18728813/122933002-9bcbe580-d344-11eb-8872-f189a882c139.png)

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

You can try to increase messages size via **Admin UI - Layout - Custom CSS**
In **Custom CSS** section try these as examples

```
:root {
	--input-font-size: 1.1rem;
  	--text-small-size: 0.975rem;
	--text-default-size: 1.1rem;
}
```

**Comment by georgebezerra** [comment]
Hi,

Thank you for the guidance on how to proceed whenever you have questions. I will follow them for sure.

The guidance you gave me worked.

Thanks.

[]s

George Bezerra

**Comment by johncrisp** [comment]
Thanks. Closing
