### ISSUE TITLE
stream-notify-room method is not working

### ISSUE THREAD

**Issue by sujasundaresan** [RocketChat/Rocket.Chat#22441]
### Description:
Am using websocket to communicate with the Rocket chat server. Am trying to implement the **typing** event indicator on the UI. For that, am calling "stream-notify-room" method. But it is not working.

### Steps to reproduce:

1. I have initiated a 'stream-notify-room' subscription, when a room is created 
`this.$socket.send({
        msg: 'sub',
        id: '42',
        name: 'stream-notify-room',
        params: [
          this.room + '/typing',
          false
        ]
      })`
2. Subscription functionality is working fine. I tested and confirmed by connecting the Rocket chat server.
3. From the UI, On message typing, I have triggered
`this.$socket.send({
          msg: 'method',
          method: 'stream-notify-room',
          id: '42',
          params: [
            this.room + '/typing',
            this.$attrs.user.username,
            true
          ]
        })`
4. From the UI, On message clear/typing stop, I have triggered
`this.$socket.send({
          msg: 'method',
          method: 'stream-notify-room',
          id: '42',
          params: [
            this.room + '/typing',
            this.$attrs.user.username,
            false
          ]
        })`
5. On these two above event the socket message shows as 
`{
  "msg": "result",
  "id": "stream-notify-room-cKe3k3Mkhk7d8i9y2"
}`
6. There is no socket message reaching on the other user(on same room) side.

### Expected behavior:
Some message should be reach on the other user socket and display the typing event.

### Actual behavior:
No message/event reaching on the socket.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.4
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 3.6.14 

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Ubuntu

**Comment by johncrisp** [comment]
Hi,

Please use Github for bugs and not general support questions.

If you think you have found a bug then use the bug template here, but read all the links first before posting.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you always test on the latest version of Rocket.chat as things get fixed all the time and any issue may have already been done.

If you want support then use https://forums/rocket/chat or https://open.rocket.chat #support 

You can chat through issues there before posting here.

I can't see any signs of an error here so closing for now - will re-open if there is actually a bug.

**Comment by sujasundaresan** [comment]
Thanks for your comments
