### ISSUE TITLE
Mac Desktop App fails to load

### ISSUE THREAD

**Issue by sudhanshuraheja** [RocketChat/Rocket.Chat#2245]
We have been trying to use the Mac app but it fails to load with the following error. 
Refused to display 'site_url' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

How do I fix this?

I am on version 0.16.0

**Comment by engelgabriel** [comment]
Can you try to upgrade your version?

**Comment by engelgabriel** [comment]
What version of the Desktop app are you using?

**Comment by sudhanshuraheja** [comment]
I am on version 0.0.9 of the MacApp.

On Tue, Feb 16, 2016 at 9:12 PM, Gabriel Engel <notifications@github.com>
wrote:

> What version of the Desktop app are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/2245#issuecomment-184737184>
> .
>



-- 
Sudhanshu Raheja
Managing Director, Leftshift Technologies
http://leftshift.io | +91-9960980066 | @leftshifters

**Comment by engelgabriel** [comment]
Please download the new BEtA from https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by sudhanshuraheja** [comment]
Thanks, this works! You are awesome.

On Wed, Feb 17, 2016 at 5:07 PM, Gabriel Engel <notifications@github.com>
wrote:

> Closed #2245 <https://github.com/RocketChat/Rocket.Chat/issues/2245>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/2245#event-553434252>.
>



-- 
Sudhanshu Raheja
Managing Director, Leftshift Technologies
http://leftshift.io | +91-9960980066 | @leftshifters
