### ISSUE TITLE
Ver 3.15.0 - LDAP Synch no longer adds users to Teams

### ISSUE THREAD

**Issue by vplb** [RocketChat/Rocket.Chat#22453]
### Description:

Previous versions, we were adding users to Teams via LDAP synch to channels. 
After update, this doesn't happen anymore. 
Error "I20210622-23:48:22.938(0) server.js:204 LDAPSync ➔ error Can't add user to channel __________________ because it is a team.
No replacement option seems to have been added. This is a major break in functionality to us, as we add and move many users over time, and having this automated is important. 

### Steps to reproduce:

1. Add user to channel-mapped group in Active Directory
2. Synchronize LDAP manually
3. User not added, view logs. 

### Expected behavior:

User added to Team. 

### Server Setup Information:

- Version of Rocket.Chat Server:  3.15.0
- Operating System: Ubuntu Linux
- Deployment Method: Docker Compose
- Number of Running Instances: 2
- DB Replicaset Oplog: y
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.23 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Windows 10

### Relevant logs:

I20210622-23:48:22.937(0) server.js:204 LDAPSync ➔ debug john is in TEAMGROUP group. 
I20210622-23:48:22.938(0) server.js:204 LDAPSync ➔ error Can't add user to channel TEAMGROUPTEAM because it is a team. 
I20210622-23:48:22.940(0) server.js:204 LDAPSync ➔ info Synced user group user from LDAP for john

**Comment by johncrisp** [comment]
Hi and thanks for reporting this . I wil try and get some advice.l

**Comment by johncrisp** [comment]
Can you please advise when you noticed the change in behaviour?

**Comment by vplb** [comment]
I noticed the action on June 18th, but my colleague located the change in the code. (i apologize if i get something wrong here, i'm not a programmer). 
https://github.com/RocketChat/Rocket.Chat/commit/fefb3e01661226248f993e6d5b6cc1e42da6e2aa
![image](https://user-images.githubusercontent.com/69546199/123334595-2acd2f00-d4f8-11eb-8026-0790c55970f4.png)

**Comment by johncrisp** [comment]
What was you prior Rocket.Chat version?

**Comment by vplb** [comment]
So it appears that someone intended it to handle this way, but it removes functionality that is very useful (almost critical to us), and that logically would be used by anyone managing teams/channels via LDAP, without a replacement method.

**Comment by vplb** [comment]
Prior version was 3.13.3

**Comment by johncrisp** [comment]
OK thanks.

Trying to get to the bottom of this.

**Comment by vplb** [comment]
Much appreciated!

**Comment by WesleydosReis** [comment]
I have the same problem.

**Comment by johncrisp** [comment]
OK, as far as I understand it this feature was only available in 3.14.x and that was a mistake. It should be EE only.

Can you please confirm this with a test?

Thanks.

**Comment by vplb** [comment]
If that's the case, that burns. Hard. Have a tool, use it, depend on it, have it stripped. To see so many other active bugs not getting full fixes, while new additions are added, then to have someone decide that the priority is to strip functionality is painful. Like OTR isn't working, updating statuses is still choppy, ldap isn't robust, but paywalling a _working_ function was a priority. 

Thanks for checking. We cannot afford enterprise at this time, Corona, already limited resources, public organization. We were offered an enterprise platform (very big name, mature, closed) for free, we turned it down in favor of RocketChat for local storage and access, configurability. It's always the coders' prerogative of course, it's just disappointing.

Thank you John, i'm not sure what tests you want me to run (if you were speaking to me), but on my end i consider this closed if you have what you need as well. Let me know.

**Comment by caesarcxiv** [comment]
Agree that this was a purposeful change to entice EE - we had converted to use the teams feature in a hope to tag @team - then found out that was enterprise as well. We left the team channels since we had already converted the channels. The LDAP sync was then stripped. We had to rename all of our team channels, archive them and create all new private channels to get the sync back - this was poor experience however this is a great opensource application that we support. IMO Teams should not be paywalled.

Perhaps you can add to teams via API calls? I haven't checked.

**Comment by johncrisp** [comment]
> Agree that this was a purposeful change to entice EE

Please note I have been advised by some somewhat red faced personnel that this was *not* done on purpose. 

It should never have been released as Community.

> Thank you John, i'm not sure what tests you want me to run (if you were speaking to me), but on my end i consider this closed if you have what you need as well. Let me know.

Yes I would like to pin down exactly which version this started in. I was advised in 3.14 but you are indicating 3.13 and I wanted to clear this up.

Believe me I do feel your pain and I will be relating you comments back to those involved.

> We were offered an enterprise platform (very big name, mature, closed) for free, we turned it down in favor of RocketChat 

Please DM through open.rocket.chat or email me details. I can raise this specifically.

**Comment by johncrisp** [comment]
As a follow up

> I mixed up the version numbers, it only worked on 3.13 - it was removed on 3.14

> the feature to sync channels existed for a long time, then when we created the Teams feature on 3.13, that sync worked for teams as well - in 3.14 we implemented the team sync for EE and blocked the channel sync from also syncing teams

I am pursuing this.

**Comment by vplb** [comment]
@caesarcxiv In 3.15 it looks like they added an option to turn a team back into a channel. I haven't tried it yet, but i am hoping to avoid doing the same as you. We chose an odd time i guess for rollout, so the workunits we imported were all told they'd be using this Team>Channel structure. 
Even if the API call works, I'd not suggest using it. It may also be patched out eventually. 

@johncrisp Sorry i may not have been as clear as i could be. We were using 3.13.3, the LDAP and Teams were working correctly in that version. We skipped 14, and went to 15 where it stopped. I will try to DM you today, i appreciate the efforts.

**Comment by vplb** [comment]
@caesarcxiv I found some info!
there is an api call to add to teams, but it's not working currently, there's a change open for it, https://github.com/RocketChat/Rocket.Chat/pull/22169

There is a workaround, using the Group Invite api. This will add people to teams: 
 https://developer.rocket.chat/api/rest-api/endpoints/groups/invite

I'm also working on a script that runs on the LDAP server, checks against a preloaded list of teams/ad groups, and sends out api calls to add people. I don't know if this would be of assistance, and i'm beyond amateur at scripting, but i could post what i have if you want to try to work with it.

**Comment by caesarcxiv** [comment]
@vplb awesome thanks for sharing. Your script would be of assistance - thanks!

**Comment by vplb** [comment]
@caesarcxiv hey, uh, sorry was a holiday here yesterday. It's not complete, and it's not pretty. I'll post it as soon as it's done, or if  you want to meet up in open.rocket.chat, i can send you what i have if you want to finish it. Cheers.

**Comment by vplb** [comment]
@caesarcxiv The Powershell script is not totally complete. I really am not a scripter, but i'm working on it. 
Will require that you keep a list of LDAP/AD Teams and their RC counterparts in order. Update them as you add new ones to the mapping in Rocket.Chat. 
What isn't working is the last api request to add the user to the group/team. Manually making the request is fine, but escaping the json formatting in Powershell is giving me endless trouble. Hopefully someone smarter, or you, figure it out, or i'll keep banging at it for a while. 
I do not imagine this is the optimal way to do it, but it seems to do everything in testing up to the very last line which is the API request. 
This also assumes you used the same usernames. If not, you'll have to change the "$rchatuser.username" to $rchat.emailorwhateveryouused.

Powershell - this runs on Active Directory server:
```

$headers = @{
    'X-User-Id' = 'youruserid'
    'X-Auth-Token' = 'yourtoken'
    'Content-type' = 'application/json'
}
#api call address and options
$request_userlist = 'https://rocket.chat.host/api/v1/users.list?&query={"active":true,"ldap":true}&count=1000'
#the call using powershell's invoke-restmethod, combining the other parts
$response_userlist = Invoke-RestMethod -Uri $request_userlist -Method Get -Headers $headers
$rchatusers = $response_userlist.users
#Create Object Array. This has to be updated with new AD groups, and RC Teams. Must be kept 1-1. Can't get the mapping from RC in api request i don't think. Could copy the json, save in another file and reference it here. 
$groups = @(
	[pscustomobject]@{adgroup="rcteam1";rcteam="rcteam1"}
	[pscustomobject]@{adgroup="adteam2";rcteam="rcteam2"}
	[pscustomobject]@{adgroup="adteam3";rcteam="rcteam3"}
)
#setup the api call for user list
$request_userlist = 'https://rocket.chat.host/api/v1/users.list?&query={"active":true,"ldap":true}&count=1000'
#call the api request
$response_userlist = Invoke-RestMethod -Uri $request_userlist -Method Get -Headers $headers
#create a list of users, by their user-fields
$rchatusers = $response_userlist.users
#loop each user in the list of users
foreach ($rchatuser in $rchatusers){
#get list of user's AD groups by name and their UID. The invite to group api will accept room ID or room name, but only user ID. 
	$uid = $rchatuser._id #get uid in another var, because you lose rchatuser from here. 
	$rchatuser = $rchatuser.username
	$usergroups = Get-ADPrincipalGroupMembership $rchatuser | select name
#simplify the usergroups variable to just the name of the groups, not all the info dumped
	$usergroups = $usergroups.name
#check if ANY of the objects in usergroups is in groups.adgroups
	$usergroups | ForEach-Object {
		if ($_ -in $groups.adgroup) {
#get the index of the adgroup, to get the matching rocketchat group. 
			$num = $usergroups.indexof($_)
#create the api request			
			$request_teamadd = 'http://localhost:3000/api/v1/groups.invite'
			$body_teamadd = '-d ' + "{ "roomId": "$groups.rcteam[$num]", "userId": "$uid" }'"
#send post request. ****THIS DOESN"T WORK. I'm having trouble with the parser to get the text formatted correctly.			
			Invoke-Restmethod -Uri $request_teamadd -Method Post -Headers $headers -Body $body_teamadd
		}
	}
}

```

**Comment by johncrisp** [comment]
Just as a FYI as previously advised this feature was never meant to be generally released. It really was a genuine accident caused by a mix up. The whole team offers its sincerest apologies.

Due to the complex nature of Teams they can't JUST leave this bit out because there are a host of other changes coming that this is an integral part of, and trying to separate it will break a lot of other things in the process.

Yes it would be great if one day it was all completely open source!! But now is not that day. As the community team we try to ensure as much code is open source as possible. The more people that help us, the louder our voice is. So do please come and get involved.

I digress. In short this is effectively NotABug/WontFix.

I can see some of you looking at some ​API workarounds possibly involving the API and https://github.com/RocketChat/Rocket.Chat/pull/22169

So I am going to leave this Issue open for a while for you to continue your discussions and for others also caught by it.

I am wondering if even if this isn't in the main UI whether it is possible to at least have some API end points around to help.

If there is enough interest I might be able to discuss it with the Product team.

It would be better if this could be moved to the forums or open.rocket - we could open a separate channel there. Just come and find me and talk about it.

**Comment by vplb** [comment]
I finished an initial draft of a working script, but it's slow and loopy. 
I don't think anyone else is here anymore, i'm totally ok to close this. 

Workaround: create powershell script that synchronizes teams to AD groups, and sends API requests via. Groups Invite (not Teams invite, that is currently bugged). 

ty for all!

**Comment by caesarcxiv** [comment]
Love to see the script if you can share

**Comment by vplb** [comment]
@caesarcxiv 
Hey, sorry about that. Ok, it isn't elegant, maybe you can use it as a starting point, but it'll sort of mash it's way through. 
I'm starting from scratch with a different method, but i don't know when i'll be able to complete it. 

1. You have to keep a list of your mapped groups updated. Save this as a .ps1 file on a server/computer that has Powershell with the AD module.  
2. It goes through every user in your RC server that is LDAP, then compares what groups they're in against that list. 
3. If they match, it sends a request to create them through the Group Invite api. (team invite API isn't working right now, when it does should be changed to that)
4. it doesn't check if they're already in a group. Can add this step maybe to reduce API calls. It just requests for every matched group.
5. You'll probably need to disable the API "Rate Limiter" in Administration
6. I have a bunch of "write-host" outputs to track what's going on for testing. I left in my notes as well. can always delete them or add more. I dunno how comfortable you are in powershell, so the command is: `write-host "entertexthere" $variable`

`$headers = @{
    "X-User-Id" = "_________________"
    "X-Auth-Token" = "_________________"
    "Content-type" = "application/json"
}
#Create Object Array. This has to be updated with new AD groups, and RC Teams. Case sensitive. 
$groups = @(
	[pscustomobject]@{adgroup="ActiveDirectoryTeam";rcteam="RocketChatTeam"}
	[pscustomobject]@{adgroup="ActiveDirectoryTeam";rcteam="RocketChatTeam"}
	[pscustomobject]@{adgroup="ActiveDirectoryTeam";rcteam="RocketChatTeam"}
	[pscustomobject]@{adgroup="ActiveDirectoryTeam";rcteam="RocketChatTeam"}
	[pscustomobject]@{adgroup="ActiveDirectoryTeam";rcteam="RocketChatTeam"}
	[pscustomobject]@{adgroup="ActiveDirectoryTeam";rcteam="RocketChatTeam"}	

)
#setup the api call for user list
$request_userlist = 'https://yourhost/api/v1/users.list?&query={"active":true,"ldap":true}'
#call the api request
$response_userlist = Invoke-RestMethod -Uri $request_userlist -Method Get -Headers $headers
#create a list of users, by their user-fields
$rchatusers = $response_userlist.users
#loop each user in the list of users
foreach ($rchatuser in $rchatusers){
#get list of user's AD groups by name and their UID. The invite to group api will accept room ID or room name, but only user ID. 
	$uid = $rchatuser._id #get uid in another var, because you lose rchatuser from here. 
	$rchatuser = $rchatuser.username
	write-host "rchatuser:" $rchatuser
	write-host "rchatuser ID: " $uid
	$usergroups = Get-ADPrincipalGroupMembership $rchatuser | select name
#simplify the usergroups variable to just the name of the groups, not all the info dumped
	$usergroups = $usergroups.name
	"usergroups: $usergroups"
	$usergroups.length
#check if ANY of the objects in usergroups is in groups.adgroups
	$usergroups | ForEach-Object { 
		if ($groups.adgroup -contains $_) {
		$num = $groups | where-object -Property adgroup -contains $_
		$num = $num.rcteam
		write-host "Matched rcteam group: " $num
		$body_teamadd = @{
			roomId = $num
			userId = $uid
		}
		$body_teamadd = $body_teamadd | ConvertTo-Json -compress
		$request_teamadd = 'https://yourhost/api/v1/groups.invite'
		write-host "Team request will be: " $request_teamadd $body_teamadd
		$response_teamadd = Invoke-Restmethod -Uri $request_teamadd -Method Post -Headers $headers -Body $body_teamadd
		$response_teamadd
		}
	}
}
`
