### ISSUE TITLE
Display error in Firefox, content squeezed to the head

### ISSUE THREAD

**Issue by mjunghanns** [RocketChat/Rocket.Chat#22468]
### Description:
When using Firefox (tested with 89.0.2, 89.0b7 developer and 90.0b12 developer), all elements of Rocket.Chat seem to be squeezed to the window's head. Haven't done any research yet but it seems to me that CSS is broken in some way.

It works as expected in Chromium based browsers.

### Steps to reproduce:

Access Rocket.Chat through Firefox Browser

### Expected behavior:

Rocket.Chat should use the entire window.

### Actual behavior:

All elements of Rocket.Chat seem to be squeezed to the window's head. (Pic. 1) This also applies to the administration view. Quite interesting is the fact, that the administration view extends to the exact size of the menu that is shown when you click on your avatar icon to access the administration view. (Pic. 2-3)

Screenshots:
![image](https://user-images.githubusercontent.com/22636982/123386573-19872f80-d597-11eb-82f5-1a755001c690.png)
Pic. 1

![image](https://user-images.githubusercontent.com/22636982/123387532-2d7f6100-d598-11eb-8ed0-8a8b0bf0bf75.png)
Pic. 2

![image](https://user-images.githubusercontent.com/22636982/123388232-d7f78400-d598-11eb-95f1-b2bc91f5836e.png)
Pic. 3

### Server Setup Information:

- Version of Rocket.Chat Server:  3.16.0-rc.1
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v12.22.1
- MongoDB Version: 4.0.24 

### Client Setup Information

- Desktop App or Browser Version: Firefox 89.0.2, 89.0.1, 89.0b7 developer and 90.0b12 developer
- Operating System: Windows 10 and Linux Mint 19.1 Tessa

**Comment by ankar84** [comment]
I believe that bug fixed by https://github.com/RocketChat/Rocket.Chat/pull/22433 and will shipped at 3.16.0 release

**Comment by mjunghanns** [comment]
It seems to be fixed.
