### ISSUE TITLE
Rocket.Chat Package Manager - A more modular design

### ISSUE THREAD

**Issue by ywecur** [RocketChat/Rocket.Chat#2246]
There are many features that could be created, but many are not desired by all. The best way to make this a flexible and universal chat solution is to introduce features as packages, with server maintainers themselves choosing which to include. Examples of packages would include things like [XMPP support](https://github.com/RocketChat/Rocket.Chat/issues/404) and [conversation threading](https://github.com/RocketChat/Rocket.Chat/issues/1112), but would also extend to most features of Rocket.Chat (e.g. Video Conferencing).

This method is currently used by, for example, [the text editor Atom](https://github.com/atom/atom) through the Atom Package Manager, and with great success. The _modular design_ of the project (a minimal core with packages for specific features) is perhaps its greatest feature and probably the reason it's as successful and universally loved as it is. Disagreements about what to include into Atom are basically non-existent as people could just release a feature as a package rather than having to rely on a majority of users being interested in a feature.

The greatest feature in my opinion, though, is **the ability for server maintainers to implement their own features without having to fork the project completely**; They could simply write a package that they install on their instance. This would greatly increase the flexibility and usability of the project and lead to _a superior number of available features_ for Rocket.Chat as opposed to its alternatives, probably making it the truly greatest alternative.

**Comment by engelgabriel** [comment]
Hi @ywecur and thanks for the great input. Can you please re-post this at https://github.com/RocketChat/Rocket.Chat/issues/1859 to avoid duplication?

**Comment by ywecur** [comment]
@engelgabriel Sorry. I searched for package manager and got no results, so I assumed that such an issue didn't exist.
