### ISSUE TITLE
Delete Discussion

### ISSUE THREAD

**Issue by viewprox86** [RocketChat/Rocket.Chat#22474]
I've been struggling for months trying to figure out how a user can delete a discussion, even if they're the last owner.  I've only been using RC a few months, and already the left sidebar is full of old dead discussions, more added every day, with the only way to delete them is to ask the admin of the site to do so I believe.

I've posted a comment on #13664  and #13689.  Sure wish someone could help advise on this front because this seems like the ultimate dealbreaker unless there's some simple thing I've overlooked.  Appreciate some guidance.  Thanks!

**Comment by hugocostadev** [comment]
You can delete by clicking in the Room Information and pressing delete
