### ISSUE TITLE
Give me please configuring manual, transfer file in a chat. Files don't open in chat. The browser displays an error: http://localhost:3000/file-upload/L2Yg9xkAJ7uWKPpWu/...0%BA.bmp?download

### ISSUE THREAD

**Issue by dkorpachev** [RocketChat/Rocket.Chat#22473]
Help me. Files don't open in chat. How to rename localhost to ip address ? Give me please configuring manual, transfer file in a chat. How to change Site URL: http://localhost:3000 ?

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

**And please rename you issue to something more meaningful.**

**Comment by johncrisp** [comment]
This seems to be a support issue.

https://forums.rocket.chat/t/how-to-rename-localhost/11491

We can re-open if we find a bug.
