### ISSUE TITLE
3.16.0 broke CDN

### ISSUE THREAD

**Issue by avignat** [RocketChat/Rocket.Chat#22490]
### Description:

3.16.0 broke CDN links

### Steps to reproduce:

1. Update to 3.16.0 from 3.15.1

### Expected behavior:

Rocket interface to load from CDN

### Actual behavior:

Interface not loading

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.0
- Operating System: Debian 10
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: Docker
- MongoDB Version: Docker

### Client Setup Information

- Desktop App or Browser Version: Buggy Electron App
- Operating System: Fedora

### Additional context

Can't downgrade to 3.15.1 had to disable CDN with `db.rocketchat_settings.update({_id:"CDN_PREFIX"},{$set:{"value":""}})`

### Relevant logs:

Nothing inside container.
Inside the browser console :
![Capture d’écran de 2021-06-28 09-42-08](https://user-images.githubusercontent.com/1545450/123600273-cad7d080-d7f6-11eb-8873-06eea545640f.png)

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Downgrading is rarely a good idea - please check if there are DB changes between versions. If there are it can seriously impact you.

To avoid automatic upgrades it is best practice not to use 'latest' but a fixed version. You can then fully test prior to upgrading.

I need to have a discussion with one of the devs as I am not sure why this situation would happen.

**Comment by avignat** [comment]
I know that downgrading can be a bad idea, I did a backup before.
I always used fixed version not latest.

**Comment by nmagedman** [comment]
This bug is caused by #20724 not including the CDN as a CSP source.
