### ISSUE TITLE
WebRTC call not working with Docker

### ISSUE THREAD

**Issue by chitkiu** [RocketChat/Rocket.Chat#2249]
I install Rocket.chat with docker and isn't work
But when i install with meteor and write meteor remove rocketchat:webrtc and meteor add rocketchat:webrtc it's work

**Comment by geekgonecrazy** [comment]
This is an issue we need to verify.

I worked a bit with @chitkiu in the support channel on the server and requested an issue be posted here.

### Doesn't work
Running via docker the WebRTC piece does not work.

I'm wondering if this is a port thing?  We need to verify that this is working for us.

### Works
But running via meteor and doing `meteor remove rocketchat:webrtc` and `meteor add rocketchat:webrtc` works.

To me this makes no sense at all why this would work...  This seems like a pointless step that should do absolutely nothing.  But in this case it appears to have?  I don't know how we replicate this bug... 


So really for this issue we probably need to just focus on making sure it works in docker.  Maybe update the documentation if there are ports that need opened when they want to use webrtc.

**Comment by rodrigok** [comment]
Can you test with this fix? https://github.com/RocketChat/Rocket.Chat/pull/2267

To be sure if your version is up to date, the new version has the config field **STUN/TURN Servers** as you can see on the PR image.

**Comment by chitkiu** [comment]
@rodrigok I test tomorrow

**Comment by pachox** [comment]
rodrigok, there is an issue on live demo too. and on my own host (build like this https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker).
what happens is that i see my own video twice, both in main and i secondary window. i can't apply the meteor workaround as i get this error: remove: You're not in a Meteor project directory.

**Comment by Sing-Li** [comment]
@pachox live demo is definitely fixed.  Fixed in #2667

You should try the [latest beta development build](https://rocket.chat/releases) as well - it should be fixed.

**Comment by pachox** [comment]
I'm going to test in a couple of hours.  Thank you

-------- Original message --------

**Comment by pachox** [comment]
i've just installed the latest beta, still no joy. but i can't see things fixed in live demo too.

**Comment by rodrigok** [comment]
@pachox what do you mean with `i see my own video twice,`?

You see the desired video as a large video on top and a video for all participants below, including your video, you can switch the main video clicking on smaller videos.

If you start a call and no one connects probably you will see you in the main video and only you in small videos, the main video will change when some one connects.

**Comment by pachox** [comment]
I fixed meteor, everything is fine now (using last beta).

Thank you

 

Pacho Baratta

UC Specialist Engineer

Service Creation

 

fabbricadigitale srl 

----------------------------- 

Via A.Volta, 3 – 26041

Casalmaggiore – Cremona - Italy

Phone +39  <tel:+390375284600> 0375 284600

 <http://www.fabbricadigitale.it/> http://www.fabbricadigitale.it

**Comment by sagar-srivastava** [comment]
for me, on my docker install webRTC is not working.

**Comment by zzswang** [comment]
me too, 

it doesn't work from latest official docker image.

**Comment by jmls** [comment]
aha - we've hit the same problem with docker - anyone got any clues ?

**Comment by designgurudotorg** [comment]
I'm finding the same thing... using 0.33.0 on Ubuntu/Docker

**Comment by geekgonecrazy** [comment]
So when looking into this.  It doesn't appear to be a docker thing.  We use turn servers for discovering the peers.  So this is happening client side, being docker isn't effecting this.  Its a feature in beta that we are working actively on fixing.

**Comment by krimlon** [comment]
has this ever been fixed? I am unable to use also.

**Comment by saggy2** [comment]
never worked for me

**Comment by akelon-user** [comment]
WebRTC doesn't work neither in Docker nor as Manual install in ubuntu
