### ISSUE TITLE
[Bug] DISABLE_PRESENCE_MONITOR env var seems not working

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#22503]
### Description:

PR https://github.com/RocketChat/Rocket.Chat/pull/22257 should fix handling of `DISABLE_PRESENCE_MONITOR=true` env var handling. But looks that still not working as it should.
I have tested with two containers with set `DISABLE_PRESENCE_MONITOR=true` and presence is still updated in real time. I expect in that case that it will works same as global presence monitor off (Admin -> Trubleshoot -> Disable Presence Brodcast -> OFF). Until it will be fixed is not possible to set configurations with only one docker container with ENABLED `Presence Monitor` and others with off. This configuration should prevent broadcast storms described in https://github.com/RocketChat/Rocket.Chat/issues/21182
I have tested with `USE_NATIVE_OPLOG=true` and without this parameter. 

### Steps to reproduce:

1. Set `DISABLE_PRESENCE_MONITOR=true` on all docker containers
2. Check that presence is online updated, same as without `DISABLE_PRESENCE_MONITOR=true` set

### Expected behavior:

When all docker containers have set `DISABLE_PRESENCE_MONITOR=true` presence should not be brodcasted.

### Actual behavior:

Instance broadcast presence only when has not set `DISABLE_PRESENCE_MONITOR=true`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.0
- Operating System: Centos 7
- Deployment Method: docker-compose
- Number of Running Instances: 5
- DB Replicaset Oplog: YES
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: all
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Thanks Emil.

I'm sure the devs will look a this.

**Comment by sampaiodiego** [comment]
hi @emikolajczak .. just to make sure, what is the latest version you tested where `DISABLE_PRESENCE_MONITOR` was working?

**Comment by emikolajczak** [comment]
Hi Diego,
I think it was 3.6.3, but I'm not 100% sure.
For sure on 3.6.3 I have no problems with crashes caused by presence broadcasts storms. It was started after upgrade 3.6.3 to 3.9.7.
