### ISSUE TITLE
Load directly into channel

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2251]
Is there a way from with the apps to load directly into a channel, skipping the first screen/layout screen?

**Comment by engelgabriel** [comment]
Just use the channel URL, like https://demo.rocket.chat/channel/general
Please reopen this if I missunderstood your question.

**Comment by royalaid** [comment]
Specifically from within the Cordova Apps for android and iOS

**Comment by engelgabriel** [comment]
Can you please open the issue on the cordova project?
https://github.com/RocketChat/Rocket.Chat.Cordova/issues
