### ISSUE TITLE
Can't create new discussions

### ISSUE THREAD

**Issue by kimokahookele** [RocketChat/Rocket.Chat#22517]

**Comment by johncrisp** [comment]
Hi.

Unless you fill in a bug template we can't help you.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/getting-support

I expect this is probably a support question so please visit https://forums.rocket.chat or https://open.rocket.chat #support 

We can re-open if you have found a bug.
