### ISSUE TITLE
CAS login window won't close due to content security policy

### ISSUE THREAD

**Issue by Monschichi** [RocketChat/Rocket.Chat#22525]
### Description:

When logging in via CAS the login window doesn't close with version 3.16.0.

### Steps to reproduce:

1. enable CAS login
2. login via CAS
3. CAS login window stays open
4. when manually closed the login to rocket chat works

### Expected behavior:

1. login via CAS
2. CAS login window closes automatically

### Actual behavior:

1. login via CAS
2. CAS login window does not close automatically

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.0
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 6
- NodeJS Version: 12.22.1
- MongoDB Version: 3.6.18

### Client Setup Information

- Desktop App or Browser Version: Firefox 89.0.2 and Chromium 91.0.4472.114
- Operating System: Linux

### Additional context

Until Version 3.15.0 the auto close worked fine.
The final CAS page https://DOMAIN/_cas/XXX contains `<html><head><script>window.close()</script></head></html>` and the content security policy is: `default-src 'self'; script-src 'self' 'unsafe-eval'; connect-src * 'self' data:; img-src data: 'self' http://* https://*; style-src 'self' 'unsafe-inline'; media-src 'self' http://* https://*; frame-src 'self' http://* https://*; font-src 'self' data:;`.
Developer console outputs: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

### Relevant logs:

Developer console: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

**Comment by bseclier** [comment]
Thanks for posting the issue @Monschichi.
Same problem in 3.16.1, this is a blocking issue :(

**Comment by goyome** [comment]
The chromium developer console add some information on the way to correct the problem.

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-jqxtvDkBbRAl9Hpqv68WdNOieepg8tJSYu1xIy7zT34='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by goyome** [comment]
It seems to be linked to this change 
https://github.com/RocketChat/Rocket.Chat/commit/9c54b0692be328a4ad5ec4da488509426334a104#diff-7998f0ae224f9a862f2bf4658d4c4eef10347ffc455812d4c778fde795c75270

**Comment by goyome** [comment]
So, if you're stuck with this, you can disable CSP in Administration > General. But it's just a workaround.
I'm wondering if it would be possible to just add the hash of the script to cors.js or there is a best way to include it only for this page

`... script-src 'self' 'unsafe-eval' 'sha256-jqxtvDkBbRAl9Hpqv68WdNOieepg8tJSYu1xIy7zT34='...`

**Comment by Rollbacke** [comment]
The problem is still there in version 3.16.3.

**Comment by camherry** [comment]
The problem is still there in version 3.17.1.

**Comment by Rollbacke** [comment]
The problem is still there in version 3.18.1.

**Comment by goyome** [comment]
Hi, 
Just a ping to see if you could look at the PR. This issue is quite annoying as you can't login to RC without closing the blank useless window. This isn't a really user-friendly behavior.

Thanks in advance for your reply

**Comment by bseclier** [comment]
Hi,
Just a ping to see if you could look at the PR. This issue is quite annoying as you can't login to RC without closing the blank useless window. This isn't a really user-friendly behavior.

Thanks in advance for your reply.

**Comment by pierre-lehnen-rc** [comment]
Fixed by #23215
