### ISSUE TITLE
iOS - Clicking Search button in Rocket Chat does nothing. 

### ISSUE THREAD

**Issue by VasylKonstantinov** [RocketChat/Rocket.Chat#22539]
### Description:
iPhone only. Clicking Search button in Rocket Chat does nothing. 

### Steps to reproduce:
1) In the RC locate the "Find Chat" button and click it.

### Expected behavior:
The search dialog appears.

### Actual behavior:
Nothing happens.

### Server Setup Information:
- Version of Rocket.Chat Server: 3.12.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 30-60
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.18

### Client Setup Information
- Desktop App or Browser Version: Browser
- Operating System: iOS

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

First, as we have previously advised, you are going to have to upgrade as 3.12.1 is not supported (and I note that on this bug you have a different Mongo DB version?)

Please follow the issue reporting guidelines and test on the latest version.

Next, note that if this is an issue then it will be with the react native app so this is in the wrong repo.

Please test it thoroughly and if it persists on 3.16.x + the latest iOS app then look here:

https://github.com/RocketChat/Rocket.Chat.ReactNative
