### ISSUE TITLE
Rocket Chat - Enable Video Conference doesn't work on first login

### ISSUE THREAD

**Issue by VasylKonstantinov** [RocketChat/Rocket.Chat#22536]
### Description:
Enable Video Conference doesn't work on first login. The Save changes button remains dimmed. Once user changes other configurable parameters (e.g. enables the chat for specific rooms) the button becomes active. Once saved, the Enable/Disable toggle starts to work properly (trigger the Save Changes button availability)

### Steps to reproduce:
1) Open Administration Panel
2) For the first time, navigate to Video Conference
3) Expand the BigBlueButton list
4) Turn on the Enabled toggle

### Expected behavior:
Save Changes button becomes active

### Actual behavior:
Save Changes button remains dimmed.

### Server Setup Information:
- Version of Rocket.Chat Server: 3.12.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 30-60
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.18

### Client Setup Information
- Browser Version
- Mac OS

**Comment by debdutdeb** [comment]
Hey there! Thanks for reporting this !!
I see your RC version is 3.12.1. Just took a look at 3.16, and it seems to be working as expected :)
You're going to have to update your instances. Unfortunately no fixes are going to be back-ported to 3.12.1
Closing but please reopen if you see this resurface in the latest version.
