### ISSUE TITLE
RC Notification settings not saved once leaving the room

### ISSUE THREAD

**Issue by VasylKonstantinov** [RocketChat/Rocket.Chat#22537]
### Description:
In the web browser version of RC, when changing alert notification settings in a specific room, they fail to save once leaving the room (this is not an issue on the mobile apps

### Steps to reproduce:
Steps to reproduce:

Open RC in a desktop web browser
Go to any room notification settings
Unfold Desktop section
Change Alerts value to any other (e.g. default to Nothing)
Save changes
Swithc current chat room 
Return to initial chat room
Check Notification settings

### Expected behavior:
Desktop alerts keeps saved setting (e.g. Nothing)

### Actual behavior:
Desktop alerts remain the same as before changes (e.g. Default)

### Server Setup Information:
- Version of Rocket.Chat Server: 3.12.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 30-60
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.18
- 
### Client Setup Information
- Desktop App or Browser Version:
desktop web

**Comment by johncrisp** [comment]
Hi.

Again, please test on latest 3.16.1

If this still occurs please post back and we can re-open it.

Thanks.
