### ISSUE TITLE
[3.16.x] Cannot create a discussion from the top left sidebar as a user.

### ISSUE THREAD

**Issue by tmartincpp** [RocketChat/Rocket.Chat#22534]
### Description:

Since at least 3.16.0, it's impossible to create a discussion from the "Create new" icon on the top left sidebar as a user.
The channel/group list is seen as "Empty" so the "Create" button will stay greyed out. 

### Steps to reproduce:

1. Start a fresh install
2. Create an admin user and a normal user
3. As the admin, try to create a discussion from the top left sidebar, it will work (you will see the general channel in the channel list)
4. As a user, try to create a discussion from the top left sidebar, it will **not** work (the channel list will remains empty)

### Expected behavior:

A user should be able to create a discussion from the top left sidebar.

### Actual behavior:

A user can't create a discussion from the top left sidebar.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Debian Buster
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.1.1 or any browser (like chromium for example)
- Operating System: Debian Buster

### Additional context

Creating a discussion directly from the parent room is working, so the issue is probably in the RoomAutoComplete part I guess (which is related to /api/v1/rooms.autocomplete.channelAndPrivate AFAIK).

### Relevant logs:

There is an object (most likely the room list) return for the admin, not the user.

Admin logs:
```
I20210701-13:12:34.232(2)? API ➔ debug GET: /api/v1/rooms.autocomplete.channelAndPrivate?selector={%22name%22:%22%22}
I20210701-13:12:34.238(2)? API ➔ debug Success { statusCode: 200, body: { items: [ [Object] ], success: true } }
I20210701-13:12:34.274(2)? API ➔ debug GET: /api/v1/users.autocomplete?selector={%22term%22:%22%22}
I20210701-13:12:34.280(2)? API ➔ debug Success {
I20210701-13:12:34.280(2)?   statusCode: 200,
I20210701-13:12:34.280(2)?   body: { items: [ [Object], [Object], [Object] ], success: true }
I20210701-13:12:34.281(2)? }
```

User logs:
```
I20210701-13:11:39.711(2)? API ➔ debug GET: /api/v1/rooms.autocomplete.channelAndPrivate?selector={%22name%22:%22%22}
I20210701-13:11:39.720(2)? API ➔ debug Success { statusCode: 200, body: { items: [], success: true } }
I20210701-13:11:39.725(2)? API ➔ debug GET: /api/v1/users.autocomplete?selector={%22term%22:%22%22}
I20210701-13:11:39.730(2)? API ➔ debug Success {
I20210701-13:11:39.730(2)?   statusCode: 200,
I20210701-13:11:39.731(2)?   body: { items: [ [Object], [Object], [Object] ], success: true }
I20210701-13:11:39.731(2)? }
```

**Comment by debdutdeb** [comment]
Hi!! Thanks for reporting this :)

I've confirmed this to be a bug. Awesome contribution from your part ;)

We'll try to update the status when more info surfaces. TTYS!
