### ISSUE TITLE
Can't share image in RC on ios

### ISSUE THREAD

**Issue by VasylKonstantinov** [RocketChat/Rocket.Chat#22538]
### Steps to reproduce:
1. Launch SA on the browser in IOS
2. OPen RC chat 
3. Click on the share button
4. Choose any image from the library and share

### Expected behavior:
Image is shared in the chat

### Actual behavior:
Image not shown in the chat

### Server Setup Information:
- Version of Rocket.Chat Server: 3.12.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 30-60
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.18

### Client Setup Information
- Desktop App or Browser Version: Web
- Operating System: iOS

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

As we have previously advised, you are going to have to upgrade as 3.12.1 is not supported.

Please follow the issue reporting guidelines and test on the latest version.

Please test it thoroughly and if it persists on 3.16.x + the latest iOS app then look here:

https://github.com/RocketChat/Rocket.Chat.ReactNative
