### ISSUE TITLE
Porting to 1.3

### ISSUE THREAD

**Issue by dcsan** [RocketChat/Rocket.Chat#2254]
`meteor update --release 1.3-modules-beta.8 `

version 1.3 is meant to improve rebuild times (god, i hope so) so i quickly bumped the release to see.

1.3-modules-beta.8

however I got the error below.
I didn't see any other issues with 1.3, so created this one.

```
➜  Rocket.Chat git:(develop) ✗ meteor
[[[[[ ~/dev/rnd/Rocket.Chat ]]]]]             

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: No version of autoupdate satisfies all constraints: @=1.2.4, @=1.2.5-modules.8
   Constraints on package "autoupdate":
   * autoupdate@=1.2.4 <- top level
   * autoupdate@=1.2.5-modules.8 <- top level
   * autoupdate@1.2.5-modules.8 <- hot-code-push 1.0.1-modules.8 <- meteor-base 1.0.1
   
=> Your application has errors. Waiting for file change.
```

refs
https://github.com/meteor/meteor/issues/6252
https://github.com/meteor/meteor/issues/5788

**Comment by dcsan** [comment]
FWIW `METEOR@1.2.2-faster-rebuilds.0` seems to be working, and allegedly that has some of the reload optimizations. 

however, any code edit for me on rocket.chat takes a good 30 secs or more to reload.
combined with the lack of ability to write tests with meteor, its pretty tedious.

does anyone have tips to get faster rebuilds?

**Comment by engelgabriel** [comment]
I don't remember why, but we had to change something on the autoupdate package. The quick way was to copy it to our packages folder. @rodrigok should we PR back our changes to MDG so we can delete the folder and use the standard package to avoid this version dependency problems?

**Comment by rodrigok** [comment]
@engelgabriel no, we disabled the autoupdate (almost).

**Comment by engelgabriel** [comment]
can we remove the package completely in that case? or rename the one we are using to  `rocketchat: autoupdate` ?

**Comment by rodrigok** [comment]
Note the **almost** in may answer.

**can we remove the package completely in that case?**
No, we use part of the functionality. And there is no way to remove that package.

**or rename the one we are using to rocketchat: autoupdate ?**
There is no way to remove the original package and we need to disable part of the code.

**Comment by engelgabriel** [comment]
Is this useful? https://github.com/meteor/meteor/issues/3759#issuecomment-85700555

**Comment by engelgabriel** [comment]
> You can also remove the `autoupdate` package from your app by removing the meteor-platform dependency and replacing it with the contents of meteor-platform other than `autoupdate`.

**Comment by rodrigok** [comment]
@engelgabriel no.

We do not use the default method to update apps, but we use the default code to notify our Cordova app to init the update.

**Comment by chang9e** [comment]
Please upgrade as soon as possible to meteor 1.3

**Comment by corecache** [comment]
Waiting for 1.3 with for CAS 2.0 support as described in #2325

**Comment by laomouzi** [comment]
Any plan to upgrade to Meteor 1.3? Thanks!

**Comment by Nodraak** [comment]
Hey,

It's been 1 month without activity here, what's the status ?
I would love to have CAS 2.0 working and this issue is required apparently.

I hope to see this issue closed soon and in the meantime thank you a lot guys for your work :)

**Comment by tab00** [comment]
Meteor 1.4 will be released soon: [Coming soon: Meteor 1.4](https://forums.meteor.com/t/coming-soon-meteor-1-4/23260/1)

**Comment by laomouzi** [comment]
Hi @engelgabriel or anyone else: 
Anyone know about the current status of porting to Meteor 1.3 or higher version?
Need the upgrade badly. Thanks for everyone!

**Comment by rodrigok** [comment]
Hu guys, we will not update to Meteor 1.3 cuz we have more important issues to solve and the version 1.3 don't have any great improvements for us.

We will port to Meteor 1.4 ASAP after the final release cuz we need features from Node 4.

Now I am working to improve the performance and my next big issue will be the Meteor version upgrade to 1.4 😄

**Comment by laomouzi** [comment]
Meteor 1.4 is officially out:
http://info.meteor.com/blog/announcing-meteor-1.4
Was wondering if it's safe to port RC to meteor 1.4 now? Any update on the status?
Thanks a lot @rodrigok

**Comment by corecache** [comment]
I've started using meteor 1.4.0.1 over the last weeks and noticed that there is sitll some general dicussion going on in the meteor community about the direction Meteor is taking (mdg, apollo, blaze)

**Comment by dcsan** [comment]
@corecache does 1.4 speed up the build times noticably? until that's solved it seems meteor is a dead duck for any project the size of RC.

**Comment by rodrigok** [comment]
@laomouzi We will do the migration to meteor 1.4 ASAP, this will be my next big issue. We are just organizing some things before, so you can expect some news about this by the end of this month.

@dcsan I don't know, but the last update did speed up my build a little.

**Comment by serut** [comment]
Yes the build is a little bit faster. 
If you plan to write some tests, move to Mocha and spacejam and you will be able to get the coverage report too.

**Comment by laomouzi** [comment]
@rodrigok Looking forward to the migration. Thanks!

**Comment by toupeira** [comment]
Please make sure you mention the required/compatible NodeJS versions in the release announcement and installation instructions. The Meteor guys seem to do a terrible job at this, e.g. [this old issue](https://github.com/meteor/meteor/issues/5124) is still open, and the only place where I could find this information was [hidden in their deployment guide](https://guide.meteor.com/deployment.html):

> - Node 4.4.7 for Meteor 1.4.x
> - Node 0.10.43 for Meteor 1.3.x and earlier

This might also be a good opportunity to bump the version to 1.0? :)

**Comment by laomouzi** [comment]
Hi guys, is there any update on this front? Can't wait to see how the migration fixes the issues and improves things. @dcsan @rodrigok @engelgabriel
