### ISSUE TITLE
Unable to create personal access token even when permisson ist set

### ISSUE THREAD

**Issue by strike65** [RocketChat/Rocket.Chat#22549]
### Description:
Even when permission is granted to create personal access tokens the user is unable to create a token. The button "Add" is greyed out.
Moreover - Already created tokens are not visible (message: no data found).

### Steps to reproduce:

My Account -> Security -> Personal Access Token 

### Expected behavior:

The button should be accessible.

### Actual behavior:

The button is greyed out.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Linux
- Deployment Method: managed/unknown
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.21.0
- MongoDB Version:4.0.25 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.2.2, Browser: latest Chrome
- Operating System: macOS, Windows

**Comment by debdutdeb** [comment]
Hi, thanks for reporting this! Also thanks for filling out the bug template, extremely helpful :D 👍🏼 

In the latest version, 3.16 this seems to be working as expected. So first thing for you to do, is update to the latest. 

Further, if you still see the issue lingering, please make sure the user who's trying to create his/her PAT, is in the role that has `create-personal-access-tokens` permission enabled. IIRC, default created users don't belong to any roles. 

Note that the "Add" button will stay greyed out until a name's been given to the PAT.

I will leave the issue open for now. Again, please test on the latest and let us know. We'll help you however we can :highfive:

Thank you!!!

**Comment by strike65** [comment]
Thanks. Because I am not able to update the server (it is a third party server), this will not help. Nevertheless, the problem ist solved. Thanks anyway!
