### ISSUE TITLE
There is no stretch option when discussing strings

### ISSUE THREAD

**Issue by hanzhiyan588** [RocketChat/Rocket.Chat#22548]
### Description:

Most users don't have this stretch option when discussing strings
![image](https://user-images.githubusercontent.com/63633319/124223961-5aeb8200-db37-11eb-8775-522d840b53c8.png)
![image](https://user-images.githubusercontent.com/63633319/124224009-748cc980-db37-11eb-913e-4edf2ed6d2e9.png)

### Expected behavior:

Every user should have this stretch option

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.0
- Operating System: Ubuntu 20.04
- Deployment Method: Docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Chrome 90.0.4430.212 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04

**Comment by debdutdeb** [comment]
Hi there, another issue? ;) Awesome, thank you !!

I'm happy to see you filling up the bug template, but unfortunately we're going to need a bit more information. Specifically about the clients of the users who aren't seeing the "Expand" button.

Please update the issue with the information I just mentioned and let us know with a comment.

TTYL :)

**Comment by hanzhiyan588** [comment]
> 你好，还有一个问题？;） 太棒了，谢谢你 ！！
> 
> 我很高兴看到您填写错误模板，但不幸的是，我们需要更多信息。特别是关于没有看到“展开”按钮的用户的客户。
> 
> 请使用我刚才提到的信息更新问题，并通过评论告诉我们。
> 
> 下次再谈 ：）
Sorry, the buttons are the key. Only one or two people have it, not all of them

**Comment by inetfuture** [comment]
> Specifically about the clients of the users who aren't seeing the "Expand" button.

We can't find any patterns, some clients just don't see the button. We've tried upgrading chrome to the latest, clearing cache, no luck.

**Comment by inetfuture** [comment]
@debdutdeb

**Comment by yash-rajpal** [comment]
The Stretch button is only visible to those users whose display resolution is low, or if the website is zoomed in.

To confirm this, you can try to zoom in the website and the stretch button will be visible to you. To confirm this - 
![Stretch_Button](https://user-images.githubusercontent.com/58601732/125167403-e57a5400-e1bd-11eb-9ae8-f3411e8066af.gif)

We can make a setting for this in admin panel, if the stretch or expand button should be shown to every user or not. I can open up a PR for this if any Rocket Chat team member can tell if this is needed or not and where should the setting for this reside?

**Comment by yash-rajpal** [comment]
@debdutdeb The Stretch button is only visible to those users whose display resolution is low, or if the website is zoomed in.

To confirm this, you can try to zoom in the website and the stretch button will be visible to you. To confirm this -
![stretch](https://user-images.githubusercontent.com/58601732/125167492-78b38980-e1be-11eb-9968-522b488bba73.gif)

We can make a setting for this in admin panel, if the stretch or expand button should be shown to every user or not. I can open up a PR for this if any Rocket Chat team member can tell if this is needed or not and where should the setting for this reside?

**Comment by inetfuture** [comment]
I see, thanks for the explanation.

> We can make a setting for this in admin panel, if the stretch or expand button should be shown to every user or not

I think this would be great.

**Comment by yash-rajpal** [comment]
@inetfuture Waiting for any Rocket.Chat team member to confirm if this is needed.

**Comment by johncrisp** [comment]
Hi Yash,

Please note that work on Rocket.Chat is decided by the Product Team rather than individual developers.

I will raise this with them and ask them for their comments before you start any work.

Thanks.

**Comment by yash-rajpal** [comment]
Thanks @johncrisp 

Yes, I understand how these things works, that's why wanted a confirmation by any team member before raising the pull request.

**Comment by johncrisp** [comment]
I have raised it with them Yash - we'll await a response.

You don't need to @ people thanks!

**Comment by kugel-** [comment]
From my experience the expand button is always shown when the browser is not maximized? In firefox, I can make the expand button show just by un-maximizing and manually enlarging the browser window using the mouse.

Please show this button always! I don't understand why I can't have larger sub-threads just because the window is maximized.

**Comment by pauschuu** [comment]
>  I don't understand why I can't have larger sub-threads just because the window is maximized.

And also, why is even the larger version of the thread display so limited? As developers, we often use the chat to share code snippets, which are hardly readable because of the word wrapping. Many people would like to be able to display a thread in "full width". :)
