### ISSUE TITLE
Video call button missing in multi-user direct chats

### ISSUE THREAD

**Issue by bognerf** [RocketChat/Rocket.Chat#22552]
### Description:

Since upgrading to 3.16.1 the button for video calls is missing in multi-user direct chats. In 3.15.0 the button was still there.

### Steps to reproduce:

1. In RocketChat Electron client or web access go to an existing multi-user direct chat or create a new one. 
2. Try to start a video call. The button to do so is missing.

### Expected behavior:

A video call button would appear in the top menu of a multi-user direct chat.

### Actual behavior:

No video call button to be found.

![adama_067](https://user-images.githubusercontent.com/1632531/124259311-a9e0e980-db2e-11eb-9054-00fa09b74316.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Ubuntu 18.04
- Deployment Method: Tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.25

### Client Setup Information

- Desktop App or Browser Version: Desktop App v2 and latest v3; Firefox & Chromium latest
- Operating System: Windows and Linux

**Comment by emikolajczak** [comment]
Hi, I can confirm this. In 3.14 call button is available in multi DM room.

**Comment by prathamjagga** [comment]
I'm working on the issue. But can you tell how to setup the rocket.chat on my local

**Comment by johncrisp** [comment]
> I'm working on the issue. But can you tell how to setup the rocket.chat on my local

Hi.

Thank you for your offer to assist but note that this is not a support channel. 

Please ask for support in https://forums.rocket.chat or https://open.rocket/chat #support - you will need an in depth understanding of Rocket Chat before you can start to try and fix issues.

This bug has been raised with Product Management and will be looked at by the development team.

**Comment by johncrisp** [comment]
FYI this is on the current sprint 13-26 July

**Comment by lijicheng168** [comment]
After testing, I found that the call icon still exists during the local installation, but when it is started in docker mode, the call icon is gone. Is it because I configured it incorrectly or a certain environment variable of docker was not passed into the app correctly?
