### ISSUE TITLE
How to move rocket.chat data from server with manual installation to server with rocket.chat running in docker?

### ISSUE THREAD

**Issue by seppel161** [RocketChat/Rocket.Chat#22560]
I am trying to move data from an existing server, where I installed rocket.chat following the [guide](https://docs.rocket.chat/installing-and-updating/manual-installation/ubuntu) for manual installation, to a new server, where I installed mongodb and rocket.chat in docker. I'm having trouble importing the data on the new server.
Both servers are running Rocket.Chat 3.16.1, but I couldn't get mongodb 4.4.3 running with docker, to match the version of the mongodb-version on the old one. So I'm currently sticking to version 4.0 from to the [example file](https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml) for the `docker-compose.yml` file. I'm not sure if this could cause any trouble.

My steps are:
1. `mongodump --username USER --password PASSWORD --archive=backup` on the old server. 
Works fine, in my point of view. Returns a directory containig 'admin'-directory, 'rocketchat'-directory and 'archive'-file.
3. `tar cvf backup.tar backup` on the old server
4. Copy `.tar`-file from old to new server.
5. `tar xvf backup.tar` on the new server.
6. `docker exec -i CONTAINER_NAME sh -c 'mongorestore --archive' < backup`
Returns error: `Failed: I/O failure reading beginning of archive: EOF`
I was inspired for this step by this [blog entry](https://jeromejaglale.com/doc/programming/mongodb_docker_mongodump_mongorestore)
The docker container is running succesfully. I stopped the rocket.chat-container, which was running before.

If anyone has any clue for me, how to get the migration done, I'd be really thankfull!

**Comment by johncrisp** [comment]
Hi,

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

This repo is reserved for issues in Rocket.Chat

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat
