### ISSUE TITLE
Why is necessary to request a token to omnichannel feature?

### ISSUE THREAD

**Issue by arthurfigueiredo** [RocketChat/Rocket.Chat#22574]
Do you believe this doesn't go against the opensource philosophy? Because a feature depends on a request for the company that maintains the project, so I can't use community-maintained resources in a standalone way.

Do requests for this endpoint pass through the rocketchat servers? what guarantees do we have that the data is not used by the company?

**Comment by johncrisp** [comment]
Hi and thanks for opening this issue.

Can you please make sure you fill out the bug template with all your server details? We can't tell much otherwise.

Can you also describe more accurately what you are trying to do, and what your concern is?

Please note that github is really for errors in the code.

If you want to ask general questions on open source then you can do so on the forums or https://open.rocket.chat

 I'll leave this open for now pending your response.

**Comment by arthurfigueiredo** [comment]
I want to host rocketchat on my server and use the community-maintained omnichanel features. But these features depend on the token provided by Rocket, so I have the doubts I put at the beginning of this thread.

As to what guarantees there are about my data trafficked through this token.

**Comment by johncrisp** [comment]
> I want to host rocketchat on my server and use the community-maintained omnichanel features. But these features depend on the token provided by Rocket, so I have the doubts I put at the beginning of this thread.

First, please fill out a template as requested.

Next. exactly which token are we talking about?

**Comment by arthurfigueiredo** [comment]
This is more a question about the security of the data that pass through your Omnichannel API Key and about the rocketchat policy of requiring this token to use resources that are maintained by the community.

I'm talking about the token of this tutorial https://docs.rocket.chat/guides/omnichannel-guides/omnichannel-admins-guide Omnichannel API Key

This issue is not a bug, release or security report, so I cannot use the templates you have today 😞

**Comment by arthurfigueiredo** [comment]
> If your organization wishes to communicate with users of Facebook, you can enable integration within Rocket.Chat to do so.
First, you will need to request an API key from Rocket.Chat Support then set it up within your Administration area.
Send an email to omni@rocket.chat to request an API key. These are processed as time allows, and may take a few days, but you should have your key and secret soon enough.
Enable Facebook integration
Enter your OmniChannel API Key 
Enter OmniChannel API Secret. Save the changes

**Comment by johncrisp** [comment]
> This issue is not a bug, release or security report, so I cannot use the templates you have today

So as Rocket.Chat is not 'broken' this is a question really for the forums or open.rocket.chat then, as per the guide.

> Omnichannel API Key

This is a tricky thing about open source. The code is there for you to inspect, check, read, and you can do whatever you want with it.

You have a choice as to whether to use it (compiled by Rocket), or not use it and develop your own version (you can't actually use the EE parts without a licence but you can still read the code).

Open source does not guarantee you anything. Just that you are free to use the code.

If you use the Rocket.Chat app then I believe currently we have to add a key for our app. I also think that IIRC there is a new app being developed that might not require this - it is not easy for us to administer currently!

One thing to think about in all this is Facebook itself. One of the biggest data gatherers online. They are by far and away the largest beneficiaries of any connection!!

If you really value your privacy, don't use them, at all!!

I will close this as notabug - if you wish to continue to discuss this please find me on https://open.rocket.chat - I am trying to find out what sort of data, if any, we collect.
