### ISSUE TITLE
Live Chat: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by jansass** [RocketChat/Rocket.Chat#2258]
When used over SSL, i always receive an error: 

Error during WebSocket handshake: Unexpected response code: 400

I've followed the guidelines here: https://github.com/RocketChat/Rocket.Chat/wiki/Run-Rocket.Chat-behind-a-SSL-Reverse-Proxy#running-behind-an-apache-ssl-reverse-proxy but it didnt change anything. I've rechecked the whole setup, but still: im stuck. I can not get Live Chat to talk to me..

Any suggestions highly appreciated!
Jan

**Comment by jansass** [comment]
Push up: Any ideas?

**Comment by sampaiodiego** [comment]
what is the URI of the request you're getting: `Error during WebSocket handshake: Unexpected response code: 400` ?
is it only the livechat stuff not working?
when did you get that error?
what steps are you doing?
what is the version of your rocket.chat?

**Comment by jansass** [comment]
Sampaiodiego:
Yes, the "internal chat" is working perfectly
Here is my testdrive: https://www.jansass.com/chat.html
Installed RS, added agent, put snippet to page
Version: 1.18.0

Reproduction: Open testdrive; see browser console for error code. When you type something into the chat window, an orange alert box opens w/o any text; the text lines are striked; the content does not reach the operator

**Comment by sampaiodiego** [comment]
I got an error text on the orange alert box:
![image](https://cloud.githubusercontent.com/assets/8591547/13217859/51519874-d944-11e5-83f1-c1e2b36f2282.png)

seems that you have no agents configured.. you have to go to `Livechat > Users` and add some agents. look at [this page](https://github.com/RocketChat/Rocket.Chat/wiki/%5BWIP%5D-How-to-use-Livechat-package) .. it's under development but already have some useful information.

about the websocket error.. seems that you have not configured ROOT_URL (Site Url) properly.. you have to set it to `https://chat.jansass.com` on the admin.

**Comment by jansass** [comment]
Sorry, i was not logged in. While i was *not* logged in, i tried myelf:

Chrom Mac:



= no error message

Firefox Mac:


No notice what so ever

Then i logged in :
(correct https in advance)

Chrome Mac:


Still no message (none received in operator chat)



No error message, BUT i received it as an operator. So i can narrow it down:

*Problem in Chrome Mac: No communication at all
*Problem in Firefox Mac: Communication works, but offline status is not displayed

Both:
WebSocket connection to 'wss://chat.jansass.com/sockjs/096/_sme___b/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
livechat.js:5 Exception in delivering result of invoking 'loadHistory': TypeError: Cannot read property 'length' of undefined
    at https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:159:728
    at null._callback (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:5:6834)
    at i.extend._maybeInvokeCallback (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:52:8277)
    at i.extend.receiveResult (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:52:8585)
    at i.extend._livedata_result (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:52:19863)
    at o (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:52:6563)
    at https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:52:567
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:3:865)
    at t.socket.onmessage (https://chat.jansass.com/packages/rocketchat_livechat/public/livechat.js?_dc=ca43de5fc31e6a82193d4d168457db47fac0ae5d:52:525)


*Errormessage  …still exist (although i’ve changed it to https in the backend; which i tried before).

So i continued investigation using parallels 10,

Parallels Win 10, Chrome: Agent logged in: Chat is getting through; Agent not logged in: No offline message*
Parallels Win 10, Firefox: Agent logged in: Chat is getting through; Agent not logged in: No offline message*
Parallels Win 10, IE: Agent logged in: Chat is getting through; Agent not logged in: Offline message works perfectly

*offline messages are coming in after i log in agent (so its a delayed delivery)

Additionally, i observed this:

i was logged out, tested IE, got the „is offline“ message, then logged as operator, and retried in IE: orange box: Internal server error. (all using different browsers and computers). The same with Firefox/Chrome: orange box without text. Now i log out as Agent, and log back in: sometimes the messages are delivered delayed, sometimes not, i no case an „offline message“ appeared.

In backend i have deleted all chats and all Guest-Users, and now all windows are showing error-messages (orange box, not text, or orange box : Internal server error“)





So i think im not allowed to delete chats? And guest-users ?

What can i do to send better data for analysis?

Jan





  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by sampaiodiego** [comment]
hmm. there is a bug when you delete guest users. =\

still, the websocket error seems that your nginx are not configured properly since I get the error even on the backend.

when meteor is not able to connect using websocket it fallsback to XHR requests. I'll test if livechat works well without websockets on a previously working scenario.

**Comment by jansass** [comment]
Ok, what can i do when im behind apache 2 ? (not nginx). Plus: i hereby declare not to delete any visitor in future. Deleting visitors is bad anyhow :)

j

  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by sampaiodiego** [comment]
I've never used Apache as a reverse proxy.. but I found some links that can help you:
http://stackoverflow.com/questions/22002744/how-to-set-up-an-apache-proxy-for-meteor-sockjs-and-websocket
https://github.com/meteor/meteor/issues/3339

**Comment by jansass** [comment]
Alright, will check that config; but i think i’ve tried before (throwing error 500 all the way) BUT: that wont Rocket chat prevent from working; since there is (obviously and state by you and others) a fall back, right?

What can i do to reset the user-database?
  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by sampaiodiego** [comment]
yes, you should be able to use rocket.chat withou websocket connection.

you can run this commands on your database in order to _reset livechat data_ (I'm sorry about that.. that's an issue I wish fix soon):
```
db['rocketchat_subscription'].remove({t:'l'});
db['rocketchat_room'].remove({t:'l'});
db['users'].remove({'profile.token':{$exists:true}});
```

**Comment by jansass** [comment]
alright, will do that. What about the other behaviour (empty error messages), not showing offline, .. ?
  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by sampaiodiego** [comment]
could be related to XHR fallback or browser rendering.
I'll test both scenarios :wink:

**Comment by jansass** [comment]
Is there anything i can assist you with ?

Jan

  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by jansass** [comment]
Awesome, that hack works and was very easy to implement: The errormessage is gone!
  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by jansass** [comment]
Hmm, sorry to bother you, but do you have a short primer on Mongo-DB? What tool do i need to administer it? im experienced in sql, but not mdb..

j

  

Mit freundlichen Grüßen
Jan Sass
--
 

jansass GmbH
Lemsahler Dorfstraße 4  
22397 Hamburg / Deutschland

Telefon	 	+49 40 300 36 844
Telefax	 	+49 40 300 36 845
Skype	 	jansass.gmbh <skype:echo123?call>
E-Mail	 	info@jansass.com <mailto:info@jansass.com>
 	 	 
	 	Google Adwords certified professional.
jansass GmbH, Agentur für Kommunikationsdesign, ist eine inhabergeführte GmbH mit Sitz in Hamburg. Handelsregister Hamburg HRB 103087. EORI DE408828833794344. Ust-ID DE 257031322. jansass (TM) ist ein eingetragenes Warenzeichen. Für Geschäftskorrespondenz gelten die allgemeinen Geschäftsbedingungen. Geschäftsführer Jan Sass.
--

**Comment by sampaiodiego** [comment]
can you ping me when you have an online agent?
I saw you've fixed the websocket error.
Everything seems ok now, so please ping me (maybe at https://demo.rocket.chat/direct/diego.sampaio) so I can help you to track the error.

about mongodb, I'm using [Robomongo](https://robomongo.org/) as GUI (I'm on Linux) and their own CLI tools to manage import/export and other admin stuff.. I also need to check at https://docs.mongodb.org/manual/ a lot :smile:

**Comment by jansass** [comment]
The agent was never offline since today, 8hrs ago (our first contact today). BUT: you can not see it in front end - THATS part of the problem a face (i've deleted the guest visitors by hand in RS backend). Give me some time to enter the mongo db stuff so the user management is resetted (or is there any other way to do that?)

**Comment by sampaiodiego** [comment]
oh, I'm sorry, I thought you already had executed the mongodb commands.
but you _have_ to be *online* (not busy or away) to receive livechats, ok?

**Comment by jansass** [comment]
Ok, that should be that hard.. Did that, but:

 db['rocketchat_subscription'].remove({t:'l'});
WriteResult({ "nRemoved" : 0 })
 db['rocketchat_room'].remove({t:'l'});
WriteResult({ "nRemoved" : 0 })
 db['users'].remove({'profile.token':{$exists:true}});
WriteResult({ "nRemoved" : 0 })

..does not look successful i believe. Im sure im hooked to the correct DB (localhost:27017) so ... im stuck. damn. my kungfu is not powerful at mongo db.

**Comment by jansass** [comment]
And yes: i am online. The mac os x app is opened and the computer was in use all day

**Comment by sampaiodiego** [comment]
haha.. you have to connect into `rocketchat` database:
`use rocketchat`

**Comment by jansass** [comment]
Awesome - its working! Thank you very much - i hope we will stay in touch for further enhancement of the brilliant software!

**Comment by jansass** [comment]
I've sent an email to gabriel along with the briefly discussed to-dos i see, alright?

**Comment by sampaiodiego** [comment]
ok @jansass .. he'll reply as soon as he can.. bests
