### ISSUE TITLE
Rocket Chat display mangled, iOS Big Sur, Safari 14.0.3

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#22596]
### Description:

Rocket Chat view is mangled on login

### Steps to reproduce:

1. Login to app in web browser

### Expected behavior:

it works

### Actual behavior:

it doesn't

<img width="1394" alt="Screen-Shot-2021-07-07-at-3 32 44-pm" src="https://user-images.githubusercontent.com/1122344/124711458-72fd4000-df41-11eb-862e-c0d2902ea714.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Ubuntu 18 LTS
- Deployment Method:  TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: True
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25 / mmapv1

### Client Setup Information

- Desktop App or Browser Version: Safari 14.0.3
- Operating System: iOS Big Sur

### Additional context

None

### Relevant logs:

None

**Comment by johncrisp** [comment]
So this link refers:

https://open.rocket.chat/channel/support?msg=X7hnSmwf75MaG6zPn

You had posted a link to a similar issue on 3.15.x 

https://open.rocket.chat/channel/support?msg=53gmkrFjdodXsQWQf

However, I believe that was on Firefox.

As per the thread I have tested this on a MacBook Pro Big Sur 11.4 with Safari 14.1.1 (16611.2.71.4) and it displays no issues at all.

So two things to ask you to do.

First is to check your OS and browser versions to make sure you are on the latest and then test again.

If you still have issues then enable the developer menu and start looking for any errors.

To test on the latest version of Rocket.Chat use open.rocket.chat as that is usually using the latest development code.
