### ISSUE TITLE
allow email notifications to be encrypted

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#2260]
Since the email notifications contain a snippet of the conversation, and thus may contain sensitive information, it would be nice to be able to have the email notifications gpg encrypted with the users public key if available.

**Comment by Johann-Snapp** [comment]
+1

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
