### ISSUE TITLE
Search not list only 'real_name'

### ISSUE THREAD

**Issue by dsisysteme** [RocketChat/Rocket.Chat#22602]
### Description:

When we use search menu , the result list is not only with 'real_name' but with a mix of 'real_name' and 'username'. The option use real_name is enable . We use an LDAP to sync user and so we view a mix of name and ID in the result of search.

### Steps to reproduce:

1. Click on 'Search' icon
2. Search a user with real_name (name)
3. Result of search is a list with real_name for members already join, and username (not real_name!) for member not already join.

### Expected behavior:

Result of search is a list with only real_name for all members.

### Actual behavior:

Result of search is a list with real_name for members already join, and username (not real_name!) for member not already join.
![image](https://user-images.githubusercontent.com/72081136/124743124-b2199a00-df1d-11eb-9ddf-13879963eda7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.2
- Operating System: Linux debian buster
- Deployment Method: tar
- Number of Running Instances:  3
- DB Replicaset Oplog: 1
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.10

### Client Setup Information

- Desktop App or Browser Version: Chrome / Firefox / Desktop app
- Operating System: Debian10

**Comment by emikolajczak** [comment]
Also reported here:
https://github.com/RocketChat/Rocket.Chat/issues/22164
https://github.com/RocketChat/Rocket.Chat/issues/21849

**Comment by tammer123** [comment]
Still happening in 3.16.3.

**Comment by jzabroski** [comment]
Jesus Christ.  How is this not an urgent security issue

**Comment by Rhuancpq** [comment]
Working on it...

**Comment by dudanogueira** [comment]
This one was fixed in https://github.com/RocketChat/Rocket.Chat/pull/25471

We really appreciate the time you took into exploring and pointing the issue 🙌🏼
