### ISSUE TITLE
Missing Call symbol in direct messages with more than 2 participiants

### ISSUE THREAD

**Issue by sa0win** [RocketChat/Rocket.Chat#22624]
### Description:

After update to new server version 3.16.1 the call symbol in direct messages with more than two participiants is currently missing. Instead of the call symbol the members symbol like in teams is shown.

### Steps to reproduce:

1. Create a direct message with more than 2 participiants in Rocket.Chat App (Windows Electron)

### Expected behavior:
Call symbol is visible an videocalls can be started 

Example:
![image](https://user-images.githubusercontent.com/58232116/125028311-18bac700-e088-11eb-9554-5e8a2f723980.png)

### Actual behavior:
Call symbol ist missing:

Example:
![image](https://user-images.githubusercontent.com/58232116/125028444-51f33700-e088-11eb-8552-d15d3bb0028c.png)

Additional information: The example shows not a team!

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Ubuntu 20.04
- Deployment Method: manual installation
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.19.0
- MongoDB Version: 4.2.14 / wiredTiger (oplog Aktiviert)

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10

### Additional context
Missing symbol since update to Rocket.Chat Server 3.16.1

**Comment by johncrisp** [comment]
I think this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22552

If so can you please close it in favour of that Issue. Thanks.

**Comment by sa0win** [comment]
Same bug. Thx for fast reply :-)
