### ISSUE TITLE
TabBar plugins

### ISSUE THREAD

**Issue by jonbaer** [RocketChat/Rocket.Chat#2263]
Hi,

I am trying to figure out how to setup 2 "external" items I need for users and would like to use the TabBar to display them (per user/channel), the main question I have is that it seems to be that you would create a package using a setting / RocketChat.TabBar.addButton / RocketChat.TabBar.removeButton but it would also be great if these were setup as "plugins" in a streamlined way.  

Just wondering if there was any thought to this or should I just go about it like the way the other packages are basically set up.  Both are easy but I guess if I wanted to distribute this to another chat project I should just install it as a Meteor package?

**Comment by marceloschmidt** [comment]
Yes, that's how we've been building plugins so far. I can see how we could totally benefit from plugins being regular meteor packages, but so far, there's nothing planned going that direction. I'll leave this issue open as a discussion on how to implement a new plugin system.

**Comment by graywolf336** [comment]
Closing in favor of #6890. Please watch that issue for future details about "plugins" or the term which has been coined of "Rocketlets".
