### ISSUE TITLE
Send this department's Livechat offline messages to a channel doesnt load channels

### ISSUE THREAD

**Issue by LifeIsAParadox** [RocketChat/Rocket.Chat#22642]
### Description:

The  option in omnichannel for offline channel does not load all channels. We only see 10 channels but we have more then 10 channels.

### Steps to reproduce:
1. go to omnichannel settings
2. click on department
3. create or edit a department
4. click on "Send this department's Livechat offline messages to a channel" and you only see 10 channels

### Expected behavior:

to see all channels or if i search for a channel to load the channel name

### Actual behavior:

we only see 10 channels and it not load any if we search for a specific one

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog:  
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: firefox 90
- Operating System: windows

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

First can you please follow our Issue reporting guidelines and test on the latest available version please. 3.16.2 is current, or preferably on 'develop'

https://rocket.chat/docs/contributing/reporting-issues

I would also recommend you upgrade your current install to the lastest point release as well..... please see the release notes.

**Comment by LifeIsAParadox** [comment]
I dont have this bug any longer after updating to the latest version.
