### ISSUE TITLE
Live Chat Appearance

### ISSUE THREAD

**Issue by ushioTora** [RocketChat/Rocket.Chat#22649]
### Steps to reproduce:

1. Go to website 
2. Click the live chat logo 

### Expected behavior:

I expect like this 
![image](https://user-images.githubusercontent.com/13395611/125403903-a0863580-e3e8-11eb-84ed-76e3a0e0dc2b.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/13395611/125403811-86e4ee00-e3e8-11eb-82a2-515ce5d74ee7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Rocky Linux
- Deployment Method: Snap
- Number of Running Instances:1 
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version: Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
- Operating System: Windows 10

### Relevant logs:

I found this logs
![image](https://user-images.githubusercontent.com/13395611/125413225-42015d5e-79ed-4ba2-8d7a-469d6e730b71.png)

**Comment by johncrisp** [comment]
Hi.

This appears to be a setup/support issue and not a bug. (You should not be using localhost)

Please ask in https://forums.rocket.chat/ or https://open.rocket.chat/channel/support

You will need to include your webserver/proxy information as well.
