### ISSUE TITLE
Missing Close Button in Create Discussion Modal

### ISSUE THREAD

**Issue by AmirAsghary** [RocketChat/Rocket.Chat#22641]
### Description:

The Create Discussion Modal does not have a clear way to exit from it. Other similar modals usually have a "Cancel" or "Close" button in the modal's footer. So when the user opens a create discussion modal, they cannot close it without creating a new discussion.

### Steps to reproduce:

1. Go to the sidebar's header
2. Click on the "Create New" button
3. Click on "Discussion"

### Expected behavior:

Showing a "Close" or a "Cancel" button in the footer so if the user decides to not create a discussion, they can click on it and close the modal.

### Actual behavior:

There is no "Close" or "Cancel" button. so the user gets stuck on the create discussion modal.
<a href="https://ibb.co/fv5KBxh" target="_blank"><img src="https://i.ibb.co/fv5KBxh/Untitled.png" alt="Untitled" border="0"></a>

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.2
- Operating System: Ubuntu 21.04
- Deployment Method: Manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25

### Client Setup Information

- Desktop App or Browser Version: Desktop App v3.2.2
- Operating System: Windows 10 Pro Build 19042

### Additional context

I did take a look into the [Create Discussion Source Code](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/components/CreateDiscussion/CreateDiscussion.tsx) and In the last component "Modal.Footer" there exists only one button for discussion creation:
```
			<Modal.Footer>
				<ButtonGroup align='end'>
					<Button primary disabled={!canCreate} onClick={create}>
						{t('Create')}
					</Button>
				</ButtonGroup>
			</Modal.Footer>
```

which should be more like this (Copied from [this](https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/client/views/teams/CreateTeamModal/CreateTeamModal.tsx)): 
```
			<Modal.Footer>
				<ButtonGroup align='end'>
                                        <Button onClick={onClose}>{t('Cancel')}</Button>
					<Button primary disabled={!canCreate} onClick={create}>
						{t('Create')}
					</Button>
				</ButtonGroup>
			</Modal.Footer>
```

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

I'll raise it with the Product team.

**Comment by johncrisp** [comment]
Ahh I can see that in Create Channel you have Cancel.

Inconsistent with Discussions which only have the 'X' upper right.

**Comment by Vishal999code** [comment]
I would like to contribute to this and make the cancel button...can you please tell how to proceed

**Comment by johncrisp** [comment]
Hi,

as a follow up this is now on the Product Road-map to be fixed in the next sprint cycle.

I don't think it will make 3.17 but should be in 3.18

Many thanks for picking this up and helping to make Rocket.Chat better!

Vishal, thanks for the offer but the fix is in hand.

**Comment by ostjen** [comment]
The fix just was merged into develop, thanks @Vishal999code :grinning:

**Comment by AmirAsghary** [comment]
@ostjen Has it been released yet?
