### ISSUE TITLE
email notification settings on a per-channel basis

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#2264]
Allow users to decide per channel if they want to receive email notifications

**Comment by sampaiodiego** [comment]
should channel configuration override global preferece?
I mean if I choose to not receive emails at `My Preferences` but choose to receive on every message in the channel '#general`, what should I do?

**Comment by sinteur** [comment]
Yes - the you should receive for that channel.

Same the other way around, if you have set to receive email at My Prefs, but want to silence one channel, just set that to none in the channel

**Comment by sampaiodiego** [comment]
So, I'm working with this sheet:

Account Setting | Channel Setting | Message Type | Action
------- | ------- | ------- | ---
Receive | All messages | mention to @me | SEND
Receive | All messages | any message | SEND
Receive | All messages | with highlight | SEND
Receive | All messages | direct message | SEND
Receive | Mentions | mention to @me | SEND
Receive | Mentions | any message | DON'T
Receive | Mentions | with highlight | DON'T
Receive | Mentions | direct message | SEND
Receive | Nothing | mention to @me | DON'T
Receive | Nothing | any message | DON'T
Receive | Nothing | with highlight | DON'T
Receive | Nothing | direct message | DON'T
Receive | Respect Account | mention to @me | SEND
Receive | Respect Account | any message | DON'T
Receive | Respect Account | with highlight | DON'T
Receive | Respect Account | direct message | SEND
Disabled | All messages | mention to @me | SEND
Disabled | All messages | any message | SEND
Disabled | All messages | with highlight | SEND
Disabled | All messages | direct message | SEND
Disabled | Mentions | mention to @me | SEND
Disabled | Mentions | any message | DON'T
Disabled | Mentions | with highlight | DON'T
Disabled | Mentions | direct message | -
Disabled | Nothing | mention to @me | DON'T
Disabled | Nothing | any message | DON'T
Disabled | Nothing | with highlight | DON'T
Disabled | Nothing | direct message | DON'T
Disabled | Respect Account | mention to @me | DON'T
Disabled | Respect Account | any message | DON'T
Disabled | Respect Account | with highlight | DON'T
Disabled | Respect Account | direct message | DON'T

**Comment by sinteur** [comment]
The one you left emtpy:

Disabled 	Mentions 	direct message -> SEND   (thinking a direct message equates a mention more or less)

and I think these should be send:

Receive 	Respect Account 	any message -> SEND   (respect account and account says "receive")
Receive 	Respect Account 	with highlight  -> SEND   (respect account and account says "receive")

**Comment by sampaiodiego** [comment]
the one I left empty was because there is no way you can set that, but it will send the email.

about the others, actually the account option says `Every Mention/DM` ... so that's way it'll not send. (I'll update the table to make it clear)
![image](https://cloud.githubusercontent.com/assets/8591547/13143715/f2678108-d62c-11e5-8edb-a694b9282d16.png)

**Comment by sinteur** [comment]
And while you're messing with all this - please treat @all as different from @me

**Comment by sampaiodiego** [comment]
yes.. @all is treated as "any message" for now.

**Comment by apastuhow** [comment]
> @ALL is treated as "any message" for now.

Actually it confuses. Because I expect that everybody will get the message that I mentioned them. And it doesn't.
