### ISSUE TITLE
Custom Fields - Custom Field appear in middle of the Registration. Cannot specify placement

### ISSUE THREAD

**Issue by gpadbidri** [RocketChat/Rocket.Chat#22643]
I am wanting to add a CHECKBOX to the Registration form where I want the user to ACCEPT our TERMS. However, there are 2 issues : 
1. No CHECKBOX Type support in Custom Fields ?
2. Custom Fields (type: select / text) when added appear in the middle of the form. Is there no way I can mention the placement of the Fields or the order ?

![image](https://user-images.githubusercontent.com/8458489/125273300-68202200-e32a-11eb-842f-8e65246a75ea.png)

**Comment by johncrisp** [comment]
Hi,

thanks for opening this issue.

When opening any issue please first read this, and test on the latest version:

https://rocket.chat/docs/contributing/reporting-issues

You need to fill in the template:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Please note that Github is only for errors and bugs with Rocket.Chat and there is no evidence of that here.

For support please ask your questions in https://forums.rocket.chat/ or https://open.rocket.chat/channel/support

Closing for now but we can re-open if we find any evidence of a bug later.
