### ISSUE TITLE
Incorrect "latest" link (3.16.3)

### ISSUE THREAD

**Issue by gu1ll0me** [RocketChat/Rocket.Chat#22655]
Trying to upgrade from 3.16.2 to 3.16.3 but https://releases.rocket.chat/latest/download linked to version 5.15.4 instead of 3.16.3. Similar to https://github.com/RocketChat/Rocket.Chat/issues/22261.

Using https://releases.rocket.chat/3.16.2/download to reinstall 3.16.2.

Thank you.

**Comment by jacotec** [comment]
Maybe related to #22658 ??

**Comment by gu1ll0me** [comment]
@jacotec 

The download link was just updated with the correct version and the 3.16.3 upgrade worked for me.
