### ISSUE TITLE
Indicator/Notification of new user pending activation

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat#2266]
If 'Manually Approve New Users' is enabled in Accounts: Registration, it would be nice for admins to receive some indication that there are new users pending activation. At very least an activated/not activated indicator in the Users list.

**Comment by RichardFoxworthy** [comment]
Does 'manually approve' work at all? 

I have 'email confirmation' and 'manually approve' options both activated in Admin controls.
I created a new user and could activate and login from the email confirmation link - no approval step required

**Comment by marceloschmidt** [comment]
Duplicate of #976. Definitely something needed.
