### ISSUE TITLE
Cannot freeze array buffer views with elements

### ISSUE THREAD

**Issue by harridu** [RocketChat/Rocket.Chat#22674]
### Description:

If I set a second EMail address in LDAP, then I cannot post anymore.

### Steps to reproduce:

1. set a second EMail address for your account in FreeIPA.
2. login and post a message to your favorite channel.

### Expected behavior:

The message should have been appended to the channel.

### Actual behavior:

The new message is greyed out. There is another message below this one saying
```
rocket.cat 8:00PM Only you can see this message
Cannot freeze array buffer views with elements
```
This message is repeated for a few times after a few minutes.

If I drop the second EMail address in LDAP, then the problem seems to be gone.
### Server Setup Information:

- Version of Rocket.Chat Server: I did not install this RocketChat version, so I do not know.
- Operating System: Debian 11
- Deployment Method: tar, AFAICS
- Number of Running Instances: ?
- DB Replicaset Oplog: ?
- NodeJS Version: v12.22.2
- MongoDB Version: 4.2.15

### Client Setup Information

- Desktop App or Browser Version: Safari iphone
- Operating System: ios 14.6

and others

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

> Version of Rocket.Chat Server: I did not install this RocketChat version, so I do not know.

We can't really help much without this information.

Are you the administrator of this instance?

**Comment by harridu** [comment]
No, we've dropped RC in favour of Teams.
