### ISSUE TITLE
Container builds for RHEL fail with gpg error

### ISSUE THREAD

**Issue by jsm84** [RocketChat/Rocket.Chat#22671]
### Description:

Container builds for RHEL are failing in master (and develop) with the following gpg error:

```
gpg: keyserver receive failed: No name
```

Apparently, the SKS keyserver network is being deprecated, which requires switching to a different keyserver such as openpgp.org. See https://stackoverflow.com/questions/66217436/gpg-keyserver-receive-failed-no-name and also https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key

I suspect that this also affects vanilla (non-RHEL) container builds also, but I've yet to confirm.

### Steps to reproduce:

1. git clone https://github.com/RocketChat/Rocket.Chat.git
2. cd Rocket.Chat/
3. docker build -f Dockerfile.rhel .docker/

### Expected behavior:

A successful container build should occur when building from master.

### Actual behavior:

```
...
STEP 8: RUN set -x  && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104  && curl -SLf "https://releases.rocket.chat/${RC_VERSION}/download" -o rocket.chat.tgz  && curl -SLf "https://releases.rocket.chat/${RC_VERSION}/asc" -o rocket.chat.tgz.asc  && gpg --verify rocket.chat.tgz.asc  && tar -zxf rocket.chat.tgz -C /opt/app-root/src/  && cd /opt/app-root/src/bundle/programs/server  && npm install
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104
gpg: directory '/opt/app-root/src/.gnupg' created
gpg: keybox '/opt/app-root/src/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No name
Error: error building at STEP "RUN set -x  && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104  && curl -SLf "https://releases.rocket.chat/${RC_VERSION}/download" -o rocket.chat.tgz  && curl -SLf "https://releases.rocket.chat/${RC_VERSION}/asc" -o rocket.chat.tgz.asc  && gpg --verify rocket.chat.tgz.asc  && tar -zxf rocket.chat.tgz -C /opt/app-root/src/  && cd /opt/app-root/src/bundle/programs/server  && npm install": error while running runtime: exit status 2
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: Fedora 33
- Deployment Method: docker/podman
- Number of Running Instances: n/a
- DB Replicaset Oplog: n/a
- NodeJS Version: n/a
- MongoDB Version: n/a

**Comment by johncrisp** [comment]
Hi and thanks for reporting.

I'll make sure the Product Team look.
