### ISSUE TITLE
[Question] Can I run Rocket.Chat with NodeJS 14 or 16?

### ISSUE THREAD

**Issue by onozaty** [RocketChat/Rocket.Chat#22675]
I am running Rocket.Chat in the following way.

- Version of Rocket.Chat Server: 3.10.4
- Operating System: CentOS 7.9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.22

Rocket.Chat stops in rare cases. When it stops, it throws out the following log.

```
Jul 8 17:51:37 rocketchat rocketchat: node: ../deps/uv/src/unix/core.c:918: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
Jul 8 17:51:39 rocketchat systemd: rocketchat.service: main process exited, code=killed, status=6/ABRT
Jul 8 17:51:39 rocketchat systemd: Unit rocketchat.service entered failed state.
Jul 8 17:51:39 rocketchat systemd: rocketchat.service failed.
```

I checked and the following problem seems to be occurring.

* https://github.com/libuv/libuv/pull/2686

This issue has already been fixed in the NodeJS 14 and 16 series, but not in the 12 series, which is already under maintenance.

I have two questions.

1. Do you have any plan to support NodeJS 14 or 16?
2. Do you have any way to make the current Rocket.Chat work with NodeJS 14 or 16?
I tried to build it in NodeJS 14 from the source code, but it didn't look easy to me.

Thanks.

**Comment by johncrisp** [comment]
Hi,

Thank for filling out the template but when opening an issue please make sure you follow the bug reporting guidelines:

https://rocket.chat/docs/contributing/reporting-issues

Note github is for issue, and not general support questions.

> Version of Rocket.Chat Server: 3.10.4

https://docs.rocket.chat/getting-support#rocket-chat-versions

So you badly need to upgrade. If you regularly read the release notes and changelogs you will see why.  Any issues on your version will not get fixed.

So please test on latest 3.16.x

For development questions such as node versions etc again, read the release notes and the documentation https://docs.rocket.chat and https://developer.rocket.chat/guides/developer

You can ask support questions at https://forums.rocket.chat or https://open.rocket.chat/channel/support

Closing this as a wontfix. We can re-open if you discover the same issue on the latest code.

**Comment by onozaty** [comment]
Hi @johncrisp 

Thank you for your response.

The following was a question about development, so I asked it on GitHub.

> 1. Do you have any plan to support NodeJS 14 or 16?
> 2. Do you have any way to make the current Rocket.Chat work with NodeJS 14 or 16?
> I tried to build it in NodeJS 14 from the source code, but it didn't look easy to me.

I'll ask the question in the forum.

Thanks.
