### ISSUE TITLE
Add mailgun addon for Heroku deploy button

### ISSUE THREAD

**Issue by patcon** [RocketChat/Rocket.Chat#2268]
Would just require adding a line to the `app.json` and making sure that the code falls back to the default mailgun envvars when others aren't set

(I forgot to save my password and got locked out, and discovered this that way :)

**Comment by patcon** [comment]
Hm. Seems that MAIL_URL isn't being contructed correctly?

Anyone up for sanity-checking me? I deployed `develop` branch using:
https://heroku.com/deploy?template=https://github.com/RocketChat/Rocket.Chat/tree/develop

Then I just did `heroku addons:create mailgun`, and copied its envvars to what rocketchat expects:

```
heroku config:set SMTP_Host=$MAILGUN_SMTP_SERVER       # smtp.mailgun.org
heroku config:set SMTP_Username=$MAILGUN_SMTP_LOGIN    # postmaster@app74bd11c40fb745949ba2974dcd17d130.mailgun.org
heroku config:set SMTP_Port=$MAILGUN_SMTP_PORT         # 587
heroku config:set SMTP_Password=$MAILGUN_SMTP_PASSWORD # <rando hex>
```

But doing a password reset throws this in the logs:

```
   260	2016-02-17T19:28:46.974796+00:00 app[web.1]: Hello,
   261	2016-02-17T19:28:46.974800+00:00 app[web.1]: 
   262	2016-02-17T19:28:46.974801+00:00 app[web.1]: To reset your password, simply click the link below.
   263	2016-02-17T19:28:46.966385+00:00 app[web.1]: (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
   264	2016-02-17T19:28:46.974802+00:00 app[web.1]: 
   265	2016-02-17T19:28:46.974803+00:00 app[web.1]: https://civictechto-rocketchat-test.herokuapp.com/reset-password/GuLBDlE_LQQ9FWThDEFD8g_<snip>
   266	2016-02-17T19:28:46.974804+00:00 app[web.1]: 
   267	2016-02-17T19:28:46.974804+00:00 app[web.1]: Thanks.
```

When I tried to remove `SMTP_Host` and set `MAIL_URL` manually, i just got an error (I did remember to urlencode the username fwiw).

Any thoughts?

**Comment by jekuno** [comment]
Providing the mailgun credentials in the RocketChat email settings works

**Comment by geekgonecrazy** [comment]
We need to make sure we can add this as an optional thing.  If not we won't be able to include this.  We for sure can't force people to use mailgun

**Comment by geekgonecrazy** [comment]
The heroku deployment method is no longer supported.  Closing this
