### ISSUE TITLE
API endpoint im.close does not work

### ISSUE THREAD

**Issue by julienchabanon** [RocketChat/Rocket.Chat#22680]
### Description:

The API endpoint im.close does not works as expected and return 400 Bad Request.

### Steps to reproduce:

1. Use the endpoint im.list to get direct message _id
2. Pass this ID to im.close using POST and roomId param as describe in the doc: [https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration/channels/close](url)
3. 400 Bad Request 

### Expected behavior:

The direct message conversation should not be listed anymore in im.list and im.close should return 200 ok

### Actual behavior:

400 Bad Request from im.close endpoint with the following message:
`"The direct message room, undefined, is already closed to the sender"`

I used to get this 400 bad request when I was passing bad params. That plus the fact that the message mention 'undefined', makes me think that maybe roomId is not the right param key expected.

Note that I am successfully using lots of rocketchat endpoint using POST and roomId as a param. My request is valid.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1 and 3.16.3
- Operating System: Manjaro
- Deployment Method: docker-compose
- Number of Running Instances: 1
- Database Migration: 226
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25

### Client Setup Information

- Desktop App or Browser Version:  87.0.4280.88
- Operating System: Manjaro

Thank you

**Comment by cuonghuunguyen** [comment]
seems there are some changes in the new version that cause the Rest API bug. I sometimes got the parsing params failed as well with the other API endpoints.

**Comment by johncrisp** [comment]
Hi and thanks for reporting.

Can you please follow the issue reporting guidelines and test on the latest possible version - if you are a developer then try a build direct from here.

Things are getting changed and fixed all the time so even a few minor versions can change things.

Please let us know soonest.

**Comment by cuonghuunguyen** [comment]
Hi, TBH I cannot reproduce the issue, I just used Rocket.Chat 3.16.x. It only happened a few times and there's no rule.
Later I set a breakpoint and found out that the body params are parsed to undefined.

**Comment by debdutdeb** [comment]
Hi julienchabanon,

I just checked this with the latest 3.16.3, and it works as expected. So I guess the solution to your issue would be to upgrade to the third patch. 

John, since there's another conversation going on, I'm going to leave it to you to close this issue.

Thanks.

**Comment by debdutdeb** [comment]
Hi julienchabanon, Good Morning :)

> The direct message conversation should not be listed anymore in im.list  

Are you sure about that? I just looked at the doc, and according to it, the wording is `Lists all of the direct messages the calling user has joined`. Closing a DM doesn't exactly make you leave the conversation, but just sort-of-like hide the chat. Otherwise I get a fear of so much redundant DMs if misused.

Hmm, since you're not deleting the chat (or don't intend to) by "closing" it, shouldn't it be listed in `im.list` endpoint?

Please correct me if I'm getting this wrong or confused. Thanks.

**Comment by cuonghuunguyen** [comment]
> The direct message room, undefined

IMO, it seems the problem is the request params parser, not about how the endpoint is used

**Comment by debdutdeb** [comment]
Hmm. cuoonghuunguyen, it'd be mighty lovely if you can (or julien) provide us with something that can indicate this a bit more clearly. 

Nonetheless, we will put this infront of the product team as a potential bug 👍🏼 I'll see if I can get the time (and be able) to create a reproducing scenario. 

Awesome, thanks!!

**Comment by julienchabanon** [comment]
@cuonghuunguyen 
I agree with you! Looks like the param roomId is not recognized anymore for some reasons. Maybe an issue with the request params parser yes.

@debdutdeb If the dm still get listed in im.list after we closed it, we should get some sort of param to let us know if it is closed or not. And does not seems to be the case as we get:
`        {
            "_id":"ew28FnZqipDpvKw3Rrocket.cat",
            "_updatedAt":"2018-02-23T17:58:56.147Z",
            "t":"d",
            "msgs":22,
            "ts":"2018-02-18T19:51:52.557Z",
            "lm":"2018-02-23T17:58:56.136Z",
            "topic":"a direct message with rocket.cat"
        }`
Also, im.close seems to be the issue there as it raise 400 bad request and mention undefined in the response every time.

**Comment by ostjen** [comment]
Just tested the im.close endpoint and it's working fine here @julienchabanon 

could you try this again?

**Comment by julienchabanon** [comment]
I just tried with version 3.17 and open / close does work. However, I was wrong to expect the dm to be removed from `/api/v1/im.list` after closing it. Instead, we need to query: `/api/v1/subscriptions.getOne` and read open property.

Doc:
[https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration/subscriptions/getone](url)

Thank you all for your help!
