### ISSUE TITLE
Avatar is not displayed next to message in an ongoing conversation

### ISSUE THREAD

**Issue by rockhouse** [RocketChat/Rocket.Chat#227]
![screen shot 2015-06-26 at 13 41 48](https://cloud.githubusercontent.com/assets/2719928/8376823/9176dbd6-1c0b-11e5-8e37-ebfdae38bbda.png)

as you can see in the screenshot in an conversation with @sampaiodiego the avatar did not display although someone else was writing the message 

maybe good to know is that a refresh of the page fixes the issue!

**Comment by sampaiodiego** [comment]
@rodrigok I think we still have a bug here.

**Comment by rodrigok** [comment]
I can't understand this bug.
How to reproduce?

**Comment by sampaiodiego** [comment]
when chating with someone, I think if you start typing on the same moment another message arrives, it will be wrongly grouped.
