### ISSUE TITLE
RocketChat Docker container stops instantly after starting

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [RocketChat/Rocket.Chat#22704]
<img width="751" alt="dfgdrg" src="https://user-images.githubusercontent.com/76442625/126233909-2e20ef7c-98cc-48e7-8286-f301313145db.png">

Everything seems correct. I renamed the "db" container to "rocketchat-db" and the"rocketchat" container to "rocketchat-server" but I updated the names to accommodate this change.

**Comment by johncrisp** [comment]
Hi,

This looks like a configuration issue and not a bug.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/contributing/reporting-issues

https://rocket.chat/docs/getting-support

Have a read here:

https://docs.rocket.chat/installing-and-updating/docker-containers

Note you can set a label in your compose file eg

**rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:3.16.3
    container_name: myrocketchat
    environment:
        - MONGO_URL=mongodb://127.0.0.1:27017/rocketchat?replSet=rs0**

Please ask your question in https://forums.rocket.chat or https://open.rocket.chat

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Thank you. What is the misconfiguration?
