### ISSUE TITLE
<br/> is printed for every line break.

### ISSUE THREAD

**Issue by wagneralkmim** [RocketChat/Rocket.Chat#22701]
### Description:

"< br />" is printed for every line break.

### Steps to reproduce:

![image](https://user-images.githubusercontent.com/5919314/126204207-33b75230-b90e-469a-97d5-7583e3d845bf.png)

### Expected behavior:

Doesn't appear the "< br />" tag.

### Actual behavior:

Tag "< br />" is printed for every line break.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Ubuntu

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Can you please make sure you full out the bug reporting template completely? It really helps debugging.

Next, it isn't clear but it looks like you are posting your own bot messages?? Can you give us some more information on how you get this issue please? It is hard to check if we can't repeat it.

**Comment by ankar84** [comment]
I confirm that bug at 3.16.3
![image](https://user-images.githubusercontent.com/4023037/126303635-55fbee6a-e446-4dbc-b274-9b4bf4b5424d.png)

**Comment by fdellwing** [comment]
I can also confirm this problem in 3.16.3. Also it does not only affect new messages, but every message in the past.

![Screenshot_20210720_120056](https://user-images.githubusercontent.com/22813377/126304952-ca9c210b-bf73-4c44-96c2-51a4318f35eb.png)

<details>
  <summary>Code example to generate this embed</summary>
```python
#!/usr/bin/env python3.7

import requests
from tweepy import OAuthHandler, Stream
from tweepy.streaming import StreamListener
from secrets import *

follow_accounts = ["564768235", "4742812221"]


def from_creator(status):
    if status.in_reply_to_status_id is not None:
        return False
    elif status.in_reply_to_screen_name is not None:
        return False
    elif status.in_reply_to_user_id is not None:
        return False
    elif status.user.id_str not in follow_accounts:
        return False
    else:
        return True


class RocketChatListener(StreamListener):
    def on_status(self, status):
        if from_creator(status):
            name: str = status.user.name
            tag: str = status.user.screen_name
            text: str = status.text
            url: str = f"https://twitter.com/{tag}/status/{status.id_str}"
            print(f"{name} (@{tag}): {text} -> {url}")
            tweet = {
                "text": f"Neuer Tweet von {name} (@{tag}):",
                "attachments": [
                    {
                        "text": text,
                        "fields": [
                            {
                                "short": True,
                                "title": "",
                                "value": f"[Direkt zum Tweet]({url})",
                            }
                        ]
                    }
                ]
            }
            requests.post(json=tweet, url=rocket_hook)
        return True

    def on_error(self, status_code):
        if status_code == 420:
            return False


if __name__ == '__main__':
    listener = RocketChatListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)

    stream = Stream(auth, listener)
    stream.filter(follow=follow_accounts)
```
</details>

**Comment by wagneralkmim** [comment]
> Hi and thanks for reporting this.
> 
> Can you please make sure you full out the bug reporting template completely? It really helps debugging.
> 
> Next, it isn't clear but it looks like you are posting your own bot messages?? Can you give us some more information on how you get this issue please? It is hard to check if we can't repeat it.


Hi. Thank you. I only filled the data I thought relevant in the bug report. It's clear what bug is this how was mentioned above.

In my case, the bot sends error messages from my project to Rocket Chat via webhook.

`        'rocketchat' => [
            'driver'  => 'monolog',
            'handler' => RocketChatHandler::class,
            'with'    => [
                'webhooks' => [env('RC_INSTANCE') . '/hooks/' . env('RC_HOOK_LOGERROR_TOKEN')],
                'username' => 'Portal Error',
                'emoji'    => ':rotating_light:',
            ],
            'level'   => env('LOG_LEVEL', 'warning'),
        ],`

**Comment by ankar84** [comment]
Probably fixed by https://github.com/RocketChat/Rocket.Chat/pull/22727
