### ISSUE TITLE
[3.16.3] Private and public channels are grouped together

### ISSUE THREAD

**Issue by fdellwing** [RocketChat/Rocket.Chat#22707]
### Description:

Since 3.16.x the sidebar does not group by public and private channels separately making it extremely hard to find the "official" channels under the mass of private channels.

### Steps to reproduce:

1. Look at the sidebar under Channels

### Expected behavior:

Restore the old behavior. If the current state is not a bug, provide a way to change that server and/or user wide.

### Actual behavior:

The behavior changed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Ubuntu
- Deployment Method: docker-compose
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.9

**Comment by ankar84** [comment]
I think for RC team it's not a bug, but feature - https://github.com/RocketChat/Rocket.Chat/pull/22160

**Comment by fdellwing** [comment]
Well, than let's hope a setting for this is integrated.

**Comment by johncrisp** [comment]
> I think for RC team it's not a bug, but feature - #22160

I think even they have appreciated it is not a popular decision, but they are rewriting the whole sort system, and I believe that as a result this will now re-appear, though likely not til early 2022.
