### ISSUE TITLE
Ugly Emojis are hard to recognize

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#2270]
We recently switched our company to Rocket and one of the top complaints is how ugly and hard to recognize the emojis are and that there are so few of them in the picker.

Please consider using different emoji graphics.

**Comment by graywolf336** [comment]
Which open source package would you recommend?

**Comment by engelgabriel** [comment]
> are so few of them in the picker

This annoys me too :) We need to fix that.

**Comment by ulope** [comment]
[Tewmoji](https://github.com/twitter/twemoji) is pretty ok. They're not quite as good looking as most commercial ones but they're clearly recognizable.

Another thought that just came to me: Why not use the native system emojis on platforms that support them?

**Comment by engelgabriel** [comment]
Mainly for consistency, can you think of any website or app that uses the native system emojis?

**Comment by ulope** [comment]
> Mainly for consistency, can you think of any website or app that uses the native system emojis?

Of the top of my head it looks like "WhatsApp Web" does

**Comment by engelgabriel** [comment]
Looking at http://emojione.com/demo/ and comparing to http://twitter.github.io/twemoji/preview.html the EmojiOne is much more complete... and not that much worst. Sometimes it is more a matter of what you got used to...

**Comment by engelgabriel** [comment]
From https://slack.com/privacy-policy

> Message Exports
Administrators of all teams, both free and premium, can export their team’s messages and files that are shared in channels. Message history for private channels and direct messages is not included in this.
Only owners for teams who have signed up for the appropriate level of Slack service and have enabled Compliance Exports can export their team’s private channel's messages, private channel's shared files and direct messages. Compliance Exports may include message edit and deletion history.

**Comment by lvh1** [comment]
I guess the best option would be to let the end-user decide what kind of emoji pack they want to use, but I guess that would require quite a lot of work.
I personally like the ones used here on GitHub, but I'm not sure if they are free to use.

**Comment by engelgabriel** [comment]
Make this configurable would require quite a lot of work indeed, we'd accept a PR, but this is not a real issue at this point. We already have an issue to fix the emoji picker.
