### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#22711]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by johncrisp** [comment]
I presume that you are asking for Arabic translation?

Please fill in the template correctly.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Next please see this for translations:

https://docs.rocket.chat/contributors/how-can-i-help/translating

I am not sure if this goes in a feature request - I'll have to check.

**Comment by ali-alhaidary** [comment]
I have sent an email to ***@***.*** to be invited for 
translation.

Ali

**Comment by ali-alhaidary** [comment]
did not get any response till now. the application needs so many corrections.

**Comment by ali-alhaidary** [comment]
translated more than 1000 entry ...
