### ISSUE TITLE
double sub-path when using iframe API

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#22737]
### Description:

Running RC 3.15.4 or 3.16.3 on a subpath like https://example.org/rocketchat iframe API "go" commands via postMessage fail:
```
frame.contentWindow.postMessage({externalCommand: "go", path: "/admin"}, "*")
``` 
adds sub-path twice, same for path ```"/account"```

Browser shows the RC 404 page and using the JS console you get the iframe url with the doubled sub-path
```
document.location.href
"https://pole.egroupware.org/rocketchat/rocketchat/admin"
```

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Admin page will be opened for an admin.

### Actual behavior:

RC 404 page is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.4 and 3.16.3 tested
- Operating System: Linux
- Deployment Method: official docker container
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.13 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: recent Chrome Browser, probably with every browser
- Operating System: Windows, Mac or Linux

### Relevant logs:

via browser JS console you get for the RC iframe:
```
document.location.href
"https://pole.egroupware.org/rocketchat/rocketchat/admin"
```

Nothing in the Docker logs.

**Comment by johncrisp** [comment]
Hi Ralf and thanks for reporting this.

I'll get this to the Product Team.

**Comment by ralfbecker** [comment]
Pull-request: https://github.com/RocketChat/Rocket.Chat/pull/22796
