### ISSUE TITLE
Paragraph split not supported in picture description on web client

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22732]
### Description:

Paragraph split not supported in picture description on web client, but mobile version do it great.

### Steps to reproduce:

1. Send a picture with large description with paragraphs
2. Check it on mobile
3. Check it on web client - all text in one paragraph, all separations are trimmed

### Actual behavior:

Web Version
![image](https://user-images.githubusercontent.com/4023037/126626807-de3dec6f-1bfb-4b4d-95b8-a42c1b8de5ed.png)

Mobile client
![image](https://user-images.githubusercontent.com/4023037/126626920-508484d0-31d4-450b-a39e-7b4e216d9bce.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

### Additional context

It would be perfect if picture description support markdown both at mobile and web client with same result.
Telegram can do that and to it perfect!
Users can post news and other staff that way.

Also, It would be nice if user can make description to few pictures at once with markdown support for description.
![image](https://user-images.githubusercontent.com/4023037/126734451-a729b9d1-5d65-454a-8ccc-e57e97ac5a57.png)

### Relevant logs:
No

**Comment by johncrisp** [comment]
Thanks Anton - we'll raise this with the Product Team.

**Comment by ankar84** [comment]
With https://github.com/RocketChat/Rocket.Chat/pull/22750 in 3.18.1 you can't do multiline in web version, but still can in mobile version.

But Web version still shows image description in a single line.

**Comment by ankar84** [comment]
> With #22750 in 3.18.1 you can't do multiline in web version, but still can in mobile version.
> 
> But Web version still shows image description in a single line.

Still same in 4.2.0
Users can't write multiline description to file

**Comment by ankar84** [comment]
Could be fixed in https://github.com/RocketChat/Rocket.Chat/pull/24924

**Comment by Kunalvrm555** [comment]
> Could be fixed in #24924

Thanks @ankar84

**Comment by ankar84** [comment]
Still an issue in 4.8.1

**Comment by ankar84** [comment]
Still a problem in 5.4.1
Users can't write multiline description to file

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

@ankar84 you are partially right, currently we do not support complex messages for file description thought the upload modal, it's in our roadmap to improve this behavior adding the composer to the upload modal.

If you want to send multi line file description, first write the description in the normal composer and select (or paste) the file that you want to send in the room, the description will be automatically attached to the description.

e.g: 

![Image](https://user-images.githubusercontent.com/20212776/228558195-4a4c7121-0c67-4490-be43-3b74438d1e4b.png)



---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
