### ISSUE TITLE
Video Conference jitsi cannot load exist config

### ISSUE THREAD

**Issue by lijicheng168** [RocketChat/Rocket.Chat#22730]
### Steps to reproduce:

1. Go to http://ip/admin/Video%2520Conference
2. Click on save
3. save jitsi works but cannot load the exist config

### Expected behavior:

load jitsi exist config

### Actual behavior:

load the default config(Off)

### Server Setup Information:

- Version of Rocket.Chat Server: docker-3.13.3
- Operating System: docker
- Deployment Method: HEAD: (0c7fbf40d) 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by johncrisp** [comment]
Hi,

please follow the bug reporting guidelines here.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

You really need to upgrade and/or test on the latest version as issues are being fixed all the time.

Thanks.
