### ISSUE TITLE
Broken Screen on Mobile app

### ISSUE THREAD

**Issue by defib** [RocketChat/Rocket.Chat#2275]
After putting in the server URL, this error pops up: http://i.imgur.com/omfcoVx.jpg

Happens on Android and iOS, but not for everyone.

**Comment by marceloschmidt** [comment]
What version are you on? Could you run the latest version and try again?

**Comment by krimdomu** [comment]
@marceloschmidt 
Hi, i have the same problem but on my android device. I'm using the docker image `bd2e44fdc078` which is version 0.34.0 and which is the latest version.

```
# docker pull rocket.chat:latest
Status: Image is up to date for rocket.chat:latest
```

**Comment by MartinSchoeler** [comment]
duplicate of #1106
