### ISSUE TITLE
[Bug] Read-Only Broadcast channel member list problem

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22756]
### Description:

In Read-Only broadcast channel regular users don't see member list button. Moderators and owners can see member list button, but don't see members. Server admins can see all.

### Steps to reproduce:

1. Create **Read-Only Broadcast** channel
2. Add users to **Read-Only Broadcast** channel
3. Check that **Read-Only Broadcast** channel as a regular userA that was added on step 2
4. Check that **userA can't see member list button**
5. **Grant userA moderator** or owner permission in that **Read-Only Broadcast** channel
6. Refresh client by userA (CTRL+R)
7. Check that **userA can see member list button**, but result always **No members found**

### Expected behavior:

All users, that members of Read-Only Broadcast channel should see member list button and all members in that list.

### Actual behavior:

Regular user in Read-Only Broadcast channel
![image](https://user-images.githubusercontent.com/4023037/126936095-3834a438-613f-4100-b19e-939bb0823e1d.png)

Moderator in Read-Only Broadcast channel
![image](https://user-images.githubusercontent.com/4023037/126936321-ad79fb6f-27fa-4f4b-a162-c7b4eca61cf2.png)

Server Admin in Read-Only Broadcast channel
![image](https://user-images.githubusercontent.com/4023037/126936384-692eb0fa-1fa6-40d8-b442-ffb3333b2bd4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

### Additional context

Read-Only not broadcast channel don't have that issue.

### Relevant logs:

No

**Comment by johncrisp** [comment]
Thanks Anton.

Can you try that on 3.17 - I'd guess it is still there but just in case?

**Comment by ankar84** [comment]
> Thanks Anton.
> 
> Can you try that on 3.17 - I'd guess it is still there but just in case?

Sure, when it get stable - I will update that issue with 3.17 information.

**Comment by debdutdeb** [comment]
I literally had "Hi Anton, Thanks for reporting this" typed out, and John came 😶 

Anyway, seems like only if a user is global moderator/admin, he/she can see the user list.

Even if the person is a channel moderator/leader/owner, the API response is -

```
{
  "success": false,
  "error": "unauthorized"
}
```

Initially I thought maybe an `if` statement against the channel context is missing, but if `owner` is also resulting in `unauthorized` response, then it's more than just that.

**Comment by ankar84** [comment]
> Anyway, seems like only if a user is global moderator/admin, he/she can see the user list.

I get that only global admin can see the list.
And we did experiment on open server which is on 3.17-rc2 and issue is still here.

**Comment by debdutdeb** [comment]
> I get that only global admin can see the list.  
Just double checked, global moderator role also has the authorization it seems like.

**Comment by ankar84** [comment]
Still an issue in 3.18.1

**Comment by Aman-Maheshwari** [comment]
Hey @ankar84 I tried reproducing this issue and found a permission `View Members List in Broadcast Room` which is initially checked only for `Admin` , `Moderator` , `Owner`. Selecting `User` in that permission solves the issue.
I hope I understood it correctly, Correct me if I am wrong. :smile: 

I am using RC version `4.2.0-develop`

**Comment by ankar84** [comment]
> Hey @ankar84 I tried reproducing this issue and found a permission `View Members List in Broadcast Room` which is initially checked only for `Admin` , `Moderator` , `Owner`. Selecting `User` in that permission solves the issue.
> I hope I understood it correctly, Correct me if I am wrong. :smile: 
> 
> I am using RC version `4.2.0-develop`

Hello, @Aman-Maheshwari 
It's very interesting!!
Can you find a pr in 3.16 release, that unchecked **users** role in that permission?
Because before that update all worked fine.

Later I will check you suggestion at my deployment and come back with answer.

**Comment by ankar84** [comment]
@Aman-Maheshwari you are definitely right!
Set checkmark at **Users** role to **View Members List in Broadcast Room** permission fixed that issue
![image](https://user-images.githubusercontent.com/4023037/144550774-3b48b57d-21b6-4bd3-8162-f098513e5df3.png)

I'm closing that issue.
But one question still remain - what PR and with what purpose unchecked that permission?

**Comment by Aman-Maheshwari** [comment]
@ankar84 Thankyou.
> But one question still remain - what PR and with what purpose unchecked that permission?

Regarding your question, I looked into the PRs but could not find it.  I will look again into it.
