### ISSUE TITLE
Livechat guest can not register or chat when using allowed domain list

### ISSUE THREAD

**Issue by Lochemage** [RocketChat/Rocket.Chat#2276]
If your chat server is restricted to only allow new user accounts from a list of allowed domains, guests will not be able to chat with the livechat system. I understand this is because guests have to have an account registered, but I feel they should not be restricted to the allowed domain list as they are specifically a guest.

Further more, if you have enabled that guests have to register their name and email, even if they register with an email that is in the allowed domain list, they still receive the error message that they are not of a valid domain.

Thanks!

**Comment by shellster** [comment]
A similar issue exists if you have admin approval of new account enabled.  You can't use the livechat.

**Comment by mixrat** [comment]
Amazing potential but I can't get the chat window to work at all unless I am logged in...
![chat_window](https://cloud.githubusercontent.com/assets/20234985/16612142/895ef52e-43b9-11e6-9be0-35584f4562cb.png)

![account_settings](https://cloud.githubusercontent.com/assets/20234985/16612130/71901f22-43b9-11e6-841e-fcba06891ea7.png)
