### ISSUE TITLE
[bug] List of rooms discussions can't be scrolled to very bottom

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22785]
### Description:

List of all chats discussions can not be scrolled to very first discussion.

### Steps to reproduce:

1. Create a chat (private group for example)
2. Start 10-15 discussions in that chat
3. Click Discussions button in chats menu
4. Try to scroll down to very first discussion

### Expected behavior:

Scroll should be work fine in discussion list

### Actual behavior:

![discussion-scroll](https://user-images.githubusercontent.com/4023037/127269646-a10a1b49-27bb-4070-b0d6-0378f2e1fbb4.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

**Comment by johncrisp** [comment]
Hi Anton,

does that happen on open?

Worth a test there to check.

**Comment by ankar84** [comment]
> does that happen on open?

Same - very first discussion not shown

**Comment by johncrisp** [comment]
Thanks to Antons hard work this is a definite bug as of today 28/7/2021 on open.rocket.chat

https://open.rocket.chat/group/channel-for-discussions

**Comment by ankar84** [comment]
Probably fix prepared in https://github.com/RocketChat/Rocket.Chat/pull/22844

**Comment by ankar84** [comment]
Checked it in 3.18.1 and can tell in fixed!
![image](https://user-images.githubusercontent.com/4023037/133600332-16aa40a1-0176-4ac5-a7d9-408ac02c19ce.png)

Thanks for the team!
