### ISSUE TITLE
[BUG] TypeError on type prop failing builds

### ISSUE THREAD

**Issue by hrahul2605** [RocketChat/Rocket.Chat#22789]
https://github.com/RocketChat/Rocket.Chat/blob/58946aeb41441f6e2aec2995c5dba9c5788d10da/client/components/CreateDiscussion/DefaultParentRoomField.tsx#L30

This TypeError fails Build and Test on github actions https://github.com/RocketChat/Rocket.Chat/runs/3180582306

**Comment by dougfabris** [comment]
Fixed here #22822
