### ISSUE TITLE
incorrect display of user information

### ISSUE THREAD

**Issue by Petroin** [RocketChat/Rocket.Chat#22786]
In the user group, if you view information about contacts. There is a selective incorrect display of information about the user. instead of information about the user with whom you are corresponding, it shows the information of the current user. Moreover, the information is not displayed selectively. Some contacts have data about him, some show the contacts of the current user instead of the contact with whom the correspondence is going on.

**Comment by ankar84** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/22219 in 3.16.0
Please update to recent 3.16.3

**Comment by johncrisp** [comment]
Thanks Anton.

Note if the OP is using a snap that has just been released too.

And closing.

**Comment by Petroin** [comment]
3.2.3 client version install

**Comment by Petroin** [comment]
Deployment
Version
3.16.3
Deployment ID
R67o6y3C4zucWWDGD
Apps Engine Version
1.27.1
Node Version
v12.22.1
