### ISSUE TITLE
external ip adress does not attach

### ISSUE THREAD

**Issue by rzolhoss** [RocketChat/Rocket.Chat#22795]
Hi, in my clients with was configurated with the external ip, i can't attach files, but when i put the internal ip adress of my server, i can do it

**Comment by johncrisp** [comment]
Hi.

Github is reserved for bugs and this looks like a support issue.

See this:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/contributing/reporting-issues
https://rocket.chat/docs/getting-support

Please ask in forums.rocket.chat or open.rocket.chat 

https://open.rocket.chat/channel/support

In the meantime I suggest you use a proper domain, fix your internal DNS, use a reverse proxy and https.

**Comment by rzolhoss** [comment]
Man, you closed my issue and with out help me, and i'm here thinking that this software has a community, with people that want help, i came here from the support button that the rocket put on his software, and you say that github is not for support problem. But i understand, when is free, we have this problems. Thanks for your help
