### ISSUE TITLE
Want to change default email templates

### ISSUE THREAD

**Issue by lleal** [RocketChat/Rocket.Chat#2279]
Hello, I've been looking where the email templates are stored so I could change them, does anybody know?

**Comment by lleal** [comment]
Found it, those are the default meteor templates, thanks for the help in the chat.

**Comment by propertunist** [comment]
i'm also looking to change the default templates.. where are they located? i have not been able to find them. thanks

**Comment by elliotd123** [comment]
@lleal Were you able to change the email templates, and if so, how?

**Comment by lunitic** [comment]
#4000 related to this
