### ISSUE TITLE
[Bug] Global search shows wrong chat names in search results

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22809]
### Description:

In a right side of message in search result of global search now appeared a room name, but it's current room name, not the room with search query name.

### Steps to reproduce:

1. Enable global search
2. In room1 write some unique word like `кавалерия`
3. Create a brand new room2
4. Try to search that word `кавалерия` in room2
5. Results are wrong

### Expected behavior:

In results user should see room name there is a search query is belongs to

### Actual behavior:

room1
![image](https://user-images.githubusercontent.com/4023037/127471968-80604c95-3782-4544-b2da-1fb8ddc3a560.png)
room2
![image](https://user-images.githubusercontent.com/4023037/127472281-d165818e-68d7-4438-baed-0c631760cae2.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

### Additional context

That another issue about global search. First issue https://github.com/rocketchat/rocket.chat/issues/21659 is about wrong checkbox behavior 

### Relevant logs:

No

**Comment by debdutdeb** [comment]
Present in 3.17.0

**Comment by johncrisp** [comment]
And another one for Product Team Debdut.

**Comment by debdutdeb** [comment]
This should be fixed in the next September or October release as well.

**Comment by noobbbbb** [comment]
How is the progress after that?

**Comment by ankar84** [comment]
Still an issue in 4.2.0!

**Comment by ankar84** [comment]
> This should be fixed in the next September or October release as well.

@debdutdeb hey! I guess someone forgot about that fixes,

**Comment by ankar84** [comment]
My issue is actually a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/20574
So closing it if favor of first one.
