### ISSUE TITLE
Mark read in chat menu doesn't affect unread threads

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22802]
### Description:

**Mark read** option in chat menu doesn't mark chat as read if there is unread messages in threads

### Steps to reproduce:

1. Get unread message in thread in some chat
2. Try to mark that chat read
3. Chat still unread and with count in blue circle

### Expected behavior:

Chat become mark as read

### Actual behavior:

Here is a chat with unread message in thread
![image](https://user-images.githubusercontent.com/4023037/127434650-d07991ba-cd52-4e7c-a0b1-82d538bd8189.png)
Try to mark room read
![image](https://user-images.githubusercontent.com/4023037/127434776-90622d3a-c77a-4df9-b845-f1778463dd18.png)
Even if user open chat and read all main chat messages there still count for unread thread
![image](https://user-images.githubusercontent.com/4023037/127437100-023b7073-5c88-4dc4-aa7d-43c4f8a5948a.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

### Additional context

I understand that thread unread messages it's a bit different thing then main chat messages.
But users need a button to mark chat as read despite of threads.
Maybe some option in users preferences like "Mark threads read too on mark chat as read" or something like that.

Now it's not a but, but it's not complete work of **Mark read** button, which must be improved.

### Relevant logs:

No

**Comment by debdutdeb** [comment]
Issue persists on 3.17.0

**Comment by johncrisp** [comment]
Thanks Anton.

One for the Product team Debdut. Can you let them know please?

**Comment by NotACreativeUsername** [comment]
Is there an update on this?
