### ISSUE TITLE
SQL code not parsed in code block

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22819]
### Description:

SQL code not parsed in code block in latest Rocket.Chat server versions
On a previous versions SQL code parsed pretty well (I don't have screenshots, but our users sure about that).

### Steps to reproduce:

1. Write some SQL code in code block in message box and send that message
2. SQL code not parsed (no color highlight)

### Expected behavior:

SQL code highlighted like other languages, like JavaScript

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/127645115-a373a47f-62df-4971-b8e1-26b57fc4e3b4.png)
![image](https://user-images.githubusercontent.com/4023037/127645143-c8c47871-8b11-4e56-9e96-fa03425d2988.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

### Additional context

New parser don't have color highlight for SQL code too

### Relevant logs:

No

**Comment by Karting06** [comment]
Hello,

It's normal. it has been disabled in this [commit](https://github.com/RocketChat/Rocket.Chat/commit/f6bb85eeb9790aed94223df7bffb2d507e3115e8#diff-9ae8d8e06ed1a9589272b27a4dcd00338d97a7870dd36407edbd7fce87b351e3).

If you uncomment [this line](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/markdown/lib/hljs.js#L158) and compile Rocket.Chat, it will work. 

Example:
![image](https://user-images.githubusercontent.com/1096435/127647579-09163365-d026-4055-b6be-32d787075cfd.png)

**Comment by ankar84** [comment]
Solved via https://github.com/RocketChat/Rocket.Chat/issues/22819#issuecomment-889834022
