### ISSUE TITLE
[bug] stream-notify-room subscription

### ISSUE THREAD

**Issue by alb-3** [RocketChat/Rocket.Chat#22817]
### Description:
Hi, I found a (supposed) bug in the subscription to **stream-notify-room** in realtime api.

I followed the instruction to subscribe to ‘**typing**’ (a event of stream-notify-room) but instead of receive ‘ready’ answer I receive ‘**nosub**’.

I used **ddp** lib that provides the unique subscription-id. The others parameters are in the format specified by the documentation ( https://developer.rocket.chat/api/realtime-api/subscriptions/stream-notify-room)

Is it an error of RocketChat server or do I make a mistake? Thanks

### Steps to reproduce:

1 creation of ddp client using ddp lib

2 connection to server using ddp client

3 login with ddp client using ddp-login lib

4 register the guest (call to livechat:registerGuest)

5 send the first message that creates the room (call to sendMessageLivechat)

6 subscription

`ddpClient.subscribe("stream-notify-room", [roomId+"/typing", false], () => { console.log("subscription"); } );` 
  
7 listen to new message

### Expected behavior:

receive` { msg: 'ready', subs: [ '`_number_`' ] }`

### Actual behavior:

receive  `{ msg: 'nosub', id: '`_number_`' }`

### Server Setup Information:

Version of Rocket.Chat Server: 3.16.4

Operating System: Ubuntu 20.04.2

Deployment Method: snap

Number of Running Instances: 1

DB Replicaset Oplog: Enabled

NodeJS Version: 12.22.1

MongoDB Version: 3.6.14

Proxy: nginx

Firewalls involved: none

**Comment by yashovardhan** [comment]
Hey there,

Thanks for reporting this.

Have you tried this on the latest version 3.17? Please check and let us know if the problem still exists. Also, the GitHub Issues are reserved for bugs, please ask the question on the [forum](forum.rocket.chat) where it would be easier for us to give an answer to you. 

I'm closing this issue for now. Feel free to open up if you believe this is actually a bug.

**Comment by johncrisp** [comment]
Note the discussion is here.

https://forums.rocket.chat/t/stream-notify-room-subscription-bug/11786

If we find there is a bug we can reopen this.

**Comment by alb-3** [comment]
Hi Yashovardhan and John, also in the latest version (3.17.0) there is the same problem.
Thanks
