### ISSUE TITLE
Video/Audio Call Icon is missing for DM - 2+ Users

### ISSUE THREAD

**Issue by benhail-tammina** [RocketChat/Rocket.Chat#22820]
Hi Team,

With the recent update Version 3.16.4, We observed that the Call Icon is missing for Direct Messages when there are more than 2 participants.

We really love this feature and is there a way we can bring it back?
Help me :)

Note:
The call icon is present for 
1.Private / Public Channels
2.Teams
3. DM - You and Single User.

**Comment by ankar84** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22552

**Comment by benhail-tammina** [comment]
Yes, it's a duplicate issue, thanks for pointing it out. We Will be following the above-tagged issue for solutions
