### ISSUE TITLE
Nextcloud OAuth Signin stopped working

### ISSUE THREAD

**Issue by sephentos** [RocketChat/Rocket.Chat#22821]
### Description:

So far I have always been able to successfully login via Nextcloud OAuth.
Since the update to 3.16.3, the login with Nextcloud no longer works.

Please notice that I did not change anything inside Nextcloud (!). No update, no configuration change etc.
It only stopped working *after* updating RocketChat Server to 3.16.3.

### Steps to reproduce:

1. Sign in with Nextcloud OAuth
2. Give access to RocketChat within the Nextcloud Authorization
3. After successfull Nextcloud Authorization the Loginpage in RocketChat shows an [undefined] error (see screenshots)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System:  Debian 10
- Deployment Method: Docker
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.26

### Client Setup Information

- Desktop App or Browser Version: Electron Client, Firefox
- Operating System: Windows

### Relevant logs:

RocketChat Log:

```
I20210730-15:34:19.955(0) Failed login detected - Username[unknown] ClientAddress[XXXXXXXX] ForwardedFor[XXXXXXXX] XRealIp[XXXXX] UserAgent[Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0] 

I20210730-15:34:19.956(0) Exception while invoking method login Error: Failed to complete OAuth handshake with nextcloud at https://XXXXXXXX/index.php/apps/oauth2/api/v1/token. failed [401] {"message":""}     at CustomOAuth.getAccessToken (app/custom-oauth/server/custom_oauth_server.js:148:18)     at Object.handleOauthRequest (app/custom-oauth/server/custom_oauth_server.js:205:26)     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)     at middleware (packages/oauth/oauth_server.js:170:5)     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:263:26)     at app/api/server/api.js:394:82     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 
```

![grafik](https://user-images.githubusercontent.com/35430448/127676748-c9f3a672-85c5-4cdb-a604-38a22f1735b0.png)

![grafik](https://user-images.githubusercontent.com/35430448/127677194-abc2bec1-5409-4c4a-a629-735a2e6056ae.png)

![grafik](https://user-images.githubusercontent.com/35430448/127677626-31af838c-14d6-4c23-bf6b-4703dc399804.png)

**Comment by debdutdeb** [comment]
Hey sephentos 👋🏼 

Apologies for the late response 😓 

I have tested nextcloud oauth on 3.17.0 and it is working. Can you please test this on the latest or at least update to the latest 3.16 patch (3.16.4)? I'll be waiting for a response. Thanks 🙂

**Comment by sephentos** [comment]
> 
> 
> Hey sephentos 👋🏼
> 
> Apologies for the late response 😓
> 
> I have tested nextcloud oauth on 3.17.0 and it is working. Can you please test this on the latest or at least update to the latest 3.16 patch (3.16.4)? I'll be waiting for a response. Thanks 🙂

Hi @debdutdeb 

Updated to 3.17.0
Problem unfortunately still persists.

Mind showing your configuration on both sides (ofc with hidden sensitive data), or mind checking my configuration showed above?

**Comment by sephentos** [comment]
Issue still existing with v3.18.1.

**Comment by firlevapz** [comment]
I'm having the same problem with OAuth2 using nextcloud and rocketchat, both installed via snap, suddenly the login stopped working.

```
nextcloud          22.1.1snap1  28503  latest/stable  nextcloud✓   -
rocketchat-server  3.17.2       1484   3.x/stable     rocketchat✓  -
```

**Comment by firlevapz** [comment]
I'm very sure now, this is a nextcloud-related problem, see issue here: https://github.com/nextcloud/server/issues/28261

So i think it can be closed here

**Comment by sephentos** [comment]
Seems that issue does only exist within nextcloud + rocketchat.
Its broken for months now.

Weird way of a [partnership](https://nextcloud.com/blog/rocket-chat-and-nextcloud-announce-partnership-and-integration/) between rocketchat and nextcloud imho...
