### ISSUE TITLE
Problem with the feature "Allow Message bad words filtering" in 3.17

### ISSUE THREAD

**Issue by bobfh** [RocketChat/Rocket.Chat#22831]
### Description:

Problem after update to 3.17 with international symbols

### Steps to reproduce:

1. Write some text on Russian - русский
2. 
### Expected behavior:

Normal Working

### Actual behavior:

rocket.cat
14:23
Only you can see this message
Cannot read property '0' of null

![изображение](https://user-images.githubusercontent.com/88323396/127855406-33eb0b58-6ab8-4f40-8e2c-14a8912fddea.png)

**Comment by bobfh** [comment]
seem is problem with russian word - filter - i have disabled it - and all works fine

**Comment by plazotronik** [comment]
> seem is problem with russian word - filter - i have disabled it - and all works fine

what kind of filter are we talking about? 
"Message_AllowBadWordsFilter" or another?

**Comment by bobfh** [comment]
Message_AllowBadWordsFilter

**Comment by paulopera** [comment]
As mentioned here earlier it's in fact a problem with the feature "Allow Message bad words filtering", not in some specific word but in the feature itself. When I enable the feature pasting a screenshot from the "Clipboard" shows me the error Cannot read property '0' of null and doesn't display any image. The error also occurs when we try to attach a file from the computer too.

![image](https://user-images.githubusercontent.com/7115215/127869243-c7b43f88-db7f-4ba5-87c4-8167ce2fcc75.png)

The file is in the Files menu (which is good and can be retrieved later) in the conversation but it's not displayed in the conversation. If I disable the feature I can paste the image and it's displayed without any errors.

![image](https://user-images.githubusercontent.com/7115215/127869299-25ab81de-b069-4174-83fd-3066d5813679.png)

I thought it could be a possible bug if the language settings is different from the Default App Language, so I set mine to the App Default (pt-br) and the problem persist.

For now I disabled the function so we can paste screenshots from the Clipboard and attach files from the computer.

**Comment by ankar84** [comment]
@bobfh please edit header of that issue to something more relevant like **Problem with the feature "Allow Message bad words filtering" in 3.17**

**Comment by paulopera** [comment]
@bobfh did you accidentally closed the issue?

**Comment by bobfh** [comment]
> 
> 
> @bobfh did you accidentally closed the issue?

i saw same problems in other issues
