### ISSUE TITLE
TypeError: e is undefined when editing a user without a username

### ISSUE THREAD

**Issue by josephcrowell** [RocketChat/Rocket.Chat#22837]
### Description:
Getting TypeError: e is undefined when clicking save in the user editor dialog if username field is blank.

Actual problem is users being able to create accounts with no username.

/api/v1/users.update also returns a 400 Bad request error for these users.

### Steps to reproduce:

1. Go to  Administration -> Users
2. Click on a user
3. Edit any data
4. Click Save

### Expected behavior:

Save the edited data

### Actual behavior:

A big grey screen and errors in the console

![image](https://user-images.githubusercontent.com/2770395/127937910-13d0ec27-a6b2-4b85-8bbf-0db02cb7695d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2

### Client Setup Information

- Desktop App or Browser Version: Firefox 90.0.2, Chrome 92.0.4515.131 and App V 3.2.2
- Operating System: Windows 10

### Relevant logs:
```
TypeError: e is undefined
    username /client/views/admin/users/EditUser.js:1
    Oa https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    Ta https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    useState https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    useState https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:544
    w /client/views/admin/users/EditUser.js:1
    Sa https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    di https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    Fs https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    ef https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    Qs https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    Xs https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    qs https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    _c https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    unstable_runWithPriority https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:586
    pc https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    _c https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    hc https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    De https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
    it https://chat.annon.com.au/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:568
66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js:568:82936
```

**Comment by debdutdeb** [comment]
Hi Joseph, thanks for reporting this.

Do you see this happen all the time? What happens if you restart the main node server process? 

I'll have to dig deeper in order to understand this class of issues. I'll update this thread accordingly.

**Comment by josephcrowell** [comment]
I tried restarting the service but the issue was still the same.

Everything was fine on the 3.16 branch so it's likely something that was committed in the major version change.

**Comment by josephcrowell** [comment]
On 3.17.1, the edit saves on the first user edit, but the second time I edit a user, the page doesn't refresh properly and I get a grey screen again. I am running through an NGINX reverse proxy.

Posst request:
`https://domain/api/v1/users.update`

Response Header:
```
HTTP/1.1 400 Bad Request
Server: nginx/1.16.1
Date: Mon, 23 Aug 2021 00:55:26 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Content-Security-Policy: default-src 'self' ; connect-src *; font-src 'self'  data:; frame-src *; img-src * data:; media-src * data:; script-src 'self' 'unsafe-eval' ; style-src 'self' 'unsafe-inline'
X-Instance-ID: vQsrFsTZQTptcHfrt
Cache-Control: no-store
Pragma: no-cache
access-control-allow-origin: *
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, X-User-Id, X-Auth-Token
Vary: Accept-Encoding
Content-Encoding: gzip
```

**Comment by josephcrowell** [comment]
This was caused by users creating an account without a username. How are they able to create an account without a username?

**Comment by reetp** [comment]
> This was caused by users creating an account without a username. How are they able to create an account without a username?

Sensibly they should not be able to.

Can you test on the latest code and re-open if this still occurs?

**Comment by josephcrowell** [comment]
I moved on to a different chat client and can't run the latest Rocket.chat due to: https://github.com/RocketChat/Rocket.Chat/issues/23346
