### ISSUE TITLE
Desktop App cannot connect to rocket.chat（docker image version 0.18） with self-signed certificate using nginx-proxy

### ISSUE THREAD

**Issue by llitfkitfk** [RocketChat/Rocket.Chat#2284]
Your Rocket.Chat version: (make sure you are running the latest)

rocket.chat docker image version 0.18:
1. Mac client cannot connect. Error shows: "Not a valid instance url" (tested)
2. Mobile Client (IOS) can connect (tested)
3. Web can connect (tested) 
4. Mobile Client (Android) & Windows PC Client (not yet tested)

rocket.chat docker image version 0.16:
Mac client works correctly

**Comment by Elvinra** [comment]
I run rocket without docker and i have the same probleme "Not a valid instance url" on windows
When the client is trying to make HEAD Request for the url, the header X-Rocket-Chat-Version is missing

**Comment by engelgabriel** [comment]
What version of the desktop app are you using? Make sure you test with the beta from https://github.com/RocketChat/Rocket.Chat.Electron/releases

**Comment by dotnetneile** [comment]
This you may have had the same issue I faced and just found that the latest release of the client doesn't use the header value to check for validity now. #2289

**Comment by engelgabriel** [comment]
Indeed, as some proxies were dropping the header we decided to stop using it. Please upgrade to the 1.0.0 version of the desktop app.

**Comment by rekeds** [comment]
I managed to connect the app to http://chat:3000

not as neat as https://chat
and on android both won't load.

**Comment by engelgabriel** [comment]
The only time I have seed such behaviour, the certificate chain was not installed correctly on NGINX, so it would only work on desktop browsers that have more complete list of root certificates.

**Comment by brylie** [comment]
We are experiencing this issue with a LetsEncrypt certificate.

**Comment by engelgabriel** [comment]
Hopefully this will work better when we upgrade to nodejs 5 in a month

**Comment by pgladwin** [comment]
Is this a LetsEncrypt issue?

**Comment by llitfkitfk** [comment]
@pgladwin no, This is issue https://github.com/RocketChat/Rocket.Chat/issues/2289
