### ISSUE TITLE
Cannot read property '0' of null when file attached

### ISSUE THREAD

**Issue by Quiver92** [RocketChat/Rocket.Chat#22853]
### Description:

When I try to upload new file to chat conversation I get a message "Cannot read property '0' of null"
![obraz](https://user-images.githubusercontent.com/13777007/128130274-c1115bc3-bef9-497c-8150-a83fd6883214.png)

### Steps to reproduce:

1. Go to user conversation
2. Click on plus sign in the right corner
3. Click on "Computer" button
4. Choose any file from PC
5. Try to upload file

### Expected behavior:

File uploaded as a message in conversation chat

### Actual behavior:

![obraz](https://user-images.githubusercontent.com/13777007/128130528-274715ab-fd30-4602-be83-8b46869d770e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.17 / mmapv1 (oplog Enabled)

### Client Setup Information

- Browser Version: Firefox 90.0.2, Chrome Latest
- Operating System:  Windows 10

### Relevant logs:

`server.js:204 System ➔ error Error sending message: TypeError: Cannot read property '0' of null     at Filter.clean (/app/bundle/programs/server/npm/node_modules/bad-words/lib/badwords.js:58:41)     at app/lib/server/methods/filterBadWords.js:25:24     at callbacks.runItem (app/callbacks/lib/callbacks.js:111:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at app/callbacks/lib/callbacks.js:45:45     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at app/callbacks/lib/callbacks.js:45:47     at callbacks.run (app/callbacks/lib/callbacks.js:127:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at sendMessage (app/lib/server/functions/sendMessage.js:220:22)     at executeSendMessage (app/lib/server/methods/sendMessage.js:79:10)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:108:11)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at packages/ddp-server/livedata_server.js:1689:15     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/ddp-server/livedata_server.js:1687:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at app/file-upload/server/methods/sendFileMessage.js:85:16     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 `

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/22831
Try to disable  `Allow Message bad words filtering` feature and check

**Comment by Quiver92** [comment]
Ok, its solves problem. Thank you
