### ISSUE TITLE
Investigate heroku labs feature to negate ROOT_URL requirement

### ISSUE THREAD

**Issue by patcon** [RocketChat/Rocket.Chat#2287]
There's a labs feature that allows an app to know it's app name, and hence the herokuapp.com url:

https://devcenter.heroku.com/articles/dyno-metadata

We could check for `HEROKU_APP_NAME` to build `ROOT_URL` if it hasn't been set.

Would be best if we could enable that labs feature from the `app.json` file. Haven't tested, but investigated the platform api ref docs and if it works, this is likely the key:

``` json
{
  "features": [
    "runtime-dyno-metadata"
  ]
}
```

I've dropped a Twitter question to find out if it's an undocumented `app.json` spec option. If not, I'll make the request.

https://twitter.com/patconnolly/status/700783691744694272

**Comment by engelgabriel** [comment]
I've already spoke to the Heroku guys, and it is not available.

```
Hi Gabriel,

Ok. We've discussed adding a web url generator to app.json, which would solve the use case you are showing there. Without knowing all the specifics about dyno metadata and custom domain names, I'm assuming that people would have to set the ROOT_URL in that case.

Do you think that generator would work?

Thanks,
Guðmundur Bjarni
```

**Comment by patcon** [comment]
Generator seems limited in scope and much less of a solution that a "features" array, but would def be a better option (for this and a few other projects I've worked on :)
