### ISSUE TITLE
3.17.0 - attempting to edit own's message ends with "Cannot read property 't' of undefined"

### ISSUE THREAD

**Issue by msoltyspl** [RocketChat/Rocket.Chat#22889]
### Description:

In version 3.17.0 (perhaps also earlier) - attempting to edit own's message ends with 2x "undefined" error popup. The message looks changed on the editor's screen (web, desktop client), but no one else can see the changes.

On the mobile client, neither the editor nor other users can see changes (and no popups).

The log (from the rocket's container) shows:

```
server.js:204 System ➔ error Exception while invoking method updateMessage Cannot read property 't' of undefined
server.js:204 System ➔ error Exception while invoking method updateMessage Cannot read property 't' of undefined
```

There seems to be nothing relevant in mongodb's log.

### Steps to reproduce:

1. Type anything
2. Try to edit

### Expected behavior:

Edited message visible for every user.

### Actual behavior:

![bug](https://user-images.githubusercontent.com/3541095/128722639-a1ab389c-3104-4b31-87b3-08371c4959eb.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: debian buster
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: vivaldi, firefox, desktop client, mobile client
- Operating System: linux, windows

As mentioned in description, desktop/web client lie about message being edited. Mobile client doesn't

**Comment by debdutdeb** [comment]
Similar to https://github.com/RocketChat/Rocket.Chat/issues/22830

**Comment by debdutdeb** [comment]
:wave:

I don't have any concrete information on this one yet. The thing is it's not universally reproducible. I'll have to figure out why and where this issue is surfacing.

If you have any information on reproducibility, please let me know.

**Comment by yashovardhan** [comment]
Hey there,

We had a conversation with the product team about this. This issue is already highlighted there and they're working on it. Most probably, it will be fixed in the next release.

**Comment by msoltyspl** [comment]
Looks like 3.17.1 fixed the issue.

**Comment by debdutdeb** [comment]
Thanks for confirming msoltyspl :)

Closing this then.
