### ISSUE TITLE
[Bug] Instance overloaded on restart

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22886]
### Description:

Some details could be find here https://github.com/RocketChat/Rocket.Chat/issues/21182#issuecomment-894084462

We have set every night restart of all Rocket.Chat instances one-by-one in 5 minutes periods long time ago and it worked perfect more then a year now.
We restart instances to mitigate memory leak and other related Rocket.Chat performance issues.
On 3.16.3 that process now is broken for us.
We use `docker restart` to restart Rocket.Chat instance.

Some instances (totally random one) could stuck after reboot process.
One tool that can show that freeze instances is `docker stats`.
That stuck and freeze instances CPU load  is 101-103%
Net I/O for that instances is stuck
There could be one or more freeze instances on one server.
User sessions (WS sessions metric looks like not influence that issue)

Sometimes another restart of that instances lead to normal load, but not always.
Sometimes restart of all server instances lead to normal load, but not always.

Few times we get that behavior not after reboot, but in a middle of the day, here is additional info about that [one](https://github.com/RocketChat/Rocket.Chat/issues/21182#issuecomment-854487719), [two](https://github.com/RocketChat/Rocket.Chat/issues/21182#issuecomment-891627673)

I think that issue on restart could be some race conditions or something like that, because right after restart there is no much user sessions on instance, and load should be very low.

### Steps to reproduce:

1. Restart all instances one-by-one
2. Check `docker stats` for all instances
3. See some instances CPU overloaded (102-103% for a period of time)

### Expected behavior:

Normal load on instance restart

### Actual behavior:

Here is some examples of such freeze instances
![image](https://user-images.githubusercontent.com/4023037/128667594-537a4508-1c9a-4e01-9ebe-93bbd42ab349.png)
![image](https://user-images.githubusercontent.com/4023037/128667650-f00cfb62-74f3-4127-ab71-058804a53fac.png)
![image](https://user-images.githubusercontent.com/4023037/128667714-f4cc7063-98f9-4e91-bac9-0bec2191a2bd.png)
![image](https://user-images.githubusercontent.com/4023037/128667768-6602077a-5cf5-4b59-96b3-e0b0fd9276c8.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20 (one without user sessions for Presence monitor)
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 and Chrome 92
- Operating System: Windows 10

### Additional context

It could ve some kind of race conditions of restart.

### Relevant logs:

No any critical logs in that freeze time. 
I did try to enable debug level - no luck.

Here is a example on instance logs in debug mode. You can see last log entry at `09:57:47.000` and then only at `10:02:05.000` so about 5 minutes that instance was overloaded and not send any logs.

<details>

```
	August 7th 2021, 10:02:06.000	s-rc-srv-05	rocketchat_rocketchat_6_1	API ➔ debug Success {  statusCode: 200,  body: {    message: '{"msg":"result","id":"8523","result":[]}',    success: true  }}
	August 7th 2021, 10:02:06.000	s-rc-srv-05	rocketchat_rocketchat_6_1	Meteor ➔ method broadcastAuth -> userId: null, arguments: ["W2xv8FA8hvthsPNTz","yKCK4XhGEP2Ki5N8y"]
	August 7th 2021, 10:02:06.000	s-rc-srv-05	rocketchat_rocketchat_6_1	Meteor ➔ method broadcastAuth -> userId: null, arguments: ["wTyZf9427S5CbFkWt","yKCK4XhGEP2Ki5N8y"]
	August 7th 2021, 10:02:05.000	s-rc-srv-05	rocketchat_rocketchat_6_1	API ➔ debug Success {  statusCode: 200,  body: { message: '{"msg":"result","id":"29"}', success: true }}
	August 7th 2021, 10:02:05.000	s-rc-srv-05	rocketchat_rocketchat_6_1	StreamBroadcast ➔ Auth.info Authorizing with 172.18.106.162:3005
	August 7th 2021, 10:02:05.000	s-rc-srv-05	rocketchat_rocketchat_6_1	SyncedCron ➔ info Not running "Remove users from Token Channels" again.
	August 7th 2021, 09:57:47.000	s-rc-srv-05	rocketchat_rocketchat_6_1	Meteor ➔ publish null -> userId: null, arguments: []
	August 7th 2021, 09:57:47.000	s-rc-srv-05	rocketchat_rocketchat_6_1	API ➔ debug POST: /api/v1/method.callAnon/public-settings%3Aget
	August 7th 2021, 09:57:47.000	s-rc-srv-05	rocketchat_rocketchat_6_1	Meteor ➔ publish null -> userId: 3nTGNAePuQrDKSkei, arguments: []
	August 7th 2021, 09:57:47.000	s-rc-srv-05	rocketchat_rocketchat_6_1	Meteor ➔ method public-settings/get -> userId: undefined, arguments: []

```

</details>

**Comment by Gummikavalier** [comment]
We've seen very high loads during and immediately after start of any node (tar based installation), but this has been how it has always been for us.

One node seems to need something like 30 to 60 seconds to establish itself, after which the CPU load goes from 100% -  200% figures down to regular 0 - 10% load.

We haven't spotted completely stuck nodes, at least not for a year or two.

**Comment by emikolajczak** [comment]
Hi @Gummikavalier ,
Are you also on 3.16.3 version?

**Comment by ankar84** [comment]
> We've seen very high loads during and immediately after start of any node (tar based installation), but this has been how it has always been for us.
> 
> One node seems to need something like 30 to 60 seconds to establish itself, after which the CPU load goes from 100% - 200% figures down to regular 0 - 10% load.

You are totally right, that is true for us too. That's why we have 5 minutes between each instance restart - to give some time to instance to get to normal load after high start load.

But stuck instances behave a bit different. On a very start CPU load is floating and can be more then 100%, but in some moment load hold near 101-103% and stay there infinite with that little change.

**Comment by debdutdeb** [comment]
:wave: Anton !

Performance related issue - hmm. I don't know where we're at with the performance improvement stuff. I'll ask Milton.

**Comment by Gummikavalier** [comment]
> Hi @Gummikavalier ,
> Are you also on 3.16.3 version?

Currently at 3.16.4, but yeah, all versions have done this (heavy starting load in the past.

> But stuck instances behave a bit different. On a very start CPU load is floating and can be more then 100%, but in some > moment load hold near 101-103% and stay there infinite with that little change.

Ok. We haven't seen that happening with 3.x.x versions, at least not yet. I remember it happening maybe two years ago couple of times, but that old cases are likely to be unrelated at this point. We also restart nodes weekly because of memory leaks, past or present, just in case.

**Comment by ankar84** [comment]
> Ok. We haven't seen that happening with 3.x.x versions, at least not yet. I remember it happening maybe two years ago couple of times, but that old cases are likely to be unrelated at this point. We also restart nodes weekly because of memory leaks, past or present, just in case.

Thanks for information, @Gummikavalier !

All that means, that we have something, that lead to that issue.
Last change to docker-compose.yml file I did was push time-out tuning with these environment variables
```
      - NOTIFICATIONS_WORKER_TIMEOUT=2000
      - NOTIFICATIONS_BATCH_SIZE=150
      - NOTIFICATIONS_SCHEDULE_DELAY_ONLINE=10
      - NOTIFICATIONS_SCHEDULE_DELAY_AWAY=0
      - NOTIFICATIONS_SCHEDULE_DELAY_OFFLINE=0

```

Maybe it could be related to our problem. But maybe there is something only we have.

**Comment by ankar84** [comment]
After few days of successful instances restart I can tell that we can rid of that problem.
We change whole restart process, made it interactive and now looks like all works perfect, as it was earlier. 
Main idea - we now checking CPU load (using docker stats) of all instances before restart next instance.

So, I'm closing that issue because it was only us involved and now it fixed for us.
