### ISSUE TITLE
Unable to login with REST API (with json)

### ISSUE THREAD

**Issue by noobbbbb** [RocketChat/Rocket.Chat#22891]
### Description:

After updating to 3.17.0, "api/v1/login" returns a 400 error and I cannot login.
Using "Content-type:application/json" returns a 400 error, but using "application/x-www-form-urlencoded" succeeds.

### Steps to reproduce:

Follow the example to call the API.
https://developer.rocket.chat/api/rest-api/endpoints/team-collaboration-endpoints/authentication/login

Example of failure.) 
```
curl -H "Content-type:application/json" \
      http://localhost:3000/api/v1/login \
      -d '{ "user": "myusername", "password": "mypassword" }'
```

Example of success.) 
```
curl -H "Content-type:application/x-www-form-urlencoded" \
      http://localhost:3000/api/v1/login \
      -d 'user=myusername' -d 'password=mypassword'
```

### Expected behavior:

Successful login, 200 status code and token returned

### Actual behavior:

Login failed and a 400 status code was returned.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: CentOS Linux release 7.5.1804 (Core)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.5

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by debdutdeb** [comment]
Hi :wave:

I just tested this on my personal server, seems to be working fine for me. I can't see any issues with your curl command either. I'm going to have to ask you to try this once again. Add the exact json server response to the comment as well.

**Comment by noobbbbb** [comment]
Thank you, debdutdeb.
I tried resetting the password to the bot user that was having the problem and was able to log in successfully.
"Content-type:application/json" also logged in fine, and it seems to be working fine.
I would like to close this issue for the time being, since the event where I could only login with "Content-type:application/x-www-form-urlencoded" is no longer occurring.
