### ISSUE TITLE
Unable to connect to recent versions from the desktop application "Not a valid instance url"

### ISSUE THREAD

**Issue by dotnetneile** [RocketChat/Rocket.Chat#2289]
Running the latest version I am unable to add servers from the windows native application. I can see in the code that it is checking by looking for a header of "X-Rocket-Chat-Version" from the server. I have also seen comments in another issues (#1352) "We will change from a custom header to a /info rest api". If this has happened and I can't find the point in code to prove this and the native app is looking for this it'll never connect.

I've proved this by having two previously registered servers and being unable to add a further. Then removing one of the two and experiencing the issue trying to add it again. That and stepping through the start.js file.

rocketHeader = 'X-Rocket-Chat-Version'.toLowerCase()
if (headers.indexOf(rocketHeader) !== -1) {

**Comment by dotnetneile** [comment]
Always the case. Found that the latest version (1.0.0) released about 13 hours ago fixes this. Just need to update the https://rocket.chat/ site to point to this release rather than the 0.0.9 version now.

**Comment by engelgabriel** [comment]
Links fixed. Thanks.
