### ISSUE TITLE
Long press on message brings up menu that doesn't work

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#2291]
Your Rocket.Chat version: 0.18
When you long press on a message it brings up a menu, none of the options on the menu work. Pressing the gear box on the message brings a mini icon menu that does work.

**Comment by mrplow** [comment]
When you long press on a message it brings up a menu, none of the options on the menu work. Pressing the gear box on the message brings a mini icon menu that does work.

**Comment by mrplow** [comment]
![gif_20160220_162044](https://cloud.githubusercontent.com/assets/1490165/13200274/87bc7a28-d7f5-11e5-8814-979b819089ee.gif)

**Comment by mrplow** [comment]
This is reproducible on the official demo server. Has no one else noticed this issue?

**Comment by geekgonecrazy** [comment]
The menu needs a little love we know :) its a legacy menu mainly was added for the report abuse functionality a while back.  :smile:

We welcome Pull Requests to improve it :+1:

**Comment by mrplow** [comment]
Ahhh okay so the report works then?
Does it email the admin user?

Just removing the delete message option would be useful since it has been moved to the gear options menu and confuses users.

**Comment by geekgonecrazy** [comment]
We don't currently have a way to view them, but it does report it.

**Comment by mrplow** [comment]
Fixed in
@e4f68c3
