### ISSUE TITLE
Rocket.chat main UI crashes when opening user profiles

### ISSUE THREAD

**Issue by ovflowd** [RocketChat/Rocket.Chat#22912]
### Description:

Sometimes when browsing users on the "Users" browser (after clicking the globe (browser) icon) and selecting a random user from the list, Rocket.chat the main UI will crash, leaving only the sidebar.

### Steps to reproduce:

1. Go to Browse
2. Select the Users tab
3. Select a user

### Expected behavior:

It should not crash and show the user profile or possibly start a DM?

### Actual behavior:

The main UI crashes

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0 (cewhZchbW2Kofibii)
- Operating System: Not sure
- Deployment Method: Not sure
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.3

### Client Setup Information

- Desktop App or Browser Version: 3.2.3
- Operating System: macOS Big Sur 11.5.2

### Relevant logs:

![Screenshot at Aug 12 14-57-04](https://user-images.githubusercontent.com/12037269/129201197-5b7bb183-b412-41e2-8143-e35c86c1475c.png)

**Comment by johncrisp** [comment]
Hi.

I'll get someone to look at this. 

Is this just a standalone server - no iframes or anything odd?

**Comment by ovflowd** [comment]
Hey @johncrisp, thank you! Afaik is just a standalone server, with nothing fancy. And normal client using the macOS App.

**Comment by yashovardhan** [comment]
Hey Claudio,

I had a conversation with the Product Team. It seems that the QA team is a bit preoccupied with other issues at the moment. We will get this checked by the first week of September and followup with a resolution.

**Comment by gabriellsh** [comment]
This has been fixed already. Please, if the issue persists, open a new report with the updated info. Thanks!
