### ISSUE TITLE
click to join and jitsi integration

### ISSUE THREAD

**Issue by kipakiha** [RocketChat/Rocket.Chat#22911]
**Description:**
Jitsi is unable to load in the same window but works with option "always open in new window" enabled, plus the "click to join" button doesn't work, users must click on the phone icon to join the call

**Steps to reproduce:**
- Install rocket.chat and jitsi as standalone on the same server
- Enable jitsi in rocket.chat
- Try to call someone
- 
**Expected behavior:**
The "click to join" button should join the call, and jitsi should be work without "always in new windows" enabled

**Actual behavior:** 
The "click to join" button produce a JS error in console : 
"Uncaught TypeError: t.muted is undefined
    e https://myserver.lan:8443/66eaa3be98974e118b931b4c4ec6172ce4ec8f05.js?meteor_js_resource=true:971"

And with the "always open in new window" option disabled, screen is splitted but nothing happens. JS console shows :

Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. myserver.lan:8443:1:560
Error in parsing value for ‘transform’.  Declaration dropped.

**Server Setup Information:**
OS: GNU/Linux Debian 11

Rocket.chat version 3.17.0
Deployment method: docker-compose

Jitsi stable-5963: release 
Deployment method: docker-compose

**Client Setup Information**
Tested on Windows 10  with firefox 90 and chrome 92
Tested on Fedora 34 with Firefox 90 and chromium  91
Tested on Debian 11 with Firefox-esr 78 
All of these produce exactly the same results

**Additionnal revelent informations**
Nothing is logged server side. Jitsi is installed using the official docker-compose file provided, as well as rocket.chat.

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/22845

**Comment by kipakiha** [comment]
Well, sorry, I looked for a lot of issues and didn't find this one. Thanks for answer, I'll wait for the other issue now. This one can be closed.

**Comment by kipakiha** [comment]
Well, sorry, I looked for a lot of issues and didn't find this one. Thanks for answer, I'll wait for the #22845  to be resolved.
