### ISSUE TITLE
user pull menu for RTL languages do not show fully

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#22923]
Describe the bug
![1](https://user-images.githubusercontent.com/75235623/129378143-e5184f9d-dd59-4596-ab3b-622f3e658852.png)
![2](https://user-images.githubusercontent.com/75235623/129378147-1331ae42-2beb-4ead-888c-606a32fd52de.png)
 in desktop web version

What operating system and which version?
ubuntu 16...20, windows

Which version of Rocket.Chat (Server)?
latest

Which version of Rocket.Chat.Electron (Electron/Desktop)?
Is there any setting relevant changed?

To Reproduce

    Go to your login page
    Click on login
    if the default language was any of the RTL
    click on your avatar
    the pull down menu will not show in full.

Expected behavior
the pull down menu should be visible in full

**Comment by yashovardhan** [comment]
Hey there,

Thanks for reporting this. I just checked and this indeed is a bug. I'll make sure to address this with the respective team. This might take a while though. I'll update on this issue accordingly.

**Comment by ali-alhaidary** [comment]
Thank you, however, this bug makes the application not usable for RTL users.

**Comment by sparse91** [comment]
A workaround. Add this to Custom CSS:
[dir="rtl"] .rc-popover__content {
  min-width: 200px;
}

**Comment by ali-alhaidary** [comment]
Yes, it worked...
Thanks

**Comment by ali-alhaidary** [comment]
:-)

**Comment by BAAlghamdi87** [comment]
this bug is it the windows app and also the web version
