### ISSUE TITLE
problem with server url not pointing to root

### ISSUE THREAD

**Issue by ObiWahn** [RocketChat/Rocket.Chat#2293]
Running the latest docker image I have the following problem:

Passing the option `--env ROOT_URL=https://docker/chat/` when starting the
container with docker run. Results in requests like:

```
"GET /assets/favicon.ico?v=3 HTTP/1.1"
"GET /sounds/door_chime.mp3 HTTP/1.1"
"GET /images/logo/logo.svg?v=3 HTTP/1.1"
fonts, ...
```

So I wonder why it is not using the `/chat/` part of the url. Chatting works so far without problems just all the images etc are missing.

The Framework also complains that I have configured https://server/chat but that I am accessing form https://server. 

Cheers

Jan

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
