### ISSUE TITLE
Creating direct message results in 404

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#22938]
### Description:

If you create a `Direct Messages` room with let's say two users, you get a 404. 

This behaviour could be reproduced on two RC servers.

### Steps to reproduce:

1. Go to 'Direct Messages'
2. Add two users
3. Browser shows https://mychatserver.net/direct and I see the 404 page
4. Reload page -> room is available

### Expected behavior:

Jumping immediately to new direct messages room.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: debian
- Deployment Method: k8s
- Node v12.22.1
- MongoDB 4.0.18

**Comment by yashovardhan** [comment]
Hey there,

Thanks for reporting this. 

Looks like you're using an old instance of the Rocket.Chat server. Can you please update your server to `3.17`?

If you still have any problem after updating, feel free to reply back on the issue.
