### ISSUE TITLE
Push notifications stop working

### ISSUE THREAD

**Issue by makarov-ittx** [RocketChat/Rocket.Chat#22935]
### Description:

Push notifications stuck on 10k of 20k a

### Steps to reproduce:

1. Use sponsorship option on github, increase push limit to 20k
2. Reaching 10k 
3. Push notifications stop working

### Expected behavior:

Use 20k push notifications

### Actual behavior:

![rc-push-limit](https://user-images.githubusercontent.com/71596855/129452025-f07a09b7-d056-4a2a-bf03-2efd20ee116b.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: Ubuntu 20.04
- Deployment Method: Manual install
- Number of Running Instances:  1
- DB Replicaset Oplog: dont know
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.26 / mmapv1

**Comment by johncrisp** [comment]
Please note that github is reserved for bugs.

Can you please contact me at john.crisp at open.rocket.chat and we can have a look at your payment setup.

Thanks.
