### ISSUE TITLE
[QUESTION] Move to new server - do I have to reinstall the private apps?

### ISSUE THREAD

**Issue by juzser** [RocketChat/Rocket.Chat#22933]
Hi, 

I'm moving our rocketchat to a new server, with separated mongoDB server. All migrate jobs,... are fine.
But I have a question: 
Beause I installed some private apps, and there are a lot of records in mongo. 
Now if I move to a new server, with old DB, do I have to re-install the private apps and all private app data are still existed or not? 
Because I think if I have to re-install the apps, the app id will be changed? And I cannot use associate records for them?

**Comment by johncrisp** [comment]
Hi, please note that github is for bugs in Rocket.Chat

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/contributing/reporting-issues

https://rocket.chat/docs/getting-support

Please ask general questions in https://forums.rocket.chat or https://open.rocket.chat/channel/support

We should be able to assist you there,

Thanks.
