### ISSUE TITLE
[QUESTION] Configure Email Inboxes to send all emails to a specific channel, instead of Omnichannel

### ISSUE THREAD

**Issue by chwba** [RocketChat/Rocket.Chat#22931]
I have been using this in Slack to have deployed applications send daily logs via email to the server - As the functionality is already implemented in RocketChat, I wonder which modifications or configuration must be applied to make it work. 

Sending emails to the Omnichannel seems to work fine but my usecase is completely different so the aim for LiveChat/Support does not apply.

**Comment by johncrisp** [comment]
Hi, please note that github is for bugs in Rocket.Chat

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/contributing/reporting-issues

https://rocket.chat/docs/getting-support

Please ask general questions in https://forums.rocket.chat or https://open.rocket.chat/channel/support

Thanks.
