### ISSUE TITLE
Allow system, channel and account level push notification default preferences

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat#2295]
Your Rocket.Chat version: 0.18.1

Currently the push notifications settings for the Desktop and Mobile Push notifications are done by a user at the Channel level. It would be great to be able to set account level preferences (or even better, to be able to view and modify all existing notification settings in a preference page) to avoid the following clicking for each channel. Channel > Tab notification > Open Push Notification > Click Save.

Also it would be great to allow server admins to set default notification settings for new channels, and for channel creators to set default notification settings for each user.

The use case is avoiding the "I didn't receive that notification!?" problem.

**Comment by sampaiodiego** [comment]
this is now possible. you can set them in all levels, server, account and channel levels.
