### ISSUE TITLE
Error for teams.addRooms -- missing rooms

### ISSUE THREAD

**Issue by dmcfarland930** [RocketChat/Rocket.Chat#22956]
Hello, I seem to be having issue adding existing rooms (in this case a group) to a team. I believe I'm sending in the proper values according to documentation. Any ideas? Is it because I'm technically adding a private group to the team?

Team Info:
`{'team': {'_id': '611c1878a72c8f000a4d2625', 'name': 'TestTeam', 'type': 1, 'createdAt': '2021-08-17T19:13:44.349Z', 'createdBy': {'_id': 'aAdxFoQqrCtEG4tM5', 'username': 'admin'}, '_updatedAt': '2021-08-17T19:13:44.349Z', 'roomId': 'tuAWyxyqTyGZs9Yqm'}, 'success': True} `

Group Info:
`{'group': {'_id': 'zjMvqqLcyZwsDi7C6', 'fname': 'TestGroup', 'customFields': {}, 'name': 'Room7-edx-development-team', 't': 'p', 'msgs': 0, 'usersCount': 3, 'u': {'_id': 'aAdxFoQqrCtEG4tM5', 'username': 'admin'}, 'ts': '2021-08-17T19:58:18.742Z', 'ro': False, 'default': False, 'sysMes': True, '_updatedAt': '2021-08-17T19:58:18.764Z'}, 'success': True}`

Data sent to teams.addRooms endpoint:
`{'teamId': 'tuAWyxyqTyGZs9Yqm', 'rooms': ['zjMvqqLcyZwsDi7C6']}`

Result of teams.addRooms:
`{'success': False, 'error': 'missing-rooms'}`

Thanks in advance.

**Comment by johncrisp** [comment]
Hi,

Please note that github is for issues, not general support.

Please make sure you fill out this template, and as per the link there on reporting issues, please test this on latest first.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Thanks.
