### ISSUE TITLE
Matomo (Piwik) and CSP error

### ISSUE THREAD

**Issue by cb3inco** [RocketChat/Rocket.Chat#22963]
### Description:

Matomo analytics are being blocked because of a CSP policy blocking the Matomo js file. 

### Steps to reproduce:

1. Go to Admin -> Analytics -> Setup Piwik (Matomo)
2. Save changes
3. Reload Rocket.Chat in regular user with Inspect open in browser.

### Expected behavior:

Send Analytics to Matomo instance

### Actual behavior:

SCP blocking of js file on Matomo.

![image](https://user-images.githubusercontent.com/14948644/129915865-59f378d2-3e06-49e9-9de4-a908edf1e618.png)

See here for more information: https://content-security-policy.com/examples/blocked-csp/ - looks like the header or meta tag needs to be updated. Here is specific information - https://content-security-policy.com/script-src/ it looks like script-src needs to be added to the 'home' header with the matomo url. 

Also Piwik should be renamed to Matomo

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Ubuntu 18.04
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Brave, Edge, Firefox
- Operating System: Ubuntu

**Comment by yashovardhan** [comment]
Hey there,

Thanks for reporting this.

Can you please test this out on the latest version and let us know? (3.17.1)

Bugs are often fixed on the latest release so please test it there first and see if it still occurs. You can also test on the development version, or try on open.rocket.chat which is usually the latest development code.

**Comment by cb3inco** [comment]
@yashovardhan thank you, I did try it also on the latest release. It's pointing to analytics.doman.com/js but I think that's wrong as well.

**Comment by tarator** [comment]
Problem still persists on version 4.0.1

**Comment by avignat** [comment]
Still a problem in 4.3.1

**Comment by ApolloLV** [comment]
If this needs to be addressed by changing the way the tracking script is included, here is the relevant code (I think):

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/analytics/client/loadScript.js

**Comment by stephen-cox** [comment]
This is a problem with RocketChat 4.7.2 and Matomo  4.10.0

**Comment by AisukoWasTaken** [comment]
Problem persists in 4.8.1

**Comment by DRLDoom** [comment]
Problem persists in v5.0.3

**Comment by avignat** [comment]
Bug still exists in 5.4.1

**Comment by wokawoka** [comment]
Is this bug still present in rocket chat 6?
