### ISSUE TITLE
Struck with account management

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#2296]
Hi, I actaully integrated the login with gitlab by setting the Gitlab API url filed in admin section, but now im the changed the gitlab url for some reasons, how do i want to change it in th rocket chat instance without logging in to rocket chat. is there any config or db values to change directly. And im running in the rocket chat in docker. please help me.

**Comment by engelgabriel** [comment]
On your DB open the `rocketchat_settings` collection and modify the `value` property of the object you can find with this query:  `{"_id":'API_Gitlab_URL"}`
