### ISSUE TITLE
users not added

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#22961]
### Steps to reproduce:

1. create rocketchat instance in moodle
2. click on that instance.
3. a new web page will open asking to login
4. after succesful login, the room page is dispalyed
5. course students are not added

### Expected behavior:

course students are added (as per previous versions)
### Actual behavior:
course students are not added

Server:
version
3.17.1
Deployment ID
k2azqAPxAsgMXZwEP
Apps Engine Version
1.27.1
Node Version
v12.18.4
Database Migration
228 (August 18, 2021 12:58 PM)
MongoDB
4.0.26 / mmapv1 (oplog Enabled)
Commit Details
HEAD: (7ab533e97)
Branch: HEAD
PID
4737

### Client Setup Information
ubuntu, windows and mac
FF, edge, safari

### Relevant logs:
```
<!-- Logs from SERVER -->
I20210818-10:01:19.998(0) server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName Invalid user [error-invalid-user] I20210818-10:04:35.697(0) server.js:204 System ➔ error Exception while invoking method saveSettings TOTP Required [totp-required] I20210818-10:09:43.347(0) server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName Invalid user [error-invalid-user] I20210818-10:09:52.835(0) server.js:204 System ➔ error Exception while invoking method login User not found [403] I20210818-10:10:34.618(0) server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName Invalid user [error-invalid-user] I20210818-10:15:09.683(0) server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName Invalid user [error-invalid-user] I20210818-10:15:15.433(0) server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName No permission [error-no-permission] 

```

**Comment by ali-alhaidary** [comment]
I20210819-08:01:28.863(0) loadLocale {   id: 'xW2jRF24vrPd8yiGz',   clientAddress: '185.240.19.124',   httpHeaders: {     host: 'localhost:3000',     'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0',     accept: '*/*',     'accept-language': 'en,ar;q=0.5',     'accept-encoding': 'gzip, deflate, br',     referer: 'https://mersaal.the5stars.org/group/b57998fe5c25fe7daa614515d9692378a8eb0ad3_______________________________________________________________________________________________________436?layout=embedded',     'content-type': 'application/json',     'x-user-id': 'null',     'x-auth-token': 'null',     'x-requested-with': 'XMLHttpRequest',     origin: 'https://mersaal.the5stars.org',     cookie: 'rc_uid=N33Ge2DfjZnwCCPrg; rc_token=89zaJ4OaSy937cJSV9tgSUMFlVy5x1uclWDM25xkyg0; _ga=GA1.2.1588204441.1629224809; _gid=GA1.2.1167299036.1629224809',     'sec-fetch-dest': 'empty',     'sec-fetch-mode': 'cors',     'sec-fetch-site': 'same-origin',     'x-forwarded-for': '185.240.19.124',     'x-forwarded-host': 'mersaal.the5stars.org',     'x-forwarded-server': 'mersaal.the5stars.org',     connection: 'close',     'content-length': '93'   },   userId: undefined } 

As I can see rc_uid is correct and as set in moodle plugin, however, rc_token is not...

**Comment by yashovardhan** [comment]
Hey there,

Thanks for reporting this.

We'll check this and get back to you as soon as possible.

**Comment by ali-alhaidary** [comment]
@yashovardhan it seems that it has not been possible since Aug 24, so I am closing this issue. Thank you.

**Comment by ali-alhaidary** [comment]
@yashovardhan it seems that it has not been possible since Aug 24, so I am closing this issue. Thank you.
