### ISSUE TITLE
Direct messages: Create new direct message leads to 404

### ISSUE THREAD

**Issue by vskarda** [RocketChat/Rocket.Chat#22971]
### Description:

New direct message to a contact with no previous chat history (chat has never been opened) leads to 404.

### Steps to reproduce:

Create > New > Direct message > _choose contact with no previous conversation_ - leads to 404 

### Expected behavior:

Chat window is opened.

### Actual behavior:

404 page is displayed

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Debian 10
- Deployment Method: classic virtual system pattern
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.4.7

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: all

**Comment by ankar84** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/22944
Will be released in 3.18 probably.

**Comment by yashovardhan** [comment]
Closing since this is already fixed in development.
