### ISSUE TITLE
[docker] what is the different between rocketchat/rocket.chat & rocket.chat 

### ISSUE THREAD

**Issue by longtth** [RocketChat/Rocket.Chat#23000]
I've search hub.docker.com today to get rocket chat and got confused between 2 link

```
docker pull rocket.chat
# https://hub.docker.com/_/rocket-chat
# this has "Official Image" tag 
```

and 

```
docker pull rocketchat/rocket.chat
# https://hub.docker.com/r/rocketchat/rocket.chat
```

what is the different between them?

**Comment by ankar84** [comment]
Answer can be found [here](https://docs.rocket.chat/installing-and-updating/docker-containers/available-images)

**Comment by longtth** [comment]
> Answer can be found [here](https://docs.rocket.chat/installing-and-updating/docker-containers/available-images)

thanks
