### ISSUE TITLE
Clicking on settings icon in Channel scrolls down to bottom

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat#2301]
Your Rocket.Chat version: develop

Using Chrome and the develop branch when I click on the settings cogwheel icon in an older message in the channel the channel automatically scrolls down, so I have to scroll back up manually to then click the desired option (which scrolls down automatically again).

Cheers,

Jun

**Comment by rodrigok** [comment]
Which OS are you using?

I tested in `OS X El Capitan, Chrome 48.0.2564.109 (64-bit), develop branch` and I can't reproduce the issue

**Comment by samhocevar** [comment]
I can reproduce the problem on Chromium (Linux) and Google Chrome (Windows 10).

**Comment by MartinSchoeler** [comment]
@jmatsushita @samhocevar  is this bug still happening?

**Comment by MartinSchoeler** [comment]
@jmatsushita @samhocevar If the bug reappears please reopen this. Thanks!
