### ISSUE TITLE
Scroll dropdown move while page is scrolling

### ISSUE THREAD

**Issue by gajkomichal** [RocketChat/Rocket.Chat#23012]
on prefferences accound card while I try to select option fron input, and the page is scroll, the drop down is mowin on page, somewhere is counting the top and left position, but can't found where it is
![Screenshot from 2021-08-23 13-18-43](https://user-images.githubusercontent.com/31179097/130439129-2d527d51-dc90-4fe1-970c-e9f98c1a5efd.png)
![Screenshot from 2021-08-23 13-18-53](https://user-images.githubusercontent.com/31179097/130439134-415b7f77-08cc-4c9f-b40e-786c12bce5ed.png)
![Screenshot from 2021-08-23 13-19-00](https://user-images.githubusercontent.com/31179097/130439135-711bfae9-737e-4e52-8ae2-5c3ca27879c5.png)
![Screenshot from 2021-08-23 13-20-35](https://user-images.githubusercontent.com/31179097/130439136-b70f6e3c-06b5-4336-a128-6d13728e3ad5.png)

Server Setup Information:

    Version of Rocket.Chat Server: 3.17.0
    Operating System and so on are unknown to me

Client Setup Information:

    Browser Version: Firefox 78.0.2 / 79.0 (64 Bit, tested on both machines), Chrome Version 93.0.4577.63 (Official Build) (64-bit)
    Operating System: Ubuntu 20.04.3 LTS

**Comment by debdutdeb** [comment]
Hi,

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

You can ask for support here:

https://open.rocket.chat
https://forums.rocket.chat

At the very least, please help the developers by filling out a bug template. Use the ‘Bug report’ button here

https://github.com/RocketChat/Rocket.Chat/issues/new/choose

Or use the bug template here:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

This will help the developers find the bug and make Rocket.Chat a better experience.
