### ISSUE TITLE
The Ubuntu system by snap installed rocket.chat, but SMTP does not work properly

### ISSUE THREAD

**Issue by dendinuo** [RocketChat/Rocket.Chat#23026]
this is log：
I20210825-16:02:56.406(8) Exception in defer callback: Error: Greeting never received     at SMTPConnection._formatError (/snap/rocketchat-server/1483/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)     at SMTPConnection._onError (/snap/rocketchat-server/1483/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)     at Timeout.<anonymous> (/snap/rocketchat-server/1483/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:704:22)     at listOnTimeout (internal/timers.js:554:17)     at processTimers (internal/timers.js:497:7) {   code: 'ETIMEDOUT',   command: 'CONN' }

**Comment by dendinuo** [comment]
I changed the SMTP port to solve this problem

**Comment by dholbrook86** [comment]
> I changed the SMTP port to solve this problem

I'm getting the same issue. What port did you settle on?
