### ISSUE TITLE
Emoji will still be rendered inside URLs

### ISSUE THREAD

**Issue by fcdt** [RocketChat/Rocket.Chat#23020]
### Description:

Emoji will still be rendered even if the surrounding text is recognized as a URL. 

### Steps to reproduce:

1. Open any chat, such as a direct message to yourself or a thread within a channel. 
2. Enter a url that contains a colon-delimited abbreviation for an emoji, for example<br/>
    `https://example.com/?cmdNode=b8:flag_lv:b9:c2`

### Expected behavior:

The URL should appear in text form as I entered it and become a clickable link.

### Actual behavior:

Sequences within the URL that match the colons-delimited abbreviations for emoji are rendered as such instead of text. The linked URL is still functional and does not contain the emoji, only the display is incorrect. To prevent this, the sequence between the colons must be interrupted by a space or something similar, which will break the link.

![rocketBug](https://user-images.githubusercontent.com/45634818/130593953-6b126a4e-e06d-4866-9165-1e1953cf18ec.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System and so on are unknown to me

### Client Setup Information:

- Browser Version: Firefox 78.0.2 / 79.0 (64 Bit, tested on both machines)
- Operating System: Ubuntu 16.04 / 19.10

### Additional context:

Internal structure of the example message created above, retrieved from `/api/v1/im.messages?roomid=anonymized&count=1`:
```json
{
  "messages": [
    {
      "_id": "anonymized",
      "rid": "anonymized",
      "msg": "https://example.com/?cmdNode=b8:flag_lv:b9:c2",
      "ts": "2021-08-24T09:12:13.293Z",
      "u": {
        "_id": "anonymized",
        "username": "fcdt",
        "name": "fcdt"
      },
      "_updatedAt": "2021-08-24T09:13:49.006Z",
      "urls": [
        {
          "url": "https://example.com/?cmdNode=b8:flag_lv:b9:c2",
          "meta": {
            "pageTitle": "Example Domain"
          },
          "headers": {
            "contentType": "text/html; charset=UTF-8",
            "contentLength": "648"
          },
          "parsedUrl": {
            "host": "example.com",
            "hash": null,
            "pathname": "/",
            "protocol": "https:",
            "port": null,
            "query": "cmdNode=b8:flag_lv:b9:c2",
            "search": "?cmdNode=b8:flag_lv:b9:c2",
            "hostname": "example.com"
          }
        }
      ],
      "mentions": [],
      "channels": [],
      "md": [
        {
          "type": "PARAGRAPH",
          "value": [
            {
              "type": "LINK",
              "value": {
                "src": {
                  "type": "PLAIN_TEXT",
                  "value": "https://example.com"
                },
                "label": {
                  "type": "PLAIN_TEXT",
                  "value": "https://example.com"
                }
              }
            },
            {
              "type": "PLAIN_TEXT",
              "value": "/?cmdNode=b8"
            },
            {
              "type": "EMOJI",
              "value": {
                "type": "PLAIN_TEXT",
                "value": "flag_lv"
              }
            },
            {
              "type": "PLAIN_TEXT",
              "value": "b9:c2"
            }
          ]
        }
      ],
      "editedAt": "2021-08-24T09:13:48.565Z",
      "editedBy": {
        "_id": "anonymized",
        "username": "fcdt"
      }
    }
  ],
  "count": 1,
  "offset": 0,
  "total": 1,
  "success": true
}
```

**Comment by debdutdeb** [comment]
Hi fcdt.

I just tested this on 3.17.0 - I'm not seeing the same behaviour unfortunately. See below

![Screenshot from 2021-08-24 18-43-25](https://user-images.githubusercontent.com/76006232/130622719-5c34b04b-0754-463b-969f-eb24b749c793.png)

**Comment by fcdt** [comment]
Hi debdutdeb, thanks for your reply. Some additional information:

The message was posted (in another test run) using `/api/v1/method.call/sendMessage` with payload
```http
{"message":"{\"msg\":\"method\",\"id\":\"23\",\"method\":\"sendMessage\",\"params\":[{\"_id\":\"anonymized\",\"rid\":\"anonymized\",\"msg\":\"https://example.com/?cmdNode=8c:flag_lv:b9:c2\"}]}"}
```
Posting it using `/api/v1/chat.postMessage` with
```sh
curl -H "X-Auth-Token: anonymized" -H "X-User-Id: anonymized" -H "content-type: application/json" "https://example.com/api/v1/chat.postMessage" -d '{"roomId":"anonymized","text":"https://example.com/?cmdNode=b8:flag_lv:b9:c2"}'
```
evokes the same behavior which is why I suspect a server-side problem.

Could this be caused by additional commands or are there other modifications that could cause such behavior?

**Comment by debdutdeb** [comment]
Hi, sorry for the delay in responding. Can you please test this on 3.18.1? I tested this with `method.call/sendMessage` as well, still couldn't reproduce the issue unfortunately.

**Comment by mikuhn** [comment]
I also have this issue, if i send only an link as message via the web client. An example would be:

https://example-my.sharepoint.com/:x:/g/personal/jlkasjsadfasdfdsf

The `:x:` part is rendered as :x:

**Comment by BriceBKOH2** [comment]
Hi, we noticed a problem today after updating to 5.0.0 with emojis being displayed in url :

![bug_url](https://user-images.githubusercontent.com/49202976/181805537-ae54bd7c-8ef2-40d4-ab74-014c9c8bc728.png)

The url in the first comment bugs the same, but also url when there is only one character (letters, number or special) followed by a dot after the https:// part.

**Comment by saschafoerster** [comment]
I can confirm this behavior reappearing after installing RocketChat 5.0.0 (docker): 
<img width="249" alt="Bildschirmfoto 2022-07-31 um 11 35 08" src="https://user-images.githubusercontent.com/1153741/182020241-618310d2-ec6d-4592-957a-9856fb2af286.png">

**Comment by kekefreedog** [comment]
Same problem for me with url which doesn't have `.com` or dot something...
![image](https://user-images.githubusercontent.com/70959083/185956419-483ce199-0e3f-4fbe-b33c-09bbea27e31a.png)

**Comment by chotaire** [comment]
This appears to be happening with urls that start with a single letter, followed by a special character, such as http://a.example.com

**Comment by saschafoerster** [comment]
@murtaza98 Can you maybe have a look at this issue for the next update? It's destroying a lot of links in our rocket.chat instance. Thank you so much!
