### ISSUE TITLE
OAuth login "hangs" with 3.18.0-rc.0, regression since 3.17.x

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#23024]
### Description:

OAuth login "hangs" with 3.18.0-rc.0 with a roughly 10 different "Uncaught in Promise" errors, until I reload with F5, then everything seems fine. 

Seems only to happen if I'm already authorized with the authorization server (EGroupware in my case), not if I have to login first. Might be a timing problem. 

You can try it out on one of our public demo-instances https://bb-trunk.egroupware.de/rocketchat/ clicking on [EGroupware users click here] to use OAuth, for user/password ping me on @RalfBecker @ open.rocket.chat. 

First login with redirect to EGroupware login works, when I then log out of RC and click again on [EGroupware users click here] the problem happens. That's a regression to 3.17!

### Steps to reproduce:

See above.

### Expected behavior:

OAuth login should work if I'm already logged into the autorization server without a manual reload.

### Actual behavior:

It hangs until I manually reload / F5.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0-rc.0
- Operating System: Mac OS or Linux checked
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.13

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Mac OS

### Relevant logs:

![Bildschirmfoto 2021-08-24 um 22 06 29](https://user-images.githubusercontent.com/972180/130682649-bf2e2b73-0f64-4084-bbc3-11770ba36442.png)

**Comment by yashovardhan** [comment]
Hey Ralf,

Thanks for reporting this. I'll bring this to the product team's attention on Monday.

**Comment by ralfbecker** [comment]
I updated and checked the mentioned demo-server with the final 3.18.0 and it still fails :(
Promise rejection errors after the OAuth redirect stall everything, until you reload the browser. Then everything works.

Ralf

**Comment by debdutdeb** [comment]
Hey Ralf, as mentioned on our private channel, this will be fixed in the next release. We were so close to this release (as you can see by the release yesterday) that this couldn't have been added to the current one. 

Any new information please continue on this thread updating. Really appreciate it.

**Comment by ralfbecker** [comment]
This problem is fixed with 4.0.0.

So from my point of view this bug report can be closed, unless you want to backport the fix to 3.18.

Ralf
