### ISSUE TITLE
Deb packages 404'ing on https://rocket.chat/

### ISSUE THREAD

**Issue by jeremiah** [RocketChat/Rocket.Chat#2303]
On this page: https://rocket.chat/ the button that leads to "Download for Linux" is resolving to a 404 page on GitHub. 

Perhaps create a PPA for Ubuntu packages and consider sending your deb packages to Debian so users can simply 'apt-get install rocket.chat' ?

**Comment by engelgabriel** [comment]
File name fixed to rocketchat-1.0.0-linux.deb

How do we create a create a PPA for Ubuntu packages?

**Comment by jeremiah** [comment]
You can simply rebuild your existing deb package on Ubuntu and put it in a Personal Package Archive: http://askubuntu.com/questions/4983/what-are-ppas-and-how-do-i-use-them/40351#40351

I would build for the Long Term Server 14.04 and for the most recent version, or perhaps you'll want to wait for Xenial which is to be released in April.

**Comment by engelgabriel** [comment]
We were planning to use this https://build.opensuse.org/project/show/network:rocketchat

**Comment by jeremiah** [comment]
That looks like the Open Build Server. It likely is a good solution. :+1: 
OBS builds both rpms and debs so you may be able to create packages for a bunch of architectures and platforms.
