### ISSUE TITLE
Messages not showing up in public channel via WebHooks post 3.17.1 snap automatic update

### ISSUE THREAD

**Issue by axi0m** [RocketChat/Rocket.Chat#23035]
### Description:

After 8/18 refresh/update to 3.17.1 via snapd, messages for a specific integration (incoming webhook) is no longer populating in the channel.

### Steps to reproduce:

1. Update to 3.17.1. via snap on Debian 10. 
2. Run this code snippet to post incoming webhooks. 
```
import requests
import json

data = {
  "emoji": ":chipmunk:",
  "text": "Example message",
  "attachments": [
    {
      "title": "Rocket.Chat",
      "title_link": "https://rocket.chat",
      "text": "Rocket.Chat, the best open source chat",
      "color": "#764FA5"
    }
  ]
}

# Rocket Webhook URL
webhook_url = "https://<redacted>/hooks/<redacted>"

prepared_json_payload = json.dumps(data)
print(f'[!] DEBUG - JSON HTTP POST payload\n')
print(prepared_json_payload)

r = requests.post(webhook_url, json.dumps(data))
print(f'[!] DEBUG - Response decoded content\n')
print(r.content)

print(f'[!] DEBUG - Response headers\n')
print(r.headers)

# Verify 200
if r.status_code != 200:
    print(f'[!] ERROR - POST request to RocketChat was unsuccessful: {r}')
if r.status_code == 200:
    print(f'[+] INFO - Webhook successfully POSTed to {webhook_url}')
```
3. No messages show up in custom public channel even though the integration is enabled, the response code from Rocket is 200 and DEBUG logs show the message was successfully received. 

### Expected behavior:

Message is displayed in channel. 

### Actual behavior:

No message shows up. 

Output from testing script. 
<img width="945" alt="Screen Shot 2021-08-25 at 12 28 13 PM" src="https://user-images.githubusercontent.com/2532857/130837476-d693069d-8bea-458f-8d0c-bd3557469ec7.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.1
- Operating System: Debian 10.10 x64
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.0.3
- Operating System: Mac OS 11.5.2

### Additional context

N/A

### Relevant logs:
```
I20210825-15:16:10.597(0) API ➔ debug POST: /hooks/<redacted>/<redacted> 
I20210825-15:16:10.599(0) Integrations ➔ Incoming WebHook.info Post integration: github_alerts 
I20210825-15:16:10.600(0) Integrations ➔ Incoming WebHook.debug @urlParams: {   integrationId: 'ZTyqi8miGnfQHb3pS',   token: '<redacted>' } 
I20210825-15:16:10.601(0) Integrations ➔ Incoming WebHook.debug @bodyParams: {} 
I20210825-15:16:10.602(0) API ➔ debug Success { statusCode: 200, body: { success: true } }
```

**Comment by debdutdeb** [comment]
Hi

Change the `post` method call to this -

```python
r = requests.post(webhook_url, json=data)
```

No need to `json.dumps`. The content type is not set to json otherwise, and thus not parsed as a js object. If it used to work like what you have written there, then it might be possible that this check was added in the recent version. 

**CAUTION: once you do, you'll not be able to open the channel because of a bug with attachments. There's no issue on github yet if I remember correctly. I'm currently looking at it and will update everyone ASAP.**

**Comment by axi0m** [comment]
@debdutdeb You are right! That seems to fix my problem. Apologies for wasting anyone's time on this.

**Comment by debdutdeb** [comment]
Not a problem axi0m :) But do remember the final caution though. 

Closing it now.
