### ISSUE TITLE
How to add fields to the users?

### ISSUE THREAD

**Issue by elgriego** [RocketChat/Rocket.Chat#2304]
I would like to add fields to the user registration!

The registration only ask for and user name & email.

I try but I can't do it :S

[UPDATE]

What i try is adding fields in the registerUser.coffe : 

userData =
            email: formData.email
            password: formData.pass
            lastname: 'lastName'

But it does not work :S, I get an error on meteor terminal: 

Error: A method named 'registerUser' is already defined
at livedata_server.js:1542:15
at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
at [object Object]._.extend.methods (livedata_server.js:1538:7)
at Object.Meteor.methods (server/lib/debug.js:33:2)
at server/methods/registerUser.js:2:1
at server/methods/registerUser.js:22:1

**Comment by rodrigok** [comment]
@RocketChat/core what do you think about this issue?

**Comment by Johann-Snapp** [comment]
@elgriego,

Actually, userData (where you're trying to add the lastname) is passed to Accounts.createUser which is a meteor function and which won't save extra data.
Just have a look a bit below, I think you can do something like: `RocketChat.models.Users.setName userId, formData.name`

**Comment by engelgabriel** [comment]
We should have a way to define extra fields for the registration form (similar to the settings?), but I can imagined it getting much more complex very soon, as admin will want to configure validations, etc.

But I agree, we should have some easy way to add more fields.

**Comment by geekgonecrazy** [comment]
Related: #2046

**Comment by timkinnane** [comment]
related #2048

**Comment by timkinnane** [comment]
@RocketChat/core I'm working on this issue with @nazclarion. We're wondering where in mongo is the best place for user field extensions - A) in the user document, B) nested in a property of user (like `custom-fields`), C) in a seperate collection?

I’m not sure what that means for migrations with different versions / branches. If we populate custom fields then build a version that doesn’t have this package, are there DB migrations that would remove the changes?

Speaking of validations etc, I'd like to work towards a more unified approach to encourage consistency with admin controls and settings pages, which is kinda lacking at present.
I've looked into how other Meteor projects do that and found a possible approach, using a few packages together to provide schemas for auto-building forms. Maybe there's some packages already doing this? e.g.

[aldeed:simple-schema](https://atmospherejs.com/aldeed/simple-schema) combined with [aldeed:collection2](https://atmospherejs.com/aldeed/collection2). Then possible to also use [aldeed:autoform](http://autoform.meteorapp.com/) to generate form UI straight from the collection schema, no template markup required.

OR 

More manual, less prescriptive approach could just be providing a front end validator to all packages, something like [Parsley.js](https://atmospherejs.com/amr/parsley.js).

Thoughts?

**Comment by engelgabriel** [comment]
It would also be useful to have these "About me"/"Role" fields be searchable from a system-wide search feature that searches among all chats and user profiles, so that I could search for expertise within my organization using the search feature.

**Comment by engelgabriel** [comment]
I would also like this feature, synced from ldap. Essentially, the additional fields could be added to 'User Data Field Map' under Admin -> LDAP. Any hints on where to start?

**Comment by engelgabriel** [comment]
@cbrummitt, @VirtuaCreative, @estadtherr, @meilinger, @joetm, @Schoaf, @svenschumacher, @gongled, @jcardila @acaronmd lets use the issue to track your request from https://github.com/RocketChat/Rocket.Chat/issues/2046

**Comment by engelgabriel** [comment]
@timkinnane and @rodrigok can we have a chat about this on our demo server?

**Comment by gpoudrel** [comment]
I agree it is needed, together with #2135 :)

**Comment by rodrigok** [comment]
Add fields in registration process was done here https://github.com/RocketChat/Rocket.Chat/pull/4073

**Comment by chellem** [comment]
+1

**Comment by geekgonecrazy** [comment]
@RocketChat/core is there anything needed done on this?  From what I can tell #4073 should have resolved this.

**Comment by graywolf336** [comment]
@geekgonecrazy Documentation on how it works and how to use it.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat.Docs/issues/221

**Comment by shaharido1** [comment]
Hey, i'm trying to add some customFields using the api/v1/users.update method.

It seems that my HTTP calls are successful (e.g. i'm managing to update the "name" field; or add complete new users). nonetheless, it seems that i can't update (or add) customField  - as it doesn't appear in the user data on mongoDB.


```
 var options = {
        url: url +"/api/v1/users.update",
        method: 'POST',
        headers: {
            "X-Auth-Token": credentials.authToken,
            "X-User-Id": credentials.userId,
            "Content-type": "application/json"
        },
        form: {userId: userId, data: {customFields: {twitter:"something"}, name: "ido try"}}
    }
request(options, function(err, res, body) {
        var bodyParse= JSON.parse(body)
        console.log(bodyParse)
    })

```

**Comment by Syirrus** [comment]
@shaharido1 I'm having the same problem. Were you able to resolve this?

**Comment by sampaiodiego** [comment]
have you guys correctly configured the `Custom Fields` under `Administration > Accounts > Registration`?

**Comment by Syirrus** [comment]
@sampaiodiego I have not. I just added the fields manual to my document i.e.

   "_id" : "Giek2324dsd",
    "customFields" : {
        "situation" : "I was hurt by a person.", 
        "amount" : "50", 
        "isShowing" : false
    }

So I have to add the custom fields in the admin section and then the API (users.update) will work?

Syirrus

**Comment by sampaiodiego** [comment]
> So I have to add the custom fields in the admin section and then the API (users.update) will work?

Yes, exactly

**Comment by Syirrus** [comment]
@sampaiodiego I added the custom fields as such to the Admin section:

{
  "bounty" : {
    "situation": "text", 
    "willPay": "text", 
    "isShowing": false
  }
}

I'm POSTing to my url and get the following return:

<all of my data>
"success": true

But, when I look at my "bounty" key it's exactly the same 
I've checked my variable types and all is consistent with what I added in the Custom Section.

Any ideas?

**Comment by Syirrus** [comment]
@sampaiodiego nevermind I took a break and looked at what I was doing and figured it out. Sorry for bothering you and thank you for your response earlier!

**Comment by shaharido1** [comment]
Hey @Syirrus I also missed the part of adding the fields to the registration tab. Maybe it's worth to add it to the docs, as it's not very intuitive..

**Comment by FF-Ibb-PD** [comment]
How can i add the field i created to my info sidebar?

Is it possible to make this deleteable or changeable by the administrator?
Like I can change a users name and password and but not the custom fields.

**Comment by shaharido1** [comment]
I don't think that you can change it from the GUI (only through the rest API).

**Comment by FF-Ibb-PD** [comment]
I had a look into the pull request and figured out, that you should see the fields if you have `view-full-other-user-info`, which seems not to work with my server right now. 
I can change the custom field i created but it's not possible for me to have insight in them.
Maybe @sampaiodiego could have a look at this issue?

Also: is it possible to declare single fields as public, so that you can choose if fields should be visible for everyone, not just for administrators?

**Comment by localguru** [comment]
Same problem here. Add custom fields to Accounts/Custom Fields, but don't see them in user's profile. view-full-other-user-info is enabled for admin and users.

**Comment by magicbelette** [comment]
Same problem with RocketChat 0.56.0. Users can see/update custom fields in their own profile but it's not displayed for others even with view-full-other-user-info enabled.

Any leads ?

**Comment by lakhandewnani** [comment]
I have a scenario in my case where I need to have a custom field as a list in which I could insert as well as delete elements . Which type of custom field I should create ?

**Comment by vfxpandit** [comment]
Use this syntax to display custom fields in profile 
http://rocketchat/admin/Accounts

Custom Fields to Show in User Info  >> 
` [{"Designation": "designation"}, {"Department": "department}]
`


**Registration >> Custom Fields**
sample json format for add custom fields 

```
{
   "designation": {"type": "text",
       "required": false,
       "minLength": 2,
       "maxLength": 100}, 
   "department": {"type": "text",
       "required": false,
       "minLength": 2,
       "maxLength": 100}
}
```

To update custom fields though Rest API 
` "data": {"name": name, "email": email,  "customFields": {"designation": 'Artist', 'department': 'Modeling'}}}`

**Comment by bilogic** [comment]
> Use this syntax to display custom fields in profile http://rocketchat/admin/Accounts
> 
> Custom Fields to Show in User Info >> `[{"Designation": "designation"}, {"Department": "department"}]`
> 
> **Registration >> Custom Fields** sample json format for add custom fields
> 
> ```
> {
>    "designation": {"type": "text",
>        "required": false,
>        "minLength": 2,
>        "maxLength": 100}, 
>    "department": {"type": "text",
>        "required": false,
>        "minLength": 2,
>        "maxLength": 100}
> }
> ```
> 
> To update custom fields though Rest API ` "data": {"name": name, "email": email, "customFields": {"designation": 'Artist', 'department': 'Modeling'}}}`

can these fields be viewed in the web UI of rocket chat itself?
