### ISSUE TITLE
[performance] Message search in a thread list lead to massive mongodb load

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#23052]
### Description:

All information related to that issue:
https://github.com/RocketChat/Rocket.Chat/pull/23034#issuecomment-906372471
https://github.com/RocketChat/Rocket.Chat/pull/22879
https://github.com/RocketChat/Rocket.Chat/issues/22132
https://github.com/RocketChat/Rocket.Chat/issues/22193

Our deployment uses Russian language. When some user search one Russian letter like `а` or short Russian word like `не` in Message Search box of Theads list then we get massive peak in CPU load of our Primary mongodb node. And in mongodb logs we see very expensive queries like this:

`COMMAND  [conn81431] command rocketchat.rocketchat_message command: find { find: "rocketchat_message", filter: { _hidden: { $ne: true }, $text: { $search: "а" }, rid: "kcKYidB6ZZsm8WZgd", tcount: { $exists: true } }, sort: { tlm: -1 }, projection: { joinCode: 0, members: 0, importIds: 0, e2e: 0 }, limit: 25, returnKey: false, showRecordId: false, lsid: { id: UUID("09d15895-85bd-4b52-b272-34417822a602") }, $clusterTime: { clusterTime: Timestamp(1630059566, 40), signature: { hash: BinData(0, B39A33070D852BF7A31D9740CD17F52B5FCEECC6), keyId: 6947176989316874242 } }, $db: "rocketchat" } planSummary: IXSCAN { _fts: "text", _ftsx: 1 } keysExamined:1522523 docsExamined:3045046 hasSortStage:1 cursorExhausted:1 numYields:11895 nreturned:4 queryHash:2588F27B planCacheKey:C53B46D6 reslen:3315 locks:{ ReplicationStateTransition: { acquireCount: { w: 11897 } }, Global: { acquireCount: { r: 11897 } }, Database: { acquireCount: { r: 11897 } }, Collection: { acquireCount: { r: 11897 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 1472826, timeReadingMicros: 2622 } } protocol:op_msg 8895ms`

and this

`COMMAND  [conn81432] command rocketchat.rocketchat_message command: count { count: "rocketchat_message", query: { _hidden: { $ne: true }, $text: { $search: "а" }, rid: "kcKYidB6ZZsm8WZgd", tcount: { $exists: true } }, $clusterTime: { clusterTime: Timestamp(1630059554, 1), signature: { hash: BinData(0, 7CF4C7FC6A49FBCFC08E225FC462B7103F804BA1), keyId: 6947176989316874242 } }, $db: "rocketchat" } planSummary: IXSCAN { _fts: "text", _ftsx: 1 } keysExamined:1522519 docsExamined:3045038 numYields:11895 queryHash:37B2DC84 planCacheKey:C482CCF4 reslen:170 locks:{ ReplicationStateTransition: { acquireCount: { w: 11897 } }, Global: { acquireCount: { r: 11897 } }, Database: { acquireCount: { r: 11897 } }, Collection: { acquireCount: { r: 11897 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 1688148, timeReadingMicros: 3622 } } protocol:op_msg 12360ms`

There was a very good PR merged https://github.com/RocketChat/Rocket.Chat/pull/18887 that located most expensive operations to secondary mongodb node (which always is idle in our deployment). But as you can see - that search messages in Thread list executed on primary mongodb node and lead to delays in chat messaging for all server users (gray messages).

### Steps to reproduce:

1. Go to chat with threads (more better)
2. Try to search one letter, or short word like `не`
3. Check mongodb logs for long queries and graph for peak

### Expected behavior:

Search should not lead to delays in messaging of all server users.
That issue should be fixed by 2 ways:
1. Locate that search to secondary mongodb node - preferred for us fix method
2. Add some indexes to message collection

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/131113728-0e26b957-1f4e-45c8-a7d2-34776fb2bc6d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.15

### Client Setup Information

- Desktop App or Browser Version: Chrome 92 and 3.4.0
- Operating System: Windows 10

### Additional context

I guess that https://github.com/RocketChat/Rocket.Chat/pull/22879 could be a partly fix for our issue, because I see in logs not one query, but number of same queries (10-20). 
But in fact, even if that expensive queries not sporadically replicated, they still very expensive and need to be much improved.

### Relevant logs:

mongodb logs we see very expensive queries like this:

<details>

```
COMMAND  [conn81431] command rocketchat.rocketchat_message command: find { find: `"rocketchat_message", filter: { _hidden: { $ne: true }, $text: { $search: "а" }, rid: "kcKYidB6ZZsm8WZgd", tcount: { $exists: true } }, sort: { tlm: -1 }, projection: { joinCode: 0, members: 0, importIds: 0, e2e: 0 }, limit: 25, returnKey: false, showRecordId: false, lsid: { id: UUID("09d15895-85bd-4b52-b272-34417822a602") }, $clusterTime: { clusterTime: Timestamp(1630059566, 40), signature: { hash: BinData(0, B39A33070D852BF7A31D9740CD17F52B5FCEECC6), keyId: 6947176989316874242 } }, $db: "rocketchat" } planSummary: IXSCAN { _fts: "text", _ftsx: 1 } keysExamined:1522523 docsExamined:3045046 hasSortStage:1 cursorExhausted:1 numYields:11895 nreturned:4 queryHash:2588F27B planCacheKey:C53B46D6 reslen:3315 locks:{ ReplicationStateTransition: { acquireCount: { w: 11897 } }, Global: { acquireCount: { r: 11897 } }, Database: { acquireCount: { r: 11897 } }, Collection: { acquireCount: { r: 11897 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 1472826, timeReadingMicros: 2622 } } protocol:op_msg 8895ms
COMMAND  [conn81432] command rocketchat.rocketchat_message command: count { count: "rocketchat_message", query: { _hidden: { $ne: true }, $text: { $search: "а" }, rid: "kcKYidB6ZZsm8WZgd", tcount: { $exists: true } }, $clusterTime: { clusterTime: Timestamp(1630059554, 1), signature: { hash: BinData(0, 7CF4C7FC6A49FBCFC08E225FC462B7103F804BA1), keyId: 6947176989316874242 } }, $db: "rocketchat" } planSummary: IXSCAN { _fts: "text", _ftsx: 1 } keysExamined:1522519 docsExamined:3045038 numYields:11895 queryHash:37B2DC84 planCacheKey:C482CCF4 reslen:170 locks:{ ReplicationStateTransition: { acquireCount: { w: 11897 } }, Global: { acquireCount: { r: 11897 } }, Database: { acquireCount: { r: 11897 } }, Collection: { acquireCount: { r: 11897 } }, Mutex: { acquireCount: { r: 2 } } } storage:{ data: { bytesRead: 1688148, timeReadingMicros: 3622 } } protocol:op_msg 12360ms
```

</details>

**Comment by ankar84** [comment]
> we'll have to see if the regex search will have a better or worse impact.

I did try to disable regex search (we have it enabled) on current 3.16.3 and I didn't see any difference.

**Comment by sampaiodiego** [comment]
that setting is misleading :disappointed: turning it off will actually prevent users from using regex.. all searches are made using the text index by default, but end users can use regex by themselves..

**Comment by ankar84** [comment]
> that setting is misleading 😞 turning it off will actually prevent users from using regex.. all searches are made using the text index by default, but end users can use regex by themselves..

yeah, agree with you. It should be commented in more correct details in Admin UI!

**Comment by ankar84** [comment]
And another thing about additions indexes, I have an [answer](https://www.mongodb.com/community/forums/t/need-help-to-improve-some-queries/119125/2?u=anton_karlan) from mongodb forum, it could be useful, I think

Your query counting number of document that matches your query. As you might know you can have only 1 text index per collection. Where as you can have compound index. Looking at your query, i believe below index would be helpful:
```
db.getSiblingDB("rocketchat").rocketchat_message.createIndex({ msg:1, rid:1},{partialFilterExpression:{tcount: { $exists: true }}})
```
Further, If you can change the `_hidden: { $ne: true }` with all other possible value like `_hidden: { $in: [false, null] }` then you can add that field to the index.

**With that you can avoid reading the ~6M document scanning.**

**Comment by sampaiodiego** [comment]
oh, good to know.. we need to evaluate more places where we could use `partialFilterExpression` .. it is still something new to me, but definitely that worth taking a look at.

**Comment by ankar84** [comment]
Closing this with #22132 after update to 3.18.1 - really more smooth mongo server CPU graph and less thread list requests.
Thank you, @sampaiodiego 
And please continue to improve mongodb performance (more proper indexes and other stuff).
