### ISSUE TITLE
Jitsi time-out have 2 separate API endpoint 

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#23063]
### Description:

Jitsi for some strange reason have 2 different API endpoins:
`method.call/jitsi:updateTimeout` - leader of request on our deployment
`video-conference/jitsi.update-timeout` - lots of requests (top 5 on our server)

Here is a 2 issues for me:
1. Why there so much requests for Jitsi (third-party service integrated to Rocket.Chat)
2. Why Rocket.Chat have 2 different API endpoints for Jitsi time-out

### Steps to reproduce:

1. Setup Jitsi integration
2. Setup Rocket.Chat Metrics
3. Check `REST API Calls / Minute` graph

### Expected behavior:

One single API endtping for Jitsi timeout with less amount of requests

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/131327391-3a2994c9-bb6c-4c6c-a5c8-f4fa9c6b90ea.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.15

### Client Setup Information

- Desktop App or Browser Version: 3.4.0 and Chrome 92
- Operating System: Windows 10

### Additional context

No

### Relevant logs:

Sometimes I see a lot of:
`server.js:204 System ➔ error Error starting video call: Error: error-not-allowed`
Maybe it could be related to big amount of such requests.

**Comment by debdutdeb** [comment]
Off-topic: are you all going forward with the 3.18 update? Asking because I still see 3.16.x there.

On-topic: another jitsi issue, ok. I'll check it out and let you know what happens. Thanks ;)

**Comment by ankar84** [comment]
> Off-topic: are you all going forward with the 3.18 update? Asking because I still see 3.16.x there.

Yeah. sure! We are in testing stage.

> On-topic: another jitsi issue, ok. I'll check it out and let you know what happens. Thanks ;)

Yes, but this not critical, just to figure out some things.

**Comment by ankar84** [comment]
Looks like in 3.18.1 question `Why there so much requests for Jitsi` is solved
![image](https://user-images.githubusercontent.com/4023037/133894508-1a5defe6-96b5-4e33-9cf9-b8275f51030b.png)

**Comment by ankar84** [comment]
Closing that issue because of new Video Conf system
