### ISSUE TITLE
Rocket.Chat integrated with FreeScout helpdesk

### ISSUE THREAD

**Issue by freescout-helpdesk** [RocketChat/Rocket.Chat#23072]
We are happy to announce that Rocket.Chat has been integrated with open source [FreeScout](https://github.com/freescout-helpdesk/freescout) helpdesk: https://freescout.net/module/rocket-chat/

If there is somewhere a list of Rocket.Chat integrations maybe Rocket.Chat Team may decide to add this integration there too.

Thanks and keep up the good work. Both open source Rocket.Chat and FreeScout play quite well together.

**Comment by debdutdeb** [comment]
Hi! Thanks! 

Is anyone from your team, on our open server? (https://open.rocket.chat) Do you mind pinging me (at)debdut.chakraborty ? PLEASE do!

I am quite interested to know more about this.

**Comment by freescout-helpdesk** [comment]
Not yet. We'll try to drop a line...
