### ISSUE TITLE
[BUG] New Chat Transfer: Transfer Room transferred the chat to undefined

### ISSUE THREAD

**Issue by cuonghuunguyen** [RocketChat/Rocket.Chat#23073]
### Description:

Transferring room to target agent by apps shows wrong transfer notification in the chat

![image](https://user-images.githubusercontent.com/29362551/131452233-535e8364-43c7-44f1-869b-5aa195a2e8c4.png)

### Steps to reproduce:

1. Transfer Chat to target agent by Apps Engine

### Expected behavior:

Notification shows with target agent name

### Actual behavior:

 `New Chat Transfer: Transfer Room transferred the chat to undefined`

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by debdutdeb** [comment]
Hi 

As replied on open, I've requested Douglas to take a look at the PR. I'm sure he'll look at it soon.

Thanks for the PR again (if I hadn't said already :p)

**Comment by cuonghuunguyen** [comment]
Thank you very much @debdutdeb
