### ISSUE TITLE
Issue with video call

### ISSUE THREAD

**Issue by maik28** [RocketChat/Rocket.Chat#2307]
I've got a problem that If I am starting/joining a video call with another person, I am seeing just myself instead of the other person who joined or started the video call. On the other side/person window he tries throughout to connect with me but it doesn't work, just shows a black screen.

I've already passed the webrtc troubleshooter on both sides and everything was o.k.

Tried it with iceweasel on the one side and firefox on the other side.

**Comment by engelgabriel** [comment]
What version of Rocket.Chat are you using?

**Comment by maik28** [comment]
I'm using version 0.13.0. Once it worked 10 minutes ago, but now it doesn't work again. It was browser to client connection. Now it even doesn't try to connect. I am seeing just myself and on the other windows the same.

**Comment by engelgabriel** [comment]
Please update to the latest version, as we cannot test old versions at this point.

**Comment by maik28** [comment]
Updated Rocket.Chat to version 0.19.0 and nothing changed. Still got the problem that i can't see the other person.

**Comment by maik28** [comment]
Are there any errorlogs that Rocket.Chat uses that I could look up? The standard log (in main.js) doesn't say anything about any errors.

**Comment by engelgabriel** [comment]
Try this on your console:
`WebRTC.instancesByRoomId[Object.keys(WebRTC.instancesByRoomId)[0]].debug = true`

**Comment by maik28** [comment]
Many thanks, It seems that it has repaired itself. It is working now.
