### ISSUE TITLE
Hellow!

### ISSUE THREAD

**Issue by kuzminsa** [RocketChat/Rocket.Chat#23075]
Hi!
При нажатии на пушуведомления в 10ке ничего не происходит. А хотелось бы попадать в диалог автора.
Спасибо пасаны. Обнял.

**Comment by ankar84** [comment]
Привет, @kuzminsa 
По этой баге уже есть репорт https://github.com/RocketChat/Rocket.Chat.Electron/issues/2007

**Comment by debdutdeb** [comment]
Thanks for the response Anton!

I would've asked you anyway to make it out to me :p google translate wasn't much help unfortunately.

Closing this since it's unrelated to this repository.

Sergo, you can add a comment on the electron issue threads, someone will look at it very soon :) 

Thanks.
