### ISSUE TITLE
Question: Is is possible to whitelist servers in federation mode?

### ISSUE THREAD

**Issue by sennewood** [RocketChat/Rocket.Chat#23078]
### Description:

The manual and Admin UI doesn't show any options to whitelist a specific list of servers. The federation mode seems interesting, but we would only allow business parters to join our server - not the whole world.

### Steps to reproduce:

None.

### Expected behavior:

None.

### Actual behavior:

None.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.2
- Operating System: Ubuntu 20.04
- Deployment Method: Docker
- Number of Running Instances: 14
- DB Replicaset Oplog: Yes
- NodeJS Version: Idk
- MongoDB Version: 4.0.x

### Client Setup Information

- Desktop App or Browser Version: Doesn't matter
- Operating System: Doesn't matter

### Additional context

No.

### Relevant logs:

No.

**Comment by ankar84** [comment]
Server whitelisting is on [confirmed next features](https://docs.rocket.chat/guides/administration/administration/settings/federation#features)

**Comment by sennewood** [comment]
Thank you.
