### ISSUE TITLE
[Bug] Mentions of #channels do not work

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#23080]
### Description:

Mentions of #channels do not work. In mobile applications it works correctly.

The bug is present since 3.17.2 and remains in 3.18.0

### Steps to reproduce:

1. #channel does not create hyperlink

### Expected behavior:

Click to go to the channel

### Actual behavior:

No hyperlink is created to go to the channel, only the name is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.4.8

### Client Setup Information

- Desktop App or Browser Version: Web and desktop client.
- Operating System: Any

**Comment by ankar84** [comment]
Not confirm that bug
![image](https://user-images.githubusercontent.com/4023037/131603383-0167fdd2-4c44-4d65-859f-6ad3123a9d49.png)
That's from 3.18.0

**Comment by aleadco** [comment]
@ankar84 This is on the web.
https://user-images.githubusercontent.com/35962168/131606625-8e21f597-5866-45f0-999a-8fdf1568eadf.mp4

In the App
![Screenshot_2021-08-31-23-24-02-961_chat rocket android](https://user-images.githubusercontent.com/35962168/131606929-76eb2610-c1b3-40b8-b6b4-d8abf32bea57.jpg)

This started from 3.17.2
Is there an option that disables the channel mention?

**Comment by aleadco** [comment]
@ankar84 I already found the cause of the error, it appears when the message analyzer is enabled in Administration / Accounts

**Comment by aleadco** [comment]
As soon as I disabled the option the hyperlink was activated
![image](https://user-images.githubusercontent.com/35962168/131608903-df948eed-f0b6-43e7-8bf1-772c776840c3.png)

**Comment by ankar84** [comment]
> @ankar84 I already found the cause of the error, it appears when the message analyzer is enabled in Administration / Accounts

You are totally right!
That issue is related to https://github.com/RocketChat/Rocket.Chat/issues/22280

Someone must take a view to that endless bugs of new parser that meant to be default soon.
@debdutdeb @yashovardhan please pay attention on that.

**Comment by debdutdeb** [comment]
Hmm .. let me think on this. Maybe by the end of this week I can get you *some* answer.

**Comment by aleadco** [comment]
@ankar84 @debdutdeb 
I was also able to confirm that the emojis are altered, I just verified.

![IMG_20210901_011649.jpg](https://user-images.githubusercontent.com/35962168/131616110-83b509db-fca1-46fd-aba9-175984b8a336.jpg)

**Comment by debdutdeb** [comment]
> I was also able to confirm that the emojis are altered, I just verified.

Is this on the mobile only? Any way to reproduce it?

As an update I'm listing all the bugs that are/might be related to this new parser, and will present them to product.

**Comment by aleadco** [comment]
> Is this on the mobile only? Any way to reproduce it?
> 
> As an update I'm listing all the bugs that are/might be related to this new parser, and will present them to product.

@debdutdeb 
It is not a problem on mobile. When message analysis is active, the encoding of some emojis is not related to the mobile app.
- Access via the web from any device and react with 👍 
- Access from the mobile application and react with the same emoji but without pressing on the existing one, you must select it as if you were going to add a new one.

Result:
Two different reactions when they should be the same.

Solution:
I deactivated the message analyzer and the reactions match again.

**Comment by debdutdeb** [comment]
Hmm. I'll check this out. Thank you Alejandro, :)

**Comment by milton-rucks** [comment]
Fixed
