### ISSUE TITLE
Can not get user info in a group direct message

### ISSUE THREAD

**Issue by IvanOpanasiuk** [RocketChat/Rocket.Chat#23096]
### Description:

I create direct message for few users.  After that I can not see the information about the user by link  'See full profile' 

### Steps to reproduce:

1. create group direct message
<img width="733" alt="Снимок экрана 2021-09-02 в 11 10 42" src="https://user-images.githubusercontent.com/15374759/131808347-a68f7972-fcca-4177-9ff8-1b050f645de5.png">

2. Click on 'See full profile'
<img width="1391" alt="Снимок экрана 2021-09-02 в 11 12 23" src="https://user-images.githubusercontent.com/15374759/131808431-89534f87-2c73-4097-a6b6-33aa43af1371.png">
<img width="1000" alt="Снимок экрана 2021-09-02 в 11 18 06" src="https://user-images.githubusercontent.com/15374759/131808476-a689c31e-95db-4a7a-abb3-736cf1b229f0.png">

3. url has changed, but there is no user info
<img width="1792" alt="Снимок экрана 2021-09-02 в 11 18 35" src="https://user-images.githubusercontent.com/15374759/131809853-5e8032fc-9d2d-4c47-b0e6-5918457d9682.png">

### Expected behavior:

I expect to see information about the user

<img width="1782" alt="Снимок экрана 2021-09-02 в 11 21 42" src="https://user-images.githubusercontent.com/15374759/131808928-a2a4c8c1-37af-4fb5-80db-a52ac75a2a58.png">

### Actual behavior:

User information does not appear

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: macOS
- NodeJS Version: 12.22.1
- MongoDB Version: v4.4.0

### Relevant logs:

<img width="1791" alt="Снимок экрана 2021-09-02 в 11 24 45" src="https://user-images.githubusercontent.com/15374759/131809450-b619e703-75cc-4d32-93bf-86cb11379cff.png">

**Comment by IvanOpanasiuk** [comment]
@debdutdeb could you check this case ?

**Comment by IvanOpanasiuk** [comment]
As I understood this is because we are calling user-info but not user-info-group. I fixed this by adding 'direct_multiple' to the 'groups' array of the 'user-info' event in file ./client/views/room/lib/Toolbox/defaultActions.ts
<img width="1005" alt="Снимок экрана 2021-09-02 в 14 08 22" src="https://user-images.githubusercontent.com/15374759/131833318-811ef831-5c8f-4707-a450-a4c5731f1273.png">

**Comment by debdutdeb** [comment]
> @debdutdeb could you please check this case ?

Hey @IvanOpanasiuk ! Sorry for the delay. 

Thanks for reporting this, and I can confirm this is an issue with 3.18.x atm.

I see you've already started tweaking the code base, lmk if you'd like to work on this. We always welcome community contributions :)

**Comment by IvanOpanasiuk** [comment]
Thank you for your answer! :) My solution was only temporary, there is a separate Action to call 'user-info-group' and of course it is better to use it

**Comment by debdutdeb** [comment]
Alright, I'll let the appropriate people know about this issue. Have a nice day!

**Comment by IvanOpanasiuk** [comment]
I would fix it myself, but I didn't find a suitable place. Have a nice day!)

**Comment by grahhnt** [comment]
I have made a fix in pr #24098, the pull needs to be reviewed though
