### ISSUE TITLE
Static Pages

### ISSUE THREAD

**Issue by fodacode** [RocketChat/Rocket.Chat#2309]
is there an easy way to generate lets say /about or /contact pages? I see in the admin to edit home/privacy/terms. 

Also is there a way to make a user profile page, lets say you can find that users info at /u/username or something of that nature. 

thanks for this project it is amazing !!!!!

**Comment by cbrummitt** [comment]
The profile page has name, username, email, password, language. It would be great to have a "Role" and/or "About me" field here.

**Comment by engelgabriel** [comment]
There is an issue for the second part of this issue, so I'll edit the title. #2046

**Comment by cyclops24** [comment]
+1

**Comment by cyclops24** [comment]
@engelgabriel @rodrigok any news about this?

**Comment by sampaiodiego** [comment]
This is something we see you should do on a CMS tool.

Feel free to propose in detail on our [forums](https://forums.rocket.chat) for future consideration as a feature.
