### ISSUE TITLE
[Bug] 4.1.2 does not show the real name of new users in several places.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#23093]
### Description:

The option to use real name is checked from previous versions.

After upgrading to 3.18.0 new registered users do not show real name in several places.

On the top and left side bar the user is shown and the real name should be shown.

### Steps to reproduce:

1. Register a new user manually, also tested with users coming from LDAP

### Actual behavior:

![image](https://user-images.githubusercontent.com/35962168/131789992-1c53729a-6067-4673-b7f8-5174789fc2b0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: wiredTiger
- NodeJS Version: 12.22.1
- MongoDB Version: 4.4.8

### Additional context

@pierre-lehnen-rc and @ankar84

This issue is closely related to #19046 since version 3.9.3. The difference is that it now directly affects the new users who register in the system.

The option **Use real name** is updated correctly, even if the modification comes from LDAP, the only problem is that these values are not shown in the left column and in the title of the chat, however in the messages it is shown correctly.

**Comment by aleadco** [comment]
@ankar84 Hello again

I reproduce the steps
1- Delete registered user in RC
2- Enabled "Use Real Name" (since we deployed RC). /instancia.rc/admin/Layout/# User Interface
3- Login with a new user.
4- The real name is correctly loaded in the information, personal, in the chat window, in the messages you send, but not at the top or in the list of conversations.

It was tested creating a manual user and another one coming from LDAP, with both the result is the same.
I insist that this came after updating to 3.18.0 and there is a very related antecedent and detected by several members of the community in #19046 but at that time we thought it was related to the attribute change, however it was updated correctly. Users at that time still have not updated the real name in the side and top view, however those who entered after the attribute change, were registered correctly. Now the opposite happens, new users since they register no longer show the real name in the side and top view.

![image](https://user-images.githubusercontent.com/35962168/132149840-4686f42a-5aa2-4dcc-8428-02eea829f968.png)

![image](https://user-images.githubusercontent.com/35962168/132149980-9bc350d8-cf6a-4501-b1ca-665292f03528.png)

![image](https://user-images.githubusercontent.com/35962168/132150148-d81a9723-3cf0-4a3c-b7a5-be6ff8ba3c5c.png)

**Comment by aleadco** [comment]
For example, these two users have not been successfully updated since #19046 
![image](https://user-images.githubusercontent.com/35962168/132150804-42a15e2c-fd18-44da-bec9-d8f761230067.png)

Back then we used `FirstName` as real name attribute and then we update to displayname where we notice the error.
As time `DisplayName` was updated correctly in the window but the side and top view did not.
![image](https://user-images.githubusercontent.com/35962168/132151355-530c3202-448a-400e-b92c-a6f562f4403a.png)

**Comment by aleadco** [comment]
By the way, here I leave the personal information view of the test user where the real name can be correctly seen.
![image](https://user-images.githubusercontent.com/35962168/132151418-b3b29796-e372-44f9-ba40-6cee7f3767dc.png)

**Comment by aleadco** [comment]
@ankar84  +1 #23051

**Comment by aleadco** [comment]
@ankar84  However, something very interesting happens, which shows me that there is some process that is not running correctly.

If I allow the user to change his name (by default we have it disabled in our RC) and we modify it, as it turns out that it updates correctly in all places.
![image](https://user-images.githubusercontent.com/35962168/132158564-1b8bce0c-e201-466a-b19d-bff2c95410ae.png)

But when that user leaves the session and re-enters, he takes the LDAP configuration correctly and again stops updating the chat list and the upper part.
![image](https://user-images.githubusercontent.com/35962168/132159196-80fce7aa-1d3f-480d-8204-a5390807a2be.png)

**Comment by Gummikavalier** [comment]
I'm seeing this new real names issue with newly created direct room members too (on 3.18.1). :(

**Comment by Gummikavalier** [comment]
Tested in RC 3.18.1. I created a new user account (name) called teppotelevisio, with real name (fname) called Teppo Televisio.

When the new user contacts old user, in Mongo's rocketchat_subscription collection the names are written as:

"fname" : "teppotelevisio"
"name" : "teppotelevisio"

While the old users are written correctly:
"fname" : "Joe Smith"
"name" : "jsmith"

Because of this, the person starting any completely new direct room discussion sees the other recipient correctly, while the recipient sees the contacting person only with their username. The other recipient's real name is simply not written correctly into the channel's subscription in the initial room creation phase.

**Comment by Gummikavalier** [comment]
While waiting for RC 4.0 we ended up working around this issue for now with the javascript mentioned by `bhdung` in the issue https://github.com/RocketChat/Rocket.Chat/issues/19046

**Comment by ankar84** [comment]
Confirm that issue at 3.18.1
And so strange - some chats creates with Real Name and some chats creates with username (short name).
Both chats was started today (I didn't have chat with both that users before) - and one with username in sidebar an header (wrong). and the other with Real Name in sidebar and header (right)

**Comment by budakovda** [comment]
I wrote a script that collects information on irrelevant records, and then updates them on primari node in portions.
Thanks to @bhdung  for the required [operation](https://github.com/RocketChat/Rocket.Chat/issues/19046#issuecomment-730822814).

**Comment by rmeissn** [comment]
To update this thread (RocketChat 4.1.2):
I haven't tested creating new users, but I still see user names in some places, real names in other places, as pointed out in https://github.com/RocketChat/Rocket.Chat/issues/23093#issuecomment-913282190
My RC instance isn't connected to any LDAP and all users were created via the administration view manually (using different ifferent RC versions over time).

**Comment by radiokang** [comment]
It seems that the real name of 'me' is not retrieved while creating the room.
**Change**
`const me = Users.findOneById(userId, { fields: { username: 1 } });`
**to**
`const me = Users.findOneById(userId);`
in server/methods/createDirectMessage.js
should be able to fix this issue.

**Comment by Gummikavalier** [comment]
I confirm that a hand edit at `bundle/programs/server/app/app.js` for the part @radiokang found out seems to fix the issue for new direct channel names in RC 4.1.2.

**Comment by aleadco** [comment]
I have updated the title since in RC 4.1.2 the error still persists.

**Comment by CvH** [comment]
@sampaiodiego
updating to 4.3.1 fixed the issue for new users I had never contacted, but all users that I contacted still have just displayed the username

likewise it is somewhere kind of cached ?

**Comment by ankar84** [comment]
> but all users that I contacted still have just displayed the username

You can use @budakovda [script](https://github.com/RocketChat/Rocket.Chat/issues/23093#issuecomment-927022370) to fix all existing DMs

**Comment by mddvul22** [comment]
That script appears to no longer be available.  Hopefully @budakovda can make it available again?

**Comment by CvH** [comment]
> You can use @budakovda [script](https://github.com/RocketChat/Rocket.Chat/issues/23093#issuecomment-927022370) to fix all existing DMs

Shouldn`t RC provide some script or at least some doc how to do it?
I guess every RC user/server was effected from that bug so the damage is already there and just the problem is fixed for the future and not for the past.

**Comment by CvH** [comment]
@sampaiodiego just to clarify the issue is just partly solved, there is still no way to repair the broken data that still exists and didn't get updated

the linked scripts are not avaible anymore and the "commands" floating around (https://github.com/RocketChat/Rocket.Chat/issues/18469#issuecomment-1005608333 https://github.com/RocketChat/Rocket.Chat/issues/19046#issuecomment-730822814) are not working (or needs something that is not explained)

**Comment by ankar84** [comment]
> @sampaiodiego just to clarify the issue is just partly solved, there is still no way to repair the broken data that still exists and didn't get updated

I guess that broken chats should be fixed by some migration like it was with other similar issues.

**Comment by Gummikavalier** [comment]
Search bar full names issue was fixed in 4.7.1 by https://github.com/RocketChat/Rocket.Chat/pull/25471

**Comment by seregasoft** [comment]
Fixed in 4.7.1 for Desktop app. But on mobile Android 4.27.1 and iOS problem still exists.

**Comment by Gummikavalier** [comment]
With the web client broken real names can still be found at least at:

- The new direct messages channel `You have joined a new direct message with`-location.

- Reactions. Old message template shows them after refresh of the page until the reactions get updated again with new reactions. New message template always fails to show real names.
