### ISSUE TITLE
New profile picture doesn't appear on profile page when selected

### ISSUE THREAD

**Issue by robertfromont** [RocketChat/Rocket.Chat#23105]
### Description:

When changing your profile picture, selecting the local file blanks out the old picture and doesn't show the new one. It doesn't appear until you save the changes and return to a room.

### Steps to reproduce:

1. Click my avatar on the top left
2. Click _My Account_
3. Click the _Upload_ button next to the profile picture
4. Select a local file

### Expected behavior:

The profile picture on the left changes to the selected file

### Actual behavior:

The profile picture disappears, so the user thinks they haven't selected a file and doesn't know what to do next.

Little do they know that if they click _Save changes_ on the top right, even though the profile picture stays blank, their profile is updated with the new picture.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: RHEL8
- Deployment Method: manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Firefox 91.0.2 (64-bit)
- Operating System: Ubuntu 20.04.3

### Relevant logs:

In the browser log I'm seeing:

```
Content Security Policy: The page’s settings blocked the loading of a resource at blob:http://the.host.name.of.our.rc/594f3d0a-4df7-4fca-aa6d-6fbef0918aae (“img-src”).
```

**Comment by debdutdeb** [comment]
Hi

I can confirm the issue.

Thanks for reporting this. I'll pass this to the product team to look at.

**Comment by chickbooman1** [comment]
HI , i just fix the problem.
app>cors>server>cors.js 
change line 47 ' img-src * data: ' into 'img-src * data: blob:'

**Comment by parannoide** [comment]
having the same problem.
