### ISSUE TITLE
E2E encrypted messages are store as plaintext in db?

### ISSUE THREAD

**Issue by yourikoeman** [RocketChat/Rocket.Chat#23113]
# ISSUE FOUND: PLS READ FIRST COMMENT

Short unrelated message: Great software, very grateful for all you guys's work on it :)
### Description:
The messages that are supposed to be e2e encrypted are accessible on the database as plain text. This may indicate something is going terribly wrong security wise.

But when i directly query the db of my rocketchat instance i can read the plain text messages that are supposed to be e2e encrypted

### Steps to reproduce:
1. Make a new channel
2. Enable E2E encryption
3. Send a message
4) Go the the db of the instance
5) Search for the record of the message in the db

### Expected behavior:
What i would expect is the following:
1. encryption key generated on client
2. all comms are encrypted on the client
3. encrypted messages send to server
4. server distributes encrypted messages
5. clients decrypt said messages

### Actual behavior:
The messages seem to reach the server unencrypted and are saved on the instance's db as plaintext

### Server Setup Information:

- Version of Rocket.Chat Server: `3.17.2`
- Operating System: `ubuntu 20.04`
- Deployment Method: `Ubuntu appliance templates (during installation)`
- Number of Running Instances: `1`
- DB Replicaset Oplog: `(oplog Enabled)`
- NodeJS Version: `v12.22.1`
- MongoDB Version: `3.6.14 / wiredTiger`

### Client Setup Information

- Desktop App or Browser Version: `Firefox 91.0.2 (64-bit)`
- Operating System: `Ubuntu 20.04`

### Additional context
Some context that may be of importance:
- I am currently the only user on this instance.
- These messages are in a channel i am the only member of
- These messages are sent by myself (the "root" user)

#### These are the documents found in the database (in reverse chronological order).
```
{ "_id" : "QMbDSaM75GeaaZuSx", "rid" : "pqxTSLtGK8SPNqitx", "msg" : "not encrypt?", "ts" : ISODate("2021-09-04T18:23:16.233Z"), "u" : { "_id" : "fNSdSXkJ6dGQM6kMY", "username" : "youri", "name" : "youri" }, "urls" : [ ], "mentions" : [ ], "channels" : [ ], "md" : [ { "type" : "PARAGRAPH", "value" : [ { "type" : "PLAIN_TEXT", "value" : "not encrypt?" } ] } ], "_updatedAt" : ISODate("2021-09-04T18:23:16.247Z") }
{ "_id" : "sAbzqpLfAac5XHhxZ", "rid" : "pqxTSLtGK8SPNqitx", "msg" : "hello", "ts" : ISODate("2021-09-04T18:22:52.804Z"), "u" : { "_id" : "fNSdSXkJ6dGQM6kMY", "username" : "youri", "name" : "youri" }, "urls" : [ ], "mentions" : [ ], "channels" : [ ], "md" : [ { "type" : "PARAGRAPH", "value" : [ { "type" : "PLAIN_TEXT", "value" : "hello" } ] } ], "_updatedAt" : ISODate("2021-09-04T18:22:52.816Z") }
{ "_id" : "MgZXMgBcCFF7NhpGk", "t" : "room_e2e_enabled", "rid" : "pqxTSLtGK8SPNqitx", "ts" : ISODate("2021-09-04T18:16:08.953Z"), "msg" : "youri", "u" : { "_id" : "fNSdSXkJ6dGQM6kMY", "username" : "youri" }, "groupable" : false, "_updatedAt" : ISODate("2021-09-04T18:16:08.953Z") }
```

**Comment by yourikoeman** [comment]
Just after i typed this up  i found the issue that has occurred, it is however something that i think might be of importance for you to be aware of. 

When running rocketchat from any browser The `window.crypto.subtle` is disabled on any site where the browser consideres the context insecure `(http) or something fishy going on with the cert`. This results in the client not encrypting any messages. 

You might want to prevent sending the messages or notify users of this in the UI of the app. Since users not using https can still want E2E encryption.

**Comment by reetp** [comment]
Thanks for reporting this.

Someone will take a look in due course.

In the meantime, as per the bug reporting guidelines, can you please test this on the latest code (currently 3.18.1)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
