### ISSUE TITLE
[Teams] several teams should autojoin the same channel

### ISSUE THREAD

**Issue by erdkinder** [RocketChat/Rocket.Chat#23125]
Hello,

I was wondering, if it would be possible to add an (existing) channel as a team-channel to more than one team!?
I wanted to _autojoin_ more than one team to join the same channel, because there will be broadcasted informations relevant for several teams.

Would be great to make this possible. At the moment it seems, if a channel is made a team-channel, I can't add it to another team.

**Comment by debdutdeb** [comment]
Hi

This feature had been requested previously by our community. 

https://github.com/RocketChat/feature-requests/issues/461

There is no timeframe for this yet, but even if it gets added, it'll probably be an enterprise-only feature. 

Thanks.
