### ISSUE TITLE
Add Galaxy support

### ISSUE THREAD

**Issue by dcworldwide** [RocketChat/Rocket.Chat#2313]
Is Galaxy fully supported? I'm looking to run RC on galaxy with multiple containers.

**Comment by Sing-Li** [comment]
@dcworldwide 

Great question!   We routinely run RC with multiple containers - so that works no problem.

But Galaxy?  Please try and let us know.  If it doesn't work, we'll fix it.   Thanks.

**Comment by engelgabriel** [comment]
Hi @dcworldwide, we tested a week ago and it worked. Please open a new issue if you have any problems.

**Comment by dcworldwide** [comment]
Will test and let you know how it goes. Thanks guys. Great work
