### ISSUE TITLE
Cannot use the Desktop Client to connect to a Heroku instance

### ISSUE THREAD

**Issue by shanecoughlan** [RocketChat/Rocket.Chat#2314]
Your Rocket.Chat version: 0.19.0

I set up a test instance on Heroku at https://empowerpeople.herokuapp.com. It works fine to log-in by the web but when I try to access it via the desktop client I get an error saying "Not a valid instance URL."

I can't find any documentation about why going to Rocket.Chat > Change Server and placing the Heroku ROOT_URL https://empowerpeople.herokuapp.com would return an error. 

This may be related to issue #1352 [sandstorm] Mobile and Descktop clients can't connect to Sandstorm RC grain.

<img width="1000" alt="screen shot 2016-02-24 at 10 59 02" src="https://cloud.githubusercontent.com/assets/3616071/13273664/8163af84-dae8-11e5-9a6b-a091023cbe4d.png">

**Comment by brylie** [comment]
This issue may be related to the SSL certificate. I.e. other users are experiencing this problem when using a self-signed HTTPS certificate or one from [LetsEncrypt](https://letsencrypt.org/).

**Comment by niktrix** [comment]
@brylie  is there any workaround for this ?

**Comment by Sing-Li** [comment]
@shanecoughlan @niktrix  -  Please make *absolutely* sure you are using the latest 1.0 version of the desktop client -->  download here https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/v1.0.0

@shanecoughlan -  I've just tested with your Let's Encrypt SSL Heroku site with the above version -- and it worked fine.

**Comment by engelgabriel** [comment]
You need the version 1.0 of the Desktop Client, and looking at your screenshot, you are using an old version.

**Comment by shanecoughlan** [comment]
Thank you @Sing-Li and @engelgabriel.  Updating from the Desktop Client from version 0.0.9 to 1.0.0 fixed the issue and I can log-in to the private server as expected.

As a side note, the Rocket.Chat Desktop Client has no update notification. It may be useful to include it as a future enhancement to help people stay up to date. :)

Regards

Shane

**Comment by engelgabriel** [comment]
We just submitted the Decktop Client to the Mac App Store, so it will the
update tool. Later we will do the same for other platforms

>

-- 
Sent from Mobile

**Comment by shanecoughlan** [comment]
You guys rock!
