### ISSUE TITLE
[jitsi] Call icon in room shows that call is going, but in fact there is no call for that room

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#23143]
### Description:

After https://github.com/RocketChat/Rocket.Chat/pull/22277 by @pierre-lehnen-rc whole Jitsi and Rocket.Chat integration behave much and much better! Most important thing - that PR fixed annoying spam **Click to Join!** buttons when someone didn't close call window.

But now Jitsi integration is still not perfect.
Our users now comply about next Jitsi problem. Sometimes (not always) RocketChat thinks that previous Jitsi call is still going and when user click telephone icon to start a new call - **Click to Join!** button not send to that chat.

We teach users this workaround - in case of that problem just say in chat `@all please start call right now by pressing call icon`

### Steps to reproduce:

1. Have an ended Jitsi call in some chat
2. There is no call in that chat at that moment
3. Call icon shows exclamation mark, like call is going on
4. Try to start a call and expect to see **Click to Join!** button
5. No **Click to Join!** button when you start call

### Expected behavior:

RocketChat must get call status properly. 
If call is ended - that call icon should be without exclamation mark and new call should generate **Click to Join!** button in chat.
If call is going on - call icon should be with exclamation mark and new call should not generate **Click to Join!** button in chat but should open call that is going.

### Actual behavior:

Here is call icon, that shows call is going on, but in fact, there is no actual call
![image](https://user-images.githubusercontent.com/4023037/132456546-d231757f-75c7-4cb6-ae8c-2975d608d5e0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14

### Client Setup Information

- Desktop App or Browser Version: Desktop client 3.2.3 and 3.5.1, Chrome 92, Mobile client 4.13.0 and 4.19.0
- Operating System: Windows 10 and Android 11

### Additional context

Jitsi server version [2.0.6173 (2021-08-16)](https://github.com/jitsi/jitsi-meet-release-notes/blob/2b84eec8ec1c48f76b178e697a2110b0e0239655/CHANGELOG-WEB.md#206173-2021-08-16)

### Relevant logs:

That could be related, I see in logs a lot (2,878 hits in 4 hours) of these entries:
```
Exception while invoking method jitsi:updateTimeout Error: Invalid user [error-invalid-user]
```
So, this could be related to https://github.com/RocketChat/Rocket.Chat/issues/22256 (or maybe not)

**Comment by ankar84** [comment]
And in some case again Click to Join! buttons appears in going call
![image](https://user-images.githubusercontent.com/4023037/132830351-810cf73b-0d79-4179-be39-e2cb4bab9b63.png)

**Comment by sandreddu** [comment]
We have the same issue. Rocket.Chat server version 4.3.1. Any idea of the reasons of such behavior?

**Comment by ankar84** [comment]
fixed since 5.X
