### ISSUE TITLE
Problem with integrations

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#2315]
When using the integration in the administration page, the url generated is throwing a message 

````    
{
  "status": "error",
  "message": "You must be logged in to do this."
}

**Comment by pavankumarkatakam** [comment]
I just entered channel, post as and all required fileds in the admin->integrations, so i got a url `https://chat.somthing.com/hooks/jcETf5Xpfiuo9oyHs/Y2wueEwq6jge7zDjA/6Beycc8GAx2HajTN6DXeGNunNFTYCmglpSg%2BFOkCT%2Bs%3D` , but when i use that url to post from curl command it is saying that the error message

````
{
  "status": "error",
  "message": "You must be logged in to do this."
}

**Comment by graywolf336** [comment]
Did you save the integration? As it's not valid until you click the save
button.

**Comment by pavankumarkatakam** [comment]
Hi @graywolf336 , After saving the data only i got the url, token and an curl example.

**Comment by pavankumarkatakam** [comment]
When debugging, I just deleted the old one and created the new incoming webhook, its working now but how do i translate the gitlab webhook data to rocket chat incoming one. For now im getting the message from gitlab but rocket don't know how to show it correctly.

**Comment by engelgabriel** [comment]
This will be done with the new option to add a parser script to integrations

**Comment by pavankumarkatakam** [comment]
Oh, i think we want to wait for it?

**Comment by engelgabriel** [comment]
Yes, we will work on this today, bare with us.

**Comment by pavankumarkatakam** [comment]
Hi @engelgabriel , Any progress on this?

**Comment by engelgabriel** [comment]
Depends on #2426

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by engelgabriel** [comment]
Now on version 0.22.0 you can use the custom scripts to process the payload

**Comment by engelgabriel** [comment]
The sample script will be done on issue https://github.com/RocketChat/Rocket.Chat/issues/2367
