### ISSUE TITLE
Copy/Paste 3.18.1 not working

### ISSUE THREAD

**Issue by AndreySemenov1** [RocketChat/Rocket.Chat#23155]
### Steps to reproduce:

1. Make screenshot
2. Try to paste in chat
3. Nothing happens

### Server Setup Information:

Version of Rocket.Chat Server: 3.18.1
Operating System: RHEL
Deployment Method: tar
Number of Running Instances: 2
DB Replicaset Oplog: +
NodeJS Version: v12.18.4
MongoDB Version: 4.4
Proxy: nginx
Firewalls involved: -

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows

**Comment by ankar84** [comment]
Not confirm that issue. Copy and paste screenshot works perfect on 3.8.0. and 3.8.1
Here is a screencast
![copy-paste](https://user-images.githubusercontent.com/4023037/132796784-c9bf2804-1e50-4991-9caa-a167c8175b17.gif)

Try to refresh you client via CTRL+R
Check general file exchange operability in RC
Try to restart both instances.

**Comment by AndreySemenov1** [comment]
After rebuilding the application, everything worked.
