### ISSUE TITLE
Mime types for .bz2 doesn't work.

### ISSUE THREAD

**Issue by mate-dev** [RocketChat/Rocket.Chat#23167]
**In RocketChat desktop app, can't add mime type for .bz2 files to Accepted Media Types
Correct mime type for .bz2 is application/x-bzip2**
This is my added media types:
`application/x-compressed,application/x-compress,multipart/x-tar,applicaton/x-gtar,application/x-www-form-urlencoded,application/x-tar-gz,application/x-compressed,application/x-gzip,application/tar+gzip,application/tar,application/x-7z-compressed,application/x-gzip,application/x-gtar,application/x-tgz,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.text,application/x-7z-compressed,text/x-diff,image/*,audio/*,video/*,application/gzip,application/json,application/zip,application/x-tar,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/x-rar-compressed,application/octet-stream,application/zip,application/octet-stream,application/x-zip-compressed,multipart/x-zip,application/x-gzip,application/x-bzip2, application/x-tgz,application/x-gtar,application/g-zip,application/x-bz2,application/bzip,application/x-stuffit`

RocketChat Version 3.14.0

**Comment by debdutdeb** [comment]
Hi, thanks for reporting this.

Please fill the bug template, and also update to the latest version and test on that before opening an issue.

For more information, read https://docs.rocket.chat/getting-support/asking-for-help

Thanks.
