### ISSUE TITLE
Admin Can't See logs, [always throw error]

### ISSUE THREAD

**Issue by raza2022** [RocketChat/Rocket.Chat#23174]
### View Logs Page always throw Error

Whenever admin go to the view logs page, logs can't be rendered properly, it always throws an error 
`Cannot read property 'sort' of undefined`

### Steps to reproduce:

1. just clone the developer branch
2. login with an admin account
3. go to Administration -> View Logs

### Expected behavior:

Admin Should access the actual logs

### Actual behavior:

Empty Page with error message `Cannot read property 'sort' of undefined`

![test](https://user-images.githubusercontent.com/5462788/132955655-08c66b87-a2f9-42d6-ab1b-b03d202cbd06.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.0-develop
- Operating System: 
- Deployment Method: local development server
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 - x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Ubuntu 18.04.5 LTS

**Comment by debdutdeb** [comment]
Hi, thanks for testing the development version ! It's really great to see this. 

I just tested it myself, and seems to be a legit bug. I'll see if internally our team knows about this or not. Either way, I'll pass this to product!

**Comment by ankar84** [comment]
I guess fix prepared in https://github.com/RocketChat/Rocket.Chat/pull/23194

**Comment by sampaiodiego** [comment]
Closed by #23194
