### ISSUE TITLE
low quality images presented to mobile clients

### ISSUE THREAD

**Issue by frossmant** [RocketChat/Rocket.Chat#23177]
### Description:

Uploaded images on rocket.chat server will be compressed and shown to the extreme on iOS clients (maybe other mobile clients as well).

All images looks correct when using Desktop client but looks completely useless when using mobile so it seems to be compressed to save bandwidth ? 

This issue has started since a couple of weeks or maybe a month ago. Did not have this problem before. Running two different rocket.chat servers both with the same problem.

Feels like some changes from a version upgrade have caused this. File upload Size has been set to 20971520 bytes so that should be enough.

### Steps to reproduce:

1. upload image on random channel from desktop/mobile client
2. look at image on desktop client
2. look at image on mobile client

### Expected behavior:

the image should have the same quality on both desktop and mobile client.

### Actual behavior:

the image presented to the mobile client is so compressed/resized it looks terrible, on the desktop client it looks ok.

these are the resolutions of the image when downloading from mobile/desktop clients
**desktop** 3024x4032
**mobile**  135x180

the resolution shown to the mobile clients is what I would call a thumbnail :)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: openSUSE Leap 15.2
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v12.18.4
- MongoDB Version:3.6.8 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop and Mobile, both latest versions
- Operating System: macOS, iOS

### Additional context

File Upload Size: **20971520**
Rotate images on upload: **true** (have tried to disable this when testing, makes no difference)
Enable image thumbnails to save bandwith: **false** (tried to disable this to check if this makes any difference)

Storage Type: GridFS

### Relevant logs:

Do not have any relevant logs.

**Comment by ankar84** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3364

**Comment by frossmant** [comment]
Ah looked around but apparently missed that there already was an issue placed for this problem. Im closing this issue.
