### ISSUE TITLE
New Relic integration

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#2318]
Really important for us. I don't see Atlassian working on it, is anybody else doing so?

**Comment by engelgabriel** [comment]
you mean to receive NewRelic updates?

**Comment by engelgabriel** [comment]
You can just go to New Relic, and configure is as a Slack integration, but point to your Rocket.Chat instance.

![image](https://cloud.githubusercontent.com/assets/1000217/13299126/85072834-db18-11e5-80cc-b6810cfc65ee.png)

**Comment by elboletaire** [comment]
It seems that newrelic changed this, and there's no "Slack" option right now?

https://newrelic.com/connect/details#slack

Seems to be something from slack side instead of from new relic...
