### ISSUE TITLE
Mismatch sender ID error for push

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#2319]
Well i have created the project in the google developers console and activated the Server key to get the API Key, and i thought the project number is the sender ID and updated that thing to rocket chat administration but when testing the push by pressing `Send a test push to my user` it is working but when i see the logs it is saying that 
````
ANDROID: Result of sender: {"multicast_id":4869915690611156000,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}

**Comment by engelgabriel** [comment]
You need to restart the Rocket.Chat server

**Comment by pavankumarkatakam** [comment]
Actually im using Docker, I just restarted the container is it not sufficient, i want to restart server by clicking the button in admin panel.

**Comment by pavankumarkatakam** [comment]
Ok i restarted the server but the same problem, first time clicking the `Send a test push to my user`  producing the green toast that it is success, but when resend it again it is saying that the user not have tokens.

**Comment by pavankumarkatakam** [comment]
Hi, one thing I want to mention is I only have android project id and api jey. But no ios related things is this make the error for mismatch id.

**Comment by pavankumarkatakam** [comment]
Hi, I update to the latest software, but not getting the  mobile push notifications here is my logs:

```
I20160324-17:27:23.777(0) Push: Send message "@pavankumar" via query { userId: 'Y2wueEwq6jge7zDjA' } 
I20160324-17:27:23.780(0) send to token { gcm: 'fe43keU2Dww:APA91bG2yqQzMBpzWuZI7X4XGrIvMkb99pbeTvwLebzg7_517VjHrRNw0z_HIMv3NJTDvjeutL74Tk4MXQiIBGGN4IqdvAExWzoBYpGlvMDwI5RV1ID_saQxAMwHPe25kCW4lni4I8nO' } 
I20160324-17:27:23.781(0) sendGCM [ 'fe43keU2Dww:APA91bG2yqQzMBpzWuZI7X4XGrIvMkb99pbeTvwLebzg7_517VjHrRNw0z_HIMv3NJTDvjeutL74Tk4MXQiIBGGN4IqdvAExWzoBYpGlvMDwI5RV1ID_saQxAMwHPe25kCW4lni4I8nO' ] { _id: 'h2kmAquaLbPKT7w8G',   createdAt: Thu Mar 24 2016 17:27:23 GMT+0000 (UTC),   createdBy: '<SERVER>',   from: 'push',   title: '@pavankumar',   text: 'This is a push test messsage',   sound: 'chime',   apn: { text: '@pavankumar:<br>This is a push test messsage' },   query: { userId: 'Y2wueEwq6jge7zDjA' } } 
I20160324-17:27:23.783(0) Create GCM Sender using "blahblahvlah" 
I20160324-17:27:23.784(0) A:Send message to: fe43keU2Dww:APA91bG2yqQzMBpzWuZI7X4XGrIvMkb99pbeTvwLebzg7_517VjHrRNw0z_HIMv3NJTDvjeutL74Tk4MXQiIBGGN4IqdvAExWzoBYpGlvMDwI5RV1ID_saQxAMwHPe25kCW4lni4I8nO 
I20160324-17:27:23.787(0) Push: Sent message "@pavankumar" to 0 ios apps 1 android apps 
I20160324-17:27:23.789(0) Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet... 
I20160324-17:27:23.989(0) Unauthorized 
I20160324-17:27:23.989(0) ANDROID: Result of sender is null 
```

**Comment by pavankumarkatakam** [comment]
Its still not working for me Im using the latest one, but getting the another error

```
I20160409-11:25:44.996(0) Push: Sent message "@pavankumar" to 0 ios apps 1 android apps 
I20160409-11:25:45.044(0) Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet... 
I20160409-11:25:45.232(0) ANDROID: Result of sender: {"multicast_id":9177000974183885000,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"NotRegistered"}]} 
```

**Comment by engelgabriel** [comment]
Have you compiled your own mobile clients as well? They also need to be build with your own ID

**Comment by pavankumarkatakam** [comment]
I didn't understand building with own ID. please explain ,,,,I'm using the app in play store and added my server address

**Comment by engelgabriel** [comment]
If you are using our mobile app form the play store, the only way to make push notifications work, is using the pre-configured gateway.
