### ISSUE TITLE
LDAP sync

### ISSUE THREAD

**Issue by shahar3012** [RocketChat/Rocket.Chat#232]
Hi,
I believe it will be great to have a way to sync user inforamtion such as display name and avatar (image) from the Active Directory. 

This feature has to do ldap queries to fetch the user data.
The data fetching can be done when the user is connected to Rocket.Chat for the first time after the authentication - SSO and auto creation of users.

Also, there should be some settings for the LDAP connection and an option to choose the query field (for example sAMAccountName, userPrincipalName) in a text input.

**Comment by hjf288** [comment]
What help is required with this?

I'm not familiar with JS and Meteor but I've worked with quite a bit of LDAP.

**Comment by engelgabriel** [comment]
Depends on #222

**Comment by engelgabriel** [comment]
Lets get some help from https://github.com/sscpac/chat-locker/issues/45

**Comment by marceloschmidt** [comment]
@rodrigok you've done some work on LDAP lately. Was this issue approached? Can we close it?

**Comment by rodrigok** [comment]
We are not retrieving any data from LDAP for user profile.

**Comment by blaskovicz** [comment]
:+1: for this feature, especially for pulling the email into the user account once a bind has completed.

**Comment by blaskovicz** [comment]
Doesn't not pulling the email also break any emailing settings (ie no users will get emailed)?

**Comment by rodrigok** [comment]
@blaskovicz yes, but we don't have email notifications yet.

**Comment by gmsecrieru** [comment]
I have proposed a JSON mapping between LDAP field and RocketChat fields (`name` and `email` as this point for security reasons) at #1236 . Although it does not import Avatars at this point, please review and let me know if that suits your current needs :)

**Comment by gmsecrieru** [comment]
I believe we can close this one since #1236 was merged.
