### ISSUE TITLE
Compress Pictures after Upload

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#2321]
Hey Guys,

is there an option to compress pictures after the upload is finished? So some bandwith is saved for other users?

How are the pictures saved if i use the mongo db and rocketchat docker container? In the mongodb instance?

Thanks in advance!

TheReal

Your Rocket.Chat version: 0.19.0

**Comment by geekgonecrazy** [comment]
Related to: #1988

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #1988.

Cheers
Thomas
