### ISSUE TITLE
Unable to build Rocket Chat 3.18 using meteor build command

### ISSUE THREAD

**Issue by jyothikadiri** [RocketChat/Rocket.Chat#23217]
We are trying to build RocketChat 3.18 using meteor build --directory ../ouput .  Observing the below errors

### Expected behavior:

meteor build --directory ../output 

should generate output bundle.

### Actual behavior:

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
The system cannot find the path specified.   /
npm WARN @nivo/line@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/annotations@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/axes@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/colors@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/core@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/legends@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/voronoi@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/core@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @rocket.chat/eslint-config@0.4.0 requires a peer of eslint@^4.19.1 || ^5.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of @typescript-eslint/parser@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN create-react-context@0.3.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-prettier@8.3.0 requires a peer of eslint@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN pdfjs-dist@2.8.335 requires a peer of worker-loader@^3.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN preact-i18nline@2.0.0 requires a peer of preact@^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN prometheus-gc-stats@0.6.2 requires a peer of prom-client@>= 10 < 12 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recompose@0.30.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-order@2.2.1 requires a peer of stylelint@^9.10.1 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package eslint-plugin-import is included as both a dev and production dependency.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
The system cannot find the path specified.
npm WARN @nivo/line@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/annotations@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/axes@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/colors@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/core@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/legends@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/voronoi@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/core@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @rocket.chat/eslint-config@0.4.0 requires a peer of eslint@^4.19.1 || ^5.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of @typescript-eslint/parser@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN create-react-context@0.3.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-prettier@8.3.0 requires a peer of eslint@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN pdfjs-dist@2.8.335 requires a peer of worker-loader@^3.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN preact-i18nline@2.0.0 requires a peer of preact@^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN prometheus-gc-stats@0.6.2 requires a peer of prom-client@>= 10 < 12 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recompose@0.30.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-order@2.2.1 requires a peer of stylelint@^9.10.1 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package eslint-plugin-import is included as both a dev and production dependency.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^
{
  message: "EPERM: operation not permitted, unlink 'C:\\RCCC\\.meteor\\local\\plugin-cache\\ecmascript\\0.15.1\\45c9ece603a1a088a265dc87a91860fad95dec52.json'",
  info: {
    file: 'packages/ecmascript/ecmascript.js',
    line: undefined,
    column: undefined,
    func: undefined
  },
  stack: 'undefined\n' +
    ' => awaited here:\n' +
    '    at Promise.await (C:\\Users\\nkadiri\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.2.1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\meteor-promise\\promise_server.js:60:12)\n' +
    '    at C:\\tools\\cli\\main.js:1529:7'
}
A subdirectory or file ..\public already exists.
File not found - *.css
File not found - *.js
File not found - head.html
The system cannot find the file specified.
Error: EPERM: operation not permitted, open 'C:\RCCC\.meteor\local\plugin-cache\ecmascript\0.15.1\c03197c398f31a2e6177271dff13e7b81139692e.json'
Error: EPERM: operation not permitted, open 'C:\RCCC\.meteor\local\plugin-cache\ecmascript\0.15.1\45c9ece603a1a088a265dc87a91860fad95dec52.json'
=> Errors while initializing project:

While loading plugin `Livechat` from package `rocketchat:livechat`:
child_process.js:635:11: Command failed:
C:\RCCC\packages\rocketchat-livechat\plugin/build.bat
The system cannot find the path specified.
npm WARN @nivo/line@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but
none is installed. You must install peer dependencies yourself.
npm WARN @nivo/annotations@0.62.0 requires a peer of react@>= 16.8.4 <
17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/axes@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but
none is installed. You must install peer dependencies yourself.
npm WARN @nivo/colors@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0
but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/core@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but
none is installed. You must install peer dependencies yourself.
npm WARN @nivo/legends@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0
but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/voronoi@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0
but none is installed. You must install peer dependencies yourself.
npm WARN @nivo/core@0.62.0 requires a peer of react@>= 16.8.4 < 17.0.0 but
none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react@15.x || 16.x ||
16.4.0-alpha.0911da3 but none is installed. You must install peer
dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x ||
16.4.0-alpha.0911da3 but none is installed. You must install peer
dependencies yourself.
npm WARN @rocket.chat/eslint-config@0.4.0 requires a peer of
eslint@^4.19.1 || ^5.16.0 but none is installed. You must install peer
dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.34.0 requires a peer of
@typescript-eslint/parser@^2.0.0 but none is installed. You must install
peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is
installed. You must install peer dependencies yourself.
npm WARN create-react-context@0.3.0 requires a peer of react@^0.14.0 ||
^15.0.0 || ^16.0.0 but none is installed. You must install peer
dependencies yourself.
npm WARN eslint-config-prettier@8.3.0 requires a peer of eslint@>=7.0.0
but none is installed. You must install peer dependencies yourself.
npm WARN pdfjs-dist@2.8.335 requires a peer of worker-loader@^3.0.7 but
none is installed. You must install peer dependencies yourself.
npm WARN preact-i18nline@2.0.0 requires a peer of preact@^7.0.0 || ^8.0.0
but none is installed. You must install peer dependencies yourself.
npm WARN prometheus-gc-stats@0.6.2 requires a peer of prom-client@>= 10 <
12 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 ||
^16.0.0 but none is installed. You must install peer dependencies
yourself.
npm WARN recompose@0.30.0 requires a peer of react@^0.14.0 || ^15.0.0 ||
^16.0.0 but none is installed. You must install peer dependencies
yourself.
npm WARN stylelint-order@2.2.1 requires a peer of stylelint@^9.10.1 ||
^10.0.0 but none is installed. You must install peer dependencies
yourself.
npm WARN The package eslint-plugin-import is included as both a dev and
production dependency.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
throw error;
^
{
message: "EPERM: operation not permitted, unlink
'C:\\RCCC\\.meteor\\local\\plugin-cache\\ecmascript\\0.15.1\\45c9ece603a1a088a265dc87a91860fad95dec52.json'",
info: {
file: 'packages/ecmascript/ecmascript.js',
line: undefined,
column: undefined,
func: undefined
},
stack: 'undefined\n' +
' => awaited here:\n' +
'    at Promise.await
(C:\\Users\\nkadiri\\AppData\\Local\\.meteor\\packages\\meteor-tool\\2.2.1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\meteor-promise\\promise_server.js:60:12)\n'
+
'    at C:\\tools\\cli\\main.js:1529:7'
}
A subdirectory or file ..\public already exists.
File not found - *.css
File not found - *.js
File not found - head.html
The system cannot find the file specified.

at checkExecSyncError (child_process.js:635:11)
at execSync (child_process.js:671:15)
at module (packages/Livechat/plugin/build-livechat.js:20:2)
at fileEvaluate (packages/modules-runtime.js:336:7)
at Module.require (packages/modules-runtime.js:238:14)
at require (packages/modules-runtime.js:258:21)
at <runJavaScript-19>:94:1
at <runJavaScript-19>:99:3

A subdirectory or file ..\public already exists.
File not found - *.css
File not found - *.js
File not found - head.html
The system cannot find the file specified.
C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Couldn't parse stack frame: ''
    at C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\utils\tools\utils\parse-stack.ts:186:11
    at Array.some (<anonymous>)
    at parseStackFrames (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\utils\tools\utils\parse-stack.ts:118:10)
    at Object.parse (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\utils\tools\utils\parse-stack.ts:64:21)
    at Object.exception (C:\tools\utils\buildmessage.js:534:29)
    at C:\tools\isobuild\bundler.js:2235:22
    at Function._.each._.forEach (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
    at JsImage.load (C:\tools\isobuild\bundler.js:2088:7)
    at C:\tools\isobuild\isopack.js:476:16
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\isobuild\isopack.js:466:20
    at Function._.each._.forEach (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:191:9)
    at Isopack.ensurePluginsInitialized (C:\tools\isobuild\isopack.js:454:7)
    at C:\tools\isobuild\compiler.js:381:16
    at Array.forEach (<anonymous>)
    at C:\tools\isobuild\compiler.js:380:26
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\isobuild\compiler.js:376:16
    at C:\tools\isobuild\compiler.js:186:28
    at Slot.withValue (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
    at Object.withCache (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1663:39)
    at C:\tools\isobuild\compiler.js:185:11
    at Function._.each._.forEach (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
    at Object.compile (C:\tools\isobuild\compiler.js:180:5)
    at C:\tools\isobuild\isopack-cache.js:354:30
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at IsopackCache._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:309:18)
    at C:\tools\isobuild\isopack-cache.js:243:16
    at Function.time (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
    at C:\tools\isobuild\isopack-cache.js:242:17
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:233:20)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:191:9)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24)
    at C:\tools\project-context.js:890:25
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:889:18)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at C:\tools\project-context.js:282:12
    at Function.run (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\cli\commands.js:1010:20
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.main.captureAndExit (C:\tools\cli\main.js:275:29)
    at buildCommand (C:\tools\cli\commands.js:1007:8)
    at C:\tools\cli\commands.js:948:25
    at Function.run (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)
    at C:\tools\cli\commands.js:946:18
    at C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Promise.await (C:\Users\nkadiri\AppData\Local\.meteor\packages\meteor-tool\2.2.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at C:\tools\cli\main.js:1529:7

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18
- Operating System: Windows Server 2019 standard

**Comment by reetp** [comment]
Hi.

Please note that github is reserved for bugs, not support.

Please read the documentation. Rocket will not build or run in Windows.

The closest you will get is this and you will need 12-16Gb to build.

https://developer.rocket.chat/getting-started/choosing-a-development-host/windows-10

Please ask your questions in https://forums.rocket.chat or https://open.rocket.chat
