### ISSUE TITLE
Unable to change file size upload limit in docker container

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#2322]
Hey Guys,

i try to change the file size upload limit to 3MB. But Rocket.chat only uses the standard 2MB on upload. In the settings its saved correctly. 

Did you have any suggestion? Can i set the file size upload limit via an environment variable on the docker container?

Thanks!

TheReal

Your Rocket.Chat version: 0.19.0

**Comment by graywolf336** [comment]
And you tried to restart your instance after saving? That setting requires
a server restart.

**Comment by TheReal1604** [comment]
Sry, wrong button :-). Dont restart the container.. test this later.. thanks for the response!

**Comment by TheReal1604** [comment]
After the restart, it works. Thanks for this hint. Can you please make a little notice to this setting?
