### ISSUE TITLE
Universal ignore user: Feature request

### ISSUE THREAD

**Issue by TNF13** [RocketChat/Rocket.Chat#23226]
I did not see anything in the current issues that match this.

### Description:

When a user is ignored, their message is still visible to the person doing the ignoring under certain circumstances. It typically displays the avatar, name, and username along with "this message was ignored" and sometimes "click to show" depending on the client being desktop app, browser, mobile app.

Ignore also only works channel-by-channel, so if two people who don't get along are in multiple channels, they have to go through each channel and ignore them. 

We use Rocket Chat for peer support/mental health purposes. When two people simply don't get along but still benefit from being in the server, we instruct them to ignore and block the person. Blocking disallows the person from messaging the person blocking and works fine. One click and done.

However, with ignore, there are a variety of reasons why someone wouldn't want to even see that the person they ignored is posting a message and have that ignore be universal. It would be nice to have a separate feature that allows users to universally ignore a person such that their messages are not visible at all and no reminder of the ignored user is presented. 

Having that feature separate from the current channel-by-channel ignore option would be beneficial to give people options depending on their needs.

**Comment by reetp** [comment]
This should be in https://github.com/RocketChat/feature-requests

I have no permissions to move it.

**Comment by TNF13** [comment]
Added to an existing issue, but it's from 2020. I guess this can be closed, but it would be a nice feature to have.
