### ISSUE TITLE
3.18.1 no longer shows the # button on team channels

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#23229]
### Description:

Until version 3.18.0 it was possible to list all the channels of the equipment from the channel in which it was.
I just upgraded to 3.18.1 and the # button is no longer showing.
This function greatly speeds up the change from one channel to another within the team.
Now the user has to go directly to the Equipment to be able to list the channels.

### Steps to reproduce:

1. Access any channel of the team
2. The # button is no longer displayed in the upper right menu options.

### Expected behavior:

That the # button is shown in all the channels that belong to the Team as it was until version 3.18.0

### Actual behavior:

The button is only shown in the Team

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.4.8

### Client Setup Information

- Desktop App or Browser Version: Chrome, Client Electron for Windows
- Operating System: Windows 10

### Additional context

The experimental version of the mobile app that came out a few hours ago still maintains that component.

**Comment by debdutdeb** [comment]
Hi, thanks for reporting this.

As far as I know the channel list is only visible from the team's main channel, not from any/all channel[s] that belong[s] to a team. I've just tested this on both 3.18.0 (as you mentioned) and also in 3.17.2

**Comment by aleadco** [comment]
Well no, any channel that belonged to the team had the number symbol in the upper right to access the channel list, a very convenient element to move from one channel to another that belongs to the team. It was lost when I upgraded to 3.18.1
Even the mobile app included that function ...

**Comment by debdutdeb** [comment]
Can you please share a screen capture?

**Comment by aleadco** [comment]
Unfortunately and the backup that contained 3.17.2 was overwritten. But I leave you the capture from the app of a channel that belongs to a team.

![IMG_20210922_100307.jpg](https://user-images.githubusercontent.com/35962168/134358495-5e930d7c-3eea-48eb-b27f-e1fcdcc9eda5.jpg)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
