### ISSUE TITLE
Error: Cannot find module 'ticons'

### ISSUE THREAD

**Issue by bharatbiswal** [RocketChat/Rocket.Chat#2323]
I am using MacOSX 10.11.2, Node v5.7.0, NPM v3.6.0 
To build the Android app, I have been following instructions from:
https://github.com/RocketChat/Rocket.Chat/wiki/Build-the-Android-Cordova-Web-App-and-connect-to-your-own-Rocket.Chat-Server

When I run "`cordova build android`"   I get following error:
**Error: Cannot find module '`ticons`'**

I have already installed ticons by following command:
`sudo npm install -g ticons`

**Comment by rodrigok** [comment]
Try to install inside the project folder:

`sudo npm install ticons`

**Comment by bharatbiswal** [comment]
It worked. Great. Thanks!
