### ISSUE TITLE
Don't recieve verification email

### ISSUE THREAD

**Issue by DeviFox** [RocketChat/Rocket.Chat#23233]
I used my work email for chat, but can't verifivate this. After pressing "Resend verification email" i'm don't recieve anything...

**Comment by reetp** [comment]
Hi,

Github is reserved for bugs in Rocket.Chat

Please read the links here:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

https://rocket.chat/docs/contributing/reporting-issues

For general help please see this:

https://rocket.chat/docs/getting-support

Thanks.
