### ISSUE TITLE
This is not a Rocket.Chat server. Contact your server admin

### ISSUE THREAD

**Issue by pullnhiuchien** [RocketChat/Rocket.Chat#23247]
I’ve installed Rocket Chat Server in ubuntu 20.04 and get into admin page successfully but when I download app from my Iphone (which connect to the same wifi with server and is able to ping to the server) but it released that “this is not a Rocket.Chat server, contact to admin”. I just want to test it locally not public. Please help me

**Comment by pullnhiuchien** [comment]
![Uploading 683A9ACF-84BF-4B38-932D-5989F0AB64E0.jpeg…]()

**Comment by reetp** [comment]
Please read the help when you create a new issue - github is for bugs and not general support:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues

> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support
