### ISSUE TITLE
Question: Is there an option to set an entire rocketChat server to readonly?

### ISSUE THREAD

**Issue by mhenninghaus77** [RocketChat/Rocket.Chat#23240]
Our management would like to switch to another communication portal. Therefore, I would like to know how I can switch an onPremise server to readonly in order to access the chat history, but at the same time prevent colleagues from actively using the chat to write. I have only found the following:

https://www.tyler-wright.com/mark-all-rocket-chat-channels-read-only-and-archive-them/

Is this really the only way?
Greetings

**Comment by reetp** [comment]
Hi,

Github is for actual bugs in Rocket.Chat

https://rocket.chat/docs/contributing/reporting-issues

Can you please ask your question in the https://forums.rocket.chat or https://open.rocket.chat

Thanks.
