### ISSUE TITLE
Timeline for remove push notification scaling 

### ISSUE THREAD

**Issue by jakiro2017** [RocketChat/Rocket.Chat#23249]
Hi

My company use RC to communicate. Thank you for the great software

However, we hit the limit per room push notification. for 8 instance and 280 active users, the performance is really bad.

I will try to separate push notification to another service, wanna ask did you guys have any ideas, timeline as I don't want to waste our effort to do duplicated thing.

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

As of you deployment, I think 8 instances is too much for 300 users, 2-3 instances would be enough. And on my experience, push notifications itself don't generate measurable load. Most load is presence exchange.

**Comment by reetp** [comment]
No evidence of a bug.
Please follow up as per Antons links.

@rocket-cat close

**Comment by reetp** [comment]
Hmmm - bot has gone to sleep.
