### ISSUE TITLE
Clicking the copy command button on Rocket Chat documentation results in copying of the pwd part as well

### ISSUE THREAD

**Issue by Vishal-Chdhry** [RocketChat/Rocket.Chat#23253]
### Description:
Clicking the copy command button on Rocket Chat documentation results in copying of the pwd part as well. This defeats the purpose of having that button there in the first place.

### Steps to reproduce:

1. Go to https://developer.rocket.chat/getting-started/choosing-a-development-host/gitpod
2. Click on any of the copy command buttons
3. Paste the command anywhere

### Expected behavior:
Clicking the button should result in copying of only the command and not the directory information

### Actual behavior:
Directory gets copied as well

**Comment by debdutdeb** [comment]
Hi.

I've fixed the issue, thanks for reporting ;)
