### ISSUE TITLE
Adding Users via Federation stopped working in 3.18.1

### ISSUE THREAD

**Issue by qwertiko** [RocketChat/Rocket.Chat#23250]
### Description:

Adding Users via Federation is not working after Updating from 3.17.1 to 3.18.1.
The error message "invalid user" is given.

### Steps to reproduce:

1. Go to Directory
2. Go to External Users
3. Search for Federated User
4. Click on the User to start a room

### Expected behavior:

User is added and room created

### Actual behavior:

The message "invalid user" is displayed

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.14

### Client Setup Information

- Desktop App or Browser Version: both/Firefox/Chrome
- Operating System: manjaro/Fedora

### Additional context

Debug Log show the following:
Sep 21 12:10:37 laura rocketchat[14765]: server.js:204 Federation ➔ client.error afterCreateDirectRoom => Could not create federated room: TypeError: Cannot read property '0' of undefined
Sep 21 12:10:37 laura rocketchat[14765]:     at Object.normalizeUser (app/federation/server/normalizers/user.js:30:16)
Sep 21 12:10:37 laura rocketchat[14765]:     at app/federation/server/hooks/afterCreateDirectRoom.js:34:41
Sep 21 12:10:37 laura rocketchat[14765]:     at Array.map (<anonymous>)
Sep 21 12:10:37 laura rocketchat[14765]:     at app/federation/server/hooks/afterCreateDirectRoom.js:33:51
Sep 21 12:10:37 laura rocketchat[14765]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

Since the error occured in the user.js file trying to get the property emails at the following place:
  const resource = _.pick(originalResource, '_id', 'username', 'type', 'emails', 'name', 'federation', 'isRemote', 'createdAt', '_updatedAt');
  const email = resource.emails[0].address;

I therefore logged via the console the array "resource" and got the following back:

{ _id: 'LdJc2Ad2iNrqtuw3L', username: 'USERNAME_REDACTED' }

There is clearly no email address that can be accessed in this array. But i am not sure why this is not the case as the user has every attribute set in the database.

**Comment by col-panic** [comment]
Same here. For us - after updating from 3.14 to 3.18 - Federation at all does not work anymore ..

**Comment by ankar84** [comment]
Have the same issue on 3.18.3
@debdutdeb @dudanogueira please help to review the fix for that issue.

**Comment by col-panic** [comment]
Related https://github.com/RocketChat/Rocket.Chat/issues/23856

**Comment by bkraul** [comment]
Hate to be insistent, but this issue was initially reported in September. The reporter himself submitted a [fix PR](https://github.com/RocketChat/Rocket.Chat/pull/23347/files) for this back in October. One-line change. No merge conflicts, no issues, all that is needed is a simple qualified approval. Yet, here we are, near the end of the year, with broken federation functionality and this issue ignored. What's the deal, guys? Are we looking at a security issue here and therefore this can't happen? An answer would be nice.

**Comment by col-panic** [comment]
@bkraul it is really insane. I like the project, but it seems disorganized and overwhelmed by the PRs and issues. One example is the closing of #23856 by @dudanogueira - he seems to not even have understood or took the time to read the problem mentioned - he just assumed that it is a duplicate and closed it. I even mentioned it there, but no reaction.

We are thinking about using the commercial version of Rocketchat, but I really doubt, that support is capable of handling Federation issues in a decent time or quality.  

It seems generaly demotivating to place patches with this project. Within https://github.com/RocketChat/Rocket.Chat/issues/18432 I was going for a real length to get the problem addressed (including mentioning it in https://forums.rocket.chat/t/federation-messages-sent-but-not-received/7991 and directly addressing people in https://gitter.im/RocketChat/Rocket.Chat) ..

**Comment by debdutdeb** [comment]
Hey, sorry for the inconvenience regrading #23856

As for the pr linked, as you can see our eng manager already requested reviews from two others. It will most likely be part of our next sprint. 

For a 100% assurance I've asked our pm and em for something concrete, internally yesterday (Friday my time).

**Comment by col-panic** [comment]
According to https://docs.rocket.chat/getting-support RocketChat 3.18 is an LTS version, will this patch hence be ported to this version? Thanks

**Comment by bkraul** [comment]
This appears corrected on latest 4.3.0-develop (e62d8d412). Thank you for getting to this.

**Comment by geekgonecrazy** [comment]
Based on this last comment is seems resolved?  Can anyone confirm?

**Comment by bkraul** [comment]
I stopped using the functionality due to its unreliability. I believe a subsequent update introduced further issues. Here is the latest error (on 4.7.0-develop), which happens upon trying to add/dm a federated user:

```
rocketchat_1          | {"level":50,"time":"2022-04-24T12:39:25.368Z","pid":9,"hostname":"REDACTED","name":"Federation","section":"client","msg":"afterCreateDirectRoom => Could not create federated room:","err":{"type":"TypeError","message":"Cannot read property 'username' of undefined","stack":"TypeError: Cannot read property 'username' of undefined\n    at Object.normalizeSubscription (app/federation/server/normalizers/subscription.js:23:53)\n    at app/federation/server/hooks/afterCreateDirectRoom.js:44:54\n    at Array.map (<anonymous>)\n    at app/federation/server/hooks/afterCreateDirectRoom.js:37:19\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Cannot read property 'username' of undefined"}
```

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
