### ISSUE TITLE
CAS Plugin: Upgrade cas libs to support CAS 2.0 protocol

### ISSUE THREAD

**Issue by corecache** [RocketChat/Rocket.Chat#2325]
The current CAS plugin supports only CAS 1.0 which is sufficient to login with a username.

The CAS 2.0 protocol transports user attributes such as Common Name, Email, and even custom attributes. The minimal implementation for CAS 2.0 rocketchat plugin would allow defining a map of attributes, which are parsed from the CAS response and will be mapped towards what RC user attributes:
- cas_response.email -> rc.user.emails
- cas_response.fullname -> rc.user.name/profile

**Comment by corecache** [comment]
One possible candidate which provides CAS 2.0: https://github.com/joshchan/node-cas

**Comment by corecache** [comment]
Another probably better candidate would be https://www.npmjs.com/package/xcas

**Comment by corecache** [comment]
Tried to use official npmjs modules to provide a CAS 2.0 library - but I failed to find a sane packaged version. Instead I tried to pull in some github module by adding it as local files, but it seems that Meteor doesnt support this practice, yet. I'm not aware of a workaround.

A heads up from @Sing-Li was given to wait till RC switched to Meteor 1.3: 
https://github.com/meteor/meteor/blob/release-1.3/packages/module /README.md

**Comment by corecache** [comment]
Upgraded my test instance to latest develop state and tried using meteor 1.4 features such as [Meteor | Npm.depends ](http://docs.meteor.com/api/packagejs.html#Npm-depends) and  [ npmjs package definitions](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

Versions:
`rocketchat_1  |    npm info using npm@3.10.6`
`rocketchat_1  |    npm info using node@v4.5.0`

Tried using the new package imports as described above:
`Npm.depends({`
`     cas: 'https://github.com/joshchan/node-cas/tarball/master'`
`});`

This fails with:
`rocketchat_1  |    While reading package from '/app/packages/rocketchat-cas':`
`rocketchat_1  |    package.js:29:5: must declare valid version of dependency:`
`rocketchat_1  |    cas@https://github.com/joshchan/node-cas/tarball/master`

@Sing-Li Any idea why this fails?

**Comment by Sing-Li** [comment]
@corecache   Meteor 1.4 supports npm modules directly now.    Please see https://guide.meteor.com/using-npm-packages.html     

Basically, you can just `npm install --save`

**Comment by Sing-Li** [comment]
@RocketChat/core   Are we starting to create new package as npm packages now?   Are we migrating?

**Comment by engelgabriel** [comment]
@rodrigok can you help @corecache here?

**Comment by rodrigok** [comment]
I'll take a look after the 0.40 release

**Comment by marceloschmidt** [comment]
@corecache please try using this syntax:

```
Npm.depends({
	cas: 'git+https://github.com/joshchan/node-cas#master'
});
```

**Comment by corecache** [comment]
That seems to work.
According to [npmjs - pacjage.json](https://docs.npmjs.com/files/package.json#dependencies) the "Local paths" should work aswell, but when adding something like
` cas: "file:test/foobar" ` or simply `cas: "foobar/test" I do get "must declare valid version of dependency" errors

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/18848361/4fbdf5a0-8404-11e6-90b7-a42b2144c5e2.png)

**Comment by engelgabriel** [comment]
@corecache do you need our help?

**Comment by corecache** [comment]
I'm on a good track now - got early CAS 2.0 response working, but it broke 1.0  ... priceless. I'm on it.

**Comment by corecache** [comment]
BugFix got merged: https://github.com/joshchan/node-cas/commit/4ae9f7a28c29ba39c8746aa14ed428dd5e5ebc5c
