### ISSUE TITLE
User Chat History Logs

### ISSUE THREAD

**Issue by PremKishan98** [RocketChat/Rocket.Chat#23267]
Hello Everyone!!

I have been using Rocket.Chat tool for a while. I am about to deploy the tool into
the production environment. Can someone please let me know how do I retrieve
the user chat history logs using the terminal. I use Ubuntu 18.04 OS. Is there any
command or tool to retrieve the chat history logs which is stored in the Rocket.chat
server. Any help will be beneficial.

Thanks!!

Note: This is not related to issues.

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

As of your question, all chats are located in mongodb in database called `rocketchat` in `messages` collection. You can retrieve all you need using corresponding mongo tools.

**Comment by PremKishan98** [comment]
Thanks and I apologise for making a mistake.

**Comment by ankar84** [comment]
> Thanks and I apologise for making a mistake.

Not a problem!
