### ISSUE TITLE
smtps is failing due ssl3_get_record : wrong version number

### ISSUE THREAD

**Issue by franciscopaniskaseker** [RocketChat/Rocket.Chat#23287]
### Description:

Every time that RC try to send e-mail, RC say that the e-mail was sent, but actually is not.
### Steps to reproduce:

1. Go to administration panel
2. go to e-mail
3. go to smtp
4. click in "send email to my user"

### Expected behavior:

E-mail sent to the user.

### Actual behavior:

E-mail is not being sent, besides the successfull green message.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: ubuntu 20.04 updated
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: v12.22.1
- MongoDB Version: v4.0.27

### Client Setup Information

- Desktop App or Browser Version:  mac desktop app
- Operating System: macos big sur

### Relevant logs:

Note: forget the dates and time

Every time that RC try to send an e-mail, in the log I can see:
```bash
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]: Exception in defer callback: [Error: 139791656081280:error:1408F10B:SSL routine>
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]: ] {
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]:   library: 'SSL routines',
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]:   function: 'ssl3_get_record',
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]:   reason: 'wrong version number',
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]:   code: 'ESOCKET',
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]:   command: 'CONN'
Sep 25 23:31:44 ip-172-31-42-134 rocketchat[555]: }
```

At the mail server side, I see:
```bash
Sep 25 21:56:54 mail postfix/submission/smtpd[27884]: connect from myrocketchatserver.com[x.y.z.w]
Sep 25 21:56:54 mail postfix/submission/smtpd[27884]: lost connection after UNKNOWN from myrocketchatserver.com[x.y.z.w]
Sep 25 21:56:54 mail postfix/submission/smtpd[27884]: disconnect from myrocketchatserver.com[x.y.z.w] unknown=0/2 commands=0/2
```

I added a postfix debug and i saw this:
```bash
  Sep 25 23:23:37 mail postfix/submission/smtpd[11538]: match_string: smtpd_forbidden_commands: ????v? ~? connect
Sep 25 23:23:37 mail postfix/submission/smtpd[11538]: match_string: smtpd_forbidden_commands: ????v? ~? get
Sep 25 23:23:37 mail postfix/submission/smtpd[11538]: match_string: smtpd_forbidden_commands: ????v? ~? post
Sep 25 23:23:37 mail postfix/submission/smtpd[11538]: match_list_match: ????v?: no match
Sep 25 23:23:37 mail postfix/submission/smtpd[11538]: > myrocketchatserver.com[x.y.z.w]: 502 5.5.2 Error: command not recognized
```

I checked the mail server cert and is everything ok. Other services are using without problem. Just rocketchat is getting this "ssl3_get_record reason: 'wrong version number'".

**Comment by franciscopaniskaseker** [comment]
I do not think is a rocketchat bug. Seems related with nodejs and https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816

**Comment by franciscopaniskaseker** [comment]
Well, I issued the SSL with ISRG Root X1 chain and I continue getting the error.

**Comment by franciscopaniskaseker** [comment]
I changed the protocol from smtps to smtp and fixed. I am not sure why.

**Comment by franciscopaniskaseker** [comment]
smtps use SSL, so i need to connect to the mail server (zimbra) through 465 port (ssl). If I set 587 port (STARTTLS), then I need to change the protocol to SMTP. I think this explain the problem. 

I will close here. It does not seems to be a bug.

**Comment by rasos** [comment]
Since RC 3.13, retrieving direct replies via IMAP(S) is broken (we've tested on several instances without success). However POP3 with TLS on port 995 is working fine. See https://github.com/RocketChat/Rocket.Chat/issues/20925
