### ISSUE TITLE
LDAP: Rocket.Chat keeps changing account image to ldap image instead of gravatar

### ISSUE THREAD

**Issue by dajester2013** [RocketChat/Rocket.Chat#2328]
Your Rocket.Chat version: 0.18.0
DB migration: 29

I have Rocket.Chat configured to use LDAP auth against our ActiveDirectory server.  Every time I log in, it changes my account photo back to my AD photo, even though I've gone in and set it to use my gravatar image instead.  I need it to recognize that I've made a custom change, and to not synchronize my photo every time.

**Comment by engelgabriel** [comment]
On version 0.19.0 the admin can turn of the photo sync for LDAP, is this correct @rodrigok?

**Comment by rodrigok** [comment]
Yes, you can disable the avatar sync in version 0.19.0

**Comment by dajester2013** [comment]
cool - confirmed that it is working in 0.19.0
