### ISSUE TITLE
Broken links in search when search term is part of the URL

### ISSUE THREAD

**Issue by SufiSR** [RocketChat/Rocket.Chat#23285]
### Description:
The link in "Search Messages" open to a 404 page.
The URL is opened with <mark> tags.

### Steps to reproduce:
Click in lookup icon to open "Search Messages" box in chat.
Find some link in chat.
Click to open the highlighted link.
![search_issue](https://user-images.githubusercontent.com/83453553/134642920-a5d2ae9f-43e0-49eb-a18f-61d5e2a4bd3a.png)

### Expected behavior:
Link opens correctly.

### Actual behavior:
Link opens a 404 page.

### Server Setup Information:
Version of Rocket.Chat Server: 3.17.2
Operating System: Linux
NodeJS Version: v12.22.1
MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Google Chrome 93.0.4577.82 (Offizieller Build) (64-Bit) / same challenge with Firefox
Operating System: Windows 10 

### Additional context
This was already closed as "could not reproduce" in issue #19369. The screenshot should help to reproduce.

**Comment by ngulden** [comment]
We experience the same behavior in our team with our internal instance.
