### ISSUE TITLE
LDAP authentication failing in spite of successful connection

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#23296]
### Description:

In spite of LDAP configuration being correct (using and LDAP service account for BINDs) and tests being successful, manual synchronization and user authentication is failing with the following error:
```
{"level":50,"time":"2021-09-27T14:00:08.797Z","pid":1,"hostname":"2af473c901d9","name":"LDAP","err":{"type":"","message":"000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000","stack":"OperationsError: 000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000\n    at messageCallback (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1218:45)\n    at Parser.onMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:886:14)\n    at Parser.emit (events.js:314:20)\n    at Parser.EventEmitter.emit (domain.js:483:12)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:107:8)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/lib/ldap/Manager.ts:144:15\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","lde_message":"000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000","lde_dn":null},"msg":"000004DC: LdapErr: DSID-0C090A5C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4563\u0000"}
```

### Steps to reproduce:

1. Update to `4.0.0-develop` (commit `70a7b94c`)
2. Attempt to log in with an LDAP user.
3. Will get `User not found or incorrect password` error.
4. Log in to administration. Attempt to test the LDAP configuration. It tests successfuly.
5. Attempt to Sync.
6. Will get a `Not Authorized` error.

### Expected behavior:

Users should be authenticated, and manual synchronization should work, given there have been no changes to the LDAP configuration or environment.

### Actual behavior:

LDAP errors occur, preventing both authentication and synchronization.
![image](https://user-images.githubusercontent.com/14616851/134924711-71649743-09bd-442b-b4f7-36694610ec54.png)
![image](https://user-images.githubusercontent.com/14616851/134924912-36ee50de-846b-4653-b583-92597c186704.png)
![image](https://user-images.githubusercontent.com/14616851/134925601-bb42c836-851f-4b32-832b-ba535cfb0ed0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: `4.0.0-develop` (commit `70a7b94c`)
- Operating System: Ubuntu 20.04.3 (docker)
- Deployment Method: docker 
- Number of Running Instances:  1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.16 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop: 3.5, Browser: Firefox 92.0.1
- Operating System: Windows 10 21H1

**Comment by bkraul** [comment]
Could this be done to an issue with c2ab5e1?

**Comment by pierre-lehnen-rc** [comment]
Thanks for reporting, I'll take a look!.

**Comment by bkraul** [comment]
@pierre-lehnen-rc thanks for looking at this so quickly!

**Comment by bkraul** [comment]
@pierre-lehnen-rc  I can report it fixed the login issue we were having. However, I have a question. I know periodic background sync is supposed to be part of the Enterprise edition now. However, shouldn't on-demand sync work for the community edition? I am still getting `Not Authorized` when I try it. Maybe I am not understanding and it is really part of Enterprise?

**Comment by ankar84** [comment]
> @pierre-lehnen-rc I can report it fixed the login issue we were having. However, I have a question. I know periodic background sync is supposed to be part of the Enterprise edition now. However, shouldn't on-demand sync work for the community edition? I am still getting `Not Authorized` when I try it. Maybe I am not understanding and it is really part of Enterprise?

Having same issue when I try to run `background sync` I get `Not Authorized` on 4.0.0 docker version.

**Comment by ankar84** [comment]
Looks like manual sync is back in 4.2.0!
With one addition of asking of users password to start (security purposes I guess)
![image](https://user-images.githubusercontent.com/4023037/143997800-b0e06859-ec87-4f9b-b323-443b7dde1956.png)
![image](https://user-images.githubusercontent.com/4023037/143997863-2d41fe47-675b-485b-8b4e-e714b6e42f76.png)

So, that and related to manual sync issues can be closed now

**Comment by reetp** [comment]
> With one addition of asking of users password to start (security purposes I guess)

As mentioned elsewhere it has absolutely nothing to do with security but a desperate attempt to block you from running a cron to get a background sync.

They really don't want you doing that.
