### ISSUE TITLE
Decrease ping interval ( websocket )

### ISSUE THREAD

**Issue by jonathantyar** [RocketChat/Rocket.Chat#23299]
The default of ping that i am getting from rocketchat websocket server had interval at 30 seconds, how can i decrease the ping intervals? is there any way i can customize the code or using some plugin?

**Comment by reetp** [comment]
When creating a new Issue please use the template and fill it out correctly.

This shows you what to do before you start:

https://rocket.chat/docs/contributing/reporting-issues

Note that github is reserved for bugs in Rocket.Chat, not general support, and there is no evidence of a bug here.

Please ask your well documented question in https://forums.rocket.chat or https://open.rocket.chat/channel/support
