### ISSUE TITLE
Theme colors stop updating

### ISSUE THREAD

**Issue by johnsimmons** [RocketChat/Rocket.Chat#2329]
Your Rocket.Chat version: 0.19.0

Installed rocket chat on Ubuntu 14.04 using [this](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker#2-install-rocketchat) method.

Everything worked really well for about a week on version 0.18.0, then theme colors stopped updating.

I changed the theme colors several times, and everything worked, then what seems to be randomly, when I change a color it says "Settings updated", but nothing happens. 

No errors reported that I can find.

I just updated to 0.19.0 to see if that helped, and it did not.

**Comment by johnsimmons** [comment]
I've tried on multiple browsers, with different admins, or separate machines.  Same issue.

**Comment by engelgabriel** [comment]
Can you try the develop build?

**Comment by johnsimmons** [comment]
Sorry, I don't see a develop tag or branch on github, is it somewhere else?

**Comment by engelgabriel** [comment]
Hi, you can download it from here: https://rocket.chat/releases

**Comment by johnsimmons** [comment]
Ok, I think I wasn't seeing the error because I was using pm2 to deploy.

When I start the application it no longer starts, and gives this error:

```
{ [Error: error evaluating function `lighten`: Object [object Object] has no method 'toHSL']
  type: 'undefined_method',
  filename: 'input',
  index: 182839,
  line: 7334,
  callLine: NaN,
  callExtract: undefined,
  column: 21,
  extract: 
   [ '\t\t&::before {',
     '\t\t\tbackground-color: lighten(@info-active-font-color, 25%);',
     '\t\t}' ],
  message: 'error evaluating function `lighten`: Object [object Object] has no method \'toHSL\'',
  stack: undefined }
{ [Error: error evaluating function `lighten`: Object [object Object] has no method 'toHSL']
  type: 'undefined_method',
  filename: 'input',
  index: 182821,
  line: 7334,
  callLine: NaN,
  callExtract: undefined,
  column: 21,
  extract: 
   [ '\t\t&::before {',
     '\t\t\tbackground-color: lighten(@info-active-font-color, 25%);',
     '\t\t}' ],
  message: 'error evaluating function `lighten`: Object [object Object] has no method \'toHSL\'',
  stack: undefined }
Updating process.env.MAIL_URL
configuring push
Using GridFS for Avatar storage

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickDomainCallback (node.js:492:13)

```

**Comment by engelgabriel** [comment]
Looks like you may have a broken theme colours settings. Were you changing them when it broke?

**Comment by johnsimmons** [comment]
What started everything was I was trying to customize my color scheme.  After about 20 minutes of changing every color to see what was what, the color changes stopped doing anything.  So I was left with terrible colors, and unable to change any of them.

**Comment by engelgabriel** [comment]
You need to delete all the color settings on the `rocketchat_settings` collections:

`db.rocketchat_settings.remove({_id:/theme/})`

**Comment by johnsimmons** [comment]
Thanks, that worked perfectly.  I'll try to figure out what I did to break it, and report back.
