### ISSUE TITLE
Don't show 'undefined' in page title when loading

### ISSUE THREAD

**Issue by lvh1** [RocketChat/Rocket.Chat#2330]
Just nit-picking at this point but still :P 
The page title shows 'undefined' for a half a second when loading 
![https://i1.someimage.com/lonIf7M.png](https://i1.someimage.com/lonIf7M.png)
would be better if it was either an empty string or just 'rocket.chat'

**Comment by rodrigok** [comment]
Was fixed via https://github.com/RocketChat/Rocket.Chat/pull/2324
