### ISSUE TITLE
Can not set up SMTP Server with SSL certificate signed by custom CA certificate

### ISSUE THREAD

**Issue by r00t1900** [RocketChat/Rocket.Chat#23300]
### Description:

I deploy rocketchat on a LAN environment which has no internet access, so I can not use the public CA signed certificate. Instead, I deploy other web services with SSL support by using custom CA certificate to sign the website SSL certificate, for example, my SMTP Server. Therefore, I would like to set smtps on rocketchat, but receive error says **self signed certificate in certificate chain**, I guess is the smtps ssl verifying did not pass.

### Steps to reproduce:

1. Deploy mongo and rocketchat by docker according to official instruction at https://hub.docker.com/r/rocketchat/rocket.chat
2. Login to rocketchat with http://localhost:80 and do some admin configuration, then use rocketchat as normal.
3. Trying to set email-smtp, filling with this params:
    - protocol: smtps
    - server: smtp.server.addr.com
    - port: 465
    - ignoreTLS: false
    - pool: false
    - username: <valid email account>
    - password: <valid email password>
    - from mail: same as username

   Then click **save changes** and **send test email to myself**, no email is delivered and logs says:
    ```
    Updating process.env.MAIL_URL
    Exception in defer callback: Error: self signed certificate in certificate chain
    at ...
    
    code: 'ESOCKET'
    command: 'CONN'
    ```
4. use docker command `docker exec -it -u 0 <instance name> bash` and `apt-get install ca-certificates` to install necessary software for adding custom CA certificate to system area under `/usr/share/ca-certificates`
5. `docker cp myCA.crt <instance name> /tmp/`
6. `docker exec -it -u 0 <instance name> bash` and `dpkg-reconfigure ca-certificates`
7. reboot docker instance and try sending email again, failed with same logs pasted above.

In stackoverflow, somebody say I can add some ignore flag to `main.js`, but I neither try the method nor be willing to disable TLS identify, cause it will put my data in and insecure situation. I just want the rocketchat docker can recognize the site SSL certificate signed by my custom CA certificate, which I have put it under `/usr/share/ca-certificates`.

### Expected behavior:

SMTP configuration of my private smtp server over personal CA signed SSL certificate works. Because I would like to use my own CA to ensure data transferring security.

### Actual behavior:

SMTP configuration fails and say something about **self signed certificate in certificate chain**.
### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: 3.4.0
- Operating System: ubuntu 18.04

### Relevant logs:

```
Updating process.env.MAIL_URL
Exception in defer callback: Error: self signed certificate in certificate chain
at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
at TLSSocket.emit (event.js:314:20)
at TLSSocket.EventEmitter.emit (domain.js:483:12)
at TLSSocket._finishInit (_tls_wrap.js:937:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
at TLSWrap.callbackTrampoline (_internal/async_hooks.js:126.14) {
code: 'ESOCKET',
command: 'CONN'
}
```

**Comment by reetp** [comment]
This was opened at the same time as a forum post:

https://forums.rocket.chat/t/rocketchat-smtp-server-configure-failed-under-private-ca-certificate-signed-smtp-ssl-certificate

Please note this on opening issues:

https://rocket.chat/docs/contributing/reporting-issues

Closing this for now - we can re-open if there is a bug found in Rocket
