### ISSUE TITLE
i18n: zh should be renamed to zh-CN

### ISSUE THREAD

**Issue by Arthur2e5** [RocketChat/Rocket.Chat#2331]
Your Rocket.Chat version: HEAD

Due to some historical and political reasons, there are two major variants of zh, zh-CN and zh-TW, written in two different scripts, zh-Hans and zh-CN respectively.

The script difference cause the two variants to look quite different. Additionally, the wording of the two variants are quite different ,especially for IT-related translations. All these can cause significant confusion for zh-TW users, so I guess you will want to separate them like most other FOSS projects do.

**Comment by philipwhiuk** [comment]
I'm guessing at some point we will run into this for other language sub-specifiers (i.e. color/colour in en-US and en-GB).

**Comment by Arthur2e5** [comment]
For en-US and en-GB things are mostly like foo*or*bar and foo*our*bar; but for zh-TW and zh-CN the difference looks like:

```
Key Manager  Plugin Package // en (ref)
金鑰管理員   外掛程式套件   // zh-TW
密钥管理器   插件    软件包 // zh-CN
```

**Comment by kxxoling** [comment]
In my opinion, it would be good to separated as zh-CN, zh-TW and zh-HK as a Chinese mainlander, zh-CN is used in China mainland in Simplified Chinese, zh-TW used in Taiwan and zh-HK for HongKong. zh-TW and zh-HK are both traditional Chinese but with some little differences, and zh-CN is Simplified Chinese which is a big different from the traditional one.

BTW, there's a tool to translate chs and cht automatically as I can remember.

**Comment by Arthur2e5** [comment]
I guess you atr talking about [OpenCC](https://github.com/BYVoid/OpenCC).

**Comment by kxxoling** [comment]
@Arthur2e5 Yes, but it can still do a lot of work for you before manual translation.

**Comment by Arthur2e5** [comment]
*checking*, *recommended*

**Comment by engelgabriel** [comment]
We now have 3 Chinese translation files, and the invitations to join the lingohub project have been sent.

![image](https://cloud.githubusercontent.com/assets/1000217/13404519/bc3fbf8a-def8-11e5-9cce-d20f6e57721d.png)
