### ISSUE TITLE
[Bug] PDF file preview stop working

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#23323]
### Description:

PDF file preview stop working in latest versions. 
In previous versions PDF preview worked correctly.

### Steps to reproduce:

1. Send PDF file to chat
2. No preview for that PDF file and user must download it to see it

### Expected behavior:

Users should see PDF file like they see images preview.

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/135557938-a1594079-16d2-4ba0-9ff9-d1b8b83d70ea.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.15

### Client Setup Information

- Desktop App or Browser Version: 3.5.6 and Chrome 93
- Operating System: Windows 10

### Additional context

No

### Relevant logs:

No

**Comment by reetp** [comment]
Duplicate of 

https://github.com/RocketChat/Rocket.Chat/issues/21075

**Comment by ankar84** [comment]
Agree with John. Answer for my question was here https://github.com/RocketChat/Rocket.Chat/issues/21075#issuecomment-798948746
So, I'm closing that issue and hope @aditya-mitra will find a great solution for that.
Many messengers shows a preview for PDF files.
