### ISSUE TITLE
Enable Android notifications for the demo chat?

### ISSUE THREAD

**Issue by dandv** [RocketChat/Rocket.Chat#2332]
I'm a Meteor dev new to Rocket.Chat.

If I understand correctly, [mobile push notifications work](https://github.com/RocketChat/Rocket.Chat/issues/1762), but are disabled for [group messages](https://github.com/RocketChat/Rocket.Chat/issues/1943).

However, I've just logged in with two accounts and pinged one from the other - there was no push notification on my Nexus 5X running the latest Android client.

Would be really nice if the rocket.chat demo had push notifications on Android.

![image](https://cloud.githubusercontent.com/assets/33569/13303981/2d810032-db07-11e5-93e2-e0897b21d582.png)

**Comment by engelgabriel** [comment]
They are not disabled for group messages. There is a time delay to avoid pushing message to the mobile too soon. Shall we close this?

**Comment by dandv** [comment]
Turned out the desktop/web session needs to be closed for 5 minutes, in order for notifications to be triggered on mobile.

This suggests it should be easy to add an option to send notifications on both/all subscribed clients. The use case is that we keep Rocket.Chat open in a tab all the time, but go to a meeting, and would like notifications to still be sent to the mobile app.

**Comment by rodrigok** [comment]
The push notification will be sent if you are offline or inactive in all connections for some time.

**Comment by engelgabriel** [comment]
The perfect behaviour would be for the notification to be put on a queue for 5 minutes. If there ir activity in the webclient, the queue is cleared, otherwise the notification gets forward to the mobile.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
