### ISSUE TITLE
Notifications on mobile are suppressed if the browser session is open

### ISSUE THREAD

**Issue by dandv** [RocketChat/Rocket.Chat#2333]
Just tested on Android. PMs and pinging my username do notify the Android app if I close the browser session, but not if the browser session is active. This is a problem because I leave my browser open at work when I leave for the day, but I'd like to receive notifications on mobile as well.

Slack sends the notifications in both places. Note that the browser tab did not have focus.

**Comment by engelgabriel** [comment]
Hi @dandv, we actually have the same behaviour. It will wait for 5 minutes and set you AWAY on the desktop connections, and after that, you will receive the push notifications. You need to way the 5 minutes to do the testing. Please reopen if that's not working.
