### ISSUE TITLE
RC 4.0.0 node upgrade fails with segfault error

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#23346]
### Description:

Starting RC node fails with segfault error after upgrading from RC 3.18.1 to RC 4.0.0.

### Steps to reproduce:

1. Stop all your running nodes
2. Download RC 4.0.0 tar package with `curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz`
2. Check that all dependencies are correct on your server
3. Install the RC 4.0.0 node binaries with `cd /tmp/bundle/programs/server && npm install`
4. Replace your first node with the new RC node
5. Start the first updated node

### Expected behavior:

Node starts and schema upgrade process begins

### Actual behavior:

The new node fails to start with a segfault error.

```
Oct 03 11:00:22 server.example.com kernel: node[18774]: segfault at 23d0 ip 00000000000023d0 sp 00007f8303d8d3c8 error 14 in node[400000+26b5000]
Oct 03 11:00:22 server.example.com abrt-hook-ccpp[18818]: Process 18774 (node) of user 5601 killed by SIGSEGV - dumping core
Oct 03 11:00:25 server.example.com abrt-server[18827]: Executable '/usr/local/bin/node' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Oct 03 11:00:25 server.example.com abrt-server[18827]: 'post-create' on '/var/spool/abrt/ccpp-2021-10-03-11:00:22-18774' exited with 1
Oct 03 11:00:25 server.example.com abrt-server[18827]: Deleting problem directory '/var/spool/abrt/ccpp-2021-10-03-11:00:22-18774'
Oct 03 11:01:01 server.example.com systemd[1]: Created slice User Slice of root.
```

### Server Setup Information:

- Version of Rocket.Chat Server: RC 4.0.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version:  12.22.1
- NPM version: 6.14.1
- MongoDB Version: 4.0

**Comment by mr-dandy** [comment]
We've got the same problem and similar configuration.

**Comment by tete2soja** [comment]
Same error for me too

**Comment by ymch** [comment]
I get the same error and cannot start with 4.0.0, not RC4.0.0.

**Comment by markus07** [comment]
The same problem with 4.0.0, upgraded from the latest available 3.x
Error:
Oct  4 14:47:14 test kernel: node[60646]: segfault at 23d0 ip 00000000000023d0 sp 00007f1cd9abc3c8 error 14 in node[400000+26b5000]

**Comment by TheWrongGuy** [comment]
We also have a segfault error after upgrading from 3.18.2 to 4.0.0.

**Comment by RC685** [comment]
I got the same error upgrading from 3.18.2 to 4.0.0. This was on our self-hosted CentOS 7 server.

**Comment by gennaris** [comment]
Same error here on a Centos 7 self-hosted - needed to downgrade...  

Oct 04 16:17:20 chat kernel: node[28685]: segfault at 23d0 ip 00000000000023d0 sp 00007f927df693c8 error 14 in node[400000+267f000]

**Comment by NiklasHamburgnet** [comment]
Same error on self hosted CentOS 7.

**Comment by whitetiger264** [comment]
> Using back previous version (https://releases.rocket.chat/3.18.2/download) works fine.

Downgrade worked for me too. Seems upgrading on CentOS 7 self hosted is an issue.

**Comment by serviceman** [comment]
I am having the same issue with a fresh install on Centos and Rocket Chat 4.0.0 self hosted, manual install.

**Comment by Gummikavalier** [comment]
Anyone with CentOS Stream or RockyLinux having the same issue? The segfault could be an issue with supported ciphers etc. with dependencies on older OSes.

**Comment by TheWrongGuy** [comment]
> Tested RC 4.0.1. Still segfaults.

Thanks for testing, so I don't have to try it myself. Was just going to ask. :D

**Comment by josephcrowell** [comment]
Yeah no 4.x releases are working properly yet.

**Comment by Gummikavalier** [comment]
> Rocket.Chat 4.0.1 (upgrade from 3.18.2) fail too with same issue (segfault at 23d0) on CentOS 7.8.2003
> 
> Is there any solution for it?

Thanks for confirming. No solutions yet.

**Comment by amsnek** [comment]
Same issue here, upgrade from 3.18.1 -> 4.0.1 
rhel7 /node-v12.22.5

**Comment by fasalsh** [comment]
Having the same segfault error on 4.0.2 update.

OS: CentOS Linux release 7.9.2009 (Core)
Previous RC version: 3.8.1
Updated to: 4.0.2

The versions below 4.0 seems working fine, so could be a bug in latest release.

# node -v
v12.22.1

# npm -v
6.14.1

Node and NPM matched as per https://github.com/RocketChat/Rocket.Chat/releases

The service getting killed automatically on startup. The error in kernel:

Oct 15 11:29:51 server.demo.com kernel: node[6071]: segfault at 23d0 ip 00000000000023d0 sp 00007ff0dd01a3c8 error 14 in node[400000+26b5000]

Any solution for this problem in CentOS 7?

**Comment by fasalsh** [comment]
@sampaiodiego Any thoughts on this as many users are affected already

**Comment by Gummikavalier** [comment]
@debdutdeb Hi, I tried that now (with RC 4.0.2) and get now

```
$  cd /opt/rocket.chat && node main.js 

Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

I'm probably doing something wrong, but I tried couple of different combinations too. I'll wait for the updated docs, unless I figure it out earlier... :)

**Comment by Gummikavalier** [comment]
@debdutdeb Whole process I tried now:
```
Ensure the correct nodejs version:
# node -v
v12.22.1

Ensure the correct NPM version:
# npm install -g npm@6.14.1
# npm cache clean -f

As root remove and move untarred RC 4.0.2 bundle to /opt/rocket.chat:
# rm -rf /opt/rocket.chat
# mv /root/bundle /opt/rocket.chat && chown -R rocket:rocket /opt/rocket.chat && chmod -R 770 /opt/rocket.chat && chown -R rocket:rocket /tmp/ufs

Su to rocket account:
# su - rocket

Then first export all the usual working ENV settings (values redacted in below but the ones that worked with RC 3.18.2):
export PORT=
export ROOT_URL=
export MONGO_URL=
export MONGO_OPLOG_URL=
export MAIL_URL=

Then run:
cd /opt/rocket.chat/programs/server/
rm -rf npm/node_modules/sharp/vendor
NODE_ENV=production npm i
cd ../.. && node main.js

Result:
Segmentation fault (core dumped)
```

**Comment by AndersonOuverney** [comment]
Hello everybody.
I'm new and I've never used rocket.chat yet and I'm trying to install it on a centos 7.

I went through the installation process following the guide, I did everything exactly as it is in the documentation about 10 times, always starting from a fresh installation, to make sure I'm not asking for anything.

On the last try I got new errors and I came to this place where people are encountering the exact same problem as me.

I would like to know from friends if there is already something we can do to upload the installation to the cents 7.

Thanks

**Comment by alireza-salehi** [comment]
version 4.1.1
CentOS Linux 7.9.2009 64bit / Linux 3.10.0-1160.45.1.el7.x86_64
npm 6.14.12
node v12.22.1
mongod v4.0.27

segmentation fault when running 
`node main.js`

**Comment by TheWrongGuy** [comment]
Was anyone brave enough to test 4.1.2 already?

**Comment by exequos** [comment]
> 
> You can also use node snap if you don't want to install and configure docker on all those machines - `sudo snap install node --channel=12/stable`
> 
> Or, if you're both against snap and docker usage (I've come across such situations), you can download a minimal ubuntu rootfs archive (since we know node + rc is working fine in ubuntu) and run node through chroot - very similar to using docker tbh.
> 
> Again - **the above are just temporary workarounds**.

thanks for suggestion

it seems to be a problem with the node binary on centos? did anyone managed to track the segfault or build node binary to check?
in my situation after many attemps for different node even on the 3.8.2 version the segfault 23d0 error occurs so. moved to...

the temporary solution with snap works fine except one - the snap version is lower than actual ones - what is the delay in snap versions vs general?

**Comment by alireza-salehi** [comment]
> Was anyone brave enough to test 4.1.2 already?

4.1.1 had same issue

**Comment by ali-alhaidary** [comment]
**upgrading from 4.1.1 to 4.1.2:**

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> fibers@4.0.3 install /tmp/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-72-glibc` exists; testing
Binary is fine; exiting
npm WARN lifecycle meteor-dev-bundle@~install: cannot run in wd meteor-dev-bundle@ node npm-rebuild.js (wd=/tmp/bundle/programs/server)
added 147 packages from 122 contributors and audited 148 packages in 5.109s

3 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New major version of npm available! 6.14.12 → 8.1.3      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v8.1.3   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

**Also, localization was not pulled from lingohub...**

**Comment by ali-alhaidary** [comment]
Also, https://github.com/RocketChat/Rocket.Chat/issues/23599 is still there not resolved...

**Comment by RC685** [comment]
Still no updates on this issue? :(

Might be worth throwing something in the update instructions on the website about the CentOS7 issue if it'll be a while.

**Comment by TheWrongGuy** [comment]
Push

**Comment by fasalsh** [comment]
@debdutdeb Any update on this case?

**Comment by tassoevan** [comment]
> @debdutdeb Any update on this case?

It's under investigation.

**Comment by mojitaleghani** [comment]
Hi everyone, I test on the lately released version right now (https://github.com/RocketChat/Rocket.Chat/releases/tag/4.2.0) which released yesterday and still faced the same error:
```
Dec 01 08:00:19 $$MY_DOMAIN kernel: node[21953]: segfault at 23d0 ip 00000000000023d0 sp 00007f1f9b2a33b8 error 14 in node[400000+26b5000]
```

are there anyone with a solution?

**Comment by sampaiodiego** [comment]
can some of you please help testing this PR https://github.com/RocketChat/Rocket.Chat/pull/23796 ?

**Comment by fasalsh** [comment]
@sampaiodiego I've tested this PR and got a different error on startup:
```
Dec 02 10:22:35 3-110-30-139.cprapid.com systemd[1]: Started The Rocket.Chat server.
Dec 02 10:22:35 3-110-30-139.cprapid.com rocketchat[4302]: internal/modules/cjs/loader.js:818
Dec 02 10:22:35 3-110-30-139.cprapid.com rocketchat[4302]: throw err;
Dec 02 10:22:35 3-110-30-139.cprapid.com rocketchat[4302]: ^
Dec 02 10:22:35 3-110-30-139.cprapid.com rocketchat[4302]: Error: Cannot find module 'reify/lib/runtime'
Dec 02 10:22:35 3-110-30-139.cprapid.com rocketchat[4302]: Require stack:
Dec 02 10:22:35 3-110-30-139.cprapid.com rocketchat[4302]: - /opt/Rocket.Chat/programs/server/runtime.js
Dec 02 10:22:35 3-110-30-139.cprapid.com systemd[1]: rocketchat.service: main process exited, code=exited, status=1/FAILURE
Dec 02 10:22:35 3-110-30-139.cprapid.com systemd[1]: Unit rocketchat.service entered failed state.
```

Steps followed:

- Stopped both mongod and rocketchat service.
- Fetched the source and extracted
curl -L https://releases.rocket.chat/latest/download -o /opt/rocket.chat.tgz && tar -xzf /opt/rocket.chat.tgz -C /opt && cd /opt/bundle/programs/server

- Replaced package.json file with the one on that PR:
wget https://raw.githubusercontent.com/RocketChat/Rocket.Chat/9e9c3e744ce21024bbf0bb72e4dd04bfa01deaf6/package-lock.json
mv package.json package.json_back
wget https://raw.githubusercontent.com/RocketChat/Rocket.Chat/9e9c3e744ce21024bbf0bb72e4dd04bfa01deaf6/package.json

- Ran npm install + npm audit fix. NPM Install output:
```
added 3464 packages from 3259 contributors and audited 3502 packages in 265.265s

336 packages are looking for funding
  run `npm fund` for details

found 78 vulnerabilities (5 low, 27 moderate, 40 high, 6 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
- Started both mongod and rocketchat service back

- It went to failed status immediately after start and got above attached errors in journalctl output.


Not sure if I did the steps wrong, if so please advise or review this case further.

Thanks

**Comment by debdutdeb** [comment]
@fasalsh are you using the root user (assuming from the no-sudo /opt handling)? If so please run `npm install --unsafe-perm` instead of just `npm install`.

**Comment by tassoevan** [comment]
There are multiple `node_modules` directories in the final build. If I remember well, the one containing `sharp` was at `programs/server/npm`. I don't know how to test it in isolation without making a fresh Meteor build.

**Comment by fasalsh** [comment]
Any update on this case? @sampaiodiego @debdutdeb

**Comment by lestercoyoyjr** [comment]
Hello Team,

I was suffering a lot to install Rocketchat, but I discover that what it fails is the node js version, so I changed from this:

`sudo apt-get -y update && sudo apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -`

to this:

`sudo apt-get -y update && sudo apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -`

The error was in the Nodejs version. I also checked that I could download the 14.18.1 version here:

`sudo npm install -g inherits n && sudo n 14.18.1`

That's how it was solved

**Comment by whitetiger264** [comment]
@Gummikavalier  This problem seems to be back again, tried upgrading from 4.7.4 to 4.8.2 today and getting a similar segmentation fault on CentOS 7 again:

```
Jul 22 16:43:14 core systemd: rocketchat.service: main process exited, code=killed, status=11/SEGV
Jul 22 16:43:14 core systemd: Unit rocketchat.service entered failed state.
Jul 22 16:43:14 core systemd: rocketchat.service failed.
[root@core ~]# 
```
```
[root@core server]# node /opt/Rocket.Chat/main.js
/opt/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:92
					return fn.apply(this, arguments);
					          ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1412:11)
    at runWebAppServer (packages/webapp/webapp_server.js:996:48)
    at packages/webapp/webapp_server.js:1494:1
    at module (packages/webapp/webapp_server.js:1494:16)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /opt/Rocket.Chat/programs/server/packages/webapp.js:1963:15
    at /opt/Rocket.Chat/programs/server/packages/webapp.js:1972:3
    at /opt/Rocket.Chat/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /opt/Rocket.Chat/programs/server/boot.js:226:21
    at /opt/Rocket.Chat/programs/server/boot.js:464:7
    at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
    at /opt/Rocket.Chat/programs/server/boot.js:463:13
[root@core server]#
```
