### ISSUE TITLE
MongoDB deprecation message - documentation url gives 404

### ISSUE THREAD

**Issue by silverstorm** [RocketChat/Rocket.Chat#23345]
### Description:

The MongoDB deprecated message contains an url to the documentation page that doesn't exist.

> rocket.cat
> 5:37 AM
> MongoDB Deprecated
> MongoDB version 4.0.27 is deprecated, please upgrade your installation.
> https://rocket.chat/docs/installation

### Steps to reproduce:

Click the link in de deprecation message.

### Expected behavior:

Valid url to install or even better update documentation page.

### Actual behavior:

A beautiful 404 (Lost in space) page appears

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.0
- Operating System: debian 11
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: page
- NodeJS Version: 12.22.1 - x64
- MongoDB Version: 4.0.27 

### Client Setup Information

- Desktop App or Browser Version: Rocket.chat electron app
- Operating System: various

**Comment by aleadco** [comment]
This is an error from the rocket.chat web service so the URL may exist. Couple of days ago rocket.chat is returning 406

![image](https://user-images.githubusercontent.com/35962168/135739268-e9903bb8-c842-4064-a9c6-2822e0aca8a1.png)
