### ISSUE TITLE
[4.0.0] - LDAP - broadcast channel does not have any members after the upgrade to 4.0.0

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#23359]
### Description:

LDAP - setup
Broadcast channel does not have any members after the upgrade to 4.0.0.

### Steps to reproduce:

1. upgrade to 4.0.0
2. check the members of a broadcast channel.
3. List is empty

### Expected behavior:

I'm expecting to see the list of members inside the broad channel

### Actual behavior:

No members found

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.0
- Operating System: Rocky Linux 8
- Deployment Method: tar
- Number of Running Instances:  3 
- DB Replicaset Oplog:  yes
- NodeJS Version: 12.20.1
- MongoDB Version: 4.2.17

### Client Setup Information

- Desktop App: 3.5.6
- Operating System: Fedora 34

### Additional context

Users are sync via LDAP

Please let me know if you need more information.

**Comment by ostjen** [comment]
hey @TimmiORG , I have a few questions for you

1) what edition are you using ?
2) if you're using community edition right now, were role sync activated before 4.0.0?
3) does it happen only on broadcast channels?

**Comment by TimmiORG** [comment]
Good morning, just updated to 4.0.1 and the issue looks like solved. The users are back inside the broadcast channel.
