### ISSUE TITLE
Access with windows desktop APP failed with error code net:ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by alfrescoo** [RocketChat/Rocket.Chat#2335]
Your Rocket.Chat version: (make sure you are running the latest)
I deployed the 0.19 release with docker on Ubuntu 14.04.

I use the self-signed SSL with the following : 
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certificate.key -out /etc/nginx/certificate.crt

Access https://XX.XX  is ok, but access through windows desktop APP failed.
The error is "Not a valid instance URL" and the error code is net:ERR_INSECURE_RESPONSE.

Is there any hint? Many thanks.

**Comment by alfrescoo** [comment]
My desktop app version is 1.0.0 and my server address is https://dingding.so

**Comment by engelgabriel** [comment]
Hi, for security reasons the Mobile and Desktop apps do not support self-signed SSL.
