### ISSUE TITLE
Can't find migration version 239

### ISSUE THREAD

**Issue by strasharo** [RocketChat/Rocket.Chat#23356]
### Description:

Rocketchat refused to start after upgrading to 4.0.0 throwing this exception:

Can't find migration version 239

### Steps to reproduce:

  1)  deploy rocketchat 3.18.1 on Ubuntu 18.04.6 LTS
  2)  run rocketchatctl update

### Expected behavior:
Rocketchat should start.

### Actual behavior:
Refuses to start with the following exception

Can't find migration version 239

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.0
- Operating System: Ubuntu 18.04.6 LTS
- Deployment Method: RocketChatCTL
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.6
- MongoDB Version: 4.0.27

### Client Setup Information

- Desktop App or Browser Version: FF latest
- Operating System: Fedora

### Relevant logs:

rocketchat[25777]:     at /opt/Rocket.Chat/programs/server/boot.js:226:21
rocketchat[25777]:     at /opt/Rocket.Chat/programs/server/boot.js:464:7
rocketchat[25777]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:280:14)
rocketchat[25777]:     at /opt/Rocket.Chat/programs/server/boot.js:463:13 {
rocketchat[25777]:   isClientSafe: true,
rocketchat[25777]:   error: "Can't find migration version 239",
rocketchat[25777]:   reason: undefined,
rocketchat[25777]:   details: undefined,
rocketchat[25777]:   errorType: 'Meteor.Error'
rocketchat[25777]: }

**Comment by strasharo** [comment]
Temporary fixed it using this:
https://github.com/RocketChat/Rocket.Chat/issues/23358#issuecomment-933377766

**Comment by geekgonecrazy** [comment]
This has now been fixed in update of rocketchatctl. 🙏  should be able to use: `rocketchatctl upgrade-rocketchatctl` to get latest version of rocketchatctl which should now upgrade properly
