### ISSUE TITLE
Update to 4.0.0 broke GitHub webhook integration

### ISSUE THREAD

**Issue by abbluiz** [RocketChat/Rocket.Chat#23368]
### Description:

I have configured an webhook integration so that push events from GitHub is notified through Rocket.Chat. But now GitHub receives an 400 error from the server.

### Steps to reproduce:

1. Produce a push event, so that GitHub attempts to send the event through webhook URL

### Expected behavior:

1. Produce a push event, so that GitHub attempts to send the event through webhook URL
2. GitHub receives an OK from Rocket.Chat instance
3. Event is processed through custom script in Rocket.Chat
4. Notification is delivered to specific chat/room in Rocket.Chat

### Actual behavior:

1. Produce a push event, so that GitHub attempts to send the event through webhook URL
2. GitHub receives an 400 error from Rocket.Chat instance
3. Notification is not received

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.0
- Operating System: Ubuntu 20.04
- Deployment Method:  Docker
- Number of Running Instances:  1
- DB Replicaset Oplog: oplog Enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.17 / wiredTiger

### Client Setup Information

(Probably irrelevant in this case)

- Desktop App or Browser Version: Firefox 92.0.1
- Operating System: Fedora 34

### Additional context

Here is the JavaScript that process the event:

```javascript
String.prototype.capitalizeFirstLetter = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
}

const getLabelsField = (labels) => {

    let labelsArray = [];
    labels.forEach(function(label) {
        labelsArray.push(label.name);
    });

    labelsArray = labelsArray.join(', ');

    return {
        title: 'Labels',
        value: labelsArray,
        short: labelsArray.length <= 40
    };

};

const githubEvents = {

    ping(request) {
        return {
            content: {
                text: '_' + request.content.hook.id + '_\n' + ':man_farmer: :woman_farmer: Aoba'
            }
        };
    },

    push(request) {

        const commits = request.content.commits;
        const branch = request.content.ref.split('refs/heads/').pop();
        const user = request.content.sender;
        const repositoryName = request.content.repository.name;
        const repositoryUrl = request.content.repository.url;

        let attachmentCommits = [];

        for (let i = 0; i < commits.length; i++) {

            let attachmentCommit = {};
            let commit = commits[i];
            let shortID = commit.id.substring(0,7);

            attachmentCommit['text'] = 'Commit [' + shortID + '](' + commit.url + '): ' + commit.message;

            // Adiciona thumb do autor somente no primeiro commit
            if (i == 0) {
                attachmentCommit['thumb_url'] = user.avatar_url;
            }

            attachmentCommits.push(attachmentCommit);

        }

        return {
            content: {
                text: '**[' + user.login + '](' + user.html_url + ')** ' + 
                      'enviou alterações para ' + 
                      '**[' + repositoryName + '](' + repositoryUrl + ')** ' +
                      'na branch **' + branch + '**',
                attachments: attachmentCommits,
            }
        };
    },

};

class Script {

    process_incoming_request({ request }) {

        const header = request.headers['x-github-event'];
        if (githubEvents[header]) {
            return githubEvents[header](request);
        }

        return {
            error: {
                success: false,
                message: 'Evento GitHub não suportado pelo Rocket.Chat'
            }
        };

    }

}
```

### Relevant logs:

Could not find related logs.

**Comment by Gummikavalier** [comment]
I've noticed in RC 3.x.x that there has been a deprecation notification that webhooks writing to to channels where the user is not part of stops working in RC 4.0.0.

Does it help with the issue if you add the bot user `rocket.cat` into the channel of webhook as a member?

**Comment by abbluiz** [comment]
@Gummikavalier You were right; I included the user that the notification is posted with and it worked. Thanks for the answer!

**Comment by sampaiodiego** [comment]
as pointed out by @Gummikavalier this behavior changed on 4.0.0 as per https://github.com/RocketChat/Rocket.Chat/pull/23310

this is also outlined on the breaking changes list.. pls make sure to read carefully all other breaking changes. :)
