### ISSUE TITLE
"Media Type Not Accepted: undefined" when uploading files with some extensions

### ISSUE THREAD

**Issue by marek-ciazynski** [RocketChat/Rocket.Chat#23388]
### Description:

I have set both `FileUpload_MediaTypeWhiteList` and `FileUpload_MediaTypeBlackList` to blank, so that all files should be accepted. When uploading files with name ending with some extensions (like `script.py`, `exampe.file`or `file_with_no_ext`) I get error that the file media type `undefined` is not accepted. It doesn't matter if the file for example really is Python script or any kind of binary file. However just adding `.zip` to the name of the file makes it uploadable, even if it is not a ZIP archive. 

### Steps to reproduce:

1. Go to any room/chat
2. Create text files `text_file`, `script.py` and try to upload them
3. Rename the files adding `.zip` at the end, and upload them again.

### Expected behavior:

All files should be uploaded successfully since media type white list setting is blank.

### Actual behavior:

Only files with `.zip` "extension" were uploaded. First two files (before renaming) results in an error "Media Type Not Accepted: undefined"

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.0
- Operating System: Ubuntu 20.04.3 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.17 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chrome 94.0
- Operating System: Ubuntu 20.04

### Additional context

File Upload settings:
![settings](https://user-images.githubusercontent.com/20818349/136215239-30ba28e0-cf16-4110-88df-5f53233db63d.png)

**Comment by giterium** [comment]
I have the same thing. This is a very unpleasant problem.

**Comment by jarbelix** [comment]
I have the same problem```
Deployment
Versão
4.0.1
ID instalação
CRNfhR8mWSSkpWkjx
Versão da Apps Engine
1.28.0
Versão do Node
v12.22.1
Migração de banco de dados
240 (8 de Outubro de 2021 às 13:00)
MongoDB
5.0.3 / wiredTiger (oplog Ativado)
Detalhes do Commit
HEAD: (accdbc6b4)
Branch: HEAD
PID
1
```

**Comment by tatem68** [comment]
Problem in Server 4.0.2 (Ubuntu), Client 3.5.7 win x64. This is a very unpleasant problem.

**Comment by gabriellsh** [comment]
@Cleod9 @jarbelix, Fix #23474 was released on version 4.1.0, and should fix this behavior. If after upgrading the problem still occurs, please, reopen the issue.
