### ISSUE TITLE
Auto Translate Works on Click but Not Automatically

### ISSUE THREAD

**Issue by LucasCioffi** [RocketChat/Rocket.Chat#23383]
### Description:

When auto-translate is turned on in a group channel it is working when I click "Translate" but it is not automatically translating.

### Steps to reproduce:

1. Turn on auto-translate in a channel and select English as your language.
<img width="351" alt="Screen Shot 2021-10-05 at 6 13 14 PM" src="https://user-images.githubusercontent.com/1825103/136109940-098e0b25-0462-403f-b188-6922c0610734.png">
2. The other person turns on auto-translate and selects Spanish.
3. The Spanish speaker types in Spanish: "Hola estoy escribiendo en español."
4. The English speaker sees it in Spanish:
<img width="299" alt="Screen Shot 2021-10-05 at 6 14 59 PM" src="https://user-images.githubusercontent.com/1825103/136110140-e1d1b316-a426-4633-b1cd-b68d0d238d30.png">
5. The English speaker can click "View Original" but they should probably see "Translate" instead.
<img width="790" alt="Screen Shot 2021-10-05 at 6 18 18 PM" src="https://user-images.githubusercontent.com/1825103/136110461-5a0514e5-8ea7-4be1-9d13-6d50067ec8c8.png">
6. After clicking "View Original" the message is translated.
<img width="290" alt="Screen Shot 2021-10-05 at 6 19 03 PM" src="https://user-images.githubusercontent.com/1825103/136110553-55402efc-2d9a-4988-b8da-8a8ac8686e82.png">
7. After being translated, the message says "View Original" and that is finally correct.
<img width="822" alt="Screen Shot 2021-10-05 at 6 21 10 PM" src="https://user-images.githubusercontent.com/1825103/136110745-d84a771c-8bf3-4332-b8af-43f9e2804891.png">
8. After a page refresh it will show the translate icon to indicate the message was translated.
<img width="294" alt="Screen Shot 2021-10-05 at 6 20 28 PM" src="https://user-images.githubusercontent.com/1825103/136110683-6fe83356-2e9a-45c6-a0a9-a2efc6f211fd.png">

This may be similar to [this bug](https://forums.rocket.chat/t/google-auto-translate-broken-after-update-to-3-7-0-manual-translate-works/8784) and [this issue](https://github.com/RocketChat/Rocket.Chat/issues/19124).
Do I need to check if users are properly subscribed as mentioned [here](https://github.com/RocketChat/Rocket.Chat/blame/79362d080058b492e41cf79d585a61ffdad9b28f/app/autotranslate/client/lib/autotranslate.js#L64)?

### Expected behavior:

I would have expected messages to appear translated automatically without a user having to click the "Translate" button for each message.

Any help will be greatly appreciated!

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Linux
- Deployment Method: Git
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 12.14
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Mac OS and Linux; same result

**Comment by AMWRI** [comment]
Hi. It seems I have the exact same issue - across various browsers, on the app, and in both admin and standard user profiles. Its a shame because it would otherwise be such a useful feature!

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
