### ISSUE TITLE
Question about GitHub integration

### ISSUE THREAD

**Issue by zb471914758** [RocketChat/Rocket.Chat#2339]
Your Rocket.Chat version: (make sure you are running the latest)
![meteor web](https://cloud.githubusercontent.com/assets/17021819/13313927/aab015cc-dbdc-11e5-9542-5aca0dd57ff2.png)

**Comment by sampaiodiego** [comment]
This is done by hubot, it was done that way because we got the hubot integration before we have webhooks.
Now you can configure the both.

**Comment by zb471914758** [comment]
@sampaiodiego Does the hubot integration mean the code packages/rocketchat-hubot and the hubot.coffee script? Thanks!

**Comment by sampaiodiego** [comment]
@zb471914758 no.. this `hubot.coffe` is an internal hubot and the one who has the github integration is the one from the repo https://github.com/RocketChat/Rocket.Chat.Hubot

maybe @Sing-Li can explain better why we have both.

**Comment by Sing-Li** [comment]
Thanks, @sampaiodiego  ---   I'll try :)

So @zb471914758, there are two different ways you can have GitHub activities posted to a channel.

1.  The easiest is incoming webhooks. Menu : Admin->Integrations   This is also one of the newest feature we have.   It requires no additional server resources and is quite easy to configure.

2.  The second one is via our NPM hubot-in-a-module, named BaronBogo : https://www.npmjs.com/package/hubot-baronbogo       You'll need to run this on a separate process or server for it to work.   The image you posted above is from BaronBogo.

The internal bot (named Rocket.Cat)  is designed for those who wants to experiment with hubot technology but do not want to, or do not have access to, additional server resources.  It is relatively limited, and currently does not support GitHub integrations.

**Comment by zb471914758** [comment]
@sampaiodiego When I install hubot-baronbogo, 
export REPOSITORY_NAME="RocketChat/Rocket.Chat"
export HUBOT_GITHUB_EVENT_NOTIFIER_TYPES=issues
and then execute
bin/hubot
hubot> hubot our issues
but I get nothing, and get an error  "ERROR { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }"

Do you know why? Thank you very much!

**Comment by engelgabriel** [comment]
Depends on #2426

**Comment by engelgabriel** [comment]
We will remove the dependency on hubot on the next version

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by andreas-bulling** [comment]
@engelgabriel the example scripts are extremely helpful. Any chance these could be extended quickly with an example that allows git pushes to be shown with the corresponding commit message(s) and an URL to the commit?

**Comment by engelgabriel** [comment]
We are working on that, and w way to share scripts via a online catalogue too.

**Comment by supriya999** [comment]
Are there any example scripts to integrate incoming webhook in rocket chat from gogs webhook?
I tried this script but its not working with combination gogs->rocket.caht
https://rocket.chat/docs/administrator-guides/integrations/github

**Comment by geekgonecrazy** [comment]
@supriya999 beauty of Rocket.Chat is you can actually just use the slack webhook option in gogs and give it the integration URL and it'll just work.

Looks like main question was answered.  Closing
