### ISSUE TITLE
mongodb deprecated version: link to doc insted of rocket.chat home page

### ISSUE THREAD

**Issue by deogracia** [RocketChat/Rocket.Chat#23397]
### Description:
Since #23381 , using a deprecated mongoDB version, the message link to https://go.rocket.chat/i/mongodb-deprecated, which leads me now to https://rocket.chat/. That redirection, doesn't help, IMO.

It should redirect us to https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/mongo-versions for example.

### Steps to reproduce:

1. use rocket.chat >= 4.0.0 with a deprecated mongodb version (3.6 for example)
2. as an admin user, you should get a direct message  pointing you to https://go.rocket.chat/i/mongodb-deprecated
3. https://go.rocket.chat/i/mongodb-deprecated redirects you to https://rocket.chat/

### Expected behavior:

https://go.rocket.chat/i/mongodb-deprecated redirects you to https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/mongo-versions

### Actual behavior:

https://go.rocket.chat/i/mongodb-deprecated redirects you to https://rocket.chat/

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: debian 9
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: set
- NodeJS Version: 12.22.1
- MongoDB Version: 3.6.23

### Client Setup Information

- Desktop App or Browser Version: -
- Operating System: -

### Additional context

N/A

### Relevant logs:

N/A

**Comment by skibbipl** [comment]
Also it would be nice to update documentation how to migrate mongodb versions in docker. I'm not sure how to do it correctly, all my attempts failed...
