### ISSUE TITLE
Cleanup in master

### ISSUE THREAD

**Issue by warcode** [RocketChat/Rocket.Chat#234]
Currently the master branch contains all kinds of appids, og-refs and tracking that really shouldn't be there.

Forking the repo should yield a clean base that a user can deploy without the need for external services and without leaking any information to 3rd parties.

**Comment by engelgabriel** [comment]
That's why it is not a 1.0 yet :)

Do you want to do a PR with the thing you think should be removed to help us out?

**Comment by engelgabriel** [comment]
We will be able to do this, when we finish #222

**Comment by engelgabriel** [comment]
All IDs are now stored on the Database
