### ISSUE TITLE
pobieranie pamięci

### ISSUE THREAD

**Issue by mlynarczykj** [RocketChat/Rocket.Chat#23403]
Cześć,

Rocket potrafi pobrać u mnie blisko 2 GB pamięci ram. Czy to normalne działanie?
![image](https://user-images.githubusercontent.com/91243681/136377480-89cb66a6-4f07-449b-ae4b-c4290dc94725.png)

Reset danych aplikacji niczego nie zmienił.
Po restarcie samej aplikacji wielkość spadła do około 500-600 MB co i tak jest sporą liczbą.
 
Pozdrawiam
Jacek Młynarczyk

**Comment by hugocostadev** [comment]
Please, open the issue in english following the template, thanks
