### ISSUE TITLE
Browser not updating new Omnichannel / updating chat without refresh

### ISSUE THREAD

**Issue by dredge999** [RocketChat/Rocket.Chat#23421]
We have an instance with 4.01 in which any browser on a particular client machine is not updating an existing chat or showing a new Omnichannel chat without a browser refresh.

This has been observed in Chrome and Brave browsers.  
Updates to both can be seen on other machines/chrome/brave/firefox so it appears to be limited to this account or this machine.
We don't see any issues in the debug console (such as cannot connect wss, etc).

Anyone have any ideas as to why this would happen to this one client and/or tips on debugging this issue?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
