### ISSUE TITLE
Too much url encoding utf8 channel link

### ISSUE THREAD

**Issue by nishimaki10** [RocketChat/Rocket.Chat#2342]
Rocket.Chat version: HEAD (hash: a1488beb40ee4733fa0e07c452457642c07bada3)

&lt;a title="あ" href="/channel/%25E3%2581%2582" class="open-room"&gt;...&lt;/a&gt;
1. あ -> %E3%81%82
2. %E3%81%82 -> %25E3%2581%2582

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
