### ISSUE TITLE
Secret URL, broken.

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#2343]
Your Rocket.Chat version: 0.18.0

I think registration by secret URL is broken in this version. When one accesses the secret URL it just says: "The URL provided is invalid". This feature used to work fine previously.
(nothing of value in the logs)

**Comment by marceloschmidt** [comment]
It seems to be working on 0.20.0. @k0nsl could you check if it works for you? 
Thanks.

**Comment by k0nsl** [comment]
@marceloschmidt: good to know; I am in the process of upgrading my instance later tonight, and will report back.

**Comment by k0nsl** [comment]
I updated to 0.20.0 and it is still broken for me; same message as described in my initial comment.

**Comment by marceloschmidt** [comment]
Can you please post a screenshot of the error message? If possible, also include a screenshot of your administration settings (where it states the secret key, if you can show it to us). Thanks.

**Comment by marceloschmidt** [comment]
Also, please make sure your Registration Form settings above it says: "Secret URL".

![image](https://cloud.githubusercontent.com/assets/1986378/13469041/60d9f95c-e084-11e5-9ef8-479eef1c88a4.png)

**Comment by k0nsl** [comment]
Hi,

Upgrading to 0.20.0 solved the problem. I didn't save any screenshots, unfortunately.

My registration form settings looks like this, and always did:
![selection_122](https://cloud.githubusercontent.com/assets/2517921/13534155/0c2efd6a-e234-11e5-92b3-384c154017e2.png)

**Comment by kicdu** [comment]
Using 'Secret URL' option on 0.20.0 and I got only 'Spinner' page without Registration form.

**Comment by marceloschmidt** [comment]
@kicdu could you send a printscreen of the error, please? can you also check your developer console for bugs? Thanks

**Comment by kicdu** [comment]
@marceloschmidt I had problem with apache in rev. proxy mode. corrected this and now the secret url is working. sry for bothering and thanks for quick response. keep up good work ;)
