### ISSUE TITLE
Cannot send message with Zapier. SSL certificate has expired.

### ISSUE THREAD

**Issue by chriscollins405** [RocketChat/Rocket.Chat#23435]
### Description:

When creating a Zap and adding the action "send a message"
![image](https://user-images.githubusercontent.com/65848492/136787650-c1e1e360-b423-4de3-b350-e7e3c61a5103.png)

I add my URL here...
![image](https://user-images.githubusercontent.com/65848492/136787717-02ac6221-fca9-4df8-8906-345012495a45.png)

I click the authorize button here....
![image](https://user-images.githubusercontent.com/65848492/136787777-fd39a56b-02af-4395-8c28-06a9908e5721.png)

And then it shows this error...
![image](https://user-images.githubusercontent.com/65848492/136787812-b534f781-9062-4f84-8369-577393078808.png)

I would imagine this is down to the latest lets encrypt root certificate issues. Is the rocketchat server using ubuntu 16 or similar where the new root certs have not been updated?

**Comment by MightyGoldenOctopus** [comment]
Have the same issue on our installation, kind of a blocker and our account manager have a 3 months latency when we describe zapier integration issues  as a blocker for stepping up to any enterprise license.

**Comment by maeries** [comment]
Can someone tell if that problem originates from our rocket chat instance or is it a problem on zapier's site?

**Comment by bscheewe** [comment]
I'm having the same problem.  Were you able to find a solution?  Is your NATed behind a firewall with cert inspection?  We are using Fortigate, but I've disabled cert inspection and still get the error.

**Comment by MightyGoldenOctopus** [comment]
Yes the problem persists on our `4.1.2` installation, we have a clear rule that opens the port `443` in our firewall so certificate inspection shouldn't be affected by it. The logs are the following:

```
I20211119-10:05:57.872(0) [OAuth2Server] POST /oauth/authorize?response_type=code&client_id=zapier&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2FRocketChatDevAPI%2F&state=XXXX
I20211119-10:05:57.873(0) [OAuth2Server] in getClient (clientId: zapier , clientSecret: null ) 
I20211119-10:05:57.878(0) [OAuth2Server] in saveAuthCode (code: XXXX , clientId: zapier , expires: 2021-11-19T10:06:27.876Z , user: { id: 'XXXX' } ) 
```

If it wasn't working in the past on the same installation I would think it is because of timezone issues, but we had no issues with zapier before, perhaps there has been a regression at that level.

**Comment by dudanogueira** [comment]
We confirmed it working on latest 4.5.X.

We just updated our Zapier docs, please, check it out:
https://docs.rocket.chat/guides/administration/admin-panel/integrations/zapier

SSL Certificate is probably a deployment error. Please, let us know if this issue still persists.
