### ISSUE TITLE
Impossible de mettre à jour de la V 3.4 vers la V 3.5.7

### ISSUE THREAD

**Issue by ccesetti** [RocketChat/Rocket.Chat#23436]
La mise à jour ne se lance pas malgré ma validation dans un environnement Windows 
![Rocket 2](https://user-images.githubusercontent.com/9976298/136792288-4b83b2e4-a5a9-436e-94e8-317f6f0ded9d.jpg)
![Rocket 1](https://user-images.githubusercontent.com/9976298/136792294-fde5190f-a839-446c-a57d-bb9d1da3f413.jpg)
10

**Comment by hugocostadev** [comment]
please, submit the issue in english and follow the issue template
