### ISSUE TITLE
Broken CSS on chat window after upgrading to 4.0.1

### ISSUE THREAD

**Issue by mr-karan** [RocketChat/Rocket.Chat#23438]
### Description:

CSS is borked on Responsive view after upgrading to 4.0.1

### Steps to reproduce:

1. Open a chat window on any screen with `width <=500px`.
2. Notice the send message/file buttons collapse on the left side

### Expected behavior:

Icons should not collapse on one side.

### Actual behavior:

![rc_css](https://user-images.githubusercontent.com/5689132/136898682-719d2348-976c-46c4-82f7-fbdb2cc895fa.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.1
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 4.2.17 / wiredTiger (oplog Enabled)
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.17 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 93.0 (64-bit) 
- Operating System: arch-linux

### Additional context

NA

### Relevant logs:

NA

**Comment by abhiraj-kale** [comment]
> ### Description:
> CSS is borked on Responsive view after upgrading to 4.0.1
> 
> ### Steps to reproduce:
> 1. Open a chat window on any screen with `width <=500px`.
> 2. Notice the send message/file buttons collapse on the left side
> 
> ### Expected behavior:
> Icons should not collapse on one side.
> 
> ### Actual behavior:
> ![rc_css](https://user-images.githubusercontent.com/5689132/136898682-719d2348-976c-46c4-82f7-fbdb2cc895fa.png)
> 
> ### Server Setup Information:
> * Version of Rocket.Chat Server: 4.0.1
> * Operating System: Ubuntu 18.04
> * Deployment Method: docker
> * Number of Running Instances: 1
> * DB Replicaset Oplog: 4.2.17 / wiredTiger (oplog Enabled)
> * NodeJS Version: v12.22.1
> * MongoDB Version: 4.2.17 / wiredTiger (oplog Enabled)
> 
> ### Client Setup Information
> * Desktop App or Browser Version: Firefox 93.0 (64-bit)
> * Operating System: arch-linux
> 
> ### Additional context
> NA
> 
> ### Relevant logs:
> NA

The fix to this already in 4.10 update. Please update it

**Comment by mr-karan** [comment]
This is fixed with 4.1.0. Thanks
