### ISSUE TITLE
[Bug] Admin can't set or add owner of chat in proper way since 3.17.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#23437]
### Description:

That issue related to https://github.com/RocketChat/Rocket.Chat/issues/17172 and new server behavior described in here https://github.com/RocketChat/Rocket.Chat/issues/17172#issuecomment-931926420 and first here https://github.com/RocketChat/Rocket.Chat/issues/17172#issuecomment-909948407 by @onigoets 

Before 3.17.0 we have had a 2 ways of changing owner of some chat:
#### Proper way (but not so straightforward as described by @pierre-lehnen-rc  here https://github.com/RocketChat/Rocket.Chat/issues/17172#issuecomment-611126320 )

- Go to admin / Permissions
- Edit the "Owner" role
- Select the room you want to change the owner of by searching for it's name
- Search for the user you want to add as owner and click on the 'Add' button.

#### Barbarian way (wrong and not private)

- Convert Private Chat to public
- Find that Public Chat
- Add\Change owner
- Convert Public Chat to Private chat again in chat settings.

Now since 3.17.0 we don't have a proper and private way to add new owner to some chat as administrator.

### Steps to reproduce:

1. Go to admin / Permissions
2. Edit the "Owner" role
3. Select the room you want to change the owner of by searching for it's name
4. Search results is empty

### Expected behavior:

Search result should show room to change owner.

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/136891466-e859ec25-77ac-4e01-900a-4aa8d37dcdea.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.15

### Client Setup Information

- Desktop App or Browser Version: Chrome 94
- Operating System: Windows 10

### Additional context

I guess we still have a [workaround](https://github.com/RocketChat/Rocket.Chat/issues/17172#issuecomment-852743853) by @emikolajczak in mongo, but it not so convenient like Admin UI
`db.rocketchat_subscription.update({ "rid": "room-id", "u._id": "user-to-add-id" }, { $push: { "roles": "owner" } } );`

### Relevant logs:

No

**Comment by ankar84** [comment]
still an issue in 4.2.0

**Comment by ankar84** [comment]
Still an issue in 4.2.2

**Comment by ipikiiskinen** [comment]
Still an issue in 4.3.1

**Comment by ankar84** [comment]
Still and issue in 4.6.2

**Comment by ankar84** [comment]
Could be fixed in https://github.com/RocketChat/Rocket.Chat/pull/26423

**Comment by ankar84** [comment]
Still an issue in 5.1.0 release

**Comment by matthias4217** [comment]
I can use the proper (but not intuitive) way in `4.8.6` on my instance. As I've never used this feature before, I don't know how long it's been fixed.

Not directly related to this, but the Owner of a room displayed in Administration > Rooms is not the same (and can even be deactivated member), and this is confusing. I suppose what I see in Rooms is the creator of the room ?

**Comment by matthias4217** [comment]
Oh, it seems I was wrong. Only five channels appear in the search, some public, some private, but the rest isn't there.

**Comment by ankar84** [comment]
still an issue in 5.3.5

**Comment by jdsatava127** [comment]
This is still an issue in 6.0.1. This makes it very difficult to change the owner of a room if the existing owner's account has been disabled.

**Comment by pierre-lehnen-rc** [comment]
Sorry about the long time to get to this.
The bug was introduced by #22618 

We're tracking it internally and will provide a fix soon.

**Comment by klepptor** [comment]
Hi @pierre-lehnen-rc 

seems there is still no solution for this, as this bug/feature still exists in 6.6.6 (not tested 6.7 yet).

Is there any chance it still will ever be adressed? It's such a basic feature to change the owner of a channel etc as organisations evolve over time I think everybody using RC in teams with more than 2 members must be missing it....
