### ISSUE TITLE
Notifications on all activity / server version 4.0.1

### ISSUE THREAD

**Issue by hoppedmalt** [RocketChat/Rocket.Chat#23447]
### Steps to reproduce:

1. Use rocket chat

### Expected behavior:

Get audible notification if you are mentioned.

### Actual behavior:

Get audible notification on every single message, on any channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.1
- Operating System: Linux 
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: macos

### Additional context

Default notification setting selected on all channels, resulting in this behaviour. Problem appeared after the server was upgraded to version 4.0.1.

**Comment by matheusbsilva137** [comment]
Hey, everyone! 👋 
Sorry for this annoying behavior and thanks for providing such a detailed analysis on what is going on and suggesting ways to fix it, @soundstorm ! As you can see, we already have a PR to fix this issue from the application's side and we'll keep you posted as we work on resetting the notifications cap.
We expect to deliver this fix before the Release Candidate (which is scheduled to the 20th).
Thanks!

**Comment by cs35-owncloud** [comment]
Hello everyone,

thanks for the support ! If the release comes soon I prefer to stick to it rather than patch and maybe have some downsides.
Mostly I fear my users :'D
Thanks again !

**Comment by soundstorm** [comment]
But unfortunately not this month released 🙄

**Comment by soundstorm** [comment]
Is there any planned release date?

**Comment by soundstorm** [comment]
Why was this excluded from 4.1.1? @sampaiodiego

**Comment by emikolajczak** [comment]
@soundstorm you can join to upcoming  community call https://forums.rocket.chat/t/community-open-call-november-10-2021/12411 and ask rocket.chat deciders. Bug fixing in rocket.chat is totally not understandable.

**Comment by cs35-owncloud** [comment]
Good news everyone, it seems it's released in [4.1.2](https://github.com/RocketChat/Rocket.Chat/releases/tag/4.1.2)
It's not yet available in the dockerhub so I can't tell how the fix is working.

**Comment by soundstorm** [comment]
Updated right before your comment. Database is migrated, so all mobileNotifications entries are now pushNotifications and changes from the web apply to the database. But seems like the mobile App (iOS) still uses the old identifier and reads/saves to mobileNotifications 🧐
So is the REST API not updated?!

**Comment by soundstorm** [comment]
Seems like the App is somehow not using the API or I don't know, since the migration file is now the only appearance of the keyword mobileNotifications.

**Comment by soundstorm** [comment]
Okay, simple rename lead to a chain of failures 🤦‍♂️
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/69a67ea998a6db62dc7932b3851c851ac4fb1ef3/app/views/UserNotificationPreferencesView/options.js
