### ISSUE TITLE
Uncaght TypeError

### ISSUE THREAD

**Issue by mzch** [RocketChat/Rocket.Chat#23444]
### Description:

After updaring to `4.0.1`, Browser reports `Uncaght TypeError: Cannot convert undefined or null to object`.

### Steps to reproduce:

1. Restart Rocket.Chat server
2. Login via Chrome or others

### Expected behavior:

Connect to the server correctly.

### Actual behavior:

Show `Connecting...` message repeatedly.

### Server Setup Information:

- Version of Rocket.Chat Server: `4.0.1`
- Operating System: Debian 11.1
- Deployment Method:  tarD
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.6
- MongoDB Version: `5.0.2`

### Client Setup Information

- Desktop App or Browser Version: Chrome `94.0.4606.71`
- Operating System: macOS `11.6`

### ScreenShot:

<img width="1492" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/136991762-3cf90fd3-6362-446d-a92b-d5edd332fcd3.png">

### Logs

There is no erver log.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
