### ISSUE TITLE
Access to integration section

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat#2346]
When "Manage integration" is granted to a role, users in this role doesn't see the Administration menu to access the Integration section. They have to use the [...]/integrations URL to access it.

Is it possible to show the Integration menu when Manage integration is granted?

Thank you.

Rocket.Chat version: 0.19

**Comment by javaning** [comment]
Rocket.Chat version: 0.20.
Room owner met the same scene. 

Does it more convenient, If bring these managements or settings to the operating channel live on the flex-tab-bar?
