### ISSUE TITLE
Error while upgrading to 4.x - Can't edit profile information anonymous user

### ISSUE THREAD

**Issue by hatung** [RocketChat/Rocket.Chat#23478]
Can't edit profile information anonymous user

### Steps to reproduce:

1.  Go to administration
2.  Click on an anonymous user
3. Edit some information and click save

### Expected behavior:

Save successful

### Actual behavior:
An error occurred:
 "Cannot read property '0' of undefined"

![image](https://user-images.githubusercontent.com/15026336/137580742-bcd37e1f-6b60-407b-88e4-bd42ded37a13.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.2
- Operating System: 
- Deployment Method:  Docker Image

### Additional context
([#23110](https://github.com/RocketChat/Rocket.Chat/pull/23110))

**Comment by Divyansh0811** [comment]
hi, can you tell me how can i access code for any specific version (4.0.2 in this case) ? The one which i have cloned has different version.
