### ISSUE TITLE
Misspell in email subject

### ISSUE THREAD

**Issue by StevenCarre** [RocketChat/Rocket.Chat#23470]
Hi,

there are multiple misspells in the French translations in emails
Here's one:
in email subject 
"[Fidesio] Votre nom a été mensionné Elisa dans le channel #mym"
it's "mentionné", rather
Thanks for reading

**Comment by hugocostadev** [comment]
Feel free to open pull request to fix the translations! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
