### ISSUE TITLE
The official Rocketchat docker-compose needs to be updated for newer version of MongoDB

### ISSUE THREAD

**Issue by Taubin** [RocketChat/Rocket.Chat#23479]
### Description:

Using the rocketchat docker-compose file here: https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml the instance installs Mongodb v4.0. When starting up rocketchat, it gives a warning stating mongodb 4.0 has been depreciated and needs to be at least 4.2. Updating the file to just 4.2 breaks due to changes in mongodb's file system. The docker-compose needs to be updated properly. 

### Steps to reproduce:

1. Install docker-compose version of rocket chat using the official instructions here: https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers/docker-compose
2. You will receive an error stating mongodb is depreciated
3. You will also receive multiple messages on your installation telling you it's depreciated. 

### Expected behavior:

The version of mongodb to be updating and the documentation updated to reflect the changes/ 

### Actual behavior:

![rocket_chat_depreciated](https://user-images.githubusercontent.com/8891792/137607865-70d7c23f-fcf2-4417-91c0-3f128b65c4bb.jpg)

![rocket_cat](https://user-images.githubusercontent.com/8891792/137607885-39abbf66-b6d0-4136-b9d4-2958f7f299b9.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server:  4.0.2
- Operating System: Ubuntu 20.04
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

**Comment by sneakyx** [comment]
As far as i understood, the `--smallfiles` options have to be removed, right?
