### ISSUE TITLE
RocketChat correct settings

### ISSUE THREAD

**Issue by MordimerMa** [RocketChat/Rocket.Chat#23481]
Hi.
Maybe someone of you can correct my setting of RocketChat. I have this filling, that I'm doing something wrong....

Server is running well. Users can login thru AD. But I can't manage whit users search. I (and all users) can see every user in AD.

Naturally I can remove users from RocketChat at setting/users. But this is not god way to do that. From all i can understand, when I will point out exact group (Rocket.Chat), then users in field search will be able to see only this users who is added to this group.

Where I need to put this group. Direct in AD tree (you can see on picture below), or maybe in AD/user/ RocketChat group?

There is my AD tree:

![2021-10-17_19h54_34](https://user-images.githubusercontent.com/57816235/137639733-b513b801-6d8d-49b1-9097-f8d605e78ccb.png)

There is my settings:

![2021-10-17_20h05_29](https://user-images.githubusercontent.com/57816235/137640135-e0466e22-a052-4592-9130-f667575b75fc.png)

I think I don't understand the descriptions in the settings exactly.

Can you help me?

Regards
RG (Mordimer)

**Comment by tmartincpp** [comment]
For configuration issues, you should not use github but https://forums.rocket.chat (please consider to close this bug).

**Comment by MordimerMa** [comment]
OK. I'm closing it.
