### ISSUE TITLE
Unable to upload files with iphone and ipad

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#23483]
### Description:

Can't upload files on iphone with latest IOS Update. Allows you to through the motions of selecting a file, etc, but no upload actually happens. Upload works fine on Mac and Windows desktops.

### Steps to reproduce:

1. Attempt to upload an image.
2. Once clicking submit, image is not uploaded.

### Expected behavior:

For image to upload.

### Actual behavior:

No image uploads

### Server Setup Information:

- Version of Rocket.Chat Server:  4.0.3
- Operating System: Centos 8
- Deployment Method: Tarball
- Number of Running Instances: 6
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version:4.0.27

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: iphone/ipad latest IOS version

**Comment by serviceman** [comment]
is there any word on this. I understand this is a volunteer community. I just have a lot of IOS users logging in with the web browser, so I am in great need for this to be fixed. This issue is also happening on open.rocket.chat

**Comment by bensaine** [comment]
I am having the same issue on my instance.

**Comment by ar33ny** [comment]
Having the same issue on our RC.

**Comment by bethrezen** [comment]
Any update on this?

**Comment by serviceman** [comment]
same thing is still happening on open.rocket.chat on 4.2.

**Comment by serviceman** [comment]
I understand that you have had your share of issues with rocket chat not installing on centos 7, but is there any intention of looking at this issue? It has been nearly two months since it has been reported and there have been no updates. I understand this is open source, and I would fix it myself if I could, but I'm loosing users due to this issue. If there is no plan to look at this issue, can someone in charge please say so, so I can start looking at alternatives? This issue is effecting 100's of my users. Again, thank you for such a great script, this is the only issue I am facing and I am getting daily complaints from my users about it.

**Comment by debdutdeb** [comment]
Hey @serviceman - sorry for the delayed response.

Could you please clarify, is this happening on **just** IOS devices using the web client? 

If so, which browser are they using?

**Comment by serviceman** [comment]
As far as I am aware it is only happening on IOS on the web client. I have had many reports of this and it's always on IOS on the web client. I also can reproduce this on my iphone XR with the latest IOS updates. This is happening on safari and chrome on IOS. You can open the file selection window, but when you select the image you want to use, it is not attached to the chat and the popup in chat doesn't appear to allow you to add a title, etc.

**Comment by debdutdeb** [comment]
Thanks. I'll check with our team, can't test since I don't have an IOS device.

**Comment by serviceman** [comment]
> Thanks. I'll check with our team, can't test since I don't have an IOS device.

Did you have any luck on this?

**Comment by serviceman** [comment]
This is still happening on 4.3.1 on the web browser on open.rocket.chat, as well as my instance. This issue was reported nearly 3 months ago and breaks a large portion of real use cases for rocket chat for anyone on an iphone, yet this issue has had no attention. Is it time to move on from Rocket Chat to another platform? I have attempted to debug this myself, there are not errors on the console on open.rocket.chat or my instance.  I have always defended the "this is an open source project" but if I was a paid member on rocket.chat I'd be experiencing the same issues. I am surprised beyond belief that such a major bug in such an important function in the script is allowed to allowed to remain, and receive no real attention, meanwhile there have been many new features added to rocket chat that would be used by a fringe group of users at best.

I reported this issue nearly 6 months ago, which pretty much breaks ALL use cases for rocket chat and it's just getting some attention after another user reports it. I had to resort to hacking it with custom javascript. https://github.com/RocketChat/Rocket.Chat/issues/24079

Is there a way to get this issue with uploads fixed? Crap, I'd even be willing to pay! I'd already be willing to be a paid member if there was a package offered that fit my needs. 

I know I'm venting here, and I don't mean to sound disrespectful, but this issue is 3 months old and I was told "I'll have my team look at it" nearly a month ago. I really am at the point of I need to get this fixed somehow, or I need to move on to a new platform. I really don't want to, it's a solid peace of programming, I am heavily vested into it with my custom code with my site, and my users generally love the system, but I can't have a "broken" system with nobody to reach out to to fix the issue. What is someone in my position supposed to do?

**Comment by serviceman** [comment]
This is still happening on 4.4.0 on open.rocket.chat as well as my instance. Again, this is happening on all IOS devices using the web version NOT the app.

**Comment by serviceman** [comment]
Still happening on 4.4.2

**Comment by Psherman42000** [comment]
@serviceman tente utilizar o app mobile que pode resolver seu problema, estou enfrentando o mesmo problema a uns meses já, se conseguir achar um jeito de resolver, por favor me avise também, farei o mesmo

**Comment by TedsCabin** [comment]
If you choose "Request Desktop Site" in Chrome on iOS it seems to work.

**Comment by TedsCabin** [comment]
After further investigation it may be related to this
[Rocket.Chat/apps/meteor/app/ui-message/client/messageBox/messageBoxActions.js](https://github.com/RocketChat/Rocket.Chat/blob/4ab08d28bc3876d83897a338d5c436b666a55baa/apps/meteor/app/ui-message/client/messageBox/messageBoxActions.js#L64-L66)

Lines 64 to 66 in [4ab08d2](https://github.com/RocketChat/Rocket.Chat/commit/4ab08d28bc3876d83897a338d5c436b666a55baa)

 if (navigator.userAgent.match(/(iPad|iPhone|iPod)/g)) { 
 	$input.click(); 
 } 
When using Chrome on Desktop, I can change the useragent via chrome DevTools to Mozilla/5.0 (iPod) and when you try to do an upload, it behaves weird and you get the upload dialog twice. If you remove iPod, iPhone, or iPad from the user agent it functions normally. This may be related to this issue.

**Comment by dudanogueira** [comment]
Hi! Can you confirm this still happens on latest 4.6.3?

I tried switching the user agent using a plugin in chrome to something Ipad, and I was able to upload a pdf and a jpg.

**Comment by serviceman** [comment]
I can confirm that it is still happening on 4.6.3 on iphone, with the latest IOS release. The "hack" I put above enables it to still work though.

**Comment by TedsCabin** [comment]
> Hi! Can you confirm this still happens on latest 4.6.3?
> 
> I tried switching the user agent using a plugin in chrome to something Ipad, and I was able to upload a pdf and a jpg.

I can confirm it still does not work in 4.6.3.  The user agent is case sensitive, so it has to be iPad.  Also you will be able to still upload via desktop even with the bug, but the file explorer dialog pops up twice which shows that something weird is going on.  On mobile browser, it just breaks entirely.

**Comment by derjohn** [comment]
Maybe it's behind a nginx proxy with max upload size? Browser does not hit that limit, mobile apps do. (I bet the Browser chunks the images in  smaller parts when uploading)

**Comment by salviof** [comment]
The problem persists in version 5.4.1

**Comment by CitizenDev** [comment]
Solved?
This issue still persists ver 6.4.8 and latest android client

**Comment by yahya-aghdam** [comment]
Same problem with v7
