### ISSUE TITLE
Allow system bot user to create users from alien systems 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2349]
For federation via matrix.org,  XMPP integration, and better Slack integration compatibility:
- add system-bot role
- add  alien-system-user role
- allow system-bot to create new users, including avatars, from alien systems
- allow system-bot to send messages on behalf of its alien users
- alien users created this way have no logon or message privileges

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.

**Comment by timkinnane** [comment]
Added as a proposal on #10174
