### ISSUE TITLE
LDAP username wrong

### ISSUE THREAD

**Issue by valessiobrito** [RocketChat/Rocket.Chat#2350]
1) Auth on Ldap with email:   valessio.brito@domain.com
2) and create wrong my username:  valessio.britodomain.com 

Rocket.Chat version: 0.18.0

**Comment by rodrigok** [comment]
Witch field are you setting as username field in RC's admin?

**Comment by valessiobrito** [comment]
Username Field = none/blank using default conf.

**Comment by rodrigok** [comment]
@valessiobrito you should inform the field from LDAP to use as username or we will try to use the value informed on login form.
