### ISSUE TITLE
Can't delete a room anymore

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat#2351]
I am a member of the admin role and since 0.19.0, there is no more Delete room button if I click on a room in the admin panel.

**Comment by pescobar** [comment]
I am having the same issue running 0.19.0 using the official docker image.

I cannot rename the channels either

**Comment by mikrobyte** [comment]
and this shall be available in the next version again right?

**Comment by sampaiodiego** [comment]
yes.. will be in 0.20 to be released today :wink:
