### ISSUE TITLE
Does iOS client not support tls?

### ISSUE THREAD

**Issue by Laisky** [RocketChat/Rocket.Chat#2352]
Your Rocket.Chat version:  
  - server: v0.19 with letsenctypt certification, 
  - iOS client: v2.2.2

My rocket.chat server is https://chat.laisky.com/ ,support tls1.0 - tls1.2

But I can not load the login page after connect to the server, it retry again and again.

I had tried to reset my device's network setting, and reinstalled the app, but nothing help.

Both on iPhone and iPad got the same problem. OSX client works quiet well.

![img_3041](https://cloud.githubusercontent.com/assets/4532436/13340601/9938b584-dc6c-11e5-9488-f07d89237d09.PNG)

**Comment by engelgabriel** [comment]
The SSL looks good

![image](https://cloud.githubusercontent.com/assets/1000217/13351132/5965e9c6-dc63-11e5-930f-deb63a6d0601.png)

Since letsenctypt is rather new, I wonder if there is come root certificate missing.

Let me me do some debugging from my side and get back to you.

**Comment by Laisky** [comment]
thanks for your response.

Browser, Windows client and OSX client is ok, the problem only happened on iOS client.

**Comment by engelgabriel** [comment]
What version of iPhone and iOS?

**Comment by Sugaroverdose** [comment]
In my deployment letsencrypt working perfectly, so it's not cert issue, even not cipher mismatch.
Check that your ROOT_URL environment variable value is https://chat.laisky.com/, i had almost the same issue when started rocket with http:// but after test moved to https:// but i didn't changed ROOT_URL value to indicate this.

**Comment by engelgabriel** [comment]
Thats a good point

**Comment by Laisky** [comment]
Change the ROOT_URL from `https://chat.laisky.com/` to `https://chat.laisky.com` solve the problem.

thanks very much for your help, it's my fault.

**Comment by timaschew** [comment]
I have this error for both iOS and Android app, webinterface working fine.
And if you're using the snap you're stucked now because you can't change the ROOT_URL.
see https://github.com/RocketChat/Rocket.Chat/issues/4971

**Comment by timaschew** [comment]
I changed to manual installation with ubuntu, set the proper ROOT_URL, but I still cannot connect with iOS or Android over HTTPS, only HTTP is working.

So please open this issue again
