### ISSUE TITLE
Activate Users / Modify Users on iPhone App

### ISSUE THREAD

**Issue by tmkis2** [RocketChat/Rocket.Chat#23530]
### Description:

We had set new users to be activated by admin only. So I tried to activate a new (test) user via the iOS Rocket.Chat App going to Administration -> Users -> selecting the User but nothing happens when I pressed the 3 dots to open up the Menu.
See here: [Screenshot 1](https://tmkis.cloud/s/qCJXgTMZZYWFwZM)
 Turning the iPhone (12 Pro Max) in landscape mode then the menu pops up. [Screenshot 2](https://tmkis.cloud/s/ZDrZfwajCHmFoD9)

### Steps to reproduce:

1. Set Users to be activated manually
2. Register new user
3. Try activating this user with iPhone Rocket.Chat App

### Expected behavior:

Should work regardless of holding mode of the phone.

### Actual behavior:

See Screenshots above.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.3
- Operating System: Ubuntu 20.04 LTS
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: MongoDB 5.0.3 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: iOS Rocket.Chat App
- Operating System: iOS 15.0.2

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
