### ISSUE TITLE
No response for start video/audio call

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat#23537]
### Description:

I installed Rocket.Chat and Coturn server in local, just enabled WebRTC and tried to testing video/audio call, but not work, also not found logs from Rocket.Chat and Coturn server.

![image](https://user-images.githubusercontent.com/4077255/138445915-1e7302f5-d89f-4c91-b500-4c072ea7d127.png)

I don't know what I missed or error configuation.

Thank you so much!

### Steps to reproduce:

1. Go to web broswer and open chat window.
2. Click on user and click "Start video/audio call"
3. No any answer and response when I click start video/audio call.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.0
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows 10 pro/Chrome 94

**Comment by akelon-user** [comment]
Hello.
I ran into a possible bug. But I have SSL enabled in Rocket.Chat. When calling a subscriber, the subscriber does not have a call implementation window.
Where to look?)
Rocket deployed in 2 different locations, Docker and Manual ubuntu
