### ISSUE TITLE
Shortcut for the 'Mail Messages' functionality

### ISSUE THREAD

**Issue by jinnear** [RocketChat/Rocket.Chat#2354]
The possibility to allow our users to e-mail messages is a quite appreciated feature which is mainly used (at least in my experience) to forward single messages to one's email client. In particular there are users who are utilising their mail client for organising their tasks. It would be a great QoL improvement if there was a shortcut for them sending single messages to themselves. I'd imagine that being implemented in a way like the following:

![screen shot 2016-02-26 at 10 06 57](https://cloud.githubusercontent.com/assets/10801000/13348210/6d9178fc-dc72-11e5-91d2-2ac257c1fc25.png)

I can see how this might raise concerns that this menu might get cluttered if too much functionality is added to it. This would however easily be remediated by allowing every user to configure which of the items they want to see and which ones they don't use at all. (Pinning for example is a feature I personally almost never use)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
