### ISSUE TITLE
User card doesn't work on iphone/ipad

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#23543]
When clicking a username in an active channel, user card doesn't work, nor does it open the private message, it simply does nothing. This is happening on iphone/ipad with the web version.

### Steps to reproduce:

1. view a channel
2. click a username inside the channel (not on the user list)
3. instead of the user card coming up, it simply does nothing on mobile.

### Expected behavior:

For user card to come up.

### Actual behavior:

nothing happens.

### Server Setup Information:

Version of Rocket.Chat Server: 4.0.3
Operating System: Centos 8
Deployment Method: Tarball
Number of Running Instances: 6
DB Replicaset Oplog: yes
NodeJS Version: 12.22.1
MongoDB Version:4.0.27

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
