### ISSUE TITLE
Push notifications on Apple devices show no details most of the time

### ISSUE THREAD

**Issue by josesolis2201** [RocketChat/Rocket.Chat#23572]
### Description:
We are having an issue exclusively with our iOS clients where the notification preview details (group, sender and text) sometimes appear hidden.

### Expected behavior:

Notification should show complete group, sender and text details:
![image](https://user-images.githubusercontent.com/77527585/139075469-452da477-e132-475c-a034-124ed6e94b1a.png)

### Actual behavior:

Sometimes notification preview lacks those details. This happens most of the time. Sporadically the notifications work for a couple of messages and then break again. 
In this image a notification works and 8 minutes later it stops working. Both messages were sent to the same group by the same person.
![image](https://user-images.githubusercontent.com/77527585/139073812-7e0fda88-751f-4c28-bac2-a19d4a74d8a7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.2
- Operating System: Ubuntu Linux
- Deployment Method: Docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled 4.2.14
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.14 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: official iOS app version 4.20.0.26006
- Operating System: iOS, iPadOS, WatchOS. Multiple versions

### Additional context
- The iOS devices privacy configuration is setup correctly to show notification previews.
- When a notification works as intended it does so on every devices that receives the notification. (If  the preview is available in iPhone it is also available in iPad)
- Notifications always works when generated via the test notification button in Admin -> PUSH
- Server settings in Admin -> PUSH -> Privacy allow for message details to appear in push notification.
![image](https://user-images.githubusercontent.com/77527585/139074226-6fdaaa94-108d-4031-9899-e4d65194d991.png)
- We are using the default notification gateway

**Comment by sampaiodiego** [comment]
@josesolis2201 can you please confirm if that happens to all rooms (private/public groups, DMs)? do you have E2E encryption enabled on those rooms?

**Comment by josesolis2201** [comment]
@sampaiodiego We have E2E encryption disabled globally. 
When it happens it is really difficult to determine which group is the one affected as it is a relatively busy server.

I did some testing today though and created a private group, a public group and enlisted a coworker's help to test DMs.

It always displayed the private group and DM notification details correctly and it failed every single time on the public group.

The test was not conclusive as we have thousand of groups, but the behavior seems to indicate it only happens on public channels?

**Comment by josesolis2201** [comment]
@sampaiodiego Further observation seems to indicate that it is only public groups being affected by this. I can confirm now that out of 9 different groups (3 of each type) it has only failed so far on the public groups. However it is important to mention that it is still a very small sample of the total amount of groups that we have

**Comment by sampaiodiego** [comment]
thanks for the info @josesolis2201 .. it seems very weird that it doesn't work only for public channels.

by looking the code, there are only two situations where the server sends a push with the text "You have a new message": 

https://github.com/RocketChat/Rocket.Chat/blob/c954c5ffece8111bf924bec91e6666b25a66749f/app/lib/server/functions/notifications/mobile.js#L50

* when the setting "Fetch full message content from the server on receipt" (this is a EE feature) is turned **on**;
* when the setting "Show Message in Notification" is turned **off**.

So we have just a few options here:

* Do you have an enterprise license? Either way, can you please disable the setting "Fetch full message content from the server on receipt" and try again? it may be an issue with how we check/persist setting values

**Comment by josesolis2201** [comment]
@sampaiodiego We do have an enterprise license. We changed the "Fetch full message content from the server on receipt" setting to **off** and notifications have been working ever since. 

I didn't even bother to check the very obvious documentation where it clearly says that enabling that setting:

> will not pass any message content - encrypted or not - via Google/Apple/other push gateways.

I do find it interesting that sometimes we received the message in the notification and sometimes we did not. If I understand correctly with that setting enabled we should have never received a complete notification right? Maybe it is worth looking into that but I personally lack the necessary knowledge of the codebase.

Anyway, this issue is now closed for us. Thanks for the help!

**Comment by sampaiodiego** [comment]
oh, good to know.. 

so when that setting is turned on, we indeed don't send the message content through push notification, but when the device receives the notification it requests the content from the server, before displaying it.. so apparently this part (fetching the push content) was failing for you in some specific cases, so I'll still investigate a little bit on this
