### ISSUE TITLE
GPU under VirtualBox

### ISSUE THREAD

**Issue by Sloneg** [RocketChat/Rocket.Chat#23575]
There is extremely ugly text rendering with pixelated fonts and curved string right up to toggling "Disable GPU". After doing it app window disappear while app process is still alive. 
Windows 7 64 bit inside the Virtualbox with 3D acceleration on the AMD A8 system.

Seems to be a font rendering issue. The same trouble is well known in Chrome browser too.

**Comment by TheDigitalEagle** [comment]
Considering the client software is just Chromium, that would make sense.
This wouldn't be a rocket.chat specific issue.

**Comment by debdutdeb** [comment]
Closing since this is not a rocket.chat issue.
