### ISSUE TITLE
Allow page up keyboard key to scroll up

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat#2358]
Your Rocket.Chat version: 0.19.0
Tested on the web interface and the desktop app.

Currently one needs to use the mouse to remove the focus from the message field and into the channel's stream in order to be able to use the Page Up key to scroll up.

In order to facilitate keyboard only operations, it would be great to be able to hit Page Up wherever the focus is and be able to navigate message that way. 

PS: Note that Tab to move across field also doesn't work.

**Comment by TwizzyDizzy** [comment]
Can still confirm this on 0.61.0.

**Comment by dirkmueller** [comment]
Still an issue with 3.15.0. I agree that being able to use page up/page down to scroll history even when focus is on the input bar would be very helpful for avoiding mouse usage.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Mouse key up and down are working without focus on the message composer

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
