### ISSUE TITLE
[BUG] Setup Wizard showing HTML Tags instead of just links

### ISSUE THREAD

**Issue by kulkarnigaurav38** [RocketChat/Rocket.Chat#23609]
### Description:

 The Cloud Info part in Setup Wizard in the Administration section is showing HTML anchor tags instead of showing just the links. 

### Steps to reproduce:

1.  Go to Administration, under Settings, open Setup Wizard.
2.  Click on Cloud Info within Setup Wizard.

### Expected behavior:

 The description in this section should read as follows:
I agree with the <a href='https://rocket.chat/terms'>Terms</a > & <a href='https://rocket.chat/privacy'>Privacy Policy</a>

### Actual behavior:

 
![Screenshot 2021-11-01 170610](https://user-images.githubusercontent.com/59637086/139777052-55417316-ca49-4e05-8f2b-c84291d0571f.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.0-develop
- Operating System: Linux (WSL2 on Windows) 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 -x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Chrome latest (95.0.4638.69) 
- Operating System: Windows 10 version 21H1

### Additional context
I am working on the issue, will raise a PR related to this issue :)

**Comment by dudanogueira** [comment]
PR #23615 will fix this. Also reported as issue #23614

**Comment by dougfabris** [comment]
Already fixed here: #24248
Thanks @kulkarnigaurav38 @dudanogueira
