### ISSUE TITLE
Cannot login into Rocketchat from iPhone via https

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat#23602]
### Description:

iPhone App cannot login RocketChat server via https, but http works. 

### Steps to reproduce:

1. Download Rocketchat app from Apple apple store, version is 4.21.0.26582
2. Add local Rocketchat server https://192.168.21.54 
3. Server add successfully, but when I click login and nothing happened. But when I add new RocketChat server via http://192.168.21.54, I can login the app.

### Expected behavior:

 Login into Rocketchat server from my iPhone.

### Actual behavior:

When I type username/password and click  login button, nothing happened.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13
- Operating System: Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: iPhone 13 pro 15.02
- Operating System:Mac IOS

### Additional context

I found log from my RocketChat server:
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: API ➔ debug POST: /api/v1/login
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPHandler ➔ info Init LDAP login fishman
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Connection.info Init setup
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Connection.info Connecting ldap://dc-2.realm.com:389
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Connection.debug connectionOptions {
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   url: 'ldap://dc-2.realm.com:389',
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   timeout: 30000,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   connectTimeout: 1000,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   idleTimeout: 1000,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   reconnect: false,
Oct 31 21:57:10 rocketchat-1 rocketchat[237realm80]:   log: Logger {
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     _events: [Object: null prototype] {},
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     _eventsCount: 0,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     _maxListeners: undefined,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     _level: 30,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     streams: [ [Object] ],
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     serializers: null,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     src: false,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     fields: {
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:       name: 'ldapjs',
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:       component: 'client',
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:       hostname: 'rocketchat-1',
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:       pid: 23780
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     },
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:     [Symbol(kCapture)]: false
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   }
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: }
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Connection.info LDAP connected
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Bind.info Binding UserDN CN=bind,CN=Users,DC=realm,DC=com
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.info Searching user fishman
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.debug searchOptions {
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   filter: '(&(sAMAccountName=fishman))',
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   scope: 'sub',
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   sizeLimit: 1000,
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]:   paged: { pageSize: 250, pagePause: false }
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: }
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.debug BaseDN DC=realm,DC=com
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.info Search result count 1
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Auth.info Authenticating CN=Fish Man,OU=User,OU=Accounts,DC=realm,DC=com
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.info Search result count 1
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAP ➔ Auth.info Authenticated CN=Fish Man,OU=User,OU=Accounts,DC=realm,DC=com
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPHandler ➔ info Querying user
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPHandler ➔ debug userQuery { 'services.ldap.id': '42a334334a8529e95ca428c0e9100a4d63e5a' }
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPHandler ➔ info Logging user
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPSync ➔ info Syncing user data
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPSync ➔ debug user { email: undefined, _id: 'bekH29q35454LEykkxzJcZ2a' }
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPSync ➔ debug ldapUser undefined
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPSync ➔ debug not syncing user roles
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPSync ➔ debug not syncing groups to channels
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPSync ➔ info Syncing user avatar
Oct 31 21:57:10 rocketchat-1 rocketchat[23780]: LDAPHandler ➔ info running afterLDAPLogin
Oct 31 21:57:11 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.info Idle
Oct 31 21:57:11 rocketchat-1 rocketchat[23780]: LDAP ➔ Connection.info Disconecting
Oct 31 21:57:11 rocketchat-1 rocketchat[23780]: LDAP ➔ Search.info Closed

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
