### ISSUE TITLE
Highlighting words in own message

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#2360]
Your Rocket.Chat version: v0.19.0 commit a1488beb40ee4733fa0e07c452457642c07bada3 (current on dev)

If you say a word that you are highlighting, it highlights and alerts you.

Ref Pull req: #2236

**Comment by marceloschmidt** [comment]
I think that, if I type a word that is set to be highlighted, it should be highlighted. It shouldn't fire an alert, though. @geekgonecrazy can you test this with current code in `develop`  and see if it's still happening to you? Thanks.
