### ISSUE TITLE
Cannot read property 'value' of undefined error seen with _appsUpdateMarketplaceInfo

### ISSUE THREAD

**Issue by rajeshkp** [RocketChat/Rocket.Chat#23610]
Cannot read property 'value' of undefined error seen with _appsUpdateMarketplaceInfo sometimes and we are unable to start the rocketchat docker container 4.0.3

```
Exception in callback of async function: TypeError: Cannot read property 'value' of undefined

    at _appsUpdateMarketplaceInfo (app/apps/server/cron.js:74:68)

    at runWithEnvironment (packages/meteor.js:1286:24)

    at packages/meteor.js:1299:14

    at Object.job (app/apps/server/cron.js:104:3)

    at packages/littledata_synced-cron.js:251:26

    at scheduleTimeout (packages/littledata_synced-cron.js:304:9)

    at packages/littledata_synced-cron.js:356:42

    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)

    at packages/meteor.js:550:25

    at runWithEnvironment (packages/meteor.js:1286:24)
```

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
