### ISSUE TITLE
We can remove user from from (Administrator->permission->edit role->user in role => try to remove user => error.

### ISSUE THREAD

**Issue by Montel** [RocketChat/Rocket.Chat#23616]
### Description:

Impossible to remove user from role when we try to edit it in Administrator->permission->edit role->click on "user in role" button. When we try to remove user it return "User is not in this role [error-user-not-in-role]" error but it's in list.

### Steps to reproduce:

1. Administrator config dialog
2. Select Permission config tab
3. click on a role for editing it
4. Click on "User in role" button
5. Remove an user from list with "trash" button
6. Accept to delete User (reported by MessageBox)
7. It will return an error message

### Expected behavior:

I want that it delete user from list of user.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.11

### Client Setup Information

- Desktop App and Browser Version:
- Linux

**Comment by Aman-Maheshwari** [comment]
This works fine for me. I do not get any error. 
Following the steps mentioned, I am able to delete user in the specific role.
Rocket.chat version : 4.2.0-develop

**Comment by dudanogueira** [comment]
I was not able to reproduce it under 4.1.0

After removing agent2 from the user role, the user was not shown at the list anymore, and at the user list (Admin>Users) the user2 no longer had the user role.

![image](https://user-images.githubusercontent.com/1761174/140519439-1a1a8546-4b07-4648-9c76-4fe36cead241.png)

Admin > Users

![image](https://user-images.githubusercontent.com/1761174/140519528-53568f0d-cbb7-44e6-92f1-9c13442a3429.png)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
