### ISSUE TITLE
[BUG] HTML tags not parsed inside Admin panel under setting

### ISSUE THREAD

**Issue by Aman-Maheshwari** [RocketChat/Rocket.Chat#23614]
### Description:
Many option in settings inside admin panel have html tags in them. (Markdown not parsed properly).
This also leads to some link being broken.

### Steps to reproduce:

1. Go to Administration, under Settings, 
- open Accounts>Registration.
- open CAS option 

### Expected behavior:

HTML tags should be replaced with the expected markdown

### Actual behavior:

No HTML tags are replaced with markdown

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0-develop
- Operating System: Linux

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 90.0.4430.212 
- Operating System: Ubuntu 20.04.1 LTS

**Comment by dudanogueira** [comment]
Hi Aman! Thanks for the PR!!!!

I asked review from our team.

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of:  https://github.com/RocketChat/Rocket.Chat/issues/28854

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
