### ISSUE TITLE
Hide Username Config doesn´t work

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#23611]
### Description:
Wir haben die Einstellung "Hide username" vorgenommen. Der Nutzername wird aber weiterhin in dem Reiter Nutzerinformation angzeigt. Sobald die Option "Hide username" gesetzt ist, sollte auch an dieser Stelle der Nutzername versteckt werden. 

### Steps to reproduce:

1. Config Accounts -> User Preferences -> Hide Username
2.  Channel at userinformation
3.  scroll down and the username will be displayed

### Expected behavior:

As soon as the option "Hide username" is set, the username should also be hidden at this point.

### Actual behavior:
The username is shown

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.0
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.17 

### Client Setup Information

- Desktop App or Browser Version: Version 3.5.7 and in webbrowser
- Operating System: Windows 10

**Comment by dudanogueira** [comment]
Hi!

As I understand, the option you mentions is:

Config Accounts -> **Default** User Preferences -> Hide Username

Those options will define the default configuration for new users only.

When you change this option, it will not affect already created users.

Let me know if this is the configuration you pointed at the issue.

Thanks!
