### ISSUE TITLE
[Bug] Chat order changes when user change notification preferences

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#23617]
### Description:

When user change notification preferences, right after that chat list in sidebar changing in a very strange way - here could be chats with not acting before users.

### Steps to reproduce:

1. Go to My Account - Preferences - Notifications
2. Change `Show Desktop Notifications For` from **Default** to **Nothing**
3. Check chats in Sidebar

### Expected behavior:

Sidebar chat order shouldn't change when user change notification preferences

### Actual behavior:

Screenshots and screencast presented in DM with Diego at open.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.15

### Client Setup Information

- Desktop App or Browser Version: Chrome 95
- Operating System: Windows 10

### Additional context

We talk about it with @sampaiodiego at open server and Diego thinks that it is a definitely front-end bug. so @ggazzo please take a look at this issue.

Another one thing is `rocketchat_subscription/update` increases in moment of notification change
![image](https://user-images.githubusercontent.com/4023037/140019326-2822f9e8-3315-4bd4-af07-e9dccf112540.png)
![image](https://user-images.githubusercontent.com/4023037/140019168-fd7aa1d5-fc82-41da-a927-8fa36dd0849d.png)
![image](https://user-images.githubusercontent.com/4023037/140019239-eeaec543-9812-484b-8cbf-7b953a61f4f3.png)
this 
Diego say that this is a proper behavior.

### Relevant logs:

No

**Comment by iMiKED** [comment]
I can confirm - right after changing something in Notifications, your contact list got sorted in weird way - empty private chats comes at first despite of your sorting options. You can't hide them all.
Maybe there's should be an option in sorting rules - "hide empty chats" or smth like that.

**Comment by ankar84** [comment]
> Maybe there's should be an option in sorting rules - "hide empty chats" or smth like that.

Nice idea!

**Comment by ankar84** [comment]
Still an issue on 4.2.2

**Comment by ankar84** [comment]
Still an issue on 4.6.2

**Comment by ankar84** [comment]
Still an issue on 4.8.2

**Comment by ankar84** [comment]
@tassoevan hey Tasso! 
You think it is not a bug but normal behavior?

**Comment by tassoevan** [comment]
@ankar84 for sure it's an odd behavior, but I'm puzzled on why the notifications preferences and the sidebar's room list are tied together. Let me check the code and see what I can find.

**Comment by iMiKED** [comment]
@tassoevan thanks! @ankar84 wrote to you on my behalf about strange issue I've got today:
I've got a conversation today with one of my contacts.

After alt+tabbing from Chrome back to RocketChat I've discovered that order of my private chats messed up - instead of my recent conversations, old or inactive conversation moved to top. Recent conversations moved to bottom of contact list.

Strange thing that I didn't changed anything in Settings - just alt+tabbed back from Chrome to Rocket.Chat.

Isn't it strange?

**Comment by tassoevan** [comment]
> why the notifications preferences and the sidebar's room list are tied together

Sorting by activity means sorting by `rocketchat_subscriptions._updatedAt` (thanks @sampaiodiego) and this field is also updated when notification preferences are stored in the room subscription, which means the concept of "activity" is broken... I'll try to find an alternative for it.

**Comment by ankar84** [comment]
> > why the notifications preferences and the sidebar's room list are tied together
> 
> Sorting by activity means sorting by `rocketchat_subscriptions._updatedAt` (thanks @sampaiodiego) and this field is also updated when notification preferences are stored in the room subscription, which means the concept of "activity" is broken... I'll try to find an alternative for it.

Interesting thing - mobile client doesn't have that problem! Chat list on mobile remain properly sorted while messon Web client.

**Comment by tassoevan** [comment]
@ankar84 Never mind... We are rightfully ordering it via `rocketchat_room.lm`, _but_ at some point the value is reset incorrectly to the current timestamp. Do you mind confirming if messing with the ordering at the web client reflects in the order at the mobile client?

**Comment by ankar84** [comment]
> Do you mind confirming if messing with the ordering at the web client reflects in the order at the mobile client?

No. Not confirm that.

# Steps to reproduce:
1. Go to `My Account - Preferences - Notifications`
2. Change `Show Desktop Notifications For` from `Default` to `Nothing`
3. Check chats in Sidebar on Web client - it's mess (current actual contacts moved away and some old accounts appeared on top)
4. Check chats in Sidebar on Mobile client - all good (current actual contacts remain on top as it should be)

So, for some reason that issue is not reproduced on Mobile.
