### ISSUE TITLE
How to change the domain?

### ISSUE THREAD

**Issue by waylon-gmail** [RocketChat/Rocket.Chat#23621]
https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers/docker-compose

I deployed the services using docker compose. And the service is running normally. Now, I want to change the domain, what should I do? I cannot find where the domain in.

Thank you.

```
    environment:
      - PORT=3000
      - ROOT_URL=https://domain -----> change this value
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
```

**Comment by emikolajczak** [comment]
In Admin panel "General -> Site URL"
