### ISSUE TITLE
Omnichannel Webhooks can't be saved

### ISSUE THREAD

**Issue by devilstars** [RocketChat/Rocket.Chat#23630]
### Description:

Omnichannel Webhooks can't be saved. The error notification contains only `"[undefined]"` text in it.

Log message:
```
{"level":50,"time":"2021-11-04T09:30:50.419Z","pid":11,"hostname":"6208d53b0878","name":"System","msg":"Exception while invoking method livechat:saveIntegration 'settings.updateValueById is not a function'"} 
```

### Steps to reproduce:

1. Go to Omnichannel -> Webhooks
2. Try to add any webhook
3. Get error

### Expected behavior:

Webhooks should be saved without errors.

### Actual behavior:

![2021-11-04_113349](https://user-images.githubusercontent.com/12907959/140290644-205d50bb-691c-4135-bda5-f1f197292349.png)

### Server Setup Information:

Deployment Method: docker
Version: 4.1.0
Deployment ID: oRpmw7vzRQBRJRirX
Apps Engine Version: 1.28.0
Node Version: v12.22.1
Database Migration: 242 (4 November 2021 y., 11:34)
MongoDB: 4.0.27 / mmapv1 (oplog Enabled)
Commit Details HEAD: (0da143cd1)
Branch: HEAD
PID: 11

### Client Setup Information

- Desktop App or Browser Version: Firefox 95
- Operating System: Windows 10

### Additional context

It's a community version of rocket.chat

### Relevant logs:
Request `/api/v1/method.call/livechat%3AsaveIntegration`
```
{"message":"{\"msg\":\"method\",\"id\":\"20\",\"method\":\"livechat:saveIntegration\",\"params\":[{\"Livechat_webhookUrl\":\"https://824a-94-125-125-154.eu.ngrok.io/api/offline\",\"Livechat_secret_token\":\"\",\"Livechat_webhook_on_start\":0,\"Livechat_webhook_on_close\":1,\"Livechat_webhook_on_chat_taken\":0,\"Livechat_webhook_on_chat_queued\":0,\"Livechat_webhook_on_forward\":0,\"Livechat_webhook_on_offline_msg\":0,\"Livechat_webhook_on_visitor_message\":0,\"Livechat_webhook_on_agent_message\":0}]}"}
```

Response
```
{"message":"{\"msg\":\"result\",\"id\":\"20\",\"error\":{}}","success":true}
```

**Comment by dudanogueira** [comment]
I can confirm this bug. 

It's probably at UI level as the API still works fine.

This is also happening on latest versions.

**Comment by iglooom** [comment]
Is there any quick workarounds for this bug right now? What the API method I can use instead GUI?

**Comment by iglooom** [comment]
Found at /admin/Omnichannel in 'CRM Integration' there is a same settings, but work properly.
