### ISSUE TITLE
E2E too low priority for a product that puts "data security first".

### ISSUE THREAD

**Issue by TheDigitalEagle** [RocketChat/Rocket.Chat#23646]
Not sure where to put this, so this felt like a good place since the forums are pretty dead.

Please understand I am writing this from a place of love, not criticism.

Rocket.Chat has been a go-to for us because of the major benefit the platform can be hosted on site (a major win for work environments where 3rd party hosting violates NDAs and customer security audits).
But for a platform that appears to be the only one to offer a decent solution for E2E, it is constantly back-burnered for "enterprise" features. I get it, this is as much of a company as it is open-sourced. But you guys are losing a lot of opportunities related to this lack of attention. 

There are 2 pull requests for E2E default settings fixes, fixing an issue that has existed since the at least 3.X release (definitely existed before 4.0). The release is on 4.1.1 and it is still back burnered.

Also the other topic that has been brought up by many in the past year of having a way to **enforce** E2E in Direct Messages. This is critical for preventing people within the company from having private unencrypted clear text conversations about customers. All chat info being internal is pointless as the chat info is communicated clear text. Sure, you can force everyone to use a VPN. But what a waste of a good feature! Last I've read anything about the topic, it was being "looked into for early 2022".

We've been able to easily force Direct Message encryption for our own internal build by simply changing a few lines. 

I want to be clear - I'm a big fan of Rocket.Chat and I've been rooting for this project since COVID forced WFH culture. Rocket.Chat enabled my team to be able to get through some tough times and I am sure that ahs caused you guys to get a lot of new customers. I am very much aware of the actual time it takes to implement versus "changing a few lines" as I said. But I do want make a very clear call-out to the **extremely low hanging fruit** you have for your potentially future Enterprise customers. 

I am very aware of the obvious directives internally to focus on features that drive revenue instead of feature requests by a free open-sourced product. These are that revenue driven features that affect your **enterprise** customers.

Thank you for your time and all you guys have done.

**Comment by pl4xy** [comment]
@TheDigitalEagle
Could you share the instructions with the community? I think it would be useful.
