### ISSUE TITLE
Create Instant Rocket.Chat for Websites

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2364]
(this is a very frequent request in #general, #support, and #dev -  it is time to formalize it here)

**_"Enable any website in the world to add Rocket.Chat with a dozen lines of code (similar to Google analytics) on a page"._**   

There should be no registration requirement, and zero commitment to any server-side resources.  Code should not be tied to any JS library or framework.  Just include the lines, and you've got Rocket.Chat running on your site.

Features:
- an independent anonymous instance of the server - instantly provisioned (4 seconds)
- visitors to site can engage in chats immediately with no registration, enjoying 80%+ of Rocket.Chat core capabilities
- optional ability to admin Rocket.Chat if they wish
- optional ability to export data for migration

Can we do it?

Definitely.   Ever since  [this commit](https://github.com/RocketChat/Rocket.Chat/commit/f71a649881abff2b32efd26e8128c498ea3460fb).  Anyone experimented with Sandstorm's app-demo mode will know exactly what is meant here. 

Who'd pay for all those instances?

@kentonv and his beta program would have, if we started last Sept  :smile:    But the minimal resources requirements of quiescent grains would make this possible.  90% percent of the instances will see very little long term activities - consuming only a 'grain' of allocated resource;  the other 10% we can detect and assist in win-win migrations to other more permanent and performant means of deployment.

This can drive Rocket.Chat adoption exponentially.

**Comment by paulhibbitts** [comment]
Hi Sing,

It is fantastic to see LiveChat make it into Sandstorm.io - I've setup Livechat in my Sandstorm install and copied the needed code to my Website but the chat widget does not show up - are there any settings on the Sandstorm side I need to have done?

Thanks very much,
Paul

**Comment by Sing-Li** [comment]
Hi Paul,

We still have a lot of work to do on LiveChat, and due to shifting of priorities - it will take some time.  Once that's completed, we'll take a look at supporting other platforms (such as Sandstorm.io). 

Sandstorm.io has an iron-clad security foundation, and LiveChat styled interactions _might_ take some hard-core engineering work.

Having said that, we do work closely with the Sandstorm team and are "all ears" when it comes to their requirements.  You may want to rally support from influential Sandstorm.io users to shift current priorities.

Thanks for reaching out,
Sing

**Comment by paulhibbitts** [comment]
Thanks for the update Sing. I am also looking at the possibility of getting a local server install of RocketChat going as well.

Cheers,
Paul

**Comment by juliomac** [comment]
+1 on having SandStorm support for Livechat.

Also could not make the chat widget to show up.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  We have cloud and a few other partners providing 100% effortless creation of server.  Then we now have snap, docker and sandstorm for minimal effort and quick installs
