### ISSUE TITLE
Unable to login via OAuth2

### ISSUE THREAD

**Issue by firlevapz** [RocketChat/Rocket.Chat#23654]
### Description:

Since version 4.1.0 (also current version 4.1.1) the users are unable to login. I've tried both the default nextcloud-setup as a custom nextcloud-setup. 
### Steps to reproduce:

1. Got to start-page
2. Click button login via Nextcloud
3. Error bubble "undefined" pops up after login-process

### Expected behavior:

User should be logged in

### Actual behavior:

![image](https://user-images.githubusercontent.com/12501952/140640626-587c252b-dfb0-458b-92a1-6f40eb98137c.png)

![image](https://user-images.githubusercontent.com/12501952/140640646-34204a9a-25ab-4872-849c-92ba4f06aba1.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.1
- Operating System: Linux/Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1 - x64
- MongoDB Version: 4.2.17

### Client Setup Information

- Desktop App or Browser Version: Browser, Firefox
- Operating System: Linux

### Relevant logs:

```
{"level":50,"time":"2021-11-07T10:05:16.501Z","pid":9,"hostname":"df9323809139","name":"System","msg":"Exception while invoking method login 'Failed to complete OAuth handshake with nextcloud at /index.php/apps/oauth2/api/v1/token. url must be absolute and start with http:// or https://'"} 
```

**Comment by firlevapz** [comment]
closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/23613

**Comment by sephentos** [comment]
Having the same issue with Nextcloud OAuth.

```
{"level":50,"time":"2021-11-17T03:17:59.246Z","pid":8,"hostname":"7af58635f8c5","name":"System","msg":"Exception while invoking method login 'Failed to complete OAuth handshake with nextcloud at /index.php/apps/oauth2/api/v1/token. url must be absolute and start with http:// or https://'"} 
```

The given Nextcloud, of course, is completly valid (Tested it with trailing slash and without).

@firlevapz The mentioned issue #23613 does not help me since its related to Gitlab and I am not even able to find these lines mentioned here https://github.com/RocketChat/Rocket.Chat/issues/23613#issuecomment-963065560 in `programs/server/app/app.js`

**Comment by firlevapz** [comment]
> @firlevapz The mentioned issue #23613 does not help me since its related to Gitlab and I am not even able to find these lines mentioned here [#23613 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/23613#issuecomment-963065560) in `programs/server/app/app.js`

What i did to get oauth with nextcloud to work, is editing the file `programs/server/app/app.js` - if you run in docker-compose, you have to enter the container to find this file - then edit line number 130950 and replace the empty string there for `serverURL` with the hardcoded host name of your choice. This workes for me until this is fixed...
