### ISSUE TITLE
Wordpress login persists even when you log out of Rocket.Chat server page

### ISSUE THREAD

**Issue by syedalamabbas** [RocketChat/Rocket.Chat#2365]
Your Rocket.Chat version: (make sure you are running the latest) Latest.

Hi All, 
                   I am very excited to use the Rocket.Chat integration with Wordpress for the website that I am developing. And very generously there is already an out of box integration provided by Rocket.Chat. See here https://github.com/RocketChat/Rocket.Chat/issues/747. 

```
               However there is one issue. Suppose you have two users, if user1 logs in through Rocket.Chat then those settings persists on the connected wordpress site. When you logout of Rocket chat and would want to try to login as user2, you become logged in as user1 !!!  This is because it doesn't logs out from the site even when you logout the RC page. You have to go the wordpress site to log out only then you can log in through RC as new user.  Even the functionality of "Log out from other logged in locations" doesn't work.  This kind of persistent credentials are not by design I am assuming.  
```

**Comment by philipwhiuk** [comment]
> However there is one issue. Suppose you have two users, if user1 logs in through Rocket.Chat then those settings persists on the connected wordpress site. When you logout of Rocket chat and would want to try to login as user2, you become logged in as user1 !!!  This is because it doesn't logs out from the site even when you logout the RC page. You have to go the wordpress site to log out only then you can log in through RC as new user.  Even the functionality of "Log out from other logged in locations" doesn't work.  This kind of persistent credentials are not by design I am assuming.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
