### ISSUE TITLE
Unable to search by email

### ISSUE THREAD

**Issue by thongdoan112** [RocketChat/Rocket.Chat#23663]
### Description: 
Search for users using email doesn't work

### Steps to reproduce:

1. Open Rocketchat
2. Typing email address (of a user with that email) on the search bar

### Expected behavior:

The result shows the user with that email

### Actual behavior:

Result return nothing
I'm not sure if this is working as intended since email is required to register yet you can't search by email?

**Comment by hugocostadev** [comment]
It's possible now! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
