### ISSUE TITLE
Double negative question General = Reporting

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2366]
Your Rocket.Chat version: (make sure you are running the latest)

![image](https://cloud.githubusercontent.com/assets/17207375/13379770/78421cfc-de2f-11e5-836a-ba5f0120f5a7.png)

Change the text to.

Send my statistics to Rocket.chat : Yes / No  or True /False

**Comment by jonest** [comment]
Looking to get started in this project. I'd like to tackle this. Is there a way people on this project typically get translations for the various languages for this?

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/17709035/decb5f38-63bd-11e6-8ce7-4339a52d69eb.png)
