### ISSUE TITLE
No container for security release 4.0.6

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#23674]
### Description:

You issued a security release 4.0.6 3 days ago, but there is still no container for it, just for 4.1.x!

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Container become available on Docker Hub shortly after a (security) release.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by tars21** [comment]
I'm missing the .tgz file also ( https://cdn-download.rocket.chat/build/rocket.chat-4.0.6.tgz ). Versions 4.0.5, 4.0.2 are still there.

**Comment by tars21** [comment]
Thank you, but those are different tgz's @dudanogueira. Your link is the source code, at cdn-download... you get the build packages:

`tree -L 3 -d`
```bash
.
├── programs
│   ├── server
│   │   ├── app
│   │   ├── assets
│   │   ├── node_modules
│   │   ├── npm
│   │   └── packages
│   ├── web.browser
│   │   ├── app
│   │   ├── dynamic
│   │   └── packages
│   └── web.browser.legacy
│       ├── app
│       ├── dynamic
│       └── packages
└── server
```

**Comment by dudanogueira** [comment]
@tars21  oops! sorry, forgot about this huge detail!!

Our engineering team is already aware of this issue and we can expect a solution soon.

Thanks for pointing out!

**Comment by ralfbecker** [comment]
Any news, I thought this is a security release / issue?

Ralf

**Comment by ralfbecker** [comment]
The 4.0.6 is now there: 
https://hub.docker.com/layers/rocketchat/rocket.chat/4.0.6/images/sha256-c9d4ccc9acce813d1eb3530d18306ed2ee7d1893eee4a12a4eaff2f54cf17de4?context=explore
