### ISSUE TITLE
docker-composer

### ISSUE THREAD

**Issue by adrianodss** [RocketChat/Rocket.Chat#23677]
### Steps to reproduce:

ERRO open rocket update 3.18.3 to 4.1.2

multiple errors cannot find module nodes

Uncaught (in promise) Error: Cannot find module '/node_modules/highlight.js/lib/languages/powershell.js'
 Uncaught (in promise) Error: Cannot find module '/node_modules/highlight.js/lib/languages/scss.js'
4570baead5d2268f7b1b9130e7a3050a0f9cb32a.js?meteor_js_resource=true:3 Uncaught (in promise) Error: Cannot find module '/node_modules/highlight.js/lib/languages/shell.js'

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2 
- Operating System:  Linux / DOCKER-COMPOSE
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi! Can you share your docker-compose before and after the upgrade?

**Comment by adrianodss** [comment]
> Oi! Você pode compartilhar sua composição de docker antes e depois da atualização?

version: '2'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:4.1.2
    restart: unless-stopped
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    volumes:
     - /mnt/HOMOLOG/4.1.2/uploads:/app/uploads:rw
     - /tmp:/tmp
    environment:
     - PORT=3000
     - ROOT_URL=http://${ROCKETCHAT_HOST}
     - MONGO_URL=mongodb://mongo:27017/rocketchat
     - MONGO_OPLOG_URL=mongodb://mongo:27017/local
     - MAIL_URL=smtp://smtp.email
     - TZ=America/Bahia
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rocketchat.rule=Host(`${ROCKETCHAT_HOST}`)"
      - "traefik.http.routers.rocketchat.entrypoints=web"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    #command: mongod --oplogSize 128 --replSet rs0
    #      ports:
    #       - 27017:27017
    volumes:
            #      - ./data/db:/data/db
            #      - ./data/backups:/dump
     - /mnt/HOMOLOG/4.1.2/data/db:/data/db
    environment:
     - TZ=America/Bahia
    ports:
    - 27017:27017
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  traefik:
    image: traefik:v2.1.1
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${ROCKETCHAT_PORT}"
    ports:
     - ${ROCKETCHAT_PORT}:3000
     - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - rocketchat



@dudanogueira 

Vi que é BR, obrigado pela ajuda! utilizo esse composer file e troco apenas a versão do rocket no inicio.
