### ISSUE TITLE
no snap releases for security updates

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat#23682]
There are no snap releases/updates anymore for some reason. There is not even a update for 3.18.2 that was released over a month ago.

Overall the whole snap repository looks strange and not properly maintained. At your website snap is promoted as "official" way to install, compared to the docker releases it looks like a mess.

stable is 3.18, release candidate 3.17 and beta 3.13 ... makes no sense
the whole latest tags are useless because heavily outdated 

current available versions at the snap repo
```
  3.x/stable:       3.18.1      2021-10-04 (1485) 289MB -
  3.x/candidate:    3.17.0-rc.5 2021-07-30 (1481) 288MB -
  3.x/beta:         3.13.2      2021-11-07 (1487) 219MB -
  3.x/edge:         3.18.1      2021-09-16 (1485) 289MB -
  latest/stable:    2.4.14      2020-12-23 (1453) 267MB -
  latest/candidate: 2.4.14      2021-07-30 (1453) 267MB -
  latest/beta:      2.1.1       2019-10-21 (1414) 251MB -
  latest/edge:      2.4.11      2021-05-11 (1427) 267MB -
  4.x/stable:       --
  4.x/candidate:    --
  4.x/beta:         --
  4.x/edge:         4.0.4       2021-11-07 (1486) 235MB -
  2.x/stable:       2.4.14      2020-12-23 (1453) 267MB -
  2.x/candidate:    2.4.14      2020-12-23 (1453) 267MB -
  2.x/beta:         2.4.14      2020-12-23 (1453) 267MB -
  2.x/edge:         ^
```

**Comment by dudanogueira** [comment]
Hi! I have routed this issue to our snap team. 

Thanks for pointing that out!

**Comment by dudanogueira** [comment]
Hi!

3.18.3 has been pushed to snap repos:

<pre>  3.x/stable:       3.18.3      2021-11-10 (1491) 289MB -
  3.x/candidate:    3.17.0-rc.5 2021-07-30 (1481) 288MB -
  3.x/beta:         3.13.2      2021-11-07 (1487) 219MB -
  3.x/edge:         3.18.3      2021-11-10 (1491) 289MB -
  latest/stable:    2.4.14      2020-12-23 (1453) 267MB -
  latest/candidate: 2.4.14      2021-07-30 (1453) 267MB -
  latest/beta:      2.1.1       2019-10-21 (1414) 251MB -
  latest/edge:      2.4.11      2021-05-11 (1427) 267MB -
  4.x/stable:       –                                   
  4.x/candidate:    –                                   
  4.x/beta:         –                                   
  4.x/edge:         4.0.5       2021-11-10 (1492) 284MB -
  2.x/stable:       2.4.14      2020-12-23 (1453) 267MB -
  2.x/candidate:    2.4.14      2020-12-23 (1453) 267MB -
  2.x/beta:         2.4.14      2020-12-23 (1453) 267MB -
  2.x/edge:         ↑                               </pre>

**Comment by CvH** [comment]
@dudanogueira again the security update is not at the snap repo (also not at dockerhub)!

Its now 18 days and still no update, so likely the problem is not fixed or there was no proper solution at all just some manual workaround.

Due the fact that snaps is your promoted way to go for the installation I would expect that snap repo is maintained, especially for security updates.
