### ISSUE TITLE
Notification Duration not working for more than 6 seconds

### ISSUE THREAD

**Issue by supervladvik** [RocketChat/Rocket.Chat#23684]
### Description:

Notification Duration not working for more than 6 seconds

My Account -> Presence -> NOTIFICATIONS -> Notification Duration
Allows you to set any time, but actually works from 1 to 6 seconds. If set more than 6 seconds, it is still 6 seconds.

### Server Setup Information:

  Version of Rocket.Chat Server: 
- Operating System: Linux debianRC 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
- Deployment Method: Hyper-V
- Number of Running Instances:  1
- NodeJS Version: не нашел
- MongoDB Version:4.0

### Client Setup Information

- Desktop App or Browser Version: Desktop
- Operating System: Windows7
- Version: 3.5.6

**Comment by dudanogueira** [comment]
Please, can you feel this info:

**Version of Rocket.Chat Server**

**Comment by supervladvik** [comment]
> Please, can you feel this info:
> 
> **Version of Rocket.Chat Server**

v12.16.1
