### ISSUE TITLE
Create a separate field to describe channels with multiple comma-separated tags

### ISSUE THREAD

**Issue by rchikballapur** [RocketChat/Rocket.Chat#2368]
When there are hundreds of channels, to direct users to the right channel, it might be useful to have tags attached to the channel describing its purpose and contents. These tags could be added by users or by an algorithm.

The Topics field is more for a phrase/sentence description and it doesn't serve the purpose today.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
