### ISSUE TITLE
Bug - Automatic refresh multiple times when connecting to rocket.chat

### ISSUE THREAD

**Issue by shahar3012** [RocketChat/Rocket.Chat#237]
Hi,
I've noticed that in the last commit, there is a bug that cuases a refresh multiple times automatically when connecting to rocket.chat. 
After 2-4 times that the page was refreshed, it stops.

**Comment by engelgabriel** [comment]
@shahar3012 Reopen this issue and let me know if that still happens, or it was just a build eventual failure.

**Comment by shahar3012** [comment]
Now everything works well.
I think it was a build failure, that took some days to fix it.
