### ISSUE TITLE
[BUG] No hover effect for items in kebab menu of individual messages 

### ISSUE THREAD

**Issue by kulkarnigaurav38** [RocketChat/Rocket.Chat#23708]
### Description:

 On every message, in the kebab menu, the items within it aren't highlighted similar to the kebab menu in the room header.

### Steps to reproduce:

1.  Go to any room, hover over any message.
2.  Click on the kebab menu (3 vertical dotted icon) and hover over the items.
3. Hovered over items are not highlighted.

### Expected behavior:

 On hover, the items should be highlighted similar to the room header kebab menu.

### Actual behavior:

 
https://user-images.githubusercontent.com/59637086/141655302-16c5dddb-7228-4de4-881c-111f53b218f8.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0-develop
- Operating System: Linux (WSL2 on Windows)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 -x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Chrome latest (95.0.4638.69)
- Operating System: Windows 10 version 21H1

**Comment by tib-source** [comment]
could you assign this to me, I would like to have a go at fixing it
