### ISSUE TITLE
Integrating with an existing Nginx/Mysql/Angular application

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#2370]
Current Scenario:
There is an EMR application where users login from an angularjs frontend and are authenticated with bcrypt password hashes stored in mysql users table.

Goal:
1. Users have to remember a single user name and password for both EMR and Rocket chat.
2. Users are presented with a login form only by the EMR and not by rocket chat. (To reduce phishing chances)
3. Only users existing in the EMR can use rocket chat.
4. When users login to EMR application they are automatically logged into Rocket chat.
5. When users log out of EMR application they are also logged out of rocket chat.
6. Inside the EMR application I can show the presence (online / office) status of the users.
7. Users can chat from inside the EMR application.

Ruled out LDAP because of Goal 2

My question is:
1. Using oauth can 4,5 be done ?

Any suggestions ? 

I can write code and contribute patches to rocket chat to achieve the above scenario.

**Comment by engelgabriel** [comment]
What you are looking for is SSO, it should be possible. You may have to do a integration between servers to invalidate  the current token to achieve 5.

**Comment by SRSaddler** [comment]
@vikaskedia were you able to get this project going? i'm currently looking to do something similar

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I am closing this this issue as there are far too many things involved here. It might by worth for you, to open issues for each of your aspects, yet I think most parts won't be implemented.

I think at least number 5 is highly unlikely).

Cheers
Thomas
