### ISSUE TITLE
Option to be prompted to join a channel instead of auto joining

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#2372]
Currently when you are added to a channel you are simply added.  There should be a setting the user could set to be invited instead of auto added.

At this point it would pop up and say that you've been invited and give them the option to accept or decline

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add "Feature: Request"

**Comment by marceloschmidt** [comment]
The complexity of doing this is not worth the time. We have this one planned though: https://github.com/RocketChat/Rocket.Chat/issues/4286

**Comment by engelgabriel** [comment]
this is a duplicate of #2194
