### ISSUE TITLE
Download Files in Chat not working on Desktop Apps due to wrong server url

### ISSUE THREAD

**Issue by idominiki** [RocketChat/Rocket.Chat#23720]
### Description:

Downloading files which received through a chat can't be downloaded via Desktop Apps due to wrong server url.

### Steps to reproduce:

1. Received file
2. Click the preview of the file (which is not displayed; but it shows a Retry picture)
3. Download the file
4. Can't download the file

### Expected behavior:

The sent file must be previewed in the chat and can be downloaded

### Actual behavior:

See this screenshot for a received file
<img width="290" alt="image" src="https://user-images.githubusercontent.com/62521486/141786616-46da9ee4-de66-401f-a93e-ea1b84202383.png">
![Bildschirmfoto 2021-11-15 um 14 06 20](https://user-images.githubusercontent.com/62521486/141787026-158ea377-8200-46b9-8d2a-2e555426b671.png)

In the server url there is the last character missing. I can't find the field in the admin panel, where I can edit this url.
It only doesn't work on desktop apps, in moblile apps it works fine.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.1
- Operating System: UCS
- Deployment Method: UCS AppCenter
- Number of Running Instances:  1
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.19 / mmapv1 (oplog activated)

### Client Setup Information

- Desktop App or Browser Version: 3.0.3
- Operating System: macOS 12.0.1 (21A559)

**Comment by debdutdeb** [comment]
Hi

This seems to be a subdirectory issue with 3.15.x. Could you please upgrade to the latest? 3.18.2 is now available on UCS.
