### ISSUE TITLE
Cannot load chat history

### ISSUE THREAD

**Issue by damianjakubiuk** [RocketChat/Rocket.Chat#23748]
History is not loading

![image](https://user-images.githubusercontent.com/20751781/142393602-4befbf09-32f7-4921-ac6c-9c7bf67d57a2.png)

History not loading
![image](https://user-images.githubusercontent.com/20751781/142393689-97bee497-46ac-453b-8c29-ffca344cde1f.png)

Request url:
https://greenparking.rocket.chat/api/v1/channels.messages/?roomId=yiuSxJ29BNNfSLhLR&count=50&offset=0&sort={%22ts%22:%201}&query={%22$or%22:%20[%20{%22t%22:%20{%22$exists%22:%20false}%20},%20{%22t%22:%20%22livechat-close%22}%20]%20}

Response:
error: "unauthorized"
success: false

Im trying to do this with Admin account. Please help
Cloud Version 
Version
3.18.1
Deployment ID
76sbi2aAjprXfzrvn
Apps Engine Version
1.27.1
Node Version
v12.22.1
Database Migration
232 (6 października 2021 21:07)
MongoDB
4.4.6 / wiredTiger (oplog Enabled)

**Comment by dudanogueira** [comment]
Hi! Have you seen this Issue?
https://github.com/RocketChat/Rocket.Chat/issues/21347

Basically:
the user role that are trying to use this feature **cannot have the permission view-joined-room**
and also, it **must has the permission view-c-room**

If that's the case, you should change the permissions accordingly. I had this problem and have seen it other time, but cannot understand how the permissions got messed, and was not able to reproduce that.

Also, please, consider updating to the latest version.

**Comment by damianjakubiuk** [comment]
it works! thank you! ❤️
