### ISSUE TITLE
[BUG] Multiple users cannot be added to a specific role in one-go.

### ISSUE THREAD

**Issue by Aman-Maheshwari** [RocketChat/Rocket.Chat#23740]
### Description:
cannot add multiple user to a particular role from admin > permissions 

### Steps to reproduce:

1. Go to Admin Panel
2. Select Permission
3. click on edit icon on a specific role (user)
4. click user in role
5. add user to a specific role

### Expected behavior:

Multiple user can be added to a specific role in one go.

### Actual behavior:
Need to add user one by one

### Server Setup Information:

- Version of Rocket.Chat Server:  4.2.0-develop
- NodeJS Version:  12.22.1
- MongoDB Version: 4.4.4 / wiredTiger 

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Linux

**Comment by dudanogueira** [comment]
Hi! Thanks for the issue AND the PR. I have requested our devs to take a look at it.

**Comment by Aman-Maheshwari** [comment]
@dudanogueira Thank you :smile:
