### ISSUE TITLE
MongoDB Deprecated when used docker-compose

### ISSUE THREAD

**Issue by godcong** [RocketChat/Rocket.Chat#23752]
### Description:

![image](https://user-images.githubusercontent.com/2727298/142584021-3e37ec48-25f6-459d-afb7-7d43c7643c6d.png)

### Steps to reproduce:
i used docker-compose to deploy the rockect chat server.
when i used mongodb 5.0,deploy always failed with `--smallfiles` env
so, i used mongodb 4.0.
but client telled me MongoDB Deprecated.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: docker with dsm6
- Deployment Method: used https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml to deploy the server, only changed volumes and port.
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: unkown
- MongoDB Version: 4.0.27

### Client Setup Information

- Desktop App or Browser Version: 3.6.0
- Operating System: windows 11

### Additional context
i can't download rocketchat image from registry.rocket.chat/rocketchat/rocket.chat:latest.
but from hub.docker.com was ok, so i changed image path registry.rocket.chat/rocketchat/rocket.chat:latest. to rocketchat/rocket.chat:latest

**Comment by fdellwing** [comment]
The `docker-compose.yml` in this repo is kind of broken..

Please use either mongodb 4.2 or 5.x without `--smallfiles` (mmap only) and with wiredTiger.

**Comment by dudanogueira** [comment]
Hi! 
We area aware and have been working on revamping a lot of the deployment methods we have.

Soon we'll update this method too! Thanks for pointing it out!

**Comment by godcong** [comment]
Can i only change the compose file mongodb to 5.x and remove `--smallfiles`.
then restart the rocket chat use `docker-compse up -d` ?

**Comment by bseclier** [comment]
I don't think so, we had to :
- migrate our mmap mongo 4.0 to wiredtiger mongo 4.0 (https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers/mongodb-mmap-to-wiredtiger-migration), 
- then migrate to wt mongo 4.2, 
- then migrate to wt mongo 4.4 (modifying featureCompatibilityVersion : https://docs.mongodb.com/manual/release-notes/4.4-upgrade-replica-set)

**Comment by HugooB** [comment]
Ultimately, we followed this guide to get things working and up to date: https://linuxhandbook.com/mongodb-upgrade-rocket-chat/

**Comment by godcong** [comment]
success  to upgrade to mongo 5.0.
1. stop the docker container
```
docker-compose stop
```

2. get the new script from https://github.com/RocketChat/docker-mmap-to-wiredtiger-migration
3. change the script port 3000 -> 13000, because 3000 is used by other container
4. build compose once
```
docker-compose up --build -d
```
Now,current mongo version is 4.0.

upgrade
1. look the current mongo FeatureCompatibilityVersion version
```
docker-compose exec mongo bash -c 'mongo --eval "db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )"'
```
If FeatureCompatibilityVersion is not 4.0,set to 4.0
```
docker-compose exec mongo bash -c 'mongo --eval "db.adminCommand( { setFeatureCompatibilityVersion: \"4.0\" } )"'
```
then stop compose
```
docker-compose stop
```
change the `docker-compose.yml`, set mongo version to 4.2,run
```
docker-compose up -d
```
waiting finished. set FeatureCompatibilityVersion to 4.2
```
docker-compose exec mongo bash -c 'mongo --eval "db.adminCommand( { setFeatureCompatibilityVersion: \"4.0\" } )"'
```
then>stop>change(4.4)>up>setFeatureCompatibilityVersion>stop>change(5.0)>up>setFeatureCompatibilityVersion


I eventually upgraded to 5.0
But this is too complicated, I hope there is a more convenient way to deploy directly to the latest version in the future

**Comment by krumelmonster** [comment]
This needs a big warning in the docs. I wanted to migrate from an up-to-date snap using wiredtiger to using docker and it took me far too long to realize that the RocketChat docs and images are outdated. I guess I'll better stick to the snap for now.
