### ISSUE TITLE
Member List showing max 25 users, can't scroll to load more

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat#23751]
### Description:

under certain circumstances, the member list will show 25 members and disallow scrolling to be able to load the rest of the users.

### Steps to reproduce:

To reproduce, make browser height tall enough so that at 25 or more member names can fit in the right hand menu. Go to a channel with more than 25 members. On initial load, it works fine and the scrollbar appears as expected. Toggle the online/all filter to online. The list updates to show online users only. Now, click back to "All" and 25 member names appear, but no scroll bar.

### Expected behavior:

it should work as it does when you initially load the page, allowing you to scroll to load the remainder of the users.

### Actual behavior:

it only shows 25, with no option to scroll.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.4
- Operating System: RedHat
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: whatever is recommended for 3.15.4
- MongoDB Version: whatever is recommended for 3.15.4

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: OSX 11.6

### Additional context

works fine on initial load of member list, but exhibits the issue when flipping the filter as stated above.

**Comment by cprice-kgi** [comment]
I commented on this closed issue that addresses something similar, but since it's closed I decided to open a new issue for discussion:
https://github.com/RocketChat/Rocket.Chat/issues/21505

**Comment by ankar84** [comment]
Just update your RC server at least to 3.18.3
I'm on 3.18.2 now and Member List show more then 25 users.

**Comment by Gummikavalier** [comment]
Our RC 5.3.3 seems to limit the max shown amount of members to somewhere between 40 - 80 for regular users and for admins ~300.

Disabling rate limiters did not have effect. I suspect there is a hardcoded limiter to save excess load via resolving hundreds of usernames to real names.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
