### ISSUE TITLE
Automatic Update does not work

### ISSUE THREAD

**Issue by julianbelina** [RocketChat/Rocket.Chat#23779]
Rocket Chat prompts that a new Version is available. When i click on Update nothing happends. I am using Version 3.5.7 on Windows 10.

**Comment by fdellwing** [comment]
Wrong repo and duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Comment by ankar84** [comment]
Closing this issue in favor of RocketChat/Rocket.Chat.Electron#1670
You can leave a comment there.
