### ISSUE TITLE
Make it possible to visually identify user role

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2378]
Your Rocket.Chat version:0.19

Rocket.Chat needs to get someway to visually identify/rank users. 
As it is now you have no clue if you talk to a core member / moderator / power user / regular user when chatting. 
Example : IRC had @ sign in front of username 

Not sure if this has been discussed..

**Comment by k0nsl** [comment]
:+1:

**Comment by rchikballapur** [comment]
+1

**Comment by mckuchta** [comment]
+1

**Comment by corecache** [comment]
Suggestion for global roles: Add attributes which define the visibility to a global user role
Suggestion for channels: Add attributes to users for a channel which define the channel visibility

**Comment by bott0r** [comment]
Another alternative is to just have different colors in the Userlist. i.e. Admin red, voice blue, normal black

**Comment by lunitic** [comment]
@bott0r i have it rather in the message "flow" . Don't think is good from a user experience to need to open up a user list and have to search for the persons name to see what kind of user it is.

**Comment by lunitic** [comment]
Also colors are already used in username list.  Color depends on status.

**Comment by bott0r** [comment]
I am all for a message display customization panel.

**Comment by vmoutoussamy** [comment]
Hi, 

Excuse me but I'm using Rocket Chat client 2.15.3 on macOS and I can not visually identify user role, so what am I missing here? 
I don't seems to have a global setting that might hide something, so I'm puzzled.
