### ISSUE TITLE
Channel Topic always in lower case

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2379]
Your Rocket.Chat version: 0.19

If you set a topic with for example a google docs link "https://docs.google.com/document/d/4H9dg1loCiTa27WFFa-sbN4JGLZtFqBm7m3ubJuI"
it will get converted to all lowercase which will create a faulty link.

This is related to  issue #2172

**Comment by engelgabriel** [comment]
They are not converted to lowercase, at least not anymore. 

Are you sure this is still an issue?

![image](https://cloud.githubusercontent.com/assets/1000217/13678083/ad6c2856-e6cb-11e5-838f-cdbdd837926b.png)

![image](https://cloud.githubusercontent.com/assets/1000217/13678095/b7d8ea36-e6cb-11e5-9b5b-b4ac37bf2900.png)

**Comment by engelgabriel** [comment]
Please reopen if this is still an issue.

**Comment by lunitic** [comment]
Works now in later versions :+1:
