### ISSUE TITLE
User & Channel mentions don't work properly

### ISSUE THREAD

**Issue by grahhnt** [RocketChat/Rocket.Chat#23806]
### Description:

User & Channel mentions aren't clickable

### Steps to reproduce:

1. Create a message with a mention to a channel or user using @username or #channel
2. Try and click on the mention

### Expected behavior:

Able to click on the mention to open the channel or open the user profile popup

### Actual behavior:

Channels don't render as clickable
![image](https://user-images.githubusercontent.com/46821216/143674732-88f3d629-4765-4ab9-91ad-5155c26b4511.png)
![image](https://user-images.githubusercontent.com/46821216/143674739-31198c21-3d0c-4487-81b6-a232de04b9c6.png)

User mentions aren't clickable, but look clickable
![image](https://user-images.githubusercontent.com/46821216/143674755-9bddfbe4-db8a-4268-aadd-1bdb28046402.png)

### Server Setup Information:

- Version of Rocket.Chat Server: Latest commit (as of [6d4784e](https://github.com/RocketChat/Rocket.Chat/commit/6d4784efe5843597baa085861d11f9a831a89ad7))
- Operating System: CentOS 7
- Deployment Method:  git
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Shipped with Meteor
- Operating System: Windows 10

### Relevant logs:

No errors or general logs for this issue

**Comment by aswinidev** [comment]
Is this still an issue because it is working fine when i tried it
@dudanogueira Please check

https://user-images.githubusercontent.com/76481696/144604776-e833314f-4be5-4e21-978c-e1e30ba12d42.mp4

**Comment by grahhnt** [comment]
![image](https://user-images.githubusercontent.com/46821216/146469151-f7c0b091-dc51-477e-bab3-8920773d51e2.png)
Turning on "Enable Message Parser" will cause all mentions to not be parsed

Sorry for the late response @aswinidev
