### ISSUE TITLE
Slack import fails

### ISSUE THREAD

**Issue by geverl** [RocketChat/Rocket.Chat#23808]
Importing a Slack export using Administration -> Import -> Import New File type Slack fails.
Importing the same file on RC 3.18.3 works.

Server running on Ubuntu 20.04.3 LTS.
Deployed using snap install rocketchat-server --channel=4.x/stable

Server log:
I20211127-16:34:29.655(0) +-----------------------------------------+ I20211127-16:34:29.656(0) |              SERVER RUNNING             | I20211127-16:34:29.656(0) +-----------------------------------------+ I20211127-16:34:29.656(0) |                                         | I20211127-16:34:29.656(0) |  Rocket.Chat Version: 4.0.5             | I20211127-16:34:29.657(0) |       NodeJS Version: 12.22.1 - x64     | I20211127-16:34:29.657(0) |      MongoDB Version: 3.6.14            | I20211127-16:34:29.657(0) |       MongoDB Engine: wiredTiger        | I20211127-16:34:29.657(0) |             Platform: linux             | I20211127-16:34:29.658(0) |         Process Port: 3000              | I20211127-16:34:29.658(0) |             Site URL: http://localhost  | I20211127-16:34:29.658(0) |     ReplicaSet OpLog: Enabled           | I20211127-16:34:29.658(0) |          Commit Hash: 803e9cfda6        | I20211127-16:34:29.658(0) |        Commit Branch: HEAD              | I20211127-16:34:29.659(0) |                                         | I20211127-16:34:29.659(0) +-----------------------------------------+ I20211127-16:34:29.659(0) +----------------------------------------------------------------------+ I20211127-16:34:29.660(0) |                              DEPRECATION                             | I20211127-16:34:29.660(0) +----------------------------------------------------------------------+ I20211127-16:34:29.660(0) |                                                                      | I20211127-16:34:29.660(0) |  YOUR CURRENT MONGODB VERSION (3.6.14) IS DEPRECATED.                | I20211127-16:34:29.660(0) |  IT WILL NOT BE SUPPORTED ON ROCKET.CHAT VERSION 5.0.0 AND GREATER,  | I20211127-16:34:29.661(0) |  PLEASE UPGRADE MONGODB TO VERSION 4.2 OR GREATER                    | I20211127-16:34:29.662(0) |                                                                      | I20211127-16:34:29.662(0) +----------------------------------------------------------------------+ {"level":50,"time":"2021-11-27T16:34:56.030Z","pid":9324,"hostname":"fairrc","name":"System","msg":"Exception while invoking method loadMissedMessages 'Invalid room [error-invalid-room]'"} {"level":50,"time":"2021-11-27T16:34:56.051Z","pid":9324,"hostname":"fairrc","name":"System","msg":"Exception while invoking method loadMissedMessages 'Invalid user [error-invalid-user]'"} I20211127-16:35:27.781(0) Unloaded the Apps Framework. {"level":50,"time":"2021-11-27T16:36:26.922Z","pid":9324,"hostname":"fairrc","name":"Slack Importer","err":{"type":"TypeError","message":"Cannot read property 'map' of undefined","stack":"TypeError: Cannot read property 'map' of undefined<br>    at SlackImporter._replaceSlackUserIds (app/importer-slack/server/importer.js:549:18)<br>    at SlackImporter.prepareChannelsFile (app/importer-slack/server/importer.js:43:17)<br>    at app/importer-slack/server/importer.js:209:28<br>    at iterateEntries (/snap/rocketchat-server/1492/programs/server/npm/node_modules/adm-zip/zipFile.js:42:4)<br>    at Object.forEach (/snap/rocketchat-server/1492/programs/server/npm/node_modules/adm-zip/zipFile.js:150:5)<br>    at Object.forEach (/snap/rocketchat-server/1492/programs/server/npm/node_modules/adm-zip/adm-zip.js:425:16)<br>    at SlackImporter.prepareUsingLocalFile (app/importer-slack/server/importer.js:206:8)<br>    at MethodInvocation.getImportFileData (app/importer/server/methods/getImportFileData.js:66:37)<br>    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:66:34)<br>    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)<br>    at packages/ddp-server/livedata_server.js:1689:15<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)<br>    at packages/ddp-server/livedata_server.js:1687:36<br>    at new Promise (<anonymous>)<br>    at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)<br>    at Server.apply (packages/ddp-server/livedata_server.js:1625:26)<br>    at Server.call (packages/ddp-server/livedata_server.js:1607:17)<br>    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/import.js:46:20)<br>    at packages/dispatch_run-as-user.js:211:14<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)<br>    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)<br>    at Object.get (app/api/server/v1/import.js:45:10)"},"msg":"Cannot read property 'map' of undefined"} {"level":50,"time":"2021-11-27T16:36:47.862Z","pid":9324,"hostname":"fairrc","name":"Slack Importer","err":{"type":"Error","message":"Meteor.userId can only be invoked in method calls or publications.","stack":"Error: Meteor.userId can only be invoked in method calls or publications.<br>    at AccountsServer.userId (packages/accounts-base/accounts_server.js:117:13)<br>    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:343:32)<br>    at 0 (app/lib/server/functions/setRealName.js:44:23)<br>    at packages/rate-limit/rate-limit.js:49:19<br>    at Array.every (<anonymous>)<br>    at Rule.match (packages/rate-limit/rate-limit.js:44:8)<br>    at packages/rate-limit/rate-limit.js:249:58<br>    at Array.filter (<anonymous>)<br>    at RateLimiter._findAllMatchingRules (packages/rate-limit/rate-limit.js:249:38)<br>    at RateLimiter.increment (packages/rate-limit/rate-limit.js:228:31)<br>    at app/lib/server/lib/RateLimiter.js:18:16<br>    at saveUserIdentity (app/lib/server/functions/saveUserIdentity.js:39:8)<br>    at ImportDataConverter.updateUser (app/importer/server/classes/ImportDataConverter.ts:245:4)<br>    at ImportDataConverter.insertUser (app/importer/server/classes/ImportDataConverter.ts:266:8)<br>    at app/importer/server/classes/ImportDataConverter.ts:324:26<br>    at Array.forEach (<anonymous>)<br>    at ImportDataConverter.convertUsers (app/importer/server/classes/ImportDataConverter.ts:293:9)<br>    at app/importer/server/classes/ImporterBase.js:198:20<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)<br>    at packages/meteor.js:550:25<br>    at runWithEnvironment (packages/meteor.js:1286:24)"},"msg":"Meteor.userId can only be invoked in method calls or publications."} {"level":50,"time":"2021-11-27T16:36:47.924Z","pid":9324,"hostname":"fairrc","name":"Slack Importer","err":{"type":"Error","message":"Meteor.userId can only be invoked in method calls or publications.","stack":"Error: Meteor.userId can only be invoked in method calls or publications.<br>    at AccountsServer.userId (packages/accounts-base/accounts_server.js:117:13)<br>    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:343:32)<br>    at 0 (app/lib/server/functions/setRealName.js:44:23)<br>    at packages/rate-limit/rate-limit.js:49:19<br>    at Array.every (<anonymous>)<br>    at Rule.match (packages/rate-limit/rate-limit.js:44:8)<br>    at packages/rate-limit/rate-limit.js:249:58<br>    at Array.filter (<anonymous>)<br>    at RateLimiter._findAllMatchingRules (packages/rate-limit/rate-limit.js:249:38)<br>    at RateLimiter.increment (packages/rate-limit/rate-limit.js:228:31)<br>    at app/lib/server/lib/RateLimiter.js:18:16<br>    at saveUserIdentity (app/lib/server/functions/saveUserIdentity.js:39:8)<br>    at ImportDataConverter.updateUser (app/importer/server/classes/ImportDataConverter.ts:245:4)<br>    at ImportDataConverter.insertUser (app/importer/server/classes/ImportDataConverter.ts:266:8)<br>    at app/importer/server/classes/ImportDataConverter.ts:324:26<br>    at Array.forEach (<anonymous>)<br>    at ImportDataConverter.convertUsers (app/importer/server/classes/ImportDataConverter.ts:293:9)<br>    at app/importer/server/classes/ImporterBase.js:198:20<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)<br>    at packages/meteor.js:550:25<br>    at runWithEnvironment (packages/meteor.js:1286:24)"},"msg":"Meteor.userId can only be invoked in method calls or publications."} {"level":50,"time":"2021-11-27T16:36:47.926Z","pid":9324,"hostname":"fairrc","name":"Slack Importer","err":{"type":"Error","message":"object [\"\"] is not a valid ObjectId","stack":"Error: object [\"\"] is not a valid ObjectId<br>    at serializeObjectId (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:287:11)<br>    at serializeInto (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:941:17)<br>    at serializeObject (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:347:18)<br>    at serializeInto (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:947:17)<br>    at serializeObject (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:347:18)<br>    at serializeInto (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:729:17)<br>    at serializeObject (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:347:18)<br>    at serializeInto (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:947:17)<br>    at BSON.serialize (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/bson.js:64:28)<br>    at Msg.serializeBson (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/msg.js:127:22)<br>    at Msg.makeDocumentSegment (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/msg.js:119:33)<br>    at Msg.toBin (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/msg.js:105:25)<br>    at MessageStream.writeCommand (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:55:28)<br>    at Connection.write (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:368:26)<br>    at _command (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/command.js:120:10)<br>    at command (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)<br>    at writeCommand (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/write_command.js:56:3)<br>    at Object.update (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/index.js:9:5)<br>    at Connection.update (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:191:8)<br>    at /snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/server.js:483:13<br>    at Object.callback (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:345:7)<br>    at processWaitQueue (/snap/rocketchat-server/1492/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:468:23)"},"msg":"object [\"\"] is not a valid ObjectId"} 

Browser console:
Import_Operation_Failed /client/views/admin/import/useErrorHandler.js:1:364
    l /client/views/admin/import/useErrorHandler.js:1
    t http://localhost:3000/aa1d4ab72b86a914f2f370581f059e8299cabbb6.js?meteor_js_resource=true:546
    a /client/views/admin/import/PrepareImportPage.js:1
Uncaught (in promise) undefined

**Comment by dudanogueira** [comment]
Hi! 

Can you provide a sample of this import file (removing personal information, and if possible, a reduced one) where we can reproduce this error?

Thanks!

**Comment by sstidl** [comment]
Hi!

```
+---------------------------------------------------+
|                   SERVER RUNNING                  |
+---------------------------------------------------+
|                                                   |
|  Rocket.Chat Version: 4.2.2                       |
|       NodeJS Version: 12.22.1 - x64               |
|      MongoDB Version: 4.2.17                      |
|       MongoDB Engine: wiredTiger                  |
|             Platform: linux                       |
|         Process Port: 3000                        |
|             Site URL: https://om-rocket.d.ffg.at  |
|     ReplicaSet OpLog: Enabled                     |
|          Commit Hash: ab3baf2f31                  |
|        Commit Branch: HEAD                        |
|                                                   |
+---------------------------------------------------+
```

I tried the attached file on a clean instance and got
```
rocketchat_1          | {"level":50,"time":"2021-12-17T23:09:30.791Z","pid":10,"hostname":"8bb97a2d25b3","name":"Slack Importer","err":{"type":"Error","message":"Meteor.userId can only be invoked in method calls or publications.","stack":"Error: Meteor.userId can only be invoked in method calls or publications.\n    at AccountsServer.userId (packages/accounts-base/accounts_server.js:117:13)\n    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:343:32)\n    at 0 (app/lib/server/functions/setRealName.js:44:23)\n    at packages/rate-limit/rate-limit.js:49:19\n    at Array.every (<anonymous>)\n    at Rule.match (packages/rate-limit/rate-limit.js:44:8)\n    at packages/rate-limit/rate-limit.js:249:58\n    at Array.filter (<anonymous>)\n    at RateLimiter._findAllMatchingRules (packages/rate-limit/rate-limit.js:249:38)\n    at RateLimiter.increment (packages/rate-limit/rate-limit.js:228:31)\n    at app/lib/server/lib/RateLimiter.js:18:16\n    at saveUserIdentity (app/lib/server/functions/saveUserIdentity.js:39:8)\n    at ImportDataConverter.updateUser (app/importer/server/classes/ImportDataConverter.ts:258:4)\n    at ImportDataConverter.insertUser (app/importer/server/classes/ImportDataConverter.ts:279:8)\n    at app/importer/server/classes/ImportDataConverter.ts:337:26\n    at Array.forEach (<anonymous>)\n    at ImportDataConverter.convertUsers (app/importer/server/classes/ImportDataConverter.ts:306:9)\n    at app/importer/server/classes/ImporterBase.js:198:20\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)\n    at packages/meteor.js:550:25\n    at runWithEnvironment (packages/meteor.js:1286:24)"},"msg":"Meteor.userId can only be invoked in method calls or publications."}
rocketchat_1          | {"level":50,"time":"2021-12-17T23:09:30.810Z","pid":10,"hostname":"8bb97a2d25b3","name":"Slack Importer","err":{"type":"Error","message":"Meteor.userId can only be invoked in method calls or publications.","stack":"Error: Meteor.userId can only be invoked in method calls or publications.\n    at AccountsServer.userId (packages/accounts-base/accounts_server.js:117:13)\n    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:343:32)\n    at 0 (app/lib/server/functions/setRealName.js:44:23)\n    at packages/rate-limit/rate-limit.js:49:19\n    at Array.every (<anonymous>)\n    at Rule.match (packages/rate-limit/rate-limit.js:44:8)\n    at packages/rate-limit/rate-limit.js:249:58\n    at Array.filter (<anonymous>)\n    at RateLimiter._findAllMatchingRules (packages/rate-limit/rate-limit.js:249:38)\n    at RateLimiter.increment (packages/rate-limit/rate-limit.js:228:31)\n    at app/lib/server/lib/RateLimiter.js:18:16\n    at saveUserIdentity (app/lib/server/functions/saveUserIdentity.js:39:8)\n    at ImportDataConverter.updateUser (app/importer/server/classes/ImportDataConverter.ts:258:4)\n    at ImportDataConverter.insertUser (app/importer/server/classes/ImportDataConverter.ts:279:8)\n    at app/importer/server/classes/ImportDataConverter.ts:337:26\n    at Array.forEach (<anonymous>)\n    at ImportDataConverter.convertUsers (app/importer/server/classes/ImportDataConverter.ts:306:9)\n    at app/importer/server/classes/ImporterBase.js:198:20\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)\n    at packages/meteor.js:550:25\n    at runWithEnvironment (packages/meteor.js:1286:24)"},"msg":"Meteor.userId can only be invoked in method calls or publications."}
rocketchat_1          | {"level":50,"time":"2021-12-17T23:09:30.814Z","pid":10,"hostname":"8bb97a2d25b3","name":"Slack Importer","err":{"type":"Error","message":"object [\"\"] is not a valid ObjectId","stack":"Error: object [\"\"] is not a valid ObjectId\n    at serializeObjectId (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:287:11)\n    at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:947:17)\n    at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:729:17)\n    at serializeObject (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:947:17)\n    at BSON.serialize (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/bson.js:64:28)\n    at Msg.serializeBson (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/msg.js:127:22)\n    at Msg.makeDocumentSegment (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/msg.js:119:33)\n    at Msg.toBin (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/msg.js:105:25)\n    at MessageStream.writeCommand (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:55:28)\n    at Connection.write (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:373:26)\n    at _command (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/command.js:125:10)\n    at command (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)\n    at writeCommand (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/write_command.js:56:3)\n    at Object.update (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/wireprotocol/index.js:9:5)\n    at Connection.update (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:195:8)\n    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/server.js:490:13\n    at Object.callback (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:345:7)\n    at processWaitQueue (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection_pool.js:468:23)"},"msg":"object [\"\"] is not a valid ObjectId"}
```
[uploadss.zip](https://github.com/RocketChat/Rocket.Chat/files/7738225/uploadss.zip)

Maybe it helps to find the problem

thank you!

- s

**Comment by dudanogueira** [comment]
PR https://github.com/RocketChat/Rocket.Chat/pull/24585 should fix this
