### ISSUE TITLE
Soft deleting chat messages

### ISSUE THREAD

**Issue by TheSETJ** [RocketChat/Rocket.Chat#23807]
Hello

I'm developing an application in which I use rocket chat's back-end. But in my application I want the messages to not be deleted completely (soft delete) and can be accessible for the admin. How can I prevent deleting or nullifying a message?

**Comment by dudanogueira** [comment]
hi! AFAIK, there isn't this feature.

Once you delete the message, it in fact deletes from the DB. Also, there is no "hide message" where could simulate this behaviour.

I am asking with more experienced RC devs and users, and will get back to you. 

If that's the case, this could be a great feature request.

Thanks!

**Comment by TheSETJ** [comment]
@dudanogueira Right, but what I'm asking is that how can I modify this behavior or prevent the message from being removed from DB?

**Comment by yash-rajpal** [comment]
Hey @TheSETJ, this feature is not available, but I believe you can reproduce the behaviour you want using the existing features in Rocket Chat.

if you are developing your front-end and only using RocketChat's backend, then you can make use of the custom fields for channels for keeping the track of soft delete date (timestamp) for each channel and then just render the messages from the date in custom fields to current date. 

Have a look here to know more about custom fields in rooms and how to set them - https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/setcustomfields

**Comment by dudanogueira** [comment]
I learned about the **Admin > Message > Show deleted Status** option, that will not remove the message object from the message collection, but instead will mark it as removed (t: rm) and in fact remove/nullify the msg content.

However, inspecting the code, i learned about this other option:
https://github.com/RocketChat/Rocket.Chat/blob/f50609df0b5a57375c019d1e19c7b0c345847f62/app/lib/server/functions/deleteMessage.ts#L33

when those two options are enabled (**Admin > Message > Show deleted Status** and **Admin > Message > Keep Per Message Editing History**), the resulting message, when edited will become:

```
{
   "_id":"cBmiAdxiix92AZfnu",
   "rid":"tB66HyiFgmwojYwC9",
   "msg":"teste2",
   "ts":{
      "$date":"2021-11-29T17:36:26.715Z"
   },
   "u":{
      "_id":"fKCApZExQec7JRqnt",
      "username":"admin",
      "name":"Administrator"
   },
   "_updatedAt":{
      "$date":"2021-11-29T17:36:36.484Z"
   },
   "urls":[
      
   ],
   "mentions":[
      
   ],
   "channels":[
      
   ],
   "md":[
      {
         "type":"PARAGRAPH",
         "value":[
            {
               "type":"PLAIN_TEXT",
               "value":"teste2"
            }
         ]
      }
   ],
   "_hidden":true,
   "parent":"rvsgRpw9Leu64cZZP",
   "editedAt":{
      "$date":"2021-11-29T17:36:36.484Z"
   },
   "editedBy":{
      "_id":"fKCApZExQec7JRqnt",
      "username":"admin"
   }
}
```
with a **_hidden** property that should be considered to hide it from the UI. **Not sure if this message will come up on rest apis.**

Do you think this is somewhat about what you expect?

**Comment by TheSETJ** [comment]
@dudanogueira I give it a try.
