### ISSUE TITLE
Make Tutorials

### ISSUE THREAD

**Issue by Dongheon97** [RocketChat/Rocket.Chat#23832]
I had some troubles setting up this service according to my environment(Cloud, Domain connecting, Local). So, based on my experience, I want to write tutorials that can be helpful for anyone who wants to build RocketChat in an environment like mine. I am going to write it in English and Korean, Could I write this?

**Comment by dudanogueira** [comment]
Hi!! Sure you can!! We really appreciate it!

We are in fact writing and recording some videos to help deployment.

I would suggest you to write a thread on forums, and we can work from there. When finished, we can publish on our blogs.

cc @debdutdeb is our deployment specialist and is leading this task.

I'll close this, as it's not an Issue. THanks!!!!
