### ISSUE TITLE
Deleting DMs from admin crashes UI for users viewing deleted conversation

### ISSUE THREAD

**Issue by gabriellsh** [RocketChat/Rocket.Chat#23847]
### Steps to reproduce:

1. Open Rocket.Chat in 2 tabs
2. Create a DM with any user and stay on the chat screen
3. In the other tab, navigate to Admin > Rooms, select the DM that's open on the other tab, and delete it.
4. Open the other tab, the app UI will be crashed.

Additionaly, for the admin user, refreshing the page and creating another DM with the same User causes an error, but after refreshing once more, the DM is created

### Expected behavior:

Display "Room does not exist" message

### Actual behavior:

UI Crashes

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0-develop 
- Operating System: Ubuntu 16.0.4 WSL
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Both crash
- Operating System: Windows

**Comment by dougfabris** [comment]
@gabriellsh I think this one is already fixed, could you double-check it?
Maybe fixed here: #23971

**Comment by gabriellsh** [comment]
Fixed already.
