### ISSUE TITLE
Want to start contributing to Rocket Chat

### ISSUE THREAD

**Issue by Utkarsh-88034** [RocketChat/Rocket.Chat#23841]
Hi, I am Utkarsh Jha and I am a web developer and i want to contribute to Rocket Chat. Please guide me in the right direction. I want to be a part of the community and help it in any way possible.
Thank you

**Comment by dudanogueira** [comment]
Hi! Please, take a look on this doc:
https://docs.rocket.chat/contributors/how-can-i-help

You should also hang out at our #dev channel:
https://open.rocket.chat/channel/dev

also there are a lot of new developers on our GSOC channel:
https://open.rocket.chat/channel/gsoc2021

and check out our forums:
https://forums.rocket.chat/

First step is to have a dev environment up and running. Check our Dev docs:
https://developer.rocket.chat/

I'll be closing this issue, as this is not an issue :)
