### ISSUE TITLE
Can't unpin deleted messages

### ISSUE THREAD

**Issue by lvh1** [RocketChat/Rocket.Chat#2384]
When you pin a message and then remove the message, it is still pinned and you cannot remove it from the pinned list anymore.

Version: latest/0.20.0

**Comment by marceloschmidt** [comment]
It seems to work for me.

![issue2384](https://cloud.githubusercontent.com/assets/1986378/13433713/db32608c-dfb1-11e5-8a0c-794cb9ca7c2d.gif)

**Comment by lvh1** [comment]
Hmm, could it be because the user who did this was not an administrator? I forgot I had turned that on (mistakes were made, lol) so normal users were able to pin messages.
So I guess the system tried to delete the pinned message, but because the user was not an administrator it failed.

**Comment by marceloschmidt** [comment]
Nice catch. Let me try with an unprivileged user.

**Comment by marceloschmidt** [comment]
I've made a few other attempts to reproduce this error. Can you show us an example that is not working?

![issue2384-2](https://cloud.githubusercontent.com/assets/1986378/13434724/aff7c70a-dfb5-11e5-8714-c023c07e0547.gif)

**Comment by lvh1** [comment]
OK, here you go: 
https://puu.sh/nrau6/1a33b506fd.mp4

**Comment by marceloschmidt** [comment]
Aha!! I think the problem actually happens with the Show Deleted Status set to true :) I'll fix that.
