### ISSUE TITLE
Failed Upgrade 3.18.3 to 4.0.0

### ISSUE THREAD

**Issue by wanderlage** [RocketChat/Rocket.Chat#23844]
### Description:

When trying to update version 3.18.3 to 4.0.0, after the login page there are errors in the console and the interface does not open. Errors being presented in node_modules.
Upgrade V3.17.2 to 3.18.2 working normally
Upgrade V3.18.2 to 3.18.3 working normally
Upgrade V3.18.3 to 4.0.0 Dont Working

### Steps to reproduce:

1. Update V3.17.2 to 3.18.2 
2. Update V3.18.2 to 3.18.3 
3. Update V3.18.3 to 4.0.0 

### Expected behavior:

Open the application normally. (3.18.3)
![image](https://user-images.githubusercontent.com/30476005/144439938-0bbdc056-dd75-4919-8969-c5d922133c52.png)

### Actual behavior:
Dont Work (4.0.0)
![image](https://user-images.githubusercontent.com/30476005/144433213-83bcc2c5-0a6d-42ad-8ae3-c36e833f96de.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  4.0.0
- Operating System: Ubuntu Server 20.04
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version:  2.22.1 - x64
- MongoDB Version: 4.4.10

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

Server: 
```
LocalStore: store created at
Thu, 2 Dec 2021 11:15:46	LocalStore: store created at
Thu, 2 Dec 2021 11:15:46	LocalStore: store created at
Thu, 2 Dec 2021 11:15:50	LocalStore: store created at
Thu, 2 Dec 2021 11:15:50	LocalStore: store created at
Thu, 2 Dec 2021 11:15:50	LocalStore: store created at
Thu, 2 Dec 2021 11:16:02	{"level":51,"time":"2021-12-02T14:16:02.472Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Migrating from version 232 -> 239"}
Thu, 2 Dec 2021 11:16:02	{"level":51,"time":"2021-12-02T14:16:02.473Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 233"}
Thu, 2 Dec 2021 11:16:02	{"level":51,"time":"2021-12-02T14:16:02.484Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 234"}
Thu, 2 Dec 2021 11:16:02	{"level":51,"time":"2021-12-02T14:16:02.660Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 235"}
Thu, 2 Dec 2021 11:16:02	{"level":51,"time":"2021-12-02T14:16:02.762Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 236"}
Thu, 2 Dec 2021 11:16:02	{"level":51,"time":"2021-12-02T14:16:02.774Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 237"}
Thu, 2 Dec 2021 11:16:03	{"level":51,"time":"2021-12-02T14:16:03.185Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 238"}
Thu, 2 Dec 2021 11:16:03	{"level":51,"time":"2021-12-02T14:16:03.776Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Running up() on version 239"}
Thu, 2 Dec 2021 11:16:03	{"level":51,"time":"2021-12-02T14:16:03.780Z","pid":1,"hostname":"rocketchat-f5f65b6d-6bj2f","name":"Migrations","msg":"Finished migrating."}
Thu, 2 Dec 2021 11:16:04	ufs: temp directory created at "/tmp/ufs"
Thu, 2 Dec 2021 11:16:09	Loaded the Apps Framework and loaded a total of 2 Apps!
Thu, 2 Dec 2021 11:16:10	LocalStore: store created at
Thu, 2 Dec 2021 11:16:10	LocalStore: store created at
Thu, 2 Dec 2021 11:16:10	LocalStore: store created at
Thu, 2 Dec 2021 11:16:18	Users with admin role already exist; Ignoring environment variables ADMIN_PASS
Thu, 2 Dec 2021 11:16:19	+-----------------------------------------------------------------+
Thu, 2 Dec 2021 11:16:19	| SERVER RUNNING |
Thu, 2 Dec 2021 11:16:19	+-----------------------------------------------------------------+
Thu, 2 Dec 2021 11:16:19	| |
Thu, 2 Dec 2021 11:16:19	| Rocket.Chat Version: 4.0.0 |
Thu, 2 Dec 2021 11:16:19	| NodeJS Version: 12.22.1 - x64 |
Thu, 2 Dec 2021 11:16:19	| MongoDB Version: 4.4.10 |
Thu, 2 Dec 2021 11:16:19	| MongoDB Engine: wiredTiger |
Thu, 2 Dec 2021 11:16:19	| Platform: linux |
Thu, 2 Dec 2021 11:16:19	| Process Port: 3000 |
Thu, 2 Dec 2021 11:16:19	| Site URL: https://rocketchat-teste.xxxxx |
Thu, 2 Dec 2021 11:16:19	| ReplicaSet OpLog: Enabled |
Thu, 2 Dec 2021 11:16:19	| Commit Hash: 2ffdd13795 |
Thu, 2 Dec 2021 11:16:19	| Commit Branch: HEAD |
Thu, 2 Dec 2021 11:16:19	| |
Thu, 2 Dec 2021 11:16:19	+-----------------------------------------------------------------+
Thu, 2 Dec 2021 11:16:25	(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
Client:
![image](https://user-images.githubusercontent.com/30476005/144439780-a1a58b98-4199-4950-b8c0-bd101580aefa.png)

**Comment by akong77** [comment]
I use snap upgrade will failed.

I upgrade from 3.18.1 to 4.1.2 use snap.But it’s will can’t start caddy.
Error message:

    2021-12-02T21:41:29+08:00 systemd[1]: Started Service for snap application rocketchat-server.rocketchat-caddy.
    2021-12-02T21:41:29+08:00 rocketchat-server.rocketchat-caddy[2351]: {“level”:“info”,“ts”:1638452489.7481782,“msg”:“using provided configuration”,“config_file”:"/var/snap/rocketchat-server/1494/Caddyfile",“config_adapter”:""}
    2021-12-02T21:41:29+08:00 rocketchat-server.rocketchat-caddy[2351]: run: adapting config using caddyfile: /var/snap/rocketchat-server/1494/Caddyfile:2: unrecognized directive: proxy
    2021-12-02T21:41:29+08:00 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
    2021-12-02T21:41:29+08:00 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result ‘exit-code’.
    2021-12-02T21:41:29+08:00 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Scheduled restart job, restart counter is at 5.
    2021-12-02T21:41:29+08:00 systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
    2021-12-02T21:41:29+08:00 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
    2021-12-02T21:41:29+08:00 systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result ‘exit-code’.
    2021-12-02T21:41:29+08:00 systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.
