### ISSUE TITLE
How can I upgrade Mongo DB to 4.0?

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat#23852]
### Description:

I just upgraded Rocket.Chat from 3.18 to 4.0, when I open Rocket.Chat from web and got error:
MongoDB DeprecatedMongoDB version 3.6.14 is deprecated, please upgrade your installation.

![mongo](https://user-images.githubusercontent.com/4077255/144555098-b0a60873-02c1-4a29-95b5-758f920e1c2c.png)
### Steps to reproduce:

1. Upgrade Rocket.Chat from 3.18 to 4.0
 # snap refresh rocketchat-server --channel=4.x/stable
rocketchat-server (4.x/stable) 4.0.5 from Rocket.Chat (rocketchat✓) refreshed
2. Then open Rocket.Chat from web and got error:
MongoDB DeprecatedMongoDB version 3.6.14 is deprecated, please upgrade your installation.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.5
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi! This is just a deprecation warning.

Here you can find supported mongo versions and deprecations:
https://docs.rocket.chat/getting-support#mongodb-versions

Here we have a forum announcement about this upgrade process:
https://forums.rocket.chat/t/updating-rocket-chat-snap-to-4-x-track/12575

**Comment by smallfish01** [comment]
> Hi! This is just a deprecation warning.
> 
> Here you can find supported mongo versions and deprecations: https://docs.rocket.chat/getting-support#mongodb-versions
> 
> Here we have a forum announcement about this upgrade process: https://forums.rocket.chat/t/updating-rocket-chat-snap-to-4-x-track/12575

Hi, Thanks for your replied.

I read the documents as you provided, due to I don't know how to safety upgrade my MongoDB to 4.0, I bypass the MongoDB version check now.

Thank you so much.
