### ISSUE TITLE
Typo in German translation

### ISSUE THREAD

**Issue by Koboo** [RocketChat/Rocket.Chat#23867]
**Describe the bug**
Provided that in the private chat the chat partner writes, a wrong translation in the German language is applied. 

What operating system and which version? 
Windows 10 Pro

Which version of Rocket.Chat.Electron (Electron)? 
3.5.7

Is there any setting relevant changed? 
Yes, Language setting to `German`

**To Reproduce**
Set the language of the client to German, start a private chat with another participant and let him type a message.
The current translation: "%client_name% **is** schreibt.."

**Expected behavior**
The correct translation: "%client_name% schreibt.."

**Screenshots**
https://imgur.com/a/FYUV27M

Thanks for your support and work on Rocket.Chat!

**Comment by TBG-FR** [comment]
Duplicate of #23593

**Comment by Koboo** [comment]
I can confirm that this is a duplicate of the #23593 
With that, I am closing this issue. Thank you very much for the reference to the other issue!
