### ISSUE TITLE
Can't get Active Directory users Authentication

### ISSUE THREAD

**Issue by Grejeru** [RocketChat/Rocket.Chat#2386]
Your Rocket.Chat version: 0.20.0

I'm trying to have working AD authentication. I don't have problems with OpenLDAP integration as I've done it on 3 different instances, but on Active Directory I can't get it working.
I'm doing almost all defaults, but in the logs I get keep saying that user is not found.

Is there a way to run server in more verbose state to see what exact LDAP query is being used to ensure that if I will run it in parallel using ldapsearch it will give/not give me informations?

Where I can define Base DN for user search, maybe because of that I can't find any users?

I'm using exact same configuration in Redmine (ldap user/password, group assignment) and it's working there, not here.

**Comment by homberger** [comment]
>but on Active Directory I can't get it working.
I'm doing almost all defaults, but in the logs I get keep saying that user is not found.

Maybe it would help if you show us your ldap settings.

>Is there a way to run server in more verbose state to see what exact LDAP query is being used to ensure that if I will run it in parallel using ldapsearch it will give/not give me informations?

You could set "Log Level" to "2 - Errors, Information and Debug". This setting can be found at "Administration" -> "Logs".

This is our working "Custom Domain Search":
```
{"filter": "(&(objectCategory=person)(objectclass=user)(sAMAccountName=#{username}))", "scope": "one", "userDN": "cn=LDAP_USER_FOR_AUTHENTICATION,,dc=ad,dc=example,dc=com", "password": "PASSWORD_OF_LDAP_USER_FOR AUTHENTICATION"}
```

"Unique Identifier Field" is set to objectGUID.

**Comment by Grejeru** [comment]
@homberger thx for tip with logs. Now I see that LDAP finds my user properly, question is rather why it can't authenticate me.

I've used Your settings and I have still the same problem. User is found, but I can't authenticate.
I'm using below settings:

Domain Base:
`dc=domain,dc=tld`

Custom Domain Search:
`{"filter": "(&(objectCategory=person)(objectclass=user)(sAMAccountName=#{username}))", "scope": "one", "userDN": "CN=LDAP Reader,OU=Service Accounts,OU=Users,OU=UK,OU=Departments,DC=domain,DC=ltd", "password": "XXxxXX"}`

Username Field:
`sAMAccountName`

Unique Identifier Field:
`objectGUID`

Sync Data: yes
Sync User Avatar: yes

User Data Field Map:
`{"name":"name", "mail":"email"}`

Default Domain: empty

**Comment by Grejeru** [comment]
Ok, I've found the reason. I've setup Rocket Chat to manually approve new users. After disabling this everything worked as a charm.
