### ISSUE TITLE
Copy paste discussions currently bad.

### ISSUE THREAD

**Issue by Maxzor** [RocketChat/Rocket.Chat#23868]
Hello, is this a design decision that the username is not in the copy-able html? Makes for copy-pasting discussions to other platforms hard.

**Comment by dudanogueira** [comment]
Hi!

Can you please state the version and the exact steps your are doing?

We need at least to reproduce it to discover if it's a bug or a feature request.

Thanks!

**Comment by Maxzor** [comment]
Try copying a block of conversation from the browser, in current open.rocket.chat
https://i.imgur.com/PEOEMPN.png
Without names and timestamps, copying a discussions looses a lot of its interest.

**Comment by serviceman** [comment]
I think what he is referring to is, when you copy and paste an conversation, the username (who said what) doesn't copy and paste with the rest of the conversation. for example, instead of something like this...

user1: hello
user2: hello back

it just copy and pasts as

hello
hello back

**Comment by debdutdeb** [comment]
@serviceman that kinda explains it, thanks.

I guess it is more of a feature request that a 'bug'.
