### ISSUE TITLE
OTR won't start – timeout

### ISSUE THREAD

**Issue by kbojens** [RocketChat/Rocket.Chat#23874]
### Description:

I want to initiate OTR with some other user on the same server but it always ends in a timeout with no OTR session established.

### Steps to reproduce:

1. Go to: OTR
2. Click on: Start OTR

### Expected behavior:

I would expect that a OTR session is started.

### Actual behavior:

No OTR session is started.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0
- Operating System: Ubuntu 20.04.3 LTS
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 5.0.4

### Client Setup Information

- Desktop App or Browser Version: Desktop App, 3.7.0
- Operating System: MacOS 12.0.1

**Comment by himpierre** [comment]
Same here. 4.2.0.

**Comment by Gummikavalier** [comment]
Confirming too, broken in RC 4.2.0.

**Comment by aimador** [comment]
Can confirm that for 4.2.1 on CentOS 7

**Comment by kbojens** [comment]
After 9 days I would somehow expect at least an answer like "yeah, we know" from the developers. This is a rather major feature …

**Comment by TomaszDom** [comment]
I don't think they care, look at how much they acknowledged https://github.com/RocketChat/Rocket.Chat/issues/20791

**Comment by jhartmann44** [comment]
Same here please fix it soon! We had that Bug back in version 3.12.... now we have it in 4.2.0 again

**Comment by dougfabris** [comment]
> After 9 days I would somehow expect at least an answer like "yeah, we know" from the developers. This is a rather major feature …

Hey @kbojens Thanks so much for reporting! Sorry for the delay, as you probably know we have a bunch of issues and we're always trying our best. The proper fix is on the way!
