### ISSUE TITLE
Slowness switching between channels after latest server update

### ISSUE THREAD

**Issue by haihosilver** [RocketChat/Rocket.Chat#23876]
### Description:

Slowness for all users since last update of rocketchat server, snaps 3.18.3.

### Steps to reproduce:

1. click on any direct message
2. click on #all

### Expected behavior:

Directly see the channel.

### Actual behavior:

* Channel goes white
* Chats are presented (old chats?)
* Auto "scroll" to bottom of chat (newest chats)

This takes approx 0.8 - 1.2 seconds. Feels sluggish and overall "slowness" switching between channels. Almost like MS Teams.

EDIT: Varies between 1-3 seconds, restart of server and clients sometimes fixes the issue BRIEFLY.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.3
- Operating System: Ubuntu 18.04.6 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.7.0 and 3.2.2
- Operating System: Windows 10

### Additional context

Worked fine on the older version of rocketchat server. Snap install with auto-update. This morning when it updated to the new design and 3.18.3 all users immediately noticed the new sluggishness switching between channels. MS Teams-like sluggish. 

Server rebooted
Clients restarted

Seems to be server version upgrade related.

### Relevant logs:

**Comment by alexweissman** [comment]
We've had this issue as well. And now today, the server is completely melting down with 100% CPU and memory usage. There's some task going on that's gobbling up all of the server resources after the latest update.

**Comment by haihosilver** [comment]
> Same issue here - except for more like 3-5 seconds before old chats jump down to most recent message when switching channels

Today its 2-3 seconds here as well. Restart of service does not solve the issue either.

**Comment by DigitalFriends** [comment]
We are having the same issues here, any workarounds or solutions for this yet?

**Comment by alexweissman** [comment]
@DigitalFriends I'm not sure why it worked, but I went to Administration > User Data Download and changed "Processing Frequency" from the default 2 minutes to 60 minutes. So far, I haven't had any more problems since doing this.

**Comment by Gummikavalier** [comment]
It seems that doing following triggers this issue in the web client:

1. Extensively scroll up on any channel with lots of messages upwards (500 to 1000 messages). This loads up lots of messages into the browser cache for this channel.
2. Scrolling couple of pages down again.
3. Switch to couple of other channels as usual.
4. Return to the original channel.

Result: Very slow operation. With a channel consisting of over 1000 messages returning to this channel takes 5 to 10 seconds. During that time the users sees only white page and cannot do anything else in the web client.

Even after scrolling back to the bottom of the channel, from this point on every time you return to this channel, the web client wants to arrange and render all messages again before showing the end result to the user.

Workaround for the issue: Refresh the browser screen.

**Comment by Vringe** [comment]
Same Issue here. Possibly related to https://github.com/RocketChat/Rocket.Chat/issues/31

**Comment by hugocostadev** [comment]
After the Room Rewrite to React and Blaze removal in **6.x Release** this is not happening anymore. Closing it
