### ISSUE TITLE
The downloaded file is corrupted.

### ISSUE THREAD

**Issue by noobbbbb** [RocketChat/Rocket.Chat#23881]
### Description:

The downloaded file is corrupted.
I'm not sure of a clear threshold, but it seems that larger file sizes are more likely to break.

■Message Side
href="https://[serverName]/file-upload/[fileID]/[filename]?download"

■FileSideBar Side
href="https://[serverName]/ufs/FileSystem:Uploads/[fileID]/[filename]"

If you download from the link on the message side, the file may be corrupted.

### Expected behavior:

Both can be downloaded successfully.

### Actual behavior:

The file is corrupted when I download it from the link on the message side.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0
- Operating System: CentOS
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: v4.0.5

### Client Setup Information

- Desktop App or Browser Version: Chrome 96.0.4664.45
- Operating System: Windows10

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
