### ISSUE TITLE
Omnichannel : user from department always available even outside business hours

### ISSUE THREAD

**Issue by sdelcroix** [RocketChat/Rocket.Chat#23894]
### Description:

I've added a user (with Admin Role) to a department with business hours.
Even outside these business hours, this user can switch his omnichannel status to available/online.

### Steps to reproduce:

1. Create a user with sufficient roles for LiveChat, or with Admin role
2. Add this user to an omnichannel department with business hours
2. Log in with this user outside of the business hours
3. Toggle On an Off the omnichannel status icon

### Expected behavior:

The user cannot switch to available status for omnichannel outside business hours.
A notification must says that business hours are off.

### Actual behavior:

The user can switch to available/unavailable status for omnichannel outside business hours.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14 / wiredTiger (oplog Activé)

### Client Setup Information

- Desktop App or Browser Version: Safari 14 & 15 / last version of Google Chrome
- Operating System: MacOS

### Additional context

Note that this issue doesn't occurs with the very first admin account.

**Comment by sdelcroix** [comment]
It now works after having wrote this issue. 

Is there some cron we have to wait for business hours to be applied to a user ?

**Comment by himani-mehra** [comment]
Hi @sdelcroix  , I would love to take on this issue and contribute to the project. Could you please assign it to me if it's available? Looking forward to your response. Thanks!

**Comment by sdelcroix** [comment]
@himani-mehra Hi, sorry I don't use Rocket.Chat anymore and I cannot assign people on issues (not a project maintainer).

**Comment by reetp** [comment]
> Could you please assign it to me

No one ever assigns issues here.

Looks like this works:

> It now works after having wrote this issue...

Closing.
