### ISSUE TITLE
Sound notifications don't work on Desktop App

### ISSUE THREAD

**Issue by ferossetto** [RocketChat/Rocket.Chat#23898]
Sound notifications don't work on Desktop App when I get a message. I've already configured it to play sound in all messages, but it doesn't work (until last week it worked normally, but it stopped working for no reason). My version is 3.0.2. I read many similar bugs on the forum, is there a possibility that this problem will be fixed permanently?

![1_print](https://user-images.githubusercontent.com/95761535/145230274-ead69529-53a6-48d9-808a-3caa68e41e9d.jpg)
![2_print](https://user-images.githubusercontent.com/95761535/145230284-0fa66449-c396-40f6-9a6f-f9eb36b1bf40.jpg)
![3_print](https://user-images.githubusercontent.com/95761535/145230290-e26ea175-833e-4981-8082-f77a62b026eb.jpg)

**Comment by dudanogueira** [comment]
hi, can you confirm this happens also on latest version?

**Comment by dudanogueira** [comment]
Also, please, specify server version, deploy method, etc.

here we have a template for opening an issue:
https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ferossetto** [comment]
> hi, can you confirm this happens also on latest version?

I just updated to the latest version (3.7.0) and the issue has been resolved. Many thanks
