### ISSUE TITLE
Blank channel when sending attachments as object

### ISSUE THREAD

**Issue by karlbateman** [RocketChat/Rocket.Chat#2389]
RocketChat v0.19.0
Running as a Docker container using compose on Debian amd64 Jessie.

Hi all,
I have integrated a Zapier webhook into RocketChat to get new tweets from my twitter list and send them to a `news` channel. Firstly it worked fine, then I started to play around with the format so that it matched what RocketChat was expecting. So using the double underscore approach to produce the nested data I finished the Zap and began running it. So now I get the messages within the channel, but the whole channel is blank. Using the inspector shows the `<div></div>` which is supposed to contain my messages is empty.

![rocket-chat_blank-channel](https://cloud.githubusercontent.com/assets/6918791/13426503/af6588be-dfa5-11e5-8904-4561980b8c76.jpg)

For the sake of trying to understand whats going on here, this is what I get from `docker logs <container_id>, so I know that it's not Zapier as it's sending the data correctly.`:

```javascript
@bodyParams { 
  text: 'Cabinet Office',
  attachments: 
  {
    color: '#2196F3',
    image_url: 'http://pbs.twimg.com/profile_images/664783281045532672/WZFsBWMR_normal.png',
    title_url: 'https://twitter.com/cabinetofficeuk/status/704618458852548608',
    title: 'The Independent Commission on Freedom of Information final report is now published https://t.co/N0nV5gmSmR' 
  } 
}
```

I really love RocketChat :rocket: guys so keep up the good work. Hopefully this is something trivial :smile: 

Thanks in advance,
K

**Comment by rodrigok** [comment]
Hi @karlbateman can we talk via chat?
My address is https://demo.rocket.chat/direct/rodrigo.nascimento

**Comment by karlbateman** [comment]
Yep even after clearing my cache, I have the same issue? It's killing whatever is in my cache as this issue moves over to when I am trying to view your pm's.

**Comment by rodrigok** [comment]
Can I access your instance?

**Comment by karlbateman** [comment]
Yeah sure, I will send you the details via dm on RocketChat.
