### ISSUE TITLE
Message count of each room is not accurate

### ISSUE THREAD

**Issue by brandonweis** [RocketChat/Rocket.Chat#239]

**Comment by rodrigok** [comment]
@brandonweis, can you explain?

**Comment by brandonweis** [comment]
![image](https://cloud.githubusercontent.com/assets/1314902/8395630/6282e3f6-1daf-11e5-8317-01a97204a4b5.png)
![image](https://cloud.githubusercontent.com/assets/1314902/8395635/81f2d390-1daf-11e5-8a20-5362e7779180.png)

I have one conversation in inchatpm channel but the message count shows 0. unless it's private message number not conversation number?
