### ISSUE TITLE
Ability to allow a group of users to search in chat only specified group of users.

### ISSUE THREAD

**Issue by dmidmi84** [RocketChat/Rocket.Chat#2390]
Your Rocket.Chat version: (0.20.0)
Let's say we have three user groups: A, B and C. It would be nice to be able to restrict the ability to communicate and search for contacts.
For example, users of group A can not communicate and search for contacts from the group B, but can communicate and search for contacts from group C. Group C can communicate with all groups A,B and C.

Thank you!

**Comment by engelgabriel** [comment]
This will be done at https://github.com/RocketChat/Rocket.Chat/issues/658
