### ISSUE TITLE
log4j security issue

### ISSUE THREAD

**Issue by srkunze** [RocketChat/Rocket.Chat#23927]
Just one question regarding the vulnerability of log4j. Is RocketChat affected?

**Comment by debdutdeb** [comment]
Hi, we don't have any dependencies on log4j, thus we shouldn't be affected.

I'll confirm with our engineering team. Closing this since not a bug.

**Comment by Philipp3211** [comment]
@debdutdeb Has the engineering team confirmed, that you are not affected?

**Comment by debdutdeb** [comment]
Yes @Philipp3211 :)

**Comment by derspotter** [comment]
I think this is incorrect. With `sudo find / -name "log4j*"` I found .../app/bundle/programs/server/npm/node_modules/moleculer/src/loggers/log4js.js I believe this is in rocket.chat or am I mistaken?

**Comment by gronke** [comment]
From https://github.com/log4js-node/log4js-node/blob/master/README.md

> Although it's got a similar name to the Java library log4j, thinking that it will behave the same way will only bring you sorrow and confusion.

**Comment by derspotter** [comment]
> From https://github.com/log4js-node/log4js-node/blob/master/README.md
> 
> > Although it's got a similar name to the Java library log4j, thinking that it will behave the same way will only bring you sorrow and confusion.

So log4js is not affected? I am relieved. Thank you for the fast answer.

**Comment by fdellwing** [comment]
This is a Java specific bug, the same library in any other language will not have this problem.
