### ISSUE TITLE
UX: Improve readability of input field placeholders

### ISSUE THREAD

**Issue by cyroxx** [RocketChat/Rocket.Chat#23934]
The placeholders for input fields and the message box are too hard to read.
The registration form looks like this:
![image](https://user-images.githubusercontent.com/1298447/145848553-a8b7a536-7e2b-458f-81bf-089b996795e7.png)

The placeholders are barely visible. I tried to improve the situation a little bit and used `#737A82` as the placeholder color:
![image](https://user-images.githubusercontent.com/1298447/145850603-7783fbcc-33dd-4dc9-8cb8-44b5bca55b29.png)
This is probably still not optimal but IMHO already a substantial improvement.

**Comment by Ayush01729** [comment]
Hello @cyroxx, I am Ayush, a web developer and I am currently working on this issue. 
Since I am new to Rocket Chat's codebase, could you please point out this exact directory??

**Comment by cyroxx** [comment]
Hi @Ayush01729,

Thank you for working on this issue!
Unfortunately, I am not familiar with the RocketChat codebase. I only tested this locally in my browser through the Web Developer Console, so I do not know where in the code this needs to be changed.

I'd suggest that you reach out to someone else, who is more familiar with the codebase and can point you into the right direction.

**Comment by dougfabris** [comment]
Hey @cyroxx thank you for your suggestion! We already have a great job done by our design team to make an entire replacement of this screen and very soon it will be implemented by the engineering team. Closing this one for now since it's not a proper issue, but stay with us to check these changes!

**Comment by cyroxx** [comment]
Hi @dougfabris, thank you for getting back to me on this. It's good to hear that your are working on an improvement on this. Is there any ticket or issue that I can follow/watch to stay updated on the upcoming changes?

Since you were pointing out that this here is "not a proper issue": Is there anything that I could have done better or differently? I was trying to report this UX/accessibility issue as good as possible, not on a payroll but in my spare time. If there is anything that can be improved by me or other volunteers when reporting such issues, please let me know.

**Comment by dougfabris** [comment]
@cyroxx I'm sorry I used wrong words, of course it's a proper issue, I would like to say that it's an issue we aware. I'm going to reopen and use this label to track ui changes that we already have planned, then when we have the proper PRs I'll sync them. Feel free to report the issues as you did here. You're welcome to interact with the community in our forum or the open server. We really appreciate your help. Thanks a lot!

**Comment by aakash-gitdev** [comment]
Hi @dougfabris, actually I want to resolve this issue, but since I am new to open source I am not really sure where is the relevant code directory for this. I went through the code base and am looking along this path currently - 
**app/theme/client/imports/general/forms.css**. Can you please suggest where should I look for the relavant code exactly?

Thanks

**Comment by dougfabris** [comment]
@aakash-gitdev We already have a proper solution for the issue. 
But we still do have a bunch of opened issues, feel free to help us and thank you 😄
