### ISSUE TITLE
HTML tags are visible in the hints of Settings in the Administration page

### ISSUE THREAD

**Issue by aswinidev** [RocketChat/Rocket.Chat#23936]
### Description:

The HTML tags are visible.

### Steps to reproduce:

1. Go to admin
2. Click on CAS or Email or any option.
3. The HTML tags are visible

### Actual behavior:

![Screenshot from 2021-12-13 22-01-52](https://user-images.githubusercontent.com/76481696/145851105-bb662eb2-03b0-4a83-9833-304357906e58.png)
![Screenshot from 2021-12-13 22-01-56](https://user-images.githubusercontent.com/76481696/145851121-2ff6204e-e36b-447a-874a-04e235d7d3bb.png)

### Server Setup Information:

- Version of Rocket.Chat Server: develop
- Operating System: LINUX

### Client Setup Information

- Desktop App or Browser Version: Browser 
- Operating System: LINUX

### Additional context

I was trying to fix this and so I think this is happening because of https://github.com/RocketChat/Rocket.Chat/blob/008310e95074aa3758e84ff1c545518ad84d350b/client/views/admin/settings/Setting.js#L96 where the description of the hints are passed into a markdown parser https://github.com/RocketChat/Rocket.Chat/blob/develop/client/components/MarkdownText.tsx which doesn't preserve the html tags as in the console.log i could see that after being parsed through marked() it changes `<` into `.&lt;` and `>` into `.&gt;` in the html strings that it returns which in turn causes the inline html tags in the content strings like `<br>`,`<ul>` etc, to be considered as a part of the content of `<p>` and not actual html tags. And so they are finally printed as it is. 

To find out before and after state the content (in MarkdownText.tsx):
![Screenshot from 2021-12-13 22-14-37](https://user-images.githubusercontent.com/76481696/145853411-0df21ad4-a14f-4cd5-a7d7-3a5c05980765.png)

Console Output of some hints which had html tags:

![Screenshot from 2021-12-13 22-12-26](https://user-images.githubusercontent.com/76481696/145853072-bf10aca1-794b-467b-a7f0-17b3fa4eab75.png)
![Screenshot from 2021-12-13 22-13-15](https://user-images.githubusercontent.com/76481696/145853104-1300b032-9a08-4af3-8501-a920d6ed5aaa.png)

 When I tried to run these marked content output in simple html editor then it converted `.&lt;br/.&gt;` into `<br/>`. So it believe it might be a way to write statements in html where we want to treat `<br/>` as a part of content and not html tag. And since marked() is converting it into this so the html tags are being visible in the hints of settings.

![Screenshot from 2021-12-13 22-33-05](https://user-images.githubusercontent.com/76481696/145856049-f49f7069-e087-4a93-9a6f-602c80eb449f.png)

**Comment by Aman-Maheshwari** [comment]
#23615  please look into this.

**Comment by aswinidev** [comment]
Hey @Aman-Maheshwari I m sorry I wasn't aware of that :v:

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/28854 

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
