### ISSUE TITLE
@all not working as expected in Threads

### ISSUE THREAD

**Issue by Czujackt** [RocketChat/Rocket.Chat#23935]
### Description:

If you create a thread and write @all in this thread, then all users who belong to the respective overlying message should actually be notified.

This works for person related notifications, but not for @all and @here.

### Steps to reproduce:

1. Create a message
2. Reply in Thread
3. Write @all

### Expected behavior:

Users should be notified and automatically follow the thread

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0
- Operating System: Ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v12.22.1
- MongoDB Version: 4.4.9 / wiredTiger (oplog Aktiviert)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
