### ISSUE TITLE
Docker adjustment to prevent port exposure

### ISSUE THREAD

**Issue by mindvox** [RocketChat/Rocket.Chat#2393]
Hi all,
As mentioned in this [article](http://blog.viktorpetersson.com/post/101707677489/the-dangers-of-ufw-docker), Docker manipulates iptables directly so you will not get the intended behaviour of allowing ports `80, 443`, if your running an instance on your host with an NGINX proxy. Your Docker instance can still be accessed by Docker's publicly exposed port. This allows your proxy to be bypassed and would not suffice within a production environment.

This is easy to overlook as you assume your firewall will be following the `DENY ALL` default. This is not an issue, but should be noted in the docs for Docker deployments. I wonder if the `docker-compose.yml` could be adjusted to mitigate this behavior?

Furthermore, if you are using Docker for your Rocket.Chat deployment you can append --iptables=false to your Docker configuration `/etc/default/docker` to avoid this, i.e.

```
...
# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --iptables=false"
...
```

I hope this is a worthwhile mention :smile:

Regards,
K

**Comment by geekgonecrazy** [comment]
By proxy do you mean like nginx reverse proxy?  Or other proxy system?

With docker you can do things like: `127.0.0.1:3000:3000`
Which is: {local ip}:{port}:{container port}

So say you actually are running a proxy and want to make available on your private ip instead of your public ip.  You could bind to your private ip doing something like: `192.168.1.100:3000:3000`

This format should be accepted in the docker-compose.yml file as well.

**Comment by karlbateman** [comment]
Thanks @geekgonecrazy, I think my issue stems from the fact that Docker is manipulating the iptable rules directly. This can be addressed by appending `--iptables=false` to your systems docker config. I just thought it was worth a mention.

**Comment by engelgabriel** [comment]
It is worth mentioning in deed, thanks for the article. I'll leave this issue open so we remember to add this to our documentation.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hasn't been done for two years now. Probably not gonna happen tomorrow. TBH I see this as a docker topic more than as a Rocket.Chat topic.

Cheers
Thomas
