### ISSUE TITLE
Emoji Picker dialog box auto closes after you select one emoji 

### ISSUE THREAD

**Issue by aswinidev** [RocketChat/Rocket.Chat#23943]
### Description:

Emoji Picker dialog box auto closes after you select one emoji which makes it inconvenient for someone who wants to add multiple emojis.

### Steps to reproduce:

1. Go to any channel or DM
2. Click on the emoji picker and pick one emoji
3. The dialog box closes after one selection

### Actual behavior:

https://user-images.githubusercontent.com/76481696/146055436-1dadcaaf-76bd-46df-9b2d-b45e24fa97a1.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: develop
- Operating System: Linux

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Linux

**Comment by Kunalvrm555** [comment]
@debdutdeb @dudanogueira attention required for this issue.
linked PR seems to have resolved the issue.
Please review

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this is not an issue, it's supposed to behave like that.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
