### ISSUE TITLE
After update the language is english

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#2394]
Hey Guys,

My  Rocket.Chat version is: 0.20.0

After the update today all users reported to me, that the mobile app now has the language "english" not "german". I tried to set the language in the general settings, restarted the server but this did not fix the issue. On my Windows Desktop all is fine.

Can i give you any logs? My Rocket.chat instance is running in a docker container.

Thanks in advance!

TheReal

**Comment by marceloschmidt** [comment]
@TheReal1604 was the app language set to German, or was it selected on users' preferences?

**Comment by TheReal1604** [comment]
hey @marceloschmidt 

the language is set for the complete instance. (Administration -> general -> language)

There I set it to german.

**Comment by marceloschmidt** [comment]
Are your users still experiencing language changes?

**Comment by TheReal1604** [comment]
@marceloschmidt yes, this happens to my mobile client too.

**Comment by marceloschmidt** [comment]
OK, I'll look into this and see if I can identify the problem... do you have any other information to help track this issue? 
Your app is set to German. 
1. Is your user preference set to German as well, or does it get reset to English? 
2. Does this happen from time to time, or does it always happen? 
3. If you create a new user on an anonymous browser window, does the new user get German or English language?

Thanks for your support on this.

**Comment by TheReal1604** [comment]
I checked the points in my mobile app...

1. my user preference is set to German
2. This happens always, but only on mobile clients. On the rocket.chat client for windows / mac all is fine
3. The new user gets the German language settings (all is fine on webclient) and on the mobile client i get the english menues and notifications.

Hope i can help you with this information.

**Comment by marceloschmidt** [comment]
@rodrigok , I confirmed this issue is happening in our Cordova app. Can you please take a look? Thanks.

**Comment by rodrigok** [comment]
@marceloschmidt @TheReal1604 Will be fixed via https://github.com/RocketChat/Rocket.Chat/pull/2590

**Comment by TheReal1604** [comment]
@rodrigok perfect, thanks for your work!
