### ISSUE TITLE
LDAP sign in hangs when creating a new user

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#2396]
Version: 0.19.0
Active Directory LDAP

When using LDAP to login when the user account has not yet been created on Rocket.Chat I get the authentication works correctly but it gets hung on "creating a new user."  I read the previous tickets that had this issue but could not fix it myself leading to the possibility that a bug still exists or that i'm doing something wrong.

Here is what the log shows, ending with "creating user R2".  Note that I deleted any possible sensitive data that was spit out in the log.

LDAPHandler ➔ info Init login r2 
I20160301-19:02:58.611(0) LDAP ➔ Connection.info Init setup 
I20160301-19:02:58.615(0) LDAP ➔ Connection.info Connecting ldap://192.168.5.10:389 
I20160301-19:02:58.619(0) LDAP ➔ Connection.debug connectionOptions { url: 'ldap://192.168.5.10:389',   timeout: 5000,   connectTimeout: 10000,   idleTimeout: 10000,   reconnect: false } 
I20160301-19:02:58.626(0) LDAP ➔ Connection.info LDAP connected 
I20160301-19:02:58.630(0) LDAP ➔ Bind.info Binding admin user CN=*my user*,CN=Users,DC=*comp domain*,DC=local 
I20160301-19:02:58.639(0) LDAP ➔ Search.info Searching user r2 
I20160301-19:02:58.644(0) LDAP ➔ Search.debug searchOptions { filter: '(&(objectCategory=person)(objectclass=user)(sAMAccountName=r2))',   scope: 'sub' } 
I20160301-19:02:58.648(0) LDAP ➔ Search.debug domain_base CN=Users,DC=*comp domain*,DC=local 
I20160301-19:02:58.668(0) LDAP ➔ Search.info Search result count 1 
I20160301-19:02:58.671(0) LDAP ➔ Search.debug Search result [   {     *Deleted list of user data for this message* } ] 
I20160301-19:02:58.699(0) LDAP ➔ Auth.info Authenticating CN=R Only 2,CN=Users,DC=*comp domain*,DC=local 
I20160301-19:02:58.710(0) LDAP ➔ Auth.info Authenticated CN=R Only 2,CN=Users,DC=*comp domain*,DC=local 
I20160301-19:02:58.714(0) LDAP ➔ Connection.info Disconecting 
I20160301-19:02:58.731(0) LDAPHandler ➔ info Querying user 
I20160301-19:02:58.735(0) LDAPHandler ➔ debug userQuery { 'services.ldap.id': '*deleted*' } 
I20160301-19:02:58.741(0) LDAPHandler ➔ debug userQuery { username: 'r2' } 
I20160301-19:02:58.746(0) LDAPHandler ➔ info User does not exists, creating r2

**Comment by rodrigok** [comment]
Do you have account creation restrictions? Like `Allowed Domains List`?

**Comment by engelgabriel** [comment]
Can you also try to upgrade to the version 0.20.0?

**Comment by twhiting** [comment]
@rodrigok No restrictions there.
@engelgabriel Upgraded & same problem

Any other ideas?

**Comment by rodrigok** [comment]
Can we talk in demo.rocket.chat? https://demo.rocket.chat/direct/rodrigo.nascimento

**Comment by rodrigok** [comment]
The problem was that the LDAP users don't have an email field, so we added a new log to inform that to admins and he solved the problem setting the Default Domain in LDAP settings to mount emails using username + @ + Default Domain.
