### ISSUE TITLE
Links not displayed in plaintext mails

### ISSUE THREAD

**Issue by psy** [RocketChat/Rocket.Chat#23967]
### Description:

Currently, HTML is simply stripped from the plaintext part of emails. Plaintext mails contain the link text, but not the link itself, which is pretty useless. For example a notification about a mention or direct message contains the "GO TO MESSAGE" link text, but not the actual link. Instead HTML links should be replaced by the link text and the link for the plaintext version.

![Selection_2021178](https://user-images.githubusercontent.com/1132707/146357391-73a215e6-321e-4cb9-b15a-4621061a3556.png)

### Steps to reproduce:

* Look at the plaintext part of emails, for example the "mentioned by XYZ" mail
* Find "GO TO MESSAGE" link text without link

### Expected behavior:

* Plaintext part should also contain the link

### Actual behavior:

* Links are removed.

**Comment by psy** [comment]
This is also important for https://github.com/RocketChat/Rocket.Chat/issues/23866

**Comment by camperjett** [comment]
Hi! Can you assign this to me.

**Comment by AbhishekJamhoriya** [comment]
Hi @psy can you please assign me this issue. so that I can work on it.

**Comment by Ayush01729** [comment]
So, @psy, you mean that the message which appears in an email should be a hyperlink, isn't it?

**Comment by Shofiya2003** [comment]
Is this issue still open?

**Comment by ritikBhandari** [comment]
Hi,
Can I work on this issue if still open?

**Comment by me-aashish** [comment]
I would like to work on this issue if it is still open

**Comment by Saumya-ranjan** [comment]
Is this issue still open?

**Comment by andynd** [comment]
This is still open but there is a working pull request ( since close to a year already actually ) in #23968 which just needs to be merged.

**Comment by AnkanSen** [comment]
I would like to work on this issue.

**Comment by kunals131** [comment]
I want to work on this issue.

**Comment by Gua00va** [comment]
Hey!! I want to work on this issue. I'm new here so I'm really excited to start contributing.

**Comment by andynd** [comment]
@Gua00va then read the whole issue and notice there is a finished PR just in need of merging.
Like that you just sound like a spam bot...

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
