### ISSUE TITLE
Add webdav account error. [duplicated-account] 

### ISSUE THREAD

**Issue by rtest12** [RocketChat/Rocket.Chat#23985]
Can't add webdav server account
My logs:

{"level":50,"time":"2021-12-18T20:27:41.748Z","pid":737,"hostname":"cloud4","name":"System","msg":"Exception while invoking method addWebdavAccount '[object Object] [duplicated-account]'"} 
I20211218-20:27:41.750(0) Exception while invoking method addWebdavAccount errorClass [Error]: [object Object] [duplicated-account]     at app/webdav/server/methods/addWebdavAccount.js:29:10     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)     at Server.call (packages/ddp-server/livedata_server.js:1607:17)     at Object.post (app/api/server/v1/misc.js:416:26)     at app/api/server/api.js:407:96     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:407:39)     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)     at packages/nimble_restivus/lib/route.coffee:59:33     at packages/simple_json-routes.js:98:9 {   isClientSafe: true,   error: 'duplicated-account',   reason: { method: 'addWebdavAccount' },   details: undefined,   errorType: 'Meteor.Error' } 

Ver. 4.2.0

**Comment by memphisraines87** [comment]
Same problem. On 4.1 all work fine. Afte update i can't add webdav server

**Comment by pipetamper** [comment]
Same Problem on 4.2.2 fresh install

**Comment by rtest12** [comment]
At 4.3 it worked, apparently fixed.
I see files, only download freezes, progress bar [0%]

**Comment by dougfabris** [comment]
Closing this issue, because it was fixed on this PR: #23924
The issue you mentioned related to the download was fixed here: #26422
Thanks for reporting these issues @rtest12 if you still having trouble after updating it, please let me know!
