### ISSUE TITLE
Invalid roles are created and can't be deleted

### ISSUE THREAD

**Issue by Hamulus** [RocketChat/Rocket.Chat#23989]
### Description:

Permissions page allow to created invalid roles and does not allow to edit/delete these roles, as well as they cannot be assigned using API.

### Steps to reproduce:

1. go to /admin/permissions and click plus at top right
2. enter desired role name and description, for example "test123", use Global scope and click save
3. Try to assign this role: this gives the following error: 
Client error: `POST https://chat.cryptomates.io//api/v1/users.update` resulted in a `400 Bad Request` response:
{"success":false,"error":"The field Roles consist invalid role name [error-action-not-allowed]","errorType":"error-actio (truncated...)

4. try to edit/delete this role, by clicking on role name
It shows "Invalid role"

### Expected behavior:

Role with wrong names should not be allowed to create and anyway they should have a possibility to be deleted

### Actual behavior:
![image](https://user-images.githubusercontent.com/6650292/146690167-51f3e8be-dfa7-4b93-b05a-c11e56f8cb6d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 20
- Deployment Method: regular install
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 6.14.6
- MongoDB Version: 4.4.10

### Client Setup Information

- Desktop App or Browser Version: Chrome 86
- Operating System: Windows 10

**Comment by dudanogueira** [comment]
I was able to reproduce this error.

also, tried a new permission called "a1" and was not able to reproduce.

On the other side, I was able to assign the test123 role to a user successfully both over API and UI.

Hamalus, can you elaborate more on this second issue?

**Comment by camperjett** [comment]
I created new permission, but I am unable to see it in the list of permissions

**Comment by camperjett** [comment]
@Hamulus I am interested in this issue. Can you help me with this?

**Comment by AbhishekJamhoriya** [comment]
Hi @Hamulus  i would like to work on this issue can you please assigne me this issue.

**Comment by Hamulus** [comment]
> Hi @Hamulus i would like to work on this issue can you please assigne me this issue.

I have no rights to assign issues

**Comment by wwc-trevor** [comment]
I ran into this issue as well and this is what I did as a workaround until it is fixed.

I was able to get rid of our invalid role by deleting the document from the rocketchat_roles collection. [^1]

@Hamulus You probably could assign new permissions in the users collection. It does assign a string instead of a role name which is strange but this is reflected in Administration > Users.

![image](https://user-images.githubusercontent.com/47799735/149426067-18da9727-304b-4379-b1d5-f09c2bd33fa4.png)

![image](https://user-images.githubusercontent.com/47799735/149426042-00e65e0e-74bd-4c68-bc2b-8c8155cb9bbe.png)


[^1]: I am using MongoDB Compass to explore the database.

**Comment by wwc-trevor** [comment]
I would consider this still active. I cannot use custom roles due to this bug. I am on RocketChat server 4.3.2

**Comment by LittleITworld** [comment]
We have the same issue with latest rocketchat version

**Comment by wwc-trevor** [comment]
What information is needed? I would love to continue this.

**Comment by LittleITworld** [comment]
I would give any information needed

**Comment by Deelight-fr** [comment]
I had had the same problem but it disappeared. I have a cluster of 5 nodes, and one node was off. Maybe it's linked...

**Comment by LittleITworld** [comment]
any updates?

**Comment by BuggyWilbur** [comment]
I am experiencing this issue, as well.  I've removed these permissions from all users and still cannot delete the custom permission roles.

**Comment by LittleITworld** [comment]
Problem still there!

**Comment by MacedoL** [comment]
Problem still there

**Comment by szdefine** [comment]
Problem still there  。 version 4.5.4， plz fix it

**Comment by vinogradovia** [comment]
@szdefine, fix #24052 in 4.6.0

**Comment by riberwind** [comment]
Problem still there 。 version 4.5.5
