### ISSUE TITLE
Setup wizard after wiredTiger migration

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat#23984]
### Description:

When I try to upgrade from mmapv1 to wiredTiger, under a docker installation, the migration seems to finish, but when I access the chat after it's done, I get greeted with the rocket.chat setup wizard. I have iFrame authentication implemented, if that makes any difference?

### Steps to reproduce:

1. Have a docker installation with iFrame set up
2. Follow wiredTiger migration guide: https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers/mongodb-mmap-to-wiredtiger-migration
3. After the migration is done, I get greeted with the rocket.chat setup wizard, as if it's a fresh installation? I had to roll back from the backup.

### Expected behavior:

Migration is sucessful and the chat continues working.

### Actual behavior:

Can't access the chat after the migration, instead I'm greeted with the setup wizard.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.1
- Operating System: Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.27 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

### Additional context

none.

### Relevant logs:

Server logs after the migration:

```
rocketchat_1          | https://github.com/browserslist/browserslist#browsers-data-updating
rocketchat_1          | ➔ System ➔ startup
rocketchat_1          | ➔ +----------------------------------------------+
rocketchat_1          | ➔ |                SERVER RUNNING                |
rocketchat_1          | ➔ +----------------------------------------------+
rocketchat_1          | ➔ |                                              |
rocketchat_1          | ➔ |  Rocket.Chat Version: 3.18.1                 |
rocketchat_1          | ➔ |       NodeJS Version: 12.22.1 - x64          |
rocketchat_1          | ➔ |      MongoDB Version: 4.0.27                 |
rocketchat_1          | ➔ |       MongoDB Engine: wiredTiger             |
rocketchat_1          | ➔ |             Platform: linux                  |
rocketchat_1          | ➔ |         Process Port: 3000                   |
rocketchat_1          | ➔ |             Site URL: http://localhost:3000  |
rocketchat_1          | ➔ |     ReplicaSet OpLog: Enabled                |
rocketchat_1          | ➔ |          Commit Hash: 73ab3c26a7             |
rocketchat_1          | ➔ |        Commit Branch: HEAD                   |
rocketchat_1          | ➔ |                                              |
rocketchat_1          | ➔ +----------------------------------------------+
rocketchat_1          | server.js:204 System ➔ error Exception while invoking method getUserRoles Invalid user [error-invalid-user]
rocketchat_1          | server.js:204 System ➔ error Exception while invoking method listCustomUserStatus Invalid user [error-invalid-user]
rocketchat_1          | server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName Invalid user [error-invalid-user]
rocketchat_1          | server.js:204 System ➔ error Exception while invoking method getRoomByTypeAndName Invalid user [error-invalid-user]
rocketchat_1          | server.js:204 System ➔ error Exception while invoking method createDirectMessage Match error: Expected string, got undefined
rocketchat_1          | server.js:204 System ➔ error Exception while invoking method createDirectMessage Match error: Expected string, got undefined
```

**Comment by debdutdeb** [comment]
Hi, since you rolled back, it won't be possible to understand why it might've happened :( 

Could you please try the process again and see if the setup wizard shows again or not?

**Comment by debdutdeb** [comment]
Can you please show us the output of the query - 

```
db.getSiblingDb('rocketchat').rocketchat_settings.find({_id: 'Show_Setup_Wizard'}).pretty()
```

**Comment by pbenkoe** [comment]
Thank you, give me a few days to get back to you. I'll re-try the upgrade and get these logs.

**Comment by pbenkoe** [comment]
Tried the upgrade again, and it worked. Thank you for your help!
