### ISSUE TITLE
"Open Video Chat using Application Window" does not work

### ISSUE THREAD

**Issue by mik2** [RocketChat/Rocket.Chat#23982]
### Description:

The option "Open Video Chat using Application Window" does not work. Chats are always opened in the browser.

### Steps to reproduce:

1. Go to Window -> Settings
2. Turn on "Open Video Chat using Application Window"
3. Start a Video Chat

### Expected behavior:

The chat is opened in a new Rocket.Chat window.

### Actual behavior:

The chat is opened in the browser.

### Client Setup Information

- Desktop App Version: 3.7.0
- Operating System: Windows 10

### Additional context

Works correctly in Desktop App Version 3.6.0.

**Comment by brianinca** [comment]
I'd add that for our setup, the Electron 3.7 client crashes changing that setting.

**Comment by jahohu** [comment]
Thanks for bringing it up! We did not start yet to roll out the client version that brings this feature, still on 3.5.7.

**Feature request**, when we are at this already: Would it be possible to add a setting to the admin panel that allows to set the default behaviour of this switch? We would prefer to set this to application window, which is the well-known and working behaviour in client version before 3.6.0, and maybe then an administrator configuration would be best for all scenarios. I understand that this setting here is on the client-side, but as the server determines the video behaviour, perhaps the suggested switch for default setting can find a way.

Cross-posting from my comment [here](https://github.com/RocketChat/Rocket.Chat.Electron/pull/2227#issuecomment-998031672) in the feature #2227.

**Comment by mik2** [comment]
In 3.7.4 and 3.7.6 the video chats are opened in an application window.
