### ISSUE TITLE
French translation error

### ISSUE THREAD

**Issue by Thysma** [RocketChat/Rocket.Chat#23983]
Hello,
it seems that there is an error in the French translation. Indeed, the word "crypté" does not exist in French, we use the word "chiffré".
Thank you very much
![image](https://user-images.githubusercontent.com/44775625/146606056-65f0a669-f754-4a71-b1ef-3fc67701bfd1.png)

**Comment by Karting06** [comment]
Hi,
It has already been fixed ;)

(it's debatable though: https://fr.wiktionary.org/wiki/crypt%C3%A9)

**Comment by dougfabris** [comment]
@Thysma It's already fixed, thanks for reporting!
