### ISSUE TITLE
File Sharing (Upload, Paste, Drop)

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#24]

**Comment by Sing-Li** [comment]
Interesting how a slight change on the title can turn a UI detail into a killer feature.

So are we thinking:

[scalable multicast]
single upload ->  S3 or Object Storage -> CND -> tons of downloaders

OR

[simple multicast]
single upload -> server-side temporary holding -> tons of downloaders

[p2p]
intent to share -> File Sharing 'Signaling'  ->  tons of sharing sessions going browser-to-browser
(almost too perfect for the data-channels portion of web-rtc)

Very cool.  Brings out the kim dot com in all of us :)

**Comment by sampaiodiego** [comment]
I think we are thinking in 'scalable multicast'..

you can paste an image or a file of any type and you or other can pin the object in the room, or simply download it.

actually, @rockhouse should be working on a part of these..

**Comment by engelgabriel** [comment]
BUG: Always pointing to localhost

![screen shot 2015-07-21 at 20 11 42](https://cloud.githubusercontent.com/assets/1000217/8814612/c92f29a6-2fe4-11e5-8a82-cac62ddf9c49.png)

**Comment by sampaiodiego** [comment]
@engelgabriel I think discussion (including bug reports) should continue on PR (#320)

**Comment by engelgabriel** [comment]
Initial version working.

**Comment by engelgabriel** [comment]
Added sub tasks:

https://github.com/RocketChat/Rocket.Chat/issues/369

https://github.com/RocketChat/Rocket.Chat/issues/370
