### ISSUE TITLE
"room not found" modal hides sidenav

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#2400]
Your Rocket.Chat version: 0.19
this code in template "main" hides sidenav, preventing selection of alternate room, when modal "room not found" is displayed...
					{{#unless modal}}
							{{> sideNav }}
						{{/unless}}

**Comment by marceloschmidt** [comment]
Can you share a printscreen so I can try to figure what happens? Thanks.

**Comment by neurobe** [comment]
my mistake
http://localhost:3000/room-not-found/c/xxx
works ok.
Perhaps the problem only appears at night. :-) 
Closing

**Comment by marceloschmidt** [comment]
Hahaha, specially if you are sleepy :) let me know if it occurs again.

**Comment by neurobe** [comment]
http://localhost:3000/room-not-found
does cover the sidenav, thus requiring a reload, but maybe that never arises in practice and so is not a problem??
