### ISSUE TITLE
Telegram Integration

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2402]
Hello,

First off, RocketChat is an amazing piece of work. I am an admin of a very small group of friends (15 guys) that have been keeping contact for the last 15 years mainly via online platforms - a forum and IRC. Recently, we switched to telegram, a fairly secure chat application that is available on many platforms. I am sure you have heard of it.

Anyway, with the api that telegram provide i cannot send the groupchat messages from an telegram group to our rocketchat platform via webhook. So far, i only managed to receive empty messages, as the webhook array is not properly formatted. This is the log from the received messages, which are displayed empty. Is there a way to  make this work
 `@bodyParams { update_id: 1337,   message:     { message_id: 1337,      from: { id: 123456789, first_name: 'bott0r' },      chat: { id: 123456789, first_name: 'Kai', type: 'private' },      date: 1456911431,      text: 'Hi how are you' } } `  

The reverse is however possible, i can ez pz send messages from a RC- channel to a telegram group (some info gets lost however (name of the sender).

I am very aware of that this is not a pressing issue, however telegram is being used by over 100 million people world wide and it would be splendid to allow some sort of crosschat platform. (i know sameroom.io does something similar with slack.) 

Best
 Kai

**Comment by engelgabriel** [comment]
We are about to release an option inside the integrations  for users to add a custom script do do the  payload parser. This will give you the power you need :)

**Comment by bott0r** [comment]
This is great!

**Comment by engelgabriel** [comment]
Depends on https://github.com/RocketChat/Rocket.Chat/issues/2426

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by bott0r** [comment]
https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---Telegram

**Comment by rodrigok** [comment]
@bott0r AWESOME, can we close this issue?

**Comment by valessiobrito** [comment]
Owww!!!  Thanks a lot!  Fantastic this integration!   :+1: :tada:

**Comment by rodrigok** [comment]
Well I will close this issue, please reopen it if you need.
