### ISSUE TITLE
SMTP server capabilities

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2405]
Add SMTP lib that receives emails in realtime with a unique address for each room.

Should allow for users to keep a conversation with others users that are using just email client instead of Rocket.Chat

https://www.npmjs.com/package/smtp-server

**Comment by jerome-chen** [comment]
+1

**Comment by mrsimpson** [comment]
+1 - any update on the state of this feature?

**Comment by SeanPackham** [comment]
Do we do this already? I know we have email replies.
