### ISSUE TITLE
Unable to access the message actions menu

### ISSUE THREAD

**Issue by abhi-abhiram** [RocketChat/Rocket.Chat#24066]
### Description:
I can't able to access the message actions menu after I starred it .But this happening only when I open pinned messages and, after i click on jump to message and, starred it.And This error **"Uncaught TypeError: t.starred.find is not a function"** is logged on console when I click on message actions menu. I caught this bug on this channel **https://open.rocket.chat/channel/gsoc2021**, 
I don't know whether same is happening on other channels. 
### Steps to reproduce:

1. Go to 'pinned messages' 
2. Click on 'jump to message' 
3. Select any message
4. Click on 'star' 
5. Now when you try to click menu again it wont appear and this error **"Uncaught TypeError: t.starred.find is not a function"** is logged on console.

### Expected behavior:
Access to message actions menu after it has starred

### Actual behavior:

![image](https://user-images.githubusercontent.com/68490325/147759936-0f82fb8f-a5e8-48ee-8eb1-dac9236d5a59.png)

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: win 10

**Comment by Barrylimarti** [comment]
It is indeed happening in the gsoc2021 channel but it is not happening in any other channel or on my workspace server.

**Comment by abhi-abhiram** [comment]
oh that is weird.
