### ISSUE TITLE
Rocketchat 4.3.0 not sending e-mails

### ISSUE THREAD

**Issue by michalstys** [RocketChat/Rocket.Chat#24071]
### Description:

After upgrade rocketchat to version 4.3.0, rocketchat stopped sending e-mails (log included)

### Steps to reproduce:

Try to send any notification or other e-mail message

### Expected behavior:

E-mails are sent

### Actual behavior:

E-mails are not sent

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1 

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

### Relevant logs:

Exception in defer callback: TypeError: Cannot read property 'email' of undefined
    at app/mailer/server/api.ts:170:44
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by dudanogueira** [comment]
Referenced Line:
https://github.com/RocketChat/Rocket.Chat/blob/4.3.0/app/mailer/server/api.ts#L170

Can you please check if the test email (Admin > Email > Smtp > Send a test to my user) is working for you?

I tried reproducing here, but to no success. Can you reproduce that on a new fresh installed docker?

**Comment by michalstys** [comment]
(Admin > Email > Smtp > Send a test to my user) option doesn't work either (same error happens).

I have set environment variable in my docker-compose.yml file:

MAIL_URL=smtps://user:pass@my.domain:465/

I tried to set up smtp server at Admin > Email > Smtp too, but that doesn't help.

When I roll back RocketChat version to 4.1.2 e-mails works fine, but when I upgrade to 4.3.0 it stops to work and there's error that I mentioned.

**Comment by skibbipl** [comment]
Same on my installation. I've upgraded today and I see errors in log:
`
I20220101-19:07:56.002(0) Exception in defer callback: TypeError: Cannot read property 'email' of undefined     at app/mailer/server/api.ts:170:44     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24) 
`

**Comment by gobbli** [comment]
Same for me on my 4.3.0 installation. If a user register, he get a mail from the system. 2FA over EMAIL and EMail testing over SMTP Settings in Admin Panel didn't work.

`I20220102-20:40:24.856(1) Exception in defer callback: TypeError: Cannot read property 'email' of undefined     at app/mailer/server/api.ts:170:44     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24) 
`

**Comment by mosesdd** [comment]
same issue here, **afaik this is unsupported** but I was able to downgrade to 4.2.2 after editing the migrations collection in mongodb

`db.migrations.update({"version":252},{"version":249})`

**Comment by gusdgg** [comment]
I think It's related to this change introduced in 4.3.0 version:

APPS: Add new email event for apps (#[23925](https://github.com/RocketChat/Rocket.Chat/pull/23925))

**Comment by Gavilaan** [comment]
Same problem here. But funny, i have 3 installations running, all installed and updated with the same ansible script. On 1 machine mail is working, 2 others not.

**Comment by wolbernd** [comment]
It seems that fc9c193ccfa7039ef763828c3324fcf34b23a106 fixes this problem. I set up a local dev instance and sending mails works with the current HEAD.

**Comment by skibbipl** [comment]
Are there any ways to enable apps framework as a workaround without email TOTP? Maybe disable TOTP temporarily in database?

**Comment by jazztickets** [comment]
4.3.1 fixed it for me.

**Comment by skibbipl** [comment]
Yup, also works for me

**Comment by brknapik** [comment]
Still issue in 4.3.3 version

On dev-tools:

```
Exception in delivering result of invoking 'login': Error: Invalid Two Factor method
    at m (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1272)
    at d (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1272)
    at 29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1270
    at 29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1079
    at Array.forEach (<anonymous>)
    at l._pageLoadLogin (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1079)
    at Object.userCallback (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1083)
    at o (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1079)
    at r (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1079)
    at n._callback (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1)
```
```
Error: No callback invoker for method 2
    at 29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1045
    at Array.forEach (<anonymous>)
    at M._process_updated (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1045)
    at M._processOneDataMessage (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1045)
    at M._livedata_data (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1045)
    at p (29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1272)
    at 29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1272
    at 29ad5156ad3b5e63ea49d9d0b214648b266cb7ca.js?meteor_js_resource=true:1

```

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
