### ISSUE TITLE
User Info not opening correctly after switching between channel types

### ISSUE THREAD

**Issue by grahhnt** [RocketChat/Rocket.Chat#24079]
### Description:

By using the "view full profile" link inside a UserCard, on first load the link will open the user info tabbar and change the url, but when you click on the same link after switching from a Channel to a DM the link will no longer open the user info panel, but will change the url

### Steps to reproduce:

1. Open a channel on page load (eg https://open.rocket.chat/channel/dev)
2. Click on a username
3. Click on "view full profile"
4. RocketChat will show the user info panel ![image](https://user-images.githubusercontent.com/46821216/147865344-a7652b91-0b2d-4a53-91d9-0619d798fb20.png)
4. Switch to a DM channel
5. Click on a username
6. Click on "view full profile"
7. The user info panel will not show, but the url will change ![image](https://user-images.githubusercontent.com/46821216/147865350-5e759b07-d4eb-431b-bd01-58b38fb2e5ca.png)

### Expected behavior:

User info panel will open

### Actual behavior:

User info panel will not open

### Server Setup Information:

- Version of Rocket.Chat Server: latest develop commit (also affects current open.rocket.chat install)
- Operating System: centos 7
- Deployment Method:  git
- Number of Running Instances: 1
- DB Replicaset Oplog: Meteor
- NodeJS Version: Meteor
- MongoDB Version: Meteor

### Client Setup Information

- Desktop App or Browser Version: Latest git
- Operating System: Windows 10

### Relevant logs:

No errors/logs appear upon interaction

**Comment by serviceman** [comment]
I reported this many versions ago. I have been forced to hack the script with some custom javascript. Here is what use.

`
let lastUrl = location.href; 
new MutationObserver(() => {
const url = location.href;
  
  if (url !== lastUrl) {
    lastUrl = url;
//Gets the mini profile correctly in the direct messages
if ((window.location.href.indexOf('direct') > 0 ) && (window.location.href.indexOf('members-list') > 0) ){

  var pathArray = window.location.href.split('/');
  var memberID = pathArray[5];
 

  FlowRouter.go("direct/" + memberID +"/user-info/");

}
    
//Gets the mini profile correctly in the rooms
if (     (window.location.href.indexOf('channel') >  0 ) && (window.location.href.indexOf('user-info') > 0) ){

  var pathArray = window.location.href.split('/');
  var memberName = pathArray[7];
  var roomName = pathArray[5];
  
  FlowRouter.go("channel/" + roomName +"/members-list/" + memberName);

  
}  
}).observe(document, {subtree: true, childList: true});
`

**Comment by grahhnt** [comment]
@serviceman I've made a fix: https://github.com/RocketChat/Rocket.Chat/pull/24098

**Comment by ankar84** [comment]
Confirm that issue on 4.2.2
