### ISSUE TITLE
UiKit Button Action not working on latest develop branch

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/Rocket.Chat#24074]
### Description:

When we try to click on any UIKit buttons sent by the apps, the button action never gets triggered. I can see the following error within the browser console
![image](https://user-images.githubusercontent.com/34130764/147826657-ed6cc78d-4bbd-4f7c-b4b1-2fb956682e1f.png)

Ps: it seems like `/api/apps/ui.interaction/:appId` endpoint is not working. This issue is reproduceable on unstable server

**Update:** Buttons are working on 4.3.0, so this issue seems to be introduced after the release

### Steps to reproduce:

Click on any buttons like
![image](https://user-images.githubusercontent.com/34130764/147826762-ab3647ae-9bd9-402b-ad70-58a95a90f857.png)

### Server Setup Information:

- Version of Rocket.Chat Server: **Latest Develop branch post 4.3.0 release**
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Himanshu664** [comment]
I'd like to work on this!

**Comment by d-gubert** [comment]
This PR introduced a change that was breaking this https://github.com/RocketChat/Rocket.Chat/pull/24053 

It has since been reverted and all is back to normal :)
