### ISSUE TITLE
RocketChat 4.3.0 Segmentation Fault

### ISSUE THREAD

**Issue by DoramGreenblat** [RocketChat/Rocket.Chat#24080]
### Description:

Upon starting Rocket Chat, the service runs for a few minutes, then dies with 
```main process exited, code=killed, status=11/SEGV```

### Steps to reproduce:
Start RocketChat and Wait for failure

### Actual behavior:

```
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: ### New Enterprise License
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: #### License validated: pro:*
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: +-------------------------------------------------------------+
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |                        SERVER RUNNING                       |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: +-------------------------------------------------------------+
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |                                                             |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |  Rocket.Chat Version: 4.3.0                                 |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |       NodeJS Version: 12.22.6 - x64                         |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |      MongoDB Version: 4.2.17                                |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |       MongoDB Engine: wiredTiger                            |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |             Platform: linux                                 |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |         Process Port: 3000                                  |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |             Site URL: https://rocketchat.site.url/  |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |     ReplicaSet OpLog: Enabled                               |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |          Commit Hash: 9161223c6b                            |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |        Commit Branch: HEAD                                  |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: |                                                             |
Jan 02 23:39:48 SERVER_NAME rocketchat[6868]: +-------------------------------------------------------------+
Jan 02 23:58:49 SERVER_NAME systemd[1]: rocketchat.service: main process exited, code=killed, status=11/SEGV
Jan 02 23:58:49 SERVER_NAME systemd[1]: Unit rocketchat.service entered failed state.
Jan 02 23:58:49 SERVER_NAME systemd[1]: rocketchat.service failed.

```

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.6 - x64
- MongoDB Version: 4.2

**Comment by debdutdeb** [comment]
@tassoevan any ideas 🤔

**Comment by DoramGreenblat** [comment]
For a little more information. I have narrowed this down to be related to API jobs.
It seems to trigger on certain API calls.

**Comment by DoramGreenblat** [comment]
A full debug of the crash event follows

```
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.383Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Integrations","section":"Outgoing WebHook","msg":"Execute Trigger:","arg":"sendMessage"}
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.383Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Integrations","section":"Outgoing WebHook","msg":"Got the event arguments for the event: sendMessage","argObject":{"event":"sendMessage","message":{"rid":"RPYCB2tpfkY5znhtc","msg":"[service.name.removed](https://url.removed/service/audit/-/jobs/96278) release 1.0.1 is ready for prod-jhb deployment.","alias":"Deploy Bot","emoji":":robot:","ts":"2022-01-03T10:20:25.321Z","u":{"_id":"iub4SuEDXjovi4b76","username":"deploybot","name":"deploybot"},"unread":true,"_id":"hEAcoQsahA4nY3EF6","_updatedAt":"2022-01-03T10:20:25.375Z","urls":[{"url":"https://url.removed/service/audit/-/jobs/96278"}],"mentions":[],"channels":[],"md":[{"type":"PARAGRAPH","value":[{"type":"LINK","value":{"src":{"type":"PLAIN_TEXT","value":"https://url.removed/service/audit/-/jobs/96278"},"label":{"type":"PLAIN_TEXT","value":"service.name.removed"}}},{"type":"PLAIN_TEXT","value":" release 1.0.1 is ready for prod-jhb deployment."}]}]},"room":{"_id":"RPYCB2tpfkY5znhtc","name":"Channel_removed","fname":"channel_removed","t":"p","msgs":35,"usersCount":20,"u":{"_id":"AmRFctJhrHyL2C9dc","username":"username.removed"},"customFields":{},"broadcast":false,"encrypted":false,"ts":"2019-03-17T11:17:26.372Z","ro":false,"default":false,"_updatedAt":"2022-01-03T10:19:47.255Z","lm":"2022-01-03T10:19:47.208Z","lastMessage":{"_id":"rw3YiZ4PK3oFZHehz","rid":"RPYCB2tpfkY5znhtc","msg":"testing","ts":"2022-01-03T10:19:47.208Z","u":{"_id":"y3QeYamZhM6KbfRYy","username":"username.removed","name":"USER_REMOVED"},"unread":true,"_updatedAt":"2022-01-03T10:19:47.248Z","urls":[],"mentions":[],"channels":[],"md":[{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"testing"}]}]}}}}
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.384Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Integrations","section":"Outgoing WebHook","msg":"Starting search for triggers for the room: RPYCB2tpfkY5znhtc"}
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.384Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Integrations","section":"Outgoing WebHook","msg":"Found 0 to iterate over and see if the match the event."}
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":35,"time":"2022-01-03T10:20:25.387Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"API","method":"POST","url":"/api/v1/chat.sendMessage","userId":"iub4SuEDXjovi4b76","length":"210","host":"rocketchat.url.tld","remoteIP":"178.128.165.23","status":200,"responseTime":69}
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.392Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Callbacks","msg":"Executing callback with id emojione-shortnameToUnicode for hook beforeSendMessageNotifications"}
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.397Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Callbacks","msg":"Executing callback with id oembed-providers-before for hook oembed:beforeGetUrlContent"}
Jan 03 12:20:25 SERVER_NAME_REMOVED systemd[1]: rocketchat.service: main process exited, code=killed, status=11/SEGV
Jan 03 12:20:25 SERVER_NAME_REMOVED systemd[1]: Unit rocketchat.service entered failed state.
Jan 03 12:20:25 SERVER_NAME_REMOVED systemd[1]: rocketchat.service failed.
```

**Comment by tassoevan** [comment]
Hey @DoramGreenblat, any core dump file generated when the crash happens?

**Comment by charlretief** [comment]
@tassoevan the crash happens when a message contains an embedded url with a local domain name like https://test.example/page

Seems like the problem is in a callback hook oembed:beforeGetUrlContent that tries to generate a preview for this local only url.

```
Jan 03 12:20:25 SERVER_NAME_REMOVED rocketchat[15718]: {"level":20,"time":"2022-01-03T10:20:25.397Z","pid":15718,"hostname":"SERVER_NAME_REMOVED","name":"Callbacks","msg":"Executing callback with id oembed-providers-before for hook oembed:beforeGetUrlContent"}
```

**Comment by Gummikavalier** [comment]
@charlretief As I could not reproduce the issue just by posting a message with an url with a local domain name, is there a specific way how this can be triggered for testing?

**Comment by charlretief** [comment]
Sending a chat message of `https://test.example/page` crashes the server for me.

**Comment by Gummikavalier** [comment]
@charlretief I tried that with the web client. Does that happen with an iOS or Android client? Or some particular type of channel?

**Comment by Gummikavalier** [comment]
Linking earlier https://github.com/RocketChat/Rocket.Chat/issues/23346 here in case this is related to node binary particular to CentOS7.

**Comment by charlretief** [comment]
Have noticed it happening in direct messages and messages posted to private groups. Using the web client.

**Comment by Gummikavalier** [comment]
@charlretief Thanks! Still stable for us on those types of channels too. Is your server operating system perhaps CentOS7 as is with the original poster of this issue?

**Comment by andreas-by** [comment]
@Gummikavalier we can replicate the crashing with a segfault.

- Centos 7
-  npm -v 6.14.1
-  node -v v12.22.1

Sending the link https://test.example/page via direct messages causes a complete crash of the instance

**Comment by Gummikavalier** [comment]
@andreas-by Thanks.

We also experienced now a segfault on RC 4.3.1 but we cannot trigger it with that message. Instead the node keeps growing in memory until it bombs.

**Comment by aimador** [comment]
@Gummikavalier can confirm it for Centos 7, RC 4.2.1, Node 12.22.1, NPM 6.14.12
Interestingly your link crashes the instance. Other links with an internal domain do not crash the server.

**Comment by Gummikavalier** [comment]
For the record we did not have segfaults with RHEL8 with RC 4.2.1 (had been in use since its release). We upgraded to 4.3.1 directly from that.

**Comment by andreas-by** [comment]
We can trigger it with .example and .invalid other domains like .localhost dont crash the system.
As workaround we put the broken domains on the blacklist....

**Comment by rozbit** [comment]
I have similar problem
`main process exited, code=killed, status=11/SEGV`
after sending inexisting url in direct message. Example https://test.example/page or https://hospital.local/

Server Setup Information:
Version of Rocket.Chat Server: 4.4.0
Operating System: CentOS 7
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 14.19.0 - x64
MongoDB Version: 4.2.18

**Comment by Gummikavalier** [comment]
On RHEL8 and 4.3.x we have so far had but only one segfault in one node, pretty soon after the upgrade to 4.3.x.

I'm still not sure what caused that one, but it seems that this segfault that is triggered via posting just an url does not happen on the node binary of RHEL8 at all. It is likely to be related to CentOS7 node binary.

**Comment by gwbrew** [comment]
Confirmed from my end https://test.example/page  crashes as well as other local urls.
Tried on web and desktop version.. bot crash rocketchat.
 
RC 4.4.2 
Node Version v14.0.0
MongoDB 4.4.12 / wiredTiger 
Centos 7

Is there a work around yet or suggestion of change? Thanks!

**Comment by tassoevan** [comment]
@lestercoyoyjr may have found it for some users in this thread. Canonically, the *minimum Node.js version was set to 14.18.2* only in version 4.4.0 due to a Meteor upgrade (#24075), but it may be possible that some dependency have a bad manifest that doesn't warn about the engine version.

It doesn't seem to be the case for @rozbit and @gwbrew, I think...

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
