### ISSUE TITLE
Welcome Email - Logo is not rendered

### ISSUE THREAD

**Issue by anvo1205** [RocketChat/Rocket.Chat#24081]
### Description:

After I signed up and setup the cloud domain for my org, I received the welcome email, but the logo is not rendered

### Steps to reproduce:
1. Sign up an SaaS account
2. Check the mailbox after successfully sign up

### Expected behavior:
Logo should be correctly rendered

### Actual behavior:
Rocket chat logo is not rendered. 404 error in the console

I am not sure what is the server information mean, but I used a bug report tool called Bird Eats Bug to capture as much info as needed including screenshot/video, console log, network requests, system info (client), etc. Please see this link here: https://app.birdeatsbug.com/sessions/xYgBDsxIANMrBUbAClfwf

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
