### ISSUE TITLE
Update strategy

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#2408]
What is the general approach to updating Rocket.Chat from an older version? For example, when updating from 0.16.0 to 0.20.0 can I skip all the minor releases in between? Or should I go 0.17.0, 0.18.0 and so on?

Would be nice to get the policy explicitly stated in https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker#5-update-an-already-installed-instance

**Comment by rodrigok** [comment]
You can update directly to the newest version, the migrations will execute from the old version to the new version.

**Comment by gramakri** [comment]
@rodrigok thanks. db migrations are just one aspect though. Are there any other aspects of the system that might fail because of direct upgrades?

**Comment by gramakri** [comment]
As a silly example, if version 1 moves a directory from foo to bar and version 3 from bar to baz. Then jumping from version 1 to version 3 won't work.

**Comment by rodrigok** [comment]
Not now, our migrations are not db only, are software version upgrade.

**Comment by engelgabriel** [comment]
Even if we have some filesystem move in the future, we will include in the migrations.

**Comment by gramakri** [comment]
@rodrigok @engelgabriel thanks, I have updated the wiki.

**Comment by saigop** [comment]
Am using 0.10.2, which i downloaded via git. Now I wanted to upgrade to latest, so only option is via I have remove the old Rocket.Chat directory and install the new one...! If yes, then the DB will remain same? or will that also be deleted? Please advice. Thanks

**Comment by engelgabriel** [comment]
How are you running the Rocket.Chat process? Did you do a `meteor build`? Where is your DB?

If you are only using the `meteor` command to run Rocket.Chat (not recommended for production), your database will be inside the `/.meteor` folder, so you have to copy it across to the new folder.

**Comment by saigop** [comment]
I have started my Rocket chat process by executing "pm2 start main.js". I didn't do meteor build.

**Comment by engelgabriel** [comment]
In that case, it is unlikely you have downloaded via git, as there is no main.js on the git repo, you need to build it. Can you please double check what you have done?

**Comment by saigop** [comment]
Yes I downloaded via git. Or can I remove the whole directory or move the directory of Rocket.Chat and install from the scratch?

**Comment by engelgabriel** [comment]
What is the value of you MONGO_URL setting?

**Comment by saigop** [comment]
MONGO_URL=mongodb://localhost:27017/rocketchat

**Comment by engelgabriel** [comment]
So the DB will remain the same.

**Comment by saigop** [comment]
Ok thanks for all your suggestions, let me move the folder and will
download fresh copy from git.

Thank you.
