### ISSUE TITLE
Administration >> Integrations - Failed to load Zapier integration

### ISSUE THREAD

**Issue by anvo1205** [RocketChat/Rocket.Chat#24086]
### Description:

Another issue with content security policy I think. The Zapier integration keeps loading and I can't see which options are available

### Steps to reproduce:

1. Sign in as an admin
2. Go to Administration >> Integrations
3. Click on Zapier tab

### Expected behavior:

The Zapier integration options should be loaded

### Actual behavior:

The table keeps loading. There is a console error `Refused to load the script 'https://zapier.com/apps/embed/widget.js?services=rocketchat&html_id=zapier-goes-here' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

Please open this link to see additional information including video, console errors, technical info and system info:
https://app.birdeatsbug.com/sessions/lVz8i7d-Tetb_PSZgG0WQ?

**Comment by cmoore-mayesh** [comment]
Were you able to find a fix for this?  I'm experiencing after upgrading to the 4.0 track on snap.

**Comment by dudanogueira** [comment]
Hi, please, check this doc on how to properly configure Zapier with Rocket.Chat:
https://docs.rocket.chat/guides/administration/admin-panel/integrations/zapier

**Comment by nonno-cicala** [comment]
> Hi, please, check this doc on how to properly configure Zapier with Rocket.Chat: https://docs.rocket.chat/guides/administration/admin-panel/integrations/zapier

I think I did follow that doc, my Zapier integrations work, but I still have this issue with RC 4.8.4
