### ISSUE TITLE
Incoming integrations broken after upgrade 3.18.0 to 4.3.0

### ISSUE THREAD

**Issue by TomaszDom** [RocketChat/Rocket.Chat#24099]
### Description:

Incoming integrations no longer work after upgrading from 3.18.0 to 4.3.0.

All integrations return the following message from the server:

`{"success":false,"error":"Invalid href value provided"}`

This behaviour is the same with old and newly recreated integrations, when using the sample curl command the behaviour is the same.

### Steps to reproduce:

1. Go to Administration -> Integrations
2. Click New and fill in the form, make sure the bot user is in the room where you want to send messages
3. Enable integration, save it, run the sample `curl` command provided in the form, e.g.:

`curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}' https://[REDACTED/hooks/[REDACTED]`

### Expected behavior:

Sample message sent correctly to the room.

### Actual behavior:

No message appears in the room, curl command receives reponse:

`{"success":false,"error":"Invalid href value provided"}`

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.0
- Operating System: Ubuntu Server 
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.27

### Client Setup Information

- Desktop App or Browser Version: all
- Operating System: all

### Relevant logs:
```

{"level":30,"time":"2022-01-04T06:44:19.114Z","pid":24320,"hostname":"[REDACTED]","name":"Integrations","section":"Incoming WebHook","msg":"Post integration:","name":"test2"} 
{"level":20,"time":"2022-01-04T06:44:19.115Z","pid":24320,"hostname":"[REDACTED]","name":"Integrations","section":"Incoming WebHook","urlParams":{"integrationId":"[REDACTED]","token":"[REDACTED]"},"bodyParams":{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"/images/integration-attachment-example.png","color":"#764FA5"}]}} 
{"level":35,"time":"2022-01-04T06:44:19.122Z","pid":24320,"hostname":"[REDACTED]","name":"API","method":"POST","url":"/hooks/[REDACTED]/[REDACTED]","userAgent":"curl/7.68.0","length":"224","host":"[REDACTED]","remoteIP":"[REDACTED]","status":400,"responseTime":8}
```

**Comment by Gummikavalier** [comment]
We are not sure whether this is completely related to issue you are experiencing with RC 4.3.0, as it actually is more related to the testing example that RC integrations page offers for testing.

We spotted in RC 3.18.3 that unless you specify full image path in the `image_url` in the example, you get that invalid href value error message. Changing it to `https://[your_rc_site]/images/integration-attachment-example.png` works.

**Comment by dudanogueira** [comment]
@Gummikavalier, You are right.

I have even noticed this example error last week, and was planning to submit a PR changing it to https://open.rocket.chat/assets/logo.png

@TomaszDom can you please provide us with other example you have used or try the above command:



`curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"[/images/integration-attachment-example.png](https://open.rocket.chat/assets/logo.png)","color":"#764FA5"}]}' https://[REDACTED]/hooks/[REDACTED]`

**Comment by Gummikavalier** [comment]
@TomaszDom I just remembered that apart from the example issue, the actual issue you are experiencing may be that since RC 4.0 the account used in the integration needs to be a member on the channel. Try adding the rocket.cat as a member to the channels with integrations.

**Comment by whitetiger264** [comment]
> @TomaszDom I just remembered that apart from the example issue, the actual issue you are experiencing may be that since RC 4.0 the account used in the integration needs to be a member on the channel. Try adding the rocket.cat as a member to the channels with integrations.

This seemed to work for me after running a few tests. Thanks.

**Comment by pescobar** [comment]
I was also experiencing this issue with my gitlab integrations. It seems that since rockechat 4.x the json sent to the webhook endpoint should not provide a field `username` . Sending a field `username` was working with rocketchat 3.x

I have fixed the issue by editing my gitlab integrations and setting `username` to an empty field. I also had to add my bot user to the channels where the alerts are sent.

**Comment by TwizzyDizzy** [comment]
I do, however, see an oddity in the hooks URLs:

```
# Hook that is working

https://my.company.chat/hooks/djXCXBg3jb4tjf6bN/8gPxFcqAjSg6snnjEhbMzCWRuCqdEftAPBf4WYwbXHdTsNTi

# Hook not working
https://my.company.chat/hooks/1233744254d4c6ddda79eedf/4LwAABnqA3ZgBibXPpJPKmWRyhnM2MXQgRDjhvYTCBdjMBpy
```

Notice how there seems to be a numerical prefix to the token that is not present in the hook that is working?

The sole difference between those hooks is, IIRC, that the one that is working has been created ages ago, the one not working has been (re-)created recently.

So I'm taking a wild guess: on newly created (or before a certain commit or whatever) integrations were created correctly and currently they are not being created correctly (namely the token having a prefix and a `/` - `1233744254d4c6ddda79eedf/4LwAABnqA3ZgBibXPpJPKmWRyhnM2MXQgRDjhvYTCBdjMBpy` in the second example.

Can anyone confirm this wild guess?

Cheers
Thomas

**Comment by dbilewicz** [comment]
> I do, however, see an oddity in the hook URLs:
> 
> ```
> # Hook that is working
> https://my.company.chat/hooks/djXCXBg3jb4tjf6bN/8gPxFcqAjSg6snnjEhbMzCWRuCqdEftAPBf4WYwbXHdTsNTi
> 
> # Hook not working
> https://my.company.chat/hooks/1233744254d4c6ddda79eedf/4LwAABnqA3ZgBibXPpJPKmWRyhnM2MXQgRDjhvYTCBdjMBpy
> ```
> 
> Notice how there seems to be a numerical prefix to the token that is not present in the hook that is working?
> 
> The sole difference between those hooks is, IIRC, that the one that is working has been created ages ago, the one not working has been (re-)created recently.
> 
> So I'm taking a wild guess: old (or before a certain commit or whatever) integrations were created correctly and currently they are not being created correctly (namely the token having a prefix and a `/` - `1233744254d4c6ddda79eedf/L4wAABnqA3ZgBibXPpJPKmWRyhnM2MXQgRDjhvYTCBdjMBpy` in the second example).
> 
> Can anyone confirm this wild guess?
> 
> Cheers Thomas

I have same issue. Old integrations works, but new with different "token style" don't work. I have error 503.

**Comment by jganseman** [comment]
Having a similar issue here. An external system seems to succeed in sending a message to the webhook, and rocketchat seems to receive it fine, but the content is gone. The value of "bodyParams", where I imagine the content should be, is empty. From rocketchat logs: 

```
{"level":30,"time":"2022-05-27T13:40:14.648Z","pid":1253,"hostname":"rocketchat","name":"Integrations","section":"Incoming WebHook","msg":"Post integration:","name":"my_webhook_name"} 
{"level":20,"time":"2022-05-27T13:40:14.650Z","pid":1253,"hostname":"rocketchat","name":"Integrations","section":"Incoming WebHook","urlParams":{"integrationId":"my_webhook_ID","token":"my_webhook_token"},"bodyParams":{}} 
{"level":35,"time":"2022-05-27T13:40:14.651Z","pid":1253,"hostname":"rocketchat","name":"API","method":"GET","url":"/hooks/my_webhook_ID/my_webhook_token","userAgent":"Apprise","host":"my_rocket_server","remoteIP":"my_external_service","status":200,"responseTime":3}
```

The sent messages have a payload with 'text' and 'avatar' fields.

Possibly a content parsing problem somewhere in on the RocketChat side?

**Comment by banoleb** [comment]
the same  issue in 5.* . Some old or now webhooks failed with code 400. It happened after update from 3* to 4 version.
 
`{"level":35,"time":"2022-09-27T15:19:36.301Z","pid":1,"hostname":"9669479ea658","name":"API","method":"POST","url":"/hooks/6*********a99fbe118fd/HzZ*****************************************vJ","userAgent":"Java/1.8.0_332","length":"1912","host":"chat-domen.com","remoteIP":"192.168.11.2","status":400,"responseTime":5}`
I think it is because of payload. Now it has new format or something else
