### ISSUE TITLE
`ReferenceError: LDAP_DEFAULTS is not defined` when LDAP_Url is set

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#2409]
Your Rocket.Chat version: Starting from 0.18.0

I get the following backtrace when LDAP_Url is set on startup.

```
19:09:08 [main] /app/code/bundle/programs/server/node_modules/fibers/future.js:245
19:09:08 [main]                         throw(ex);
19:09:08 [main]                               ^
19:09:08 [main] ReferenceError: LDAP_DEFAULTS is not defined
19:09:08 [main]     at server/lib/ldap.coffee:3:3
19:09:08 [main]     at /app/code/bundle/programs/server/boot.js:249:5
```

**Comment by gramakri** [comment]
It looks like this started from 3c7c6c2e5ae66aa4d227b6646c773de78bfd2fae which removed the variable from exports.

**Comment by gramakri** [comment]
I managed to fix the Cloudron app by simply not using LDAP_Url and using LDAP_Host instead.

**Comment by engelgabriel** [comment]
@rodrigok should we close this? Or do we have to improve the error message to avoid new issue in the future?

**Comment by rodrigok** [comment]
Fixed, we do not use the LDAP_DEFAULTS anymore, as LDAP now uses the settings directly we don't need to set this object anymore.
