### ISSUE TITLE
LDAP: First user cannot login with username (but can login with email)

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#2410]
Your Rocket.Chat version: >= 0.17.0

Starting from 0.17.0, the first user is unable to login with username. Logging in via email works.

Also tested with 0.20.0 and the issue persists.

**Comment by gramakri** [comment]
I am trying to bisect the commit that broke this in https://github.com/cloudron-io/rocketchat-app/issues/8

**Comment by gramakri** [comment]
@rodrigok do you know the commit that causes this? if not, i will continue bisecting when I find the time.

**Comment by rodrigok** [comment]
@gramakri no sorry, I have no idea.

**Comment by engelgabriel** [comment]
@marceloschmidt is this related to what you are doing?

**Comment by engelgabriel** [comment]
@gramakri is this only with LDAP? Can you list the steps to reproduce?

**Comment by gramakri** [comment]
Steps to reproduce:
0. Start out fresh with no users.
1. Add LDAP settings to mongodb - LDAP_Enable, LDAP_Url, LDAP_Port, LDAP_DN, LDAP_Bind_Search, LDAP_Sync_User_Data. You can see the variables set in https://github.com/cloudron-io/rocketchat-app/blob/master/start.sh
2. Start Rocket.Chat (you can see lower down in start.sh that it's just a simple `node main.js` invocation)
3. Cannot login using LDAP username. Logging in using LDAP email works. This worked in 0.16.0 but has stopped working since 0.17.0.

In 0.16.0, the first LDAP user that logged in became the superadmin automatically.

I have only tested this with LDAP. I will test this without LDAP shortly.

@engelgabriel

**Comment by engelgabriel** [comment]
@gramakri do you know that you can pass ANY settings to the Rocket.Chat process via Environment Variables, and it will store them on the DB when it starts?

**Comment by gramakri** [comment]
@engelgabriel ah, that is good to know! I will slowly move our app to use that pattern.

cc @nebulade

**Comment by gramakri** [comment]
I justed tested without LDAP.
0. Start out fresh with no users.
1. Register new user with email and then choose a username.
2. Can login with username.

That said, the LDAP and non-LDAP cases are a little different. What I really want to test is if Rocket.Chat will allow the first user to login via username when there are no users in the database (which I cannot test with non-LDAP case since I register a user first).

**Comment by engelgabriel** [comment]
Did you configure the LDAP -> Username Field ?

**Comment by gramakri** [comment]
@engelgabriel I thought we used it but there is a typo in the code. So, we use the defaults. Has something changed about the userdata field map? I tried setting it `LDAP_Sync_User_Data_FieldMap` to `'{"username":"name", "mail":"email"}'` but that doesn't seem to work.

**Comment by gramakri** [comment]
OK, I was able to fix this. Looks like a whole lot of the config variables have changed. Settings `LDAP_Custom_Domain_Search` and `LDAP_Username_Field` correctly fixes the problem.

Looks like some values are not migrated correctly from 0.16.0 to 0.17.0 but since they are old releases, I will close this issue.
