### ISSUE TITLE
CAS popup does'nt close automatically 

### ISSUE THREAD

**Issue by laurent6** [RocketChat/Rocket.Chat#24103]
### Description:

When I use CAS connexion the popup window not close. If we clode it manually we are connect to rocketchat 
Note that autoclose option is enable to 
### Steps to reproduce:

1. Configure CAS option  
2. Click on button CAS
3.  Wait and see

https://www.loom.com/share/80bb228798e74eca9c2382024020f801

### Expected behavior:

The popup automatically close 

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: ubuntu 
- Deployment Method:  docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v12.22.1
- MongoDB Version: 5.0.4 / wiredTiger (oplog Activé)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by laurent6** [comment]
Hi, 
no one have any idea about this issue

**Comment by pierre-lehnen-rc** [comment]
Fixed by #23215 on Rocket.Chat 4.3.0
