### ISSUE TITLE
Already selected users are not visible while adding another user from the Add Users menu

### ISSUE THREAD

**Issue by try-catch-stack** [RocketChat/Rocket.Chat#24115]
### Description:

There is now way to see if we have already selected a user from the dropdown list in the Add User menu. Also the dropdown list automatically closes after selecting a user which makes it inconvenient to select multiple users.

### Steps to reproduce:

1. Go to the members section of a group/channel.
2. Click on Add button on the bottom.
3. Start selecting users from the list and you will see that the you will not be able to see the already selected users with the list is open.

### Expected behavior:

We should have a separate sections on the above of Text field which will show the selected users. Also the options list can be changed to select multiple users at once maybe with checkbox or without it but with a visual effect that the user is selected.
Another thing which can be seen in the attached video is that when we search for a user and click on the clear button on the right , the text is not cleared but sort of flickers. The button doesn't even have a tool tip to define its behavior so I am not sure if that is the expected behavior but I feel it is supposed to clear the text field can show to current selected users.

### Actual behavior:

https://user-images.githubusercontent.com/77742477/148400376-1e5465b7-aeaf-4eb2-b306-eb39b67f9017.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Shivansh-yadav13** [comment]
rather than making a separate section maybe we can just keep the selected users in place of having "Choose users" on the search. what do you think? @try-catch-stack

**Comment by try-catch-stack** [comment]
@Shivansh-yadav13 Yes that should also work but we need to take care of the space available for typing as it is a text field in the first place. Let's see what admins suggest about the issue.

**Comment by dudanogueira** [comment]
Hi! This is indeed not the best UI experience.

I have marked tag UI and will raise it to our UI/UX team. Not sure if this should be here or in 
https://github.com/RocketChat/Rocket.Chat.Fuselage

**Comment by dudanogueira** [comment]
For reference:
https://rocketchat.github.io/Rocket.Chat.Fuselage/fuselage/master/?path=/docs/forms-multiselect--multi-select-filtered

**Comment by Sayan-dev** [comment]
Are we still on this? Then I can proceed with the UI change

**Comment by try-catch-stack** [comment]
Appreciate your interest @Sayan-dev ! But we already have a [PR](https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/645) for refactoring of MultiSelect component , that can be used here in place of autocomplete component . You can however have a discussion with the team and work on migrating to MultiSelect after the above PR is merged in the Fuselage repo.
