### ISSUE TITLE
Oauth Error: Failed to use RestAPI by oauth

### ISSUE THREAD

**Issue by anti1234** [RocketChat/Rocket.Chat#2411]
Your Rocket.Chat version: develop

Hi , I am tring to use the oauth2 for RocketChat . I have registered the third client on the Rocket website  and  also  got  the  accss_token  like this:
```
{
  "token_type": "bearer",
  "access_token": "a825c202ef2de7ff2bdcd21f0e362e44a9f984b2",
  "expires_in": 3600,
  "refresh_token": "82ae7143c52b728368129f1f6017f626af7d57bc"
}
``` 
But I am confused that how could I access the API with this token ?  The [Rocket Chat REST API
] (https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs) wiki looks like this :

```
curl -H "X-Auth-Token: 9HqLlyZOugoStsXCUfD_0YdwnNnunAJFV47U3QHXSq" 
  -H "X-User-Id: aobEdbYhXfu5hkeqG" 
  http://localhost:3000/api/publicRooms

{
  "status": "success",
  "rooms": [
    {
      "_id": "GENERAL",
      "usernames": [
        "admin",
        "sing"
      ],
     "ts": "2015-07-24T14:35:23.542Z",
     "t": "c",
      "other fields": "other fields ...."

```

It seems to use a diffrent  authorization mechanism, what should I do?  

Thank you for any idea ! :smile:

**Comment by rodrigok** [comment]
What is exactly your question? After the OAuth authorization you have the access token, you should use it as described in your post.

**Comment by anti1234** [comment]
@rodrigok  Thanks for your replay :-D. 

 My problem is I just got the `"access_token": "a825c202ef2de7ff2bdcd21f0e362e44a9f984b2"`. 

However, from the wiki  [Rocket Chat REST API] (https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs) ,it seems needing two arguments : `X-Auth-Token` and `X-User-Id`. 

Where can I get the `X-User-Id` ?  So appreciate if you could show a example about how to use it .

**Comment by anti1234** [comment]
Well ,I got the userId from the `rocketchat_oauth_access_tokens` collection . 
```
meteor:PRIMARY> db.rocketchat_oauth_access_tokens.find({accessToken:/a825c/}).pretty()
{
	"_id" : "F5BhDsepd6qxDTc7G",
	"accessToken" : "a825c202ef2de7ff2bdcd21f0e362e44a9f984b2",
	"clientId" : "C2ygYaFTgpjRw2rmG",
	"userId" : "3Lot3kbwCPPqcKvG5",
	"expires" : ISODate("2016-03-03T04:29:10.582Z")
}
```

Then I use the `accessToken` and `userId` to access the `publicRooms` API . 

```
curl -H "X-Auth-Token: a825c202ef2de7ff2bdcd21f0e362e44a9f984b2" 
  -H "X-User-Id: 3Lot3kbwCPPqcKvG5" 
  http://localhost:3000/api/publicRooms
```
But I got the error result : 
```
{
  "status": "error",
  "message": "You must be logged in to do this."
}
```

I found the [kahmali/meteor-restivus](https://github.com/kahmali/meteor-restivus/blob/devel/lib/route.coffee)  will check the authorization from the `users` collection while [RocketChat/rocketchat-oauth2-server](https://github.com/RocketChat/rocketchat-oauth2-server) just insert  the accessToken into `rocketchat_oauth_access_tokens` collection . 

They seems have two diffrent authorization mechanism for me.  

meteor-restivus： 
```
Api.addRoute 'articles/:id', authRequired: true,
    get: -> 
      Articles.findOne @urlParams.id
```
rocketchat-oauth2-server:
```
oauth2server.routes.get('/account', oauth2server.oauth.authorize(), function(req, res, next) {
  var user = Meteor.users.findOne(req.user.id);

```

Is it right to use oauth accessToken to access to RestAPI ? Or maybe I should write another api for oauth security ?  

:cry:  Thank for any replay !

**Comment by rodrigok** [comment]
Ok, the `publicRoom` (https://github.com/RocketChat/Rocket.Chat/blob/develop/server%2Frestapi%2Frestapi.coffee) REST api is not enabled to work with OAuth, you should use the Restivus auth style.

The APIs that you can access via OAuth are here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-api%2Fserver%2Froutes.coffee we need to migrate the other APIs to this package to enable for OAuth.

**Comment by anti1234** [comment]
Got it !  :smile:

**Comment by rackmuthu** [comment]
We are using Keycloak as oauth2 provider for Rocket Chat. We are trying to access REST API of Rocket Chat from a JS Client. The JS Client login via Keycloak and gets the access token. But REST API expects User-ID and AUth-Token. How do we use the Access token provided by Oauth2 provider in accessing REST API of Rocket chat?

**Comment by TheDreamSaver** [comment]
How did you get the access token @anti1234 ?
Which endpoint you used?
