### ISSUE TITLE
Add user agent 'internal server error'

### ISSUE THREAD

**Issue by JelX7ouss** [RocketChat/Rocket.Chat#2412]
As a root or admin, I want to be able to see guests messages. In livechat /livechat-manager/users I want to add the root account I've just created to 'add agent', however an 'internal server error' appears. 

Here is what I did:
**Step one**: register a new user named 'root', **Step Two**: set the role to admin in my shell using
`db.users.update( { "_id" : "USER_ID" }, { $set: { "roles" : "admin" } } )`

On the other hand, if I create a simple user, and directly add that user as an agent, all works! But I want the admin to be an agent.

So I am thinking of using the shell again. Anyone can provide me a query like the above one?

**Comment by JelX7ouss** [comment]
Ok.

So I fixed this by using the shell again. If anyone is having this type of error when trying to add the root account as an agent please read [this](https://github.com/RocketChat/Rocket.Chat/wiki/Roles-and-Permissions#roles-available)

And in your mongod shell type:

`db.users.update( { "_id" : "USER_ID" }, { $set: { "roles" : ["admin", "livechat-agent"] } } )`

you can either logout, or the settings will be auto. refreshed.

**Comment by engelgabriel** [comment]
Why did you use the shell in the first place? You should be able to do it all via admin panel.

**Comment by JelX7ouss** [comment]
Hey @engelgabriel , See this [doc](https://github.com/RocketChat/Rocket.Chat/wiki/Creating-the-First-Admin)

After I've created the account (called root) I've set it as admin as the doc says using the shell.
I also had to make the root account a livechat-agent, but using the panel nothing works! So I used the shell again.
The only time the panel worked for me is when I've created an account an directly set it to livechat-agent (like a simple account, no admin roles required)

**Comment by JelX7ouss** [comment]
Either there is a bug, or may be the doc must be updated.

**Comment by engelgabriel** [comment]
I guess the doc must be updated. What DOC did you use?

**Comment by engelgabriel** [comment]
I've deleted the document, the first user is automatically granted admin rights.

**Comment by JelX7ouss** [comment]
@engelgabriel  Thanks.
 "automatically granted admin rights" Yeah!
You know I had to re-install everything, but what I've encountered is the same.
As you said, the first user will be auto. an admin, and I CHECKED that using shell.. but going back to the panel I just can't set that first user account as a livechat-agent also! I guess may be I did something wrong? Anyway... I just wanted to point this :)

**Comment by engelgabriel** [comment]
Let me check that last part. @sampaiodiego please help?

**Comment by JelX7ouss** [comment]
@engelgabriel Well, I re-installed and tested it, it works from the Panel! WOW LOL

But trust me, I had to use the shell in the first place... because something wrong just happend... However, now this better be closed HAHA

**Comment by engelgabriel** [comment]
OK! I glad it is working now!
