### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#2413]
I try to connect my android application (Rocket.Chat) to our server . it downloads all files but can't connect to server (it show waiting for server connection, trying again ...)

rocket.chat version 0.20 
Android 4.4
Rocket chat Android app downloaded from play store.

Its working on via browser. let me know if any ports to be allowed in firewall?

**Comment by rodrigok** [comment]
How are you running your server? Via docker or using the `meteor` command?

**Comment by sureshdba2003** [comment]
using meteor command

**Comment by rodrigok** [comment]
ok, so you should use `meter --mobile-server http://yourServerAddres:port`

**Comment by sureshdba2003** [comment]
Yes, i have used the same command meter --mobile-server http://xxx.xxx.xxx.xxx:3000. but it is didn't work? any other port to be allowed?

**Comment by engelgabriel** [comment]
@sureshdba2003 you should never use the `meteor` command in production.

**Comment by engelgabriel** [comment]
Please reopen with more info if the problem persists.

**Comment by jots** [comment]
I have the same problem.  starting rocket.chat with pm2.  How do I get the --mobile-server   into the command line?  I don't recall how the pm2 was setup.

**Comment by engelgabriel** [comment]
Did you build from source or did you download the compiled version?

**Comment by jots** [comment]
I had a version installed from source from Oct 2015. 
I overwrote it with the latest by getting code:
`curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz`
and replacing old directory with the new one and running `npm install` in programs/server.

**Comment by engelgabriel** [comment]
Try to use the latest develop, we just did some fixes.

**Comment by jots** [comment]
Thanks.
I tried develop.  but it comes up with a bluescreen.  devtools shows:
```
Mixed Content: The page at 'https://server/' was loaded over HTTPS, but
 requested an insecure XMLHttpRequest endpoint
 'http://server:3000/sockjs/info?cb=vpb_5a08pj'. This request has been 
blocked; the content must be served over HTTPS.
```
why is that :3000 in there?  I have nginx ssl proxy in front.

revert back to non dev version and site works again.

**Comment by engelgabriel** [comment]
Did you configure your ROOT_URL? Or the SIte_URL on the admin penal?

**Comment by jots** [comment]
Changing SIte_URL on the admin panel fixed it!
I had to delete my server entry on the android app and add it again, and it works!
thank you!
