### ISSUE TITLE
CAS: Admin unable to change password for a user or force a password reset

### ISSUE THREAD

**Issue by Mihara** [RocketChat/Rocket.Chat#2414]
Your Rocket.Chat version: 0.20 - just installed from official docker image.

We're considering a migration to RocketChat from Slack, because we have message archives exceeding the free limit and a fluid and uncertain number of users. Importing a large archive is kind of problematic, *(it appears to choke on uploaded files and certain external links and works much better if I import channel by channel)* but works, but here's another problem:

I have imported a bunch of users. Now I want to give them access. If I forbid them from changing their username by using `Accounts -> Allow Username Change: False` *(which is important for CAS, since the username given by CAS will always be the one on the CAS server, and repeated logins with the same username after it has been changed in RocketChat will create a new user)* my admin user cannot alter their user records at all -- I cannot change anything on them, a message pops up saying "Username change not allowed" even though I just open up the user and press the save button.

So I can't give my users temporary passwords if want to prevent them from being able to change their usernames.

**Comment by dmidmi84** [comment]
+1 
Also can`t change e-mail address for any user. `Accounts -> Allow E-mail Change is set to True.`
Version 0.20.0

**Comment by corecache** [comment]
First off, the usernames are coming straight from the CAS server, in CAS 1.0 those are the primary key upon which to identify users - RocketChat basically has no authority over usernames coming from the CAS service.

If one changes the username in RocketChat, there is no other way of identifying that specific user for future logins and sessions, at least not with CAS 1.0 - because that is like altering a reference/pointer/foreign-key to a specific user outside the authority of RocketChat.

1) Why would you actually want to change the usernames?
2) Why don't you use the Display Name / Profile of the users?

Speaking for CAS 2.0 it would be possible to import more attributes from the CAS service, such as email, Common Name, DIsplay Name etc... would that solve your issue?

**Comment by corecache** [comment]
I gave this another thought, for internals:

Instead of using Meteor.user.username to identify with the user attributes coming from the CAS service, one should use Meteor.user.services.<cas-N-service-id>.user_id.attributes[] to propagate on user creation and for login lookups.

**Comment by Mihara** [comment]
If I *just* set 'allow username change' to 'false', the admin is unable to alter any of the user's *other* attributes, including email, no matter how they registered. Which has to be a bug. :)

The CAS requirement to keep usernames straight is just what caused me to trip over it. That said, in our particular case, usernames that CAS returns are unfit for human consumption. I.e. they're primarily autogenerated uuids of the `00cb-jc0Y-1pVG-VBcQ-hFl5-9g` kind. So storing this internally and using it to identify the user when logging in through CAS, and permitting them to change their username-as-per-RocketChat to whatever they wish to see would solve the CAS problem well. _(I don't see an option to make RocketChat show anything *other* than a username in actual chat)_ Ability to parse CAS extended attributes as per CAS 2.0 to also fill the name would be preferable, of course, because then I could conceivably generate a decent visible username for them...

**Comment by engelgabriel** [comment]
@marceloschmidt can you fix this part?
>If I just set 'allow username change' to 'false', the admin is unable to alter any of the user's other attributes, including email, no matter how they registered. Which has to be a bug. :)

**Comment by engelgabriel** [comment]
@Mihara do you see any errors on your logs?

**Comment by marceloschmidt** [comment]
@Mihara I'm not using CAS, but when I set 'allow username change' to 'false', my admin user may change other users' details. So I'm not sure the "no matter how they registered" is 100% true. Can you provide some steps to reproduce? Thanks.

**Comment by Mihara** [comment]
@marceloschmidt 

I tried this on users from other sources and this is what I get when 'allow username change' is set to 'false':

* Users imported from Slack get "Username change not allowed" message in a pop-up and no log message, even though I'm not trying to change their username at all, no matter which attribute I'm trying to alter.
* Trying to set an email on a user registered from CAS, who had a username and no other attributes, produced the following internal server error message: `I20160304-17:14:57.599(0) Exception while invoking method 'insertOrUpdateUser' ReferenceError: username is not defined     at [object Object].Meteor.methods.insertOrUpdateUser (packages/rocketchat_lib/server/methods/insertOrUpdateUser.coffee:29:50)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)     at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13) `
* Trying to add a email to a user who was created as part of live chat gives me a 'username change not allowed' message and nothing in the logs.
* Trying to alter email or name of a user who was registered through the secret registration link gives me a 'username change not allowed' message and nothing in the logs.

It is possible that steps to reproduce include importing a Slack dump, but at the moment I don't have the time to set up a clean experiment.

**Comment by marceloschmidt** [comment]
Thank you @Mihara I'll follow up on this and try to make a few more tests, maybe importing a sample from slack.

**Comment by corecache** [comment]
Added a PR which resolves this issue *partially* at least for the identification via CAS sso part.
The CAS plugin no longer relies on the internal rocketchat username, but instead creates its own key to identify external users with.

**Comment by corecache** [comment]
@Mihara Feedback wanted - did the fix solve your problem?

**Comment by Mihara** [comment]
@corecache Missed that there's a new release, sorry about that.

Rolling out the new release created a new problem:

```
~ $ docker logs rocketchat 

/app/bundle/programs/server/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
[object Object]
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /app/bundle/programs/server/packages/accounts-base.js:1814:4
```

It just won't start now, this repeats every time. I'm not sufficiently versed in either mongo or nodejs to understand what's going on and how could I fix it. It's not that I couldn't drop the test db and start again, but I'd hate for this sort of thing to happen in production, so I'll hold back in case it's possible to extract any extra information from that.

**Comment by engelgabriel** [comment]
Hi, can you get the full log file? Looks like the Rocket.Chat instance cannot connect to the MongoDB server at all.

**Comment by engelgabriel** [comment]
@Mihara it may be related to this https://github.com/RocketChat/Rocket.Chat/issues/1472

**Comment by Mihara** [comment]
@engelgabriel That, unfortunately, *is* all of the log file, there's nothing else. Mongo insists it is up: `2016-03-10T10:26:54.378+0000 I NETWORK  [initandlisten] waiting for connections on port 27017`

I've just did this to update Rocket:
```
docker pull rocket.chat
docker stop rocketchat
docker rm rocketchat
docker run --name rocketchat --link db -d rocket.chat
docker logs -f rocketchat
```

The log output cited above is literally all the log output I get before it dies. Unless Rocket Chat official image defines any data storage now, which I think it doesn't, it should work exactly the same as it did, right? The same sequence worked to update from 0.19 to 0.20.
