### ISSUE TITLE
Cannot view room/channel in firefox

### ISSUE THREAD

**Issue by japrogramer** [RocketChat/Rocket.Chat#24159]
### Description:

only in firefox can we not see the room

Uncaught DOMException: An invalid or illegal string was specified fireGlobalEvent.ts:17:3
    fireGlobalEvent fireGlobalEvent.ts:17
    _compute tracker.js:308
    Computation tracker.js:206
    autorun tracker.js:576
    fireGlobalEvent fireGlobalEvent.ts:8
    module startup.ts:27
    maybeReady meteor.js:938
    loadingCompleted meteor.js:950
    (Async: EventListener.handleEvent)
    <anonymous> meteor.js:965
    <anonymous> meteor.js:1004
    <anonymous> meteor.js:1360

Exception in template helper: fireGlobalEvent

### Steps to reproduce:

use firefox

### Actual behavior:
![image](https://user-images.githubusercontent.com/1387859/149272710-4d3cf83b-2591-47e6-81b0-ef2d47e3b2fc.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  4.1.0
- Operating System: linux
- NodeJS Version: 4.17.6

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
