### ISSUE TITLE
Editing settings is not allowed

### ISSUE THREAD

**Issue by Alirezamn93** [RocketChat/Rocket.Chat#24152]
Hi, 
on step 2 (Organization Info) I get this error log
`Jan 12 11:10:13 xp0.ir rocketchat-server.rocketchat-server[949]: {"level":50,"time":"2022-01-12T10:10:13.048Z","pid":949,"hostname":"","name":"System","msg":"Exception while invoking method saveSettings 'Editing settings is not allowed [error-action-not-allowed]'"}`
what's wrong?
my server is Ubuntu 20.4 and I installed Rocket.Chat using snap.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
