### ISSUE TITLE
UI broken in Safari 15.2

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#24167]
### Description:

As well as Firefox ESR mentioned in issue https://github.com/RocketChat/Rocket.Chat/issues/24062 fixed in RC 4.3.1, also the latest Apple Safari 15.2 browser fails immediately after logging into RC.

### Steps to reproduce:

1. Log into Rocket.Chat with a clean Safari browser session
2. After the login, the screen turns black

### Expected behavior:

All elements of the page are visible and operate normally.

### Actual behavior:

None of the elements on the screen are visible apart from the default background color.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2

### Client Setup Information

Web client on the latest Apple Safari 15.2 browser. The latest version of macOS Monterey.

**Comment by Gummikavalier** [comment]
Pings to @debdutdeb and @tassoevan :)

**Comment by lovekyleman** [comment]
Here the same, black screen after logging in. But turn E2E off, everything is back to normal

**Comment by serviceman** [comment]
I have the same issue, it doesn't matter if E2E is on or not, just a black screen.

**Comment by IT-Hebk** [comment]
We also have the same issue.

**Comment by dougfabris** [comment]
Hey guys! We're aware of the issue and we're already working on that! Thanks for sharing

**Comment by pablozandona** [comment]
We also have the same issue on Chrome 96.0.4664.110.

<img width="999" alt="Screen Shot 2022-01-17 at 14 36 40" src="https://user-images.githubusercontent.com/5611322/149815732-f284a178-dcff-456a-a9ae-8f58ba428800.png">

**Comment by lovekyleman** [comment]
And we also have the black screen issue on Rocket.Chat app
