### ISSUE TITLE
Don't check for social network avatar when they are disabled.

### ISSUE THREAD

**Issue by dmidmi84** [RocketChat/Rocket.Chat#2417]
Your Rocket.Chat version: (0.20.0)
I'm going to `My account-> Change Avatar`  and there is `"Loading suggestions..."` showing forever.
If I'm uploading my picture as an avatar and it takes to long to be changed. 
At that moment I can't switch to chat rooms back, just shows rocketchat gif.

![image](https://cloud.githubusercontent.com/assets/16577937/13498438/a416dfa8-e162-11e5-89d6-5d81ba6f0fd9.png)

**Comment by engelgabriel** [comment]
Where is your system configured to store the avatars? GridFS or LocalFS?

**Comment by engelgabriel** [comment]
Can you take a screenshot of your browser console?

**Comment by dmidmi84** [comment]
Hi! Sorry for delayed answer! System is configured to GridFS (but I`ve tryed both, nothing has changed). 
![image](https://cloud.githubusercontent.com/assets/16577937/13674843/bf87a972-e6e7-11e5-94d4-9b9c10db0938.png) 
Just have upgraded to 0.21.0 version and the problem is the same..

**Comment by engelgabriel** [comment]
Are you using SSL? Can  you get a screenshot of your network tab?

**Comment by dmidmi84** [comment]
Hi! After  approx 1min of waiting when "Loading suggestions..." is showing it dissapears, then in dev console I see -> 
![image](https://cloud.githubusercontent.com/assets/16577937/13804814/ab5d60fc-eb58-11e5-8866-fb00a6c4e098.png) It`s like it tries to check for avatars on those accounts, even they are disabled? And those links are closed in our network :-) So after "Loading suggestions..." dissapears I can change my avatar quickly.

**Comment by rodrigok** [comment]
@dmidmi84 No, we don't get suggestions for disabled services but we always try to get suggestion from gravatar, the problem is that this method to get suggestions is blocking all other methods until finish, I fixed that in the PR #2596
