### ISSUE TITLE
Reset section button does not disable the Save button in settings of Administration panel.

### ISSUE THREAD

**Issue by try-catch-stack** [RocketChat/Rocket.Chat#24189]
### Description:

The  settings in the administration panel (Accounts, Analytics etc.) have a 'Reset section to Default' button which appears if we have some unsaved changes in a section. This button is supposed to reset all the settings in that given section to the default ones and should also disable the save and cancel buttons on the top right if there are no unsaved changes left in any section (After resetting) . But it does not happen to disable these buttons and the Save button can still be pressed even without any changes in the settings. 
The individual reset button on each setting works fine tho and does disable these buttons .

### Steps to reproduce:

1. Go to any of the settings present in the Administration panel.
2. Change some settings in a section and click on the 'Reset section to default' button on the bottom of that section.
3. The settings will be set to the default ones but the Save and Cancel buttons can still be clicked.

### Expected behavior:

The Cancel button should disappear and the Save button should be disabled just the way individual reset button on the right of each setting works.

### Actual behavior:

Cancel and Save buttons can still be clicked.

https://user-images.githubusercontent.com/77742477/149670966-32f44890-9e77-4a9b-82f6-7f3521622cfd.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
