### ISSUE TITLE
[BUG]: Broken link in search 

### ISSUE THREAD

**Issue by himanshumalviya15** [RocketChat/Rocket.Chat#24198]
The link in "Search Messages" open to a not found page.

### Description:

When click on search message icon and search for a link then after when we click on the searched linked it redirect to not found page.

### Steps to reproduce:

1. Click on "Search Messages" box in chat.
2. Find some link in chat.
3. Click to open the highlighted link.

### Expected behavior:

https://user-images.githubusercontent.com/76220055/149798969-95100975-38d0-4040-a45b-037166f3392a.mp4

### Server Setup Information:

Version of Rocket.Chat Server: 4.2.0-develop
Operating System: Ubuntu 20.04

### Client Setup Information

Desktop App or Browser Version: Browser
Operating System: Linux

### Related Issues

#18770 
#23285

### Additional context

No

**Comment by Jaiharishan** [comment]
I will work on this issue and fix the bug.
