### ISSUE TITLE
Pinning Messages prints the message without formatting

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2420]
Your Rocket.Chat version: 0.20
A picture is worth a thousand words.
![screen shot 2016-03-03 at 12 49 58 pm](https://cloud.githubusercontent.com/assets/2439803/13509064/8ade8ac8-e13e-11e5-81da-726caf052b3e.png)
As you can see the message should be quoted but is not.

**Comment by engelgabriel** [comment]
Expected recursion...

![image](https://cloud.githubusercontent.com/assets/1000217/13511919/3912b2b8-e176-11e5-967d-01036d7f4a24.png)

**Comment by royalaid** [comment]
To follow this up it also appears that attachments or url unfurls are not included

**Comment by sampaiodiego** [comment]
closed by 0d5d13c839818b209245d1217dc4ac840f45cb61

![image](https://cloud.githubusercontent.com/assets/8591547/13750827/e2f42254-e9e5-11e5-8dca-bf4086592f06.png)
