### ISSUE TITLE
Custom fields not visible in api/v1/users.list

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#24208]
### Description:

My "custom fields", which are also visible via the GUI, are not displayed using the API.

### Steps to reproduce:

1. Create a custom field
2. Sync custom field via LDAP (or manual if no EE)
3. GET ...api/v1/users.list

### Expected behavior:

```
{
  "users": [
    {
      "_id": "kcs9AtdDcvcDScc4df",
      "username": "tars21",
      "customField1": "value",
      "emails": [
      ...
```

### Actual behavior:

```
{
  "users": [
    {
      "_id": "kcs9AtdDcvcDScc4df",
      "username": "tars21",
      "emails": [
      ...
```

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.2
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.22.9
- MongoDB Version: 4.2.18

### Additional context

I've tried all query parameters from here:
https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/users-endpoints/get-users-list

Should this possibly not be possible in general? Is there any other method to access all users and their custom fields via the API?

Thank you in advance!

**Comment by tmkis2** [comment]
We are on the latest 6.2.x Version but still don't get custom fields in users.list - does this really work?
