### ISSUE TITLE
custom OAuth2 doesn't work for Auth0

### ISSUE THREAD

**Issue by jeffreywescott** [RocketChat/Rocket.Chat#2421]
Your Rocket.Chat version: `develop` branch

Hi, I was trying to add a custom OAuth2 implementation backed by [Auth0](https://auth0.com/), but it doesn't work for two reasons:

1. `oAuthServicesUpdate` doesn't support numeric characters in the provider name.
2. `custom_oauth_server` expects `id` or `ID` in the serviceData, but Auth0 only provides `user_id`.

PR on the way!

**Comment by mautematico** [comment]
Hola @jeffreywescott 
are you able to write an example on this, or to point me on the right direction?

I am half way there, if I understand correctly this Auth0 mini howto:
https://auth0.com/authenticate/slack/wordpress (of course, replacing slack with rocket.chat and wordpress with whatever I have on my side).

¡Gracias!
