### ISSUE TITLE
Add button disabled realeases 4.3.2

### ISSUE THREAD

**Issue by karlos-silva2** [RocketChat/Rocket.Chat#24228]
Good Morning

Add files button stopped working in realeses 4.3.2

![image](https://user-images.githubusercontent.com/85645175/150341842-7946db79-6f16-4afa-9ee0-675550b2f653.png)

I have to enable something from that version?

Thank you, I await return

**Comment by Jaiharishan** [comment]
It works in version 4.4.0, try that one

**Comment by himpierre** [comment]
Works for me with 4.3.2.

**Comment by Jaiharishan** [comment]
Yep, it works in the latest version.

**Comment by karlos-silva2** [comment]
resolvido na versão 4.3.2
