### ISSUE TITLE
[Feature] Change Omnichannel Icon

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#24229]
### Description:

It appears that we are unable to customize the Omnichannel icon.  Options exist to change other icons inside Rocket Chat.  But there appears to not be an option to change the live chat icon.  The icon I'm referring to is:
 
![image](https://user-images.githubusercontent.com/6833993/150365175-40c92fb9-4e62-4211-ab56-99286585f56b.png)

### Steps to reproduce:

1. Go to Administration -> Omnichannel
2. Look through settings
3. Don't see any options for changing this icon.

### Expected behavior:

I would hope to see an option to upload a different icon.

### Actual behavior:

Don't see an such option.  If I'm missing something obvious, I apologize.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.17

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Linux

**Comment by AlecKinnear** [comment]
I cannot believe that RocketChat thinks it's a good idea to make it difficult/impossible for publishers to change the Omnichannel icon. Publishers depend on live chat (Omnichannel) to engage visitors not market RocketChat.

**Comment by AlecKinnear** [comment]
Wow, we have to resort to nginx hacks to change the Omnichannel icon. Welcome to the wonderful world of corporate FOSS.

**Comment by MartinSchoeler** [comment]
Added in https://github.com/RocketChat/Rocket.Chat/pull/31820
