### ISSUE TITLE
[BUG] No Errors for Invalid Name or Password on Setup Wizard

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/Rocket.Chat#24238]
### Description: 

Whenever we setup a Rocket.Chat server, we have to go through a setup wizard. While filling the Admin info form in setup wizard we are not able to submit the form if the Name and Password fields are empty, but there is no message showing us that an empty Name or Password is Invalid.

### Steps to reproduce:

1. Start a new Rocket.Chat server and enter the setup wizard.
2.  Fill User Name and Password. 
3. Click On Continue

### Expected behavior:

1. There should be an error message below the message name input field indicating that an empty name is invalid.
2. There should be a error message below the password field for invalid or weak passwords.

![image](https://user-images.githubusercontent.com/70485812/150405158-e36896ea-0b68-435a-b683-fbbfd4f1d0a9.png)

### Actual behavior:

1.  No error message is shown below empty Name and Password field, user is given no indication why they are not able to submit the form.

![error_in_rocket_chat](https://user-images.githubusercontent.com/70485812/150404771-9e56653e-c8e6-49d5-aaa5-1f3667c5e45b.JPG)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0-develop 
- Operating System: Ubuntu (Using Gitpod)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.18.2 - x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Browser Version 97.0.4692.71
- Operating System: Windows 10

**Comment by Ayush01729** [comment]
Hello @samad-yar-khan, I am Ayush and I am currently working on this issue.
