### ISSUE TITLE
Adding Oauth and registering a user with an email that already exsists hijacks that user

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2424]
Your Rocket.Chat version: 0.20
I recently enabled oauth and wanted to link my google login to RC, it turns out that registering with Oauth seems to have made my only admin account unaccessable because using a login with a correct password does not login and resetting the password via email only resets the new regular user account.

**Comment by engelgabriel** [comment]
Can you look ad the users collection and check if there is 1 or 2 users?

**Comment by royalaid** [comment]
It appears when searching via sending a DM that there is only the new user. Is there another way to search?

**Comment by engelgabriel** [comment]
If the ADMIN user did not verify his email, yes, the new user will have deleted the previews one. This is the expected behaviour, but we should give a confirmation button first.

https://github.com/RocketChat/Rocket.Chat/issues/2055

**Comment by engelgabriel** [comment]
If you restart your RC server.. the oldest user will me made admin in case you dont have any other admins.

**Comment by royalaid** [comment]
Is there a way to merge users?

**Comment by engelgabriel** [comment]
Not manually, but if a user has a verified email, and logs in using oAuth with the same verified email, they will be merged.

**Comment by royalaid** [comment]
Okay, I think my admin account never had a verified email so I am guess that account is just kinda stuck in limbo until/if user merging is made?

**Comment by engelgabriel** [comment]
The old account was deleted.

**Comment by royalaid** [comment]
:cry: Okay, I am guessing there isn't a way to unify the messages by that user and this new one then similar to the request in #2311?

**Comment by engelgabriel** [comment]
Let me do some teste. @marceloschmidt do we really delete the original user or do we just remove the email form that account?

**Comment by marceloschmidt** [comment]
Duplicate of #2055

**Comment by marceloschmidt** [comment]
Yes, the account is deleted. I'm working on it right now, please follow up on issue #2055
