### ISSUE TITLE
rockect.chat 4.0.5 - Error: EHOSTDOWN: host is down, open '/app/uploads/4kEEbDMfrNvAg3Mp3' [ufs: cannot upload file] FECHAR

### ISSUE THREAD

**Issue by karlos-silva2** [RocketChat/Rocket.Chat#24251]
### Description:

I have this error below when sending a file through chat: Error: EHOSTDOWN: host is down, open '/app/uploads/4kEEbDMfrNvAg3Mp3' [ufs: cannot upload file] FECHAR

![Uploading image.png…]()

Rocket.Chat Version: 4.0.5                                   |
NodeJS Version: 12.22.1 - x64                           |
MongoDB Version: 3.6.12                                  |
Platform: linux                                   |
Process Port: 3000                                    |
ReplicaSet OpLog: Enabled                                 |
Commit Hash: 4e8ba1542d                              |
Commit Branch: HEAD

**Comment by dudanogueira** [comment]
related:
https://github.com/RocketChat/Rocket.Chat/issues/24258
