### ISSUE TITLE
confused of the room owners role scope

### ISSUE THREAD

**Issue by javaning** [RocketChat/Rocket.Chat#2425]
Your (or my) Rocket.Chat version: (0.20.0)

here why are moderator&owner scope assigned "Subscriptions" ?

> 		{ name: 'moderator', scope: 'Subscriptions', description: 'Room moderators' }
> 		{ name: 'owner', scope: 'Subscriptions', description: 'Room owners' }

can anyone explain and tell me why? thanks

**Comment by engelgabriel** [comment]
Hi, scope tells the system on what data model the information should be stored. Since the Subscription object is what controls the relationship of each User to a Room, we decided to store their roles there.
