### ISSUE TITLE
[BUG] Blank Report Message Sent

### ISSUE THREAD

**Issue by nishant23122000** [RocketChat/Rocket.Chat#24261]
### Description:
 There should be something written inside the report box before sending the report.

### Steps to reproduce:

1. Go to any Channel
2. Pick up any message and report them
3. **Report This message** pop up will open
4. If we add just a spacebar, It gives permission to send a report without any text.

### Expected behavior:

There should be at least something written before sending the report message.

### Actual behavior:

It detects the spacebar as a written text and gives permission to send the report blank.

https://user-images.githubusercontent.com/53515714/150627000-c50c9515-091b-47e8-9461-02c3179e17d7.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:  4.4.0
- Operating System: Windows 10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Biki-das** [comment]
@nishant23122000  hey buddy , could you help me to guide on how do i set up the rocket chat web version

**Comment by nishant23122000** [comment]
@Biki-das  Yes, ping message here: https://open.rocket.chat/home

**Comment by debdutdeb** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/24262
