### ISSUE TITLE
Custom processing script for integration webhooks

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2426]
Allow users to add custom scripts that for the following steps of the webhooks:

- Prepare Outgoing Requests
- Process Outgoing Requests Responses
- Process Incoming Payloads

**Comment by pavankumarkatakam** [comment]
Wanna check out this.

**Comment by engelgabriel** [comment]
Please see initial documentation at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub

**Comment by hkuich** [comment]
@engelgabriel: This is probably obvious to everybody else, but where can I actually add the custom scripts/the ones that you have kindly supplied at https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---GitHub? There is no field in the GUI for doing this in the version I am using (I am using version: 0.19.0 from Feb 22 2016). Any help would be appreciated!

**Comment by sampaiodiego** [comment]
@hkuich this GUI was added by #2432 3 days ago in the `develop` branch.
it will be officially relased next week in the 0.22 version

**Comment by hkuich** [comment]
will wait on the 0.22 release then. thanks for the quick reply...
