### ISSUE TITLE
[Bug] All apps are disabled after restart of instance with highest value of Active Handlers in muti-instance deployment

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#24260]
### Description:

That issue is really critical for us, because we are using one Rocket.Chat application that must be enabled all the time.
Since version 4.1.0 Rocket.Chat performance is much better and RAM memory leak is smaller then before, but still exist.
In previous versions we used to restart all our instances every night (check this for more info https://github.com/RocketChat/Rocket.Chat/issues/22886 
https://github.com/RocketChat/Rocket.Chat/issues/17473#issuecomment-636642842)
But on version 4.3.1 I guess a weekly restart would be enough. 
But whole deployment restart leads to new bug in 4.3.1 - all installed and enabled applications become disabled!
That is a really critical for us.

Ping @d-gubert because this is important App-Engine issue

### Steps to reproduce:

1. Install and enable few apps
2. Restart all RC instances one-by-one
3. Check apps state - they all disabled

### Expected behavior:

Apps remain enabled on instances restart

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/150626469-5bc32a71-c500-4479-a13a-9fea47434e70.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.1
- Operating System: OL8
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.8
- MongoDB Version: 4.411

### Client Setup Information

- Desktop App or Browser Version: 3.7.6
- Operating System: Windows 10

**Comment by debdutdeb** [comment]
Just for public knowledge, this is known internally, and team's working on a fix at the moment.

**Comment by ankar84** [comment]
Looks like restart of one single instance lead to disable of all apps
And that instance is same as [looks overloaded in Metrics](https://github.com/RocketChat/Rocket.Chat/issues/22254)
![image](https://user-images.githubusercontent.com/4023037/150705042-4ae55903-28c0-41bc-8a33-ffccc1f68a2f.png)

**Comment by ankar84** [comment]
So my guess is that among all instances there is only one that handles RC applications management. And after that instance is restarted - all apps are become disabled.

**Comment by geekgonecrazy** [comment]
I believe no dedicated one manages the apps state. But something happened causing I'm guessing the apps to crash which caused them to be disabled. 

The event was probably then propagated to the other instances which then also stopped them

**Comment by ankar84** [comment]
Update. Recently we added more CPUs to our mongodb server and after that I didn't see that issue, all restart process goes without any issues, like is was before of 3.18.x versions.
So, maybe the reason if that issue is related to database performance?

**Comment by ankar84** [comment]
Actually I'm on recent 4.6.2 now and after upgrade resources to mongodb I don't see that issue.
So, I'm closing that.
