### ISSUE TITLE
User can direct message himself/herself.

### ISSUE THREAD

**Issue by Ayush01729** [RocketChat/Rocket.Chat#24270]
### Description:

A user should be able to direct message others, but he/she is able to direct message himself.

### Steps to reproduce:

1. Send a message
2. Click on three dots on extreme RHS of your message.
3. There will be an option to DM yourself.

### Expected behavior:

When I send a message, others can DM me replying to it, but I shouldn't be able to DM myself.

### Actual behavior:

When I am sending a message, others as well as I myself can reply to it.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:Microsoft Edge Version 97.0.1072.55 / Google Chrome Version 97.0.4692.71
- Operating System:Windows 10

### Additional context
![issue](https://user-images.githubusercontent.com/76625106/150788690-b977145a-4a2a-4a81-9c84-4407e45b2f57.PNG)

**Comment by Himanshu664** [comment]
I think this feature is needed to store things in our dm.

**Comment by debdutdeb** [comment]
This is a feature, not a bug. See Admin > Message > "Allow user direct message to yourself".
