### ISSUE TITLE
[BUG]: video player shows incorrect details

### ISSUE THREAD

**Issue by Jaiharishan** [RocketChat/Rocket.Chat#24271]
### Description:

 When a video is uploaded and viewed the player shows incorrect timings 

### Steps to reproduce:

1. Go to any channel or teams
2. Send a Video Message from your side.
3. Play the video you sent.

### Expected behavior:

Player to show actual video timings 

### Actual behavior:

Player shows incorrect timings

https://user-images.githubusercontent.com/78893503/150909851-d56dccef-062e-451b-a7ce-279aa8807243.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Windows 10
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.4
-MongoDB Engine: wiredTiger

### Client Setup Information:

- Desktop App or Browser Version: 3.7.6
- Operating System: Windows 10

### Relevant logs:
No relevant logs to mention.

**Comment by samad-yar-khan** [comment]
Hey @Jaiharishan, I tried following the instructed steps but I am not able to replicate the issue. Can you please upload a screenshot or a screen recording ?

**Comment by Jaiharishan** [comment]
Yeah I will upload one
