### ISSUE TITLE
Images in Rocket.Chat/public/images/logo fail to load

### ISSUE THREAD

**Issue by agentirons** [RocketChat/Rocket.Chat#2428]
When editing the Side Navigation Footer html code under the Layout menu, setting the src attribute as "src=/public/images/logo/_somefile_.png" only works if the image was a part of the default installation. Newly added image files, even with the same permissions, result in a broken image icon.

I can directly access any of the default images in a browser pointed to localhost:3000/images/logo/_image_.png, but attempting to access a file that I've copied to that folder gives me a blue loading screen.

**Comment by engelgabriel** [comment]
During development, using `meteor run` you can edit the files of the /public/ from the cloned repo directly, but you cannot edit files of compiled bundle, you have to use `meteor build` from source again.
