### ISSUE TITLE
[BUG]: Copying the message in quote doesn't work correctly

### ISSUE THREAD

**Issue by Jaiharishan** [RocketChat/Rocket.Chat#24287]
### Description:

When tried to copy a message in quote it gives incorrect response.

### Steps to reproduce:

 1. Quote an message in any team or channel.
 2. Use the copy option and copy the quote message.
 3. Paste the copied message and see the error.

### Expected behavior:

To give the exact copied message.

### Actual behavior:

Gives an incorrect response.

https://user-images.githubusercontent.com/78893503/151015066-bff0f2be-eb84-469b-aeee-7f5c9c6af5ea.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Windows 10
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.4
- MongoDB Engine: wiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.7.6
- Operating System: Windows 10

### Relevant logs:
No relevent logs to mention.

**Comment by geekgonecrazy** [comment]
This is exactly the intended behavior.  Copy copies the message exactly.  If you hit enter the result is the exact same as the one you hit copy on.

The url hit you see there is how quoted messages currently work.  If you hit edit on a message with a quote you will see this same thing

**Comment by Jaiharishan** [comment]
Yeah, now I got it. Thank you for letting me know this!
