### ISSUE TITLE
Automate Continuous Integration with Travis

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#243]
https://travis-ci.org/

**Comment by Sing-Li** [comment]
Please push our version tagged builds to MaxCDN  - https://www.maxcdn.com/open-source/    

They should be open-source friendly - and truly edge'd worldwide.

**Comment by rodrigok** [comment]
Travis activated, testing only the build process to prevent errors like this https://github.com/RocketChat/Rocket.Chat/commit/e4848046368d9c60a2273e6b0d4409e609cc818e


https://travis-ci.org/RocketChat/Rocket.Chat/
