### ISSUE TITLE
[BUG]: Copying a discussion message gives 'undefined'

### ISSUE THREAD

**Issue by Jaiharishan** [RocketChat/Rocket.Chat#24313]
### Description:
  When tried to copy a message from the discussion it returns undefined.

### Steps to reproduce:

1. Create a discussion for any message in a channel or team.
2. Go to that discussion page and try copying that message
3. Now paste that message you will get undefined as the response.

### Expected behavior:

To give back the actual message.

### Actual behavior:

It gives back undefined

https://user-images.githubusercontent.com/78893503/151406413-41202308-0d6f-413c-9e58-1aae17fa7775.mp4

### Server Setup Information:
- Version of Rocket.Chat Server: 4.4.0
- Operating System: Windows 10
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.4
- MongoDB Engine: wiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.7.6
- Operating System: Windows 10

### Relevant logs:
No relevant logs to mention.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
