### ISSUE TITLE
How to configure nginx to access rocket chat on a subfolder/location?

### ISSUE THREAD

**Issue by b-rodrigues** [RocketChat/Rocket.Chat#24332]
### Description:

Cannot get rocket chat to load on a url such as: https://mydomain.com/chat/

### Steps to reproduce:

My nginx configuration file looks like this:

```
upstream backend {
    server mydomain.com:3000;
}

server{
  listen 443 ssl;
....
...
...

 location /rocketchat/ {
       proxy_pass http://backend;
       proxy_redirect off;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;

   }
}
```

### Expected behavior:

Going on https://mydomain.com/rocketchat should show the website.

### Actual behavior:

But I see the three dots loading indefinitely. Changing the configuration to

```
location / {
...
```

instead of what I have

```
location /rocketchat/ {
...
```
works when I go to mydomain.com.

What may be going on, is that when I go to mydomain.com, I get redirected to mydomain.com/home, and I guess there's some redirection issues. I have followed every guide and read every thread on this, tried everything I've found, with no success.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.2
- Operating System: ubuntu 20.04 
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: no idea, where do I find this?
- NodeJS Version: v12.22.7
- MongoDB Version:3.6.23 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Brave 
- Operating System: opensuse tumbleweed

### Additional context

The server is accessible via http://mydomain.com:3000

**Comment by dudanogueira** [comment]
Hi! Please checkout this at our forums:
https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371/29

Closing for now, as this is not an Issue.
