### ISSUE TITLE
Directly linked channel does not load for newly created user

### ISSUE THREAD

**Issue by garg** [RocketChat/Rocket.Chat#2433]
Your Rocket.Chat version: 0.20.0 (current master branch as of 5th March 2016)

1. With admin user, create a new channel called 'channel2' (or whatever)
2. Take the URL of the new channel and open it from a different browser (or logout and clear cache) eg.
http://localhost:3000/channel/channel2
3. Create new user while on this URL. This is like giving a link to your channel to a friend, and the friend tries to create an account and login
4. Account is created successfully, but the channel never loads. I have seen either the following graphic, or a blue background. It never loads. Unless I do an actual browser refresh.
 
![image](https://cloud.githubusercontent.com/assets/16932/13550224/0f9564a4-e2e7-11e5-8df0-af125806552e.png)

**Comment by rodrigok** [comment]
Can you open your developer console and send us a print screen when this error happens?

**Comment by geekgonecrazy** [comment]
I replicated on the demo server. Doesn't have to be a new channel.  Just any channel that the user isn't already a member of.  No errors in the developer console.  If you refresh it loads just fine.

![image](https://cloud.githubusercontent.com/assets/51996/13690281/c65c039e-e6f4-11e5-97f0-1ce50a913540.png)
