### ISSUE TITLE
Display icons for uploaded file attachments

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#2434]
Your Rocket.Chat version: 20
Display standard file-type icons for uploaded files in Rocket.Chat - eg: .pdf, .doc, .xls, .ics etc?

Could be configurable via the file upload admin commands, where each permitted file type could have a default icon or a configurable icon?

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
