### ISSUE TITLE
New Relic failed to open log file /app/bundle/programs/server/newrelic_agent.log - Rocketchat 4.2.0 

### ISSUE THREAD

**Issue by thangs6** [RocketChat/Rocket.Chat#24356]
Hello everyone,
When i try to deploy rocketchat  in kubectl getting permission issue 

New Relic failed to open log file /app/bundle/programs/server/newrelic_agent.log
{ Error: EACCES: permission denied, open '/app/bundle/programs/server/newrelic_agent.log'
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/app/bundle/programs/server/newrelic_agent.log' }
/app/bundle/programs/server/node_modules/fibers/future.js:313
throw(ex);

I installed ROcketchat in a kubernetes.
Rocket.Chat 4.2.0
Mongo DB . 4.0 
file sharing system : Filesystem

**Comment by geekgonecrazy** [comment]
Closing due to no references to this package even existing in our code base
