### ISSUE TITLE
docker :latest tag points to 3.18.5

### ISSUE THREAD

**Issue by individual-it** [RocketChat/Rocket.Chat#24353]
### Description:
We had trouble this morning when updating our rocket chat to the newest version, logs showed
`Exception in callback of async function: errorClass [Error]: [Can't find migration version 252]`
after investigating a bit I fount out latest tag on docker points to version 3.18.5

### Steps to reproduce:

1. `docker pull rocketchat/rocket.chat:latest`
2.  `docker inspect rocketchat/rocket.chat:latest`

Or check https://hub.docker.com/r/rocketchat/rocket.chat/tags

### Expected behavior:

:latest pointing to 4.4.0

### Actual behavior:
:latest points to 3.18.5

![grafik](https://user-images.githubusercontent.com/2425577/151733718-fa0321e1-5da6-4f6d-9775-aa8cc8f55486.png)

**Comment by Provoker** [comment]
The same problem after upgrade from 4.3.2

**Comment by ankar84** [comment]
cc @sampaiodiego to fix that

**Comment by sampaiodiego** [comment]
it's fixed now. sry guys.

**Comment by debdutdeb** [comment]
fyi this issue shouldn't repeat itself from now on (https://github.com/RocketChat/Rocket.Chat/pull/24366).
