### ISSUE TITLE
Add additional allowed schemes of link in Custom Links

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#24358]
### Description:

Previously I asked to markdown work in Custom Fields here https://github.com/RocketChat/Rocket.Chat/issues/20005
And @yash-rajpal implemented it in https://github.com/RocketChat/Rocket.Chat/pull/20947 (Thanks, Yash!)

And now at 4.3.1 version I see, that `http` and `https` links works perfect in Custom Links.
But we need other then that two protocols. We need `notes://` protocol for sure. And theoretically some other protocols, like `e1c://`
And now that protocols don't work - click to nothing.

Also worth mention that `Admin UI - Message - Markdown` we have that additional protocols
![image](https://user-images.githubusercontent.com/4023037/151763130-bd959cf6-9a3b-45bf-95e0-e66d27ae266a.png)
But I guess that settings are ignored since new parser https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-1009610000

Enabling old parser don't solve that issue for me.

Also that situation tested on latest 4.4.0 - same issue.

### Steps to reproduce:

1. Add `notes` in `Allowed schemes of Link` in `Admin UI - Message - Markdown`
2. Add notes link in markdown to some Custom Field like `[Link text](notes://link/to/document)`
3. Open User Profile on user with filled Custom Field
4. Click that Custom Field (Link Text)
5. Nothing happens

### Expected behavior:

`notes` (and other) schema works as `http` and `https` schemas.

### Actual behavior:

`notes` schema doesn't work

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 12
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.18.2
- MongoDB Version: 4.2.17

### Client Setup Information

- Desktop App or Browser Version: Chrome 97
- Operating System: Windows 10

### Additional context

It could be a new parser issue or separate issue
@ggazzo please take a look at that issue

**Comment by dudanogueira** [comment]
Thanks!

**Comment by samad-yar-khan** [comment]
@dudanogueira  If no one has been assigned the issue so far, I can try working on this ?

**Comment by sidmohanty11** [comment]
Hi @ankar84 , hope you are great! I tried reproducing this in my dev environment but couldn't seem to reproduce it. As per my debugging goes, I discovered that the schemes are used properly:

As you can see here,

#### settings log
![after_debugging_mdschemes](https://user-images.githubusercontent.com/73601258/152816278-e45734e3-f9b8-4c44-8a19-c1c967faf186.png)

#### message (by using your example)
![after_debugging_mdschemes2](https://user-images.githubusercontent.com/73601258/152816333-11411605-83dc-4b66-a3c1-d82cf427024e.png)

Please check it and let me know.

Thank you

**Comment by sidmohanty11** [comment]
@ankar84 thank you so much for your explanation. I could see that in custom fields of user info, marked is used for markdown preview. Here in this line [client/component/MarkdownText.tsx](https://github.com/RocketChat/Rocket.Chat/blob/6fbd7f1614da4eb109252a3c01028e2b04c7ce6a/client/components/MarkdownText.tsx#L111) dompurify sanitizes any other protocol,
![after_debuggin_mdlink3](https://user-images.githubusercontent.com/73601258/152852005-83484683-ca69-4cbf-b667-79530c9375b5.png)

**Comment by ankar84** [comment]
> Here in this line client/component/MarkdownText.tsx dompurify sanitizes any other protocol

@sidmohanty11 thanks for your investigation!
Can we add additional protocols to sanitise rules?
cc @ggazzo

**Comment by ankar84** [comment]
could be fixed in https://github.com/RocketChat/Rocket.Chat/pull/26697

**Comment by ankar84** [comment]
@dudanogueira @ggazzo hey!
I tested https://github.com/RocketChat/Rocket.Chat/pull/26697 on my side and it works perfect!
![image](https://user-images.githubusercontent.com/4023037/199440409-85525d12-4cae-4b8c-9e35-a32dfbba564a.png)

Can you review that PR, please.

**Comment by gabriellsh** [comment]
Hey @ankar84 ! Thanks for the report. As for the other link schemes, the actual issue is not the scheme itself (eg `e1c` or `notes`), but the URL not having a `.` in the domain. We are actually working on that issue right now.

For the Custom Fields, I think we need a different fix than the one cited. I'll see what we can do.

**Comment by ankar84** [comment]
> Hey @ankar84 ! Thanks for the report. As for the other link schemes, the actual issue is not the scheme itself (eg `e1c` or `notes`), but the URL not having a `.` in the domain. We are actually working on that issue right now.
> 
> For the Custom Fields, I think we need a different fix than the one cited. I'll see what we can do.

Great news @gabriellsh 
Thanks a lot for your attention!!
