### ISSUE TITLE
4.4.0 Jitsi JWT Auhentication broken

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#24351]
### Description:

After upgrading to Rocket.Chat 4.4.0 Jitsi JWT authentication does not work anymore.

### Steps to reproduce:

1. upgrade to 4.4.0 (from 4.3.2)
2. start video call
3. authentication fails

### Expected behavior:

jwt authentication should still work

### Actual behavior:

jitsi asks for login on mobile and denies connection on browser

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: sure
- NodeJS Version: 14.8.1
- MongoDB Version: 4.4.8

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

prosody log.
```
Jan 30 17:31:30 general warn    Error verifying token err:not-allowed, reason:Not acceptable by exp
Jan 30 17:32:47 mod_bosh        info    Client tried to use sid '7b82c183-fec9-4242-9f67-a99b28f2a18e' which we don't know about
```

So I guess the token is not send at all.

**Comment by fdellwing** [comment]
If no token is send, it would say that in the reason. But reason says, that the token is expired. Please double check the datetime on both RC and Jitsi.

**Comment by ankar84** [comment]
I can not confirm that issue
![image](https://user-images.githubusercontent.com/4023037/151771479-ae960e4d-a7bd-4020-b4d8-7f40e86704e2.png)

**Comment by himpierre** [comment]
You guys are right. System time was skrewed. Sorry!

**Comment by himpierre** [comment]
Hello again. :)

Is the "call already ended" problem back again with 4.4.2? I double checked the clocks on the system and there is no difference between them. @ankar84 could you be so nice and confirm or decline the problem? Thanks!

**Comment by ankar84** [comment]
> Hello again. :)
> 
> Is the "call already ended" problem back again with 4.4.2? I double checked the clocks on the system and there is no difference between them. @ankar84 could you be so nice and confirm or decline the problem? Thanks!

If it is so, you need yo start another issue with reproduce steps.

And close that issue

**Comment by himpierre** [comment]
Seems to be a desktop client problem this time.
https://github.com/RocketChat/Rocket.Chat/pull/23904#issuecomment-1047148888
