### ISSUE TITLE
channels.members endpoint returns duplicate members

### ISSUE THREAD

**Issue by try-catch-stack** [RocketChat/Rocket.Chat#24359]
### Description:

`channels.members` endpoint is used to get the list of all members of that channel. More on the endpoint [here](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/members) .
It can be paginated using the parameters `count` and `offset` which are optional .
After testing with multiple channels I can confirm that the response contains duplicate members , i.e. same members are returned multiple times but **only with the rooms that have more members that the `count` parameter which is 50 by default.**

### Steps to reproduce:

1. Fetch members of a channel with more than 50 members (or pass `count` with value less than members of the channel) using `channels.members` and set `offset` to 0.
2. Get the members again but now with `offset` equal to `count` and similarly with multiples of `count` to get other members.
3. You'll notice that some members present in the first response object are also present in the further fetched responses.

Other way to confirm this bug is to open a channel in the mobile app and see its members. You'll see some members are present multiple times. I even created an issue https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3638 in the React Native repo but after exploring a bit , this seems to be an issue with the API (pagination maybe) itself. 

To test on your development environment :
1) Create a channel and add some members say 15.
2) Fetch members of the channel with passing `count` parameter as some number smaller than the number of members say 5 and set `offset` to 0.
3) Now do this for `offset` values 5 and 10 and compare the three responses. You'll notice that some users are present in more than one response.

### Expected behavior

All the responses should contain unique members and together all the responses should consists of all the members of that channel.

### Actual behavior:

Some members of the channel are present in multiple responses and some are not even once.

### Server Setup Information:

- Version of Rocket.Chat Server:  4.4.0-develop
- Operating System: Ubuntu 20.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.2
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
