### ISSUE TITLE
Google OAuth Login broken in 4.4.0

### ISSUE THREAD

**Issue by mr-karan** [RocketChat/Rocket.Chat#24355]
### Description:

After upgrading to 4.4.0, Google OAuth complains about `redirect_uri` mismatch. Nothing has changed in the config, only upgraded from 4.3.0 to 4.4.0 caused this.

### Steps to reproduce:

1. Login using Google OAuth
2. See the error message

```
Error 400: redirect_uri_mismatch

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
```

### Expected behavior:

Google OAuth should work normally as it was working a version before.

### Actual behavior:

![image](https://user-images.githubusercontent.com/5689132/151740677-7061e16d-9dd5-4617-bf74-3d0100d86bea.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Doesn't matter
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Dont know where to find this
- NodeJS Version: v14.18.2
- MongoDB Version: 4.2.18 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: `Chrome Version 97.0.4692.99 (Official Build) Arch Linux (64-bit)`
- Operating System: Arch Linux

### Additional context

The OAuth URL is correct and unchanged in the settings:

![image](https://user-images.githubusercontent.com/5689132/151740858-a0f14f3a-a6fa-40de-acf3-fc9e57fbd39a.png)

### Relevant logs:

-

**Comment by mr-karan** [comment]
For people coming here, 
I'd `?close` in the `redirect_uri` in Google Console but it was missing from here. Did this `redirect_uri` change across versions? (removal of `?close` i.e.)

**Comment by geekgonecrazy** [comment]
@sampaiodiego we might need to call this out as a breaking change or at least a note?

**Comment by danielfariati** [comment]
Don't know if related to this, but now in version 4.4.1, everyone trying to login with Google is getting an "Internal Server Error".
The problem is exactly the same as described here: https://github.com/RocketChat/Rocket.Chat/issues/19856

**Comment by sampaiodiego** [comment]
@danielfariati did you end up removing `?close` from callback url on Google as @[mr-karan](https://github.com/mr-karan) mentioned? if so, you should add it back

**Comment by danielfariati** [comment]
No. We actually have both there.

Google:
Javascript origins: https://[our-domain]
Redirect URIs: https://[our-domain]/_oauth/google?close AND https://[our-domain]/_oauth/google

RocketChat:
ROOT_URL=https://[our-domain]

In can see in the settings that  Accounts_OAuth_Google_callback_url is https://[our-domain]/_oauth/google (without the ?close). But that is not customizable and I assume is the server default.

**Comment by danielfariati** [comment]
@sampaiodiego 
I believe the cause of the problem is the variable defined here: https://github.com/RocketChat/Rocket.Chat/blob/7632f12cfcc7ed8ee8f843587fdff63b101cc765/app/lib/server/startup/settings.ts#L672
As you can see, the URL is defined without the `?close`. Admins also can't change that, as it is readonly.

**Comment by jthomaschewski** [comment]
@danielfariati good idea.
Manually changing the value in DB doesnt help though. temporarily tried it by running this:

```js
db.rocketchat_settings.update({
  _id: 'Accounts_OAuth_Google_callback_url'
}, {
  $set: { value: "_oauth/google?close" }
})
```
(of course be careful when tinkering with DB...)

**Comment by jthomaschewski** [comment]
Workaround for now:

- change migration version in db from 254 to 253:
```js
db.migrations.update({_id: "control", version: 254}, {$set: {version: 253}})
```
- downgrade to `v4.4.0`
- make sure the redirect uri *without* `?close` is authorized in google api console

Migration `254` will be re-applied when upgrading again but this shouldnt be an issue as its only gracefully re-creating some indexes.

**Comment by toantc** [comment]
I downgraded to 4.4.0 from 4.4.1 and added both URL with and without `?close` to the Google Console.
It's working on the web and desktop app but the mobile app isn't.

## Step to reproduce

1. Open mobile app
2. Login with Google Auth
3. Choose the email to login with 
4. Clicked "Open this page in Chat"

## Expected behavior

The mobile app should be logged in

## Actual behavior

The login screen is shown again

**Comment by sampaiodiego** [comment]
looks like there was a missing piece on the fix.. I'm working in a new fix right now

**Comment by cooljeanius** [comment]
> looks like there was a missing piece on the fix.. I'm working in a new fix right now

so... does that mean this should be reopened, then?

**Comment by sampaiodiego** [comment]
the missing part was already done (https://github.com/RocketChat/Rocket.Chat/pull/24450) and released on 4.4.2

**Comment by cooljeanius** [comment]
> the missing part was already done (#24450) and released on 4.4.2

Then why is it still broken for the MacPorts Rocket.Chat instance?

**Comment by sampaiodiego** [comment]
not sure @cooljeanius .. can you please provide more information? any error message on the logs?

**Comment by sidmohanty11** [comment]
Same error in `v4.8.1` :(

**Comment by cooljeanius** [comment]
> The exact error we see in the logs is:
> 
> ```
> rocket-chat_rocketchat.1.x94i0noq42cp@docker    | {"level":40,"time":"2022-05-20T21:34:48.125Z","pid":9,"hostname":"76618ccfda4d","name":"System","msg":"Automatically added ?close to 'redirect_uri' for github, this behavior will be removed in v5.0.0.\nPlease update your OAuth config to accept both with and without ?close as the 'redirect_uri'."}
> rocket-chat_rocketchat.1.x94i0noq42cp@docker    | Exception while invoking method 'login' TypeError: emails.find is not a function
> rocket-chat_rocketchat.1.x94i0noq42cp@docker    |     at Object.handleOauthRequest (packages/github-oauth/github_server.js:10:31)
> rocket-chat_rocketchat.1.x94i0noq42cp@docker    |     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
> rocket-chat_rocketchat.1.x94i0noq42cp@docker    |     at middleware (packages/oauth/oauth_server.js:171:5)
> rocket-chat_rocketchat.1.x94i0noq42cp@docker    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
> ```

Downstream issue on the MacPorts Trac: https://trac.macports.org/ticket/65937
