### ISSUE TITLE
Windows App Is not allowing me to access account page

### ISSUE THREAD

**Issue by DecodingDoom** [RocketChat/Rocket.Chat#24352]
I am able to download and install the app, but when I click on my account Icon it does not bring up any options to login or edit my status, as I do on the browser version (chrome)

It's a real bother, as I can't seem to get all of the channels for our chat to load on the browser interface, but I can on the windows app, which won't allow me to use my account

**Comment by dudanogueira** [comment]
Hi! Do you see any error in logs?

Also, can you state the versions you are using?
