### ISSUE TITLE
Update profile without password

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#2437]
Your Rocket.Chat version: (make sure you are running the latest)
0.20.0

As a logged in User
When I change my profile (My name)
I shouldn't have to retype my password

**Comment by istanfield09** [comment]
Is there anything else to this bug? When I change my profile name as a regular logged in user, I do not have to retype my password. v0.20.0

**Comment by pierreozoux** [comment]
https://cloud.pierre-o.fr/index.php/s/stqTkyNIcu1HYje

I have v0.20.0 also

On 07-03-2016 23:44, Ian Stanfield wrote:
> Is there anything else to this bug? When I change my profile name as a regular logged in user, I do not have to retype my password. v0.20.0
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/RocketChat/Rocket.Chat/issues/2437#issuecomment-193509784
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by istanfield09** [comment]
You can modify any part of your profile, other than your password, without providing your actual password. For example you can change and save the "Name" field without providing your password. But if you wish to change your password, you must provide your old password, and a new password. That is what that error message is describing. Perhaps we could enhance the UI so that changing your password is not in the profile field, or is some sub option.

**Comment by pierreozoux** [comment]
@istanfield09 arf, sorry, it is just my firefox filling the 'old password field'

I let you close if you feel it is irrelevant.

**Comment by istanfield09** [comment]
@pierreozoux I can't close the issue, but I think it actually brings up an interesting UX consideration. Since updating certain fields depend on other fields, and updating other fields don't depend on those fields, perhaps they should be separate from one another.

**Comment by engelgabriel** [comment]
I agree, let's make the UI more clear anyway. I'll close when we fix this.

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/13688253/616f7046-e6ff-11e5-8edf-b2c01287d1de.png)
