### ISSUE TITLE
Outgoing integrations not accepting response

### ISSUE THREAD

**Issue by tensor5g** [RocketChat/Rocket.Chat#24374]
### Description:

After the 4.4.0 update, outgoing integrations no longer seem to accept the response text. I have created an extremely simple outgoing integration that will respond with {"text":"test"} to any request, but rocket.chat will not post that message into the channel. When I try to debug this by viewing history, I get a blank page. It seems any integration that has more than 0 history will respond with a blank page this way. This is the error I get in console when attempting to open the history: `TypeError: u is not a function`

### Steps to reproduce:

1. Create an outgoing WebHook Integration
2. Point it to a URL that responds with {"text":"test"}
3. Trigger the outgoing WebHook
4. Observe that the WebHook receives the request, responds with a 200, but nothing appears in the channel

### Expected behavior:

Taking my response and posting it in the channel

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Docker
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Tried in latest Firefox and Edge
- Operating System: Windows 10

### Relevant logs:

The docker console does not display any errors from the outgoing hook or from opening the history.
My browser's console displays `TypeError: u is not a function` when attempting to open integration history, and some more nonsense: https://pastebin.com/w55Tt4HE

**Comment by thrakks** [comment]
Same here. All of our webhooks are suddenly broken as of 4.4.0. External applications are returning 200 and yet nothing is appearing in rocketchat.

Version of Rocket.Chat Server: 4.4.0
Operating System: Centos 7.9
Deployment Method: Manual installation
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version: 14.18.2
MongoDB Version: 4.4

**Comment by harvard1932** [comment]
same issue.. 2023...
