### ISSUE TITLE
Error on Download files in WebDav Integration with Nextcloud

### ISSUE THREAD

**Issue by mtcoliveira** [RocketChat/Rocket.Chat#24385]
Description:
Hello, i need some help with Webdav Integration function.

I've a Nextcloud Server with Webdav Working perfectly.
I enabled Webdav integration in Rocket.Chat.
In a public room and added a webdav connection.

The problem starts when I use this connection to send some file (like an image, for example) in the chat. I can browse my files on the Webdav Server, I select the file and when I click on send, it is stuck at 0%.
I tried to check the logs but nothing appears.
File type and size settings are default in my settings i.e. all file types and size up to 5MB

Using devtools to debug the process of sending the image, it generated a 404 error.

Below the debug trace:
Request URL https://MYDOMAIN/ufs/GridFS:Uploads/4mzFudqwpLjjfKaqQ?token=a97939E8ab&progress=0.1472044276331749
Request Method: POST
Status code: 404
Remote Address: MYDOMAIN:443

I'm using Docker behind NGINX without subfolder settings

Steps to reproduce:
Go to Rocket Chat Admin Page
Click on WebDav Integration
Check WebDav Integration Enable
In a room, configure the parameters correctly with: Name, WebDav URL, Username and Password

Expected behavior:
Add new WebDav Server, browse the folders, click on the file and send the file successfully.

Actual behavior:
I can add the server configuration, browse the folders until I get to the file. After clicking in send, it is stopped at 0% and not send the file.

Server Setup Information:
Version of Rocket.Chat Server: v4.4.0
Verion of Nexcloud Server: v23.0.0
Operating System: Debian v10.0
Deployment Method: Docker v20.10.3
Number of Running Instances: 1

Client Setup Information
Browser Version: Edge v97.0.1072.76
Operating System: Windows 11

**Comment by raffaelone** [comment]
I have exactly the same problem.
This is the error returned from the DevTools console:
![Error-webdav](https://user-images.githubusercontent.com/73063127/161433126-b167aba5-347e-47d0-899f-27a745027fcd.png)


**Server Setup Information**:
Version of Rocket.Chat Server: 4.5.5
Version of Nexcloud Server: 22.2.6
Operating System: Ubuntu Server 20.04.4 LTS
Deployment Method: Snap
Number of Running Instances: 1

**Client Setup Information**
Browser Version: Google Chrome  100.0.4896.60
Operating System: Ubuntu 20.04.4 LTS

**Comment by julianwinkel** [comment]
+1

**Comment by Jonher937** [comment]
I think you are hitting the same thing I did: https://github.com/RocketChat/Rocket.Chat/issues/24775
Workaround is to disable the proxy mix-in (as long as you don't use it) and rebuild: https://github.com/Jonher937/Rocket.Chat/blame/8a1b901daa1efb258b9619b63d6f09e6b21a2eb7/app/file-upload/server/index.js#L3-L4

**Comment by dougfabris** [comment]
Closing this issue, because it was fixed on this PR: #26422
Recently on our latest major release, we did a bunch of refactoring related to WebDAV and fortunately, I strongly believe, this specific issue will be available in our next release 5.1.0. 
If you guys still having trouble after updating it, please let me know!
Thanks for reporting it @mtcoliveira
