### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by adolfoalamo** [RocketChat/Rocket.Chat#2438]
Hi guys, this is not an issue.  I just want to know what is the best hosting company to host rocket chat?  Please advice!

**Comment by thomasharrick** [comment]
I personally love Heroku. In the github instructions, there's a button that says "Deploy to Heroku". You will be prompted to set up an account and host your app for FREE. But on the downside, it takes a considerable amount of time to load. [Click here to deploy immediately](https://heroku.com/deploy?template=https://github.com/RocketChat/Rocket.Chat/tree/develop).

Hope this works!

--Thomas Harrick
thomasharrick.com

**Comment by adolfoalamo** [comment]
Hi Thomas,
Thank you for your reply. I am looking for the faster and more efficient hosting!  I do not care if I have to pay for hosting. Thank you

**Comment by thomasharrick** [comment]
Hello adolfoalamo--
Try Cloudron if you are willing to pay money. I tried it and it's nice. There's a 30day money back guarantee.

**Comment by adolfoalamo** [comment]
Are those prices dollar? Where are they located?

**Comment by thomasharrick** [comment]
Doubtful. Actually Heroku's fast, and nice, but it's speed is mediocre and changes dramatically and frequently. I tried to access by app 20 min ago, and it was so slow, but now it's as fast as lightning. Probably not what you're looking for, but worth a shot.

**Comment by engelgabriel** [comment]
Hi @adolfoalamo and @thomasharrick, we are also creating a hosting infrastructure ourselves, if you are interested in giving it a try on our beta, please visit https://rocket.chat/deploy

This will be a good way to support the project.

**Comment by k0nsl** [comment]
@adolfoalamo:

I can recommend the KVM plans at BuyVM -- [http://buyvm.net/kvm-vps/](http://buyvm.net/kvm-vps/). They provide a solid service. You can also add filtering via Voxility for next to nothing (I think a filtered IP is $1 per month extra. I forget.
Anyway, I highly recommend them.

**Comment by adolfoalamo** [comment]
@engelgabriel How can we re-skin and have our own domain name on your hosting?  Please advice

**Comment by engelgabriel** [comment]
We dont support own domain yet :(

**Comment by adolfoalamo** [comment]
What about re-skin and logo on the botton?

**Comment by engelgabriel** [comment]
You can change colours and logo on the admin ui.
