### ISSUE TITLE
Administration Panel - Users page not working in Safari

### ISSUE THREAD

**Issue by Visualbench** [RocketChat/Rocket.Chat#24380]
### Description:
Administration Panel Users page does not display the users in Safari (self-hosted server)

### Steps to reproduce:

1. Go to Rocket Chat Admin Page 
2. Click on Users tab 
3. List of the users is not visible 

### Expected behavior:
List of the users to be visible

### Actual behavior:
List of the users is not visible

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Ubuntu 20.04
- Deployment Method: Docker 
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Safari 13.1.2
- Operating System: Mac OS

**Comment by dudanogueira** [comment]
Hi! Please, check the version you are using.

Latest is 4.4.0

Thanks!

**Comment by Visualbench** [comment]
> Hi! Please, check the version you are using.
> 
> Latest is 4.4.0
> 
> Thanks!

Sorry about that, I am using 4.4.0

**Comment by dudanogueira** [comment]
Thanks!

Sorry, forgot to also ask:
Was it working in previous versions and stopped after upgrade?

**Comment by Visualbench** [comment]
> Sorry, forgot to also ask: Was it working in previous versions and stopped after upgrade?
It is not working from **3.6.0 or lower**

**Comment by Visualbench** [comment]
After Inspecting the element, I found out that this version of Safari (13.1.2) doesn't understand _width: 100% and height:100%_ at the **rc-scrollbars-container** div, so nothing is displayed.

Any suggestions on how to overcome this?

![image](https://user-images.githubusercontent.com/87965439/152086648-571aa0d4-92bc-43b3-b164-38e92c615f5f.png)

**Comment by dudanogueira** [comment]
Then I think we can close this issue.

I know that we are doing some changes at the Admin Panel, and this area may be revamped down the road.

Also, this seems to be more a Safari Bug then Rocket.Chat's, considering that it works well on Safari's recent versions.

Thanks!
