### ISSUE TITLE
[BUG] Spelling of Incoming in Integration is wrong

### ISSUE THREAD

**Issue by Himanshu664** [RocketChat/Rocket.Chat#24391]
### Description:

Spelling of Incoming is wrong in Integration it is inconming it should be incoming.

### Steps to reproduce:

1. Go to Admin
2. Click on Integration

### Expected behavior:
![after](https://user-images.githubusercontent.com/76220055/152104537-9eaef9d5-edda-4a20-9d42-51bb221c123c.jpg)

### Actual behavior:
![incoming](https://user-images.githubusercontent.com/76220055/152104526-b9d4140e-1c5c-4354-b366-0fa68b192c0a.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0-develop
- Operating System: Linux ubuntu 20.04
- NodeJS Version: v14.18.2
- MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
- Operating System: Linux Ubuntu 20.04

**Comment by dougfabris** [comment]
Closing this one because it's already fixed: #26333
