### ISSUE TITLE
Push Important Information via Home Page

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2440]
Hello, 

I would like to be able to include html and php into the home page, while static pages and embedded youtube videos are nice they get old really fast, hence some dynamic content would be preferable.

To be specific i'd like to include something along these lines 

`<?php require_once "includes/functions.php"; ?>
<?php getFeed("http://mf.feeds.reuters.com/reuters/UKTopNews"); ?>
`

and achieve something like this :dancers: 

![newsfeed](https://cloud.githubusercontent.com/assets/17119942/13567590/622ac58a-e45c-11e5-9189-c7a316725173.png)

ps: also great show

**Comment by rodrigok** [comment]
We can't support PHP, but maybe we can add an iframe there, so you can load anything you want.

**Comment by bott0r** [comment]
sounds perfect :D

**Comment by IQ2022** [comment]
yes i totally agree we should leverage that front page to the max :+1:

**Comment by bott0r** [comment]
I noticed when i include an iframe in the home-section it wont show up in my browsers, which is expected. however when i utilize the android app the iframe will be displayed.

**Comment by Sing-Li** [comment]
Woke up to long-anticipated new iOS version (with all the features and fixes) but saw the same old home page screen.  

Had a change of heart ....  that page is Xtremely USEFUL for us to push IMPORTANT update information to all our Rocket.Chat user base (with minimal hassle).

Changed title to better reflect issue --   @RocketChat/core  - please reconsider the priority on this one.   Thx.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
