### ISSUE TITLE
[FEATURE REQUEST] Message tracking feature should be included

### ISSUE THREAD

**Issue by aakash-gitdev** [RocketChat/Rocket.Chat#24416]
**Description:**

We should be able to know who all have read our messages, so that during urgent situations we can directly tag them and know their opinions about our message.

**Steps to reproduce:**

1) Click on the options button on the top right corner of any message.

**Expected Behaviour:**

If we click on a particular message, there should be an option to view a complete list of all those who have read the message.

**Actual Behaviour:**

Currently, this feature is unavailable.
![message tracker](https://user-images.githubusercontent.com/94236076/152555992-e25d61f8-3c1e-4494-bc9d-00d09761d766.jpeg)

**Comment by aakash-gitdev** [comment]
*I will be glad to have some opinions about this feature request.*

**Comment by debdutdeb** [comment]
Hi! thanks for the interest :)

The feature you're talking about is called read reciepts, already is part of rocket.chat - Administration > Message > Message_Read_Receipt_Enabled. It is disabled by default. 

Closing this now, but feel free to continue the conversation.
