### ISSUE TITLE
Error message for invalid commands

### ISSUE THREAD

**Issue by matthias-brun** [RocketChat/Rocket.Chat#2442]
Your Rocket.Chat version: develop/HEAD

At the moment if a user enters an invalid (-> unrecognized) chat command and hits the enter key the textbox is cleared but nothing happens.

I have seen this lead to confusion several times when users pasted a UNIX file path (e.g. /var/lib/something) and didn't notice that the path was interpreted as an invalid command and discarded.
In my opinion the behaviour is fine as is but there should be an error message telling the user that their message was interpreted as an invalid command. The existing error messages package would be fine for this purpose:
![screen shot 2016-03-07 at 14 34 20](https://cloud.githubusercontent.com/assets/10801000/13570929/baa3ecc2-e471-11e5-83ea-018c09112e17.png)

**Comment by rodrigok** [comment]
Can you test again? This should be fixed by https://github.com/RocketChat/Rocket.Chat/pull/2432

Reopen this issue if the problem persists
