### ISSUE TITLE
Permissions page in admin panel not loading in version 4.3.2 and 4.4.1

### ISSUE THREAD

**Issue by mosynaq** [RocketChat/Rocket.Chat#24447]
### Description:
I am evaluating Rocket Chat and I encountered this issue: When I want to view permissions page in admin panel, it simply does not load.
It is worth to mentioning that I use Keycloak as the IdP and my user is admin.

### Steps to reproduce:

1. Login to your account.
2. Go to Admin panel.
3. Click on "Permissions" on left pane.

### Expected behavior:

Displaying Permissions page

### Actual behavior:

I get an empty page.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.2 or 4.4.1
- Operating System: CentOS 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.18.2
- MongoDB Version: 4.4.2 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 10

### Relevant logs:
Chrome log: `invalid-param at Function.isPermissionRestrictedForRole`, two times
Server log: nothing

**Comment by dudanogueira** [comment]
Hi!

Can you reproduce this on a clean install with latest or just in your deployment?

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
