### ISSUE TITLE
v4.4 not upggarding from v4.3.3

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#24446]
### Description:
several errors is displayed when upgrading from v4.3.3 to v4.4

### Steps to reproduce:

sudo systemctl stop rocketchat
sudo rm -r /opt/Rocket.Chat.old
sudo mv /opt/Rocket.Chat /opt/Rocket.Chat.old
sudo n install 14.18.2
curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server && npm install
sudo mv /tmp/bundle /opt/Rocket.Chat
sudo chown -R rocketchat:rocketchat /opt/Rocket.Chat
sudo systemctl start rocketchat

### Expected behavior:
v4.3.3 to be upgraded to v4.4

### Actual behavior:
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/bundle/programs/server/node_modules/fibers/build'
gyp ERR! System Linux 4.15.0-167-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /tmp/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/bundle/programs/server/node_modules/fibers/build'
gyp ERR! System Linux 4.15.0-167-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /tmp/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v14.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@https://github.com/meteor/node-fibers/archive/refs/tags/5.0.0-1.tar.gz install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/the5stars.servant/.npm/_logs/2022-02-08T09_38_40_682Z-debug.log

**Comment by r3dnib** [comment]
Same Problem here....

**Comment by sthaydn** [comment]
Same here. I have installed build-essentials as stated in the error log, but still no luck.

**Comment by lovekyleman** [comment]
![image](https://user-images.githubusercontent.com/93461213/153734416-fd45d490-ba81-408d-92ad-683bb1a69925.jpeg)
Downgrade to Node v12 is fine. But can't start Rocket.Chat. 
Node V14, errors, but Rocket.Chat works fine.
Does know how to fix this? 
Thanks

**Comment by sthaydn** [comment]
So I have it working finally. I don't really know what is the solution, but https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/updating brought me on the right path. Maybe you should also install "make" and please be assured you really have node 14.x installed AND active.

**Comment by ali-alhaidary** [comment]
Thanks, worked for me as well 4.3.3 to 4.4.2
I think the issue was installing Node 14.18.2 (as stated in the release)  and not 14.0.0 (as stated in the update), otherwise, all steps were the same...
