### ISSUE TITLE
User Registration Form Secret URL broken since 4.4.0

### ISSUE THREAD

**Issue by tom666-debug** [RocketChat/Rocket.Chat#24444]
### Description:

Seems that the funktion to provide a secret link for the user regestration form is broken since version 4.4.0.
All I got when opening this page (e.g. https://chat.mydomain.de/register/[secret_hash]) is a "provided URL is wrong"

### Steps to reproduce:

1. Check your "secret link" settings here: Administation, Accounts, Regestration
2. Try to open the "secret" link as configured  (e.g. https://chat.mydomain.de/register/[secret_hash])

### Expected behavior:

After opening the "secret link" a regestration form will be opend.

### Actual behavior:

![image](https://user-images.githubusercontent.com/78903224/152940204-9b760ae8-8f3a-430f-9d00-22281523de45.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.1
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.18.2
- MongoDB Version: 5.0.3 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment]
Confirm that issue 
![image](https://user-images.githubusercontent.com/4023037/152952365-e505a60a-438b-4ba4-9164-899a7ee7aee4.png)

**Comment by dudanogueira** [comment]
confirming it too. No outstanding logs.

**Comment by lovekyleman** [comment]
We have the same issue

**Comment by Bengrunt** [comment]
Encountered this as well. :/

**Comment by supportdesk-si** [comment]
Same here. Upgraded to 4.4.2 and private channel invites are defaulting to Invalid or expired invite token.  This is a huge issue!!!  

Making registration private, disabled or public makes no difference.

It was working perfectly fine prior to the update.

Deployment
Version 4.4.2
Apps Engine Version 1.30.0
Node Version v14.19.0
Database Migration 254 (February 11, 2022 3:52 PM)
MongoDB 4.2.18 / wiredTiger (oplog Enabled)

**Comment by Cob0ld** [comment]
we have the same problem with version 4.4.2

**Comment by supportdesk-si** [comment]
There is a note in one of the links that it was addressed in 4.4.4 but what a bummer.  You can't get it via releases link and one would say enterprise environments with this type of quality control should really be thinking twice. Just 2 cents

**Comment by kitich** [comment]
We have the same issue.

INFO:

```
Version 4.4.2
Apps Engine Version 1.30.0
Node Version v14.18.2
Database Migration 254
MongoDB 4.0.20 / mmapv1 (oplog Enabled)
Commit Details HEAD: (ec8011e94)
```

**Comment by rymek** [comment]
Same issue here:
`Deployment
Version
4.4.0
Deployment ID
CD2sgexXT6yLzkAh6
Apps Engine Version
1.30.0
Node Version
v14.18.2
Database Migration
253 (February 11, 2022 9:48)
MongoDB
4.4.5 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (f32fdfb36)
Branch: HEAD`

**Comment by axkibe** [comment]
I tried to figure out if the issue can be easily fixed..
I'm failing because I don't understand how this should work:

https://github.com/RocketChat/Rocket.Chat/blob/develop/client/views/invite/SecretURLPage.tsx

There seem to be only two outcomes to the query, either is loading, or if not loading the invalid URL message is displayed. There is no success route? From debugging, onSuccess from the query is called, and `valid` is true.. but then it still defaults to the invalid URL answer.

Maybe
```
setLoginDefaultState('register');
KonchatNotification.getDesktopPermission();
```
is supposed to reload the page somewhere else?

Unfortunately in 4.3 last version were it worked this whole subsystem was written quite different, so comparing these also didn't help...

Help, this is quite important to get fixed. (PS: if not soon, can one downgrade from 4.4 to 4.3?)

**Comment by hmdd81** [comment]
Still happens in 4.5.0

**Comment by tom666-debug** [comment]
Still broken in 4.5.1 - Seems that allowing user to register themself is totally overrated ....

**Comment by supportdesk-si** [comment]
Latest update same issue.  This is crippling and surprisingly ignored by the dev community.

**Comment by Cob0ld** [comment]
any eta when this might get fixed ?! its an important feature

**Comment by kitich** [comment]
Still broken on 4.5.2

**Comment by axkibe** [comment]
How is everybody ignoring I did make a patch, despite it not getting
accepted..

**Comment by supportdesk-si** [comment]
The option is not working.  This is very strange for such a platform to ignore such a vital functionality!

**Comment by lovekyleman** [comment]
Seems no one cares about this bug
4.5.3 still the same

**Comment by supportdesk-si** [comment]
Version 4.5.3 is dead in the water again.

Does anyone knows or follows this bug.  Seems there is a fix but it is not incorporated into the release. WTF?

**Comment by Cob0ld** [comment]
> Version 4.5.3 is dead in the water again.
> 
> Does anyone knows or follows this bug. Seems there is a fix but it is not incorporated into the release. WTF?

Yeah comes across that way ... idk why this is not getting more attention

**Comment by supportdesk-si** [comment]
Just placed 4.6.0-rc0 ... same issue :(  What is going on?

**Comment by hailfinger** [comment]
Will this fix be backported to 4.5.x?

**Comment by danielehrhardt** [comment]
Fixed:
[2388725](https://github.com/RocketChat/Rocket.Chat/pull/24921#issuecomment-1087529718)

**Comment by bdelwood** [comment]
Still seeing this issue in v4.6.0 with new invite links.

**Comment by yash-rajpal** [comment]
@bdelwood the fix for invite links is released in v4.6.1

**Comment by Labevue** [comment]
Hello,

It's not working with 
![image](https://user-images.githubusercontent.com/49780995/194923770-f2cd2eee-87d7-44b0-a7cf-bbdc9824dfeb.png)

And the mail is : 
`<h2>Bienvenue dans [Site_Name]</h2>
<p>Suivez ce lien pour vous inscrire : </p>
<p>[Site_URL]/register/[secret_hash]</span></p>
<a class="btn" href="[Site_URL]">Connexion</a>

Help please 

`

**Comment by Labevue** [comment]
Hello,

It's not working with : 
![image](https://user-images.githubusercontent.com/49780995/194925276-8fa17f16-73af-4692-a7ac-4bba7b0c50e0.png)

Register settings : 
![image](https://user-images.githubusercontent.com/49780995/194925388-4f414e7c-f552-4974-a295-8e21dbe5c54a.png)

Mail template : 
![image](https://user-images.githubusercontent.com/49780995/194925469-3d6a31d6-d215-4d60-9603-3036001942ce.png)

Help please ....
Best regards
