### ISSUE TITLE
Admin can change the name of user

### ISSUE THREAD

**Issue by Ayush01729** [RocketChat/Rocket.Chat#24448]
### Description:

Admin can change the name of any user. 
Although, on the chat the original name is visible, so it is better to disable that "edit" button

### Steps to reproduce:

1. Go to administration
2. Go to users
3. You can edit the name of users.

### Expected behavior:

Only users should be able to edit their name and not the admin

### Actual behavior:

Admin and user both can edit their name

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

![rocket_chat](https://user-images.githubusercontent.com/76625106/153000692-3d11476e-e244-48cd-a1c3-060f2fc85821.PNG)

**Comment by Himanshu664** [comment]
@Ayush01729 This is default feature admin has rights to change to username,you can close this issue
