### ISSUE TITLE
Custom colors broken after update from 3.18.5 to 4.4.1

### ISSUE THREAD

**Issue by Rollbacke** [RocketChat/Rocket.Chat#24449]
### Description:

The 

### Steps to reproduce:

1. Go to admin panel -> Layout -> Colors
2. Set custom HTML color (Type color, no Expression)
3. Save
4. Refresh and see that it doesn't work.

### Expected behavior:

Working custom HTML colors in Layout -> Colors.

### Actual behavior:

The colors are "broken" since the update to 4.4.1.
When I go back to the admin panel, the colors I changed are in "expression" mode.
If I go back and change them as color type, it doesn't work.
And if I go back there again, they are again in "expression" mode.
![colors_broken](https://user-images.githubusercontent.com/86650802/153022722-625fad15-b5f8-44fa-8095-fd45c04587b9.png)
![colors_in_admin_panel](https://user-images.githubusercontent.com/86650802/153022726-72000d6b-7ba2-4b1e-98c4-4a94cea824b5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.1
- Operating System: Ubuntu 20.04.3
- Deployment Method: tar
- Number of Running Instances: 7
- DB Replicaset Oplog: N/A
- NodeJS Version: 14.18.2
- MongoDB Version: 4.2.18

### Client Setup Information

- Desktop App or Browser Version: 91.5.0esr (64 bits)
- Operating System: Deb11

### Relevant logs:

I haven't relevant logs

**Comment by viveky45** [comment]
@Rollbacke i would like to work on it.

**Comment by Rollbacke** [comment]
> @Rollbacke i would like to work on it.

Can you reproduce the problem?
