### ISSUE TITLE
Link previews for Reddit do not display preview block/image

### ISSUE THREAD

**Issue by binarydad** [RocketChat/Rocket.Chat#24457]
### Description:

Links pasted into chat do not render a preview do not have a preview. Other links seem to work fine. 

### Steps to reproduce:

1. Grab a link, such as https://www.reddit.com/r/funny/comments/so4pyf/dakota_has_been_on_stall_rest_for_months_due_to/
2. Send to chat

### Expected behavior:

I expect a link preview to show at least a description, ideally with image.

### Actual behavior:

Just the link is sent as text, but without any sort of preview block.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.1
- Operating System: Ubuntu 18
- Deployment Method: Native
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4

There is no difference if the link is sent via mobile app or web, and neither renders the preview. 

![image](https://user-images.githubusercontent.com/1760607/153231694-9e5c548f-88ae-47df-a190-48cd58ff24bb.png)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
