### ISSUE TITLE
Improve emoji

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#2446]
There are two emoji's that are really not okay to be honest.

:D and :) those two do not look like any other emoji out there, those two are way way to happy/weird looking.

They should be looking something like the first smiley on both rows, i've had many users complaining about this and i agree with them.
![smileys](https://cloud.githubusercontent.com/assets/17712562/13585778/0f883652-e4be-11e5-9e00-2ada14652dd8.png)

Also there would be really cool if you could add a emoji symbol under the upload file symbol so the users can see a list of all the emojis that exists.

**Comment by graywolf336** [comment]
Please see: https://github.com/RocketChat/Rocket.Chat/issues/2270

**Comment by Molle500** [comment]
Okay great but how about the emoji symbol to easy access the emoji list?

**Comment by engelgabriel** [comment]
That would be awesome! :)

**Comment by Molle500** [comment]
Would be cool if you could change these emoji's as well since they are much more recognizable.
https://github.com/twitter/twemoji

**Comment by engelgabriel** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/480

**Comment by sebgrizzly** [comment]
This is not only a duplication, the used emoji's are not very nice, it would be awsome to use the standard emotji's on RocketChat too.

**Comment by tadeu** [comment]
The +1 (:+1:) emoji is SO UGLY!

![image](https://user-images.githubusercontent.com/955251/32052380-d420dd9e-ba36-11e7-98b9-e3a43ba115d6.png)

Here are some alternatives for comparison: https://emojipedia.org/thumbs-up-sign/

**Comment by tadeu** [comment]
Reference to related open issue: #1838
