### ISSUE TITLE
4.4.2: GitLab OAuth doesn't work anymore

### ISSUE THREAD

**Issue by v1adislav** [RocketChat/Rocket.Chat#24460]
### Description:

After upgrading Rocket.Chat to version 4.4.2, OAuth no longer works with GitLab.
You get an undefined error after successful login to our self-managed GitLab instance.

### Steps to reproduce:

1. Upgrade Rocket.Chat to version 4.4.2
2. Click login with GitLab OAuth
3. Login into GitLab instance
4. Undefined error triggered -> Login failed

### Actual behavior:

When I try to login I get "Internal server error"

<img width="341" alt="image" src="https://user-images.githubusercontent.com/31951534/153351960-0b722f24-8b82-43a9-8b9a-62abb8ff1ba5.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.2
- Operating System: Oracle Linux 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.18.2
- MongoDB Version: 5.0.5 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: MacOS / Windows

### Additional context

The GitLab-URL is set to our self hosted GitLab instance.

### Relevant logs:

```Exception while invoking method 'login' Error: Failed to complete OAuth handshake with gitlab at https://gitlab.com/oauth/token. failed [401] {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method```

**Comment by xcore89** [comment]
I have the same problem on version 4.4.2.

**Comment by 4nt0h4** [comment]
I confirm that OAuth authorization does not work

**Comment by dudanogueira** [comment]
Hi! What are the versions you upgraded from?

this is probably related to https://github.com/RocketChat/Rocket.Chat/issues/24355

**Comment by v1adislav** [comment]
@dudanogueira The bug started with version 4.2.2. Now I have updated from 4.4.0

**Comment by J-Ankit2020** [comment]
Can I work on this issue

**Comment by J-Ankit2020** [comment]
@v1adislav can I work on this

**Comment by NeXT405** [comment]
Any news on this??

**Comment by g5pw** [comment]
I also have an Internal Server Error during OAuth login with Github after upgrading, I can see the following in the logs:

```
rocket-chat_rocketchat.1.8wy3ziw1gily@docker    | {"level":40,"time":"2022-02-14T16:26:33.799Z","pid":8,"hostname":"2750394edd44","name":"","name":"System","msg":"Automatically added ?close to 'redirect_uri' for github, this behavior will be removed in v5.0.0.\nPlease update your OAuth config to accept both with and without ?close as the 'redirect_uri'."}
rocket-chat_rocketchat.1.8wy3ziw1gily@docker    | Exception while invoking method 'login' TypeError: emails.find is not a function
rocket-chat_rocketchat.1.8wy3ziw1gily@docker    |     at Object.handleOauthRequest (packages/github-oauth/github_server.js:10:31)
rocket-chat_rocketchat.1.8wy3ziw1gily@docker    |     at OAuth._requestHandlers.<computed> (packages/oauth2/oauth2_server.js:10:33)
rocket-chat_rocketchat.1.8wy3ziw1gily@docker    |     at middleware (packages/oauth/oauth_server.js:171:5)
rocket-chat_rocketchat.1.8wy3ziw1gily@docker    |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by v1adislav** [comment]
@sampaiodiego mb fix this problem?

**Comment by chriz-uniba** [comment]
I guess this is also related to https://github.com/RocketChat/Rocket.Chat/issues/23613 --- which has some workaround that worked for us.

**Comment by cooljeanius** [comment]
This is breaking the MacPorts Rocket.Chat instance: https://lists.macports.org/pipermail/macports-users/2022-March/050863.html

**Comment by v1adislav** [comment]
problem resolve in version 4.5.2

**Comment by cooljeanius** [comment]
> problem resolve in version 4.5.2

But the MacPorts Rocket.Chat instance is still broken, though...
