### ISSUE TITLE
Using random port number instead of 3000

### ISSUE THREAD

**Issue by littlep13** [RocketChat/Rocket.Chat#2447]
Rocket.Chat version: 0.20.0

Hi,

I was following the guide, https://github.com/RocketChat/Rocket.Chat/wiki/Windows-Deployment, for setting up a demo environment on a Windows 7 VM. 

After completing the steps, I found that I couldn't get to the login page by using http://localhost:3000 or http://my-server-url:3000. Then, I used netstat -a to find out what ports were being listened and found that I could open the login page by going to http://localhost:50396.

Can you please let me know how or where I can fix the port?

Thanks.

**Comment by tvld** [comment]
Do you have same issue on a Linux VM ?

**Comment by engelgabriel** [comment]
Did you have the browser open? Is that the web socket port negotiated by the browser and the server? This is not something that can/needs fixing.
