### ISSUE TITLE
I am having trouble to setup Rocket.Chat with a remote MongoDB (TLS)

### ISSUE THREAD

**Issue by arifulislamat** [RocketChat/Rocket.Chat#24487]
## I am having trouble to setup Rocket.Chat with a remote MongoDB (TLS)   

What i am trying to accomplish: 

***Setup Rocket.Chat container with docker-compose and connect Rocket.Chat with a manged secure MongoDB instance running on DigitalOcean.*** 

I have found helpfull docs at: https://docs.rocket.chat/quick-start/installing-and-updating/simple-deployment-methods/docker-and-docker-compose/docker-containers/high-availability-install  

This docs is perfect, but I need to make a secure connection with TLS.  

### My docker-compose environment for Rocket.Chat looks like:  
```      
 environment:
      - PORT=3000
      - ROOT_URL=https://localhost:3000/
      - MONGO_URL=mongodb+srv://rocketchat_user:<password>@<mongodb-server-address>/rocketchat_db?authSource=admin&replicaSet=rs0&w=majority&tls=true&tlsCAFile=<cert-path>
      - MONGO_OPLOG_URL=mongodb+srv://rocketchat_user:<password>@<mongodb-server-address>/local?authSource=admin&replicaSet=rs0&tls=true&tlsCAFile=<cert-path>
  ```   
### Server Setup Information

-  Version of Rocket.Chat Server:  4.4.1
- Host Operating System:  Ubuntu 20 LTS 
- Deployment Method:  Docker Compose  

### MongoDB Information 

- MongoDB Version: 4.4 
- Protocol: mongodb+srv
- TLS: True 
- Provider: DigitalOcean  

**Any help will be highly appreciated, Thanks !**

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
