### ISSUE TITLE
[BUG]: Empty role is created in new role 

### ISSUE THREAD

**Issue by Himanshu664** [RocketChat/Rocket.Chat#24482]
### Description:
when I create new role from permissions, it can be created empty.

### Steps to reproduce:

1. Go to Admin
2. Click on Permissions
3. Click on New Role
4. Save without giving role name
### Expected behavior:

Role name and  Role description should made mandatory.

### Actual behavior:

https://user-images.githubusercontent.com/76220055/153590526-d583398b-bc62-4b2b-a045-5811c77d99b6.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.5.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.2
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by prsndp** [comment]
@Himanshu664 I would like to work on this issue if it is open officially? thanks:)

**Comment by J-Ankit2020** [comment]
@Himanshu664  I would like to work on this issue

**Comment by dougfabris** [comment]
Already fixed here: #25063
Thanks for reporting @Himanshu664
