### ISSUE TITLE
Unable to access once setup is complete

### ISSUE THREAD

**Issue by miarosemathews** [RocketChat/Rocket.Chat#24492]
Whenever i go to the url i set during setup i just get a blank page that has a grey background. I cannot access any of the app.

<img width="1119" alt="Screen Shot 2022-02-14 at 1 56 47 AM" src="https://user-images.githubusercontent.com/63470220/153814987-fc7cf7dc-9824-4f21-acf5-bd31fdec9a32.png">

**Comment by debdutdeb** [comment]
Hi, please fill the issue template, we can't help unless we have all the information.
