### ISSUE TITLE
Is upgrading from rocket chat 3.6 to 3.15.1 officially supported?

### ISSUE THREAD

**Issue by kelvinblade** [RocketChat/Rocket.Chat#24494]
We are trying to upgrade mongo from 4.0 to at least 4.2. We understand that the lowest version to support mongo 4.2 is rocket chat 3.15.1. Our rocket chat is currently 3.6.

1) Is there any official documentation on which versions of rocket chat can be safely upgraded to which versions?
2) Does anyone know if upgrading from rocket chat 3.6 to 3.15.1 is officially supported?

Thanks.

**Comment by fdellwing** [comment]
Updating 3.6 to 3.15.1 should not be a problem (but please update to 3.18.5 for security reasons). I'm not aware of any breaking changes in between those.

**Comment by debdutdeb** [comment]
Thanks for replying @fdellwing :)
