### ISSUE TITLE
Document installation of released version

### ISSUE THREAD

**Issue by hhenkel** [RocketChat/Rocket.Chat#2449]
Your Rocket.Chat version: GIT Develop branch

The installation of the latest rocket.chat version is documented multiple times on the wiki. However it seems like the released versions needs different handling - therefore I would suggest to improve the documentation on that.

**Comment by engelgabriel** [comment]
We need to clear up the wiki

**Comment by marceloschmidt** [comment]
Docs have been updated in several aspects. Could you please check our new docs at https://rocket.chat/docs ? If it's missing some info, let us know and we can reopen this.
