### ISSUE TITLE
Incoming WebHook improvment

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2450]
Your Rocket.Chat version: 0.21

This issue may not be an issue. Could just be lack of information.

Is it possible to do a webhook that can post in multiple channels.

Use Case:
Lets say I have 50 channels and want to post individually to them from an external source.  

As I understand today i would today need to create 50 webhooks and to be able to in them all. 
And as soon i add a channel i would need to create a new webhook.

This  will be a pain to administrate. 

Is there anyway to create a webhook where you could specify the #channel 

Hope you understand
Mathias

**Comment by rodrigok** [comment]
Hi @lunitic, you always can override the channel via webhook, so your external service can define where will post the message.

```javascript
{
  "text": "Response text",
  "channel": "#general", // <-- custom channel
  "attachments": [
    {
      "title": "Rocket.Chat",
      "title_link": "https://rocket.chat",
      "text": "Rocket.Chat, the best open source chat",
      "image_url": "https://rocket.chat/images/mockup.png",
      "color": "#764FA5"
    }
}
```

**Comment by amenk** [comment]
It's also possible to pass via GET paramt to the hook

**Comment by knokio** [comment]
Is this working right now? I'm testing with the latest version (v0.65.1) and I can't override the channel defined in the webhook.
