### ISSUE TITLE
Feature wish - command line api

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#2453]
allow me to create (private) channels from the command line and invite users to a channel. Reason (perhaps there's other way to do this): I want to automate certain tasks with hubot, and I want hubot to be able to do a lot of tasks for me. I've already got a bot command to create and populate a gitlabs repo...

**Comment by geekgonecrazy** [comment]
@sinteur technically this would already be possible using the hubot callMethod function on the adapter.

You can call like:
```
robot.adapter.callMethod('methodName', {key: value});
```

The meteor method:
https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-lib/server/methods/insertOrUpdateUser.coffee#L2

Of coure a CLI api would still be cool.  Just not sure how it'd be implemented.  Almost would have to be a separate binary

**Comment by sinteur** [comment]
Interesting, I'll have a poke around

**Comment by sinteur** [comment]
Poked around... Simple hubot script like this:

  robot.respond /makemeachannel (.*)/i, (res) ->
   roomName = res.match[1]
   robot.adapter.callMethod('createPrivateGroup', { '0': roomName, '1': ['johnsinteur' ] });

or this:

  robot.respond /makemeachannel (.*)/i, (res) ->
   roomName = res.match[1]
   robot.adapter.callMethod('createChannel', { '0': roomName, '1': ['johnsinteur' ] });

shows the EXACT same lines in rocket chat's verbose logging as would appear if I manually created a room or provate channel via the web interface, but no room is created and no error is shown.

manual via web:
I20160311-11:17:49.260(1)? [methods] createPrivateGroup -> userId: bmp2McA6Aua4dJcLp , arguments:  { '0': 'test98765', '1': [ 'rosbot' ] }

via hubot call:
I20160311-11:25:47.558(1)? [methods] createPrivateGroup -> userId: 966ncuZr7keAvtr8N , arguments:  { '0': { '0': 'test1234567', '1': [ 'johnsinteur' ] } }

(and both the manual account as the hubot account have admin rights....

so obviously I'm doing something wrong. Have a hint for me greek?

**Comment by sinteur** [comment]
ho wait I think I see a difference..

**Comment by geekgonecrazy** [comment]
@sinteur try this:

```
robot.adapter.callMethod('createPrivateGroup', 'groupname', ['username1', 'username2'])
```

Just a note.  Right now just being added to a group doesn't alert them.  A message will have to be sent into the room before it'll show up in the list.  It'll show up under more private groups.  But sending a message should surface it.  I think we have an issue tracking that.

**Comment by sinteur** [comment]
robot.respond /make me a channel (.*)/i, (res) ->
   roomName = res.match[1]
   res.send "Sure, hold on"
   newroom = robot.adapter.callMethod('createPrivateGroup', roomName, ['USER1','USER2'])
   res.send  "+done - Added USER1 and USER2 to the new room"
   newroom.then (roomId) =>
   	console.log(roomId)
    robot.messageRoom roomId.rid, "@all hello!"

**Comment by geekgonecrazy** [comment]
@sinteur thanks for dropping that nugget here :+1:
