### ISSUE TITLE
Overlay after deleting a file wont disappear

### ISSUE THREAD

**Issue by Ruuudi** [RocketChat/Rocket.Chat#2454]
Your Rocket.Chat version: v0.21.0

After deleting a file from channel an alert messages displays a success message. But you can't close this overlay. You have to reload the browser.

**Comment by sampaiodiego** [comment]
what store type are you using? `Administration > File Upload > Storage Type`

**Comment by Ruuudi** [comment]
`image/*,audio/*,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document`

**Comment by sampaiodiego** [comment]
I'm sorry, what **Storage Type** ? AmazonS3 or GridFS?

**Comment by Ruuudi** [comment]
Sorry, my fault. I'm using GridFS.

**Comment by Ruuudi** [comment]
btw: is there any option to change the storage type? Under `Administration > File Upload > Storage Type` there is nothing to choose.
