### ISSUE TITLE
Video and audio call in omnichannel

### ISSUE THREAD

**Issue by mahyarkarimi** [RocketChat/Rocket.Chat#24550]
Video and audio conferencing using Webrtc in omnichannel has issues

### Steps to reproduce:
1. enabled web rtc in settings
2. enabled audio and video calls in omnichannel settings
3. make a call with agent to widget

### Expected behavior:

The settings() function in `app/livechat/server/api/lib/livechat.js:110` raises an exception due to not having input parameter and reading businessUnit of undefined.
all the references of livechat.settings() method must have at least an empty object ({}) as input parameter to work.
with having this change the call is created and the customer can answer it however no video and audio is transferred to neither omnichannel client web app nor customer widget.

### Server Setup Information:

Version 4.4.2
Apps Engine Version 1.30.0
Node Version v14.18.2
Database Migration 254 (February 20, 2022 9:14 AM)
MongoDB 4.4.4 / wiredTiger (oplog Enabled)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
