### ISSUE TITLE
Omnichannel: Add toPhone Number to custom fields from twilio sms integration

### ISSUE THREAD

**Issue by racquetmaster** [RocketChat/Rocket.Chat#24570]
When an SMS comes in from Twilio, it grabs the city, state, and country and updates the room information. It would be nice if it included the toPhone as well.

We have multiple branches around the country. Each branch has a phone number. Customers can text into those numbers and they all get passed into rocket.chat omnichannel. If we could see the phone number that they are texting, we would know which branch they are trying to speak to. This should be a couple of lines added to this section:

https://github.com/RocketChat/Rocket.Chat/blob/96c555544ec5027aede0d8f5562c66781d2abea6/app/livechat/imports/server/rest/sms.js#L178-L191

**Comment by KhadishaKudys** [comment]
May I work on this issue, please?

**Comment by its-kunal** [comment]
may i work in this issue.

**Comment by aakash-gitdev** [comment]
Kindly suggest what changes should I include in my code? This is my first PR in Rocket chat so it would be great to have some feedback.
