### ISSUE TITLE
View fails to load when trying to send a message to a new user.

### ISSUE THREAD

**Issue by redRolf** [RocketChat/Rocket.Chat#24579]
**Describe the bug**
- Search for a User you have not messaged before.
- Click on the User with the intent of sending him a message.
- The interface will now not load. It will stay blank, as if it is stuck.
- When reloading the view with `⌘ + r` the view will load correctly and a message can be sent normally

What operating system and which version?
- MacOS 12.2.1
Which version of Rocket.Chat (Server)?
- 4.4.1
Which version of Rocket.Chat.Electron (Electron/Desktop)?
- 3.7.7
Is there any setting relevant changed?

**To Reproduce**
1. Search for a user you have never messaged before
2. Click on the  user. The interface will now not load.

**Expected behavior**
Correct loading of the user interface in all scenarios

**Screenshots**

**Additional context**

**Comment by redRolf** [comment]
That works for me thank you for triaging 🙏

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/24175
