### ISSUE TITLE
writing to readonly property 'reconnectCount'

### ISSUE THREAD

**Issue by galmok** [RocketChat/Rocket.Chat#2459]
Your Rocket.Chat version: 0.21.0

I am trying to make smtp work and in that process, I am using password recovery interface of Rocket.Chat, but after having inserted my password (account is created, but not verified), and then clicking the recovery button, Rocket.Chat crashes completely with this error:

```
C:\rocket.chat\programs\server\npm\email\node_modules\simplesmtp\lib\client.js:823
    this._xoauth2.reconnectCount = 0;
                                 ^

TypeError: Cannot assign to read only property 'reconnectCount' of false
    at SMTPClient._actionAUTHComplete (C:\rocket.chat\programs\server\npm\email\node_modules\simplesmtp\lib\client.js:823:34)
    at SMTPClient._onData (C:\rocket.chat\programs\server\npm\email\node_modules\simplesmtp\lib\client.js:329:29)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:529:20)
```

I have set the MAIL_URL variable like this:

smtp://<username>:<pw>@mailhost.site.com:25/

**Comment by engelgabriel** [comment]
You should set all the  SMTP setting on the admin panel individually, not the MAIL_URL.


![image](https://cloud.githubusercontent.com/assets/1000217/13677193/ad8d104c-e6c7-11e5-9189-877026367905.png)

**Comment by galmok** [comment]
I would if I could log in...
Den 10/03/2016 17.55 skrev "Gabriel Engel" <notifications@github.com>:

**Comment by galmok** [comment]
How do we log in without a SMTP server configured?

**Comment by galmok** [comment]
Never mind. I upgraded to 0.22 and now I can log in without the above mentioned error.

However, for both 0.21 and 0.22, I had to update fibers from 1.0.5 to 1.0.10 and I also had to upgrade npm-bcrypt. Maybe the project should upgrade these files?

**Comment by engelgabriel** [comment]
Did you have to update fibers manually? This is odd. Did you run the `npm install` command on the  right folder after update?

**Comment by galmok** [comment]
Not sure if you want me to reply here, but yes, I had to upgrade fibers (and npm-bcrypt) manually. The `npm install`process did not perform the upgrade. In fact, it seems to ignore the project.json file where I first tried to fix this issue.

**Comment by engelgabriel** [comment]
Thanks for replying... this is the first time this issue was reported.. thats why I was surprised. What folder did you perform the npm install? Did you install fibers (and npm-bcrypt) globally?

**Comment by galmok** [comment]
First, I will say that I am running this on Windows 7 x64 with node v4.4.0.

I extracted all files and entered the `programs/server` folder and in there I ran `npm install`. It fails with fibers being the culprit (I am not familiar with node exception reading). Once I updated the npm-shrinkwrap to reference 1.0.10, the correct version of fibers was fetched and installed and the installation continued and completed.

However, when running `node main.js`, it crashes with this error:


```
Error: %1 is not a valid Win32 application.
\\?\C:\rocket.chat-0.22\programs\server\npm\npm-bcrypt\node_modules\bcrypt\build\Release\bcrypt_lib.node
```

After some searching, I decided to manually replace the bcrypt folder with a fresh copy (0.7.8 -> 0.8.5). I found nowhere to configure this, hence the manual replacement of the files.

I have also given a few details in this issue: 

#2501

**Comment by engelgabriel** [comment]
Meteor doens't support node v4.4.0 officially yet, because of this very issues. They make node v4 the default on Meteor 1.4

**Comment by engelgabriel** [comment]
https://forums.meteor.com/t/when-is-meteor-upgrading-node/17148
