### ISSUE TITLE
Chat text input improvementes

### ISSUE THREAD

**Issue by nevson** [RocketChat/Rocket.Chat#246]
When somebody starts typing a message then the text input jumps up by a few pixels as the information that somebody else is writting a message gets displayed. This can be very distracting in case you're also writing a message as then the text input jumps all the time up and down. Would it be possible to
  a.) statically reserve the space for this notification so that the layout doesn't change or
  b.) show this notification above the text input?

Secondly it would be awesome if you could debounce the emoji popup when typing e.g. `:)`. Because the popup appears / disappears so fast I initially thought that the whole screen is flickering but then I've noticed that this was the emoji popup which has been shown for a brief moment. Debouncing the popup by ~500ms should help already I guess so that the popup won't show up when writing quickly an emoji.

Last but not least, the ability the resize the text input via a handle would be awesome too :)

**Comment by mhkeller** [comment]
I'm not sure if this is the same problem but I sometimes get a flicker / bump when I send a new message. 
![rocket chat bug](https://cloud.githubusercontent.com/assets/498744/8459935/8c53e856-1fee-11e5-9624-ece9a52fab8e.gif)

**Comment by engelgabriel** [comment]
It is a problem. We are fixing it. Thanks! :)

**Comment by engelgabriel** [comment]
Depends on #253

**Comment by sampaiodiego** [comment]
related to #253 and fixed by #307
