### ISSUE TITLE
[BUG] No need of sidebar menu tooltip

### ISSUE THREAD

**Issue by Himanshu664** [RocketChat/Rocket.Chat#24604]
### Description:

No need of sidebar menu it makes things complicated.

### Steps to reproduce:

1.  Go to Sidebar Menu
2.  Click on Sidebar Menu

### Expected behavior:

https://user-images.githubusercontent.com/76220055/155529083-742a26da-b259-4e75-aded-b4235c32eead.mp4

### Actual behavior:

https://user-images.githubusercontent.com/76220055/155529077-fef6b8bc-bc5e-4403-aa5a-b48c4b2528f4.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.5.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.2
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by Shivansh2287** [comment]
hey can I work on this issue
