### ISSUE TITLE
Enter key doesn't work when logging in with 2FA

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [RocketChat/Rocket.Chat#24639]
### Description:

When logging in to your workspace, you may type in your email and password then press the Enter key to log in. However, with 2FA enabled on your account, you must move your mouse to click the "Verify" button in the 2FA window, as the Enter key does not trigger it.

### Steps to reproduce:

1. Progress to the screen where you enter your 2FA code to log in.
2. Try to press the Enter key to attempt to log in after having typed in your 2FA code.
3. Nothing happens as the Enter key is not bound to the "Verify" button.

### Expected behavior:

Pressing the Enter key with the 2FA code typed into the login screen checks the code and logs in the user. i.e. the same function as clicking the "Verify" button with the mouse.

### Actual behavior:

The Enter key has no effect.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.2
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.2
- MongoDB Version: 4.4.12 / wiredTiger

**Comment by ritikBhandari** [comment]
hi,
Can i work on this?
