### ISSUE TITLE
Discrepancy between docs and docker-compose

### ISSUE THREAD

**Issue by nhcarrigan** [RocketChat/Rocket.Chat#24636]
### Description:

This is a small thing, but saw this when looking in to MongoDB version bumps.

In the [documentation](https://docs.rocket.chat/quick-start/installing-and-updating/other-deployment-methods/manual-installation/extras/mongo-versions), the recommended MongoDB storage engine is `WiredTiger`. In the example [docker-compose file](https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml#L40) it appears to still be using the `mmapv1` storage engine.

Not sure if this is intentional, or if the docker-compose file should be updated to have parity with the docs.

**Comment by fdellwing** [comment]
There are multiple PR working on that exact topic.
