### ISSUE TITLE
Animated/GIF Avatars

### ISSUE THREAD

**Issue by 4GAP3** [RocketChat/Rocket.Chat#24638]
Is it possible to somehow have animated avatars in rocketchat in anyway? 

Thanks in advance for answering 😄

**Comment by hugocostadev** [comment]
Not right now :/ 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
