### ISSUE TITLE
503 Service Unavailable No server is available to handle this request.

### ISSUE THREAD

**Issue by RanabirChakraborty** [RocketChat/Rocket.Chat#24641]
From today morning 7 AM IST it's showing "503 Service Unavailable
No server is available to handle this request."

**Comment by yash-rajpal** [comment]
Please follow the bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines :- https://rocket.chat/docs/contributing/reporting-issues

There seems some sort of a problem in your Rocket.Chat deployment which is not directly related to a issue in Rocket.Chat, Its better to ask for help with this on our support forums - https://forums.rocket.chat/ as github is reserved for bugs. Thanks!
