### ISSUE TITLE
Add lines between each post

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#2465]
Discord have this really good feature with a line between each post between the users. It much easier for the eyes to see what text belongs to each post.

Would love to see this being implemented on Rocket Chat
![lines](https://cloud.githubusercontent.com/assets/17712562/13665112/08320a24-e6ab-11e5-9483-2db5feeb50c2.PNG)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
