### ISSUE TITLE
[BUG] Not Resetting User Avatar

### ISSUE THREAD

**Issue by nishant23122000** [RocketChat/Rocket.Chat#24655]
### Description

All fields reset when we click on the reset button but let's say the user changes the avatar, at that time we should also provide that reset feature there.

### Steps to reproduce:

1. Go to account/profile
2. Change user avatar
3. click reset without saving
4. It will not reset the user avatar
### Expected behavior:

When the user clicks the reset button, we should reset the user's avatar also.

### Actual behavior:

User avatar not resetting when we click on reset.

https://user-images.githubusercontent.com/53515714/156133632-9ed88c94-69c3-4399-b9af-784110f9d95a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: Windows 10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Shivansh2287** [comment]
can I work on this issue

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/) provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
