### ISSUE TITLE
need flash window on web when sending message or setting some functions?

### ISSUE THREAD

**Issue by gcrocky** [RocketChat/Rocket.Chat#24663]
why to flash window when sending message or setting some functions(like: select transfer ) ?

**Comment by hugocostadev** [comment]
Sorry, could you elaborate more on your question? And please, go to our other channel to ask it, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
