### ISSUE TITLE
oAuth with NextCloud dont works

### ISSUE THREAD

**Issue by mrfurquim** [RocketChat/Rocket.Chat#24662]
oAuth nextcloud dont login the call back url dont works
both servers use ldap protocol to log in

https://user-images.githubusercontent.com/80480722/156250845-14e83e3d-b956-4ff9-905c-0de49823c8b2.mp4

**Comment by debdutdeb** [comment]
Fixed in https://github.com/RocketChat/Rocket.Chat/pull/24476
