### ISSUE TITLE
Cannot open room with new LDAP user

### ISSUE THREAD

**Issue by jsdidierlaurent** [RocketChat/Rocket.Chat#24669]
### Description:

After a fresh rocket chat Update from 4.4.0 to 4.5.0
When i start a chat with new ldap user, i have "Room not found" message

### Steps to reproduce:

1. Adding new user in my Active Directory
2. Connect this account to RocketChat successfully
3. Trying to start chat with it

### Expected behavior:

Correctly starting a Room 

### Actual behavior:

![image](https://user-images.githubusercontent.com/11354381/156312990-a15f370c-06a3-4871-9257-15e2939234c0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: Ubuntu 16.04.6 LTS
- Deployment Method: Docker version 18.09.7, build 2d0083d
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3 (Embed by your Dockerfile)
- MongoDB Version: 4.2.17

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows / Linux

### Additional context

Everything was working fine in 4.4. And I can no longer rollback in 4.4 without having to rollback the data and I don't really want to lose 1 day of data.

The problem is the same when I start a chat with someone I've never spoken to. But if another user than me has already spoken to the person, everything works.

### Relevant logs:

Server Log
```
{"level":50,"time":"2022-03-02T07:14:43.300Z","pid":1,"hostname":"ae9e47d46816","name":"","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"}
{"level":50,"time":"2022-03-02T07:14:43.348Z","pid":1,"hostname":"ae9e47d46816","name":"","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"}
```

Client Log
```
{
    "isClientSafe": true,
    "error": "error-invalid-user",
    "reason": "Invalid user",
    "details": {
        "method": "createDirectMessage"
    },
    "message": "Invalid user [error-invalid-user]",
    "errorType": "Meteor.Error"
}
```

**Comment by ankar84** [comment]
@jsdidierlaurent Hey!
What if make a refresh (CTRL+R) right after room not found page appears?

**Comment by ankar84** [comment]
> Same error 🥲

Ok! But what if you try to DM that user **again** from directory or any other way?

**Comment by jsdidierlaurent** [comment]
Oh ! From DIrectory it works ! It's only broken when i'm using Search !

**Comment by jsdidierlaurent** [comment]
Hum, I spoke too soon. Using Directory fix my issue with user i try to talk. But i already have issue with other users ...
And Directory didn't work every time ...

And yes search = magnifying glass tool

**Comment by nickerber** [comment]
That's a very annoying issue! 
The issue, that one had to press CTRL + R after joining a direct message with a user the first time was very annoying. This new issue makes the process even more complicated. It is hard to tell our users how to proceed. 
We're currently evaluating the usage of rocketchat in an enterprise environment and this seems to be a showstopper.

Some more information from my side inspecting the Network tab in Chrome DevTools:
**From search (magnifying glass tool):**
(1) First try opening a direct message with an ldap user with whom I did not start a direct message yet:  

Call of _api/v1/method.call/getRoomByTypeAndName_
```
Request Payload: 
{
    "message": "{\"msg\":\"method\",\"id\":\"18\",\"method\":\"getRoomByTypeAndName\",\"params\":[\"d\",\"CHBSgNZoZkqF4SteF\"]}"
}

Response: {"message":"{\"msg\":\"result\",\"id\":\"18\",\"error\":{\"isClientSafe\":true,\"error\":\"error-invalid-room\",\"reason\":\"Invalid room\",\"details\":{\"method\":\"getRoomByTypeAndName\"},\"message\":\"Invalid room [error-invalid-room]\",\"errorType\":\"Meteor.Error\"}}","success":true}
```

Call of _api/v1/method.call/createDirectMessage_
```
Payload: 
{
    "message": "{\"msg\":\"method\",\"id\":\"19\",\"method\":\"createDirectMessage\",\"params\":[\"CHBSgNZoZkqF4SteF\"]}"
}

Response: 
{"message":"{\"msg\":\"result\",\"id\":\"19\",\"error\":{\"isClientSafe\":true,\"error\":\"error-invalid-user\",\"reason\":\"Invalid user\",\"details\":{\"method\":\"createDirectMessage\"},\"message\":\"Invalid user [error-invalid-user]\",\"errorType\":\"Meteor.Error\"}}","success":true}
```

(2) Second try opening a direct message, with the same user as in (1):
No api call, except: api/v1/method.call/license%3AgetModules

(3) After changing to another channel first and then repeating the steps in (1) the same api-calls as in (1) are performed.

**From directory:**
(1) First try opening a direct message with an ldap user with whom I did not start a direct message yet: 
Call of _api/v1/method.call/getRoomByTypeAndName_
```
Request Payload:
{
    "message": "{\"msg\":\"method\",\"id\":\"63\",\"method\":\"getRoomByTypeAndName\",\"params\":[\"d\",\"da\"]}"
}
Response:
{"message":"{\"msg\":\"result\",\"id\":\"63\",\"error\":{\"isClientSafe\":true,\"error\":\"error-invalid-room\",\"reason\":\"Invalid room\",\"details\":{\"method\":\"getRoomByTypeAndName\"},\"message\":\"Invalid room [error-invalid-room]\",\"errorType\":\"Meteor.Error\"}}","success":true}
```

Call of _api/v1/method.call/createDirectMessage_
```
Request Payload:
{
  "message": "{\"msg\":\"method\",\"id\":\"64\",\"method\":\"createDirectMessage\",\"params\":[\"da\"]}"
}
Response:
{"message":"{\"msg\":\"result\",\"id\":\"64\",\"result\":{\"t\":\"d\",\"rid\":\"CHBSgNZoZkqF4SteFm3FZKyD5zsJ6areLf\",\"usernames\":[\"Administrator1\",\"da\"]}}","success":true}
```

Call of _api/v1/method.call/getRoomByTypeAndName_
```
Request Payload:
{
  "message": "{\"msg\":\"method\",\"id\":\"65\",\"method\":\"getRoomByTypeAndName\",\"params\":[\"d\",\"CHBSgNZoZkqF4SteFm3FZKyD5zsJ6areLf\"]}"
}
Response:
{"message":"{\"msg\":\"result\",\"id\":\"65\",\"result\":{\"_id\":\"CHBSgNZoZkqF4SteFm3FZKyD5zsJ6areLf\",\"t\":\"d\",\"_updatedAt\":{\"$date\":1646216056057},\"default\":false,\"usersCount\":2,\"ro\":false,\"sysMes\":true,\"ts\":{\"$date\":1646216056054},\"usernames\":[\"Administrator1\",\"da\"],\"uids\":[\"CHBSgNZoZkqF4SteF\",\"m3FZKyD5zsJ6areLf\"]}}","success":true}
```

Result: Blank screen

(2) Refreshing by pressing CTRL + F3
Call of _api/v1/method.call/getRoomByTypeAndName_
```
Request Payload:
{
  "message": "{\"msg\":\"method\",\"id\":\"7\",\"method\":\"getRoomByTypeAndName\",\"params\":[\"d\",\"CHBSgNZoZkqF4SteFm3FZKyD5zsJ6areLf\"]}"
}
Response:
{"message":"{\"msg\":\"result\",\"id\":\"7\",\"result\":{\"_id\":\"CHBSgNZoZkqF4SteFm3FZKyD5zsJ6areLf\",\"t\":\"d\",\"_updatedAt\":{\"$date\":1646216056057},\"default\":false,\"usersCount\":2,\"ro\":false,\"sysMes\":true,\"ts\":{\"$date\":1646216056054},\"usernames\":[\"Administrator1\",\"da\"],\"uids\":[\"CHBSgNZoZkqF4SteF\",\"m3FZKyD5zsJ6areLf\"]}}","success":true}
```
Result: Direct message opens as expected

**Comment by ankar84** [comment]
> The issue, that one had to press CTRL + R after joining a direct message with a user the first time was very annoying. This new issue makes the process even more complicated. It is hard to tell our users how to proceed.

Totally agree with you!
Thank you for you detailed analysis!

@rodrigok @engelgabriel @milton-rucks hello!
Please check that issue.
Issues like that shows Rocket.Chat in bad way for community and customers.

**Comment by raczkow** [comment]
I've got this issue with local accounts.

**Comment by toantc** [comment]
We've got this issue with the Google OAuth account

**Comment by william00179** [comment]
We have this issue with SAML accounts
