### ISSUE TITLE
RocketChat upgrade to 4.5.0 fails

### ISSUE THREAD

**Issue by ShamimIslam** [RocketChat/Rocket.Chat#24665]
### Description:
1. Rocket chat running behind nginx proxy since Rocketchat does not force HTTPS redirect
2. 20.04.4 LTS (Focal Fossa)
3. Rocket chat v 4.4.0

### Steps to reproduce:

1. rocketchatctl upgrade-rocketchatctl (current version fails unary operator [)
2. rocketchatctl update 

OR 
1 follow manual instructions to upgrade (which does not result in the wrong version of node installed)

### Expected behavior:
Runs correct version of node and runs the system

### Actual behavior:
1. incorrect version of node installed (12.x instead of 14.x)
2. update to 14.x (n 14.18.2) and update in systemd unit allows startup
3. Attemping to access results in "bad gateway" response

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System:  20.04.4 LTS (Focal Fossa)
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ?? No replica
- NodeJS Version: 14.18.2 (keeps wanting to install 12.x on automated update)
- MongoDB Version: default version with first install on digital ocean

### Client Setup Information

- Desktop App or Browser Version: firefox (latest)
- Operating System: Fedora 35

### Relevant logs:
Not sure what to provide here - please provide some clarity on where and what to provide.
You can see this happen as well just by following the steps when running behind a proxy
Forced to restore via snapshot

**Comment by hugocostadev** [comment]
It was commented on the linked issue that it was fixed
