### ISSUE TITLE
Can not add user to chanel

### ISSUE THREAD

**Issue by redRolf** [RocketChat/Rocket.Chat#24673]
### Description:

When trying to add a user to a channel, only a subset of 10 users is offered for selection.

### Steps to reproduce:

1. create a private channel (the behaviour is not limited to private chanels, this is just as an example)
2. go to the user members menu
3. click on `Add`
4. Search for a user (only a subset 10 users will be displayed)

The same behavior can be observed when creating a new channel and trying to add a new user in the channel creation menue.

In both cases, the following request is sent to the server: `https://<your-endpoint>/api/v1/users.autocomplete?selector=%7B%22term%22%3A%22%22%7D`

This then only returns a subset of all users. That can be reproduced with the curl command below:

```
curl  -H 'X-Auth-Token: <your-token>' \
      -H 'X-User-Id: <your-id>' \
      -H "Content-type: application/json" \
      'https://<your-endpoint>/api/v1/users.autocomplete?selector=%7B%22term%22%3A%22%22%7D'
```

I suspect, that the cause may be this merge: https://github.com/RocketChat/Rocket.Chat/pull/24529

### Expected behavior:

* All users are displayed and or can be searched for

### Actual behavior:

* Only a subset of all users can be selected. 
### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: Docker (FCOS Host)
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 98.0.4758.109
- Operating System: MacOS

### Additional context

I am happy to provide any information that may be required. I have tried to limit the info here to what seemed relevant. 😇

**Comment by Bengrunt** [comment]
We experience the same issue with our 4.5.0 instances.

**Comment by redRolf** [comment]
@Bengrunt a temporary workaround is to:
1. Create the channel as intended, but not add anyone.
2. Add the desired people by sending the slash command: `/invite @username`

This works for public and private channels :)

**Comment by TimmiORG** [comment]
This should be something for 4.5.1 as this a quite basic feature which is heavily used.

**Comment by catalins95** [comment]
Hello
You have the same issue as me #24712
Possible fix by #24328
Try this fix please 😄 ❤️ and tell me if it is working.

On monday I will try it too.

Let me know please if u could solve it.

Best Regards,
Catalin.

**Comment by daniel-jettka** [comment]
> By the way, the issue affects discussions and direct messages as well. While the workaround mentioned by @redRolf works for discussions, it will not for direct messages since you can't create them. Resorting to "temporary" private channels seems to be the only alternative.

Temporary workaround for DMs: go to top menu "Directory", search for user, click on user entry - this will open a DM "channel"

**Comment by dudanogueira** [comment]
We have users in forums with the same error that sad it was fixed in 4.5.1

Can you guys confirm?

**Comment by TimmiORG** [comment]
Confirmed, working for me again with 4.5.1.

**Comment by amottier** [comment]
It is working again but, when trying to add a user, I get immediately (i.e. without any latency) a list of suggested users to add, if I start typing it will first filter users from this list and when my search no longer match a user in this initial list it displays "None" briefly (but feels not that brief), then "Loading" briefly and only then I get the user I was looking for. I would say that "it is working" but user experience is not perfect.

**Comment by billynoah** [comment]
@amottier - that was my experience as well.  It was reasonably fast to autocomplete but would be nice if there was a "Loading" message or something while it was performing the request, e.g., https://select2.org/data-sources/ajax

**Comment by dudanogueira** [comment]
Great feedback @amottier! Thanks!

As you probably know, we are refactoring a lot of components, and those nasty bugs are expected.
