### ISSUE TITLE
Use STARTTLS or SSL in SMTP settings

### ISSUE THREAD

**Issue by senthai** [RocketChat/Rocket.Chat#2468]
Hi,

is it possible to use STARTTLS or SSL/TLS in SMTP settings?
when running in docker I cant use localhost and external 25 is disabled.

thx

**Comment by engelgabriel** [comment]
Sure you can, see our own SMTP settings.

Make sure you SAVE the settings and RESTART your Rocket.Chat server after you update the config, this is a limitation of MeteorJS.

![image](https://cloud.githubusercontent.com/assets/1000217/13951847/fc0f3008-f011-11e5-8808-0e16f1ce4296.png)
