### ISSUE TITLE
Window Crashing

### ISSUE THREAD

**Issue by MercantilTI** [RocketChat/Rocket.Chat#24692]
![erro rocket chat](https://user-images.githubusercontent.com/100847863/156566791-e088b9df-35da-4ce2-a5a3-55db7951071b.png)
when I quickly click on different conversations, the rocket chat window crashes and is all black

**Comment by dudanogueira** [comment]
Can you get more logs from the server?

This is probably the API  Rate Limit kicking in.

Try increasing its throtle value in:
Admin > Rate Limiter

**Comment by Gummikavalier** [comment]
May be related so linking to this https://github.com/RocketChat/Rocket.Chat/issues/23555
