### ISSUE TITLE
flex column reverse with scrollbar work difference

### ISSUE THREAD

**Issue by devopg** [RocketChat/Rocket.Chat#24700]
Hello. I do not know who to turn to, there are almost no specialists in this field. But you should definitely know.

i have flex list with scroll. if i add new item to head then scrollbar position on top -> scrollbar remains on top and we see new element.

![image](https://user-images.githubusercontent.com/61819835/156740952-4b2b724b-df8a-42c4-8e6a-53283333877d.png)

Then i set reverse to flex column for it list. I expect the same behavior only from below.

But i get "jump" after add new element if i scroll up then scrolldown and press 'ADD' btn.

what is problem ? why scrollbar is not 'sticky' like as nornal column flex ?

![image](https://user-images.githubusercontent.com/61819835/156740981-42866496-a6a4-41da-b890-7907661c5a4e.png)

sandbox: https://codepen.io/shenkonor-mail-ru/pen/mdqveey[](https://i.stack.imgur.com/RZ2SO.gif)

Chrome 96 windows

```
<script src="https://cdn.tailwindcss.com"></script>

<div class="h-screen bg-teal-200 flex flex-col">
  <div class="h-20 flex-shrink-0 bg-indigo-400">header</div>
  <div class="flex-grow grid grid-cols-[300px_1fr] grid-rows-1 bg-green-200 min-h-0">
    <div>left short content</div>
    <div class="flex flex-col">
      <div id="list" class="flex-grow bg-rose-300 overflow-y-scroll flex flex-col-reverse">
      </div>
      <button id="btn" class="bg-fuchsia-800 rounded shadow">ADD</button>
    </div>
  </div>
  <div class="h-20 flex-shrink-0 bg-indigo-400">footer</div>
</div>

```

```
var btn = document.getElementById("btn");

let i = 1;

btn.onclick = function(event) {

 add()
}

function add(){
   var div = document.createElement("div");
   div.classList.add("h-60", "border", "border-black", "text-xl", "shrink-0");
  div.textContent += "ADDED " + i;
  i++;
   document.getElementById('list').prepend(div);
 // document.getElementById('list').append(div);
}

for (var z = 0; z < 6; z++) {
  add();
}
```

UPDATE 1: add video 

![image](https://i.stack.imgur.com/RZ2SO.gif)

**Comment by dev-medclans** [comment]
Hi,
I am facing similar issue.  Did you find solution?
I am using flex-direction:column-reverse for a chat application so that new messages show up at bottom. I am expecting scrollbar to stick to the bottom because of column-reverse and show new messages as they arrive. This is working fine in all platforms except iPhone.
In iPhone ( for all browsers - chrome, safari, mozilla) when new message comes in, scrollbar position is still yet previous message. New messages are not shown until I scroll manually.

**Comment by devopg** [comment]
@dev-medclans hi i didnt find solution :(((

**Comment by raidokulla** [comment]
Same problem, iOS, all browsers.

**Comment by ognyanK** [comment]
Same...

**Comment by omidgfx** [comment]
Same

**Comment by UninstallGame** [comment]
> Same problem, iOS, all browsers.

hi, you fix this problem?

**Comment by MartinSchoeler** [comment]
This is not related to Rocket.Chat at all, will be closing this issue.
