### ISSUE TITLE
Set STMP settings. Get "set the MAIL_URL environment variable" when attempting send

### ISSUE THREAD

**Issue by kjcsb1** [RocketChat/Rocket.Chat#2471]
Your Rocket.Chat version: 0.21.0

Deployed to Heroku. Set up smtp details in Settings > SMTP. But get error in logs "set the MAIL_URL environment variable". Any advice appreciated.

**Comment by andrewmartin00** [comment]
I'm seeing the same issue.

**Comment by marceloschmidt** [comment]
This is a problem with how Meteor sends e-mail. Let's try and make a PR for meteor to allow changing the SMTP server after a mail has been sent. Meteor's issue: https://github.com/meteor/meteor/issues/4323

**Comment by marceloschmidt** [comment]
For now, if you restart your server after making changes, it should work.

**Comment by marceloschmidt** [comment]
Let's see if Meteor accepts our PR https://github.com/meteor/meteor/pull/6698

**Comment by alexweissman** [comment]
Can we update the documentation about this at https://rocket.chat/docs/administrator-guides/email/?  I feel like that's probably doing more harm than good at this point.

**Comment by engelgabriel** [comment]
@alexweissman can you do a PR to update the documentation at https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/5.%20Administrator%20Guides/Email/README.md ?

**Comment by alexweissman** [comment]
@engelgabriel done!

**Comment by santhosh9** [comment]
Hello All,

I have configured an email in smtp, email is hosted at hostgator, all emails are going through to the emails that are hosted at hostgator, but none of the emails go to any of the gmail accounts, that is to the users that signed up with gmail accounts.

can someone help me solve this???

when I send an email directly from my hostgator email to the gmail account, it works but when an email is sent through rocket chat, it does show as sent but nothing goes to gmail and nothing can be found in gmail inbox or in the spam folder.

thanks!
