### ISSUE TITLE
Quoting Messages and Link Previews don't work when channels are E2E enabled and encryption is on

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#24721]
### Description:

After enabling E2E quoting and link previews of messages do not work anymore. 

### Steps to reproduce:

1. Enable and activate E2E 
2. Goto E2E enabled channel
3. Quote a message, enter text, send message
4. Quoted message doesn't show. 

5. Enter Link in message window and send it
6. Only the link appears, no preview of the link

### Expected behavior:

Quoting and Link Previews work in E2E enabled channels too.

### Actual behavior:

They don't.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.2 / 4.5.0
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: Sure
- NodeJS Version: 14
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Linux and MacOS

**Comment by lovekyleman** [comment]
Also have this issue

**Comment by KamilSucharski** [comment]
It's inconvenient - having to choose between security and functionality. Please fix this.

**Comment by fcharlaix-opendsi** [comment]
I can confirm the issue, is annoying to losses such functionality for security

**Comment by undallesoyeah** [comment]
It would be very cool to get an update on this open security issue. :)

**Comment by tobiasreinhard** [comment]
Now its almost mid of September 2022 and it's still not working. This is a core feature which was working without E2E, please fix this asap.
