### ISSUE TITLE
Hide url

### ISSUE THREAD

**Issue by dmidmi84** [RocketChat/Rocket.Chat#2472]
Hi! Is there any way to hide URL? As a sample now I can see complete url to direct chat `https://chat.domain.com/direct/test` It would be great to hide it `https://chat.domain.com/`

Your Rocket.Chat version: (0.21.0)

**Comment by IQ2022** [comment]
:+1:

**Comment by engelgabriel** [comment]
This is on porpoise, so you can send or save links to specific rooms or users. It is a design decision that cannot be changed.

**Comment by krsnaa** [comment]
that is a GOOD design decision.
