### ISSUE TITLE
An option to deactivate autocompletion

### ISSUE THREAD

**Issue by thiesschneider** [RocketChat/Rocket.Chat#2473]
Hi, 

it would be nice to be able to deactivate the autocomplete (for emojis) function in the settings.

thx :)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
