### ISSUE TITLE
Development Environment Error

### ISSUE THREAD

**Issue by ktsrivastava29** [RocketChat/Rocket.Chat#24735]
I'm unable to setup the Development Environment.
It says there's no index.html file

![Screenshot from 2022-03-08 14-48-46](https://user-images.githubusercontent.com/77936821/157208518-a2604f96-90c4-44bd-9d8d-67dce733b7b9.png)

**Comment by dudanogueira** [comment]
Hi @ktsrivastava29!

Please, refer to:
https://open.rocket.chat/channel/dev
for development questions

or
https://open.rocket.chat/channel/google-summer-of-code
if your are a Google Summer of Code participant.

Thanks!
