### ISSUE TITLE
Room name for direct message between multiple users display only a single user real name

### ISSUE THREAD

**Issue by amottier** [RocketChat/Rocket.Chat#24774]
### Description:

I'm using direct message with multiple users (usually a total of 3 users: 2 colleagues + myself). Usually the room name is a concatenation of other participant real name (option `UI_Use_Rel_Name` - Layout → User Interface → Use Real Name enabled).

But for a few (**not all of them**) direct message with multiple users the room name only include a single user real name. I cannot isolated anything specific to those room.

If I disable the `UI_Use_Rel_Name` - Layout → User Interface → Use Real Name option, I get the expect behavior, i.e.: all room are named with a comma separated list of usernames.

### Steps to reproduce:

Sadly I cannot currently try to reproduce it due to #24673 

### Expected behavior:

If I'm user John Smith `john.smith` and create a direct message with Jane Doe `jane.doe` and User One `user.one` I expect the room to be named:
- jane.doe, user.one if option `UI_Use_Rel_Name` is disabled (this is actually what I get, so this is working just fine)
- Jane Doe, User One if option `UI_Use_Rel_Name` is enable. This is what I get for some of my direct message to multiple users but not for all of them.

### Actual behavior:

With my example above the room would be named for example only Jane Doe (missing the second user real name)

On the screenshot below you can see the avatar with the number 3 as we are 3 in the direct message discussion but only one user real name (I blur the last name):
![screenshot direct message 3 users](https://user-images.githubusercontent.com/5032635/157408213-28bf464c-42f8-4059-952a-cf00da7effb0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.5 (reported initially on 4.5.0, might have been existing before that)
- Operating System: Debian GNU/Linux 10 (buster) on the server
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 5.0.5 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: tested both on desktop app 3.7.8 (on macOS) and in Firefox 91.6.1esr (64 bits) (on Linux)
- Operating System: macOS Big Sur 11.5.2 and Debian GNU/Linux 11 (bullseye)

### Additional context

Our instance is using our own GitLab for user authentication.

### Relevant logs:
No relevant logs.

**Comment by stefan-baranoff** [comment]
This also happened for us, but both with and without real user names enabled. The name of the room is different for different users. Some see the whole list while others see just a single user. For those who see a single user, it's not the same user.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
