### ISSUE TITLE
[BUG] Issue For Parsing Error Object Inside ToastMessage.

### ISSUE THREAD

**Issue by nishant23122000** [RocketChat/Rocket.Chat#24772]
### Description:

Firstly, When the user performs any action, Meteor will call any API method, and If any error occurs(while fetching data from a database or else any other reason). meteor will throw an error with Meteor. Error(),

Meteor.Error() return the object which contain `{error:'', details: }`, and we have function to parse this object inside :
https://github.com/RocketChat/Rocket.Chat/blob/develop/client/lib/utils/handleError.ts. (hasError(),hasDetails())

Secondly, If we throw custom error with new Error(), then it will return object {name:'', message:''}. So we have to handle that case also.

### Steps to reproduce:

There are many examples that help to understand this, for example,
1. Try to prune the message with 0 messages.
2. ToastMessage will show undefined

### Expected behavior:
So when we throw a custom error, we have to handle that case inside the handleError.js file,

From :
```

const hasMessage = (error: {}): error is { message: string } => 
        'error' in error && typeof (error as { message: unknown }).message === 'string';
```

To : 
```
const hasMessage = (error: {}): error is { message: string } =>
	'message' in error && typeof (error as { message: unknown }).message === 'string';
```
Becuse new Error() throws object contains `{name : '', message: ''}`.

### Actual behavior:

This ToastMessage will show undefined,
```
                    if (count < 1) {
				throw new Error(t('No_messages_found_to_prune'));
			}

			dispatchToastMessage({ type: 'success', message: `${count} ${t('messages_pruned')}` });
			closeModal();
			reset();
		} catch (error) {
			dispatchToastMessage({ type: 'error', message: error });
			closeModal();
		}
```
Because we are throwing custom Error.

### Server Setup Information:

- Version of Rocket.Chat Server:  4.5.0
- Operating System:  Windows 10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

How error handling work and what it return in object,

https://docs.meteor.com/api/methods.html#Meteor-Error
https://stackoverflow.com/questions/9156176/what-is-the-difference-between-throw-new-error-and-throw-someobject

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
