### ISSUE TITLE
Mapping keycloak groups to rocketchat channel

### ISSUE THREAD

**Issue by gregfr** [RocketChat/Rocket.Chat#24807]
Greetings

I've set up keycloak as "custom oauth" and  I can log in. I'd like to map groups to channel, so I can specify in keycloak which channels a user has access to.

The documentation here:
https://docs.rocket.chat/guides/administration/misc.-admin-guides/authentication/open-id-connect/keycloak
is missing images, but even with images from there:
https://github.com/RocketChat/Rocket.Chat/issues/15225

I had no success.

In the keycloak admin, in client scopes/evaluate, I can see the information in "generated user info":
`{
  "sub": "76fdfa9f-b4a0-4111-8db2-869536954dec",
  "email_verified": false,
  "roles": [
    "rocket-admin"
  ],
  "groups": [
    "my-channel"
  ],
  "preferred_username": "toto"
}`

What am I missing?

Thanks in advance

**Comment by dudanogueira** [comment]
Hi @gregfr 

Please, refer to https://open.rocket.chat/channel/support for support.

Also please consider this document about what features are available for CE:
https://docs.rocket.chat/guides/administration/identity-management-ee-vs-ce
