### ISSUE TITLE
The "App Defination Documentation" Link is not working

### ISSUE THREAD

**Issue by Rohan749** [RocketChat/Rocket.Chat#24818]
### Description:
On the Rocket-chat Devs website under Apps Engine -> Getting Started -> The Apps Engine CLI, the title: 'Extending the App class' has a link named: 'App Definition Documentation'. It's not working.

Link to Rocket.chat Devs: https://developer.rocket.chat/apps-engine/getting-started/rocket.chat-app-engine-cli
![Screenshot from 2022-03-14 09-26-39](https://user-images.githubusercontent.com/90546860/158102370-5013c3c4-2690-4792-9e38-640e71793175.png)

### Steps to reproduce:

1. Go to Rocket-chat Devs website: Apps Engine -> Getting Started -> The Apps Engine CLI.
2. In extending the app class, click on the link: App Definition Documentation.
3. The link says: File not found

### Expected behavior:

Expected to direct to the defined Link.

### Actual behavior:
![Screenshot from 2022-03-14 09-25-02](https://user-images.githubusercontent.com/90546860/158102259-955e8a6f-46e4-41cf-9829-59a48278eada.png)

**Comment by dudanogueira** [comment]
Is the correct link https://rocketchat.github.io/Rocket.Chat.Apps-engine/ ?

**Comment by dudanogueira** [comment]
Fix sent to documentation. It should sync soon. thanks!
