### ISSUE TITLE
User is automatically logged out after a certain amount of logins elsewhere

### ISSUE THREAD

**Issue by dmonn** [RocketChat/Rocket.Chat#24826]
### Description:

When logged into RocketChat, a user will automatically get logged out after a certain amount of logins e.g. via the API. E.g. when logged into a server and using REST API calls via https://github.com/jadolg/rocketchat_API, logouts can happen after just 20-25 requests.

### Steps to reproduce:

1. Log in to RocketChat server
2. Install API wrapper https://github.com/jadolg/rocketchat_API
3. Run this

```
import time
from rocketchat_API.rocketchat import RocketChat

rocket = RocketChat(USER_ID, PASS, server_url=CHAT_URL)
while True:
    rocket.chat_get_message(SOME_MESSAGE_ID)  # happens with anything
   time.sleep(1)
```

Logouts will happen 60-90 seconds after script starts running. The REST API keeps working, but the web session is logged out.

This is an example, but a real life situation we're running in by using webhooks to have some follow-up actions for new messages. 

### Expected behavior:

There's no reason to believe that the current session gets logged out due to this or there should be a settings.

### Actual behavior:

User gets logged out.

### Server Setup Information:

![Screenshot 2022-03-14 at 16 59 26](https://user-images.githubusercontent.com/6407031/158214840-dc8f7248-3508-4700-a7d5-6a62e6c3f77c.png)

### Client Setup Information

- Desktop App or Browser Version: Chrome 99

### Additional context

![Screenshot 2022-03-14 at 17 17 20](https://user-images.githubusercontent.com/6407031/158215145-53ddf481-dca6-4a8c-b5b6-e39295a2b234.png)

Rate Limiter is set to 1000 requests per second, should be comfortable.

**Comment by dmonn** [comment]
Hey @sampaiodiego Kudos, this works amazing with the PATs. Issue solved.

Just to be 100% sure, these tokens **never** expire? Even on server restart / updates they'd persist? How many active PATs can a user have? Haven't found docs around this.

**Comment by sampaiodiego** [comment]
great to hear it worked @dmonn 😄 

no, PATs are persisted, they don't expire and are technically unlimited, I mean, there is no limit on the code, but having too many may degrade system performance.

**Comment by dmonn** [comment]
Hey @sampaiodiego 

We just had a short downtime because every single PAT was invalidated at once. What are scenarios where this could happen? We didn't update/upgrade, didn't play around with settings, it just happened 'by itself'.

**Comment by dmonn** [comment]
Does 'Login Expiration' have anything to do with this here? We migrated these users that tried out the beta about 7 days ago. The Login Expiration was set to 7 days too....

**Comment by sampaiodiego** [comment]
that's weird.. no, PATs are not invalidated/removed based on Login Expiration setting.. 

I've found a few actions that cause all login tokens to be removed though (including PATs):

- endpoint `/api/v1/users.resetTOTP`
- endpoint `/api/v1/users.resetE2EKey`
- endpoint `/api/v1/users.logout`
- Deactivate a user

**Comment by dmonn** [comment]
No worries, keeping an eye out.

That being said, are there some situations where `/api/v1/users.logout` is called by the system? We had a brief period where our iframe integration would send `Custom_Script_Logged_Out` without us doing anything, but it happened to solve itself.

**Comment by dmonn** [comment]
Hey @sampaiodiego might be related https://github.com/RocketChat/Rocket.Chat/issues/25091
