### ISSUE TITLE
Add a message that email verification is required for email notifications to work

### ISSUE THREAD

**Issue by rm234179** [RocketChat/Rocket.Chat#2483]
Your Rocket.Chat version: "version": "0.21.0"

Note this was an upgrade of an existing install.

I cannot get email notifications to work.  I have tried setting both the setting in My Account >> Preferences and in the per channel notifications.

![screen shot 2016-03-11 at 4 04 18 pm](https://cloud.githubusercontent.com/assets/6712253/13717993/f34f5e10-e7a2-11e5-8786-c12a084cfdba.png)

![screen shot 2016-03-11 at 4 05 34 pm](https://cloud.githubusercontent.com/assets/6712253/13718016/20973a32-e7a3-11e5-89b7-fa45c57ddefe.png)

Other notifications are working (e.g. push to android and iphone).  Also SMTP is working as verified by "SEND A TEST EMAIL TO MY USER".

**Comment by vitamindck** [comment]
I ran into the same issue and found that the account I was trying to test with did not have the email "Verified"

Once I verified it, the emails were sent as expected. There was no notification in the log as to why the email was not sent.

**Comment by rm234179** [comment]
@vitamindck Thank you for the answer.  I was able to get the offline email notifications to work after I turned on email verification.

It might be helpful to add a message that states that email verification is required for the feature to work.
