### ISSUE TITLE
Help! Problem of connecting to server

### ISSUE THREAD

**Issue by kuryachiyandreysergeevich** [RocketChat/Rocket.Chat#24841]
![image](https://user-images.githubusercontent.com/13069420/158552132-9f21d32c-6b8c-4ae4-a5fa-46b9741d6dec.png)

account already connected!

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
