### ISSUE TITLE
Start chat doesn´t work

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#24842]
### Description:

 If I look for a user in the search bar and click on them to start the chat, I get the error message "Room can´t found". 
![Bild_2022-03-16_103358](https://user-images.githubusercontent.com/67680741/158560068-c9465d38-dda2-462b-b8d8-3c542aee79e8.png)

### Steps to reproduce:

1.  Look for a user in search bar
2.  Click on user to start the chat
3.  the error message occurs

### Expected behavior:

The chat room will be open and you can start the chat with the user. 

### Actual behavior:

The chat can´t open. 

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.2
- Operating System: Ubuntu 18
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.17

### Client Setup Information

- Desktop App or Browser Version: Error occurs in Desktop App and at Browser
- Operating System: Windows 11, Google Chrome Browser

**Comment by dudanogueira** [comment]
duplicated: https://github.com/RocketChat/Rocket.Chat/issues/24727
