### ISSUE TITLE
Extra highlight words do not create a mark in the scrollbar region

### ISSUE THREAD

**Issue by edwardmuel** [RocketChat/Rocket.Chat#2485]
Your Rocket.Chat version: 0.21.0 (deployed through Docker)

`@mentions` create a colored mark in Rocket.Chat's scrollbar region. The configurable extra highlight words do not.

![image](https://cloud.githubusercontent.com/assets/15653318/13724365/a5a7ce44-e848-11e5-8fe4-b9f18ddc4dcf.png)

**Comment by thomasharrick** [comment]
Question: can you send me detailed instructions with how to deploy to Docker?

**Comment by geekgonecrazy** [comment]
@thomasharrick that's offtopic for this issue... Please check our documentation: https://rocket.chat/docs/Rocket.Chat.Docs/master/deployment-docker-nginx-ssl-hubot or reach out on https://demo.rocket.chat/channel/support

@edwardmuel That would be a nice thing to have.

**Comment by timkinnane** [comment]
Closing this now as the search features and UI have much improved since the issue was created.
