### ISSUE TITLE
Multiple Broken Links

### ISSUE THREAD

**Issue by Rohan749** [RocketChat/Rocket.Chat#24852]
### Description:

In Rocket.chat Devs Website, under Apps Engine -> Adding Features -> Schedular APIs has a section Permissions which contains 2 links: "Permission System" link and the "Schedular API needs the following permission" link. Both of them are not working. 

![Screenshot from 2022-03-17 08-50-10](https://user-images.githubusercontent.com/90546860/158730208-f91ce415-feb6-4757-aafb-b744faba683e.png)

Link to the Schedular API: https://developer.rocket.chat/apps-engine/fundamentals-of-apps/scheduler-api

### Steps to reproduce:

1. Go to Rocket.chat Devs Website, under Apps Engine -> Adding Features -> Schedular APIs
2. Click on "Permission System" link and the "Schedular API needs the following permission" link.
3. The redirected page could not be found.

### Expected behavior:

Should redirect to the required page

### Actual behavior:

![Screenshot from 2022-03-17 08-37-52](https://user-images.githubusercontent.com/90546860/158729819-bfe53e2f-80a7-4eb8-b2c2-6aa6a1fa4d44.png)
The same behavior in the "Schedular API needs the following permission" link.

**Comment by hugocostadev** [comment]
We are improving our docs and we will get more attention to that, thanks!
