### ISSUE TITLE
Highlight words - Visual inconsistency

### ISSUE THREAD

**Issue by edwardmuel** [RocketChat/Rocket.Chat#2486]
Your Rocket.Chat version: 0.21.0 (deployed through Docker)

`@mentions` have bolded text and a rounded background. Extra highlight words currently look out of place.

![image](https://cloud.githubusercontent.com/assets/15653318/13724365/a5a7ce44-e848-11e5-8fe4-b9f18ddc4dcf.png)

**Comment by geekgonecrazy** [comment]
It is a bit inconsistant.  I don't know that we would want to give them the same styling as a mention, because they are not the same.  But it could use some improvement in styling
