### ISSUE TITLE
[BUG] Two Jump to message button when message is starred

### ISSUE THREAD

**Issue by Himanshu664** [RocketChat/Rocket.Chat#24861]
### Description:
Two jump to message button is show when message in thread is starred

### Steps to reproduce:

1. Go to room
2. Click on thread
3. Star a thread message
4. Jump to Message is showing twice

### Expected behavior:

https://user-images.githubusercontent.com/76220055/158846023-609e82b1-a030-48ac-aae7-19b5b0b8ae3c.mp4

### Actual behavior:

https://user-images.githubusercontent.com/76220055/158846008-c3c7efb9-69b0-4fac-9cda-7235ebe3253b.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.5.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.3
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by dudanogueira** [comment]
Duplicated: https://github.com/RocketChat/Rocket.Chat/issues/23951
