### ISSUE TITLE
@mentions - Do not require the at symbol

### ISSUE THREAD

**Issue by edwardmuel** [RocketChat/Rocket.Chat#2487]
Your Rocket.Chat version: 0.21.0 (deployed through Docker)

Currently, `@mentions` require the at symbol to be detected as a highlight.
Directly mentioning the name with or without at should trigger a highlight.

![image](https://cloud.githubusercontent.com/assets/15653318/13724365/a5a7ce44-e848-11e5-8fe4-b9f18ddc4dcf.png)

**Comment by geekgonecrazy** [comment]
I don't know that I agree with this.  I think this is exactly the reason the highlight support was added.  So that if you wanted to be highlighted with out the `@` in front of your username.

**Comment by engelgabriel** [comment]
I agree with @geekgonecrazy, and if all users wanted to be highlighted without @, it would be very a expensive regex for the server to run on every message.
