### ISSUE TITLE
Extra highlight words - Overrides @mentions, breaks @mention username links

### ISSUE THREAD

**Issue by edwardmuel** [RocketChat/Rocket.Chat#2488]
Your Rocket.Chat version: 0.21.0 (deployed through Docker)

If you have your username added as an extra highlight words (a workaround to #2487), it overrides `@mentions`
Username linking is also broken by this.

![image](https://cloud.githubusercontent.com/assets/15653318/13724419/bafa803c-e84a-11e5-95e7-c3bee3107ccf.png)

**Comment by geekgonecrazy** [comment]
mentions should for sure be ran first before highlighting.

**Comment by Hudell** [comment]
This problem was fixed at some point, as it doesn't happen in the current version.
