### ISSUE TITLE
Clicking on message box redirects to another page

### ISSUE THREAD

**Issue by akgupta0777** [RocketChat/Rocket.Chat#24891]
### Description:

Clicking on message box in private channels redirects to another page

### Steps to reproduce:

1. Create a private channel with no member only you.
2. Click on message box to type message.
3. You will be redirected to another channel page in my case gsoc-2022

### Expected behavior:

Redirection doesn't happen on clicking messageboxes

### Actual behavior:

https://user-images.githubusercontent.com/51379307/159173285-bcd0b087-ad5b-48c1-9796-45937d35b509.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: Rocket.chat web
- Operating System: Windows 11 Home 21H2
- Deployment Method:  none used web app
- Number of Running Instances: none
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: Chrome latest
- Operating System: Microsoft windows 11 home 21H2

**Comment by Gummikavalier** [comment]
I cannot reproduce this as reliably, but I have seen it happen on RC 4.5.2 sometimes just after moving between few channels.
