### ISSUE TITLE
Overriding global retention policy in channel settings does not work

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#24894]
### Description:

Channel specific overriding of the global message retention policy does not work.

### Steps to reproduce:

1. Enable Global Retention Policy under Administrator settings and set it for one year.
![Screenshot from 2022-03-21 09-49-23](https://user-images.githubusercontent.com/6958942/159221753-c9c1bd2c-7384-42b4-8bbe-57fc549fae10.png)

2. As an admin go to any single channel settings and override the global retention policy with a shorter time.
![Screenshot from 2022-03-21 09-51-44](https://user-images.githubusercontent.com/6958942/159222016-5d03bc4c-c913-42a0-aac8-a71b207a97a2.png)

### Expected behavior:

After the specified time of days in the channel settings the messages should get pruned from the modified channel.

### Actual behavior:

After the specified time of days the messages still remain on the channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.2
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.18.3
- MongoDB Version: 4.2

**Comment by Gummikavalier** [comment]
It is also not possible to set the pruning time longer than the default global policy. After saving the new channel retention time, it just resets back to the the global default next time you check under the channel settings.

**Comment by jaluoto** [comment]
Hoping for a fix to this. It's currently blocking Slack to RC migration for a collaboration network that requires longer retention policy than the global setting.

**Comment by Rollbacke** [comment]
The thing that is weird is that it says "Room modified", but when you go back there, nothing has changed.
If the retention time of the channel is greater than the global one, it does not change anything.
On the other hand, shorter, it works (tested in 3.18.3 and 5.1.2).

**Comment by Gummikavalier** [comment]
My last test with 5.1.3 I was able to set the retention time from global 30 days to 3 days on a specific channel only by turning the global retention time off. Then the setting gets saved on the channel. But after turning the global retention time back on, the channel specific retention time is not respected and any messages linger there all that 30 days.

**Comment by Gummikavalier** [comment]
This is still an issue. In RC 6.4.8 it is not possible to create a new channel based retention policy for any channel at all.

The error message is:
![Screenshot from 2023-12-05 09-41-46](https://github.com/RocketChat/Rocket.Chat/assets/6958942/93755027-bc68-40ae-a276-6e553aa02ff6)

Admin account gets this error and has `Edit Room's Retention Policy` privilege.

**Comment by Gummikavalier** [comment]
As a workaround you can activate channel based custom pruning by running in the mongo database:
```
db.rocketchat_room.update({fname:'yourchannelname'}, {$set: {'retention.overrideGlobal' : true} }, {multi:true});
```
and then changing the settings normally.

**Comment by sandrotanner** [comment]
It seems the error happens while validating the room settings before saving them:
https://github.com/RocketChat/Rocket.Chat/commit/d48a70f43fa14165c665383fbfa43bf27ecd024f#diff-e6f4d9f644eb975d808c71b73c67ffdf9e5ce8c6e84720596162fd5d56a7c3f4L102 

I think it would fix the error if `hasRetentionPolicy()` checked not only for local but also global retention policy...
Here: 
https://github.com/RocketChat/Rocket.Chat/commit/d48a70f43fa14165c665383fbfa43bf27ecd024f#diff-e6f4d9f644eb975d808c71b73c67ffdf9e5ce8c6e84720596162fd5d56a7c3f4L49

Or just removing the check alltogether. Maybe @tassoevan can give us some insights into why the check is there? What was the idea of that? Or phrased differently: why would saving a retentionPolicy when there is no retentionPolicy present yet be invalid?

**Comment by panic2k** [comment]
Hopefully this issue would be resolved sometimes 🫠

**Comment by dougfabris** [comment]
> This is still an issue. In RC 6.4.8 it is not possible to create a new channel based retention policy for any channel at all.
> 
> The error message is: ![Screenshot from 2023-12-05 09-41-46](https://private-user-images.githubusercontent.com/6958942/287961124-93755027-bc68-40ae-a276-6e553aa02ff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTQ3NTUsIm5iZiI6MTcxNjIxNDQ1NSwicGF0aCI6Ii82OTU4OTQyLzI4Nzk2MTEyNC05Mzc1NTAyNy1iYzY4LTQwYWUtYTI3Ni02ZTU1M2FhMDJmZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTQxNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ0MzZiNDk0YzQ4YmVkM2YzYjZhMWNjMjYxMmFmMzI4YWZmNmMzMWY1ZjNhMjc3ZDVkYjg2OWZhZGQwOGQ1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tBxl2H6qfsWN-wORcYFPJDVmQZsJ8HpLCn74ffwNKjA)
> 
> Admin account gets this error and has `Edit Room's Retention Policy` privilege.
> 
> If the retention policy already exists in the channel, it is still possible to edit it.

@Gummikavalier related to this specific one, we're going to fix here: #32454

**Comment by Gummikavalier** [comment]
@dougfabris Whee, thanks a lot! :heart: :hugs:

**Comment by dougfabris** [comment]
Actually it solves the issue entirely, if you have any chance to test would be really appreciated!

Closing this one!

**Comment by Gummikavalier** [comment]
Thanks! I will test it when 6.9.0 release version. Usually the release candidates are too spicy for me. :hot_face: 

Then again, RC stands for release candidate. :grin:
