### ISSUE TITLE
Create UI to edit the Subscription object / channel settings

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#249]
Maybe the link would be a COG beside the room name at the top. It would open the right flex bar with the setting for the room and your subscription for the room too.

**Comment by marceloschmidt** [comment]
+1

**Comment by marceloschmidt** [comment]
This can be closed in favor of more specific issues https://github.com/RocketChat/Rocket.Chat/labels/feat%3A%20channel%20settings
