### ISSUE TITLE
Automatic User Creation

### ISSUE THREAD

**Issue by ChrisJBurns** [RocketChat/Rocket.Chat#24912]
We are currently setting up RocketChat, and we were hoping that with RocketChat being installed and setup, alongside it, it would create some bot accounts (in our case just one). Is this possible via configuration options? Or is it a manual process where someone has to run a script to hit an API to do it - or even do it manually via the RocketChat UI?

**Comment by ankar84** [comment]
> Or is it a manual process where someone has to run a script to hit an API to do it

Yes, you can create users in scripts via REST API or if you have LDAP, you can integrate it and users will generated from LDAP.
