### ISSUE TITLE
livechat:registerGuest api not working with RC version 4.5.2

### ISSUE THREAD

**Issue by Elintondm** [RocketChat/Rocket.Chat#24918]
When we call the livechat:registerGuest in the realtime API we didn't get any response.

Using Rocketchat 4.3.2 everything works fine.

### Server Setup Information:

Implantação
Versão
4.5.2
ID da Implantação
Noq4BacoMR5uivnhe
Versão da Apps Engine
1.31.0
Versão do Node
v14.18.3
Migração de Banco de Dados
256 (23 de Março de 2022 às 11:17)
MongoDB
4.2.8 / wiredTiger (oplog Ativado)
Detalhes do Commit
HEAD: (ed2cb3fe6)
Branch: HEAD
PID
1

**Comment by dudanogueira** [comment]
Hi! Can you provide a curl command or the piece of code you are calling this API?

Thanks!

**Comment by Elintondm** [comment]
Hi,

I don't know how to generate a curl due it is a websocket API. I use this library to https://github.com/daniel-sc/rocketchat-modern-client to send API requests and it is working fine with a lot of versions, except this: 4.3.2

**Comment by Elintondm** [comment]
Another information: this rocketchat is cloud hosted at oficial rocketchat service.

**Comment by Elintondm** [comment]
I think this could by a proxy or firewall error due my requests doesn't receive any response.

**Comment by dudanogueira** [comment]
This could be an error on the library rather then on the server. Maybe the API had some change that is no longer implemented on the library.

I suggest you testing the API on the server directly and then checking the library itself.

**Comment by dudanogueira** [comment]
closing as this is probably on the library side.
