### ISSUE TITLE
[Markdown] Links in brackets

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#24929]
### Description:

There is an issue with links surrounded with brackets.
Example with brackets:
![image](https://user-images.githubusercontent.com/50440047/159917219-b8af8b05-03e4-4b8a-9ec1-8275d91591da.png)
![image](https://user-images.githubusercontent.com/50440047/159917262-3ccaca1d-8950-4b18-994e-323e88358277.png)

Example without brackets:
![image](https://user-images.githubusercontent.com/50440047/159917372-6da712e0-0263-40fb-befe-04e8f13c26bb.png)
![image](https://user-images.githubusercontent.com/50440047/159917404-56f264c3-0a6e-47a2-a682-1b56997e28d1.png)

### Steps to reproduce:

1. Check examples described above.

### Expected behavior:

Link surrounded by brackets is parsed correct. 

### Actual behavior:

Incorrect parsed link

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.3
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 9
- DB Replicaset Oplog: YES
- NodeJS Version: v12.22.8
- MongoDB Version: 4.2.19 

### Client Setup Information

- Desktop App or Browser Version: all
- Operating System: all

**Comment by fdellwing** [comment]
It's like this for ages. Only workaround I found is to add an extra space.

**Comment by dusatvoj** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/27484#issuecomment-1359334117

**Comment by Toledodev** [comment]
Hey @emikolajczak, This error is not happening on my machine
![Screensho
![Screenshot_3](https://user-images.githubusercontent.com/87545086/209990019-1f1237bd-6a32-4975-b9f4-48d78cc06371.png)
t_4](https://user-images.githubusercontent.com/87545086/209990016-92daa92c-8f73-44cb-8e39-8f00f7fbc327.png)

**Comment by dusatvoj** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/26580#issuecomment-1377184693

**Comment by hugocostadev** [comment]
This specific issue it was fixed in the last release
