### ISSUE TITLE
[BUG] Changing Password Field is confusing

### ISSUE THREAD

**Issue by himanshumalviya664** [RocketChat/Rocket.Chat#24927]
### Description:
Changing password is confusing

### Steps to reproduce:

1.Go to My Account
2. Check password field name

### Expected behavior:

![After](https://user-images.githubusercontent.com/76220055/159909166-899ec6b6-1ee9-4ff0-b859-41e8b9698745.png)

### Actual behavior:

![Before](https://user-images.githubusercontent.com/76220055/159909171-434914fe-f809-40b3-99ab-394b0c0104b2.png)

### Server Setup Information:
Version of Rocket.Chat Server: 4.6.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.3
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by hugocostadev** [comment]
We are improving this and it's already better, thanks for your feedback

PR that improves the feature: https://github.com/RocketChat/Rocket.Chat/pull/29322
