### ISSUE TITLE
Batch user import/management and department tree feature

### ISSUE THREAD

**Issue by yumben-yf** [RocketChat/Rocket.Chat#2493]
For rocket.chat to be used as an internal communication platform within a company, I think two features are needed:

1. Batch user Management
    for example, import/create users from a .csv file or some external database

2. Add a "Users & Organization" section to the left panel, which contains something like a department **tree** where **ALL** users is listed and sorted into different departments(as they are in different departments of the company). 
Also, a phone number field for the user info page would be very convenient.

**Comment by engelgabriel** [comment]
Hi, please break this feature request into two issues, as they are distinctive works.

**Comment by yumben-yf** [comment]
Hi, @engelgabriel 
I broke it down into 2 issues:
#2508
#2509

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (453/400 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:36774)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1afmWu-000cw9-PZ
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:48:54 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=4Y9H+4t9WnocQWTbTYn1KSGVtRg=; b=YKdAwG74jHAojXui
	psVC6emlq6vwNaQwLtST1bQ5hSzuA7aW8XcMNfReoqcYigtkLoUWaKke0Lf0DR21
	6yqTHDEJzi3XmVZL1LWy/0DxysDYCD/14SHeiG9sz5eU9qkfTOhaVYswZc5Aa6Zz
	AnXjNORSjDXJSTu/qGtc+FsUBDE=
Received: by filter0434p1mdw1.sendgrid.net with SMTP id filter0434p1mdw1.29328.56E7E8603D
        2016-03-15 10:48:00.957095403 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id GCeQDhkSSSe-cVZrbujOww
	for <yann.dupuy@zyapps.com>; Tue, 15 Mar 2016 10:48:00.842 +0000 (UTC)
Date: Tue, 15 Mar 2016 03:48:00 -0700
