### ISSUE TITLE
[BUG] Typo when 1 message is pruned

### ISSUE THREAD

**Issue by himanshumalviya15** [RocketChat/Rocket.Chat#24940]
### Description:

when 1 message is pruned it shows "1 messages pruned" it should show "1 message pruned"
### Steps to reproduce:

1. Go to room
2. Click on prune message
3. prune only 1 message

### Expected behavior:

https://user-images.githubusercontent.com/76220055/160060660-6fb073df-aa36-4129-9b25-7fd46dcaf77a.mp4

### Actual behavior:

https://user-images.githubusercontent.com/76220055/160060669-a0f954af-77e0-49cf-8ecb-1a1ce440c7ad.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.6.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.3
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest version and it was fixed here: #24940

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
