### ISSUE TITLE
docker build error..

### ISSUE THREAD

**Issue by hktalent** [RocketChat/Rocket.Chat#24944]
docker build -f .docker/Dockerfile .
=> ERROR [4/5] RUN aptMark="$(apt-mark showmanual)" && apt-get install -y --no-install-recommends g++ make python ca-certificates && cd /app/bundle/programs/server && npm insta 23.8s

https://github.com/webrtc/samples/pull/8 23.53 /bin/sh: 1: cd: can't cd to /app/bundle/programs/server

executor failed running [/bin/sh -c aptMark="$(apt-mark showmanual)" && apt-get install -y --no-install-recommends g++ make python ca-certificates && cd /app/bundle/programs/server && npm install && apt-mark auto '.*' > /dev/null && apt-mark manual $aptMark > /dev/null && find /usr/local -type f -executable -exec ldd '{}' ';' | awk '/=>/ { print $(NF-1) }' | sort -u | xargs -r dpkg-query --search | cut -d: -f1 | sort -u | xargs -r apt-mark manual && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false && npm cache clear --force]: exit code: 2

**Comment by BaezCrdrm** [comment]
You can fix it by changing the Dockerfile with the latest[ v14 bullseye-slim image](https://github.com/nodejs/docker-node/blob/6e8f32de3f620833e563e9f2b427d50055783801/14/bullseye-slim/Dockerfile).

Replace with `FROM node:14-bullseye-slim`
https://github.com/RocketChat/Rocket.Chat/blob/083775f74e34b04eee0d42b7b14ea35cbb115378/.docker/Dockerfile#L1
