### ISSUE TITLE
API users.create

### ISSUE THREAD

**Issue by wangcc57** [RocketChat/Rocket.Chat#24954]
install Rocket.Chat server by docker, https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml
call the API users.create by curl, still timeout, but the user be created success.

I have called this API by Postman, but still timeout.

other APIs can be call normally

[root@iZwz9ee5ye356hitr5k9okZ ~]# curl -H "X-Auth-Token: Ro3TxvYieJH4OqyKTlaznvHqlABjrRhQf84fPyRXfVW" \
 -H "X-User-Id: jGAmPLygEzsFvnsK4" \
 -H "Content-type:application/json" \
 http://localhost:3000/api/v1/users.create \
 -d '{"name": "2222", "email": "2222@user.tld", "password": "22222222", "username": "2222"}'
curl: (52) Empty reply from server

**Comment by LMjava2017** [comment]
Try going to admin->account->avatar and toggling "set default avatar" option off.

**Comment by wangcc57** [comment]
thanks，solved my issue
