### ISSUE TITLE
Impossible to hover cursor on the edit mark icon of the messages next to the first

### ISSUE THREAD

**Issue by Kyogre** [RocketChat/Rocket.Chat#24962]
### Description:

It is impossible to hover cursor on the pencil icon of the edited messages, underneath the first message.

### Steps to reproduce:

1. User send 2 (or more) message in a row.
2. Somebody (same user or moderator) edits the second message.
3. User tries to hover cursor on the pencil icon, but the icon disappears.

### Expected behavior:

User can hover cursor on the edit mark icon of the second (and next) message.

### Actual behavior:

User can't see who and when edited any of his messages. On the subsequent messages, grouped, there is no way of showing the edit mark icon.
Video demo: https://user-images.githubusercontent.com/2260980/160235618-66b32e60-f17c-4d9d-96b7-351187b409f2.mp4

### Server Setup Information:

Tried on https://open.rocket.chat/

### Additional context

Discussed here: https://forums.rocket.chat/t/impossible-to-hover-cursor-on-the-edit-mark-icon-of-the-messages-next-to-first/13664

**Comment by aakash-gitdev** [comment]
Hey I am still trying to understand the codebase. Can you help me out with finding the relevant code directory for this issue?  Will be a great help! I want to work on this issue.

**Comment by Dnouv** [comment]
Hello @aakash-gitdev 
Are you still working on this issue? Just confirming, if you are, then please let me know.
Thank you!

**Comment by aakash-gitdev** [comment]
Right now my university examinations are going on. But after they get over I will continue with this.

**Comment by Kyogre** [comment]
I haven't tested it yet, but maybe it is fixed in https://github.com/RocketChat/Rocket.Chat/pull/24984 ?
