### ISSUE TITLE
private group cannot response the hubot command, how can I set the environment

### ISSUE THREAD

**Issue by zb471914758** [RocketChat/Rocket.Chat#2496]
export ROCKETCHAT_ROOM=''
export LISTEN_ON_ALL_PUBLIC=true

I get the help information on  https://github.com/RocketChat/hubot-rocketchat
the LISTEN_ON_ALL_PUBLIC can work on private groups, as below picture

![listen on all public](https://cloud.githubusercontent.com/assets/17021819/13738655/6bceded2-ea01-11e5-92c3-b73f89d1e26e.png)

when I execute  bin/hubot -a rocketchat, 

all the public channels can get the hubot response(eg. hubot time) , but the private group can't response, 
do you know why? Or is there something else to be set?

**Comment by engelgabriel** [comment]
Did you invite the hubot user to the private channel?

**Comment by geekgonecrazy** [comment]
@zb471914758 

That environment variable might be a bit misleading.  Pretty much it lets it respond to any messages for rooms its in.  If you mention the bot in a public room he is added to the room, then able to respond.  This isn't the case for private groups.

So for private groups you have to explicitly add the bot.

> IMPORTANT NOTE: This option also allows the bot to listen and respond to messages from all newly created private groups that ***the bot's user has been added as a member.***

**Comment by zb471914758** [comment]
yes, it's ok, that is the reason. Thanks
