### ISSUE TITLE
LDAP Sync failing for users with non alphanumeric chars in username (Resaon: not slugifying username for sync)

### ISSUE THREAD

**Issue by Turbocube644** [RocketChat/Rocket.Chat#24972]
Bug probably introduced in PR #23171 (Refactoring of LDAP for Rocket.Chat 4.0)
Problem: The LDAP sync fails for users where the combined username (e.g. LDAP_Username_Field = "#{givenName}.#{sn}") contains non alphanumeric letters. This is true for spaces in the last name (more or less common in europe) as well as german umlauts in any of the names.
As another symptom we noticed the usernames are no longer lowercased since Version 4.0. (This indicates that the name ist not slugified as before)

Digging through the code, I think the error is in the following line in the function mapUserData: https://github.com/RocketChat/Rocket.Chat/blob/4b408c2ddea118fad49fe1e5949f79154ad0c1b7/server/lib/ldap/Manager.ts#L133

`this.getLdapUsername(ldapUser)` gives a non-slugified version while `usedUsername` might be already the slugified version.
An easy fix would be replacing `this.getLdapUsername(ldapUser) || usedUsername`  with `this.slugifyUsername(ldapUser, usedUsername)` (or `this.slugifyUsername(ldapUser, usedUsername) || usedUsername` ?). 
This might call `slugifyUsername` twice for some call stacks, however.

Fixing this would be highly appreciated. If you know a cleaner verison, this would also be great :)

**Comment by ankar84** [comment]
> As another symptom we noticed the usernames are no longer lowercased since Version 4.0. (This indicates that the name ist not slugified as before)

Totally agree that it was very hard for us to move to that new case sensitive usernames. I described it here https://github.com/RocketChat/Rocket.Chat/issues/24555

**Comment by Turbocube644** [comment]
@pierre-lehnen-rc any news on this?

**Comment by Turbocube644** [comment]
@pierre-lehnen-rc would be really great to get a fix for this. Still present in current versions :(
