### ISSUE TITLE
App CPU usage too high when idle and in the background

### ISSUE THREAD

**Issue by nortcele** [RocketChat/Rocket.Chat#24970]
Last version is using too much CPU even while idle in the background.

rocket.chat version 3.8.0
macOS 12.3

**Comment by nortcele** [comment]
![rocket chat cpu usage](https://user-images.githubusercontent.com/910206/160352282-237758af-02f4-45dd-9977-5d21e592c823.png)

**Comment by maiksd** [comment]
Same here, same versions, same CPU usage.
<img width="1186" alt="Bildschirmfoto 2022-03-28 um 11 06 00" src="https://user-images.githubusercontent.com/903073/160364995-ecdc9442-974b-4ed9-b7f2-d2521ed73702.png">

**Comment by maiksd** [comment]
I killed that specific renderer, which got rid of the CPU load problem, and the client kept running anyway. But obviously that's not ideal.

**Comment by ankar84** [comment]
@maiksd @nortcele do you have connection to open.rocket.chat? Or only your home connection?

**Comment by nortcele** [comment]
I have connection to https://chat.macports.org server and the my work serve.

**Comment by maiksd** [comment]
I have only one active connection, which is to our company's work instance. Colleagues don't confirm the problem, but almost all of them don't yet have 3.8.0 running.

**Comment by ankar84** [comment]
> I have connection to https://chat.macports.org server and the my work serve.
> 
> Even when I have removed all servers from the server list and non lnger have volontary connexion to a server, Rocket.Chat continue to use too much cpu ![empty-connection](https://user-images.githubusercontent.com/910206/160401574-7c611137-2204-4675-b2d6-938e3f78aa38.png)

Exactly! That was my guess.
Simply open welcome page of open.rocket.chat (not login in) in browser or in Electron app and you see CPU load.
There something on that page.
I already told that to community managers. Let's wait for a fix.

**Comment by giterium** [comment]
Same problem. Ubuntu has a very large load, Windows has less.

**Comment by TheMatzy** [comment]
Hi, I have the same issue. I find out that when you are not logging in, that the CPU is in the Rocket.Chat Client high and in the Browser (Firefox & Google Chrome)

In Chrome when I am not logged in
![grafik](https://user-images.githubusercontent.com/41703752/160575343-d592a3dd-1ea2-49a1-b3ae-22a1ad15182c.png)


When I am logged in, CPU is again low
![grafik](https://user-images.githubusercontent.com/41703752/160575744-fcb4a316-fff6-4e1b-b605-802c377a3c9e.png)

Here a Runtime Analysis in Firefox
![grafik](https://user-images.githubusercontent.com/41703752/160576782-5b63037e-6f37-4b03-bc60-8de22cca17b6.png)

It looks like some javascript component is responsible. but when you log in it is gone.

**Comment by toppermitz** [comment]
Same here 

MacOS 12.3
Rocket.Chat app 3.8.1
Rocket.Chat Server 4.5.4
M1 Chip

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/13020454/160718482-11018359-5994-49ab-9c49-d2f4db63041f.png">

After I disable this settings the cpu load back to normal and never uses high CPU again
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/13020454/160718860-4649ab11-cd5c-4ae3-9400-7d0238b8e95f.png">

**Comment by klamma** [comment]
same problem for me on Version 3.15.0 on MacOS Monterey 12.2.1

**Comment by ankar84** [comment]
> same problem for me on Version 3.15.0 on MacOS Monterey 12.2.1

You need update both server version to 4.6.1 and desktop client version to 3.8.2
