### ISSUE TITLE
Snaps are not updated at the repositories

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat#24979]
Rocketchat at snaps is still at 4.5.1 and not updated to latest bugfix release.
The 4.6.x release is nowhere either.

For example the 4.5.1 release contains a bug that is already fixed in later version.
So if you are using OAuth you have still a semi broken application also the fix is already there but you can't install them.

There is a edge channel that isn't used properly either and all other channels at snap are just outdated like usual.

This reminds me a lot at https://github.com/RocketChat/Rocket.Chat/issues/24349 where similar problems turned up.

Maybe @debdutdeb has a idea what happening.

I would really appreciate if there is a reliable way to stay up to date and get bug fixes and security related fixes in a proper time frame after a release was made (so days not weeks or months).

**Comment by debdutdeb** [comment]
Hi, eta for automating the whole process is tomorrow eod. I'll manually push the newest release tonight :)

**Comment by CvH** [comment]
oh thats sounds nice, hopefully the whole situation "just works" soon :)

**Comment by btafoya** [comment]
I see 4.5.5 was released but still the snap is at 4.5.1. Any change to this? I find it odd that the snap is so far behind, especially when it is the promoted install method.

**Comment by debdutdeb** [comment]
4.5.5 released on snap.

**Comment by debdutdeb** [comment]
Automation workflow added here https://github.com/RocketChat/rocketchat-server-snap/pull/45
