### ISSUE TITLE
AD-imported avatars being resized with white borders

### ISSUE THREAD

**Issue by l3mde** [RocketChat/Rocket.Chat#2497]
Your Rocket.Chat version: 0.20.0 - 40d4f47a2af31c03c856fe18bcc091aa81211263

Hi, we are running a RC instance on an up-to-date CentOS 7 host using ansible for deployment (the default playbook)

Integration with active directory is working really fine, except one thing:

Syncing avatars from profile pictures in active directory will end up with the correct pictures, but minified with a large white border... 

E.g. (just for visualisation):
![rc](https://cloud.githubusercontent.com/assets/427792/13739622/8d7213d6-e9cc-11e5-850e-9e2b06713bf6.png)

The behaviour was already present in 0.15.0.

**Comment by rodrigok** [comment]
If your picture is less the 200px of size the image will be resized. Can you confirm if this is the problem?

You can disable avatar resize or change the size in admin page under `Accounts` page.

![image](https://cloud.githubusercontent.com/assets/234261/13884621/8a69c820-ed0d-11e5-84ae-8413582e5c84.png)

**Comment by engelgabriel** [comment]
Hi @l3mde, please turn off the **Resize Avatars** option and reopen this issue if the problem persists.
