### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by yacosta738** [RocketChat/Rocket.Chat#24975]
I think it would be awesome if Rocket Chat could have a native dark mode.

![bitmoji](https://sdk.bitmoji.com/render/panel/21759482-c054-4dc5-aaef-e9ce15cf7e3a-db1ffc10-9e7f-4bea-a043-e744f59d5043-v1.png?transparent=1&palette=1&width=246)

**Comment by dudanogueira** [comment]
Hi! Please, give your +1 on this Issue:

https://github.com/RocketChat/feature-requests/issues/143

**Comment by juzser** [comment]
I've updated the Dark mode for the new version of Rocket using css variables.
You guys can try this here: https://github.com/juzser/Rocket.Chat-Dark-Theme
