### ISSUE TITLE
Threads are cut off for certain window widths

### ISSUE THREAD

**Issue by DaDummy** [RocketChat/Rocket.Chat#24985]
**Describe the bug**
With certain window widths the thread view is cut off on the left since a couple of versions:

What operating system and which version?
- Kubuntu 21.10
- Windows 10
Which version of Rocket.Chat (Server)? 4.5.3
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.8.0
Is there any setting relevant changed? No.

**To Reproduce**
1. Open thread view on any message
2. Reduce the window width until shortly before the channel list is collapsed.

**Expected behavior**
Threads are displayed in a readable fashion.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11466036/160625389-0e26a56d-2c36-431c-a9c3-cacc02c156de.png)

**Additional context**
This appears to be largely independent of the exact version. This issue has been present since at least a month across multiple client and server versions now.

**Comment by Gummikavalier** [comment]
I can confirm this issue on RC 4.5.5.

We use the following custom CSS to work around the issue:

```
/* Decreasing size of expanded thread view */
div.rcx-box.rcx-box--full.rcx-vertical-bar.rcx-thread-view.rcx-css-1m6pvl6 {
    width: 65% !important;
}

/* Increasing size of collapsed thread view */
aside.rcx-box.rcx-box--full.rcx-vertical-bar.rcx-css-17l0eu7 {
    width: 45% !important;
}
```

**Comment by tewfik-ghariani** [comment]
I confirm that the left sidebar overlaps with extended threads, especially when **zoomed in**

<img width="952" alt="Screenshot 2022-05-19 at 15 39 44" src="https://user-images.githubusercontent.com/11073604/169307092-ea58c081-3fc1-4ed1-860c-2bfabb260cf8.png">

I guess a potential solution would be to add the possibility to collapse/expand the left sidebar manually ( ref https://github.com/RocketChat/Rocket.Chat/issues/21131 )

**Comment by MartinSchoeler** [comment]
This was fixed by https://github.com/RocketChat/Rocket.Chat/pull/29461
