### ISSUE TITLE
Giphy Support

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#25]

**Comment by rafaelks** [comment]
@engelgabriel Actually, would be nice to support different kind of integration. Something more generic. What you think?

**Comment by sampaiodiego** [comment]
this could be achieved by #32

**Comment by engelgabriel** [comment]
Agreed.. we must build a generic plugin interface, and create some initial samples.. and Giphy could be one of them.

**Comment by engelgabriel** [comment]
We now support Hubot and custom message processor via packages, so I'll close this one.

**Comment by engelgabriel** [comment]
Now that we have the integrations working with custom scripts, lets give a shot to migrate the Giphy from hubot to a internal slash command, that posts the gif as the users and not the bot.

**Comment by marceloschmidt** [comment]
@geekgonecrazy has created an integration webhook with Giphy

**Comment by engelgabriel** [comment]
@marceloschmidt Can you add the link here for the script while we dont get the app catalogue?

**Comment by manuelbachl** [comment]
geekgonecrazy did, too? So now we've got 2 integrations?

**Comment by engelgabriel** [comment]
actually... @geekgonecrazy installed yours, @manuelbachl :)

**Comment by engelgabriel** [comment]
Once we get the catalogue up, @manuelbachl will be able to publish there.

**Comment by manuelbachl** [comment]
in the meantime just look at the wiki - under Technical Guides - Webhooks, there It's listed
https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting---Gif

**Comment by marceloschmidt** [comment]
You rock, @manuelbachl thanks for that
