### ISSUE TITLE
Threads and broken UI

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#25013]
### Description:

It doesn't always happen, so it is difficult to track.
But it happens several times a week, since some months (I know it is vague, but I don't have better).

### Steps to reproduce:

1. use rocketchat with threads
2. click on channels/threads

### Expected behavior:

The UI should remain "stable"

### Actual behavior:

The UI gets borked, and you need to refresh to make it work again.
Borked here means that for instance the thread you were in is "blocked" you are in an other channel, and it is still displaying the previous thread, or information pane.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.4
- Operating System: debian
- Deployment Method: kubernetes
- Number of Running Instances: 2
- DB Replicaset Oplog: true
- NodeJS Version: docker
- MongoDB Version: 4.2.8

### Relevant logs:

Didn't find a relevant log :/ sorry, I'll try next time it happens.

**Comment by dudanogueira** [comment]
Hi! Those kind of issues is indeed complicated, as it's hard to reproduce.

It would help if you can record this somehow.

Regarding logs, you checked also on browser console logs, right?

**Comment by ankar84** [comment]
I guess that issue is related to my issue https://github.com/RocketChat/Rocket.Chat/issues/22323
Can you confirm that, @pierreozoux ?

**Comment by pierreozoux** [comment]
@ankar84 thanks! Yes, it looks definitely related.
