### ISSUE TITLE
Problems to compile Rocket Chat on Windows Server

### ISSUE THREAD

**Issue by VolkerBachmann** [RocketChat/Rocket.Chat#2501]
Your Rocket.Chat version: 0.21 and latest Developer

Hi,

I'm trying to compile Rocket Chat on a Windows Server.
I've installed the dependencies and a SDK 7.1 on the Windows Server 2008 R2.
Every time I try to compile in the directory \bundle\programs\server with "npm install" I got an error message that looks like fibers is not there (see attached npm-debug.log)

What needs to be done to compile the module?
Thanks and best Regards,
Volker

[npm-debug.txt](https://github.com/RocketChat/Rocket.Chat/files/172600/npm-debug.txt)

**Comment by galmok** [comment]
I have been through this exercise and this is what you do:

Edit this file:

programs/server/npm-shrinkwrap.json

Find the fibers section and replace 1.0.5 with 1.0.10 in all 3 lines.

I am not sure if you need to fix project.json that also mentiones fibers 1.0.5, but for good measure, I did so.

Also, in this folder:

programs/server/npm-bcrypt/node_modules

replace bcrypt with an updated version (0.7.8 -> 0.8.5).

After this, npm install will succeed.

**Comment by engelgabriel** [comment]
Meteor doens't support node v4.4.0 officially yet, because of this very issues. They make node v4 the default on Meteor 1.4

**Comment by engelgabriel** [comment]
https://forums.meteor.com/t/when-is-meteor-upgrading-node/17148

**Comment by VolkerBachmann** [comment]
Great, this seems to work, although I didn’t replace the bcrypt.
Will test further on.

Thanks and best Regards,
Volker

Von: galmok [mailto:notifications@github.com]
Gesendet: Freitag, 18. März 2016 11:54
An: RocketChat/Rocket.Chat <Rocket.Chat@noreply.github.com>
Cc: Volker Bachmann <Volker.Bachmann@ranger.de>
Betreff: Re: [Rocket.Chat] Problems to compile Rocket Chat on Windows Server (#2501)


I have been through this exercise and this is what you do:

Edit this file:

programs/server/npm-shrinkwrap.json

Find the fibers section and replace 1.0.5 with 1.0.10 in all 3 lines.

I am not sure if you need to fix project.json that also mentiones fibers 1.0.5, but for good measure, I did so.

Also, in this folder:

programs/server/npm-bcrypt/node_modules

replace bcrypt with an updated version (0.7.8 -> 0.8.5).

After this, npm install will succeed.

**Comment by engelgabriel** [comment]
OK, since this is working, I'l close the issue, and problem will be totally fixed when Meteor supports node v4
