### ISSUE TITLE
docker hub latest tag points to version 4.5.3

### ISSUE THREAD

**Issue by ksarink** [RocketChat/Rocket.Chat#25026]
### Description:

The latest tag on the Docker hub of the rocketchat/rocket.chat is not pointing to the latest release (v4.5.5) but instead pointing to v4.5.3
See this (edited: removed irrelevant versions) screenshot:
![Screenshot from 2022-04-01 19-13-44](https://user-images.githubusercontent.com/2464969/161312150-df3a2530-0c81-497f-b63c-2d69db2d7647.png)

### Steps to reproduce:

1. go to https://hub.docker.com/r/rocketchat/rocket.chat/tags
2. compare DIGESTs of versions

### Expected behavior:

DIGEST of latest is the same as of version 4.5.5

### Actual behavior:

DIGEST of latest is the same as of version 4.5.3

### Server Setup Information:

n/a

### Client Setup Information

n/a

### Additional context

This already happened with other versions in the past: #24353

### Relevant logs:

n/a

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing out.
4.6.0 was just released, and fixed this issue:
https://github.com/RocketChat/Rocket.Chat/releases/tag/4.6.0
