### ISSUE TITLE
Questions regarding hosting rocket chat app on google app engine

### ISSUE THREAD

**Issue by syedalamabbas** [RocketChat/Rocket.Chat#2503]
Your Rocket.Chat version: latest. 

Hi,
         I planning to use rocket chat app with google app engine. But I was wondering if it is possible to separate the data in the current application structure.  Here are few questions I have (assuming there is a large scale use of rocket chat) : 

1. Mongodb  like  db services are available like https://cloud.google.com/datastore/ , but is it possible to use the rocket chat app with that ? Google or even AWS doesn't have any Mongo db cloud service directly. 

2. Is the current app structure able to store differently for binary data and structured data ?
For instance see https://cloud.google.com/nodejs/getting-started/using-cloud-storage. 

The application uses Cloud Storage to store binary data (pictures in this case), while continuing to use a structured database for the book information (either Cloud Datastore, Cloud SQL, or MongoDB).

Is there a way to configure that data separation in rocket chat ? These considerations become important with scale. 
 
Please advice.

**Comment by engelgabriel** [comment]
Hi,

1. Not yet, Rocket.Chat depends on MongoDB, but you can run MongoDB on Google or even AWS. We have plans to become DB agnostic, but this will take a while.

2. Yes, we currently support a few ways to store uploaded files: S3, GridFS, LocalFS, etc. We are writting new storage adaptares as needed.

That data separation already exists.

**Comment by syedalamabbas** [comment]
Ok. Sorry my knowledge was inadequate, thanks for describing this to me. I first tried to go through the online chat, but I couldn't find anyone responding. 
          Rocket chat is great, especially for me the wordpress website integration came as a significant boost. 

Thanks.
