### ISSUE TITLE
Can't add multiple paragraphs before and after the quotation

### ISSUE THREAD

**Issue by Kyogre** [RocketChat/Rocket.Chat#25040]
### Description:

On both (Original and Marked) markdown parsers Rocket Chat can't recognize multiple line breaks above and below the quotation.
Text example:
```
text1


>quote


text2
```

### Steps to reproduce:

\-

### Expected behavior:

User can separate quote from surrounding text with desired amount of paragraphs (Enter button).

### Actual behavior:

Missing line breaks around the quote.

![no paragraphs around the quote detected](https://user-images.githubusercontent.com/2260980/161419639-53eabdef-739b-492d-94af-7eabb7e0ef0b.png)

### Server Setup Information:

Tested on https://open.rocket.chat

### Client Setup Information

\-

### Additional context

As a workaround user can type [FIGURE SPACE or NARROW NO-BREAK SPACE or WORD JOINER](https://en.wikipedia.org/wiki/Non-breaking_space) « » in place of each paragraph.

### Relevant logs:

\-

**Comment by MartinSchoeler** [comment]
![Screenshot 2024-07-26 at 16 17 57](https://github.com/user-attachments/assets/7eae549b-6c58-415d-93ef-30febe93205d)

Hey, I believe this is working on the latest release, if you still experience the issue feel free to open a new issue here on GH.

Cheers!
