### ISSUE TITLE
Continuous use makes it sluggish

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#2505]
Your Rocket.Chat version: .21

When I use rocket chat on chrome 49.0.2623.87 (64-bit) after a day at work the chat window becomes sluggish.

Everyone else on my team also has the same issue.

One way to fix this problem is to close the chat window and opening the tab again.

![step 1 - fresh chrome 2016-03-15 at 1 22 14 am](https://cloud.githubusercontent.com/assets/6703876/13771806/b22d54f2-ea4d-11e5-8640-4158760c49c4.png)
step 1 - fresh chrome

![step 2 - chrome with just 1 tab of rocket chat 2016-03-15 at 1 23 04 am](https://cloud.githubusercontent.com/assets/6703876/13771805/b22d1820-ea4d-11e5-9f9d-1bdab2dfba21.png)
step 2 - chrome with just 1 tab of rocket chat

![step 3 - chrome after browsing rocketchat channels with embedded youtube video 2016-03-15 at 1 24 20 am](https://cloud.githubusercontent.com/assets/6703876/13771804/b22b891a-ea4d-11e5-8efb-1f53ee27a218.png)
step 3 - chrome after browsing rocketchat channels with embedded youtube video

Looking at the memory usage from the three screenshots above it seems to me that the memory leak might be happening when rendering the youtube videos in the channels.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (438/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:59325 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNe-000ayc-AM
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:25 +0100
Date: Tue, 15 Mar 2016 01:10:30 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458029430;
	bh=mtle/TsSFutETMU/9olqiX2Lxx4PhfQ0sDjiErxFS78=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=QfMOBppxUWBND4fFXjn2PwMNRMt+pHG+IDR7YXLWmetITl1LVCpV54Vu57mq/P2Z4
	 YaJGwnuU0aRuw/FcftOOLXhUV+F2wl+gc63D50eTtT2qzzrIWLwR3ztnkvlpsjBkzJ
	 x7FDZ+6+SUR4vhx5eK5+CwZ2y45VvRD3kFvd3LHQ=

**Comment by lvh1** [comment]
I guess this is because all the messages from that day are still loaded. A limit should be added so when there are more than say 500 messages, the oldest ones are 'unloaded' to free up some memory.

**Comment by engelgabriel** [comment]
Probably relates to https://github.com/RocketChat/Rocket.Chat/issues/31

**Comment by engelgabriel** [comment]
I'll close this issue and increase the priority of the old one.
