### ISSUE TITLE
Login using Realtime API and personal acees token

### ISSUE THREAD

**Issue by gn1024** [RocketChat/Rocket.Chat#25058]
Can I use my personal access token (https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/users-endpoints/generatepersonalaccesstoken) as auth-token when logging in using Realtime API (https://developer.rocket.chat/reference/api/realtime-api/method-calls/login#using-an-authentication-token)?
Thank you.

**Comment by dudanogueira** [comment]
Hi!

I believe you can. Please, keep here for bugs and issues.

For community support please refer to:
https://open.rocket.chat/channel/support
or
https://forums.rocket.chat/
