### ISSUE TITLE
[question] login logout event

### ISSUE THREAD

**Issue by changsijay** [RocketChat/Rocket.Chat#2507]
Your Rocket.Chat version: 0.21.0

Hi, I can see some brief usage from the admin dashboard.
where can I get any user's login logout event with timestamp?
are they stored in some collection in the mongodb?

Cause I want to make a statistic about how many users use, how long they stay per week/month.
Thanks.

**Comment by marceloschmidt** [comment]
We only store their last login timestamp, in the user record. I can see this would be a very nice feature to have.
