### ISSUE TITLE
Room not found error when initiating a new direct conversation 

### ISSUE THREAD

**Issue by hegedussz** [RocketChat/Rocket.Chat#25077]
### Description:

We just upgraded to 4.6.0 and now have the following problem. When using the search to start a new direct message room with another user, that was never talked to, we get an error message:

> Room not found
> This room does not exist or you may not have permission to acces

### Steps to reproduce:

This can be reproduced on our instance after upgrading to 4.6.0

Search for a new user with whom you never talked before
Click on him to start a new DM
You should see the error message right now.

### Expected behavior:

A new room with "You have joined a new direct message with ..." should open.

### Actual behavior:

A room not found error is shown.

### Server Setup Information:

Version of Rocket.Chat Server: 4.6.0
Docker version: 20.10.12
Operating System: Debian 10
Deployment Method: Manual installation
Number of Running Instances: 1
DB Replicaset Oplog: yes
NodeJS Version: 14.18.3 - x64 
MongoDB Version: 5.0.6 / wiredTiger (oplog Enabled)

**Comment by dudanogueira** [comment]
Can you try this on an anonymous/incognito window?

or clearing cache, or ctrl+shit+r, etc?

It may be cached...

**Comment by ankar84** [comment]
Yeap, looks like cache issue. Bug was fixed in 4.6.0

**Comment by hegedussz** [comment]
I tried the incognito windows (Mozzila, Chrome).

Somtimes good for the first attempt. 
Unfortunately, after repeated attempts, the error occurs again.

**Comment by dudanogueira** [comment]
Great. This was an ongoing issue for the last couple versions, and seems to be fixed now.

I'll close the issue. 

Please, let us now if it happens again. Thanks!!

**Comment by Sx3** [comment]
Issue is Still for the federated users on v 4.5.5
