### ISSUE TITLE
Batch user import/create

### ISSUE THREAD

**Issue by yumben-yf** [RocketChat/Rocket.Chat#2508]
Your Rocket.Chat version: (0.22)
A batch user managment feature, e.g. import/create multiple users, either from a .csv file or some external databases would be very useful.

**Comment by marceloschmidt** [comment]
Importing from services like Linkedin, Google Contacts, Facebook, etc. would be good.

**Comment by graywolf336** [comment]
This can be done via the CSV importer now: https://rocket.chat/docs/administrator-guides/import/csv

**Comment by huiminzeng** [comment]
Hi @graywolf336 ! Could you please tell me whether there is any possibility that i can use some script to control the behavior of the importer? For instance, rocketchat would import .csv files automatically when gets started? thx

**Comment by luixal** [comment]
Would be great to have a template zip to download. Trying to build it right now, but getting only the "Invalid import file type" alert. No idea whats wrong.

Also, would be much easier to upload CSV files directly (selecting what are you importing with that file if necessary). In our app, we use a template like this (with quite good results):

![image](https://user-images.githubusercontent.com/615268/44206882-86c5b580-a15b-11e8-80b9-6f6e93f93ed1.png)
