### ISSUE TITLE
Organizational structure feature

### ISSUE THREAD

**Issue by yumben-yf** [RocketChat/Rocket.Chat#2509]
Your Rocket.Chat version: (0.22)
 For rocket.chat to be used as an internal communication platform within a company,  I think the feature of a department tree would be necessary.
    I suggest adding a "Users & Organization" section to the left panel, which contains something like a department tree where ALL users are listed and sorted into different departments(as they are in different departments of the company).
    Also, a phone number field for the user info page would be very convenient. So at least 2 new attributes of a user should be added: department and phone number.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (449/400 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:54053 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmPr-000bYY-62
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:41:40 +0100
Date: Tue, 15 Mar 2016 03:40:49 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458038449;
	bh=e/eB9aAYQXDlYL93dDceXXv2nnfLg0a53q+ApaLwugk=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=qy6YXQCFDdx+QHTu8Yz7gX6HTjFBfWWO5T8HmFg65p4nAMiGXqJppvaKspZFaKDM4
	 /NL+iLUZpS8BjEdtjZh+m3fLJ3bt0NaRDPzRRnkx/V4mcbs0U0cJg6K8aRQK5C8/sY
	 1sZ6RKq7GFhIDsctAarSdmhWkO/0M0HJYs4svjSk=

**Comment by Laisky** [comment]
+1 important for company

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by caryxiao** [comment]
This feature is very good.  👍
