### ISSUE TITLE
Text/Emoji Format in Sidebar & Emails

### ISSUE THREAD

**Issue by ahmedibrahim404** [RocketChat/Rocket.Chat#25106]
### Description:
There is a problem with the emoji format when shown on the sidebar, on when received on emails. It appears as a plain text (for example the smiling face appear => `:smile:`)

In the emails, there is also problem in parsing the markdown format

### Steps to reproduce:

1. Send any message containing an emoji
2. The emoji will appear as plain text on the left side bar

OR

1. When being offline and receiving any message containing markdown format or emoji, It will appear as plain text with no format

### Expected behavior:
The emoji should appear as an image in both sidebar & email. As well as the text should be formatted.

### Actual behavior:
![164936280095043683](https://user-images.githubusercontent.com/34144004/162290030-cab70572-4c10-44de-b304-47c01156c2bb.gif)
![Screenshot from 2022-04-07 22-13-28](https://user-images.githubusercontent.com/34144004/162290053-fb99c58b-4464-4fc6-9d75-b8ddededb5e4.png)
![Screenshot from 2022-04-07 22-13-54](https://user-images.githubusercontent.com/34144004/162290059-ae9964ca-b5ba-4d8a-9cf2-b401ceb91938.png)

**Comment by nmagedman** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/27580#issuecomment-1462686167

**Comment by nmagedman** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/27580#issuecomment-1462686167

> The PR description says that this closes #25106 “Text/Emoji Format in Sidebar **& Emails**”
however the PR only addresses the _sidebar_ part of that issue.  What is the plan for supporting Markdown **_in email?_**
