### ISSUE TITLE
Docker 4.6.0 to 4.6.1 Error: Can't find migration version 258

### ISSUE THREAD

**Issue by Shadow00Caster** [RocketChat/Rocket.Chat#25111]
### Description:
Error: Can't find migration version 258 when running 4.6.1 from 4.6.0 in Docker.

### Steps to reproduce:
1. Run RC on version 4.6.0 with mongo 5.0.6 and then change RC to latest (4.6.1 at time of this post)
2. Error is displayed and server does not start

### Expected behavior:
Product should function

### Actual behavior:
Server does not start and exits with Error: Can't find migration version 258

### Server Setup Information:
```
|  Rocket.Chat Version: 4.6.0                         |
|       NodeJS Version: 14.18.3 - x64                 |
|      MongoDB Version: 5.0.6                         |
|       MongoDB Engine: wiredTiger                    |
|             Platform: linux                         |
|         Process Port: 3000                          |
|     ReplicaSet OpLog: Enabled                       |
|          Commit Hash: 843d7adf7d                    |
|        Commit Branch: HEAD                          |
```

### Client Setup Information
N/A

### Additional context
- Mongo FeatureCompatibilityVersion is set to 4.4, unsure if this needs to be changed or is an issue, previously it was 3.6 when upgrading to 4.4, changed to 4.4 to upgrade to latest (5.0.6 at time of this post)

### Relevant logs:
Error: Can't find migration version 258

**Comment by Magelo** [comment]
Same issue for me. I had 4.6.0 and mongo 5.0.6 and updating to 4.6.1 RC is not working :

Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.

**Comment by elektro-wolle** [comment]
See my comment on #25110: `latest` tag is pointing to an old version.

**Comment by Razva** [comment]
Replace `latest` with `4.6.1` and you're golden.

**Comment by slimshizn** [comment]
> Replace `latest` with `4.6.1` and you're golden.

confirmed working. Thanks.
