### ISSUE TITLE
Jitsi Integration doesn't allow desktop sharing

### ISSUE THREAD

**Issue by LucasRueckert** [RocketChat/Rocket.Chat#25112]
Description:

When starting a video conference via Jitsi it is not possible to share your desktop. Microphone and Camera work fine.
Steps to reproduce:

    Configure Jitsi Integration
    Enter Channel and start Video conference
    Click on Share Desktop Button

Expected behavior:

My desktop (or parts of it) are shared to all other participants.

Actual behavior:

Error message "Permission to access screen wasn't granted" (in Browser Dev Tools JavaScript console). The permission is not requested from the user (as they are with Mic and Cam).

Server Setup Information:

    Version of Rocket.Chat Server: 4.4.2
    Operating System: Debian11(client), Debian10(server)
    Deployment Method: .deb package
    Number of Running Instances: 1

Client Setup Information
    Desktop client versions(not working): 3.7.3 - 3.8.2
    Behaviour occurs with Firefox(latest) and Chrome(latest) under Linux

Same problem has been fix in BBB integration(Issue [#16972](https://github.com/RocketChat/Rocket.Chat/issues/16972) ; Fix [#17290](https://github.com/RocketChat/Rocket.Chat/pull/17290))

Permission is missing in Development Branch(https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/views/room/contextualBar/Call/Jitsi/lib/Jitsi.js)

Line 167:
    old: this.frame.setAttribute('allow', 'microphone; camera');
    fix: this.frame.setAttribute('allow', 'microphone; camera; display-capture');

After deploying this fix to our server screen sharing worked fine.

**Comment by LucasRueckert** [comment]
New Link to the file:
[(https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/views/room/contextualBar/VideoConference/Jitsi/lib/Jitsi.js)]

**Comment by jeanfbrito** [comment]
I think that since version 5.0.0 that introduced Video Conference, this is not an issue anymore. Could you confirm please?
