### ISSUE TITLE
Migration missing from 4.6.1 release

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#25110]
### Description:

Migration missing in 4.6.1

### Steps to reproduce:

1. Be running 4.6.0 or earlier
2. Update to 4.6.1
3. See logs. 

### Expected behavior:

I should be running 4.6.1 but I'm not. 

### Actual behavior:

See logs. 

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.0 (tried to update to 4.6.1)
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: y
- NodeJS Version: Docker image
- MongoDB Version: 4.2

### Relevant logs:
```
rocketchat_1          | LocalStore: store created at 
rocketchat_1          | LocalStore: store created at 
rocketchat_1          | LocalStore: store created at 
rocketchat_1          | /app/bundle/programs/server/node_modules/fibers/future.js:280
rocketchat_1          | 						throw(ex);
rocketchat_1          | 						^
rocketchat_1          | 
rocketchat_1          | Error: Can't find migration version 258
rocketchat_1          |     at migrateDatabase (server/lib/migrations.ts:246:9)
rocketchat_1          |     at module (server/startup/migrations/xrun.js:8:1)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1          |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
rocketchat_1          |     at module (server/startup/migrations/index.ts:1:17)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1          |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
rocketchat_1          |     at module (server/startup/index.ts:1:8)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1          |     at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
rocketchat_1          |     at module (server/main.ts:1:30)
rocketchat_1          |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat_1          |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat_1          |     at require (packages/modules-runtime.js:258:21)
rocketchat_1          |     at /app/bundle/programs/server/app/app.js:206654:15
rocketchat_1          |     at /app/bundle/programs/server/boot.js:401:38
rocketchat_1          |     at Array.forEach (<anonymous>)
rocketchat_1          |     at /app/bundle/programs/server/boot.js:226:21
rocketchat_1          |     at /app/bundle/programs/server/boot.js:464:7
```

**Comment by geekgonecrazy** [comment]
Interesting… https://github.com/RocketChat/Rocket.Chat/blob/4.6.1/server/startup/migrations/v258.ts definitely seems to be there.  Are you using the specific docker tag?

**Comment by ankar84** [comment]
Just for information - I successfully upgraded from 4.3.3 to 4.6.1

**Comment by elektro-wolle** [comment]
Same issue here with an instance started running in docker (rocketchat/rocket.chat:latest)
After checking the digests of `latest` against the other tags: `latest` is equal to `4.4.3`.
Changed the image tag to 4.6.1 and everything is working again

**Comment by ankar84** [comment]
> Same issue here with an instance started running in docker (rocketchat/rocket.chat:latest) After checking the digests of `latest` against the other tags: `latest` is equal to `4.4.3`. Changed the image tag to 4.6.1 and everything is working again

@debdutdeb Guess you did a PR which must prevent such issues.

**Comment by Razva** [comment]
Somebody messed the `latest` tag. [facepalm]

**Comment by geekgonecrazy** [comment]
from one sysadmin to another.  Please don't use docker latest tag in production.  You deserve more stability then a pointer that can change at any time

**Comment by emadshkeer** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/25110

**Comment by emadshkeer** [comment]
https://github.com/RocketChat/Rocket.Chat/issues

**Comment by robbyoconnor** [comment]
@emadshkeer I checked. Maybe look at when I made this issue when you do this.

**Comment by robbyoconnor** [comment]
@geekgonecrazy I pull from the `latest` and usually trust that since you are offering a service, you'd keep releases stable, guess I'm wrong in that assumption -- this really shouldn't come off as harsh as it sounds, sorry about that.

**Comment by geekgonecrazy** [comment]
> I pull from the latest and usually trust that since you are offering a service, you'd keep releases stable, guess I'm wrong in that assumption -- this really shouldn't come off as harsh as it sounds, sorry about that.

Our docker release isn't really a service though.  It's a release.  Ideally I agree latest should always point to the latest release.

But from sysadmin perspective this kind of case is exactly why I would personally not use latest for production install.

For those that provide only latest I always grab the sha256 and use that in place of the tag.

Not saying you must do that or that Rocket.Chat is saying you must.  Just recommending it from one sysadmin to another. 🙂

--

Regardless though this should be resolved and unfortunately this was the cause of this bug.  Latest got pointed to a patch release that happened to be released after the actual latest semver.

**Comment by robbyoconnor** [comment]
Should I close this bug? I got 4.6.1 with the 4.6.1 tag working

**Comment by NCDemonic** [comment]
Why is this bug closed? Shouldn't the latest tag be pointing to 4.6.1?

**Comment by geekgonecrazy** [comment]
Yes it should but it was also already resolved 👍 

> Regardless though this should be resolved and unfortunately this was the cause of this bug. Latest got pointed to a patch release that happened to be released after the actual latest semver.

https://hub.docker.com/r/rocketchat/rocket.chat/tags

![image](https://user-images.githubusercontent.com/51996/162839149-61596908-d684-478c-a12c-2a9b78c053ab.png)
![image](https://user-images.githubusercontent.com/51996/162839167-ab325277-0e76-42cb-8a9b-1689e5e37d7c.png)
