### ISSUE TITLE
Documentation Custom CSS/Custom Scripts 

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2511]
Your Rocket.Chat version: 0.22
Is there any examples on how to use the new feature Custom CSS/Custom Scripts.
And what it exactly is doing?

I assume it would help with theming the missing layout fields?

Best Regards
Mathias

**Comment by lunitic** [comment]
At least CSS was easier than i thought.
To change the color of the bar to the right add the following in the CSS
`//Right Bar
	.flex-tab-bar {
	background-color: #43ffff;
	}`

**Comment by rodrigok** [comment]
@lunitic it's simple, your CSS/LESS will be added at the end of the main LESS, so you can do anything you want.

The SCRIPTS are the same thing, you can write your JS to run at the end of the Login Page or the end of Main Page (for logged users), you can use this to add an Analytics script for example.

**Comment by engelgabriel** [comment]
@lunitic please reopen if you need more info. We will add documentation about this soon.

**Comment by Nemra1** [comment]
@engelgabriel i swear ..i need any manual to edit skin but my minde is broken becuse icant finde any explain to edit .css file

**Comment by lunitic** [comment]
Administration => Layout =>custom CSS. 

There you do all you custom css fixes

**Comment by jszaszvari** [comment]
Is this still going to be documented? 

It's really difficult just to guess what needs to go in there, and if someone does not look on GitHub at these comments they'll find nothing on how its done.

**Comment by ifohancroft** [comment]
I also desperately need documentation. Specially about the custom js and what can be done with it?
For example can we catch events with it and do something accordingly?
What I mean by that is for example when using the jitsi video conference, when someone calls you don't hear a sound. I'd like to intercept the event with js and play a sound or do something else or many stuff.

**Comment by 42robots** [comment]
is there any update on this? Especially the Custom Scripts Sections sounds interesting. 
I guess that would be a place for neat little custom features, like adding a popup on incoming calls or something ... Is there any little getting started hint on this?

**Comment by chatnl** [comment]
Bump for examples. I am not a specialist, a simple example how to add a script when a user logs in or out would be great. I tried to put some javascript in there but nothing happens.

**Comment by rockkoca** [comment]
need example like how to get the values from settings
