### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by senthai** [RocketChat/Rocket.Chat#2512]
Your Rocket.Chat version: (make sure you are running the latest)

Hi there I am running Rocket Chat in a docker container.
It is running a while and then it crashes.

It always crashes when someone is writing after a long time.
The Error looks like this:
`rocketchat_1 | /app/bundle/programs/server/npm/raix_push/node_modules/apn/node_modules/q/q.js:155
rocketchat_1 |                 throw e;
rocketchat_1 |                       ^
rocketchat_1 | Error: ENOENT, open 'cert.pem'
db_1         | 2016-03-15T18:41:38.179+0000 I NETWORK  [conn12] end connection 172.17.0.5:50268 (4 connections now open)
db_1         | 2016-03-15T18:41:38.179+0000 I NETWORK  [conn10] end connection 172.17.0.5:50266 (4 connections now open)
db_1         | 2016-03-15T18:41:38.179+0000 I NETWORK  [conn8] end connection 172.17.0.5:50264 (4 connections now open)
db_1         | 2016-03-15T18:41:38.180+0000 I NETWORK  [conn9] end connection 172.17.0.5:50265 (2 connections now open)
db_1         | 2016-03-15T18:41:38.180+0000 I NETWORK  [conn11] end connection 172.17.0.5:50267 (0 connections now open)
rocketchat_rocketchat_1 exited with code 8
`

Any Ideas?

Thx!!!

**Comment by thomas-mangin** [comment]
This is caused by the push notification. Not sure if it is a bad configuration or bug on rocket.chat (this trace is present on both 0.21.0 and 0.22.0), but the simplest way to get back to a stable installation is to disable push.
This thread may also be of help
https://github.com/RocketChat/Rocket.Chat/issues/1762

**Comment by senthai** [comment]
oh okay. i will see what happens if i change settings there.
thx!

**Comment by senthai** [comment]
deactivated push notifications and now it seems to work.
also push is working now... i am very confused ^^
