### ISSUE TITLE
App is crashing after updating the local repository.

### ISSUE THREAD

**Issue by Rohan749** [RocketChat/Rocket.Chat#25137]
### Description:

After updating my remote repo with the current version, I started the app but it crashed. I updated meteor also but it is still showing the same result.

### Steps to reproduce:

1. Update the remote repo.
2. Start the app.(meteor start --port <port>)
3. the result is : Your app is crashing, waiting for file change

### Expected behavior:

It should have started locally

### Actual behavior:
![Screenshot from 2022-04-10 19-37-58](https://user-images.githubusercontent.com/90546860/162623344-f10c2aff-3597-41f9-b6a0-681b9de3902b.png)

**Comment by geekgonecrazy** [comment]
Please never run Rocket.Chat for anything other then development using the meteor command.  Please instead head to our docs and select a deployment method.

If you've got a fork I'd suggest taking a look at our ci and generating a release artifact of your choosing.  

The meteor command is not meant for production deployments but as a development tool.  As such it does a lot of things that take more memory and cpu as well as of course hasn't been a copy ran through tests like our releases are (which slowly but surely will catch and prevent more and more regressions)
