### ISSUE TITLE
Mark as Unread

### ISSUE THREAD

**Issue by jeffrapp** [RocketChat/Rocket.Chat#2513]
The ability to mark a stream of messages as unread would be a very welcome feature.  If I pop over to a DM to see what's up, it would be helpful to mark that message as unread so I can remember to come back to it later.

**Comment by engelgabriel** [comment]
I like that too!

**Comment by Danathus** [comment]
Note: in slack you can alt + click on a message to mark it as unread. Also if you hover over a message, and click the "..." to the side, one of the context menu options that pop up is "Mark unread."

I'd recommend the same user interface for the rocket.chat implementation.

**Comment by xenithorb** [comment]
Is this closed by the new "Mark as unread" feature?

**Comment by engelgabriel** [comment]
Yes @xenithorb it can get better, but the feature is now there:

![image](https://cloud.githubusercontent.com/assets/1000217/17535492/31e9933c-5e65-11e6-9ae0-011680f31bf4.png)
