### ISSUE TITLE
Does the ROCKETCHAT_URL environment support domain name?

### ISSUE THREAD

**Issue by zb471914758** [RocketChat/Rocket.Chat#2514]
when I use domain name to set the environment as below: 
ROCKETCHAT_URL=http://*.*.com
export ROCKETCHAT_USER=bot
export ROCKETCHAT_PASSWORD=bot

and the execute 
``` bin/hubot -a rocketchat```

It will print: 
[Wed Mar 16 2016 11:20:39 GMT+0800 (CST)] INFO Connecting To: *.*.com

but not show: 
[Wed Mar 16 2016 10:56:38 GMT+0800 (CST)] INFO Successfully connected!

and I try to add the port, it also can't connect

Do you know why? Thanks

**Comment by Againstreality** [comment]
Yes it does. Is the Port the one on which rocketchat runs? And can your host resolve DNS correctly?

**Comment by zb471914758** [comment]
It is now OK, thanks
