### ISSUE TITLE
desktop notifications not working with 4.6.1

### ISSUE THREAD

**Issue by Monschichi** [RocketChat/Rocket.Chat#25163]
### Description:

even if notifications are enabled for a user no desktop notifications are triggered.

### Steps to reproduce:

* update to 4.6.1
* enable desktop notifications
* no notifications are triggered

### Expected behavior:

Desktop notifications should get triggered.

### Actual behavior:

Desktop notifications are not triggered.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.1
- Operating System: Debian Buster
- Deployment Method: tar
- Number of Running Instances: 8
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version: 5.0.6

### Client Setup Information

- Desktop App or Browser Version: FF 99, Chrome 100, Electron App
- Operating System: Linux, Windows

### Relevant logs:

no relevant logs found.

**Comment by ankar84** [comment]
Not confirm that 
![image](https://user-images.githubusercontent.com/4023037/163079037-730c6790-a7e6-4a00-84d8-9404e6ac5703.png)

**Comment by wolbernd** [comment]
I can confirm the problem. In our case this is not limited to desktop notifications but also mail notifications.

We tested with latest Chromium, Firefox and RC Desktop app.

In our server logs I see a lot of messages like these:
```
{"level":50,"time":"2022-04-13T07:31:32.261Z","pid":3922,"hostname":"rchat1","name":"StreamBroadcast","section":"Stream","msg":"Stream broadcast from 'localhost:3005' to 'localhost:3004' with name local does not exist"} 
{"level":35,"time":"2022-04-13T07:32:00.657Z","pid":3926,"hostname":"rchat1","name":"Meteor","method":"stream:notify-room","userId":null,"remoteIP":null,"instanceId":"nLTyB7TwzzxZFJT3D"} 
```
but I'm not really sure if those are relevant. 

Here is our server info:
    Version of Rocket.Chat Server: 4.6.1
    Operating System: Ubuntu 18.04
    Deployment Method: tar
    Number of Running Instances: 6
    DB Replicaset Oplog: Enabled
    NodeJS Version: 14.19.1
    MongoDB Version: 4.2.19

**Comment by ankar84** [comment]
> {"level":50,"time":"2022-04-13T07:31:32.261Z","pid":3922,"hostname":"rchat1","name":"StreamBroadcast","section":"Stream","msg":"Stream broadcast from 'localhost:3005' to 'localhost:3004' with name local does not exist"}

I see a lot of these log entries too!

But guess your guys issue about that log entry

> {"level":35,"time":"2022-04-13T07:32:00.657Z","pid":3926,"hostname":"rchat1","name":"Meteor","method":"stream:notify-room","userId":null,"remoteIP":null,"instanceId":"nLTyB7TwzzxZFJT3D"}

**Comment by ankar84** [comment]
Guess I have that issue now on 4.6.2 on my production server.

**Comment by ankar84** [comment]
> Not confirm that ![image](https://user-images.githubusercontent.com/4023037/163079037-730c6790-a7e6-4a00-84d8-9404e6ac5703.png)

And I don't know why I didn't get this issue on my test server.

**Comment by ankar84** [comment]
@sampaiodiego @pierre-lehnen-rc  Hey, guys!
Looks very important issue.

**Comment by tauame** [comment]
We are having the same issue here. Same message logs and same server version. Confirmed both on 4.6.0 and 4.6.2. I'm not sure, but I think it stopped working when we updated to 4.6.0. At least that's when the "streambroadcast with name local does not exist" started showing up on logs.

**Comment by sampaiodiego** [comment]
hey guys.. I'd say the log saying "Stream ... with name local does not exist" is not related to the issue you're facing.

I couldn't reproduce the issue yet though.. but I'm taking a look at this

**Comment by ankar84** [comment]
> edit: nvm, they're definitely related.. just opened a PR adding it back to fix the issue.

@sampaiodiego Hey, Diego!
I found a very important detail.
That issue is about multi-instance and  instances iterability.
It two users sending messages on same instance - notifications works perfect.
If two users on a different instances - there is no notification.

Tested that changing cookies in DevTools.

**Comment by ankar84** [comment]
@sampaiodiego Diego, I see that network statuses (Online, Away, Offline) works not properly on 4.6.2
Is that related to `StreamBroadcast` error or it is something else and I need to make separate issue?

**Comment by sampaiodiego** [comment]
@ankar84 maybe it is related to https://github.com/RocketChat/Rocket.Chat/issues/25194 ?

**Comment by ankar84** [comment]
Test 4.6.3 and can tell that notification works again!
Thanks, Diego!

**Comment by brknapik** [comment]
Hi,
 
In our envrionment even upgraded to last version 4.6.3, the problem still exist 😞 .
