### ISSUE TITLE
RocketChat not showing any messages. Reload not fixing things

### ISSUE THREAD

**Issue by dannyfwolf** [RocketChat/Rocket.Chat#25164]
![image](https://user-images.githubusercontent.com/60444841/162981927-4a17a6de-3fdd-4a63-9818-ba2527fdab1c.png)

**Comment by artemChernitsov** [comment]
Can you share DevTools Console & Network tab, server logs?

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

**Comment by dannyfwolf** [comment]
Hi, 
I updated my version of RocketChat and that fixed the issue so I am no longer able to reproduce it in order to provide details. Sorry that I can't be more helpful, 

Danny
