### ISSUE TITLE
Tweeting out from a ROOM

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2516]
How to setup a room to have an option to tweet out anything posted? Also have the option to allow users to tweet out via their **own handles** (admin to approve per room etc)
is there a wiki how to setup?
Is Your Rocket.Chat version: (0..22)

**Comment by engelgabriel** [comment]
Hi,

This have not been implemented, but you could build a simple version via custom integration if you want.

If this is a feature request, please describe it in more details.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this as this can very likely be achieved by outgoing webhooks or hubot integrations. If you don't agree, please let me know.

As for the permissions: this is something that would need deeper integration but I don't think it would be worth the effort in this very context here.

Cheers
Thomas
