### ISSUE TITLE
Test SMTP settings - error 500 - 

### ISSUE THREAD

**Issue by Vidhyadharantechdays** [RocketChat/Rocket.Chat#2517]
HI,
I am running rocket.chat on  docker  and its version: 0.21.0  ,
I gave all the smtp properties , however i got Error 500 , And here is the logs
I20160316-16:34:24.951(0) Updating process.env.MAIL_URL 
I20160316-16:34:39.337(0) Exception while invoking method 'sendSMTPTestEmail' AuthError: Invalid login - 503 5.5.1 Error: authentication not enabled     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)     at smtpSend (packages/email/email.js:86:1)     at Object.Email.send (packages/email/email.js:185:1)     at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:12:9)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     - - - - -     at SMTPClient._actionAUTHComplete (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:826:23)     at SMTPClient._onData (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)     at CleartextStream.emit (events.js:95:17)     at CleartextStream.<anonymous> (_stream_readable.js:765:14)     at CleartextStream.emit (events.js:92:17)     at emitReadable_ (_stream_readable.js:427:10)     at _stream_readable.js:420:7     at process._tickDomainCallback (node.js:502:13)

**Comment by engelgabriel** [comment]
Looks like `AuthError: Invalid login`

Did you try the same SMTP configuration on another email client?

**Comment by engelgabriel** [comment]
Can you share a print screen of your config (without the password)?

**Comment by engelgabriel** [comment]
Please reopen with more info if the problem persists in version 0.23.0

**Comment by Vidhyadharantechdays** [comment]
I have checked with the other client. it was working fine. 

I am currently running in docker? If i want to upgrade to 0.23.0 , what should i run ?
