### ISSUE TITLE
Can't to paste images, in to the channel between the federations(two organizations)

### ISSUE THREAD

**Issue by AntarPrakash** [RocketChat/Rocket.Chat#25197]
Hi,
When u are need to paste some screen or image in channel between two companyes nothing is happend and u see just a text without attachments

**Comment by ankar84** [comment]
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

**Comment by geekgonecrazy** [comment]
Federation is alpha.  I don't know that files have even been implemented yet

**Comment by geekgonecrazy** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/24329 which includes more details
