### ISSUE TITLE
Microphone icon vanishes after clicking on it.

### ISSUE THREAD

**Issue by leandroqm** [RocketChat/Rocket.Chat#2519]
Tested on https://demo.rocket.chat/channel/general.
Whenever I click on the microphone to send an audio message, it vanishes.
@Sing-Li confirmed the bug with me.

**Comment by jots** [comment]
I see the same thing.  Also chrome adds a red "recording" icon to the tab and it never goes away.  So it appears it is recording, but no way to stop it.
