### ISSUE TITLE
HOWTO write package/plugin/extension?

### ISSUE THREAD

**Issue by mitjajez** [RocketChat/Rocket.Chat#2520]
I'm looking in code how to write my own (opensource) package where i'd put some graphics elements in sideNav and turn main-content in something else. So where and how to put my code to be rendered as wished?

I saw #1859, this would be great!

However, also [wiki: Understanding-the-Code](https://github.com/RocketChat/Rocket.Chat/wiki/Understanding-the-Code) would help.

**Comment by engelgabriel** [comment]
We are working on a new documentation site, bare with us and we will announce next week

In the meantime, https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting

**Comment by assadvirgo** [comment]
@engelgabriel any update on this?

**Comment by purp** [comment]
+1. Interested in learning how to write a plugin for R.C

**Comment by voffkas** [comment]
+1

**Comment by purp** [comment]
@engelgabriel any update here? We're nearly 18 months later than the new docs site, and it's not clear where to find this info.

**Comment by jszaszvari** [comment]
@graywolf336 is working on this.

**Comment by jszaszvari** [comment]
@purp see here for more specifics https://github.com/RocketChat/Rocket.Chat/issues/6890

**Comment by purp** [comment]
@jszaszvari Thanks for the pointer. This looks like a much bigger effort which will be excellent when it lands. I was looking for more of a "How do I get started *now* even if it's going to change" pointer.

**Comment by graywolf336** [comment]
@purp Best place to look until then is the code and the current packages inside of the Rocket.Chat code base. You will have to manage a fork of Rocket.Chat and keeping it updated if you don't plan on publishing your changes to the main project. That's a big responsibility and one of the main motivators behind Rocketlets.
