### ISSUE TITLE
Issue Delivering messages

### ISSUE THREAD

**Issue by lidernetworktecnologia** [RocketChat/Rocket.Chat#25228]
Messages are not delivered and you need to keep updating the page. Same problem already reported by two users in RocketChat/Rocket.Chat.Electron#1938 issues. Is there a solution?

--- original message ---

Mensagens nao sao entregues e precisa ficar atualizando a pagina. Mesmo problema relatado já por dois usuários no issues RocketChat/Rocket.Chat.Electron#1938. Alguma solução?

**Comment by dudanogueira** [comment]
Olá! Você é um cliente Enterprise? Se sim, por favor, abra um ticket de suporte em https://support.rocket.chat/

Caso seja um usuário Community, nos especifique por favor as informações solicitadas no template de abertura, como versão do servidor, navegador, etc, para que possamos ajudar da melhor maneira possível. 

Em geral esse tipo de problema é algo relacionado à instalação ou ambiente, e não um problema do produto em si.

Também considere usar o nosso [canal de suporte comunitário](https://open.rocket.chat/channel/support) ou [fórum](https://forums.rocket.chat/)

Obrigado!

**Comment by geekgonecrazy** [comment]
Based on the linked issue of a SaaS customer please also follow appropriate channels to open an issue.  As if SaaS the issue will need to be addressed via support and not any advise that can be given here
