### ISSUE TITLE
Telegram send pre-message

### ISSUE THREAD

**Issue by finsfera0** [RocketChat/Rocket.Chat#25238]
Hello, 

At the moment the bot starts, we get the notification "telegram: 5058002625 Chat started 11:26 PM" and only then the message.
How can I not receive the first chat alert?

<img width="668" alt="Снимок экрана 2022-04-20 в 01 34 30" src="https://user-images.githubusercontent.com/97625144/164112464-c101d35e-5d05-4d53-9555-6e1e80e7a739.png">

**Comment by dudanogueira** [comment]
[Related Thread on Open](https://open.rocket.chat/channel/support/thread/KPe29EPttbaRh6u5M)

As stated on the thread this is just a visual element that indicates a new room. 

It should be possible to hide it using ADMIN > LAYOUT > CUSTOM CSS with the following snippet:

```
.livechat-started{
  display: none;
}
```

**Comment by dudanogueira** [comment]
Ps: If you want to keep the date, use this one:

`
.livechat-started div.message-body-wrapper, .livechat-started div.avatar{
  display: none;
}
`
