### ISSUE TITLE
Is it possible to register a user via the REST API?

### ISSUE THREAD

**Issue by stonetwig** [RocketChat/Rocket.Chat#2525]
Hello,

I am part of a group that evaluates Rocket.chat instead of Slack and it seems great.
However, I am wondering if and how I can register a user via the rest api? Is it even possible?

I checked the documentation but could not find any information about a register endpoint. Because the issue we have is that we already have a signup system where the user provides their desired email and password, so it would be great if we just could send an extra http request in the background to register the same account for the chat application. This can be done with slack today, except that the user must click on a register link sent to their mail.

Best regards,
stonetwig

**Comment by gitim** [comment]
Hi, I had the same question and found [undocumented api](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/restapi/restapi.coffee#L80-L133)  for registering users, but I haven't checked it yet.

**Comment by MartinSchoeler** [comment]
https://rocket.chat/docs/developer-guides/rest-api/users/create
