### ISSUE TITLE
Got warning need to change server URL regularly

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat#25266]
### Description:

I often got the below warning when I login to RockatChat from webpage:

"The setting Site URL is configured to http://localhost:3000 and you are accessing from https://chat.mydomain.com!"
"Do you want to change to https://chat.mydomain.com?"

When I click "yes" it will be ok but several days after the warning will happen again. 
![image](https://user-images.githubusercontent.com/4077255/164684701-dade3fd3-4112-430c-a797-ba44f10b07fe.png)

### Steps to reproduce:

1. Access Rockat.Chat from web and login as administrator
2. Got warning to change URL.
3. Click "Yes" works but serval days after, the warning happen again.

### Expected behavior:

The URL should be https://chat.mydomain.com

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version:4.2.17

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi! This is not a bug/issue.

When you click Yes, you will change that information for that specific user only.

You need to change the siteurl parameter in snap. Here you can have the command for that:
https://docs.rocket.chat/quick-start/installing-and-updating/rapid-deployment-methods/snaps/auto-ssl-with-snaps

please, consider using our [Community Support Channel](https://open.rocket.chat/channel/support) or [Forums](https://forums.rocket.chat/) when not sure if it's a bug or a configuration issue.

Thanks!

**Comment by smallfish01** [comment]
> 

Hello Dudanogueira,

Thanks for you replied, actually I have setup the correct "Site URL" in "General", so you means I also need running "snap set rocketchat-server siteurl=https://chat.mydomain.com" in my server?

Thank you.
