### ISSUE TITLE
New users created with CAS don't join the default channels

### ISSUE THREAD

**Issue by anthony-o** [RocketChat/Rocket.Chat#2526]
Your Rocket.Chat version: 0.21.0

I configures my Rocket.Chat to use my CAS server. The users are automatically created when they first log into the Rocket.Chat instance.

My problem is that it seems to be a bug here because even if the #general channel is configured to be default (default=true), the new users are not automatically added to the #general channel...

**Comment by corecache** [comment]
Hi there,
That is correct - there is currently no call to let CAS created users join the default channels - but there should be. I'll try to fix this the upcoming days.

**Comment by synotna** [comment]
Is this similar to but not the same as https://github.com/RocketChat/Rocket.Chat/issues/2195 ?

We just updated to 0.24.0 and the problem is still there

**Comment by corecache** [comment]
Okay, a few things to note, I tested the auto-joins before the PR and it worked - the code which was implemented came from packages/rocketchat-ldap/server/loginHandler.js - so in theory that one shouldn't work either.

**Comment by engelgabriel** [comment]
@rodrigok can you take a look at this?

**Comment by rodrigok** [comment]
How can I test CAS?

**Comment by corecache** [comment]
By having a CAS instance configured with some non-selfsigned ssl certs

**Comment by engelgabriel** [comment]
That was polite way to ask for one to borrow :)

**Comment by corecache** [comment]
I don't have one available in public

**Comment by rodrigok** [comment]
Can you verify if the `user._id` has the correct value when calling the `joinDefaultChannels`?

**Comment by rodrigok** [comment]
You can see that in logs if you active the debug level:
```javascript
		logger.debug('Created new user for \'' + result.id + '\' with id: ' + user._id);
```

**Comment by corecache** [comment]
I'm still on vacavation and will verify this as soon as I'm home again - this will probably in the week of 4th - 8th april.

**Comment by anthony-o** [comment]
To launch a local CAS server, you can use [this project](https://github.com/iorga-group/docker-cas-test):

```
git clone https://github.com/iorga-group/docker-cas-test.git
cd docker-cas-test
docker build -t cas-test ./
docker run -it --rm -p "8080:8080" -p "8443:8443" --hostname sso.mycompany.com cas-test
```
(don't forget to associate `sso.mycompany.com` with your localhost)

**Comment by corecache** [comment]
@rodrigok Retested this with 0.24 and 0.25, works as intended:

`.015(0)? cas_server.js:30 CAS ➔ debug Using CAS_base_url: https://login.my.org/sso`
`.120(0)? cas_server.js:42 CAS ➔ info Validated user: mytestuser`
`.622(0)? cas_server.js:129 CAS ➔ debug Looking up user with username: mytestuser`
`.632(0)? cas_server.js:149 CAS ➔ debug User 'mytestuser'does not exist yet, creating it`
`.664(0)? cas_server.js:154 CAS ➔ debug Created new user for 'mytestuser' with id: Gcq29FbtE9mHMqkKR`
`.668(0)? cas_server.js:156 CAS ➔ debug Joining user to default channels`
`.674(0)? [methods] joinDefaultChannels -> userId: Gcq29FbtE9mHMqkKR , arguments:  {}`
`.744(0)? [methods] canAccessRoom -> userId: null , arguments:  { '0': 'GENERAL', '1': null }`
`.763(0)? [publish] settings -> userId: Gcq29FbtE9mHMqkKR , arguments:  {}`
`.807(0)? [publish] stream-notify-all -> userId: Gcq29FbtE9mHMqkKR , arguments:  { '0': null }`
`.812(0)? [publish] stream-notify-room -> userId: Gcq29FbtE9mHMqkKR , arguments:  { '0': null }`
`.813(0)? [publish] stream-notify-user -> userId: Gcq29FbtE9mHMqkKR , arguments:  { '0': null }`

**Comment by engelgabriel** [comment]
@anthony-o please reopen this issue with your startup logs if the problem persists for you on version 0.25.0
