### ISSUE TITLE
I can't see messages from users, just groups

### ISSUE THREAD

**Issue by joaofilippe** [RocketChat/Rocket.Chat#25267]
![image](https://user-images.githubusercontent.com/85184341/164708544-a3c9c4c3-9a9c-4bcc-a91a-c965bab6c387.png)

**Comment by dudanogueira** [comment]
Hi! Please, refer to our [Community Support Channel](https://open.rocket.chat/channel/support) or [Community Forums](https://forums.rocket.chat/).

Also, when opening an issue, please, provide the requested information. 

This is most likely a configuration problem. Have you changed some permissions? What version are you running? 

Without more context, is really hard to help you out, here or on the forums/support channels :grimacing:
