### ISSUE TITLE
OTR not avaiable on Mobile Clients

### ISSUE THREAD

**Issue by Againstreality** [RocketChat/Rocket.Chat#2528]
I run Rocket Chat 0.22 on the desktop and webclient OTR ist available. as an Option.
On Ios 9.2.1 and Android it seems that the UI misses the  option. #36 

![otr](https://cloud.githubusercontent.com/assets/11700533/13845904/6fa2f2e8-ec43-11e5-9de9-d502feaa8d0d.jpg)

**Comment by engelgabriel** [comment]
We need to test for prefixed encrypting functions on older browsers.

**Comment by marceloschmidt** [comment]
Hello @Againstreality do you have access to `develop` branch? If you do, please test again with the latest code. I've added webkitSubtle as possible crypto engine, which is what safari uses, I think. Let me know if it works for you. Thanks.

**Comment by Againstreality** [comment]
I will do today. Thx.

**Comment by Againstreality** [comment]
okay i downloaded from https://rocket.chat/releases/develop/download and this made it available but not working on Android but not on ios
