### ISSUE TITLE
Emoji button not working

### ISSUE THREAD

**Issue by aakash-gitdev** [RocketChat/Rocket.Chat#25293]
### Description:
Emoji icon button not working

### Steps to reproduce:

1.  Go to any channel
2.  Click on the emoji icon in the textbox area

### Expected behavior:

On clicking the emoji icon, the emoji panel should open

### Actual behavior:

On clicking the emoji icon, the emoji panel did not open.
![image](https://user-images.githubusercontent.com/94236076/164992605-ded59224-5055-4df5-96d7-e5234fb66135.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context
As of now this button is not opening up. I think there is some small error in the relevant code.

**Comment by aakash-gitdev** [comment]
I am trying to look for the code for the emoji icon settings and am looking in the messageBox directory as shown in above image. Can someone please guide me with the exact path to the appropriate code as I am new to this codebase ?

**Comment by JohnSeabourn** [comment]
I am also having the same issue.  I click on the emoji icon and it doesn't do anything.

**Comment by hugocostadev** [comment]
Working since 5.4 (LTS) version
