### ISSUE TITLE
Rocket emoji tab not working properly in android version

### ISSUE THREAD

**Issue by Gmdsheikh60** [RocketChat/Rocket.Chat#25291]
Description:
Rocket emoji tab not working properly in the android version it just shows,s emoji signs only and when we send the message it goes correctly.

Steps 
Login to user
open the emoji tab
select the rocket tab I the emojis 
select any emoji
in the message tab, it will only show an emoji sign but when we send a message it shows the emoji accordingly. Kindly review the attached SS for a better understanding

![Rockerchat bug](https://user-images.githubusercontent.com/100342639/164965934-82ad3667-6ba8-4280-95ef-89a87f3f1984.jpeg)

**Comment by aleadco** [comment]
#4109
