### ISSUE TITLE
Fields Query Parameters not working on livechat rooms list endpoint

### ISSUE THREAD

**Issue by mkvashennikov** [RocketChat/Rocket.Chat#25300]
### Description:

Fields Query Parameters not working on livechat rooms list endpoint

### Steps to reproduce:

1. Send request with query or fields parameter on endpoint '/api/v1/livechat/rooms'
2. Returned all rooms without apply query or fields

### Expected behavior:

Rooms can be filtered by fields

### Actual behavior:
![image](https://user-images.githubusercontent.com/30016120/165133551-6ae0878a-c4ed-4b8a-92b7-ff2893802ad5.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.14.0
- Operating System:  Windows 11
- Number of Running Instances:  1

**Comment by dudanogueira** [comment]
Hi! 

I have checked on latest code, and looks that query parameter is still not supported:
(files have been changing places due to some coding refactoring for monorepo)

https://github.com/RocketChat/Rocket.Chat/blob/f0c37c5a8c904181577b80d239255284ac6a1280/apps/meteor/app/livechat/imports/server/rest/rooms.js#L26

Also, [tried to look for other endpoint](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/list) but it filters by **t: "c".**

I will mark as bug and raise it with our team. 

Thanks for pointing out.

**Comment by dudanogueira** [comment]
This is the documentation of this API, for reference:
https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/omnichannel-endpoints/rooms/livechat-rooms-list

**Comment by ykabusalah** [comment]
Could I attempt to fix this issue? And if so, would you mind assigning it to me?

**Comment by Shofiya2003** [comment]
I want to work on the issue. Could you please assign it to me.

**Comment by debdutdeb** [comment]
@ykabusalah @Shofiya2003 feel free to work on this. Please join our [#contributors](https://open.rocket.chat/channel/contributors) channel and leave me a ping (\@debdut.chakraborty). You can ask me any related questions there.

**Comment by Shofiya2003** [comment]
@debdutdeb  I was working on the issue. I followed all the steps in the documentation to setup rocket chat locally but when I run yarn build I get this error  'command (packages/ui-contexts) yarn run build exited (129)' . Could you please help me?

**Comment by Shofiya2003** [comment]
@debdutdeb I tried pulling the changes but there are some changes in the folder that I did not make. I tried stashing and reverting them but there is an error. What should I do?
error: lstat("apps/meteor/.storybook/.eslintrc.js"): Function not implemented

fatal: Unable to process path apps/meteor/.storybook/.eslintrc.js

Cannot save the current worktree state

This it the error which I get after staging and stashing the commits
Should I do the cloning process again?

**Comment by dudanogueira** [comment]
Closing this issue, if needed, please, reopen :)

**Comment by Aashray446** [comment]
Hi, is this issue still open? Can I start working on it? @debdutdeb

**Comment by Aashray446** [comment]
I have explored the codebase related to this issue, currently, I guess instead of query support, custom fields are given to perform any search for custom fields.  Am I correct?

**Comment by coderboy-yash** [comment]
Hi, @debdutdeb  is this issue still open I want to work on this issue.
Can you please assign this to me?

**Comment by lokesh-wagh** [comment]
I think we need to change the findRoomsWithCriteria to include msgs as a query parameter

**Comment by lokesh-wagh** [comment]
Hey @debdutdeb @dudanogueira is this issue still relevant 
I mean has it been patched or by-passed in previous version's

**Comment by Starkz24** [comment]
Since this issue has been fixed with [this PR](https://github.com/RocketChat/Rocket.Chat/pull/30542), can we please close this issue?

**Comment by VaidyaPranav** [comment]
Hi, I’m interested in working on this issue. Could you assign it to me, or let me know if it’s already being worked on?

**Comment by souvik150** [comment]
I would love to pick this up!

**Comment by Bhavna1312** [comment]
Hello! I’m new to open source but eager to learn and contribute. I’d like to work on this issue.

**Comment by SarthakB-06** [comment]
Hello! I'm new to open source and i would like to work on this issue

**Comment by ghuleomkar** [comment]
Hello i am new to open source and i would like to work on this issue

**Comment by Roronoa-santhosh** [comment]
Hi, I'm new to open source and I'd like to work on this issue.

**Comment by codeboy-pro** [comment]
Hello i am new to open source and i would like to work on this issue

**Comment by finexaakash** [comment]
Hi 👋  
I’m a beginner contributor and would like to work on this issue.  
Is it still valid, and can you please assign it to me or guide me where to start?

**Comment by Yashika-code** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?

**Comment by wineerteam** [comment]
Hi team 👋

I’ve gone through the issue description and comments.
The problem looks clear and reproducible on my side.

I’d like to work on this issue and submit a fix.
Please let me know if I can proceed.

Thanks!

**Comment by dikshaa2909** [comment]
Hi, I’d like to work on this issue.
I have the Rocket.Chat development environment running locally and I’m investigating the problem.
Please let me know if this issue is still relevant and can be assigned to me.
Thanks!

**Comment by shash-hq** [comment]
Maintainers, I'd like to work on this. I've analyzed the endpoints and can implement the missing query parameter filtering for the Livechat rooms API. Can you assign it to me?

**Comment by Bugbuster2004** [comment]
@dudanogueira may i work on this issue , i have figured it out on how to fix this

**Comment by dnyaneshwaripachankar-droid** [comment]
hello!
may i work on this issue , and study codebase backend and frontend  and i`d like to work on this query parameter filtering the app meteor livechat

**Comment by OMNIA-ibrahiim** [comment]
I've traced the bug across 4 files and identified the fix. I'd like to work on this , is it still available?
