### ISSUE TITLE
Conversational UX Platform

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2531]
Build intelligent speech interfaces for apps, devices, and web
Ref: https://api.ai/

**Comment by jonbaer** [comment]
I think this could be something like an admin server package inside of rocketchat-hubot (ie: Rocket.Cat) which allows for full customizations (scripts to load, NLP/NER setup, etc) ... there is a possibility that more bot applications (and domains) may come from work being done on Botkit (https://github.com/howdyai/botkit) than Hubot at some point so it would be nice to see support for both.  I think the api.ai tools are pretty domain specific and could probably already work out of the box with integration webhooks as is.  I think this all depends on how much bot setup you would like to see happen inside of Rocket.Chat itself (from scalability viewpoint it may need to be a different app IMHO).

**Comment by timkinnane** [comment]
Seems like some very broad issues being discussed here that would not be addressed in this repo. @engelgabriel should we close or re-purpose this issue? It might be actionable to support a Dialogflow adapter, other than that I think the larger issue of creating an interface for conversation design would be something specific to each bot platform/framework. I don't see it being possible to provide as an agnostic UX unless it was simply embedding the dashboard within admin views.

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas

**Comment by timkinnane** [comment]
Closing now as this discussion predates the bots project which has now identified targeted framework adapters for
- #9937 Botkit
- #10457 Rasa
- #5772 Botpress
