### ISSUE TITLE
Atualizar Servidor Rocket

### ISSUE THREAD

**Issue by vrct07** [RocketChat/Rocket.Chat#25328]
Como eu faço para atualizar meu servidor Rocket para a versão mais atual ? Parece que ele está desatualizado.
Parece que meu servidor está totalmente desatualizado, e eu não consegui achar nada na documentação que me auxilie atualiza-lo para a versão mais atual.

![image](https://user-images.githubusercontent.com/45132739/165649087-e410d7b9-f032-4983-bdd9-c6783d87528e.png)

**Comment by dudanogueira** [comment]
Oi!

Primeiro precisamos saber como foi instalado o seu servidor. Você está usando a versão Cloud? Por favor, considere usar o [canal comunitário de suporte](https://open.rocket.chat/channel/support) ou [fórums](https://forums.rocket.chat/) para suporte antes abrir um novo Issue. Para clientes Enterprise, existe [acesso o sistema de suporte](https://support.rocket.chat/)
