### ISSUE TITLE
Slack Import - Error when importing a channel and not their creator

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#2532]
Your Rocket.Chat version: 0.22

If you import a channel but not the user who created it in Slack, the import will fail.

See: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-importer-slack%2Fserver%2FSlackImporter.coffee#L166

**Comment by graywolf336** [comment]
Should we opt to not import the channel or should we make the channel creator the admin or rocket.cat?

**Comment by sampaiodiego** [comment]
Maybe we could set as owner the user who is importing.

**Comment by graywolf336** [comment]
Ah yeah, that'll work best.
