### ISSUE TITLE
Chrome 101+ with navigator.userAgent

### ISSUE THREAD

**Issue by detain** [RocketChat/Rocket.Chat#25322]
According to [Chromium Blog (User agent reduction](https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html) it sounds like using _navigator.userAgent_ will only start working once per pageload .. after that it will give a blank response. the code in particular its complaining about is 
rocketchat\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js

```
if (navigator.userAgent.indexOf('Chrome') > -1 && navigator.userAgent.indexOf('Edge') === -1 || navigator.userAgent.indexOf('Firefox') > -1) {
```
That can be replaced with 
```
if (navigator.userAgent.match(/chrodme|edge|firefox/i) !== null) {
```
which should resolve the problem of callinjg navigator.userAgent multple times

**Comment by dudanogueira** [comment]
Hi! Please, when opening a new issue, provide the required details.

What are the versions you are using? 
How can we reproduce this error?

I believe this is something at react-dom node module itself.

**Comment by ankar84** [comment]
> How can we reproduce this error?

Guess it's now a bug report, but code optimization, that should be a PR.
