### ISSUE TITLE
Configurações de Call Center

### ISSUE THREAD

**Issue by vrct07** [RocketChat/Rocket.Chat#25324]
Olá, me chamo Vitor e estou enfrentando um problema e gostaria de ajuda. As configurações do Call Center não aparecem no nosso servidor, tenho seguido o caminho Menu Avatar > Administração > Configurações > Pesquisar Central de Atendimento e não aparece o Menu. Gostaria de saber se preciso habilitar algo para aparecer.

![image](https://user-images.githubusercontent.com/45132739/165582471-8d43bacd-ffe0-4024-ba59-128ee4dc4b41.png)
![image](https://user-images.githubusercontent.com/45132739/165582863-4692f7ed-4410-483b-a6e2-9cf4604b6461.png)

**Comment by vrct07** [comment]
Essa é minha versão. 

![image](https://user-images.githubusercontent.com/45132739/165586552-f986df97-6b77-4b52-b56c-b26617ffb691.png)

**Comment by dudanogueira** [comment]
Oi!

**[PT]**
O VOIP ainda é uma função em estágio experimental, então é recomendado estar sempre na versão mais atual (4.6.3), pois muita coisa tem mudado.

Por favor, considere usar o [canal comunitário de suporte](https://open.rocket.chat/channel/support) ou [fórums](https://forums.rocket.chat/) para suporte antes abrir um novo Issue. Para clientes Enterprise, existe [acesso o sistema de suporte](https://support.rocket.chat/)

**[EN]**
Voip feature is still in experimental stage. So we recommend to always use the latest version, as a lot of things have been changing.

Please, consider using our [community support channel](https://open.rocket.chat/channel/support) ou [Forums](https://forums.rocket.chat/) for community support before opening an Issue. For Enterprise users, there is [a support ticket system too](https://support.rocket.chat/)

Thanks!
