### ISSUE TITLE
Member list disappears after toggle

### ISSUE THREAD

**Issue by Morgy93** [RocketChat/Rocket.Chat#2533]
Your Rocket.Chat version: 0.22.0

![rocketchat_member](https://cloud.githubusercontent.com/assets/7961978/13848988/7d25418a-ec54-11e5-89e7-454028aad9ff.gif)

The member list moves to the left if you close and open it again while viewing a member.
Happens on the browser version and Windows Client (which is basically just a webview)
Would love to test that on your https://demo.rocket.chat/ but it just returns some 500 error =)
I should mabe make a new issue for that one..

**Comment by Morgy93** [comment]
Well your demo is back again and the same bug occurs.

**Comment by sampaiodiego** [comment]
@Morgy93 can you please confirm that this is still happening?

I just tried it but I'm not able to reproduce.

Tested on Linux: Chrome 49, desktop app 1.2.0, Firefox 45
