### ISSUE TITLE
Add ReplyGif reactions

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#2536]
it would be nice if you add replygif reactions

**Comment by Julime** [comment]
![lmzzpmm_700wa_0](https://cloud.githubusercontent.com/assets/7944656/13873494/22a33cdc-ecf2-11e5-9e7f-976bd4a34fdf.gif)

**Comment by Morgy93** [comment]
![pm0qorl_700wa_0 1](https://cloud.githubusercontent.com/assets/7961978/13873560/97a8086e-ecf2-11e5-85ab-1a29698466b5.gif)

**Comment by engelgabriel** [comment]
Yay, Replygif now has a REST API. It's still very new and everything is subject to change without prior notice. Please let me know if you want to use it in production - just as much for your own sake. Feedback and requests for additional endpoints or data are welcome.
CORS is currently enabled. Use the API key "39YAprx5Yi" for all requests.
Example
```
http://replygif.net/api/tags?api-key=39YAprx5Yi
```

Docs: http://replygif.net/about

**Comment by lvh1** [comment]
If you have hubot installed you could use this https://www.npmjs.com/package/hubot-reaction 
Works pretty well

**Comment by jaredhilton** [comment]
This integration is in progress.

**Comment by jaredhilton** [comment]
[PR merged on Rocket.Chat.Integrations](https://github.com/RocketChat/Rocket.Chat.Integrations/pull/1). [PR opened on Rocket.Chat.Docs](https://github.com/RocketChat/Rocket.Chat.Docs/pull/230).

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

So if I get this right, this can be closed then? If not, please get back to me :)

Cheers
Thomas
