### ISSUE TITLE
iOS Badge shows unread messages, despite the fact that there are none

### ISSUE THREAD

**Issue by mrwee** [RocketChat/Rocket.Chat#25370]
### Description:

In the iOS App v4.27.0 the App badge is often out-of-sync in terms of unread messages. 
![image](https://user-images.githubusercontent.com/6720774/166250882-de15f71e-582f-4cea-b4ea-0cbb018345f1.png)
If I access the server via Windows client or HTTPS, then there are no unread messages. Stopping the app, and starting it again, makes no difference.

### Steps to reproduce:

Difficult to say, what triggers the lack of sync, so I have no good way of reproducing.

### Expected behavior:

The unread badge should follow the actual unread status of the user.

### Actual behavior:

Badge shows unread messages, but there are none (as per problem description)

### Server Setup Information:

Rocket.Chat server Version 4.3.1
Apps Engine Version: 1.29.1
Node Version: v12.18.4
MongoDB: 5.0.6 / wiredTiger (oplog Enabled)

### Client Setup Information

iOS App v4.27.0 
iPhone 13 Pro Max, iOS 15.4.1.

**Comment by lovekyleman** [comment]
Have the same issue

**Comment by vinceogne** [comment]
Same here

**Comment by stephenanspach** [comment]
Me too, just started happening yesterday

**Comment by Sc0th** [comment]
same....

**Comment by dudanogueira** [comment]
Are all of you guys using iOS too?

**Comment by ankar84** [comment]
Could be already fixed in 4.27.1 https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.27.1

**Comment by mrwee** [comment]
@ankar84 So it seems. I can't reproduce it anymore after iOS app update to 4.27.1. Closing the ticket :)
