### ISSUE TITLE
Can't setup push notifications

### ISSUE THREAD

**Issue by nicolamori** [RocketChat/Rocket.Chat#25379]
### Description:
I followed [these instructions](https://desk.rocket.chat/portal/en/kb/articles/i-don-t-receive-push-messages) to configure push notifications for my self-hosted server. Despite following every step the test push is not sent to my Android device (the notifications for the app are enabled). There is only one step I was unable to perform: in the `Administration->General->Notifications` panel I don't have any `Always notify mobile` switch to turn on. Anyway the test push is not sent/received even with the mobile app in foreground, so I don't know if this detail is relevant.

### Steps to reproduce:

1.Configure the push notifications as explained at the above link
2.Connect a mobile client
3. Send a test push

### Expected behavior:
A notification should appear on the mobile device

### Actual behavior:
No notification appears.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.3
- Operating System: Debian Buster 
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4.0

### Client Setup Information

- Mobile App Version: 4.27.0
- Operating System: LineageOS 18.1 (Android 11)

### Relevant logs:
Server log:
```
rocketchat            | {"level":40,"time":"2022-05-03T10:41:35.609Z","pid":1,"hostname":"d586df75db74","name":"Push","msg":"Error sending push to gateway (not authorized) {\"statusCode\":401,\"content\":\"{\\\"code\\\":121,\\\"error\\\":\\\"rocket.chat cloud registration required\\\",\\\"requestId\\\":\\\"692e6638-fda0-40d2-b380-ba57e239488d\\\",\\\"status\\\":401}\",\"headers\":{\"access-control-allow-headers\":\"Content-Type, Authorization, Content-Length, X-Requested-With\",\"access-control-allow-methods\":\"GET, PUT, POST, DELETE, OPTIONS\",\"access-control-allow-origin\":\"*\",\"access-control-expose-headers\":\"Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by\",\"cache-control\":\"private, no-cache, no-store, must-revalidate\",\"connection\":\"close\",\"content-length\":\"126\",\"content-type\":\"application/json; charset=utf-8\",\"date\":\"Tue, 03 May 2022 10:41:35 GMT\",\"expires\":\"-1\",\"pragma\":\"no-cache\",\"vary\":\"Accept-Encoding\",\"x-powered-by\":\"Rocket Fuel and Rocketeers\"},\"ok\":false,\"data\":{\"code\":121,\"error\":\"rocket.chat cloud registration required\",\"requestId\":\"692e6638-fda0-40d2-b380-ba57e239488d\",\"status\":401}}"}
```
No logs from browser.

**Comment by debdutdeb** [comment]
LineageOS? my custom rom knowledge is a bit rusty, it's been a while, but, do you have gapps installed? Which one? you need google services for push notifications to work.

**Comment by ankar84** [comment]
`Error sending push to gateway (not authorized)`
1. You are using your whitelabel app or original Rocket.Chat app from Google Play Store?
2. If using Rocket.Chat app - did you register your workspace in cloud console? And also you need to agree with all conditions in Admin UI.


> you need google services for push notifications to work

That's true!

**Comment by nicolamori** [comment]
@ankar84 Actually I didn't properly setup the gateway, I missed the cloud registration step. I am new to Rocket.Chat and from the documentation at the link reported on my original message it was not clear to me that I had to register on the Rocket.Cloud chat. Now push notification works, thanks!
