### ISSUE TITLE
Instagram Direct does not receive messages on Rocket

### ISSUE THREAD

**Issue by vrct07** [RocketChat/Rocket.Chat#25374]
**Description:**

My Instagram Direct app doesn't receive omnichannel messages.

**Steps to reproduce:**

1 - In the admin panel. Setup -> Apps -> Instagram Direct > Install.
2 - link to instagram.
3 - Send a message to Instagram.

**Expected behavior:**

Customer sends a message on Instagram Direct and the message is received within the Rocket dashboard.

**Actual behavior:**

In just 1 specific page, Instagram messages do not reach Rocket, I tested it with other pages and it worked normally. When I put this page back, it doesn't receive messages from Instagram, only from Facebook Messenger.

**Server Setup Information:**

Versão
4.6.1

Versão do mecanismo de aplicativos
1.31.0

Versão do node
v14.18.3

Migração do banco de dados
258 (20 de Abril de 2022 às 20:34)

MongoDB
4.2.8 / wiredTiger (oplog Ativado)

**Client Setup Information**

Desktop App or Browser Version: 3.8.3
Operating System: Win10

**Comment by Mervan2** [comment]
> **Description:**
> 
> 
> 
> My Instagram Direct app doesn't receive omnichannel messages.
> 
> 
> 
> **Steps to reproduce:**
> 
> 
> 
> 1 - In the admin panel. Setup -> Apps -> Instagram Direct > Install.
> 
> 2 - link to instagram.
> 
> 3 - Send a message to Instagram.
> 
> 
> 
> **Expected behavior:**
> 
> 
> 
> Customer sends a message on Instagram Direct and the message is received within the Rocket dashboard.
> 
> 
> 
> **Actual behavior:**
> 
> 
> 
> In just 1 specific page, Instagram messages do not reach Rocket, I tested it with other pages and it worked normally. When I put this page back, it doesn't receive messages from Instagram, only from Facebook Messenger.
> 
> 
> 
> **Server Setup Information:**
> 
> 
> 
> Versão
> 
> 4.6.1
> 
> 
> 
> Versão do mecanismo de aplicativos
> 
> 1.31.0
> 
> 
> 
> Versão do node
> 
> v14.18.3
> 
> 
> 
> Migração do banco de dados
> 
> 258 (20 de Abril de 2022 às 20:34)
> 
> 
> 
> MongoDB
> 
> 4.2.8 / wiredTiger (oplog Ativado)
> 
> 
> 
> **Client Setup Information**
> 
> 
> 
> Desktop App or Browser Version: 3.8.3
> 
> Operating System: Win10

**Comment by dudanogueira** [comment]
Hi!

For support for paid apps or Enterprise Edition, please, refer to http://support.rocket.chat/

Thanks!
