### ISSUE TITLE
Chat menu requires two clicks to open

### ISSUE THREAD

**Issue by Feuermurmel** [RocketChat/Rocket.Chat#25399]
**Describe the bug**

In the top-left corner of the chat window is a strip of icons to access chat-specific views and dialogs. The rightmost (three dots in a vertical line) opens a menu with the options _Starred messages_, _Pinned Messages_ etc. Opening that menu requires two clicks instead of one to open, which I find unintuitive.

What operating system and which version? macOS 12.3.1
Which version of Rocket.Chat (Server)? (need instructions on how to find this out from the client app)
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.8.4
Is there any setting relevant changed? (what is "setting relevant"?)

**To Reproduce**

1. Open any chat or channel.
2. Hover cursor onto menu in top right corner.
3. Click the menu before waiting too long.

**Expected behavior**

The menu should open. Instead, only the tooltip "Options" is shown. Please see the screen recording below.

**Screenshots**

https://user-images.githubusercontent.com/50332/166637590-4ad6e955-482b-464b-841b-693aefc0c336.mp4

**Comment by dudanogueira** [comment]
Hi!

We need to know the server versions.

Go to you avatar (top left corner), then Administration, Then info.

Thanks!

**Comment by Feuermurmel** [comment]
> Go to you avatar (top left corner), then Administration, Then info.

Uhh, I'm not sure what you mean. I only have these options:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/50332/168483209-3a9acf8b-7dab-46ed-b9a6-5aa4cb1fbabe.png">

I'm not an admin on the server, mind you.

**Comment by Feuermurmel** [comment]
I escalated this and got this info:

```
Version 4.6.2
Apps Engine Version 1.31.0
Node Version v14.18.3
Database Migration 258 (April 18, 2022 3:55 PM)
MongoDB 4.2.17 / wiredTiger (oplog Enabled)
Commit Details HEAD: (e8cb66624)
Branch: HEAD
```

**Comment by Feuermurmel** [comment]
Is there more information I can or should provide? :)

**Comment by Feuermurmel** [comment]
I'm not going to try to prevent this issue from being closed anymore after this. The Rocket.Chat native UI feels finicky and buggy. I'm trying to help improve things one step at a time here.

But having to fight with a bot instead of getting a definitive response from a human makes means I'm wasting my time. It would feel much better if someone came along here and said e.g. "No, we're not going working on this."

**Comment by jeanfbrito** [comment]
> I'm not going to try to prevent this issue from being closed anymore after this. The Rocket.Chat native UI feels finicky and buggy. I'm trying to help improve things one step at a time here.
> 
> But having to fight with a bot instead of getting a definitive response from a human makes means I'm wasting my time. It would feel much better if someone came along here and said e.g. "No, we're not going working on this."

Update the server to a newer version to see if this is fixed. It doesn't happens to me on open.rocket.chat.
You can always open a pull request with the fix to help improve.

**Comment by Feuermurmel** [comment]
We have currently run version 4.8.7, the problem still appears. Are you running version 5?
