### ISSUE TITLE
Use Events or Streams to broadcast messages

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#254]
The idea is to reduce the need for the merge box, broadcasting all messages of each room, and have the minimongo to update the entire message on the local collection.

Arunoda's Streams looked promising, but it discontinued 
http://arunoda.github.io/meteor-streams/
https://github.com/arunoda/meteor-streams/

Maybe we could ask to become the maintained or at least fork it.
https://github.com/arunoda/meteor-streams/issues/21#issuecomment-59030380

Alternatives:
https://github.com/raix/Meteor-EventDDP
https://github.com/Lepozepo/meteor-streams/

**Comment by sampaiodiego** [comment]
done by #311

**Comment by coxley** [comment]
Is this something that could be/is exposed for an external app to take advantage? Would be very cool to be able to hack together a real-time feed for a room or something.

**Comment by rodrigok** [comment]
@coxley, yes, the current implementation of streams that we are using is based over DDP methods and publications, so any external apps can send streams using methods and receive streams listening for publications.

If you need I can explain more how to do this.

**Comment by coxley** [comment]
@rodrigok If you wouldn't mind, it'd be great to learn more about how to do it! :)

**Comment by Sing-Li** [comment]
@coxley   The best example we have - is an external application that uses NO METEOR CODE at all. 

Yet, it intercepts the Rocket.Chat's DDP message firehose,  processes, and reintroduces messages back into the system.

It is only about a single page of CoffeeScript code, and completely dockerized - so it is very easy to try and (hopefully) understand. 

The repo is here : [Rocket.Chat Hubot Adapter](https://github.com/RocketChat/hubot-rocketchat)

Hope this is helpful.

**Comment by rodrigok** [comment]
If you need to handle streams manually:

```javascript
// Connect to Rocket.Chat via DDP
connection = DDP.connect('http://localhost:3000');

//// LISTEN EVENT
// Create a new collection to monitor typing events in remote connection
collection = new Meteor.Collection('stream-typing', connection);

// Subscribe to typing events
connection.subscribe('stream-typing');

// Handle events on add of collection and reserve an especial item of
// type subscriptionId to be used with Meteor Calls
collection.find({}).observe({
	added: function(item){
		if (item.type == 'subscriptionId') {
			window.subscriptionId = item._id;
		}
		console.log(item)
	}
});


//// EMIT EVENT
// Call stream on connection passing subscription id and arguments
// first argument must be event name, stream-typing is the stream name
connection.call('stream-typing', subscriptionId, ['typing', {room: 'GENERAL', username: 'rodrigo.rocket.team', start: true}]);
```

**Comment by Sing-Li** [comment]
@rodrigok   captured for future reference ... https://github.com/RocketChat/Rocket.Chat/wiki/Real-time-messaging-APIs   :smile:

**Comment by rodrigok** [comment]
Thanks @Sing-Li, you are awesome :D

**Comment by markhorsman** [comment]
Hello everyone. I tried @rodrigok approach but got the following error:

a["{\"msg\":\"nosub\",\"id\":\"9ZFTePErqMDzvuYyv\",\"error\":{\"error\":404,\"reason\":\"Subscription not found\",\"message\":\"Subscription not found [404]\",\"errorType\":\"Meteor.Error\"}}"] 

Because I never get an subscriptionId, the connection.call line also fails.
It looks like the 'stream-typing' sub does not exist.

Any suggestions?

**Comment by krisleech** [comment]
@markhorsman I know very little about this, but I found with `stream-messages` I could get messages for every room. I'm using Asteroid, not DDP library.

```
asteroid.subscribe("stream-messages", roomId, 10);
```

However it seems `roomId` is ignored and you get all messages.
