### ISSUE TITLE
No login prompt anymore

### ISSUE THREAD

**Issue by mrwee** [RocketChat/Rocket.Chat#25404]
Our existing Rocket.Chat installation no longer provides a login prompt for either weblogin (Edge / Firefox) or the WIndows client.
When browsing to the URL, a white box appears/dissapeares and the page is left black. When trying to add the server in the Windows client (3.8.6) nothing happens. When restarting the Windows app, the server is gone.

Existing iOS users, can still access the server. 
Nothing has been changed on the server / infrasstructure.

Server:
Rocket.Chat server Version 4.3.1
Apps Engine Version: 1.29.1
Node Version: v12.18.4
MongoDB: 5.0.6 / wiredTiger (oplog Enabled)

**Comment by mrwee** [comment]
Using the same Windows client, I can connect to a 4.7.0 server :(

**Comment by dudanogueira** [comment]
Hi!

Can you see any outstanding logs?

Can you try on an incognito window?

This is certainly not a bug or at least not easily reproducible. 

Please consider our [Community Support Channel](https://open.rocket.chat/channel/support) so we can figure this out and maybe reproduce, then open a bug.

Also, some information about [how to get help](https://docs.rocket.chat/getting-support/asking-for-help)
