### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by khodge281** [RocketChat/Rocket.Chat#25433]

**Comment by khodge281** [comment]
> I pay you people a LOT of money every month to communicate with my employees. It has become cumbersome and is not working worth a shit. NOT it has me locked out and says the password i have is wrong on my desktop, and wants me to install some new server app. BULLSHIT, ENABLE MY DAMN PASSWORD LIKE IT WAS AND LET ME LOG IN.
> 
> AND I DONT HAVE DAYS TO WASTE, I EXPECT HELP NOW!!!!!!!

After screwing around with it and pushing everything i could, i finally got my server to reload. You people need to make this more user friendly. It DOES NOT do the things it did when i signed up.

**Comment by geekgonecrazy** [comment]
I’ve sent your info to support team.  Please make sure you’ve opened a ticket there and they will get to it asap.


If it’s just a password issue please try the password reset option which should work just fine
