### ISSUE TITLE
Integrations body data not available

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#2543]
Hi, im using the develop branch of docker rocket chat, i want to integrate with the Amazon SNS incoming weebhook so that for a special topic SNS broadcast the message to rocket and then rocket will initmate to my team members. The problem here is amazon is sending the data but im unable to see the data in request object of incoming script but i see the headers are present. Im checking the data is present or not by consoleing the request object

`request.headers` have the data but `request.content` & `request.content_raw` is `{}`.

**Comment by engelgabriel** [comment]
Can you do a log of the full `request.headers` object? Maybe SNS is sending a content-type that we are no expecting.

**Comment by pavankumarkatakam** [comment]
From headers i got that content type is text/plain  `'content-type':text/plain; charset=UTF-8'` , If this is the case what i want to do now, From SNS side there is no option to change the content-type as well as method also.

**Comment by engelgabriel** [comment]
@rodrigok in that case, should the `request.content_raw` still have the whole content as a string?
Do we already parse the content when the type is text/plain 'content-type':text/plain; charset=UTF-8'?

**Comment by pavankumarkatakam** [comment]
But, `request.content_raw` and `request.content` is `undefined`.

**Comment by rodrigok** [comment]
@pavankumarkatakam @engelgabriel Fixed by https://github.com/RocketChat/Rocket.Chat/commit/43e97f495f79f1812d2d807f4270c251eb65c2ed

Now `request.content_raw` gets the value directly from request buffer, should work better now.

@pavankumarkatakam can you use our latest develop version to see if this is fixed?

**Comment by pavankumarkatakam** [comment]
Yeah sure please a minute.

**Comment by pavankumarkatakam** [comment]
Yeah, now getting the content_raw and of course content is {}. Thanks.

**Comment by pavankumarkatakam** [comment]
Hi here is my script

    class Script{
 
       process_incoming_request({request})
      {
        var ses_message =JSON.parse(request.content_raw);
        var original_message= JSON.parse(ses_message.Message);
        return {
            text:original_message.text
        };
     }
    }

But logs showing the `Integrations -> Incoming WebHook.debug result undefined`

**Comment by rodrigok** [comment]
@pavankumarkatakam you should return content.text:

```
  return {
    content: {
        text:original_message.text
    }
  };
```
