### ISSUE TITLE
Twice gzipped when in gridfs

### ISSUE THREAD

**Issue by tuxBurner** [RocketChat/Rocket.Chat#2545]
Your Rocket.Chat version: 0.22.0

We found out that when the rocketchat sever stores a txt file in the gridfs and you download it again it gets twice gzipped. It seems that the mongodb gziped the file and that meteor gezipped the file again.

When we changed it to filesystem storage, only meteor gezipped the file and everything went well.

**Comment by engelgabriel** [comment]
This is urgent. We are working on a fix to the next release on Monday.

**Comment by engelgabriel** [comment]
Same issue is happening on https://github.com/RocketChat/Rocket.Chat/issues/2547

**Comment by tuxBurner** [comment]
Thx
