### ISSUE TITLE
no access

### ISSUE THREAD

**Issue by jwhill10** [RocketChat/Rocket.Chat#25459]
this is 2nd time.
says either no acct or password wrong.
i fixed yesterday.
TODAY its saying same thing.
can you fix?
thanks
jerry

**Comment by dudanogueira** [comment]
Hi, please refer to our Community Support Channel on how to get support.

Also, please read our [Asking for Help Guide](https://docs.rocket.chat/getting-support/asking-for-help)

Closing as this cannot be considered a bug.
