### ISSUE TITLE
Error render SVG to PNG on Amazon Linux 2

### ISSUE THREAD

**Issue by taihoa** [RocketChat/Rocket.Chat#25466]
### Description:

When making a request to the channel's PNG avatar or the user uses the name as the avatar, the server is returning the avatar with an error displaying the unicode of the name.

### Steps to reproduce:

1. Request avatar: http://localhost:3000/avatar/room/JISHIN?format=png
2. Error
![image](https://user-images.githubusercontent.com/8847573/167812475-c13a351a-6bd9-48f7-a807-477ac1bc8a48.png)

### Expected behavior:
Expect to return the correct image with the name of the room or user
![image](https://user-images.githubusercontent.com/8847573/167812588-e47dc9f0-bf3d-49fd-89c0-4ce6c80b867e.png)

I looked for the cause, and found that sharp library is giving this error on Amazon linux 2
https://github.com/lovell/sharp/issues/3109

Anyone have a solution to this problem?
Hope the helping!

### Server Setup Information:
- Operating System: Amazon linux 2

**Comment by Kamp11** [comment]
Same problem on version 4.8.1, snap, Ubuntu 20.04.
How to solve this problem?

**Comment by taihoa** [comment]
> Same problem on version 4.8.1, snap, Ubuntu 20.04. How to solve this problem?
Cause: Server Amazon linux 2 miss font Japanese
You can try install font for server Amazon Linux 2 by command below:
sudo yum makecache
sudo yum install google-noto-sans-japanese-fonts.noarch
