### ISSUE TITLE
4.7.0 regression: edit button not displayed in the first minute after sending a new message

### ISSUE THREAD

**Issue by Nico264** [RocketChat/Rocket.Chat#25478]
### Description:

In rooms where editing is enabled and limited in time, the client does not display the edit button in the first minute after sending.
Editing by pressing the up arrow key or with other clients still work as expected. It's only a UI issue.

I think I tracked this down in [messageActionDefault.ts](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/ui-utils/client/lib/messageActionDefault.ts#L174):
```
return !!currentTsDiff && currentTsDiff < blockEditInMinutes;
```

where `currentTsDiff` is the difference in minutes between the current time and the message timestamp.
During the first minute, `currentTsDiff` is `0` hence `!!currentTsDiff` is `false` and the edit button is not displayed.

This was introduced [here](https://github.com/RocketChat/Rocket.Chat/commit/71d0ed8e3209a95e6ecb897a83d9a6b6422380af#diff-1c4229889c586572f8b981b5926e32737dfaf00a9510dc5f4e92fd098092f26cR174).

### Steps to reproduce:

1. Send a message in a room with edits enabled enabled for settings.Message_AllowEditing_BlockEditInMinutes > 1.
2. Hover the message, the edit button does not appear during the first minute.

### Expected behavior:

The edit button is available as soon as the message is sent.

### Actual behavior:

The edit button only appears one minute later.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Firefox 100
- Operating System: OpenSUSE

**Comment by ankar84** [comment]
Confirm that issue on 4.7.0!

**Comment by usefool** [comment]
Same for me - if the "block edit after ..." option is set

Workaround: set " Block Message Editing After (n) Minutes" Option to 0 (to disable it)

**Comment by saschafoerster** [comment]
Still there on 4.8.1

**Comment by danel1** [comment]
@debdutdeb @sampaiodiego This is quite "breaking" for most of our users, since they've used the edit button mostly. Also we've set a limit to disable editing after one minute - so for us the button is gone completely... This should be an easy and fast fix - please take a look at it.

**Comment by debdutdeb** [comment]
Hey, thanks for the ping. I'll look into it tonight. In the meantime if someone would like to open a PR, we'll pf course accept that too.

**Comment by danel1** [comment]
> Hey, thanks for the ping. I'll look into it tonight. In the meantime if someone would like to open a PR, we'll pf course accept that too.

See #25724
