### ISSUE TITLE
gear wheel bug

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#2551]
Something atleast i find disturbing is when you press the gear wheel and decide to not press any of the icons you should be able to click anywhere in the chat for the menu to dissapear. Now you have to click on the small arrow, else it wont go away :)

**Comment by cedemore** [comment]
+1 i find this annoying too.. :-/

**Comment by mccambridge** [comment]
Looks like this is fixed in 0.26?
