### ISSUE TITLE
4.7.0 and 4.7.1 - web clients do not work, mobile clients work

### ISSUE THREAD

**Issue by fc757** [RocketChat/Rocket.Chat#25513]
NodeJS: 14.18.3
Mongodb: 5.0.8

When building 4.7.0 or 4.7.1 get this:

---

`linux-x64-83-glibc` exists; testing
Binary is fine; exiting

> gc-stats@1.4.0 install /tmp/bundle/programs/server/npm/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.4.0 and node@14.18.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz

---

When starting get this:

---

May 14 09:39:13 cetialphafive systemd[1]: Started The Rocket.Chat server.
May 14 09:39:18 cetialphafive node[226292]: (node:226292) UnhandledPromiseRejectionWarning: MongoError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1", expireAfterSeconds: 2592000 }, existing index: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1" }
May 14 09:39:18 cetialphafive node[226292]:     at MessageStream.messageHandler (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
May 14 09:39:18 cetialphafive node[226292]:     at MessageStream.emit (events.js:400:28)
May 14 09:39:18 cetialphafive node[226292]:     at MessageStream.emit (domain.js:475:12)
May 14 09:39:18 cetialphafive node[226292]:     at processIncomingData (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
May 14 09:39:18 cetialphafive node[226292]:     at MessageStream._write (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
May 14 09:39:18 cetialphafive node[226292]:     at writeOrBuffer (internal/streams/writable.js:358:12)
May 14 09:39:18 cetialphafive node[226292]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
May 14 09:39:18 cetialphafive node[226292]:     at Socket.ondata (internal/streams/readable.js:731:22)
May 14 09:39:18 cetialphafive node[226292]:     at Socket.emit (events.js:400:28)
May 14 09:39:18 cetialphafive node[226292]:     at Socket.emit (domain.js:475:12)
May 14 09:39:18 cetialphafive node[226292]:     at addChunk (internal/streams/readable.js:293:12)
May 14 09:39:18 cetialphafive node[226292]:     at readableAddChunk (internal/streams/readable.js:267:9)
May 14 09:39:18 cetialphafive node[226292]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
May 14 09:39:18 cetialphafive node[226292]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
May 14 09:39:18 cetialphafive node[226292]:     at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
May 14 09:39:18 cetialphafive node[226292]: (Use `node --trace-warnings ...` to show where the warning was created)
May 14 09:39:18 cetialphafive node[226292]: (node:226292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
May 14 09:39:18 cetialphafive node[226292]: (node:226292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

---

![image](https://user-images.githubusercontent.com/4654695/168428352-8408020c-20e0-4473-a285-e42ddea02738.png)

**Comment by ali-alhaidary** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/25396
https://github.com/RocketChat/Rocket.Chat/issues/25512

**Comment by ankar84** [comment]
related to https://github.com/RocketChat/Rocket.Chat/issues/25460

**Comment by geekgonecrazy** [comment]
Closing in favor of #25460
