### ISSUE TITLE
4.7.1 option to edit message not shown anymore

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#25533]
### Description:

After updating to 4.7.1 we cannot edit messages anymore. The option to do that is just gone. I double checked Administation -> Messages. It's still allowed to edit messages.

### Steps to reproduce:

1. Write a message
2. Click on the three dots menu on the right side of the message
3. No "edit" option anymore

### Expected behavior:

"Edit option should be still there.

### Actual behavior:

Well, no edit option to be seen.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 4
- DB Replicaset Oplog: sure
- NodeJS Version: 14
- MongoDB Version: 4.4

**Comment by dudanogueira** [comment]
I was not able to reproduce this on 4.7.1

I have a user, agent1
whenever I disable Admin > Message, it will not be allowed to edit messages, unless he is part of one of the roles that has the **edit-permission** in Admin > Permissions.

Can you reproduce this on a clean install?

**Comment by himpierre** [comment]
I'm not sure we understand eachother correctly. The problem is we cannot edit messages anymore although it's allowed in the settings.

Am 19. Mai 2022 14:59:48 MESZ schrieb Duda Nogueira ***@***.***>:
>I was not able to reproduce this on 4.7.1
>
>I have a user, agent1
>whenever I disable Admin > Message, it will not be allowed to edit messages, unless he is part of one of the roles that has the **edit-permission** in Admin > Permissions.
>
>Can you reproduce this on a clean install?
>

**Comment by alvarow** [comment]
The Edit option went away...  on the right click context menu. I have the same problem, coming from 4.6.3.  Up arrow edits still work, so looks like I do have permission.

**Comment by Gummikavalier** [comment]
I'm not not seeing this issue on RC 4.7.1 either.

Not sure if related particularly to this issue, but with recent versions of RC (within few months) we've had issues to open message view top panels and message reaction and reply items. This seems to be related to cache as doing a shift-reload or just plain refresh couple of times fixes the issues.

**Comment by alvarow** [comment]
I tried on fresh browser, I usually stick with Firefox, I went to Chrome and the issue is there as well.

Send a message, within a few seconds click on the 3 vertical dots, look for edit option, and it is not there. I am able to edit using keyboard shortcut UP Arrow (like unix shell), that works fine.

**Comment by ia-bg** [comment]
Maybe you have to wait one minute? I have the same Problem but I get the edit option after a minute.
See https://github.com/RocketChat/Rocket.Chat/issues/25478

**Comment by himpierre** [comment]
> Maybe you have to wait one minute? I have the same problem but I get the edit option after a minute. See #25478

Yes indeed! :mindblown:
