### ISSUE TITLE
Question about Login Page Design

### ISSUE THREAD

**Issue by garg** [RocketChat/Rocket.Chat#2556]
Your Rocket.Chat version: 0.22

What is a good way to change the design of the login page? I would like to add a background, custom divs, custom css,  etc. 

The administration section allows me to change the header and footer. Currently, are those the only two ways to customize the login page?

**Comment by RichardFoxworthy** [comment]
+1

**Comment by jonbaer** [comment]
I may write a blog post about this but this is what I have done (YMMV):

Make a copy of rocketchat-theme to (your-company)-theme and then swap the packages ...

meteor remove rocketchat-theme
meteor add (your-company)-theme
mv rocketchat-theme out of /packages
... customize ...

Then create a server/startup.coffee which will update Layout_Home_Body, Layout_Home_Title, Layout_Login_Header, etc.  I don't know if this is best practice (yet) but this is what has worked for me so far.  What may be ideal is to create this startup template inside of rocketchat-theme for reference.

**Comment by garg** [comment]
Thank you! That's very helpful

**Comment by engelgabriel** [comment]
Is you need all those changes, you need to register a new template like @jonbaer explained.

If you just need colours and logo, you can do that on version 0.23.0

**Comment by vyasjay2793** [comment]
@jonbaer I have read all you mentioned above
"Make a copy of rocketchat-theme to (your-company)-theme and then swap the packages ...

meteor remove rocketchat-theme
meteor add (your-company)-theme
mv rocketchat-theme out of /packages
... customize ...

Then create a server/startup.coffee which will update Layout_Home_Body, Layout_Home_Title, Layout_Login_Header, etc."


But, can you please guide me how to make new copy of theme and update it in details. Thanks :)

**Comment by jonbaer** [comment]
@vyasjay2793 Sorry I don't think what I wrote applies any longer (considering the ticket is closed and was applied to an earlier version of Rocket.Chat), poking around you should probably look at the official docs: https://rocket.chat/docs/developer-guides/ui-and-theming/ https://github.com/RocketChat/Rocket.Chat/issues/277 or hop on the #support channel in the demo.rocket.chat.

**Comment by mphslaats** [comment]
Hi, I was wondering about how I needed to change the login page to my custom theme, and this is the post that came up the most when I googled it.
However the following link is broken: https://rocket.chat/docs/developer-guides/ui-and-theming/
Does anyone have any ideas??

**Comment by andpiazza** [comment]
Hello @mphslaats - I ran recently on the same problem.
Long story short, it seems that **to develop a custom theme you need to tailor RC with custom CSS code**, and there's **very little to no documentation on it**.

Would be curious how my two conclusions above compare / contrast from the community.

**Comment by mphslaats** [comment]
Hi @andpiazza Thanks for your reply, After lots of searching I could not find the best practice indeed. Like you pointed out I could hardly find any documentation.  
I solved my issue by going to Administration - Layout - Custom CSS. Here I am able to add custom CSS, however I have no idea if this is the best practice.
