### ISSUE TITLE
Android Application SSL Proxy DNS issues

### ISSUE THREAD

**Issue by ScaredyCat** [RocketChat/Rocket.Chat#25563]
### Description:

Using the rocket chat app ( version 4.27.1.32281 ) when trying to login to a server on an internal network connects from the first page but does not allow logging in and simply displays the progress animation in the blue button.

### Expected behavior:

Expect the application to log user in without issue. 

### Actual behavior:
 
Does not log user in.

### Server Setup Information:

Linux, Ubuntu 20.04.4 LTS virtual machine

Pound server for SSL using Let's Encrypt wildcard cert directing to non-ssl rocket server

Version 
4.6.2

Apps Engine Version 
1.31.0

Node Version 
v14.18.3

MongoDB
4.2.17 / wiredTiger (oplog Enabled)

Commit Details

HEAD: (e8cb66624)
Branch: HEAD

Deployment Method: snap

### Client Setup Information

Android 10
App version 4.27.1.32281

### Additional context

Web browser on same android device works fine, connects and logs in without issue.

### Relevant logs:

adb repeatedly outputs:

05-19 09:44:27.417   699 26036 D DnsProxyListener: GetAddrInfoHandler::run: {rocket.mydomain.com 235 235 235 983275 10553 0}
05-19 09:44:27.421   699 26036 D DnsProxyListener: reportDnsEvent{ 235 1 0 1 rocket.mydomain.com 10553}

mydomain.com is for sanitisation only.

**Comment by dudanogueira** [comment]
Hi!

Please, [refer to this doc on how to setup SSL for internal networks](https://developer.rocket.chat/mobile-app/mobile-app-environment-setup/supporting-ssl-for-development-on-rocket.chat#the-rocket.chat-server-is-not-accessible-on-the-internet)

I'll close this one for now.

Please, refer to our Community [Support Channel](https://open.rocket.chat/channel/support) for [Forums](https://forums.rocket.chat/), and check out our [Asking for Help Guide](https://docs.rocket.chat/getting-support/asking-for-help).

**Comment by ScaredyCat** [comment]
This is an applicaion bug, not a config problem.
