### ISSUE TITLE
Mention to all members in channel/group

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#256]
We should have an @all to send a notification to everyone on a room

**Comment by rwakida** [comment]
Is this similar to mentioning a user in the room?  For example, if I type @user1, then a green icon with '1' appears in the sidenav next to the room for user1.  

So typing @all would create the same green icon for all users subscribed to the room?

**Comment by rwakida** [comment]
Hi @sampaiodiego is my last comment on the right track?  Thanks.

**Comment by sampaiodiego** [comment]
hey @rwakida , I'm sorry for not answered before.

it's exactly what you described on previous comment.. a @all message shouold notification everyone who has a subscription to that room. =)

**Comment by rwakida** [comment]
okay.  Thanks @sampaiodiego =)

**Comment by wolfika** [comment]
Just an idea for consistency, maybe you could consider using @channel instead of @all, since Slack uses the former for the exact same functionality you described.

**Comment by sampaiodiego** [comment]
ok,  we should have @channel and @group just an alias for @all ..

**Comment by rodrigok** [comment]
I agreed with @sampaiodiego
