### ISSUE TITLE
Disable profile if LDAP is enable

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2560]
Your Rocket.Chat version: Latest.

As I understand the LDAP implementation today is a one way implementation.
LDAP overrule the local user database.

Still if a user goes to "My Account => Profile" then it looks like they can change the following fields, which they cant since they are in the LDAP database
 
- Name
- Username
- E-mail
- New password

I would suggest that a checkbox is added to the LDAP page, saying **Do not show profile** on My Account page.  Since it is useless.

**Comment by Molle500** [comment]
+1

**Comment by lunitic** [comment]
I would say close this ticket.. the option "Allow User Profile Change" already exists .

Haven't notice it .
