### ISSUE TITLE
Inject status(online/away/busy) on another website? 

### ISSUE THREAD

**Issue by a-s-f** [RocketChat/Rocket.Chat#2561]
I am looking to get my status(online/away/busy) on another webpage, can be used as an easy indicator to my clients if I am around for a chat

**Comment by engelgabriel** [comment]
We dont have that feature yet. Would you expect it to update in realtime? Or when you do a request?

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by kaiiiiiiiii** [comment]
@MartinSchoeler This feature is already implemented as far as I can see? #9549 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
