### ISSUE TITLE
  Upload failure error occurs when the uploaded file exceeds 100m

### ISSUE THREAD

**Issue by CoreCodeJOJO** [RocketChat/Rocket.Chat#25619]
MongoError: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. [ufs: cannot upload file]

![图片](https://user-images.githubusercontent.com/37408687/169934458-6b339f14-9973-4eb4-8942-43f3e34603a4.png)

**Comment by MightyGoldenOctopus** [comment]
This is a limitation of using GridFS as you storage solution, it is also not viable if you dont have a file upload retention policy in place as this will store it in your RAM.

You can change the storage solution to local filesystem or AWS S3 or GCP Storage from the admin panels in "File Uploads" section.

**Comment by dudanogueira** [comment]
Closing this one. 

Thanks @MightyGoldenOctopus for the explanation.

Also, you should consider in between moving parts, like reverse proxy, for example.

Also, consider reading this guide before opening an Issue.
https://docs.rocket.chat/getting-support/asking-for-help

**Comment by CoreCodeJOJO** [comment]
Thanks for your help, the problem has been solved.
