### ISSUE TITLE
Audio playback stops on Android when new private message is received

### ISSUE THREAD

**Issue by blubbi321** [RocketChat/Rocket.Chat#2563]
Whenever I have audio playback running, eg a podcast via AntennaPod and receive a message from rocketchat audio playback is set to pause.
I am using the Rocketchat app from the Android store to receive the messages. 

Tested if I could reproduce the problem by triggering the "test desktop notification" in there - did not work.

Please tell me if you need more information. Would be great if one could change this behavior ;)

Rocket.Chat version: 0.22.0
Android Version 5.1.1 (Cyanogen 12.1-YOG4PAS60J)
Hardware Model: Zuk Z1

**Comment by blubbi321** [comment]
Still present in 0.24

**Comment by SaintTemplar** [comment]
Still somewhat present on VZW Galaxy S5 stock Android 6.0, Rocket.Chat v2.3.1, some apps will get paused, some will have their volume lowered until audio is manually stopped/started or player goes to the next track.

**Comment by Hudell** [comment]
I'll be closing this since it is an issue on the old Cordova app. If the same thing happens on the new apps, an issue should be opened on the respective repository.
