### ISSUE TITLE
Release 4.7.3 not downloadable

### ISSUE THREAD

**Issue by bognerf** [RocketChat/Rocket.Chat#25657]
I'd like to let you know, that the latest 4.7 release is not downloadable.

When entering https://releases.rocket.chat/4.7.3/download the response is

```
{"error":"not found"}
```

Best regards,

bognerf

**Comment by ralfbecker** [comment]
Same is true for 4.7.3 and 4.4.4 container on hub.docker.com, they don't exist: https://hub.docker.com/r/rocketchat/rocket.chat/tags?page=1&name=4.7.3

Ralf

**Comment by SchaeVHS** [comment]
This seems to be very worrying, as 4.7.3 is still not in dockerhub. So the security bugfix seems not to be on dockerhub even 3 days after hotfix :-/ Is there an ETA?

**Comment by casalsgh** [comment]
Team, Rocket.chat is aware and working to solve this.

**Comment by rodrigok** [comment]
> Same is true for 4.7.3 and 4.4.4 container on hub.docker.com, they don't exist: https://hub.docker.com/r/rocketchat/rocket.chat/tags?page=1&name=4.7.3
> 
> Ralf

Docker images are available on our docker hub page, including the link you shared.

We are investigating the download links from our domain

**Comment by casalsgh** [comment]
@bognerf please ignore 4.7.3 and jump to 4.7.4. It's now available on link https://releases.rocket.chat/latest/download .

**Comment by cs35-owncloud** [comment]
Hello,

thanks for the explanations, nevertheless the latest release is still not available on the official Rocket.Chat dockerhub repository.

Official repository: https://hub.docker.com/_/rocket-chat

Other repository (but up to date): https://hub.docker.com/r/rocketchat/rocket.chat

It's very confusing, which one should the users trust ? Are both really maintained by Rocket.Chat ?
Any updates on the missing versions on the official dockerhub repository ?

Thanks.
