### ISSUE TITLE
Grant user in Private group

### ISSUE THREAD

**Issue by sophornsna** [RocketChat/Rocket.Chat#2565]
I have a problem with Rocket.Chat, when the owner private leave from group. All the user cannot invite other user to join private group beside owner private group. How can we grant the user in private group to owner group?

**Comment by engelgabriel** [comment]
@marceloschmidt, when a owner tries to leave that have no other owners, it would return an erros asking him to add another owner.

**Comment by sophornsna** [comment]
Thank for your answer and I have another question to ask you. Why the Rocket Chat client for Microsoft windows doesn't show the notification like Ubuntu Client (mean alert message to show us). This is my question.
