### ISSUE TITLE
v4.7.3 link downloads v4.7.2

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#25660]
### Description:

v4.7.3 link downloads v4.7.2

### Steps to reproduce:

https://releases.rocket.chat/latest/download

**Comment by ali-alhaidary** [comment]
Are there anyone going to fix this please?

**Comment by ali-alhaidary** [comment]
This link also down loads 4.7.2
https://releases.rocket.chat/4.7.3/download

**Comment by foss-** [comment]
Surprised there is no reaction at all from RC on this issue, especially since [4.7.3](https://github.com/RocketChat/Rocket.Chat/releases/tag/4.7.3) was a security hotfix release.

**Comment by Gummikavalier** [comment]
Note that sha256sums differ between the original 4.7.2 and the new one. (And I do mean the original download, not the version that exist under 4.7.2 currently.)

**Comment by dudanogueira** [comment]
Hi, sorry for the late response.

Our team is already looking into this.

**Comment by Gummikavalier** [comment]
Might be of some importance to get announcement whether the recent versions were really made by ggazzo or by someone else. 

I refer to this:
https://thehackernews.com/2022/05/nearly-100000-npm-users-credentials.html

Thanks!

**Comment by ggazzo** [comment]
sorry sorry, actually was my fault, no invaders or anything else, just me 😞 . somehow I picked the wrong commit to tag, please ignore 4.7.3 and jump to 4.7.4
