### ISSUE TITLE
My Rocket is loading forever

### ISSUE THREAD

**Issue by HuyNguyenKiai** [RocketChat/Rocket.Chat#25661]
![image](https://user-images.githubusercontent.com/103712437/170692231-69a642d6-5414-4312-b7af-7e97ca2ac957.png)

**Comment by viniciusxyz** [comment]
@HuyNguyenKiai Had a similar problem a while back, in my case I just deleted the server added in the desktop app and added it again.

**Comment by MartinSchoeler** [comment]
Hey I'll be closing this due lack of updates and info, please try again with the latest versions and if the issue persists, please reopen this following the issue template, thanks!
