### ISSUE TITLE
Не отправляется личное сообщение конкретному человеку. (A private message is not sent to a specific person.)

### ISSUE THREAD

**Issue by Djullii** [RocketChat/Rocket.Chat#25679]
Здравствуйте, в корпоративном чате есть перечень сотрудников, всем сотрудникам я могу отправлять сообщения, одному почему то нет. Выходит Не допускается создать личное сообщение.
(Hello, there is a list of employees in the corporate chat, I can send messages to all employees, for some reason not to one. It turns out it is not allowed to create a private message.)

**Comment by dudanogueira** [comment]
Hi, please, try using our forums first, before opening a new issue.

https://forums.rocket.chat/

Also, check this out:
https://docs.rocket.chat/getting-support/asking-for-help
