### ISSUE TITLE
Set "_id" field in endpoint "Register a new department"

### ISSUE THREAD

**Issue by Rozanchick** [RocketChat/Rocket.Chat#25678]
https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/omnichannel-endpoints/department/register-a-new-department
In documentation it is not explained, but i can send "_id" field in request and department will be created with this id. Can i use this feature in our project or it will possibly be removed?

Example payload:
```
{
  "department": {
    "enabled": false,
    "showOnRegistration": true,
    "showOnOfflineForm": true,
    "email": "1@test.ru",
    "name": "111FF",
    "_id": "myCustomId",
    "description": ""
  }
}
```
Response:
```
{
    "department": {
        "enabled": false,
        "showOnRegistration": true,
        "showOnOfflineForm": true,
        "email": "1@test.ru",
        "name": "111FF",
        "_id": "myCustomId",
        "description": "",
        "_updatedAt": "2022-05-30T09:20:50.661Z"
    },
    "agents": [],
    "success": true
}
```

**Comment by dudanogueira** [comment]
Hi!

I believe it is safe to use, as we have no plans of removing this feature. THanks!
