### ISSUE TITLE
[4.7.4] - Directory - Sorting result into "Invalid sort parameter provided"

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#25695]
### Description:

The sorting inside the directory is not working correctly.
There is a message "Invalid sort parameter provided" while clicking on the name for example.

### Steps to reproduce:

1. Open directory
2. Click on Name to sort the Users by Name.

### Expected behavior:

Is to sort the Names either ascending or descending.

### Actual behavior:

![grafik](https://user-images.githubusercontent.com/979342/171165711-a0c86c7f-0f48-454c-8749-29e5f443b06b.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  4.7.4
- Operating System:  Rocky Linux 8
- Deployment Method: tar
- Number of Running Instances:  3
- DB Replicaset Oplog:  yes
- NodeJS Version:  v14.18.3
- MongoDB Version: 4.2.20

### Client Setup Information

- Desktop App or Browser Version:  Desktop App - 3.8.6
- Operating System: Fedora 36

Please let me now if you need more information.

**Comment by emikolajczak** [comment]
Issue exists also on https://open.rocket.chat/

**Comment by ankar84** [comment]
Confirm that on 4.8.0
![image](https://user-images.githubusercontent.com/4023037/171337591-08f6b0ca-9b81-4b80-a0b6-86efa51d5411.png)
After a few clicks on  Users,, Created at and other options I get that error.

**Comment by matthias4217** [comment]
I can reproduce it on `4.7.4`. It would seem that this error appears when sorting in decreasing order. Increasing is fine.
