### ISSUE TITLE
Can't upgrade from 4.7.2 to 4.7.4 (latest tag)

### ISSUE THREAD

**Issue by dolohow** [RocketChat/Rocket.Chat#25693]
### Description:

Rocketchat 4.7.4 (latest) does not start.

### Steps to reproduce:

1. Run 4.7.2 docker tag
2. Change to latest

### Expected behavior:

Rocket chat is working fine

### Actual behavior:

Rocketchat does not start

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.2
- Operating System: Ubuntu
- Deployment Method: k3s/docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enable
- NodeJS Version: 14.18.3 - x64
- MongoDB Version: 4.4.14

### Relevant logs:

```
{"level":40,"time":"2022-05-31T06:11:28.613Z","pid":1,"hostname":"rocketchat-server-55f74f4d69-lldrg","name":"","name
":"Migrations","msg":"Not migrating, control is locked. Attempt 0/30. Trying again in 10 seconds."}
{"level":40,"time":"2022-05-31T06:11:38.640Z","pid":1,"hostname":"rocketchat-server-55f74f4d69-lldrg","name":"","name
":"Migrations","msg":"Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds."}
```

**Comment by kahrpatrick** [comment]
It seems that the latest tag is pointing to 4.4.5  not 4.7.4

**Comment by Parkhost** [comment]
yup, same problem here, change the tag from latest to 4.7.2 did solve my problem, seems rocket.chat messed up the docker image tag versioning

**Comment by kahrpatrick** [comment]
You can set the tag to 4.7.4 to get the latest version
