### ISSUE TITLE
Error on meteor run

### ISSUE THREAD

**Issue by jaypanares** [RocketChat/Rocket.Chat#257]
Hi,

I'm working on a fork of this repo, but when I run `meteor` I get the following error:

```
=> Started proxy.
=> Started MongoDB.
rocketchat:hubot: updating npm dependencies -- coffee-script, hubot,
hubot-calculator, hubot-google-hangouts, hubot-google-images,
hubot-google-translate, hubot-maps, hubot-help, hubot-scripts,
hubot-youtube...
npm ERR! missing: tap-consumer@*, required by tap@0.3.3

=> Errors prevented startup:

   While building package rocketchat:hubot:
   error: couldn't read npm version lock information

=> Your application has errors. Waiting for file change.
```

Is there anything I need to do beforehand before I can get it to run?

**Comment by jaypanares** [comment]
Slightly figured out that there might be something wrong with my environment (Windows 8).  I ran the same app on Cloud9 (Online IDE) with no errors.  What's wrong with my local setup?  Did I miss to install anything?

**Comment by Wloa** [comment]
Hi Jay, There is some issue with Windows installation. I had the same problem and Gabriel Helped me. See the below link.

https://github.com/RocketChat/Rocket.Chat/issues/242https://github.com/RocketChat/Rocket.Chat/issues/242https://github.com/RocketChat/Rocket.Chat/issues/242

**Comment by jaypanares** [comment]
@Wloa Thanks!  It's working now, but are there any side effects with removing `rocketchat:hubot` ?  Does the app still work with full functionality without that package?

**Comment by Wloa** [comment]
The app works perfectly the only issue is video. So when you enter say you tube url, it just list the link while in Linux one will show the video in the chat body itself..

**Comment by jaypanares** [comment]
Ok, good to know.  Thanks!

**Comment by leoharsha** [comment]
type:meteor remove rocketchat:hubot and run it...it works!
