### ISSUE TITLE
A click on announcement banner doesn't start livestream

### ISSUE THREAD

**Issue by amottier** [RocketChat/Rocket.Chat#25705]
### Description:

A click on the announcement banner displaying the message "Broadcast is now live. Click here to watch!" open the announcement popup instead of playing the livestream.

Also removing livestream URL does not remove the announcement banner despite the display of `Room announcement changed to: (none) by ow2adm 09:42` system message.

This seems to be a regression introduced in version 4.7.0, I was getting the expected behavior in 4.6.3.

### Steps to reproduce:

1. On a fresh new install
2. Go to "Administration" → "Settings" → "LiveStream & Broadcasting" and toggle "Livestream Enabled" and click on "Save changes"
3. Go to "general" channel, in the channel kebab menu select "Livestream"
4. Set livestream URL (e.g. https://youtu.be/u9foWyMSATM) and click on Save button
5. Click on the announcement banner with message: "Broadcast is now live. Click here to watch!"

### Expected behavior:

A click on the announcement banner should open the livestream video player.

Also clearing the livestream video URL should actually remove the announcement message.

### Actual behavior:

[Actual behavior](https://user-images.githubusercontent.com/5032635/171353620-c7390f2a-ebfe-460d-aa02-b0ed935a94c5.mp4)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.0, able to reproduce since 4.7.0, was working fine on 4.6.3
- Operating System: Debian GNU/Linux 10 (buster) on the server
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 91.9.1esr (64-bit)
- Operating System: Debian GNU/Linux 11 (bullseye)

### Relevant logs:

None

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, The Livestream & Broadcasting integration has been deprecated, may not work as expected, and will not receive updates.  

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
