### ISSUE TITLE
Can Not Change Password Even Though Setting Is Enabled

### ISSUE THREAD

**Issue by amayer5125** [RocketChat/Rocket.Chat#2570]
Your Rocket.Chat version: 0.22.0

When I go to My Account > Profile and attempt to change my password I get the error "Your Rocket.Chat administrator has disabled the changing of usernames". The username and email fields are disabled.

Here are my settings:
Allow User Profile Change: True
Allow Username Change: False
Allow E-mail Change: False
Allow Password Change: True

Expected behavior: I can change my password. Usename and Email fields are ignored.

**Comment by engelgabriel** [comment]
I believe @marceloschmidt may have already fixed it on the version 0.23.0 that is coming out today.

**Comment by marceloschmidt** [comment]
Yes, it's pushed in the latest `develop` branch

**Comment by amayer5125** [comment]
Sorry about that. I searched for an issue and didnt find one, so I figured I would post it. Glad to hear its fixed already.
