### ISSUE TITLE
Integration with Gogs

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2571]
Submit a PR with the changes on wording to explain that you can use the Slack integration for Rocket.Chat

https://github.com/gogits/gogs/issues/2834

**Comment by geekgonecrazy** [comment]
Would it be of any benefit to have our own Integration listed?  Right now it'd be a complete copy of the Slack Integration just renamed.

**Comment by engelgabriel** [comment]
It would be a starting point to build more functionality and instruction on how to setup the Rocket.Chat side.

**Comment by supriya999** [comment]
Are there any example scripts to integrate incoming webhook in rocket chat from gogs webhook?
I tried this script but its not working with combination gogs->rocket.caht
https://rocket.chat/docs/administrator-guides/integrations/github
please guide/help.

**Comment by graywolf336** [comment]
@supriya999 Just set the gogs to slack and it'll do everything for you, at least that's how it was when I used it.

**Comment by TwizzyDizzy** [comment]
As discussed: please add a label "feature-needs-review".

/cc @SeanPackham 

Cheers
Thomas
