### ISSUE TITLE
Little translation bug in `typing`

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#25721]
### Description:

I have access to Russian translation via LingHub and checked translation for `typing` and all looks correct.
But users see `<UserName> is печатает ...` where `is` is unnecessary and wrong (looks not translated)

### Steps to reproduce:

1. Choose Russian language
2. Ask some user to write you a message and check message box for typing status
3. Get wrong `<UserName> is печатает ...` 

### Expected behavior:

Correct result should be `UserName печатает ...` without `is`

### Actual behavior:

All strings are translated correctly, including `is typing`
![image](https://user-images.githubusercontent.com/4023037/171592563-85be334e-9749-40e4-87a7-60ee35f0bc4e.png)
But result is:
![image](https://user-images.githubusercontent.com/4023037/171592444-a09c9a6d-d6fb-498e-bd07-9bc591bbcd8b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.0
- Operating System: OL8
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 5.0.8

### Client Setup Information

- Desktop App or Browser Version: Chrome 100
- Operating System: Windows 10

**Comment by Karting06** [comment]
It's the same issue as #23593.

**Comment by ankar84** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23593
