### ISSUE TITLE
Emoji picker watch tone

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#2573]
When selecting any tone other than the default the "watch" which is tone-less is incorrectly trying to change tone

![rocket](https://cloud.githubusercontent.com/assets/432460/13925620/5ead68fa-ef5f-11e5-8da0-053130b92adf.png)

**Comment by fduraibi** [comment]
@sampaiodiego

**Comment by sampaiodiego** [comment]
this is no happening to me..
is this hapenning all the time?

**Comment by fduraibi** [comment]
For me yes, if I switch to the first tone (yellow circle on the top) I see the watch, but if I change the tone  to any other tone and refresh the page (you have to refresh the page to see it) it will append a tone number to it

**Comment by fduraibi** [comment]
It might be a problem with Firefox only, I see it with Firefox for Linux and Android. But not in Chrome

**Comment by sampaiodiego** [comment]
ok.. confirmed on Firefox.. thanks
