### ISSUE TITLE
what is the latest release 4.8.0 or 4.6.4 ?

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#25742]
### Description:

what is the latest release 4.8.0 or 4.6.4 ?

**Comment by dudanogueira** [comment]
Hi! Latest is 4.8.0.

We will be fixing the release page here and published docker images soon.

This is the latest 4.8.0 docker image in our registry:
registry.rocket.chat/rocketchat/rocket.chat:4.8.0

or in docker hub:
https://hub.docker.com/layers/rocket.chat/rocketchat/rocket.chat/4.8.0/images/sha256-e857fa4b0728d518cacdd3c92199d8fa6ad38a3928c50c47ae7c31eb98173244?context=explore

and this is the release notes:
https://github.com/RocketChat/Rocket.Chat/releases/tag/4.8.0

**Comment by dudanogueira** [comment]
latest is back pointing to 4.8.0. CLosing :)

**Comment by ali-alhaidary** [comment]
@dudanogueira sorry, but it is not
