### ISSUE TITLE
Add Shortcut Key For Message Box

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2574]
Your Rocket.Chat version: 0.22

Add a shortcut key that will bring the user to the message input box for typing since `Tab` is not ideal, currently.

**Comment by engelgabriel** [comment]
The message input gets the focus when the window get focus.
We will make the message input also get focus when you press any letter and you are not already on another input.

**Comment by sampaiodiego** [comment]
the actual behavior put the focus on messages when you start typing
