### ISSUE TITLE
Codemirror performance

### ISSUE THREAD

**Issue by lvh1** [RocketChat/Rocket.Chat#2576]
The CodeMirror editor seems to have pretty bad performance for some reason, keystrokes are delayed by almost a second: 
![ ](https://i.imgur.com/LOYDCaN.gif)
I did a quick search and I think part this may be the issue https://github.com/RocketChat/Rocket.Chat/blob/127ff29f11054d69746b1f5c62064f53b3d00c1e/packages/rocketchat-ui-admin/admin/admin.coffee#L140:L145
Could be totally wrong though. 

Your Rocket.Chat version: 0.22.0

**Comment by geekgonecrazy** [comment]
yeah this is pretty painful.  Looks like we need a bit of debouncing on the save to the local variable to reduce the lag felt here.
