### ISSUE TITLE
Error when you need to mention the user & And also an error in quotes from a mobile application

### ISSUE THREAD

**Issue by vpnwe912** [RocketChat/Rocket.Chat#25760]
Good day.
Error when you need to mention the user
When I just try to mention the user with a message, it hooks him
@user

but when I after I mention the user and add text after him, it stops highlighting him
@user text text
![Безымянный](https://user-images.githubusercontent.com/34860203/172000970-ba33965b-2ac0-4d48-bae1-f8038c079fc0.png)

And also an error in quotes from a mobile application when you quote a message, it adds it with a link and partially not for all chats, how can this be fixed?
![1](https://user-images.githubusercontent.com/34860203/172001396-0e687656-c09e-41c5-b4b3-72fb571338bf.png)

**Comment by aleadco** [comment]
Probably related to #22280 and #23080

**Comment by hugocostadev** [comment]
All issues mentioned here are fixed in last releases ;D
