### ISSUE TITLE
Omnichannel Analytics page error - Chart is not a constructor

### ISSUE THREAD

**Issue by jarismar** [RocketChat/Rocket.Chat#25775]
### Description:

We recently upgraded to 4.8.0 (from 4.7.1) and noticed that Omnichannel Analytics page does not finish loading.

After investigation it seems chart.js dependency was upgraded which is causing this error, I believe the newer version of chartJS no longer defines a default export.

### Steps to reproduce:

1. Just visit omnichannel analytics page notice chart won't render and there is a Undefined message displayed

### Expected behavior:

Omnichannel analytics page should load without errors.

### Actual behavior:

![Omnichannel_Analytics_page_error](https://user-images.githubusercontent.com/1980614/172216323-b00262ee-f307-4ef4-8156-351c73d474e8.jpeg)

### Server Setup Information:
```
+--------------------------------------------+ 
|               SERVER RUNNING               | 
+--------------------------------------------+ 
|                                            | 
|  Rocket.Chat Version: 4.8.0                | 
|       NodeJS Version: 14.18.3 - x64        | 
|      MongoDB Version: 5.0.8                | 
|       MongoDB Engine: wiredTiger           | 
|             Platform: linux                | 
|         Process Port: 3000                 | 
|             Site URL: https://localhost  | 
|     ReplicaSet OpLog: Enabled              | 
|          Commit Hash: 0e38639928           | 
|        Commit Branch: HEAD                 | 
|                                            | 
+--------------------------------------------+ 
```

### Client Setup Information

- Desktop App or Browser Version: Version 102.0.5005.61 (Official Build) (x86_64)
- Operating System: Mac OSX

### Additional context

I think the dynamic import for chat.js needs to change from:

```
	const chartImport = await import('chart.js');
	const Chart = chartImport.default; // <=== error here chartImport.default is undefined
```

to

```
	const { Chart } = await import('chart.js');
```

**Comment by ddkedr** [comment]
Still no response from RC team...
