### ISSUE TITLE
latest 4.8.1 still points to 4.8.0

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#25815]
### Description:

https://releases.rocket.chat/latest/download still points to 4.8.0

**Comment by geekgonecrazy** [comment]
Folks.. a bit of patience.  The ci for the release is still going.  Just because it's tagged doesn't mean assets are yet published.

https://github.com/RocketChat/Rocket.Chat/actions/runs/2465702108

**Comment by geekgonecrazy** [comment]
it finished and is accurate as should be
