### ISSUE TITLE
index conflict error causing process exit

### ISSUE THREAD

**Issue by fc757** [RocketChat/Rocket.Chat#25828]
RocketChat: 4.8.1
NodeJS: 14.18.3
MongoDB: 5.0.8 (oplog enabled/password set)
MongoDB Engine: wiredTiger

on startup get the below errors
---

Jun  9 20:33:44 cetialphafive node[650812]: Error creating indexes for integration_history MongoError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1", expireAfterSeconds: 2592000 }, existing index: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1" }
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.messageHandler (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.emit (events.js:400:28)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.emit (domain.js:475:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at processIncomingData (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream._write (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
Jun  9 20:33:44 cetialphafive node[650812]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.ondata (internal/streams/readable.js:731:22)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.emit (events.js:400:28)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.emit (domain.js:475:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at addChunk (internal/streams/readable.js:293:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at readableAddChunk (internal/streams/readable.js:267:9)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Jun  9 20:33:44 cetialphafive node[650812]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Jun  9 20:33:44 cetialphafive node[650812]:     at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
Jun  9 20:33:44 cetialphafive node[650812]:   ok: 0,
Jun  9 20:33:44 cetialphafive node[650812]:   code: 85,
Jun  9 20:33:44 cetialphafive node[650812]:   codeName: 'IndexOptionsConflict',
Jun  9 20:33:44 cetialphafive node[650812]:   '$clusterTime': {
Jun  9 20:33:44 cetialphafive node[650812]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 28, high_: 1654821224 },
Jun  9 20:33:44 cetialphafive node[650812]:     signature: { hash: [Binary], keyId: [Long] }
Jun  9 20:33:44 cetialphafive node[650812]:   },
Jun  9 20:33:44 cetialphafive node[650812]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 28, high_: 1654821224 }
Jun  9 20:33:44 cetialphafive node[650812]: }
Jun  9 20:33:50 cetialphafive node[650812]: MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
Jun  9 20:33:51 cetialphafive node[650812]: {"level":40,"time":"2022-06-10T00:33:51.432Z","pid":650812,"hostname":"cetialphafive.com","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Jun  9 20:33:51 cetialphafive node[650812]: Error creating indexes for nps_vote MongoError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, unique: true, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }, existing index: { v: 2, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream.messageHandler (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream.emit (events.js:400:28)
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream.emit (domain.js:475:12)
Jun  9 20:33:51 cetialphafive node[650812]:     at processIncomingData (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream._write (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
Jun  9 20:33:44 cetialphafive node[650812]: Error creating indexes for integration_history MongoError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1", expireAfterSeconds: 2592000 }, existing index: { v: 2, key: { _updatedAt: 1 }, name: "_updatedAt_1" }
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.messageHandler (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.emit (events.js:400:28)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.emit (domain.js:475:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at processIncomingData (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream._write (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
Jun  9 20:33:44 cetialphafive node[650812]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.ondata (internal/streams/readable.js:731:22)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.emit (events.js:400:28)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.emit (domain.js:475:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at addChunk (internal/streams/readable.js:293:12)
Jun  9 20:33:44 cetialphafive node[650812]:     at readableAddChunk (internal/streams/readable.js:267:9)
Jun  9 20:33:44 cetialphafive node[650812]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Jun  9 20:33:44 cetialphafive node[650812]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Jun  9 20:33:44 cetialphafive node[650812]:     at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
Jun  9 20:33:44 cetialphafive node[650812]:   ok: 0,
Jun  9 20:33:44 cetialphafive node[650812]:   code: 85,
Jun  9 20:33:44 cetialphafive node[650812]:   codeName: 'IndexOptionsConflict',
Jun  9 20:33:44 cetialphafive node[650812]:   '$clusterTime': {
Jun  9 20:33:44 cetialphafive node[650812]:     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 28, high_: 1654821224 },
Jun  9 20:33:44 cetialphafive node[650812]:     signature: { hash: [Binary], keyId: [Long] }
Jun  9 20:33:44 cetialphafive node[650812]:   },
Jun  9 20:33:44 cetialphafive node[650812]:   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 28, high_: 1654821224 }
Jun  9 20:33:44 cetialphafive node[650812]: }
Jun  9 20:33:50 cetialphafive systemd[1]: opendmarc.service: start operation timed out. Terminating.
Jun  9 20:33:50 cetialphafive node[650812]: MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
Jun  9 20:33:51 cetialphafive node[650812]: {"level":40,"time":"2022-06-10T00:33:51.432Z","pid":650812,"hostname":"cetialphafive.com","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Jun  9 20:33:51 cetialphafive node[650812]: Error creating indexes for nps_vote MongoError: An equivalent index already exists with the same name but different options. Requested index: { v: 2, unique: true, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }, existing index: { v: 2, key: { npsId: 1, identifier: 1 }, name: "npsId_1_identifier_1" }
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream.messageHandler (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream.emit (events.js:400:28)
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream.emit (domain.js:475:12)
Jun  9 20:33:51 cetialphafive node[650812]:     at processIncomingData (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Jun  9 20:33:51 cetialphafive node[650812]:     at MessageStream._write (/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)

mobile clients can connect, web clients get the below:
---

![image](https://user-images.githubusercontent.com/4654695/173050856-083b6c69-034c-47ea-b9e8-09978f620015.png)

**Comment by fc757** [comment]
If I restart the RocketChat service the index errors go away, but unfortunately the web clients still do not work. I turned on advanced logging and didn't see any errors when connecting with web clients or actually any kind of logs from my web clients,  just my iOS clients.

screenshot of inspector for 4.8.1
---
![image](https://user-images.githubusercontent.com/4654695/173191064-f2d66b50-8736-4b3d-a2d2-e31e8c830d55.png)

screenshot of inspector for 4.6.3
---
![image](https://user-images.githubusercontent.com/4654695/173191082-c770904a-1027-4dcb-882b-fa2267afc997.png)

**Comment by fc757** [comment]
I tried running 4.8.1 in a docker container and it is doing the same thing. I am using the mongoDB externally.

**Comment by whitetiger264** [comment]
Tried upgrading from RC 4.7.2 to 4.81 getting the same error. 

OS: CentOS 7
Apps Engine Version: 1.31.0
Node Version: v14.0.0
MongoDB: 4.2.20 / wiredTiger (oplog Enabled)

```
# tail -f /var/log/messages | grep rocketchat
Jun 14 16:10:12 core rocketchat: Error creating indexes for integration_history MongoError: Index with name: _updatedAt_1 already exists with different options
Jun 14 16:10:12 core rocketchat: at MessageStream.messageHandler (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:272:20)
Jun 14 16:10:12 core rocketchat: at MessageStream.emit (events.js:315:20)
Jun 14 16:10:12 core rocketchat: at MessageStream.EventEmitter.emit (domain.js:485:12)
Jun 14 16:10:12 core rocketchat: at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Jun 14 16:10:12 core rocketchat: at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
Jun 14 16:10:12 core rocketchat: at doWrite (_stream_writable.js:385:12)
Jun 14 16:10:12 core rocketchat: at writeOrBuffer (_stream_writable.js:367:5)
Jun 14 16:10:12 core rocketchat: at MessageStream.Writable.write (_stream_writable.js:307:12)
Jun 14 16:10:12 core rocketchat: at Socket.ondata (_stream_readable.js:707:22)
Jun 14 16:10:12 core rocketchat: at Socket.emit (events.js:315:20)
Jun 14 16:10:12 core rocketchat: at Socket.EventEmitter.emit (domain.js:485:12)
Jun 14 16:10:12 core rocketchat: at addChunk (_stream_readable.js:296:12)
Jun 14 16:10:12 core rocketchat: at readableAddChunk (_stream_readable.js:272:9)
Jun 14 16:10:12 core rocketchat: at Socket.Readable.push (_stream_readable.js:213:10)
Jun 14 16:10:12 core rocketchat: at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
Jun 14 16:10:12 core rocketchat: operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1655215800 },
Jun 14 16:10:12 core rocketchat: ok: 0,
Jun 14 16:10:12 core rocketchat: code: 85,
Jun 14 16:10:12 core rocketchat: codeName: 'IndexOptionsConflict',
Jun 14 16:10:12 core rocketchat: '$clusterTime': {
Jun 14 16:10:12 core rocketchat: clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1655215800 },
Jun 14 16:10:12 core rocketchat: signature: { hash: [Binary], keyId: 0 }
Jun 14 16:10:12 core rocketchat: }
Jun 14 16:10:12 core rocketchat: }
Jun 14 16:10:15 core systemd: rocketchat.service: main process exited, code=killed, status=11/SEGV
Jun 14 16:10:15 core systemd: Unit rocketchat.service entered failed state.
Jun 14 16:10:15 core systemd: rocketchat.service failed.
```

**Comment by fc757** [comment]
4.6.4 still works as expected for me. Upgraded from 4.6.3.

**Comment by geekgonecrazy** [comment]
Probably the workaround would be to remove the index.  Did you happen to create an index manually on that collection?

**Comment by pierreozoux** [comment]
@geekgonecrazy I have the same issue, and I didn't create the index manually.

Thanks for the advice of removing the index.

**Comment by whitetiger264** [comment]
Hi @geekgonecrazy 

No, I did not create any index, however, please see this comment here: [Link](https://github.com/RocketChat/Rocket.Chat/issues/26046#issuecomment-1170177789)

It seems even if you do delete the index, its recreated again and same error happens.

**Comment by fc757** [comment]
The index issue doesn't seem to be the root cause of web clients not working any longer. I have cleared the index errors manually, but with or without the index errors, my instance starts successfully and everything works except web clients.

**Comment by geekgonecrazy** [comment]
I've just seen this same thing happen with a different index:
> Error creating indexes for nps_vote MongoError: Index with name: npsId_1_identifier_1 already exists with different options

@sampaiodiego @rodrigok

**Comment by fc757** [comment]
I tried updating to the latest 5.0 RC-7 and web clients still cannot connect. Mobile clients still work.

I don't get any errors in the log this time though. Did a port change or something for web connections?

**Comment by fc757** [comment]
[rocket.cetialphafive.com-1657936772460.log](https://github.com/RocketChat/Rocket.Chat/files/9124957/rocket.cetialphafive.com-1657936772460.log)

I see this in the browser when trying to connect with the newer versions.

**Comment by fc757** [comment]
/node_modules/libsodium/dist/modules/libsodium.js:1 
        
       Refused to connect to 'data:application/octet-stream;base64,AGFzbQEAAAABvgImYAJ/fwBgAAF/YAN/f38Bf2ACf38Bf2ADf39/AGABfwBgAX8Bf2AEf39/fwF/YAt/f39/f39/f39/fwF/YAV/f39/fwF/YAZ/f39/f38Bf2AHf39/f39/fwF/YAN/f34Bf2AEf35/fwF/YAZ/f39+f38Bf2AAAGAGf39+f39/AX9gBH9/fn8Bf2AGf39+f35/AX9gDH9/f39/f39/f39/fwF/YAh/f39/f39/fwF/YAR/f39/AGADf39+AGAFf39+f38AYAh/f35/f35/fwF/YAl/f39/fn9+f38Bf2ACfn8BfmACf34AYAZ/f35/f38AYAR/fn9/AGAHf39/fn9/fwF/YAp/f39/f39/f39/AX9gAn5+AX5gAX8BfmAEf39/fgBgBX9/fn5/AX9gBX9/fn9/AX9gBX9/f35/AX8CHwUBYQFhABUBYQFiAAIBYQFjAAYBYQFkAA...EQqWVVJAaZ1iogcVeFNQ70uNG7MnCgahDI0NK4FsGkGVOrQVEIbDcemeuO30x3SCeoSJvhtbywNGNaycWzDBw5y4pB40qq2E5z42N3T8qcW6O4stbzby5o/LLvXe6Cj3RgLxdDb2OleHKr8KEUeMiE7DlkGggCx4woHmMj+v++kOm9gt7rbFCkFXnGsvej+b4rU3Lj8nhxxpxhJurOPifKB8LAIce4htEe6+DN1n3a6njRbu5/T331um8Xcqpn8AammMiixX1jCq4N+b4EmD8RG0ccEzULcRuEfQQj9XfbKJMkx0B7q8oyvL7JFQq+njxMDRCcxGcdQ7ZCPsu+1MVMKn5l/Jwpf1ns+tY6q2/LXxdYR0qMGURsgABB4JACCyFTaWdFZDI1NTE5IG5vIEVkMjU1MTkgY29sbGlzaW9ucwEAQbCRAgs1MI5QAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0=' because it violates the following Content Security Policy directive: "connect-src *". Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'data:' must be added explicitly.

eval @ /node_modules/libsodium/dist/modules/libsodium.js:1
/node_modules/libsodium/dist/modules/libsodium.js:1 
        
       Refused to connect to 'data:application/octet-stream;base64,AGFzbQEAAAABvgImYAJ/fwBgAAF/YAN/f38Bf2ACf38Bf2ADf39/AGABfwBgAX8Bf2AEf39/fwF/YAt/f39/f39/f39/fwF/YAV/f39/fwF/YAZ/f39/f38Bf2AHf39/f39/fwF/YAN/f34Bf2AEf35/fwF/YAZ/f39+f38Bf2AAAGAGf39+f39/AX9gBH9/fn8Bf2AGf39+f35/AX9gDH9/f39/f39/f39/fwF/YAh/f39/f39/fwF/YAR/f39/AGADf39+AGAFf39+f38AYAh/f35/f35/fwF/YAl/f39/fn9+f38Bf2ACfn8BfmACf34AYAZ/f35/f38AYAR/fn9/AGAHf39/fn9/fwF/YAp/f39/f39/f39/AX9gAn5+AX5gAX8BfmAEf39/fgBgBX9/fn5/AX9gBX9/fn9/AX9gBX9/f35/AX8CHwUBYQFhABUBYQFiAAIBYQFjAAYBYQFkAA...EQqWVVJAaZ1iogcVeFNQ70uNG7MnCgahDI0NK4FsGkGVOrQVEIbDcemeuO30x3SCeoSJvhtbywNGNaycWzDBw5y4pB40qq2E5z42N3T8qcW6O4stbzby5o/LLvXe6Cj3RgLxdDb2OleHKr8KEUeMiE7DlkGggCx4woHmMj+v++kOm9gt7rbFCkFXnGsvej+b4rU3Lj8nhxxpxhJurOPifKB8LAIce4htEe6+DN1n3a6njRbu5/T331um8Xcqpn8AammMiixX1jCq4N+b4EmD8RG0ccEzULcRuEfQQj9XfbKJMkx0B7q8oyvL7JFQq+njxMDRCcxGcdQ7ZCPsu+1MVMKn5l/Jwpf1ns+tY6q2/LXxdYR0qMGURsgABB4JACCyFTaWdFZDI1NTE5IG5vIEVkMjU1MTkgY29sbGlzaW9ucwEAQbCRAgs1MI5QAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAAAIAAAACQAAAAoAAAALAAAADAAAAA0=' because it violates the document's Content Security Policy.
eval @ /node_modules/libsodium/dist/modules/libsodium.js:1
d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3 
        
       Uncaught (in promise) Error: Cannot find module 'stream'
    at y (d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3:638)
    at d.n [as require] (d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3:3668)
    at t (d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3:730)
    at module (/node_modules/cipher-base/index.js:1:57)
    at d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:1307:764
    at g (d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3:1094)
    at d.n [as require] (d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3:3652)
    at t (d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:3:730)
    at module (/node_modules/create-hash/browser.js:1:105)
    at d6c223179d4f08275508257eaf5de07c7dd11d13.js?meteor_js_resource=true:1307:764

**Comment by fc757** [comment]
I finally figured out what the issue was. If you have `Enable second layer encryption for data transport' enabled, versions above 4.6.4 can't connect via the web.

I was able to upgrade to 4.8.1 and things seem to be working as expected.

**Comment by whitetiger264** [comment]
> The index issue doesn't seem to be the root cause of web clients not working any longer. I have cleared the index errors manually, but with or without the index errors, my instance starts successfully and everything works except web clients.

@fc757 how exactly did you fix the index errors? Can you provide exact commands you ran, please?

**Comment by fc757** [comment]
I used MongoDB Compass to delete the values it complained about. It would recreate them on start up. There was a number of them it complained about before it finally worked itself out. 

Also, the newer RC 5.x versions seem to do this on its own on install.

**Comment by engelgabriel** [comment]
Just for future reference: The index issue is not impactful on later versions of Rocket.Chat. The instance starts successfully and everything will work normally. To remove the index warnings you have cleared the index errors manually for now.
