### ISSUE TITLE
Authentication for MongoDB?

### ISSUE THREAD

**Issue by etb09** [RocketChat/Rocket.Chat#2584]
I was following the https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker Tutorial to run the Rocket.Chat on my (hosted) server. 

The problem: My MongoDB instance has an authentication (username/password).

How is it possible to set username and password for MongoDB?

Your Rocket.Chat version: latest, as given in tutorial above

**Comment by engelgabriel** [comment]
@sampaiodiego you have done this before, can you point @etb09 in the right direction, until our docs get updated.

**Comment by geekgonecrazy** [comment]
@etb09 did you get this figured out?

You'd set your environment variable `MONGO_URL` something like this:

`MONGO_URL=mongodb://username:password@127.0.0.1:27017/meteor`

**Comment by engelgabriel** [comment]
Please follow https://github.com/RocketChat/Rocket.Chat.Docs/issues/69
