### ISSUE TITLE
Exclude app role users from mentions 

### ISSUE THREAD

**Issue by akhayyat** [RocketChat/Rocket.Chat#25862]
Is it possible to exclude specific users, or users of a specific role, from @-mention auto-completion?
This is particularly relevant for users that are only meant to use the API (app users), for example, users of the app role.

This would also be a security feature. Mention auto-completion using the @ character may be used to reveal users that should not be a part of any chat, such as api-only app users.

**Comment by dudanogueira** [comment]
Closing as this is a feature request, now in: https://github.com/RocketChat/feature-requests/issues/569
