### ISSUE TITLE
unread property doesn't exist

### ISSUE THREAD

**Issue by BahrouniYousra** [RocketChat/Rocket.Chat#25883]
I would like to know how can I add unread property inside rooms object when I use this api "/api/v1/users.info" as administrator, it return just

"rooms": [
{
"_id": "blabla",
"rid": "GENERAL",
"name": "general",
"t": "c"
}
]

**Comment by dudanogueira** [comment]
Hi, please, use our Community [forums](https://forums.rocket.chat/) or [support channel ](https://open.rocket.chat/channel/support)for asking questions.

Here is only issues.

Regarding your questions, check this thread out:
https://forums.rocket.chat/t/how-to-get-rooms-direct-chat-unread-messages/12647/5
