### ISSUE TITLE
limit autocompleting names in private channels to those in the channel

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#2588]
When you're in a private channel and start to type @name... it attempts to autocomplete, but it will include names of people NOT in the channel. If you're using private channels for conversations with customers, this leaks info on other customers (or employees)

**Comment by geekgonecrazy** [comment]
@sinteur I hadn't thought of this use case.  Good one though.  Also you can't invite on mention... so there really isn't a need to mention anyone outside the channel.

**Comment by engelgabriel** [comment]
there is.. if you want to say: talk to @sampaiodiego 
for example.

**Comment by sinteur** [comment]
That's my point. It shouldn't. See use case I mentioned

**Comment by engelgabriel** [comment]
I agree It should not leak (not send a alert to the person), but the autocomplete should still work.

**Comment by sinteur** [comment]
leaking is often unintended and not the the person mentioned, but to the other customers in the channel.

suppose I am talking to several bankers and I accidentally autocomplete @bankerjoker when I meant to autocomplete @bankerjones - where bankerjoker is a competitor and bankerjones who IS in the current channel should not know that.

**Comment by sampaiodiego** [comment]
if a user have access to a private channel, he'll have access to any person on the chat? am I wrong?

**Comment by sinteur** [comment]
Again: auto complete makes me leak info about people who are NOT in the channel TO the people who ARE.

**Comment by sampaiodiego** [comment]
but everyone in the channel can talk to anyone in the server. there is no such limitation.

**Comment by sinteur** [comment]
How, if they don't know the other person is on the server?  And if the CAN know, they shouldn't or RocketChat is unusable as a way to talk to customers

**Comment by engelgabriel** [comment]
OK, this is specific use case. We should create a special type of users, like "guests" that have much more limited permission, so that they cannot mention anyone outside their channels.

**Comment by sinteur** [comment]
It's not the guests who make the auto-complete error....

**Comment by engelgabriel** [comment]
So you want a special setting on rooms so no memeber is allowed to mention non members?

**Comment by sinteur** [comment]
Well - at least leave them out of the autocomplete - if that only works by forbidding the entire @name string, I will live with that. And even better if I can make that the default

**Comment by engelgabriel** [comment]
We have discussed, and will work on that in the next week or two.

**Comment by dmidmi84** [comment]
Hello! That will be great if those users "with much more limited permissions" also cannot use autocomplete search in direct messages.

**Comment by mickeyclausen** [comment]
+1

**Comment by HenrikSkriver** [comment]
+1

**Comment by hvkirkegaard** [comment]
+1

**Comment by fjolle** [comment]
+1

**Comment by stevenhfotofix** [comment]
+1

**Comment by geekgonecrazy** [comment]
@stevenhfotofix consider maybe using the guest role for these users?  I think this would lock them down to not be able to see any user not in the channel.

**Comment by sinteur** [comment]
I keep staring at screens and not seeing it. Where do I assign roles to a user?

**Comment by geekgonecrazy** [comment]
@sinteur its not the most obvious unfortunately.  So during user creation there is an option to select the role. Otherwise goto the permissions, select the little edit icon next to the guest user:

![screenshot 2016-06-25 at 12 48 10 pm](https://cloud.githubusercontent.com/assets/51996/16358220/1e63c4aa-3ad3-11e6-99d4-f3e1682b528b.png)

Then add the user here.  You'll need to remove the user role if they have that role also.
![screenshot 2016-06-25 at 12 48 53 pm](https://cloud.githubusercontent.com/assets/51996/16358221/388cf6f8-3ad3-11e6-9061-ded572624b3b.png)

**Comment by sinteur** [comment]
Ah. That's indeed not obvious. And since our clients self register, that's quite a headache

**Comment by melanierieback** [comment]
Could somebody fix this please??  This is a major security hole...

**Comment by stevenhfotofix** [comment]
@geekgonecrazy They are on the guest role already, but last I checked, it did not limit them at all.  I mentioned that on my comment by calling them "guest" members.  I will update to the latest version and verify though.

**Comment by stevenhfotofix** [comment]
This is still an issue in 0.38.0 - Yahoo messenger shut down today, and we are hoping to migrate a large number of users to our rocket chat install - but we can't, because they will have access to names we don't want them to use.  Please take a look at this again.

**Comment by sinteur** [comment]
To demonstrate, I've created a new user with only the guest role, verified in the database that this is indeed the only role, invited it to a private channel, and it can auto-complete names not in the channel. See screenshots. 
![screen shot 2016-09-14 at 15 57 14](https://cloud.githubusercontent.com/assets/13427371/18515090/60b3b6a2-7a94-11e6-9304-9afe6cdca9f2.png)
![screen shot 2016-09-14 at 15 59 05](https://cloud.githubusercontent.com/assets/13427371/18515091/60b4655c-7a94-11e6-972b-0cbccb1e7e9b.png)

**Comment by linksilver** [comment]
+1

**Comment by stevenhfotofix** [comment]
+1 again

**Comment by engelgabriel** [comment]
So we FINALLY will start the work on this one.

We will create 2 new permission:

* Can mention `@all`
* Can mention everyone
* Can mention users in channel

You will be able to add/remove from the guest or default user role as you wish.

Would that cover all use cases?

**Comment by stevenhfotofix** [comment]
Those would work for us, for sure!  Very excited and grateful!!

**Comment by linksilver** [comment]
yeah it will be nice ! thanks !

**Comment by hughlroberts** [comment]
+1

**Comment by akachapati** [comment]
+1

**Comment by andersonluciano** [comment]
+1

**Comment by Jannibal** [comment]
+1

**Comment by MaksymRybak** [comment]
Yes, guys. It's very usefull also for our team. 
Thank you very much.

**Comment by linksilver** [comment]
do you know when will it be released  ? (approximatly)

**Comment by ryran** [comment]
@engelgabriel said:

> We will create 3 new permission:
> 
> 1. Can mention @all
> 2. Can mention everyone in server
> 3. Can mention only users in channel
> 
> You will be able to add/remove from the guest or default user role as you wish.
> 
> Would that cover all use cases?

IMHO, no. The current behavior makes no sense to me for private channels. Currently, I'm in a private channel with 4 users and only one of their names starts with `jh`. I type `jh<Tab>` and it auto-completes the name of someone else in our org ... what ... the heck.

**Comment by sinteur** [comment]
You're looking at this from the user point of view. Look at it from a channel point of view. If you ONLY create these permissions, somebody with permission 2 can still accidentally leak info in a private channel. In a private channel 3 should be the default (and since @all means all in channel that would be allowed too) and in public channels somebody might have an extra privilege which would include 2

**Comment by ryran** [comment]
If the 3rd option really is automatically applied for private channels, then yes, this would make things work more how I think most people would expect. However, one should not have to edit channel settings or user roles to achieve this.

**Comment by Ulrar** [comment]
Same thing, there are 6 of us in a private channel, all our usernames starts with the same prefix (for the company name) and we just keep HL-ing people out of the channel for no reason.
The leaking use case is interesting but of no concern to us, as only our company has accounts anyways, our use case is purely just avoid HLing random people that have nothing to do with the current discussion and cannot even join the current channel.

I think it would make a lot more sense, at least in private channels, to only auto-complete on people who have access rights to join, or something like that.

**Comment by localguru** [comment]
Is anything going on here?

**Comment by przemika** [comment]
+1

**Comment by gdelavald** [comment]
This issue was solved by PR #7830 so I'll close the issue, if anyone has opinions or any problem with the implementation, please open a new issue.
