### ISSUE TITLE
smiley button on wrong postiotion and not working

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#2589]
Your Rocket.Chat version: 0.23.0
there seems to be a static smiley below the text input field
![capturfiles_4](https://cloud.githubusercontent.com/assets/7944656/13951829/69bddd18-f033-11e5-9b08-71ea44a3853b.png)
![capturfiles_5](https://cloud.githubusercontent.com/assets/7944656/13951830/69bf849c-f033-11e5-9ea8-b5560c43ccb6.png)

**Comment by bott0r** [comment]
This, is the button to utilize the emoji picker in the web version, its not working for me on the mobile version.

**Comment by Julime** [comment]
can't click on it. Neither on macos desktop app nor web view

**Comment by bott0r** [comment]
it works flawless on chrome

**Comment by Julime** [comment]
works not even in chrome for me.

**Comment by bott0r** [comment]
![capture2](https://cloud.githubusercontent.com/assets/17119942/13954382/cee30c1a-f040-11e5-8e69-12a9398b9c57.JPG)

**Comment by Julime** [comment]
![capturfiles_6](https://cloud.githubusercontent.com/assets/7944656/13955135/da46ba90-f043-11e5-9729-c1ef1be02d6c.png)

**Comment by bott0r** [comment]
I know the crafty decs working on the mobile fix, i am sure it will work soon :+1:

**Comment by engelgabriel** [comment]
We think we know what the problem is, and @sampaiodiego  will submit a fix to the develop branch shortly.

**Comment by sampaiodiego** [comment]
The fix is now on `develop` branch.
@Julime can you test it please? thank you

**Comment by Julime** [comment]
I can check this on tuesday

**Comment by Julime** [comment]
@sampaiodiego 
Things didn't went better i'd say ...
![capturfiles_7](https://cloud.githubusercontent.com/assets/7944656/14100501/3d27c92a-f58e-11e5-875e-8deb5c06df06.jpg)

**Comment by engelgabriel** [comment]
Can you clear your cache? Some of your icons are not updated either.

**Comment by Julime** [comment]
Do you mean client cache? I'm using the MacOS client, but in browser there is even more broken (wrong icons). If there is a server cache: where can i clear it?

**Comment by engelgabriel** [comment]
Client cache. Can you clear the cache in your browser and send a new screenshot?

**Comment by Julime** [comment]
shure
![capturfiles_8](https://cloud.githubusercontent.com/assets/7944656/14111437/ff067262-f5ca-11e5-87a2-7aed1db34940.jpg)

**Comment by Julime** [comment]
@engelgabriel can you please re-open this bug?

**Comment by Julime** [comment]
Okay, i fixed it: a few weeks ago i tried to include a css file (@import) in administration/layout, but it didn't work. Until the next restart (8 days ago) there was no problem with it.
