### ISSUE TITLE
How to Push Notifications

### ISSUE THREAD

**Issue by WreckingBANG** [RocketChat/Rocket.Chat#25927]
Hello,
I am new to Rocket.Chat. i want to get notifications to my android device. Is there an easy way for that? I did not found any good guids that explain step by step how to push notifications. Can you please help me?

**Comment by IKrendelev** [comment]
Push notifications are sent to Rocket.Chat official mobile apps via Rocket.Chat Push Gateway (`gateway.rocket.chat`). It is done to keep official applications GCM and APN tokens (used to send pushes to official Android and Apple RC apps directly) in secret. 

To use public Rocket.Chat Push Gateway (free deployment is limited to 10'000 mobile pushes per month) you must connect (register) your instance to Rocket.Chat cloud workspace.

Open `Administration menu > Connectivity services` and then follow instructions to create and connect your cloud workspace.
After your instance is connected to Cloud Workspace, you'll start receiving push notifications automatically.

**Comment by WreckingBANG** [comment]
Thank you. I will try it out later

**Comment by WreckingBANG** [comment]
Does this still work if i build the app myself?

**Comment by IKrendelev** [comment]
> Does this still work if i build the app myself?

I think application build by yourself won't work via official push gateway. 
To build mobile application you need to include google-services.json (android) / google-services.plist (apple) config file with Push identifiers to your project. When you whilelabel your application, you should create free Firebase account to manage your push notifications from your server.

I've tried to build both iphone and android devices. My whitelabelled android application successfully receives push notifications via my Firebase account. However I can't build an application for iphone (I've never developed and built apps for iphone and don't know how to build IPA file).

**Comment by tamalbachar** [comment]
> > Does this still work if i build the app myself?
> 
> I think application build by yourself won't work via official push gateway. To build mobile application you need to include google-services.json (android) / google-services.plist (apple) config file with Push identifiers to your project. When you whilelabel your application, you should create free Firebase account to manage your push notifications from your server.
> 
> I've tried to build both iphone and android devices. My whitelabelled android application successfully receives push notifications via my Firebase account. However I can't build an application for iphone (I've never developed and built apps for iphone and don't know how to build IPA file correctly).

@IKrendelev i have built the whitelabelled app and it runs fine but the notifications are not coming. i have followed all the steps mentioned in [the official guide](https://developer.rocket.chat/open-source-projects/mobile-app/configuring-push-notifications) but it doesn't seem to work. what can be the problem?

**Comment by IKrendelev** [comment]
It has been a long time ago (about a year or more ago). 

I remember I've created Firebase Cloud Messaging account, downloaded google-services.json, included it to Android & iPhone projects. 
I've disabled "Use gateway" option onRC Push Settings page, pasted APN & GCM to corresponding fields.
Android project started receiving pushes, but iPhone has not. 

BTW, as I remember, Push'es don't come to iPhone emulator in XCode. And thus notifications doesn't work there.

**Comment by tamalbachar** [comment]
> It has been a long time ago (about a year or more ago).
> 
> I remember I've created Firebase Cloud Messaging account, downloaded google-services.json, included it to Android & iPhone projects. I've disabled "Use gateway" option onRC Push Settings page, pasted APN & GCM to corresponding fields. Android project started receiving pushes, but iPhone has not.
> 
> BTW, as I remember, Push'es don't come to iPhone emulator in XCode. And thus notifications doesn't work there.

@IKrendelev thank you for your reply. really appreciate that you mentioned the steps. i am building only the android version and hence did not have the apn keys. I have actually followed all these steps already. 
I placed my google-services.json in the play folder. However, the notifications still does not work! I am at my wits end here. i know i am missing something silly but unable to find what. 
my google-services.json looks like:
{
  "project_info": {
    "project_number": "5xx4xxx7xxx0", //pasted this in the gcm sender id
    "project_id": "chat-xxxxxx-reactnative",
    "storage_bucket": "chat-xxxxxx-reactnative.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:525480670030:android:ed01f8572d720a4708241f",
        "android_client_info": {
          "package_name": "chat.xxxxxx.reactnative"
        }
      },
      "oauth_client": [],
      "api_key": [
        {
          "current_key": "Axxaxxxfx9xxxPMrxxxPqzxxx_Ljxxx_0G-xxxk" //did not paste this in the server key, instead pasted the lagacy api key from firebase which is more lengthier.
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": []
        }
      }
    }
  ],
  "configuration_version": "1"
}

**Comment by tamalbachar** [comment]
I think i solved the issue. getting the notifications now! looks like i needed to place the google-services.json in experimental folder! tanks a ton for taking the time and repling. adios and good luck!
