### ISSUE TITLE
String "^1" appears under rocket.chat logo.

### ISSUE THREAD

**Issue by GunStm** [RocketChat/Rocket.Chat#25935]
Hi! This happens when i press "ctrl". Version 3.8.7
![^1.gif](https://user-images.githubusercontent.com/64286615/174663477-28b8836d-f4db-48c0-8ba4-ef70183aaff9.gif)

**Comment by IKrendelev** [comment]
This is not a bug.
`^` sign means "Ctrl" modifier key. 
`^1` means "Ctrl+1" hotkey to switch to this particular server (in case you are connected to multiple servers).
If this confuses you, then you can disable servers sidebar via `View > Servers` menu.
