### ISSUE TITLE
Users custom status drops on change presence status

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#25940]
### Description:

Users custom status drops on change presence status

### Steps to reproduce:

1. Click avatar
2. Choose **Custom status**
3. Set some text status
4. Change presence status (for example online => away)
5. Check custom status is dropped

### Expected behavior:

Custom status should remain despite of presence status.
I'm not 100% sure, but on a pre 4.8 versions that was true.

### Actual behavior:

![custom-status01](https://user-images.githubusercontent.com/4023037/174724294-fde82f10-3dd3-4a1a-b4c7-991cc9acf7cf.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.1
- Operating System: OL8
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 100
- Operating System: Windows 10

### Additional context

I guess that on a previous versions Custom status remain despite presence status changes

**Comment by ankar84** [comment]
5.3.5 still have that issue

**Comment by casalsgh** [comment]
@hardikbhatia777 is this something you might want to be assigned?

**Comment by VanshulB** [comment]
Hey @casalsgh I would like to work on this issue. Found [useStatusText](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/sidebar/header/hooks/useStatusItems.tsx#L32), but not sure if it's the file containing the issue. Is there a way to check if the user has set up a custom status cause the function `isDefaultStatus()` always returns true? Also, it should be `user.statusText` instead of `status.name` for getting custom status ? (cause the `status` object doesn't seem to have `name` property in it)?

**Comment by hardikbhatia777** [comment]
> @hardikbhatia777 is this something you might want to be assigned?

Sorry, I did not get a notification for this post. I'll look into it and get back to you.

**Comment by ggazzo** [comment]
@casalsgh this feature was implemented like that by design, its ok if we decide/want to change it, but not a bug.  

and the changes and descriptions should reflect this decision

**Comment by casalsgh** [comment]
FYI to all here -> Gazzo had the latest and feature is working as designed. Per our Product squad we are looking to change behaviour in the future as follows:
"Save the text and status in localstorage. When clicking ‘edit custom status' just fill out the fields with what we have saved there." 

If anyone is in to perform behavior change that would be great (will assign)

**Comment by hardikbhatia777** [comment]
@casalsgh I'll be happy to work on this :)

Just for some clarity on the idea, you want there to be a menu which lists out previously saved custom statuses and a text box for anything new, like this?

![image](https://github.com/RocketChat/Rocket.Chat/assets/98163873/3706557f-f27f-4357-b0d0-88e73023e01a)

**Comment by milton-rucks** [comment]
Hi @hardikbhatia777 

There is no need to create a dropdown menu. Just bringing the text box with the previously used text is enough.

**Comment by gabriellsh** [comment]
@hardikbhatia777 Just complementing, I don't think we have the need to save this info anywhere permanent, you could save it directly to the localstorage and then just fill the box with whatever was there before

**Comment by casalsgh** [comment]
@ankar84 behaviour changes implemented with PR-31237 by @hardikbhatia777 . Will be on 6.6.0 release and with that considering this item closed. Please mention me here if you have any other comments
