### ISSUE TITLE
After update to 4.8.1 older E2E-encrypted messages not decrypting in mobile apps

### ISSUE THREAD

**Issue by InspectorWitherspoon** [RocketChat/Rocket.Chat#26014]
### Description:

Last night our server auto-updated to 4.8.1. Now all encrypted messages that existed before the update are unreadable in the mobile apps, both on Android and iOS. Desktop apps are unaffected. Newer messages created after the update are decrypted as usual. Logging out and back in, restarting the apps, clearing the cache has no effect.

We tried reverting to the previous version (via snap revert), that killed the server outright, it stopped loading. Switching back and forth between snap versions didn't help. In the end we had to remove the server and reinstall from scratch, now it works again, but the older messages are still unreadable.

- Operating System: Ubuntu 20.04
- Deployment Method: snap

**Comment by nyubbie** [comment]
Possible similar issue to [#25996](https://github.com/RocketChat/Rocket.Chat/issues/25996)

**Comment by AndyMwwwy** [comment]
Expect the same problem with android app after auto update to 4.8.1. Hope that can be fixed, so older messages get visible again. Thanks

**Comment by scottbadams** [comment]
I think I have a work around. When the user starts the 1st direct message to a user for the 1st time, disabling and reenabling E2E (3 dots, upper right corner), seems to correct the issue. It is important that this be done before sending the 1st message. After that, E2E seems to work fine. This needs to be done for each NEW direct message to another user. The receiver does not need to do anything different as long as their encryption key is already in place.

If a message was started without doing the above steps, the DM will need to be deleted from the admin console and the user will need to start their message again, this time, following the steps above.

**Comment by AndyMwwwy** [comment]
Thanks for your description. What if the DM are already continued? Still possible to re-enable encryption? New messages are currently fine, but old once are unreadable in Android App.

**Comment by scottbadams** [comment]
In that case, I had to reset the users encryption key.  After that, they were able to see all of the old encrypted messages.  Interesting note, images were still viewable even though the text was not.

I'm still fairly new to Rocket.chat but I tend to test the hell out of something before implementing it, although I am still learning.
