### ISSUE TITLE
Bugs in UI

### ISSUE THREAD

**Issue by tanya17-05** [RocketChat/Rocket.Chat#26010]
Action button in Product tab of [home page](https://rocket.chat/) is not readable on hover. I also found the same issue at multiple sections. I am new to opensource. Can someone assign me to solve this issue?

**Comment by debdutdeb** [comment]
Please fill the bug template.

**Comment by debdutdeb** [comment]
https://rocket.chat  is not an open source project, so there is no contribution line to that. Please join the [contributors](https://open.rocket.chat/channel/contributors) channel as mentioned in the email.

Closing this.
