### ISSUE TITLE
Pasted images have an ugly white border in Dark Mode

### ISSUE THREAD

**Issue by vinniefalco** [RocketChat/Rocket.Chat#26028]
See:
![image](https://user-images.githubusercontent.com/1503976/175996427-c6e45cc6-ef02-4622-86a3-40cb084e246e.png)

**Comment by dudanogueira** [comment]
How have you enabled this dark mode? This seems to be something added by the browser/plugin as I have just manually changed the background and was not able to reproduce this:

![image](https://user-images.githubusercontent.com/1761174/176185119-5501032b-584a-45b1-8f0b-a0aa060e0ba9.png)
