### ISSUE TITLE
Changing Username results in loss of avatar

### ISSUE THREAD

**Issue by vinniefalco** [RocketChat/Rocket.Chat#26033]
Steps: Change username
Result: Custom avatar is replaced with a default avatar
![image](https://user-images.githubusercontent.com/1503976/176003117-8e6345a7-3d8d-437f-b89b-2cdefcc17302.png)

**Comment by Adarsh9306** [comment]
@vinniefalco is the issue still open ? I want to work on this issue.. please assign it to me?

**Comment by priyanshusutar1102** [comment]
@vinniefalco i want to work on the issue #26033 Changing Username results in loss of avatar

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
