### ISSUE TITLE
Changing Username results in Lost Connection / Bad Gateway

### ISSUE THREAD

**Issue by vinniefalco** [RocketChat/Rocket.Chat#26032]
Steps: Change the username
Result: Loss of connection to server
![image](https://user-images.githubusercontent.com/1503976/176002734-9d355a05-c0fa-4ae9-9c79-4afa4282bb79.png)

**Comment by jeanfbrito** [comment]
Did you tried login off and login on again?

**Comment by vinniefalco** [comment]
> Did you tried login off and login on again?

Yes, that resolves the issue.
