### ISSUE TITLE
No Logo in fresh installs

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#2604]
Your Rocket.Chat version: 0.23.0

In the login page, the url is now "/assets/logo?v=3". With a fresh install, this url is not found and thus results in a broken image link in the login page.

Possibly related to https://github.com/RocketChat/Rocket.Chat/pull/2581

**Comment by gramakri** [comment]
@rodrigok you can see this here - https://chat-demo.cloudron.me/ . Note that upgraded installs work fine because they reference the older link it seems "/images/logo/logo.svg?v=3"

**Comment by gramakri** [comment]
Just a guess: https://github.com/RocketChat/Rocket.Chat/pull/2581/commits/0639849c8655ca44350179e54b69e2326dac533f#diff-b91dc66abec974250a8985f32de853cdR11 should be served from _two_ urls now to support both fresh (/assets/logo?v=3) and upgraded (/images/logo/logo.svg?v=3) installs.

**Comment by rodrigok** [comment]
The new url should redirect to old url if no value was setted for that asset.

The problem is with the redirect

https://chat-demo.cloudron.me/assets/logo?v=3 redirects to https://chat-demo.cloudron.me//images/logo/logo.svg?v=3 with `//`
