### ISSUE TITLE
Deeplinking support

### ISSUE THREAD

**Issue by a7medo778** [RocketChat/Rocket.Chat#2607]
hi guys
it makes sense since the apps are crossplatform, the sharing URL should be using deeplinking method to detect if the user is opening the chatroom url in a mobile device and launch it in the app instead of webpage
the best option out there is : https://branch.io/ (free and activly updated)

with regards
ahmad

**Comment by andreas-bulling** [comment]
+1

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
