### ISSUE TITLE
SMTP Settings - Sending Test E-mail Without Restarting Rocket.Chat Server Results in "AuthError: Invalid login"

### ISSUE THREAD

**Issue by GT500org** [RocketChat/Rocket.Chat#2608]
Your Rocket.Chat version: 0.23.0

If I configure my SMTP settings, save them, and send a test e-mail it errors out (login failure). My maillog says the following, which suggests Rocket.Chat may be ignoring the login information I entered:

> Mar 22 18:39:57 <censored> postfix/smtpd[5978]: connect from localhost[127.0.0.1]
> Mar 22 18:39:57 <censored> postfix/smtpd[5978]: setting up TLS connection from localhost[127.0.0.1]
> Mar 22 18:39:57 <censored> postfix/smtpd[5978]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
> Mar 22 18:40:01 <censored> postfix/smtpd[5978]: warning: localhost[127.0.0.1]: SASL PLAIN authentication failed: 
> Mar 22 18:40:01 <censored> postfix/smtpd[5978]: lost connection after AUTH from localhost[127.0.0.1]
> Mar 22 18:40:01 <censored> postfix/smtpd[5978]: disconnect from localhost[127.0.0.1]

Restarting the Rocket.Chat server solves the problem.

I was able to log in to the account I created for Rocket.Chat via webmail before testing it in Rocket.Chat, and the account is working fine.

If you would like to know the error from Rocket.Chat's logs, then here's a copy and paste:

> Exception while invoking method 'sendSMTPTestEmail' AuthError: Invalid login - 535 5.7.8 Error: authentication failed:     at Object.Future.wait (<path censored>/programs/server/node_modules/fibers/future.js:398:15)     at smtpSend (packages/email/email.js:86:1)     at Object.Email.send (packages/email/email.js:185:1)     at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:12:9)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     - - - - -     at SMTPClient._actionAUTHComplete (<path censored>/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:826:23)     at SMTPClient._onData (<path censored>/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29)     at CleartextStream.emit (events.js:95:17)     at CleartextStream.<anonymous> (_stream_readable.js:765:14)     at CleartextStream.emit (events.js:92:17)     at emitReadable_ (_stream_readable.js:427:10)     at _stream_readable.js:420:7     at process._tickDomainCallback (node.js:492:13)

I installed Rocket.Chat manually on CentOS 6.5 (x86_64) by following the instructions [here](https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker). I used the version of node.js that was on the EPEL repository (0.10.42-4), the latest version of MongoDB from their CentOS repository (3.2.4-1), the version of curl from the CentOS 6.5 base repository (7.19.7-46), and the version of graphicsmagic from the EPEL repository (1.3.23-4). All are x86_64 packages.

**Comment by engelgabriel** [comment]
Meteor requires the server to be restarted in order to read the new SMTP settings. There is notting we can do at this point. We are working with MDG to try to solve the issue.

**Comment by GT500org** [comment]
I'd recommend adding some sort of notice in the SMTP settings that the server does require a restart for SMTP setting changes to take effect.

**Comment by m52go** [comment]
Is this still the case, i.e., restart to enable new SMTP settings? I'm not able to set up Mailgun but don't have direct access to the server to restart.
