### ISSUE TITLE
Whatsapp official Integration status endpoint info

### ISSUE THREAD

**Issue by Beedataco** [RocketChat/Rocket.Chat#26082]
We are using status endpoint but its not delivering whatsapp template info:

exected:

"content": {
      "statuses": [
        {
          "conversation": {
            "expiration_timestamp": XXXXX,
            "id": "XXXXXXXX",
            "origin": {
              "type": "user_initiated"
            }
          },
          "id": "XXXXXXXX",
          "message": {
            "recipient_id": "222222222"
          },
          "pricing": {
            "billable": true,
            "category": "user_initiated",
            "pricing_model": "CBP"
          },
          "recipient_id": "333333",
          "status": "sent",
          "timestamp": "16566147232",
          "type": "message"
        }
      ]
    },
    "privateHash": "XXXXXXXXXX"
  }
]

real answer

**Comment by dudanogueira** [comment]
Hi!

Please, read the template before creating a new issue.

Consider using our [Community Forums](https://forums.rocket.chat/) or [Community Support Channel](https://open.rocket.chat/channel/support) for usage instructions.

Thanks!
