### ISSUE TITLE
None Latin words are not getting highlighted

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#2610]
Your Rocket.Chat version: (latest from develop branch)

English words gets the yellow highlighting but Arabic words doesn't!
![tmp_11155-img_20160322_214706-194488521](https://cloud.githubusercontent.com/assets/432460/13973505/d103cbcc-f079-11e5-860f-ee566e8e48e6.jpg)
![tmp_11155-img_20160322_214853-629836013](https://cloud.githubusercontent.com/assets/432460/13973507/d44e9cd0-f079-11e5-8398-e094f234bb7a.jpg)

**Comment by engelgabriel** [comment]
Can you help with a PR?

**Comment by fduraibi** [comment]
@engelgabriel I don't know which part of the code is doing the highlighting, but I feel it has something to do with "Slugify" being enforced even if the setting is disabled.

Do you know who implemented this feature?

**Comment by fduraibi** [comment]
ok, first of all, i hate you @engelgabriel you kinda tricked me to work on it.

I found the problem, it is caused by using the regex anchor \b to detect word boundaries, however, that anchor is not unicode compatible.

so in this line:
https://github.com/Johann-Snapp/Rocket.Chat/blob/develop/packages/rocketchat-highlight-words/client.coffee#L20

```
msg = msg.replace(new RegExp("(\\b)(#{s.escapeRegExp(highlight)})(\\b)(?![^<]*>|[^<>]*<\\/)", 'gmi'), '$1<span class="highlight-text">$2</span>$3')
```


i replaced it with this (simply removing the `(\\b)` and adjusting the rest of the regex:
```
msg = msg.replace(new RegExp("(#{s.escapeRegExp(highlight)})(?![^<]*>|[^<>]*<\\/)", 'gmi'), '<span class="highlight-text">$1</span>')
``` 

However, that makes it detect the word even if it is part of a bigger word, so we need to substitute `\b` with something else, maybe whitespace and other symbols like period, comma ...etc.

So we need a regex expert here.

**Comment by engelgabriel** [comment]
@rodrigok is our in-house REGEX expert :+1:

**Comment by rodrigok** [comment]
@fduraibi Can you try this:

```coffeescript
msg = msg.replace(new RegExp("(^|\\b|[\\s\\n\\r\\t.,'\\\"\\+!?:-])(#{s.escapeRegExp(highlight)})($|\\b|[\\s\\n\\r\\t.,'\\\"\\+!?:-])(?![^<]*>|[^<>]*<\\/), 'gmi'), '$1<span class="highlight-text">$2</span>$3')
```

**Comment by fduraibi** [comment]
@rodrigok It works, however there was a missing double quote at the end of the regex, and I also added another form of comma used in Arabic language `،`

Here is the new line after fixing the missing quote and adding the special comma:
```coffeescript
msg = msg.replace(new RegExp("(^|\\b|[\\s\\n\\r\\t.,،'\\\"\\+!?:-])(#{s.escapeRegExp(highlight)})($|\\b|[\\s\\n\\r\\t.,،'\\\"\\+!?:-])(?![^<]*>|[^<>]*<\\/)", 'gmi'), '$1<span class="highlight-text">$2</span>$3')
```

**Comment by rodrigok** [comment]
@fduraibi awesome, can you create a new PR with this change?

**Comment by fduraibi** [comment]
@rodrigok done
