### ISSUE TITLE
Hide message "Enter you E2E Password" even if Encryption is enabled

### ISSUE THREAD

**Issue by wellemut** [RocketChat/Rocket.Chat#26168]
### Description:
**Feature Request:**

The message to enter your E2E Password is very dominant, although only few people really need it and use it.
![grafik](https://user-images.githubusercontent.com/15019030/177743733-a9698e50-9aa1-4f81-9344-7b60fc9eb3d4.png)

I wish to have a switch in the admin-panel, where I can deactivate the blue header-message, even if E2E is activated.

### Steps to reproduce:

1. Login to any RocketChat Instance, where E2E is activated
2. If you did not enter your E2E password before, you will see a blue message at the top
3. You can not get rid of it, unless you enter your E2E password

### Expected behavior:

It would be nice if the question for your E2E password only pops-up the first 3 times the user logs in, or only for 5 min. after login and then disappears. (especially important, as we use the chat-iframe on small pages.)

If you recieve an encrypted message, the field to enter your E2E password will popup again. Otherwise you would not see it.
Anytime the user can navigate to 

### Actual behavior: My Account > Security > E2E Encryption **and enter** or change the password there (chaning is already possible there)
![grafik](https://user-images.githubusercontent.com/15019030/177743349-6187fc39-d38f-4eba-ad97-1fc26a23ad10.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  4.8.1
- Operating System: Windows 
- Number of Running Instances:  1
- MongoDB Version: 4.2.17 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Both, in Browser, Mobile RC-App and RC-Desctop-App
- Operating System: Andorid and Windows

**Comment by milton-rucks** [comment]
Thank you for taking the time to share your thoughts and for your suggestion

After thorough review and consideration, we've decided not to move forward with implementing this feature at this time.

While we won't be implementing this specific request, your feedback is invaluable to us. It helps shape our understanding of our users' needs and informs future updates and enhancements.

Please do continue to share your ideas and feedback with us.

**Comment by svenseeberg** [comment]
I would like to revisit this issue. We are operating a Rocket.Chat server for a 5 digit number of users. We frequently get feedback about the E2E banner which confuses them. We have 2 groups of users:
- (IT) experts that use this feature in a limited number of cases.
- Non-experts who think they need to act on it and have no idea what to do. In some cases they set a password and forget it. In most cases they don't even understand why they enter the password or what the feature is about.

In our experience the current implementation is problematic from an UX perspective.

**Comment by svenseeberg** [comment]
@milton-rucks would you be willing to discuss/re-open this issue again?

**Comment by b90g** [comment]
To this day {after +10 years of RC), i get support emails from people who set an E2EE password not knowing what it is and when  trying to sign in using the E2EE password and wonder why they cannot login.

Give admins the chance to hide the banner so users who want to use the feature go to settings.

This feels  just like  patronizing users and admins...

@milton-rucks
