### ISSUE TITLE
WebRTC Media stream error: The operation is insecure.

### ISSUE THREAD

**Issue by brylie** [RocketChat/Rocket.Chat#2616]
Your Rocket.Chat version: 0.19.0

When initializing a call over WebRTC in Firefox, the call fails. I notice the following error in the browser console:

```
MediaStreamError { name: "SecurityError", message: "The operation is insecure.", constraint: "", stack: "" }
```

**Comment by engelgabriel** [comment]
Please upgrade to the latest version of Rocket.Chat and make sure you are using SSL.
