### ISSUE TITLE
Add support for bibtex-js (or similar)

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#2619]
Your Rocket.Chat version: 0.22.0

We are using Rocket.Chat within our research group and regularly paste paper references into chat windows, either only for future reference (like an archive) or during a specific discussion. It would be really nice if Rocket.Chat supported some bibtex parser to 1) render the pasted bibtex nicely in the chat window (similar to katex for Latex) and 2) still allow to download the bibtex reference later again (for insertion into a paper for example). This would even allow to have a room only with cool/interesting references.

I haven't tried it but this library looks promising:
https://github.com/Legend/bibtex-js

**Comment by andreas-bulling** [comment]
Some more options:
https://github.com/vkaravir/bib-publication-list
https://github.com/mikolalysenko/bibtex-parser
https://www.npmjs.com/package/bibtex-parser-js
http://brianmingus.github.io/bibtex.js/website/

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
