### ISSUE TITLE
Is it good to have a Todo List in each channel?

### ISSUE THREAD

**Issue by brandonweis** [RocketChat/Rocket.Chat#262]
Members can pin their conversation to the todo list and also create one manually.
Member can assign other members to the todos.
##

**Comment by sampaiodiego** [comment]
we are planning some improvements on right side bar. this is a good idea to put in there. =)

**Comment by engelgabriel** [comment]
![screen shot 2015-07-06 at 11 21 50](https://cloud.githubusercontent.com/assets/1000217/8524380/43b0f454-23d1-11e5-958c-a2473b0cde42.png)

**Comment by warcode** [comment]
Is it possible to extract things like these into plugins? While useful this doesn't seem to be something directly related to chat.

**Comment by engelgabriel** [comment]
Thats the plan. Everything will go into /packages so you can turn every feature on/off

**Comment by brandonweis** [comment]
cool, everything in package and reusable, is there a coding style guideline? I have some time for this.

**Comment by engelgabriel** [comment]
We have been using CoffeeScript, but not real coding style guideline yet :( That's in my TODO list.

**Comment by brandonweis** [comment]
I would like to contribute. Is there a todo-assignee list? Be great to avoid working on things others already been doing

**Comment by engelgabriel** [comment]
We are focusing on the issues for v0.4 and v0.5

All others as open.. if you let me know you are working on one, I'll add the IN PROGRESS tag.

**Comment by graywolf336** [comment]
This could be done with the sidebar tabs now :smile:

**Comment by antoined26** [comment]
What about this feature now ?

**Comment by brandonweis** [comment]
Sorry I didn't have time to continue, feel free to take over

**Comment by gdoleczek** [comment]
Is there any source source code for this feture, so any one could look at it and maby contribute?

**Comment by schucan** [comment]
how about implementing an automatic todo list like in https://mainframe.com/ ? Whenever someone is mentioned, take the phrase around that mention, and render these into a list. Looks very useful to me. And technically shouldn't be too hard to do, right?

**Comment by n30ngruu3n** [comment]
It would be just nice, if there is going to be a todo list in the tabbed right sidebar. Would like to use this!

**Comment by danilomiranda** [comment]
I'm working on it right now

**Comment by danilomiranda** [comment]
Working in progress, I had some overwork in my current job but now I'm back to that issue
![tasks](https://user-images.githubusercontent.com/1092454/27740344-21141726-5d88-11e7-9f2b-2d37dce44522.gif)
I'm thinking how he will create a new task.
maybe a slashCommand?
Something like that `/task <description>`

**Comment by gabfamcx** [comment]
I would like to use this function early!!!!
When can i use it ?

**Comment by mnlbox** [comment]
What is the state of this feature?

**Comment by rentox** [comment]
nice, any news? we would love to use this feature

**Comment by nubestra** [comment]
I started working on this feature yesterday, but then i thought maybe someone is already working on this and googled "rocket chat todo list integration" and found to this thread.

 @danilomiranda ¿can i help you build this feature? what i was thinking was a button for adding comments as "todos" the same way you can add messages as "starred items" what do you think?

**Comment by danilomiranda** [comment]
@nubestra is good you talk with @graywolf336 and follow the issue https://github.com/RocketChat/Rocket.Chat/issues/6890 to understand the plugin concept in RC.

**Comment by justUmen** [comment]
2018 ! Is there something available now ?

**Comment by graywolf336** [comment]
@justUmen Not quite yet, once the Rocket.Chat Apps get to a point to where they support the Contextual Bar then there will be. :)

**Comment by graywolf336** [comment]
Closing this in favor of it becoming a Rocket.Chat App. Please provide some feedback on our forums as I created a post to correlate to this: https://forums.rocket.chat/t/todo-list-application/423
