### ISSUE TITLE
Emoji hover over syntax

### ISSUE THREAD

**Issue by philthynz** [RocketChat/Rocket.Chat#2620]
It would be very useful to be able to hover over any emoji, and see the `:xxx:` syntax for the emoji. Also having this inside the emoji picker would be great.

**Comment by PavelVanecek** [comment]
Current version of RocketChat already does this:

![image](https://cloud.githubusercontent.com/assets/1100170/14781591/c82fc6e8-0ae3-11e6-84e5-c9a19a7465aa.png)

It seems this was implemented in https://github.com/RocketChat/Rocket.Chat/issues/1245
