### ISSUE TITLE
More Channels -> Filter Joined / All

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#2621]
Your Rocket.Chat version: 0.23.0

Is it possible somehow to set the Filter-Standard in "More Channels -> Filter Joined / All" to "All"?

We had some feedback from users "searching" for channels not finding them because of the filter set to "Joined". They are coming from slack.

Thanks!

**Comment by engelgabriel** [comment]
I agree, @marceloschmidt can you make the default be "All" by "Name" please.

**Comment by IQ2022** [comment]
can we group Channels? like set a department and within that multiple groups?
