### ISSUE TITLE
The problem with the web version of rocket

### ISSUE THREAD

**Issue by Molo4ekSdadness** [RocketChat/Rocket.Chat#26210]
There is a global problem with the work of the rocket chat in the company, namely in the work of the web version
Infinite loading and not displaying any data
The problem occurs in all browsers except Google Chrome All browsers have been updated to the latest version, but this did not solve the problem.
Please fix this bug

**Comment by dudanogueira** [comment]
Hi!

We certainly will need more information to help you. Please, read thru this [guide on how to properly ask for help](https://docs.rocket.chat/getting-support/asking-for-help)

Thanks!
