### ISSUE TITLE
Ability to customize channels who a new user will join by default.

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#2622]
Your Rocket.Chat version: 0.23.0

A new user always join the default channel aka "general", it could be cool if I can customize channels by default a new user joins to avoid having to add each new user in the other channels.

**Comment by MaxKK** [comment]
This is AFAIK already possible. "Default channels".

**Comment by corecache** [comment]
If I remember correctly - as Administrator do:

- create the room
- Admin Panel -> Rooms -> Select your newly created room -> Right Panel select "Default" to True

**Comment by unixfox** [comment]
@corecache Thanks you, I din't see it. Sorry
