### ISSUE TITLE
When Using Push Gateway Server Can't Start

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#2623]
Your Rocket.Chat version: `develop branch`

```
TypeError: Cannot read property 'keyData' of undefined
    at configurePush (server/lib/cordova.coffee:77:10)
    at server/lib/cordova.coffee:152:2
    at /home/rocket/Rocket.Chat/programs/server/boot.js:249:5
```

@rodrigok this is happening as a result of 32461b00d6f6da03d39dd55c80ffed0afb7697c1.

**Comment by rodrigok** [comment]
Thanks, fixed by https://github.com/RocketChat/Rocket.Chat/commit/503890f2015706774574dcb18e0601607b1b2cee
