### ISSUE TITLE
when a new user enters on rocket.chat it automatically join to GENERAL channel.

### ISSUE THREAD

**Issue by amitmeyraz** [RocketChat/Rocket.Chat#2625]
Your Rocket.Chat version: (23)
hi,
at my server mschool.rocket.chat its not happening.
when a new user join to the chat, nothing happen. i created the general channel and define it as default, but there is no automatic appearance of the channel.
please advice
![2016-03-23_22-52-32](https://cloud.githubusercontent.com/assets/5375635/14000509/30cae2f4-f14a-11e5-8b9c-c8d783b2ca39.jpg)

**Comment by rodrigok** [comment]
Can we access your chat to test?

**Comment by amitmeyraz** [comment]
yes, of course.
https://mschool.rocket.chat/home

sign in as a new user , you can sign in via faceook.
do you need admin pass?

**Comment by rodrigok** [comment]
@amitmeyraz as you can see I was added to the general room after my account creation

![image](https://cloud.githubusercontent.com/assets/234261/14033212/5e17c9ae-f1f7-11e5-8834-284df9baa2e7.png)

**Comment by amitmeyraz** [comment]
yes i see,
i wonder why when i am entering as a new user, its not happening.
for test purpose, i made a new user and sign in with the new user and nothing happen.
i will try now again and update you.

**Comment by amitmeyraz** [comment]
strange, its working very good now,
i can promise you that few days ago i tried dozen times and nothing.
i am very sorry that i bother you.
thanks a lot.
Amit Meyraz

**Comment by rodrigok** [comment]
Haha, no problem, I'm glad this is working now.
