### ISSUE TITLE
Soundcloud player

### ISSUE THREAD

**Issue by System-Glitch** [RocketChat/Rocket.Chat#2630]
When I use a channel with a Soundcloud embed player in it, my navigator freezes all inputs/outputs. Impossible to load any tab and to post new messages in the channel.
After a few seconds, the "Reconnecting..." message appears in RocketChat.

I'm using firefox.

**Comment by engelgabriel** [comment]
Does it happens on other browsers? What happens when you you see the Soundcloud embed player in other sites?

**Comment by JeremGamer** [comment]
No problems on other websites with the same navigator.
It seems that there's no problem on Edge. I currently can't test on other navigators.

**Comment by MartinSchoeler** [comment]
Couldn't reproduce in the latest version. If you experience this bug again please open a new issue with updated details. Thanks!
