### ISSUE TITLE
Feature Request - Radio Channels

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2631]
Nice to have, maybe not legal, but worth a shot.

It would be really fantastic to be able to create a bot that could first connected to spotify, lastfm, or something, and would reroute the audio signal from these services into a given channel, via webrtc, all other clients would not have the permission to speak(voice) in this channel, so connected people could listen to the generated audio signal, i.e. music

After that, the possibilities are endless, e.g. playlists and queues where people can add to the queue with a simple chat command such as `@radiobot: add Michael Jackson Smooth Criminal` or similar features.

**Comment by kramer65** [comment]
This indeed sounds quite awesome, but I guess it's not very high on the list of priorities.. :-)

**Comment by Nemra1** [comment]
coool idea

**Comment by ElieMyIdea** [comment]
What a nice Idea !! 
+1 :D

**Comment by timkinnane** [comment]
Specific bot requests are out of scope for these issues, but we collect them under one issue related to general bots features here: #10174

**Comment by czare** [comment]
This could be also useful for live translation during presentations. Imagine a conference, in which the speaker is speaking in english, and there are a few people who will act as real time translators. The translators and the audience would have rocket chat installed, and there would have different groups/rooms for different languages. Everyone would join as hearers, while the translators would speak alone in their respective rooms, and the target audience would hear.
