### ISSUE TITLE
5.0.0 not available

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#26337]
### Description:

My instance is updated manually using the update procedure described at https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/updating

The latest stable update available is 4.8.2

**Comment by lovekyleman** [comment]
Really interesting.
Still no 5.0.0

**Comment by artutava** [comment]
How do we upgrade to 5.0.0 (switch track) with this installation method?

https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/updating

I know there is a way to switch tracks on snaps. How to do this with this manual approach?

**Comment by lovekyleman** [comment]
> How do we upgrade to 5.0.0 (switch track) with this installation method?
> 
> 
> 
> https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/updating
> 
> 
> 
> I know there is a way to switch tracks on snaps. How to do this with this manual approach?
> 
> 
> 
> 

What a joke, no one cares about it

**Comment by aleadco** [comment]
> > How do we upgrade to 5.0.0 (switch track) with this installation method?
> > 
> > 
> > 
> > https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/updating
> > 
> > 
> > 
> > I know there is a way to switch tracks on snaps. How to do this with this manual approach?
> > 
> > 
> > 
> > 
> 
> What a joke, no one cares about it 

I always followed that procedure to update to the latest version, if nothing changed in the update method, the documentation must be updated.

I look forward to hearing from this matter.

**Comment by aleadco** [comment]
@murtaza98 ???

**Comment by lovekyleman** [comment]
Still no 5.0.0.
What's wrong with rocketchat

**Comment by rymek** [comment]
Follow the manual guide but instead of:
`curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz`

use:
`curl -L https://releases.rocket.chat/5.0.0/download -o /tmp/rocket.chat.tgz`

**Comment by stachi** [comment]
> Follow the official manual guide but instead of: `curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz`
> 
> use: `curl -L https://releases.rocket.chat/5.0.0/download -o /tmp/rocket.chat.tgz`

You should NOT do this. The Version you will get atm is a very old developer build. Its pre RC. Just check the build info before you download something. 
[Look](https://i.ibb.co/hM7b7tQ/Screenshot-2022-07-26-003352.jpg) here https://releases.rocket.chat/5.0.0/info
It is this Version https://github.com/RocketChat/Rocket.Chat/commit/83851a0ad551ca0ca34cd91703a62f253b0e863a

That is probably the reason the build server does not update. It conflicts with the version.

**Comment by artutava** [comment]
@stachi Is there a way to get the latest 5.0?

**Comment by stachi** [comment]
> @stachi Is there a way to get the latest 5.0? I mean.. without downloading this pre RC version?

You could build it yourself but I am not into that.
Based on the commits RC 12 is identical to the final version (only the Version Infos are changed).
You could use this for now. https://releases.rocket.chat/5.0.0-rc.12/download

**Comment by aleadco** [comment]
@sampaiodiego and @rodrigok  Could you comment any solution to get to 5.0.0 using the manual method? Or is there a problem? @stachi states that there may be a conflict, is that correct?

**Comment by sampaiodiego** [comment]
thanks guys for letting us know. we're already taking a look on this and will resolve asap

**Comment by sampaiodiego** [comment]
this is fixed now, you can use either `latest` , `stable` or `5.0.0` to download the latest bundle:

```bash
$ curl https://releases.rocket.chat/latest/info
{"tag":"5.0.0","commit":"59cae121081e16ed80c9b65db7c6c235a096d043","key":"build/rocket.chat-5.0.0.tgz","etag":"53e6d27c4a8bc3b83f0ae9078df74734-26","count":31,"nodeVersion":"14.19.3","compatibleMongoVersions":["4.2","4.4","5.0"]}%

$ curl https://releases.rocket.chat/stable/info
{"tag":"5.0.0","commit":"59cae121081e16ed80c9b65db7c6c235a096d043","key":"build/rocket.chat-5.0.0.tgz","etag":"53e6d27c4a8bc3b83f0ae9078df74734-26","count":31,"nodeVersion":"14.19.3","compatibleMongoVersions":["4.2","4.4","5.0"]}%

$ curl https://releases.rocket.chat/5.0.0/info
{"tag":"5.0.0","commit":"59cae121081e16ed80c9b65db7c6c235a096d043","key":"build/rocket.chat-5.0.0.tgz","etag":"53e6d27c4a8bc3b83f0ae9078df74734-26","count":31,"nodeVersion":"14.19.3","compatibleMongoVersions":["4.2","4.4","5.0"]}%
