### ISSUE TITLE
Rocket.cat reports newer version but it's not on latest in the rocketchat docker repository

### ISSUE THREAD

**Issue by bergi9** [RocketChat/Rocket.Chat#26339]
### Description:

The rocket.cat contacted me to update my rocket.chat to version 4.8.2. So I pulled via `docker-compose pull` and it's still the same version on 4.8.1. In my docker-compose file it's not pinned to a version, so it's pinned to `latest` tag. Had manually pin the newer version to docker-compose file.

### Steps to reproduce:

This is my docker-compose file.
```
version: '3.7'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat
    .....
 ```
and this is version 4.8.1 as of now.

### Expected behavior:

When rocket.cat writes me a newer version is available, the newer version should also applied to the `latest` tag.

### Server Setup Information was:

- Version of Rocket.Chat Server: 4.8.1
- Operating System: unraid
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: from docker
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: latest desktop app and iOS
- Operating System:

**Comment by tom666-debug** [comment]
confirmed - it's the same with major release 5.0.0, not available yet on Docker Hub

**Comment by aleadco** [comment]
Related to #23337

**Comment by saschafoerster** [comment]
I updated my docker instance yesterday, first to 4.8.2, then to 5.0.0. Maybe you try again as well?

**Comment by saschafoerster** [comment]
The container on your screenshot is the "official" from Docker. 

The true and only official is this release:
https://hub.docker.com/r/rocketchat/rocket.chat

I also got confused by this. 😅

**Comment by tom666-debug** [comment]
Wow, I agree, its really confusing :stuck_out_tongue_winking_eye:
Thx for the hint, I was able to download the latest images (4.8.2 and 5.0.0).

**Comment by debdutdeb** [comment]
Thanks for clarifying @tom666-debug ! Closing now.

**Comment by bergi9** [comment]
Still the same issue as version 5.1 is not on docker hub.

**Comment by debdutdeb** [comment]
It IS on docker hub, please use rocketchat/rocket.chat NOT just rocket.chat.

**Comment by debdutdeb** [comment]
OUT OFFICIAL one is under OUR account/namespace, i.e. rocketchat/rocket.chat.

**Comment by bergi9** [comment]
Oh ok, thanks
