### ISSUE TITLE
subgroups in a private group

### ISSUE THREAD

**Issue by droup** [RocketChat/Rocket.Chat#2633]
Your Rocket.Chat version: 0.23

Hi guys, first of all.. BRAVO ! What a great job you've done!

we use rocket in our company and it's just awesome! 
Just a suggestion, it will be really great if we can create subgroup in a private group already created.

For example, i create a Private group "fellowshipofthering" with 9 users for a chat with the entire group,
i would like members of this group can create private subgroups into this group, like "human", "hobbits", "oldfriends",...
and when they create the subgroup they just can choose members of "fellowshipofthering".

It's just an example but in a company, it will be really useful to have hierarchy in a private group!
Thanks

**Comment by kramer65** [comment]
Isn't what you're describing simply a new private group? At least, I'm not sure how it differs?

If what you're describing would be possible, wouldn't that create a mess of groups in groups in groups in groups... inception?

**Comment by dytec** [comment]
That would be the worst you can do...

**Comment by droup** [comment]
No create groups in groups in groups wille be the better way to madness...

Imagine the principal private group like a team, subgroups could be multiple projects but that should be limited to one degree of subgroup into the principal private group. 
In this way, it will be easy to find a specific project because it looks like "classified" by team.

**Comment by engelgabriel** [comment]
This will be done on issue https://github.com/RocketChat/Rocket.Chat/issues/2049

But this grouping will be for listing only. We are still deciding if it will be per TAGs or FOLDERS.
