### ISSUE TITLE
Docker image for Rocket.Chat 5.0.0 seems to ignore MONGO_URL environment variable

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#26346]
I'm currently running Rocket.Chat 4.8.2 using Docker and systemd as described at https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd

I replaced the version `4.8.2` by `5.0.0` in the systemd unit just to observe that the Docker container won't properly start up anymore.

Logs:

```
Jul 22 17:04:29 alpha docker[827378]: /app/bundle/programs/server/node_modules/fibers/future.js:313
Jul 22 17:04:29 alpha docker[827378]:                                                 throw(ex);
Jul 22 17:04:29 alpha docker[827378]:                                                 ^
Jul 22 17:04:29 alpha docker[827378]: MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
Jul 22 17:04:29 alpha docker[827378]:     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
Jul 22 17:04:29 alpha docker[827378]:     at listOnTimeout (internal/timers.js:557:17)
Jul 22 17:04:29 alpha docker[827378]:     at processTimers (internal/timers.js:500:7) {
Jul 22 17:04:29 alpha docker[827378]:   reason: TopologyDescription {
Jul 22 17:04:29 alpha docker[827378]:     type: 'ReplicaSetNoPrimary',
Jul 22 17:04:29 alpha docker[827378]:     servers: Map(1) {
Jul 22 17:04:29 alpha docker[827378]:       'localhost:27017' => ServerDescription {
Jul 22 17:04:29 alpha docker[827378]:         _hostAddress: HostAddress { isIPv6: false, host: 'localhost', port: 27017 },
Jul 22 17:04:29 alpha docker[827378]:         address: 'localhost:27017',
Jul 22 17:04:29 alpha docker[827378]:         type: 'Unknown',
Jul 22 17:04:29 alpha docker[827378]:         hosts: [],
Jul 22 17:04:29 alpha docker[827378]:         passives: [],
Jul 22 17:04:29 alpha docker[827378]:         arbiters: [],
Jul 22 17:04:29 alpha docker[827378]:         tags: {},
Jul 22 17:04:29 alpha docker[827378]:         minWireVersion: 0,
Jul 22 17:04:29 alpha docker[827378]:         maxWireVersion: 0,
Jul 22 17:04:29 alpha docker[827378]:         roundTripTime: -1,
Jul 22 17:04:29 alpha docker[827378]:         lastUpdateTime: 1099101446,
Jul 22 17:04:29 alpha docker[827378]:         lastWriteDate: 0,
Jul 22 17:04:29 alpha docker[827378]:         error: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
Jul 22 17:04:29 alpha docker[827378]:             at connectionFailureError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:381:20)
Jul 22 17:04:29 alpha docker[827378]:             at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:301:22)
Jul 22 17:04:29 alpha docker[827378]:             at Object.onceWrapper (events.js:520:26)
Jul 22 17:04:29 alpha docker[827378]:             at Socket.emit (events.js:400:28)
Jul 22 17:04:29 alpha docker[827378]:             at emitErrorNT (internal/streams/destroy.js:106:8)
Jul 22 17:04:29 alpha docker[827378]:             at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Jul 22 17:04:29 alpha docker[827378]:             at processTicksAndRejections (internal/process/task_queues.js:82:21)
Jul 22 17:04:29 alpha docker[827378]:       }
Jul 22 17:04:29 alpha docker[827378]:     },
Jul 22 17:04:29 alpha docker[827378]:     stale: false,
Jul 22 17:04:29 alpha docker[827378]:     compatible: true,
Jul 22 17:04:29 alpha docker[827378]:     heartbeatFrequencyMS: 10000,
Jul 22 17:04:29 alpha docker[827378]:     localThresholdMS: 15,
Jul 22 17:04:29 alpha docker[827378]:     setName: 'rs0',
Jul 22 17:04:29 alpha docker[827378]:     maxSetVersion: 3,
Jul 22 17:04:29 alpha docker[827378]:     maxElectionId: ObjectId {
Jul 22 17:04:29 alpha docker[827378]:       [Symbol(id)]: Buffer(12) [Uint8Array] [
Jul 22 17:04:29 alpha docker[827378]:         127, 255, 255, 255, 0,
Jul 22 17:04:29 alpha docker[827378]:           0,   0,   0,   0, 0,
Jul 22 17:04:29 alpha docker[827378]:           0,  48
Jul 22 17:04:29 alpha docker[827378]:       ]
Jul 22 17:04:29 alpha docker[827378]:     },
Jul 22 17:04:29 alpha docker[827378]:     commonWireVersion: 13,
Jul 22 17:04:29 alpha docker[827378]:     logicalSessionTimeoutMinutes: undefined
Jul 22 17:04:29 alpha docker[827378]:   }
Jul 22 17:04:29 alpha docker[827378]: }
```

This is the `ExecStart` command from the systemd unit:

```
ExecStart=/usr/bin/docker run \
    --name rocketchat \
    -v /var/lib/rocketchat/uploads:/app/uploads \
    -e MONGO_OPLOG_URL=mongodb://mongo:27017/local \
    -e MONGO_URL=mongodb://mongo:27017/rocketchat \
    -e ROOT_URL=[...] \
    --link mongo:mongo \
    --net=rocketchat_default \
    -p 127.0.0.1:3000:3000 \
    -p [::1]:3000:3000 \
    rocketchat/rocket.chat:5.0.0
```

When running Rocket.Chat 4.8.2, the hostname `mongo` does not resolve to `127.0.0.1`. It seems at some point the environment variable `MONGO_URL` is ignored and instead `127.0.0.1` is used (hardcoded?).

I did not see anything in the release notes that anything regarding the deployment changed from 4.8.2 to 5.0.0.

**Comment by siddjellali** [comment]
same issue here !

**Comment by paulchen** [comment]
There are already two issues that seem to describe the same problem:

- https://github.com/RocketChat/Docker.Official.Image/issues/165
- https://github.com/RocketChat/Rocket.Chat/issues/26231

I did not yet try the solution from https://github.com/RocketChat/Rocket.Chat/issues/26231#issuecomment-1184913583

However, if that's the solution and in fact my MongoDB is set up wrongly, in my opinion the documentation at https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd should be set up. Additionally, it might make sense to add this to the release notes.

**Comment by klangborste** [comment]
I had the same issue, then tried it out and it worked well :-)
I agree with that:
> However, if that's the solution and in fact my MongoDB is set up wrongly, in my opinion the documentation at https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd should be updated. Additionally, it might make sense to add this to the release notes.

https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd--> "Build the mongo-init-replica container (only run once)" and then the part:

>mongo mongo/rocketchat --eval "rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'localhost:27017' } ]})"

should be:

`mongo mongo/rocketchat --eval "rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongo:27017' } ]})"`

**Comment by siddjellali** [comment]
Confirm ! solved thanks.

**Comment by dudanogueira** [comment]
Hi! Check out this important note from the 5.0.0 release notes:

Important note

If you're using MongoDB in a Docker container, you might need to add directConnection=true to MONGO_URL and MONGO_OPLOG_URL environment variables. i.e.: MONGO_URL=mongodb://mongo/rocketchat?replicaSet=rs0&directConnection=true

https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0
