### ISSUE TITLE
Omnichannel Analytics

### ISSUE THREAD

**Issue by ruvenss** [RocketChat/Rocket.Chat#26344]
### Steps to reproduce:

User Menu
Omnichannel
Analytics

### Expected behavior:

Show the Analytics without an error notification

### Actual behavior:

The analytics are empty, and an unknown error appears

### Server Setup Information:

- Version of Rocket.Chat Server:  4.8.1
- Operating System: Ubuntu 20.x
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog:  WiredTiger
- NodeJS Version:  14.18.3
- MongoDB Version: 5.0.9

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 103.0.5060.134
- Operating System: Mac O

### Additional context

![Untitled 4](https://user-images.githubusercontent.com/3003888/180456314-c4ffce9d-ac68-4429-9266-afc8715ab808.jpg)

### Relevant logs:

Log are empty

**Comment by renatobecker** [comment]
The problem is already solved.
https://github.com/RocketChat/Rocket.Chat/pull/25873
