### ISSUE TITLE
After updated from 4.8.1 to 5.0 , Even admin accounts shows : Oops! Something went wrong. Please reload the page or contact an administrator.

### ISSUE THREAD

**Issue by bingovivi** [RocketChat/Rocket.Chat#26352]
### Description:

After updated from 4.8.1 to 5.0 , Even admin accounts shows : Oops! Something went wrong. Please reload the page or contact an administrator.

![图片](https://user-images.githubusercontent.com/13223430/180700722-f9abb99f-4733-4212-9c10-0a674dbdd180.png)
                       | 

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server:  5.0
- Operating System:  Ubuntu 21
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:4.4.15

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by bingovivi** [comment]
![图片](https://user-images.githubusercontent.com/13223430/180701665-b92662b4-b1ec-44b9-8411-d60483fb09ab.png)

OMG ， If anyone else ! lol

**Comment by bingovivi** [comment]
> ![图片](https://user-images.githubusercontent.com/13223430/180701665-b92662b4-b1ec-44b9-8411-d60483fb09ab.png)
> 
> OMG ， If anyone else ! lol
> 
> Mamamia !!!

Why 4.8.1 setting like this , it can work normal?   Can anyone add select all button please ?

**Comment by ankar84** [comment]
I don't have such issue on 2 my test deployments. Both docker method.

**Comment by aleadco** [comment]
I can confirm this in 5.0.0-rc12 with manual deployment, in all rooms we get `Oops! Something went wrong. Please reload the page or contact an administrator`... @bingovivi the permissions mentioned in the configuration section do not need to be specified unless you need to customize them for specific roles, so by default they should all be disabled.

I have always had everything unchecked, if any of these permissions are now required then there must be some error.

![image](https://user-images.githubusercontent.com/35962168/181090865-83236239-f61e-4850-aec5-fb1572c264cd.png)

**Comment by lovekyleman** [comment]
Confirm the issue

**Comment by Neboer** [comment]
Same issue here. After upgrade RocketChat to 5.0.0, the browser client shows this error when a user opens up a chat room. In browser console it says: 

```
Uncaught Error: TypeError: Cannot read properties of undefined (reading 'some')
    at Object.getLanguage (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:207781:89)
    at eval (/client/views/room/MessageList/hooks/useAutotranslateLanguage.ts:formatted:21:29)
    at 07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:230448:33
    at t._compute (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:151278:50)
    at new t (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:151223:42)
    at o.autorun (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:151399:37)
    at 07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:230447:37
    at Object.useMemo (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:72992:37)
    at t.useMemo (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:59479:40)
    at r (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:formatted:230444:35) 
```

Please fix it and thank you very much!

**Comment by treebes** [comment]
We had a similar issue this morning, make sure the users having this issue have a language set.

![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)

**Comment by Neboer** [comment]
> We had a similar issue this morning, make sure the users having this issue have a language set.
> 
> ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)

Very helpful! Thanks a lot. Is there a way for admins to update users which have a void language section with default language value quickly?

**Comment by charisteed28** [comment]
Same problem.
After upgrading 4.8.1 to 5.0.0, docker-image.
Language in user set default.
No errors in log.

Console show this:
```
Uncaught Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at O (/client/views/room/MessageList/components/MessageContent.tsx:1:2814)
    at Dc (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:59696)
    at gi (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:69176)
    at di (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:68510)
    at li (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:68168)
    at Rs (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:114835)
    at nu (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:98840)
    at ru (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:98768)
    at eu (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:98631)
    at Gs (07209f7aff72860ca8f6c4de51803a1e16f37033.js?meteor_js_resource=true:1124:95485) {componentStack: '\n    at O (/client/views/room/MessageList/componen…esource=true:1218:63317)\n    at Suspense\n    at f'}
```

Haaalp!

**Comment by treebes** [comment]
It looks like this will be the way to do it.

https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/users-endpoints/set-preferences#payload

> > We had a similar issue this morning, make sure the users having this issue have a language set.
> > ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)
> 
> Very helpful! Thanks a lot. Is there a way for admins to update users which have a void language section with default language value quickly?

**Comment by yatounoneko** [comment]
> We had a similar issue this morning, make sure the users having this issue have a language set.
> 
> ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)

I have the same problem and resumed after change language. I see the problem, when i go back to the home page from the settings menu that language option will get null but it was low probability,. Fortunately, this situation currently only affects accounts with panel permissions and will not affect ordinary users......

**Comment by ghbranding** [comment]
> > We had a similar issue this morning, make sure the users having this issue have a language set.
> > ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)
> 
> I have the same problem and resumed after change language. I see the problem, when i go back to the home page from the settings menu that language option will get null but it was low probability. ~Fortunately, this situation currently only affects accounts with panel permissions and will not affect ordinary users......~
> 
> Update: 100% can repeat the problem, as long as the language is updated on the Android client (I tested it from English to Chinese), there will be a NULL situation. If the App is switch to any language in the web page, it will become English.

Worked for me selecting English or Default, but persist on some languages like 'Português do Brasil'.

**Comment by schieck0** [comment]
> > We had a similar issue this morning, make sure the users having this issue have a language set.
> > ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)
> 
> I have the same problem and resumed after change language. I see the problem, when i go back to the home page from the settings menu that language option will get null but it was low probability. ~Fortunately, this situation currently only affects accounts with panel permissions and will not affect ordinary users......~
> 
> Update: 100% can repeat the problem, as long as the language is updated on the Android client (I tested it from English to Chinese), there will be a NULL situation. If the App is switch to any language in the web page, it will become English.

Worked for me selecting English or Default, but persist on some languages like 'Português do Brasil'.

**Comment by RACunha** [comment]
> > > We had a similar issue this morning, make sure the users having this issue have a language set.
> > > ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)
> > 
> > 
> > I have the same problem and resumed after change language. I see the problem, when i go back to the home page from the settings menu that language option will get null but it was low probability. ~Fortunately, this situation currently only affects accounts with panel permissions and will not affect ordinary users......~
> > Update: 100% can repeat the problem, as long as the language is updated on the Android client (I tested it from English to Chinese), there will be a NULL situation. If the App is switch to any language in the web page, it will become English.
> 
> Worked for me selecting English or Default, but persist on some languages like 'Português do Brasil'.

Same here

**Comment by yatounoneko** [comment]
Version 5.0.2 seems to fix the situation where "Oops!..." does not appear even if the language field is NULL.
At least Chinese I tried normal. But it seems that some languages ​​can't be used directly(Select language then show "Oops!..." error at once #26522), please upgrade carefully.

**Comment by terR0Q** [comment]
Upgraded to 5.0.2, this didn`t fix problem for slack+russian messages.

**Comment by danielfariati** [comment]
Yep... Confirm that the error happens when selecting the language "Português do Brasil".
Asking the users to rollback the language to "Default" works (even if the "Default" is "Português do Brasil" for most of them LOL).

You can run this on MongoDB as a workaround, while the bug is not fixed:
```
db.users.updateMany(
    {
        $and: [
            {'settings.preferences.language': {$ne: null}},
            {'settings.preferences.language': {$ne: ''}}
        ]
    },
    {
        $set: {
            'settings.preferences.language': '',
            language: ''
        }
    }
)
```
This should rollback all the users to the default language.
(You could probably remove the find clause as do this to all users, instead of only for users who have a language set... But this is how I executed it just to be sure)

**Comment by LeoColman** [comment]
Happens on my end independent of language.
Javascript console displays
> Uncaught Error: TypeError: j.replies is undefined

**Comment by LeoColman** [comment]
Can confirm it's still happening in 5.0.3

**Comment by saschafoerster** [comment]
We also had this issue with one account, who had the language setting "German informal". My account on the same server didn't have this problem, but I had "German formal". After switching to "German formal" the channels were visible again.

**Comment by LeoColman** [comment]
I tried changing the language to English, Default (which in my server is Português Brasileiro) and PTBR itself. Some rooms appear again after switching to English, but most are still crashing with the Type Error from my previous comment

**Comment by LeoColman** [comment]
Can confirm it's still happening in 5.0.4

**Comment by LeoColman** [comment]
Can confirm it's still happening in 5.1.0-rc.0

**Comment by LeoColman** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/26365#issuecomment-1228707836

This hack by @iglooom fixed the issue for me

**Comment by Neboer** [comment]
> [#26365 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/26365#issuecomment-1228707836)
> 
> This hack by @iglooom fixed the issue for me

Do these two issues share a same workaround?

**Comment by LeoColman** [comment]
I'm not completely sure if they're duplicate issues

**Comment by lanjackg2003** [comment]
> > We had a similar issue this morning, make sure the users having this issue have a language set.
> > ![image](https://user-images.githubusercontent.com/23241603/181587572-457cf5ce-5540-4570-917e-3d3279e7e1b4.png)
> 
> I have the same problem and resumed after change language. I see the problem, when i go back to the home page from the settings menu that language option will get null but it was low probability. ~Fortunately, this situation currently only affects accounts with panel permissions and will not affect ordinary users......~
> 
> Update: 100% can repeat the problem, as long as the language is updated on the Android client (I tested it from English to Chinese), there will be a NULL situation. If the App is switch to any language in the web page, it will become English.

Yep. It looks like a language issue. When I switch back to English language on the phone app the webpage re-works again.
Don't try to switch back the language to English on the web browser.
