### ISSUE TITLE
Does Community Edition haven’t  these 4  basic features in Offline License?

### ISSUE THREAD

**Issue by yukeiyang** [RocketChat/Rocket.Chat#26350]
After installing the Rocketchat Community Edition on Ubuntu 22.04, I applied the Offline License according to the official document: 

https://docs.rocket.chat/rocket.chat-saas/cloud-account/manage-your-workspace-on-cloud-account/workspaces/apply-offline-license

But, I found these 4 basic features still always can not be activated  on Info Tab of Administration. 

Omnichannel
Auditing
Canned Responses
Engagement Dashboard

![image](https://user-images.githubusercontent.com/6512594/180657208-7fb3b98d-a3fe-491e-85f4-7049e643f708.jpeg)

I want to know, Does the Community Edition haven’t  these 4  basic features in Offline License?

**Comment by dudanogueira** [comment]
Hi! Community Edition has Omnichannel with a basic feature set. 

[Auditing](https://docs.rocket.chat/guides/message-auditing), [Canned Responses](https://docs.rocket.chat/guides/omnichannel/canned-responses/canned-responses-omnichannel-managers-guide), [Engagement Dashboard](https://docs.rocket.chat/guides/administration/admin-panel/engagement-dashboard) and other features are Enterprise only ([you can check those here](https://rocket.chat/pricing)).

The Offline license / trial was probably not properly applied for some reason. Is this installation air-gaped or it has internet access?

You can get enterprise support at https://support.rocket.chat/

**Comment by yukeiyang** [comment]
@dudanogueira Thank you. Your answer is awesome, I was stuck here before you told me this information. Now, Solved.
