### ISSUE TITLE
[bug] Description of all slash commands undefined since 5.0

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#26355]
### Description:

Description of all slash commands unavailable since 5.0

### Steps to reproduce:

1. Write `/` in message composer to get list of all slash commands
2. All descriptions are in `undefined` status

### Expected behavior:

Slash commands description should be on place

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/180769132-45594f7d-04b6-4198-a1ae-70056ca17efa.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: OL8
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 103
- Operating System: Windows 10

**Comment by ankar84** [comment]
could be a fixed by https://github.com/RocketChat/Rocket.Chat/pull/26372

**Comment by debdutdeb** [comment]
Yup, fixed in #26372 :)
