### ISSUE TITLE
App can't connect to my Rocket.Chat installation. How to debug?

### ISSUE THREAD

**Issue by kramer65** [RocketChat/Rocket.Chat#2636]
Your Rocket.Chat version: 0.22.0

I've installed RocketChat using the Docker image by issuing the following commands:

```
docker pull rocketchat/rocket.chat:latest
docker run -d --name db mongo mongod --smallfiles
docker run -d --name rc --link db:db -e MONGO_URL=mongodb://db:27017/rocketchat -e ROOT_URL=http://52.58.71.91:3000 -p 3000:3000 rocketchat/rocket.chat
```
I explicitly set the ROOT_URL as an environment variable so that it is correct. The site works fine, but unfortunately, the Android app won't fully connect to my server instance. It first connects, downloads some files, and then I end up with the screen below.

Does anybody know what could be wrong or how I can debug this?

![screenshot_20160324-163123](https://cloud.githubusercontent.com/assets/596581/14028029/cf2a39d0-f1fa-11e5-918c-326e41f1491b.png)

**Comment by engelgabriel** [comment]
You need to set the admin setting: Site URL

**Comment by kramer65** [comment]
@engelgabriel - Thanks for the suggestion, but I forgot to mention that that is already set as well:

![schermafbeelding 2016-03-25 om 07 51 10](https://cloud.githubusercontent.com/assets/596581/14039615/888911fe-f25e-11e5-9d00-43595c5b572b.png)

I tried looking at the server logs, but that just says the following:

```
I20160324-16:00:00.004(0) (percolate_synced-cron.js:71) SyncedCron: Starting "Generate and save statistics".
I20160324-16:00:00.588(0) (percolate_synced-cron.js:71) SyncedCron: Finished "Generate and save statistics".
I20160324-17:00:00.002(0) (percolate_synced-cron.js:71) SyncedCron: Starting "Generate and save statistics".
I20160324-17:00:00.593(0) (percolate_synced-cron.js:71) SyncedCron: Finished "Generate and save statistics".
etc. etc.
```

Any more ideas?

**Comment by rodrigok** [comment]
@kramer65 can you test our latests develop version? We did some changes related to this issue.

**Comment by kramer65** [comment]
@rodrigogs - I'd love to test you latest develop version. Is there a docker version of that, or do I need to manually install that?

**Comment by TheReal1604** [comment]
Change this: docker pull rocketchat/rocket.chat:latest to docker pull rocketchat/rocket.chat:develop 

This should pull the latest image from the develop branch.

**Comment by kramer65** [comment]
Awesome, it works now!
From today I'm going to test this within our organisation with 2 other people. If that goes well, next week we're gonna ditch slack and use rocketchat with our whole organisation (about 20 people). 

One more question: what turned out to be the problem?

**Comment by Sing-Li** [comment]
A bug introduced by recent code changes that messed caused old ROOT_URL value to be used.  Now fixed.
