### ISSUE TITLE
 RocketChat bot connects via personal token, but creates error 401 - {"status":"error","message":"You must be logged in to do this."}

### ISSUE THREAD

**Issue by saschafoerster** [RocketChat/Rocket.Chat#26360]
I have been using N8N to automate stuff in RocketChat. The credentials and workflows where working until I updated to 4.8.1

Since then my bot get's this error, when trying to sent a message to a channel (which it did successfully for months) 

`401 - {"status":"error","message":"You must be logged in to do this."}`

The connection is successful, I also created a second token without 2FA, but the result is the same: 
<img width="891" alt="Bildschirmfoto 2022-07-26 um 10 15 14" src="https://user-images.githubusercontent.com/1153741/180958878-bd4424cf-c0a5-49a4-a49b-0941f5ae6cdd.png">

When using the credentials, I get this error (which I didn't get before)
<img width="510" alt="Bildschirmfoto 2022-07-26 um 10 16 09" src="https://user-images.githubusercontent.com/1153741/180958884-0248f899-12f6-40a6-abf0-0eb98a8ae71d.png">

### Server Setup Information:

- Version of Rocket.Chat Server: now 5.0.0 (but I had this problem also with 4.8.1 and 4.8.2)
- Operating System: Debain
- Deployment Method: docker
- Number of Running Instances: 1  
- DB Replicaset Oplog: yes
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15

**Comment by saschafoerster** [comment]
I also wonder, that the bot is not online anymore. I remember it to be online all the time: 
<img width="287" alt="Bildschirmfoto 2022-07-26 um 10 28 50" src="https://user-images.githubusercontent.com/1153741/180960831-360d0ce9-a088-419c-879d-d655dc6fae9b.png">

I also tried to see more details in the protocol, but it seems as if there is no notice of the login-error.

**Comment by debdutdeb** [comment]
@dudanogueira do you know how n8n works? 😬

**Comment by saschafoerster** [comment]
Sorry guys, I guess it's a problem of N8N and the solution has been found already! Thanks anyway: 
https://github.com/n8n-io/n8n/issues/3776

**Comment by debdutdeb** [comment]
Thanks for letting us know! Cheers

**Comment by lknite** [comment]
@saschafoerster I'd like to use a rocketchat trigger to start an n8n workflow & also use human-in-the-loop with n8n.  Have you already implemented these workflows or know of a repo where someone has?

**Comment by saschafoerster** [comment]
@lknite I only have workflows that push into RocketChat, not the other way around. Sorry.

**Comment by lknite** [comment]
I wrote a simple rocketchat client that watches either a channel or waits for a direct message and sends a local webhook in response.

Using as a workaround cause there isn't a webhook rocketchat trigger for n8n yet.

https://gitlab.com/lknite/webhook-chat-client
