### ISSUE TITLE
Jitsi JWT auth broken in one-on-one rooms in 4.8.2 (using web browser)

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat#26364]
### Description:

With version 4.8.2 Jitsi calls using JWT auth are broken. Jitsi reports an authentication error.

![image](https://user-images.githubusercontent.com/3321655/181023593-f1a92e92-3d43-4d38-be46-abfdb3a91130.png)

![image](https://user-images.githubusercontent.com/3321655/181023641-343e3798-6c96-4633-bd3e-09621bbbdbaf.png)

Mobile Apps are *not* affected, these are working fine. Only web browser sessions are affected.

Also, calls in channels (group rooms) are also working.

### Steps to reproduce:

1. Have Jitsi set up with JWT token authentication, rooms hash turned off
![image](https://user-images.githubusercontent.com/3321655/181024064-d57eff13-d1fd-43ec-a15d-4af71df97383.png)

2. Start a video call in a direct chat room (one-on-one chat) or join it in the web browser.
3. See the authentication error

### Expected behavior:

You should be able to join or start video conferences also in direct chat rooms.

### Actual behavior:

Jitsi reports authentication error. See above.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.2
- Operating System: Ubuntu 20.04 LTS
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.20 / wiredTiger (oplog Aktiviert)

### Client Setup Information

- Desktop App or Browser Version: Only Browser is affected. Mobile apps are working fine.
- Operating System: 

### Additional context

Decoding the JWT token from the browser console does not show a direct issue in both cases, the only difference in the decoded tokens is that the token from the one-on-one room has these "%20" in the room name where RC uses spaces in the name. The working channel JWT token does not have these "%20":

Working:

```
{
  "iss": "JitsiMydomain",
  "sub": "jitsi.mydomain.de",
  "iat": 1658842884,
  "nbf": 1658842884,
  "exp": 1658846484,
  "aud": "RocketChat",
  "room": "JayChatadmintest",
  "context": {
    "user": {
      "name": "***",
      "email": "**@***",
      "avatar": "https://mydomain.de/avatar/marco",
      "id": "ethmug86Z687CiE2F"
    }
  }
}

```
Not working:

```
{
  "iss": "JitsiMydomain",
  "sub": "jitsi.mydomainde",
  "iat": 1658842531,
  "nbf": 1658842531,
  "exp": 1658846131,
  "aud": "RocketChat",
  "room": "JayChatadmin%20x%20marco",
  "context": {
    "user": {
      "name": "***",
      "email": "**@***",
      "avatar": "https://mydomain.de/avatar/marco",
      "id": "ethmug86Z687CiE2F"
    }
  }
}
```

I did not use it for a while in direct chat rooms with the browser, so it might be broken a few versions before 4.8.2

**Comment by ankar84** [comment]
Really strange. We are on 4.8.2 now and don't have that issue. All clients works perfect with JWT Token authentication, bot Web and Mobile.

**Comment by gpopesc** [comment]
I was on 4.8.1, now on 5.0.1 and jitsi integration works with hosted jitsi server,

**Comment by jacotec** [comment]
Updated to version 5 and I needed to redo all the config because of the new kind how to configure video conferences. Now it's suddenly working.

No idea what broke in V4, closing. Thank you for your comments!
