### ISSUE TITLE
[bug] Chats holds to load history for some time until any action since 5.0 version

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#26361]
### Description:

Since 5.0 I consider that some chats are loading history for a long time (some even infinite). 
But on any action, history is loaded immediately.

### Steps to reproduce:

1. Search user you don't have recent talk (for easy reproduce, that could be any chats in fact)
2. Click to start conversation with that user
3. Chat history is loading even if there is no history and it as a brand new DM

### Expected behavior:

Chats open fast like it was on a pre 5.0 versions

### Actual behavior:

![image](https://user-images.githubusercontent.com/4023037/180988323-edebc8a6-a08a-4ac8-a93a-df0d8d328498.png)
From opens server
![load-history01](https://user-images.githubusercontent.com/4023037/180991158-a3c13434-9769-4dc9-ab32-86c870939a75.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: OL8
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 103
- Operating System: Windows 10

### Additional context

I see it on open.rocket.chat as well

### Relevant logs:

No logs in moment of loading...

**Comment by stachi** [comment]
Can confirm this with 5.0.0-rc12 (which is identical to final) with manual deployment. Tested with latest Firefox ESR. It happens very randomly.

**Comment by JeroenAdam** [comment]
Yes, a large negative impact on performance since upgrade from 4.8.2
Rocketchat v5.0.0 - Mongo 5.0.9
I tried dropping/creating the index navigation.token on messages, it is not a solution

**Comment by engelgabriel** [comment]
Are there any errors on the browser console?

**Comment by JeroenAdam** [comment]
No errors in console.
Maybe this screenshot can help.
![image](https://user-images.githubusercontent.com/16437621/181545924-fa297c0b-4778-4753-a624-2fd9f2364990.png)

**Comment by milton-rucks** [comment]
Task already included in the current sprint as a high priority - the team is working on that

**Comment by ankar84** [comment]
could be fixed in https://github.com/RocketChat/Rocket.Chat/pull/26425

**Comment by chotaire** [comment]
Thanks for making this high priority. It's still broken in 5.0.1, chat history doesn't update until I move my mouse around and this absolutely needs fixed. I wonder how that slipped through, everyone should have seen this bug happening right away?

**Comment by ankar84** [comment]
> Thanks for making this high priority. It's still broken in 5.0.1, chat history doesn't update until I move my mouse around and this absolutely needs fixed. I wonder how that slipped through, everyone should have seen this bug happening right away?

Guess that will be fixed in 5.0.2 according to a milestone label in PR

**Comment by milton-rucks** [comment]
Fixed in 5.0.3
https://github.com/RocketChat/Rocket.Chat/pull/26425

**Comment by shevchukma** [comment]
We confirm. In our installation, the bug is gone. Thanks a lot!
