### ISSUE TITLE
Unable to set Environment Variable in Rocket.Chat Cloud (SaaS)

### ISSUE THREAD

**Issue by FrankLuisDev** [RocketChat/Rocket.Chat#26384]
### Description:

Impossible to set Environment Variable in Rocket.Chat Cloud (Saas)
As described in the [Developer Guide](https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/users-endpoints/create-users-token), i need to integrate the /api/v1/users.createToken in order to obtain the authentication-token and perform the Iframe authentication

### Steps to reproduce:

1. Properly setted the permission _user-generate-access-token_ on Rocket.Chat Cloud Administration Panel for all roles (just for be sure)
2. Integrate the api my_server.rocket.chat/api/v1/users.createToken

### Expected behavior:

Obtain the the authentication token
`{
  "data": {
    "userId": "BsNr28znDkG8aeo7W",
    "authToken": "2jdk99wuSjXPO201XlAks9sjDjAhSJmskAKW301mSuj9Sk",
  },
  "success": true
}`

### Actual behavior:
`{
  "success": false,
  "error": "Not authorized [error-not-authorized]",
  "errorType": "error-not-authorized",
  "details": {
    "method": "createToken"
  }
}`

### Server Setup Information:

- Version of Rocket.Chat Server: 4.8.1 (Cloud)
- Operating System: n/a
- Deployment Method: n/a
- Number of Running Instances:  n/a
- DB Replicaset Oplog: n/a
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.8 / wiredTiger (oplog Enabled)
- License: Enterprise Trial

### Client Setup Information
- Desktop App or Browser Version: Thunder Client plugin on Visual Studio Code
- Operating System: Windows 11

### Additional context

The guide reported [here ](https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/users-endpoints/create-users-token) say that: _IMPORTANT To be able to use this endpoint you must set the ENV VAR (CREATE_TOKENS_FOR_USERS=true)._ but is not documented where i can set this enviornment variable in Rocket.Chat Cloud installation 
I could provide the Deployment ID.

**Comment by dudanogueira** [comment]
Hi! Answered at the forums :)

https://forums.rocket.chat/t/unable-to-set-environment-variable-on-rocket-chat-cloud-saas/14566
