### ISSUE TITLE
Add ability to delete channel's history/media

### ISSUE THREAD

**Issue by mikrobyte** [RocketChat/Rocket.Chat#2639]
Your Rocket.Chat version: 0.23.0

> This is not an issue but a feature request "nice to have"

**1.** The ability to delete a channel's or 1 to 1 conversation history and media shared.

**2.** For small servers, the ability to automatically delete/overwrite the memory used for conversation and shared media history. Say, if it's older than X days, months. **OR**, whenever the conversation history or media buffer is over X amount of gigabytes, then start overwriting the oldest line/media.

**Comment by 6a7070** [comment]
I'm interested in this ability too. It's a requirement from my team. We need a tool that has the ability to purge all history after X days or at least ad-hoc by an admin.

**Comment by dggtydnk** [comment]
This is also a requirement for my company.  I desperately want to adopt RocketChat in our company, but our executives said there must be an option to limit/not store history for certain channels before this can be deployed.

**Comment by joshzitting** [comment]
I need this feature too! any progress?

**Comment by marceloschmidt** [comment]
We have a /api/v1/rooms.cleanHistory API method that will delete messages between two dates. We could change that method to also delete files. We could probably add an option to delete files only on this method.
