### ISSUE TITLE
URL detection wrong

### ISSUE THREAD

**Issue by hegedussz** [RocketChat/Rocket.Chat#26405]
### Steps to reproduce:

1.  Copy URL link
2. Pase URL link in channel 

### Expected behavior:

When I write/copy URL text channel or private message the URL detecion wrong

### Actual behavior:

![link](https://user-images.githubusercontent.com/20745628/181714645-f87f59f2-ebf1-4836-8201-2bf9a932ad06.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Deployment Method:  docker
- Number of Running Instances: 3 
- MongoDB Version: 5.0.6

### Client Setup Information

- Desktop App or Browser Version: Desktop App - 3.8.7
- Operating System: Windows 11

### Additional context

When I write/copy URL text in Reply Thread or Quote the URL detection fine

**Comment by hugocostadev** [comment]
duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/26661
