### ISSUE TITLE
Script Full Screen button in 'Integrations' does not work

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#2640]
Your Rocket.Chat version: 0.23.0

1. Create integration
2. Press Full Screen button under scripts code view

I see this in the console
```
Uncaught TypeError: Cannot read property 'CodeMirror' of undefined
```

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/commit/28aa767774f18222dea087a14db879458d21acf7

Thanks
