### ISSUE TITLE
Remove "admin" next to username?

### ISSUE THREAD

**Issue by xcpdq** [RocketChat/Rocket.Chat#26409]
Hello,

Starting version 5.0 there is a "Admin" text displayed near the username in the chats. Is it possible to hide this?

Thank you!

**Comment by ankar84** [comment]
Try Hide roles in ### My Account - Preferences - Message
![image](https://user-images.githubusercontent.com/4023037/181740616-95137084-def0-4860-b6f9-b3a985332e50.png)

**Comment by urosino** [comment]
I believe this **Display Roles** setting is now ignored, the same as **Embed Ignored Hosts**.

**Comment by chotaire** [comment]
Well, this really needs to be fixed. To be honest, I wonder who needs this info in each and every chatline anyway. I don't want my users to see what a huge genital I suddenly have so I am not upgrading any further instances to 5.0 for now.

**Comment by Romich777** [comment]
5.0.1 Admin/Settings/Layout/User Interface/Display Roles still have no effect

**Comment by Romich777** [comment]
> Try **Hide roles** in **My Account - Preferences - Message** ![image](https://user-images.githubusercontent.com/4023037/181740616-95137084-def0-4860-b6f9-b3a985332e50.png)
> 
> And Also Administrative setting for whole workspace **Admin UI - Settings - Layout - User Interface** ![image](https://user-images.githubusercontent.com/4023037/181741638-98ad3729-2a7c-4014-a0bd-10f6cf70d357.png)

In what chat version you made these screenshots?

**Comment by rtyshyk** [comment]
> Well, this really needs to be fixed. To be honest, I wonder who needs this info in each and every chatline anyway. I don't want my users to see what a huge genital I suddenly have so I am not upgrading any further instances to 5.0 for now.

Use CSS to hide your huge genitalia. Go to the Settings -> Layout -> Custom CSS and then...
```css
div .rcx-message-header__roles {
  display: none !important;
}
```

**Comment by chotaire** [comment]
@rtyshyk Good idea, thanks. 

Note: I remember the "Bot" tag was always displayed, eventhough display roles had been turned off. Not sure if that was intended, maybe because a bot has no genitalia? Your aforementioned hint may likely also hide that tag, I'll inspect later.

**Comment by rtyshyk** [comment]
> @rtyshyk Good idea, thanks. 
> 
> 
> 
> Note: I remember the "Bot" tag was always displayed, eventhough display roles had been turned off. Not sure if that was intended, maybe because a bot has no genitalia? Your aforementioned hint may likely also hide that tag, I'll inspect later.

We use default rocket.cat as a bot, I have never seen Bot role near it.

**Comment by chotaire** [comment]
Webhooks were displaying it.

![bot](https://user-images.githubusercontent.com/9246549/183064092-957333a3-3aa8-4268-b0da-bd04301efb69.png)
