### ISSUE TITLE
[bug] Update to 5.0.0 - no headlines in chat history but in threads

### ISSUE THREAD

**Issue by hans4rc** [RocketChat/Rocket.Chat#26406]
### Description:

headlines (# to ####) are ignored in the chat history, but shown in threads.

### Expected behavior:

![image](https://user-images.githubusercontent.com/66670106/181730783-e6aaee4a-9d42-471b-b4c3-260313f2d2e1.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/66670106/181730231-bb895592-4572-4b94-9863-531d7c510930.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: Rocky Linux
- Deployment Method: do not know
- Number of Running Instances: 1
- DB Replicaset Oplog: 5.0.9 oplog activated
- NodeJS Version: 14.20.0
- MongoDB Version: 5.0.9

### Client Setup Information

- Desktop App or Browser Version: Chrome 103.0.5060.134
- Operating System: Windows 10 Pro

**Comment by hugocostadev** [comment]
Fixed in the latest 6.0.0 release
