### ISSUE TITLE
Error starting version 5.0 after upgrade

### ISSUE THREAD

**Issue by vura** [RocketChat/Rocket.Chat#26411]
Hii,
I'm having trouble starting version 5.0 later.
I did all the correct procedures to update mongo to version 5.0.
It's working.
But when I update the application version (Rocket.Chat) it gives an error, timeout.

MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

Anyone having the same problem?

Currently my Rocket.Chat working:
**Rocket Version:** 4.8.2
**Deployment ID:** ***
**App engine version:** 1.32.0
**node version:** v14.18.3
**Database migration:** 265 (July 28, 2022 15:54)
**MongoDB:** 5.0.9 / wiredTiger (oplog Enabled)
**Commit Details:**
HEAD: (***)
Branch: HEAD
**PID:** 1

**Comment by ololukaszuk** [comment]
If you are using docker in my case this helped:

https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0#:~:text=Important%20note,rs0%26directConnection%3Dtrue
Important note

If you're using MongoDB in a Docker container, you might need to add directConnection=true to MONGO_URL and MONGO_OPLOG_URL environment variables. i.e.: MONGO_URL=mongodb://mongo/rocketchat?replicaSet=rs0&directConnection=true

**Comment by vura** [comment]
Hii @ololukaszuk ,

I also use docker.
I updated mongoDB and rocket.chat through this site but I still couldn't update to version 5.0. Displays the error I said.

My current settings Rocket
MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replSet=rs01
MONGO_URL: mongodb://mongodb:27017/rocketchat


Do I change to the way you said?
MONGO_URL=mongodb://mongo:27017/rocketchat?directConnection=true
MONGO_OPLOG_URL=mongodb://mongo:27017/local?directConnection=true

Thanks!!!

**Comment by ololukaszuk** [comment]
Hi, I'm guessing that if you're using replSet=rs01 parameter in MONGO_OPLOG_URL you should probably keep it.
So in your case I guess it should look like this:

MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replSet=rs01&directConnection=true
MONGO_URL: mongodb://mongodb:27017/rocketchat?directConnection=true

**Comment by dudanogueira** [comment]
Consider the important notes on 5.0.0 release regarding this issue. CLosing for now.
