### ISSUE TITLE
Error page when reading as Anonymous User public channel

### ISSUE THREAD

**Issue by sleeplessnight2** [RocketChat/Rocket.Chat#26424]
### Description:

When reading as an anonymous user of a public channel, the message history crashes after some time.

### Steps to reproduce:

1. Create Public Channel. Allow anonymous reading and type some messages at this room
2. Open the channel as anonymous User
3. You will now see the messages list
4. click inside the list and wait less than 10 seconds (depends on the hosted server...)
5. you will see the error page in the message list.

### Expected behavior:

anonymous user can read the messages

### Actual behavior:

you will see the error page in the message list.
 and the Browser console show this:

![2022-07-29 23 46 17](https://user-images.githubusercontent.com/8561601/181847370-9c37b05f-8c64-474a-a6aa-90eada4eab5b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: Ubuntu 20.04
- <label type="info"></label>- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.9 / wiredTiger (oplog active)

### Client Setup Information

- Desktop App or Browser Version: testet with Chrome, latest
- Operating System: 

### Additional Info
This did not happen in the v4.8.2. I have just updated to 5.0.0 without changing anything...

**Comment by sleeplessnight2** [comment]
Version 5.2.0 has completely destroyed the function.

Now the buttons to login or write anonymously don't even go...

The browser console is full of error messages.
Should a developer look at this here, I'll give more info.

**Comment by sleeplessnight2** [comment]
nobody cares about this. waste of time

**Comment by derpsteb** [comment]
But why close the issue, it's not resolved? :D
