### ISSUE TITLE
Styling error in integrations view on update

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#2643]
Your Rocket.Chat version: 0.23.0

The integrations view has a different style for a fresh install and an updated install. There are no obvious errors on the browser console, so I am not sure how to give you more information.

A fresh install on Rocket.Chat 0.23.0 looks like below:
![fresh_install](https://cloud.githubusercontent.com/assets/82041/14038519/4fd1a2e4-f20f-11e5-9770-f5c37fede8cc.png)

An updated install of Rocket.Chat looks like below:
![on_update](https://cloud.githubusercontent.com/assets/82041/14038520/4ff0c764-f20f-11e5-9f7b-e25399f07015.png)

Is there any styling related info saved in mongodb? Maybe there is some obsolete data from a previous version. [Cloudron](https://cloudron.io) apps only retain the db across updates.

**Comment by gramakri** [comment]
You can see the breakage here : https://talk-demo.cloudron.me/admin/integrations (username: cloudron password: cloudron)

**Comment by engelgabriel** [comment]
This is fixed on version 0.24.0
Please reopen otherwise
