### ISSUE TITLE
Customer Name not appear after upgrade to 5.0

### ISSUE THREAD

**Issue by neo-clon** [RocketChat/Rocket.Chat#26455]
### Description:

After upgrade my workspace, the name of the customers on Omnichannel Contact Center not appear

![image](https://user-images.githubusercontent.com/12282168/182480194-af0fffdb-5257-4120-b1be-539545ea85c1.png)

![image](https://user-images.githubusercontent.com/12282168/182480261-b619c2da-ec11-4d55-9952-d7ca241256e5.png)

**Comment by KevLehman** [comment]
Hey! Good morning!

Can you please share with us the result of the corresponding `visitors.search` call (from network tab, don't forget to anonymize it! :) )

Testing on 5.1 (or develop, better said) I cannot reproduce the issue. So wanted to know what's being returned from the BE regarding those visitors to see how we can solve it, thanks! 
 
![image](https://user-images.githubusercontent.com/11577696/187974906-1b098377-a0d5-4966-a01d-7e7002ce0534.png)

**Comment by neo-clon** [comment]
Fixed after upgrade to version 5.1
