### ISSUE TITLE
system not recognize user non latin letters

### ISSUE THREAD

**Issue by amitmeyraz** [RocketChat/Rocket.Chat#2645]
Your Rocket.Chat version: (23)
hi, enclose a PS

when try to change role of users via permission the system not recognize users that there name isnt latin.
![rc2](https://cloud.githubusercontent.com/assets/5375635/14041249/08e423a4-f280-11e5-9d35-f6e41396e935.jpg)

**Comment by sampaiodiego** [comment]
@amitmeyraz this field only search for `usernames`..
I just tested with the username `תובתסוד` and it worked.

I'll close this for now. Please reopen it if you still can't find a user by their **username**, ok?
