### ISSUE TITLE
[5.0.1] Unable to access General, Messages and other settings from Chrome

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat#26458]
### Description:

Access to the General settings (Administration >> Settings >> General) and Messages sections (Administration >> Settings >> Messages) are inaccessible, the access buttons are not visible in the administration panel.

If you try to access the `https://my.rocket.net/admin/settings/general` link directly you can see that the target exists, however you get a gray screen and multiple errors in the browser console.

![image](https://user-images.githubusercontent.com/35962168/182528233-403e149a-2b73-4659-8c3b-523ce5bc0d4c.png)

I did not verify this behavior in 5.0.0 but it is very likely that it exists, if someone can confirm it would also be useful.
### Steps to reproduce:

1.  _Administration >> Settings >> General_ and _Administration >> Settings >> General_
2. 
### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.1
- Operating System: Ubuntu 20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v14.18.3
- MongoDB Version: 5.0.10

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 103.0.5060.134
- Operating System: Windows

### Additional context

In Rocket Electron, Firefox and Edge there are no such errors.

**Comment by ankar84** [comment]
Actually I don't have such problem on my test env with 5.0.1
![image](https://user-images.githubusercontent.com/4023037/182532370-31288a89-a2d7-4f8e-82e9-f30f93e7e8b9.png)
![image](https://user-images.githubusercontent.com/4023037/182532407-710700ed-4c60-4588-9bba-cdb2d1b08356.png)
![image](https://user-images.githubusercontent.com/4023037/182532439-3adef5e8-22f7-46aa-8d59-e49f4b4cf2cb.png)

But I know for sure, that sometimes some of Settings areas don't appears for some reason. Refresh usually helps.

**Comment by aleadco** [comment]
@ankar84  Sure enough, I had to clear all cache and cookies to resolve the issue. Thank you
