### ISSUE TITLE
👍 emoji parsed as a tel link when using the `:+1:` alias

### ISSUE THREAD

**Issue by NathanBnm** [RocketChat/Rocket.Chat#26469]
### Description:

When using the `:+1:`  alias for the 👍  emoji it results to the following tel link `//tel:1` which opens in the browser when clicking on it

### Steps to reproduce:

1. Type `:+1:` in the message input

### Expected behavior:

The 👍 emoji should display properly

### Actual behavior:

<img width="279" alt="Capture d’écran 2022-08-04 à 10 36 27" src="https://user-images.githubusercontent.com/45366162/182802656-5d39b8be-06be-4702-808f-3de8494b417f.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 5

### Client Setup Information

- Desktop App or Browser Version: Electron / Web (Chrome)
- Operating System: OSX

**Comment by DaVukovic** [comment]
We can confirm this issue. Deactivating the "autlinker" for telephone numbers doesn´t solve this problem. 

Please, dear RC-Team, in case you need something to debug this issue, let us know which other infos you might need.

**Comment by hugocostadev** [comment]
It was already fixed and there is already a Release Candidate. Soon we will be released the official Release.
