### ISSUE TITLE
Error notification in integrations shows "object Object"

### ISSUE THREAD

**Issue by slhck** [RocketChat/Rocket.Chat#26474]
### Description:

Error messages when adding integrations show only `[object Object]`

### Steps to reproduce:

1. Add a new integration
2. Enter a wrong (non-existing) username or channel name
3. Press save

### Expected behavior:

An error should be show in the error box.

### Actual behavior:

The error box shows `[object Object]`.

![ ](https://user-images.githubusercontent.com/582444/182887966-67fc7d51-0bc2-4d10-82f9-fc4753bc2304.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0
- Operating System: any
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.9 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: both affected
- Operating System: macOS 11

### Additional context

The console shows the correct error:

![SCR-20220804-l19](https://user-images.githubusercontent.com/582444/182888121-7f59f836-7f9a-4d08-a798-e13af7eda6ea.png)

**Comment by ydc-poi** [comment]
根本的な解決方法ではないですが、APIを叩くことで回避できます。
It is not a fundamental solution, but it can be avoided by tapping the API.

https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/integration-endpoints/create

**Comment by debdutdeb** [comment]
Fixed in https://github.com/RocketChat/Rocket.Chat/pull/26320
