### ISSUE TITLE
Short URL not recognized and converted to emoji

### ISSUE THREAD

**Issue by grthr** [RocketChat/Rocket.Chat#26475]
Description:
When pasting an short URL like https://g.co/meet/something, it is not rendered as Link and not clickable.
Even using it inside Markdown Link style does not work.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/5175544/182888595-0744ddb3-b314-4a53-a150-e7aecaf74c08.png">

Steps to reproduce:
Type https://g.co/meet/something in the message input
Expected behavior:
A link should be created to the given URL

Actual behavior:
An emoji is rendered from the :/ and no link is created.

Server Setup Information:
Version of Rocket.Chat Server: 5.0.1
Deployment Method: docker
Number of Running Instances: 1
MongoDB Version: 4.2
Client Setup Information
Desktop App or Browser Version: Electron / Web (Chrome)
Operating System: Windows

**Comment by grthr** [comment]
This was working fine in 4.8.1

**Comment by Akkowicz** [comment]
Facing the same issue, it's quite annoying.

**Comment by fuchsundvogel** [comment]
Super annoying. We had to downgrade the server to an older version because we could not send file paths anymore without them getting destroyed by emojis.

**Comment by grthr** [comment]
Just found out that the behavior is different in Threads. There it works as expected. Maybe this helps finding the cause of the issue.

**Comment by saschafoerster** [comment]
<img width="226" alt="Bildschirmfoto 2022-08-15 um 09 14 50" src="https://user-images.githubusercontent.com/1153741/184592433-9405026a-5cd1-4be8-a890-de46e6f7d29c.png">

Same issue with "10:30" > 0:3 get's translated into an emoji.

**Comment by Vaarlion** [comment]
hi :)
We just updated to the latest version, and sure thing short url aren't translated to URL.

**Comment by Vaarlion** [comment]
So, in Settings, Account, Default User Preferences, you have a global switch to revert to the old message template.
![image](https://user-images.githubusercontent.com/59558433/185921181-5fd6f3ca-4f65-4509-b928-bcf01305f0c0.png)

You can also do this for your user only in My account, Preferences , Global

**Comment by kekefreedog** [comment]
Same problem for me with url which doesn't have `.com` or dot something...
![image](https://user-images.githubusercontent.com/70959083/185956419-483ce199-0e3f-4fbe-b33c-09bbea27e31a.png)

**Comment by hugocostadev** [comment]
Fixed by: https://github.com/RocketChat/fuselage/pull/800/files
