### ISSUE TITLE
Autolinker autolinks anything with a dot in it

### ISSUE THREAD

**Issue by Montg0mery** [RocketChat/Rocket.Chat#26476]
### Description:

Any text in a chat message with a dot in it, such as "System.exit()" will get autolinked by Rocket Chat, even though the default settings imply that it should only autolink scheme URLs, www URLs, TLD URLs, emails, and phone numbers. "System.exit" is none of those, for example.

### Steps to reproduce:

1. Type asdf.asdf into a chat message and send
2. Observe that it has been autolinked by Rocket Chat

### Expected behavior:

No autolink except for text which matches one of the above-mentioned settings (e.g. with a scheme, or with www, or with a well-known TLD).

### Actual behavior:

Anything with a dot gets autolinked, even things that are clearly not links.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.1
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: 

### Additional context

Screenshot:

![image](https://user-images.githubusercontent.com/88062966/182888751-4a278576-3055-409e-8ff3-02a09d4f8934.png)

**Comment by kanhaiya04** [comment]
Hi @Montg0mery 
I have gone through the issue and I am also facing it.
Can Someone guide me how to proceed as I am new to the organisation.

**Comment by hugocostadev** [comment]
Hi, @Montg0mery we are investigating a good fix for that. 

Since there are a lot of valid TLD (Top Layer Domains) like `.com` `.net`, `.chat`, and thousands of others it is impossible to guarantee that the written URL is a valid one, but we are studying a good fix and we are working to [fix the AutoLinker feature](https://github.com/RocketChat/Rocket.Chat/issues/27135) to make the text formatting better

**Comment by Montg0mery** [comment]
> Hi, @Montg0mery we are investigating a good fix for that.
> 
> Since there are a lot of valid TLD (Top Layer Domains) like `.com` `.net`, `.chat`, and thousands of others it is impossible to guarantee that the written URL is a valid one, but we are studying a good fix to make the text formatting better

You can get the official list of TLDs from IANA (https://www.iana.org/domains/root/db) and not auto-link unless the text ends in one of those, or fix Rocket.Chat so that auto-linking can be disabled for links which don't start with with a valid scheme such as `http://` or `https://`.

Ideally both, so that auto-linking is better by default, but can also be turned off for domains without a scheme.

**Comment by hugocostadev** [comment]
Hi @Montg0mery we already tried to check for valid TLDs, but this would bring several other issues and increase the time for parsing messages. 
Also, checking for thousands of valid TLDs or limiting just to HTTP protocol would not be ideal for the majority of our users ...

**Comment by Montg0mery** [comment]
> Hi @Montg0mery we already tried to check for valid TLDs, but this would bring several other issues and increase the time for parsing messages. Also, checking for thousands of valid TLDs or limiting just to HTTP protocol would not be ideal for the majority of our users ...

@hugocostadev: OK, I can understand not wanting to check for every possible TLD (although with a hashmap that would be fast), but I don't understand what you mean when you say that a majority of users would be annoyed if scheme-less autolinking went away.

Surely most people are not looking for things like `str.length` to be autolinked into a hyperlink, or if they accidentally miss a space off the end of sentence like "... until the end of today.Tomorrow there will be..." which will autolink "today.Tomorrow" into a hyperlink.

The vast majority of links that the majority of users paste into Rocket.Chat are going to start with a scheme, such as `https://`.

Please can we at least have an option (off by default if you want!) to not autolink scheme-less text just because it happens to have one dot in the middle?

**Comment by kvbe-schiemat** [comment]
Hi @hugocostadev ,

thank you very much for your work! Will there be a similar feature or workaround for this problem when the autolink feature is removed in the future? Maybe I have misunderstood something :) 

Thanks
Tim

**Comment by hugocostadev** [comment]
Hi @Montg0mery and @kvbe-schiemat ! I understood your point and concerns and we will discuss them internally. Thanks a lot for your contribution.

**Comment by upengareri** [comment]
This issue seems to be really annoying. In my case when I use URL that has single character in the sub-domain then it fails to link correctly e.g https://some.website/.h.ey.com 
<img width="350" alt="rc" src="https://user-images.githubusercontent.com/3920237/210827959-ee76a6fa-e465-469d-82ae-65a25b47f40f.png">

But when you open that message as thread then it renders it properly.

I hope this issue gets a higher priority.

**Comment by hugocostadev** [comment]
I'm working on this and soon we will fix it, I'll bring updates soon

**Comment by Matt-something** [comment]
We have the opposite but also vexing issue that https://singleword/ will not be recognised as a hyperlink.
The hyperlinking is very very broken
