### ISSUE TITLE
v5.0.0 - Display Roles setting is now ignored, the same for Disable Embed for Users (Enterprise)

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat#26489]
### Description:
I had Display Roles and Disable Embed for Users turned  off since I remember, but after we upgraded to v5.0.0, those settings are now ignored.

### Steps to reproduce:
1. Turn off Display Roles in admin panel.
2. Disable Embed for Users in admin panel.

### Expected behavior:
1. Do not show roles in the chat.
![181741270-66caf3e5-70f8-4bcd-bb40-c5c2de656cdd](https://user-images.githubusercontent.com/25570106/183087997-681c182a-cf7e-4c53-b445-dd962ab0e48f.png)

2. Do not show url previews (og tags) for certain users.
![181741265-30b989e7-0b27-410d-85a0-5ea3331c5c86](https://user-images.githubusercontent.com/25570106/183088018-f80e86de-b137-49a6-a89f-20c1df311e0e.png)

### Actual behavior:
1. Roles are shown in the chat.
![b5curls4H](https://user-images.githubusercontent.com/25570106/183037478-d0fcc08a-a838-4b70-92da-2157954b1d07.png)

2. Url previews are displayed in the chat.
![i0twats5p](https://user-images.githubusercontent.com/25570106/183035358-567cdf29-ed65-4ebd-9a1c-ec3b62cc1491.png)

### Server Setup Information:
* License: Enterprise
* Version of Rocket.Chat Server: 5.0.0
* Operating System:  Ubuntu 18.04
* Deployment Method: Docker image
* Number of Running Instances: 1
* DB Replicaset Oplog: rs0
* NodeJS Version: v14.19.3

* MongoDB Version: 4.4.15 / wiredTiger (oplog Enabled)

### Client Setup Information
- Desktop App or Browser Version: Desktop App, 3.8.7

- Operating System: Windows 11

### Additional context
 - No additional context.

### Relevant logs:
```
No additional logs.
```

**Comment by kanhaiya04** [comment]
Hi
Can someone guide me how to proceed for this issue as I am new to the organisation.

**Comment by teach404W** [comment]
+1 same issue on 5.0.2

**Comment by xcpdq** [comment]
Same issue on version 5.0.2. Guys, please release a fix for this. Thank you.

**Comment by juhanix** [comment]
same here with community edition

Deployment Version 5.0.0
Apps Engine Version 1.33.0
Node Version v14.19.3
Database Migration 279 (19. August 2022 12:06)
MongoDB 4.4.15 / wiredTiger (oplog Enabled)
Commit Details HEAD: (59cae1210)

**Comment by csharpen** [comment]
Display Roles still ignored on Community Edition 5.0.4.

**Comment by dudanogueira** [comment]
Hi! There is a PR ready for that:
https://github.com/RocketChat/Rocket.Chat/pull/26601

It should be merged, hopefully for 5.1.0

**Comment by dudanogueira** [comment]
Ok, it's now planned for 5.2.0 release:

https://github.com/RocketChat/Rocket.Chat/milestone/301

**Comment by dudanogueira** [comment]
@urosino I will close this now, as I can't related this issue to the PR, that was merged already. 

Please, if possible, test it upon release, and if not fixed, repoen :)

Thanks!
