### ISSUE TITLE
RTL issue in message display

### ISSUE THREAD

**Issue by gitd3v** [RocketChat/Rocket.Chat#26499]
### Description:
after upgrade to 5.0.1, all messages typed in RTL and have mixed persian/english words does not show correctly in desktop app or browser, mobile app is not affected
setting "Use legacy message template", temporarily fixes the issue.

### Expected behavior:

show messages correctly
![Screenshot_20220806_094400](https://user-images.githubusercontent.com/110710266/183235173-50697276-43f6-4036-91c2-3ea2a8bb3230.png)

### Actual behavior:
words is not in the right places
![Screenshot_20220806_094255](https://user-images.githubusercontent.com/110710266/183235144-b361c07b-cc5a-4119-b190-86c6daab2215.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.1

### Client Setup Information

- Desktop App or Browser Version: latest
- Operating System: linux

**Comment by isaacvonaaron** [comment]
Same issue here. If I manipulate the <DIV> wrapping the text, Electron gets it right. It even aligns the text to right.
While typing text:
![image](https://user-images.githubusercontent.com/10384285/184534153-2fd6a6ac-5454-42aa-9b0a-5c6c9f9c442a.png)
After sending it
![image](https://user-images.githubusercontent.com/10384285/184534165-c59dc572-1f63-489e-aa28-fde50439a2b5.png)

**Comment by isaacvonaaron** [comment]
I created a temporary hack
Admin-> Settings -> Layout -> Custom Script for Logged In Users

```
window.setInterval(
  function() { 
    $('div.rcx-box').attr('dir', 'auto'); 
  },
  1000
);

```

**Comment by bahmanjafari** [comment]
In 5.0.3 still problem is exist

**Comment by pouyadarabi** [comment]
Thanks to @isaacvonaaron

I created an optimized way using Mutation Observer


Custom Script:

```

function setAutoDir(){
    $("div.rcx-message-container[dir!='auto'],div.rcx-message-body[dir!='auto']").attr('dir', 'auto'); 
    $("textarea.rc-message-box__textarea[dir!='auto']").attr('dir', 'auto'); 
}
setAutoDir();
var elementCount = $('.rcx-message-body').length;
var observer = new MutationObserver(function(mutations) {
   var newCount = $('.rcx-message-body').length;
   if (newCount != elementCount) {
        elementCount = newCount;
        setAutoDir();
    }
});
observer.observe(document, {attributes: false, childList: true, characterData: false, subtree:true});
```
This will set `dir=auto` for messages and input box.

----


If you want to keep messages in left and just fixing RTL issue, add this

Custom CSS:

```
.rcx-message-body {
  text-align: left;
}
```

**Comment by molaeiali** [comment]
Same issue on 3.8.12 on Linux

I think this and https://github.com/RocketChat/Rocket.Chat/issues/26857 are issues related to https://github.com/RocketChat/Rocket.Chat.Electron project though, will open an issue there, mentioning these issues here

**Comment by jeanfbrito** [comment]
> Same issue on 3.8.12 on Linux
> 
> I think this and #26857 are issues related to https://github.com/RocketChat/Rocket.Chat.Electron project though, will open an issue there, mentioning these issues here

Just to tell you that this is a server issue and not an Electron one, that's why I closed the issue there. Ok?
We are aware of this already @debdutdeb ?

**Comment by ahmadidev** [comment]
Thanks, @isaacvonaaron, and @pouyadarabi for the workarounds. Is there a plan to include this fix in upcoming releases?

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

![image](https://user-images.githubusercontent.com/20212776/230363689-9a954f92-fd10-4c90-92a2-aeff20e0a0c7.png)


[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by armanexplorer** [comment]
In my case with RocketChat Server 6.11.1, the code @pouyadarabi provided did not work fully and I got some errors in the console that say `Uncaught ReferenceError: $ is not defined`, and also the inputs with `textarea.rc-message-box__textarea` selector did not update.
So, I rewrote the code in pure JS with a focus on `textarea.rc-message-box__textarea` (because in this version of RocketChat Server other inputs were RTL-friendly) and it finally worked for me:
```js
(function() {
    // Function to set dir="auto" for textareas that don't have it
    function setAutoDir() {
        var textareas = document.querySelectorAll("textarea.rc-message-box__textarea:not([dir='auto'])");
        textareas.forEach(function(textarea) {
            textarea.setAttribute('dir', 'auto');
        });
    }

    // Function to initialize and observe the textareas
    function init() {
        var elementCount = document.querySelectorAll('textarea.rc-message-box__textarea').length;
        if (elementCount > 0) {
            setAutoDir();

            // MutationObserver to detect changes in the DOM
            var observer = new MutationObserver(function(mutations) {
                var newCount = document.querySelectorAll('textarea.rc-message-box__textarea').length;
                if (newCount !== elementCount) {
                    elementCount = newCount;
                    setAutoDir();
                }
            });

            // Start observing the document for changes in the child list and subtree
            observer.observe(document, { attributes: false, childList: true, characterData: false, subtree: true });

            // Clear the interval once the elements have been initialized
            clearInterval(checkForTextareas);
        }
    }

    // Check every 500ms to see if the textareas have been added to the DOM
    var checkForTextareas = setInterval(init, 500);
})();

```

**Comment by morteza1131** [comment]
I fix it with this custom css

```
/* Force bidirectional text handling in message input */
.rc-message-box__textarea,
.js-input-message,
textarea[name="msg"],
.message-box-container textarea {
  direction: auto !important;
  unicode-bidi: plaintext !important;
}
```
