### ISSUE TITLE
iOS Client(APP) cannot play audio and video

### ISSUE THREAD

**Issue by yatounoneko** [RocketChat/Rocket.Chat#26500]
### Description: 
iOS App cannot play audio and video

### Steps to reproduce: 

1. Upload or record any audio or video
2. Send the messages
3. In iOS APP receive file and play

### Expected behavior: 
Playable on all clients and web

### Actual behavior:
Can only be played on Android and PC clients or website

### Server Setup Information: 

- Version of Rocket.Chat Server: 5.0.1 -> 5.0.2 now problem persist
- Operating System: Debain 11
- Deployment Method: Rocketchatctl
- Number of Running Instances: 1
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.10
- MongoDB Engine: wiredTiger
- Platform: linux
- Process Port: 3000
- Site URL: https://website.com (Nginx SSL reverse proxy)
- ReplicaSet OpLog: Enabled

### Client Setup Information

- Desktop App or Browser Version: 
	- iOS: 4.29.0.34197
	- Android: 4.29.0.34199
	- PC: 3.8.7
- Operating System: 
	- iOS: 15.3.1
	- Android: 12
	- PC: Windows 11 22H2

### Additional context
I tried to iPhone 7 plus and iPhone 13 was problem the same.

### Relevant logs:
No error messages

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4350

**Comment by yatounoneko** [comment]
Waiting your fix, many thanks.

**Comment by yatounoneko** [comment]
yes... 4.30 audio is fixed but video problem persist.

![IMG-20220928-WA0000](https://user-images.githubusercontent.com/22129910/192661042-6f284eb3-5511-4a56-86ca-446d4e39ce48.jpg)
