### ISSUE TITLE
Mobile App Showing Plain Text Only

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2650]
Our Rocketchat version is 0.23 with the app version 2.2.2.

When we connect to our RC server from the mobile app we are getting plain text only from both iOS and Android.

I'm not sure if this has to do with some nginx configuration. The server we are accessing ends in .com and it is reverse proxying into our backend that ends in .us. Everything works in the browser fine. I noticed someone in #support has had a similar issue but I didn't see a solution.

Is there a way to see what the requests look like coming from the mobile app?

![e9e96c28-f286-11e5-960b-9dc4d6acae7f](https://cloud.githubusercontent.com/assets/8405384/14054231/9bd25a80-f2a5-11e5-8dc1-6ad297cde130.PNG)

**Comment by TheReal1604** [comment]
Got this issue some days ago, after updating rocket.chat with the latest commits all seems fine. Think some update did break it, but it's fixed for now. 

Anyone have better information around this issue?

**Comment by engelgabriel** [comment]
This should be fixed in the release 0.24.0 shipping today.
Please reopen this issue otherwise.
