### ISSUE TITLE
Pls HELP me out

### ISSUE THREAD

**Issue by sanjayk0508** [RocketChat/Rocket.Chat#26512]
i cloned the repo in my vscode but there is no proper guidance on what commands to be passed, so i can run it on my local host.

**Comment by florisvangeel** [comment]
you might be looking for [this](https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup)

**Comment by sanjayk0508** [comment]
Heyy @florisvangeel, Thank you for your help

**Comment by dudanogueira** [comment]
@sanjayk0508 also check our Get Started channel on how to deep dive into our codebase and hang out with other contributors: https://open.rocket.chat/channel/how-to-get-started
