### ISSUE TITLE
Silent mention

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#2651]
So it would be nice to be able to mention someone with out notifying them.  Kind of like a polite mention.

Think for example you are referring to someone in conversation but you don't really need to notify them about it.

Example: `this feature was developed by @rodrigo and @diego`  I don't want to alert them and drag them out of what they are doing.  I just want to credit them / point to the actual user.

So i'm thinking maybe something like: `this feature was developed by ~rodrigo and ~diego` ?

They wouldn't receive a notification or sound of a mention.  They just would simply have their name highlighted, and would be treated mostly the same in every other way as a mention.  It just does not require their attention.

Not sure about the syntax.  But I think this would be very useful.

**Comment by dariosusman** [comment]
Can't this be a choice? I'm running 0.57.1. Highlights are marked, but not notified, when the setting clearly states "To be notified when someone mentions a word of phrase..."

**Comment by geekgonecrazy** [comment]
Closing in favor of #9017
