### ISSUE TITLE
[Request] - rocket chat to rocket chat communications.

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2653]
Another request from your favourite nuisance!

It would be amazing if channels could be shared between instances.

For example, I would really like to subscribe to the demo.rocket.chat/developer channel on and chit chat with gabriel, however to do so I need to go open another tab and open another RC instance, and join that channel. Would it not be fantastic to just add  that specific channel to my instance instead to see what's happening there.

I can only imagine what programing effort needs to be done in order to accomplish the necessary security.

 I mean technically it is possible already utilizing webhooks, if I would host two rocket chat servers I could easily cross communicate, but to do so with a sercer i dont host Its complicated. A simple subscription button that would be amazing.

**Comment by capensisma** [comment]
well this can be easily done with the Current APi, just allow people to get an API key so they can connect to their account from the instance and chat on other channels...

or have a admin option to add other Rocket.Chat Instance ...

**Comment by bott0r** [comment]
This would also be a solution to have decentralized servers :dancers:

**Comment by TheReal1604** [comment]
+1 Need this.

**Comment by engelgabriel** [comment]
We believe this is one of the most important features we need to implement.
This is planned on https://github.com/RocketChat/Rocket.Chat/issues/601
