### ISSUE TITLE
Running rocketchat from a subfolder

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#2655]
Your Rocket.Chat version: (.23)

When running rocket chat from a subfolder http://www.site.com/chat/

The problem is that:
1. Images
2. Avatar
3. Assets

Are loaded from document_root as /images /avatar and /assets.

To solve this problem I had to give the following commands:
>find ./ -type f -readable -writable -exec sed -i "s\/images/\/chat/images/\g" {} \;
>find ./ -type f -readable -writable -exec sed -i "s\/assets/\/chat/assets/\g" {} \;

Since 
ROOT_URL=https://www.site.com/chat

the system should have loaded images and assets from chat folder.

Any idea where i should be making this change in the source code ?

**Comment by lunitic** [comment]
Planning to do the same. Did you solved it within rocket chat?

**Comment by graywolf336** [comment]
#2624 is an attempt to get this going.

**Comment by engelgabriel** [comment]
Please try the develop branch when #2624 get merged today.

**Comment by rodrigok** [comment]
Our develop branch has this option, please reopen this issue if the problem persists.

**Comment by lunitic** [comment]
I just tried this in 0.25 and I cant get it to work.. I have set  my ROOT_URL=https://localhost:3000/chat 

Getting the following errors in the console.. The system is a totaly clean install of rocket.chat 0.25

![image](https://cloud.githubusercontent.com/assets/17207375/14403117/cae82cb2-fe4b-11e5-9ae7-35843eeed300.png)

**Comment by lunitic** [comment]
ping @rodrigok does not seem to work...

**Comment by rodrigok** [comment]
@lunitic can you test with our latest develop version?

**Comment by engelgabriel** [comment]
@lunitic you can't use `https` unless you have a reverse proxy on your setup.

**Comment by lunitic** [comment]
I stripped down the nginx configuration to minimal...  and still i get the sock.js error

`server {
    listen 82;
    server_name www.example.com;
    error_log /var/log/nginx/rocketchat.access.log;

    location / {
        proxy_pass http://www.example.com/;
       
    }

     location /chat/ {
        proxy_pass http://localhost:3000/chat/;
        
    }

}`

**Comment by engelgabriel** [comment]
it is in the wrong order... the first `location` will catch the request.

You can't use `ROOT_URL=https://localhost:3000/chat`

The `HTTPS` only exists in your port `82`

So you can either have

`ROOT_URL=http://localhost:3000/chat`

or 

`ROOT_URL=https://localhost:82/chat`

**Comment by lunitic** [comment]
@engelgabriel Will make totally new files for testing and comeback.. Pretty sure i tested every single combinations..

**Comment by lunitic** [comment]
@engelgabriel My problem seems to be with NGINX and not the RC:. If i takeaway the NGINX then everyworks.. Must be something with the location parameters.. I just disable the nginx front end and then www.domain.com/chat works..

**Comment by dangkiena3** [comment]
I use a nginx Reverse Proxy and add Rocket Chat server like:

`location /chat {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect   off;
            proxy_pass       http://10.0.25.137:3000; 
        }
`

But when I access https://mydomain.com/chat, a white screen appear:

Please help me.

Thank you!
