### ISSUE TITLE
URL is rendered with emoji :/

### ISSUE THREAD

**Issue by xl32** [RocketChat/Rocket.Chat#26555]
### Description:

Some URLs are displayed with an emoji :/ inside

### Steps to reproduce:

1. Go to any channel
2. Write a message "https://i.example.com/"
3. Observe a result

### Expected behavior:

See URL https://i.example.com/ with an optional preview

### Actual behavior:

Emoji is posted as a part of URL
![image](https://user-images.githubusercontent.com/1729594/184350803-bafd658f-7f88-49ef-b08f-27bfbc69fafa.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System: Rocky Linux 8
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome 104
- Operating System: Windows

**Comment by omgold** [comment]
Apparently there is something wrong with the url syntax detection.

in the OP example, it seems to fail because of the `i.` (a single character hostname). it works for me when replaced with `.ix`.

What also fails for me is a fqdn without a `.`, like `http://example/test`.

**Comment by kekefreedog** [comment]
Same problem for me with url which doesn't have `.com` or dot something...
![image](https://user-images.githubusercontent.com/70959083/185956419-483ce199-0e3f-4fbe-b33c-09bbea27e31a.png)

**Comment by chotaire** [comment]
The URL detection is such a major nuisance that this (and link previews / image display) is what keeps me from updating to 5.1.0. Emojis can't even be disabled systemwide. 

And as for link previews / image display: Previously, on 5.0 you would simply click the image (it has a magnifying glass icon on mouse-over) and it would properly display. On 5.1.0 the same magnifying glass is shown, but when clicking it, absolutely nothing happens.

Fixing these things people work with every day need to be prioritized really. Unfortunately 5.1.0 has been a huge step backwards for the user and taken much of the trust I had in upgrading this software.

**Comment by kiwi-oss** [comment]
[Here's a workaround](https://github.com/RocketChat/Rocket.Chat/issues/26475#issuecomment-1222291767)

**Comment by hugocostadev** [comment]
It is already fixed by https://github.com/RocketChat/fuselage/pull/800
