### ISSUE TITLE
Missing proxy settings for fetching external pages

### ISSUE THREAD

**Issue by netdevfighter** [RocketChat/Rocket.Chat#2657]
We use the rocket chat on an internal network without direct internet access (is blocked by firewall) but we can use a proxy for access it (only for external networks/pages).

Is it possible to implement proxy (external destination) and no proxy (internal destination)? 

That would be pretty cool for link previews (for example).

**Comment by engelgabriel** [comment]
I believe this depends on https://github.com/RocketChat/Rocket.Chat/pull/2555

**Comment by zbyte** [comment]
same issue

**Comment by zbyte** [comment]
Will it ever been done?

**Comment by Abraka** [comment]
Any progress on this?

**Comment by marceloschmidt** [comment]
I'm not sure I understand the request. Are you interested in a server-side proxy? Because afaict, image and link preview happens on the server side, so a proxy on the client-side wouldn't make much sense.

**Comment by Abraka** [comment]
No, we just simply want a option in administration interface of rocketchat... something like: http(s)proxy://"corporate.proxy.com". Description: Use this option for links and content-video preview if your installation cannot reach internet directly.
Do not confuse this for system wide option of http_proxy which could cause internals components of rocketchat to communicate between each other through this proxy, which is very unwelome scenario.

**Comment by marthydavid** [comment]
Hi
I've just found this PR #11124
Is it helpful?

**Comment by Abraka** [comment]
well, function description looks similar...what scares me here is that request is over year old!

**Comment by idl0r** [comment]
That'd be really cool. We'd like to use a proxy.

**Comment by fcoppolani** [comment]
Yes still need it, keep it alive !

**Comment by marthydavid** [comment]
Hi!
What do you think about this?
https://github.com/RocketChat/Rocket.Chat/compare/develop...marthydavid:2657-RocketChat-Proxy-Support

**Comment by Paulpatou** [comment]
No news ?

**Comment by Paulpatou** [comment]
??

**Comment by Weuxel** [comment]
After Log4Shell, security has tightened. Internet access via proxy is mandatory now.
Please provide a proxy setting

**Comment by bellegarde-c** [comment]
Was working previously but breaks in 4.4.0 :(

```
[Unit]
Description=The Rocket.Chat server
After=network.target mongod.service
[Service]
ExecStartPre=/bin/sleep 30
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=http_proxy=http://srv-proxy-1.********************:3128 https_proxy=http://srv-proxy-1.********************:3128 MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=https://rocket****************** PORT=3001
[Install]
WantedBy=multi-user.target
```

Any idea ?
