### ISSUE TITLE
Avatars buggy in 5.0.3

### ISSUE THREAD

**Issue by sketch242** [RocketChat/Rocket.Chat#26606]
### Description:

After updating from 4.8.2 to 5.0.3, there seems to be a lot of buggy behavior around avatars.

Sequence of events and results of testing:

1. In 4.8.2, i had a default avatar with my first name letter with a green background.
2. Upgraded to 5.0.3
     a.  My avatar changed to have a brown background in desktop/browser.  
     b.  Mobile still shows the green background on all chats.  It does show the brown background in my profile.
4. I uploaded an image for a new avatar in Chrome.  
      a. This resulted in immediate changes on my screen, but the user I was chatting with did not see them in the chat.  Changing chats and restarting their desktop client did not cause it to change.
      b. I opened RC in Firefox and I do see the new avatar everywhere.
      c. The other user does see the new avatar when they open my profile.
      d.  Confirmed same behavior with a second user.
      e.  Looked at RC on Android, and I still see the old green-background avatar for my user's chats.
      f.  I still see the brown-background avatar in my user settings on android as well.
5.  Uploaded a second image as a new avatar via Android
      a.  I see the avatar change immediately in my chats in both Chrome and Firefox.
      b.  Users confirm they see no changes.
      c.  Exit settings on android and I still see my old green avatar icon.  
      d.  Go back into user settings on android and I still see the old brown avatar icon.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System: Rocky Linux 8
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.10 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 104.0.5112.79, Firefox 103.0.2 / Rocket.Chat Android 4.29.0
- Operating System: macOS 11.6.8 / Android 13

I don't see any errors generated in the Rocket.Chat server log, or by the browser.

**Comment by maciejpankanin** [comment]
I don't know if it is same issue or not but for me after upgrade from 4.8.X to 5.0.3 all of my integrations have default rocket.cat avatar.

**Comment by ggazzo** [comment]
a lot of "issues" here
- yes, we changed the default colors, to a more inclusive palette (in terms of accessibility), so if you have no avatar uploaded , is normal facing a different one
- Browser caches the avatar and sometimes it takes a few to invalidate, no relation with the server version
- mobile caches the avatar's this is a bug/feature and the cache time is almost infinite, this is a little bit annoying, but there is no relation with the server version
