### ISSUE TITLE
Some clients can't log in with Custom OAuth in 5.0.3

### ISSUE THREAD

**Issue by sketch242** [RocketChat/Rocket.Chat#26613]
### Description:

After updating from 4.8.2 to 5.0.3, some Electron apps are no longer able to log in via custom OAuth.  We're using a custom OAuth using the pop-up method against Office 365.  

After the server was updated, existing user sessions continue to work fine.  However, if a user logs out and attempts to log back in, the login fails.  The error "No matching login attempt found" appears _before_ the Office365 authentication pop-up even appears.  Reloading after successfully authenticating, after which it no longer pops up an auth window, does not help.  It still gives the same error.

From the server log (see below), it appears that the OAuth authentication is working correctly, as I get my name/email address/etc in the result.  Just that the client it isn't getting properly matched to the client somehow.

Fails on:  Mac and Linux desktop electron app 3.8.7

Works on: Windows desktop electron app 3.8.7, Chrome (104.0.5112.7), Firefox (103.0.2), Android app (4.29.0), iOS App (reported by users, should be the latest version)

I'm not sure if this is a bug with the Electron app or the server, but it appears to have at least been triggered by the server upgrade, so I'm filing it here.

### Steps to reproduce:

1. Log out, remove server, or reset app data in the electron app.
2. Attempt to login.

### Expected behavior:

1. Log out, remove server, or reset app data in the electron app.
2. Attempt to login.
3. Login is successful.

### Actual behavior:

1. Log out, remove server, or reset app data in the electron app.
2. Attempt to login.
3. Client returns the error "No matching login attempt found"

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System: Rocky Linux 8
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.10 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop app version 3.8.7
- Operating System: macOS 11.6.8, Fedora Linux 36

### Relevant logs:

Redacted server logs:

```
Aug 18 18:01:56 <myserver> podman[264728]: {"level":30,"time":"2022-08-18T18:01:56.142Z","pid":1,"hostname":"<myserver>","name":"System","msg":"Failed login detected - Username[unknown] ClientAddress[<WW.XX.YY.ZZ>] ForwardedFor[<WW.XX.YY.ZZ>] XRealIp[undefined] UserAgent[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.8.7 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36]"}
Aug 18 18:01:57 <myserver> podman[264728]: {"level":20,"time":"2022-08-18T18:01:57.328Z","pid":1,"hostname":"<myserver>","name":"CustomOAuth","msg":"Identity response","data":{"aio":"<long string>","amr":"[\"pwd\",\"mfa\"]","family_name":"<Last>","given_name":"<First>","ipaddr":"WW.XX.YY.ZZ","name":"First Last","oid":"<GUID>","rh":"0.<long string>.","sub":"<long string>","tid":"<GUID>","unique_name":"<myemail>","upn":"<myemail>","uti":"<string>","ver":"1.0"}}
```

**Comment by ankar84** [comment]
Could be related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/2466

**Comment by sketch242** [comment]
Interesting, could be.  

I finally got a suggestion from enterprise support today, and they suggested changing the OAuth Login Style from Popup to Redirect.  That appears to have have fixed it for me.  I seem to recall that we were using popup because, on some older clients (maybe mobile), Redirect didn't work with O365's login flow.  However, it appears to work fine on all of the current clients.
