### ISSUE TITLE
How to made the messages readed on api?

### ISSUE THREAD

**Issue by lamjack** [RocketChat/Rocket.Chat#2661]
Your Rocket.Chat version: 0.5

API Version: 0.1

I get the user unread messages list on api, but how to mark then readed? because i implement this function on my website.

Could make it readed using rest api?

**Comment by engelgabriel** [comment]
Hi, due to limited resources, we can only support users that are keeping the server up-to-date. Can you upgrade to the current version?

**Comment by geekgonecrazy** [comment]
Please update and let us know if you still have issues.  Also feel free to join the [#support](https://demo.rocket.chat/channel/support) channel for additional help.
