### ISSUE TITLE
How i can remove smiles from txt messages ?

### ISSUE THREAD

**Issue by bobfh** [RocketChat/Rocket.Chat#26624]
### Description:
Smiles in txt messages

### Steps to reproduce:

1.  ![изображение](https://user-images.githubusercontent.com/88323396/185675895-981ce933-3d3c-4c8e-b5ab-f275981dcda3.png)

### Expected behavior:

Text only - without graph

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System:  Debian 10
- Deployment Method: tar
- Number of Running Instances: 1

**Comment by urosino** [comment]
We share the same problem.

![CautiousSeaurchinSaturday](https://user-images.githubusercontent.com/25570106/185731436-86919260-7b44-4fc3-b85b-dfcb8427502b.png)

**Comment by krenuser** [comment]
Escape % character:
```Disk space is critically low (used 90\%)```

**Comment by kekefreedog** [comment]
Same problem for me with url which doesn't have `.com` or dot something...
![image](https://user-images.githubusercontent.com/70959083/185956419-483ce199-0e3f-4fbe-b33c-09bbea27e31a.png)

**Comment by chotaire** [comment]
How you can remove smiles from text messages:

`Administration -> Settings -> Accounts -> Default User Preferences -> [ ] Use Emojis`

Yes, this also works for existing accounts if they have not altered their personal setting.

**Comment by hugocostadev** [comment]
Fixed on [Release 5.1.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.1.0) But I recommend keeping the product updated with the last stable release.
