### ISSUE TITLE
Legacy message template is still used inside threads

### ISSUE THREAD

**Issue by krenuser** [RocketChat/Rocket.Chat#26642]
### Description:

Legacy message template is still used inside threads, while new message template is enabled and used in main channel to display messages.
I have some CSS improvements to legacy template, so I see difference between new and old one easily.

### Steps to reproduce:

1. Enable new message template in My Account.
2. Open any thread and post a message there.
3. Witness legacy message template instead of new one.

### Expected behavior:

All messages (either in main channel or in threads) are shown using new message template.

### Actual behavior:

Main channel messages are displayed in new message template as expected.
Thread messages are still displayed in legacy message template.

### Server Setup Information:

- Version of Rocket.Chat Server: **5.0.4**
- Operating System: **Ubuntu 20.04**
- Deployment Method: **docker**
- Number of Running Instances: **1**
- DB Replicaset Oplog: **Enabled**
- NodeJS Version: **v14.19.3**
- MongoDB Version: **5.0.11 / wiredTiger**

### Client Setup Information

- Desktop App or Browser Version: **Desktop App v3.8.7**
- Operating System: **Windows 10**

### Additional context

_none_

### Relevant logs:

_(not applicable)_

**Comment by dudanogueira** [comment]
Hi!

Thanks for pointing this out.

**Comment by ggazzo** [comment]
we know its a work in progress, thanks for reporting anyway
