### ISSUE TITLE
Show thread messages in the main channel feature does not exist anymore

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#26651]
### Description:

Pre RC 5.0.0 there used to be a feature that allows users to choose whether all messages in the thread are shown on the main view of the channel.

This was called `Show thread messages in the main thread` under personal settings.

![Screenshot from 2022-08-22 18-34-57](https://user-images.githubusercontent.com/6958942/185962488-8ed1892f-9848-42b0-890a-45862376349d.png)

The new feature replacing it in RC 5.0.x called `Also send thread message to channel behavior` is nice but it covers only sending messages by the person in question. This leaves out any messages of users who choose not to make their replies visible on the main channel view adding to confusion what is shown on the main view and what is not.

### Steps to reproduce:

1. Teach people the feature that allows seeing all threaded messages on the main view, and some of them feel it is easier to keep track of many threads at once this way.
2. Upgrade to RC 5.0.0

### Expected behavior:

Everybody is happy. ;)

### Actual behavior:

Get confronted by users who preferred to follow all threaded messages on the main channel view. Try not to anger everybody else by simply enforcing `Also send thread message to channel behavior: Always` for everybody.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.4
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox or Chrome

### Additional context

For the record a link to the new feature that does not cover all of the old functionality: https://github.com/RocketChat/Rocket.Chat/pull/26002

**Comment by Jojuh** [comment]
Can confirm, I am unsure if this is related but you can also not change the View mode to Normal, instead an empty selection is shown after saving the settings and the view does not differ from Cozy or Compact.

![image](https://user-images.githubusercontent.com/42804197/186087305-281d9b92-5a97-4882-b9a7-617948c149c2.png)

**Comment by ggazzo** [comment]
@milton-rucks

**Comment by matthias4217** [comment]
Why is it in https://github.com/RocketChat/Rocket.Chat/labels/wontfix ?

**Comment by smuuf** [comment]
Yes, this should be up to the user's preference how he/she wants to display channel threads, and _not_ how the sender specifies it.

**Comment by Gummikavalier** [comment]
To complete this issue I also have to mention that I don't think the developers actually have understood the issue this change causes because we were suggested educating users for it would be the solution. Not even after explaining it carefully several times. So maybe it can be considered again later.

**Comment by aceArt-GmbH** [comment]
> Also send to channel behavior

This also affects notifications.
Previously all messages were shown in main thread but only if you actively followed a thread or participated you got a notification
