### ISSUE TITLE
Links on the Files List are not signed for S3

### ISSUE THREAD

**Issue by netdevfighter** [RocketChat/Rocket.Chat#2667]
Your Rocket.Chat version: ? Running on your demo chat. ;)

Over the side menu I can not open some attachments.  I get only the loading circle all the time.
![unabletoopenatts](https://cloud.githubusercontent.com/assets/4456399/14085215/e9520b54-f51e-11e5-98a0-dfa5529a4839.png)

Can you check this?

**Comment by sampaiodiego** [comment]
@netdevfighter can you please check your browser console for errors? also, do you got any errors on the network tab? thanks

**Comment by netdevfighter** [comment]
Yes, I get HTTP Code 403. I can see more details on the screenshots.

![accessdenied](https://cloud.githubusercontent.com/assets/4456399/14086193/2475ffb0-f524-11e5-9d7b-b789301931df.png)

**Comment by sampaiodiego** [comment]
Ok, thank you..

this is related to S3 storage type. links on the file list are not signed (shame on me).

I'll fix this ASAP.
