### ISSUE TITLE
[Bug] Cannot make italic with stars

### ISSUE THREAD

**Issue by xmedeko** [RocketChat/Rocket.Chat#26680]
### Description:

In the older v4.8.x it was possible to make italic text by stars and underscores, i.e. `*italic*` and `_italic_`. Now, underscores works only, single stars makes bold text. Note: this violates common Markdown syntax, e.g. see https://daringfireball.net/projects/markdown/syntax#em

### Expected behavior:

Single stars should makes text italic - emphasize.

### Actual behavior:

Single stars should makes text bold - strong.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System: Linux
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.13 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App Version: 3.8.7
- Operating System: Windows 10

**Comment by DatAmstrongest** [comment]
Can I work on this issue?

**Comment by hugocostadev** [comment]
This was added in our radar, and we will discuss this internally to see the impact that this change could have. THanks !

**Comment by gabriellsh** [comment]
Hi @xmedeko!

First thing, thanks for your contribution!

What happened is that we recently rewrote the whole message template, and dropped support for different parsers. Previously we had a couple of different parsing settings, and one of them indeed uses `*` for italic, but the `Original` (that's the default setting option) always used `*` for bold.

This new template was under a flag before 5.0, and now is the default one. If you still wan't to use the old template, you can go to `My account > preferences > global > Use legacy message template`. Beware though, that this preference might not exist in the future.

**Comment by xmedeko** [comment]
@gabriellsh Yes, I have switched to the legacy template already. It's hard to understand to me, why you do not follow common Markdown syntax and develop some own flavour. It's very inconvenient. E.g. see my link above or check the Github, it makes `*italic*` as really *italic*, not bold. IMO with writing new parser, it's time to drop such oddities and align with common Markdown implementations.
