### ISSUE TITLE
Convert ASCII to Emoji preference does not appear to be honored.

### ISSUE THREAD

**Issue by poandlsl** [RocketChat/Rocket.Chat#26681]
### Description:

Convert ASCII to Emoji preference does not appear to be honored.  After disabling this preference, users still experience ASCII being converted to emojis automatically.

### Steps to reproduce:

1. Disable 'Convert ASCII to Emoji' in My Account > Preferences > Messages
2. Send a message containing an ASCII emoticon (`:)` or `The final score was 0:3`)
3. Witness `:)` convert to :smiley: and `The final score was 0:3` convert to 'The final score was :innocent:'

### Expected behavior:

When 'Convert ASCII to Emoji' is disabled, no ASCII should be converted to emojis.

### Actual behavior:

ASCII characters are converted to emojis, despite the disabled setting.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: Rocky Linux 8.6
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: Rocketchat Desktop Client 3.8.7 and Firefox 103.0
- Operating System: Ubuntu 20.04

**Comment by dudanogueira** [comment]
Hi! I Can confirm this bug.

We have been changing the Message Parser, and did a Community Open Call about it:
https://www.youtube.com/watch?v=zhPF9LpTR94&t=1046s

Thanks for pointing out!

**Comment by postwarbreakout** [comment]
Same here. We have bots that send file paths and that's a total mess now.
Even simple backslashes just disappear: `c:\temp\tempfile` becomes "C😕temptempfile".

**Comment by postwarbreakout** [comment]
By browsing to similar issues, I found a workaround which fixed things for us: https://github.com/RocketChat/Rocket.Chat/issues/26475#issuecomment-1222291767
