### ISSUE TITLE
SMTP reacted to slow and caused errror's

### ISSUE THREAD

**Issue by BadreatD** [RocketChat/Rocket.Chat#26690]
Server Setup Information

Version of Rocket.Chat Server: 5.0.4
Operating System: Debian 11
Deployment Method: tar ( manual )
Number of Running Instances: 1
NodeJS Version: v14.20.0
MongoDB Version: 4.4.16
Proxy: reverse Proxy Nginx
Firewalls involved: ufw

I could not send E-Mails via SMTP caus the greeting_timeout value was to low /DIR/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js
changed " const GREETING_TIMEOUT = 35 * 1000; // how much to wait after connection is established but SMTP greeting is not receieved

My STMP Server reacts a bit slow but the changed worked!

Error Message before the change:
Exception in defer callback: Error: Greeting never received at SMTPConnection._formatError (/DIR/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:784:19) at SMTPConnection._onError (/DIR/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:770:20) at Timeout. (/DIR/Rocket.Chat/programs/server/npm/node_modules/meteor/email/node_modules/nodemailer/lib/smtp-connection/index.js:704:22) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7) { code: ‘ETIMEDOUT’, command: ‘CONN’ }

**Comment by dudanogueira** [comment]
Hi!

Have you tried setting the MAIL_URL with all the [settings you need from the nodemailer](https://nodemailer.com/smtp/#connection-options)?

This should give you direct access to define the nodemailer url to be used, according to here:
https://github.com/RocketChat/Rocket.Chat/blob/f0c37c5a8c904181577b80d239255284ac6a1280/apps/meteor/app/lib/server/startup/settingsOnLoadSMTP.ts

make sure to leave **SMTP_Host** empty, so it never enters this code and leaves MAIL_URL as it comes from the environment.

**Comment by dudanogueira** [comment]
Closing for now. Let me know if this solves it for you otherwise we reopen :)

THanks!
