### ISSUE TITLE
Limit the history depth for group of users

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2669]
Your Rocket.Chat version: 0.24.0

Hello. It would be great to have a way to limit the history depth (search and scroll) for group of users. For example, provide full history for administrators and moderators and a month ago for a user.

**Comment by engelgabriel** [comment]
It would be easier to limit per "days back" than per number os messages.

**Comment by sinteur** [comment]
Feel free to mark 3528 as a duplicate.

**Comment by dggtydnk** [comment]
#3528 is a bit different, that is requesting limiting history per channel, this request is limiting history per user

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
