### ISSUE TITLE
Can't lock to Ubuntu launcher

### ISSUE THREAD

**Issue by dannystyleart** [RocketChat/Rocket.Chat#2673]
Linux client could not be locked to the ubuntu launcher, so after I have closed the app I have to search for it trough the dash, start the app and from panel context menu have to click on show to open the app window.

Environment: Ubuntu 14.04 LTS x64 (Unity DE) with virtual desktops turned on.

Expected: 
When app starts, the icon in the launcher should appear and stay untill app closes, but if the user clicked locked the icon, it should not disappear.

**Comment by giray** [comment]
Works for me on Ubuntu 15.10 (Unity) and RocketChat+ 1.2.0, though its a bit flaky, have to quit rocketchat then start, and lock to launcher.

If I unlock, I cannot re-lock to launcher without restarting...

**Comment by engelgabriel** [comment]
Hi, can you please open the issue at https://github.com/RocketChat/Rocket.Chat.Electron/issues

Please make sure you are using the version 1.2

**Comment by tuxBurner** [comment]
+1
