### ISSUE TITLE
CentOS 7 Segmentation Fault

### ISSUE THREAD

**Issue by whitetiger264** [RocketChat/Rocket.Chat#26739]
Because my previous [post](https://github.com/RocketChat/Rocket.Chat/issues/26664) was closed, even though I never confirmed it was fixed, I am now re-opening a new one again. 

- Version of Rocket.Chat Server: 4.7.4
- Operating System: CentOS 7
- Deployment Method: Manual
- Number of Running Instances: 1
- Node Version: 14.18.3
- MongoDB Version: 4.2.22

I tried upgrading from `4.7.4` to the latest release version `5.0.5` today and once again, I am presented with a segmentation error:

```
[root@core opt]# node /opt/Rocket.Chat/main.js
Segmentation fault (core dumped)
[root@core opt]# 
```

I previously experienced an issue with `MongoServerSelectionError: Server selection timed out after 30000 ms` error and solved this by adding the `&directConnection=true` to both `MONGO_URL` & `MONGO_OPLOG_URL` strings.

I was then again presented with a common error `Error: Must pass options.rootUrl or set ROOT_URL in the server environment` and solved this with

```
export ROOT_URL=https://rockethcat.example.com:3000/
export MONGO_URL=mongodb://localhost:27017/rocketchat
export PORT=3000
```
And now, I am back to my Seg fault, which I reported many times now since version 4.7.4 with no insight on how to solve this:

```
[root@core opt]# node /opt/Rocket.Chat/main.js
Segmentation fault
[root@core opt]# 
```

Hopefully this request does not get closed again and addressed, please. :(

**Comment by Fasal-Official** [comment]
I'm having similar issue here https://github.com/RocketChat/Rocket.Chat/issues/26716
