### ISSUE TITLE
Cannot register user on rocketchat workspace

### ISSUE THREAD

**Issue by acrespomoa** [RocketChat/Rocket.Chat#26734]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Issue doesn't have the information required. Closing.
