### ISSUE TITLE
Emoji item selection just changes on KeyUp()

### ISSUE THREAD

**Issue by Morgy93** [RocketChat/Rocket.Chat#2675]
Your Rocket.Chat version: 0.24.0

If you try to select one of the Emoji with the arrow keys, you'll notice that the selection just changes on some KeyUp() event.
Meaning you can't keep the key pressed to cycle through the items. 

![emoji](https://cloud.githubusercontent.com/assets/7961978/14100817/720a2cbc-f590-11e5-9fdf-86873bd2c06d.gif)

**Comment by engelgabriel** [comment]
Thanks for reporting. PRs are welcome!
