### ISSUE TITLE
Blank screen on Administration > Settings > Omnichannel page

### ISSUE THREAD

**Issue by imahbub** [RocketChat/Rocket.Chat#26778]
### Description:

I wanted to configure omnichannel communication using Rocket.Chat for my team, so I visited the administration > Settings > Omnichannel page, and it showed me a blank page with no noticeable data or loading spinner. 

We had omnichannel enabled and accessible before in the previous version of Rocket.Chat. 

### Steps to reproduce:

1. In Rocket.Chat 5.0.4 go to administration.
2. Navigate to Settings option.
3. Search and open “Omnichannel”

### Expected behavior:

I should have gotten settings page for Omnichannel

### Actual behavior:

It loads for a brief second and the page turns blank. Screenshot included.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.4
- Operating System: Host OS Debian 11
- Deployment Method: Docker official image
- Number of Running Instances: 1
- DB Replica set Oplog: Yes
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.16 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 104.0.1
- Operating System: Arch Linux

### Additional context

Screenshot

![image](https://user-images.githubusercontent.com/63340482/187971035-43961e57-0794-4b84-9879-2c8bcf467881.png)

### Relevant logs:

Server log: https://pastebin.com/uhnnK4dz
Browser console log: https://pastebin.com/wMicmX5H

Thank you Rocket.Chat team for looking into my issue.

**Comment by dudanogueira** [comment]
Hi!

Can you make sure this user has user role? I have seen som errors like this before.

Also, try a hard refresh (cltr+shift+R)

Another thing to look is how your deployment is being proxied. We have a comprehensive doc for this:
https://docs.rocket.chat/quick-start/environment-configuration/configuring-ssl-reverse-proxy

Please, take a look at https://docs.rocket.chat/getting-support/community-support on how/when to open an issue. 

This is probably some deployment or config issue, as this have been working for a lot of our users. 

Thanks!

**Comment by himpierre** [comment]
@imahbub were you able to solve this issue? I have exactly the same problem. Working omnichannel settings page with version 4.8.2. Empty page with version 5.1.1. All other settings pages work so this cannot be a proxy issue I guess @dudanogueira?

cheers, t.

**Comment by imahbub** [comment]
> @imahbub were you able to solve this issue? I have exactly the same problem. Working omnichannel settings page with version 4.8.2. Empty page with version 5.1.1. All other settings pages work so this cannot be a proxy issue I guess @dudanogueira?
> 
> cheers, t.

Hi @himpierre we still could not solve this issue. We are testing on staging still :(

**Comment by himpierre** [comment]
Also I just tried without any proxy. Same picture.

**Comment by himpierre** [comment]
@dudanogueira Is there a way to disable Omnichannel via Mongodb shell command?

**Comment by himpierre** [comment]
TThere are a lot of errors calling the omnichannel settings page.

![image](https://user-images.githubusercontent.com/40269193/189290773-351d533c-0efc-4def-93bf-658f50b28894.png)

**Comment by himpierre** [comment]
There is another Bug open. https://github.com/RocketChat/Rocket.Chat/issues/26516

**Comment by fabiosurrage** [comment]
I have exactly the same problem. Working omnichannel settings page with version 4.8.2. Empty page with version 5.0.5 and 5.1.1.

**Comment by tom666-debug** [comment]
Yep ... same as https://github.com/RocketChat/Rocket.Chat/issues/26516
Seems they dont care at all

**Comment by billynoah** [comment]
We have this problem as well.

**Comment by dudanogueira** [comment]
Hi! We have found the problem for this issue!!

Sorry for the delay, it was a hard one to reproduce. 

Please, check this message for a workaround while we fix it on a later patch:
https://github.com/RocketChat/Rocket.Chat/issues/26516#issuecomment-1244173602

I will close this for now in favor of: https://github.com/RocketChat/Rocket.Chat/issues/26516
