### ISSUE TITLE
REST API: Add abillity to specify different user while calling users.setStatus

### ISSUE THREAD

**Issue by eerrap** [RocketChat/Rocket.Chat#26774]
**Desired api enhancement:**
Allow Users with appropriate permission "Manage User Status" to set another users status via REST API assuming a userId or userName of another user is given, as already available for users.getStatus.

**Suggestion**
`curl -H "X-Auth-Token: 40tB-Cn5YQJ74QMlQXi4Zf4E_-e0P5CrklU2pWOtV9M" \
     -H "X-User-Id: uunbZHiuEnib8Pawj" \
     -H "Content-type: application/json" \
     -d '{"userId": "BsNr28znDkG8aeo7W", "message":"My status update", "status": "online"}' \
     https://localhost:3000/api/v1/users.setStatus`

**Comment by dudanogueira** [comment]
Hi!

:champagne:  **Congratulations!** :champagne: 
You have unlocked an undocumented feature ;)

You can do it with:
{"message":"My status update", "status": "online", "userId": "zXuq7SvPKYbzYmfpo"}
or
{"message":"My status update", "status": "online", "username": "duda.nogueira"}

I have changed the documentation to reflect it (should be published anytime soon)
https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/users-endpoints/set-status

[I was able to discover this by inspecting this code](https://github.com/RocketChat/Rocket.Chat/blob/f74ba4e587ec294b4482ba578dcb2708f0322b4e/apps/meteor/app/api/server/v1/users.ts#L999)

Thanks for pointing it out!
