### ISSUE TITLE
$ money amounts don't create links, but % still does

### ISSUE THREAD

**Issue by dletter** [RocketChat/Rocket.Chat#26771]
### Description:

If you type $77.77, it comes up normally in chat.

If you type 77.77% , it makes a link for "77.77" , which could be to something you wouldn't want to link somebody to.

Percents should be not created into links, just like money amounts are not.

### Steps to reproduce:
Type 88.88% , hit enter.

1. 
2. 
3. 

### Expected behavior:

No link should be generated.

### Actual behavior:

Creates a link.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
It was already fixed and there is already a Release Candidate. Soon we will be released the official Release.
