### ISSUE TITLE
markdown tables not rendering correctly

### ISSUE THREAD

**Issue by sperlab** [RocketChat/Rocket.Chat#26777]
Hi there.

Running self-hosted rocket chat 5.0.5
**Markdown Parser** from **Message** **Settings** **MArkdown** section is set to **Marked** (and **Enable Marked Tables** checked)

Any combination of options does not bring back correct rendering of markdown tables such as

```
| A field | B Field |
| ---------- | --------- |
| 456123 | aaaaaaaaa |
| 789524 | bbbbbbbbbbb |
| 365214 | ccccccccccccc |
```
Which, if not mistaken, rendered perfectly well in rc 4.x

**Comment by dudanogueira** [comment]
That's right. in 4.X it was rendered correctly.

**Comment by sheck87** [comment]
I'm having the same issue with v5. Does anyone have a solution for this?

**Comment by thrakks** [comment]
+1 for this. I reckon it was piggybacking html rendering in messages to work. Now that with 5.x.x disabling rendering html to prevent xss attacks Marked tables are broken too. 

Coincidence? I think not!

Please please please can we fix Marked tables (especially being created by incoming webhooks) or optionally allow HTML rendering again?

**Comment by sperlab** [comment]
Well ..., markdown rendering seems not only broken for tables. Lists and even links do not render properly (dokuwiki links for example).

Is there a way to test a downgrade from **5.1.1** to **4.8.6** to get it back to normal ?

**Comment by hugocostadev** [comment]
Hi Guys, we are working to fix those issues.
@sperlab you don't need to downgrade, just go to My Account and enable the Old message parser option

**Comment by frostbtn** [comment]
Thanks **[hugocostadev](https://github.com/hugocostadev)**! You probably meant the _My Account_ -> _Preferences_ -> _Global_ -> _Use legacy message template_ setting. It definitely returns Markdown tables and link formatting! Unfortunately it's a per-user setting. At least it is something to wait the fix with.

**Comment by sperlab** [comment]
Perfect, now only need to dig into a mongodb query to batch update that pref for all already created users.
ThX @hugocostadev

**Comment by hugocostadev** [comment]
You are welcome!

We are considering supporting table on the new message parser by the way...

**Comment by thrakks** [comment]
@hugocostadev @frostbtn Thanks for that! Fixes our problems for now. Definitely would love Tables being supported in the new message parser too of course but this keeps us working and able to update Rocketchat

**Comment by sheck87** [comment]
In v6 option _Use legacy message template_ was removed, so the problem comes back... Is there any fixes for v6?

**Comment by timiil** [comment]
is it possible to reenable this great feature in the new version?

**Comment by detoxhby** [comment]
any update on this one?

**Comment by thrakks** [comment]
@hugocostadev any ETA on when Rocketchat will at minimum support displaying tables again?

I'm forced to be version locked at ~5.1.2 due to my companies staunch reliance on tables for displaying data via our webhooked integrations in info channels.

**Comment by hugocostadev** [comment]
We don't have a plan yet @thrakks , feel free to raise a PR to implement this feature in our message-parser https://github.com/RocketChat/fuselage/tree/develop/packages/message-parser
