### ISSUE TITLE
При отправке времени влезает смайлик.

### ISSUE THREAD

**Issue by DReeborn** [RocketChat/Rocket.Chat#26784]
Если отправить в сообщении "10:30" то получается "1😇0 ", т.к. "0:3" преобразуется в смайлик без необходимости.

**Comment by kiwi-oss** [comment]
Could you use a site like [DeepL](https://www.deepl.com) to translate your message to English? This makes it easier for others to help you as English is the commonly used language on GitHub.

Your problem has [already been reported](https://github.com/RocketChat/Rocket.Chat/issues/26475). You can find a workaround there: [use legacy templates](https://github.com/RocketChat/Rocket.Chat/issues/26475#issuecomment-1222291767).
