### ISSUE TITLE
Rocet Chat App wont login

### ISSUE THREAD

**Issue by BrodieBurbach** [RocketChat/Rocket.Chat#26781]
On my iphone 12 iOS15.6.1, my work chat (below) will not allow me to login. after inputting user name/password and clicking the login button it just spins. 
https://chat.unifieddatalibrary.com/chat/

**Comment by dudanogueira** [comment]
Hi!

Running Rocket.Chat in a subpath is no longer advised nor supported:
https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371

It can cause unexpected behaviors.

Please, refer to this documentation on when/how to open an issue:
https://docs.rocket.chat/getting-support/community-support#reporting-bugs

Thanks!
