### ISSUE TITLE
Empty item at chanel member list

### ISSUE THREAD

**Issue by netdevfighter** [RocketChat/Rocket.Chat#2678]
![rocketchatmemberlist](https://cloud.githubusercontent.com/assets/4456399/14102315/1952ce08-f59a-11e5-98dc-460b61401440.png)

There is a blank line at the member list. I don't know what this has triggered. Maybe the deletion of the user rocket.cat?

Your Rocket.Chat version: 0.24.0

**Comment by engelgabriel** [comment]
Does the empty line persist after refresh?
Can you open the console and get a dump of the users list array of the room?

**Comment by netdevfighter** [comment]
@engelgabriel Yes, the line is persist after refresh, clear the browser cache etc.

Here the users list of the room:
´´´
a["{\"msg\":\"added\",\"collection\":\"rocketchat_room\",\"id\":\"GENERAL\",\"fields\":{\"name\":\"helpdesk\",\"t\":\"c\",\"topic\":\"NWDev\",\"usernames\":[\"jboehler\",\"arunk\",\"hubot\",null,\"tlindenmann\",\"khirschfeld\"]}}"]
´´´

**Comment by sampaiodiego** [comment]
I can't reproduce :disappointed: 

@netdevfighter can you please update your rocket.chat and see if it still happens?

**Comment by netdevfighter** [comment]
Yes, I have already the latest rocket version of this week. But the problem still exists.

You can see the null value on the usernames property:

`001-rs:PRIMARY> db.rocketchat_room.find( { _id : "GENERAL" })`
`{ "_id" : "GENERAL", "ts" : ISODate("2016-03-18T22:39:31.545Z"), "t" : "c", "name" : "helpdesk", "usernames" : [ "jboehler", "arunk", "hubot", null, "tlindenmann", "khirschfeld", "ddraper" ], "msgs" : 40, "default" : true, "lm" : ISODate("2016-03-30T13:48:06.479Z"), "topic" : "NWDev" }`

**Comment by sampaiodiego** [comment]
@netdevfighter I couldn't reproduce the `null` value using the system.

anyway, I put a `null` value directly in the database and the empty line did not show to me.

**Comment by netdevfighter** [comment]
Ok, I understand that's not easy to find out.

This is the html snippet of the user list:
`<ul class="list clearfix lines">
						
							<li class="user-image user-card-room status-online">
								<a data-username="tlindenmann" tabindex="0" title="tlindenmann">
									<div class="avatar">
		<div class="avatar-image" style="background-image:url(/avatar/tlindenmann.jpg?_dc=0);"></div>
	</div>
									<p>tlindenmann (UTC +2)</p>
								</a>
							</li>
						
							<li class="user-image user-card-room status-">
								<a data-username="arunk" tabindex="0" title="arunk">
									<div class="avatar">
		<div class="avatar-image" style="background-image:url(/avatar/arunk.jpg?_dc=0);"></div>
	</div>
									<p>arunk </p>
								</a>
							</li>
						
							<li class="user-image user-card-room status-">
								<a data-username="hubot" tabindex="0" title="hubot">
									<div class="avatar">
		<div class="avatar-image" style="background-image:url(/avatar/hubot.jpg?_dc=0);"></div>
	</div>
									<p>hubot </p>
								</a>
							</li>
						
							<li class="user-image user-card-room status-">
								<a data-username="jboehler" tabindex="0" title="jboehler">
									<div class="avatar">
		<div class="avatar-image" style="background-image:url(/avatar/jboehler.jpg?_dc=0);"></div>
	</div>
									<p>jboehler </p>
								</a>
							</li>
						
							<li class="user-image user-card-room status-">
								<a tabindex="0">
									<div class="avatar">
		<div class="avatar-image"></div>
	</div>
									<p> </p>
								</a>
							</li>
						
							<li class="user-image user-card-room status-">
								<a data-username="ddraper" tabindex="0" title="ddraper">
									<div class="avatar">
		<div class="avatar-image" style="background-image:url(/avatar/ddraper.jpg?_dc=0);"></div>
	</div>
									<p>ddraper </p>
								</a>
							</li>
						
							<li class="user-image user-card-room status-">
								<a data-username="khirschfeld" tabindex="0" title="khirschfeld">
									<div class="avatar">
		<div class="avatar-image" style="background-image:url(/avatar/khirschfeld.jpg?_dc=0);"></div>
	</div>
									<p>khirschfeld </p>
								</a>
							</li>
						
					</ul>`

Give me some time, I will try to analyze it on the affected instance. Yeah let's work together, if that's okay for you.

**Comment by netdevfighter** [comment]
I could not also longer reproduce the behavior. 

If it occurs again, I will open this ticket again.

Thanks

**Comment by engelgabriel** [comment]
Thanks @netdevfighter
