### ISSUE TITLE
Cursor jumps to channel message box after sending an image to a thread

### ISSUE THREAD

**Issue by krenuser** [RocketChat/Rocket.Chat#26790]
### Description:

After uploading (pasting) image to a thread, cursor automatically returns to channel's message box, even without hiding thead and its semi-transparent backdrop.

It happens often when you send an image and then then leave a comment immediately to it (because Description text box in Send file popup doesn't suggest `@mentions` and smiles and doesn't allow multi-line).

### Steps to reproduce:

1. Open any thread
2. Put some image to the clipboard, e.g. make a PrintScreen.
3. Paste it to thread, press ENTER or "Send" button.
4. Start typing text again.

### Expected behavior:

Cursor jumps to thread's message box and text is now typed in it.

### Actual behavior:

Cusror jumped to channel's message box, a thread and its backdrop are still visible.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.4
- Operating System: Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.11 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.8.9 + Web version
- Operating System: Windows 10

### Additional context

─

### Relevant logs:

─

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
