### ISSUE TITLE
Markdown parser removes colons from timestamps

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#26799]
### Description:

When a message contains a time specification in format HH:MM:SS, in some cases the colons get removed.

### Steps to reproduce:

1. Write the following messages (one line per message):

```
10:00
10:20:30
10:30
10:30:50
10:20:30
13:51:17
10:30:51
10:31:51
10:21:51
10:20
```

### Expected behavior:

The messages are rendered as they are written.

### Actual behavior:

What gets rendered, looks like this:

```
10:00
102030
10:30
10:30:50
102030
135117
10:30:51
10:31:51
102151
10:20
```

As you can see, in _some_ of the timestamps, the colons are missing.

![image](https://user-images.githubusercontent.com/404840/188319949-1b41ed4b-e225-4c62-b764-e9dc10b84b03.png)

When editing any of the messages, all missing colons are visible.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.0
- Operating System: Linux
- Deployment Method: Docker image via Systemd (as documented in https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd)
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.11 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:
  - Chromium Version 105.0.5195.102 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 104.0.1 (64-Bit)
- Operating System: Arch Linux

The same behaviour can be observed in the Android app as well.

**Comment by dudanogueira** [comment]
I can confirm that.

10\:31\:51 will work.

This is related to
https://github.com/RocketChat/Rocket.Chat/issues/26800

**Comment by hugocostadev** [comment]
> 

Not related with #26800

**Comment by hugocostadev** [comment]
It was already fixed and there is already a Release Candidate. Soon we will be released the official Release.
