### ISSUE TITLE
snap”rocketchat-server" has no updates available
Snap“rocketchat-server

How to upgrade version 3.18.7 to version 5.0

### ISSUE THREAD

**Issue by yes567** [RocketChat/Rocket.Chat#26791]
![Screenshot_20220902_221520.jpg](https://user-images.githubusercontent.com/106227627/188168708-ca57e662-8892-47c8-948d-f7bef54e6b04.jpg)

**Comment by dudanogueira** [comment]
Hi!

This is not software issue.

Please, check here on when/how to open a new issue:
https://docs.rocket.chat/getting-support/community-support

Thanks!
