### ISSUE TITLE
Unable to switch to another user when administrating users

### ISSUE THREAD

**Issue by anthony-o** [RocketChat/Rocket.Chat#2679]
Your Rocket.Chat version: 0.24.0

In https://myrocketchantinstance.mycompany.com/admin/users, when I edit a user, after clicking on "Save", I want to select another user to modify it, and the right panel sticks on the previous selected user, even if I click on "Cancel".

That right panel should display me the user I've just selected.

**Comment by marceloschmidt** [comment]
Fixed in e1291d7
