### ISSUE TITLE
/shrug gets an arm removed

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#26800]
### Description:

When typing `/shrug`, the resulting kaomoji is missing an arm.

### Steps to reproduce:

1. Create a message using `/shrug`.

### Expected behavior:

The kaomoji being rendered looks as follows: ` ¯\_(ツ)_/¯ `

### Actual behavior:

The kaomoji is missing an arm: ` ¯_(ツ)_/¯ `

![image](https://user-images.githubusercontent.com/404840/188320706-b93fe29d-6c50-4b14-a429-3d6106fe21be.png)

When editing the message, the arm is visible.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.0
- Operating System: Linux
- Deployment Method: Docker image via Systemd (as documented in https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/systemd)
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.11 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:
  - Chromium Version 105.0.5195.102 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 104.0.1 (64-Bit)
- Operating System: Arch Linux

The same behaviour can be observed in the Android app as well.

**Comment by stefanandres** [comment]
In fact. Also it seems every single backslash is removed. E.g. `\o/` becomes `o/` as well.

**Comment by kuemmi** [comment]
Yes, all backslashes are getting removed, see also: #26907
