### ISSUE TITLE
integrations broken in latest build

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#2680]
when I try the curl command listed in the integration screen, I get:  {"status":"error","message":"You must be logged in to do this."}

**Comment by bott0r** [comment]
Works for me, however i had the same error when the token for the integration were using special characters. which RC version are you using at the moment ? (check your tokens for anything like % or so)

**Comment by sinteur** [comment]
I did a git pull yesterday, so I'm fairly up to date. Token has no % - and since none of them work anymore I suspect that's not it. Here's a sample token: hpiAnf2Twqtnykn2c/12dmjBcJSTgnVAJ4SnjC4EmiRSVSl5Z/fSDfxIZLfOA=

**Comment by bott0r** [comment]
hmm, i just updated 10 seconds ago to the recent dev built and both incoming and outgoing webhooks work.

**Comment by sinteur** [comment]
just did another git pull, I will update this with the results. It's building now

**Comment by bott0r** [comment]
I just tested a newly created webhook and it worked fine, however i my webhook token only consists out of normal characters  no slashes no = 

S8dWiZhztSko4Dot8/XtEb5RDsSdvqDtzWFCzQepqyoHj2ZrxbuEWJHi3qexwzPo9A

**Comment by sinteur** [comment]
It looks like this last git pull fixed it - although all integrations are turned off now. That, however, is something I can fix. I will close this.
