### ISSUE TITLE
Rocketchat 5.0.5 Jitsi App Integration - mic/cam options not correctly synced to Jitsi / no pre join page

### ISSUE THREAD

**Issue by comander192** [RocketChat/Rocket.Chat#26817]
### Description:

With the new Jitsi app integration we now have the mic/cam buttons when opening the call. These should be synced to the opened call. For us the cam button is automatically deactivated in the Rocketchat call UI but when the call opens the cam is turned on. Also there is no pre join page in Jitsi anymore though it is enabled in the Jitsi config. Rocketchat seems to override that setting but doesnt correctly sync the settings from its UI to Jitsi.

### Steps to reproduce:

1. Jitsi App Integration
2. open call in public channel
3. choose cam off, mic on in Rocketchat UI
4. Jitsi call gets opened
5. cam is on and mic is on

### Expected behavior:

Cam should be off in Jitsi as configured in the Rocketchat UI. OR open the pre join page in Jitsi as in Rocketchat version 4.x.x

### Actual behavior:

Cam is turned on in Jitsi Call. No pre join page is opened.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.5
- Operating System: RedHat 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: from Docker
- MongoDB Version: 5.0.11

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 104.0.5112.102 (Official Build) (64-bit)
- Operating System: Windows 10 21H1

### Relevant logs:

Cant see Errors, is there something else we can check in the logs?

**Comment by comander192** [comment]
Regarding the pre join page:

Rocketchat seems to send the parameters to Jitsi:

`
POST https://testchat.kv-telematik.de/api/v1/video-conference.join

{,…}
providerName
: 
"jitsi"
success
: 
true
url
: 
"https://jitsi/roomid?jwt=xxx#config.desktopSharingChromeExtId=\"nocfbnnmjnndkbipkabodnheejiegccf\"&config.callDisplayName=\"general\"&config.startWithAudioMuted=false&config.startWithVideoMuted=true&config.prejoinPageEnabled=false&config.prejoinConfig.enabled=false"` 
config.prejoinPageEnabled=false&config.prejoinConfig.enabled=false

**Comment by comander192** [comment]
It seems like the default configuration in the new start channel UI is not registered correctly:
<img width="149" alt="image" src="https://user-images.githubusercontent.com/26652586/188639428-77e7c3ea-4264-4ac8-955c-68e5b5332955.png">
I havent touched the 2 mic/cam buttons and started the call which resulted in:
`#config.desktopSharingChromeExtId=\"nocfbnnmjnndkbipkabodnheejiegccf\"&config.callDisplayName=\"testchannel\"&config.startWithAudioMuted=false&config.prejoinPageEnabled=false&config.prejoinConfig.enabled=false"`

There is no config.startWithAudioMuted=false even when the cam button is not activated. Default behaviour in Jitsi is then to enable the cam. This is the string once I activated and deactivated the cam button and startet then started the call:
`#config.desktopSharingChromeExtId=\"nocfbnnmjnndkbipkabodnheejiegccf\"&config.callDisplayName=\"testchannel\"&config.startWithAudioMuted=false&config.startWithVideoMuted=true&config.prejoinPageEnabled=false&config.prejoinConfig.enabled=false"`

**Comment by broferek** [comment]
All these URL parameters overload anything you may have set up in your own Jitsi config which is really annoying if we can't control the default behaviour we want to get in Rocket Chat Jitsi App.

**Comment by comander192** [comment]
It seems like us skipping the Prejoin page in Jitsi is the root cause here. Before the Rocketchat update we always enabled this page in our Jitsi settings and everything went fine even with over 40 participants. We changed nothing in our Jitsi config nor made an update there and after the Rocketchat update  the Jitsi calls were broken.

Please give us the option in the Jitsi App Settings to enable/disable the Prejoin page instead of hardcoding it in the app here:
https://github.com/RocketChat/Apps.Jitsi/blob/a17b000dbafacb6a1a5e0f405bdbddac55645b1c/src/videoConfProvider.ts#L101

Just give us this as a toggle in the UI!

I will now try to compile and upload the app to Rocketchat with there 4 code lines deleted.

**Comment by comander192** [comment]
I just compiled the app myself and uploaded it to Rocketchat via Apps Engine CLI. Works fine so far with 12 participants, I will post an update tomorrow after a bigger meeting.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
