### ISSUE TITLE
Rocketchat 5.0.5 Jitsi App Integration - some users cant hear others

### ISSUE THREAD

**Issue by comander192** [RocketChat/Rocket.Chat#26818]
### Description:

When we open Jitsi calls through Rocketchat with more than 8 users not all users can hear each other. The problem seems to be completely random. For example 8 users join the call initialy and 2 users join 3mins later. The 8 users can hear each other but not the 2 users that joined later and the same goes the other way, the 2 users can hear other but not the 8 initial users.

This issue happened after we updated from Rocketchat 3.18.7 to 5.0.5. We havent touched our Jitsi installation during this update. There were no Jitsi config changes between the Rocketchat version before and after. So this seems to related to the new Rocketchat Jitsi integration via the app.

### Steps to reproduce:

1. Jitsi App with JWT Auth
2. Open call in public channel
3. login happens automatically through JWT
4. Call is open and "initial" users can hear each other
5. additional users after (usually) 8 initial users cant hear others sometimes

### Expected behavior:

All users can hear each other

### Actual behavior:

Not all users can hear each other

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.5
- Operating System: RedHat 7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: from Docker
- MongoDB Version: 5.0.11

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 104.0.5112.102 (Official Build) (64-bit)
- Operating System: Windows 10 21H1

### Additional context

Also there is no pre join page available in Jitsi anymore even though its enabled in the settings see https://github.com/RocketChat/Rocket.Chat/issues/26817

### Relevant logs:

We dont see any errors in the Jitsi logs so its not easy to reproduce the error. Here are the Jitsi app Logs:
```
September 6, 2022 1:00 PM: "generateUrl" (1ms)
Instance: xxx
debug: 2022-09-06T11:00:55.860Z Caller: anonymous OR constructor
[
  "Executing generateUrl on video conference provider..."
]
debug: 2022-09-06T11:00:55.861Z Caller: anonymous OR constructor
[
  "Video Conference Provider's generateUrl was successfully executed."
]

September 6, 2022 1:01 PM: "customizeUrl" (2ms)
Instance: gQF44GdsbPyhhfQPB
debug: 2022-09-06T11:01:07.237Z Caller: anonymous OR constructor
[
  "Executing customizeUrl on video conference provider..."
]
debug: 2022-09-06T11:01:07.239Z Caller: anonymous OR constructor
[
  "Video Conference Provider's customizeUrl was successfully executed."
]
```

**Comment by chotaire** [comment]
That sounds like a problem using the Jitsi server, not with Rocket.Chat. To my understanding the Jitsi app just establishes the connection to a Jitsi server. So if there are issues with users not hearing each other, you will need support for Jitsi. I've seen this happening when people use different brands of browsers. Try if that still happens if everyone is using Chrome. Jitsi has recommended Chrome for a long time.

**Comment by debdutdeb** [comment]
Here's how the app generates the whole url (including the query parameters)
https://github.com/RocketChat/Apps.Jitsi/blob/a17b000dbafacb6a1a5e0f405bdbddac55645b1c/src/videoConfProvider.ts#L71

Not sure 100% whether this is the cause of an incorrectly generated url or a jitsi problem .. can you somehow check and compare the urls of a working and a non-working attendee?

**Comment by comander192** [comment]
It is possible that our Jitsi is not working 100% correctly. It is a very complex system and setup. But before the Rocketchat update it worked fine with 3.16.x and 3.18.7 Rocketchat. We havent touched the Jitsi config nor updated it. We only updated Rocketchat and installed the Jitsi app there and after that the Jitsi calls still have there problems.

It could be related to the now skipped Jitsi Prejoin page as mentioned here
https://github.com/RocketChat/Rocket.Chat/issues/26817

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
