### ISSUE TITLE
download status

### ISSUE THREAD

**Issue by thiesschneider** [RocketChat/Rocket.Chat#2683]
I am using the Rocket.Chat.Electron app beside the webclient and would love to have something like a progressbar for the file I download in Electron also. 
It would also be nice to open the downloaded file or the folder where the file is stored.

Thanks for this great Chat... you rock!

**Comment by engelgabriel** [comment]
Thanks for the kind words! :)

**Comment by MartinSchoeler** [comment]
Please reopen this in the electron repository. Thanks!
