### ISSUE TITLE
Link previews of images in new message parser are cropped and can't be clicked to enlarge.

### ISSUE THREAD

**Issue by chotaire** [RocketChat/Rocket.Chat#26838]
### Description:

Link previews of URLs to externally hosted images are often cropped and cannot be clicked to enlarge when using the new message parser.

### Steps to reproduce:

1. Post the following URL in a chat: https://i.gyazo.com/05c72da69a204f78f1008329cd5f5464.jpg
2. See how the image is cropped (it seems to expect a 16:9 ratio)
3. When hovering the mouse over the preview it shows how it is clickable, but nothing happens when clicked.

### Expected behavior:

The behavior should be the same as with uploaded images. The image should be shown completely and when clicking it, it will open a full size view of the image.

### Actual behavior:

Depending on the image (it seems to expect a 16:9 ratio), it is vertically cropped and clicking it does nothing.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.1
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1 on that server
- DB Replicaset Oplog: Unknown
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 105.0.5195.102
- Operating System: Windows 11 Pro (latest patches)

### Screenshots

Legacy Message Parser (everything works):

![7574c58fbd865d3ff7ba6ac9ed3e0cbb](https://user-images.githubusercontent.com/9246549/189338073-765d3755-e63d-4913-a491-45c688a8ad32.png)

New Message Parser (cropped and not clickable):

![12d955e42c2e0b2ecc6b0d2fce38c610](https://user-images.githubusercontent.com/9246549/189338105-d02eb648-2255-45aa-8b99-c2128e2cc33f.png)

New Message Parser when image has been uploaded (now it's clickable):

![f66d1f40f6a45f5b8c38e201fa09e1a6](https://user-images.githubusercontent.com/9246549/189340520-ee749f83-dd60-44bf-8751-2c384fd9a120.png)

**Comment by urosino** [comment]
I agree, it's annoying to see cropped images. I don't like the way the images are now displayed after the 5.0.0 upgrade. How can we show images in their natural size like it was before the update?

**Comment by chotaire** [comment]
Not sure how it is with others, but this is the one issue that keeps me from enabling the new message parser in its current state because users really don't like it at all. It's not just cosmetic, not being able to click to enlarge is really very annoying.

**Comment by wreiske** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/20546

**Comment by hugocostadev** [comment]
Hi @chotaire thank you for your feedback! 

We are addressing a lot of Message Parser Issues, and this one Is being worked on by me in the current cycle.

You should expect a fix soon, once I have a Pull Request that fixes this issue I gonna mention this issue there. 

Thanks

**Comment by chotaire** [comment]
@hugocostadev Thanks for letting us know about the current status. It is much appreciated.
