### ISSUE TITLE
Inline link preview not working?

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#2684]
Your Rocket.Chat version: 0.24.0

Unless there is something that I need to configure in the latest version inline link previews (incl. youtube) don't seem to work anymore.

**Comment by engelgabriel** [comment]
Lets test after https://github.com/RocketChat/Rocket.Chat/pull/2682 gets merged.

**Comment by rodrigok** [comment]
Please reopen if the problem persists

**Comment by salviof** [comment]
They persist do not working when in live chat

**Comment by salviof** [comment]
> Please reopen if the problem persists

They persist do not working when in live chat
