### ISSUE TITLE
Cycle Life ISSUE

### ISSUE THREAD

**Issue by rayamfonseca** [RocketChat/Rocket.Chat#26847]
Hello,

My name is Rayam Fonsêca, I am a Master's student in Computer Science at the Federal University of Sergipe. In order to write an article, we are doing an exploratory study of some applications, and the one chosen by me was Rocket.Chat. If possible, I would like to know how the life cycle of the issues works, if there is a screening before they are assigned by the community members, if any, if there is any priority and, also, in relation to the roles assigned after the issue is selected, is she treated by any member? or are members only recipients for other programmers to solve problems? Thank you very much in advance!

**Comment by dudanogueira** [comment]
Hello Rayam!

Please, feel free to reach me at duda.nogueira@rocket.chat or our community team at community@rocket.chat
or at our open server:  [https://open.rocket.chat/direct/duda.nogueira](https://open.rocket.chat/direct/duda.nogueira)

Thanks!
