### ISSUE TITLE
MongoServerSelectionError: connection timed out

### ISSUE THREAD

**Issue by artmatv** [RocketChat/Rocket.Chat#26856]
My server is down after adding new user to DB or making someone an admin. Reboot helps to work it again. I've installed rocketchat via snap and set up nginx on 127.0.0.1 because connection didn't happen without nginx.
Here's my last 1000 lines from logs
[rocketchatlogs.txt](https://github.com/RocketChat/Rocket.Chat/files/9552401/rocketchatlogs.txt)

**Comment by dudanogueira** [comment]
Hi!

Ps: the problem you have is not related to the software, but to it's usage.

Please, checkout our [Community Resources](https://docs.rocket.chat/getting-support/community-resources) before opening a bug.

And when/if opening an issue, please, follow the template with requested infos as It really helps debugging it! :smile: 

Closing for now.
