### ISSUE TITLE
Fields Query Parameters not working on Group Members list endpoint

### ISSUE THREAD

**Issue by iKnowJavaScript** [RocketChat/Rocket.Chat#26854]
### Description:
Fields Query Parameters not working on Group Members list endpoint

### Steps to reproduce:

1. Send a get request with query parameter on endpoint '/api/v1/groups.members' i.e `/api/v1/groups.members?roomId='pGEtuyxaKJrrxmS8j'&query={'name':{'$regex':${search},'$options':'i'}}`
2. Returns an error
`data: {
      success: false,
      error: `Invalid query parameter provided: "{'name':{'$regex':geo,'$options':'i'}}" [error-invalid-query]`,
      errorType: 'error-invalid-query',
      details: [Object]
    }
  },`

Note: request works when query filter is not being applied.

1. 
3. 
4. 

### Expected behavior:

Members can be filtered by query

### Actual behavior:

`data: {
      success: false,
      error: `Invalid query parameter provided: "{'name':{'$regex':geo,'$options':'i'}}" [error-invalid-query]`,
      errorType: 'error-invalid-query',
      details: [Object]
    }
  },`
![Screenshot 2022-09-12 at 22 18 23](https://user-images.githubusercontent.com/28352178/189760588-5bc08c62-a489-4009-9f4a-37502f73c878.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: API call with Axios
- Operating System: Mac OS

**Comment by dudanogueira** [comment]
Hi!

This is the API DOC for reference:
https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/groups-endpoints/members

It only states that it has **offset, count and sort**. Of those, sort is not working.

Here is the code:
https://github.com/RocketChat/Rocket.Chat/blob/ddd1e87cd142eb2bcbdcb7c1e8f237462ef5d477/apps/meteor/app/api/server/v1/groups.js#L638

**Comment by iKnowJavaScript** [comment]
@dudanogueira missed that the endpoint doesn't support Query.
Weird one.

I will close this. Thanks.
