### ISSUE TITLE
Jump to first unread message doesn't work

### ISSUE THREAD

**Issue by netdevfighter** [RocketChat/Rocket.Chat#2685]
![rocketchatfirstunread](https://cloud.githubusercontent.com/assets/4456399/14106535/0b86f386-f5b2-11e5-8fb6-191d65a42318.png)

After clicking on "JUMP TO FIRST unread" is nothing happens ...  No move on the scroll bar. Can you have a look on this?

Your Rocket.Chat version: demo chat

**Comment by engelgabriel** [comment]
I had the same problem today.

**Comment by engelgabriel** [comment]
Is this happening to anyone else on the @RocketChat/core ?
