### ISSUE TITLE
Image Download in Windows Client broken?

### ISSUE THREAD

**Issue by blubbi321** [RocketChat/Rocket.Chat#2686]
Hey everybody,

could not find this issue via searching so here we go:

I cannot seem to download images in the windows app by clicking the blue link above the image. The functionality works flawlessly in a browser though.

Rocket.Chat version: 0.22.0

**Comment by andreas-bulling** [comment]
maybe related to #2579?

**Comment by blubbi321** [comment]
Sound like it. Sorry, was not looking for mac issues. Will try to upgrade and report back. Thanks for the quick reply!

**Comment by andreas-bulling** [comment]
the new version shows a download button next to the title.

**Comment by engelgabriel** [comment]
please upgrade your server to version 0.24.0 and your desktop app to 1.2 and reopen this issue if the problem persists.

**Comment by blubbi321** [comment]
Upgrade with the additional button solved the issue :)
