### ISSUE TITLE
Global 'Also send to channel' admin switch does not change the default setting for users

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#26861]
### Description:

This is partly related to earlier design decision discussed at https://github.com/RocketChat/Rocket.Chat/issues/26651

As a consequence of change of visibility options in the thread messages we chose to enforce `Also send to channel` switch `on` for all our users. This was to get some predictability into how the messages are shown on the channels in general. (So someone who chose the option to always send messages to the main channel does not look like they were discussing in the thread alone for those not following the thread.)

However, in RC 5.1.2 setting the user default in admin option `Allow users to select the Also send to channel behavior: Always` does not activate for users at all.

![Screenshot from 2022-09-13 18-44-56](https://user-images.githubusercontent.com/6958942/189947146-9ec4a570-0387-4592-b51c-3b4f68562050.png)

### Steps to reproduce:

1. Go to `Admin -> Settings -> Accounts -> Default User Preferences -> Allow users to select the Also send to channel behavior`
2. Select `Always`
3. As a user whose personal settings are set to Default (which is the default in UX), type messages into new and old threads. Use the new template in the user profile (default).

### Expected behavior:

`Also send to channel` check mark should be and stay selected by default in the threads.

### Actual behavior:

The first message in the thread gets the check mark but the subsequent ones do not, and will not be visible on the main channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.2
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Firefox, Chrome latest

**Comment by ankar84** [comment]
Definitely that setting should be managed via Admin UI. I personally plan to set that option to `Never`, so threads always stay separately from main chat until user manually set `Also send to channel` check mark.

**Comment by IKrendelev** [comment]
> Definitely that setting should be managed via Admin UI. I personally plan to set that option to `Never`, so threads always stay separately from main chat until user manually set `Also send to channel` check mark.

At some moment in the past I had to patch `app.js` RC source file to set `message.tshow` parameter of validateMessage function to always be `false` (like "Also send to chat" is always unchecked).

**Comment by Gummikavalier** [comment]
I think this issue of setting not sticking for users has been fixed by the RC 5.4.0. Closing.

Caveat: If you change this your users need to do refresh of their client/browser window for the new setting to become active.
