### ISSUE TITLE
The new message template cannot resolve pointer usernames that contain @ character

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#26869]
### Description:

The new message template cannot "resolve" user names in the message pointers should they contain @ character in the target's username.

Especially the systems that use emails as their main username attribute suffer from the issue. Also those Oauth enabled instances that get the user names in format such as `username@example.com`.

In this issue example the username is called `099fnd2ee@example.com`. The real name is `Test Account`.

### Steps to reproduce:

1. Set RC to user real names by default under `Layout -> User Interface -> Use Real Name`
2.  Create account with username that contains @ character. Set the name and email separately to something else.
3. Send a message to the user that has @ character in their username

### Expected behavior:

The pointer string should show the real name (Test Account) and also have it highlighted.

### Actual behavior:

The username is shown instead of the real name and it is not highlighted.

![Screenshot from 2022-09-14 15-25-14](https://user-images.githubusercontent.com/6958942/190154469-9bab7bb5-eaec-4257-b76e-2762dd4f1c0d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.2
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Any browser

**Comment by hugocostadev** [comment]
Hi @Gummikavalier , thanks for your concern.

Let me ask you a question, do you even got it to create a username with an email pattern? 
When I tried to replicate this issue I got an error: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/20212776/192774559-a94fefac-0b01-49fd-8ac7-f4b6f6f7c89f.png">

**Comment by Gummikavalier** [comment]
@hugocostadev Yes. In our case the usernames get created by Oauth provisioning and we also have allowed @ character in the UTF-8 slugify options. Like this:

```
Admin -> General -> UTF8

On both validation fields string: [0-9a-zA-Z-_.@-]+

UTF8 Names Slugify 'on'
```

Sorry that I forgot to add that into the original issue.

**Comment by hugocostadev** [comment]
Got it @Gummikavalier ! Thank you for your feedback, I'll address this issue internally!

**Comment by Gummikavalier** [comment]
Confirmed working on RC 5.4.0. :heart:
