### ISSUE TITLE
Emoji as avatar does not show correctly

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#2687]
![rc_emoji](https://cloud.githubusercontent.com/assets/8321589/14110238/998fdd0c-f600-11e5-937f-36a716850c77.png)

Solution is:
```.avatar .emojione{
  width: 100%;
}```
in custom css.
`Rocket.Chat version: (0.24)`

**Comment by engelgabriel** [comment]
Thanks @vetash, @sampaiodiego will fix this.
