### ISSUE TITLE
Omnichannel > Contact Chat History not working (after upgrading to version 5)

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat#26878]
### Description:

As a LiveChat Agent, the option "Contact Chat History" (clock icon) is not displaying the history of the visitor_id

I tried with the API REST endpoint (https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/omnichannel-endpoints/omnichannel-visitors/get-livechat-visitors-chat-history) for the same visitor_id and the same room_id and the history is there! so the problem is something related with the UI experience 

1. take a new incoming omnichannel inquiry
2. click the Contact Chat History icon
3. the history for the visitor_id is not retrieved

### Expected behavior:

The history for the visitor_id is not retrieved (as the API endpoint does)

### Actual behavior:

The history for the visitor_id is not retrieved

### Server Setup Information:

- Version of Rocket.Chat Server:  5.1.2
- Operating System:  Ubuntu 20.04
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog:  Enabled
- NodeJS Version:  v14.19.3
- MongoDB Version: 4.4.16 / wiredTiger (oplog Enabled)

### Client Setup Information

- Browser Version: Google Chrome
- Operating System: macOS

**Comment by dudanogueira** [comment]
Hi!

While I was able to reproduce this in 5.1.2, on latest code (develop branch) I was not.

Can you try this functionality on a staging environment with develop code? We have a always updated [docker tag for develop branch here](https://hub.docker.com/r/rocketchat/rocket.chat/tags?page=1&name=develop)

**Comment by dudanogueira** [comment]
too soon. I kind of reproduced it on latest codebase.

There is indeed something going on here.

**Comment by didacroyo** [comment]
Hi duda, after migrating to develop the issue seems to be resolved!
Tomorrow with production load the users will confirm. Any new input I'll let you know!
Thanks a lot!
