### ISSUE TITLE
Rocket Chat 5.0.7 tar file missing from https://cdn-download.rocket.chat/build/

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#26879]
### Description:

Rocket Chat 5.0.7 tgz file (released on 9/12/2022 with a security hotfix) is missing from https://cdn-download.rocket.chat/build/ server.

### Steps to reproduce:

1. Run "wget https://cdn-download.rocket.chat/build/rocket.chat-5.0.7.tgz"
2. Get 404 Not Found Error
3. Panic!

### Expected behavior:

I should be able to download the file so that I can install it and upgrade from 5.0.6

### Actual behavior:

![image](https://user-images.githubusercontent.com/6833993/190421863-96f12a2c-af57-48e6-96e1-202cc20a37c7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.6
- Operating System: Red Hat Linux 8
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 4.19.3
- MongoDB Version: 4.2

**Comment by florisvangeel** [comment]
Thanks for the notification, you can find the releases [here](https://github.com/RocketChat/Rocket.Chat/releases) in both tar.gz as zip format including the latest version.

**Comment by mddvul22** [comment]
Thanks @florisvangeel but that does not appear to be the same type of package.  The tar.gz files you are mentioning appear to be complete source code releases.  The file I'm trying to download, after you untar it, has one folder in it, called "bundle", and everything is inside that folder.  These appear to be two different things.

**Comment by Vaarlion** [comment]
Funny enough ... https://releases.rocket.chat/5.0.7/download return https://cdn-download.rocket.chat/build/rocket.chat-5.0.6.tgz?6debca4f134f774406b979780767ebb1-26

And https://releases.rocket.chat/5.0.8/download don't work so it's not a "is not found get last version" type of issue ...
Who slipped ? and why is it not automated :sweat_smile:
