### ISSUE TITLE
UI and Addons

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2688]
Given using rocket chat in i-frame is not totally recommended specially if you use SSL and you don have that enabled for your main website, i suggest we make use of the real-estate available - i know this wa mentioned before but here are some more suggestions.. 
having ability to add icons for site menu, or widgets, or even pod-cast player, youtube channel, this can goes up and down - sounds too dreamy but wonder if this is possible? 

Left hand Side BAR:

![image](https://cloud.githubusercontent.com/assets/12454319/14111142/90f1f144-f597-11e5-8829-e1379a3497ac.png)

**Comment by engelgabriel** [comment]
This is possible and even planned to some extent.

**Comment by IQ2022** [comment]
:+1: :100: ROCKET chat has Rocket team :) very happy to hear that @engelgabriel

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for now due to a lack of activity on it. Feel free to open a PR if this is something you're working on though :)
