### ISSUE TITLE
Could not build from source code

### ISSUE THREAD

**Issue by cuongnn-smartosc** [RocketChat/Rocket.Chat#26887]
### Description:

I tried to build and package the Rocket.Chat from  the source code but it was failed. Can someone guide me how to build and package from the source?

### Steps to reproduce:

1. Checkout code from master branch
2. Execute `apps/meteor/.example-build-run.sh`
3. Show error at  `meteor npm install`

`meteor npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
`

### Expected behavior:

Can be build successfully

### Actual behavior:

`meteor npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
`

### Client Setup Information

- Operating System: MacOS Intel
- Node: v14.19.3
- NPM: 6.14.17

### Additional context

I also try to run the following at the project root
`yarn build`

but it also shows error 

`
✦ ➜ yarn build
• Packages in scope: @rocket.chat/agenda, @rocket.chat/api-client, @rocket.chat/cas-validate, @rocket.chat/core-typings, @rocket.chat/ddp-streamer, @rocket.chat/eslint-config, @rocket.chat/favicon, @rocket.chat/fuselage-ui-kit, @rocket.chat/gazzodown, @rocket.chat/livechat, @rocket.chat/meteor, @rocket.chat/model-typings, @rocket.chat/models, @rocket.chat/poplib, @rocket.chat/rest-typings, @rocket.chat/ui-client, @rocket.chat/ui-contexts, @rocket.chat/ui-video-conf, rocketchat-services
• Running build in 19 packages
@rocket.chat/livechat:build: cache miss, executing cc58e43558c4185e
@rocket.chat/fuselage-ui-kit:build: cache miss, executing f56ee155b77ae424
@rocket.chat/favicon:build: cache hit, replaying output ba2f3fc164672497
@rocket.chat/cas-validate:build: cache hit, replaying output d05c93f0a8ec3b38
@rocket.chat/agenda:build: cache hit, replaying output 36fef81fc2678f4b
@rocket.chat/ui-video-conf:build: cache hit, replaying output 9b2b49d16e37d5e4
@rocket.chat/core-typings:build: cache hit, replaying output da4735731d585ef8
@rocket.chat/model-typings:build: cache hit, replaying output a5df5c47241d8d52
@rocket.chat/models:build: cache hit, replaying output 9f683c39679b033b
@rocket.chat/rest-typings:build: cache hit, replaying output 4a92c6c91bf7c309
@rocket.chat/ui-contexts:build: cache bypass, force executing 4cdc856ba3fe1ba3
rocketchat-services:build: cache miss, executing 7ab7dc325802051d
@rocket.chat/api-client:build: cache hit, replaying output 0d19392212e50df7
@rocket.chat/ui-client:build: cache miss, executing e6e2e4316e9c89bb
@rocket.chat/ddp-streamer:build: cache miss, executing 71a5803ddc0c0ed7
@rocket.chat/fuselage-ui-kit:build: src/surfaces/createSurfaceRenderer.tsx(17,8): error TS2786: 'SurfaceComponent' cannot be used as a JSX component.
@rocket.chat/fuselage-ui-kit:build:   Its element type 'ReactElement<any, any> | Component<{}, any, any> | null' is not a valid JSX element.
@rocket.chat/fuselage-ui-kit:build:     Type 'Component<{}, any, any>' is not assignable to type 'Element | ElementClass | null'.
@rocket.chat/fuselage-ui-kit:build:       Type 'Component<{}, any, any>' is not assignable to type 'ElementClass'.
@rocket.chat/fuselage-ui-kit:build:         The types returned by 'render()' are incompatible between these types.
@rocket.chat/fuselage-ui-kit:build:           Type 'React.ReactNode' is not assignable to type 'import("/Users/cuongnguyen/Documents/github/smart-chat-server/node_modules/@types/meteor/node_modules/@types/react/index").ReactNode'.
@rocket.chat/fuselage-ui-kit:build:             Type '{}' is not assignable to type 'ReactNode'.
@rocket.chat/fuselage-ui-kit:build:               Type '{}' is missing the following properties from type 'ReactPortal': key, children, type, props
@rocket.chat/fuselage-ui-kit:build: ERROR: ".:build:esm" exited with 1.
@rocket.chat/fuselage-ui-kit:build: ERROR: command finished with error: command (packages/fuselage-ui-kit) yarn run build exited (1)
@rocket.chat/gazzodown:build: cache miss, executing c3ba56bb6c01f29f
command (packages/fuselage-ui-kit) yarn run build exited (1)
`

but the `yarn dev` still can be run successfully

**Comment by dudanogueira** [comment]
Hi! This is not a bug :confused: 

If you want to run de development environment - and specially on a mac - please, check out this channel where the mac developers hang out:
https://open.rocket.chat/channel/working-on-linux-or-mac

Also, please, check out this doc on how to get started on mac environment:
https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx
