### ISSUE TITLE
Message rendering of links containing : is still broken 

### ISSUE THREAD

**Issue by saschafoerster** [RocketChat/Rocket.Chat#26889]
We use Google Alert for monitoring. 
With version 5.0 we had problems with this links not being rendered at all, instead we saw emojis. 

Now, after updating to 5.2.1 we don't see the emoji anymore, but the link is not clickable to the full length. it goes to the second ... &url=https and stops here ://ga.

<img width="484" alt="Bildschirmfoto 2022-09-15 um 11 23 20" src="https://user-images.githubusercontent.com/1153741/190576349-63f80791-5a13-43ac-9503-2e5a11082dbd.png">

To reproduce: 

Share this links in RocketChat: 

https://www.google.com/url?rct=j&sa=t&url=https://ga.de/freizeit/region-erleben/bonn-und-region-tipps-fuers-wochenende-flohmarkt-rheinaue-weltkindertag-stadtfest_aid-53876987&ct=ga&cd=CAIyHDQ0NzEyYWE3MDA1MGNhNTQ6Y29tOmRlOkRFOlI&usg=AOvVaw3ySYrO9lM0iNSnk43gPVwZ

Only this part will be clickable: 

https://www.google.com/url?rct=j&sa=t&url=https

**Comment by saschafoerster** [comment]
@engelgabriel Another issue for the tag subj:message-rendering

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing it out!

**Comment by sandeep13122002** [comment]
> Hi! Thanks for pointing it out!

I want to contribute to this repository,I am a newbie in opensource

**Comment by hugocostadev** [comment]
It was already fixed and there is already a Release Candidate. Soon we will be released the official Release.
