### ISSUE TITLE
Livechat Realtime API: livechat:getInitialData method not found

### ISSUE THREAD

**Issue by Elintondm** [RocketChat/Rocket.Chat#26899]
After update RC to 5.0.4 the Realtime API method is gone: livechat:getInitialData

Logs:

```Send message failed: {"isClientSafe":true,"error":404.0,"reason":"Method \u0027livechat:getInitialData\u0027 not found","message":"Method \u0027livechat:getInitialData\u0027 not found [404]","errorType":"Meteor.Error"}```

**Comment by sampaiodiego** [comment]
it was removed with breaking changes on 5.0: https://github.com/RocketChat/Rocket.Chat/pull/25889

cc @KevLehman @murtaza98

**Comment by Elintondm** [comment]
Thanks!!!

We use this method of Realtime API to see if the given client is already with an open chat and to discover the current chat department. 

Please how to discover these things using realtime API now?

**Comment by Elintondm** [comment]
Is it possible to downgrade the RC version of a cloud version?

**Comment by murtaza98** [comment]
> Thanks!!!
> 
> We use this method of Realtime API to see if the given client is already with an open chat and to discover the current chat department.
> 
> Please how to discover these things using realtime API now?

Hi @Elintondm Can you check if any of these endpoints fit your use-case
1. [/livechat/room](https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/livechat-endpoints/livechat-room/livechat-room-info) - This allows you to query a single room using visitor's token & from that response you should get the corresponding department ID
2. [/livechat/rooms](https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/omnichannel-endpoints/rooms/livechat-rooms-list) - This is a bit more flexible API which is designed for livechat managers who can query using multiple filters. So you can use it to query open rooms from specific departments

**Comment by murtaza98** [comment]
> Is it possible to downgrade the RC version of a cloud version?

I'm not really sure about this. Can you please reach out to the support team to check about SaaS https://desk.rocket.chat
