### ISSUE TITLE
Import history from plain text file

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2689]
Your Rocket.Chat version: 0.24.0
Is there a way to import history from plain textfile with simple format "date;member;text" ? I can import my history into the mongodb table **rocketchat_message** directly, but I cant regenerate the previews for urls and documents...

**Comment by engelgabriel** [comment]
It can be done, @geekgonecrazy has created a import framework that you should be able to adapt to use any file format. Do you want to collaborate to create a PR for plain text file?

**Comment by geekgonecrazy** [comment]
@graywolf336 built most of it out with the slack plugin.  :smile:

@zxweed would csv be an acceptable format to use? It's just Comma Separated Values so very similiar to what you describe, and would potentially be more universal.

**Comment by zxweed** [comment]
Yes, csv is the acceptable format to use - I can convert my history to it and then import. Generally, I need only "datetime", "member" and "message" fields.

**Comment by geekgonecrazy** [comment]
@zxweed so this would only be message details?  Would all the users already be created then require a mapping maybe via the UI?

**Comment by zxweed** [comment]
@geekgonecrazy, according to my experiments with table **rocketchat_message**, users does not need to be created before import, the link with message uses the username as key, not the userid. So I can import the users after messages.

**Comment by geekgonecrazy** [comment]
@zxweed as part of our import framework we actually insert the message so that it'll be fully processed by the stack.  This way things like mentions will be properly associated with users. So as for an import process we'd want to import users and then messages.  This is fairly easy with our import framework.

**Comment by zxweed** [comment]
ok, @geekgonecrazy, how can I use this import framework?

**Comment by dbushong** [comment]
I've got a ton of IRC logs to import, so something like this would be super; if it doesn't exist I'll end up writing it - does any code exist yet?

**Comment by graywolf336** [comment]
This will be possible with the pull request #4945
