### ISSUE TITLE
Backslashes in messages don't show without escaping

### ISSUE THREAD

**Issue by oyxnaut** [RocketChat/Rocket.Chat#26907]
### Description:

Unescaped backslashes are removed from messages, _unless_ there is no other character after the \.

### Steps to reproduce:

1. Write `\a`
2. Write `\\a`
3. Write `\`
5. Write `\\`

Note: This needs to be a "normal" message. Inside backticks, a single backslash doesn't disappear.

### Expected behavior:

The messages should read:
1. `\a`
2. `\\a`
3. `\`
4. `\\`

### Actual behavior:

The messages read:
1. `a`
2. `\a`
3. `\`
4. `\`

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.2
- Operating System: Ubuntu 20.04
- Deployment Method: Official Docker image
- Number of Running Instances: 3
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.12

### Client Setup Information

- Desktop App or Browser Version: Chromium 105.0.5195.125
- Operating System: Arch Linux

**Comment by cctvccav** [comment]
I meet the same problem.

**Comment by toomaslepik** [comment]
We have same problem!
server  Rocket.Chat: 5.1.3

**Comment by paulchen** [comment]
@toomaslepik please see https://github.com/RocketChat/Rocket.Chat/issues/26799 for the problem regarding missing colons in timestamps

**Comment by als999** [comment]
In threads, all backslashes are displayed. The bug is only in the main chat window.
