### ISSUE TITLE
Rocketchat aws deployment error

### ISSUE THREAD

**Issue by wahdatjan** [RocketChat/Rocket.Chat#26913]
Tried 21 times. Waiting 5 secs...
rocketchat_1          | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1          | 						throw(ex);
rocketchat_1          | 						^
rocketchat_1          | 
rocketchat_1          | MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
rocketchat_1          |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)

**Comment by dudanogueira** [comment]
Hi! Please, follow the issue template so we can help you.

By the look of this log, rocketchat doesn't seems to be able to reach for the mongo.

Please, check this doc before opening an issue:
https://docs.rocket.chat/getting-support/community-resources

Thanks!
