### ISSUE TITLE
Want to add different language in livechat rocketchat

### ISSUE THREAD

**Issue by binodyadav6119** [RocketChat/Rocket.Chat#26933]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by binodyadav6119** [comment]
I want different language other than english while chatting in livechat. How to achieve?

**Comment by rajanshresth** [comment]
I want to work on this issue.. 
Can you assign me this issue?

**Comment by dudanogueira** [comment]
hi @binodyadav6119 You can change the Widget language by using it's API.

Check here for more on that:
https://developer.rocket.chat/reference/api/livechat-api#set-language-for-widget

The supported languages, as of today, lives here (the link is outdated in doc after the monorepo change, it should be fixed soon):
https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/livechat/src/i18n

I will close this for now, let me know if this helps you. 
Thanks!
