### ISSUE TITLE
[IOS - Safari, Chrome] Cannot enter chat room

### ISSUE THREAD

**Issue by minemos** [RocketChat/Rocket.Chat#26943]
### Description:

On Iphone cannot enter chat room (only mobile)
Android is fine

### Steps to reproduce:

1. Go to direct room list
2. Click room to enter
3. Come back to list or show blank screen

### Expected behavior:

1. Go to direct room list
2. Click room to enter
3. Show room

### Actual behavior:

https://user-images.githubusercontent.com/24834933/192118023-f3faa11c-b955-4010-ac70-35e80d7bf3f3.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.0-develop
- Operating System: Ubuntu
- Deployment Method: yarn start
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version: 4.4.4

```
"@rocket.chat/apps-engine": "^1.31.0",
"@rocket.chat/css-in-js": "~0.31.9",
"@rocket.chat/emitter": "~0.31.9",
"@rocket.chat/fuselage": "0.32.0-dev.9",
"@rocket.chat/fuselage-hooks": "~0.31.9",
"@rocket.chat/fuselage-polyfills": "~0.31.9",
"@rocket.chat/fuselage-tokens": "~0.31.9",
"@rocket.chat/fuselage-ui-kit": "~0.31.9",
"@rocket.chat/icons": "~0.31.9",
"@rocket.chat/logo": "~0.31.9",
"@rocket.chat/memo": "~0.31.9",
"@rocket.chat/message-parser": "~0.31.9",
"@rocket.chat/mp3-encoder": "^0.24.0",
"@rocket.chat/onboarding-ui": "next",
"@rocket.chat/string-helpers": "~0.31.9",
"@rocket.chat/ui-kit": "~0.31.9",
"mongodb": "^3.6.10",
"mongodb-memory-server": "^7.4.1",
```

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: IOS chrome, safari

### Relevant logs:

No logs

**Comment by dudanogueira** [comment]
Hi!

Have you tried this in latest 5.1.3 version? Did you get the same outcome?
