### ISSUE TITLE
According to the official guide, the server hangs up after the lateste update

### ISSUE THREAD

**Issue by avenger2005** [RocketChat/Rocket.Chat#26946]
docker pull registry.rocket.chat/rocketchat/rocket.chat:latest 
docker-compose stop rocketchat 
docker-compose rm rocketchat 
docker-compose up -d rocketchat

https://docs.rocket.chat/quick-start/upgrading-rocket.chat

**Comment by sandeep13122002** [comment]
I want to work on this issue can you assgin me?

**Comment by dudanogueira** [comment]
Hi! We will need more details on whats going on here.

But this is not a software issue, but a deployment issue

Please, check out this community resources before opening an issue and how to get proper help:
https://docs.rocket.chat/getting-support/community-resources

Also, state what version you are upgrading to and try to get more logs with relevant errors:
docker-compose logs

Bear in mind about newer Rocket.Chat versions (5.X+) require some changes in the previous provided docker compose file.
We have covered those changes here: https://www.youtube.com/watch?v=8DeBQsfe2rU&ab_channel=Rocket.Chat

From:
https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0

> If you're using MongoDB in a Docker container, you might need to add directConnection=true to MONGO_URL and MONGO_OPLOG_URL environment variables. i.e.: MONGO_URL=mongodb://mongo/rocketchat?replicaSet=rs0&directConnection=true

I will be closing for now. Thanks!
