### ISSUE TITLE
D: becomes :fearfulc:

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#26942]
### Description:

When typing `D:` in a chat, this part of the message is rendered as `:fearfulc:`.

### Steps to reproduce:

1. Type `D:`.

### Expected behavior:

The text is rendered as `D:`.

### Actual behavior:

The text is rendered as `:fearfulc:`.

![image](https://user-images.githubusercontent.com/404840/192109681-a093bef3-e4a8-420e-b04d-4e4fe5f30402.png)

In edit mode:

![image](https://user-images.githubusercontent.com/404840/192109687-1c0c3a05-be24-4892-be89-7c7f24fad052.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.3
- Operating System: Debian GNU/Linux 11.5
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.12 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chromium 105.0.5195.125 (Offizieller Build) Arch Linux (64-Bit), Firefox 105.0 (64-bit), but should be observable in any browser.
- Operating System: Arch Linux

### Additional context

This problem was already mentioned in a comment to another issue which has been closed in the meantime: https://github.com/RocketChat/Rocket.Chat/issues/26485#issuecomment-1222191442

The problem can be observed in the app as well:

![image](https://user-images.githubusercontent.com/404840/192109806-a7121763-295e-4469-a9c7-b32055e21e4f.png)

In the channel list it is even rendered as an emoji:

![image](https://user-images.githubusercontent.com/404840/192109812-de5ab9a0-f3cb-4256-920c-baea92f8fc3d.png)

**Comment by dudanogueira** [comment]
[I think I found the mistype](https://github.com/RocketChat/fuselage/blob/dc71a45cf8c5d9945a54e765c3c8632c7feb8c5d/packages/message-parser/src/grammar.pegjs#L611). it should be translated to `:fearfull:` or :fearful: 

Nice catch, @paulchen!  Thanks!
