### ISSUE TITLE
Video calls not keeping track of existing members and session

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#2694]
When you start a group call it frequently has issues establishing connections to the existing guests.

Often prompting existing participants to join a call when a new person tries to join.

**Comment by engelgabriel** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/933

**Comment by amitmeyraz** [comment]
hi, 
is it will be fix at 0.25? no video or audio :(

**Comment by MartinSchoeler** [comment]
@geekgonecrazy is this still an issue?

**Comment by geekgonecrazy** [comment]
It's likely hit and miss. Let's go ahead and close
