### ISSUE TITLE
Erro ao carregar imagens após atualização

### ISSUE THREAD

**Issue by diegocarlesso** [RocketChat/Rocket.Chat#26959]
![image](https://user-images.githubusercontent.com/75617157/192592491-41044f1f-70ef-45a0-9f0b-e436b98a2065.png)
Hoje, após atualizar o RocketChat para a última versão disponível, as imagens enviadas e recebidas diretamente no programa não carregam.

**Comment by dudanogueira** [comment]
Oi!

Em geral este erro aparece quando a url do Rocket.Chat está errada, em ADMIN > SETTINGS > GENERAL > SITE URL

Por favor, preenche o template para abrir uma nova issue e leia esta doc antes de abrir um issue:
https://docs.rocket.chat/getting-support/community-resources
