### ISSUE TITLE
Real Name is not used in message headers when viewing on mobile browsers

### ISSUE THREAD

**Issue by TedsCabin** [RocketChat/Rocket.Chat#26967]
### Description:

Message headers do not follow the UI_Use_Real_Name setting when on mobile browser (<768px width), therefore only usernames are shown on mobile.  If the goal is to reduce the width

### Steps to reproduce:

1. Set server setting `Use Real Name` to `Enabled`
2. Use a browser with a width <768px
3. All message headers will now use the username

### Expected behavior:

Message headers should show real name, which is how it worked <v5

### Actual behavior:

All message headers show the username instead of real name

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.3
- Operating System:  Ubuntu 20.04.5
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.7

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows/Android/iPhone

browser width >=768px
![image](https://user-images.githubusercontent.com/104330064/192762239-93094c71-b3ba-43cb-b063-73b4e6c87d2e.png)

browser width <768px
![image](https://user-images.githubusercontent.com/104330064/192762346-71c19bec-3c02-4afd-b715-3c063104aca4.png)

**Comment by dudanogueira** [comment]
Thanks for pointing out the issue **AND** sending the PR 
:heart:
