### ISSUE TITLE
Customization from web app not showing on mobile

### ISSUE THREAD

**Issue by melakhvision** [RocketChat/Rocket.Chat#26991]
Hello,

I have added some customization on the web app but they are not showing on the mobile app version.

Where can we make customization for the mobile app version

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  Ubuntu 20.4
- Deployment Method: Docker 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi!
They are different codebases.

The Mobile App is a App itself that consumes the server APIs. 

Here you have the code for the mobile app:
https://github.com/RocketChat/Rocket.Chat.ReactNative
