### ISSUE TITLE
Native iOS Application

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#270]
We need to start working on this to get a ALPHA version as soon as possible.

Some ideas on https://github.com/danielfbm/meteor-cordova-web-example are very interesintg.

From https://forums.meteor.com/t/different-interfaces-based-on-devices/264/19

**Comment by greentornado** [comment]
I can try to ake one in Appcelerator

**Comment by hexrain** [comment]
Based on some experience with Cordova I can't recommend this approach. 
I'm yet to become familiar with Meteor so correct me if I'm wrong – Meteor's build on DDP, right? There's an iOS library out there - https://github.com/alansikora/objective-c_ddp-client.
It should be possible to create a native app without JS.

**Comment by rodrigok** [comment]
@hexrain yes, it's possible. I already did an native iOS app with Meteor.

**Comment by engelgabriel** [comment]
@hexrain we will do the Cordova first, and leave the full native for later, and probably keep both.

**Comment by ArjunRajJain** [comment]
thoughts on using something like famo.us for the rendering?

**Comment by engelgabriel** [comment]
The Rocket.Chat Native iOS Application project has started. https://github.com/RocketChat/Rocket.Chat.iOS
Who wants to join in? The plan is to use Swift.

**Comment by engelgabriel** [comment]
Hey folks, we are testing our hybrid app for iOS, if you want to test the application please send me your email (apple id) to support at rocket.chat with subject *ios-app* and we will add your email to our testflight.

**Comment by davidalzate** [comment]
how can I config the app to use my own host and not the demo one?

**Comment by alexschomb** [comment]
I just asked myself the same question. I suspect you can't use BYOS with the AppStore version of Rocket.Chat, yet. Though, it might be possible to build your own iOS version from source with Xcode and upload it to your iDevice with iTunes. (not tested by me)
