### ISSUE TITLE
Navbar Issue

### ISSUE THREAD

**Issue by Znoy108x** [RocketChat/Rocket.Chat#27007]
i can solve the navbar issue .

**Comment by arjunlubana** [comment]
What's the issue? Please elaborate?

**Comment by Znoy108x** [comment]
![image](https://user-images.githubusercontent.com/75539409/194202623-9db1f6dd-03c6-4ac1-81f5-76922b89455a.png)
![image](https://user-images.githubusercontent.com/75539409/194202731-fe711096-206f-4de1-bc75-10995787b5c8.png)

The navbar is visible all the time after clicking it 
and if the user wants to remove it then he had to click the outside the navbar dropdown list 
what i can do is i can make it completly work on hover !!
as the person hovers on the navbar then the dropdown will be visible and when the person moves cursor out of the  drop down it will automatically dissapears !!
