### ISSUE TITLE
Deleting user doesn't delete messages

### ISSUE THREAD

**Issue by dandv** [RocketChat/Rocket.Chat#2700]
0.21.0, commit hash ...dac592
1. Log in as user X and leave some messages in #general
2. In a different tab, log in as an admin and delete user X. Notice the warning dialog saying that the user's messages will be deleted.

A third user who was watching #general reports that user X's messages are still there. Hard reloading the page no longer shows the deleted user's messages.
When I wanted to join #general as the admin user, the preview mode still showed the messages.

Possibly related: #1149, #739

**Comment by engelgabriel** [comment]
We dont send the "remove" message for each deleted message on this event, as it may be a lot of traffic. We could maybe send the delete user event to all logged users, so they can delete the messaged on the client.

**Comment by engelgabriel** [comment]
It would be something similar to the UPDATE AVATAR :)

**Comment by andreas-bulling** [comment]
I am not sure I understand the logic behind this - why delete all messages of a deleted user at all/by default? Couldn't it be that some messages the user posted are still of value to others even if the user himself is not active any more? I would at least leave the decision to also delete all messages to the admin so he can do this on a case-by-case basis.

**Comment by dytec** [comment]
@andreas-bulling +1

**Comment by engelgabriel** [comment]
In that case you should not DELETE the user, but just deactivate instead. If you REALLY want to delete the user record, we have to delete related references to keep DB integrity.

**Comment by andreas-bulling** [comment]
@engelgabriel that makes sense. What does DEACTIVATE involve - the user is not able to login anymore etc?

**Comment by engelgabriel** [comment]
Yes, the user looses access completely.

**Comment by imtrobin** [comment]
When the user is deactivated, we can still find them on the member list, is there option to not show them?

**Comment by Hudell** [comment]
PR #9947 adds the option to delete an user without removing their messages.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/6535

**Comment by vynmera** [comment]
This will be implemented in #11236 :)
