### ISSUE TITLE
migration v231 fails after 2022-09-27

### ISSUE THREAD

**Issue by fuminori-ido-m** [RocketChat/Rocket.Chat#27014]
### Description:

migration v231 fails after 2022-09-27

#### Comment

I guess [the migration](https://github.com/RocketChat/Rocket.Chat/blob/4.5.7/server/startup/migrations/v231.ts) set 2022-09-27 as expiration datetime and it causes validation error of LDAPBanner model, this leads migration of v231 fails.

I am not sure why this expireAt is really needed or not.  The workaround is to disable all of LDAP, SAML, and CustomOauth and pass this migration step.  I hope some NOTE regarding this in upgrade-document.

### Steps to reproduce:

1. prepare rocketchat < ver.3.18.0
2. try to update to any versin in 3.18.x .. 4.x

### Expected behavior:

migration completed and rocketchat runs

### Actual behavior:

migration fails with the following message:

>       |                         ERROR! SERVER STOPPED                        |
>       |                                                                      |
>       |                    Your database migration failed:                   |
>       |              Start date cannot be later than expire date             |

### Server Setup Information:

- Version of Rocket.Chat Server:  3.0.13
- Operating System: Debian 9 (stretch) ( [docker image 3.0.13](https://hub.docker.com/layers/rocketchat/rocket.chat/3.0.13/images/sha256-22692a236db7152c1314868adf12fc64dddc8ba234233cd4739ffa4b230580c8?context=explore) )
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  ?
- NodeJS Version: v12.14.0
- MongoDB Version: 3.6.23

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

### Relevant logs:

> ...
> {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 230","time":{"$date":1664857383316},"level":"info"}
> {"line":"120","file":"migrations.js","message":"Migrations: Running up() on version 231","time":{"$date":1664857383319},"level":"info"}
> 
> +----------------------------------------------------------------------+
> |                                                                      |
> |                         ERROR! SERVER STOPPED                        |
> |                                                                      |
> |                    Your database migration failed:                   |
> |              Start date cannot be later than expire date             |
> |                                                                      |
> |  Please make sure you are running the latest version and try again.  |
> |           If the problem persists, please contact support.           |
> |                                                                      |
> |                   This Rocket.Chat version: 3.18.2                   |
> |                    Database locked at version: 215                   |
> |                     Database target version: 232                     |
> |                                                                      |
> |           Commit: 03394ccaa516cf36424d4a9f92ac412fed9258f6           |
> |                  Date: Fri Oct 1 18:34:44 2021 -0300                 |
> |                             Branch: HEAD                             |
> |                              Tag: 3.18.2                             |
> |                                                                      |
> +----------------------------------------------------------------------+
> 
> Error: Start date cannot be later than expire date
>     at server/services/banner/service.ts:42:10
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
>  => awaited here:
>     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
>     at server/sdk/lib/LocalBroker.ts:15:15
>     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by fxmanu** [comment]
I'm having the exact same issue.

**Comment by mercy-thuyle** [comment]
Hello @fuminori-ido-m  @fxmanu 
I have the same too, did you solved it?

**Comment by fxmanu** [comment]
> Hello @fuminori-ido-m @fxmanu I have the same too, did you solved it?

@mercy-thuyle as the author of this issue stated, the workaround is, to disabled LDAP, etc...

For me, disabling LDAP, updating and reenabling worked.

**Comment by fuminori-ido-m** [comment]
Hi @mercy-thuyle,   yes, as @fxmanu saied above, and I also mention the workaround at my first post, the following is the workaround:

1. disabling all of LDAP, SAML, and CustomOauth
2. update rocketchat
3. enable them again

(I hope some update of the migration document for this issue).

**Comment by racerxdl** [comment]
And how to disable it when the server doesnt start because of the update? :thinking:

**Comment by PhilippFr** [comment]
> And how to disable it when the server doesnt start because of the update? 🤔

@racerxdl 
What worked for me is setting `"value": false` for the `"_id": "LDAP_Enable"` item in the `rocketchat_settings` collection.

**Comment by racerxdl** [comment]
> > And how to disable it when the server doesnt start because of the update? thinking
> 
> @racerxdl What worked for me is setting `"value": false` for the `"_id": "LDAP_Enable"` item in the `rocketchat_settings` collection.

LDAP wasn't active here, but github, twitter and facebook was. Then I just removed all entries that match with the query in migration:
https://github.com/RocketChat/Rocket.Chat/blob/4.5.7/server/startup/migrations/v231.ts#L17-L19

Funny enough, I didnt had to re-enable anything.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
