### ISSUE TITLE
Docker as root

### ISSUE THREAD

**Issue by francoataffarel** [RocketChat/Rocket.Chat#27010]
Its simple, how can i access docker image from rocket.chat as root?

**Comment by dudanogueira** [comment]
Hi! 

Sorry, This is really not the place to ask this. here is only for issues on software.

Please, take a look on this resources if you are looking for help:
https://docs.rocket.chat/getting-support/community-resources

It is also a good idea to state what you are trying to do.
There should be no reason why you would want that :thinking:

**Comment by francoataffarel** [comment]
So @dudanogueira i want insert some features inside docker
