### ISSUE TITLE
Ability to link to individual messages

### ISSUE THREAD

**Issue by dandv** [RocketChat/Rocket.Chat#2701]
Use case: send someone a link to a specific part of the conversation in a given channel

This can almost be done right now via search (see #946), but the URL should be updated with a permalink to the message, probably based on its `_id`.

Another enhancement would be to have a "link" context menu item next to Star and Reactions:

![image](https://cloud.githubusercontent.com/assets/33569/14128494/28643076-f5d6-11e5-9ace-38a155b5fc48.png)

**Comment by andreas-bulling** [comment]
+1

**Comment by royalaid** [comment]
Just context Slack implaments this by a link that can be copied by right-clicking the timestamp of a message
