### ISSUE TITLE
gray banner at the top of rocketchat window 

### ISSUE THREAD

**Issue by cn0xn** [RocketChat/Rocket.Chat#27028]
### Description:

- After the update rockechat to 5.1.1 new users have a gray banner at the top of the page which cannot be closed. 

### Expected behavior:

- Normal top of window 

### Actual behavior:

![Screenshot 2022-10-06 182315](https://user-images.githubusercontent.com/51883532/194484949-b1fd5883-7c41-4ef7-9224-2ed164fa4d03.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.1

### Client Setup Information

- Desktop , Web

### Additional context

- DevTools

![Screenshot 2022-10-07 094821](https://user-images.githubusercontent.com/51883532/194485165-efe03832-8359-4462-84c3-d8983fb14aa2.png)

**Comment by DevTomilola-OS** [comment]
I would like to work on this, kindly assign to me.

**Comment by prasanthmurugasamy** [comment]
I would like to try and work it on it., can you send me the existing top banner design ?

**Comment by Adityasaini10012001** [comment]
assign this to me

**Comment by sshivam12** [comment]
I would like to work on this issue, kindly assign to me

**Comment by debdutdeb** [comment]
No need to assign, if anyone want to work on it, please go ahead.

**Comment by waseemjeelani** [comment]
> No need to assign, if anyone want to work on it, please go ahead.

@prasanthmurugasamy

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
