### ISSUE TITLE
Problem - than i trying del the file from chat windows

### ISSUE THREAD

**Issue by bobfh** [RocketChat/Rocket.Chat#27021]
### Steps to reproduce:

1. Open chat windows
2. Click on clip
3. Click on del - and after check file is deleted or not

### Expected behavior:

Deleted file
### Actual behavior:

1)
![изображение](https://user-images.githubusercontent.com/88323396/194372786-1d9173ad-fd8f-43e7-a4a3-3fe25ffe2712.png)
2)
![изображение](https://user-images.githubusercontent.com/88323396/194372833-484a333e-1812-4ad7-8669-7c25179b2268.png)
3)
![изображение](https://user-images.githubusercontent.com/88323396/194372883-2ef02b56-13b7-4f59-b199-7589c51a2e8e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: Last
- Operating System:  Linux
### Client Setup Information

- Desktop App or Browser Version: Last Browser Chrome
- Operating System:

**Comment by dudanogueira** [comment]
Hi!

I have tested this on 4.8.6 and 5.2.0-rc.4 and it's working as expected.

Can you state your server version?

**Comment by himpierre** [comment]
I have that problem too with S3 storage for files. Pruning messages works for files too tho. There is a support ticket open for this. We are EE customers.
cheers, t.
