### ISSUE TITLE
Author name of quoted message is set to username instead of real name although "Use Real Name" is turned on

### ISSUE THREAD

**Issue by liv1n9** [RocketChat/Rocket.Chat#27031]
### Description:
Author name of quoted message is still username instead of real name although "Use Real Name" setting is turned on

### Steps to reproduce:

1.  Setup new Rocket.Chat server
2.  Go to Settings > Layout > User Interfaces >  Turn on "Use Real Name"
3.  Create new user and group and join user to group. Send the first message in group and then quote this message

### Expected behavior:
Author name of quoted message is author real name

### Actual behavior:

Author name of quoted message is author's username

![](https://live.staticflickr.com/65535/52411777232_e09c9afee1_o.png)
### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0-rc.4
- Operating System: Ubuntu 18.04.5 LTS
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu 22.04

**Comment by liv1n9** [comment]
The last message stored in MongoDB:
```
{
	"_id" : "jGHwdQKuZrF4T43zo",
	"rid" : "obxfYzJTwTYWv7TPz",
	"msg" : "[ ](http://localhost:5000/group/New-Group?msg=w6ENn72KdFSWkFCe5) This is quote of #1 message",
	"ts" : ISODate("2022-10-08T07:55:31.457Z"),
	"u" : {
		"_id" : "TvT57HguS2KxwhhPo",
		"username" : "22000086",
		"name" : "Tím"
	},
	"_updatedAt" : ISODate("2022-10-08T07:55:31.497Z"),
	"urls" : [
		{
			"url" : "http://localhost:5000/group/New-Group?msg=w6ENn72KdFSWkFCe5",
			"ignoreParse" : true
		}
	],
	"mentions" : [ ],
	"channels" : [ ],
	"md" : [
		{
			"type" : "PARAGRAPH",
			"value" : [
				{
					"type" : "LINK",
					"value" : {
						"src" : {
							"type" : "PLAIN_TEXT",
							"value" : "http://localhost:5000/group/New-Group?msg=w6ENn72KdFSWkFCe5"
						},
						"label" : {
							"type" : "PLAIN_TEXT",
							"value" : " "
						}
					}
				},
				{
					"type" : "PLAIN_TEXT",
					"value" : " This is quote of "
				},
				{
					"type" : "MENTION_CHANNEL",
					"value" : {
						"type" : "PLAIN_TEXT",
						"value" : "1"
					}
				},
				{
					"type" : "PLAIN_TEXT",
					"value" : " message"
				}
			]
		}
	],
	"attachments" : [
		{
			"text" : "This is #1 message",
			"author_name" : "22000086",
			"author_icon" : "/avatar/22000086",
			"message_link" : "http://localhost:5000/group/New-Group?msg=w6ENn72KdFSWkFCe5",
			"attachments" : [ ],
			"ts" : ISODate("2022-10-08T07:55:20.694Z")
		}
	]
}
```

**Comment by dudanogueira** [comment]
I can confirm. Tested with old parser and new parser.

**Comment by dudanogueira** [comment]
Added it to Message Parser project, but not sure if it's rendering, ans the attachment has 22000086 as a value for author_name
:thinking:

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/23051

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
