### ISSUE TITLE
3.18.7 - Custom Fields - DefaultValue not working

### ISSUE THREAD

**Issue by huberte** [RocketChat/Rocket.Chat#27034]
### Steps to reproduce:

1. 

Account --> Register --> Custom Fields

Add the page example : 

`{ "role": { "type": "select", "defaultValue": "student", "options": ["teacher", "student"], "required": true, "modifyRecordField": { "array": true, "field": "roles" } }, "twitter": { "type": "text", "required": true, "minLength": 2, "maxLength": 10 } }`

### Expected behavior:

See student as default

### Actual behavior:

See teacher as default (the first entry)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.7
- Operating System: 
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 3.6 .14

### Client Setup Information

- Desktop App or Browser Version: chromium
- Operating System: ubuntu

**Comment by dudanogueira** [comment]
Hi, thanks for pointing out!

I just tested this on latest candidate 5.2.0-rc.6 and it works as expected.

3.X will only receive security patches. In fact, it already reached the end of life, according to here:
https://docs.rocket.chat/getting-support/enterprise-support

You should consider upgrading.

**Comment by huberte** [comment]
Hi, I did upgrade on 5.0.6

The problem still there. Do you really see the default entry ? I still see teacher on my side
