### ISSUE TITLE
Typing indicator translation flawed

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat#27036]
### Description:

The information about a user typing is passed as text below the message box [(-> Code)](https://github.com/RocketChat/Rocket.Chat/blob/0da143cd1359d5dcd19f5d62df9e27506e2475a2/app/ui-message/client/messageBox/userActionIndicator.html)

However, due to the way it's implemented, the translation is not easily possible: Earlier, there were dedicated texts for each activity, which even had a [gender specific translation](https://github.com/RocketChat/Rocket.Chat/blob/9161223c6b006767f85767b063ab7e96fe6779c2/packages/rocketchat-i18n/i18n/de.i18n.json#L2210) in many languages. Since the verb ("is") and the activity ("typing") is now translated separately, no idiomatic translation is available.

### Steps to reproduce:

1. Set the locale to German
2. make another user send a message to you while having opened the same channel

### Expected behavior:

An idiomatic translation, as it's already been done earlier

### Actual behavior:

In German e. g. "is schreibt", which is just horrific/embarassing

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.3

**Comment by mrsimpson** [comment]
Workaround: A custom translation 
```json
      "is": "ist",
      "are": "sind",
      "typing": "am schreiben",
```

**Comment by paulchen** [comment]
There is already an issue for this problem: https://github.com/RocketChat/Rocket.Chat/issues/23593

There is also work ongoing in order to fix it: https://github.com/RocketChat/Rocket.Chat/pull/27004

**Comment by mrsimpson** [comment]
Thanks for the heads up, @paulchen
Closing in favor of #23593
