### ISSUE TITLE
The latest version can't find rocketchat:ldapjs package, so start up failed, when I execute "npm install ldapjs", the error occured agian, do you know why?

### ISSUE THREAD

**Issue by zb471914758** [RocketChat/Rocket.Chat#2704]
=> Errors prevented startup:                  
   
   While selecting package versions:
   error: Package version not in catalog: rocketchat:ldapjs 1.0.0
   
   While refreshing package catalog to resolve previous errors:
   error: Network error: wss://packages.meteor.com/websocket: UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Comment by engelgabriel** [comment]
Are you building from source or have you downloaded the tar file?

**Comment by zb471914758** [comment]
@engelgabriel, I build from source, but it can't be download automatically

**Comment by geekgonecrazy** [comment]
Please try one of our current releases.  This issue shouldn't occur.
