### ISSUE TITLE
API for sending messages to users?

### ISSUE THREAD

**Issue by jasperla** [RocketChat/Rocket.Chat#2705]
Is it planned to integrate into the API a way to send direct messages to users?
E.g. for setups where public rooms are not an option and instead private groups are used, status bots' only method for communication with certain users would be through direct messages.

**Comment by vetash** [comment]
Use @user instead #chanel
```curl -X POST --data-urlencode "payload={\"channel\": \"@admin\", \"username\": \"Asterisk*\", \"text\": \"test\", \"icon_emoji\": \":asterisk:\"}" $webhooklink```

**Comment by jasperla** [comment]
But that would only work if I setup a webhook for every receiving user (adding multiple users to the "Post to Channel" field gives an error), and keep track of the unique webhook URLs that would thus be produced.

**Comment by vetash** [comment]
No, just change @admin to @another user.

**Comment by jasperla** [comment]
That works perfectly fine. Thanks!

**Comment by ngokylan** [comment]
Hi Vetash, can you give me the example of this variable $webhooklink. Im having trouble in making direct sending msg too. this is the only api syntax that is used to send msg http://chat.server.com/api/rooms/$roomid/send

**Comment by vetash** [comment]
@ngokylan You need to Administration page -> integrations -> create incoming webhook. Then you need to copy Webhook URL into your code. Also on page of IW you can see curl example.

**Comment by ngokylan** [comment]
@vetash Woa, this is amazing. Many thanks to you

**Comment by ngokylan** [comment]
Hi Vetash, How can I implement the client Webhook to link to Rocket.chat and be able to send direct message from user to user? Im quite new in Webhook technology. I previously use Socket.io technology for my current chat application.

**Comment by ngokylan** [comment]
Also, I have some other questions: 

is there anyway that from the client side to keep the connection to the rocket.chat server like socket.io create a websocket connection to the socket.io server and keep the pooling connection to listen to the incoming msgs?


how can we create new user + channel via the API from the rocket.chat server?

when sending a direct message from a user to a user, should we Authenticate or subscribe to the destination channel?

Appreciate your response!

Thanks

**Comment by vetash** [comment]
Hi! @ngokylan 
`How can I implement the client Webhook to link to Rocket.chat and be able to send direct message from user to user?`
I'm sure this is imposible with webhooks.
`is there anyway that from the client side to keep the connection to the rocket.chat server like socket.io create a websocket connection to the socket.io server and keep the pooling connection to listen to the incoming msgs�?` 
I think webhooks is not that you need. Also, as i notice you want to build something like bot? So take a look at <https://github.com/RocketChat/hubot-rocketchat|hubot> 
`how can we create new user + channel via the API from the rocket.chat server?`
Sorry, idk.
`when sending a direct message from a user to a user, should we Authenticate or subscribe to the destination channel?`
Same there - i don't know. You should talk about it with developers in <https://rocket.chat/|demo chat.>
