### ISSUE TITLE
Incorrect display name showing when open PM with user

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#27058]
Hi!

Incorrect display name showing when open PM with user.
In card user have normal display name and in DB. But in PM and in search incorrect.
What it is? Cache on server? Help me please

Thank you advanced

**Comment by dudanogueira** [comment]
Hi! You will need to explain it better, also stating some settings you might have changed.

And follow the Issue template :)

Please, before opening an issue, read thru 
https://docs.rocket.chat/getting-support/community-resources

Tks!
