### ISSUE TITLE
Webhook page does not contain script

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#2706]
![webhook_page](https://cloud.githubusercontent.com/assets/8321589/14142506/2351f096-f6c1-11e5-8f39-4b4c1b29a043.png)

Rocket.Chat version: (0.24)

**Comment by engelgabriel** [comment]
The script is optional. See https://github.com/RocketChat/Rocket.Chat/wiki/WebHook-Scripting

**Comment by vetash** [comment]
Oh, i thought is curl example, sorry. :smile:
