### ISSUE TITLE
Repeated backslashes missing

### ISSUE THREAD

**Issue by ShaunR** [RocketChat/Rocket.Chat#27071]
When you write repeated backslashes only the first is shown and the rest removed.  This happens in both a channel and direct chat. View screenshot below for example of the problem.

Version
5.2.0-rc.6

Apps Engine Version
1.35.0-alpha.46

![image](https://user-images.githubusercontent.com/1671445/195915354-05bfa3a0-73ad-470f-a7cc-2d9792eb48e1.png)

**Comment by ShaunR** [comment]
When you edit the message the slashes show up so they are being stored, they appear to removed during the display process.

**Comment by paulchen** [comment]
I guess this is the same problem as reported in https://github.com/RocketChat/Rocket.Chat/issues/26907. Also, https://github.com/RocketChat/Rocket.Chat/issues/26800 is presumably a symptom of the very same problem.

**Comment by ShaunR** [comment]
Just upgraded from 5.2.0-rc.6 to 5.2.0 and the issue looks to be fixed.

**Comment by ShaunR** [comment]
Sorry, issue is not fixed in 5.2.0

**Comment by dudanogueira** [comment]
Closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/26907

**Comment by magiks-hub** [comment]
Version 5.2.0 issue still exists too...
![image](https://user-images.githubusercontent.com/78742513/199236271-5690f96a-6165-4592-8edc-0934075c9b62.png)
![image](https://user-images.githubusercontent.com/78742513/199236343-9b7211a2-728c-4f5a-a2c2-c805d2f7b1fc.png)

**Comment by magiks-hub** [comment]
> thanks for pointing out, @ShaunR !!! 🤗



> 

Server version 5.3.2 issue with slashes still not fixed...
