### ISSUE TITLE
Mute channel function

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#2707]
If there'll function "mute channel" like in slack it will be great. )

**Comment by jclabaugh** [comment]
put a little thought into this and propose initially something between what R.C has now and what Slack has, there is a happy 'middle-ground'

Do Not Disturb

- ability to mute all notifications (desktop, push/mobile, email, audio) at the application level and/or the individual channel level (public, private, DM)
- Like Slack, provide a simple one-click icon near user's name to mute/un-mute notifications across all. One-click to turn on/off and change to icon to show current state
- Unlike, Slack, initially not add any timeframes for Do Not Disturb

At the channel level in left panel:

- mute icon is visible when a channel is muted so user can quickly see if a channel is muted
- ability to un-mute by clicking that icon

At the channel level in right menu:

- Change Push Notifications to Notifications
- Icon changes if the channel is muted
- Notifications has two sections, one for push notifications (as-is) and a second called 'Do Not Disturb' with a button that allows the user to mute that individual channel

![mute_pt1](https://cloud.githubusercontent.com/assets/14165558/14509159/e87af958-0198-11e6-9f17-4de861399e61.png)
![mute_pt2](https://cloud.githubusercontent.com/assets/14165558/14509161/ea3b9fe0-0198-11e6-96e5-fbb4ec0d980d.png)

**Comment by HoldOffHunger** [comment]
Was this option removed?  I don't see it.  ![whatever](https://user-images.githubusercontent.com/14262061/167889206-db077eb7-5b99-47d6-b8c7-a90cc93f0822.jpg)

**Comment by wadouk** [comment]
@HoldOffHunger in the channel `more` menu on right
![image](https://user-images.githubusercontent.com/787448/205680108-4bd68425-3082-4f0c-bb56-5870c8a034df.png)
