### ISSUE TITLE
Links to www.n-tv.de not clickable

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27078]
### Description:

The link https://www.n-tv.de/ is not clickable when being part of a message. However, a link preview is generated which can be clicked.

This seems to happen with all URLs that match `\.[a-z]\-`.

### Steps to reproduce:

1. Write a message containing https://www.n-tv.de/.
2. Desperately click on the non-clickable link.

### Expected behavior:

The link is clickable.

### Actual behavior:

The link is not clickable.

![image](https://user-images.githubusercontent.com/404840/195988005-7ad2242c-7d4e-4e54-bfd1-68e4683ec455.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0
- Deployment Method: Docker
- Number of Running Instances: 1

### Client Setup Information

Affects any desktop and mobile browser as well as the Android app.

**Comment by dudanogueira** [comment]
Hi! We had some discussion about this at this thread:

https://forums.rocket.chat/t/message-quote-issue/15115/6

**Comment by mani-rsg** [comment]
Hi @dudanogueira , would like to work on this issue, can you assign this to me?

**Comment by ggazzo** [comment]
fixed and working on the 5.3.x and 5.4.0-develop branch

**Comment by hugocostadev** [comment]
Reopening here because I'm working on this

**Comment by paulchen** [comment]
Today I noticed that links to the mobile edition of Wikipedia show the same behaviour, e.g. https://en.m.wikipedia.org/wiki/Main_Page:

![image](https://user-images.githubusercontent.com/404840/214351156-9f82f3e5-573c-46b3-86d3-fee3089f2bab.png)

@hugocostadev will your changes fix this as well or shall I create a separate issue for this?

**Comment by hugocostadev** [comment]
Hi @paulchen , I made a change that's includes this scenario, thanks for reporting!
