### ISSUE TITLE
The background bug 

### ISSUE THREAD

**Issue by djonrid** [RocketChat/Rocket.Chat#27097]
In night mode, the background of forwarded messages is white (previously it was black)
RocketChart Version 3.8.12
OS Windows 11

**Comment by dudanogueira** [comment]
Hi, please, fill the Issue template.

Here a guide on how to better use our Community Resources:
https://docs.rocket.chat/getting-support/community-resources

1 - 3.8.12 is a really old version
2 - We do not have a dark mode as of now
3 - You can probably change all that using CSS in ADMIN > Layout > Custom CSS

Thanks!
