### ISSUE TITLE
is there a way to customize the content of offline message emails?

### ISSUE THREAD

**Issue by Simplici** [RocketChat/Rocket.Chat#27108]
Hello,

from the [documentation](https://docs.rocket.chat/guides/administration/admin-panel/settings/email/editing-emails-content#offline-message), I know that we can customize the subject and body of many emails. But strangely, it is not possible to customize the body of the offline message email.

i integrate rocketchat in an iframe of my application, so I want to replace the default link in email by the url of my application which will show the chat in an iframe.

**Comment by hugocostadev** [comment]
Hi @Simplici, today is not possible to edit the default link, it gets from your client host.

**Comment by Simplici** [comment]
> Hi @Simplici, today is not possible to edit the default link, it gets from your client host.

@hugocostadev do you have any plan to support this?
