### ISSUE TITLE
Users logging in default to Offline/Invisible status

### ISSUE THREAD

**Issue by abruening-iwt** [RocketChat/Rocket.Chat#27112]
### Description:

When a user logs into Rocket.Chat with a browser that does not have any cookies from a previous sign-in, their status is set to Offline (invisible).

### Steps to reproduce:

1. Log into Rocket.Chat and set your status to Online
2. Log back out
3. Clear cookies and offline data or open a new private session
4. Log into Rocket.Chat
5. User status will be set to Offline

### Expected behavior:

One of these:

- Default status should be Online
- Server should remember last status
- Allow users and/or admins to set a default status

### Actual behavior:

User status will be set to Offline.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0
- Operating System: Devuan Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.16 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Firefox 102.4 and 106
- Operating System: Windows 10 and Devuan Linux

### Additional context

Users are signing in with LDAP accounts.
Reporting user says that this is a relatively new issue.

**Comment by ritikBhandari** [comment]
Hi @abruening-iwt ,
Are you still facing this issue?

**Comment by tobiasreinhard** [comment]
Facing the same issue on 5.2 (Docker). Also my users can't change their profile pictures.
Switched back to 5.1.4, still can't change the status but profile picture upload works.

**Comment by abruening-iwt** [comment]
> Hi @abruening-iwt , Are you still facing this issue?

Yes

**Comment by abruening-iwt** [comment]
> Facing the same issue on 5.2 (Docker). Also my users can't change their profile pictures. Switched back to 5.1.4, still can't change the status but profile picture upload works.

To clarify: Changing the status works fine, this is just about the status being automatically set to offline/invisible after logging in.

**Comment by Gummikavalier** [comment]
I confirm this too on RC 5.2.0. User provisioning with Oauth too.

**Comment by ritikBhandari** [comment]
@dudanogueira should I work on this?

**Comment by mddvul22** [comment]
We are having this issue since upgrading to 5.2.0.  We are using the package available at:
https://cdn-download.rocket.chat/build/rocket.chat-5.2.0.tgz

**Comment by mddvul22** [comment]
To be clear, regarding why this bug is so problematic.  When you login, your own status shows as green/online.  However, everybody else sees that same person as offline/invisible.  To fix this, you have to manually set your status to online, even though it looks to yourself like you are already online.

**Comment by tobiasreinhard** [comment]
This bug is very annoying. So many users are reporting inconsistens online/offline states. Please fix this asap!

**Comment by mddvul22** [comment]
We are on 5.2.0.  Can anybody confirm whether this bug is also present in 5.3.0?

**Comment by MBraunshausen** [comment]
still present in 5.3.1

**Comment by xi67** [comment]
Same here in 5.3.3 with only one user.

**Comment by mddvul22** [comment]
In our testing we have discovered an additional problem related to this bug:

1. If you login in RC and set your status to available, everything is good. You are available and others see you as available, also.
2. However, when your client triggers auto-away, in your personal preferences, you become offline (not away). This is where things go really bad. When you go away, your status should change to away. However, in my testing, it changes to offline.
3. When you come back, your client turns green/online, again. But it seems at this point that other clients never update. They see you as remaining offline -- UNTIL you again go to your status and click on online, again.
4. In my testing, if you go into your own preferences and disable auto-away, you will stay online, until you logout. 
5. Turning off auto-away does fix this.  However it does not fix the status when first logging in.

**Comment by dext0r** [comment]
Fixed for me by turning on setting "Use REST instead of websocket for Meteor calls" (General -> REST API)

**Comment by popindavibe** [comment]
Very similar issue for me, though I would mention some different symptoms:

- if connecting via browser, status show 'offline', and the user is in a semi-offline state indeed, as typically messages sent to him show but also get mailed to him
- if connecting via the electron app, status shows online, but I get the exact same behavior on mails being sent to the now-connected user.

In both cases, status shows **offline** for the other users.

**Comment by popindavibe** [comment]
> Fixed for me by turning on setting "Use REST instead of websocket for Meteor calls" (General -> REST API). Don't forget refresh browser page before trying to login.

This worked for me too, thanks!

**Comment by tobiasreinhard** [comment]
We've switched from Rocket.Chat to MS Teams because this issue persists more than 3 months. It's a shame.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by xi67** [comment]
Still here in 6.1.5
