### ISSUE TITLE
Logo on bottom left hand corner is missing icons

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2712]
Your Rocket.Chat version: 0.24

The Rocket.Chat logo on the bottom left hand corner of the UI on each platform is missing the Made with <3 on Github (or something like that)

<img width="256" alt="screen shot 2016-03-30 at 5 29 42 pm" src="https://cloud.githubusercontent.com/assets/8405384/14159756/55fd3e84-f69d-11e5-8130-43cbe746a418.png">

**Comment by IQ2022** [comment]
actually can we make it more user friendly in the way to customize this part? i.e ability to add menu buttons etc.
