### ISSUE TITLE
No Administration > Messages > AutoLinker  Settings working since updating to 5.0.3

### ISSUE THREAD

**Issue by coreybx** [RocketChat/Rocket.Chat#27135]
### Description:
Administration > Messages > AutoLinker. 
No settings here work correctly since updating to version 5.0.3. The default settings work as intended but any changes here do not apply.

### Steps to reproduce:
Go to Administration > Messages > AutoLinker
Set 'Enable' to False
Save changes
Post a message like https://google.com

### Expected behavior:
The text is NOT turned into a hyperlink

### Actual behavior:
The text is turned into a hyperlink

### Container image information:
`rocket.chat                  5.0.3       9641e63149aa`
### Server Setup Information:
```
+--------------------------------------------------+
|                  SERVER RUNNING                  |
+--------------------------------------------------+
|                                                  |
|  Rocket.Chat Version: 5.0.3                      |
|       NodeJS Version: 14.19.3 - x64              |
|      MongoDB Version: 4.4.1                     |
|       MongoDB Engine: wiredTiger                 |
|             Platform: linux                      |
|          Commit Hash: c5b43b004e                 |
|        Commit Branch: HEAD                       |
|                                                  |
+--------------------------------------------------+
```

**Comment by hugocostadev** [comment]
Thank you @coreybx we are addressing this issue internally.

**Comment by hugocostadev** [comment]
The AutoLinker settings only work with the Legacy Message Template. 
In the next major release, (6.x) this setting along with others and the Legacy Message Parser will be removed.
