### ISSUE TITLE
How can I access to database?

### ISSUE THREAD

**Issue by Buzzele** [RocketChat/Rocket.Chat#2713]
Hi,

I have deployed Rocket.Chat with help of the tutorial at DigitalOcean. Now I want to get access to database because I want to try making backups. If I am in the Rocket.Chat directory and type in "mongo" then its connectint to "test". Where is my mistake. Is there a docu online?

Best Regards

**Comment by Sing-Li** [comment]
Definitely become familiar with MongoDB administration in general, especially `mongodump`, if you are running Rocket.Chat in production:

https://docs.mongodb.org/v3.0/tutorial/backup-and-restore-tools/

**Comment by Buzzele** [comment]
Thanks alot

**Comment by YehualashetGit** [comment]
I have the same issu in accessing the database is there anyone try to  help me
