### ISSUE TITLE
In dev mode, using meteor - help on removing a package I installed

### ISSUE THREAD

**Issue by zb471914758** [RocketChat/Rocket.Chat#2714]
version: 0.24.0

I have downloaded the package: mdg:validation-error@0.5.1, 
And even if I delete the mdg:validation-error@0.5.1 in the file .meteor/versions, the error occurs still: 

```
Error: isopack mdg:validation-error not yet loaded?
    at Error (<anonymous>)
    at [object Object]._.extend.getIsopack (/tools/isobuild/isopack-cache.js:108:13)
```

can I get some help, or would you offer the package please ? Thanks!

**Comment by zb471914758** [comment]
@sampaiodiego,@Sing-Li  Would  someone help me? Thanks!

**Comment by sampaiodiego** [comment]
use this command to remove a package `meteor remove mdg:validation-error`

**Comment by zb471914758** [comment]
@sampaiodiego When I execute " meteor remove mdg:validation-error", 
It occurs "mdg:validation-error is not in this project. ", that means I have no "validation-error" package, but why it should also load the package? how can I delete the using in all callings? Thanks!

**Comment by Sing-Li** [comment]
Easiest way is to start over fresh from empty directory and `git clone ...`;  your package directory may be messed up.

**Comment by zb471914758** [comment]
@sampaiodiego , @Sing-Li 
My directory is empty, and git clone it, but the error still occurs,
Perhaps my network proxy is limited, it can not be downloaded automatically.
Can someone share the package: mdg:validation-error@0.5.1?

**Comment by zb471914758** [comment]
@sampaiodiego , @Sing-Li 
Where the package is used,? I can not find it is required or called. Thanks!

**Comment by geekgonecrazy** [comment]
Please feel free to join us in the [#dev](https://demo.rocket.chat/channel/dev) to discuss development related things.
