### ISSUE TITLE
Grey screen on adding users to channel in channel create mode

### ISSUE THREAD

**Issue by Kot-o-pes** [RocketChat/Rocket.Chat#27146]
### Description:

Getting a grey screen when adding users to newly created chanel
### Steps to reproduce:

1. Click create new channel
2. add users to channel
3. press enter to add needed user

### Expected behavior:

user is added 

### Actual behavior:

grey screen

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.4
- Operating System: linux
- Deployment Method: k8s
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: 3.8.11
- Operating System: macos 12.6

**Comment by debdutdeb** [comment]
Hi, please share the browser console logs :)

**Comment by Kot-o-pes** [comment]
Hi @debdutdeb 
console log from chrome 
`ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562 MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
registerType @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
t @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8 strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
w @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
U @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
$ @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
R @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
T @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
C @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
E @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
A @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
subschema @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
m @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:11
code @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:11
G @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
code @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
block @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
F @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
code @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
block @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
T @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
C @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
code @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
code @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
func @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
x @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
b @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
f @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:8
_compileSchemaEnv @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
compile @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
e @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1038
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
t @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
e @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1038
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:5
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
g @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
n @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
t @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:3
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562 Auto-Translate is disabled [error-autotranslate-disabled]
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
await in (anonymous) (async)
_compute @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
_recompute @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
o._runFlush @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
postMessage (async)
u @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
_ @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
invalidate @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
changed @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1335
t.runTask @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
t.flush @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
t.drain @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
insert @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1335
update @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1335
update @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1355
o.each.c.Collection.<computed> @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1449
Object.entries.forEach.c.<computed> @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1451
upsert @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1355
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1451
r.withValue @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
directOp @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1451
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1451
Object.entries.forEach.c.<computed> @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1451
E @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
f @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
await in f (async)
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1562
_compute @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
_recompute @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
o._runFlush @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
postMessage (async)
u @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1
_ @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
invalidate @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
changed @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1333
statusChanged @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
_connected @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
socket.onopen @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
r.dispatchEvent @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
k._dispatchOpen @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
k._didMessage @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
o.ws.onmessage @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1315
ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118 TypeError: Cannot read properties of undefined (reading '_federated')
    at renderSelected (UserAutoCompleteMultipleFederated.tsx:1:1712)
    at Dc (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:59696)
    at Rs (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:111726)
    at nu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98840)
    at tu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98768)
    at eu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98631)
    at Gs (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:95485)
    at ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:45604
    at r.unstable_runWithPriority (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1136:3778)
    at _a (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:45381)
Fi @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
Ni.r.callback @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
La @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
Ui @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
cu @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
r.unstable_runWithPriority @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1136
_a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
au @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
Gs @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
(anonymous) @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
r.unstable_runWithPriority @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1136
_a @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
ya @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
va @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
Le @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
fr @ ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118
ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118 Uncaught TypeError: Cannot read properties of undefined (reading '_federated')
    at renderSelected (UserAutoCompleteMultipleFederated.tsx:1:1712)
    at Dc (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:59696)
    at Rs (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:111726)
    at nu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98840)
    at tu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98768)
    at eu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98631)
    at Gs (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:95485)
    at ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:45604
    at r.unstable_runWithPriority (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1136:3778)
    at _a (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:45381)`

**Comment by Kot-o-pes** [comment]
https://user-images.githubusercontent.com/33171510/198712779-4cf5cd95-d4b5-47ef-8d40-38c69f9f2f30.mp4

**Comment by ggazzo** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/27213
