### ISSUE TITLE
anonymous message writing does not work

### ISSUE THREAD

**Issue by QuakeIV** [RocketChat/Rocket.Chat#27149]
### Description:

Anonymous message writing doesn't work, because the 'Sign in to start talking' and 'Or talk as anonymous' buttons dont do anything.

### Steps to reproduce:
Enable anonymous read/write under settings/accounts
Access server while logged out
Navigate to a public and default room
Click the 'Sign in to start talking' and 'Or talk as anonymous' buttons

### Expected behavior:
'Sign in to start talking' would prompt you to log in
'Or talk as anonymous' button would give you a prompt to create an anonymous login token

### Actual behavior:
The buttons do nothing

### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0
- Operating System: Debian 10 Buster 64 bit
- Deployment Method: Tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.20.1 - x64
- MongoDB Version: 6.0.2

### Client Setup Information

- Desktop App or Browser Version: Firefox 92 (64-bit)
- Operating System: Ubuntu 20.04.3 LTS

### Additional context
Consider the following file: https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/views/room/components/body/composer/ComposerAnonymous.tsx

From the git history it kindof looks like while re-organizing someone commented out the click handlers for the two buttons in question because they cause a compilation failure, and never fixed/reimplemented them, so they in fact do nothing

### Relevant logs:
If you really want to see logs I can provide them, however I currently have a custom version deployed to my server since I tried re-building with the code un-commented (to be clear, i did NOT have a custom version deployed when I first noticed this issue), and then made various efforts to fix it myself (it is not as simple as just un-commenting the code, and I am not a typescript/react/javascript whatever guy so I was unable to figure it out after several hours).  It takes like an hour to redeploy everything and get you a version of the logs from your own production release and I currently believe I already mostly identified the issue so I will not bother for now.

**Comment by QuakeIV** [comment]
is there any way i can like put a bounty on this to speed up proceedings or something, i dont think this is a big fix if someone who actually knows react or node or whatever tackles it

**Comment by georgemaschke** [comment]
I am also experiencing this issue on Rocket.Chat 5.3.1 running under Ubuntu 20.04 LTS. I hope this bug can be prioritized, as it renders my installation (and doubtless many others) essentially useless for new visitors.

**Comment by georgemaschke** [comment]
I note that this serious bug persists in Rocket.Chat 5.3.5.
