### ISSUE TITLE
Image upload doesn't work.

### ISSUE THREAD

**Issue by kramer65** [RocketChat/Rocket.Chat#2715]
Your Rocket.Chat version: (make sure you are running the latest)

I'm running the latest development version of Rocket.Chat (pulled from `rocketchat/rocket.chat:develop`) and I'm having trouble with image uploads. When I upload an image it looks like it finished successfully. I first see a correct preview:
![schermafbeelding 2016-03-31 om 12 24 44](https://cloud.githubusercontent.com/assets/596581/14173248/08fbf4cc-f73d-11e5-9c7a-e9189b5293fa.png)
After that the progress bar at the top finishes without any error. But then the image preview in the chat shows as a white square, and when downloading the image the file is empty (0kb). The original file is really small (~200kb), so that shouldn't be the problem.

Does anybody have any idea what the problem could be or how I could debug this?

**Comment by andreas-bulling** [comment]
check the console output when running Rocket.Chat. Could be a permission problem

**Comment by kramer65** [comment]
Hmmm, and now it suddenly works. No idea why.. 

But thanks for your suggestion!

**Comment by kajisaap** [comment]
We are no latest snap package and 🚀 chat is at  `Version: 0.40.1`

We started experiencing this as well. Symptoms are almost the same but the scenarios are different.

When "upload" settings are tied to "Filesystem", the progress bar would freeze at 100% and nothing happens at all no matter the time. We get following in the log

```bash
ufs: cannot write file "zkb9tX9CKP8zLkX2W" (EROFS: read-only file system, open '/zkb9tX9CKP8zLkX2W.gif') { [Error: EROFS: read-only file system, open '/zkb9tX9CKP8zLkX2W.gif']
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: '/zkb9tX9CKP8zLkX2W.gif' }
Exception while invoking method 'ufsComplete' Error: EROFS: read-only file system, open '/zkb9tX9CKP8zLkX2W.gif'
    at Object.Future.wait (/snap/rocketchat-server/45/node_modules/fibers/future.js:449:15)
    at [object Object].ufsComplete (meteor://💻app/packages/jalik:ufs/ufs-methods.js:62:20)
    at [object Object].methodsMap.(anonymous function) (meteor://💻app/packages/rocketchat:lib/server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (meteor://💻app/packages/ddp-server/livedata_server.js:1711:12)
    at meteor://💻app/packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
    at meteor://💻app/packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
    at meteor://💻app/packages/ddp-server/livedata_server.js:707:46
    at Session.method (meteor://💻app/packages/ddp-server/livedata_server.js:681:23)
    at meteor://💻app/packages/ddp-server/livedata_server.js:551:43
    - - - - -
    at Error (native)
ufs: cannot delete temp file "/tmp/ufs/zkb9tX9CKP8zLkX2W" (ENOENT: no such file or directory, unlink '/tmp/ufs/zkb9tX9CKP8zLkX2W')
```

As for GridFS case, upload shows it worked fine but we get the blank placeholder of zero-byte / an empty file. However, nothing gets vomited in logs in this case.
<img width="521" alt="screen shot 2016-09-23 at 11 17 29" src="https://cloud.githubusercontent.com/assets/722803/18791130/7cf49a88-817f-11e6-87f7-7afe36c4cb12.png">

**Comment by engelgabriel** [comment]
@kajisaap can you please open a new issue for this with the info you added here? This is a different problem.
