### ISSUE TITLE
The default value for the e-mail verification in login form

### ISSUE THREAD

**Issue by nishimaki10** [RocketChat/Rocket.Chat#2716]
Your Rocket.Chat version: 0.24.0

I set Email Verification to True.
A user update email and logout without verification. The next time the user try to login, I want so that the user can get a default value in verification form.
And I want to update user data if modified in this form, because can not login if updated to invalid email.

**Comment by marceloschmidt** [comment]
If users update their e-mail address, I think they should receive a new validation e-mail. If they logout, when they try to login, they should be offered the option to re-send the validation e-mail.
