### ISSUE TITLE
Rocket.chat problem

### ISSUE THREAD

**Issue by peter-glass** [RocketChat/Rocket.Chat#27164]
This is the second time I have reported this problem with rocket.chat. I am unable to open the app from the web and my desktop. I enter my credentials on the signon screen and receive a "please wait..." message. The app does not open.

**Comment by peter-glass** [comment]
I updated my password as advised by email about an hour ago. I subsequently received email informing me that my password update was successful. However, I am still unable to gain access to the rocket chat session for my subscription to the Soctt.Kennedy REIT forum. I paid a substantial fee to gain access to this forum and I am being denied access. This is very frustrating. 

I did visit https://github.com/settings/sessions/authentications/1977583719 in order to review the information displayed there. It reports that I opened a session this morning which is false. I attempted to open a session, but my attempt was unsuccessful. I am at a loss as to how to proceed. There is nothing more that I can do. 

Please investigate this issue and provide a remedy.

Thank you, Peter Glass

**Comment by hugocostadev** [comment]
Hi, @peter-glass any updates on that? 

Sorry, could you give us more information about the version of the Rocket.Chat that you are using, host, operational system, browser, and everything else that could help us investigate? Thank you

I test it here with the last release and the password update feature is working as expected.

If you confirm that you are still facing the issue and provide us with the required information I'll reopen the issue.

Thanks!

**Comment by peter-glass** [comment]
Hugo,
Thanks for your reply. It appears that Sonal Dhingra fixed this problem
last Friday. You can close the ticket.

Take care, 再见，  Peter Glass
Old Crazy Fool: https://s.disco.ac/mpnmesfdjdxd

**Comment by peter-glass** [comment]
Hello Hugo (or whoever receives this message),
Rocket Chat has been an on-going nightmare. I had lost access for a period
of time, and after several complaints and email exchanges it was apparently
fixed, presumably by Sonal Dhingra.

However, the repair was not permanent. Once again I am locked out of the
application and unable to read messages from the REIT forum to which I
subscribe. Would you please look into this and restore my access once
again.

In order to be clear, just as last time I had this problem, whenever I try
to access the chat, the application just hangs on the sign on screen. This
is true for both the web and desktop versions.

Thank you, pg

Take care, 再见，  Peter Glass
Old Crazy Fool: https://s.disco.ac/mpnmesfdjdxd
