### ISSUE TITLE
Create webhook/integrations with rest api

### ISSUE THREAD

**Issue by cbajohr** [RocketChat/Rocket.Chat#2717]
Is it or will it be possible to create/edit/remove integrations and rooms via API?
It would save a lot of time if you could create (private) rooms and automatically create a new webhook for it, with a defined script.

Your Rocket.Chat version: 0.24.0

**Comment by odk-** [comment]
I just found this issue when looking for exact same thing: way to add webhook by api. By checking code I found POST method /api/v1/integrations.create but no info what data should be sent to this endpoint. Will it be official one and we just need to wait for doc update?

**Comment by graywolf336** [comment]
Closing due to us having this already built out:

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/integrations.js

https://rocket.chat/docs/developer-guides/rest-api/integration/

**Comment by odk-** [comment]
According to link you've pasted this is not closed:

type | webhook-outgoing | Required | The type of integration to create, currently only webhook-outgoingis supported.

Issue is that it's not possible to add incoming integration, like for example: You add new room and set up webhook for JIRA notifications about new issues. For me it looks like this should be still open.

**Comment by piotrkochan** [comment]
I think the same. @graywolf336 please consider reopen

**Comment by graywolf336** [comment]
@piotrkochan and @odk- actually, the documentation is out of date. You can create incoming integrations:

https://github.com/RocketChat/Rocket.Chat/blob/bcbb97bf02564d635fb0ab47168e3927276629da/packages/rocketchat-api/server/v1/integrations.js#L23-L36
