### ISSUE TITLE
No link preview when quoting a message

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27174]
### Description:

When quoting a message, no preview will be generated for any link in the reply.

### Steps to reproduce:

1. Write a message.
2. Quote this message and insert a link into the reply.

### Expected behavior:

A preview for the link is shown.

### Actual behavior:

No preview is shown.

![image](https://user-images.githubusercontent.com/404840/199599427-b2f6fbd5-ca86-4da1-8c2b-b8caf819a7a6.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.0
- Deployment Method: Docker
- Number of Running Instances: 1

### Client Setup Information

Affects any combination of browser and operating system as well as the Android app.

### Additional context

When not quoting a message, the preview for the link from the above screenshot looks like this:

![image](https://user-images.githubusercontent.com/404840/199599146-7204d1cf-3a93-4b8d-85d1-63e9b057b662.png)

**Comment by hugocostadev** [comment]
Hi @paulchen thanks for submitting the issue.

This behavior is expected, if we show the link preview and quoted message the layout would be very messy, because of that we only allow link previews on messages that do not contain any other type of attachments (quotes, images, files ....)
