### ISSUE TITLE
Translation of "are_typing" is wrong (at least in german)

### ISSUE THREAD

**Issue by TLINDEN** [RocketChat/Rocket.Chat#27171]
### Description:

When in a chat with one or more people, you can see something like this in the status line while someone else is currently writing:

**userx is writing...**

We are using the german translation, which is defined in `de*.i18n.json` as:
```
"are_typing": "schreiben",
```

and displayed as: **userx is schreiben...**

But this is not correct german, which should read: **userx schreibt...**

- that is, the **is** shall be part of the translation, which it doesn't seem to be currently.

### Steps to reproduce:

1. set lang to german
2. open a chat with someone
3. watch that user writing

### Expected behavior:

Correct translation would be: **userx schreibt...**

### Actual behavior:

Current translation is: **userx is schreiben...**

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.1
- Operating System: Debian 10 (Kernel 5.10.46-4)
- Deployment Method: kubernetes
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: v4.4.11

### Client Setup Information

- Desktop App or Browser Version: Chrome any current version
- Operating System: Linux and Mac

**Comment by bbrauns** [comment]
duplicate https://github.com/RocketChat/Rocket.Chat/issues/23593

**Comment by TLINDEN** [comment]
oh, thx.
