### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#2718]
Your Rocket.Chat version: 0.24.0

I am experiencing a problem with uploading images (see #2715): The loading bar goes up to 50%, then suddenly drops back to 0% and nothing happens, both using GridFS and Filesystem.

Exception while invoking method 'ufsComplete' TypeError: Cannot call method 'pipe' of undefined at gm.identify (server/config/configFileUploadFileSystem.js:28:20) at gm.emit (events.js:106:17) at gm.<anonymous> (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/getters.js:129:14) at cb (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/command.js:314:16) at gm._spawn (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/command.js:221:14) at gm._exec (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/command.js:190:17) at gm.identify (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/getters.js:127:10) at [object Object].UploadFS.store.Local.transformWrite (server/config/configFileUploadFileSystem.js:40:43) at [object Object].self.transformWrite (packages/jalik_ufs/ufs-store.js:193:1) at [object Object].self.write (packages/jalik_ufs/ufs-store.js:274:1) ufs: cannot delete temp file at /tmp/ufs/ATSxb9mFXfpn5oZfv (ENOENT, unlink '/tmp/ufs/ATSxb9mFXfpn5oZfv')

Exception while invoking method 'ufsComplete' TypeError: Cannot call method 'pipe' of undefined at gm.identify (lib/fileUpload.coffee:33:21) at gm.emit (events.js:106:17) at gm.<anonymous> (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/getters.js:129:14) at cb (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/command.js:314:16) at gm._spawn (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/command.js:221:14) at gm._exec (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/command.js:190:17) at gm.identify (/home/user/Rocket.Chat/programs/server/npm/rocketchat_file/node_modules/gm/lib/getters.js:127:10) at [object Object].Meteor.fileStore.UploadFS.store.GridFS.transformWrite (lib/fileUpload.coffee:44:44) at [object Object].self.transformWrite (packages/jalik_ufs/ufs-store.js:193:1) at [object Object].self.write (packages/jalik_ufs/ufs-store.js:274:1) ufs: cannot delete temp file at /tmp/ufs/pbzwZzQwDfT78DkWf (ENOENT, unlink '/tmp/ufs/pbzwZzQwDfT78DkWf')

**Comment by root-dir** [comment]
Make sure the user running the app has write permissions on /tmp/ufs

**Comment by andreas-bulling** [comment]
The user has - still doesn't work...

**Comment by sjt003** [comment]
same as error here

**Comment by sjt003** [comment]
both filesystem and gridfs

**Comment by propertunist** [comment]
initially my file uploads (using local filesystem) were getting stuck at 0%, then i read this thread and set the owner of /tmp/ufs/ appropriately.. now the images get uploaded to about 50% in the green uploading bar and then they reverse back to 0.

**Comment by propertunist** [comment]
oh, correction - they go to 100% very quickly and then revert to 0. i am not seeing any relevant errors.

**Comment by dpendolino** [comment]
I'm have the same issue on version 0.34.0. My user has full rwx and I even expanded that to 777.

**Comment by MartinSchoeler** [comment]
@andreas-bulling 
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates
