### ISSUE TITLE
Dark Mode unusable on MacOS

### ISSUE THREAD

**Issue by sreimann81** [RocketChat/Rocket.Chat#27186]
Hello,

darkmode is somehow broken. The titlebar is white even in dark mode. I cleared the cache to make sure there is no outdated CSS in place, but likely this is broken upstream. Dark mode is not usable like this (because of the input bar).

MacOS 13
Client: 3.8.12
Server: 5.3.0

BR
Sebastian
![Bildschirm­foto 2022-11-04 um 09 43 02](https://user-images.githubusercontent.com/96955994/199930554-c94e090e-ab40-485f-a96a-31ec9b69ac28.png)

**Comment by foss-** [comment]
Is there dark mode support in Rocket Chat now? Did I miss something in the changelog?

**Comment by sreimann81** [comment]
Works again

**Comment by moubctez** [comment]
It's still broken in Server v5.3.1

**Comment by juzser** [comment]
I've updated the Dark mode for the new version of Rocket using css variables.
You guys can try this here: https://github.com/juzser/Rocket.Chat-Dark-Theme

**Comment by diegobelotti** [comment]
Just to help others: "Go to Admin > Settings > Layout. Then **_replace_** the following code to the fields:"

> I've updated the Dark mode for the new version of Rocket using css variables. You guys can try this here: https://github.com/juzser/Rocket.Chat-dark-mode
