### ISSUE TITLE
Rocket Chat v. 3.8.6 - Upload issue

### ISSUE THREAD

**Issue by pomil** [RocketChat/Rocket.Chat#27227]
When uploading fails, then for the others it seems that uploading is continuing. It stops when I upload successfully a new file.

**Comment by hugocostadev** [comment]
Hi there!

Sorry, this error does not happen on the latest releases.
Rocket.Chat provides support for 6 months to the latest releases of each major version.

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find it here: https://github.com/RocketChat/Rocket.Chat/releases

For more information about your support: https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions
