### ISSUE TITLE
[BUG] Desktop notifications when application closed not working

### ISSUE THREAD

**Issue by AvivBenShoham** [RocketChat/Rocket.Chat#27224]
### Description:

When the application is closed and the user received a message, the desktop notification does not show up.

### Steps to reproduce:

1. Download the application in your windows computer (maybe linux too?)
2. Send a message to the logged in user there
3. Check if the notification appear in a desktop popup

### Expected behavior:

Desktop notification will appear

### Actual behavior:

Desktop notification doesn't appear

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: docker
- Number of Running Instances: 13
- NodeJS Version: 12.18.2
- MongoDB Version: 4.4.2

### Client Setup Information

- Desktop App
- Windows 10

**Comment by hugocostadev** [comment]
Hi there! 

Sorry, this error does not happen on the latest releases.
Rocket.Chat provides support for 6 months to the latest releases of each major version.

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find it here: https://github.com/RocketChat/Rocket.Chat/releases 

For more information about your support: https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions
