### ISSUE TITLE
[5.0 Regression][Usability] No longer possible to decide to view all thread messages in main channel from the receiver-side

### ISSUE THREAD

**Issue by SaintedSheep** [RocketChat/Rocket.Chat#27220]
### Description:

This feature got removed with 5.0,
change: https://github.com/RocketChat/Rocket.Chat/pull/26002

### Expected behavior:

The decision to show all thread messages in the main channel should be choosable for each client, even if the author of a message decided to not send it to the main channel explicitely (via the checkmark).

You can have people that always see all thread messages in the main channel, and people that only see those that were explicitely send there, depending on their individual decision for that setting.

### Actual behavior:

This feature does no longer exist. Each sender now decides if their message is shown in the main channel, without the receiver being able to affect it clientside. You can activate the sender-setting for everyone admin-side, but that means one of the two parties will be unhappy: Either those that don't want to see all thread messages in the main channel will be forced to see them, or those that want to see all won't.

### Additional context

the problem was already explained here https://github.com/RocketChat/Rocket.Chat/issues/26651 but closed there, I feel the need to bring this to light, as this is a major issue for usability at our company.

**Comment by aceArt-GmbH** [comment]
> Also send to channel behavior

This also affects notifications.
Previously all messages were shown in main thread but only if you actively followed a thread or participated you got a notification

**Comment by benedikt-wegmann** [comment]
In channels with mixed topics this new behavior has actually degraded communication and negatively effected everybody. It is not simply a styling change. People are actually missing out on communication.

**Comment by ankar84** [comment]
We upgraded to 5.3.3 and users now comply about that feature missing.
IMHO, fix should be options and on receiver side, like preference option for all threads (show all, show only  sender want to put in main chat)
