### ISSUE TITLE
Feature request - More search options

### ISSUE THREAD

**Issue by gafish04** [RocketChat/Rocket.Chat#2722]
Hi, 

We have install Rocket.Chat few days ago, very good job ! 
We have some needs, and Rocket.Chat covers most of them very well.
The only thing we haven't found yet it's some more advanced search options : 
- in a channel, search for post for a particular user (maybe with a keyword in the search, like "from: @user "
- in a channel, search on document name 

Is these features are planned ?

Best regards

**Comment by bgomelsky** [comment]
There are a couple of existing channel search options **from:**_username_ and **mention:**_username_  (no spaces between **:** and username)

**Comment by gafish04** [comment]
Thank you. 
It works with from:user, without spaces (when I've tried, it was with spaces).

**Comment by engelgabriel** [comment]
awesome
