### ISSUE TITLE
Users have not added from other channel

### ISSUE THREAD

**Issue by pauloriply** [RocketChat/Rocket.Chat#27238]
I have many channels i9n my RC installation.
Main channel called ch1, and he has 77 users
Secondary channel called ch2, he has 63 users
When i trying to add all users from ch1 to ch2 by command `/invite-all-from #ch1` i don't receive any results, and users doesn't adding.

Steps to reproduce:
1 - Go to the destination channel
2 - Enter command `/invite-all-from #sourceChannelName`

Expected behavior:
all users from source channel must be added to destination channel

Actual behaviours
Users doesn't added

P.S.: I remember, that on previous version RC has command to invite all users to channel, where you are, by `/invite @all`

Server Setup Information:
Version of Rocket.Chat Server: 5.3.0
Operating System: ubuntu 20.04
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: yes
NodeJS Version: v14.19.3
MongoDB Version: 5.0.8 / wiredTiger (oplog Enabled)
No logs in debug mode.

**Comment by ggazzo** [comment]
this is odd rocket.cat should tell you the problem, could you please check the maximum number of users per room?

**Comment by pauloriply** [comment]
> this is odd rocket.cat should tell you the problem, could you please check the maximum number of users per room?

Whre i can find this value in settings?

**Comment by pauloriply** [comment]
@ggazzo reopen this issue please.
