### ISSUE TITLE
Message quote issue

### ISSUE THREAD

**Issue by 3x3cut0r** [RocketChat/Rocket.Chat#27249]
### Description:

If i quote a message in Rocket.Chat the message above the quote has a incorrectly formated link in front of the text which was not there before

### Steps to reproduce:

1. quote a message (test message)
2. enter your answer (test quote)
3. send the message

### Expected behavior:

the answer shoud be shown without that link

### Actual behavior:

the answer has a incorrectly formatted link in front of the test

![Bildschirm­foto 2022-11-12 um 13 04 39](https://user-images.githubusercontent.com/1408580/201473351-96a6ede0-4ce4-4abb-8ffa-b7ff76e7c58c.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.0
- Operating System: debian 11
- Deployment Method: docker (linux amd64)
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.13

### Client Setup Information

- Desktop App or Browser Version: Chrome 107
- Operating System: MacOS X 13.x

### Additional context

Last working state was on Rocket.Chat Server Version 5.1.3
It is maybe related to the Message Parser and has something to do with special characters in the Server URL (see discussion), but this is not the case here.

### Community discussion:

[https://forums.rocket.chat/t/message-quote-issue/15115/8](https://forums.rocket.chat/t/message-quote-issue/15115/8)

**Comment by staukini** [comment]
Same issue here on my site. 
Version 5.3.1
docker (official rocketchat/rocket.chat:5.3.1; MongoDB 4.4)
Host: Ubuntu 20.04

Client: Linux and Windows; Browser: Firefox (106.5) and Chrome (107.0.5304.110)

**Comment by Abhi149209** [comment]
@3x3cut0r assign ME I can resolve this

**Comment by 3x3cut0r** [comment]
what do you mean? i cannot assign anyone on this project?!

**Comment by Abhi149209** [comment]
@ggazzo can you assign me ?

**Comment by ggazzo** [comment]
go ahead @Abhi149209

**Comment by ggazzo** [comment]
btw @3x3cut0r could you try https://open.rocket.chat or just the version 5.4.0 candidate ? I cant no longer reproduce your problem

**Comment by ggazzo** [comment]
btw  the problems is related with your domain `3x3cut0r`

if you try `[3x3cut0r](https://3x3cut0r.de)` at version 5.3.0 you should see the same problem

we had an issue if domains starting with numbers

it was closed by https://github.com/RocketChat/fuselage/pull/855

**Comment by 3x3cut0r** [comment]
yes i can confirm. on 5.4.0-rc.1 its gone and working again!
thx!
