### ISSUE TITLE
Rocketchat sticky session question

### ISSUE THREAD

**Issue by GloomyDay** [RocketChat/Rocket.Chat#27256]
Hello,i have a qustion about rocketchat and sticky sessions ,are they still need to be enabled in large deployments ( for example in kubernetes with 16 instances ) ?

 I found multiple old posts about it ,like this  https://github.com/RocketChat/Rocket.Chat/issues/17473#issuecomment-621203370 ,or offical guide (only apache part https://docs.rocket.chat/quick-start/scaling-rocket.chat/running-multiple-instances ) .

So my question is: are they still need to be enabled in load balancer ?

**Comment by ggazzo** [comment]
General rule: yes.
This is mainly due to `ws` fallback which is done using `xhr`
if you don't allow the fallback then in theory you wouldn't need it
