### ISSUE TITLE
Problem with displaying non-FQDN links in the new message template

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27257]
### Description:

If you use the new message template, links with hostname are not displayed as links, but as text.
![image](https://user-images.githubusercontent.com/104189570/201660710-32f05e11-9e3d-48ac-acfb-7f6d17f174ba.png)
In the old message template, non-FQDN links display fine.
![image](https://user-images.githubusercontent.com/104189570/201660905-f396ccf3-8fc4-4034-ba4e-96f746e80979.png)

### Steps to reproduce:

1. Go to "My Account -> Preference -> Global".
2. Disable "Use legacy message template" setting.
3. Write a message with the link http://site
4. Link does not become active

### Expected behavior:

The new message template converts non-FQDN links to clickable ones.

### Actual behavior:

The new message template leaves non-FQDN links as text.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.0
- Operating System: Oracle Linux 8.6
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.13

### Client Setup Information

- Desktop App or Browser Version: Chromium 103
- Operating System: Debian 11

### Additional context

We will try to avoid using non-FQDN links, but for compatibility reasons, please return support for them.

**Comment by ankar84** [comment]
I guess @hugocostadev and @gabriellsh already working on that problem.

**Comment by gabriellsh** [comment]
Yep, here's a merged PR for it: https://github.com/RocketChat/fuselage/pull/901

This will only fix when using the `[title](link)` pattern though. We have some limitations that we're currently trying to overcome regarding our parser, but we didn't want to leave this issue unattended, so we did what's possible for now.
