### ISSUE TITLE
Unable to change colors of announcement

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27269]
### Description:

Using Workspace -> Settings -> Layout -> Colors it is not possible to change the colors of an announcement.

### Steps to reproduce:

1. Be a user with the role `Admin`.
2. Navigate to Workspace -> Settings -> Layout -> Colors.
3. Change the following colors and save the changes:
   - Announcement Text Color to #d30909
   - Announcement Background Color to #ffdd00
   - Announcement Text Color Hover to #ee00ff
   - Announcement Background Color Hover to #00ff1e
The relevant section will look like this:
![image](https://user-images.githubusercontent.com/404840/202025235-44f3d28c-a7a3-4d65-8083-a39724c34931.png)
You may of course use a different set of colors, I just used these colors for illustration.
4. Create an announcement in an any channel.

### Expected behavior:

The colors are applied:

![image](https://user-images.githubusercontent.com/404840/202025963-95a6797e-43df-48d9-8d0e-df85f41d3bcb.png)

### Actual behavior:

The colors are not applied:

![image](https://user-images.githubusercontent.com/404840/202025595-9b717462-b340-4fa6-bbc1-83ad494e03a2.png)

However, they are applied when hovering the announcement:

![image](https://user-images.githubusercontent.com/404840/202027374-e3409e7f-bc85-4424-9583-dd3fdba543bc.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 5.0.13 / wiredTiger (oplog Enabled)

### Client Setup Information

Affects any combination of browser and operating system.

### Additional context

This apparently happens because changing the colors at Workspace -> Settings -> Layout sets the CSS variables
 - `--rc-color-announcement-text`,
 - `--rc-color-announcement-background`,
 - `--rc-color-announcement-text-hover`, and
 - `--rc-color-announcement-background-hover`.

However, the non-hovered announcement uses the CSS variables
 - `--rcx-color-announcement-background` and
 - `--rcx-color-announcement-text`:

![image](https://user-images.githubusercontent.com/404840/202026836-5e8a9c5b-58e7-424b-9393-f8d976613e47.png)

The hovered announcement uses the CSS variables
 - `--rc-color-announcement-background-hover` and
 - `--rc-color-announcement-text-hover`.

Therefore, it is displayed as expected:

![image](https://user-images.githubusercontent.com/404840/202027065-3634814f-a012-43e6-a174-db449bc2bcea.png)

I stumbled upon this issue while investigating into https://github.com/pbaity/rocketchat-dark-mode/issues/203.

**Comment by Gummikavalier** [comment]
I confirm this issue in RC 5.3.1 too.

**Comment by Abhi149209** [comment]
@Gummikavalier @paulchen please assign me , I can resolve the issue

**Comment by ggazzo** [comment]
Layout colors is no longer available try CSS vars or custom css
