### ISSUE TITLE
Register username screen stuck on "Loading suggestions"

### ISSUE THREAD

**Issue by Kamlesh72** [RocketChat/Rocket.Chat#27266]
### Steps to reproduce:

1. Go to https://open.rocket.chat
2. Register using Google account or Github account

### Expected behavior:

Screen should show usernames or move to another page.

### Actual behavior:

![Screenshot 2022-11-15 at 9 11 55 PM](https://user-images.githubusercontent.com/90441742/201962158-63288a7e-e750-490b-af78-340736b9c2c1.png)

### Client Setup Information:

- Hardware: Macbook Air M1
- Rocket.chat - Browser Version 5.3.0
- Operating System: macOS Monterey 12.6.1
- Browser: Safari Version 16.0

**Comment by infuman69** [comment]
Yeah faced the same issue 2days ago.

**Comment by MauryanKansara** [comment]
I'm also facing the same issue in Windows 11 with Chrome and Brave..........

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
