### ISSUE TITLE
[feature] Healthcheck endpoint for rocketchat server

### ISSUE THREAD

**Issue by Kot-o-pes** [RocketChat/Rocket.Chat#27278]
### Description:

Hello, everyone. I am running two separate deployments of rocketchat in k8s in different datacenters connected to the same db and its being exposed by nginx server. Recently we had issues with one of k8s clusters however it was still reachable by network and failover didnt work. Ive started searching for a healthcheck endpoint for rocketchat to be able to perform helathcheck request for a failover procedure but i havent found anything regarding it. Is it possible to add such endpoint which will return 200 OK if everything is up and running and 50x if its not. 

### Expected behavior:

Rocketchat to have a healthcheck page 
### Actual behavior:

Rocketchat doesnt have a healthcheck page
### Server Setup Information:

Version
5.3.1
Apps Engine Version
1.35.0
Node Version
v14.19.3
MongoDB
5.0.11 / unknown
Commit Details
HEAD: (a639f2002)
Branch: HEAD

**Comment by dudanogueira** [comment]
Hi! Have you seen this PR? it introduces a healthcheck for data stream!
https://github.com/RocketChat/Rocket.Chat/pull/27026

**Comment by Kot-o-pes** [comment]
thank you @dudanogueira this is what i was looking for!
