### ISSUE TITLE
HTML entities not properly handled in link previews

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27270]
### Description:

The link preview uses the value of the `content` attribute of the `<meta name="description">` tag of a HTML page, if present. Sometimes, this attribute contains HTML entities. These HTML entities are not handled properly leading to HTML entities shown to the user.

### Steps to reproduce:

1. Write a message containing the link https://github.com/RocketChat/Rocket.Chat/issues/27269 (`https://github.com/RocketChat/Rocket.Chat/issues/27269`).
2. Look at the link preview.

### Expected behavior:

The description text reads `Description: Using Workspace -> Settings -> L...`.

### Actual behavior:

The description text reads `Description: Using Workspace -&gt; Settings -&gt; L...`:

![image](https://user-images.githubusercontent.com/404840/202031187-ced49cb0-31c5-42e1-bd5d-6c2fe9e9ca21.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 5.0.13 / wiredTiger (oplog Enabled)

### Client Setup Information

Affects any combination of browser and operating system.

**Comment by xareyli** [comment]
Please review https://github.com/RocketChat/Rocket.Chat/pull/27371

**Comment by henit-chobisa** [comment]
Hello @paulchen, I am working on the same for now.

**Comment by hugocostadev** [comment]
Fixed in the 6.x release!



![Image](https://user-images.githubusercontent.com/20212776/228564930-1001fded-6fb3-4a25-a58e-c25662510fc6.png)
