### ISSUE TITLE
[question] URL cache or config I missed?

### ISSUE THREAD

**Issue by moranno** [RocketChat/Rocket.Chat#27273]
I changed my URL chats.xxx.com to chat.xxx.com by using `snap set rocketchat-server siteurl=http://chat.xxx.com` and changed general workspace Site URL settings in administration panel.
Then I `snap restart rocketchat-server`

But when I visit the livechat, there always a old URL with port 3000 fetched, check the img below:
<img width="459" alt="iShot_2022-11-16_11 05 12" src="https://user-images.githubusercontent.com/77610980/202074745-45c24c8d-7738-4d78-8676-f27f17c0a47a.png">

Any ideas?

**Comment by dudanogueira** [comment]
Hi! Please, consider going thru this doc before opening an Issue:
https://docs.rocket.chat/getting-support/community-resources

It also helps when we know what version are you running.

This can be a cached from the browser. Have you tried reloading it or accessing with incognito mode?

I am closing this and I'll ask you to [open a thread](https://forums.rocket.chat/) or [send here a message](https://open.rocket.chat/channel/support)

Thanks!
