### ISSUE TITLE
LastMessage incorrect after deletion if E2E is enabled and last message is removed

### ISSUE THREAD

**Issue by web-mi** [RocketChat/Rocket.Chat#27285]
### Description:

If End-to-End Encryption is enabled and you delete the last message in a room the is updated to the last message without a type (t) attribute set which will be last message before the encryption was enabled for this room or no message if no unencrypted message is available.

If you send an encrypted message the lastMessage is updated correctly but on deletion the method `Rooms.resetLastMessageById` is called which will get the last message by calling `Messages.getLastVisibleMessageSentWithNoTypeByRoomId`. But an e2e message has the t set to "e2e" and will be ignored.

Maybe the method need to be replaced by something called `Messages.getLastVisibleMessageSentWithNoSystemTypeByRoomId` which will include e2e types too.

### Steps to reproduce:

1. Enable End-to-End Encryption in Settings
2. Start a new room (no matter which type)
3. Enable encryption for this room
4. Write multiple messages with different content
5. Last message will be shown on the left side (Expanded view)
6. Delete the last message
7. Reload the page if the message on the left side is not updating
8. Find the wrong last message in the preview on the left.

### Expected behavior:

The last message is shown nevermind if its an encrypted or unencrypted message

### Actual behavior:

Last unencrypted message is shown:
![image](https://user-images.githubusercontent.com/1172672/202299350-689cabe0-4f7e-44b9-a6b9-0940206f5e12.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4 to latest
- Operating System: n/a
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: n/a
- NodeJS Version: n/a
- MongoDB Version: latest

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Ubuntu

**Comment by milton-rucks** [comment]
Fixed in 6.10
