### ISSUE TITLE
Badwords Filtering not working on new Message Parser

### ISSUE THREAD

**Issue by dudanogueira** [RocketChat/Rocket.Chat#27298]
### Description:

When you set up bad words to be filtered, it will change for *** on notifications, but not on channel.

### Steps to reproduce:

1. Enable `WORKSPACE > SETTINGS > MESSAGE > Allow Message bad words filtering`
2. `WORKSPACE > SETTINGS > MESSAGE > Add Bad Words to the Blacklist` to onebadword,otherbadword
3. Send a message to a channel: onebadword followed by otherbadword

### Expected behavior (this is what happens if using legacy message parser):

![image](https://user-images.githubusercontent.com/1761174/202783265-da4927dd-9fc7-4d5e-8623-52a9af0dd2fd.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/1761174/202783388-5b4de3df-3dc7-490f-98ac-37d830322e40.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
For reference: https://forums.rocket.chat/t/cant-add-bad-words-to-blacklist/15363/3

**Comment by henit-chobisa** [comment]
Hey there @dudanogueira, 
I am looking forward to resolving the following issue.

**Comment by henit-chobisa** [comment]
Hello @dudanogueira, hope you're doing well! 😄
I am passionate to work on this issue, should I make a draft PR for the same? 🚀

**Comment by dudanogueira** [comment]
> Hello @dudanogueira, hope you're doing well! 😄
> I am passionate to work on this issue, if you can tell me, how should I go about the  new fuselage `message-parser`, I would be more than grateful to you. 

Hi! Thanks! I will ask one of our developers as I don't know about it too, hehehehe

**Comment by henit-chobisa** [comment]
Thank you so much, 
I made a body parser for Our Github App using Regex, here https://github.com/RocketChat/Apps.Github22/pull/32
This one also seems fun to work on! 🚀🚀🚀

**Comment by xareyli** [comment]
Oh, it seems that there is an assigned developer for this issue.
@dudanogueira Should I notify that I'm working on an issue before creating PR?

P.S.
Review https://github.com/RocketChat/Rocket.Chat/pull/27368

**Comment by henit-chobisa** [comment]
Hey @xareyli, 
I was researching this issue, came to both `pre` and `post` message save callbacks, and was thinking of changing something in the message parser, but your solution of reversing the `beforeSaveMessage` callback chain seems super awesome!!! 😍😍
It would be awesome if you practice making a draft PR whenever you think of working on an issue, notifying other devs that you're working on the same.

**Comment by dudanogueira** [comment]
thanks @xareyli and @henit-chobisa for the interest! I asked already our devs to review this PR!

Really appreciate it :)
