### ISSUE TITLE
Rocket Python Bot

### ISSUE THREAD

**Issue by seyed-dev** [RocketChat/Rocket.Chat#27303]
# RocketPyBot
## Python lib for create rocketchat bot with getupdate like TelegramBots
i create this lib for Making a robot in the simplest way

github : https://github.com/seyed-dev/rocketchatbot
pypi : https://pypi.org/project/pyrocketbot/

**Comment by dudanogueira** [comment]
Hi!

Thanks for that contribution!

Great places to advertise your project:
- https://forums.rocket.chat/c/community-creations/
- https://forums.rocket.chat/c/bots-special-interest-panel/11
- https://open.rocket.chat/channel/bots

Also check out this recent documentation we did on creating bots using botpress:
https://developer.rocket.chat/bots/creating-your-own-bot-from-scratch/develop-a-botpress-bot

I will close this issue as it's not a software issue.

Thanks!
