### ISSUE TITLE
Downloading protected uploads should login if not authenticated

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#2730]
Your Rocket.Chat version: 0.24 develop

Using the mobile android app.
When Protect uploaded files is enabled when you go to download a file it opens a web page in a browser authenticating the user. If your not logged in you receive a 403 error.

Even though my credentials are stored in a cookie I still recieved the 403 error. After going to my main rocketchat site in the browser (logged in automatically) and then going back to the mobile app the link works.

The meat of this issue is that RC should try to login if the user isn't authenticated.

**Comment by geekgonecrazy** [comment]
maybe it should open with a token so that we know your authenticated, instead of having to have you log in?

**Comment by mrplow** [comment]
Looks like it does contain a token, but I'm not skilled enough to know what it's doing on the backend.

https://chat.myserver/file-upload/M2G9zrWc582mcyk7P/snapseed-01.jpeg?rc_uid=WWxDgp7dJo5whppm8&rc_token=aNDjP5J0qUjye6zlRLE0NvxLPZH9Zz0VK368jkpXQ9_

**Comment by mrplow** [comment]
Fixed in @0828804
