### ISSUE TITLE
Question: is there a way to remove imported files (e.g Slack)?

### ISSUE THREAD

**Issue by pacospace** [RocketChat/Rocket.Chat#27379]
HI all,

I wanted to know if there is a way to remove the imports (e.g. slack) from the UI. Or if there is a procedure to do that in general?

Thank you so much!

Thanks!

**Comment by dudanogueira** [comment]
Hi!
I don't think there is, from the UI :(

If you want answer for more questions (here is more for reporting bugs), please, check this guide:
https://docs.rocket.chat/getting-support/community-resources

Thanks!

**Comment by pacospace** [comment]
> Hi! I don't think there is, from the UI :(
> 
> If you want answer for more questions (here is more for reporting bugs), please, check this guide: https://docs.rocket.chat/getting-support/community-resources
> 
> Thanks!

Thanks a lot @dudanogueira, sorry for spamming here. I actually asked in forums: https://forums.rocket.chat/t/delete-imports-e-g-slack-from-rocketchat/15431 :)
