### ISSUE TITLE
Links to a third-level domain with a dash are not active

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27376]
### Description:

In the new message template, links do not become clickable if there is a third-level domain in the address, while a dash is present in the second-level domain.

### Steps to reproduce:

1. Send to chat link http://test.e-xample.com
2. The link does not become active.

### Expected behavior:

Links with dashes are converted to clickable links.

### Actual behavior:

Links to a third-level domain with a dash are not converted to active.
![image](https://user-images.githubusercontent.com/104189570/204227069-8835e892-40ef-40a0-8cdc-bce7affbcaac.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.3
- Operating System:  Oracle Linux 8.5
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.8.11
- Operating System: Windows 10

**Comment by matthias4217** [comment]
I can confirm what's been said, on Rocket Chat 5.3.3. However, I'd like to add that `https://test.ex-ample.com` works fine.

**Comment by dudanogueira** [comment]
Related issue: https://github.com/RocketChat/Rocket.Chat/issues/27078

**Comment by david-m-m** [comment]
Seems like links with a 2nd level domain starting with a number are also affected:
* `[Test Link](https://www.1forall.com)` is *not* rendered correctly
* `[Test Link2](https://www.one-forall.com)` is rendered as a link

**Comment by sketch242** [comment]
Also on 5.3.3.  Possibly worth noting this happens even if you try to use markdown to get around it (includes "edit mode" of last link to show markdown)

<img width="378" alt="image" src="https://user-images.githubusercontent.com/5010790/207466650-eb06dac3-ca2a-458a-820f-7141bd624fb4.png">

Also, this is specific to the new message parser.  It renders correctly with the legacy if I switch to the message template:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/5010790/207467233-12f82068-7e11-4db2-9a6f-6319c5f72aa1.png">

**Comment by frankMagoba** [comment]
Cause of bug is an external lib @rocket.chat/message-parser that is responsible for detecting links in messages and the changes needed to resolve this need to be made on some other different repo [here](https://github.com/RocketChat/fuselage)

**Comment by grape9292** [comment]
Have the same issue in RocketChat 5.4.1. Links like `test.1test.com` and `test.t-est.com` isn't clickable in a text message.

**Comment by hugocostadev** [comment]
Hi, @shevchukma I'm working on this issue! Thanks for reporting!
