### ISSUE TITLE
History not loading after update to 5.3

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27372]
### Description:

After updating from version 4.8.6 to version 5.3.3, chats with a large number of messages in threads do not load history. I get the error "Error, to many requests. Please slow down..."
After that, the download circles flash, but nothing else downloads. Unable to load history.
In other chats where there are not many messages in the threads, the chat history is loaded.
I tried changing the Rate Limiter values, but that didn't work. The Rate Limiter is now at its default value.

### Steps to reproduce:

1. Open a chat with a large number of messages in threads.
2. An error appears, the chat content is not loading.

### Expected behavior:

The chat history is loaded even if there are threads with a large number of messages in the chat.

### Actual behavior:

Chat history does not load if it has a large number of messages in many threads
Below is an example video.
![loadcontent](https://user-images.githubusercontent.com/104189570/204163044-4c08319e-b17a-4a73-b473-b44b13e85d9b.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.3
- Operating System:  Oracle Linux 8.5
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.8.14, Chromium 103.0.5060.53
- Operating System: Windows 11. Debian 11.

### Additional context

Version 4.8.* and previous versions did not have this problem.

### Relevant logs:

![image](https://user-images.githubusercontent.com/104189570/204163625-67e60fe5-290b-47e5-9664-f23f0840b95b.png)

**Comment by ankar84** [comment]
Confirm that bug.
Looks like every thread message create separate REST API request, and if amount of such messages a big, then Rate Limiter blocks it. That behavior must be fixed.
cc @dudanogueira @debdutdeb to show that issue to team.

**Comment by dudanogueira** [comment]
Fix was included in 5.4.0 :)
