### ISSUE TITLE
5.3.3 release

### ISSUE THREAD

**Issue by paneda1998** [RocketChat/Rocket.Chat#27370]
Hi 
I need to have docker image for 5.3.3 release
but in dockerhub latest version is 5.2.0

**Comment by MarlynxLinux** [comment]
> Hi I need to have docker image for 5.3.3 release but in dockerhub latest version is 5.2.0

docker pull rocketchat/rocket.chat:5.3.3

**Comment by paneda1998** [comment]
thanks for your answer
i have another question
is ther any difference between this two dockerhub repos?
https://hub.docker.com/r/rocketchat/rocket.chat
and
https://hub.docker.com/_/rocket-chat


are both of them official?
