### ISSUE TITLE
ROCKET NOT SHOWING NEW MESSAGES

### ISSUE THREAD

**Issue by davidsy1** [RocketChat/Rocket.Chat#27388]
NONE OF OUR USERS ARE GETTING NOTIFICATIONS.  ALSO, MANY USERS STATE THAT THEIR MESSAGES ARE NOT LOADING AND ARE STAYING 'GREYED OUT'.  
WE HAVE INSTALLED AND UPDATED OUR CLIENT APPS, BUT THE PROBLEM CONTINUES.  
PLEASE HELP.
THANK YOU,
DAVID
DIRECT 605 791-2403

**Comment by dudanogueira** [comment]
Hi @davidsy1 

This is not the right place to ask for help, but to point issues in Rocket.Chat.

For that you need to provide some information.

Please, check out this doc on how to ask for help and better use our Community Resources:
https://docs.rocket.chat/getting-support/community-resources

I will close this issue as it's not on the right place not has the template filled.

Please, if you have the Enterprise Edition, refer to http://support.rocket.chat for our Enterprise Level support.

Thanks!
