### ISSUE TITLE
Livechat: Omnichannel adminstration return a blank page

### ISSUE THREAD

**Issue by Floflobel** [RocketChat/Rocket.Chat#27395]
### Description:

When we go to the omnichannel administration settings, we see a blank page with errors in the developer console.

### Steps to reproduce:

1. Administration > Workspace > Settings > Omnicanal
2. Blank page

### Expected behavior:

View the omnichannel settings page

### Actual behavior:

Blank page
![sqjTPVkgHH](https://user-images.githubusercontent.com/13889750/204395094-fd57cdbd-3812-4af5-803e-075c8382733e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.3
- Operating System: Ubuntu 20.04.5 LTS
- Deployment Method: snap
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Firefox 107.0
- Operating System:  Linux

**Comment by murtaza98** [comment]
@Floflobel Could you please check if the solution described [here](https://github.com/RocketChat/Rocket.Chat/issues/26516#issuecomment-1244173602) solves this issue?

**Comment by murtaza98** [comment]
The error seems to be from the mongo shell - most likely you're using a version that doesn't support `.collection()` method. 

Try to use instead:
`db.rocketchat_settings.deleteOne({ _id: 'Canned_Responses_Enable'  })`

Or if you want to you use MongoDB Compass GUI editor (or any other tool of your liking) to do the same thing :wink: The end goal is to make sure that you remove that particular document entry from your database
