### ISSUE TITLE
Can't send audio messages or videochat while on chrome or chromium (Tested on Linux and Windows)

### ISSUE THREAD

**Issue by leandroqm** [RocketChat/Rocket.Chat#2739]
Your Rocket.Chat version: 0.24.0

Can't initiate or receive audio messages and videochat while using chrome or chromium.
It works on Firefox, either on Linux or on Windows desktops, but won't work with Chrome or Chromium on those.
If I send an audio message from firefox, the user on Chrome/Chromium can listen to it, but he can't record, no matter what OS is used.

Deployment was done through this guide:
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker

Tried the same at https://demo.rocket.chat/channel/general and it works.
Maybe the docker version is not the latest...?

**Comment by engelgabriel** [comment]
Are you deploying with SSL?

**Comment by leandroqm** [comment]
If this goes to production, then yes. For now, there is no SSL/TLS enabled.

**Comment by engelgabriel** [comment]
A few browsers dont support WebRTC without SSL

**Comment by leandroqm** [comment]
Yes, but I can do it on the demo server, just not on the fresh pull from the docker repo.

**Comment by Sing-Li** [comment]
On the demo server, you are **ALWAYS** accessing with SSL - it is **https:**//demo.rocket.chat/ !

**Comment by leandroqm** [comment]
I see. Okay, I will implement SSL/TLS and test it tomorrow and get back to you. :-) Thanks!

**Comment by leandroqm** [comment]
Thank you very much, that solves the issue.
