### ISSUE TITLE
Channel navigation is confusing

### ISSUE THREAD

**Issue by sethfork** [RocketChat/Rocket.Chat#2740]
### Usability Feedback for More Channels view:

**Context:**
I’ve visited the [Startup Study Group Chat](https://ssg.rocket.chat/) around 3-5 times since the initial creation of my account a few weeks ago. Until today, I was a member of just two channels. It wasn’t that I was uninterested in joining the other channels; **it’s just that I actually had no idea that they existed**.

While I’ll admit that my past attempts to find those channels were half-assed at best; those failures still translated into an inability to exchange value with the micro-communities I sought, which thereby led to my inactivity as a user.

**Suggestion:**
The interface I'm referring to is the view you get when clicking **More Channels.** If the channel-navigation controls and indicators were **consolidated into 2-3 objects** (_rather than the 6 the arrows point to_), I’m guessing I would not have had this problem. Also, the default setting for this channel view should be **changed from Joined to All.** The user got to this view by selecting **more channels,** which makes it safe to assume that the user is there to discover new channels that they have not yet joined.
<img width="652" alt="screen shot 2016-03-29 at 8 55 50 pm" src="https://cloud.githubusercontent.com/assets/7088679/14224825/9f850996-f86f-11e5-8a92-952433d3420a.png">

_This is my first real contribution to a public project. I'm excited to watch Rocket Chat develop and I hope to contribute to the product in any way I can!_

Cheers,
Seth

**Comment by marceloschmidt** [comment]
This should now be much better with ffef53e5235a9f932f48d611eb7498799fce485f. Let us know if it there's still something missing.
