### ISSUE TITLE
Make previews for PDF files

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2741]
Your Rocket.Chat version: 0.24.0
It would be great to make previews for first page of PDF-book, attached or linked to the chat.

**Comment by Bitti09** [comment]
:+1:

**Comment by nishimaki10** [comment]
:+1:

**Comment by amadou009** [comment]
Hello, someone can helpe me. I want to customize Rocket.chat but i don't know which documents i have to modify.

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap so we will revisit once other priorities have been addressed.
