### ISSUE TITLE
Unable to join a public channel in read-only mode

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27412]
### Description:

When entering a channel that is in read-only or broadcast mode, the Join button is not visible, only the inscription "This room is read only" is visible.

### Steps to reproduce:

1. A simple user enters the channel in read-only mode.
2. He cannot join the channel because there is no button to do so.

### Expected behavior:

A non-administrator user can by himself join channels in read-only mode.

### Actual behavior:

Demo using open.rocket.chat
![pubrochan](https://user-images.githubusercontent.com/104189570/204752332-9baf05ac-5ecf-4223-bc94-580dc84d13c9.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.3
- Operating System:  Oracle Linux 8.5
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14

Also reproduced on open.rocket.chat

### Client Setup Information

- Desktop App or Browser Version: Chrome 107.0.5304.88 
- Operating System: Windows 10

### Additional context

The channel administrator can add such a user manually.

**Comment by henit-chobisa** [comment]
Hey @shevchukma, thank you so much for opening the issue.
Actually, Read-only is only required to allow read-only access to the room, it doesn't promise or include membership.
Hence, it would be better if you can clarify a bit more on this, about the end goal you are thinking of.

**Comment by shevchukma** [comment]
Hi @henit-chobisa. I do not think so. You can join a read-only channel with the /join command.
In version 4.8.*, the Join button was present in the interface for such channels.
The main inconvenience is that when you have not joined the channel, it is not in your contact list. Every time it needs to be found using the search.

**Comment by henit-chobisa** [comment]
Hey @shevchukma, hope you're doing good.

Thank you so much for opening this issue, I have resolved this, keeping in mind your perspective.

Kindly have a look on the PR and I would be grateful if you can respond me with your thoughts on any helpful additions.

Thank You 🙏

**Comment by shevchukma** [comment]
Thank you @henit-chobisa!
