### ISSUE TITLE
Search by username

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2742]
Your Rocket.Chat version: 0.24.0
It would be great to search not only by message text, but by usernames too (case insensitive, of course.)

**Comment by lvh1** [comment]
Might as well go all-out with it, like this:
![](https://i.imgur.com/YgBbkPL.png)
But that would require quite some work/testing :p

**Comment by zxweed** [comment]
At this time for me will be enougth just include the username in search scope, without any GUI changes

**Comment by dytec** [comment]
There are existing channel search options:  **from:**username and **mention:**username

**Comment by dytec** [comment]
#2722

**Comment by lvh1** [comment]
Nice, guess it should just be documented then.

**Comment by zxweed** [comment]
@dytec, thank you for info
