### ISSUE TITLE
Messages from Realtime subscriptions do not have an unique id 

### ISSUE THREAD

**Issue by antoniozh** [RocketChat/Rocket.Chat#27430]
### Description:

When subscribed to a room. the messages from the subscription sent by the Rocket.Chat server do not have an unique id, it seems that somewhere in the server instead of the id variable, an "id" string is sent by mistake. 

### Steps to reproduce:

Subscribe to a room
Write a message in the room
Capture the WebSocket response

### Expected behavior:

The response should have an randomly generated ID 

### Actual behavior:

The response has the id set to the string "id"

### Server Setup Information:

The current Rocket.Chat trial server:

```
+--------------------------------------------------------+ 
|                     SERVER RUNNING                     | 
+--------------------------------------------------------+ 
|                                                        | 
|  Rocket.Chat Version: 5.3.1                            | 
|       NodeJS Version: 14.19.3 - x64                    | 
|      MongoDB Version: 4.4.16                           | 
|       MongoDB Engine: wiredTiger                       | 
|             Platform: linux                            | 
|         Process Port: 3000                             | 
|             Site URL: https://softbauware.rocket.chat  | 
|     ReplicaSet OpLog: Enabled                          | 
|          Commit Hash: a639f2002a                       | 
|        Commit Branch: HEAD                             | 
|                                                        | 
+--------------------------------------------------------+ 
```
### Client Setup Information

- Desktop App or Browser Version: A modified Rocket.Chat.Net client I am currently working on 

### Relevant logs:

`{"msg":"changed","collection":"stream-room-messages","id":"id","fields":{"eventName":"GENERAL","args":[{"_id":"ppnsxvZCmfNAge69R","rid":"GENERAL","msg":"Hello!","ts":{"$date":1669973272961},"u":{"_id":"initialuser","username":"softbauware","name":"softbauware"},"_updatedAt":{"$date":1669973272988},"urls":[],"mentions":[],"channels":[],"md":[{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"Hello!"}]}]}]}}`

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

Check the following docs:
https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/integration-endpoints/create#outgoing-webhook
https://docs.rocket.chat/use-rocket.chat/workspace-administration/integrations#outgoing-webhook-script

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
