### ISSUE TITLE
Context menu is bouncing in small window

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat#27445]
### Search before asking

- [x] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [X] Linux

### Operating System Version

Windows 10, Ubuntu 21.10

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.8.13

### Rocket.Chat Server Version

5.3.4

### Describe the bug

If the application window or web browser window isn't big enough to show the whole menu, it bounces.
I have the same problem with Linux snap and deb and Windows 10 exe versions.

It works normally if I change the size of the app or browser window to show the whole context menu.

### How to Reproduce

Reduce the window's height, so the entire context menu does not fit.

### Describe your Expected behavior

Show context menu without bouncing.

### Anything else

Video preview: https://user-images.githubusercontent.com/1219067/205139571-5a7dd72f-91d0-4abe-bec0-600443fb8ff7.mp4

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by graywolf336** [comment]
https://user-images.githubusercontent.com/850391/212151573-c7faeba8-5c44-4bfb-aad0-df4124f97097.mov

Another example of it happening, except this time inside of threads

**Comment by hugocostadev** [comment]
Fixed by: https://github.com/RocketChat/fuselage/pull/967
