### ISSUE TITLE
Messing up the amazon S3 Configuration leads to (admin/general) lockout

### ISSUE THREAD

**Issue by stunder** [RocketChat/Rocket.Chat#2746]
I updated the FileUpload Max size from 2097152 to 20097152 then I enabled Amazon S3 storage and saved my information.  After this the frontend began "retrying connection"  I eventually accessed the default root of the serer and now I am getting 503 errors.   Is there a way to change the FileUpload settings back to default?  I can see the changes in the DB but the service will not start.

**Comment by sampaiodiego** [comment]
@stunder did you see any message at server logs?
you can see them under `Adminstration > View Logs`

**Comment by stunder** [comment]
@sampaiodiego I just got done rebuilding the server.  After the lockout I was unable to get the server to accept any connections that would get me to the View Logs.   I have now built 3 servers 2 for me to develop/test on and 1 that I can point most of my users to. I will retry the error situation tonight and report back.

**Comment by sampaiodiego** [comment]
ok.. thanks..
if it get stuck, view the logs directly from the server.. for example with: `docker logs`, `pm2 logs`, etc. depending how you deployed your rocket.chat

**Comment by Lochemage** [comment]
@sampaiodiego 

I did this as well, my problem was that I had changed Amazon S3 Region setting to an invalid value and apparently it causes the server to crash on startup.

In my case, I had to SSH into the mongodb directly and apply the following:
```
use rocketchat
db.rocketchat_settings.update({_id: "FileUpload_S3_Region"}, {$set: {value: "us-west-2"}})
```

Hope this helps.

**Comment by engelgabriel** [comment]
Thanks for the info @Lochemage
