### ISSUE TITLE
Server 5.4 thinks I'm permanent online and delays push notifications

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat#27465]
### Description:

After upgrading to 5.4, the server thinks I'm permanently online and delays all push notifications by minutes. Watching myself with a different user I'm also not falling into "away" after the configured time.

### Steps to reproduce:

1. I'm online in RC
2. I'm logging out, I even pressed "log out from other sessions" on my iPhone - nothing helps
3. RC server permanently thinks I'm online
4. All push messages to my IOS devices are delayed because the server thinks I have a browser open.

### Expected behavior:

With no session active I should get push notifications immediately and fall to "away" after the configured time.

### Actual behavior:

I'm shown permanently online and all push notifications are sent delayed

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Ubuntu 20.04 LTS
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.18 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Additional context

A display of all active sessions (including sessions of which the server "thinks" they are there) in the UI with the ability to kill a session would be a benefit.

Apart from this, a hotfix to get this back into a good state would be appreciated.

I'm the only user where this happened.

Server restart and system reboot does not help!

**Comment by jacotec** [comment]
Similar to #27145 . I could solve it by manually deleting the entries in "usersSessions" in the MongoDB.
However, manually patching in the DB should not be the normal use case, so I'll leave this open. The root cause of a stuck session must be fixed.

**Comment by CR0815** [comment]
I've just opened https://github.com/RocketChat/Rocket.Chat/issues/27468 because i'm affeected as well and just saw your report afterwards. So we're already 2 affected instances :(

**Comment by bseclier** [comment]
The issue is still in 5.4.10 and the UsersSessions cleanup didn't solve the problem.
