### ISSUE TITLE
Links in topic and announcement do not open in a new browser tab

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27473]
### Description:

While links in messages or the link to the Rocket.Chat homepage in the bottom left corner open in a new browser tab per default, links in the topic and in the announcement don't.

### Steps to reproduce:

1. Set the topic or the announcement of a channel to https://youtu.be/E8gmARGvPlI.
2. Click on that link in the topic/announcement with the left mouse button.

### Expected behavior:

The link opens in a new browser tab.

### Actual behavior:

The link opens in the same browser tab. This means I leave Rocket.Chat.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Deployment Method: Docker
- Number of Running Instances: 1

### Client Setup Information

This issue occurs on all browsers and operating systems as the `target="_blank"` attribute is simply missing.

**Comment by hugocostadev** [comment]
Hi @paulchen this is a known issue and already has an open PR, thanks! 

Pull Request: https://github.com/RocketChat/Rocket.Chat/pull/27554
