### ISSUE TITLE
Cant upgrade RocketChat

### ISSUE THREAD

**Issue by Gabe88def** [RocketChat/Rocket.Chat#27474]
Description:
Followed the standard upgrade procedure I use, manually each time on my server. Usually on first startup there are some migrating outputs, but this time it just immediately failed to start.

Steps to reproduce:
Start with 3.0.3 server, then manually upgrade by using the following commands:

curl -L https://releases.rocket.chat/latest/download -o /tmp/rocket.chat.tgz
tar -xzf /tmp/rocket.chat.tgz -C /tmp
cd /tmp/bundle/programs/server && npm install
sudo mv /tmp/bundle /opt/Rocket.Chat
sudo chown -R rocketchat:rocketchat /opt/Rocket.Chat
sudo systemctl start rocketchat
Expected behavior:
RocketChat starts are normal.

### Actual behavior:

![rc](https://user-images.githubusercontent.com/119975343/206023086-942412db-47d3-48fc-a581-fe533eaf2235.PNG)

### Server Setup Information:

Version of Rocket.Chat Server: 3.0.3
Operating System: CentOS 7.7
Deployment Method: tar (manual)
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: v12.0.0
MongoDB Version: db version v4.0.28

###Currently stuck on
[root@173-255-193-20 ~]# systemctl status rocketchat
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/usr/lib/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-12-06 14:57:22 CST; 8s ago
  Process: 31273 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=203/EXEC)
 Main PID: 31273 (code=exited, status=203/EXEC)

Dec 06 14:57:22 173-255-193-20.ip.linodeusercontent.com systemd[1]: Started The Rocket.Chat server.
Dec 06 14:57:22 173-255-193-20.ip.linodeusercontent.com systemd[1]: rocketchat.service: main process exited, code=...XEC
Dec 06 14:57:22 173-255-193-20.ip.linodeusercontent.com systemd[1]: Unit rocketchat.service entered failed state.
Dec 06 14:57:22 173-255-193-20.ip.linodeusercontent.com systemd[1]: rocketchat.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by jeffclay** [comment]
I hope your RC instance isn't exposed to the internet. Version 3.x has some severe vulnerabilities. 

That said, are you downloading the pre-built bundle from https://releases.rocket.chat/{version}/download or are you downloading the tar file from https://github.com/RocketChat/Rocket.Chat/releases  ? 

Not that it helps much now, but I'm currently working on a upgrade script in python; moving our old server from 2.1.0 to current.

**Comment by Gabe88def** [comment]
@jeffclay First link didn't open and Im going to try again using the tar file. Been trying to do this for some time and want to get it updated to current as well. CentOS is the what it's running of of. I'll update this and provide some details after trying again.

**Comment by Gabe88def** [comment]
@jeffclay Would it be in increments? version 3.x -> 4.x -> 5.x?

**Comment by jeffclay** [comment]
@Gabe88def No, unfortunately there are many db migrations between major versions. You have to iterate through each minor version (3.x.x, 4.x.x, etc.) all the way up. There are 187 versions between 3.0.3 and 5.4.0. I've found that 3.3.1, 3.3.2 and 3.12.2 don't have bundles available for download, so you have to skip those.

In reality not all 187 of those version have database migrations but there isn't a way to determine (from github release page notes) which versions do or do not have migrations; so we are stuck installing each one.

**Comment by jeffclay** [comment]
The log is cut off, I can't tell what's going on. Please show the full log from when you start the RC service until it dies.

**Comment by Gabe88def** [comment]
@jeffclay Appreciate that. these are the logs

Dec 07 13:22:25 173-255-193-20.ip.linodeusercontent.com setroubleshoot[3397]: SELinux is preventing /usr/bin/mongod from read access on the file snmp. For complete SELinux messages run: sealert -l 8eb3584c-7467-4594-bff4-ecfaac5007e1
Dec 07 13:22:25 173-255-193-20.ip.linodeusercontent.com python[3397]: SELinux is preventing /usr/bin/mongod from read access on the file snmp.

                                                                      *****  Plugin catchall (100. confidence) suggests   **************************

                                                                      If you believe that mongod should be allowed read access on the snmp file by default.
                                                                      Then you should report this as a bug.
                                                                      You can generate a local policy module to allow this access.
                                                                      Do
                                                                      allow this access for now by executing:
                                                                      # ausearch -c 'ftdc' --raw | audit2allow -M my-ftdc
                                                                      # semodule -i my-ftdc.pp

^C

**Comment by Gabe88def** [comment]
Changed the /opt/Rocket.Chat to rocketchat
![image](https://user-images.githubusercontent.com/119975343/206283344-1644b0f8-7c85-4bdb-8ea7-64e618e41306.png)

**Comment by jeffclay** [comment]
You're struggling because you're not looking at full logs. You're just posting small snippits of the full picture.

Follow these instructions:
1.  Open an SSH session to the server. 
2. Become root (sudo su -) or (su -) however you normally do it.
3.  Open a second SSH session to the server.
4. Become root (sudo su -) or (su -) however you normally do it.
5. In 1 of the 2 sessions (it doesn't matter which)  - type 'journalctl -f' and press enter. This will start following all of the systems logs. Leave this running and proceed to the next step.
6. In the remaining session (the one not running journalctl -f) type 'systemctl restart rocketchat' and press enter.
7. Go back to the session that's running journalctl and watch it.

The log information that's useful will begin where it says 'Started The Rocket.Chat server.'  and end when you see the line 'systemd[1]: rocketchat.service: Main process exited' or similar.   That's the information that will help diagnose the issue.

**Comment by dudanogueira** [comment]
Hi!

This is really not the right place to have this, as this is not an Issue with the Software, but a deployment issue.

**We strongly do not suggest running it manually, as you will deal with a lot of dependencies, specially while migrating.**

A clear path of upgrade is:

1 - Backup your data from your current instance
2 - Run a docker deployment with the same version you are running for staging
3 - Restored backed up data into this new docker container
4 - Migrate version, and don't skip majors, go 3.x > 4.x > 5.x
5 - Test your environment

After validated, plan and execute the migration in production

I will close for now, but please, feel free to join our [Forums](https://forums.rocket.chat/) and [Support Channel](https://open.rocket.chat/channel/support) or keep the discussion here :shrug:
