### ISSUE TITLE
Profile shows Local Time 0

### ISSUE THREAD

**Issue by darkufo** [RocketChat/Rocket.Chat#27472]
### Steps to reproduce:

1. Goto the Full Profile of one of the members who is on the same timezone as you
2. Scroll down till you see the Local Time section

### Expected behavior:

Local Time should show the local time / zone

### Actual behavior:

Local TIme is set to 0
![chrome_2022-12-06_19-09-35](https://user-images.githubusercontent.com/12990410/206003778-70c21f08-fdd3-45ee-b4cd-7406ae42717e.png)

### Server Setup Information:

Deployment
Version
5.4.0

Deployment ID
7nWQCAJsN7XfZagJ7

Apps Engine Version
1.36.0

Node Version
v14.19.3

Database Migration
281 (December 6, 2022 5:39 PM)

MongoDB
5.0.12 / wiredTiger (oplog Enabled)

Commit Details
HEAD: (51f456a54)

Branch: HEAD

### Client Setup Information

- Chrome Stable (same problem happens on Safari)
- Windows 11 (Also MacOS)

**Comment by hugocostadev** [comment]
Is it still happening?  I could not reproduce here... 
Is this a localhost server? Witch user is that, a real one? 

Try to upgrade to our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) 

If you are still facing this issue, please, reopen it and provide us with more info about the server and browser.
