### ISSUE TITLE
Problem with app apis: api.computedPath is undefined

### ISSUE THREAD

**Issue by sviat9440** [RocketChat/Rocket.Chat#27477]
### Description:

Problem with app apis: api.computedPath is undefined

### Steps to reproduce:

```
export class MergeRequestsEventsHook extends ApiEndpoint {
    public static readonly path = 'merge_requests';

    public readonly path = 'merge_requests';

    public constructor(
        app: IApp,
    ) {
        super(app);
    }

    public async post(
        request: IApiRequest, endpoint: IApiEndpointInfo, read: IRead, modify: IModify, http: IHttp, persis: IPersistence,
    ): Promise<IApiResponse> {
        this.app.getLogger().log(request);
        return this.success('{}');
    }
}

export class WebhooksApi implements IApi {
    public readonly visibility: ApiVisibility.PRIVATE;

    public readonly security: ApiSecurity.UNSECURE;

    public readonly endpoints: Array<IApiEndpoint> = [
        new MergeRequestsEventsHook(this.app),
    ];

    public constructor(
        private app: IApp,
    ) {
    }
}
```

```
export class MyApp extends App {
    constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
        super(info, logger, accessors);
    }

    protected async extendConfiguration(configuration: IConfigurationExtend, environmentRead: IEnvironmentRead): Promise<void> {
        await super.extendConfiguration(configuration, environmentRead);
        await configuration.api.provideApi(new WebhooksApi(this));
    }
}
```

### Expected behavior:

Url is `https://rocketchat.b2bpolis.ru/api/apps/public/d1b309e5-630a-4363-8bb5-ec0a1bc230a7/merge_requests`
When send POST request to this url, I see status 200. 

### Actual behavior:

Url is `https://rocketchat.b2bpolis.ru/undefined/merge_requests`

![Снимок экрана от 2022-12-07 10-05-54@2x](https://user-images.githubusercontent.com/13107421/206111299-930ec89f-926d-4e43-9d62-1a4145df22f1.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.0
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version:  v14.19.3
- MongoDB Version: 4.4.17
- Apps engine Version: 

### Client Setup Information

not relevant

### Additional context

POST to `https://rocketchat.b2bpolis.ru/api/apps/public/d1b309e5-630a-4363-8bb5-ec0a1bc230a7/merge_requests`, returns 404 with no content

POST to some undefined endpoint like `https://rocketchat.b2bpolis.ru/api/apps/public/d1b309e5-630a-4363-8bb5-ec0a1bc230a7/abcdef`, returns 404 with `Not found` text.

So, it reacts to the presence or absence of endpoint. But the endpoint method is not called, and 404 is returned with an empty response.

### Relevant logs:

I cannot found any in rocket logs or app logs

**Comment by debdutdeb** [comment]
```ts
public readonly visibility: ApiVisibility.PRIVATE;
public readonly security: ApiSecurity.UNSECURE;
```

You're setting the types, not the values. 

Switch to,

```
public readonly visibility = ApiVisibility.PRIVATE;
public readonly security = ApiSecurity.UNSECURE;
```

and it should work.

**Comment by sviat9440** [comment]
Oh, thank you! I wasted several hours trying to figure out what the problem was (
