### ISSUE TITLE
Correct E2E password does not work in RC 5.4.0 on consecutive logins

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#27476]
### Description:

Reset E2E password does not work on consecutive logins.

Resetting E2E key works but the offered key is not accepted on consecutive logins.

### Steps to reproduce:

1. Enable E2E in admin settings
2. Login as usual into RC
3. Type in your existing E2E-password, or copypaste the new one you got, or reset your password or key

### Expected behavior:

The new E2E-password should be queried at the top of the page on consecutive logins. The new password should be accepted as a correct one.

### Actual behavior:

The new key password is not queried at all on consecutive logins (no banner visible). You cannot copypaste the new password anywhere safe as it is not shown at all.

At this stage after you change the E2E password under your profile settings, after the next login you finally see the banner to type the password in. However the correct password is claimed to be wrong.
![Screenshot from 2022-12-07 08-34-08](https://user-images.githubusercontent.com/6958942/206106170-484ad788-7b86-4b27-b007-0f31906f02e5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox and Chrome

### Additional context

Also reproducible at open.rocket.chat.

E2E password management still worked in RC 5.3.x.

**Comment by ksba2004** [comment]
I would like to work on this issue, Please assign this to me.

**Comment by Raptor3um** [comment]
I have the same issue on 5.4.0

**Comment by arthur-trt** [comment]
We've got the same issue in 5.4.1

**Comment by zajinx** [comment]
same on my 5.4.0 deployment, if i use the option rest e2e key, it works only on the device were i used this option. anything complains about wrong password or if i do manage to add it when i try to send a message it says ‘Cannot read properties of undefined (reading ‘slice’)’ 


Version of Rocket.Chat Server: 5.4.0
Operating System:  Ubuntu 20.04.5 LTS
Deployment Method: snap 5.x/stable
Number of Running Instances: 1
NodeJS Version: 14.19.3
MongoDB Version: 4.4.15 / wiredTiger (oplog Enabled)

**Comment by zajinx** [comment]
any updates?

**Comment by Gummikavalier** [comment]
I guess there is a big crunch behind the scenes to complete RC 6.0 as most of the stuff has been dormant in Github for many weeks now. I expect any changes done to be backported to RC 5 on the regard of main features such as this.

**Comment by zajinx** [comment]
I just checked on 5.4.2 and the issue went away, I don't see anything in the latest changelog for rocket chat server about this

**Comment by Gummikavalier** [comment]
The issue was not fixed for me after resetting the E2E key; the user is still not shown the new key. Also resetting the password of the key in the settings does not work. (After logout the new password is told to be wrong.)

**Comment by fapgomes** [comment]
On RC 5.4.3 the issue stills present.

**Comment by Gummikavalier** [comment]
Fixed in RC 6.0. Closing.
