### ISSUE TITLE
[BUG] RocketChat Desktop start with blank screen

### ISSUE THREAD

**Issue by Amteco** [RocketChat/Rocket.Chat#27480]
[BUG] RocketChat Desktop app when start first time its load list of channels/users but when you click on any channel its just show 3 dots animate - like loading and nothing happened, you can try on other channels and always is the same. Its never finish loading.

When you start typing message to channel then only start loading message history

System config:
Rocket Chat Desktop 3.8.13 - on previous version problem doesn't exist
Linux Manjaro 5.15.87-1 Plasma X11

**Comment by hugocostadev** [comment]
duplicated of #27490
