### ISSUE TITLE
Search : Arrow up doesn't work

### ISSUE THREAD

**Issue by matthias4217** [RocketChat/Rocket.Chat#27489]
### Description:

WHen using the search function (`Ctrl+K` or via the search button), using the arrow down key press works fine. However, the arrow up doesn't work. In the Electron client (on Ubuntu 22.04), it does nothing. In the web browser (Firefox), it sometimes allow to go up once. (Maybe depending on the type - channel or private message.)

### Steps to reproduce:

1. Click on the search button or use `Ctrl+K`
2. Scroll down with the down arrow
3. Scroll up with the up arrow - this won't work

### Server Setup Information:

- Version of Rocket.Chat Server: `5.3.3`
- Operating System: 
- Deployment Method: Openshift microservice deployment, using RocketChat's helm chart.
- Number of Running Instances: Several
- DB Replicaset Oplog: 
- NodeJS Version: `14.19.3`
- MongoDB Version: `5.0.13`

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Ubuntu `22.04.1`

### Error log

```
Uncaught TypeError: n.previousSibling is null
    ne /client/sidebar/search/SearchList.tsx:1
    t https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:13
    ArrowUp /client/sidebar/search/SearchList.tsx:1
    u /node_modules/tinykeys/dist/tinykeys.module.js:1
    u /node_modules/tinykeys/dist/tinykeys.module.js:1
    c /node_modules/tinykeys/dist/tinykeys.module.js:1
    e /client/sidebar/search/SearchList.tsx:1
    lu https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
    unstable_runWithPriority https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1148
    _a https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
    su https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
    ze https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
    ft https://chat.cc.in2p3.fr/83abe46b061083047cf3c29178b6077f40f1d1aa.js?meteor_js_resource=true:1130
3 83abe46b061083047cf3c29178b6077f40f1d1aa.js:1:3665
```

**Comment by dudanogueira** [comment]
Hi! Can you reproduce it this in latest version?

[Our open server](https://open.rocket.chat/) runs it, and I was not able to reproduce it there.

Thanks!

**Comment by matthias4217** [comment]
It looks like this is not as straightforward as I initially thought, but I think I have found the cause : on the servers where I have this issue, I have a room and a direct message channel as favourites. Adding a room as favourite on an instance (in `5.3.3` and `5.4.0`) where I previously didn't have this issue, triggers it.

However, I haven't been able to reproduce it on `open.rocket.chat`. I wonder if it's because I haven't been in enough rooms and direct message channels. So there may be some other conditions for this error to happen.
