### ISSUE TITLE
Sperate gateway for iOS and android push

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#2748]
Your Rocket.Chat version: 0.24 dev

I am using my own key and product number for the gcm settings but the apn stuff is all blank. The gateway is disabled so gcm works with my android build, but that also disabled notifications for the app store version for iOS.
I can afford the $25 to publish my android app but not the $200 for iOS, also from what I read you need a mac to compile it as well.
I was hoping it would be possible to use the default gateway for iOS but my own rocketchat server for gcm.

**Comment by rasos** [comment]
Yes, it would be great to be able to choose per OS  whether I use the push service with the Rocket.Chat gateway and their genuine Apps or if I build my own and establish a separate push service, but probably not for all platforms.

**Comment by MartinSchoeler** [comment]
Please reopen this issue in the respective android/ios repositories. Thanks!
