### ISSUE TITLE
Can not edit or delete comment

### ISSUE THREAD

**Issue by gretalee** [RocketChat/Rocket.Chat#27492]
A comment's context menu (three dots) does not open anymore. Nothing happens, when I click on the context-menu-button (see screenshot). 
Because of that I am not able to edit or remove a comment. 

This happens since the last app update. I am on 3.8.14. 
My OS is OSX 12.6 (Monterey)

![Bildschirmfoto 2022-12-08 um 10 44 15](https://user-images.githubusercontent.com/236321/206414738-f5992bbe-07f4-4a22-abdf-fcde93716e75.png)

**Comment by hugocostadev** [comment]
Hi there!

Sorry, this error does not happen on the latest releases.

[[Rocket.Chat](https://rocket.chat/)](https://rocket.chat/) provides support for 6 months to the latest releases of each major version.

I would suggest you update your [[Rocket.Chat](https://rocket.chat/)](https://rocket.chat/) version to the latest stable version, which you can find it here: [https://github.com/RocketChat/Rocket.Chat/releases](https://github.com/RocketChat/Rocket.Chat/releases)

For more information about your support: [https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions](https://docs.rocket.chat/getting-support/enterprise-support#rocket.chat-versions)

**Comment by gretalee** [comment]
Hello @hugocostadev,
that is good to know. Unfortunately the AppStore provides this old version. And the App itself does not announce, that there is some newer one. Could you please give me a link to an installer package for desktop usage? 
I am using the app on my MacBook.

<img width="726" alt="Bildschirmfoto 2022-12-16 um 16 49 19" src="https://user-images.githubusercontent.com/236321/208136921-06032bbc-12c5-4c51-93ca-6520c225f225.png">

<img width="614" alt="Bildschirmfoto 2022-12-16 um 16 52 44" src="https://user-images.githubusercontent.com/236321/208137114-4cb04488-11a8-4268-8552-2e373a2e56f7.png">

**Comment by hugocostadev** [comment]
Sorry, @gretalee I thought that you are mentioning the server version, not the desktop client. 

Anyway, this issue was fixed on the last release (server) 5.4.0, you can update the version get this resolved
