### ISSUE TITLE
 [Bug] Sticky Announcement Bar links are now opening  internally instead of being opened in external browser/app and there is no easy way to go back to the rocket chats.

### ISSUE THREAD

**Issue by Kiran-khan-Com** [RocketChat/Rocket.Chat#27496]
Device: Desktop App 
Browser : Any
For instance I open a link from one of my channel's announcement link and instead of opening in my browser tab, it opens within the rocket.
![image](https://user-images.githubusercontent.com/77098540/206503324-1613d4bb-7862-4150-961c-c5035e6f57c6.png)

**Comment by dudanogueira** [comment]
Hi @Kiran-khan-Com! Thanks for pointing out.

Please, fill in the issue template when opening an issue. Those are really important to us.

I tested, and indeed the behavior changed on newer 5.4 comparing with 4.8.X

This will also have a non optimal behavior for the App, so I think is indeed a great thing to change.
