### ISSUE TITLE
RC 5.4.0 no login possible

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat#27490]
Since Rocket Chat 5.4.0 you can't login anymore. 
Regardless if you use RC Electron Client or normal Webbrowser you end up at a empty screen.
![rc](https://user-images.githubusercontent.com/1355173/206385856-a1e65542-5db0-4776-9424-388876d4c762.gif)

```
Uncaught (in promise) undefined https://some.chaturl.abc/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1458
``` 

Snap RC 5.4.0
Chrome/Firefox/RC Client

https://github.com/RocketChat/Rocket.Chat/issues/27480 sounds similar

# update
It does not work anymore if OAuth is enabled and "Show Default Login Form" disabled. You need to enable the normal login, if you can use it or not to workaround that problem.

**Comment by dcardozoo** [comment]
We had the same problem. We had OAuth login only, after reactivating the normal login option on the Admin settings (thankfully we had before the update the session open), it was working again. 

it seems a Bug at least for us, when the normal Login is deactivated. Hope for a fix soon :)

**Comment by CvH** [comment]
we have also just OAuth

**Comment by dcardozoo** [comment]
If you can, just for testing activate also the normal login. At least so, you can login again

**Comment by CvH** [comment]
If I enable "Show Default Login Form" at the settings it works again.
If you have locked out yourself this might help https://github.com/RocketChat/Rocket.Chat/issues/3760#issuecomment-274359537 (not tested if it actually works)

**Comment by tuxcrafter** [comment]
I can confirm this regression bug with version from 5.4.0 yesterday at 17:56 CET. I had to enable Accounts_ShowFormLogin to be able to login again.

I am using SAML login only, this command has saved me several times in the past to enable to login form:

curl --location --request POST 'http://localhost:3000/api/v1/settings/Accounts_ShowFormLogin' \
--header 'X-Auth-Token: <secret>' \
--header 'X-User-Id: N3H9ef5FdjXNX3iRa' \
--header 'Content-type: application/json' \
--data-raw '{ "value": true }'

**Comment by tuxcrafter** [comment]
sudo snap revert rocketchat-server revert my installation to a working state

**Comment by shevchukma** [comment]
I confirm this issue. For us it is critical. The update is not possible until the problem is fixed. We are running 20 instances RC in docker.

**Comment by mikesrus** [comment]
affected too. saml login not work

**Comment by ThibautPlg** [comment]
Same here. Thankfully the upgrade to 5.4.0 did not reset the user sessions and we noticed the bug only when inviting new users to the instance. 
The [workaround](https://github.com/RocketChat/Rocket.Chat/issues/27490#issuecomment-1342248720) works well, thanks @dcardozoo and @CvH .

**Comment by jacotec** [comment]
Before I open a new issue - maybe it's related to this issue:

I've configured OAuth (Keycloak) as a second login source ... all looks great, but there is no additional login button for this on the login screen. Do you see the same behavior in 5.4.0?

**Comment by dudanogueira** [comment]
@jacotec I was not able to reproduce this =\

**Comment by mikesrus** [comment]
19 jan 2023 still no snap with 5.4.1 and issue still active 

```
root@chat:~# snap info rocketchat-server
name:      rocketchat-server
summary:   Rocket.Chat server
publisher: Rocket.Chat (rocketchat✓)
store-url: https://snapcraft.io/rocketchat-server
contact:   https://open.rocket.chat/channel/ubuntu-snap
license:   unset
description: |
  Have your own Slack like online chat, built with Meteor. https://rocket.chat/
commands:
  - rocketchat-server.backupdb
  - rocketchat-server.mongo
  - rocketchat-server.restoredb
services:
  rocketchat-server.rocketchat-caddy: simple, disabled, active
  rocketchat-server.rocketchat-mongo: forking, enabled, active
  rocketchat-server:                  simple, enabled, active
snap-id:      xxxxxxxxxxxxxxxxxxxxxxxxxxxx
tracking:     5.x/stable
refresh-date: 42 days ago, at 04:05 MSK
channels:
  5.x/stable:       5.4.0  2022-12-07 (1536) 300MB -
  5.x/candidate:    5.4.0  2022-12-07 (1536) 300MB -
  5.x/beta:         5.3.4  2022-11-30 (1532) 292MB -
  5.x/edge:         5.4.0  2022-12-07 (1536) 300MB -
  latest/stable:    3.18.7 2022-07-01 (1521) 289MB -
  latest/candidate: 3.18.7 2022-07-01 (1521) 289MB -
  latest/beta:      3.18.7 2022-07-01 (1521) 289MB -
  latest/edge:      4.1.2  2021-12-06 (1497) 285MB -
  4.x/stable:       4.8.7  2022-12-04 (1533) 281MB -
  4.x/candidate:    4.8.3  2022-08-08 (1523) 278MB -
  4.x/beta:         4.8.3  2022-08-08 (1523) 278MB -
  4.x/edge:         4.8.7  2022-12-04 (1533) 281MB -
  3.x/stable:       3.18.7 2022-07-01 (1521) 289MB -
  3.x/candidate:    3.18.7 2022-07-01 (1521) 289MB -
  3.x/beta:         3.18.7 2022-07-01 (1521) 289MB -
  3.x/edge:         3.18.7 2022-07-01 (1521) 289MB -
  2.x/stable:       2.4.14 2020-12-23 (1453) 267MB -
  2.x/candidate:    2.4.14 2020-12-23 (1453) 267MB -
  2.x/beta:         2.4.14 2020-12-23 (1453) 267MB -
  2.x/edge:         ↑                              
installed:          5.4.0             (1536) 300MB -
```

should we migrate to docker?
snap package won't be updated anymore?

**Comment by CvH** [comment]
@mikesrus
> snap package won't be updated anymore?

just main versions get (looks like) updated, bug fix versions are manually pushed (or broken automated)
last security bug fix took 4 months to arrive :) 
Luckily nobody cares and nobody maintains it. Docker is not better, there it looks also broken,

https://github.com/RocketChat/Rocket.Chat/issues/27677
https://github.com/RocketChat/rocketchat-server-snap/issues/49

@debdutdeb used to maintain it but that looks like a thing from the past :(
