### ISSUE TITLE
Cannot add pics anymore

### ISSUE THREAD

**Issue by RichWasHere** [RocketChat/Rocket.Chat#27494]
Galaxy S21+
App Version 4.33.0.36481
Server version 3.17.0

Previously, I could add a pic to a chat and have it appear inline.  Last time I was able to do this was Dec 5. On Dec 6th, I was prompted by Google Play to update the app, and now my posted pics do not appear in the chat. The filename appears as a hyperlink, and the file must be downloaded to be viewed.

**Comment by RichWasHere** [comment]
Upon some more testing, this appears to be connected to the way the photo app modifies files. An unedited photo can be added with no issue. A picture downloaded from the internet can be added with no issue. However, using the phot edit tools in the Gallery app on the phone causes the images to not work inline.

**Comment by dudanogueira** [comment]
Hi!

Please, fill in the issue template before opening and Issue.

I will close it here, and please, open it on the React Native repo:
https://github.com/RocketChat/Rocket.Chat.ReactNative

Thanks!
