### ISSUE TITLE
[BUG] IPostMessageReacted returns field named `isRemoved` instead of `isReacted`

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Rocket.Chat#27497]
### Description:
- AppsEngine have `IPostMessageReacted`, **Handler for after a message get a reaction or a reaction got removed** . has method `executePostMessageReacted` which takes one of the parameter of type `IMessageReactionContext` which includes **isReacted** field to know whether the emoji has been added or deleted. But everytime if we react with emoji in messages instead of having a `boolean` value in **isReacted** field, we are getting `undefined` regardless the operation we are making ( add or delete ).

- Reason for having value as `undefined` everytime is from RocketChat, we are returning the field named `isRemoved` instead of `isReacted`. [Have a look over here](https://github.com/RocketChat/Rocket.Chat/blob/b12e64c661b2ecfa09e07ccab1cdcd38b79cd439/apps/meteor/app/apps/server/bridges/listeners.js#L88). But Expected field should have name `isReacted` as per the [docs](https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/messages_imessagereactioncontext.imessagereactioncontext.html).

### Steps to reproduce:

1. Implement `IPostMessageReacted` in RocketChat App.
2. log `isReacted` field in console.
3. Deploy the app and React any message with emoji and check console.

`OR` 

- Set up this [playground](https://github.com/Nabhag8848/RC-Apps-Snippets/tree/playground) app to avoid the step 1 and follow rest of steps.

### Expected behavior:

- Instead of having `undefined` in `isReacted` we are expecting it to be `boolean` value as to know the emoji operation within message (add or delete).

### Actual behavior:
- As we can see, getting isReacted field as `undefined`
![isReactedField undefined](https://user-images.githubusercontent.com/65061890/206540130-ef5cd1b9-32c8-413f-9f19-258ec34a58b8.png)

### Note: 
- [x] willing to work on this.

**Comment by Nabhag8848** [comment]
Working on it🚀.

**Comment by dudanogueira** [comment]
Thanks @Nabhag8848 ! That's a nice catch!
