### ISSUE TITLE
Emoji together with the word

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27505]
### Description:
Hello.
Our users ask us to add emoji processing even if there are no spaces around them.
![image](https://user-images.githubusercontent.com/104189570/206656768-2781b83f-8c5e-4a74-8cae-ef5944ef5363.png)
We want the emoji code to be converted to emoji in both cases.

**Comment by CulturalProfessor** [comment]
Hey I would like to work on this issue can you assign it to me.

**Comment by xareyli** [comment]
Feature request. @dudanogueira should this be implemented?

**Comment by dudanogueira** [comment]
Hi! I believe that this need to be discussed. I tested other platforms, and None of them does it. This parser area is very tricky. I'll mark it for discussion and will ask our parser ninjas to add their cents.

@hugocostadev

**Comment by hugocostadev** [comment]
Hi guys, IMO we cannot predict if the user indeed wants to write an emoji... that's the reason that we do not accepts that! 

As @dudanogueira mentioned, any major player does that, probably because of this.

What do you guys think? Can we close it?

**Comment by Saksham294** [comment]
Hi, I think this feature may not be that useful as right now the user has the option to add emoji or just plain text emoji. 

Not only we can't predict the user behaviour but also it can be restrictive. That's why I think we should not add it.

**Comment by hugocostadev** [comment]
I agree with @Saksham294 , thanks for your contribution!

If anyone has a different opinion on this topic we can reopen this issue, meanwhile, I'll close it.

Thanks
