### ISSUE TITLE
Custom URI scheme doesn't work in messages

### ISSUE THREAD

**Issue by banderosss** [RocketChat/Rocket.Chat#27502]
### Description:

The setting Markdown_SupportSchemesForLink is ignored in the desktop app and browser. Custom links are shown as text.
But in threads custom links are shown normaly.

### Steps to reproduce:

1. Go to **Administration > Workspace > Settings > Message > Markdown**
2. Add to **Markdown Support Schemes for Link** your own scheme

### Expected behavior:

Custom shceme must be shown as link.
![image](https://user-images.githubusercontent.com/49503733/206586657-9898d3ac-b92a-4a80-9ffd-9904d79cf0a1.png)

### Actual behavior:
Custom shceme in message
![image](https://user-images.githubusercontent.com/49503733/206586788-b62d1322-b3d5-4505-bba0-0fb6dcaa7fc0.png)

Custom Scheme in thread
![image](https://user-images.githubusercontent.com/49503733/206587066-88e6298b-9118-41fe-ba2e-a0efc9071d91.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Centos 7
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 107.0.5304.108, (64 bit)/Rocket.Chat 3.8.12/3.8.13/3.8.14
- Operating System: Windows 10 Pro/Windows 7 Pro

### Additional context

The same issue was on a previos versions of server (5.3.x/5.2.x/5.1.x)

**Comment by shevchukma** [comment]
We had a similar problem. We had to change the server name to a second level domain. Our [issue](https://github.com/RocketChat/Rocket.Chat/issues/27065).

**Comment by banderosss** [comment]
Unfortunately we can't do this. It isn't a client-server technology. It is a custom URI scheme for own app. And that app is registred to be a default handler for a URI scheme name in operating system. In the Slack app that URI is handled normaly.  I'm assuming this is a problem with the new message parser, specifically the missing dot in theURI. If I paste the link into any browser, it will prompt me to launch the application that is associated with this scheme 
![image](https://user-images.githubusercontent.com/49503733/206848941-8ce48eb7-c7f0-4385-b8fc-76fa13e27600.png)

**Comment by hugocostadev** [comment]
Hi @banderosss , this is not recognized by the new message parser, you can write with this pattern that it will:

```md 
[test](consultantplus://offline/ref=AB90EA55DE2AA43E3159936815A414390D504B9B7E05B4535A455D1F863CFD3360EE34767Ah3161)
```

**Comment by banderosss** [comment]
Hi @hugocostadev, thank you for your response. It really works
