### ISSUE TITLE
Change color of read receipt

### ISSUE THREAD

**Issue by alekdimitrov** [RocketChat/Rocket.Chat#27516]
Hi. We have a problem with read receipt. Can I change color of read receipt?  For me especially in the windows client the difference between a grey and a light blue check mark is invisible. I would like to change the color of the unread and read check marks, but I do not see a way to do so in the layout menu. 
This is will be very usefull feature!

**Comment by dudanogueira** [comment]
Hi! Please, fill in the template for and provide screenshots so we can better understand this issue.
