### ISSUE TITLE
[BUG] - Save button does not stay disabled in Notification Preferences for no change

### ISSUE THREAD

**Issue by arpankodes** [RocketChat/Rocket.Chat#27512]
### Description:

https://user-images.githubusercontent.com/91999901/206894234-9f993371-64d9-47f0-9c37-4c034a168104.mp4

### Steps to reproduce:
on a refreshed page
1. On a refreshed page of the channel (or go to another channel on a refreshed page) , click on three-dots menu on right corner.
2. Click on the Notification Preferences, toggle "Mute @all and @here mentions" on and then off again.
3. Disabled "Save" button does not stay disabled. 

### Expected behavior:

"Save" button should stay disabled.

### Actual behavior:

"Save" button is enabled even toggle button is off as before (i.e even after no change)

### Server Setup Information:

- Version of Rocket.Chat Server:  5.5.0-develop
- Operating System: Ubuntu 20.04.5 LTS
- Deployment Method: yarn dsv
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: v5.0.12

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 107.0.5304.87 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.5 LTS

### Relevant logs:

LocalStore: store created at  
LocalStore: store created at  
LocalStore: store created at  
Loaded the Apps Framework and loaded a total of 0 Apps! 
LISTENING 
+-----------------------------------------------+ 
|                 SERVER RUNNING                | 
+-----------------------------------------------+ 
|                                               | 
|  Rocket.Chat Version: 5.5.0-develop           | 
|       NodeJS Version: 14.19.3 - x64           | 
|      MongoDB Version: 5.0.5                   | 
|       MongoDB Engine: wiredTiger              | 
|             Platform: linux                   | 
|         Process Port: 24187                   | 
|             Site URL: http://localhost:3000/  | 
|     ReplicaSet OpLog: Enabled                 | 
|          Commit Hash: e0de8d4eb1              | 
|        Commit Branch: develop                 | 
|                                               | 
+-----------------------------------------------+

**Comment by arpankodes** [comment]
@aleksandernsilva @dougfabris @LucianoPierdona @ggazzo @juliajforesti

**Comment by xareyli** [comment]
@arpankodes please test https://github.com/RocketChat/Rocket.Chat/pull/27513

**Comment by ManavSarkar** [comment]
Can I work on this issue?
