### ISSUE TITLE
Application Crash in all Browsers with SAML-Login

### ISSUE THREAD

**Issue by svenseeberg** [RocketChat/Rocket.Chat#27511]
### Description:

The web application in version 5.4.0 is crashing on all browsers before the login screen appears.

### Steps to reproduce:

1. Go to https://chatbegruenung.de (for example).
2. Application crashes with the following trace:
   ![image](https://user-images.githubusercontent.com/15197000/206861464-559befac-8a42-4eee-92cd-e01c9ee48334.png)

### Expected behavior:

The login button should appear.

### Actual behavior:

Application crashes.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.1
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Firefox 107.0 / Chromium 108.0.5359.94
- Operating System: All

### Additional context

None

### Relevant logs:
See screenshot above

**Comment by mikesrus** [comment]
look here for temporial solution https://github.com/RocketChat/Rocket.Chat/issues/27490

**Comment by mikesrus** [comment]
but snap package still do not have update
it shows 
`snap "rocketchat-server" has no updates available`

**Comment by svenseeberg** [comment]
> but snap package still do not have update

Yes, no release yet: https://github.com/RocketChat/Rocket.Chat/releases
