### ISSUE TITLE
Grammarly not working

### ISSUE THREAD

**Issue by VenomFate-619** [RocketChat/Rocket.Chat#27510]
No suggestions of Grammarly coming in the textbox

![image](https://user-images.githubusercontent.com/67755128/206831019-24c7fc36-64bf-4c44-b1f0-c61d8d52ce4f.png)

Execpted
![image](https://user-images.githubusercontent.com/67755128/206830999-4c93306e-4311-4278-886c-d2a5679fc753.png)

One need Grammarly because it not only spell check but also corrects your grammatical mistake

**Comment by xareyli** [comment]
Is that a feature request?

**Comment by VenomFate-619** [comment]
yup

**Comment by hugocostadev** [comment]
Please, can you elaborate more? 

In the browser I can see that Grammarly works... what is it your version, are you using browser, desktop app? 

Try to use the Issue template, please. Thanks

**Comment by VenomFate-619** [comment]
Os: PopOs
Browser: Brave
Version: 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)
