### ISSUE TITLE
How to customize login screen?

### ISSUE THREAD

**Issue by elfnya1337** [RocketChat/Rocket.Chat#27525]
In 5.4.0. version i can't change anymore on login screen (and even plain text)

![image](https://user-images.githubusercontent.com/68885244/207283464-b369942d-0fdb-4005-9516-62d2f1df98ea.png)

![image](https://user-images.githubusercontent.com/68885244/207280389-8c9b589a-c9f7-48d7-ad3a-2245409a3e0a.png)

![image](https://user-images.githubusercontent.com/68885244/207280419-a3809544-258d-4193-be2e-2816a0c8ca4b.png)

**Comment by dudanogueira** [comment]
@elfnya1337 I'll close your issue for now, as a lot of those issues will be fixed on [our next release](https://github.com/RocketChat/Rocket.Chat/milestone/317)

Please, when opening an issue, try to follow the template, it really help us to have a clear understanding about the error.

You can find a [great content here about how to better use our Community Resources.](https://docs.rocket.chat/getting-support/community-resources)

Thanks!
