### ISSUE TITLE
[BUG]: No redirect after leaving a channel

### ISSUE THREAD

**Issue by xareyli** [RocketChat/Rocket.Chat#27528]
### Description:

After leaving a channel a user is not redirected.
![forGH](https://user-images.githubusercontent.com/118266546/207326088-9cf49553-8f5e-434d-b6dc-54d880a2a59e.gif)

I am not sure whether this is a bug or not, but looks weird

### Steps to reproduce:

1. Join a channel
2. Leave it
3. You stay in that channel

### Expected behavior:

The user is expected to be redirected to the nearest channel

### Actual behavior:

The user stays in the channel they leaved

### Server Setup Information:

- Version of Rocket.Chat Server: 5.5.0-develop 
- Operating System: Arch Linux
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.5

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Arch Linux

### Additional context

This may be intended behavior, but rather looks like a bug

**Comment by Saksham294** [comment]
If this is a bug I would like to try and fix it

**Comment by thepranays** [comment]
If this behavior has to be implemented ,i would like to work on it.Please guide me

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
