### ISSUE TITLE
How to monitor ipv6

### ISSUE THREAD

**Issue by wangyijin209** [RocketChat/Rocket.Chat#27537]
![image](https://user-images.githubusercontent.com/85976497/207589391-7d7805f7-5e0d-4cf8-b864-f7c89e36bbb2.png)
My vps only have ipv6, but rocket Chat listens to ipv4 by default. After I use nginx proxy manger reverse proxy, the following occurs
![image](https://user-images.githubusercontent.com/85976497/207589675-c07128cf-78df-4e83-8bf9-e42710c6db25.png)
I want to know how to let Rocket.chat listen to ipv6

**Comment by dudanogueira** [comment]
Hi! Thanks for using Rocket.Chat!

This is not the right place to ask deployment questions. Please, check out this doc on how to better use our [Community Resources](https://docs.rocket.chat/getting-support/community-resources)

There is already this question in our Forums:
https://forums.rocket.chat/t/getting-rocketchat-to-listen-to-ipv6-as-well-as-ipv4/12881/4
