### ISSUE TITLE
Oauth button not showing on homepage after upgrade to 5.4.0

### ISSUE THREAD

**Issue by adaneps** [RocketChat/Rocket.Chat#27542]
### Description:

When deactivating the "Show Default Login Form" option, the button for Oauth does not appear on the Home page

### Steps to reproduce:

1. General - Account 
2. Disable how Default Login Form
3. Open an incognito tab and access rocket chat, the Oauth button does not appear.

### Expected behavior:

Display button or shape for Oauth authentication

### Actual behavior:

Anything

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System:  Linux 
- Deployment Method: Docker rocketchat/rocket.chat:5.4.0
- Number of Running Instances: 1
- DB Replicaset Oplog: local 
- NodeJS Version: 
- MongoDB Version: 4.4

### Client Setup Information

- Browser Version: Chrome 108.0.5359.99 / Firefox 108.0
- Operating System: Windows 11

### Additional context

Oauth Customized : Keycloak

### Relevant logs:

Server without error logs
Browser Console:

```
Uncaught (in promise) undefined
https://</url>/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1458
```

**Comment by dudanogueira** [comment]
Thanks for pointing out!

This was fixed in https://github.com/RocketChat/Rocket.Chat/pull/27475
