### ISSUE TITLE
Read receipt is not enough readable on desktop client

### ISSUE THREAD

**Issue by alekdimitrov** [RocketChat/Rocket.Chat#27550]
### Description:
Hi. We have a problem with read receipt. Can I change color of read receipt? For me especially in the windows client the difference between a grey and a light blue check mark is invisible. I would like to change the color of the unread and read check marks, but I do not see a way to do so in the layout menu.
This is will be very usefull feature!

### Steps to reproduce:

1. Write some message on desktop client (v.3.8.14)
2. Read recept are alomost with the same color (difference between a grey and a light blue check mark is invisible in FullHD resolution - 1,920 x 1,080 pixels)
3. I cant understand if other people are read my message or not

### Expected behavior:
I would like to change the color of the unread and read check marks. So change color of readed marks or make RR bigger may be will be decision of the problem

### Actual behavior:

I cannot change color of the unread and read check marks (see atached file if resolution are normal is very very  dificult to see wich readreciept are blu or grey)

![readreciept](https://user-images.githubusercontent.com/69185353/207848986-120c448f-d679-49dc-a24d-c67e4016e5fc.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App and Browser Version:
- Operating System: Windows 10

**Comment by dudanogueira** [comment]
Hi! Our designers are now aware of this issue!

Thanks for pointing it out!

**Comment by kr-2003** [comment]
Hi! I am actually a newbie to open source. But I want to work on this issue. Please guide me.

**Comment by thepranays** [comment]
Hey i am new to oss,Can i work on this issue ? I can see two approaches 
1.Change the colors suitable enough to be seen on every device
2.Add customization feature for theming the colors
Please guide me

**Comment by dudanogueira** [comment]
Hi! Our designers are working on this already, thanks!

if you are looking for issues to help, please, check the "good first issue" tag or join our [Community Open Call](https://open.rocket.chat/channel/Rocket-Chat-Open-Community)

Thanks!!

**Comment by matheusbsilva137** [comment]
The read-receipt size has been increased in #27665
