### ISSUE TITLE
Click markdown example toggle help dialog

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2755]
Your Rocket.Chat version: 0.27

It would be nice to have the ability to format the text not only by markdown codes typed on keyboard, but by selecting a fragment and mouse click on the help line (or by the hotkey like ctrl-b) too.

![image](https://cloud.githubusercontent.com/assets/16319433/14254253/94cab558-fa97-11e5-9652-f9a9601fc9fc.png)

**Comment by bott0r** [comment]
In general it would be outstanding to figure out how all the inline commands work. I could not figure out how kalatex works, tho i have a lot of experience with latex in general. 
> $$\alpha$$
> $ \lambda $
> <katex> test </katex>

nothing seems to work haha :dancers:

**Comment by zxweed** [comment]
@bott0r, you should inline the expression with \( and \) and enable the KaTeX plugin

**Comment by bott0r** [comment]
@zxweed thanks! 
Tho, to mention the spaces are very important, \(test)\ does not work while \( test )\ does

**Comment by andreas-bulling** [comment]
If KaTeX (or other plugins) is enabled it should add an entry to the markdown help line

**Comment by krisleech** [comment]
Example for future Googlers:

`\(\sigma\)`

**Comment by MartinSchoeler** [comment]
Done in #7643
