### ISSUE TITLE
Bold font in the description

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27567]
### Description:

In the description of the file, words marked with ** are displayed not in bold but in italics.

### Steps to reproduce:

Mark the word in bold in the description of the file.

### Expected behavior:

Bold markup in the description is rendered in bold.

### Actual behavior:

Bold markup in the description is shown in italics.
![image](https://user-images.githubusercontent.com/104189570/208116668-7a915b16-1088-4944-af01-3c537fa5d297.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.5
- Operating System:  Oracle Linux 8.5
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 107.0.5304.88 
- Operating System: Windows 10

### Additional context

On open.rocket.chat it is also reproduced.
Strikethrough and italics display correctly.

**Comment by hugocostadev** [comment]
Hi there! Thanks for your contribution... There is one PR that will be merged very soon that will switch the parser for attachments description to use the new message-parser that will fix this behavior, I'm referencing it to this issue be closed after merge! Thanks

PR: https://github.com/RocketChat/Rocket.Chat/pull/27317
