### ISSUE TITLE
Links in Channel Topics should open as new tab

### ISSUE THREAD

**Issue by rroepke** [RocketChat/Rocket.Chat#27563]
When sending a link as a message, the respective link opens in a new tab when clicked on by any user. Unfortunately, when embedding a link in a channel topic, the link opens in the same tab as the RocketChat app.

Since it is not allowed to embed pure HTML in topics, I would prefer to have the same behavior for links here, similar to links in chat messages.

Overall, I think an overall setting on "Open links" could be useful with options like "in same tab", "in new tab", "in new window"l, basically controlling the target-attribute of a-tag.

**Comment by hugocostadev** [comment]
Hi @rroepke this is a known issue and already has an open PR, thanks! 

Pull Request: https://github.com/RocketChat/Rocket.Chat/pull/27554
