### ISSUE TITLE
Client issues

### ISSUE THREAD

**Issue by sohovfx** [RocketChat/Rocket.Chat#2757]
Your Rocket.Chat version: 1.2

Hi all,

Thanks for such a great project, we really appreciate all your effort!

One of our users running on OpenSuSE 13.2 raised an issue.

- When messages are raised and he's away from his desk, the notifier shows him the messages and offers a 'view' button.  Clicking this button does nothing.

- When viewing unread messages, they don't disappear from the notifier as they are seen.  The only way to mark a message read, is to reply to it .. that's odd.

Corollary but still important to him was the lack of options for the notifier.  He would prefer a persistent bouncing or non-hiding alert until he's clicked on it.

We've yet to play with this on the Debian side, but on OSX clicking the notification also does not bring the application to the foreground and the dock icon does not bounce on notifications.

**Comment by engelgabriel** [comment]
What is the version of the server?

**Comment by sohovfx** [comment]
Hi Gabriel, 

Version is 0.22.0 

Thanks, 

Todd Smith 
Head of Information Technology 

soho vfx | 
99 Atlantic Ave. Suite 303, Toronto, Ontario M6K 3J8 
office: (416) 516-7863 fax: (416) 516-9682 web: sohovfx.com 

----- Original Message -----

**Comment by engelgabriel** [comment]
Please upgrade to the latest release, as this problem has been fixed.

**Comment by engelgabriel** [comment]
Can you please test it again with the version release today?
