### ISSUE TITLE
Can't install via snap on a CPU without `AVX/AVX2` support

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat#27581]
### Description:

Rocket.chat installed via snap doesn't start on a CPU without `AVX/AVX2` support.

### Steps to reproduce:

1. Try to install Rocket.chat via snap on a CPU without `AVX/AVX2` support

### Expected behavior:

Rocketchat.chat should start without issues

### Actual behavior:

Rocket.chat doesn't start and throws a `core dumped`

### Server Setup Information:

- Version of Rocket.Chat Server: 5.x/stable track
- Operating System: Ubuntu 22.04
- Deployment Method: snap 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Apparently my CPU (Intel(R) Atom(TM) CPU N2800) doesn't have `AVX/AVX2` support which seems to be needed.
Channel `3.x/stable` (and I assume lower) seems to work without any issues.

### Relevant logs:

Output of **journalctl -fu snap.rocketchat-server.rocketchat-server.service**:
```
Dec 19 23:05:17 X3 systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Dec 19 23:05:19 X3 rocketchat-server.rocketchat-server[1610392]: node $SNAP/main.js
Dec 19 23:06:13 X3 rocketchat-server.rocketchat-server[1610452]: strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
Dec 19 23:06:19 X3 rocketchat-server.rocketchat-server[1610392]: /snap/rocketchat-server/1536/helpers/rocketchat.sh: line 23: 1610452 Illegal instruction     (core dumped) node $SNAP/main.js
Dec 19 23:06:22 X3 rocketchat-server.rocketchat-server[1610550]: pkill: pidfile not valid
Dec 19 23:06:22 X3 rocketchat-server.rocketchat-server[1610550]: Try `pkill --help' for more information.
Dec 19 23:06:22 X3 systemd[1]: snap.rocketchat-server.rocketchat-server.service: Control process exited, code=exited, status=1/FAILURE
Dec 19 23:06:22 X3 systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
Dec 19 23:06:22 X3 systemd[1]: snap.rocketchat-server.rocketchat-server.service: Consumed 1min 8.415s CPU time.
```

**Comment by dudanogueira** [comment]
Hi! This is probably a mongo 5.0 limitation:
https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610

Please, try deploying with docker and mongo 4.5:
https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose

Also, please, check this documentation before opening an issue:
https://docs.rocket.chat/getting-support/community-resources

Thanks!

**Comment by PeGaSuS-Coder** [comment]
> Hi! This is probably a mongo 5.0 limitation:
https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610
