### ISSUE TITLE
Admin/Mod Flair

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2758]
Your Rocket.Chat version: 0.24
I was wondering if there is a way to add something similar to user flair on reddit to denote Admin/mods in chat. Even better would be to add custom titles but the Admin/mod flair could actually serve a purpose.

**Comment by engelgabriel** [comment]
We already have the moderator role in the room, so what are you requesting in more details?

**Comment by royalaid** [comment]
Just a little label next to the name of the user 
<img width="174" alt="screen shot 2016-04-04 at 3 33 07 pm" src="https://cloud.githubusercontent.com/assets/2439803/14266089/9e62c1d6-fa7a-11e5-83cd-ef04189a62e8.png">
In this case the flair is `Nexus 6, Chroma` but having labels like `admin` and `mod` would be useful especially on larger servers.

**Comment by lunitic** [comment]
Aint it same as https://github.com/RocketChat/Rocket.Chat/issues/2378 #2378

**Comment by royalaid** [comment]
Oh yeah it kinda is, only difference being that with this you offer an option to customize your flair.

**Comment by engelgabriel** [comment]
Let's keep the discussion on the #2378

**Comment by tepease** [comment]
@engelgabriel any chance of re-opening this since the fix on #2378 used a discrete set of roles? It would be great to have room specific custom flair that could be set, e.g. 
tepease **Owner** *mystic*
in a Pokemon Go room.

**Comment by tepease** [comment]
As per the reddit convention mentioned above, only room admins can set users' flair, but in slack anyone can set their own. I think a combination is best, in which mods can set room specific flair from the user flyout menu and users can modify their own.
