### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by GrigoriosPetsos** [RocketChat/Rocket.Chat#27625]
Hi There, VPN (Cyberghost) and Rocket chat do not run simultanously. Can you help?

**Comment by dudanogueira** [comment]
Please, check this doc on how to better get support using our [Community Resources](https://docs.rocket.chat/getting-support/community-resources).

I'll close this issue as there is not even the template answered.

Thanks!

**Comment by GrigoriosPetsos** [comment]
This will not help to make my decision towards a prolonging the testphase. Why did you not just simply give me the answer? This would not have lasted longer than just pointing me to somewhere else ...
