### ISSUE TITLE
Regression:  web-rtc - support remote video monitoring (again)

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2762]
I believe this feature has been replaced, and then refactoring removed it altogether.

We need to have an ability for a callee to auto-answer for remote video monitoring (after a delay, and so on).   It used to work, even AFTER the inband driver has been eliminated.

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.
