### ISSUE TITLE
Integrations section is not responsive.

### ISSUE THREAD

**Issue by adijr9487** [RocketChat/Rocket.Chat#27634]
### Description 
In Integrations section, the page is not responsive for the screen size of width less than 650px.

### Steps to reproduce
1. Navigate to _Integrations_ inside _fully featured_
2. Press _New_ to create an integration.

## Preview
![image](https://user-images.githubusercontent.com/56039219/209439588-3d379aad-72ba-427a-b9ce-b972f0e0bc8b.png)

### Server Setup Information:

Version : 5.5.0-develop
Deployment ID : e59SBD8ijDSbKw2o3
Apps Engine Version : 1.36.0
Node Version : v14.19.3
Database Migration : 281 (December 24, 2022 11:35 AM)
MongoDB : 5.0.5 / wiredTiger (oplog Enabled)

**Comment by AliTechGeek52** [comment]
Can I solve this issue ?

**Comment by adijr9487** [comment]
I have already solved it on one of my branch. Just waiting for someone to approve.

**Comment by dudanogueira** [comment]
Thanks  and @AliTechGeek52 for the interest :)

@adijr9487 Please, go ahead and submit the PR mentioning this issue so we can review it :)

Thanks!

**Comment by deep-69bits** [comment]
@adijr9487   hello, can I get your mail or any contact ??

**Comment by adijr9487** [comment]
It's adijr9487@gmail.com
> @adijr9487 hello, can I get your mail or any contact ??
