### ISSUE TITLE
File links not clickable because they contain more than 2 slashes file:/// in kde env

### ISSUE THREAD

**Issue by rareshornet** [RocketChat/Rocket.Chat#2764]
Your Rocket.Chat version: 0.25

We are using Fedora 19 ith kde4 in our production environment and the killer feature for rocket chat for us is that it doesn't recognize the file:/// links. It does recognize file links with 2 slashes file:// but they don't work in kde. Is there a chance you guys can add an exception for 3 slashes like file:///bla/bla/vbla so we can add rocket chat to our prod env? It would a massive help for us as currently we are struggling with pidgin and some crappy xmpp server and rocket chat is such a great piece of work.

Cheers!

**Comment by mylesw-luma** [comment]
+1 for this

**Comment by sambvfx** [comment]
Any update on this?
