### ISSUE TITLE
Hovering over reaction on thread doesn't show who reacted

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat#27649]
### Description:

While hovering over the a message reaction on a room shows who reacted, that doesn't happen when we hover over reactions inside a thread

### Steps to reproduce:

1.  Go to a reaction inside a thread and hover the mouse over it
2.  There's no toast showing who reacted

### Expected behavior:

The usernames of those that reacted to the message should be shown

### Actual behavior:

Already described above on **Description**
Screen record below:

https://user-images.githubusercontent.com/25697531/209663291-7db335e8-349d-4e8a-9929-11b24b819e35.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: Official Rocket.chat Server
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Google Chrome `Version 108.0.5359.124 (Official Build) (64-bit)`
- Operating System: Ubuntu 22.04

**Comment by dudanogueira** [comment]
Thanks for pointing it out. Our team is aware :)

**Comment by ggazzo** [comment]
this problem is related to a migration we are performing, as soon as we finish everything will be back to normal, don't worry this is in develop only, this is never going to production
