### ISSUE TITLE
Quoting message with a quoted message prepends internal link of the message we are quoting

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat#27648]
### Description:

When quoting a message that has another message quoted, the internal link to the message is prepended to the message that we are quoting (at least on threads).
### Steps to reproduce:

1.  Quote a message on a thread that has another message quoted
2.  Internal link will be prepended to the message we are quoting

### Expected behavior:

No internal prepended to the 

### Actual behavior:

Screenshot below:
![thread_prepend_link](https://user-images.githubusercontent.com/25697531/209660335-efaa98d2-174b-4cdf-94d1-ac0cadef67c9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: Official Rocket.chat Server
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Google Chrome `Version 108.0.5359.124 (Official Build) (64-bit)`
- Operating System: Ubuntu 22.04

**Comment by ankar84** [comment]
Confirm that. Don't look like proper behavior.

**Comment by adarsh500** [comment]
Hey, can i work on this issue?

**Comment by kanhaiya04** [comment]
Hi @dudanogueira, I just faced the same issue and trying to fix it. Can you guide me on how to get started?
I am new and want to Contribute.

**Comment by Player256** [comment]
In the website it works fine but in the local dev env i observed the issue stated above.Weirdly the context menu jiggles in the website but does not show any problem in the local dev.
