### ISSUE TITLE
Users experience Grey Screen after log in.

### ISSUE THREAD

**Issue by Gabe88def** [RocketChat/Rocket.Chat#27666]
DESCRIPTION:
User reached out that they are unable to see the home page after logging into their profile. One user was able to see their home page and after changing the display from "Medium" to "Extended" they saw the same issue as the first user. (Grey Screen home page). 

SERVER RUNNING:
|       Rocket.Chat Version: 5.4.1                       | 
|       NodeJS Version: 14.21.1 - x64               | 
|      MongoDB Version: 4.4.18                      | 
|       MongoDB Engine: wiredTiger 

EXPECTED BEHAVIOUR:
![image](https://user-images.githubusercontent.com/119975343/209982851-c6765f15-c6a6-4e71-8478-d7fbc2cea47f.png)

ACTUAL BEHAVIOUR:
![image](https://user-images.githubusercontent.com/119975343/209982945-ba8fda02-6051-4d04-8361-d3e43665f1f0.png)

VIDEO CLIP:
https://user-images.githubusercontent.com/119975343/209982869-2a84b9e9-d4e0-4e37-ba93-fa75e7f47e3c.mp4

TESTING PROCEDURES:
Created Testing Rocket Chat account.
Duplicated dispaly settings.
No Issue. 
User that was having issues with their account used test account and had no issues.
Cloned RC and replicated issue. Once i changed display setting the Issue happened. 
Console Logs:
![image](https://user-images.githubusercontent.com/119975343/209988589-438719a5-8641-497a-a47d-e57188b62207.png)

HYPOTHESIS:
User account specific is having issues with rocketchat or some features break as soon it is enabled. 
Console logs uploaded for review 
[45.33.24.203-1672335007326.log](https://github.com/RocketChat/Rocket.Chat/files/10320755/45.33.24.203-1672335007326.log)

**Comment by deep-69bits** [comment]
can i work on this or can we both??

**Comment by Gabe88def** [comment]
> can i work on this or can we both??

We can work on it if you'd like

**Comment by deep-69bits** [comment]
@Gabe88def  ok i want to add some more features we can add it later

**Comment by Gabe88def** [comment]
sure. let me know when you're available

**Comment by dudanogueira** [comment]
Hi @Gabe88def this is probably a deployment issue.

Please, consider reading thru our https://docs.rocket.chat/getting-support/community-resources material before opening an issue and how to better ask for help.

Also, consider joining https://open.rocket.chat/channel/support for community support.
