### ISSUE TITLE
Error with gitlab authentication

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#2766]
Hi, im using the latest docker rocketchat container, up to yesterday it is working fine with gitlab oauth authentication. but after today updated to develop tag of docker container it is not working

here are some logs
```
[methods] getUsernameSuggestion -> userId: null , arguments:  {}
at: afdf16a1e8fd0aeae933d64db02eabecbefa352a2544c9e12ac09a18f728466f
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to fetch identity from gitlab at https://git.invizotechnologies.com/api/v3/user. failed [400] {\"error\":\"invalid_request\",\"error_description\":\"Both Authorization header and payload includes access token.\"}","time":{"$date":1459839875005},"level":"warn"}
Exception while invoking method 'login' Error: Failed to fetch identity from gitlab at https://git.invizotechnologies.com/api/v3/user. failed [400] {"error":"invalid_request","error_description":"Both Authorization header and payload includes access token."}
    at CustomOAuth.getIdentity (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:92:16)
    at Object.handleOauthRequest (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:101:20)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
    at middleware (packages/oauth/oauth_server.js:173:1)
    at packages/oauth/oauth_server.js:146:1
```

**Comment by engelgabriel** [comment]
Error introduced by https://github.com/RocketChat/Rocket.Chat/pull/2752/files

Maybe this should a config of the oAuth?

**Comment by honnel** [comment]
Same problem here...

**Comment by pavankumarkatakam** [comment]
Yeah, may there shoud be an option to choose the Headers or query to keep token.

**Comment by pavankumarkatakam** [comment]
Hey its my fault to mention this before, im actually using gitlab built in one not an custom one.

**Comment by pavankumarkatakam** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/6078669/14402134/31c44708-fe48-11e5-9c50-6dcb3b805983.png)

**Comment by engelgabriel** [comment]
It is working on the develop branch, and will be release tomorrow on version 0.26.0

**Comment by pavankumarkatakam** [comment]
ok

**Comment by sebastientaggart** [comment]
@pavankumarkatakam did you ever get this solved?  If so, what did you end up doing?

**Comment by pavankumarkatakam** [comment]
At that time I just downgrade the version, but im now using the latest version and its working fine.

**Comment by sebastientaggart** [comment]
@pavankumarkatakam thanks for the reply!  I'm on latest Gitlab and latest RocketChat as well.  I must be screwing up the settings.  Are your settings the same as your screenshot above?
