### ISSUE TITLE
getting guest email in omnichannel chat

### ISSUE THREAD

**Issue by gstlouisgit** [RocketChat/Rocket.Chat#27674]
I have started to explore the chat integration in to a website.  IT is pretty good and seems to be working well!

However, if I test this as a guest, it asked me to enter my name for guest and email.  But when I receive the chat in RC I cannot see the guest email address?  Am I not seeing this or is it made to be like this?

Thank you

**Comment by MartinSchoeler** [comment]
![Screen Shot 2023-01-02 at 2 38 49 PM](https://user-images.githubusercontent.com/20868078/210264100-036eb42f-e118-47dc-bbea-bf81122788df.png)
You can usually find this information on the `Contact Information` tab on the right sidebar

I will be closing this for now, if you still can't find the information needed on the contact info tab, feel free to open a new issue with more details about your installation (like what version and os are you using) cause that might be a bug

Thanks!
