### ISSUE TITLE
Snap and Docker packages get not updated 04/23

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat#27677]
Currently (for months) RC updates are not properly published to the snap store (and Dockerhub) so you can't update to a more recent version.

It looks like just major versions get pushed but never (or huge delays) any bugfix versions or security updates. 

The whole process seems to be semi broken for years. 
The **security update** for 4.8.x branch was released 4 months after announcement at snap so likewise this is a manual process ?

I already made a ticket at the snap issue tracker but it looks like its not maintained.
https://github.com/RocketChat/rocketchat-server-snap/issues/49

**Comment by CvH** [comment]
looks like it works again, no idea if manually triggered or really working this time :)

**Comment by CvH** [comment]
and ofc it is not working again
snapstore was not updated, doin't got 6.0.1 or 6.1.0

**Comment by henrywithu** [comment]
It'll be appreciated if devs can update ARM64 in Snap.
The current official latest version is still 4.x there.
Thanks

**Comment by CvH** [comment]
seems to work now for several months :)
