### ISSUE TITLE
Rocket.Chat5.4.1 error

### ISSUE THREAD

**Issue by TwoDogs2** [RocketChat/Rocket.Chat#27675]
I encountered such a problem when installing the new version
![image](https://user-images.githubusercontent.com/121689365/210174724-1063177f-b8a3-4a34-81b5-357934ba2bdd.png)
system Centos7
NodeJS v12.22.12
mongod version v4.0.28

**Comment by dudanogueira** [comment]
hi! Please, consider reading this doc before opening an issue:
https://docs.rocket.chat/getting-support/community-resources

AFAIK, Centos7 indeed has some problems with newer versions of RC. If you can upgrade to a newer Linux flavor and use docker or k8s, you can avoid this.
