### ISSUE TITLE
amazon s3 upload

### ISSUE THREAD

**Issue by assafm81** [RocketChat/Rocket.Chat#2768]
Your Rocket.Chat version:0.24.0

hey,

i configure my amazon s3 bucket but i cann't upload any file in the channels.  i checked my permissions with bucket explorer and from there i can upload and delete files. 
in the logs i can see "

[methods] slingshot/uploadRequest -> userId: edfer , arguments:  { '0': 'r
  '1': { name: 'comment.txt', size: 102, type: 'text/plain' },
  '2': { rid: 'a26r8fizEeb57LGKP' } }
"
and when i am trying to upload a file i getting " -0 " and red line ..

Please help :)

**Comment by assafm81** [comment]
i solved that F**k issue :) 
i was needed to configure the default CORS policy of the bucket. 
the correct policy should be:

> 

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

>

**Comment by assafm81** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>

**Comment by Lochemage** [comment]
@assafm81 

Thank you for this, I had the same problem and this fixed it.

**Comment by graywolf336** [comment]
We need to add that to the documentation then.

**Comment by sampaiodiego** [comment]
yes.. sorry about that.. this is already in slingshot's docs..
my fault not writing it somewhere. =\
