### ISSUE TITLE
Please mark channel as READ when I've scrolled to the bottom (Windows app)

### ISSUE THREAD

**Issue by cryptomius** [RocketChat/Rocket.Chat#27684]
Please mark channel as READ when I've scrolled to the bottom (Windows app)

At present, I need to manually flag channels as 'Read' as Rocket Chat doesn't seem to realise I'm at the most recent post. 

Either this or make the 'Mark as Read' a single click button rather than having to hunt for it.

For each channel + each new post this adds up to a lot of inconvenience.

**Comment by cryptomius** [comment]
I should clarify - it looks like there is a button to mark the channel as read (at top of messages list) however it seems I have to scroll up then scroll back down before the channel will switch to being read.

**Comment by 0xEvolex** [comment]
Same problem here.

As of now it seems to happen more frequently with messages of bot users or in channels that contain multiple unread messages (more than viewable on a single screen, adjusting resolution can influence this issue)

Pressing ESC manually resets the unread messages counter.

**Comment by didacroyo** [comment]
Crated as a new issue (using the template) here: https://github.com/RocketChat/Rocket.Chat/issues/27776

**Comment by hugocostadev** [comment]
closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/27776
