### ISSUE TITLE
Regression: message cog does not show on Android Cordova client

### ISSUE THREAD

**Issue by brakhane** [RocketChat/Rocket.Chat#2771]
Your Rocket.Chat version: 0.25

With 0.25 (maybe sooner, it worked with 0.21) the message cog where you star/pin/delete messages does not shown anymore on the mobile Cordova client, it still works on desktop .

**Comment by engelgabriel** [comment]
This is a new feature, unfortunately we are waiting for apple to release the new version of the app that will open a native menu when you press and hold the message.

**Comment by AJ-Acevedo** [comment]
I just received an in app iOS notice that a new version of the app is available.

**Comment by engelgabriel** [comment]
The IN-APP does not count. This is a major update, need to be form the app store when a couple of days.

**Comment by brakhane** [comment]
@engelgabriel you just mentioned the iOS app, am I right in assuming a new android version will be released with the iOS one?

**Comment by engelgabriel** [comment]
Yes :)

-- 
Sent from Mobile
