### ISSUE TITLE
Can't open full user's profile in multi-user chat

### ISSUE THREAD

**Issue by WinterSilence** [RocketChat/Rocket.Chat#27711]
Link/button "View full profile" doesn't work.
Desktop version: 3.8.11
![изображение](https://user-images.githubusercontent.com/3521094/211510637-f1b5f3b9-5531-4f62-bd1a-3a9ec28349ba.png)

**Comment by dudanogueira** [comment]
Please, fill int the issue template.

THanks!

**Comment by WinterSilence** [comment]
@dudanogueira then fix it in application, i'm just press "send bug report"
