### ISSUE TITLE
Links in channel desciption, accouncements are not set target="_blank"

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat#27719]
### Description:

When i have a weblink in a channel description which is shown above the chat, or the channel announcment, links are opened inside the electron app instead of opening the browser.

https://github.com/RocketChat/Rocket.Chat.Electron/issues/2581

### Steps to reproduce:

1. Set a link in description or announcement.
2. Click the Link

### Expected behavior:

Links open in a new window/tab. Especially in electron: links should open in webbrowser.

### Actual behavior:

Links just opened in the same window / inside the RC electron app.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: Debian
- Deployment Method: probably aptitute
- Number of Running Instances: 1 
- DB Replicaset Oplog: dunno 
- NodeJS Version: dunno
- MongoDB Version: dunno

### Client Setup Information

- Desktop App or Browser Version: Firefox, Chromium, RC Electron App
- Operating System: Linux (Fedora, Debian), Windows11

**Comment by dmitriy-olhovsky** [comment]
Confirm, the same problem occurred in the latest version of Rocket Chat (5.4.1).

**Comment by kanhaiya04** [comment]
Hi, Is this issue still exist??
When I checked in Rocket Chat(6.0.0 - develop) I didn't get this issue, it's working fine.
If it's open I would like to work.

**Comment by dmitriy-olhovsky** [comment]
@kanhaiya04 Yes, it still exists in version 5.4.1. I think you checked it in the new version (6.0) and maybe the bug doesn't show up there.

**Comment by hugocostadev** [comment]
This was fixed in this PR and it'll be released in the upcoming weeks.

PR: https://github.com/RocketChat/Rocket.Chat/pull/27554

**Comment by Wiljes** [comment]
The problem still exists in Ver 5.4.3

**Comment by b90g** [comment]
> The problem still exists in Ver 5.4.3

seems to work in 6.0
