### ISSUE TITLE
Show small previews/icons for pictures in the files list tab

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2773]
Your Rocket.Chat version: 0.24

It would be useful for fast visual picture search

<img width="362" alt="2016-04-05 14 22 25" src="https://cloud.githubusercontent.com/assets/16319433/14280203/f97d6d68-fb39-11e5-99de-0aca0c0b1ad1.png">

**Comment by IQ2022** [comment]
:+1: Agree, we need to have more features added to the attachment/File section

**Comment by PeaceS** [comment]
would be super!

**Comment by Hudell** [comment]
I'm gonna close this because this feature was included at some point after the issue was opened.
