### ISSUE TITLE
link with parentheses is not working

### ISSUE THREAD

**Issue by woottipong-gl** [RocketChat/Rocket.Chat#27733]
When I put parentheses () in link, it not include on the link

**Comment by dudanogueira** [comment]
hi! Thanks for pointing out :) But please, fill in the issue template, it really help us :)

Reproduced on latest version as of now https://github.com/RocketChat/Rocket.Chat/commit/cdc2f99f8
and 5.4.1

example for reproduction:
`[teste1](http://rocket.chat?text=(some_argument))`

**Comment by ksba2004** [comment]
I would like to work on this issue, please assign this to me.
Also, please give some resources so that I can take reference.

**Comment by hugocostadev** [comment]
duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/13149
