### ISSUE TITLE
No role assign to manual registered users despite of Default Roles for Users settings

### ISSUE THREAD

**Issue by tidusete** [RocketChat/Rocket.Chat#27736]
### Description:

I have defined the `guest role` on **Admin UI - Account - Registration - Default Roles for Users**
![image](https://user-images.githubusercontent.com/17460698/212082453-202fd6e1-1861-4d7c-b408-9f38029078f6.png)
But when I'm creating a user though the portal doing it manual filling the form, it sends the following json to the api.
```
{"roles":[],"name":"testuser","username":"testuser","statusText":"","bio":"","nickname":"","email":"<ommited>","password":"<ommited>","verified":false,"requirePasswordChange":false,"setRandomPassword":false,"sendWelcomeEmail":true,"joinDefaultChannels":true}
```
I know that I left empty the list_box where you can choose on which roles you want to add the user but that's because I want to use the default one defined on **Admin UI - Account - Registration - Default Roles for Users**
![image](https://user-images.githubusercontent.com/17460698/212084633-a8525735-39a6-4331-a15e-e8bd33b16a76.png)

### Steps to reproduce:

1. Define your default roles on **Admin UI - Account - Registration - Default Roles for Users**
2. Create a manual user through https://_yourdomain_/admin/users/new
3. Check the role of the user created

### Expected behavior:

I would like to have on my user the default role

### Actual behavior:

It creates the user but doesn't have been assigned to any role.
![image](https://user-images.githubusercontent.com/17460698/212084633-a8525735-39a6-4331-a15e-e8bd33b16a76.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.2.0
- Operating System: Ubuntu 20.04
- Deployment Method: docker-compose
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.13

### Client Setup Information

- Desktop App or Browser Version: Firefox 108.0.2
- Operating System: Ubuntu 22.04

**Comment by bhardwajdisha** [comment]
hi @tidusete & @dudanogueira, I would like to work on this issue, can you please assign this to me
