### ISSUE TITLE
When changing an account, direct chat rises in the list

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27738]
### Description:

We have a process when we disable a user account, we rename his login and email.
We do this through a REST API request like this:
`"https://$server/api/v1/users.update" -d '{"userId": "'$userId'", "data": { "username": "'$toName'", "email" : "'$toEmail'"}}'`
After that, for other users, the chat with this user is placed at the very top of the list. In the database, the **_updatedAt** field is updated in the **rocketchat_room** collection.
If you rename the user manually, through the administrator interface, this does not happen - the chat with the user does not change the position in the list.

### Steps to reproduce:

1. Select a user, for example UserA, who is at the bottom of the chat list for user UserB
2. Rename UserA to UserA_old via /api/v1/users.update request
3. For UserB, the contact UserA_old will be at the top of the list.

### Expected behavior:

The position of a contact does not change if it is renamed via api/v1/users.update.

### Actual behavior:

The contact rises to the top of the list for other users if it is renamed via api/v1/users.update.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: CentOS Linux release 7.9.2009
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.12

### Client Setup Information

- Desktop App or Browser Version: Chrome 108.0.5359.95
- Operating System: Windows 10

### Additional context

We also have a similar issue where a large number of private chats up at the top of the list. I think this is due to the regular pruning old messages. But I'm not exactly sure, and have not yet identified a pattern.

**Comment by iMiKED** [comment]
I can confirm this wrong CL behaviour.

**Comment by Alzamer** [comment]
I'd like to work on this. Can someone assign me?

**Comment by shevchukma** [comment]
I see that this issue has been fixed after PR [27912](https://github.com/RocketChat/Rocket.Chat/pull/27912).
