### ISSUE TITLE
Chat window not visible

### ISSUE THREAD

**Issue by OmidH** [RocketChat/Rocket.Chat#27749]
### Description:

After updating through the Mac App Store to version 3.8.17 (103) the app window is not visible anymore. Also all menu item regarding the window are deactivated.

Further infos:
- My Machine has a M2 Chip.

While starting the app from a terminal the following out put is shown:

`objc[11559]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x22246b2e0) and /Applications/Rocket.Chat.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x11db5e978). One of the two will be used. Which one is undefined.`

### Steps to reproduce:

1. Update your App to the newest version (3.8.17 (103)) in App Store

### Expected behavior:

See the chat window

### Actual behavior:

Nothing to see, no obvious errors.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App: 3.8.17 (103)
- Operating System: Ventura 13.0.1 (22A400)

### Relevant logs:

`objc[11559]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x22246b2e0) and /Applications/Rocket.Chat.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x11db5e978). One of the two will be used. Which one is undefined.`

**Comment by dudanogueira** [comment]
Hi!

This might be duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2583

If that's the case, please, can you close this issue and keep track on that issue?

Thanks!

**Comment by OmidH** [comment]
Thanks @dudanogueira indeed a duplicate.
