### ISSUE TITLE
Support for Piwik and/or Google Analytics

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#2774]
It would be good to have support for analytics; configurable via the administration UI — particularly [Piwik](http://piwik.org/), as alternative to Google Analytics.

**Comment by k0nsl** [comment]
My bad, I now see there is a similar issue about this:

#233

**Comment by engelgabriel** [comment]
You can already configure your Google Analytics by defining the Google Tag Manager ID in the Admin Panel, in the General tab. :)

**Comment by Hostile** [comment]
what is google tag manager ID? for analystic?
