### ISSUE TITLE
Missing CSRF middleware 

### ISSUE THREAD

**Issue by WYGIN** [RocketChat/Rocket.Chat#27746]
[here](https://github.com/RocketChat/Rocket.Chat/blob/303e8364a1a5e290505a3f35f8496e8e3fee4e06/apps/meteor/ee/server/services/ecdh-proxy/lib/server.ts#L16) i found there is a Missing CSRF middleware & cookie-based authentication may be vulnerable to CSRF.

**Comment by xxxmadxxx** [comment]
Hi @WYGIN, please, read the policy and report in https://hackerone.com/rocket_chat so we can better manage your issue.
