### ISSUE TITLE
Website in not fully responsive

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#27759]
### Description:
After restore down rocket.chat or in small screen, maximum contents starting or left side parts and buttons are out of the page. Infact after using the horizontal scroll-bar same problem is occurred.

### Steps to reproduce:

1.Open Rocket.Chat website in desktop.
2. Restore Down the browser 
3. scroll horizontally

### Expected behavior:
All contents and buttons should be perfectly visible using horizontal scrollbar.

### Actual behavior:

https://user-images.githubusercontent.com/81948346/212660052-85a4c5e3-cd7c-4eca-8b25-f8ef083858ae.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System:wndows 10(22H2)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: dunno
- NodeJS Version: 19.4.0 
- MongoDB Version:6.0.3

### Client Setup Information

- Desktop App or Browser Version:Microsoft Edge 108.0.1462.76 (Official build) (64-bit).
- Operating System:wndows 10(22H2)

**Comment by anikdhabal** [comment]
should i work on this issue?

**Comment by Shubham043** [comment]
I want to work on this issue please assign me

**Comment by dudanogueira** [comment]
Hi! Thanks for the input out our website.

This code doesn't live here in Github, so I can only relay this to our dev dev.

THanks!

**Comment by dudanogueira** [comment]
Hi! This seems fixed now. Closing.

Thanks for the report!!
