### ISSUE TITLE
Mobile app shows a web wrapper as opposed to a proper app

### ISSUE THREAD

**Issue by benjackson1111** [RocketChat/Rocket.Chat#27757]
### Description:

I have a self-hosted instance I've just set up after much trouble to move away from Slack after they changed their policy around message history. I then finally got SSL / reverse proxy working, imported Slack data and loaded up the iOS app only to discover that it's a wrapper for the desktop web site. I can't find any info about this in your docs or support forums. I'm very confused. What I'm seeing does not match what I see as screenshots for the app on the App Store. I've even downloaded the Test Flight beta version and it's the same. How do I make it work as expected and as advertised in the app store?

I'm sorry if I've missed something, I admit I've just done an all nighter trying to make reverse proxy work as the instructions provided didn't cover everything and was showing a white screen until I used the correct (non documented) methods for ensuring all files are covered by the proxy.

Thank you!

### Steps to reproduce:

1. Login to the iOS app
2. marvel at how ugly/messed up it is
3. get confused
![IMG_5180](https://user-images.githubusercontent.com/55636850/212521651-87196421-e207-4a2f-a0ce-ac40cd05b3c3.PNG)
<img width="270" alt="Screenshot 2023-01-14 at 7 04 46 PM" src="https://user-images.githubusercontent.com/55636850/212521654-ac7ad9b1-169c-4b49-a990-0be801a8fd67.png">

### Expected behavior:

Look like the iOS app screenshots on the app store

### Actual behavior:

![IMG_5180](https://user-images.githubusercontent.com/55636850/212521598-45bccd1d-b0dd-4cfa-8fa6-330418597c0a.PNG)

### Server Setup Information:
<img width="270" alt="Screenshot 2023-01-14 at 7 04 46 PM" src="https://user-images.githubusercontent.com/55636850/212521607-0939a30c-4171-4916-8a26-5e7f1da8d21c.png">

- Version of Rocket.Chat Server:  
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: n/a
- Operating System: n/a

### Additional context

none

### Relevant logs:

n/a

**Comment by dudanogueira** [comment]
Hi! Welcome to our community :hugs: 

Looks like you are using 6.0.0-develop that was not released yet... **so things may be moving around**... 
Not sure this is the problem, but it's one point to look for. You should **consider testing your environment on a 5.4.1** instance.

Secondly, this is definitely **not the expected outcome**. The mobile app is not only a web wrapper, but **a whole React Native App** that will consume the apis, etc.

I see you do some SSO. It would be interesting to explain more about it, so we can try understanding it better.

I will move this issue to the React Native, as this might be related.

I am sorry you had a hard time deploying Rocket.Chat. We would love to have you at our upcoming first session of the weekly helpline: https://app.livestorm.co/rocket-chat/rocketchats-weekly-technical-helpline?type=detailed

and try to understand how we can improve this experience.

Thanks!

**Comment by benjackson1111** [comment]
Thanks for your response.

All I did was follow the directions in the dev docs to install on macOS. It installed v6 without any prompting. I did have to switch Terminal to Rosetta also, due to all the errors with M1/arm (that didn’t go away even after following troubleshooting steps). I have NO idea how to make macOS install a different version to test.

No, I have not turned on SSO at all. In fact, I turned it off when I kept seeing this ugly SSO window pop up after login. All I wanted was for everyone to login with their alphashows email, not any other sign in method.

I’m glad to hear that this is not the expected outcome. I did feel it was supposed to be a react native app. I even installed react native just to see if this would make a difference!! (I thought maybe our server had to have some of the files to make the iOS app act properly, but that doesn’t make a lot of sense)

The weekly helpline seems cool.

Right now, I gave up, as I started to see that even if the iOS app worked properly there was still a lot of other issues that I couldn’t make it match Slack. So instead, I set up SlackBridge, and just made it copy every message over from Slack to Rocket.chat (and just in case, back again). Great feature!! So i have rocket chat just running on our mac server in terminal, and archiving our slack channels/messages, essentially, and stay on the free Slack plan. We’re only a small children’s theatre company.  That way we can search messages older than 90 days ago as we tend to take long gaps between our shows.

Thank you so much! I’d really be interested to see if we can get the iOS app to work properly.

Ben



:: HAVE A GREAT SHOW!! ::

Ben Jackson (he/him)
CEO & Founder
ALPHASHOWS

**Comment by benjackson1111** [comment]
Hi again!

I just wanted to follow up on this.

I saw that 6.0 and 6.1 was released so I went to upgrade my macOS instance of Rocket.Chat. This wasn’t easy, I basically had to manually remove the Rocket.Chat folder I’d setup, and set it up from scratch, and then experiment to find out where my existing db was stored and move it over (turns out if I just move the db folder inside meteor/.meteor/local - yes a HIDDEN directory - I could make it keep all my data). Firstly - I think this should be easier...

But yes there should be some instructions for how to upgrade on Mac OS X.

But in the process, I noticed that again, the instructions you provide here:

https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx <https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx>

basically say to clone Rocket.chat without extra parameters. The DEFAULT branch for Rocket.Chat on Github is the DEVELOP release!! You mentioned in your email to me that I was running 6.0.0-develop as though I had specifically selected it and I was doing the wrong thing by choosing this version. That’s not the case - I was forced to run that version because it’s the default!

So again when I upgraded, I got 6.2-develop instead of what I woudl have expected. A release candidate - some stable one.  So I finally figured out to use flag -b and specify the branch (but I also had to fork the entire thing not just the default branch, as a setting on github). Then I got 6.0 release and everything is working now.

ie... git clone -b release-candidate https://github.com/your-username/Rocket.Chat

I think you need to update your Mac OS X instructions

https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx <https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx>

It needs to specify a branch and explain how to do that.

You’re also missing a step before 'yarn build'. You need ‘yarn install’ to be run before that. It will not work without this step. This held me up for DAYS until I found someone on the internet with the same error (for a different app/project) that explained to run yarn install.

So this email is just to prompt you to update the instructions for Mac OS X.

Thanks!
Ben Jackson (he/him)
CEO & Founder
ALPHA☆SHOWS
CHILDREN'S THEATRE THAT ROCKS
 
p. 1300 850 658 <tel:1300850658> | e. ***@***.*** ***@***.***>
Warehouse 34 / 42 Mc Arthurs Road
Altona North, VIC 3025 
REAL, QUALITY THEATRE THAT COMES TO YOU! <https://www.alphashows.com.au/>
www.alphashows.com.au <https://www.alphashows.com.au/>

Alpha Shows Schedule <https://www.alphashows.com.au/schedule/> | View the upcoming schedule
Downloads <https://www.alphashows.com.au/downloads/> | Curriculum & Brochure Downloads

**Comment by hugocostadev** [comment]
Hi @benjackson1111 , thanks a lot for your feedback, we will update our docs, feel free to contribute also.

Sorry, but GitHub is only for issues/bugs related to the repository project. If you need help and have questions, check the channels below. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
