### ISSUE TITLE
The SSL reverse proxy mode broken in release 0.25

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2775]
Your Rocket.Chat version: 0.25.0 

if the Site URL points to http version (because it served too) the error is:
![image](https://cloud.githubusercontent.com/assets/16319433/14282029/12639950-fb45-11e5-92e6-41b88528bc19.png)

if the Site URL points to https - the chat is loaded, but the logo picture are not shown:
![image](https://cloud.githubusercontent.com/assets/16319433/14282160/d31d6586-fb45-11e5-9565-6c00edd32410.png)

ForceSSL are disabled. Release 0.24.0 works fine in both cases.

**Comment by engelgabriel** [comment]
Can you inspect the URL the logo is trying to load? The error message is unrelated.

The alerts about blocking an unsafe request, are correct, you should never to that.
If you want your site served overt HTTPS, you should redirect all other requests and put the correct address on your Site URL.

**Comment by rodrigok** [comment]
@zxweed Can you test our latest develop version?

**Comment by zxweed** [comment]
@rodrigok development build was ok, thanks
