### ISSUE TITLE
Seperate webhook management and parser scripts  

### ISSUE THREAD

**Issue by cbajohr** [RocketChat/Rocket.Chat#2776]
Updating a webhook script for many rooms is currently really uncomfortable. It would be much easier if you could create scripts and link them to a created webhook, instead of adding the scriptcode directly to each integration. This would allow to update many integrations that are using the same parser script.

Your Rocket.Chat version: 0.25.0

**Comment by engelgabriel** [comment]
Just so we can understand you use case, why do you use the same script for more then one web-hook?
Do you know that you can let the web-hook decide the channel it will post the message to?

**Comment by cbajohr** [comment]
I use incoming webhooks for our ticket tool for example. With this ticket tool each ticket project has one webhook in rocket chat for receiving informations for private project group. 
So the parser script is always the same for every webhook, but the webhook URL is another at the tickettool.

It would be much easier if I could edit the script at one place for all linked webhooks. Currently I have to edit all scripts in every webhook to make a script update.

**Comment by engelgabriel** [comment]
Ok, this is on the plan. We will create web-hook templates, more like App,
that can be reused or in other words, installed multiple times. So that
will do what your are looking for.



-- 
Sent from Mobile

**Comment by MartinSchoeler** [comment]
I belive that Rocket.Chat apps will solve this issue in time, I will close this for now.
