### ISSUE TITLE
Unread counter is not updated automatically after reading all messages

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat#27776]
### Description:
The unread message counter is not updated after reading all in a group, as posted also here a few weeks ago: "Mark channel as READ when I've scrolled to the bottom" https://github.com/RocketChat/Rocket.Chat/issues/27684

### Steps to reproduce:
1. Enter into a group with unread messages
2. Read all the messages and scroll down till the bottom

### Expected behavior:
The unread counter automatically disappears

### Actual behavior:
The unread counter is still reflecting there are unread messages

### Server Setup Information:
Version of Rocket.Chat Server: 5.3.5
Operating System: Ubuntu Server
Deployment Method: docker
Number of Running Instances: 2
DB Replicaset Oplog: Enabled
NodeJS Version: v14.19.3
MongoDB Version: 5.0.13 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: not relevant
Operating System: not relevant

**Comment by evgencode** [comment]
The same issue:
![image](https://user-images.githubusercontent.com/2129431/217459430-235f7184-b5f8-4a19-8d5a-058fa5dda4a1.png)

No unread messages or threads but the counter does not disappear
