### ISSUE TITLE
Users registering with @protonmail.com don't receive confirmation mail.

### ISSUE THREAD

**Issue by MaxKK** [RocketChat/Rocket.Chat#2779]
Your Rocket.Chat version: 0.24.0

The users who registered with a protonmail.com email address don't receive their confirmation link. 

Cheers.

**Comment by engelgabriel** [comment]
What does the LOG says? What SMTP are you using?

**Comment by MaxKK** [comment]
Ok, it was a problem with SMTP. Working again. Thank you.
