### ISSUE TITLE
Like or Up-vote a post

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#278]
Posts with more likes or up-votes get longer retention time.

Beyond a certain threshold likes, post becomes part of a rolling 'sticky list' at top of the room.

**Comment by graywolf336** [comment]
Maybe posts which are liked get put into a sidebar tab?

**Comment by geekgonecrazy** [comment]
@RocketChat/core do we think reactions covers this one?  As far as stickying messages we also have pinning messages.

**Comment by marceloschmidt** [comment]
I think reactions cover the "liking" features. And yes, sticking is possible via pinning, so I vote for closing this issue.

**Comment by vetash** [comment]
Reactions is not the same?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  Like mentioned I think we've got this covered with reactions and pinning
