### ISSUE TITLE
Add GIF and Stickers in emoji library.

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#27800]
### Description:

The emoji library is very backdated. In most of the communication platform have GIF and Sticker Section along with emoji in emoji library.

### Steps to reproduce:

1. Open Rocket.Chat
2. Open Emoji Library

### Expected behavior:

There should be GIF and sticker section.

### Actual behavior:

Only have Emoji.

### Server Setup Information:

- > Version of Rocket.Chat Server: 5.4.1
- > Operating System: windows 10(22H2)
- > Deployment Method: docker
- > Number of Running Instances: 1
- > DB Replicaset Oplog: donno
- > NodeJS Version: 19.4.0
- > MongoDB Version:6.0.3

### Client Setup Information

Desktop App or Browser Version:Microsoft Edge 108.0.1462.76 (Official build) (64-bit).
-Operating System: windows 10(22H2)

**Comment by anikdhabal** [comment]
@dudanogueira should I work on this issue?

**Comment by SumeetMaurya** [comment]
can you assign this to me, if no one is working on it
