### ISSUE TITLE
More Option(three dot) in thread is not working Properly

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#27801]
### Description:

In thread after clicking the option or the three dot of the lowermost message on the page, the dropdown menu or list are out of the page and also tremble continuously.

### Steps to reproduce:

1. Open Rocket.Chat
2. Go to threads 
3. Open  a long thread

### Expected behavior:

The dropdown menu should be in the page and visible all option.If the menu or list should visible above the three dot or option button after clicking just like normal message  section,then it should working fine.

### Actual behavior:

Dropdown menu is visible under the three dot button after clicking,that's why it is out of the page and also tremble continuously.

https://user-images.githubusercontent.com/81948346/213883184-711d7cbe-f0e1-4a91-9b31-099a9b6ce611.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: windows 10(22H2)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: donno
- NodeJS Version: 19.4.0
- MongoDB Version:6.0.3

### Client Setup Information

-Desktop App or Browser Version:Microsoft Edge 108.0.1462.76 (Official build) (64-bit).
-Operating System: windows 10(22H2)

**Comment by devyloper** [comment]
It is behaving perfectly on my PC. It is showing all the options without a scrollbar on the side.

**Comment by anikdhabal** [comment]
@devyloper I saw in the Rocket.chat community 1 or 2 person faced the same issue.

**Comment by dudanogueira** [comment]
I believe this issue was reported already:

#26506
