### ISSUE TITLE
Interactive tutorial for new users

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#2780]
Everytime a new user join my Rocket Chat platform, I have to learn him how to use Rocket Chat. It could be great if you introduce an interactive guide like Mattermost already does.

![](https://i.unixfox.eu/54-21-59-2016.png)

Disclaimer : I do not ask exactly copy other web chat platforms but to take up the idea.

**Comment by frdmn** [comment]
:+1:

**Comment by djeber** [comment]
:+1:

**Comment by Sing-Li** [comment]
:+1:  

We would ❤️  to see community contribution on this one!

We know many of you,  our community members,  are semi-pro bloggers and You-tubers -- here's your chance to contribute to this super project!!


Just for inspiration... in our **tiny**  RockOnPi community (folks who run Rocket.Chat on their $5 RaspberryPi servers) ... one community member @rdagger , created this ....

[![screen shot 2016-04-06 at 4 01 11 pm](https://cloud.githubusercontent.com/assets/122633/14330925/d37471ca-fc10-11e5-9055-efb8bb1084eb.png)](https://www.youtube.com/watch?v=BevcvRLsa9Y&feature=youtu.be)

**Comment by Molle500** [comment]
:+1:

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
