### ISSUE TITLE
bash scripts are not portable

### ISSUE THREAD

**Issue by AJ-Acevedo** [RocketChat/Rocket.Chat#2781]
I noticed that the bash scripts like [install.sh](https://github.com/RocketChat/Rocket.Chat/blob/develop/install.sh) and [example-build.sh](https://github.com/RocketChat/Rocket.Chat/blob/develop/example-build.sh) are not using portable bash shebangs. Not everyone uses the default bash. For example you can change your default bash using homebrew.

These:
`#!/bin/bash`

Should look like this:
`#!/usr/bin/env bash`

I'd be more than happy to submit a PR if you guys are interested.

**Comment by engelgabriel** [comment]
Can you do a pull request?

**Comment by AJ-Acevedo** [comment]
@engelgabriel I submitted a pull request for this issue.
