### ISSUE TITLE
cryptographically weak pseudo-random number used

### ISSUE THREAD

**Issue by WYGIN** [RocketChat/Rocket.Chat#27811]
### Steps to reproduce:

1. go to this [link](https://github.com/RocketChat/Rocket.Chat/blob/16eacbf94fa8514e2d0f96012b1748de3fa1d220/apps/meteor/app/lib/server/lib/PasswordPolicyClass.js#L163) 
2.  on line 163 you will find password is generated by maths.random which is cryptographically weak.
3. [about it](https://cwe.mitre.org/data/definitions/338.html) 

### Expected behavior:

Using cryptographically strong password.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by xxxmadxxx** [comment]
Hi @WYGIN,

Please, report to us at https://hackerone.com/rocket_chat so we can have our security team working on this.

Thanks!

**Comment by WYGIN** [comment]
@xxxmadxxx thanks for suggestion but i already made a PR on the issue so if everything looks perfect you can check the PR & merge it
