### ISSUE TITLE
Can't use regexp in Livechat URL

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#27826]
### Description:

We are facing issue with RocketChat LiveChat / OmniChannel. There's a problem with very few features at at this module of RC. We wanted to use the message trigger in more advanced way but it's not working.

We wanted to setup welcome message with regexp at URL (tested at free version, production is enterprise). There's a problem that it's just not working.

The regexp which was working: `^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$`

Not Working regexps:
- `^(?:http(s)?://)?[\w.-]+(?:.[\w.-]+)+rc/en/[\w-._~:/?#[]@!$&'*+,;=.]+$`
- `^(?:http(s)?://)?[\w.-]+(?:.[\w.-]+)*rc/en/$`
- `/(cs|en)/`

### Steps to reproduce:

1. Setup livechat trigger in the way described below
2. Try to use trigger on website
3. Message is not shown

### Expected behavior:

Message is shown

### Actual behavior:

Message is not shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 14.19.3
- MongoDB Version:4.4.18

### Client Setup Information

- Desktop App or Browser Version: Latest Chrome
- Operating System: Any

### Additional context

N/A

### Relevant logs:

N/A

![2023-01-24_17-29-11](https://user-images.githubusercontent.com/11560794/214352636-3bbf1128-b5d9-49eb-96d3-ec3b0807d88d.png)

**Comment by KevLehman** [comment]
Hey @dusatvoj , we fixed a similar issue on 6.3.2, can you check over there if the issue still persist on that release?

Thanks!

**Comment by dusatvoj** [comment]
@KevLehman , yes we want to check if it's working ASAP.

Even we have an enterprise support, it took smth around 6 months _(:facepalm: ; also without backport to version we reported in - even it was still supported version)_ from bug report to fix it and support told me that it should be fixed in 6.3.0. We weren't brave enough to test it now but we are planning to do it in next days / weeks.
