### ISSUE TITLE
Switching display options breaks account/webpage

### ISSUE THREAD

**Issue by Gabe88def** [RocketChat/Rocket.Chat#27829]
Description:

I have 2 users so far that is experiencing some issues when changing their Display Settings from 'Condensed to Extended'Steps to reproduce:

Open Rocket.chat
Click on Display settings
Had settings from Condensed and changed it to Extended.
Expected behavior:
When clicking on Extended display setting the webpage turns display to extneded

Actual behavior:

Testing Account:
https://user-images.githubusercontent.com/119975343/214366367-4dfa133f-1cb1-44ce-ad19-8e6edab5b68b.mp4

Server Setup Information:

Version of Rocket.Chat Server: 5.4.1
Operating System: WIndows 10
Deployment Method: Ubuntu 20
Number of Running Instances: 1
DB Replicaset Oplog: (oplog Enabled)
NodeJS Version: 14.21.1
MongoDB Version: 4.4.18 / wiredTiger
Client Setup Information

Desktop App or Browser Version: Both
Operating System: Windows 10
No issues with mobile application
Additional context
Relevant logs:
[104.237.128.54-1674582916748.log](https://github.com/RocketChat/Rocket.Chat/files/10492728/104.237.128.54-1674582916748.log)
[104.237.128.54-1674582968208.log](https://github.com/RocketChat/Rocket.Chat/files/10492729/104.237.128.54-1674582968208.log)

**Comment by dudanogueira** [comment]
Hi! Thanks for reporting this issue :hugs: 

This is probably some UI issue, so the relevant log should be at the browser console. Can you notice anything there (under developer tools)

Thanks!

**Comment by Gabe88def** [comment]
I thought so. So far only 3 users have experienced this issue. I have included a video of the issue as well as the browser console and logs. 

https://user-images.githubusercontent.com/119975343/214939862-f3f4d0ea-063b-494f-afc3-24ae54f557ed.mp4

[69.164.207.118-1674763740843.log](https://github.com/RocketChat/Rocket.Chat/files/10513035/69.164.207.118-1674763740843.log)
[69.164.207.118-1674763733443.log](https://github.com/RocketChat/Rocket.Chat/files/10513036/69.164.207.118-1674763733443.log)

**Comment by Gabe88def** [comment]
@dudanogueira Hello, Any feedback on why this may be happening to some user profiles?

**Comment by Gabe88def** [comment]
Issue has not been resolved.

**Comment by dudanogueira** [comment]
Hi, this looks like a really specific issue.

This will always happen to those 3 specific users and with others never happens?

**Comment by Gabe88def** [comment]
Hello @dudanogueira ,
Yes, that is correct, only specific users are having issues. two so far. I cloned the server and tested with my account. When clicking on display settings it is set to 'compressed'. As soon as I change it to "Expand" the issue happens as per the video shown above.

**Comment by dudanogueira** [comment]
Ah. That makes it even harder to fix, as it's not easily reproducible.

On those kind of situation, we have better results debugging that by joining directly into your workspace.

Do you think this is possible?

Thanks!

**Comment by Gabe88def** [comment]
@dudanogueira Sure, I'll be working on that for you and create your account during this week. I'll keep you posted
