### ISSUE TITLE
Link preview cannot be collapsed

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27827]
### Description:

Rocket.Chat creates previews for links, if possible. This preview can be collapsed by clicking on an arrow symbol. However, for certain previews, this arrow can be clicked, but the preview does not collapse.

### Steps to reproduce:

1. Submit a message containing the link https://emoji.supply/kitchen/?%F0%9F%98%82+%F0%9F%A6%81=rt
2. Wait for the link preview to be shown.
3. Click on the arrow symbol above the preview.

### Expected behavior:

The preview is collapsed as it happens with other links like https://www.reddit.com/gallery/103zkpd:

Before clicking the arrow:

![image](https://user-images.githubusercontent.com/404840/214362408-370a319b-df30-4204-951f-d241120bb49e.png)

After clicking the arrow:

![image](https://user-images.githubusercontent.com/404840/214362518-cfd02554-9838-47a7-be64-31dde6e34394.png)

### Actual behavior:

The preview is not collapsed.

Before clicking the arrow:

![image](https://user-images.githubusercontent.com/404840/214362679-d73b3800-0e6a-48db-beb5-240335bdc3b3.png)

After clicking the arrow:

![image](https://user-images.githubusercontent.com/404840/214362753-1ea569fe-71a3-4025-b435-ca10f03627b5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Deployment Method: Docker
- Number of Running Instances:  1
- MongoDB Version: 5.0.14 / wiredTiger (oplog Aktiviert)

### Client Setup Information

- Desktop App or Browser Version:
  - Firefox 109.0 (64-bit)
  - Google Chrome Version 109.0.5414.75 (Offizieller Build) (64-Bit)
  - Rocket.Chat Electron app 3.8.16
- Operating System: Windows 10, Arch Linux

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing it out. 

This was fixed already on 6.0.0-develop!

**Comment by paulchen** [comment]
@dudanogueira Thanks, I just verified using the current `develop` image from Docker Hub (`f17427a50dcd`) that this issue is fixed in Rocket.Chat 6.0.0-develop.
