### ISSUE TITLE
error to start rocketchat

### ISSUE THREAD

**Issue by Marsalys** [RocketChat/Rocket.Chat#27831]
I have always error to start rocketchat
● rocketchat.service - Rocket.Chat server
     Loaded: loaded (/etc/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-01-24 19:51:42 UTC; 26s ago
    Process: 20626 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
   Main PID: 20626 (code=exited, status=1/FAILURE)

janv. 24 19:51:42 rocketchat rocketchat[20626]:     stale: false,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     compatible: true,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     heartbeatFrequencyMS: 10000,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     localThresholdMS: 15,
janv. 24 19:51:42 rocketchat rocketchat[20626]:     setName: 'rs01',
janv. 24 19:51:42 rocketchat rocketchat[20626]:     logicalSessionTimeoutMinutes: undefined
janv. 24 19:51:42 rocketchat rocketchat[20626]:   }
janv. 24 19:51:42 rocketchat rocketchat[20626]: }
janv. 24 19:51:42 rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
janv. 24 19:51:42 rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.
root@rocketchat:~#

please help me

I have two nodes
node mongodb and node rocketchat

I don't find process to install it

**Comment by dudanogueira** [comment]
Hi! Welcome to our community!

Before opening an issue, please, always feel in the issue template and check this doc:
https://docs.rocket.chat/getting-support/community-resources

Also, this is not a product issue, but a deployment one.

We are hosting a weekly technical helpline for helping on deployment/migrations:
https://app.livestorm.co/rocket-chat/rocketchats-weekly-technical-helpline

if you want a more imediate support, please, join ou Community Support channel:
https://open.rocket.chat/channel/support

Closing this issue for now.

THanks!
