### ISSUE TITLE
Severe lag with OS X client when application is running on Retina Display

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#2783]
Your Rocket.Chat version: just recloned from master

![bildschirmfoto 2016-04-06 um 10 39 33](https://cloud.githubusercontent.com/assets/944459/14310737/e015d32e-fbe3-11e5-950c-821520584d6d.png)

I am using a Cinema Display in addition to my MacBook Pro Retina screen and I noticed that whenever `Rocket.Chat+` is running on the Retina display, the fans are spinning like crazy and the Rocket.Chat client by itself gets really unresponsive and laggy.

Whenever I move the application from the MacBook screen to my (non-retina) Cinema Display, the application is fast and the lag/performance issues are gone immediately.

I made two comparison GIFs to show you the issue:

#### Retina display (laggy) - [alternative .mov](http://up.frd.mn/6Fx2uOSoUW.mov)

![1_laggy mov](https://cloud.githubusercontent.com/assets/944459/14310816/37c1293e-fbe4-11e5-9e93-6d825656d118.gif)
 
#### Cinema display (no lag) - [alternative .mov](http://up.frd.mn/hnM9nrxmyM.mov)

![2_non-laggy mov](https://cloud.githubusercontent.com/assets/944459/14310861/6d4894d4-fbe4-11e5-9bbc-1ba8ef31845c.gif)

Any ideas?

**Comment by frdmn** [comment]
Crud, I just noticed that i should have probably raised this issue in the https://github.com/RocketChat/Rocket.Chat.Electron/ repository.

**Comment by rodrigok** [comment]
@frdmn Had you downloaded the app from the Map App Store?

If yes, can you try the DMG version? https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.3.0

I'd test here and this happens for me only when I'm using the version distributed via Mac App Store. If you confirm I will open a new issue on the electron's repository.

Thanks

I will move this issue to the correct place

**Comment by rodrigok** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #164](https://github.com/RocketChat/Rocket.Chat.Electron/issues/164) via [**ZenHub.io**](https://www.zenhub.io/)
