### ISSUE TITLE
Emojis with underscores in their name not rendered when prepended by an underscore

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27835]
### Description:

When there is an underscore in front of an emoji having an underscore in its name, that emoji is not rendered.

### Steps to reproduce:

1. Submit the message `_ :gay_pride_flag:`.

### Expected behavior:

![image](https://user-images.githubusercontent.com/404840/214405968-e2fc9667-bbfa-43ac-828c-821125d14898.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/404840/214405368-74dd7017-75f2-499e-88c1-bfc72237ea30.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Deployment Method: Docker
- MongoDB Version: 5.0.14

### Client Setup Information

Issue is browser and operating system agnostic.

**Comment by dudanogueira** [comment]
Thanks!

**Comment by paulchen** [comment]
I just found out that this actually works as expected on Rocket.Chat 6.6.6. Thanks to whoever fixed this in the meantime!
