### ISSUE TITLE
Emojis not rendered inside bold text

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27839]
### Description:

When writing bold text, emojis created by their name cannot be used.

### Steps to reproduce:

1. Write the message `:family_mmbb: *:family_mmbb:*`.

### Expected behavior:

![image](https://user-images.githubusercontent.com/404840/214411756-9974411c-4f36-4460-aa85-03f1ea3ee410.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/404840/214410920-220a23c0-6b17-4c93-8808-6faf78b52068.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Deployment Method: Docker
- MongoDB Version: 5.0.14

### Client Setup Information

Issue is browser and operating system agnostic.

### Additional context

This at least happens for italics as well.

**Comment by durgesh077** [comment]
I want to resolve this issue. Please assign it to me.

**Comment by Hundred-Eyes** [comment]
I would like to resolve this issue, may I have it assigned

**Comment by ashish-S24** [comment]
Is this issue still available? I would like to give it a try.
