### ISSUE TITLE
Full end to end encryption

### ISSUE THREAD

**Issue by vaggosifa** [RocketChat/Rocket.Chat#2784]

**Comment by geekgonecrazy** [comment]
@vaggosifa can you be more specific?  Which part of enabling end to end encryption?  There is a lot of parts to doing end to end encryption.  Some including SSL.  Which is something the person setting up would handle.

So will need more details.  :smile:

**Comment by vaggosifa** [comment]
Full end to end encryption everywhere in group chats and direct chats.Something like Telegram's encryption.

**Comment by marceloschmidt** [comment]
We already have a few issues requesting OTR and Axolotl implementations. Let's keep discussions there.
