### ISSUE TITLE
'otp-error' when changing user roles 

### ISSUE THREAD

**Issue by antoniozh** [RocketChat/Rocket.Chat#27849]
### Description:

When I am trying to set roles for users on my web client, an error prevents me from setting them. The error is called 'otp-required'. 

### Steps to reproduce:

Go to Administration - Users on the web browser
Try to change a new users role to Admin
An 'otp-required' error appears

### Expected behavior:

User roles will be set correctly or at least a pop up with OTP is called to confirm changes.

### Actual behavior:

The administrator is denied access to changing the settings 

### Server Setup Information:

20230125-13:55:43.871(0) +----------------------------------------------+ 
I20230125-13:55:43.871(0) |                SERVER RUNNING                | 
I20230125-13:55:43.871(0) +----------------------------------------------+ 
I20230125-13:55:43.871(0) |                                              | 
I20230125-13:55:43.871(0) |  Rocket.Chat Version: 4.1.2                  | 
I20230125-13:55:43.871(0) |       NodeJS Version: 12.22.1 - x64          | 
I20230125-13:55:43.871(0) |      MongoDB Version: 4.4.15                 | 
I20230125-13:55:43.871(0) |       MongoDB Engine: wiredTiger             | 
I20230125-13:55:43.871(0) |             Platform: linux                  | 
I20230125-13:55:43.871(0) |         Process Port: 3000                   | 
I20230125-13:55:43.871(0) |             Site URL: http://localhost:3000  | 
I20230125-13:55:43.872(0) |     ReplicaSet OpLog: Enabled                | 
I20230125-13:55:43.872(0) |          Commit Hash: 2aba8d2d82             | 
I20230125-13:55:43.872(0) |        Commit Branch: HEAD                   | 
I20230125-13:55:43.872(0) |                                              | 
I20230125-13:55:43.872(0) +----------------------------------------------+ 

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 109.0.5414.75
- Operating System: Windows 11

### Additional context

The popup for the OTP is correctly shown when trying to change E-Mail settings. 
Afterwards, the user roles can be set for the remainder of the administrator login session.
This means that the functionality for an OTP is implemented, just not when changing roles and the additional OTP confirmation is needed.

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing it out.
I was not able to reproduce this on latest 6.0.0-develop.

OTP worked fine for editing user. Only when the pop up is canceled, it does give this error.

Please, consider upgrading your workspace to at least 4.8.7, as 4.1.2 is outdated and vulnerable.

**Comment by antoniozh** [comment]
I updated to 5.4.0 and it works now. It seemed like that the Docker.Official.Image docker compose file only pulled the 4.1.2 image!
