### ISSUE TITLE
Custom Translation allows invalid json and break UI

### ISSUE THREAD

**Issue by sector7gp** [RocketChat/Rocket.Chat#27846]
### Description:

We wanted to make some changes using custom translation, we forgot to include the `<br/>` tag at the beginning, so the front end had broken

### Steps to reproduce:

1. Settings
2. General
3. Translations
4. Custom translations
5. Set the field with: `<code>{ "en": { "Channels": "Rooms" }, "pt": { "Channels": "Salas" } }</code>`  ignoring the` <br/>
`
the next output is how is setted in the setting document in mongo:
```
 db.rocketchat_settings.find({_id : "Custom_Translations"}).pretty()
{
        "_id" : "Custom_Translations",
        "createdAt" : ISODate("2022-12-05T20:37:53.542Z"),
        "value" : "<code>{ \"en\": { \"Welcome\": \"Bienvenidos\" } }</code>",
        "packageValue" : "",
        "valueSource" : "packageValue",
        "secret" : false,
        "enterprise" : false,
        "i18nDescription" : "Custom_Translations_Description",
        "autocomplete" : true,
        "sorter" : 25000,
        "ts" : ISODate("2022-12-05T20:37:53.542Z"),
        "type" : "code",
        "group" : "General",
        "section" : "Translations",
        "public" : true,
        "i18nLabel" : "Custom_Translations",
        "hidden" : false,
        "blocked" : false,
        "requiredOnWizard" : false,
        "env" : false,
        "_updatedAt" : ISODate("2023-01-25T13:26:36.722Z")
}
```
notice the lack of the `<br/>` tag in the value field

### Expected behavior:

The front end still alive

### Actual behavior:
The front end breaks

![image](https://user-images.githubusercontent.com/1781640/214588865-986250e7-eeb9-470a-bb5e-5ddeae077009.png)

### Server Setup Information:

Implementación
Versión 5.4.1
ID de implementación BY5JmCq5iXeezaP5e
Versión de motor de aplicaciones 1.36.0
Versión de nodo v14.19.3
Migración de base de datos
281 (25 de enero de 2023 10:28)
MongoDB 5.0.8 / wiredTiger (oplog Habilitada)
Detalles de confirmación HEAD: (f7908e8e8)
Rama: HEAD
PID 751170

### Client Setup Information

Happens only in web and desktop app

### Workarround
Change the setting by mongosh

Open your OS terminal

open monsgo console

`> mongo`

Run this query to show the values in the DB

`rs01:PRIMARY> db.rocketchat_settings.find({_id : \"Custom_Translations\"}).pretty()`

run this query to clean the custom field

`rs01:PRIMARY> db.rocketchat_settings.update({"_id":"Custom_Translations"},{$set:{"value":""}})`

**Comment by Pradumn27** [comment]
Hi @dudanogueira can you assign me this issue?

**Comment by Sandeepdecode** [comment]
Hi, I can fix this issue kindly assign me

**Comment by dudanogueira** [comment]
Nice PR, @Pradumn27 !! Congratulations!!!

**Comment by Pradumn27** [comment]
Thank you @dudanogueira . Can you also review and merge the PR? Thank you.

**Comment by Gauravjadhav22** [comment]
hey,
i can fix this please assign me!..

**Comment by Gauravjadhav22** [comment]
hey,
i can fix this please assign me!..

**Comment by Gauravjadhav22** [comment]
hey,
i can fix this issue please assign me!..

**Comment by Akshaybagai52** [comment]
Hey I can fix this issue 
Can you assign me?

**Comment by Gua00va** [comment]
Hey!! I want to work on this issue. I'm new here so I'm really excited to start contributing. Please assign it to me.

**Comment by MewadaAnkit** [comment]
Hey , I want to work on this issue . Please assign it to me.

**Comment by Shiva953** [comment]
Hey,is this issue still open? I would like to work on it.

**Comment by tejastomarbyte** [comment]
Hey, is this isssue still open? Please assign it to me I would like to work on it.

**Comment by enoch85** [comment]
This happened to me today as well. Would be super nice if [the PR](https://github.com/RocketChat/Rocket.Chat/pull/27873) could be merged soon!

cc  @dougfabris
