### ISSUE TITLE
Sent and read message icon

### ISSUE THREAD

**Issue by graftork** [RocketChat/Rocket.Chat#27851]
Hello, I ask you to make the icon of the received message brighter (more different) or in a different shape. There is absolutely no difference between read and unread messages. Thank you!

**Comment by dudanogueira** [comment]
Hi!

Please, when opening a new issue, go thru the template providing all the necessary info.

This was already reported, and was changed in 6.0.0-develop:

![image](https://user-images.githubusercontent.com/1761174/214829954-87643d66-c400-4755-bdbb-a97ff206a3a1.png)
