### ISSUE TITLE
Team Channnel Auto-Join issue

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#27852]
### Description:

We have a private team with private channels but we want to auto-join people from the team into some subset of channels. There's an error `no default error message specified` (which is not so specific, lol)

### Steps to reproduce:

1. Create a private team
2. Create private channel inside of private team
3. Try to setup Auto-Join

### Expected behavior:

Auto-Join successful setup

### Actual behavior:

![image](https://user-images.githubusercontent.com/11560794/214826214-0fb817bd-22d3-465f-af1d-aba8d1ff71fb.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: Debian linux
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4.18

### Client Setup Information

- Desktop App or Browser Version: App @ MacOS, don't know the version (i think it's server side issue, btw)
- Operating System: MacOS X

### Additional context

N/A

### Relevant logs:

N/A

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing it out!

Does the auto join works even after this error message?
I have just tested this on 6.0.0-develop, and I didn't get this error message and it worked fine.

Can you check the API the requests when clicking the option? 
it should be http://localhost:3000/api/v1/teams.updateRoom

This might be a UI problem only. If you state the auto join works even with this error, we consider it fixed already :)

Thanks!
