### ISSUE TITLE
Emoji size

### ISSUE THREAD

**Issue by tanc** [RocketChat/Rocket.Chat#2786]
Rocket.Chat version: 0.25.0

The emoji are quite tiny and hard to see. One thought was whether we could show a larger emoji if the emoji is displayed on its own? Much like Skype does. Thoughts?

**Comment by engelgabriel** [comment]
Like Skype too.

**Comment by ChristianFusco** [comment]
#3072 I think I made a decent fix for this.  I'm not sure if it's in the file you want it to be in, but I'll move it wherever you'd like.

**Comment by krf** [comment]
Is it possible to make this optional or add an option to disable this behavior? I find it quite annoying, to be honest :)
