### ISSUE TITLE
Unable to delete video conference message.

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27869]
### Description:

In the latest versions of Rocket Chat, the format of messages about the start of a video conference in the chat has changed. Now, even the channel owner cannot delete the call message. The menu is simply missing from such messages.
Tested on version 5.4.1 and open.rocket.chat server.
We use Jitsi Meet for call integration.

### Steps to reproduce:

1. Make a call.
2. Try to delete the call message.

### Expected behavior:

The call message can be deleted.

### Actual behavior:

The call message cannot be deleted.
![Clipboard - January 27, 2023 4_52 PM](https://user-images.githubusercontent.com/104189570/215103208-6e9b3255-112e-4ba1-a995-2d30e527ab74.png)

**Comment by dudanogueira** [comment]
Thank you very much @shevchukma for you awesome issues report recently, always with a good catch!

I believe that his is not a message exactly, but a _system message_.  And it would indeed be nice to be able to both delete/hide per message, and also configure the channel to hide those altogether

**Comment by Auricmondal** [comment]
Hey @dudanogueira , I am new to open source contribution. I want to contribute to this issue. Can you help me get started?

**Comment by hugocostadev** [comment]
I'm not sure when, but this was fixed already... thanks for your interest @Auricmondal
