### ISSUE TITLE
not able to clone repo on windows

### ISSUE THREAD

**Issue by Rishab49** [RocketChat/Rocket.Chat#27885]
### Description:
while cloning the following error

Cloning into 'Rocket.Chat'...
remote: Enumerating objects: 355526, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 355526 (delta 48), reused 62 (delta 24), pack-reused 355419Receiving objects: 100% (355526/355526), 649.55 MiB | 3.73 MiB/s
Receiving objects: 100% (355526/355526), 650.51 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (232381/232381), done.
error: invalid path 'apps/meteor/definition/externals/meteor/jparker:gravatar.d.ts'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows 10

**Comment by AdityaSingh-02** [comment]
Try to setup Rocket.chat on wsl Ubuntu.. as codebase has deep folder nesting and windows just face problems I don't know why 🥲 .. and you can ask your doubts on rocket chat community https://open.rocket.chat/channel/Rocket-Chat-Open-Community

**Comment by dudanogueira** [comment]
That's right.

Also, read this before opening an issue: https://docs.rocket.chat/getting-support/community-resources

here you can find better help on using windows for development
https://open.rocket.chat/channel/working-on-windows-wsl2
