### ISSUE TITLE
Linking the company url to the companies listed under Enterprise

### ISSUE THREAD

**Issue by ItsRoy69** [RocketChat/Rocket.Chat#27883]
### Description:
When I am visiting the page "https://www.rocket.chat/enterprise" I came across few companies, thus linking the url with the company logos will be better UI
![image](https://user-images.githubusercontent.com/78967360/215332446-503246ed-782f-4f50-aedb-bf4c109def5f.png)

### Steps to reproduce:

1. Go to "https://www.rocket.chat/enterprise"
2. Click on the logos of companies
3. Nothing happens

### Expected behavior:

Mentioned sites will appear

### Actual behavior:

Nothing appears

**Comment by ItsRoy69** [comment]
I can work on this issue

**Comment by dudanogueira** [comment]
THanks for pointing it out!

This code does not live on github, so we can only rely them to our website developer.

**Comment by ItsRoy69** [comment]
Okay okay... Thanks

**Comment by Telford0** [comment]
Trading crypto and making profit, an expert like Lauren B Alex will guide you to make good profits,  she is on Facebook message her no how to get start.

**Comment by ItsRoy69** [comment]
?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
