### ISSUE TITLE
© 2022 Rocket.Chat should be changed to © 2023 Rocket.Chat

### ISSUE THREAD

**Issue by aditi5050** [RocketChat/Rocket.Chat#27889]
![rc_1](https://user-images.githubusercontent.com/102579070/215510378-747ff7b1-82e7-4a2b-9a31-26dbe2816e6d.jpg)

**Comment by dudanogueira** [comment]
Thanks!!

**Comment by aditi5050** [comment]
Welcome 🙂

**Comment by Subhrajit-Dutta** [comment]
Hey! I am new to open source. Can I work on this issue?

**Comment by Rishav1707** [comment]
Unable to run this site locally.
The following error is occur:
![node](https://user-images.githubusercontent.com/97666287/216349715-1a6c70ea-306a-43d5-98eb-afb44c2a2925.png)

**Comment by okaydivyansh** [comment]
Hi I'm new to open source. Can I work on this?

**Comment by SohamRatnaparkhi** [comment]
> Unable to run this site locally. The following error is occur: ![node](https://user-images.githubusercontent.com/97666287/216349715-1a6c70ea-306a-43d5-98eb-afb44c2a2925.png)

Hey, you can use `nvm` which is node version manager to install node version 14.21.2. After installing nvm, following steps will solve this issue:
``` bash
nvm i 14.21.2
nvm use 14
```
