### ISSUE TITLE
Hyperlinks containing some special characters are broken

### ISSUE THREAD

**Issue by DClabaut** [RocketChat/Rocket.Chat#27890]
### Description:

Hyperlinks containing some special characters are not displayed correctly inside the channel, yet they are displayed correctly inside a thread.

### Steps to reproduce:

- Go to a channel on RocketChat
- Send "https://rocket.chat/:api/health" and "http://rocket.chat?text=(some_argument)"
- Reply in thread, send  "https://rocket.chat/:api/health" and "http://rocket.chat?text=(some_argument)"

### Expected behavior:

- Links are displayed as they were entered in both the channel and the thread, and clicking the link takes the user to the right place
- Current special characters breaking the links are: `# ( ) :`

### Actual behavior:

- Links are displayed incorrectly in the channel, and clicking the link takes the user to the truncated link

![Screenshot from 2023-01-30 12-00-32](https://user-images.githubusercontent.com/965290/215544794-25cd00cf-b98f-40f3-943b-c4a3aaae21ac.png)

![Screenshot from 2023-01-31 11-52-11](https://user-images.githubusercontent.com/965290/215829069-a0b3474a-90dc-41f5-abaa-b0e097f750bc.png)

- Links are displayed correctly in the thread, and clicking the link takes the user to the right place

![Screenshot from 2023-01-30 12-00-46](https://user-images.githubusercontent.com/965290/215544836-64bf8786-450d-4858-b27f-1ed9004379ef.png)

![Screenshot from 2023-01-31 11-52-28](https://user-images.githubusercontent.com/965290/215829113-e7b6502a-6469-4c88-b5fc-b218c027d37b.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  5.0
- Operating System:  Debian
- Deployment Method:  Tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: All
- Operating System: Windows, Linux

### Additional context

Similar to https://github.com/RocketChat/Rocket.Chat/issues/27733

**Comment by DClabaut** [comment]
Almost. #27733 identifies the issue only with parenthesis, I'm adding colons, and there are probably other special characters. Also your comment there asked to fill the correct issue template, and here it is.

**Comment by hugocostadev** [comment]
Thanks for reporting @DClabaut we did a fix for that
