### ISSUE TITLE
Personal Wall -  subsume core Facebook / Twitter (but private and controlled)

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#279]
Allow a directed room to oneself.   Only one single writer allowed in this room, but unlimited visitors.

Visitors gets a 'facebook-skinned' or 'twitter-skinned' view into all posts in the room.

Native mobile apps with specialized views: enable private social-network styled interactions.

Depends on #277 and #278

Finally give that sparse index a _real_ test :)
##

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.
