### ISSUE TITLE
The Image crashes when we use Github on mobile

### ISSUE THREAD

**Issue by aditi5050** [RocketChat/Rocket.Chat#27901]
# This is how it looks
![issue11](https://user-images.githubusercontent.com/102579070/215683376-6815a413-85c3-403b-b689-7176c2a3a9c9.jpeg)
# This how it should look like
![issue1](https://user-images.githubusercontent.com/102579070/215683390-0e7ce577-b87e-4dab-b918-ac27c3f6e6e4.jpg)

**Comment by divyanshchahar** [comment]
Can I work on this issue?

**Comment by divyanshchahar** [comment]
@aditi5050 are you using github app on mobile or github website in the browser on mobile

**Comment by aditi5050** [comment]
@divyanshchahar I'm using it on GitHub app

**Comment by dudanogueira** [comment]
Hi, please, fill in the Issue template.

We need to know the version and steps to reproduce.

**Comment by akash19coder** [comment]
@aditi5050 I guess it's not just on mobile but everywhere because I just viewed README in my desktop. The photos are missing.

**Comment by aditi5050** [comment]
I guess it is only not working on mobile and tab in my case it is working fine on my laptop but crashing on my mobile

**Comment by AdarshVMore** [comment]
is the issue solved ?

**Comment by Arnabdaz** [comment]
> @aditi5050 I guess it's not just on mobile but everywhere because I just viewed README in my desktop. The photos are missing.

> I guess it is only not working on mobile and tab in my case it is working fine on my laptop but crashing on my mobile

hello I believe this issue is due to dns ... try changing your dns to google dns or cloudflare dns and try loading again.... 

**https://developers.google.com/speed/public-dns/docs/using** you can refer to this guide for further details.
**https://developers.cloudflare.com/1.1.1.1/setup/android/** incase you don't prefer google dns you can use cloudflare dns.

**Comment by Arnabdaz** [comment]
I hope this works if it does pls let know so that the issue can be closed.
