### ISSUE TITLE
auto role - saml  issues 

### ISSUE THREAD

**Issue by assafm81** [RocketChat/Rocket.Chat#2790]
Your Rocket.Chat version: 0.25
first :  i can create new user with all the values:
email, name, username 
but i can't auto associate the user to a an existing rule 
i am always get the 'User' role for new user creation.

any one solved that ?

**Comment by marceloschmidt** [comment]
You can assign a new role to a user if you go to Administration -> Permissions. Does that solve it for you?

**Comment by MartinSchoeler** [comment]
Closing due lack of response

**Comment by janrudolph** [comment]
@MartinSchoeler We also reported this issue a couple weeks ago: https://github.com/RocketChat/Rocket.Chat/issues/9689
