### ISSUE TITLE
Does not show emoji when have a character before :

### ISSUE THREAD

**Issue by vitorekr** [RocketChat/Rocket.Chat#27905]
### Description:

After analyzing some issues, I checked some with the same objective but viewed in a niche way.

The problem here is about selecting emoji by text, for example :emoji:

What was verified is that there is a demand for being able to choose an emoji by text even with some character before it, for example, *:emoji*.

![Screenshot from 2023-01-31 10-31-32](https://user-images.githubusercontent.com/56610229/215774138-0be198a0-7d56-4953-ba1c-03031b76e789.png)

### Steps to reproduce:

1. Go to a chat room
2. try to write an emoji, for example, :kiss_mm:
3. Try again, but put some character before, after or both. 
4. Look that when sending the message the emoji is not displayed.

### Expected behavior:

I want to be able to choose an emoji by text even if there is a character before or after or both

### Actual behavior:

Currently, when writing an emoji, it is not displayed if there is any character next to the ":".

### Where I can start to find this in code?

Find these three folders:
![Screenshot from 2023-01-31 10-34-35](https://user-images.githubusercontent.com/56610229/215774823-684e57a2-3368-4f84-b82b-4df6c46537b5.png)

You can find these folders following this path:
![Screenshot from 2023-01-31 10-36-01](https://user-images.githubusercontent.com/56610229/215775180-507fb766-8aa9-4380-bcc2-53bccd2b6c84.png)

I think you can find the problem, or start the study by emojiPicker.js and look the regex.
![Screenshot from 2023-01-31 10-38-08](https://user-images.githubusercontent.com/56610229/215775934-02035007-076a-4d1b-b5b2-6d9e72416f13.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.0.0
- Operating System: Linux
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.5

### Client Setup Information
- Operating System: Ubuntu-22.0.4

**Comment by mohitmohlia** [comment]
I can work on this please assign this to me

**Comment by hugocostadev** [comment]
Honestly, I have my concerns about that... Imagine if the user wants to write something that in coincidence has the emoji pattern in the middle of the string... Would show the emoji, that's why we create this condition, emojis need to have spaces between them to work... What do you think?
