### ISSUE TITLE
Livechat won't show: No such function: __ (livechat.js?_dc=042de0a...:5)

### ISSUE THREAD

**Issue by GilbertGobbels** [RocketChat/Rocket.Chat#2791]
Your Rocket.Chat version: 0.25.0
Whenever I try to use livechat on a webpage, it fails to display the window.
Instead, I get the following error in my browser console upon page load: 
` livechat.js?_dc=042de0a…:5 Error: No such function: `
Which is an error thrown when the variable "t" is assigned.
We've had livechat working without problems fine before, but it sometimes just does this, and it's really annoying.
(After installing a fully new rocket.chat instance/database the problem still wasn't solved :S)

**Comment by k0nsl** [comment]
I can confirm and recreate this as well.

**Comment by geekgonecrazy** [comment]
@sampaiodiego might have some insight into this.  I know we started investigating this.

**Comment by sampaiodiego** [comment]
livechat is broken on `master` branch (and the 0.25 version as well).
but it's already fixed on `develop` branch..

@engelgabriel should we release a hotfix version?

**Comment by geekgonecrazy** [comment]
This should be fixed with the latest release.  Let us know if not.
