### ISSUE TITLE
No more than one livechat agent can chat with a guest at a time.

### ISSUE THREAD

**Issue by achraf-jeday** [RocketChat/Rocket.Chat#2792]
When many livechat agents are online and a guest starts a chat session only one agent will be able to chat with her/him (only one agent will have access to the newly created chat channel).

### Proposed Solution

All livechat agents should have access to the guest channel including offline agents.

**Comment by graywolf336** [comment]
You can actually invite an agent into the room and they will be able to chat with them.

**Comment by achraf-jeday** [comment]
@graywolf336 thank you. Can you show me how to invite another livechat agent to the guest channel.

**Comment by graywolf336** [comment]
@achraf-jeday It's the same as any other room, via the invite slash command. `/invite @username` :)

**Comment by achraf-jeday** [comment]
@graywolf336 after I invited the agent to the guest room he is able to submit messages but unable to receive messages from the guest or from the other agent !

**Comment by graywolf336** [comment]
@achraf-jeday That's odd, it used to work that way. We'll have to wait for someone else to chime in, as I'm not sure if that is intended or a recursion bug.

**Comment by achraf-jeday** [comment]
@graywolf336 thanks for your responses just one last question:
when a guest starts a livechat session the system picks an agent to chat with her/him and leave the other agents.
How does the chat system do that (based on what)?

**Comment by graywolf336** [comment]
That would be a question for @sampaiodiego

**Comment by sampaiodiego** [comment]
so, this is a bug not related to livechat itself..
I'm submitting a fix soon =)
