### ISSUE TITLE
No error message when uploading a file that is not allowed

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27924]
### Description:

When sending some rare file types (for example [.har](https://en.wikipedia.org/wiki/HAR_(file_format))) that are not allowed to be sent, there is no message that this type of file is forbidden to be sent.

### Steps to reproduce:

1. Set "Accepted Media Types" setting in "File Upload"  section. For example `image/*,application/pdf,text/plain,application/msword`
2. Try sending a rare file type like .har
3. The file is not loaded into the chat, and there is no error message.

### Expected behavior:

An error appears like this:
![image](https://user-images.githubusercontent.com/104189570/216084439-ff079cc1-7c24-4aa3-8461-2b2a86b8f170.png)

### Actual behavior:

The message does not appear, the file is not loaded, the user does not understand what the problem is.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: Oracle Linux Server release 8.6
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: yes
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14 

### Client Setup Information

- Desktop App or Browser Version: Chrome 108
- Operating System: Win10

### Additional context

HAR file for example https://gist.github.com/ericduran/6330201

### Relevant logs:

In the browser console there are messages like this:
`a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:5 fuselage: 0.31.22
a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583 MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
registerType @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583
a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1046 strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
w @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1046
a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583 Uncaught (in promise) undefined
a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1217 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
E @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1217
a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583 Auto-Translate is disabled [error-autotranslate-disabled]
(anonymous) @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583
27145:1          Failed to load resource: the server responded with a status of 429 (Too Many Requests)
/api/v1/rooms.upload/kn4cL92kQygxT5mi5:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:5          POST https://rc.example.com/api/v1/rooms.upload/kn4cL92kQygxT5mi5 400 (Bad Request)
upload @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:5
(anonymous) @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583
f @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583
onSubmit @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583
S @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1583
Ye @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
tr @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
nr @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
Zn @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
Xn @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
(anonymous) @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
qe @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
Ve @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
ao @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
pt @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
dt @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
t.unstable_runWithPriority @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1175
_a @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
ze @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
lt @ a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139
`

**Comment by VarthanV** [comment]
@shevchukma  , I would like to work on this , Please assign me this issue

**Comment by mvvvmd** [comment]
I noticed this when I file is too large also, seems related.

**Comment by Sayan4444** [comment]
@shevchukma I raised a pull request against this issue. I hope merging this PR should solve your issue. If you want some more improvements please revert me back
