### ISSUE TITLE
Auto-translate: Translations are not displayed

### ISSUE THREAD

**Issue by meinrecht** [RocketChat/Rocket.Chat#27949]
### Description:
When enabling autotranslation in the "messages" section of the settings and as user for a channel with one of the supported languages, the messages are shown as is without any translation. However they do show the icon of the autotranslation tool used.

Also the translated message is stored in the database - this shows that the english text has actually been translated to german (which are the example languages used)  - see below.

### Steps to reproduce:
1. Activate auto translate feature Message->Auto Translate.
2. Create a channel and add two users as members of the channel.
3. Activate auto translation in the channel for each user to individual language (one german, one english).
4. Post a message as the english user in english.
5. The german user sees the original message, but the translation icon is there.
6. Clicking "show original" and "translate" on the message does not change anything (except that the icon disappears and reappears)
7. Reloading the screen does not help

I tested this myself impersonating two users, one via the browser integration, the other via the desktop client.

### Expected behavior:

Posting a message in one language should lead to the other user receiving the message in their language.

### Actual behavior:

The original message is shown as if autotranslation was disabled. The icon (of DeepL or Google, depending on the API used) is shown though.

This is a screenshot of the user that has selected language "german" getting two untranslated english messages from user neven2 (language english) using DeepL (Google is the same):
![Bildschirmfoto vom 2023-02-03 20-04-42](https://user-images.githubusercontent.com/76648671/216686218-9fbb3721-6126-4457-b3ef-9a5c5adf979a.png)

The database entry for the first one is shown here and contains the correct german translation:
```
{ "_id" : "Neg8Y3CvK4yKPJiZm", "rid" : "rqBQXfLER2ynYjZ5Z", "msg" : "Why is DeepL not translating any messages?", "ts" : ISODate("2023-02-03T18:15:20.061Z"), "u" : { "_id" : "sXzBkCKFsG7JyNvq9", "username" : "neven2", "name" : "my name" }, "_updatedAt" : ISODate("2023-02-03T18:15:20.288Z"), "urls" : [ ], "mentions" : [ ], "channels" : [ ], "md" : [ { "type" : "PARAGRAPH", "value" : [ { "type" : "PLAIN_TEXT", "value" : "Why is DeepL not translating any messages?" } ] } ], "translationProvider" : "deepl-translate", "translations" : { "de" : "Warum übersetzt DeepL keine Nachrichten?" } }
```

### Server Setup Information:
- Version of Rocket.Chat Server: 5.4.2
- Operating System: Debian bookworm/sid
- Deployment Method:  docker-compose
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.14

### Client Setup Information
Desktop app version: 3.8.13
Browser: firefox 109.0.1
Operating System: Linux

### Additional context
For enabling auto-translate the official documentation was used:
https://docs.rocket.chat/setup-and-configure/advanced-workspace-management/google-cloud/auto-translate
DeepL configuration has been set up accordingly.

I have allowed autotranslation for several roles from `admin` to `user`.

Have tried both Google API and DeepL.

Have tried different language pairs.

Have tried private messages and channels.

I tried downgrading to version 5.3.6. of `rocketchat`  - same thing.

I also tried to disable `hubot` without this making any difference.

I checked, if `docker-compose restart` or `docker-compose down; docker-compose up -d` helped when changing the API used because of this issue: https://github.com/RocketChat/Rocket.Chat/issues/20038

A closed error from 2019, that was left stale, mentions a very similar problem, although that one was solvable by doing reloads. This did not work here: https://github.com/RocketChat/Rocket.Chat/issues/14744

### Relevant logs:

No error messages from the output of `docker-compose logs -f`.
No error messages in the java script console of the app or in web developer tools of the browser.

**Comment by INFORMERadm** [comment]
Same here. Using SaaS cloud deployment. Tried every possible variation with DeepL like enabling and disabling auto-translation, before and after restarting workspace. I am convinced that my settings are correct as everything used to work fine before upgrading the workspace to version 5.4.1 and ultimately I hoped the with 5.4.2 these things would be fixed so I upgraded again but the result is the same. Auto translation does not work.

**Comment by hugocostadev** [comment]
This was fixed in this PR: https://github.com/RocketChat/Rocket.Chat/pull/27317. 
Could you try to update it to our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) and let us know? 

If you still face this issue, please, reopen it and provide us with more info about the server and browser and providers

Thanks a lot for contributing

**Comment by INFORMERadm** [comment]
i have upgraded to 6 and now all works absolutely perfectly, good job, guys.

Am Di., 4. Apr. 2023 um 14:02 Uhr schrieb meinrecht <
***@***.***>:
