### ISSUE TITLE
Add COPY button to the message menu in mobile version

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2795]
Your Rocket.Chat version: 0.25.0

It will be very useful to have local menu buttons for edit message and copy to clipboard in mobile version

![screenshot_2016-04-06-19-06-06_19-11-04](https://cloud.githubusercontent.com/assets/16319433/14324232/a6a97944-fc2c-11e5-9668-ea91c2582e96.png)

**Comment by rodrigok** [comment]
Hi @zxweed, the new version (2.3.0 https://github.com/RocketChat/Rocket.Chat.Cordova/releases) has a new native menu for that.

Are you using Android or iOS? I'm releasing the Android for public access right now and the iOS is in review by Apple right now.

**Comment by zxweed** [comment]
I have manually updated to the version 2.3.0 for Android, but the local menu still the same.

**Comment by rodrigok** [comment]
@zxweed Are you sure? This only works with Rocket.Chat server version from 0.25.0

**Comment by zxweed** [comment]
@rodrigok, sorry, I was checked version 0.24, with server version 0.25 local menu are great, thank you.

**Comment by rodrigok** [comment]
@zxweed you are welcome
