### ISSUE TITLE
On hovering a pinned massage in dark mode background becomes white in color

### ISSUE THREAD

**Issue by Veer0x1** [RocketChat/Rocket.Chat#27950]
**Description:** When your system is in dark mode, you open a pinned massage and hover over it, it changes the background according to the light mode.

**Steps to reproduce:**
1. Switch to the dark mode
2. Open a pinned message
3. hover over it.

**Expected behaviour:** It should remain in dark mode, and no changes should be visible.

**Actual behaviour:** Background changes to as per the light mode

**Operating System:**  macOS 13.1
**Browser:** Chrome

https://user-images.githubusercontent.com/96714915/216687538-a73070e9-5daf-4c50-9e43-f8a9dfdca21f.mov

**Comment by Maykkkk** [comment]
Hey, assign me this issue

**Comment by sande265** [comment]
claim
I would like to work on this issue.

**Comment by hugocostadev** [comment]
Fixed on the latests releases

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
