### ISSUE TITLE
Ошибка входа

### ISSUE THREAD

**Issue by kuznetsova46** [RocketChat/Rocket.Chat#27952]
Не удается войти. Появляется ошбка
![2023-02-05_08-43-06](https://user-images.githubusercontent.com/124485248/216803977-cbf409b9-92b9-409d-b647-8b7e99c65b74.png)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
