### ISSUE TITLE
Scroll Bar is not present in Message container and also in thread

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#27953]
### Description:

No scroll bar is present in message  container and also in thread. It is very difficult to see old messages. Use keyboard or click on the top and bottom of the message container in order to scroll. It is very difficult to scroll the page using keyboard or clicking on the top & bottom.

### Steps to reproduce:

1. Open Rocket.chat
2. Open Messages or thread
3. Try to see older messages 

### Expected behavior:

There should be a scroll bar in order to scroll the page.

### Actual behavior:

https://user-images.githubusercontent.com/81948346/216833090-8abd2d7c-ca34-49b0-99e0-829c7db8fdbc.mp4

### Server Setup Information:

Version of Rocket.Chat Server: 5.4.1

Operating System: windows 10(22H2)

Deployment Method: docker

Number of Running Instances: 1

DB Replicaset Oplog: donno

NodeJS Version: 19.4.0

MongoDB Version:6.0.3

### Client Setup Information

Desktop App or Browser Version:Microsoft Edge 108.0.1462.76 (Official build) (64-bit).
-Operating System: windows 10(22H2)

**Comment by notlelouch** [comment]
I can solve this issue, please assign this to me

**Comment by sande265** [comment]
claim
I would like to work on this issue.

**Comment by monishkajha17** [comment]
Can you please assign this issue to me, I would like to work on it

**Comment by SANGAAM** [comment]
overflow-y: scroll
this code will solve this issue
I will be grateful it if you  assign this issue to me

**Comment by sande265** [comment]
> overflow-y: scroll this code will solve this issue I will be grateful it if you assign this issue to me
overflow-y: auto; would do just fine. & it will eliminate unnecessary scroll behavior trigger.

**Comment by Tejasp2003** [comment]
I would like to work on this issue

**Comment by hugocostadev** [comment]
This cannot be reproduced in open.rocket.chat anymore  probably was fixed in our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) , if still happens, please, provide more info about your browser. Thanks
