### ISSUE TITLE
Finnish translations are advertising a specific company

### ISSUE THREAD

**Issue by Sigurs** [RocketChat/Rocket.Chat#27968]
### Description:

Finnish translations are advertising a specific company.

`"Powered_by_RocketChat": "Palvelun tarjoaa Elisa Videra",`
In English: "Service provided by Elisa Videra"

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json#L3777

### Expected behavior:

"Powered by RocketChat" which I think it's been before.
Everything  I can think of in Finnish just soudns bad.

### Actual behavior:

Lower left corner:
![image](https://user-images.githubusercontent.com/10909187/217351571-213f4fda-a3ac-427a-8b84-981895d34d76.png)

**Comment by rishavmehra** [comment]
I think there is should be [`"Powered_by_RocketChat": "Palvelun tarjoaa RocketChat"` ](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/packages/rocketchat-i18n/i18n/fi.i18n.json#L3776)- If I'm not wrong @Sigurs

**Comment by Sigurs** [comment]
Refers bit to a RocketChat being the service provider ("Service provided by RocketChat"), but still considerably better than company X @rishavmehra
