### ISSUE TITLE
Markdown Unordered list indentation

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#27971]
### Description:

Indentation in an unordered list is not displayed, the asterisk does not turn into a dot. I do the markup as indicated in the Markdown article.

### Steps to reproduce:

1. Write text:
```
* List item
    * Nested list item indented by 4 spaces
```

### Expected behavior:

There is an indent in an unordered list.

### Actual behavior:

There is no indent in an unordered list.
![image](https://user-images.githubusercontent.com/104189570/217539654-e9b2160a-063d-48e3-aa5d-695890fa11ce.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  5.4.2

### Client Setup Information

- Desktop App or Browser Version: Chrome 108

### Additional context

On the open.rocket.chat server, the problem is reproduced too.

**Comment by Ayush-singla27** [comment]
I would like to give this issue a go.

**Comment by hugocostadev** [comment]
duplicated of https://github.com/RocketChat/Rocket.Chat/issues/26738
