### ISSUE TITLE
Link parsed inconsistently between messages feed and threads

### ISSUE THREAD

**Issue by ThibautPlg** [RocketChat/Rocket.Chat#27973]
### Description:

A link/url containing a trailing dot (`.`) does not behave the same way in a general message and in a thread. 

### Steps to reproduce:

1. Post a link followed by a dot
2. Reply to create a thread
3. Witness two different links for the same message (Thread header and message)

### Expected behavior:
Links should be parsed the same way to display the same information and link to the same resource. 

### Actual behavior:

When posting a link followed by a dot, as in the end of a sentence, the dot is considered as being part of the link, leading to wrong resource. 
![2023-02-08_15-01](https://user-images.githubusercontent.com/17176051/217551266-4142d6cf-bf81-41ff-b425-4d2539876e50.png)

However, **inside** the thread, after clicking "Reply" the link is correct and does lead to the linked resource as expected.
![2023-02-08_14-58](https://user-images.githubusercontent.com/17176051/217550545-83fa5c03-c82c-4e89-8692-5dc2e4587674.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: Rocky
- Deployment Method: Docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Firefox 106 / Desktop 3.8.14
- Operating System: Debian

Thanks;

**Comment by ThibautPlg** [comment]
Might be the same thing as https://github.com/RocketChat/Rocket.Chat/issues/27890.

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of:  https://github.com/RocketChat/Rocket.Chat/issues/28314

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
