### ISSUE TITLE
flickering options when no space at bottom

### ISSUE THREAD

**Issue by durgesh077** [RocketChat/Rocket.Chat#27982]
### Description:

When there is one line of text written in general channel, and if More button is opened it flickers

### Steps to reproduce:

1-Go to general channel 
2- type a new text of 1 line 
3- send it
4- click on  menu button on the right

### Expected behavior:

It shouldn't flicker

### Actual behavior:
It flickers

**Comment by durgesh077** [comment]
I want myself to work on this issue. Please assign it to me

**Comment by hugocostadev** [comment]
It was already fixed by: https://github.com/RocketChat/fuselage/pull/967
