### ISSUE TITLE
Missing Labels and not working translation at Login Form

### ISSUE THREAD

**Issue by lowshoe** [RocketChat/Rocket.Chat#27984]
### Description:

The Login Form at our self-hosted Rocketchat instance does not show correct labels. Instead they are labelled with "**component.login**", "**component.form.emailOrUsername**", "**component.form.password**" "**component.login**" Furthermore, the Translation from English to German is not working. You can click an "**Switch to**en" (the space between to and 'de/en' is really missing.) After clicking, the only thing that changes is the Language switcher which is now "**Switch to**de". The Link to the registration form is shown though we disabled it in the Account Settings.

### Steps to reproduce:

1. Access Rocket.Chat login page as unauthorized user.

### Expected behavior:

1. Correct labels for form header, form fields, submit-button and validation messages instead of component.something
2. Working translation when switching language
3. Do not show link to registration form if disabled

### Actual behavior:

See screenshot for details:
![screenshot_rocktchat_login_form](https://user-images.githubusercontent.com/33627628/217825193-7d2c839b-67a4-48de-ac47-a9cd79215147.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.2
- Operating System: Oracle Linux 8
- Deployment Method: Podman
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: The error could be reproduced in the Electron app (3.8.16) as well as in different browsers (Firefox 109.0.1, Chromium 109.0.5414.119, Opera  95.0.4635.25), Adblocker disabled
- Operating System: Fedora Linux

### Additional context

The Issue is already present in 5.4.0

### Relevant logs:

No errors are present in logs.

**Comment by abhishek3434** [comment]
@lowshoe please can you assign me this issue

**Comment by lowshoe** [comment]
@abhishek3434 sorry, this must be done by a repository maintainer.

**Comment by sidhu-webgrid** [comment]
I am also facing the same issue, my version of rocket chat is 5.4.3, this was happening since my mongodb has been crashed due to unexpected shutdown

**Comment by Gua00va** [comment]
Hey, is this issue still open. I would like to work on it. Can you assign it to me?

**Comment by lowshoe** [comment]
Something new on this Problem? We are still facing this issue. Could one of the Repo-Maintainers please assign the issue to @abhishek3434 or @Gua00va ?

**Comment by dvnkln** [comment]
Same issue #27442
