### ISSUE TITLE
When typing an IP in the chat, it isn't clickable.

### ISSUE THREAD

**Issue by olafleur** [RocketChat/Rocket.Chat#2799]
When entering an IP address in the chat (for example : http://127.0.0.1/ ) the URL is not clickable like when you enter an URL like http://google.com .

Is that intended behaviour?

**Comment by AJ-Acevedo** [comment]
Confirmed on https://demo.rocket.chat

**Comment by olafleur** [comment]
It is because Rocket.Chat use the Autolinker library, which, for the moment cannot autolink IP addresses :
https://github.com/gregjacobs/Autolinker.js/issues/112

**Comment by bahmanjafari** [comment]
I have the same problem in 5.0.3

![Screenshot from 2022-09-06 10-03-19](https://user-images.githubusercontent.com/29546232/188554603-473ebd89-2b72-49f6-9eb2-1168818a450f.png)
