### ISSUE TITLE
Input label Text in the Workspace creating form is not clearly visible.

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#27999]
### Description:

Text in the Workspace creating form is not clearly visible.

### Steps to reproduce:

1. Create a new Workspace
2. see the input label

### Expected behavior:

It should clearly visible.

### Actual behavior:

<img width="462" alt="Screenshot 2023-02-12 172852 (2)" src="https://user-images.githubusercontent.com/81948346/218310583-bf265480-c54d-4534-acbb-4490714454ed.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0-develop
- Operating System: windows 10(22H2)
- Deployment Method: Gitpod
- Number of Running Instances: 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2
- MongoDB Version:5.0.5

### Client Setup Information

- Desktop App or Browser Version: Microsoft Edge 108.0.1462.76 (Official build) (64-bit).
- Operating System: windows 10(22H2)

**Comment by ShreyanshKeshav33** [comment]
I can work on this! Can I get assigned to it?

**Comment by DanielS01ss** [comment]
Hi!
I would love to work on this issue!

**Comment by Gua00va** [comment]
I would like to work on this issue.

**Comment by Tejasp2003** [comment]
I would like to grab this issue. Please assign this issue to me

**Comment by jihacshnu** [comment]
I would like to contribute to this
