### ISSUE TITLE
IFrame Auth logout

### ISSUE THREAD

**Issue by gsckoco** [RocketChat/Rocket.Chat#28006]
### Description:

When using IFrame auth, when the user logs in and then attempts to log out they get immediately logged back in

### Steps to reproduce:

1. Setup IFrame auth, using the example provided on the documentation site, using cookies hosted on the IFrame page
2. Log in using the IFrame auth.
3. Attempt to logout

### Expected behavior:

User doesn't get instantly logged back in. 

### Actual behavior:

User gets instantly logged back in after clicking log out.

https://user-images.githubusercontent.com/46426171/218430078-4532f131-c122-4934-a82c-b08daab4654a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Linux
- Deployment Method: Docker (WSL2)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 6.0.4

### Client Setup Information

- Browser Version: Chrome 109.0.5414.121 
- Operating System: Windows 10 Pro

### Additional context

I think a good solution to this would be to specify that the redirect to the login page is from a logout and have that passed into the IFrame through query params or through the IFrame postMessage method.

I do have a work around that instead of instantly logging the user in that after they log in on the IFrame it takes them to a second page that has a button to confirm that they want to log in, however this isn't ideal.

**Comment by SANGAAM** [comment]
Please assign this issue to me I will love to solve this issue

**Comment by guijun13** [comment]
It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. Thank you very much!

**Comment by gsckoco** [comment]
> It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. Thank you very much!

Do you know what version introduced the fix, is it pre 6.0?

**Comment by guijun13** [comment]
> > It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. Thank you very much!
> 
> Do you know what version introduced the fix, is it pre 6.0?

Hey @gsckoco. I tested on develop, I wasn't able to find if it was fixed before 6.0.
