### ISSUE TITLE
Send message via URL

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat#28008]
There is such a wish: to be able to send a message via URL.
This is how I see it: by clicking on a link like this https://open.rocket.chat/channel/general&text=Test%20message in the #general channel, the text "Test message" appears in the input field. All I have to do is send a message. Is this possible?

**Comment by SANGAAM** [comment]
can u please specify it more

**Comment by SANGAAM** [comment]
i got u Hey I will luv to work on this issue Can you assign me??

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

This is more suitable to create slash commands or create an app

To Request a Feature go to our Community Forum.

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by shaedrich** [comment]
This issue would also be interesting for links from outside RocketChat. Slash commands do not work for this and creating an app is significantly overkill
