### ISSUE TITLE
Can I download files in the File List window?

### ISSUE THREAD

**Issue by Laisky** [RocketChat/Rocket.Chat#2801]
Your Rocket.Chat version: 

  - server v0.25
  - client: v1.2.0 for OSX(same problem on Windows client v1.2)

Could I download files that displayed on the File List window?

When I click a image file, the image will display. But there is nothing happened when I click a non-media file such as pdf.

![rocket_chat_](https://cloud.githubusercontent.com/assets/4532436/14343805/dbee8f00-fcd5-11e5-9096-3812c1c36a0f.jpg)

**Comment by zxweed** [comment]
Why don't use the click on filename to download?

**Comment by Laisky** [comment]
@zxweed Click on the filename just display the image. and there is nothing happened when I click the non-medie file(such as .pdf or .rar).

**Comment by zxweed** [comment]
I have checked it now (version 0.25) - the pdf file was succesfully downloaded by click on the filename
