### ISSUE TITLE
Bug with dark theme in windows

### ISSUE THREAD

**Issue by Psychodrill** [RocketChat/Rocket.Chat#28010]
Are you seeing typed message in message block? No? But it typed! Dark font on dark background.
![Screenshot_102](https://user-images.githubusercontent.com/43932805/218457553-3cb00974-5239-4359-863b-02c8116a8155.png)

**Comment by dudanogueira** [comment]
Hi!

Can you replicate this on http://open.rocket.chat?

Please, provide all the necessary information required on. If you are using 5.X, bear in mind that his feature will only land in 6.0 versions and up.

I'll close it for now. Thanks!
