### ISSUE TITLE
@mention autocomplete when inside Private Groups should show members only

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2802]
Currently, the autocomplete shows and searches the entire universe of users.

**Comment by cbajohr** [comment]
That would be extremely useful.... it happens quiet often that you accidentally mention someone in a private channel, that is not on the channel and not allowed to see the message...

**Comment by soenkef** [comment]
+1 - good feature

**Comment by geekgonecrazy** [comment]
Probably a dupe of #2588

**Comment by mickeyclausen** [comment]
+1

**Comment by marceloschmidt** [comment]
Duplicate of #2588
