### ISSUE TITLE
x86_64 dependency error on Apple M1

### ISSUE THREAD

**Issue by dmitri-vlasov** [RocketChat/Rocket.Chat#28023]
### Description:

Seems like one of the dependencies is for Apple M1 arm architecture still rely on x86_64 architecture cause `yarn dev` command  on MacOS Apple Silicon produces an error: `missing tool for os.osx.x86_64 in meteor-tool@2.7.3`

### Steps to reproduce:

Installing according official doc: https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx with one addition - it requires also `yarn install` command to run.

### Expected behavior:

Rocket.Chat should run after a command `yarn dev`

### Actual behavior:

<img width="965" alt="Снимок экрана 2023-02-14 в 01 01 10" src="https://user-images.githubusercontent.com/8647677/218576820-2efe8cdb-083b-41e7-87cc-66ae8802da99.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.2
- Operating System: macOS Monterey 12.6
- Deployment Method: source code
- Number of Running Instances: -
- DB Replicaset Oplog: -
- NodeJS Version: v14.19.3
- MongoDB Version: - 

### Relevant logs:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node',
1 verbose cli   '/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.21.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @rocket.chat/meteor@5.4.2~predev: @rocket.chat/meteor@5.4.2
6 info lifecycle @rocket.chat/meteor@5.4.2~dev: @rocket.chat/meteor@5.4.2
7 verbose lifecycle @rocket.chat/meteor@5.4.2~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @rocket.chat/meteor@5.4.2~dev: PATH: /Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dmitry/Documents/Coding/uab_icona/Rocket.Chat/apps/meteor/node_modules/.bin:/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin:/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64:/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/.bin:/private/var/folders/ln/k9rfqvts0bb_2hjg8036lnn40000gn/T/xfs-3d76de4e:/private/var/folders/ln/k9rfqvts0bb_2hjg8036lnn40000gn/T/xfs-2d08f07a:/Users/dmitry/bin:/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dmitry/Library/Python/3.6/bin:/Users/dmitry/Library/Python/2.7/bin:/Library/Apple/usr/bin:/usr/local/node-v14.19.3-darwin-x64/bin:/Users/dmitry/Library/Android/sdk/platform-tools:/Users/dmitry/Library/Android/sdk/emulator
9 verbose lifecycle @rocket.chat/meteor@5.4.2~dev: CWD: /Users/dmitry/Documents/Coding/uab_icona/Rocket.Chat/apps/meteor
10 silly lifecycle @rocket.chat/meteor@5.4.2~dev: Args: [ '-c', 'meteor --exclude-archs "web.browser.legacy, web.cordova"' ]
11 silly lifecycle @rocket.chat/meteor@5.4.2~dev: Returned: code: 1  signal: null
12 info lifecycle @rocket.chat/meteor@5.4.2~dev: Failed to exec dev script
13 verbose stack Error: @rocket.chat/meteor@5.4.2 dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid @rocket.chat/meteor@5.4.2
15 verbose cwd /Users/dmitry/Documents/Coding/uab_icona/Rocket.Chat/apps/meteor
16 verbose Darwin 21.6.0
17 verbose argv "/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node" "/Users/dmitry/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/npm" "run" "dev"
18 verbose node v14.21.2
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 1
22 error @rocket.chat/meteor@5.4.2 dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"`
22 error Exit status 1
23 error Failed at the @rocket.chat/meteor@5.4.2 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aj-2000** [comment]
Although I was unable to run my Meteor app using the steps mentioned in the documentation, I was able to get it running by following these steps:

Navigate to the directory where your Meteor app is located using the cd command,
`cd apps/meteor`
Run the meteor command to install all the required dependencies for your app and start it,
`meteor`
If the meteor command is still not working, you can try running meteor reset first to reset your app's local database and cache
`meteor reset`
By following these steps, you should be able to successfully run your Meteor app.

**Comment by Legend101Zz** [comment]
@dmitri-vlasov  
I had the same issue while setting up RC on my system and I tried this:- 

- I Install the most recent Meteor version https://www.meteor.com/developers/install (I had an older version installed )
- I used Pyenv and had version 3 set up globally. So I had to `pyenv install 2.7` then `pyenv local 2.7` to set Python 2 in the current directory ( as some packages use python to run their script and I came to know that python2 is not preinstalled in latest MacOS
[[news source](https://developer.apple.com/documentation/macos-release-notes/macos-catalina-10_15-release-notes)].So  I guess it is the root cause.
- Then try running the app using a rosetta terminal as mentioned in the docs https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/mac-osx
- Then go to apps/meteor and then  `meteor reset`,then go to the main directory and remove node_modules (if installed) and then again run `yarn ` and then` yarn dev`
