### ISSUE TITLE
Livechat different messages for differents departments

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#28068]
### Description:

We use the livechat/ominchannel feature. 
It is currently integrated into a website for a department. That works wonderfully.
But now other departments also want to use the live chat. For this, however, it is necessary for them to be able to use different texts (notification of absence and welcome message) as well as business hours. Unfortunately I can't find a way to set this for different departments.

Is that possible? A variant would be e.g. to set it via the script to be integrated for the website. I've already tried that, but it's being ignored.

### Steps to reproduce:

1.  Omnichannel
2. Live Chat appearance
3. 

### Expected behavior:

Configure different messages and times per department

### Actual behavior:

Only one Configuration is possible 

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.0
- Operating System: Ubuntu 22.04
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.17

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi! This is possible.

You will need to register the vistor and pass the department while doing so. here is the piece of code you will need:

https://developer.rocket.chat/reference/api/livechat-api#register-visitor

Also, please, issues are reserved to softwares problems. our Forums is a better place for this kind of questions :)
here is a great guide on how to use our community resources:
https://docs.rocket.chat/getting-support/community-resources

I'll close it for now but feel free open a forum thread if you need further assistance.

Thanks!
