### ISSUE TITLE
S3 CDN Domain for Downloads not working

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#28070]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by lovekyleman** [comment]
CDN domain for downloads is ignored 
It's using Bucket URL for downloads 

Rocket.chat version: 5.4.3

OS : Debian 11

**Comment by doktormd5** [comment]
FileUpload_S3_CDN is not used
https://github.com/RocketChat/Rocket.Chat/blob/9520d90763a9434ac1605cc13cae9fdc0e5c857a/apps/meteor/app/file-upload/server/config/AmazonS3.ts#L73

**Comment by lovekyleman** [comment]
> FileUpload_S3_CDN is not used
> 
> https://github.com/RocketChat/Rocket.Chat/blob/9520d90763a9434ac1605cc13cae9fdc0e5c857a/apps/meteor/app/file-upload/server/config/AmazonS3.ts#L73
Unbelievable

**Comment by lovekyleman** [comment]
> It's been unused for 6 years!
> 
> 
> 
> ```
> 
> commit a8519bafb9cf84cd7fc9887f1459a6d52d90d083
> 
> Author: Rodrigo Nascimento <rodrigoknascimento@gmail.com>
> 
> Date:   Thu May 25 17:18:00 2017 -0300
> 
> 
> 
>     Remove use of slingshot from client
> 
> 
> 
> ...
> 
> -       const cdn = RocketChat.settings.get('FileUpload_S3_CDN');
> 
> ...
> 
> +       // const CDN = RocketChat.settings.get('FileUpload_S3_CDN');
> 
> ```

Just don't know Why cancel file upload s3 CDN. It's good for uploading
