### ISSUE TITLE
Private Group Owner Cannot Rename Group

### ISSUE THREAD

**Issue by ChanningMorris** [RocketChat/Rocket.Chat#2807]
Your Rocket.Chat version: 0.25 (Docker Version)

We've stood up the Docker version of Rocket.Chat locally and are testing it with about 50 users.  One user made a private group for his team, but cannot rename the group.  He gets the red error bar that says "Not Allowed".

I was able to join the private group via invite and change it (I have admin privileges) as well as verify that he has owner and moderator privileges.  He also logged out/logged in and is still unable.

Wanted to make sure I'm not missing something obvious as to why he wouldn't be able to rename or expose a bug.

**Comment by geekgonecrazy** [comment]
Can you verify if he wasn't naming to the same name as any other group or channel?  Or that it didn't include any special characters?  I think the error on this isn't super clear.  So just want to make sure its not it being unclear and it was a valid new name.

**Comment by ChanningMorris** [comment]
I was able to change the room to what he wanted it named, so I'm pretty sure it wasn't an invalid name or duplicate room name.

I have been able to recreate the problem though.  I created a test user on our instance this morning, created a private group, and I'm unable to change the name.  I named the room "testgroup" on creation and have tried editing it to "testgroupedit" and "asdf1234" - both return "Not Allowed" for my new user and are not existing channel names according to the list under the admin panel.

My admin login was able to change the name of the group to "testgroupedit" and back without issue.  Also tried removing the test user's privileges and readding them (and reloading the page afterwards), but he's completely unable to rename the group.  Seems to be the same case with public rooms as well.

**Comment by ChanningMorris** [comment]
Just a few more data points from my testing this morning: 

Enabling room editing for all users allows the test user to make the change that's throwing an error despite having owner and moderator permissions.  

Removing the ability for owners and moderators to edit the channel removes the pencil button that brings up the edit box, which is expected.  Adding them back restores the pencil, but non-admin owner/moderator users get "Not Allowed" for any edit attempts unless I allow all users to edit.

**Comment by bgomelsky** [comment]
I think the issue is on this line https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-channel-settings/client/views/channelSettings.coffee#L65 
The if statement 
`if not RocketChat.authz.hasAllPermission('edit-room', @rid) or room.t not in ['c', 'p']` should use `rid` instead of `@rid`

**Comment by SimonSarazin** [comment]
We have exactly the same issue on the rocket.chat we installed for the nuitdebout mouvement in France (http://chat.nuitdebout.fr)

**Comment by ChanningMorris** [comment]
Upgraded our install to 0.26 last night and the issue is still present.

**Comment by mccambridge** [comment]
Just discovered that `RocketChat.authz.hasRole(Meteor.userId(), 'owner', Session.get('openedRoom'))` evaluates to `false` in private groups for the owner, whereas it's confirmed `true` in public groups. I'm going to file a separate bug for this, but I wonder if it's related to buggy permissions with this issue.

**Comment by toupeira** [comment]
I ran into the same issue on channels, the channel owner (normal user) can't rename it and gets a "Not allowed" error, while the admin can edit it just fine.
