### ISSUE TITLE
Jitsi Meet intergration: Camera is "disabled" by default - How can I change the default setting to "enabled" ?

### ISSUE THREAD

**Issue by moell9** [RocketChat/Rocket.Chat#28089]
Just a quick question:
Jitsi Meet intergration: Camera is "disabled" by default - How can I change the default setting to "enabled" ?

**Comment by SANGAAM** [comment]
setting->Device tab->Default Camera Option Click on the dropdown menu next to this option.->then select the camera u want and then save

i hope it wil help u

**Comment by moell9** [comment]
Sorry, but I don't know which setting you mean. Perhaps a screenshot helps.
![Camera disabled](https://user-images.githubusercontent.com/14744719/219675079-3f32225f-78fd-47f0-922c-a68d8e56c22e.JPG)
I'm speaking on this camera setting in Rocket.Chat. This is disabled by default.

**Comment by moell9** [comment]
Nobody else any answer ?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
