### ISSUE TITLE
Comment on a file upload

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#2809]
Your Rocket.Chat version: 0.25.0

**[Feature Request]**
Currently when you upload some type of file it automatically inserts into the thread without being able to comment directly on the post.  I have to edit the file upload post to attach a comment to it.  it'd be nice if on a file upload there was a field to add a comment directly.

**Comment by geekgonecrazy** [comment]
I agree.  This would be nice, instead of having to do something like ^^ What do you think?

I've done that and had someone send a message before I was complete, kinda throws things off a bit

**Comment by twhiting** [comment]
Currently the upload field looks like this

<img width="501" alt="screen shot 2016-04-08 at 12 06 58 am" src="https://cloud.githubusercontent.com/assets/10718586/14375363/e8ecc314-fd1d-11e5-96b0-cc3d20650ea4.png">

Adding a textbox above / below the image where we could add a message in would be great.  Ideally Github handles this **very** well.  It allows you to upload a file and continue writing the comments formatting your post however you'd like.  This would be awesome on rocket.chat.

<img width="708" alt="screen shot 2016-04-08 at 12 09 39 am" src="https://cloud.githubusercontent.com/assets/10718586/14375395/39fbca52-fd1e-11e5-9d38-30653b7bbc4e.png">

**Comment by twhiting** [comment]
So overall mashing github's file upload / commenting style on rocket.chat, it'd look something like this:

<img width="1378" alt="screen shot 2016-04-08 at 12 16 39 am" src="https://cloud.githubusercontent.com/assets/10718586/14375542/5425ead8-fd1f-11e5-91b0-a4939e5fd3de.png">

Hope that makes sense.

**Comment by geekgonecrazy** [comment]
Hm...  How about this.

If you are typing a message and you paste or attach an image.  It would go inline like you have illustrated above.

If you just click attach and don't have a message you'd be able to type a message to send along with the image or file?

**Comment by twhiting** [comment]
Sounds great to me, this would help people like me that sometimes are writing long technical posts that ideally should all be one post instead of a bunch of posts split up by file uploads and images.

**Comment by MartinSchoeler** [comment]
This feature has been already implemented today
