### ISSUE TITLE
pinned comments redirects to a new tab

### ISSUE THREAD

**Issue by samarth8765** [RocketChat/Rocket.Chat#28101]
Description:
When I click on "pinned messages" it redirects to a new tab instead it should display pinned messages in the same tab for a better user experience.

**Comment by Preetam078** [comment]
hey @samarth8765 can you please assign this task to me

**Comment by Preetam078** [comment]
please assign this task to me, I think i can resolve this

**Comment by dudanogueira** [comment]
Please, provide all the requried informations from the template, like version, etc, steps to reproduce, etc.

Thanks!
