### ISSUE TITLE
Reactions don't follow UI_Use_Real_Name

### ISSUE THREAD

**Issue by gsckoco** [RocketChat/Rocket.Chat#28104]
### Description:

When the `Use Real Name` option is set to true, reactions to messages do not use the user's real name.
![image](https://user-images.githubusercontent.com/46426171/220124415-dc13e26f-bdb3-4904-aec2-7e017fa6c1a1.png)

### Steps to reproduce:

1. Enable Use Real Names
2. React to a message from another account
3. Username shows up instead of the Full Name value

### Expected behavior:

I expect when use real name is true, that reactions use the real name instead of the username

### Actual behavior:

Uses usernames instead of real names

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.3
- Operating System: Ubuntu Server 22.04
- Deployment Method: [Manual Installation](https://docs.rocket.chat/deploy/prepare-for-your-deployment/other-deployment-methods/manual-installation/debian-based-distros/ubuntu)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 110.0.5481.97 
- Operating System: Windows 10 Pro

### Additional context
I have tried to implement this functionality myself, but to no avail, I am unsure on how to get the full name field from the user from their Username

**Comment by gsckoco** [comment]
For what its worth I think I managed to get it work pretty well.

MessageReactionsList.tsx
```js
<MessageReaction
        key={name}
        counter={reactions.usernames.length}
        hasReacted={hasReacted}
        reactToMessage={reactToMessage}
        name={name}
        names={reactions.names ? reactions.names.map((displayName, index) => {
                const thisUser = Meteor.user()?.username
                const username = reactions.usernames[index];
                return username == thisUser ? null : (displayName ? displayName : username)
        }).filter(v => v !== null ) : reactions.usernames}
/>
```

I removed the use of useReactionsFilter as I didn't fully understand what it was doing, and when trying to implement the above function into that hook it didn't seem to have any effect (Could have something to do with the change detection in the dev environment).
![image](https://user-images.githubusercontent.com/46426171/220209779-bce90523-bd54-4d00-840e-36585db4b09e.png)

**Comment by tamasgal** [comment]
@gsckoco which RocketChat version did you hack? In my `MessageReactionsList.tsx` (I found two of them) I only see some obfuscated JavaScript lines.

```
root@cd3ae10c7ee3:/app/bundle# cat ./programs/web.browser/dynamic/client/views/room/MessageList/components/MessageReactionsList.tsx
function module(e,t,s){let a,n,c,o,i,l,r,u;s.link("@rocket.chat/fuselage",{MessageReactions(e){a=e},MessageReactionAction(e){n=e}},0),s.link("react",{default(e){c=e}},1),s.link("../contexts/MessageListContext",{useOpenEmojiPicker(e){o=e},useReactionsFilter(e){i=e},useReactToMessage(e){l=e},useUserHasReacted(e){r=e}},2),s.link("./MessageReaction",{MessageReaction(e){u=e}},3);const g=e=>{let{message:t}=e;const s=r(t),g=l(t),m=i(t),k=o(t);return c.createElement(a,null,t.reactions&&Object.entries(t.reactions).map((e=>{let[t,a]=e;return c.createElement(u,{key:t,counter:a.usernames.length,hasReacted:s,reactToMessage:g,name:t,names:m(t)})})),c.createElement(n,{onClick:k}))};s.exportDefault(g)}
```
