### ISSUE TITLE
sockjs and _timesync cannot be run from subdirectory

### ISSUE THREAD

**Issue by klimkowd** [RocketChat/Rocket.Chat#2810]
Currently running version RocketChat 0.25 and trying to get it to run out of a subdirectory.  All the assets load correctly but calls to sockjs and _timesync are still making requests to the root domain.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
