### ISSUE TITLE
Questions to Jitsi Conference Calls Provider

### ISSUE THREAD

**Issue by moell9** [RocketChat/Rocket.Chat#28109]
When is a video call ended ? When all participants hang up ? Does the status of the video call change ?
For us it looks like this after a video call:
All participants hang up. However, the video call is still actively visible afterwards. How can this be ended correctly ?
![Call ongoing](https://user-images.githubusercontent.com/14744719/220332307-889a664c-4c4d-4e10-80ed-11c87433ee9d.JPG)
It would be expected that the video call is terminated and the status changes.
![Call ended](https://user-images.githubusercontent.com/14744719/220332369-2e3750ef-84be-4fba-945a-102697256a29.JPG)
Is this a bug or something I can change in the settings ?

**Comment by moell9** [comment]
The developer of the Jitsi App told me the following:
The Jitsi app doesn't detect when the call has ended. Rocket.Chat will flag the calls as ended after a 24 hours timeout.

My question now: Is it possible to edit the flag? For us, for example, 2 hours would be quite enough.

**Comment by hugocostadev** [comment]
closing since the discussing is taking place in the correct repo: https://github.com/RocketChat/Apps.Jitsi/issues/25
