### ISSUE TITLE
Unfinished private chat content persists in another private chat

### ISSUE THREAD

**Issue by honey-grapes** [RocketChat/Rocket.Chat#28112]
### Description:

Not sure if this is a bug but when I entered something in one private chat box, it persists into another private chat box as shown in the video below.

https://user-images.githubusercontent.com/66938562/220501313-973c5c0e-d06b-4799-908a-fd5fa5e0b7a8.mov

### Steps to reproduce:

1.  Go to a private chat on the web app, type something
2.  Go to another private chat then you'll see the message that you intend to send to first person persisting in the second private chat

### Expected behavior:

Unfinished content from one private chat should not go into another private chat

### Actual behavior:

Unfinished content from one private chat goes into another private chat

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: macOS

**Comment by XshubhamX** [comment]
@honey-grapes  Thank you for identifying the problem.

**Potential reason**
It appears that when we go between conversations, the state is not updated or reset.

**Solution**
Examine the necessary module to see if the state is being reset.

Should I continue to work on this? @ggazzo @sampaiodiego

**Comment by honey-grapes** [comment]
> @honey-grapes Thank you for identifying the problem. Can you please also specify the version?
> 
> **Potential reason** It appears that when we go between conversations, the state is not updated or reset.
> 
> **Solution** Examine the necessary module to see if the state is being reset.
> 
> Should I continue to work on this? @ggazzo @sampaiodiego

Hi Shubham, I can take a look as well! Is it fine if I take a stab at this?

**Comment by XshubhamX** [comment]
@honey-grapes yup go ahead.
I believe that this issue will lead to a feature where we have to store draft messages of every chat in state.

**Approach**
When switching between conversations, the appropriate draft message should be selected from the state and handed on to the component. The state should include a hash map that stores the username as the key and the draft message as the value.

Something like this

`
const draft_hash = {
    "user1": "Hi",
    "user2": "Nice!"
}
`

**Comment by dudanogueira** [comment]
I was not able to reproduce it on chrome using latest 6.0 on open.rocket.chat (in rc1 now)

Using chrome on Linux :grimacing:

**Comment by dudanogueira** [comment]
Maybe is this a mac only thing?

**Comment by XshubhamX** [comment]
@dudanogueira Its a weird issue, I tried to replicate it and this happens. Its happening because the localstorage keys are not being updated correctly. So in the below video you'll notice that -

1. I wrote Hi in the first chat box, and the drafted chat was allocated a new key in the local storage with the value as "HI".
2. Performed the same thing in the second chat box and then a new key was added with the key as "Hello".
3. Now that I've tried switching between conversations sequentially, both chat boxes are displaying the same value because at one point both keys had the same value.

https://user-images.githubusercontent.com/63532716/221235821-1aefc0ff-57d7-487e-bbf7-48755f7ef766.mov

**Comment by dudanogueira** [comment]
Ah... Ok. I might have tested it differently.

I'll try it that way. Thanks!

Do you think you can produce a PR for it?

**Comment by XshubhamX** [comment]
Yep I can!

**Comment by Pheewww** [comment]
hey @dudanogueira can i also work on it?

**Comment by Gummikavalier** [comment]
I was able to replicate this issue on open.rocket.chat too.

**Comment by Dr-Shadow** [comment]
We have this issue on our self managed Rocket Chat instance as well.

Version : 6.1.1

Client version : Rocket Chat Electron 3.9.1

**Comment by jdsatava127** [comment]
We are experiencing the same issue after an upgrade to 6.x.
Server Setup Information:
Version of Rocket.Chat Server: 6.1.5
Operating System: CentOS 7
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog: Yes
NodeJS Version: 14.21.2
MongoDB Version: 5.0.15
Client Setup Information
Desktop App or Browser Version: App 3.9.1 and Google Chrome 112.0.5615.121
Operating System: Windows 10

**Comment by dkatheininger** [comment]
Same here.
We are experiencing the same issue after an upgrade to 6.x.

Server Setup Information:
Version of Rocket.Chat Server: 6.1.x and onwards (currently 6.2.2)
Operating System: Debian 11 (bullsey)
Deployment Method: docker

Client Setup Information
Browser Version: Google Chrome 112+, Firefox 112+
Operating System: Windows 10/11 and macOS 12.6/13.4
