### ISSUE TITLE
[UI FEATURE]: Try adding a dark mode in the website

### ISSUE THREAD

**Issue by money8203** [RocketChat/Rocket.Chat#28119]
### Description:

It should be great to have a dark mode option in the website

### Steps to reproduce:

Integrate one

### Expected behavior:

Dark Mode will make website look more amazing

**Comment by XshubhamX** [comment]
@money8203 What website are you referencing, If you're talking about Rocket Chat's online client, it already exists, or you are referring to the official website.

**Comment by money8203** [comment]
The main website

**Comment by dudanogueira** [comment]
Thanks for the suggestion! 

I will relay this to our web devs!
