### ISSUE TITLE
can Rocketchat accommodate deployments of up to 500000 users, up to 250000 concurrently active users?

### ISSUE THREAD

**Issue by seconp** [RocketChat/Rocket.Chat#28114]
I want to use the IM in my city to sale sonething. can Rocketchat accommodate deployments of up to 500000 users, up to 250000 concurrently active users? how to deploy the instance?

**Comment by Gummikavalier** [comment]
You should probably ask their sales about it. There are not many that big RC instances, particularly with concurrent active users. I think only the developers and their sales know what size the biggest instances in the world are.

AFAIK open.rocket.chat had its userbase at over 150 000 - 300 000 users couple of years back and not that many were online at the same time.

Recently with RC 5.x and RC 6.x development they have been moving away from monolithic structure with application nodes to micro services that scale better.

However, Rocket.Chat as most of the systems rely heavily on its database, and database is much harder to scale horizontally if you don't design for it from the beginning this in mind.

**Comment by dudanogueira** [comment]
Hi @seconp!

For sure, for a deployment that big, you will need the Enterprise license.

Let me know how we can help you. my email is duda.nogueira@rocket.chat and you can reach me at
https://open.rocket.chat/direct/duda.nogueira

Also, this kind of inquiring can be done in a better place, like our forums or support channel.

Here you have a guide on how to better take advantage on our Community Resources:
https://docs.rocket.chat/getting-support/community-resources

I'll close here for now, but feel free to keep the discussion going!

Thanks!
