### ISSUE TITLE
No global search message option for users in RC 6.0

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#28118]
### Description:

The global message search tick box is missing for users in RC 6.0 rc.0. The search results are local to channel.

### Steps to reproduce:

1. Go to Admin -> Settings -> Search -> Default provider -> Global search and set it on
2. Go to any channel and search for messages

### Expected behavior:

Users should be able to mark their search as global.

### Actual behavior:

The global search tick box is missing. The search results are local to selected channel only.

![Screenshot from 2023-02-22 17-14-23](https://user-images.githubusercontent.com/6958942/220667673-eb201ffa-57f8-490c-bd06-82345116ce41.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0 rc.0
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.2
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Any browser

### Additional context

Global search was still working on RC 5.4.3

**Comment by Gummikavalier** [comment]
Thinkin ahead a bit... Is this a regression, or is it because global search as itself is not compatible with the idea of distributed micro services and several databases?

**Comment by dudanogueira** [comment]
I believe the checkbox will not be available if you enable the globalsearch.

This line is not receiving true for the variable globalsearch:
https://github.com/RocketChat/Rocket.Chat/blob/b2b866571fc15f65113c5e05e52668eaa348c55d/apps/meteor/client/views/room/contextualBar/MessageSearchTab/hooks/useMessageSearchQuery.ts#L27

I will let our team know about it.

Thanks!

**Comment by Gummikavalier** [comment]
Thanks! :+1:

**Comment by Gummikavalier** [comment]
Fixed in RC 6.0 final. Closing.
