### ISSUE TITLE
Implementation of the loader component while searching.

### ISSUE THREAD

**Issue by XshubhamX** [RocketChat/Rocket.Chat#28124]
Description:
It might be rather misleading for the end user if a global search is taking a long time to gather users because the screen doesn't display any progress or a loading bar while the search is being conducted (for a user). The video below will explain this much better.

https://user-images.githubusercontent.com/63532716/220742196-1c4183e5-a700-4e83-8f46-beaee15fd59f.mov

Steps to reproduce:

- Go to the search bar and search for any user.

Expected behaviour:

- Loading component should be shown in place of static list of users.

Actual behavior:

- The screen doesn't show any progress or loading bar

Client Setup Information

- Desktop App or Browser Version: Chrome

- Operating System: macOS

- Version - 5.4.3

Should I work on this @sampaiodiego @dudanogueira

**Comment by dudanogueira** [comment]
Hi @XshubhamX! This indeed would be a great improvement!

if you are up for the challenge, I recommend you working on a mock up as a proposal, and then we can ask our ux team on further guidance on how to better implement this.

Maybe adding a spinner right next to the X button while the request is being made.

WDYT?

**Comment by XshubhamX** [comment]
@dudanogueira Indeed, a snipper that, let's say, rotates till data is received and then vanishes. As a proposal, I'll do a figma or a graphic.

**Comment by dudanogueira** [comment]
@XshubhamX I checked with our team and this is in our roadmap already :grimacing: 

I'll keep the issue open for reference. THanks!
