### ISSUE TITLE
Inbox style push notifications

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#2812]
Currently the newest push notification overrides the last push notification.

On iOS I don't believe you have much choice in the matter.  But on Android we have a couple of different types of notifications to allow stacking of notifications.
### Threading

You would increment an id every message and it would let you show multiple messages.  This would do for single threaded conversations. 

Just listing to say hey we do have options :smile:
### Inbox Style

This is the style I propose.
It groups messages by the title

Looking something like this:
![](https://cloud.githubusercontent.com/assets/353180/9468727/2d658bee-4b11-11e5-90fa-248d54c8f3f6.png)

We would have the contents like:
Title: server / channel
Body: Message contents
Style: 'inbox'

Because the Title would be the same for multiple messages in a thread... and we have style: inbox.  Android will auto group the messages.

Some info on sending: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#inbox-stacking

For any Android user this is likely what they are used to.

I've opened a ticket over at raix:push to allow this: https://github.com/raix/push/issues/196

**Comment by geekgonecrazy** [comment]
The pull request to allow this on the raix/push end was merged  :) https://github.com/raix/push/pull/224

**Comment by hughlroberts** [comment]
My users are also requesting this feature. Would be very helpful for project management when there's often many threads.
