### ISSUE TITLE
Drag scrollbar by mouse only does not disable the autoscroll mode

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2813]
Your Rocket.Chat version: 0.25

If I read history and new message arrived - the chat was scrolled down to the new messages. How can I disable this mode?

**Comment by engelgabriel** [comment]
Autoscroll is turn off when you scroll up, and the flag appears to alert about new messages.

![image](https://cloud.githubusercontent.com/assets/1000217/14392129/509b8540-fd96-11e5-9c49-46f2b7b3be08.png)

**Comment by zxweed** [comment]
This mode does not work always. For example, I read the history very far away from current line and I me constantly throws back on every new message

**Comment by engelgabriel** [comment]
do you see any errors on the console log?

**Comment by zxweed** [comment]
No any message in console, browser - Firefox for Windows, version 45

**Comment by zxweed** [comment]
The problem was reproduced if I scroll history via drag scrollbar by mouse only, not by the keyboard or mouse wheel.

**Comment by lvh1** [comment]
The same happens when scrolling up by clicking your mouse wheel and dragging down. Each time more messages are loaded, it scrolls back to the bottom.

**Comment by MartinSchoeler** [comment]
Hey @zxweed , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
