### ISSUE TITLE
Make the mention by click on username

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2814]
Your Rocket.Chat version: 0.27

It would be useful to paste the mention into message bar by mouse click on the username (may be with ctrl/alt modifier)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
