### ISSUE TITLE
[6.0.0-rc0-2] Firefox private mode does not work

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#28144]
### Description:

No able to open rocket chat with FF in private mode.
I'm able to login but only receive the spinning wheel.
No issue in normal mode and other browser in private mode e.g Chromium or so. 

### Steps to reproduce:

1. open FF in private mode
2. Login to rocket Chat

### Expected behavior:

Reaching the normal rocket chat page after login.

### Actual behavior:

Gray screen with the spinning wheel

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0 rc2
- Operating System: Rocky Linux 8
- Deployment Method: tar
- Number of Running Instances:  3
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: FF 110
- Operating System: Fedora 37

**Comment by sandeep13122002** [comment]
can any one suggest me how to start contributing ?

**Comment by Pheewww** [comment]
Maybe the issue is related to OS since it's working in my FF(private) in win 10

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest releases
---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by TimmiORG** [comment]
Finally got fixed by https://github.com/RocketChat/Rocket.Chat/pull/29545 in 6.2.6
