### ISSUE TITLE
Scroll in a Thread doesn't work to the top of the message 

### ISSUE THREAD

**Issue by paolapalhais** [RocketChat/Rocket.Chat#28150]
### Description:

Link of the link at loom with what's going on - https://www.loom.com/share/003223aac77742a78aa68e3122be6e73 

### Steps to reproduce:

1.   a Thread
2.  Open  - Read
3.   Try to scroll up 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi Paola!

I was not able to reproduce this on a Linux using latest Chrome.

Can you provide the OS and browser version you are running?

Also, can you reproduce this using the latest Desktop App? Or can you reproduce this using a different browser?

Thanks!

**Comment by dudanogueira** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/28298
