### ISSUE TITLE
Open channel description links in a new tab

### ISSUE THREAD

**Issue by ecke101** [RocketChat/Rocket.Chat#28167]
### Description:

In Rocketchat most links open in a new tab by default which makes sense.
The exception is channel description links.
This is an example from the blender.chat python channel. All these links open in the same tab:
![bild](https://user-images.githubusercontent.com/249736/221298650-64484246-6572-48dd-8e05-d430d364d13f.png)

### Steps to reproduce:

1. Go to a channel with a link in the description.
2. Click the link with the left mouse button.
3. Compare the behaviour with clicking on the link with the middle mouse button.

### Expected behaviour

All links should open in a new tab by default. That is they should have `target="_blank"`.

**Comment by sufiiyan** [comment]
hello @ecke101  assign me this issue, i might solve it.

**Comment by ecke101** [comment]
> hello @ecke101 assign me this issue, i might solve it.

Hello. I don't think I have the rights to do that.

**Comment by TafreedAhmad** [comment]
How to claim this? Anyone?

**Comment by Tejasp2003** [comment]
hey, I want to work on this issue. Please assign me

**Comment by Tejasp2003** [comment]
> ### Description:
> In Rocketchat most links open in a new tab by default which makes sense. The exception is channel description links. This is an example from the blender.chat python channel. All these links open in the same tab: ![bild](https://user-images.githubusercontent.com/249736/221298650-64484246-6572-48dd-8e05-d430d364d13f.png)
> 
> ### Steps to reproduce:
> 1. Go to a channel with a link in the description.
> 2. Click the link with the left mouse button.
> 3. Compare the behaviour with clicking on the link with the middle mouse button.
> 
> ### Expected behavior
> All links should open in a new tab by default. That is they should have `target="_blank"`.

It's opening in a new tab only. Can you elaborate more on the issue or provide any video of the issue?

**Comment by yash-rajpal** [comment]
Hey @ecke101! This works fine on the new 6.0.0 release. Can you please provide your server version on which it doesn't work? Thanks!

**Comment by dudanogueira** [comment]
This is fixed in 6.0.0 
I believe by this PR https://github.com/RocketChat/Rocket.Chat/pull/27554

Closing for now. Thanks for reporting!

**Comment by thw0rted** [comment]
There's a small issue with this fix.  If your channel description links to another channel on the same server, as a user I would expect it to open in the current window.  With this implementation, it opens a new tab, so now I have two RocketChat tabs going on the same server.

I made a suggestion on #6595 that channel references (`#otherchannel`) should be linkified automatically, but unless/until that gets implemented it isn't possible to create a channel link in the description that doesn't open a second chat tab.

Would it make sense to add an exception so that links to the current server aren't forced into a new tab?

**Comment by ecke101** [comment]
This is slightly off topic but I also noticed that clicking the "Download" button next to an image or video still opens it in the same tab.

![bild](https://user-images.githubusercontent.com/249736/233675272-b5c12d4e-64a4-4e70-a1dc-eb8b6ee02503.png)

**Comment by aurisnoctis** [comment]
I think this was reverting the fix of https://github.com/RocketChat/Rocket.Chat/issues/27491

See [my comment](https://github.com/RocketChat/Rocket.Chat/issues/27491#issuecomment-1842847119) and @Gummikavalier 's comment below mine
> Yes, the state of the issue seems to fluctuate. I think it broke again in RC 6.x.
