### ISSUE TITLE
Meteor Error while setting up the repository for development 

### ISSUE THREAD

**Issue by SohamRatnaparkhi** [RocketChat/Rocket.Chat#28179]
### Description:
While setting up this repository, after cloning the repository and installing all the dependencies, I am getting an error after running the `yarn dsv` command.
The error is - ` command finished with error: command (apps/meteor) yarn run dsv exited (254)
command (apps/meteor) yarn run dsv exited (254)`

I have followed all the steps mentioned in the `README.md` file. 
Here's the screenshot showing the particular error.
![image](https://user-images.githubusercontent.com/92905626/221421824-0a801d73-59bf-43d5-8661-4053e95b2fe9.png)

### Steps to reproduce:

1. git clone https://github.com/RocketChat/Rocket.Chat 
2.  npm install -g meteor 
3. Installing yarn
4. `yarn`
5. `yarn dsv`

### Expected behavior:
According to README, it is expected that a server should start locally at port `3000`

### Actual behavior:
Due to an error, the server isn't starting

### Server Setup Information:

- Version of Rocket.Chat Server: latest repo version
- Operating System: Pop!_OS 22.04 LTS (Linux distro)
- Number of Running Instances: 0
- NodeJS Version: v14.21.2

### Client Setup Information

- Desktop App or Browser Version: Browser - `Chrome` version:`Version 110.0.5481.177 (Official Build) (64-bit)`
- Operating System: Pop!_OS 22.04 LTS

### Relevant logs:
Error logs generated are as follows:

```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.21.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @rocket.chat/meteor@6.0.0-develop~predev: @rocket.chat/meteor@6.0.0-develop
6 info lifecycle @rocket.chat/meteor@6.0.0-develop~dev: @rocket.chat/meteor@6.0.0-develop
7 verbose lifecycle @rocket.chat/meteor@6.0.0-develop~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @rocket.chat/meteor@6.0.0-develop~dev: PATH: /home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sohamr/projects/Rocket.chat/Rocket.Chat/apps/meteor/node_modules/.bin:/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64:/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/tmp/xfs-bffe2f72:/tmp/xfs-62ebf313:/home/sohamr/.meteor:/home/sohamr/.nvm/versions/node/v14.21.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @rocket.chat/meteor@6.0.0-develop~dev: CWD: /home/sohamr/projects/Rocket.chat/Rocket.Chat/apps/meteor
10 silly lifecycle @rocket.chat/meteor@6.0.0-develop~dev: Args: [ '-c', 'meteor --exclude-archs "web.browser.legacy, web.cordova"' ]
11 silly lifecycle @rocket.chat/meteor@6.0.0-develop~dev: Returned: code: 254  signal: null
12 info lifecycle @rocket.chat/meteor@6.0.0-develop~dev: Failed to exec dev script
13 verbose stack Error: @rocket.chat/meteor@6.0.0-develop dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"`
13 verbose stack Exit status 254
13 verbose stack     at EventEmitter.<anonymous> (/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid @rocket.chat/meteor@6.0.0-develop
15 verbose cwd /home/sohamr/projects/Rocket.chat/Rocket.Chat/apps/meteor
16 verbose Linux 6.1.11-76060111-generic
17 verbose argv "/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/sohamr/.meteor/packages/meteor-tool/.2.9.1.xadh76.nzxkg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "run" "dev"
18 verbose node v14.21.2
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 254
22 error @rocket.chat/meteor@6.0.0-develop dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"`
22 error Exit status 254
23 error Failed at the @rocket.chat/meteor@6.0.0-develop dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 254, true ]


```

**Comment by Mahmoudgalalz** [comment]
Hello, @SohamRatnaparkhi 
just define the export in the ./bashrc or ./zshrc

`export PATH=/home/<username>/.meteor:$PATH`

change the username of yours

**Comment by mradulbohra** [comment]
Hey @Mahmoudgalalz, I tried the way you provided but still not able to run the local server. Getting the same error.
Thanks!

**Comment by SohamRatnaparkhi** [comment]
> Hey @Mahmoudgalalz, I tried the way you provided but still not able to run the local server. Getting the same error. Thanks!

Hey, same here. Locally, on my system, I even tried running their docker image for mongo server but still it failed.
Can someone help me solving this issue.

**Comment by njiddasalifu** [comment]
Hi run meteor --version in the apps/meteor directory
wait for log message of success
go back to root directory and run yarn make sure you have stable internet speed. it will take minutes you will see many log messages but built will be success if netwok is good.
finall run yarn dsv to start server.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by hiyamatakao** [comment]
This issue is related to mongodb.
Mongodb does not run on some processor architectures, such as Xeon
https://stackoverflow.com/questions/68829656/mongod-does-not-start-mongod-service-failed-with-result-signal
