### ISSUE TITLE
Emoji don't work after text in continous

### ISSUE THREAD

**Issue by Pheewww** [RocketChat/Rocket.Chat#28193]
### Description:

Emoji don't work after text without space.

### Steps to reproduce:

1. Go to any text channel
2. send a message with an emoji that is without space.

### Expected behavior:

The emoji is sent with the text message.

### Actual behavior:

The emoji text for system rendering is sent along with your message.

[emoji_after_text.webm](https://user-images.githubusercontent.com/67512605/221626952-7e8fc088-07b7-47dc-9298-f1c3578a9851.webm)

### Client Setup Information

- Desktop App or Browser Version: firefox
- Operating System: win 10

**Comment by Pheewww** [comment]
I want to know how the Unicode Support is created and how Rendering and Displaying of unicode characters is done. i can certainly work in it also.

**Comment by Bankar-Swapnil** [comment]
Hello is this issue still available? Can I work on this

**Comment by Mahmoudgalalz** [comment]
I'm working on it, and I will send the PR sooner,

**Comment by shevchukma** [comment]
Already discussed [#27505](https://github.com/RocketChat/Rocket.Chat/issues/27505)
