### ISSUE TITLE
New people joined notifications are taking whole screen space.

### ISSUE THREAD

**Issue by Pheewww** [RocketChat/Rocket.Chat#28196]
### Description:

New people joined notifications are frustating

### Steps to reproduce:

1.   Go to any community chat where lots of people have joined.

### Expected behavior:

You should see notifications regarding people joined taking some space of the screen.

### Actual behavior:

The whole messages space is taken by the notifications and it's harder to find conversations related to each other.
![People_joining_notification](https://user-images.githubusercontent.com/67512605/221632168-624fb083-ed91-4a21-bfb8-80e77963d199.png)

### Client Setup Information

- Desktop App or Browser Version: firefox
- Operating System: win 10

**Comment by Pheewww** [comment]
One solution is that if no of people joined increases certain number (say 10), then singles notifications can be displayed with only number of people joined. I can work on this.

**Comment by dudanogueira** [comment]
Hi! This can be hidden on a per channel configuration:

![image](https://user-images.githubusercontent.com/1761174/221655824-70b905cd-9df0-4178-a643-686b40712621.png)

So the owner/moderator of the channel can choose if they want to show or hide certain system messages. This behavior is unavoidable if you want to both show those kind of system messages on a highly active channel.

I'll close it, but thanks for reporting this, we really appreciate it :)
