### ISSUE TITLE
Whatsapp 360Dialog message crash Rocket.Chat

### ISSUE THREAD

**Issue by leolage** [RocketChat/Rocket.Chat#28202]
### Description:

One simple customer send a specific message and crash our RocketChat Enterprise Instalation. I try to get support by enterprise techs, but I cant have help after 12 hours!
The message of custer have a mysql status query, and have a lot of caracters. RocketChat receive message, but cant confirm to whataspp a message received, and whatsapp try to sending again the big message to rocketchat, creating a loop and crashing rocketchat. We stop service and restart, but not fix problem. We cant use RocketChat Enterprise at more 12 hours.

### Steps to reproduce:

1. Customer send a Whatsapp message via Dialog360 to our Rocketchat specific content (the content inside log below)
2. Rocketchat open 1 Ominchannel chat for customer.
3. Seconds later, RocketChat open another chat to same customer, after 3 times RocketChat stop respond.

### Expected behavior:

I need to cancel this message, because RocketChat receiving this message forever.

### Actual behavior:

after 3 times received same buged message, rocketchat crash, and need to restart, not responde more. We need to close ports 80 and 443 to stop receive message buged from whatsapp.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.3
- Operating System:  AlmaLinux 8.7
- Deployment Method:  tar file installed direct on linux
- Number of Running Instances: 1
- DB Replicaset Oplog: no replica
- NodeJS Version: v14.18.3
- MongoDB Version: 4.4.18 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Browser Chrome
- Operating System: Windows 10

### Additional context

I open ticket to enterprise (poor) support: 69277 
### Relevant logs:

Below, the log with message content:

[
  "incoming's post is being executed...",
  {
    "method": "post",
    "headers": {
      "connection": "upgrade",
      "host": "rocketchat.mycompany.com",
      "x-real-ip": "99.99.99.99",
      "x-forwarded-for": "99.99.99.99",
      "x-forwarded-proto": "https",
      "x-nginx-proxy": "true",
      "content-length": "38045",
      "user-agent": "Go-http-client/1.1",
      "content-type": "application/json",
      "accept-encoding": "gzip"
    },
    "query": {
      "contactWaId": "55000000000"
    },
    "params": {},
    "content": {
      "contacts": [
        {
          "profile": {
            "name": "John Doe"
          },
          "wa_id": "55000000000"
        }
      ],
      "messages": [
        {
          "from": "55000000000",
          "id": "ABEGVYaaaaaa",
          "text": {
            "body": "mysql> SHOW ENGINE INNODB STATUS;\n+--------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Type   | Name | Status                                                                                                                   |\n+--------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| InnoDB |      |\n=====================================\n2023-02-27 10:40:22 0x7f67d6f72700 INNODB MONITOR OUTPUT\n=====================================\nPer second averages calculated from the last 28 seconds\n-----------------\nBACKGROUND THREAD\n-----------------\nsrv_master_thread loops: 1337 srv_active, 0 srv_shutdown, 71 srv_idle\nsrv_master_thread log flush and writes: 1408\n----------\nSEMAPHORES\n----------\nOS WAIT ARRAY INFO: reservation count 3899\nOS WAIT ARRAY INFO: signal count 2777\nRW-shared spins 0, rounds 1655, OS waits 429\nRW-excl spins 0, rounds 998, OS waits 49\nRW-sx spins 2, rounds 60, OS waits 2\nSpin rounds per wait: 1655.00 RW-shared, 998.00 RW-excl, 30.00 RW-sx\n------------\nTRANSACTIONS\n------------\nTrx id counter 202375306\nPurge done for trx's n:o < 202366905 undo n:o < 0 state: running but idle\nHistory list length 385\nLIST OF TRANSACTIONS FOR EACH SESSION:\n---TRANSACTION 421561253636384, not started\n0 lock struct(s), heap size 1136, 0 row lock(s)\n---TRANSACTION 421561253640032, not started\n0 lock struct(s), heap size 1136, 0 row lock(s)\n---TRANSACTION 421561253635472, not started\n0 lock struct(s), heap size 1136, 0 row lock(s)\n---TRANSACTION 421561253634560, not started\n0 lock struct(s), heap size 1136, 0 row lock(s)\n---TRANSACTION 421561253630912, not started\n0 lock struct(s), heap size 1136, 0 row lock(s)\n---TRANSACTION 421561253638208, not started\n0 lock struct(s), heap size 1136, 0 row lock(s)\n--------\nFILE I/O\n--------\nI/O thread 0 state: waiting for completed aio requests (insert buffer thread)\nI/O thread 1 state: waiting for completed aio requests (log thread)\nI/O thread 2 state: waiting for completed aio requests (read thread)\nI/O thread 3 state: waiting for completed aio requests (read thread)\nI/O thread 4 state: waiting for completed aio requests (read thread)\nI/O thread 5 state: waiting for completed aio requests (read thread)\nI/O thread 6 state: waiting for completed aio requests (write thread)\nI/O thread 7 state: waiting for completed aio requests (write thread)\nI/O thread 8 state: waiting for completed aio requests (write thread)\nI/O thread 9 state: waiting for completed aio requests (write thread)\nPending normal aio reads: [0, 0, 0, 0] , aio writes: [0, 0, 0, 0] ,\n ibuf aio reads:, log i/o's:, sync i/o's:\nPending flushes (fsync) log: 0; buffer pool: 0\n90537 OS file reads, 7355 OS file writes, 3146 OS fsyncs\n1.96 reads/s, 16384 avg bytes/read, 0.29 writes/s, 0.29 fsyncs/s\n-------------------------------------\nINSERT BUFFER AND ADAPTIVE HASH INDEX\n-------------------------------------\nIbuf: size 1, free list len 1250, seg size 1252, 457 merges\nmerged operations:\n insert 988, delete mark 711, delete 0\ndiscarded operations:\n insert 0, delete mark 0, delete 0\nHash table size 553193, node heap has 906 buffer(s)\nHash table size 553193, node heap has 867 buffer(s)\nHash table size 553193, node heap has 569 buffer(s)\nHash table size 553193, node heap has 501 buffer(s)\nHash table size 553193, node heap has 624 buffer(s)\nHash table size 553193, node heap has 1036 buffer(s)\nHash table size 553193, node heap has 1219 buffer(s)\nHash table size 553193, node heap has 364 buffer(s)\n13129.92 hash searches/s, 1255.17 non-hash searches/s\n---\nLOG\n---\nLog sequence number 81761596244\nLog flushed up to   81761596244\nPages flushed up to 81761592876\nLast checkpoint at  81761592876\n0 pending log flushes, 0 pending chkp writes\n1989 log i/o's done, 0.28 log i/o's/second\n----------------------\nBUFFER POOL AND MEMORY\n----------------------\nTotal large memory allocated 2198863872\nDictionary memory allocated 59995744\nBuffer pool size   131056\nFree buffers       35715\nDatabase pages     89255\nOld database pages 33072\nModified db pages  41\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 51, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 88484, created 771, written 5027\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 89255, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n----------------------\nINDIVIDUAL BUFFER POOL INFO\n----------------------\n---BUFFER POOL 0\nBuffer pool size   16382\nFree buffers       4616\nDatabase pages     11005\nOld database pages 4082\nModified db pages  10\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 8, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 10872, created 133, written 740\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 11005, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 1\nBuffer pool size   16382\nFree buffers       4110\nDatabase pages     11511\nOld database pages 4269\nModified db pages  0\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 2, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 11407, created 104, written 359\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 11511, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 2\nBuffer pool size   16382\nFree buffers       5155\nDatabase pages     10461\nOld database pages 3881\nModified db pages  3\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 8, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 10396, created 65, written 578\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 10461, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 3\nBuffer pool size   16382\nFree buffers       3701\nDatabase pages     11921\nOld database pages 4420\nModified db pages  4\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 11, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 11845, created 76, written 653\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 11921, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 4\nBuffer pool size   16382\nFree buffers       6159\nDatabase pages     9467\nOld database pages 3504\nModified db pages  1\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 2, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 9403, created 64, written 335\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 9467, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 5\nBuffer pool size   16382\nFree buffers       3741\nDatabase pages     11886\nOld database pages 4407\nModified db pages  5\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 4, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 11820, created 66, written 544\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 11886, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 6\nBuffer pool size   16382\nFree buffers       4181\nDatabase pages     11440\nOld database pages 4242\nModified db pages  10\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 5, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 11311, created 129, written 1161\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 11440, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n---BUFFER POOL 7\nBuffer pool size   16382\nFree buffers       4052\nDatabase pages     11564\nOld database pages 4267\nModified db pages  8\nPending reads      0\nPending writes: LRU 0, flush list 0, single page 0\nPages made young 11, not young 0\n0.00 youngs/s, 0.00 non-youngs/s\nPages read 11430, created 134, written 657\n0.00 reads/s, 0.00 creates/s, 0.00 writes/s\nBuffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000\nPages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s\nLRU len: 11564, unzip_LRU len: 0\nI/O sum[0]:cur[0], unzip sum[0]:cur[0]\n--------------\nROW OPERATIONS\n--------------\n0 queries inside InnoDB, 0 queries in queue\n3 read views open inside InnoDB\nProcess ID=13367, Main thread ID=140083978897152, state: sleeping\nNumber of rows inserted 755328, updated 924, deleted 215, read 182217064\n334.45 inserts/s, 0.11 updates/s, 0.04 deletes/s, 667803.08 reads/s\n----------------------------\nEND OF INNODB MONITOR OUTPUT\n============================\n |\n+--------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n1 row in set (0,12 sec)\n\nmysql>"
          },
          "timestamp": "1677505389",
          "type": "text"
        }
      ]
    },
    "privateHash": "DA6PXhzMjA5CduxGt"
  }
]

Next log lines:

{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"| InnoDB |      |"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"====================================="}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"2023-02-27 10:40:22 0x7f67d6f72700 INNODB MONITOR OUTPUT"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"====================================="}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"Per second averages calculated from the last 28 seconds"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"-----------------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"BACKGROUND THREAD"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"-----------------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"srv_master_thread loops: 1337 srv_active, 0 srv_shutdown, 71 srv_idle"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"srv_master_thread log flush and writes: 1408"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"----------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"SEMAPHORES"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"----------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"OS WAIT ARRAY INFO: reservation count 3899"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"OS WAIT ARRAY INFO: signal count 2777"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"RW-shared spins 0, rounds 1655, OS waits 429"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"RW-excl spins 0, rounds 998, OS waits 49"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"RW-sx spins 2, rounds 60, OS waits 2"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"Spin rounds per wait: 1655.00 RW-shared, 998.00 RW-excl, 30.00 RW-sx"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"------------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"TRANSACTIONS"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"------------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"Trx id counter 202375306"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"Purge done for trx's n:o < 202366905 undo n:o < 0 state: running but idle"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"History list length 385"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"LIST OF TRANSACTIONS FOR EACH SESSION:"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"---TRANSACTION 421561253636384, not started"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"0 lock struct(s), heap size 1136, 0 row lock(s)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"---TRANSACTION 421561253640032, not started"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"0 lock struct(s), heap size 1136, 0 row lock(s)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"---TRANSACTION 421561253635472, not started"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"0 lock struct(s), heap size 1136, 0 row lock(s)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"---TRANSACTION 421561253634560, not started"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"0 lock struct(s), heap size 1136, 0 row lock(s)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"---TRANSACTION 421561253630912, not started"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"0 lock struct(s), heap size 1136, 0 row lock(s)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"---TRANSACTION 421561253638208, not started"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"0 lock struct(s), heap size 1136, 0 row lock(s)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"--------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"FILE I/O"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"--------"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 0 state: waiting for completed aio requests (insert buffer thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 1 state: waiting for completed aio requests (log thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 2 state: waiting for completed aio requests (read thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 3 state: waiting for completed aio requests (read thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 4 state: waiting for completed aio requests (read thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 5 state: waiting for completed aio requests (read thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 6 state: waiting for completed aio requests (write thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 7 state: waiting for completed aio requests (write thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 8 state: waiting for completed aio requests (write thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"I/O thread 9 state: waiting for completed aio requests (write thread)"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":"Pending normal aio reads: [0, 0, 0, 0] , aio writes: [0, 0, 0, 0] ,"}]},{"type":"PARAGRAPH","value":[{"type":"PLAIN_TEXT","value":" ibuf aio reads:, log i/o's:, sync i/o's:

 I capture this log on whatsapp dialog360 app log, its a response from rocketchat to whatasapp?
 
 
![image](https://user-images.githubusercontent.com/23029635/221742171-2753f469-73ee-419d-8f0d-aa21f12be48e.png)

**Comment by leolage** [comment]
update 1: I fix the error in cloud access token, but problem persists exactly of I described.

**Comment by SANGAAM** [comment]
@rocket.chat/forked-matrix-sdk-crypto-nodejs@npm:0.1.0-beta.12 must be built because it never has been before or the last one failed

Hey while intsalling yarn dependencies im getting this issue can u pls tell me where im wrond

**Comment by leolage** [comment]
below the complete message of customer, this customer send a mysql status by whatasapp message... rocketchat message have a limit of 5000 characters by message (per default) but ignore it

https://pastebin.com/ZvsjWYMk

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project. If this issue still persist, open a Forum discussion, please

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
