### ISSUE TITLE
The link does not work when the second block of the URL starts with a number.

### ISSUE THREAD

**Issue by misafortune** [RocketChat/Rocket.Chat#28215]
### Description:

The link does not work when the second block of the URL starts with a number.

### Steps to reproduce:

1. Send the following by message.

http://3dconnexion.com/
http://www.3dconnexion.com/
https://3dconnexion.com/
https://www.3dconnexion.com/

### Expected behavior:

All URLs will be linked.

### Actual behavior:

Not linked only if the second block starts with a number.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Operating System: Ubuntu 20.04.5 LTS
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: on
- NodeJS Version: v14.21.1
- MongoDB Version:6.0.3 / wiredTiger (oplog on)

### Client Setup Information

- Desktop App3.8.16
- Browser Version: Chrome 110.0.5481.105
- Operating System:Windows 10/11

### Additional context

Image files are attached.
![3fef7f5a343134d00300eb0d32f7e3b6](https://user-images.githubusercontent.com/33389270/222057258-e48762c4-be4a-45b5-9e87-ac994bc2f919.png)

### Relevant logs:

{"level":20,"time":"2023-03-01T05:55:18.495Z","pid":93506,"hostname":"---","name":"OEmbed","msg":"Getting oembed metadata for 'https://3dconnexion.com/'"} 
{"level":20,"time":"2023-03-01T05:55:18.497Z","pid":93506,"hostname":"---","name":"OEmbed","msg":"Found oembed metadata in cache for 'https://3dconnexion.com/'"} 
{"level":20,"time":"2023-03-01T05:55:18.497Z","pid":93506,"hostname":"---","name":"OEmbed","msg":"Getting oembed metadata for 'https://www.3dconnexion.com/'"} 
{"level":20,"time":"2023-03-01T05:55:18.498Z","pid":93506,"hostname":"---","name":"OEmbed","msg":"Found oembed metadata in cache for 'https://www.3dconnexion.com/'"}

**Comment by hugocostadev** [comment]
Hi there, we made a change in our message-parser on how to indentify links and parse it properly and we fixed... 

You can check in our latest release: https://github.com/RocketChat/Rocket.Chat/releases/tag/6.0.0-rc.3
