### ISSUE TITLE
Telephone numbers after 11 numbers in succession

### ISSUE THREAD

**Issue by zpallin** [RocketChat/Rocket.Chat#2822]
Your Rocket.Chat version: (0.25.x)

For some reason, having 11 numbers in succession automatically makes those numbers a "telephone number". Meaning, clicking on it has the effect of calling a number... except not really.

I'm not sure why this is the case, but it seems like a bug, or just a poorly implemented feature (no offense, I could be wrong). 

If Rocket Chat intends on making "tel:" links for formatted numbers, shouldn't the rule be evoked when numbers match more strict formats such as the US's # (###) ### - #### format?

Just a thought.

**Comment by andreas-bulling** [comment]
related to #810

**Comment by andreas-bulling** [comment]
related to #810

**Comment by engelgabriel** [comment]
I believe this is now fixed as mentioned above. Please reopen otherwise.
