### ISSUE TITLE
Reactions not displaying properly in after upgrade to v25

### ISSUE THREAD

**Issue by jkdale** [RocketChat/Rocket.Chat#2823]
We just upgraded from v23 to v25.

Our team loves Rocket Chat and when we saw that emoji reactions we added to v24, it became very important for us to upgrade from v23.

So when I upgraded our server things seems to go OK. There were a couple errors I noticed when launching, but they seemed unrelated:
rocketchat_theme server.coffee:102 rocketchat:theme ➔ stop_rendering 896
{ [Error: variable @message-hover-background-color is undefined]
  type: 'Name',
  filename: 'input',
  index: 101658,
  line: 3971,
  callLine: NaN,
  callExtract: undefined,
  column: 20,
  extract: 
   [ '\t&:hover {',
     '\t\tbackground-color: @message-hover-background-color;',
     '\t}' ],
  message: 'variable @message-hover-background-color is undefined',
  stack: undefined }
cas_rocketchat.js:50 CAS ➔ info Disabling CAS login service
rocketchat_theme server.coffee:102 rocketchat:theme ➔ stop_rendering 799
{ [Error: variable @status-online is undefined]
  type: 'Name',
  filename: 'input',
  index: 179064,
  line: 7503,
  callLine: NaN,
  callExtract: undefined,
  column: 8,
  extract: [ '.icon-at.status-online {', '\tcolor: @status-online;', '}' ],
  message: 'variable @status-online is undefined',
  stack: undefined }
sync.js:195 LDAPSync ➔ info Enabling LDAP user sync
rocketchat_theme server.coffee:102 rocketchat:theme ➔ stop_rendering 852
{ [Error: error evaluating function `darken`: Object [object Object] has no method 'toHSL']
  type: 'undefined_method',
  filename: 'input',
  index: 182453,
  line: 7715,
  callLine: NaN,
  callExtract: undefined,
  column: 24,
  extract: 
   [ '\t\t\tcolor: fade( @quaternary-font-color, 50% );',
     '\t\t\tborder-bottom-color: darken(@primary-background-color, 2%);',
     '\t\t\t&:hover {' ],
  message: 'error evaluating function `darken`: Object [object Object] has no method \'toHSL\'',
  stack: undefined }
{"line":"114","file":"migrations.js","message":"Migrations: Migrating from version 34 -> 37","time":{"$date":1460201798070},"level":"info"}
{"line":"114","file":"migrations.js","message":"Migrations: Running up() on version 35","time":{"$date":1460201798074},"level":"info"}
rocketchat_theme server.coffee:102 rocketchat:theme ➔ stop_rendering 759
{ [Error: error evaluating function `darken`: Object [object Object] has no method 'toHSL']
  type: 'undefined_method',
  filename: 'input',
  index: 182453,
  line: 7715,
  callLine: NaN,
  callExtract: undefined,
  column: 24,
  extract: 
   [ '\t\t\tcolor: fade( @quaternary-font-color, 50% );',
     '\t\t\tborder-bottom-color: darken(@primary-background-color, 2%);',
     '\t\t\t&:hover {' ],
  message: 'error evaluating function `darken`: Object [object Object] has no method \'toHSL\'',
  stack: undefined }

So when I connected to our instance to check it out, I noticed that emoji reactions do not appear to be displaying properly. Here is a screenshot:
https://www.dropbox.com/s/owtkvnh2pznjvym/Screen%20Shot%202016-04-09%20at%207.45.20%20AM.png?dl=0

Any idea what's going on?

**Comment by marceloschmidt** [comment]
Could you try with the latest version, please? It's possible that this has already been fixed. Thanks!

**Comment by jeje42** [comment]
Hi,

I get the same error message about @message-hover-background-color using this method with a raspberry pi B+ : https://github.com/RocketChat/Rocket.Chat.RaspberryPi .

I use a local mongodb database (v3.2.6) on archlinux.

Is the archive "rocket.chat-pi-develop.tgz" up to date ? 

Anyway I cannot access to the running app. I give you the whole output message :

[output.txt](https://github.com/RocketChat/Rocket.Chat/files/280633/output.txt)

Thanks for your help !

**Comment by rodrigok** [comment]
Please, reopen the issue if the problem persists
