### ISSUE TITLE
Is it possible to use omnichannel in your domain?

### ISSUE THREAD

**Issue by ascmedia** [RocketChat/Rocket.Chat#28238]
Question: i need scheme like with telegram bots, omnichannel but with RC bot. People will ask questions to bot, and some stuff will answers them. Something like inner ticket system.

**Comment by dudanogueira** [comment]
Hi! This is not the right place to ask questions. Here is for software issues only. And when opening an issue, provide all the required information.

Please, read this doc before opening an issue or to find where to get proper help when using or integrating Rocket.Chat:
https://docs.rocket.chat/resources/get-support/community-resources

The answer to your question, in general lines is yes, you can use bot with Rocket in all sorts.
