### ISSUE TITLE
Enter key does not work in modal password windows

### ISSUE THREAD

**Issue by ansiwen** [RocketChat/Rocket.Chat#28242]
### Description:

When the Web-UI asks you to re-enter the password (2fa fallback) in a modal window, the enter key has no effect, and you have to use the mouse to verify.

### Steps to reproduce:

1. disable 2fa but enable password fallback
2. change any setting that requires 2fa in the `/admin` UI
3. enter your password into the modal window

### Expected behavior:

after entering the password, the enter key should submit the password

### Actual behavior:

The enter key has no effect

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.3
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 110.0.5481.177
- Operating System: MacOS 12.6.1

**Comment by bhardwajdisha** [comment]
Hi Ansiwen
I would like to work on this issue. Can you please assign this issue to me?
