### ISSUE TITLE
Users Cannot Parse Markdown URL's with special characters using new message parser

### ISSUE THREAD

**Issue by tuxfoo** [RocketChat/Rocket.Chat#28251]
### Description:

While using the new message parser; URL's that contain special characters are not rendered (The title).
![image](https://user-images.githubusercontent.com/1560023/222620718-46563733-f5db-472f-9bd1-fbae4e02b986.png)

### Steps to reproduce:

1. Use the new message parser
2. See screenshot

### Expected behavior:

The URL will be rendered with the title from the markdown

### Actual behavior:

The markdown is rendered as plain text

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.2
- Operating System: CentOS Linux release 8.5.2111
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4.18

### Additional context

We would switch back to the old parser but unfortunately we were experiencing [issues/27118](https://github.com/RocketChat/Rocket.Chat/issues/27118) which was even more annoying; so we decided we would replace special characters before our bot posts them to Rocketchat (First message in screenshot is replacing characters with hypens which seem to work).

**Comment by hugocostadev** [comment]
Thanks for contributing, I'll take a look
