### ISSUE TITLE
Download dialog has unreadable text

### ISSUE THREAD

**Issue by AndreSomers** [RocketChat/Rocket.Chat#28253]
Running on: Kubuntu Linux (Ubuntu 20.04.5 LTS) running KDE 

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-139-generic
OS Type: 64-bit

RocketChat version 3.8.13 desktop client

The download dialog in RocketChat client application is completely unusable, as the font seems to not be present or something along those lines. All characters are just these place holder boxes:

![Screenshot RocketChat download dialog](https://user-images.githubusercontent.com/10531631/222658705-9a85e4a9-4cb9-45a8-8742-10001f9c918d.png)

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
