### ISSUE TITLE
UI: scroll down quirk in channel list

### ISSUE THREAD

**Issue by ansiwen** [RocketChat/Rocket.Chat#28255]
### Description:

If the list in the left sidebar is longer than the windows height, scrolling sometime "jumps". Especially weird is if the list is just a bit longer than the window, so that the last item is almost covered. See attached video. (The weird channel names in the video are not the problem, they are part of another test and not related. It also happens with regular channel names.)

### Steps to reproduce:

1. create a couple of channels
2. resize the window so that the last channel is just not visible
3. scroll down in the channel list

### Expected behavior:

smooth scrolling

### Actual behavior:

weirdly jumping around

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.3
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 110.0.5481.177
- Operating System: MacOS 12.6.1

https://user-images.githubusercontent.com/7792669/222725869-7e1d52e8-6fe6-4983-acd3-f90c487b77d4.mov

**Comment by bhardwajdisha** [comment]
Hi
Please assign this issue to me I would like to work on this issue

**Comment by priyanshu-kun** [comment]
@ansiwen I don't know man, I didn't see any weird scroll behavior except content overflow scroll in x direction. As you can see in the video!
[Screencast from 04-03-23 08:18:54 AM IST.webm](https://user-images.githubusercontent.com/57032769/222872179-3667d690-07bb-40ed-b1e8-c04ad42c2def.webm)

**Comment by garvitkhandelwal** [comment]
@ansiwen anyone working on this? i would like to get this assigned to me.

**Comment by hugocostadev** [comment]
This was fixed in our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) most likely by this PR https://github.com/RocketChat/Rocket.Chat/pull/27571
