### ISSUE TITLE
Flickering message context menu when touch the bottom of window

### ISSUE THREAD

**Issue by ansiwen** [RocketChat/Rocket.Chat#28259]
### Description:

If the context menu of a message touches the bottom of the window it starts to flicker. (See attached video)

### Steps to reproduce:

1. scroll a messsage in a channel in a position so that it touches the bottom of the window

### Expected behavior:

A stable context menu is shown

### Actual behavior:

The context menu is flickering

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.3
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 110.0.5481.177
- Operating System: MacOS 12.6.1

https://user-images.githubusercontent.com/7792669/222764029-40eaf5a4-6dc3-4b69-8ba7-ebbe6a6e5bec.mov

**Comment by rithiksanjeev** [comment]
Hey, iam new and i wanna work on this issue. Can you assign it to me?

**Comment by hugocostadev** [comment]
This was already fixed on latest release 6.0.0
