### ISSUE TITLE
Channel already exists error contains # with channel name

### ISSUE THREAD

**Issue by Bankar-Swapnil** [RocketChat/Rocket.Chat#28273]
### Description:

Channel already exists error contains # with channel name

### Steps to reproduce:

1. create first channel with channel name eg("test")
2. try to create second channel with channel name same as first team eg("test")

### Expected behavior:

 shows error = "The  Channel  'test' already exists"

### Actual behavior:

it shows error = "The  Channel  '#test' already exists"

![Screenshot (28)](https://user-images.githubusercontent.com/98152507/222881258-65e4aa94-7657-4ba8-a631-d491f78e4764.png)

### Client Setup Information

- Desktop App or Browser Version: firefox
- Operating System: win 10

**Comment by hugocostadev** [comment]
Hi, thanks for contributing! 

But this is not a bug and a issue, it was intended to be like that
