### ISSUE TITLE
Unable to upload files after upgrading

### ISSUE THREAD

**Issue by jeffclay** [RocketChat/Rocket.Chat#28274]
When trying to upload a file, the page flickers and nothing actually uploads. There are no errors or messages presented in the web UI.

I'm getting this message in journalctl when trying to upload a file:
```
Mar 04 01:16:14 rc rocketchat[12631]: Exception in callback of async function: Error: Input Buffer is empty
Mar 04 01:16:14 rc rocketchat[12631]:     at Sharp._createInputDescriptor (/opt/Rocket.Chat/programs/server/npm/node_modules/sharp/lib/input.js:35:13)
Mar 04 01:16:14 rc rocketchat[12631]:     at new Sharp (/opt/Rocket.Chat/programs/server/npm/node_modules/sharp/lib/constructor.js:298:29)
Mar 04 01:16:14 rc rocketchat[12631]:     at Sharp (/opt/Rocket.Chat/programs/server/npm/node_modules/sharp/lib/constructor.js:137:12)
Mar 04 01:16:14 rc rocketchat[12631]:     at app/assets/server/assets.ts:522:3
Mar 04 01:16:14 rc rocketchat[12631]:     at runWithEnvironment (packages/meteor.js:1320:24)
Mar 04 01:16:14 rc rocketchat[12631]:     at packages/meteor.js:1333:14
Mar 04 01:16:14 rc rocketchat[12631]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

### Server Setup Information:

- Upload storage type: GridFS
- Version of Rocket.Chat Server:  5.4.3
- Operating System: Rocky Linux 9.1
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Multiple browsers 
- Operating System: Linux and Mac OS

**Comment by affan00733** [comment]
Hi ,
I am a working professional and willing to participate in GSOC 2023 so want to solve this issue

**Comment by jeffclay** [comment]
I'm confused. @affan00733 why are you only stating that you want to solve the issue without offering any troubleshooting recommendations or proposing a solution?

**Comment by affan00733** [comment]
Yes, @jeffclay  I will offer a few solutions; all I need is your approval to get started. As my goal is to participate in the rocket.chat GSOC project in 2023, I wanted to address this issue PR so it could be highlighted in my proposal. This will help you understand my application better since then I will be familiar with the project and also I have the advantage that I am a working professional.

**Comment by jeffclay** [comment]
@affan00733 I don't know what you're trying to do; this isn't a pull request. This issue is open to anyone to assist with and it does not require permission or applications.

**Comment by tehami02** [comment]
@jeffclay As I can see  the error "Input Buffer is empty" indicates that the code is attempting to process a file that has no content. This can happen if the file is not properly uploaded to the server, or if there is a bug in the upload code that is causing it to fail.
Also the error message suggests that the issue might be with the "sharp" library that rocket.chat uses for image processing.

**Comment by jeffclay** [comment]
@tehami02 that isn't helpful.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest releases.

If still happens, let us know and provide more details, please. If this is the case you can reopen the issue

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
