### ISSUE TITLE
App Crashing when switching to Hindi (hi-In) language 

### ISSUE THREAD

**Issue by AdityaSingh-02** [RocketChat/Rocket.Chat#28280]
### Steps to reproduce:

1.  .../admin/settings/General 
2. Change language to hi-In
3. Save changes

### Expected behavior:
Language should change to Hindi

### Actual behavior:
App is crashing

![Screenshot 2023-03-05 205530](https://user-images.githubusercontent.com/94185167/222969756-1894e856-2c4a-4178-8a68-acd50fd6abbd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.2
- MongoDB Version:5.0.5

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:Ubuntu

**Comment by bhardwajdisha** [comment]
hi @AdityaSingh-02 Can I take this up ?
