### ISSUE TITLE
Server stopped working after adding value into Amazon S3 acl 

### ISSUE THREAD

**Issue by muke5hy** [RocketChat/Rocket.Chat#2828]
Your Rocket.Chat version: (make sure you are running the latest)
I added wrong acl info mistakenly in the `Amazon S3 acl` since then app has stopped working I'm getting following error in log   

```
Error: Match error: Failed Match.Where validation in field acl
    at check (packages/check/match.js:33:1)
    at new Slingshot.Directive (packages/edgee_slingshot/packages/edgee_slingshot.js:304:1)
    at Object.Slingshot.createDirective (packages/edgee_slingshot/packages/edgee_slingshot.js:274:1)
    at server/config/configFileUploadAmazonS3.js:94:13
    at [object Object].later [as _onTimeout] (packages/underscore/underscore.js:731:1)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
error: Forever detected script exited with code: 8
error: Script restart attempt #60
Updating process.env.MAIL_URL

/home/ubuntu/Rocket.Chat/programs/server/packages/check.js:56
    throw err; 
```

How do I rectify it, Can I change value directly in mongo if yes how?

**Comment by muke5hy** [comment]
I got temporary fix to this problem by removing entry from settings collection, removed ```FileUpload_S3_Acl``` _id

**Comment by MartinSchoeler** [comment]
Hey @muke5hy , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
