### ISSUE TITLE
Unnecessary hover effect when hover on user / room name in room information and user information section

### ISSUE THREAD

**Issue by Bankar-Swapnil** [RocketChat/Rocket.Chat#28299]
### Description:

in the room information and in the user information section if we hover on user name or room name it shows unnecessary hover effect and hover effect place is wrong 

### Steps to reproduce:

1. click on user information  /  click on room information 
2. hover on user name   /   hover  on room name 

### Expected behavior:

no hover effect is required when hover on room name / user name .

### Actual behavior:

https://user-images.githubusercontent.com/98152507/223200750-106db623-47f5-4529-8453-231cdf049dce.mp4

### Client Setup Information

- Desktop App or Browser Version: firefox
- Operating System: win 10

**Comment by hugocostadev** [comment]
This is not necessary, on bigger names the name in truncated.

![image](https://user-images.githubusercontent.com/20212776/224320495-f254aafa-7753-42a2-9265-fa72e196c733.png)

Thanks for contributing
