### ISSUE TITLE
Wrong toast message while creating a new custom sound with an existing name

### ISSUE THREAD

**Issue by bhardwajdisha** [RocketChat/Rocket.Chat#28297]
### Description:
The toast message displayed is incorrect when attempting to create a new custom sound `/admin/custom-sounds/new`   with a name of file that already exists.
Two toast one indicating success while the other indicating an error is displayed.

![image](https://user-images.githubusercontent.com/67470541/223190528-3cd8b801-2939-426f-83b5-37f2a14ff78e.png)

### Steps to reproduce:

1. Go to Administration section `/admin`
2. From the sidebar, choose custom sound `/admin/custom-sounds` 
3. Go to `/admin/custom-sounds/new`  and create a new custom sound file with the same name as of an existing file

### Expected behavior:

An error toast should be displayed only.

### Actual behavior:
Both the success as well as error message is displayed.

https://user-images.githubusercontent.com/67470541/223188179-16f0ec31-91c0-4d06-be81-3648a94af8d8.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Ubuntu
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: v14.21.2
- MongoDB Version: v5.0.5

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 110.0.5481.104
- Operating System: Windows 11 with WSL

**Comment by bhardwajdisha** [comment]
hi @dougfabris and @dudanogueira, can you please review this.
I would like to work on this issue.

**Comment by subhajit20** [comment]
Hi @bhardwajdisha have you fixed the issue ?

**Comment by subhajit20** [comment]
Cool, @bhardwajdisha , can you tell me where is that particular file exists inside the project that you have fixed?

**Comment by bhardwajdisha** [comment]
@subhajit20 Sure you can find this file here : apps/meteor/client/views/admin/customSounds/AddCustomSound.tsx

**Comment by dudanogueira** [comment]
Nice catch, @bhardwajdisha!! Thanks!
