### ISSUE TITLE
Enable Desktop popup Notifications

### ISSUE THREAD

**Issue by aokutemaruino** [RocketChat/Rocket.Chat#283]
When the window receives the message at the time of the non-active, I want to make HTML5 desktop notification is displayed.
Also, I want to be a notification of conditions can be set for each DM and room. (Notification conditions, such as "Mention only" や "All messages")

The ability to display a notification has been implements in notification.coffee? Just not being used?

https://developer.mozilla.org/en-US/docs/Web/API/notification
https://slack.zendesk.com/hc/en-us/articles/201355156-Desktop-notifications

**Comment by rodrigok** [comment]
Hi @aokutemaruino, we are working on it now as we are developing the Desktop App (https://github.com/RocketChat/Rocket.Chat.Electron), the notification will be available on the Desktop and Web version, probably until the weekend.

The configuration will be implemented as long as we implement the settings page (https://github.com/RocketChat/Rocket.Chat/issues/222)

**Comment by aokutemaruino** [comment]
@rodrigok Thank you answer! looking forward to the weekend.
