### ISSUE TITLE
User Directory

### ISSUE THREAD

**Issue by rhysxevans** [RocketChat/Rocket.Chat#2831]
Your Rocket.Chat version: 0.24.0

Hi

The ability to have a user directory would be great. So instead of having to search the user user list we could just select the user name. This may give more details about the user if hovering over the name, potentially listing the email address etc

We have some people who's names are spelt a bit oddly and or the user name may not match the actual users name

Thanks

**Comment by louisemessage** [comment]
Closed as members list is available in 2.10.5.
