### ISSUE TITLE
Not redirecting to home when hiding channel/team/directmessage

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Rocket.Chat#28324]
### Description:
- When we are in the channel/team/direct-message and hiding any of those currently doesn't hide that room.[Check Fig (b)] I think hiding is similar to delete and used by user to get rid of those rooms. thus when hiding this should redirect to home. [Check Fig (a)]

### Steps to reproduce:

1.  Go to channel/team/direct-message
2.  Hide the channel/team/direct-message you are in.
3.  Check the room on the right isn't getting redirect to home.

### Expected behavior:

![HomePage](https://user-images.githubusercontent.com/65061890/223638007-2a3ea19e-384d-4a6b-ab81-02eb7509512d.gif)
<p align="center"> <b> [Fig (a)] </b> </p>

### Actual behavior:

![NotGettingHide](https://user-images.githubusercontent.com/65061890/223637042-1607e456-97ae-47b5-9922-65b93e2e06ae.gif)
<p align="center"> <b> [Fig (b)] </b> </p>

### Additional context
- [x] I'm not sure this is the feature or bug.correct me and would love to know the idea/mindset behind this if its a feat.

**Comment by IllTamer** [comment]
Perhaps hiding in the original logic is not the same as deleting, so the chat interface still exists. I'm also stumped on this issue, if it's flagged as a bug, I'll fix it as soon as possible.

**Comment by tabareslorenzo** [comment]
I think I have a working solution!

**Comment by dougfabris** [comment]
Closing this one because redirecting to the home route after hiding a room isn't a behavior we want here. You can continue seeing the room but it has been hidden!
Thanks for your contribution @Nabhag8848
