### ISSUE TITLE
Unread Rooms/Channels list order

### ISSUE THREAD

**Issue by rhysxevans** [RocketChat/Rocket.Chat#2832]
Your Rocket.Chat version: 0.24.0

Hi

Is there away we could make unread channels/rooms move to the top of the lists ? so if we have 20 channels and they all don't fit into the scroll-able screen the currently "active" ones always appear at the top of their respective sections.

I hope that makes sense

Thanks

**Comment by cbajohr** [comment]
There's an option for that in your personal user config "unread rooms mode"

**Comment by rhysxevans** [comment]
Perfect, will let my users know

thanks for your help

**Comment by engelgabriel** [comment]
Thanks @cbajohr, and I hope it is what you need @rhysxevans

**Comment by hughlroberts** [comment]
Still not too great in that it breaks it out of the lists rather than actually bumping it to the top but a good workaround at this point... would rather it be improved to actually stay in the channels / private messages and favorites sections but bump to the top and then stay at the top in order of frequency of use rather than going back down

**Comment by ricardojohnny** [comment]
How do I change this setting for all users by default?

**Comment by tylwright** [comment]
@ricardojohnny - You can run this on the DB to update the setting for all _existing_ users.  Not sure how to make it sticky for new users yet.

```
db.users.update(
	{},
	{ $set: { "settings.preferences.roomsListExhibitionMode": "unread"} },
	{multi: true}
);
```

**Comment by simonv3** [comment]
Honestly I think this should be the default view for any new user. I think it's much more user friendly (and also familiar from people who are coming from Slack)

**Comment by HammyHavoc** [comment]
I have to agree with @simonv3, it isn't intuitive/conducive to productivity if you've got more than a handful of DMs/channels/groups.
