### ISSUE TITLE
Getting all channels/rooms via API doesn't get all rooms

### ISSUE THREAD

**Issue by Kuper299** [RocketChat/Rocket.Chat#28325]
Hello all,

I'm running Rocket Chat v5.4.1, my main goal is to filter all the non-archived rooms, since there is no method to do so directly I tried to get all the rooms and channels of a user using its token and user id and filtered the non-archived rooms out of the results.
to get all the rooms/channels I used the following API requests using python:
```
subscriptions.get
channels.list
rooms.get
```

I got most of the rooms, however there are around 100 rooms that I can't get using the rest API.

Is there another method I can use to reach my goal or am I missing something in the process?

Please let me know if more information is required.

Thank you

**Comment by dudanogueira** [comment]
Hi, please, provide all thew required information when opening an issue, specially a way to replicate this issue on a clean new install.

Please, read this documento on how to better use our community resources:
https://docs.rocket.chat/getting-support/community-resources

You should check if the user you are using has necessary permissions to list all channels. Also, you can "mimic" the API calls inspecting the UI, so at admin/rooms you can inspect the calls for getting the rooms list for an ADMIN user.

Closing now
