### ISSUE TITLE
Link previews are not removed when the link is edited out

### ISSUE THREAD

**Issue by denisfadeev** [RocketChat/Rocket.Chat#2833]
When I edit my sent message and remove a link from it, the link preview stays in the chat.
Mac App Version 1.3.1 (15)

**Comment by MartinSchoeler** [comment]
@karlprieb this is still happening on the latest version

**Comment by Hudell** [comment]
The problem is still happening, but if you add a new url when editing, then the previews are updated accordingly.

**Comment by Hudell** [comment]
@ggazzo please check the proposed solution on the comments of #4993

**Comment by ggazzo** [comment]
@Hudell I dont think `/packages/rocketchat-lib/server/functions/updateMessage.js` is a ux problem, but give some days I will try ;)
