### ISSUE TITLE
Allow to clear channel history manually und timed

### ISSUE THREAD

**Issue by cbajohr** [RocketChat/Rocket.Chat#2834]
Your Rocket.Chat version: 0.25.0

Like Hipchat, it should be possible for administrators to clear the history of a channel and/or to set an optional and relative time limit for keeping messages, like 1 month.

**Comment by prohde** [comment]
+1

**Comment by engelgabriel** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/1861
Related to https://github.com/RocketChat/Rocket.Chat/issues/2196
