### ISSUE TITLE
[Omnichannel] React UI error when accessing Omnichannel in Admin Settings

### ISSUE THREAD

**Issue by maudrid** [RocketChat/Rocket.Chat#28343]
### Description:

In the admin settings page, when I click on ommnichannel, I just get a blank screen.
See related forum Post: https://forums.rocket.chat/t/omichannel-settings-page-not-loading/16138

### Steps to reproduce:

1. Open the admin section
2. Go to settings
3. Find Omnichannel
4. Select Omnichannel

### Expected behavior:

See all the settings related to Omnichannel

### Actual behavior:

See a blank, grey screen

### Server Setup Information:

Server Setup Information
Version of Rocket.Chat Server: tested on 5.4.2 and 5.1.4
Operating System: Docker Image
Version 5.4.2
Apps Engine Version 1.36.0
Node Version v14.19.3
Database Migration 281 (March 2, 2023 8:59 AM)
MongoDB
5.0.9 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (87f116bab)
Branch: HEAD
PID 1
Proxy: tested on both nginx and traefik
Firewalls involved: I’m unsure

### Client Setup Information

- Browser: Google Chrome Version 111.0.5563.64 (Official Build) (64-bit)
- Operating System: Linux Mint

### Additional context

Browser devtools:
Network Tab: No errors
Console:
```
ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118 Uncaught Error: Minified React error #130; visit [https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=](https://reactjs.org/docs/error-decoder.html?invariant=130&args%5B%5D=undefined&args%5B%5D=) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at yu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:107534)
at d (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:53373)
at b (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:54643)
at ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:56704
at ui (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:67706)
at Rs (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:113409)
at nu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98840)
at tu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98768)
at eu (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:98631)
at Gs (ea9e86d7e3257f2bf616fd7cb00c992e9982c903.js?meteor_js_resource=true:1118:95485)
```

**Comment by dudanogueira** [comment]
Hi! This might be related:
https://github.com/RocketChat/Rocket.Chat/issues/27395

Can you try that soltuion? Thanks!

**Comment by maudrid** [comment]
Thank you, yes this fixes it for me:
``sudo docker exec -ti rocketchat-mongo mongo rocketchat-mongo/rocketchat --eval "db.rocketchat_settings.deleteOne({ _id: 'Canned_Responses_Enable'  })"``

**Comment by minix-it** [comment]
> Thank you, yes this fixes it for me: `sudo docker exec -ti rocketchat-mongo mongo rocketchat-mongo/rocketchat --eval "db.rocketchat_settings.deleteOne({ _id: 'Canned_Responses_Enable' })"`

Hi there, how run this fix on SNAP ? Thankyou

**Comment by yash-rajpal** [comment]
For snap deployments we can access mongo using -
`rocketchat-server.mongo`

For a one liner, maybe please try -
`rocketchat-server.mongo rocketchat --eval "db.rocketchat_settings.deleteOne({ _id: 'Canned_Responses_Enable' })"`

**Comment by minix-it** [comment]
done in snap but not working anymore. records deleted 0

root@rocket:~# sudo rocketchat-server.mongo rocketchat --eval "db.rocketchat_settings.deleteOne({ _id: 'Canned_Responses_Enable' })"
MongoDB shell version v4.4.15
connecting to: mongodb://127.0.0.1:27017/rocketchat?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("c66657a3-a0e7-421b-b06c-e5133d12ad1b") }
MongoDB server version: 4.4.15
{ "acknowledged" : true, "deletedCount" : 0 }
root@rocket:~#

**Comment by minix-it** [comment]
![Cattura](https://user-images.githubusercontent.com/66483598/224533255-5a7b6705-0d18-4a07-8101-303ffc1909f5.PNG)
