### ISSUE TITLE
Microsoft Botframework Integration

### ISSUE THREAD

**Issue by flashguy22** [RocketChat/Rocket.Chat#2835]
Hey guys, any current plans to get integrated into Microsofts new Bot Framework? I just wrote my first Bot there and there is a Slack integration but unfortunately no custom oauth option. Maybe you should get in contact?

**Comment by flashguy22** [comment]
Maybe something like this could get us going: https://github.com/wballard/botbuilder-hipchat

**Comment by flashguy22** [comment]
Also an integration of wit.ai Bot Engine would be awesome. Maybe this can be done via hubot?
https://wit.ai/blog/2016/04/12/bot-engine

**Comment by flashguy22** [comment]
I was able to hook up our rocket.chat via hubot to the new wit.ai with it's amazing stories feature. 
You can see how I did it here: http://stackoverflow.com/questions/36621406/wit-ai-bot-engine-stories-connected-to-hubot/36646263#36646263
Please bear with me for the approach as I'm not a very skilled JS developer. This is more like a hack but it works for now to experiment with these new amazing features.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by sveroa** [comment]
Here is an exampe how to implement a channel with MS Bot framework
https://github.com/ritazh/botframework-hipchatchannel

**Comment by sumandipanshu** [comment]
Is there any example specific for BotFramework integration with Rocket chat?
