### ISSUE TITLE
docker install 

### ISSUE THREAD

**Issue by Finnimbrun** [RocketChat/Rocket.Chat#28356]
```
version: '2'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s);
        chown rocketchat:rocketchat /tmp/uploads
        "
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /datastore/rocketchat/file:/tmp/uploads
    environment:
      - PORT=3000
      - directConnection=true
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - REG_TOKEN=${REG_TOKEN}
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./data/db:/data/db
    command: mongod --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:5.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

```

rocketchat-rocketchat-1  | }
rocketchat-rocketchat-1  | Tried 6 times. Waiting 5 secs...
rocketchat-rocketchat-1  |
rocketchat-rocketchat-1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat-rocketchat-1  |                                              throw(ex);
rocketchat-rocketchat-1  |                                              ^
rocketchat-rocketchat-1  | errorClass [Error]: [An error occurred when creating an index for collection "users: not primary]
rocketchat-rocketchat-1  |     at Collection.createIndex (packages/mongo/collection.js:801:15)
rocketchat-rocketchat-1  |     at setupUsersCollection (packages/accounts-base/accounts_server.js:1776:9)
rocketchat-rocketchat-1  |     at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
rocketchat-rocketchat-1  |     at packages/accounts-base/server_main.js:7:12
rocketchat-rocketchat-1  |     at module (packages/accounts-base/server_main.js:19:31)
rocketchat-rocketchat-1  |     at fileEvaluate (packages/modules-runtime.js:336:7)
rocketchat-rocketchat-1  |     at Module.require (packages/modules-runtime.js:238:14)
rocketchat-rocketchat-1  |     at require (packages/modules-runtime.js:258:21)
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/packages/accounts-base.js:2192:15
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/packages/accounts-base.js:2199:3
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/boot.js:369:38
rocketchat-rocketchat-1  |     at Array.forEach (<anonymous>)
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/boot.js:210:21
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/boot.js:423:7
rocketchat-rocketchat-1  |     at Function.run (/app/bundle/programs/server/profile.js:256:14)
rocketchat-rocketchat-1  |     at /app/bundle/programs/server/boot.js:422:13 {
rocketchat-rocketchat-1  |   isClientSafe: true,
rocketchat-rocketchat-1  |   error: 'An error occurred when creating an index for collection "users: not primary',
rocketchat-rocketchat-1  |   reason: undefined,
rocketchat-rocketchat-1  |   details: undefined,
rocketchat-rocketchat-1  |   errorType: 'Meteor.Error'
rocketchat-rocketchat-1  | }
rocketchat-rocketchat-1  | Tried 7 times. Waiting 5 secs...

**Comment by Syntoxr** [comment]
Did you close because you found a solution? Could you share please?

**Comment by Finnimbrun** [comment]
For reference only

I encountered an issue when upgrading to a new version, so I backed up the MongoDB data and installed the new version of the container. Then, I restored the MongoDB data on the new container.

```
# backup
docker exec MongoDB_container_id sh -c 'mongodump --archive' > you_backup_filename.dump

docker pull registry.rocket.chat/rocketchat/rocket.chat:latest

docker compose stop rocketchat

docker compose rm rocketchat

docker compose up -d rocketchat

# restore
docker exec -i MongoDB_container_id  sh -c 'mongorestore --archive' < you_backup_filename.dump
```
