### ISSUE TITLE
Сan't change homepage

### ISSUE THREAD

**Issue by elfroot1337** [RocketChat/Rocket.Chat#28361]
I have empty field
![image](https://user-images.githubusercontent.com/127527062/224345774-eb5b61ba-0c96-4a89-934d-5722daaf4a7c.png)

and nothing changing
![image](https://user-images.githubusercontent.com/127527062/224345976-50309953-2bd4-43a7-a98e-eb7e5e7133c6.png)

**Comment by dudanogueira** [comment]
please, provide the required template information while opening an issue! What version are you running?

**Comment by elfroot1337** [comment]
Version 6.0.0 on docker

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/28586

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
