### ISSUE TITLE
OAuth App Authorization page crashes when a user is not logged in to Rocket.Chat already

### ISSUE THREAD

**Issue by abhinavkrin** [RocketChat/Rocket.Chat#28372]
### Description:
I was trying to log in to a test oauth app created at http://localhost:3000/admin/oauth-apps. When I was taken to the authorization page at http://localhost:3000/oauth/authorize, the page crashed and shows a blank screen. 

### Steps to reproduce:

1. Create an oauth app at http://localhost:3000/admin/oauth-apps
2. Configure to use the created oauth app at any platform. For testing purpose, I added it in the RC itself at http://localhost:3000/admin/settings/OAuth
3. Log in using that oauth option into Rocketchat

### Expected behavior:
The authorization page should show login options when the user is unauthenticated and the consent page otherwise.

### Actual behavior:
The page crashes when user is not logged in.

https://user-images.githubusercontent.com/15830206/224485399-43631b14-406e-49dc-8d09-6a608f0e28e2.mp4

![error_authorize](https://user-images.githubusercontent.com/15830206/224485406-0259de73-b240-4cfc-816c-5255a53ba2bf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0-develop
- Operating System: Debian 11
- Deployment Method: development version using yarn dsv
- Number of Running Instances: 1
- NodeJS Version: 14

### Client Setup Information

- Desktop App or Browser Version: Chrome 108.0.5359.124
- Operating System: Debian 11

### Additional context
The problem is actually with the "authorize" blaze template. In which it is trying to render loginButtons when user is not already authenticated. But it seems that it is not defined as the error log shows `No such templates: loginButtons`

### Relevant logs:
![error_authorize](https://user-images.githubusercontent.com/15830206/224485502-82c7dba4-65fb-4033-900d-ccaf03f5309e.png)

**Comment by Dev79844** [comment]
Hey
Can you assign me this issue?

**Comment by abhinavkrin** [comment]
Hey @Dev79844  This issue was recently fixed.
