### ISSUE TITLE
MessageType.render is deprecated. Use MessageType.message instead

### ISSUE THREAD

**Issue by lyz-code** [RocketChat/Rocket.Chat#28384]
### Description:

When we start the application we see the next trace in the logs:

```
MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
```

### Steps to reproduce:

1. Start the application
2. See error in the logs

### Expected behavior:

No error in the logs

### Server Setup Information:

- Version of Rocket.Chat Server:  6.0.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2 - x64
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: irrelevant
- Operating System: irrelevant

**Comment by lyz-code** [comment]
Hi @Tejas150 that would be awesome :)

**Comment by Devansht420** [comment]
hey @lyz-code if you can please give some information about where this function is causing an impact that'd be really helpful.

**Comment by Devansht420** [comment]
@nikolaydyankov you will see this warning in the logs regardless of using `iframe`.
