### ISSUE TITLE
'rocketchat_omnichannel_service_level_agreements' could not be created

### ISSUE THREAD

**Issue by lyz-code** [RocketChat/Rocket.Chat#28386]
### Description:

After upgrading to 6.0.0 we're seeing the next trace in our application logs:

```
Some indexes for collection 'rocketchat_omnichannel_service_level_agreements' could not be created
```

### Steps to reproduce:

1. Upgrade from 5.1.0 to 6.0.0
2. See error in the logs

### Expected behavior:

No error in the logs

### Server Setup Information:

- Version of Rocket.Chat Server:  6.0.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2 - x64
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: irrelevant
- Operating System: irrelevant

**Comment by murtaza98** [comment]
Hi, It's likely an issue with the data with your environment. Both the indexes we have for this collection are `unique` indexes which won't be created if you have duplicated data. Here's the [code](https://github.com/RocketChat/Rocket.Chat/blob/569103394df5313a92b31738b7eb96a2349060fa/apps/meteor/ee/server/models/raw/ServiceLevelAgreements.ts#L12) 

So, please verify if your SLA (Service level agreement's), `name` and `dueTimeInMinutes` is indeed unique and appropriately add those indexes back

**Comment by lyz-code** [comment]
Hi @murtaza98 , I don't remember setting any SLA or even using `omnichannel` (I sincerely don't know what it is). Can you guide me on how to verify if our SLA (Service level agreement's), `name` and `dueTimeInMinutes` is indeed unique and appropriately add those indexes back?

**Comment by murtaza98** [comment]
Sure, Can you goto Omnichannel settings -> SLA policy to verify it you have any active sla policies configured. Incase you're not using Rocket.Chat, the this shouldn't be relevant to you as this feature is only applicable to omnichannel conversations. Learn more about omnichannel feature within our docs -> https://docs.rocket.chat/use-rocket.chat/omnichannel

Here are the steps to verify:
1)
![image](https://user-images.githubusercontent.com/34130764/226614799-d3a8ad8b-b387-404a-a5ad-f245cd45a97b.png)
2) 
![image](https://user-images.githubusercontent.com/34130764/226614923-826ec9c3-7839-4d25-a63d-58885cc6b869.png)

**Comment by lyz-code** [comment]
I see that in our production instance we don't even  have Omnichannel enabled, as the testing instance was forked from production I find it very unlikely that it was enabled there either.

Do you want me to close this issue? other users that are not using this feature may run into the same error

**Comment by murtaza98** [comment]
Sure lets close it.
