### ISSUE TITLE
How to add autolinker to Custom Fileds?

### ISSUE THREAD

**Issue by Robbot-Zhao** [RocketChat/Rocket.Chat#28383]
### Description:

I added one custom field called phone number as discribed here https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/account-settings/custom-fields, and this extra info also shown in user info page, but it can not be clicked, or pasted. My question is how to add autolinker here as in message dialog?

### Steps to reproduce:

1. add new custom field, in my case it is a phone number
2. it is shown in userinfo page in app and web page
3. but it can not be clicked and act the right action as supposed.

### Expected behavior:

when I click the phone number, it can jump to phone call in smart phone.
### Actual behavior:
nothing happed.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dudanogueira** [comment]
Hi! Thanks for opening this issue.

Right now, you cannot change how the custom field is displayed.

What you can do, is to create an App that will read that visitor info, and render you a modal or context sidebar that can render the contents as you like, or even gather more information from a third party.

I will close this issue for now as this is can be implemented with apps and is not an issue exactly.
