### ISSUE TITLE
MongoDB error cursor.count is deprecated 

### ISSUE THREAD

**Issue by lyz-code** [RocketChat/Rocket.Chat#28385]
### Description:

After upgrading to 6.0.0 we're seeing the next trace in our application logs:

```
(node:8) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead
```

### Steps to reproduce:

1. Upgrade from 5.1.0 to 6.0.0
2. See error in the logs

### Expected behavior:

No error in the logs

### Server Setup Information:

- Version of Rocket.Chat Server:  6.0.0
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2 - x64
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: irrelevant
- Operating System: irrelevant

**Comment by Jyotiraditya24** [comment]
looking into it

**Comment by dudanogueira** [comment]
This is fine. I it's just a warning that it's deprecated :)

THanks for the report :)
