### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MadDog4533** [RocketChat/Rocket.Chat#28380]
### Description:

Getting an "Uncaught RangeError: Maximum call stack size exceeded" browser error and not able to open workplace settings after upgrading from 5.4.4

Could be related to issue #28354 I had the same problem upgrading the db. 

### Steps to reproduce:

1. Upgrade from 5.4.4
2. Login
3. Select Adminstration 3 dots
4. Select workspace
5. info page pops up
6. Selecting settings or any other tab does nothing and console report uncaught rangeerror

### Expected behavior:

Able to open workspace settings and tabs

### Actual behavior:

Nothing happens browser reports an error.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Ubuntu
- Deployment Method: manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Brave/Chrome
- Operating System: Windows 11

### Relevant logs:
![image](https://user-images.githubusercontent.com/11152887/224626630-d52d525f-60c4-470d-a18a-5666d5fc7a4f.png)

**Comment by hugocostadev** [comment]
closing in favor of Duplicate issue https://github.com/RocketChat/Rocket.Chat/issues/28581
