### ISSUE TITLE
Downgrade from 6.0 to latest 5.X

### ISSUE THREAD

**Issue by rrmt23** [RocketChat/Rocket.Chat#28410]
Hello!
In the new version, the important function "read status" was made paid.
We used it for 1 day and are wondering if it's possible to return to version 5.x?

Is it possible to migrate from version 6 back to 5 while keeping the current database (from version 6) in order to save all data, settings and chat history? 
5.4 -> 6.0 -> 5.4 with same DB?

Use in Docker with Mongo 5.0

Thank you!!!

**Comment by pierre-lehnen-rc** [comment]
Downgrading from a different major version is not as trivial as from one minor to another, as we run database migrations on it. You'll need to check the [migrations](https://github.com/RocketChat/Rocket.Chat/tree/develop/apps/meteor/server/startup/migrations) to see if there's any operation you need to undo.

**Comment by hugocostadev** [comment]
Hi @rrmt23 somethings that you should pay attention to if you want to downgrade manually: 

- Check the last migration on 5.x
- Check all migrations from that to the current 6.0 migrations
- Revert migrations one by one
- Rollback code
- revert in reverse order, so start from the latest migration, then the second last, and so on.

Since the GitHub is only for issues, If you still have some doubts or want to discuss more it, please
- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
OR
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by lsfoschine** [comment]
### Downgrade from Rocket.Chat version 6.x to 5.4.3

1. **Stop the container**:
   Stop the Rocket.Chat container. Make sure to replace `docker-compose.yaml` with the actual name of your container configuration file.
   ```bash
   docker compose -f docker-compose.yaml stop
   ```

2. **Edit the container configuration file**:
   Open the container configuration file (ex: `docker-compose.yaml`) and find the line that defines the Rocket.Chat image. Change it to the desired version (in this case, 5.4.3):
   ```yaml
   image: registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-5.4.3}
   ```

3. **Update the database version**:
   Start a mongo shell to access the Rocket.Chat database:
   ```bash
   mongo
   ```

   Inside the mongo shell, select the appropriate database (replace `<database name>` with the actual name of your Rocket.Chat database):
   ```javascript
   use <database name>
   ```

   Then, update the migration version to match version 5.4.3 (281 in this case):
   ```javascript
   db.migrations.updateOne({ _id: 'control' }, { $set: { version: 281, locked: false } });
   ```

4. **Start the container**:
   Now that the configuration has been adjusted, start the Rocket.Chat container again:
   ```bash
   docker-compose -f docker-compose.yaml up -d
   ```

5. **Verify everything is working correctly**:
   Check if the container is running and inspect the logs to ensure there are no issues:
   ```bash
   docker ps -a
   docker logs -f <container ID>
   ```
   Make sure to replace `<container ID>` with the actual ID of your container.

This procedure should downgrade the Rocket.Chat version from 6.x to 5.4.3. Make sure to back up any important data before making any significant changes to your production environment.
