### ISSUE TITLE
Entering wrong old password while changing password shows 'undefined' message

### ISSUE THREAD

**Issue by Heluhan** [RocketChat/Rocket.Chat#28422]
### Description:

When trying to change the password, if the user enters the wrong old password, the message shown on the top-right corner is "undefined".

### Steps to reproduce:

1. Log in to the Rocket.Chat account.
2. Navigate to My Account.
3. Navigate to Profile.
4. Enter a new password twice.
5. Enter the wrong old password and click on "Save Changes".

### Expected behavior:

The system should prompt the user with an error message saying that the old password is incorrect.

### Actual behavior:

The system shows "undefined" message on the top-right corner.

<img width="237" alt="Screen Shot 2023-03-14 at 5 36 55 PM" src="https://user-images.githubusercontent.com/106983269/225143969-e1a16786-6a14-4c4e-b392-9187ca0a4d5a.png">

### Client Setup Information

- Desktop App or Browser Version: 3.9.19 
- Operating System: MacOS 12.5.1 (21G83)

### Additional context

I'm unsure if this issue is due to using an old password that doesn't match or if it's because I logged in with OAuth, which means I never had an old password.

**Comment by XshubhamX** [comment]
Fixed in the latest version 
@Heluhan

**Comment by dudanogueira** [comment]
thanks for the report!

before reporting an issue, try to always test in latest version (http://open.rocket.chat always latests commits)
