### ISSUE TITLE
bug: No impact of confirm password field

### ISSUE THREAD

**Issue by XshubhamX** [RocketChat/Rocket.Chat#28425]
Description:
Ui doesn't complain to confirm password if user has not entered anything in that field. Video will make more sense.

https://user-images.githubusercontent.com/63532716/225240596-cccb3573-91e6-485a-af66-a30c6a2bff0a.mov

Steps to reproduce:

- Write new password 
- Save Changes

Expected behaviour:

- UI should complain to confirm password

Actual behavior:

- Password saved

Client Setup Information

Chrome
Operating System: macOS
Version - 6.0.0

**Comment by rishivyas24** [comment]
Can you please assign this bug to me? I just want to work on it.

**Comment by XshubhamX** [comment]
@rishivyas24 lets just wait for the approval, this issue can also be in the the roadmap.

**Comment by rishivyas24** [comment]
ok

**Comment by XshubhamX** [comment]
Working on it @yash-rajpal
