### ISSUE TITLE
bug: Emoji not seen when selected from toolbar

### ISSUE THREAD

**Issue by XshubhamX** [RocketChat/Rocket.Chat#28421]
Description:
When selecting an emoji from the emoji bar, a blank space is not added by default, due to which the emoji is not rendered. Check video for more clarity.

https://user-images.githubusercontent.com/63532716/225138301-f220a4ab-73f7-4803-aa49-bc72d8238eae.mov

Steps to reproduce:

- Write a text and select emoji.
- Send the message

Expected behaviour:

- Emoji should be shown

Actual behavior:

- No Emoji on screen

Client Setup Information

Chrome
Operating System: macOS
Version - 6.0.0

**Comment by yash-rajpal** [comment]
This is a duplicated issue, we will handle this issue with #28193 and #28216 will fix this problem.

Thanks!
