### ISSUE TITLE
Calendar Plugin

### ISSUE THREAD

**Issue by dvmorris** [RocketChat/Rocket.Chat#2843]
Is there a calendar plugin for Rocket.Chat? 

I'm looking for something akin to what GroupMe supports (http://blog.groupme.com/post/110564177859/introducing-calendar-we-are-thrilled-to-announce), or Glip (https://glip.zendesk.com/hc/en-us/articles/202321744-Calendar-App)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
