### ISSUE TITLE
Rocket.Chat Android apps are forcefully logged out after making CSS changes

### ISSUE THREAD

**Issue by chotaire** [RocketChat/Rocket.Chat#28444]
### Description:

In Rocket.Chat 6.0.0, when making any change under Workspace -> Settings -> Layout -> Custom CSS, it seems that all users are logged out of their Rocket.Chat Android app sessions when they open the app thereafter. 

### Steps to reproduce:

1. Make any change under Workspace -> Settings -> Layout -> Custom CSS
2. Open Rocket.Chat app on Android
3. Verify you are being logged out

### Expected behavior:

Phone app users shouldn't be logged out, as CSS changes do not have any effect on the phone app at all. Instead, web browser sessions should be forcefully hard-reloaded, the same way it happens when updating Rocket.Chat (dockerized) to a newer version. 

### Actual behavior:

Phone app users are logged out after every change made to CSS. If a user is using multiple phones, they'll all be logged out. I did not receive any similar reports from iOS users.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Rocket.Chat Android App v4.36.0.38053
- Operating System: Android 13

**Comment by bulkinav** [comment]
In fact, this problem occurs when you need to enter TOTP code when your making changes in Settings. After that, there is a logout from all other devices.

**Comment by david-uhlig** [comment]
> In fact, this problem occurs when you need to enter TOTP code when your making changes in Settings. After that, there is a logout from all other devices.

Can confirm this. Still happens on 6.5.0

**Comment by bulkinav** [comment]
@sampaiodiego please review this issue, because it is very intrusive and brings a lot of inconvenience. I mentioned you because I don't know who can tackle this problem from Rocket team.

**Comment by chotaire** [comment]
I've no longer received reports of other (non-admin) users being logged out. Can someone confirm that any users other than yourself are being logged after making changes to CSS (or as @bulkinav mentioned, when doing any change in Settings that requires a TOTP verification)? Actually, I might have to rename this issue and alter its entire description if it's the same code throughout Settings causing the logout.

**Comment by david-uhlig** [comment]
@sampaiodiego happens to me without 2FA. I change some admin setting, have to enter my password to confirm and get logged out afterward on the Android app and other web browser sessions. I'm not immediately logged out of the current web session though.

**Comment by chotaire** [comment]
Same here, it's just asking for the user password.

**Comment by sampaiodiego** [comment]
alright, I've found the issue.. it goes back to version 5.4.3 .. I'm still trying to understand the reasoning behind the change that introduced the issue.. I'll get back when have something else to share

**Comment by sampaiodiego** [comment]
JFYI the fix has been published in 6.5.4 release

**Comment by chotaire** [comment]
Just to confirm that this is normal, after updating the docker version of Rocket.Chat, the web ui will no longer force-reload. Is this intended behavior?

**Comment by sampaiodiego** [comment]
@chotaire there is a random delay now.. this was done to help hammering the backend with all clients reloading at the time..

**Comment by paulchen** [comment]
> Just to confirm that this is normal, after updating the docker version of Rocket.Chat, the web ui will no longer force-reload. Is this intended behavior?

To my knowledge, this was already introduced some time ago in #30858.
