### ISSUE TITLE
When an online user is deactivated, their online status remains online.

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat#28441]
### Description:

When an online user is deactivated, their online status remains online.

### Steps to reproduce:
1. execute curl with
```
curl -H "X-Auth-Token: ***" \
     -H "X-User-Id: ***" \
     -H "Content-type:application/json" \
     https://server/api/v1/users.update \
     -d '{"userId": "***", "data": { "active": false}}'
```
2. Open Rocket.Chat and you will see this user with online status.

### Expected behavior:

Offline user status

### Actual behavior:

Online user status

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.4
- Operating System:  Oracle Linux Server release 8.6
- Deployment Method: docker
- Number of Running Instances: 22
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.15

## Additional context

It does not occurs with every deactivation.

### Relevant logs:
From MongoDB rocketchat users collection for that user:
```
        "status" : "online",
        "active" : false,
        "statusDefault" : "online",
        "statusConnection" : "online",

```

**Comment by njiddasalifu** [comment]
Can you give more details on this issue

**Comment by Kot-o-pes** [comment]
possibly related to https://github.com/RocketChat/Rocket.Chat/issues/27468

**Comment by dudanogueira** [comment]
Hi!

Can you replicate this in 6.0.0?

**Comment by hugocostadev** [comment]
Are you doing this call thought an APP?
