### ISSUE TITLE
Messagebox duplicates unsent messages when switching between channels twice

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#28468]
### Description:

[I think I saw this particular one before in Github but could not find it now. Only those that concerned already sent messages. Please close if duplicate.]

Messagebox duplicates unsent messages after switching between two channels twice.

This is reproducible for time being at open.rocket.chat.

### Steps to reproduce:

1. Start typing on any channel into the messagebox. Do not press enter.
2. Switch to other channel and back twice.

### Expected behavior:

The messagebox should remain empty on the other channel.

### Actual behavior:

The message from the first channel gets copied to the messagebox on the other channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 5.0.15
- NodeJS Version: 14.21.2
- MongoDB Version: 5.5

### Client Setup Information

- Desktop App or Browser Version: Firefox, Mac client, probably others too

**Comment by ShreyanshKeshav33** [comment]
Hey Can I Take this issue?

**Comment by joseph-belmonte** [comment]
> [I think I saw this particular one before in Github but could not find it now. Only those that are concerned already sent messages. Please close if duplicate.]

This could be related to https://github.com/RocketChat/Rocket.Chat/issues/28112 Is that the one you were thinking of?

**Comment by Gummikavalier** [comment]
> > [I think I saw this particular one before in Github but could not find it now. Only those that are concerned already sent messages. Please close if duplicate.]
> 
> This could be related to #28112 Is that the one you were thinking of?

Exactly that was what I was looking for. I'll close this one. We were able to replicate using any channel type though.
