### ISSUE TITLE
The hyperlink does not open in a new web browser tab (File description, Pinned Messages, Announcement)

### ISSUE THREAD

**Issue by hDw1z** [RocketChat/Rocket.Chat#28460]
### Description:

The hyperlink does not open in a new web browser tab if it is located in the following places:
- File description;
- Pinned Messages;
- Announcement.

### Steps to reproduce:

1. Upload a file to send. Insert a hyperlink in the "File description" field (1)
![image](https://user-images.githubusercontent.com/89155702/225821194-0d23998a-e836-4aff-99f8-7813a1b7e3f8.png)

2. Send the file.

3. The hyperlink (1) does not open in a new web browser tab:
![image](https://user-images.githubusercontent.com/89155702/225820288-42e4cbd3-8550-42cb-8bd1-6500f0932283.png)

### Expected behavior:

The hyperlink opens in a new web browser tab if it is located in the following places:
- File description;
- Pinned Messages;
- Announcement.

### Actual behavior:

The hyperlink does not open in a new web browser tab if it is located in the following places:
- File description;
- Pinned Messages;
- Announcement.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Ubuntu Server 22.04.1 LTS (Jammy Jellyfish) x64
- Deployment Method: Docker image
- Number of Running Instances: 1
- NodeJS Version: 14.19.3
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Any web browser, Google Chrome 105.0.5195.125 (Official Build) (64-bit)
- Operating System: Any, Debian 11 x64.

**Comment by grthr** [comment]
Links in the room topic also do not open in a new tab.

The behavior is quite annoying, as this is not consistent with links in normal chat messages.

**Comment by grthr** [comment]
might be related to #28167

**Comment by yash-rajpal** [comment]
Hey @hDw1z! This works fine on the new 6.0.0 release. I see you are using 5.4.0 version, can you please confirm if you are using new message template or old one?

Thanks!

**Comment by saadkhan011** [comment]
Hi hdw1z,
I want to work on this issue if it is open please assign it to me

**Comment by yash-rajpal** [comment]
Hey @saadkhan011! We do not assign issues, please feel free to open a PR fixing the issue. Thanks!

**Comment by hDw1z** [comment]
Hi, @yash-rajpal
> This works fine on the new 6.0.0 release
Right. Thanks.
