### ISSUE TITLE
Show all @all-messages of a channel

### ISSUE THREAD

**Issue by punkrock** [RocketChat/Rocket.Chat#2847]
Is it possible to have an show all @all-messages of a channel? This would be much helpful to catch important messages.

**Comment by graywolf336** [comment]
Do they show up in the mentions tab on the right hand side?

**Comment by punkrock** [comment]
Nope, unfortunately not.

**Comment by graywolf336** [comment]
Do you think that would be a good enough place to put them?

**Comment by punkrock** [comment]
Hmm, not really. But a seperate button seems to me too much. Maybe as a link on the top within the slide-window which opens, if you click on the mentions-button. S.th. like "Show all mentions" (including the @all's) and beside this link "Show only @all's". That would be very cool.

**Comment by lvh1** [comment]
In the meantime you could use the search function to search for `mention:all`

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
