### ISSUE TITLE
Cannot explore apps in marketplace

### ISSUE THREAD

**Issue by SereneWong** [RocketChat/Rocket.Chat#28484]
I want to install BigBlue buttons so that i can initiate an video call,but when i click the marketplace ,it says "Connection error
Cannot connect to internet or your workspace may be an offline install."
![rocketchat](https://user-images.githubusercontent.com/44776086/226082053-e7abfaab-0825-4e1f-92cd-0471a740c58a.png)

**Comment by SereneWong** [comment]
network problem? or video call is just an enterprise function?
my edition is 30 day free trial(formerly free edition),self deployed and managed on my privite server.

**Comment by SereneWong** [comment]
Can anybody help me?

**Comment by stleitner** [comment]
Check your servers DNS settings

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest releases.

If you are still facing it, give us more info and you can reopen this issue

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
