### ISSUE TITLE
Message Timestamps - Improvement

### ISSUE THREAD

**Issue by edwardmuel** [RocketChat/Rocket.Chat#2848]
Your Rocket.Chat version: 0.25.0 (36f23ce4528a302cc927c8bfc4166ce875202b46)

Messages grouped within a specific time period have no timestamps visible to the user (other than the first message in the group)
When looking through message history, how is a user supposed to know exactly when a specific message was sent?
Slack shows timestamps for grouped messages when hovering over the message. Slack also displays a more complete date when hovering over any timestamp.

Clients currently receive but do not use the full timestamp for non-edited messages.

``` HTML
<li id="xxx" class="message sequential   own" data-username="edward" data-date="April 12, 2016" data-timestamp="1460464347631">
    <a class="thumb user-card-message" href="#" data-username="edward" tabindex="1">
        <div class="avatar">
            <div class="avatar-image" style="background-image:url(/avatar/edward.jpg?_dc=0);"></div>
        </div>
    </a>
    <a class="user user-card-message" href="#" data-username="edward" tabindex="1">edward</a>
    <span class="info">
        <span class="time">7:32 AM</span>
        <div class="message-cog-container">
            <i class="icon-cog message-cog" aria-label="Actions"></i>
        </div>
    </span>
    <div class="body" dir="auto">
        that would probably work for watching for changes
    </div>
    <ul class="reactions hidden">
        <li class="add-reaction">
            <span class="icon-people-plus"></span>
        </li>
    </ul>
</li>
```

![image](https://cloud.githubusercontent.com/assets/15653318/14462009/aa44dd3e-008a-11e6-869e-afbd3b20880b.png)

**Comment by Hudell** [comment]
The current version of Rocket.Chat already shows the full date when hovering the message timestamp.
