### ISSUE TITLE
Message Edit Information - Disappears on Sequential Messages

### ISSUE THREAD

**Issue by edwardmuel** [RocketChat/Rocket.Chat#2849]
Your Rocket.Chat version: 0.25.0 (36f23ce4528a302cc927c8bfc4166ce875202b46)

Timestamps are displayed when hovering over the "edited by user" text using a span title.
When a message in a message group is edited, the message timestamp cannot be viewed. Instead, when the message is hovered over, the edit information disappears.

![image](https://cloud.githubusercontent.com/assets/15653318/14463413/75d75ada-0090-11e6-86bf-d1f831207c15.png)

The span title is still in the HTML, but it is hidden by `message-cog-container`.

``` HTML
<li id="xxx" class="message sequential   own" data-username="edward" data-date="April 12, 2016" data-timestamp="1460470143638">
    <a class="thumb user-card-message" href="#" data-username="edward" tabindex="1">
        <div class="avatar">
            <div class="avatar-image" style="background-image:url(/avatar/edward.jpg?_dc=0);"></div>
        </div>
    </a>
    <a class="user user-card-message" href="#" data-username="edward" tabindex="1">edward</a>
    <span class="info">
        <span title="edited at April 12, 2016 9:09 AM by edward" class="time">
            9:09 AM
        </span>
        <span class="edited" title="edited at April 12, 2016 9:09 AM by edward">
            <i class="icon-edit" aria-label="Edited"></i>
            by
            <a class="thumb thumb-small user-card-message" href="#" data-username="edward" tabindex="1">
                <div class="avatar">
                    <div class="avatar-image" style="background-image:url(/avatar/edward.jpg?_dc=0);"></div>
                </div>
            </a>
        </span>
        <div class="message-cog-container">
            <i class="icon-cog message-cog" aria-label="Actions"></i>
        </div>
    </span>
    <div class="body" dir="auto">
        test
    </div>
    <ul class="reactions hidden">
        <li class="add-reaction">
            <span class="icon-people-plus"></span>
        </li>
    </ul>
</li>
```

**Comment by engelgabriel** [comment]
We have hidden ir because of the space is not always enough for the information in all languages.
Since sequential messages are only grouped in a 5 minutes timeframe, we thought that this is not a big deal. We welcome design suggestions to fix this problem

**Comment by edwardmuel** [comment]
Would adding another button to the cog menu for displaying the information be a good solution?

**Comment by engelgabriel** [comment]
Thats our idea too. We just haven't done because the priority for this is currently low.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
