### ISSUE TITLE
Layout > Custom Scripts > Custom Script for Logged In Users problem

### ISSUE THREAD

**Issue by KimJohann** [RocketChat/Rocket.Chat#28496]
Trying to use "Layout > Custom Scripts > Custom Script for Logged In Users" on the admin page while using rocketchat. However, even if I enter the JavaScript code, I have to refresh the page for it to work.
For example
if(window.location.pathname == '/account/profile'){ alert("Welcome")
} code, it doesn't work when you move to the page. It works only when I refresh the page. How to solve this problem?

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.0
- Operating System: ubuntu  20.04
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enable oplog
- NodeJS Version: 14.18.3
- MongoDB Version: 5.0.15

**Comment by dudanogueira** [comment]
Hi! This is probably you :)

https://forums.rocket.chat/t/layout-custom-scripts-custom-script-for-logged-in-users-problem/16264

answer:
`I believe this working as expected. That script will only run after the first log in, not on all page changes.`

Thanks!
