### ISSUE TITLE
AutoScroll Issue During Live Chat Message Arrival

### ISSUE THREAD

**Issue by bhardwajdisha** [RocketChat/Rocket.Chat#28502]
### Description:
During livechat, the auto scroll feature doesn't comes into action at the time of arrival of new message

### Steps to reproduce:

1. Go to https://open.rocket.chat/livechat
2. Continue Chatting and notice the auto scroll behavior at chat window

### Expected behavior:
Auto Scroll feature should work smoothly

### Actual behavior:
Auto Scroll feature not working properly and smoothly

https://user-images.githubusercontent.com/67470541/226453362-3b021d21-588a-481b-ba00-d4527ceaef7b.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Ubuntu
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: rs0
- NodeJS Version: v14.21.2
- MongoDB Version: v5.0.5

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 110.0.5481.104
- Operating System: Windows 11 with WSL

**Comment by bhardwajdisha** [comment]
Hi, @dudanogueira I would like to work on this issue

**Comment by Mustafa-Azad025** [comment]
Hi @bhardwajdisha , Can you pls provide the path of whole code of above url in repo ?

**Comment by bhardwajdisha** [comment]
Hi @Mustafa-Azad025, you can find the code for livechat inside packages folder

**Comment by murtaza98** [comment]
Possibly fixed by https://github.com/RocketChat/Rocket.Chat/pull/28547
