### ISSUE TITLE
Can't install App from Marketplace (Enterprise)

### ISSUE THREAD

**Issue by xcpdq** [RocketChat/Rocket.Chat#28546]
### Description:

We have an Enterprise edition of Rocket Chat. I want to install Google Meet from the Marketplace but I am getting the message "Google Meet is a free application available only for Enterprise Edition. Upgrade to access all new features." and there's a Cancel button and "Start your 30-day free trial" . 

### Steps to reproduce:

1. Go to Marketplace
2. Click on Enterprise
3. Click on Google Meet

### Expected behavior:

To be able to install the Google Meet app into our RC.

### Actual behavior:

The message "Google Meet is a free application available only for Enterprise Edition. Upgrade to access all new features." and there's a Cancel button and "Start your 30-day free trial" . 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 16.13
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: 3.8.16
![Rocket Chat_screenshot](https://user-images.githubusercontent.com/18256939/226890942-930d9376-55b0-4d91-9487-0a6e404c4c82.png)

- Operating System: Windows 10

### Additional context

N/A

### Relevant logs:

N/A

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

If you are an Enterprise client, could you please open a ticket for that? By doing so we'll have more information about your server and we'll be able to help you better. Thanks! 

I'll close for now, if you have more insights, feel free to reopen! 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
