### ISSUE TITLE
Tagging/Mentioning user while simultaneously uploading file does not correctly tag or mention

### ISSUE THREAD

**Issue by EnableServices** [RocketChat/Rocket.Chat#28545]
### Description:

Tagging/Mentioning user while simultaneously uploading file does not correctly tag or mention

### Steps to reproduce:

1. Go to channel and start writing message, making sure to @ a user
2. Hit attachment button and choose file
3. Hit send

### Expected behavior:

File is uploaded and message correctly links to user as a mention

### Actual behavior:

File is uploaded but mention is just normal text, no mention

### Server Setup Information:

6.0.0

### Client Setup Information

Firefox Dev Edition latest version

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of:  https://github.com/RocketChat/Rocket.Chat/issues/25918

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
