### ISSUE TITLE
New Custom User doesn't send id information

### ISSUE THREAD

**Issue by Montel** [RocketChat/Rocket.Chat#28542]
### Description:
I am the Ruqola developer 

When we use administration module we can add custom user
=> we can define name and status
(for example "test5"/"online)

but when RC server send info about new "Custom User" it doesn't provide "_id" element
=> We can't know this identifier.
This identifier is necessary for using it in RC client or ruqola (otherwise we need to restart it)

but default we receive
{"collection":"stream-notify-logged","fields":{"args":[{"userStatusData":{"name":"test9","statusType":"busy"}}],"eventName":"updateCustomUserStatus"},"id":"id","msg":"changed"}

=> missing "_id"

When custom user is updated it's ok
see
{"userStatusData":{"_id":"641aa7c0402d8abf0db86816","name":"test2","statusType":"away"}}

Could you add missing "_id" element when we create custom user please ?

Thanks.

**Comment by Montel** [comment]
RC 5.4.0 and RC 6.0

**Comment by Montel** [comment]
Ping ? no news ?.

**Comment by hugocostadev** [comment]
Sorry, are you using it with an app, webhook, RC server ... ?  Can you detail a lit bit more your issue, please

**Comment by Montel** [comment]
I develop ruqola (kde rocketchat apps). But it when we add a new custom user info RC doesn't send _id
=> we can't update information in apps.
Same in RC client , we need to fetch all list, but it will better to send _id => we can update it directly.
