### ISSUE TITLE
Cannot connect to Rocket

### ISSUE THREAD

**Issue by Raquel-Nob** [RocketChat/Rocket.Chat#28553]
We cannot get a connection to our Rocket.Chat via our PCs or phone apps. It is just "Waiting for server connection," endlessly. We've tried reloading, re-installing, and nothing is working.

**Comment by dudanogueira** [comment]
Hi! Your server is probably offline.

[if it's hosted in our cloud (like mycompany.rocket.chat) we can help you out here](https://support.rocket.chat/). Otherwise, you will need to reach out for your system administrador.

I'll close it for now.
