### ISSUE TITLE
Messages disappear or get reordered on the channel

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#28573]
### Description:

This is a stub of an issue where messages disappear on channel and in threads after the messages have been edited or reacted to.

The issue happens only if you are running more than one node in a monolithic configuration. More nodes you have in use, more likely it is to reappear.

### Steps to reproduce:

1. Run at least two instances (RC processes). (Important!)
2. React to a message already existing on any channel apart of the first message on the channel or thread.
3. Remove the reaction directly from reaction button below the message (the icon showing your reaction).
4. Add the reaction again and then remove it again from below the message.

### Expected behavior:

Repeated reacting and unreacting using the reaction icon beneath the message works as normal.

### Actual behavior:

The unreacted message relocates to the top of the channel or thread.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Latest Chrome and Firefox

### Additional context

On the channel / thread where this issue happens it is enough to either react to a message or remove an existing reaction.

In the thread with the issue active it is enough to react to any message on it, and after you remove that same reaction, the issue triggers.

The message that has been edited or reacted to moves to the top in the thread, just beneath the very first message of the thread. A line marking the day change also appears before and after the message that was relocated.

In the message options we use following time formats:
Time format: `HH:mm`
Date format: `dddd, D MMMM YYYY`
Time and date format: `YYYY MMM DD, HH:mm`

After I stopped all nodes one by one the issue persisted until there was only one node left. After that we could not replicate the issue using one node.

Important find: This issue triggers only when your are using the direct reaction buttons (the ones that show existing reactions) under the message. It does not trigger if you use the emoji picker from the end of the message line to add or remove your reaction. Why it does not trigger when you are running only one instance is a good question though.
Update: It happens every time even when using emoji picker if you use default `Use REST instead of websocket for Meteor calls`.

**Comment by hugocostadev** [comment]
HI @Gummikavalier ! We are having a problem reproducing this... can you give us more details about the way that the server is setup? Thanks

**Comment by Gummikavalier** [comment]
Hi, yes.

Vmware as the hypervisor.
6 x 2.6 GHz Intel Xeon cores
32 GB memory
SSD enterprise storage system with over 1 GB/s throughput for read and write, minimum 500 GB/s at any given time

Nothing else on that same node. Purpose built for rocketchat monolithic, so it runs only mongo, nodejs and nginx processes. Our RHEL installations are quite bare to save cycles in the datacenter, we install only the required dependencies for any service.

I tested with 13ms and under 1ms latencies, but the issue remains also with under 1ms.

**Comment by Gummikavalier** [comment]
I was commenting my findings at openrocketchat.

If you run only one instance, shift-reload, and try to trigger the issue (which is not possible with one instance at all) you'll get only this harmless error (but only once):

```
Uncaught TypeError: t.current is null
```

But if you start a second instance, you'll start getting this error:
```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule b72588aceeff5772be12d1a7d577ba65b69458dd.js:1310:97033
```

**Comment by Gummikavalier** [comment]
So to sum it up you probably use date-fns module only when running multiple instances.

Our NPM version is the correct 6.14.17 mentioned on the RC GitHub release page.

**Comment by tars21** [comment]
The same applies to our setup as well.
Thanks for the analysis so far, @Gummikavalier 👏 

**Server Setup Information:**
Version of Rocket.Chat Server: 6.1.0
Operating System: Debian 11
Deployment Method: tar
Number of Running Instances: 3
DB Replicaset Oplog: Yes
NodeJS Version: 14.21.3
NPM Version: 6.14.17
MongoDB Version: 5.0

**Comment by Gummikavalier** [comment]
I had a go with RC 6.1.0 and the issue triggers now also when you add or remove reactions using the emoji picker at the end of the message view. In RC 6.0.1 it was consistent that it did not happen using that.

**Comment by Gummikavalier** [comment]
The fix is brewing:
https://github.com/RocketChat/Rocket.Chat/pull/28770

**Comment by Gummikavalier** [comment]
I confirm that the issue does not trigger anymore in RC 6.1.1 neither using websockets or REST. Thanks! :heart:

**Comment by Gummikavalier** [comment]
Tail for this case: We still get reports of missing / relocated messages from our users. I'm not yet sure if this is by non-refreshed clients or the same issue triggered by reactions or some other operation this time.

**Comment by Gummikavalier** [comment]
Reactions bug is fixed for good I think, but we still have this another one. This is probably not related but his is on FYI basis now here:
https://github.com/RocketChat/Rocket.Chat/issues/28824#issuecomment-1499263299
