### ISSUE TITLE
Enterprise version custom Oauth provider is missing required configuration options

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#28571]
### Description:

RC 6.0.x is missing all configuration options for custom Oauth providers.

Also the docs don't mention any options:
https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/oauth

The minimum set for custom Oauth / OpenID connect provider options would contain at least these:
clientid
client_secret
url of the specified openidprovider

### Steps to reproduce:

1. Go to Admin -> Settings -> Oauth
2. Choose an existing custom Oauth provider or create a new one

### Expected behavior:

You should have plenty of options to define critical attributes

### Actual behavior:

All options apart from Roles to Sync are missing.

![Screenshot from 2023-03-23 09-44-01](https://user-images.githubusercontent.com/6958942/227137225-891d9342-8b43-420f-a631-88d68da7c5ca.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Any browser

### Additional context

This functionality is absolutely vital for Enterprise users as well as testing authentication scenarios using test environments.

**Comment by Gummikavalier** [comment]
Closing this one. The issue was that any existing Enterprise and testing environment and new non-enterprise configuration scheme does comply with the latest changes into RC.

However it is possible to create a completely new configuration in Enterprise that should workaround this issue.

**Comment by xoxys** [comment]
Seriously... That's such a bad UX.... Old providers are still working but can't be changed anymore, and we have to create a new one to get back control over it?

**Comment by Gummikavalier** [comment]
Yes, that indeed needs a new config, then deletion of the old one. This is bit of a shame particularly because doing these is always bit risky if you haven't documented all settings properly, and sometimes it is just best to not document such things as shared secrets anyway.

**Comment by Gummikavalier** [comment]
Seems to be fixed for old configs in RC 6.3.0. :+1:
