### ISSUE TITLE
New permission request to restrict users from viewing other channels

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#2857]
Your Rocket.Chat version: 0.26.0

Hey guys, we have a pretty important feature request / bug here (for us and how we use rocketchat).  We use rocket.chat to talk to some of our privileged customers.  We do this by creating a "customer" role and setting a user to that role.  The only permission we allow them is the "view c-room" permission:
![settings](https://cloud.githubusercontent.com/assets/10718586/14475166/d980e664-00bd-11e6-995b-0cbcdd794574.JPG)

This way we can add them to a channel and in the UI they only see the channels they are apart of.  One big problem for us is that these users can click the "more channels..." button and view any other public channels including other customers channels.  You can imagine the headache this might cause and we would like to get in front of it.  

![view c room](https://cloud.githubusercontent.com/assets/10718586/14475204/0ca07906-00be-11e6-8628-3a6d17c2cc5f.JPG)

**Solution**
Implement a new permission that allows us to disable the "More channels" toggle so a user wouldn't be able to so easily access / view another channel.

**Comment by twhiting** [comment]
I found a solution for us.  Instead of adding our customers into public channels we simply moved them over to private channels instead.  Setting our customer role to _view-p-room_ only allows a customer to see channels they are apart of and nothing else.

I'm not going to close this issue though because I think that permission may still be useful, I'll leave that up to you guys though.

**Comment by marceloschmidt** [comment]
That's the solution I'd go for anyway. Channels are always public, while private groups are, well, private ;) There are a few other issues regarding permissions, so we'll have quite a few more customized options. I'll close this one.

**Comment by ulope** [comment]
Just FYI: This can be solved even easier with the `guest` role (which might not have existed when this issue was created). Guests can by default only view rooms they have been invited to.
