### ISSUE TITLE
Admin menu not working (reopen #28543)

### ISSUE THREAD

**Issue by jatoko** [RocketChat/Rocket.Chat#28581]
### Description:
Reopening issue https://github.com/RocketChat/Rocket.Chat/issues/28543

Clicking menu items in admin menu does not work. Getting "uncaught range error" in RC Desktop client and  "too much recursion" error in Firefox web client.

I can reproduce this error **every time** in both the RC Desktop Client and browser client.

### Steps to reproduce:

Click "Workspace" -> click any menu item, e.g., "Settings" -> not working

### Expected behavior:

Clicking a menu item should load the respective site.

### Actual behavior:

Nothing happens, error in console: 

In RC Desktop client: 
```
Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at y.match (b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14878)
    at b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14736
    at i (b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14107)
    at b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14773
    at i (b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14107)
    at b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14773
    at i (b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14107)
    at b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14773
    at i (b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539:14107)
```

In Firefox web client:
```
Uncaught InternalError: too much recursion
    match https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    middleware https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    i https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    middleware https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    i https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    middleware https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    i https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
    middleware https://XXX/b72588aceeff5772be12d1a7d577ba65b69458dd.js?meteor_js_resource=true:1539
```

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: n.a.
- NodeJS Version: n.a.
- MongoDB Version: 5.0.4

### Client Setup Information

- Desktop App or Browser Version: RC client 3.8.17 and Firefox 111
- Operating System: Win10

**Comment by hugocostadev** [comment]
Hi @jatoko sorry, I could not reproduce it here, I'll try again, next time you can reopen the same issue to keep history. I'll bring updates sson, thanks

**Comment by hugocostadev** [comment]
I cannot reproduce yet... Did you tried to open in a different browser or open in a incognito window? Try to clear the application data (cache and storage), please. And let me know

**Comment by jatoko** [comment]
I have cleared the cache of both RC Desktop Client and browser. I also used Chrome and Firefox using both normal and private browsing mode. I asked a colleague to verify the issue, finding the following:

- The error happens when calling / and then use the menu to open the admin menu under /admin
- The error does **not** happen when we call /admin directly

I hope this helps.

**Comment by MadDog4533** [comment]
Hello, I have the same issue: #28380 

The only way to use the workspace administration I've found is by refreshing when the URI is /admin/*
Are you using a non-root web URL by chance? 

For instance, my install is not https://chat.example.com/ but I have rocket's webroot bound to https://example.com/chat/
so for me admin is on: /chat/admin/
I'm thinking that could possibly be the problem since the debugger points to this line with the decodeURIComponent.

`this.regexp.exec(decodeURIComponent(i));`

**Comment by jatoko** [comment]
Thanks for confirming the issue. 

> The only way to use the workspace administration I've found is by refreshing when the URI is /admin/* Are you using a non-root web URL by chance?
> 
> For instance, my install is not https://chat.example.com/ but I have rocket's webroot bound to https://example.com/chat/ so for me admin is on: /chat/admin/ 

Yes, we run RC using a non-root web URL, just as you do on https://example.com/chat/. For us, it is also /chat/admin using a reverse proxy. This setup has worked flawlessly under RC v5.

**Comment by hugocostadev** [comment]
Thank you guys, I'll address it internally and fix ASAP

**Comment by hugocostadev** [comment]
**NOTE:** Running in a subfolder has been officially deprecated. It will no longer be supported in the upcoming 4.0 release. See our [April 2020 announcement](https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371)

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
