### ISSUE TITLE
Login Terms layout option does not have any effect

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#28586]
### Description:

Custom layout `Login Terms` option does not have any effect to the login screen in RC 6.0.

We've used this to inform our users of extra details before they log in.
Not many people bother to read the actual terms behind the particular link reserved for it and we got law advice that the most crucial terms should be visible in the main login view directly.

### Steps to reproduce:

1. Go to `Admin -> Settings -> Layout -> Home page content`
2. Alter the field `Login Terms`.
3. Check the login screen for changes.

### Expected behavior:

Edited terms should come to effect under the login elements.

### Actual behavior:

The contents of the login terms remain always the same:
![Screenshot from 2023-03-23 20-45-59](https://user-images.githubusercontent.com/6958942/227317191-74540ea6-b3a4-4953-a839-00371e371122.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Any

**Comment by jeremyd100** [comment]
This issue is also present in version 5.4.4, running within Docker Compose, running against 5.0 Mongo DB.

People that are running on a context path for example /rocketchat, will notice this problem. People running on the default path probably have not noticed this.

The links within the default text will break things.

**Comment by Ahamad-Tanzeel-Khan** [comment]
I think I can work on this issue, can anyone please assign me this project.

**Comment by hugocostadev** [comment]
> I think I can work on this issue, can anyone please assign me this project.

No need to ask for permission to fix the issue, feel free to work on it! 
Just check if someone it's already raised a PR for that (should be linked in this issue).
Best of luck 🚀 👏 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Dass404** [comment]
This article may help to solve this issue- [click here](https://www.mysourcebook.com/2023/04/login-terms-layout-option-does-not-have-any-effect-in-rocketchat-rocket.chat.html) to read.

**Comment by Rbcoder1** [comment]
I Want To Work On IT .

**Comment by Ykumar1415** [comment]
if this issue is not assigned to anyone then I want to work on this issue
