### ISSUE TITLE
Add custom HTTP Headers to let other servers know it is a Rocket.Chat server

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#286]
Needed for native apps
See https://github.com/RocketChat/Rocket.Chat.Electron/issues/1#issuecomment-120001636

**Comment by rodrigok** [comment]
Name suggestions? Value suggestions?

My suggestion:
* rocket-chat-version: 0.0.1

**Comment by engelgabriel** [comment]
:+1: for rocket-chat-version: 0.0.1
