### ISSUE TITLE
kibana's link does not work 

### ISSUE THREAD

**Issue by avelino** [RocketChat/Rocket.Chat#28604]
### Description:

kibana's URI has many different (special) characters, this makes it not work as a link that "breaks" the link in the middle, even if you put it in markdown formatting `[name](https://...)`

```
https://kibana-url/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(columns:!(_source),filters:!(),index:'34822uy4h2jkh4-20f2-11ea-a4cb-6f101195e59b',interval:auto,query:(language:kuery,query:'request:%20%22%2Fperfil%2Fnotificacoes%22'),sort:!())
```

### Steps to reproduce:

1. write message with kibana's url
2. click in send

### Expected behavior:

is it possible to share kibana's url raw and in markdown formatting

### Actual behavior:

<img width="2179" alt="Screenshot 2023-03-24 at 13 59 08" src="https://user-images.githubusercontent.com/31996/227591766-758983c2-156e-4160-8016-b74ef0d1c4c0.png">
<img width="1848" alt="Screenshot 2023-03-24 at 13 59 28" src="https://user-images.githubusercontent.com/31996/227591779-5cdd9a3e-1282-4506-a8bb-310af8c63346.png">

### Server Setup Information:

- Version of Rocket.Chat Server: v6.0.0
- Operating System: Linux (Ubuntu)
- Deployment Method: k8s
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: macOS

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/27733 , this is in progress

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
