### ISSUE TITLE
ARM64 Docker Image

### ISSUE THREAD

**Issue by henrywithu** [RocketChat/Rocket.Chat#28624]
Thanks for the wonderful RocketChat. It will be much appreciated if you can build an ARM64 docker image.
Btw, the snap version in SnapCraft.io is super out-dated (only version 4.x).

**Comment by AlexG-Surevine** [comment]
Seconded on the ARM64 docker images - this would be very useful!

**Comment by spkane** [comment]
This is a duplicate of #27305.
