### ISSUE TITLE
username is not a parameter on desk.rocket.chat sign up but still visible on "forgot password" page

### ISSUE THREAD

**Issue by Onyx2406** [RocketChat/Rocket.Chat#28623]
### Description:
The page at https://desk.rocket.chat/portal/rocketchat/PortalLoginPage.do?mode=forgetPassword&locale=en requires the user to enter either a username or an email address. However, during sign up, only email addresses are accepted and there is no option for a username, as the username is not a parameter even on the profile page.

### Steps to reproduce:

1. Go to https://desk.rocket.chat/portal/rocketchat/PortalLoginPage.do?mode=forgetPassword&locale=en and see yourself.

### Expected behavior:
It should only ask for Email address. 

### Actual behavior:
![5551](https://user-images.githubusercontent.com/32770175/227711022-14c64084-ef81-4853-89ea-13f8900e83b0.png)

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 11

**Comment by thakursachin05** [comment]
We need only Email Address to show up the page to the user.
Right ?? @Onyx2406

**Comment by Onyx2406** [comment]
> We need only Email Address to show up on the page to the user. Right ?? @Onyx2406 If is it , then i can fix this issue.
> 
> Expect Behaviour ![image](https://user-images.githubusercontent.com/60600782/227732199-df03a353-8087-4060-be4e-52ceaaa7eea7.png)

Yes

**Comment by thakursachin05** [comment]
Can you assign this issue to me , so that i can fix it.

**Comment by Onyx2406** [comment]
> Can you assign this issue to me , so that i can fix it. @Onyx2406

I am a contributor as well. Don't wait for someone to assign you, just open a PR.

**Comment by thakursachin05** [comment]
Me finding the same for last two days

> I don't think the code for this issue is in this repository.

**Comment by hugocostadev** [comment]
Yep, it's not in this repo. But thanks for reporting!
