### ISSUE TITLE
Not able to log out on desk.rocket.chat

### ISSUE THREAD

**Issue by Onyx2406** [RocketChat/Rocket.Chat#28622]
### Description:

Upon logging into desk.rocket.chat, if you attempt to log out, it fails to do so and instead automatically logs you back in if you click on the "Sign In" button.

### Steps to reproduce:

1. Sign into desk.rocket.chat with your account.
2. Now log out from your profile window.
3. Now click on Sign In button and you will see you are logged in without entering password and email.

### Expected behavior:

There should not be any automatic logging in.

### Actual behavior:

There should not be any automatic logging in, and the only way to sign in with a different account is to clear the data of the webpage.

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System: Windows 11

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but this is not for this project, but I'll address it internally. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
