### ISSUE TITLE
Apple logo is missing on Sign In page

### ISSUE THREAD

**Issue by Onyx2406** [RocketChat/Rocket.Chat#28625]
### Description:

Apple logo is missing on Sign In page

### Steps to reproduce:

1. Visit https://open.rocket.chat/account/profile

### Expected behavior:

Apple logo should be visible just like github and google logo below it.

### Actual behavior:

![44142](https://user-images.githubusercontent.com/32770175/227732969-a9b2d6ca-53c2-4383-aac5-1bb8a6f6259a.png)

### Client Setup Information

- Desktop App or Browser Version: Browser 
- Operating System: Windows 11

**Comment by Shaheer-Ahmd** [comment]
I would like to contribute to this.

**Comment by tejas558** [comment]
Hey, I'm interested in fixing this issue, I'm working on a PR to close it.

**Comment by tejas558** [comment]
![image](https://user-images.githubusercontent.com/88541385/227839012-c37d2e96-b454-4666-9ad2-b939dd6f8ff8.png)

i don't even see log in services when i run it locally

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

This is not an issue, it's configurable, closing for now
---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
