### ISSUE TITLE
Unable to see log in providers on local instance

### ISSUE THREAD

**Issue by tejas558** [RocketChat/Rocket.Chat#28634]
### Description:
On the login page, I am unable to see the log in provider options. Ie. Sign in with google / github / apple.

### Steps to reproduce:
1. Go to localhost:3000/home
2. View login page and can't find options to log in with provider
1. 
2. 
3. 

### Expected behavior:
There should be login providers ie sign in with google

### Actual behavior:
There isn't a sign in with google option
![image](https://user-images.githubusercontent.com/88541385/227847481-7d6e686e-0e4b-49c5-96b9-561f0a25b9e7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by shibu-g** [comment]
hi can i start working on this issue?

**Comment by tejas558** [comment]
> hi can i start working on this issue?

Hi shibu, you're welcome to start working on this issue. Feel free to create a PR and close this issue any time that you wish.

**Comment by udittripathi** [comment]
Hi can I also try solving this issue?

**Comment by tejas558** [comment]
> Hi can I also try solving this issue?

You're more than welcome to start solving this issue. Just create a PR and link this issue.

**Comment by debdutdeb** [comment]
Sorry but the issue does not have enough information. Seems more like it's a new deployment and you have not enabled those login methods. 

I'll close this one for now, but feel free to continue discussion, or reopen with more information. 

Thanks:)
