### ISSUE TITLE
In the Registration from placeholder is not shown in the Password field  and Confirm Password field

### ISSUE THREAD

**Issue by Bankar-Swapnil** [RocketChat/Rocket.Chat#28639]
In the Registration from placeholder is not shown in the Password field  and Confirm Password field

### Steps to reproduce:

1. go to Registration page 

### Expected behavior:

![Screenshot (104)](https://user-images.githubusercontent.com/98152507/227962148-c3f42d06-2704-4217-9fb4-d17e47d22d81.png)

### Actual behavior:

![Screenshot (105)](https://user-images.githubusercontent.com/98152507/227962108-d5cb3b11-0c9d-40f0-96d6-2de4af98929d.png)

### Client Setup Information

- Desktop App or Browser Version: firefox
- Operating System: win 10

**Comment by tejas558** [comment]
Duplicate issue.

**Comment by Rizwan201** [comment]
Can you assign me this issue

**Comment by hugocostadev** [comment]
I'm checking this out with UI/UX team, usually, placeholder in that scenario is used to give us a hint, doing like that we are just repeating ourselves. As soon as I have a concrete answer I update this issue.

By the way, @Rizwan201 doesn't need to ask to assign an issue to you, if you want to do it, just get it.
