### ISSUE TITLE
Guess chat

### ISSUE THREAD

**Issue by buhino** [RocketChat/Rocket.Chat#2863]
Hi, good morning. Im testing rocket chat in my company and i have a question. It's possible to create a private channel with clients that dont need to register in the server??. We want to have in one hand the company chat and in the other hand the chat with the clients (without password).

Is possible?? You can say to me other alternatives to do this. One user in the demo chat suggest me https://github.com/RocketChat/Rocket.Chat/issues/658 this feature, but the main scope that we want is exactly the guess mode for the clients.

Thx and best reggards.

**Comment by bott0r** [comment]
The live chat implementation does something like that.

**Comment by buhino** [comment]
I have a docker-compose implementation with the rocketchat/rocket.chat:latest image. Reading the docs of live chat appears this "Livechat package is only on develop builds at the moment" in 
https://rocket.chat/docs/master/server-management-livechat . In the latest image appears the feature of live chat but dont works. Should I throw the containers with the rocketchat/rocket.chat:develop image?? Anyone know about this??

**Comment by lvh1** [comment]
That's not true, it now ships with the normal image since a couple of months. All you need to do is activate it on the /admin/Livechat page

**Comment by buhino** [comment]
Yes, i have activated the livechat from the admin panel but i dont know what are the step of start a livechat. Can you resume pls?

Thx

**Comment by lvh1** [comment]
you first gotta install it on your website (url is /livechat-manager/installation)

**Comment by buhino** [comment]
The problem was in the version of rocketchat, the livechat was in my panel but doesnt work. After to update 0.27 version works. Close issue
