### ISSUE TITLE
Editing Message while "Reply in Thread" window open

### ISSUE THREAD

**Issue by famfop** [RocketChat/Rocket.Chat#28663]
### Description:

While having the "Reply in Thread" window open, when trying to edit the original "Message" (not an answer in the thread!) firstly the "More" button behaves weirdly, e.g. mouse hover does not work, and when pressing on "Edit" the text box in the "Reply in Thread" window shows the text to edit. This feels weird, I expect the text to appear in the original "Message box".

### Steps to reproduce:

1. Send a message into a channel (only tested for channels, I guess this happens everywhere).
2. Reply to your message.
3. Have the "Reply in Thread" window on the right side open.
4. Press the "3-dot" resp. "More" button
5. Notice how hovering does not change the background color of the menu-item currently hovered - it feels unresponsive
6. Actually press on edit
7. Be confused
8. Find the original message back in the tiny "Reply in Thread" text box. I thought it to be in the original box where I did create the message in the first place.

I tested this on both the client v.3.9.0 on linux (manjaro) and also in the browser ui (firefox).

**Comment by H9660** [comment]
This seem to be a doable job. Can I work on this?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

About the weird behavior that you mentioned in the "More" button, could you elaborate more? Not happening here

About the edit behavior, this is not an issue, it's designed to behave like that, the user could be using the Expanded thread view. If you want the original message to appear in the main Message Composer you need to edit through the main message, not inside the thread.

I'll close it for now, let me know if you understand or if you have any observations, concerns, or doubts about it. 


---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by famfop** [comment]
Hi, about the "More" button. Not sure how to explain it but I'll try.
When I have the thread view open on the right side and want to edit the original message (of the thread basically), I have two options: Either I select the "More" Button in the thread view or in the "normal" view. The unexpected behaviour happens when I try to press on the "More" button in the "normal" view. In that case the hover does not work as explained before. Also, if there are two ways to edit a message, I guess it should respect which "More" button I pressed and then use the main Message Composer or the thread Message Composer, IMHO.
