### ISSUE TITLE
Renaming channels: Redundant hash sign (#) cannot be removed from channel name

### ISSUE THREAD

**Issue by marco-websource** [RocketChat/Rocket.Chat#28679]
We noticed that a redundant, leading hash sign could not be removed from a channel name by renaming the channel in the UI.

Example case:
- A user creates a new channel and accidentally includes the hash sign in the name: "#example"
- Since RC displays hash signs before channel names, the channel then looks weird with two hash signs: "##example"
- The user tries to rename the channel from "#example" to "example", but this does not work. RC says the change has been applied, but the channel name stays the same.

There is a workaround by doing it in two steps and also changing another part of the name, not just removing the #:
1. Rename "#example" to "example-temp"
2. Rename "example-temp" to "example"

We are using Rocket.Chat 5.4.2 (Node v14.19.3, MongoDB 5.0.14 / wiredTiger)

**Comment by marco-websource** [comment]
Yes, we have enabled UI_Allow_room_names_with_special_chars.

The UTF8 settings are at the default values:
- UTF8_Channel_Names_Validation = [0-9a-zA-Z-_.]+
- UFT8_Names_Slugify = true

Thinking about those options I suspect the problem might be that the slugified names of '#example" and "example" are identical. So the change is a no-op in terms of the slugifed name but not in the displayed name.

**Comment by hugocostadev** [comment]
But if you are using these settings, how do you were able to create a channel using `#` ?

**Comment by marco-websource** [comment]
It is possible because the channel name validation is done with the slugified channel name, i.e. after the special character has been removed by limax (https://github.com/RocketChat/Rocket.Chat/blob/7b5e6552f1f608a149a3fefe380a0f8c8ad5dd47/apps/meteor/app/utils/server/lib/getValidRoomName.js#L45) .
The slugified channel name is "example" but the displayed channel name is "#example". If you try to remove the # from the displayed channel name this doesn't always work.
