### ISSUE TITLE
Offline Email Notifications - Add option to only notify user and not email the contents of the message.

### ISSUE THREAD

**Issue by goobersmooch** [RocketChat/Rocket.Chat#2867]
Rocket.Chat version: 0.26.0

Our organization is looking into using rocketchat as an internal communication tool. Some of the direct messages to users may contain confidential information. If a user is offline and receives a direct message containing confidential information, the email that gets sent to the user contains the contents of the message. It would be really helpful to have an option to only email the user that they have a message, but not show the message in the email.

**Comment by georgeowell** [comment]
I think this is especially important when loads of big email providers still don't bother to implement TLS correctly.

There could also be an option to hide message content in desktop notifications https://github.com/RocketChat/Rocket.Chat/issues/6142

**Comment by makibras** [comment]
We have triaged this as this gives control over privacy preferences and helps with regulatory compliance.

**Comment by sampaiodiego** [comment]
we'll need a privacy section like we have for Push notifications:
![image](https://user-images.githubusercontent.com/8591547/61488413-8989e580-a97e-11e9-8431-ccc8a8953030.png)
