### ISSUE TITLE
Login with Auth0 passwordless login via sms

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#28681]
Hi,

I have added Auth0 as OAuth -> Member. And that seems to work fine so far.

I am trying to use Auth0 passwordless login with SMS, which unfortunately results in an error `No matching login attempt found` in the console. This happens immeditaley as I click on Auth0 login button and the popup window close with sending back the error. However if I choose Email/Pass as login in Auth0, everything works.

Scope is `sms email` in OAuth.

So my question is does RC works with Auth0 SMS logins or any scope like sms etc. Anyone tried this flow before?

Bdw I am on RC **5.4.0**.

Please let me know if need more info.

Thanks

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project, for doubts you can use our Forum.

Replying to your question. No, rocket.chat does not have any native solution for SMS authentication, but you can implement an OAuth provider that it has or implement [External Authentication](https://docs.rocket.chat/setup-and-configure/advanced-workspace-management/authentication#external-authentication)

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by mmarif4u** [comment]
Thanks @hugocostadev

Maybe I was not clear enough when I mentioned Auth0. I was referring to https://auth0.com. Which is a third party OAuth provider.

They provide SMS based logins too. I was wondering if it is possible with RC to authenticate with SMS on [Auth0](https://auth0.com) and return back just a phone number or something as username?

Right now RC does not work with the above flow though.
