### ISSUE TITLE
why was receipt checkmarks taken away?

### ISSUE THREAD

**Issue by rivendellstuff** [RocketChat/Rocket.Chat#28698]
Seems like a weird feature to move to paid. My wife and I use it. We have like 6 family members on our chat and thats it. I'm not upgrading to enterprise for a tiny family chat. I'd just move to Synology's free chat instead. But I figured I'd ask why such a feature was moved to enterprise.

Looks like I'm stuck on 5.4.0 forever til i find a suitable replacement.

**Comment by rivendellstuff** [comment]
> Wait, they took away read receipts? That has to be a joke.

no joke. dont update if you enjoy them. i did... it was pure hell going back cuz the database is diff after 6

**Comment by esnutd** [comment]
Read receipts has been gone.dont update to 6

**Comment by hugocostadev** [comment]
Hi there, thanks for sharing your doubts

Sorry, but GitHub is only for issues/bugs related to the repository project.

Go to our Forum and see related topics about it.

About the Read Receipts:

> Read Receipts have been an EE feature for a long time but, as noted, that restriction has not been previously enforced. Recently the team has invested time in improving the read receipts handling for threads that were not working correctly. As part of the change, we have also begun enforcing the EE restriction.
> **6.0** introduces to the **Community Edition** several other improvements, such as 10 security patches, a MS Teams Bridge app for easier cross-platform messaging, GitHub app, a brand new message composer, improved invitations, extended marketplace inventory and the much requested dark mode. We remain committed to continuing to add capabilities to the Community Edition and having a viable commercial offering is key to our ability to continue and expand our current level of investment in our Community Edition.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by rivendellstuff** [comment]
> Hi there, thanks for sharing your doubts
> 
> Sorry, but GitHub is only for issues/bugs related to the repository project.
> 
> Go to our Forum and see related topics about it.
> 
> About the Read Receipts:
> 
> > Read Receipts have been an EE feature for a long time but, as noted, that restriction has not been previously enforced. Recently the team has invested time in improving the read receipts handling for threads that were not working correctly. As part of the change, we have also begun enforcing the EE restriction.
> > **6.0** introduces to the **Community Edition** several other improvements, such as 10 security patches, a MS Teams Bridge app for easier cross-platform messaging, GitHub app, a brand new message composer, improved invitations, extended marketplace inventory and the much requested dark mode. We remain committed to continuing to add capabilities to the Community Edition and having a viable commercial offering is key to our ability to continue and expand our current level of investment in our Community Edition.
> 
> **Questions? Help needed? Feature Requests?**
> 
> * Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
> * Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

i guarantee you not a SINGLE sale will come from moving "read receipts" to enterprise. NOT a single human being will start paying premium prices for such a small "feature". What will happen though is home users will stop upgrading at 5.4 and those "super security features" you're talking about wont matter cuz many wont get them anymore.  Then someone will get hacked it will be headlines everywhere "Rocketchat hacked! Private content data posted online". Sure there will be follow ups where Rocketchat explains how its been patched forever but ppl were running old versions. But no one ever reads that far. Ppl will just note that "rocketchat.. not safe". All cuz you took a miniscule feature away from the community edition. The community that tests and reports on how to make the product better. 

So ya... your "pros" for the community edition arent very compelling. Not to mention now that this happened... we're all just waiting for you to start locking everything behind paid like a bait and switch. Build a community of loyal ppl then flip it paid on that exact community. dirtball move. breaks the trust. good luck
