### ISSUE TITLE
Change Request: Add "latest" argument to "subscriptions.read" in REST API

### ISSUE THREAD

**Issue by vsg-sandi** [RocketChat/Rocket.Chat#28707]
Suggest adding "latest" argument (The end of time range of messages to mark as read) to "subscriptions.read" in REST API.  This would allow you to get "channels.history" with "unreads=true" then mark the messages you just pulled as read "subscriptions.read" using the last message's time stamp as your "latest" argument.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project. Open a feature request in our Forum, please

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
