### ISSUE TITLE
How to export Rocket.Chat's API in Open API format?

### ISSUE THREAD

**Issue by luozhouyang** [RocketChat/Rocket.Chat#28724]
How can I export Rocket.Chat's API in Open API format, so I can use swagger codegen to generate SDKs?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

@luozhouyang we are working on a swagger, soon we will have news

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
