### ISSUE TITLE
GUI crashes in dev mode for inactivity in the Rocket.Chat app tab

### ISSUE THREAD

**Issue by Asem-Abdelhady** [RocketChat/Rocket.Chat#28725]
### Description:

I opened Rocket chat locally in development mode(devlopment branch). I tried to create a team but I switched tab before I create it. I went back to Rocket.Chat tab and the GUI crashes. I get the message **The application GUI just crashed** 

### Steps to reproduce:

1. Open the development mode
2. Click on create new
3. Choose the team option
4. Switch tabs for 4 minutes
5. Go back to the development tab

### Expected behavior:

The team creation form still exists or the error GUI crashed does not appear.
### Actual behavior:

I get GUI crashd in the screen :
<p style="align-items: center">
<img src="https://user-images.githubusercontent.com/40506647/229106164-cd3deda0-c299-418d-86a1-11ae0ede4dd2.png" />
</p>

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.0-develop 
- Operating System: Ubuntu 22.04.2 LTS 
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.2 - x64
- MongoDB Version: 5.0.5

### Client Setup Information

- Desktop App or Browser Version:  Chrome 111.0.0.0
- Operating System: Ubuntu 22.04.2 LTS 

### Relevant logs:
![image](https://user-images.githubusercontent.com/40506647/229110217-d7667d30-98c5-4682-aa8d-019bc97d1a03.png)
![image](https://user-images.githubusercontent.com/40506647/229110659-806c8678-6581-443b-9fb7-4e8b675a40a6.png)

**Comment by AdityaSingh-02** [comment]
Which language were you using?

**Comment by Asem-Abdelhady** [comment]
> 

I am sorry what do exactly to do you mean by language

**Comment by hugocostadev** [comment]
Could you update your branch and try it again? This is supposed to be fixed in the last develop branch. 
If this still persists, reopen this issue, please. 

Thanks for reporting
