### ISSUE TITLE
Can not create integration (incoming webhook) for a new existing room

### ISSUE THREAD

**Issue by blu-IT** [RocketChat/Rocket.Chat#28723]
### Description:

My problem i similar to the one already mentioned here #13061 and here #13103 .
I created an incoming webhook (for monitoring alerts with uptime kuma) and when configuring the room/channel, the systems says: "Invalid room" - but the channel / room exists and I am also a member of that room.

The strange thing is, that I configured a webhook some time ago for uptime-kuma and it worked for another (identical configured channel), but now I want the monitoring messages to be shown in another separate channel and setting up this new hook does not work.

### Steps to reproduce:

1. Go to Administration -> Integrations
2. Click New and fill in the form, make sure the bot user is in the room (e.g. #monitoring) where you want to send messages
3. Add your script and click save

### Expected behavior:

Parameters are accepted and incoming webhook is saved. 

### Actual behavior:

The message "Invalid room" appears and webhook can not be saved.

### Logs:

I20230331-10:56:04.321(2) server.js:204 System ➔ error Exception while invoking method updateIncomingIntegration Invalid room [error-invalid-room] 
I20230331-11:01:30.003(2) server.js:204 System ➔ error Exception while invoking method updateIncomingIntegration Invalid room [error-invalid-room] 
I20230331-11:17:49.059(2) server.js:204 System ➔ error Exception while invoking method updateIncomingIntegration Invalid room [error-invalid-room] 
I20230331-11:18:41.503(2) server.js:204 System ➔ error Exception while invoking method updateIncomingIntegration Invalid room [error-invalid-room]

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.7
- Operating System: Ubuntu 18.0.4 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog:  wiredTiger (oplog activated)
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: FF 111
- Operating System: Windows 11

**Comment by blu-IT** [comment]
OK, this is somekind of weird: Configuring the webhook, I had to set the channel name to _#monitoring_ instead of _#Monitoring_ . But with the channel that was configured first, it worked with #Tec instead of #tec and the channels are named with a upper case letter.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
