### ISSUE TITLE
Avatars distorted

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#28726]
### Description:

Avatars are appearing completely distored and styling is broken.

### Steps to reproduce:

1. Update to 6.2.0-develop (docker, git commit 37f6852b7)
2. Message screen looks like this:

![image](https://user-images.githubusercontent.com/14616851/229117687-e910e7af-ad46-4b6e-a7d5-6c2d05529c2d.png)

### Expected behavior:

Avatars should display correctly

### Actual behavior:

Avatars show distored and styling broken

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.0-develop (docker, git commit 37f6852b7)
- Operating System: (Ubuntu 22.04, docker)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version:  v14.21.3
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.9.0 / 111.0.1 (64-bit)
- Operating System: Windows 11 Pro

### Additional context

None

### Relevant logs:

None

**Comment by hugocostadev** [comment]
Hi there, this issue was fixed in this PR: https://github.com/RocketChat/Rocket.Chat/pull/28732 thanks for reporting
