### ISSUE TITLE
Ugly code block in RocketChat v6

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#28729]
### Description:

There's a new feature, called "dark mode" but the [unofficial dark mode](https://github.com/pbaity/rocketchat-dark-mode/) had way better color scheme.

### Steps to reproduce:

1.Upgrade RC to v6
2. Set dark mode
3. Write code block

### Expected behavior:

Some dark behavior of code block when the dark mode is set

### Actual behavior:

Ugly white behavior 
![image](https://user-images.githubusercontent.com/11560794/229131057-6106af84-45bb-42ec-8058-31d14185c051.png)

in contrast of code block in v5.4 with the unofficial dark mode
![image](https://user-images.githubusercontent.com/11560794/229131660-2e8fff9e-f1e9-48a9-99df-2f59a39fdc59.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: debian linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: desktop app, `rocketchat-client-bin 3.8.16-1`
- Operating System: arch linux

### Additional context

N/A

### Relevant logs:

N/A

**Comment by hugocostadev** [comment]
Thanks for your feedback, we will discuss internally with our Design team

**Comment by ivans-netto** [comment]
Hi @dusatvoj 

We've implemented the code block for dark theme, if you update to Rocket.Chat's last version you're gonna see it fixed. More syntax highlights are coming on upcoming releases.
