### ISSUE TITLE
Make Hashtags

### ISSUE THREAD

**Issue by wrought** [RocketChat/Rocket.Chat#2873]
version: latest

It would be great if users could create hashtags. Everybody else is doing it, so users I've communicated with get confused about the `#channel` features because they expect those to be hashtags.

**Comment by IQ2022** [comment]
also Cashtags $

**Comment by marceloschmidt** [comment]
Thanks for the suggestion, but this doesn't fit Rocket.Chat's architecture.

**Comment by T7o7heVV** [comment]
@marceloschmidt sorry as a software developer I do not understand how this cannot fit the architecture of Rocket.Chat. A simple version of hashtags would suffice in forms of a user-defined string-prefix which can even be searched for in a normal message-content search. There is no need for any database related support for those hashtags. The feature would only be UI-related as Rocket.Chat would then enumerate all messages containing at least one instance of the specified string.

Right now, everyone can "fake" hashtags by using any prefix and manually searching through the messages later on. But a UI support would be very nice!

**Comment by krausdavid** [comment]
+1

**Comment by alexander-potemkin** [comment]
The problem, as I see it, is that hashtag is reserved for the channels + making efficient search requires search engine, which is still a thing in progress (in 2020)

**Comment by heyyo-droid** [comment]
Would it be possible to use channels also as tags ?  
For example, if adding a message containing a link to a channel #something it will also add this message to this  channel #something.

**Comment by nick2525** [comment]
It will be nice to have tags
