### ISSUE TITLE
This workspace has reached its seat limit so no more members can join

### ISSUE THREAD

**Issue by tridung141196** [RocketChat/Rocket.Chat#28743]
Hi Rocketchat teams, I deploy rocketchat community and after woking along time. I have a problem "*No more seats available* This workspace has reached its seat limit so no more members can join. *[Request More Seats](https://chat.kienlongbank.co/requestSeats)*"

I check Server connection status:

db.serverStatus().connections
{
	"current" : 60,
	"available" : 838800,
	"totalCreated" : 705833,
	"active" : 36,
	"exhaustIsMaster" : 4,
	"exhaustHello" : 0,
	"awaitingTopologyChanges" : 50
}

So, how to resolve this?
Thank you so much!

**Comment by tridung141196** [comment]
<img width="1440" alt="Screen Shot 2023-04-01 at 11 05 37" src="https://user-images.githubusercontent.com/29392230/229264944-80dc4ee1-674e-4f93-b705-9e5aede19e6f.png">

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/) provides **security** support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
