### ISSUE TITLE
rocketchat.md link to system requirements page error 404

### ISSUE THREAD

**Issue by manikanta-swamy-n** [RocketChat/Rocket.Chat#28746]
### Steps to reproduce:

1.  Go to readme.md file in the rocket.chat repo.
2.  Click on "requirements documentation" of heading Installation. 
3.  getting page not foud error in the docs.rocket.chat.
![Screenshot 2023-04-02 120620](https://user-images.githubusercontent.com/81160682/229337522-2b843d84-cd17-401c-b314-dac4397be58d.png)

### Expected behavior:

the link should take you to the page of system requirements.
![Screenshot 2023-04-02 122422](https://user-images.githubusercontent.com/81160682/229337458-51fee99f-18b4-4a19-80b0-175fa9b40b4a.png)

### Actual behavior:
getting error 404 page not found error.
![Screenshot 2023-04-02 115722](https://user-images.githubusercontent.com/81160682/229337385-b381a2b6-af81-498b-9b49-fb889efb3447.png)

### Client Setup Information
- Operating System: windows

### Additional context

easily fixable by just updating the links in the readme.md file.

**Comment by 26thavenue** [comment]
@hugocostadev can you assign me this issue

**Comment by hugocostadev** [comment]
> @hugocostadev can you assign me this issue

No need to ask for permission to fix the issue, feel free to work on it! 
Just check if someone it's already raised a PR for that (should be linked in this issue).
Best of luck 🚀 👏
