### ISSUE TITLE
User is asked in mobile client to install a desktop extension when selecting screen sharing

### ISSUE THREAD

**Issue by watermelonjuice** [RocketChat/Rocket.Chat#2874]
Your Rocket.Chat version: demo site
The user is asked in mobile client to install a desktop extension when selecting screen sharing in video chat.

**Comment by antn89** [comment]
Same my issue

**Comment by MartinSchoeler** [comment]
@watermelonjuice this should be already fixed, if not please reopen this with updated details. Thanks!
