### ISSUE TITLE
BUG_REPORT.md template opening issues : link page not found error(404).

### ISSUE THREAD

**Issue by manikanta-swamy-n** [RocketChat/Rocket.Chat#28752]
### Description: Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues giving page not found 404 error on inspection. 
![Screenshot 2023-04-02 191409](https://user-images.githubusercontent.com/81160682/229356909-7be703e9-a678-4ecc-9232-5ad8633b1429.png)

### Steps to reproduce:

1. Go to issues and click new issue
2. Click on bug report get started.
3. now in the reporting template select the first link in a new window.

### Expected behavior:

![Screenshot 2023-04-02 192322](https://user-images.githubusercontent.com/81160682/229357303-330f71a8-2430-4d30-bc52-00367cb150a3.png)

### Actual behavior:

![Screenshot 2023-04-02 115722](https://user-images.githubusercontent.com/81160682/229357337-3fffa1f2-e8fe-4b3c-9922-53bffa2dffe9.png)

### Client Setup Information

- Operating System: windows

**Comment by adityakode** [comment]
I would like to work on this issue

**Comment by manikanta-swamy-n** [comment]
docs: README.md and BUG_REPORT.md changed document updation #28747
