### ISSUE TITLE
Config settings private apps crash the server

### ISSUE THREAD

**Issue by juzser** [RocketChat/Rocket.Chat#28761]
### Description:

When I tried to update settings of our private apps, the server crashed.
It keeps request on app update API and screenshot API repeatly.

**I think the main point is: my workspace is Free-edition (limit 3 private apps) but I already have 6 private apps running before upgraded to version 6.0.**

<img width="1717" alt="Screenshot 2023-04-03 at 15 40 13" src="https://user-images.githubusercontent.com/5735071/229457847-fcc334a4-34cb-4f89-a6da-ac0b6e46a768.png">

### Steps to reproduce:

1. Go to `...marketplace/private/list`
2. Click on any private apps & change settings.
3. Save changes
4. Crash.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Ubuntu
- Deployment Method: Manually
- Number of Running Instances: 1
- NodeJS Version: v14.19.1
- MongoDB Version: 5.0.8 / wiredTiger

**Comment by debdutdeb** [comment]
Fixed in 6.0.1 :)
