### ISSUE TITLE
/help notifying the shortcuts in multiple messages 

### ISSUE THREAD

**Issue by chinma-yyy** [RocketChat/Rocket.Chat#28763]
### Description:

When using `/help` to list the keyboard shortcuts the bot notifies the user with multiple messages instead of one message.

### Steps to reproduce:

1. Use `\help` in any room

### Expected behavior:
The bot should notify the user with all the shortcuts in a single message

### Actual behavior:
The bot notifies the user multiple times in different messages
![Screenshot from 2023-04-03 21-08-16](https://user-images.githubusercontent.com/112387862/229485768-e2b963ef-713a-4083-bbe5-b3feee13364d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Alexanderwar** [comment]
i would like to work on it can you assign the task to me
