### ISSUE TITLE
Site_Url is not persistent

### ISSUE THREAD

**Issue by sporqist** [RocketChat/Rocket.Chat#28768]
### Description:

The variable Site_Url in rocketchat_settings inside mongodb is being overwritten / recreated on restart.

This started happening after doing an Upgrade from 3.18.7 to 4.8.1 to 5.4.5. This is how I did the upgrade:
```bash
snap switch rocketchat-server --channel=4.x/stable
snap refresh rocketchat-server
# Wait until the upgraded server comes up and finished it's db migrations.
snap switch rocketchat-server --channel=5.x/stable
snap refresh rocketchat-server
```

### Steps to reproduce:

1. Restart Rocketchat Snap
    ```bash
    snap restart rocketchat-server
    ```
2. Open any chat with file/picture uploads

### Expected behavior:

Pictures are showing and downloads work.

### Actual behavior:

Pictures are missing and download links use https://localhost:3000/ as base URL instead of my Site_Url https://chat.example.org/.

When i check the value of `Site_Url` in mongodb, it looks like this:
```json
{
    "_id" : "Site_Url",
    "value" : "http://localhost:3000",
    "packageValue" : "https://chat.example.org/",
    "valueSource" : "processEnvValue",
    "secret" : false,
    "enterprise" : false,
    "i18nDescription" : "Site_Url_Description",
    "autocomplete" : true,
    "sorter" : 0,
    "ts" : ISODate("2023-04-03T09:25:45.394Z"),
    "createdAt" : ISODate("2023-04-03T09:25:45.394Z"),
    "type" : "string",
    "group" : "General",
    "public" : true,
    "i18nLabel" : "Site_Url",
    "hidden" : false
    "blocked" : false,
    "requiredOnWizard" : false,
    "env" : false,
    "processEnvValue" : "http://localhost:3000",
    "_updatedAt" : ISODate("2023-04-03T09:25:45.394Z")
}
```

As you can see, `packageValue` still holds the original value I want but `value` went back to the default. 

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.5
- Operating System: Debian 11
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: **no replicas**
- NodeJS Version: v14.19.3
- MongoDB Version: v4.4.15

### Client Setup Information

- Desktop App or Browser Version: Chromium 111.0.5563.147 stable
- Operating System: openSUSE Tumbleweed 20230330-0

### Additional context

Sometimes the "Site URL"-field in Administration -> Workspace -> Settings -> General is missing entirely. 

![Rocketchat Site URL missing](https://user-images.githubusercontent.com/22202402/229533239-cfe73ae3-7da5-49ab-9231-467adcf95c62.png)

I'm using these commands to check and set the value of `Site_URL`:
1. Enter the database snap:
    ```bash
    snap run --shell rocketchat-server.rocketchat-mongo
    ```
2. Query/Update the value of `Site_Url`:
    ```bash
    mongo parties --eval 'db.rocketchat_settings.find({"_id" : "Site_Url"}).pretty()'
    mongo parties --eval 'db.rocketchat_settings.update({"_id" : "Site_Url"},{$set:{value:"https://chat.example.org/"}})'
    ```

### Relevant logs:

```log
Apr 03 10:39:53 chat systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Apr 03 10:39:54 chat rocketchat-server.rocketchat-server[1217261]: node $SNAP/main.js
Apr 03 10:40:15 chat rocketchat-server.rocketchat-server[1217314]: strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
Apr 03 10:40:19 chat rocketchat-server.rocketchat-server[1217314]: LocalStore: store created at
Apr 03 10:40:19 chat rocketchat-server.rocketchat-server[1217314]: LocalStore: store created at
Apr 03 10:40:19 chat rocketchat-server.rocketchat-server[1217314]: LocalStore: store created at
Apr 03 10:40:27 chat rocketchat-server.rocketchat-server[1217314]: MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
Apr 03 10:40:28 chat rocketchat-server.rocketchat-server[1217314]: {"level":40,"time":"2023-04-03T08:40:28.296Z","pid":1217314,"hostname":"chat","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Apr 03 10:40:33 chat rocketchat-server.rocketchat-server[1217314]: Browserslist: caniuse-lite is outdated. Please run:
Apr 03 10:40:33 chat rocketchat-server.rocketchat-server[1217314]:   npx update-browserslist-db@latest
Apr 03 10:40:33 chat rocketchat-server.rocketchat-server[1217314]:   Why you should do it regularly: https://github.com/browserslist/update-db#readme
Apr 03 10:40:34 chat rocketchat-server.rocketchat-server[1217314]: {"level":40,"time":"2023-04-03T08:40:34.020Z","pid":1217314,"hostname":"chat","name":"VoIPService","msg":"VoIP service already stopped"}
Apr 03 10:40:34 chat rocketchat-server.rocketchat-server[1217314]: {"level":51,"time":"2023-04-03T08:40:34.743Z","pid":1217314,"hostname":"chat","name":"Migrations","msg":"Not migrating, already at version 281"}
Apr 03 10:40:34 chat rocketchat-server.rocketchat-server[1217314]: {"level":51,"time":"2023-04-03T08:40:34.796Z","pid":1217314,"hostname":"chat","name":"DatabaseWatcher","msg":"Using change streams"}
Apr 03 10:40:35 chat rocketchat-server.rocketchat-server[1217314]: Loaded the Apps Framework and loaded a total of 0 Apps!
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: +------------------------------------------------+
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |                 SERVER RUNNING                 |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: +------------------------------------------------+
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |                                                |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |  Rocket.Chat Version: 5.4.5                    |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |       NodeJS Version: 14.19.3 - x64            |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |      MongoDB Version: 4.4.15                   |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |       MongoDB Engine: wiredTiger               |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |             Platform: linux                    |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |         Process Port: 3000                     |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |             Site URL: https://chat.example.org/|
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |     ReplicaSet OpLog: Enabled                  |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |          Commit Hash: 45d3ca8961               |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |        Commit Branch: HEAD                     |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: |                                                |
Apr 03 10:40:36 chat rocketchat-server.rocketchat-server[1217314]: +------------------------------------------------+
```

**Comment by debdutdeb** [comment]
there is a file in /var/lib/rocketchat/current called OVERWRITE_SETTING_Site_Url.env, delete that file :) I'll add a migration to do that on latest.

**Comment by sporqist** [comment]
Thank you so much. Dealing with this over the last few days hasn't been fun at all :sweat_smile: 

I'm worried, this file might be recreated in later patches. Is it safe to assume, this file will not be created in the future if I delete it now? Would it be safer to edit it to my liking and not delete it?

**Comment by sporqist** [comment]
Also for anyone using the rocketchat snap, this is the correct path: `/var/snap/rocketchat-server/current/OVERWRITE_SETTING_Site_Url.env`

**Comment by debdutdeb** [comment]
> I'm worried, this file might be recreated in later patches.
Will make sure it doesn't ;) I had to include it once because of a bug in core, where an incorrect site url could cause the ui to break, and the existing path of updating it didn't work. 
> Is it safe to assume, this file will not be created in the future if I delete it now?
yes.
> Would it be safer to edit it to my liking and not delete it?
sure, depends on what you edit it to haha
> *Also, what exactly does sudo snap set rocketchat-server siteurl= do? That command is suggested in OVERWRITE_SETTING_Site_Url.env. Does it take precedence over environment variables?
that command basically overwrites the `.env` file with a new value. as it is right now, after editing or removing the file, i'd recommend not running any snap set .. commands as that will just re place that file. or better yet temporarily use `snap set` to update that file. a migration will take care of those configs in the next version.
> It would be great to have a table for all the ways to set Site_Url and their priority somewhere in the docs.
At first boot, ROOT_URL gets set as Site_Url, setting `Site_Url` as environment variable will take second precedence. Next, `OVERWRITE_SETTING_Site_Url` will **always** overwrite your UI setting. Moving forward I'm thinking about making `snap set .. siteurl=<>` to update the db directly so that it is more of the same as doing it via the ui.
