### ISSUE TITLE
Some links do not work depending on the TLD

### ISSUE THREAD

**Issue by metode-cz** [RocketChat/Rocket.Chat#28782]
### Description:

I can't click through some links. 
for example:
https://mypage.iko <- not working
https://mypage.eu <- is ok

This has been solved for many years.- https://www.rfc-editor.org/rfc/rfc3986

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.0
- Operating System: Linux Debian
- Deployment Method: docker

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

The `.iko` TLD does not seem to be a valid open TLD, is an internal TLD? 

I did search several sources, like https://publicsuffix.org/list/public_suffix_list.dat

If it's an internal host, we shipped in this PR https://github.com/RocketChat/Rocket.Chat/pull/28501 a solution for that, you just need to add a new config, soon it will be released, but it's already on `develop` . Check the PR description for more information on how to add this setting. 

I'll close the issue for now, but if have more insights and considerations, feel free to reopen. Thanks

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Comment by metode-cz** [comment]
Hi, yes, It's internal TLD. This worked normally in older versions of rocketchat.
