### ISSUE TITLE
have  the ability of "send or share  to the specified channel" manually ?

### ISSUE THREAD

**Issue by javaning** [RocketChat/Rocket.Chat#2878]
Your Rocket.Chat version: (0.25.0)

when i find some resources interesting (useful), so I want share to my team ...   like fb feed dialog

if not, is there a plan on this feature ?

thanks

**Comment by marceloschmidt** [comment]
Do you mean like copying a message or a file to another channel?

**Comment by javaning** [comment]
@marceloschmidt   like share a page link ( with some words) to facebook from other websites: **forword (or share) to rocket.chat** . 
thanks

**Comment by marceloschmidt** [comment]
Are you talking about mobile apps, maybe? I think you might be referring to the native android share screen, is that so? If that's what you meant, it has been implemented already, see the screenshot below:

![2016-05-03 12 01 18](https://cloud.githubusercontent.com/assets/1986378/14982627/193bdab0-110e-11e6-90cc-e3475cd5813b.png)

I'm pretty sure that's also available for the iOS...

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
