### ISSUE TITLE
Unable to send file with non-standard extension

### ISSUE THREAD

**Issue by sigsergv** [RocketChat/Rocket.Chat#28808]
### Description:

It's impossible to send file with non-standard extension.

### Steps to reproduce:

Try to upload (Add file from computer) any file with non-standard extension, for example, `test.abcde` or `test.signed`.

### Expected behavior:

Send file dialog should appear,

### Actual behavior:

Error message in top-right corner:

Media Type Not Accepted: undefined

![image](https://user-images.githubusercontent.com/1030732/230055759-a2193b7f-5a66-42bf-90eb-e69d8f5499ff.png)

### Server Setup Information:

_no information_

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

Desktop app (linux), browser (firefox linux, firefox mac, chrome linux) — the same behaviour.

**Comment by CulturalProfessor** [comment]
Hey @sigsergv I was able to upload a file with **.random** extension .
![image](https://user-images.githubusercontent.com/92238941/230061355-d678bc05-02d9-48a3-a89f-26107f5d68e4.png)

I am using ubuntu 22.04

**Comment by sigsergv** [comment]
The same error.

I'll contact system administrators to check version, maybe it's not a last one available.

**Comment by hugocostadev** [comment]
Hi @sigsergv check with admin if there are setting set at `/admin/settings/FileUpload` > `Accepted Media Types`
This could be the problem

**Comment by sigsergv** [comment]
Looks like it's fixed already in latest server version.
