### ISSUE TITLE
Unable to disable "Register Username" under 6.0

### ISSUE THREAD

**Issue by darrennye** [RocketChat/Rocket.Chat#28820]
I have two different sites/domains running WordPress. Each one has the MiniOrange OAuth Server 5.1 plugin installed, and they both call one chat server that is running Rocket Chat 6. and within Rocket Chat, I have the two custom OAuth clients running.

MiniOrange actually helped me get the integration running between the two. And that works.

Once the user goes to the RocketChat server, I have RocketChat configured to ask if they are “Logging In from [www.domain1.com](http://www.domain1.com/)” or “Logging in from [www.domain2.com](http://www.domain2.com/)”.

Once they click either option, I want them to go RIGHT INTO Chat, after they authenticate from WordPress to RocketChat.

Ideally they would also NOT get that pop-up to “Allow” or “Deny”.

But right now when someone goes from the two OAuth server Wordpress site, to the Chat server, they are first getting the “Allow” or “Deny” prompt, but after “Allowing” they then get the pop-up asking them to "REGISTER USERNAME". And this pop-up does pass the correct username from WordPress, but it allows them to change it, and I don’t want users to change it.

None of the flags I've tried, will successfully turn this REGISTER USERNAME off. How do I stop this from appearing? Is this a bug?

Also how do I stop the “Allow” or “Deny”? Is this really necessary?

Thanks all.

**Comment by ggazzo** [comment]
Rocket.chat requests registration of a username when the corresponding property is blank only.
This prompt is only issued once. in your case if you assign a username, will it be necessary to provide it again in the future? 

logging in through the domain does not automatically transfer the username from WordPress.

**Comment by darrennye** [comment]
Please see these related posts:

https://forums.rocket.chat/t/how-can-i-disable-register-username-window-and-use-default-username-automatically/16295

https://forums.rocket.chat/t/how-to-disable-register-username/16438

**Comment by darrennye** [comment]
Anyone know if there is a way to prevent the pop-up allowing a user to change their username?

Is this a bug or ??

**Comment by hugocostadev** [comment]
Is this still happening?  Are you referring to the popup of the form for a second of the Register Username form? If so, I opened a PR for that: https://github.com/RocketChat/Rocket.Chat/pull/29356

**Comment by darrennye** [comment]
No, I got around the issue. I think I reinstalled, started from scratch, and then realized one setting, somewhere, I didn't have set correctly.

________________________________

**Comment by hugocostadev** [comment]
Can you share the setting here to let others know? 

Closing for now! Thanks
