### ISSUE TITLE
Command not Being Added

### ISSUE THREAD

**Issue by EngineerHus** [RocketChat/Rocket.Chat#28827]
I've a docker container running Rocketchat server where I have forked the rocketchat repo to customize my own rocketchat server. I've created a new folder within _/Rocket.Chat/apps/meteor/app_ called _slashCommands-lol_ with a folder inside it called _server_. The _server_ folder has 2 files in it called _lol.ts_ and _index.ts_. 

**lol.ts** 
```
import { Meteor } from 'meteor/meteor';

import { slashCommands } from '../../utils/lib/slashCommand';
import { hasPermissionAsync } from '../../authorization/server/functions/hasPermission';

slashCommands.add({
	command: 'lol',
	callback: async (_command: 'lol', params, item): Promise<void> => {
		const uid = Meteor.userId();
		if (uid && (await hasPermissionAsync(uid, 'edit-room', item.rid))) {
			await Meteor.callAsync('saveRoomSettings', item.rid, 'roomTopic', params);
		}
	},
	options: {
		description: 'Slash_Topic_Description',
		params: 'Slash_Topic_Params',
		permission: 'edit-room',
	},
});
```
**index.ts**
`import ./server';`
I have copied this from another command where I only changed the naming to `lol ` just to test it out for now and see whether my changes get added or not (once I have confirmed my commands get added, I'll then build a custom command). However when I rebuilt the container with `docker-compose up --build` and refresh the Rocketchat server on my browser, the command cant be found at all. I tried /lol but says _"No Such command /lol"_. Have a rebuilt the container wrong/coded the function wrong or is there a certain step I am missing? Thanks in advance

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
