### ISSUE TITLE
One-click Deploy Issue on Heroku, wrong environment key name MONGODB_URI provided. 

### ISSUE THREAD

**Issue by michieriffic** [RocketChat/Rocket.Chat#2882]
Error: MONGO_URL must be set in environment

Initial key set in the environment: MONGODB_URI
Should be MONGO_URL

So just change it to MONGO_URL for others who are having this issue. Thanks :)

**Comment by engelgabriel** [comment]
I am not sure I understand where do you think we have "MONGODB_URI"?

**Comment by michieriffic** [comment]
Heroku generated that env var with key name MONGODB_URI instead of MONGO_URL when i've used the one-click deploy resulting to error: MONGO_URL must be set in environment.

![screen shot 2016-04-14 at 11 30 22 pm](https://cloud.githubusercontent.com/assets/12575688/14533753/f7cc0734-0298-11e6-88ba-244507e6809e.png)

**Comment by engelgabriel** [comment]
I've updated https://github.com/RocketChat/heroku-buildpack-meteor.git so the One-click Deploy is working again. I've just did a quick test myself.
