### ISSUE TITLE
I have installed rocket chat , it asked my url to connect i have done it and again  it asked to give the smart internz credentials. here its not taking credentials and its reflecting like incorrect user name or invalid.

### ISSUE THREAD

**Issue by sumanthchowdary1** [RocketChat/Rocket.Chat#28837]

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
