### ISSUE TITLE
The difference between TEAM and CHANNEL?

### ISSUE THREAD

**Issue by vodanhtu** [RocketChat/Rocket.Chat#28839]
Hello everybody,
I am a new user used Rocket.Chat. Can everybody explain for me the the difference between TEAM and CHANNEL? In my opinion, I think the two are similar. 
sorry if you think this question is stupid
Thanks!!!!!!!!!

**Comment by tassoevan** [comment]
In short, a channel is a public chat room, and a team is a room that can have sub-rooms (like channels and private groups). You don't need to be the workspace administrator to manage a team.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by bird-in-a-tree** [comment]
@tassoevan can you please elaborate a bit more?

I see both channels and teams can be private and public.
Both channels and teams can have create subchannels (discussions).
