### ISSUE TITLE
webRTC stability

### ISSUE THREAD

**Issue by pachox** [RocketChat/Rocket.Chat#2884]
we run RC 0.26, but we tested the public demo too, with similar results.
Calls and video calls are not working in a complete affordable way, sometimes they work, sometimes don't.
it happens that:
- userA places a call to userB but userB doesn't receive any notification
- userA places a call to userB but userA screen remains blank
- userA places a call to userB but nothing happens when userA clicks on the button (we can find the action in RC log files)
- userA places a call to userB, userB answers but both users can only see their own video

All RTC tests are generally fine, from some networks connectivity tests fail.
i think we need to:
- identify issues and understand what needs improving
- improve documentation with troubleshooting tests

**Comment by Sing-Li** [comment]
New solution testing now.

On https://demo.rocket.chat

When you are in a Direct Message or Private Group.  You will notice a  _new_ video button on the toolbar , just click it anytime to start a video conference with all those in the room

**Comment by MartinSchoeler** [comment]
Hey @pachox , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
