### ISSUE TITLE
Не могу зарегистрироваться

### ISSUE THREAD

**Issue by FilimonovaDina** [RocketChat/Rocket.Chat#28841]
Здравствуйте, скачала приложение и не могу зарегистрироваться, т.к. в приложение написано, что не возможна регистрация нового пользователя.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
