### ISSUE TITLE
Rocket.Chat turns :D into :england:

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28844]
### Description:

When typing `:D`, a list of emojis will be suggested. Hitting enter will then select the first of these suggestions instead of submitting the message. In my case, the first emoji in the list is `:england:`.

### Steps to reproduce:

1. Type `:D`.
2. Hit enter.

### Expected behavior:

Instead of suggesting `:england:` and then selecting it, I would expect the message to be submitted.

In Rocket.Chat 5.4.3 (the most recent version before Rocket.Chat 6.0.0 was released), this was actually the case:

https://user-images.githubusercontent.com/404840/230746959-4aab09f9-d256-4407-89ab-77412d241b19.mp4

### Actual behavior:

`:D` gets replaced by `:england:`, something I never intended:

https://user-images.githubusercontent.com/404840/230746966-7432085e-6a8d-4b22-9daa-23feeffa9cb3.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

**Comment by hugocostadev** [comment]
I don't know if this could be considered a bug... When you press enter you are selecting the `:england:` emoji, maybe we need to evaluate this behavior.

Maybe could be related to this other issue: https://github.com/RocketChat/Rocket.Chat/issues/28819

**Comment by Karting06** [comment]
I agree.
It's extremely annoying at the end of a text. In such case, I press `ENTER` to send the message not to select the emoji.
Hence, the autoselection/autofocus of the first emoji of the list should be removed.

**Comment by hugocostadev** [comment]
Thank you for your suggestions, your feedback is very important to us and I will bring this to light internally!

**Comment by eloo-abi** [comment]
I guess this suggestion should work like every suggestion feature in our browsers?
If hit enter i will get the string i have written.
And to select one of the suggestion it need to explicit select it by using the down arrow key or something else..

![image](https://user-images.githubusercontent.com/49561925/232404757-5145eca9-81cd-40fb-ad04-92c6acacadec.png)

and yes.. the current behaviour is IHMO a bug because it has changed from an intuitive behaviour to a bad one
