### ISSUE TITLE
Unable to highlight a user when prepending the username with a >

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28846]
### Description:

When I prepend a username with `>`, the user will not be highlighted.

### Steps to reproduce:

Suppose you have a user with the username `test1`.

1. Write the message `test > @test1`.

### Expected behavior:

The user will be highlighted.

### Actual behavior:

The user will not be highlighted:

![image](https://user-images.githubusercontent.com/404840/230747357-aa2d35e3-a8a8-492a-8d02-b49b059f900e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

The issue seems to be client-agnostic. I just verified it with:

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

### Additional context

The issue only occurs when the `>` is immediately followed by the username.

What does not work:
- `test > @test1`
- `> @test1`

What works:
 - `> test @test1`
 - `test > test @test1`
 
![image](https://user-images.githubusercontent.com/404840/230747457-588bf976-39d9-4969-b4e1-f0eeba8da2a9.png)

**Comment by hugocostadev** [comment]
Adding more info:

Seems that the mention is being parsed correctly, could be something related with the mention resolver

![image](https://user-images.githubusercontent.com/20212776/230909518-278e66a8-7a21-4931-91a8-300cec693830.png)

**Comment by ayush3160** [comment]
@hugocostadev , I would like to work on this issue. Can you please assign it to me.
