### ISSUE TITLE
Username suggestion list misaligned

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28847]
### Description:

Under certain circumstances, the suggestion list for users to highlight exceeds a certain list and becomes misaligned.

### Steps to reproduce:

1. You need a channel with six users.
2. Ensure that five of the users have written at least one message recently. This is necessary for the suggestion list to contain enough items labelled "Suggestion from recent messages".
3. Log in with the sixth user.
4. Type `@all` and delete `all`, leaving only `@`.

### Expected behavior:

A neat list of usernames is shown.

### Actual behavior:

A list of usernames is shown, but it is misaligned. Some parts are even hidden behind the input box:

![image](https://user-images.githubusercontent.com/404840/230748053-5306224a-8a35-4ac4-b3a4-867090a0d4dd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

**Comment by jayesh-jain252** [comment]
@hugocostadev 
This same issue is occurring for "/" command popup

![image](https://user-images.githubusercontent.com/79307894/231755193-41aa3383-6801-4d34-82dc-c3c4ecb643f4.png)

As well as emoji popup. As per ComposerPopupProvider.tsx (apps/meteor/client/views/room/providers/ComposerPopupProvider.tsx) emoji list is sliced to return 10 items but it hides behind the message composer

![image](https://user-images.githubusercontent.com/79307894/231760859-ff93ad5e-3926-445a-bbe0-1776b591ef33.png)
(only 9 emojis are shown)

So I tried adding overflow:"auto" to Tile in (apps/meteor/app/ui-message/client/popup/ComposerBoxPopup.tsx)
![image](https://user-images.githubusercontent.com/79307894/231758003-fb0d270a-e200-402f-9cbb-4480b2beb5c7.png)

[emoji_slash.webm](https://user-images.githubusercontent.com/79307894/231758592-49360f0f-c30e-4691-9369-fb2be7c9d7a7.webm)

And this works for the user mention list as well. 

Is adding a scrollbar to the ComposerBoxPopup a good idea to solve this issue?
