### ISSUE TITLE
How do you add a command?

### ISSUE THREAD

**Issue by EngineerHus** [RocketChat/Rocket.Chat#28856]
Can someone guide in the right direction in how to add a new command to rocketchat server? I want to create a command called `/jira`. Is that possible? Thanks in advance

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

But GitHub is only for issues/bugs related to the repository project.

Quick answer: This is called slash commands 
This can be used with an existing app like the [Jira app](https://docs.rocket.chat/extend-rocket.chat-capabilities/rocket.chat-marketplace/rocket.chat-public-apps-guides/atlassian/jira-server-v2.0)
Or can be created using the [App Engine ](https://developer.rocket.chat/apps-engine/building-custom-apps/sample-app-snippets/extending-messages#create-the-slash-command)

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
