### ISSUE TITLE
Local Development issues

### ISSUE THREAD

**Issue by mehta0056** [RocketChat/Rocket.Chat#28855]
Hi,
Not able to setup rocket chat code on my local system. getting some dependencies issues. when I tried to install yarn.

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by vedant-pandey** [comment]
Hi can you share the error log that you are getting, since I was facing similar issue but was able to resolve it.

**Comment by mehta0056** [comment]
Hi Vedant,
below are the error that I am getting.
<img width="933" alt="image" src="https://user-images.githubusercontent.com/130342013/230864453-0d07d7d0-d6be-463c-843c-869ef28b07dc.png">

**Comment by vedant-pandey** [comment]
I got the same issue, if you look at the line at the end where it mentions a file path called `build.log` and open it. Probably it would give an error about node-gyp not being installed. This is some sync issue, you should try to do a `yarn add node-gyp` which would work. Since the recommended method of installing globally doesn't work

**Comment by mehta0056** [comment]
In the build log file below msg
# This file contains the result of Yarn building a package (@rocket.chat/forked-matrix-sdk-crypto-nodejs@npm:0.1.0-beta.12)
# Script name: postinstall

[31m[1mInternal Error[22m[39m: @rocket.chat/forked-matrix-sdk-crypto-nodejs@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at TR.getCandidates (C:\Users\nares\Downloads\Rocket.Chat-develop\Rocket.Chat-develop\.yarn\releases\yarn-3.2.2.cjs:435:5226)
    at wd.getCandidates (C:\Users\nares\Downloads\Rocket.Chat-develop\Rocket.Chat-develop\.yarn\releases\yarn-3.2.2.cjs:391:1281)
    at C:\Users\nares\Downloads\Rocket.Chat-develop\Rocket.Chat-develop\.yarn\releases\yarn-3.2.2.cjs:439:7764
    at Lg (C:\Users\nares\Downloads\Rocket.Chat-develop\Rocket.Chat-develop\.yarn\releases\yarn-3.2.2.cjs:390:11154)
    at ce (C:\Users\nares\Downloads\Rocket.Chat-develop\Rocket.Chat-develop\.yarn\releases\yarn-3.2.2.cjs:439:7744)

**Comment by vedant-pandey** [comment]
Did you do yarn install first, and installed meteor?

**Comment by mehta0056** [comment]
Yes I have installed yarn as well as meteor.

**Comment by vedant-pandey** [comment]
Check [this issue](https://github.com/RocketChat/Rocket.Chat/issues/25396)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Dhruwang** [comment]
@mehta0056 did you found the solution ?

**Comment by zhyzhy782** [comment]
> @mehta0056 did you found the solution ?

I also encountered this issue. how to resolve it? I can't got the solution.
