### ISSUE TITLE
Не обновляется список сообщений и статусов 

### ISSUE THREAD

**Issue by PElfimov** [RocketChat/Rocket.Chat#28850]
Шаги воспроизведения 

1. Приходит сообщение появляется звук и индикация 
2. перехожу к сообщению,  но текста сообщения нет и не исчезает индикация 
3. Перезапускаю рокет чат сообщение появляется и обновляется индикация 
4. Пои попытки отправить картинку ее в теле сообщения не видно пока не перезагрузил приложение чата 

Чат версии 3.8.19
ос MACOS 13.2.1 (22D68)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

If you want to continue this report, please, try to write in English and send more details about your environment.

By the way, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
