### ISSUE TITLE
Highlighting users not possible when the message has an attachment

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28852]
### Description:

If a message has an attachment (e.g. an image or a file of any other type), it is not possible to highlight users in that message. However, when editing such a message, suggestions for users to be highlighted are offered. This leads to the wrong impression that highlighting users is actually possible.

### Steps to reproduce:

1. Drag any file into a Rocket.Chat channel.
2. Enter a description for that file. When you try to highlight a user in that dialog, you will notice that you will not get any suggestions. "Manually" try to highlight a user anyway by typing an `@` sign followed by their username.
3. Submit the message. You will notice that the user is not highlighted.
4. Edit the message. Now, Rocket.Chat suggests users to be highlighted.
5. Select one of the suggested users and save the changes. You will notice that the user is not highlighted.

### Expected behavior:

I would expect Rocket.Chat to show consistent behaviour regarding messages with attachments.

- Either highlighting is possible, then usernames may also be suggested when uploading a file.
- Or highlighting is not possible. Then Rocket.Chat should not suggest usernames when editing a message that has an attachment.

### Actual behavior:

Messages with attachments look like the following after trying to highlight users:

![image](https://user-images.githubusercontent.com/404840/230783511-d94d1db8-391c-4722-9bc0-30bba1b5db54.png)

When editing a message, users are suggested for highlighting them:

https://user-images.githubusercontent.com/404840/230783694-3dded615-e329-4498-8242-0d53f73ddcde.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/25918
If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
