### ISSUE TITLE
Time format settings in Administration vanishing

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28869]
### Description:

After changing time format settings in the Administration, under certain circumstances the settings that have changed vanish.

### Steps to reproduce:

1. Login with an admin.
2. Navigate to Administration -> Settings -> Message
3. Change the setting(s) "Time Format", "Date Format", and/or "Time and Date Format".
4. Click "Save".
5. Click the "X" button to exit the Administration area.
6. Without taking any other action, click the kebab menu in the sidebar to navigate to Administration -> Settings -> Message

### Expected behavior:

All three time format settings are available.

### Actual behavior:

The setting(s) that have been changed in step 3 are missing. After clicking the refresh button in the browser, all time format settings are visible.

https://user-images.githubusercontent.com/404840/231004266-b52d494d-ee47-49ba-8972-67c6d66a6acd.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

- Arch Linux
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
- Windows 10 Pro 22H2, Build 19045.2788
  - Google Chrome Version 112.0.5615.50 (Offizieller Build) (64-Bit)
  - Microsoft Edge Version 112.0.1722.39 (Offizielles Build) (64-Bit)
  - Firefox 111.0.1 (64-bit)
  - Electron client 3.9.1

I could not reproduce this issue using Firefox 111.0.1 (64-bit) on Arch Linux.

### Additional context

As can be seen in the above video, I verified the problem in an Incognito tab to avoid problems related to cookies or browser extensions.

It is important that you exactly follow the above steps. These are examples of scenarios where the issue does not occur:

- If you click on Settings -> Message instead of steps 5 and 6 (i.e. you do not leave Administration)
- If between steps 5 and 6 you select a channel in the sidebar.

**Comment by hugocostadev** [comment]
Hi @paulchen I could not reproduce ... can you double check if still happening with the latest develop branch?

**Comment by paulchen** [comment]
> Hi @paulchen I could not reproduce ... can you double check if still happening with the latest develop branch?

I just tried the latest `develop` image from Docker Hub (`6.3.0-develop`, Git revision `3d3bf4d832`). Using that image, I can't reproduce the issue either.

Therefore, I close this issue now.
