### ISSUE TITLE
The Application GUI just Crashed

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#28864]
### Description:

Whenever click on the Files option in three dot menu, it' shows that The Application GUI just Crashed.

### Steps to reproduce:

1.click on three dot options
2. click on files

### Expected behavior:

This should be worked.

### Actual behavior:

https://user-images.githubusercontent.com/81948346/231004726-fe7de483-ed2d-4083-924e-8d16ab8309f0.mp4

### Server Setup Information:

-Version of Rocket.Chat Server: 6.0.0-develop
-Operating System: windows 10
-Deployment Method: Gitpod
-Number of Running Instances:
-DB Replicaset Oplog: Enabled
-NodeJS Version: 14.21.2 - x64
-MongoDB Version:5.0.5

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Console error: 
![image](https://user-images.githubusercontent.com/20212776/231143912-bc324b4e-e012-47c6-859f-64c970e68eb1.png)
