### ISSUE TITLE
Close button of Invite friend's Popup Diaglog in Game Center not working.

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#28865]
### Description:

Close button of Invite a friend's Popup Diaglog is not working.

### Steps to reproduce:

1. Click on Game Center
2. Add friend in any game
3. Click close button in Popup Diaglog

### Expected behavior:

This should work and there should be a cancel button.

### Actual behavior:

https://user-images.githubusercontent.com/81948346/231005826-90d1bc9b-ef5c-4233-a9b8-7af0d28bf9f3.mp4

### Server Setup Information:

-Version of Rocket.Chat Server: 6.0.0-develop
-Operating System: windows 10
-Deployment Method: Gitpod
-Number of Running Instances:
-DB Replicaset Oplog: Enabled
-NodeJS Version: 14.21.2 - x64
-MongoDB Version:5.0.5

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by vishalhampiholi** [comment]
Hi @hugocostadev  , I am first time contributor please help me to contribute to this issue

- I am not able to find the game center in my local ( version 6.2.0-develop)

**Comment by muzamil301** [comment]
@hugocostadev I would liek to work on this issue. Please let me know to link issue with PR or new branch or how can I assign this issue to myself

**Comment by Hanshika-Mehta** [comment]
Hello @hugocostadev  could you please assign this task to me , I have made projects in MERN stacks , so I know how to solve the issue , there is issue of the button  or a modal pop up property  but that can easily be sorted 
Thank you

**Comment by Ykumar1415** [comment]
Hello @hugocostadev could you please assign this task to me. i want to work on this issue.
