### ISSUE TITLE
preformatted as tooltip

### ISSUE THREAD

**Issue by hvma** [RocketChat/Rocket.Chat#2886]
the `preformatted` feature is kind of hidden. It would be neat if it showed alongside the other tool tips.... The Slack way, for reference purpose:
![preformatted](https://cloud.githubusercontent.com/assets/18415187/14526754/d478d7ce-0245-11e6-8355-54b60cfd7663.png)

Your Rocket.Chat version: 0.26

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as it has been implemented.

![image](https://user-images.githubusercontent.com/179595/35920536-6b5d28a6-0c18-11e8-9450-d888404da095.png)

I have just disovered another issue though - for that see: #9625

Cheers
Thomas
