### ISSUE TITLE
Quotes do not honor time format settings

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28863]
### Description:

The timestamp given in a quoted message does not honor time format settings (global and/or user-dependent).

### Steps to reproduce:

1. Login with an admin.
2. In Administration -> Settings -> Message, reset "Time Format" to its default value `LT`.
3. In My Account -> Preferences -> Localization, set the "Language" to "English".
4. In My Account -> Preferences -> Messages, reset the "Time Format" to "Default".
5. Write a message quoting another one.
6. Look at the timestamp of the quoted message.
7. In Administration -> Settings -> Message, set "Time Format" to `LTS`.
8. Look at the timestamp of the quoted message.
9. In Administration -> Settings -> Message, reset "Time Format" to its default value `LT`.
10. In My Account -> Preferences -> Messages, set the "Time Format" to "24-hour clock".
11. Look at the timestamp of the quoted message.

### Expected behavior:

In step 6, I would expect the timestamp to read `11:08 PM`.

In step 8, I would expect the timestamp to read `11:08:28 PM`.

In step 11, I would expect the timestamp to read `23:08`.

### Actual behavior:

The timestamp is always shown as `11:08 PM`.

Step 6:

![image](https://user-images.githubusercontent.com/404840/231000421-693cc84f-02d2-424a-8ada-9e6300ac8110.png)

Step 8:

![image](https://user-images.githubusercontent.com/404840/231000279-8c6652a9-16e4-4f19-9adf-40545ae9933c.png)

Step 11:

![image](https://user-images.githubusercontent.com/404840/231000506-06e6e348-6a1c-4c4b-8808-a0ec16c71996.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

The issue seems to occur with any combination of client and operating system.

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

### Additional context

The issue is further complicated by the user's language setting. I only documented what's happening in English.

In #25034, a similar issue is reported regarding the timestamp in the sidebar.

**Comment by ayush3160** [comment]
I am working on this issue
