### ISSUE TITLE
Links are not working in 6.1.1

### ISSUE THREAD

**Issue by ChrisJBurns** [RocketChat/Rocket.Chat#28880]
RocketChat Version: `6.1.1`

When we enter links into a message, they do not appear blue at all anymore. Links to website that are secured with a public certificate authority work fine. But internal links to URL's with self-signed certificates do not appear blue or clickable.

Example:

![image](https://user-images.githubusercontent.com/29541485/231460170-42f03659-fec2-4763-a417-b1e00e219107.png)

We have just finished upgrading from 3.9.7 (where this worked completely fine).

**Comment by hugocostadev** [comment]
Hi @ChrisJBurns , the new version of Rocket.Chat uses a new message-parser, and the new message-parser auto detects only valid TLD (Top Layer Domains). 

If you want to link custom TLD's you can set up our new setting called `Custom Domain Whitelist for Auto Link` that you can find at `Administration >  Message` and add your domain there. 

I hope that you fix your issue, if not, we can continue the discussion here. If you still face the problem, please, reopen this issue.

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by ChrisJBurns** [comment]
@hugocostadev  I can't seem to find that setting `"Custom Domain Whitelist for Auto Link"` under the URL `https://rocketchat.domain.com/admin/settings/Message`?

**Comment by ChrisJBurns** [comment]
Ahh, I've found the PR: https://github.com/RocketChat/Rocket.Chat/pull/28501 but it doesn't seem to be in `6.1.1` so I'm assuming it will be released in `6.2.0` as it's a new feature? Will be release this week?

**Comment by hugocostadev** [comment]
@ChrisJBurns Yes , it will be released with 6.2.0 

It's expected the Release Candidate to be released next Monday (17)
