### ISSUE TITLE
Group shared links in the sidebar, like with files.

### ISSUE THREAD

**Issue by elboletaire** [RocketChat/Rocket.Chat#2889]
Your Rocket.Chat version: 0.26.0

I've been searching for this issue in the issue list, but could not find it (if it exists, sorry!).

We use rocket chat in our work (like probably a lot more people) and we miss a feature that we think is very basic for our business: group the shared links in a tab, like it happens with files, starred or pinned posts.

**Comment by rore** [comment]
We recently started using rocket.chat and I just had the same thing in mind! Really missing it.

**Comment by RogerValentine** [comment]
Yes ! In chat.nuitdebout.fr 4000 users, we need that !

**Comment by hvma** [comment]
from IT university copenhagen : we need that too

**Comment by MartinSchoeler** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by elboletaire** [comment]
LOL, seriously? What about a "PR accepted" label and leave it open for the community?
