### ISSUE TITLE
README.md Broken Link

### ISSUE THREAD

**Issue by RayAsh37** [RocketChat/Rocket.Chat#28901]
### Description:
Clicking "How can I help?" on README.md leads to a broken link.

### Steps to reproduce:

1. Go [here](https://github.com/RocketChat/Rocket.Chat#contributions)
2. Click on "How can I help?"
3. Land on this page.
![Screenshot (2)](https://user-images.githubusercontent.com/70441807/231737027-e9e24e0a-eebe-4c9e-bd73-219d40f12901.png)

### Expected behavior:
I should have been redirected to this [page](https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute)

### Actual behavior:
I land on this [page](https://docs.rocket.chat/contribute-to-rocket.chat/how-can-i-help)

### Server Setup Information:
NA

**Comment by RayAsh37** [comment]
Additionally, the link named "How can I help?" is also redirecting to the above-mentioned link in the 'Expected behavior' section.
![Screenshot (4)](https://user-images.githubusercontent.com/70441807/231738364-d3ac2b0e-661f-467e-8e92-a50a67ecbe30.png)

**Comment by AnimeshRy** [comment]
@hugocostadev Any reason why broken links issues keep popping up. Saw the same issue in previous pages aswell ?

**Comment by RayAsh37** [comment]
@hugocostadev shall I close this issue on my end?

**Comment by hugocostadev** [comment]
> @hugocostadev shall I close this issue on my end?

No need... this issue will be closed automatically when the PR is merged

**Comment by hugocostadev** [comment]
fixed by: https://github.com/RocketChat/Rocket.Chat/pull/28943
