### ISSUE TITLE
Video call issue

### ISSUE THREAD

**Issue by murder666** [RocketChat/Rocket.Chat#2891]
Rocket.Chat version 0.25.0: (make sure you are running the latest)
When I click on the video call button, I see a black screen appears with the "Connection" inscription, then this screen disappears, and I can only see my screen.
May be it`s NAT issue ?

**Comment by jhagberg** [comment]
Same here we cant get the video calling to function. Is there any setup guide to read that can aid locating the problem. Running on a Ubuntu 14.04 VM.

**Comment by Arvi89** [comment]
Hello,
I tried with 0.30 this week, and I had a lot of issues making the video work consistently. I could make it work at home, but in the office, most of the time it didn't work at all, either people seeing a black square or just nothing happened.

**Comment by Sing-Li** [comment]
New solution testing this week.

On https://demo.rocket.chat

When you are in a Direct Message or Private Group. You will notice a new video button on the toolbar , just click it anytime to start a video conference with all those in the room

**Comment by kevincolten** [comment]
I like the convenience of the video conference button, but can we put a prompt asking the user if that's what they want to do? New users always end up clicking it see what it does and the channel becomes cluttered with the conference buttons and people apologizing, etc.
