### ISSUE TITLE
Show User's First and Last Name During Searches

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2892]
Your Rocket.Chat version: .26

Is it possible to append the user's first and last name during a search. The usernames on our system (connected to LDAP) are obscure and finding other users to mention or direct message while only knowing their first and last name makes it somewhat challenging. Maybe something like `user123 - John Doe`

**Comment by marceloschmidt** [comment]
I'll close this issue in favor of #874. We need to work on that issue ASAP, as there are multiple issues referring to the same request.
