### ISSUE TITLE
Update mongodb 4.4 to 5.0 in docker environment fails

### ISSUE THREAD

**Issue by jhjadmin** [RocketChat/Rocket.Chat#28923]
### Description:

After pulling the 5.0 bitnami/mongodb container coming from 4.4.15 the mongodb container stucks in restarting loop.

### Steps to reproduce:

1. Docker Compose environment with rocketchat 6.1.0 and mongodb 4.4
2. Update mongodb container to 5.0

### Expected behavior:

mongodb container starts normally

### Actual behavior:

mongodb container stucks in restarting loop

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.0
- Operating System: Debian 11 bullseye
- Deployment Method: docker and docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.2
- MongoDB Version: 4.4.15

### Relevant logs:

rocketchat container log:
```
/app/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
errorClass [Error]: [An error occurred when creating an index for collection "users: getaddrinfo ENOTFOUND mongodb]
    at Collection.createIndex (packages/mongo/collection.js:801:15)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1776:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)
    at packages/accounts-base/server_main.js:7:12
    at module (packages/accounts-base/server_main.js:19:31)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/packages/accounts-base.js:2192:15
    at /app/bundle/programs/server/packages/accounts-base.js:2199:3
    at /app/bundle/programs/server/boot.js:369:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:210:21
    at /app/bundle/programs/server/boot.js:423:7
    at Function.run (/app/bundle/programs/server/profile.js:256:14)
    at /app/bundle/programs/server/boot.js:422:13 {
  isClientSafe: true,
  error: 'An error occurred when creating an index for collection "users: getaddrinfo ENOTFOUND mongodb',
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

mongodb container log:
```
mongodb 07:41:37.86 Welcome to the Bitnami mongodb container
mongodb 07:41:37.86 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 07:41:37.86 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 07:41:37.86 
mongodb 07:41:37.86 INFO  ==> ** Starting MongoDB setup **
mongodb 07:41:37.89 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 07:41:37.91 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb 07:41:37.93 INFO  ==> Initializing MongoDB...
mongodb 07:41:37.96 INFO  ==> Deploying MongoDB with persisted data...

mongodb 07:41:37.99 INFO  ==> ** MongoDB setup finished! **
mongodb 07:41:38.02 INFO  ==> ** Starting MongoDB **
mongodb 07:41:44.97 
mongodb 07:41:44.97 Welcome to the Bitnami mongodb container
mongodb 07:41:44.97 Subscribe to project updates by watching https://github.com/bitnami/containers
mongodb 07:41:44.98 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mongodb 07:41:44.98 
mongodb 07:41:44.98 INFO  ==> ** Starting MongoDB setup **
mongodb 07:41:45.00 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 07:41:45.02 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mongodb 07:41:45.05 INFO  ==> Initializing MongoDB...
mongodb 07:41:45.08 INFO  ==> Deploying MongoDB with persisted data...
mongodb 07:41:45.11 INFO  ==> ** MongoDB setup finished! **

mongodb 07:41:45.15 INFO  ==> ** Starting MongoDB **
```

**Comment by debdutdeb** [comment]
> mongodb container log not helpful, because container stucks in reboot loop

That's why it's helpful, and needed to troubleshoot this. Please add that.

**Comment by Nasirahamad88** [comment]
It seems like there's an error in creating an index for the "users" collection in MongoDB. The error message indicates that there was a failure in performing a DNS lookup for the MongoDB server, as indicated by the "getaddrinfo ENOTFOUND mongodb" part of the error message.

**Comment by Nasirahamad88** [comment]
check that the hostname or IP on mongodb server

**Comment by debdutdeb** [comment]
> check that the hostname or IP on mongodb server

Not needed. That error is popping up because mongo container is failing to start up. So we need mongo logs to now understand why that's failing.

**Comment by jhjadmin** [comment]
Added the mongodb log.

**Comment by jhjadmin** [comment]
> check that the hostname or IP on mongodb server

What do you mean by this? IP of the container and container name?

**Comment by jhjadmin** [comment]
The problem was, that my instance is running as a proxmox vm and the CPU feature AVX was not enabled. MongoDB 5+ needs that:
https://github.com/bitnami/charts/issues/12834

I migrated the vm to a host which CPU supports AVX and then I set the CPU mode of the VM from kvm64 to host (it is proxmox specific I think). After that, I could update the container.
