### ISSUE TITLE
Standalone Server Option is missing -> Can not finish setup

### ISSUE THREAD

**Issue by maxdata** [RocketChat/Rocket.Chat#28932]
Standalone Server Option is missing -> Can not finish setup.

I have recently installed Rocket.Chat version 6.0.0 using docker compose, but I have encountered an issue during the setup process. 
The Standalone Server option is missing from the setup wizard, which prevents me from completing the setup.

When I try to register the server, I do not receive a confirmation email, and the workspace is not accessible. 
If I reload the page, it displays setup wizard step 2 again.

I am reaching out for assistance in resolving this issue and completing the server setup. Can you please advise me on how to proceed?

Thank you for your help.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project. Next time go to our Forum or Open app.

Answering your question, to bypass the cloud registration you can temporally disable the internet connection and it'll give you the option to register as a standalone, or you can block temporally the request for `cloud.registerPreIntent`. This was done to let Air gaped environment continue with the setup. But we recommend to register the workspace if you want to deploy it to production.

We are investigating a way to disable that for development purposes. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
