### ISSUE TITLE
Last version download link broken

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#28934]
https://releases.rocket.chat/latest/download is not working anymore.

**Comment by knordsiek** [comment]
Same here

**Comment by bognerf** [comment]
Same here.

**Comment by CAberry** [comment]
Confirmed ! :+1: 

![image](https://user-images.githubusercontent.com/35067345/232476039-bfcb45f6-a7ab-4de9-914c-22f22985e54e.png)
