### ISSUE TITLE
What Is The Default API Auth Token Expiration?

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2894]
Your Rocket.Chat version: 0.26

I've just started working with the API and I was wondering what the default auth token expiration time is? The doc mentions to implement our own, but I was just wondering if there was any default one implemented or if the one that is generated does not expire.

**Comment by marceloschmidt** [comment]
Server defaults at 90 days.

**Comment by lucasdidur** [comment]
Can I change this value? Or disable token expiration?

**Comment by RedJohn14** [comment]
Any news on this case? How disable token expiration?

**Comment by RedJohn14** [comment]
How disable token expiration? I use the RocketChat API for some scripts to send me notifications. In regular intervals I must renew the API Token. I search for an option to get a never expire API token for my notifications user.
