### ISSUE TITLE
Wrong time for TimeZone America/Mexico_City

### ISSUE THREAD

**Issue by arantuna** [RocketChat/Rocket.Chat#28959]

**Comment by hugocostadev** [comment]
Please, follow the issue template 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
