### ISSUE TITLE
Can't skip setup wizard

### ISSUE THREAD

**Issue by Amir0715** [RocketChat/Rocket.Chat#28978]
Hi. I want to change the server on which my RocketChat is running in the container. To do this, I made a mongodb dump and restored this dump in a new container on a new server. 
Next step, I launched the container with RocketChat and expected it to be delivered. 
I also passed the OVERWRITE_SETTING_Show_Setup_Wizard parameter in the environment variable: "completed"
But unfortunately it didn't help me skip the app installation page. 

How do I skip the installation step?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Check it here, please: https://github.com/RocketChat/Rocket.Chat/issues/28932

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
