### ISSUE TITLE
Make Role Tags optional and configurable

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#2899]
Your Rocket.Chat version: (make sure you are running the latest) 0.26

Can we make Role Tags #2858 optional, and the tag text content configurable? 

It adds visual clutter to the message view, having every regular user marked with a 'Users' tag is unnecessary

I'd like to be able to:

- turn this feature off completely 
- use this feature only for certain roles (eg show the 'Admin' Tag on an admin user, but not to other roles)
- customise text shown in each tag (maybe this is already possible by changing the Role name?)

**Comment by RichardFoxworthy** [comment]
Ah! I figured it out. Can modify role description field in Admin and control this. So all good...

**Comment by zxweed** [comment]
@RichardFoxworthy, where this admin panel are? I need to to mark only admins and moderators, not users...

**Comment by RichardFoxworthy** [comment]
Hi zxweed it is under Administration / Permissions menu. You can customise
the text for Role description or leave it blank. Cheers

On Tue, 19 Apr 2016, 8:48 PM zxweed <notifications@github.com> wrote:

> @RichardFoxworthy <https://github.com/RichardFoxworthy>, where this admin
> panel are? I need to to mark only admins and moderators, not users...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/2899#issuecomment-211855426>
>
-- 
-- 
*Richard Foxworthy*
Co-founder, CEO
4th Party
+61 447 367 915
www.4thparty.com.au
richard.foxworthy@4thparty.com.au
PGP: http://www.4thparty.com.au/pgp
