### ISSUE TITLE
Mentioning in Description of Picture Upload not working

### ISSUE THREAD

**Issue by tommy-whatsoever** [RocketChat/Rocket.Chat#28991]
### Description:

If you open the picture upload modal in a group chat, it is not possible to mention a person via @-sign. The mentioning is just shown as clear text.

### Steps to reproduce:

1. Open a Group or 1-to-1 chat
2. Drag and drop an image into the chat
3. Fill out the picture description and try to link a person via @-sign

### Expected behavior:

The person should be mentioned, the full name should be shown in the chat message and the person should get a notice being mentioned

### Actual behavior:

The @-tagged person is just shown as normal text in the chat window
![Bildschirm­foto-2023-04-20-um-14 02 35](https://user-images.githubusercontent.com/12498995/233360795-d144d741-9556-4349-bc24-20a3fa183519.jpg)
### Server Setup Information:

Not available for me.

### Client Setup Information

- Desktop App or Browser Version: rocket.chat 3.9.3
- Operating System: macOS Ventura 13.1

**Comment by hugocostadev** [comment]
duplicated: https://github.com/RocketChat/Rocket.Chat/issues/25918
