### ISSUE TITLE
[BUG] OAuth password setting affects basic user authentication

### ISSUE THREAD

**Issue by rmaksimov** [RocketChat/Rocket.Chat#29018]
### Description:
Disabling the "Allow Password Change for OAuth Users" option makes it impossible to change password for internal RC users. The "New Password" field becomes disabled and the following description appears:
> Your Rocket.Chat administrator has disabled the changing of passwords

### Steps to reproduce:
1. Administration -> Settings -> Accounts
2. Disable "Allow Password Change for OAuth Users"
3. Go to My Account and try to change password

### Expected behavior:
The "Allow Password Change for OAuth Users" option must not affect basic username/password authentication

### Actual behavior:
Administration settings
![Screenshot from 2023-04-24 11-12-16](https://user-images.githubusercontent.com/2904679/233940547-ae500ccd-249a-4bd6-8f00-a9384c700157.png)

User profile
![Screenshot from 2023-04-24 11-11-46](https://user-images.githubusercontent.com/2904679/233940525-20533189-d956-476a-8dbc-39d81a46af2f.png)

### Server Setup Information:
- Version of Rocket.Chat Server: 6.1.4
- Deployment Method: tar
- MongoDB Version: 6.0

**Comment by Ninad3721** [comment]
Hello @rmaksimov I tried to recreate issue by.
1.By disabling the "Allow password change for OAuth Users" from admin profile.
2.Opening a USER profile in incognito tab.
3.Changing the password.

I was able to change the normal password, Am I doing something wrong here ?

**Comment by rmaksimov** [comment]
hi, @Ninad3721, steps to reproduce are correct, so I don't know what's wrong
I have been using RC from ~3.x versions and updated it by building from source code from GH
the problem has appeared on 6.x versions (but I don't know which one)

**Comment by rmaksimov** [comment]
fixed in ~6.2.2
