### ISSUE TITLE
Rocketchat sever suddenly shut down

### ISSUE THREAD

**Issue by willychanggggg** [RocketChat/Rocket.Chat#29016]
The rocketchat server shut down, all members cannot use, even use api, could someone tell me the what is the issue? 
We use cloud not host by ourselves
![image](https://user-images.githubusercontent.com/117712366/233786537-f6d14dbd-0628-44d6-b1a0-dfc2dadffe3f.png)

**Comment by hugocostadev** [comment]
Hi there, are you still experiencing this issue? 

Should be fixed by now, right? 

If not, reopen this issue, please
