### ISSUE TITLE
[BUG] Cursor reverts back to starting position in AI assist modal input

### ISSUE THREAD

**Issue by XshubhamX** [RocketChat/Rocket.Chat#29015]
Description:

Inside the AI assist model the cursor revert back to the starting position after writing one letter.

Steps to reproduce:

1. Click on the AI assist button near message composer toolbox.
2. Then remove the place holder text.
3. Click outside of the input box.
4. Click the input box again and start writing.

You will observe that after writing 1st letter the cursor reverts back to the starting position

Below video will make more sense.

https://user-images.githubusercontent.com/63532716/233779768-12d0fafe-a68e-47f5-92b7-e7f57601e68e.mov

Server Setup Information:
Version of Rocket.Chat Server: 6.0.1
Operating System: MacOS

----------------------------------------------------------------------------------------------------------------

cc @yash-rajpal

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project. This issue it's related with a private app, I'll send it to the responsible team

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
