### ISSUE TITLE
Make it possible to select active languages

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2902]
Your Rocket.Chat version: 0.26

I am not aware of any setting to specify which languages that should be active on the server.
Many of the translations are incomplete (trying to keep the Swedish one alive)

I would  be nice if there was a setting where you could specify active languages on the server.

**Comment by marceloschmidt** [comment]
There is, it's under Administration / General => Language
![image](https://cloud.githubusercontent.com/assets/1986378/14932999/6e098c0e-0e57-11e6-8343-a4c68fdfcb69.png)

Keep in mind that users will still be able to override this with their own language preferences.
