### ISSUE TITLE
Free Trial - Restricted access

### ISSUE THREAD

**Issue by YOKESHCR** [RocketChat/Rocket.Chat#29030]
Currently the free trial for Rocket Chat can only be accessed if the the Organization email regarding to the office is given.

I might recommend you to include all valid User emails including Gmail accounts so that I can also contribute to the code.

![image](https://user-images.githubusercontent.com/27686539/234098769-c4be7b49-c7d7-4d91-839c-25e8a4c28d96.png)

Thanks,
Yokesh.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

It's great to hear that you want to contribute with the code! If you want check it out functionalities go to our open.rocket.chat open community. You can also self host or run locally the code. Welcome 


Sorry, but GitHub is only for issues/bugs related to the repository project, closing for now.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
