### ISSUE TITLE
Outgoing webhook response not working

### ISSUE THREAD

**Issue by edonit-moitend** [RocketChat/Rocket.Chat#2903]
Rocket.Chat version: 0.26.0

I am sending outgoing webhook and the API receives it fine, and tries to return a response in JSON but the message does not show and I got this error on Logs:

`Exception in callback of async function: Error: [methods] joinRoom -> Not allowed [403]     at [object Object].Meteor.methods.joinRoom (server/methods/joinRoom.coffee:10:14)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:1611:18     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at [object Object]._.extend.apply (livedata_server.js:1610:45)     at [object Object]._.extend.call (livedata_server.js:1553:17)     at [object Object].<anonymous> (server/processWebhookMessage.js:36:20)     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) `

**Comment by edonit-moitend** [comment]
I do not know how but it started to work, maybe after I restart the RocketChat service.

**Comment by irmela** [comment]
I'm getting the same error with the RocketGif Integration. It worked at first and then stopped working and creating this error. Restart Server didn't work.
Version: 0.28.0 

`Exception in callback of async function: Error: [methods] joinRoom -> Not allowed [403]     at [object Object].Meteor.methods.joinRoom (server/methods/joinRoom.coffee:10:14)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:1611:18     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at [object Object]._.extend.apply (livedata_server.js:1610:45)     at [object Object]._.extend.call (livedata_server.js:1553:17)     at [object Object].<anonymous> (server/processWebhookMessage.js:36:20)     at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) `
