### ISSUE TITLE
Number of group members wrongly replaced with number of online group members

### ISSUE THREAD

**Issue by Zack-83** [RocketChat/Rocket.Chat#29041]
Hallo,

thanks for developing this cool functional chat system!

On a channel, when expanding the members list, the default behavior is to show only the users who are online.

[FEATURE REQUEST] It would be preferable to show all users as the default, or at least allow choosing the initial view via a setting.

[BUG] The caption appearing over the list reports the same number for online users and total users (in this screenshot it reads: "Show: 3 Total: 3"). This is really misleading! The second number should correspond to the real total number of group members.

![image](https://user-images.githubusercontent.com/37865804/234240305-738e7e3b-00ad-4302-b017-4310e05ac09f.png)

**Comment by anikdhabal** [comment]
I think it's working fine. **Showing:** is defined the rendered items and Teams Members is defined the total number of users is online. Same when the status is **All**, **total:** is defined the total number of users. And eventually when you scroll down the showing: number is increasing.


![Screenshot 2023-04-28 022051](https://user-images.githubusercontent.com/81948346/234986403-2af666bc-3edb-4597-ab1e-a88296b58c0b.jpg)

What do you think @hugocostadev?

**Comment by hugocostadev** [comment]
yes, it's working fine @anikdhabal ... 
I think that @Zack-83 mentioned that could be misleading to the end user and could get confused by the `Total` field being the Total members of the room

**Comment by anikdhabal** [comment]
understood
