### ISSUE TITLE
How to fully migrate from mattermost? 

### ISSUE THREAD

**Issue by olodar** [RocketChat/Rocket.Chat#29040]
Hi, is there any way to migrate from mattermost? I mean, import all posts/threads, including all attachments and messages structure, including saved posts (which in rocketchat called "starred"). Mattermost supports so called bulk export, but how to import this in rocketchat?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

Check it out this docs to accomplish that: https://docs.rocket.chat/use-rocket.chat/workspace-administration/import/import-csv 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
