### ISSUE TITLE
The application GUI just crashed when try to open SlackBridge

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29044]
### Description:

The application GUI just crashed when try to open SlackBridge inside Settings.

### Steps to reproduce:

1.  Go to Administration
3. Click on workspace
4. settings->SlackBridge

### Expected behavior:

Work properly.

### Actual behavior:

https://user-images.githubusercontent.com/81948346/234309510-c962efd4-124d-4746-9e13-51a70d2cc419.mp4

### Server Setup Information:

-Version of Rocket.Chat Server: 6.3.0-develop
-Operating System: windows 10
-Deployment Method: Gitpod
-Number of Running Instances:
-DB Replicaset Oplog: Enabled
-NodeJS Version: 14.21.3 - x64
-MongoDB Version:6.0.3

**Comment by casalsgh** [comment]
Team is aware and working to fix. 
PS: Version for fix expected to be 6.2.0 release

**Comment by anikdhabal** [comment]
@casalsgh I wanted to make a Pr on this issue

**Comment by hugocostadev** [comment]
Fixed here: https://github.com/RocketChat/Rocket.Chat/pull/29050

Thanks for your contribution
