### ISSUE TITLE
Clicking a quoted message doesn't scroll the chat to the original message

### ISSUE THREAD

**Issue by filipa-lourenco** [RocketChat/Rocket.Chat#29059]
### Description:

A user quotes a message and sends it in the chat. Another user wants to see the original message and navigate to it, so the user tries double-clicking the quoted message. The expected behaviour is that by clicking the quote the user will be able to navigate in the chat to the original message, but that doesn´t happen. The user has to click the date to navigate to the original message, which doesn't seem like an obvious solution. 
It would be better if the user could navigate to the original message by double-clicking anywhere on the quoted message.
bug is.

### Steps to reproduce:

1. Quote a message in a chat
2. Try to navigate to the original message by clicking anywhere on the quoted message

### Expected behavior:

I expect as a user to be able to navigate to the original message that was quoted in a simple way. I expect that by double-clicking anywhere on the quoted message the chat will scroll up to show me the original message.

### Actual behavior:

Clicking anywhere on the quoted message produces no effect. The only thing that navigates me to the original message is clicking on the date. This doesn´t feel like an obvious action to a user.

### Server Setup Information:

Version of Rocket.Chat Server: 6.0.0
Operating System: Ubuntu Server 22.04
Deployment Method: Docker
Number of Running Instances: 1
App Engine-version: 1.37.0-alpha.164
Nodversion: v14.21.2
Migration of database: 292 (11 april 2023 kl. 16:18)
MongoDB: 5.0.15 / wiredTiger (oplog activated)

### Client Setup Information

- Desktop App or Browser Version: Desktop app, version 3.9.3
- Operating System: Windows 11 64bit

See the recording:

https://user-images.githubusercontent.com/129831842/234587804-2c02832a-19fd-4fb4-b7f6-07680097342e.mp4

**Comment by hugocostadev** [comment]
Hi there, thanks for raising this issue, we'll discuss internally with our UX/UI team and get back to you soon

**Comment by jsdgdo** [comment]
Hey @filipa-lourenco, appreciate you taking the time to bring this up to us. 

As we intended, quoting a message is actually to build upon something that was written before, this is why we show the full content of the message. This also means that not always the person reading the quoted message would have access to the room on which it was originally written, we have to be mindful about which content is accessed by which people. 

If you want to give a reference to a message in the current context, you can always **share the link to a message**, this will make its contents available wherever is shared but the person reading will also have access to it in the original context by clicking the link (provided they have the permissions to see it). 

All of this to say, quoting is behaving as it was intended to.
