### ISSUE TITLE
Horizontally stack the previews if urls are in one message

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2905]
Your Rocket.Chat version: 0.31

It would be great to compact the space of previews by stacking pictures (only pictures, not pages links) horizontally if their urls are in one or sequential messages:

![image](https://cloud.githubusercontent.com/assets/16319433/14566053/8ae95100-0336-11e6-8a5e-6a39ee407e73.png)

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap so we will revisit once other priorities have been addressed.
