### ISSUE TITLE
A quoted message that includes a file creates a link but is not clickable

### ISSUE THREAD

**Issue by filipa-lourenco** [RocketChat/Rocket.Chat#29061]
### Description:

A user sends a file in the chat, another user quotes this message that includes a file. In the quoted message the file appears as a clickable link, but clicking this link opens a browser window with an error message. It is difficult to figure out how to get to the original message with the file, the only way is to click the date in the quoted message. This doesn´t feel obvious from a user standpoint.

### Steps to reproduce:

1. Send a message in a chat that includes an attached file.
2. Quote that message.
3. Try to open the file.

### Expected behavior:

The expected behaviour is that link shown to represent the file will navigate the user to the original message where the file was sent OR open the file directly. 

### Actual behavior:

By clicking the link the user gets a browser window with an error message since the file could not be opened. When the user tries to figure out how to find the original file that was quoted it is not obvious how to find it, the user has to click the date on the message under the quote.

### Server Setup Information:

Version of Rocket.Chat Server: 6.0.0
Operating System: Ubuntu Server 22.04
Deployment Method: Docker
Number of Running Instances: 1
App Engine-version: 1.37.0-alpha.164
Nodversion: v14.21.2
Migration of database: 292 (11 april 2023 kl. 16:18)
MongoDB: 5.0.15 / wiredTiger (oplog activated)

### Client Setup Information

- Desktop App or Browser Version: Desktop app, 3.9.3
- Operating System: Windows 11 64bit

### Additional context

See recording for an example of the behaviour.

https://user-images.githubusercontent.com/129831842/234587108-55570a77-7780-4332-9158-fade3f5fc6b7.mp4

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/29059

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
