### ISSUE TITLE
Make the "compact mode" really compact

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2906]
Your Rocket.Chat version: 0.26

The "compact mode" must be more compact to fit the small netbook's screens (1366*768). So it would be nice to hide avatars, show smaller previews (80px height), make the interline space smaller and so on:

![image](https://cloud.githubusercontent.com/assets/16319433/14566636/05ca7fbe-0339-11e6-9a12-abd4c7cdaf9e.png)

**Comment by lvh1** [comment]
You could use this as custom css to make it more compact: 
https://gist.github.com/lvh1/3b9c77b2bef7401010bec4250e9d5ba9
this would make it look like this: ![](https://i.imgur.com/eCENlgf.png)

**Comment by zxweed** [comment]
@lvh1, thank you, this css style looks great. 

May be devteam make it default in the compact mode? The difference between styles are very insensible now...

**Comment by lvh1** [comment]
Maybe they could add a third, 'ultra compact' mode so people have more choice, that would be great :)

**Comment by engelgabriel** [comment]
Can you do a PR with this?

**Comment by lvh1** [comment]
Sure thing.

**Comment by engelgabriel** [comment]
Lets make it as a extra option, and I'd put the cogs and time stamps on the far right

**Comment by bott0r** [comment]
yes please see also https://github.com/RocketChat/Rocket.Chat/issues/2881 and https://github.com/RocketChat/Rocket.Chat/pull/1377

**Comment by bott0r** [comment]
@lucasvanhalst Can you repost the custom CSS script

**Comment by lucasvanhalst** [comment]
@bott0r https://gist.github.com/lucasvanhalst/3b9c77b2bef7401010bec4250e9d5ba9
