### ISSUE TITLE
App crash when deleting discussion

### ISSUE THREAD

**Issue by amirAlamian** [RocketChat/Rocket.Chat#29060]
I deployed the latest version of the Rocket.Chat repository and When I want to remove my discussion, web page redirected me to /home page but it loaded like this
![image](https://user-images.githubusercontent.com/65771812/234585053-8e11d6f4-a4f5-4e43-b98e-9b25a3930320.png)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

I could not reproduce with the latest `develop` branch, could you try again or provide us more info about the version that you are running and your environment settings?  Try to follow the issue template, please

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by amirAlamian** [comment]
I tried master branch

**Comment by hugocostadev** [comment]
Please, send more info about your server and environment... try with the `develop` branch or one of the latest releases

**Comment by amirAlamian** [comment]
my OS is ubuntu 22.04 desktop and Iam using mongodb version 5 with node version 14.21.2

**Comment by amirAlamian** [comment]
any progress?

**Comment by hugocostadev** [comment]
Can you test again with the latest 6.2.0 release, please?  I still could not reproduce

**Comment by amirAlamian** [comment]
It seems like Its fixes thanks

**Comment by amirAlamian** [comment]
It seems like Its fixed thanks
