### ISSUE TITLE
File uploads / Downloads broken

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#2907]
Your Rocket.Chat version: 0.26.0

We are seeing an issue with file uploads & downloads.  I can't reproduce it every time but I think it's associated w/ copy/pasting clipboard images. (which we do frequently for messaging bugs in our UI or system)

How it shows up on my end.
![capture3](https://cloud.githubusercontent.com/assets/10718586/14568377/c138405e-02f5-11e6-828a-eab010d3eb50.JPG)

On the other end there is no preview, and a download results in: 
![clipboard](https://cloud.githubusercontent.com/assets/10718586/14568037/5bb6ce68-02f4-11e6-9059-e9217f5f1bae.jpg)

And how it shows up in the file list sidebar (Notice it doesn't show as a picture like the others)
![clipboard2](https://cloud.githubusercontent.com/assets/10718586/14568362/b18c4c36-02f5-11e6-8e60-4160fb465cf9.jpg)

**Comment by engelgabriel** [comment]
What file storage are you using?

**Comment by twhiting** [comment]
Default: GridFS

It's finicky, hopefully you guys can repro because it isn't always broken for us. Just a couple times today

**Comment by engelgabriel** [comment]
Does it have anything to do with filenames?
Why dont you guys move to S3? It is far more stable.

**Comment by twhiting** [comment]
@engelgabriel We will do that and i'll report here.  I have no experience with any of it so let me see if that helps and i'll report back here.

**Comment by lunitic** [comment]
Seeing the same thing with clipboards.  Will do more investigation.  We use snippet tool in Windows a lot to do screens hots.  The user who did the upload don't see it until he so a refresh in browser.  Griefs here to

**Comment by lunitic** [comment]
Extra information.  I run 3 instances on the machine at.  If it could have something with load balancing to do?

**Comment by engelgabriel** [comment]
GridFS can be very CPU intensive, and sometimes causes the process to HALT while is serving the file to multiple users. I works ok for small teams, but if you are building a services to scale, move away from GridFS, it is not meant for that.

**Comment by lunitic** [comment]
The you suggest local storage?

**Comment by M4v3R** [comment]
@twhiting Can you check if it always works the first time you try, but fails on subsequent tries. And then if you hit refresh in the browser it works again (for one time)? Because that's what was happening for me.

**Comment by wtsarchive** [comment]
@twhiting Can you check if it always works the first time you try, but fails on subsequent tries. And then if you hit refresh in the browser it works again (for one time)? Because that's what was happening for me.

**Comment by lunitic** [comment]
@engelgabriel This happens on my Lab server with 5 ppl.

**Comment by engelgabriel** [comment]
From what @wtsarchive have described, we may have two different issues here.
1. There may be a permission but if it only works the first time. Can you give more log info?
2. GridFS is not meant for scale, you should use the Local File System (with shared volume if using multiple dockers) or you should  use S3, Google Cloud Storage or Rackspace Cloud Files.

**Comment by andreas-bulling** [comment]
maybe related to #2718

Upload doesn't always fail - sometimes it does work, which sounds similar to what @lunitic and @twhiting have described

**Comment by miscs** [comment]
what we see with 0.26 and 0.27 is that file-uplaods works the first time for a file but not later on when trying to upload the same file again. we use file-system as storage.

easy to reproduce: upload a large image. cancel while uploading. try again -> nothing happens.

**Comment by andreas-bulling** [comment]
I observe the same thing

**Comment by twhiting** [comment]
Yea we are still having the problem,  @engelgabriel suggested we use S3 and I would except for our company doesn't want to pay for amazon services if we don't have to.  We would like to stick with storing our data locally.

**Comment by engelgabriel** [comment]
@twhiting did you try using Local File System?

**Comment by twhiting** [comment]
Yep, also broken. 

If I use the snipping tool on windows to copy and image, paste it into slack, hit upload. 
1. With GridFS the file is unviewable / broken
2. With local filesystem. the upload won't ever upload, the progress bar goes up to about 75% then drops back down to zero percent:
![file](https://cloud.githubusercontent.com/assets/10718586/14683039/e50d6380-06e5-11e6-9940-c0df6b81cf99.JPG)

**Comment by engelgabriel** [comment]
Are you  using version 0.27.0? 
Are you using NGINX?
Can you turn DEBUG mode in admin panel and see  go to View Logs?
We will do some more here with you info.

**Comment by twhiting** [comment]
0.27.0, NGINX via Proxy/ReverseProxy

When I uploaded some clipboard screenshots via the client, then logged in via Chrome, The messages are un-viewable (They don't seem to load in the browser, or the the client if another person is viewing).   
![thumb](https://cloud.githubusercontent.com/assets/10718586/14683521/602dc88c-06e8-11e6-938e-dd252bda24de.JPG)

Then when I click the download button, this is what appears in the logs for each click I do. 
![log](https://cloud.githubusercontent.com/assets/10718586/14683527/666a0256-06e8-11e6-84f3-ee359e641afe.JPG)

**Comment by engelgabriel** [comment]
Hi guys, is this still a problem in the current release?

**Comment by DonatasFe** [comment]
Hi, we are experiencing the same on Windows Clients.  Our error we during file/image download is:
The image “https://our-domain.com/file-upload/ZTkvoZb9LB6bPaSbh/boss%20day.jpg” cannot be displayed because it contains errors."

The download is working directly from web client. 
Version: 0.42.0
Node version: v4.5.0

**Comment by engelgabriel** [comment]
This has now been fixed.
