### ISSUE TITLE
How to downgrade version 6 to version 5 using snap

### ISSUE THREAD

**Issue by shibiriba** [RocketChat/Rocket.Chat#29091]
I upgraded my rocketchat server from version 5, which was excellent, to version 6 which seemed to be better, however a number of useful features that were previously free were removed in this version, I would like to know how to downgrade using snap.

**Comment by geekgonecrazy** [comment]
You'd need to set the track and then fix the broken migrations to let Rocket.Chat start back up.  Easier is downgrade and restore from backup.

Going to close as this isn't really a bug.
