### ISSUE TITLE
Team members or members menu is not working perfectly.

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29094]
### Description:

when opening team members or members of a team or channel I observe something. 

1.) Let suppose if the type of Team Members is ALL, then you are able to scroll to end of the list. But after selecting the type ONLINE, you see that the total is showing 10 and you are not able to scroll. And vise-versa for type ONLINE -> ALL.

https://user-images.githubusercontent.com/81948346/235235148-194a656c-0276-4b5c-a480-ddf2cec67985.mp4

2.) It's working fine when the scrollbar position is changed before selecting the other type.

https://user-images.githubusercontent.com/81948346/235235639-a2e0587d-c78a-4143-8492-3ab936299f22.mp4

### Steps to reproduce:

1. Go to Team members 

### Expected behavior:

It's should work fine without changing the scroll bar position.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop 
- Operating System: Windows 10
- Deployment Method: Gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3 - x64                                                     
- MongoDB Version:6.0.3

**Comment by yash-rajpal** [comment]
Fixed by #28636 

Thanks for reporting.
