### ISSUE TITLE
_*ib*_ doen't work

### ISSUE THREAD

**Issue by Blaumeiser** [RocketChat/Rocket.Chat#291]
Combining _ * to have italic bold-combos does't work. Example:
_i_ -> ok
*b* -> ok
_*ib*_ -> nok
*_bi_* -> nok

**Comment by sampaiodiego** [comment]
seems that doesn't work on github too :laughing:

**Comment by haosdent** [comment]
Other markdown editor also not support this.

**Comment by sampaiodiego** [comment]
@engelgabriel is this fixed? won't be supported?

**Comment by sampaiodiego** [comment]
fyi: in github two characters means bold either * ou _ .. one of them means italic.. three of them are bold **and** italic.

**Comment by sampaiodiego** [comment]
well, this is now officially supported @Blaumeiser
