### ISSUE TITLE
New Contact is not visible after saving.

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29103]
### Description:

When saving a new contact after creating, the contact is not visible in the contact list at that time. It is visible after came back to contact list from another menu.
### Steps to reproduce:

1. Go to omnichannel contact center
2. Click on new contact

### Expected behavior:

It should visible at the of saving.

### Actual behavior:

https://user-images.githubusercontent.com/81948346/235470234-182f27a1-8fbd-4ea1-9cf7-a1ab73b23d1f.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: windows 10
- Deployment Method: Gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3 - x64
- MongoDB Version:6.0.3

**Comment by wilsonfurtado2000** [comment]
cani work on this issue ?

**Comment by mHasnaat-Iftikhar** [comment]
If that issue is still not resolved. So, can I start working onn that?

**Comment by Ykumar1415** [comment]
i want to work on this issue i have solved similar problem before. please sir assign i t to me .

**Comment by Keanby** [comment]
We need do reload http://localhost:3000/api/v1/livechat/visitors.search

**Comment by nikhil-babar** [comment]
If this issue is not being resolved, can I start working on it?
