### ISSUE TITLE
Send message to guests?

### ISSUE THREAD

**Issue by opinaka** [RocketChat/Rocket.Chat#29105]
Is it possible to use the Rockchat API to send messages to guests, based on the information provided by omnichannel webhooks?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

Ask your question in our Forum, please...

But check it out this API, maybe will help you: https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/livechat-endpoints/livechat-message/livechat-send-new-message 



---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by JankinHou** [comment]
> 您好，感谢您提出问题！🚀 💯
> 
> 抱歉，GitHub 仅适用于与存储库项目相关的问题/错误。
> 
> 在我们的论坛中提出您的问题，请...
> 
> 但是看看这个 API，也许会帮助你： https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/livechat-endpoints/livechat-message/livechat-send-new-message
> 
> **问题？需要帮助吗？功能请求？**
> 
> * 加入我们的 Open [Server](https://open.rocket.chat/) #support 频道，随时提出问题
> * 加入我们的社区[论坛](https://forums.rocket.chat/)并在那里搜索/创建帖子
> * 功能请求：在[功能请求](https://github.com/RocketChat/feature-requests)存储库中打开问题

您好。我使用该接口，推送消息的时候，在聊天室里显示的是客户发送的消息，这个不是应该实现bot主动给客户推送消息吗
