### ISSUE TITLE
Markdown links don't work anymore if title contains parenthesis in 6.x

### ISSUE THREAD

**Issue by TBG-FR** [RocketChat/Rocket.Chat#29108]
### Description:

Markdown links don't work anymore (they're not handled as links) if their title contains parenthesis.

### Steps to reproduce:

1. Open any channel or private conversation in RocketChat 6.x
2. Send a message with the following content
```
[This link (is not) working](https://www.rocket.chat/)
[This link is working](https://www.rocket.chat/)
```
3. Check the resulting behaviour after sending the message

### Expected behavior:

Both links should work and be clickable, as below
[This link (is not) working](https://www.rocket.chat/)
[This link is working](https://www.rocket.chat/)

### Actual behavior:

One of the link isn't working, because of the parenthesis inside the title
![image](https://user-images.githubusercontent.com/18146038/235666125-43983411-bb8a-4176-b55a-1f40953eb611.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.5
- Operating System: Linux
- Deployment Method: Docker

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows, Linux

### Additional context

We're thinking that the markdown interpretor/editor changed with the 6.x version, because it was working well before we update the Rocket.Chat instance (and it work everywhere else : Github, Obsidian, etc)

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/13149

If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by TBG-FR** [comment]
From what I've seen during my researches, `[Link name with (parenthesis) inside](https://www.rocket.chat/)` is not always the same bug/problem as `[Link name](https://www.rocket.chat/link-with-(parenthesis)-inside`), but we'll see if #13149 helps to fix both, thanks 😉
