### ISSUE TITLE
Contribution Guidelines link broken in developer documentation

### ISSUE THREAD

**Issue by shikhershukla** [RocketChat/Rocket.Chat#29114]
### Description:

I have found a broken link in the developer documentation on the page '[developer documentation](https://developer.rocket.chat/)'. The link to the "Contribution guidelines" is not working, takes us to '(https://github.com/RocketChat/developer-docs/blob/master/broken-reference/README.md)' an this page is not found, returns a 404 error.

The broken link to the contribution guidelines is causing issues for contributors trying to get started with the Rocket.Chat project. Fixing the link would greatly benefit the community and ensure that contributors have access to the information they need to contribute effectively.

I suggest that the broken link be updated with the correct URL which is '[Contributing to Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/blob/95fad4cd1dc4d2930f69d9a63eac4fb9895e5d45/.github/CONTRIBUTING.md)' or '[Ways to Contribute](https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute)'. I am interested in fixing this issue and would like to be assigned to it.

### Steps to reproduce:

1. Go to '[Rocket.Chat Github repository](https://github.com/RocketChat/Rocket.Chat)'
2. Click on '[Review developer documentation](https://developer.rocket.chat/)'
3. Click on 'Contribution Guidelines' under Contribution

### Expected behavior:

Clicking the link should take us to '[Contributing to Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/blob/95fad4cd1dc4d2930f69d9a63eac4fb9895e5d45/.github/CONTRIBUTING.md)' or '[Ways to Contribute](https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute)'

### Actual behavior:

Clicking on the link takes us to 'https://github.com/RocketChat/developer-docs/blob/master/broken-reference/README.md' which is 404 not found.

**Comment by Ratnadeep2k** [comment]
https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute

May be the link help to get to redirect the expected webpage ..

**Comment by hugocostadev** [comment]
Hi @shikhershukla we had for sure to improve our docs, thanks for reporting

**Comment by Yash-Ambekar** [comment]
This issue is fixed I suppose.

**Comment by hugocostadev** [comment]
Fixed on the lastest releases, thanks
