### ISSUE TITLE
A major Bug in the Footer section of Page

### ISSUE THREAD

**Issue by Bharadwajshivam28** [RocketChat/Rocket.Chat#29116]
Hello sir, I have noticed one thing that in the footer section the button which switches different languages is having a bug . Let me explain you whole thing. When we click on button which switches language then when the box appears where we have to select language that box pops up. then it hides the  no of forks  ..

Dropping the screenshot when we select the language switcher it hides the number of forks -

![WhatsApp Image 2023-05-02 at 11 56 08 PM(1)](https://user-images.githubusercontent.com/108119109/235759116-4cf16526-440f-4e24-a10c-44d3ac3d9966.jpeg)

Without selecting the Language selector the no of forks are visible - 

![Screenshot from 2023-05-03 00-03-27](https://user-images.githubusercontent.com/108119109/235755117-1e5e0445-03b1-44af-81f1-cd1fa271d85d.png)

⭐ How can we Fix it - 

1) One way to fix it is that we can align the button which switches  language to right most corner which will not lead hide number of  forks .

2) We can align the button which switches language to more down which will not lead to hide number of forks count.

**Comment by Bharadwajshivam28** [comment]
@dougfabris Please assign me sir i can fix it

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the bug! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project, the website it's not open source but we will bring this to the responsible team 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Bharadwajshivam28** [comment]
> Hi there, thanks for raising the UI concern! 🚀 💯 
> 
> Sorry, but GitHub is only for issues/bugs related to the repository project, the website it's not open source but we will bring this to the responsible team 
> 
> ---
> 
> **Questions? Help needed? Feature Requests?** 
> 
> - Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
> - Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
> - Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository 

Okay Thanks
