### ISSUE TITLE
New Messages Don't Show in Thread Pane until Refresh

### ISSUE THREAD

**Issue by jdsatava127** [RocketChat/Rocket.Chat#29117]
### Description:

Replies to a thread are no longer showing in the Thread Pane unless you refresh RocketChat. When the thread exceeds the window height, we have to close the thread and reopen to see any new replies. This started happening with our upgrade to v6.x.

### Steps to reproduce:

1. Open thread
2. Have users post messages until window height is exceeded.

### Expected behavior:

Should be able to scroll down in the open Thread Pane to see new replies or the Thread Pane should auto-scroll to the bottom when new replies are posted.

### Actual behavior:

New replies are not shown in thread automatically.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.5
- Operating System: CentOS 7
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: App 3.9.1 and Google Chrome 112.0.5615.121
- Operating System: Windows 10

**Comment by Ninad3721** [comment]
Hello , I would like to work over this , I tried to reproduce it but things are working fine in localhost. Can you attach a picture or video of the error so I can get clear idea what you are trying to convey.

**Comment by abhinav700** [comment]
@hugocostadev Can you assign this issue to me please? I would like to work on it.

**Comment by hugocostadev** [comment]
@abhinav700  No need to ask for permission to fix the issue, feel free to work on it! 
Just check if someone it's already raised a PR for that (should be linked in this issue).
Best of luck 🚀 👏 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by sarthaksharma27** [comment]
Hello, @hugocostadev  I noticed that no pull request has been submitted yet, and given that this issue remains open, and you mentioned earlier that there's no need to assign, I have started working on it. 🚀

**Comment by PranitPatil03** [comment]
Hello @jdsatava127, I attempted to replicate the issue, but everything is functioning properly on my local setup. Could you please provide a picture or video capturing the error? This will help me understand exactly what you are experiencing.

<details><summary>Details</summary>
<p>

![image](https://github.com/RocketChat/Rocket.Chat/assets/91155068/de2e020f-dc02-4c53-ac77-beeaf828fabe)

</p>
</details>

**Comment by jdsatava127** [comment]
I haven't been able to recreate this issue either (we are now on version 6.4.4) and we haven't received any more complaints from our user base. I think it's ok to mark this as resolved.
