### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2914]
Your Rocket.Chat version: 0.26-0.31

The node.js killed after restart with message:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./chat.sh: line 5:  1351 Aborted                 (core dumped) node main.js
```
On dmesg:
```
[  999.897804] Out of memory: Kill process 1333 (node) score 859 or sacrifice child
[  999.898799] Killed process 1333 (node) total-vm:1955432kB, anon-rss:896972kB, file-rss:0kB
```
I have 1 Gb of memory on my VPS. The "used memory size" for node.js process is increased continiously. If I enabled the swap - the server was slow down and then process are killed too.

Where can I get the callstack or some other debug info?

**Comment by marceloschmidt** [comment]
Any chance to run this with the latest version?

**Comment by zxweed** [comment]
@marceloschmidt, this is sporadic error, so I will report if I can reproduce it with the latest version.

Where can I get the callstack in this case?

**Comment by zxweed** [comment]
the problem are reproduced on 0.28:

> May  2 11:39:59 Ubuntu-1404-trusty-64-minimal kernel: [ 1737.101615] Out of memory: Kill process 1773 (node) score 880 or sacrifice child
> May  2 11:39:59 Ubuntu-1404-trusty-64-minimal kernel: [ 1737.102131] Killed process 1773 (node) total-vm:1834108kB, anon-rss:891852kB, file-rss:0kB
> 

Can I limit the memory usage of mongodb or node.js?

**Comment by zxweed** [comment]
Before crash I have the memory shortage on node.js:
```%Cpu(s): 95.3 us,  2.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  1.0 si,  1.3 st
KiB Mem:   1016824 total,  1007848 used,     8976 free,     5560 buffers
KiB Swap:        0 total,        0 used,        0 free.   347100 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1496 www-data  20   0 1489304 544420   7196 R 99.1 53.5   1:09.32 node
   29 root      20   0       0      0      0 S  0.3  0.0   0:00.58 kworker/0:1
   33 root      20   0       0      0      0 S  0.3  0.0   0:00.42 kswapd0
 1530 mongodb   20   0 3110488 202000 157964 S  0.3 19.9   0:03.99 mongod
```

**Comment by marceloschmidt** [comment]
I think you should try increasing the total memory in your VPS, especially if you're running rocket.chat alongside with other services.

**Comment by zxweed** [comment]
@marceloschmidt, It seems that memory shortage caused by one of the connected client (I have found it by connecting the clients one by one.) Can I see the internal memory distribution by client sessions to confirm this?

**Comment by marceloschmidt** [comment]
@zxweed I don't know how to debug memory issues. Would you like to keep this issue open until someone can help you with that, or do you consider that your main issue was lack of memory, and in that case, this issue could be closed?
Thanks.

**Comment by zxweed** [comment]
@marceloschmidt, I have upgraded the VM to 2 Gb of memory, but the problem still exists. My current version is 0.31 with node.js 0.10.43

**Comment by zxweed** [comment]
```
node invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
node cpuset=/ mems_allowed=0
CPU: 1 PID: 2401 Comm: node Not tainted 4.2.0-34-generic #39~14.04.1-Ubuntu
Hardware name: Hetzner vServer, BIOS 1.8.2 04/01/2014
 0000000000000000 ffff88007af47a58 ffffffff817b5fed 0000000000000000
 ffff88007c092940 ffff88007af47b08 ffffffff817b0a9c 0000000000000000
 0000000000000000 0000000000000000 0000000000000000 0000000000000000
Call Trace:
 [<ffffffff817b5fed>] dump_stack+0x45/0x57
 [<ffffffff817b0a9c>] dump_header+0x81/0x202
 [<ffffffff8117a000>] oom_kill_process+0x1c0/0x390
 [<ffffffff8117a6e1>] out_of_memory+0x4b1/0x4f0
 [<ffffffff8117fdfb>] __alloc_pages_nodemask+0x96b/0x990
 [<ffffffff811c5675>] alloc_pages_vma+0xb5/0x200
 [<ffffffff811a686d>] handle_mm_fault+0x134d/0x1840
 [<ffffffff810a9136>] ? set_next_entity+0xa6/0x4c0
 [<ffffffff81064289>] __do_page_fault+0x199/0x430
 [<ffffffff81064587>] trace_do_page_fault+0x37/0xa0
 [<ffffffff8105cb29>] do_async_page_fault+0x19/0x80
 [<ffffffff817bf378>] async_page_fault+0x28/0x30
Mem-Info:
active_anon:493444 inactive_anon:74 isolated_anon:0
 active_file:27 inactive_file:65 isolated_file:0
 unevictable:0 dirty:0 writeback:0 unstable:0
 slab_reclaimable:4402 slab_unreclaimable:3117
 mapped:2 shmem:101 pagetables:2520 bounce:0
 free:3363 free_pcp:142 free_cma:0
Node 0 DMA free:7972kB min:40kB low:48kB high:60kB active_anon:7604kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB
lowmem_reserve[]: 0 1983 1983 1983
Node 0 DMA32 free:5480kB min:5580kB low:6972kB high:8368kB active_anon:1966172kB inactive_anon:296kB active_file:108kB inactive_file:260kB
lowmem_reserve[]: 0 0 0 0
Node 0 DMA: 15*4kB (UE) 21*8kB (UE) 18*16kB (UEM) 13*32kB (UEM) 10*64kB (UEM) 4*128kB (UE) 3*256kB (UE) 4*512kB (UEM) 1*1024kB (E) 1*2048k
Node 0 DMA32: 34*4kB (UEM) 94*8kB (UE) 113*16kB (UEM) 9*32kB (UEM) 23*64kB (UM) 4*128kB (UM) 2*256kB (UM) 0*512kB 0*1024kB 0*2048kB 0*4096
Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
198 total pagecache pages
0 pages in swap cache
Swap cache stats: add 0, delete 0, find 0/0
Free swap  = 0kB
Total swap = 0kB
524158 pages RAM
0 pages HighMem/MovableOnly
11937 pages reserved
0 pages cma reserved
0 pages hwpoisoned
```

**Comment by zxweed** [comment]
As I can see - the problem is reproduced when someone are loaded too much history... So admin need to deactivate and activate this account to reset his browser. If not - the node.js crashed (after server restart) continiously.

**Comment by lucasvanhalst** [comment]
@zxweed what would 'too much' history be? I've loaded a few thousand messages on my own instance in my browser to the point it's pretty much unusable and didn't see the memory increase in any meaningful way

**Comment by geekgonecrazy** [comment]
the kernel exception looks to be pretty obvious its a memory issue.  Also note if you are running a bigger install.  Might be a good idea to move your database to another server.  As sometimes mongodb with the wiredtiger engine can be a bit aggressive.

**Comment by lostinblue** [comment]
Had the same issue, had to upgrade the memory. 

Um, you should really consider having different optional DB backends because there is no reason this should require that much memory. You are not gaining anything by storing every message ever on the server in memory at all times. Especially considering you are offloading almost all the processing to the client when you have this much of the client in JS. Which is fine, you end up using up more battery power on mobile devices but at least you get a nice UI, but if you are going to make that sacrifice you should not be also wasting server resources.

**Comment by geekgonecrazy** [comment]
Allowing different dbs is for sure something we are looking at.  

I'm not sure I understand what you mean by every message stored in memory at all times?
