### ISSUE TITLE
centos 9 stream why  can't install ?

### ISSUE THREAD

**Issue by wtoshopnet** [RocketChat/Rocket.Chat#29166]
Can you provide a new set of installation code listings? Because I can't install it with the installation method on your website. Thank you! !

**Comment by hugocostadev** [comment]
Hi, @wtoshopnet can you give more details? What docs did you check? Witch step did you get stuck? 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
