### ISSUE TITLE
exception occurs when switch language 

### ISSUE THREAD

**Issue by wubin1989** [RocketChat/Rocket.Chat#2916]
Your Rocket.Chat version: 0.26.0
When I change language from default to Chinese, exception occurs as below.

=> Meteor server restarted
I20160417-10:46:00.288(8)? Exception in setTimeout callback: TypeError: Cannot read property 'version' of undefined
I20160417-10:46:00.289(8)?     at server/startup/serverRunning.coffee:4:36
I20160417-10:46:00.289(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160417-10:46:00.289(8)?     at packages/meteor/timers.js:6:1
I20160417-10:46:00.289(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160417-10:46:36.809(8)? { [Error: Unknown asset: moment-locales/zh.js] stack: [Getter] }
I20160417-10:47:15.744(8)? Exception in defer callback: Error: connect ETIMEDOUT
I20160417-10:47:15.744(8)?     at Object.Future.wait (/Users/000000/.meteor/packages/meteor-tool/.1.1.10.lqfxtb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20160417-10:47:15.745(8)?     at Object.call (packages/meteor/helpers.js:119:1)
I20160417-10:47:15.745(8)?     at Object.HTTP.post (packages/http/httpcall_common.js:61:1)
I20160417-10:47:15.745(8)?     at generateStatistics (server/startup/cron.coffee:13:8)
I20160417-10:47:15.745(8)?     at server/startup/cron.coffee:19:3
I20160417-10:47:15.745(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160417-10:47:15.745(8)?     at packages/meteor/timers.js:6:1
I20160417-10:47:15.745(8)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160417-10:47:15.746(8)?     - - - - -
I20160417-10:47:15.746(8)?     at errnoException (net.js:905:11)
I20160417-10:47:15.746(8)?     at Object.afterConnect [as oncomplete] (net.js:896:19)

**Comment by marceloschmidt** [comment]
Sorry for the delayed response. 

Could you please try with the latest version? 

Thanks.

**Comment by qge** [comment]
@marceloschmidt Got same error when switching to Chinese Simplified.

**Comment by geekgonecrazy** [comment]
Please try with latest version and let us know if this is still happening
