### ISSUE TITLE
Something went wrong with error alert is showing instead of "no results found" in custom sound

### ISSUE THREAD

**Issue by wave-nature** [RocketChat/Rocket.Chat#29175]
### Description:

If there is no custom sounds, it supposed to show no results, but here it is showing something went wrong with  alert error message of "no results found" (looks like vice versa). Although I checked in network tab status is 200 and sounds is empty array.

### Steps to reproduce:

1.  Go to admin panel side bar
2.  Click on custom sounds
3.  Here you can see the bug if there is no custom sounds

### Expected behavior:

It should show the message no results found if there is no custom sounds

### Actual behavior:

![image](https://user-images.githubusercontent.com/81299143/236897184-1004fea4-a7a5-4d3c-aed5-3835d1a3d8d2.png)

But in production it is showing error message of something went wrong even though there is no custom sounds

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by wave-nature** [comment]
I request to work on this issue and solve this ASAP. Please allow me!

**Comment by dougfabris** [comment]
Hey @wave-nature this issue was fixed here: #28302 and release on our latest 6.2 version.
Thanks for your contribution!
