### ISSUE TITLE
No padding to the Skeleton placeHolder in the omnichanel contact centre 

### ISSUE THREAD

**Issue by wilsonfurtado2000** [RocketChat/Rocket.Chat#29181]
Description:

Missing padding for the skeleton placeholder in the omnichanel contact centre

### Steps to reproduce:

1. Click on the omnichanel directory icon in the main sidebar column

 Actual behavior:
<img width="1440" alt="Error_1" src="https://user-images.githubusercontent.com/72563697/237060578-b5312186-7599-4dd6-a039-69b4476cfe44.png">

 Expected behavior:
there should be padding given and the skeleton placeholder should be properly aligned

**Comment by wilsonfurtado2000** [comment]
i am working on this issue

**Comment by mHasnaat-Iftikhar** [comment]
@wilsonfurtado2000 I'm going to work on that

**Comment by Nitishupkr** [comment]
i m already working on this

**Comment by mHasnaat-Iftikhar** [comment]
Okay

**Comment by Kishn0109** [comment]
Hi  I am trying to run yarn testunit on dev branch to check if all the test cases are working fine so that I can push my changes that I have done but suffering from an error since morning. It will be helpful if you give some reference to get out from this issue   @hugocostadev  ``

**Comment by Kishn0109** [comment]
#29237

**Comment by Kishn0109** [comment]
#26727 This is my approach for above bug and it will fix this issue

**Comment by hugocostadev** [comment]
@Kishn0109 whenever you create a fix for issue, link the issue, please.
