### ISSUE TITLE
Can't delete my messages in the channels

### ISSUE THREAD

**Issue by agamarra-bal** [RocketChat/Rocket.Chat#29196]
Can't delete my messages in the channels while using the linux app (downloaded from snap) 

In the web app I can delete some messages but can't delete all of them

**Comment by hugocostadev** [comment]
Can you provide more info?  Follow the issue template, please... 

If you think that the issue it's just for the desktop client report here: https://github.com/RocketChat/Rocket.Chat.Electron


---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by jw1892626** [comment]
> Can't delete my messages in the channels while using the linux app (downloaded from snap)
> 
> In the web app I can delete some messages but can't delete all of them

Is it only messages with images?

**Comment by agamarra-bal** [comment]
It is any type of message, it doesn't matter if there is with or without images
________________________________

**Comment by agamarra-bal** [comment]
I guess it is file system
________________________________

**Comment by debdutdeb** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/29266 , closing in favour of that.
