### ISSUE TITLE
Paste jpg from clipboard fail

### ISSUE THREAD

**Issue by vnavna01** [RocketChat/Rocket.Chat#29211]
The client will not paste a jpg file from the clipboard. The weird thing is that it changes the extension from jpg to png as well.

**Comment by hugocostadev** [comment]
Are you sure? It's working fine here...

I'll close for now, if you still face the issue, provide the info on the issue template, pelase.

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
