### ISSUE TITLE
Add personal preference for 12/24h time

### ISSUE THREAD

**Issue by toupeira** [RocketChat/Rocket.Chat#2922]
My Rocket.Chat version: 0.26.0

From what I gather (#1959, #1960) the time format depends on the moment.js locale, which depends on the Rocket.Chat UI language. The thing is, I'd like to use English but also 24h format since I live in Europe, one way to offer that would be to expose the `en-*` locales from moment.js so I can just use `en-gb` to get 24h times. Another option might be to have a dedicated setting for the time formatting.

**Comment by engelgabriel** [comment]
Have you seen this PR https://github.com/RocketChat/Rocket.Chat/pull/2852 ?

**Comment by toupeira** [comment]
I did not, thanks! That looks like it solves my issue. Though if that's only an admin-level setting, you still might want to consider adding it as a user option or adding the missing locales, for servers with an international userbase.

**Comment by bott0r** [comment]
HH:mm:ss

**Comment by evgeni** [comment]
Ohai,

I think #2852 is not really a solution here. We're running Rocket.Chat for a worldwide org, and the users tend to prefer different 12/24h clock settings (while still using English instead of $Local_Lang).

I think ultimately time-preferences should not be coupled to language preferences. It might be a good default, but the user should be able to override this.

My 0.02€

**Comment by toupeira** [comment]
Actually I agree with @evgeni, it's just less of an issue for me because I don't have international users. But the point is valid, so I reopened the issue.

**Comment by Artoria2e5** [comment]
A +1 on this. 12/24h time can often be a personal preference thing as opposed to a locale-dependent one.

**Comment by baurmatt** [comment]
Yes, please! :)

**Comment by baynes** [comment]
+1 from me. I am English (UK) but want 24 hour clock.

**Comment by cypa** [comment]
+1

**Comment by engelgabriel** [comment]
We are accepting PRs to turn this into a personal setting.

**Comment by bott0r** [comment]
While you guys are at it, I am sure it would be greatly appreciated if a user could customize the order of entities of messages.

Right now its:
[avatar] [name] [time] [msg]


It would be great if users could change the arrangement. 
I personally prefere

[time] [avatar] [name] [msg]

I am sure other people would like to do 

[time] [name] [msg]

**Comment by gyde** [comment]
Where is this feature now, can't see it anywhere under the "My Account -> Preferences"?

**Comment by leonschoorl** [comment]
It's at: My Account -> Preferences -> Messages -> Time Format
