### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dsanchezTMC** [RocketChat/Rocket.Chat#29239]
our chat is not working or connecting

**Comment by sagnikc395** [comment]
can you give a description of what exactly is not working ?

**Comment by hugocostadev** [comment]
Please, follow the issue template, if you want informal and more direct support go to our #support channel at open.rocket.chat

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
