### ISSUE TITLE
:rocket: .chat

### ISSUE THREAD

**Issue by DymCx** [RocketChat/Rocket.Chat#2923]
[🚀.chat](https://🚀.chat) (https://xn--158h.chat)

\*drops mic\*

**Comment by DymCx** [comment]
<turns out> github doesnt support [_all_](http://www.emoji-cheat-sheet.com) the text-emojis, and ditches actual emoji in the issues-list

**Comment by engelgabriel** [comment]
Nice try :)

**Comment by DymCx** [comment]
D:

T_T
