### ISSUE TITLE
Open and save attachment

### ISSUE THREAD

**Issue by tibczy** [RocketChat/Rocket.Chat#29248]
![image](https://github.com/RocketChat/Rocket.Chat/assets/30168997/13e04b4b-da3e-4ae1-851c-66042e067d7a)
![image](https://github.com/RocketChat/Rocket.Chat/assets/30168997/59bf20a2-1fc4-458a-be2f-948b02f84418)
click on the attachment to get this popup image of the opened
and when I save the file it displays my folders like this
What could be the problem?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the problem! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project, this seems an OS issue, we do not change the behavior of OS systems

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
