### ISSUE TITLE
`:D` emoji is autocorrected to `:england:`, + other silly emoji autocorrects

### ISSUE THREAD

**Issue by rnd-ash** [RocketChat/Rocket.Chat#29241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Operating System Version

Arch linux (Using the official electron client)

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.9.x (Present in all 3.9 versions I've tested)

### Rocket.Chat Server Version

6.1.7

### Describe the bug

Typing `: D` followed by `Enter`, should result in a smiley face, but rocketchat will autocorrect this to the England flag emoji. 

Uploaded a video of the wrong autocorrection occuring.

https://github.com/RocketChat/Rocket.Chat.Electron/assets/14551965/87f8abc4-5124-4706-85eb-c34a95d857de

Another example is `:P` (Should be stuck_tounge_out), being corrected to `:couplekiss_mm:`

### How to Reproduce

In any chat, typing in some basic emojis will result in odd autocorrections overwriting the emoji entered.

### Describe your Expected behavior

Typing simple emojis (Standard ones), should not result in really weird autocorrection.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by jayesh-jain252** [comment]
Similar to issue #28844

**Comment by hugocostadev** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/28844
