### ISSUE TITLE
Login as admin failed

### ISSUE THREAD

**Issue by knordsiek** [RocketChat/Rocket.Chat#29249]
### Description:

After Login as Admin: 

Error message:
Application Error
The application GUI just crashed.

### Steps to reproduce:

1. Login as user, ok 
2. Login as admin site failed with error message Application Error The application GUI just crashed.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.0
- Operating System: Rocky Linux 8.0
- Deployment Method: Server
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version: Chromium Version 113.0.5672.92 and Firefox 113.0 (64-Bit)

- Operating System: Kubuntu 20.04

**Comment by sleeplessnight2** [comment]
the same thing happens with my installation

**Comment by vinzv** [comment]
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/74432/0acf7103-d4cc-4f22-9d0c-f7fd0d9c04ac)
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/74432/9d1ef995-a9ce-4ebe-86fa-de95e8290d2a)
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/74432/fd15b79b-bc0b-4140-b964-65e817f67c22)

This only occurs with user rocketadmin but not with other users having admin permissions.

**Comment by sleeplessnight2** [comment]
![image](https://github.com/RocketChat/Rocket.Chat/assets/8561601/74eb9c39-b25c-4d1f-aa4a-7b8cc43e665e)

This occurs when I reload the page after logging in with an admin account.

Cache etc is cleared, as well as on the Linux everything in /tmp/ that belongs to RocketChat.

I am running MongoDB version 6.0.6.

**Comment by EofChris** [comment]
I can also confirm the problem. Seems to happen with all admin accounts regardless of the username. Log output is the same as above.

```
Rocket.Chat Version: 6.2.0
NodeJS Version: 14.21.3 - x64
MongoDB Version: 5.0.17
MongoDB Engine: wiredTiger
```

**Comment by ggazzo** [comment]
Hey thanks for your report, and for the information. Unfortunately I haven't been able to reproduce your problem yet and I'm afraid the logs are not related to this, as we know of some we already solved/omitted it in version 6.3.0-develop. Do you have any more information that could help us?

I'm admin for most of the instances I use, and I haven't encountered any problems logging in.

Have you tried in some new browser, without any old cache? Any special settings?

**Comment by knordsiek** [comment]
In our system (we are using ldap authentication) we have created the user rocketadmin with role admin and no user role perhaps this is the problem, can anyone else confim this?

**Comment by EofChris** [comment]
We are currently using local authentication. The admin user is a "normal" user account with role admin.

**Comment by Nintend0d0** [comment]
I have the same issue in Firefox and with the desktop app. If I try to access the admin panel on the mobile version, I also see the GUI crash error.

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/11808561/53d022ef-52b9-4f83-91e4-9d1799c89a09)

Any more places where I can get logs? The console does only show errors regarding some missing source maps.

I'm using the rocketchat/rocket.chat docker container behind a caddy reverse proxy. GUI crashes also if I connect directly via IP without using a proxy.

Also using "normal" accounts. Only my account (the only admin account on the server) is affected.

I’m using mongo 4.4 because my home server is old 😅.

Strangly I still get push notifications even though the GUI does not load.

**Comment by ggazzo** [comment]
can I have access to any of those environments?

**Comment by Nintend0d0** [comment]
Hah! I solved it!

Something was messed up in the database. I think a syntax error or too much in the "banners" property.

I could fix it this way:

1. Go into your mongo shell.
2. `use rocketchat`.
3. View your user with `db.users.find({"username": "your_username"}).pretty()` you'll have a big banners property.
4. Run `db.users.update({"username": "your_username"},{$set:{"banners":{}}})` to clear that property.
5. Pray you didn't kill your DB.
6. CTRL + R in client and it works!

I take no warranty for messed up databases!!! Create a backup first.

**Comment by NB-SWP** [comment]
These seem like messages from "Rocket.cat" to me.

**Comment by Bugt** [comment]
I had the same issue:

<img width="867" alt="Bildschirmfoto 2023-05-17 um 08 38 41" src="https://github.com/RocketChat/Rocket.Chat/assets/33179601/491c3389-5ae7-44d9-a45d-7a9f728780e8">

https://github.com/RocketChat/Rocket.Chat/issues/29249#issuecomment-1550185731 
Solved it!

**Comment by EofChris** [comment]
I can confirm the problem is solved by https://github.com/RocketChat/Rocket.Chat/issues/29249#issuecomment-1550185731 

Thanks a lot.

**Comment by tudomisc** [comment]
(https://github.com/RocketChat/Rocket.Chat/issues/29249#issuecomment-1550185731)
Worked for me, thanks a lot!

**Comment by o-** [comment]
We are affected by this too. My account was completely locked, I couldn't do anything anymore. Clearing `banners` was not enough. I also had to clear the following: `db.users.update({"username": "user"},{$set:{"settings":{}}})`.

ftr, the following was in this field before I cleared it: ` settings: { profile: {}, preferences: { language: 'en' } },`

**Comment by fuzsin** [comment]
Solved by (https://github.com/RocketChat/Rocket.Chat/issues/29249#issuecomment-1550185731), thanks a lot!

The only thing is that the name of my database was _parties_ (there was no _rocketchat_ at all). the command `show dbs` will list all existing databases

**Comment by ggazzo** [comment]
if anyone else has problems with this, before cleaning the database, please let me know the payload inside banners.

I'll try to reproduce here anyway

**Comment by Nintend0d0** [comment]
Mine was

```json
{
  "banners": {
    "versionUpdate-5_3_0": {
      "id": "versionUpdate-5_3_0",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.3.0"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.3.0",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_3_1": {
      "id": "versionUpdate-5_3_1",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.3.1"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.3.1",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_3_2": {
      "id": "versionUpdate-5_3_2",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.3.2"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.3.2",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_3_3": {
      "id": "versionUpdate-5_3_3",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.3.3"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.3.3",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_3_4": {
      "id": "versionUpdate-5_3_4",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.3.4"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.3.4",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_3_5": {
      "id": "versionUpdate-5_3_5",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.3.5"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.3.5",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_4_0": {
      "id": "versionUpdate-5_4_0",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.4.0"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.4.0",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_4_1": {
      "id": "versionUpdate-5_4_1",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.4.1"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.4.1",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_4_2": {
      "id": "versionUpdate-5_4_2",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.4.2"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.4.2",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_4_3": {
      "id": "versionUpdate-5_4_3",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.4.3"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.4.3",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-5_4_4": {
      "id": "versionUpdate-5_4_4",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["5.4.4"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/5.4.4",
      "modifiers": [],
      "read": true
    },
    "versionUpdate-6_0_0": {
      "id": "versionUpdate-6_0_0",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.0.0"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.0.0",
      "modifiers": [],
      "read": true
    },
    "mongodbDeprecation_4_4_19": {
      "id": "mongodbDeprecation_4_4_19",
      "priority": 100,
      "title": "MongoDB_Deprecated",
      "text": "MongoDB_version_s_is_deprecated_please_upgrade_your_installation",
      "textArguments": ["4.4.19"],
      "modifiers": ["danger"],
      "link": "https://go.rocket.chat/i/mongodb-deprecated"
    },
    "versionUpdate-6_0_1": {
      "id": "versionUpdate-6_0_1",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.0.1"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.0.1",
      "modifiers": []
    },
    "versionUpdate-6_1_0": {
      "id": "versionUpdate-6_1_0",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.0"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.0",
      "modifiers": []
    },
    "versionUpdate-6_1_1": {
      "id": "versionUpdate-6_1_1",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.1"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.1",
      "modifiers": []
    },
    "versionUpdate-6_1_2": {
      "id": "versionUpdate-6_1_2",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.2"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.2",
      "modifiers": []
    },
    "versionUpdate-6_1_3": {
      "id": "versionUpdate-6_1_3",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.3"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.3",
      "modifiers": []
    },
    "versionUpdate-6_1_4": {
      "id": "versionUpdate-6_1_4",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.4"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.4",
      "modifiers": []
    },
    "mongodbDeprecation_4_4_20": {
      "id": "mongodbDeprecation_4_4_20",
      "priority": 100,
      "title": "MongoDB_Deprecated",
      "text": "MongoDB_version_s_is_deprecated_please_upgrade_your_installation",
      "textArguments": ["4.4.20"],
      "modifiers": ["danger"],
      "link": "https://go.rocket.chat/i/mongodb-deprecated"
    },
    "versionUpdate-6_1_5": {
      "id": "versionUpdate-6_1_5",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.5"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.5",
      "modifiers": []
    },
    "versionUpdate-6_1_6": {
      "id": "versionUpdate-6_1_6",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.6"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.6",
      "modifiers": []
    },
    "versionUpdate-6_1_7": {
      "id": "versionUpdate-6_1_7",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.1.7"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.1.7",
      "modifiers": []
    },
    "versionUpdate-6_2_0": {
      "id": "versionUpdate-6_2_0",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": ["6.2.0"],
      "link": "https://github.com/RocketChat/Rocket.Chat/releases/tag/6.2.0",
      "modifiers": []
    },
    "mongodbDeprecation_4_4_21": {
      "id": "mongodbDeprecation_4_4_21",
      "priority": 100,
      "title": "MongoDB_Deprecated",
      "text": "MongoDB_version_s_is_deprecated_please_upgrade_your_installation",
      "textArguments": ["4.4.21"],
      "modifiers": ["danger"],
      "link": "https://go.rocket.chat/i/mongodb-deprecated"
    }
  }
}
```

**Comment by ggazzo** [comment]
I tested using development branch and its working great, not sure if something substantial changed but I will check ;) 

![image](https://github.com/RocketChat/Rocket.Chat/assets/5263975/5713528c-8197-41d0-bdc9-32ed3c6159a6)
```
  "banners": {
    "versionUpdate-x_x_x": {
      "id": "versionUpdate-x_x_x",
      "priority": 10,
      "title": "Update_your_RocketChat",
      "text": "New_version_available_(s)",
      "textArguments": [
        "x.x.x"
      ],
      "link": "https://rocket.chat/releases/x.x.x",
      "modifiers": []
    }
  }

```

**Comment by Bugt** [comment]
@ggazzo have you tried testing it using the whole payload @Nintend0d0 provided? (To rule out a size problem).
Mine was about as big as this one.

I'm using Rocket.Chat in english and had the issue. Not sure if the translation is the cause.

**Comment by ggazzo** [comment]
> @ggazzo have you tried testing it using the whole payload @Nintend0d0 provided? (To rule out a size problem). Mine was about as big as this one.
> 
> I'm using Rocket.Chat in english and had the issue. Not sure if the translation is the cause.

yep I set the banner object with the whole payload 

I didnt test with a different language

**Comment by jemand771** [comment]
one of our two admins also suffered from this with their language set to german, but I don't know about the other one.
might still be a coincidence, but it's odd that multiple people noticed it.

(I don't have admin perms, so I didn't experience the bug myself and also sadly don't have the original payload anymore)

**Comment by Nintend0d0** [comment]
So, I updated from 6.2.0 to 6.2.2 and it crashed again.

This time I deleted each entry on by one. The crash disappeared, when I deleted this property in banners.

```json
{
            "mongodbDeprecation_4_4_21" : {
                    "id" : "mongodbDeprecation_4_4_21",
                    "priority" : 100,
                    "title" : "MongoDB_Deprecated",
                    "text" : "MongoDB_version_s_is_deprecated_please_upgrade_your_installation",
                    "textArguments" : [
                            "4.4.21"
                    ],
                    "modifiers" : [
                            "danger"
                    ],
                    "link" : "https://go.rocket.chat/i/mongodb-deprecated"
            }
    }
```

It also could be a side effect of an another problem, which I'm not aware of?

**Comment by Nintend0d0** [comment]
I could even narrow it more down.

When I run `db.users.update({"username": "your_username"}, {$set: {"banners.mongodbDeprecation_4_4_21.text":"Hallo Welt"}})`, crash disappears.

When I reinsert the original string via `db.users.update({"username": "your_username"}, {$set: {"banners.mongodbDeprecation_4_4_21.text":"MongoDB_version_s_is_deprecated_please_up
grade_your_installation"}})` it crashes.

**Important**, when I set the language to English I have no crash! So it must be something with the translation.

**Comment by Nintend0d0** [comment]
Probably found it!

https://github.com/RocketChat/Rocket.Chat/blob/cc68894674070308f4fec02444d677e1f9261871/apps/meteor/packages/rocketchat-i18n/i18n/de.i18n.json#L3330

There is a space after the %. `% s` instead `%s`.

**Comment by Fiodin** [comment]
It seems like this error is back. I upgraded a few days ago on **Snap**  to Version 6.6.0 and cannot log in as admin with this exact error.

Unfortunately the db thing didn't work and down- and upgrading with the snap either.

Any suggestions?

**Comment by racus-pz** [comment]
I faced a similar error today, i've tried couple restarts, that MongoDB thing, and nothing... 

If I try to log in into admin account - three dots,
If I try to log in into user account - everything works just perfect 

Funny thing: mobile app worked perfectly but I couldn't open Admin Panel

In an act of desperation, I pressed and held Ctrl+Shift+R (Reload Option) window reloaded like 150+ times and finally, It started to work. It showed me 20+ messages with update info, I have closed them all and now it is ok.
