### ISSUE TITLE
Support for copy to clipboard

### ISSUE THREAD

**Issue by sta-szek** [RocketChat/Rocket.Chat#2925]
Your Rocket.Chat version: 0.26

I think there is no option (or I can't find it) for copying to clipboard (especially code blocks), which may be a very nice feature.

When you want to select a long block of code, the selection is very uncomfortable...

**Comment by marceloschmidt** [comment]
If anyone wants to make a PR for this one, it shouldn't be too hard:

Add a button [copy to clipboard] somewhere in the code block with a `clipboard` class and a `data-clipboard-target` that points to the code block, eg.: 

`<a class="clipboard" data-clipboard-target=".message#message_id code">{{_ "COPY_TO_CLIPBOARD"}}</a>`

Needs testing, but that should be about it...

**Comment by diegoprates** [comment]
Hi, I would like to start contribing to this project, I will submit a PR for this.

**Comment by Sing-Li** [comment]
@diegoprates  it is yours now :)  please reference this ticket in your PR when ready.  thanks

**Comment by flarehl** [comment]
@Sin-Li I know I forgot to submit a post here, but I did manage to get a basic copy to clickboard functionality added to code blocks, the commit can be seen above diegoprates comment. I already submitted a pull request for this issue, I don't know if that will change anything.
