### ISSUE TITLE
Application Error When Deleting uploaded Files After upgrade to 6.2.0 (FileSystem Type)

### ISSUE THREAD

**Issue by esnutd** [RocketChat/Rocket.Chat#29266]
### Description:

Application Error When Deleting uploaded Files After upgrade to 6.2.0

### Steps to reproduce:

1. Go to Direct Message
2. upload a file and try to delete on
3. Refresh your tab and you can see you file deleted succesfully but in file menu you can see the file name and you cant delete it

check this video:
https://mega.nz/file/KjJyERaA#jQyzvcl_MMYLqH3nMpB2RDesYX00JzQpRGsm88EQzKY

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.0
- Operating System: Rocky linux 9
- Deployment Method: Manually
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version:6.0.5 / wiredTiger (oplog Enabled)

**Comment by chotaire** [comment]
Does this happen in direct message only? If not, I don't see the file when also deleting the message, just fyi.

**Comment by esnutd** [comment]
> Does this happen in direct message only? If not, I don't see the file when also purging the message, just fyi.

Both channel and direct message same error occured

**Comment by esnutd** [comment]
Server side logs when i want to delete any files:


May 20 09:09:09 node01 node[39985]: {"level":40,"time":"2023-05-20T05:39:09.303Z","pid":39985,"hostname":"node01","name":"DeprecationWarning","section":"METHOD","msg":"deleteMessage method is deprecated, and will be removed in future versions"}
May 20 09:09:09 node01 node[39985]: {"level":50,"time":"2023-05-20T05:39:09.347Z","pid":39985,"hostname":"node01","name":"System","msg":"Exception while invoking method deleteMessage","err":{"type":"Error","message":"ENOENT: no such file or directory, stat '/u01/upload/64685cf17338b29cd19aa989'","stack":"Error: ENOENT: no such file or directory, stat '/u01/upload/64685cf17338b29cd19aa989'\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/ufs/ufs-local.ts:72:20\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/ufs/ufs-store.ts:230:3\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/ufs/ufs-local.ts:76:5\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/file-upload/server/lib/FileUpload.ts:677:4\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/lib/server/functions/deleteMessage.ts:48:13\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:557:17\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","errno":-2,"code":"ENOENT","syscall":"stat","path":"/u01/upload/64685cf17338b29cd19aa989"},"msg":"ENOENT: no such file or directory, stat '/u01/upload/64685cf17338b29cd19aa989'"}

**Comment by esnutd** [comment]
This Error occuerd if your storage type set on FileSystem,then i changed back to GridFs and error has been gone

**Comment by jw1892626** [comment]
I have same issue.  Removing files using FileSystem is definitely broken.  This also prevents you from deleting a channel sometimes.  Probably related to https://github.com/RocketChat/Rocket.Chat/issues/29309.

**Comment by debdutdeb** [comment]
this is the source pr btw - https://github.com/RocketChat/rocket.chat/pull/28769

it's trying to follow the same code path twice, resulting in this weird error it looks like.

**Comment by Snyaify** [comment]
I came across this bug too, I’ll say more, I deleted my avatar and can’t download a new one now, I constantly get an error ENOENT

I tried to remove or reset the avatar through curl, no luck:

```
curl -H "X-Auth-Token: d****" \
     -H "X-User-Id: Y*****" \
     -H "Content-type:application/json" \
     http://192.168.0.162:3000/api/v1/users.resetAvatar \
     -d '{ "userId": "Y***" }'
```
{"success":false,"error":"ENOENT: no such file or directory, stat '/storage/646611908618216a5009a186'"}

No one from my team can't set avatar now..

**Comment by debdutdeb** [comment]
should be fixed with the linked pr :)

**Comment by sleeplessnight2** [comment]
Is it possible that for this 6.2.3 will be released as soon as possible?

I'm currently being cross-fired as an admin by many sites for this.

It would be nice. In the past there have been minor releases for less important changes.

**Comment by divinespear** [comment]
I have same issue on 6.2.0 and after with filesystem.
met `ENOENT` while delete uploaded file, it seem to trying delete file twice.

there is many failure reasons on filesystem functions, so **should** handle exceptions.

**Comment by andys448** [comment]
If you are enable LDAP sync with this bug - login not working. Nothing happens after push button login. FS type also.

**Comment by sleeplessnight2** [comment]
> If you are enable LDAP sync with this bug - login not working. Nothing happens after push button login. FS type also.

That doesn't seem to have anything to do with this bug.
LDAP works fine for me, even under 6.2.2 ...

**Comment by andys448** [comment]
> > If you are enable LDAP sync with this bug - login not working. Nothing happens after push button login. FS type also.
> 
> 
> 
> That doesn't seem to have anything to do with this bug.
> 
> LDAP works fine for me, even under 6.2.2 ...

Hi! Try to reset/remove avatar or set manually photo, enable sync from ldap avatar, try to login.

**Comment by steffen-kdab** [comment]
Same problem here. LDAP enabled, Filesystem storage enabled, some people can't log in. Error logged when they try is:
```
{"level":50,"time":"2023-06-07T21:32:10.526Z","pid":1,"hostname":"5b44ce062e42","name":"System","msg":"Exception while invoking method login","err":{"type":"Error","message":"ENOENT: no such file or directory, stat '/app/uploads/ck6Gy5YM9fckHcNiW'","stack":"Error: ENOENT: no such file or directory, stat '/app/uploads/ck6Gy5YM9fckHcNiW'
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at server/ufs/ufs-local.ts:72:20
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/file-upload/server/lib/FileUpload.ts:677:4
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/lib/server/functions/setUserAvatar.ts:105:15
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at server/lib/ldap/Manager.ts:103:3
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at server/lib/ldap/Manager.ts:240:3
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at server/lib/ldap/Manager.ts:265:3
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at server/lib/ldap/Manager.ts:48:5
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at packages/accounts-base/accounts_server.js:588:57
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at packages/accounts-base/accounts_server.js:1525:11
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at packages/accounts-base/accounts_server.js:653:7
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/api/server/v1/misc.ts:618:17
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","errno":-2,"code":"ENOENT","syscall":"stat","path":"/app/uploads/ck6Gy5YM9fckHcNiW"},"msg":"ENOENT: no such file or directory, stat '/app/uploads/ck6Gy5YM9fckHcNiW'"}
```
The file /app/uploads/ck6Gy5YM9fckHcNiW does indeed not exist, but creating a dummy file with that name doesn't change anything.
