### ISSUE TITLE
Application Error after update to RocketChat 6.2.0

### ISSUE THREAD

**Issue by zmijunkie** [RocketChat/Rocket.Chat#29265]
### Steps to reproduce:
Update to RocketChat 6.2.0.
Try to connect to chat with Macox M2 using Client Rocket.Chat.app Version 3.9.3

### Expected behavior:

Connect to server

### Actual behavior:

Screen shows:Application Error - The application GUI just crashed

### Server Setup Information:

- Version of Rocket.Chat Server: 
- 6.2.0
- Operating System: 
- debian/maxos
- Deployment Method: 
- tar
- Number of Running Instances: 
- 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.2
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- using Desktop App Rocket.Chat.app Version 3.9.3
- Operating System:Macox M2 

### Relevant logs:

![Bildschirm­foto 2023-05-17 um 07 03 19](https://github.com/RocketChat/Rocket.Chat/assets/1107216/1fc05498-2020-48a9-835a-78bba0252c5a)

**Comment by EofChris** [comment]
Hey, this might be related to #29249

**Comment by nstoeckigt** [comment]
> Hey, this might be related to #29249

I fixed that issue with the solution from [Nintend0d0](https://github.com/RocketChat/Rocket.Chat/issues/29249#issuecomment-1550185731)
To find all admin I used
```
rocketchat> db.users.find( { roles: 'admin' }, { username: 1, _id: 0 } )
```

You might want do this in a loop if you have a wast amount of effected users.

**Comment by hugocostadev** [comment]
Thanks for helping @nstoeckigt ! 💯 

@zmijunkie let us know if this worked, please

**Comment by nstoeckigt** [comment]
This might also be related to #29395 and therefore is fixed in 6.2.3

If you continue upgrading to that version you also should be fine!
Please give feedback here if thats the case!

**Comment by zmijunkie** [comment]
got this error again, after upgrading to 6.2.6, just appeared and went away - does not affect anything else - 6.2.6 just works

**Comment by hugocostadev** [comment]
Perfect, closing because it was fixed on 6.2.6.  Thanks

**Comment by akong77** [comment]
Hello,
I has upgrade to 6.2.6 with snap.Some user has show application error.

**Comment by gusarg81** [comment]
Hi, today I have this problem as well. Using Snap version (rocketchat-desktop  3.9.5).
