### ISSUE TITLE
Application crashes when clicking on Analytics option in Omnichannel view page

### ISSUE THREAD

**Issue by jayesh-jain252** [RocketChat/Rocket.Chat#29272]
### Description:

When clicking on the "Analytics" option in the Omnichannel view page (omnichannel/analytics) the application crashes with the following error in the console

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/c851a5c3-d36e-4e59-8e47-faf5d3d17360)

### Steps to reproduce:

1. Click on omnichannel
![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/b742dce6-b3e4-4582-9ded-078ab89c2295)

2. Then Click on Analytics
![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/2280f5ea-d23f-46f5-88ee-2707aab282f6)

### Expected behavior:

Analytics pages should be displayed

### Actual behavior:

Application is crashing

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: Windows 10
- Deployment Method: Gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3 - x64
- MongoDB Version: 6.0.3

### Relevant logs:

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/2da0778d-5a78-42e8-9fd8-7010db1baf8d)

location of AgentOverview.tsx: apps/meteor/client/views/omnichannel/analytics/AgentOverview.tsx

**Comment by Kushagra-0** [comment]
I have also faced similar issues when opening analytics tab.

**Comment by jayesh-jain252** [comment]
I tried removing the useTranslation t function

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/5ae3f5d8-877c-4904-b1e3-8d417a90889f)

to 

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/aeff2b08-78be-47bb-b3de-1194246683b6)

Than the "Analytics" Page works

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/9692da90-eff1-4e82-9da7-605458fd75e0)

**Comment by anikdhabal** [comment]
> If I remove the useTranslation t function
> 
> ![image](https://user-images.githubusercontent.com/79307894/239025514-5ae3f5d8-877c-4904-b1e3-8d417a90889f.png)
> 
> like this
> 
> ![image](https://user-images.githubusercontent.com/79307894/239025723-aeff2b08-78be-47bb-b3de-1194246683b6.png)
> 
> Than the "Analytics" Page works
> 
> ![image](https://user-images.githubusercontent.com/79307894/239025961-9692da90-eff1-4e82-9da7-605458fd75e0.png)

Yes there's no need the translation key
