### ISSUE TITLE
Served by drop down size not consistent

### ISSUE THREAD

**Issue by Kushagra-0** [RocketChat/Rocket.Chat#29273]
### Description:

When clicking on served by drop down bar, the size of bar increases.

### Steps to reproduce:

1. Go to Current Chats under Omnichannel

### Expected behavior:

When clicked the bar should remain at its original size.

### Actual behavior:
[Screencast from 17-05-23 09:32:07 PM IST.webm](https://github.com/RocketChat/Rocket.Chat/assets/115860756/2a283630-e2ca-4aad-800b-f5b722b10e92)

**Comment by hugocostadev** [comment]
duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/28937
