### ISSUE TITLE
Reactions field inconsistency

### ISSUE THREAD

**Issue by kbrianps** [RocketChat/Rocket.Chat#29299]
Hi,

I'm creating a bot and I've realise that reactions field behavior is bit problematic.

Reactions field, as have been implemented, become a message object property when someone react and it's been deleted when someone unreact (undo your reaction). There's no signal that indicates a reaction have been removed. It's expected to reactions still exist (even empty or as 0), as other properties.

This turns the use of Message Object properties difficult, seems it's inconsistent.

**Comment by hugocostadev** [comment]
Please, open the Issue in this repo: https://github.com/RocketChat/Rocket.Chat.Apps-engine
