### ISSUE TITLE
Unable to delete users

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#29292]
### Description:

This is a stub for the issue where deleting users fails using admin web console.

The issue started in RC 6.2.x.

Additional conditions to reproduce the issue are still unknown at the time of writing this.

### Steps to reproduce:

1. Go to Administration -> Users
2. Choose an existing user
3. Choose Delete and confirm the deletion in the popup

### Expected behavior:

The user account gets deleted.

### Actual behavior:

A red notification consisting of word `ENOENT` flashes at the top right corner after pressing `Delete` in the confirmation popup. User account does not get deleted.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: The latest Chromium

### Additional context

This is likely to be related to the code that checks and assigns new owners to the channels owned by the user.

Deleting any newly created users does not trigger the issue, nor does it happen with every single old user either.

Tested with a clean browser session (private window).

### Relevant logs:

...

**Comment by Dnouv** [comment]
Addition info: 
Call to `/v1/users.delete`
```js
// Payload
{
    "userId": "KBLioGZWw9gd9s2",
    "confirmRelinquish": false <--- this needs to be true, if call is made from Admin Panel
}
```
```js
// Response
{
  "success": false,
  "error": "[user-last-owner]",
  "errorType": "user-last-owner",
  "details": {
    "shouldBeRemoved": [
      "koko"
    ],
    "shouldChangeOwner": []
  }
}
```

**Comment by debdutdeb** [comment]
so I'm guessing by the description we're missing the old modal that used to set confirmRelinquish?

**Comment by debdutdeb** [comment]
yep there was a modal that confirmed.

**Comment by jw1892626** [comment]
I saw this issue as well and was able to resolve it by clearing out the avatar that was messed up for that user do this issue: https://github.com/RocketChat/Rocket.Chat/issues/29309

**Comment by debdutdeb** [comment]
May be related to https://github.com/RocketChat/Rocket.Chat/issues/29266

@Gummikavalier are you using filesystem for uploads?

**Comment by Gummikavalier** [comment]
@debdutdeb Yes, filesystem for uploads is in use. So most likely related to that other issue.

**Comment by PurnenduMIshra129th** [comment]
Hello Sir,	@Gummikavalier  i wanted to solve this issue.Please assign this to solve this

**Comment by andys448** [comment]
The same issue with remove rooms.

![image](https://github.com/RocketChat/Rocket.Chat/assets/78227059/b87bab32-31b7-42cc-8d98-6b457a7a0d82)

**Comment by Gummikavalier** [comment]
It just keeps giving :partying_face:

**Comment by Gummikavalier** [comment]
Naturally pruning of old messages is affected too.

**Comment by Gummikavalier** [comment]
At least following confirmed working in production environment:
Deletion of users
Deletion of messages with attachments
Pruning of messages
