### ISSUE TITLE
GUI crashes after opening CAS or email settings

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29301]
### Description:

The application GUI just crashed, when opening CAS(Central Authentication Service) and Email  in the settings. 
### Steps to reproduce:

1. Go to workspace
2. Click on settings
3. open CAS & also Email

### Actual behavior:

![Screenshot 2023-05-20 000135](https://github.com/RocketChat/Rocket.Chat/assets/81948346/46eeacad-eb50-4faa-a594-1ce58467692b)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version:6.0.3 

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by cutzenfriend** [comment]
Hello I have the same issue after updating the docker containers from 6.2.0 to 6.2.2 but it happen instant after login. So I can't even navigate...

<img width="499" alt="Bildschirm­foto 2023-05-20 um 10 31 23" src="https://github.com/RocketChat/Rocket.Chat/assets/1510611/18d8f65e-613f-4fc1-9feb-6a42d9086681">

**Comment by jw1892626** [comment]
I found some of my custom javascript had an error in it and was crashing the application GUI, even though it was not before the update.  Check devtools console to see if there are any js errors.  Also clear out the custom javascript by clearing out the js fields.  IE: `db.getCollection('rocketchat_settings').update({_id:'Custom_Script_Logged_In'}, {$set : {'value': '' }})`

**Comment by debdutdeb** [comment]
> I found some of my custom javascript had an error in it and was crashing the application GUI, even though it was not before the update. Check devtools console to see if there are any js errors. Also clear out the custom javascript by clearing out the js fields. IE: `db.getCollection('rocketchat_settings').update({_id:'Custom_Script_Logged_In'}, {$set : {'value': '' }})`

Would it be possible to share that script with us?

**Comment by jayesh-jain252** [comment]
@debdutdeb Email Settings is causing the application to crash because of (I removed the t function and it worked)

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/4bb68316-8f1e-41d1-ae10-f26aa73e2e74)
at apps/meteor/client/views/admin/settings/inputs/SelectSettingInput.tsx

![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/4d272786-9a89-48df-ba78-33ed7857fd64)

I am guessing this is because of the values that options use in the Email setting are not being handled correctly by the translation service.
![image](https://github.com/RocketChat/Rocket.Chat/assets/79307894/c7e37a3c-80fc-4f4c-8e2c-0da366cfb5c1)

Let me know if I am misunderstanding this.

**Comment by jw1892626** [comment]
> > I found some of my custom javascript had an error in it and was crashing the application GUI, even though it was not before the update. Check devtools console to see if there are any js errors. Also clear out the custom javascript by clearing out the js fields. IE: `db.getCollection('rocketchat_settings').update({_id:'Custom_Script_Logged_In'}, {$set : {'value': '' }})`
> 
> Would it be possible to share that script with us?

I was removing some DOM elements with JS, and when I would change channels and then go back to the original channel it crashed the GUI.  I resolved it by adding a CSS class to the element instead of removing the element.
