### ISSUE TITLE
Webhook doesn't fire

### ISSUE THREAD

**Issue by soler504** [RocketChat/Rocket.Chat#29306]
![Screenshot 2023-05-19 235554](https://github.com/RocketChat/Rocket.Chat/assets/44504839/24672994-03db-4584-8744-af5b244cf16e)
Webhook doesn't trigger when I use the /invite @ command to invite another live agent in an omnichannel chat.

However, if I make a HTTP request to this URL /api/v1/channels.history?roomId=     
the message appears here, also you have a type for this kind of message. In the documentation, the type is "au"

**Comment by debdutdeb** [comment]
Hi, could I ask you to fill the issue template please?

**Comment by soler504** [comment]
![webhook](https://github.com/RocketChat/Rocket.Chat/assets/44504839/9bc3a0de-5aab-492a-a7a8-6e01d0f1fc74)
![webhook2](https://github.com/RocketChat/Rocket.Chat/assets/44504839/5016fac4-1f86-4b62-9aab-0c3eb97cefd7)
![invite user](https://github.com/RocketChat/Rocket.Chat/assets/44504839/c3563ae3-f9c1-4cbf-9033-18f431355897)

If you type the command  /invite @, the webhook doesn't trigger, perhaps it's a message (as you can see in the first image that I attached)  . 

I tried omnichannel webhooks and outgoing webhooks, neither of these kind of webhooks trigger

**Comment by soler504** [comment]
![webhook site](https://github.com/RocketChat/Rocket.Chat/assets/44504839/2169819e-da25-4060-afef-41e8838648cb)

you can use this website to check if the webhooks trigger

**Comment by soler504** [comment]
> Hi, could I ask you to fill out the issue template, please?
