### ISSUE TITLE
Expect editedBy name

### ISSUE THREAD

**Issue by kbrianps** [RocketChat/Rocket.Chat#29300]
Hi,

I'm creating a bot and noticed that the editedBy field doesn't contain a name property like MessageObject.u usually does.

In addition to satisfy developer expectation and provide information clearly, supporting tracking and publicizing, this would avoid the need to have in code another method to get full name.

**Comment by hugocostadev** [comment]
Please, open this issue in the https://github.com/RocketChat/Rocket.Chat.Apps-engine repo
