### ISSUE TITLE
The Phone number does not have validation check in omnichannel 

### ISSUE THREAD

**Issue by Ykumar1415** [RocketChat/Rocket.Chat#29312]
Description:
When we create a new contact, the phone section does not have a limit for the length of phone numbers; it also accepts the alphabet. 

Steps to reproduce:
Go to the omnichannel contact center
Click on the new contact
Expected behavior:
It should check the format of the phone number whether it is valid or not.

Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/97088265/cd5801cc-676b-4f88-9a3b-044f750a7e0e

Server Setup Information:
Rocket.Chat Server: 6.3.0-develop
Operating System: Ubuntu
Deployment Method: Gitpod
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
NodeJS Version: 14.21.3 
MongoDB Version:6.0.3

**Comment by Ykumar1415** [comment]
I am currently working on this issue.

**Comment by anikdhabal** [comment]
This issue has been created before #20528

**Comment by debdutdeb** [comment]
@Ykumar1415 please check first if there is any existing open issue before creating another one.

**Comment by debdutdeb** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/20528

**Comment by debdutdeb** [comment]
closing in favour of #20528

**Comment by Ykumar1415** [comment]
> @Ykumar1415 please check first if there is any existing open issue before creating another one. You can react with a 👍🏼 to any issue to show your support, or add a comment in that issue.

sorry sir, but due to not having any search box option this happened I searched for this issue in the good first issue but it was not there so I created a new one.

**Comment by Ykumar1415** [comment]
Should i make a pull request again  referring to that issue number

**Comment by anikdhabal** [comment]
One PR has been created before #29101.Hopefully I will fix it by today.
