### ISSUE TITLE
Setting Up Rocket Chat locally failed

### ISSUE THREAD

**Issue by thekavikumar** [RocketChat/Rocket.Chat#29314]
Hey there,

I was setting up the rocket chat locally to contribute, but when I use yarn many deps get installed and it ultimately failed.
I don't know why it failed. Can anyone help me set up rocket chat?
![image](https://github.com/RocketChat/Rocket.Chat/assets/50093149/9471c540-ccac-467a-bfb0-429414adb9b4)

**Comment by debdutdeb** [comment]
Please use wsl2.

Closing as not a bug.

**Comment by thekavikumar** [comment]
Please help me this issue 
![image](https://github.com/RocketChat/Rocket.Chat/assets/50093149/544310b5-1390-4395-8df5-4e9f12b23002)
