### ISSUE TITLE
Install guide for docker container does not work out of the box

### ISSUE THREAD

**Issue by bafzachris** [RocketChat/Rocket.Chat#29329]
# Issue description

The install guide (https://hub.docker.com/_/rocket-chat) on docker hub says one should install mongodb:4.0:
`$ docker run --name db -d mongo:4.0 --smallfiles --replSet rs0 --oplogSize 128`

However when starting the rocket chat container the log states that the minimum required mongo version is 4.4.

It works with mongo:5.0. The --smallfiles option is deprecated by mongo as well and  does no longer work.

# Expected 
Rocket chats offical docker container should start.

P.S.
I do not know if this is the right place for this issue.

**Comment by debdutdeb** [comment]
Hi there, we are working on resolving the library rocket.chat image confusion.

Please refer to this for a more up to date documentation on how to install rocket.chat using docker and docker compose.

Closing the issue as it's not a product bug, but please feel free to continue the thread if you have any more questions.
