### ISSUE TITLE
[bug] multiple problems with RC installed in a subdirectory

### ISSUE THREAD

**Issue by rmaksimov** [RocketChat/Rocket.Chat#29331]
### Description:
There are multiple bugs in RC that is installed in a subdirectory

1. The `{SUBDIR}` subdirectory part is missing in a user avatar paths (from some old versions to 6.2.2)
![image](https://github.com/RocketChat/Rocket.Chat/assets/2904679/291d9ad9-dd75-4d6b-a3e9-546b4a4e2766)
actual: `{URL}/account/profile`
expected: `{URL}/{SUBDIR}/account/profile`

2. The `{SUBDIR}` subdirectory part is missing in group chats paths (affected some versions between 6.1.8 and 6.2.2)
actual: `{URL}/group/{NAME}`
expected: `{URL}/{SUBDIR}/group/{NAME}`

3. The `{SUBDIR}` subdirectory part is missing in direct messages paths (affected some versions between 6.1.8 and 6.2.2)
actual: `{URL}/direct/{NAME}`
expected: `{URL}/{SUBDIR}/direct/{NAME}`

4. The `{SUBDIR}` subdirectory part is missing in file uploads paths (from some old versions to 6.2.2; related to #20984). There are two links that allow to download a file, only the first one (on the screenshot below) is affected
![image](https://github.com/RocketChat/Rocket.Chat/assets/2904679/81352538-770a-49ea-9397-8f6b7f0b34c4)
actual: `{URL}/file-upload/{NAME}`
expected: `{URL}/{SUBDIR}/file-upload/{NAME}`

### Steps to reproduce:
In case of avatar:
1. Go to `My account` -> Profile

In case of group chats / direct messages
1. Click on the appropriate chat button

In case of uploads
1. Click on the download _icon_ (cloud with arrow)

### Expected behavior:
A subdirectory part must be included in all paths in RC

### Server Setup Information:
- Version of Rocket.Chat Server: 6.2.2
- Operating System: linux
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.2
- MongoDB Version: 6.0.6

### Client Setup Information
- Desktop App or Browser Version: both
- Operating System: any

**Comment by debdutdeb** [comment]
Hi, @rmaksimov 

We do not officially support subfolder installs. Things breaking is kind of expected. I'll close this issue as it's not something we plan on fixing or supporting right now. 

I would recommend you set rocketchat up in a subdomain instead.

Please feel free to continue this thread - if somebody from the community can help.
