### ISSUE TITLE
Rocketchat rooms are disappearing.

### ISSUE THREAD

**Issue by Sys-Admin992** [RocketChat/Rocket.Chat#29333]
Hi, I have a problem with Rocket Chat where some rooms suddenly disappear, and when the users search for them, the rooms don't appear and look like they were deleted, so I want to know the reason for this problem and if I can restore the hidden rooms.

**Comment by debdutdeb** [comment]
Hi, please fill out the issue template. Without that it's going to be hard to help.

**Comment by Sys-Admin992** [comment]
Ok, But please this is so important for me cause I lost a new many rooms 
I will attach screenshots of this problem
[https://ibb.co/82cftGj
https://ibb.co/PhVYSZ9](url)

**Comment by Sys-Admin992** [comment]
> Hi, please fill out the issue template. Without that it's going to be hard to help.

**Comment by Sys-Admin992** [comment]
> Ok, But please this is so important for me cause I lost a new many rooms
> I will attach screenshots of this problem
> [https://ibb.co/82cftGj](url)
> [https://ibb.co/PhVYSZ9](url)
