### ISSUE TITLE
Multi Whatsapp

### ISSUE THREAD

**Issue by codsec** [RocketChat/Rocket.Chat#29342]
Is possible to have multiple whatsapp numbers/sessions connected?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

The best place to ask this is in our forum, but here it's the answers that I found in the docs.rocket.chat: https://docs.rocket.chat/resources/frequently-asked-questions/whatsapp-business-app-faqs#can-i-have-more-than-one-number-registered-is-there-a-price-difference

Yes, you can have more than one number but there isn’t a difference based on the number of numbers bought.

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
