### ISSUE TITLE
Export data (users, channels, chats etc.) from trial version

### ISSUE THREAD

**Issue by GioWolvie** [RocketChat/Rocket.Chat#29355]
Hello!

I use trial version. Wanna deploy community version and need to save my data from trial to export it to community version. 

Is it possible?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
