### ISSUE TITLE
Mantis webhook

### ISSUE THREAD

**Issue by lobocode** [RocketChat/Rocket.Chat#2935]
In the slack, there is an addon/plugin for integration with the Mantis bug tracker. It would be interesting to something similar in the rocket.  https://github.com/mantisbt-plugins/Slack

**Comment by etcy** [comment]
While we are at this, can we get a redmine webhook as well?

**Comment by Esysteme** [comment]
any news ?

**Comment by geekgonecrazy** [comment]
This would make for a great Rocket.Chat App. But not something we necessarily would want to add to our core code base.

If any want to discuss or propose this feature in detail please feel free to open a post on [our forum](https://forums.rocket.chat) in the feature request category.

Thanks,

**Comment by ratzxx** [comment]
Working MantisBT to RocketChat plugin: https://github.com/ratzxx/MantisBT-Rocket
