### ISSUE TITLE
Late login phase fails with Firefox and Custom Oauth config

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#29351]
### Description:

A clean Firefox session is unable to finish the login to RocketChat instance that uses Custom Oauth config.

Old Firefox sessions work even after logging out and back in.

This is related to existing issue https://github.com/RocketChat/Rocket.Chat/issues/29039 .

I created a separate issue about this because this Firefox issue is fully consistent and reproducible and completely prevents any new users to log into RC using Firefox. Older issue is bit iffy and concerns mostly Chrome.

### Steps to reproduce:

1. Setup Custom Oauth config in RC
2. Login with Custom Oauth provider using a clean session of Firefox (private window will do)

### Expected behavior:

Login succeeds and finishes properly.

### Actual behavior:

The login actually works for the Custom Oauth part, but it stalls at the point where the user privileges and subscriptions to channels should be handled by the Web client and the server. You get three dots cycling forever.

![Screenshot from 2023-05-24 09-18-31](https://github.com/RocketChat/Rocket.Chat/assets/6958942/54525723-f48f-4e49-8d30-c6b774a8b608)

When you look under the `Indexed DB` in the Firefox under `F12 -> Storage -> Indexed DB`, none of the requires tables get recreated, including `localforage` table that would contain the required information to continue the login.

Experimenting using Chrome reveals that the `Indexed DB -> localforage` table should be created immediately after entering the login page, and after the Custom Oauth login phase at the latest. (Using Chrome, if you delete the table while you are still at the login screen, the table gets recreated later during the login.)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox
- Operating System: Any

### Additional context

If you login using old Firefox session that still has the original localforage table in its Indexed DB cache the login works fine. Hence the issue is solely in the creation process of this table.

It is unknown to me whether this issue concerns also provided preset of Oauth configs in RC.

**Comment by crycode-de** [comment]
Seems to be related to #28388 too.

**Comment by Gummikavalier** [comment]
@crycode-de Thanks, I hadn't noticed that one. Indeed this is the same issue. Closing this one in favor of that one.
