### ISSUE TITLE
Label & placeholder of Login and Registration Form is not translated. 

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29362]
### Description:

Label & placeholder of Login and Registration Form is not translated. when login as an user or create new account.
### Steps to reproduce:

1. Login as an user or  create new account

### Expected behavior:

Translate properly.

### Actual behavior:

![Screenshot 2023-05-25 185259](https://github.com/RocketChat/Rocket.Chat/assets/81948346/0c8b19c9-2480-4344-b2b7-a04e69929eff)

![Screenshot 2023-05-25 191459](https://github.com/RocketChat/Rocket.Chat/assets/81948346/c11a5fff-4241-4b27-bcf9-a5d841848f19)
![Screenshot 2023-05-25 195406](https://github.com/RocketChat/Rocket.Chat/assets/81948346/b92188e0-a0e0-4019-8e62-57e6dfffce5e)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: 
- Deployment Method: gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version:14.21.3 - x64 
- MongoDB Version:6.0.3

**Comment by anikdhabal** [comment]
yes, I think . (dot) need to escape. That's why I've replaced it with _ (underscore). And It's translated successfully after those changes. Any suggestion apart from this? @hugocostadev

**Comment by hugocostadev** [comment]
Great, I'll close it
