### ISSUE TITLE
CAS stopped working on version 6.2.2

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#29376]
### Description:

After an update to Rocketchat 6.2.2 from 3.15, following a proper upgrade path ( 3.15 -> 4.0.6 -> 4.8.7 -> 5.4.10 -> 6.2.2) and also upgrading Mongo to 5.0 while at Rocketchat 4.0.6, the CAS Login Stopped working.

### Steps to reproduce:

1. Click on CAS Login Button
2. Enter your CAS credential and login

### Expected behavior:

The CAS login windows closes and you are redirected to rocketchat workspace home

### Actual behavior:

The CAS login windows closes, you are not redirected and stay in the login page

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.2
- Operating System: tested on Ubuntu 18.04 LTS and RHEL 8
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- MongoDB Version: 5.0.18

### Client Setup Information

Tested and replicated with Chrome , Firefox, desktop app

### Relevant logs:

There are no logs whatsoever from the browser console
The only log entry when trying to login via CAS, on rocketchat side, are these:

{"level":20,"time":"2023-05-26T10:37:34.015Z","pid":1,"hostname":"af39ef1a251a","name":"CAS","msg":"Using CAS_base_url: https://*******.com/cas/"}
{"level":30,"time":"2023-05-26T10:37:34.043Z","pid":1,"hostname":"af39ef1a251a","name":"CAS","msg":"Validated user: myuser"}

**Comment by xl32** [comment]
I observe the same behavior with SAML and 2FA in 6.2.0-6.2.2. If 2FA is turned off (e.g. from the mobile app), login works OK.
Do you have 2FA?

**Comment by JohnLukeP** [comment]
> I observe the same behavior with SAML and 2FA in 6.2.0-6.2.2. If 2FA is turned off (e.g. from the mobile app), login works OK. Do you have 2FA?

Hi, 
no, we have 2FA disabled; it was also disabled before upgrading.

**Comment by hipoloco** [comment]
This issue is related with #29039. Check my message for a workaround.

**Comment by brtptrs** [comment]
We are also seeing this on 6.2.5 using CAS and with 2fa disabled
The RocketChat support team is currently investigation this issue

**Comment by hipoloco** [comment]
The problem still persists in version 6.2.6. The following error appears in Firefox console:

> TypeError: a.default.detectStore(...) is undefined h1-check.js:formatted:92:16
>     u h1-check.js:92
>     1337 h1-check.js:124
>     n h1-check.js:11
>     <anónima> h1-check.js:66
>     <anónima> h1-check.js:67
>     inject ExtensionContent.jsm:593
>     AsyncFunctionNext self-hosted:756

**Comment by brtptrs** [comment]
For us the problem is also not solved with 6.2.6

**Comment by casalsgh** [comment]
The internal eng teams are checking into it.

**Comment by casalsgh** [comment]
Team, FYI - The internal squads are still working on this. Most likely fix will be on 6.4.0

**Comment by JohnLukeP** [comment]
Hi, has this been resolved only on 6.4.0? october first will be the deadline for services and we still can't move from 6.1.8, which is the latest working with CAS.

**Comment by casalsgh** [comment]
6.4.0 should be out today. The fix will be available on this version.
