### ISSUE TITLE
Unable to open Releases inside App info

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29384]
### Description:

Unable to open Releases inside App info
### Steps to reproduce:

1.Go to Marketplace
2. Go to App info
3. open Releases 

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/81948346/f923a13d-099c-4151-b5d3-cf180bf96c49

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0-develop
- Operating System: 
- Deployment Method: gitpod
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version:14.21.3 - x64 
- MongoDB Version:6.0.3

**Comment by adityagarg06** [comment]
Hi @hugocostadev, I want to contribute to the issue. Could you assign me the issue.

**Comment by Rottenblasters** [comment]
@hugocostadev 
I was looking into this issue, when I found out that the request to fetch the `versions list` is giving a server error (`500 code`)
I am attaching the picture below for reference. I am not able to understand why this is happening.
![rocket chat issue](https://github.com/RocketChat/Rocket.Chat/assets/68077049/a41d28d8-5d49-454c-a8a4-2ae7cedde03b)

**Comment by Ravindra283** [comment]
@hugocostadev 
This marketplace API breaking throwing a 404 not found error. 
https://marketplace.rocket.chat/v1/apps/7a8cd36b-5f7b-4177-bd7f-bfc9be908bf8/versions

![Screenshot from 2023-05-30 22-10-49](https://github.com/RocketChat/Rocket.Chat/assets/115916318/ad090140-5ec1-4717-9a61-d56b199913f4)

**Comment by pankaj87072** [comment]
@adityagarg06 are you working on it

**Comment by adityagarg06** [comment]
@pankaj87072 yeah im trying, you can also go ahead

**Comment by subhrajyoti-basu** [comment]
I tried to fix the issue using codespace but the dev server is not starting. I want to start contributing looking for help with running the development server.

**Comment by jayesh-jain252** [comment]
@subhrajyoti-basu you could try using Gitpod. Gitpod Server Environment Setup Docs: https://developer.rocket.chat/open-source-projects/server/server-environment-setup/gitpod

**Comment by subhrajyoti-basu** [comment]
> @hugocostadev I was looking into this issue, when I found out that the request to fetch the `versions list` is giving a server error (`500 code`) I am attaching the picture below for reference. I am not able to understand why this is happening. ![rocket chat issue](https://user-images.githubusercontent.com/68077049/241959193-a41d28d8-5d49-454c-a8a4-2ae7cedde03b.png)

I checked the issue and it was from the backend server need some time to check on the code. I am new to the folder structure and design pattern.

**Comment by subhrajyoti-basu** [comment]
`` const request = await fetch(`${baseUrl}/v1/apps/${this.urlParams.id}/versions`, { headers }) `` on location ``apps/meteor/ee/server/apps/communication/rest.ts`` it uses another domain ``'https://marketplace.rocket.chat'``
the problem lies on that domain it returns no value that causes the 500 internal error

**Comment by subhrajyoti-basu** [comment]
Where can I get `` https://marketplace.rocket.chat `` API end points

**Comment by AryanChopraa** [comment]
hey @hugocostadev ! is this issue still open i would like to contribute
