### ISSUE TITLE
Slash commands as events

### ISSUE THREAD

**Issue by warcode** [RocketChat/Rocket.Chat#294]
Slash commands such as 

    /topic
    /me
    /slash parameter1 parameter2

should have a built-in handler that lets plugins register for the callbacks.

Returns the parameter(s) entered by the user.

**Comment by sampaiodiego** [comment]
we do have plugins and handlers for this =)

as you can see the /me command on https://github.com/RocketChat/Rocket.Chat/tree/master/packages/rocketchat-me

so, unless you want a specific command I'll close this issue, ok?

**Comment by warcode** [comment]
As it is now each plugin has to check for /x in a message and handle it from there.

What I am proposing is a single system that checks for /x before any real "message" is sent, generating a callback to the registered function for x. This makes it possible to restrict having a command affecting  multiple plugins, which might break things. The current system also makes it cumbersome to have a /help listing all the available slash commands, while a single slash command handler would know the registered commands and be able to list them all.
