### ISSUE TITLE
Widget do Livechat  ADD BUTTONS

### ISSUE THREAD

**Issue by karlos-silva2** [RocketChat/Rocket.Chat#29403]
There is some release that offers the inclusion of buttons in the Livechat widget. For user interaction

**Comment by aryanpaul123** [comment]
i want to contribute in this project

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

No, there isn't ... If you would like to propose a feature request to this, you can open an issue in the https://github.com/RocketChat/feature-requests repo

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
