### ISSUE TITLE
Pressing enter in Search Channels leaves search

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2941]
Your Rocket.Chat version: 0.26

When entering a search term in the "Search Channels" it feels natural to press the enter key.

If Enter key is pressed you will be redirected back to the channel, this is an annoying experience.

An Enter press should result in nothing.

**Comment by marceloschmidt** [comment]
Agreed! Should be an easy fix `e.preventDefault()` on keydown, checking e.keyCode
