### ISSUE TITLE
bug: group with a Persian name

### ISSUE THREAD

**Issue by bahmanjafari** [RocketChat/Rocket.Chat#29410]
Hello

Please make it possible to create a group with a Persian name if possible.

Bests

**Comment by ghonche** [comment]
same issue here :(

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

I created a channel with a Persian name, what issue/error are you receiving? 

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/29bc92bb-fb0e-4540-9c7a-85848b01ea4c)

Check this setting:
![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/7abe7a55-e80a-4fa0-9602-e7b1548a8c4b)


---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by bahmanjafari** [comment]
Thank you @hugocostadev 

After the update to 6.2.2, the problem was solved.

Bests
