### ISSUE TITLE
Marketplace / Cloud Login does not work

### ISSUE THREAD

**Issue by ChrisLauinger77** [RocketChat/Rocket.Chat#29414]
### Description:

I want to login to cloud to be able to install Jitsi plugin but the an error appears:
"Error
page.oauthAuthorizationPage.error.oauth_invalid_workspace_redirect_uri . RequestId: d9673dd6-dd60-47e7-a3cb-db7cb2a88200"

### Steps to reproduce:

1.  Connectivity Services
2.  Login to Rocket.Chat Cloud
3. 

Cloud console and sync works though

### Expected behavior:

Cloud login possible - Marketplace usable

### Actual behavior:

![Bildschirmfoto vom 2023-05-31 19-35-46](https://github.com/RocketChat/Rocket.Chat/assets/3518684/605b3146-bc3f-4e9b-9bb2-120e17ffa2ef)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: debian / egroupware package
- Deployment Method: 
- Number of Running Instances: 1

+------------------------------------------------------------------------+
|                             SERVER RUNNING                             |
+------------------------------------------------------------------------+
|                                                                        |
|  Rocket.Chat Version: 5.4.10                                           |
|       NodeJS Version: 14.19.3 - x64                                    |
|      MongoDB Version: 5.0.18                                           |
|       MongoDB Engine: wiredTiger                                       |
|             Platform: linux                                            |
|         Process Port: 3000                                             |
|             Site URL: https://egroupware.conop-systems.com/rocketchat  |
|     ReplicaSet OpLog: Enabled                                          |
|          Commit Hash: ba268c5004                                       |
|        Commit Branch: HEAD                                             |
|                                                                        |
+------------------------------------------------------------------------+

### Client Setup Information

- Desktop App or Browser Version:
Firedfox 102.11.0esr (64-Bit)
Chromium Version 113.0.5672.126 (Offizieller Build) built on Debian 12.0, running on Debian 12.0 (64-Bit)
- Operating System: debian bookwork (client) debian bullseye (server)

How can I get it working to have back Jitsi ? Any advise would be appreciated.

**Comment by hugocostadev** [comment]
You can go directly to https://cloud.rocket.chat/ login and authorize your workspace by there. Can you try and let me know if works? Thanks 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by ChrisLauinger77** [comment]
I see my workspace - it is also active:
![Bildschirmfoto vom 2023-05-31 20-08-30](https://github.com/RocketChat/Rocket.Chat/assets/3518684/e71375af-d78c-44e4-9121-abdcd639e8a0)
Where can I authorize it ? I do not see any possibility to do this ...

**Comment by hugocostadev** [comment]
Can you share a print screen from the page that you click to activate Jitsi?

**Comment by ChrisLauinger77** [comment]
Step 1
![Bildschirmfoto vom 2023-05-31 20-36-39](https://github.com/RocketChat/Rocket.Chat/assets/3518684/b3cefcb7-0b9b-475d-a373-8f7368150c41)
Step 2
![Bildschirmfoto vom 2023-05-31 20-36-44](https://github.com/RocketChat/Rocket.Chat/assets/3518684/be944461-c6c8-4264-aec8-2af24dc701e5)
Step 3
![Bildschirmfoto vom 2023-05-31 20-36-56](https://github.com/RocketChat/Rocket.Chat/assets/3518684/f88badcc-9e7b-461a-89fe-3ac4f0c0d19c)

**Comment by hugocostadev** [comment]
Hi @ChrisLauinger77  

we do not request cloud authorization to install an app if the workspace is registered anymore

Rocket.Chat will provide only security fixes and answer support tickets related to configuration and usage for the below-mentioned versions. Bugs not related to security issues will be fixed only in new versions. But Pull requests are welcome

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by geekgonecrazy** [comment]
Specifically the login requirement was removed in 6.x so upgrading won't require login any more.  Its not something we can back port.

Side note.. This is related to the subfolder part of the address.  Subfolder specifically is an installation method we still don't fully support.  

But upgrading to 6.x will get you past this.
