### ISSUE TITLE
Marketplace AppFilters component changed

### ISSUE THREAD

**Issue by Rottenblasters** [RocketChat/Rocket.Chat#29432]
### Description:

It seems that the `AppsFilter` component of Marketplace has had some UI changes which is making it look bad. I am not sure if it has been done purposely or it was by mistake, but in my opinion the previous UI looked much better and cleaner.

### Steps to reproduce:

1. Open your Rocket.chat application in browser
2. Go to Marketplace
3. Click on Explore

### Expected behavior:

![issue_expected_behaviour](https://github.com/RocketChat/Rocket.Chat/assets/68077049/2bf26064-8475-4eb2-a5ce-2a0de74d01cd)

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/68077049/7d00577e-c0da-4b15-ab34-701a6c8f3b9a

### Server Setup Information:

- Version of Rocket.Chat Server: `6.3.0-develop`
- Operating System: 
- Deployment Method: `gitpod`
- Number of Running Instances: `1`
- DB Replicaset Oplog: 
- NodeJS Version:` v14.21.3`
- MongoDB Version: `6.0.3 / wiredTiger (oplog Enabled)`

**Comment by hugocostadev** [comment]
fixed by: https://github.com/RocketChat/Rocket.Chat/pull/29443
