### ISSUE TITLE
display a "No data found" message when there is no item when clicking on any omnichannel sideBar contents

### ISSUE THREAD

**Issue by wilsonfurtado2000** [RocketChat/Rocket.Chat#29445]
### Steps to reproduce:

1.  Click on the three-dot icon 
2.  click on omnichannel 
3.  click on the any of the sidebar components 

### Expected behavior:

<img width="1440" alt="Screenshot 2023-06-03 at 10 23 08 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/72563697/291e6354-4e54-4ab2-bfd7-719913fcd361">

### Actual behavior:

It displays table containing empty rows 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by yashcodewallah** [comment]
hey can you assign me this issue ?
