### ISSUE TITLE
Fails to generate http links from custom tld

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#29451]
### Description:

RocketChat does not support custom tld. My University is using a custom tld **.prive**

When inserting a http link for this tld, Rocket does not detect the link.

### Steps to reproduce:

Enter http://myserver.mydomain.prive/file.html => no link

Enter http://myserver.mydomain.fr/file.html => link

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.2
- Operating System:  Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.3
- MongoDB Version: 6.0.0

### Client Setup Information

- Desktop App or Browser Version: Firefox (last)
- Operating System: Linux

**Comment by ankar84** [comment]
Please set up option `Custom Domain Whitelist for Auto Link` at `Admin UI - Settings - Message` with your custom tld **prive**

**Comment by hugocostadev** [comment]
Please @bellegarde-c follow @ankar84 suggestion, we do support custom TLD.
