### ISSUE TITLE
Login into Cloud Console gives page.oauthAuthorizationPage.error.oauth_invalid_workspace_redirect_uri error

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#29450]
The instance is self-hosted and connected to Rocket.Chat cloud. It has been updated to Rocket.Chat 5.4.10 lacking Jitisi integration for converence calls. 

So I search the Jitsi app and tried installing it, which requires to login to Rocket.Chat cloud. 

That login fails reproducable :(

### Description:

The Rocket.Chat cloud login fails/stops with the following URL: 
https://cloud.rocket.chat/authorize?response_type=code&client_id=646f5de0ce4e06000136cd55&redirect_uri=https://bb-compat.egroupware.de/rocketchat/admin/cloud/oauth-callback&scope=openid%20offline_access&state=Jzth8d3EjbTz9zcmM

and an OAuth error page.oauthAuthorizationPage.error.oauth_invalid_workspace_redirect_uri 
![Bildschirmfoto 2023-06-05 um 09 36 17](https://github.com/RocketChat/Rocket.Chat/assets/972180/615c21d1-f7fd-4089-8e81-d6f0cc2afc92)

> It might be caused by our Rocket.Chat instances being installed under the URL/path-prefix /rocketchat and not directly in the root.

### Steps to reproduce:

1. Go to Connectivity Services
2. Click on [Login to Rocket.Chat Cloud]
3. OAuth login fails with the above error-message

### Expected behavior:

Login should work ;)

### Actual behavior:

See above screenshot

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.10
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.19.3
- MongoDB Version: 4.2.24/wiredTiger

### Client Setup Information

- Desktop App or Browser Version: current Chrome 114.0.5735.90
- Operating System: MacOS 12.6.5
- Tried with other browsers and OS, result is always the same

### Additional context

I can give you access to the Rocket.Chat instance, so you can test it yourself.

### Relevant logs:

Nothing in the logs, when the OAuth login fails, which is not unexpected as it fails on the Rocket.Chat cloud side ...

**Comment by hugocostadev** [comment]
duplicated of https://github.com/RocketChat/Rocket.Chat/issues/29414
