### ISSUE TITLE
[bug] The "goto message" button in Starred post list are not shown

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2945]
Your Rocket.Chat version: 0.27

![image](https://cloud.githubusercontent.com/assets/16319433/14637112/e5d4e616-0637-11e6-83e7-5c062eec3a6a.png)

In the Mentions list all ok, but in Starred and Pinned list the gear button doesn't work

The version 0.26 does not have this bug

**Comment by zxweed** [comment]
http://demo.rocket.chat has the same problem

**Comment by zxweed** [comment]
@geekgonecrazy, can you check this bug, please?

**Comment by geekgonecrazy** [comment]
@rocketchat/core any ideas why this stopped working?

**Comment by sampaiodiego** [comment]
I'm looking into it right now.
no idea why it stoped working though

**Comment by sampaiodiego** [comment]
as metioned in #3026 it doesn't working on searches too
