### ISSUE TITLE
Changing Profile Picture doesnt work

### ISSUE THREAD

**Issue by knordsiek** [RocketChat/Rocket.Chat#29465]
After changing the profile picture an save it it caught an error: Enoent
The profile image didn' t change 

### Steps to reproduce:

1. My Account
2. Set new profile image
3. save changes

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Rocky Linux 8
- Deployment Method: Stand alone Server
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version: Browser an Client affected
- Operating System: Ubuntu div.

**Comment by AyushKaithwas** [comment]
> After changing the profile picture an save it it caught an error: Enoent The profile image didn' t change
> 
> ### Steps to reproduce:
> 1. My Account
> 2. Set new profile image
> 3. save changes
> 
> ### Server Setup Information:
> * Version of Rocket.Chat Server:
> * Operating System: Rocky Linux 8
> * Deployment Method: Stand alone Server
> * Number of Running Instances: 2
> * DB Replicaset Oplog: enabled
> * NodeJS Version: 14.21.3
> * MongoDB Version: 6.0
> 
> ### Client Setup Information
> * Desktop App or Browser Version: Browser an Client affected
> * Operating System: Ubuntu div.

I cannot reproduce this issue, can you provide a video of this issue?

**Comment by StevenSeifried** [comment]
I also can't reproduce it anymore. Seems to be fixed with the latest release

**Comment by knordsiek** [comment]
Yes fixed with 6.25
