### ISSUE TITLE
The best way to use Rocket.Chat inside of ios Application?

### ISSUE THREAD

**Issue by SimBioT1954** [RocketChat/Rocket.Chat#29467]
Hello!

With the [Rocket.Chat.iOS](https://github.com/RocketChat/Rocket.Chat.iOS) repository being archived, it appears that there is currently no way to incorporate Rocket Chat into a new Swift app. Is this correct?

My team is very fond of the platform and would like to use it in our product. We hope to integrate the platform seamlessly so that our users can have the best possible chat experience. However, we are looking for shortcuts to launch our app as quickly as possible without having to create an entirely new Swift client for Rocket Chat.

What is the best approach to take in order to launch our app with Rocket Chat quickly? 
Any help would be greatly appreciated! 👍

**Comment by Shaik-Sirajuddin** [comment]
You can use Rocket.Chat.ReactNative Repo .
React Native is a cross platform framework for mobile apps , you can launch both android and ios app from the same codebase. RocketChat has is React Native repo here : https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

You have some options, depends a lot of your use case

Chat Engine: https://developer.rocket.chat/chat-engine/overview-of-chat-engine
Embedded layout: https://developer.rocket.chat/customize-and-embed/embedded-layout
Our API: https://developer.rocket.chat/reference/api
Mobile White-label:  https://developer.rocket.chat/open-source-projects/mobile-app/mobile-app-white-labelling

Sorry, but GitHub is only for issues/bugs related to the repository project, closing this issue

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
