### ISSUE TITLE
Desktopnotification within threads doesnt work

### ISSUE THREAD

**Issue by knordsiek** [RocketChat/Rocket.Chat#29463]
### Description:

If you write a message within a thread the other user doesn' t get a desktopnotification.
only if he is named the notification poped up.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.2
- Operating System: Rocky Linux 8
- Deployment Method:  Standalone Server
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version: Client: 3.9.4 also with Chromium 114.0.5735.90 
- Operating System: Kubuntu 20.04 and other

**Comment by hugocostadev** [comment]
Hi @knordsiek , can you check with the latest `develop` branch? I could not reproduce it here...

Witch type of channel are you using? Are you sure that the user that supposes to receive the notification is following the thread? (bell icon **without** cross mark)
