### ISSUE TITLE
ZIP attach are not possible

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2946]
Your Rocket.Chat version: 0.27

I have enabled the **application/zip** MIME-type, but cannot attach the zip files:

![image](https://cloud.githubusercontent.com/assets/16319433/14637244/c2c8c60a-0638-11e6-8264-8f038c52ea2a.png)

![image](https://cloud.githubusercontent.com/assets/16319433/14637261/e494e494-0638-11e6-9bcb-b36c9ad11b49.png)

**Comment by engelgabriel** [comment]
Did you try restarting the server or refreshing the page?

**Comment by zxweed** [comment]
@engelgabriel, yes, I have restarted and updated the server many times. I see this bug at four last releases..

**Comment by engelgabriel** [comment]
Have you seen this? http://stackoverflow.com/questions/6977544/rar-zip-files-mime-type

Maybe try `application/zip, application/octet-stream` ?

**Comment by jclabaugh** [comment]
We use `application/zip,application/x-compressed-zip` and can upload.zip files ok.

**Comment by engelgabriel** [comment]
thanks @jclabaugh

**Comment by engelgabriel** [comment]
@zxweed please reopen if the recommended setting doens't work.

**Comment by zxweed** [comment]
@engelgabriel, nope, I have specified all media types, but cannon attach zip files (pictures and pdfs are ok):

![image](https://cloud.githubusercontent.com/assets/16319433/14645880/155d8a64-0660-11e6-8961-8bcac1f1220b.png)

**Comment by subesokun** [comment]
I'm facing the exact same issue as @zxweed

**Comment by engelgabriel** [comment]
I have just created https://github.com/RocketChat/Rocket.Chat/issues/3217 to hep this issue.
