### ISSUE TITLE
Search (Control + K) for quick open a chat with keyboard not working

### ISSUE THREAD

**Issue by lucassch** [RocketChat/Rocket.Chat#29466]
### Description:

Search (Control + K) for quick open a chat with keyboard not working

### Steps to reproduce:

1. Press control + K
2. Write the user or channel name
3. Press arrow down and enter

### Expected behavior:

Highlight the selected user and iopen a chat by keyboard

### Actual behavior:

Arrow down/up doesnt work
If enter pressed, the page reload
Only works if clicks on user with the mouse

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.2
- Operating System: Ubuntu 22.04.1 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Latest windows app and updated google chrome.
- Operating System: Windows 11

### Relevant logs:

```
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1599:3494881
    at 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:5:86707
    at ArrowDown (81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1599:3495593)
    at 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1328:8709
    at Array.forEach (<anonymous>)
    at HTMLInputElement.<anonymous> (81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1328:8392)
(anonymous) @ 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1599
(anonymous) @ 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:5
ArrowDown @ 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1599
(anonymous) @ 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1328
(anonymous) @ 81376f3c070c7bbdca5b39608384c51da0ce70e3.js?meteor_js_resource=true:1328
```
![image](https://github.com/RocketChat/Rocket.Chat/assets/4160094/a39fabdc-b192-4c5d-8994-dbbdcb0ddaa6)

**Comment by bmangilli** [comment]
it happens to me too

**Comment by wilsonfurtado2000** [comment]
it works fine in local development environment ,but  yea in the production the issue is present (macOS)

**Comment by AyushKaithwas** [comment]
I am working on this
