### ISSUE TITLE
[feature] Let users a way to specify some about info..

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2947]
Your Rocket.Chat version: 0.31

..It may be a tag line only. And will be great to search (or filter userlist) by this info.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
