### ISSUE TITLE
Allow non-latin letters in room names

### ISSUE THREAD

**Issue by subhog** [RocketChat/Rocket.Chat#2948]
Rocket.Chat version: 0.27.0

When I'm trying to open a room with non-latin letters I've got an error stating that I should only use letters, numbers and dashes. This is a serious shortcoming for internationalization.

**Comment by marceloschmidt** [comment]
Have you tried changing UTF8 Names Validation under Administration / General?

![image](https://cloud.githubusercontent.com/assets/1986378/14932610/639f0da0-0e4f-11e6-94fa-3e98a5366d76.png)

Let me know how it goes.

**Comment by geekgonecrazy** [comment]
Let us know if you had any issues with the advice suggested above 👍
