### ISSUE TITLE
How i build

### ISSUE THREAD

**Issue by devwill** [RocketChat/Rocket.Chat#295]
How i build a web version

**Comment by rodrigok** [comment]
Can you be more specific?

**Comment by devwill** [comment]
estou tendo dificuldade de rodar o rocket no meu servidor tenho pouca experiencia com apps assim e gostaria de instala-lo para estudos

**Comment by mcsaucy** [comment]
Hey Devwill,

The development installation instructions work fairly well if you're simply looking to try it.
```
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor
```

**Comment by rodrigok** [comment]
Fala @devwill, como tu está tentando rodar ele? Tem 2 formas, uma usando o Meteor como descrito pelo @mcsaucy e outra compilando e rodando direto com o node.

**Comment by devwill** [comment]
qual o processo para compilar pelo node e rodar no meu servidor poderia me enviar pelo email por gentileza ewill849@gmail.com

**Comment by rodrigok** [comment]
@devwill você pode seguir este script: https://github.com/RocketChat/Rocket.Chat/blob/master/build.sh

Basicamente você precisa fazer o seguinte:
* Fazer build do projeto *meteor build --server url.do.teu.server.com ./*
* Pegar o tar.gz e descompactar dentro do teu server
* Entrar na pasta *bundle/programs/server*
* Instalar as dependências *npm install*
* Voltar para a pasta *bundle* e rodar o arquivo main.js *node main.js*
* Não esqueça de setar as variáveis de ambiente MONGO_URL, MONGO_OPLOG_URL e ROOT_URL

**Comment by devwill** [comment]
I build with meteor and now how i publish in my server
