### ISSUE TITLE
Create global and personal settings to hide user role labels

### ISSUE THREAD

**Issue by taybin** [RocketChat/Rocket.Chat#2950]
Your Rocket.Chat version: 0.27.0
In a small group like mine, the user role labels are distracting and unnecessary.  Is there a way to hide them?

**Comment by tmanternach** [comment]
It looks like you can manually remove the labels in Admin->Permissions. https://github.com/RocketChat/Rocket.Chat/pull/2858#issuecomment-211884750

**Comment by lvh1** [comment]
or you could use some custom css to hide it for everyone :p 
`.role-tag{display:none !important;}`

**Comment by agentirons** [comment]
Just ran into this too, it's true that you can workaround it for the time being by going to Admin->Permissions, clicking the edit button next to a user type (column headers) and deleting the Description field.

**Comment by andreas-bulling** [comment]
There should IMHO be an option to switch these off globally - I was searching for exactly that after upgrading to 0.27.0

**Comment by mylesw-luma** [comment]
+1 - the tags add clutter.

**Comment by jimt** [comment]
As a workaround, adding
`.role-tag {display: none;}`
to your `Administration > SETTINGS > Layout > Custom CSS` will hide the tags.

**Comment by Sing-Li** [comment]
@jimt   Brilliant!    Do you mind creating a "Pro tips" section in our doc and adding this?  It will be very useful for others for sure!   TIA

PR against this would be appreciated:

https://github.com/RocketChat/Rocket.Chat.Docs/tree/master/6.%20Developer%20Guides

**Comment by pescobar** [comment]
+1 for adding this as a global setting and user setting

**Comment by KyleK1782** [comment]
> As a workaround, adding `.role-tag {display: none;}` to your `Administration > SETTINGS > Layout > Custom CSS` will hide the tags.

Somehow this is still an issue where the setting doesn't work in Administration > SETTINGS > Layout >  User Interface -> Display Roles (off). The updated CSS tag is `rcx-message-header__roles` based on 5.0.6. 

Adding the below to Administration > SETTINGS > Layout > Custom CSS will remove the role tags in messages.  
```
.rcx-message-header__roles { display: none !important; }
```

**Comment by PvUtrix** [comment]
> > As a workaround, adding `.role-tag {display: none;}` to your `Administration > SETTINGS > Layout > Custom CSS` will hide the tags.
> 
> Somehow this is still an issue where the setting doesn't work in Administration > SETTINGS > Layout > User Interface -> Display Roles (off). The updated CSS tag is `rcx-message-header__roles` based on 5.0.6.
> 
> Adding the below to Administration > SETTINGS > Layout > Custom CSS will remove the role tags in messages.
> 
> ```
> .rcx-message-header__roles { display: none !important; }
> ```
Thx! Worked for me on 5.4.2 as well
