### ISSUE TITLE
Cannot send a message to a private room to which a user with Administrator privileges does not belong.

### ISSUE THREAD

**Issue by takano-mts** [RocketChat/Rocket.Chat#29503]
hi.
I need your help.
As the title says I am a administrator privileges trying to send a message using postMessage or sendMessage to a private room.
However, I get an error "error-not-allowed" and cannot send the message.
So I checked the source code,
I found that the function "canAccessRoom" seems to be involved.

Based on the above, I have the following questions.

1. If I modify the source code to be able to send messages, is there a possibility of increasing the vulnerability?
2. Is there a setting that allows this without modifying the source?
3. I think intentionally blocking the message, is it wrong to do the above modification?

Thank you.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the questions! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project, but here it goes you answers:  

1. If I modify the source code to be able to send messages, is there a possibility of increasing the vulnerability?
**A: Yes, if you do this any admin can do the same and you will be blocked for other updates on that** 

2. Is there a setting that allows this without modifying the source?
**A: No, but you can create a specific user for that and add it to all channels, or even better, create a app or webhook**

3. I think intentionally blocking the message, is it wrong to do the above modification?
**A: It's not wrong, only members or apps can send messages to the channel** 
---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
