### ISSUE TITLE
Cannot upload files since update

### ISSUE THREAD

**Issue by Sirttas** [RocketChat/Rocket.Chat#29506]
### Description:

We updated to 6.2.3 and we cannot upload files anymore, its just never show up without any logs.

### Steps to reproduce:

1. Upload a file
2. Nothing happen

### Expected behavior:

The file gets uloaded

### Actual behavior:

The file don't get uloaded.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.3
- Operating System: linux/docker
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.18 

### Client Setup Information

- Desktop App or Browser Version: tried with app and web
- Operating System: tried on both windows and MacOS

### Relevant logs:

There is no new log apearing after the issue occure.

**Comment by colombani** [comment]
Same issue noticed

**Comment by hugocostadev** [comment]
Hi @Sirttas and @colombani , is this still happening?  I could not reproduce it here... What browser and File Storage are you using? thanks

**Comment by colombani** [comment]
Hi @hugocostadev, since this morning, I can upload images but only with 1 user (among about 25) and in 1 channel.
I can not send that same file to other users or channels.
How could I help you ?
