### ISSUE TITLE
why no 6.25?

### ISSUE THREAD

**Issue by wtoshopnet** [RocketChat/Rocket.Chat#29504]
# sudo snap search rocketchat-server
Name                           Version  Publisher           Notes  Summary
rocketchat-server              6.2.3    rocketchat✓         -      Rocket.Chat server
rocketchat-server-development  4.3.0    debdut-chakraborty  -      An Open Source Slack Alternative

**Comment by wtoshopnet** [comment]
give me  centos 9 stream install list .thanks.

**Comment by hugocostadev** [comment]
Sorry, I don't understand what you are looking for... 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
