### ISSUE TITLE
threads having long descriptions overlap with its content 

### ISSUE THREAD

**Issue by wilsonfurtado2000** [RocketChat/Rocket.Chat#29501]
### Description:

<img width="1420" alt="Screenshot 2023-06-08 at 3 39 20 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/72563697/04bf93d2-840f-415b-8421-1a2c498b7e48">

### Steps to reproduce:

1. Go to any channel 2. 
2. click on the thread icon which will display all the threads3. 
3. you can see that the content of some threads which have large content overlap with each other

### Expected behavior:

either we need to show the three dot placeholder if content is more than the space , or allocate the required amount of space

### Actual behavior:

content overlaps with each other

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases, this print was taken how on the day that you raised the issue? 

Are you using witch browser? 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
