### ISSUE TITLE
Help me out !

### ISSUE THREAD

**Issue by ayushgupta4002** [RocketChat/Rocket.Chat#29511]
**I was trying to setup this repo locally but faced error like this while installing dependencies!**

![image](https://github.com/RocketChat/Rocket.Chat/assets/66496371/7cb4fc6e-769c-426b-9c9a-4b6ccf22eb5a)

**These are the build logs** 

`# This file contains the result of Yarn building a package (@rocket.chat/forked-matrix-sdk-crypto-nodejs@npm:0.1.0-beta.12)
# Script name: postinstall

[31m[1mInternal Error[22m[39m: @rocket.chat/forked-matrix-sdk-crypto-nodejs@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at TR.getCandidates (C:\Users\Ayush\Desktop\projects\Rocket.Chat\.yarn\releases\yarn-3.2.2.cjs:435:5226)
    at wd.getCandidates (C:\Users\Ayush\Desktop\projects\Rocket.Chat\.yarn\releases\yarn-3.2.2.cjs:391:1281)
    at C:\Users\Ayush\Desktop\projects\Rocket.Chat\.yarn\releases\yarn-3.2.2.cjs:439:7764
    at Lg (C:\Users\Ayush\Desktop\projects\Rocket.Chat\.yarn\releases\yarn-3.2.2.cjs:390:11154)
    at ce (C:\Users\Ayush\Desktop\projects\Rocket.Chat\.yarn\releases\yarn-3.2.2.cjs:439:7744)
`

**Comment by Shaik-Sirajuddin** [comment]
I faced the same issue while setting up the repo in windows , tried on ubuntu 22.04.2 wsl it worked.
To solve this you may try installing wsl and setting up local in development in linux system.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question, join our open community, it's the best place to ask for help! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
