### ISSUE TITLE
Deleting a file without deleting the whole post

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#2951]
Your Rocket.Chat version: 0.27.0

_**Improvement**_
When you delete a picture/file from your post it deletes the whole post (including valuable data like messages).  This should be improved to only remove the file/image itself and not the whole post.

**Comment by louisemessage** [comment]
Thank you for your suggestion. This feature is not on our short-term roadmap so we will revisit once other priorities have been addressed.
