### ISSUE TITLE
How do I use full width for Rocket.Chat API chat.sendMessage message block text?

### ISSUE THREAD

**Issue by airedwin** [RocketChat/Rocket.Chat#29520]
### Description:

When I send a message as a block with sections, in the channel the message shows up with a fixed width style (rcx-message-block--width-fixed) instead of using the full width of the channel. How do I get it to use the full with the same way it shows when I send it as message.msg?

### Steps to reproduce:

1. Use API to sendMessage (/api/v1/chat.sendMessage)
2. `{
    "message": {
        "rid": "GENERAL",
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*Text example* Normal message `code` here"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "Malone's mission to keep the Nuggets thinking about hoops, not that trophy, could be helped by the fact that Miami's only win in this series came a week ago in Denver. Also, the Heat have won seven road games during the postseason and are 2-0 when they've faced elimination — against Chicago in the play-in tournament and at Boston in Game 7 of the conference finals.  When the teams left Denver a week ago, the series was tied at 1 and Malone was grilling the Nuggets over effort after a 111-108 loss. Now that it’s 3-1, after two double-digit wins in Miami, it’s clear Nikola Jokic and Co., received the message."
                }
            }
        ]
    }
}`

### Expected behavior:

The message text should use the full width of the channel

### Actual behavior:

The message text has a fixed width

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- Operating System: N/A
- Deployment Method: k8s
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: N/A
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: Edge
- Operating System: Windows

### Additional context

![image](https://github.com/RocketChat/Rocket.Chat/assets/21992412/b8cbcaef-10b8-4d32-9c6d-f8666fdb3422)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

**Quick answer:** It's not possible, we don't have this option. If it's very necessary you can add a custom script or CSS to change this behavior for this case

Sorry, but GitHub is only for issues/bugs related to the repository project, closing it here.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by airedwin** [comment]
Thanks, but what is the purpose of having the fixed width? Is that documented anywhere?

**Comment by smuuf** [comment]
I think this _is_ a bug, because it is really not apparent why the limited width in this case should be considered a "feature".
