### ISSUE TITLE
Functions involving sending emails for verification/password reset not working

### ISSUE THREAD

**Issue by Rottenblasters** [RocketChat/Rocket.Chat#29561]
### Description:

All functions involving sending any type of emails of the `account-base` module are not working this includes `sendResetPasswordEmail`, `sendVerificationEmail` functions.

### Steps to reproduce:

1.  Go to login screen of Rocket.chat
2.  Click on "forgot password" link
3.  Enter your email and wait for sometime, you won't get any email
4. Similar error can be seen if verification email is sent. This can be reproduced if you have `Two Factor Authentication` enabled

### Expected behavior:

You should receive emails for password reset and account verification.

### Actual behavior:
**You don't receive any emails it is because of below errors**

This is for `sendResetPassword` function

![rocket chat_accounts-base_error](https://github.com/RocketChat/Rocket.Chat/assets/68077049/18486f1f-8ffb-44fd-999c-015d5aac181e)

This is for `sendVerificationEmail` function

![rocket chat_accounts-base_error_2](https://github.com/RocketChat/Rocket.Chat/assets/68077049/8f60f413-efc3-4312-bc6b-749650bacd44)

It seems both errors have a common message i.e. `"message": "Invalid URL: undefined"`

### Server Setup Information:

- Version of Rocket.Chat Server: `6.3.0-develop`
- Operating System: 
- Deployment Method:  `gitpod`
- Number of Running Instances: `1`
- DB Replicaset Oplog: 
- NodeJS Version: `v14.21.3`
- MongoDB Version: `6.0.3 / wiredTiger (oplog Enabled)`

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by AyushKaithwas** [comment]
Did you set up SMTP (Simple Mail Transfer Protocol) settings from the admin panel?
![image](https://github.com/RocketChat/Rocket.Chat/assets/86650576/5057d8b4-d9e0-488e-bb5c-76309c3da7f8)

**Comment by hugocostadev** [comment]
It's working on open.rocket.chat for me and in local environment... 

Just checked: 
![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/79c23565-0332-4fea-b460-d50a284e042e)

Are you receiving any other email? Check your SMTP settings

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
