### ISSUE TITLE
Rocket Chat Issue

### ISSUE THREAD

**Issue by Bakeacakeal** [RocketChat/Rocket.Chat#29573]
I went into the app and all I could see was a blank page.

**Comment by MaxAtoms** [comment]
Please read the guide before opening a new issue: https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat/ways-to-contribute/report-bugs.

Side-note: The account of OP was opened in January and the only public activity is this issue.
I guess we have a troll here...

**Comment by hugocostadev** [comment]
Please, follow the issue template. 

@MaxAtoms , thanks for checking 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
