### ISSUE TITLE
I have updated to version 6.2.6, but it is still 6.2.5 in Workspace.

### ISSUE THREAD

**Issue by ymch** [RocketChat/Rocket.Chat#29570]
Did you forget to modify `rocket.chat-6.2.6/bundle/programs/server/apps.js`?
![Screenshot 2023-06-17 at 04-56-55](https://github.com/RocketChat/Rocket.Chat/assets/2923124/41bddb7c-1e3d-43aa-b3fb-4897198c3c66)![スクリーンショット 2023-06-17 04 59 52](https://github.com/RocketChat/Rocket.Chat/assets/2923124/d5cc2453-7cab-4b3a-ace2-7deb162608ba)

**Comment by Gummikavalier** [comment]
I confirm that the RC 6.2.6 says 6.2.5 also in the admin info panel.

**Comment by Gummikavalier** [comment]
Fixed in https://github.com/RocketChat/Rocket.Chat/issues/29555
