### ISSUE TITLE
Ability to remove joined / left channel text

### ISSUE THREAD

**Issue by cedemore** [RocketChat/Rocket.Chat#2959]
I would love if you added an option in the administration panel where you can choose to display when a user joined/left a room. Atleast the users on my server find this distracting / unnecessary. 

I think this option would be great to have.

Thanks in advance /Cedemore

**Comment by Molle500** [comment]
+1

**Comment by lunitic** [comment]
Ugly solution:
Could it be possible to hide them via CSS.. 
I see they have a class..

class="message  system uj"
class="message  system ul"

**Comment by tmace85** [comment]
+1 ;) Would be a nice option. Its annoying if you have a lot of people in the room.

**Comment by Molle500** [comment]
Also shouldn't only be user joined/left. Should be optional to have all those kind of messages like user was promoted to owner/mod or channel name changed by Molle and so on... :)

**Comment by siomosp** [comment]
+1

**Comment by timkinnane** [comment]
Probably a solution based on hiding the messages is better than actually preventing them, since some bot interactions are triggered by these special events message types. e.g. Someone entering a room, bot might send a welcome message.

**Comment by rodrigok** [comment]
@timkinnane You are right, but we can filter messages to not send to client these type of messages, bots will keep listening on message insertion.

**Comment by lunitic** [comment]
@rodrigok been struggling whole night to try to disable the messages. No luck. My other solution in #3418 does not work anymore. Seems like there been code changes. Any suggestion how to hardcode patch away the user has joined messages. Brain feels like spaghetti carbonara now

**Comment by jkolhi** [comment]
@rodrigok Me and @lunitic have been struggling hard for many hours to figure out how it works - any pointers that can help us explain the flow? I have been searching in the source but not been able to see the flow. Any help very much appreciated!
