### ISSUE TITLE
UI: Option menu is not styled properly

### ISSUE THREAD

**Issue by anikdhabal** [RocketChat/Rocket.Chat#29609]
### Description:

Icon of "Show my Reminder" is not positioned in correct way and the icon of Google Drive is not visible inside options menu.
### Steps to reproduce:

1. Go to Options

### Expected behavior:

There should be a icon for google drive and the icon should place properly inside options.
### Actual behavior:

![Screenshot 2023-06-21 225508](https://github.com/RocketChat/Rocket.Chat/assets/81948346/bcf1f9cd-385c-4181-bff6-241cf9a9f1ad)

**Comment by abhishekcha790** [comment]
@anikdhabal i would like to work on this issue. please assign this to me.

**Comment by hugocostadev** [comment]
@abhishekcha790
No need to ask for permission to fix the issue, feel free to work on it! 
Just check if someone it's already raised a PR for that (should be linked in this issue).
Best of luck 🚀 👏 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by iampaandey** [comment]
I'm working on this issue as no PR has been raised for the same yet @hugocostadev

**Comment by iampaandey** [comment]
Can you please elaborate exactly where this issue is coming @hugocostadev @anikdhabal

**Comment by anikdhabal** [comment]
> Can you please elaborate exactly where this issue is coming @hugocostadev @anikdhabal

![Screenshot 2023-07-03 131716](https://github.com/RocketChat/Rocket.Chat/assets/81948346/8302834f-8f64-43eb-9bb5-e52a46774a80)

**Comment by iampaandey** [comment]
ohkay I'm working on the issue soon it will be resolved.

**Comment by auspy** [comment]
hi. I've carefully reviewed the issue description. It's a problem where my skillset can come to use. If you're still actively working on this issue, I'd love to collaborate with you. Two heads are better than one, and together, we might find a resolution faster.
However, if you're unable to continue with the work, I would like to request permission to take over the issue. I'll make sure to acknowledge your initial efforts and provide updates throughout the process.
Thank you for your time and consideration.

**Comment by Dnouv** [comment]
Thank you so much for reporting this issue, and I really appreciate all of your interest in taking this on. But the problem no longer exists.

Here is a recent screenshot:
![image](https://github.com/RocketChat/Rocket.Chat/assets/61188295/cd0380b1-7f14-4848-82c8-79d58d34053a)

Please feel free to open the issue in case you have any new concerns.
