### ISSUE TITLE
6.2.7: Emoji not displayed on search

### ISSUE THREAD

**Issue by DClabaut** [RocketChat/Rocket.Chat#29604]
### Description:

When searching for emoji, the actual emoji are not displayed. Adding them works though.

### Steps to reproduce:

- In a chat, click the `Emoji` button
- Search for an emoji, e.g. type `cat` in the search bar
- The search returns a series of black tiles
- Hovering the tiles shows the emoji further down, left of the "Skin tone" text

### Expected behavior:

- Emojis are supposed to be displayed in search results

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/965290/63218b51-b110-4e4b-90f7-3c3de3ad7d88

### Server Setup Information:

- Version of Rocket.Chat Server:  Downloaded `https://releases.rocket.chat/6.2.7/download`, server shows `Rocket.Chat Version: 6.3.0-develop` upon start
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.18

### Client Setup Information

- Desktop App or Browser Version: Reproduced in Firefox Private Mode and Chromium
- Operating System: Ubuntu 22.04

### Additional context

Updated to 6.2.5 with Node 14.0.0, ran into [this issue](https://github.com/RocketChat/Rocket.Chat/issues/24679)), updated again to 6.2.7 with node 14.14.0, where the emoji issue was first detected.

**Comment by TimmiORG** [comment]
@sampaiodiego 
Are you able to comment how to get back to the 6.2.x branch. The faulty 6.2.7 release updated the DB to a newer schema?
Any chance to go back or do we have to wait until there will be 6.3.0 release?

**Comment by sampaiodiego** [comment]
I'm really sorry about that.. 

to revert the database migration and then be able to either downgrade to `6.2.6` or upgrade to `6.2.8` you need to update the migration record on the the base.. you can do it running this command on your MongoDB:

```
use rocketchat; // make sure to be on the correct database
db.migrations.updateOne({ _id: 'control' }, { $set: { version: 294, locked: false } });
```

**Comment by sampaiodiego** [comment]
this issue itself, will be fixed by https://github.com/RocketChat/Rocket.Chat/pull/29603

**Comment by TimmiORG** [comment]
> 

Hi @sampaiodiego 
thank you for the quick feedback. I manage to get my system to 6.2.8 again.
I hope this does not generate any trouble while going to 6.3.0 in future.

**Comment by sampaiodiego** [comment]
thx for confirmation @TimmiORG .. from what I've seen it will not cause any issues updating to 6.3.0 .. but I'll double check that.. 👍

**Comment by DClabaut** [comment]
Hello @sampaiodiego , I tried to run the update this way:

```
$ mongo
MongoDB shell version v5.0.18

rs01:PRIMARY> use local;
switched to db local

rs01:PRIMARY> db.migrations.updateOne({ _id: 'control' }, { $set: { version: 294, locked: false } });
{ "acknowledged" : true, "matchedCount" : 0, "modifiedCount" : 0 }
```

```
$ sudo systemctl stop rocketchat && sudo rm -rf /opt/Rocket.Chat && sudo n install 14.21.3 && curl -L https://releases.rocket.chat/6.2.8/download -o /tmp/rocket.chat.tgz && tar -xzf /tmp/rocket.chat.tgz -C /tmp && cd /tmp/bundle/programs/server && npm install && sudo mv /tmp/bundle /opt/Rocket.Chat && sudo chown -R rocketchat:rocketchat /opt/Rocket.Chat && sudo systemctl start rocketchat
```

Starting the server fails regardless on the version specified (tried 6.2.8, 6.2.6, 6.2.5 and 6.2.4) with this error:
```
Jun 21 15:20:41 chat rocketchat[7343]: /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
Jun 21 15:20:41 chat rocketchat[7343]:       throw error;
Jun 21 15:20:41 chat rocketchat[7343]:       ^
Jun 21 15:20:41 chat rocketchat[7343]: Error: Can't find migration version 299
Jun 21 15:20:41 chat rocketchat[7343]:     at server/lib/migrations.ts:249:9
Jun 21 15:20:41 chat rocketchat[7343]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by sampaiodiego** [comment]
@DClabaut you're using the wrong database name.. `local` is not the correct database..

look at your `MONGO_URL` environment variable, you'll find the correct database name there, something like:

`MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs0`

in this case `rocketchat` is the database name.

**Comment by DClabaut** [comment]
Thank you, it works.

My systemd configuration was strange. It's unclear to me how it worked (it has worked like this for years)

```
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat
Environment=MONGO_OPLOG_URL=mongodb://localhost:27017/local?replSet=rs01
```

I set both to `rocketchat` and could run the update to 2.6.8.

The emojis now load when searched, so I will close this issue. Thank you for your time.

**Comment by sampaiodiego** [comment]
oh, `MONGO_OPLOG_URL` should be pointing to `local`, that's correct.. 

the explanation is `MONGO_OPLOG_URL` is used to read MongoDB's oplog, which is read from the `local` database.. so you should revert that one to `local`.. it didn't cause issues to you because by default rocket.chat does not use oplog anymore.. but if it needs to switch to oplog for any reason, you better have this env var correctly set.

but Rocket.Chat data is stored in the database from the `MONGO_URL` env var.. so for this one you should keep `rocketchat` as the database name.

I hope that makes sense.. =)
