### ISSUE TITLE
Retention Policy

### ISSUE THREAD

**Issue by CAberry** [RocketChat/Rocket.Chat#29619]
### Description:

The retention policy does not show the right amount of days / years in channels

### Steps to reproduce:

1. Settings -> Retention Policy -> Enable
![image](https://github.com/RocketChat/Rocket.Chat/assets/35067345/6b9bf0c3-a7df-4b6b-9521-9d9363642de2)

2. Here we choose 730 days (approx 2 years)
![image](https://github.com/RocketChat/Rocket.Chat/assets/35067345/d9ec2fcc-2155-4bbc-9e67-f52adfc7da4d)

3. Go to any channel and click on the "room information"
![image](https://github.com/RocketChat/Rocket.Chat/assets/35067345/0e03f0e7-bde4-456c-a0f5-2e83568bc0c7)

### Expected behavior:

Should be printed 2 yeas or 730 days

### Actual behavior:

For 730 days in settings, it shows "172 685 271 years"

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.5
- Operating System: Debian 11 bullseye
- Deployment Method: tarball
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.18

### Additional context

Cronjob settings set to every minute but nothing happens

![image](https://github.com/RocketChat/Rocket.Chat/assets/35067345/a115fc58-0073-4bb2-a159-083e84d44140)

**Comment by Gummikavalier** [comment]
We are having this bug too.
