### ISSUE TITLE
About App Update

### ISSUE THREAD

**Issue by taux06s** [RocketChat/Rocket.Chat#29617]
I am using the windows desktop app for Rocket chat. However, from the update notification, I get a notification that it has been downloaded and when I install it, it fails to install. What is the problem with this?

**Comment by kertiskz** [comment]
I saw a comment somewhere that this problem was fixed in version 3.9.5. You can install it by downloading it from the  [official website](https://www.rocket.chat/install#Apps)

**Comment by taux06s** [comment]
Thank you very much. We will install 3.9.5 as soon as possible.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

But @kertiskz is correct! :D 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
