### ISSUE TITLE
Custom script not working: Template.thread.onCreated() =>  Cannot read properties of undefined (reading 'onCreated')

### ISSUE THREAD

**Issue by maluhub** [RocketChat/Rocket.Chat#29621]
### Description:

This happens after upgrade from 5.4.10 to 6.2.8:
in custom script `Template.thread.onCreated()` leads to  `Cannot read properties of undefined (reading 'onCreated')`
which caues custom script not working.

### Steps to reproduce:

1. Go to “Layout > Custom Scripts > Custom Script for Logged In Users”
2. Insert this script:
```
Template.thread.onCreated(() => {
const instance = Template.instance();
instance.state.set('sendToChannel', false);
}); 
```
3. Start *new* thread in any conversation.

### Expected behavior:

`Also send to channel` should be DISABLED by default.

### Actual behavior:

`Also send to channel` is ENABLED by default.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.8
- Operating System: Ubuntu 22.04 LTS
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: On
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.9.5
- Operating System: Windows 11 

### Relevant logs:

Chrome log:
```log
scripts.js?e6abebedb6e181f9b07eeec8043560e484267fef:20 Uncaught TypeError: Cannot read properties of undefined (reading 'onCreated')
```

**Comment by hugocostadev** [comment]
The Meteor template references do not work anymore, we are removed that.
You need to create another script to fit reach your goal...

Something that disable the check, like that: 

```js
document.querySelector('[name=alsoSendThreadToChannel]').checked = false
```

**Comment by onegin** [comment]
Rocket.Chat 
Server - 6.3.6
Client 3.9.7 ( Mac) 
Not working :(
