### ISSUE TITLE
Run linux command on remote server by slash command

### ISSUE THREAD

**Issue by DFazeli** [RocketChat/Rocket.Chat#29630]
Hi.
I want to create a user on a remote Linux server by using the `slash command`
for example:

`/createuser USERNAME`

then USRNAME created on my Linux server (or any other command)
I use Rocketchat `version 6.2.0`
I can’t find `the slash command` in the admin panel

Please guide me fully
thank you.

**Comment by hugocostadev** [comment]
Hi @DFazeli sorry for the late reply...  thanks for raising the question! 🚀 💯 

We don't have this slash command... 
You can accomplish that by creating an app that registers this slash command and does the necessary API request to add the user.

Docs: https://developer.rocket.chat/apps-engine/building-custom-apps/sample-app-snippets/sub-command-pattern

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
