### ISSUE TITLE
Can't use search function when using "share message"

### ISSUE THREAD

**Issue by Snyaify** [RocketChat/Rocket.Chat#29632]
### Description:

Can't share message with person (can't use search user function when sharing message)

### Steps to reproduce:

1. Select the message to be shared
2. Press the "Share Message" button
3. In the window that appears, I write the name of the person who needs to send the message

### Expected behavior:

In the "Share message" window that appears, I write the name of the person whom I want to send the message, I get the result "Empty", but at the same time I can select this person from the drop-down list

### Actual behavior:

A search should work for a person who needs to send a message through a form
Here is a video of actual behavior: https://clouds.be4free.ru/s/NqdBqc78KG2bLGC

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.8
- Operating System: Debian 11
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.18 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop app v 3.9.5
- Operating System: Windows 11

**Comment by Rottenblasters** [comment]
This issue seems to an extension of issue #29328
