### ISSUE TITLE
High Availability Documentation

### ISSUE THREAD

**Issue by dupree972** [RocketChat/Rocket.Chat#2964]
Your Rocket.Chat version: .027

I would like to setup Rocket.Chat in a HA fashion. Is this possible and are their any documentation or guidance for doing so..
Thanks...

**Comment by delize** [comment]
I too would like to see if this is possible. We are looking for an alternative to Hipchat, and Rocket.Chat looks to be what we want, but HA is one of our requirements.

**Comment by simonclausen** [comment]
Some discussion and info about this in #520 and #1867.

**Comment by engelgabriel** [comment]
Hi, please follow https://github.com/RocketChat/Rocket.Chat.Docs/issues/68
