### ISSUE TITLE
Cron workflow to run on only the main repo and not on forked.

### ISSUE THREAD

**Issue by chinma-yyy** [RocketChat/Rocket.Chat#29667]
### Description:

The Cron workflow should only run on the main Rocket chat Repository and not on the forked repository leading to unnecessary use of resources and spam notifications.

### Steps to reproduce:

1. Fork the repository
2. 
3. 

### Expected behavior:

Only run the workflow on the main repo
### Actual behavior:

Runs on all forked repository
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the concern! 🚀 💯 

The workflows / Github Actions can be disabled manually in your fork... for me it starts as disabled and If I want I need to enable them, but if the workflows are enabled, just disable them manually

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
