### ISSUE TITLE
Request: Disable Marketplace for Users

### ISSUE THREAD

**Issue by seraphyn** [RocketChat/Rocket.Chat#29664]
It would be wonderful if it is possible to make the marketplace for apps invisible to users. 
Sometimes the requests for an instance with over 200 users almost turn into spam.

And we don't want to fuel unnecessary covetousness and spend time explaining things over and over again.

I hope the request will find friends

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the request! 🚀 💯 

You can disable access to Marketplace through the `Permissions` admin ... 
Just remove the Role `User` from the `access-marketplace` (Access Marketplace) permission 

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/fe32795c-aff3-4f38-a79d-3609bf83b692)

Sorry, but GitHub is only for issues/bugs related to the repository project, closing here

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by serviceman** [comment]
This option is no longer available in 6.9.2, unless it moved.
