### ISSUE TITLE
Upgrade to 6.2.8 sometime will show application error.

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#29661]
### Description:

Hello,
I has upgrade to 6.2.8 with snap.Some user has show application error.

### Steps to reproduce:

1. Click any room or direct message
2. Maybe will show application error

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.8
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: 3.9.5
- Operating System: Windows 11

**Comment by hugocostadev** [comment]
Hi there, can you share more details? Any console error? 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by akong77** [comment]
OK,I will try find some detail error.Please wait.
