### ISSUE TITLE
emoji's not showing after upgrade to 0.27

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat#2966]
Your Rocket.Chat version: 0.27.0

After the upgrade from 0.26 to 0.27 emojis are not displayed anymore 

![image](https://cloud.githubusercontent.com/assets/316284/14678984/47566c1c-0718-11e6-88c6-d2606b820bd1.png)

Looking at the HTML source its there.
 ```
<span class="emojione emojione-1f606" title=":laughing:">😆</span>
```
however is not visible on either chrome, or the electron client

**Comment by giray** [comment]
Fixed in 0.28.0

**Comment by flypenguin** [comment]
btw - is there any point where you blog / publish / tweet / etc. information about new releases? :)

**Comment by Sing-Li** [comment]
https://github.com/RocketChat/Rocket.Chat/releases

**Comment by flypenguin** [comment]
that's too easy (read: could have thought of that myself ;) . thanks!
