### ISSUE TITLE
webrtc screensharing / video not fullscreen

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat#2967]
Your Rocket.Chat version: 0.27

During video chat and most noticeably when sharing screens, when going "full-screen" the video stream does not scale to fullscreen, but has lots of black area.

While acceptable during video conferencing, is quite annoying when sharing a screen / presentation.

![image](https://cloud.githubusercontent.com/assets/316284/14679155/fa5d3ea8-0718-11e6-8e28-ec86b61bd574.png)

**Comment by MartinSchoeler** [comment]
Hey @giray , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
