### ISSUE TITLE
send listener chat user info in outgoing integration

### ISSUE THREAD

**Issue by sjad5241** [RocketChat/Rocket.Chat#29699]
hi i have a problem in outgoing rocketchat integration

in data passed request i just have username of user that sent message

but i need username of user that recived message how can i change data pass to have username of user that recived message in request body

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

We need more info, follow the template of the issue, please...  add more info and reopen this issue. Thanks

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
