### ISSUE TITLE
Missing CSRF Protection Middleware in Server Configuration

### ISSUE THREAD

**Issue by Onyx2406** [RocketChat/Rocket.Chat#29693]
### Description:

The application server currently lacks Cross-Site Request Forgery (CSRF) protections which could potentially allow for unwanted state-changing requests to be submitted on behalf of a user who visits a malicious website.

### Steps to reproduce:

- Deploy and run the server.
- Monitor network traffic during state-changing operations.
- Notice absence of CSRF tokens in requests.

### Expected behavior:

A CSRF token should be generated and validated for each session to prevent potential CSRF attacks.

### Actual behavior:

There are currently no CSRF protections in place, leaving the application vulnerable to potential CSRF attacks.

### Additional context

The csurf middleware could be used to add CSRF protection to the application.

**Comment by xxxmadxxx** [comment]
Hi @Onyx2406,

Please open this issue inside our HackerOne program: https://hackerone.com/rocket_chat so the security team can appropriately triage it. Thank you.
