### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AzycrayUno** [RocketChat/Rocket.Chat#29700]
I am literally logged in on my old computer and when I try to log in with the same user name and password on the new computer it doesn't recognize me. It also does not recognize the URL from the Seeking Alpha chat room I use. I am also using the online version with my correct email address showing so I tried to get a change password link and it never showed up. 
My email is vajaensch@gmail.com
My user name is Azycray 
To get help with Rocket Chat I had to open a new account because I couldn't log in with my saved info for github
So, I need help but can't say where the biggest problem is.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

We need more details, are you using SaaS, or self-hosted, we need the version and etc...  Maybe try to contact our support team directly in the website rocket.chat 

Sorry, but GitHub is only for issues/bugs related to the repository project, closing here... 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
