### ISSUE TITLE
Feature: Status Message 

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat#2971]
Your Rocket.Chat version: 0.27

Would be nice to have a User Status Message, such as "at office", "at home", "call met at xyz'.
Hovering over user avatar would show the status message, as well as clicking on the user...

**Comment by sadeva** [comment]
+1 for this.

**Comment by engelgabriel** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2422
