### ISSUE TITLE
Question: Is there some way to have badges next to a user name?

### ISSUE THREAD

**Issue by Loki-Afro** [RocketChat/Rocket.Chat#29716]
Not a Bug but a Question :)

Question: Is there some way to have badges next to a user name?

Some Context:

we want to introduce some "gamification" into rocketchat where badges are some kind of incentive to do certain task.
maybe badges should be earn able multiple times - not sure.

It should be visible in a similar way as `Admin` is displayed next to a username

Is there any feature that would bring us closer to what i had in mind?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Badges only appear to display the role of a User if desired... You can play around with roles and hide the ones that you don't want with custom CSS/Javascript

Sorry, but GitHub is only for issues/bugs related to the repository project, closing here...

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
