### ISSUE TITLE
Ability to control user badges 

### ISSUE THREAD

**Issue by hlgr360** [RocketChat/Rocket.Chat#2972]
Version 0.27.0

The latest version added user badges which a lot of my team find cluttering and distracting. Is there a way to disable those. Why would I care if someone is an User or an Admin in a chat. My folks suggested location badges instead .. but short of that I prefer to be able to disable them all together.

**Comment by lvh1** [comment]
You can either:
* Remove the 'description' of all permission groups under /admin/permissions
* add this custom css to /admin/Layout -> custom css `.message .info .role-tag{	display:none!important;}`

to achieve that

**Comment by hlgr360** [comment]
Perfect. Thank you. Do you want me to close this issue to keep it open to track an permissions toggle.

**Comment by lvh1** [comment]
You can close it since there's another issue about this already
https://github.com/RocketChat/Rocket.Chat/issues/2950
