### ISSUE TITLE
docker deployment test

### ISSUE THREAD

**Issue by BlackBatM4n** [RocketChat/Rocket.Chat#29737]
hi, am trying to deploy a test environment on docker but i can't, i am used to 1 docker compose file and when i try this command it also doesn't work "docker-compose -f docker-compose-local.yml -f docker-compose-ci.yml up -d" the output is this "Service account-service has neither an image nor a build context specified. At least one must be provided.", if someone can help me with a guide for docker deployment it would be great thanks!!

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

Check out our docs:
https://docs.rocket.chat/deploy/prepare-for-your-deployment/rapid-deployment-methods/docker-and-docker-compose

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
