### ISSUE TITLE
Add custom emoji failed in FileSystem storage

### ISSUE THREAD

**Issue by dejiar** [RocketChat/Rocket.Chat#29738]
### Description:

Trying to add new custom emoji in RocketChat running 6.2.8. After selecting the file and click upload, Rocketchat does not give any response and after awhile, i got ENOENT error. I tried to manually copy the file to Rocketchat server and reload the emoji page, and it show up.

### Steps to reproduce:

1. Add a new emoji. Storage type must be running on FileSystem
2. Click upload after selecting the png/gif file

### Expected behavior:

The emoji added without any error.

### Actual behavior:

The emoji add failed. And show ENOENT error. It was working before 6.2 upgrade.

### Server Setup Information:

- Version of Rocket.Chat Server:  Running in kubernetes and file system backed by PVC
- Operating System: 
- Deployment Method: helm chart/kubernetes
- Number of Running Instances: 1
- DB Replicaset Oplog: 3
- NodeJS Version: 
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows/Linux

**Comment by hugocostadev** [comment]
Hi @dejiar , I could not reproduce here... Any other logs? 

Can you upload other images with your filesystem? 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by dejiar** [comment]
![image](https://github.com/RocketChat/Rocket.Chat/assets/5075502/f732afad-3c1f-466a-918b-7549d8fcbd62)
This is error when i try to add emoji.

Uploading new image in avatar have no issue.

RC version is latest 6.2.9

**Comment by hugocostadev** [comment]
I got it to reproduce here. 

### Steps to Reproduce
1. Go to rocket.chat client 
2. Go to Workspace > Settings > Custom Emoji FileSystem
3. Change to something like: 
![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/9f573df5-2f09-46a5-a024-910fd3bf28e1)
4. Restart your server 
5. Try to add a new custom emoji In Workspace > Custom Emoji 
6. Notice that no error popups and in the terminal the contributor error appears 

**NOTEs:**  
- I tried to change the folder permission with `sudo chmod 777 emoji-fs/` but did not work
- No error appears on the front end
- The record is created anyway without the uploaded image
- The directory is only created after restart the server
