### ISSUE TITLE
Overwriting Push notifications delay using ENV VARs does nothing

### ISSUE THREAD

**Issue by IvanGrishchenko** [RocketChat/Rocket.Chat#29747]
### Description:
I'm running Rocket.Chat on docker and using Rocket.Chat gateway for receiving push notifications.
But there is an issue with mobile push notifications if there is an active PC session. The standard 120-second delay isn't affected by OVERWRITE_SETTING_NOTIFICATIONS_SCHEDULE_DELAY_ONLINE. However if Rocket.Chat is closed on PC then I receive push notifications instantly. I have also tried to introduce this in .env and docker-compose.yml.save just to be sure. None of the above changes the hardcoded 120-second delay

### Environment Information:

- Rocket.Chat Server Version: 6.2.9
- Rocket.Chat App Version: 1.39.1
- Device Name: 
- OS Version:  Ubuntu 22.04 LTS

### Steps to reproduce:

1. Introduce "OVERWRITE_SETTING_NOTIFICATIONS_SCHEDULE_DELAY_ONLINE xx" to docker-compose.yml 

### Expected behavior:

The delay should be the xx value that the user sets

### Actual behavior:

The delay is 120-seconds no matter what xx is

### Additional context:

![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/44530332/f1447a14-854c-4e64-b266-66a14b5a1368)

**Comment by hugocostadev** [comment]
Closing this issue, duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/29742
If you still want to continue the discussion for any reason, continue in the mentioned or reopen this issue if you think that it's not related. Thanks 🚀 💯 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
