### ISSUE TITLE
Left menu, links are broken and lead to a 404 error in 6.2.9 in sub directory install.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#29767]
### Description:
Left menu, when selecting rooms, or direct messages is broken when in a sub directory. For example, if an install is located at domain.com/subdirectory and you try to navigate to a room that would be at domain.com/subdirectory/channel/roomname the link points to domain.com/channel/roomname, removing the "subdirectory" name from the URL.

### Steps to reproduce:

1. attempt to navigate to a room from the left side menu
2. Link will be broken as the subdirectory install is removed from the URL.

### Expected behavior:

For navigation to work as expected

### Actual behavior:

Navigation link leads to a 404 link.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.9
- Operating System: Centos 7
- Deployment Method: tar
- Number of Running Instances: 6
- DB Replicaset Oplog:  yes
- NodeJS Version: 4.21.3
- MongoDB Version: 4.4

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows

**Comment by sandeep13122002** [comment]
can you assign this issue to me ?

**Comment by serviceman** [comment]
flowRouter.go also isn't triggering, it is reloading the page completely because the event is passive instead of non passive.

**Comment by serviceman** [comment]
I created a hack that you can put under "custom scripts for logged in users". I wish I could do something direct in the code. There may be bugs but from my initial testing everything seems to work as intended.
```
$(document.body).unbind("click touchstart").on('click touchstart', '.rcx-sidebar-item--clickable' ,function(event){
var URL = $(this).attr("href");
   if(URL.startsWith('/channel/') || URL.startsWith('/direct/')){
            var newUrl = $(this).attr("href"); // Sets the new url as the URL that is in the browser.

            $(this).attr("href", "javascript:;"); // Set herf value to NULL so there is no redirect

     		$( "div.rcx-box--full" ).removeClass( "opened" ); // Removes the opened class from the menu

// Must wait a few milliseconds so the new URL will register as blank so there is no redirect.
  setTimeout(
  function() 
  {
        $("a[href*='javascript:;']").attr("href", newUrl); // Changes the URL back to the actual URL to keep menu links correct.
        FlowRouter.go(URL); // Change the user to the channel/ direct message.
          
  }, 250);  

    
	}
});
```

**Comment by hugocostadev** [comment]
Hi @serviceman 

NOTE: Running in a subfolder has been officially deprecated. It will no longer be supported in the upcoming 4.0 release. See our [April 2020 announcement](https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371)

If you want to run your server in a subfolder like https://your.domain.com/chat/ you have to set up a reverse proxy. See [Run Rocket.Chat behind a SSL Reverse Proxy](https://github.com/deploy/rocket.chat-environment-configuration/configuring-ssl-reverse-proxy)

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
