### ISSUE TITLE
OpenGraph, Twitter Card

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#2976]
I really think that is time to implement this basic feature of every app and website.

When I share my chat on social, only url is correct. The title is wrong (Rocket.Chat), description is missing, thumbnail/image is missing.

Check it out:

 ![](http://content.screencast.com/users/shtefcs/folders/Jing/media/38d4139d-f344-4574-9b87-b82ac1cee3b8/2016-04-21_0708.png)

What you think @engelgabriel  ? I think this is easy implementation and if you need any help me and @jelenajjo can help you. We will just need guide or setup from your side, how to pull data automatically from Chat Settings.

Peace

**Comment by marceloschmidt** [comment]
Hi @shtefcs is this something you'd be willing to make a PR? I think everyone could benefit from it, if we have a simple way of setting it up... Thanks.

**Comment by Syirrus** [comment]
Being able to read the contents of a channel without logging in would be awesome indeed.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
