### ISSUE TITLE
Fail to setup SMTP & Email

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#2977]
Your Rocket.Chat version: (make sure you are running the latest)  **0.26.0**

I  have this problem for long time. I can't make emails work at all.  Tested many SMTP settings, but didn't manage to do it.

Even users fail to register via email and password form. It's say "Please wait".
In admin, the user is registered, but he don't get username created, check screenshot below:

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/fd9e6656-9f9d-4f0d-a394-8f3fbe2869eb/2016-04-16_1613.png)

Here is the log for the failed registration:

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/8aa79de5-3293-4c60-8504-f6b4ca775f14/2016-04-16_1616.png)

## SMTP Test log

```
Exception while invoking method 'sendSMTPTestEmail' Error: connect ETIMEDOUT     at Object.Future.wait (/home/Rocket.Chat/bundle/programs/server/node_modules/fibers/future.js:398:15)     at smtpSend (packages/email/email.js:86:1)     at Object.Email.send (packages/email/email.js:185:1)     at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:12:9)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     - - - - -     at errnoException (net.js:905:11)     at Object.afterConnect [as oncomplete] (net.js:896:19) 
```

**Comment by sadeva** [comment]
Hi @shtefcs,

I got the same issue too, and after a few days, I got the solution. It's caused by the SMTP port is being blocked by the server/provider. If you're on DigitalOcean, try changing the port to 2525.

Hope that helps.

**Comment by shtefcs** [comment]
@sadeva 

Tnx for replay mate.

Yes I am on Digital Ocean, and my port of server is not default one, its changed to 7532.

Do you think that part should work ?

**Comment by sadeva** [comment]
I don't know mate. Check it from your console (SSH) using telnet.

**Comment by shtefcs** [comment]
As @sadeva  said, it was blocked port on Digital Ocean.

Thank you mate for pointing me out.

I will close this issue now.
