### ISSUE TITLE
[feature] Bind the "@" symbol (mention list) on F2 key

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2978]
Your Rocket.Chat version: 0.27

In some local keyboard layouts the "@" symbol does not exist, so I need to switch to international layout, press the "@" and switch back to post the message. This is very disappointed, so I would ask to bind mention list on nearest key - F2 also

**Comment by geekgonecrazy** [comment]
So you'd like to tag/mention someone without having to type @?  Would some graphical way of mentioning help as well?

**Comment by zxweed** [comment]
No, I just want to access mentions menu by pressing F2, the same way as pressing "@". Or (yet another and better way) I want to put mention reference by mouseclick on the nickname instead on calling user menu.

The key point - I need to type mentions faster, now there are too many clicks (with double switch keyboard layout) to accomplish it.

**Comment by engelgabriel** [comment]
Just out of curiosity @zxweed , how do you guys send emails?

**Comment by zxweed** [comment]
@engelgabriel, we are using "ReplyTo" button or Address Book with name search, the direct input of email is very rare operation

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
