### ISSUE TITLE
context-sensitive username autocompletion

### ISSUE THREAD

**Issue by fascinatedcow** [RocketChat/Rocket.Chat#2979]
Your Rocket.Chat version: 0.27.0

If I am in a channel and there is one person whose name starts with a "j", I would expect to be able to type "j" followed by <tab> and to have the person tagged. Instead it autocompletes the alphabetical first (I think) user beginning with "j", even though that user is not in my channel.

**Comment by rodrigok** [comment]
@fascinatedcow can you post a video explaining your problem? Maybe the problem is because we are matching the text with the entire username and not with the begining of the username?

**Comment by KevinMGranger** [comment]
@rodrigok If I understand correctly, the problem isn't that the match seems inaccurate-- it's that you're more likely to tag people that are in the channel than those who aren't in the channel.

People in the channel should have a higher priority in the suggestions list.

**Comment by rodrigok** [comment]
@KevinMGranger Yes, and they have 😄  the code lists users in order of recent messages in channel (it's a local and very quick search) than add more results from room's users list (local too and will be removed in the future) and then get more data from server to complete the list.

So, if you type `:` you should see the user from the latest message as your first option.

**Comment by KevinMGranger** [comment]
Hmm. I'm noticing this behavior now, but I swear that wasn't the case before. Was this a recent change?

**Comment by rodrigok** [comment]
@KevinMGranger 1 or 2 months ago.

**Comment by MartinSchoeler** [comment]
Feature already added.
