### ISSUE TITLE
Allow a user to change password

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#298]

**Comment by strk** [comment]
I cannot find the password change link, where is it ?

**Comment by marceloschmidt** [comment]
It's under My Account / Profile.

![image](https://cloud.githubusercontent.com/assets/1986378/18207147/40f466f6-7100-11e6-9485-9ea17698fb97.png)

**Comment by strk** [comment]
Thanks !
May I suggest to request entering the new password twice ?
