### ISSUE TITLE
"Error Oops Something Went Wrong" after a while in the chat window

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat#29808]
### Description:

Sometimes after a while, an error "Error Oops Something Went Wrong"  appears in the chat window.

### Steps to reproduce:

1. Open rocketchat in a browser
2. Wait a while.
3. This error may appear

### Expected behavior:

List of messages in the chat window

### Actual behavior:

error "Error Oops Something Went Wrong"

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.8
- Operating System: Oracle EL 7
- Deployment Method: docker (3 monolith Rocket.chat containers + 1 NATS container, Enterprise plan)
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 114
- Operating System: Windows 10

### Additional context

There are no breaks in the network, the server and client are on the same network. This was not the case in previous versions.

![error](https://github.com/RocketChat/Rocket.Chat/assets/666827/8552a7d4-cbe0-49a8-b5ea-0f8ee9707a35)

### Relevant logs:
There is nothing in the rocket chat container logs.

Chrome console:
orEachCallback @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
socket.onmessage @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
r.dispatchEvent @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
k._dispatchMessage @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
k._didMessage @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
o.ws.onmessage @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380     GET https://rcdev.bcs.ru/sockjs/info?cb=jo77gg1bmm net::ERR_ADDRESS_UNREACHABLE
_start @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
(anonymous) @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
setTimeout (async)
n.delay @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
n.XHRLocalObject @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
doXhr @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380
(anonymous) @ adbe793e41282308cffbfe2690d36f051a7ffdf4.js?meteor_js_resource=true:1380

**Comment by hugocostadev** [comment]
Hi there, thanks for your contribution... 

Can you check again in the last `develop` branch? I could not reproduce here...  Is still happening? Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by shiryov** [comment]
Hi!
After a while, this problem went away. And it doesn't happen again.
We assume that this was due to the work on our VMI in those days.
