### ISSUE TITLE
Custom Fields not displayed on registration page

### ISSUE THREAD

**Issue by tmkis2** [RocketChat/Rocket.Chat#29802]
### Description:

Custom Fields not visible on web registration page

### Steps to reproduce:

1. Install the latest rocket chat Server Version
2. Add custom fields (required)
3. visit the user registration page

### Expected behavior:

Custom fields to be displayed on the registration page 

### Actual behavior:

even set to required they don't appear. They ARE visible however if you use the mobile app on ios and register an account there.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.9
- Operating System: Debian 11
- Deployment Method: docker
- Number of Running Instances: 4
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.18

### Client Setup Information

- Desktop App or Browser Version: Safari or Chrome
- Operating System: Mac OS X

**Comment by hugocostadev** [comment]
It was implemented in this PR https://github.com/RocketChat/Rocket.Chat/pull/29202 and it's going to be released in the next release (6.3.x) 

Thanks for raising the issue

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
