### ISSUE TITLE
username autocomplete next guess

### ISSUE THREAD

**Issue by fascinatedcow** [RocketChat/Rocket.Chat#2980]
Your Rocket.Chat version: 0.27.0

When using <tab> to autocomplete a user, I would expect that after the first guess, I could press <tab> again to choose the next matching user. This doesn't happen. Instead you have to delete the whole user and try again. When you have a lot of users, you basically have to type out the entire username in order to tag them.

This is related to #2979.

**Comment by geekgonecrazy** [comment]
@fascinatedcow you can use the arrows when that autocomplete pops up to choose which one you want.  

So you're saying if I tab complete @fascinatedcow but I wanted the next one down I'd hit tab again and it'd cycle through them?

**Comment by marceloschmidt** [comment]
Is this issue still tracking anything?

**Comment by geekgonecrazy** [comment]
@marceloschmidt I believe the ask here is: tab once autocompletes.  But then hitting tab again would goto the next best match.

So you type: `@gee`
and you get:
* `@geekology`
* `@geekgonecrazy`

You hit tab once it auto completes to `@geekology`.  Which is incorrect, so he wants to be able to hit tab once again and it change from `@geekology` to the next one in the list which is `@geekgonecrazy`

I think this could be a great addition.

**Comment by marceloschmidt** [comment]
Ahhh yes!! Definitely something worth doing!!

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
