### ISSUE TITLE
File cannot be uploaded again after cancellation

### ISSUE THREAD

**Issue by tzengshinfu** [RocketChat/Rocket.Chat#29810]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10 22H2

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.9.5

### Rocket.Chat Server Version

6.2.9

### Describe the bug

There is no response when trying to re-upload after canceling the file upload, until canceling another file upload to enable re-upload.

### How to Reproduce

1.Select file A.
2.Cancel the upload of file A.
3.Select file A again.
4.No response.
5.Select file B.
6.Cancel the upload of file B.
7.Select file A again.
8.The file A upload interface reappears normally.
![error](https://github.com/RocketChat/Rocket.Chat.Electron/assets/2170033/8e35f6f2-3251-477b-9463-3ec292f7eb90)

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by Sayan4444** [comment]
I have failed to replicate this issue....can u please check if this issue still persists?

**Comment by tzengshinfu** [comment]
> I have failed to replicate this issue....can u please check if this issue still persists?

Hello [Sayan4444](https://github.com/Sayan4444):

After some time, we have upgraded our Rocket.Chat Desktop App Version to 3.9.11 and Server Version to 6.5.0.
The issue has now been resolved. I will close this issue.

Thank you for your concern.😊
