### ISSUE TITLE
Add "ReplyTo" button to the local message menu

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#2981]
Your Rocket.Chat version: 0.29

Now there are many unnecessary clicks needs to quote post and reply message.

**Comment by bott0r** [comment]
I think that would be a great idea, i am also wondering if there is an interest in threaded comments??

![untitled-1](https://cloud.githubusercontent.com/assets/17119942/14708599/3919c9aa-07cc-11e6-8e75-0aa6bdde19d0.png)

**Comment by zxweed** [comment]
The "Quote" button has been added
