### ISSUE TITLE
Why can’t I delete my cloud account without opening another account in your support system?

### ISSUE THREAD

**Issue by andryyy** [RocketChat/Rocket.Chat#29828]
I don’t know where I could place this. But there is simply no way for me to delete my account on your cloud platform without creating another account. 😄

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Could you elaborate more on your question? If you want to delete your account to our cloud service,  send the request to support@rocket.chat please

Sorry, but GitHub is only for issues/bugs related to the repository project, closing here

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by AdityaMayukhSom** [comment]
I think `support@rocket.chat` is not available for anyone who is on starter plan, which makes it really hard to delete the Rocket Chat Cloud account. Any thoughts regarding creating a system with which cloud account users can delete their organizations and their account too by themselves?
