### ISSUE TITLE
Link decoration doesn't work with local domain names

### ISSUE THREAD

**Issue by 541263** [RocketChat/Rocket.Chat#29824]
### Description:

When you post a link like https://google.com/something Rocket.Chat decorates it as a link and make it clickable.
But when you have some local network service with one-word-domain-name and link looks like http://server/documents it doesn't work as expected.

### Steps to reproduce:

1. Open any chat
2. Post a link like "http://server/documents"
3. It isn't decorated and isn't clickable

### Expected behavior:

Link decorated as a hyperlink and open browser when is clicked

### Actual behavior:

Link looks like simple text

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.4
- Operating System: centos 7.4
- Deployment Method: docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: 3.9.4
- Operating System: windows 10

**Comment by hugocostadev** [comment]
To highlight custom domains without TLD (e.g: .local , .com) you can use the markdown for label/reference  pattern:

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/73a80b60-7131-4541-a79d-b91a57db35b0)

If you have a custom domain, like `.local` you can add in the `Workspace > Setting > Message` _Custom Domain Whitelist for Auto Link_ Setting: 

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/e2c90694-4db2-4f48-b558-8d5e8311f5f7)

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by 541263** [comment]
First of all I corrected version of the server, it's 6.2.10 on Ubuntu.

> To highlight custom domains without TLD (e.g: .local , .com) you can use the markdown for label/reference pattern:

This method works properly but requires some additional actions and is therefore boring.

> If you have a custom domain, like `.local` you can add in the `Workspace > Setting > Message` _Custom Domain Whitelist for Auto Link_ Setting:

And this method DOES NOT WORK for a single word domain name.
f.e. http://server/documents will not be decorated even I write "server" into `Workspace > Setting > Message`
