### ISSUE TITLE
Desktop Notifications doesn't work in Desktop Windows Applications Rocket.Chat+ 1.3.1

### ISSUE THREAD

**Issue by Amigo77** [RocketChat/Rocket.Chat#2984]
Your Rocket.Chat version: 1.3.1

Actual Result: Any Notifications from Windows desktop application doesn't work.
Expected Result: Notifications like Slack-notifications should work fine. 

Steps to reproduce:
1. Open Rocket.Chat Windows Application
2. Send any message to any recipient or try to receive it form other
3. See that recepient should not receive any notification (except red light on icon in tray and sound "din-don")

Red light on icon in tray is very inconspicuous.
If I don't use my headphones I can't to hear "din-don".

Moreover, many people are accustomed to the alerts in Slack-style is immediately obvious when who received a message and first string of the message.

Environment:
Windows 7 SP 1 x64
Rocket.Chat 1.3.1

**Comment by KervyN** [comment]
Yep. We got this problem 2.
No Notification via bubble / traybar / taskbar icon.

**Comment by cbajohr** [comment]
Same problem here. Any chance to fix this in the next release? @RocketChatApp 

It seems like a windows 7 only problem.

**Comment by rodrigok** [comment]
@cbajohr unfortunately we have major problems to solve right now, maybe someone from community can help us with that doing a PR for the Electron project to solve this issue.

**Comment by cbajohr** [comment]
Update: a fix for this problem is on its way... 
https://github.com/RocketChat/Rocket.Chat.Electron/pull/199

**Comment by virtualwatt** [comment]
any plans to fix this someday? :)

**Comment by gdelavald** [comment]
Fixed in previous versions.
