### ISSUE TITLE
Search Tab Doesn't Close When Search on Mobile

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#2986]
On a mobile device, both via Safari and a Cordova app, on a search result, if I click the gear icon and see the dropdown-menu (which is almost impossible to do, but that's another issue), when I click on the right hand icon, the page does not respond.

The expected behavior would be for the search panel to close and the page navigate to the message I clicked in the search results.

**Comment by MartinSchoeler** [comment]
@karlprieb the search works but the flex tab doesn’t close. There should be a if that collapses the flex if the platform is mobile.

**Comment by reetp** [comment]
There have been big changes to the mobile clients since this was opened.

Closing for now. Please reopen in the correct app section if this is still an issue.

**Comment by reetp** [comment]
@rocket-cat close
