### ISSUE TITLE
Multiple DOM nodes using the same id

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#2988]
Your Rocket.Chat version: 0.27.0

There are occasions when two nodes with the same `id` appear in the document.

For example, if I search for a message that currently appears on the page, the message with a given `id`, e.g. `xsAHQ6gGjKZToZikW` and the search result for that message both appear in the document at the same time. Both have identical `id`'s

DOM element `id`'s should be unique and never repeat in the same document [[MDN]](https://developer.mozilla.org/en-US/docs/Web/API/Element/id)

This could be causing issues with search and wherever else it occurs in the app.

I see you prefix `id` queries in your jQuery code, e.g. `$(".mentioned-messages-list \##{message_id} .message-cog-container").append el`. The DOM query would be more performant if you could just search for an `id`, e.g. `$("\##{message_id}").append el`.

I'm not sure where else this occurs, but I would consider applying a contextual prefix to the `id`, e.g. `id="main_<id>"` and `id="search-result_<id>"` in order to avoid conflicts.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
