### ISSUE TITLE
How To Apply Highlights To Every User

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2990]
Your Rocket.Chat version: 0.26

I noticed that there is not a way for an administrator to globally set specific words to be highlighted for every user. I was hoping I could get some advice on the approach in writing a mongo shell script to do this. I see inside the file `saveUserPreferences.coffee` that contains the method `RocketChat.models.Users.setPreferences Meteor.userId(), preferences` and a search into the mongodb users collection I see the settings object

```
"settings" : {
        "preferences" : {
            "disableNewRoomNotification" : false,
            "disableNewMessageNotification" : false,
            "useEmojis" : true,
            "convertAsciiEmoji" : true,
            "saveMobileBandwidth" : true,
            "compactView" : false,
            "unreadRoomsMode" : true,
            "autoImageLoad" : true,
            "emailNotificationMode" : "all",
            "highlights" : [
                "nopsstest"
            ]
        }
    },
    "language" : "en",
    "type" : "user"
}
```

and in `Users.coffee` there is an update:

```
setPreferences: (_id, preferences) ->
        update =
            $set:
                "settings.preferences": preferences

        return @update _id, update
```

Would it be safe to simply Update this settings object for each user if they don't have it, and properly pull any prior settings and update accordingly? I'm just trying to look out for any gotchas from the system to avoid breaking life. Thanks!

**Comment by marceloschmidt** [comment]
It should be OK to update user preferences, but exactly how are you going to do this? Are you going to update all users once, or is it going to be something to be run on every new registration? What's the use case? Thanks.

**Comment by MartinSchoeler** [comment]
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
