### ISSUE TITLE
Can't put the dev environment to work

### ISSUE THREAD

**Issue by icemagno** [RocketChat/Rocket.Chat#29912]
### Description:

Setup instructions to a dev environment not working

### Steps to reproduce:

Follow "instructions to setup a dev environment" in main page.

### Expected behavior:

To work 

### Actual behavior:

It is a nightmare to manage versions of necessary packages. Follow to https://yarnpkg.com/getting-started/install and see combinations of versions that makes sense only for those who tolerate node's poor dependency handling. After choosing ```npm i -g corepack``` because you said I need Node 14.x ( fall in <16.10 option ) I receive the warning:

```Unsupported engine for corepack@0.19.0: wanted: {"node":">=16.20.0"} (current: {"node":"14.21.3" ... ```

and then, by trying the next step ```Take a look at the [latest Yarn release](https://github.com/yarnpkg/berry/releases/latest), note the version number, and run:``` ( because fall in option Node.js <16.17 or <18.6 ) I receive the error:

```
corepack prepare yarn@3.6.1 --activate
/root/.volta/tools/image/packages/corepack/lib/node_modules/corepack/dist/lib/corepack.cjs:39787
      process.exitCode ??= code;
                       ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/root/.volta/tools/image/packages/corepack/lib/node_modules/corepack/dist/corepack.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
```

### Server Setup Information:

- Version of Rocket.Chat Server: Do not know. Don't even get the environment to work
- Operating System: Ubuntu 20.04 Docker 
- Deployment Method: Do not know. Don't even get the environment to work
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: v14.21.3
- MongoDB Version: N/A

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

**Comment by icemagno** [comment]
I'll check it ASAP and return.

**Comment by icemagno** [comment]
For short, I've created a Docker image to serve as "builder":

## Deploy a database:

```
docker run --name rocket-db --hostname=rocket-db --network=internal \
-v /etc/localtime:/etc/localtime:ro \
-v /srv/rocket-db:/data/db \
-e MONGODB_REPLICA_SET_MODE=primary \
-e MONGODB_REPLICA_SET_NAME=rs0 \
-e MONGODB_INITIAL_PRIMARY_HOST=rocket-db \
-e MONGODB_ADVERTISED_HOSTNAME=rocket-db \
-e MONGODB_ENABLE_JOURNAL=true \
-e ALLOW_EMPTY_PASSWORD=yes \
-d mongo:5.0.19 --replSet rs0 --oplogSize 128

docker exec -ti rocket-db mongo --eval "printjson(rs.initiate())"
```
Your presistent data folder is at ```/srv/rocket-db```

## Prepare the code

* 1. Create a folder named ```/srv/rocket```
* 2. Clone the repository to there
* 3. Start the builder image command line with options to allow the server to bring up (like database and etc)

```
mkdir /srv/rocket
cd /srv/rocket
git clone https://github.com/RocketChat/Rocket.Chat.git

docker run --rm --name rocket-builder --hostname=rocket-builder --network=internal \
-v /etc/localtime:/etc/localtime:ro \
-e ROOT_URL=http://172.22.1.49:36300 \
-e DEPLOY_METHOD=docker \
-e MONGO_URL=mongodb://rocket-db:27017/rocketchat?replicaSet=rs0 \
-v /srv/rocket:/home/ \
-p 36302:3000 \
-it magnoabreu/rocket-builder:6.3 /bin/bash
```

Change host and port as you need.

Once you're inside the "buider", go to ```/home/Rocket.Chat`` ( wich points to the outside folder where you cloned the repository ) and build the code.

```
 yarn
 yarn dsv
```

After a (long) time your server is up.

This image will vanish as soon as you exit from it. You'll need to run it again (or remove the ```--rm```from docker run command)

**Comment by wai52168** [comment]
@icemagno 
Why can't this be FREE and EASY ? #29911
I agree with your opinion. +1
