### ISSUE TITLE
Customization of "role tags"

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#2992]
Your Rocket.Chat version: 0.27.0

Hi. I just upgraded from 0.26.0 to 0.27.0 and I am seeing some minor but pleasant changes to the UI. However, I've got one question. Can we allow for customization of the "role tags" next to a user's name.
See, here is a screenshot of my user:
https://screen.img-cdn.ru/chrome_2016-04-22_06-05-39.png

It says "Rocket.Chat Admin", "Users" and "Room Owner". Allowing to customize this part would make for a tidier UI. In my case I would shorten "Rocket.Chat Admin" to just "Admin" and I think it is superfluous to include "Users" next to somebody who has the role of "Rocket.Chat Admin".
Lastly, perhaps it could be an option to make all it a setting, to even show these role tags in the first place. I'll keep them myself, but it would have been nice to have ability to customize the text for the various role tags.

Over and out.

**Comment by gramakri** [comment]
I came to report the same issue. I too feel the role tags are cluttering the otherwise clean Rocket.Chat UI. Is there a way to disable it? Thanks!

**Comment by geekgonecrazy** [comment]
@k0nsl we need to be a little more clear with this... But if you goto roles and edit the description this controls what is shown in the tag.  

If you click here:
![image](https://cloud.githubusercontent.com/assets/51996/14758165/df5356c4-08c1-11e6-9da3-10cbb5863f9c.png)

What ever is shown here:

![image](https://cloud.githubusercontent.com/assets/51996/14758171/f51fb4ca-08c1-11e6-9415-db49ec205e5b.png)

Is what is in the tag.

@gramakri removing the description will disable the tag from showing up.  But I agree we need a way to turn off the feature.

**Comment by k0nsl** [comment]
@geekgonecrazy: thanks, that did the trick!

**Comment by geekgonecrazy** [comment]
Awesome!

@gramakri if this doesn't do the trick for you.  Please feel free to open a ticket requesting the changes in behavior.

**Comment by gramakri** [comment]
@geekgonecrazy Removing description does indeed get back the old UI but IMHO this seems to be a workaround. I will open another ticket.
