### ISSUE TITLE
Failure to update latest package - Error: Can't find migration version 256

### ISSUE THREAD

**Issue by KTancula** [RocketChat/Rocket.Chat#29921]
### Description:

Hello,

Today I wanted to upgrade the rocketchat server from 4.5.2 to 6.2.10 in the manual version in Ubuntu 20.04.6 LTS.
The upgrade was done according to the following instructions :
https://docs.rocket.chat/deploy/prepare-for-your-deployment/other-deployment-methods/manual-installation/updating.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.10
- Operating System: Ubuntu 20.04.6 LTS
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v14.18.3
- MongoDB Version: db version v4.2.24
- Proxy: nginx

### Steps to reproduce:

Steps taken :
![image](https://github.com/RocketChat/Rocket.Chat/assets/109288141/3af97bc2-2fd5-4892-9a6e-099aaa1500fc)

The upgrade ran with the following notifications :
![image](https://github.com/RocketChat/Rocket.Chat/assets/109288141/1a2c563b-f67d-4afa-a798-6e32c36ca589)

### Expected behavior:

Run server

### Actual behavior:

Error in start server
After the upgrade this message appears :
Jul 26 10:45:05 rocketchat systemd[1]: Started The Rocket.Chat server.
Jul 26 10:45:10 rocketchat rocketchat[2152]: Some indexes for collection 'rocketchat_room' could not be created:
Jul 26 10:45:10 rocketchat rocketchat[2152]: Wildcard indexes require feature compatibility version 4.2
Jul 26 10:45:10 rocketchat rocketchat[2152]: Some indexes for collection 'rocketchat_livechat_visitor' could not be created:
Jul 26 10:45:10 rocketchat rocketchat[2152]: Wildcard indexes require feature compatibility version 4.2
Jul 26 10:45:10 rocketchat rocketchat[2152]: Some indexes for collection 'rocketchat_integration_history' could not be created:
Jul 26 10:45:10 rocketchat rocketchat[2152]: Index with name: _updatedAt_1 already exists with different options
Jul 26 10:45:10 rocketchat rocketchat[2152]: Some indexes for collection 'rocketchat_nps_vote' could not be created:
Jul 26 10:45:10 rocketchat rocketchat[2152]: Index with name: npsId_1_identifier_1 already exists with different options
Jul 26 10:45:10 rocketchat rocketchat[2152]: Some indexes for collection 'rocketchat_uploads' could not be created:
Jul 26 10:45:10 rocketchat rocketchat[2152]: Index with name: rid_1 already exists with different options
Jul 26 10:45:13 rocketchat rocketchat[2152]: (node:2152) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Jul 26 10:45:13 rocketchat rocketchat[2152]: Please migrate your code to use AWS SDK for JavaScript (v3).
Jul 26 10:45:13 rocketchat rocketchat[2152]: For more information, check the migration guide at https://a.co/7PzMCcy
Jul 26 10:45:13 rocketchat rocketchat[2152]: (Use node --trace-warnings ... to show where the warning was created)
Jul 26 10:45:13 rocketchat rocketchat[2152]: Some indexes for collection 'rocketchat_livechat_priority' could not be created:
Jul 26 10:45:13 rocketchat rocketchat[2152]: Index with name: name_1 already exists with different options
Jul 26 10:45:13 rocketchat rocketchat[2152]: LocalStore: store created at
Jul 26 10:45:13 rocketchat rocketchat[2152]: LocalStore: store created at
Jul 26 10:45:13 rocketchat rocketchat[2152]: LocalStore: store created at
Jul 26 10:45:16 rocketchat rocketchat[2152]: strict mode: missing type "object" for keyword "additionalProperties" at "#" (strictTypes)
Jul 26 10:45:16 rocketchat rocketchat[2152]: strict mode: missing type "object" for keyword "properties" at "#" (strictTypes)
Jul 26 10:45:17 rocketchat rocketchat[2152]: strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes)
Jul 26 10:45:20 rocketchat rocketchat[2152]: MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
Jul 26 10:45:20 rocketchat rocketchat[2152]: {"level":40,"time":"2023-07-26T08:45:20.915Z","pid":2152,"hostname":"rocketchat","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"}
Jul 26 10:45:22 rocketchat rocketchat[2152]: /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
Jul 26 10:45:22 rocketchat rocketchat[2152]: throw error;
Jul 26 10:45:22 rocketchat rocketchat[2152]: ^
Jul 26 10:45:22 rocketchat rocketchat[2152]: Error: Can't find migration version 256
Jul 26 10:45:22 rocketchat rocketchat[2152]: at server/lib/migrations.ts:249:9
Jul 26 10:45:22 rocketchat rocketchat[2152]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jul 26 10:45:22 rocketchat rocketchat[2152]: => awaited here:
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at module (server/startup/migrations/xrun.js:8:1)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.require (packages/modules-runtime.js:238:14)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at module (/opt/Rocket.Chat/programs/server/app/app.js:1432420:8)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.require (packages/modules-runtime.js:238:14)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at module (/opt/Rocket.Chat/programs/server/app/app.js:1439025:8)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.require (packages/modules-runtime.js:238:14)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.moduleLink [as link] (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at module (/opt/Rocket.Chat/programs/server/app/app.js:1511243:8)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at fileEvaluate (packages/modules-runtime.js:336:7)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Module.require (packages/modules-runtime.js:238:14)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at require (packages/modules-runtime.js:258:21)
Jul 26 10:45:22 rocketchat rocketchat[2152]: at /opt/Rocket.Chat/programs/server/app/app.js:1526689:15
Jul 26 10:45:22 rocketchat rocketchat[2152]: at /opt/Rocket.Chat/programs/server/boot.js:369:38
Jul 26 10:45:22 rocketchat rocketchat[2152]: at Array.forEach ()
Jul 26 10:45:22 rocketchat rocketchat[2152]: at /opt/Rocket.Chat/programs/server/boot.js:210:21
Jul 26 10:45:22 rocketchat rocketchat[2152]: at /opt/Rocket.Chat/programs/server/boot.js:423:7
Jul 26 10:45:22 rocketchat systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
Jul 26 10:45:22 rocketchat systemd[1]: rocketchat.service: Failed with result 'exit-code'.

**Comment by backeby** [comment]
Hi, I faced this same issue today, I don't think you can jump two major versions from 4.5.2.
I went 4.5.0 today to 5.4.3 and then to 6.2.11

Substitute the `latest` in the curl command with `5.4.3` to take you to the newest 5-version, update to that, start and then run the upgrade again with the latest to take you to 6.2.11

**Comment by hugocostadev** [comment]
Yep, @backeby is right... we do a clean up in the migration repository in a major change...  You need to update one major at time. 

Any other problem/doubt? I'll close for now.

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
