### ISSUE TITLE
Unable to start the server.

### ISSUE THREAD

**Issue by NitinCopods** [RocketChat/Rocket.Chat#29922]
Hey folks, I am facing this issue after running `yarn dev` this command. Please help me in solving this issue. 
<img width="658" alt="Screenshot 2023-07-26 at 3 53 35 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/111356197/d8a256dd-00f3-42ed-b5a5-5173b1bd7930">

**Comment by debdutdeb** [comment]
responded on open.
