### ISSUE TITLE
npm-bcrypt error in Rocket chat on FreeBSD

### ISSUE THREAD

**Issue by dprandzioch** [RocketChat/Rocket.Chat#2993]
Your Rocket.Chat version: Latest git master

After installing RocketChat using the following document:

https://rocket.chat/docs/master/installing-and-updating/deployment-options/freebsd

I get the following error:

> ## [rocketc@rocket ~/Rocket.Chat]# npm install --clang=1 bcrypt
> 
> > bcrypt@0.8.5 install /root/Rocket.Chat/node_modules/bcrypt
> > node-gyp rebuild
> 
> gmake: Entering directory '/root/Rocket.Chat/node_modules/bcrypt/build'
>  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
>  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
>  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
>  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
>  COPY Release/bcrypt_lib.node
> gmake: Leaving directory '/root/Rocket.Chat/node_modules/bcrypt/build'
> bcrypt@0.8.5 node_modules/bcrypt
> ├── bindings@1.2.1
> └── nan@2.0.5
> 
> [rocketc@rocket ~/Rocket.Chat]# meteor 
> => Running Meteor from a checkout -- overrides project version (Meteor 1.2.1)
> [[[[[ ~/Rocket.Chat ]]]]]                     
> 
> => Started proxy.  
> => Started MongoDB.  
> => Errors prevented startup:                  
> 
>   While checking for npm-bcrypt@0.7.8_2:
>   error: No compatible binary build found for this package. Contact the package author and ask them to publish
>   it for your platform.
> 
> => Your application has errors. Waiting for file change`

Already tried the suggested command "cp -R ~/meteor/packages/non-core/npm-bcrypt ~/Rocket.Chat/packages/*" with no success.

**Comment by Sing-Li** [comment]
@dprandzioch  Thanks for the report.

Please bear with us for a few days.  FreeBSD community member @rawzone is working on new instructions on deploying on FreeBSD that will work on 10.2 with ALL our latest Rocket.Chat stable releases.

You may want to visit https://demo.rocket.chat/channel/freebsd-compat  if you want a glimpse of the process sooner.

**Comment by dprandzioch** [comment]
@Sing-Li Thanks for the information. @rawzone already posted a Gist containing the extact same problem I experience:

https://gist.github.com/rawzone/506aae90fb78f49e89552b4bac374f1d

So maybe this might get fixed/documented soon.

**Comment by rawzone** [comment]
@dprandzioch I added a pull request on the documentation about deploying Rocket.chat on FreeBSD. Lets hope it get merged in... 

But until then you can have a look at my version here:
https://github.com/rawzone/Rocket.Chat.Docs/blob/master/3.%20Installing%20and%20Updating/2.%20Deployment%20Options/FreeBSD.md

Hope it helps.

**Comment by marceloschmidt** [comment]
It's been merged. Has this been solved?

**Comment by gogosofta** [comment]
I wonder where the https://download.rocket.chat/build/rocket.chat-freebsd-develop.tgz has gone?
