### ISSUE TITLE
How can i move rocketchat database on new server?

### ISSUE THREAD

**Issue by PaNKartoNiK** [RocketChat/Rocket.Chat#29949]
Hi everyone.
I have a server at a company where I have debian 9 installed, and I have RC version 3.x on it. It is installed on MongoDB according to the documentation from the official RC site

I recently started a new server on debian 11 on which I installed via snap RC the latest version.

I would like to transfer the database from the old server to the new one. The problem is that I don't know where exactly it installed the RC database on the new server. I tried to move the base via mongodump and mongorestore, unfortunately it didn't work. Is it possible to move the database itself from version 3.x to the latest version?

**Comment by esnutd** [comment]
can you check nodejs driver ?

**Comment by PaNKartoNiK** [comment]
On debian 9: v12.14.0, on debian 11: v14.21.2

**Comment by esnutd** [comment]
can you attarch either image or log file here?

**Comment by hugocostadev** [comment]
It's not possible neither recommended to migrate and skip major version, you need to update one major at time

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
