### ISSUE TITLE
How can I make autoupdate at cordova?

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#2994]
Myself deployed a rocket. Chat server, and build to an android app, but I how to use do autoupdate at android, I look at the Rocekt. Chat in the autoupdate found cordova part of the packages are commented out, is this why?How can I do it like a Rocket. Chat official app, when the user opens the app automatically update server with updated files?
Hope some one can help me!

**Comment by geekgonecrazy** [comment]
@Micjoyce have you built and compiled your own version of the app?  If you're using our app your app should automatically prompt for an update for your server.
