### ISSUE TITLE
The message indicator remains in the sidebar after viewing the message (V 6.2.11)

### ISSUE THREAD

**Issue by mahtifarahani** [RocketChat/Rocket.Chat#29961]
https://github.com/RocketChat/Rocket.Chat/assets/75629709/3bae5488-447e-45d2-9b98-fefa2966f1a7

Hello, I am using the latest version, but this problem is clearly visible
Another thing is that sometimes I don't receive event messages and there are problems in the event section. (In iframe)

**Comment by olodar** [comment]
Confirm this problem. Sometimes message won't mark as read.

**Comment by esnutd** [comment]
Yes,I have same issue

**Comment by edoniti** [comment]
Same issue here, we recently upgraded from `4.8.7` to  `6.3.0`. If you close the web/app and then open again the indicator is gone, but not without re-opening the web/app. Even if you mark explicitly as read it does not work.
