### ISSUE TITLE
Can the function keys be hidden? (for Apps Marketplace)

### ISSUE THREAD

**Issue by wai52168** [RocketChat/Rocket.Chat#29966]
**SERVER RUNNING**
Rocket.Chat Version: 6.2.11
NodeJS Version: 14.21.3 - x64
MongoDB Version: 6.0.8

Can the part inside the red box in the following picture be hidden? It's not needed.
![image](https://github.com/RocketChat/Rocket.Chat/assets/81604190/f88ede2c-7632-4494-9ded-69e8dc786a57)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

You can remove thought custom css or remove the permission 'manage-apps' and 'access-marketplace' for all roles


---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
