### ISSUE TITLE
Import hipchat enterprise data

### ISSUE THREAD

**Issue by pqvindesland** [RocketChat/Rocket.Chat#2997]
Your Rocket.Chat version: 0.27.0

When importing data from a hipchat server to Rocket chat, rocket chat requires the file to be compressed in a zip format but on hipchat 1.3.9 (2016.03.24.210917) the file is in a tar.gz.aes format which the rocket chat importer does not recognise.

I decrypt the file with openssl aes-256-cbc -d -in hipchat-2016-04-21_17-22-52.tar.gz.aes -out hipchat-2016-04-21_17-22-52.tar.gz -pass pass:password so it's left with only tar.gz this also fails as rocket chat only wants a zip file which hipchat does not give anymore.

Extracting the tar.gz and compressing the files to a zip file does not work.

Could this be looked into? I imagine that there are users who are using this feature so it would be great if it could be fixed.

**Comment by geekgonecrazy** [comment]
@pqvindesland do you know if it still gives .zip on non-encrypted export?

**Comment by pqvindesland** [comment]
No it does not give any options of selecting what compressed file type or if to encrypt it or not.

**Comment by graywolf336** [comment]
@pqvindesland Are you using the free version or the enterprise version?

**Comment by graywolf336** [comment]
@RocketChat/core After doing some research and talking with someone else, it appears there are two different HipChat instances which we will need to support. The first one is the one which is currently there and working, the hipchat cloud. The second one is the one which is currently not there, the hipchat enterprise edition. Sadly though, this is a little more difficult to work with since it requires us to have a dataset from an enterprise edition of hipchat as there is little to no documentation on that export's structure and I don't have access to one.

Any ideas?

**Comment by engelgabriel** [comment]
Maybe I can buy the starter licence of the enterprise edition? They used to offer for 10 USD for the first 10 users. Can you check?

**Comment by pqvindesland** [comment]
We are using the enterprise version, if you need an export then I can always setup a new server push some data into it and export it and send it to you if that would help.

**Comment by engelgabriel** [comment]
@pqvindesland This would really help!

**Comment by graywolf336** [comment]
@pqvindesland Yes, that would be extremely helpful!

**Comment by pqvindesland** [comment]
I will get it done this week and upload the export.

**Comment by graywolf336** [comment]
Awesome, looking forward to it! :+1:

**Comment by christianreiss** [comment]
Any update on this? :)

**Comment by geekgonecrazy** [comment]
@christianreiss I believe no progress on this yet.  We don't have access to an enterprise install of hipchat so we can't test this until we get ahold of an export.

**Comment by JamieH** [comment]
Hey @geekgonecrazy I have access to an enterprise install

**Comment by graywolf336** [comment]
Mind hitting me up on the demo server? So we can get this implemented
