### ISSUE TITLE
Hover BUG

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#2998]
I dont know if anyone else have noticed this but whenever you hover over any (blue)button in your chat or any of the channels in the left panel  ANY colored text  (links for an example) in the chat blinks??

It isn't that visible when it's a light background but try adding a dark background and you will see it immediately

**Comment by Molle500** [comment]
![examplee](https://cloud.githubusercontent.com/assets/17712562/14736506/d88defe2-0877-11e6-9c40-cf9edaf68ac7.png)


If you hover your mouse over the channels (marked with red). The links (marked with green) will blink like crazy

**Comment by geekgonecrazy** [comment]
I'm not able to replicate this.  Looks like you're in chrome?  Also what version of Rocket.Chat are you on?

**Comment by Sing-Li** [comment]
Do you see the attributes in dev tools changing values?  If not, it might be a graphics driver level problem.

**Comment by Molle500** [comment]
@geekgonecrazy @Sing-Li 
The demo is on your chat so it's the latest version, but this has occured on all the versions atleast i have tried.

I've found out it only happends on Google chrome, not any other browser. I have tried on three different computers all with different graphic brands. Same problem on all three computers when using chrome.

I recorded it on my desktop to show you, if you enter full screen and 1080p you should see it clearly.

https://youtu.be/4rgNUXQ22-o?t=16

**Comment by lvh1** [comment]
I know what you mean, but I think this is a bug with chrome itself as I have seen it happen on other websites as well, but not so often.

**Comment by AdrianoCahete** [comment]
Use [ScreenToGif](https://screentogif.codeplex.com/) to create a gif with just selected area (instead full screen) to show better.

**Comment by marceloschmidt** [comment]
This doesn't seem like something we have control over. I'll close this until further information is provided that identifies this as a Rocket.Chat bug.
