### ISSUE TITLE
API Rate Limiter

### ISSUE THREAD

**Issue by maxin9966** [RocketChat/Rocket.Chat#29988]
My current version is 6.2.9, installed using Docker. The earliest version should be 6.2.5. Initially, everything was working fine, but recently I've encountered the following issues:

I have already disabled the API Rate Limiter, but I still frequently receive errors like "Max retries exceeded with URL" when uploading files using the Python robot client. It seems that the setting did not take effect.

I set the maximum upload file size to 100MB, but it doesn't seem to work at all. The maximum file size for upload remains as 1MB, which was set in the previous configuration. It appears that the setting didn't take effect.

I configured scheduled cleaning, but it is currently not working. I'm using the file system as my current file system, and the setting still doesn't work. (This setting used to work fine before; I'm not sure if it's due to a version update. I noticed that you are trying to fix this bug in the latest version. Do you know when the new version will be released?)

When I use the default file system, my robot client consumes high CPU usage and causes significant lag after uploading a large number of images. However, when I switch to the file system, the high CPU usage problem is resolved.

All these issues were working fine in my previous usage. I'm not sure if updating the version caused these problems. Can someone provide an answer?

**Comment by maxin9966** [comment]
Adding one more question,
When I deploy the service on Tencent Cloud server (China mainland), the server's network works perfectly fine. However, I noticed that the interface for adding a user provided by the administrator freezes and times out. It seems like the user is being added halfway and gets stuck at a certain step. But when I deploy the server in Hong Kong or the United States, this issue does not occur. Does it have something to do with the network? Could it be because Tencent Cloud server cannot access a specific interface of your official services?

**Comment by maxin9966** [comment]
Adding a question:
When I deploy the service on Tencent Cloud Server (Mainland China), I noticed that the API for adding users gets stuck and times out directly. It seems like the user is partially added but gets stuck at a certain step. However, when I deploy the server in Hong Kong or the United States, this issue does not occur. It appears to be related to the network (the server can access the internet). Could it be because Tencent Cloud servers are unable to invoke a specific interface provided by your official services?

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
