### ISSUE TITLE
Click on new message notification do not open proper chat

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#29987]
### Description:

Click on new message notification do not open proper chat, and actually do nothing.

### Steps to reproduce:

1. Get some new message with notification on computer (Web and Desktop versions)
2. Click on that notification
3. Nothing happens

### Expected behavior:

Proper chat should be opened. If message was in thread, then thread should be opened in proper position (that new message)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.10
- Operating System: OL8.5
- Deployment Method: docker
- Number of Running Instances: 16
- DB Replicaset Oplog: Enabled - change streams
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.16 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 114 and Rocket.Chat desktop 3.9.5
- Operating System: Windows 10 22H2

### Additional context

If opened another tab in browser, then click on notification opens Rocket.Chat tab

### Relevant logs:

In devTools (but could be not related - saw that first notification and didn't appear later on other notifications)

```

Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
play @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1599
newMessage @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1599
E @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1599
(anonymous) @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1599
(anonymous) @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1500
emit @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1500
(anonymous) @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1500
(anonymous) @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1500
emit @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1500
(anonymous) @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1500
(anonymous) @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380
forEachCallback @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380
socket.onmessage @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380
r.dispatchEvent @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380
k._dispatchMessage @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380
k._didMessage @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380
o.ws.onmessage @ 70ddc01addb7676e8fd9ad58755a8a5dd1666eb1.js?meteor_js_resource=true:1380


```

**Comment by shiryov** [comment]
Same issue on 6.3.3 both in the browser and in the Electron application (3.9.6)
