### ISSUE TITLE
[6.3.0] - OAuth broken after update

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#30003]
### Description:

Not possible to login via OAuth after upgrade to 6.3.0.
SAML intergration is still working.

### Steps to reproduce:

1. click on login for OpenConnectID
2. enter password and credentials
3. reaching login page again.
4. 
### Expected behavior:

Successful login

### Actual behavior:

Login not possible with OAuth integration.
Identity provider is Keycloak.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0
- Operating System:  Rocky Linux 8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version:  v14.21.3
- MongoDB Version: 5.0.19 / wiredTiger (oplog Enabled)

### Client Setup Information

- Browser: Firefox 116
- Operating System: Fedora 38

### Additional context

No change inside configuration. Only update of rocket.chat to 6.3.0.

### Relevant logs:

`Aug  3 09:00:25 rocket-test RocketChat[610922]: Exception while invoking method 'login' Error: Failed to complete OAuth handshake with keycloak at https://login.domain.com/realms/domain.com/protocol/openid-connect/token. Bad Request
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at app/custom-oauth/server/custom_oauth_server.js:148:18
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  3 09:00:25 rocket-test RocketChat[610922]: => awaited here:
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at app/custom-oauth/server/custom_oauth_server.js:194:18
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  3 09:00:25 rocket-test RocketChat[610922]: => awaited here:
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/oauth2/oauth2_server.js:10:22
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  3 09:00:25 rocket-test RocketChat[610922]: => awaited here:
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/oauth/oauth_server.js:171:5
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  3 09:00:25 rocket-test RocketChat[610922]: => awaited here:
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/accounts-base/accounts_server.js:1525:11
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  3 09:00:25 rocket-test RocketChat[610922]: => awaited here:
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/accounts-base/accounts_server.js:653:7
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Aug  3 09:00:25 rocket-test RocketChat[610922]: => awaited here:
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/meteor.js:365:18
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/ddp-server/livedata_server.js:791:46
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at new Promise (<anonymous>)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at Session.method (packages/ddp-server/livedata_server.js:739:23)
Aug  3 09:00:25 rocket-test RocketChat[610922]:    at packages/ddp-server/livedata_server.js:603:43
`

**Comment by Gummikavalier** [comment]
For the record custom Oauth configuration is still working.

**Comment by psy** [comment]
We are facing the same issue with a custom oauth provider.

Logs:
```
Aug 04 11:21:28 rocket rocketchat[171083]: {"level":50,"time":"2023-08-04T11:21:28.737Z","pid":171083,"hostname":"rocket","name":"System","msg":"Exception while invoking method login","err":{"type":"Error","message":"","stack":"Error: Failed to complete OAuth handshake with <SSO> at <DOMAIN>/oauth2/token. BAD REQUEST\n    at app/custom-oauth/server/custom_oauth_server.js:148:18\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/custom-oauth/server/custom_oauth_server.js:194:18\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/oauth2/oauth2_server.js:10:22\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/oauth/oauth_server.js:171:5\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/accounts-base/accounts_server.js:1525:11\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/accounts-base/accounts_server.js:653:7\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at packages/ddp-server/livedata_server.js:1818:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1743:17)\n    at app/api/server/v1/misc.ts:620:33\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:620:17\n    at /usr/share/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":""}
```

**Comment by pierre-lehnen-rc** [comment]
Thank you for the report!
Can you tell me if you updated from rocket.chat 6.2 or from an older version?

**Comment by TimmiORG** [comment]
Hi @pierre-lehnen-rc 
before we run a 6.2.10.

**Comment by m4z** [comment]
Same here, custom oauth broken after 6.2.10 → 6.3.0 update. Our log format looked slightly different IIRC, but I won't have access to the logs until monday.

**Comment by pierre-lehnen-rc** [comment]
Bug introduced by #28828 , it was caught by our QA team and supposedly fixed by #29131 , but it seems to still happen for some specific OAuth providers depending on how they send us the response. 
I'll test it with keycloak specifically for confirmation.

**Comment by raisedadead** [comment]
What is the quickest way to rollback a version? It seems simply pointing to a previous release doesn't work.

**Comment by cyrillbolliger** [comment]
Is there any possibility to hotfix this? We're also suffering this issue...

**Comment by mawe42** [comment]
I have a hunch that it might be related to a missing `OAuth.openSecret()` call after this commit in this line:
https://github.com/RocketChat/Rocket.Chat/commit/306d4ace1e2acabe6a7da593401511b277a95880#diff-5de402c11f9d389e642876d8c990011ecf9dbf1cd4696b9470c48841dabecc3cR128

So maybe hotfixing line 128 with `params.append('client_secret', OAuth.openSecret(config.secret));` might help...

**Comment by rainlabs** [comment]
I noticed that after update to 6.3.0 token exchange is working differently. I see in logs that instead of sending POST request with body, rocket.chat sends payload as get params but still in POST request and my keycloak server can't recognize it as valid request.

Also I found in the code that the Authorization header has also been changed from 'Bearer' to 'Basic' which requires changing keycloak config to enable basic auth.

**Comment by ankar84** [comment]
@pierre-lehnen-rc hey!
Same problem here. We have perfectly working SSO via KeyClock integration in domain environment now on 6.2.10
Testing 6.3.0 on test deployment in same KeyCloak integration and confirm that it is broken.
User press button => some windows appears for a moment and then nothing happens.

**Comment by psy** [comment]
We rolled back to 6.2.11 for the moment but it's annoying that

1. this was not tested before rollout

**Comment by inta** [comment]
It's not only OAuth, LDAP login is broken too. As long as the sessions are valid Rocket.Chat keeps working, but new logins fail.
The log says something like `Username already exists. [403]`

(Sorry, I do not have the log anymore, because I had to roll back the VM.)

**Comment by pierre-lehnen-rc** [comment]
We're working on a fix for this issue.

> It's not only OAuth, LDAP login is broken too. As long as the sessions are valid Rocket.Chat keeps working, but new logins fail. The log says something like `Username already exists. [403]`
> 
> (Sorry, I do not have the log anymore, because I had to roll back the VM.)

That's unrelated to this issue. Please open a new one if you have any more information.
Either way I'll double check the LDAP flow here.

**Comment by svenseeberg** [comment]
> > It's not only OAuth, LDAP login is broken too. As long as the sessions are valid Rocket.Chat keeps working, but new logins fail. The log says something like `Username already exists. [403]`
> > (Sorry, I do not have the log anymore, because I had to roll back the VM.)
> 
> That's unrelated to this issue. Please open a new one if you have any more information. Either way I'll double check the LDAP flow here.

I can see the same issue. I created a new issue for that: #30034

**Comment by ykorzikowski** [comment]
Same issue here. I downgraded to 6.2.11 and needed to downgrade also my database to 294. 

```
db.migrations.update({_id: 'control'},{$set:{locked:false,version:294}})
```

**Comment by seraphyn** [comment]
Same on our side.
IMO this should be fixed with a small minor release

**Comment by casalsgh** [comment]
Team, Rocket.Chat will have a patch release (6.3.1) soon with needed fix for this one. 
Just validating solution (QA steps)

**Comment by zidex** [comment]
please release a helm-chart with this version

**Comment by sandrotanner** [comment]
Thanks for the fix. I have problems upgrading since https://releases.rocket.chat/6.3.1/download does not exist yet @sampaiodiego

**Comment by bndrgroup** [comment]
Please release this to registry.rocket.chat/rocketchat/rocket.chat:6.3.1 for helm users!
