### ISSUE TITLE
iOS native app bug after update

### ISSUE THREAD

**Issue by schucan** [RocketChat/Rocket.Chat#3000]
Rocket.Chat version: iOS app version 2.3.1

I had a "there is a new version of the app files" popover when I started the app on my iPhone 6s. I tapped on "yes, update". It loaded the "3" files, and now I have the loading throbber. Even if I get out of the app, kill it, and restart. It stays there. 

Interestingly, notifications continue to work!

The workaround: If I uninstall rocket from the device, kill safari (for cache, I guess), reinstall rocket, reconfigure my chat server, it works again.

This happened the second time, i.e. every time there was this popover for an update.

**Comment by Sing-Li** [comment]
I observe the same problem on the iPad.  Actually if you wait for half an hour or longer, eventually it may load the chat.
