### ISSUE TITLE
View user information GUI crash

### ISSUE THREAD

**Issue by chenjpu** [RocketChat/Rocket.Chat#30001]
### Description:

![image](https://github.com/RocketChat/Rocket.Chat/assets/1785778/1be835ec-b474-4c69-956d-f779b9c85ae7)

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server:  6.3.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

https://github.com/RocketChat/Rocket.Chat/pull/28912

**Comment by chenjpu** [comment]
When I switch the language from Chinese to the other (English, China (Hong Kong)) display is normal

**Comment by xwb777** [comment]
> When I switch the language from Chinese to the other (English, China (Hong Kong)) display is normal

me too

**Comment by liyue1010110** [comment]
咋解决的  直接换港汉么

**Comment by chenjpu** [comment]
是的

**Comment by xwb777** [comment]
> 是的

感觉这样解决有点尴尬，中文香港的有的翻译很离谱，close是亲密，open是开放，我尝试着设置英文语言，然后在通用设置里面的翻译设置里把中文的i18n的Json贴进去，但是发现不生效，很头疼，不知道是不是哪里漏了什么设置

**Comment by liyue1010110** [comment]
找到解决方案了  把/opt/Rocket.Chat/programs/server/assets/app/i18n/zh-HK.json 备份 然后把zh.i18n.json 或者zh-CN.json 重命名为zh-HK.json 注意文件权限要rocketchat:rocketchat  到设置里语言设置成中文(香港) 个人偏好改成默认 就 不会再崩溃了 不知道为什么文件内容一样 但是用zh 或者zh-CN 就会崩溃  @chenjpu
