### ISSUE TITLE
WebRTC no longer available since 5.x

### ISSUE THREAD

**Issue by linwuliao** [RocketChat/Rocket.Chat#30007]
### Description:

WebRTC no longer available since 5.x，
I install the rokect chat 6.3.0 with docker and I configed the webrtc with my own turn server and enable it, but when I click the “Call” button ,it shows me “App not enabled”, and it need me install and configure a conference call app.

I tried using version 5.x , but it has the same issue.
then,I downgrade the version to 4.8, I meet another issue same as https://github.com/RocketChat/Rocket.Chat/issues/25550

### Steps to reproduce:

1. install rocket chat with docker.
2. install turn server.
3. configure webrtc with the turn server and enable it.
4. click the "Call" button in 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0
- Operating System: ubuntu 22 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:
- MongoDB Version: 5.x
- Proxy: caddy
- Firewalls involved:

### Client Setup Information

- Desktop App or Browser Version: Edge 115.0.1901.188
- Operating System: Windows 10

**Comment by kkqy** [comment]
close because https://github.com/RocketChat/Rocket.Chat/pull/23172#issuecomment-1670003878

**Comment by linwuliao** [comment]
close because of https://github.com/RocketChat/Rocket.Chat/pull/23172#issuecomment-1670003878
