### ISSUE TITLE
Discussion Rest API?

### ISSUE THREAD

**Issue by pendalf45** [RocketChat/Rocket.Chat#30004]
I should to use discussions because of naming rules (need spaces, etc...).

How can I use rest api for deleting discussions, inviting to and kicking from?

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

Check our API Docs: [REST API - Rocket.Chat Developer](https://developer.rocket.chat/reference/api/rest-api)

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
