### ISSUE TITLE
Upgrade 6.2.11 to 6.3.0: MongoTopologyClosedError: Topology is closed

### ISSUE THREAD

**Issue by oliob** [RocketChat/Rocket.Chat#30005]
### Description:

Upgraded docker container from 6.2.11 to 6.3.0. then got: MongoTopologyClosedError: Topology is closed. Instance does not start any more. Downgrade to 6.2.11 did help, it works again.

Error Message:

### Steps to reproduce:

1. Upgrade docker container from 6.2.11 to 6.3.0

### Expected behavior:

works

### Actual behavior:

get `MongoTopologyClosedError: Topology is closed.` error and instance does not start.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0
- Operating System: ubuntu 22.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.8

### Relevant logs:
`$> docker logs docker-rocketchat-1`

Some indexes for collection 'rocketchat_analytics' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_apps_persistence' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_avatars' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_banner' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_banner_dismiss' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_calendar_event' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_credential_tokens' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_custom_sounds' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_custom_user_status' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_email_inbox' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_email_message_history' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat__trash' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_custom_emoji' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_export_operations' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_federation_servers' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_import_data' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_integration_history' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_integrations' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_agent_activity' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_custom_field' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_department' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_department_agents' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_inquiry' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_room' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_trigger' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_livechat_visitor' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_matrix_bridged_rooms' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_matrix_bridged_users' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_message' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_notification_queue' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_nps' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_nps_vote' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_oauth_apps' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_oauth_auth_codes' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_oauth_access_tokens' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_oauth_refresh_tokens' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_oembed_cache' could not be created:
	Topology is closed
Some indexes for collection 'pbx_events' could not be created:
	Topology is closed
Some indexes for collection '_raix_push_app_tokens' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_message_reads' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_room' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_server_events' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_sessions' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_statistics' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_subscription' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_team' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_team_member' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_uploads' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_user_data_files' could not be created:
	Topology is closed
Some indexes for collection 'users' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_video_conference' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_webdav_accounts' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_federation_room_events' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_import' could not be created:
	Topology is closed
Some indexes for collection 'rocketchat_cron_history' could not be created:
	Topology is closed
/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

MongoTopologyClosedError: Topology is closed
    at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:232:46
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at app/settings/server/startup.ts:8:2
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at module (app/settings/server/index.ts:23:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (server/oauth2-server/oauth.ts:175:2)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (/app/bundle/programs/server/app/app.js:1521132:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (/app/bundle/programs/server/app/app.js:1552388:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14) {
  [Symbol(errorLabels)]: Set(0) {}`

**Comment by rodrigok** [comment]
@oliob thanks for your report. Do you have more logs or those are from the start of the process?

If you try to start an empty instance for another database (but to a different db name) do you have the same issue?

**Comment by oliob** [comment]
@rodrigok i just tested it again going from 6.2.11 again same instance to 6.3.0 on the docker side. now it worked. Strange.... i did not change anything on the DB side.

**Comment by schmel** [comment]
same problem. I fix it by adding a parameter  'directConnection=true' to the mongodb connection string.
```
MONGO_OPLOG_URL : mongodb://rocketchat:$(DB_PASS)@rocket-chat-mongodb:/local?replicaSet=rs0&directConnection=true
MONGO_URL : mongodb://rocketchat:$(DB_PASS)@rocket-chat-mongodb:/rocketchat?replicaSet=rs0&directConnection=true
```

**Comment by florisvangeel** [comment]
These errors arise when mongo is crashed/down.  
had the same issue without docker upgrading to 7.7.9 and running out of disk space.  
Thus mongo crashed and obviously rocket.chat couldn't start.
