### ISSUE TITLE
Favicon is being marked as when pending messages, but there is any.

### ISSUE THREAD

**Issue by maxsdw** [RocketChat/Rocket.Chat#3002]
Your Rocket.Chat version: 0.26.0

We have noticed even though we have no unread messages (not even the ever lasting un-read message) the tab still indicates there are unread messages.

**Comment by cedemore** [comment]
Same problem here

**Comment by geekgonecrazy** [comment]
@maxsdw does this happen with 0.27.0 as well?  Also have you noticed anything in particular clearing that away?

**Comment by maxsdw** [comment]
I have tested it only on 0.26.0. Refreshing or pressing ESC key helps to clear it away, but not always.

**Comment by MartinSchoeler** [comment]
@geekgonecrazy have you seen this bug happening recently?

**Comment by geekgonecrazy** [comment]
I personally don't know that I ever saw it.  Going to go ahead and close.  @maxsdw let me know if this was closed in error.
