### ISSUE TITLE
check_mk notifications within RocketChat

### ISSUE THREAD

**Issue by Againstreality** [RocketChat/Rocket.Chat#3003]
Hi we liked to have an check_mk integration within Rocket.Chat. So we got our monitoring frontend within Rocket. So we build one based on an Bashscript. 

So we did it: https://github.com/Againstreality/Rocket.Chat.check_mk-integration
You can use it if you want.

**Comment by engelgabriel** [comment]
Awesome @Againstreality ! Thanks fro sharing. We will add this to the docs.

**Comment by engelgabriel** [comment]
I have created https://github.com/RocketChat/Rocket.Chat.Docs/issues/23
