### ISSUE TITLE
[6.3.0] SAML login breaks in mobile app

### ISSUE THREAD

**Issue by svenseeberg** [RocketChat/Rocket.Chat#30049]
### Description:

When logging in with the mobile app via a SAML IdP, the app logs in but stays in the SSO browser widget. The app itself does not register a successful login. Instead, the Rocket.Chat website is shown in the browser widget.

### Steps to reproduce:

1. Configure SAML IdP
2. Log in via native app
3. App stays in SSO widget, even after successful login

### Expected behavior:

The app should register the successful login and return to its native chat options

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/15197000/bcb8ee28-9e6d-4e32-8a57-a2f5c3e87d20)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.19

### Client Setup Information

- Desktop App or Browser Version: Android 4.39.0.43604
- Operating System: Android 13

### Additional context

N/A

### Relevant logs:

The app sends a request to `/api/v1/login` with a JSON body:
```json
{
"saml": true,
"credentialToken": "MySecret"
}
```
The server answers with HTTP 401 Unauthorized and the following message:
```json
{
"status": "error",
"message": "No matching login attempt found",
"error": 12345678
}
```
The message obviously comes from https://github.com/RocketChat/Rocket.Chat/blob/856c23555a43853165ba9d9daeed508ccf4c6892/apps/meteor/app/meteor-accounts-saml/server/loginHandler.ts#L23

**Comment by arthur-trt** [comment]
Facing the same problem here with Android and iOS

**Comment by anicoa** [comment]
In CredentialTokens.create the token is written into collection rocketchat_credential_tokens into field inResponseToId:

```
{ "_id": "id","userInfo":{"profile":{"inResponseToId":"JBvsCVkOeEPRH1v8N", 
```

But CredentialTokens.findOneNotExpiredById is looking for the token in _id:

```
"filter":{"_id":"JBvsCVkOeEPRH1v8N","expireAt":{"$gt":{"$date":"2023-08-10T14:02:30.620Z"}
```

**Comment by arthur-trt** [comment]
Issue still present in 6.3.1

**Comment by HunKjj** [comment]
Yes 6.3.1 same issue

**Comment by HunKjj** [comment]
Some investigation done, auth with saml seems ok, just from mobile phone we goes to web version.

**Comment by Serzho2025** [comment]
I tested this evening, got problem with saml auth and Android sso viget on 6.3.1, need fix asap

**Comment by anicoa** [comment]
@pierre-lehnen-rc may I kindly ask for support and review of the pr?

**Comment by pierre-lehnen-rc** [comment]
Bug introduced by #29945 
We changed one of the urls related to the saml login and the react app is still expecting the old url only.

**Comment by AndrewChau** [comment]
This is a very severe issue for us. Would appreciate if it can be prioritized, thanks.

**Comment by anicoa** [comment]
@pierre-lehnen-rc anything we can do?

**Comment by HunKjj** [comment]
Ok ! Great ! Thanks for Fix this problem ! But now problem with exist on Browser and PC version ! "Page not found"

**Comment by enoch85** [comment]
This is now merged and could be closed.
