### ISSUE TITLE
Can not install Rocket.Chat

### ISSUE THREAD

**Issue by Karmylr** [RocketChat/Rocket.Chat#30045]
### Description:

After I execute the `snap install rocketchat-server`, I get an error `Run install hook of "rocketchat-server" snap if present (run hook "install": [ERROR] Your cpu does not support avx or avx2 instructions, which is required to run mongo 5.x, shipped with the next version of this snap.)`

### Server Setup Information:

- Version of Rocket.Chat Server:  newest
- Operating System: Debian 12
- Deployment Method: snap
- CPU: Intel Celerun J4125

**Comment by Dnouv** [comment]
Hey @Karmylr 

Thank you for opening the issue. But it seems this (`AVX`) is actually a requirement set by Mongo -> https://github.com/docker-library/mongo/issues/485

The error message you are seeing indicates that your CPU, an Intel Celeron J4125, does not support the AVX or AVX2 instruction sets. These instruction sets are required to run MongoDB 5.x, which is included in the `snap` version of Rocket.Chat you are trying to install via snap.

According to the [Intel® Product Specifications](https://ark.intel.com/content/www/us/en/ark/products/197305/intel-celeron-processor-j4125-4m-cache-up-to-2-70-ghz.html), the Intel Celeron J4125 processor does not support AVX or AVX2 instruction sets. This means that you will not be able to run MongoDB 5.x on this processor and, therefore, cannot install `Rocket.Chat` via snap on your current system.


You may consider using a different deployment method (and using Mongo `4.x` - Rocket.Chat supports Mongo 4.4) or upgrading your hardware to a CPU that supports the AVX or AVX2 instruction sets.

I will close this issue, please feel free to open, it in case you need any further assistance.

---
Some useful links:
1. [Rocket.Chat Supported Mongo Versions](https://docs.rocket.chat/setup-and-configure/rocket.chat-environment-configuration/mongodb-configuration/mongo-versions)
2. [Deploy Rocket.Chat](https://docs.rocket.chat/deploy/prepare-for-your-deployment)

Thank you!

**Comment by CommanderGL** [comment]
this would mean that this repo is no longer relevant as this error happens on raspberry pi's: [RocketChat/Rocket.Chat.RaspberryPi](https://github.com/RocketChat/Rocket.Chat.RaspberryPi)
