### ISSUE TITLE
iFrame authentication not loading on log out

### ISSUE THREAD

**Issue by gsckoco** [RocketChat/Rocket.Chat#30046]
### Description:

When you log out of RocketChat, it will redirect you to the built in login screen despite having iFrame authentication enabled

### Steps to reproduce:

1. Set up iFrame auth.
2. When logged in, log out (Either through the UI or your session expiring)
3. Default log-in page displays instead of the iFrame auth

### Expected behavior:

On log out, display iFrame auth instead of built-in log-in page. Default log-in/sign-up should never be accessible with iFrame auth in place

### Actual behavior:

Built-in login page is displayed, instead of iFrame, when it should not be accessible.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.3 (Also the case on 6.0 test system)
- Operating System: Ubuntu Server 22.04
- Deployment Method: Running as a service, no docker (https://docs.rocket.chat/deploy/prepare-for-your-deployment/other-deployment-methods/ubuntu)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome 115
- Operating System: Windows 10 Professional

**Comment by guijun13** [comment]
Hi there, thanks for the contribution! 🚀 💯 

It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. 
Thank you very much!

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
