### ISSUE TITLE
Non root URL install bugs and bad links

### ISSUE THREAD

**Issue by MadDog4533** [RocketChat/Rocket.Chat#30057]
### Description:

Installs bound to non root addresses ie. https://example.com/chat/ dont propery handle link routing.
A resource on https://example.com/chat/channel/general is linked as https://example.com/channel/general
As well as all resources on admin side dont properly use the web root dir. 

Still havent seen a PR patching the regression 5.x -> 6.x from decodeURIComponent not properly working with non root installs and throwing a maximum call stack exceeded in the browser until a refresh occurs. Confirmed it was still throwing errors in 6.2.x cant test 6.3.x since the admin links dont include ref to the non root uri. #28581 #28380

### Steps to reproduce:

Install RC on anything non root. example: https://example.com/chat/

### Expected behavior:

All resources are prepended with proper uri /channel/general is [root]/channel/general

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.0
- Operating System: ubunutu 20.04 LTS
- Deployment Method: Tar
- Number of Running Instances: 1
- DB Replicaset Oplog: true
- NodeJS Version: 14.21.2
- MongoDB Version: 5.0.14

### Client Setup Information

- Desktop App or Browser Version: Brave / Chromium
- Operating System: Windows

**Comment by hugocostadev** [comment]
**NOTE:** Running in a subfolder has been officially deprecated. It will no longer be supported in the upcoming 4.0 release. See our [April 2020 announcement](https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371)

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
