### ISSUE TITLE
Connection between keycloak and rocketchat

### ISSUE THREAD

**Issue by aminr99** [RocketChat/Rocket.Chat#30061]
### Description:

I am trying to authenticate Rocket-Chat with Keycloak using OpenID Connect but after login into keycloak I am not redirected to rocket. both of them are created in separate containers.
I really appreciate for help.
### Steps to reproduce:

Keycloak Setup:
![image](https://github.com/RocketChat/Rocket.Chat/assets/52712713/e1d6d549-7f11-4495-8f4c-d790e514820f)
![image](https://github.com/RocketChat/Rocket.Chat/assets/52712713/af2ad59f-1928-436a-9300-d752c9735b9f)

Rocket Setup:
![image](https://github.com/RocketChat/Rocket.Chat/assets/52712713/77bb671e-cdb0-45c1-9bc3-69e559eeb894)
![image](https://github.com/RocketChat/Rocket.Chat/assets/52712713/52f68ae4-be20-4057-84f3-8f28f149471c)

### Expected behavior:
I can login into Rocket-Chat with keycloak

**Comment by ankar84** [comment]
Try 6.3.1 with #30041 that could fix your problem

**Comment by JoeriHermans** [comment]
It seems the `6.3.1` build, which includes #30041 , has failed.

**Comment by aminr99** [comment]
@JoeriHermans @ankar84 
Thank you very much, my problem was solved in version 6.3.1
