### ISSUE TITLE
Error: [not-allowed]  /meteor_js_resource=true:367:19243)

### ISSUE THREAD

**Issue by isaacdarcilla** [RocketChat/Rocket.Chat#30076]
### Description:

I am trying to authenticate user using IFrame, but I got this error:

```json
{
    "isClientSafe": true,
    "error": "not-allowed",
    "message": "[not-allowed]",
    "errorType": "Meteor.Error"
}
```

Error: [not-allowed]\n    at o (http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:367:19243)\n    at E._livedata_nosub (http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:367:19315)\n    at E.onMessage (http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:367:21963)\n    at http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:337:2695\n    at Array.forEach (<anonymous>)\n    at c.forEachCallback (http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:337:3767)\n    at socket.onmessage (http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:337:2664)\n    at r.dispatchEvent (http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:337:8506)\n    at http://localhost:3001/8ef777f0affa3d99854cf3b39710be86f1f1d647.js?meteor_js_resource=true:337:18656\n    at Array.forEach (<anonymous>)

### Expected behavior:

Authenticate the user with "login-with-token"

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3
- Operating System: Windows 11
- Deployment Method: Docker

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

This is the React component to authenticate user on page load

```js
import Skeleton from '@/components/Skeleton'
import { useAuth } from '@/hooks/auth'
import Head from 'next/head'
import { useEffect } from 'react'

const ChatEmbed = () => {
    const { user } = useAuth()

    useEffect(() => {
        if (user) {
            const iframe = document.querySelector('iframe');

            const handleIframeLoad = () => {
                // Get the authentication token
                const authToken = user.loginToken;
                console.log(authToken);

                // Pass the authentication token to the embedded chat interface
                iframe.contentWindow.postMessage({
                    externalCommand: 'login-with-token',
                    token: authToken
                }, '*');
            };

            iframe.onload = handleIframeLoad;

            // Clean up the event listener when the component unmounts
            return () => {
                iframe.onload = null;
            };
        }
    }, [user])

    return (
        <>
            <Head>
                <title>VOLT Arts - Chat</title>
            </Head>
            {!user ? (
                <>
                    <div className="space-y-2">
                        <Skeleton center={true} />
                    </div>
                </>
            ) : (
                <>
                        <iframe
                            title="Chat Channel"
                            src={`http://localhost:3001/channel/general?layout=embedded`}
                            className="absolute w-full h-full"
                            allow="camera;microphone"
                            sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
                        />
                </>
            )}
        </>
    )
}

export default ChatEmbed

```

**Comment by Shivamdwivedi1403** [comment]
.

**Comment by Ziktorin** [comment]
+1, the same error with keycloak auth

**Comment by isaacdarcilla** [comment]
I resolved this by setting the **IFrame URL and API URL**

The API URL must return the `authToken` . More here https://developer.rocket.chat/customize-and-embed/iframe-integration/configuring-iframe-auth

![image](https://github.com/RocketChat/Rocket.Chat/assets/22732118/c45bfd8f-6839-4578-8717-f6b7bfc0424a)
