### ISSUE TITLE
DeepL api url

### ISSUE THREAD

**Issue by nimetu** [RocketChat/Rocket.Chat#30075]
DeepL integration currently only supports pro plan url `api.deepl.com`, but the free plan uses `api-free.deepl.com`.

DeepL [documenation](https://www.deepl.com/docs-api/api-access/authentication)  tells that free api keys can be easily identified.

> DeepL API Free authentication keys can be identified easily by the suffix ":fx"
> (e.g., 279a2e9d-83b3-c416-7e2d-f721593e42a0:fx)

**Comment by thepranays** [comment]
Can i work on this issue ? Please provide some directions to start.

**Comment by nimetu** [comment]
> Can i work on this issue ? Please provide some directions to start.

https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/autotranslate/server/deeplTranslate.ts
