### ISSUE TITLE
Overwrite Setting by environment is not working for plugin in marketplace?

### ISSUE THREAD

**Issue by kkqy** [RocketChat/Rocket.Chat#30078]
I use the environment below to overwrite the domain of Jitsi that installed in marketplace.
`OVERWRITE_SETTING_jitsi_domain=abc.com`

but it didn't work.

It seems like that the Overwrite Setting by environment  is only available for internal settings.

**Comment by hugocostadev** [comment]
you are correct, it's only possible to overwrite internal settings
