### ISSUE TITLE
Create a bot editing UI

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#3008]
Your Rocket.Chat version: latest

I edited the Rocket.Cat account and changed the name of it, now I can not seem to change it back.  it's causing the right menu to behave funky. It won't allow me to edit the account in admin either

![capture](https://cloud.githubusercontent.com/assets/10718586/14755453/a5a9022e-089f-11e6-804a-bb883d9d9ede.JPG)

I would like to change the name back, can't seem to find a way to do it.

**Comment by sadeva** [comment]
Hi @twhiting, you can edit it via the mongo console.

**Comment by twhiting** [comment]
Can you give me a quick walkthrough of how i'd do that?

**Comment by engelgabriel** [comment]
What is the error on the browser console?

**Comment by twhiting** [comment]
@engelgabriel when I open the sidebar on my bot I get all this: (with sensitive info I left out about my domain)

```
Exception in template helper: TypeError: Cannot read property 'username' of undefined
Exception in template helper: TypeError: Cannot read property 'username' of undefined
Exception in template helper: TypeError: Cannot read property 'username' of undefined
Exception in template helper: TypeError: Cannot read property 'name' of undefined
Exception in template helper: TypeError: Cannot read property 'utcOffset' of undefined
Exception from Tracker recompute function:
TypeError: Cannot read property 'clear' of undefined
    at .<anonymous> (2f0aa3e….js?meteor_js_resource=true:373)
    at 2f0aa3e….js?meteor_js_resource=true:83
    at Function.e._withTemplateInstanceFunc (2f0aa3e….js?meteor_js_resource=true:84)
    at 2f0aa3e….js?meteor_js_resource=true:83
    at Object.d._withCurrentView (2f0aa3e….js?meteor_js_resource=true:83)
    at l (2f0aa3e….js?meteor_js_resource=true:83)
    at t.Computation._compute (2f0aa3e….js?meteor_js_resource=true:35)
    at new t.Computation (2f0aa3e….js?meteor_js_resource=true:35)
    at Object.t.autorun (2f0aa3e….js?meteor_js_resource=true:35)
    at d.View.autorun (2f0aa3e….js?meteor_js_resource=true:83)

```

**Comment by Sing-Li** [comment]
For security reasons, rocket.cat is a system-internal bot user that does not have email or password and can never login.  It should never be edited via the sidebar  (perhaps we should disable that for rocket.cat?).

If you need custom integration "bot user", please create a new normal user and assign it bot roles.

**Comment by engelgabriel** [comment]
We should care for this special case, we are build a bot editing interface.

**Comment by Sing-Li** [comment]
👍

**Comment by twhiting** [comment]
Is there anyway I can return rocket cat to its previous state or delete it all together?

**Comment by engelgabriel** [comment]
If you delete and restart the server.. it will be recreated.

Gabriel Engel

**Comment by twhiting** [comment]
@engelgabriel how would I delete the bot if I can't even access the edit menu? from the console?  Could you walk me through how to do that?  thanks

**Comment by engelgabriel** [comment]
What server version are you using?

**Comment by sadeva** [comment]
Hi @twhiting, are you trying on your local environment or on a docker container?

**Comment by twhiting** [comment]
I'm on version 0.28.0 and using a docker container

**Comment by engelgabriel** [comment]
@sampaiodiego can you understand why this error may be happening? Can we add some testes to prevent the script from braking because of a missing property?

**Comment by sampaiodiego** [comment]
> can you understand why this error may be happening?

the query we were using to set user's email was creating an object if the user hasn't an email before (fixed in e6b58eb99ce51b2248bb70ab1fce7491a38dbe27)

> Can we add some testes to prevent the script from braking because of a missing property?

I just added some tests to the case mentioned above (see 1b8f98fcd58b9ec733107b67bfab77f069d21686).. but it can happens in many other places..

**Comment by marceloschmidt** [comment]
This will be closed as a bug. Just opened #3078 for the new UI issue.

**Comment by twhiting** [comment]
No my issue hasn't been resolved, I'm trying to find a method of deleting rocket.cat once the name has been changed

**Comment by marceloschmidt** [comment]
@twhiting I see you're running this through docker. Do you know how to get shell access on the docker running mongo? If you can have shell access there, then you'll have to type: `mongo [db_name]`, where db_name is the name you specified in your docker composer file, or the last part of MONGO_URL, which is the db name. Then, after you go into mongo, you have to type: `db.users.remove({ username: 'rocket.cat' });` or whatever the new username is. Let me know how that goes.

**Comment by engelgabriel** [comment]
@twhiting did you try the develop branch? The fix have not been released on the stable version yet.

**Comment by twhiting** [comment]
@marceloschmidt Thank you that worked great.   @engelgabriel No havn't tried development branch all I needed for now was a way to delete the bot to regenerate it.  Thanks everyone!
