### ISSUE TITLE
Release numbers vs version numbers

### ISSUE THREAD

**Issue by rhires** [RocketChat/Rocket.Chat#3009]
I don't see anything that correlates the release number (.25, for example) to the version number (1.3.1, for example)...

How do I know what goes with what?

**Comment by geekgonecrazy** [comment]
@rhires are you talking the version number and how it relates to other version numbers?

I don't completely understand what you mean.

**Comment by rhires** [comment]
So when I go to download from your page, I get version 1.3.1 (https://itunes.apple.com/app/rocket.chat/id1086818840). But when I look at the releases section (https://rocket.chat/releases), it's numbered .26 or whatever. Does .26 = 1.3.1? Or how would I know what release number = what version number?

**Comment by geekgonecrazy** [comment]
@rhires ah!

Ok so the version in the app store is for the mobile app its self.

The version on the release page has to do with the actual server piece.

Mobile apps: version 1.3.1
Server: version 0.26.0

So the release numbers are for two different components.  Both completely valid to their perspective pieces

**Comment by rhires** [comment]
There should be some mention of that on the releases page, I would think. Also, some links to where the mobile apps can be downloaded from - the main (non-techie) website doesn't let the user know that there are these different components, and it can be confusing. Anyway, thanks for the clarification.
