### ISSUE TITLE
User menu falls out of the home window in RTL languages

### ISSUE THREAD

**Issue by paymanzafar1** [RocketChat/Rocket.Chat#30094]
### Description:
I am using Persian language which is a RTL language. In the home window, when I click on my avatar to open the user menu, it opens but it is not visible as in the below image.

![image](https://github.com/RocketChat/Rocket.Chat/assets/91053236/0ea5c7c6-b56a-4cc7-963b-0a014a01f56f)

It is correct when I switch to English language as in the below image:

![2](https://github.com/RocketChat/Rocket.Chat/assets/91053236/171adfee-376f-48ea-ae3f-185f3bbe528d)

### Steps to reproduce:

1. Login to the system
2. Go to Adminstration-> Workspace-> Settings -> General
3. Set the language to Persian
4. Go the the home page
5. Click on your avatar on the upper right corner of the page

### Expected behavior:

The user menu open on the right side of avatar and falls outside of the screen

### Actual behavior:

The user menu must fall on the left side of the avatar to be seen

**Comment by manojku1803** [comment]
Can You please provide the file path?

**Comment by ashutosh887** [comment]
Should I work on this @paymanzafar1

**Comment by paymanzafar1** [comment]
Hi there.
Of-course. I appreciate your help to solve this bug.
@iagocarmona, @manojku1803, @ashutosh887

**Comment by iagocarmona** [comment]
Can assign me? I'll wotk on this.

**Comment by paymanzafar1** [comment]
Hi @hugocostadev 
There are several requests to help in this issue.
