### ISSUE TITLE
The application GUI just crashed

### ISSUE THREAD

**Issue by xtayaitak** [RocketChat/Rocket.Chat#30109]
### Description:

"The application GUI just crashed" when manager users.

![image](https://github.com/RocketChat/Rocket.Chat/assets/4498459/1a291e00-b559-44fd-9542-9aecbc5376de)

1. go to manager user
2. click an user

- Version of Rocket.Chat Server: 
- Operating System: ubuntun 20.04
- Deployment Method: docker
- Number of Running Instances: 1

- Desktop App or Browser Version:chrome,desktopapp
- Operating System:win10

![image](https://github.com/RocketChat/Rocket.Chat/assets/4498459/82da2c06-32ce-4d8a-8a87-ca3cb8d3de0e)

**Comment by chaoslawful** [comment]
See #30082
