### ISSUE TITLE
Room information panel reports a hilarious retention time number

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#30101]
### Description:

Room information view shows a hilarious number in the retention time message.

Does not affect actual retention time.

This issue has been around since RC 6.0.0.

### Steps to reproduce:

1. Under admin settings set the global retention time to 90 days
2. Go to any channel and check Room information

### Expected behavior:

The retention time should show 90 days.

### Actual behavior:

![Screenshot from 2023-08-16 18-47-57](https://github.com/RocketChat/Rocket.Chat/assets/6958942/75f47373-ed37-45f8-b71b-9f8351c3d177)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.1
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Latest Firefox or Chrome

**Comment by hugocostadev** [comment]
Fixed at [fix: Time format of Retention Policy #29651](https://github.com/RocketChat/Rocket.Chat/pull/29651)
