### ISSUE TITLE
Application Error: The application GUI just crashed

### ISSUE THREAD

**Issue by megapepe76** [RocketChat/Rocket.Chat#30113]
I have rocketchat managed by my job, and I am getting this message but nobody else in my organization is. I have done everything, nothing seems to help.,

**Comment by gusarg81** [comment]
Hi, I am having the same problem since latest rocketchat-server (6.3.1), with the follow error in console:

> TypeError: Cannot read properties of undefined (reading 'hours')
>     at lastDay (eval at <anonymous> (TranslationProvider.tsx:1:1), <anonymous>:51:46)
>     at A.R [as calendar] (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:225:719703)
>     at 241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:522:2860279
>     at g (UserInfo.tsx:1:2222)
>     at Ii (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:59708)
>     at hs (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:69188)
>     at ds (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:68522)
>     at ls (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:68180)
>     at $c (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:114847)
>     at nu (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:98852)

This is critical, since I have two instances, separate servers, which I use for my clients, with the same error.
Both Snap packages, both Ubuntu 22.04.

Any ideas or workaround? Thanks.

**Comment by cm-quint** [comment]
> Hi, I am having the same problem since latest rocketchat-server (6.3.1), with the follow error in console:
> 
> > TypeError: Cannot read properties of undefined (reading 'hours')
> > at lastDay (eval at  (TranslationProvider.tsx:1:1), :51:46)
> > at A.R [as calendar] (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:225:719703)
> > at 241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:522:2860279
> > at g (UserInfo.tsx:1:2222)
> > at Ii (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:59708)
> > at hs (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:69188)
> > at ds (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:68522)
> > at ls (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:68180)
> > at $c (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:114847)
> > at nu (241ed9ab96b707efb232a05e041797fec786ca1e.js?meteor_js_resource=true:130:98852)
> 
> This is critical, since I have two instances, separate servers, which I use for my clients, with the same error. Both Snap packages, both Ubuntu 22.04.
> 
> Any ideas or workaround? Thanks.

I was able to workaround setting the general language as English (it was previously set as 'Default'). 
/admin/settings/General

**Comment by gusarg81** [comment]
This did not fixed the problem for me. Changed to English, and when I navigate to users info, app crash.

**Comment by florisvangeel** [comment]
yea it fails on sub packages like gazzodown, cron as well as readable-stream, packages/models, ee/packages/ddp-client
i19n as well, awaiting fixes...

**Comment by hugocostadev** [comment]
Seems to be fixed now in the latest release, could you check, please? Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by gusarg81** [comment]
I use Snap version in my server, which latest is 6.3.1. If I try to upgrade to Edge channel, then rocketchat-server will not start:

"Not migrating, control is locked."
