### ISSUE TITLE
Notification sound at LiveChat customer panel

### ISSUE THREAD

**Issue by edoniti** [RocketChat/Rocket.Chat#3012]
It would be great to have a notification sound to notify the customers when the chat agent replies on their LiveChat. I really like this feature when I use online chat support on different systems, because many times chat agents take some time to check the issue and than get back, so the customer does not have to check time by time if they got a reply but they will hear the notification sound.

**Comment by AlecTroemel** [comment]
I like this. Ideally the customer would be able to toggle the notification sound on and off
