### ISSUE TITLE
Out of memory during rollup update 6.2.10 -> 6.3.1

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat#30125]
### Description:

When an instance starts, it quickly reaches the max_old_space_size limit and crashes with an error
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

### Steps to reproduce:

1. On a running system with about 3k active sessions, start updating to version 6.3.1
2. Recreate first docker container from the official 6.3.1 image and run it

### Expected behavior:

Instance run normally

### Actual behavior:

The instance crashes with an error after a few minutes:
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.10, 6.3.1
- Operating System: Oracle Linux Server release 8.6
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 114
- Operating System: Windows, Mac, Linux

### Additional context
graphs with max_old_space_size=8g

![Clipboard - August 20, 2023 9_56 AM](https://github.com/RocketChat/Rocket.Chat/assets/666827/84ca4c30-79fb-426e-9f34-c2ead26dc0dc)

![Clipboard - August 20, 2023 9_41 AM](https://github.com/RocketChat/Rocket.Chat/assets/666827/024f9d26-3f99-49c9-97cb-eb89d7ba1dbc)

### Relevant logs:

[first_start_log.txt](https://github.com/RocketChat/Rocket.Chat/files/12394183/first_start_log.txt)

**Comment by geekgonecrazy** [comment]
how many instances are running?  Also what does mongo look like?  Is it on a different host?

**Comment by shiryov** [comment]
20 instances are running
MongoDB replicaset runs on 3 separate physical servers, there was no increased load average MongoDB servers at the time of this OOM, no long operations too.

**Comment by shiryov** [comment]
We have reduced the number of instances to 16.
Before the rollup update all instances of 6.2.10 were stopped at once and started again.
The problem has not reproduced again. 6.3.1 works well
