### ISSUE TITLE
Sorting & Filters in Admin > Users

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#3013]
I find it very useful to have some kind of sorting feature in `Admin > User` page.

At least by **registration date** .

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/669b6080-63a1-4b17-b868-760ccb95c737/2016-04-23_1406.png)

**Comment by lvh1** [comment]
You might want to blank out those emails, just for the sake of privacy.

**Comment by shtefcs** [comment]
Well, I was thinking about it, but that's 4 guys are people i know and i know that their emails are public visible on many sites. 

You are mostly right, I wanted, but made quick calculation in my head, that I am not doing anything bad. Actually they would be probably glad if someone say hi to them :P

**Comment by ggazzo** [comment]
Implemented :)
