### ISSUE TITLE
"yarn dev" without mongodb. Is it possible?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#30149]
Hello!

Can i run "yarn dev" in local development without mongodb. Is it possible?
I already have mondodb and set mongo enviroment variables

Thanks you advanced

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

I'm not sure... try to run with `MONGO_URL` and `MONGO_OPLOG_URL` env vars inside the `apps/meteor` folder ...

```bash
MONGO_URL='...' MONGO_OPLOG_URL='...' meteor
```

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
