### ISSUE TITLE
Disabling 'access-marketplace' permission for users show an empty 'Administration' tab

### ISSUE THREAD

**Issue by mboudet** [RocketChat/Rocket.Chat#30159]
### Description:

When the 'access-marketplace' permission is disabled for users, the 'Administration' menu is empty (except for a vertical bar).

### Steps to reproduce:

1. Disable 'access-marketplace' permission for users
2. Log in as a normal user
3. Click on the 'Administration' menu

### Expected behavior:

Maybe simply hide the 'administration' button if the menu is empty? Or a least show a message such as 'No available action'.

### Actual behavior:

Weird empty menu (vertical bar showing)

![image](https://github.com/RocketChat/Rocket.Chat/assets/17642511/79e8f2dd-9f9d-495d-949e-dc6a23272d7e)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.1
- Deployment Method: docker
- MongoDB Version: 5.0

### Client Setup Information

Browser: Firefox

**Comment by amitpanwar789** [comment]
can you assign me, I would like to work on this

**Comment by ashutosh887** [comment]
@mboudet Let me work on this

**Comment by mboudet** [comment]
Sure. I don't think I can assign anyone on my end.
