### ISSUE TITLE
Problem with first login after PC boot

### ISSUE THREAD

**Issue by adamage2k** [RocketChat/Rocket.Chat#30158]
Since the last update, my colleagues and I have been experiencing an issue with the initial login after a PC boot. Every time, we are required to enter our credentials, and it appears that there is a server loading bug. After logging in, we are also required to use the "reload server" option; otherwise, we are unable to access the system.

**Comment by hugocostadev** [comment]
please, can you provide more info? Follow the issue template, please...

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by hugocostadev** [comment]
When you click at open issue there is a issue template already in the description textarea

**Comment by adamage2k** [comment]
After latest update there is no longer issue with loging in.
