### ISSUE TITLE
Unable to upload assets on web and desktop client

### ISSUE THREAD

**Issue by shobhitsharma** [RocketChat/Rocket.Chat#30162]
### Description:

There is currently an issue with new rocket chat version where users are not able to attach screenshots. The issue is related to missing assets that might have caused by tree-shaking library which incorrectly cached or mapped. 

### Steps to reproduce:

1. Goto attach button
2. Select an attachment

### Expected behavior:

Attachments should work.

### Actual behavior:

Throws following error in developer console.

```bash
to load resource: the server responded with a status of 404 ()
/sockjs/info?cb=xfcgg40ro9:1     Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_NETWORK_IDLE_TIMEOUT
/sockjs/info?cb=lkyq551e4h:1     Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_NETWORK_IDLE_TIMEOUT
/sockjs/info?cb=g9khe64l9e:1     Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR.QUIC_NETWORK_IDLE_TIMEOUT
1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3 Uncaught (in promise) Error: Cannot find module 'foreach'
    at y (1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3:644)
    at d.r [as require] (1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3:3674)
    at t (1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3:736)
    at module (index.js:1:44)
    at 1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:1370:764
    at g (1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3:1100)
    at d.r [as require] (1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3:3658)
    at t (1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:3:736)
    at module (types.js:1:91)
    at 1f20aee670e8ae63462e2a14a61c401f4c223584.js?meteor_js_resource=true:1370:764

```

<img width="858" alt="Screenshot 2023-08-24 at 4 38 40 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/772855/6505f579-6e3a-4339-84d6-54b6fc1d5236">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.5 or 3.9.6
- Operating System: MacOS
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System:

**Comment by hugocostadev** [comment]
Can you send the real Rocket.Chat Server version?  Not the Desktop version, please... 

Seems that you are on a version 6+ ... did you tried to update to the 6.3 release?  Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by pajaron-mms** [comment]
hi @hugocostadev version is 6.2.10. there is a 6.3 version we can upgrade to?

**Comment by hugocostadev** [comment]
Yes, there is, check it here: [Releases · RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/releases)

**Comment by pajaron-mms** [comment]
we've updated and it didn't get fixed, but the new learning was that copy+pasting an image works. just dragging+droping, plus using the attachment button doesn't.
