### ISSUE TITLE
 prevent API calls from out of my web app

### ISSUE THREAD

**Issue by davisbra** [RocketChat/Rocket.Chat#30189]
how can I prevent API calls from out of my web app?
For example, I want to prevent API calls from Postman or Curl
and APIs only work from my default URL

**Comment by hugocostadev** [comment]
Sorry, can you elaborate more? Did you find a bug with it? 

Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
