### ISSUE TITLE
Markdown: strikethrough text does not work with the code span

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat#30185]
### Description:

I have my application that works as a notificator. It gets alerts from Zabbix and sends them to Rocket.Chat. After the alert is closed, my notification edits Rocket.Chat message.

For new alert message is:

```
:sos: WARNING `[server.example.net]: less than 10% 4.48 GB on volume /` [12345](https://zabbix.example.net/tr_events.php?triggerid=29634&eventid=247154493)
```

it is ok: 
![image](https://github.com/RocketChat/Rocket.Chat/assets/1219067/8458c2bd-586f-44c1-be25-1bfd22bd238c)

but after the notificator app edit message, formatting breaks. Edited message:

```
:white_check_mark: ~~_WARNING `[server.example.net]: less than 10% 4.48 GB on volume /` Duration: 01:10:01 [12345](https://zabbix.example.net/tr_events.php?triggerid=29634&eventid=247154493)_~~

or

:white_check_mark: ~_WARNING `[server.example.net]: less than 10% 4.48 GB on volume /` Duration: 01:10:01 [12345](https://zabbix.example.net/tr_events.php?triggerid=29634&eventid=247154493)_~
```
and it is broken:

![image](https://github.com/RocketChat/Rocket.Chat/assets/1219067/2bce21f3-59cc-40de-8f41-1b11d5fae1f7)

if I put exactly the same markdown to the Visual Studio Code, it is ok:

![image](https://github.com/RocketChat/Rocket.Chat/assets/1219067/0c6965e5-03bf-45b8-acf8-14a7980fe834)

### Expected behavior:

Show the message as in VS code editor

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.1
- Operating System: Debian 12 x64
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: desktop app 3.8.16 and Google Chrome 116
- Operating System: Ubuntu 22.04 x64

**Comment by tuxmartin** [comment]
@hugocostadev Hello, I had the similar issue https://github.com/RocketChat/Rocket.Chat/issues/29773

Today I upgraded to Rocket.Chat 6.3.1 and now I have this problem.

Do you have any idea how can I fix it?

**Comment by hugocostadev** [comment]
Hi @tuxmartin , do you think that the error was introduced in the latest version?  I don't think so... it was working before? 

Either way, it's a bug and we can improve it... thanks for reporting 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by tuxmartin** [comment]
@hugocostadev I think it worked in Rocket.Chat Server: `5.4.10`.

**Comment by hugocostadev** [comment]
maybe... depending the message-parser that you were using it

**Comment by tuxmartin** [comment]
@hugocostadev I don't understand. I was using Rocket.Chat 5.4.10 and didn't configure any parser.

Is there any hotfix solution?

**Comment by hugocostadev** [comment]
At 5.4.10 version we had a configuration in user preferences that you could choose between the new message parser and the old one... but now we just have one. 

We will work on a fix for that

**Comment by ashutosh887** [comment]
Let me work on this @tuxmartin @hugocostadev

**Comment by tuxmartin** [comment]
@ashutosh887 I will be pleased if someone fixes this.

**Comment by ashutosh887** [comment]
Please assign @tuxmartin

**Comment by tuxmartin** [comment]
@ashutosh887 I can't assign. I don't have permission to the GitHub repository. I just reported a bug.

**Comment by tuxmartin** [comment]
@ashutosh887 do you have any progress?

**Comment by tuxmartin** [comment]
Rocket.Chat 6.4.2: still the same problem :-(

**Comment by tuxmartin** [comment]
Rocket.Chat 6.4.4: still the same problem :-( 

It is a significant issue for me.

I would like to send some money for the repair if that helps.

**Comment by AdityaRaut13** [comment]
As I told you earlier the problem is with the parser and hence it must be raised in the fuselage repo.
By adding the code to Italic Content, I was able to work with the things out. 
But it must be merge with the latest build in the fuselage.

**Comment by tuxmartin** [comment]
@AdityaRaut13 what shoul I do? Create an issue at repo https://github.com/RocketChat/fuselage?

**Comment by AdityaRaut13** [comment]
Yes, you need a feature request for the same on that repo.

**Comment by AdityaRaut13** [comment]
Ask about adding inLineCode to the italicContentBlock.
You can also ask them to add it to other contentBlock .

**Comment by tuxmartin** [comment]
It's been broken for almost four months. There is a way to fix it. But still nothing happens :-(

**Comment by Subhojit-Dey1234** [comment]
@tuxmartin Raised the following PRs for this issue. Hope it will fix it.
https://github.com/RocketChat/fuselage/pull/1256
https://github.com/RocketChat/Rocket.Chat/pull/31349

**Comment by hugocostadev** [comment]
Hi guys, thanks for your patient and @Subhojit-Dey1234 contribution! I'm going to take a look ASAP

**Comment by tuxmartin** [comment]
I have still the same problem with Rocket.Chat 6.6.0 (snap).

When I use strikethrough text **without link**, it's ok:

```
:white_check_mark: ~AVERAGE [vpn1.example.com]: Container /nginx: Container has been stopped with error code Duration: 00:00:03~
```
![image](https://github.com/RocketChat/Rocket.Chat/assets/1219067/f3e65575-8c04-4fac-b9a4-d22d717805e5)

But I need to have link and it's still broken:

```
:white_check_mark: ~AVERAGE [vpn1.example.com]: Container /nginx: Container has been stopped with error code Duration: 00:00:03 [4923369](https://zabbix.test.eu/tr_events.php?triggerid=123&eventid=456)~
```
![image](https://github.com/RocketChat/Rocket.Chat/assets/1219067/cc73736b-a081-42ef-b8af-815bdfa894f3)

I tried to (as an workaround) move link after end `~`, that's even worse:

```
:white_check_mark: ~AVERAGE [vpn1.example.com]: Container /nginx: Container has been stopped with error code Duration: 00:00:03~ [4923369](https://zabbix.test.eu/tr_events.php?triggerid=123&eventid=456)
```
![Výběr_105](https://github.com/RocketChat/Rocket.Chat/assets/1219067/9c1140a7-342d-4d44-b9c4-14695638813a)


Is this an Rocket.Chat error? Or am I using Markdown wrong?

**Comment by tuxmartin** [comment]
I tried to split it to two groups, still broken:

```
:white_check_mark: ~AVERAGE [vpn1.example.com]: Container /nginx: Container has been stopped with error code Duration: 00:00:03~ XXX ~[4923369](https://zabbix.test.eu/tr_events.php?triggerid=123&eventid=456)~
```
![Výběr_106](https://github.com/RocketChat/Rocket.Chat/assets/1219067/08baf8fe-4b5e-42e4-9253-53dbfee22f2a)
