### ISSUE TITLE
Make a class per Roletag

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#3019]
Today its not possible to do custom css per role. There is only one tag.

I would suggest the following change in packages/rocketchat-ui-message/message/message.html

```
{{#each roleTags}}
<span class="role-tag-{{.}}">{{.}}</span>

```

Then every role will have a unique tag.

**Comment by marceloschmidt** [comment]
Instead of `class="role-tag-{{.}}"` we opted for `data-role="{{.}}` which can also be accessed in CSS and we won't have problems with spaces in role description.

**Comment by lunitic** [comment]
@marceloschmidt Works too :+1:
