### ISSUE TITLE
Avatars can not be store on filesystem

### ISSUE THREAD

**Issue by netdevfighter** [RocketChat/Rocket.Chat#3020]
Your Rocket.Chat version: 0.27.0

The storage typ is:
FileSystem

The storage path is:
/srv/rocket.chat/avatars/ (directory has as owner rocketchat)

With the attachments works this without problems.

**Comment by netdevfighter** [comment]
After restarting the service ....it works .. ..but it was very clear that it requires a restart ...

**Comment by marceloschmidt** [comment]
Let's make a note on issue #1492. I'll close this one in favor of that.
