### ISSUE TITLE
Not-translated strings

### ISSUE THREAD

**Issue by paymanzafar1** [RocketChat/Rocket.Chat#30218]
### Description:
I am using Persian language, and installed BigBlueButton & Jitsi for video calls. When you initiate a call in a livechat, the following strings are not translated in the widget. It is not possible to translate them via custom translations in the Settings->General.

![image](https://github.com/RocketChat/Rocket.Chat/assets/91053236/3f7fdee6-9e15-44c2-a8d9-cd180b96545d)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Could you share more info?  Follow the issue template please... Seems that you are using an old version... 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by paymanzafar1** [comment]
Hi There.
I am using version 6.3.2.
I checked the fa.json file in the \packages\livechat\src\i18n folder. These strings are not there.

**Comment by paymanzafar1** [comment]
Hi There.
I added the following strings as your instructions, and built the package again. But the problem is not solved.

"Join_call": "به تماس بپیوندید.",
"video_livechat_started": "تماس تصویری آغاز شد."

**Comment by paymanzafar1** [comment]
I also updated to version 6.3.3 without any difference.

**Comment by ashutosh887** [comment]
Let me work on this @paymanzafar1
