### ISSUE TITLE
"message too long" error

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#3021]
Rocketchat Version 0.26.

Hello Devs.

When i try to paste a very long text in the chat window i get the error message: "message too long". What is the limitation here?

thanks and best regards
t.

**Comment by marceloschmidt** [comment]
The message length is limited by an administration setting under Administration / Message / Maximum Allowed Message Size. In the demo, this is set to 5000 characters.

![image](https://cloud.githubusercontent.com/assets/1986378/14783467/2bc0b820-0ac6-11e6-908f-ff9b0a97d92d.png)

**Comment by MatanRubin** [comment]
What are the implications of setting it to a very large number (say 100K)?
Is there any Slack-like feature which suggests turning a long message into a snippet (instead of not allowing you to send the message)?
