### ISSUE TITLE
Livechat feature: Tell the customer if there are no agents available

### ISSUE THREAD

**Issue by SamiPussinen** [RocketChat/Rocket.Chat#3023]
0.26.0

The customer should be told about missing agents BEFORE he types a message not after the first attempt. Is this possible to be implemented?

**Comment by sampaiodiego** [comment]
Yes, it is possible.

We are thinking on at least two possibilities:
* Do not show the livechat widget if there is no agents online;
* If there is no agent online, show a form to the customer send an email.

What is the expected behavior to you? Thanks

**Comment by SamiPussinen** [comment]
The latter solution sounds better to me, because this way we would get a lead from that customer and they are left with a feeling that somebody will get back to them.

Great project, by the way.

**Comment by insidesmart** [comment]
Second option is present in all live chat tools (like olark) which is very useful for not missing any leads / questions. So my vote also goes to second option.

**Comment by vetash** [comment]
I think there should be third option: 
If no one is online - show message like:
```Sorry, no one is online, send your message for us:
Email: <input>
Message: <input>
<button>Send</button>```
Is it possible? I realy need this feature.

**Comment by vetash** [comment]
`If there is no agent online, show a form to the customer send an email.` - it would be great!
