### ISSUE TITLE
Application Error:The application GUI just crashed.

### ISSUE THREAD

**Issue by liqunxiong** [RocketChat/Rocket.Chat#30264]
version 6.3.3
When switching to the chat window,the above crash error is reported.

**Comment by benedikt-wegmann** [comment]
We have the same issue with another user, the whole web UI crashes and says so in the browser. The report is by the Rocket.Chat UI, *not* by the browser.
Interestingly it was another Chinese user, so perhaps related to character set/fonts/localisation?

**Comment by JuanCasad0** [comment]
Same problem here, since 6.3 and up to 6.3.3. Installed via docker-compose, and upgraded for years without problems until now.

**Comment by benedikt-wegmann** [comment]
@JuanCasad0 I was wrong about suggesting a link to Chinese language settings, we had users with western language settings as well.
What seem to have helped is:

1. In the Admin settings -> General -> Language change the language from "Default" to something explicit, save, then change to the language you want as a default, save again
2. Tell affected users to basically do the same steps in their Account settings for their client's language

**Comment by JuanCasad0** [comment]
Thanks, @benedikt-wegmann . I noticed it affected to admins with spanish language selected. Changing (after trial and error to sort out the crash) that changing all of them to English helped a bit. However, from time to time the crash appears again, which can be "temporarily fixed" by pressing ctrl-R.

**Comment by filefi** [comment]
> We have the same issue with another user, the whole web UI crashes and says so in the browser. The report is by the Rocket.Chat UI, _not_ by the browser. Interestingly it was another Chinese user, so perhaps related to character set/fonts/localisation?

confirmed, I ran into this issue and I'm a Chinese user.
