### ISSUE TITLE
Android App Doesn't connect to my newly created rocketchat server

### ISSUE THREAD

**Issue by marboxvel** [RocketChat/Rocket.Chat#3027]
Rocket.Chat version: 0.26.0
Android app version: 2.3.1
I've installed the RocketChat server on my RPi2 arch arm distribution following this guide https://volumelabs.net/rocket-chat-raspberry-pi-2/ 
I configured apache with reverse proxy so I can access the server through https. By now, I had it working on firefox, windows desktop app and android web browsers. The problem is when I try to connect to the server through the android app, it refuses to load the server page and reply with 'Failed to connect to server: abort. abort'. I'm using self signed certificate for Let's Encrypt requires my public IP to be registered with a domain name and mine is not.
Because I'm using a self signed certificate, I must be asked to authenticate it manually when the server is requested from any application, all my browsers worked fine because they have been instructed to add an exception to that certificate. My android app hasn't even been offered this option and I guess this is where my problem lies. I can't connect to the server because it is not trusted by the app.
Is there a way to fix this guys?

**Comment by netdevfighter** [comment]
The problem is your self-signed certs ... ;)

**Comment by yoimbert** [comment]
same probleme with Android with Let's Encrypt certificate.

**Comment by Sing-Li** [comment]
we do not support self-signed certs

**Comment by yoimbert** [comment]
I m sorry. But with my full certif not working on android. 
Failed to connect to server abort.

**Comment by Sing-Li** [comment]
@yoimbert  that's a different problem.  Someone can help you if you come over to    https://demo.rocket.chat/channel/support

**Comment by marboxvel** [comment]
And can you tell us why you don't support self-signed certs with android app and do support them with browsers?

**Comment by yoimbert** [comment]
I think the self signed there is no CA Intermediate. But I could be wrong. ( let's encrypt for example )

**Comment by marboxvel** [comment]
But they could program the app to work the same as the browsers. If they don't fix the android app to work with self-signed certs, I will have no interest in RocketChat since the android app is all I need.

**Comment by nishishailesh** [comment]
But they could program the app to work the same as the browsers. If they don't fix the android app to work with self-signed certs, I will have no interest in RocketChat since the android app is all I need.

**Comment by ktown007** [comment]
I'm having the same issue with proper certs.

**Comment by Franselbaer** [comment]
The proxy_set settings within location fixed it.

**Comment by cldtech** [comment]
> We do not support self-signed certs. Please re-open if you have full cert and still have problem.

That's not very source friendly!
