### ISSUE TITLE
RC 6.x UI unusable, if RC is installed with url-prefix

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#30272]
### Description:

If Rocket.Chat is installed with an url-prefix eg. https://example.org/rocketchat the generated URL in the UI point to the root (https://example.org/) and not inside the RC container.

So far we found this to be true for the following (relative) urls:
* /channel/&lt;channel-name>
* /group/&lt;group-name>
* /admin/*
* /direct/&lt;user-name>
* /account/*
* /marketplace/*

So if you click on one of these urls, e.g. a channel in the UI, you get a **404 Not Found** from the web-server, as there is no such url.
Obviously the the proxy configuration is correct and RC Settings > General > Website-URL contains the full URL with the prefix.

The situation can bei mitigated by proxying not only /rocketchat into the container, but also /channel, /group, ... into the RC container. Though it leads to a full reload of the UI ending at the correct place, e.g. the cannel you clicked on.

The above behavior is observed in:
* browser (current Chrome and Firefox)
* Electron Desktop client under Mac OS and Windows
* probably the mobile apps too (not yet tested)

The bug is relative urgent, as it blocks the requested update to Rocket.Chat 6.x to continue using RC infrastructure e.g. for push notifications!

### Steps to reproduce:

1. Open the RC URL
2. Log in
3. click e.g. on any channel

### Expected behavior:

The channel should be opened.

### Actual behavior:

Browser displays the 404 Not Found status page, as the (generated) URL does NOT exist.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.3
- Operating System: Linux Host
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.21.3 (as it comes with your 6.3.3 Docker image)
- MongoDB Version: 5.0.20

### Client Setup Information

- Desktop App or Browser Version: Chrome 116.0.5845.140 (Offizieller Build) (x86_64)
- Operating System: Mac OS Monterey

### Additional context

I can provide access to a test-installation via [#Rocket.Chat EGroupware](https://open.rocket.chat/group/rocket-chat-egroupware).

**Comment by geekgonecrazy** [comment]
https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371

We don’t support subdir currently.

**Comment by ralfbecker** [comment]
Unfortunately this is in general not as easy, as it might sound :( 

The forum discussion also contains the [post from Gabriel](https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371/22), saying you rely on the community for testing and fixing subpath issues.

Has this changed now?

I reported and helped fixing the issues in the past and like to continue working on it.

Let me give some context, why this is important for us: EGroupware is groupware which integrates via Docker and mostly OpenIDConnect other projects to cover areas we don't cover ourselves. Rocket.Chat is an example, so it Collabora online or Guacamole and some photo galleries (all but RC support installation in a subpath).
Univention (a Debian based Linux distribution with an integrated directory server and identity provider) also offers Rocket.Chat in a subpath installable via their appstore.

Installing the whole setup in multiple domains, which means multiple proxy configuration, certificated and DNS entry make the whole installation essentially more complex :(

The other alternative is installing RC in the root and the rest with a subpath. But that has the flaw, that every new path RC uses would potentially break an other app or is not usable if the other apps subpath has a higher prio on the proxy.

I'm willing to look into the current issue with 6.x and provide a pull request fixing it, if we have the understanding - as in the past - that it would reviewed and merged in a reasonable time and the official policy stays as before.

Ralf

**Comment by geekgonecrazy** [comment]
I think if a PR was opened fixing it as long as it was clean there wouldn’t be any reason for us not to accept it.  

Just closed as from our perspective it’s not something we will be fixing.
