### ISSUE TITLE
Customize display of role tags

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#3028]
Your Rocket.Chat version: 0.27.0

Each of user's role is displayed as a tag in the chat. This gets quite distracting (and very repetitive). Would be great to have this turn this display on/off.

The workaround in https://github.com/RocketChat/Rocket.Chat/issues/2992 is to remove the description. While that does the trick, the description should not be used to turn off role tags (after all it's the description of the role).

Thanks, am happy to test if it's implemented :-)

**Comment by graywolf336** [comment]
Feature was just added via #3025. :)
