### ISSUE TITLE
Editing readOnly/reactWhenReadOnly are not allowed for broadcast rooms

### ISSUE THREAD

**Issue by dc74089** [RocketChat/Rocket.Chat#30288]
### Description:

An error is thrown when trying to set a broadcast channel as default through Workspace Admin -> Channels

### Steps to reproduce:

1. Create a new broadcast channel
2. Visit Workspace administration
3. Click Rooms on the left sidebar
4. Click on the newly created broadcast channel
5. Toggle "Default" to on
6. Attempt to save the channel
7. Observe the error message (`Editing readOnly/reactWhenReadOnly are not allowed for broadcast rooms [error-action-not-allowed]`) 

### Expected behavior:

No error will be generated, and the channel will be set as a default channel

### Actual behavior:

An error is thrown, and the channel is not saved (and consequently not marked as a default channel)

<img width="1470" alt="Screenshot 2023-09-05 at 12 51 19" src="https://github.com/RocketChat/Rocket.Chat/assets/5996485/506cce8d-460c-4500-9d63-6a204e06b4ea">

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.3
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.9 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Browser; Chrome 116.0.5845.140
- Operating System: MacOS

### Additional context

N/A

### Relevant logs:

No relevant logs are produced.

**Comment by Ninad3721** [comment]
@dc74089 are you sure that this error should not occur, or there is some mistake with the error message ?

**Comment by dc74089** [comment]
Yes, I'm pretty sure the error should not occur. I have seen nothing in the documentation suggesting that Broadcast channels cannot be default channels. 

The default toggle is the only setting I am attempting to change. The error relates to reactions.

**Comment by Ninad3721** [comment]
okay I will look into this

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest version and it was fixed here: #30907

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
