### ISSUE TITLE
E2E-password popup shows %s instead of the password

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#30298]
### Description:

This is a localization issue at least with the Finnish localization. At least English, Spanish and Norwegian are ok.

In the popup that opens from the banner, instead of the newly created E2E-password, you are shown a variable name `%s`.

### Steps to reproduce:

1. Switch your language to `Finnish` under user's personal settings
2. Reset the existing E2E-password under the personal settings
3. After logging back in click the E2E-banner

### Expected behavior:

You are shown your newly created E2E-password.

### Actual behavior:

Instead of the E2E-password you see only `%s`.

![Screenshot from 2023-09-06 09-37-58](https://github.com/RocketChat/Rocket.Chat/assets/6958942/986f1fa0-7dbe-4455-9b35-2e7ddd369634)

The `Copy password` button works and copies a working E2E-password so the issue is only visual and probably a typo in the localization files.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.3
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Any browser

**Comment by milton-rucks** [comment]
Resolved in 6.8
