### ISSUE TITLE
Buen día

### ISSUE THREAD

**Issue by BeckHurry** [RocketChat/Rocket.Chat#30307]
No puedo usar mi rocket, ni web, ni desktop, ni móvil, porque me aparece la leyenda "Application Error
The application GUI just crashed." y todo en blanco, llevo 7 días sin poder usarlo; necesito realmente que me apoyen con ello.

**Comment by HMSodep** [comment]
Mira el #30097

**Comment by MartinSchoeler** [comment]
Should be fixed by https://github.com/RocketChat/Rocket.Chat/pull/30167
