### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [RocketChat/Rocket.Chat#30325]
### Description:
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

### Steps to reproduce:
Scroll to bottom and see twitter old logo

### Expected behavior:
Twitter logo should be changed to X

### ScreenShot:

<img width="960" alt="Screenshot 2023-09-08 153950" src="https://github.com/RocketChat/Rocket.Chat/assets/91591901/0018c3e7-e802-4114-8c3d-78e63e0ce1a0">

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context
@jwilkins 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by Ayush-Vish** [comment]
I am working on this issue

**Comment by Swagat47** [comment]
I would like to work on this issue.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project, the website is build in house

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
