### ISSUE TITLE
Update the "Mobile Notifications Gateway Configuration" docs

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#3033]
Android
To configure mobile notifications using the rocket.chat gateway:

Go to https://console.developers.google.com/ and create a project there.
Go to API Manager, and enable “Google Cloud Messaging for Android”
In API Manager, open the “Credentials” tab, click 'New credentials -> API key. In the window that pops up, choose “Server key”
Fill in the correct IP address from your server and Click “Create”
Fill in the obtained API key in your rocketchat administrator panel (GCM API Key)
The GCM Project Number which you also have to fill in on rocketchat can be found on the dashboard of your Google developers project, first block that shows up . (https://console.developers.google.com/home/dashboard, http://i.imgur.com/3DXHEKy.png)
In Rocket.Chat.Cordova  
Fill in GCM Project Number in the file www/shared/js/android_sender.js , replace "YOUR-ANDROID-ID-HERE" with your GCM Project Number

iOS
For iOS you need an apple developer account that costs 99$ per year. Follow instructions here: https://github.com/raix/push/blob/v3.x/docs/IOS.md

Rocket.Chat
Go to Administration=>Push 
Set the Enable Gateway to False, then you will use your own rocketchat as gateway instead of the https://rocket.chat server
Restart server 

Now you should be able to Send a test message. Make sure that you have logged in to the server once. And then closed the app. You should see a test notitication after you pressed the send button

**Comment by lucasvanhalst** [comment]
Actually I was mistaken, when using the gateway (and rocketchat app from the appstore/playstore) you don't need to do any of this and it should work by just turning push notifications on.

**Comment by lunitic** [comment]
This is what you need to do if you compile an own client.

**Comment by lunitic** [comment]
Your instruction worked to 95% :)

**Comment by marceloschmidt** [comment]
Would you be so kind and create a PR for us in https://github.com/RocketChat/Rocket.Chat.Docs/ ? That would be great! Thanks!

**Comment by lunitic** [comment]
@marceloschmidt I fix. didn't know where to fix it myself..

**Comment by MartinSchoeler** [comment]
Please reopen this in https://github.com/RocketChat/docs/
