### ISSUE TITLE
Send message from command line

### ISSUE THREAD

**Issue by iojeda** [RocketChat/Rocket.Chat#3034]
Hi Im writing here cause i dont know any better place to do it, please if this is not the place tell me where to post this question.

I want to send notifications to Rocket.Chat channels from a computer shell command line with a xmpp client or something like that.
How can I accomplish this? I mean... what protocol or way of connection do I have available in Rocket.Chat to do that? It's xmpp or any other available?

Thanks in advance.

**Comment by bt** [comment]
I would suggest you create a new integration, then using something like cURL to make the request.

From **Administration > Integrations**

Create a new **Incoming Webhook**

Fill in the information, and at the end, it should give you an example cURL command line.

**Comment by iojeda** [comment]
Thank you very much for your kind help. This was of great help and solved the issue.

**Comment by zerOnepal** [comment]
any quick examples on the the `curl` `url` and `params` ? @bt @iojeda

**Comment by bt** [comment]
Go to your Rocket.Chat instance, login as an administrator and then click your username on the top right and choose **Administration**:

![1](https://cloud.githubusercontent.com/assets/1100843/20955398/1e7f37ee-bc97-11e6-8114-6d0e259f9674.jpg)

In the Administration menu, choose **Integrations**:

![2](https://cloud.githubusercontent.com/assets/1100843/20955414/3cb365e6-bc97-11e6-9f37-78413aae3f06.jpg)

Create a **New Integration**:

![3](https://cloud.githubusercontent.com/assets/1100843/20955423/48bb61c2-bc97-11e6-8eb9-9b7ea672b17e.jpg)

You want to send messages to Rocket.Chat via cURL, so choose **Incoming WebHook**:

![4](https://cloud.githubusercontent.com/assets/1100843/20955445/5b60cb0a-bc97-11e6-962e-389236a1ee13.jpg)

Fill in the details as requested:

![5](https://cloud.githubusercontent.com/assets/1100843/20955447/64d2b9b4-bc97-11e6-95f1-0df14c16e8bb.png)

Save your changes:

![6](https://cloud.githubusercontent.com/assets/1100843/20955450/6a0f7bc4-bc97-11e6-8db6-4f89a867f51e.jpg)

Under **Example** box, you should suddenly get a cURL example:

![7](https://cloud.githubusercontent.com/assets/1100843/20955463/7cc5b4d6-bc97-11e6-84a4-77bffe1d0f78.png)

@zerOnepal

**Comment by zerOnepal** [comment]
thanks for quick ride @bt
but one more problem i have... How do i send multi-lines message using the `curl` 😞  

my case here, involves **"machine generated multiple line text messages"** not just  `"text":"Example message"` 

thanks for the example, i am not the admin but now I know the process 😉 
![example](https://cloud.githubusercontent.com/assets/1100843/20955463/7cc5b4d6-bc97-11e6-84a4-77bffe1d0f78.png)

**Comment by bt** [comment]
@zerOnepal I guess the admin just needs to give you a token with permissions to write to a channel.

I believe text is actually **HTML-based** (I might be wrong though).

Try something like:
```
"text": "Multi-line<br />Text"
```
and see if it works! 😄

**Comment by zerOnepal** [comment]
hey check this out, one stop solution to :allthethings: 
 https://github.com/course-hero/slacktee

**Comment by javanux** [comment]
Thank you @bt  @thapakazi  that was helpful. 🚀
