### ISSUE TITLE
Uncaught ReferenceError: Weglot is not defined     at (index):408:1

### ISSUE THREAD

**Issue by zkhan90** [RocketChat/Rocket.Chat#30352]
I don't know much about Codebase and about the error but 
I was using the application and found this error in Console.
 
![Screenshot 2023-09-11 233147](https://github.com/RocketChat/Rocket.Chat/assets/141441878/aab81dc1-b37e-49c0-9c31-c3f85d3da059)

**Comment by zkhan90** [comment]
![Screenshot 2023-09-11 233741](https://github.com/RocketChat/Rocket.Chat/assets/141441878/f5cfde66-91c2-44e1-ac44-388682a198e4)

**Comment by Dnouv** [comment]
Hi there, thanks for raising the issue! 🚀 💯

Sorry, but GitHub is only for issues/bugs related to the repository project; the website is built in-house.

--- 
Questions? Help needed? Feature Requests?

Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
