### ISSUE TITLE
Code blocks deletes first word if without space

### ISSUE THREAD

**Issue by bt** [RocketChat/Rocket.Chat#3035]
Your Rocket.Chat version: 0.27.0

Hey guys,

Just have a minor bug in which, when I post a code block like such:

![screen shot 2016-04-27 at 12 56 22 am](https://cloud.githubusercontent.com/assets/1100843/14822680/e4b79176-0c12-11e6-8e26-1795b535fccb.png)

The chat message sent only shows the following:

![screen shot 2016-04-27 at 12 55 16 am](https://cloud.githubusercontent.com/assets/1100843/14822642/c8d3d988-0c12-11e6-8545-5df52d8fa0e4.png)

However, when I post a code block with a space:

![screen shot 2016-04-27 at 12 56 10 am](https://cloud.githubusercontent.com/assets/1100843/14822685/e91c650c-0c12-11e6-8779-1c45dd015f1c.png)

Then the chat message shows the full code block:

![screen shot 2016-04-27 at 12 55 12 am](https://cloud.githubusercontent.com/assets/1100843/14822637/c2e76350-0c12-11e6-9c42-9b8f80909c6d.png)

Is this a minor bug?

**Comment by bt** [comment]
Just noticed it happens on any word that is directly after the quotes.

**Comment by graywolf336** [comment]
It expects the first word to be the language of the code being posted.

**Comment by bt** [comment]
Oh is that so?

I wonder if there would be a way to make it guess intelligently?

**Comment by lucasvanhalst** [comment]
It's like that on almost all services who implement this kind of markdown (for example here on github as well), so I would not change that behaviour.

**Comment by bt** [comment]
Sorry for the late reply.

So on GitHub, using the same example would yield the following:

```
var c = 1;
var a = c + 10;
console.log(a);
```

Compared to if I prefix it with `javascript` then it will perform syntax highlighting, like so:

```javascript
var c = 1;
var a = c + 10;
console.log(a);```

Should we implement the same behaviour (ie. put it into a block without highlighting if the language is unknown)?

I can provide a PR for this. Please discuss.

**Comment by marceloschmidt** [comment]
Github will not render if it's in the same line...

```var c = 1;
var a = c + 10;
console.log(a);
```

But if you want to make a PR that will accept this as 
```
var c = 1;
var a = c + 10;
console.log(a);
```
and identify if the first word is a language, it would be great...
