### ISSUE TITLE
Chat Input area border an aggressive blue after update beyond 5.x to 6.x

### ISSUE THREAD

**Issue by thrakks** [RocketChat/Rocket.Chat#30374]
### Description:

Finally was able to convince my users to stop using HTML tables in chat incoming integrations so could update beyond the 5.x version I was on. Now they're complaining that the Chat input area when in focus has a very intense blue border that they find annoying. I'm show my ignorance here but how do I specifically edit or remove that using Custom CSS? :focus / :focus-visible do nothing.

### Steps to reproduce:

1. Be on a version 6.x
2. Click on chat input
3. Border is intensely blue

### Expected behavior:

This is likely expected behaviour, just would like to remove or customise it.

### Actual behavior:

Likely my ignorance, but can't intuitively edit or customise using Custom CSS

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.4
- Operating System: Oracle Linux 9.1
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: as per docker
- NodeJS Version: as per docker
- MongoDB Version: as per docker

### Client Setup Information

- Desktop App or Browser Version: Multiple (chrome/ firefox etc.)
- Operating System: (Windows / MacBook etc.)

### Additional context

Very sorry if this is a waste of time.

**Comment by Dnouv** [comment]
Hey @thrakks 

Thank you so much for opening the issue. You can easily customize the color to the one you feel comfortable with; here is an example of how to modify the CSS of Focus (To customize colors, navigate to **Administration > Workspace > Settings > Layout > Custom CSS**):
```
.rcx-content--main {
  --rcx-input-colors-focus-border-color: #ffff00;
  --rcx-color-shadow-highlight: #ffff00
}
```
![image](https://github.com/RocketChat/Rocket.Chat/assets/61188295/ce27a45a-c2c6-4818-af17-109d7471643a)

After doing the above, you get something like the below image (but please notice, this will apply to any focused element; for example, inside the Admin settings, if you click on the `Search` element, it will also appear the same color):
![image](https://github.com/RocketChat/Rocket.Chat/assets/61188295/8f03912d-efa6-47d5-bce0-6c4ac32bcd4f)

--- 
Questions? Help needed? Feature Requests?

Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
For more overrides [Customizing Colors](https://developer.rocket.chat/customize-and-embed/white-labelling/customizing-colors)
Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by thrakks** [comment]
> Hey @thrakks
> 
> Thank you so much for opening the issue. You can easily customize the color to the one you feel comfortable with; here is an example of how to modify the CSS of Focus (To customize colors, navigate to **Administration > Workspace > Settings > Layout > Custom CSS**):
> 
> ```
> .rcx-content--main {
>   --rcx-input-colors-focus-border-color: #ffff00;
>   --rcx-color-shadow-highlight: #ffff00
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/61188295/267983613-ce27a45a-c2c6-4818-af17-109d7471643a.png)
> 
> After doing the above, you get something like the below image (but please notice, this will apply to any focused element; for example, inside the Admin settings, if you click on the `Search` element, it will also appear the same color): ![image](https://user-images.githubusercontent.com/61188295/267983151-8f03912d-efa6-47d5-bce0-6c4ac32bcd4f.png)
> 
> Questions? Help needed? Feature Requests?
> 
> Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there For more overrides [Customizing Colors](https://developer.rocket.chat/customize-and-embed/white-labelling/customizing-colors) Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

You are my hero. I had spent ages with Inspector up trying to determine the right combination of classes and clearly I just wasn't even close. Thank you so much.
