### ISSUE TITLE
[Enhancement]  Social Media Icons Alignment on Website

### ISSUE THREAD

**Issue by VivekBaldha0712** [RocketChat/Rocket.Chat#30377]
Problem:
The social media icons on our website are currently vertically aligned, and they should be displayed horizontally for a better user experience and a more aesthetically pleasing layout.

Expected Behavior:
The social media icons should be horizontally aligned in the footer of the website, as is the standard practice on most websites.

Current Behavior:
Currently, the icons are stacked vertically, which not only looks less visually appealing but also affects the overall layout and alignment of our website.
<img width="173" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/86009821/6f53154e-14d2-418f-b707-6da5716938c4">

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue.

**Comment by KSSaiTeja** [comment]
i have prior knowledge about this can i raise a PR regarding this issue

**Comment by Dnouv** [comment]
Hey @VivekBaldha0712 

Thank you so much for bringing this UX addition to our attention. However, this repository is specifically for the `Rocket.Chat` application, and the webpage you mentioned isn’t open source. We recommend setting up the server according to the [developer documentation](https://developer.rocket.chat/getting-started/development-environment-setup) or visiting & signing up [Open Server](https://open.rocket.chat) to better understand. 

We appreciate your understanding. Thank you!
