### ISSUE TITLE
"yarn dev" gives errors, can't test locally

### ISSUE THREAD

**Issue by mitaka009** [RocketChat/Rocket.Chat#30416]
### Description:
- i have installed node and using `nvm use 14.21.3`
- i have installed yarn, `npm i -g yarn`
- i have installed meteor js, ` npm i -g meteor@2.12`
- cloned the repo, did a `yarn install`
- then did a `yarn dev`, it fails 

### Client Setup Information

- Desktop App or Browser Version: firefox
- Operating System: Linux ( xubunut )

### Relevant logs:

![error](https://github.com/RocketChat/Rocket.Chat/assets/145256821/5b8de004-a7cb-4911-963d-dc9bd551e4b6)

@rocket.chat/sha256:dev:
@rocket.chat/sha256:dev: 2:05:37 pm - Found 0 errors. Watching for file changes.
@rocket.chat/models:dev: src/index.ts(81,8): error TS2307: Cannot find module '@rocket.chat/model-typings' or its corresponding type declarations.
@rocket.chat/models:dev: src/proxify.ts(1,33): error TS2307: Cannot find module '@rocket.chat/model-typings' or its corresponding type declarations.
@rocket.chat/models:dev:
@rocket.chat/models:dev: 2:05:37 pm - Found 2 errors. Watching for file changes.
@rocket.chat/random:dev:
@rocket.chat/random:dev: 2:05:37 pm - Found 0 errors. Watching for file changes.
@rocket.chat/log-format:dev:
@rocket.chat/log-format:dev: 2:05:37 pm - Found 0 errors. Watching for file changes.
@rocket.chat/base64:dev:
@rocket.chat/base64:dev: 2:05:37 pm - Found 0 errors. Watching for file changes.
@rocket.chat/favicon:dev:
@rocket.chat/favicon:dev: 2:05:38 pm - Found 0 errors. Watching for file changes.
@rocket.chat/password-policies:dev:
@rocket.chat/password-policies:dev: 2:05:38 pm - Found 0 errors. Watching for file changes.
@rocket.chat/account-utils:dev:
@rocket.chat/account-utils:dev: 2:05:38 pm - Found 0 errors. Watching for file changes.
@rocket.chat/meteor:dev: => Started MongoDB.
@rocket.chat/instance-status:dev: src/index.ts(21,19): error TS7006: Parameter 'result' implicitly has an 'any' type.
@rocket.chat/instance-status:dev: src/index.ts(22,33): error TS7006: Parameter 'index' implicitly has an 'any' type.
@rocket.chat/instance-status:dev: src/index.ts(33,19): error TS7006: Parameter 'created' implicitly has an 'any' type.
@rocket.chat/instance-status:dev:
@rocket.chat/instance-status:dev: 2:05:38 pm - Found 3 errors. Watching for file changes.
@rocket.chat/cas-validate:dev:
@rocket.chat/cas-validate:dev: 2:05:38 pm - Found 0 errors. Watching for file changes.
@rocket.chat/cron:dev: src/index.ts(1,24): error TS2307: Cannot find module '@rocket.chat/agenda' or its corresponding type declarations.
@rocket.chat/cron:dev:
@rocket.chat/cron:dev: 2:05:39 pm - Found 1 error. Watching for file changes.
@rocket.chat/server-fetch:dev:
@rocket.chat/server-fetch:dev: 2:05:39 pm - Found 0 errors. Watching for file changes.
@rocket.chat/logger:dev:
@rocket.chat/logger:dev: 2:05:39 pm - Found 0 errors. Watching for file changes.
@rocket.chat/core-typings:dev: ERROR: command finished with error: command (/home/amitanshu/Desktop/Rocket.Chat/packages/core-typings) yarn run dev exited (129)
@rocket.chat/core-typings#dev: command (/home/amitanshu/Desktop/Rocket.Chat/packages/core-typings) yarn run dev exited (129)

 Tasks:    0 successful, 31 total
Cached:    0 cached, 31 total
  Time:    48.663s
Failed:    @rocket.chat/core-typings#dev

 ERROR  run failed: command  exited (129)

**Comment by just4kick** [comment]
I followed all the steps mentioned [here: Setting up a Development Environment in Linux](https://developer.rocket.chat/open-source-projects/server/server-environment-setup/linux) but encountered an error.
### local environment
Ubuntu 22.04.3 LTS


## terminal log
@rocket.chat/meteor:dsv: [[[[[ /media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor ]]]]]
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: => Started proxy.
@rocket.chat/meteor:dsv: /home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
@rocket.chat/meteor:dsv:       throw error;
@rocket.chat/meteor:dsv:       ^
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: Error: EISDIR: illegal operation on a directory, read
@rocket.chat/meteor:dsv:     at Object.readSync (fs.js:618:3)
@rocket.chat/meteor:dsv:     at Object.readSync (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:143:28)
@rocket.chat/meteor:dsv:     at tryReadSync (fs.js:383:20)
@rocket.chat/meteor:dsv:     at Object.readFileSync (fs.js:420:19)
@rocket.chat/meteor:dsv:     at /home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1522:23
@rocket.chat/meteor:dsv:     at wrap.makeCacheKey (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:36:15)
@rocket.chat/meteor:dsv:     at recomputeNewValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:198:31)
@rocket.chat/meteor:dsv:     at Slot.withValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
@rocket.chat/meteor:dsv:     at reallyRecompute (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:181:19)
@rocket.chat/meteor:dsv:     at Entry.recompute (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:91:9)
@rocket.chat/meteor:dsv:     at optimistic (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:150:25)
@rocket.chat/meteor:dsv:     at /tools/isobuild/compiler.js:483:22
@rocket.chat/meteor:dsv:     at Array.forEach (<anonymous>)
@rocket.chat/meteor:dsv:     at /tools/isobuild/compiler.js:478:20
@rocket.chat/meteor:dsv:     at /tools/isobuild/compiler.js:186:28
@rocket.chat/meteor:dsv:     at Object.withCache (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:18)
@rocket.chat/meteor:dsv:     at /tools/isobuild/compiler.js:185:11
@rocket.chat/meteor:dsv:     at Function.each (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
@rocket.chat/meteor:dsv:     at Object.compile (/tools/isobuild/compiler.js:180:5)
@rocket.chat/meteor:dsv:     at /tools/isobuild/bundler.js:3316:24
@rocket.chat/meteor:dsv:     at Object.capture (/tools/utils/buildmessage.js:283:5)
@rocket.chat/meteor:dsv:     at bundle (/tools/isobuild/bundler.js:3262:31)
@rocket.chat/meteor:dsv:     at /tools/isobuild/bundler.js:3205:32
@rocket.chat/meteor:dsv:     at Slot.withValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
@rocket.chat/meteor:dsv:     at Object.withCache (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:39)
@rocket.chat/meteor:dsv:     at Object.bundle (/tools/isobuild/bundler.js:3205:16)
@rocket.chat/meteor:dsv:     at /tools/runners/run-app.js:579:24
@rocket.chat/meteor:dsv:     at Function.run (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
@rocket.chat/meteor:dsv:     at bundleApp (/tools/runners/run-app.js:578:34)
@rocket.chat/meteor:dsv:     at AppRunner._runOnce (/tools/runners/run-app.js:625:35)
@rocket.chat/meteor:dsv:     at AppRunner._fiber (/tools/runners/run-app.js:947:28)
@rocket.chat/meteor:dsv:     at /tools/runners/run-app.js:408:12 {
@rocket.chat/meteor:dsv:   errno: -21,
@rocket.chat/meteor:dsv:   syscall: 'read',
@rocket.chat/meteor:dsv:   code: 'EISDIR'
@rocket.chat/meteor:dsv: }
@rocket.chat/meteor:dsv: npm ERR! code ELIFECYCLE
@rocket.chat/meteor:dsv: npm ERR! errno 1
@rocket.chat/meteor:dsv: npm ERR! @rocket.chat/meteor@6.5.0-develop dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"`
@rocket.chat/meteor:dsv: npm ERR! Exit status 1
@rocket.chat/meteor:dsv: npm ERR! 
@rocket.chat/meteor:dsv: npm ERR! Failed at the @rocket.chat/meteor@6.5.0-develop dev script.
@rocket.chat/meteor:dsv: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: npm ERR! A complete log of this run can be found in:
@rocket.chat/meteor:dsv: npm ERR!     /home/sumit/.npm/_logs/2023-09-17T12_01_29_691Z-debug.log
@rocket.chat/meteor:dsv: ERROR: command finished with error: command (/media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor) yarn run dsv exited (1)
@rocket.chat/meteor#dsv: command (/media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor) yarn run dsv exited (1)

 Tasks:    35 successful, 36 total
Cached:    33 cached, 36 total
  Time:    11.66s 
Failed:    @rocket.chat/meteor#dsv

 ERROR  run failed: command  exited (1)

**Comment by theslowdeveloper** [comment]
use `yarn dsv` instead

**Comment by just4kick** [comment]
@theslowdeveloper i did use ```yarn dsv``` but didn't work and terminal logs is below

> I followed all the steps mentioned [here: Setting up a Development Environment in Linux](https://developer.rocket.chat/open-source-projects/server/server-environment-setup/linux) but encountered an error.
> 
> ### local environment
> Ubuntu 22.04.3 LTS
> 
> ## terminal log
> @rocket.chat/meteor:dsv: [[[[[ /media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor ]]]]] @rocket.chat/meteor:dsv: @rocket.chat/meteor:dsv: => Started proxy. @rocket.chat/meteor:dsv: /home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218 @rocket.chat/meteor:dsv: throw error; @rocket.chat/meteor:dsv: ^ @rocket.chat/meteor:dsv: @rocket.chat/meteor:dsv: Error: EISDIR: illegal operation on a directory, read @rocket.chat/meteor:dsv: at Object.readSync (fs.js:618:3) @rocket.chat/meteor:dsv: at Object.readSync (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:143:28) @rocket.chat/meteor:dsv: at tryReadSync (fs.js:383:20) @rocket.chat/meteor:dsv: at Object.readFileSync (fs.js:420:19) @rocket.chat/meteor:dsv: at /home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1522:23 @rocket.chat/meteor:dsv: at wrap.makeCacheKey (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:36:15) @rocket.chat/meteor:dsv: at recomputeNewValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:198:31) @rocket.chat/meteor:dsv: at Slot.withValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29) @rocket.chat/meteor:dsv: at reallyRecompute (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:181:19) @rocket.chat/meteor:dsv: at Entry.recompute (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:91:9) @rocket.chat/meteor:dsv: at optimistic (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:150:25) @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:483:22 @rocket.chat/meteor:dsv: at Array.forEach () @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:478:20 @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:186:28 @rocket.chat/meteor:dsv: at Object.withCache (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:18) @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:185:11 @rocket.chat/meteor:dsv: at Function.each (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7) @rocket.chat/meteor:dsv: at Object.compile (/tools/isobuild/compiler.js:180:5) @rocket.chat/meteor:dsv: at /tools/isobuild/bundler.js:3316:24 @rocket.chat/meteor:dsv: at Object.capture (/tools/utils/buildmessage.js:283:5) @rocket.chat/meteor:dsv: at bundle (/tools/isobuild/bundler.js:3262:31) @rocket.chat/meteor:dsv: at /tools/isobuild/bundler.js:3205:32 @rocket.chat/meteor:dsv: at Slot.withValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29) @rocket.chat/meteor:dsv: at Object.withCache (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:39) @rocket.chat/meteor:dsv: at Object.bundle (/tools/isobuild/bundler.js:3205:16) @rocket.chat/meteor:dsv: at /tools/runners/run-app.js:579:24 @rocket.chat/meteor:dsv: at Function.run (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14) @rocket.chat/meteor:dsv: at bundleApp (/tools/runners/run-app.js:578:34) @rocket.chat/meteor:dsv: at AppRunner._runOnce (/tools/runners/run-app.js:625:35) @rocket.chat/meteor:dsv: at AppRunner._fiber (/tools/runners/run-app.js:947:28) @rocket.chat/meteor:dsv: at /tools/runners/run-app.js:408:12 { @rocket.chat/meteor:dsv: errno: -21, @rocket.chat/meteor:dsv: syscall: 'read', @rocket.chat/meteor:dsv: code: 'EISDIR' @rocket.chat/meteor:dsv: } @rocket.chat/meteor:dsv: npm ERR! code ELIFECYCLE @rocket.chat/meteor:dsv: npm ERR! errno 1 @rocket.chat/meteor:dsv: npm ERR! @rocket.chat/[meteor@6.5.0-develop](mailto:meteor@6.5.0-develop) dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"` @rocket.chat/meteor:dsv: npm ERR! Exit status 1 @rocket.chat/meteor:dsv: npm ERR! @rocket.chat/meteor:dsv: npm ERR! Failed at the @rocket.chat/[meteor@6.5.0-develop](mailto:meteor@6.5.0-develop) dev script. @rocket.chat/meteor:dsv: npm ERR! This is probably not a problem with npm. There is likely additional logging output above. @rocket.chat/meteor:dsv: @rocket.chat/meteor:dsv: npm ERR! A complete log of this run can be found in: @rocket.chat/meteor:dsv: npm ERR! /home/sumit/.npm/_logs/2023-09-17T12_01_29_691Z-debug.log @rocket.chat/meteor:dsv: ERROR: command finished with error: command (/media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor) yarn run dsv exited (1) @rocket.chat/meteor#dsv: command (/media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor) yarn run dsv exited (1)
> 
> Tasks: 35 successful, 36 total Cached: 33 cached, 36 total Time: 11.66s Failed: @rocket.chat/meteor#dsv
> 
> ERROR run failed: command exited (1)

**Comment by brf153** [comment]
I am also not being able to set up Rocket.Chat for development purposes in my system. My issue is regarding the installation of packages using the command `yarn` . I am using yarn version 3.2.2, node version 14.21.3 , nvm version 0.39.4 and ubuntu os 22.04. I attaching a screenshot for the issue.
![Screenshot from 2023-09-17 19-48-48](https://github.com/RocketChat/Rocket.Chat/assets/107868772/2a2b1563-ec1f-44d8-bb35-fb80c9414309)

**Comment by cuixiaotu** [comment]
> I am also not being able to set up Rocket.Chat for development purposes in my system. My issue is regarding the installation of packages using the command `yarn` . I am using yarn version 3.2.2, node version 14.21.3 , nvm version 0.39.4 and ubuntu os 22.04. I attaching a screenshot for the issue.我也无法在我的系统中设置 Rocket.Chat 进行开发。我的问题是关于使用命令 `yarn` 安装软件包。我使用的是yarn版本3.2.2、node版本14.21.3、nvm版本0.39.4和ubuntu操作系统22.04。我附上该问题的屏幕截图。 ![Screenshot from 2023-09-17 19-48-48](https://user-images.githubusercontent.com/107868772/268563677-2a2b1563-ec1f-44d8-bb35-fb80c9414309.png)
> 
> After this, `yarn dev` fails to start the server stating `ERROR run failed: Package tasks (<package>#<task>) are not allowed in single-package repositories: found @rocket.chat/ui-contexts#build Turbo error: Package tasks (<package>#<task>) are not allowed in single-package repositories: found @rocket.chat/ui-contexts#build`此后， `yarn dev` 无法启动服务器，并提示 `ERROR run failed: Package tasks (<package>#<task>) are not allowed in single-package repositories: found @rocket.chat/ui-contexts#build Turbo error: Package tasks (<package>#<task>) are not allowed in single-package repositories: found @rocket.chat/ui-contexts#build`

You can use volta or check yarn version and then try yarn again.
![image](https://github.com/RocketChat/Rocket.Chat/assets/22334267/ef1f74b4-c2eb-40b0-b133-4d5c1030117a)

**Comment by MayurAnklekar** [comment]
Did yarn `install work` without any errors?

**Comment by JOSHIK27** [comment]
even iam facing the same issue in setting. yarn dev is failing for a case among 38 cases. I also tried yarn dsv

**Comment by ManojaD2004** [comment]
I am also getting the same error. Someone please help.

**Comment by ManojaD2004** [comment]
> @theslowdeveloper i did use `yarn dsv` but didn't work and terminal logs is below
> 
> > I followed all the steps mentioned [here: Setting up a Development Environment in Linux](https://developer.rocket.chat/open-source-projects/server/server-environment-setup/linux) but encountered an error.
> > ### local environment
> > Ubuntu 22.04.3 LTS
> > ## terminal log
> > @rocket.chat/meteor:dsv: [[[[[ /media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor ]]]]] @rocket.chat/meteor:dsv: @rocket.chat/meteor:dsv: => Started proxy. @rocket.chat/meteor:dsv: /home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218 @rocket.chat/meteor:dsv: throw error; @rocket.chat/meteor:dsv: ^ @rocket.chat/meteor:dsv: @rocket.chat/meteor:dsv: Error: EISDIR: illegal operation on a directory, read @rocket.chat/meteor:dsv: at Object.readSync (fs.js:618:3) @rocket.chat/meteor:dsv: at Object.readSync (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:143:28) @rocket.chat/meteor:dsv: at tryReadSync (fs.js:383:20) @rocket.chat/meteor:dsv: at Object.readFileSync (fs.js:420:19) @rocket.chat/meteor:dsv: at /home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1522:23 @rocket.chat/meteor:dsv: at wrap.makeCacheKey (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:36:15) @rocket.chat/meteor:dsv: at recomputeNewValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:198:31) @rocket.chat/meteor:dsv: at Slot.withValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29) @rocket.chat/meteor:dsv: at reallyRecompute (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:181:19) @rocket.chat/meteor:dsv: at Entry.recompute (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:91:9) @rocket.chat/meteor:dsv: at optimistic (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:150:25) @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:483:22 @rocket.chat/meteor:dsv: at Array.forEach () @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:478:20 @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:186:28 @rocket.chat/meteor:dsv: at Object.withCache (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:18) @rocket.chat/meteor:dsv: at /tools/isobuild/compiler.js:185:11 @rocket.chat/meteor:dsv: at Function.each (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7) @rocket.chat/meteor:dsv: at Object.compile (/tools/isobuild/compiler.js:180:5) @rocket.chat/meteor:dsv: at /tools/isobuild/bundler.js:3316:24 @rocket.chat/meteor:dsv: at Object.capture (/tools/utils/buildmessage.js:283:5) @rocket.chat/meteor:dsv: at bundle (/tools/isobuild/bundler.js:3262:31) @rocket.chat/meteor:dsv: at /tools/isobuild/bundler.js:3205:32 @rocket.chat/meteor:dsv: at Slot.withValue (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29) @rocket.chat/meteor:dsv: at Object.withCache (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:39) @rocket.chat/meteor:dsv: at Object.bundle (/tools/isobuild/bundler.js:3205:16) @rocket.chat/meteor:dsv: at /tools/runners/run-app.js:579:24 @rocket.chat/meteor:dsv: at Function.run (/home/sumit/.meteor/packages/meteor-tool/.2.12.0.1q3zjvj.962u++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14) @rocket.chat/meteor:dsv: at bundleApp (/tools/runners/run-app.js:578:34) @rocket.chat/meteor:dsv: at AppRunner._runOnce (/tools/runners/run-app.js:625:35) @rocket.chat/meteor:dsv: at AppRunner._fiber (/tools/runners/run-app.js:947:28) @rocket.chat/meteor:dsv: at /tools/runners/run-app.js:408:12 { @rocket.chat/meteor:dsv: errno: -21, @rocket.chat/meteor:dsv: syscall: 'read', @rocket.chat/meteor:dsv: code: 'EISDIR' @rocket.chat/meteor:dsv: } @rocket.chat/meteor:dsv: npm ERR! code ELIFECYCLE @rocket.chat/meteor:dsv: npm ERR! errno 1 @rocket.chat/meteor:dsv: npm ERR! @rocket.chat/[meteor@6.5.0-develop](mailto:meteor@6.5.0-develop) dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"` @rocket.chat/meteor:dsv: npm ERR! Exit status 1 @rocket.chat/meteor:dsv: npm ERR! @rocket.chat/meteor:dsv: npm ERR! Failed at the @rocket.chat/[meteor@6.5.0-develop](mailto:meteor@6.5.0-develop) dev script. @rocket.chat/meteor:dsv: npm ERR! This is probably not a problem with npm. There is likely additional logging output above. @rocket.chat/meteor:dsv: @rocket.chat/meteor:dsv: npm ERR! A complete log of this run can be found in: @rocket.chat/meteor:dsv: npm ERR! /home/sumit/.npm/_logs/2023-09-17T12_01_29_691Z-debug.log @rocket.chat/meteor:dsv: ERROR: command finished with error: command (/media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor) yarn run dsv exited (1) @rocket.chat/meteor#dsv: command (/media/sumit/Media/gateway/gitclone/rocket/Rocket.Chat/apps/meteor) yarn run dsv exited (1)
> > Tasks: 35 successful, 36 total Cached: 33 cached, 36 total Time: 11.66s Failed: @rocket.chat/meteor#dsv
> > ERROR run failed: command exited (1)

Getting the same error

**Comment by ManojaD2004** [comment]
Hey all! I found the solution! Run `yarn add deasync` then run `yarn dsv` ! This worked for me!!

**Comment by skushagra9** [comment]
run `sudo apt install g++ build-essential git curl python2-minimal` and then run `yarn dsv`
make sure node version is 14.21.3

It should work

**Comment by usersdfg** [comment]
Anyone completely setup the code then give me complete commands to run it

**Comment by Raj-Mandal-20** [comment]
does anyone get the solution?

**Comment by manishks2901** [comment]
Hello guys , I across this problem which is now solved 

1.)brew install g++ git curl python@2
2.)brew install png++ 
3.)yarn dev
