### ISSUE TITLE
When canceling an upload or paste text in:

### ISSUE THREAD

**Issue by Kietil** [RocketChat/Rocket.Chat#3043]
When a drag-into-window upload is performed but canceled, the window remains with the overlay on top. Switching channel, will not cancel the gray overlay "Drop to upload file".

Editing text outside the chat, and paste it in, will not format into rocket.chat standard. From win notepad into rocket.chat creates extra empty line after each line break.

Also. Editing large walls of text requires a press of ctrl to expand the textfield. It's a extra button function that newcommers may not know of, that should happen automaticly.

PS:
This is nitpicking in a superb software that should be separated into different issues or thrown in the trash bucket as nagging side-comments. Please excuse my random pointers, I just like this software too much to stay silent. This will be the new kid on the block soon, just like Gulp was for task-running.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
