### ISSUE TITLE
Difference between Group and Team on V6.0

### ISSUE THREAD

**Issue by ralexrdz** [RocketChat/Rocket.Chat#30444]
Hey rocket scientists, I'm on a Self Hosted Rocket Chat V6

I'm looking at REST API's Endpoints documentation and can't figure out where to create Groups, or if there is a difference between Groups and Teams.

Would you be able to point me to the explanation?

Is it a feature that is discontinued on newest version, but documentation stills shows it?

Thanks in advance :rocket:

**Comment by Gummikavalier** [comment]
These should be them respectively:

channel = open channel
https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/channels-endpoints

room  = group aka private group
https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/groups-endpoints

teams = teams can contain channels and groups they can inherit their members from their parent team
https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/teams-endpoints
