### ISSUE TITLE
Experienced a text input failure that affected text input in other applications

### ISSUE THREAD

**Issue by Donngd** [RocketChat/Rocket.Chat#30451]
After upgrading to iPadOS 17, I can't type in RocketChat using my Smart Keyboard. The input method status bar doesn't even appear. Even worse, if I switch to another app that can use the Smart Keyboard normally, that app will also stop working. I have to quit and reopen it to get it back to normal.
## iPad Pro 2018, iPadOS 17.0(21A329), RocketChat 4.40.0.47248

**Comment by no-nice-username** [comment]
Same here. Ipad Pro M1, Rocket chat 4.41.0.49562

**Comment by Donngd** [comment]
Update iPad OS to 17.0.3 today，problem solved

**Comment by Donngd** [comment]
> Same here. Ipad Pro M1, Rocket chat 4.41.0.49562

Update iPadOS to 17.0.3

**Comment by no-nice-username** [comment]
Just updated to 17.0.3 - still the same for me. RC is completely unusable with the mk attached

**Comment by fc757** [comment]
I have the same issue as well and was running IPadOS 17.0.3 at the time of my issue post in the Rocket.Chat.ReactNative  github. I've even tried 17.2 beta in desperation and I still have the issue. 

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5260

It looks like it's something to do with: -[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:] perform input operation requires a valid sessionID

But I have no idea how to fix that.

**Comment by diegolmello** [comment]
Let continue the discussion on https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5260#issuecomment-1808475646
