### ISSUE TITLE
Feature - in-app screenshot tool

### ISSUE THREAD

**Issue by flypenguin** [RocketChat/Rocket.Chat#3047]
Your Rocket.Chat version: 0.28
I found that the possibility to make and send a screenshot from a messaging app is really useful in companies. I know that I can press "shift-print", select my area, open file manager, drag and drop it in rocketchat, but "click - select - enter" is way better IMO :)

**Comment by engelgabriel** [comment]
What OS are you using?

**Comment by engelgabriel** [comment]
Can't you take a screen capture into clipboard and just paste on Rocket.Chat? I do it on the Mac all the time.

**Comment by flypenguin** [comment]
sure I can. And Win, or Linux? And the people who don't know CMD-CTRL-Shift-4, or don't have Macs, which is about everyone else in my company and most of the ones before? ;) You're completely right that most OSs have this built in, I just think as a shared team solution it might be convenient ("nice to have" fits pretty well) to those people who don't know how to quickly access this, which is "most" IMHO :)

**Comment by engelgabriel** [comment]
I agree, it is definitely a nice to have. We would welcome contributors for that.

Do you know if this work on windows? 
http://windows.microsoft.com/en-us/windows/take-screen-capture-print-screen#take-screen-capture-print-screen=windows-8

Maybe as a stopgap, we could have this command on a quick help button.

**Comment by twhiting** [comment]
@flypenguin On windows use the "Snipping tool" its awsome.

**Comment by lucasvanhalst** [comment]
If you're on windows I would recommend this instead - https://getsharex.com/ 
It's a great program and has tons of customization and options available

**Comment by takavfx** [comment]
I want this one too as a function installed into Rocket.Chat or Rocket.Chat.Electron.
I've already posted my idea here: RocketChat/Rocket.Chat.Electron#334

Actually I found this( https://www.npmjs.com/package/electron-screencapture ) npm-package for electron. I'm not sure how this works but it can be better some kind of this thing is installed into such as Rocket.Chat.Electron.

**Comment by matheusd** [comment]
Another use-case: have the "take screenshot" button on the live chat widget (or on the channel) such that an operator can request a screenshot and use the live chat as a general support solution.

**Comment by today4king** [comment]
its really great if have this button

**Comment by gdelavald** [comment]
I'll close this ticket since it's related to the desktop app, please continue discussion on RocketChat/Rocket.Chat.Electron/issues/334
