### ISSUE TITLE
Question: About meteor-accounts-saml differences

### ISSUE THREAD

**Issue by jykae** [RocketChat/Rocket.Chat#3048]
We have difficulty getting SAML signature validation passing with steffow version that you have possibly forked. You have commented out some parts as well as these parameters, https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-accounts-saml/saml_utils.js#L240

Does that validate or what happens (hopefully not any skipping)?
It would be important to know that what happens as the signature is crucial part, and you have gone through that fixing/patching process for the package.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open a new issue with updated details. Thanks
