### ISSUE TITLE
New Docker Installation having "The application GUI just crashed.

### ISSUE THREAD

**Issue by iamfasal** [RocketChat/Rocket.Chat#30494]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by debdutdeb** [comment]
There is nowhere enough information to troubleshoot this :/ sorry
