### ISSUE TITLE
Bug : No DropDown visible when Create New button is Clicked in rocket chat

### ISSUE THREAD

**Issue by lokesh-wagh** [RocketChat/Rocket.Chat#30498]
### Description:

I was using Open.Rocket.Chat when i encountered this issue
on clicking the create new button i am expecting a dropdown instead a small div appear's

### Steps to reproduce:

1. open.rocket.chat in your browser
2. Create New button in button group

### Expected behavior:

A drop down with some other button's

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/129964049/b8d360dd-e0a3-40d8-a9ca-facc86d3d7de

no drop down 
instead  a small div that may be was supposed to be a little bit bigger

### Client Setup Information

- Desktop App or Browser Version: Open.rocket.chat endpoint

### Additional context

I have used the url https://open.rocket.chat to open the rocket chat web client  app

**Comment by lokesh-wagh** [comment]
If somebody is experiencing same issue please let me know

**Comment by lokesh-wagh** [comment]
This issue only exist's in the open.rocket.chat server 

in my local setup it is displaying properly 

![image](https://github.com/RocketChat/Rocket.Chat/assets/129964049/41f948d1-941e-4f70-a134-4cf2758efff1)

**Comment by Gokul2003g** [comment]
Is the issue resolved, how did you solve this?

**Comment by lokesh-wagh** [comment]
It's only in the rocket chat server for contributor's and developer's

Not in the local development server that I have 

So I think that the create channel maybe purposefully disabled to prevent dm's

**Comment by Gokul2003g** [comment]
Okay
