### ISSUE TITLE
LDAP / AD - Error: Username already exists. [403]

### ISSUE THREAD

**Issue by zetoadmin** [RocketChat/Rocket.Chat#30507]
Hello!

I have a problem with AD logging to Rocket Chat. After my problems with AD, when a had to disable Ldap integration, I cant log myself and another persons to Chat. When i try find user by 'ldap search test' - it works, user is found. But when I try to login access via login page, and input correct ad pass and press Log to, then nothing happens and I don't log in. In Rocket Chat log i have: 

`
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":30,"time":"2023-09-27T12:13:48.052Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP","section":"Connection","msg":"LDAP connected"}
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":30,"time":"2023-09-27T12:13:48.052Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP","section":"Search","msg":"Searching by username","username":"kopernikus","baseDN":"OU=XXXXXXX,DC=ad,DC=XXXXX,DC=pl","searchOptions":{"filter":"(&(objectClass=person)(|(userAccountControl=512)(userAccountControl=66048))(sAMAccountName=kopernikus))","scope":"sub","sizeLimit":1000,"attributes":["*","+"],"paged":{"pageSize":250,"pagePause":false}}}
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":30,"time":"2023-09-27T12:13:48.053Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP","section":"Bind","msg":"Binding UserDN","userDN":"CN=integrator,OU=Grupy uprawnien,OU=XXXXXXX,DC=ad,DC=XXXXX,DC=pl"}
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":30,"time":"2023-09-27T12:13:48.059Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP","section":"Search","msg":"LDAP Search found 1 entries and loaded the data of 1."}
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":30,"time":"2023-09-27T12:13:48.070Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP","section":"Auth","msg":"Authenticating","dn":"CN=Kopernikus,OU=SAS - Administratorzy Systemów Serwerowych,OU=DSI - Dział Systemów Informatycznych,OU=DG - Dyrektor Generalny,OU=DZ - Zarząd,OU=XXXXXXX,DC=ad,DC=XXXXX,DC=pl"}
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":30,"time":"2023-09-27T12:13:48.073Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP","section":"Auth","msg":"Authenticated","dn":"CN=Kopernikus,OU=SAS - Administratorzy Systemów Serwerowych,OU=DSI - Dział Systemów Informatycznych,OU=DG - Dyrektor Generalny,OU=DZ - Zarząd,OU=XXXXXXX,DC=ad,DC=XXXXX,DC=pl"}
Sep 27 14:13:48 chat Rocket.Chat[292338]: {"level":50,"time":"2023-09-27T12:13:48.102Z","pid":292338,"hostname":"chat.domain.pl","name":"LDAP Data Converter","err":{"type":"errorClass","message":"Username already exists. [403]","stack":"Error: Username already exists. [403]\n    at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1206:15)\n    at app/authentication/server/startup/index.js:300:28\n    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at AccountsServer.Accounts.insertUserDoc (app/authentication/server/startup/index.js:355:17)\n    at app/importer/server/classes/ImportDataConverter.ts:372:19\n    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/importer/server/classes/ImportDataConverter.ts:523:18\n    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":403,"reason":"Username already exists.","errorType":"Meteor.Error"},"msg":"Username already exists. [403]"}
`

And `Find user after login` is set to `no`

**Comment by zetoadmin** [comment]
I have no enterprise edition

**Comment by zetoadmin** [comment]
And also one more thing: For new AD users, it everything works. First I can log by AD pass, next to when I change pass by Rocket Char panel, i can log by this pass, but then when i  try to log by AD pass, it is updated in local rocket database and logging works.

**Comment by alexiosc** [comment]
I can confirm we're seeing the exact same behaviour. Our back-end is OpenLDAP, not AD. This worked fine earlier this week before we upgraded.

**Comment by wobonfim** [comment]
I've been the same problem. I'm triyng to change the AD server, but only works for new users. If i create a local user, the integration with AD works perfectly, when i loggin, the passord AD is accept and all works fine. But, if the user was previously create with AD, when i try to loggin with the new AD, i can't. the same message "Username already exists. [403]"

**Comment by zetoadmin** [comment]
Exactly... is fix for it?

**Comment by wobonfim** [comment]
> Exactly... is fix for it?

not yet!

**Comment by pierre-lehnen-rc** [comment]
Related: #30034 

> I've been the same problem. I'm triyng to change the AD server, but only works for new users. If i create a local user, the integration with AD works perfectly, when i loggin, the passord AD is accept and all works fine. But, if the user was previously create with AD, when i try to loggin with the new AD, i can't. the same message "Username already exists. [403]"

If you change the AD server, rocket.chat will no longer recognize it as being the same user as before and will try to create a new one. The issue above has instructions on how to remove the links to the old AD server so the new one can work.

**Comment by Rhywden** [comment]
> Related: #30034
> 
> > I've been the same problem. I'm triyng to change the AD server, but only works for new users. If i create a local user, the integration with AD works perfectly, when i loggin, the passord AD is accept and all works fine. But, if the user was previously create with AD, when i try to loggin with the new AD, i can't. the same message "Username already exists. [403]"
> 
> If you change the AD server, rocket.chat will no longer recognize it as being the same user as before and will try to create a new one. The issue above has instructions on how to remove the links to the old AD server so the new one can work.

That's nice. We have the same error but did NOT change anything about the AD/LDAP.

**Comment by zetoadmin** [comment]
To resolve problem I did it for all accounts: 

```
use rocketchat
db.users.updateOne({username: "USERNAME"}, {$set: {"ldap": false}})
db.users.updateOne({username: "USERNAME"}, {$unset: {"services.ldap": true}})
```
It works.
