### ISSUE TITLE
Slack import does not recognize the source file

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#3050]
Your Rocket.Chat version: 0.31

The slack export bundle contains JSON-files only, but the servers returns "invalid import file type" error.

![image](https://cloud.githubusercontent.com/assets/16319433/14847839/77cb279c-0c73-11e6-950d-c4fe684fc3da.png)

**Comment by zxweed** [comment]
Hello, @graywolf336, @geekgonecrazy. Tell me, please, is there a way to import slack history in it's current format (only json-files)?

**Comment by geekgonecrazy** [comment]
@zxweed the import expects the zip file that is given to you by a slack export

**Comment by zxweed** [comment]
@geekgonecrazy, I have tried the zip file too with same results:
![image](https://cloud.githubusercontent.com/assets/16319433/14896408/44df3f62-0d86-11e6-8267-c58f04bf2d55.png)

**Comment by zxweed** [comment]
there are no error message in the log:

> [methods] setupImporter -> userId: Efjsx7m6u4mrfcm7A , arguments:  { '0': 'slack' }
> [methods] getImportProgress -> userId: Efjsx7m6u4mrfcm7A , arguments:  { '0': 'slack' }

**Comment by geekgonecrazy** [comment]
@zxweed i'm out of ideas on this one.  @graywolf336 might know more.

**Comment by graywolf336** [comment]
@zxweed the file must be an untouched zip file which Slack provides. The importer expects a particular layout of the files insides the zip. Try the importer again with the zip from Slack and get back with us.

**Comment by zxweed** [comment]
@graywolf336, I have reexport the fresh bundle from slack and try to import it with the same effect - import processes was not initiated.

**Comment by graywolf336** [comment]
@zxweed mind trying out the newest release? Version 0.30 contains some changes to the slack importer.

**Comment by zxweed** [comment]
@graywolf336, I have upgrade to 0.30.0 - the problem still exists

**Comment by zxweed** [comment]
0.31 version the same

**Comment by graywolf336** [comment]
@zxweed Hit me up on the demo server so we can talk about this and get the issue resolved, as we need to look into the file's structure

**Comment by AlexandreSNeto** [comment]
Same problem here. There are some solution ?

**Comment by zxweed** [comment]
0.34 - problem exists

**Comment by marcocevoli** [comment]
on 0.33 and same problem

**Comment by teamfighter** [comment]
v.0.37. Same problem there.

**Comment by zxweed** [comment]
0.38 - problem exists

**Comment by jszaszvari** [comment]
I have run into the same issue. I found that doing the users first, then
doing the channels one by one seemed to let me get through it till the end.

I needed to restart the server a few times but it eventually all went
through. Very strange.

**Comment by jszaszvari** [comment]
Sorry I forgot to mention, it worked much better when I was logged in as a
user that did not exist in the slack import. Not sure if related or just a
coincidence though.

I'll give the import a try in a new instance now..

I may still have a export from a few weeks ago when it was all working
fine. I'll try and do a compare as well and report back my findings.

**Comment by geekgonecrazy** [comment]
@jszaszvari that might actually be an important piece.  I can see things struggling a bit if you are logged in as a user present in the import.

@graywolf336 thoughts?  Think this would be a difference between it working and not working?

**Comment by whren** [comment]
Hi, I encountered this issue on 0.41.0.

Debugging on my side leads me to event.target.files[x].type being empty.
The check that throw the exception is there in the [source](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-importer/client/admin/adminImportPrepare.coffee#L32).

Hope it'll help

**Comment by graywolf336** [comment]
@whren what would you suggest relying on then?

**Comment by whren** [comment]
@graywolf336 I'll suggest to rely on [file signature](https://en.wikipedia.org/wiki/List_of_file_signatures) + extension if Blob.type is empty.

**Comment by engelgabriel** [comment]
@graywolf336 is this still a problem?

**Comment by graywolf336** [comment]
@engelgabriel I think so, I never could replicate it sadly.

**Comment by zxweed** [comment]
The 0.46 release still have this problem

**Comment by graywolf336** [comment]
@zxweed Any chance we can talk on the demo server?

**Comment by zxweed** [comment]
@graywolf336 sure, we have already discussed this issue

**Comment by morbidpete** [comment]
Same issue here. version 0.48.2 using snap under ubuntu server

**Comment by graywolf336** [comment]
This should now be fixed in the develop branch, if someone feels like
testing it to verify that would be greatly appreciated!

**Comment by morbidpete** [comment]
@graywolf336 
   I am running the snap container, is there a way to use the dev in snap or do I need to wait?

**Comment by graywolf336** [comment]
@geekgonecrazy can you answer the above question?

**Comment by geekgonecrazy** [comment]
@morbidpete if you are in a production environment don't try this.  There are a lot of things changing between 0.48.2 and what will be 0.49.0. 

Run the following in your dev environment:
`sudo snap install rocketchat-server --channel edge`

**Comment by morbidpete** [comment]
@geekgonecrazy No production yet, Just seeing if this is a viable option to replace slack for our use. Thank you for the quick reply.

**Comment by morbidpete** [comment]
Worked great, thank you all so much for fixing this!

**Comment by graywolf336** [comment]
Awesome, thank you for trying it out and reporting back! @morbidpete
