### ISSUE TITLE
Updating rocketchat server always getting this error .

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#30517]
Please help
Thank you
node-pre-gyp ERR!
install response status 400 Bad Request on https://github.com/kelektiv
/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar.g
z
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@14.21.3 ( node-v83 ABI,,
glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 400 Bad Request on https://github.com/kelekt iv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-x64-glibc.tar

**Comment by athoik** [comment]
Hi,

Do you have python on your system? 

On debian 11 and debian 12 there is no python executable any more. 
Although there is still python2.7 installed.

So in order to bypass that error creating a symlink python to python2.7 worked for me...

```
# become root
sudo -i
# switch to /usr/bin folder
cd /usr/bin
# create a symlink python to python2.7
ln -s python2.7 python
```

Now repeat the installation and let us know if that trick worked for you as well.

**Comment by lovekyleman** [comment]
> Hi,
> 
> 
> 
> Do you have python on your system? 
> 
> 
> 
> On debian 11 and debian 12 there is no python executable any more. 
> 
> Although there is still python2.7 installed.
> 
> 
> 
> So in order to bypass that error creating a symlink python to python2.7 worked for me...
> 
> 
> 
> ```
> 
> # become root
> 
> sudo -i
> 
> # switch to /usr/bin folder
> 
> cd /usr/bin
> 
> # create a symlink python to python2.7
> 
> ln -s python2.7 python
> 
> ```
> 
> 
> 
> Now repeat the installation and let us know if that trick worked for you as well.

Thank you for your help.
I'm ganna try it 
Must be python2.7 ? Python3 is not good for rocketchat?
Thanks

**Comment by lovekyleman** [comment]
I have python3 installed on my system (Debian 11)
But no python2.7

**Comment by athoik** [comment]
Try to install it python and then create the symlink.

```
sudo apt install python
```

**Comment by lovekyleman** [comment]
I have tried it. But can't fix the problem

**Comment by lovekyleman** [comment]
And always have other problem like 

gc-stats@1.4.0 install /tmp/bundle/programs/server/прт/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 400 Bad Request on https://node-binaries.s3.am
azonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for gc-stats@1.4.0 and node@14.21.3 (node-V83 ABI,
glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 400 Bad Request on https://node-binaries.s3.
amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz

**Comment by athoik** [comment]
Indeed the problem is gc-stats package. It requires a very old node-pre-gyp, that uses python2.

A possible solution would be to switch to a maintained version of gc-stats. Eg: https://github.com/sematext/node-gcstats

Or another solution would be to install manually python (since you cannot install it with apt from debian).

Certainly updating gc-stats would be perfect, since python2 is already history.

Try the following to install python manually.

```
cd /tmp
wget http://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
tar -xzf Python-2.7.9.tgz
cd Python-2.7.9

./configure --prefix=/usr/local --enable-shared
make
sudo make install
cd ..
```

Then check if python is installed and run rocket chat installation.

**Comment by athoik** [comment]
I think installing latest node-gyp fixes issue! No need for python2.

```
sudo npm install -g node-gyp
```

On python 3.11 used by debian 12 I had this error: https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp After changing rU to r build worked just fine!

**Comment by lovekyleman** [comment]
> I think installing latest node-gyp fixes issue! No need for python2.
> 
> 
> 
> ```
> 
> sudo npm install -g node-gyp
> 
> ```
> 
> 
> 
> On python 3.11 used by debian 12 I had this error: https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp After changing rU to r build worked just fine!

Sudo npm install -g node-gyp just update to node-pre-gyp@0.17.0
And can't fix the issue

**Comment by lovekyleman** [comment]
> Indeed the problem is gc-stats package. It requires a very old node-pre-gyp, that uses python2.
> 
> 
> 
> A possible solution would be to switch to a maintained version of gc-stats. Eg: https://github.com/sematext/node-gcstats
> 
> 
> 
> Or another solution would be to install manually python (since you cannot install it with apt from debian).
> 
> 
> 
> Certainly updating gc-stats would be perfect, since python2 is already history.
> 
> 
> 
> Try the following to install python manually.
> 
> 
> 
> ```
> 
> cd /tmp
> 
> wget http://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
> 
> tar -xzf Python-2.7.9.tgz
> 
> cd Python-2.7.9
> 
> 
> 
> ./configure --prefix=/usr/local --enable-shared
> 
> make
> 
> sudo make install
> 
> cd ..
> 
> ```
> 
> 
> 
> Then check if python is installed and run rocket chat installation.

Already have python2.7.9 installed but can't fix the issue

**Comment by lovekyleman** [comment]
> I think installing latest node-gyp fixes issue! No need for python2.
> 
> 
> 
> ```
> 
> sudo npm install -g node-gyp
> 
> ```
> 
> 
> 
> On python 3.11 used by debian 12 I had this error: https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp After changing rU to r build worked just fine!

Done.but still can't fix the issue
