### ISSUE TITLE
Oauth w/ MS Entra: Bad Request at /openid/userinfo

### ISSUE THREAD

**Issue by DClabaut** [RocketChat/Rocket.Chat#30520]
### Description:

Followed this documentation: https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/oauth/ms-office-365-oauth-setup to have users log in with Microsoft Entra (Formerly AzureAD, Formerly MS 365, etc).

The login button appears, clicking it redirects to Microsoft, then back to the login page.

### Steps to reproduce:

- Create application in MS Entra (see details in https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/oauth/ms-office-365-oauth-setup, with one difference, `Supported Account Types` has been set to `Accounts in this Directory Only` (first option))

- Using admin account, go to `https://my_rocket.chat/admin/settings/OAuth` 
- Click "Add Custom Oauth", call it Microsoft
- Set this configuration:
  -  Enabled: True
  - URL: `https://login.microsoftonline.com/<tenant ID>`
  - Token Path: /oauth2/v2.0/token
  - Token Sent via: Payload
  - Identify Token sent via: Header
  - Identity Path: /openid/userinfo
  - Authorize Path: /oauth2/v2.0/authorize
  - Scope: openid
  - ID: Application ID provided by Entra
  - Secret: Provided by Entra
  - Login style: Redirect
  - Button Text: Login via Microsoft
  - {Username, Email, Name, Avatar} field: NULL
  - Merge Users: True
  - Merge Users From Distinct Services: True
  - OAuth Group Channel map: `{}`
  
- In different browser / new session, go to `https://my_rocket.chat/home`
- Click `Login via Microsoft`
- Login to Microsoft (Username, Password, 2FA)

### Expected behavior:

User accesses RocketChat

### Actual behavior:

User goes back to login page

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.7
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.18

### Client Setup Information

- Desktop App or Browser Version: Firefox-esr 115.2, Chromium 108
- Operating System: Ubuntu 22

### Additional context

- Identity endpoint is described in https://login.microsoftonline.com/<tenant_id>/v2.0/.well-known/openid-configuration as `https://graph.microsoft.com/oidc/userinfo`, though `https://login.microsoftonline.com/<tenant ID>/openid/userinfo` does exist or it would just return a 404.

- RC instance used for testing is accessible via IP address not FQDN, with an invalid cert, as it is a temporary instance meant specifically to test migrating from LDAP-based auth to OIDC-based auth.

### Relevant logs:

```
Exception while invoking method 'login' Error: Failed to fetch identity from microsoft at https://login.microsoftonline.com/<tenant_id>/openid/userinfo. Bad Request     at app/custom-oauth/server/custom_oauth_server.js:186:18     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/custom-oauth/server/custom_oauth_server.js:195:18     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at packages/oauth2/oauth2_server.js:10:22     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at packages/oauth/oauth_server.js:171:5     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at packages/accounts-base/accounts_server.js:1525:11     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at packages/accounts-base/accounts_server.js:653:7     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)     at packages/meteor.js:365:18     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)     at packages/ddp-server/livedata_server.js:791:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:739:23)     at packages/ddp-server/livedata_server.js:603:43 
```

**Comment by DClabaut** [comment]
As an update, I managed to get this to work by removing `/2.0` in `Token Path` and `Identity Path`. This configuration does not get the `email` value, so if you merge using email, you need to set `Key Field` to `email` and `Email field` to `upn`.

For the record, the available fields for user identification are: `family_name`, `given_name`, `name`, `unique_name` and `upn`

Can the documentation be updated?

**Comment by pierre-lehnen-rc** [comment]
Thanks for the report! I'll notify the docs team.
Since it's not a problem with rocket.chat itself I'll close the issue here.

**Comment by CorentinDeBoisset** [comment]
I can't make it work the same way @DClabaut did... Maybe Microsoft removed some legacy endpoints.

The userinfo endpoint of the application in the microsoft admin is "https://graph.microsoft.com/oidc/userinfo", and I can't make Rocketchat send a valid request.

Could this issue be re-opened and investigated?

**Comment by manojkcoder** [comment]
> I am also running into the problem, exact same results as @CorentinDeBoisset . Tried some configuration (like with v2.0/ and without, and using the graph.microsoft userinfo url) combinations, but can't get the login via Entra to work.

make sure, you have:

Identify Token sent via: Header

**Comment by radmiraal** [comment]
> > I am also running into the problem, exact same results as @CorentinDeBoisset . Tried some configuration (like with v2.0/ and without, and using the graph.microsoft userinfo url) combinations, but can't get the login via Entra to work.
> 
> make sure, you have:
> 
> Identify Token sent via: Header

Thanks! Authentication is now successful. Just in case someone stumbles on this issue I post my settings as reference:

`Token Path: /oauth2/token
Token Sent Via: Payload
Identity Token Sent Via: Header
Identity Path: /openid/userinfo
Authorize Path: /oauth2/authorize
Scope: openid profile email
Param Name for access token: access_token
Id / Secret: copied from entra
Login Style: Redirect
Key Field: Email`

Did not dig into groups yet ;-)
