### ISSUE TITLE
Automatic login using external authentication service

### ISSUE THREAD

**Issue by Ron537** [RocketChat/Rocket.Chat#3052]
Hi there!

I've implemented SAML authentication in my Rocket.Chat application.
When a user wants to login, he have to click a separate button (for the SAML authentication) and only then (after clicking) he is redirected to the SAML provider service which is taking care of the authentication.

I think it would be great if you add an option to "automatic redirect" the user to the authentication service (something like simulating a click event on the login button) when the user is browsing the application for the first time (not logged-in).

So the sequence would be as followed:
1. User browse to the Rocket.Chat application
2. Automatically redirected to the external authentication service( _SAML_ , Facebook , Google , etc... ) if the option for automatic redirect for this authentication method is enabled
3. User logged in to the application.

![screenshot from 2016-04-27 13-30-15](https://cloud.githubusercontent.com/assets/12497978/14852208/97ed4982-0c8d-11e6-968e-3f130d833108.png)

**Comment by Ron537** [comment]
This all process is instead of waiting for the user to click the 'SAML LOGIN' button (in my case)

**Comment by kruczjak** [comment]
:+1: (in Custom OAuth)

**Comment by ksuquix** [comment]
+1 (for CAS in my case, but same thing)

**Comment by corecache** [comment]
Duplicate for CAS: #2327

**Comment by fcoppolani** [comment]
:+1:  in Custom OAUTH

**Comment by fengt** [comment]
+1 (in Custom OAuth)

**Comment by MartinSchoeler** [comment]
This is a duplicate.
