### ISSUE TITLE
Cluster or HA setup

### ISSUE THREAD

**Issue by dupree972** [RocketChat/Rocket.Chat#3053]
Your Rocket.Chat version: 0.28

Has anyone set this up in a redundant or HA manner/clustered or have any guidance on how to do so.. Any help would be much appreciated. This is a critical requirement for us to deploy rocket.chat and I can't find any really docs or examples of what that would look like....

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
