### ISSUE TITLE
Feature request : Opening of replies section when clicking on replies icon. 

### ISSUE THREAD

**Issue by Ninad3721** [RocketChat/Rocket.Chat#30539]
### Description:

In the current system when clicking on "replies"  under a message it do not do anything but clicking on "reply" button it shows all the reply to that message. This is bit misleading for a user because clicking on replies icon do not show replies  to that message.
https://www.loom.com/share/1253a0725bf149f5b7fbf9751c4c928c?sid=9bcf8e53-aacb-4a1d-a0fb-02d708f4d1c5
### Steps to reproduce:

1. open open.rocket.chat 
2. find a message which have some replies 
3. click on replies icon 

### Expected behavior:

replies section should open as  it opens up when clicking on reply button

### Actual behavior:

Nothing happens when clicking on replies icon

### Client Setup Information

- Desktop App or Browser Version:  Browser (Microsoft Edge)
- Operating System: Windows 11

**Comment by unbalancedvariance** [comment]
Hey can I work on this issue?

**Comment by MeethDavda** [comment]
Hey, I have added the feature request but while pushing the code it fails at @rocket.chat/meteor#testunit. Any suggestion to fix it ?

<img width="985" alt="Screenshot 2023-10-04 at 11 13 24 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/97303932/5844c03f-8809-42cd-8cf5-ef03453c052a">

**Comment by AdityaRaut13** [comment]
@MeethDavda can you show the whole error ?

**Comment by MeethDavda** [comment]
@AdityaRaut13 Yeah sure, it ways these 3 tests were failed

<img width="981" alt="Screenshot 2023-10-05 at 11 13 30 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/97303932/8e114c1c-43c5-4c9c-9db1-980e758373ee">

**Comment by MayurAnklekar** [comment]
You can change the timezone on your machine, and it will work!!

**Comment by MeethDavda** [comment]
It works! Thanks

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, by design, it's not meant to be clickable .

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
