### ISSUE TITLE
OAuth with Login Style "Redirect" does not work anymore in Firefox (Chrome works fine)

### ISSUE THREAD

**Issue by marco-websource** [RocketChat/Rocket.Chat#30545]
### Description:

After updating to Rocket.Chat 6.4.0 we see the following issue:

Our custom OAuth does not work anymore in Firefox when Login Style "Redirect" is selected. After clicking the login button and entering the credentials on our login page the user is redirected back to the RC login page. Clicking the login button again loops back to the login page. The problem does **not** occur in Chrome or in the apps. Also, the login work properly when the Login Style is changed to "Popup" (this is our current workaround).

### Steps to reproduce:

1. Open RC login page in Firefox.
2. Click on OAuth login button of a custom OAuth-provider with Login Style set to "Redirect".
3. Enter credentials on OAuth provider page.

### Expected behavior:

Login to RC (show homepage / default channel).

### Actual behavior:

The user is always redirected back to the RC login page after successful OAuth login.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.21 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 102.14.0esr (64-Bit) / 118.1.0 (Android app)
- Operating System: Linux / Android

### Additional context

Our issue looks exactly like https://github.com/RocketChat/Rocket.Chat/issues/20374, which has been fixed in https://github.com/RocketChat/Rocket.Chat/pull/20722. Could this be a regression, i.e. that the workaround https://github.com/RocketChat/Rocket.Chat/blob/6.4.0/apps/meteor/app/custom-oauth/client/swapSessionStorage.js does not work anymore?

Also, https://github.com/RocketChat/Rocket.Chat/issues/23043#issuecomment-1641596320 could be the same issue.

### Relevant logs:

There are no relevant entries in the server log.
In the Firefox console we see the following error (stack trace shortened for readability):

`Object { stack: "r@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:1:4644\nn@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:18922\n_livedata_nosub@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:18994
[...]@https://chat.example.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:246:381731\n", isClientSafe: true, error: "not-allowed", reason: undefined, details: undefined, message: "[not-allowed]", errorType: "Meteor.Error" }
SDKClient.ts:86:13`

**Comment by Gummikavalier** [comment]
I can confirm this happening on Firefox.

Similar to Chrome one that as already fixed before:
https://github.com/RocketChat/Rocket.Chat/issues/29643

**Comment by ruslantum** [comment]
can confirm the issue on firefox on multiple different os versions

**Comment by Bengrunt** [comment]
We confirm as well.

**Comment by zwhhz** [comment]
We can confirm too

**Comment by BigSnicker** [comment]
Can confirm. Any timeline on a fix yet?  We've had to direct people to not use Firefox at the moment.

**Comment by lyz-code** [comment]
Our users have the same issue

**Comment by pirhoo** [comment]
We got the problem too. 

Some additional context: I tried in Private Window and with deleting cache and all site data but I got the same error. 

Using the "popup" login style solved the issue.

**Comment by alarischu** [comment]
We confirm the same issue. Thank you, @marco-websource for helping to find the temporary workaround for the issue.

**Comment by TimmiORG** [comment]
Issue still exist in 6.4.3

**Comment by zwhhz** [comment]
> Issue still exist in 6.4.3

can you link the issue please? cant find it in the change list.

**Comment by mhutter** [comment]
Note that the workaround presented here (use "Popup" style) breaks compatibility with alternative frontends like Ferdium.
