### ISSUE TITLE
Unable to save profile after edit

### ISSUE THREAD

**Issue by dejiar** [RocketChat/Rocket.Chat#30543]
### Description:

After updating our server to 6.4.0, user no longer can save their profile if `Allow Username change` and `Allow name change` is disable.

### Steps to reproduce:

1. Go to setting, untick `Allow Username change` and `Allow name change`
2. Go to profile, edit anything that are allow to edit and click save.
3. Nothing will happen and debugging page will show `error: "Not allowed [error-not-allowed]"`

### Expected behavior:

Previously, it can be save without any issue.

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/5075502/182533e1-0331-44db-abf5-ee331817975d)

### Server Setup Information:

- Version of Rocket.Chat Server: Running in kubernetes
- Operating System:
- Deployment Method: helm chart/kubernetes
- Number of Running Instances: 1
- DB Replicaset Oplog: 3
- NodeJS Version:
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by AravindAkuthota** [comment]
hello @dejiar  the issue has resolved on latest version 6.5.0 of rocket. Chat. update it

**Comment by wreiske** [comment]
> hello @dejiar the issue has resolved on latest version 6.5.0 of rocket. Chat. update it

How do you recommend going about updating to 6.5.0 if it hasn't been released yet?

**Comment by himpierre** [comment]
Maybe fixed in 6.4.3? https://github.com/RocketChat/Rocket.Chat/pull/30731

**Comment by dejiar** [comment]
Have upgraded to 6.4.6, still not fix yet

> Maybe fixed in 6.4.3? #30731

**Comment by himpierre** [comment]
Works for me.

Am 19. November 2023 02:45:17 MEZ schrieb DeJiar ***@***.***>:
>Have upgraded to 6.4.6, still not fix yet
>
>> Maybe fixed in 6.4.3? #30731
>
>
>

**Comment by dejiar** [comment]
Issue seem resolve after upgrade to version 6.5
