### ISSUE TITLE
email to post into a chat room

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3056]
if someone receive news letter, or alerts via emails in their inbox, is there a way to have those emails sent of forwarded into a dedicated room (keeping their rich text or have their own style) ??

**Comment by jerrygzy** [comment]
+1 ,  we are thinking of this feature too

**Comment by stanhu** [comment]
👍 We need this too!

**Comment by rchikballapur** [comment]
+1

**Comment by bjoseph1** [comment]
+1

**Comment by bradnagle** [comment]
+1

**Comment by soenkef** [comment]
+1 Really nice feature!

**Comment by DirkJanknecht** [comment]
+1

**Comment by jszaszvari** [comment]
I don't think the chat core should be watching out for these emails. 

This is what webhooks are designed to do (help facilitate this kind of intergration) 

You can use something like Zapier which has rocket.chat integration 

https://rocket.chat/docs/administrator-guides/integrations/zapier

Official site: https://Zapier.com

It just took me less than 5 mins to accomplish what you want : 

![img_1485](https://cloud.githubusercontent.com/assets/872463/25698775/91a8d974-3103-11e7-9269-ba43aad7ac61.PNG)

If you need more than Zapier provides for free and are unwilling to pay, then there is a service which does the same thing but is self hosted Called Huginn - https://github.com/huginn/huginn

**Comment by pkgodara** [comment]
Email text can be forwarded, so it will not have older styles, no html. Is that ok. As far as I understand, some dedicated email to which you can forward emails & can post messages to rooms. Is that what you want??

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by Aldekein** [comment]
Just to show a way it could be set up:

1. Set up a [Postmark incoming email](https://postmarkapp.com/developer/user-guide/inbound/parse-an-email) that will send webhooks.
2. Set up Rocket.chat incoming webhook with custom script enabled, like this one:

```
class Script {
  process_incoming_request({ request }) {
    var text = `From: "${request.content.FromName}" <${request.content.From}>\n`
    text += `Subject: ${request.content.Subject}\n`
    text += `\n${request.content.TextBody}`
    
    if (request.content.Attachments.length > 0) text += `\n\n${request.content.Attachments.length} attachments can be viewed at https://groups.google.com/a/xxxxxxxx.com/forum/#!forum/xxxxxxxx`
    
    return {
      content: {
        text: text
       }
    };
  }
}
```
