### ISSUE TITLE
Retention policy banner in Team Information panel shows wrong retention period (1 second)

### ISSUE THREAD

**Issue by marco-websource** [RocketChat/Rocket.Chat#30567]
### Description:

The retention policy banner in the Team Information panel displays a retention period of 1 second, although the retention policy is 2 years, which is correctly displayed at the top of the channel window (see screenshot). We see this problem only for Teams, the retention policy banner shows the correct retention period in Room Information panels (public or private group channels).

![rocket_chat_screenshot](https://github.com/RocketChat/Rocket.Chat/assets/13545742/d2451dad-071e-4706-8176-04210b6f40b3)

### Steps to reproduce:

1. Set a global retention policy.
2. Open Team Information panel of a Team.

### Expected behavior:

The retention policy banner should display the correct retention period (same as at the top of the channel window).

### Actual behavior:

The retention policy banner shows a retention policy of 1 second.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.21 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 102.14.0esr (64-Bit)
- Operating System: Linux

### Additional context

Related issue, that could probably be fixed at the same time: https://github.com/RocketChat/Rocket.Chat/issues/12182 ("exclude pinned messages" not taken into account in Room and Team Information panels, or in more general terms: the policy banner in info panels does not correspond with policy information at top of the channel).

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases. It was fixed here: #32454

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
