### ISSUE TITLE
Show more user details in admin -> users

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3057]
can we show date registered/last seen in the user table ? also anyway to download the list?

also on top show total currently Logged, and ROLES.

![image](https://cloud.githubusercontent.com/assets/12454319/14860945/13851b2a-0c79-11e6-8d1b-fb92ddb1475b.png)

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by ggazzo** [comment]
![image](https://user-images.githubusercontent.com/5263975/92032204-2ef94780-ed40-11ea-8d44-37576bd79a3f.png)
