### ISSUE TITLE
Nick anti-impersonation

### ISSUE THREAD

**Issue by tharude** [RocketChat/Rocket.Chat#3058]
Your Rocket.Chat version: 0.25
Let me suggest you to add an "anti-impersonation module" to Rocket Chat.
Once an user registers a nick name like J0el, all variances of this nick like JOel, JoeI etc. to became unavailable for registration.

**Comment by punkrock** [comment]
Especially the problem with uppercase "i" and lowercase "L" is important, because joeI =/= joel

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #4708.

Cheers
Thomas
