### ISSUE TITLE
SMS out of Rooms

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3059]
I see we have SMS in live chat, can this be setup for a room to post alerts to mobile numbers - users need to subscribe with numbers

**Comment by IQ2022** [comment]
has this feature got any attraction? can we send SMS out of rooms.. 

https://wparena.com/how-to-add-sms-text-messaging-services-to-blogs-and-websites/

**Comment by designgurudotorg** [comment]
@IQ2022 Working SMS into the chat experience across the app would be amazing, and open up RC to a whole world of dumb phones (plus enable us to code bots to interact with SMS within chatrooms)...  

Guessing we should spec this properly to see who is interested in working on building this out.  Have you seen this functionality work in a specific format through any other chat platform?  Want to write back with a spec? I can spend some time on this later in the week.

**Comment by timkinnane** [comment]
I don't think this is in scope as a core platform feature, but would be a good proposal for a new integration or bot. I'll close this ticket and add it as a proposal with a collection of others on issue #10174 - If I'm wrong and you feel strongly this should be a core feature, please comment and reopen.
