### ISSUE TITLE
Slack legacy custom integration (bots) is getting deprecated which in turn would affect Slackbridge

### ISSUE THREAD

**Issue by casalsgh** [RocketChat/Rocket.Chat#30594]
Our Slackbridge integration depends on Slack bot integration which is now deprecated and will be removed in the future. More info here - https://api.slack.com/legacy/custom-integrations. Their new recommended approach is using [Slack Apps](https://api.slack.com/start).

Update is needed on https://github.com/RocketChat/Rocket.Chat/tree/develop/apps/meteor/app/slackbridge

**Comment by hardikbhatia777** [comment]
Hey @casalsgh, can I be assigned this issue? Would love to contribute to this awesome project :)

**Comment by abhinavkrin** [comment]
Hello @casalsgh,
I've submitted a PR that enhances our Slack bridge integration by adopting the Slack app approach. This aligns with Slack's recommended practices, specifically utilizing the Events API. By doing so, we ensure that our integration has only the necessary scopes and permissions for seamless interaction.
For more details about the changes and the implementation, please refer to PR #30630.
Looking forward to your feedback!

**Comment by casalsgh** [comment]
> Hey @casalsgh, can I be assigned this issue? Would love to contribute to this awesome project :)

Sorry, ben away due to an event here; but will bring other items in a near future and tag you in case you want to check.

**Comment by casalsgh** [comment]
> Hello @casalsgh, I've submitted a PR that enhances our Slack bridge integration by adopting the Slack app approach. This aligns with Slack's recommended practices, specifically utilizing the Events API. By doing so, we ensure that our integration has only the necessary scopes and permissions for seamless interaction. For more details about the changes and the implementation, please refer to PR #30630. Looking forward to your feedback!

Thanks @abhinavkrin ! will request a review from internal engineering =)

**Comment by casalsgh** [comment]
Thanks for closing this one @abhinavkrin =) 
it will be on our next release

**Comment by abhinavkrin** [comment]
Thanks @casalsgh .  Glad to know that 🤞. Also, we should update the documentation to integrate slack bridge as the slack app would need a set of scopes to function. I have added the app manifest in my pull request #30630. It includes the scope I used.
