### ISSUE TITLE
Slash command preview of type:text is not visible

### ISSUE THREAD

**Issue by nimetu** [RocketChat/Rocket.Chat#30598]
Slash command preview of type:text is not visible. type:other is visible.

h4 inherits font-size from outer box which is 0px.
code has own font-size set and so is visible.

https://github.com/RocketChat/Rocket.Chat/blob/a8718eddc03cda4907e6c20de151ec9e982976cd/apps/meteor/app/ui-message/client/popup/components/composerBoxPopupPreview/ComposerBoxPopupPreview.tsx#L131-L132

**Comment by AbhishekCS3459** [comment]
@nimetu I wanna fix this issue please assign me this .

**Comment by hardikbhatia777** [comment]
Please provide proper steps to replicate the issue. Thanks!

**Comment by nimetu** [comment]
Example app with bug: https://github.com/nimetu/rc-apps-bug

Here is a striped down version
```
export class TestSlashCommand implements ISlashCommand {
  public providesPreview = true;

  public async previewer(context: SlashCommandContext, read: IRead, modify: IModify,
                         http: IHttp, persis: IPersistence): Promise<ISlashCommandPreview> {
    const i18nTitle = 'title';

    let items: Array<ISlashCommandPreviewItem> = new Array();

    items.push({
      id: 'text',
      type: SlashCommandPreviewItemType.TEXT,
      value: "BUG: not visible",
    })

    items.push({
      id: 'other',
      type: SlashCommandPreviewItemType.OTHER,
      value: 'visible',
    });

    return { i18nTitle, items };
  }
}
```
