### ISSUE TITLE
Tests... create a lot of tests

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#306]
See http://www.meteortesting.com/

**Comment by samhatoum** [comment]
I think so too

**Comment by engelgabriel** [comment]
@samhatoum YES! We need your help!! :)

**Comment by engelgabriel** [comment]
Label `contrib:experts needed` = @samhatoum :+1:

**Comment by geekgonecrazy** [comment]
Is there a framework we can start using to write some tests?  Even if we started per package it'd be a huge improvement.

@RocketChat/owners

**Comment by samhatoum** [comment]
you will want to use Jasmine for package testing

https://velocity.readme.io/docs/jasmine-testing-a-meteor-package

**Comment by geekgonecrazy** [comment]
@samhatoum awesome! Thanks for the quick response!

I've seen jasmine but not used it.  Looks pretty straightforward.  

Any tips on creating tests?

I'd like to start pushing more tests so we can get the habit started now.  Code base is growing at a very rapid pace :smile:

**Comment by gmsecrieru** [comment]
Related to #1044

**Comment by kakawait** [comment]
#1160 my small contrib :)

**Comment by marceloschmidt** [comment]
Closing the discussion in favor of #1045.
