### ISSUE TITLE
Indicate level of activity within channels when browsing the list of public channels

### ISSUE THREAD

**Issue by cbrummitt** [RocketChat/Rocket.Chat#3060]
I'd like to see **indicators of how active public channels are** when browsing the list of public channels. This would make it easier to find active, lively channels, especially in a large community with dozens of public channels.

After clicking "More channels..." we currently see a list of channels that we can sort by name or by number of messages:
![image](https://cloud.githubusercontent.com/assets/1268375/14871368/4375f760-0c96-11e6-9328-b1e4a95ed500.png)

In this list of public channels, I'd like to be able to see 
- how many users are in each channel, and/or
- how many messages are in each channel.

For comparison, Slack brings up a full-screen window for browsing channels with 4 ways of sorting it: 
![image](https://cloud.githubusercontent.com/assets/1268375/14871434/e6dbc650-0c96-11e6-94c8-a0d53739c0ad.png)
Also, Slack shows the number of users in each channel with a small "person" icon followed by a number: 
![image](https://cloud.githubusercontent.com/assets/1268375/14871443/fd159c5c-0c96-11e6-8b31-06e589b119dd.png)
This "person-icon 10" could be a succinct way to show the # members in the list of channels. Perhaps it could be shown next to the "join" icon.

Note that the HISTORY button shows the number of messages in each of the channels (as well as the date created and the date of the last message). So right now you could use the HISTORY window to find what channels are very active, but it would be nice if this activity level could be shown in the browsing window.

My Rocket.Chat version: 0.27.0, desktop version 1.1.0 (10)

**Comment by MartinSchoeler** [comment]
I believe that the upcoming channel discovery feature will solve this issue. Closing this for now.
