### ISSUE TITLE
About mention all user in team

### ISSUE THREAD

**Issue by mushroom11s** [RocketChat/Rocket.Chat#30618]
Env info:

- Deployment server version ：3.18.0
- apps Engine Version : 1.27.1
- node version: 12.22.1
- Run as Docker.

Problem: 
I Can't send @all message but my role permissions set "mentions" @all and @here is true. 
When i send @all msg,the bot will ask me :Group mentions @all and @here have been disabled for rooms with more than 1 members.action is not allowed
I don't know how to setting this?

**Comment by mushroom11s** [comment]
![Screenshot 2023-10-17 132957](https://github.com/RocketChat/Rocket.Chat/assets/28756933/605a9ec5-4019-404a-a7f1-7013fb733372)
![Screenshot 2023-10-17 133038](https://github.com/RocketChat/Rocket.Chat/assets/28756933/b8c34f0d-9d7f-4f80-bfcd-373a875c2e31)

Can anyone help me ！？😭

**Comment by mushroom11s** [comment]
@pierre-lehnen-rc  @casalsgh @Kunalvrm555

**Comment by casalsgh** [comment]
@mushroom11s please check: Workspace > Settings > General > Notifications. There should be a setting for Max Room Members Before Disabling All Message Notifications.

**Comment by mushroom11s** [comment]
> @mushroom11s please check: Workspace > Settings > General > Notifications. There should be a setting for Max Room Members Before Disabling All Message Notifications.

It's already set to 100,but is not work.And when i use TEST DESKTOP NOTIFICATIONS is ok.

**Comment by mushroom11s** [comment]
????
