### ISSUE TITLE
Custom CSS won't overwrite existing values

### ISSUE THREAD

**Issue by wolbernd** [RocketChat/Rocket.Chat#30621]
### Description:

To comply with company guidelines we want to change some colors in the rocketchat webfrontend. As per the documentation we put the color codes in the custom CSS field. However since 6.4.1 these changes don't show anymore (We updated directly from 6.2 so I'm not sure in which version exactly that bug was introduced).

### Steps to reproduce:

* Got to Workspace -> Settings -> Layout 
* Open the Custom CSS Tab
* Enter the following 
```
.rcx-sidebar--main {
  --rcx-color-surface-tint: #023d6b;
}
```

### Expected behavior:

The sidebar should have a dark blue background.

### Actual behavior:

The sidebar has a dark gray background (default background color)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.1
- Operating System: Ubuntu 22.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.18

### Client Setup Information

- Desktop App or Browser Version: Firefox 118.0.2
- Operating System: Linux

Also happens with Chromium 118.0.5993.54 

### Additional context

It looks like the priority of the defaults has somehow become higher than the stuff in Custom CSS:
![Screenshot_20231011_151311](https://github.com/RocketChat/Rocket.Chat/assets/24311754/f0f48d37-cbe6-4b65-bc56-d459363f7765)

As a workaround one can add `!important` to each entry like so:
```
.rcx-sidebar--main {
  --rcx-color-surface-tint: #023d6b !important;
}
```
This way the chosen color will be used, however that is not an elegant solution to the problem.

**Comment by Gummikavalier** [comment]
There seems to be a bug in RC 6.4.1 that prevents the loading of Custom CSS in the client end after every restart of the RC instance. I'll create another issue about this.

**Comment by eXtrem0us** [comment]
I have the same issue. Besides, there's another one, which seems relevant. The **Layout** option is vanished in the Electron App, whilst it can be seen when I login to Rocket Chat by the same admin account.
![Screenshot at 2023-10-14 11-19-39](https://github.com/RocketChat/Rocket.Chat/assets/7892702/70902416-5f3e-4105-a999-8d4fe9084c58)

**Comment by benwick** [comment]
I sincerly hope, they havn't gutted this feature...

**Comment by juliajforesti** [comment]
Hey @wolbernd !
Yeah, that's the current behavior. Due to some css specificity rules override, if you are customizing an existing var, you'll need to add `!important` 

Thanks! :)

**Comment by wolbernd** [comment]
@juliajforesti If that is the case, the official documentation should reflect that: https://docs.rocket.chat/use-rocket.chat/workspace-administration/settings/layout

**Comment by ChristophWolffNabu** [comment]
This should NOT be a solution for an enterprise software that costs that much money per user!
