### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by aadarsh-nagrath** [RocketChat/Rocket.Chat#30635]
Hi,
I am facing an issue in installing dependencies when I follow the local development setup instructions mentioned in docs. I visited React.Chat.Electron and saw people with same issues as mine. I am new to Rocket Chat. Check the image below
![image](https://github.com/RocketChat/Rocket.Chat/assets/92307537/981870bd-a6ab-413b-95f5-1b803fcc2f7e)

It shows -
@rocket.chat/forked-matrix-sdk-crypto-nodejs@npm:0.1.0-beta.12 couldn't be built successfully
isolated-vm@npm:4.4.2 couldn't be built successfully 
event-loop-stats@npm:1.4.1 couldn't be built successfully 

And Finally "Failed with errors"
Any solution to this ? or any possible causes why this is happening.
Also I have followed all the instruction from this as well -
https://developer.rocket.chat/open-source-projects/server/server-environment-setup/windows-10

**Comment by aryan-bhokare** [comment]
use all the versions properly 
Install nvm and use the version specified  in the docs and then again install specified of meteor hopefully it will run properly.

**Comment by ozonetech** [comment]
@aadarsh-nagrath please where you able to solve this problem,

**Comment by BhuvanPdDahal** [comment]
I am getting the same erors.

**Comment by ozonetech** [comment]
Try to install Mongod and make sure it is running, As this error is due to server I guess, Running Mongod Clear the error for me

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by MichaelFlyacts** [comment]
I had a simmular issue. It was able to solvend, when i installed make in wsl (e.g. via sudo apt install build-essential). Maybe this hint can be included in the docs of https://developer.rocket.chat/open-source-projects/server/server-environment-setup/windows-10
