### ISSUE TITLE
Upgrading to RC 6 with MongoDB 4

### ISSUE THREAD

**Issue by CVB2000** [RocketChat/Rocket.Chat#30641]
Greetings, we are currently facing the issue that we'd like to upgrade to Rocket Chat 6, coming from 5.4.10.
Unfortunately our VPS is not supporting avx/2. Is there any way to install RC6 using snaps with staying on MongoDB 4?

Or any other way around the AVX topic? I could not find a way to do this. Any tutorial would be highly appreciated.
Thank you!

**Comment by dantematik** [comment]
Hi not a good Idea , but you could : 
https://docs.rocket.chat/resources/rocket.chats-support-structure/enterprise-support-and-version-durability#mongodb-versions
It's possible to bypass the MongoDB version check by using the environment variable BYPASS_MONGO_VALIDATION=true. Bare in mind that this work around should be used only when extrictly necessary and may prevent some functionalities to work properly or even prevent the server to start.

4.4 is not in the need of AVX. 

But have a look a VM not supporting AVX must be old... security etc.

The alternative way there is a mongodb hack around.  (https://github.com/GermanAizek/mongodb-without-avx).
Still not a good idea. 
Take the save way : Check a Server with AVX (perhaps anupgrade from your infra will do it...) 

Have nice Day

**Comment by CVB2000** [comment]
Hi @dantematik , thanks for sharing this information.
A tweak around might be a solution, but it does not seem to be reliable and safe for the future. I hoped for a solution like "Yeah, you can change to MySQL" or whatever.
Since our hoster refuses to enable AVX and it is a rather small project, we'll be moving on to another solution instead of upgrading.
Thank you anyway!
