### ISSUE TITLE
Convert Hipchat special messages to native format

### ISSUE THREAD

**Issue by quinox** [RocketChat/Rocket.Chat#3065]
Your Rocket.Chat version: I ran the migration a while ago on 0.25 

After importing users and chat from a Hipchat dump all the "special" messages were shown as regular text in Rocket.chat. I had to fix the following:
- Hipchat's `/code foo\\nbar` should be replaced by `'''\nfoo\nbar'''`
- Hipchat's `/me foo bar` should be replaced by `_foo bar_`
- Hipchat's `/quote foo\\nbar` should be replaced by `> foo\n> bar`

For all 3 formats Hipchat stores newlines as an escaped sequence. these require an additional search/replace. A real example from one of the JSON files from the export file:

``` json
{                                                                                                           
  "date":"2014-11-14T21:05:37+0000",                                                                        
  "from":{                                                                                                  
    "name":"Some User",                                                                             
    "user_id":123456                                                                                        
  },                                                                                                        
  "message":"\/code \/\/ This file exists\\n\t\t\t$file = THEME_CSS . $link;\\n\t\t\tif ( file_exists($file) ) {\\n\t\t\t\t\/\/ This wont trigger\\n\t\t\t\tvar_dump('blaat');"
},                                                                                                          
```

It was rendered in Hipchat as a regular code snippet:

``` js
// This file exists
            $file = THEME_CSS . $link;
            if ( file_exists($file) ) {
                // This wont trigger
                var_dump('blaat');
```

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
