### ISSUE TITLE
Releases Build not updated

### ISSUE THREAD

**Issue by sleeplessnight2** [RocketChat/Rocket.Chat#30653]
In Short: `https://releases.rocket.chat/6.4.2/info` returns `{"error":"release not found"}`
I think that's all I need to say but I would be happy to try this release for a fix

**Comment by lmauromb** [comment]
@sleeplessnight2 `https://releases.rocket.chat/6.4.2/info` is already returning the correct info

**Comment by sleeplessnight2** [comment]
Yes, but only about 4 hours after I opened this.... even /latest/ pointed to the .1 release...

So it probably took care of itself *cough*.

**Comment by sleeplessnight2** [comment]
.
