### ISSUE TITLE
Cannot create user with random password and forced email verification

### ISSUE THREAD

**Issue by AlexanderKgr** [RocketChat/Rocket.Chat#30668]
### Description:

Cannot create user with random password and the option "Only allow verified users to login" enabled

### Steps to reproduce:

First of all i have enabled the option "Only allow verified users to login"
I am trying to create a new user.
Writing Name, Username, Email, Verified (not enabled), Require password change (Enabled), Set random password and send by email (Enabled), Roles - User, Join default channels (disabled), Send welcome email (enabled)

I am receiving email that my password has changed and then the welcome email (In my opinion this should change order)

I am trying to login with my random password that i have received.
It asks for email verification. Send confirmation email

I am receiving the email verification mail.
Opening the link to verify the email.

Then asks for logging.
Email Password and then again for email verification
This happens continuously.

### Expected behavior:
Login with random password.
Verify Email
Ask for new password.
Successful login 

### Actual behavior:

Cannot  verify email when a new user is created with random password

### Server Setup Information:

- Version of Rocket.Chat Server:  6.4.2
- Operating System: Ubuntu Server  22.04.3
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 118.0.5993.71
- Operating System: Windows 11

**Comment by roblefko** [comment]
This happens for all new users, not just those with a random password. Verify email is not working correctly.
