### ISSUE TITLE
Gitlab webhook doc

### ISSUE THREAD

**Issue by lobocode** [RocketChat/Rocket.Chat#3067]
I put the javascript that is the rocket documentation.chat to generate hooks for gitlab, and is giving this error message:

`rocketchat_integrations api.coffee:165 Integrations ➔ Incoming WebHook.error   function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }      /*jshint  esnext:true*/   // see https://gitlab.com/help/web_hooks/web_hooks for full json posted by GitLab   var NOTIF_COLOR = '#6498CC';      var Script = (function () {    function Script() {     _classCallCheck(this, Script);    }       Script.prototype.process_incoming_request = function process_incoming_request(_ref) {     var request = _ref.request;        try {      switch (request.headers['x-gitlab-event']) {       case 'Push Hook':        return this.pushEvent(request.content);       case 'Merge Request Hook':        return this.mergeRequestEvents(request.content);       case 'Note Hook':        return this.commentEvent(request.content);       case 'Issue Hook':        return this.issueEvent(request.content);       case 'Tag Push Hook':        return this.tagEvent(request.content);      }     } catch (e) {      console.log('gitlabevent error', e);      return {       error: {        success: false,        message: e.message || e       }      };     }    };       Script.prototype.issueEvent = function issueEvent(data) {     return {      content: {       username: data.user.name,       text: data.user.username + ' ' + data.object_attributes.state + ' an issue _' + data.object_attributes.title + '_ on ' + data.project.name + '. *Description:* ' + data.object_attributes.description + '. See: ' + data.object_attributes.url,       icon_url: data.user.avatar_url      }     };    };       Script.prototype.commentEvent = function commentEvent(data) {     var comment = data.object_attributes;     var user = data.user;     var text = undefined;     if (data.merge_request) {      var mr = data.merge_request;      text = user.name + ' commented on Merge Request #' + mr.id + ' [' + mr.title + '](' + comment.url + ')';     } else if (data.commit) {      var commit = data.commit;      var message = commit.message.replace(/<br>[^\s\S]+/, '...').replace(/<br>$/, '');      text = user.name + ' commented on commit [' + commit.id.slice(0, 8) + ' ' + message + '](' + comment.url + ')';     } else if (data.issue) {      var issue = data.issue;      text = user.name + ' commented on issue [#' + issue.id + ' ' + issue.title + '](' + comment.url + ')';     } else if (data.snippet) {      var snippet = data.snippet;      text = user.name + ' commented on code snippet [#' + snippet.id + ' ' + snippet.title + '](' + comment.url + ')';     }     return {      content: {       username: 'gitlab/' + data.project.name,       icon_url: data.project.avatar_url || user.avatar_url || '',       text: text,       attachments: [{        text: comment.note,        color: NOTIF_COLOR       }]      }     };    };       Script.prototype.mergeRequestEvent = function mergeRequestEvent(data) {     var user = data.user;     var mr = data.object_attributes;     return {      content: {       username: 'gitlab/' + mr.target.name,       icon_url: mr.target.avatar_url || mr.source.avatar_url || user.avatar_url || '',       attachments: [{        title: user.name + ' ' + mr.action + ' Merge Request #' + mr.id + ' ' + mr.title,        title_link: mr.url,        text: '_' + mr.source_branch + ' into ' + mr.target_branch + '_',        color: NOTIF_COLOR       }]      }     };    };       Script.prototype.pushEvent = function pushEvent(data) {     var project = data.project;     return {      content: {       username: 'gitlab/' + project.name,       text: '![' + data.user_name + '](' + data.user_avatar + ') ' + data.user_name + ' pushed ' + data.total_commits_count + ' commits to ' + project.name + '. See: ' + project.web_url,       icon_url: project.avatar_url || data.user_avatar || '',       attachments: [{        title: data.total_commits_count + ' Commits',        title_link: project.web_url,        text: data.commits.map(function (commit) {         return '  - ' + new Date(commit.timestamp).toUTCString() + ' [' + commit.id.slice(0, 8) + '](' + commit.url + ') by ' + commit.author.name + ': ' + commit.message.replace(/\s*$/, '');        }).join('<br>'),        color: NOTIF_COLOR       }]      }     };    };       Script.prototype.tagEvent = function tagEvent(data) {     var tag = data.ref.replace(/^.*?([^\/]+)$/, '$1');     return {      content: {       username: 'gitlab/' + data.project.name,       icon_url: data.project.avatar_url || data.user_avatar || '',       text: data.user_name + ' push tag [' + tag + ' ' + data.checkout_sha.slice(0, 8) + '](' + data.project.web_url + '/tags/' + tag + ')'      }     };    };       return Script;   })();`

**Comment by engelgabriel** [comment]
Integration script have been updated
