### ISSUE TITLE
Rocket.Chat Federaion is now working? Or not?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#30673]
Hello!

Tell me please.
Rocket.Chat Federaion is now working? Or not?
Or deprecated?

I want to connect two servers with a federation and I want to understand which method works now.

Thank you advance.

Version: 6.4.1

**Comment by lmauromb** [comment]
Rocket.Chat classic federation was deprecated starting 6.0, the recommended and supported solution is to enable Matrix Federation, which also opens the interoperability with Matrix homeservers.

More info can be found [here](https://docs.rocket.chat/~/changes/k7fzOgIYGo04wBdi1Drc/use-rocket.chat/workspace-administration/settings/federation)

**Comment by arpsyapathy** [comment]
> Rocket.Chat classic federation was deprecated starting 6.0, the recommended and supported solution is to enable Matrix Federation, which also opens the interoperability with Matrix homeservers.
> 
> More info can be found [here](https://docs.rocket.chat/~/changes/k7fzOgIYGo04wBdi1Drc/use-rocket.chat/workspace-administration/settings/federation)

@lmauromb 

Rocket.Chat Basic Federation is deprecated starting 6.0 - that's ok.

But Rocket.Chat Federation Network?
https://docs.rocket.chat/~/changes/k7fzOgIYGo04wBdi1Drc/use-rocket.chat/rocket.chat-federation

Or Rocket.Chat Federation Network = Rocket.Chat Basic Federation?

How can i make federation Rocket.Chat server 1 and Rocket.chat server 2? In 6.4 version

**Comment by lmauromb** [comment]
@arpsyapathy 

Yes, Rocket.Chat Federation Network = Rocket.Chat Basic Federation. 

The supported way for federation in 6.4 is by enabling the Matrix Bridge.

To connect RC server 1 and RC server 2, both servers will need their own attached Matrix homeserver and using Matrix they will be able to communicate.

You can find more about this here: https://docs.rocket.chat/~/changes/k7fzOgIYGo04wBdi1Drc/use-rocket.chat/workspace-administration/settings/federation/matrix-bridge

**Comment by arpsyapathy** [comment]
> @arpsyapathy
> 
> Yes, Rocket.Chat Federation Network = Rocket.Chat Basic Federation.
> 
> The supported way for federation in 6.4 is by enabling the Matrix Bridge.
> 
> To connect RC server 1 and RC server 2, both servers will need their own attached Matrix homeserver and using Matrix they will be able to communicate.
> 
> You can find more about this here: https://docs.rocket.chat/~/changes/k7fzOgIYGo04wBdi1Drc/use-rocket.chat/workspace-administration/settings/federation/matrix-bridge

I created two servers

1. Rocket.Chat Server + Synapse server. Configurired with official RC docs.
2. Rocket.Chat Server + Synapse server. Configurired with official RC docs.

But I don’t understand how to link them together into a federation :(

**Comment by lmauromb** [comment]
hey @arpsyapathy

Were you able to do the following steps:

1. Enable `Matrix Federation` on the App Settings
2. Create a new channel, with the federated option clicked
3. Invite a user from the other Rocket.Chat application

When inviting a user for the other RC application you need to add them with the following format:

```
@username:hostname
```

example,

username: user
hostname: test.example.com

```
@user:test.example.com
```

**Comment by arpsyapathy** [comment]
> hey @arpsyapathy
> 
> Were you able to do the following steps:
> 
> 1. Enable `Matrix Federation` on the App Settings
> 2. Create a new channel, with the federated option clicked
> 3. Invite a user from the other Rocket.Chat application
> 
> When inviting a user for the other RC application you need to add them with the following format:
> 
> ```
> @username:hostname
> ```
> 
> example,
> 
> username: user
> hostname: test.example.com
> 
> ```
> @user:test.example.com
> ```

Hey @lmauromb !

Thank you for helping me!
one question left

Federation now is totally enterprise? (Federation channel, private groups, dm etc)
Or in free version i can use some features of federation now?

**Comment by lmauromb** [comment]
@arpsyapathy more details could be found here: https://docs.rocket.chat/use-rocket.chat/rocket.chat-federation 

but yes the workflows you're describing would need an Enterprise license

**Comment by arpsyapathy** [comment]
@lmauromb Thank you very match!
