### ISSUE TITLE
[6.4.2/3/4] Custom OAuth (Keycloak) - OpenID Connect - issue with Firefox - working with Chromium

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#30688]
### Description:

Custom OAuth login (Keycloak) not working working with Firefox normal and privacy mode. Same on different OS (Linux and Windows 10). This was not the case with Rocket.Chat 6.3.10
Working with Chromium, Edge.

### Steps to reproduce:

1. Setup OAuth Provided with Keycloak and use Firefox 118.0.2 to login.
2. Entering credential into Keycloak
3. Redirect to Rocket.Chat reaches login page

### Expected behavior:

Getting logged into Rocket.Chat

### Actual behavior:

Staying on the login page

### Server Setup Information:

- Version of Rocket.Chat Server:  6.4.2 / 6.4.3 / 6.4.4
- Operating System:  Rocky Linux 8.8.
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version:  14.21.3
- MongoDB Version: 5.0.21

### Client Setup Information

- Browser Version: Firefox 118
- Operating System: Windows 10 and Fedora 39

### Additional context

Issue happened on my test system after upgrading to Rocket.Chat 6.4.2 from 6.3.10

### Relevant logs:

No error is present in the logs.

**Comment by TimmiORG** [comment]
@pierre-lehnen-rc 
do you think that your change could cause this?
https://github.com/RocketChat/Rocket.Chat/commit/f5a886a1445fde3d1698b6d1a143c127e2811126

**Comment by pierre-lehnen-rc** [comment]
specifically firefox?

**Comment by TimmiORG** [comment]
Yes only with Firefox.  Not able to login with FF on different OS. But always with other browsers.

**Comment by BigSnicker** [comment]
Likely the same issue as https://github.com/RocketChat/Rocket.Chat/issues/30545

**Comment by TimmiORG** [comment]
Hi @BigSnicker 
Oh I missed that, yes looks like the same to me as well.

**Comment by TimmiORG** [comment]
@pierre-lehnen-rc 
Thank you for looking into that.
