### ISSUE TITLE
Question: Debug log showing plain text LDAP credentials

### ISSUE THREAD

**Issue by rsvdl** [RocketChat/Rocket.Chat#3069]
Your Rocket.Chat version: 0.28.0 Docker

Hi Github,

No clue if this is working as expected or if it is something more serious:
When enabling debug logging under "Administration -> Logs -> Log Level 2" all succesful LDAP login usernames and passwords are logged in plain text under the "View Logs" option.

Is there any way to hide this information when enabling debug logging?

Thanks a bunch!

Example log: `I20160428-20:27:38.851(0) LDAPSync ➔ debug user { username: 'user',   email: 'user@example.net',   password: 'P@ssword',   _id: 'QQ7XxsSEj6xyd486p' } 
`

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
