### ISSUE TITLE
Disabling message avatars doesn't disable them in quotes

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#30709]
### Description:

When disabling avatars for messages, avatars are still shown when quoting a messages.

### Steps to reproduce:

1. Disable avatars in Account -> Preferences -> Messages -> Display Avatars
2. Write a message.
3. Write a second message quoting the first one.

### Expected behavior:

The quote does not show an avatar.

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/bac17388-4d46-427d-8663-e01c1b61303d)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.2
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.11

### Client Setup Information

The issue seems to be client-agnostic. However, I verified it with:

- Browser Version:
  - Chromium Version 118.0.5993.70 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 118.0.2 (64-bit)
- Operating System: Arch Linux

### Additional context

The avatar is also shown while composing a message quoting another one:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/b6191850-8d0d-43a0-81af-932bcdc222fe)

**Comment by hardikbhatia777** [comment]
@paulchen Should be fixed by #31393. Thanks for reporting :)
