### ISSUE TITLE
Editing a message doesn't show until full reload

### ISSUE THREAD

**Issue by drsybren** [RocketChat/Rocket.Chat#30726]
### Description:

After editing a message, the old message is still shown. It requires a reload of the webapp to show the edited message.

### Steps to reproduce:

1. Type a message
2. Press the UP cursor key
3. Edit your message, press ENTER
4. See that the old message is still shown in the channel
5. Press F5
6. See the edited message in the chanel.

### Expected behavior:

Immediately see the edited message in the channel.

### Actual behavior:

Old message is still shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.2
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.11 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Brave v1.59.122
- Operating System: Linux

### Additional context

This issue was introduced after we upgraded from 6.1.1 to 6.4.2. There are many things broken that seem to centre around a data connection between the RocketChat web client & server (notifications not coming through, unread message counts not being updated on receiving a message, inability to mark messages as unread).

### Relevant logs:

The bug reporting template links to https://docs.rocket.chat/resources/development-docs#gathering-logs but that link is dead. The page does *not* link to the relevant page in the developer documentation, but rather to the root URL. Neither the word "gathering" nor the word "log" can be found on that page, so it's a dead end.

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by Sayan4444** [comment]
I guess the issue has been solved as I am unable to replicate it. Can you check it?, if it persists a video of the issue will be very helpful

**Comment by drsybren** [comment]
I think this was solved, as I can't reproduce it either.
