### ISSUE TITLE
>v6.4.1: Layout -> Custom CSS is ignored after Rocket.Chat update and needs to be saved again to become effective

### ISSUE THREAD

**Issue by chotaire** [RocketChat/Rocket.Chat#30738]
### Description:

Starting with 6.4.0, when updating the docker version of Rocket.Chat, some contents in Workspace -> Settings -> Layout -> Custom CSS are being ignored after the update.

### Steps to reproduce:

1. Install Rocket.Chat Docker Version 6.4.0 or 6.4.1
2. Use Custom CSS
3. Update to Rocket.Chat Docker Version 6.4.2

### Expected behavior:

Until Version 6.4, the expected behavior is custom layout (user-defined CSS) to stay effective after a Rocket.Chat Update. 

### Actual behavior:

Some if not all content in Layout -> Custom (user-defined) CSS is being ignored after the update. It will be necessary to edit CSS and save again before it becomes effective. Updating the custom CSS has the side effect that all Rocket.Chat phone app users will be logged out of their apps. Since custom CSS is broken after every Rocket.Chat update, and CSS needs to be manually "fixed", this will log out all app users after every Rocket.Chat update, which is terrible. This also means that the forced refresh will load the faulty (non-custom) layout for all browser sessions and as thus web users are required to hard-reload their browsers after each Rocket.Chat version upgrade for the "fixed" custom layout to become visible again.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.2
- Operating System: Linux
- Deployment Method: docker-compose
- Number of Running Instances: 2
- DB Replicaset Oplog: activated
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.21

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 118.0.5993.118 (64-bit)
- Operating System: Windows 11 Pro Version 10.0.22621.2428

**Comment by phriedrich** [comment]
According to ticket #30627 this will be fixed with 6.5.0.

**Comment by chotaire** [comment]
Closed as duplicate.
