### ISSUE TITLE
Icon Batch is not showing unread messages anymore

### ISSUE THREAD

**Issue by thorstenhilker** [RocketChat/Rocket.Chat#30733]
Hi!
On my Mac the icon symbol is not showing unread messages any more.
The icon looks like the image I attached.
The "batch" doesn't change even when I have read all messages or if I get a personal message.

Greetings!
![Bildschirmfoto 2023-10-24 um 19 01 04](https://github.com/RocketChat/Rocket.Chat/assets/29892310/ede09d8e-4c2f-49e8-8493-1c505a1a4d4a)

**Comment by lalitkumawat1m** [comment]
Hello Team I want to work on this issue please assign to me

**Comment by CvH** [comment]
same as #30712 
currently no feedback from RC at all

**Comment by gabriellsh** [comment]
Duplicate issue, let's continue the discussion in https://github.com/RocketChat/Rocket.Chat/issues/30712 since it was opened first.

**Comment by gabriellsh** [comment]
I just left this comment there https://github.com/RocketChat/Rocket.Chat/issues/30712#issuecomment-1799474964 that might help you.
