### ISSUE TITLE
No Desktop Notifications on Linux/Gnome

### ISSUE THREAD

**Issue by ramedlawH** [RocketChat/Rocket.Chat#3075]
Your Rocket.Chat version:0.27
Rocket.Chat Client: 1.2.0
OS: Linux / Gnome

I cannot receive any desktop notifications from the client, although its enabled.
If I run a "Test Desktop Notifications" inside the client, it works.

I don't receive any notifications if someone mention my name or inside direct messages.

**Comment by waldemar21** [comment]
I think it has something to do with lags. If we have a big delay between sending and receiving messages, notifactions don't work. We cant even see the  "user is typing..." information if someone is typing.

**Comment by ramedlawH** [comment]
Notifications working again after updating on newest version of Rocket.Chat ;)
