### ISSUE TITLE
"message removed" only shown after reloading page

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#30791]
### Description:

If "Show Deleted Status" for messages is enabled, the text "message removed" is not visible after deleting a message. After reloading the page, it is shown.

### Steps to reproduce:

1. In Administration -> Settings -> Message, enable "Show Deleted Status". 
2. Delete a message.

### Expected behavior:

Instead of the message that has just been deleted, the text "message removed" is shown.

### Actual behavior:

For a short moment, the text "message removed" is visible before it vanishes. After reloading the page, the text "message removed" will be shown as expected.

https://github.com/RocketChat/Rocket.Chat/assets/404840/00b62134-ca1b-4a22-a9b8-a2428b0299d4

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.11

### Client Setup Information

- Browser Version: Chromium Version 118.0.5993.117 (Offizieller Build) Arch Linux (64-Bit)
- Operating System: Arch Linux

**Comment by Sayan4444** [comment]
unable to reproduce this issue

**Comment by paulchen** [comment]
> unable to reproduce this issue

I just did a quick retest on Rocket.Chat 6.5.0. I was unable to reproduce the problem as well. Therefore, I close the issue now.
