### ISSUE TITLE
Marketplace does not work without internet?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#30798]
Hello!

My rocket.chat server only works within a private local network and does not have access to the Internet.
When I try to go to the Marketplace section (to install the desired application from the archive), I see an endless load page and cannot do anything.

Does the marketplace not work without the Internet? Or can this be fixed somehow?

thanks in advance

Version 6.4.1

**Comment by 72tlukas72** [comment]
Same problem with version 6.3.10. I don't even see the apps which are already installed.

**Comment by hugocostadev** [comment]
You can only install private apps without network or you can enable rocket.chat in your private network...

Check the latests version, you should be able to go to the marketplace. Let me know if worked

**Comment by 72tlukas72** [comment]
Cool but limitation on 25 users??! Downgrade back...

**Comment by hugocostadev** [comment]
@72tlukas72 We've recently introduced a plan offering all enterprise features for free to groups with fewer than 25 users. For those with more users, you have the opportunity to try the enterprise features. After the trial period, the system will automatically revert to the community version. However, you have the option to bypass the trial in the admin settings. I emphasize that we are not imposing any restrictions.

For more information check the Announcement:  https://forums.rocket.chat/t/introducing-the-starter-plan-free-access-to-premium-features-for-limited-scale-use/18736/3
