### ISSUE TITLE
Layout glitch in extended channel list

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#30797]
### Description:

When the display mode for the channel list is set to "Extended", the last messages are cut off by a few pixels.

### Steps to reproduce:

1. Set the display mode for the channel to "Extended".

### Expected behavior:

The last messages of each channel are completely visible.

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/407d9405-1d9b-46ac-a223-239c77bfba08)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.11

### Client Setup Information

- Browser Version:
  - Chromium Version 118.0.5993.117 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 119.0 (64-bit)
- Operating System: Arch Linux

**Comment by robinreckmann** [comment]
Same here, I implemented a temporary fix for this in our instance via the custom CSS:

.message-body--unstyled {
  margin-left: 2px;
}

**Comment by MartinSchoeler** [comment]
Seems to be fixed on the latest version, closing this.

Thanks!
