### ISSUE TITLE
Dropping a file from another browser window creates two upload dialogs

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#30793]
### Description:

When dragging a file from another Chromium window and dropping it into a Rocket.Chat channel, the file upload dialog is shown twice.

### Steps to reproduce:

1. Open a Rocket.Chat channel in one Chromium window.
2. Open the image to be drag-and-dropped in another Chromium window.
3. Drag the image and drop it into the Rocket.Chat channel.

### Expected behavior:

One file upload dialog is opened.

### Actual behavior:

Two file upload dialogs are opened, one overlapping the other:

https://github.com/RocketChat/Rocket.Chat/assets/404840/ceee0db6-b7c9-424a-9e78-07f6af2c165d

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.11

### Client Setup Information

I was able to reproduce this with the following clients:

- Windows 10
  - Google Chrome Version 118.0.5993.118 (Offizieller Build) (64-Bit)
  - Microsoft Edge Version 118.0.2088.76 (Offizielles Build) (64-Bit)
  - Electron Client 3.9.9
- Arch Linux
  - Chromium Version 118.0.5993.117 (Offizieller Build) Arch Linux (64-Bit)

I was unable to reproduce this in Firefox 119.0, neither on Windows 10 nor on Arch Linux.

**Comment by paulchen** [comment]
> This issue cant be reproduced, can you recheck if it exists?

I just successfully reproduced it using
 - Rocket.Chat 6.5.1
 - Arch Linux, Chromium Version 120.0.6099.129 (Offizieller Build) Arch Linux (64-Bit)

**Comment by Sayan4444** [comment]
@paulchen very very thank you for the confirmation. It helped me to fix the exsisting problem. It will be fixed as soon as this PR gets merged
