### ISSUE TITLE
Have a place for blogs/posts or other stuff

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#308]
![image](https://cloud.githubusercontent.com/assets/1986378/8726540/47a6ea5e-2bb1-11e5-869c-ea818fa7feb1.png)
##

**Comment by graywolf336** [comment]
:+1: we use posts to create long responses or to releases some public information. Having the ability to allow posts to be viewed by anyone (not just members) would be awesome.

**Comment by graywolf336** [comment]
As I look into moving over from slack, this is one of the things which is missing as we have a few posts which need to be moved over along with us. Wondering what it would take to get this implemented..

**Comment by geekgonecrazy** [comment]
Trying to locate an issue I saw while looking through.  Mentioned message types.  Maybe we can give this a message type? Then get more put in for actually creating messages of those types?

**Comment by graywolf336** [comment]
Well posts should be able to set whether they're accessible from anyone inside or outside the organization, that way if you wanted to make a public announcement type thing you could do it with rocket.chat and link to it...at least that's my idea.

**Comment by IQ2022** [comment]
it would be nice if its accessible from the outside as well, and also your posts to be linked to your blog :D  sort of a live Blog Feed..

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.
