### ISSUE TITLE
Create an account is not working from v 6.4.2 [Email verification]

### ISSUE THREAD

**Issue by Cancer-zern** [RocketChat/Rocket.Chat#30811]
### Description:

Registration for the new account is not working the problem with Email confirmation looping

### Steps to reproduce:

1. Go to web site and Create an account
2. Fill the form and then "Join your team"
3. Got an Email and click the button "Verify your email"
4. Forward to the login page.
5. Try to Sign-In then forwarding me to email confirmation page again and again (looks like looping)

### Actual behavior:

![Clipboard - October 24, 2023 4_30 PM](https://github.com/RocketChat/Rocket.Chat/assets/68541237/2fffefb0-1a2a-4527-99a8-866850c68a7d)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.2 - 6.4.4
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

**Comment by paymanzafar1** [comment]
This problem is what I saw in logging to https://open.rocket.chat/home.

**Comment by Cancer-zern** [comment]
Version 6.4.8 has same issue

**Comment by Cancer-zern** [comment]
Version 6.5.0 has same issue
