### ISSUE TITLE
Lowercase rule for channel name not obeyed when updating a channel

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#3081]
Rocket.Chat 0.62.0 ensures new channels are always created with a lowercase name but when the channel is edited the lowercase rule is not applied and uppercase letters can be used in the name.

**Comment by bhbarbosa** [comment]
Hello, I can confirm it.

Rocket.Chat version: 0.37.1

Actually, when you create a private group with uppercase letters, Rocket.Chat converts it to lower case. However, you can rename the group with uppercase letters after creation on the right panel.

@marceloschmidt is it possible to make it just create with uppercase (remove the lowercase function when creating groups):

**Comment by Devact** [comment]
Hello, This is still an issue. 0.55.0-rc.3

**Comment by SeanPackham** [comment]
This is the intended behaviour, all channel names are converted to lowercase versions.

**Comment by TheReal1604** [comment]
@SeanPackham Ok, then we have an issue at the edit function of a channel. I can rename channels to uppercase names. This should be fixed.

![grafik](https://user-images.githubusercontent.com/5877910/37297538-3ae6e534-261e-11e8-87f6-199146d0171b.png)

**Comment by SeanPackham** [comment]
Thank you @TheReal1604 that is a new issue! I will update the title and description and reopen it.

**Comment by nikeee** [comment]
I did a PR for this issue.
