### ISSUE TITLE
Download Manger try to download contents automatically !

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#3082]
( even in last version of demo )
Hi 
i faced with this problem every time , after that i login to main chat page ,my download manager (i use IDM) try to download some content from page ...
is there any way to block them from detecting downloadable contents ?
some URL s that every time detected :
https://demo.rocket.chat/sounds/notify.ogg
https://demo.rocket.chat/sounds/door_chime.mp3

i should say that my download manger with this setting didn't do this in any sites , just see this problem in Rocketchat (And some time in Youtube  for downloading videos!  :laughing: )

**Comment by Sing-Li** [comment]
Yes. I see the same thing all the time.  Download manager is too smart in detecting what can be downloaded and it can change with every upgrade (they should since it is their entire business).  

Disable it for the browser you're Rocket.Chat ing with if you find it annoying.
