### ISSUE TITLE
[Bug]: The logo of the twitter is not updated

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [RocketChat/Rocket.Chat#30826]
### Description:

 The logo of the twitter is not updated . 

### Steps to reproduce:

1. Go to  website .
2. Scroll down website .
3. and at the end [footer] of the website 
4. see the logo of the twiiter .

### Expected behavior:
The twitter logo should be updated

### Actual behavior:

The twitter logo is not updated.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4
- Operating System:  widnows-11

### Client Setup Information

- Desktop App or Browser Version:  Chrome
- Operating System: Windows 11

### Additional context

<img width="864" alt="Screenshot 2023-11-01 162820" src="https://github.com/RocketChat/Rocket.Chat/assets/130988755/e0ac4017-2e33-4729-8ce0-7dcc7fb27bbe">

**Comment by REVANVEKAR** [comment]
I would like to work on this issue

**Comment by REVANVEKAR** [comment]
I'd like to take up this issue

**Comment by sampaiodiego** [comment]
thx for pointing it out, the website team is already aware of this.. I'm closing this issue since this repository is not related to our website.

**Comment by anniepauline** [comment]
@sampaiodiego May I know the repo that is related to the website so that I can work on the issue?
