### ISSUE TITLE
There Should be a Cancel ❌ button when user don't want to edit on TextArea.

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [RocketChat/Rocket.Chat#30821]
### Description:

Clicking on the Edit Button, the Textbox is highlighted with yellow color showing that we are editing the text. But what if the user doesn't want to edit? `There should be a cancel Button for this`.

### Steps to reproduce:

1. Go to Teams/Channel
2. Click on any of the teams/Channels where you are participant.
3. Try to Send a Text to the Team/Channel
4. Try to Edit the Text and See that there is no Cancel Button for Edit Text if the user wants to continue without editing the Text.

### Expected behavior:

There Should be a `Cancel Button ❌`  to continue without Editing the Text.

### Actual behavior:

No Such Cancel Button is found on the open. rocket.chat 

### Client Setup Information

-  Browser Version: Chrome Version 118.0.5993.118 (Official Build) (64-bit)
- Operating System: Windows 11

### Screenshot 
<img src="https://i.imgur.com/YNXP4oV.png"/>

**Comment by hugocostadev** [comment]
Today you can press ESC to dismiss the edition...

No need to ask for permission, feel free to work on it! 
Just check if someone it's already raised a PR for that (should be linked in this issue).
Best of luck 🚀 👏 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Sayan4444** [comment]
@hugocostadev is this feature request valid ,I mean do you want this feature in the website? If yes then I will start working right away

**Comment by Sayan4444** [comment]
Hi @Gurmeet-Singh657 I just worked this issue out exactly how DISCORD did it. If you have a better UI please do share it with me and I will implement it

**Comment by Gurmeet-Singh657** [comment]
That's nice. Go with your UI. I just found the issue and raised that so that anyone can work on this 😊
