### ISSUE TITLE
is the read receipts feature enabled back?

### ISSUE THREAD

**Issue by dkhokhlov** [RocketChat/Rocket.Chat#30836]
is the read receipts feature enabled back? 
in which version?

6.5 is not published on docker hub.

**Comment by krenuser** [comment]
Do you use Enterprise version? 
It's enterprise feature now, since RC 6.0, as I remember.

**Comment by 72tlukas72** [comment]
This feature was (re)moved from community edition to enterprise edition :-(

**Comment by dkhokhlov** [comment]
I am using image: 

registry.rocket.chat/rocketchat/rocket.chat:6.4.4 

according to this video the read receipts should be back in v6.5:

https://forums.rocket.chat/t/update-6-0-0-read-receipts-complaint/16164/80

**Comment by casalsgh** [comment]
As mentioned by @dkhokhlov answered on above thread that shares the following video -> https://youtu.be/6prKzkw_VAI ([48:01])

**Comment by casalsgh** [comment]
6.5.0 expected for end of November
