### ISSUE TITLE
Searching for permissions is unintuitive

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#30835]
### Description:

Searching for certain permissions in Administration -> Permissions does not always lead to the result I would expect.

### Steps to reproduce:

1. Log in using an admin.
2. Set your language to English.
3. Navigate to Administration -> Permissions.
4. Search for "mention".
5. Search for "mention all".
6. Set your language to German.
7. Navigate to Administration -> Berechtigungen.
8. Search for "erwähnen".

### Expected behavior:

Step 4: I find the permissions "Mention All" and "Mention Here".
Step 5: I find the permission "Mention All".
Step 8: I find the permission "Alle".

### Actual behavior:

Step 4 works as expected:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/ec469b69-0207-4d1b-b527-0753db057273)

Step 5 does not show any result:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/8d9fafb8-e107-47c5-83d3-a15b4045da14)

Step 8 does not show anything either:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/2ad316db-4e40-416d-b90f-871f02ec155f)

### Additional context

When setting the language to German and searching for the English term "mention", both permissions can be found:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/a8e0dfc7-8f0e-4d91-9057-449e336af4d6)

**Comment by CvH** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/22295
nobody from RC cares :)

**Comment by paulchen** [comment]
> #22295 nobody from RC cares :)

Oh. For some reason I did not find that issue when checking for an already existing report of this problem. I close this issue now as a duplicate.
