### ISSUE TITLE
Unreadable download 

### ISSUE THREAD

**Issue by chelceacalin** [RocketChat/Rocket.Chat#30847]
This is what I see when trying to download anything

![image](https://github.com/RocketChat/Rocket.Chat/assets/76866499/fd2da78d-8d2e-47ed-8b5f-0a34bd25d220)

**Comment by debdutdeb** [comment]
Sorry you should post on some linux forum. Probably on linux mint forum? 

Also looks like you're simply missing fonts. 

This is rocket.chat's github issue page .. not related to linux in general 😬
