### ISSUE TITLE
RC warns at startup that MongoDB 4.4.x is deprecated, but it is not

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#30888]
### Description:

On startup, RC says:

```
+----------------------------------------------------------------------+
|                              DEPRECATION                             |
+----------------------------------------------------------------------+
|                                                                      |
|  YOUR CURRENT MONGODB VERSION (4.4.25) IS DEPRECATED.                |
|  IT WILL NOT BE SUPPORTED ON ROCKET.CHAT VERSION 7.0.0 AND GREATER,  |
|  PLEASE UPGRADE MONGODB TO VERSION 5.0 OR GREATER                    |
|                                                                      |
+----------------------------------------------------------------------+
```

But MongoDB 4.4's service EOL is not until February 2024.

### Steps to reproduce:

1. Run RC against MongoDB 4.4.x
2. View the RC log and/or run RC and view the banner at the top warning about the deprecation.

### Expected behavior:

RC should not warn that MongoDB 4.4 is deprecated when it is not.

### Actual behavior:

RC warns that MongoDB 4.4 is deprecated (even though it is not).

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.10
- Operating System: RHEL7
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yup
- NodeJS Version: 14.21.3
- MongoDB Version: 4.4.19, 4.4.25

**Comment by paulchen** [comment]
Maybe the message should be changed to state that Rocket.Chat's support for MongoDB 4.x is deprecated instead of stating that MongoDB 4.x itself is deprecated.

**Comment by reetp** [comment]
Mongo 4.4 is EOL in Feb 2024, Mongo 5.0 in Oct 2024 and 6.0 in Jul 2025

(I hope they are not going to enforce the use of rapid release versions)

Mongo 5+ requires the AVX instruction set so will probably kill a lot of older hardware.

https://www.mongodb.com/support-policy/lifecycles

On 6.5.0 we get this from the Rocket bot

Rocket Cat @rocket.cat
7:02 PM
MongoDB Deprecated
**MongoDB version %s is deprecated, please upgrade your installation.**
https://go.rocket.chat/i/mongodb-deprecated

That is despite this being set in the docker compose file:

BYPASS_MONGO_VALIDATION=true

`%s`  ? 

Hmmm. All a bit messy and inaccurate.

**Comment by hugocostadev** [comment]
Hey @KevLehman any thoughts?

I think that this was introduced in https://github.com/RocketChat/Rocket.Chat/pull/27891 

The message shouldn't be checking `>=4.4.0` instead of `>=5.0.0` ?

**Comment by casalsgh** [comment]
Team, the mention of deprecated was deprecated for Rocket.Chat. 
Now we also deprecated MongoDB 5 as it reached EoL per Mongo. 

Please consider moving to 7.0.0 Rocket.Chat with at least Mongo 6 -> https://github.com/RocketChat/Rocket.Chat/releases/tag/7.0.0

**Comment by ggazzo** [comment]
the idea behind the message is not keep tracking of EOL mongo databases. but inform that rocket.chat no longer offer support. which means no tests or no fixe, in case of bugs found in this specific version. so you should upgrade. 

should be closed by https://github.com/RocketChat/Rocket.Chat/pull/33907
