### ISSUE TITLE
rocket.chat does not have these features

### ISSUE THREAD

**Issue by jaffer0808** [RocketChat/Rocket.Chat#30895]
1. When converting languages eesti to other languages, it is easy to report errors due to the large number of messages.
2. The chat window search cannot find pictures with text records.
3. Wrong messages cannot be revoked in time, but can only be deleted. It is best for the parties concerned to revoke them.

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the question! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
