### ISSUE TITLE
The link to verify the email does not work

### ISSUE THREAD

**Issue by sanraymer** [RocketChat/Rocket.Chat#30890]
Why doesn’t the confirmation email work (THE LINK, THE EMAIL ARRIVES)? Not even with open.rocket.chat

For example, if I register and enter my email, I receive it, I press the link ([https://open.rocket.chat/#/verify-email/aGkyZPLkbT1j44vxTp4ldXXVNldvR49zWm_nmmDK61K](https://open.rocket.chat/#/verify-email/aGkyZPLkbT1j44vxTp4ldXXVNldvR49zWm_nmmDK61K)) and nothing happens, it redirects me to home without doing anything else.

![image](https://github.com/RocketChat/Rocket.Chat/assets/54831765/6cec9fdb-5f12-4614-ad68-2699c551f80e)

±--------------------------------------------------+
| SERVER RUNNING |
±--------------------------------------------------+
| |
| Rocket.Chat Version: 6.4.5 |
| NodeJS Version: 14.21.3 - x64 |
| MongoDB Version: 6.0.11 |
| MongoDB Engine: wiredTiger |
| Platform: linux |
| Process Port: 3000 |
| Site URL: https://mysite.com/ |
| ReplicaSet OpLog: Enabled |
| Commit Hash: edb6cae740 |
| Commit Branch: HEAD |
| |
±--------------------------------------------------+

After pressing the verification link, [open.rocket.chat/#/verify-email/aGkyZPLkbT1j44vxTp4ldXXVNldvR49zWm_nmmDK61K](https://open.rocket.chat/#/verify-email/aGkyZPLkbT1j44vxTp4ldXXVNldvR49zWm_nmmDK61K) I log in with my account and the same thing appears.

THE SAME HAPPENS ON MY WEBSITE. What is the solution?

![image](https://github.com/RocketChat/Rocket.Chat/assets/54831765/b63707fe-b881-4be3-9826-324c3b9dbbf2)

In the logs I see an alert and I don’t know if it is related:
{“level”:40,“time”:“2023-11-04T16:43:07.066Z”,“pid”:17641,“hostname”:“ip-000000000”,“name”: “DeprecationWarning”,“section”:“METHOD”,“msg”:“The method "sendConfirmationEmail" is deprecated and will be removed on version 7.0.0”}

**Comment by AMalfez** [comment]
Hi!
Could you tell me the name of the file and where it is located?
The file in which you declared sendConfirmationEmail method.

**Comment by sanraymer** [comment]
I saw it in the web logs, not in any file. /admin/logs

But I insist, that problem also happens in https://open.rocket.chat/ so I think it comes in the source code not in my environment.

Do you know what the problem could be?

**Comment by Puer-Vetus** [comment]
I'm seeing the same behavior. Getting the same message in the rocket chat server output/log. The email arrives to the user, but the link to verify just takes them to the login screen and doesn't verify the email, even if they re-login on that screen.

Version
6.4.5
Apps Engine Version
1.41.0-alpha.312
Node Version
v14.21.3
Database Migration
303 (November 10, 2023 3:20 PM)
MongoDB
6.0.11 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (edb6cae74)
Branch: HEAD

**Comment by sanraymer** [comment]
I think it's a Rocket Chat bug. In which file do you think the solution may be?

**Comment by Dog1ch** [comment]
Same on 6.4.1

**Comment by hugocostadev** [comment]
We are working on this problem, thanks for reporting! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
