### ISSUE TITLE
Some of the translation keys are missing in Hindi translation 

### ISSUE THREAD

**Issue by its-kunal** [RocketChat/Rocket.Chat#30892]
### Description: 

There are lots of keys missing in `hi-IN.18N.json` as compared to `en.i18n.json` file available in the `apps/meteor/packages/rocketchat-i18n/i18n` folder

### Steps to reproduce:

1. Go to-  `apps/meteor/packages/rocketchat-i18n/i18n`

### Expected behavior:

There should be a translation present for all the keys.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by its-kunal** [comment]
I would to like contribute in this issue.

**Comment by MartinSchoeler** [comment]
Hey @its-kunal No need to ask for assignment, feel free to contribute! It should be relatively simple, just add the keys and values to the translation file and open a PR. Thanks!

**Comment by its-kunal** [comment]
Hey @MartinSchoeler Please review my pull request - #30927

**Comment by notlelouch** [comment]
is this issue still open?

**Comment by its-kunal** [comment]
Hey @MartinSchoeler Please review my pull request - #30927
