### ISSUE TITLE
Screen sharing not possible in mac os x client

### ISSUE THREAD

**Issue by pboos** [RocketChat/Rocket.Chat#3090]
Rocket.Chat Server version: 0.28.0
Rocket.Chat Mac OS X Client: Version 1.3.1 (15)

When going to share the screen in the desktop app (downloaded from apple store), it asks to install the plugin. Clicking on the link does not do anything.

I have the plugin installed in chrome and it works fine in chrome.

Would be great to have screen sharing work as well out of the desktop app. But I wonder if that is actually possible.

**Comment by marceloschmidt** [comment]
It is not working for Electron apps. We should at least remove the button in that case. But we'll look for a solution to this.

**Comment by geekgonecrazy** [comment]
@pboos created a ticket on the desktop client repo: https://github.com/RocketChat/Rocket.Chat.Electron/issues/188 please follow that.

**Comment by MartinSchoeler** [comment]
@pboos https://github.com/RocketChat/Rocket.Chat.Electron/pull/337 fixed this.
