### ISSUE TITLE
Encryption password not shown

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#30923]
### Description:

When the profile language is set to German, the encryption password will not be shown in the password window.

### Steps to reproduce:

1. Create an account on https://open.rocket.chat/.
2. You should see this banner:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/6c3f89e6-6794-41b6-8e9d-55caa4a5f62a)

3. Set your profile language to German. The banner should now look like this:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/4d68b1fd-49fc-4546-af50-425396cb5006)

4. Click on the banner.

### Expected behavior:

The window that is opened shows the encryption password.

### Actual behavior:

The window shows `%s` instead of the password:

![image](https://github.com/RocketChat/Rocket.Chat/assets/404840/6f95c986-e923-4ee6-aa3c-961f74a47a07)

However, the button for copying the password works as expected.

If the profile langauge is set to English, the password will be shown.

### Server Setup Information:

I don't know. Ask the guys running https://open.rocket.chat/. 🙂 

### Client Setup Information

- Browser Version: Google Chrome Version 119.0.6045.106 (Offizieller Build) (64-Bit)
- Operating System: Windows 10

**Comment by andys448** [comment]
The same issue on 6.3.10
