### ISSUE TITLE
rocketchat .28 does not run from a subfolder

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#3092]
Your Rocket.Chat version: .28

> git clone -b 0.28.0 https://github.com/RocketChat/Rocket.Chat.git
> export ROOT_URL=https://www.site.com/chat
> cd Rocket.Chat
> meteor

When I load www.site.com/chat/ the packages and css are still being loaded from /

The good: assets and images have relative URLs
![images and assets have relative url](https://cloud.githubusercontent.com/assets/6703876/14945311/7a325eee-0fc3-11e6-84c3-ae1dee07a515.png)

The bad: css, packages and app still had absolute url with /
![packages have absolute url](https://cloud.githubusercontent.com/assets/6703876/14945306/643d5f26-0fc3-11e6-9e37-42a1f7d93e49.png)

![css has absolute url](https://cloud.githubusercontent.com/assets/6703876/14945309/6d79665c-0fc3-11e6-9477-641f856ad036.png)

![app has absolute url](https://cloud.githubusercontent.com/assets/6703876/14945310/71d4f6a8-0fc3-11e6-8625-41609e134e29.png)

I tried this previously in version .25 (Please see issue #2655 ), I am creating a new issue since I am now trying this with a new version.

Other issues that I have read through: #2646

**Comment by alvarow** [comment]
This is still happening on 0.42.0 as well ... I see almost all assets being properly referred, but the last javascript is still not relative on the initial loading page, see below the `/` before the filename:

 `<script type="text/javascript" src="/3d8acf37edaf1fec0f40b7373b31fb0ea14581a2.js?meteor_js_resource=true">`

Hoping this is a quick fix

**Comment by MaluNoPeleke** [comment]
Still the same problem with 0.43

**Comment by steedos** [comment]
open meteor shell on dev env and enter the following command will fix this
WebAppInternals.setBundledJsCssPrefix("/chat") 

It seems it's cause by 
Rocket.Chat/packages/rocketchat-lib/server/startup/settingsOnLoadCdnPrefix.coffee

**Comment by MaluNoPeleke** [comment]
Can this be included in the next release, @engelgabriel ?

**Comment by Hudell** [comment]
This has already been fixed.
