### ISSUE TITLE
Can't integrate with Crowd

### ISSUE THREAD

**Issue by ShelestSergey** [RocketChat/Rocket.Chat#30932]
### Description:

Integration with Crowd doesn't work. When I try to login using Crowd credentials, nothing happens. But in logs I see, that method authenticate doesnt return correct answer.
### Steps to reproduce:

1.  Open Rocket.Chat
2.  Enter login and password 
3. Press login button

### Expected behavior:

Rocket.Chat create new user from crowd and authorize to chat

### Actual behavior:

Nothing happens...

### Server Setup Information:

Rocket.Chat Version: 6.4.5                   
NodeJS Version: 14.18.3 - x64           
MongoDB Version: 5.0.22                  
MongoDB Engine: wiredTiger              
Platform: linux                   
Process Port: 3000                    
Site URL: https://chat.*****.**  
ReplicaSet OpLog: Enabled                 
Commit Hash: edb6cae740              
Commit Branch: HEAD                                                            

Crowd:
Version5.2.0
Build number1941

### Client Setup Information

- Desktop App or Browser Version: FireFox 119.0.1
- Operating System: Windows 11

### Additional context

Crowd and Rocket.Chat running on same server with nginx.
I created App in crowd and assign group with users.
Test connection works fine.
I tested all crowd API methods with credentials by Postman and they work.

Logs:
{"level":30,"time":"2023-11-12T18:12:35.087Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"Extracting crowd_username"} 
{"level":20,"time":"2023-11-12T18:12:35.089Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"Could not find a user by email '#useremail#'"} 
{"level":20,"time":"2023-11-12T18:12:35.089Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"Could not find a user by username"}
 {"level":20,"time":"2023-11-12T18:12:35.090Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"Could not find a user with by crowd_username '#useremail#'"}
 {"level":20,"time":"2023-11-12T18:12:35.090Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"New user. User is not synced yet."} 
{"level":20,"time":"2023-11-12T18:12:35.090Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"Going to crowd: '#useremail#'"}
 {"level":20,"time":"2023-11-12T18:12:35.091Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"Auth result: %j"} {"level":30,"time":"2023-11-12T18:12:35.091Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"False result \"!auth\". Could not authenticate... '#useremail#'"} {"level":20,"time":"2023-11-12T18:12:35.091Z","pid":497191,"hostname":"loin","name":"CROWD","msg":"User #useremail# is not allowd to access Rocket.Chat"} 

"Auth result: %j" - is my custom logger message to realize what happened on auth.
Thats the result of this line:  const auth = Promise.await(this.crowdClient.user.authenticate(crowdUsername, password)
but _doRequest in user.authenticatу works fine and return in callback res correct JSON. But I think(JS is not my language), return is wrong. But maybe I missed something in configuration due to lack of docs...

**Comment by basvanbeeknl** [comment]
in latest version of Rocketchat v6 the login page does not work either. When submitting the form the page shows GUI Error.
When we disable the Crowd integration the login form behaves normally.

Please prioritize this issue, otherwise users that use Crowd integration cannot upgrade from v5 to v6.

**Comment by ShelestSergey** [comment]
I think the main problem is that atlassian-crowd-patched node module made with callbacks, but Rocket.Chat v. 6.5 using promises.
Based on that all functions of class CROWD in app.js don't receive return values.

**Comment by ShelestSergey** [comment]
So... I'm very close to resolve my issue.
As I said before main problem is using Promise in main app.js and callbacks in crowd module.
Next problem is that in authenticate function in app.js is string "crowdUser.password = password;" but in fetchCrowdUser return doesn't have this field. 
So the solutions is:
1. In return section of fetchCrowdUser(crowdUsername) add string: "		password: '' " after "        crowd_username: crowdUsername,"
2. In index.js of at atlassian-crowd-patched module function _doRequest have to refactor to use Promise. 
Somehow like that...
> 
  return new Promise((resolve, reject) => {

  var data = "", error;
> 
and all callbacks in code change to reject or resolve..
After I did this, I've could create user from Crowd after using crowd login credentials.
I think, I can attach my solution on weekend. Have a lot of work
