### ISSUE TITLE
Do calls work in the federation?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat#30944]
Hi all!

Tell me please.
Do calls work in the federation? (rooms, dm)
In Jitsi or Pexip?
Or are calls only in plans for implementation for now?

Thank you

**Comment by lmauromb** [comment]
@arpsyapathy VideoConf options are not available at the moment on federated rooms/dms. 

A work in progress is available at #29254, but not plans to get released soon.
