### ISSUE TITLE
Translation placeholders displayed instead of actual translation text (including default lang)

### ISSUE THREAD

**Issue by dazoot** [RocketChat/Rocket.Chat#30940]
### Description:

Instead of translated text or English text we see translation place holders

### Steps to reproduce:

Even after changin language we still see translation place holders instead of actual translated text.

Ex: `component.login`

![image](https://github.com/RocketChat/Rocket.Chat/assets/1543455/356da10b-eb71-44b8-b896-df82d595809a)

### Expected behavior:

See the actual translation or the default English text.

### Actual behavior:

Translation placeholder are shown.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.5
- Operating System: Debian 10
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version:  v14.21.3
- MongoDB Version: 4.4.25 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: desktop latest 3.9.9 and browser
- Operating System: Windows / Mac

**Comment by hardikbhatia777** [comment]
Hello @dazoot, can you provide proper steps to replicate the issue? 
![image](https://github.com/RocketChat/Rocket.Chat/assets/98163873/e0e24a35-2c95-496d-aad9-fa81069a8bb5)

It appears to be working fine for me. Thanks!

**Comment by dazoot** [comment]
We did not do anything specific. We have keep upgrading the rocket chat server until i have noticed that translation does not work anymore. No matter what language i choose in personal profile or server admin, we only see the placeholders.

**Comment by bmanolov** [comment]
:heavy_check_mark: With the update to **6.6.0** the problem has been resolved.

Thank you!

**Comment by dazoot** [comment]
Looks good.
