### ISSUE TITLE
[visual] In history mode the "new message" flag overlapped with recent bar

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#3095]
Your Rocket.Chat version: 0.28

![image](https://cloud.githubusercontent.com/assets/16319433/14953074/bea19602-106e-11e6-93bb-e60c16f82572.png)

**Comment by MartinSchoeler** [comment]
Hey @{name}, I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
