### ISSUE TITLE
Broken images after direct navigation

### ISSUE THREAD

**Issue by Borfswitch** [RocketChat/Rocket.Chat#3096]
If you navigate directly to a channel, or any other page by url (e.g. https://domain.com:3000/channel/general), the rocketchat logo in the bottom left corner of the window breaks. You have to navigate to the root in order to get the image to show up.

I'm using Chrome and RocketChat 0.25.0.

**Comment by marceloschmidt** [comment]
Does this happen in the demo as well? Please try https://demo.rocket.chat/channel/general and let me know. I have tried reproducing it and it didn't happen. If it doesn't happen for you in the demo, please update your instance to the latest version and try again.

**Comment by Borfswitch** [comment]
Seems to be fixed in 0.28.0. Thanks!
