### ISSUE TITLE
Text input bug

### ISSUE THREAD

**Issue by VictorSCamargo** [RocketChat/Rocket.Chat#30965]
### Description:

Chat text visualization bug that happens when you change the chat while writing text with multiple lines.

### Steps to reproduce:

1. Open a chat
2. Write a line of text
3. Create a new line with Shift+Enter and write something more
4. Change to another chat
5. Return to chat where you were writing
6. Try to edit the second line of text you were writing

### Expected behavior:

See all the text I was writting

### Actual behavior:

Only first text line is showed and the rest is shown only after I create a new line with Shift+Enter.

### Server Setup Information:

- Version of Rocket.Chat Server: 
I cannot check it and I dont have time for it right now, sorry.

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 115.0.5790.110 (Official Build) (64-bit)
- Operating System: Ubuntu 22.04

### Relevant logs:

Dont have access.

**Comment by Thanush19** [comment]
i can fix this @VictorSCamargo
