### ISSUE TITLE
Enabling the dark mode according to the user settings.

### ISSUE THREAD

**Issue by rishabh02dev** [RocketChat/Rocket.Chat#30970]
This is not an option for the dark mode switch in the application rocket.chat.

This is an issue that I have encountered as well. I am not sure if it is a bug or if it is intentional. However, I would like to see this feature implemented.

Reasons for supporting this feature

User satisfaction: Many users prefer to use dark mode, as it can reduce eye strain and improve sleep quality. By enabling dark mode for GitHub issues, you would be making your application more enjoyable for a wider range of users.

Accessibility: Dark mode can also be helpful for people with visual impairments. By enabling dark mode, you would be making your application more accessible to a wider range of users.

Consistency: Many other applications - such as Slack and Trello - already offer dark mode. By enabling dark mode, you would be aligning your application with the expectations of many users.
How to implement this feature

### Steps to reproduce:

CSS Code

body {
  background-color: #222;
  color: #fff;
}

a {
  color: #ccc;
}

img {
  brightness: 1.2;
  border: 1px solid #fff;
}

One way to implement this feature would be to add a new toggle switch to the settings menu. This toggle switch would allow users to enable or disable dark mode.

Another way to implement this feature would be to make the application automatically switch to dark mode based on the user's system settings. This would be a more user-friendly solution, as it would not require the user to manually change the settings.

### Expected behavior:

Dark mode is a display setting that reduces the brightness of the interface and uses darker colors, such as black or gray. It is often used in digital devices, such as smartphones, tablets, and computers, to reduce eye strain and improve sleep quality.

Improved readability

Dark mode can improve readability by increasing the contrast between the text and background. This can be especially helpful in low-light conditions, such as when you are using your device in bed or in a dark room.

Reduced eye strain

Staring at a bright screen for long periods of time can cause eye strain, which can lead to headaches, blurred vision, and other symptoms. Dark mode can help to reduce eye strain by reducing the amount of blue light that is emitted by the screen. Blue light is a type of light that can suppress melatonin production, a hormone that helps to regulate sleep.

Improved sleep quality

Blue light can also interfere with sleep. By reducing the amount of blue light that is emitted by the screen, dark mode can help to improve sleep quality.

Extended battery life

On OLED screens, dark mode can extend battery life. This is because OLED pixels only emit light when they are displaying a color. When a pixel is displaying black, it does not emit any light. This means that using dark mode can reduce the amount of power that is used by the screen.

Reduced glare

Dark mode can also reduce glare, which can be helpful when you are using your device in bright light.

Reduced sensitivity to light

Dark mode can be helpful for people who are sensitive to light. This is because it can reduce the amount of light that is emitted by the screen.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Gummikavalier** [comment]
LLM AI generated issue report?

Nevertheless the dark mode is in already.

**Comment by rishabh02dev** [comment]
Yes
