### ISSUE TITLE
Channel description links opens in RocketChat instead of default web browser

### ISSUE THREAD

**Issue by Ahmad-Ali-com** [RocketChat/Rocket.Chat#30971]
When we click on a link pasted under a channel description that stays at the top of that channel as an announcement bar, the link opens within RocketChat instead of going installed/default web browser and you would have to go back via `View menu` > `Back` in order to get back to you chats. Can anyone please help fix this issue, it is really annoying.

![image](https://github.com/RocketChat/Rocket.Chat/assets/45877486/ea15063a-3ee1-4b99-aeed-cc6163096c9e)

**Comment by Ahmad-Ali-com** [comment]
This issue is same for almost a year now, currently i am using 3.9.10 and the issue is still there.

**Comment by Ansh101112** [comment]
Will try to fix it and submit the pr asap.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/) provides **security** support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
