### ISSUE TITLE
Outgoing webhook not working: joinRoom -> Not allowed

### ISSUE THREAD

**Issue by irmela** [RocketChat/Rocket.Chat#3098]
Version: 0.28.0
I'm getting the same error as described in #2903 .
I've implemented the RocketGif Integration and it worked a few times but then it stopped working and I'm getting this error. Restart Server didn't solve the Problem.

`Exception in callback of async function: Error: [methods] joinRoom -> Not allowed [403] at [object Object].Meteor.methods.joinRoom (server/methods/joinRoom.coffee:10:14) at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26) at maybeAuditArgumentChecks (livedata_server.js:1698:12) at livedata_server.js:1611:18 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at [object Object]._.extend.apply (livedata_server.js:1610:45) at [object Object]._.extend.call (livedata_server.js:1553:17) at [object Object].<anonymous> (server/processWebhookMessage.js:36:20) at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)`

**Comment by marceloschmidt** [comment]
Can you please confirm that the user is in the `bot` role? You do that by going to Administration, then Permissions, then clicking to edit the `bot` role. There you can see the users that belong to this role.
