### ISSUE TITLE
[ench] Decreasing registration page font size to improve ui

### ISSUE THREAD

**Issue by PrakharSachan5342** [RocketChat/Rocket.Chat#30988]
### Description:

The text "Send your first message in minutes." font is too big , its not looking good 
If we decrease font size of "Send your first message in minutes." it will surely increase ui/ux

### Steps to reproduce:

1. Go to website 
2. click on "[Get started — it's free]" at landing page 
3. you will see a registration page 

### Expected behavior:

The text "Send your first message in minutes." font is too big , its not looking good 
If we decrease font size of "Send your first message in minutes." it will surely increase ui/ux

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/91385023/bf023241-3caf-41f0-8a39-ec0d7b628d7a)

**Comment by pankaj-2503** [comment]
Yeah , I agree with you as this is too big text it's font size must have to be decreased for better ui.  How about this i have changed the font-size to 70px.
![image](https://github.com/RocketChat/Rocket.Chat/assets/90036864/7219fb88-dd5b-482c-99f4-9b2dc642b893)

**Comment by pankaj-2503** [comment]
If you then  agree you can assign this to me , I can fix this.

**Comment by pankaj-2503** [comment]
If you agree then you can assign this to me I will fix this issue.

**Comment by MartinSchoeler** [comment]
Hello! Unfortunately our website is not currently an open source repo, and this repo is specific to the rocket.chat application, so I will be closing this, but don't worry, I'll pass your feedback to the team in charge of the website.

Thanks!
