### ISSUE TITLE
 ¯\_(ツ)_/¯ "/shrug" command out put is incorrect.

### ISSUE THREAD

**Issue by krispayne** [RocketChat/Rocket.Chat#30987]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Operating System Version

macOS 13.6.2

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.9.9

### Rocket.Chat Server Version

6.4.5

### Describe the bug

when typing the slash command "/shrug" a user can print  "\`¯\_(ツ)_/¯\`". When that message is sent the first "\" is removed:  "¯_(ツ)_/¯" . This is resolved by enclosing the command in a code block.

![Screenshot 2023-11-14 at 3 24 47 PM](https://github.com/RocketChat/Rocket.Chat.Electron/assets/70580/a1ad13d1-93b8-4a06-aea1-19c9b01a3cf5)
![Screenshot 2023-11-14 at 3 25 27 PM](https://github.com/RocketChat/Rocket.Chat.Electron/assets/70580/7290409a-8ebb-45a3-838d-7f8c98648a87)
![Screenshot 2023-11-14 at 3 25 32 PM](https://github.com/RocketChat/Rocket.Chat.Electron/assets/70580/0eb41439-acce-4257-873a-6d24a6def047)

### How to Reproduce

1. open a message that requires you to offer your genuine sentiment of "idk"
2. type /shrug.
3. 

### Describe your Expected behavior

/shrug produces `¯\_(ツ)_/¯` 

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by StorytellerCZ** [comment]
Just tried on v6.4.8 and it worked as it should.

**Comment by hugocostadev** [comment]
are you sure about your version?  Here it worked as expected... We had this issue prior 5.2 but it was fixed
