### ISSUE TITLE
RocketChat 6.4.x fails to load

### ISSUE THREAD

**Issue by spl0k** [RocketChat/Rocket.Chat#30990]
### Description:

After upgrading from RocketChat version 6.3.3 to any of the 6.4 versions (actually tested with 6.4.0 and 6.4.6), it fails to load (or more accurately, it fails to display). Trying to access it show the three dots "spinner" and it stays stuck here.

### Steps to reproduce:

1. Start from a working 6.3 installation
2. Upgrade it to 6.4
3. Try to access it. If a tab (when viewing from a browser) or the desktop app was already open, refresh it.

### Expected behavior:

RocketChat should load properly

### Actual behavior:

When accessing it, it stays on the three dots spinner.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.0 and 6.4.6
- Operating System: Debian 12
- Deployment Method: Manual install from tarballs
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.11

### Client Setup Information

- Desktop App Version: 3.9.10
- Browser Version: Opera 104.0.4944.54
- Operating System: Windows 10

### Additional context

I already searched for similar issues and some also report being stuck on the 3 dots. As those mention the site URL it should be noted that this happens on a staging environment where the site URL stored in DB doesn't match the one actually used to access the instance.

### Relevant logs:

Server logs don't show anything of interest. Just the "SERVER RUNNING" box when startup finished and nothing more.

The clients on the other hand...
```
Uncaught (in promise) Error: Cannot find module '/client/polyfills/index.ts'
    at y (url_common.js:80:1)
    at g (url_common.js:80:1)
    at d.r [as require] (url_common.js:80:1)
    at d.x [as link] (verifyErrors.js:34:1)
    at verifyErrors.js:34:1
    at dynamics_browser.js:74:1
```
This might be related to meteor. I'm not sure how I can get its version but here what npm tells me:
```
rocketchat@server:~/rocketchat-6.4.0/programs/server$ npm list | grep meteor
meteor-dev-bundle@ /var/www/rocketchat/rocketchat-6.4.0/programs/server
├─┬ @meteorjs/reify@0.24.0
├── meteor-promise@0.9.0
```

**Comment by CvH** [comment]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/2766
https://github.com/RocketChat/Rocket.Chat.Electron/issues/2758
:) issue handling as usual at RC

**Comment by spl0k** [comment]
I actually tried to deploy 6.4 in production and now it works, so it's certainly related to the site URL not matching the one used to access the instance.
In prior versions it would just work and display a "would you like to fix the site URL?" popup to admins after login, now we can't even reach this popup.

Even if it's somehow fixed for me, I'll leave the issue open as this should be considered a regression and should be fixed.

**Comment by recklessnl** [comment]
Similar to https://github.com/RocketChat/Rocket.Chat/issues/30931

**Comment by rrmt23** [comment]
@tassoevan help

**Comment by CvH** [comment]
#31029

In the meanwhile I am really wondering if there is at all a RocketChat Team that fixes bugs or monitors the github issues.
The amount of heavy bugs (at basic functionality) that introduced at every update is worrisome. In the last year not a single version without major problems that are not fixed without updating to a new major version that introduced different major bugs.

**Comment by urosino** [comment]
> #31029
> 
> In the meanwhile I am really wondering if there is at all a RocketChat Team that fixes bugs or monitors the github issues. The amount of heavy bugs (at basic functionality) that introduced at every update is worrisome. In the last year not a single version without major problems that are not fixed without updating to a new major version that introduced different major bugs.

I agree. 

- sign-outs
- reloads
- ...

**Comment by da-avidid** [comment]
Hello, just want to add the following issue here #30717 . It seems to be related and maybe you can fold it all into one thread.
