### ISSUE TITLE
Amazon S3 file upload doesn't work with AWS Signature v4

### ISSUE THREAD

**Issue by sander3** [RocketChat/Rocket.Chat#3099]
Your Rocket.Chat version: latest.

AWS regions deployed after 2014 require AWS Signature V4. Rocket.Chat doesn't handle uploads well when you are using AWS region eu-central-1 (deployed last year).

**Comment by hadifarnoud** [comment]
any update on this issue? it uploads just fine but can't access the files

**Comment by engelgabriel** [comment]
Update https://github.com/RocketChat/Rocket.Chat.Docs/pull/144 when fixed.

**Comment by fspc** [comment]
The documentation should reflect the fact that any region that only supports version 4 as shown at http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region will exhibit the same issue as the S3 Frankfurt Region.

**Comment by pandada8** [comment]
I have an available patch which test passed on `cn-north-1` region, where only  version 4 is supported.
If anyone have interests, I can open a PR for it.

**Comment by sander3** [comment]
Please do! 👍
