### ISSUE TITLE
Unable to install apps: failed to aggregate seen app requests due to a database error

### ISSUE THREAD

**Issue by TLINDEN** [RocketChat/Rocket.Chat#31001]
### Description:

I have the community edition installed on k8s without any apps so far. When I try to install an app, a popup appears:

```
0 of 5 apps currently enabled.

Workspaces on Community Edition can have up to 5 apps enabled. Upgrade to Enterprise to enable unlimited apps.
```
When I click on the `next` button, nothing happens.

### Steps to reproduce:

1. Go to marketplace
2. search fo an app (poll in my case)
3. click `install`
4. click `next`

### Expected behavior:

The app just should be installed.

### Actual behavior:

In the log I can see this:
```
rocketchat-fitsintegration-{"level":50,"time":"2023-11-17T10:23:54.998Z","pid":1,
 "hostname":"rocketchat-767b78b4f7-d4zd8",
 "name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
Error: ENOENT: no such file or directory, open '/tmp/userDataX3NYdi/64de13a9887c5fd246438b8e/user.html'
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at server/lib/dataExport/processDataDownloads.ts:160:4
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/userDataX3NYdi/64de13a9887c5fd246438b8e/user.html'
}
```

The `/tmp` directory doesn't contain such stuff:

```
I have no name!@rocketchat-767b78b4f7-d4zd8:/app/bundle$ ls -l /tmp/
total 8
drwxr-sr-x 2 999 999 4096 Nov 17 10:23 rocketchat-importer
drwx--S--- 2 999 999 4096 Nov 17 10:23 ufs
```

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: chrome latest
- Operating System: Kubuntu 23.10

### Additional context

We use Rocketchat version 6.3.0

**Comment by hugocostadev** [comment]
Do you still have this issue? I could not reproduce here

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by TLINDEN** [comment]
The problem persists.

**Comment by TLINDEN** [comment]
Could please someone look after this issue? I also like to add, that it seems like Rocketchat wants to upload data to some undisclosed destination as reported in another issue already.

Thanks,Tom

**Comment by TLINDEN** [comment]
Seems like Rocketchat is about to go to the dark side. It's a pity ...

**Comment by hugocostadev** [comment]
Hey @TLINDEN I'm sorry to take long to reply.

I tested with our latest release and I could not reproduce the error, could you try to update, please? 

> Could please someone look after this issue? I also like to add, that it seems like Rocketchat wants to upload data to some undisclosed destination as reported in another issue already.
> 
> Thanks,Tom

I would like to iterate that we do not do such thing, we do collect very basic stats if you are registered to our cloud platform, that you need to have access to the marketplace. But all of this is described in our terms.

**Comment by TLINDEN** [comment]
Hi, thanks for your kind response. Ok, so I'll retry the update. While we're at it: what about the licensing and user limitation issues? We have >500k users, do we still have to cancel the subscription after registration two times?


best,
Tom
