### ISSUE TITLE
How to enable the preview of image URLs?

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#3101]
Hi :)

for some reasons I've issues with previewing image URLs that have been pasted into a chat room. The current behavior is that only the plain link gets displayed but no image/preview gets shown for that link. For example I've installed the `hubot-victory` package which posts a simple URL into a chat room e.g. http://www.quickmeme.com/img/ea/ea4671998341d9fbb6f7815394b49cb2890a50ac80b62802fb021c147c068d8e.jpg
It'd be great if that URL gets rendered inline in the chat room. Any guess what goes wrong in my case or do you know which settings I've to modify? If you need more information I'd happily provide them.

The only issue I found so far which sounds similar to my issue is https://github.com/RocketChat/Rocket.Chat/issues/1362 but expect the comment that it should work I didn't really help me.

Thanks a lot!

Btw. pasting images from the clipboard shows properly a preview of that image. 

Your Rocket.Chat version: 0.28.0 (fresh installation)

**Comment by marceloschmidt** [comment]
Hello @subesokun! Is that happening with all images posted by hubot, or all images from all links? What happens if you manually post that link? Does it get an image preview?

**Comment by subesokun** [comment]
Hi @marceloschmidt, it happens to all images from all links. So for the images posted by hubot as well as for the manually posted image links only the link is getting displayed without any preview.

**Comment by subesokun** [comment]
Uh, maybe I know now a potential reason why it's not working for me. Is the rendering of the preview image is happening on the server or client side? Our Rocket.Chat instance is running in a private network with no internet access so obviously it would fail rendering a preview on the server side. Could you give me a pointer to the source code where the magic of generating the preview image takes place?

**Comment by marceloschmidt** [comment]
The method that does that is this one: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages%2Frocketchat-oembed%2Fserver%2Fserver.coffee#L20

**Comment by subesokun** [comment]
Ok the issue was really that our Rocket.Chat Docker Container had no internet access and hence couldn't create a previews. I'm wondering if it would make sense to show some notification/warning on the admin page in case there is no internet connection to highlight some features that won't work without internet.
