### ISSUE TITLE
RocketChat doesn't work on Safari browser MacOS

### ISSUE THREAD

**Issue by oleh-v** [RocketChat/Rocket.Chat#31018]
### Description:

RocketCat doesn't open on MacOS+Safari.  It runs "the loader" ever. 
Browser console has errors, and "verifyErrors.js" runs like in the loop...
(see screenshots)

<img width="240" alt="safari-0" src="https://github.com/RocketChat/Rocket.Chat/assets/42116260/e74d8212-6a17-4f17-85da-3758b06ed2fd">
<img width="1488" alt="safari-1" src="https://github.com/RocketChat/Rocket.Chat/assets/42116260/f110de4d-273a-4944-944d-2ff72e1d49a0">
<img width="1167" alt="safari-2" src="https://github.com/RocketChat/Rocket.Chat/assets/42116260/37d5e0e0-5c30-4a4c-8f91-65bac646c2e0">
<img width="882" alt="safari-3" src="https://github.com/RocketChat/Rocket.Chat/assets/42116260/ff7a0b97-6f00-4044-8733-442f101c66cf">

### Steps to reproduce:

1. Just open in MacOS Safari-browser and try to open RocketChat

### Expected behavior:

RocketChat works on MacOS in Safari browser

### Actual behavior:

RocketCat doesn't open on MacOS+Safari.  It runs "the loader" ever. 
(screenshot in description)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.5
- Operating System:  Centos 7.4
- Deployment Method: DOCKER
- Number of Running Instances: 1
- DB Replicaset Oplog: 128MB
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.22

### Client Setup Information

- Desktop App or Browser Version: Safari 16.0 (17614.1.25.9.10, 17614)
- Operating System: MacOS 12.6 (21G115)

### Relevant logs:

in browser console:

```
[Error] Unhandled Promise Rejection: SyntaxError: Duplicate parameter 'e' not allowed in function with destructuring parameters.
	promiseEmptyOnRejected (d4e87a31a15d379ef7fede162927a08e9efa34b8.js:22:120513)
	promiseReactionJob
```
```
Unhandled Promise Rejection: SyntaxError: Duplicate parameter 'e' not allowed in function with destructuring parameters.
```

**Comment by manish2022-creator** [comment]
I would like to work on it -.

**Comment by hugocostadev** [comment]
are you still facing this issue?  I could run RC in 6.5 in safari....

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by pranavkonidena** [comment]
<img width="1512" alt="Screenshot 2023-12-04 at 2 52 57 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/122373207/4c70a5a9-d85e-4ed0-bc10-b1421d72801c">
It is working for me.. Could you please specify which part is not working exactly..

**Comment by andreaswolf** [comment]
We're getting similar reports from our users since upgrading to 6.4.6, but we're still investigating the root cause.

**Comment by andreaswolf** [comment]
We just tested on several machines and it seems it's broken in Safari up to 16.2 and working in 16.5 (that's versions we explicitly tested, I have no idea myself if there were any versions in between).

The behaviour was reproducible on different instances of RocketChat.

**Comment by datamaker** [comment]
I'm having the same problem.

**Comment by hugocostadev** [comment]
Hi guys, what about trying to run in the Safari 17?  I didn't face this issue here

**Comment by mddvul22** [comment]
We can confirm that this problem still exists.

**Comment by RaymondMouthaan** [comment]
Just installed RocketChat on k8s and can confirm that the loader is endless in Safari 17 as well as the RocketChat Mac store app.

+----------------------------------------------+
|                SERVER RUNNING                |
+----------------------------------------------+
|                                              |
|  Rocket.Chat Version: 6.4.4                  |
|       NodeJS Version: 14.21.3 - x64          |
|      MongoDB Version: 6.0.10                 |
|       MongoDB Engine: wiredTiger             |
|             Platform: linux                  |
|         Process Port: 3000                   |
|             Site URL: http://localhost:3000  |
|     ReplicaSet OpLog: Enabled                |
|          Commit Hash: d994a6ff33             |
|        Commit Branch: HEAD                   |
|                                              |
+----------------------------------------------+

**Comment by robinreckmann** [comment]
Same here, tested on Rocket.Chat versions 6.5.0 and 6.5.3 for iOS 16.2 and below and on an older MacBook running MacOS Big Sur. 

The root cause of this issue was fixed in WebKit a while ago in November 2022, but people using "older" hardware who are not willing to invest into a new phone will be unable to use Rocket.Chat on the web.

WebKit references:
https://bugs.webkit.org/show_bug.cgi?id=220517
https://github.com/WebKit/WebKit/commit/a44c26d2439a38be3ea8572d80d006ff218bf528

**Comment by andreaswolf** [comment]
This is not stale, the error is not fixed AFAICS.

**Comment by robinreckmann** [comment]
The following seems to fix the issue (tested with Rocket.Chat 6.5.3 base on iPad OS 14.7.1):

Change the file "MultiSelectCustomListWrapper.tsx" in packages/ui-client/src/components/MultiSelectCustom as follows:

Before:
```
import { Box } from '@rocket.chat/fuselage';
import { forwardRef, type ComponentProps } from 'react';

const MultiSelectCustomListWrapper = forwardRef<Element, ComponentProps<typeof Box>>(function MultiSelectCustomListWrapper(
        { children },
        ref,
) {
        return (
                <Box ref={ref} zIndex='2' w='full' position='absolute' mbs={40} pbs={4}>
                        {children}
                </Box>
        );
});

export default MultiSelectCustomListWrapper;
```


After:
```
import { Box } from '@rocket.chat/fuselage';
import { forwardRef, type ComponentProps } from 'react';

const MultiSelectCustomListWrapper = forwardRef<Element, ComponentProps<typeof Box>>(function MultiSelectCustomListWrapper(
        props,
        ref,
) {
        const { children } = props;
        return (
                <Box ref={ref} zIndex='2' w='full' position='absolute' mbs={40} pbs={4}>
                        {children}
                </Box>
        );
});

export default MultiSelectCustomListWrapper;
```

Then build meteor with the `--platforms web.browser` flag (like `meteor build --server-only --platforms web.browser  --directory /tmp/rc-build`) to build Rocket.Chat without the legacy browsers packages. After that, clear the Safari cache for your website running Rocket.Chat (really important if you tried accessing your Rocket.Chat instance before on the same device as a GUI crashed screen will likely be shown without clearing the cache).

A full build routine for a docker image includes the following steps for me (using Ubuntu with WSL2 on Windows with Node.js, meteor and yard installed as stated [here](https://developer.rocket.chat/open-source-projects/server/server-environment-setup/windows-10)):
1) git clone the official Rocket.Chat repository and change the file mentioned above accordingly, then cd to the Rocket.Chat directory
2) `yarn`
3) `yarn dsv`
4) `export METEOR_ALLOW_SUPERUSER=true`
5) `cd ~/Rocket.Chat/apps/meteor`
6) `METEOR_DISABLE_OPTIMISTIC_CACHING=1 meteor build --server-only --platforms web.browser --directory /tmp/rc-build`
7) `cp .docker/Dockerfile /tmp/rc-build`
8) `cd /tmp/rc-build`
9) `docker build -t <your image name> .`

**Comment by andreaswolf** [comment]
… still not stale.

**Comment by andreaswolf** [comment]
AFAICS this is not fixed yet, is it?

**Comment by andreaswolf** [comment]
… still not stale AFAICS

**Comment by andreaswolf** [comment]
I'm pretty sure this is not fixed yet.
