### ISSUE TITLE
Offline Liveagent not working on Firefox (6.4.7)

### ISSUE THREAD

**Issue by BigSnicker** [RocketChat/Rocket.Chat#31023]
### Description:

Clicking on offline liveagent icon, when embedded in another site, does not produce any form on Firefox.  It works correctly on all other browsers tested.

### Steps to reproduce:

Embed liveagent javascript in target website
Have no Omnichannel agents logged in and offline agents form enabled
Click on greyed out icon.

### Expected behavior:

Expect the "No agents online" form to come up on Firefox.

![image](https://github.com/RocketChat/Rocket.Chat/assets/18507363/1ba9afee-a738-4cf6-8d8e-c0f26ff7af3d)

### Actual behavior:

Nothing happens.  Note that the "online agent" form works correctly, with "Liveagent Connected" being shown.

![image](https://github.com/RocketChat/Rocket.Chat/assets/18507363/7a6f987b-b77d-43b2-ac7b-a94c4f0d4f05)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.7
- Operating System: Windows 10
- Deployment Method: Docker
- Number of Running Instances: 1

**Comment by MartinSchoeler** [comment]
Hello @BigSnicker do you get any errors on the browser console? Thanks!

**Comment by BigSnicker** [comment]
Yes!  Strangely makes it look like a network issue, but other browsers work fine:

Structured Ingestion ping failure with error: error [PingCentre.sys.mjs:148:17](resource:///modules/PingCentre.sys.mjs)
    sendStructuredIngestionPing resource:///modules/PingCentre.sys.mjs:148
TypeError: linkMap is undefined
    Links_onLinkChanged resource://gre/modules/NewTabUtils.sys.mjs:2001
    PlacesProvider__callObservers resource://gre/modules/NewTabUtils.sys.mjs:695
    handlePlacesEvents resource://gre/modules/NewTabUtils.sys.mjs:677
[NewTabUtils.sys.mjs:697:19](resource://gre/modules/NewTabUtils.sys.mjs)
Structured Ingestion ping failure with error: error 10 [PingCentre.sys.mjs:148:17](resource:///modules/PingCentre.sys.mjs)
    sendStructuredIngestionPing resource:///modules/PingCentre.sys.mjs:148
<empty string> 2
Structured Ingestion ping failure with error: error 11 [PingCentre.sys.mjs:148:17](resource:///modules/PingCentre.sys.mjs)
    sendStructuredIngestionPing resource:///modules/PingCentre.sys.mjs:148

**Comment by BigSnicker** [comment]
Looks like this is working in 6.5.0?
