### ISSUE TITLE
Displaying component.<label> in Home page

### ISSUE THREAD

**Issue by AnudeepReddyBondugula** [RocketChat/Rocket.Chat#31062]
### Steps to reproduce:

1. Go to 'https://open.rocket.chat/home'

### Expected behavior:

It should display the labels (like emailOrUsername, password)

### Actual behavior:
Displaying component.form.emailOrUsername, component.form.password ...

![image](https://github.com/RocketChat/Rocket.Chat/assets/110739683/8ab5d2a1-3e01-4768-873b-7d726409d150)

### Client Setup Information

- Desktop App or Browser Version: Brave 1.60.x
- Operating System: Windows

**Comment by chiragmalik2612** [comment]
i'll fix it , please assign this issue to me.

**Comment by rosefinchh** [comment]
I think the issue has been resolved.

**Comment by AnudeepReddyBondugula** [comment]
Yes the issue has been resolved. I don't know why I faced this issue may be due to network issue
