### ISSUE TITLE
Incorrect placeholder text in search box in windows devices

### ISSUE THREAD

**Issue by mayank6725** [RocketChat/Rocket.Chat#31076]
### Steps to reproduce:
1. Go to open.rocket.chat on a web browser running on windows
2. Click on the search icon next to home icon
3. You can see the placeholder text as Search (^+K)
![image](https://github.com/RocketChat/Rocket.Chat/assets/69050987/eaf593ce-9e4a-424e-a09f-7ed586416efc)

### Proposed solution:
The search box placeholder text says ' Search (^+K) ' for windows devices. The caret (^) key is used on Mac devices to define Ctrl key and not on windows laptops. Windows laptop only has a Ctrl key with no caret(^). We should change the placeholder text to Search (Ctrl+K) for windows devices.

### Supporting proof
https://i0.wp.com/bigtechquestion.com/wp-content/uploads/2021/07/control.jpg?resize=600%2C600&ssl=1

### Client Setup Information
Desktop App or Browser Version: Google Chrome version 119.0.6045.160 (Official Build) (64-bit)
Operating System: Windows 10

### PR for this issue #31074

**Comment by Soham508** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by MartinSchoeler** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/31074
