### ISSUE TITLE
Can hubot put javascript .. inside rocket chat message window ?

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#3107]
Your Rocket.Chat version: .28

For my company .. I have written a bot which is used to add tasks and set priority

The users want the task list to have a icon which can be clicked to change the priority

![screen shot 2016-05-01 at 7 04 58 pm](https://cloud.githubusercontent.com/assets/6703876/14967963/026be54a-106f-11e6-96a6-1b31f4d1d04f.png)

In the above message how do I make the red icon a clickable icon .. on click I want to open a dropdown ..

Can hubot put javascript .. inside rocket chat message window ?

**Comment by disenchant** [comment]
From a security perspective I would highly recommend that if implementing this feature request is considered, that it comes with a global setting to disable any code execution.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
