### ISSUE TITLE
Incorrect indentation of the last message in the chat list

### ISSUE THREAD

**Issue by sanyappc** [RocketChat/Rocket.Chat#31083]
### Description:

incorrect indentation of the last message in the chat list

![image](https://github.com/RocketChat/Rocket.Chat/assets/13138763/b85c5ce8-0c35-4725-9af8-8affe87e3f07)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.8
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.9 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: chrome 119.0.6045.160
- Operating System: windows 11

**Comment by brf153** [comment]
@sanyappc I am working on this issue. Will send a pr soon.

**Comment by brf153** [comment]
@sanyappc I am not facing this issue in my system...ubuntu 22.04 with desktop app version 3.9.9

**Comment by sanyappc** [comment]
the problem seems to be fixed in 6.5.0

**Comment by sanyappc** [comment]
it looks like this problem has been fixed in 6.5.0
