### ISSUE TITLE
False error: Workspace Version Unsupported

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#31093]
### Description:

Non-Admin users are being presented with a supposedly false warning error message that our workspace version is unsupported.  "This workspace is running an unsupported version of Rocket.Chat.  Your workspace admin needs to update to at least v6.4.5 to prevent cutoff."  It reports that we will be "cutoff" in 27 days.  This is incorrect, annoying, and obnoxious.  First, non-admins shouldn't ever see messages like this.  Second, it is incorrect.  We are running version 6.3.12 which is supported at least into January 2024!  Even if support for this version ends on January 1st, 2024, that is 34 days away.  

https://docs.rocket.chat/resources/rocket.chats-support-structure/enterprise-support-and-version-durability

### Steps to reproduce:

1. Open app
2. See pop up.

### Expected behavior:

1. No such warning should ever be delivered to non-admins.
2. No such warning should ever be delivered to admins on workspaces that are supported.

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/6833993/ffd54d25-651f-405e-b1fa-1baaea3af51a)

![image](https://github.com/RocketChat/Rocket.Chat/assets/6833993/74293c2b-1246-463e-9d85-9201d2953cfc)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.12
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.20

### Client Setup Information

Is happening to multiple people with different versions.

**Comment by mboudet** [comment]
Same issue here. Not only the required version (6.4.5) is not yet available as a docker image (which we are using for deployment), but the 6.4.X versions seems to be plagued with some blocking issues, so I'd rather not migrate yet.

Given that 6.3.12 was released 2 weeks ago, it seems to be a bit early for a total deprecation.

**Comment by diegolmello** [comment]
@mddvul22 @mboudet Can you check if it's still happening?

**Comment by diegolmello** [comment]
Let's wait a bit for @mddvul22 confirmation before closing.
Thanks for the feedback, @mboudet! 🤗

**Comment by hugocostadev** [comment]
We are sorry about that, this is supposed to be fixed by now 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by mddvul22** [comment]
Sorry for the delay, everybody.  I'm being told that the popups have stopped.  Thanks!  I'll close and reopen if they return.

**Comment by fcmildef** [comment]
We seem to have the same issue in the last weeks:

![Image](https://github.com/user-attachments/assets/e6151bbf-c34c-49b3-ad10-b3ef060342fa)

we are running workspace version 7.7.0

Also agree with original issue,  even if it where correct, this message should never be send to the users.

**Comment by M1cr0nic** [comment]
Just last week, we had the same pop-up showing to end users.  Pop-up states to upgrade to v7.7.0 when my workspace is already v8.4.0

<img width="604" height="269" alt="Image" src="https://github.com/user-attachments/assets/bb2d875e-1a26-4178-a97c-a61fb148fb75" />

Server Setup Information:
Version of Rocket.Chat Server: 8.4.0
Operating System: Ubuntu
Deployment Method: Docker-Compose
Number of Running Instances: 1
DB Replicaset Oplog: (I don't know how to check)
NodeJS Version: 22.16.0
MongoDB Version: 8.0.21 / wiredTiger

**Comment by bruno-sales-gmx** [comment]
Same problem here,

<img width="953" height="426" alt="Image" src="https://github.com/user-attachments/assets/5e8816a7-4d90-4c67-aa88-33f885feef87" />
Server Setup Information:
Version of Rocket.Chat Server: 8.3.2
Operating System: Ubuntu
Deployment Method: Official Snap
Number of Running Instances: 1
DB Replicaset Oplog: (I don't know how to check)
NodeJS Version: 22.16.0
MongoDB Version: 8.0.21 / wiredTiger
