### ISSUE TITLE
RC 6.4.8 after upgrade Ctrl + P doesnt  work correctly

### ISSUE THREAD

**Issue by duven87** [RocketChat/Rocket.Chat#31112]
### Description:

Yesterday I had to update our RC 3.15 which was running smoothly and correctly to the latest version 6.4.8 because of the apk and desktop app blocking warnings.

Since then, RC is a bit nicer but slower, reloading oft , code ``` now you most put it in another new line, ...
But the worst its when searching for channels or users with Ctrl+P works "sometimes".

When searching and starting with letters for example, I get several results and before automatically the first of the list when I hit enter entered that channel or user.
Now it does anything. Sometimes it does it correctly and many times it enters a channel or user that has nothing to do with the search.

### Steps to reproduce:

Ctrl+P example + ENTER

### Expected behavior:

Go to the first of the list while Im writing

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/24485101/e4abef4b-ba7a-49cc-8a93-a2f068b558ea)
ENTER
![image](https://github.com/RocketChat/Rocket.Chat/assets/24485101/ff35a0ab-099d-45f8-ab0a-04ee583f67fa)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.8
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.23

### Client Setup Information

- Desktop App or Browser Version: Chromium Version 119.0.6045.159, app 3.9.10
- Operating System: Mint 21.2 / Ubuntu 22

**Comment by hugocostadev** [comment]
I tested here and could reproduce the issue.

Sometimes when searching the focus stays on the first item of the list of users, some other times it does not, and when pressing enter without a user being focused refreshes the page

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Sumitwarrior7** [comment]
Hello, @hugocostadev, sir

I'm experiencing a similar issue. I'd like to address it and contribute to the solution. 
Could you tell me  the relevant part of code related to this functionality?

Thank you.

**Comment by hugocostadev** [comment]
Hey @Sumitwarrior7 the component is https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/client/sidebar/search/SearchList.tsx

Best of luck!

**Comment by ChaudharyRaman** [comment]
@hugocostadev, I think this issue can be closed.

**Comment by duven87** [comment]
is it merged  or ready to merge?

**Comment by duven87** [comment]
After upgrade to 6.6.5, it works correctly..
