### ISSUE TITLE
Restart server on error?

### ISSUE THREAD

**Issue by du5t** [RocketChat/Rocket.Chat#3111]
Your Rocket.Chat version: 0.29.0

```
{"line":"419","file":"webapp_server.js","message":"Error serving static file Error: ENOENT, stat
 '/home/user/Rocket.Chat/programs/web.browser/app/images/logo/favicon-128x128.png'","time":{"$date":1462254706330},"level":"error"}
```

occasionally the server running this spits lots of these kinds of errors; basically static file serving issues. a restart of the server process cures these, but i would like to make it automatic.

how do i hook to the error event and restart the server in this case?

**Comment by geekgonecrazy** [comment]
This error shouldn't be happening.  Please use pm2 or a system service to run rocket.chat they have things like auto restart built in.
