### ISSUE TITLE
unable to access some public channels

### ISSUE THREAD

**Issue by sensit77** [RocketChat/Rocket.Chat#31111]
### Description:
Unable to access some public channels even for admin from web browsers (desktop,mobile) and desktop app. no problem on mobile application 4.43. Client language default or english - the same results.
Users only get message: "Oops! Something went wrong. Please reload the page or contact an administrator."

### Actual behavior:
<img width="491" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/22908016/048aa924-f5c7-4334-87ba-b106c561e1b3">

### Expected behavior:
Access all channel without error.

### Server Setup Information:
Version
6.4.8
Apps Engine Version
1.41.0-alpha.312
Node Version
v14.21.3
Database Migration
303 (November 28, 2023 6:47 AM)
MongoDB
5.0.22 / wiredTiger (oplog Enabled)

### Browser console example errors
TypeError: l is undefined
    fields DefaultAttachment.tsx:1
    module DefaultAttachment.tsx:1
    React 13
    q use-sync-external-store-shim.production.min.js:18
    c createReactiveSubscriptionFactory.ts:1
    c createReactiveSubscriptionFactory.ts:1
    c createReactiveSubscriptionFactory.ts:1
    _compute tracker.js:302
    withComputation tracker.js:609
    _compute tracker.js:301
    _recompute tracker.js:318
    _runFlush tracker.js:489
    s setimmediate.js:102
    _setImmediate setimmediate.js:111
    <anonymous> setimmediate.js:126
    <anonymous> setimmediate.js:134
    <anonymous> url_common.js:80
[/node_modules/react-dom/cjs/react-dom.production.min.js:224:200](chrome://devtools/node_modules/react-dom/cjs/react-dom.production.min.js)

​

**Comment by hugocostadev** [comment]
Weird... is this still happening? 
Can you send a print of the console.error? Did you change something on the code or it's running the release code without any change? 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by sensit77** [comment]
Update:
After to upgrade to the latest v6.5.0, above error messages gone, but new  error appears in the browser console:
react-dom.production.min.js:224 TypeError: Cannot read properties of undefined (reading 'replace')
     at eval (DefaultAttachment.tsx:90:75)
     at Array.map (<anonymous>)
     at eval (DefaultAttachment.tsx:81:35)
     at Ch (react-dom.production.min.js:165:137)
     at ck (react-dom.production.min.js:275:460)
     at bk (react-dom.production.min.js:258:347)
     at ak (react-dom.production.min.js:258:278)
     at Tj (react-dom.production.min.js:258:138)
     at Lj (react-dom.production.min.js:251:163)
     at eval (react-dom.production.min.js:131:115)

the result is the same, moreover, there are channels where the latest messages appear and the error occurs only when going back to older messages by scrolling back or searching.
