### ISSUE TITLE
remove token from push notificationa

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#3112]
Rocketchat: 0.28

I've configured push notification (gcm) and everything works nicely so far. Thanks for that. My question is, how do i remove a token when i don't want to deliver any notifications to a specific device anymore?

thanks and cheers
t.

**Comment by marceloschmidt** [comment]
If you logout of the connected app, that token will cease to exist. Also, if you go to your profile then logout of other sessions, those sessions will also lose their tokens.

**Comment by himbeere** [comment]
Ah, i see. Works as expected. Thanks.
