### ISSUE TITLE
Suprising user limit in 6.5.0

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [RocketChat/Rocket.Chat#31149]
### Description:
I've upgraded to 6.5.0 and was greeted by "registration needed". I did that... a now a pro plan trial was activated. 
I do not want any trial. So I disabled it.
Now all of a sudden there is a user limit of 25! With the option to pay thousands of dollars per year to keep using rocketchat.

Nothing of the above was mentioned in the changelog.

### Steps to reproduce:

1. Have a running rocketchat version < 6.5.0
2. Update to 6.5.0

### Expected behavior:

I expected either to continue using the free plan or be informed that the free plan is going away and Im supposed to pay thousands of dollars per year to continue using RocketChat.

### Actual behavior:

See Description above.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.8 => 6.5.0
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  active
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version: 3.9.10
- Operating System: Mac OS Sonoma

**Comment by himpierre** [comment]
You can switch back to the Community Version by "cancel subscription" on the subscription page.

**Comment by MatthiasKuehneEllerhold** [comment]
As stated in the description: there is user limit of 25 then.

**Comment by MatthiasKuehneEllerhold** [comment]
According to every link provided in the admin page and on rocket.chat there is no more community version.
See https://www.rocket.chat/pricing

**Comment by etaormm** [comment]
> According to every link provided in the admin page and on rocket.chat there is no more community version. See https://www.rocket.chat/pricing

That is true, but there is also this post where they state that you can still use Community - you just have to cancel your Starter subscription.

https://www.rocket.chat/blog/new-starter-pro-plans

**Comment by rodrigok** [comment]
@MatthiasKuehneEllerhold thanks for your question. On 6.5 we've introduced a free plan, which contains many of our paid features with a limit of 25 users to help small teams to grow. The new free plan is applied automatically for everyone to test it, for installations with more than 25 users a trial of the pro plan is applied for the test.

You have the option to cancel the trial at the bottom of the subscription page, it will re-apply the free license. If you have the free license you can cancel it in the same place to move back to the community without user limits.

We will keep improving our communication to make those options clear to everyone.

Thanks @himpierre and @etaormm for the explanations 😄

**Comment by kertiskz** [comment]
I don't understand where I can change this tariff plan that I didn't ask for?

**Comment by krumelmonster** [comment]
It is configured in Administration/Workspace/Subscription, however we where still unable to create new users after switching to community (`Seat limit reached`) until after restarting the server and pressing `Sync license update` (found on the upper right of the Administration/Workspace/Subscription page). It seems that RocketChat will slowly move to make the Community version unusable, the way 6.5.0 has been done sends a clear message.

That such a breaking change is not even documented in the changelog smells of malice, especially considering how this is being communicated. I received this email right **after** upgrading to 6.5.0:

> *Your Rocket.Chat workspace named [...] configured 
> to be accessed at [...] is now on the Rocket.Chat Starter 
> plan. *
> 
> The Starter plan is an excellent starting point for smaller teams to collaborate 
> securely and effectively.
> 
> Your team now has access to nearly all security, team collaboration and 
> omnichannel features for up to 25 users and 100 monthly active contacts (MAC).
> 
> If your team outgrows the Starter plan limits you can upgrade to a paid plan [tracking URL]

 :chart_with_downwards_trend:

**Comment by keros** [comment]
This was a funny start into the day.
snap auto updated to 6.5.0 in the night
`snap revert` works but the old `6.4.8` version does not run with the already migrated datastore. So revert is broken **nice**.

As MatthiasKuehneEllerhold already mentioned no consent was given to upgrade from community edition to trial (or anything else). But 6.5.0 simply does it **nice**.
A admin needs to register a workspace with his e-mail for `license updates, notifications of critical vulnerabilities and access to Rocket.Chat Cloud services` reasons. For comunity edition this makes no sense **nice**.
This is also not skippable #31163 **nice**.
At the time of this writing the `[Terms and Conditions](https://rocket.chat/terms)` on the `Register your workspace` site bring you to a `Page not found` site **nice and trustworthy**.
We now reverted to a backup and stopped snap from auto updateing until there is a fixed version. Which means wir are maybe at risk with an old 6.4.8 version **nice**.

Don't get me wrong. Thank you for all the work you put into rocketchat. Thank you for the free community edition. We really like this product.
But this update to 6.5.0 was at least a bad and untrustworthy move.
Please consider the feedback and fix this in the next realeases.

**Comment by TheDom42** [comment]
> This was a funny start into the day. snap auto updated to 6.5.0 in the night `snap revert` works but the old `6.4.8` version does not run with the already migrated datastore. So revert is broken **nice**.

Thank you. Exactly my experience today! Without this thread, I wouldn't even be aware, that the CE still exists. Even AFTER searching specifically for it, I wasn't able to find it. The blog post from last week is NOT easily findable.

> Don't get me wrong. Thank you for all the work you put into rocketchat. Thank you for the free community edition. We really like this product. But this update to 6.5.0 was at least a bad and untrustworthy move. Please consider the feedback and fix this in the next releases.

To even further extend this point - we are using Rocket Chat since mid-2020 and we had several occasions, where features would just be taken away by a snap auto-update without early notification. After registering the server last year (to regain mobile notifications), the sales team sent 10(!) emails (in a weekly manner) to get us to sign up for the paid version. To me, even now, it is unclear, what the features of the CE are in comparison to the starter plan. To me, this is just a weird and sketchy business practice.
As @keros said - thank you for designing and releasing RC. But please, please make sure that people are notified about such very significant changes.

**Comment by TheDom42** [comment]
> Does the online downgrade requirement trigger for these instances?

I'm not entirely sure if the offline registration is something else, but we had our workspace registered before the 6.5.0 upgrade (see above; to use the cloud push gateway). We also needed to "Cancel Subscription" in the workspace to get back to CE.

**Comment by Gummikavalier** [comment]
> > Does the online downgrade requirement trigger for these instances?
> 
> I'm not entirely sure if the offline registration is something else, but we had our workspace registered before the 6.5.0 upgrade (see above; to use the cloud push gateway). We also needed to "Cancel Subscription" in the workspace to get back to CE.

So it *might* work depending whether the cancel subsciption button wants to connect to cloud.rocket.chat or if it is local only.

For previously unregistered ones the issue mentioned here would stump the completely unregistered air gapped systems, at least:
https://github.com/RocketChat/Rocket.Chat/issues/31163

**Comment by Gummikavalier** [comment]
I did an upgrade of our offline registered CE edition instance. (There is an option for offline registration in the cloud.rocket.chat and it worked at least with version RC 6.4.8.)

After the upgrade to RC 6.5.0 the Starter Edition 25 user limit and subscription cancellation requirement did not trigger for this one. It started, and remained, as Community Edition.

**Comment by filefi** [comment]
is there any way to downgrade to v6.4.8?

**Comment by engelgabriel** [comment]
Dear Rocket.Chat Community, I've been following the discussions here regarding our recent 6.5 release and the concerns about the automatic enrollment into a trial of our enterprise version. I want to openly address these concerns and provide clarity on our intentions and actions moving forward.

Firstly, I apologize for the lack of clear communication regarding this change and any inconvenience or concerns it may have caused. Our goal was to allow our users to experience the additional features available in the enterprise version, but we realize that the way we implemented this was not in line with our community's expectations, especially regarding transparency and consent.

Regarding privacy concerns, please be assured that protecting your data and respecting your privacy are paramount to us. The automatic enrollment into the trial version did not change the way we handle your data. We adhere strictly to privacy laws and guidelines, and your data remains secure and private.

We have taken your feedback seriously and are taking the following actions:

- **Improving Transparency:** We are committed to being more transparent in our communication, especially regarding significant changes in our releases. We will ensure that all changes, especially those affecting user experience and privacy, are clearly communicated in our release notes and other channels.

- **Revisiting Consent Mechanisms:** We are reviewing our processes to ensure that any changes requiring user consent are implemented in a way that is clear and straightforward, allowing our users to make informed decisions.

- **Development of a Reversion Tool:** We understand the need for greater control over software updates. As a result, we are developing a tool that will allow users to easily revert to previous versions if they are not satisfied with an update. This tool will provide more flexibility and ensure that you can maintain a setup that best suits your needs. Until our new reversion tool is developed, users who wish to revert to the previous version can do so by manually modifying the database version record and reinstalling the previous build. This process should be done with caution.

We value the trust you place in Rocket.Chat and are committed to maintaining that trust through transparency, responsiveness, and continuous improvement.

Thank you for your support and for bringing your concerns to our attention. We are dedicated to rectifying this situation and ensuring Rocket.Chat remains a reliable and user-centric platform.

**Comment by turboyz** [comment]
After one month since the last message from @engelgabriel, I've noticed there's no mention of the community version on the pricing page at https://www.rocket.chat/pricing. It's essential to highlight that Rocket.Chat originated from the community, and it appears the current focus is solely on companies and enterprises. Please consider acknowledging the community version, as it is the very reason Rocket.Chat exists.

This is truly frustrating. I dislike it when open-source projects are influenced by a profit-driven business mindset.

In case things take a turn for the worse, I'm exploring a Plan B and searching for a straightforward open-source chat project. A simply one with chat only.

I'm also annoyed by constantly receiving messages that force me to upgrade. If something is working well, why should I be compelled to upgrade it every 2-3 months?

**Comment by omegaeducacional** [comment]
> Depois de um mês desde a última mensagem do , notei que não há nenhuma menção à versão da comunidade na página de preços [em https://www.rocket.chat/pricing](https://www.rocket.chat/pricing). É essencial destacar que o Rocket.Chat se originou da comunidade, e parece que o foco atual é apenas em empresas e empreendimentos. Por favor, considere reconhecer a versão da comunidade, pois é a própria razão pela qual o Rocket.Chat existe.
> 
> Isso é realmente frustrante. Eu não gosto quando projetos de código aberto são influenciados por uma mentalidade de negócios orientada para o lucro.
> 
> Caso as coisas piorem, estou explorando um plano B e procurando um projeto de bate-papo de código aberto simples. Um simples com bate-papo apenas.
> 
> Também fico irritado por receber constantemente mensagens que me forçam a atualizar. Se algo está funcionando bem, por que devo ser obrigado a atualizá-lo a cada 2-3 meses?

mattermost work fine

**Comment by slhck** [comment]
I guess there still isn't any plan to become more transparent about the community version, given that it's not even listed in the plan overview, and that no real feature comparison exists. How am I supposed to know what features I am losing if I cancel my (Starter) subscription? After some digging I found [this PDF](https://8859759.fs1.hubspotusercontent-na1.net/hubfs/8859759/Rocket.Chat%20Community%20vs.%20Starter%20plan.pdf), but it would be good to show this on the plans page, and not in a [forum thread](https://forums.rocket.chat/t/introducing-the-starter-plan-free-access-to-premium-features-for-limited-scale-use/18736).

**Comment by fullheart** [comment]
The Blender Foundation organization is also leaving Rocket.Chat and moving to [Element](https://element.io/) (Matrix). See announcement from August 9th, 2024: https://devtalk.blender.org/t/blender-chat-migration/36155

**Comment by ThatOneCalculator** [comment]
Is it possible to switch back from community to starter? Cancelled, but didn't realize that would mess up push notifications :(

**Comment by xinnjie** [comment]
Please be noted, there is a hard config limit of 200 active sessions in community version.

**Comment by benedikt-wegmann** [comment]
@MatthiasKuehneEllerhold Have a look at the top of the following file in your Rocket.Chat application: `app/bundle/programs/server/npm/node_modules/@rocket.chat/presence/dist/Presence.js`.
