### ISSUE TITLE
Please make Sent & RR in visually different colors

### ISSUE THREAD

**Issue by momentics** [RocketChat/Rocket.Chat#31147]
Hey Gents!

although you enabled RR in the latest 6.5, it became worse than 4.x. Althrough it seems that in older versions it was also similar. It seems I patched your 4.x long time ago, but new version takes too much time to hack.

Well, please make it in visually different colors. Well, let it be: sent (gray) - to no color, because  it is unusefull, RR - is visible, say green or blue. Or different in geometry: sent (gray) - circle, RR - filled in circle...

Try to see it by youself. If you see it 50-80% of size you coluld see no visual difference. And btw, web version does not show RR at all.

thanks in advance, Alex

![image](https://github.com/RocketChat/Rocket.Chat/assets/6221848/a8f67bcf-6b0f-49e4-a552-3e4ce271a306)

![image](https://github.com/RocketChat/Rocket.Chat/assets/6221848/0a67f1e7-3b68-4f19-ae2c-4f0e3c007c42)

**Comment by caskelly** [comment]
@ivans-netto - Please provide comments in relation to our WCAG/BITV/ADA accessibility updates

**Comment by ShivendraTrivedi** [comment]
@momentics Hey, this issue is related to web or app or both can you explain little bit more as I am proficient in web development.  I am a beginner and I know how to solve this issue and wanted to get this issue assigned.

**Comment by momentics** [comment]
Naturally, this is a server-related problem. 
I accidentally posted it it the issues list of client's application . And this is not the right place to identify this problem. The point is that the client application displays the content sent by the server. And the server response contains the problem - poorly visible RR icons. 

It works as:
1) Gray RR - message delivered
2) Darkblue message readed by the client. 
as a sesult, it has poor visual difference at 80-100% of scale.

250% screenshoots scale show poor visual difference, but it shoud be good. so is proposed to improve server's code and as a result improve the overall chatting solution and its UX.

Hope somebody will post it to RC issues list.

**Comment by ivans-netto** [comment]
Hi @momentics Ivan here, Head of Design at Rocket.Chat.

Thank you for bringing up the color contrast issue, this is an accessibility-related topic. If you encounter any future accessibility issues, feel free to use the accessibility tag. It's a helpful practice that assists our team in quickly identifying and addressing these matters. 

Regarding the specific color contrast issue you highlighted, rest assured that we are actively working on a solution to enhance the readability of the read receipts feature. I'm considering additional measures to make it even more user-friendly for those who may struggle to differentiate between gray and blue.

Thanks again for your contribution.

**Comment by momentics** [comment]
Thank you @ivans-netto.
RC used to be very good. I hope it stays that way.
