### ISSUE TITLE
Not able to install Premium Marketplace apps on version 6.5.0 - Starter plan

### ISSUE THREAD

**Issue by etaormm** [RocketChat/Rocket.Chat#31148]
Hi,
according to this https://www.rocket.chat/pricing , Premium marketplace app should be available in Starter plan, but its not possible to add em unless I "start free 30-day premium trial".

Am I missing something?

![image](https://github.com/RocketChat/Rocket.Chat/assets/104149242/f12060dc-f486-44ea-bd51-c6d62124d1e2)

![image](https://github.com/RocketChat/Rocket.Chat/assets/104149242/559176b0-14cb-4498-ab2a-6b6795b3e596)

**Comment by rodrigok** [comment]
@etaormm thanks for your report. I'll scale this internally and will have news here soon.

**Comment by caskelly** [comment]
Per @rodrigok, an internal ticket has been opened to resolve this issue.  Thanks for reporting this

**Comment by caskelly** [comment]
@etaormm - This issue has been resolved.  Please confirm that you are able to install Premium apps and we will close this ticket on confirmation
