### ISSUE TITLE
More Rest API options

### ISSUE THREAD

**Issue by Ron537** [RocketChat/Rocket.Chat#3115]
Hello,
I think we should add more Rest API functions.
Currently we can only get public rooms, join public room, leave public room, get public room's messages and send a message to public room.

There are some functionalities that can make our life easier, for example:
1. Create private / public room (with option to add members already in the creation)
2. Join non-public rooms
3. Add option to modify room (public / private) - Edit name / descriptions / participants etc..

This functions are very important for our integrations, otherwise we won't be able to integrate to applications.

**Comment by marceloschmidt** [comment]
Definitely something we need to work on... feel free to open PRs, we'll gladly accept them :) Thanks!

**Comment by theblazehen** [comment]
You might also want to look at connecting with the meteor interface

**Comment by Ron537** [comment]
@theblazehen Can you explain a little further?

**Comment by theblazehen** [comment]
@Ron537 For example, the Rest API could act as a wrapper for meteor methods, so I would be able to call (for example) getRoomIdByNameOrId, or addUserToRoom from the rest API, without having to re-implement those features / methods in the api itself.

I'm not *too* familiar with the code, but I think if we possibly added say the bulk add to room rest api methods to a method that can be called with meteor, and then just have the wrapper it would reduce the amount of duplicated code.

**Comment by Deepakkothandan** [comment]
#3525 The PR extends the rest api with the functionailties, list all users, Delete a User and create a private group with optionally adding users to the private group
