### ISSUE TITLE
Environment=AUTO_ACCEPT_FINGERPRINT=true Not working

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#31162]
This Environment=AUTO_ACCEPT_FINGERPRINT=true not working.
Every time I restart rocketchat I have to confirm it manually 

Rocketchat version 6.5.0

**Comment by lovekyleman** [comment]
> @lovekyleman can you share here your config to start the service? 
> 
> 
> 
> `AUTO_ACCEPT_FINGERPRINT` is an internal env var that should be used only by our cloud since it controls the server's config enforcement.
> 
> 
> 
> The modal to confirm should only appear when the site URL or the database connection string changes, so please provide more info regarding your config.

Thanks for your time 
I didn't change site URL and datebase connection string 
Every time I restart rocketchat I have to confirm that manually 
Here is the config 

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://USERNAME:PASSWORD@mongo.com:27017,mongo1.com:27017,mongo2.com:27017/rocketchat?replicaSet=rs01&authSource=admin&tls=true&tlsCertificateKeyFile=/etc/mongodb.pem
Environment=MONGO_OPLOG_URL=mongodb://oploguser:PASSWORD@mongo.com:27017,mongo1.com:27017,mongo2.com:27017/local?replicaSet=rs01&authSource=admin&tls=true&tlsCertificateKeyFile=/etc/mongodb.pem
Environment=NOTIFICATIONS_WORKER_TIMEOUT=2000
Environment=NOTIFICATIONS_BATCH_SIZE=150
Environment=NOTIFICATIONS_SCHEDULE_DELAY_ONLINE=0
Environment=NOTIFICATIONS_SCHEDULE_DELAY_AWAY=0
Environment=NOTIFICATIONS_SCHEDULE_DELAY_OFFLINE=0
Environment=ROOT_URL=https://mydomain.com
Environment=PORT=3000
Environment=BIND_IP=0.0.0.0
Environment=INSTANCE_IP=x.x.x.x
Environment=AUTO_ACCEPT_FINGERPRINT=true
[Install]
WantedBy=multi-user.target

**Comment by rodrigok** [comment]
@lovekyleman can you put your loglevel to 1 (info) and restart the server? Doing that, do you see any logs related to fingerprint on restart? You can check for `FingerPrint`
