### ISSUE TITLE
"Running_Instances 2"

### ISSUE THREAD

**Issue by gladston3** [RocketChat/Rocket.Chat#3116]
Your Rocket.Chat version: 0.29.0

Under administration -> info -> rocket.chat there is a line "Running_Instances 2".
Does that mean, that I am somehow running two instances of rocket.chat on the same time? If yes, this is definitely not on porpuse.
How can I troubleshoot/fix that issue?

Thank you (:

**Comment by marceloschmidt** [comment]
If it was a recent restart, this could happen. Every time you fire up an instance, there's a new record created in `instances` collection. Then it removes the inactive instances. This removal should not take more than 5 minutes. You could always manually delete the records there, but it would be interesting to know what caused this, in case it didn't fix itself.

**Comment by gladston3** [comment]
Hi,

it happened after I upgraded from version 0.28 to 0.29. But it went away shortly after - exactly like you described. So I guess, there is nothing to fix (;

Thank you for your explanation
Cheers
gladston3
