### ISSUE TITLE
Rocket Chat no Termina de Cargar

### ISSUE THREAD

**Issue by kingdsand** [RocketChat/Rocket.Chat#31169]
buenos dias

tengo el siguiente problema con el servidor rocket que no termina de cargar por la web, se queda la pantalla en gris y los errores que salen en el navegador son los siguientes:

![Screenshot_20231206_110841](https://github.com/RocketChat/Rocket.Chat/assets/5050663/a0eaa8bc-d52f-48c9-882c-1f07f082165c)

la version que tengo instalada es la siguiente y esta en ubuntu 22.

![Screenshot_20231206_103510](https://github.com/RocketChat/Rocket.Chat/assets/5050663/458e67e2-409d-43fa-8dfc-954ccd1862db)

**Comment by mirosodja** [comment]
Same problem with same version except site url on http://localhost:3000

**Comment by ggazzo** [comment]
Could you tell me which value is set for Site_Url ?

**Comment by geekgonecrazy** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/30913 this should fix

Make sure url in your config is the same as you access it.  So if it’s set to localhost then access via localhost.  If you set to my.domain access at my domain.  You get the picture.

You might need to use to adjust the setting OVERWRITE_SETTING_Site_Url=address-you-access-from

**Comment by mirosodja** [comment]
I'll explain how I've fixed exaclty same problem as @kingdsand has but I am not sure that solution is right. Somehow caddy server was running beside apache server. Apache server is configured as proxy and reverse proxy. After shutdown caddy service rocket.chat works normally.

Anyway, I couldn't disabled caddy server completely even I run "sudo snap set rocketchat-server caddy=disable" and "sudo systemctl disable snap.rocketchat-server.rocketchat-caddy.service". It is not active, it's failed (Result: exit-code). But it still loaded with status "loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-caddy.service; disabled; vendor preset:  @enabled)".

**Comment by kingdsand** [comment]
export PORT=3000
export ROOT_URL=http://10.17.8.50:3000/
export OVERWRITE_SETTING_SITE_URL=10.17.8.50
export MONGO_URL=mongodb://localhost:27017/rocketchat
export MONGO_OPLOG_URL=mongodb://localhost:27017/local?replSet=rs01
export StandardOutput=syslog
export StandardError=syslog
