### ISSUE TITLE
Users can edit each others messages

### ISSUE THREAD

**Issue by maxsdw** [RocketChat/Rocket.Chat#3119]
Your Rocket.Chat version: 0.26.0

On **Administration > Permissions**, if **edit-messages** is set to TRUE, users can edit each others messages, which is bad; editing a message should be enable only for the user that created it.

**Comment by zxweed** [comment]
@maxsdw, does you check this by the admin account?

**Comment by maxsdw** [comment]
Yes, we are using one of our admin accounts to check this setting.

**Comment by zxweed** [comment]
@maxsdw admin can edit other's messages, user - no

**Comment by marceloschmidt** [comment]
It's by definition that admins, owners and moderators can edit other users' messages. You can remove that permission, if you'd like to. Go to Administration, then Permissions, then uncheck the `edit-message` permission for each role you don't want to allow that.

**Comment by kariem** [comment]
@marceloschmidt I have adapted the permissions: for the `edit-message` permission there is only a check for the role _owner_. However, as an administrator I can still edit other user's messages. Should I add a separate bug report?
