### ISSUE TITLE
update user fails

### ISSUE THREAD

**Issue by dazoot** [RocketChat/Rocket.Chat#31221]
### Description:

It's imposible to update users from the Administration section.

### Steps to reproduce:

1. Go to Administration -> Users
2. Click on any user and try to add a new role ex: `livechat-agent`
3. Click `Save`

### Expected behavior:

The user to be updated.

### Actual behavior:

Nothing gets updated and we get an error:

`Cannot read properties of undefined (reading '_id')`

![image](https://github.com/RocketChat/Rocket.Chat/assets/1543455/093097e7-fdcf-4e0c-baf4-78be99e36fad)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.5.0
- Operating System: Debian 10
- Deployment Method: `tar`
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.3
- MongoDB Version: 4.4.26

### Client Setup Information

- Desktop App or Browser Version: Desktop App and Browser (chrome)
- Operating System: Windows 10

**Comment by swapnilshah5889** [comment]
Hello @dazoot,
I tried editing a user from the administration section and I was able to update it successfully in my local. Can you please share more info or steps about how to reproduce this error? I have attached a screenshot of my local showing the success message upon editing and saving a user profile. 

![image](https://github.com/RocketChat/Rocket.Chat/assets/21017928/ed57a1ef-bc2e-491e-908c-4aec79d2bde3)

**Comment by Gummikavalier** [comment]
Same, I could not reproduce with RC 6.5.0. Probably best to try with an incognito browser session to ensure a clean cache in the session.

I noticed that for instance LDAP settings clearly have cache issues coming from older version to 6.5.0. (And often even between simply reloads of pages too.)

**Comment by Sayan4444** [comment]
I tried it on igognito and still unable to reproduce the issue

**Comment by sumanbalayar08** [comment]
I wanna solve this issue. Can you assign me this issue?

**Comment by Airbornharsh** [comment]
@dazoot I am Unable to Reproduce the issue. I guess it is solved. Share the logs

**Comment by VenkateshSircilla123** [comment]
![Screenshot from 2024-01-18 21-21-26](https://github.com/RocketChat/Rocket.Chat/assets/113850972/5f94440d-4965-4551-a64b-f87d81e82ed0)
its working for me.

**Comment by dazoot** [comment]
I did an upgrade to latest version 6.5.3, disabled omnichannel and it seems to be working now.

**Comment by Sayan4444** [comment]
@dazoot Great! if the issue is solved, then you may close it

**Comment by dazoot** [comment]
Did an upgrade to `6.7.1` and again we have this issue:

`Cannot read properties of undefined (reading '_id')`

Also login does not work anymore on the iPhone app. Wrong password.

**Comment by dazoot** [comment]
Disabled my 2fa from my profile / preferences. Logged in on mobile then and reset 2FA. Both work now.
