### ISSUE TITLE
*Rocket.Chat Alert:* flood every day

### ISSUE THREAD

**Issue by Nowatel** [RocketChat/Rocket.Chat#31238]
### Description:

Everyday I recieve:

*Rocket.Chat Alert:*

Workspace members are not receiving notifications on mobile
Remove notification limit with Enterprise trial.

Workspace is ok, starter license is active and working fine. Notifications are working, limits are ok.

### Steps to reproduce:

Wait 24h :)

### Expected behavior:

Stop flooding, proper workspace recognition. 

### Actual behavior:

<img width="835" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/48793688/49898e4c-e1f5-419a-b8af-58bd742c63b6">

### Server Setup Information:

Deployment
Version
6.5.0
Deployment ID
wwkoRcEHKZTySBtA3
Apps Engine Version
1.41.0
Node Version
v14.21.3
Database Migration
304 (December 2, 2023 1:58 PM)
MongoDB
6.0.12 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (2a3306701)
Branch: HEAD
Release 6.5.0

### Client Setup Information

- Desktop App or Browser Version: Desktop App 
- Operating System: Windows

**Comment by geekgonecrazy** [comment]
We had a period of a few versions where alerts weren't being delivered.  So these are likely prior months where push hit the cap.  6.5.0 this bug was fixed so all of the alerts were being fetched.  We've updated so alerts expire after which they can't be fetched so should stop this from being possible in the future and also retroactively expired all other alerts.  So this should stop happening.

**Comment by iMitya** [comment]
Hello, we have the same problem. Onn December 7, 2023, service messages about the notification limit for mobile devices began to arrive.
Versiona 6.5.2
Plan Starter
![2024-01-12_11-13-57](https://github.com/RocketChat/Rocket.Chat/assets/156410963/a9be694d-215d-4263-abfd-c65e131887a5)

**Comment by iMitya** [comment]
> We had a period of a few versions where alerts weren't being delivered. So these are likely prior months where push hit the cap. 6.5.0 this bug was fixed so all of the alerts were being fetched. We've updated so alerts expire after which they can't be fetched so should stop this from being possible in the future and also retroactively expired all other alerts. So this should stop happening.

Please read the above message from me.

**Comment by cutzenfriend** [comment]
Doesn't stop happening. All of our users get this message everyday since 6.5.0 and we are currently on the newest version.
