### ISSUE TITLE
nodejs OOM in 6.4.2

### ISSUE THREAD

**Issue by Kot-o-pes** [RocketChat/Rocket.Chat#31240]
### Description:
Rocketchat failed with OOM error

### Steps to reproduce:

`
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory 1: 0xa3ad50 node::Abort() [node] 2: 0x970199 node::FatalError(char const*, char const*) [node] 3: 0xbba90e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node] 4: 0xbbac87 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node] 5: 0xd76ea5 [node] 6: 0xda783e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node] 7: 0xdb3876 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node] 8: 0xd9fa0f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node] 9: 0xd9fc88 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
`
### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: debian10
- Deployment Method: k8s
- Number of Running Instances: 1
- DB Replicaset Oplog: 5.0.14 / wiredTiger (oplog Enabled)
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.14

**Comment by KevLehman** [comment]
Can you share a bit more about your environment & deployment setup? Also, does it fail at boot, or when you're doing some operation?

**Comment by Kot-o-pes** [comment]
> Can you share a bit more about your environment & deployment setup? Also, does it fail at boot, or when you're doing some operation?

Its running in k8s, deployment has one replica and nginx ingress, i dont see any errors in log before this message except 
```
Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/c0092699-6e89-4bf4-bcc8-71c77a9c4539.zip' => awaited here: at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12) at server/lib/dataExport/uploadZipFile.ts:11:16 at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 => awaited here: at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12) at server/lib/dataExport/processDataDownloads.ts:232:25 at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 { errno: -2, code: 'ENOENT', syscall: 'stat', path: '/tmp/zipFiles/c0092699-6e89-4bf4-bcc8-71c77a9c4539.zip'
```

**Comment by Kot-o-pes** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/31114 this might be related

**Comment by Kot-o-pes** [comment]
Ive also set up exceptions monitoring and noticed that these exceptions occurs on a daily basis 
```
Rocket.Cat
9:52
URI malformed
URIError: URI malformed
    at decodeURI (<anonymous>)
    at Router.match (/app/bundle/programs/server/npm/node_modules/meteor/rocketchat_restivus/node_modules/connect-route/lib/connect-route.js:61:12)
    at /app/bundle/programs/server/npm/node_modules/meteor/rocketchat_restivus/node_modules/connect-route/lib/connect-route.js:102:24
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 ```
 
 and this one 
 ```
 Rocket.Cat
8:18
Can't wait without a fiber
Error: Can't wait without a fiber
    at Function.wait (/app/bundle/programs/server/node_modules/fibers/future.js:159:9)
    at Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:448:10)
    at MongoConnection.findOne (packages/mongo/mongo_driver.js:829:84)
    at Collection.findOne (packages/mongo/collection.js:459:29)
    at getUserById (packages/accounts-password/password_server.js:5:51)
    at AccountsServer.Accounts.generateResetToken (packages/accounts-password/password_server.js:402:16)
    at AccountsServer.Accounts.sendEnrollmentEmail (packages/accounts-password/password_server.js:567:14)
    at Immediate.<anonymous> (app/lib/server/functions/setUsername.ts:102:14)
    at processImmediate (internal/timers.js:464:21)
    at process.topLevelDomainCallback (domain.js:152:15)
    at process.callbackTrampoline (internal/async_hooks.js:128:24)
    ```
    not 100% sure its related but looks weird to me

**Comment by Kot-o-pes** [comment]
updated to 6.4.8 OOM still happens 
```
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa3ad50 node::Abort() [node]
 2: 0x970199 node::FatalError(char const*, char const*) [node]
 3: 0xbba90e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbbac87 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd76ea5  [node]
 6: 0xda783e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xdb3876 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 8: 0xd9fa0f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
 9: 0xd9fc88 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
 ```

**Comment by Kot-o-pes** [comment]
@KevLehman fyi

**Comment by KevLehman** [comment]
Yeah, it's a bit hard to tell without knowing more about your setup. RAM, what's deployed there, hoe much memory is available to k8s, where's mongo hosted, etc.
