### ISSUE TITLE
Text area only shows the last line of the message

### ISSUE THREAD

**Issue by vkklt** [RocketChat/Rocket.Chat#31252]
### Description:

When a user types a long message in Rocket.Chat (which causes the text area to grow), leaves the chat for another without sending the message, and then returns, the text area only shows the last line of the message. The user needs to use the up arrow to navigate through the lines of the message, as the text area does not grow again.

Typing a long message
![Captura de tela 2023-12-15 154513](https://github.com/RocketChat/Rocket.Chat/assets/109630661/c1036b83-99e7-4128-aded-c489e96dc740)

After leaving and returning to the chat without sending the message
![Captura de tela 2023-12-15 154521](https://github.com/RocketChat/Rocket.Chat/assets/109630661/2e4862d0-bb30-4195-93fd-7eab153ddedb)

### Steps to reproduce:

1. Type a long message in Rocket.Chat, causing the text area to grow.
2. Leave the chat for another chat without sending.
3. Return to the original chat.

### Expected behavior:

The text area should display the entire message, not just the last line. 

### Actual behavior:

The text area only shows the last line of the message. The user needs to use the up arrow to navigate through the lines of the message.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.0
- Operating System: Ubuntu Server 
- Deployment Method: snap
- MongoDB Version: 5.0.15 

### Client Setup Information

- Desktop App or Browser Version: I tested on Firefox and Edge, desktop app version 3.9.x
- Operating System: Windows 10 and 11

**Comment by Debshibraj123** [comment]
@vkklt  I can work on it please assign it to me

**Comment by aayank13** [comment]
hey @vkklt , please assign this issue to me

**Comment by hugocostadev** [comment]
No need to ask for permission to fix the issue, feel free to work on it! 
Just check if someone it's already raised a PR for that (should be linked in this issue).
Best of luck 🚀 👏 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
