### ISSUE TITLE
Incorrect invitation link to the team

### ISSUE THREAD

**Issue by sanyappc** [RocketChat/Rocket.Chat#31250]
Incorrect invitation link to the team

### Steps to reproduce:

1. Go to group
2. Click on Members -> Invite Link
3. Get link

### Expected behavior:

Working link 
https://127.0.0.1:3000/invite/AvcDef
that adds users to the team

### Actual behavior:

Non-working link
https://127.0.0.1:3000/invite?host=127.0.0.1%3A3000&path=invite%2FAvcDef
that says "Рage not found"

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.0
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.9 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: chrome 120.0.6099.62
- Operating System: windows 11

**Comment by bajajtushar094** [comment]
Hi @sanyappc, I can work on the issue. Can you assign it to me?

**Comment by sanyappc** [comment]
@bajajtushar094 I'm a regular user and just reported the bug. I don't have the authority to assign bugs to anyone

**Comment by MartinSchoeler** [comment]
@bajajtushar094 There is no need for assignments in the Rocket.Chat Repo, just create a PR fixing the issue and mention the relevant issues

**Comment by hugocostadev** [comment]
Do you have some customization on your instance? 

The link should use the https://go.rocket.chat/ website to choose where the user wants to open the link, like that: 

![image](https://github.com/RocketChat/Rocket.Chat/assets/20212776/b4dd8a7d-1b51-4867-9f07-f0db3543f086)

Can you check the `Accounts_Registration_InviteUrlType` setting value? Thanks

**Comment by sanyappc** [comment]
@hugocostadev
No, just docker.
Accounts_Registration_InviteUrlType is set to Proxy. Looks like the default value

**Comment by ameeetgaikwad** [comment]
Working on this issue!

**Comment by hugocostadev** [comment]
Very weird... You should be getting the https://go.rocket.chat/ link instead of an IP address

**Comment by sanyappc** [comment]
@hugocostadev I reset the DeepLink_Url value and it works now
