### ISSUE TITLE
Link to channels from Layout= Home Body

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#3125]
Hi all,

Not sure if this ticket should be under cordova app or here. Since its a little bit of both.

I am struggling with the **Home Body** ,  administration => layout => Home Body.
I would like to have links on that page that takes the  user directly to different  #channels 

I can get it to work with desktop clients, but I cant figure our how to do such href that works in the cordova app. When a user clicks on it in their app then the app will open up an external window in the browser (chrome/safari)

Anyone have any quick html fix or is this a much bigger task than I expect?

**Comment by dytec** [comment]
I think it´s related to #2607

**Comment by lunitic** [comment]
Not sure .. I don't understand the other ticket...

**Comment by IQ2022** [comment]
not sure i understand as well.. did you mean something like this
<tr><td><span style="font-weight:bold"><a href="/channel/general">#general </span></td><td>General  Discussions </td><td>Public</td></tr>

This works for me

**Comment by lunitic** [comment]
@IQ2022 Cheers that did the trick!!

My  href  had the full URL href="https://myserver.com/channel/general  and then it will open in Safari and Chrome.
