### ISSUE TITLE
Merge channel and private group lists

### ISSUE THREAD

**Issue by samhocevar** [RocketChat/Rocket.Chat#3126]
I would love an option (or even the default behaviour, I believe it would make more sense) to merge channels and private groups in the sidebar.

Rationale for this:

 - there is already visual feedback to tell channels and private groups apart (the lock icon vs. the # icon)
 - owners can change a channel into a private group at any moment and conversely, which will move the room around in the users’s sidebar and cause confusion
 - when one has many direct messages open, *massive* amounts of scrolling are required to reach the bottom of the sidebar to see private groups

**Comment by nemolivier** [comment]
Other solution than merging the lists : 
- make the « private messages » list foldable (and other lists too) ;
- add this list under the private chanel.

**Comment by amayer5125** [comment]
I do enjoy having channels and private messages grouped on slack. This would be a great option.
