### ISSUE TITLE
Buggy dropdown for `country` selection field.

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/Rocket.Chat#31260]
I'm getting a bug. This is related to the dropdown menu of the Country selection filed when registering.

### Description:
The dropdown doesn't close automatically after selecting and also isn't opened in the right place.

### Steps to reproduce:

1. Go to register page. Step 2 of 4.
2. Fill -> Organization name, Organization industry, Organization size, 
3. Fill country preference, and see the error.

### Expected behavior:

The dropdown should be closed after selecting and also should be opened in the right place.

### Actual behavior:

[dropdown.webm](https://github.com/RocketChat/Rocket.Chat/assets/95426993/f8753deb-dad0-423f-a9dc-531477bcd67f)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0-develop
- Operating System: linux (Using gitpod)
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.4 - x64
- MongoDB Version: 6.0.3

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 10

**Comment by apurb-coder** [comment]
hey @umangutkarsh I would like to work on this issue

**Comment by ajay2827** [comment]
@umangutkarsh  can you please assign this to me, so that I can start working on it.

**Comment by thejaysharma** [comment]
Hey @umangutkarsh, I want to work on this issue, Could you please assign it to me?

**Comment by pranay911** [comment]
Hi **@umangutkarsh** Could you Please assign this issue to me?

**Comment by kh-ac** [comment]
@umangutkarsh 
I didn't get the same steps (organization name, country , etc...) when trying to register 
can you explain how to reproduce the Bug ?

**Comment by hugocostadev** [comment]
duplicated of: https://github.com/RocketChat/Rocket.Chat/issues/31200 

It's going to be fixed in the next patch release (6.5.1) by this PR: [fix: country select #31305](https://github.com/RocketChat/Rocket.Chat/pull/31305)
