### ISSUE TITLE
pass client cert with ldap request

### ISSUE THREAD

**Issue by umdstu** [RocketChat/Rocket.Chat#3129]
Your Rocket.Chat version: 0.28.0

Hi,

Is there a way to pass a client cert to the ldap server? Trying to pass a client-cert file in the connection request but can't see that in the example code. If so, how is it done? If not, can this be added?

"Test" lookups fail with:

`SSL3_GET_RECORD:wrong version number:s3_pkt.c:339 in the log`

This error clears up on the command line using openssl s_client once I pass in the -cert option

Thanks

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
