### ISSUE TITLE
Language selection box is empty which should be default

### ISSUE THREAD

**Issue by cherish2003** [RocketChat/Rocket.Chat#31307]
### Description:

Language selection box in preferences section is empty when opened which should be default 

### Steps to reproduce:

1.  Go to Account
2.  Click on Preferences
3. See language selection box

### Expected behavior:

 language selection box should be set to default which is empty when opened 

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/88829894/0246383a-57a8-4361-bac5-b1c9a4bb96e9

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Sayan4444** [comment]
This is hard to replicate. After when you change it to default, can you tell me which steps to reproduce to get the blank selected input field which is main issue again?

**Comment by Lovakush** [comment]
@cherish2003 Please assign this issue to me. I am interested to work on this issue

**Comment by Lovakush** [comment]
[fix : change Language selection box is empty to Default](https://github.com/RocketChat/Rocket.Chat/pull/31317)

@cherish2003

**Comment by Lovakush** [comment]
#31317
