### ISSUE TITLE
[Improvement] No hover effect on 2 "Check it out" buttons in the Home Page

### ISSUE THREAD

**Issue by Sch476** [RocketChat/Rocket.Chat#31319]
### Description:
On hovering over the "Check it out" buttons in the Home Page, it has a over effect. But 2 of the "Check it out" buttons doesn't have this hover effect. 
It is a Visual Bug. 

### Steps to reproduce:

1. Go to "rocket.chat".
2. Scroll down and hover on "Check it out" buttons.

### Expected behavior:
On hovering on all "Check it out" buttons, an hover effect should happen.

### Actual behavior:
On hovering on all "Check it out" buttons, 2 of the buttons don't have the hover effect.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Braver
- Operating System: Windows 11

### Additional context
Screencast : 

https://github.com/RocketChat/Rocket.Chat/assets/127319225/1bb7da9a-c79f-4177-b5c8-1929cdf8c43b

**Comment by Bhupender-kumar455** [comment]
It's sure a UI bug. I can fix this .

**Comment by manideep1428** [comment]
It's CSS bug. I Will Fix it

**Comment by pankaj-2503** [comment]
There is not problem in this as they have not included the hover effect that's it.

**Comment by metakunal** [comment]
Hi @Sch476 I can fix this issue. Can I get it assigned to me.

**Comment by MartinSchoeler** [comment]
Hey, unfortunately this issue cannot be fixed by the community as our website is closed source, don't worry I'll pass this issue to the website team, thanks!
