### ISSUE TITLE
[UI] [Minor] Select submenu of Lower res screens position issues on Setup Wizard page

### ISSUE THREAD

**Issue by 8rxn** [RocketChat/Rocket.Chat#31314]
### Description:

On lower resolution screens, in the org registration screen [setup-wizard/2], country select options positions weirdly.

### Steps to reproduce:

1. Reduce the Resolution to a wide screen width less than approximately 768px [or a regular screen with equivalently increased scaling/zoom].
2. Go to the new org creation page ['/setup-wizard/2'] 
3. Click on Country select menu 

### Expected behavior:

The select sub-menu should come right below the option.

### Actual behavior:

It positions somewhere towards the top of the container

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6
- Operating System: Ubuntu 22.04.2 LTS
- Deployment Method:  Local development server from fork
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.4 - x64           
- MongoDB Version: 6.0.3

### Client Setup Information

- Desktop App or Browser Version: Brave Version 1.61.109 Chromium: 120.0.6099.144 (Official Build) (64-bit)
- Operating System: Ubuntu 22.04.2 LTS

### Additional context

![Screenshot from 2023-12-24 18-57-26](https://github.com/RocketChat/Rocket.Chat/assets/75237697/f6dfbf31-5318-422d-bd23-8c4c181072ba)

### Relevant logs:

Couldn't finds any relevant logs. Seemed like a css issue.

---
This is my first issue report here. Please let me know if I may have made any errors/ wrongly tagged anything. I'll be happy to change that.

**Comment by SahilDahekar** [comment]
I had faced a similar issue yesterday where i typed india it although filtered the dropdown for me but i was not able to select the country in dropdown and had to refresh the page .

**Comment by Akshaybagai52** [comment]
Hi if it's issue is open can i contribute to it 
Thanks

**Comment by its-kunal** [comment]
Hey, can I contribute to this issue?

**Comment by Nandini-Maheshwari** [comment]
Hey
If no one is working on this, may I ?

**Comment by SahilDahekar** [comment]
This issue is fixed by PR #31325

**Comment by Devansht420** [comment]
Yes its fixed and is going to be added in the next patch.

Its the same as [#31260](https://github.com/RocketChat/Rocket.Chat/issues/31260)
@8rxn you can close this issue now

**Comment by 8rxn** [comment]
@Devansht420 Thanks for pointing out that it's already fixed. I must have missed it. I'm closing it now.
