### ISSUE TITLE
Hubot Cannot Listen/Respond When Invited To Private Group

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#3132]
Your Rocket.Chat version: 0.29

I have hubot set to listen on all public and able to accept direct messages. There is an issue where he can only listen and respond to private group when he is invited on the initial creation of the channel, but cannot listen and respond to private groups when he is invited after the initial creation of the private group.

We have users that have already created private groups with info and would like to invite hubot but they would have to delete their private group and recreate it with him as a member.

**Comment by MartinSchoeler** [comment]
@agrover Is this still happening in the latest release?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Comment by reetp** [comment]
I am experiencing this or similar on v0.57 - CentOS 6, Node 4.7.x

Not sure if it should be re-opened or a new bug created

If I create a Public channel I can add and chat to the internal hubot.
If I convert it to Private the bot does not respond
Convert back it Public and it works again

Let me know if you want to reopen or create a new bug, and any debugging info I can provide.

**Comment by MartinSchoeler** [comment]
@reetp please create a new issue following our new issue guidelines. Thanks!

**Comment by reetp** [comment]
Someone else already has:
https://github.com/RocketChat/Rocket.Chat/issues/7550
