### ISSUE TITLE
Clicking my own avatar in a private message shows the other person's profile

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#3133]
Your Rocket.Chat version: latest (confirmed on your instance at rocket.chat)

This isn't a big deal, but I thought I'd log it as a bug. When I'm in a PM room, if I click on my own avatar, the other person's profile opens. I would expect my own profile to open.

It's an odd use case where I was going to change my profile pic. It's not a big deal but one of those little things that makes the app look fragile.

**Comment by cjanietz** [comment]
You personally might think this not intended, but it actually is.

**Comment by mccambridge** [comment]
Okay, I see. I just expect clicking on my avatar next to a message would do the same thing it does in #general as it would in a PM. Why would you intend to have clicking my avatar open someone else's profile?

**Comment by marceloschmidt** [comment]
Thanks for the PR! But I'm over the edge on this one... what if you click your own avatar, then you click on the sidebar icon for hiding that panel and then, later on, click again on the sidebar icon, now to show the user details... I'd expect it to show the details from the user I'm talking with, not my own details.

**Comment by mnt** [comment]
Well how I see it is if you hide the panel and you open the panel again why should it change ? Im not here to have an huge debate but this is my personal opinion. Ill see what I can do so that it would work in your case.

**Comment by marceloschmidt** [comment]
I guess we could merge that as is, as it's already better than what we had before. I've asked myself before why clicking on my own name would open up the other user's info ;) @RocketChat/core what do you think?

**Comment by agirisan** [comment]
FWIW I think clicking my own name should open my own profile. Very often I click on my own name intending to check or edit something and get annoyed when I get the other user's profile...

I for one would like to see the PR merged.
