### ISSUE TITLE
Minimize the media by clicking outside the image, instead of using the minimize arrow.

### ISSUE THREAD

**Issue by Sanskar711** [RocketChat/Rocket.Chat#31341]
### Steps to reproduce:

1.  Login to rocket chat.
2. Go to any Community chat.
3. Click on any media 

### Expected behavior:

Clicking on area nearby should close the image

### Actual behavior:

![issue1](https://github.com/RocketChat/Rocket.Chat/assets/97801615/3b436bf4-bca1-41df-a4fd-72d486c1aaf6)

I think this feature will improve user experience significantly

**Comment by Sayan4444** [comment]
@Sanskar711 I hope this PR may solve this issue. If you find something wrong or wanted to convey something else, please revert me back
