### ISSUE TITLE
Possiblity breaking changes in new Meteor version

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#3134]
Meteor will probably have [this batching feature](https://github.com/meteor/meteor/pull/5680) merged in.

I think as a consequence, [meteor streams](https://arunoda.github.io/meteor-streams/) will stop working.

Personally, I would claim that Rocket.Chat should move away for streams anyway for and just use [control-mergebox package](https://github.com/peerlibrary/meteor-control-mergebox) ([#1710](https://github.com/RocketChat/Rocket.Chat/issues/1710)), but it would be probably good to first even see if it is really breaking anything.

**Comment by marceloschmidt** [comment]
We started using our own streamer: https://github.com/RocketChat/meteor-streamer
It is possible that it will also break, but let's confirm it first.

**Comment by rodrigok** [comment]
@mitar I did some tests with the project around the package (as you can see here https://github.com/RocketChat/meteor-streamer) upgrading the project `meteor update --release 1.3.3-ddp-batching-beta.0` and everything is working great.

So I will close this issue for now, if you find another problem please reopen it.

Thanks.

**Comment by geekgonecrazy** [comment]
Thanks for bringing this up!  Always best to try before hand then be blindsided.

> Personally, I would claim that Rocket.Chat should move away for streams anyway for and just use control-mergebox package (#1710)

@mitar personally i'm interested to hear some of your thoughts behind thinking we should move towards control-mergebox instead of streams.

**Comment by mitar** [comment]
Let's have that conversation in #1710.

**Comment by mitar** [comment]
Also see #894.

**Comment by geekgonecrazy** [comment]
ah thanks!  I have some reading to do :smile:
