### ISSUE TITLE
End Users Should NEVER See "Workspace version unsupported"

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#31358]
### Description:

End users (non-admins) should NEVER see messages in the desktop app or mobile app that a workspace version is unsupported.  We are currently running 6.3.12.  I realize that support for this version is ending this month.  However, that is a message that should ONLY be shown to admins!

### Steps to reproduce:

Run  version 6.3.x of RC.  On the latest mobile app and desktop apps get the following message
![image](https://github.com/RocketChat/Rocket.Chat/assets/6833993/46068a43-c5d5-410d-811d-239f69c228e3)

### Expected behavior:

Only admins should ever see this message.  If you are going to spam users with this message, at least give admins the ability to turn off that notification.

### Actual behavior:

Non-admins are receiving these messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.12
- Operating System: Linux
- Deployment Method: build images found at cdn-download.rocket.chat/build/
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.23

### Client Setup Information

- Desktop App or Browser Version: latest versions
- Operating System: All operating systems

**Comment by barbarazanellaa** [comment]
Hello, @mddvul22!

Thank you for contacting us. We are currently aware of this issue and are working to fix it :)
End-users should receive this message ONLY if their admins don't upgrade their workspaces after 15 days out of the supported window.

Please let us know if there is anything else we can do to help.
Best regards, Bárbara Zanella.
