### ISSUE TITLE
Feature Request : Add a customization option for user to switch between dark and light mode

### ISSUE THREAD

**Issue by pankaj-2503** [RocketChat/Rocket.Chat#31353]
### Description:

Add a button with functionality like switching between light and dark mode on the rocketchat.io main website . 

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Adding own customization while working on website 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by pankaj-2503** [comment]
>  https://rocket.chat/

**Comment by KevLehman** [comment]
Oh, okay. This repository is not related to that landing page. I'll forward the request for a dark mode switch with the corresponding internal team so they can work on that.

Code for that page is not open source either, so you may not see any PR related to that change.

Thx for your interest in making the site better 🤗 I'm gonna close this issue.
