### ISSUE TITLE
License invalid after upgrading to 6.5.1

### ISSUE THREAD

**Issue by BeConfused** [RocketChat/Rocket.Chat#31379]
### Description:

After upgrading to 6.5.1 The log reports an error and considers the license as invalid.
Syncing the license manually does not change this and the server reports itself as community license.

### Steps to reproduce:

Deploy a Rocketchat with an Enterprise License with version 6.4.4 using helm and upgrade by changing the tag to 6.5.1

### Expected behavior:

License does not change and is validated in server logs.

### Actual behavior:

License is registered as Community in frontend.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4 to 6.5.1
- Operating System: Official Docker Image (Debian GNU/Linux 11 (bullseye))
- Deployment Method: official Helm chart version 6.4.4 with overridden tag rolled out with ArgoCD
- Number of Running Instances: Rocket.Chat: 1 / MongoDB: 3 Replicas + 1 Arbiter
- NodeJS Version: v14.21.3
- MongoDB Version: v6.0.9

### Client Setup Information

- Desktop App or Browser Version: Ferdium 6.7.0 / Chrome / Firefox / RocketChat Native App 
- Operating System: Pop!_OS 22.04, MacOS (Sonoma 14.2.1)

### Relevant logs:

Server Log Error:

```
== UnHandledPromiseRejection ===
InvalidLicenseError: Invalid license
    at validateFormat (/app/bundle/programs/server/npm/node_modules/@rocket.chat/license/dist/validation/validateFormat.js:14:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at LicenseImp.setLicense (/app/bundle/programs/server/npm/node_modules/@rocket.chat/license/dist/license.js:180:15)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at ee/app/license/server/startup.ts:100:6
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
---------------------------------
Errors like this can cause oplog processing errors.
Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Future node.js versions will automatically exit the process
=================================
```

**Comment by ggazzo** [comment]
If you have an enterprise license, does that mean you paid for it, correct? I suggest you talk with rocket.chat support so they can understand when this license was generated and if there is any issue. If it persists, they may even generate a new v3 license for you, which I'm sure will work. also since you are registered, just performing a sync with cloud should give you a new license.
