### ISSUE TITLE
User Unable To Leave Channel

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#3137]
Your Rocket.Chat version: 0.29

When a user is attempting to leave a channel, they receive an error message stating they can't leave a 'livechat' and that they must use the close button. We don't have livechat enabled.

<img width="477" alt="screen shot 2016-05-04 at 3 09 58 pm" src="https://cloud.githubusercontent.com/assets/8405384/15028850/873f9918-1210-11e6-91e8-25632af9da49.png">

**Comment by ChanningMorris** [comment]
Already reported and fixed: https://github.com/RocketChat/Rocket.Chat/issues/3121
