### ISSUE TITLE
No Error Handling in the v1 Chat.ts

### ISSUE THREAD

**Issue by Airbornharsh** [RocketChat/Rocket.Chat#31381]
### Description:

there is no error handling in the chat.ts file. It can cause crash if not handled properly.

### Steps to reproduce:

1.  Go to apps > meteor > app > server > v1 > chat.ts
2.  Try to add error handler for all api

**Comment by HARSH048** [comment]
Hi  @Airbornharsh ,
I'm Harsh,  interested in contributing toRocketChat.  I've been exploring the project and am particularly interested on this issue. I'd love to contribute by working on this issue.
Looking forward to contributing to this issue Can you assign this to me.

**Comment by Airbornharsh** [comment]
@HARSH048 I have added a PR. Maintainers will check if it is valid

**Comment by hugocostadev** [comment]
Sorry, but in witch scenario is not handling error correctly? Not having try/catch does not mean that there are not error handling

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by Sayan4444** [comment]
@Airbornharsh can you tell me the error which is not handled like a situation in which u expected something but something else is happening. A small video will be great
