### ISSUE TITLE
Publish checksum with new releases

### ISSUE THREAD

**Issue by stevenhfotofix** [RocketChat/Rocket.Chat#3139]
Your Rocket.Chat version: 0.29.0

Publishing with Ansible, requires updating the rocket_chat_tarball_sha256sum with the latest checksum for the tarball located at https://rocket.chat/releases/latest/download

The project itself is not updated very often, and when it is - its often updated just before the main project has a new latest release - giving the checksum almost no time for being useful.

Currently, there is no published checksum that I can find for the latest release.  We can download the file and get our own checksum, but that kinda defeats the purpose of them in the first place - as we don't know if our downloaded file has been compromised.

Can we get an official checksum posted either on https://rocket.chat/releases or https://github.com/RocketChat/Rocket.Chat/releases when a release has been made?  It would be useful for more than just Ansible.

**Comment by marceloschmidt** [comment]
@Sing-Li could you take this one, please?

**Comment by sampaiodiego** [comment]
@geekgonecrazy how could we achieve this? we already have a gpg signature just need an md5 file as well.

I was looking how ubuntu does that https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu but I'm not that used to GPG :grimacing:

**Comment by geekgonecrazy** [comment]
Do we want another in addition to our current signature?  It’ll already alert if tampered.

I think it would be pretty easy though... in ci do sha256sum then drop it somewhere just like we did with the .asc file

**Comment by stevenhfotofix** [comment]
> Do we want another in addition to our current signature? 
Is the RocketChat/Rocket.Chat.Ansible role being depreciated?  It has not had a release in over a year, and is using some rather old versions of node in its install (node 8.9.4 and NPM 5.6.0, vs the recommended version for the latest RC release of 8.11.4 and NPM 6.4.1)

The sha256sum check in the current role is currently a joke, since I have to download it once - have it fail and tell me the new hash, then I put the new hash into the playbook and it will finish the install.  If it was tampered with, I would have no clue since I have no official sha256sum to work with.

If ansible is no longer supported, then this ticket is out of date and no longer needed.  Otherwise, I don't see a way around needing to get this from an official source.

**Comment by geekgonecrazy** [comment]
@stevenhfotofix its definitely not deprecated.  The maintainer has been unavailable so we're trying to find those familiar enough to help us get the role updated.  

So if you are familiar we definitely welcome help to getting updated.  But we for sure want to keep it around

**Comment by stevenhfotofix** [comment]
I am not too familiar with it, just enough to get rocket.chat running, honestly.  However I will take a close look at it this weekend to see if its something I would feel that I could contribute to.  

Ansible is something I have wanted to dive more into with my production environment anyways - and this may be a good excuse to get me to actually do something.  If nothing else, than to have a playbook flag to disable the sha256sum until a solution is ready.

**Comment by geekgonecrazy** [comment]
Take a look at our dockerfile here: https://github.com/RocketChat/Docker.Official.Image/blob/master/Dockerfile#L40 for an example of retrieving an verifying the integrity that we use for all of the places we download the release as part of process

**Comment by geekgonecrazy** [comment]
https://releases.rocket.chat/latest/asc is the link to the latest signature.  This validates the integrity.

Can substitute latest with your release of choice.
