### ISSUE TITLE
im counters endpoint fails after successful login

### ISSUE THREAD

**Issue by zeitan** [RocketChat/Rocket.Chat#31390]
### Description:

After login in the service using the API  an user admin with permission to view room fails in ge counter for a chat room
<img width="430" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/245020/9be52407-ac02-4eff-b80f-55fb374f828d">
<img width="860" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/245020/5d547240-31cd-4ebd-92d3-8157c42504e7">

Room was created by user authenticated to google

### Steps to reproduce:

1. login with user and passowrd, get  auth-token and userId from rocket chat server
2. try to get counter for a existent chatRoomId or existen chatRoomId and userId in the chat, got 403
3. channels endpoint using the same auth info is working

### Expected behavior:
get the ounters

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.8
- Operating System: Linux
- Deployment Method: docker/k8s
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Teak-Rosewood** [comment]
Could you specify the API you are using, as the API doesn't seem to have a room.counter endpoint in its documentation.

**Comment by jaymehta002** [comment]
can you assign me this issue?
I need details of api

**Comment by zeitan** [comment]
I'm using this API: https://developer.rocket.chat/reference/api/rest-api/endpoints/messaging/im-endpoints/counters @jaymehta002  (I create firt a IM/DM room with https://developer.rocket.chat/reference/api/rest-api/endpoints/messaging/im-endpoints/create (using google auth)

**Comment by Teak-Rosewood** [comment]
i am unable to reproduce your issue, could you help me figure out where I'm going wrong?
i have first created the room as ADMIN with 3 people
![create-room](https://github.com/RocketChat/Rocket.Chat/assets/88363398/08988068-8e34-45e5-8268-f5e182a47e72)
I have sent a dummy message to check its working
![send-message](https://github.com/RocketChat/Rocket.Chat/assets/88363398/45f08f61-0ef2-4dbd-bd60-552c432cb31d)
I called the API you have specified logged in with the authentication of user and I am receiving a counter
![counter-received-1](https://github.com/RocketChat/Rocket.Chat/assets/88363398/4f8a356e-1404-4044-b4b1-5976d3776737)
![counter-received-2](https://github.com/RocketChat/Rocket.Chat/assets/88363398/bfc9c8da-9ea2-403b-8d0a-24251aae681a)
and it seems to be working fine

**Comment by zeitan** [comment]
Hi @Teak-Rosewood ,  thanks or answering quickly.
1. I created the IM-room with a userA (in this case this userA is authenticated to Google, when the IM-room was created I invited to a user B to this IM-room
2.  After that I used a user C (not google authenticated  but admnin) to get ciounters, in that poibnt is when I got a 403.
As I referred in the description above I defined my admin user (user C) with view-room-adminitration
<img width="387" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/245020/29e44a1e-5e72-4aba-b3f3-72fd09410b2a">
what could I be doing bad on my side to receive a 403??

**Comment by Teak-Rosewood** [comment]
Okay there seems to be an issue with the permissions and getting the counter, I am looking into this issue. 

I have identified another problem in the process: Chat room doesn't seem to be created when an admin creates a chat room without the admin in the room.

**Comment by zeitan** [comment]
Thanks for the update @Teak-Rosewood  I will wait for the update in this issue

**Comment by zeitan** [comment]
Not sure if it's related (using same users described [here](https://github.com/RocketChat/Rocket.Chat/issues/31390#issuecomment-1881485169) ) to the same issue but I got the same error (403) when I try to use this API too: https://developer.rocket.chat/reference/api/rest-api/endpoints/messaging/im-endpoints/members
if I need to create. separated issue please let me know

**Comment by zeitan** [comment]
Hi @Teak-Rosewood , we had a meeting the last Tuesday with some rocket.chat sales people and a sales engineer recommend us to use
https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/groups-endpoints/get-group-members to get counters (obviously moving from IM/DM create to groups.create).
This works ([group creation](https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/groups-endpoints/create-group)) but when I try to retrieve the counters usig the roomId  or the roomName those could not be found (400 bad request)

My use case is exactly this same: https://forums.rocket.chat/t/how-can-i-view-members-of-a-private-group/5475/2
is this scenario similar issue you described for im/counters??
do I need to wait for some udate form your side about that?

**Comment by zeitan** [comment]
Follow the issue in your repo looks like this is an expected behavior fro groups.members
https://github.com/RocketChat/Rocket.Chat/issues/19075#issuecomment-937992473
How the comment is old, is this still the behavior?

**Comment by Teak-Rosewood** [comment]
i have narrowed down the issue to this part of the im.ts file, which isn't granting the admin to view rooms created even with permissions. still trying to look into the details of the same 
![Screenshot from 2024-01-11 19-45-30](https://github.com/RocketChat/Rocket.Chat/assets/88363398/ae99b87d-f8cd-4299-8bba-ca3816e2b78a)
the code here maps to the canAccessRoom.ts which imports authorization from the rocket.chat/core-services package. since this seems to be at the server it is causing a bunch of APIs and client to behave abnormally. 

@KevLehman could you recommend some steps to take

**Comment by zeitan** [comment]
@Teak-Rosewood  could an admin see the members of a private group althught the amdin doesn't belongs to the private group?
I mentioned here the use case https://github.com/RocketChat/Rocket.Chat/issues/31390#issuecomment-1887677454

**Comment by Teak-Rosewood** [comment]
if im not wrong, an admin can access the counter and members of private groups even though the admin doesn't belong to the group with the right permissions. when tested the same on my environment with 1 admin and 2 users i noticed mainly two issues:

**Comment by zeitan** [comment]
@Teak-Rosewood 

> `an admin can access the counter and members of private groups even though the admin doesn't belong to the group with the right permissions`

I found this old comment where this behavior is not possible: 
https://github.com/RocketChat/Rocket.Chat/issues/19075#issuecomment-937992473
is still part of the RC current versions?

**Comment by Teak-Rosewood** [comment]
the end point here https://developer.rocket.chat/reference/api/rest-api/endpoints/messaging/im-endpoints/create has a excludeSelf option which returns the members added along with the room id, which should ideally be used to view a counter, I am looking into the issue currently but it might take a bit of time to fix as the issue seems to be quite low level and might affect a bunch of APIs

**Comment by zeitan** [comment]
@Teak-Rosewood 
for example I tried to use this endpoint https://developer.rocket.chat/reference/api/rest-api/endpoints/rooms/groups-endpoints/get-group-members using thizs same behavior: https://forums.rocket.chat/t/how-can-i-view-members-of-a-private-group/5475/2
and I could not get the members for the roomId
````
{
    "success": false,
    "error": "The required \"roomId\" or \"roomName\" param provided does not match any group [error-room-not-found]",
    "errorType": "error-room-not-found"
}
````
Because the calling user doesn't belong to he private group.

Searching in your issues I ound this comment https://github.com/RocketChat/Rocket.Chat/issues/19075#issuecomment-937992473
where is mentioned this is an expected behavior.
