### ISSUE TITLE
Disable uploaded image resampling

### ISSUE THREAD

**Issue by stevenhfotofix** [RocketChat/Rocket.Chat#3140]
Your Rocket.Chat version: 0.29.0

When sending JPEG images over Rocket.Chat, it seems that the file is being resampled and downsized by the time it reaches the other user.  When dealing with photography, this is an extremely undesirable outcome - requiring us to zip a file before sending it to the other user.  

Is there a way to disable image downsizing and keeping them untouched by an image software when the other user downloads them?

An example JPEG started out at 1,309,444 bytes, and was downloaded by the other user at 277,826 bytes - losing a lot of data long that trip.  Attached is an image comparison showing the areas where the image was significantly changed, and why we don't want the chat system to change the files along the way.

A PNG was also transferred, starting off at 3,036,528 bytes, and ending up 3,063,159 bytes.  So there is something being done with PNG files as well, but it does not lose data (though it is still something we don't desire to happen - we want a file sent to another user to remain as untouched as possible)

![planetexpressship 1920x1080](https://cloud.githubusercontent.com/assets/821782/15047271/6a1e7b2e-12a1-11e6-8c88-a96b0b7b2fb3.jpg)

![planetexpressship 1920x1080-transferred](https://cloud.githubusercontent.com/assets/821782/15047272/6a1e9e42-12a1-11e6-9242-0b73eaa15933.jpg)

![image](https://cloud.githubusercontent.com/assets/821782/15047277/6d4124aa-12a1-11e6-92c1-624b5cda6cb4.png)

**Comment by marceloschmidt** [comment]
I think admins should have the option of enabling/disabling downsampling for the sake of their disk space, but I agree this should be an option, especially for the photography-concerned communities.

**Comment by SeanPackham** [comment]
@marceloschmidt is this still relevant now that we have removed imagemagik?
