### ISSUE TITLE
Update files notification turns UI into unusable plain text

### ISSUE THREAD

**Issue by anonymouse64** [RocketChat/Rocket.Chat#3142]
Android Client version: 2.3.1
Server version : 0.28.0 

After installing a fresh version of the android app, then logging into my Rocket.Chat server, I get the following notification:
![notification](https://cloud.githubusercontent.com/assets/6006573/15051384/efd73974-12bd-11e6-9607-99c4df98b593.png)

I click update and now the messages window looks like the following:

![after update](https://cloud.githubusercontent.com/assets/6006573/15052823/2bc31f8c-12c5-11e6-8661-7c5cdb97a3d4.png)

If I clear the app data for RocketChat (not uninstalling the app) and log back in this goes away.

I am using Android 6.0.1, I can post more details if requested.

This seems to be very relevant to : https://github.com/RocketChat/Rocket.Chat/issues/2650 

Thanks,
Ian

**Comment by MartinSchoeler** [comment]
Hey @anonymouse64 , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
