### ISSUE TITLE
jitsi meet conference call integration with rocket.chat

### ISSUE THREAD

**Issue by MuhammadMalook** [RocketChat/Rocket.Chat#31420]
Hello!.
I'm integrating rocket.chat as an iframe in my next app. I have been using latest pro trail version of rocket.chat.
I have been trying to configure jitsi conference call with rocket.chat.
But it's not working even after enabled.
Some times getting error in console as : no-videoconf-provider-app
Some times it asks for configuration of conference provider while making a call.

**Comment by florisvangeel** [comment]
you probably didn't setup your jitsi [properly](https://meetrix.io/blog/webrtc/jitsi/how-to-setup-jitsi-meet%E2%80%93jvb-on-ubuntu-22-04.html) if it works with https://meet.jit.si you can easy confirm.

This issue can probably be closed
