### ISSUE TITLE
Require password change has no effect on the Android app

### ISSUE THREAD

**Issue by david-uhlig** [RocketChat/Rocket.Chat#31421]
### Description:

After creating a new user with the option "Set random password and send by email" enabled, the user can log in directly through the Android app without having to change their random password. The password change requirement is only triggered once they use the web interface. On web, it is triggered regardless if the user changed their password on the Android app themselves.

### Steps to reproduce:

1. Go to /admin/users/new
2. Create a new user with the option "Set random password and send by email" enabled
3. Receive the password changed e-mail.
4. Using the Android app, log in with the newly created username and random password. You will be able to log in without changing the password.
5. Change your password in the Android app regardless.
6. Using a web browser, log in with the same username and your changed password.

### Expected behavior:

The newly created user should have to change their password when first logging in with the Android app.

### Actual behavior:

The user is not required to change their password when logging in with the Android app.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.2
- Operating System: Ubuntu 22.04 LTS
- Deployment Method: Docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Firefox 120.0.1
- Operating System: Ubuntu 23.10
- Android App Version: 4.44.2.54511

### Additional context

I wasn't sure whether to report this here or to the ReactNative repository. If necessary I can move the bug report over there.

**Comment by zahidhussain998** [comment]
plase assgin me

**Comment by david-uhlig** [comment]
Fixed through RocketChat/Rocket.Chat.ReactNative#5722
