### ISSUE TITLE
Blue sidebar flickers and renders when you move your mouse (chrome)

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3143]
![20160505-162456-20160505-162408-rocket chat jpg - paint net 4 0 9](https://cloud.githubusercontent.com/assets/10524529/15056121/221b995a-12de-11e6-936f-0ded9e89ba35.jpg)
Rocket.Chat version: 1.2.0
Chrome version: 50.0.2661.94 m 
Windows 7 Professional Service Pack 1 64 bit

Issue still happens after clearing cache.

The rendering of the left blue bar (Channels, Direct Messages, Private Groups) has some weird rendering going on in Chrome. Every time you move your mouse to hover a new name or new channel it re-renders the whole thing and shifts by 1/2 pixel or so. It looks blurry. You can especially see it if one of your Direct Message contact is set as Busy and has a red '@' sign. The red '@' sign will change in color when the 1/2 pixel rendering issue occurs. 

In the attachment: the left is the rendering issue sidebar, the right is the "normal" idle sidebar.

**Comment by Molle500** [comment]
i made a issue about this as well. #2998

**Comment by marceloschmidt** [comment]
Do you see the flickering here? I'm on Chrome v50.0.2661.94, Mac OS X 10.11.

![not_flickering](https://cloud.githubusercontent.com/assets/1986378/15076839/feb8bd36-1381-11e6-89f7-2ad86703478a.gif)

I don't see any flickering.

**Comment by nmummau** [comment]
I don't see any flickering with your gif. See my attached video (sorry for
poor quality)

I'm using Chrome: 50.0.2661.94 m
Windows 7 Professional Service Pack 1 64-bit


*Neal Mummau*
Tel: (717) 368-3096
Email: nealmummau@gmail.com

**Comment by nmummau** [comment]
I don't see any flickering in your gif, but it's still happening for me. Using Windows 7 Professional. May be different than your Mac version of Chrome.

**Comment by nmummau** [comment]
I don't see any flickering in your gif, but it's still happening for me. Using Windows 7 Professional. May be different than your Mac version of Chrome.

**Comment by cjanietz** [comment]
I can confirm the issue for Windows 7, not for Windows 10, not sure what it is causing though, Definitely more of a Chrome issue.

**Comment by poxin13** [comment]
Yup, I notice this issue too on Server 2012 R2. Chrome Version 50.0.2661.94

**Comment by Molle500** [comment]
Chrome: 50.0.2661.94
Windows 10

Always flickering :/

**Comment by poxin13** [comment]
![flicker](https://cloud.githubusercontent.com/assets/10375741/15293183/c868c9d0-1b54-11e6-8738-96d7b6d3bd1b.gif)

Here's a gif of what I see happening.

**Comment by Molle500** [comment]
Here is a gif how it looks for me. Windows 10 chrome. I made the background dark becouse it's easier to see the flicker.
![1234](https://cloud.githubusercontent.com/assets/17712562/15298950/68de82d6-1ba2-11e6-8dcd-34323a2c477b.gif)

**Comment by Molle500** [comment]
Friends! i've found what is causing this problem!

`.side-nav ul .opt {
-webkit-transition:opacity 0.12s ease;
transition: opacity 0.12s ease;
}`

It's those transitions on the leave/hide room that cause the flickering.... 

Is it possible to fix it? (without removing the transiting since it's nice).

**Comment by MartinSchoeler** [comment]
@Molle500 Does this still happens on the latest release?

**Comment by nmummau** [comment]
I can confirm that it is no longer an issue for me. My original complain was on a Windows 7 machine, however I'm now using Windows 10 and Chrome Version 58.0.3029.110 (64-bit).
