### ISSUE TITLE
Ummm... Slenderman?

### ISSUE THREAD

**Issue by MattFloyd** [RocketChat/Rocket.Chat#3144]
Your Rocket.Chat version: 29

Issue: Under certain circumstances, `&` will turn into Slenderman

![image](https://cloud.githubusercontent.com/assets/9384928/15054059/a17a8a4a-12d3-11e6-9977-349d154000b2.png)

![image](https://cloud.githubusercontent.com/assets/9384928/15054073/aee5f7be-12d3-11e6-997a-9582d1844658.png)

![image](https://cloud.githubusercontent.com/assets/9384928/15054102/d70d74ba-12d3-11e6-9ad0-e884c1358ea2.png)

This was under Chrome 50.0.2661.94 with no Slenderman extensions
Happens in Internet Explorer as well
Happens in the desktop app

**Comment by Phen-Ro** [comment]
![image](https://cloud.githubusercontent.com/assets/10386623/15054376/164c4696-12d5-11e6-8628-431296129215.png)
Confirmed

**Comment by marceloschmidt** [comment]
What's your app language?

**Comment by Phen-Ro** [comment]
English.  I'm running Windows 7, and it's all English, too.   Nothing on my computer is configured for anything other than English.

**Comment by marceloschmidt** [comment]
OK! /me creating a Win 7 VM :)

**Comment by Phen-Ro** [comment]
I did some more research and it appears to be an issue with the version of the font I have installed: https://github.com/adobe-fonts/source-code-pro/issues/11

This is not a RocketChat problem.

**Comment by marceloschmidt** [comment]
@MattFloyd do you also have this font installed?

**Comment by MattFloyd** [comment]
Confirmed -- Slenderman lives in the font, not RocketChat.
