### ISSUE TITLE
Workspace doesn't stay in the Community Plan

### ISSUE THREAD

**Issue by julian-** [RocketChat/Rocket.Chat#31449]
## Description:

Hello,

I have upgraded to 6.5.2 because I have some issues with a meteor script in the 6.4.x versions.
For the meteor issue, I will probably need to create a separate ticket, because it seems it is still present in 6.5.

Whatsoever, this ticket is about changing from the default "start plan" to the desired "community plan".
I mean, why there is no button like: "Select your plan" with the option "Community Plan" in it?

I always get set back to the starter plan or need to complete the workspace registration again.
Endless loop.

I have to remove the registration token under "Premium", then reload the license under "Subscriptions". to see the application changed to the community plan. but when I restart my docker container, the plan changes back to starter.
So, I have removed (as noticed under premium) the cloud registration entry for this workspace and reset the premium section again. This leads to a state, where I get forced to fulfill the workspace registration again which of course enables the start plan for this workspace. 🤯 🔁 

_Edited:_

The Offline-Registration would be a valid solution for me, but this is not working as documented (https://docs.rocket.chat/setup-and-configure/rocket.chat-air-gapped-deployment/offline-workspace-registration).
The button "Register Offline" is missing during the registration process and all variants of possible provided codes are "invalid".

## Steps to reproduce:

Set up the docker instance for version 6.5.2 from scratch.
See starter plan is enabled, go to "Premium" reset the section, and save. 
Then you can reload the page and see in "Workspace Settings" that your "Starter plan" has been changed to the "Community plan".

As noticed under Premium - go into the cloud and remove the appropriate workspace registration.

## Expected behavior:

The community plan stays activated from now until forever for this setup. 
Even after the restart.

## Actual behavior:

I get forced to fulfill the cloud registration and the workspace will operate with the starter plan again. 

_b) When you skip deleting the cloud registration entry, the workspace will be set back to the "starter plan" after the restart or after using the "sync license" action under "Subscription"_

___

Server Setup Information:
Version of Rocket.Chat Server: 6.5.2
Operating System: Redhat
Deployment Method: git
Number of Running Instances: 1
DB Replicaset Oplog: active
NodeJS Version: v14.21.3
MongoDB Version: 6.0.2 / wiredTiger (oplog activated)
Client Setup Information
Desktop App or Browser Version: -
Operating System: -

**Comment by soundstorm** [comment]
I had the same issue, contacted support. They suggested just to cancel the starter plan subscription. So you'll be back to regular features you had before. Hopefully the features don't get circumcised further in the future.

**Comment by vmarinogg** [comment]
Hey, @julian- 

Not sure if you already solved the issue, but what @soundstorm mentioned above is the best path to follow. 

Just to be aware, every time you restart your docker, the workspace will connect to RC Cloud and it will identify that your WS is without any plan because of the way you removed the token. On the Cloud side, we didn't receive a signal to "cancel" your Starter Plan this way, that's why it keeps generating a new token and providing the plan again to your workspace.

So, just go to your subscription section in the admin panel and click on the **Cancel** button at the bottom.

Hope it helps. :)

**Comment by julian-** [comment]
Hi @vmarinogg & @soundstorm,

thanks a lot for your replies. 

I will try it as soon as possible and will let you know. I will reopen this Issue in case I still have some problems with the related topic. :)
