### ISSUE TITLE
connection problem with rocket.chat

### ISSUE THREAD

**Issue by TriDuPapier** [RocketChat/Rocket.Chat#31448]
Good morning,
I can no longer connect to any version of rocket.chat on desktop 3.9.11 and on mobile.
Sincerely

I put the screenshot of the error

![prob-rc](https://github.com/RocketChat/Rocket.Chat/assets/156651967/b5418f2a-cee1-4241-9449-8af4e53e3e55)

**Comment by Mubashir2611** [comment]
can you describe more on this issue. and post a video on it.

**Comment by riyanrathore26** [comment]
Hi @TriDuPapier 
this issue mostly occur when you change code 
see carefully your code and make it like before

**Comment by MartinSchoeler** [comment]
Github is for bugs in Rocket.Chat not general support.

This looks like a setup problem.

Please ask for help in:

https://open.rocket.chat/ #support

If there is actually a bug in Rocket we can re-open.
