### ISSUE TITLE
Yarn Install Error: Peer Dependencies Issue

### ISSUE THREAD

**Issue by varshith257** [RocketChat/Rocket.Chat#31443]
### Description:
Encountering an error while running yarn install for the Rocket.Chat project. The error suggests that some peer dependencies are incorrectly met. Here are the details of the issue:

### Steps to reproduce:
1) Clone the Rocket.Chat repository.
2) Run yarn install.

### Expected behavior:
The dependencies should be installed successfully without any errors.

### Actual behavior:
The installation is failing with the mentioned error messages.

 YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 410ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 11s 306ms
➤ YN0000: ┌ Link step
➤ YN0007: │ isolated-vm@npm:4.4.2 must be built because it never has been before or the last one failed
➤ YN0007: │ event-loop-stats@npm:1.4.1 must be built because it never has been before or the last one failed
➤ YN0009: │ isolated-vm@npm:4.4.2 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\91970\AppData\Local\Temp\xfs-4c4998a9\build.log)
➤ YN0009: │ event-loop-stats@npm:1.4.1 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\91970\AppData\Local\Temp\xfs-7c915bfb\build.log)
➤ YN0000: └ Completed in 13s 337ms
➤ YN0000: Failed with errors in 26s 396ms

### Additional context
Fix installing of peer dependencies

### Relevant logs:
 YN0000: ┌ Resolution step
➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [13f20] doesn't provide react-dom (pde481), requested by @design-systems/utils➤ YN0002: │ @devtools-ds/themes@npm:1.2.0 [4e25a] doesn't provide react-dom (pd4536), requested by @design-systems/utils➤ YN0002: │ @nivo/annotations@npm:0.84.0 [66b78] doesn't provide react-dom (pa1655), requested by @react-spring/web
➤ YN0002: │ @nivo/arcs@npm:0.84.0 [4a77f] doesn't provide prop-types (p6e185), requested by @nivo/core
➤ YN0002: │ @nivo/arcs@npm:0.84.0 [4a77f] doesn't provide react-dom (pa539b), requested by @react-spring/web
➤ YN0002: │ @nivo/axes@npm:0.84.0 [66b78] doesn't provide react-dom (pf83f6), requested by @react-spring/web
➤ YN0002: │ @nivo/bar@npm:0.84.0 [965c2] doesn't provide prop-types (p48418), requested by @nivo/core
➤ YN0002: │ @nivo/bar@npm:0.84.0 [965c2] doesn't provide react-dom (p2cc74), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.84.0 [8b69b] doesn't provide react-dom (p9227f), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.84.0 [965c2] doesn't provide react-dom (pfda81), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.84.0 [b1026] doesn't provide react-dom (p45252), requested by @react-spring/web
➤ YN0002: │ @nivo/core@npm:0.84.0 [fde56] doesn't provide react-dom (p4f3bb), requested by @react-spring/web
➤ YN0002: │ @nivo/heatmap@npm:0.84.0 [965c2] doesn't provide prop-types (p29789), requested by @nivo/core
➤ YN0002: │ @nivo/heatmap@npm:0.84.0 [965c2] doesn't provide react-dom (pe755e), requested by @react-spring/web
➤ YN0002: │ @nivo/line@npm:0.84.0 [965c2] doesn't provide react-dom (p344f1), requested by @react-spring/web
➤ YN0002: │ @nivo/pie@npm:0.84.0 [965c2] doesn't provide prop-types (pce6df), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.84.0 doesn't provide prop-types (p3a776), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.84.0 doesn't provide react (p26170), requested by @react-spring/web
➤ YN0002: │ @nivo/tooltip@npm:0.84.0 doesn't provide react (p4765c), requested by @nivo/core
➤ YN0002: │ @nivo/tooltip@npm:0.84.0 doesn't provide react-dom (pf77a2), requested by @react-spring/web
➤ YN0002: │ @nivo/voronoi@npm:0.84.0 [fde56] doesn't provide prop-types (p1642b), requested by @nivo/core
➤ YN0002: │ @react-aria/dialog@npm:3.5.1 [53dc5] doesn't provide react-dom (p15fff), requested by @react-aria/overlays
➤ YN0002: │ @react-aria/dialog@npm:3.5.1 [9f731] doesn't provide react-dom (p6398a), requested by @react-aria/overlays
➤ YN0002: │ @react-aria/gridlist@npm:3.3.0 [53dc5] doesn't provide react-dom (p800df), requested by @react-aria/grid
➤ YN0002: │ @react-aria/gridlist@npm:3.3.0 [99643] doesn't provide react-dom (p5d828), requested by @react-aria/grid
➤ YN0002: │ @react-aria/gridlist@npm:3.3.0 [9f731] doesn't provide react-dom (p84401), requested by @react-aria/grid
➤ YN0060: │ @rocket.chat/css-in-js@npm:0.31.25 provides stylis (pc4346) with version 4.1.3, which doesn't satisfy what @rocket.chat/stylis-logical-props-middleware requests
➤ YN0002: │ @rocket.chat/ddp-streamer@workspace:ee/apps/ddp-streamer doesn't provide @rocket.chat/ddp-client (p190ef), requested by @rocket.chat/ui-contexts......................................

**Comment by Piyush-onGIT** [comment]
I also faced the same issue on my Windows system, but it worked when I did the same in my WSL. You can also try to switch to the WSL system,

**Comment by Sipaiki** [comment]
did you fixed it ?

**Comment by varshith257** [comment]
No, I didn't tried it again. It's been a long time I had this issue

**Comment by nguyen1998pr** [comment]
In Ubuntu, I run **sudo apt-get install build-essential** and error disappeared

**Comment by heet434** [comment]
Hi @varshith257 , I had the same issue, which was due to a missing python import in one of the node modules. I was successfully able to fix it in MacOS by installing setuptools as @Gustrb correctly stated. 
You could run ``` brew install python-setuptools``` if you use homebrew.

**Comment by 11WALTER11** [comment]
> Hi @varshith257 , I had the same issue, which was due to a missing python import in one of the node modules. I was successfully able to fix it in MacOS by installing setuptools as @Gustrb correctly stated. You could run ` brew install python-setuptools` if you use homebrew.

Hi @heet434,

I tried installing brew `install python-setuptools`, but it didn’t work. Would you mind explaining how to get rid of this error, as just installing it didn’t fix it?

**Comment by heet434** [comment]
@11WALTER11 could you share more details about exactly what error you're facing and how you got there?
