### ISSUE TITLE
short user name

### ISSUE THREAD

**Issue by haifengl** [RocketChat/Rocket.Chat#3145]
Your Rocket.Chat version: latest

We can create a user whose name is only one character. We are able to login with that user and send messages to others. However, other users cannot find this user when create a new direct message.

**Comment by marceloschmidt** [comment]
Yes, I have seen this happen as well. It's not exclusively for short names, but any username that is contained in too many other usernames may experience this. For example, in the demo, if you're looking for the `as` user:
![image](https://cloud.githubusercontent.com/assets/1986378/15078144/2ee2eb0c-1388-11e6-95b3-6af55e6bc6b6.png)

**Comment by MartinSchoeler** [comment]
This is still happening on the latest version
