### ISSUE TITLE
Java rest client doesn't work

### ISSUE THREAD

**Issue by haifengl** [RocketChat/Rocket.Chat#3146]
Your Rocket.Chat version: latest

When sending a message using the Java client (https://github.com/baloise/rocket-chat-rest-client), the following exception thrown:

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!DOCTYPE html>
<html>
<head>
<base href="/">

  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/c15180ad5fb26d413c2288e92e210abb21f0c180.css?meteor_css_resource=true">  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/theme.css?8d81cca034ddc6fb0757dd506d2bf0e2b8c7ad33">

<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.2.1%22%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fchat.adp.ai%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22accountsConfigCalled%22%3Atrue%2C%22autoupdateVersion%22%3A%22d1e6d236d362037d427d08654dc1406f90c39127%22%2C%22autoupdateVersionRefreshable%22%3A%22f321a8ffd2f78c5b2c01a84ce48d74750bee65bb%22%2C%22autoupdateVersionCordova%22%3A%228359a273589a90f39a16cdb64a00bb022b27cecc%22%7D"));</script>

  <script type="text/javascript" src="/d60d4f39bf3e4f8c15004ea56d0bb2d26a0b27ab.js?meteor_js_resource=true"></script>

<title>Rocket.Chat</title>
	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="expires" content="-1" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="fragment" content="!" />
	<meta name="distribution" content="global" />
	<meta name="rating" content="general" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
	<meta name="msapplication-TileColor" content="#04436a">
	<meta name="msapplication-TileImage" content="images/logo/mstile-144x144.png?v=3">
	<meta name="msapplication-config" content="images/logo/browserconfig.xml?v=3">
	<meta name="theme-color" content="#04436a">
	<link rel="manifest" href="images/logo/manifest.json?v=3">
	<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/nocfbnnmjnndkbipkabodnheejiegccf">
	<link rel="icon" sizes="any" type="image/svg+xml" href="assets/favicon.svg?v=3">
	<link rel="icon" sizes="256x256" type="image/png" href="assets/favicon_256.png?v=3">
	<link rel="icon" sizes="192x192" type="image/png" href="assets/favicon_192.png?v=3">
	<link rel="icon" sizes="128x128" type="image/png" href="assets/favicon_128.png?v=3">
	<link rel="icon" sizes="96x96" type="image/png" href="assets/favicon_96.png?v=3">
	<link rel="icon" sizes="64x64" type="image/png" href="assets/favicon_64.png?v=3">
	
	<link rel="shortcut icon" sizes="16x16 32x32 48x48" type="image/x-icon" href="assets/favicon_ico.ico?v=3" />
	<link rel="apple-touch-icon" sizes="57x57" href="images/logo/apple-touch-icon-57x57.png?v=3">
	<link rel="apple-touch-icon" sizes="60x60" href="images/logo/apple-touch-icon-60x60.png?v=3">
	<link rel="apple-touch-icon" sizes="72x72" href="images/logo/apple-touch-icon-72x72.png?v=3">
	<link rel="apple-touch-icon" sizes="76x76" href="images/logo/apple-touch-icon-76x76.png?v=3">
	<link rel="apple-touch-icon" sizes="114x114" href="images/logo/apple-touch-icon-114x114.png?v=3">
	<link rel="apple-touch-icon" sizes="120x120" href="images/logo/apple-touch-icon-120x120.png?v=3">
	<link rel="apple-touch-icon" sizes="144x144" href="images/logo/apple-touch-icon-144x144.png?v=3">
	<link rel="apple-touch-icon" sizes="152x152" href="images/logo/apple-touch-icon-152x152.png?v=3">
	<link rel="apple-touch-icon" sizes="180x180" href="images/logo/apple-touch-icon-180x180.png?v=3">
</head>
<body>

	<div id="initial-page-loading" class="page-loading">
		<div class="spinner">
			<div class="rect1"></div>
			<div class="rect2"></div>
			<div class="rect3"></div>
			<div class="rect4"></div>
			<div class="rect5"></div>
		</div>
	</div>

</body>
</html>
; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1823)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3828)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3773)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at com.github.baloise.rocketchatrestclient.RocketChatClient.authenticatedGet(RocketChatClient.java:62)
	at com.github.baloise.rocketchatrestclient.RocketChatClient.getPublicRooms(RocketChatClient.java:41)
	at com.github.baloise.rocketchatrestclient.RocketChatClient.getRoom(RocketChatClient.java:149)
	at com.github.baloise.rocketchatrestclient.RocketChatClient.send(RocketChatClient.java:137)

**Comment by Sing-Li** [comment]
Please post the issue at the https://github.com/baloise/rocket-chat-rest-client  repository.  We have no access to that code.  Thanks.
