### ISSUE TITLE
Wrong time format (hours)

### ISSUE THREAD

**Issue by mirabilos** [RocketChat/Rocket.Chat#31483]
### Description:

version: 4.45.0.55377
device: SM-G398FN

It uses AM/PM like people across the pond despite the system being set up for 24-hour clock.

### Steps to reproduce:

1. See the timestamp on a post

### Expected behavior:

24-hour format like almost everywhere in the world

### Actual behavior:

American format

### Server Setup Information:

- Version of Rocket.Chat Server: I have no idea
- Operating System: I have no idea
- Deployment Method: I have no idea
- Number of Running Instances: I have no idea
- DB Replicaset Oplog: I have no idea
- NodeJS Version: I have no idea
- MongoDB Version:I have no idea

### Client Setup Information

- Desktop App or Browser Version: not applicable
- Operating System: Android

### Additional context

n/a

### Relevant logs:

not applicable

**Comment by mirabilos** [comment]
Hardik Bhatia dixit:

>1. Click on your profile photo (top left).

Top left is a three horizontal lines icon. If I click that, it
does show my profile picture, but if I click that it just goes
back to the channel view.

>2. Go to 'Accessibility and Appearance' under the 'Account' label.

There’s no Account label. There *is* a Settings label, but that
has neither Accessibility nor Appearance.

There is also a Display label, but that doesn’t have anything
like that either.

>3. Click on 'Adjustable Layout'
>
>You'll see the option to toggle between the two modes there :)

Nope :(

**Comment by mirabilos** [comment]
Hardik Bhatia dixit:

>@mirabilos some screenshots from your end would help since you didn't
>@provide any info about your hardware in your original post. Rest

I did, it’s an SM-G398FN (Samsung).

In case it matters, Rocket.Chat is installed from Google Playstore
since the F-Droid version was unavailable for a time.

bye,
//mirabilos

**Comment by hardikbhatia777** [comment]
Oh, I checked the bottom portion and only saw android. I cross-checked and yes, it appears the accessibility menu isn't there in the mobile app, would you mind posting this issue in the Rocket.ChatReactNative repository as well? That's the mobile app repository. Thanks for reporting!

**Comment by mirabilos** [comment]
Hardik Bhatia dixit:

>Oh, I checked the bottom portion and only saw android. I cross-checked
>and yes, it appears the accessibility menu isn't there in the mobile
>app, would you mind posting this issue in the Rocket.ChatReactNative
>repository as well? That's the mobile app repository.

Huh, okay: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5501

I came here because this is where the autoresponder to the in-äpp
problem reporting thing sent me.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this one since it was already reported on the mobile app repository!

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
