### ISSUE TITLE
Edit message bug

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#3149]
When you edit a message and press on cancel our save changes the page reloads and you get thrown back to the front back.

NOTE* only happends when you click on them with the mouse. It works as it should when you simply press esc or enter on your keyboard.
![example](https://cloud.githubusercontent.com/assets/17712562/15058570/4fe9ef78-131d-11e6-9334-d55d7d01fa8d.PNG)

//Molle

**Comment by PavelVanecek** [comment]
I just tried and it works fine for me. What version of Rocket.Chat do you have installed? What browser and OS are you using?

**Comment by Molle500** [comment]
Yeah this one is fixed already :) closing!
