### ISSUE TITLE
getUserRoles returns a list of users and roles to low priv user

### ISSUE THREAD

**Issue by aphick** [RocketChat/Rocket.Chat#31490]
### Description:  

Queries to `/api/v1/method.call/getUserRoles`  with the POST data:
```
'{"message":"{\"msg\":\"method\",\"id\":\"\",\"method\":\"getUserRoles\",\"params\":[]}"}'
```
Returns a list of seemingly random usernames and IDs. The same list of users is returned regardless of the user querying or the query parameters.

### Steps to reproduce:

`curl 'http://127.0.0.1:3000/api/v1/method.call/getUserRoles' --compressed -X POST -H 'X-User-Id: <USER_ID>' -H 'X-Auth-Token: <AUTH_TOKEN>' -H 'Content-Type: application/json' --data-raw '{"message":"{\"msg\":\"method\",\"id\":\"\",\"method\":\"getUserRoles\",\"params\":[]}"}'
`

### Expected behavior:

Unsure what the purpose of this endpoint is, but access to this method should be restricted to admins, or filtered based on the which other users the requesting user has contacted.

### Actual behavior:

A random list of other users, their roles, and userids is returned.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.9
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.12

### Client Setup Information

- Desktop App or Browser Version: Curl

**Comment by saurabhbakolia** [comment]
Hey, I would like to work on it, if now else is working on?

**Comment by rique223** [comment]
Hey aphick, first of all, thanks for your contribution. If you have a further look at this method code you'll see that this endpoint only returns roles that are supposed to be public so there is no problem in showing them to low privilege users.

**Comment by aphick** [comment]
Hey @rique223, the problem I raise in my issue is that queries to this endpoint are returning user IDs and names of clients that we do not want visible to everyone. To me, being able to get the username and ID of another user you haven't interacted with is an information disclosure vulnerability.

If this is indeed working as intended, could you please inform me of a way to make certain roles not public?

**Comment by rique223** [comment]
> Hey @rique223, the problem I raise in my issue is that queries to this endpoint are returning user IDs and names of clients that we do not want visible to everyone. To me, being able to get the username and ID of another user you haven't interacted with is an information disclosure vulnerability.
> 
> If this is indeed working as intended, could you please inform me of a way to make certain roles not public?
If you delete the description of the given roles they will stop being returned by this endpoint. You can also change their scope from global to rooms.
