### ISSUE TITLE
cant login with luce research

### ISSUE THREAD

**Issue by tashalee991** [RocketChat/Rocket.Chat#31508]
i used chat.luceresearch.com to connect into the app and it says it was outdated. how do i connect with the app with luce research company?

**Comment by DrizzyOVO** [comment]
hi @tashalee991, can you explain the issue in detail?

**Comment by abhishekwaghmare01** [comment]
Hiii @tashalee991 , can you please explain the issue in detail?

**Comment by MartinSchoeler** [comment]
Hello @tashalee991 it appears that lucresearch is a company/community that uses a Rocket.Chat workspace, so you will probably have to contact their company/community directly and check what you need to login with them

If you are on desktop you can try to access the URL directly via browser, that could help as well. 

Closing this, thanks!

**Comment by tashalee991** [comment]
Thanks, I'll check it out.
