### ISSUE TITLE
Integration with Google Drive, Dropbox

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3151]
This could be helpful if we want to save documents and files on clouds vs storing them on your VPS, saving on size.  - i think :) 
ability to integrate dropbox or any cloud based storage to a room.

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by mdramos** [comment]
+1

**Comment by Rohlik** [comment]
Slack already have this integration (with Google drive).

**Comment by hodyroff** [comment]
Best would be ownCloud/WebDAV support for a start.

**Comment by engelgabriel** [comment]
https://slack.com/apps/A0F7YS32P-google-drive

**Comment by engelgabriel** [comment]
https://uppy.io/

**Comment by orangecoloured** [comment]
Integration with ownCloud would be really cool.

**Comment by cubefoo** [comment]
google and dropbox?
we went for rocket.chat to regain control over our data and not give it away to these companies
so please support other self hosted open source apps first (like nextcloud / owncloud)

**Comment by jszaszvari** [comment]
@cubefoo it's not like it will be mandatory. You don't have to switch it on. 

As great as nextcloud support would be, it will only cater for a very small section of users. 

I'm sure it will happen, but google drive and Dropbox are smarter first options. 

Your not giving anything away if you leave it switched off..

**Comment by cubefoo** [comment]
@jszaszvari // I get it that these services have a larger user base and therefore it's the logical first choice based on demand alone but I strongly disagree that it's the smarter choice ;)

but I have to admit, it seems most people are more concerned about saving a few bucks than protecting the ownership of their data.

**Comment by Escubaer** [comment]
Honestly, Open Source applications should fit together and work together. If I use Google why should I not use Slack? If I use ownCloud its obvious that I would be looking for a social collaboration tool to accompany it. Therefor commercial integrations first is a shame and will make sure that the Open Source solutions never win ...

**Comment by TheReal1604** [comment]
https://rocket.chat/docs/administrator-guides/file-upload/minio - is also a nice storage backend

**Comment by PeaceS** [comment]
+1 we really need this

**Comment by sampaiodiego** [comment]
This is being done by #10978

**Comment by hugocostadev** [comment]
Available through apps
