### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by iamrudra** [RocketChat/Rocket.Chat#3152]
Trying to install manually on Ubuntu 14.04 LTS - I get this error while installing the packages with 

`npm install`

>npm ERR! fibers@1.0.5 install: node ./build.js
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
>npm ERR! This is most likely a problem with the fibers package,
>npm ERR! not with npm itself.

**Comment by Sing-Li** [comment]
Please use Ubuntu 14.04 LTS - what platform (CPU and OS) are you on?

**Comment by iamrudra** [comment]
@Sing-Li - I apologize - I am using 14.04 - I mistyped it the first time.

**Comment by iamrudra** [comment]
@Sing-Li - I tried it on Ubuntu 14.04 as well as a blank Ubuntu workspace on Cloud 9. but I face the same error.

**Comment by iamrudra** [comment]
I opened an [issue with fibers package](https://github.com/laverdet/node-fibers/issues/287). According to the response I tried changing the `package.json` to 1.0.12 but then too npm tries to install 1.0.5. I wonder why....?

**Comment by Syirrus** [comment]
Try a "sudo npm install"

**Comment by zxweed** [comment]
The manual recommends the 0.10.40 version of node.js

**Comment by iamrudra** [comment]
@Syirrus - I tried that already but it does not help.

**Comment by iamrudra** [comment]
@zxweed - It says - 
>Meteor needs *at least* this version of node to work.

I'd like to believe that it will surely work with higher versions?

**Comment by zxweed** [comment]
In my experiments the some of higher versions of node.js have an errors with fibers module. But I read the post about succesfull installation of node.js version 5 also.

**Comment by laverdet** [comment]
@zxweed fibers works fine on all versions of node.

**Comment by geekgonecrazy** [comment]
If using newer version of node.js then supported by meteorjs or what we recommend.  you're using at your own risk.  We haven't done testing to guarantee anything will work

**Comment by zxweed** [comment]
@laverdet, I have tested all the major versions of node.js and only the 0.10.X installs normally. All other versions returns the error with default installation:
```
Error: `/root/Rocket.Chat/programs/server/node_modules/fibers/bin/linux-x64-v8-4.5/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/root/Rocket.Chat/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Rocket.Chat/programs/server/boot.js:1:75)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by laverdet** [comment]
@zxweed that error message is from fibers@1.0.5, which is 18 months old. The latest version is 1.0.13.

You still won't be able to run RocketChat on versions of node other than 0.10.x. See https://github.com/meteor/meteor/issues/5124 for more information.

**Comment by FibreFoX** [comment]
Would be nice to have fibers@1.0.13, the meteor-bug seems to be fixed: https://github.com/meteor/meteor/pull/7218

It would be very nice to have the documentation point to "known bugs/workarounds" like these.

**Comment by geekgonecrazy** [comment]
Note taken. 👍 We'll be updating to a newer version of meteor before too long, and you will be able to use a higher version of Node.js.

@iamrudra going to go ahead and close this issue.  Looks like you might have it resolved.  Feel free to re-open if not the case.
