### ISSUE TITLE
Can't start Mongo server

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#3154]
Your Rocket.Chat version: 22.0

I am using rocket chat more than a three months with out any problem.

the last day, i am not able to start rocket chat, the following error has occurred. 

![image](https://cloud.githubusercontent.com/assets/16605816/15066010/100a1a0c-1383-11e6-9eb9-ff9cfca53bd8.png)

Please help us to take backup of exiting instance & recover it?

**Comment by marceloschmidt** [comment]
That's weird, I have never seen this. Maybe a corrupt file system?

**Comment by geekgonecrazy** [comment]
If you're still having this issue please try running one of our compiled releases.
