### ISSUE TITLE
URL for the latest version is still 6.5.2.

### ISSUE THREAD

**Issue by ymch** [RocketChat/Rocket.Chat#31547]
This is not a bug in Rocket.Chat, but I have noticed it and would like to report it.

We are currently using Rocket.Chat 6.5.2.
Even though 6.5.3 has been released, both "Rocket.Cat" and the "Update Checker" are still on 6.5.2.
![Screenshot 2024-01-26 at 23-26-04](https://github.com/RocketChat/Rocket.Chat/assets/2923124/dc68c8d6-8684-4f30-b340-8cf1fef3d210) ![Screenshot 2024-01-26 at 23-28-35 Rocket Chat 三和システムサービス株式会社](https://github.com/RocketChat/Rocket.Chat/assets/2923124/204c7078-c639-4b5b-8ce5-3714f8948cc9)

To update Rocket.Chat, I downloaded a tar.gz.
curl -L https://releases.rocket.chat/latest/download -o rocket.chat.tar.gz

After updating, I checked the version and it was still 6.5.2.

The alias or symbolic link for the latest version on the distribution server has been directed to 6.5.2.
https://releases.rocket.chat/latest/download
    -> rocket.chat-6.5.2.tar.gz

For the time being, I downloaded it using the version-specified URL.
curl -L https://releases.rocket.chat/6.5.3/download -o rocket.chat.tar.gz

**Comment by lovekyleman** [comment]
https://releases.rocket.chat/6.5.3/download
You have to edit it to update RC to the latest version this time
