### ISSUE TITLE
User can't see room to which he was invited (view-c-room false)

### ISSUE THREAD

**Issue by prohde** [RocketChat/Rocket.Chat#3155]
My Rocket.Chat version: 0.29.0

I played around with the user permissions and found out that users who aren't allowed to see the public channels (don't have the permission view-c-room) can't see the channels they were invited to.
I think even if they shouldn't see the list of all the public channels they should be able to see those they were invited to.

**Comment by marceloschmidt** [comment]
I think we need to split this into two permissions: `view-c-list` and `join-c`, as it could be possible that we don't want a user to join *any* channels.

**Comment by gregrparker** [comment]
I'm new to this so please excuse my ignorance. I have created 3 private rooms. I have joined someone to one of those rooms but don't want him to be able to view the other rooms.  

My question is in 2 parts - I have now set user permissions as view c-room view d-room and view history. Will this allow him to view ALL private rooms, or just the one he has been added to?

If it allows him to view ALL private rooms, is there a way to stop that and only give him access to the one room he was added to?

**Comment by marceloschmidt** [comment]
@gregrparker only the private rooms he was invited to

**Comment by mdrobisch** [comment]
Are there any news here? I think a split of view-c-list and join-c would become very handy. Is this task suitable for a beginner like me. It would be  please to contribute to Rocket.Chat in this way. Where could i start?

**Comment by MartinSchoeler** [comment]
Will close this since today we have the `view-joined-room`
