### ISSUE TITLE
Remove unwanted tooltip from reaction emoji

### ISSUE THREAD

**Issue by praveen-p09** [RocketChat/Rocket.Chat#31562]
### Description:

An unwanted tooltip `true` appears on hovering over reaction emojis.

### Steps to reproduce:

1. Go to any channel
2. Hover over reaction emoji of any message 
3. A tooltip `true` appears over some emojis

### Expected behavior:

No such tooltip should appear.

### Actual behavior:

![Screenshot 2024-01-28 131637](https://github.com/RocketChat/Rocket.Chat/assets/128630671/2cc6df67-960c-49f9-970f-094ed41092ea)
![Screenshot 2024-01-28 130809](https://github.com/RocketChat/Rocket.Chat/assets/128630671/418f733c-8790-4c18-833d-3f1e0e4a23c0)
![Screenshot 2024-01-28 131526](https://github.com/RocketChat/Rocket.Chat/assets/128630671/82d2f4eb-f691-4e3e-819d-fbcdfb7fc1c0)

**Comment by praveen-p09** [comment]
Hello maintainers! Can I work on this issue?

**Comment by Devansht420** [comment]
this issue is happening.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and it was fixed here: #31570

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
