### ISSUE TITLE
Underlined bar is inconsistent on hover and there is no hover effect on Demo request button.

### ISSUE THREAD

**Issue by pankaj-2503** [RocketChat/Rocket.Chat#31575]
### Description:

On hover different  link the underline is too far it should have to be close for better Ui. It is present at https://www.rocket.chat/install.
### Steps to reproduce:

1. 
2. 
3. 

### Actual behavior:
![image](https://github.com/RocketChat/Rocket.Chat/assets/90036864/281850c9-638c-459d-ae8f-2b16eb05fbde)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue @hugocostadev

**Comment by AnshuPathak-88825** [comment]
all tabs has same line alignments

**Comment by pankaj-2503** [comment]
I think this is not an isssue for alignment it is built that way.I was just trying to propose a soln. where the underline should be closer to navlinks for better ui.
