### ISSUE TITLE
Attaching a LARGE file completely breaks the application

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3157]
Your Rocket.Chat version: 1.2.0

When I attempt to upload a 12,811 KB .LOG file, the app turns completely black (see screenshot).
I typically upload .LOG files and send them to our application developers for development troubleshooting unhandled exceptions, etc.
This happens when you drag and drop, or if you choose to manually attach the file.

It seems to be able to attach files <~10,000 KB, but anything larger it will explode in horror.

![20160506-124602-rocket chat](https://cloud.githubusercontent.com/assets/10524529/15079767/87b4e104-1388-11e6-8f6a-993d888268b8.jpg)

In Chrome, I think this is handled with this error message:
![image](https://cloud.githubusercontent.com/assets/10524529/15079976/b821c7de-1389-11e6-825d-283fb344651c.png)

**Comment by marceloschmidt** [comment]
Please update your app to version 1.3.1. This has been fixed.

**Comment by nmummau** [comment]
Confirmed. Thank you. Drag and Drop has been disabled entirely within the application. That sort of stinks :frowning: 

Now requires manually attaching the file... and if it's too large it will throw the "file is too large" message.
