### ISSUE TITLE
Has "Pro trial" but /api/v1/licenses.isEnterprise returns isEnterprise=true

### ISSUE THREAD

**Issue by demesg** [RocketChat/Rocket.Chat#31580]
Version 6.5.3 docker
Pro trial - Operating within plan limits

Rest API get 'http://localhost:3000/api/v1/licenses.isEnterprise'
response:
{"isEnterprise":true,"success":true}

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://developer.rocket.chat/v1/docs/contribute-through-bug-reporting) again for help on providing additional information.
