### ISSUE TITLE
Livechat: Show agent email cannot be disabled

### ISSUE THREAD

**Issue by iqqmuT** [RocketChat/Rocket.Chat#31586]
### Description:

**Show agent email** setting cannot be disabled.

### Steps to reproduce:

1. Open **Administration** > **Omnichannel** > **Livechat Appearance**
2. Disable **Show agent email**
3. Click **Save changes**
4. Reload the page

### Expected behavior:

**Show agent email** setting is disabled.

### Actual behavior:

**Show agent email** setting was not changed, it is still enabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.13 (Atlas)

### Client Setup Information

- Desktop App or Browser Version: Chrome 120.0.6099.224
- Operating System: Linux

### Additional context

Omnichannel title can be changed from the same form. No error logs.

### Screenshot
![2024-01-31_15-11](https://github.com/RocketChat/Rocket.Chat/assets/490260/1d0c2a19-46e0-4ecb-bf1d-9151e6301774)

**Comment by sumitkukrejas** [comment]
Tried recreating this issue, works fine on my end

**Comment by privnote42** [comment]
I have the same problem.
After a reload, these options are active again.

But only if I call up the Omnichannel directly, if I go to Settings and open Omnichannel, the options are deactivated.
But unfortunately the options don't seem to be active.
The agent's username and e-mail address are still visible in the chat for the visits

is there perhaps a workaround how i can overwrite this in the database?

**Comment by renatobecker** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/31528.
