### ISSUE TITLE
Jump to Date

### ISSUE THREAD

**Issue by cjanietz** [RocketChat/Rocket.Chat#3158]
Slack introduced a very valuable featur for message navigation: Jumping back to specific dates by calendar.
I find myself very often scrolling a lot, when looking for a specific date, would be a nice feature to have
![image](https://cloud.githubusercontent.com/assets/10359132/15082933/cc7cfea6-13ca-11e6-8ed2-3cda1b6f9baa.png)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by darkpal** [comment]
Very helpful feature when you need to find messages by date. Try to find a message you posted a year ago in current RocketChat version. This is a pain.

**Comment by michnovka** [comment]
this is really a deal-breaker for us at the moment :(

**Comment by NicKerrr** [comment]
+1
