### ISSUE TITLE
Translations: steamline discussions to either "Unterhaltung" or "Diskussion"

### ISSUE THREAD

**Issue by david-uhlig** [RocketChat/Rocket.Chat#31587]
### Description:

The german translations use both *Diskussion* and *Unterhaltung* to refer to the discussions feature. This should be steamlined to either one of those. Both work out from a translation point of view.

### Steps to reproduce:

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/4084672/306d0451-19ec-4560-8fd4-b6a43770d881)

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/4084672/671c6288-7146-4074-9208-58edf7caf263)

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/4084672/e6a97511-88fe-4751-a252-e8f0070356dd)

### Expected behavior:

Either *Diskussion* or *Unterhaltung* should be used in the translation, not both of them.

### Actual behavior:

See screenshots. Might not contain all locations where the translations appear.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.2
- Operating System: Ubuntu 22.04 LTS
- Deployment Method: Docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by sumitkukrejas** [comment]
so which one should we keep 'Unterhaltung' or 'Diskussion', I'll make change i18n for german.

**Comment by david-uhlig** [comment]
*Diskussion* would be the direct translation, and my choice here, since RC doesn't distinguish between discussion and conversation in english either. But that's on the maintainers to decide.

**Comment by hardikbhatia777** [comment]
Thanks for the report once again @david-uhlig!  

Would you mind checking out the fixed translations and verify that they're all appropriate? I'm not fluent enough in German (even though I did take a German course in school haha) to be completely sure. Thanks!
