### ISSUE TITLE
Two identical emojis for clown

### ISSUE THREAD

**Issue by Press1ToWin** [RocketChat/Rocket.Chat#31598]
![image](https://github.com/RocketChat/Rocket.Chat/assets/69167682/f65aaf24-35f9-4b5f-a69b-c484d7c58a02)
there are two emojis for clown and the only one difference is name for emoji, i guess one of emojis is needless

**Comment by ProgrammingPirates** [comment]
Hello Sir, @Press1ToWin Can you assign me this issues please ?

**Comment by Thanush19** [comment]
@Press1ToWin  ,if the issue is not resolved yet , i can work on this...

**Comment by MartinSchoeler** [comment]
Emojis are provided by the lib https://github.com/joypixels/emoji-toolkit
