### ISSUE TITLE
Smiley sizes wrong without text

### ISSUE THREAD

**Issue by gramakri** [RocketChat/Rocket.Chat#3159]
Your Rocket.Chat version: (make sure you are running the latest)

You can see this at demo.rocket.chat as well. This is a recent regression.

When you type a smiley with not text, it looks big like below.

![image](https://cloud.githubusercontent.com/assets/82041/15083990/74a0414c-1385-11e6-916d-e0003a0b3d89.png)

**Comment by gramakri** [comment]
I left a few smileys in the #general channel for you see to see for yourself. Thanks.

**Comment by Sing-Li** [comment]
Feature, not bug. Community member contributed - but without setting to disable.  

Will be adding a setting to disable in a future release.

**Comment by Otiel** [comment]
Created #9780 to track this.
