### ISSUE TITLE
Possible to join room multiple times

### ISSUE THREAD

**Issue by warcode** [RocketChat/Rocket.Chat#316]
A user should never be able to have multiple entries in a room.

Due to the routing being broken (?) when I go to /room/GENERAL and click JOIN in the preview mode I get added to the room multiple times. This should check if the user is already in the room before adding it again.

**Comment by marceloschmidt** [comment]
I cannot reproduce this, as the JOIN button doesn't show up. @warcode can you test this again and let us know if this is still a problem? Thanks!

**Comment by warcode** [comment]
This might be part of a different issue.

1. Leave/Hide the General channel
2. Go to more channels
3. All channel links go to /room instead of /room/id
4. Manually type in /room/GENERAL
5. Click Join button fails.

This issue appeared after the switch from Iron to Flow.

**Comment by marceloschmidt** [comment]
Fixed!
