### ISSUE TITLE
User limitation (25 user)

### ISSUE THREAD

**Issue by mohhamedion** [RocketChat/Rocket.Chat#31601]
I deployed the project on my localhost and am planning to deploy it on my own server. As far as I know, this is an open-source project, so it shouldn't be subject to any kind of limitation. However, for some reason, the app is restricted to only 25 users, even though I am not using Rocket.chat services. I am a little bit confused. is it paid service even if am using the open-source code?

PS: I was following this guide to deploy using Docker:
https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose

**Comment by Weuxel** [comment]
Hi,
go to the Administration Panel --> Subscription, scroll all the way down and click on "Cancel Registration" (or however the Button is called).
You should be back to Community Edition.
Fell into the same trap. It´s a dark pattern imho.

**Comment by mohhamedion** [comment]
@Weuxel  Thank you =)
how about the Conference Call, i cant see any providers in the Conference Call page? is it available only in the paid edition?

**Comment by demesg** [comment]
It may also be worth noting that it is not possible to evaluate Enterprise version without applying for Trial without manually contacting sales. If you e.g. want to develop custom roles/permissions.

**Comment by tamalbachar** [comment]
worked for me. thank you so much!!
