### ISSUE TITLE
[ Feature Request ] Can sort by Role of user

### ISSUE THREAD

**Issue by alihamza1221** [RocketChat/Rocket.Chat#31617]
### Steps to reproduce:

1.  go in workspace
2. Click on users.' 

### Expected behavior:
  Give option to get user according to role or sort according to role

### Actual behavior:
  Can't sort on the basis of rule.
  - so, if needed a specific user make hurdles to search through

![feature req](https://github.com/RocketChat/Rocket.Chat/assets/133019575/4900159b-1927-4646-af72-91a0cb5f8278)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.6.0-develop
- Operating System: windows 10
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.4 - x64                             |
- MongoDB Version:6.0.3

### Client Setup Information

- Desktop App or Browser Version: local host 3000 chrome
- Operating System: win 10 wsl ubuntu

**Comment by SySagar** [comment]
If no one is working. I will like to take up this issue @alihamza1221

**Comment by SySagar** [comment]
Also @alihamza1221  I just wanted to confirm if this is more like developing a filter so that on selecting specific roles we can get all the associated users.

**Comment by alihamza1221** [comment]
yes

**Comment by rique223** [comment]
Hey folks, first of all, thanks for your contribution. We are internally refactoring the user's page, which will introduce a filter-by-role system and a bunch of other QOL improvements to this page, and most likely solve the problems @alihamza1221 mentioned so hang tight while we work our magic.
