### ISSUE TITLE
电子邮件需要验证码如何解决

### ISSUE THREAD

**Issue by yaoxipenga** [RocketChat/Rocket.Chat#31610]
ERROR Unable to Login: {"isClientSafe":true,"error":"totp-required","reason":"TOTP Required","details":{"method":"email","codeGenerated":true,"emailOrUsername":"xipengyao666bot","availableMethods":["email"]},"message":"TOTP Required [totp-required]","errorType":"Meteor.Error"} Reason: TOTP Required
[Fri Feb 02 2024 04:33:27 GMT+0000 (UTC)] ERROR If joining GENERAL please make sure its using all caps.
[Fri Feb 02 2024 04:33:27 GMT+0000 (UTC)] ERROR If using LDAP, turn off LDAP, and turn on general user registration with email verification off

**Comment by alihamza1221** [comment]
@yaoxipenga  can you provide more details about the issue .
- how to reproduce

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://developer.rocket.chat/v1/docs/contribute-through-bug-reporting) again for help on providing additional information.
