### ISSUE TITLE
[6.6.0] OAuth - OpenConnectID login button without function

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#31618]
### Description:

Starting to test RocketChat 6.6.0 on my test platform. 
SAML login button is still working as before in 6.5.3.
The login via OAuth (Keycloak OpenConnectID) does not redirect to the keycloak service. Same happens for popup login style. Just no popup will be opened.

### Steps to reproduce:

1. Configure OAuth 
2. Try to login via the OAuth -> nothing happens while pressing the button

### Expected behavior:

Redirect to login page of the identity provider.

### Actual behavior:

Nothing is happening on the OAuth button.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: Rocky Linux 8.9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v14.21.3
- MongoDB Version:5.0.24 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Fedora 39

**Comment by alihamza1221** [comment]
@TimmiORG 
 can you provide any image or video regarding this it will be helpful

**Comment by TimmiORG** [comment]
Hi @alihamza1221 
very quick reply. ;)

Hope this helps. The mouse cursor is not visible but you see that I pressed first button twice with no effect. Than the SAML button with the redirect to the IDP.

[Bildschirmaufzeichnung vom 2024-02-02, 14-21-17.webm](https://github.com/RocketChat/Rocket.Chat/assets/979342/142904e6-6fe3-4ac5-8779-889d46d643be)

**Comment by TimmiORG** [comment]
Hi @pierre-lehnen-rc 
sorry for bothering again. But looks like OAuth is broken again in 6.6.0.
Issue is happening with FF and Chrome.

**Comment by pierre-lehnen-rc** [comment]
Do you get any errors on the browser's console?

**Comment by TimmiORG** [comment]
Yes while loading the page. But nothing while clicking on OAuth button.
[console-export-2024-2-12_14-55-15.txt](https://github.com/RocketChat/Rocket.Chat/files/14239193/console-export-2024-2-12_14-55-15.txt)

**Comment by pierre-lehnen-rc** [comment]
Looks like the client is failing to subscribe to one or more of the streams. Can you check the websocket on the network tab and see what messages are failing? (You'll need to refresh the page after opening the debugger window)

**Comment by TimmiORG** [comment]
it looks like this for me:
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/979342/31c9c5cd-4f55-428e-abb1-85392553366e)

**Comment by pierre-lehnen-rc** [comment]
If you click on that item you'll get a list of messages that were sent/received through it.

**Comment by TimmiORG** [comment]
Does this help:
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/979342/a9168f78-951e-463c-ac6c-d17f8413d5e8)

**Comment by pierre-lehnen-rc** [comment]
Not quite. I'm not sure how this is presented in firefox, but on chrome's debugger there's a "Messages" sub-tab when a websocket is selected.

**Comment by TimmiORG** [comment]
No problem to use Chrome
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/979342/b463f94b-49d1-47ab-b84e-17cab95006b2)

**Comment by pierre-lehnen-rc** [comment]
I've reproduced the issue here; I'm working on a fix for a patch coming out later this week.

**Comment by pierre-lehnen-rc** [comment]
I've fixed the issue on the linked PR and added an end-to-end test to ensure that the redirect doesn't break again with future changes.

I'm also planning on adding the complete OAuth flow to our end-to-end tests soon (I did something similar for SAML very recently). The bug was actually introduced by some of the groundwork I did in preparion for those tests.

**Comment by TimmiORG** [comment]
Hi @pierre-lehnen-rc 
thank you very much. 
It I understand correctly it happens only if SAML and OAuth are enabled at the same time.
I'm using only OAuth in production. So it should be fine to upgrade there or not?
When do you expect the fix to be released?

**Comment by pierre-lehnen-rc** [comment]
The bug is there if there's any non-custom login service, such as SAML or Google OAuth. If you have just the one Custom OAuth enabled in production, then it won't be affected.
We're preparing a patch release with the fix, probably for tomorrow.
