### ISSUE TITLE
dynamic search slug not working properly

### ISSUE THREAD

**Issue by SySagar** [RocketChat/Rocket.Chat#31653]
### Description:

If we want to search a particular item or word in the chats then we can simply use the search box. On first time entry it works. But on further searching the search urls slug in address bar gets wrongly updated.

### Steps to reproduce:

1. Go to search box on top left.
2. Search any item
3. Click on jump to that message button
4. Then search something else

### Expected behavior:

It should give the exact message in the chats 

### Actual behavior:

Update the address bar slug incorrectly hence no search found further

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.8
- Operating System: win 10
- Deployment Method:
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 5

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: win 10

### Additional context

https://github.com/RocketChat/Rocket.Chat/assets/93787385/7883a912-6c90-4edd-81d2-fe006d5b9984

**Comment by MSVaibhav4141** [comment]
Hey i can work on this .Kindly assign me this issue if possible:)
Thanks

**Comment by SySagar** [comment]
Hey @MSVaibhav4141 I have already work on this issue.

**Comment by MSVaibhav4141** [comment]
@SySagar Sorry ! My bad..
