### ISSUE TITLE
Augment outgoing webhook data

### ISSUE THREAD

**Issue by jimt** [RocketChat/Rocket.Chat#3168]
Your Rocket.Chat version: 0.27.0

It would be convenient if the outgoing webhook integration provided a `permalink` to the message so that the external service could build a link back to the specific message rather than just the channel.

I would also like a link to the user's avatar (although at least for now, that seems easy to derive from the `user_name`).

**Comment by jimt** [comment]
It would also be nice to receive the user's `Name` (in addition to `user_name`).

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
