### ISSUE TITLE
Push limit message is impossible to dismiss

### ISSUE THREAD

**Issue by ziorufus** [RocketChat/Rocket.Chat#31708]
### Description:

I have a self-installed version of Rocket.Chat (with docker), and it continuously shows the message "Attention You have reached your monthly mobile push limit. Check push usage for more details." even if we are not using Rocket.Chat on the mobile phone. In addition, the message immediately reappears after clicking on the X.

### Steps to reproduce:

1. Open Rocket.Chat (on web or app)
2. The message is always visible on the top of the screen, even after clicking the X to dismiss it

### Expected behavior:

1. I should not see it, since no one is using actively the iOS/Android app (some of us has it installed, but no one is really using it)
2. After clicking the X, the message should disappear.

### Actual behavior:

The message is always there and visible.

![Screenshot 2024-02-09 at 14 36 20](https://github.com/RocketChat/Rocket.Chat/assets/3517832/c531dcea-f69d-45c2-a3ea-da7ded5c7a7b)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.3
- Operating System: Ubuntu 22.04.3 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.16 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Chrome 121.0.6167.160 arm64 or app version 3.9.11
- Operating System: macos Sonoma

### Relevant logs:

No logs involved (I checked, but I could not see anything relevant for the issue).

**Comment by SubstantialCattle5** [comment]
Hey, can I work on this issue if this is still open.

**Comment by ziorufus** [comment]
I confirm the issue is still there.

**Comment by ziorufus** [comment]
Hi! I updated to version 6.9.2 and subscribed to the Starter Plan (I had no choice) and the message is still there, although the [pricing page](https://www.rocket.chat/pricing) says "Unlimited push notifications" for that plan. Is it possible to have this issue solved, please? I also would like to use Rocket.Chat from my mobile phone, but without notifications is really hard.

**Comment by reetp** [comment]
OP did not mention that mobile notifications have never worked.

This is likely a setup/support issue and there is a thread open on open.rocket.chat

https://open.rocket.chat/channel/support?msg=MRtKwvR6ZyE3cvrFn

Please follow up there.

If there is a bug this can be re-opened.

**Comment by reetp** [comment]
OP had notifications turned off.
