### ISSUE TITLE
ChatGPT feature is not working at all

### ISSUE THREAD

**Issue by SySagar** [RocketChat/Rocket.Chat#31702]
### Description:

Currently we have a chatGPT addon in the message box. It open a modal where you can enter promt and a custom message. However its output is unknow as it is not generating anything now.

### Steps to reproduce:

1. Go to any channel
2. In the message box , besdie the attachemt icon you will fin `+` symbol 
3. Click on it and select chatGPT
4. Enter the promt and message

### Expected behavior:

The results are know but I assume that it should fill the chatbox with the description

### Actual behavior:

Shows custom loading and then the modal collapses.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.2
- Operating System: win 10
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.x
- MongoDB Version: 6.x

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: win 10

![Screenshot (31)](https://github.com/RocketChat/Rocket.Chat/assets/93787385/cfe9b4d6-a470-41db-bcb2-daa4e75b1419)

**Comment by ProgrammingPirates** [comment]
Hello Sir, @SySagar  Can you assign me this issues please ?

**Comment by SySagar** [comment]
hey @ProgrammingPirates , I am not sure if this is pretty much an issue. Maybe we have to close it. Till a maintainer reviews it , I won't be closing.

**Comment by hugocostadev** [comment]
Yep, it's not an issue, the app was misplaced there and should not be used by contributors! Thanks for the feedback
