### ISSUE TITLE
Long "by" label causes line break for edited messages in german language

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#3171]
Your Rocket.Chat version: demo instance

Checkout the GIF below:

![ohne titel2 mov](https://cloud.githubusercontent.com/assets/944459/15100689/d516831a-1579-11e6-8265-b3966bc7719e.gif)

**Comment by geekgonecrazy** [comment]
suggested fix @frdmn ?  I'm trying to think how we could even handle this.  Unless we do like slack and others and simply append `(edited)` or i18n translation of that after the message

**Comment by frdmn** [comment]
What about we completely get rid of the "by" label like this since we still have the pen icon as "edit indicator":

![](http://up.frd.mn/n5KpT13M4q.png)

**Comment by frdmn** [comment]
I like the "(edited)" solution more than just the icon indicator. People are used to it (from Slack) and it's more obvious what it stand for.

**Comment by geekgonecrazy** [comment]
I tend to agree... Its simple.  Problem with that.. is what happens in other languages where word is longer then (edited) is?

**Comment by MartinSchoeler** [comment]
Will close this issue since today we are using just the icons

**Comment by frdmn** [comment]
👍
