### ISSUE TITLE
loadHistory method in Realtime Api 

### ISSUE THREAD

**Issue by Moralex45** [RocketChat/Rocket.Chat#31724]
There are 4 main payload arguments for the loadHistory method in the documentation: roomId, timestamp, quantity, date.
However, when viewing the source code
loadHistory(rid, end, limit = 20, ls, showThreadMessages = true) , the argument showThreadMessages appears.

How can I use the showThreadMessages argument?

`
        return self.create_method(
            Method.LOAD_HISTORY,
            channel_id,
            None,
            1,
            datetime.utcnow(),
            True
        )
`
The code above does not give any results

### Server Setup Information:

Rocket.Chat Version: 6.6.0
NodeJS Version: 14.21.3 - x64 
MongoDB Version: 5.0.24
MongoDB Engine: wiredTiger
Platform: linux
Process Port: 3001
Site URL: http://localhost:3001
ReplicaSet OpLog: Enabled 
Commit Hash: 92a307ec3d
Commit Branch: HEAD

**Comment by ProgrammingPirates** [comment]
Hello Sir, @Moralex45  Can you assign me this issues please ?

**Comment by Moralex45** [comment]
Hello @ProgrammingPirates , what do you mean? Can you help me with a solution?

**Comment by Moralex45** [comment]
Figured it out. But I think it would not be superfluous to specify all this in the documentation.
