### ISSUE TITLE
Unable to change room names

### ISSUE THREAD

**Issue by eliKeetch** [RocketChat/Rocket.Chat#31722]
### Description:

On 2 snap installations I cannot change the names of existing rooms. When I edit the room name a message pops up saying it was successful, though it does not actually update the name. They are both on the current version 6.6.0

### Steps to reproduce:

1. Go to workspace
2. Go to Rooms
3. Edit Room name
4. Change does not reflect

### Expected behavior:

It should update the room name on the front end

### Actual behavior:

The room name does not update 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 2

**Comment by PranitPatil03** [comment]
Hello @eliKeetch 

I tested this in my local environment and successfully edited the room name. I have a video showing the process.


https://github.com/RocketChat/Rocket.Chat/assets/91155068/758f90a8-0e25-4094-8025-a4526dc7c242

**Comment by eliKeetch** [comment]
@PranitPatil03, Thank you I actually didn't specify this but it was unable to update in the admin area

**Comment by Pritam-sd-dev** [comment]
hi, I am working to fix it.
