### ISSUE TITLE
Statuses get stuck until refresh the page.

### ISSUE THREAD

**Issue by SerPenTargo** [RocketChat/Rocket.Chat#31744]
After upgrading to version 6.6.0, when status changes are made, other users do not see the change in their contact list until they click the Refresh Page (F5) button in their browser.

### Steps to reproduce:

User Ben changes status from Online to Away or from Away to Busy.

### Expected behavior:

All other users immediately see Ben's status change.

### Actual behavior:

Users see Ben's status as it was before the change.
To see Ben's status change, users have to refresh the page in their browser.

The same thing happens in the Desktop App, but you have to close/open it to see the status change.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0.
- Operating System: Oracle Linux 9.3.
- Deployment Method: docker.
- Number of Running Instances: 1.
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3 - x64.
- MongoDB Version: 5.0.24.

### Client Setup Information

- Desktop App or Browser Version: both Desktop App 3.9.12 and 3.9.13 and Browser Version of Rocket.Chat.
- Operating System: Windows 10 22H2, Windows 11 23H2.

**Comment by Gummikavalier** [comment]
Linking https://github.com/RocketChat/Rocket.Chat/issues/31705 here

**Comment by sampaiodiego** [comment]
thanks @Gummikavalier .. 

@SerPenTargo this issue has been fixed on 6.6.1 ..
