### ISSUE TITLE
Some emoji aliases don't work

### ISSUE THREAD

**Issue by bt** [RocketChat/Rocket.Chat#3176]
Your Rocket.Chat version: 0.29

So far I have found that the `cry` ASCII alias does not work; specifically `:'(`

![screen shot 2016-05-09 at 11 33 21 pm](https://cloud.githubusercontent.com/assets/1100843/15114686/7210d35e-163e-11e6-8226-7fa983dad6f4.png)

**Comment by sampaiodiego** [comment]
duplicated of #2013

**Comment by bt** [comment]
Oops, sorry! 👍
