### ISSUE TITLE
Log In Error as Admin - seems back

### ISSUE THREAD

**Issue by Fiodin** [RocketChat/Rocket.Chat#31779]
It seems like this error #29249 is back.

I am running some instances under Snapd and a few days ago it did the automatic upgrade to version 6.6.0. Since then I cannot log in as admin with this exact error.
On one instance I was logged in as admin and I am still. But trying to log in in a new window crashes with that error

I tried to do the DB Banners thing, but Mongo doesn't find any big banners or deleting em doesn't change anything. And because I am running under Snap I couldn't find the _i18n.json_ file within the snap directory.

Down- and Upgrading rocketchat didn't solve it, too

I do have 2FA enabled for the admin account.

Any suggestions?

### Steps to reproduce:

1. Update Rocket.Chat to Version 6.6.0
2. Try to Log-In as admin

### Expected behavior:

Log-In succeeds.

### Actual behavior:

Right after the Log-In I get an error what says "Application Error. The application GUI just crashed"

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: different: on Debian 12 and Ubuntu server 22.04
- Deployment Method: Snap
- Number of Running Instances: 3

### Additional Information

On all instances I do have 2FA via TOTP activated.

### Edit

I even now tried the solution in Comment [1552854287](https://github.com/RocketChat/Rocket.Chat/issues/29249#issuecomment-1552854287) with no effect.

**Comment by Dr-Shadow** [comment]
Did you have success fixing this issue recently @Fiodin ?

**Comment by Fiodin** [comment]
> Did you have success fixing this issue recently @Fiodin ? (6.6.1)

No, cause I don't switch to edge channel.

**Comment by Fiodin** [comment]
Last night I tried something:
1. Did a backup of one of the instances
2. Completely removed the Snap installation for it
3. Reinstalled the Snap
4. Restored the Backup
Finally could log in as admin

Then did the same with the other two instances with the same result.

I don't if this is solved now, but the error is gone and I could log-in.
