### ISSUE TITLE
Outlook Email Rendering

### ISSUE THREAD

**Issue by Silvenga** [RocketChat/Rocket.Chat#3179]
Your Rocket.Chat version: (make sure you are running the latest)
0.28.0 (the version demo is running?)

In emails, source below:

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">&gt; test <img class="emojione" alt="😏" src="//cdn.jsdelivr.net/emojione/assets/png/1f60f.png?v=2.1.4"> 
```

Emojis are referenced using `//cdn.jsdelivr.net`. This does not work correctly under Outlook. Although, not an expert in Outlook, I believe Outlook is trying to follow the asset as a UNC path (basically, it's checking networking shares). This is expected under Outlook as assets may be on network shares for internal messages. 

Rocket.Chat should consider using https (the overhead of TLS is insignificant) or http (images may not need protection) to maintain compatiblity. Currently, whenever Outlook views the images from Rocket.Chat, the application freezes pending a timeout.

**Comment by geekgonecrazy** [comment]
with `cdn.jsdelivr.net` and being in emails, it might be safe for us to just use `https://`

**Comment by engelgabriel** [comment]
Is this still a problem? We use local sprites now.

**Comment by geekgonecrazy** [comment]
I clicked mail message on a message and sent to an outlook account.  It actually showed up like this:

![image](https://cloud.githubusercontent.com/assets/51996/21377242/80fb3f56-c702-11e6-8998-0f1e5b906b1e.png)

**Comment by Silvenga** [comment]
I can no longer confirm - company hasn't upgraded since 0.34.0 (and likely won't anytime soon).

**Comment by isabellarussell** [comment]
Please let us know if this is still a problem. For now, we are closing the issue.
