### ISSUE TITLE
slack import doesn't classified channels..

### ISSUE THREAD

**Issue by ninetiger99** [RocketChat/Rocket.Chat#3180]
Your Rocket.Chat version: (make sure you are running the latest)
0.29.0 using docker

slack import doesn't classified channels..
today, I export slack data using standard slack exporter.
and import slack data using slack importer in rocket.chat. import is success. but, all message in the #general channel. how bad... please fix slack importer classified message's own channel.

**Comment by engelgabriel** [comment]
I believe this is fixed on the develop branch.. and I'll merge to master in a few hours.

**Comment by ninetiger99** [comment]
Thx, I waiting 0.30.0 version. 
Have a nice day.

**Comment by engelgabriel** [comment]
Done! :)
