### ISSUE TITLE
Moving the application window throws error dialog

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3181]
Your Rocket.Chat version: 1.3.1
Windows 7 Professional

When I click and drag the title bar of the application to move the window, I get an error window. Literally whenever I move the window a few inches it throws the error. If I acknowledge the error dialog, and then move the application, the error is thrown again.

![image](https://cloud.githubusercontent.com/assets/10524529/15119206/d0d89806-15dd-11e6-96b2-c34eab4592bb.png)

**Comment by geekgonecrazy** [comment]
@nmummau does this happen immediately after starting the application up?

Like if you kill it completely (make sure its not in task bar, or there aren't more then on in task bar) then start it.  How long before this happens?

**Comment by geekgonecrazy** [comment]
@nmummau I've moved this over to the desktop application repository: https://github.com/RocketChat/Rocket.Chat.Electron/issues/187 please follow up there.
