### ISSUE TITLE
Images in chat not loading - 504 Gateway Time-out

### ISSUE THREAD

**Issue by rest2t** [RocketChat/Rocket.Chat#31818]
### Description:

After upgrading to version 6.6.1, there was an error with infinite loading of the client until the browser zsrash.
After restoring the installation from a backup, the images do not load with error 504 Bad Gateway.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Images are loading

### Actual behavior:

Images are not loading - error 504 Gateway Time Out

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: Ubuntu 23.10
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.5

### Client Setup Information

- Desktop App or Browser Version: Not working on App, Mobile and browser
- Operating System: Ubuntu, Windows, Android

**Comment by rest2t** [comment]
Uploading file also cause 504 error.

**Comment by Himanshu-kiran** [comment]
Please add steps to reproduce.
