### ISSUE TITLE
Hi, I am new here and am interested in contributing to rocket chat. Is this issue being taken up by someone else, or can I work on it?

### ISSUE THREAD

**Issue by 143divya** [RocketChat/Rocket.Chat#31827]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by sub20hz** [comment]
Stop following dumb youtubers and sh*tting up open source projects in an attempt to brand yourself as an open source contributor (who does not know how to program) to scam some employer in your home country/abroad
