### ISSUE TITLE
Pasting images to uploads, files are missing file extension

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3183]
When I post image to a room from clipboard, it will save it as clipboard.. so when anyone downloads that file it will be with file format, and they can't open it, can we make it default to an image (JPEG)? 

or any other format if its audio or video?

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by geekgonecrazy** [comment]
I'd say we need do based on mime type.

**Comment by IQ2022** [comment]
I think this is a much needed feature, our file uploading system need to be improved, similar features to SLACK, if not better.. :)

**Comment by nishimaki10** [comment]
:+1:

**Comment by 24601** [comment]
It seems that the PR merged in 91b4f0 didn't extend this new logic to S3-based file uploads. Can anyone verify this or explain why this didn't happen? We are considering doing the work and will source it back, but wanted to check to see if there was any wisdom around excluding S3.

**Comment by bpetrynski** [comment]
This problem still exists, at least on macOS.

macOS app version: 2.15.3
server app version: 0.74.3

**Comment by AndreySemenov1** [comment]
Hi! 

Any news?
