### ISSUE TITLE
Unable to leave public channels

### ISSUE THREAD

**Issue by mischah** [RocketChat/Rocket.Chat#3184]
Your Rocket.Chat version: `0.29.0`

Hi there, it seems that is isn’t possible to leave channels.

Steps to reproduce:

+ Enter a public channel
+ Enter `/leave`
  + Result:  
![rocket chat 2016-05-09 21-20-45](https://cloud.githubusercontent.com/assets/441011/15125205/f1d3453a-162b-11e6-9d4e-21995ca45dcf.png)
+ Hit the »leave« button in the roomlist in the left sidebar
  + Result:  
![rocket chat 2016-05-09 21-23-32](https://cloud.githubusercontent.com/assets/441011/15125314/6b8ce8c2-162c-11e6-9aaa-423f4f238012.png)

The only way to get out of the room seems to be to get kicked from a moderator or owner by now.

**Comment by PavelVanecek** [comment]
This issue has already been reported and fixed for the next release: https://github.com/RocketChat/Rocket.Chat/issues/3121

**Comment by mischah** [comment]
Oops. Thanks. I did used the search. But didn’t find it.
