### ISSUE TITLE
Able to login before email verified

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3185]
I enabled turn email verification on (in registration)
Went and tried signing up, it waited a bit and then logged me in with the user i selected,

i did receive email to verify, shouldn't it wait first to ensure that email is correct?  then log me into chat room?

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by geekgonecrazy** [comment]
Ok as per our conversation on the demo server.  This isn't actually a bug.  When you use oauth to sign up, email address is auto verified.
