### ISSUE TITLE
User presence issues in 6.6.2 

### ISSUE THREAD

**Issue by Alestor** [RocketChat/Rocket.Chat#31873]
### Description:

The presence of users are still not updated properly on the latest release 6.6.2.  

### Steps to reproduce:

Login to the workspace from browser with user account A. Login to the workspace from the IOS App with user Account B. Close the app on IOS. Check status on the browser from user account A. 

### Expected behavior:

On 6.5.3 and before the user B goes into away on closing the app on a mobile  device and offline after a reasonable amount of time like 60 to 120 seconds.

### Actual behavior:

The user B on the mobile device stays online for hours and more from the perspective of user A (browser).

### Server Setup Information:

- Version of Rocket.Chat Server:  6.6.2
- Operating System:  Debian 10
- Deployment Method: tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  1
- NodeJS Version:  v14.21.3
- MongoDB Version: 5.0.25

### Client Setup Information

- Desktop App or Browser Version: Firefox 123 on client A and App version 4.46.57000 on IOS client B
- Operating System: Linux / IOS

### Relevant logs:

Downgrading to 6.5.3 fixes this behavior immediately within the same environment.

**Comment by Gummikavalier** [comment]
Linking to existing discussion at https://github.com/RocketChat/Rocket.Chat/issues/31768

**Comment by shoei101** [comment]
this has been happening since 6.6.0 - hopefully we get a fix soon
