### ISSUE TITLE
Chinese for Taiwan reverst to Chinese

### ISSUE THREAD

**Issue by gregorycoleman** [RocketChat/Rocket.Chat#3188]
Your Rocket.Chat version: 1.3.1 Windows Desktop

I select Chinese Taiwan in the preferences. The next time I go to preferences, langusage reverts to a generic "Chinese" and displays simplified characters.

**Comment by MartinSchoeler** [comment]
@gregorycoleman is this still happening in the latest release?

**Comment by MartinSchoeler** [comment]
Due lack of updates I will close this issue. If the bug still exists, please reopen this. Thanks for the feedback
