### ISSUE TITLE
Notifying messages containing highlight words from self

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3190]
Android Rocket.Chat version: 2.3.1
Desktop Rocket.Chat version: 1.3.1

I have the word 'test' setup as a highlight word in Rocket.Chat. Every time I, myself, type the word 'test' I'm getting an Android notification on my phone. Seems a bit excessive, considering I know what I just typed.

**Comment by geekgonecrazy** [comment]
yes I have experienced this as well.  Also happens if you have notify all on, and you're signed in to two locations.

Like you post a message from your phone, but you have the desktop client connected.  It will notify the desktop client that you posted a message.

**Comment by Hudell** [comment]
We have recently refactored the notification system, so I'll be closing this old issue. If someone runs into this problem again, it can be reopened.
