### ISSUE TITLE
Add warning that users messages will be deleted when deleting the user

### ISSUE THREAD

**Issue by s17t** [RocketChat/Rocket.Chat#3191]
Your Rocket.Chat version: 0.29

Deleting user will delete all her message without a warning. Would be possible to show a warning/confirmation before deleting user or guide admin toward disabling user instead of deleting it ?

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
