### ISSUE TITLE
Add ability to specify minimum username length

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat#3192]
Your Rocket.Chat version: 0.29

This is echoed from a request on rocket.chat #support.

Add the ability to specify a minimum length for usernames on registration.

i.e: Usernames must be greater than [5] characters.

**Comment by sampaiodiego** [comment]
Would be nice to have a setting for such validation.

But as a workaround, you can change the RegExp of `UTF8 Names Validation` setting (under `Administration > General`) to something like this: `[0-9a-zA-Z-_.]{5,}`

**Comment by wildaces215** [comment]
Is this issue still open?

**Comment by neotim** [comment]
close

**Comment by marceloschmidt** [comment]
I'll close this in favor of @sampaiodiego's answer and keep #4301 referenced
