### ISSUE TITLE
Switching between Administration->Users page and Channel causes message ui to overlap

### ISSUE THREAD

**Issue by acaronmd** [RocketChat/Rocket.Chat#3193]
seems like #1221 hasn't been completely squashed yet. I can easily reproduce it by going back and forth from the Administration->Users page to the General Channel.

![image](https://cloud.githubusercontent.com/assets/17034188/15153434/82beee9a-1696-11e6-9629-d0ce7ad3b085.png)

Your Rocket.Chat version: 0.30.0

**Comment by jhagberg** [comment]
Got the same issue here when upgrading to 0.30.0

**Comment by cpitman** [comment]
Multiple channels overlapping is still reproducible in 0.42 as well.

**Comment by JackDragon** [comment]
Got the same issue still in 0.42. And it sometimes happens when switching to and from other tabs as well, not just rocketchat. Using chrome.

**Comment by ggazzo** [comment]
We dont have this behavior anymore, if I'm wrong please open again :)
