### ISSUE TITLE
is there any way to downgrade v6.5.0 to v6.4.X?

### ISSUE THREAD

**Issue by filefi** [RocketChat/Rocket.Chat#31936]
Description:
I've upgraded to 6.5.0 and was greeted by "registration needed". I did that... a now a pro plan trial was activated.
I do not want any trial. So I disabled it.
Now all of a sudden there is a user limit of 25! With the option to pay thousands of dollars per year to keep using rocketchat.

Nothing of the above was mentioned in the changelog.

Steps to reproduce:
Have a running rocketchat version < 6.5.0
Update to 6.5.0
Expected behavior:
I expected either to continue using the free plan or be informed that the free plan is going away and Im supposed to pay thousands of dollars per year to continue using RocketChat.

Actual behavior:
See Description above.

Server Setup Information:
Version of Rocket.Chat Server: 6.4.8 => 6.5.0
Operating System: Debian
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: active
NodeJS Version: 14.21.3
MongoDB Version: 6.0
Client Setup Information
Desktop App or Browser Version: 3.9.10
Operating System: Mac OS Sonoma

**Comment by bulkinav** [comment]
> Nothing of the above was mentioned in the changelog.

Yes, the introduction of paid restrictions was very quiet. Nevertheless, this was evident from the commits, but it is unlikely that many people are reading them.

**Comment by david-uhlig** [comment]
When you cancel the "trial" subscription, you get back to the community edition.

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/4084672/bbecf389-d1d6-435c-b8bb-ed6096a0c825)

![grafik](https://github.com/RocketChat/Rocket.Chat/assets/4084672/1a9a27af-3df0-465a-8fe8-953c1ad62e47)

**Comment by Visbhavesh** [comment]
I wanted to work in thus issue please Assign this issue to me.

**Comment by filefi** [comment]
> When you cancel the "trial" subscription, you get back to the community edition.
> 
> ![grafik](https://private-user-images.githubusercontent.com/4084672/311432159-bbecf389-d1d6-435c-b8bb-ed6096a0c825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzc2NjYsIm5iZiI6MTcxMTE3NzM2NiwicGF0aCI6Ii80MDg0NjcyLzMxMTQzMjE1OS1iYmVjZjM4OS1kMWQ2LTQzNWMtYjhiYi1lZDYwOTZhMGM4MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMDcwMjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ5YzdiNmZlYzI3NmRlY2QzMzAzZDllZTM2ZjczZDIwZTBiZmQyMDdlYmI0MDcyMTEwMWJjM2Y3ZTMwNzRkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EM72vzKt-YehgP-mx4RTBDfZn8Ug3-2VP5yhY4igCJ4)
> 
> ![grafik](https://private-user-images.githubusercontent.com/4084672/311432221-1a9a27af-3df0-465a-8fe8-953c1ad62e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzc2NjYsIm5iZiI6MTcxMTE3NzM2NiwicGF0aCI6Ii80MDg0NjcyLzMxMTQzMjIyMS0xYTlhMjdhZi0zZGYwLTQ2NWEtOGZlOC05NTNjMWFkNjJlNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMDcwMjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ4MzVhNGY3Yjg1NTk1ZjFkMjMxMjNmY2I0Y2MyZWU0YTVhNjEwZWM3NzVjOGFjMjBiYTA5ZjFmMmQzYzllOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t2rJZRBGc3hGYWxLuaTPnK-40BdjdS9HRhBdbKEDggc)

For Rocket.Chat version 6.5.0, workspace registration via the Cloud Portal is **mandatory**. Unregistered workspaces will receive a prompt for registration, and access to the workspace will be restricted for admins in the web application until the registration process is fully completed.

**Comment by david-uhlig** [comment]
Sure. However, my previous statement remains valid. You have the option to opt-out of the starter tier and return to the community tier with the same restrictions as before version 6.5.0.

**Comment by filefi** [comment]
> Sure. However, my previous statement remains valid. You have the option to opt-out of the starter tier and return to the community tier with the same restrictions as before version 6.5.0.

but my admin account can not login without regsitration, I lost the control of my system.

**Comment by geekgonecrazy** [comment]
Downgrading isn't recommended there were data migrations between the two versions.  Best case is restoring from backup.

If really want to take a big risk can find the highest migration version in 6.4.0 and update the migration collection with that as the migrated version.  Then you can start up.  You risk data being in a bad format though.

If you wish to follow up on this I would suggest the forum.
