### ISSUE TITLE
Slide buttons not turning off on Integrations

### ISSUE THREAD

**Issue by reminett** [RocketChat/Rocket.Chat#31943]
### Description:

Slider buttons on Outgoing Webhooks - Advanced Settings can be turned off, but it does not reflect that it is turned off after saving.

### Steps to reproduce:

Go to:
Administration
Workspace
Integrations
Outgoing
Click one of the integrations
Scroll down to Advanced Settings and expand it
Turn off i.e. "Retry Failed Url Calls"
Save
Go back into the integrations and you will see that the button is now enabled again. However, it is indeed turned off when testing the integration (not retrying on fail).

### Expected behavior:

The slider button should reflect that the setting is Off instead of On when it in reality has the Off-state.

### Actual behavior:

The slider button indicates it is On when in reality it is Off.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.3

- Operating System: Linux (Ubuntu)

- Deployment Method: Docker

- Number of Running Instances: 1

- DB Replicaset Oplog: 

"optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1709926013, 1),
                        "t" : NumberLong(12)
                },
                "lastCommittedWallTime" : ISODate("2024-03-08T19:26:53.330Z"),
                "readConcernMajorityOpTime" : {
                        "ts" : Timestamp(1709926013, 1),
                        "t" : NumberLong(12)
                },
                "appliedOpTime" : {
                        "ts" : Timestamp(1709926013, 1),
                        "t" : NumberLong(12)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1709926013, 1),
                        "t" : NumberLong(12)
                },
                "lastAppliedWallTime" : ISODate("2024-03-08T19:26:53.330Z"),
                "lastDurableWallTime" : ISODate("2024-03-08T19:26:53.330Z")

- NodeJS Version: v14.21.3

- MongoDB Version: 5.0.23

### Client Setup Information

- Desktop App or Browser Version: Chrome 122.0.6261.112

- Operating System: MacOS

**Comment by Gummikavalier** [comment]
It is somewhat common issue in RC admin console that things do not show correctly after editing some existing setting. Sometimes even whole entries of the configuration go missing. I've developed a habit that I always do shift-reload in the browser to clear up the views from missing or ghost entries.

When I do some really important stuff, such as changing authentication settings, I often confirm them using private/incognito browser session to be sure.

**Comment by hardikbhatia777** [comment]
Thanks for the report @reminett!

It's (fortunately) a rather simple issue with frontend logic. Should be fixed soon.

**Comment by hardikbhatia777** [comment]
@Gummikavalier can you direct me to the admin console components that you mentioned here? I - suspect there's a similar issue there, I'll try including that in this PR or raise another one if its something different.

**Comment by reminett** [comment]
> Thanks for the report @reminett!
> 
> It's (fortunately) a simple issue with the frontend logic of the toggle switch. Should be fixed soon.

Perfect - thanks for looking at this so fast! This is the first time I report a bug, so this was a great experience :)
Any idea when this will be in a release?

**Comment by hardikbhatia777** [comment]
> Perfect - thanks for looking at this so fast! This is the first time I report a bug, so this was a great experience :)

Glad to hear that :)  🚀

> Any idea when this will be in a release?

Not really sure about this, I'm not a part of the internal team.

**Comment by Gummikavalier** [comment]
> @Gummikavalier can you direct me to the admin console components that you mentioned here? I suspect there's a similar issue there, I'll try including that in this PR or raise another one if its something different.

Different issue (cache ones I mean). For instance when you edit Premium LDAP settings, it often happens that big parts of the configuration disappear from the browser view after saving the settings and later coming back to check them.
