### ISSUE TITLE
Deploy.to.Cloud repo

### ISSUE THREAD

**Issue by lkraider** [RocketChat/Rocket.Chat#3194]
Whatever happened to it? Where are the deploy scripts now? Interested in the Vagrant scripts.

**Comment by geekgonecrazy** [comment]
I believe they were all transitioned to our docs repo: https://github.com/RocketChat/Rocket.Chat.Docs
@RocketChat/core someone might be able to tell you where the vagrant file disappeared to in there?

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat.Docs/tree/master/3.%20Installation/5.%20Automation%20Tools/Vagrant

**Comment by geekgonecrazy** [comment]
@engelgabriel thanks!
