### ISSUE TITLE
Enable popup notification remain visible even after disabling and actively pressing the cancel key 

### ISSUE THREAD

**Issue by RomeoIndiaJulietUniform** [RocketChat/Rocket.Chat#31947]
### Steps to reproduce:

1.  Click on Administration by pressing the three vertical dots
2.  Go to Workspace
3.  Click on Integrations
4. Click on New
5. Choose Incoming
6.  Enable the toggle
7.  Try to disable the toggle
8.  Try to press the Cancel button 

### Expected behavior:

  After disabling the toggle or the pressing the Cancel Button or doing both the pop-up should disappear 

### Actual behavior: The pop-up remains active 

![Screenshot from 2024-03-09 14-28-19](https://github.com/RocketChat/Rocket.Chat/assets/157402485/efe6afb9-2b09-4c7d-ad68-807cb41a38d0)

[Screencast from 09-03-24 02:28:41 PM IST.webm](https://github.com/RocketChat/Rocket.Chat/assets/157402485/c1aa30d3-173d-4205-a3ab-1c85631046fa)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.0-develop 
- Operating System: Linux Ubuntu 22.04 LTS
- Deployment Method:  Linux
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: 14.21.4 - x64  
- MongoDB Version: db version v7.0.5

### Client Setup Information

- Desktop App or Browser Version: Google Chrome Version 121.0.6167.139 (Official Build) (64-bit)
- Operating System: Linux Ubuntu 22.04 LTS

**Comment by hardikbhatia777** [comment]
Hey, I'm unable to replicate this issue on 6.7.0 - it's working as intended on my end. Can you try again and confirm if the issue persists?

**Comment by RomeoIndiaJulietUniform** [comment]
@hardikbhatia777 Yes, now it got fixed in my part also. Maybe it was just another service hang or state management issue. Closing the issue, thanks.
