### ISSUE TITLE
Return to channel view when closing preferences or admin navigation

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#3195]
Your Rocket.Chat version: (0.30.0)

Two annoying things with the chat right now is when you press on the arrow next to your username the list with settings pops up, when you press somewhere outside this box it should dissapear instead of having to manually press on the arrow again for it to slide up.

Second thing is when you go to "My account" and when you're done and press on the (x) the whole menu should collapse and you should get back to the room you previously was in, right now you have to press on it again to come back there.

![animation](https://cloud.githubusercontent.com/assets/17712562/15161130/41e6a7f2-16fd-11e6-9e50-99c54121fcc2.gif)

**Comment by phutchins** [comment]
I'm on board with this. We're currently assessing a number of different chat solutions for our business and I really love RocketChat. This is one of the 2 or 3 things however that makes the experience feel clunky which doesn't really fit into the rest of the experience which is very clean and smooth! 

Would love to see this changed... If its fairly simple and someone can point me in the right direction in the codebase I may be able to find time to submit a PR for this.
