### ISSUE TITLE
[BUG ] message box not showing in embedded iframe 

### ISSUE THREAD

**Issue by isaacdarcilla** [RocketChat/Rocket.Chat#31951]
### Description:

Trying to embed an iframe but the message box is not showing. it just keeps on loading the skeletons.

See image: 

![image](https://github.com/RocketChat/Rocket.Chat/assets/22732118/cdf83f32-7048-4fb4-9353-f718cda59506)

### Steps to reproduce:

1. Followed the integration documentation [here](https://developer.rocket.chat/chat-engine/chat-engine-in-iframe)
2. Load the locahost:3000 in the browser.

### Expected behavior:

The message box should appear, just like the messages.

### Actual behavior:

The message box is not showing, it just loads.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.1
- Operating System: Windows 11
- Deployment Method: AWS
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 16.20
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows 11

### Relevant logs:

{
    "isClientSafe": true,
    "error": "not-allowed",
    "message": "[not-allowed]",
    "errorType": "Meteor.Error"
}

**Comment by vachigaggl** [comment]
@isaacdarcilla did you implement this script in your iframe url?
```
<script>
window.parent.postMessage({
  event: 'login-with-token',
  loginToken: 'your-token'
}, 'http://your.rocket.chat.url');
</script>
```

Since my update to Rocket.Chat 6.10, I get this in my console, because the code of the iframe url no longer gets evaluated:
```
Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' 'unsafe-eval' 'sha256-jqxtvDkBbRAl9Hpqv68WdNOieepg8tJSYu1xIy7zT34=' 'sha256-aui5xYk3Lu1dQcnsPlNZI+qDTdfzdUv3fzsw80VLJgw='”
```

Apparently the cahange of the Content-Security-Policy conflicts with the iframe auth feature!

**Comment by isaacdarcilla** [comment]
Yes, this is resolve though, the issue is coming from the chat name, you should check if your using the Room ID or Room name in the URL.
