### ISSUE TITLE
Unprivileged user will see all channel, visibility leaks

### ISSUE THREAD

**Issue by s17t** [RocketChat/Rocket.Chat#3196]
Your Rocket.Chat version: 0.29

I have 'member' role with the permissions: 'view-c-room', 'view-d-room' and 'view-p-room'. 

When user with this role is engaged in a chat he will able to see all other channel using the '#' auto completion, join in, see users list in that channel and also list uploaded files in that channel.

At some level the role checks are made, though, because he won't be able to send message or read history nor download files.

**Comment by marceloschmidt** [comment]
@s17t I'm not sure I'm following what the bug is. `view-c-room` gives the permission of viewing **all** public channels list and also to **join** any of those channels. After joining, they can freely speak. Could you clarify what would you expect from this permission? Thanks.

**Comment by s17t** [comment]
@marceloschmidt, my bad. The affected role is named 'user' with just one privilege: 'view-p-room'.

I confirm that behavior.

Thank for you

**Comment by sinteur** [comment]
To test the guest role I created a new user called "test.user". I can add the guest role to the new account, however, I cannot REMOVE the user role as there are too many users in my system to have the new user show up on the first (and only) screen of users. How can I remove a role?

**Comment by maxdwit** [comment]
still an issue in Version 0.49:
Guest User role ( no permission set at all )
can see all non private channels / can join all non private channels

**Comment by sampaiodiego** [comment]
@maxdwit can you please confirm if this is still an issue? we have done some improvements on permissions and I think it should be fixed.. thx

**Comment by MartinSchoeler** [comment]
I will close this due lack of updates, if the problem appears again, please reopen this with updated details. Thanks!
