### ISSUE TITLE
Custom replaceFn

### ISSUE THREAD

**Issue by baruKV** [RocketChat/Rocket.Chat#3197]
Hi,

I want to add a custom replaceFn function to autolink our ticket ids.
I figured out how but not where (https://github.com/gregjacobs/Autolinker.js#custom-replacement-function)
What is the best way to do it? I use docker and in the Dockerfile the release is downloaded from web.

Your Rocket.Chat version: 0.23.0

**Comment by marceloschmidt** [comment]
You'd probably have to make changes to the autolinker package `packages/rocketchat-autolinker/autolinker.coffee`. Using docker is not the best way to make changes to the source code. I recommend forking the project on github, making your changes, then compiling it yourself... you can create a new docker image after you make the changes.

**Comment by baruKV** [comment]
Hi marceloschmidt,

thx for the hint. 
Maybe a stupid question but I can't find a build instruction.
There is an example-build.sh and the travis build script https://travis-ci.org/RocketChat/Rocket.Chat
Is `meteor build` enough ?

**Comment by marceloschmidt** [comment]
Usually `meteor build` would be enough... specific requirements need specific settings though, so let us know if you need further assistance on deploying your changes.
