### ISSUE TITLE
API response not including rooms (users.info)

### ISSUE THREAD

**Issue by isaacdarcilla** [RocketChat/Rocket.Chat#31977]
When using directly to postman

![image](https://github.com/RocketChat/Rocket.Chat/assets/22732118/42fff8f7-5b61-4c3f-a7d8-2413770667e8)

When in the browser

![image](https://github.com/RocketChat/Rocket.Chat/assets/22732118/83154761-2e0e-4a15-8190-5e93ca998054)

**Comment by Visbhavesh** [comment]
I wanted to work in thus issue please Assign this issue to me.
