### ISSUE TITLE
HTML Tags not recognized in Registation Email

### ISSUE THREAD

**Issue by LaClick** [RocketChat/Rocket.Chat#3198]
Hello,
The mails we receive when having a new registration are not html but raw text.
We see the html tags in the mail boby.

I am talking about the body mail in Administration->Email->Registration->Body
It works ok for the invitation mail and the admin registration mail.

Can some one help us.

Best regards, Xavier RockeChat implementation : www.laclick.fr

**Comment by pierreozoux** [comment]
I'm hosting @LaClick and he is running latest (0.30.0).

I don't understand why, but on the registration email (only), I get a "Content-Type: text/plain".

Header and Footer are empty and the Registration is:
```
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body>
        Bonjour [fname] <a href="mailto://contact@laclick.fr">contact@laclick.fr</a>
    </body>
</html>
```

I tried to look in the code, but it looked fine :) Do you have any idea what is happening?

**Comment by pierreozoux** [comment]
Oops, sorry I found the issue! \o/

I send a fix!

**Comment by marceloschmidt** [comment]
You did? I was just committing the changes to `develop` :)

**Comment by pierreozoux** [comment]
You did?

**Comment by marceloschmidt** [comment]
Was this your solution? https://github.com/RocketChat/Rocket.Chat/commit/a516cc40744c1ce8229a2c205c82b715f7a67e03

**Comment by pierreozoux** [comment]
Yes :) line 41! Great!

Thanks a lot for your reactivity!

**Comment by marceloschmidt** [comment]
Thanks! Let me close this one now ;)

**Comment by pierreozoux** [comment]
Just tested, and I got Internal server error:

```
app_1 | [methods] registerUser -> userId: null , arguments:  { '0': 
app_1 |    { name: '$$',
app_1 |      emailOrUsername: '$$',
app_1 |      email: '$$',
app_1 |      pass: '$$',
app_1 |      'confirm-pass': '$$' } }
app_1 | Exception while invoking method 'registerUser' TypeError: undefined is not a function
app_1 |     at Object.Accounts.emailTemplates.verifyEmail.html (server/lib/accounts.coffee:26:2)
app_1 |     at AccountsServer.Accounts.sendVerificationEmail (password_server.js:775:43)
app_1 |     at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:20:13)
app_1 |     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
app_1 |     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
app_1 |     at livedata_server.js:708:19
app_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
app_1 |     at livedata_server.js:706:40
app_1 |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
app_1 |     at livedata_server.js:704:46
```

**Comment by marceloschmidt** [comment]
Ahh :( I'll fix that ASAP! Thanks

**Comment by LaClick** [comment]
Now it looks that the HTML interpretor, treats LineFeeds as <br>, I have to delete all LF to have the goog looking.

**Comment by LaClick** [comment]
By the way is it possible to have the verification mail adress mail configurable

**Comment by marceloschmidt** [comment]
@pierreozoux could you try now? Thanks.

**Comment by pierreozoux** [comment]
It is fixed, thanks!

And you can close the issue.
