### ISSUE TITLE
Cannot find module '../build/Release/sharp-darwin-arm64v8.node - nothing happens, just program stuck 

### ISSUE THREAD

**Issue by fara0000** [RocketChat/Rocket.Chat#31980]
Release version: latest
Branch: development
Node version: 14.21.3
npm: 6.14.18
meteor: 2.15

OS: MacOS M1 

**Steps:**
1. yarn 
2. yarn build
3. yarn dsv or dev

**Solution:**
Tried to solve this problem via installing different packages (sharp, sharp for arm and so on) but nothing worked out.
When I running it come to here and then nothing happens, just program stuck, I tried for waiting 30–40 minutes, nothing changes.

Also tried all possible solutions of log about installing verbose, sharp

**Logs:**

@rocket.chat/meteor:dsv: cache bypass, force executing 0b983f2e668e3616
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: > @rocket.chat/meteor@6.7.0-develop dev /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor
@rocket.chat/meteor:dsv: > meteor --exclude-archs "web.browser.legacy, web.cordova"
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: [[[[[ ~/Desktop/myProjects/Rocket.Chat/apps/meteor ]]]]]
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: => Started proxy.                             
@rocket.chat/meteor:dsv: => Started MongoDB.                           
@rocket.chat/meteor:dsv: => Linted your app. No linting errors.        
@rocket.chat/meteor:dsv: W20240313-12:40:08.787(3)? (STDERR) /Users/fakhriimanzade/.meteor/packages/promise/.0.12.2.1p12lm2.cswei++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR)       throw error;
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR)       ^
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR) 
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR) Error: 
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR) Something went wrong installing the "sharp" module
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) 
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) Require stack:
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/sharp.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/constructor.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/index.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/npm-require.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/boot.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/main.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) 
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) Possible solutions:
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) - Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) - Consult the installation documentation: https://sharp.pixelplumbing.com/install
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Object.<anonymous> (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/sharp.js:37:9)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1116:14)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.Mp._compile (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Object.Module._extensions..js (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:981:32)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.Mp.load (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:821:12)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:1005:19)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at require (internal/modules/cjs/helpers.js:107:18)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Object.<anonymous> (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/constructor.js:11:1)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1116:14)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module.Mp._compile (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Object.Module._extensions..js (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:981:32)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module.Mp.load (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:821:12)
@rocket.chat/meteor:dsv: => Exited with code: 1
@rocket.chat/meteor:dsv: => Your application is crashing. Waiting for file change.

**Comment by fara0000** [comment]
**Full logs message:**
**yarn dsv**

╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                  Update available v1.12.4 ≫ v1.12.5                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.12.5    │
│           Run "npx @turbo/codemod@latest update" to update            │
│                                                                       │
│        Follow @turborepo for updates: https://x.com/turborepo         │
╰───────────────────────────────────────────────────────────────────────╯
• Packages in scope: @rocket.chat/account-utils, @rocket.chat/agenda, @rocket.chat/api-client, @rocket.chat/apps, @rocket.chat/base64, @rocket.chat/cas-validate, @rocket.chat/core-services, @rocket.chat/core-typings, @rocket.chat/cron, @rocket.chat/eslint-config, @rocket.chat/favicon, @rocket.chat/fuselage-ui-kit, @rocket.chat/gazzodown, @rocket.chat/i18n, @rocket.chat/instance-status, @rocket.chat/jwt, @rocket.chat/license, @rocket.chat/livechat, @rocket.chat/log-format, @rocket.chat/logger, @rocket.chat/message-parser, @rocket.chat/meteor, @rocket.chat/mock-providers, @rocket.chat/model-typings, @rocket.chat/models, @rocket.chat/omnichannel-services, @rocket.chat/password-policies, @rocket.chat/pdf-worker, @rocket.chat/poplib, @rocket.chat/presence, @rocket.chat/random, @rocket.chat/rest-typings, @rocket.chat/server-cloud-communication, @rocket.chat/server-fetch, @rocket.chat/sha256, @rocket.chat/tools, @rocket.chat/ui-avatar, @rocket.chat/ui-client, @rocket.chat/ui-composer, @rocket.chat/ui-contexts, @rocket.chat/ui-kit, @rocket.chat/ui-theming, @rocket.chat/ui-video-conf, @rocket.chat/web-ui-registration
• Running dsv in 44 packages
• Remote caching disabled
@rocket.chat/log-format:build: cache miss, executing 3eab8dac61e0285b
@rocket.chat/logger:build: cache miss, executing 00c4583f6fbfac48
@rocket.chat/account-utils:build: cache miss, executing 1241d7aee1b874ec
@rocket.chat/favicon:build: cache miss, executing 77de77eb248c1d2c
@rocket.chat/password-policies:build: cache miss, executing d6ecdee4f371ac00
@rocket.chat/cas-validate:build: cache miss, executing 0794688fd1a1d8ea
@rocket.chat/server-fetch:build: cache miss, executing 594d3020d94d9da6
@rocket.chat/agenda:build: cache miss, executing 0602c01ebd84c6e1
@rocket.chat/i18n:build: cache miss, executing dc0ddd4ebe019f5f
@rocket.chat/tools:build: cache miss, executing 2d6bd80a0c6f241e
@rocket.chat/account-utils:build: 
@rocket.chat/logger:build: 
@rocket.chat/log-format:build: 
@rocket.chat/server-fetch:build: 
@rocket.chat/cas-validate:build: 
@rocket.chat/favicon:build: 
@rocket.chat/i18n:build: 
@rocket.chat/agenda:build: 
@rocket.chat/tools:build: 
@rocket.chat/password-policies:build: 
@rocket.chat/i18n:build: 
@rocket.chat/jwt:build: cache miss, executing 4264752128cbef72
@rocket.chat/jwt:build: 
@rocket.chat/password-policies:build: 
@rocket.chat/ui-kit:build: cache miss, executing b040a4050b0355bb
@rocket.chat/ui-kit:build: 
@rocket.chat/tools:build: 
@rocket.chat/ui-composer:build: cache miss, executing 6bfb34811a9f4867
@rocket.chat/ui-composer:build: 
@rocket.chat/log-format:build: 
@rocket.chat/sha256:build: cache miss, executing 5b9f8012f01b9902
@rocket.chat/sha256:build: 
@rocket.chat/logger:build: 
@rocket.chat/base64:build: cache miss, executing 85fbfcad0e978c3f
@rocket.chat/base64:build: 
@rocket.chat/server-fetch:build: 
@rocket.chat/peggy-loader:build: cache miss, executing c7668fbe96ff667f
@rocket.chat/peggy-loader:build: 
@rocket.chat/favicon:build: 
@rocket.chat/random:build: cache miss, executing 6b5559d7f38a5cbf
@rocket.chat/random:build: 
@rocket.chat/agenda:build: 
@rocket.chat/cas-validate:build: 
@rocket.chat/account-utils:build: 
@rocket.chat/ui-kit:build: [!] tsc.js is already patched with the latest version. For details, run: ts-patch check
@rocket.chat/ui-kit:build: [!] typescript.js is already patched with the latest version. For details, run: ts-patch check
@rocket.chat/ui-kit:build: [+] ts-patch installed!
@rocket.chat/ui-kit:build: ----------------------------------------
@rocket.chat/ui-kit:build:  Typia Setup Wizard
@rocket.chat/ui-kit:build: ----------------------------------------
@rocket.chat/ui-kit:build: Since TypeScript v5.3 update, "tsc" no more parses JSDoc comments.
@rocket.chat/ui-kit:build: 
@rocket.chat/ui-kit:build: Therefore, "typia" revives the JSDoc parsing feature by patching "tsc".
@rocket.chat/ui-kit:build: 
@rocket.chat/ui-kit:build: This is a temporary feature of "typia", and it would be removed when "ts-patch" being updated.
@rocket.chat/jwt:build: 
@rocket.chat/sha256:build: 
@rocket.chat/base64:build: 
@rocket.chat/random:build: 
@rocket.chat/ui-composer:build: 
@rocket.chat/peggy-loader:build: 
@rocket.chat/message-parser:build: cache miss, executing 9b6c250514dfcda0
@rocket.chat/message-parser:build: 
@rocket.chat/message-parser:build: asset messageParser.development.js 556 KiB [emitted] (name: main)
@rocket.chat/message-parser:build: runtime modules 937 bytes 4 modules
@rocket.chat/message-parser:build: modules by path ../../node_modules/ 175 KiB
@rocket.chat/message-parser:build:   modules by path ../../node_modules/tldts-core/dist/es6/ 20.4 KiB
@rocket.chat/message-parser:build:     modules by path ../../node_modules/tldts-core/dist/es6/src/*.js 18 KiB 8 modules
@rocket.chat/message-parser:build:     + 2 modules
@rocket.chat/message-parser:build:   modules by path ../../node_modules/tldts/dist/es6/ 154 KiB
@rocket.chat/message-parser:build:     ../../node_modules/tldts/dist/es6/index.js 1.47 KiB [built] [code generated]
@rocket.chat/message-parser:build:     ../../node_modules/tldts/dist/es6/src/suffix-trie.js 2.21 KiB [built] [code generated]
@rocket.chat/message-parser:build:     ../../node_modules/tldts/dist/es6/src/data/trie.js 151 KiB [built] [code generated]
@rocket.chat/message-parser:build: modules by path ./src/ 322 KiB
@rocket.chat/message-parser:build:   ./src/index.ts 257 bytes [built] [code generated]
@rocket.chat/message-parser:build:   ./src/grammar.pegjs 315 KiB [built] [code generated]
@rocket.chat/message-parser:build:   ./src/definitions.ts 11 bytes [built] [code generated]
@rocket.chat/message-parser:build:   ./src/guards.ts 176 bytes [built] [code generated]
@rocket.chat/message-parser:build:   ./src/utils.ts 6.61 KiB [built] [code generated]
@rocket.chat/message-parser:build: webpack 5.78.0 compiled successfully in 13726 ms
@rocket.chat/message-parser:build: 
@rocket.chat/message-parser:build: asset messageParser.production.js 186 KiB [emitted] [minimized] (name: main)
@rocket.chat/message-parser:build: orphan modules 175 KiB [orphan] 15 modules
@rocket.chat/message-parser:build: runtime modules 670 bytes 3 modules
@rocket.chat/message-parser:build: cacheable modules 497 KiB
@rocket.chat/message-parser:build:   ./src/index.ts + 1 modules 433 bytes [built] [code generated]
@rocket.chat/message-parser:build:   ./src/grammar.pegjs 315 KiB [built] [code generated]
@rocket.chat/message-parser:build:   ./src/utils.ts + 13 modules 181 KiB [built] [code generated]
@rocket.chat/message-parser:build: webpack 5.78.0 compiled successfully in 17924 ms
@rocket.chat/message-parser:build: 
@rocket.chat/message-parser:build: asset messageParser.mjs 186 KiB [emitted] [javascript module] [minimized] (name: main)
@rocket.chat/message-parser:build: orphan modules 175 KiB [orphan] 15 modules
@rocket.chat/message-parser:build: runtime modules 670 bytes 3 modules
@rocket.chat/message-parser:build: cacheable modules 497 KiB
@rocket.chat/message-parser:build:   ./src/index.ts + 1 modules 433 bytes [built] [code generated]
@rocket.chat/message-parser:build:   ./src/grammar.pegjs 315 KiB [built] [code generated]
@rocket.chat/message-parser:build:   ./src/utils.ts + 13 modules 181 KiB [built] [code generated]
@rocket.chat/message-parser:build: webpack 5.78.0 compiled successfully in 17452 ms
@rocket.chat/message-parser:build: 
@rocket.chat/message-parser:build: assets by path *.map 7.39 KiB
@rocket.chat/message-parser:build:   asset definitions.d.ts.map 4.77 KiB [emitted]
@rocket.chat/message-parser:build:   asset utils.d.ts.map 1.86 KiB [emitted]
@rocket.chat/message-parser:build:   asset index.d.ts.map 583 bytes [emitted]
@rocket.chat/message-parser:build:   asset guards.d.ts.map 195 bytes [emitted]
@rocket.chat/message-parser:build: assets by path *.ts 7.84 KiB
@rocket.chat/message-parser:build:   asset definitions.d.ts 3.88 KiB [emitted]
@rocket.chat/message-parser:build:   asset utils.d.ts 3.28 KiB [emitted]
@rocket.chat/message-parser:build:   asset index.d.ts 506 bytes [emitted]
@rocket.chat/message-parser:build:   asset guards.d.ts 185 bytes [emitted]
@rocket.chat/message-parser:build: asset messageParser.umd.js 186 KiB [emitted] [minimized] (name: main)
@rocket.chat/message-parser:build: orphan modules 175 KiB [orphan] 15 modules
@rocket.chat/message-parser:build: runtime modules 670 bytes 3 modules
@rocket.chat/message-parser:build: cacheable modules 497 KiB
@rocket.chat/message-parser:build:   ./src/index.ts + 1 modules 433 bytes [built] [code generated]
@rocket.chat/message-parser:build:   ./src/grammar.pegjs 315 KiB [built] [code generated]
@rocket.chat/message-parser:build:   ./src/utils.ts + 13 modules 181 KiB [built] [code generated]
@rocket.chat/message-parser:build: webpack 5.78.0 compiled successfully in 18354 ms
@rocket.chat/core-typings:build: cache miss, executing 3f3afec9b0bfd04d
@rocket.chat/core-typings:build: 
@rocket.chat/core-typings:build: 
@rocket.chat/rest-typings:build: cache miss, executing a4869292ad19a27e
@rocket.chat/pdf-worker:build: cache miss, executing 1d99d0da3c4a0682
@rocket.chat/license:build: cache miss, executing 7e9a432c5b185db5
@rocket.chat/pdf-worker:build: 
@rocket.chat/model-typings:build: cache miss, executing 9fe8a7cdba4758c9
@rocket.chat/rest-typings:build: 
@rocket.chat/license:build: 
@rocket.chat/model-typings:build: 
@rocket.chat/license:build: npm WARN lifecycle The node binary used for scripts is /private/var/folders/k8/zx0dd3dn4g78fszh4nvl0c2h0000gn/T/xfs-c251a9b5/node but npm is using /Users/fakhriimanzade/.nvm/versions/node/v14.21.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
@rocket.chat/license:build: 
@rocket.chat/license:build: > @rocket.chat/license@0.1.5 build:types /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/ee/packages/license
@rocket.chat/license:build: > tsc --emitDeclarationOnly
@rocket.chat/license:build: 
@rocket.chat/license:build: npm WARN lifecycle The node binary used for scripts is /private/var/folders/k8/zx0dd3dn4g78fszh4nvl0c2h0000gn/T/xfs-c251a9b5/node but npm is using /Users/fakhriimanzade/.nvm/versions/node/v14.21.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
@rocket.chat/license:build: 
@rocket.chat/license:build: > @rocket.chat/license@0.1.5 build:js /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/ee/packages/license
@rocket.chat/license:build: > rm -rf dist && tsc -p tsconfig.json
@rocket.chat/license:build: 
@rocket.chat/pdf-worker:build: 
@rocket.chat/model-typings:build: 
@rocket.chat/apps:build: cache miss, executing 29aeccc1b5f6173a
@rocket.chat/models:build: cache miss, executing 70e2b95245d92b7e
@rocket.chat/apps:build: 
@rocket.chat/models:build: 
@rocket.chat/rest-typings:build: 
@rocket.chat/ui-contexts:build: cache miss, executing 6fdf3528f3666c35
@rocket.chat/api-client:build: cache miss, executing c1681ea3f7a0926d
@rocket.chat/ui-contexts:build: 
@rocket.chat/api-client:build: 
@rocket.chat/apps:build: 
@rocket.chat/models:build: 
@rocket.chat/core-services:build: cache miss, executing 7093200df08a447a
@rocket.chat/instance-status:build: cache miss, executing c93311ae291f9db6
@rocket.chat/cron:build: cache miss, executing 616f9a483b43dea6
@rocket.chat/instance-status:build: 
@rocket.chat/cron:build: 
@rocket.chat/core-services:build: 
@rocket.chat/ui-contexts:build: 
@rocket.chat/mock-providers:build: cache miss, executing b74c843365861b44
@rocket.chat/ui-avatar:build: cache miss, executing d94b3860e0396510
@rocket.chat/ui-theming:build: cache miss, executing 0a66326bffb62673
@rocket.chat/mock-providers:build: 
@rocket.chat/ui-avatar:build: 
@rocket.chat/ui-theming:build: 
@rocket.chat/cron:build: 
@rocket.chat/instance-status:build: 
@rocket.chat/api-client:build: 
@rocket.chat/ddp-client:build: cache miss, executing c6af740816b9849f
@rocket.chat/ddp-client:build: 
@rocket.chat/ui-theming:build: 
@rocket.chat/ui-avatar:build: 
@rocket.chat/ui-video-conf:build: cache miss, executing 59b633c745ae2a33
@rocket.chat/ui-video-conf:build: 
@rocket.chat/mock-providers:build: 
@rocket.chat/ui-client:build: cache miss, executing cd42287f966b9dd0
@rocket.chat/ui-client:build: 
@rocket.chat/ddp-client:build: 
@rocket.chat/ui-video-conf:build: 
@rocket.chat/ui-client:build: 
@rocket.chat/web-ui-registration:build: cache miss, executing 2ab4fb50767709fd
@rocket.chat/gazzodown:build: cache miss, executing 4c1742c2644a6018
@rocket.chat/web-ui-registration:build: 
@rocket.chat/gazzodown:build: 
@rocket.chat/core-services:build: 
@rocket.chat/omnichannel-services:build: cache miss, executing 709750ff1aa74115
@rocket.chat/presence:build: cache miss, executing 5d90dd85e8757ce8
@rocket.chat/omnichannel-services:build: 
@rocket.chat/presence:build: 
@rocket.chat/presence:build: 
@rocket.chat/omnichannel-services:build: 
@rocket.chat/gazzodown:build: 
@rocket.chat/fuselage-ui-kit:build: cache miss, executing e16bdcfac3ebf868
@rocket.chat/livechat:build: cache miss, executing ef85c91a0962c9ec
@rocket.chat/livechat:build: 
@rocket.chat/fuselage-ui-kit:build: 
@rocket.chat/web-ui-registration:build: 
@rocket.chat/fuselage-ui-kit:build: 
@rocket.chat/livechat:build: WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
@rocket.chat/livechat:build: This can impact web performance.
@rocket.chat/livechat:build: Assets: 
@rocket.chat/livechat:build:   44490.chunk.b95ee.js (960 KiB)
@rocket.chat/livechat:build:   44088.chunk.4c859.js (648 KiB)
@rocket.chat/livechat:build:   66929.chunk.eeee7.js (259 KiB)
@rocket.chat/livechat:build:   88157.chunk.a6172.js (365 KiB)
@rocket.chat/livechat:build:   33910.chunk.58dcd.js (1.21 MiB)
@rocket.chat/livechat:build:   61652.chunk.792bb.js (951 KiB)
@rocket.chat/livechat:build: 
@rocket.chat/livechat:build: webpack compiled with 1 warning
@rocket.chat/livechat:build: 
@rocket.chat/livechat:build: webpack compiled successfully
@rocket.chat/meteor:dsv: cache bypass, force executing 0b983f2e668e3616
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: > @rocket.chat/meteor@6.7.0-develop dev /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor
@rocket.chat/meteor:dsv: > meteor --exclude-archs "web.browser.legacy, web.cordova"
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: [[[[[ ~/Desktop/myProjects/Rocket.Chat/apps/meteor ]]]]]
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: => Started proxy.                             
@rocket.chat/meteor:dsv: => Started MongoDB.                           
@rocket.chat/meteor:dsv: => Linted your app. No linting errors.        
@rocket.chat/meteor:dsv: W20240313-12:40:08.787(3)? (STDERR) /Users/fakhriimanzade/.meteor/packages/promise/.0.12.2.1p12lm2.cswei++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR)       throw error;
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR)       ^
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR) 
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR) Error: 
@rocket.chat/meteor:dsv: W20240313-12:40:08.821(3)? (STDERR) Something went wrong installing the "sharp" module
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) 
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) Require stack:
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/sharp.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/constructor.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/index.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/npm-require.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/boot.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) - /Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/main.js
@rocket.chat/meteor:dsv: W20240313-12:40:08.822(3)? (STDERR) 
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) Possible solutions:
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) - Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR) - Consult the installation documentation: https://sharp.pixelplumbing.com/install
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Object.<anonymous> (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/sharp.js:37:9)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1116:14)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.Mp._compile (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Object.Module._extensions..js (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:981:32)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.Mp.load (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:821:12)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:1005:19)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at require (internal/modules/cjs/helpers.js:107:18)
@rocket.chat/meteor:dsv: W20240313-12:40:08.823(3)? (STDERR)     at Object.<anonymous> (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/node_modules/sharp/lib/constructor.js:11:1)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1116:14)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module.Mp._compile (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:77:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Object.Module._extensions..js (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:105:23)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:981:32)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Module.Mp.load (/Users/fakhriimanzade/Desktop/myProjects/Rocket.Chat/apps/meteor/.meteor/local/build/programs/server/runtime.js:37:33)
@rocket.chat/meteor:dsv: W20240313-12:40:08.824(3)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:821:12)
@rocket.chat/meteor:dsv: => Exited with code: 1
@rocket.chat/meteor:dsv: => Your application is crashing. Waiting for file change.

**Comment by ridsync** [comment]
@fara0000 
meteor is having issues with rosetta on m1. Please refer to the following guide when installing and reinstalling meteor and you should be able to resolve the issue.

https://docs.meteor.com/install.html#old-versions-m1

**Comment by reetp** [comment]
OK, 
On my Mac M1 yesterday:

```
brew install nvm
nano ~/.zshrc`
```

Add

```  
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
```

Exit the terminal and create a new one.

`nvm install 14.21.3`

Get a coffee/beer/wine depending on your time of day.

Then: 

```
npm install -g yarn
npm install -g meteor
export PATH=/Users/$youruser/.meteor:$PATH
cd ~git/Rocket.Chat
cd apps/meteor
meteor --version
cd ../..
yarn dsv
```

And a few minutes later I had a running rocket on http://127.0.0.1:3000 !!

Dev docs need updating (in hand).

This is a support issue so please follow up at https://open.rocket.chat or https://forums.rocket.chat
