### ISSUE TITLE
"Register your Workspace" Wizard is unskippable since 6.6.x? 

### ISSUE THREAD

**Issue by amsnek** [RocketChat/Rocket.Chat#31982]
### Description:

After Upgrading from 6.5 -> 6.6 it seems that the Wizard "Register your workspace" is unsippable? Can Rocket.Chat now only be used with an online registration? 
In 6.5 one could still skip this by setting the environment variable:
OVERWRITE_SETTING_Show_Setup_Wizard="completed"

### Steps to reproduce:

1. Upgrade to 6.6.x
2. Attempt to login on https://<rocket.chat.url> as admin

### Expected behavior:

Login allowed / no forced registration required

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/73526449/31c19b4f-9a18-44cd-aca3-14a3cdd7b63d)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.3
- Operating System: Linux
- Deployment Method: custom
- Number of Running Instances: 1

**Comment by Gummikavalier** [comment]
Please try also:
```
db.rocketchat_settings.update({"_id":"Show_Setup_Wizard"}, {$set: {"value" : "completed"} });
```
in the mongo shell. Worked for me when I was troubleshooting licensing and support issues.

**Comment by amsnek** [comment]
Thanks a lot @Gummikavalier!
You are awesome, that worked as intendended.
