### ISSUE TITLE
Нет прав для открытия аттачмента

### ISSUE THREAD

**Issue by AleksBulatov** [RocketChat/Rocket.Chat#31988]
Мне в личной переписке в рокетчате прислали xlsx-файл.
При попытке открыть его (при клике на него) получаю ответ:
----------
Доступ к rocketchat.samokat.ru запрещен У вас нет прав для просмотра этой страницы.
HTTP ERROR 403
----------
VPN самоката, есди он для этого требуется, включен.

**Comment by reetp** [comment]
Sorry but you need to speak in English and complete a bug template.
