### ISSUE TITLE
When not-member user is mentioned, browser tab freezes

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat#31991]
### Description:

In some cases, when a user who is not a member is mentioned, the browser tab freezes
![freeze](https://github.com/RocketChat/Rocket.Chat/assets/666827/938e731e-de43-4ca6-b6df-a4c647393e56)

### Steps to reproduce:

1. Go to any public/private/team room
2. Mention in message a user who is not a member of this room
3. Send message

### Expected behavior:

The message is sent, and in version >=6.6.3 notification received from rocket.cat that the user is not a member.

### Actual behavior:

The message is sent, browser tab freezes.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.6.3 Enterprise 
- Operating System: Oracle Linux Server release 8.6
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 122.0.6261, 120.0.6099; Rocket.Chat Electron 3.9.9, 3.9.14
- Operating System: Windows

### Relevant logs:

No errors in Chrome console while tab frozen

**Comment by preeesha** [comment]
Hey @shiryov, thanks for reporting the issue. Do you face this problem on the browser as well or it's just limited to the electron app?

**Comment by shiryov** [comment]
Hello
This Issue reproduced both in the Chrome browser and in Electron app 3.9.9,
3.9.14

пт, 15 мар. 2024 г., 03:57 Prisha Gupta ***@***.***>:

**Comment by MarlynxLinux** [comment]
Hello!
I confirm that I have the same problem, it has appeared since version 6.6.0

Developers Rocket.Chat please fix it

**Comment by gelpiu-developers** [comment]
+1. Reported also here #32127

**Comment by reetp** [comment]
Can you try on 6.8.or 6.9 with latest browsers please?

If you are on EE you can open a support request.

**Comment by shiryov** [comment]
@reetp On 6.8.0 everything is fine, this issue did not reproduce
