### ISSUE TITLE
Pre-process messages to allow plugin developers to add their own /commands

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#32]

**Comment by marceloschmidt** [comment]
Thought about having a list of pre-processors and enabling plugins to register pre-processors. Then, before saving the message to the database, call each processor with the return statement of the previous processor. There should also be some way for defining plugin priorities.

**Comment by engelgabriel** [comment]
+1

**Comment by marceloschmidt** [comment]
Adds the possibility of inline pasting code

**Comment by engelgabriel** [comment]
@marceloschmidt finished this already.
