### ISSUE TITLE
User/Global translation not working most of the time

### ISSUE THREAD

**Issue by fliespl** [RocketChat/Rocket.Chat#32008]
### Description:

User selected translation not working most of the time (defaults to english).

### Steps to reproduce:

Change default language (user or global) to something other than english (polish in my case).

Do reload the page a few times - it's rendered in english.

### Expected behavior:

Proper language displayed.

### Actual behavior:

Even though language file is being loaded - UI is rendered with English.

### Server Setup Information:
Official docker setup - 6.6.3

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Docker

**Comment by MarlynxLinux** [comment]
Hello!
I confirm that I have the same problem, it has appeared since version 6.6.0

Steps to reproduce:
1. Workspace > Setting > General
2. For the "Language" value, set any language (I choose Russian) and apply the changes
3. Refresh the page in the browser or reload the server tab in the desktop application, the interface language will change to English

Server Setup Information:
- Version of Rocket.Chat Server: 6.6.3
- Plan: Enterprise
- Operating System: Ubuntu 20.04
- Deployment Method: manual install (Deploy with Ubuntu)
- Number of Running Instances: 1
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

Client Setup Information:
- Desktop App or Browser Version: 3.9.14
- Operating System: Windows/Linux/MacOS

**Comment by robinreckmann** [comment]
Same here since version 6.6.0, currently on 6.6.3. 

It seems like the language is correctly loaded whenever you login for the first time, then on each subsequent refresh the language is set to English, no matter which language is specified in the preferences.

When you logout with user A, then login with user B, logout and login user A again, the correct language will be displayed, but only until the first refresh while being logged in.

**Comment by alexhaiduk** [comment]
We has the same problem about localization.

Steps to reproduce:
    Workspace > Setting > General
    For the "Language" value, set any language (I choose Russian) and apply the changes
    Refresh the page in the browser or reload the server tab in the desktop application, the interface language will change to English

Server Setup Information:
    Rocket.Chat Server: v6.6.3
    Plan: Community
    Operating System: Debian 11.6
    Deployment Method: manual install (Deploy on Debian)
    Number of Running Instances: 1
    NodeJS Version: 14.21.3
    MongoDB: v5.0.15

Client Setup Information: any client, but not Android app and iOS app

We found in Logs this:
```json
{"level":35,"time":"2024-03-19T06:35:03.920Z","pid":39658,"hostname":"tst-chat4","name":"Meteor","method":"autoTranslate.getSupportedLanguages","userId":"tHSrxxxq29P6piuXn","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0","referer":"https://tst-chat4.domain.com/home","remoteIP":"1.1.1.1","instanceId":"0fc46296-6a55-4042-999d-d5ecb7ccfeb0"} Exception while invoking method autoTranslate.getSupportedLanguages errorClass [Error]: Auto-Translate is disabled [error-autotranslate-disabled]     at app/autotranslate/server/methods/getSupportedLanguages.ts:20:10     at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at packages/meteor.js:367:22     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)     at packages/ddp-server/livedata_server.js:1854:36     at new Promise (<anonymous>)     at Server.applyAsync (packages/ddp-server/livedata_server.js:1853:12)     at Server.callAsync (packages/ddp-server/livedata_server.js:1779:17)     at app/api/server/v1/misc.ts:561:33     at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/api/server/v1/misc.ts:561:17     at /opt/rocket.chat-latest/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {   isClientSafe: true,   error: 'error-autotranslate-disabled',   reason: 'Auto-Translate is disabled',   details: undefined,   errorType: 'Meteor.Error' }

{"level":35,"time":"2024-03-19T06:35:03.925Z","pid":39658,"hostname":"tst-chat4","name":"API","method":"POST","url":"/api/v1/method.call/autoTranslate.getSupportedLanguages","userId":"tHSrxxxq29P6piuXn","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0","length":"119","host":"localhost:3000","referer":"https://tst-chat4.domain.com/home","remoteIP":"1.1.1.1","status":200,"responseTime":6}
```

**Comment by TF-R** [comment]
Same here:

Server Setup Information:

    Version of Rocket.Chat Server: 6.6.3
    Plan: Enterprise
    Operating System: Ubuntu 22.04
    Deployment Method: Docker
    Number of Running Instances: 14
    NodeJS Version: v14.21.3
    MongoDB Version: 5.0.25 / wiredTiger (oplog Enabled)

**Comment by satvik2131** [comment]
Hi , I am trying to work on this issue and searching codebase and discovered some of the files as well , but I am not able to find the file which is responsible for selecting the language for the whole app , please can anyone guide me with this ?? @fliespl

**Comment by satvik2131** [comment]
Hi , I have tried to work on the issue and I thought that this is the issue from the backend . The backend keeps returning "en" when application starts even after setting it to other language

**Comment by gabriellsh** [comment]
A new issue was created for the second part of this issue
See https://github.com/RocketChat/Rocket.Chat/issues/32268
Once again thanks for contributing!
