### ISSUE TITLE
Unable to login using Android client and CAS plugin

### ISSUE THREAD

**Issue by s19n** [RocketChat/Rocket.Chat#3200]
Your Rocket.Chat version: 0.29
When trying to login via CAS using the Android app, the login page is correctly shown but after providing username and password a blank page is shown (see attached screenshot).

Everything works correctly when using a browser.
![cas_login_attempt](https://cloud.githubusercontent.com/assets/1647955/15181259/8485a598-1786-11e6-97eb-1b324f50ea45.png)

**Comment by geekgonecrazy** [comment]
Does this only effect the mobile application or does this happen when doing mobile web also?

**Comment by s19n** [comment]
The issue affects the mobile application only. No issues while using Chrome or Firefox for Android.

**Comment by genesplicer** [comment]
Can confirm. I have the same issue.

**Comment by ajwinter** [comment]
Pull request created. Anyone that can test, please do so!

**Comment by s17t** [comment]
Updated to 0.33.0 and the CAS login works again, thank you!
