### ISSUE TITLE
Mail notifications show "undefined" as channel when triggered by LiveChat

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#3201]
Your Rocket.Chat version: demo instance

![bildschirmfoto 2016-05-11 um 16 41 45](https://cloud.githubusercontent.com/assets/944459/15184897/46d6ed22-1797-11e6-8464-f35c59ede81c.png)

**Comment by geekgonecrazy** [comment]
so you were notified in a livechat session when offline?  Seems like that shouldn't have been possible.  Maybe livechat we should disable mentioning?

**Comment by frdmn** [comment]
To be honest, I'm not sure how I received those. 

I am certain that I didn't disabled the LiveChat, but perhaps my Mac went to sleep or something and disconnected me from RC.

Should LiveChat never generate notifications?

**Comment by geekgonecrazy** [comment]
We're implementing an offline message form they can submit when no user is online.  That will send an email.  But mentioning I don't think should be..

**Comment by frdmn** [comment]
I still receive a lot of LiveChat notifications. The setup is usually the following:

* I set myself online available as LiveChat agent
* I leave my Mac, so the client probably sets myself to unavailable or something like that
* Visitors now open a new chat via the LiveChat widget and any message now generates a mail notification
