### ISSUE TITLE
Rocket.chat desktop notifications are disabled

### ISSUE THREAD

**Issue by 443798686** [RocketChat/Rocket.Chat#32014]
The desktop notifications for the installed Rocket.chat program have been disabled, whereas logging in via the browser does not have this issue. Additionally, multiple reloads occasionally enable desktop notifications, And there is no problem with the test. The settings in the browser, system notifications, and internal settings of the software have all been checked and are fine; it is unclear what is causing this problem.

**Comment by Visbhavesh** [comment]
I wanted to work in thus issue please Assign this issue to me.

**Comment by reetp** [comment]
If the OP still has issues please open a new bug and complete a bug template.

> I wanted to work in thus issue please Assign this issue to me.

[Visbhavesh](https://github.com/Visbhavesh) No one is going to assign issues. Please work on what you want to.
