### ISSUE TITLE
Not closing the notification limit window

### ISSUE THREAD

**Issue by Danchik97** [RocketChat/Rocket.Chat#32028]
I can't close the window!

Workspace members are not receiving notifications on mobile
Your plan's monthly mobile notification limit has been reached.

Notifications are coming in, everything is working. This window occupies half of the screen. It appears only in the admin panel. When trying to close it - connection timeout.
Version Rocket.Chat server 6.5.2
![image](https://github.com/RocketChat/Rocket.Chat/assets/163991473/6097db02-91d0-4279-b865-c975a8968ec3)

**Comment by Ritesh92A** [comment]
Hey I think this issue and issue no.- 32018 is same and I want to solve this. Please assign this to me.

**Comment by grzebo** [comment]
I have the same issue. My workspace is over the notification limit, but I cannot close the banner, clicking on the "X" does nothing.

I'm on version 6.6.4

**Comment by grzebo** [comment]
You're right! Clicking it multiple times (more like 200+ for me) made it disappear. Still a bug though.

**Comment by rituraj12797** [comment]
trying it

**Comment by grzebo** [comment]
Here's how to disable all the banners:
https://github.com/RocketChat/Rocket.Chat/issues/31893#issuecomment-2011986117

**Comment by reetp** [comment]
Please test this on latest 6.9.x and let us know what happens.

If you are using CE then note the push notification limit is 10,000 per month.

**Comment by vymyk** [comment]
This is still an issue on 7.10.0. How can I help to actually solve this and not just disable all banners in the db? :)

**Comment by reetp** [comment]
> This is still an issue on 7.10.0. How can I help to actually solve this and not just disable all banners in the db? :)

Presume this is limits to push notifications?


Disable push or run your own push server so you don't exceed your limits?

**Comment by vymyk** [comment]
> > This is still an issue on 7.10.0. How can I help to actually solve this and not just disable all banners in the db? :)
> 
> Presume this is limits tl oush notificstions?
> 
> Disable push or run your own push server so you don't exceed your limits?

The issue isn't about the limit itself. The notification banner is not going away when clicking/spamming the X.

**Comment by reetp** [comment]
Probably related to this.

https://github.com/RocketChat/Rocket.Chat/issues/32018

**Comment by sukit-hg** [comment]
Custom css can resolve. 
.rcx-banner.rcx-banner--warning {
    display: none !important;
}
For me it work. (v7.10.0)
