### ISSUE TITLE
"PermissionDeniedError" "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."

### ISSUE THREAD

**Issue by gregoirelemoulant** [RocketChat/Rocket.Chat#3202]
Hello,
I have installed rocketchat thanks to docker, everything is working fine but the video and call are not working. My Chrome console report this : NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}

I reach my server via http public network in local. 

Do you think I need to moove to https ? and is there any documentation to make it via docker ?

Thanks

**Comment by geekgonecrazy** [comment]
check your Site URL in your settings and ensure that its set to have https:// in the url.  I'm guessing you set this up over http, and then added your https and did a redirect.

**Comment by gregoirelemoulant** [comment]
I changed the site url.  But what do you mean by "added your https and did a redirect."  ? thanks

**Comment by geekgonecrazy** [comment]
I mean that out of the box rocket.chat is going to listen to an address like this: `http://host:3000`

So to get https you had to have added nginx or something in front of it.  At that level typically is when you redirect from http://host to https://host  So you need to verify that your site URL is exactly what the URL will be after the redirect.

**Comment by gregoirelemoulant** [comment]
yes it works thank you !!

**Comment by geekgonecrazy** [comment]
👍  good deal!  Feel free to join us on our demo server [#support](https://demo.rocket.chat/channel/support)

**Comment by sirius2013** [comment]
Hi. I got same issue.
so it is impossible to make working on http server?

**Comment by geekgonecrazy** [comment]
@sirius2013 no many have had it successfully work over http.  Please visit: [#support](https://demo.rocket.chat/channel/support)

**Comment by leizard** [comment]
Hi @geekgonecrazy @sirius2013 do you guys work out the issue ? It seems like it still exist with the Cordova app, I can't make the camera/video work on Android
