### ISSUE TITLE
[Bug]: Livechat - Calling `registerGuest()` method with existing set token causes blank chat

### ISSUE THREAD

**Issue by harvard1932** [RocketChat/Rocket.Chat#32042]
Running into exact issue on the latest version 6.6.4 as mentioned in https://forums.rocket.chat/t/issue-blank-chats/19092

**Comment by MartinSchoeler** [comment]
Hello @harvard1932 can you give us more info?

Where exactly is the chat history blank? In the livechat widget or in the main Rocket.Chat view?

Do you have any errors on your browser console?

What exatly are the steps to reproduce the issue?

Thanks!

**Comment by Visbhavesh** [comment]
I wanted to work in thus issue please Assign this issue to me.

**Comment by harvard1932** [comment]
> Hello @harvard1932 can you give us more info?
> 
> Where exactly is the chat history blank? In the livechat widget or in the main Rocket.Chat view?
> 
> Do you have any errors on your browser console?
> 
> What exatly are the steps to reproduce the issue?
> 
> Thanks!

The issue is that javascript call to add chat information like customer name, email, etc. Would trigger the chat history to disappear on 
![image](https://github.com/RocketChat/Rocket.Chat/assets/1342903/63fbab80-bdd2-410c-95de-4c51db5b82dd)

basically overwriting older call on 
![image](https://github.com/RocketChat/Rocket.Chat/assets/1342903/5c6bbee8-76af-4c6e-ba20-c59431b6aa88)

which populates chat history.

**Comment by harvard1932** [comment]
> I wanted to work in thus issue please Assign this issue to me.

I have added some replication information on this bug

**Comment by Visbhavesh** [comment]
> > I wanted to work in thus issue please Assign this issue to me.
> 
> I have added some replication information on this bug

sure assign it to me and I look into it

**Comment by MartinSchoeler** [comment]
@Visbhavesh no need for assignment, if you find something you want to work on, feel free to work on it and create a PR

**Comment by MartinSchoeler** [comment]
> > Hello @harvard1932 can you give us more info?
> > Where exactly is the chat history blank? In the livechat widget or in the main Rocket.Chat view?
> > Do you have any errors on your browser console?
> > What exatly are the steps to reproduce the issue?
> > Thanks!
> 
> The issue is that javascript call to add chat information like customer name, email, etc. Would trigger the chat history to disappear on ![image](https://private-user-images.githubusercontent.com/1342903/315899551-63fbab80-bdd2-410c-95de-4c51db5b82dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU3OTgsIm5iZiI6MTcxMTEwNTQ5OCwicGF0aCI6Ii8xMzQyOTAzLzMxNTg5OTU1MS02M2ZiYWI4MC1iZGQyLTQxMGMtOTVkZS00YzUxZGI1YjgyZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTEwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE2M2QxYjMzMTc4Yzk2NTFmOTA4N2Q3NjIwMzBiMWRiOTcwNGQzNDc1ZDVhNDkyODU4ZmM4NzA5YTEyYWIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7AKoBuvBPkFagbV80McqftNHdn_4gWbzKnRoN9d3cLg)
> 
> basically overwriting older call on ![image](https://private-user-images.githubusercontent.com/1342903/315899713-5c6bbee8-76af-4c6e-ba20-c59431b6aa88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU3OTgsIm5iZiI6MTcxMTEwNTQ5OCwicGF0aCI6Ii8xMzQyOTAzLzMxNTg5OTcxMy01YzZiYmVlOC03NmFmLTRjNmUtYmEyMC1jNTk0MzFiNmFhODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTEwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY5NmJkZTAzYjZiMzYzYjM0N2E0MTJjZWE0MDNjY2QzYWIxYzg3MTNlMjQ0YmI4MDdmNDk4MjlkMGRiZjIwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8c3xstXbWrD2PoQfvkpevlsCU86xkTkHSs8NujNQxYY)
> 
> which populates chat history.

Ahh it seems that a livechat API call is overriding your livechat guest token and another conversation is being started (if you send a message in this empty chat you'll see that it creates another conversation as another guest). Some calls like `registerGuest()` and `setToken()` can cause that. Also, if you call `registerGuest()` while having the said guest already logged, that causes an empty screen, that is a bug that's being worked on.

If you need more help with this you'll probably have to share your script (or something similar to what are you doing) that calls the livechat API endpoints

Cheers!

**Comment by Visbhavesh** [comment]
> > > Hello @harvard1932 can you give us more info?
> > > Where exactly is the chat history blank? In the livechat widget or in the main Rocket.Chat view?
> > > Do you have any errors on your browser console?
> > > What exatly are the steps to reproduce the issue?
> > > Thanks!
> > 
> > 
> > The issue is that javascript call to add chat information like customer name, email, etc. Would trigger the chat history to disappear on ![image](https://private-user-images.githubusercontent.com/1342903/315899551-63fbab80-bdd2-410c-95de-4c51db5b82dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU3OTgsIm5iZiI6MTcxMTEwNTQ5OCwicGF0aCI6Ii8xMzQyOTAzLzMxNTg5OTU1MS02M2ZiYWI4MC1iZGQyLTQxMGMtOTVkZS00YzUxZGI1YjgyZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTEwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE2M2QxYjMzMTc4Yzk2NTFmOTA4N2Q3NjIwMzBiMWRiOTcwNGQzNDc1ZDVhNDkyODU4ZmM4NzA5YTEyYWIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7AKoBuvBPkFagbV80McqftNHdn_4gWbzKnRoN9d3cLg)
> > basically overwriting older call on ![image](https://private-user-images.githubusercontent.com/1342903/315899713-5c6bbee8-76af-4c6e-ba20-c59431b6aa88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU3OTgsIm5iZiI6MTcxMTEwNTQ5OCwicGF0aCI6Ii8xMzQyOTAzLzMxNTg5OTcxMy01YzZiYmVlOC03NmFmLTRjNmUtYmEyMC1jNTk0MzFiNmFhODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTEwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY5NmJkZTAzYjZiMzYzYjM0N2E0MTJjZWE0MDNjY2QzYWIxYzg3MTNlMjQ0YmI4MDdmNDk4MjlkMGRiZjIwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8c3xstXbWrD2PoQfvkpevlsCU86xkTkHSs8NujNQxYY)
> > which populates chat history.
> 
> Ahh it seems that a livechat API call is overriding your livechat guest token and another conversation is being started (if you send a message in this empty chat you'll see that it creates another conversation as another guest). Some calls like `registerGuest()` and `setToken()` can cause that. Also, if you call `registerGuest()` while having the said guest already logged, that causes an empty screen, that is a bug that's being worked on.
> 
> If you need more help with this you'll probably have to share your script (or something similar to what are you doing) that calls the livechat API endpoints
> 
> Cheers!

 to ensure it 

Check API Call Order: Review your script and ensure you're not calling registerGuest() and setToken() consecutively.
Conditional Logic for registerGuest(): Implement a check before calling registerGuest(). If the guest is already registered, skip this call.
Await Bug Fix: If the issue is confirmed as a bug, consider waiting for a fix from the livechat API provider. In the meantime, you can implement a temporary workaround using the conditional logic mentioned above.

**Comment by harvard1932** [comment]
> > > > Hello @harvard1932 can you give us more info?
> > > > Where exactly is the chat history blank? In the livechat widget or in the main Rocket.Chat view?
> > > > Do you have any errors on your browser console?
> > > > What exatly are the steps to reproduce the issue?
> > > > Thanks!
> > > 
> > > 
> > > The issue is that javascript call to add chat information like customer name, email, etc. Would trigger the chat history to disappear on ![image](https://private-user-images.githubusercontent.com/1342903/315899551-63fbab80-bdd2-410c-95de-4c51db5b82dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU3OTgsIm5iZiI6MTcxMTEwNTQ5OCwicGF0aCI6Ii8xMzQyOTAzLzMxNTg5OTU1MS02M2ZiYWI4MC1iZGQyLTQxMGMtOTVkZS00YzUxZGI1YjgyZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTEwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE2M2QxYjMzMTc4Yzk2NTFmOTA4N2Q3NjIwMzBiMWRiOTcwNGQzNDc1ZDVhNDkyODU4ZmM4NzA5YTEyYWIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7AKoBuvBPkFagbV80McqftNHdn_4gWbzKnRoN9d3cLg)
> > > basically overwriting older call on ![image](https://private-user-images.githubusercontent.com/1342903/315899713-5c6bbee8-76af-4c6e-ba20-c59431b6aa88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDU3OTgsIm5iZiI6MTcxMTEwNTQ5OCwicGF0aCI6Ii8xMzQyOTAzLzMxNTg5OTcxMy01YzZiYmVlOC03NmFmLTRjNmUtYmEyMC1jNTk0MzFiNmFhODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTEwNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY5NmJkZTAzYjZiMzYzYjM0N2E0MTJjZWE0MDNjY2QzYWIxYzg3MTNlMjQ0YmI4MDdmNDk4MjlkMGRiZjIwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8c3xstXbWrD2PoQfvkpevlsCU86xkTkHSs8NujNQxYY)
> > > which populates chat history.
> > 
> > 
> > Ahh it seems that a livechat API call is overriding your livechat guest token and another conversation is being started (if you send a message in this empty chat you'll see that it creates another conversation as another guest). Some calls like `registerGuest()` and `setToken()` can cause that. Also, if you call `registerGuest()` while having the said guest already logged, that causes an empty screen, that is a bug that's being worked on.
> > If you need more help with this you'll probably have to share your script (or something similar to what are you doing) that calls the livechat API endpoints
> > Cheers!
> 
> to ensure it
> 
> Check API Call Order: Review your script and ensure you're not calling registerGuest() and setToken() consecutively. Conditional Logic for registerGuest(): Implement a check before calling registerGuest(). If the guest is already registered, skip this call. Await Bug Fix: If the issue is confirmed as a bug, consider waiting for a fix from the livechat API provider. In the meantime, you can implement a temporary workaround using the conditional logic mentioned above.

Currently we are using:

    this.initialize({
        theme: {
            color: '#d681f8',
            fontColor: '#FFFFFF',
            iconColor: '#1d74f5',
            title: "Chat",
           offlineTitle: "Server Updating",
        },
        department: '<?php echo $_SESSION["x"]; ?>',
        guestToken: '<?php echo $_SESSION["x"]; ?>',
        language: 'en',
  });

    this.registerGuest({
        token: '<?php echo $_SESSION["x"]; ?>', // The token field is not required. If it is not passed, a new token will be generated
        name: js_variable_name,
        email: '<?php echo $_SESSION["x"]; ?>@x.com',
        customFields: [ // The customFields field is not required. If it is passed it needs to be an Array, where each item needs to be an object with key and value fields
            {key:  'membership', value: '<?php echo $y; ?>', overwrite: true},
            {key:  'ID', value: '<?php echo $x; ?>', overwrite: true}
        ]
    });

because this.initialize doesnt have any official doc on being able to contain customfields.
And on rocketchat js API there isn't a way to check if registerGuest already registered or not, unless I am missing something.

Thank you so much for your help! This only became of an issue in latest 6.6.4, and it wasn't really an issue in earlier versions.

**Comment by MartinSchoeler** [comment]
@harvard1932 

Yeah, you might be setting the the `guestToken` twice and that is causing the bug, while the fix is not out as a work around you could do something like 
```
var token = '<?php echo $_SESSION["x"]; ?>'
if (window.localStorage.store.includes(`"token": "${ token }"`)) {
    this.registerGuest({"your guest data here"})
}
```
I would also suggest removing the token from ´initialize´ as it is already being set by registerGuest

This will prevent the register guest to be called when the exact same token is already set on localstorage

Hope this helps!
Thanks!

**Comment by harvard1932** [comment]
> @harvard1932
> 
> Yeah, you might be setting the the `guestToken` twice and that is causing the bug, while the fix is not out as a work around you could do something like
> 
> ```
> var token = '<?php echo $_SESSION["x"]; ?>'
> if (!window.localStorage.store.includes(`"token": "${ token }"`)) {
>     this.registerGuest({"your guest data here"})
> }
> ```
> 
> I would also suggest removing the token from `initialize` as it is already being set by registerGuest
> 
> This will prevent the register guest to be called when the exact same token is already set on localstorage
> 
> Hope this helps! Thanks!

Well.. Because we use the live chat from another domain, it wouldnt have access to the localstorage of the rocketchat server due to cross site limitation. It would still be better suited for rocket chat to fix the issue from the core, or add additional javascript API that allows for checking if guest token exists.
