### ISSUE TITLE
No access to market place

### ISSUE THREAD

**Issue by eyck** [RocketChat/Rocket.Chat#32053]
### Description:

When accessing marketplace an error message is shown 'Could not reach Marketplace'. The server logs show
```
rocketchat_1          | {"level":40,"time":"2024-03-22T06:24:14.718Z","pid":24,"hostname":"xxxx","name":"Rocket.Chat Apps","msg":"Unable to access Marketplace. Does the server has access to the internet? 'invalid json response body at https://marketplace.rocket.chat/v1/categories reason: Unexpected token < in JSON at position 0'"}
```

The server has access to the internet and the marketplace (tested with traceroute). When fetching the URL using `curl -H "Accept: application/json" https://marketplace.rocket.chat/v1/categories` the result is a normal HTML document, not the expected JSON...

### Steps to reproduce:

1. Go to 'Administration -> Marketplace' -->
![grafik](https://github.com/RocketChat/Rocket.Chat/assets/437271/21a2fe5d-801e-48b6-ba8e-4e509ac253da)

### Expected behavior:

Show available marketplace apps

### Actual behavior:

Error message

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.5
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.25

### Client Setup Information

- Firefox 124.0
- Win 11

**Comment by inattendu** [comment]
same issue 
`mars 22 12:12:51 chat rocketchat[343627]: {"level":40,"time":"2024-03-22T11:12:51.395Z","pid":343627,"hostname":"chat","name":"Rocket.Chat Apps","msg":"Unable to access Marketplace. Does the server has access to the internet? 'invalid json response body at https://marketplace.rocket.chat/v1/categories reason: Unexpected token < in JSON at position 0'"}
`

**Comment by railsmechanic** [comment]
Same here...

**Comment by Gummikavalier** [comment]
Same. Also with an enterprise license.

**Comment by railsmechanic** [comment]
Seems to be working again. 🤷‍♂️

**Comment by eyck** [comment]
yes
