### ISSUE TITLE
OpenAI Stream API through Websocket (Python

### ISSUE THREAD

**Issue by rsilveira79** [RocketChat/Rocket.Chat#32079]
### Description:

Hello
I'm trying to stream a message that I'm receving from OpenAI stream API (receiving one token each time, to have the same feeling as ChatGPT (in which the message keeps being written).

I'm using the following code to do that (using python `websockets`), however I couldn't figure out a wait to make the messages appear in the same line (the seem to all go to a line break, even though the token itself doesn't containt a line break.

Can someone help with that?

```python
openai_response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "system", "content": "You are a helpful assistant - Make fun of user request."},
                    {"role": "user", "content": msg}],
        stream=True)
for i,chunk in enumerate(openai_response):
    if chunk.choices[0].delta.content is not None:
        token = chunk.choices[0].delta.content
        accumulated_response += token
        response_message = {
                "msg": "method",
                "method": "sendMessage",
                "id": str(generate_random_ids(3)),
                "params": [
                    {
                        "_id": str(generate_random_ids(20)),
                        "rid": str(room_id),  # The room ID to send the message to
                        "msg": token
                    }
                ]
            }
        ws.send(json.dumps(response_message))
```
In this case, **ws** is my websocket, and I react to that even when I'm receiving a message from the user `on_message`

```python
ws = websocket.WebSocketApp("ws://localhost:3000/websocket",
                            on_open=on_open,
                            on_message=on_message,
                            on_error=on_error,
                            on_close=on_close)
```

The effect I'm getting is as shown in the screenshot below:
<img width="509" alt="Screenshot 2024-03-27 at 12 54 32 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/11993881/0a13b016-1b8f-4292-8068-ee6807d60d69">

**Comment by hardikbhatia777** [comment]
Hi

Your code seems to be sending data via the websocket for every word in the OpenAI response. Declaring the `accumulated_response` variable before the loop and sending the message after the loop ends should solve your problem.

```
# Initialize a variable to store the response 
accumulated_response = ""

openai_response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a helpful assistant - Make fun of user request."},
        {"role": "user", "content": msg}
    ],
    stream=True
)

# Accumulate response chunks for the response
for i, chunk in enumerate(openai_response):
    if chunk.choices[0].delta.content is not None:
        token = chunk.choices[0].delta.content
        accumulated_response += token

# Send them as one single message, this will avoid the response being split into different lines
response_message = {
    "msg": "method",
    "method": "sendMessage",
    "id": str(generate_random_ids(3)),
    "params": [
        {
            "_id": str(generate_random_ids(20)),
            "rid": str(room_id),  # The room ID to send the message to
            "msg": accumulated_response  # Send accumulated response
        }
    ]
}

ws.send(json.dumps(response_message))

# Optional depending on your code, clearing the response may help in some cases? 
accumulated_response = ""

```  

This isn't exactly a problem with Rocket.Chat, but hope this helps :)

**Comment by rsilveira79** [comment]
Hi
Thanks for sending a reply.
Actually I wanted the effect of updating the message every received token,
same as when you use OpenAI. For sorter replies I could wait until the end
of the loop, for for longer answers the user will be waiting without an
update which is not ideal.
I could use Server Sent Events but looks like RocketChat doesn’t support.
I was able to get the effect by using send message and update message but
it’s seems like a hack now .

*Roberto Pereira Silveira*
📱 +1 (551) 263 2125

**Comment by dyogaharshitha** [comment]
@rsilveira79 
I would like to work on it

**Comment by dyogaharshitha** [comment]
.take

**Comment by sporqist** [comment]
Afaik there is no intended way of doing something like this in Rocket.Chat but your approach could work. I'd start with defining a minimum chunk size to improve performance. I think calling `updateMessage` every 8 words or so would help performance a lot.

Be aware that each `updateMessage`-call will result in a write to your db.

**Comment by reetp** [comment]
This is a support issue and not a bug in Rocket.Chat

Please ask for help in https://open.rocket.chat or https://forums.rocket.chat

If you go to open you can ask about AI and there are some AI groups there you can join.
