### ISSUE TITLE
E2E key on Mibile devices (IOS)

### ISSUE THREAD

**Issue by Taz-Hubelia** [RocketChat/Rocket.Chat#32082]
### Description:

Hi,

Some of our Users are having an issue where when they login to their IOS mobile app, it never prompts them to enter the E2E key so they cant decrypt their messages on their phones and access their conversations...

We have tried reinstalling the app, and logging out and back in of the account.
It seems to be working normally on Android though as I didn't have this issue on my android phone.

Please provide guidance on this issue.

Thanks,
Taz

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: workspace Version 6.6.0
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: IOS

**Comment by reetp** [comment]
This would likely be a react issue.

Please test on the latest version of Rocket and if it still occurs, open a bug in the react native repo.
