### ISSUE TITLE
Unexpected Markdown Behavior in Custom Status: Bold  Formatting Not Working as Expected

### ISSUE THREAD

**Issue by CyberStranger** [RocketChat/Rocket.Chat#32081]
### Description:

When setting a Custom Status in RocketChat, I am experiencing unexpected behavior with markdown formatting for bold text. Traditionally, in message fields, wrapping a word in asterisks (*) makes it bold, and wrapping it in underscores (_) makes it italic. However, this expected behavior is not consistent when applying the same formats in Custom Status.

### Steps to reproduce:

1. Go to 'Profile' and select 'Custom Status'.
2. In the Custom Status field, try to format a word as bold by wrapping it in single asterisks (*) - expecting the word to appear bold.
3. For italic text, wrap a word in underscores (_) and observe the formatting.
![set_custom_status](https://github.com/RocketChat/Rocket.Chat/assets/24211877/14f0ed8d-3197-4411-bc14-9ea5b95125ec)

### Expected behavior:

- Text wrapped in asterisks (*) should appear bold.
- Text wrapped in underscores (_) should appear italic.

### Actual behavior:

- Text wrapped in single asterisks (*) unexpectedly appears as italic instead of bold.
- Text wrapped in underscores (_) correctly appears as italic.
- Strikethrough formatting works as expected when text is wrapped in tildes (~).
- Text only becomes bold when wrapped in double underscores (__).
![actual_status](https://github.com/RocketChat/Rocket.Chat/assets/24211877/de3e998e-3ceb-441c-8c4b-b79dc956fe8f)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.6.3, 6.5.2
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.15 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: RocketChat Electron 3.9.9, RocketChat Electron 3.9.14, Google Chrome 122, Mozilla Firefox 115.8.0ESR
- Operating System: Microsoft Windows 10, Debian 12 Bookworm

**Comment by reetp** [comment]
Still seems to occur on open.rocket.chat.

I will ask someone to take a look.
