### ISSUE TITLE
Error during yarn install

### ISSUE THREAD

**Issue by hvgowda92** [RocketChat/Rocket.Chat#32089]
Getting below error when doing yarn install

# This file contains the result of Yarn building a package (fibers@npm:5.0.3)
# Script name: install

Usage Error: The nearest package directory (/Users/name/Documents/GitHub/rocketchat/Rocket.Chat/apps/meteor/node_modules/fibers) doesn't seem to be part of the project declared in /Users/name/Documents/GitHub/rocketchat/Rocket.Chat.

- If /Users/name/Documents/GitHub/rocketchat/Rocket.Chat isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/name/Documents/GitHub/rocketchat/Rocket.Chat is intended to be a project, it might be that you forgot to list apps/meteor/node_modules/fibers in its workspace configuration.
- Finally, if /Users/name/Documents/GitHub/rocketchat/Rocket.Chat is fine and you intend apps/meteor/node_modules/fibers to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

Using 
Meteor 2.15
Node v14.21.3

### Steps to reproduce:

git clone https://github.com/<your-username>/Rocket.Chat.git
yarn

**Comment by reetp** [comment]
This is a development/support issue.

Please ask in open.rocket.chat #support
