### ISSUE TITLE
Make warning when hiding room/conversation configurable

### ISSUE THREAD

**Issue by jihakas** [RocketChat/Rocket.Chat#3208]
Your Rocket.Chat version: 0.30.0

It would be nice to be able to toggle whether or not a warning is showed when a user hides/leaves a room and/or direct messages, at least as long as they are not the only owner/moderator of that room.

This could be configurable on the user's account preferences or from the administration settings, whatever makes most sense.

**Comment by geekgonecrazy** [comment]
I think this was mainly added, because people were under the impression they had deleted or left the room.  Maybe we could even make it do this once to inform them what's happening, but after that we just simply hide it.

**Comment by jihakas** [comment]
If you have it as an option under a user's account preference, something like "Don't show warning when leaving room or closing a direct message", then the user would probably know what they're trying to achieve and not be confused by lack of feedback when leaving/closing rooms?

**Comment by geekgonecrazy** [comment]
@jihakas true... As an addition, we could also add a checkbox on the pop up to not show the notification again.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
