### ISSUE TITLE
Option to treat UNC share link as link

### ISSUE THREAD

**Issue by andresguate** [RocketChat/Rocket.Chat#3209]
Your Rocket.Chat version: 0.30.0

When a user enter the text of a unc shared folder (e.g. \192.168.0.1\share) this is inserted only as text, so the reciever cant just click over it

Sorry if this has been answered before but I cant find a solution, in our old chat system the user just insert the text and when the message is sent can be clicked as a link

**Comment by geekgonecrazy** [comment]
I don't believe our regex for links will match this.  Also to note, we recently added the ability to ignore local ips.  This is configurable, but once this is functionality was added, you'd need to configure what ever ip or subnet you wanted to allow.

**Comment by jcatarino** [comment]
It would be useful to have paths like `\server\folder1\folder2` as a link where people could just click and open that folder. This already happens for linux and macOS if `file://` is added before the path but this doesn't work for windows paths.

**Comment by jcatarino** [comment]
How do we access the functionality of disabling/enabling local ips ?

**Comment by seerl** [comment]
+1 for this feature with the format y:\sharefolder\path\document.docx or simliar

**Comment by sampaiodiego** [comment]
With the upcoming release of our Rocket.Chat Apps framework. I think this is more fitting as a Rocket.Chat App message parser.

Please feel free to post your Rocket.Chat App idea to our [forum](https://forums.rocket.chat) so maybe someone(even you) can create it.
