### ISSUE TITLE
How to contribute ROCKET.IO website??

### ISSUE THREAD

**Issue by theavitw** [RocketChat/Rocket.Chat#32095]
I saw that..Rocket.io web page has some bugs..

**Comment by MartinSchoeler** [comment]
Hello, I don't think we have any affiliation to te rocket.io page, secondly if you do find any issues on the rocket.chat webpage, you need to be more specific about it.

Finally, the rocket.chat website is unfortunately closed code, so no contributions from community can be made there. I can still pass any issues to the team responsible for it. Thanks! 

I'll be closing this
