### ISSUE TITLE
Uncaught (in promise) undefined: when i open room, There is no response from the useRoom in the room when data in the database changes.

### ISSUE THREAD

**Issue by NQToan1509** [RocketChat/Rocket.Chat#32096]
log error in browser:

![Screenshot from 2024-03-30 10-25-08](https://github.com/RocketChat/Rocket.Chat/assets/115467525/f898d9a9-de9d-40c3-b9f3-36e90d0900c7)

**Comment by theavitw** [comment]
Kindly describe more

**Comment by NQToan1509** [comment]
> Kindly describe more

When I create a room for a user, then when I enter the room I get an error like that. I haven't found the cause of the error.

**Comment by NQToan1509** [comment]
describe:
When I created the room and loaded the id into the interface when running the openRoom function, I got the above error. I saw an issue #27670 when I wasn't logged in. I got this error, but my problem is that I've logged in but still get the error.

**Comment by NQToan1509** [comment]
![Screenshot from 2024-03-31 21-57-16](https://github.com/RocketChat/Rocket.Chat/assets/115467525/f7aff553-4afa-4877-9362-8068a12eecc3)

**Comment by debdutdeb** [comment]
Please share reproduction steps. I am still lost on what this issue is about.

**Comment by reetp** [comment]
No further response.

If this still occurs please open a new bug and complete a bug template.

Thanks.
