### ISSUE TITLE
Admin info page is not updating its statistics

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#32111]
### Description:

Admin info page has stopped updating its data (message amounts in channels, users etc.)

### Steps to reproduce:

1. Go to /admin/info page in RC using browser
2. Check messages value in direct message channels
3. Send direct messages for a test
4. Check messages value again in direct message channels
5. Do a shift-reload just in case and check the value again

### Expected behavior:

The value should increase

### Actual behavior:

None of the values on the info page get any updates anymore

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.6
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 10
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Chrome

### Additional context

We replicated the issue on three separate instances. None of them update their info page.

Engagement page statistics still work.

**Comment by Gummikavalier** [comment]
I see that the data started updating again. I'm just not sure how often. It may be a very long time when it does.

**Comment by taniasa** [comment]
I have the same problem.
In the company where I work, the deployment was done by someone else with Ubuntu Snap, I don't know how to log in to Mongo in Ubuntu Snap.
Running the command 'sudo snap services rocketchat-server' I saw that mongo appears as 'rocketchat-server.rocketchat-mongo'
Can anyone help me connect please.

**Comment by reetp** [comment]
Does this still occur on 6.8 or 6.9 ?

**Comment by Gummikavalier** [comment]
@reetp Seems to work now for both 6.8.0 and 6.9.0.

Test done in two setups, switching user states and sending messages to channels. After pressing refresh on /admin/info page stats update properly.

I'm closing this issue as fixed.

**Comment by Gummikavalier** [comment]
Fixed by 6.8.0.

**Comment by reetp** [comment]
Thanks!!
