### ISSUE TITLE
Add ability to disable email globally

### ISSUE THREAD

**Issue by jihakas** [RocketChat/Rocket.Chat#3211]
Your Rocket.Chat version: 0.30.0

It would be nice to have an option to disable all attempts at sending emails, or set all email fields such as 'offline email notifications' under users accounts to disabled. We don't want to use the email functionality at all, have left all the email configurations blank, but I still see attempts at sending emails in our logs.

**Comment by mixrat** [comment]
Agreed. We use this as an office environment so when people clock in they can see their messages. There is no need to send the message twice and in some cases it is a security issue. For example when passwords are exchanged, the email notifications send this data insecurely over email.

**Comment by gigawhitlocks** [comment]
This is a security / privacy issue. Without admin ability to disable this feature, it's incredibly easy for potentially sensitive information to leak from a channel to a 3rd party email provider.

I haven't been involved with RC as a developer yet but I'd be happy to submit a PR if one of the maintainers can provide a link to the relevant portion(s) of the codebase so I can get more familiar with the RC codebase.

If that information could be provided, hopefully this would also not be my last contribution to Rocket Chat.

**Comment by ashepelev** [comment]
It will be nice to see option "Disable Email notifications when user is offline". User account also has some other options which defaults are hardcoded and cannot be changed. While user preferences have some harmless options like "Hide roles" or "Auto Load Images" which are mostly visual, it has also "Disable Email notifications globally". Users need to disable such notifications manually and its not right.

**Comment by jamesdwilson** [comment]
I would appreciate just the setting to hide message content in the emails, globally.

**Comment by SeanPackham** [comment]
Do not configure email to stop all emails from being sent. We won't support removing them from the logs in the near future.

**Comment by notnamed** [comment]
Not configuring email means that password resets don't work. We should be able to send password resets without sending chat logs.

**Comment by mixrat** [comment]
Agree with @notnamed  - this issue should not be closed.

**Comment by SeanPackham** [comment]
@notnamed @mixrat thank you for clarifying I see how there is no easy way to do this at the admin level without every used individually configuring notification settings.
