### ISSUE TITLE
Firebase Cloud Messaging (FCM) Legacy API deprecation

### ISSUE THREAD

**Issue by machadolucas** [RocketChat/Rocket.Chat#32124]
### Description:

Rocket.Chat is currently using the `node-gcm` project to integrate with Firebase Cloud Messaging (FCM) for sending push notifications. According to Google, the FCM Legacy API which is used by `node-gcm` project is now deprecated and will stop working on [June 20, 2024](https://firebase.google.com/support/faq#fcm-23-deprecation).
After that date, push notifications will stop working on Rocket.Chat if integration with FCM is not updated.

### Steps to reproduce:

1. Getting a [reminder](https://firebase.google.com/support/faq#fcm-23-deprecation) from Google about the deprecation and that my white-labeled RocketChat app is using Legacy HTTP protocol and Legacy Server Keys.
2. Verify that RocketChat server code is using outdated integration with FCM.

### Expected behavior:

Code needs to be updated with another FCM integration that supports the new FCM API. There is an issue in the `node-gcm` project recommending migration to another lib: https://github.com/ToothlessGear/node-gcm/issues/370

### Actual behavior:

`node-gcm` project is installed in [package.json#L135](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/package.json#L135) and used in [gcm.ts#L3](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/push/server/gcm.ts#L3)

### Server Setup Information:

- Version of Rocket.Chat Server: all versions

**Comment by Gustrb** [comment]
Hey @machadolucas thanks for raising this issue!

I'm currently working on implementing the new version using the FCM API instead of the old API, whilst keeping everything compatible with the legacy way of sending notifications.

The implementation is mostly done, I will link it here when I open the Pull Request.
