### ISSUE TITLE
Auto removed rocket app by Kasperskyp anti virus 

### ISSUE THREAD

**Issue by phannseiha** [RocketChat/Rocket.Chat#32125]
I have installed rocket chat app version 3.9.14. after I finished installation, I powered on my pc second time. Rocket chat was removed by Kaspersky. How to solve this issue ?

**Comment by Gummikavalier** [comment]
Interesting. Was the desktop app downloaded from GitHub here?

https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.9.14

**Comment by reetp** [comment]
Any further information on this?
