### ISSUE TITLE
Browser window frozen when mentioning user not in channel.

### ISSUE THREAD

**Issue by gelpiu-developers** [RocketChat/Rocket.Chat#32127]
### Description:

We are 15 people using Rocket.Chat and all but one computer are experiencing problems when mentioning users not in the channel. The one computer where is working is significantly more powerful than the others (Macbook Pro M3 vs Windows AMD Ryzen 5 5500U With Raden Graphics 2,10GHz 8GB/Macbook Air).

In the computer where it works, after sending the mentioning message, the dialog offering the after-mention actions is shown. In the other computers, the browser window just gets frozen, and you have to close it to be able to work again.

![Screenshot 2024-04-04 at 12 04 31](https://github.com/RocketChat/Rocket.Chat/assets/71498948/84a0972c-67a0-4c63-9633-a5bef88b7a7a)

We have test with different browsers and the behaviour is the same. We have test using different users in different computers and with different roles and it just won't make a difference. It is always working in the more powerful computer and not in the others.

### Steps to reproduce:

1. Enter public channel
2. Mention user not in the channel.
3. Browser window gets frozen.

### Expected behavior:

1. Enter public channel
2. Mention user not in the channel.
3. Dialog selection mention options appear.

### Actual behavior:

Browser window gets frozen.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.6
- Operating System: Linux Debian 10 arch x64
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: wiredTiger (oplog Enabled)
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.22 

### Client Setup Information

- Desktop App or Browser Version: Chrome 123
- Operating System: Windows 11

### Additional context

CPU arises to 100% when doing this.

### Relevant logs:

- No error logs on server.
- No error logs on browser console.
- No error requests on browser network tab.

**Comment by vorrtas** [comment]
Also happened to me in discussion
resetting app using crtl+shift+r 
helps as well as inviting
person before mentioning
 no errors in console and no hanging request in network tab
 
 running in docker registry.rocket.chat/rocketchat/rocket.chat with tag latest
 any solution will be appreciated

**Comment by SySagar** [comment]
Same as #31991

**Comment by reetp** [comment]
Does this happen on latest? eg 6.9 or 6.8 ?

I just tested on 6.8.0 and latest browsers and I can't replicate it?
