### ISSUE TITLE
Can not preview url in message

### ISSUE THREAD

**Issue by antn89** [RocketChat/Rocket.Chat#3213]
Hi guy,
I install rocked.chat v 0.30, but when i send a youtube link, it doesn't show preview,
Here is config from: Rocket.Chat/programs/server/packages/rocketchat_oembed.js

providers.registerProvider({                                                                                   // 1
  urls: [new RegExp('https?://www.youtube.com/\\S+'), new RegExp('https?://youtu.be/\\S+')],                   // 33
  endPoint: 'https://www.youtube.com/oembed?maxheight=200'                                                     // 33
});

**Comment by nishimaki10** [comment]
I found exception log.

```
Exception in defer callback: SyntaxError: Unexpected end of input
     at Object.parse (native)
     at packages/rocketchat_oembed/server/providers.coffee:74:19
     at packages/rocketchat_lib/lib/callbacks.coffee:73:21
     at Array.reduce (native)
     at Object.RocketChat.callbacks.run (packages/rocketchat_lib/lib/callbacks.coffee:68:103)
     at Object.OEmbed.getUrlMeta (packages/rocketchat_oembed/server/server.coffee:130:30)
     at Object.OEmbed.getUrlMetaWithCache (packages/rocketchat_oembed/server/server.coffee:143:16)
     at packages/rocketchat_oembed/server/server.coffee:183:18
     at Array.forEach (native)
     at OEmbed.RocketUrlParser (packages/rocketchat_oembed/server/server.coffee:179:16) 
```

**Comment by marceloschmidt** [comment]
Hello @antn89 what's the error for you? Can you send us the link you're trying to use and could you try that link on https://demo.rocket.chat and tell us if it works for you? Thanks.

**Comment by antn89** [comment]
Hi @marceloschmidt,
I installed rocket chat v 0.30 (lastest version) on centos 7. 
As first, Everything work statble, but when i send a link from youtube, it don't show preview, only show url as hyperlink. As i know, this version is enable this feature by default. I don't know why it doesn't work in my case.
The second, in my admin page, it doesn'show modun API, (in my attachment file), how can it show in admin page setting ?
![rocketchat-administration](https://cloud.githubusercontent.com/assets/19310978/15237181/bca4efe0-18f5-11e6-82a5-b6b5e3b2eae9.PNG)

**Comment by marceloschmidt** [comment]
I think the API section content has been moved to the Message subitem. Can you check if embed is enabled?

**Comment by antn89** [comment]
@marceloschmidt : 
I check as you recoment, but option 'embed' has value 'true'.

**Comment by marceloschmidt** [comment]
Can you send me the link you are trying to preview?

**Comment by antn89** [comment]
Hi @marceloschmidt 
This is the link as you request : https://chat.mydomain/admin/Message.
![message](https://cloud.githubusercontent.com/assets/19310978/15536298/f6301ce0-229a-11e6-9886-f8d0f53c7aac.PNG)

**Comment by marceloschmidt** [comment]
No @antn89. I asked for the link for which the preview doesn't work. The youtube video you're trying to watch but the preview is not displayed. Are you still having this problem?

**Comment by antn89** [comment]
Hi @marceloschmidt,
This error no longer occur when i install new version of rocket chat, 0.31,
