### ISSUE TITLE
6.7.0-rc.3 Livechat messages not updating at all, only after refresh where new messages populates

### ISSUE THREAD

**Issue by harvard1932** [RocketChat/Rocket.Chat#32133]
Live chat version: 6.7.0-rc.3  
The same bug didn't happen in 6.6.4.
Issue: Livechat messages not updating at all, only after refresh where new messages populates
This update seems to break livechat message function...

**Comment by harvard1932** [comment]
Bug started on 6.7.0-rc.0 after checking different version to isolate the bug.

**Comment by MartinSchoeler** [comment]
Hello @harvard1932 can you share more info?

1. Any errors on the console? If possible please send a screenshot of it
2. Are you calling any `LivechatApi` endpoints on your page? 
Thanks!

**Comment by harvard1932** [comment]
> Hello @harvard1932 can you share more info?
> 
> 1. Any errors on the console? If possible please send a screenshot of it
> 2. Are you calling any `LivechatApi` endpoints on your page?
>    Thanks!

1. No error on the console for this. 
2. Not calling any Livechat API other than chat initialize JS widget API (I think all related bug to this API is fixed in rc 3 where now setting guesttoken wont wipe chat). So this bug is something else

**Comment by harvard1932** [comment]
Still same issue in 6.7.0 released v ersion started since 6.7.0-rc.0...
