### ISSUE TITLE
Glitched Livechat rooms where webhooks will no longer trigger. 

### ISSUE THREAD

**Issue by harvard1932** [RocketChat/Rocket.Chat#32137]
Not sure if its related to #32131 and is something obvious enough to be picked up. 
But on rare occasions, few livechat rooms on specific token/guestToken rooms will be glitched/stuck where when guest input a message, it would never trigger the webhook for customer service to know. It happens maybe 1% of the time, maybe related to token/guesttoken, since once it happens to a room it will stuck forever unless the chat is ended, and start a new chat. But the guest's message are recorded inside rocket chat, just that it wouldn't trigger webhook. 

Thank you so much!!!

**Comment by KevLehman** [comment]
Don't think it's related to that fix, but we'll investigate. 

Can you add more details? Like, logs, the room object & the message you received (annonymized pls) and other stuff that may be needed? 🤗 thanks!
