### ISSUE TITLE
Problem with "auto reply" from marketpalce

### ISSUE THREAD

**Issue by qeinz** [RocketChat/Rocket.Chat#32147]
If you are about to enter a "zalgo text" with a big chunk of charackters into auto reply from a direct chat and than send a message and click "no" it will crash your rocket chat in docker 
![image](https://github.com/RocketChat/Rocket.Chat/assets/66924611/cd47efea-5f75-42e1-8429-ed8e48db7cab)

**Comment by reetp** [comment]
Please fill in a proper bug femplate withall your server details.

Make sure you also test on the latest version.
