### ISSUE TITLE
Video Call turns black on Android Apps

### ISSUE THREAD

**Issue by mgsolid543** [RocketChat/Rocket.Chat#3215]
Hi All,

Your Rocket.Chat version: (make sure you are running the latest)
I have downloaded, installed, and tried on Android Rocketchat Application v2.3.1, but when i want to make a video call with my friend it turns out black on the screen

[Screenshot](http://s32.postimg.org/qjbt3vttx/IMG_20160512_WA0055.jpg)
The video call is run well when i tried it on **Google Chrome** browser

thankyou,
best regards.

**Comment by vovcacik** [comment]
Same problem, tested now and few months ago.

**Comment by MartinSchoeler** [comment]
Please reopen this on the android app repository. Thanks.
