### ISSUE TITLE
Empty link of forwarded files 

### ISSUE THREAD

**Issue by Anders-77** [RocketChat/Rocket.Chat#32161]
Forward the received files to the other dialogue and see that there are only names of links without the links - it happens on the Android app. Desktop app act similarly but the links look like correct, but don't work as well.

Server Version 6.6.6
Desktop app 3.9.14
Android 4.48.0.59929
Windows Home

**Comment by SySagar** [comment]
If possible can you give us more insightes on this my some images or possibly a video ?

**Comment by Anders-77** [comment]
Yes sure. Send you the record of mobile app behaviour,  but it is the same on desktop app.

https://github.com/RocketChat/Rocket.Chat/assets/166539184/b3f7b16d-00f3-4c1b-919e-f916a4f1bee0

**Comment by reetp** [comment]
Just tested this on Android 4.48.0.59929 on 6.6.7 and had no issues at all with either a PDF or a image.

As you already have similar comments on https://github.com/RocketChat/Rocket.Chat/issues/32160 I suspect there is something else going on that we don't know about.

What type of file storage are you using?

How did you install Rocket?

What do your logs tell you?
