### ISSUE TITLE
Opening of downloaded files in the dialog

### ISSUE THREAD

**Issue by Anders-77** [RocketChat/Rocket.Chat#32160]
Hello there!
When I receive some files, except images, I can download them and I expect to open them by clicking on the link in the dialog. But I can only open them from the destination, where these files were downloaded to. When I go to the list of the files of this dialog, I have only the download link. It looks like a bug.
It happens on the desktop app and on the Android app. But I noticed, that sometimes the Android app works correctly (only for some users), or sometimes it opens some types of files and downloads again the others.

Server Version 6.6.6
Desktop app 3.9.14
Android 4.48.0.59929 
Windows Home

**Comment by SySagar** [comment]
Please provide some video resouce so that I can get started

**Comment by Anders-77** [comment]
Uploading InShot_20240415_172245358.mp4…

**Comment by Anders-77** [comment]
https://github.com/RocketChat/Rocket.Chat/assets/166539184/9768ffa0-cf31-44d9-bfec-f736f08ae228

**Comment by Anders-77** [comment]
for the desktop app it looks so, but mobile app changes its behaviour without reasons..
as I wrote before, sometimes it works like it realized in whatsup, for example, just openning files in assosiated apps.

**Comment by reetp** [comment]
> Android 4.48.0.59929

Lastest is 4.48.0.60773 so please test on that.

Note that if it is an issue with the React Android app you should close this and open a bug in the correct repo - or ask in https://open.rocket.chat/channel/react-native - there is also a link there to the Beta versions to test.

On mine with Android 14 on a S23 a PDF popups the "Open With" dialog (there is no PDF rendering library in Rocket)

Images have a download button to save to your gallery.
