### ISSUE TITLE
Uploadig LDAP user avatar errors by <Invalid JSON Custom Fields>

### ISSUE THREAD

**Issue by momentics** [RocketChat/Rocket.Chat#32189]
It used to be work till 6.7.0. Latest checked version is 6.6.0 and seems 6.6.3 too.
However, updating server up to 6.7.0 breaks this functionality.

**Steps to reproduce:**
1. Sync on ldap users (this configuration used to be work since 4.x succesifully)
2. Open Users list on Admin Panel
3. Try to set up user's avatar image by *.jpg file
4. Invalid JSON Custom Fiels error occurs

**Expected:**
- Avatar to be updated without errors

**Configuation:**
- Server: Latest, 6.7.0 docker image (all in one).
- Client: 3.9.14, windows 10 x64
- Starter license, 10/25 used

![image](https://github.com/RocketChat/Rocket.Chat/assets/6221848/cc95e1da-b9a9-4443-87e4-00fcab3d8f1e)

**Comment by momentics** [comment]
Gents, any idea when this might be fixed?

UI with partial avatars looks like homebrew software...  :(  The old ones work as they should, but the new ones only have colored letters. btw, it also reproduced throught the web UI

**Comment by momentics** [comment]
**Update**:
Avatars are displayed if the user is logged into RC. Most likely they are downloaded from AD Imge but not from uploaded pics.

**Comment by reetp** [comment]
Hi,

can you check on the latest 6.7.x or 6.8.x please.

**Comment by momentics** [comment]
> Hi,
> can you check on the latest 6.7.x or 6.8.x please.


Hello @reetp 
I just tried 6.8.0 to repeat the issue. 

**That what had been done:**

- Latest 6.8.0 had been installed via docker image
- New Windows AD user had been created
- RC->Working space->Settings->LDAP had been synchronized, to refresh users list. New created user is visible in RC-> Working space->Users.
- User's  parameters had been edited (particularly avatar image). Used JPG file 512x512px, and 65 kb in size
- Original error repeated

However, if the same JPG file is configured in Windows AD->UserImage, same error occurs. But avatar will be shown right after first time mentioned user is logged into RC. 

**Therefore, same issue exists in latest 6.8.0 version.  Sorry John...**

**Comment by reetp** [comment]
The dev who does most of the LDAP stuff doesn't believe it is a LDAP error per se.

I presume you have some code in LDAP->Premium-> Sync Custom Fields or similar? 

What is the custom code that is triggering this?

**Comment by momentics** [comment]
Hello @reetp !

Nope. It is not premium and no custom code. It is Starter licence.


Trivial conf:

- Server type - Active Directory
- Host - _host ip_
- Port - 389  (this is private network)
- Reconnect - Yes
- Reserve auth - Yes

- User DN - _correct user DN_
- Password - _correct user DN password_
- Encryption - none
- Cert - None (this is provate network)

this configuration used to be since 4.x

**Comment by reetp** [comment]
Should all work for our number of users.

Hmmm.

Any errors in the browser console?

Note if we search the code for this error we can see this:

https://github.com/search?q=repo%3ARocketChat%2FRocket.Chat+error-invalid-customfield&type=code

`JSON.parse(settings.get('Accounts_CustomFields'));`

Check Accounts, Registration, Custom Fields

**Comment by momentics** [comment]
Hello @reetp 

John, I checked it in the browser console it actually gives this message as per the the link above. Looks like this is the right place in souce code. As per your recommendation, I checked the Account and Registration for custom fields. Indeed, during registration there was an optional field. It was created back in the days of RC 4.x and I had already forgotten about it. Please note it used to be work till RC 6.6.0.

Btw, removing optional Custom field had resolved the issue. However, unless this is an optional field it should not report of errors I guess.


**Accounts:**
![image](https://github.com/RocketChat/Rocket.Chat/assets/6221848/6c55a13c-3c15-4f8b-a996-dd6436569f07)

**Registartion:**
![image](https://github.com/RocketChat/Rocket.Chat/assets/6221848/8942ba86-8379-4984-ada1-9774da7eafe1)
