### ISSUE TITLE
Copy to clipboard does not work on cordova

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#3218]
In the cordova app (on android), when pressing the buttons 'copy' or 'permalink' nothing happens.
Version: 0.30.0

**Comment by geekgonecrazy** [comment]
@lucasvanhalst please see: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/98

**Comment by lucasvanhalst** [comment]
@geekgonecrazy Thought it belonged here since the code that needs to be changed is in this repo, rather than the cordova one.

**Comment by geekgonecrazy** [comment]
@lucasvanhalst its cordova specific, so we will need to add code to the cordova project to handle the copy
