### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by isclever** [RocketChat/Rocket.Chat#32198]
### Description:

Push notifications aren't being sent.  Logs show that it was successfully sent on my end but the notification doesn't arrive.

### Steps to reproduce:

1.  Go to settings -> Push
2.  Click "Send a test push to my user"
3. Debug level logs show:
`rocketchat_1  | {"level":20,"time":"2024-04-12T18:04:02.643Z","pid":8,"hostname":"dce2d24b6fcd","name":"Push","msg":"Sent message \"@<REDACTED MY USER>\" to 0 ios apps 2 android apps"}`

### Expected behavior:

Push notifications working

### Actual behavior:

Notifications are not received. 

### Server Setup Information:

- Version of Rocket.Chat Server:  6.6.6
- Operating System:  Debian
- Deployment Method:  Docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  4.4.29 / wiredTiger (oplog Enabled)
- NodeJS Version:  v14.21.3
- MongoDB Version: 4.4.29 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Android
- Operating System: Android

### Additional context

I've attempted to resolve this issue by upgrading 6.4.4 -> 6.4.9 -> 6.5.4 -> 6.6.6

### Relevant logs:

See above.

**Comment by reetp** [comment]
> I've attempted to resolve this issue by upgrading 6.4.4 -> 6.4.9 -> 6.5.4 -> 6.6.6

This likely means that the issue isn't directly rocket itself.

Have you registered your workspace? What version are you using? CE/Starter etc?
Check under Administration > Workspace

Which gateway are you using?
Administration > Settings -> Push

Any firewalls in the way?

**Comment by kishanbh** [comment]
+1
