### ISSUE TITLE
"MORE UNREADS" doesn't make sense/is incorrect most of the time

### ISSUE THREAD

**Issue by connorshea** [RocketChat/Rocket.Chat#3219]
I keep seeing this:
<img width="269" alt="screen shot 2016-05-12 at 12 20 54 pm" src="https://cloud.githubusercontent.com/assets/2977353/15225743/03bf3afc-183d-11e6-87ae-3c1474a9935d.png">

But it doesn't make sense in context, since half the time it's pointing in the wrong direction or at a channel I can already see has unreads. In my opinion, it's not adding much, and is confusing (especially for new users, since they won't have enough channels to fill up the full screen height), so I'd suggest it be removed.

**Comment by connorshea** [comment]
For example, there are no channels with unreads when I scroll up here:

<img width="263" alt="screen shot 2016-05-12 at 12 31 43 pm" src="https://cloud.githubusercontent.com/assets/2977353/15225856/85d0c268-183d-11e6-9a75-b8cfa9451779.png">

`random` is the only one with unreads.

**Comment by MartinSchoeler** [comment]
Hey @connorshea , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
