### ISSUE TITLE
SSO with forums

### ISSUE THREAD

**Issue by mikeamcbrien** [RocketChat/Rocket.Chat#322]
So many communities would love a system that would allow sso from their software, like forums, Invision Power, vBulletin and eve wordpress.

Allow a mechanism for Single Sign On from any of these systems could be a huge benefit to any of the communities involved and their real time communication needs.

and API that would also allow simple information, like #of users chatting, online, active, etc for pulling to the website would also work great in tandem with this feature.
##

**Comment by stefanffsx** [comment]
+1 to register/sign-in with like a vBulletin forum, would be awesome.

**Comment by rodrigok** [comment]
Any ideas how to implement this?

**Comment by AdrianoCahete** [comment]
XenForo have a Steam SSO here: https://github.com/HowIChrgeLazer/Steam-Authentication-for-XenForo

**Comment by andricicezar** [comment]
+1 I would love this feature. I would like to use it with a CAS server, like this one: http://rubycas.github.io/

**Comment by andricicezar** [comment]
Check this, maybe it can help you: https://atmospherejs.com/admithub/shared-auth

**Comment by engelgabriel** [comment]
Guys, just so I can understand and see if we can make this into our v1.0 release.

Is the SSO part important? Or just the OAuth or SAML part?

I mean, is that important that the user is automatically logged in, or it is enough for now that he can just use the same username and password without the need to re-register?

We could use soemthing like https://atmospherejs.com/natestrauser/accounts-saml

Or 

We could create a generic oAuth package that can be configured to connect to Wordpress and alikes if they have something like https://wordpress.org/plugins/oauth2-provider/ installed.

**Comment by andricicezar** [comment]
I think is more important that the user be automatically logged in, because
it will be a seamless flow when you integrate more projects together.

**Comment by geekgonecrazy** [comment]
May I suggest an adapter approach?  This would allow developers to write authentication methods for their different platforms, and take a lot of the burden off of you guys.  

We discussed this in chat. @graywolf336 mentioned this.  But I find it a great idea, and want to make sure its with the issue.

**Comment by graywolf336** [comment]
Yes, I think the adapter approach would be one of the best ways to go about this. It wouldn't be a seamless flow as others have mentioned in here but it would make it so only one login is required across several platforms (at least in my regards). There are a vast amount of solutions out there which can be hooked into via an adapter to try and meet the needs of them all, which is where the adapters would come into play. I use Xenforo and would be nice to use that as the system which my team uses to log in with.

**Comment by engelgabriel** [comment]
Support for Okta SSO through SAML v2

**Comment by engelgabriel** [comment]
https://github.com/nate-strauser/meteor-accounts-saml

**Comment by engelgabriel** [comment]
https://meteorhacks.com/extending-meteor-accounts

**Comment by engelgabriel** [comment]
We can test here: https://www.okta.com/get-okta-free/

**Comment by engelgabriel** [comment]
Go to https://www.okta.com/solutions/identity-layer-for-developers.html
there is a sign up for a developer account

**Comment by jjshoe** [comment]
Def. want this without requiring a third party sso/oauth solution. I want to tie into my existing web app.

**Comment by mchilson** [comment]
Same here...Would like to integrate with my existing custom community site using the user's preexisting account.

**Comment by engelgabriel** [comment]
@mchilson can't you use SAML or oAuth?

**Comment by mchilson** [comment]
Yes of course, but like most that have posted here a seamless, fully integrated solution is much better for my users/subscribers and they come first. Nothing scares a unsophisticated user off more than having to jump through hoops.maybe have a "simple integrated mode" where the username can be passed and a session created? I know this is not how the app is structured but it would be VERY helpful to most integrators. With that said, .I really like rocket.chat and hope to be able to use it sometime in the future if this type of integration is ever implemented..

**Comment by IQ2022** [comment]
does this support also Forums like
https://www.discourse.org/
https://nodebb.org/
http://flarum.org/

**Comment by jjshoe** [comment]
I too would love to see more than the adapter approach. The ability to have a user log into a website once is crucial.

**Comment by engelgabriel** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/1369

**Comment by engelgabriel** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/1924

**Comment by jjshoe** [comment]
FWIW - Hipchat does NOT have this feature to this day. Despite there being 2,700+ votes for it. Atlassian hasn't even acknowledged it publicly. Lots of people are forced into slack as a result.

It would be easy to slide rocket chat in as an option for all the hipchat people looking for a ship to jump on.

https://help.hipchat.com/forums/138883-suggestions/suggestions/2908263-single-sign-on-via-google-apps-crowd-active-dire

**Comment by anthony-o** [comment]
I would also need such feature: ability to connect to an existing SSO (here I would like a CAS support or any protocol that CAS can handle - oAuth, SAML... :))

**Comment by engelgabriel** [comment]
CAS has just been added to the develop branch.

https://github.com/RocketChat/Rocket.Chat/pull/2183

**Comment by corecache** [comment]
Just a quick update: CAS 1.0 is fully integrated by now. First steps towards CAS 2.0 were taken.

**Comment by auryn-macmillan** [comment]
What's the latest on this? I'd really love to hook up my Discourse instance as an SSO provider for my rocket.chat instance.

**Comment by balsig99** [comment]
here is integration of ROCKET CHAT AND IPB [invision power board ] FORUM board by @wohali Please contribute to source code :)  https://github.com/wohali/ips4-oauth2-server

**Comment by spinza** [comment]
Would also like to see discourse integration.  Using discourse as the SSO provider.

**Comment by jszaszvari** [comment]
You can probably do it through the SAML provider already.

These are all plugins that the community should be coming up with, it's not
efficient use of a developers time to interstate this stuff that maybe 5
people would use. They need to be focusing on the core product, not
integration with all these small tools that a few people use.

**Comment by spinza** [comment]
Yeah but it's also good to gather interested people.  Happy to get started on doing discourse one.

**Comment by spinza** [comment]
Is there any guidance on auth development for this?

**Comment by wohali** [comment]
@spinza In short if the forum software you have supports acting as an OAuth provider, you've already got what you need - it's just a matter of configuring the OAuth provider in your forum software and the OAuth consumer in Rocket.chat.

Otherwise you're looking at adding that functionality to the forum software, as I did with my IPS addon.

**Comment by spinza** [comment]
Thanks, it doesn't have oauth.  It's Discourse. 

So either I can add OAuth to it (or host a OAuth module separately that talks to Discourse), or I can add a specific module for it's SSO here.  I am a noob with js.  So I'm hoping there is a "template" or good example for adding another auth option to Rocket.Chat.

**Comment by Sentinelrv** [comment]
The Peercoin community is switching its forum from SMF to Discourse. We also use rocket.chat. Providing a single sign in option for both the forum and chat would be a great way to strengthen our community experience. The forum and chat would then be seamlessly integrated.

Has anyone made any progress on this?

**Comment by corecache** [comment]
@Sentinelrv Try using established standards like LDAP, or CAS based on LDAP/Database/x or OAuth based on differnt backend to which all your applications in need for authentication (maybe authorization too) are able to connect to.

**Comment by spinza** [comment]
I've setup an oauth2 provider that effectively uses the discourse as backend for login.  So login at chat.example.com gets redirected to oauth.example.com which redirects to discourse.example.com.  Of course any other oauth2 compatible sites can use it too.  

This was based off some example django oauth provider and adding discourse sign on and pydiscourse.

**Comment by engelgabriel** [comment]
@Sentinelrv did you achieve what you wanted with oAuth?

**Comment by evaletolab** [comment]
:+1:  for SSO solution, it's a great feature that will allow a better user experience.

As an example, Disqus allow this feature and it really gives a better user experience :rocket: 
https://help.disqus.com/customer/portal/articles/236206-integrating-single-sign-on
We use it in our plateform karibou.ch, here a screenshot before the karibou.ch login, 
![image](https://cloud.githubusercontent.com/assets/1422935/22690572/c9beaea8-ed36-11e6-9356-ffb707234b60.png)
And here, right after the karibou.ch login,
![image](https://cloud.githubusercontent.com/assets/1422935/22690606/eeff087a-ed36-11e6-911e-1318debcb299.png)

If there is a way to implement it? In our case we are the owner of the plateform !

Cheers, Olivier

**Comment by madguy02** [comment]
@geekgonecrazy   How do i try out the adapters, for SSO purposes to any personal applications?

**Comment by geekgonecrazy** [comment]
@madguy02 Rocket.Chat has all found in the Administration section

**Comment by graywolf336** [comment]
As we allow Rocket.Chat being both an oAuth client and server, should we consider this suffice to close this issue? If another specific login source, as we have plenty right now, then we will accept pull requests. :)

**Comment by geekgonecrazy** [comment]
I think we should break this up into specific issues if there are any. SSO for forums is generic.  I mean some forms support oauth, others like saml or cas.  Others have their own.

**Comment by graywolf336** [comment]
Agreed. If there's a particular forum system which doesn't support oAuth or SAML or CAS and needs it's own, then please open an issue so that contributors can find it easily and help. :)
