### ISSUE TITLE
Channel scrolls to bottom when clicking image

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#32206]
### Description:

After reloading a channel, clicking an image in a message makes the channel scroll to the very bottom instead of showing the image.

### Steps to reproduce:

1. Open a channel in a browser.
2. Refresh the page.
3. Scroll up to a message containing an image.
4. Click on the image.

### Expected behavior:

The image is shown.

### Actual behavior:

The channel scrolls to the very bottom:

https://github.com/RocketChat/Rocket.Chat/assets/404840/f9f5cfb5-6300-4a3a-92e5-1ea892cf9ce9

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.0
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.14

### Client Setup Information

Based on the reports by the users on my Rocket.Chat instance, the issue seems to occur in every browser. I just successfully reproduced it using:

- Browser Version:
  - Version 123.0.6312.105 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 124.0.2 (64-bit)
- Operating System: Arch Linux

### Additional context

The same behaviour occurs when clicking a link preview or an attachment.

**Comment by Gummikavalier** [comment]
We are witnessing the very same thing happening with the message toolbar. For instance:

1. Switch from one channel to other
2. Scroll up to some old message
3. Hover mouse over the message and select `Reply in thread`

Reply in thread action does not trigger and the message view scrolls to bottom.

**Comment by Gummikavalier** [comment]
@juliajforesti Hi, do you think this issue could be introduced by the new time bubble feature?
https://github.com/RocketChat/Rocket.Chat/pull/31572

**Comment by SySagar** [comment]
For some reason I am unable to produce it neither in open.rocket.chat or in my local dev environment.


https://github.com/RocketChat/Rocket.Chat/assets/93787385/057d1c90-cad0-44b9-b56b-0f4398da7757

**Comment by paulchen** [comment]
> For some reason I am unable to produce it neither in open.rocket.chat or in my local dev environment.

I can't reproduce it on open.rocket.chat either. Maybe this depends on the deployment method? There have been issues in the past that only occurred when using Docker.

**Comment by Gummikavalier** [comment]
I think they've simply fixed it there now. It did happen the last time I tested there, but I cannot reproduce there anymore either.

**Comment by Den4ik92** [comment]
I have the same bug, it can be reproduced as follows:
-In the browser (refresh the page):
-In the app (View menu -> Refresh without cache):

1. Open any chat with a long history 
2. Scroll up until loading old messages
3. Click on any message and it scrolls all the way down

**Comment by wanderlage** [comment]
I have the same problem after updating to version 6.7.0

**Comment by dougfabris** [comment]
Indeed it's an issue folks. Unfortunately it is a side effect introduced with the message keyboard navigation we shipped on 6.7. It's already fixed an the 6.7.1 is on the way

**Comment by Gummikavalier** [comment]
Confirmed working in RC 6.7.1 for us.

**Comment by dougfabris** [comment]
Thank you for always helping us @Gummikavalier

**Comment by Gummikavalier** [comment]
No problem! :heart: Credits for @paulchen too for the fastest reaction. :+1:

**Comment by dougfabris** [comment]
@Gummikavalier Of course, nice catch @paulchen 
Thank you all 💯 🚀

**Comment by paulchen** [comment]
I can confirm that this problem is fixed in 6.7.1. Thanks @dougfabris for taking care of it!
