### ISSUE TITLE
Mobile App show green preloader on "Join" to call via Jitsi with token

### ISSUE THREAD

**Issue by DustpaN-Spb** [RocketChat/Rocket.Chat#32234]
### Description:

Mobile App show green preloader on "Join" call via Jitsi with token

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.0
- Operating System: Ubuntu
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 

![Screenshot_2024-04-17-16-06-26-26_6c2112e95a10afaab76cfa27a6d42c7b](https://github.com/RocketChat/Rocket.Chat/assets/162093806/47713aa7-7879-45c1-9c5e-efa39338ef5b)

**Comment by reetp** [comment]
Yo have not provided enough information about your setup for us to tell what is happening.

This looks like a support issue.

Please ask your question here https://open.rocket.chat/channel/support or the  forums and describe your Jitsi setup please.
