### ISSUE TITLE
File upload Delay

### ISSUE THREAD

**Issue by imanerfanian** [RocketChat/Rocket.Chat#32235]
### Description:

File Upload 10s Delay

### Expected behavior:

fix this issue

### Actual behavior:

When i try to send files ( like .pdf file or anything else ) it send's with maybe 10s or 15s delay. the progress bar is appears and complete fast but the actual file send with delay.  i have another RocketChat Server with Nginx webserver and it's okay but this server with Caddy have problem. idk its the webserver or anything else.. i also checked the log and there was nothing about this delay.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.0
- Operating System: Ubuntu 22.04.3 LTS
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)
- Webserver: Caddy

### Client Setup Information

- Desktop App or Browser Version: Chrome Latast
- Operating System: Windows 10

**Comment by reetp** [comment]
This is really as support issue and there is not enough information to be able to help you.

Please ask in https://open.rocket.chat/channel/support or the forums.
