### ISSUE TITLE
multi_static_select not working correct

### ISSUE THREAD

**Issue by vorontsoved** [RocketChat/Rocket.Chat#32243]
Hello, I'm using the application engine, but multi_static_select is not working.
The app engine repositories are not responding, please help

<img width="754" alt="Снимок экрана 2024-04-18 в 15 58 09" src="https://github.com/RocketChat/Rocket.Chat/assets/92857671/905fa57b-abd1-426d-b1bc-799e66e9ab17">

**Comment by reetp** [comment]
Can you please fill out a proper bug template with your server details.

Template is here

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

We can't help without that sort of information.

Thanks.
