### ISSUE TITLE
Kicked users still can access the messages and message on the channel.

### ISSUE THREAD

**Issue by umangutkarsh** [RocketChat/Rocket.Chat#32246]
### Description:

Some validations might be required to check if the user is currently a member of the channel.
In the below provided video record, I am using embedded chat and providing the host as `localhost:3000` on which the docker image of my rocket.chat server is running.

### Steps to reproduce:

1. Start RocketChat server
2. Login with different users on the Embedded Chat and Rocket.Chat (don't login as admin in the EC)
3. Kick the other user from the channel through rocket.chat server.
4. The other user is still able to access the channel.

### Expected behavior:
The user who is kicked out should not be able to message until they join the channel again.

### Actual behavior:
Can still access the messages of the channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.0
- Operating System: Windows 11 (WSL 2)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3 - x64
- MongoDB Version: 5.0.24

### Client Setup Information

- Desktop App or Browser Version: Browser version
- Operating System: Windows 11 (WSL 2)

### Additional context

Attaching a relevant video:

[kick-issue.webm](https://github.com/RocketChat/Rocket.Chat/assets/95426993/39b560c6-48ca-4558-ba3d-b86309edcf1d)

**Comment by gabriellsh** [comment]
That is a public channel. If the user has the correct permissions he'll always be able to read all messages. This is not a bug, it's intended behaviour. If need to either make the channel private, or give the users a role that doesn't allow for reading public channels.

Thanks for contributing though! Keep it up.
