### ISSUE TITLE
Can't login as admin after receiving NPS notification

### ISSUE THREAD

**Issue by droncheg** [RocketChat/Rocket.Chat#32242]
### Description:

Just received NPS notify about planned survey at 2024-05-09 from Rocket.Cat

### Steps to reproduce:

1. Receive NPS notify in Rocket.Cat bot chat
2. Hang on browser admin login and desktop application, but works in Android App

### Expected behavior:

No hangs at all

### Actual behavior:

Today i received 2 notification about NPS surveys which come at 2024-05-09 in two different Rocket.Chat instances. After that i cannot login as administrator to browser or desktop on both instances: Chromium crashes with Error 4, desktop app consumes 100% and no info at all. But can logging in to Android app and read all chats, but without access to admin panel (i think that cause hang). Any other admin accounts has same behavior. Under usual user all works perfect.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: Gentoo Linux
- Deployment Method: node-env with prebuilt server
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.16-r1

### Client Setup Information

- Desktop App or Browser Version: Chromium 123.0.6312.105, Rocket.Chat app 3.9.10
- Operating System: Gentoo Linux

I would like to disable this NPS crap, but can't do it via any way - browser, desktop or mobile app. Can i disable NPS via mongo shell? Will this disabling help with the above problem?

**Comment by grzebo** [comment]
It might be the banner problem, discussed here:

https://github.com/RocketChat/Rocket.Chat/issues/31893#issuecomment-2011986117

**Comment by droncheg** [comment]
> It might be the banner problem, discussed here:
> 
> [#31893 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/31893#issuecomment-2011986117)

Thanks a lot! That helps!
