### ISSUE TITLE
Refreshing the page is changing the language back and not respecting the User Preference

### ISSUE THREAD

**Issue by jessicaschelly** [RocketChat/Rocket.Chat#32268]
### Description:
When a user changes their language preference in the "User Preference" settings and then refreshes the page, the language reverts back to English.

### Steps to reproduce:

1. Go to user preferences
    `/account/preferences`
2. Change to a language different from English
e.g: Belarusian
3. Refresh the page

### Expected behavior:
The User Preference should be respected and the language should be kept as the one selected

### Actual behavior:
It changes the Language on the screen to English (probably because of the browser language) 

Before refreshing:
![image](https://github.com/RocketChat/Rocket.Chat/assets/33631127/9a5012a3-bd1a-48ea-94bc-258d95ecacc4)

After refreshing:
![image](https://github.com/RocketChat/Rocket.Chat/assets/33631127/f56ffa56-ea4b-4113-b5f5-732673787680)

### Server Setup Information:
6.6.3

### Client Setup Information

Desktop App or Browser Version: Browser
Operating System: Windows

**Comment by SySagar** [comment]
#31802 hey @gabriellsh I think this error has been since a long time. If I remeber then I was unable to produce it on my dev however a lot of people have claimed it exists.

**Comment by robinreckmann** [comment]
> #31802 hey @gabriellsh I think this error has been since a long time. If I remeber then I was unable to produce it on my dev however a lot of people have claimed it exists.

The issue was introduced in version 6.6.0 afaik.
