### ISSUE TITLE
Jumping on chat screen insteaed of only referenceed reply, it is happening with every message

### ISSUE THREAD

**Issue by Ahmad-Ali-com** [RocketChat/Rocket.Chat#32283]
Ever since I updated my rocket chat to latest version (3.9.14), when i click anywhere on the chat for the first time on that chat screen whether I am in a direct message window or a channel  window, upon clicking even on the blank space takes the view to some old message like it does when you click on a reply with reference message but right now it is happening for every message which is really annoying and i have to scroll again and again and it is becoming hard to work with RocketChat, can someone please take care of it?

**Comment by maurice-does-software** [comment]
This same problem also just started for my company's install when the snap updated to version 6.7.0. @Ahmad-Ali-com do you mean you updated *from* version 3.9.14?

**Comment by Ahmad-Ali-com** [comment]
> This same problem also just started for my company's install when the snap updated to version 6.7.0. @Ahmad-Ali-com do you mean you updated _from_ version 3.9.14?

At the moment i see the 3.9.14 is the latest version and i am facing this issue in this version, earlier i was using 3.9.10 or 3.9.11 without this issue

**Comment by reetp** [comment]
I think this may be a Electron bug - you refer to 3.9.14 which is the Electron client version, not the server version.

Please open this in:

https://github.com/RocketChat/Rocket.Chat.Electron/issues
