### ISSUE TITLE
Channels unread messages don't always get marked as read when entered (counter remains)

### ISSUE THREAD

**Issue by EqualMarcus** [RocketChat/Rocket.Chat#32323]
### Description:

The issue below, which is closed, is still re-produceable in the latest version
v6.6.6

"we're experiencing issues where the channels having only few new messages in them don't get marked as read automatically, leaving the channel name as bolded in the channel list pane."

https://github.com/RocketChat/Rocket.Chat/issues/15471

The issue has also been reported here

https://forums.rocket.chat/t/unread-message-counter-icon-wont-go-away/19339

### Steps to reproduce:

I'm not sure how to re-produce this issue. Some people in my organisation have it, some do not.

### Expected behavior:

When you click on a channel, it marks it as read

### Actual behavior:

When you click on a channel, it does not mark it as read

### Server Setup Information:

- Version of Rocket.Chat Server: v6.6.6
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.26 

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.9.14
- Operating System: macOS, Windows

### Additional context

Some users are using macOS, some are using Windows. Some are using the Browser, some are using the Desktop App.

**Comment by reetp** [comment]
If your docker upgrades automatically (because you use 'latest', which you shouldn't)  I have found that caches don't get refreshed correctly and things get 'wedged'.

Do you get any network drops or other issues?

I would suggest in the first instance that you fix your version, and then clean all the caches on browsers, apps, and Electron clients and see if it re-occurs.

**Comment by EqualMarcus** [comment]
Hi @reetp Thanks for replying - Is there a way I can trigger caches to clear for all of our users. We have 190 users, so telling each one to do so is difficult, as many are not very good with technology.

Our Rocket Chat is fixed at a particular version, although an annoying header came up telling us to upgrade from 6.4 to 6.6, so I did...

I personally am not seeing the issue.

**Comment by reetp** [comment]
Clearing caches automagically on that scale is not something I have experience of.

You could ask on open.rocket.chat


Fixed version is good, but generally keep up to date. Note the per version EOL dates.
