### ISSUE TITLE
Focus on message-box when menu is open should close off canvas state

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#3233]
Your Rocket.Chat version: 0.30.0, confirmed on http://rocket.chat

When you have the menu open (e.g. to choose another room) and then focus on the message-box to type a message, the `menu-opened` class should be removed to bring the entire message area back on canvas and close the menu.

In the screenshot below, 1. the menu was already open, and 2. I touched the message-input textarea. Expected behavior would be for the menu to close, but it remains open.

![rc-off-canvas](https://cloud.githubusercontent.com/assets/400890/15251890/7e37498e-18f9-11e6-8a54-5782fa4e2b27.png)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
