### ISSUE TITLE
Certain characters break image preview

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#3235]
Your Rocket.Chat version: 0.30.0, confirmed on https://demo.rocket.chat

When I upload an image with unusual chars, e.g. an apostrophe in the file `1417278514faiDon'tdrinkandprime.jpg`, it breaks the preview in chat. But the modal overlay still shows the image properly.

![rc-bad-chars-upload](https://cloud.githubusercontent.com/assets/400890/15252234/e43da33a-18fa-11e6-8075-b2255e07b09e.png)

**Comment by ruihildt** [comment]
Hi, this is really an issue for french user, as any accentuation like é / à / è (which are really common) in the filename will break the preview.

**Comment by louisemessage** [comment]
Tested this in 2.10.5 with jpg. and png. and file preview displays correctly.
