### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3236]
can we not create an icon for register vs text ? or was this done on purpose.  - i think alot of people shy away when they just can't login, we should make Register/Login buttons visible. IMO (for non-tech savvy)

![image](https://cloud.githubusercontent.com/assets/12454319/15254301/1f526a38-1904-11e6-972e-c2422a9dd02b.png)

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
