### ISSUE TITLE
Support showing full name

### ISSUE THREAD

**Issue by haosdent** [RocketChat/Rocket.Chat#324]
Currently, username is as primary key and could not change. It also used in room and  subscription and other data structures. Do we have plan to support this? For example show the nickname in room. And user also could change nickname.
##

**Comment by sampaiodiego** [comment]
you (or chat admin) should choose what to show, either username or name/nickname.

so yes, we do have plans to support this configuration. =)

**Comment by haosdent** [comment]
thank you

**Comment by onigoetz** [comment]
:+1: I would love to see that

**Comment by leeychee** [comment]
:+1:

**Comment by AlexTr** [comment]
:+1:

**Comment by Laisky** [comment]
> you (or chat admin) should choose what to show, either username or name/nickname.

> so yes, we do have plans to support this configuration. =)

👍I really need this.

**Comment by bott0r** [comment]
maybe a compromise along these lines 
![capture](https://cloud.githubusercontent.com/assets/17119942/14422778/c2cfbf52-ffd8-11e5-8681-2991a109785d.JPG)

IMHO: A decent way would be to have an extensive customization panel in the admin section and a simple user customization tab, where the individual user can change some things. 
As discussed https://github.com/RocketChat/Rocket.Chat/pull/1377

**Comment by chey** [comment]
+1

**Comment by LFCavalcanti** [comment]
+1

**Comment by LFCavalcanti** [comment]
Seems that PR  #3337 solves this issue.
Not sure if it will map based on attributes from SSO backends like LDAP.

**Comment by Mte90** [comment]
Will be very useful because it's one of the things that are missing on rocketchat respect slack.

**Comment by jdashn** [comment]
I too would like to see this changed. Is there any chance of this moving forward soon? With our org using LDAP, and our usernames being what they are.. this would allow us to move from testing RocketChat to USING RocketChat -- Would a bounty help?

**Comment by danpospisil** [comment]
+1

**Comment by rajsardhara** [comment]
+1

**Comment by amenk** [comment]
can it also show the full name in the user list?

**Comment by amenk** [comment]
trying to make a PR ...

**Comment by jdashn** [comment]
Does #3851  Solve this? I know 3851 should be effecting not only channel list, but searches, mentions and direct messages list.

Maybe i'm missing something?

**Comment by amenk** [comment]
Yes, #3851 might solve this - saw it too late ... maybe #3851 can be merged soon?

**Comment by willihelm** [comment]
I would also appreciate this feature. In my company we have cases where the name of a user changed by marriage but it is too much work to change the sAMAccountName. So they are displayed with their old names in rocket.

**Comment by engelgabriel** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/6597
