### ISSUE TITLE
React to most recent message

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3240]
Slack has the ability to react to most recent message using a syntax like: `+:emoji_name:` which it applies to the most recent message.

**Comment by engelgabriel** [comment]
To avoid giving the reaction to the wrong message, we should capture the ID of the last message as soon as the user types + as the first character of the input field.

**Comment by louisemessage** [comment]
This is a feature in 2.10.5, so closing this issue.
