### ISSUE TITLE
Include reactions in mentions tab

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3241]
Something like slacks doing: It probably shouldn't alert you.  But at least be able to see some way what people reacted to.  👍 

![image](https://cloud.githubusercontent.com/assets/51996/15258052/feaa5ace-190e-11e6-85ea-76ae79e9da2a.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing, as this has been implemented.

Cheers
Thomas
