### ISSUE TITLE
Cannot run it on raspberry pi with snap

### ISSUE THREAD

**Issue by sciencekiller** [RocketChat/Rocket.Chat#32423]
As far as I know, the only version that support arm64 is snap version. I have tried to use docker, but it threw some errors, telling me that this app can't run on arm64 machine. So then I tried to use snap version, and the snap web page shows that it support arm64. After the package has been downloaded with the command "sudo snap install rocketchat-server", I get an error. It says 
```
- Run install hook of "rocketchat-server" snap if present (run hook "install": [ERROR] Your cpu does not support avx or avx2 instructions, which is required to run mongo 5.x, shipped with the next version of this snap.)
```
I know it means mongodb 5 cannot run on my machine and it is truly impossible to be solved, for mongodb official didn't support arm64. But I can successfully install mongodb4 on my machine, so I am wondering if I can use rocket chat with mongodb 4, or if anyone can come up with a better idea to make mongodb5 run on a raspberry pi. Any help is appreciated.

**Comment by reetp** [comment]
Thi sin't a bug per se- it is a packaging question.

I am not sure of the status of snaps on arm64 - you should ask in:

https://open.rocket.chat/channel/raspberrypi

I don't think Pis are a fully supported option so YYMV. 

There are Mongo 5 arm64 packages 

https://www.mongodb.com/try/download/community-edition/releases

But not sure whether that really helps you get Rocket running

Ask on open.rocket
