### ISSUE TITLE
Keep video active during screen sharing

### ISSUE THREAD

**Issue by disenchant** [RocketChat/Rocket.Chat#3243]
While in a video call, users can start sharing their screen with other users, which is great. Unfortunately as soon as a user shares his/her screen, only the screen is visible and the user's webcam/video is gone. It would be great to be able to still have the possibility to see the user even during the screen sharing to make the call more personal. (picture-in-picture instead of two steams?)
I hope the following mockup illustrates what I mean 😃 

How users would see a screen from an other user, that was shared with them (the person visible here is the one sharing his screen):
![desktop](https://cloud.githubusercontent.com/assets/686611/15261958/b466708c-195f-11e6-9403-f297cc515a86.jpg)

**Comment by disenchant** [comment]
This mockup might be even more clear, as it's actually based on a Rocket.Chat video call:

![ddfff4be-69e1-11e5-98f5-3dd951a9a9f5](https://cloud.githubusercontent.com/assets/686611/15262187/0580221e-1961-11e6-8fa9-9a7c7893ee6b.png)

**Comment by IQ2022** [comment]
very much WebRTC needed an improvement, it would be cool idea to show some sort of a sign on the channel, that there is video/sharing going on so people can join (if they are invited or if they are part of that room)... also have voice chat alone will be cool idea - to have voice chat...and can be totally moderated by Admin/moderators to mute users if not allowed to tlak.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
