### ISSUE TITLE
Add simple polls

### ISSUE THREAD

**Issue by disenchant** [RocketChat/Rocket.Chat#3244]
I think a lot of unnecessary discussions in rooms could sometimes be avoided by the possibility to create simple polls. Something similar than Twitter has introduced last year (https://blog.twitter.com/2015/introducing-twitter-polls) would be great. This feature  could be used in all kinds of cases, be it to decide where the team should go for lunch or finally settle on which programming language is the best.

**Comment by marceloschmidt** [comment]
We have created a simple integration script that kind of handle polls. Take a look at this gist, we'll make sure we add to our docs sometime soon. https://gist.github.com/sampaiodiego/db4b60717e7ac0051024dde23c6a902e

**Comment by unixfox** [comment]
Any plan to add this to the documentation ?

**Comment by dohseven** [comment]
Is it already implemented? The milestone is 0.31.0, but the /poll command does not seem to work.

**Comment by sevan6** [comment]
Hi @engelgabriel 
was this tested on 0.31.0 ?
Looks like /poll is not active on our instance (0.34.0)

Thx

**Comment by engelgabriel** [comment]
@sevan6 did you install the script from the link? https://gist.github.com/sampaiodiego/db4b60717e7ac0051024dde23c6a902e

**Comment by dohseven** [comment]
The "How to install" comment added by @graywolf336 under the script helped me enabling the polls, thanks!

**Comment by IQ2022** [comment]
i added the script, it doesnt seem to  work...

**Comment by k0nsl** [comment]
@IQ2022: and did you follow @graywolf336 instructions to the tee?

I just tested it and I got it working immediately.

**Comment by TheReal1604** [comment]
see https://github.com/RocketChat/Rocket.Chat/issues/3615#issuecomment-228091716
