### ISSUE TITLE
X-Content-Type-Options nosniif blocking javascript missing MIME type

### ISSUE THREAD

**Issue by crutchfield** [RocketChat/Rocket.Chat#32456]
### Description:

MIME type appears to be missing on javascript, meteor_runtime_config.js.

### Steps to reproduce:

1. Fresh install of 6.8.0 via docker
2. Register
3. Logout and attempt to log back in 

### Expected behavior:

Expected login screen or application to appear 

### Actual behavior:

Got "loading"  dots 
![image](https://github.com/RocketChat/Rocket.Chat/assets/7025068/09b84de7-708a-4667-9bf8-fab6123d764e)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.8.0
- Operating System: Amazon Linux 2023
- Deployment Method: Docker (Nginx reverse proxy)
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: (From docker image)
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version:  Firefox 115.10.0esr (64-bit), Chrome 124.0.6367.208 (Official Build) (64-bit)
- Operating System: Amazon Linux 2023 and Microsoft Windows 2022 Datacenter 

### Additional context

Get same behavoir from both linux/firefox and windows/chrome. 

### Relevant logs:

Firefox console

`The resource from “https://rocketchat2.pcms.internal/meteor_runtime_config.js?hash=b9db519591a16fd9eb3f010d6086859eb693e884” was blocked due to MIME type (“”) mismatch (X-Content-Type-Options: nosniff). rocketchat2.pcms.internal
`

Chrome console 
![image](https://github.com/RocketChat/Rocket.Chat/assets/7025068/33775ba3-e4f1-41d2-bd4a-07088762600c)

**Comment by crutchfield** [comment]
Falling back to release 6.7.2 does not have same issue.

**Comment by szmarczak** [comment]
Looks like a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/30717 https://github.com/RocketChat/Rocket.Chat/issues/30938

**Comment by crutchfield** [comment]
Agree it does appear to be a duplicate.

**Comment by DialogIntelligens** [comment]
Did you fix it?

**Comment by crutchfield** [comment]
The issues they referenced appear to still be open.  That is why I felt closing as a duplicate was appropriate.  Expecting them to address the issue through the earlier reported issue.
