### ISSUE TITLE
Incorrect Display of Participants Count in Calls with More than Three Participants in Web and Desktop Versions

### ISSUE THREAD

**Issue by CyberStranger** [RocketChat/Rocket.Chat#32474]
### Description:

After updating to version 6.8.0, an issue arises when creating a call in a room that involves more than three participants. In calls with more than three participants, the display in the call window incorrectly shows __usersCount__member_joined instead of displaying the correct number of participants. This issue appears to be specific to the web and desktop versions of RocketChat. Notably, the mobile versions on iOS 4.48 and Android 4.47 do not exhibit this problem and correctly display the participant count.

### Steps to reproduce:

1. Open RocketChat in a web or desktop environment.
2. Navigate to any room and initiate a call.
3. Have more than three users join the call.
4. Observe the participant count displayed in the call window.

### Expected behavior:

The call window should accurately display the number of participants once more than three users are involved.

### Actual behavior:

The call window displays __usersCount__member_joined instead of the additional number of participants.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.8.0
- Operating System:  Linux
- Deployment Method: Docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.21 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: RocketChat Electron 3.9.9, RocketChat Electron 3.9.14, Google Chrome 125, Mozilla Firefox 115.8.0esr
- Operating System: Microsoft Windows 10

### Additional context

![Clipboard - 23 мая 2024 г , 10 30](https://github.com/RocketChat/Rocket.Chat/assets/24211877/cefd0bdb-83c8-4178-80a1-923c1d7e2757)

**Comment by reetp** [comment]
Not sure if this is related to another issues with FF ESR - there is another bug about recently if you search.

Can you try testing on 6.9.x please?
