### ISSUE TITLE
Import not working 

### ISSUE THREAD

**Issue by vani-software** [RocketChat/Rocket.Chat#32476]
Cannot drag and drop some files. There is a issue about import You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".

**Comment by reetp** [comment]
Sorry but you need to create a proper bug template.

Describe your setup and exactly what you were doing or trying to achieve.

If you are writing code then you should ask for support in:

https://open.rocket.chat/channel/support
