### ISSUE TITLE
Show how many channels there are

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#3248]
I think the "More channels" should specify how many channels exists in total like Slack.
![11](https://cloud.githubusercontent.com/assets/17712562/15263593/d0dbc558-196b-11e6-9bf5-5b002ea81e4a.PNG)

Also perhaps add the search icon before "More channels" to make it stick out more, right now it's hard to find for some users.

**Comment by tgxn** [comment]
This is in develop as of [this pull request](https://github.com/RocketChat/Rocket.Chat/pull/3967)
Resolved #3248

**Comment by MartinSchoeler** [comment]
closed by #3967
