### ISSUE TITLE
Cyrillic in font Roboto

### ISSUE THREAD

**Issue by klaus-spb** [RocketChat/Rocket.Chat#325]
Seems font Roboto was taken without Cyrillic. And in cyrillic it does not work. Can you put font with cyrillic characters ?
![cyrillic](https://cloud.githubusercontent.com/assets/2184315/8820360/6521a99c-305d-11e5-87b6-ecf691add058.png)

**Comment by sampaiodiego** [comment]
hey @klaus-spb can you paste here some cyrillic characters so we can test it? thanks

**Comment by klaus-spb** [comment]
Это написано кириллицей.

Thanks

**Comment by marceloschmidt** [comment]
@klaus-spb could you please see if this has been fixed so we can close this issue? Thanks!

**Comment by klaus-spb** [comment]
Now fonts are looking good. Thanks
