### ISSUE TITLE
Personal data in your emails to customer

### ISSUE THREAD

**Issue by gv-eul** [RocketChat/Rocket.Chat#32519]
Dear Rocket.chat,

We have received several emails from you on 07/05/2024 and 15/05/2024 when there was an issue with the licences renewal. However, we noticed that your email was addressed to our colleagues on their first and last name. As far as we are aware we have not shared this information with you. 
Could you please let us know how this happened? PLease find attached an example.
thanks 

![Annotation 2024-05-29 104210](https://github.com/RocketChat/Rocket.Chat/assets/165013962/9790d010-64f5-4b27-ad19-f8ee0f7d4486)

**Comment by reetp** [comment]
Please read the privacy statement.

https://docs.rocket.chat/customer-center/legal-center/privacy-policy

If you have a paid for supported version then you can contact sales/support via your cloud workspace panel.

For the CE version there is a contact link there if you have further questions.

Closing as this is not actually a bug with RocketChat.
