### ISSUE TITLE
Can't upload .xlsx file

### ISSUE THREAD

**Issue by kramer65** [RocketChat/Rocket.Chat#3251]
Your Rocket.Chat version: 0.28.0

As the title says, I can't upload an .xlsx file. It says the file type is not supported. In a business environment I think it is quite important though, to support such common document files.

**Comment by marceloschmidt** [comment]
You can edit the file types allowed for upload.
Please see this issue https://github.com/RocketChat/Rocket.Chat/issues/3217 and this https://github.com/RocketChat/Rocket.Chat/issues/2946
