### ISSUE TITLE
Omnichannel Telegram can't receive a text file

### ISSUE THREAD

**Issue by tiaga** [RocketChat/Rocket.Chat#32529]
### Description:
It's not possible to receive a text file in Rocket.Chat that was sent to Omnichannel Telegram bot despite that `text/*` was added to Accepted Media Types. `text/plain` also has no effect.

### Steps to reproduce:
1. In Rocket.Chat go to Apps > Installed > Telegram > Settings and set "Accepted Media Types" to `image/*,application/zip,video/*,text/*`
2. Send a random text file (`.txt`) to the bot conversation in Telegram

### Expected behavior:
A text file is delivered to Rocket.Chat.

### Actual behavior:
A file isn't delivered to Rocket.Chat the error can be seen in logs.

### Server Setup Information:
- Version of Rocket.Chat Server: 6.7.2
- Operating System: Debian 11 (inside Docker image)
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: 14.21.3 (inside registry.rocket.chat/rocketchat/rocket.chat:6.7.2)
- MongoDB Version: 5.0.23 (bitnami/mongodb)

### Client Setup Information

- Desktop App: 3.9.14
- Operating System: Linux Mint 21.3

### Additional context
Probably related to [#25942](https://github.com/RocketChat/Rocket.Chat/issues/25942).

### Relevant logs:
The following can be found in Docker container logs:
```
[Telegram App] Something went wrong while trying to upload the file for telegram user in room tf6ZfP2eyQakCxm8f TypeError: fileType is not a function
    at determineFileType (ee/lib/misc/determineFileType.js:12:23)
    at app/apps/server/bridges/uploads.ts:54:18
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by reetp** [comment]
Closing in favour of:

https://github.com/RocketChat/Rocket.Chat/issues/31906
