### ISSUE TITLE
Omnichannel Telegram blacklist support

### ISSUE THREAD

**Issue by tiaga** [RocketChat/Rocket.Chat#32530]
**Is your feature request related to a problem? Please describe.**
It's not possible to block a Telegram user in Rocket.Chat Omnichannel (Telegram integration), thus a user can easily flood you with messages.

**Describe the solution you'd like**
An ability to block Telegram users on Rocket.Chat Omnichannel side (for instance in Telegram integration settings) to ignore messages from them.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by reetp** [comment]
This is a feature request rather than a bug.

Please open this in the feature request repo.

https://github.com/RocketChat/feature-requests

Thanks.
