### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by lil5** [RocketChat/Rocket.Chat#32537]
Full screen error message on rocket chat's website: https://developer.rocket.chat/fuselage-design-system/conventions only happened the first load, afterwards the errors still exist in the console but the black error screen is gone.

<img width="1282" alt="Screenshot 2024-06-01 at 23 05 42" src="https://github.com/RocketChat/Rocket.Chat/assets/17646836/5ac50c76-5ce0-4ffc-aed1-65f7d3bc12aa">

**Comment by reetp** [comment]
This should be opened against the documentation repos as it isn't a bug in rocket.chat itself.

Sorry I can't move it.

Please reopen in the correct repo - either documentation or developer documentation.

Thanks.
