### ISSUE TITLE
Omnichannel Telegram can't send a zip file on Windows

### ISSUE THREAD

**Issue by tiaga** [RocketChat/Rocket.Chat#32538]
### Description:
It's not possible to send a zip file using Rocket.Chat on Windows through Omnichannel to Telegram. The following error appears:
![image](https://github.com/RocketChat/Rocket.Chat/assets/10153548/d252bc2b-2a5c-4a1b-ac7a-dfce83c6b817)
On Linux it works okay for the same file.

### Steps to reproduce:
Send a random zip file from Rocket.Chat on Windows through Omnichannel to Telegram.

### Expected behavior:
A zip file is sent from Rocket.Chat to Telegram.

### Actual behavior:
A zip file isn't delivered from Rocket.Chat to Telegram and the following error appears:
```
Sorry!! This file was not shared because files with this type of extension is not allowed
```

### Server Setup Information:
- Version of Rocket.Chat Server: 6.7.2
- Operating System: Debian 11 (inside Docker image)
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: 14.21.3 (inside registry.rocket.chat/rocketchat/rocket.chat:6.7.2)
- MongoDB Version: 5.0.23 (bitnami/mongodb)

### Client Setup Information
- Desktop App: 3.9.14
- Operating System: Windows 11

### Additional context
Probably it's caused by the fact that Windows systems use `applicaiton/x-zip-compressed` instead of `application/zip` and this mime type isn't allowed. Same behavior can be seen on Windows in Google Chrome.

### Relevant logs:
_There are no any messages from the server_

**Comment by reetp** [comment]
Closing in favour of:
 https://github.com/RocketChat/Rocket.Chat/issues/31906

Please follow up there.
