### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Ruun** [RocketChat/Rocket.Chat#32539]
### Description:

there is a broken link on the rocket.chat website

### Steps to reproduce:

1. 
https://www.rocket.chat/community
3. 
<img width="351" alt="Screenshot 2024-06-02 at 9 49 32 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/76751124/ff31c2dd-5588-450f-8cb1-7b8997b88c87">
5. 
<img width="903" alt="Screenshot 2024-06-02 at 9 49 46 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/76751124/0086a467-1328-4ddc-9006-ec73b19834dd">

### Expected behavior:

bring me to https://university.rocket.chat/
### Actual behavior:

<img width="903" alt="Screenshot 2024-06-02 at 9 49 46 PM" src="https://github.com/RocketChat/Rocket.Chat/assets/76751124/0086a467-1328-4ddc-9006-ec73b19834dd">

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by userAdityaa** [comment]
Hey, I would like to work on this issue. But can anyone help me find the file location for fixing this ?

**Comment by Ruun** [comment]
I have been looking for the file. Haven’t found it yet but if I do I will let you know

**Comment by Tony-Stark-Jr** [comment]
Hello, @Runn I can't find step 3 in your given link https://www.rocket.chat/community. So, can you please me to generate this issue first.

**Comment by Ruun** [comment]
They removed it
