### ISSUE TITLE
Rename `unread rooms` to `unread`

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#3253]
To avoid confusion - since _room_ is not used anywhere else on UI

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, since IMO this has been implemented:

![image](https://user-images.githubusercontent.com/179595/36228091-77f84850-11d3-11e8-9d0c-fe39de3a7c46.png)


Cheers
Thomas
