### ISSUE TITLE
 support window notification

### ISSUE THREAD

**Issue by wanderlage** [RocketChat/Rocket.Chat#32546]
### Actual behavior:

We received an email informing us that our workspace version is out of compliance.
The current version is 6.7.1 which is in active support until October.
The email states version 6.5.4.
How to proceed?

### Server Setup Information:

- Version of Rocket.Chat Server:  6.7.1
- Operating System: 
- Deployment Method: Docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version:  v14.21.3
- MongoDB Version: 6.0.10 / wiredTiger (oplog Enabled)

![image](https://github.com/RocketChat/Rocket.Chat/assets/30476005/c676aa21-ffac-408d-a50d-9476c59985e9)

![image](https://github.com/RocketChat/Rocket.Chat/assets/30476005/d55d62ec-5fd9-4a67-987f-be0363394bd3)

**Comment by xbiafra** [comment]
We have the same issue, currently we use the newest version 6.9.0

<img width="363" alt="Zrzut ekranu 2024-06-4 o 10 15 31" src="https://github.com/RocketChat/Rocket.Chat/assets/41372417/16d006d8-49ec-4178-b23f-c20ce0d6a012">


Non-admin user get this notification:
![image](https://github.com/RocketChat/Rocket.Chat/assets/41372417/d6178d4d-89c1-47c5-a8f3-5f605a1ff2a1)

Whats more we were notified by email that we use v6.5.0 which is outside of our support window while it's not true.

**Comment by reetp** [comment]
I think your system is out of sync with your cloud panel.

See this:

https://forums.rocket.chat/t/received-msg-you-are-running-v6-5-0-which-is-outside-of-our-support-window/20082

Please check, and resync.

**Comment by xbiafra** [comment]
Hmm but how to do it if rocket is in state:
**Workspace registered**

I can't find option to unregister or provide new token.

**Comment by reetp** [comment]
Have you checked 

a) your workspace status in your cloud panel. Ensure you have the right server.

b) Admin/Subscription/Sync Licence Update

**Comment by geekgonecrazy** [comment]
> Whats more we were notified by email that we use v6.5.0 which is outside of our support window while it's not true.

In your case you've registered the same workspace address with a couple of different accounts.  Looks like a test account workspace is back on 6.5.0 and its alerting on that workspace.

For your case since you did include a screenshot containing workspace address i've fixed so you won't get emails about that workspace any more.

**Comment by wanderlage** [comment]
@geekgonecrazy , 

Where would we get information on what version the workspace (https://cloud.rocket.chat/) is?
Why is it that when I synchronize (Sync License Update) an error is not returned.

**Comment by reetp** [comment]
The management panel at cloud.rocket.chat doesn't show your local registered version.

No idea why not.

If you sync your licence with no error you should be ok.

Check your logs and admin/info.
