### ISSUE TITLE
Inconsistent Markdown Formatting in Custom Status Field

### ISSUE THREAD

**Issue by Giridharan002** [RocketChat/Rocket.Chat#32544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Ubuntu 22.04.4

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.19.14

### Rocket.Chat Server Version

6.7.0-develop

### Describe the bug

When attempting to set a Custom Status in the Rocket.Chat desktop app, I've encountered an issue with markdown formatting for bold and italic text. Traditionally, in message fields, wrapping a word in asterisks (*) makes it bold, and wrapping it in underscores (_) makes it italic. However, this expected behavior is not consistent when applying the same formats in the Custom Status field.

### How to Reproduce

Open the Rocket.Chat desktop app.
Click on the profile Avatar at the top left corner
Click on the Custom Status field.
Attempt to format text as bold by wrapping it in asterisks (*) or as italic by wrapping it in underscores (_).

### Describe your Expected behavior

Text that is wrapped in asterisks (*) should be displayed in bold
Text that is wrapped in underscores (_) should be displayed in italic.

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by secretkontributer** [comment]
Is this bug still prevelent?
I wanna start working on it
