### ISSUE TITLE
Quote reply below own text is irritating

### ISSUE THREAD

**Issue by rahra** [RocketChat/Rocket.Chat#32543]
If I quote-reply in a conversation, the quoted text appears below my text.

This is pretty irritating since it behaves different from all other messengers on this world, where the own text is below the quoted next and not above.

I suggest to reverse this since it is against the natural read order and against what one is used from other messengers.

**Comment by reetp** [comment]
This isn't a bug per se as nothing is actually broken. It just doesn't work the way you want it too.

So it's a feature request and shoukd be moved there.

I think there are several duplicates around if you search.

**Comment by rahra** [comment]
Yes, I agree, this isn't a bug, but I didn't say that. I just wanted the highlight that. 
I think that I'm not the only one stumbling on this since most messengers behave different which makes sense because of the natural order of reading top down.

**Comment by reetp** [comment]
And as I said that makes it a feature request.

Closing in favour of:

https://github.com/RocketChat/feature-requests/issues/688

Please follow up there (have a search for 'quote') to see other requests as well:

https://github.com/RocketChat/feature-requests/issues?q=is%3Aissue+quote+
