### ISSUE TITLE
blackout windows app without using 5 hours over.

### ISSUE THREAD

**Issue by ninetiger99** [RocketChat/Rocket.Chat#3255]
Your Rocket.Chat version: (make sure you are running the latest)
0.30.0 using docker

rocket.chat windows app without using 5 hours, than black-outed app screen.
for more detail, please check attachment screenshot file.
that file include Debug console print.
"Error during WebSocket handshake:" ...

after blackout, I reload the page, then, work good.
but, without using 5 hours over, then, blackout again. 

Currently, I confirm this bug only windows platform. 

![blackout](https://cloud.githubusercontent.com/assets/7449353/15283281/38110278-1b84-11e6-923e-06bc879c9120.png)

**Comment by edonit-moitend** [comment]
Do you have the latest version from https://rocket.chat of the Windows application which is 1.3.1? After upgrading to this version we did not have this problem anymore.

**Comment by ninetiger99** [comment]
You are great! 
Just update windows version rocket chat, then fix it!  

Thank you for your help.
