### ISSUE TITLE
Desktop app Icon not flashing upon new notificatoin in the taskbar when minimized [V4.0.0]

### ISSUE THREAD

**Issue by Ahmad-Ali-com** [RocketChat/Rocket.Chat#32560]
If the desktop app is minimized then upon receiving new notifications it used to flash in the taskbar but now it does not, however it is flashing if not minimized like another application window is active then it flashes but currently i am missing updates because i am used to minimize it when not using. 

![image](https://github.com/RocketChat/Rocket.Chat/assets/45877486/410c49bd-8514-4f98-a09d-9dc005981e65)

**Comment by reetp** [comment]
Hi,

this needs to be in the Electron repo here:

https://github.com/RocketChat/Rocket.Chat.Electron/issues

Unfortunately I can't move it. 

Please re-open in the Electron repo.

Also fill out a proper template with server version etc which aids debugging.
