### ISSUE TITLE
add tableflip

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#3257]
Since /shrug " (  ¯\_(ツ)_/¯  ) was added, /tableflip & /unflip should be added as well :).

/tableflip = (╯°□°）╯︵ ┻━┻
/unflip = ┬─┬﻿ ノ( ゜-゜ノ)

@geekgonecrazy  ;)

**Comment by wildaces215** [comment]
I would like to take this bug.

**Comment by geekgonecrazy** [comment]
@wildaces215 I don't believe anyone else is working on it.  Have at it! Mention me in your pull request and i'll take a look 😄

**Comment by wildaces215** [comment]
Ok since I am new at contributing to open source where is the code for me to fix?

**Comment by wildaces215** [comment]
Where is the emojis located?

**Comment by subesokun** [comment]
I guess there are several files you need to touch, see https://github.com/RocketChat/Rocket.Chat/search?utf8=%E2%9C%93&q=shrug

**Comment by geekgonecrazy** [comment]
@wildaces215 its actually not an emoji its a slash command.  Please take a look at the package located here: https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-slashcommands-shrug

Basically you would just need to copy this package and replace the text being inserted.  Should be pretty easy.  👍 

To get it to show up in rocket.chat after you made the changes modify the .meteor/packages file and add your new package along with the other slashcommands: https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/packages#L85

**Comment by wildaces215** [comment]
I am trying to create  a pull request but its not working. Says that I'm not authorized to do so. What am i doing wrong?

**Comment by geekgonecrazy** [comment]
The process you need to follow is: fork->edit the files get everything working in your fork->then open a pull request to our repo

**Comment by wildaces215** [comment]
Created the pull request, when you get a chance @geekgonecrazy
