### ISSUE TITLE
Separate Favorite Channels and Users in Favorites List

### ISSUE THREAD

**Issue by lam-nya** [RocketChat/Rocket.Chat#32602]
Currently, channels and users marked as favorites are mixed in a single list. This can be cumbersome to navigate.

Proposed Solution:
Split the Favorites list into two distinct sections:
1. Favorite Channels
2. Favorite Users

Modify the UI to display these sections separately, while maintaining sort order within each section.

Optionaly add an option in Settings to enable or disable this feature.

Thank you for considering this enhancement to improve user experience.

**Comment by reetp** [comment]
Closing this as rocket isn't broken. It just doesn't work the way you want which belongs here

https://github.com/RocketChat/feature-requests/issues

If you search there you will find there have been several requests for menu enhancements.

I think some were promised but never delivered.

If you open this there I'll have a look and find out what's happening. Features are on my (long) todo list.

Thanks.
