### ISSUE TITLE
Email Id validation is not working properly 

### ISSUE THREAD

**Issue by sudharsan4252** [RocketChat/Rocket.Chat#32617]
### Description:
The email validation is not working, I tried to create Saas account with my mail it turns red input not able to submit

### needed warning or **ERROR MESSAGE ** so that we can know what is the error 
Or there is issue with the code itself Dont know 

### Steps to reproduce:

1. Go to  https://www.rocket.chat/trial-saas
2. Complete the form 
3. use your mail id  there wont be any error popping but input turns red 
4. unable to create account

### Actual behavior:

![Screenshot 2024-06-17 133652](https://github.com/RocketChat/Rocket.Chat/assets/115398156/92a78d7d-a634-43ca-b2a2-85745029e22a)
###

**Comment by reetp** [comment]
I think you need to use a proper email address and not a gmail one.

At a guess you aren't based in the EU either.

This isn't a bug in Rocket.Chat code.

Please ask for assistance in:

https://open rocket.chat #support

**Comment by reetp** [comment]
For reference


> Organization Email: 
> Provide an organization email ID. This is required to access Rocket.Chat cloud and verification emails. 
> **It cannot be a personal email ID.**

https://docs.rocket.chat/setup-and-configure/trials/saas-trial

**Comment by sudharsan4252** [comment]
@reetp  It would be nice if there is any error or pop up message showing enter your email or organisation mail, I can't figure out why I can't create account till you tell
