### ISSUE TITLE
Clearing Custom CSS doesn't reset original CSS style

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3261]
I have pasted a custom CSS in error, clearing it out doesn't bring back original style.. 

`
body{
  font-family: 'Open Sans', sans-serif;
  background:#3498db;
  margin: 0 auto 0 auto;  
  width:100%; 
  text-align:center;
  margin: 20px 0px 20px 0px;  
}

p{
  font-size:12px;
  text-decoration: none;
  color:#ffffff;
}

h1{
  font-size:1.5em;
  color:#525252;
}

.box{
  background:white;
  width:300px;
  border-radius:6px;
  margin: 0 auto 0 auto;
  padding:0px 0px 70px 0px;
  border: #2980b9 4px solid; 
}

.email{
  background:#ecf0f1;
  border: #ccc 1px solid;
  border-bottom: #ccc 2px solid;
  padding: 8px;
  width:250px;
  color:#AAAAAA;
  margin-top:10px;
  font-size:1em;
  border-radius:4px;
}

.password{
  border-radius:4px;
  background:#ecf0f1;
  border: #ccc 1px solid;
  padding: 8px;
  width:250px;
  font-size:1em;
}

.btn{
  background:#2ecc71;
  width:125px;
  padding-top:5px;
  padding-bottom:5px;
  color:white;
  border-radius:4px;
  border: #27ae60 1px solid;

  margin-top:20px;
  margin-bottom:20px;
  float:left;
  margin-left:16px;
  font-weight:800;
  font-size:0.8em;
}

.btn:hover{
  background:#2CC06B; 
}
# btn2{

  float:left;
  background:#3498db;
  width:125px;  padding-top:5px;
  padding-bottom:5px;
  color:white;
  border-radius:4px;
  border: #2980b9 1px solid;

  margin-top:20px;
  margin-bottom:20px;
  margin-left:10px;
  font-weight:800;
  font-size:0.8em;
}
# btn2:hover{

background:#3594D2; 
}
`
Cleared top code and set it to left, and then delete it again, still doesnt show original CSS..
site

https://chat.seekingoptions.com

check CSS in your Dev tool.

Your Rocket.Chat version: (0.30)

**Comment by marceloschmidt** [comment]
Yes, thanks for that. It currently requires a valid CSS, so if you input 
```
body { }
```
it would revert your changes. We'll work on fixing that.

**Comment by MartinSchoeler** [comment]
@IQ2022 this was already fixed
