### ISSUE TITLE
Got error code 400 for token

### ISSUE THREAD

**Issue by artemChernitsov** [RocketChat/Rocket.Chat#32638]
### Description:

I have an issue with a white-label React Native app and push notifications. For some reason, push notifications have stopped working. I recreated the entire environment from scratch following the manual. From the logs, it appears APN is configured, but for some reason, the user token received a 400 error.

### Relevant logs:

```
root-rocketchat-1  | {"level":20,"time":"2024-06-19T19:44:41.679Z","pid":1,"hostname":"ecc71194099a","name":"Push","msg":"APN configured"}

```
```
root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.149Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"send message \"@artem.chernitsov\" to userId 'iKs6eCZFdFSrCPvHr'"}
root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.150Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"send to token {\"apn\":\"b32eaffc68005e5238d2301c44ceb73ed380e531bf48d26304eee8eb65e4723c\"}"}
root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.151Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"send to token {\"apn\":\"b32eaffc68005e5238d2301c44ceb73ed380e531bf48d26304eee8eb65e4723c\"}"}
root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.164Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"Sent message \"@artem.chernitsov\" to 1 ios apps 0 android apps"}
root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.869Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"Got error code 400 for token b32eaffc68005e5238d2301c44ceb73ed380e531bf48d26304eee8eb65e4723c"}
root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.870Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"Removing token b32eaffc68005e5238d2301c44ceb73ed380e531bf48d26304eee8eb65e4723c"}
```

**Comment by reetp** [comment]
This is likely a bug in your code/app and not Rocket.Chat itself.

Have you followed this?

https://forums.rocket.chat/t/attn-custom-mobile-apps/20012

If you still require support/assistance then ask in https://open.rocket.chat #react-native

**Comment by artemChernitsov** [comment]
Please, check the logs.
The issue with iOS app, not Android
`root-rocketchat-1  | {"level":20,"time":"2024-06-19T20:32:53.164Z","pid":1,"hostname":"448d3c63be08","name":"Push","msg":"Sent message \"@artem.chernitsov\" to 1 ios apps 0 android apps"}`

**Comment by reetp** [comment]
If yoi have built your own app it's still a support issue.

Please ask in the correct place as above.
