### ISSUE TITLE
integration rocket chat with zimbra

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#3265]
Your Rocket.Chat version: 28.0.0

It is possible to integrate rocket chat with Zimbra using zimlet?

**Comment by MartinSchoeler** [comment]
Documentation for our Integrations can be found [here](https://rocket.chat/docs/administrator-guides/integrations). If you have any further questions please  ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat). Thanks!
