### ISSUE TITLE
Installation does NOT ALLOW to SKIP "Register Workspace" with your CLOUD service and agree to your terms etc 

### ISSUE THREAD

**Issue by jittygitty** [RocketChat/Rocket.Chat#32658]
### Description:

I just did a fresh "SELF-HOSTED" install of this rocket-chat. But i found it sketchy when it started asking for organization details, like even size, how many people etc and other info, all 'required' with no option to leave blank. Then when you go to next page it got even WORSE, you're greeted with some info as if you just signed up for some CLOUD SERVICE when here you were trying to AVOID all that and went through all the hassle to install everything SELF-HOSTED.

So please tell us, HOW do we get rid of that page to agree with YOUR PRIVACY policy and to REGISTER WORKSPACE with your CLOUD? I don't want to agree to anyone's privacy policy, I don't want to share data, and I don't want to register with your cloud at all. I just want to run rocket-chat off my server, that's it. thanks

### Steps to reproduce:

Do a fresh install of Rocket-Chat, then start it on http://yourIP:3000

**Comment by reetp** [comment]
This is a support issue, not a bug.

Note that Rocket.Chat is open source, but that relates to reading and modification of code.

I believe you have to register even for CE. You can do that offline - see the docs.

Please ask on open.rocket.chat #support 

Thanks.

**Comment by reetp** [comment]
I believe you can possibly bypass the registration screen with this but I am not sure what will work.

`
OVERWRITE_SETTING_Setup_Wizard: completed
`

**Comment by jittygitty** [comment]
I tend to think that this is not a support question, because it seems more like a bug to not have the option to skip the cloud registration and privacy policy on a "self-hosted install" without modifying the source code. 

Sending people away to a secluded chat and closing this ticket quickly will prevent others from being aware of this problem beforehand or seeing a solution. (And 'if' that's on purpose, I think it's not the right way to deal with this. ) 

Kindly offer the "solution" here, where a lot more people can see and benefit, versus some chat room. I thought I had tried something similar to what you said, in mongosh but it did not seem to work. Thank you!

**Comment by jittygitty** [comment]
In case it helps others, I was able to skip the registration of workspace and agreement to privacy policy but it is important that we receive "CLARIFICATION"  that setting the environment variable to "COMPLETED" if in fact it SKIPS it instead of actually marking you off as having truly "completed" the registration and agreed to their privacy policy etc.

Setting it in db fields in mongosh didn't work, the only thing that worked was creating environment variable of OVERWRITE_SETTING_Setup_Wizard and setting it to "completed". Again would be nice to have it say "skipped" instead of "completed", because we obviously do NOT want to "complete" it, so hopefully in effect it does do an OPT-OUT.

**Comment by jittygitty** [comment]
I'm guessing you represent the RocketChat company or the developers in some way? (Since it seems you can close other people's tickets, Or can anyone close anyone else's tickets and I'm just blind and didn't notice how?)

If that's the official message that you are delivering to us, if you're saying that we should get used to further efforts to force us who "self-host" to sign onto the cloud, that makes me wonder if such a company is in favor of open source in the long-run, or if it was just the plan to garner quick publicity and widespread usage which it wouldn't have achieved without an open source license. I hope such worries can be alleviated, since these forced registrations are worrisome.

I do know what a truly open source license such as MIT was meant for, especially in contrast to AGPL license or an "open source" proprietary license. Is there any plan going forward for a gradual move to a more proprietary model?

Because I think it's a fair concern that if those behind a project are so "determined" to force something on everyone, even self-hosted, that this desire at some point may very well lead to a license change if it's "easily foiled" in the code.

Also, to me communication on github is "gold", it's like going on "record", compared to some chat in a chatroom that does not get indexed by any search engine and can disappear without anyone really noticing, it's like private vs public.

You have a right to license and do as you wish of course, I just simply want to know which way this is going, since I'm just starting to use it and it would be a good time for me to switch if the license will not remain MIT. One big reason I wanted to get on board with this project was specifically because you actively advertise yourselves as different from those other companies just pretending to love open source:

https://www.rocket.chat/platform/open-source
"Rocket.Chat holds an MIT license
Our MIT license is very permissive, and we don’t force copyleft. Unlike a few other providers that hold AGPL licenses, Rocket.Chat doesn’t force its customers to open source their new, internally created products."

The MIT license is great for us end users who want to self-host.
I'm hoping that remains so. Thanks!

**Comment by reetp** [comment]
A bug tracker is to track bugs.

This isn't one. That's it.

There are no plans I am aware of to change the licencing.

Equally the licencing does not prevent Rocket insisting on registration, or charging for services.

(You probably ought to go back and read some history here, and my involvment in it)

You can of course fork it, and within the licence terms do whatever you want with it if you aren't happy.

Please, continue this discussion on open, or the forums, which are the right places for discussions on open source.

Ask me anything you want there (you can always screenshot posts if you feel it is necessary to make it more "public") and I'll be happy to discuss it.

 Thanks.

**Comment by jittygitty** [comment]
@reetp Well I've laid out my concerns already, and for now I got my problem solved and skipped registration. If you can send me a link where I can read the history you were referring to I'd appreciate it and I'll try to read up when I have time.
Thanks for your reply.

**Comment by reetp** [comment]
You don't need to @ anyone

There is a search feature here, in the forums, and open if you are interested enough.

I'd also suggest you have a read about what open source really is, and what "free" software really means.

Thanks.

**Comment by jittygitty** [comment]
Sure, if you can't link to any starting point, I'll try search for the 'history' you mentioned when I have time to search etc. take care

**Comment by reetp** [comment]
Please read the docs.

https://docs.rocket.chat/docs/license-application

> Unregistered workspaces are no longer supported. 

You can air gap an install but will still need a licence.

Again, please understand the difference between 'Free' and 'open source'

Please direct any further questions to the forums or https://open.rocket.chat

Thanks.

**Comment by reetp** [comment]
> I apologise but I'm not gonna sign up on this website because I prefer my answers to be indexed by search engines to help more people who will have this problem.

No need to apologise.

However, this is not a bug.

The answers are already here, so no one is missing anything.

You can discuss further on the forums if you wish. They are open and indexed. So no need to worry about anything being missed.

> Rocket Chat has a free tier so I don't get why I would need a license.

Rocket.Chat has a "Community Edition" with licencing conditions. Do not confuse that with "free".

Again, please appraise yourself of "open source".

The source code is there for you to read and use. That does not mean you don't need to register or get a licence regardless of the "tier".

To continue this discusion please use an appropriate forum.

https://forums.rocket.chat
https://open.rocket.chat

Thanks.

**Comment by jittygitty** [comment]
ItsQuadrus, take a look at https://github.com/RocketChat/Rocket.Chat/issues/31163#issuecomment-2191060240
You can have iptables to mark/track outgoing attempts as well. 

As far as I know, rocketchat community edition that's available here is MIT licensed. Therefore, you shouldn't need any other license, if there is some other license mechanism you would be free to remove it from the code completely. My concern was indeed that the seeming shifting attitude of the developers may lead them to "change" the MIT license.

Again, in a previous comment here (above) I quoted their website:
https://www.rocket.chat/platform/open-source
"Rocket.Chat holds an MIT license
Our MIT license is very permissive, and we don’t force copyleft. Unlike a few other providers that hold AGPL licenses, Rocket.Chat doesn’t force its customers to open source their new, internally created products."

So obviously if that is true, then you absolutely do "not" need to register or get any license from them since it is MIT.

If they wish to change that, and to force registering or getting some other license, they'll need to "ditch" MIT license.

**Comment by reetp** [comment]
Note - I am not a Rocket employee.

I have been a community member since not long after Rocket open sourced (I've been involved with open source for over 25 years). A few years ago I worked for Rocket.Chat for a short period as community manager. Part of the reason I left was my concerns about changes in CE and licencing......

I am a trusted community member here now, and though I do not speak for the company, I know the company philosophy and how some of this works.

Their answers likely won't diverge much from mine.

------------

MIT is the licence under which you can use and redistribute code.

It *does not* state whether the developer  can or can't enforce some form of registration for use.

It *does* permit you to modify the code as you wish, so you can fork it and remove anything you object too, as long as you keep the licence in the code.

However, remember that though EE code is publicly published - ie open source -  it is under a different licence and cannot be used in the same way as CE code.


> If they wish to change that, and to force registering or getting some other license, they'll need to "ditch" MIT license.

Actually, no they don't.

As advised the MIT licence does not prohibit registration, and you have the ability to modify said code if you choose. Don't like it? Remove it.

As far as I am aware there are no current plans to do that. I have long fought to keep as much 'free' as long as possible. Believe me, things could have been far more restrictive than they currently are.

But be careful what you wish for. Rocket.Chat have to make some money somehow, or they go bust, and you get no "free" code at all.

Rocket.Chat could enforce a different licence, or stay with MIT and restrict access to paying customers only. Then what are you going to do?

Note what happened at RedHat and their "open source" GPL licenced software......

I suggest you read about that and have a long hard think about the implications.

I know none of this is what you want to hear, but that is because you misunderstand what open source really means. It is not a free lunch, or free beer.

Remember, you could take the CE source remove restrictions, and add your own registration!!

Personally I might don't always agree entirely with some aspects here (and quietly fight for the community) but I do understand how and why.

As I have said repeatedly, you can talk to me in more depth on the forums (entirely public) or open for more information.
