### ISSUE TITLE
MacOs Rocket.Chat microphone problem

### ISSUE THREAD

**Issue by devopsalexandr** [RocketChat/Rocket.Chat#32659]
### Description:

After any calls by Rocket.Chat I have problem with mic in an another programs until fully kill browser process.

### Steps to reproduce:

1. start a call from client (it will be opened in browser)
2. End the call
3. try check mic in (Setting -> Sound -> Input) check voice.

### Expected behavior:

After a call you can use your mic as well 

### Actual behavior:

Nobody hear me after call by Rocket

### Client Setup Information

- Desktop App or Browser Version: Rocket.Chat 4.0.0 , Safari Version 17.5 (19618.2.12.11.6)
- Operating System: Sanoma 14.5 

### Additional context

I must kill all Safari processes and mic will be available in an another programs

**Comment by reetp** [comment]
Please fill in the bug template with your server details.

Please make sure you also test on 'latest' and not an older version as bugs get fixed regularly.

**Comment by devopsalexandr** [comment]
> Please fill in the bug template with your server details.
> 
> Please make sure you also test on 'latest' and not an older version as bugs get fixed regularly.

I haven't access to the server, but I use latest version from app store.

**Comment by reetp** [comment]
Have you spoken to your server admin?

We need more detail before we can investigate.

**Comment by devopsalexandr** [comment]
Okey  I will try, but I think it is a local problem with mic capture. 
it's not problem on the server side, it is problem on the client, it doest frees the mic

**Comment by reetp** [comment]
Yes I agree, but we need to know what version of the server we are dealing with.

If it is old it will not get fixed.

**Comment by devopsalexandr** [comment]
The version on the server is 6.6.1

**Comment by reetp** [comment]
So you should be at least on the latest version:

https://github.com/RocketChat/Rocket.Chat/releases/tag/6.6.10

For testing please use at least 6.9+ - we need to try and eliminate that if possible. You could possibly test on open.rocket.chat

This is the bug template that you should have filled in with the server information.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

I have raised this internally and it may need moving, but I am waiting more information.

**Comment by reetp** [comment]
I have asked someone to take a look but to fix it we have to be able to try and reproduce it.

> I must kill all Safari processes and mic will be available in an another programs

This comment leads me to suspect this is likely an issue with Safari itself not releasing the mic, rather than the Rocket.Chat Electron app.

Someone will take a look at some point, but I am not sure whether there is much we can do.

Thanks for your patience.

**Comment by devopsalexandr** [comment]
When i use google meats, zoom, discord etc in my browser, after call i haven't any problem, only with Rocket :(

**Comment by reetp** [comment]
> When i use google meats, zoom, discord etc in my browser, after call i haven't any problem
Each of those uses a different method to make a call.

When you make a call in Rocket.Chat and it opens in Safari, what calling application are you using? 

Jitsi? Something else?

**Comment by devopsalexandr** [comment]
Yes Jitsi.

**Comment by reetp** [comment]
Is that meet.jit.si or your own hosted Jitsi?

**Comment by devopsalexandr** [comment]
it is own hosted Jitsi

**Comment by reetp** [comment]
Your Jitsi version is 2 years old.


![Screenshot_20240626_143943_GitHub.jpg](https://github.com/RocketChat/Rocket.Chat/assets/3800384/ab78e562-cb8d-40c1-80c9-7bb8d5814243)


I really suggest you get up to date as I think the issue likely lies more with Jitsi/Safari than Rocket.Chat

That will probably cure some of you issues.

**Comment by devopsalexandr** [comment]
how i can use Rocket.Chat client directly for a calls?

**Comment by reetp** [comment]
> how i can use Rocket.Chat client directly for a calls?

I don't believe you can, and haven't been able to for quite some time.

Rocket.Chat offloads it to Jitsi/Google Meet etc.

You probably need to talk to your server admin.

**Comment by casalsgh** [comment]
@devopsalexandr this is most likely a problem with jitsi version as pointed by Reetp. Please speak with your admin when possible to upgrade the app version and that should do the trick. 

At the moment Rocket.Chat rely on this external solutions for video conferencing. You have options like Jitsi, Google Meet and Pexip, but all will require server admin to set those up. 
Reference if needed on meet -> https://docs.rocket.chat/docs/google-meet-app
