### ISSUE TITLE
CPU Overload with Rocket 3.9.14

### ISSUE THREAD

**Issue by agnusfatts** [RocketChat/Rocket.Chat#32651]
We've observed strange behavior in Rocket Chat, which involves very high, sudden CPU load that is unrelated to the current activities being performed. Rocket Chat is running in a Dockerized environment managed by Portainer. The host has 16 CPUs and 25 GB of RAM and is not under heavy load. Rocket version Rocket 3.9.14

- Version of Rocket.Chat Server:  6.9.1
-  license tyoe: free (community)
- number of users: 135

![overload](https://github.com/RocketChat/Rocket.Chat/assets/75703269/890c2038-806a-4944-96d0-3e8218a489d4)

**Comment by reetp** [comment]
Please fill out a proper template.

Rocket version (current is 6.9.2), licence type, and number of users are required.

**Comment by reetp** [comment]
Have you checked running processes?

Is it actually Rocket, or another process?

You need to do some digging on your server to see what is causing this.

**Comment by agnusfatts** [comment]
We've been working on this for a long time. After many tests and trials, we concluded that one of the channels was the cause. After removing it, the situation seems to have improved. We are still analyzing what exactly could have caused this, as nothing significant was happening on that channel. It`s working on VMware virual machine located  on HPE Alletra storage. It`s  (it was) a Rocket process.

**Comment by reetp** [comment]
Ok thanks for letting us know.

If you have further information please come back here.

**Comment by Roshanpanji** [comment]
@agnusfatts 

> We've been working on this for a long time. After many tests and trials, we concluded that one of the channels was the cause. After removing it, the situation seems to have improved. We are still analyzing what exactly could have caused this, as nothing significant was happening on that channel. It`s working on VMware virual machine located on HPE Alletra storage. It`s (it was) a Rocket process.

I've been facing the same issues for the last 2 months,
Can you help me how you found the channel which is causing the issue, is there is any way to find the memory and CPU usage per channels?
