### ISSUE TITLE
How to verify email address : HTML not working

### ISSUE THREAD

**Issue by LaClick** [RocketChat/Rocket.Chat#3268]
Rocket.Chat version: 0.31.0

The "How to verify email address" Email is not in HTML format. It seems that it is send as plain text.

Is it possible to have a "How to verify email address" mail configurable ? Like the invitation ans registration mails ?

Best regards, Xavier

**Comment by LaClick** [comment]
By configrable I meen is it possible to make the "How to verify email address" mail customizable ?

**Comment by LaClick** [comment]
Same problem with the "How to reset your password" mail.

**Comment by kosli** [comment]
the email is sent as plain text AND html, but the html version is exactly the same as the plain text -> so the link is not clickable as it doesn't contain a "<a href>" tag.....

**Comment by isabellarussell** [comment]
Hi, this has been tested. HTML emails are working, using 0.62.
