### ISSUE TITLE
User administration page

### ISSUE THREAD

**Issue by warcode** [RocketChat/Rocket.Chat#327]
A page similar to the "Settings" pages, visible only to administrators.

- [x] List all users
- [x] Disable/Ban/Delete users
- [x] Edit users
- [x] Promote users to administrators
- [ ] Invite users / Generate invitation links
- [x] Manually approve users after registration

Many of these are already issues as individual items.

**Comment by marceloschmidt** [comment]
Still lacking invitation as per #194. This is closed now.
