### ISSUE TITLE
Unauthenticated SMTP not working in RocketChat

### ISSUE THREAD

**Issue by vidhya03** [RocketChat/Rocket.Chat#3271]
My SMTP will work with unauthenticated, I am setting the value without username and password

![image](https://cloud.githubusercontent.com/assets/534679/15321110/0edb08c6-1c52-11e6-8f79-cdec842eb388.png)

While testing sendemail , the application trying to authenticate and failed
![image](https://cloud.githubusercontent.com/assets/534679/15321124/2b55bde8-1c52-11e6-9389-3f591dbddca6.png)

Due to this new registration also showing error.

> I20160517-08:27:19.045(0) [methods] registerUser -> userId: null , arguments: { '0': { name: 'dharan', emailOrUsername: '', email: 'vidhya@labkit.in', pass: 'vidhya', 'confirm-pass': '***_' } } 
> I20160517-08:27:19.206(0) Exception while invoking method 'registerUser' AuthError: Invalid login - 503 5.5.1 Error: authentication not enabled at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15) at smtpSend (packages/email/email.js:86:1) at Object.Email.send (packages/email/email.js:185:1) at AccountsServer.Accounts.sendVerificationEmail (password_server.js:781:9) at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:18:13) at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26) at maybeAuditArgumentChecks (livedata_server.js:1698:12) at livedata_server.js:708:19 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at livedata_server.js:706:40 - - - - - at SMTPClient._actionAUTHComplete (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:826:23) at SMTPClient._onData (/app/bundle/programs/server/npm/email/node_modules/simplesmtp/lib/client.js:329:29) at CleartextStream.emit (events.js:95:17) at CleartextStream.<anonymous> (_stream_readable.js:765:14) at CleartextStream.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:427:10) at _stream_readable.js:420:7 at process._tickDomainCallback (node.js:502:13) 
> I20160517-08:29:12.849(0) [methods] registerUser -> userId: null , arguments: { '0': { name: 'dharan', emailOrUsername: '', email: 'vidhya@labkit.in', pass: 'vidhya', 'confirm-pass': '**_*' } }

**Comment by frdmn** [comment]
I already did some troubleshooting together with @Vidhyadharantechdays, but apparently right now RocketChat is not able for sending mails without any authentication - even though you keep the `Username` and `Password` empty.

/cc @RocketChat/core

**Comment by Nodraak** [comment]
I can send mails without username and password. The problem must be on your side.
Do you have access to the log of the mail server ?

**Comment by Vidhyadharantechdays** [comment]
No i don't have access to mail server logs. But i have tested the mail
server with another application.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
