### ISSUE TITLE
Alternative endpoint for create users token

### ISSUE THREAD

**Issue by knrl** [RocketChat/Rocket.Chat#32722]
Hello,

I want to generate and retrieve tokens of users as an admin, I investigated recent endpoints but I didn’t find a way to that. There was create users token endpoint but it is now deprecated. I wonder is there any alternative way to create token for users as an admin.

We want to use rocket.chat as a messaging backend for the application we are developing. Client applications will only connect to the application, the application itself will act as a middleware and can send messages on behalf of the relevant user when necessary.

Server Setup Information
Version of Rocket.Chat Server: 6.9.2
Operating System: Windows
Deployment Method: docker
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version: 14.21.3
MongoDB Version: 6.0.13
Proxy: traefik
Firewalls involved: No

**Comment by reetp** [comment]
I believe this forum post refers.

https://forums.rocket.chat/t/alternative-endpoint-for-create-users-token/20227

Please note this is not a bug. Rocket.Chat is not broken. It just doesn't function as you want.

At best it is a feature request for a feature that has been deprecated and will be removed in v8.0 so this is wonfix.

Please have a search for users.createToken here and in the forums for more information.

I will endeavour to get an official response as to why it was removed and follow up in the forums, but it is not going to be reinstated.

**Comment by reetp** [comment]
Here's why.

https://github.com/RocketChat/Rocket.Chat/pull/32216

**Comment by knrl** [comment]
I think this PR's itself main issue here, there would be better way to solve the mentioned issue. The solution shouldn't be remove the endpoint. Now, there is no way to access via a middleware like happen in our case. We use a middleware that talks for all clients.
