### ISSUE TITLE
Reaction/Emoji tab going out of screen

### ISSUE THREAD

**Issue by AryanSwaroop** [RocketChat/Rocket.Chat#32726]
### Description:

While trying to react on a message in channel. On clicking the reaction button , the reaction window opens but partially its out of the screen.

### Steps to reproduce:

1. Go to channels 
2. Send a message
3. Click on reaction or emoji button on right of message

### Expected behavior:

Window remaining in the viewable area.

### Actual behavior:

Gone out of viewable area on opening.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0-rc.4
- Operating System: Ubuntu 20.04.6 LTS
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: 14
- MongoDB Version: 7.0

### Client Setup Information

- Desktop App or Browser Version: Mozilla Firefox 111.0
- Operating System: Ubuntu 20.04.6 LTS

![Screenshot 2024-07-05 144811](https://github.com/RocketChat/Rocket.Chat/assets/113257605/c0169093-2c6e-45b9-aa01-696afedbbd9b)

**Comment by reetp** [comment]
I believe there are some internally known issues on this.

if you are testing then make sure you really are on latest code - I think rc5 is already out.

**Comment by AryanSwaroop** [comment]
Can i work on this issue ?
