### ISSUE TITLE
Notifications to users despite not being in private group

### ISSUE THREAD

**Issue by matthias-brun** [RocketChat/Rocket.Chat#3273]
Issue #2165 was opened concerning this subject and the bug fixed in #2954.
Under certain circumstances the issue persists even after the fix. I tested this issue on master.

To reproduce use following steps:

1. Take three users:
  * UserA (Admin)
  * UserB (Not Admin)
  * UserC (Not Admin)
2. UserB opens a private group, which only he is a member of.
3. UserB sends the message "@UserA @UserC this is a test"
4. UserA receives a desktop notification informing him of the message sent by UserB in the private group. UserC does not receive a notification.

In more general terms, if someone sends a message mentioning several users, one of which is an admin, then exactly one of the other users will receive a notification. (It's not necessarily the admin receiving the notification)
Note: This doesn't work if the admin being mentioned is the person sending the message.

**Comment by maheshkalal** [comment]
Hello Team
I have upgraded my Rocket Chat server version from 0.32.0 to 0.33.0 but still not getting notifications in windows desktop application..

**Comment by maheshkalal** [comment]
Hello Rocket chat team, 
No notification in private group at windows desktop app, will be address in upcoming release? 
 kindly reply on this bug

**Comment by matthias-brun** [comment]
@maheshkalal This issue is not related to your problem and it was closed, which means that it's unlikely anyone's going to reply to you here. Open a new issue and describe your problem there.
