### ISSUE TITLE
Only mentions should re-add a private group to your channel list

### ISSUE THREAD

**Issue by zzt4** [RocketChat/Rocket.Chat#3274]
Your Rocket.Chat version: 0.30.0

If you hide a private group, any message posted will re-add the private group to your channel list. I think better behavior would be to only re-add the private group to your list if you are mentioned or `@all` is mentioned.

**Comment by tasmar** [comment]
This also applies to public channels.
👍

**Comment by marceloschmidt** [comment]
I agree. It's possible to unhide it if you want to as well, if you go to channels list, so this makes sense.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
