### ISSUE TITLE
Version 6.10.0 is behaving strangely.

### ISSUE THREAD

**Issue by ymch** [RocketChat/Rocket.Chat#32759]
### Description:

I have updated from version 6.9.3 to 6.10.0, and although the server process starts, it behaves strangely.
For example, when I access Workspace->Settings (/admin/settings), there is no scroll bar and I cannot see all items.
I am not comfortable with this, so I reverted back to version 6.9.3.

### Steps to reproduce:

1. Update to version 6.10.0
2. Go to Workspace->Settings (/admin/settings).

### Expected behavior:

All items must (should) be displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: v6.10.0
- License Type: Community
- Number of Users: 21
- Operating System: Rocky Linux 9.4
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.27

### Client Setup Information

- Desktop App or Browser Version: DesktopApp4.0.0 | Firefox128.0 (64bit)
- Operating System: Windows10 v22H2 (Build 19045.4651)

### Relevant logs:
```
systemd[1]: Started The Rocket.Chat server.
    :
(Omitted)
    :
rocketchat[29925]: +-------------------------------------------------+
rocketchat[29925]: |                  SERVER RUNNING                 |
rocketchat[29925]: +-------------------------------------------------+
rocketchat[29925]: |                                                 |
rocketchat[29925]: |  Rocket.Chat Version: 6.10.0                    |
rocketchat[29925]: |       NodeJS Version: 14.21.3 - x64             |
rocketchat[29925]: |      MongoDB Version: 5.0.27                    |
rocketchat[29925]: |       MongoDB Engine: wiredTiger                |
rocketchat[29925]: |             Platform: linux                     |
rocketchat[29925]: |         Process Port: 3000                      |
rocketchat[29925]: |             Site URL: https://chat.*******.jp/  |
rocketchat[29925]: |     ReplicaSet OpLog: Enabled                   |
rocketchat[29925]: |          Commit Hash: 623a265851                |
rocketchat[29925]: |        Commit Branch: HEAD                      |
rocketchat[29925]: |                                                 |
rocketchat[29925]: +-------------------------------------------------+
rocketchat[29925]: Subprocess stderr #033[0m#033[32mDownload#033[0m https://deno.land/std@0.216.0/io/write_all.ts
rocketchat[29925]: Subprocess stderr #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/jsonrpc-lite/-/jsonrpc-lite-2.2.0.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/@msgpack/msgpack/-/msgpack-3.0.0-beta2.tgz
rocketchat[29925]: Subprocess stderr #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/acorn/-/acorn-8.10.0.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/astring/-/astring-1.8.6.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/@rocket.chat/ui-kit/-/ui-kit-0.31.25.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/acorn-walk/-/acorn-walk-8.2.0.tgz
rocketchat[29925]: #033[0m#033[32mDownload#033[0m https://registry.npmjs.org/@rocket.chat/icons/-/icons-0.32.0.tgz
```
---

Added on 2024/07/13

Normally, the log immediately after startup should only output up to the release information, but in v6.10.0, I am noticing a disturbing "Subprocess stderr" error following it.
(I hope this error does not affect the process and is just my unfounded fear.)

Incidentally, this error is output in the following source:
`bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/runtime/deno/AppsEngineDenoRuntime.js`
(Line:457)
```
    parseError(chunk) {
        return __awaiter(this, void 0, void 0, function* () {
            console.error('Subprocess stderr', chunk.toString());
        });
    }
```

**Comment by lovekyleman** [comment]
Yes. You're right

**Comment by SebiBasti** [comment]
I have the same. You can still search for the section you want to open. I think they just messed up the `overflow` value somewhere.

**Comment by NikFort** [comment]
Same here.

**Comment by reetp** [comment]
Thanks for reporting this.

I will ask someone to take a look

**Comment by scuciatto** [comment]
Looks like a CSS issue (but we are confirming it). After investigating it seems that  height: 100% !important; is being added to the scroll component

**Comment by d-gubert** [comment]
A word about the `Subprocess stderr` messages in the logs: those that you've seen specifically do not report on an issue; we've switched the runtime of Apps-Engine to use Deno, and those messages are logged by default by Deno when installing dependencies.

This only happens once and Deno caches the dependencies. It should be cached during the installation process, by since your rocket.chat server runs as a different user from the one you used to update it, it cached the dependencies in a different place that the server doesn't have access to - and that's why it needs to download them the first time it runs after the update.

**Comment by ymch** [comment]
I updated to version 6.10.1 and all problems have been resolved.
Thank you very much.

> This only happens once and Deno caches the dependencies. It should be cached during the installation process, by since your rocket.chat server runs as a different user from the one you used to update it, it cached the dependencies in a different place that the server doesn't have access to - and that's why it needs to download them the first time it runs after the update.

As you said, there was no `Subprocess stderr` output on the second startup.

I am closing this issue thread as resolved.
