### ISSUE TITLE
Multiple services make desktop client disconnect when not focused.

### ISSUE THREAD

**Issue by florisvangeel** [RocketChat/Rocket.Chat#32753]
### Description:

Adding multiple services to a client restricts update of connection and notifications to the active (highlighted service)

### Steps to reproduce:

1. Install Desktop client from app store or build latest 4.0.0
2. Add multiple services besides open. and demo.rocket.chat
3. focus and highlight one service
4. Wait 15-60 minutes not touching or minimising the app.
5. Click to one of the not focused services.

### Expected behavior:

Not focused services should maintain connection up and refresh notification etcetera.

### Actual behavior:
Non focused services stuck in toaster trying to connect.
No communication until hard reload Shift+CMD+R or SHIFT+CTRL+R

https://github.com/RocketChat/Rocket.Chat/assets/1267925/955a7485-7f3a-4db0-9516-04cca2668eba

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.6
- License Type: Community
- Number of Users: N
- Operating System: Ubunti 22.04
- Deployment Method: Ansible
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.x

### Client Setup Information

- Desktop App or Browser Version: 4.0.0 (master) or any version below.
- Operating System: OSX ( problem happens in any OS )

### Additional context
Tested with transparent proxy in Caddy and Nginx as well as running RC directly behind NAT routing on dedicated IP number. 
All have the same issue.

Hypothesis is it must be the client not polling / connecting properly?

### Relevant logs:
No Errors, just the usual warnings.

**Comment by reetp** [comment]
If it is a client issue it should probably be here:

https://github.com/RocketChat/Rocket.Chat.Electron

I'll try and test myself - I never normally use the client!

**Comment by florisvangeel** [comment]
sorry, cross posted here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2914

**Comment by reetp** [comment]
Follow up there.

I'll close this.

W can re-open if a bug is found in rocket.chat.

**Comment by florisvangeel** [comment]
yes its a duplicate of [this](https://github.com/RocketChat/Rocket.Chat/issues/17748#issuecomment-2049835952) that seems to be still open.

**Comment by florisvangeel** [comment]
Tested the patch, didn't help that went into the 3 balls and never loaded the app.
Also managed to invoke same behaviour in browser so it surely not App related.
