### ISSUE TITLE
Rocketchat IOS APP can't upload files of MP3, JPG

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#32762]
Rocketchat IOS APP can't upload files of MP3, JPG and lots more, but it's ok with browsers

**Comment by reetp** [comment]
Please open in the correct repo:

https://github.com/RocketChat/Rocket.Chat.ReactNative

But before you do please make sure you test on the latest version of Rocket.Chat

You can use open.rocket.chat to do that.

Also make sure you fill out a bug template correctly or we can't help you. Server information and app information is extremely important to help diagnose your issue.

Thanks.
