### ISSUE TITLE
Internal Server Error: w/Login Using OAUTH with Google, FB, etc.

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#3276]
Your Rocket.Chat version: (make sure you are running the latest: 0.31)

When I try to login I get the following error:

`Exception while invoking method 'login' MongoError: E11000 duplicate key error index: heroku_nx4r0674.users.$services.facebook.id_1 dup key: { : "565385089" }     at Object.Future.wait (/app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)     at _Class.RocketChat.models._Base._Class.update (packages/rocketchat_lib/server/models/_Base.coffee:31:24)     at _Class.RocketChat.models.Users._Class.setServiceId (packages/rocketchat_lib/server/models/Users.coffee:183:11)     at AccountsServer.Accounts.updateOrCreateUserFromExternalService (server/configuration/accounts_meld.coffee:30:28)     - - - - -     at Object.toError (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     at Server.Base._callHandler (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     at /app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     at [object Object].MongoReply.parseBody (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     at [object Object].<anonymous> (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     at [object Object].emit (events.js:95:17)     at [object Object].<anonymous> (/app/.meteor/heroku_build/app/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13) `

**Comment by Syirrus** [comment]
My database migration is 53

**Comment by Syirrus** [comment]
UPDATE: I reboot my instance and disabled OAUTH for each service (FB, GOOGLE, etc.) and it seems to be working now. Just wanted to update anyone that looked at this thread

**Comment by marceloschmidt** [comment]
If this issue happens again, please reopen. Thank you.
