### ISSUE TITLE
dose‘t work

### ISSUE THREAD

**Issue by chunjiu** [RocketChat/Rocket.Chat#32770]
![1720753983520](https://github.com/user-attachments/assets/a571eaa7-817f-4556-9885-61206bf6d3fc)

**Comment by SySagar** [comment]
Does it somehow makes the build failed ? If that's the case then I thing its mostly because it requires more resources than allocated to it. Maybe try spacing up or use `yarn dsv`

**Comment by SinghaAnirban005** [comment]
<code>yarn dsv</code> worked in my case . Do try out !

**Comment by reetp** [comment]
When opening an issue please fill out a full bug template and give the issue a related name and not just 'doesn't work'.

We can't help you without it.

It appears this is most likely a deployment issue.

Please read the documents thoroughly and ask for support in https://open.rocket.chat

https://docs.rocket.chat/

https://developer.rocket.chat/v1/docs/server-environment-setup
