### ISSUE TITLE
WebHooks should allow asynchronous processing

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#3277]
Hi,

it'd be great if the WebHook request handlers could be asynchronous by accepting a Promise as a return value from the `process_incoming_request` handler beside the sync. message object. This Promise would then resolve with a valid Rocket.Chat message. This way you could keep the 100% compatibility with the Slack API as mentioned in #1501 but also support async. processing.

I.e.

> The `process_incoming_request` method should return an object with a property content containing a valid Rocket.Chat message, **a Promise that resolves with a valid Rocket.Chat message as first argument** or an object with a property error that will be returned as the response of the request in JSON format and status code 400.

The reason why I request this feature is because upon an incoming request I need to query some REST API to get more information before I can return the Rocket.Chat message.

Your Rocket.Chat version: 0.28.0

**Comment by jsaddiction** [comment]
I also would love this functionality..
use case:
I run applications like CouchPotato server.  These applications either already support webhook notifications or are in development for such implementation.  The notifications don't deliver much however.  In the case of CouchPotato, it delivers an imdb id and a message.  

If i could make a call to an online database such as "themoviedb.org" I could collect much more information pertaining to the imdb id.

if there is any other way to accomplish this task i would be greatly appreciative..  Thanks again and great work!!

Rocket.Chat version: 0.42.0

**Comment by rodrigok** [comment]
We already support HTTP calls in a sync way.

But we have plans to accept a full async (using promises) script.
