### ISSUE TITLE
Ошибка транслирования текста при вставке сообщения

### ISSUE THREAD

**Issue by Akanov222** [RocketChat/Rocket.Chat#32772]
При вставке в сообщение текста, содержащего путь с множеством символов, программа пропускает несколько символов.

Скрин ошибки:
https://drive.google.com/drive/folders/1UbJRjy-XyEAZocK8Z_ICmSxn-W7Er8Q1?usp=sharing

**Comment by reetp** [comment]
Please fill out a proper bug template with your server details. We cannot help without it.

You will also need to speak English.

Possibly related:

https://github.com/RocketChat/Rocket.Chat/issues/32282

Thanks.
