### ISSUE TITLE
Hindi Language Translation Backlog in UI

### ISSUE THREAD

**Issue by smritidoneria** [RocketChat/Rocket.Chat#32786]
### Description:

When switching the language to Hindi, some words and phrases remain in the default language. The application should fully support Hindi translation.

### Steps to reproduce:
Go the preferences section while clicking upon the profile
choose Hindi from the dropdown of language
### Expected behavior:

All UI elements should be translated into Hindi.
### Actual behavior:
Certain words and phrases remain in English.

https://github.com/user-attachments/assets/7bc4b92d-3c8f-43ed-82fe-6780c454f3c3

### Server Setup Information:

- Version of Rocket.Chat Server:  6.10.0
- License Type:Community
- Number of Users: 3
- Operating System: MacOs
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.4
- MongoDB Version:7.0.5

### Client Setup Information

- Desktop App or Browser Version:Browser
- Operating System:MacOs

**Comment by reetp** [comment]
Please see this:

https://github.com/RocketChat/Rocket.Chat/issues/30218#issuecomment-1699103928

There are lots of parts that have no translation. Please feel free to make a PR.

**Comment by smritidoneria** [comment]
okay, thanks. I will work upon this

**Comment by sameer-dudeja** [comment]
There is a pending PR on this issue #30927 
Which has a lot of work in it but still not merged.
@dougfabris  Do you know what's the status for this PR, I also was interested in similar work but not sure now.

**Comment by its-kunal** [comment]
@reetp, please review this PR #30927
