### ISSUE TITLE
Notification schedule

### ISSUE THREAD

**Issue by NicKerrr** [RocketChat/Rocket.Chat#32789]
Hello! I want only receive notifications in the hours i choose. Pls, create settings for this.

**Comment by reetp** [comment]
Hi.

This not a bug in Rocket.Chat - it just doesn't do what you would like it to do.

So it is a feature request.

Please re-open here and fill in an Issue template properly as well.

https://github.com/RocketChat/feature-requests

Rocket.Chat is open source, so your pull requests with some code to fix this will be welcome.

Thanks.
