### ISSUE TITLE
Search functionality of members 

### ISSUE THREAD

**Issue by smritidoneria** [RocketChat/Rocket.Chat#32784]
### Description:

Search functionality is not properly implemented while searching the member of the channel

### Steps to reproduce:

1. Go to any channel
2. Click on  members search

### Expected behavior:

Search should happen correctly

### Actual behavior:

https://github.com/user-attachments/assets/7d6ca3b0-a798-4fb2-9a54-fe02f507a4a2

### Server Setup Information:

- Version of Rocket.Chat Server: 
- License Type: Community
- Number of Users: 3
- Operating System: MacOs
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.21.3
- MongoDB Version:5.0.27

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: MacOs

**Comment by reetp** [comment]
Hi.

Please go back and complete the Server Setup information.

We can't help without it.

You can also test on the latest version of Rocket.Chat at http://open.rocket.chat

**Comment by smritidoneria** [comment]
hey, I have added the server setup information and I have also checked out this,http://open.rocket.chat/, the search functionality has issues

**Comment by reetp** [comment]
Testing on open.rocket.chat using a browser:

https://github.com/user-attachments/assets/7fa8e47a-cf13-417e-a10e-dd8b79f35fe6

Also tested using Rocket.Chat 3.9.16 on open and it also worked.


> Please go back and complete the Server Setup information.

We need to see this information.

> Version of Rocket.Chat Server:
> License Type: Community

**Comment by smritidoneria** [comment]
<img width="474" alt="Screenshot 2024-07-14 at 7 34 51 PM" src="https://github.com/user-attachments/assets/022b02d7-584b-487e-af19-7cf0b65321a5">
if I search for 1 here, then why is Elivia Kerstner showing in search results

**Comment by reetp** [comment]
You have still not told us about your own install.

> if I search for 1 here, then why is Elivia Kerstner showing in search results

Because there is a `1` in her Bio.

There is also a `1` in mine as well if you check - you should see reetp there if you check 'all' and not 'online'.

I don't see a bug here currently.
