### ISSUE TITLE
Shoing Undefined on a Toast Message

### ISSUE THREAD

**Issue by JASIM0021** [RocketChat/Rocket.Chat#32783]
#### Description:

Users are encountering an issue where an "Undefined" message is displayed in a toast notification after attempting to change their password.

#### Steps to Reproduce:

1. Navigate to [https://mobile.rocket.chat](https://mobile.rocket.chat)
2. Click on the profile icon.
3. Select "Profile" and then click on "Security."
4. Create and confirm a new password.
5. Save the new password.

#### Expected Behavior:

A user-friendly and clear message should be displayed to the user indicating the success or failure of the password change process.

#### Actual Behavior:

An "Undefined" message is displayed in the toast notification, which is not informative for the user.

#### Screenshot:

![Undefined Toast Message](https://github.com/user-attachments/assets/4ec38bbc-c424-4f8a-a49c-ebb6ab06ec31)

**Comment by reetp** [comment]
HI and thanks for reporting this.

Is this your server or is it one of Rocket.Chat servers?

**Comment by JASIM0021** [comment]
@reetp  this issue is occurring in the RocketChat server I don't have any server

**Comment by reetp** [comment]
Don't need to @ people thanks.

Ok. Don't recall having seen "mobile.rocket.chat" before.

Only open.rocket.chat

I'll check.
