### ISSUE TITLE
use docker Workspace is not registered

### ISSUE THREAD

**Issue by MR-ZiWeiter** [RocketChat/Rocket.Chat#32796]
rocketchat/rocket.chat.preview:sha-d0bedf7

After using docker deployment, I cannot set it up through the administrator and keep wandering back and forth in registering services
![image](https://github.com/user-attachments/assets/bc870c5a-f400-45d6-a93c-f97465188639)

**Comment by MR-ZiWeiter** [comment]
> First, please fill out a bug template properly.
> 
> Second you need to register with a genuine address - I don't believe gmail etc are permitted.
> 
> However, that should be displayed and I am not sure why it isn't.
> 
> I'll ask the team about this.

This problem has been changed to set the completion property of the table and skipped temporarily. But the new problem is that the locally deployed service registration interface takes 20 seconds to register successfully each time. I checked all the modifiable configurations, but still failed.

**Comment by reetp** [comment]
> First, please fill out a bug template properly.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
