### ISSUE TITLE
Rocket Chat Still Using Node v14 which is EOL.

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#32790]
### Description:

Rocket Chat is still using Node version 14.21.3.  Version 14.x has been EOL since April of 2023.  There was a [forum post ](https://forums.rocket.chat/t/nodejs-14-end-of-life/17167) back in June of 2023 regarding what Rocket Chat was doing to move to a newer version of Node.  That post mentioned that Meteor would be supporting a forked version of Node version 14.  However, according to that page, and the links on that page, the special forked version of Node version 14 was only going to be supported until April 2024.  This would seem to imply that all Rocket Chat versions are again running Node without security support.

### Steps to reproduce:

1. Go the Rocket Chat releases [page](https://github.com/RocketChat/Rocket.Chat/releases)
2. See supported Node version.

### Expected behavior:

I would expect that Rocket Chat would now support newer versions of Node.

### Actual behavior:

![image](https://github.com/user-attachments/assets/f9caeed0-9c89-4f97-b4b4-0a864ab1a63e)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.10.0
- License Type: Enterprise
- Number of Users: 150
- Operating System: Linux
- Deployment Method: builds from RC build server
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.15

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Linux

### Additional context

It might also be helpful/beneficial for the devs to provide some more current information on this.

**Comment by reetp** [comment]
This is a duplicate of this discussion.

https://github.com/orgs/RocketChat/discussions/29658

Please follow up there - I will ask for an official update on this on that discussion.

Thanks.

**Comment by mddvul22** [comment]
@reetp respectfully, this is not a duplicate of that discussion.  A discussion is NOT a bug report.  This is indeed a security bug and this bug report should be open until it is resolved.  A discussion is not the equivalent.

**Comment by reetp** [comment]
This is a duplicate issue.

If you want to open a security bug then please follow the docs as normal.

You can mail security @ rocket.chat

But as it is a known - duplicate - issue already in hand internally as per the discussion and forum posts there is no point.

Rocket will be making an updated comment on the discussion shortly.

Please follow up there.

**Comment by casalsgh** [comment]
Folks, we are working to move to a newer version with release 7.0. We understand the security concerns of using a Node version that is no longer supported, but we have internal processes in place to test the security of our product, assess vulnerabilities and fix them. At this time, we are not aware of any vulnerabilities in Node 14.21.3 that pose a significant risk to Rocket.Chat, community or customers.

**Comment by SebiBasti** [comment]
I'm not the biggest fan of needing to trust in software development. EOL means when a new attack vector for node 14 is found that it will not be fixed or even discussed because it's EOL.

It would just be nice to get a rough timeline until when we have to have an eye on security mailing lists and such.

**Comment by casalsgh** [comment]
Rought timeline for 7.0: End of September 2024. 
It's in progress work, dates might change for different reasons (business or tech, and focused mainly on quality), but that is what we are internally working towards at the moment.

**Comment by reetp** [comment]
Please follow up in the existing discussion.

(Pretty sure Rocket hoped and expected this would be done some while ago but..... dependencies...... :-(  )

**Comment by pyrocto** [comment]
> Rough timeline for 7.0: End of September 2024.

Now that it's September 2024, you probably have a better idea of when 7.0 is coming out.  What's the current estimate?

**Comment by reetp** [comment]
> Please follow up in the existing discussion.

When it's ready......

Just have to be patient.

Pretty sure there'll be lots of info pre-launch.
