### ISSUE TITLE
request: /clear

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3279]
Your Rocket.Chat version: 0.31

Hey folks,

For some situations, like a #monitoring channel you want to /clear the screen. It's perfectly okay if this would be client-side only. Just 'wipe' and get a fresh, empty channel (on your end).

_Thanks & Cheers!_
-Chris.

**Comment by marceloschmidt** [comment]
You can already type command + ctrl + k or shift + control + k but you will get the latest 50 messages because of auto-scroll. We'll work on fixing that besides adding the /clear command.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
