### ISSUE TITLE
Threads are not getting pruned

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#32794]
### Description:

Pruning of threads is not working at least on channels that have channel based separate shorter retention time.

### Steps to reproduce:

1. Set global pruning in admin settings `admin -> settings -> retention policy` for `1 year` and apply it for everything. Disable option `Do not prune threads`. (Meaning *do* prune threads.)
2. Create a test channel and set retention time on that channel separately into `1 day`.
3. Create a thread and couple of messages under that thread on the channel. Also type some individual messages on the channel for comparison later.
4. Two days later check the messages on the channel.

### Expected behavior:

No messages can be found on the channel.

### Actual behavior:

Individual messages have been pruned correctly but the thread and all messages in it remain on the channel at least for one year.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.9.3
- License Type: Enterprise
- Number of Users: -
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0

### Additional information:

The thread pruning functionality works in RC 6.10.0 for newly created channels.

The bug would be in the upgrade process that does not add `ignoreThreads: false` into channel's properties for the existing channels that have already had the channel based pruning enabled in RC 6.9.x. (Which did not have such option at all.)

**Comment by Gummikavalier** [comment]
@dougfabris FYI. Observed on two separate older channels I used for testing. These channels were not completely new though, and I'm yet to do the third test with a completely new channel.

**Comment by Gummikavalier** [comment]
Confirmed that the thread pruning functionality works in RC 6.10.0 for newly created channels.

The bug would be in the upgrade process that does not add `ignoreThreads: false` into channel's properties for the existing channels that have already had the channel based pruning enabled in RC 6.9.x.

**Comment by Gummikavalier** [comment]
Bump

**Comment by dougfabris** [comment]
Hey @Gummikavalier sorry for the delay, I was really busy here last days! Indeed in 6.10.0 we introduced the ability to `Do not prune Threads` in retention override but since channels hasn't the prop previously it won't work for old channels as you correctly said. I'm almost sure we'll have to add a migration to add this property to the old channels to fix it. 

We usually wait for major releases to create migrations, but since it's just a addition I'm going to take a look with the team if it's possible to do that right away. 

I really appreciate your help finding this one 🚀

**Comment by Gummikavalier** [comment]
@dougfabris Sorry, I got that bot stale message so I just bumped to keep this open. I keep one old channel and thread on our production system reserved for checking, and then confirm this fixed when it gets pruned.

But thanks for the response, appreciated! This is not actually a biggie as the feature was so recent it was not widely used in the past, and workaround is easy to do if required. :heart:

**Comment by Gummikavalier** [comment]
Aand I confirm that this issue has been fixed on behalf of old channels too in RC 7.0.0. Thanks! :hugs:
