### ISSUE TITLE
Channel/Group topics

### ISSUE THREAD

**Issue by warcode** [RocketChat/Rocket.Chat#328]
Editable topic/title shown at the top of the channel/group behind the name.

* Displayed in chat when a user enters for the first time.
* Used as MOTD/description/etc

**Comment by graywolf336** [comment]
:+1: yes, this is very helpful to have.

**Comment by AdrianoCahete** [comment]
Settable with command /topic is good too.

**Comment by gwillen** [comment]
Pretty excited about this feature! We like to use this (in Slack/IRC) for stuff like FAQs and important links.

**Comment by plemarquand** [comment]
Isn't this sort of done? If you open up Room Info there is a field for setting the topic. You can only set the topic if you have the 'edit-room' permission.

There isn't a `/topic` slash command though.

**Comment by gwillen** [comment]
@plemarquand This is sort of hard for me to test, since there's no way for me to know (that I can see) what permissions I have on a channel, and I don't know if it's possible to set them.

But I assume I have 'edit-room' on a private channel created by me... and I think I may have run into another bug? It seems like, on rooms I own, there's a 'gear' icon in the top right corner, which looks like it could be the 'Room Info' you're talking about. But when I click on it, search opens instead. And in fact, it seems like on rooms I own, clicking any of the tabs in the top right opens the tab _below_ the one I clicked on. Very odd.

**Comment by plemarquand** [comment]
@gwillen The "Room Info" button is the first button on the flex-tab-bar on right right. Its an "information" icon (lowercase i in a circle). Without permissions I see a 'topic' field, but its just empty and I can't change it.

**Comment by gwillen** [comment]
Hm, I think we must be running an old version? We have no icon like that. Thanks.

**Comment by geekgonecrazy** [comment]
@RocketChat/core I believe this functionality was merged down in last weeks version right?

@gwillen what version are you running?

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/12275859/8d3e99be-b959-11e5-9f0e-d8d37d9b8693.png)

**Comment by Frankstar** [comment]
@engelgabriel Is it possible to use hyperlinks and inline picture in topics?
Like `![Build Status](https://travis-ci.org/RocketChat/Rocket.Chat.svg?branch=develop)`

![Build Status](https://travis-ci.org/RocketChat/Rocket.Chat.svg?branch=develop)

or Hyperlinks like `[Rocket.Wiki](https://rocket.chat/docs/)` [Rocket.Wiki](https://rocket.chat/docs/)

**Comment by geekgonecrazy** [comment]
Hyperlinks are supported.  You'll see we use them on our demo server.  Images however I don't think are.  I would probably argue it would just add clutter.  What do you do if some puts a huge graphic there?

**Comment by RichardFoxworthy** [comment]
Images & icons in topic can deliver very valuable context and info in compact way. Definitely a good thing to support

**Comment by Frankstar** [comment]
@geekgonecrazy well sure - but you can mess up so many things.
if you put in a big picture and mess up the header -> remove it.

Still its a very usefull Feature for us any many others i guess.
