### ISSUE TITLE
request: embetterment of online/offline status

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3282]
Your Rocket.Chat version: 0.31

Hey folks,

We need a better online status display, like so:
- Green: online and available,
  (- Yellow: online and away,)
  (- Red: online but in DND,)
- Gr(e|a)y: Offline and NO push enabled/ possible
- blue(?): offline, but push possible

I never really used anything besides online/offline (read: away, dnd and whatnot) but currently I cant determine if the user is offline / offline with push / away...

Would it be possible to differentiate with colo(u)rs about mobile presence?

Thanks & Cheers!
-Chris.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
