### ISSUE TITLE
There is no route for the path: / when trying to deploy rocketchat 6.10.0 on an air-gapped environment

### ISSUE THREAD

**Issue by eldadweiss** [RocketChat/Rocket.Chat#32826]
### Description:

When trying to deploy rocket-chat version 6.10.0 on an air-gapped environment the website is not loading.
The loading animation is running infinitely. 
The console shows this error : There is no route for the path: /

This case does not happen on version 6.8.3 or 6.9.3 which works as expected.

### Steps to reproduce:

1. Perform a fresh installation (using the docker installation)
2. Try to navigate into http://<IP>:3000
3. See the error

### Expected behavior:

The first usage wizard should be displayed

### Actual behavior:

![rocket-chat](https://github.com/user-attachments/assets/d3d28efe-641f-4e66-bcee-489a53c9f115)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0
- Operating System: Ubuntu Server 22.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: default
- NodeJS Version: default
- MongoDB Version: default

### Client Setup Information

- Desktop App or Browser Version: Chrome 126.0.6478.126
- Operating System: Windows/Linux

**Comment by reetp** [comment]
Thanks for reporting.

I will ask the team to take a look.

**Comment by rodrigok** [comment]
The issue is related to end to end encryption that requires service workers. Unfortunately, service workers do not work on unsecured connections (not https, except for localhost domain). We have another issue related to firefox incognito window having problems with service worker, I think the solution will be the same. Will route this internally

**Comment by milinddeore** [comment]
@rodrigok Thanks! 
Incase you only have SSH access, run `curl http://localhost:3000` in the terminal. The Server is indeed UP.
