### ISSUE TITLE
Scroll function in settings are broken

### ISSUE THREAD

**Issue by konzeptplus-gmbh** [RocketChat/Rocket.Chat#32827]
### Description:

Scrolling is broken in the admin/setting. 
In the latest version 6.10.0 Enterprise of RocketChat, the settings are not very usable anymore because the scroll function is broken.

### Steps to reproduce:

1. Login as admin and go to : yourrocektCaht/admin/settings 
2. Scroll down

### Expected behavior:

You are not able scroll down the grid of all the apps. So you are only able to search or go via Browser and reduce the % of the Browserscale. 

### Actual behavior:

Just scrolling down. 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0
- License Type: Enterprise
- Number of Users: 100
- Operating System: Debian 11
- Deployment Method: Docker
- Number of Running Instances: 2
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.28 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 4.01 Windows
- Operating System: Windows / Linux

**Comment by reetp** [comment]
Thanks for reporting.

I'll ask the team to take a look - but note if you are on Enterprise you can contact support directly.

**Comment by ymohit1603** [comment]
hey casalsgh i really wanna work on this issue can you issign it to me?

**Comment by ymohit1603** [comment]
@casalsgh

**Comment by reetp** [comment]
> i really wanna work on this issue can you issign it to me?

Issues are not assigned

> @casalsgh 

Please don't @ people. Thanks.

> As for this issue, will be fixed on 6.11.

Read the comments properly.

Already fixed.

Thanks.

**Comment by Gummikavalier** [comment]
Confirmed working in RC 6.10.1. This can be closed.
