### ISSUE TITLE
request: @here / @$tag

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3283]
Your Rocket.Chat version: 0.31

Hey folks,

To complement @all which messages all the users in the room, regardless of online status, a @here mention would ping all currently non-offline users in a channel. Think of it as an "Hey, all awake folks!" without waking sleeping guys (literally).

Killer feature: Allow users to set tags for themselves in their profile, like "webdesigner", "admin", "intern". This would make "Hey @admins, the server is down" possible, notifying all who have that tag.

Thanks & Cheers!
-Chris.

**Comment by KervyN** [comment]
That tagging would be awesome.

**Comment by s17t** [comment]
Would be great but please use another character over '@' symbols to not overlap with legit usernames.

**Comment by brendanheywood** [comment]
Me too: '@here' should be a reserved symbol and work the same as hipchat and slack.

**Comment by KervyN** [comment]
Well, why is it a problem to use @? Just define some useful tags like @admins @devs @shittypeople. 
When a tag already exist, people are not allowed to use it as username. When the username already exist, admins are not allowed to use them as tags. :-)

**Comment by mkretzer** [comment]
It would we very useful to be able to only message online users...

**Comment by antnat** [comment]
Where customs tags added or should add this as possible feature again?

**Comment by christianreiss** [comment]
Was never added, would welcome a re-add!

**Comment by xurizaemon** [comment]
Seems on topic to remind that notifications work on Github too: the usernames mentioned above (except @shittypeople!) are real people / orgs now getting notified about this issue. I believe we can prevent triggering notifications for randomly mentioned people using backticks: `@here` etc.

:thumbsup: for this proposal too!

**Comment by antnat** [comment]
As this ticket is closed I've raised #9973 for mentioning by tags feature.
