### ISSUE TITLE
Contribution Link is not working 

### ISSUE THREAD

**Issue by sameer-dudeja** [RocketChat/Rocket.Chat#32850]
### Steps to reproduce:

1. Clicked on ways contribute on readme.md [Ways to contribute](https://developer.rocket.chat/contribute-to-rocket.chat/ways-to-contribute)

### Expected behavior:

Should be a valid link to working page

### Actual behavior:

![image](https://github.com/user-attachments/assets/fd7f1e33-2b52-4989-826d-9f6d66249c29)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- License Type:
- Number of Users: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Chrome Latest
- Operating System: Win11

**Comment by reetp** [comment]
Thanks. I have reported this to the team to be fixed.

**Comment by casalsgh** [comment]
Fixed now, please check and let us know. thanks!
