### ISSUE TITLE
"yarn" Fails to build , Can't test locally

### ISSUE THREAD

**Issue by Raj-Mandal-20** [RocketChat/Rocket.Chat#32859]
## Description:

i have installed node and using `nvm use 14.21.3`
i have installed yarn, `npm i -g yarn`
i have installed meteor js,  `npm i -g meteor@2.16`
cloned the repo, did  `yarn` 
it fails

## Client Setup Information
Desktop App or Browser Version:  Chrome
Operating System:  Windows 11

## Relevant logs:
![image](https://github.com/user-attachments/assets/930aa7b2-fdee-4c96-af7a-6d839382aa87)
![image](https://github.com/user-attachments/assets/4e2ef8fe-64dc-442c-be7f-61ae77cf4dff)
![image](https://github.com/user-attachments/assets/604943f2-1965-4b61-aa47-80a16e4ed36b)

**Comment by Raj-Mandal-20** [comment]
#30416

**Comment by Sibam-Paul** [comment]
@Raj-Mandal-20 do yarn dsv

**Comment by Raj-Mandal-20** [comment]
@Sibam-Paul I had already tried with `yarn dsv` and `yarn dev` it showing some errors 
### when I did `yarn dsv`
![image](https://github.com/user-attachments/assets/a37573f9-7495-42b8-a0bf-81d99c05e009)
![image](https://github.com/user-attachments/assets/ff9cbea1-c55d-4e73-ad73-3173752c8317)
![image](https://github.com/user-attachments/assets/0e371ec9-2d1a-46eb-8415-fbc7d993e98f)
![image](https://github.com/user-attachments/assets/b2728522-6548-4971-8885-0c6fb9373a55)
![image](https://github.com/user-attachments/assets/d5859c0c-2d1a-4eff-8393-e7c1a30e693e)
![image](https://github.com/user-attachments/assets/6e28f787-b916-4e5f-847f-b44325d78fff)

### after  `yarn dev` 
it freezes after some time waiting for file changes

![image](https://github.com/user-attachments/assets/afba1239-13c7-48fe-8a10-e22454605090)
![image](https://github.com/user-attachments/assets/d37a72df-5d1d-4b54-ac69-6703636d7718)
![image](https://github.com/user-attachments/assets/bd12af5b-4f81-4b8f-a760-28f80d7f4067)

**Comment by KevLehman** [comment]
Have you tried just cloning the repo inside the linux filesystem? I'm assuming you're on WSL (i expect wsl2 cause i never got RC to run on wsl1). If you're on WSL1, update.

Clone the repo inside the linux filesystem. Using the mounted paths from windows is slow and can cause issues (as the files are technically on windows even when read by linux).

If after that you continue to have problems, please update the thread.

**Comment by Raj-Mandal-20** [comment]
Yes, I am using WSL2, followed what you have told but still shows this error. I have recloned the repo again but still facing the problem. `yarn dev` still stuck on the file changes but when I ran `yarn dsv` it rendered the client page but with some errors.
### here are the logs
![image](https://github.com/user-attachments/assets/5b9c41ff-861d-44f8-b753-e3b2414fe4e1)
![image](https://github.com/user-attachments/assets/14faf967-eb51-41ce-b937-f841c4048d48)
### In Client Side it is showing this
![image](https://github.com/user-attachments/assets/df234a8f-9fe2-41f6-bb2a-36879e3a00ed)

**Comment by Raj-Mandal-20** [comment]
>



Hello @KevLehman,  Yes I am using WSL2, followed what you have told but still shows this error. I have recloned the repo again but still facing the problem. `yarn dev` still stuck on the file changes but when I ran `yarn dsv` it rendered the client page but with some errors.
> 
> ### here are the logs
> ![image](https://private-user-images.githubusercontent.com/99534700/351122140-5b9c41ff-861d-44f8-b753-e3b2414fe4e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUzMjIsIm5iZiI6MTcyMTY4NTAyMiwicGF0aCI6Ii85OTUzNDcwMC8zNTExMjIxNDAtNWI5YzQxZmYtODYxZC00NGY4LWI3NTMtZTNiMjQxNGZlNGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YzY2NGJiOGUxMjY1NWNkMTEzMGY5MzUzOTUzMGZiZmUwODk0ODU4ZjJhODdmZmEyYTVjYWQwYzhjYjI2MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A58UYMVQAV7PdjEXRXcwd-Kufncu2BVSdPVmMlmhn9g) ![image](https://private-user-images.githubusercontent.com/99534700/351122178-14faf967-eb51-41ce-b937-f841c4048d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUzMjIsIm5iZiI6MTcyMTY4NTAyMiwicGF0aCI6Ii85OTUzNDcwMC8zNTExMjIxNzgtMTRmYWY5NjctZWI1MS00MWNlLWI5MzctZjg0MWM0MDQ4ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOGUwZmFkMTc5OWVlYWFlMzA1Y2ZiZmE3NjAyZWNmYmFmNTFkN2M0YjllZjQ0YjliZjJkMDY0MGZiNmMzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBo88XExbmxwMeAQ-0T5xOJyKU_v6B3XDLlZV5kgkzU)
> 
> ### In Client Side it is showing this
> ![image](https://private-user-images.githubusercontent.com/99534700/351122331-df234a8f-9fe2-41f6-bb2a-36879e3a00ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODUzMjIsIm5iZiI6MTcyMTY4NTAyMiwicGF0aCI6Ii85OTUzNDcwMC8zNTExMjIzMzEtZGYyMzRhOGYtOWZlMi00MWY2LWJiMmEtMzY4NzllM2EwMGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIxNTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YTU1NTk1NTM5OTM0ZDI3MjQ2ZmNmZGViNDM5NzBhZjU3N2EzNzk4Yzk0YjViZDgxOGYyYjI1ODVmZjhmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZI0TTshu8-ndAFurGZu9JZoh9llyCQvcTQBHp6g0ps)

**Comment by Raj-Mandal-20** [comment]
Hii @KevLehman , Yes I am using WSL2, followed what you have told but still shows this error. I have recloned the repo again but still facing the problem. yarn dev still stuck on the file changes but when I ran yarn dsv it rendered the client page but with some errors.

## Here are the Logs
![image](https://github.com/user-attachments/assets/9647694a-42f6-4e36-9074-0b714f7d785b)
![image](https://github.com/user-attachments/assets/9c32bd6a-368e-4ad2-a54c-c27b5f7b92b5)

## Client Side Logs
![image](https://github.com/user-attachments/assets/e8962457-9ce3-485f-a022-b7dda5437cfd)

**Comment by reetp** [comment]
How much RAM have you got?
You really need at least 12Gb and preferably 16Gb for trying to build on Windows/WSL2
I have a pretty powerful Linux workstation with 64Gb RAM and even that takes a several minutes with `yarn` and then `yarn dsv`

**Comment by Raj-Mandal-20** [comment]
Hello @reetp ,
I have 16 GB of RAM, and the i7 processor still facing this problem.
I think this is happening because of WSL, so, I am Dual Booting my PC with Ubuntu if it works I will inform in this thread.

**Comment by Raj-Mandal-20** [comment]
Hello @reetp  ,
I have 16 GB of RAM, and i7 processor still facing this problem.
I think this is happening because of WSL, so, I am Dual Booting my PC with Ubuntu if it works I will inform in this thread.

**Comment by reetp** [comment]
No need to @ people thanks.

I just cloned and ran it on my Ubuntu 22.04 desktop as a test and it worked.


I did this:

```
sudo apt install g++ build-essential git curl python2-minimal
sudo apt install nodejs
sudo apt install libvips
sudo apt install node-gyp
```

Install the npm package manager with this command.

`wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`

This should be added to your .bashrc/.zshrc/.profile file:

...
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
...

Reload one of:

```
bash: source ~/.bashrc
zsh: source ~/.zshrc
ksh: . ~/.profile
```

Do NOT update npm

Install Node 14.21.3

`npm install 14.21.3`

Install Meteor

`npm install -g meteor`

Install yarn

`npm install -g yarn`

```
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
```
Then:

`yarn`

Be patient.

Then:

`yarn dsv`

Be very very very patient.

```
@rocket.chat/meteor:dsv: I20240723-11:51:24.199(2)? +-----------------------------------------------+
@rocket.chat/meteor:dsv: I20240723-11:51:24.199(2)? |                 SERVER RUNNING                |
@rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? +-----------------------------------------------+
@rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |                                               |
@rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |  Rocket.Chat Version: 6.11.0-develop          |
@rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |       NodeJS Version: 14.21.4 - x64           |
@rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |      MongoDB Version: 7.0.5                   |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |       MongoDB Engine: wiredTiger              |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |             Platform: linux                   |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |         Process Port: 22655                   |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |             Site URL: http://localhost:3000/  |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |     ReplicaSet OpLog: Enabled                 |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |          Commit Hash: ee60ea659d              |
@rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |        Commit Branch: develop                 |
@rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? |                                               |
@rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? +-----------------------------------------------+
@rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.618Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/REGISTRY: '$node' service is registered.
@rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.619Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/REGISTRY: 'matrix' service is registered.
@rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.620Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/$NODE: Service '$node' started.
@rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.620Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/MATRIX: Service 'matrix' started.
@rocket.chat/meteor:dsv: I20240723-11:51:24.203(2)? [2024-07-23T09:51:23.621Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/BROKER: ✔ ServiceBroker with 2 service(s) started successfully in 543ms.
@rocket.chat/meteor:dsv: => Started your app.
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: => App running at: http://localhost:3000/

```

**Comment by Raj-Mandal-20** [comment]
It works thanks a lot **reetp.**

**Comment by mohanRajPartha** [comment]
> No need to @ people thanks.
> 
> I just cloned and ran it on my Ubuntu 22.04 desktop as a test and it worked.
> 
> I did this:
> 
> ```
> sudo apt install g++ build-essential git curl python2-minimal
> sudo apt install nodejs
> sudo apt install libvips
> sudo apt install node-gyp
> ```
> 
> Install the npm package manager with this command.
> 
> `wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash`
> 
> This should be added to your .bashrc/.zshrc/.profile file:
> 
> ... export NVM_DIR="$HOME/.nvm" [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion ...
> 
> Reload one of:
> 
> ```
> bash: source ~/.bashrc
> zsh: source ~/.zshrc
> ksh: . ~/.profile
> ```
> 
> Do NOT update npm
> 
> Install Node 14.21.3
> 
> `npm install 14.21.3`
> 
> Install Meteor
> 
> `npm install -g meteor`
> 
> Install yarn
> 
> `npm install -g yarn`
> 
> ```
> git clone https://github.com/RocketChat/Rocket.Chat.git
> cd Rocket.Chat
> ```
> 
> Then:
> 
> `yarn`
> 
> Be patient.
> 
> Then:
> 
> `yarn dsv`
> 
> Be very very very patient.
> 
> ```
> @rocket.chat/meteor:dsv: I20240723-11:51:24.199(2)? +-----------------------------------------------+
> @rocket.chat/meteor:dsv: I20240723-11:51:24.199(2)? |                 SERVER RUNNING                |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? +-----------------------------------------------+
> @rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |                                               |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |  Rocket.Chat Version: 6.11.0-develop          |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |       NodeJS Version: 14.21.4 - x64           |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.200(2)? |      MongoDB Version: 7.0.5                   |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |       MongoDB Engine: wiredTiger              |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |             Platform: linux                   |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |         Process Port: 22655                   |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |             Site URL: http://localhost:3000/  |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |     ReplicaSet OpLog: Enabled                 |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |          Commit Hash: ee60ea659d              |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.201(2)? |        Commit Branch: develop                 |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? |                                               |
> @rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? +-----------------------------------------------+
> @rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.618Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/REGISTRY: '$node' service is registered.
> @rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.619Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/REGISTRY: 'matrix' service is registered.
> @rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.620Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/$NODE: Service '$node' started.
> @rocket.chat/meteor:dsv: I20240723-11:51:24.202(2)? [2024-07-23T09:51:23.620Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/MATRIX: Service 'matrix' started.
> @rocket.chat/meteor:dsv: I20240723-11:51:24.203(2)? [2024-07-23T09:51:23.621Z] INFO  8b4b36c2-72b6-48fa-be24-7e278ed5b039/BROKER: ✔ ServiceBroker with 2 service(s) started successfully in 543ms.
> @rocket.chat/meteor:dsv: => Started your app.
> @rocket.chat/meteor:dsv: 
> @rocket.chat/meteor:dsv: => App running at: http://localhost:3000/
> ```

which version of meteor did you use?

**Comment by mohanRajPartha** [comment]
I will try with the latest version of meteor
using `npm install -g meteor`

**Comment by reetp** [comment]
> No need to @ people thanks.

^^^^^^^^^^^^^^^^

This is a support issue, not a bug.

Please stop commenting on the issue and use the community support channel here:

https://open.rocket.chat/channel/support

Thanks.
