### ISSUE TITLE
npm Install Failure After Rocket.Chat Update to Version 6.10

### ISSUE THREAD

**Issue by yeddeka** [RocketChat/Rocket.Chat#32853]
@reetp 
### Description:

Dear Support Team,

I hope this message finds you well.

We are experiencing an issue following our recent update of Rocket.Chat from version **6.9.3** to version **6.10**
. Since the update, our attempts to run npm install have consistently failed.

The error message we are encountering is as follows:

deno-bin@1.37.1 node install.js
event.js
throw er;  // unhandled error event
connect ETIMEOUT **140.82.121.4:443**

Please note that our server operates behind a proxy, and we have ensured that access to GitHub and deno.land/* is properly whitelisted.

Given this context, we would greatly appreciate your assistance in diagnosing the root cause of this issue.
Specifically, we are interested in understanding whether this is related to the recent update, the proxy configuration, or any other factors that may be contributing to the timeout error.

Thank you for your support. We look forward to your prompt response.

Best regards,
Kamel Ben Yedder

### Steps to reproduce:
`
cd rocketchat-6.10.0/programs/server && npm Install 
`
### Actual behavior:

`Error: connect ETIMEDOUT 140.82.121.4:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Emitted 'error' event on Writable instance at:
    at ClientRequest.eventHandlers.<computed> (/rocketchat-6.10.0/programs/server/npm/node_modules/deno-bin/node_modules/follow-redirects/index.js:37:24)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.121.4',
  port: 443
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deno-bin@1.37.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deno-bin@1.37.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /export/home/kvbapp/.npm/_logs/2024-07-22T09_19_49_489Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0
- License Type:  Community
- Number of Users: 20
- Operating System: REHL 8
- Deployment Method: tar 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 6  

### Client Setup Information

- Desktop App or Browser Version:  Chrome 126.0.6478.183 
- Operating System: Windows 10

### Relevant logs:
`
6564 verbose linkBins [
6564 verbose linkBins   { deno: 'bin/deno.js', 'deno-bin': 'bin/deno.js' },
6564 verbose linkBins   '/opt/kvb/rocketchat-6.10.0/programs/server/npm/node_modules/.bin',
6564 verbose linkBins   false
6564 verbose linkBins ]
6565 verbose rebuildBundles [ 'follow-redirects' ]
6566 info lifecycle deno-bin@1.37.1~install: deno-bin@1.37.1
6567 verbose lifecycle deno-bin@1.37.1~install: unsafe-perm in lifecycle true
6568 verbose lifecycle deno-bin@1.37.1~install: PATH: /opt/kvb/node-v14.21.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/kvb/rocketchat-6.10.0/programs/server/npm/node_modules/deno-bin/node_modules/.bin:/opt/kvb/rocketchat-6.10.0/programs/server/npm/node_modules/.bin:/opt/kvb/node-v14.21.3-linux-x64/bin:/opt/kvb/node-v14.21.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/kvb/rocketchat-6.10.0/programs/server/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/export/home/kvbapp/bin:/opt/kvb/bin:/export/home/kvbapp/bin:/export/home/kvbapp/src/collab-scripts
6569 verbose lifecycle deno-bin@1.37.1~install: CWD: /opt/kvb/rocketchat-6.10.0/programs/server/npm/node_modules/deno-bin
6570 silly lifecycle deno-bin@1.37.1~install: Args: [ '-c', 'node install.js' ]
6571 silly lifecycle deno-bin@1.37.1~install: Returned: code: 1  signal: null
6572 info lifecycle deno-bin@1.37.1~install: Failed to exec install script
6573 verbose stack Error: deno-bin@1.37.1 install: `node install.js`
6573 verbose stack Exit status 1
6573 verbose stack     at EventEmitter.<anonymous> (/opt/kvb/node-v14.21.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
6573 verbose stack     at EventEmitter.emit (events.js:400:28)
6573 verbose stack     at ChildProcess.<anonymous> (/opt/kvb/node-v14.21.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6573 verbose stack     at ChildProcess.emit (events.js:400:28)
6573 verbose stack     at maybeClose (internal/child_process.js:1088:16)
6573 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
6574 verbose pkgid deno-bin@1.37.1
6575 verbose cwd /opt/kvb/rocketchat-6.10.0/programs/server/npm
6576 verbose Linux 4.18.0-513.24.1.el8_9.x86_64
6577 verbose argv "/opt/kvb/node-v14.21.3-linux-x64/bin/node" "/opt/kvb/node-v14.21.3-linux-x64/bin/npm" "rebuild" "--update-binary"
6578 verbose node v14.21.3
6579 verbose npm  v6.14.18
6580 error code ELIFECYCLE
6581 error errno 1
6582 error deno-bin@1.37.1 install: `node install.js`
6582 error Exit status 1
6583 error Failed at the deno-bin@1.37.1 install script.
6583 error This is probably not a problem with npm. There is likely additional logging output above.
6584 verbose exit [ 1, true ]

`

**Comment by reetp** [comment]
Note - this is not support. It is an issue tracker.

We would appreciate it if you filled out a bug template properly as per this - it helps speed up triaging issues:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

If you have a Pro or EE licence you can contact support directly.

If you have a Starter or CE licence then support is in the https:/forums.rocket.chat or https://open.rocket.chat

This is likely related to these - always search and read old issues before posting a new one:

https://github.com/RocketChat/Rocket.Chat/issues/32761
https://github.com/RocketChat/Rocket.Chat/issues/32759

If one of these is your issue then please close this and follow up on the appropriate issue. 

Thanks.

**Comment by yeddeka** [comment]
@reetp

**Comment by reetp** [comment]
> @reetp

Please don't @ people. They will help if they can.

Oplogs??

Also seach here for "deno".

This is already known via the above links.

**Comment by DerFaysal** [comment]
i have the same Issue! Any updates on this?

**Comment by reetp** [comment]
> i have the same Issue!

You have provided no debugging information so it is impossible to help you. Exactly the same? Absolutely identical? 

Then read this:

> This is already known via the above links.

https://github.com/RocketChat/Rocket.Chat/issues/32853#issuecomment-2244419536


Otherwise you need to test on the latest version - at least 6.11.0 -  and then fill out a bug template properly.

Thanks.
