### ISSUE TITLE
Long topic message are not splitted on multiple lines

### ISSUE THREAD

**Issue by s17t** [RocketChat/Rocket.Chat#3285]
Your Rocket.Chat version: 0.29

as the subject. The best would be provide HTML formatting for topic message.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
