### ISSUE TITLE
Ignore Links in code blocks

### ISSUE THREAD

**Issue by orschaef** [RocketChat/Rocket.Chat#3286]
Rocket.Chat version: 1.3.1 (15)

**Problem**
If you post code like the block below, the links get resolved ... what causes 3 images to appear in the chat.
That leads to annoyed chat partners, especially if you post a larger example json with a bunch of links... ;-)

```
 {
      "id": 2,
      "imageUrl": "https://pbs.twimg.com/profile_images/562466745340817408/_nIu8KHX.jpeg",
      "thumbnailUrl": "https://i.ytimg.com/vi/6sta6Gkpgcw/maxresdefault.jpg",
      "detailsUrl": "http://www.petscorner.co.uk/petopedia/wp-content/uploads/header-kittens.jpg"
}
```

**Steps to reproduce**
Copy the code block above and paste it into rocket chat... you wil see the code block ... and 3 sweet kittens ;)

**Possible Solution**
Deactivate link resolution in code blocks (or at least give a possibility to manually activate/deactivate it)

**Comment by vetash** [comment]
Also in <links|http://www.markdowntutorial.com/>

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
