### ISSUE TITLE
SMTP mail issue

### ISSUE THREAD

**Issue by jakesullyneytiri** [RocketChat/Rocket.Chat#3288]
Hi,

I just installed rocket.chat and when i setup the SMTP i click save and then send test mail it tells me it sends me a mail to my email adress but i still do not recive anything? it's like SMTP function is broken or something so could you guys help me out?

Your Rocket.Chat version: 0.31.0

**Comment by jakesullyneytiri** [comment]
Okay i found this

(Mail not sent; to enable sending, set the MAIL_URL environment variable.) 

so next question where is the config file for this line located? i'm using script onto clean ubuntu 14.04 no docker and it's runing under Node.js

**Comment by jakesullyneytiri** [comment]
Okay akward moment i tried again configuring the SMTP function and out of no where it just started to work :/ odd really i did same config earlier 5 times but then it errored out and wouldn't send any mails but now it actually did send one :/ odd anyhow problem fixed.

**Comment by marceloschmidt** [comment]
Currently you have to reboot the server. Once we upgrade to Meteor 1.3 you won't need to reboot anymore, as this has been fixed in Meteor Code.
