### ISSUE TITLE
Mobile App issue

### ISSUE THREAD

**Issue by jakesullyneytiri** [RocketChat/Rocket.Chat#3289]
Hi,

I'm trying to use the mobile app for android but problem is when i type in url to rocket.chat it throws ERROR: Could not connect to the server! Abort: Abort. but if i browse to url via pc it works just fine :/ so i'm clueless why it wont work on mobile app? i followed this guide https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04 to setup rocket.chat on droplet at digitalocean :/ it uses nginx as proxy method to put 3000 port as 80 on a domain but mobile app still rejects it so yeah any clue why??
Your Rocket.Chat version: 0.31.0

Update: All is now fine :) after searching around i finally found out what was behind to why mobile app rejected the url it was due to SSL not being verified on mobile phones once i got that part fixed the mobile app finally accepted my url and so it downloaded files and letted me login :)

/Thanks

**Comment by yuchaozh** [comment]
Hi @jakesullyneytiri, I have the same problem now. How do you fix the issue that SSL not being verified on mobile phones?

Thanks.

**Comment by jakesullyneytiri** [comment]
Hi sorry for late reply, well issue was that my web server wasn't ussing a derpm or w.e file is called again and that it wasn't ussing fully certificate from let'sencrypt once i corrected it the mobile devices could load the chat url as verified :)
