### ISSUE TITLE
domain .me does not work

### ISSUE THREAD

**Issue by johnceltar** [RocketChat/Rocket.Chat#3290]
Hi,

i can not register new Users with our domain .me (blackspot.me) in Rocket.Chat (0.30 latest). 

I think it is a bug or is there a chance to change the add the .me Domain anywhere?

Thank and best regards
celtar (from blackspot.me)

**Comment by marceloschmidt** [comment]
I can register with @whatever.me... Can you try on https://demo.rocket.chat?

**Comment by dytec** [comment]
I can´t register with a .rocks domain either...

**Comment by johnceltar** [comment]
Hi,

i try it 8.23 CET - and get a Failure "Invalid Domain".

it is the same failure if you try to create a user with a .me Domain.

Hope it helps.

thx
celtar

**Comment by marceloschmidt** [comment]
@johnceltar what does that mean? can you show us printscreens of the error? did you try registering on demo?

**Comment by johnceltar** [comment]
Hi,

just try to explain it.

I try to register on your Demo Chat Server (see attached Screenshot) 
with E-Mail celtar@blackspot.me - it does not working - i can not 
continue. (i think last time i got a failure but now it does not 
continue without a failure notice)

If i try to add a User (As an Administrator) in my own rocket.chat 
System (Adduser) wit celtar@blackspot.me i got a short Message Popup 
and  a failure "invalid Domain" see attached Screenshot (latest Version 
0.31)

Is there something else i can do or explain? (sorry my english is not so 
well - i am a german).

My Server:
Debian 8 (Jessie) with latest patches
Virtual Server with 4 GB RAM and a small SSD
Nginx Reverse Proxy System (i try it also without - same failure)

Thanks for Help
John Celtar


Am 23.05.2016 um 21:06 schrieb Marcelo Schmidt:

**Comment by marceloschmidt** [comment]
In our server this domain fails because we use DNS Domain Check
![image](https://cloud.githubusercontent.com/assets/1986378/15483690/5afba918-210c-11e6-8c07-1b03251dfdf2.png)
and this domain fails the check.

**Comment by AJ-Acevedo** [comment]
Could it be something with the regex [here](https://github.com/RocketChat/Rocket.Chat/blob/611ecae62cbe447f8ee89a25549792d42a5cdb32/packages/rocketchat-lib/server/lib/validateEmailDomain.js#L22)?

```js
RocketChat.validateEmailDomain = function(email) {
	const emailValidation = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
	if (!emailValidation.test(email)) {
		throw new Meteor.Error('error-invalid-email', 'Invalid email ' + email, { function: 'RocketChat.validateEmailDomain', email: email });
	}
```

**Comment by johnceltar** [comment]
Hi,

thanks for the Info (DNS Check was enabled). It was the missing reverse DNS entry for my Domain. I will fix that. 

Please close this Issue.

Thanks and best regards
john

**Comment by AJ-Acevedo** [comment]
@johnceltar Does it work if you add the domain to the [Whitelist](https://github.com/RocketChat/Rocket.Chat/blob/611ecae62cbe447f8ee89a25549792d42a5cdb32/packages/rocketchat-lib/server/lib/validateEmailDomain.js#L3)?

**Comment by jpelaez01** [comment]
@marceloschmidt thanks. It worked for me.
