### ISSUE TITLE
upload big file above 100MB，Unable to upload

### ISSUE THREAD

**Issue by tianle8888** [RocketChat/Rocket.Chat#32922]
﻿### Description:
rocket.chat Version 6.9.3
settings/FileUpload Maximum File Upload Size (in bytes):900000000
Storage Type：GridFS
License Type:Community Version
install：docker
Desktop App ：3.9.15
﻿
### Steps to reproduce:
1， upload file size 100MB to channel
2， After uploading, no error message was received and the chat window did not display the uploaded file
3.，"..." ->file can see the file, but it cannot be downloaded and there are no errors

﻿

**Comment by MarlynxLinux** [comment]
Hello, if you are using the nginx in proxy mode then use the in the configuration
`client_max_body_size 1000M;`

**Comment by reetp** [comment]
Don't use GridFS for **anything** beyond testing. It will grind your install to a halt.

Use proper file storage. Local, S3 or whatever.

Set file limits in your reverse proxy.

I'd also get the migrate script from here and move any existing files out of GridFS.

This isn't a bug in Rocket.Chat.

For support please use the forums or open.rocket.chat

**Comment by tianle8888** [comment]
@MarlynxLinux It has already been added for testing client_max_body_size 1024M;

**Comment by reetp** [comment]
> @MarlynxLinux 

Please don't @. It is unnecessary.

> Don't use GridFS

Have you changed that? If not then do it before you do anything else.

> I am accessing the Rocket.chat server directly through the HTTP  protocol   without using an nginx proxy, and uploading files has the same issue

Don't do that except on a local test machine.

Use a proxy and SSL/https.

> file can see the file, but it cannot be downloaded and there are no errors

﻿What sort of file is it?

**Comment by tianle8888** [comment]
zip file

**Comment by reetp** [comment]
Ok,

Server 6.10.1
Set my file upload limit to -1
Local file storage
Apache reverse proxy

Uploaded a 200Mb test zip to a new test channel.

Done on my mobile via wifi. Zero issues.

See above re File Storage, File Size etc.

![Screenshot_20240729_152216_RocketChat Experimental.jpg](https://github.com/user-attachments/assets/08b0f41a-1312-41dd-9c5a-a65266fa4135)

![Screenshot_20240729_152244_RocketChat Experimental.jpg](https://github.com/user-attachments/assets/fd8c1d99-83e0-4a0f-89ad-20e6439b3bcc)

**Comment by tianle8888** [comment]
After changing to a file system, my issue was resolved. Currently, the 300MB file upload test is normal. Thank you

**Comment by reetp** [comment]
> After changing to a file system, my issue was resolved. Currently, the 300MB file upload test is normal. Thank you

Glad you got it fixed.

I really suggest you use the migrate script here and clear out GridFS.
