### ISSUE TITLE
Global Search Error: 'Room not Found' When Jumping to Thread Messages from Direct Messages

### ISSUE THREAD

**Issue by CyberStranger** [RocketChat/Rocket.Chat#32956]
### Description:

When using the Search Messages feature with the Global search option enabled, the search results will correctly include messages located within a thread. However, if you attempt to jump to one of these thread messages by clicking the "Jump to Message" button, an error message "Room not Found" appears, even though you are a member of the room where the thread is located.

### Steps to reproduce:
1. Enter any room and create a thread.
2. Write any phrase within the thread.
3. Open any direct message conversation.
4. Click on the "Search Messages" button.
5. Enable the Global Search toggle.
6. In the search bar, enter the phrase you wrote in the thread.
7. When the search results appear, click on the "Jump to message" button.
### Expected behavior:

The system should jump to the specific message in the thread within the correct room without any errors.

### Actual behavior:

An error message "Room not Found" is displayed. This issue is specifically observed when the global search is initiated from a direct message window with another user. The error does not occur when the global search is activated from an open group window, and the message jump works successfully.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.8.0
- License Type: Enterprise
- Number of Users: 
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.15 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: RocketChat Electron 4.0.1
- Operating System: Microsoft Windows 10

### Additional context

![animation1](https://github.com/user-attachments/assets/fc3ff1c3-546f-4cfa-a865-f120b414a3ea)

**Comment by reetp** [comment]
Please always test on latest (currently 6.10.2 or 6.11.x). A lot happens in a few months.

Also upgrade to latest 6.8.x to fix outstanding bugs.

I think similar has been reported before. Have a search here as well.

**Comment by CyberStranger** [comment]
I was able to reproduce this issue on 6.10.2

**Comment by Gummikavalier** [comment]
This is still reproducible in RC 7.1.0. (Exactly as depicted by CyberStranger.)
