### ISSUE TITLE
Language selection inconsistency between header and footer dropdowns

### ISSUE THREAD

**Issue by NayanshiSingh** [RocketChat/Rocket.Chat#32960]
### Description:
When changing the language from the dropdown menu in the header, the selected language is correctly displayed in the header dropdown. However, the footer dropdown always shows "EN" (English) regardless of the selected language. The footer dropdown should also reflect the selected language.

### Steps to reproduce:

1. Go to the website.
2. Change the language from the dropdown menu in the header.
3. Scroll down to the footer.
4. Observe that the footer dropdown still shows "EN" instead of the selected language.

### Expected behavior:

The footer language dropdown should display the selected language, just like the header dropdown.

### Actual behavior:
The footer dropdown always shows "EN" (English) regardless of the selected language. The footer dropdown should also reflect the selected language.

https://github.com/user-attachments/assets/12c99626-b491-4494-95e9-bc757ee6cb06

### Server Setup Information:

- Version of Rocket.Chat Server: 
- License Type:
- Number of Users: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:  23H2
- Operating System: Windows 11

**Comment by reetp** [comment]
Thanks for reporting.

I'll refer this to the web team as it isn't a Rocket.Chat server issue.
