### ISSUE TITLE
Bug report template leads to 404

### ISSUE THREAD

**Issue by danielpotthast** [RocketChat/Rocket.Chat#32962]
### Description:

The referenced url https://developer.rocket.chat/rocket.chat/contribute-to-rocket.chat/ways-to-contribute/report-bugs doesn't exist.

### Steps to reproduce:

1. Create a new bug report
2. Try to follow the guide

### Expected behavior:

A working guide

### Actual behavior:

A nice, but useless 404 page

**Comment by reetp** [comment]
Thanks for reporting.

It should probably be these. I'll get it updated.

https://developer.rocket.chat/docs/modes-of-contribution

https://developer.rocket.chat/docs/contribute-through-bug-reporting

**Comment by reetp** [comment]
I think you'll find this is now fixed.
