### ISSUE TITLE
Safari not rendering UI updates in random places

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3296]
This happens on iOS when you open the side panel.  It doesn't render on first pass.  You have to trigger it again

**Comment by ninetiger99** [comment]
I agree. I have same bug. On my iphone 6s. 

This bug can make below. 

Side panel button click and click in public room. 
For example. You click people icon and bell icon and clip icon repeatedly. Then not show side panel UI.

**Comment by MartinSchoeler** [comment]
@geekgonecrazy Have you seen this bug recently?

**Comment by geekgonecrazy** [comment]
I was reporting on behalf of someone else.  If no one is seeing it, probably safe to close now :)
