### ISSUE TITLE
Strange log when sendeng attachment

### ISSUE THREAD

**Issue by olodar** [RocketChat/Rocket.Chat#32976]
### Description:

When I sending attachments, I see strange logs in journal (see log file)

### Steps to reproduce:
1. Send attachment
2. See logs

### Expected behavior:
-

### Actual behavior:
-

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.2
- License Type: ?
- Number of Users: 1
- Operating System: Ubuntu 22.04
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 14.21.3
- MongoDB Version: 7.0.12

### Client Setup Information

- Desktop App or Browser Version: Chromium 127.0.6533.72
- Operating System: Ubuntu 22.04

### Relevant logs:
[rocketchat.log](https://github.com/user-attachments/files/16486517/rocketchat.log)

**Comment by reetp** [comment]
Hi.

What sort of attachments?

All of them? Some of them?

Can you also test on the latest 6.11.x as well please?

**Comment by olodar** [comment]
@reetp It seems appearing with every file type (tested jpg, png, mkv).

>
Hi.

What sort of attachments?

All of them? Some of them?

Can you also test on the latest 6.11.x as well please?

Where I can download it? 
https://releases.rocket.chat/latest/download gives latest ver 6.10.2

**Comment by reetp** [comment]
>  It seems appearing with every file type (tested jpg, png, mkv)

OK.

> Where I can download it?

You are using tar so here I think:

https://github.com/RocketChat/Rocket.Chat/releases

https://github.com/RocketChat/Rocket.Chat/tags

Or run a test VM + docker.

**Comment by olodar** [comment]
@reetp No, there's no those such logs in 6.11.0, seems it was fixed.
