### ISSUE TITLE
request: home screen to join channel instead

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3298]
Your Rocket.Chat version: 0.31

Hey folks,

Minor issue. Uppojn joining rocket.chat with a new session you get the home screen, configurable via Layout -> Content. But instead would it be awesome if you would join (or could join) a pre-determined channel instead. Especially on the mobile this would save several click each time. And to be honest no matter what you write in the home tab no one would read/appreciate it more than once.

Thanks & Cheers!
-Chris.

**Comment by jcherqui** [comment]
:+1:

**Comment by JigSawFr** [comment]
Could be great, yes !

**Comment by kruff** [comment]
+++

**Comment by ErikXXon** [comment]
Sounds great

**Comment by rodrigok** [comment]
This feature was already implemented, you can set the channel to be loaded after login at `Admin > General > First Channel After Login`
