### ISSUE TITLE
Messages before July 1st disappeared after upgrading from 6.10.0 to 6.10.1

### ISSUE THREAD

**Issue by ETararenko** [RocketChat/Rocket.Chat#33010]
### Description:

Messages before July 1st disappeared after upgrading from 6.10.0 to 6.10.1

### Steps to reproduce:

1. Upgrade to 6.10.1 version
2. Check any room with a history older than July 1st

### Expected behavior:

Ability to view old messages

### Actual behavior:

Messages before July 1st disappeared

### Server Setup Information:

- Version of Rocket.Chat Server:  6.10.1
- License Type: Community
- Number of Users: 
- Operating System: Ubuntu 22.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v14.21.3
- MongoDB Version: 6.0.11 

### Client Setup Information

- Desktop App or Browser Version: 3.9.9, 4.0.0, 4.0.1.
- Operating System: Windows 10, MacOS

### Additional context

We updated Rosketchat from version 6.7.0 to 6.10.1 and all our messages disappeared before July 1.
After that, we created a clone of the server from the backup before the upgrade and upgraded it step by step 6.7.7 -> 6.8.5 -> 6.9.5 -> 6.10.0 -> 6.10.1
After updating from 6.10.0 to 6.10.1, messages disappeared on the clone.
Updating to the latest version 6.10.2 did not help.

**Comment by Skeen** [comment]
I believe we are seeing the same issue on our RocketChat Cloud instance. We have reported the issue to Rocket.Chat Support.

**Comment by Gummikavalier** [comment]
Does this concern all channels?

At the time it was possible to enable channel based pruning settings, after which they were removed for a long time, as they didn't work properly.

If you have not enabled any channel specific message pruning settings at the time on channel, it'd be best to first check whether the messages got really deleted, indicating a pruning issue (there were such changes in 6.10.1), or whether it is just a visibility issue in the UX.

If you have access to the database of your instance, you can run these commands to print the timestamps of existing messages on some specific channel:

```
mongosh rocketchat

DBQuery.shellBatchSize = 1000000

db.rocketchat_room.find( {'name':'channelname_in_ui'}, {'name':1});

  ^ get the _id of the room

db.rocketchat_message.find({'rid':'paste_room_id_here'},{'ts':1})

  ^ this prints id-numbers and timestamps of all messages on the channel
```

Note: I'm not employee of RocketChat, but concerned about such issue, if no logical reason for the disappearance of the messages can be found.

**Comment by Gummikavalier** [comment]
Another question that may be important: Do you have global pruning of messages enabled in admin settings and if you do, what are your choices there?

**Comment by ETararenko** [comment]
Looks like they were deleted from the database. The earliest date for one of the chats that is often used is
```
db.rocketchat_message.find({'rid':'paste_room_id_here'},{'ts':1});
2024-07-01T13:22:45.840Z
```
We have enabled a 180 day retention policy for all messages/rooms.

**Comment by Gummikavalier** [comment]
Ok, thanks. Did those `-1` values appear for you too into fields that previous versions were filled up with that `180`?

**Comment by Skeen** [comment]
> Ok, thanks. Did those `-1` values appear for you too into fields that in previous versions were filled up with that `180`?

It said 180 in all the fields for us, but I unfortunately cannot check the database as I'm on the Rocket.Chat Cloud solution.

**Comment by ETararenko** [comment]
> Ok, thanks. Did those `-1` values appear for you too into fields that in previous versions were filled up with that `180`?

we don't have -1 values ​​anywhere, everywhere where possible it's 180

**Comment by gabriellsh** [comment]
@Gummikavalier Settings w/ -1 value are just cached in the UI, they should disappear eventually or if you clear the cache.

@ETararenko Could you perhaps get the Setting value from the database? We introduced a change in 6.10 in order to start saving the retention policy settings in millis instead of days to allow for a narrower time frame (hours and minutes). I'd also like to know if every room was affected. Could you also attachone or 2 records from the rooms database of rooms that were affected? Make sure to hide any secrets if there are any, I'm interested in the room configuration.

The settings id's that I need are: `['RetentionPolicy_TTL_Channels', 'RetentionPolicy_TTL_Groups', 'RetentionPolicy_TTL_DMs']`

Thanks in advance.

**Comment by Skeen** [comment]
>
> The settings id's that I need are: `['RetentionPolicy_TTL_Channels', 'RetentionPolicy_TTL_Groups', 'RetentionPolicy_TTL_DMs']`
> 
> Thanks in advance.

I'm seeing this:
```
{
    "_id": "RetentionPolicy_TTL_Channels",
    "value": 15552000000,
    "packageValue": 2592000000,
    "enterprise": false
  },
  {
    "_id": "RetentionPolicy_TTL_DMs",
    "value": 15552000000,
    "packageValue": 2592000000,
    "enterprise": false
  },
  {
    "_id": "RetentionPolicy_TTL_Groups",
    "value": 15552000000,
    "packageValue": 2592000000,
    "enterprise": false
  },
```
Which seems inline with the expectations of 180 days of retention policy.

180 days * 24 hours / day * 60 minutes / hour * 60 seconds / minute * 1000 milliseconds per second = 15552000000 milliseconds.

**Comment by ETararenko** [comment]
@gabriellsh Hello, сan you clarify from which collections you need information? A couple of records from rocketchat_room?
And where i can find` ['RetentionPolicy_TTL_Channels', 'RetentionPolicy_TTL_Groups', 'RetentionPolicy_TTL_DMs'`]?

**Comment by gabriellsh** [comment]
Hi @ETararenko  I linked a PR with the fix. It was an issue with settings reactivity. A patch should come out soon. For a workaround, you can disable Retention before upgrading, and then you can safely upgrade your workspace. Then just reenable it and it should work as normal.
