### ISSUE TITLE
Video message

### ISSUE THREAD

**Issue by duohost** [RocketChat/Rocket.Chat#3302]
Your Rocket.Chat version: (make sure you are running the latest)
Can you add video message button like audio button is here:
![film-countdown-number-1-008](https://cloud.githubusercontent.com/assets/19369515/15391044/6981422c-1dbf-11e6-8c57-2a985edee383.jpg)

**Comment by rasos** [comment]
Version 0.37 now has a video recording button. Works fine with browser, but not on my Android App (shows only black box, it seems that embedded web engine does not have access to mic/camera).

**Comment by MartinSchoeler** [comment]
This was already implemented.
