### ISSUE TITLE
Where can I download docker-compose.yml for rockerchat 5.4.8?

### ISSUE THREAD

**Issue by yuhvv** [RocketChat/Rocket.Chat#33064]
Where can I download docker-compose.yml for rockerchat 5.4.8? It cannot be used with the latest version of yml file

**Comment by reetp** [comment]
This is s support question, not a bug.

V5.x is no longer supported. You need to be on at least v6.5+

Please ask on https://open.rocket.chat `#support` or https://forums.koozali.org
