### ISSUE TITLE
Version 6.10.3 missing from build server

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#33072]
### Description:

The new release 6.10.3 which includes a security hotfix is missing on the build server.  Download link should be:
https://cdn-download.rocket.chat/build/rocket.chat-6.10.3.tgz
But it results in a 404 Not found error.  6.11.1 is there, but not 6.10.3

### Steps to reproduce:

1. Go to https://cdn-download.rocket.chat/build/rocket.chat-6.10.3.tgz
2. Wait for download
3. Get 404 error instead.

### Expected behavior:

I would expect to download the security fixed version.

### Actual behavior:

404 error, instead.

### Server Setup Information:

- Version of Rocket.Chat Server: Not applicable
- License Type: Not applicable
- Number of Users:  Not applicable
- Operating System: Not applicable
- Deployment Method:  Not applicable
- Number of Running Instances: Not applicable
- DB Replicaset Oplog:  Not applicable
- NodeJS Version: Not applicable
- MongoDB Version: Not applicable

### Client Setup Information

- Desktop App or Browser Version: Not applicable
- Operating System: Not applicable

**Comment by reetp** [comment]
This is known and under investigation.

**Comment by chotaire** [comment]
There is also no 6.10.3 on Docker Hub. Talking security hotrfixes, you guys do keep an eye on this, right?

![bb5048108de74e01f42f8cac25ac43a6](https://github.com/user-attachments/assets/a7bd95e1-6456-4502-8974-41066abb3dae)

**Comment by casalsgh** [comment]
Team, 6.10.3 had problems. Please skip directly to 6.10.4; 
we'll not have a 6.10.3 being shared and will be discontinued.
