### ISSUE TITLE
Feature: Use electron spell checking

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#3307]
Looks like electron merged spell checking a few years ago here: https://github.com/electron/electron/pull/942

Is there any way we can get spell checking enabled in the desktop clients?

If this is enabled for windows and not linux, or Ubuntu and the person that builds my client is not doing something right, please let me know. 

I'm currently using this person's build because there is no Fedora repo / rpm available: https://copr.fedorainfracloud.org/coprs/mosquito/rocketchat/

**Comment by geekgonecrazy** [comment]
This actually doesn't work for windows, but works just fine on ubuntu.  That Fedora build maybe missing the spellcheck package.  

Please check here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/24  We want to get an official rpm.

**Comment by bios-ben** [comment]
"This doesn't work for windows" are you saying electron or rocket.chat.electron? I'd like to see some spell check in the windows client and was wondering if I should make a ticket but found this mention here.
