### ISSUE TITLE
Cannot close the above reminder

### ISSUE THREAD

**Issue by sunstrider12** [RocketChat/Rocket.Chat#33078]
### Description:

when i close this reminder, 
server log error:
```
{"level":50,"time":"2024-08-17T05:53:11.999Z","pid":1,"hostname":"fa083c6e624d","name":"System","err":{"type":"CloudWorkspaceConnectionError","message":"Failed to connect to Rocket.Chat Cloud: undefined","stack":"CloudWorkspaceConnectionError: Failed to connect to Rocket.Chat Cloud: undefined\n    at server/modules/core-apps/cloudAnnouncements.module.ts:256:10\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/modules/core-apps/cloudAnnouncements.module.ts:87:27\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"CloudWorkspaceConnectionError"},"msg":"Failed to connect to Rocket.Chat Cloud: undefined"}
```

### Actual behavior:

<img width="1072" alt="图片" src="https://github.com/user-attachments/assets/b423f0d3-d0fd-48a3-9111-211818b98f0d">

### Server Setup Information:

- Version of Rocket.Chat Server:  6.11.1
- License Type: 
- Number of Users: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 3.9.14
- Operating System: macos

**Comment by reetp** [comment]
> when i close this reminder,
> server log error:

Does the banner actually close?

This information is important to help debug:

License Type:
Number of Users:
Operating System:
Deployment Method:
Number of Running Instances:
DB Replicaset Oplog:
NodeJS Version:
MongoDB Version:

I suspect this may be a duplicate of this issue but it depends whether the banner disappears. 

https://github.com/RocketChat/Rocket.Chat/issues/32018

More information required.
