### ISSUE TITLE
"Average of chat duration" analytics report is incorrect

### ISSUE THREAD

**Issue by paymanzafar1** [RocketChat/Rocket.Chat#33080]
### Description:
Hi.
I am using Rocket Chat version 6.11.1. 

I received the following report from Analytics menu for today. As you see the first agent had 133 chats until now. 

![image](https://github.com/user-attachments/assets/3887fd2c-b1d1-4f2b-8e15-fef396f2214e)

But as you see the average chat duration for the same agent for today was 01:09:07 (One hour 9 minutes and 7 seconds) which is impossible for a 6 hours time period.

![image](https://github.com/user-attachments/assets/0bbfa898-54eb-4557-85d8-0f7469466de7)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.11.1
- License Type: Community
- Number of Users: 18
- Operating System: UBUNTU 22.04
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.16

**Comment by reetp** [comment]
Thanks for reportinfg.

Can you please fill out the reat of teh Sererv informatiom. This makes debugging easier.

**Comment by paymanzafar1** [comment]
Hi @reetp,
Thank you very much for your reply.
I completed the rest of server information table. Please note that I am already on the latest version.

**Comment by anoniz** [comment]
Hi, I am new to the codebase, can you tell where in the codebase , this issue is coming from? which module?

**Comment by reetp** [comment]
> Hi, I am new to the codebase, can you tell where in the codebase , this issue is coming from? which module?

That's a support question.

Please ask for help in the forums or https://open.rocket.chat #support

**Comment by paymanzafar1** [comment]
Hi @reetp,
Is there any update on this issue? Thank you.

**Comment by reetp** [comment]
> Hi @reetp,

No need to @ thanks.

> Is there any update on this issue?

I've referred it to the team to check.

**Comment by casalsgh** [comment]
Team, don't have the bandwith to check it rn, but added to list. Will see if we can have internal team take a look.

**Comment by renatobecker** [comment]
Hi @paymanzafar1 

Thanks for reporting the issue. Can you please share with us the time of the first conversation answered on the day assigned to this agent? And also what is the timezone of your workspace?

Thanks.

**Comment by paymanzafar1** [comment]
Hi @renatobecker 
Thanks for your follow up, and sorry for the delay to reply.
I investigated the operator chats at the reported date, and found that he did not closed the chats on time. This was the reason to have long average chat duration.
The problem is resolved.
