### ISSUE TITLE
Notifications don't handle the quoted text formatting

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3308]
When a user types >Message, the '>' is used to format the text within Rocket Chat, but the notification doesn't handle this and just prints out the plain text '>Message'.
![20160519-152346-](https://cloud.githubusercontent.com/assets/10524529/15406859/30a51c96-1dd6-11e6-87aa-007376b7db74.jpg)

Your Rocket.Chat version: 0.30.0 (Chrome)

**Comment by rodorgas** [comment]
There's no support for markup on Notifications API, so this is expected.

**Comment by timkinnane** [comment]
Is it not possible to parse desktop and email notifications through the same methods as message stream rendering, to include html converted from markdown? Obviously wouldn't work for push notifications, but email at least could be consistent.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/9979
