### ISSUE TITLE
Docker ran out of memory error

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#3309]
Your Rocket.Chat version: 0.31

I've had two outright crashes of Rocket.Chat.  One this week and one last week.
Seems to be a **Docker ran out of memory error**.

My temp fix has been to list all images
`sudo docker images`

Then remove any unused images
`sudo docker rmi <id>`

But It's definitely only a temp fix and would like to know if this is a bug or a way that I can fix it so i'm not getting calls at 2am from the teams :+1:

**Comment by geekgonecrazy** [comment]
This is a docker thing.  Typically you just have to keep an eye on it.  The more images you have the more space it takes.   But if you quickly are running out of hard drive space, you might want to consider using increasing the capacity.

**Comment by Nodraak** [comment]
If you don't build docker images, no temporary images will get created. Just clean after yourself when building containers :)
Note sure ifit can help, but you can limit the disk space allocated to docker.
