### ISSUE TITLE
Opening sidebar with big latency

### ISSUE THREAD

**Issue by klaus-spb** [RocketChat/Rocket.Chat#331]
On official site https://rocket.chat/ when open sidebar in room to see "Members List"  it`s opening with big latency. About 3-4 seconds.

On my local project i have not such problem. Seems because i have less users

**Comment by sampaiodiego** [comment]
yes @klaus-spb on live we have about 9000 users in General channel.. the members list wasn't optimized yet for this number of users, but we know the issue and will take a look before 1.0

thanks for pointing it out btw.
