### ISSUE TITLE
Internal Server Error file upload

### ISSUE THREAD

**Issue by chispaa** [RocketChat/Rocket.Chat#3310]
Your Rocket.Chat version: 0.27

Hi,

I was running Rocket.Chat without a problem as root. I changed the node user and now I can't upload files.

`I20160519-19:32:17.307(-4) Exception while invoking method 'ufsWrite' Error: EACCES, open '/tmp/ufs/nm2FRdk99kHw8PQNy'     at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].Meteor.methods.ufsWrite (packages/jalik_ufs/ufs-methods.js:168:1)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/opt/Rocket.Chat/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)     - - - - - `

The new user can write to /tmp, is there any other change that I should do for it to run as a different user?.

Thanks!.

**Comment by graywolf336** [comment]
Make sure the right permissions are set, since you was using root user there is a malconfigured permission somewhere.

**Comment by chispaa** [comment]
Thank you for your time, I though that it was writing to /tmp directly, not the ufs subdirectory.

Now it works great, thanks!.
