### ISSUE TITLE
Add flag to return list of all users instead of just a count

### ISSUE THREAD

**Issue by aBisoc** [RocketChat/Rocket.Chat#33106]
On the users.list api, I want to be able to just specify that I want to get all users, instead of sending a huge integer. https://developer.rocket.chat/apidocs/get-users-list

**Comment by reetp** [comment]
Hi.

First can you try and describe more accurately what you are trying to do as it isn't obvious to me.

> Gets all of the users in the system and their information, the result is only limited to what the request sender has access to view.

Do you have permission?

If you filled out a bug template properly it would help.

Also read this for some tips on how to report issues effectively.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

Note this is either a support question, or at best a NFR right now so this isn't really the right place to ask.

**Comment by aBisoc** [comment]
Thank you!
