### ISSUE TITLE
Ampersand symbol is messed up when using inline code format (`&`)

### ISSUE THREAD

**Issue by JackDragon** [RocketChat/Rocket.Chat#3311]
Your Rocket.Chat version: 0.30.0

The ampersand symbol becomes messed up and looks like the screen is crying when I wrap it using inline code convention.

![image](https://cloud.githubusercontent.com/assets/1388117/15413380/8afbe004-1de4-11e6-98cf-d62f517ed2ca.png)

**Comment by graywolf336** [comment]
You need to update one of your fonts, as it is missing the ampersand symbol.

References:
* #3144
* https://github.com/adobe-fonts/source-code-pro/issues/11
