### ISSUE TITLE
Storage memory consumption is increasing (android)

### ISSUE THREAD

**Issue by tmaczukin** [RocketChat/Rocket.Chat#3312]
Your Rocket.Chat version: 2.3.1, Android

Hi! As a follow up after our chit-chat today. I have a Rocket.Chat application on my Android phone. After the installation a week ago it was using ~30MB of my storage memory. Now it is using ~80MB. And I'm running out of available storage on my phone :).

During our talk we agreed, that:
1. You are caching the previous versions of application during update. You need to look on this and think how to decrease the storage usage.
2. It would be good to move cached data like messages, images end others (but not application settings nor login data) to the Android cache memory. Thanks to this a user like me will be able to remove cached data **without** logging out from the chat (what for me is a little problematic because my passwords has >30 characters). Now I can only "remove all data" of the application which will log me out of it.

Anyway - good work, and don't stop! :)

**Comment by azenan** [comment]
# Problem

This *may* be unrelated as I'm having this issue on Rocket.Chat+ Android v1.0.22.

I woke up this morning to a warning about my phone's system storage being almost full. Checking the storage settings I was shocked to find that Rocket.Chat+ was using 7.06GB of storage space.

![2017-11-22 08 41 58](https://user-images.githubusercontent.com/5036083/33144708-d06bbfec-cf72-11e7-9f2d-2c39916ac21f.png)

Sorry I don't have a screenshot of the settings page that shows the breakdown of where the storage was allocated: 95% or so was in the `User data` category.

# Other possibly useful details:

* Phone: Nexus 6P
* Android version: 8.0.0
* Rocket.Chat server is hosted by my company

**Comment by Hudell** [comment]
This issue was a problem with the old Cordova app, so I'll be closing it. If any similar problem is found on the newer apps, it should be registered on the related repository.
