### ISSUE TITLE
Previewing uploaded files cors problem

### ISSUE THREAD

**Issue by dqhieu9301** [RocketChat/Rocket.Chat#33122]
![image](https://github.com/user-attachments/assets/b800f649-e1aa-42a1-a2a6-519307962332)

When I call the file retrieval api in room-chat, I get a cors error while all other apis still work normally

**Comment by reetp** [comment]
This looks like a support issues and not a bug.

We can't help you without you completing a bug template.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

If you go here:

https://open.rocket.chat/channel/support

You can read this on how to report issues effectively:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98


In the meantime I suggest you get your reverse proxy set up as per the documentation and working correctly with https certificates as that will likely fix your issues.

https://docs.rocket.chat/v1/docs/deploy-with-docker-docker-compose#enable-https

Thanks.
