### ISSUE TITLE
"Unread on top" missing from user options

### ISSUE THREAD

**Issue by EqualMarcus** [RocketChat/Rocket.Chat#33125]
### Description:

The "Unread on top" option is available for global workspace settings / default user settings, but it's not actually visible on a per-user basis. 

### Steps to reproduce:

1. Go to preferences
2. Click around preferences, accessibility, etc
3. See no "Unread on top" option
4. Go to workspace 
5. Go to Settings 
6. Go to Accounts
7. Open "Default User Preferences"
8. See "Unread on top" option available

### Expected behavior:

To have a per-user level option for "Unread on top"

### Actual behavior:

No option available

### Server Setup Information:

- Version of Rocket.Chat Server: 6.9.2
- License Type: ?
- Number of Users: 203 
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 14
- MongoDB Version: ?

### Client Setup Information

- Desktop App or Browser Version: Desktop App 4.0.0
- Operating System: MacOS

### Additional context

N/A

### Relevant logs:

N/A

**Comment by reetp** [comment]
It is available in the list here:

![Screenshot_2024-08-22_19-45-03](https://github.com/user-attachments/assets/4d0bb83f-c117-4c15-9c91-938e78498c42)

I don't see a bug here.

**Comment by EqualMarcus** [comment]
Closing
