### ISSUE TITLE
Please darkmode in configuration

### ISSUE THREAD

**Issue by VBatalha** [RocketChat/Rocket.Chat#33132]
Please darkmode in configuration

**Comment by reetp** [comment]
Not sure what you mean.

We can't help you without you completing a bug template and describing your issue properly.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

If you go here you can read this on how to report issues effectively:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98
