### ISSUE TITLE
Make version information easier to gain

### ISSUE THREAD

**Issue by tmaczukin** [RocketChat/Rocket.Chat#3313]
For web application it's now impossible to find the version number (or I didn't find it - if it available somewhere, please guide me to it). I can find a version of Android app (and probably other mobile versions) but only through the application management panel.

I think that you can show a number of the version somewhere in the layout of the application for **all signed in** users. It will make easier for us to find the version number. And for you it would probably improve the quality of reported issues. You have a "Your version" field in the issue template - if I would use only the web based app I would be not able to provide the version number ;)

**Comment by matthias-brun** [comment]
Version information can be seen by browsing to the path `/api/info`.

**Comment by tmaczukin** [comment]
OK. So there is a way in web application, that's good. But I still consider that it would be better (and definitely easier for less technical people) to show this version explicitly somewhere in the application.

Entering `/api/info` by hand or looking it up in mobile OS applications management panels is not so user friendly as it could be :)

**Comment by mischah** [comment]
I feel pretty much the same and wanted to open an issue as well.

The `/api/info` workaround is nice though. 

> But I still consider that it would be better (and definitely easier for less technical people) to show this version explicitly somewhere in the application.

It actually is available within the user interface at  `/admin/info`. Problem. Regular users aren’t abe to get to this page.

I thought about adding the version number somewhere in HTML sourcecode. 
But I don’t know if this is a more convenient than looking at `/api/info`. At least people get a chance to get that information without knowing the internal URL structure.

**Use case**
People without admin privileges that like to report a bug.

**Comment by christianreiss** [comment]
Now we need a $version variable for the latest release so we can create an Icinga alert if we are not on the latest version. Oh sweet jebus, yes.

**Comment by graywolf336** [comment]
`RocketChat.Info` contains the version.

![screen shot 2016-05-24 at 8 29 50 pm](https://cloud.githubusercontent.com/assets/850391/15525272/4adcc6d8-21ee-11e6-8b50-cf96b0e96920.png)

**Comment by marceloschmidt** [comment]
This information is also stated under Administration / Info

![image](https://cloud.githubusercontent.com/assets/1986378/15553898/bc1e95a2-2297-11e6-8183-08793cfda559.png)
