### ISSUE TITLE
About rocketchat IOS APP E2EE photos display issues

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#33143]
Encrypted photos on rocketchat iOS app not friendly to users
When you receive photos which only display for 2 seconds and then go "white" (see the photo below)
![image](https://github.com/user-attachments/assets/3328a139-baa3-417b-be82-2581e8de8406)
Wanna see the photos? You have to exit the chat window and then go back to the chat window again and photos can display normally
That's really unfriendly 

rocketchat iOS APP version 4.50.1.63099 (the latest)

rocketchat 6.10.4

**Comment by reetp** [comment]
Thanks for reporting. Please fill out bug templates fully.

Please have a read on how to report bugs effectively. 

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

This should be tested on the latest code so at least 6.11.1 as of today.

You can also test on https://open.rocket.chat which is always latest.

Note you this should probably be in the react-native repo.

If the bug exists on open then re-open this bug in react-native.

Thanks.

**Comment by reetp** [comment]
Note if it works on open.rocket.chat I suggest you look at your reverse proxy & websockets.

**Comment by lovekyleman** [comment]
> Note if it works on open.rocket.chat I suggest you look at your reverse proxy & websockets.

Unencrypted photos are fine.
No problems related to proxy & websockets
Because works fine on browsers.
encrypted videos and encrypted voice messages are ok on rocketchat IOS APP

Server Setup Information:

Licence type : starter
Number of users:
Server hardware: VPS
Version of Rocket.Chat Server:6.10.4
Operating System: Debian 11
Deployment Method: tar
Number of Running Instances:3
DB Replicaset Oplog:
NodeJS Version:v14.21.3
MongoDB Version:6.0.17
Client information:4.50.1.63099 (latest)

Client type: IOS APP

And open.rocket.chat's channels e2ee disabled I can't test this

**Comment by reetp** [comment]
> encrypted videos and encrypted voice messages are ok on rocketchat IOS APP

So related to E2E then.

These details are *really* important when you create an issue. Please make sure you document points such as these as it stops people wasting time.

Searching for similar issues also helps.

A quick look for E2E would have revealed this, and several related bugs. I believe these may be fixed in 6.12 via the PR mentioned there.

https://github.com/RocketChat/Rocket.Chat/issues/32963

Closing as it appears to be a duplicate.
