### ISSUE TITLE
request: search for user should include Username as well as Name

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3315]
Your Rocket.Chat version: 0.31

Hey folks,

While searching for direct messages the search field should include Username as well as the Name. Reason are (among others):

- Most users Name do not change, their username does.
- Maybe the Username (ie, first name) was taken, so the Username not part of the real name.
- A user only knows the Real name of the User,
- A user only knows the Username of the User,
- etc.

A search included both would yield results in any case.

Thanks for consideration1
_-Christian._

**Comment by marceloschmidt** [comment]
I'll close this issue in favor of #874. We need to work on that issue ASAP, as there are multiple issues referring to the same request.
