### ISSUE TITLE
Unable to Authenticate RocketChat REST API with KeyCloak JWT Token

### ISSUE THREAD

**Issue by charafsalmi** [RocketChat/Rocket.Chat#33173]
### Description:

My RocketChat (RC) instance is set, up and running, with a SSO managed by KeyCloak (KC). I can connect using KC to RC, it works perfectly. I am developing a web app widget to get the latest message. My frontend connects to KC and gets the JWT token from the same KC client as the one used by my RC instance.

What I need to do is use my KC JWT token to hit the RC REST API. I tried to pass the token but it doesn't work.

### Steps to reproduce:

```
curl -X GET https://parole.slm-lab.net/api/v1/me \
  -H "Content-type:application/json" \
  -d '{ "serviceName": "keycloak", "accessToken": "eyJhbGciOiJIUzUx---JWT","expiresIn": 200 }'
```

### Expected behavior:

Return the endpoint response as if I was using a X-auth-token and X-user-id, because, after all, I am actually connected.

### Actual behavior:

It always returns `{"status":"error","message":"You must be logged in to do this."}`, no matter what I try.

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- License Type: free
- Number of Users: a few
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: none
- NodeJS Version: 14
- MongoDB Version: 7

### Client Setup Information

- Desktop App or Browser Version: latest MS Edge
- Operating System: All of them

### Additional context

How to use a KC JWT to hit the REST API ?

```
$ curl -X GET https://parole.slm-lab.net/api/v1/login \
  -H "Content-type:application/json" \
  -d '{ "serviceName": "keycloak", "accessToken": "eyJhbGciOiJIUzUx---JWT","expiresIn": 200 }'

{"status":"error","message":"API endpoint does not exist"}
```

### Relevant logs:

None.

**Comment by reetp** [comment]
Github is for Issues in the software, not general support,.

Please ask in the appropriate forum:

https://forums.rocket.chat/

https://open.rocket.chat/channel/support

Also worth a read though all this - there is a lot there.

> "API endpoint does not exist"

https://developer.rocket.chat/docs

You can test a lot with the API explorerer

https://developer.rocket.chat/apidocs

Thanks.

**Comment by charafsalmi** [comment]
Thank you. Sorry for the mistake. You probably don't know but your answer actually helped me understand better and solve my issues.

My mistake were :
- I was not using the right JWT (there are a few)
- I didn't define an openid scope in KC. It's just about creating a blank scope, calling it "openid" and adding it to the client.

For other people finding this topic, I share a shell script here that helped me a lot to debug.

```
#!/bin/bash

USERNAME=""
PASSWORD=""
REALM="set-my-realm"
CLIENT_ID="set-my-client-id"
KC_SERVER="https://set-my-kc.domain.com"
RC_SERVER="https://set-my-rc.domain.com"
GRANT_TYPE="password"

read -p "Enter username: " USERNAME
read -sp "Enter password: " PASSWORD
echo ""

TOKEN_RESPONSE=$(curl -s -X POST "$KC_SERVER/realms/$REALM/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=$USERNAME" \
  -d "password=$PASSWORD" \
  -d "grant_type=$GRANT_TYPE" \
  -d "client_id=$CLIENT_ID")

ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r .access_token)

if [ "$ACCESS_TOKEN" == "null" ]; then
  echo "Failed to retrieve access token. Response: $TOKEN_RESPONSE"
  exit 1
fi

echo "Access token retrieved successfully."

USERINFO_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET "$KC_SERVER/realms/$REALM/protocol/openid-connect/userinfo" \
  -H "Authorization: Bearer $ACCESS_TOKEN")

echo "HTTP response code for userinfo request: $USERINFO_RESPONSE"

echo "ACCESS_TOKEN:"
echo $ACCESS_TOKEN

echo "Calling RocketChat service with access token..."
curl -X POST "$RC_SERVER/api/v1/login" \
  -H "Content-type:application/json" \
  -d '{ "serviceName": "'$REALM'", "accessToken": "'$ACCESS_TOKEN'", "expiresIn": 200 }'
```
