### ISSUE TITLE
run on android device failed!

### ISSUE THREAD

**Issue by YY030913** [RocketChat/Rocket.Chat#3318]
Your Rocket.Chat version: (0.31.0)
meteor 1.3.2
android 5.1

when start is a blank page

it's not set Meteor.settings, i got it

but it still can't load css [style failed picture](http://7fvja6.com1.z0.glb.clouddn.com/S60521-131256.jpg)

anyone know how to set the meteor.settings?

**Comment by YY030913** [comment]
it's not set Meteor.settings, i got it

**Comment by YY030913** [comment]
but when i run my server on --mobile-server http://192.168.1.2:3000，the css load failed
`I20160521-00:55:27.697(8)? I/chromium(10049): [INFO:library_loader_hooks.cc(108)] Chromium logging enabled: level = 0, default verbosity = 0
I20160521-00:55:27.891(8)? W/chromium(10049): [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
I20160521-00:55:27.891(8)? I/chromium(10049): [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=50 off=1382828 len=3242
I20160521-00:55:27.892(8)? I/chromium(10049): [INFO:aw_browser_main_parts.cc(76)] Loading webviewchromium.pak from, fd:51 off:239276 len:1143506
I20160521-00:55:27.995(8)? W/chromium(10049): [WARNING:data_reduction_proxy_settings.cc(328)] SPDY proxy OFF at startup
I20160521-00:55:28.042(8)? W/chromium(10049): [WARNING:password_handler.cc(26)] create-->contents = 0xf4d2ee00, delegate = 0xf4ff9e80
I20160521-00:55:28.043(8)? W/chromium(10049): [WARNING:password_handler.cc(34)] attaching to web_contents 
I20160521-00:55:30.832(8) (android:http://meteor.local/:0) XMLHttpRequest cannot load http://localhost:3000/_timesync. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://meteor.local' is therefore not allowed access. The response had HTTP status code 404.
I20160521-00:55:30.837(8) (android:http://meteor.local/plugins/cordova-plugin-console/www/console-via-logger.js:173) Error syncing to server time: 
I20160521-00:55:30.844(8) (android:http://meteor.local/plugins/cordova-plugin-console/www/console-via-logger.js:173) deviceready has not fired after 5 seconds.
I20160521-00:55:30.845(8) (android:http://meteor.local/plugins/cordova-plugin-console/www/console-via-logger.js:173) Channel not fired: onDOMContentLoaded
I20160521-00:55:33.258(8) (android:http://meteor.local/home:0) XMLHttpRequest cannot load http://localhost:3000/_timesync. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://meteor.local' is therefore not allowed access. The response had HTTP status code 404.
I20160521-00:55:33.261(8)? { [Error: Unknown asset: moment-locales/zh.js] stack: [Getter] }
`

**Comment by YY030913** [comment]
Site URL: http://192.168.1.2:3000/
but on android the css haven't loaded
`I20160521-02:57:14.863(8) (android:http://meteor.local/plugins/cordova-plugin-console/www/console-via-logger.js:173) deviceready has not fired after 5 seconds.
I20160521-02:57:15.106(8) (android:http://meteor.local/plugins/cordova-plugin-console/www/console-via-logger.js:173) Channel not fired: onDOMContentLoaded
I20160521-02:57:17.536(8)? W/chromium(16172): [WARNING:password_handler.cc(201)] OnPasswordFormsRendered called
I20160521-02:57:17.537(8)? W/chromium(16172): [WARNING:aw_password_handler_delegate_impl.cc(206)] IsSavePasswordEnabled ret is 
I20160521-02:57:17.537(8)? W/chromium(16172): [WARNING:password_handler.cc(206)] OnPasswordFormsRendered can_save = 0
I20160521-02:57:17.546(8)? { [Error: Unknown asset: moment-locales/zh.js] stack: [Getter] }
I20160521-02:57:18.137(8)? W/chromium(16172): [WARNING:password_handler.cc(160)] OnPasswordFormsParsed called
I20160521-02:57:18.138(8)? W/chromium(16172): [WARNING:aw_password_handler_delegate_impl.cc(206)] IsSavePasswordEnabled ret is 
I20160521-02:57:18.139(8)? W/chromium(16172): [WARNING:password_handler.cc(174)] requesting data16.. <email>, <>, <>, <
I20160521-02:57:18.139(8)? W/chromium(16172): [WARNING:password_handler.cc(182)] requesting data.. <http://meteor.local/>, <>, <http://meteor.local/home>, <http://meteor.local/home
I20160521-02:57:18.139(8)? W/chromium(16172): [WARNING:aw_password_handler_delegate_impl.cc(185)] GetPasswordRequest called!!
I20160521-02:58:45.711(8)? { [Error: Unknown asset: moment-locales/zh.js] stack: [Getter] }

`

**Comment by YY030913** [comment]
[style failed picture](http://7fvja6.com1.z0.glb.clouddn.com/S60521-131256.jpg)

**Comment by marceloschmidt** [comment]
How are you building your meteor app?

**Comment by geekgonecrazy** [comment]
Please check out our Cordova repo: https://github.com/rocketchat/Rocket.Chat.Cordova
