### ISSUE TITLE
Dropdown does not close upon clicking arrow again

### ISSUE THREAD

**Issue by abirc8010** [RocketChat/Rocket.Chat#33184]
### Description:

The Don't ask me again list dropdown in the 'Global' preferences section does not close when clicking the dropdown arrow again.

### Steps to reproduce:

1. Go to Account
2. Navigate to the Preferences.
3. Open the 'Global' section in the preferences.
4. Click on the `Don't ask me again list` dropdown to open it.
5. Click on the dropdown arrow again to attempt to close it.

### Expected behavior:

The dropdown should close when clicking the dropdown arrow again.

### Actual behavior:

[Screencast from 2024-08-29 22-52-39.webm](https://github.com/user-attachments/assets/47c5dcb1-e258-4e31-96ad-46cbf2dd649c)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.12.0
- License Type: Community
- Number of Users: n/a
- Operating System: Ubuntu 24.04 LTS
- Deployment Method: n/a
- Number of Running Instances: n/a
- DB Replicaset Oplog: n/a
- NodeJS Version:  14.21.4
- MongoDB Version: 7.0.5 

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by sachan13harshit** [comment]
@abirc8010 can you please assign this issue to me

**Comment by abirc8010** [comment]
@sachan13harshit  Sorry, I’m unable to assign issues.

**Comment by Barrylimarti** [comment]
This looks like an issue with the fuselage's multi select component, and I think fuselage's maintainer are planning to replace these components entirely as mentioned in this [pull request](https://github.com/RocketChat/fuselage/pull/1282).

**Comment by abirc8010** [comment]
@Barrylimarti Thanks for the info.

**Comment by reetp** [comment]
> @sachan13harshit Sorry, I’m unable to assign issues.

No one assigns issues. It doesn't work that way here.

**Comment by reetp** [comment]
> This looks like an issue with the fuselage's multi select component, and I think fuselage's maintainer are planning to replace these components entirely as mentioned in this [pull request](https://github.com/RocketChat/fuselage/pull/1282).

I think you are probably right so this will be a won't fix I'm afraid.
