### ISSUE TITLE
Reaction bubble empty (renders blank)

### ISSUE THREAD

**Issue by jw4949** [RocketChat/Rocket.Chat#33195]
### Description:

Reaction bubble renders empty on Desktop and Browser

### Steps to reproduce:

1. React to e message
2. Reaction bubble (when hovering over reaction) renders blank

### Expected behavior:

Reaction bubble should display the users, that reacted with that specific emoji

### Actual behavior:

![Screenshot 2024-09-02 at 10 38 20](https://github.com/user-attachments/assets/3c2151c2-b132-48d1-8a7f-55f7862e8371)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.11.1
- License Type: Starter
- Number of Users: 10
- Operating System: Mac, Docker Desktop
- Deployment Method: Docker compose
- Number of Running Instances: 1
- DB Replicaset Oplog: oplog disabled
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.24 / wiredTiger (oplog Disabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop app and browser
- Operating System: Mac os

### Additional context
When clicking the _Reactions_ submenu, the reactions show correctly.
![Screenshot 2024-09-02 at 10 38 28](https://github.com/user-attachments/assets/b558f882-d0eb-4629-a6cc-ec2c98664ceb)

**Comment by reetp** [comment]
Can you check on a test vm of 6.12.rc2 please or https://open.rocket.chat

Thanks.

**Comment by jw4949** [comment]
> Can you check on a test vm of 6.12.rc2 please or https://open.rocket.chat

I registered on https://open.rocket.chat and it seems to work. I suspect, that my installation is broken, and a fresh install would fix it 😅

**Comment by abirc8010** [comment]
> Test on 6.12 when released.
 I think this issue is not present in 6.12. I attempted to reproduce it but it worked fine.

**Comment by reetp** [comment]
And closing.
