### ISSUE TITLE
First opening the desktop app, showing 'Electron' in the title bar

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3319]
Your Rocket.Chat version: Version 1.3.1

When the app first opens on my PC it shows this:
![image](https://cloud.githubusercontent.com/assets/10524529/15439060/2e47055a-1e9d-11e6-89c0-8c026b6fd8b9.png)

**Comment by gdelavald** [comment]
This was fixed in previous versions. Thanks!
