### ISSUE TITLE
Rocketchat cpu spikes on startup

### ISSUE THREAD

**Issue by liel2610** [RocketChat/Rocket.Chat#33208]
Hello,
I work in a company that uses a relatively old version of rocketchat, we are currently running rocket on a large number of pods (we have 6000 active users on average).
We have one issue that has been with us for a long time - every time we rollout a pod, or start a new one, his cpu jumps to the 80 90 percent area, and with it the other pods as well.
We have noticed that every startup of a pod there is a heavy query called on the `permissions` collection, we assume that the cpu jump is related to this, and because the pods listen to each other, the cpu of the other pods also jumps together with the new pod.
We would love to know if this is a common problem? Has anyone ever experienced it, and would appreciate guidance on how we can solve the problem or a deeper understanding of it. Thank you!

**Comment by reetp** [comment]
> uses a relatively old version of rocketchat,

Sorry but you need to upgrade. No one will help you with your version.

https://docs.rocket.chat/v1/docs/en/support-prerequisites

https://docs.rocket.chat/docs/version-durability

For general support please use the appropriate forum

https://open.rocket.chat/channel/support

https://forums.rocket.chat

Thanks.
