### ISSUE TITLE
Read receipts signs are not shown in 4.0.2 RC

### ISSUE THREAD

**Issue by momentics** [RocketChat/Rocket.Chat#33204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Operating System Version

Windows 10

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

4.0.2

### Rocket.Chat Server Version

6.9.3

### Describe the bug

Read receipts signs are not shown on 4.0.2 client and 6.9.3 server. 4.0.0 with the same server does not have this issue.

### How to Reproduce

In this scenario RC 4.0.2 had been installed over version 4.0.0 successfully. To see issue please check receipts marker. Marker does not exist.

### Describe your Expected behavior

The expected behaviour includes the same receipt marker right as 4.0.0

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by reetp** [comment]
Please fill in the server details from the bug template or use this guide.

Deployment type eg snap, licence type, number of users are particularly important.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#information-that-support-or-devs-will-require


Can you test on latest 6.11.2 or 6.12.x please?

**Comment by reetp** [comment]
Just installed 4.0.2 on my Macbook as I have no Windows and on 6.11.1 read receipts work fine.

Please fill in the server details I requested earlier.

**Comment by momentics** [comment]
John, i just reverted the 4.0.2 RC client install to 4.0.0, and see no read receipts! Seems there are some kind of different issue. 
Suprisly. but on other PCs where 4.0.0 installed and never 4.0.2 been installed, I can see read reciepts!

Meantime I'll try to use >3.9 server. In all cases it used to be Docker image wirh the particular version with Starter license. Yes, it uses Linux internally, but this is calibrated build for docker and has just AD integration.

**Comment by reetp** [comment]
Try clearing the client cache. It can get 'stuck'.

**Comment by momentics** [comment]
Yep, I did it with the all available clearing menu items with no luck.

However I just installed registry.rocket.chat/rocketchat/rocket.chat:6.11.2 and there is no issue with 4.0.2 nor 4.0.0 client versions and can see reciepts. Whola!

I guess we can close the issue, but seems we where unable to determine the issue. Possibly cache clearing does not work complitelly. And new server install cleared the cache.

**Comment by reetp** [comment]
> However I just installed registry.rocket.chat/rocketchat/rocket.chat:6.11.2 and there is no issue with 4.0.2 nor 4.0.0 client versions and can see reciepts. Whola!

Cool!

> And new server install cleared the cache.

Nope. The cache is in the client. And no, as far as I'm aware, there's way to force them all to clear - that's been asked before!
