### ISSUE TITLE
After update to Version 6.12 - Message: “Start date cannot be later than expire date

### ISSUE THREAD

**Issue by thokich** [RocketChat/Rocket.Chat#33222]
Hello,
after update Server from 6.11.1 → 6.11.2 → 6.12 in docker enviroment
I become when i start the container in 6.12 this message in the log

In version 6.11.1 i do not become this messages.

Description
024-09-06T07:47:52.155Z 50 pid=1 hostname=1234567890 name=System msg=Error during workspace sync function=announcementSync

err={“type”:“Error”,“message”:“Start date cannot be later than expire date”,“stack”:"Error: Start date cannot be later than expire date\n

at BannersRaw.createOrUpdate (server/models/raw/Banners.ts:63:10)\n

at server/services/banner/service.ts:35:17\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n

=> awaited here:\n

at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n

at app/cloud/server/functions/syncWorkspace/handleCommsSync.ts:64:2\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n

=> awaited here:\n

at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n

at app/cloud/server/functions/syncWorkspace/announcementSync.ts:101:4\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}

2024-09-06T07:47:52.156Z 50 pid=1 hostname=1234567890 name=System msg=Error during workspace sync

err={“type”:“Error”,“message”:“Start date cannot be later than expire date”,“stack”:"Error: Start date cannot be later than expire date\n

at BannersRaw.createOrUpdate (server/models/raw/Banners.ts:63:10)\n

at server/services/banner/service.ts:35:17\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n

=> awaited here:\n

at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n

at app/cloud/server/functions/syncWorkspace/handleCommsSync.ts:64:2\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n

=> awaited here:\n

at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n

at app/cloud/server/functions/syncWorkspace/announcementSync.ts:101:4\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n

=> awaited here:\n

at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n

at app/cloud/server/functions/syncWorkspace/index.ts:16:3\n

at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}

Server Setup Information
±--------------------------------------------------------+
| SERVER RUNNING |
±--------------------------------------------------------+
| |
| Rocket.Chat Version: 6.12.0 |
| NodeJS Version: 14.21.3 - x64 |
| MongoDB Version: 7.0.7 |
| MongoDB Engine: wiredTiger |
| Platform: linux |
| Process Port: 3000 |
| Site URL: https://rocketchat.germany.de/ |
| ReplicaSet OpLog: Enabled |
| Commit Hash: ecff0a61cc |
| Commit Branch: HEAD |
| |
±--------------------------------------------------------+

When i Push the Button “sync license update” then i become the same message.

**Comment by thokich** [comment]
I think the problem comes from the same area as my last problem. There was a fix for it #32610.

**Comment by reetp** [comment]
I can confirm that this started to occur in 6.11.2

**Comment by scuciatto** [comment]
Hey, @thokich this should be fixed now. Can you check, please?

**Comment by thokich** [comment]
Hey, @scuciatto it looks good. When i Push now the Button “sync license update” then the error message in log is disappeared. Good job thanks.

**Comment by thokich** [comment]
The error message in log is disappeared.
