### ISSUE TITLE
Outgoing Webhook Integration Room Undefined

### ISSUE THREAD

**Issue by wagesj45** [RocketChat/Rocket.Chat#33228]
### Description:

After a Snap installation version update, the established Outgoing Webhook integration fails. The logs suggest that it thinks the `room` object is `undefined`. The script section of the integration fails to execute.

### Steps to reproduce:

1. Create an Outgoing Webhook integration
2. Set the event trigger to `Message Sent`
3. Set the channel to `#channel` (replace with a real channel)
4. Set the trigger words to `!help,!etc` (replace with comma delimited words that are prefixed with `!`)
5. Set the URLs to `http://dev.null`
6. Set the "Post as" value to `rocket.cat`
7. Set Alias to `any-alias`
8. Set Emoji to `:any-emoji:`
9. Set "Script Enabled" to `true`
10. Create a script per the example [in the documentation](https://docs.rocket.chat/docs/integrations)

### Expected behavior:

The script executes when one of the trigger words is typed.

### Actual behavior:

The script does not execute when one of the trigger words is typed.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.12.0
- License Type: Community
- Number of Users: 46
- Operating System: Debian 11 (bullseye)
- Deployment Method: snap
- Number of Running Instances: 1

### Additional context

This integration previously worked. Nothing else in the integration process was changed. I will attach the entire log set resulting from the message that *should* trigger the integration and script. Below is what seems to be the most relevant entries. All logs have been modified to remove instance/user specific data.

[log.txt](https://github.com/user-attachments/files/16915267/log.txt)

### Relevant logs:
```
2024-09-07T01:41:38-05:00 rocketchat-server.rocketchat-server[813]:
{
  "level": 20,
  "time": "2024-09-07T06:41:38.540Z",
  "pid": 813,
  "hostname": "[hostname]",
  "name": "Integrations",
  "section": "Outgoing WebHook",
  "msg": "Starting search for triggers for the room: undefined"
}
2024-09-07T01:41:38-05:00 rocketchat-server.rocketchat-server[813]:
{
  "level": 20,
  "time": "2024-09-07T06:41:38.540Z",
  "pid": 813,
  "hostname": "[hostname]",
  "name": "Integrations",
  "section": "Outgoing WebHook",
  "msg": "Found 0 to iterate over and see if the match the event."
}
```

**Comment by reetp** [comment]
Please have a search before opening a  new issue.

Closing as a duplicate:

https://github.com/RocketChat/Rocket.Chat/issues/33219

**Comment by wagesj45** [comment]
I'm sorry, @reetp , but how is this related? The issue you linked is related to a missing `channel_id`. I actually *did* do a search, found this issue, and it seems unrelated to an undefined trigger.

My script does not utilize the `channel_id`, or indeed any of the data passed to the script beyond the message text. In fact, the `prepare_outgoing_request()` function is never getting executed.

If you could clarify how the two issues are related, I'd be very appreciative.

**Comment by reetp** [comment]
I think this is the related bit.

> the established Outgoing Webhook integration fails.

And 

> thinks the room object is undefined

Room/channel/whatever likely.

Thiny they are likely related.

Also wondering also how your snap is on 6.12  as they normally don't relesse until the 15th or so?

**Comment by wagesj45** [comment]
> Also wondering also how your snap is on 6.12 as they normally don't relesse until the 15th or so?

Good question. My tracking channel is set to `6.x/stable` and it updated sometime within the last 24 hours.

**Comment by reetp** [comment]
Thanks for the info.

Checking that too. But it's the weekend. Might take a while.
