### ISSUE TITLE
Rocket Chat Opens Up, After Login, to Random Rooms/Channels -- Some that No Longer Exist

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat#33236]
### Description:

When our employees login to Rocket Chat, they are often dumped into random rooms/channels, rather than to /home.  Sometimes, they are dumped into channels/rooms that no longer exist, other times they are dumped into channels/rooms that they are not members of.  However, this seems to be random and _some_ of the time they are placed in /home.

### Steps to reproduce:

1. Honestly, I'm not sure how to reproduce this, but:
2. login to Rocket Chat
3. Find yourself in a random room.

### Expected behavior:

After logging in, you should always go to /home.

### Actual behavior:

![image](https://github.com/user-attachments/assets/27faa405-f9cf-492f-b923-604b7badefcd)
![image](https://github.com/user-attachments/assets/5d193ab4-9ce3-4d33-9e11-c52d80573127)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.5
- License Type: Enterprise
- Number of Users: 155
- Operating System: Linux
- Deployment Method: Rocket Chat provided build images
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.17

### Client Setup Information

- Desktop App or Browser Version: happens on all of the above
- Operating System: Windows, Mac, Linux

**Comment by reetp** [comment]
Generic first channel on login is set here:

admin/settings/General
First Channel After Login

Add new user by default to Room:
Rooms, Select room, Enable/Disable Default channel 

> License Type: Enterprise
Map LDAP groups and Teams to channels.

I would imagine that someone has deleted a room without clearing out users and there is still a mapping there somewhere.

As an Enterprise customer you should contact support and they can help you. That is what you pay for!

**Comment by reetp** [comment]
Note - this is a bug tracker and not really a support forum. You have paid support and should use them.

> Can we set that to /home

Not sure - you can ask support....  personally I set up a generic room that everyone joins and point them at that rather than home.

If you remove the default room I guess it should go to home but you may need to hit the 'Restart Server' for it to take effect. button.

> As for the ldap stuff, we aren't using ldap. We are using SAML. 

Same difference generally.

**Comment by msudipta888** [comment]
can i work on this issue

**Comment by reetp** [comment]
> can i work on this issue

First it needs to be determined if there is actually an issue and so far we don't even know that. 

As they said:

> Honestly, I'm not sure how to reproduce this

It needs to be reproducible so we can try and discover what is going on - you can't fix unknown problems.

The OP needs to try an discover what triggers this.

Secondly if there is an issue then really the OP should contact his paid for support channel where he will get a much faster response - he should do that anyway as paid support is a fast track for help and fixing issues.

As a result I wouldn't waste time right now unless either the OP can reproduce it, or you can.

**Comment by mddvul22** [comment]
FYI, a paid support ticket has been open for several days.

**Comment by reetp** [comment]
> FYI, a paid support ticket has been open for several days.

Ok. Follow it up there. Chase as necessary.

Note there is zero guarantee of assistance here.

As per my comments above if we can't repeat it there's nothing we can do to help here.

I would spend some time trying to get a repeatble occurrence.

**Comment by Deelight-fr** [comment]
> When our employees login to Rocket Chat, they are often dumped into random rooms/channels, rather than to /home. Sometimes, they are dumped into channels/rooms that no longer exist, other times they are dumped into channels/rooms that they are not members of. However, this seems to be random and _some_ of the time they are placed in /home.

@mddvul22 Are you using SAML authentication?

**Comment by mddvul22** [comment]
> @mddvul22 Are you using SAML authentication?

Yes, we are.

**Comment by Deelight-fr** [comment]
We may have the same problem here, with some people joining private rooms were they have not been invited, just after login. We have a Satosa proxy to enable Shibboleth authentication because Rocket Chat does not support IDP discovery. Maybe this is linked, but it's very hard to reproduce.

**Comment by mddvul22** [comment]
I have a ticket open with paid support on this issue.  They kind of believe it is related to SAML auth, also.
