### ISSUE TITLE
Send message to new user bug

### ISSUE THREAD

**Issue by MichaelSavin** [RocketChat/Rocket.Chat#3324]
Your Rocket.Chat version: 31
If a new user was added in RoketChat group, but at the same time, as long as this person does not have any message, it does not appear among the participants of the group. I can not send him any message.

**Comment by MartinSchoeler** [comment]
@MichaelSavin Couldn’t reproduce on latest version, probably the issue has been fixed. If not, please reopen this. Thanks!
