### ISSUE TITLE
Rocket.chat startup exceeds Heroku Boot Timeout

### ISSUE THREAD

**Issue by mbidewell** [RocketChat/Rocket.Chat#3325]
I am working with rocket.chat on Heroku.  Often when I attempt to startup the app, rocket.chat exceeds the 60 second boot timeout.  Can this be worked around?

**Comment by AJ-Acevedo** [comment]
I found an interesting article on using a proxy as a workaround for Ruby on Rails.

_The basic idea is to have a proxy bind to the port immediately and then buffer requests until the backend came up_

[Beat Heroku's 60 Seconds Application Boot Timeout with a Proxy](http://artsy.github.io/blog/2012/12/13/beat-heroku-60-seconds-application-boot-timeout-with-a-proxy/)

**Comment by Sing-Li** [comment]
@mbidewell   on the cf client (modified by heroku), there is a `-t` option that should extend this up to 180 seconds --- that should give you a lot more room.

BUT - on Bluemix - see #3338  ... even 3 minutes seems to be too short.

**Comment by justinr1234** [comment]
@Sing-Li I'm not sure how this would work with a nodejs project ... am I missing something?

**Comment by justinr1234** [comment]
Looks like you need to upgrade to a paid version of mongolab:  https://devcenter.heroku.com/articles/mongolab#changing-plans

**Comment by mbidewell** [comment]
So it is the mongodb performance that is this issue?

**Comment by justinr1234** [comment]
I believe so. I haven't had a single problem since I upgraded my mlab

**Comment by brynnbp** [comment]
Also having same issue. Doesn't make sense to upgrade mlab at a minimum of $18/month for this, unfortunately.

**Comment by RichardFoxworthy** [comment]
Hi @justinr1234 would you mind setting out exactly how you did the upgrade to the paid mongo. I've attempted this, but am seeing some weird behaviour now app works fine but new users cannot register, which seems very odd

**Comment by justinr1234** [comment]
I just followed the Mongo documentation that they link when get to upgrade and didn't get any issues. Mongo dumped my db and recreated my add on. Additionally, I cloned the heroku build pack from the rocket chat repo and changed the Add ons in the pack to say the paid version of month instead of free.

See here: https://github.com/justinr1234/heroku-buildpack-meteor/commit/c7b868c0c968e01413c469f2576a850fdb746ff7

**Comment by RichardFoxworthy** [comment]
I updated the DB by backing up the free tier DB and creating a new paid db from that backup using the mLabs web interface. Then copied the URI from the web interface, updated it with user/password, and pasted it into the Heroku env variable.

App works fine. But new regsitration does not work.  

I found this in my logs: 

`» 2 Jun 2016 11:08:48.423 232 <190>1 2016-06-02T01:08:48.031879+00:00 app web.1 - - Exception while invoking method 'registerUser' AuthError: Invalid login - 534-5.7.9 Application-specific password required. Learn more at at Object.Future.wait (/app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:398:15) at smtpSend (packages/email/email.js:86:1) at Object.Email.send (packages/email/email.js:185:1) at AccountsServer.Accounts.sendVerificationEmail (password_server.js:781:9)
» 2 Jun 2016 11:08:48.423 187 <190>1 2016-06-02T01:08:48.031894+00:00 app web.1 - - at [object Object].Meteor.methods.registerUser (server/methods/registerUser.coffee:20:13)
» 2 Jun 2016 11:08:48.423 176 <190>1 2016-06-02T01:08:48.031895+00:00 app web.1 - - at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
» 2 Jun 2016 11:08:48.423 154 <190>1 2016-06-02T01:08:48.031896+00:00 app web.1 - - at maybeAuditArgumentChecks (livedata_server.js:1698:12)
» 2 Jun 2016 11:08:48.423 126 <190>1 2016-06-02T01:08:48.031896+00:00 app web.1 - - at livedata_server.js:708:19
» 2 Jun 2016 11:08:48.423 177 <190>1 2016-06-02T01:08:48.031897+00:00 app web.1 - - at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
» 2 Jun 2016 11:08:48.423 126 <190>1 2016-06-02T01:08:48.031898+00:00 app web.1 - - at livedata_server.js:706:40`

**Comment by justinr1234** [comment]
I added the paid add on via the instruction from the Heroku command line and it managed all the environment variables for me. Only thing I hand edited was changing the build pack.

**Comment by RichardFoxworthy** [comment]
doh! never mind, was a separate problem caused by changing my SMTP settings. DB seems all good. Thanks for your help @justinr1234

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (406/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:28405)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1b8IVL-002CpD-Qv
	for yann.dupuy@zyapps.com; Thu, 02 Jun 2016 04:37:18 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=HpbFqcfgKxViWhKWV2eamqXymTI=; b=qrwbhH7rvX34RQYF
	0A0ix9Q0GXJFcedlY4GZyqt3nYk4HHGjgy55kO3fTstKXDvQT2vJ/c+SsotmK0du
	y926u7d7/g+maBVR5/lFMjkjaJO75IkKARxrOPjabvKbmDiJxDueWfhzjbu9HmCO
	muKwV5HfVGM/hFo+gadCfXczKvo=
Received: by filter0631p1mdw1.sendgrid.net with SMTP id filter0631p1mdw1.30071.574F9BA219
        2016-06-02 02:36:18.352046259 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id KVVXgQErQvmIF29mjvRS3Q
	for <yann.dupuy@zyapps.com>; Thu, 02 Jun 2016 02:36:18.396 +0000 (UTC)
Date: Wed, 01 Jun 2016 19:36:18 -0700

**Comment by engelgabriel** [comment]
Fixed

**Comment by justinr1234** [comment]
@engelgabriel what fixed it?
