### ISSUE TITLE
"The application GUI just crashed" - after dismissing banner

### ISSUE THREAD

**Issue by kluvi** [RocketChat/Rocket.Chat#33263]
### Description:
When admin dismisses banner with notification, that new version 6.12 is available, the app crashes:
![image](https://github.com/user-attachments/assets/14ab78d0-5c83-4e12-a096-a6bf9eb14da1)

When I remove manually in mongo the role "admin" from user, everything works. Admins, that dont dismiss this notification are not affected.

Tried to delete some items from `rocketchat_banner_dismiss`, but it didnt help.

Notifications are working correctly even when the app is crashed, mobile app also works (but not the admin panel in mobile app)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.12.0
- Number of Users: about 70
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3 - x64
- MongoDB Version: 4.4.29

### Additional context
Same problem described here: https://forums.rocket.chat/t/application-error-the-application-gui-just-crashed/20534

### Relevant logs:
browser console:
```
console.js:288 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at aX (_define_property.mjs:14:1)
```

**Comment by CotPilot** [comment]
I didn't close the banner. I just restarted the client - the same issue here.
I tried to clear the data of the desktop application. I tried logging in incognito mode in my browser. None of this changes the result - Minified React error #31 and "The application GUI just crashed".

**Comment by katiestarling** [comment]
Happening with our instance as well except none of us dismissed the banner it just randomly started happening late at night while I was answering messages and we have tried everything and even any fixes that have been mentioned in the past for this issue..we are quite confused and just upset but one odd note is an admin on MacBook is having no crashes and has been able to get in their admin panel but can't on their mobile browser or any other device and they are using the same browser that most of us admins use which is Firefox... it's been frustrating with no fix found yet! Let's hope soon cause having no access to the admin panel is just so frustrating...

**Comment by CotPilot** [comment]
This morning the interface suddenly was working. I saw a banner that a new version is available, but I didn't close it just in case. So I wrote in several chats, everything was OK for a while. Then I decided to go to the Workspace, to the admin section and it fall out again! And still the same "The application GUI just crashed" error.

**Comment by waveoffire** [comment]
i just fixed it by running command:
`/usr/bin/mongosh --eval 'use rocketchat' --eval 'db.rocketchat_banner.updateMany({active: true },{ $set: { active: false }})'`

you can add it to crontab
`*/10 * * * * /usr/bin/mongosh --eval 'use rocketchat' --eval 'db.rocketchat_banner.updateMany({active: true },{ $set: { active: false }})'`
the error is most likely caused by a message limit message, which appears every 12 hours

**Comment by CotPilot** [comment]
Aaaand... it's all back!! Wow! @waveoffire thank you very much!

**Comment by reetp** [comment]
For reference also mentioned here:

https://forums.rocket.chat/t/bug-on-admin-panel/20587

**Comment by KodoGit** [comment]
For snap users:
sudo rocketchat-server.mongo
use parties
db.rocketchat_banner.updateMany({active: true },{ $set: { active: false }})

**Comment by reetp** [comment]
FYI this has been referred to devs.

**Comment by MartinSchoeler** [comment]
This is related to https://github.com/RocketChat/Rocket.Chat/issues/31893 so I'll quote my response from there 

> Hey, just an update, I could not reproduce the issue locally, I will probably need a sample of the database entry that is causing the issue. If anyone wants to help, I believe you can force a recheck by asking for a license sync on the subscription admin page
And if you don't want to share your db entries on a public forum, feel free to dm me at https://open.rocket.chat/direct/martin.schoeler
Many thanks!

**Comment by reetp** [comment]
Thanks Martin!

If anyone has an issue contacting Martin directly drop a message in #support there and I'll sort it out.

**Comment by KodoGit** [comment]
When this error comes I have these active banners:
closeToSeatsLimit
reachedSeatsLimit
and a dozen of "Workspace members are not receiving notifications on mobile"
6.12.1 Community

I wonder why SeatsLimit banners come to Community version.

**Comment by reetp** [comment]
> I wonder why SeatsLimit banners come to Community version.

Because if yoi read enough you will see that CE code is not separate. It is the same code as the licenced version with some parts disabled.

There have long been plans to release a CE with this sort of stuff removed but it is highly complex with some parts deeply embedded, and it would need to be maintained somehow.

Of course Rocket is open source so you can always fork it and remove whatever you want yourself if you don't like it.

**Comment by KodoGit** [comment]
May be RC generates too much banners?

MongoDB shell version v5.0.15
connecting to: mongodb://127.0.0.1:27017/parties?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("23892437-7961-4f1e-b39a-a4206cf897cb") }
MongoDB server version: 5.0.15
{ "acknowledged" : true, **"matchedCount" : 441, "modifiedCount" : 441** }

**Comment by abhinavk-rw** [comment]
Are we going to have a fix from the developers for :- 

Application Error
The application GUI just crashed.

**Comment by reetp** [comment]
> Are we going to have a fix from the developers for :- 

Please read what the dev said.

You can't fix what you can't repeat. It's why full debugging information is important, and you have provided nothing about your own instance.

https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-2361928585

**Comment by xi67** [comment]
Same here, have to execute this every morning to access rocketchat : 
docker exec data_mongo_1 /usr/bin/mongosh --eval 'use rocketchat' --eval 'db.rocketchat_banner.updateMany({active: true },{ $set: { active: false }})'

**Comment by reetp** [comment]
> Same here

That is absolutely no use.

Please read the above comments carefully including my previous one. See what the developer has said.

He needs data, not "metoo".

**Comment by MakselPr** [comment]
> Thanks Martin!
> 
> If anyone has an issue contacting Martin directly drop a message in #support there and I'll sort it out.

To solve the issue so that the developer can replicate it locally, they need either my entire database or specific tables. ?

**Comment by vexsx** [comment]
it has happened for me to for some admins , like others i did pull out role admin then doing my work , after a while i pulled out about 2 3 admins role from my users then push role admin to myself  again since that day no pull or push was needed .
i did push role admin to another user of mine , it worked for him too .

i should mention i did remove all my banner of my account and that admin way before i do pull or push

**Comment by reetp** [comment]
> it has happened for me and for some 

Already said "#MeToo" helps no one, particularly you.

It needs absolute specifics.

Be specific as per information you have been given, and the devs comments above linked below.

Read these, fully.

https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-2370889212

https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-2361928585

**Comment by KodoGit** [comment]
> Read these, fully.
That issue is closed.
That dev does not reply.
Nobody can understand what that dev needed.

**Comment by reetp** [comment]
> > Read these, fully.
> 
> That issue is closed.

This is, as a duplicate.

The correct bug is as linked above.

> That dev does not reply.

He had been on vacation. He also has a mountain of other issues to handle and priorities go to subscribed users.

That is the nature of open source.

> Nobody can understand what that dev needed.

He detailed it quite clearly.

https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-2361928585

And my comment:

https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-236199836

Please read carefully.

**Comment by waogden** [comment]
@reetp I'm not sure I understand. Martin said that he needs sample of the db entry that is causing the problem. Does he need the entire table? Does he need something more specific than that?

**Comment by reetp** [comment]
> @reetp I'm not sure I understand. Martin said that he needs sample of the db entry that is causing the problem. Does he need the entire table? Does he need something more specific than that?

Please don't @ me. I read all the posts.

I suggest you contact him and see what he wants? No point in asking me.

At least the banners tables I guess but possibly a whole db.

**Comment by scrivna** [comment]
@MartinSchoeler I experienced this same issue. I had two banners active in the rocketchat_banner table, copied for you below, when set as active:false it resolved the issue.


`{
  "_id": "c9f1f8eb-663a-4443-ad48-2c3ce6b4aba2",
  "active": true,
  "platform": [
    "web"
  ],
  "createdAt": {
    "$date": "2022-04-05T12:00:08.368Z"
  },
  "expireAt": {
    "$date": "2022-04-26T12:00:07.187Z"
  },
  "startAt": {
    "$date": "2022-04-05T12:00:08.368Z"
  },
  "roles": [
    "admin"
  ],
  "createdBy": {
    "_id": "rocket.cat",
    "username": "rocket.cat"
  },
  "_updatedAt": {
    "$date": "2022-04-05T12:00:08.371Z"
  },
  "view": {
    "viewId": "c9f1f8eb-663a-4443-ad48-2c3ce6b4aba2",
    "appId": "banner-core",
    "blocks": [
      {
        "type": "section",
        "blockId": "attention",
        "text": {
          "type": "plain_text",
          "text": "NPS survey is scheduled to run at 2022-04-26 for all users. It's possible to turn off the survey on 'Admin > General > NPS'",
          "emoji": false
        }
      }
    ]
  }
}`

`{
  "_id": "67117d75a495ea0a131a2a54",
  "_updatedAt": {
    "$date": "2024-10-18T21:52:17.653Z"
  },
  "active": true,
  "createdAt": {
    "$date": "2024-10-17T21:11:17.475Z"
  },
  "createdBy": "cloud",
  "expireAt": {
    "$date": "2024-10-19T21:11:17.475Z"
  },
  "platform": [
    "web",
    "mobile"
  ],
  "roles": [
    "admin"
  ],
  "selector": {
    "roles": [
      "admin"
    ]
  },
  "startAt": {
    "$date": "2024-10-17T21:11:17.475Z"
  },
  "surface": "banner",
  "view": {
    "variant": "warning",
    "viewId": "67117d75a495ea0a131a2a54",
    "appId": "cloud-announcements-core",
    "title": {},
    "blocks": [
      {
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": "**Omnichannel social channels, desktop and mobile apps will stop working in 15 days.**"
        }
      },
      {
        "type": "section",
        "text": {
          "type": "plain_text",
          "text": "Please update to supported workspace version. Learn more"
        }
      },
      {
        "type": "section",
        "text": {
          "type": "mrkdwn",
          "text": "[more information](https://go.rocket.chat/i/supported-versions)"
        }
      }
    ]
  }
}`

**Comment by ila-embsys** [comment]
Have experienced the same issue. Dismissing the banner is the cause to "Application Error".

After a little investigation, I think it is the problem on the frontend side, since the mobile app is not affected but only web version. Moreover, just enough to remove the banner's HTML node by browser's inspector to trigger "Application Error". Looks like some rendering engine can not redraw UI elements after the banner's element disappears.

**Comment by reetp** [comment]
**Please, please, please** do yourself a favour and read ALL the comments AND links here or you will be **ignored**.

I have spelled the same thing out several times and it is getting boring saying the same thing over and over again.

No `MeToo` comments. Be professional and specific.

Everyone is probably different. Help the devs and fill in the server details.

Next contact Martin on open.rocket in the `#support` channel.

He will need a complete database dump.

Unless you do that **you will be ignored**.

Thanks.

**Comment by MartinSchoeler** [comment]
> @MartinSchoeler I experienced this same issue. I had two banners active in the rocketchat_banner table, copied for you below, when set as active:false it resolved the issue.
> 
> `{ "_id": "c9f1f8eb-663a-4443-ad48-2c3ce6b4aba2", "active": true, "platform": [ "web" ], "createdAt": { "$date": "2022-04-05T12:00:08.368Z" }, "expireAt": { "$date": "2022-04-26T12:00:07.187Z" }, "startAt": { "$date": "2022-04-05T12:00:08.368Z" }, "roles": [ "admin" ], "createdBy": { "_id": "rocket.cat", "username": "rocket.cat" }, "_updatedAt": { "$date": "2022-04-05T12:00:08.371Z" }, "view": { "viewId": "c9f1f8eb-663a-4443-ad48-2c3ce6b4aba2", "appId": "banner-core", "blocks": [ { "type": "section", "blockId": "attention", "text": { "type": "plain_text", "text": "NPS survey is scheduled to run at 2022-04-26 for all users. It's possible to turn off the survey on 'Admin > General > NPS'", "emoji": false } } ] } }`
> 
> `{ "_id": "67117d75a495ea0a131a2a54", "_updatedAt": { "$date": "2024-10-18T21:52:17.653Z" }, "active": true, "createdAt": { "$date": "2024-10-17T21:11:17.475Z" }, "createdBy": "cloud", "expireAt": { "$date": "2024-10-19T21:11:17.475Z" }, "platform": [ "web", "mobile" ], "roles": [ "admin" ], "selector": { "roles": [ "admin" ] }, "startAt": { "$date": "2024-10-17T21:11:17.475Z" }, "surface": "banner", "view": { "variant": "warning", "viewId": "67117d75a495ea0a131a2a54", "appId": "cloud-announcements-core", "title": {}, "blocks": [ { "type": "section", "text": { "type": "mrkdwn", "text": "**Omnichannel social channels, desktop and mobile apps will stop working in 15 days.**" } }, { "type": "section", "text": { "type": "plain_text", "text": "Please update to supported workspace version. Learn more" } }, { "type": "section", "text": { "type": "mrkdwn", "text": "[more information](https://go.rocket.chat/i/supported-versions)" } } ] } }`
> 
> FYI i don't have permissions to message you on the rocket.chat server link provided in your comment, so posting it here in the hope you see it.

Alright, I've narrowed the issue down to the ´title´ property on the second db entry, the banner component was not expecting an empty object as title and is breaking, I've opened a PR on fuselage fixing that, what everyone on this conversation can do to help is checking if there is any other property is breaking the ui (if your ui is breaking, check your entries on `rocketchat_banner` collections and see if there is any other property with an empty object or similar)

I'll check with the cloud team if we can change these payloads for a more immediate fix too

Thanks everyone for helping with debugging this issue!

**Comment by waogden** [comment]
Thanks Martin! (And John for putting up with us)

**Comment by railsmechanic** [comment]
For me, setting `active: false` does not solve the problem. I need to delete all entries of the `rocketchat_banner` collection. 🙈

**Comment by geidsonc** [comment]
the fix needs to be pushed to 6.x versions as well.

**Comment by MartinSchoeler** [comment]
Hello! Just to update everyone in this issue, we've managed to normalise the return of the banner service in our cloud infra, so once the existing banners are removed from the database, the issue should not happen again (even in 6.x versions), if **after removing the entries from rocketchat_banner colletions** you're still having this issue, let me know so we can investigate it again. You can ping me in the [support channel in open.rocket.chat](https://open.rocket.chat/channel/support) with the ´@martin.schoeler´ handle.

Thanks!

**Comment by HelloJack0** [comment]
<img width="560" height="536" alt="Image" src="https://github.com/user-attachments/assets/8d4a8afc-af5b-41d4-a9a9-c780fde231d7" />

<img width="1699" height="620" alt="Image" src="https://github.com/user-attachments/assets/70df13ba-badb-4e09-85ac-aa2ca6a41178" />

<img width="434" height="89" alt="Image" src="https://github.com/user-attachments/assets/0aa4eeea-fc04-4e8d-9cb7-ff8bbf42b0f9" />

8.0.1 still have , setting active: false does not solve the problem
