### ISSUE TITLE
Application missing on F-Droid

### ISSUE THREAD

**Issue by pankaj-bind** [RocketChat/Rocket.Chat#33282]
Application is missing on F-Droid but its link given in Readme file.
![{20FEC8AE-DFE6-4A94-AD86-477AE1BDCA27}](https://github.com/user-attachments/assets/b5ff099f-65f3-4522-9ed6-97c4d119372b)

**Comment by reetp** [comment]
Which Readme file please?

Paste a link.

**Comment by pankaj-bind** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/README.md
In mobile app section, you have given F-Droid link but it is not working

**Comment by reetp** [comment]
Thanks.

They'll get it fixed though I am not sure whether it will appear on F-Droid.

**Comment by reetp** [comment]
So I asked the dev and he said roughly this:

> We tried submitting a long time ago and maintainers were not helpful.

> Eventually we gave up and they did everything on their own after users requested us on the store.

> We don't know whats happened there currently, but they build it and it's up to them to update.

**Comment by marek22k** [comment]
Is there any news? If I'm not mistaken, the app was in F-Droid for a long time? Maybe it could be included in IzzyOnDroid as an interim solution?

**Comment by reetp** [comment]
Please read my previous comment, and the comments of the Rocket.Chat app dev.

You need to speak to F-Droid and ask them.

**Comment by marek22k** [comment]
Do you have a link to the F-Droid ticket? As far as I know, they don't remove an app from their store for no reason (at least I've never heard of it).

**Comment by reetp** [comment]
Please, read what the dev said above.

> but they build it and it's up to them to update

There is not a ticket that Rocket.Chat has open I am aware of.

You need to contact them and ask them yourself.

https://f-droid.org/issues/

https://gitlab.com/fdroid/fdroiddata/-/issues/?sort=created_date&state=all&search=rocket&first_page_size=20

From reading it would appear that they likely have issues with the EE parts of Rocket.Chat but that is a conversation you need to have with their devs.

This is really an F-Droid issue and not Rocket.Chat so closing.

If their devs want to come back and discuss anything then they can open an issue in the React Native repo where this belongs. The Rocket dev will happily talk to them.

https://github.com/RocketChat/Rocket.Chat.ReactNative
