### ISSUE TITLE
Webhook replacement avatar not used

### ISSUE THREAD

**Issue by peterdalydickson** [RocketChat/Rocket.Chat#3329]
Your Rocket.Chat version: 0.31.0

I setup a Gitlab webhook, as per https://rocket.chat/docs/administrator-guides/integrations/gitlab-md/, and set an Avatar URL.

The override avatar displays in the example message, but a default image is used in the messages displayed from the webhook.

A bug, or do I have to configure something else?

**Comment by graywolf336** [comment]
This has been verified to work recently, feel free to open it again if you are still having this issue provide the information you're using. :+1:

**Comment by wonkaba** [comment]
@peterdalydickson Were you able to figure this out? I am seeing the same behavior.
