### ISSUE TITLE
Unexpected behaviour in im.counters endpont API

### ISSUE THREAD

**Issue by e-o-j** [RocketChat/Rocket.Chat#33301]
### Description:

When querying the im.counters endpoint for a user that has never entered the chat, the unreads counter returns null instead of the total number of messages in the room.

### Steps to reproduce:

1. Open a direct message conversation between two users
2. Send some messages from one of the users
3. Query the im.counters endpoint with the userId of the other user of the conversation

### Expected behavior:

The unreads variable shows the same number of messages as the msgs variable.

### Actual behavior:

The unreads variable returns null

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.2
- License Type: Community
- Number of Users: 479
- Operating System: Debian 12 (bookworm)
- Deployment Method: docker
- Number of Running Instances: 1

**Comment by reetp** [comment]
> Version of Rocket.Chat Server: 6.10.2

Have you tested on latest?

Please do and let us know.

**Comment by e-o-j** [comment]
> > Version of Rocket.Chat Server: 6.10.2
> 
> Have you tested on latest?
> 
> Please do and let us know.

I have just tested in latest version (6.12.1) and the error persist:

```json
{
  joined: true,
  members: 2,
  unreads: null,
  unreadsFrom: null,
  msgs: 1,
  latest: '2024-10-07T08:28:23.875Z',
  userMentions: 0,
  success: true
} 
```

**Comment by reetp** [comment]
> I have just tested in latest version (6.12.1) and the error persist:
> 

There is 6.12.2 (you really should upgrade) and 6.13.0 and 7.0-rc

Latest literally means that. For you test on 6.13 or 7.0

**Comment by e-o-j** [comment]
I've just tested in 6.13.0 and 7.0.0-rc.6 (the latest versions a the time of writing this comment) and get the same result in both scenarios.

**Comment by e-o-j** [comment]
This is still relevant

**Comment by reetp** [comment]
> for a user that has never entered the chat

At a guess you have to have entered a chat before you can know what's in it?

**Comment by e-o-j** [comment]
But from an integrations point of view, if I as a user query the im.counters endpoint to see how many messages I have unread, getting a null from a chat that has unread messages is confusing i think

**Comment by reetp** [comment]
I'll refer it to the team but I'm not sure there'll be a rush to look at it.

**Comment by casalsgh** [comment]
Taking for internal review from engineering

**Comment by scuciatto** [comment]
We have confirmed the bug on our end. We will address the fix internally.
Thanks for reporting!
