### ISSUE TITLE
The interface is black, and it is the same after reloading

### ISSUE THREAD

**Issue by dahaiaqsw** [RocketChat/Rocket.Chat#33312]
version 3.5.3
After logging in, some computers show a black screen, and after reloading the result is the same, but on other computers it is fine.
help please!

**Comment by reetp** [comment]
Your version is unsupported.

https://docs.rocket.chat/docs/support-prerequisites

Upgradr and ask question at https://forums.rocket.chat or https://open.rocket.chat #support
