### ISSUE TITLE
METEOR_LOGIN_TOKEN Not Being Set In Cookies After Update To 0.31

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#3332]
Your Rocket.Chat version: 0.31

I just updated this morning and noticed that I kept getting logged out of my session every 20 minutes or so after inactivity. I also have to relogin on the mobile app on my iOS.

Prior to the update, there have been no issues and my sessions would persist even after putting my laptop to sleep.

I've tried refreshing my browser cache and restarting my computer but this keeps happening. Is anyone else have this issue?

**Comment by richardwlu** [comment]
This is happening on Chrome and Firefox, and to multiple users.

I increased the login expiration time to `1e+22` as an admin but I am still getting logged out every 20-30 minutes or so.

**Comment by richardwlu** [comment]
And if I refresh the page, I get logged out.

**Comment by marceloschmidt** [comment]
@richardwlu sorry to hear about that. Could you please log in to https://demo.rocket.chat and check if this happens there as well? I'm logged in there for the whole day and haven't seen this happen yet...

**Comment by richardwlu** [comment]
@marceloschmidt Thank you for your response. I've logged into demo.rocket.chat and will let you know. Just to verify, is it supposed to just look like this when logged in without any other channels?
<img width="1838" alt="screen shot 2016-05-25 at 3 51 31 pm" src="https://cloud.githubusercontent.com/assets/8405384/15555934/bdd1f864-2290-11e6-88fd-cb267de9049f.png">

**Comment by marceloschmidt** [comment]
Since you first logged in via live chat, you already have a guest user in the chat so you can't really see anything else... to view as a regular user, please open an anonymous windows or clear browser data.

**Comment by richardwlu** [comment]
@marceloschmidt It looks like my session persists on demo.rocket.chat and this issue is only happening on my own instance.

Now I wonder if it has to do with nginx, but I didn't change any configs. I did update RC without shutting down nginx but that never posed a problem before.

Any thoughts are greatly appreciated!

**Comment by richardwlu** [comment]
Is this normal?

![screen shot 2016-05-26 at 12 14 04 pm](https://cloud.githubusercontent.com/assets/8405384/15583525/cc2f4154-233b-11e6-937d-da0f1f1d2dde.png)

**Comment by richardwlu** [comment]
@marceloschmidt Looking at the cookies set in the browser I found an inconsistency between my devchat, demo.rocket.chat, and our prod instance:

- The devchat instance which doesn't kick us off has `meteor_login_token`
- The demo.rocket.chat has `meteor_login_token`
- The prod instance that is kicking us off does **not** have `meteor_login_token`

Resources -> Cookies with `meteor_login_token`
<img width="1643" alt="withmeteortoken" src="https://cloud.githubusercontent.com/assets/8405384/15584818/de0cb586-2341-11e6-965c-8393c4590237.png">

and without `meteor_login_token`
![withoutmeteortoken](https://cloud.githubusercontent.com/assets/8405384/15584822/ea355070-2341-11e6-90ad-1458212c95bc.png)

Any reason why the meteor_login_token cookie would not be set?

**Comment by richardwlu** [comment]
@engelgabriel Would you happen to have any thoughts on this?

**Comment by richardwlu** [comment]
And just noticed that in the browser's local storage the Meteor.loginTokenExpires value is set to a time in the past...which is highly likely the problem:

![screen shot 2016-05-26 at 2 52 44 pm](https://cloud.githubusercontent.com/assets/8405384/15588144/195c81c4-2352-11e6-844b-1f23958fd7d4.png)
I'm wondering where and how this is getting set, and why only in our prod instance...

**Comment by richardwlu** [comment]
I ended up deleting the old bundle and redownloading the latest and running from there. Now everything is working as usual.

Something screwed up during the update so I am not sure what it was.

**Comment by richardwlu** [comment]
@marceloschmidt Do you have any clues as to why this would happen?

**Comment by marceloschmidt** [comment]
None! Never seen this happen before! I've even looked on SO for it and couldn't find anything related to that. I'm glad it's been solved 😓

**Comment by richardwlu** [comment]
Gotcha, well thanks anyway! Hopefully someone will benefit and avoid this in the future.
