### ISSUE TITLE
Support for sound-emojis

### ISSUE THREAD

**Issue by sta-szek** [RocketChat/Rocket.Chat#3333]
It would be nice to have a sound-emoji in Rocket.Chat :) listed [here](http://www.emoji-cheat-sheet.com/) under **Campfire also supports a few sounds section**.

**Comment by bios-ben** [comment]
And I might add, a UI for custom snippets of course so not just limited to official emoji

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by Agisbert** [comment]
Yes please!
