### ISSUE TITLE
Confirmation modal when trying to leave LiveChat room shows "undefined"

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#3334]
Your Rocket.Chat version: demo instance

Below "Are you sure?":

![bildschirmfoto 2016-05-24 um 08 59 38](https://cloud.githubusercontent.com/assets/944459/15495026/e830a4ce-218d-11e6-8365-9e5ccf7d89eb.png)

**Comment by dwaynehulsman** [comment]
+1

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
