### ISSUE TITLE
Request: Setting option for Colors per User 

### ISSUE THREAD

**Issue by atau1979** [RocketChat/Rocket.Chat#3335]
Your Rocket.Chat version: 0.31

Slack has menu for setting "colors per User".

Is my sentence correct? thanks.

**Comment by lucasvanhalst** [comment]
Do you mean the theme? 
If so see #277, not possible yet

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates in a long time. If the issue still persists please open a new issue with updated details. Thanks!
