### ISSUE TITLE
scroll bar color is black on black background

### ISSUE THREAD

**Issue by ans-artal** [RocketChat/Rocket.Chat#33359]
The scroll bar can be really hard to see.

Exemple :
![scrollbar](https://github.com/RocketChat/Rocket.Chat/assets/92530185/2f42fcb9-c1b1-4bc1-80ea-de94824edbbf)

This is a Issue on Rocket.Chat.Electron

but it's not an Issue on Rocket.Chat server
(or rather not anymore)
as it was fixed in those threads : 
https://github.com/RocketChat/Rocket.Chat/pull/32341
https://github.com/RocketChat/Rocket.Chat/issues/32367

I hope the fix that was in the Rocket.Chat server could be ported to Rocket.Chat.Electron

Otherwise, the fix is ​​to simply change the scrollbar color to white or light gray.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases. Fixed here #32341

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months for the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
