### ISSUE TITLE
Can't Listen to Audion after recording it.

### ISSUE THREAD

**Issue by thepiyush-303** [RocketChat/Rocket.Chat#33360]
### Description: 
I am unable to listen to audio messages when sending them either to a channel or directly to a friend in the chat. The audio message appears to be sent successfully, but when I try to play it, no sound is heard.

### Steps to reproduce:

1. Open a chat (either a direct message or a channel).
2. Record and send an audio message.
3. Attempt to listen to the audio message.
4. No sound is heard during playback.
### Expected behavior:
The audio message should play with sound.

### Actual behavior:
The audio message is sent, but it is not playing any sound.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.12.0-develop
- License Type:
- Number of Users: 
- Operating System: Ubuntu 24.04.1 LTS
- Deployment Method:  Gitpod/Docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version:  v14.21.4
- MongoDB Version: 7.0.5 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: FireFox 130.0 (64-bit)
- Operating System:  Ubuntu 24.04.1 LTS

**Comment by reetp** [comment]
> Version of Rocket.Chat Server: 6.12.0-develop

Really?

Either use latest 6.12.x or 6.13.rc

> License Type:
> Number of Users:

Please fill these in.

> MongoDB Version: 7.0.5

Note that 7.x is not technically supported though it probably won't affect it.

Eg release notes:

https://github.com/RocketChat/Rocket.Chat/releases/tag/6.12.1

What proxy are you using?

What file storage are you using?

Have you tested on open.rocket.chat?

**Comment by thepiyush-303** [comment]
@reetp 
Thank you for your response, I found that the issue isn't related to the application but rather to my device itself. It seems my microphone isn't functioning properly, which is why I was facing the audio problem.
