### ISSUE TITLE
Duplication of not joined channel in new Sidebar when clicking.

### ISSUE THREAD

**Issue by Barrylimarti** [RocketChat/Rocket.Chat#33379]
### Description:
The newly added feature of sidebar navigation for channels related to a GSOC24 in https://open.rocket.chat adds a duplicate channel when clicking in a channel which is not joined previously.

### Steps to reproduce:

1. Go to https://open.rocket.chat
2. Go to gsoc2024 channel.
3. Try to select a channel not joined by you previously.

### Expected behavior:

Duplication of channel name in sidebar should not happen.

### Actual behavior:

https://github.com/user-attachments/assets/5c12add7-a596-4888-8779-a4f13a000666

### Server Setup Information:

Latest https://open.rocket.chat/

### Client Setup Information

- Desktop App or Browser Version: Firefox Version 130.0.1
- Operating System: MacOS

**Comment by reetp** [comment]
Sent this to the team thanks.

**Comment by casalsgh** [comment]
Thanks for reporting. Sharing with responsible squads

**Comment by ivans-netto** [comment]
Hi @Barrylimarti 

Rooms you haven't joined won't appear in the new nav (sidepanel) in the first release.
