### ISSUE TITLE
Server takes too long to startup - Heroku and Bluemix

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#3338]
Having same problem on Heroku and Bluemix - both CloudFoundry based hosts.

The startup timeout is max at 180 seconds.

Server often takes longer than 180 seconds, from startup to listening to the PORT.

Suggested: start listening to PORT sooner to enable proper deployment.

**Comment by sampaiodiego** [comment]
duplicated of #3325 ?

**Comment by Sing-Li** [comment]
Not dupe - that one might resolve with the workaround for Heroku only.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I'm going to close this. See [here](https://github.com/RocketChat/Rocket.Chat/issues/10213#issuecomment-376720669) for my reasoning.

If one decides to tackle this, one should go about it in a way that totally decouples the boot time of the server from the amount of content/channels/whatever is on the server.

Cheers
Thomas

**Comment by luco** [comment]
+1 on this
