### ISSUE TITLE
OIDC does not work with Authelia

### ISSUE THREAD

**Issue by cyberb** [RocketChat/Rocket.Chat#33396]
### Description:

I am trying to add Authelia OIDC integration

### Steps to reproduce:

Add Authelia usinig this issue doc: https://github.com/authelia/authelia/discussions/7934

Authelia logs are ok now but I am redirected back to login

### Expected behavior:

Should log me in

### Actual behavior:

Login screen still

### Server Setup Information:

- Version of Rocket.Chat Server: 6.9.2
- License Type: Starter
- Number of Users: 1
- Operating System: Linux
- Deployment Method: Syncloud
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 4.4.16

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Ubuntu

### Additional context

browser logs:
```
<!DOCTYPE html>
<html>
<body>
  <div id="config" style="display:none;">{"setCredentialToken":true,"credentialToken":"UvKUQ7EH3-8hww1BLIyxWtkIdRUTE3QyNVYYkWJ3ptV","credentialSecret":"iz0Hn61YjXsVcrZoZCk8K0Rq9Av0Aj9EyciSxGCxqAO","storagePrefix":"Meteor.oauth.credentialSecret-","redirectUrl":"https:&#x2F;&#x2F;rocketchat.example.com&#x2F;home","isCordova":false}</div>
  <script type="text/javascript" src="/packages/oauth/end_of_redirect_response.js"></script>
</body>
</html>
```

### Relevant logs:

No logs on server

**Comment by reetp** [comment]
> Version of Rocket.Chat Server: 6.9.2

You really ought to use the lastest 6.9.x version

> I am trying to add Authelia OIDC integration

Think this is a feature-request rather than a bug so you should test on latest code and follow up with an issue here:

https://github.com/RocketChat/feature-requests

**Comment by cyberb** [comment]
Let me try with latest 6.12.1 (I will come back in couple days)
I expected OIDC to work with various implementations, Authelia seems flexible enough and devs provided a sample config which seems to work but something is wrong on RC side, it would be great to know how to get more logs to see exactly it does not like.

**Comment by reetp** [comment]
Note that this does not appear as a directly supported option currently as far as I can see from the Rocket.Chat docs so YMMV.

How have you tried to enable it in Rocket? 

Did you set up a Custom OAuth? 

admin/settings/OAuth

Show us the settings.

You need to detail exactly what you have done so far. As far as I can see from the posted link it was tested on 6.11.1 and you are on 6.9.x 

You need to be at least on the same or later version.

Also note that some things like mappings may only work certain versions - eg they many not work on CE etc.

**Comment by cyberb** [comment]
It works with 6.12.1, https://www.authelia.com/integration/openid-connect/rocket-chat

Thank you!
