### ISSUE TITLE
Customizable sounds for events

### ISSUE THREAD

**Issue by hamdawg** [RocketChat/Rocket.Chat#3340]
Your Rocket.Chat version: latest, I think?

I would like to be able to customize what sounds play when I receive a message that begins a new private conversation (like if it's the first message in more than 30 minutes) or when I receive a notify message. This should include the ability to adjust the volume of these sounds so they aren't so loud.

**Comment by soenkef** [comment]
+1

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
