### ISSUE TITLE
No Sound for Desktop Notifications

### ISSUE THREAD

**Issue by msbkmr** [RocketChat/Rocket.Chat#33421]
### Description:

After updating Rocket Chat docker image to version 6.11.0, we started getting reports of no sound for desktop notifications. I upgraded the server version to 6.12.1, but the issue persisted. I have found a workaround of changing the 'Notification sound volume' level in preferences, force closing the desktop app and re-opening. Sound will play after those steps but the issue returns the next day. 

### Steps to reproduce:

1. After updating to server version 6.11.0, sending direct messages or messages from channel will not play notification sounds
2. To restore the sound, click user icon and then select Preferences
3. Scroll to the Sound section and change the Notifications sound volume by a few levels and click Save changes before changing back to the desired value and clicking Save changes again
4. In the bottom right-hand corner of your screen, click the small arrow and hover over the Rocket Chat icon, right click and choose Quit to close Rocket Chat
5. Re-open the Rocket Chat application and sound will play for notifications 
6. The issue will eventually return, I can't say for sure if its when Rocket Chat app is closed to the system tray or when the PC sleeps, but has consistently reoccurred the next day

### Expected behavior:

Sound to play for all Rocket Chat notifications, per the settings in preferences. 

### Actual behavior:

Sound does not play unless the steps to reproduce are taken, with the issue eventually returning. 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.12.1
- License Type: Community
- Number of Users: 200
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: 4.1.1 (behavior has happened on 4.1.0 and 4.0.1)
- Operating System: Windows 11

**Comment by mddvul22** [comment]
We are seeing this same issue with 6.12.1.

**Comment by msbkmr** [comment]
> We are seeing this same issue with 6.12.1.

We've updated to 6.13.0 and the issue persists.

**Comment by mddvul22** [comment]
We are experiencing the problem also in the browser.  For us, it isn't just the desktop app.

**Comment by reetp** [comment]
> We are experiencing the problem also in the browser.  For us, it isn't just the desktop app.

You need to fill in your own server info.

We have no idea if your systems are identical or not. You may have an entirely different issue. `#metoo` is no use without absolute specifics.

If it is browser too I'd look at your OS rather than Rocket.

Can you try on a different OS?

**Comment by reetp** [comment]
See my comments here.

https://github.com/RocketChat/Rocket.Chat/issues/33805#issuecomment-2468104561

This is likely a duplicate of #33805
