### ISSUE TITLE
Errors in integrations

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#3343]
Your Rocket.Chat version: 0.31.0
root@chat:~# cat /Rocket.Chat/.node_version.txt
v0.10.40
root@chat:~# cat /Rocket.Chat/server/.bundle_version.txt
0.5.16

i get the following :

rocketchat_integrations api.coffee:114 Integrations ➔ Incoming WebHook.info Post integration
rocketchat_integrations api.coffee:23 Integrations ➔ Incoming WebHook.info will evaluate script
TypeError: Cannot set property 'bot' of undefined
    at Object.executeIntegrationRest [as action] (packages/rocketchat_integrations/server/api/api.coffee:173:2)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:147:25)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes/json-routes.js:76:1

can you tell me how to fix or diagnose. thanks. i have jira and github integrations active as per your docs.

**Comment by marceloschmidt** [comment]
It looks like the script being evaluated has an error. Can you share the script with us?

**Comment by admin-crowd-iugo** [comment]
which script did you want ? i can paste all scripts for all integrations below :

class Script {
  /**
   * @params {object} request
   */
  process_incoming_request({ request }) {
    // request.url.hash
    // request.url.search
    // request.url.query
    // request.url.pathname
    // request.url.path
    // request.url_raw
    // request.url_params
    // request.headers
    // request.user._id
    // request.user.name
    // request.user.username
    // request.content_raw
    // request.content

    // console is a global helper to improve debug
    console.log("Request: " + JSON.stringify(request.content));

    var records = JSON.parse(request.content.records);
  	var attachments = [];
    
    for(var i = 0; i < records.length; i++)
    {
      attachments.push({
        "color": "warning",
        "text": records[i].syslog_message
      });
    }
    
    return {
      content:{
        text: request.content.text,
        attachments: attachments
        // "attachments": [{
        //   "color": "#FF0000",
        //   "author_name": "Rocket.Cat",
        //   "author_link": "https://demo.rocket.chat/direct/rocket.cat",
        //   "author_icon": "https://demo.rocket.chat/avatar/rocket.cat.jpg",
        //   "title": "Rocket.Chat",
        //   "title_link": "https://rocket.chat",
        //   "text": "Rocket.Chat, the best open source chat",
        //   "fields": [{
        //     "title": "Priority",
        //     "value": "High",
        //     "short": false
        //   }],
        //   "image_url": "https://rocket.chat/images/mockup.png",
        //   "thumb_url": "https://rocket.chat/images/mockup.png"
        // }]
       }
    };

    // return {
    //   error: {
    //     success: false,
    //     message: 'Error example'
    //   }
    // };
  }
}

--------------------------------

const getLabelsField = (labels) => {
  let labelsArray = [];
  labels.forEach(function(label) {
    labelsArray.push(label.name);
  });
  labelsArray = labelsArray.join(', ');
  return {
    title: 'Labels',
    value: labelsArray,
    short: labelsArray.length <= 40
  };
};

const githubEvents = {
  ping(request) {
    return {
      content: {
        text: ':thumbsup: ' + request.content.zen
      }
    };
  },

  issues(request) {
    const user = request.content.sender;
    const attachment = {
      author_icon: 'http://plainicon.com/dboard/userprod/2800_a1826/prod_thumb/plainicon.com-50223-512px-5be.png',
      author_name: '#' + request.content.issue.number + ' - ' + request.content.issue.title,
      author_link: request.content.issue.html_url,
      fields: []
    };

    if (request.content.issue.labels) {
      attachment.fields.push(getLabelsField(request.content.issue.labels));
    }

    if (request.content.issue.assignee) {
      attachment.fields.push({
        title: 'Assignee',
        value: request.content.issue.assignee.login,
        short: true
      });
    }

    const actions = {
      'assigned': ':inbox_tray:',
      'unassigned': ':outbox_tray:',
      'opened': ':triangular_flag_on_post:',
      'closed': ':white_check_mark:',
      'reopened': ':triangular_flag_on_post:',
      'labeled': ':label:',
      'unlabeled': ':label:'
    };

    const text = actions[request.content.action] + ' issue';

    return {
      content: {
        icon_url: user.avatar_url,
        alias: user.login,
        text: text,
        attachments: [attachment]
      }
    };
  },

  issue_comment(request) {
    const user = request.content.comment.user;
    var attachment = {
      author_icon: 'http://plainicon.com/dboard/userprod/2800_a1826/prod_thumb/plainicon.com-50223-512px-5be.png',
      author_name: '#' + request.content.issue.number + ' - ' + request.content.issue.title,
      author_link: request.content.comment.html_url,
      fields: []
    };

    if (request.content.issue.labels) {
      attachment.fields.push(getLabelsField(request.content.issue.labels));
    }

    if (request.content.issue.assignee) {
      attachment.fields.push({
        title: 'Assignee',
        value: request.content.issue.assignee.login,
        short: true
      });
    }

    const text = request.content.comment.body;

    return {
      content: {
        icon_url: user.avatar_url,
        alias: user.login,
        text: text,
        attachments: [attachment]
      }
    };
  },

  pull_request(request) {
    const user = request.content.sender;
    const attachment = {
      author_icon: 'http://plainicon.com/dboard/userprod/2800_a1826/prod_thumb/plainicon.com-50223-512px-5be.png',
      author_name: '#' + request.content.pull_request.number + ' - ' + request.content.pull_request.title,
      author_link: request.content.pull_request.html_url
    };

    let text;
    switch (request.content.action) {
      case 'assigned':
        text += ' assigned to: ' + request.content.assignee.login;
        break;
      case 'unassigned':
        text += ' unassigned ' + request.content.assignee.login;
        break;
      case 'opened':
        text += ' opened';
        break;
      case 'closed':
        if (request.content.pull_request.merged) {
          text += ' merged';
        } else {
          text += ' closed';
        }
        break;
      case 'reopened':
        text += ' reopened';
        break;
      case 'labeled':
        text += ' added label: "' + request.content.label.name + '" ';
        break;
      case 'unlabeled':
        text += ' removed label: "' + request.content.label.name + '" ';
        break;
      case 'synchronize':
        text += ' synchronized';
    }

    return {
      content: {
        icon_url: user.avatar_url,
        alias: user.login,
        text: text,
        attachments: [attachment]
      }
    };
  }
};

class Script {
  process_incoming_request({ request }) {
    const header = request.headers['x-github-event'];
    if (githubEvents[header]) {
      return githubEvents[header](request);
    }

    return {
      error: {
        success: false,
        message: 'Unsupported method: ' + header
      }
    };
  }
}

----------------------

/*jshint  esnext:true*/
const DESC_MAX_LENGTH = 140;
const JIRA_LOGO = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACRElEQVRYhbWXsUscQRTGf4iIyHHIISIWIsHisMgfkNIiBJFwiKQIkipVqpA/wEZEggSxEkmZwiKI5A84REKKkIMQrINYBQmHBDmEHJdNMW+42dk3d3O76wcDu2/e973vZvfN7EF+PAfaMjYL6AzFJFBRYh0gkdEBpryciuQVwjPgFugCu068CvQcAz1g2pnfEc6taOTGL6dIAjxw5nad+FsnvuhxrosYuPbElrz5Rc8Ucu9yfhcxsAncYZZ4fwTeO+HcUcILWgFqOXg1si9vFBrAXB7iEMySfYQZzGCeWxdoAq+Bh8BYjoJjwn0jWrYrqsOIbdIvUQLseTmPgHXgiYx1ibnYU3RuYpyfKMQ/mNWx+KzkfHHmZ4Tj55zGGNhQiAlw5OQ8VeYbzvxRQCNqUxoHLgMCa07eRyd+4sTXAtwrYCLGAJje1URugLrkVIHvMuyLVZccjfsitrhFMyD0k36bTtA/cOZkTuOckaOTFtA7IgEuSG9ONeBHILctWrnwGNO/mvA3zAk4LddaThfTpoXwKiBuVyL0yxPhloLtAUVCY7us4hb7IxQ/KLu4xWFE8cP7Kg6mld4PKH5BvoNrZBMfBphohKnFMAusyvU48ClgoA3M34eBUynwUu6ngK8BE1Gn3ihYccR79Jd5nuyXsx0rZRo498Q7mK8dMDudZuC8rOLLgQI7Ts5xIGe5DANbinCP9AfmEul/SnZslWHgTBFuKnna8a3lpRCzadSVWMiAj6GPIMbAX+/+H9BS8loyN4ibwX9j/jIXDkk+pgAAAABJRU5ErkJggg==';
function stripDesc(str) {
	return str.length > DESC_MAX_LENGTH ? str.slice(0, DESC_MAX_LENGTH - 3) + '...' : str;
}

function prepareAttachment({issue, user}, text) {
	let issueType = issue.fields.issuetype;
	let res = {
		author_name: user.displayName
		, author_icon: user.avatarUrls['24x24']
		, thumb_url: issueType.iconUrl
	};
	if (text) {
		text = text.replace(/\{\{(user|issue)\.([^a-z_0-9]+)\}\}/g, (m, type, key) => (type==='user' ? user : issue)[key]);
		res.text = text;
	}
	return res;
}
class Script {
	process_incoming_request({request}) {
		const data = request.content;
		try {
			if (!data.issue || (data.user && data.user.name === 'gitlab')) {
				return;
			}
			let issue = data.issue;
			let baseJiraUrl = issue.self.replace(/\/rest\/.*$/, '');
			let user = data.user;
			let assignedTo = (issue.fields.assigned && issue.fields.assigned.name !== user.name) ? `, assigned to ${issue.fields.assigned.name}` : '';
			let issueSummary = `[${issue.key}](${baseJiraUrl}/browse/${issue.key}) ${issue.fields.summary} _(${issue.fields.priority.name.replace(/^\s*\d*\.\s*/, '')}${assignedTo})_`;
			let message = {
				icon_url: (issue.fields.project && issue.fields.project.avatarUrls && issue.fields.project.avatarUrls['48x48']) || JIRA_LOGO
				, attachments: []
			};

			if (data.webhookEvent === 'jira:issue_created') {
				message.attachments.push(prepareAttachment(data, `*Created* ${issueSummary}:\n${stripDesc(issue.fields.description)}`));
			} else if (data.webhookEvent === 'jira:issue_deleted') {
				message.attachments.push(prepareAttachment(data, `*Deleted* ${issueSummary}`));
			} else if (data.webhookEvent === 'jira:issue_updated') {
				if (data.changelog && data.changelog.items) { // field update
					let logs = [];
					data.changelog.items.forEach((change) => {
						if (!change.field.match('status|resolution|comment|priority') ) {
							return;
						}
						if (change.field==='description') {
							logs.push(`Changed *description* to:\n${stripDesc(change.toString)}`);
						} else {
							logs.push(`*${change.field}* changed from ${change.fromString} to *${change.toString}*`);
						}
					});
					logs.length && message.attachments.push(prepareAttachment(data, `*Updated* ${issueSummary}:\n  - ${logs.join('\n  - ')}`));
				}

				if (data.comment) { // comment update
					let comment = data.comment;
					let action = comment.created !== comment.updated ? 'Updated comment' : 'Commented';
					message.attachments.push(prepareAttachment(data, `*${action}* on ${issueSummary}:\n${stripDesc(comment.body)}`));
				}
			}

			if (message.text || message.attachments.length) {
				return {content:message};
			}
		} catch(e) {
			console.log('jiraevent error', e);
			return {
				error: {
					success: false,
					message: `${e.message || e} ${JSON.stringify(data)}`
				}
			};
		}
	}
}

**Comment by admin-crowd-iugo** [comment]
ive attached it as a file because its not pasting properly. 

please see attached file with name of integration followed by script.


[rocketchatintegrations.txt](https://github.com/RocketChat/Rocket.Chat/files/284837/rocketchatintegrations.txt)

**Comment by admin-crowd-iugo** [comment]
in debug mode :
rocketchat_integrations api.coffee:23 Integrations ➔ Incoming WebHook.info will                                              evaluate script
rocketchat_integrations api.coffee:24 Integrations ➔ Incoming WebHook.debug func                                             tion _classCallCheck(instance, Constructor) { if (!(instance instanceof Construc                                             tor)) { throw new TypeError('Cannot call a class as a function'); } }

/*jshint  esnext:true*/
var DESC_MAX_LENGTH = 140;
var JIRA_LOGO = 'data:image/png;base64
--rest of the jira js code here--
rocketchat_integrations api.coffee:162 Integrations ➔ Incoming WebHook.debug res                                             ult undefined
TypeError: Cannot set property 'bot' of undefined
    at Object.executeIntegrationRest [as action] (packages/rocketchat_integratio                                             ns/server/api/api.coffee:173:2)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route                                             .coffee:147:25)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes/json-routes.js:76:1
rocketchat_integrations api.coffee:114 Integrations ➔ Incoming WebHook.info Post                                              integration
rocketchat_integrations api.coffee:115 Integrations ➔ Incoming WebHook.debug @ur                                             lParams { integrationId: 'WNNxnG4XvMxwe5wDW',
  token: 'QiHT58jNcdhEy34CFT3gCd3ciagoP2Eh4dSoGLnDSa9N7aE3' }
rocketchat_integrations api.coffee:116 Integrations ➔ Incoming WebHook.debug @bo                                             dyParams { timestamp: 1464295832888,
  webhookEvent: 'comment_created',

**Comment by juniorsemacento** [comment]
There is any update for this issue?

I've try to use the Jira integration and receiving the same error.

`
....
Jun  2 11:34:16 rocket RocketChat[28226]: })();
Jun  2 11:34:16 rocket RocketChat[28226]: #033[34mIntegrations ➔ Incoming WebHook.debug#033[39m result undefined
Jun  2 11:34:16 rocket RocketChat[28226]: TypeError: Cannot set property 'bot' of undefined
Jun  2 11:34:16 rocket RocketChat[28226]: at Object.executeIntegrationRest [as action] (packages/rocketchat_integrations/server/api/api.coffee:173:2)
Jun  2 11:34:16 rocket RocketChat[28226]: at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:147:25)
Jun  2 11:34:16 rocket RocketChat[28226]: at packages/nimble_restivus/lib/route.coffee:59:33
Jun  2 11:34:16 rocket RocketChat[28226]: at packages/simple_json-routes/json-routes.js:76:1

`

**Comment by feraudet** [comment]
Same issue on 0.33.0 who make all incomming integration failling

**Comment by juniorsemacento** [comment]
@marceloschmidt do you need more information or anything else that we can help? Thanks

**Comment by william-p** [comment]
Same issue on 0.35.0 with Gitlab integration.

```
TypeError: Cannot set property 'bot' of undefined
    at Object.executeIntegrationRest [as action] (packages/rocketchat_integrations/server/api/api.coffee:173:2)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:147:25)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes/json-routes.js:76:1
```

Hardcore workaround: Delete https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/api/api.coffee#L173 and 174

Or directly on build (for testing or other ... tested with docker image):

    sed -i".bak" '/this.bodyParams.bot/,/};/d' ./programs/server/packages/rocketchat_integrations.js

**Comment by marceloschmidt** [comment]
@rodrigok fixed this with commit https://github.com/RocketChat/Rocket.Chat/commit/d818d945f4ffc2678a71b2d9743220ea826c83d3
