### ISSUE TITLE
error not user add search

### ISSUE THREAD

**Issue by bazarnew** [RocketChat/Rocket.Chat#3344]
Your Rocket.Chat version: (make sure you are running the latest)

When I try to add a user account into a channel, RocketChat responds with `error-not-allowed`, no matter which user account I try. Can somone tell my why?` 
![fffssgg](https://cloud.githubusercontent.com/assets/13213506/15535184/816323d0-2281-11e6-9fd0-2e1291e1e357.png)

**Comment by bazarnew** [comment]
When I try to add a user account into a channel, RocketChat responds with `error-not-allowed`, no matter which user account I try. Can somone tell my why?`

**Comment by marceloschmidt** [comment]
What's your Rocket.Chat version? Also, it looks like your i18n is all misconfigured, how have you deployed this instance?

**Comment by bazarnew** [comment]
hi
rocket.chat version 0.28.0

**Comment by MichaelSavin** [comment]
@marceloschmidt I see another problem (on the version 31). Search is not performed if at the beginning of the name is @. This confuses "normal" users.

**Comment by marceloschmidt** [comment]
@bazarnew can you update to latest version and try again?
@MichaelSavin can you open a different issue for what you're reporting?
Thanks.

**Comment by bazarnew** [comment]
How do I update update teach about it?

@marceloschmidt

**Comment by marceloschmidt** [comment]
@bazarnew that depends on how you've deployed it. How are you starting your server? Are you using docker?

**Comment by geekgonecrazy** [comment]
Closing this.  Please let us know if you have additional information.
