### ISSUE TITLE
Enhancement : Customer should not see a message that his chat was returned to Queue

### ISSUE THREAD

**Issue by nitinsonawane234** [RocketChat/Rocket.Chat#33459]
While support agent mark return to queue on a perticular ongoing chat, it shows on client side that "xyz retured the chat to the queue". It should not see a message that his chat was returned to Queue.

**Comment by reetp** [comment]
Closing as this is not a bug in Rocket.Chat

Please open in the correct repository

https://github.com/RocketChat/feature-requests
