### ISSUE TITLE
Multiple Ldap Authentication

### ISSUE THREAD

**Issue by jackfrost82** [RocketChat/Rocket.Chat#3345]
Is it possible to use multiple ldap source for authentication?

**Comment by marceloschmidt** [comment]
Currently, no.

**Comment by alaverty** [comment]
+1 Have two domains in the same forest, looks like I can only log in users from domain. 
Need the ability to log in users from both domains.

**Comment by mfilotto** [comment]
Any news on this one ?

**Comment by fwkeating** [comment]
I am also very interested in multi  ldap servers added for auth. For myself I would need at least 3 to access enough of our data to verify most users.

**Comment by ElucGeek** [comment]
Same need here, any plan on this ? Any possible workaround ?

**Comment by alexlaverty** [comment]
We are working around this at the moment by using Github Enterprise auth to login which has our two domains configured.

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/5058

**Comment by miltonarce** [comment]
Now it is possible?

**Comment by MathieuMailhos** [comment]
That would be a great feature
