### ISSUE TITLE
Large file transfer integrity is false

### ISSUE THREAD

**Issue by dzjbet** [RocketChat/Rocket.Chat#33487]
We set the file upload size limit to -1, and no error was displayed when uploading files. But only after more than one G. The file is not displayed in the message box, and the integrity of the database is false. We don't know what the reason is, is the software not supported, or is the configuration inaccurate。
![screenshot-20241008-164230](https://github.com/user-attachments/assets/cfef20c8-35a2-44b6-87d0-3eccd69d7f00)
![image](https://github.com/user-attachments/assets/19e22d10-ebc8-49b8-b500-33c74b0790c5)

**Comment by dzjbet** [comment]
Client example（JavaScript）：
const file = document.getElementById('fileInput').files[0];
const chunkSize = 1024 * 1024; // 1MB
const chunks = Math.ceil(file.size / chunkSize);

for (let i = 0; i < chunks; i++) {
    const start = i * chunkSize;
    const end = Math.min(file.size, start + chunkSize);
    const blob = file.slice(start, end);

    const formData = new FormData();
    formData.append('file', blob, file.name);
    formData.append('chunkIndex', i);
    formData.append('totalChunks', chunks);

    fetch('/api/upload-chunk', {
        method: 'POST',
        body: formData
    }).then(response => response.json())
      .then(data => console.log(data))
      .catch(error => console.error(error));
}

Server-side example （Node.js）：
const fs = require('fs');
const path = require('path');
const Busboy = require('busboy');

app.post('/api/upload-chunk', (req, res) => {
    const busboy = new Busboy({ headers: req.headers });

    let file;
    let chunkIndex;
    let totalChunks;

    busboy.on('file', (fieldname, stream, filename, encoding, mimetype) => {
        if (fieldname === 'file') {
            file = [];
            stream.on('data', (data) => file.push(data));
            stream.on('end', () => {
                const tempFilePath = path.join(__dirname, 'temp', `${filename}_${chunkIndex}`);
                fs.writeFileSync(tempFilePath, Buffer.concat(file));
            });
        }
    });

    busboy.on('field', (fieldname, value) => {
        if (fieldname === 'chunkIndex') {
            chunkIndex = parseInt(value, 10);
        } else if (fieldname === 'totalChunks') {
            totalChunks = parseInt(value, 10);
        }
    });

    busboy.on('finish', () => {
        if (chunkIndex === totalChunks - 1) {
            // 合并所有分片
            const finalFilePath = path.join(__dirname, 'uploads', filename);
            const writeStream = fs.createWriteStream(finalFilePath);

            for (let i = 0; i < totalChunks; i++) {
                const tempFilePath = path.join(__dirname, 'temp', `${filename}_${i}`);
                const readStream = fs.createReadStream(tempFilePath);
                readStream.pipe(writeStream, { end: false });
                readStream.on('end', () => {
                    fs.unlinkSync(tempFilePath); // 删除临时文件
                });
            }

            writeStream.on('close', () => {
                res.json({ success: true, message: 'File uploaded successfully' });
            });
        } else {
            res.json({ success: true, message: 'Chunk uploaded successfully' });
        }
    });

    req.pipe(busboy);
});

**Comment by reetp** [comment]
If you don't fill in a template properly you will not get anyone to look at this.

Thanks.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md
