### ISSUE TITLE
Use Meteor.absoluteUrl() to handle being deployed on a virtual-host.com/folder/

### ISSUE THREAD

**Issue by ogirardot** [RocketChat/Rocket.Chat#335]
I'm kind of struggling trying to get it working on a server name like that http://my.domain/rocket.chat/ 
More precisely, these fonts/images are trying to load from / instead of ROOT_URL : 
 * /fonts/roboto-regular-webfont.woff2 
 * /fonts/roboto-regular-webfont.woff 
 * /images/logo/favicon-16x16.png?v=3
 * /fonts/roboto-regular-webfont.ttf

Which is not *critical* but the FlowRouter does not behave as well making it impossible to use the app : 

    There is no route for the path: /rocket.chat/

is the error I get, and the meteor-timesync client is trying to use `/_timesync` too (but I managed to redirect using nginx...).

My set-up is to use the docker container and a nginx reverse proxy. 
I'm not exactly sure what to do to fix the client side... 

Regards, 

Olivier.

**Comment by engelgabriel** [comment]
I'll fix it.

**Comment by engelgabriel** [comment]
I removed the fonts form the /public folders and started to use it from google fonts api again.

But there are a few places where we have to add Meteor.absoluteUrl() to the beginning of the url.

@ogirardot can you give it a shot and submit a PR with the changes?

**Comment by engelgabriel** [comment]
How are you trying to achieve this? With NGINX or Apache?

**Comment by ogirardot** [comment]
Nginx

**Comment by trogdan** [comment]
ditto, i too use a virtualhost, but i'm still trying to get back the /_timesync issue.  @ogirardot where is _timesync located, or rather, what rule did you use to tell meteor to find it?

**Comment by engelgabriel** [comment]
@trogdan it is not a file or directory, it is a registered route on the http server.

**Comment by philipphoffmann** [comment]
I think this is related to #1696

**Comment by howdoicomputer** [comment]
I don't know how useful these links are but Wekan had the same problem:

https://github.com/wekan/wekan/issues/321
https://github.com/kadirahq/flow-router/pull/329
