### ISSUE TITLE
Apps-engine method executePreFileUpload allows not allowed files in some cases 

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat#33506]
### Description:

If **executePreFileUpload** execution time is more than one second, the **FileUploadNotAllowedException** is ignored and file is uploaded into the chat.

### Steps to reproduce:

1. Create simple app with sleep(1000) in method executePreFileUpload before throwing FileUploadNotAllowedException
2. Install app
3. Upload any file to the channel/group/dm

### Expected behavior:

File upload is blocked

### Actual behavior:

File upload successful

### Server Setup Information:

- Version of Rocket.Chat Server: 6.11.3
- License Type: Enterprise
- Number of Users: 7500
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 25
- NodeJS Version: v14.21.3

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Windows

### Additional context

```
import {
    IAppAccessors,
    ILogger,
    IConfigurationExtend,
    IEnvironmentRead,
    IHttp,
    IModify,
    IPersistence,
    IRead,
} from '@rocket.chat/apps-engine/definition/accessors';
import { App } from '@rocket.chat/apps-engine/definition/App';
import { IAppInfo } from '@rocket.chat/apps-engine/definition/metadata';
import { FileUploadNotAllowedException } from '@rocket.chat/apps-engine/definition/exceptions';
import { IFileUploadContext, IPreFileUpload } from '@rocket.chat/apps-engine/definition/uploads';

export class PreMethodTimeoutTestApp extends App implements IPreFileUpload {
    constructor(info: IAppInfo, logger: ILogger, accessors: IAppAccessors) {
        super(info, logger, accessors);
    }

    async sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    public async executePreFileUpload(context: IFileUploadContext, read: IRead, http: IHttp, persis: IPersistence, modify: IModify): Promise<void> {
        await this.sleep(1003);
        throw new FileUploadNotAllowedException('Virus found');
    }
}
```

### Relevant logs:
**Skipped file:**
![image](https://github.com/user-attachments/assets/5ab24ed5-70d7-4b92-a3cc-60fe6efa530b)

**But the exception was throwed:**
![image](https://github.com/user-attachments/assets/e745f777-1eb2-42fc-9006-193fe1b1cf76)

This issue does not reproduce in version 6.9.x or older

**Comment by reetp** [comment]
For reference opened here:

https://forums.rocket.chat/t/how-to-use-apps-for-long-1-20-sec-file-checking-on-external-service/20731

Please follow the guide.

* Ensure you’re running the latest version of Rocket.Chat. An update might resolve your issue.

https://developer.rocket.chat/docs/contribute-through-bug-reporting

**Comment by CyberStranger** [comment]
I tested this 
in RocketChat 6.13, and this issue is also present.
![preFileUpload](https://github.com/user-attachments/assets/ea9c4a38-9439-4f7a-a269-f037c9f85ab6)

**Comment by reetp** [comment]
> License Type: Enterprise

You should open a ticket directly with support - you will get a faster response there. Let them know this issue is open.

**Comment by shiryov** [comment]
#33834

**Comment by debdutdeb** [comment]
Closing this in favor of https://github.com/RocketChat/Rocket.Chat/issues/33834
