### ISSUE TITLE
gitpod failed (deno missing)

### ISSUE THREAD

**Issue by Utopiah** [RocketChat/Rocket.Chat#33537]
### Description:
I tried to run the Gitpod link and the build failed.

### Steps to reproduce:

1. Go on this repo
2. Click on https://gitpod.io/#https://github.com/RocketChat/Rocket.Chat
3. Wait

### Expected behavior:

Work

### Actual behavior:
Did not work

### Server Setup Information:

- Version of Rocket.Chat Server:  everything is from the Gitpod file

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Additional context

N/A

### Relevant logs:
```

@rocket.chat/apps-engine:build: 
@rocket.chat/apps-engine:build: /bin/sh: 1: deno: not found
@rocket.chat/apps-engine:build: Could not execute "deno" in the system. It is now a requirement for the Apps-Engine framework, and Rocket.Chat apps will not work without it.
@rocket.chat/apps-engine:build:  Make sure to install Deno and run the installation process for the Apps-Engine again. More info on https://docs.deno.com/runtime/manual/getting_started/installation
@rocket.chat/apps-engine:build: ERROR: ".:build:deno-cache" exited with 1.
@rocket.chat/apps-engine:build: ERROR: command finished with error: command (/workspace/Rocket.Chat/packages/apps-engine) /tmp/xfs-258483d5/yarn run build exited (1)
@rocket.chat/apps-engine#build: command (/workspace/Rocket.Chat/packages/apps-engine) /tmp/xfs-258483d5/yarn run build exited (1)

 Tasks:    21 successful, 23 total
Cached:    0 cached, 23 total
  Time:    3m10.241s 
Failed:    @rocket.chat/apps-engine#build

 ERROR  run failed: command  exited (1)
gitpod /workspace/Rocket.Chat (develop) $ 
```

**Comment by reetp** [comment]
This is not an issue with Rocket.Chat server itself but with the documentation.

Please go to the relevant page and where it says:

`Was this article helpful?`

Select 'No' and add your comment and then team will deal with it.

In the interim you may be able to follow the Linux setup to install Deno.

**Comment by Utopiah** [comment]
It's referring to 2 files from this repository AFAICT, namely `.gitpod.yml` and `README.md` so I didn't see the link from the documentation itself but from this repository, via Github. Consequently I do not know where the "Was this article helpful?" link is but feel free to point whomever is in charge of the documentation then to point to this issue.

Thanks for the clarification still.

**Comment by Utopiah** [comment]
To clarify https://github.com/RocketChat/Rocket.Chat#gitpod-setup

**Comment by reetp** [comment]
https://developer.rocket.chat/v1/docs/gitpod

**Comment by reetp** [comment]
You can add on the doc page that they need to change github as well.

**Comment by reetp** [comment]
Believe the issue is the documentation.

You need deno installed. Have a look at the linux setup on how to do it.

**Comment by Utopiah** [comment]
I'm not sure this setup (namely relying on Gitpod to get Rocket.chat running to test how to developer for it) is understood but maybe I'm missing something.

Gitpod is provided by this very repository via https://github.com/RocketChat/Rocket.Chat/blob/develop/.gitpod.yml thus if something is missing, e.g. a dependency, it's not up to a user to fix it on "their system" but rather to whomever is providing the `.gitpod.yml` file in this repository.

**Comment by reetp** [comment]
Referred to team for comment.

**Comment by Ericksolaris** [comment]
just install  brew install deno
