### ISSUE TITLE
Allow card to collapse 

### ISSUE THREAD

**Issue by sp9324** [RocketChat/Rocket.Chat#33538]
### Description:
Unable to collapse the card after expanding it. I would like to add the option to collapse it. Kindly assign this issue.

### Steps to reproduce:

1. Go to 'Solutions'->'Technology'
2. Click on '+' sign next on any card

### Expected behavior:

Card should also collapse on click. 

### Actual behavior:

Presently, there is a timeout bar that collapses the card after a set interval. 
![image](https://github.com/user-attachments/assets/b151eb7b-6c45-4d09-bbca-a05fb2c79866)

**Comment by ishwarthecodddr** [comment]
so if someone solves the issue will it be merged?

**Comment by reetp** [comment]
No.

The site is not maintained here.

**Comment by ishwarthecodddr** [comment]
then why the issues?

**Comment by reetp** [comment]
It's not a github issue.

The code here is only for Rocket.Chat server.

It's an issue with the website, and nothing to do with Rocket.Chat server itself.

Contact sales/support or ask on https://open.rocket.chat
