### ISSUE TITLE
Teams mentions through @ and # not working

### ISSUE THREAD

**Issue by NickA1ex** [RocketChat/Rocket.Chat#33541]
In Rocket Chat 6.12.1 with an Enterprise license, when team is mentioned via @, the team does not receive mentions

Steps to reproduce:
Create a team. For example with the name TestMentionsTeam_1
Mention the team in any channel by writing @TestMentionsTeam_1
![image](https://github.com/user-attachments/assets/edab349d-8688-425c-9483-4070d2c0e44f)

Expected behavior:
The team got mention in mentions tab

Actual behavior:
The team don't have any mentions in mentions tab
![image](https://github.com/user-attachments/assets/db2dc242-2b75-471d-bcb6-f2a4bfa7c7ef)

Server Setup Information:
Version of Rocket.Chat Server: 6.12.1
Operating System: Ubuntu 22
Deployment Method: Native
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version: v14.21.3
MongoDB Version: 6.0.11 / wiredTiger (oplog Enabled)
Proxy: NGINIX
Firewalls involved:

This issue reflected not for all teams
Some teams can get mentions

**Comment by BadriVishalPadhy** [comment]
@NickA1ex  assign this issue to me

**Comment by reetp** [comment]
> @NickA1ex  assign this issue to me 


No one assigns issue.

**Comment by BadriVishalPadhy** [comment]
what

**Comment by reetp** [comment]
> what

You asked this:

> > @NickA1ex  assign this issue to me 

I responded:

> No one assigns issues.

Issues are never assigned.

Work on anything you like but be aware it may be being worked on internally as they have a separate internal system.

Best you can do is test and try and repeat it, and if so offer to submit a PR.

Unlike many projects, Github is not the primary resource at Rocket.Chat

It is very secondary.

If you do produce a PR there is no guarantee it will be accepted. Depends on Dev, Product, Sales & Marketing.

N.B. if an issue is set 'Tasked' it has been referred to the internal team already.

**Comment by NickA1ex** [comment]
> @NickA1ex assign this issue to me

Hi!

Yep, @reetp is right

Instance deployed on internal company server

I just wanted to understand if anyone has encountered this problem and perhaps knows how to solve it or at least knows where to look

Unfortunately I couldn't find the answer on the rocketchat forum or on Google

**Comment by reetp** [comment]
You don't need to @ anyone thanks.

> with an Enterprise license,

Contact support directly - it's what you pay for!!

**Comment by reetp** [comment]
If you haven't contacted support can you please test n v7 and let us know if this still exists.
