### ISSUE TITLE
Link back to direct message from email

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3355]
When you are sent an email about a missed direct message it should have a link back to the conversation.

**Comment by RichardFoxworthy** [comment]
Also message permalink should be inserted when the message is emailed to user using the 'Mail Messages'  option available in the 'Room Info'  side-on panel

**Comment by geekgonecrazy** [comment]
@RichardFoxworthy absolutely!  Especially now that we have those 😄

**Comment by isabellarussell** [comment]
Hi @geekgonecrazy is this still ongoing? Tried to find where to enable missed direct message notifications/emails but could not locate it. To test this, where can we configure the notifications (on Cloud)?

**Comment by geekgonecrazy** [comment]
I believe so.  I think we just need to add a link to click and go to the DM

**Comment by rodrigok** [comment]
The button was already implemented on Rocket.Chat emails.
