### ISSUE TITLE
Removing logo from sidebar causes usability issues

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3357]
If you remove the logo from the sidebar instead of replacing it.  You will be unable to select the last channel in the list on mobile.

**Comment by geekgonecrazy** [comment]
A hack/fix for it is to do something like:

```
.side-nav .rooms-list > .wrapper {
    padding-bottom: 2em;
}
```

Credit: @sampaiodiego

**Comment by TwizzyDizzy** [comment]
@geekgonecrazy is this still an issue on latest stable?

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
I think the new design probably fixes 👍
