### ISSUE TITLE
Ability to resize channel list / message window

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3358]

**Comment by k3vmcd** [comment]
I agree with the title in the sense that the user ought to be able to click and drag the Channel List divider to resize the pane.

Additionally, the user should be able to click and drag the Server List pane to shrink the far left pane and server icons.

**Comment by jsumners** [comment]
This should also apply to the user list pane. I would also like the ability to collapse the channel list completely. Channels could have some sort of unique icon that can be updated to indicate new messages.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I'm closing this in favour of #4688 because the issue, I think, is quite similar if not identical. If you do not agree, please get back to me :)

Cheers
Thomas

**Comment by vadipp** [comment]
But #4688 was closed as Won't Fix. So I think that this issue should be reopened again.

**Comment by geekgonecrazy** [comment]
Feel free to open a feature request on https://github.com/rocketchat/feature-requests
