### ISSUE TITLE
Why is this app so painfully slow?

### ISSUE THREAD

**Issue by co50** [RocketChat/Rocket.Chat#33582]
I have a very fast recently built PC that can blaze through any game or app but using RocketChat is like I'm running a Pentium 100Mhz with 640K of RAM. I've switched back to using the website version.

**Comment by reetp** [comment]
Unless you fill out a bug template no one will help you.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

This will hep you on how to debug properly.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

> I've switched back to using the website version.

And likely you are in the wrong repo - you shoudl be in either the Electron app or react native repo.
