### ISSUE TITLE
After inactivity time, chat reopens last window, without any messages

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#336]
User nikolai.lapenok reports: "think something wrong and in members list is three me. I write direct messages to rocketbot. After that i close room with bot and open general channel. But after several minutes without any clicks open page with direct messages with rocket bot. I returned to general. And after an hour it repeat, again without any clicks opens room with rocketbot (btw witout any messages in this room)"

**Comment by rodrigok** [comment]
Probably solved by https://github.com/RocketChat/Rocket.Chat/pull/377
