### ISSUE TITLE
Encrypted Notifications

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3361]
iOS we have a route forward: http://stackoverflow.com/questions/36451413/how-can-whatsapp-encrypt-push-notifications-on-ios

Need to investigate Android.

**Comment by elimisteve** [comment]
+1 This would be great!

**Comment by danielwegener** [comment]
afaik signal on android just uses empty notifications that launches the local application service which then pulls the actual encrypted message from the server.

**Comment by geekgonecrazy** [comment]
@danielwegener hm... thats an interesting approach also

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.

**Comment by nomitri-experimental** [comment]
Is there a roadmap on when this is going to be in stable state or at least when it will be available for the mobile apps?

**Comment by JoshMcCullough** [comment]
FYI we have to disable push notifications because they're not encrypted. This is a requirement for our use case.

**Comment by igalic** [comment]
an organisation i work with also disables mobile notifications for this reason.

signal's route has already been suggested.

has anyone considered [Tutanota's](https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html)?

**Comment by geekgonecrazy** [comment]
Going to close this.  As has actually been implemented when e2e is on.  And if using enterprise will also do for non e2e rooms

**Comment by Feuermurmel** [comment]
> Going to close this. As has actually been implemented when e2e is on. And if using enterprise will also do for non e2e rooms

Where is this documented?
