### ISSUE TITLE
Call recording

### ISSUE THREAD

**Issue by david-strejc** [RocketChat/Rocket.Chat#3363]
Your Rocket.Chat version: 0.31.0

Is there any plan for WebRTC call recording? Many people whom I showed Rocket Chat asked about this feature.

**Comment by Sing-Li** [comment]
Absolutely.

**Comment by david-strejc** [comment]
How this would be done? Server will be a participant in WebRTC call? Or one of call participants will have to record whole conversation onto his device?

I would like to have an option to have calls recorded into server folder or GridFS - this will be very useful for HRs, support centers && many others.

**Comment by megabit-computing** [comment]
I can only use the call feature if this is implemented! Any ideas when development may start?

**Comment by cirrosol** [comment]
This would be very useful.

**Comment by rodrigok** [comment]
We have Jitsi as a call provider, we have plans to add other providers like Big Blue Button, so this would be a requirement of the provider not of Rocket.Chat so I'll close this.

Thanks
