### ISSUE TITLE
Ubuntu deployment documentation

### ISSUE THREAD

**Issue by imtrobin** [RocketChat/Rocket.Chat#3364]
The documentation seems broken. I tried Opera, IE, and it hangs. The other pages load fine.

https://rocket.chat/docs/master/installing-and-updating/deployment-options/ubuntu

**Comment by bott0r** [comment]
https://rocket.chat/docs/installation/manual-installation/ubuntu/

**Comment by Sing-Li** [comment]
@imtrobin    Can you please let us know _**where**_ you find that link, so we can fix or remove it - thank you.

**Comment by imtrobin** [comment]
Link from the github page from ubuntu vps deployment

https://github.com/RocketChat/Rocket.Chat

**Comment by geekgonecrazy** [comment]
Our Ubuntu documentation is up and recently modified.  So should be good to go 👍
