### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by oncorphinchus** [RocketChat/Rocket.Chat#33648]
### Description:

SyntaxError: missing ) after argument list

### Steps to reproduce:

1. Follow the installation guide for either Linux or Windows
2. When you reached the point where you have to `cd ` into Rocket.Chat and `yarn`
3. you will get this error `SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47`

### Expected behavior:

Running yarn should install everything needed before the programm is ready to be accessed.

### Actual behavior:

![Screenshot 2024-10-18 131117](https://github.com/user-attachments/assets/d6033323-8546-4bda-be67-be308c1ae507)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.13.0
- License Type: Community?
- Number of Users: 0
- Operating System: Ubuntu, windows server 2022 datacenter azure, 
- Deployment Method: tried wsl 2 and ubuntu
- Number of Running Instances: none 
- DB Replicaset Oplog: ?
- NodeJS Version: 14
- MongoDB Version: 8.0.1

### Client Setup Information

- Desktop App or Browser Version: no clients yet
- Operating System:

I am trying to setup a Rocket Chat server for a cloud computing project in school.

**Comment by abirc8010** [comment]
It seems you're trying to install the latest version of RocketChat (7.0.0).
Please use Node.js version 20.17.0 instead, and make sure you have Meteor version 3.0.3 and Deno 1.x installed.

**Comment by reetp** [comment]
If this resolves your issue please close this bug.
