### ISSUE TITLE
How to delete private (group-)chats as user/ownder 

### ISSUE THREAD

**Issue by soenkef** [RocketChat/Rocket.Chat#3365]
Hi!
I´ve tried many hours for finding an option/permission to let user/owner delete their own chats. I´ve already set up the permissions for user/owner "delete-p/delete-d", but I didn´t find the possibility to delete any chat without going to "administration"-section for admins.

Who can help me?

Your Rocket.Chat version: (0.28)

**Comment by marceloschmidt** [comment]
In fact, the permission exists, but there's no UI for handling that. It goes to the list of channel improvements we have yet to make. Thanks!

**Comment by soenkef** [comment]
A possible UI could be an icon right of the groupname (where you can leave or hide rooms). Or a button in the information-icon of the flexbar.

**Comment by soenkef** [comment]
Anything new here?

**Comment by marceloschmidt** [comment]
I think adding a button in the information-icon flex would be the best option (for both channel and private groups).

**Comment by soenkef** [comment]
Hey, when I would be able to put in the delete option, I would have done it already. Is anybody able to pick up a solution for a UI "Delete chat" or "Delete all messages of a room" without admin role?

Only with set up permissions "delete-c" and "delete-" while being owner.

This would be great!

**Comment by VIM-Arcange** [comment]
Is there any way to convert a private group to a public channel ?

**Comment by 0utsider** [comment]
+1

**Comment by greenhammock** [comment]
+1

**Comment by Jaahquubel** [comment]
+1

**Comment by soenkef** [comment]
Alright now for me! 0.46 has the option. Closed.

**Comment by jorgejeferson** [comment]
Hi, Version: 0.65.2
I don't find this option, can someone help me!

Não encontro essa opção, alguém pode me ajudar?

**Comment by chriswoolfe** [comment]
@jorgejeferson, its under Room Info 
![image](https://user-images.githubusercontent.com/5896087/68788124-d752e980-0610-11ea-9226-58eaec9be814.png)
