### ISSUE TITLE
Markdown Images Don't Work Behind Proxy

### ISSUE THREAD

**Issue by tasmar** [RocketChat/Rocket.Chat#3366]
There is a bug in the markdown images when you are behind a proxy where images will always be shown with 0px width and height.

**Comment by marceloschmidt** [comment]
Can you show us an example, please?

**Comment by tasmar** [comment]
![rc_markdown_image_bug](https://cloud.githubusercontent.com/assets/5840586/15619595/d424bb0c-241a-11e6-8521-a408517dcbdc.png)
![rc_markdown_image_temp_fix](https://cloud.githubusercontent.com/assets/5840586/15619594/d4245fea-241a-11e6-8018-9a3c613f5e96.png)

These are screenshots of a test environment behind a proxy.  The first image shows that the markdown image is technically in RC, but is not viewable as there is no height and width settings.  I am able to use a bookmarklet to add height and width the the images though, see the code snippet below.

```
javascript:(function(){
  var config = { 
    attributes: true, 
    childList: true, 
    characterData: true,
    subtree: true
  }; 
  var fixImages = function(){ 
    var images = document.querySelectorAll(".inline-image");
    for(var i=0; i<images.length; i++){
      images[i].style.height = "200px";
      images[i].style.width="300px";
    }; 
  }; 
  var observer = new MutationObserver(fixImages);
  var wrapper = document.querySelector(".wrapper");
  observer.observe(wrapper, config);
  fixImages();
})();
```

**Comment by tasmar** [comment]
Adding the script to `Layout` -> `Custom Scripts` also works, but only on the browsers.  The images do not work in the electron app still, even with the custom script to provide a height and width to it.

**Comment by gabriellsh** [comment]
I think this does not happen anymore. If you still experience this issue, please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
