### ISSUE TITLE
blocking other user in privatemessages room

### ISSUE THREAD

**Issue by bazarnew** [RocketChat/Rocket.Chat#3367]
Your Rocket.Chat version: (make sure you are running the latest)
hi

 How can a user block other users inorder not to chat with them
?
For example telegram
 Forexample in telegram setting we have block user option &if someone don't want to speak with that person,choose that option & block thatperson
&that blocked user cannot send her message
![dddqqqqqa](https://cloud.githubusercontent.com/assets/13213506/15579662/e1ed3d40-237a-11e6-92cc-ca7e6633bb66.png)

**Comment by marceloschmidt** [comment]
You can't. There's an open request for that: #1311
