### ISSUE TITLE
Oauth login setup

### ISSUE THREAD

**Issue by CollinsCoding** [RocketChat/Rocket.Chat#3368]
Sorry if this is a dumb question but I am struggling to find where I configure the third party oauth services as seen in the demo. I am currently just seeing a login screen with none of these third part icons.

I'd appreciate anyone's guidance,

Cheers

**Comment by Sing-Li** [comment]
Administration -> Settings -> OAuth

You _must_ be logged in as an administrator.

**Comment by CollinsCoding** [comment]
Thank you.
