### ISSUE TITLE
How do uploaded videos support the default extraction of the first frame?

### ISSUE THREAD

**Issue by 3419912225** [RocketChat/Rocket.Chat#33681]
After the user upload the video, the default is black is not displayed, how can it be displayed as the first frame of the video, ask for advice

**Comment by reetp** [comment]
Github is not for help or support but for bugs.

This is likely a setup issue and you should really asking for help in the https://forums.rocket.chat/ or https://open.rocket.chat/

You will not get any help unless you detail your server setup correctly as per the bug template:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

You will help yourself if you also read all of this:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#file-readme-md
