### ISSUE TITLE
Messages will not be pushed in real time and need to be refreshed to be received.

### ISSUE THREAD

**Issue by dahaiaqsw** [RocketChat/Rocket.Chat#33687]
messages are gray before i manually reloaded. 
rc_version:latest
mongo_version:6.0.3
![Rocket Chat_wHn2J7cSv8](https://github.com/user-attachments/assets/d169945d-a9a1-47a6-973d-925dc0fd87b9)

pls help me, ths.

**Comment by deathbarn** [comment]
I have encountered the same issue before. At that time, the database was down. Is the database running properly?

**Comment by reetp** [comment]
> pls help me, ths.

Github is not for help or support but for bugs. 

This is likely a setup issue and you should really asking for help in the https://forums.rocket.chat or https://open.rocket.chat

> messages are gray before i manually reloaded.
> rc_version:latest
> mongo_version:6.0.3

You will not get any help unless you detail your server setup correctly as per the bug template, though as indicated your issues are likely to be with DB or network/reverse proxy.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

You will help yourself if you also read this:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#file-readme-md

**Comment by dahaiaqsw** [comment]
> I have encountered the same issue before. At that time, the database was down. Is the database running properly?

db is alright yet.

**Comment by reetp** [comment]
> You will not get any help unless you detail your server setup correctly


^^^^^^^^^^^^^^^^^^^^^^^^^^
