### ISSUE TITLE
Preview of svg files

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#3369]
Your Rocket.Chat version: (0.31.0)

I have few problems when uploading svg files:
1- There is no preview
2- Clicking on the empty preview box shows the spinning wheel and it stays like that forever. (see attached screenshot)
3- Clicking of the file name tries to download the image instead of displaying it.
4- Downloading the file results in a file that is different from the original and doesn't work

I had this problem on a production server which is running behind an nginx. So I tried it on my test server by connecting directly to port 3000 (so no nginx) and I got the same problem!

However, this problem doesn't exist in Rocket Chat demo server. So am I missing some configuration?

![rc-svg](https://cloud.githubusercontent.com/assets/432460/15589112/62461870-235f-11e6-9e09-495fce05a23d.png)

just to confirm the file displays correctly in the upload dialog:

![rc-svg2](https://cloud.githubusercontent.com/assets/432460/15589204/d39217ae-235f-11e6-8bbc-46494eb925cc.png)

**Comment by klatys** [comment]
@fduraibi does normal image work ok?

**Comment by fduraibi** [comment]
@klatys yes, normal images preview fine.

It is only with svg. I think the problem may not be with the preview but rather with the file upload since the file itself changes to another format that is not viewable.

**Comment by AceSlash** [comment]
I have the same issue, the file indeed changes when it is sent via rocketchat. Linux "file" return this before: `SVG Scalable Vector Graphics image`
And after transfert with RocketChat: `ASCII text, with very long lines`

**Comment by andrefreitas** [comment]
I have the same issue here with version 0.39.0.

**Comment by Alucard616** [comment]
Same Problem in Version 0.49.3

**Comment by richardt3** [comment]
Same problem in 0.53.0.

Proxying through nginx. Will do some testing on direct access and on how nginx handles svg outside of RC

**Comment by louisemessage** [comment]
Tested in 2.10.5 and SVG. files are visible
