### ISSUE TITLE
show offline users

### ISSUE THREAD

**Issue by haosdent** [RocketChat/Rocket.Chat#337]
I suggest change the [code](https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/room.coffee#L210-L212) from

```
		if status in ['online', 'away', 'busy']
			return {username: username, status: status}
		return
```

to

```
		if status not in ['online', 'away', 'busy']
			status = 'offline'
		return {
			username: username
			status: status
		}
```

**Comment by sampaiodiego** [comment]
@haosdent doing this on demo server could break clients =P there is so much users to show that it is not a good idea.

we'll optimize the members list soon ;)

**Comment by haosdent** [comment]
LoL. Does the config part is OK now? If it's OK, could config this through settings. I could add it.

**Comment by sampaiodiego** [comment]
yes, it's working. you could try to do it. =)

only for you to know, will be there a button to toggle offline users' visibility.. later your settings may control if this button will displayed or not, something like "always show offline users: yes or not"

**Comment by haosdent** [comment]
Thanks, let me do it.

**Comment by sampaiodiego** [comment]
thank you :smiley:

**Comment by haosdent** [comment]
np

**Comment by bbrockman** [comment]
I wish I saw this before  I implemented this in our fork ( sscpac/chat-locker/pull/42 ).  I also updated the user names to be styled corresponding to their status.

**Comment by rodrigok** [comment]
@bbrockman Have you tested with 10.000 users in a single room?

**Comment by bbrockman** [comment]
@rodrigok We have not, but luckily for us, our customer base is much smaller :smiley:

**Comment by rodrigok** [comment]
Ok, but this PR will break our online demo :smile: 

We need a config view for rooms, so this can be optional per room, but, until there, can you add one IF to render offline users only if room has less then 200 users?

**Comment by bbrockman** [comment]
We have quite different use cases!

**Comment by engelgabriel** [comment]
Hi @bbrockman they may be a bit different, but we surely can add some "IFs" just to accommodate this differences? It should be very straight forward to test the size of the room and decide the best behavior, do you agree?

**Comment by bbrockman** [comment]
Certainly.

**Comment by engelgabriel** [comment]
@bbrockman GREAT! :+1: 

We are looking forward for you pull request!

**Comment by geekgonecrazy** [comment]
Maybe to keep from breaking the server.  Show the total amount of users like you already do.  But only show in the list x amount.  Like online users, plus 10 of the offline.  With a button to load more.  This way you limit it to small chunks. 

Of course search would search through all offline / online users.

**Comment by rodrigok** [comment]
@geekgonecrazy, maybe, we have 2 issues:

* Render: render 10k nodes can break the app or do a high CPU / Memory spike (can be solved with pagination as you said)
* Collection: Load 10k records in a collection at client side is bad, again, high CPU and Memory, so we need to keep user data in an array.

Today we have an array with all usernames of users with subscriptions to the room, this array is at the client side so we can render the array size (users count) and loop to verify and show online users (online users are loaded in the user's collection).

If we use the array to populate the mention list we will don't have the user's name, only the username, or we can create another array getting all user's names from db. In this case we will have only the users in the room.

The best solution IMHO is use remote search for mentions and, about the user list, we can do the pagination.

**Comment by geekgonecrazy** [comment]
That seems like the best solution to me.  Sounds like maintaining a list of users client side causes complications.  Also maybe not guarenteed up to date? 

Maybe caching to an extent client side for speed?  But hit the server for authoritative response + additional mentions?

**Comment by rodrigok** [comment]
I think we can start with the remote search and monitor the performance impact to decide if we need to create some kind of client cache.

**Comment by engelgabriel** [comment]
Done
