### ISSUE TITLE
 ERROR  run failed: command  exited (1)

### ISSUE THREAD

**Issue by oncorphinchus** [RocketChat/Rocket.Chat#33700]
### Description:

 ERROR  run failed: command  exited (1)

### Steps to reproduce:

1. Follow the Linux installation guide
2. "yarn dev" at the end 

### Expected behavior:

Last step before it's deployed.

### Actual behavior:

@rocket.chat/apps-engine:build: error: Error in @rocket.chat/mp3-encoder@0.24.0 parsing version requirement for dependency: lamejs@git+https://github.com/zhuker/lamejs.git
@rocket.chat/apps-engine:build:
@rocket.chat/apps-engine:build: Invalid npm version requirement. Unexpected character.
@rocket.chat/apps-engine:build:   git+https://github.com/zhuker/lamejs.git
@rocket.chat/apps-engine:build:   ~
@rocket.chat/apps-engine:build: node:child_process:966
@rocket.chat/apps-engine:build:     throw err;
@rocket.chat/apps-engine:build:     ^
@rocket.chat/apps-engine:build:
@rocket.chat/apps-engine:build: Error: Command failed: deno cache main.ts
@rocket.chat/apps-engine:build:     at genericNodeError (node:internal/errors:984:15)
@rocket.chat/apps-engine:build:     at wrappedFn (node:internal/errors:538:14)
@rocket.chat/apps-engine:build:     at checkExecSyncError (node:child_process:891:11)
@rocket.chat/apps-engine:build:     at Object.execSync (node:child_process:963:15)
@rocket.chat/apps-engine:build:     at Object.<anonymous> (/home/RocketMaster/Rocket.Chat/packages/apps-engine/scripts/deno-cache.js:18:14)
@rocket.chat/apps-engine:build:     at Module._compile (node:internal/modules/cjs/loader:1469:14)
@rocket.chat/apps-engine:build:     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
@rocket.chat/apps-engine:build:     at Module.load (node:internal/modules/cjs/loader:1288:32)
@rocket.chat/apps-engine:build:     at Module._load (node:internal/modules/cjs/loader:1104:12)
@rocket.chat/apps-engine:build:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
@rocket.chat/apps-engine:build:   status: 1,
@rocket.chat/apps-engine:build:   signal: null,
@rocket.chat/apps-engine:build:   output: [ null, null, null ],
@rocket.chat/apps-engine:build:   pid: 47945,
@rocket.chat/apps-engine:build:   stdout: null,
@rocket.chat/apps-engine:build:   stderr: null
@rocket.chat/apps-engine:build: }
@rocket.chat/apps-engine:build:
@rocket.chat/apps-engine:build: Node.js v20.17.0
@rocket.chat/apps-engine:build: ERROR: ".:build:deno-cache" exited with 1.
@rocket.chat/apps-engine:build: ERROR: command finished with error: command (/home/RocketMaster/Rocket.Chat/packages/apps-engine) /tmp/xfs-d66e3fef/yarn run build exited (1)
@rocket.chat/apps-engine#build: command (/home/RocketMaster/Rocket.Chat/packages/apps-engine) /tmp/xfs-d66e3fef/yarn run build exited (1)

 Tasks:    20 successful, 22 total
Cached:    20 cached, 22 total
  Time:    32.852s
Failed:    @rocket.chat/apps-engine#build

 ERROR  run failed: command  exited (1)

Server Setup Information:

Version of Rocket.Chat Server: newest
License Type: Community?
Number of Users: 0
Operating System: Ubuntu server 
Deployment Method: ubuntu
Number of Running Instances: none
DB Replicaset Oplog: ?
NodeJS Version: 20.17
Deno version: 3.03

Client Setup Information

Desktop App or Browser Version: no clients yet
Operating System:

I am trying to setup a Rocket Chat server for a cloud computing project in school.

**Comment by reetp** [comment]
Please stop opening new issues.

This was your last.

https://github.com/RocketChat/Rocket.Chat/issues/33648

This is a support request, not a bug.

Ask in the https://forums.rocket.chat  or https://open.rocket.chat  `#support`

Before you do, please read this - all of it including the links.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

> I am trying to setup a Rocket Chat server for a cloud computing project in school.

Unless you are trying to code and develop just use docker or snaps.
