### ISSUE TITLE
Do not allow the username "all"

### ISSUE THREAD

**Issue by BackIsBachus** [RocketChat/Rocket.Chat#3370]
Your Rocket.Chat version: 0.31.0

Hello there,

I don't think I saw this mentioned elsewhere (but correct me if it is), but you can create a user whose username is... `all`

I know it is silly but is highly problematic because you can't just mention this user in a conversation it will highlight everyone in the channel (the normal `@all` behaviour). Although the auto-completion shows 2 options the outcome is the same. 
![username_all](https://cloud.githubusercontent.com/assets/6058550/15592325/16367d3c-23a3-11e6-9f46-436aeee3a11c.PNG)
(Sorry for the French interface :fr: )

So I think it should not be possible to choose this specific username because someone someday will have the same idea again (also I don't think trusting the end-user on this one is a wise move ^^).

**Comment by Syirrus** [comment]
I think the @all is problematic in that it can be spammed. Maybe in addition to preventing someone from using this "reserved name" we can also limit the @all usage to only moderators or admins

**Comment by mnt** [comment]
@RocketChat/core

Well we could add all as a default blocked username: 
https://github.com/RocketChat/Rocket.Chat/pull/3589

What do you guys think?

**Comment by louisemessage** [comment]
Tested in 2.10.5 and this is still an issue

**Comment by ggazzo** [comment]
fixed :)
