### ISSUE TITLE
Links in a room topic are not auto linked

### ISSUE THREAD

**Issue by brendanheywood** [RocketChat/Rocket.Chat#3371]
0.31.0

Adding a link into a channel header is very useful for things like a 'Getting started' or Rules of the road type doc related to each channel. Almost all other chat products we've used do this: hipchat, slack, mattermost

![image](https://cloud.githubusercontent.com/assets/187449/15593733/68e3a9fc-23f2-11e6-8e24-8c43a27c3c12.png)

**Comment by RichardFoxworthy** [comment]
@brendanheywood you can use markdown to achieve click-able text links like this: 
[Keyword_1](https://www.myurl.com) | [Keyword_2](https://www.yoururl.com)

**Comment by brendanheywood** [comment]
Sure, but that's a pretty horrible UX, why force people to do something so clunky just for a link? Links in comments are autolinked, why not in the room topic as well?

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
