### ISSUE TITLE
Editing channel topic should be a textarea not text input

### ISSUE THREAD

**Issue by brendanheywood** [RocketChat/Rocket.Chat#3372]
0.31.0

It would be much nicer if when editing the topic it was a textarea, the previewed content wraps, but edited content doesn't:

![image](https://cloud.githubusercontent.com/assets/187449/15593797/d0bcdd8c-23f2-11e6-9948-2d30d450943b.png)

Current UI which is hard to use:

![image](https://cloud.githubusercontent.com/assets/187449/15593808/e1533344-23f2-11e6-8bc8-9525158539e2.png)

Better desired UI mockup:

![image](https://cloud.githubusercontent.com/assets/187449/15593841/200a37f4-23f3-11e6-89a0-307548be1aec.png)

**Comment by geekgonecrazy** [comment]
Don't you think an input forces people to consider that the topic space is limited?

**Comment by brendanheywood** [comment]
Limiting it's size, and whether it wraps or not are independent UX concerns. The reality is that the room topic has the width of the screen and can fit a fair bit of content on a single line. But when editing it, (in the context of the right side bar) even a quite small topics will wrap, and editing in a single line is awkward.

eg this is my current room topic:

![image](https://cloud.githubusercontent.com/assets/187449/15594135/2adbdbee-23f6-11e6-9a60-f36a20e5601e.png)

That topic is what I would consider a pretty typical real life topic, all rooms have a url which is what this topic is about, rules of the road, project setup etc, see also #3371 

Honestly I would much prefer it if the topic was editable directly inline in the topic header space and then this whole problem would go away. This is how hipchat and slack work. 

Eg something like this:

![image](https://cloud.githubusercontent.com/assets/187449/15594278/6cdb0da2-23f7-11e6-8ebb-58ab45cb148d.png)

**Comment by MartinSchoeler** [comment]
This was fixed on the latest version.
