### ISSUE TITLE
Authentication in Rocket.Chat

### ISSUE THREAD

**Issue by Artgit** [RocketChat/Rocket.Chat#3373]
Hi,

I want to integrate Rocket.Chat into my existing application.

Is it possible to seamlessly authenticate my existing users in Rocket.Chat application ? If so, could you please point me to example or documentation about that ?

Thanks,
Alex

Your Rocket.Chat version: latest

**Comment by rasos** [comment]
Depends on how you have organised your existing users:
CAS
LDAP
OAuth
SAML
See https://rocket.chat/docs/administrator-guides/authentication/

**Comment by geekgonecrazy** [comment]
Yes we have several different ways of integrating authentication.  Please see our documentation https://rocket.chat/docs
