### ISSUE TITLE
Split screen chat

### ISSUE THREAD

**Issue by david-strejc** [RocketChat/Rocket.Chat#3374]
Is there a plan for having option to split chat screen? 

I would like to have two rooms side by side (cause most of the time I chat 1:1 and I also would like to have split screen and be in General chat room).

This combines with keyboard shortcut to switch between chats.

Is this planned? Or is this a good idea?

**Comment by IQ2022** [comment]
how about ability to detach window? or have floating and then dock back?

**Comment by david-strejc** [comment]
What is planned wit webinars? Are you planning webinar specific functions?

**Comment by LeDistordu** [comment]
I need this !!! +1

Split and Detach are both good options ! Split is priority for me, for web and desktop.

**Comment by drq883** [comment]
Separate windows for channels would be a nice feature.

Has there been any traction on this since requested?

**Comment by ggazzo** [comment]
Hey @david-strejc we'll be moving this discussion to the [forums.](https://forums.rocket.chat/t/split-screen-chat/1764).
