### ISSUE TITLE
[bug] New users are not joined the default channel automatically

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#3375]
Your Rocket.Chat version: 0.31

After register and approve by moderator the user has an empty set of channels and need to search and join the GENERAL channel manually. This channel has the default checkbox enabled, but this not work in some last releases.

**Comment by marceloschmidt** [comment]
I think the `joinDefaultChannels` is not being called upon registration approval.

**Comment by zxweed** [comment]
Any changes? The 0.38 release has the same problem..

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
