### ISSUE TITLE
Create a new channel via Rocket.Chat API

### ISSUE THREAD

**Issue by Artgit** [RocketChat/Rocket.Chat#3377]
From time to time I need to programmatically create a new channels in Rocket.Chat.

Is any way to do this via Rocket.Chat API or in some other way ? If so, could you please show an example ? Thanks.

**Comment by sampaiodiego** [comment]
yes, there is :smile: 

I just created an example on our docs: https://rocket.chat/docs/developer-guides/rest-api/#create-a-channel
