### ISSUE TITLE
Changing html on rendring breaks message ordering

### ISSUE THREAD

**Issue by warcode** [RocketChat/Rocket.Chat#338]
1. Create a new channel
2. Type "1", "2", "3" as individual messages
3. Refresh the page and its fine
4. Paste a link as an individual message, type "4" as an individual message
5. Refresh the page

Order is reversed/mixed.

If you disable autolinker and oembed this doesn't happen.

**Comment by marceloschmidt** [comment]
Cannot reproduce. Maybe it's already been fixed.

**Comment by warcode** [comment]
@marceloschmidt I pulled the latest right now, and its still happening in Chrome Version 35.0.1916.153 in my Linux VM, and both Firefox dev 41.0a2 (2015-07-27) and Opera beta 31.0.1889.74.

This is happening when I run it with meteor in dev and when after being deployed with mup.

The only thing I have done to the repo is disabled rocketchat:oembed in packages.
