### ISSUE TITLE
Desktop Notifications not working properly

### ISSUE THREAD

**Issue by ishwariiic** [RocketChat/Rocket.Chat#33805]
### Description:

Desktop Notification Sound Fails to Work in Rocket.Chat (Version 6.12.1)

### Steps to reproduce:
After updating to Rocket.Chat server version 6.11.0, I began noticing that notification sounds for desktop alerts stopped working as expected. The issue persisted even after upgrading to version 6.12.1.

Steps to Replicate the Issue-
1]Update the Rocket.Chat server to version 6.11.0 or later.
2] You can observe that no notification sounds are played when receiving direct messages or channel messages.
To restore sound temporarily:
3]Open “Preferences” via the user icon.Adjust the “Notification sound volume” up or down slightly, save, then adjust back to the preferred level and save again.
4]Exit  Rocket.Chat completely by right-clicking on its icon in the system tray.
5]Reopen the app to temporarily restore sound for notifications.
The issue will return, often after the app is minimized to the system tray or the computer enters sleep mode.

### Expected behavior:

Notification sounds should play reliably for all messages in line with user settings, with no need for repeated adjustments.

### Server Setup Information:

Rocket.Chat Server Version: 6.12.1
License: Community
Active Users: 20
Operating System: Linux
Deployment Method: Docker
Instances Running: 1
DB Replication Oplog: Enabled
NodeJS Version: 14.21.3
MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by Suvendu-UI** [comment]
pls assign me this issue

**Comment by msbkmr** [comment]
I have this same exact behavior, currenting running Rocket.Chat server version 6.13.0 now. Reported in issue #33421

**Comment by Suvendu-UI** [comment]
Hey @jwilkins can you assign me this issue

**Comment by reetp** [comment]
> Hey @ishwariiic  can you assign me this issue 

No one assigns issues.

**Comment by Subham0803a** [comment]
@ishwariiic hii i would like to contribute on this issue could can assign me the issues

**Comment by reetp** [comment]
> @ishwariiic hii i would like to contribute on this issue can assign me the issues 

Please READ!!

In my previous comment I clearly said:

> No one assigns issues.
   ^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Subham0803a** [comment]
Can help me to start contribution in rocket chat like hot acces the issues
and all

**Comment by reetp** [comment]
> Can help me to start contribution in rocket chat like hot acces the issues
> and all

There is no simple solution.

Ask in for help here:
 https://open.rocket.chat/channel/support

**Comment by reetp** [comment]
Anyone looking at this please first test on v7.x and with both the latest electron client and browsers as well.

It needs properly diagnosing first.

**Comment by reetp** [comment]
Possible duplicate of 

#33805

**Comment by Subham0803a** [comment]
Duplicate means ?

**Comment by reetp** [comment]
> Duplicate means ?

https://dictionary.cambridge.org/dictionary/english/duplicate

These are likely all the same - duplicate - issue.

There are 3 of them all very similar.

**Comment by Subham0803a** [comment]
Okkk
