### ISSUE TITLE
Hover message for emoji reactions formatting

### ISSUE THREAD

**Issue by ben-hig** [RocketChat/Rocket.Chat#3380]
Your Rocket.Chat version: v0.36.5
The hover message for emoji reactions is formatted incorrectly when too many people use the same reaction. It should read "personA, personB, etc and **X more** reacted with :emoji:" Instead reads "personA, personB, etc and **more X** reacted with :emoji:"
Basically the number of additional people who reacted needs to be moved before the word "more."
example:
![andmorex](https://cloud.githubusercontent.com/assets/12514402/15611999/92d2e9c6-23f2-11e6-976b-ffbb0fe3ec04.jpg)

**Comment by bt** [comment]
Hmm, you mention version 0.36.5, but the latest version is [0.31.0](https://github.com/RocketChat/Rocket.Chat/releases)?

I just had a look at the code for reactions on the develop branch and it seems to be fixed already, 2 days ago.

Commit 3599aa3 fixes it.

**Comment by geekgonecrazy** [comment]
Closing @bt thanks for point it out
