### ISSUE TITLE
 8/5000 Suspected memory leak

### ISSUE THREAD

**Issue by 3419912225** [RocketChat/Rocket.Chat#33835]
According to my current use, the web version and the PC client version, if opened for a long time, and there are many users in the case of chatting, it will become special card, mainly reflected in switching channels, typing.

But I don't know if this belongs to a bug, I asked chatgpt about this situation, the answer is that there may be a memory leak, please kindly check the development team, thank you

**Comment by reetp** [comment]
Fill out a bug template with your server details or this will be ignored.

Note that ChatGPT is not reliable, and in this case almost certainly wrong.
