### ISSUE TITLE
Issue to make a call Jitsi Integration

### ISSUE THREAD

**Issue by lucasverisys** [RocketChat/Rocket.Chat#33853]
we've encountered an issue with Jitsi calls. Every time we try to call another contact via Jitsi, the incoming or outgoing call pop-up window frequently doesn't appear. Sometimes the pop-up does appear and we can answer the call, but nothing happens—it doesn't even open a new browser window/tab for the Jitsi meeting room.

- Version of Rocket.Chat Server: 
- License Type: Starter
- Number of Users:  5
- Operating System: Ubuntu
- Deployment Method: <!-- snap and docker->
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:5.0.15 / wiredTiger (oplog Ativado)

![jitsi error](https://github.com/user-attachments/assets/322184a2-fd6d-4329-8b6e-fda4645d403b)

**Comment by not-meet** [comment]
hey @lucasverisys it's an interesting issue to work on! I would like to work on this issue.. :-)

**Comment by reetp** [comment]
> hey @lucasverisys it's an interesting issue to work on! I would like to work on this issue.. :-)


You haven't even triaged whether it is actually a bug yet.

Do some groundwork first.

**Comment by reetp** [comment]
> Version of Rocket.Chat Server: ??

> Deployment Method: <!-- snap and docker-> ??

Please tell us more information.

This is important.

**Comment by lucasverisys** [comment]
> > hey @lucasverisys it's an interesting issue to work on! I would like to work on this issue.. :-)
> 
> You haven't even triaged whether it is actually a bug yet.
> 
> Do some groundwork first.

What did  you mean with groundwork ?

**Comment by reetp** [comment]
> > 
> > Do some groundwork first.
> 
> What did  you mean with groundwork ? 

I was referring to Not-Meet.

Before you can look at working on/fixing something you have to work out if it is actually a bug,  has been fixed in a later version, or user error.

Hence my questions.

Please answer them.

**Comment by reetp** [comment]
> > hey @lucasverisys it's an interesting issue to work on! I would like to work on this issue.. :-)
> 
> Do you have the same problem ? 

No. They are trying to find issues to work on but don't realise you can't fix anything until you know exactly what is broken.

**Comment by JagjeevanAK** [comment]
@lucasverisys bro @reetp means just reproduce this issue on @not-meet side so to confirm the is this issue is faced by  ** everyone **

**Comment by reetp** [comment]
> @lucasverisys bro @reetp means just reproduce this issue on @not-meet side so to confirm the is this issue is faced by everyone

Exactly this.

The first step in any issue is triage/diagnosis. You can't fix something you don't understand.

Otherwise you'll waste hours chasing ghosts, or find it was a support issue.

**Comment by reetp** [comment]
Please tell us this:

> Version of Rocket.Chat Server:

I also note you are running this locally on 3000

![Screenshot_2024-11-11_14-43-29](https://github.com/user-attachments/assets/8346083d-9f52-417a-aca0-f2f464b4f94c)

Apart from development you should never use ip:3000

Using it locally will cause all sorts of problems. The server should be setup with a proper domain name behind a reverse proxy and using https.

eg only accessible via `https://chat.mydomain.info`

**Comment by reboot523** [comment]
> 请告诉我们：
> 
> > Rocket.Chat 服务器的版本：
> 
> 我还注意到您正在 3000 本地运行它
> 
> ![Screenshot_2024-11-11_14-43-29](https://private-user-images.githubusercontent.com/3800384/384943356-8346083d-9f52-417a-aca0-f2f464b4f94c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDQxNzMsIm5iZiI6MTczNDQwMzg3MywicGF0aCI6Ii8zODAwMzg0LzM4NDk0MzM1Ni04MzQ2MDgzZC05ZjUyLTQxN2EtYWNhMC1mMmY0NjRiNGY5NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMDI1MTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU1MGUwODc2ODRhMTcxMDljMGVkYjNjNWUzYWMwZTVkODIwOGEzOTU5YzE5M2U4OWNmZDM5M2I1ZDU0NjBjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iC2wtnFtr4rasstxHyDmQpkRCA7eqNMprz9YzSe2VRc)
> 
> 除了开发之外，你永远不应该使用 ip：3000
> 
> 在本地使用它会导致各种问题。服务器应在反向代理后面设置适当的域名并使用 https。
> 
> 例如，只能通过以下方式访问`https://chat.mydomain.info`

I'm having the same issue and now I'm using let's E's security certificate and it's a standard ssl 80/443 port. The mobile client RocketChat cannot jump to an external browser by joining the call to access the JITSI, but other buttons or links can jump directly to the external browser.

**Comment by reetp** [comment]
> I'm having the same issue and now I'm using let's E's security certificate and it's a standard ssl 80/443 port. The mobile client RocketChat cannot jump to an external browser by joining the call to access the JITSI, but other buttons or links can jump directly to the external browser.

This is an old closed bug that was likely a configuration issue and unlikely to be exactly related to your issue.

You will not get help unless you fill out this information - server and client information is vital. Make sure you have tested on the latest code as well please.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- License Type:
- Number of Users: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

For general support like this you should ask on https://open.rocket.chat/channel/support with a properly documented question showing all that information.

If it is a bug then you can open a new issue later.

**Comment by friedrichkeydel** [comment]
If it's a configuration issue: Did someone find a solution?
I've got the exact same Problem using the Electron App on macOS! It's resolved directly after refreshing (Command + R) for some time, but after a certain amount of time it happens again!.

**Server Setup Information:**

- Version of [Rocket.Chat](https://rocket.chat/) Server: 7.4.1
- License Type: Starter
- Number of Users: 24
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- NodeJS Version: v22.13.1
- MongoDB Version: 6.0.13 / wiredTiger (oplog Aktiviert)

**Client Setup Information**

- Desktop App or Browser Version: 4.2.0
- Operating System: macOS

**Comment by friedrichkeydel** [comment]
For additional invastigation: Sometimes the call-popup works correctly, but the following error appears on side of the called person after taking it:

https://github.com/RocketChat/Rocket.Chat/issues/33853
