### ISSUE TITLE
Version 7.0.0 Docker image - App is not working

### ISSUE THREAD

**Issue by blueiceprj** [RocketChat/Rocket.Chat#33864]
### Description:

I tried to update to the new version but the application did not start.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type:
- Number of Users: 
- Operating System: Linux - Docker - rocketchat/rocket.chat:latest
- Deployment Method: Docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v20.17.0
- MongoDB Version: 8X

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: MacOS

### Relevant logs:

Attaching to rocketchat-app
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app | node:internal/modules/cjs/loader:1228
rocketchat-app |   throw err;
rocketchat-app |   ^
rocketchat-app | 
rocketchat-app | Error: Cannot find module '/app/bundle/bash'
rocketchat-app |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-app |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-app |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-app |     at node:internal/main/run_main_module:28:49 {
rocketchat-app |   code: 'MODULE_NOT_FOUND',
rocketchat-app |   requireStack: []
rocketchat-app | }
rocketchat-app | 
rocketchat-app | Node.js v20.17.0
rocketchat-app exited with code 1

**Comment by saschafoerster** [comment]
Same here. What a mess. 

```
rocketchat-rocketchat-1  | node:internal/modules/cjs/loader:1228
rocketchat-rocketchat-1  |   throw err;
rocketchat-rocketchat-1  |   ^
rocketchat-rocketchat-1  | 
rocketchat-rocketchat-1  | Error: Cannot find module '/app/bundle/bash'
rocketchat-rocketchat-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
rocketchat-rocketchat-1  |     at Module._load (node:internal/modules/cjs/loader:1051:27)
rocketchat-rocketchat-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
rocketchat-rocketchat-1  |     at node:internal/main/run_main_module:28:49 {
rocketchat-rocketchat-1  |   code: 'MODULE_NOT_FOUND',
rocketchat-rocketchat-1  |   requireStack: []
rocketchat-rocketchat-1  | }
rocketchat-rocketchat-1  | 
rocketchat-rocketchat-1  | Node.js v20.17.0
rocketchat-rocketchat-1 exited with code 1
rocketchat-rocketchat-1 exited with code 0
```

**Comment by tom666-debug** [comment]
confirmed - same here

**Comment by Arcopix** [comment]
Since the update:
```
node:internal/modules/cjs/loader:1228
  throw err;
  ^
Error: Cannot find module '/app/bundle/bash'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.17.0
```

**Comment by reetp** [comment]
> rocketchat/rocket.chat:latest

Never, ever, use latest unless you are developing or like living dangerously.

Specify a version.

Plenty of info online as to why not.

Is everyone using docker directly, or docker-compose as per the docs?

Note: `#metoo` is irrelevant and you will get ignored.

Please be specific about your own scenario. It is very very important.

> FYI - after rollback

You should never roll back, particularly in major upgrades, due to changes in the DB - which you won't know if they are reversible until too late. 

Backup and restore is the only really guaranteed method.

**Comment by Yasen6275** [comment]
>Never, ever, use latest unless you are developing or like living dangerously.

Would you be so kind to explain to me what is the role of Release Candidates? And wasn't the idea docker, snap and such things to work everywhere as its working on "developer"'s computer?

**Comment by 3x3cut0r** [comment]
I switched to `registry.rocket.chat/rocketchat/rocket.chat:7.0.0`
Its working fine now!

**Comment by saschafoerster** [comment]
I compared the latest docker-compose.yml from RocketChat with mine. 
The switch to "registry.rocket.chat" alone, did not help in my case. 
I also had to remove the command: "bash... " in my docker-compose.yml, then it would start up. 

Next. Upgrade mongo.

**Comment by reetp** [comment]
You all probably need to get the latest compose files & use a .env as per the docs.

(Includes me as well, but mine isn't broken)


https://docs.rocket.chat/v1/docs/deploy-with-docker-docker-compose

**Comment by blueiceprj** [comment]
> I compared the latest docker-compose.yml from RocketChat with mine. The switch to "registry.rocket.chat" alone, did not help in my case. I also had to remove the command: "bash... " in my docker-compose.yml, then it would start up.
> 
> Next. Upgrade mongo.

It works. Thanks.

**Comment by blueiceprj** [comment]
This is the solution.
https://github.com/RocketChat/Rocket.Chat/issues/33864#issuecomment-2466027566

**Comment by mremptypants** [comment]
> I compared the latest docker-compose.yml from RocketChat with mine. The switch to "registry.rocket.chat" alone, did not help in my case. I also had to remove the command: "bash... " in my docker-compose.yml, then it would start up.
> 
> Next. Upgrade mo

What did your replace it with?  'node' 'main.js' ?

**Comment by 3x3cut0r** [comment]
we have removed the complete 'command' entry, not just parts of it like node or main.js
