### ISSUE TITLE
[7.0.0] Failed to startup Deno subprocess Error: spawn deno ENOENT / Error while compiling the App

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat#33863]
### Description:

All marketplace apps have been disabled after the upgrade to RocketChat 7.0.0.
During startup every app is listed with a "Error while compiling the App ...."

### Steps to reproduce:

1. Upgrade RocketChat from 6.13.0 to 7.0.0
2. All apps are disabled with the error above

### Expected behavior:

That is is possible to activate and use the marketplace apps.

### Actual behavior:

Apps not working.

### Server Setup Information:

- Version of Rocket.Chat Server:  7.0.0
- License Type: Community
- Number of Users:  >30
- Operating System:  Rocky Linux 8
- Deployment Method:  tar
- Number of Running Instances:  1 
- DB Replicaset Oplog:  no
- NodeJS Version:  v20.17.0
- MongoDB Version: 6.0.19 / wiredTiger (oplog Disabled)

### Client Setup Information

- Desktop App or Browser Version: FF 132
- Operating System: Fedora 41

### Relevant logs:

```
Nov  1 10:29:26 rocket-test RocketChat[4501]: Failed to startup Deno subprocess Error: spawn deno ENOENT
Nov  1 10:29:26 rocket-test RocketChat[4501]:    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
Nov  1 10:29:26 rocket-test RocketChat[4501]:    at onErrorNT (node:internal/child_process:484:16)
Nov  1 10:29:26 rocket-test RocketChat[4501]:    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
Nov  1 10:29:26 rocket-test RocketChat[4501]:  errno: -2,
Nov  1 10:29:26 rocket-test RocketChat[4501]:  code: 'ENOENT',
Nov  1 10:29:26 rocket-test RocketChat[4501]:  syscall: 'spawn deno',
Nov  1 10:29:26 rocket-test RocketChat[4501]:  path: 'deno',
Nov  1 10:29:26 rocket-test RocketChat[4501]:  spawnargs: [
Nov  1 10:29:26 rocket-test RocketChat[4501]:    'run',
Nov  1 10:29:26 rocket-test RocketChat[4501]:    '--allow-net',
Nov  1 10:29:26 rocket-test RocketChat[4501]:    '--allow-read=/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine,/opt/Rocket.Chat/programs/server/npm/node_modules',
Nov  1 10:29:26 rocket-test RocketChat[4501]:    '--allow-env=NODE_EXTRA_CA_CERTS',
Nov  1 10:29:26 rocket-test RocketChat[4501]:    '/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts',
Nov  1 10:29:26 rocket-test RocketChat[4501]:    '--subprocess',
Nov  1 10:29:26 rocket-test RocketChat[4501]:    '5a85e557-2e86-4699-b6ba-316d40536e2b'
Nov  1 10:29:26 rocket-test RocketChat[4501]:  ]
Nov  1 10:29:26 rocket-test RocketChat[4501]: }
Nov  1 10:29:26 rocket-test RocketChat[4501]: +-----------------------------------------------------------+
Nov  1 10:29:26 rocket-test RocketChat[4501]: |                       SERVER RUNNING                      |
Nov  1 10:29:26 rocket-test RocketChat[4501]: +-----------------------------------------------------------+
Nov  1 10:29:26 rocket-test RocketChat[4501]: |                                                           |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |  Rocket.Chat Version: 7.0.0                               |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |       NodeJS Version: 20.17.0 - x64                       |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |      MongoDB Version: 6.0.19                              |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |       MongoDB Engine: wiredTiger                          |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |             Platform: linux                               |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |         Process Port: 3000                                |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |             Site URL: https://                            |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |     ReplicaSet OpLog: Enabled                             |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |          Commit Hash: dfc7e0e874                          |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |        Commit Branch: HEAD                                |
Nov  1 10:29:26 rocket-test RocketChat[4501]: |                                                           |
Nov  1 10:29:26 rocket-test RocketChat[4501]: +-----------------------------------------------------------+
Nov  1 10:29:46 rocket-test RocketChat[4501]: Error while compiling the App "GIPHY (8b882242-0cb7-419f-87d8-93b1d09e1ec2)":
Nov  1 10:29:46 rocket-test RocketChat[4501]: Error: [8b882242-0cb7-419f-87d8-93b1d09e1ec2] Timeout: app process not ready
Nov  1 10:29:46 rocket-test RocketChat[4501]:    at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts:277:55)
Nov  1 10:29:46 rocket-test RocketChat[4501]:    at listOnTimeout (node:internal/timers:581:17)
Nov  1 10:29:46 rocket-test RocketChat[4501]:    at processTimers (node:internal/timers:519:7)
Nov  1 10:29:46 rocket-test RocketChat[4501]: Failed to startup Deno subprocess Error: spawn deno ENOENT
Nov  1 10:29:46 rocket-test RocketChat[4501]:    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
Nov  1 10:29:46 rocket-test RocketChat[4501]:    at onErrorNT (node:internal/child_process:484:16)
Nov  1 10:29:46 rocket-test RocketChat[4501]:    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
Nov  1 10:29:46 rocket-test RocketChat[4501]:  errno: -2,
Nov  1 10:29:46 rocket-test RocketChat[4501]:  code: 'ENOENT',
Nov  1 10:29:46 rocket-test RocketChat[4501]:  syscall: 'spawn deno',
Nov  1 10:29:46 rocket-test RocketChat[4501]:  path: 'deno',
Nov  1 10:29:46 rocket-test RocketChat[4501]:  spawnargs: [
Nov  1 10:29:46 rocket-test RocketChat[4501]:    'run',
Nov  1 10:29:46 rocket-test RocketChat[4501]:    '--allow-net',
Nov  1 10:29:46 rocket-test RocketChat[4501]:    '--allow-read=/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine,/opt/Rocket.Chat/programs/server/npm/node_modules',
Nov  1 10:29:46 rocket-test RocketChat[4501]:    '--allow-env=NODE_EXTRA_CA_CERTS',
Nov  1 10:29:46 rocket-test RocketChat[4501]:    '/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts',
Nov  1 10:29:46 rocket-test RocketChat[4501]:    '--subprocess',
Nov  1 10:29:46 rocket-test RocketChat[4501]:    '7a8cd36b-5f7b-4177-bd7f-bfc9be908bf8'
Nov  1 10:29:46 rocket-test RocketChat[4501]:  ]
Nov  1 10:29:46 rocket-test RocketChat[4501]: }


```

**Comment by not-meet** [comment]
@TimmiORG  i would like to work on this issue.. it would be really great if you give me a green flag so that i can start working on it :-)

**Comment by limer-org** [comment]
Similar problem with manual installation.
`lis 01 23:19:53 kashi rocketchat[4990]: Failed to startup Deno subprocess Error: spawn deno ENOENT
lis 01 23:19:53 kashi rocketchat[4990]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
lis 01 23:19:53 kashi rocketchat[4990]:     at onErrorNT (node:internal/child_process:484:16)
lis 01 23:19:53 kashi rocketchat[4990]:     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
lis 01 23:19:53 kashi rocketchat[4990]:   errno: -2,
lis 01 23:19:53 kashi rocketchat[4990]:   code: 'ENOENT',
lis 01 23:19:53 kashi rocketchat[4990]:   syscall: 'spawn deno',
lis 01 23:19:53 kashi rocketchat[4990]:   path: 'deno',
lis 01 23:19:53 kashi rocketchat[4990]:   spawnargs: [
lis 01 23:19:53 kashi rocketchat[4990]:     'run',
lis 01 23:19:53 kashi rocketchat[4990]:     '--allow-net',
lis 01 23:19:53 kashi rocketchat[4990]:     '--allow-read=/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine,/opt/Rocket.Chat/programs/server/npm/node_modules',
lis 01 23:19:53 kashi rocketchat[4990]:     '--allow-env=NODE_EXTRA_CA_CERTS',
lis 01 23:19:53 kashi rocketchat[4990]:     '/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts',
lis 01 23:19:53 kashi rocketchat[4990]:     '--subprocess',
lis 01 23:19:53 kashi rocketchat[4990]:     '8b882242-0cb7-419f-87d8-93b1d09e1ec2'
lis 01 23:19:53 kashi rocketchat[4990]:   ]
lis 01 23:19:53 kashi rocketchat[4990]: }`

**Comment by limer-org** [comment]
after installed deno from `cur -fsSL https://deno.land/install.sh | sh -s v1.0.0` i got: 

> lis 02 00:26:37 kashi rocketchat[6194]: Subprocess stderr Compile file:///opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts
lis 02 00:26:37 kashi rocketchat[6194]: Subprocess stderr error: Uncaught URIError: relative import path "jsonrpc-lite" not prefixed with / or ./ or ../ Imported from "file:///opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts"
lis 02 00:26:37 kashi rocketchat[6194]:     at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
lis 02 00:26:37 kashi rocketchat[6194]:     at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
lis 02 00:26:37 kashi rocketchat[6194]:     at resolveModules ($deno$/compiler.ts:32:10)
lis 02 00:26:37 kashi rocketchat[6194]:     at processImports ($deno$/compiler.ts:735:27)
lis 02 00:26:37 kashi rocketchat[6194]:     at processImports ($deno$/compiler.ts:753:13)
lis 02 00:26:37 kashi rocketchat[6194]:     at async compile ($deno$/compiler.ts:1316:31)
lis 02 00:26:37 kashi rocketchat[6194]:     at async tsCompilerOnMessage ($deno$/compiler.ts:1548:22)
lis 02 00:26:37 kashi rocketchat[6194]:     at async workerMessageRecvCallback ($deno$/runtime_worker.ts:74:9)
lis 02 00:26:37 kashi rocketchat[6194]: Subprocess stderr Compile file:///opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts
lis 02 00:26:38 kashi rocketchat[6194]: Subprocess stderr error: Uncaught URIError: relative import path "jsonrpc-lite" not prefixed with / or ./ or ../ Imported from "file:///opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts"
lis 02 00:26:38 kashi rocketchat[6194]:     at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
lis 02 00:26:38 kashi rocketchat[6194]:     at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
lis 02 00:26:38 kashi rocketchat[6194]:     at resolveModules ($deno$/compiler.ts:32:10)
lis 02 00:26:38 kashi rocketchat[6194]:     at processImports ($deno$/compiler.ts:735:27)
lis 02 00:26:38 kashi rocketchat[6194]:     at processImports ($deno$/compiler.ts:753:13)
lis 02 00:26:38 kashi rocketchat[6194]:     at async compile ($deno$/compiler.ts:1316:31)
lis 02 00:26:38 kashi rocketchat[6194]:     at async tsCompilerOnMessage ($deno$/compiler.ts:1548:22)
lis 02 00:26:38 kashi rocketchat[6194]:     at async workerMessageRecvCallback ($deno$/runtime_worker.ts:74:9)
lis 02 00:26:47 kashi rocketchat[6194]: === UnHandledPromiseRejection ===
lis 02 00:26:47 kashi rocketchat[6194]: Error: [8b882242-0cb7-419f-87d8-93b1d09e1ec2] Timeout: app process not ready
lis 02 00:26:47 kashi rocketchat[6194]:     at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts:277:55)
lis 02 00:26:47 kashi rocketchat[6194]:     at listOnTimeout (node:internal/timers:581:17)
lis 02 00:26:47 kashi rocketchat[6194]:     at processTimers (node:internal/timers:519:7)

**Comment by reetp** [comment]
> Similar problem with manual installation

We can't tell that unless you give us your deployment info.

Full in the bug template for yor own scenario.

OP had a running server but couldn't install apps. So not the same thing.

**Comment by fc757** [comment]
So this is what fixed it for me.

systemctl stop rocketchat

curl -fsSL https://deno.land/install.sh | sh -s v1.0.0

cp deno from ~/.deno/bin to /usr/bin/deno or add it to your path

then I did deno  upgrade --version 1.43.6

**Comment by limer-org** [comment]
thanks @fc757 
Increasing the deno version helped me. the installation from the marketplace works fine.

**Comment by TimmiORG** [comment]
I just looks through the deployment docs and found the following:
![image](https://github.com/user-attachments/assets/bf60e618-9a89-4262-ac7d-58ec7735ddf8)

But this is resulting into the following error as well:

```
npm install --production
npm warn config production Use `--omit=dev` instead.
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:~
```

**Comment by TimmiORG** [comment]
Hi @reetp ,

I don't think that this is resolved.
Maybe you can explain what I'm missing?

As I wrote I can run the commands with 6.13.0 and node 14.21.3.
But I receive an error with node 20.17.0 and 7.0.0.

**Comment by reetp** [comment]
I think this comment?

https://github.com/RocketChat/Rocket.Chat/issues/33863#issuecomment-2453168393

**Comment by paulchen** [comment]
> I think this comment?
> 
> [#33863 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/33863#issuecomment-2453168393)

I observe part of this issue in a Docker-based setup. I don't think I should fiddle around with `npm` inside the Docker container.

```
Error while compiling the App "Tenor (ab4728ec-613e-472f-a24c-b48a77aacfff)":
Error: [ab4728ec-613e-472f-a24c-b48a77aacfff] Timeout: app process not ready
    at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/src/server/runtime/deno/AppsEngineDenoRuntime.ts:277:55)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
```

I do not see the `Failed to startup Deno subprocess Error: spawn deno ENOENT` error.

I wonder whether this is related to the problems I'm having since 6.11.1 that prevent me from installing/enabling apps, cf. https://github.com/RocketChat/Rocket.Chat/issues/33140

**Comment by TimmiORG** [comment]
> I think this comment?
> 
> [#33863 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/33863#issuecomment-2453168393)

I don't think so as -> https://github.com/RocketChat/Rocket.Chat/issues/33863#issuecomment-2454344074
does not work with RocketChat 7.0.0 and I guess RocketChat is handling the dependencies or not? 
Otherwise the documentation needs to be updated.
Also how do I know which deno version is the right one to use.
Do I need to take care of keeping it up to date?

**Comment by reetp** [comment]
>  I don't think I should fiddle around with npm inside the Docker container.

No, not in docker.

The problem here is we have multiple posters with vaguely similar errors, but they are actually not the same.

It's a cats cradle of `#metoo` with no proper deployment detail.

Impossible to triage and resolve, and a waste of peoples time.

> I'm having since 6.11.1 that prevent me from installing/enabling apps

In which case stay in the relevant bug.

**Comment by paulchen** [comment]
> It's a cats cradle of `#metoo` with no proper deployment detail.

Sorry, forgot to add this to my previous comment.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Starter
- Number of Users: 20
- Operating System: Debian 12
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: whatever is inside the Docker container
- MongoDB Version: 6.0.19 / wiredTiger (oplog Enabled)

### Client Setup Information

Behaviour is likely the same with all clients.

- Desktop App or Browser Version: Chromium Version 130.0.6723.91 (Offizieller Build) Arch Linux (64-Bit)
- Operating System: Arch Linux

**Comment by florisvangeel** [comment]
Confirmed deno is a requirement for the build process now for 7.x and above.
yarn build fails if it's not installed.

Just follow the instructions at [deno](https://docs.deno.com/runtime/getting_started/installation/)
in my case on Linux:
```
curl -fsSL https://deno.land/install.sh | sh
source ~/.profile
```
the source command is not to have to reopen the shell to load environment variables.
This dependency is only needed to build the package, so you don't have to copy it to /usr/bin

Follow up for closing this issue is to update the deployment documentation.

**Comment by ITSonixcdGmbH** [comment]
I would like to add that 

> Confirmed deno is a requirement for the build process now for 7.x and above. yarn build fails if it's not installed.
> 
> Just follow the instructions at [deno](https://docs.deno.com/runtime/getting_started/installation/) in my case on Linux:
> 
> ```
> curl -fsSL https://deno.land/install.sh | sh
> deno upgrade --version 1.43.6
> ```
> 
> its needed for building and running the service so you have to copy it to `/usr/local/bin` since /user/bin should be reserved for the package manager of your os.
> 
> Combining with the pointers from [TimmiORG](https://github.com/RocketChat/Rocket.Chat/issues/33863#issuecomment-2454344074) found some clues in the logs:
> 
> ```
> RocketChat[8735]: Subprocess stderr #033[0m#033[1m#033[31merror#033[0m: TypeScript files are not supported in npm packages: file:///var/lib/rocket.chat/bundle/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts
> ```
> 
> Whom leads to upstream issues [here](https://questions.deno.com/m/1247269121180176444) and [here](https://github.com/denoland/deno/issues/24093)
> 
> Tried with deno 1.43.6 as well as 1.46.3 The api call to jitsi app https://myrocket.tld/api/apps/3b387ba9-f57c-44c6-9810-8c0256abd64c/apis should not give a 404 Even then apps not working. (RC 7.1.0 community)
> 
> **UPDATE**: Turns out there is a mistake in the [documentation](https://docs.rocket.chat/docs/additional-deployment-methods) regarding `deno` and `apps-engine` underneath are the corrections for debian/ubuntu
> ## one time action: install deno as admin
> 
> ```
> curl -fsSL https://deno.land/install.sh | sh
> ## downgrade deno from 2.x
> deno upgrade 1.43.6
> ## make available to all users
> cp ~/.deno/bin/deno /usr/local/bin/deno
> ```
> 
> ## each time when building become the rocketchat user
> 
> ```
> su rocketchat -s/bin/bash
> ## navigate to the project folder, mine is:
> cd /var/lib/rocket.chat/bundle
> ## use exact nodejs version see package.json for current version 
> nvm use 20.18.0 
> ## we need to install the submodules in the programs/server directory
> cd programs/server 
> ## export the actual cache folder usually ~/.cache/deno
> export DENO_DIR=/var/lib/rocket.chat/.cache/deno
> ## npm install --production is deprecated instead use:
> npm install --omit=dev
> ```
> 
> the post install functions are also removed from the package
> 
> Now the marketplace finally works 😎
> 
> Footnote: i don't use docker for stateful apps.

Thank you that helped us a lot. We had a additional Problem that resulted in a Apps error while installing which was caused by not having the filesystem folder configured.

**Comment by sebastianleecn** [comment]
Same problem for me, deno 1.37.1 
ubuntu 24.04
Rocket.Chat 7.4.1
Yarn dsv starting is ok
But rc-apps loop deno spawn error
