### ISSUE TITLE
Reading status after upgrade to 7.0.0

### ISSUE THREAD

**Issue by wgaulke** [RocketChat/Rocket.Chat#33877]
### Description:

After the upgrade to 7.0.0 user read status is not updated. Only after some time / reloading the client the status is updated. 

What I did:

- Upgrading MongoDB from 5.0 to 6.0 (changing setFeatureCompatibilityVersion to 6.0) 
- Upgrading Rocketchat from 6.13.0 to 7.0.0

### Steps to reproduce:

- Upgrade mongo from 5 to 6
- Upgrade rocketchat from 6 to 7

### Expected behavior:

Messages are set to read as soon as channel is opened / message viewed.

### Actual behavior:

Viewed status is not changing, only after reload.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Starter
- Number of Users: 22
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: provided by docker
- MongoDB Version: 6.0.

### Client Setup Information

- Desktop App or Browser Version: latest electron app
- Operating System: MacOs

### Relevant logs:

Server:

```
rocketchat-1  | === UnHandledPromiseRejection ===
rocketchat-1  | TypeError: Cannot read properties of undefined (reading 'status')
rocketchat-1  |     at EventEmitter.<anonymous> (server/services/meteor/service.ts:172:72)
rocketchat-1  |     at EventEmitter.emit (node:events:531:35)
rocketchat-1  |     at EventEmitter.emit (node:domain:488:12)
rocketchat-1  |     at LocalBroker.broadcastLocal (/app/bundle/programs/server/npm/node_modules/@rocket.chat/core-services/src/LocalBroker.ts:100:15)
rocketchat-1  |     at Api.broadcastLocal (/app/bundle/programs/server/npm/node_modules/@rocket.chat/core-services/src/lib/Api.ts:65:23)
rocketchat-1  |     at DatabaseWatcher.<anonymous> (server/modules/watchers/watchers.module.ts:335:8)
rocketchat-1  |     at DatabaseWatcher.emit (node:events:519:28)
rocketchat-1  |     at DatabaseWatcher.emit (node:domain:488:12)
rocketchat-1  |     at DatabaseWatcher.emitDoc (server/database/DatabaseWatcher.ts:226:8)
rocketchat-1  |     at ReadableCursorStream.<anonymous> (server/database/DatabaseWatcher.ts:135:9)
rocketchat-1  |     at ReadableCursorStream.emit (node:events:519:28)
rocketchat-1  |     at ReadableCursorStream.emit (node:domain:488:12)
rocketchat-1  |     at addChunk (node:internal/streams/readable:559:12)
rocketchat-1  |     at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
rocketchat-1  |     at ReadableCursorStream.Readable.push (node:internal/streams/readable:391:5)
rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/mongodb/src/cursor/abstract_cursor.ts:963:18
rocketchat-1  |     at next (/app/bundle/programs/server/npm/node_modules/mongodb/src/cursor/abstract_cursor.ts:779:5)
rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/mongodb/src/cursor/abstract_cursor.ts:818:5
rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/mongodb/src/cursor/find_cursor.ts:116:7
rocketchat-1  |     at /app/bundle/programs/server/npm/node_modules/mongodb/src/utils.ts:461:15
rocketchat-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Electron Client:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at local_collection.js:1469:14
    at Array.forEach (<anonymous>)
    at E._modify (local_collection.js:1459:27)
    at E._modifyAndNotifySync (local_collection.js:781:21)
    at local_collection.js:638:30
    at r._eachPossiblyMatchingDocSync (collection.overwrites.js:27:1)
    at E.update (local_collection.js:632:10)
    at n.update (collection.js:962:31)
    at i.Collection.<computed> [as update] (collection.overwrites.js:79:1)
```

Any hints are appreciated :)

**Comment by sampaiodiego** [comment]
looks like you're using Oplog instead of the default Change Stream for MongoDB realtime data.. is there any particular reason? do you mind sharing this and any other environment variable you're using? tia

**Comment by sampaiodiego** [comment]
interesting.. looks like it something wrong with MongoDB then, but I couldn't spot anything that could be the culprit.. ideally in rocket.chat startup logs you should see a log saying `Using change streams`..

not related, but I didn't find any reference to those env vars you're using (like `MONGODB_REPLICA_SET_MODE` etc).. those are by another MongoDB container called `bitnami/mongodb`..

**Comment by wgaulke** [comment]
@sampaiodiego I checked the startup logs and there is a:

`"hostname":"8be673dd928b","name":"DatabaseWatcher","msg":"Using change streams"}`

Thanks for the hints regarding the env-vars. I'll cleanup my config!

I am closing this ticket, as it looks like it was resolved.
