### ISSUE TITLE
Push notifications for iOS and Android not working

### ISSUE THREAD

**Issue by gierre18** [RocketChat/Rocket.Chat#33875]
### Description:

We are not ble to configure the push notifications.

### Expected behavior:

We should get the push notifications. 

### Actual behavior:

We are not able to configure push notifications as there is no "Connectivity services" area.

### Server Setup Information:

- Version of Rocket.Chat Server:  6.13.0
- License Type: Starter
- Number of Users: 19
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1 
- Mongodb 5.0.24

### Client Setup Information

- Mobile App (iOS and Android official app)
- Operating System: iOS/Android

**Comment by reetp** [comment]
Please don't open an issue because you don't get an instant answer on open.

I presume this is you?

https://open.rocket.chat/channel/support?msg=3JzXXLBhAxFNSFTFW

Push works out of the box.

Please follow up on open as I don't see a bug.

We'll re-open if one is found.
