### ISSUE TITLE
Language Change in Rocket.Chat Causes Crashes or Doesn't Work for Some Languages

### ISSUE THREAD

**Issue by thepiyush-303** [RocketChat/Rocket.Chat#33878]
### Steps to reproduce:

1. Open the Rocket.Chat application.
2. Go to Profile > Preferences > Language.
3. Attempt to change the language to different options.
4. Observe the behavior for each selected language.

 Expected behavior:

The application should:

Correctly update to the selected language without issues.
No crash.
### Actual behavior:

Changing to Hindi does not affect the language displayed.
Selecting Punjabi (India) causes the application to crash.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.13.0-develop
- License Type:
- Number of Users: 1
- Operating System: Ubuntu
- Deployment Method: development
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14
- MongoDB Version: 7.0.5

### Client Setup Information

- Desktop App or Browser Version: FireFox 131.0.2 (64-bit)
- Operating System:

### Additional context

Missing Language Files: It seems that some language files might not be included in the codebase, leading to these issues.
Application Startup Crashes: When I start my application, it constantly crashes. How can I recover it?

### Relevant logs:

`@rocket.chat/meteor:dsv: => App running at: http://localhost:3000/
@rocket.chat/meteor:dsv: I20241104-21:59:35.354(5.5)? [2024-11-04T16:29:34.393Z] WARN (VoIPAsteriskService/126565 on Piyush-Linux): Voip is not enabled. Cant start the service
@rocket.chat/meteor:dsv: I20241104-21:59:35.356(5.5)? [2024-11-04T16:29:34.437Z] USERLVL (Migrations/126565 on Piyush-Linux): Not migrating, already at version 304
@rocket.chat/meteor:dsv: I20241104-21:59:35.357(5.5)? [2024-11-04T16:29:34.485Z] USERLVL (DatabaseWatcher/126565 on Piyush-Linux): Using change streams
@rocket.chat/meteor:dsv: I20241104-21:59:35.357(5.5)? [2024-11-04T16:29:34.886Z] USERLVL (License/126565 on Piyush-Linux): License installed
@rocket.chat/meteor:dsv: I20241104-21:59:35.357(5.5)?     version: "3.0"
@rocket.chat/meteor:dsv: I20241104-21:59:35.357(5.5)?     hash: "ZK1DUncI"
@rocket.chat/meteor:dsv: I20241104-21:59:38.410(5.5)? [2024-11-04T16:29:38.305Z] USERLVL (License/126565 on Piyush-Linux): License installed
@rocket.chat/meteor:dsv: I20241104-21:59:38.411(5.5)?     version: "3.0"
@rocket.chat/meteor:dsv: I20241104-21:59:38.411(5.5)?     hash: "yHloFjMU"
@rocket.chat/meteor:dsv: events.js:377
@rocket.chat/meteor:dsv:       throw er; // Unhandled 'error' event
@rocket.chat/meteor:dsv:       ^
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: Error [ERR_STREAM_WRITE_AFTER_END] [ERR_STREAM_WRITE_AFTER_END]: write after end
@rocket.chat/meteor:dsv:     at new NodeError (internal/errors.js:322:7)
@rocket.chat/meteor:dsv:     at writeAfterEnd (_http_outgoing.js:694:15)
@rocket.chat/meteor:dsv:     at write_ (_http_outgoing.js:706:5)
@rocket.chat/meteor:dsv:     at ServerResponse.write (_http_outgoing.js:687:15)
@rocket.chat/meteor:dsv:     at IncomingMessage.ondata (internal/streams/readable.js:731:22)
@rocket.chat/meteor:dsv:     at IncomingMessage.emit (events.js:400:28)
@rocket.chat/meteor:dsv:     at IncomingMessage.Readable.read (internal/streams/readable.js:504:10)
@rocket.chat/meteor:dsv:     at flow (internal/streams/readable.js:986:34)
@rocket.chat/meteor:dsv:     at resume_ (internal/streams/readable.js:967:3)
@rocket.chat/meteor:dsv:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
@rocket.chat/meteor:dsv: Emitted 'error' event on ServerResponse instance at:
@rocket.chat/meteor:dsv:     at writeAfterEndNT (_http_outgoing.js:753:7)
@rocket.chat/meteor:dsv:     at processTicksAndRejections (internal/process/task_queues.js:83:21) {
@rocket.chat/meteor:dsv:   code: 'ERR_STREAM_WRITE_AFTER_END'
@rocket.chat/meteor:dsv: }
@rocket.chat/meteor:dsv: npm ERR! code ELIFECYCLE
@rocket.chat/meteor:dsv: npm ERR! errno 1
@rocket.chat/meteor:dsv: npm ERR! @rocket.chat/meteor@6.13.0-develop dev: `meteor --exclude-archs "web.browser.legacy, web.cordova"`
@rocket.chat/meteor:dsv: npm ERR! Exit status 1
@rocket.chat/meteor:dsv: npm ERR! 
@rocket.chat/meteor:dsv: npm ERR! Failed at the @rocket.chat/meteor@6.13.0-develop dev script.
@rocket.chat/meteor:dsv: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: npm ERR! A complete log of this run can be found in:
@rocket.chat/meteor:dsv: npm ERR!     /home/thepiyush/.npm/_logs/2024-11-04T16_30_03_353Z-debug.log
@rocket.chat/meteor:dsv: 
@rocket.chat/meteor:dsv: ERROR: command finished with error: command (/home/thepiyush/Desktop/dros/Rocket.Chat/apps/meteor) /tmp/xfs-79a0922c/yarn run dsv exited (1)
@rocket.chat/meteor#dsv: command (/home/thepiyush/Desktop/dros/Rocket.Chat/apps/meteor) /tmp/xfs-79a0922c/yarn run dsv exited (1)

 Tasks:    44 successful, 45 total
Cached:    44 cached, 45 total
  Time:    2m27.827s 
Failed:    @rocket.chat/meteor#dsv

 ERROR  run failed: command  exited (1)
`

**Comment by swastikCommits** [comment]
> @rocket.chat/meteor:dsv: npm ERR! Exit status 1
@rocket.chat/meteor:dsv: npm ERR!
@rocket.chat/meteor:dsv: npm ERR! Failed at the @rocket.chat/[meteor@6.13.0-develop](mailto:meteor@6.13.0-develop) dev script.
@rocket.chat/meteor:dsv: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@rocket.chat/meteor:dsv:
@rocket.chat/meteor:dsv: npm ERR! A complete log of this run can be found in:
@rocket.chat/meteor:dsv: npm ERR! /home/thepiyush/.npm/_logs/2024-11-04T16_30_03_353Z-debug.log
@rocket.chat/meteor:dsv:
@rocket.chat/meteor:dsv: ERROR: command finished with error: command (/home/thepiyush/Desktop/dros/Rocket.Chat/apps/meteor) /tmp/xfs-79a0922c/yarn run dsv exited (1)
@rocket.chat/meteor#dsv: command (/home/thepiyush/Desktop/dros/Rocket.Chat/apps/meteor) /tmp/xfs-79a0922c/yarn run dsv exited (1)

Tasks: 44 successful, 45 total
Cached: 44 cached, 45 total
Time: 2m27.827s
Failed: @rocket.chat/meteor#dsv

ERROR run failed: command exited (1)
`
Here the error log you showed occurs while setting up the codebase locally.

**Comment by JagjeevanAK** [comment]
Hey I reproduced it locally and @thepiyush-303 is correct it does crashes on local machine but not in production if you see on http://open.rocket.chat

**Comment by PurnenduMIshra129th** [comment]
Hi Mentors can i work to fix this issue? Currently i am new to this organization and want to solve this issue and i am already started working on this. So assign this to me it should be useful for me to learn about Rocket.chat .

**Comment by reetp** [comment]
> Hi Mentors can i work to fix this issue? Currently i am new to this organization and want to solve this issue and i am already started working on this. So assign this to me it should be useful for me to learn about Rocket.chat .

No one mentors here, or assigns issues.

https://gist.github.com/reetp/b0ba4e3d0ea2ff48ca9da00a5a647d42

**Comment by reetp** [comment]
> Version of Rocket.Chat Server: 6.13.0-develop

Please test on v7.0 +

This looks more like a support/development issue and you shoudl be asking in 

https://open.rocket.chat/channel/support

**Comment by Abhiborkar7** [comment]
I have tested this on v7.1.0-develop and it is giving the following error:

@rocket.chat/meteor:dsv: ERROR: command finished with error: command (/home/abhishek/Desktop/Repositories/Rocket.Chat/apps/meteor) /tmp/xfs-eb4cec36/yarn run dsv exited (1)
@rocket.chat/meteor#dsv: command (/home/abhishek/Desktop/Repositories/Rocket.Chat/apps/meteor) /tmp/xfs-eb4cec36/yarn run dsv exited (1)

Tasks: 49 successful, 50 total
Cached: 49 cached, 50 total
Time: 1m53.428s
Failed: @rocket.chat/meteor#dsv

ERROR run failed: command exited (1)
