### ISSUE TITLE
OTR Chat is not removed on OTR session end

### ISSUE THREAD

**Issue by fin-tsg** [RocketChat/Rocket.Chat#33909]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Rocky Linux 9.4

### It happens on the web browser too?

No, it just happens on the Desktop app

### Rocket.Chat Desktop App Version

4.1.1

### Rocket.Chat Server Version

7.0.0

### Describe the bug

OTR Chat is not removed on OTR session end.

The OTR message persists on the recipient's client, including between restarts. The message can only be removed if they click Reload in the Help menu.

### How to Reproduce

1. Open a direct message
2. Click the Options menu
3. Click OTR
4. Click Start OTR button
5. Wait for other user to accept
6. Send a message.
7. End the OTR session

### Describe your Expected behavior

The OTR message is removed from both users.

### Are you willing to submit a code contribution?

- [ ] Yes, I am willing to submit a Pull Request!

**Comment by scuciatto** [comment]
We were able to reproduce the issue internally. The team is going to work on it.

**Comment by scuciatto** [comment]
That's how this feature is designed.

The web client still keeps a cache of those sent OTR messages.

**Comment by fin-tsg** [comment]
Hi @scuciatto this was reported against the desktop client. Is it still the case the OTR message should be cached in the desktop client?
