### ISSUE TITLE
When read receipts works and  E2E encryption photos become "whitelabeled " on iOS app ( the latest 4.54.1.68652)

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#33925]
User A sends a E2E encryption photo to user B and the photo display normally until user b read the message Now the  read receipts works and the E2E encryption photo becomes "whitelabel" on both user's screen (iOS APP)
see the photo below
![image](https://github.com/user-attachments/assets/26bea621-c8ee-49ae-a173-9dce2ad49d49)

As long as read receipts work and photos in end-to-end encryption become ‘whitelabeled’. 
This issue exists since the E2E encryption of files became available 

Expected behavior:
E2E encryption Photos can display normally with read receipts enabled

Actual behavior:
Whitelabeled 

One more bug on iOS app.
E2E encryption photos can be saved and E2E encryption videos can't be saved 

RC server: 6.13.0
iOS app: 4.54.1.68652 (the latest)

**Comment by reetp** [comment]
If it's a react app issue please close it here and re-open in the ReactNative repo.

https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by lovekyleman** [comment]
> If it's a react app issue please close it here and re-open in the ReactNative repo.
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative

Ok. Thanks
