### ISSUE TITLE
language options list is not sorted correctly

### ISSUE THREAD

**Issue by thepiyush-303** [RocketChat/Rocket.Chat#33934]
### Steps to reproduce:

1. Go to user Preferences
2. check : localization -> language list 

### Expected behavior:

language list should be sorted

### Actual behavior:

 not sorted

### Server Setup Information:

- Version of Rocket.Chat Server: 6.13.0-develop
- License Type:
- Number of Users: 1
- Operating System: linux
- Deployment Method: development
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14
- MongoDB Version: 7

### Client Setup Information

- Desktop App or Browser Version: firfox 131.0.2 (64-bit)

- Operating System: ubuntu

### Additional context

[Screencast from 2024-11-07 16-01-07.webm](https://github.com/user-attachments/assets/f37e6cf0-2401-46f8-86e0-db641941b1ef)

**Comment by casalsgh** [comment]
Asking internal team for reviews
