### ISSUE TITLE
nginx reverse proxy fails to load tap-i18n json

### ISSUE THREAD

**Issue by leoniscsem** [RocketChat/Rocket.Chat#3395]
When accessing Rocket.Chat through an nginx reverse proxy, the app fails to load `tap-i18n/de.json`. There is no difference in using the `Docker image` or native installation with `node.js`. When accessing through `IP:PORT`, the file loads fine.

Browser console output: `XHR failed loading: GET "https://chat.domain.com/tap-i18n/de.json" .`

**Environment:**
- Rocket.Chat version: (Docker image: **rocketchat/rocket.chat:latest**)
- Ubuntu 14.04
- nginx 1.10
- Chromium (latest)

**nginx.conf**

```
upstream backend {
    server 10.0.0.10:3000;
}
server {
   listen         80;
   server_name    chat.domain.com;
   return         301 https://$server_name$request_uri;

}

server {
    listen 443 ssl http2;
    server_name chat.domain.com;
    ssl_certificate /etc/letsencrypt/live/chat.domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.domain.com/privkey.pem;
    keepalive_timeout 60;

    error_log /var/log/nginx/rocketchat.access.log;

    location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;

    # increase proxy buffer to handle some requests
        proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    # force timeouts if the backend dies
    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
    }
}
```

Adding a higher timeout does not have a real impact, but the server at least doesn't give me a 502 error.

**Comment by leoniscsem** [comment]
Noone else experiences this?

![tumbleweed](https://cloud.githubusercontent.com/assets/6514726/15809230/acf1a8dc-2b8c-11e6-96f9-ed30b063c041.gif)

**Comment by michaudg** [comment]
Same problem here with version 0.36. Removing "http2" from the listen line fix the bug.

**Comment by michaudg** [comment]
Upgrading nginx to 1.11.3 solved the problem for me.

**Comment by gerbsen** [comment]
Worked for me too! I think this can be closed.

**Comment by reetp** [comment]
@rocket-cat close

Please reopen if you have further issues
