### ISSUE TITLE
[gitsy] unable to receive notifications from Gitlab

### ISSUE THREAD

**Issue by CrystalMethod** [RocketChat/Rocket.Chat#3397]
Rocket.Chat version: 0.31
Gitlab version: 8.7.6

In Gitlab I added system wide as well as project based web hooks. Gitsy commands work, but I see no notification from Gitlab. I can find the following exception in the logs. 

```
hubot_1 | 2016-05-29T19:42:07.668393748Z [Sun May 29 2016 19:42:07 GMT+0000 (UTC)] INFO Sending Message To Room: #GENERAL
hubot_1 | 2016-05-29T19:42:07.668496447Z [Sun May 29 2016 19:42:07 GMT+0000 (UTC)] INFO Looking up Room ID for: #GENERAL
```

```
Exception while invoking method 'getRoomIdByNameOrId' TypeError: Cannot read property 'usernames' of undefined
     at [object Object].Meteor.methods.getRoomIdByNameOrId (server/methods/getRoomIdByNameOrId.coffee:8:10)
     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
     at livedata_server.js:708:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at livedata_server.js:706:40
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at livedata_server.js:704:46
     at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
     at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13) 
```

**Comment by pasmon** [comment]
Have you set the rooms either in Hubot environment or in Gitlab hook? I think you should get rid of the hash character (#) in room names, I tripped on that as well at some point.

**Comment by geekgonecrazy** [comment]
I believe you need to make sure your bot user has the bot role assigned to it.

**Comment by lobocode** [comment]
I've a simple solution for this in shellscript:

Dependency : rsstail (apt-get install rsstail).
```bash
#!/bin/bash

# Repolist
repo="urls"

# Emoji 
emoji=":robot:"

# channel hook
hook="Your webhook url"

PYTHONIOENCODING=utf8 rsstail --nofail -n 1 -i 2 -l -u -a $repo | while read q
do
	command="$(curl -X POST --data-urlencode 'payload={"icon_emoji":"'"$emoji"'","text":"@all: Gitlab Commits: ","attachments":[{"text":"'"$q"'","color":"#764FA5"}]}' $hook)"

done

```

It works perfectly for me. Furthermore, it serves to read RSS in general. The gitlab has a RSS for each repository or branch.

**Comment by MartinSchoeler** [comment]
Will be closing this issue due lack of updates

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
