### ISSUE TITLE
The "Create" button does not work

### ISSUE THREAD

**Issue by mirina47** [RocketChat/Rocket.Chat#33970]
I just created an account following the instructions and also watched a YouTube video. Other people had the opportunity to create new channels immediately after registration, but for some reason the "Create" button does not work for me. It is there, but it is impossible to click on it when you hover the cursor over it. I've tried this in the Windows app and in the web version.

**Comment by allenhack638** [comment]
> I just created an account following the instructions and also watched a YouTube video. Other people had the opportunity to create new channels immediately after registration, but for some reason the "Create" button does not work for me. It is there, but it is impossible to click on it when you hover the cursor over it. I've tried this in the Windows app and in the web version.

Could you please share an image or a video of the user interface where the 'Create' button is unresponsive? This will help us investigate and resolve the issue more efficiently.[
![Screenshot 2024-11-15 232601](https://github.com/user-attachments/assets/71fa8184-c39c-47bb-9f5e-b4a005796d37)
](url)

**Comment by mirina47** [comment]
![image](https://github.com/user-attachments/assets/6f0833d1-4eac-492a-8a6f-f1ce0f70de6f)
![image](https://github.com/user-attachments/assets/0d49850d-691a-4cfd-ba78-0bab41f1dd60)

**Comment by mirina47** [comment]
> > I just created an account following the instructions and also watched a YouTube video. Other people had the opportunity to create new channels immediately after registration, but for some reason the "Create" button does not work for me. It is there, but it is impossible to click on it when you hover the cursor over it. I've tried this in the Windows app and in the web version.
> 
> Could you please share an image or a video of the user interface where the 'Create' button is unresponsive? This will help us investigate and resolve the issue more efficiently.[ ![Screenshot 2024-11-15 232601](https://private-user-images.githubusercontent.com/54641339/386710369-71fa8184-c39c-47bb-9f5e-b4a005796d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3Mzc3NTUsIm5iZiI6MTczMTczNzQ1NSwicGF0aCI6Ii81NDY0MTMzOS8zODY3MTAzNjktNzFmYTgxODQtYzM5Yy00N2JiLTlmNWUtYjRhMDA1Nzk2ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYjdkYjllMjY2NTA1MWNlMWNlNjQwNmY3ZjMyNTExZmI2M2JjMjQxOGViYmM0NWY1YzUzMjRkODczNDU2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GN7aCFng53tXHTDlzMGCY5EzFghROJ50FwgGfM2H9Jk) ](url)

![image](https://github.com/user-attachments/assets/73b081ee-4425-4057-af7f-cbf98b6d60b0)
![image](https://github.com/user-attachments/assets/7f5b4fa6-a796-4dc5-b93c-895376cf3521)

**Comment by allenhack638** [comment]
> > > I just created an account following the instructions and also watched a YouTube video. Other people had the opportunity to create new channels immediately after registration, but for some reason the "Create" button does not work for me. It is there, but it is impossible to click on it when you hover the cursor over it. I've tried this in the Windows app and in the web version.
> > 
> > 
> > Could you please share an image or a video of the user interface where the 'Create' button is unresponsive? This will help us investigate and resolve the issue more efficiently.[ ![Screenshot 2024-11-15 232601](https://private-user-images.githubusercontent.com/54641339/386710369-71fa8184-c39c-47bb-9f5e-b4a005796d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3Mzc3NTUsIm5iZiI6MTczMTczNzQ1NSwicGF0aCI6Ii81NDY0MTMzOS8zODY3MTAzNjktNzFmYTgxODQtYzM5Yy00N2JiLTlmNWUtYjRhMDA1Nzk2ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDA2MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYjdkYjllMjY2NTA1MWNlMWNlNjQwNmY3ZjMyNTExZmI2M2JjMjQxOGViYmM0NWY1YzUzMjRkODczNDU2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GN7aCFng53tXHTDlzMGCY5EzFghROJ50FwgGfM2H9Jk) ](url)
> 
> ![image](https://private-user-images.githubusercontent.com/115398948/386824001-73b081ee-4425-4057-af7f-cbf98b6d60b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTk0MjcsIm5iZiI6MTczMTkxOTEyNywicGF0aCI6Ii8xMTUzOTg5NDgvMzg2ODI0MDAxLTczYjA4MWVlLTQ0MjUtNDA1Ny1hZjdmLWNiZjk4YjZkNjBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwODM4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDJmMDk0OGFmMmFjYzlmYmQ1MTRjZWJkZTYzZGQxOGI2MGYxZGE0MmYyMTQ0ZWI5OGUzOGM3YTNiNjYyYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z6gOYLzvamHb3IDXI64RCjpUT99Q9aPYv8E50ZFjgC0) ![image](https://private-user-images.githubusercontent.com/115398948/386824013-7f5b4fa6-a796-4dc5-b93c-895376cf3521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTk0MjcsIm5iZiI6MTczMTkxOTEyNywicGF0aCI6Ii8xMTUzOTg5NDgvMzg2ODI0MDEzLTdmNWI0ZmE2LWE3OTYtNGRjNS1iOTNjLTg5NTM3NmNmMzUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwODM4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGNjMGQxODI4MTM2Mjk4YmU4MjVkODRlMWFlZTMyZDM4MDk1NWM4ZTc0NjY5MDg5YmUxMTA5ZTRhN2NmZGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pHS4rsh-C4XVD8UABg5PJjo_2MiK071K0LgePfcssSM)

You need to navigate to the Permissions tab in the workspace and specify which roles are allowed to create channels. Once enabled, the 'Create Channel' button will become available.

**Comment by MartinSchoeler** [comment]
Yes this is a permission issue, you probably don't have permission to create channels, please contact the server's admin and request permission, if you are on open.rocket.chat, the permission is disabled but for a select few.

Thanks!
