### ISSUE TITLE
[feat] Filter for Hidden Chats

### ISSUE THREAD

**Issue by Arslan2214** [RocketChat/Rocket.Chat#33974]
### Description: 
There is no filter option for separating hidden chats form other, Why not to add an option that perform this functionality efficiently.

### Steps to reproduce:

1. Go to **Filter Chat option**
2. It should be able to filter out all hidden chats

### Expected behavior:

Just to filter out all the hidden chats that are not usually visible.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- License Type:
- Number of Users: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Brave (latest)
- Operating System: Windows 10

**Comment by reetp** [comment]
Please fill out your server details.

If you test on the latest code and the issue exists then open an issue in the feature-requests repo.

https://github.com/RocketChat/feature-requests

Thanks.
