### ISSUE TITLE
No message visible when uploading file on E2EE channel

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#33973]
### Description:

We have issues with file uploads on both files encryption enabled and files encryption disabled but this concerns latter case.

It is possible to upload files (PNG) into E2EE channels but the message does not get shown.

### Steps to reproduce:

1. `Admin -> Settings -> End-to-end encryption`: Enable E2EE. Disable `Encrypt files`.
2. `Admin -> Settings -> File Upload`: Set `Accepted Media Types` and `Blocked media types` both blank.
3. `Admin -> Settings -> File Upload`: Set as `Storage Type: FileSystem` and under `File System` use a system path that rocketchat service account has permissions into.
4. As an E2EE-enabled user create an E2E-encrypted private channel
5. Upload a png image file to the channel

### Expected behavior:

You should see the message and embedded image as usual on the channel

### Actual behavior:
Modal(?) works ok:
![Screenshot from 2024-11-16 10-48-23](https://github.com/user-attachments/assets/f792d6ed-3439-490d-b42d-96e5ea46412b)

After send/enter you get an error message that you are not allowed to upload file. Original message does not appear.
![Screenshot from 2024-11-16 10-48-31](https://github.com/user-attachments/assets/4f1a99c3-e0b3-4aa9-a274-c6e804a0e905)

The file upload has actually succeeded, as you can find the file under `Files` on the channel. Only message about it is missing.
![Screenshot from 2024-11-16 10-54-04](https://github.com/user-attachments/assets/59e624ef-a3f4-44f2-9993-a02c31d9f397)

Other members on the channel don't see any message but the file upload has succeeded, as they too can find the file under the `Files` view.
![Screenshot from 2024-11-16 11-24-00](https://github.com/user-attachments/assets/96fe336c-f00f-4267-8af2-ec7f023095cd)

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Enterprise
- Number of Users: 500+
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: Yes
- NodeJS Version: 20.17.0
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version: Latest Chrome and Firefox running in regular mode. Same issue happens in browser incognito/private mode too, so it is not web client cache acting up.
- Operating System: Linux

### Additional context

For the record if you enable `Encrypt files` in the first step, nothing happens when you press send or enter in the file upload modal. The modal does not close at all (unless you press X, which then cancels the operation).

I can make these both issues as separate support cases unless they are already known by the devs.

**Comment by reetp** [comment]
Have you opened a support issue?

If not you should, and refer to this. You will get much higher priority.

Remember github is not their primary workspace - it is the last thing to get updated/looked at.

Thanks.

**Comment by Gummikavalier** [comment]
@reetp Not yet but I did so now. Ticket number `#99816`.

**Comment by Gummikavalier** [comment]
Ok, this unencrypted files in encrypted channels was resolved by support. I had really wooden eye when looking at admin settings, or alternatively I had a browser cache issue.

You only have to switch this on to allow unencrypted files on encrypted channels without error messages. It works as designed if you don't; then you can upload the file but you cannot send the message part along with it.

![Screenshot from 2024-11-26 07-50-57](https://github.com/user-attachments/assets/790d26ea-555e-46c7-96fb-264ec1a6bad7)
