### ISSUE TITLE
Want to place html code over Chatrooms in fix position

### ISSUE THREAD

**Issue by Buzzele** [RocketChat/Rocket.Chat#3398]
Hi,

Is it able to set integrate a own html code at a fixed position over all chatrooms? Have search in this repro and find some files like room.html. But I have deployed Rocketchat and have no access to such files. How can I add own HTML-Codes anyway?

Thanks and Best Regards!

**Comment by klatys** [comment]
Hi @Buzzele what exactly would you like to have in that code? Would maybe setting room topic do? You can also use markdown there :)
![room topic](https://www.dropbox.com/s/5qxx5zo11a6qycj/Screenshot%202016-06-10%2020.07.23.png?dl=1)

**Comment by Buzzele** [comment]
Hi klatys and thanks for the reply.

I want to have html/css boxes, in some cirbumstances with javascript inside  :(

I tried it with your proposal. Unfortunately, the channel name disappears when I write several lines of code. He is pushed upwards causing by the topic lines.

Then I tried to get a popup with Javascript, what wood be also a good solution but it seems, javascript is not supported in the Topic-Name, some html tags, what I tried, does.

Is it possible to set a new point in the right side menu? so that I can place the box in this area?

Sorry for my bad english.

Best Regards

**Comment by klatys** [comment]
And you wan't that code block to be different for each room, is that correct? In that case that is not possible (yet) and this should be considered as a feature request.
Otherwise (same code in every room) you could edit the room template (as you mentioned above ^^) - how is your instance deployed (why don't you have access to the files?).

**Comment by Buzzele** [comment]
If it is possible to edit the templates and if it has to be the same code (not different for each room), then this would be ok for the next weeks ;) But I dont have access to all files which I can see in this repository. I deployed rocket.chat with this steps: https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
