### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by david-strejc** [RocketChat/Rocket.Chat#3399]
Is there any problem with week release cycle? Or I just missed something? For us is Rocket Chat the best Open Source project out there - so I hope it will never die as other projects did.

Is there any way I can help you with? Unfortunately I am former DevOps and infrastructure engineer - so my Javascript and node.js is equal to cat or dog writing code ;-) 

I can help you with backend infrastructures and can provide this project my skills in DevOps. 

Anyway many thanks for this great project. It was my dream for 10 years. It is really ultimate - and when it will have all those planned and in progress features I will dance magic dance around fire!

**Comment by marceloschmidt** [comment]
Hello @david-strejc ! No problems at all! Last week we were busy at OSCON, in TX, so we did not create a new release that week. Thank you for your offer, we welcome you to go to https://demo.rocket.chat/channel/contributors and hang out there, we have quite a few devs there willing to help and be helped.
Cheers.
