### ISSUE TITLE
Mentions and Emojis not working in input of edit message

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#34]

**Comment by matthewshirley** [comment]
Basically doing what chatWindowDashboard does but changed to the correct class. 

This is the best way I could see doing unless there is a common file these helpers can be placed in?

**Comment by engelgabriel** [comment]
What do you think @rodrigok ?
Is there is a common file these helpers can be placed in? 
Maybe a global helper?

**Comment by rodrigok** [comment]
This popups can be moved to a separated template passing only the input selector to configure.

I can accept this PR and make this changes, but later today only.
