### ISSUE TITLE
Messages not displayed on re-login using room URL path

### ISSUE THREAD

**Issue by rwakida** [RocketChat/Rocket.Chat#340]
To replicate:
1. logout and go to /home URL path.  Refresh screen
2. login
3. select a channel (URL path should update with path)
4. logout
5. login again (see blank blue screen from RocketChat/Rocket.Chat#339)
6. logout
7. login.  SideNav appears, but loading rocket ship image is displayed in message area.   No error on server/client console.
8. Refresh page and everything works.

**Comment by marceloschmidt** [comment]
Fixed
