### ISSUE TITLE
binding to a different port

### ISSUE THREAD

**Issue by CollinsCoding** [RocketChat/Rocket.Chat#3400]
I am running docker-compose on a ubuntu droplet in digital ocean and with the current setup I am able to access the rocket.chat instance on www.mywebsite.com:3000 but in order to be able to access it on www.mywebsite.com I need to reconfigure the port to port 80, is there a single place I can make this reconfiguration?

There seems to be a lot of hardcoded port 3000 references so I am not sure if there is an official approach to this issue?

Appreciate any guidance

**Comment by MaxVonk** [comment]
Add this to your Ngnix, rocketchat.conf

   location / {
      proxy_http_version 1.1;
      client_max_body_size 50M;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Frame-Options SAMEORIGIN;
      proxy_pass http://192.168.1.243:3000;

**Comment by CollinsCoding** [comment]
thank you, this worked!
