### ISSUE TITLE
SMTP Send Test Mail not working - Unrecognized authentication type

### ISSUE THREAD

**Issue by malkar20** [RocketChat/Rocket.Chat#3401]
Your Rocket.Chat version: 0.31.0

Hello,

When trying to send a test mail after configuring mail server, I get "internal server error" on the GUI and the following error in logs:

```
Exception while invoking method 'sendSMTPTestEmail' AuthError: Invalid login - 504 5.7.4 Unrecognized authentication type
    at Object.Future.wait (/home/rocketchat/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:86:1)
    at Object.Email.send (packages/email/email.js:185:1)
    at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)
    at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:23:26)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

I am running rocketchat on ubuntu 16.04 LTS. I performed a manual installation following published instructions, I am running an MS Exchange 2010 Server, telnet mail server on port 25 works, my SMTP settings in rocket chat are as follows:

Host: 192.168.200.212
port: 25
username: Rocket.Chat , I also tried mydomain\rocket.chat and rocket.chat@mydomain.com
from email: rocket.chat@mydomain.com

**Comment by malkar20** [comment]
Hello,

Ive tried reverting back to ubuntu 14.04 on a fresh installation - some previous strange behavior disappeared however email problem still present

**Comment by nikatnite** [comment]
Hi Malkar,

I also received the same error.   In my case, I did not have a receive connector in exchange 2010 set up that would accept connection to that server.

I created a new receive connector (you could just modify an existing one if you'd like) for Rocketchat and all was well.

**Comment by reetp** [comment]
This hasn't been commented on for some long while and Rocket is now on version 0.70.x so a lot has changed.

It is most likely a configuration issue - there are various threads around about configuring Rocket with MS Exchange. Please see the forums https://forums.rocket.chat/ or chat https://open.rocket.chat for support on this.

Closing notabug. Please reopen if you still experience issues with Rocket itself and provide full logs.

**Comment by reetp** [comment]
@rocket-cat close
