### ISSUE TITLE
Self logo not able to show on android version of rocket chat

### ISSUE THREAD

**Issue by istanleyyaw** [RocketChat/Rocket.Chat#3402]
Your Rocket.Chat version: (make sure you are running the latest)
0.31
It have no issue on website and desktop application. iOS not sure.

**Comment by geekgonecrazy** [comment]
Can you illustrate with a picture or something?

**Comment by istanleyyaw** [comment]
![screenshot_20160601-072833](https://cloud.githubusercontent.com/assets/17511056/15693772/bd2892ee-27ca-11e6-867e-2d9bebb43e1a.jpg)
![screenshot_20160601-072730](https://cloud.githubusercontent.com/assets/17511056/15693775/c4f494be-27ca-11e6-85ad-e856f23a9b83.jpg)
on the same phone, one is use cheome browser, one is using the rocket chat application

**Comment by geekgonecrazy** [comment]
ah! ok how is the image being included?  By a link?

**Comment by istanleyyaw** [comment]
uploaded to the server.

**Comment by geekgonecrazy** [comment]
@istanleyyaw how was it uploaded?  through the assets section?  Need a bit more to go on to be able to figure out why this is happening

**Comment by istanleyyaw** [comment]
yah. using the administration function. i will explorer more to give u what
is the difference between app logo and web logo. btw, will the logo be
refresh from server each time app.start or only the first time iT sync file
difference?

**Comment by geekgonecrazy** [comment]
only when you click the update that pops up in the app.

**Comment by QuintusWillemse** [comment]
We have this same issue. Is there already a way to solve this?

**Comment by geekgonecrazy** [comment]
@QuintusWillemse how did you upload the image, and how did you add the image to the sidebar?

**Comment by QuintusWillemse** [comment]
Hi, I just now see that this is about the Android app. We had the same problem with the iPhone app. I've uploaded the image in the environment via the normal browser. Expecting that the images that we upload in Assets would also be used in the App.

**Comment by QuintusWillemse** [comment]
I do have to say that we're running the Rocket Chat version of April 2016 on our server

**Comment by geekgonecrazy** [comment]
Which release in April?  We had several releases of Rocket.Chat server in April.  
* 0.25.0 - April 4th
* 0.26.0 - April 11th
* 0.27.0 - April 18th
* 0.28.0 - April 25th

You can find out your servers version by going to Administration->Info or going to: http://yourserver/api/info

**Comment by QuintusWillemse** [comment]
0.28.0 - April 25th

**Comment by geekgonecrazy** [comment]
A quick and easy solution to this... would be to base64 encode your image and put it there in the sidebar.  But I do see where its happening.  Some reason its not hitting the cache.  Alternatively... its possible if you use a relative link instead of a full link it might work.

**Comment by QuintusWillemse** [comment]
Ok, I'll try this, thank you Aaron!

**Comment by sduensin** [comment]
This still happens with an out-of-the-box snap install with 0.48.2.  I changed nothing.  Installed it, fired it up, visited with the Android client.

**Comment by LeDistordu** [comment]
Still no solution

**Comment by engelgabriel** [comment]
Can you please test with version `0.49.3`?

**Comment by tbnobody** [comment]
I am having the same issue with the latest iOS app and a rocket.chat default installation. I did not change any asset settings but the logo is not shown in the app.

**Comment by jszaszvari** [comment]
Still the same issue here on iOS and Android 

<img width="290" alt="screen shot 2017-03-04 at 4 41 05 am" src="https://cloud.githubusercontent.com/assets/872463/23562014/d1676af2-0094-11e7-9541-4d8d7a865bc5.png">

**Comment by reetp** [comment]
Not sure but is this related?

https://github.com/RocketChat/Rocket.Chat/issues/3387

I still have the issue on 0.52 with the stock logo. Appears in a browser but not in the Android app.

**Comment by lewyg** [comment]
Try to add this in Layout>Custom CSS

> .side-nav .footer img {
> content:url("/assets/logo.png");
> }

It works for me(for .png logo)

**Comment by ccfang** [comment]
@lewyg Also works for me for .png logo, thanks a lot. 

Test on Android and iOS app built from Cordova, Rocket.Chat version `0.57.1`
