### ISSUE TITLE
Android version not able to download or preview docx word file

### ISSUE THREAD

**Issue by istanleyyaw** [RocketChat/Rocket.Chat#3403]
Your Rocket.Chat version: (make sure you are running the latest)
0.31
When click it on web version it will download, but in android version it will show loading icon forever and no more action.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
