### ISSUE TITLE
No Placeholder for Password Field in Login Form

### ISSUE THREAD

**Issue by thepiyush-303** [RocketChat/Rocket.Chat#34032]
Version of Rocket.Chat Server: 7.1.0
Operating System: ubuntu
Browser: FireFox
![Screenshot from 2024-11-20 18-39-21](https://github.com/user-attachments/assets/3ef55f84-07aa-4dce-b9a7-bd85158f723c)

**Comment by TheAnkushAgarwal** [comment]
please assign this issue to me

**Comment by adityajha2005** [comment]
hey, I've fixed the issue, can you please assign the issue to me

**Comment by reetp** [comment]
Please note:

1. No one EVER assigns issues.
2. If there is already a PR open then please don't waste your time and duplicate effort.

Sit and watch what happens and if the original PR gets accepted.

Have a read here:

https://gist.github.com/reetp/b0ba4e3d0ea2ff48ca9da00a5a647d42#file-developers-readme-md

**Comment by scuciatto** [comment]
This is expected. When we develop the new login form, the design team didn't add placeholder on the password field on purpose.
