### ISSUE TITLE
Auto hide the right menu on mobile layout like the left menu

### ISSUE THREAD

**Issue by istanleyyaw** [RocketChat/Rocket.Chat#3404]
Your Rocket.Chat version: (make sure you are running the latest)
0.31
As the space is quite limited on mobile version, better to hide the right menu to display more content.

**Comment by mrplow** [comment]
Agreed.
Hadn't the channel name go all the way to the right with a menu bottom that opens the right menu

**Comment by geekgonecrazy** [comment]
Many have suggested this... A cool idea.. but how do you propose being able to show the panel bar?

**Comment by istanleyyaw** [comment]
like what currently slack or mattermost did?

**Comment by mrplow** [comment]
This is how i was picturing it.
Extend the channel title bar on the top of the screen all the way to the right.
Add an arrow pointing right on the top right inside the top bar.
Pressing the arrow unhides the right bar, this also reverses the direction of the top right arrow.
Pressing the arrow again hides the right menu and reverses the arrow again.

**Comment by reetp** [comment]
There have been substantial changes to the server and mobile versions since this issue was opened.

Please reopen in the correct client section if this is still an issue

**Comment by reetp** [comment]
@rocket-cat close
