### ISSUE TITLE
Store message in local storage instead of load it from server each time to open it quick.

### ISSUE THREAD

**Issue by istanleyyaw** [RocketChat/Rocket.Chat#3405]
Your Rocket.Chat version: (make sure you are running the latest)
Even offline, still able to check local message, this is extremely useful for native app. And just need to load new message since last received message time stored locally.

**Comment by marceloschmidt** [comment]
What about the limitation for how much you can store in localStorage?

**Comment by istanleyyaw** [comment]
10mb size limitation for localstorage, good enough for store recent messge, at least each time when user open one conversation, it will not show the loading page, instead it show recent message directly and load and append new message at the end once got new message from server

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
