### ISSUE TITLE
rocketchat links on mobile devices should be offered to open in-app

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat#34065]
### Description:

When i send someone a link to a conversation, threat, channel  on my rocketchat instance and a mobile browser is used to open that link i can login directly in  a browser without being offered/asked if i might have an APP installed. (if this is a dublicate, sorry i couldnt find it)

### Steps to reproduce:

1.  Send direct link
2.  open link on mobile device
3.  

### Expected behavior:

a banner or popup would be shown and ask me if i want to open the link in the app.

### Actual behavior:

i get promted to login in the browser

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- License Type: one where we get push notifications for several users
- Number of Users: +500
- Operating System: debian
- Deployment Method:  maybe apt?
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: -
- MongoDB Version:-

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by reetp** [comment]
> (Btw, feature requests belong in https://github.com/RocketChat/feature-requests )

Or in the react repo here:

https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by b90g** [comment]
thanks will head over to https://github.com/RocketChat/feature-requests

as for react native: no, the server is responsible to hand out what happens when i click on a link to chat when i am not logged in.
