### ISSUE TITLE
[improvement] mobile layout left menu

### ISSUE THREAD

**Issue by istanleyyaw** [RocketChat/Rocket.Chat#3410]
Your Rocket.Chat version: (make sure you are running the latest)
0.31

Suggest that for the mobile version layout, when the left menu popup, click on any place on the main window should triger the left menu hide instead of click <- button only. that would be more make sense for the UI.

**Comment by soenkef** [comment]
+1

**Comment by geekgonecrazy** [comment]
Dupe of #3351
