### ISSUE TITLE
read receipts?

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#3411]
Your Rocket.Chat version: (make sure you are running the latest) 31

Is there any way to tell if a Rocket.Chat message has actually been read by the recipient?

**Comment by msamoylov** [comment]
+1. I assume I should create a server method and extend `RocketChat.models.Messages` for that?

**Comment by soenkef** [comment]
+1

**Comment by thetacobean** [comment]
+1 This is definitely a needed feature.

**Comment by alexandrecanuto** [comment]
+1

**Comment by hughlroberts** [comment]
Would really like this feature...

**Comment by rolies106** [comment]
Any update on this? I really waiting for this feature...

**Comment by sampaiodiego** [comment]
just to let you guys know, we're planning to work on this for the upcoming release.

we'll implement it as the following:

- the feature will be turned off by default
- server admin will be able to chose to:
  - show if a message was read by everyone on the room it was sent
  - show the time each person read a message

should the read receipt be restricted to the sender only?

**Comment by soenkef** [comment]
Hi! 

Thank you!

I think that this feature should be restricted only to the sender!

**Comment by RichardFoxworthy** [comment]
I think its better for everyone who has access to a channel to also be able to see how widely a message in that channel has been read ...  there should be no privacy issue because they already have access to that message. I think this logic applies to both DMs and to channels. 

This model works well in Riot, I think it will also be good for RC

This approach could support some clever tricks for bots - eg bot could repost important messages to people who have not read them

**Comment by GoetheG** [comment]
Shouldn't this issue be merged with all the other same isses? Cause this error still occurs with the latest version.
#4957
#15656
#15484

**Comment by sampaiodiego** [comment]
sorry @GoetheG what you mean by merge those issues? Also I didn't get what issue you're still having.
