### ISSUE TITLE
Feature Request: onUserLogin Event for Apps Engine

### ISSUE THREAD

**Issue by XHorizonX** [RocketChat/Rocket.Chat#34115]
**Problem**
Currently, there is no way to capture user login events in Rocket.Chat Apps Engine. For systems that require additional actions during user logins—such as checking if a user is deactivated and activating them automatically—this functionality is essential. Specifically, during a login attempt, it is necessary to detect whether the user is deactivated in Rocket.Chat and automatically activate them if needed, allowing them to proceed with their login seamlessly.

**Proposed Solution**
Add a new event, onUserLogin, to the Apps Engine. This event should trigger whenever a user attempts to log in successfully. The event should provide access to the user's details (e.g., username, ID, and active status). If the user is found to be deactivated in Rocket.Chat, this event would allow the application to automatically activate the user and finalize the login process.

**Use Cases**
Automatically activating deactivated users during their login attempt, allowing a seamless experience.
Logging user login activities, including both successful and failed login attempts, for auditing purposes.
Triggering custom workflows, notifications, or additional actions upon user login events.

**Benefits**
This feature would greatly enhance the extensibility of Rocket.Chat by allowing developers to handle user login workflows dynamically. It would make Rocket.Chat more adaptable to environments where systems often require automatic user activation and custom workflows tied to login events.

**Comment by reetp** [comment]
Please open this in either the apps engine repo or feature reqjests.

Thanks.
