### ISSUE TITLE
Create user from mongo

### ISSUE THREAD

**Issue by dohrix** [RocketChat/Rocket.Chat#3412]
Version 0.32

I have a script to create users from mongodb directly,  users can log in and update theire profils or create direct discussion but are invisible in the admin users list and can't be added to the channels.

I tried to restart rocketchat and mongo without success.

I there any solution or do i have to only create by the admin panel?

**Comment by geekgonecrazy** [comment]
@dohrix you would likely want to do so via a rest api not the database directly

**Comment by dohrix** [comment]
I searched into the documentation but i didn't found how to manage users, i'll search again, thx ;)

**Comment by ashish157** [comment]
@geekgonecrazy @dohrix 
I too need a REST API to create users from my client. Unfotunately on search I found nothing related to it in the documents. 
Can you please provide an example ?

Rocket chat 0.37.1
Ubuntu 14.04.5 LTS
