### ISSUE TITLE
Group video call mute one person

### ISSUE THREAD

**Issue by mhlavac** [RocketChat/Rocket.Chat#3414]
It would be great to be able to mute one person only.

We are doing calls everyday and some of our call participants sit next to each other. They need to mute each other otherwise they can hear themselves.

**Comment by Sing-Li** [comment]
New solution testing this week.

On https://demo.rocket.chat

When you are in a Direct Message or Private Group. You will notice a new video button on the toolbar , just click it anytime to start a video conference with all those in the room

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
