### ISSUE TITLE
Channel intercom

### ISSUE THREAD

**Issue by mhlavac** [RocketChat/Rocket.Chat#3415]
Would it be possible to do something like an intercom for channel.

Everyone who joins channel would listen automatically and if button is pressed I could speak to everyone. This would be great if I need to capture someone attention or I need to solve a problem really quickly.

We are using rocket.chat mainly for development discussions and to be able to yell that production server is down would be a big help ;-)

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
