### ISSUE TITLE
Put the emoji button to the right side menu bar instead

### ISSUE THREAD

**Issue by istanleyyaw** [RocketChat/Rocket.Chat#3417]
Your Rocket.Chat version: (make sure you are running the latest)
0.31
benefit
1. much more space to display and select the emoji
2. can have big size emoji
3. much easier to choose on mobile version.
4. can avoid keyboard popup on mobile version if choose to direct post once choose the emoji.

**Comment by geekgonecrazy** [comment]
Can you illustrate this in some way?  I don't completely understand

**Comment by istanleyyaw** [comment]
![screenshot_20160601-073307](https://cloud.githubusercontent.com/assets/17511056/15693844/63c11f4a-27cb-11e6-82ed-9a601f085116.png)

this is what it shows currently,(bottom side is keyboard actually). as it auto focus on the search emoji textbox. 
what if put the emoji button on the panel bar together with info,  search button, when click on it, right panel popup with all the emoji display on the right panel. more space to show and select emoji on both desktop and mobile version.

**Comment by istanleyyaw** [comment]
or when the emoji popup, hide the keyboard, and show the emoji keyboard at the same location of android keyboard. (and do we really need search function in emoji keyboard?)

**Comment by geekgonecrazy** [comment]
Ah I think I get what you mean.  Yeah... we actually have a pull request open that moves it to a better location: #3229

**Comment by marceloschmidt** [comment]
@thiagosanchz please act on this one

**Comment by vynmera** [comment]
This no longer makes sense with our design change, as the right-side bar icons are gone and moved to the top right.
