### ISSUE TITLE
Disabling the "User has joined" commentary

### ISSUE THREAD

**Issue by Jack-Collins** [RocketChat/Rocket.Chat#3418]
Is there a way to disable this as I think for rooms with a higher traffic it becomes overkill?

**Comment by mrplow** [comment]
I would also be nice to be able to disable this while running imports

**Comment by lunitic** [comment]
RIght now i launched a server which getting about 100 users per day.. The "User has joined" gets flooded into the default channel.

I found in /rocketchat-lib/server/methods/joinDefaultChannels.coffee


		```
		# Insert user joined message
				if not silenced
					RocketChat.models.Messages.createUserJoinWithRoomIdAndUser room._id, user

```
If I remove it  at least the "User has joined" does not occur in the default channel.
However i don't now if there is any other implications or if its safe.

**Comment by rodrigok** [comment]
Maybe we can group better this messages like slack does, or add an option per room to not render some system messages.

**Comment by lunitic** [comment]
@rodrigok 

This is what I plan to do ..Do you think it will break anything other ?

```
# Insert user joined message
#                if not silenced
 #                   RocketChat.models.Messages.createUserJoinWithRoomIdAndUser room._id, user
```

**Comment by timkinnane** [comment]
This is a dupe of #2959 - Just wanted to add my comment to both issues...

>hiding the messages is better than actually preventing them, since some bot interactions are triggered by these special events message types. e.g. Someone entering a room, bot might send a welcome message.

**Comment by rodrigok** [comment]
Closing in favor of #2959
