### ISSUE TITLE
有时候无法连接,

### ISSUE THREAD

**Issue by reboot523** [RocketChat/Rocket.Chat#34196]
我的rocketchat和jitsi用docker-compose部署在同一个VPS上,但是无法rocketchat(端口2087/2096)调用jitsi(标准SSL端口)

**Comment by reetp** [comment]
First, English only I'm afraid.

This is a support not a bug.

Read this, document your problem properly, and ask in the correct channels.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#information-that-support-or-devs-will-require



https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#how-to-ask-for-help-1
