### ISSUE TITLE
email field is case sensitive

### ISSUE THREAD

**Issue by kashifnawaz123** [RocketChat/Rocket.Chat#3420]
Your Rocket.Chat version: 0.32.0

Hi Team,
when configured rocket chat on my server and some user is doing password reset it seems the email field is case sensitive, which means user registered User1@example.com and when he is doing password reset , he is using email id as user1@example.com  and click on forgot password. 

User in this particular scenario is not getting password reset email from server , he has to use User1@example.com only

**Comment by brandtheisey** [comment]
This hosed our implementation today as well.
