### ISSUE TITLE
url / login provisioning file for windows/linux rocket.chat client application (feature request)

### ISSUE THREAD

**Issue by frasercarter** [RocketChat/Rocket.Chat#3422]
app provisioning file to enable preconfiguration of team url within package, so that end users don't need to know the URL to join the chat.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
