### ISSUE TITLE
Use RocketChat in other site

### ISSUE THREAD

**Issue by galrotem1993** [RocketChat/Rocket.Chat#3423]
Your Rocket.Chat version: 0.32.0  (develop)

Hello, is it possible to add Rocket.Chat  as a component to a site? like the facebook chat?
maybe an iframe or embed link?

Anyone have examples, on how to added rocket.chat to a site?

**Comment by bt** [comment]
Have a look at the Live Chat feature. I think that's what you're after.

**Comment by serhiiso** [comment]
@bt Is it live chat integration (livechatinc.com) or similar but own functionality ?

**Comment by MartinSchoeler** [comment]
@galrotem1993 you can use either iframe https://rocket.chat/docs/developer-guides/iframe-integration or livechat https://rocket.chat/docs/administrator-guides/livechat/#livechat
