### ISSUE TITLE
Incorrect/Non-functional Message Navigation Shortcuts in /help command Documentation

### ISSUE THREAD

**Issue by darshanlahamage** [RocketChat/Rocket.Chat#34230]
### Description:

The keyboard shortcuts listed in the /help slash command for message navigation are incorrect or non-functional **on Windows**. Several `Alt` **Command key combinations do not work as documented**, while some functionality is **actually available through different key combinations.**

### Steps to reproduce:

1. Type `/help` in any channel
2. Test the following shortcuts: **windows**
    - Alt + Left Arrow
    - Alt + Up Arrow
    - Alt + Right Arrow
    - Alt + Down Arrow

### Expected behavior:
Alt + Left Arrow: Move to beginning of message
Alt + Up Arrow: Move to beginning of message
Alt + Right Arrow: Move to end of message
Alt + Down Arrow: Move to end of message

### Actual behavior:
Alt + Left Arrow: Navigates back in browser history instead of moving cursor
Alt + Up Arrow: No action
Alt + Right Arrow: No action
Alt + Down Arrow: No action
Note: On Windows, Ctrl + Left/Right Arrow actually moves to the beginning/End of the message, but this correct shortcut is not documented

### Server Setup Information:

- Version of Rocket.Chat Server: 7.1.0
- License Type:
- Number of Users: 
- Operating System: 
- Deployment Method:  
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 20.18.0
- MongoDB Version:

**Comment by thepiyush-303** [comment]
The same issue is already raised, no need to add same one more time.
