### ISSUE TITLE
Allow scandic letters in room and user names

### ISSUE THREAD

**Issue by simopaasisalo** [RocketChat/Rocket.Chat#3424]
Your Rocket.Chat version: 0.32.0

In the newest release version I can't seem to input scandic letters (åäö) into usernames or room titles. 
in room names (room name åäö), the error shown is 
`__room_name__ is not a valid room name. Use only letters, numbers, hyphens and underscores`

For the user:
`åäö is not a valid username`

**Comment by simopaasisalo** [comment]
I think this might simply be solved by editing the UTF8 settings, but I tried some different configurations but couldn't get them to work. If anyone has a working regex, I'd be much obliged

**Comment by bgomelsky** [comment]
Here is what we use to allow Japanese names (replace or add valid UTF8 character ranges): 

`[0-9a-zA-Z-_.\u3040-\u309f\u30a0-\u30ff\u4e00-\u9fff]+`

**Comment by simopaasisalo** [comment]
@bgomelsky Thanks, but still couldn't get it to work. Here's what I tried
`[0-9a-zA-Z-_.\00C0-\00F7]+`
That range definitely contains all the chars I would need, but I'm still getting the same errors. I did try rebooting the server, but that had no effect either.

**Comment by simopaasisalo** [comment]
@bgomelsky Thank you! Here's what worked, for anyone struggling with the same problem:

`[0-9a-zA-Z-_.\u00C0-\u00F7]+`
