### ISSUE TITLE
Add members to room improvement

### ISSUE THREAD

**Issue by danieljsm** [RocketChat/Rocket.Chat#3425]
Your Rocket.Chat version: 0.32

when adding a new member to a room only members not present in the room should be avaible to select, not all server members

**Comment by NexSabre** [comment]
Or should be some separate line on list.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
