### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by CodePoetSarah** [RocketChat/Rocket.Chat#3426]
Version v0.36.10 of the client running on Xubuntu Ubuntu 16.04 LTS using the debian deb rocketchat-v1.3.1-linux-x64.deb

The authentication against google doesn't give an option for additional accounts. It defaults to my personal gmail, but doesn't allow me to change it to my work gmail. Adding the account doesn't make any difference as it doesn't show up in the drop down. 

If it tries the account which isn't authorised on that account, the login screen goes blank and the screen locks up.

![screenshot_2016-06-01_11-13-31](https://cloud.githubusercontent.com/assets/688510/15714809/0d2f4232-27ea-11e6-8e2a-ff47886e4b37.png)

**Comment by Andy-Thornton** [comment]
This issue also occurs on Fedora 23 workstation.

**Comment by reetp** [comment]
I'm not sure if anything much has changed on this or not.

Rocket is currently on 0.70.4 and the client on 2.14.x so a lot of water has passed under the bridge.

Closing for lack of more up to date information. Please reopen if there are further issues.

**Comment by reetp** [comment]
@rocket-cat close
