### ISSUE TITLE
[OFFICIAL/TV!!]* — KSW 101 LiVe 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 FrEe BrOaDcAsT oN TV Guide & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 20 December 2024

### ISSUE THREAD

**Issue by ehsd991** [RocketChat/Rocket.Chat#34264]
The KSW 101 event, set to take place this Friday, December 20, 2024, at the Paris La Défense Arena, features the highly anticipated lightweight championship bout between Salahdine Parnasse and Wilson Varela.

[🔴GO LIVE🌐🟢==►► CLICK HERE TO STREAMING](https://there-is-way-on-gam-pas-go.blogspot.com/)

[🔴STREAMING🌐🟢==►► CLICK HERE TO WATCH LIVE](https://there-is-way-on-gam-pas-go.blogspot.com/)

Salahdine Parnasse will put his Konfrontacja Sztuk Walki lightweight championship on the line when he meets Wilson Varela in the KSW 101 headliner on Friday at Paris La Defense Arena in Nanterre, France. Meanwhile, onetime Bellator MMA tournament winner Marcin Held collides with Davy Gallon in the three-round lightweight co-main event at 155 pounds.

KSW 101 “Parnasse vs. Varela”—which streams live to kswtv.com pay-per-view at 1 p.m. ET/10 a.m. PT—also features a middleweight tilt matching Laid Zerhouni with Alain Van De Merckt, a welterweight affair pitting Romain Debienne against Mickael Lebout, a 174-pound catchweight cash slotting Alex Lohore opposite Artur Szczepaniak and a lightweight confrontation pairing Ramzan Jembiev with El Hadji Ndiaye.

While Parnasse is the clear favorite, Varela's six-fight winning streak and knockout power pose a significant threat. Any fight can shift dramatically, especially with Varela's striking experience and momentum.

KSW 101 marks KSW's second event in France, increasing the stakes of local rivalries.
Parnasse, known for his grappling and versatility, faces Varela, a striking specialist with a knockout history.

Fans can expect an electrifying fight night, projecting potential future matchups depending on the outcome. A Parnasse win could lead to defense against other top contenders, while a Varela upset might set off a surge of interest in his career.

An exhilarating clash of styles awaits at KSW 101, with both fighters having impressive credentials. This bout is not just a title fight; it’s a representation of regional pride and showcases the growth of European MMA.

Following up on his stellar performance earlier this year, Parnasse asserts his dominance having won his last fight against Moldovan Valeriu Mircea by knockout just seconds before lasting through the first round. Parnasse, often referred to as the "Kylian Mbappé of MMA," boasts an impressive fight record, including 11 victories within the KSW, where he currently holds both the lightweight and featherweight championships.

Meanwhile, Wilson Varela has been steadily climbing the ranks, currently riding on a six-fight winning streak. His recent performances have established him as a force to be reckoned with, leading many to wonder if he can topple Parnasse and claim the championship. Varela holds 12 wins out of 18 fights, and he has previously displayed knockout power with five finishes under his belt, including notable victories against Marian Ziółkowski, the former lightweight champion.

The stakes are high for this match, not only because it is for the lightweight title, but also because it symbolizes the competitive spirit between fighters from Paris and Marseille—a narrative often highlighted when these two cities clash.

Fans can catch the action starting at 20:30 on RMC Sport, with the championship fight expected to commence around 23:00. The fight card promises to deliver exciting matchups across various weight classes, including Davy Gallon battling Marcin Held and Laïd Zerhouni facing Alain Van De Merckt.

The anticipation builds, with over 20,000 spectators expected to witness this electrifying night of MMA. Describing the event, Jonathan Toulemonde, the director of the Westfield Les 4 Temps which hosted the official weigh-in, expressed pride at welcoming such a significant event, stating, "Nous sommes particulièrement fiers d'accueillir cet événement inédit au sein de Westfield Les 4 Temps."

THE LINEUP 155: Salahdine Parnasse vs. Wilson Varela 155: Davy Gallon vs. Marcin Held 185: Laid Zerhouni vs. Alain Van De Merckt 170: Romain Debienne vs. Mickael Lebout 174: Alex Lohore vs. Artur Szczepaniak 155: Ramzan Jembiev vs. El Hadji Ndiaye 145: Eduard Kexel vs. Alioune Nahaye 145: Fabien Xabidi vs. Nacim Belhouachi 161: Amaury Wako-Zabo vs. Maciej Rebacz 139: Zakaria Hamou vs. Andrzej Karkula

**Comment by jeanpaul98728** [comment]
[https://www.mylittlepolynesia.com/](url) thanks for sharing
