### ISSUE TITLE
[FIGHT/TV!!]* — Tyson Fury vs Oleksandr Usyk LiVe 𝐒𝐭𝐫𝐞𝐚𝐦𝐬 FrEe BrOaDcAsT oN TV Guide & 𝐒𝐭𝐫𝐞𝐚𝐦𝐢𝐧𝐠 21 December 2024

### ISSUE THREAD

**Issue by reesazghupo4** [RocketChat/Rocket.Chat#34286]
Tyson Fury and Oleksandr Usyk are set to face off again tonight, seven months after Fury's first professional loss. Boxing fans have backed Oleksandr Usyk to put the rivalry with Tyson Fury to bed and go 2-0 up in the series ahead of their heavyweight dust-up.

Fury was the favorite in their initial bout and maintained control until Usyk flipped the script in the second half. The Ukrainian became the first undisputed champion of the division since Lennox Lewis in 1999, but only three belts will be up for grabs tonight in Riyadh.

This highly anticipated heavyweight clash will determine the undisputed world champion, with the IBF, IBO, WBA, WBC, and WBO titles all on the line.

The pair first went toe-to-toe back in May this year. In what was a mouthwatering back-and-forth encounter, the Ukrainian went on to defeat the 'Gypsy King' via split decision. Following the win, the 37-year-old became the first undisputed heavyweight world champion since Lennox Lewis back in 1999.

Usyk is the clear favourite to get his hand raised yet again, that said, there are still a fair few who believe Fury has what it takes to dethrone the Ukrainian sensation. And our readers have voted in their thousands with regard the result of the fight - and there is a clear winner.

A mere seven months after Oleksandr Usyk narrowly outpointed Tyson Fury to become the first undisputed heavyweight boxing champion in 24 years, the two fighters return to Saudi Arabia this Saturday for a much anticipated rematch. 

Since that first encounter Usyk has had to give up his IBF belt, meaning only three titles are being put on the line by the unbeaten Ukrainian fighter this time out. 

But following a coin toss, it was ruled that the judge from Panama would be the replacement.

Robles is not very experienced but has previously been a judge at ringside for British fighters.

He officiated when Dmitry Bivol defeated Mancunian boxer Lyndon Arthur in Saudi Arabia last year.

That split decision loss back in May marked the first time Fury had tasted defeat after 16 years as a professional. The British fighter will be determined to get revenge on Saturday, with a win for the "Gypsy King" likely to pave the way for an all-British match-up with either Daniel Dubois or Anthony Joshua. 

Usyk is favored to win after nearly stopping Fury in the ninth round in May, but both fighters have vowed to definitively settle their rivalry. Regardless of the outcome, Anthony Joshua could be next in line for his fellow Brit as they aim to finally resolve their long-standing rivalry.

While the masses have backed the 37-year-old undefeated Ukrainian to reign supreme, Fury will no doubt have something to say about that. During an intense staredown on Thursday night, the Brit was eager to issue a chilling warning to his upcoming opponent.

**Comment by reetp** [comment]
Spammers not welcome.

**Comment by Hff4gd2** [comment]
fgd

**Comment by bulloksmainnok** [comment]
rdfvd
