### ISSUE TITLE
Wrong Message Dispatches on changing User Role

### ISSUE THREAD

**Issue by thepiyush-303** [RocketChat/Rocket.Chat#34288]
### Description:

Any Room -> User info -> change their Roles (e.g set as moderator/leader) -> wrong message dispatches

### Server Setup Information:

- Version of Rocket.Chat Server: 7.2.0-develop
- License Type:
- Number of Users:  2
- Operating System: ubuntu
- Deployment Method:  development
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Firefox

### Additional context

[Screencast from 2024-12-20 21-49-12.webm](https://github.com/user-attachments/assets/8c5d624c-2ad8-47aa-824d-d8585cf60a34)

### Relevant logs:
In the above clip it is shown than when removing user from Moderator Role it says Added.

**Comment by ritikpal1122** [comment]
hi @thepiyush-303 can i work on this ?

**Comment by thepiyush-303** [comment]
There is already a PR

**Comment by reetp** [comment]
> hi @thepiyush-303 can i work on this ?

Please read thoroughly.

**Comment by casalsgh** [comment]
will ask eng for a PR review
