### ISSUE TITLE
Spotify links are being treated as simple links

### ISSUE THREAD

**Issue by theworldbright** [RocketChat/Rocket.Chat#3428]
Your Rocket.Chat version: Develop Branch

Spotify links should be parsed as specified here https://github.com/RocketChat/Rocket.Chat/issues/865

**Comment by Bitti09** [comment]
Your Rocket.Chat version: Develop Branch from 2h ago

Not fixed for me. Still shown as normal links.

**Comment by theworldbright** [comment]
@Bitti09 Can you give the specific link you tried?

And do the following links still show as normal links? They are all turned into iframe's for me.

https://open.spotify.com/track/34AWo71Ya5gq7wpNnatwr7
spotify:track:34AWo71Ya5gq7wpNnatwr7
spotify:album:6TmMmGVseWokw8pcVsWRfV

**Comment by theworldbright** [comment]
Also which browser are you using? I tested it on Opera, Chrome, FF.
