### ISSUE TITLE
Oauth scopes on custom oauth provider

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3429]
We need to add the ability to specify the scopes on custom oauth methods

**Comment by wohali** [comment]
It would be awesome if you supported pulling the user's OAuth-provided avatar via this. I don't know if this is a separate request or not.

**Comment by geekgonecrazy** [comment]
@wohali actually we already pull the avatar.  If you goto the avatar section in My Account you should be able to select use this avatar by any of your connected oauth services

**Comment by wohali** [comment]
Incorrect. The source code special cases support for various specific vendors, but never pulls it for a custom OAuth provider. The relevant code is here:
1. https://github.com/RocketChat/Rocket.Chat/blob/a5cb22bb0017f4c39654bf1e2895ae64acb0339b/packages/rocketchat-ui-account/account/avatar/prompt.html#L71-L98
2. https://github.com/RocketChat/Rocket.Chat/blob/625b2963fdda3f41aff8c2b488352b54054f4945/server/methods/getAvatarSuggestion.coffee#L1-L48

You'll notice everything is special cased for the pre-implemented OAuth providers, but nothing is looking at the profile returned by a custom OAuth provider. :(

**Comment by geekgonecrazy** [comment]
@wohali ok good point.  I didn't realize we were hard coding the paths.  We should probably make use of the info passed back.  Thanks for bringing that up.

Is it standardized in anyway or dependent on the oauth provider?

**Comment by wohali** [comment]
I wish I knew, but a way to specify a json selector in the OAuth Custom config (to select within the returned response document) would probably be sufficient...and it could guess a few locations for default behaviour when such a field is unspecified ("profile", "user.profile", etc.)

**Comment by Kim-Goon** [comment]
This problem solved that click the "REFRESH OAUTH SERVICES" button beside " ADD CUSTOM OAUTH" button. :-)
