### ISSUE TITLE
Site Name doesn't show up correctly in oembed

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3431]
Server URL name shows as "rocket.Chat" and not the site name? how can we set variables?

![image](https://cloud.githubusercontent.com/assets/12454319/15724580/b55913e0-2815-11e6-9e0b-32486c51bc69.png)

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by geekgonecrazy** [comment]
This is due to the title being injected in blaze templates client side.  So this may depend on us switching to something like react as discussed here: #1680
