### ISSUE TITLE
Granting Access

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3435]
is there a way for Admin to control how users access their tool? i.e allowing access to users to log only from web browser vs app? 
thats if we can differentiate how users are connecting to the chat tool

Your Rocket.Chat version: 0.32

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @IQ2022, I'm closing this. There is currently no feature to do this - if you still want this implemented, please open a discussion over at https://forums.rocket.chat. :)

Cheers
Thomas
