### ISSUE TITLE
Log messages to systemd no longer works 

### ISSUE THREAD

**Issue by antn89** [RocketChat/Rocket.Chat#3436]
Your Rocket.Chat version: (make sure you are running the latest) 0.31.0
Hi all,
I can view all log at admin page, but it difficult to search some log messages. 

In the 0.30 version, all log was parsed in the message log on server.
But on version 0.31 and 0.32, it not stay here?
In 0.30.0, 0.31.0 and 0.32.0 version i config as below:

[Unit]
Description=The Rocket.Chat  server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /root/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=root
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=https://mydomain PORT=3000
[Install]
WantedBy=multi-user.target

**Comment by Sing-Li** [comment]
Please do not use View Log for your own coding.  And do not rely on it to provide any consistent log.

It is designed for internal diagnostic and support only.

Closing this issue.

**Comment by Sing-Li** [comment]
Anyone  else  out there using systemd and observe the same problem?  

Please drop a note here, it will help us isolate the problem.

**Comment by antn89** [comment]
Hi @Sing-Li 
This issue has fixed when i create service start by forever-service. All log message in /var/log/rocketchat.log.
Thank you alot.
`forever-service install -s main.js -e "ROOT_URL=https://example.com/ MONGO_URL=mongodb://localhost:27017/rocketchat PORT=3000" rocketchat`
