### ISSUE TITLE
how to use restapi to keep livechat?

### ISSUE THREAD

**Issue by supershy77** [RocketChat/Rocket.Chat#3439]
Recently out team build a project named Bim for collaboration,we want to make integration with Rocket.Chat,but it is hard to me.
I find that Rocket.Chat provide restapi ,when i want to send a message to a person named "supershy" i can use "rooms/:id/send" and other people can receive messages by get "rooms/:id/messages",
meanwhile a person named "qiqi" send a message to "supershy", "supershy" should refresh the page in order to see the updated message. my big question is that how "supershy" can receive message immediately?

**Comment by sampaiodiego** [comment]
hi @supershy77 .. please take a look on our [RealTime APIs](https://rocket.chat/docs/developer-guides/realtime-api)

**Comment by MartinSchoeler** [comment]
Closing this issue due lack of response in a long time. If your issue persists after trying the RealTime APIs please reopen this with updated details. Thanks!
