### ISSUE TITLE
GitHub OAuth Provider

### ISSUE THREAD

**Issue by continuouslee** [RocketChat/Rocket.Chat#3445]
Your Rocket.Chat version: demo.rocket.chat server

I tried authenticating against my GitHub username and the first time through it allowed me to create my account.  Once I did that, all subsequent authentications have resulted in an "Internal Server Error".  Talking to @engelgabriel, the logs are showing an "access denied" error in auth.js.  Keeping this open for tracking as a bug.

**Comment by continuouslee** [comment]
@RocketChat/core 

I have just done a test of OAuth and GitHub:
- Running under the `develop` branch, authentication works as expected.  Very fast even.
- Running under the `origin/improvements/more-streams` branch, authentication fails with an odd error:

```
I20160604-02:09:44.152(0)? Exception while invoking method 'login' TypeError: Cannot read property '_id' of undefined
I20160604-02:09:44.152(0)?     at packages/underscore/underscore.js:261:1
I20160604-02:09:44.152(0)?     at Array.map (native)
I20160604-02:09:44.153(0)?     at Function._.map._.collect (packages/underscore/underscore.js:123:1)
I20160604-02:09:44.153(0)?     at Function._.pluck (packages/underscore/underscore.js:261:1)
I20160604-02:09:44.153(0)?     at _Class.update (server/models/_Base.js:69:27)
I20160604-02:09:44.153(0)?     at _Class.RocketChat.models.Users._Class.setEmailVerified (packages/rocketchat_lib/server/models/Users.coffee:208:11)
I20160604-02:09:44.153(0)?     at AccountsServer.Accounts.updateOrCreateUserFromExternalService (server/configuration/accounts_meld.coffee:33:28)
I20160604-02:09:44.153(0)?     at [object Object].Package (packages/accounts-oauth/oauth_server.js:55:1)
I20160604-02:09:44.153(0)?     at accounts_server.js:462:32
I20160604-02:09:44.153(0)?     at tryLoginMethod (accounts_server.js:239:14)
```

Can we please move `https://demo.rocket.chat` back to the `develop` branch?

**Comment by geekgonecrazy** [comment]
@continuouslee we have our secret ninja on it. :smile:  Should be resolved soon

**Comment by sampaiodiego** [comment]
@continuouslee it has been fixed at https://github.com/RocketChat/Rocket.Chat/commit/8185e67406835695421efbda9a62c5593d63ae09

I'm already deploying the fix to demo server.. :wink:

**Comment by continuouslee** [comment]
@sampaiodiego - Still can't authenticate :(

**Comment by geekgonecrazy** [comment]
@continuouslee maybe the account didn't get linked to github right?  Not sure mine worked finally and hadn't been.  

If you can hop on the demo server with another account, I can hook you up with a temp password.  So you can login.  Or I can email it to you :smile:

**Comment by continuouslee** [comment]
:tada: :sparkles: :rainbow:
## RCA (root cause)  
Something we need to document is if someone goes into GitHub and changes their email address and makes the new email address the primary, they need to change their email address in Rocket.Chat.  So they should change in Rocket.Chat first, then change in GitHub because otherwise, the OAuth validation will fail and they won't be able to get back into Rocket.Chat.

**Comment by geekgonecrazy** [comment]
That makes sense.  Also we need to better handle oauth with different email addresses.  I believe we have an issue for that.
