### ISSUE TITLE
Disable the hex-color box

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#3446]
Is there a way to disable that color box that shows after you type #number ?  If not, can we add that option? We reference tickets/bugs using that sytax so a color box is always being added in.  Couldn't find a setting to disable it.

**Comment by GreenAsJade** [comment]
Totally agree - this stupid thing is driving us nuts.

We have tickets referred to as #xxx the number ... we talk about them all day.   Having these stupid colored boxes is insane!

**Comment by gkarmas** [comment]
Another suggestion, insert the option to disable HEX colors in Rocket Chat's administration page.

**Comment by alfredbez** [comment]
@twhiting do use a package which creates real links to your tasksystem or do you only share Simple task-ids? We are looking for a package which creates links from task-ids.

**Comment by twhiting** [comment]
@alfredbez Sorry for the late response, I was on vacation. I wrote a hubot script for the built in rocketchat-hubot plugin that finds a "#<number>" in any typed message.   If it finds a match it automatically edits the message immediately after and inserts a clickable link to our bug system.  It works great for us and since its a link it gets rid of this color box too!

**Comment by timkinnane** [comment]
> insert the option to disable HEX colors in Rocket Chat's administration page  

@gkarmas this should be handled by #1859 or #2255. I think the solution for this issue is still to disable (comment out) hex colors package by default and if you need it, turn it on.

**Comment by TAdeJong** [comment]
@alfredbez FYI: @TobiasKappe wrote a pull request for something that does exactly that: #6700
