### ISSUE TITLE
Outdated and Non-Functional .gitpod.yml gitpod configuration File 

### ISSUE THREAD

**Issue by darshanlahamage** [RocketChat/Rocket.Chat#34487]
### Description:

The current **`.gitpod.yml`** file is outdated and non-functional. It fails to initialize the development environment when a Gitpod workspace is opened. The following critical issues render the configuration unusable:

1. **Deprecated Configurations:**

 The **`github.prebuilds`** section is no longer supported by Gitpod as per their documentation. 
**Prebuilds are now configured in the  Gitpod project settings, making this section ineffective.**
 
  ![image](https://github.com/user-attachments/assets/75ad46eb-6c72-45c1-beb5-adacdc3f3e3e)

**2. Mismatched Task Configuration:**
The task commands in .gitpod.yml fail to match the instructions provided in Rocket.Chat’s [Rocke.chat doc for gitpod setup](https://developer.rocket.chat/docs/gitpod). Missing required tasks to prepare the environment during prebuilds. Commands are not structured to ensure successful initialization.

**4. Resulting in failed initialization:**
Developers must manually execute environment setup commands to initialize the workspace. This defeats the purpose of having an automated Gitpod configuration file.

### Additional context
Gitpod Deprecation Notice: 

- [Deprecated github.prebuilds](https://www.gitpod.io/docs/references/gitpod-yml#github)
- https://github.com/apps/gitpod-io
- [Latest Prebuilds Configuration Guide](https://www.gitpod.io/docs/configure/repositories/prebuilds)

Rocket.Chat Documentation: [Gitpod Setup Instructions](https://developer.rocket.chat/docs/gitpod)

**Comment by reetp** [comment]
Yup it's a mess including docs which are wrong for Flex.

Needs a ground up review from the team.

I have referred it to them already.
