### ISSUE TITLE
[Bug] : In mobile screen this two buttons are collapse

### ISSUE THREAD

**Issue by harshal050** [RocketChat/Rocket.Chat#34483]
### Description:

On mobile screens, two buttons are collapsing and overlapping, making them difficult to use.

### Steps to reproduce:

1. Go to  https://docs.rocket.chat/  
2. scroll down  
3. You can see this issue  

### Expected behavior:

The two buttons should be displayed properly without overlapping or collapsing, maintaining proper spacing and usability.

### Actual behavior:

The two buttons collapse into each other on mobile screens, as shown below:

![Screenshot_20241223_050056](https://github.com/user-attachments/assets/be02698e-74be-4b8e-94d7-9635267f1f1e)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- License Type:
- Number of Users: 1
- Operating System: windows 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by amanchoudhary18** [comment]
I would love to work on this issue. It seems a small position fix. 
![image](https://github.com/user-attachments/assets/9f3c0a58-ec49-4403-a33b-4c0b88293619)
![image](https://github.com/user-attachments/assets/25044d61-5c2f-4b9c-be15-e2c6a693670f)

**Comment by amanchoudhary18** [comment]
![image](https://github.com/user-attachments/assets/7c0ab2e8-8674-46c4-8a50-e875bc78f018)

Also noticed some alignment issue in desktop browser view.

**Comment by ritikpal1122** [comment]
hi @harshal050 Can i work on this ?

**Comment by thepiyush-303** [comment]
This repo maintains open.rocket.chat/.
these issues are irrelevant here.

**Comment by harshal050** [comment]
> I would love to work on this issue. It seems a small position fix. ![image](https://private-user-images.githubusercontent.com/63499156/398040075-9f3c0a58-ec49-4403-a33b-4c0b88293619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjQ2NjUsIm5iZiI6MTczNDk2NDM2NSwicGF0aCI6Ii82MzQ5OTE1Ni8zOTgwNDAwNzUtOWYzYzBhNTgtZWM0OS00NDAzLWEzM2ItNGMwYjg4MjkzNjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE0MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNjhjYzMzOWJjZmJiMGJiMjhiMDVhZTA3ZjgyODg1ODgzZGEyNTZmYmMwNTdjMGI4YWE3MTU2MmI4YzNjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KBJWG9pVTOThPArO-F1nc2DeQPtEPdJzVCVxdagh6oE) ![image](https://private-user-images.githubusercontent.com/63499156/398040087-25044d61-5c2f-4b9c-be15-e2c6a693670f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjQ2NjUsIm5iZiI6MTczNDk2NDM2NSwicGF0aCI6Ii82MzQ5OTE1Ni8zOTgwNDAwODctMjUwNDRkNjEtNWMyZi00YjljLWJlMTUtZTJjNmE2OTM2NzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE0MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NmVhYmMzN2MzMmUxZTA0MTQwY2E2MjhjMDU3NGJiM2RkNDZhOWZmOGU5ZjllYTc3ZmUxMWRhNDA4MmI5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M1oJI1h7DhL1sdKYnMQpKOky4AqjtjGgsyDy4MocyTQ)

yes you can

**Comment by harshal050** [comment]
@thepiyush-303 please send me repo link

**Comment by harshal050** [comment]
### **"Anyone who wants to work on this issue, please do it quickly. Credit will be given to the one who solves it first."**

**Comment by reetp** [comment]
> @amanchoudhary Yes you can

No, you can't.

Period.

**Comment by reetp** [comment]
> "Anyone who wants to work on this issue, please do it quickly. Credit will be given to the one who solves it first."
> 

No idea where you found this but it is wrong - probably in the docs which need correcting.

Docs are now held in a private repo.

No PRs accepted.

You can your own note under "Was this helpful"

**Comment by reetp** [comment]
From Casals at Rocket:

> I think that we can't fix. It is standard on the platform we use. 

> PC is working fine; might be just on mobile, and only seen when folks go to the bottom of the page. 

> Red button is just to get folks to top of the page again, so should not be a big issue.
