### ISSUE TITLE
Bug when calling REST API for room messages

### ISSUE THREAD

**Issue by afaizal** [RocketChat/Rocket.Chat#3449]
Got Error: Cannot return null or undefined from an endpoint: get api/rooms/:id/messages/:ts\n    at packages/nimble_restivus/lib/route.coffee:61:25\n

Tried testing by giving invalid room ID.

The error handling seems to be missing.
Any advice ?

**Comment by sampaiodiego** [comment]
I can advice you to pass only valid room IDs until someone fix that :smile:

**Comment by Deepakkothandan** [comment]
@afaizal What version of Rocket Chat did you use to test the above scenario. I tested the above method with version 0.33 and here is the `output`vagrant@vagrant-ubuntu-trusty-64:~$ curl -H "X-Auth-Token: jtia1b3kqkN4IgcTBuyTZ_-TlSTjqSkJ4PxKiGeV1eI" -H "X-User-Id: ibHxrcoR66M2wNf7d" http://localhost:3000/api/rooms/nonexistingroom/messages
{
  "status": "fail",
  "message": "Error :: Invalid room [error-invalid-room]"
`

**Comment by sampaiodiego** [comment]
thanks @Deepakkothandan .. I tried and got the same result.
