### ISSUE TITLE
How to customize Rocket.Chat ?

### ISSUE THREAD

**Issue by amadou009** [RocketChat/Rocket.Chat#3452]
Hello, i wan to customize Rocket.chat but i don't know which documents i have to modify.
Please help me.

**Comment by marceloschmidt** [comment]
Rocket.Chat uses Meteor. A good starting point is to learn meteor: http://guide.meteor.com/

**Comment by kumarpradeephk** [comment]
Hello,i want to customize and integrate rocket chat in website and Android app but  i am not able to do that, which file i have to modify.please help me.

**Comment by rahul7471** [comment]
@kumarpradeephk DiD you find any solution. Please Reply asap

**Comment by kumarpradeephk** [comment]
@rahul7471  first you have to understand  codeflow after that you will understand where you can customize.
