### ISSUE TITLE
Emphasize showing realname in UX

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3453]
We do a field trial in an enterprise environment. People are used (and sensible) to read real names including titles instead of nicknames only. 
Could we have a check-box option in the Layout / User Interface settings, to display in addition the real name right of the self-image on the top left corner in the messaging screen with the two lines:
realname = Dr. Joe Rock 
@username = @Joe_Rock
instead of the latter only.
Secondly, the list of contacts for direct messages should show the realname, with that checkbox ticked. 
Thirdly, the user info dialog (person icon on the right bar) should show realname in bold and username below, with that checkbox ticked. 

Using Rocket.Chat version:0.32

**Comment by sampaiodiego** [comment]
Is it ok for you to keep showing the usernames at the messages? if so, don't you think it will be a bad UX emphasing the real name all over the UI except at the messages?

**Comment by rasos** [comment]
Well, I thought that real names at messages might prevent users using mentions. But you're right, the check box option should probably not mix the UX up and real names should be used at all occasions. In order to be able to address a person with the username for mentions, it should be probably be displayed on a second line e.g. in the chat window near the real name.
