### ISSUE TITLE
Page Refresh needed to establish Video Chat

### ISSUE THREAD

**Issue by MogiePete** [RocketChat/Rocket.Chat#3454]
Your Rocket.Chat version: 0.32.0

Google Chrome 52.0.2743.24 - Mac OS X
Mozilla Firefox 46.1 - Mac OS X
Google Chrome 49.x.xxxx.xx - Windows 7

When establishing a video chat both parties report getting the popup to accept the call however neither party is able see the window for the video chat. Instead both parties must refresh the page and once this is done both parties are able to see both video feeds.

This has been verified on both Google Chrome and Firefox when establishing video chat to and from a Windows 7/10 PC.

This has not been verified from Mac OS X to Mac OS X or Windows 7/10 to Windows 7/10.

**Comment by xadhoom** [comment]
can you check if is this same issue #3413 ?

**Comment by MogiePete** [comment]
We have narrowed this down to only happen when one or both parties are connected via VPN.
