### ISSUE TITLE
Chat is cleared when clicking on permalink to deleted post

### ISSUE THREAD

**Issue by MogiePete** [RocketChat/Rocket.Chat#3455]
Your Rocket.Chat version: 0.32.0

Confirmed in Google Chrome and Rocket.Chat Windows Client.

To replicate:

Create a post
Create a permalink
Post Permalink
Delete original post
Click on Permalink
Chat is cleared. 

Search still works and I can find older messages in the channel but they do not display in the chat window at all until a page refresh has occurred or the Windows Client has been closed and reopened.

**Comment by sweetkandy** [comment]
Same behavior happens if you click a permalink twice, you don´t even have to delete the original post.

Create a post
Create a permalink
Post Permalink
Click on Permalink
Click on Permalink
Chat is cleared

rocket.chat version 0.45.0

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
