### ISSUE TITLE
Slackbridge 2-way

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#3457]
Your Rocket.Chat version: develop 2015-06-03

Great work on slackbridge! It's working so well.

Is it in the plans to have it a two way communication so you could reply in rocket chat and it would also show in slack?

**Comment by geekgonecrazy** [comment]
What kind of use case are you seeing here?  Keeping them both going side by side?  A one way sync isn't super complicated, but 2 way becomes more so.

**Comment by mrplow** [comment]
Yes a two way side by side.

I know it would be very complicated but I was just opening up the
discussion to the possibility of the enhancement down the road.

**Comment by mrplow** [comment]
Our teams use case is mostly mobile and unfortunately the initial latency of loading the app is too show, so we use slack while mobile.

**Comment by geekgonecrazy** [comment]
@mrplow ah!  Yes we are aware of that and trying to resolve it.  Hate to see that be the reason to have to use two platforms.  Would be a little Irritating for sure

**Comment by vetash** [comment]
Also i think bridge need configuration for channels. We use slack+rocket chat too and now we must use hubot for forward messages between some specific channels, not all. So bridge need to configuration in this case.

**Comment by dawesi** [comment]
this would also be great while migrating from slack to rocket.chat for communities...

**Comment by dalareo** [comment]
This 2-way sync feature would be nice to go forward with Rocket Chat integration in huge teams. What about setting an IRC channel as bridge beetween Slack and Rocket.Chat. Maybe it could also serve as a Telegram bridge!!
@vetash are you able to forward Rocket.Chat messages to Slack??

**Comment by trondvh** [comment]
There is also a security aspect here. Some companies don't allow mobile users to connect to their on-prem Rocket Chat server(s) without VPN, if at all. A bidirectional SlackBridge would let Slack act as a proxy, and could connect mobile users to on-prem Rocket Chat servers in a secure way.
