### ISSUE TITLE
[Win 10] After installing new fonts on OS, Rocket.Chat font changed

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#3460]
Your Rocket.Chat version: 1.3.1

I installed many new fonts on Win 10. I dunno if this has s.th. do with it, but now the font of RocketChat has changed. Seems like it has no sharpening anymore and as font it's using Impact or s.th. similar.

Image: http://i.imgur.com/wVscl44.jpg

I already re-installed RC and deleted everything in `/username/local/RocketChat` and `/username/roaming/RocketChat`

**Comment by punkr0ck** [comment]
Okay, the font is "Helvetica Neue Bold" which was used. After deinstalling the font, everything is fine again. Could anyone confirm this issue?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
