### ISSUE TITLE
Get access to server side cookies

### ISSUE THREAD

**Issue by Artgit** [RocketChat/Rocket.Chat#3461]
I need to get access to server side cookies in RocketChat application.

Please show an example how it can be achieved.

**Comment by geekgonecrazy** [comment]
A quick look at the cookies would show you we have the following cookies:

![image](https://cloud.githubusercontent.com/assets/51996/15802047/f7083a88-2a6c-11e6-9047-9fca45f3b098.png)

* meteor_login_token
* rc_token
* rc_uid

you would access them just like you typically would access a cookie.

**Comment by Artgit** [comment]
Thanks. I have implemented new Flow-router trigger in RocketChat application and need to access cookies inside of this trigger. Is it possible ?

**Comment by Artgit** [comment]
I have implemented a server side callback inside of RocketChat application.

`RocketChat.callbacks.add 'afterValidateLogin', AfterLoginProcessor, RocketChat.callbacks.priority.HIGH`

Inside of this `AfterLoginProcessor `callback I need to create a new cookie that will be sent to the client.

Is it possible and if so please show an example.

**Comment by geekgonecrazy** [comment]
I don't believe the cookies are available there... Only thing you're gonna have access to is the properties on `login` and I doubt the cookies are there.
