### ISSUE TITLE
S3 Upload with CDN suggests domain but misses scheme

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#3466]
Your Rocket.Chat version: (make sure you are running the latest)
0.32.0

Referencing #3465 as it's a related bug. 

Description includes **"CDN domain for downloads"**, but resulting 302 redirect does not include //, OR http:// OR https:// - should instead say something like "Full URI to root of CDN".

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
