### ISSUE TITLE
Importing a slack team is importing attachments to GridFS

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#3468]
Your Rocket.Chat version: current develop 2016-06-03

I have my File Upload setting to FileSystem and it is working when manually uploading images but when I run my import from rocketchat it loads them all into GridFS

**Comment by graywolf336** [comment]
Feel free to submit a pull request for this change, the code for it is located at the Importer Base.

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-importer/server/classes/ImporterBase.coffee#L151
