### ISSUE TITLE
history is not showing

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#347]
While trying to view the history for a group the will try to redirect to /room

**Comment by rodrigok** [comment]
@oinirio are you talking about the history view where is listed the history of all channels, groups and private rooms?

Or the button "load more" inside each room?

**Comment by oinirio** [comment]
@rodrigok It's in the history view, after I click in a channel nothing happen

**Comment by rodrigok** [comment]
OK, I'll take a look ASAP

**Comment by oinirio** [comment]
@rodrigok any update on this, sorry to bother with this

**Comment by gabel** [comment]
Is this only a channel history or should I be able to search the chat history here? Nevertheless here are details about the routing error (see attached screenshot).

![image](https://cloud.githubusercontent.com/assets/242039/9243866/d74234f8-4195-11e5-8802-60947de5ef56.png)
