### ISSUE TITLE
Shared Hosting

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#3472]
Is it possible to have rocket chat running on a server that hosts other websites as well? My shared hosting I don't mean the traditional shared hosting that you would find on HostGator or whatever but it is a private server that I have running Ajenti and it hosts several other websites, I have shell access but I wonder if it is possible to install rocket chat on that server and run it without conflicts or problems?

**Comment by k0nsl** [comment]
@c0fe: yes, it should be no problem as long as there are resources available and the port being open. As for conflicts, Ajenti is python based, if I remember correctly, so there should be none.

**Comment by c0fe** [comment]
Final question, I prefer to run Debian 8 Jessie. I looked for rocket chat installation tutorial and saw a lot of ones for Ubuntu and not sure if Ubuntu is required or Debian 8 would work fine?

**Comment by c0fe** [comment]
I hate Docker and containers in general, I have setup rather complex systems and Docker has made so complex where the server just became a bowl of spaghetti.

**Comment by xenithorb** [comment]
Use Ansible then with this role: https://galaxy.ansible.com/RocketChat/Server/#readme 

It supports Jesse. 

I don't use debian, but the principle remains the same, you can see the options I changed and use to deploy to a singular AWS instance here: https://github.com/opsech-io/opsech-rocket-ansible
