### ISSUE TITLE
Able to still read private room on mobile after leaving on desktop

### ISSUE THREAD

**Issue by Isabello** [RocketChat/Rocket.Chat#3473]
Your Rocket.Chat version: 0.3.2

Upon leaving a private room on a desktop device a mobile device can still read the chat until the user navigates away from it on the mobile device. This poses some security concerns but I am not sure how you would fix it.

**Comment by disconnect3d** [comment]
Is this still not fixed?

**Comment by ggazzo** [comment]
@Isabello I cant reproduce anymore, I think it was fixed long time ago...
