### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by iojeda** [RocketChat/Rocket.Chat#3474]
Rocket chat version 0.31.0

I have Rocket.Chat install secured with an Nginx reverse proxy with TLS 1.2 enforcement.
I told a friend of mine to run an atack and he was able to get a list of all rocket.chat users and their mails using a metasploit atack.

I'm not sure if this is due to something I have done wrong with my Rocket.Chat configuration or this is an actual security issue.
Just wanted to let you know.
Thanks for this great piece of software
If I can support you in any way about this issue please let me know.

**Comment by graywolf336** [comment]
For possible security issues, please follow the [SECURITY.md](https://github.com/RocketChat/Rocket.Chat/blob/develop/SECURITY.md) instructions.
