### ISSUE TITLE
User login event on the Rocket Chat client side

### ISSUE THREAD

**Issue by Artgit** [RocketChat/Rocket.Chat#3477]
I need to catch User login event on the Rocket Chat client side. Please suggest me the point in the code where it may be possible. Thanks.

**Comment by Artgit** [comment]
Also, is it possible to send a redirect to client from a following callback:

RocketChat.callbacks.add 'afterValidateLogin', AfterLoginProcessor, RocketChat.callbacks.priority.HIGH

class AfterLoginProcessor
 constructor: (login) ->
  # how to send redirect here ?

**Comment by graywolf336** [comment]
Please see the following code for an example of tracking users logging in and out: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-piwik/client/trackEvents.js#L67
