### ISSUE TITLE
Monitoring user presence on all instances

### ISSUE THREAD

**Issue by elie222** [RocketChat/Rocket.Chat#3478]
Rocket.Chat version: 0.33.0

The server calls: `UserPresenceMonitor.start()` here: https://github.com/RocketChat/Rocket.Chat/blob/develop/server/startup/presence.coffee#L13

There doesn't seem to be a reason to do this on more than one Meteor instance. Calling `UserPresenceMonitor.start()` on one Meteor instance should be enough. (This only matters if you're running multiple Meteor instances of RocketChat.)

**Comment by geekgonecrazy** [comment]
@RocketChat/core thoughts?

**Comment by elie222** [comment]
Has anyone been using Rocket Chat at large scale? I've been seeing issues
with the Konecty package on a different app, but I need to do more to
research.

**Comment by geekgonecrazy** [comment]
@elie222 definitely being used on larger scale deployments.  @engelgabriel or @rodrigok would probably be able to better answer your questions regarding the UserPresence

**Comment by geekgonecrazy** [comment]
Was brought to my attention that had already started being discussed here: https://github.com/Konecty/meteor-user-presence/issues/17

Lets resolve any issues we have there since this is package specific.
