### ISSUE TITLE
Special characters broken if https or Reverse Proxy

### ISSUE THREAD

**Issue by hdering** [RocketChat/Rocket.Chat#3479]
Your Rocket.Chat version: 0.33.0

Hello together,

I have a strange behavior. When I go through our reverse proxy (Apache2.2) with an external URL (https://sub.mydomain.de/ redirect to http://mylocalname), special characters are displayed incorrectly:

![image](https://cloud.githubusercontent.com/assets/3204979/15858037/d58cefe4-2cbe-11e6-8203-744765ba0bec.png)

When I open the local URL (http://mylocalname) everything is ok.

Anybody has a idea?

**Comment by geekgonecrazy** [comment]
So does: `https://sub.mydomain.de/ `redirect or is it being proxied to `http://mylocalname` ?

What ever URL you are accessing the site, is what you need to set in General->Site URL

**Comment by hdering** [comment]
hi @geekgonecrazy 
it is being proxied:
`ProxyPreserveHost on

ProxyPass / http://10.54.147.103/
ProxyPassReverse / http://10.54.147.103/`

The Website-URL is the external URL (https://sub.domain.de).

**Comment by geekgonecrazy** [comment]
Seems like the proxy is doing something... but I can't figure out how.   Maybe character encoding is being altered by the proxy? 

Does it only do this with this language selection or others as well?

**Comment by hdering** [comment]
I'm so sorry....I found a mistake in my reverse proxy configuration.
I copied a configuration for rocket.chat. There was a line:
AddDefaultCharset ISO-8859-1

I removed it and now it works...

**Comment by geekgonecrazy** [comment]
@hdering ok awesome!  Glad you got it figured out 😄
