### ISSUE TITLE
Favicon not working with multiple icons sizes

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#348]
Depends on https://github.com/ejci/favico.js/issues/85
##

**Comment by marceloschmidt** [comment]
@engelgabriel has this been fixed?

**Comment by MartinSchoeler** [comment]
@engelgabriel is this still a issue?

**Comment by MartinSchoeler** [comment]
@engelgabriel I will close this issue. Reopen if this bug still exists
