### ISSUE TITLE
omnichannel wait for answer

### ISSUE THREAD

**Issue by wx-11** [RocketChat/Rocket.Chat#34837]
<details>
<summary>Chinese</summary>

使用 livechat，用户在客服不在线的时候提问，客服上线后无法收到消息。我一个人做客服，应该改成上线后可以接受到历史消息，你们觉得呢？

</details>

When using live chat, if a user asks a question while the customer service agent is offline, the agent cannot receive the message when they come online. Since I am the only one handling customer service, it might be better if agents can receive historical messages after coming online. What do you think?

**Comment by reetp** [comment]
If you don't fill out a bug template properly with your server information this will get ignored/closed.
