### ISSUE TITLE
Forward Message Not Working in Version 7.1.0

### ISSUE THREAD

**Issue by esnutd** [RocketChat/Rocket.Chat#34841]
In version 7.1.0 of Rocket.Chat, the "Forward Message" functionality is not working correctly. When attempting to forward a message:
The recipient receives an empty message instead of the original content.
Steps to Reproduce

    Open a channel or direct message in Rocket.Chat.
    Select a message to forward.
    Choose a recipient to forward the message to.
    Observe that the recipient receives an empty message.

Expected Behavior

    The recipient should receive the exact content of the forwarded message.

Actual Behavior

    The forwarded message is blank for the recipient.

Environment Details
Version:7.1.0
Apps Engine Version: 1.48.0
Node Version: v20.18.1
MongoDB: 6.0.5 / wiredTiger (oplog Enabled)

**Comment by thepiyush-303** [comment]
It is working fine in 7.2.0

**Comment by reetp** [comment]
> Environment Details
> Version:7.1.0

Hence as per the bug template & reporting advice it does say "always test on latest as your issue may be resolved"

(https://open.rocket.chat always runs latest)

Also you should fill in a complete template - full environment is usually helpful eg

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#information-that-support-or-devs-will-require

**Comment by esnutd** [comment]
> It is working fine in 7.2.0

I deployed Rocket.Chat Version: 7.2.0-rc.0, and it's not working again.

**Comment by reetp** [comment]
Tested on my own 7.0.x and open.rocket.chat which is 7.2 and it works as expected.

This seems to be related to your own environment and no evidence of a bug.

Please follow up on your original thread here.

https://open.rocket.chat/channel/support?msg=qSMFMWYtfj5p7nocJ

Closing. We  can re-open if you can provide evidence there is actually an error.
