### ISSUE TITLE
In sandstorm, can't set user email

### ISSUE THREAD

**Issue by zeigerpuppy** [RocketChat/Rocket.Chat#3484]
I am trying to enable email notifications in sandstorm, but when I try to set the user email via:

> > Administration>>Users

the program returns an error "Invalid domain".  the email is correct and I have set up the SMTP settings also.  I presume that at the moment this feature is unavailable.
Preferably it would be good to autoimport the email from the sandstorm user email and allow outgoing email if possible only for notifications.

Rocket.Chat version: 0.31.0 (Sandstorm)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
