### ISSUE TITLE
Feature Request: Global Option to Limit Invite Link Expiry Time

### ISSUE THREAD

**Issue by Parvezkhan0** [RocketChat/Rocket.Chat#34845]
Description:

Currently, Rocket.Chat lacks an admin-level option to restrict the expiry time of invite links created by channel owners or moderators. Invite links are a crucial feature for user onboarding in email-provisioned services. However, in instances where the platform is used by less experienced users, they often create invite links with "never expire" settings without proper consideration.

The short and simple nature of these links makes them susceptible to malicious actors conducting long-term harvesting operations to discover forgotten, never-expiring invite links. To mitigate this risk, administrators should have the ability to:

Globally disable the option to set links as "never expiring."
Alternatively, increase the length and complexity of invite links to make them harder to guess.

Steps to Reproduce:

Create a channel.

Generate an invite link.

Set the expiry time to "never" for the invite link.

Expected Behavior:
Channel owners or moderators should not be able to create "never expiring" invite links easily or by default.

Actual Behavior:

Any channel owner or moderator can create invite links with no expiry limit, increasing the risk of misuse or exposure.

Server Setup Information:

Rocket.Chat Version: 6.5.0

Operating System: RHEL8

Deployment Method: tar

Number of Instances: 10

DB Replicaset Oplog: Yes

NodeJS Version: 14.21.3

MongoDB Version: 5.0

Client Setup Information:

Platform: Desktop App or Browser

Version: Any

Additional Context:

As a temporary workaround, administrators can manually delete never-expiring links via Administrator > Invites, or automate the process using database cleanup scripts. However, implementing a global option for link expiry limits would provide a more efficient and permanent solution.

**Comment by reetp** [comment]
> Rocket.Chat Version: 6.5.0

Before opening a bug always test on latest code.

Your version was EOL June 2024. You should upgrade **immediately** for your own security, and keep it up to date - you should be at least on 6.5.9 

You are far more at risk through that than unexpired links.....

6.9.7 will be EOL in a few days so minimum 6.10 and preferably 7.x

(You should also upgrade Mongo to 6+)

https://docs.rocket.chat/docs/version-durability

> Expected Behavior:
> Channel owners or moderators should not be able to create "never expiring" invite links easily or by default.

That depends entirely on the admin. Some may be happy, some may not.

As you state, admins can delete them as required but I am not sure what options are available on latest and needs checking (it could even be an EE feature).

If you test on latest and want to have this considered please open in the correct repo as per this:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#is-it-a-feature-request

> If Rocket works but doesn't do something the way you want it to then this is a feature request NOT a bug. Open a request in Feature Requests
