### ISSUE TITLE
Inconsistent Alignment of UI Components

### ISSUE THREAD

**Issue by RishiSharmapro** [RocketChat/Rocket.Chat#34855]
## Problem 1: Misaligned Social Media Buttons
- **Issue**: At the bottom of the page, the social media buttons are not properly aligned. Instead of being evenly distributed or grouped in a single row, there is one button per row across five rows.  
- **Impact**: This creates a visually unappealing and inconsistent user experience. It may also result in unnecessary vertical space usage.  
- **Expected Behaviour**: All social media buttons should be aligned in a single row or distributed evenly in a grid layout to ensure proper alignment and improved aesthetics.  
- **Steps to reproduce**: 
>  1. Visit the web page on any device having width less than 768 px
> 2. Scroll to the bottom of the page 

> 

---

## Problem 2: Overflow Issue with Login Button Component
- **Issue**: When the login button is clicked, the scroll-down popup component overflows the site boundary, causing extra white space to appear on the right side of the page.  
- **Impact**: This issue disrupts the layout and results in a broken UI, negatively impacting user experience on desktop and mobile views.  
- **Expected Behaviour**: The popup should stay within the boundaries of the site and not cause horizontal scrolling or extra white space.  
- **Steps to reproduce**: 
>  1. Visit the web page on any device having width equal or greater than 1024 px
> 2. Click on the login button provided in the Navbar

---

## Problem 3: Non-Responsive Button Visibility
- **Issue**: A button that is not useful in mobile view is displayed with having no function. It should not be shown on devices with a screen width less than 1024px. 
- **Impact**: This creates unnecessary clutter in the mobile UI and could confuse users.  
- **Expected Behaviour**: The button should only be visible on devices with a screen width of **1024px or greater** and hidden on smaller screens using CSS media queries.  
- **Steps to reproduce**: 
>  1. Visit the web page on any device having width less than 1024 px
> 2. Click on the more option button shown at the right in the Navbar. 
> 3. Click on the option named "Product"
> 4. Now there is a cross button after the "Chat" and clicking on this doesn't perform any action.

---

## Problem 4: Unresponsive Cross Button in Rocket.Chat Section
- **Issue**: When the user opens the website or reloads it a section is loaded at the top of the site that provides information about Rocket.Chat contains two buttons ("Read More" and "Rocket.Chat AI") and a cross button to close the section. However, the cross button is unresponsive and fails to remove the section when clicked. I tested the site along different devices and found that this issue is present in devices with width roughly lying in [500, 1420] px 
- **Impact**: This leads to a non-functional UI component, frustrating users who wish to dismiss the section.  
- **Expected Behaviour**: Clicking the cross button should hide or remove the section dynamically ensuring a smooth and responsive experience.  
- **Steps to reproduce**: 
>  1. Visit the web page on any device having width in the above listed range.
> 2. A section in red is loaded above the navbar.  
> 3. Try clicking on the cross button 

---

### Screenshots of the above listed issues: 

- ## Problem 1: 

<img width="377" alt="Screenshot 2024-12-31 at 4 58 28 PM" src="https://github.com/user-attachments/assets/81328d5e-15f7-478c-9251-d4379b60d607" />

---

- ## Problem 2: 

<img width="1470" alt="Screenshot 2024-12-31 at 3 43 43 PM" src="https://github.com/user-attachments/assets/b6ae03ec-7f0c-4952-b267-34a8cce25296" />
<img width="1470" alt="Screenshot 2024-12-31 at 5 05 54 PM" src="https://github.com/user-attachments/assets/dcf06336-8b33-4438-b741-b06bf92dd183" />

---

- ## Problem 3: 
<img width="376" alt="Screenshot 2024-12-31 at 4 59 46 PM" src="https://github.com/user-attachments/assets/959bbe3e-a888-408e-af9b-1416d2be1ec9" />

---

- ## Problem 4: 

https://github.com/user-attachments/assets/51027942-b268-4b49-8237-153c5ddeeb95

**Comment by reetp** [comment]
These are not issues with Rocket itself but the website and do not belong here.

Please report on open.rocket.chat in the support channel.

Thanks.

**Comment by reetp** [comment]
Reported to team. No further action required.
