### ISSUE TITLE
Win2012R2 install document links to user supplied file

### ISSUE THREAD

**Issue by galmok** [RocketChat/Rocket.Chat#3486]
Your Rocket.Chat version: 0.32

The Win2012R2 manual install document links to rocket.service.js by Sing Li, but that file is first of all personal and second of all, not quite updated. 

Page in question:

https://rocket.chat/docs/installation/manual-installation/windows-server/

Link to rocket.service.js:

https://github.com/Sing-Li/bbug/blob/master/images/rocket.service.js

I received a working rocket.service.js file from @frdmn and it worked better. It included MAIL_URL support and caused the service to be registered as "Rocket Chat" instead of "rocketchat.exe" (and was not even visible in the Services view). Link to the updated rocket.service.js file:

https://gist.github.com/frdmn/27dfb2957bdbf9e8e834d920ab897864

I am not sure why the service wasn't named properly as the two files appear to be identical in the naming area. Perhaps this is a first registration problem?

**Comment by MartinSchoeler** [comment]
Please reopen this on the docs repository
