### ISSUE TITLE
no voice chat in sandstorm.io

### ISSUE THREAD

**Issue by germakoci** [RocketChat/Rocket.Chat#3487]
Your Rocket.Chat version: 0.31.0 (this is the latest that I can upload to sandstorm from the sandstorm.apps market, dated 17th of May)

I can't use the voice chat option

**Comment by ndarilek** [comment]
Happens in 0.33.0 as well. We did a test a few weeks back and couldn't get this working. I don't see anything in Firefox's error logs, and I'm not familiar enough with about:webrtc to diagnose.

I just looked briefly, and I can't sort through the layers upon layers of abstraction and packages to find exactly where it is that the Web RTC API sends ICE candidates to negotiate with remote peers. The webrtc package just seems to contain the interface code, adapter.js and the settings. Not sure I'll have time to fix but would very much like to see this resolved, and I can give it a shot if it isn't overly complex.

**Comment by Wizarth** [comment]
I've noticed (pre 0.33) that attempting to use voice/video caused the Member List tab to be stuck open, and if I switched to a different channel and attempted to use voice/video there, the console would show a permission denied error from WebRTC.

**Comment by ndarilek** [comment]
Hmm, any more insight into that error? Was there a stacktrace, was it a 
network request, etc.? I'm a bit limited in how much I can personally 
test since I'm having to fix the accessibility of the audio/video call 
interface at the same time.

**Comment by germakoci** [comment]
hi guys, sorry, no real insight into this, only thing I've noticed is that when starting the video call I can see my face instead of the other participant; I had that outside sandstorm happening as well (installed on chat.thesponge.eu) but the admin updated the version and then we could use the voice/video chat

**Comment by Wizarth** [comment]
There wasn't a stacktrack included, it seemed to just be a console.log of the object returned from the getUserMedia API, from my quick Google of the class type.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
