### ISSUE TITLE
switch between chat windows

### ISSUE THREAD

**Issue by lw-schick** [RocketChat/Rocket.Chat#3489]
I miss the possibility to have each chat in an separate window. 
This will give the possibility to switch between chats via ALT+TAB

Your Rocket.Chat version: Version 1.3.1

**Comment by seobullshit** [comment]
would be also nice to search users privat chats by STRG-F

**Comment by lw-schick** [comment]
moved to https://github.com/RocketChat/Rocket.Chat.Electron/issues/205
