### ISSUE TITLE
Implement REST-full API

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#349]
Add an initial implementation - to be fully extended in later releases.

**Comment by graywolf336** [comment]
I have a question, for documentation and personal usage purposes. The wiki displays a [login method](https://github.com/RocketChat/Rocket.Chat/wiki/REST-APIs#logon-with-rest-api) and all the other methods require authentication yet the [restapi.coffee](https://github.com/RocketChat/Rocket.Chat/blob/master/server/restapi/restapi.coffee) doesn't contain that method. My question is, how does one do authentication with the rest api?

**Comment by rodrigok** [comment]
Login is implemented by the REST lib https://github.com/kahmali/meteor-restivus/#logging-in

**Comment by graywolf336** [comment]
@rodrigok Yeah should have commented on here, but we found out I was using GET instead of POST and that's why I was getting the error.
