### ISSUE TITLE
Editing multiple messages at the same time cause the editor and script to get out of sync

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3491]
Your Rocket.Chat version: 1.3.1
1. Type 'test 1' and then press enter.
2. Type 'test 2' and then press enter.
3. Press the up (↑) arrow. 
4. Highlight the text 'test 2' and then press Ctrl+X to cut the text.
5. Press the up (↑) arrow.
6. Modify the 'test 1' text to say something different, like 'test 1-change' and then press enter.
7. Press the up (↑) arrow.

BUG: notice now that even though the 'test 2' that is highlighted, shows as empty in the text editor below. 

![image](https://cloud.githubusercontent.com/assets/10524529/15895877/884a888e-2d5b-11e6-9478-a2b59bb1c530.png)

**Comment by MartinSchoeler** [comment]
Could not reproduce this bug on the latest release, please try it out with the newest version. If you experience this issue again, please reopen this. Thanks!
