### ISSUE TITLE
Small (below recommended dimensions) avatars are not properly scaled up

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#3492]
Your Rocket.Chat version: demo instance

When you upload a smaller than recommended (20x20 instead of the 200x200 pixels) avatar, the preview actually renders it properly (http://i.imgur.com/HjtDjWe.png) , but as soon as you save the upload and apply the new avatar - it looks wrong in the proper places (http://i.imgur.com/X5SWfAP.png).

I figured that instead of scaling the small upload to the proper dimension, it's just increasing its canvas to match said dimensions.

Example avatar: https://rocketchat.iwelt.de/avatar/jonas.friedmann.jpg?_dc=0  (which now has 200 x 200 px again)

(Issue reported by @galmok)

**Comment by engelgabriel** [comment]
This have been fixed.
