### ISSUE TITLE
OTR: Key leaked?

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#3495]
Your Rocket.Chat version: 0.3.1 Desktop Windows

I don't know how this happend but seems like something got leaked (or what ever) while having an OTR conversation. I tried to reproduce it without success. So, I don't know, what it is and why it showed up suddenly client. Important:  My opponent could **not** see the key.

`{"$binary":"pCtqGYWxH4Jutphy3mTjtNJeArMm9aaajfe3vk8K+ivqk5PrhaJg/fsuzm85BurKRW5EIlvs4cSpaM55GJSVstHc2A3vFR78EuSZbiyRDOOFS4rIqnsZ3tLk3tFqSPyl51OwWQyGXjp3yECDAEvAk59DyJbrUGl4McYKZ/tZSGCSfKc9sO+FsXmBCtVEWsti9Ojm0o+/e0Wc2hnOG1bfPJsfuLnnrLZGQryl6zwxhpFAU5JujR31QbtZXmKB3tKwqVstaBpgMtxZK5niOzKKCWwwDUSU0/tiesGGIQ=="}`

**Additional infos:** My opponent tried to send messages to me, but the didn't show up on my side. On his side he got this: http://i.imgur.com/nkN4sBG.jpg

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
