### ISSUE TITLE
An & inside of an inline code is displayed wrong

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#3500]
Your Rocket.Chat version: 1.3.1 Win Desktop Client

An `&` inside of an inline code is displayed wrong

Image: http://i.imgur.com/H7wf8OS.jpg

**Comment by geekgonecrazy** [comment]
What brower are you using?

**Comment by punkr0ck** [comment]
I tested the Windows 10 desktop client, Firefox and Chrome. Everytime it's displayed wrong, like in the picture above.

**Comment by geekgonecrazy** [comment]
Interesting...

OSX Desktop Client
![image](https://cloud.githubusercontent.com/assets/51996/15980826/0b79d320-2f34-11e6-989c-9d3ce3b3c6f1.png)

Windows Desktop Client
![image](https://cloud.githubusercontent.com/assets/51996/15980856/4a01eb82-2f34-11e6-9903-c7cb6d6053c0.png)

Looks pretty much the same.  
Any thing different on your system?  Any fonts changed, and custom css.  

Does it do this for you on our demo server here:  https://demo.rocket.chat

Also assume you meant `0.31.0` does it do this if you update to `0.32.0` or `0.33.0`  ?

**Comment by punkr0ck** [comment]
Yes, on https://demo.rocket.chat it's displayed wrong, too. Tested with Firefox. Beside this, I am using the Desktop Client on Windows (version 1.3.1) - I did a mistake in the first post.

Well, I installed new fonts on Windows, but the problem was there before this. I will ask some other users on our chat (lisk.chat) to verify the problem.

**Comment by geekgonecrazy** [comment]
@punkr0ck let me know.  I'll check with the rest of the team.  For some reason this feels like we've seen and resolved this before.

**Comment by mazhead** [comment]
@geekgonecrazy have this same problem on win7, no other fonts installed. Using both client and web (firefox) and & is displayed wrongly.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
