### ISSUE TITLE
Direct messages label incorrect when messages hidden

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3501]
Version 0.32.0

If you hide all your DMs from the room list, the label reverts to:

> You haven't started any conversations yet.

![screenshot 2016-06-09 17 53 29](https://cloud.githubusercontent.com/assets/1774379/15922463/25e1741c-2e6b-11e6-8694-ccfbda563c79.png)

This is inaccurate, should say something like 'No direct messages open.' ?
For that matter the _"More direct messages..."_ and _"More channels..."_ shouldn't say "More" when there's none to begin with. Possibly "Search" or "Browse" is more accurate?

I know it's a minor issue, but creating confusion on the context of interactions increases cognitive load and detracts from good UX. Or so I'm told.

**Comment by geekgonecrazy** [comment]
I think there is an issue out here for this already.  But i'll leave this open until I find it :grin:

**Comment by MartinSchoeler** [comment]
Closing this due the new ui design, if the problem persists with the new version, please open a new issue with updated details. Thanks!
