### ISSUE TITLE
Allow manually setting user to verified without requiring username

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat#3505]
Your Rocket.Chat version: 0.33.0

Somewhat related to #3503 

If a user misplaces the email verification request email, it would be nice for admins to be able to manually mark the user as verified _without_ setting a username so they can complete the registration process (i.e: login for the first time and choose a username for themselves). Currently the username is a required field, and we either need to ask for the user for their username choice in our support conversation, or set it to some value and allow the them to edit it later.

**Comment by SeanPackham** [comment]
This feature has been implemented in a more recent version.
