### ISSUE TITLE
Integrations option to enable for all private groups in addition to all public channels

### ISSUE THREAD

**Issue by joeleaver** [RocketChat/Rocket.Chat#3506]
Your Rocket.Chat version: (make sure you are running the latest)
0.33.0

I'd like to be able to configure an integration to respond to all private groups in addition to all public channels. Right now if I want to enable an integration in any private group, I have to manually specify all public channels in the comma-separated list.

**Comment by genemachine** [comment]
I would also like the ability to set an integration globally. If a user creates a private room, I don't want to have to send them through the awkward step of contacting the administrator to allow the integration to be usable.
