### ISSUE TITLE
Support Mac feature of Paste and Match Style

### ISSUE THREAD

**Issue by justop** [RocketChat/Rocket.Chat#3508]
Your Rocket.Chat version: 1.3.1 (15) - Mac client

When I paste text from any Office product that contains formatting, Rocket pastes it as an image, which more often than not is not legible, unless it is downloaded.  Perhaps Rocket can support the Mac feature of Paste and Match Style that would paste it as pure text.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
