### ISSUE TITLE
Layout > Content interface ignores HTML Lists

### ISSUE THREAD

**Issue by LFCavalcanti** [RocketChat/Rocket.Chat#3509]
Rocket.Chat version: 0.32.0

In the Admin interface, Layout > Content both `<ul>` and `<ol>` are being ignored. The rest of the code is saved and showed, like in the Terms of Service, but the Lists are converted to paragraphs `<p>`.

Examples:

```
<ul class="topics" type="square">
        	`<li><strong>A:</strong> Something.</li>
		<li><strong>B:</strong> Something else.</li>
</ul>
```

Or...

```
<ol class="topics" type="I">
        	<li>Kitties pictures are forbidden here.</li>
		<li>All your base belong to us</li>
</ol>
```

Simple lists... everything else working, even CSS for links.

**Comment by geekgonecrazy** [comment]
@LFCavalcanti is it actually stripping out the ul and ol ?  Or is it applying css to make the list not decorated?

**Comment by LFCavalcanti** [comment]
@geekgonecrazy It is accepting all text formating from the css style, just doesn't seems to be an HTML List, just a flat paragraph.
On of the `<ol>` with type "I" have a "subtopic" with another `<ol>` with type "a", not even the text tabbing is shown, that's why it seems to have converted it to a `<p>`.

**Comment by LFCavalcanti** [comment]
**[SOLVED]**
If you need to use HTML Lists, use CSS Styles, because the inline `type=""` is ignored. Use `list-style=""` instead.

Example:

```
...
<style>
        .topics_roman {
		color:#000;
		font-family:Tahoma;
		text-align:left;
		font-size: 12px;
		line-height: 1.3;
		margin-left: 3em;
		list-style:upper-roman;
	}
</style>
...
<ol class="topics_roman">
        <li>Kitties pictures are forbidden here.</li>
        <li>All your base belong to us</li>
</ol>
...
```

**Comment by geekgonecrazy** [comment]
👍  glad you figured it out!
