### ISSUE TITLE
request: #nsfw tag

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3511]
Your Rocket.Chat version: 0.33

Hey folks,

Quick one: It would be totally awesome if we could have a nsfw (not safe for work) tag/flag, so messages don't show or show as collapsed. A complimentary "Online" and "Online at Work" or "Online at Home" status would show-by-default or hide-by-default.

Thanks & Cheers!
-Chris.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
