### ISSUE TITLE
request: Search on keyboard shortcut

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#3512]
Your Rocket.Chat version: 0.33

Hey folks,

Quick one: Instead of having to press the "+" Icon in the sidebar to search for channels, private channels and private messages, open up a search box on a (specific) keyboard action. The search should search all possible sources and show the results like it does now. But make it open/create selected chat by pressing enter only (ie, no need to touch your mouse).

Thanks & Cheers!
-Chris.

**Comment by klatys** [comment]
@christianreiss ctrl+p or cmd + p on mac should do the trick :)

**Comment by christianreiss** [comment]
How did I miss that? Awesome. Exactly what I needed. I tried everything. Thought ctrl+p is printing :)
