### ISSUE TITLE
add a report post button

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#3514]
There should be a button (preferably in the gear wheel menu) where users can report a post.

I´m not 100% sure how the solution should work but my idea is: a new channel which only Moderators and Admins can access. There a bot (cat bot?) should post a text something like this. 
![exa](https://cloud.githubusercontent.com/assets/17712562/15964362/766147ca-2f18-11e6-9f9a-197cadcf8ba1.PNG)

Also if it's possible it would be nice if the mod / admin could mark the post as "Reviewed" when he/she has reviewed it and deleted/banned the user.

Today there is a report button in the mobile UI but it doesn't do anything.. :/

Would be really really nice to have this implemented.

// Molle

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by timkinnane** [comment]
Added this as a proposal on #10174
