### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#3516]
So I am installing Rocket Chat on Debian 8

I am following this guide:

https://rocket.chat/docs/installation/manual-installation/ubuntu/#2-install-rocketchat

But I keep getting this error:

https://dpaste.de/UQZP

Can someone please help?

**Comment by klatys** [comment]
@c0fe 
Seems like mongo is not running. Can you check please?
 `# mongo --host=localhost --port=27017`

**Comment by c0fe** [comment]
Checked it, wasn't running but now getting this error:

https://dpaste.de/4nZ2

**Comment by klatys** [comment]
@c0fe Some service is already using port 80 (probably your webserver) you can set it up on different port (e.g. 3000 as mentioned in the guide) and then set your nginx to route it from port 80 (configuration described [here](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx.html)).

**Comment by c0fe** [comment]
I get this error now:

`This site can’t be reached

chat.polarpos.com refused to connect.
Search Google for chat polarpos 3000
ERR_CONNECTION_REFUSED`


https://dpaste.de/L5Zt

Also do I have to keep the SSH session running to keep rocket chat running?

**Comment by k0nsl** [comment]
What do you get if you type `curl -I localhost:3000`? And is port 3000 opened in the firewall?

The way you are running Rocket.Chat will not allow it to run if you quit the SSH session. You can use [screen](https://www.gnu.org/software/screen/manual/screen.html) to detach and reattach the Rocket.Chat session.

**Comment by c0fe** [comment]
I get this: https://dpaste.de/TT0B

**Comment by c0fe** [comment]
Seems to be working now but how do I get to listen to a specific domain such as: subdomain.domain.com?

**Comment by c0fe** [comment]
Also how can I have it properly grab on to a subdomain?

I got it set in the settings but when I try to connect I get this:

This site can’t be reached

chat.polarpos.com refused to connect.
Search Google for chat polarpos 3000
ERR_CONNECTION_REFUSED

What am I doing wrong?

**Comment by klatys** [comment]
For both running from browser and adding a ssl certificate you have to first configure your nginx - see [this nginx configuration](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx.html) as mentioned above - you are interested in part `Running behind a Nginx SSL Reverse Proxy`. If you happen to have sysadmin configuring your server, ask them, they'll know what to do. Otherwise use the instructions given.

**Comment by c0fe** [comment]
I already have Nginx running on that server for other websites. So is this better served to run on a separate server?

**Comment by klatys** [comment]
No need for that, you just have to define a separate site.
So you either have `/etc/nginx/sites-enabled/default` or something like
`/etc/nginx/sites-enabled/polarpos.com` on your disk. I suggest creating a new file at `/etc/nginx/sites-enabled/chat.polarpos.com` containing config from the guide (with your updated info of course). Also be sure to have your certificate in place, otherwise nginx won't start up again... I would test the configuration on your localhost first, since you're probably using a production machine.

**Comment by k0nsl** [comment]
@c0fe: it can be run fine on a server hosting other sites.

As for:
> Also how can I have it properly grab on to a subdomain?

Are you sure you have created the appropriate DNS records (i.e A/AAAA record) for the subdomain?

**Comment by c0fe** [comment]
@k0nsl I have entered the correct IP address in CloudFlare's DNS
@klatys I am not sure why I am not able to access when having port 3000

**Comment by c0fe** [comment]
Now I am getting this error: https://dpaste.de/YztA

**Comment by c0fe** [comment]
I got it working but when it shows this:

https://dpaste.de/tDHS

Do I have to keep the ssh session for it to keep running?

**Comment by k0nsl** [comment]
@c0fe: use my suggestion [above](https://github.com/RocketChat/Rocket.Chat/issues/3516#issuecomment-225281418).

**Comment by c0fe** [comment]
What about using forever-service?

**Comment by c0fe** [comment]
Also is it possible to run it on a different port than 3000?

**Comment by klatys** [comment]
"forever-service" is mentioned [here](https://github.com/RocketChat/Rocket.Chat/issues/3516#issuecomment-225281418) you can use different port with `export PORT=3000`

**Comment by c0fe** [comment]
Is there a way to get the SSL certificate to work without setting nginx to be as a reverse proxy? I am already using NGINX as a webserver and do not have Apache.

**Comment by k0nsl** [comment]
@c0fe:

You can try using [Caddy](https://caddyserver.com/) as your reverse proxy. It will let you configure a SSL without needing any input from you. In effect: it is effortless.

**Comment by c0fe** [comment]
Is there any plans to adding SSL support without this reverse proxy requirement?

**Comment by klatys** [comment]
That's more server setup thing than Rocketchat's I guess... BTW digitalocean also has nice step by step tutorial [here](https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04?utm_medium=social&utm_source=twitter&utm_campaign=rocketchat_ubuntu_tut&utm_content=no_image) (for ubuntu, yet most of it is the same)

**Comment by geekgonecrazy** [comment]
@c0fe Node.js / Meteor doesn't handle SSL as cleanly.  It makes more sense to let users use something like nginx to handle SSL termination.

Looks like you got things resolved.  Going to close this issue.  Please feel free to drop by our demo server: https://demo.rocket.chat/channel/support
