### ISSUE TITLE
Multiple Chrome tabs open to Rocket Chat will result in multiple desktop notifications

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3517]
Your Rocket.Chat version: v31

1. Open multiple chrome tabs and point them all to a Rocket Chat private group
2. Have one of your private message friends send you a message
BUG: multiple desktop notifications appear, one for each Rocket Chat tab

![image](https://cloud.githubusercontent.com/assets/10524529/15976826/26d8385c-2f23-11e6-9664-c6704428769a.png)

**Comment by geekgonecrazy** [comment]
If you are signed in on two / three different computers wouldn't you expect to get a notification on all computers?

**Comment by danielwegener** [comment]
Solvable using shared workers or service workers. For me it is also not uncommon to have multiple rocket chat windows/tabs open (even by accident). Moving the display of messages to a worker would also have the benefit that we could start using the [Push API](https://www.w3.org/TR/push-api/) - allow us to receive notifications even if there is NO rocket.chat tab open.

**Comment by rodorgas** [comment]
[Notification.tag](https://developer.mozilla.org/en-US/docs/Web/API/Notification/tag) could be used to minimize this issue. The browser will receive multiple notifications with the same tag, but will show only the last.

**Comment by geekgonecrazy** [comment]
@rodorgas I was un-aware of this tag.  Thanks for sharing.  I'm sure adding this would require significantly less work then adding service worker.

Not to say we don't want to add service worker.  Its just too big of a chunk to bite off right now :grin:
