### ISSUE TITLE
All Messages Mobile Push not working

### ISSUE THREAD

**Issue by jaredneedell** [RocketChat/Rocket.Chat#3519]
I added All Messages to my Mobile Push notifications settings for general and support channels in your demo rocket.chat and I still haven't gotten anything in over an hour (of being offline).

**Comment by vetash** [comment]
![ddd](https://cloud.githubusercontent.com/assets/8321589/15987016/71e4da06-304c-11e6-82e6-8bd887e0e092.PNG)
Please be sure your config is right as in screenshot save settings and restart rocket chat server.

**Comment by dukemnm** [comment]
It only works on @ not all messages.

**Comment by jaredneedell** [comment]
@dukemnm Are adding in to my issue or telling me that as a fact?

@vetash  The settings are already like this, I can test push just fine. Also I'm seeing the same issue on the demo chat server.

**Comment by mmeinert** [comment]
You need to be mentioned (with @'yourname' or @'all') or using private message, yes, it's a fact...
Work is in progress for better Mobile push notifications #2754

**Comment by TheReal1604** [comment]
@mmeinert Then the settings are really misleadingly. I have some public channels that are filled with messages from my bot about new github rc commits and something like this. I set the mobile notification to "all messages" and dont get notifications on my iphone... i have set the desktop notifications to "all messages" too, and thats working!

As additional information, i have the debug logging for mobile push messages on and don´t see some entries in the logs then my bot is posting something new in the public channel. (so no push messages are triggered internal)

**Comment by dukemnm** [comment]
Sorry for the late response @jaredneedell but like @mmeinert said, it is a fact.  been playing with settings and could not get mobile push.

**Comment by rore** [comment]
I confirm this, setting the push notification settings for a channel to "All messages" does not work, I'm not getting push notifications for messages on the channel. I am getting them on mentions so push is working in principle.

**Comment by rore** [comment]
@engelgabriel has the issue with push notifications for "all messages" been identified? it's really a problem for channels of critical issues that needs attention.

**Comment by engelgabriel** [comment]
We are working on a gib refactoring for the performance of the notifications, this should be solved when the PR gets merged.

**Comment by engelgabriel** [comment]
@rodrigok can you please confirm that this will be fixed on your refactoring?

**Comment by rodrigok** [comment]
@engelgabriel Ok, I will fix that with the refactoring

**Comment by rore** [comment]
@rodrigok @engelgabriel do you have any idea when this fix is expected? It's a major blocker for us for getting real adoption as people can't rely on actually getting notifications.

**Comment by engelgabriel** [comment]
We are moving the refactoring into the develop branch today.

**Comment by TheReal1604** [comment]
@engelgabriel Some news on this? I tested the push notifications for rooms on my 0.37.1 docker deployment and it seems that is it not working, don't get push messages from channels. But configured in the channel that I want to get all messages as push.. Hmmmm.

**Comment by Hudell** [comment]
We have recently refactored the notification system, so I'll be closing this old issue. If someone runs into this problem again, it can be reopened.
