### ISSUE TITLE
Verify Account with phone number

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#352]
we can add another option for registering steps that get and verify their number instead of email
or get and verify both of them
this can be useful for future feature to find phone contacts that use a same rocketchat site too!
##

**Comment by frdmn** [comment]
`ramin` from the RocketChat demo instance requested the same feature:

![](http://up.frd.mn/grWE3vwu9x.png)

If this ever gets implemented it would be nice if we could let him know 😁

**Comment by AhmedMashour** [comment]
any updates on this request ?

**Comment by isabellarussell** [comment]
This issue is now closed as the feature is not on our short term roadmap but may be revisited once other priorities have been addressed.
