### ISSUE TITLE
User Groups / Departments

### ISSUE THREAD

**Issue by Slind14** [RocketChat/Rocket.Chat#3522]
Seeing as the live chat module supports groups/departments is there any way to achieve something similar with channels? Being able to set join requirements on public/private channels (needs to be part of the group staff) or force join if user is part of group X?

**Comment by YuniSocial** [comment]
We are looking into this right now. Anyone have any thoughts?

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.

**Comment by ondrejtomcik** [comment]
Still not on a radar? Missing this very much: https://slackhq.com/introducing-user-groups-5a17e4531d32

**Comment by piotrkochan** [comment]
I think that this functionality is really needed and should be considered to be implemented in the future.
