### ISSUE TITLE
Make private group linkable like channels

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#3526]
Your Rocket.Chat version: 0.33.0
Channels have ability to convert hashtag and name of channel to links so we can quick go to this channel. I think rc need ability to add links for private groups too. Mb it can be use with `$` symbol.

**Comment by alexbrazier** [comment]
I think it would be good to just use `#` to link private channels as well. Currently they come up as suggestions when you start typing, but they won't be linked.

I think if the user that sends the message has permission to see the private channel, then it should be linked for everyone to see. Another issue could be to have a request to join private channel, that will send a message in the channel, or to the owner to add a user.

**Comment by jbguerraz** [comment]
I believe it should just ignore the fact it's a private channel.
If one get a link to a private channel he's not a member of, one already get a message saying something like "private channel XXX not found" which is fine IMHO.  We're using only (except #general) private channels and having working channel links would be cool !
@geekgonecrazy Is there a good reason for such behavior or a PR would be welcomed ?

**Comment by geekgonecrazy** [comment]
Added this to `feature: request` to so we can evaluate if we want this.

**Comment by sampaiodiego** [comment]
we'll support that using the same `#` symbol.. but a link will be rendered only if you're already member of that private group

**Comment by engelgabriel** [comment]
Done
