### ISSUE TITLE
Delete history for long lasting channels

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#3528]
Allow for a "delete all messages in this channel older than X" for an admin. Every time we onboard somebody, they get access to all history in chat, even when that's in no way relevant any more to ongoing affairs or even recently finished affairs. 

Or perhaps have a setting "no scrolling back more than one week" or something like that..

**Comment by geekgonecrazy** [comment]
Does #2669 fit the description of what you're wanting?

**Comment by ulope** [comment]
Sounds more like #2355

**Comment by engelgabriel** [comment]
Closed in favor of #2355
