### ISSUE TITLE
Invoking an old messages edit menu jumps to end of conversation

### ISSUE THREAD

**Issue by Schoaf** [RocketChat/Rocket.Chat#3532]
As soon as I click the little gear-wheel icon of a message that is old (I had to scroll to it), the panel scrolls right back to the end of the conversation. When I scroll back up, I can see the messages edit menu and can perform the desired action.
I cannot reproduce the issue on your demo server though.

Rocket.Chat version: 0.33.0
Windows Desktop app: 1.3.1
In the windows desktop version and in Firefox.

**Comment by geekgonecrazy** [comment]
Yeah i'm unable to reproduce. 😦  Any more info you can give for this?

**Comment by Schoaf** [comment]
Cannot reproduce it either.. Not on my pc nor on the laptop. hmm... Well, if I get it again, I'll tell you guys. ;-)

**Comment by geekgonecrazy** [comment]
👍  awesome!  I'll keep an eye out for that happening as well.
