### ISSUE TITLE
Permissions cut off if window too small

### ISSUE THREAD

**Issue by Schoaf** [RocketChat/Rocket.Chat#3533]
The permissions page gets cut off so you can't see all roles. There is no horizontal scrollbar so you have to make the window larger to see them.

![permissions_cut_off](https://cloud.githubusercontent.com/assets/13690603/15999824/8a4b7a12-3148-11e6-9d77-2c3c058cedbb.png)

Should probably be fixed together with https://github.com/RocketChat/Rocket.Chat/issues/3316

My Rocket.Chat version: 0.33.0

**Comment by alexbrazier** [comment]
@Schoaf I think there is a horizontal scrollbar at the bottom, it is just quite small and light grey

**Comment by Schoaf** [comment]
sorry, you are right. There is one :-D
