### ISSUE TITLE
File Upload from AndroidLily 

### ISSUE THREAD

**Issue by autocoder-gig** [RocketChat/Rocket.Chat#3536]
Your Rocket.Chat version: 0.33
Hi,

Was trying to the file upload from android lily app, getting error:
Exception while invoking method 'ufsWrite' Error: Match error: Expected number, got undefined at check (packages/check/match.js:33:1) at [object Object].Meteor.methods.ufsWrite (packages/jalik_ufs/ufs-methods.js:127:1) at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26) at maybeAuditArgumentChecks (livedata_server.js:1698:12) at livedata_server.js:708:19 at [object Object]..extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at livedata_server.js:706:40 at [object Object]..extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at livedata_server.js:704:46 at tryCallTwo (/home/ubuntu/Rocket.Chat/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)

File Upload using: GridFS
Its working fine from web.

What could be possible issue.

Regards,

**Comment by geekgonecrazy** [comment]
@autocoder-gig please watch the issue you created on that repo: https://github.com/RocketChat/Rocket.Chat.Android.Lily/issues/25  This is developed by a contributor, and specific to that project.
