### ISSUE TITLE
Can't download Windows version (.exe) off Rocket.Chat website

### ISSUE THREAD

**Issue by jjc12** [RocketChat/Rocket.Chat#3537]
I have Windows 8.1 and whenever I click "Download for Windows" from Rocket.Chat, I get led to the website https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.1/rocketchat-v1.3.1-win32-ia32.exe which simply displays a 404 - this is not the webpage you were looking for. 

How can I overcome this error to download Rocket.Chat for windows?

**Comment by klatys** [comment]
Hi @jjc12 correct link is https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.1/rocketchat-v1.3.1-win32-x64.exe

@RocketChatApp can someone please update the link on website? (Only windows link doesn't work)

**Comment by engelgabriel** [comment]
We have just fixed on the new website that is going live today.
