### ISSUE TITLE
Android: Notifications lower Spotify volume permanently

### ISSUE THREAD

**Issue by simopaasisalo** [RocketChat/Rocket.Chat#3538]
Your Rocket.Chat version: 0.32.0

Hi,

A minor bug; when a chat notification is received on an Android device, Spotify ( and possibly other music apps ) volumes are lowered permanently. The volume can be restored by pausing and resuming play. 
On other app notifications (for example email, Skype) the volume is lowered only for the duration of the notification sound, but is then returned to original volume.

**Comment by geekgonecrazy** [comment]
Please see: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/73
