### ISSUE TITLE
Per Channel Permissions

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#3539]
Your Rocket.Chat version: 0.33

Hey guys,

is there a way to mute all users in a channel like eg:
a right for the channel to allow chatting from only moderators or admins for a public channel.

Kind regards,

**Comment by klatys** [comment]
As far as I know no, (at least not to mute all users with one click) only one by one.
partially duplicate to #3498

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
