### ISSUE TITLE
freeze on loading screen after avatar change

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#354]
While changing the avatar if use the initials is selected or an image file the app will freeze until I select another room

**Comment by rodrigok** [comment]
We just changed how to change user's avatar. Can you test again and reopen this issue if this problem still occurs?

**Comment by oinirio** [comment]
@rodrigok latest master solve this bug, but now after ```meteor reset``` while creating a new user the general room doesn't have the text entry ![no entry text](http://i.imgur.com/X2ppfAm.png)

also I cannot upload an image to use it as avatar from firefox v39.0, in chrome works fine

**Comment by rodrigok** [comment]
Can you pull the project and test again?

I just fixed a problem with the package rocketchat-logger that is causing this problem.

**Comment by oinirio** [comment]
@rodrigok Awesome it works perfectly.

One question, Any idea why other users in my local network can't see the avatars nor the uploaded images or the initials?

**Comment by Wloa** [comment]
@rodrigok, There is no text input when using IE, and no chat post as
well. I think, we have issue with IE browser. 

 

On 29.07.2015 11:20, Oscar Rosario wrote: 

> @rodrigok [1] Awesome it works perfectly. 
> 
> One question, Any idea why other users in my local network can't see the avatars nor the uploaded images or the initials? 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/rodrigok
[2]
https://github.com/RocketChat/Rocket.Chat/issues/354#issuecomment-125987019

**Comment by rodrigok** [comment]
@oinirio No ideia.

@Wloa Can you open a new issue about this problem?
