### ISSUE TITLE
REST API  -  Deprecating v0.1

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#3541]
We are thinking of deprecating the first version of our REST API implementation.

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/restapi/restapi.coffee

Please let us know how this might impact you.

**Comment by wandonye** [comment]
For now REST api seems to be the only way I can get the list of all rooms(including direct message).
What will be the replacement?

**Comment by graywolf336** [comment]
@wandonye `channels.list`, `groups.list`, and soon `im.list`. Once everything has been added, the api mentioned in the first comment will be deprecated.

**Comment by MartinSchoeler** [comment]
@Sing-Li can this be closed?

**Comment by geekgonecrazy** [comment]
I'm going to go ahead and close this.  I don't think we ended up deprecating anything.  Please as always keep tuned to release notes before upgrading.  We will do our best to warn there if we are deprecating anything.
