### ISSUE TITLE
Idea : Integrate with Atom.io Editor

### ISSUE THREAD

**Issue by rwatts3** [RocketChat/Rocket.Chat#3542]
It would be nice to have direct integration with Atom.io. 
I'd be happy to contribute if this is something that is in consideration.

**Comment by Sing-Li** [comment]
Indeed!  

Of course, the integration has to be, if it is part of Rocket.Chat core code, chat-centric :+1:

That is, the atom.io editor can come in via a flextab  (just one idea); others welcomed.

PR of a package welcomed!

**Comment by geekgonecrazy** [comment]
I can see some code collaboration / interfacing being a cool integration.  Like invite user via rocket.chat to collaborate on code.  etc.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
