### ISSUE TITLE
Idea: integrate with itsabot

### ISSUE THREAD

**Issue by kjcsb1** [RocketChat/Rocket.Chat#3543]
Itsabot (https://github.com/itsabot/abot) is building a chat bot. There is a lot of duplication/overlap in their roadmap with what rocket.chat alread does (https://github.com/itsabot/abot/wiki/Roadmap). Could you collaborate so that they focus on the bot and you focus on the chat?

**Comment by geekgonecrazy** [comment]
@kjcsb1 thanks for sharing!  We'll check it out!

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
