### ISSUE TITLE
Can't access private groups after user name change.

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3545]
Version 0.33.0

Changed my username and lost access to previously created private groups. Assuming they need to use UID instead of name for member keys.

**Comment by geekgonecrazy** [comment]
Can you give more details on your setup when you get this?  I've renamed multiple times and have a lot of private groups, and kept them between renames.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
