### ISSUE TITLE
Automatically delete Users when using LDAP 

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#3546]
Your Rocket.Chat version: 0.33

Hey guys,

i encountered the Problem that Rocket Chat does not delete users which has been removed in the ldap. Is there a way deleting users automatically when removing in ldap?

Kind regards,

**Comment by geekgonecrazy** [comment]
I don't believe we currently sync.  We simply check the account when you try and sign in.

**Comment by scoopex** [comment]
From my point of view rocket chat should:
- should delete a user from the local user database after a specifiable amount of time if the user is not part of the ldap directory anymore
- should reject logins using the local password fallback storage after a specifiable amount of time
- should delete inactive users from the local database after a specifiable amount of time

**Comment by rodrigok** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat/issues/6174
