### ISSUE TITLE
Channel specific notification settings should also affect highlight words

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#3548]
Rocket.Chat version: 0.33

Disabling all notifications in the channel specific notification settings don't affect per-user highlight words.

**Comment by shaneleblanc** [comment]
Wanted to chime in, this is still ongoing.

Notifications about Highlight Words messages **override channel specific notification settings**. If you turn a channel's notifications setting to OFF, it should not notify you about anything - but having any Highlight words (e.g. for your first name)  will override this. 

As such, to stop receiving constant notifications in some channels (despite turning notifications off for the channel), users have to stop using the Highlight Words entirely, across all channels.

**Comment by rodrigok** [comment]
We did a [refactor](https://github.com/RocketChat/Rocket.Chat/pull/10686) in our notifications logic, this issue seems to be fixed.

I'll close it, please comment here if our version 1.0 or later still has the problem.

Thanks.
