### ISSUE TITLE
[feature] time range search, search by time

### ISSUE THREAD

**Issue by pedro-nonfree** [RocketChat/Rocket.Chat#3549]
Your Rocket.Chat version: 0.31.0

I was proposing to push more conversations to rocket chat instead of the mailing list but someone had a complain:
The problem of long discussions is that you can only search by words, regex, etc. But in mailing list archives you can also search information by time: day, week, month, year. I think this could be a valuable feature for rocket chat.

**Comment by lucasvanhalst** [comment]
This would be ideal:
 ![](https://i.imgur.com/tnJ0LIM.png)
`from:username` and `mention:username` are already supported, by the way
