### ISSUE TITLE
Video call on mac client does not work

### ISSUE THREAD

**Issue by brunoleite** [RocketChat/Rocket.Chat#3553]
Your Rocket.Chat version: 1.3.1

I've tried to use the video call or only call on mac client and it does not work, the other person does not appear on call. If I use the web client it works perfectly. I've checked http://test.webrtc.org and everything seems ok (ipv6 ignored), and I also have tested in two different networks, same problem.

**Comment by graywolf336** [comment]
You're talking about the electron client, please open an issue here: https://github.com/RocketChat/Rocket.Chat.Electron
