### ISSUE TITLE
jitsi-meet is need ssl?

### ISSUE THREAD

**Issue by tsuruchika** [RocketChat/Rocket.Chat#3559]
Your Rocket.Chat version: 0.34.0
On Docker.

I trying to version0.34.0.
jitsi-meet is activated in config.
But, alert on video call window.

* Permission Denied
    * There was an error connectiong to your microphone.
    * You hove not granted permission to use your microphone.

Rocket Chat is need SSL?

**Comment by graywolf336** [comment]
Are you using electron desktop client or your web browser?

**Comment by tsuruchika** [comment]
I use web browser.
Google Chrome.

**Comment by graywolf336** [comment]
You must setup your Rocket.Chat instance with SSL if you want to use jitsi with Chrome.
