### ISSUE TITLE
[Jitsi] Problem sharing screen

### ISSUE THREAD

**Issue by MaxVonk** [RocketChat/Rocket.Chat#3560]
Your Rocket.Chat version: 0.34.0

Love the Jitsi-addition, works fine for us, problem is that screen-sharing is a no-go.
Tried both chrome, firefox and RocketChat-application.

Extension unable to load. Installed the extension from Chrome Web Store.

**Comment by IQ2022** [comment]
Yes i love the Jitsi, same as above, Screen sharing doesn't work.. 
also i hope we can get an option to enable this with private messages or not,  it would good to have Admin to control who to enable this feature for. 
Public channel (which channel), private channel, or direct messages.

i realize its in beta so i love the fact its coming....

Thank you team Rocket

**Comment by IQ2022** [comment]
also noticed the icon keeps flashing even after shutting it down,  i disabled it from admin and it keeps flashing..

![image](https://cloud.githubusercontent.com/assets/12454319/16081617/494ec416-32dc-11e6-93d1-46b7e8088be3.png)

**Comment by geekgonecrazy** [comment]
@IQ2022 a refresh will take care of the flashing.  :smile:

Screen sharing fix is in progress also.

**Comment by tobiasmuehl** [comment]
For screen sharing you need to pack your own browser extension as explained [here](https://github.com/jitsi/jidesha/tree/master/).

But the option to add `desktopSharingChromeExtId` from admin panel is still missing. If that's added screen sharing would work! @geekgonecrazy

**Comment by geekgonecrazy** [comment]
@tobiasmuehl thanks for the hint.  Busy week, but i'll see about squeezing that into next release :smile:

**Comment by IQ2022** [comment]
has this been added to the new package :) 0.36 ?

**Comment by cryptargh** [comment]
@geekgonecrazy I just wanted to add my voice to the choir that would really, really, really want to have the Jitsi screensharing work as Jitsi is pretty bloody awesome at everything else so why not this too :)

**Comment by asthomasdk** [comment]
I am also keen to know what the status is on the screen sharing extension support. 

I tried to package my own - but I still get an error when trying to screen share.

**Comment by asthomasdk** [comment]
Just noticed that there is actually a chrome extension available to install. I was not prompted for this when we started using our own RC server setup. 

Unfortunately, the extension is not working. We keep getting a "permission denied" error when trying to use screen share.

**Comment by tobiasmuehl** [comment]
The extension needs to be compiled for every domain jitsi is running on
individually, but if I recall correctly you also need to specify the
extension's ID on the server. I linked to this a while ago in this issue

Thomas Hansen <notifications@github.com> schrieb am Do., 4. Aug. 2016 um
05:18 Uhr:

**Comment by asthomasdk** [comment]
I did try that first - but couldn't get it to work. 

I'll give it another go. 

Is there no way this can be handle dynamically so that creating a separate extension for each install can be avoided?

**Comment by j0nnii** [comment]
Hi,

Having this problem as well. I've defined Rocket.Chat setting "Chrome Extension Id" to match Jitsi Desktop Streamer extension's id, but still getting the Permission denied error. I guess separate extension is only needed if using a private Jitsi server instead meet.jit.si? Anyway tried the separate extension, but same issue with that.

**Comment by rockneverdies55** [comment]
@geekgonecrazy - is there any work being done to get screensharing to work? I was personally expecting that to be fixed with 0.37.0. Screensharing is a very important feature especially in dev environments.

**Comment by geekgonecrazy** [comment]
@rockneverdies55 Yes i'm still digging.  Its a Jitsi side error so i'm trying to track things down on that side and see what we need to change to get things working.

**Comment by cryptargh** [comment]
Excellent!

**Comment by shtefcs** [comment]
It's a true, I am not even using video conferencing cause *screen-sharing* doesn't work.

**Comment by geekgonecrazy** [comment]
Just an update for everyone.  Heard back from the Jitsi team, and they have determined the source of the problem and are working on a solution.  :+1:. So stay tuned :smile:

**Comment by geekgonecrazy** [comment]
Closing this issue in favor of the more detailed #3919
