### ISSUE TITLE
Web Cam is giving Only secure origins are allowed (see:https://goo.gl/Y0ZkNV) error

### ISSUE THREAD

**Issue by Adarsh13** [RocketChat/Rocket.Chat#3561]
Hello All
In my hosted site i am getting the below error in chrome browser, in other browsers its working fine.
## Only secure origins are allowed (see:https://goo.gl/Y0ZkNV)

my hosted link is http://10.15.20.131/index.html#/customer/searchCustomerInfo .

please suggest the solution for my problem .

Regards
Adarsh Dubey

**Comment by graywolf336** [comment]
It's saying you need to use SSL when using that feature of your Chrome browser. You need to use SSL (https) or continue using other browsers.
