### ISSUE TITLE
Add de_AT language from Lingohub "Deutsch (Österreich)"

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3564]
We've slightly modified de_DE for de_AT in Lingohub by making the language more consistent (formal "Sie" language only) and adapting it to regional usage (we always say "Chat" and "Chatgruppe", even in business environments).
Please integrate de_AT for the next release and add to the language chooser in the user settings "Deutsch (Österreich)".

**Comment by MartinSchoeler** [comment]
Added
