### ISSUE TITLE
Can't finish / leave  group call - no UI available

### ISSUE THREAD

**Issue by micshome** [RocketChat/Rocket.Chat#3565]
Your Rocket.Chat version: 0.33.0
When call to group, all users connected properly, but it is no option to finish group call, and no option to leave group call- no UI available

**Comment by Merryfurr** [comment]
Still an issue in 0.47.0 and 0.48.0-develop

**Comment by travka** [comment]
Still have a problem in MACOS app, can start call, but can't end it

**Comment by gabriellsh** [comment]
Tested on 2.4.0-develop. Everything seems fine, able do enter and exit of video calls. In any case, if you find that after updating this still happens, please, reopen this issue.
