### ISSUE TITLE
Docker File Question

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#3566]
Does the Rocket Chat docker file have everything it needs to run or do I need to have other components to add in other docker and make connections to get it to work?

**Comment by k0nsl** [comment]
@c0fe:

Yeah, it's just "plug and play" basically. You might want to put a reverse proxy such as nginx (or use [Caddy](https://caddyserver.com/) due to simplicity) in front of the Rocket.Chat instance, though.

**Comment by c0fe** [comment]
How do I put it in front? Their IRC channel isn't helpful.

**Comment by k0nsl** [comment]
@c0fe:

A few days back you already indicated that you ran nginx in front of your Rocket.Chat instance. As per:
https://github.com/RocketChat/Rocket.Chat/issues/3516#issuecomment-225367037

**Comment by c0fe** [comment]
Nope didn't run it in front just as a webserver and not using docker.

**Comment by klatys** [comment]
@c0fe Nginx can translate domain (say chat.whatever.com) to any location/port on your server (as long as dns record for that (sub)domain point to your server) so basically its always in front of everything.
If you managed to make it work before (when rocketchat ran as a service/from console) it should be basically the same setup (in short: nginx routes chat.whatever.com to localhost:3000)

**Comment by Syirrus** [comment]
I have a question about Docker. Okay so I have d/l'ed the src (Rocket.Chat) and type meteor on my local machine and all is well it runs. I have also done some editing of the src (on my local machine) and I see my augmentations. However, how the heck do you generate a Docker image from my augmented src (Rocket.Chat) that I have edited on my computer?

**Comment by c0fe** [comment]
@Syirrus this may be helpful: https://docs.docker.com/engine/userguide/containers/dockerimages/

**Comment by Syirrus** [comment]
@c0fe Thanks for the link. I have been through that guide already. I'm just not understanding how to get the code on my machine into the docker image. What do I need to specify in the Dockerfile for that to happen? Is it automagic?

**Comment by MartinSchoeler** [comment]
Closing this issue due lack of activity in a long time. 

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
