### ISSUE TITLE
rocketchat-ui-message: messagePopupConfig::popupSlashCommandsConfig commands are truncated to 11 _before_ the sort

### ISSUE THREAD

**Issue by jeffreywescott** [RocketChat/Rocket.Chat#3571]
Your Rocket.Chat version: `develop` branch

Right now, a somewhat "random" list of slash commands is displayed in the message popup when the `/` key is pressed with _no additional keys_. This is because the `getFilter` function chooses the first 11 commands in the collection _before_ they are sorted rather than _after_ they are sorted.

The end result of this is that you don't get the 11 alphabetically-first commands in the popup. Then, if a user types another key, commands seem to appear out of nowhere.

We discovered this bug after adding a custom `/cycle` command. It wouldn't show up when the user typed `/` but _would_ when the user typed `/c`. PR forthcoming.

**Comment by graywolf336** [comment]
👍  looking forward to the pull request
