### ISSUE TITLE
Browsing /avatar/ crashes RocketChat

### ISSUE THREAD

**Issue by didierm** [RocketChat/Rocket.Chat#3573]
Your Rocket.Chat version: 0.33.0

When browsing the URL https://rocketchathost/avatar/ , RC throws an error and crashes : 
```
rocketchat[23432]: events.js:72
rocketchat[23432]: throw er; // Unhandled 'error' event
rocketchat[23432]: ^
rocketchat[23432]: Error: EISDIR, read
systemd[1]: rocketchat.service: main process exited, code=exited, status=8/n/a
systemd[1]: Unit rocketchat.service entered failed state.
systemd[1]: rocketchat.service failed.
```

This is reproducible.

**Comment by mmeinert** [comment]
I don't have a crash on 0.34.0, but the web page turns to red.
Strange but not a problem at all.

**Comment by didierm** [comment]
Upgraded to RC 0.34.0 ; Rocket.Chat still crashes.

**Comment by geekgonecrazy** [comment]
@didierm if you run out of systemd does it crash?  If not there may be some tweaking needing done in your unit file

**Comment by didierm** [comment]
Running outside systemd : 
```$ MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://chathost PORT=3000 ADMIN_PASS=adminpass ADMIN_EMAIL=adminemail@domain MAIL_URL='smtp://smtphost:25/' /usr/bin/node /opt/rocketchat/Rocket.Chat/main.js```

... still crashes.

(adding any string after /avatar/, i.e. "/avatar/dummy" does not invoke a crash)

**Comment by geekgonecrazy** [comment]
@didierm so the server full crashes and you have to start it back up?  When I do this I get a red screen.  But no crash.

**Comment by didierm** [comment]
Yes, the server crashes.
A random colour is expected to be assigned when no avatar callsign is defined (i.e. /avatar/callsign), as exhibited by https://demo.rocket.chat/avatar/ .

It would be nice if someone could point us to directions on how to debug this issue (as the above log output is rather sparse), as we consider this a DoS.

@graywolf336 : what more info do you need ? Glad to provide.

**Comment by geekgonecrazy** [comment]
@didierm we mainly just need enough info to be able to reproduce this.  

So if you could start up outside of systemd, and maybe see some logs of what happened?   Running manually should give us more info then the systemd exit did.

**Comment by sampaiodiego** [comment]
@didierm what are your avatar configs (under `Admin > Accounts > Avatar`)

![image](https://cloud.githubusercontent.com/assets/8591547/16343260/753c3126-3a0c-11e6-932a-e851e70a8929.png)

**Comment by didierm** [comment]
@geekgonecrazy Running outside systemd (see my comment above, citing the invoked command line) also crashes, with the same terse error message.

``
@sampaiodiego 
Resize Avatars : True
Avatar Size : 200
Avatar Storage Type : Filesystem
Avatar Storage Path : /srv/rocketchat/data/avatars

**Comment by sampaiodiego** [comment]
Ok, I realized that it was indeed crashing the server if no username was provided and the `Storage Type` was set to `FileSystem`

So now (because of 14b3ff7), if you access /avatar/ you'll receive a 403 status.

thanks @didierm for reporting

**Comment by didierm** [comment]
@sampaiodiego Thank you, smashing two flies with one swipe !
(we considered unrestricted access to /avatar/ as somewhat fishy)
