### ISSUE TITLE
Log In button text isn't properly being flushed on Chrome in Linux

### ISSUE THREAD

**Issue by delize** [RocketChat/Rocket.Chat#3579]
Your Rocket.Chat version: 0.33

The button below the Username and Password fields was not properly cleared when typing in information, as seen below:
![image](https://cloud.githubusercontent.com/assets/4028612/16132909/1e5cc3b8-33ca-11e6-8477-fe216fb0780c.png)

**Comment by TomCelestin** [comment]
I also noticed that if you go to "Forgot your password" and come back it's stacking in the button the more you do it

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
