### ISSUE TITLE
Custom OAuth not validating.

### ISSUE THREAD

**Issue by kasperrt** [RocketChat/Rocket.Chat#3580]
Your Rocket.Chat version: latest from docker

When adding a custom OAuth provider (https://docs.dataporten.no/docs/authorization/), I get this as an error in the meteor console: 

``` Exception while invoking method 'login' Error: Service data for service testapp must include id```

I have my suspicions about the returned array is in a different form wanted by Rocket.Chat, so is there any way of specifying this, creating a plugin to take this in mind?

Here's the format the data is returned 

```
{
    "user": {
        "userid": "76a7a061-3c55-430d-8ee0-6f82ec42511f",
        "userid_sec": ["feide:andreas@uninett.no"],
        "name": "Full Display name",
        "email": "email@address.something",
        "profilephoto": "photo:ID"
    },
    "audience": "e8160a77-58f8-4006-8ee5-ab64d17a5b1e"
}
```

More info here: https://docs.dataporten.no/docs/oauth-authentication/

**Comment by FrankFang** [comment]
How did you solve this?

**Comment by kasperrt** [comment]
Added a check if the user object had the property userid. Since dataporten uses user.userid, instead of the usual user.id, it didn't see that the OAuth had gone through.
