### ISSUE TITLE
New feature request: invididual user /ignore

### ISSUE THREAD

**Issue by lilliott** [RocketChat/Rocket.Chat#3590]
Your Rocket.Chat version: Version 1.3.1 (15)

Hi everyone,

Striving to empower everyone to contribute in their personal ways and skills, on the nuitdebout.fr chat we'd clearly prefer to minimise admin tasks to the minimum and especially get rid of time-intensive moderation between users.
Offering the possibility to anyone to /ignore the messages from a specific account could definitely help. Is that something you could implement?

Thx & kind regards,
lilliott

**Comment by Hudell** [comment]
You can block direct messages from users by opening a DM window with them, clicking on the "User Info" button and then on the "Block User" option.

The blocked user will still be able to talk to you on channels that you both participate, but they won't be able to send direct messages anymore.

**Comment by marceloschmidt** [comment]
Being handled by #9785
