### ISSUE TITLE
Allow converting of Livechat users to regular users

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#3592]
Your Rocket.Chat version: latest
I have this problem for long time, mentioned few times on rocket.chat dev/support channel.

The thing is that I am using _live chat widget_ on my website [vanila.io](https://vanila.io) .

The widget is mostly for clients, but a lot developers contact me there.

I mostly tell them to register on https://chat.vanila.io to continue conversation.

But there is where problem begin. 

When _live chat user_ try to register to access chat.vanila.io, they already have created account with livechat. They can't register or find our chat channels .

This is what they see:

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/a9243dc2-4968-4a7c-9d51-e77d0cc99919/2016-06-20_1943.png)

I have this problem for months, and need to tell users to clear cookies and register again. 
Was expecting that this will be fixed, but seems not :D .

Any thoughts on this peeps ?

**Comment by dytec** [comment]
Somehow related to my issue #3269

**Comment by shtefcs** [comment]
Yeah, exactly!

**Comment by pierreozoux** [comment]
Hitting the same issue, I think it is important to have a better UX here!

**Comment by alexweissman** [comment]
I have this same issue.  I can add them manually to the rooms, but their accounts still don't show up in the Administrative "Users" panel.  It's like maybe they're in the database, but don't have any of the default user roles?

**Comment by alexweissman** [comment]
Is there any update on this?  This is really causing problems with my community, [UserFrosting](https://github.com/userfrosting/UserFrosting), because newbies will try to livechat us, no one will be around, and so they'll send me an offline message.  

When I respond to this message via email, I tell them to join the main chat, but of course that doesn't work as they are a "livechat user" with no permissions on any of our support rooms.

**Comment by geekgonecrazy** [comment]
#9048 might actually complicate this request.

**Comment by alexweissman** [comment]
> Removing livechat visitors from regular users collection will help rocket.chat run lighter **and also allows livechat visitors to become regular rocket.chat users.**

Hmm, sounds like it's intended to fix this very problem!  @sampaiodiego can you confirm?

**Comment by shtefcs** [comment]
Honestly I stopped using livechat feature cause of that.

**Comment by sampaiodiego** [comment]
alright, #9048 actually fixes the issue @shtefcs was having. he can now tell his livechat visitors to access his rocket.chat URL and register. :smile:

**Comment by shtefcs** [comment]
Finally ^^ . Thanks Diego and others 👍
