### ISSUE TITLE
Showing messages only from selected users in public & private channels/groups 

### ISSUE THREAD

**Issue by shtefcs** [RocketChat/Rocket.Chat#3593]
Your Rocket.Chat version: latest

This is what I find it very useful.

Sometimes when I open my chat I see 200-300 new messages. There are new users, old and a lot of messages are exchanged.

What I thought it would be really great to have is to be able to filter and show all messages of particular user.

This will give you fast and easy way to get back and read all messages from that users and bring back in conversation/context.

Does anyone thought about this feature, or its only me being weird :D  ?

Peace

**Comment by shtefcs** [comment]
Anyone ? :)

**Comment by marceloschmidt** [comment]
Please open a topic on our [forum](https://forums.rocket.chat/c/feature-requests) to discuss the implementation. Personally, I don't think it makes too much sense :)

**Comment by shtefcs** [comment]
It doesn't have sense to you probably cause you didn't have that kind scenarios where its needed. 

If 500 messages happen on the channel, by 57 users, and u want to see what specific user wrote how would you do? Of course, consider that is very important to you. 

So you would scroll trough all 500 messages to find the you need it, and we all know how RC is slow and heavy when you have lot of messages to load.

Anyway, that was just a suggestion from my POV, since I needed lot of times on busy chats.
