### ISSUE TITLE
Atlassian Crowd Integration

### ISSUE THREAD

**Issue by Intox123** [RocketChat/Rocket.Chat#3594]
Your Rocket.Chat version: 0.33

I have been looking at Rocket.Chat as a solution in my corporate setting and we require Atlassian Crowd integration for our user management. I see that it doesn't currently support it out of the box so I've been working on implementing it myself using [this](https://github.com/wehkamp/atlassian-crowd-client/) npm module

I've had a few ideas about how to implement it but was wondering if I could get some feedback from people/devs on whether or not I should
1. Just authenticate users and create them in the user table when they first authenticate
2. Sync users by copying all users from a crowd group into Rocket.Chat's user table and allowing them to authenticate after their user exists in the table? (periodically then syncing the users to a set interval, a bit like other Atlassian products I believe)

Thanks

**Comment by SQUIDwarrior** [comment]
I think you should make it work the same as LDAP authentication. I am running Rocket.Chat using LDAP authentication and it works like this:

1. If the user exists in LDAP, but has not logged into Rocket.Chat for the first time, there is no user entry in Rocket.Chat
2. Once the user logs into Rocket.Chat for the first time using their LDAP credentials, a user entry is created in Rocket.Chat according to the LDAP mapping settings
3. At some regular interval, Rocket.Chat syncs data from LDAP for existing users and updates as necessary. But no users are auto-populated.
