### ISSUE TITLE
Hidden Registration Internationalisation

### ISSUE THREAD

**Issue by HuntStarJonny** [RocketChat/Rocket.Chat#3595]
I tried rocketchat for the first time and stumbled accross a annoying problem, that should be easy to fix.
The sample Text under hidden registration says in german
"Beispiel: https://demo.rocket.chat/registrieren/[geheimer_schluessel]"
so i invest some time to find out why https://rocketchat.example.de/registrieren/somehiddenurl didn't work for me.
After some searching i tried after many many other https://rocketchat.example.de/register/somehiddenurl and it worked fine.
Just change the sample text to "Beispiel: https://demo.rocket.chat/register/[geheimer_schluessel]" to
 avoid other users wasting their time.

If someone tell me where the correspondening file is, i can fix the code too.

**Comment by dytec** [comment]
Good catch!
You can change it in the i18n files:
Rocket.Chat/packages/rocketchat-lib/i18n/de.i18n.json
and
Rocket.Chat/packages/rocketchat-lib/i18n/de-AT.i18n.json

Line 96
