### ISSUE TITLE
Blackberry push service

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3597]
We have successfully tested Rocket.Chat on Blackberry and created a BAR for it. However, it does not show notifications yet, as it requires its own push service. 
This seems to be the right source for push on Cordova based apps: https://github.com/raix/PushPlugin 
Ideally, Rocket.Chat is offering a BAR with their own keys and [register a push service at Blackberry](https://developer.blackberry.com/services/push/), so that this can be also used with the RC gateway.

**Comment by ArchGalileu** [comment]
Hello rasos
I have an BlackBerry Passport, where is the BAR?

Best regards
ArchGalileu

**Comment by rasos** [comment]
Here is our test BAR with a developer key, valid for 3 months:
 http://92.222.23.45/owncloud/index.php/s/rhEvuvUObPHXj4A - 
Application ID: 	300088-h59715e2r8y26821o6r636400ae2577e0
Push Registration URL: 	http://cp300088.pushapi.eval.blackberry.com 
I probably should not post the password here, tell me where to send it to if you want to test.

To create a BAR with your own keys requires some bureaucratic steps.  Follow this tutorial:
https://developer.blackberry.com/html5/documentation/v2_2/testing_and_signing_setu
p.html
You need to install Blackberry Command Line tools https://developer.blackberry.com/android/tools/
to package and deploy with the „BlackBerry APK Packager“
You register for a free push service here: https://developer.blackberry.com/services/push/ and need to fill out the form here: https://www.blackberry.com/profile/?eventId=8207

**Comment by rasos** [comment]
We have tested the Android App on Blackberry, which does a fairly good job. Rocket.Chat also works fine with the buil-in BB browser. 
So this issue can be considered low priority or even be closed.

**Comment by mathewjpotter** [comment]
Hey I am wondering if I could get some help, I am using a passport and would like to get rocket chat working I tried using the legacy cordova app 2.8 but it does not connect to my rocket chat server, even though I enabled it in the settings. my rocket chat server is 2.4 app engine is 1.11 , the app does work decently from the fire fox browser , but getting a push notification established for messages would be ideal
