### ISSUE TITLE
iOS App Send Button

### ISSUE THREAD

**Issue by jprone** [RocketChat/Rocket.Chat#3598]
Your Rocket.Chat version: iOS 9.3.2 (iPhone 6s) Version 2.3.1

The send button (the button which is a flat image of a paper airplane) feels like its area of influence 
should be a little larger.  It's really easy to accidentally tap on the UI space below the "Message" field and above the grey bar that contains the buttons "<" ">"                                    "Done", which effectively hides the iOS keyboard rather than sending the message.

The button I'm referring to is detailed with red, and the UI space below the "Message" field is detailed in green in the following imgur upload.

http://i.imgur.com/VIl9fci.png

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
