### ISSUE TITLE
download mailing list

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3600]
nice to have a feature for Admin download a mailing list? or user list?
in addition the above ask.
I think its the most part of the chat tool is to have the ability to backup your current user base.. if anything happens to the server, or app.. can be recoverable. but users and their password need to be backup up and pulled out of the server ... if you can enable this feature it would be really useful
Your Rocket.Chat version: (make sure you are running the latest)

**Comment by IQ2022** [comment]
is there a way to download email list??? into CVS from admin side???? it should be easy no?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close.

Closing this, since you could easily select this from mongodb.

Cheers
Thomas
