### ISSUE TITLE
posting to multiple rooms

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3601]
Is there a way to add a command or a feature that when someone types a message can automatically sent to another channel for records? 
 example : 
am in general room and i decided to take a trade 
"buy 1000 $AAPL" + command 
this message will be copied to a different room called #trades 
vs me copying that message over? 

does it make sense :) 
Your Rocket.Chat version:0.34

**Comment by lucasvanhalst** [comment]
I'm fairly sure you could create a hubot script that would do this 
Similar to this: https://github.com/RocketChat/hubot-rocketchat/issues/126#issuecomment-225286769
but instead of `updateMessage` you would have to call `sendMessage` (see https://github.com/RocketChat/Rocket.Chat/blob/f90c48b5c1fbee48a39a506b3985d758e1ecb90b/packages/rocketchat-lib/server/methods/sendMessage.coffee)

You can have the bot listen to 'buy [number] [symbol]' and send it to a particular room if a message matches this requirement

**Comment by IQ2022** [comment]
wish there is step by step on how to do that?

**Comment by lucasvanhalst** [comment]
Well you could start by deploying a hubot and linking it to your rocket.chat server. 

If you're willing to use docker it's easy, copy paste this file in some directory on your server (preferable somewhere in /opt or so) and call it `docker-compose.yml`: https://gist.github.com/lucasvanhalst/7c4b2cd563fccae822d221caa3217b15  (this is mainly copied from here https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml)
adjust the parameters as necessary (ROCKETCHAT_USER could be 'bot' for example, this is an account you have to create and it will be used to post as the bot)
Create a folder in the directory where you placed your docker-compose called 'data' and in that folder another one called 'hubot-scripts'. In this last folder you can place any custom scripts you like and they will be added to the hubot when you start it

Execute the command `docker-compose up hubot` and it should be up and running.

The script itself could look something like this (call it `hubot-respond-to-buy.js' or something like that and place it in the data/hubot-scripts folder):
```javascript
module.exports = function (robot) {
        function sendMessage(newMessage) {
                return robot.adapter.callMethod('sendMessage', {
                        rid: 'room-id-where-the-message-should-go',
                        msg: newMessage
                })["catch"](function (err) {
                        return console.error(err);
                });
        }

        robot.hear(/buy ([0-9]+) (.*)/ig, function (msg) {
                var newMessage, amount , symbol;
                amount = msg.match[1];
                symbol = msg.match[2]
                newMessage = msg.message.user + ' wants to buy ' + amount + ' of ' + symbol;
                sendMessage(newMessage);
        });
};
```
You should replace `room-id-where-the-message-should-go` with the actual room id. Unfortunately you can't view it easily, only by using inspect element in the browser or in the database directly.
To test you could put `GENERAL` as room id as every rocket.chat instance has a room with this id unless you've deleted it.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by timkinnane** [comment]
Added this as a proposal on #10174
