### ISSUE TITLE
Removing user from room is not possible.

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#3603]
Your Rocket.Chat version: 0.34.0

When I try to remove a user from the room it says `invalid role`, as per:
![invalid role](https://k0nsl.img-cdn.ru/chrome_2016-06-21_22-15-29.png "Invalid role")

This has actually been a problem since at least three versions back, but I just presumed it had been fixed already :)

**Comment by Deepakkothandan** [comment]
@Rocketchat/core  Agreed, facing the same error with version 0.34.0

**Comment by xadhoom** [comment]
to be fair, even if the message pops up, the user is currently removed from the room.

**Comment by k0nsl** [comment]
@xadhoom: no, the user is still in the room -- you would need to click "DEACTIVATE" to actually disable the user.

**Comment by xadhoom** [comment]
mmmh in my case if I close the user details and check into members list the user is not there anymore.

to reproduce:
* open members list
* select one user, the userInfo flextab opens
* click remove user
* dialog opens with confirm request, check ok -> error
* close the dialog, select "show all" on the flextab and the user is not there anymore
