### ISSUE TITLE
Layout->Colors, changed each color value, now color changes do not take effect, errors visible in the logs

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#3605]
Your Rocket.Chat version: 0.34.0
Ubuntu 14:04

steps to reproduce:
- Go to the layouts/colors config, and change every color value
- Refresh the page, colors have changed
- Go back to layouts/colors and change values to something less horrific, save and refresh 

The changes do not take effect, and I am trapped with the worst possible colors with no real avenue of escape except for a reinstall. I found this in the logs after restarting the service

```
I20160621-22:15:44.587(-4) Updating process.env.MAIL_URL 
I20160621-22:15:47.140(-4) { [Error: error evaluating function `lighten`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 180775,   line: 7418,   callLine: NaN,   callExtract: undefined,   column: 21,   extract:     [ '\t\t&::before {',      '\t\t\tbackground-color: lighten(@info-active-font-color, 25%);',      '\t\t}' ],   message: 'error evaluating function `lighten`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160621-22:15:47.178(-4) ufs: store created at  
I20160621-22:15:48.525(-4) (migrations.js:114) Migrations: Not migrating, already at version 54
I20160621-22:15:49.353(-4) { [Error: error evaluating function `lighten`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 180775,   line: 7418,   callLine: NaN,   callExtract: undefined,   column: 21,   extract:     [ '\t\t&::before {',      '\t\t\tbackground-color: lighten(@info-active-font-color, 25%);',      '\t\t}' ],   message: 'error evaluating function `lighten`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160621-22:15:50.106(-4) { [Error: error evaluating function `lighten`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 180775,   line: 7418,   callLine: NaN,   callExtract: undefined,   column: 21,   extract:     [ '\t\t&::before {',      '\t\t\tbackground-color: lighten(@info-active-font-color, 25%);',      '\t\t}' ],   message: 'error evaluating function `lighten`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160621-22:15:50.108(-4) Updating process.env.MAIL_URL 
```

**Comment by jszaszvari** [comment]
Having the same issue here as of this-morning

In the logs

rocketchat:theme ➔ stop_rendering 344 
I20160904-22:22:49.963(0) { [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 182591,   line: 7592,   callLine: NaN,   callExtract: undefined,   column: 20,   extract:     [ '\t&:after {',      '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',      '\t}' ],   message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160904-22:22:58.425(0) Expression 
I20160904-22:22:58.426(0) { value: [ { value: 303, unit: [Object] }, { value: 4, unit: [Object] } ] } 
I20160904-22:22:58.428(0) rocketchat:theme ➔ stop_rendering 343 

I20160904-22:22:58.429(0) { [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 182591,   line: 7592,   callLine: NaN,   callExtract: undefined,   column: 20,   extract:     [ '\t&:after {',      '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',      '\t}' ],   message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160904-22:23:36.909(0) Expression 
I20160904-22:23:36.910(0) { value: [ { value: 303, unit: [Object] }, { value: 4, unit: [Object] } ] } 

I20160904-22:23:36.912(0) rocketchat:theme ➔ stop_rendering 461 
I20160904-22:23:36.913(0) { [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 182511,   line: 7592,   callLine: NaN,   callExtract: undefined,   column: 20,   extract:     [ '\t&:after {',      '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',      '\t}' ],   message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',   stack: undefined }

**Comment by engelgabriel** [comment]
Now we have a RESET button by the setting, so you can get the default value back.
