### ISSUE TITLE
Importing HipChat Data - Not Respecting Private Chat Groups

### ISSUE THREAD

**Issue by delize** [RocketChat/Rocket.Chat#3606]
Your Rocket.Chat version: .33
RocketChat is unable to respect privacy in regards to chat rooms.

When importing RocketChat data, Private Chat rooms are set to Public after import is complete.

I mentioned this to @geekgonecrazy in #support but never got a reply back, after replying to him.

**Comment by geekgonecrazy** [comment]
As mentioned when we talked there, its something we have to improve on.  👍
