### ISSUE TITLE
[Jitsi] Feature Request: Audo conference and Push to talk would be great

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#3607]
I'd like to see the a way to create audio-only-conferences. Alongside with a way to activate push to talk, as far as i am aware of it jitsi included push to talk a while back.

**Comment by IQ2022** [comment]
i like this idea to be used along with text chat, sometimes you dont want to type just voice chat, and to have ability to moderate it with raising hands even cooler :D

**Comment by hughlroberts** [comment]
Like this idea.

**Comment by a-t101** [comment]
https://github.com/jitsi/jitsi-android/issues/52 
I post the issue too,  :-D
Did anyone do something interesting and let us know what he did?
I really appreciate.

**Comment by HammyHavoc** [comment]
I want to see this too.

**Comment by bryandesrosiers** [comment]
I want to see this too.

**Comment by bryandesrosiers** [comment]
I also want to see this incorporated into Rocket Chat, please and thank you.

**Comment by reetp** [comment]
All NFRs are now being referred to the forums for discussion.

Please open a new thread there please https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
