### ISSUE TITLE
Leaving private video chat javascript error

### ISSUE THREAD

**Issue by galmok** [RocketChat/Rocket.Chat#3610]
Your Rocket.Chat version: official demo (probably latest stable, 0.34)

I was video chatting (me and one more), and left the video chat by selecting a forum (#support) and this error popped up in the javascript console:

> Room Changed... Close panel! a1a497eade21536bef6f3d38bbdbef1990cc4aec.js?meteor_js_resource=true:412
> Exception in defer callback: TypeError: undefined is not a function
> at t.extend.withValue (https://cdn-demo.rocket.chat/a1a497eade21536bef6f3d38bbdbef1990cc4aec.js?meteor_js_resource=true:3:6576)
> at https://cdn-demo.rocket.chat/a1a497eade21536bef6f3d38bbdbef1990cc4aec.js?meteor_js_resource=true:3:2784
> at Object.<anonymous> (https://cdn-demo.rocket.chat/a1a497eade21536bef6f3d38bbdbef1990cc4aec.js?meteor_js_resource=true:3:6834)
> at e (https://cdn-demo.rocket.chat/a1a497eade21536bef6f3d38bbdbef1990cc4aec.js?meteor_js_resource=true:3:2037) a1a497eade21536bef6f3d38bbdbef1990cc4aec.js?meteor_js_resource=true:3
> Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by geekgonecrazy** [comment]
@galmok Thanks for reporting this. We'll take a look.  Did anything visually break when this happened?

**Comment by galmok** [comment]
I don't remember seeing any visual corruption.
Den 28. jun. 2016 19.17 skrev "Aaron Ogle" <notifications@github.com>:

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
