### ISSUE TITLE
Android native share to rocket.chat results in blank file upload

### ISSUE THREAD

**Issue by k3vmcd** [RocketChat/Rocket.Chat#3611]
Rocket.Chat version: 0.34.0

File uploads configured to use S3 and successfully uploading from Android when starting upload from within the Rocket.Chat app (using the paperclip icon).

When browsing media and using the native Android share link, then selecting to share on Rocket.Chat and choosing a channel, the confirmation window shows the file preview and the user clicks to begin upload. When the upload completes, it is only a blank placeholder in Rocket.Chat. Browsing in S3 confirms the file did not upload correctly and is blank.

**Comment by xenithorb** [comment]
Duplicates #3724
