### ISSUE TITLE
how to update the Rocket.Chat platform to newest version in rocket chat docker container on AWS.

### ISSUE THREAD

**Issue by abhilash07** [RocketChat/Rocket.Chat#3613]
Rocket.Chat version: 0.31.0

i have deployed rocket chat over AWS environment along Rocket-chat containers, now i am looking for instructions to backup my data and update my rocket.chat (0.31.0)  to latest version 0.34.0 on AWS rocket chat docker container. Please guide me. Thanks in advance. 

Abhilash

**Comment by continuouslee** [comment]
@abhilash07 - If you have a separate mongo instance that you tied your rocket.chat docker container to, this is quite easy.  

1. `docker stop rocketchat` ##what ever the name or id is of the rocket.chat container
2. `docker pull rocketchat/rocket.chat`
3. `docker start rocketchat`

You should not be using Rocket.Chat and MongoDB in the same instance.

**Comment by abhilash07** [comment]
Hi Lee Faus

thanks for your information i have attached my environment please let me know is it enough if i follow the above process to update my rocket.chat

![2016-06-23 1 - copy](https://cloud.githubusercontent.com/assets/10971841/16292879/6f9f528c-3950-11e6-8822-a75f7df8b840.png)
![2016-06-23 1](https://cloud.githubusercontent.com/assets/10971841/16292880/71034e08-3950-11e6-9341-8e421f1048e1.png)

**Comment by continuouslee** [comment]
Yes. Here is what you should be able to do:

1. `docker stop rocketchat_rocketchat_1`
2. `docker pull rocketchat/rocket.chat`
3. `docker start rocketchat`

That should be it.  If this solves your problem, please close the issue.
