### ISSUE TITLE
Links not supported in attachment titles

### ISSUE THREAD

**Issue by gustavkarlsson** [RocketChat/Rocket.Chat#3614]
Adding a link using the format `<URL|TEXT>` to an attachment title displays it verbatim instead of formatting it as a link. It seems to work fine in the attachment text field.

I see no reason why it shouldn't be supported in title fields.

Rocket.Chat version: 0.33.0

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
