### ISSUE TITLE
Feature request: Add polls

### ISSUE THREAD

**Issue by simopaasisalo** [RocketChat/Rocket.Chat#3615]
Hi,

Could there be an option to create polls in a channel? For example, a possible use case would be to vote on the time of a meeting.

This would be a useful feature for many of our teams using Rocket Chat.

**Comment by dohseven** [comment]
Seems like something was done in https://github.com/RocketChat/Rocket.Chat/issues/3244, but the current status is unknown.

**Comment by dohseven** [comment]
Check this script (https://gist.github.com/sampaiodiego/db4b60717e7ac0051024dde23c6a902e) and the How to install section in the comments.

**Comment by IQ2022** [comment]
it didnt work with the comments, did you have to use the exact Alias name and rocket.cat?

**Comment by TheReal1604** [comment]
Absolutely working for me: 

![image](https://cloud.githubusercontent.com/assets/5877910/16309978/f2f7c0f0-396a-11e6-9d9d-b14dabff17d2.png)

Just followed the instructions from @graywolf336 in the gist.

**Comment by IQ2022** [comment]
would there be any ability to make those options clickable ? vs reacting by emoji?

**Comment by ianubhav** [comment]
Its not working says poll comand not found

**Comment by graywolf336** [comment]
@ianubhav I updated my installation text on the gist: https://gist.github.com/sampaiodiego/db4b60717e7ac0051024dde23c6a902e#gistcomment-1808702

**Comment by designgurudotorg** [comment]
I know its been a few months since this script was written - should it still work as written up by @graywolf336 ? Haven't been able to get it to work today no matter what token I'm using (using RC 0.56.0)

**Comment by rasos** [comment]
Related to #4102 . Anybody tried with bots like in Telegram ? https://telegram-store.com/blog/telegram-polls/

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #4102, as it's the same overall topic.

Cheers
Thomas
