### ISSUE TITLE
Feature Request:  Allow user to specify callback url in custom oauth module

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#3617]
Your Rocket.Chat version: 0.30.0

The custom oauth module currently builds the callback url for the user to provide to the OAuth provider, i.e. for https://rc-server.mydomain.com/_oauth/customuritest.  One of our providers doesn't respond well to the "/_oauth/" portion of the url (specifically the "/_" causes problems).  I know that comes from the underlying Meteor layer, but would it possible to allow the user to specify the callback url (or at least a potion of it to get around this issue)?

**Comment by skug67** [comment]
I noticed the same problem here and in the cas module.  It's particularly problematic for me because I'm running rocketchat at a suburl via Passenger/Apache, so sending the callback directly to /_cas/ means that it never makes it to my rocketchat server.....

**Comment by skug67** [comment]
Seems like this (or at least my piece of this) may be related to #2518, perhaps the fix didn't clean up quite all the URLs that were needed.

**Comment by geekgonecrazy** [comment]
if you have any specific oauth provider that doesn't like `/_oauth/` maybe open issue specifically about that so we can take a look in detail.  Closing due to age and no further reports
