### ISSUE TITLE
iOS Push Notifications configuration

### ISSUE THREAD

**Issue by gotev** [RocketChat/Rocket.Chat#3620]
Hi,
I'm using Rocket.Chat 0.34 for developers:

``` shell
git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor --mobile-server http://192.168.1.170:3000
```

 and I'm having problems in configuring the push notifications for iOS. GCM works.
I've followed this guide: https://github.com/raix/push/blob/v3.x/docs%2FIOS.md
and I have the `pem` files for the private key and the certificate. I can successfully connect to APNS from command line:

``` shell
openssl s_client -connect gateway.sandbox.push.apple.com:2195 
    -cert PushChatCert.pem -key PushChatKey.pem
```

I've tried to simply copy and paste the contents of the two `pem` files into the GUI:
![schermata 2016-06-24 alle 10 23 35](https://cloud.githubusercontent.com/assets/16792495/16332405/00bc781c-39f6-11e6-8938-492f24967bfb.png)

but then when I try to send test push notifications, what I get from the meteor command line is the following:

```
W20160624-10:09:31.913(2)? (STDERR) /Users/alex/.meteor/packages/raix_push/.3.0.2.17x4rsd++os+web.browser+web.cordova/npm/node_modules/apn/node_modules/q/q.js:155
W20160624-10:09:31.913(2)? (STDERR)                 throw e;
W20160624-10:09:31.913(2)? (STDERR)                       ^
W20160624-10:09:31.913(2)? (STDERR) Error: 140735312175104:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 40
W20160624-10:09:31.913(2)? (STDERR) 
W20160624-10:09:31.913(2)? (STDERR)     at SlabBuffer.use (tls.js:235:18)
W20160624-10:09:31.913(2)? (STDERR)     at CleartextStream.read [as _read] (tls.js:455:29)
W20160624-10:09:31.913(2)? (STDERR)     at CleartextStream.Readable.read (_stream_readable.js:341:10)
W20160624-10:09:31.913(2)? (STDERR)     at EncryptedStream.write [as _write] (tls.js:369:25)
W20160624-10:09:31.914(2)? (STDERR)     at doWrite (_stream_writable.js:226:10)
W20160624-10:09:31.914(2)? (STDERR)     at writeOrBuffer (_stream_writable.js:216:5)
W20160624-10:09:31.914(2)? (STDERR)     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
W20160624-10:09:31.914(2)? (STDERR)     at write (_stream_readable.js:602:24)
W20160624-10:09:31.914(2)? (STDERR)     at flow (_stream_readable.js:611:7)
W20160624-10:09:31.914(2)? (STDERR)     at Socket.pipeOnReadable (_stream_readable.js:643:5)
W20160624-10:09:31.914(2)? (STDERR)     at Socket.emit (events.js:92:17)
=> Exited with code: 8
```

and then the server restarts. I don't know if I've done something wrong in the configuration or if it's a bug. Can anyone help me address this issue?
Thank you!

**Comment by geekgonecrazy** [comment]
Are you deploying the mobile apps using meteor or are you using our cordova app?  Just to help narrow this down a bit.

**Comment by gotev** [comment]
I've built the Cordova app from sources and I have set the Apple push certificates in it using my iOS developer account.

**Comment by pandix** [comment]
I have pretty much the same problem with Rocket Chat app source builded with xcode ... Whatever the config in the admin panel, it says "no token for this user" but everything works perfectly elsewere

**Comment by gotev** [comment]
@pandix what have you set in the Rocket Chat server GUI as APN key and APN certificate?

**Comment by pandix** [comment]
I've tried to leave the APN passphrase blank (as I didn't set any password for my certificates, and then I tried with a simple password, both didn't work). APN certificate I paste the one I get following the tutorial on rocket.chat doc (same thing for APN key) ... I'm sure i'm missing something in the config, may be the APN key is not what I thought. I didn't set an SSL connexion on my website, http only, may be it is a problem for APN servers ?

**Comment by BlockChainSG** [comment]
Hello, did anyone get to resolve this?

**Comment by imrealashu** [comment]
Hey, any luck with this issue ? As I'm too confused with the way. I'm not quite sure how and in which format we need to add the certificate contents as well as content of APN keys...

**Comment by zaphod534** [comment]
I'm having the exact same problem. Where can we find a more detailed guide on how to configure Push Notification for iOS? I followed this [guide](https://github.com/raix/push/blob/v3.x/docs/IOS.md). 
If I enable log, I get this error when trying to send push notification:
```
Push: Send message "mario" via query { userId: 'yyyyyyyyyyyyyyy' } 
send to token { apn: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
Got error code 515 for token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
```

Any news?  @geekgonecrazy

**Comment by imrealashu** [comment]
Try putting the content of `.pem` file in both fields `APN KEYS` and `APN CERTS`. It'll work. 👍

**Comment by zaphod534** [comment]
Thanks for the quick reply :)
Do you mean the combined pem with certificate and key? 
I've tried it, but still get the same error...

**Comment by imrealashu** [comment]
Did you Restarted the Rocket Chat server after configuring?

**Comment by zaphod534** [comment]
Eeeeemh... no! I restart the server and it works!!!! 
Thank you so much 🥇

**Comment by liminary** [comment]
@imrealashu @zaphod534 

Hi, I tried to copy the entire PEM file using cat command (starting with "-----BEGIN CERTIFICATE-----" and ending with "-----END ENCRYPTED PRIVATE KEY-----" into both APN Key and APN Cert with the passphrase I entered. Still, it does not work after I restart the server. The log showed sent message "" to 0 ios apps 0 android apps.

**Comment by reetp** [comment]
I think this can be closed. We are on rocket 0.70.4 and there are much newer clients available.

Please reopen in the appropriate section if you have further issues

**Comment by reetp** [comment]
@rocket-cat close
