### ISSUE TITLE
Option to disable auto join to channel on mention

### ISSUE THREAD

**Issue by afaizal** [RocketChat/Rocket.Chat#3621]
Your Rocket.Chat version: (make sure you are running the latest)
If I mention an user to channel room, the user will auto join to my channel.
Can I change this settings?
so users can only join if they press join channel button

**Comment by Svenito** [comment]
:+1: on this

**Comment by andersonluciano** [comment]
Hey, 
This feature will be developed?

**Comment by Flauschbaellchen** [comment]
Would be great if a user chan choose between the following:
* Auto-join on mention  (but not if it's a private one)
* Email on mention if not part of the channel (but not if it's a private one)
* completely disable email and auto-join

A default setting within the administration panel would be great, too.

**Comment by stbc** [comment]
Would love to see that! 👍

**Comment by SeanPackham** [comment]
in more recent versions of Rocket.Chat @'ing someone does not automatically invite them. You have to manually invite them

**Comment by attrib** [comment]
@SeanPackham With 0.63.3 I still get auto invited and I can't find any option to change this. 

Its only solved for private groups, but not for public channels.

**Comment by petcg** [comment]
> in more recent versions of Rocket.Chat @'ing someone does not automatically invite them. You have to manually invite them

I think that is quite a breaking change.

We have depended on **auto-join on mention**.
Users should be able to allow it or not, and it should be enabled by default for compatibility.

The title of this issue is "Option to disable auto join to channel on mention".

Currently, there is no option, and I think this should be reopened.

**Comment by Eiken** [comment]
I also think this should be reopened. I get mentioned a lot but have no interest to join each projects rooms.
