### ISSUE TITLE
Improve context menu in Desktop client

### ISSUE THREAD

**Issue by pdfforge** [RocketChat/Rocket.Chat#3622]
Your Rocket.Chat version: 0.3.4

The context menu for conversations in RocketChat+ / Desktop client is not particularly useful. Among other things, it has Cut, Copy and Paste when no selection is done after clicking into the history. Cut and Paste never makes sense here, even is something is selected. The copy does work, but when right-clicking a link, it should offer "Copy link address" as well, as it is done by browsers. Right now, the Copy button does not copy anything, when nothing is selected.

**Comment by geekgonecrazy** [comment]
I've moved this ticket to the appropriate repo: https://github.com/RocketChat/Rocket.Chat.Electron/issues/215 please subscribe there.
