### ISSUE TITLE
using OAuth (or other protocol) to sync Rocket.Chat to an Elgg based social network?

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#3626]
i have been testing this very promising chat app on my local server with intention of integrating it into my existing PHP website that is based on the elgg framework (elgg.org). i would like to replace the existing chat and add the extra video/audio features that rocketchat supports.
i need rocketchat to auto login the user if they are logged in to my website and to grab their user profile photo and other details (username), but i'm not clear on the best way to do that.
i have read similar threads in the issues list here but haven't seen any straight answers. the user guide for rocket chat just has empty sections for CAS and SAML - with nothing on custom OAuth implementations - so i don't have much to go on to proceed.
elgg has an old OAuth plugin and various APIs for various purposes, plus security tokens and other useful features - so i think the job won't be too difficult once i get an understanding of the best approach.
is there anywhere i can learn the best approach for me? a video/presentation/book/website/issue?
or is anyone willing/able to offer assistance here?
if it is appropriate i can create a plugin for elgg which will facilitate the use of rocketchat on elgg and that may result in a significant increase in new users of the software with programming skills to assist you.
thanks

**Comment by propertunist** [comment]
i have been learning via the #learn channel in the rocket.chat demo site and have successfully used the existing API to insert basic user information from my elgg site into rocket.chat. however, i am not able to locate a way to add user metadata / avatars via the API. i'm not really sure what use it is to be able to add users if i can't then complete their profiles programatically. 
i would attempt to insert the data using a direct call to mongoDB, but for the moment i am stuck with that because i am using PHP7 and the php driver for mongoDB is different from PHP5.6 and for some reason the function calls i have seen used for PHP7 do not all work for me here presently.
i am now wondering whether a better approach would be to create a custom import inside rocket.chat for elgg - however, i have no experience of meteor so prefer to avoid that if possible.

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)

Thanks!
