### ISSUE TITLE
Ability to restrict Google OAuth to a specific Domain

### ISSUE THREAD

**Issue by jhmk** [RocketChat/Rocket.Chat#3627]
The ability to restrict Google OAuth to a specific Domain would give companies the feature to use Rocket Chat without invitation.
Example: your company owns the Domain @amazingcompany.org. So everyone with that email address can automatically login and use RocketChat. Everyone else not

**Comment by nghinv-exo-tqa** [comment]
That's what I am longing for too.

**Comment by antgel** [comment]
Any updates here? This would be great.

**Comment by nghinv-exo-tqa** [comment]
Hello,
I have this problem solved:
1. goto https://yourrocketchat/admin/Accounts
2. set @youralloweddomain.com to 'Allowed Domains List'
3. set @gmail.com to 'Blocked Domains List'

that's all.

**Comment by geekgonecrazy** [comment]
Yes exactly the above: its not specific to any oauth provider and works regardless of how you choose to authenticate.

Closing as not an issue and not needed as an additional feature.

**Comment by samueloph** [comment]
I don't understand why does @nghinv-exo-tqa have to explicitly block the gmail domain. 

Why is simply allowing your domain not enough? And if this is really needed, wouldn't also allow for any other domain that has a google account (which isn't gmail.com or your domain) to login?
