### ISSUE TITLE
In sandstorm, "Receive notifications" not sticky

### ISSUE THREAD

**Issue by zeigerpuppy** [RocketChat/Rocket.Chat#3628]
In sandstorm, each time rocket.chat loads, it asks for permission to send notifications.
This does not stay set in the browser settings because the auth request comes from a different URL each time.

**Comment by geekgonecrazy** [comment]
Just by the nature of how sandstorm works... I don't know that there is going to be a solution for this. Maybe if there were at some point persistent URL's for grains(there might already be)?

I took a look through the issue tracker over there: https://github.com/sandstorm-io/sandstorm/issues I actually didn't see this answered.

 @kentonv and team might be able to answer.  But I think your question would be better asked there

**Comment by kentonv** [comment]
Yeah, this is a Sandstorm problem. We are working on a new notifications API for apps to go through which will solve this.

**Comment by engelgabriel** [comment]
hi @kentonv any update on the new notifications API for apps?

**Comment by engelgabriel** [comment]
I am closing this in favor of https://github.com/RocketChat/Rocket.Chat/issues/2407

**Comment by kentonv** [comment]
This was fixed by #3743.
