### ISSUE TITLE
nginx goes to 502 when SSL is enabled for rocketchat

### ISSUE THREAD

**Issue by propertunist** [RocketChat/Rocket.Chat#3629]
i am running the latest version of rocketchat with nginx 1.10.1, php7.0.8 on fedora 23 and am using firefox 47 to test with.
rocketchat works fine locally and on my remote server without https enabled, however, when i activate https (using a let's encrypt certificate and with rocketchat on it's own subdomain) i always see a 502 error in the browser.
the message in the nginx log is:
```
 *887 peer closed connection in SSL handshake while SSL handshaking to upstream, client: xx.xx.xx.xx, server: chat.mysite.org, request: "GET / HTTP/2.0", upstream: "https://xx.xx.xx.xx:3000/", host: "chat.mysite.org"
```
i've used various versions of nginx to attempt to resolve this and changed some keepalive values in nginx as that was a suggested solution for some similar cases, but so far i haven't found a solution for rocketchat.

**Comment by propertunist** [comment]
oh, so it appears this is a weird routing issue on my server. i have 2 subdomains, one for rocketchat and one for my test site. if i enable both sub domains in nginx then traffic for both is going to my test site. if i disable the test site then traffic to both sub domains goes to rocket chat and rocket chat loads correctly using SSL. i have no idea why this is as the server blocks and server_name directives are set correctly. i continue!

**Comment by propertunist** [comment]
this was apparently due to not having a default_server directive in the nginx configuration and some alterations were needed to the server declarations.

**Comment by BillBrower** [comment]
@propertunist I'm having a similar issue. Mind sharing the server declaration alternations you had to make?

**Comment by propertunist** [comment]
@BillBrower as i recall, the changes were mostly to the 'listen' directives in the server blocks. i have recently upgraded from nginx 1.8.x to 1.10.x and so i changed spdy to http2 on the ssl lines. there was nothing unusual in what i did, but in conjunction with the default_server value being applied to my main site, it just fixed the issue.
i think i also added SSL certificate directives to some of the server blocks i have which handle routing for alternative domain names i use for the same site.
basically, i just made extra sure that every server block was complete, which they weren't previously. before i setup the rocketchat subdomain there had only been 1 subdomain, so the issue was partially due to having more than 1 for the first time, partially due to upgrading nginx, partially due to sloppy configurations and probably also due to some not so well coded logic somewhere in the source of nginx or somewhere else!
i can't really be more helpful without seeing your code, but maybe that is of some use.
