### ISSUE TITLE
502/504 bad gateway

### ISSUE THREAD

**Issue by sharmapradeep** [RocketChat/Rocket.Chat#3630]
I had Rocket.Chat setup correctly on aws ubuntu machine using docker image, nginx and it was working fine. Then I change ssl certificate from letsencypt and reboot the machine. Then started the server again. Certificate is working now but getting following error
"502 bad gateway"

> [error] 2400#0: *36 connect() failed (110: Connection timed out) while connecting to upstream, client: client_ip, server: server_name, request: "GET /favicon.ico HTTP/1.1", upstream: "http://server_ip:3000/favicon.ico", host: "host_address", referrer: "https://domain_address"

**Comment by sharmapradeep** [comment]
It worked by changing 
proxy_pass : myserver.com:3000 
to 
proxy_pass : localhost:3000 
As 3000 port is not open for public. 
Why did it work earlier when I had the same configuration, is still a mystery.

**Comment by propertunist** [comment]
i have a similar issue, but changing the port proxy_pass value did not fix it for me: https://github.com/RocketChat/Rocket.Chat/issues/3629
