### ISSUE TITLE
Windows Server Mobile Support

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3631]
Currently windows server builds don't support the mobile app.

**Comment by neohitokiri** [comment]
oh, in that case, how can i migrate data to linux server?

**Comment by neohitokiri** [comment]
thanks

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, as the policy has now been adopted to not officially support Windows server setups. If anybody feels the urge to contribute a [community-supported guide](https://rocket.chat/docs/installation/community-supported-installation/): feel free :)

Cheers
Thomas
