### ISSUE TITLE
Could we consider the message audit functionality

### ISSUE THREAD

**Issue by chunchill** [RocketChat/Rocket.Chat#3634]
could we add a message audit functionality to enhance this app?
1. when a common user send a message, the message should only be shown to others after the admin audit it.
2. the admin will see any message the common user sent out.
3. the audit button could be just put on the UI the same as the "delete" button does.

**Comment by Sing-Li** [comment]
Similar to a room message moderator, but in a forum?  

Complete _auditing_ is covered by #2869

**Comment by chunchill** [comment]
@Sing-Li Exactly.

**Comment by louisemessage** [comment]
Closing this issue for the meantime as there hasn't been activity on it for over a year.
