### ISSUE TITLE
Fine grain control to user-visibility of each message

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#3636]
Need ability to make any message _invisible_ to various parties in a room.

Many use-cases.  Recently surfaced use-cases included:
-  slash command with output only visible to command issuer
-  direct message to oneself, used as a draft-message-holding-area, or to-do-reminder and so on
-  invisible messages used in signaling for webrtc, in band control of application extensions, and/or other IoT protocols

**Comment by tassoevan** [comment]
Closing it due to staleness.
