### ISSUE TITLE
Can't use RocketChatFileAvatarInstance in version Migrations?

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#3639]
Your Rocket.Chat version: (make sure you are running the latest)

I want to reset some user's avatar when I migrate to a new version.But I get a Error 'RocketChatFileAvatarInstance is not defined '

`
 +----------------------------------------------------------------------+
 |                                                                      |
 |                         ERROR! SERVER STOPPED                        |
 |                                                                      |
 |                    Your database migration failed:                   |
 |              RocketChatFileAvatarInstance is not defined             |
 |                                                                      |
 |  Please make sure you are running the latest version and try again.  |
 |           If the problem persists, please contact support.           |
 |                                                                      |
 |                    This Rocket.Chat version: 1.0.0                   |
 |                   Database locked at version: 37.1                   |
 |                      Database target version: 38                     |
 |                                                                      |
 |           Commit: 4c0ce6ea5e8abe97bf748f2f46d83d26b85f2e29           |
 |                 Date: Mon Jun 27 23:59:24 2016 +0800                 |
 |                        Branch: seerline-master                       |
 |                            Tag: v0.7.1862                            |
 |                                                                      |
 +----------------------------------------------------------------------+
`

How can I use RocketChatFileAvatarInstance in Migration?

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity. 
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)

Thanks!
