### ISSUE TITLE
/api/bulk/register 502 Bad Gateway - empty reply (52)?

### ISSUE THREAD

**Issue by bcamacho** [RocketChat/Rocket.Chat#3640]
Rocket.Chat version: 0.34.0

Expecting return with user id's, instead obtaining an empty response.
"(52) Empty reply from server."

At first, I tried to register using the host which resulted in 502 - bad gateway. I went down the rabbit hole thinking this was an issue with reverse proxy with nginx. Next, I tested on Docker container.

When registering new users using API the response from docker container running on port 3000 is empty: 
"(52) Empty reply from server"

curl -H "X-Auth-Token: 8PYWI-lZ6KIo-3XbRPwa7G2fEoTdIh1K8Kb4mjzbW4u"  -H "X-User-Id:  gtB3DxjzHua4grFNP" -H "Content-Type: application/jsn" -X POST -d '{"users":[{"email":"brandy@someName.com","name":"brandylee","pass":"doit123"}]}'  https://someServer.com/api/bulk/register

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

**Comment by geekgonecrazy** [comment]
Looks like your payload is correct.  Please try on latest version of Rocket.Chat.  I've tried very recently and it works great.
