### ISSUE TITLE
Feature request: new channel type "Moderated Channel"

### ISSUE THREAD

**Issue by AceSlash** [RocketChat/Rocket.Chat#3641]
The idea is to have a channel where only some users can write on it, like on some IRC channel where only voiced/oped users can talk.

This can be very useful to be able to create an announcement channel with a lot of people.

The only way to achieve this at the moment is to mute every users except the ones you want to be able to talk, which is not practical with a high number of users.

A new type of channel where only moderator can talk should do the trick.

**Comment by TheReal1604** [comment]
+1

**Comment by hExPY** [comment]
+1

**Comment by dupree972** [comment]
Has anyone worked out a solution for compliance export of messages? Slack offers such a solution and the lack of it is a major impediment to adoption in financial services or enterprise.
Thanks,
Bill

**Comment by rjones-lf** [comment]
Hyperledger would very much like this - something like +m for irc. We want to be able to have announce-only channels, as well as moderated discussions

**Comment by marceloschmidt** [comment]
We have now broadcast channels. Does that fix the problem for you? Please reopen if you think it doesn't.
