### ISSUE TITLE
How can run like service

### ISSUE THREAD

**Issue by johnfelipe** [RocketChat/Rocket.Chat#3643]
Version: 0.34.0 

How can i run like service, when reboot ubuntu server 14.04 can access to my installation

**Comment by zxweed** [comment]
See the (installation manual](https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04)
Step 4 — **Configuring Rocket.Chat as a Service**
