### ISSUE TITLE
How can put my sendgrid user for send confirmation email

### ISSUE THREAD

**Issue by johnfelipe** [RocketChat/Rocket.Chat#3644]
Version: 0.34.0

	====== BEGIN MAIL #0 ======
	(Mail not sent; to enable sending, set the MAIL_URL environment variable.)
	MIME-Version: 1.0
	To: info@felipeurrego.com
	Subject: How to verify email address on Rocket.Chat
	Content-Type: multipart/alternative;
			boundary="----mailcomposer-?=_1-1467160317498"

	------mailcomposer-?=_1-1467160317498
	Content-Type: text/plain; charset=utf-8
	Content-Transfer-Encoding: quoted-printable

	Hello,

	To verify your account email, simply click the link below.

	http://181.136.243.82:3000/#/verify-email/4yU9EVouwlY_2h2jAy1g-BcTL80W5FmAjw5HTJurIIp

	Thanks.

	------mailcomposer-?=_1-1467160317498
	Content-Type: text/html; charset=utf-8
	Content-Transfer-Encoding: quoted-printable

	Hello,

	To verify your account email, simply click the link below.

	http://181.136.243.82:3000/login/#/verify-email/4yU9EVouwlY_2h2jAy1g-BcTL80W5FmAjw5HTJurIIp

	Thanks.

	------mailcomposer-?=_1-1467160317498--
	====== END MAIL #0 ======

registration is disabled

![registrationdisabled](https://cloud.githubusercontent.com/assets/428820/16436925/cd1935ca-3d67-11e6-8c36-d7e973055a14.png)

**Comment by johnfelipe** [comment]
ok got it

/admin/Email

set my sendgrid account and credentials

admin/Accounts

In registration put my settings

But email never show

**Comment by sadeva** [comment]
Hi @johnfelipe, try using port 587.

**Comment by johnfelipe** [comment]
@sadeva but sendgrid is port 25?

**Comment by sadeva** [comment]
No, email providers like Sendgrid officially use port 25, 2525, 587, and 465.
Some cloud servers like DigitalOcean don't allow port 25 by default.

**Comment by johnfelipe** [comment]
I have my own server, then test that ports?

**Comment by sadeva** [comment]
You can test if you can send an email from your server at certain port by using `telnet`.

**Comment by wijs9218** [comment]
@johnfelipe  How did you configure the SMTP with sendgrid credentials?
