### ISSUE TITLE
Slash commands autocomplete misaligned on mobile

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#3648]
Your Rocket.Chat version: 0.35

Screenshot says it all
![screenshot_20160628-205034](https://cloud.githubusercontent.com/assets/1490165/16439997/8efefd46-3d72-11e6-9e40-d17374599f03.png)

**Comment by rasos** [comment]
And slash commands are not translated. It seems i18n is missing here.

**Comment by tassoevan** [comment]
i18n seems to be working ok right now.
