### ISSUE TITLE
RestAPI: info end point is public

### ISSUE THREAD

**Issue by Jamie-Owen** [RocketChat/Rocket.Chat#3651]
Your Rocket.Chat version: 0.35.0

Whilst I was looking at the API I noticed that the 'info' endpoint is available without authenticating, it should probably require authentication as it returns various information about the build that system administrators would rather keep private.

Easy to remedy, PR incoming.

**Comment by marceloschmidt** [comment]
If anyone wants to take a step on this, see comments on the PR: https://github.com/RocketChat/Rocket.Chat/pull/3652#issuecomment-229358245

**Comment by jaredhilton** [comment]
@marceloschmidt @graywolf336 according to their [documentation](https://github.com/kahmali/meteor-restivus#authrequired), as soon as you set authRequired to true, it responds with a 401 when unauthenticated. The change I have come up with may need some consideration and could probably be done a little better -- essentially, we default with a response of info.version number (that solves for the mobile clients), and if there is a header with a user-id, we use that to check if their role is admin. If so, show the rest of the data. I can commit what I've got so you can see.

**Comment by marceloschmidt** [comment]
Hello @jaredhilton thanks for helping out on this one. Please create a pull request with your solution! We'd love to see what you've come up with. Thanks!
