### ISSUE TITLE
Notifications not received in private group 

### ISSUE THREAD

**Issue by maheshkalal** [RocketChat/Rocket.Chat#3653]
I have Rocket chat 0.33.0 in Ubuntu server. 
In private group, users are not receiving desktop notifications for incoming new messages.  
My users are using windows based Rocket chat applications.

**Comment by xidianwlc** [comment]
I hava the same problem, when in private group @someone  there is no notification

**Comment by JobbeDeluxe** [comment]
I have noticed the same on my Ubuntu Server running 0.35. I am not receive an massage on my android phone when I was called by @name. And some other ask for notification on the browser. So it looks like they have no received either.

**Comment by Hudell** [comment]
We have recently refactored the notification system, so I'll be closing this old issue. If someone runs into this problem again, it can be reopened.
