### ISSUE TITLE
Current Jitsi Meet integration ignores device selection

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#3654]
Tested repeatably reproducible.

The current Jitsi Meet integration always uses the first mic / camera device found.  Regardless what is set on the browser or as system default on the OS.  

This obviously only happens on systems with two or more mics and/or cameras attached.  And can explain may of the "no sound" cases reported.

**Comment by Sing-Li** [comment]
If you use the Settings icon of the Jitsi toolbar at the top to select device.  It will save.  Closing this ticket.

**Comment by amaraka** [comment]
Hi Sing-Li I have installed Rcoket Chat with Nginx SSL so it loads fine with HTTPS and video messaging and audio works in Chrome but Jitsi never populates at all say cannot connect to DNS server and I select True SSL and add in the HTTPS link of my Jitis server.  On its own Jitsi works fine..  Any idea why its not populating?  Please advise..  Thank you Zion
