### ISSUE TITLE
Change role from user edit flyout

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3656]
Feature request / improvement
Admins should be able to change a user's role from the user flyout panel, instead of having to go through permissions. This would address a couple issues:
1. It's not intuitive that the permissions edit screen is where you would change a user's role. Even being pretty familiar with RC now, it took me a long time to track that down.
2. When creating a user, it's easy to accidentally select the wrong role from the drop down. So it should be easy to follow up creating a user with editing those details to correct any mistakes.

On that last point, it might be cause for another bug report, where I've seen a different role selected as default on consecutive user creation (e.g. create first user, gets assigned 'user' by default, next time I make a user, 'livechat-agent' is the default selection). That causes even more confusion when you can't easily change or even check the user's role after creation.

We will work on developing and submitting this solution, but I'm reporting it for the future PR and in case anyone else is interested.

Related to #1629, would be enhanced by #3057.

**Comment by danielfl** [comment]
To change the role for a RocketChat user, go to https://domain/admin/permissions and click in the name of the role you want to assign. A form will open with the list of users for this role and a textbox where you can insert the username.

I agree that in the flyout page it would be much better and intuitive.
