### ISSUE TITLE
Some errors in logs

### ISSUE THREAD

**Issue by mmeinert** [RocketChat/Rocket.Chat#3658]
Your Rocket.Chat version: 0.34.0

I just reports some errors found in log
`cron.coffee:6 SyncedCron ➔ info Exception "Generate and save statistics" Error: CERT_HAS_EXPIRED     at Object.Future.wait (/home/michael/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)     at Object.call (packages/meteor/helpers.js:119:1)     at Object.HTTP.post (packages/http/httpcall_common.js:61:1)     at Object.generateStatistics [as job] (server/startup/cron.coffee:13:8)     at packages/percolate_synced-cron/packages/percolate_synced-cron.js:226:1     at scheduleTimeout (packages/percolate_synced-cron/packages/percolate_synced-cron.js:274:1)     at packages/percolate_synced-cron/packages/percolate_synced-cron.js:322:1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/meteor/timers.js:6:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     - - - - -     at SecurePair.<anonymous> (tls.js:1381:32)     at SecurePair.emit (events.js:92:17)     at SecurePair.maybeInitFinished (tls.js:980:10)     at CleartextStream.read [as _read] (tls.js:472:13)     at CleartextStream.Readable.read (_stream_readable.js:341:10)     at EncryptedStream.write [as _write] (tls.js:369:25)     at doWrite (_stream_writable.js:226:10)     at writeOrBuffer (_stream_writable.js:216:5)     at EncryptedStream.Writable.write (_stream_writable.js:183:11)     at write (_stream_readable.js:602:24)     at flow (_stream_readable.js:611:7)     at Socket.pipeOnReadable (_stream_readable.js:643:5)`

`Exception while invoking method 'ufsWrite' Error: EACCES, open '/tmp/ufs/LSrXZWpAdZ4LhNbf2'     at Object.Future.wait (/home/michael/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].Meteor.methods.ufsWrite (packages/jalik_ufs/ufs-methods.js:168:1)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/home/michael/Rocket.Chat/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)     - - - - - `

`cron.coffee:6 SyncedCron ➔ info Exception "Generate and save statistics" Error: socket hang up     at Object.Future.wait (/home/michael/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)     at Object.call (packages/meteor/helpers.js:119:1)     at Object.HTTP.post (packages/http/httpcall_common.js:61:1)     at Object.generateStatistics [as job] (server/startup/cron.coffee:13:8)     at packages/percolate_synced-cron/packages/percolate_synced-cron.js:226:1     at scheduleTimeout (packages/percolate_synced-cron/packages/percolate_synced-cron.js:274:1)     at packages/percolate_synced-cron/packages/percolate_synced-cron.js:322:1     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at packages/meteor/timers.js:6:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     - - - - -     at createHangUpError (http.js:1528:15)     at CleartextStream.socketCloseListener (http.js:1578:23)     at CleartextStream.emit (events.js:117:20)     at tls.js:694:10     at process._tickDomainCallback (node.js:502:13) `

Application is working fine, just for the record...

**Comment by lucasvanhalst** [comment]
Pretty sure this is fixed by now, the rocket.chat domain SSL certificate has just been renewed yesterday

**Comment by mmeinert** [comment]
Perfect, I'll reopen if necessary
