### ISSUE TITLE
Feature request:  CRM API Integration

### ISSUE THREAD

**Issue by MaximOrlovsky** [RocketChat/Rocket.Chat#3659]
The idea is to integrate Rocket.Chat with different CRMs through 1 integration only, using unified API platform -- https://app.api2crm.com/ (There is a possibility to create a free account)). 

Supported CRMs (17) : Salesforce, MS Dynamics, Hubspot, Insightly, Pipedrive, Zoho, SugarCRM, Highrise, Capsule, PipelineDeals, SuiteCRM, Bitrix24, Solve, Vtiger, OroCRM, Zurmo and bpm’online.

Documentation -- https://app.api2crm.com/docs

**Comment by neha1deshmukh** [comment]
Is there any update on this?

**Comment by Multipass2** [comment]
I'd also appreciate an update on this 👍

**Comment by rahul7471** [comment]
@MaximOrlovsky Any update on integration of rocket live chat with sugarCRM?

**Comment by reetp** [comment]
All NFRs are now being referred to the forums for discussion.

Please open a new thread there please https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@rocket-cat close
