### ISSUE TITLE
rocketchat doesn't  dereference LDAP aliases (derefAliases)

### ISSUE THREAD

**Issue by jhilaire-cls** [RocketChat/Rocket.Chat#3660]
RocketChat version: 0.35.0
I connected rocketchat to an openLDAP directory, however  in the LDAP base where rocketchat is configured to search its users, there are only LDAP aliases. By default Rocketchat doesn't dereference aliases, so the authentication doesn't work and there is no option to allow aliases dereferencing in rocketchat.
To allowed aliases dereferencing, my patch look like this:

--- a/packages/rocketchat-ldap/server/ldap.js
+++ b/packages/rocketchat-ldap/server/ldap.js
@@ -221,7 +221,8 @@ LDAP = class LDAP { 
                const searchOptions = {
                        filter: domain_search.filter.replace(/#{username}/g, username),
-                       scope: 'sub'
+                       scope: 'sub',
+                       derefAliases: 3
                };
                logger.search.info('Searching user', username);

@@ -259,7 +260,8 @@ LDAP = class LDAP {
                const searchOptions = {
                        filter: filter,
-                       scope: 'sub'
+                       scope: 'sub',
+                       derefAliases: 3
                };
                logger.search.info('Searching by id', id);

@@ -288,7 +290,8 @@ LDAP = class LDAP {
                const searchOptions = {
                        filter: domain_search.filter.replace(/#{username}/g, username),
-                       scope: 'sub'
+                       scope: 'sub',
+                       derefAliases: 3
                }; 
                logger.search.info('Searching user', username);

**Comment by jhilaire-cls** [comment]
Deref Alias still not working in 0.36.0, the same modification as described above should be made in the file server/packages/rocketchat_ldap.js (instead of file packages/rocketchat-ldap/server/ldap.js in 0.35.0)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Can you please try to reproduce this on latest stable? You might also have a look at #890 if it's related. If the issue at hand is still there and different than the issue mentioned before, please get back to me, I'll happily reopen :)

Cheers
Thomas
