### ISSUE TITLE
Sending test email failing with Gmail SMTP

### ISSUE THREAD

**Issue by theray76** [RocketChat/Rocket.Chat#3663]
Your Rocket.Chat version: 0.34.0

After filling out the SMTP settings under email and clicking the button to send a test email, I get the following out put in the console:

Exception while invoking method 'sendSMTPTestEmail' URIError: URI malformed     at decodeURIComponent (native)     at makePool (packages/email/email.js:29:1)     at packages/email/email.js:50:1     at packages/underscore/underscore.js:750:1     at Object.Email.send (packages/email/email.js:183:1)     at [object Object].Meteor.methods.sendSMTPTestEmail (packages/rocketchat_lib/server/methods/sendSMTPTestEmail.coffee:15:9)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 

I tried saving the settings and restarting first, as suggested by others, with no improvement. I'm running this instance on a Digital Ocean Ubuntu 14.04.4 droplet and have confirmed with them that ports 587 and 465 are open. 

Has anyone else experienced this issue?

**Comment by TheReal1604** [comment]
We have discussed this 2 days / 3 days ago. Your postbox password could be to complex. Especially if you have characters like "(" in the password. Can you try it with an easier password?
