### ISSUE TITLE
Improving notifications

### ISSUE THREAD

**Issue by yangming860101** [RocketChat/Rocket.Chat#3667]
Your Rocket.Chat version:0.34

When someone sends a direct message to me,the icon becomes bright.
![image](https://cloud.githubusercontent.com/assets/5293889/16509621/6f41701e-3f71-11e6-9bc2-ea7f79afbb7b.png)

The OS that I use is windows 7.I have up to 50 people in our private group,when some one sends a message in the group,the icon does not becomes bright.
![image](https://cloud.githubusercontent.com/assets/5293889/16509602/4a52a6ba-3f71-11e6-93cc-24ed086054a3.png)
So I don't know there's  a message in the group, it would be nice to have a global setting for make the icon bright when someone send a message in a private group.Otherwise people don't know that there's a message in the group.
 It is too inconvenient.

**Comment by yangming860101** [comment]
Rocket.Chat client version:v1.3.1-win32-x64

**Comment by rasos** [comment]
The notification issue has been widely discussed already #3362 #3518 #2574 #1602.
Desired is:
1. See new messages also in channels and private groups, including total numbers (also in web interface at each line)
2. Offer an option, to receive all notifications in groups, even when online and not away

Currently, as long as you are online and not away, you do not get notifications.  Here is a patch
https://github.com/RocketChat/Rocket.Chat/issues/1602#issuecomment-226559485
but it seems that when applying it, you get even notifications of your own messages. We'v observed that iPhone users then always have a (1) indicator.

**Comment by Hooloovoo** [comment]
On Windows 10, and Rocket.Chat client 2.9.0.

By default, it appears that the 
![image](https://user-images.githubusercontent.com/556230/31126040-63d0cf28-a842-11e7-9cb0-46952fca25dc.png) icon flashes when a direct message or mention happens, but does not when somebody posts to a chat room. That matches the default options for the toaster pop-up notifications and seems like a sensible default.

What seems less sensible is that, if one changes My Account > Messages > Show Desktop Notifications For to be "All Messages", the toaster pop-ups show for all messages, but the tray icon does not flash for all messages. To my mind the icon flashing and toaster pop-ups should always be the same.

**Comment by Hooloovoo** [comment]
My ideal would be to have a little circle on the icon with the number of unread messages, like HipChat does. Even more ideal from my perspective would be to split out the number of general chat messages (which may or may not cause a flash) from personal (direct messages/mentions) in two different circles.

A crude mock-up is here:
![image](https://user-images.githubusercontent.com/556230/31126763-974872b4-a844-11e7-9bf5-50e4e561bb64.png)

**Comment by reetp** [comment]
This seems to a client issue rather than a server issue.
Current client is 2.14.x and server is on 0.70.x

If you still have issues then please open in the Electron client section https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by reetp** [comment]
@rocket-cat close
