### ISSUE TITLE
Desktop notification not work

### ISSUE THREAD

**Issue by yangming860101** [RocketChat/Rocket.Chat#3668]
Your Rocket.Chat version:0.34
Rocket.Chat client version:v1.3.1-win32-x64
My OS:windows7
The desktop notification does not work,Is there a way to solve it?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
