### ISSUE TITLE
Images are not showing in lan

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#367]
Avatar images ( Initials or uploaded ) are not showing to the other users in the lan.
To test I turn off the firewall but the images won't load either, not even when the users connect using the public ISP IP.

PS:. Images parsed from URLs load perfectly only the avatars are in blank

**Comment by sampaiodiego** [comment]
it's a known bug @oinirio .. thanks for reporting =)

**Comment by sampaiodiego** [comment]
I mean, if you set or change your avatar, other people won't see your new avatar until a browser refresh.. this is a known bug..

**Comment by oinirio** [comment]
@sampaiodiego not even if I refresh the browser, I try cleaning the cache and force restart (ctrl + shift + r) and still can't see the avatars, but I can see it perfectly in localhost

**Comment by sampaiodiego** [comment]
ok, I see.. it could be a problem with ROOT_URL.. tell me, are you running on localhost and telling the others to access your app by your IP?

can you try running with a command like this? changing _192.168.1.100_ to your real IP

`ROOT_URL="http://192.168.1.100:3000" meteor`

**Comment by oinirio** [comment]
@sampaiodiego this fix it, thanks
