### ISSUE TITLE
[Request] Create channel/group with URL

### ISSUE THREAD

**Issue by hvma** [RocketChat/Rocket.Chat#3670]
Your Rocket.Chat version 0.34

Being able to create a new channel or group by typing in the desired channel/group URL would be a very useful :

> Example: https://demo.rocket.chat/channel/mynewchannel

Also, assigning ownership via the URL would be a decent supplement:

> Example: https://demo.rocket.chat/channel/mynewchannel/user1

This would open for extremly easy co-use other webservices. In our case a learning management system (Moodle).

**Comment by paulhibbitts** [comment]
This suggestion would also be very valuable when using Livechat to discuss something with a student - taking the ad-hoc nature of Livechat and helping move to the student to a Rocket.Chat channel/room.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
