### ISSUE TITLE
Feature request: email bot

### ISSUE THREAD

**Issue by teamfighter** [RocketChat/Rocket.Chat#3671]
Dear sirs!
Could you implement some kind of email bot?
I.e. I am sending email to address bot@myrocketchat-domain.com, and this message is showing in specific channel.
Is it possible or maybe it is realized now?

**Comment by TheReal1604** [comment]
You can do this with huginn in backend I guess. https://github.com/cantino/huginn 

Huginn can translate the mail and then send a webhook with the content to some specific incoming integration. Sry, don't have a guide for this. The most things are self explanatory. I suggest you the huginn docker container, it's an easy way to deploy it.

**Comment by teamfighter** [comment]
I have already installed and integrated hubot, maybe there is exist some kind of guide for this software?

**Comment by teamfighter** [comment]
What I have done:
I have setup hubot and installed mail-notifier. This script connects to my mailbox and reads mail (I think it is, because mail is marked as read, but it doesnt display any messages in configured rooms. Its a crap ( Any help, guys?

**Comment by teamfighter** [comment]
Looks like I have finally done with hubot and now it is working absolutely perfectly! =)

**Comment by TheReal1604** [comment]
Can you please post some steps how to get it work? ;-)

Von meiner Nintendo 64 gesendet

Am 04.07.2016 um 18:03 schrieb teamfighter <notifications@github.com<mailto:notifications@github.com>>:


Looks like I have finally done with hubot and now it is working absolutely perfectly! =)

-

**Comment by teamfighter** [comment]
First of all, you have to install mail-parser2 and change hubot script as following:
`MailListener = require "mail-listener2"
moment = require "moment"

config =
  rooms: (process.env.HUBOT_MAIL_NOTIFIER_ROOMS or "").split(",")
  username: process.env.HUBOT_MAIL_NOTIFIER_USERNAME
  password: process.env.HUBOT_MAIL_NOTIFIER_PASSWORD
  host: process.env.HUBOT_MAIL_NOTIFIER_HOST
  port: process.env.HUBOT_MAIL_NOTIFIER_PORT
  tls: process.env.HUBOT_MAIL_NOTIFIER_SECURE
  mailbox: process.env.HUBOT_MAIL_NOTIFIER_MAILBOX
  markSeen: process.env.HUBOT_MAIL_NOTIFIER_MARK_SEEN
  fetchUnreadOnStart: process.env.HUBOT_MAIL_NOTIFIER_FETCH_UNREAD
  debug:  console.log.bind console
module.exports = (robot) ->
  unless config.rooms[0].length > 0
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_ROOMS environment variable."
    return

  unless config.username
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_USERNAME environment variable."
    return

  unless config.password
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_PASSWORD environment variable."
    return

  unless config.host
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_HOST environment variable."
    return

  unless config.port
    config.port = 993

  unless config.secure
    config.secure = true

  unless config.mailbox
    config.mailbox = "INBOX"

  unless config.markSeen
    config.markSeen = true

  unless config.fetchUnread
    config.fetchUnreadOnStart = true

  mailListener = new MailListener config
  mailListener.start()

  mailListener.on "server:connected", ->
    robot.logger.info "hubot-mail-notifier connected as #{config.username} to #{config.host}:#{config.port}"

  mailListener.on "error", (err) ->
    robot.logger.error "hubot-mail-notifier error", err

  mailListener.on "mail", (mail) ->
    from = []
    for sender in mail.from
      from.push "#{sender.name} <#{sender.address}>"

    date = moment mail.headers.date

    message = """
                New email from: #{from.join ","}
                Date: #{date.fromNow()} <#{date.format "LLLL"}>
                Subject: #{mail.subject}

                #{mail.text}
              """

    for room in config.rooms
      robot.messageRoom room, message`

**Comment by keithyau** [comment]
have a step will be very appreciated

**Comment by anlx-sw** [comment]
i would also like to use a email to rocket.chat channel connector (preferably with the mail attachment as file attachment). unfortunately the link of @teamfighter isn't working for me any more. does anyone know how to accomplish this (i can't find a mail-parser2 script for hubot when i google for it)

**Comment by teamfighter** [comment]
@anlx-sw i'll provide script tomorrow.

**Comment by anlx-sw** [comment]
@teamfighter could you locate your script? - many thanks

**Comment by anlx-sw** [comment]
@teamfighter any update?

**Comment by teamfighter** [comment]
Here is mail-notifier script
`
MailListener = require "mail-listener2"
moment = require "moment"

config =
  rooms: (process.env.HUBOT_MAIL_NOTIFIER_ROOMS2 or "").split(",")
  username: process.env.HUBOT_MAIL_NOTIFIER_USERNAME
  password: process.env.HUBOT_MAIL_NOTIFIER_PASSWORD
  host: process.env.HUBOT_MAIL_NOTIFIER_HOST
  port: process.env.HUBOT_MAIL_NOTIFIER_PORT
  tls: process.env.HUBOT_MAIL_NOTIFIER_SECURE
  mailbox: process.env.HUBOT_MAIL_NOTIFIER_MAILBOX2
  markSeen: process.env.HUBOT_MAIL_NOTIFIER_MARK_SEEN
  fetchUnreadOnStart: process.env.HUBOT_MAIL_NOTIFIER_FETCH_UNREAD
  debug:  console.log.bind console
module.exports = (robot) ->
  unless config.rooms[0].length > 0
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_ROOMS2 environment variable."
    return

  unless config.username
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_USERNAME environment variable."
    return

  unless config.password
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_PASSWORD environment variable."
    return

  unless config.host
    robot.logger.error "Please set the HUBOT_MAIL_NOTIFIER_HOST environment variable."
    return

  unless config.port
    config.port = 993

  unless config.secure
    config.secure = true

  unless config.mailbox
    config.mailbox = "INBOX"

  unless config.markSeen
    config.markSeen = true

  unless config.fetchUnread
    config.fetchUnreadOnStart = true

  mailListener = new MailListener config
  mailListener.start()

  mailListener.on "server:connected", ->
    robot.logger.info "hubot-mail-notifier connected as #{config.username} to #{config.host}:#{config.port}"

  mailListener.on "error", (err) ->
    robot.logger.error "hubot-mail-notifier error", err

  mailListener.on "mail", (mail) ->
    from = []
    for sender in mail.from
      from.push "#{sender.name} <#{sender.address}>"

    date = moment mail.headers.date

    message = """
                New email from: #{from.join ","}
                Date: #{date.fromNow()} <#{date.format "LLLL"}>
                Subject: #{mail.subject}

                #{mail.text}
              """

    for room in config.rooms
      robot.messageRoom room, message
`

**Comment by anlx-sw** [comment]
thanks!

**Comment by timkinnane** [comment]
I'm closing this because it looks like it might have already been resolved and bot requests are out of scope for these issues, but we collect them under one issue related to general bots features here: #10174
