### ISSUE TITLE
Using Rocket.Chat in iframe

### ISSUE THREAD

**Issue by steoo** [RocketChat/Rocket.Chat#3673]
Goal: using Rocket.Chat inside my website inside an iframe.
Issue: how to login a user simultaneously on my website and in iframed rocket.chat, without having them to log-in two times ( one in my website and one in the iframe )? 

What I want to accomplish is: a user login in in my website and in a transparent way it gets logged in inside the iframe too.

I looked at the iframe API which _seems_ to do exactly this thing, but I got lost when it says that the user should be already logged in to _authenticate_

Any clue?

**Comment by YuniSocial** [comment]
See here in different issue :  https://github.com/RocketChat/Rocket.Chat/issues/2001

**Comment by MartinSchoeler** [comment]
Yes please refer to #2001
