### ISSUE TITLE
Feature request: Set a user's avatar

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#3676]
Your Rocket.Chat version: 0.35.0

I would like the ability for admins to set the avatar of user's and new users be assigned a default avatar. This would make running a chat room for online games more manageable.

**Comment by logankoester** [comment]
Dupe of https://github.com/RocketChat/Rocket.Chat/issues/1871

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

As @logankoester said: duplicate.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate
