### ISSUE TITLE
Version 0.35: Release notes missing

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3677]
From the link on the download page there are no release notes.
https://github.com/RocketChat/Rocket.Chat/releases/tag/0.35.0/ 
We'd like to know, what is new, before we upgrade.

**Comment by TheReal1604** [comment]
https://github.com/RocketChat/Rocket.Chat/blob/develop/HISTORY.md

**Comment by xenithorb** [comment]
Looks like @engelgabriel just forgot to mark the tag as a release is all

**Comment by engelgabriel** [comment]
Thanks for the reminder :)
