### ISSUE TITLE
Feature Request: Auto-idle kicks

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#3678]
Your Rocket.Chat version: 0.35.0

I would like a setting to kick/remove a user from a room other then default rooms after 30 minutes of inactively.

**Comment by SKOx0** [comment]
I'll start this package

**Comment by wargamesqcf** [comment]
or really any way of limits users to just one room, other then default would be nice, I am trying to make a rpg site and have a single player/character in multiple rooms is less then ideal.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
