### ISSUE TITLE
Prevent invalid role assignment / selection

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3679]
0.35.0

When creating a user, role select allows you to chose any role, regardless the scope. If you can chose **Moderator** or **Owner** which are room scoped roles, they don't get a base role of **User** and can't access any functionality, even to navigate to a room.

This role select helper needs to filter the role selection to only roles with global scope.
It should also only include Admin in the list if the current user can `assign-admin-role`.

We also have made changes to resolve #3656 (with help from [Ethaan](https://github.com/Ethaan)). He pointed out that there's no protection against changing the role of the last admin. All areas where admin can be un-assigned should invoke a helper to check you're not removing the last one - includes Permissions edit view, Remove Admin buttons, user role select from User Edit fly out.

**Comment by ggazzo** [comment]
fixed long time ago, any problem let me know
