### ISSUE TITLE
How to config reverse proxy in existing conf apache2

### ISSUE THREAD

**Issue by RedPr0m0** [RocketChat/Rocket.Chat#3680]
Your Rocket.Chat version: 0.35
Version apache2: 2.4.7

Help on how to configure a reverse proxy on apache2.
Installed mods apache2: proxy_wstunnel, proxy_http, proxy_html, proxy_balancer
My config apache2:

`
<IfModule mod_ssl.c>
<VirtualHost _default_:443>
	ServerAdmin webmaster@localhost

	DocumentRoot /var/www
	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>

	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	LogLevel warn
	CustomLog ${APACHE_LOG_DIR}/ssl_access.log combined

	#SSLProxyEngine On
	ProxyPreserveHost On
	ProxyRequests Off
	#ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket
	ProxyPass /chat/ http://localhost:3000/
	ProxyPassReverse /chat/ http://localhost:3000/
	
	#<Location /chat/>
	#	ProxyPreserveHost On
	#	ProxyPass http://localhost:3000/
        #	ProxyPassReverse http://localhost:3000/
	#	#ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket

	RewriteEngine On
	RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
 	RewriteCond %{QUERY_STRING} transport=websocket    [NC]
	RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]

	#	Order allow,deny
    #       Allow from all
	#</Location>
	
     <Directory "/usr/share/phpmyadmin/">
            Order deny,allow
            Deny from all
            Allow from 127.0.0.0/255.0.0.0 192.168.0.0/255.255.255.0 10.5.0.0/24 ::1/128
     </Directory>

	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/my.domain.crt
	SSLCertificateKeyFile /etc/ssl/private/my.domain.key
	SSLCertificateChainFile /etc/ssl/certs/1_root_bundle.crt
	<FilesMatch "\.(cgi|shtml|phtml|php)$">
		SSLOptions +StdEnvVars
	</FilesMatch>
	<Directory /usr/lib/cgi-bin>
		SSLOptions +StdEnvVars
	</Directory>
	BrowserMatch "MSIE [2-6]" \
		nokeepalive ssl-unclean-shutdown \
		downgrade-1.0 force-response-1.0
	BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

    Alias /iredadmin/static "/usr/share/apache2/iredadmin/static/"
    WSGIScriptAlias /iredadmin "/usr/share/apache2/iredadmin/iredadmin.py/"
    Alias /mail "/usr/share/apache2/roundcubemail/"
    Alias /phpmyadmin "/usr/share/phpmyadmin/"
</VirtualHost>
</IfModule> 
`

**Comment by TheReal1604** [comment]
There is a guide in the Rocket.chat docs.. 
https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx
But I am not sure if its the best config, on my server i have a battery issue at the moment and @geekgonecrazy thinks it could be related to the apache2 reverse proxy..

**Comment by TheReal1604** [comment]
@RedPr0m0 Update: The config in the docs is working fine, the battery issue has other reasons.. Can you give us an update please? 

@MartinSchoeler Or we have to close this issue? :8ball:
