### ISSUE TITLE
LDAP user sync not working

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#3681]
Your Rocket.Chat version: 35

![image](https://cloud.githubusercontent.com/assets/16605816/16551864/3cbe090c-41da-11e6-956c-d89228fb7107.png)

**Comment by MartinSchoeler** [comment]
@sureshdba2003 Is this issue still happening in the latest releases ?

**Comment by pskumart** [comment]
Hi Martin,
I have the same issue with the latest version of Rocket Chat. Can you help me with the resolution?

Exception while invoking method 'ldap_sync_users' ConnectionError: 79__ldap://10.10.32.17:636 closed   at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)   at LDAP.searchAllSync (packages/meteor.js:213:24)   at LDAP.searchUsersSync (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:291:16)   at sync (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:740:26)   at [object Object].ldap_sync_users (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:1089:17)   at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1064:26)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:2108:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1042:22   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1041:43   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1040:48   at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1018:23)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:880:89      - - - - -   at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1277:17   at Array.forEach (native)   at Client._onClose (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1272:19)   at Socket.g (events.js:260:16)   at emitOne (events.js:77:13)   at Socket.emit (events.js:169:7)   at TCP._onclose (net.js:486:12)
