### ISSUE TITLE
Ad-hoc file/screenshot upload Livechat feature suggestion

### ISSUE THREAD

**Issue by paulhibbitts** [RocketChat/Rocket.Chat#3686]
It would be really helpful for educational contexts to be able to have site visitors upload files when using Livechat.

Thanks for considering this request.
Paul

**Comment by kicdo** [comment]
Right now our plan is to integrate Rocket Chat to our software. One of the main requirements from RFP's is the ability to share files with agents in livechats. This would be an important feature that we definitely need.
