### ISSUE TITLE
Rocket.chat can't run: rocketchat_1 | Error: failed to connect to [mongo:27017]

### ISSUE THREAD

**Issue by tphanix** [RocketChat/Rocket.Chat#3688]
Rocket.chat can't run, please help me. I don't know why.

**Your Rocket.Chat version: (make sure you are running the latest):**
Digest: sha256:1760ec08833dbae5a37183518c83c042485b07ad5848a2aff80c6885ac2eed9a
Status: Image is up to date for rocketchat/rocket.chat:latest

OS: CentOS 6.6
Docker version 1.7.1, build 786b29d
docker-compose version 1.5.2, build 7240ff3

**[root@s06 Rocket.Chat]# docker-compose logs**
rocketchat_1 | 
rocketchat_1 | /app/bundle/programs/server/node_modules/fibers/future.js:278
rocketchat_1 | 						throw(ex);
rocketchat_1 | 						      ^
**rocketchat_1 | Error: failed to connect to [mongo:27017]**
rocketchat_1 |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat_1 |     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
rocketchat_1 |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
rocketchat_1 |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
rocketchat_1 |     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
rocketchat_1 |     at new Mongo.Collection (packages/mongo/collection.js:102:1)
rocketchat_1 |     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
rocketchat_1 |     at new AccountsServer (accounts_server.js:16:5)
rocketchat_1 |     at Package (globals_server.js:5:12)
rocketchat_1 |     at /app/bundle/programs/server/packages/accounts-base.js:1814:4
rocketchat_1 |     - - - - -
rocketchat_1 |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
rocketchat_1 |     at [object Object].emit (events.js:106:17)
rocketchat_1 |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
rocketchat_1 |     at [object Object].emit (events.js:98:17)
rocketchat_1 |     at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
rocketchat_1 |     at Socket.emit (events.js:95:17)
rocketchat_1 |     at net.js:441:14
rocketchat_1 |     at process._tickCallback (node.js:458:13)

**[root@s06 Rocket.Chat]# vim docker-compose.yml**
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
#    volumes:
#       - ./uploads:/app/uploads
  environment:
    - PORT=4000
    - ROOT_URL=http://x.x.x.x:4000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 4000:4000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
     - ROCKETCHAT_URL=rocketchat:4000
     - ROCKETCHAT_ROOM=GENERAL
     - ROCKETCHAT_USER=bot
     - ROCKETCHAT_PASSWORD=botpassword
     - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
     - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
     - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080

**[root@s06 Rocket.Chat]# docker-compose ps**
      Name               Command              State               Ports       
-----------------------------------------------------------------------------
rocketchat_hubot_   /bin/sh -c node     Up                  0.0.0.0:3001->808 
1                   -e "consol ...                          0/tcp             
rocketchat_mongo_   /entrypoint.sh      Up                  27017/tcp         
1                   mongod --sm ...                                           
rocketchat_rocket   node main.js        Up                  3000/tcp, 0.0.0.0 
chat_1                                                      :4000->4000/tcp   

**[root@s06 Rocket.Chat]# iptables -L -n -t nat | grep DOCKER**
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           ADDRTYPE match dst-type LOCAL 
DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8         ADDRTYPE match dst-type LOCAL 
Chain DOCKER (2 references)

**Comment by k0nsl** [comment]
This is how I typically "solve" a similar issue:

```
service docker stop
service docker start
docker pull rocketchat/rocket.chat:latest
docker-compose stop chat
docker-compose rm chat
docker-compose up -d chat
```
Keep in ming: you would need to adjust the above to conform to your docker-compose layout. This typically fixes it for me.

**Comment by tphanix** [comment]
@k0nsl  thank so much. However it could not be solved my issues.

**Comment by geekgonecrazy** [comment]
yes typically if it fails to connect to mongo its a race condition.  Where mongo isn't started when Rocket.Chat is looking for it.  To solve it normally you could just do docker-compose up db and then docker-compose up rocketchat
