### ISSUE TITLE
Scalable File Sharing

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#369]
Upload -> Object Storage -> CDN -> tons of downloaders

- [x] Local Filesystem
- [x] S3 Storage
- [ ] OpenStack Swift Storage
- [x] CDN Configuration

**Comment by engelgabriel** [comment]
made possible by https://github.com/RocketChat/Rocket.Chat/issues/24

**Comment by Sing-Li** [comment]
Need to make sure we also support other S3 compatible object storage (OpenStack Swift -  such as HP, SoftLayer, and delimiter)

**Comment by MuhClaren** [comment]
+1 for Swift

**Comment by engelgabriel** [comment]
@tdhz77 are you working on the S3 support?

**Comment by engelgabriel** [comment]
Will fix #1622 and #2131

**Comment by engelgabriel** [comment]
I'll close this issues and we can open new ones for specific storage support

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/4296

**Comment by hbakhtiyor** [comment]
@engelgabriel would be nice to look at the project https://minio.io/

**Comment by geekgonecrazy** [comment]
@hbakhtiyor have you tried using it with Rocket.Chat?  I've seen this project and am a big fan.

**Comment by hbakhtiyor** [comment]
@geekgonecrazy not yet

**Comment by DaBlitzStein** [comment]
google drive?
