### ISSUE TITLE
Tab autocomplete adds mention to beginning of line, not at cursor position

### ISSUE THREAD

**Issue by peterdalydickson** [RocketChat/Rocket.Chat#3691]
Your Rocket.Chat version: 0.35.0

This issue is difficult to describe so I recorded a 49sec jing video - http://screencast.com/t/UtzZZve7d4zs

Basically, when I press tab to autocomplete, I always expect the competition to occur where my cursor is.

But if the letter combination I'm attempting to autocomplete occurs previously in the message, that gets autocompleted instead.

**Comment by gwillen** [comment]
I wonder if this is not getting attention because it's not obvious without watching the video what it is? But I just independently hit it, it's really super broken.

Example:

"Hogwarts is cool, gw<TAB>" -> "Ho@gwillen arts is cool, gw"

**Comment by geekgonecrazy** [comment]
I've renamed this one to hopefully more accurately explain what it is you're wanting

**Comment by geekgonecrazy** [comment]
This one should now be complete.  I've not experienced any issues with it.  Closing

**Comment by gwillen** [comment]
Thanks! Is there a PR / commit somewhere with the fix? Or is this more a case of "that code got rewritten since this bug was filed"?

**Comment by geekgonecrazy** [comment]
@gwillen to be honest so much has changed since then.  I have no idea :grin: I just can't reproduce any more
