### ISSUE TITLE
Extend user info

### ISSUE THREAD

**Issue by Shikaka** [RocketChat/Rocket.Chat#3692]
Your Rocket.Chat version: 0.35.0

Improvement.

It will be great, if users can fill additional information in theirs profiles (if they want)
or possibility to specify field's and syncronize them with LDAP ...

For example Work tel, Location, department... etc...

**Comment by vetash** [comment]
Or custom fields.

**Comment by engelgabriel** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2046
