### ISSUE TITLE
Default rocket chat database

### ISSUE THREAD

**Issue by Aveline67** [RocketChat/Rocket.Chat#3693]
Your Rocket.Chat version: latest

I run a docker setup using a mondb image and a rocketchat image

```
docker run --name db  -v /home/chat:/data/db -d mongo:3.0 --smallfiles
docker run --name rocketchat --link db --env ROOT_URL=http://chat._example_.com -p 3000:3000 -d rocket.chat
```

Rocket chat creates a database, but how could I log to the database to retrieve rocketchat's data ?

Which username/password do use rocket chat with mongodb ?

**Comment by IQ2022** [comment]
it would be nice to be able to download DB from the interface as root admin..

**Comment by Aveline67** [comment]
Actually it creates a database accessible to every ones if I open the port like this:

`docker run --name db  -v /home/chat:/data/db -p 0.0.0.0:27017:27017 -d mongo:3.0 --smallfiles`

which means I can indeed access the database as it is not secured by default.
the two previous docker commands are secure because only the rocket chat container can access the mongodb container (--link parameter)

**Comment by lucasvanhalst** [comment]
well you can dump all data to a file using this command if that's what you want
```bash
docker exec mongo mongodump --archive=archive.json
```

**Comment by MartinSchoeler** [comment]
Feel free to open again or create a new issue if you find any bugs with Rocket.Chat 

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
