### ISSUE TITLE
Options for close livechat button location 

### ISSUE THREAD

**Issue by AlecTroemel** [RocketChat/Rocket.Chat#3694]
The button to close a livechat conversation is pretty well hidden. Right now it is in the tabbar info page and people seem to be have a difficulty finding it. it would be nice to have some options to where or how it is shown. 
- could move the buttons to directly on the header of the room 
- could open the tabbar info page automatically when you go to a room to show where it is

**Comment by sampaiodiego** [comment]
@AlecTroemel I was thinking on start with the info tabbar opened for livechat rooms. as it contains another useful infos (like navigation history and guest data)

**Comment by bizzbyster** [comment]
I'm unable to find the close button. Can you explain where it is? Tabbar info page?

**Comment by bizzbyster** [comment]
found it

**Comment by Sing-Li** [comment]
implement as per @sampaiodiego 's idea
