### ISSUE TITLE
invalid slash commands shouldn't be considered messages

### ISSUE THREAD

**Issue by jeffreywescott** [RocketChat/Rocket.Chat#3697]
Your Rocket.Chat version: develop

Right now, if a user makes a typo while trying to issue a slash command, if the command typed doesn't match an actual command (e.g., `/inviet @username`), it will display that message in the channel to all users. This could range anywhere from mildly embarrassing to seriously unfortunate (for example, if there's private information being sent to the slash command, which is entirely possible in the world of custom slash commands).

PR forthcoming.

**Comment by JorisVanEijden** [comment]
Problem is that many people used this "bug" to add integrations/webhooks to add additional commands.
See #3906
