### ISSUE TITLE
Uncaught NotSupportedError: Failed to construct 'AudioContext'

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#3699]
Your Rocket.Chat version: (make sure you are running the latest)

When I send some audio record message in demo.rocket.chat, I got this error and I can send any more audio record message.
`
audioRecorder.coffee:7 Uncaught NotSupportedError: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
`
[ AudioContext.close() ](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/close)
will fix this error

```
  stop: (cb) ->
    @recorder.stop()

    if cb?
      @getBlob cb

    @stream.getAudioTracks()[0].stop()

    @recorder.clear()

    @audio_context.close()  # close audiocontext 
    delete @audio_context
    delete @recorder
    delete @stream
```

**Comment by danielwegener** [comment]
Would be great to know which browser (which version) you are using on which OS.

**Comment by Micjoyce** [comment]
browser:
Google Chrome	51.0.2704.103  （64）
version	aa7c8d23c098e96a388ffedf6698230bda650bb3-refs/branch-heads/2704@{#723}
OS Mac OS X 
Blink	537.36 (@aa7c8d23c098e96a388ffedf6698230bda650bb3)
JavaScript	V8 5.1.281.65

android version: 5.1

**Comment by MartinSchoeler** [comment]
@Micjoyce Is this bug happening in the newer releases?

**Comment by Micjoyce** [comment]
This issure can be close. I make a test  in demo.rocket.chat and not found againt.

**Comment by MartinSchoeler** [comment]
OK Thanks for the reply @Micjoyce !
