### ISSUE TITLE
File Sharing peer2peer

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#370]
intent to share -> file sharing 'signaling' -> tons of sharing sessions going browser-to-browser
(almost too perfect for the data-channels portion of web-rtc; or BitTorrent integration)
##

**Comment by engelgabriel** [comment]
made possible by https://github.com/RocketChat/Rocket.Chat/issues/24

**Comment by hbakhtiyor** [comment]
@engelgabriel worth to look at the project https://webtorrent.io/

**Comment by louisemessage** [comment]
Completed in https://github.com/RocketChat/Rocket.Chat/issues/24. Closing issue
