### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#3700]
Your Rocket.Chat version:0.35.0
Person has an account, has an email on that account and gets this when they try to set their password.

Exception while invoking method 'sendForgotPasswordEmail' Error: No such email for user.     at AccountsServer.Accounts.sendResetPasswordEmail (password_server.js:529:11)     at [object Object].Meteor.methods.sendForgotPasswordEmail (server/methods/sendForgotPasswordEmail.coffee:6:13)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)

**Comment by MartinSchoeler** [comment]
@wargamesqcf have you had this issue in the newest release?

**Comment by wargamesqcf** [comment]
I got around this with wordpress oauth and let wordpress handle  all my account stuff.
