### ISSUE TITLE
Push Notifications for RocketChat webview in android

### ISSUE THREAD

**Issue by VibhaPS** [RocketChat/Rocket.Chat#3702]
Rocket.Chat version: (0.31.0)
My android app loads Rocket.Chat into a webview. I would like to receive Push Notifications in my app.

I make the necessary settings(GCM API key and Sender id) in the Rocket.Chat server. I can get push notifications in the cordova app built using the same GCM API key and Sender id.

However I would like to receive push notifications in my android app where Rocket.Chat is loaded into a webview. I register with GCM and receive a registration token. I understand that I need to send this token to the RocketChat server in order to receive push notifications from GCM. 

I do not see any API's to set the GCM registration token? How can I accomplish this? Please advise. Thanks in advance.

**Comment by pandix** [comment]
I tried the same with an ios webapp without success,
I'm intrested too if someone as an idea ...

**Comment by geekgonecrazy** [comment]
Going to close this to clean up open issues.  But would love to hear if you had success with this.
