### ISSUE TITLE
URL to Youtube or Facebook link does not show embedded video

### ISSUE THREAD

**Issue by feraudet** [RocketChat/Rocket.Chat#3706]
Your Rocket.Chat version: 0.35.0

Hi,

I'm not sure if it's a bug or a non-existent feature, but links to Youtube or FaceBook video does not show embedded video.

Regards,

Cyril

**Comment by MartinSchoeler** [comment]
Hey @feraudet i have checked and youtube videos show the embedded video, try it in the newest version
