### ISSUE TITLE
REST API extension

### ISSUE THREAD

**Issue by lcpaf** [RocketChat/Rocket.Chat#3707]
Is somehow possible to add the following to the REST API?
All `users` in my favorites bar, with their respective `status` and `unread messages` as a counter.
This would be really handy!

**Comment by sachinrkeche** [comment]
I am also looking for the for the unread messages count any idea?

**Comment by geekgonecrazy** [comment]
You can already fetch users and your dm unread status via our rest api.  Closing.  Please see our documentation: https://rocket.chat/docs
