### ISSUE TITLE
Clicking a deleted user shows invalid information panel

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3708]
If you delete a user and then click on a mention of theirs it opens the user info panel looking like this:

![image](https://cloud.githubusercontent.com/assets/51996/16632655/c6c3885a-438a-11e6-9841-44a4219cad81.png)

We need to show something meaningful here.  Like user no longer exists

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

It's not very likely that this is still an issue. If so, just reopen :)

Cheers
Thomas
