### ISSUE TITLE
Possible memory leak in Rocket.Chat (and/or KaTeX-implementation?)

### ISSUE THREAD

**Issue by tfla** [RocketChat/Rocket.Chat#3709]
My Rocket.Chat version: 1.3.1 (Linux)

So I was playing around with the KaTeX-implementation to see what could be done, and obviously I ended up doing pixel-art, but before too long my OS started crashing when copy/pasing snippets of code. 
Pasting this piece of code in a channel uses more than 6GB of RAM on my system, if y'all can replicate something is probably wrong... :)
`$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#ffcc33}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#ffffff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffcc33}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffcc33}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#ffcc33}{\rule{1em}{1em}}\color{#ffcc33}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$
$\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}\color{#3399ff}{\rule{1em}{1em}}$`

**Comment by geekgonecrazy** [comment]
@tfla does this crash just your client or does this mess up the server as well?

**Comment by Fscape** [comment]
If my issue is the same, it's the client - when pasting any large amount of text.
Clients' OSs: Xubuntu 16.04 & .10, latest updates, 6GB RAM, i5. 
As soon as a large paragraph of text (like Lorum Ipsum) is pasted, htop shows a cpu spike to 100%, and the RAM usage rises until full... causing the OS to freeze, requiring a hard reset.
(I don't get a chance to actually send the text message)
Logs show nothing out of the ordinary.
Server: Snap 0.48.2

**Comment by geekgonecrazy** [comment]
It sounds like this is client side only then if the server isn't locking up and crashing as well.

Is this in our desktop app or also via the browser?

**Comment by Fscape** [comment]
I edited my comment too late :)
Works fine in a browser.
(Also fine on the Windows10 app)

**Comment by geekgonecrazy** [comment]
@rocketchat/core I'm guessing the spell check engine that is behind the black screen is also behind this.  Thoughts?

**Comment by Fscape** [comment]
This is no longer causing the OS to freeze for me in the new client version 2.2.0 (Thanks!)
A block of 1300 characters of plain text now takes +-10 seconds to appear when pasting into chat, but it gets there.
During this time, the CPU jumps to 100%, and the RAM hardly even changes.
(Once the pasted text appears, the spellcheck works well too)

**Comment by geekgonecrazy** [comment]
Glad to see there has been improvements. With Katex there really is no getting around there being a spike in processing.  But ideally this could be improved even more.

**Comment by geekgonecrazy** [comment]
Please give this a try on the newest version of Rocket.Chat.  Going to go ahead and close.  Please feel free to re-open if still experiencing this issue.
