### ISSUE TITLE
Please add to lingohub one string

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#3712]
Your Rocket.Chat version: 0.35
![0000000016](https://cloud.githubusercontent.com/assets/8321589/16651385/95a1d94e-447e-11e6-957c-dac722a713f6.png)
This message not able to translate from very first versions, please add this to lingohub.

**Comment by MartinSchoeler** [comment]
@vetash Was it added in the latest version?

**Comment by vetash** [comment]
I cant find it in lingohub:
![screenshot_20160820_053523](https://cloud.githubusercontent.com/assets/8321589/17825019/4a08f848-66a0-11e6-887a-37f6ed7da595.png)

**Comment by vetash** [comment]
One year after i hope you can find the time for this :)
