### ISSUE TITLE
RTL Issue

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#3714]
Your Rocket.Chat version: demo.rocket.chat
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11560275/16669898/a9ef46fa-448f-11e6-9848-d303543619d1.gif)

**Comment by bazarnew** [comment]
Hi I have this problem for Persian

**Comment by djeber** [comment]
the issue is present on all rtl languages

**Comment by bazarnew** [comment]
@diegoprates

**Comment by bazarnew** [comment]
@sampaiodiego

**Comment by djeber** [comment]
@engelgabriel

**Comment by djeber** [comment]
@fduraibi

**Comment by engelgabriel** [comment]
We will take a look.

**Comment by fduraibi** [comment]
@djeber I personally don't have time these day to look into it, so I hope someone else will fix it.

**Comment by Saleh7** [comment]
**it seems the problem was in #line19 and #line24**

-------------
https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-ui-flextab/flex-tab/flexTabBar.coffee

```coffee

		if RocketChat.TabBar.isFlexOpen() and RocketChat.TabBar.getTemplate() is @template
			RocketChat.TabBar.closeFlex()
			$('.flex-tab').css('max-width', '')
			$('.main-content').css('right', '40px')
		else
			if not @openClick? or @openClick(e,t)
				if @width?
					$('.flex-tab').css('max-width', "#{@width}px")
					$('.main-content').css('right', "#{@width + 40}px")
				else
					$('.flex-tab').css('max-width', '')

				RocketChat.TabBar.setTemplate @template, ->
					$('.flex-tab')?.find("input[type='text']:first")?.focus()
					$('.flex-tab .content')?.scrollTop(0)

```

**Comment by fduraibi** [comment]
You are right @Saleh7 the "right: 40px;" is set inline and take precedent over the correct css and it is LTR only.

**Comment by Saleh7** [comment]
@fduraibi :+1: 

-----

![Rocket](https://media.giphy.com/media/l41YviGmUlQgUEW9G/giphy.gif)

**Comment by fduraibi** [comment]
I think this problem is solved now. It doesn't happen to me anymore after the update
