### ISSUE TITLE
how to disable the red dot in mac osx dock rocketchat icon (screen attached)

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#3717]
Rocketchat 0.35.

Hello Devs.

How do i disable the strange red dot in MacOSX Dock? It seems it shows when a new message is posted without being mentioned in a room i am a member of at this time. 
![bildschirmfoto 2016-07-08 um 10 15 01](https://cloud.githubusercontent.com/assets/631865/16681506/6d6fdbb6-44f5-11e6-86fb-c91efc8241d1.png)

Thanks and cheers
t.

**Comment by vetash** [comment]
Try to mak all messages as read. Red dot shows you that you have to PM message or mention in one of rooms.

**Comment by MartinSchoeler** [comment]
@himbeere is the problem solved?

**Comment by himbeere** [comment]
Yes. It's solved. Thanks.
