### ISSUE TITLE
SMTP settings

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#372]
Build a MAIL_URL environment variable based on:

SMTP_Host
SMTP_Port
SMTP_Username
SMTP_Password

**Comment by graywolf336** [comment]
A few more settings I would like to see:
* From Email Name (use the site name from the settings?)
* From Email

Unless it currently does this when you change the smtp settings in the UI..

**Comment by graywolf336** [comment]
The above suggestion by me was pulled in via pull request #693, so it can be ignored now. :)
