### ISSUE TITLE
hubot integration: long text never arrives

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#3722]
the hubot-help module has this code:

emit = cmds.join "\n"
msg.send emit

However, if you've got a large(r) number of scripts and modules and such installed, you will get ZERO output unless you replace it with:

for i in cmds
   msg.send i

I have not tried to find out what the size limit is for a message, but theres a point where the text will just be silently thrown away

**Comment by vetash** [comment]
I think this should be posted in hubot issues. Not rocket chat core.
https://github.com/RocketChat/hubot-rocketchat/issues
