### ISSUE TITLE
Distinguish external links.

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#3723]
I wanted to submit this idea in case it slipped my mind: it would be terrific if we could have an option (i.e enable/disable) to distinguish between internal and external links.
If somebody posts an external link we could make use of something like FontAwesome and `fa-external-link`.

I was going to try and put this idea into practice later today, if I got time, by simple jQuery solution. Although I am sure there must be some better way to do it. Maybe somebody else has also been thinking about this sort of thing, or am I the only one that would like to see this? :D

Have a great Friday, all.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
