### ISSUE TITLE
When S3 File Upload enabled, sharing from Android gallery produces wrong file contents and metadata

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#3724]
Your Rocket.Chat version: 0.35.0
##### Description:

When S3 File Upload enabled, sharing from gallery produces wrong file contents and metadata

This bug only applies to having S3 File Upload enabled and working. 
##### Steps to reproduce:
- Enable S3 File upload and confirm working from computer
- Use an android phone (ios untested in this scenario) and navigate to your gallery app.
- Use the "Share to" icon, to share to rocket.chat. 
- Note that this process works ok, to include the proper image thumbnail, it asks you to select a room/channel - do that. 
- The file is uploaded, but what appears is an empty box in place of where the image should be.
  - This step works fine with GridFS instead, hence the bug and why it only applies to S3's code path.
##### Items worth mentioning:
- Opening the app first, and selecting the paperclip icon and going through that dialog works correctly with S3 and GridFS
- Turning on GridFS and reproducing the steps above works as intended, only when S3 is enabled does it not work correctly. 
##### What is actually happening:

I took the time to go through and find the S3 objects so I could see what was happening. I suspected bad metadata was at play and I was partially right:
1. `Content-Disposition` metadata differs from that of a normal working file (normal file is first):
   
   ```
   Content-Disposition inline; filename="JPEG_20160708_144552_2119815730.jpg"; filename*=utf-8''JPEG_20160708_144552_2119815730.jpg
   
   Content-Disposition inline; filename="content"; filename*=utf-8''content
   ```
2. Contents differ from that of a normal file. While a normal file has binary data in an image format, the broken file is 15 bytes in length, and has a contents of:
   
   ```
   [object Object]
   ```
- I am unaware if this is Rocket.Chat.Server related or Rocket.Chat.Cordova related, but I suspect this is server related since it works just fine when using GridFS (not using S3 or other methods)

**Comment by MartinSchoeler** [comment]
@xenithorb Is this issue still happening in the newest version?

**Comment by xenithorb** [comment]
Unfortunately it seems that with 0.37.0 sharing from the gallery doesn't even bring up the file sharing modal anymore; sharing to rocket.chat brings up the app but does nothing.

**Comment by xenithorb** [comment]
You can still share through the "paper clip" icon, by selecting that, then documents, and then selecting an image. But as far as using the platform-wide sharing API - that doesn't seem to work at all now, whereas before it would bring up the modal with the correct thumbnail, but not send the right file contents. (as per documented in my original comment here)

**Comment by MartinSchoeler** [comment]
@xenithorb Yes bug confirmed, we will try to take a look at it, Thanks for replying to an old post!

**Comment by xenithorb** [comment]
This is still broken

I could understand if it were closed in favor of Rocket.Chat.Android not even having a share-to ability though. 

It's hard with so many bugs to determine whether or not this will ever get looked at again, but it's still definitely broken

**Comment by Hudell** [comment]
While the Rocket.Chat.Android app doesn't have the share-to ability, this issue was already solved on the new API that handles upload, so when the feature gets added it will be working properly.
