### ISSUE TITLE
Will it support other characters in channel name?

### ISSUE THREAD

**Issue by okworld26** [RocketChat/Rocket.Chat#3726]
Your Rocket.Chat version: (make sure you are running the latest)

Currently, only numbers or letters are support in channel name, will it support characters of other Languages? such as Chinese characters in channel name? any plan?

**Comment by vetash** [comment]
May be this helps you: https://github.com/RocketChat/Rocket.Chat/issues/640

**Comment by okworld26** [comment]
Thank you.
