### ISSUE TITLE
HTML links not clickable

### ISSUE THREAD

**Issue by purldator** [RocketChat/Rocket.Chat#3731]
Your Rocket.Chat version: **0.35.0 develop; [last commit](https://github.com/RocketChat/Rocket.Chat/commit/53b95eccc9a65c5362410f3478a6a1147e30a936)**

I started noticing this around four, five days ago.  All hyperlinked links posted to any channel type are not clickable in Chrome latest, despite appearing with all styling conventions clearly expressing the fact it _should_ be clickable.  You must right-click, select "open in new tab/window" to use them.

**Comment by Jmbrace** [comment]
Yeah you are right, did you have a chance to look into the code base and find any relevant packages/files where the problem may stem from?

**Comment by purldator** [comment]
@Jmbrace; Aye.  @nishimaki10 made [a swift fix](https://github.com/RocketChat/Rocket.Chat/issues/3732) and it only needs a final check/pass.
