### ISSUE TITLE
one time registration URIs

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#3733]
Your Rocket.Chat version: 0.35

Hello Devs.

Are there plans to integrate "one time" registration URIs? There is the secret URL at the moment but if that URI leaks to the internet everyone can register.

thanks and cheers
t.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
