### ISSUE TITLE
Emoji One upgrade to v2.2.5

### ISSUE THREAD

**Issue by xasx** [RocketChat/Rocket.Chat#3735]
Emoji One has received an update.
https://github.com/Ranks/emojione/releases

Features new 'Unicode 9' set which might be useful to colorify what one has to say.

Please add support for the new ones.

Your Rocket.Chat version: 0.35.0

**Comment by graywolf336** [comment]
@RocketChat/core this adds `:facepalm:` 😜

**Comment by sampaiodiego** [comment]
Unfortunately just updating `emojione` isn't enough..
so I'll reopen the issue.

**Comment by graywolf336** [comment]
@sampaiodiego What all needs to be done in addition to updating the `emojione` package?

**Comment by sampaiodiego** [comment]
a lot! :joy: 
we're using a [CSS with percent position for PNG sprite](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emojione/sprites.css) which is [not supported](https://github.com/Ranks/emojione/issues/208#issuecomment-196695116) by `emojione`. so we need to generate a new CSS for the new emojis or start using their CSS (which [as far I remember they [can't be resized](https://github.com/Ranks/emojione/issues/220) - like for big emojis)

also we need to update the [tones list](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emojione/emojiPicker.js#L231) and [category map](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emojione/emojiPicker.js#L299) 

and there could be more things to do =P

**Comment by graywolf336** [comment]
@sampaiodiego Ah gotcha! Do you have to do this all manually, or have you managed to create a script which does this?

**Comment by sampaiodiego** [comment]
[there is a script to generate the map vars](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emojione/generateEmojiIndex.js) .. but I have to realize what to do with the CSS

**Comment by xasx** [comment]
:yellow_heart: Thanks for following-up on this. Already expected that it isn't just about updating dependencies...
Hope the new emojis are worth the noise I produced...
