### ISSUE TITLE
Timesync fails with livechat when running under a sub directory. 

### ISSUE THREAD

**Issue by Jmbrace** [RocketChat/Rocket.Chat#3742]
As of version  0.35.

Timesync did not work in a subDir till this commit.

https://github.com/RocketChat/Rocket.Chat/commit/96f392c475cf013d8a6ff2cdbd0cafb0fce07ae7#diff-5dfcce34552e28f9a581c3637610ed9cR51

The solution was to check for a ROOT_URL_PATH_PREFIX and append it to the syncUrl.

However the livechat app still references to this (the current version of Timesync).

https://github.com/mizzao/meteor-timesync/blob/master/timesync-client.js#L46

So timesync does not work for livechat when rocket chat is run in a subdir.

The cheap workaround is to create a packages folder inside the app folder of the livechat package directory and copy the meteor-timesync package into it, we should find a better way to fix this however.

**Comment by MartinSchoeler** [comment]
@Jmbrace Is this issue still happening in the newest version?
