### ISSUE TITLE
unable to load scripts for hubot

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#3745]
Your Rocket.Chat version: 0.35.0
I put scripts into the scripts folder of home/danny/scripts but I don't know what I am missing.

	docker run -it -e ROCKETCHAT_URL=162.208.48.77:3000 \
    -e ROCKETCHAT_ROOM='GENERAL' \
    -e ROCKETCHAT_ROOM='diceroom' \
    -e LISTEN_ON_ALL_PUBLIC=true \
    -e ROCKETCHAT_USER=testbot \
    -e ROCKETCHAT_PASSWORD=password \
    -e ROCKETCHAT_AUTH=password \
    -e BOT_NAME=testbot \
    -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help,basic \
    -v $PWD/scripts:/home/hubot/scripts \
    rocketchat/hubot-rocketchat:v0.1.4

`# hubot greeting.
#
# (hi|hello) - say hi to your butler

module.exports = (robot) ->
  robot.respond /hi|hello/i, (msg) ->
    msg.send "Howdy!"`

**Comment by geekgonecrazy** [comment]
@wargamesqcf please visit us in [#hubot](https://demo.rocket.chat/channel/hubot) or on the hubot adapter repo https://github.com/rocketchat/hubot-rocketchat
