### ISSUE TITLE
status *message* when away

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#3747]
Rocketchat 0.35

hello devs.

Is it possible to leave a status *message* when setting the status to away or the like? hipchat has this possibility. see attache screen.

thanks and cheers
![screen shot 2016-07-12 at 09 09 29](https://cloud.githubusercontent.com/assets/631865/16758843/5d7459d6-4814-11e6-9470-1dba856c139b.png)

**Comment by MartinSchoeler** [comment]
It is not possible, if you think that would be a good feature, post a request for one and we will take a look at it
