### ISSUE TITLE
Feature Request - "Live Feed" of all subscribed channels

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#3748]
It would be amazing if rocket chat could introduce a live feed channel that displays everything you subscribed to.
The screenshot gives an idea how something like this could be reliazed,  here I subscribed to the channels #dev #general and #contributers 
![capture](https://cloud.githubusercontent.com/assets/17119942/16761424/6aa9d1f6-4820-11e6-8c79-1109c1b3082e.JPG)

Let me know what you think.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
