### ISSUE TITLE
View Updation

### ISSUE THREAD

**Issue by varunsree** [RocketChat/Rocket.Chat#3749]
How can I update rocket chat html (view), search through the project files, couldn't find any html's inside the code base .Is there any option for edit the HTML  part

**Comment by MartinSchoeler** [comment]
Hey there is a lot of html here for example
https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-ui/views/app
you can find a lot more in the project

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
