### ISSUE TITLE
Cannot register with umlaut

### ISSUE THREAD

**Issue by KonradHoeffner** [RocketChat/Rocket.Chat#3752]
When I try to register for a rocket chat, I get a 403 error.
I suppose that is because my name contains "ö" (the o umlaut).

**Comment by MartinSchoeler** [comment]
@KonradHoeffner Is it your name or your username, if its the name i think that has been fixed and if its the username this type of character is not allowed in the username.

**Comment by geekgonecrazy** [comment]
Closing let us know if you still have issues.
