### ISSUE TITLE
Improve E-Mails sent to survive spam filter

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3753]
E-Mails sent from RC are missing some header information. At our set-up, Google currently puts the first E-mail from RC into your spam folder. A user registration confirmation test at https://www.mail-tester.com results in a score of 5.7/10.

-0.001      HTML_MESSAGE        HTML included in message
-0.635      HTML_MIME_NO_HTML_TAG       HTML-only message, but there is no HTML tag
-1.105      MIME_HTML_ONLY      Message only has text/html MIME parts
-0.001      MIME_QP_LONG_LINE       Quoted-printable line longer than 76 chars
-1.396      MISSING_DATE        Missing Date: header
-0.14       MISSING_MID     Missing Message-Id: header

I am not sure if the HTML tag should be included in the E-Mail header template:  https://myserver.tld/admin/Email

There should be definitely be sent a text/plain version along with the HTML message, as this is an important fallback if E-Mail readers do not render it correctly.

Your Rocket.Chat version: 0.34

**Comment by spinza** [comment]
Missing date header seems to be addressed.  See my comment here: https://github.com/RocketChat/Rocket.Chat/issues/3165#issuecomment-247885246

**Comment by PPPBerlin** [comment]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

Rocket.Chat notification emails have a spam score of >3. The main reason is the missing "From".
Here is an example from a recent mail I got:

X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "From"
X-Spam-Status: No, score=3.651 tagged_above=0 required=6.2
tests=[BAYES_50=0.8, HELO_MISC_IP=0.25, HTML_MESSAGE=0.001,
HTML_MIME_NO_HTML_TAG=0.377, MIME_HTML_ONLY=0.723,
MIME_QP_LONG_LINE=0.001, MISSING_FROM=1, MISSING_MID=0.497,
NO_DNS_FOR_FROM=0.001, URIBL_BLOCKED=0.001] autolearn=disabled

**Comment by TwizzyDizzy** [comment]
Is this still relevant in 0.62.1? If so, please let me know, otherwise I'll close this issue.

Cheers
Thomas

**Comment by spinza** [comment]
Meteor 1.4.1.1 seems to include the fix that adds a Date header if none are present when Meteor sends an email. (This PR:https://github.com/meteor/meteor/pull/6916)

So this is essentially fixed :) as Rocket used that or a more recent version of Meteor.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Thanks for your feedback! :)

Cheers
Thomas
