### ISSUE TITLE
Enchancements Ideas for Rocket Chat based on DiscordApp

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#3754]
Your Rocket.Chat version: (make sure you are running the latest)

Have you guys heard of Discord?  I was checking out the user interface and I think Rocket.Chat could benefit from some of what it has implemented in terms of readabliity and interface. 

I like how the channels are on the left and the users are all on the right. 
Anyway, it feels a lot like Rocket.Chat, but has been refined heavily to serve the gamer community.  

![discordapp](https://cloud.githubusercontent.com/assets/138841/16773795/94ecee56-4859-11e6-9d73-956b7193fbb3.jpg)
https://discordapp.com/

What do you guys think?

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity.
