### ISSUE TITLE
[Feature request] Add reaction shortcut

### ISSUE THREAD

**Issue by throll** [RocketChat/Rocket.Chat#3756]
It could be nice to have a short cut to the add reaction button when flying over a message without using the cog-wheel button. This feature is highly used on our slack team.
![capture d ecran 2016-07-12 a 17 58 32](https://cloud.githubusercontent.com/assets/899333/16774008/70d1df30-485a-11e6-8bfc-6944eb72b7db.png)

Rocket.Chat version: 0.35

**Comment by lutoma** [comment]
Or even better, do it the way slack does, where `+:thumbsup:` will add a reaction emoji.

**Comment by danilomiranda** [comment]
How about that guys?
![reaction](https://user-images.githubusercontent.com/1092454/28551038-9adc8390-70bb-11e7-984e-f16e8419ac1c.gif)
