### ISSUE TITLE
Textos não aparecem da versão develop do livechat

### ISSUE THREAD

**Issue by athossouza** [RocketChat/Rocket.Chat#3758]
Estou testando a versão develop, vi que ao usar o livechat os textos não aparecem, ou seja, o user guest as mensagens que ele mesmo escreve e as mensagens que o agente escreve não aparecem, ficam em branco.
O agente consegue ver as mensagens normalmente.

**Comment by FibreFoX** [comment]
@athossouza you might want to use english language for this to get recognized

**Comment by sampaiodiego** [comment]
@athossouza this should be fixed.. please comment/reopen if stil happenning
