### ISSUE TITLE
[Feature Request] disable password login

### ISSUE THREAD

**Issue by leo108** [RocketChat/Rocket.Chat#3760]
I hope there will be a switch to control whether users can login in by username and password, if this switch is on, then users can only login with cas/oauth .

**Comment by wargamesqcf** [comment]
its already in, admin > account> Show form-based Login

**Comment by leo108** [comment]
thanks

**Comment by FibreFoX** [comment]
Just to have this documented somewhere: if you have locked out yourself by disabling that option (because you misinterpreted it), it is possible to re-enable this via REST

```
curl http://localhost:3000/api/v1/login  -d "username=USERNAME&password=PASSWORD"
// get you user-id and auth-token

curl -H "X-Auth-Token: LOGIN-TOKEN"  -H "X-User-Id: SOME-ID" -H "Content-type:application/json"  http://localhost:3000/api/v1/settings/Accounts_ShowFormLogin  -d '{ "value": true }'
```

**Comment by engelgabriel** [comment]
@MartinSchoeler maybe we should add this to the docs?
