### ISSUE TITLE
iPhone 6 does not show all group members in portrait format

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3763]
When clicking on the group member icon, and selecting "Show all", the line disappears and nothing happens. If you either turn the phone to landscape or click again the group member icon, all members are shown.
This has been observed on several iPhone6 devices and iPads. 
Any local CSS changes have been removed for testing.

http://imgur.com/iFZyJGh
Your Rocket.Chat version: 0.34

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
