### ISSUE TITLE
[Feature-Request] Shortcuts

### ISSUE THREAD

**Issue by zuernBernhard** [RocketChat/Rocket.Chat#3765]
It would be Great to have Keyboard shortcuts / Keystrokes in Rocketchat to be even faster and more productive.

First ideas:

* Ctrl+C opens a textinputfield with autosuggest to search through all channels/conversations on the current-server.
* Ctrl+P opens a textinputfield with autosuggest to search through all people on the current-server.
* Keystrokes can be configured

**Comment by sewi-cpan** [comment]
Ctrl+C is reserved for "copy" as in "Copy&Paste". Overwriting this would make Rocket.Chat even worse.

**Comment by BackIsBachus** [comment]
I think this is related to #3281 where a few ideas came up to use shortcuts from Hipchat and Slack.

**Comment by zuernBernhard** [comment]
Yes you are right. Lets continue in #3281
