### ISSUE TITLE
choose departments when livechat is open

### ISSUE THREAD

**Issue by fferraro87** [RocketChat/Rocket.Chat#3767]
Your Rocket.Chat version: (make sure you are running the latest) 0.35.0

Hi i create two departments on livechat, so i want that everytime a customer open livechat on my site, he must choose between this two departments. there is a way to do that?
thanks

**Comment by mguspero** [comment]
Hi, this is possible? If not, how to select the customer select the department? 
Thanks!

**Comment by geekgonecrazy** [comment]
This feature was recently added.
