### ISSUE TITLE
Media Preview Broken

### ISSUE THREAD

**Issue by bradnagle** [RocketChat/Rocket.Chat#3771]
Your Rocket.Chat version: 0.35

When posting URL into chat the preview is shown incorrectly

![image](https://cloud.githubusercontent.com/assets/6994704/16823837/4b7eb586-49aa-11e6-9008-48e6882a6a1d.png)

![image](https://cloud.githubusercontent.com/assets/6994704/16823916/f11d6afa-49aa-11e6-9e4c-c5c191ec30dd.png)

![image](https://cloud.githubusercontent.com/assets/6994704/16823862/7bca902a-49aa-11e6-91e0-140404751310.png)

**Comment by CloudDevAU** [comment]
+1 for fixing this.

**Comment by null-dev** [comment]
BTW, the icons8.com one is an issue with icons8, not RocketChat.

**Comment by bradnagle** [comment]
Thanks null-dev. As a comparison the same link shows differently in Skype.

![image](https://cloud.githubusercontent.com/assets/6994704/16826902/bd946a66-49c4-11e6-8ed3-95e82323c4fe.png)

**Comment by MartinSchoeler** [comment]
There is a line break the title tag in the google site:
![image](https://cloud.githubusercontent.com/assets/20868078/17555336/98e070a8-5ee5-11e6-9e16-fa29b2c0c9f9.png)
and in the icons8 there is a angular template:
![image](https://cloud.githubusercontent.com/assets/20868078/17555397/d6a149b2-5ee5-11e6-9a70-8d6d973382f6.png)
the method that gets the information from the title tag wasn't expecting this, that seems to be causing the issue.
We're working on a fix now hope it solves the problem. Thanks for the bug report!
