### ISSUE TITLE
Add permission to use @all and/or option to restrict usage in certain channels 

### ISSUE THREAD

**Issue by craighton** [RocketChat/Rocket.Chat#3774]
Your Rocket.Chat version: 0.35.0

I would love to see an added permission line to restrict the usage of @all in channels. 

Alternatively or in addition a channel option to disable usage in public channels would be awesome.

**Comment by MartinSchoeler** [comment]
@craighton today we have the `mention-all` permission that does exactly that. Thanks for the feedback!
