### ISSUE TITLE
emojis in demo broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#3775]
Your Rocket.Chat version: demo.rocket.chat

![image](https://cloud.githubusercontent.com/assets/5877910/16830428/152cde5a-499f-11e6-95d1-096559abef1e.png)

The emojis in the demo system are broken, i use google chrome.

**Comment by xasx** [comment]
This should probably be automatically fixed after the next rebuild.

**Comment by TheReal1604** [comment]
@xasx Yep, its now working on the Demo system.
