### ISSUE TITLE
Rocket chat OS X client behind enterprise proxy fails to connect to demo server

### ISSUE THREAD

**Issue by md1986** [RocketChat/Rocket.Chat#3776]
Your Rocket.Chat version: 1.31
OS: OS X 10.11.5 El Capitan
Proxy: SSL on Port 9090, configured by a .pac file in the network preferences

Expected Behavior: connect to the demo server and show a proper user interface.
Actual Behavior: empty chat screen (can't attach screenshot here as it seems).

OS X Logs:
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6117]): Rocket.Chat+ Hel(6117) deny mach-lookup org.chromium.Chromium.rohitfork.6116
![Uploading Hardcopy2016-07-14 at 10.14.01.png…]()
![Uploading Hardcopy2016-07-14_101401.png…]()

Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6117]): Rocket.Chat+ Hel(6117) deny mach-lookup org.chromium.Chromium.iosurfacemgr.6116
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6118]): Rocket.Chat+ Hel(6118) deny mach-lookup org.chromium.Chromium.rohitfork.6116
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6118]): Rocket.Chat+ Hel(6118) deny mach-lookup org.chromium.Chromium.iosurfacemgr.6116
Jul 14 10:10:51 MDMBP15 diagnosticd[128]: error evaluating process info - pid: 6117, puniqueid: 6117
Jul 14 10:10:51 MDMBP15 com.apple.xpc.launchd[1] (com.apple.ReportCrash[6119]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
Jul 14 10:10:51 MDMBP15 diagnosticd[128]: error evaluating process info - pid: 6120, puniqueid: 6120
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6120]): Rocket.Chat+ Hel(6120) deny mach-lookup org.chromium.Chromium.rohitfork.6116
Jul 14 10:10:51 MDMBP15 diagnosticd[128]: error evaluating process info - pid: 6121, puniqueid: 6121
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6120]): Rocket.Chat+ Hel(6120) deny mach-lookup org.chromium.Chromium.iosurfacemgr.6116
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6121]): Rocket.Chat+ Hel(6121) deny mach-lookup org.chromium.Chromium.rohitfork.6116
Jul 14 10:10:51 MDMBP15 sandboxd[131] ([6121]): Rocket.Chat+ Hel(6121) deny mach-lookup org.chromium.Chromium.iosurfacemgr.6116
Jul 14 10:10:51 MDMBP15 kernel[0]: Sandbox: Rocket.Chat+ Hel(6122) deny(1) mach-lookup org.chromium.Chromium.rohitfork.6116
Jul 14 10:10:51 MDMBP15 kernel[0]: Sandbox: Rocket.Chat+ Hel(6122) deny(1) mach-lookup org.chromium.Chromium.iosurfacemgr.6116
Jul 14 10:10:51 MDMBP15 networkd[201]: -[NETProxyLookup url] invalid URL scheme '5274'
Jul 14 10:10:52 MDMBP15 ReportCrash[6119]: Saved crash report for Rocket.Chat+ Helper[6120] version 0 to /Users/mdut1002/Library/Logs/DiagnosticReports/Rocket.Chat+ Helper_2016-07-14-101052_MDMBP15.crash
Jul 14 10:10:52 MDMBP15 ReportCrash[6119]: Saved crash report for Rocket.Chat+ Helper[6121] version 0 to /Users/mdut1002/Library/Logs/DiagnosticReports/Rocket.Chat+ Helper_2016-07-14-101052-1_MDMBP15.crash
Jul 14 10:10:52 MDMBP15 ReportCrash[6119]: Saved crash report for Rocket.Chat+ Helper[6117] version 0 to /Users/mdut1002/Library/Logs/DiagnosticReports/Rocket.Chat+ Helper_2016-07-14-101052-2_MDMBP15.crash
Jul 14 10:10:57 MDMBP15 kernel[0]: Sandbox: Rocket.Chat+ Hel(6124) deny(1) mach-lookup org.chromium.Chromium.rohitfork.6116
Jul 14 10:10:57 MDMBP15 kernel[0]: Sandbox: Rocket.Chat+ Hel(6124) deny(1) mach-lookup org.chromium.Chromium.iosurfacemgr.6116
Jul 14 10:11:01 MDMBP15 kernel[0]: Sandbox: Rocket.Chat+(6116) deny(1) file-read-data /Users/mdut1002/Library/Preferences/com.apple.symbolichotkeys.plist

**Comment by geekgonecrazy** [comment]
@md1986 can you open an issue on our electron repo: https://github.com/rocketchat/rocket.chat.electron I don't believe we have support in our desktop client or mobile client for proxies.
