### ISSUE TITLE
Can't see registration form

### ISSUE THREAD

**Issue by david-strejc** [RocketChat/Rocket.Chat#3778]
Your Rocket.Chat version: 35

I am not able to see registration form - I have set registration to public, but without any success.

**Comment by david-strejc** [comment]
WebSocket connection to 'ws://chat.octopussystems.cz/sockjs/096/q2k_27im/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

This is what I am getting in console.

**Comment by MartinSchoeler** [comment]
@david-strejc  is this bug still happening?
