### ISSUE TITLE
Mobile Push Notifications not working for user

### ISSUE THREAD

**Issue by thecanadianbaker** [RocketChat/Rocket.Chat#3779]
Your Rocket.Chat version: 0.35.0

Mobile Device: Samsung Galaxy S7 (SM-G930F)
Android Version: 6.0.1
Rocket.Chat App Version: 2.3.1

Most users receive notifications, but my user (_@jason.murray_) does not, even when using the 'Send A Test Push To My User' button on the _Push_ page in the _Admin_ section. The logs indicate that the push is sent, but then the token is removed after a second test message is sent. The messages are never received :

```
I20160714-12:59:25.076(0) Push: send message "@jason.murray" via query { userId: 'x2Nt7dYczfDYczrYp' } 
I20160714-12:59:25.077(0) Push: send to token { gcm: 'faJ7JfS3ET4:APA91bEFrzqWDrt1xFzQshMtCV1BhGb44XlTtbvXcuQv50EQFbWkwxPXTkHkVuAdbWIfB3Lc2TQT5RARC0vN7f8taVU8-5dWdHqszxn5IzEGOOPz3SXdKIoqESVtjAuPtf-yvOVXXXXX' } 
I20160714-13:22:01.947(0) ldap.js:276 LDAP ➔ Search.error Search by id 31323537 returned 2 records 
I20160714-13:35:28.987(0) Push: send message "@jason.murray" via query { userId: 'x2Nt7dYczfDYczrYp' } 
I20160714-13:35:28.988(0) Push: send to token { gcm: 'faJ7JfS3ET4:APA91bEFrzqWDrt1xFzQshMtCV1BhGb44XlTtbvXcuQv50EQFbWkwxPXTkHkVuAdbWIfB3Lc2TQT5RARC0vN7f8taVU8-5dWdHqszxn5IzEGOOPz3SXdKIoqESVtjAuPtf-yvOVXXXXX' } 
I20160714-13:35:30.268(0) removing push token faJ7JfS3ET4:APA91bEFrzqWDrt1xFzQshMtCV1BhGb44XlTtbvXcuQv50EQFbWkwxPXTkHkVuAdbWIfB3Lc2TQT5RARC0vN7f8taVU8-5dWdHqszxn5IzEGOOPz3SXdKIoqESVtjAuPtf-yvOVXXXXX 
```

The _Push_ configuration page:
![screenshot 2016-07-14 15 43 24](https://cloud.githubusercontent.com/assets/15822260/16841485/b778b3a2-49d9-11e6-9c5c-453e6e9f8c30.png)

**Comment by rasos** [comment]
Push notifications does not work, if you have side loaded your App (not using the version from Google play store), as the GCM keys may be different, see #2754.
