### ISSUE TITLE
Had somebody successfully built working docker image?

### ISSUE THREAD

**Issue by Almax** [RocketChat/Rocket.Chat#3780]
Rocket.Chat version: 0.35
VPS - Ubuntu 1404

The problem is that i can't build RC docker image
i passed through many instructions on the web without success

The oficial docker image rocketchat/rocket.chat works like a charm with https and 80 port
but i would like to run my own fork of the RC with some customization
i'm stucked
i was following steps in the official instructions - how to run RC manually on ubuntu
but https still dont work.  

Could somebody share some working dockerfile configs or anything that help me build my own 
docker image please

**Comment by BorntraegerMarc** [comment]
@Almax Have the exact same issue... Did you solve it already? Would be great  to get some community support on this one.

**Comment by ryannealmes** [comment]
I think I have managed to get this working. Still testing stuff, but it looks like it's working.

It was a bit of a mission but the main points are

### Rocket.Chat section
- clone rocket.chat
- make your changes
- [build](https://guide.meteor.com/deployment.html#custom-deployment) the meteor package
- this generates a tar.gz file with your rocket.chat release 

### Docker section
- get the [dockerfile](https://hub.docker.com/r/rocketchat/rocket.chat/~/dockerfile/) for the rocket.chat image
- [build](https://docs.docker.com/engine/tutorials/dockerimages/) a new docker image with your release in it. If you look at the dockerfile you can see it points to the RC release. This needs to be updated to point to the release you generated in the first section. I used AWS S3 to pull down the release.

```
FROM rocketchat/base

ENV RC_VERSION develop

MAINTAINER buildmaster@rocket.chat

VOLUME /app/uploads

RUN set -x \
 && curl -SLf "https://someaws.s3.link/Rocket.Chat.tar.gz" -o rocket.chat.tgz \
 && tar -zxf rocket.chat.tgz -C /app \
 && cd /app/bundle/programs/server \
 && npm install \
 && npm cache clear

USER rocketchat

WORKDIR /app/bundle

# needs a mongoinstance - defaults to container linking with alias 'mongo'
ENV MONGO_URL=mongodb://mongo:27017/rocketchat \
    HOME=/tmp \
    PORT=3000 \
    ROOT_URL=http://localhost:3000 \
    Accounts_AvatarStorePath=/app/uploads

EXPOSE 3000

CMD ["node", "main.js"]

```
- tag your images with whatever name you want
- get a copy of the RC `docker-compose.yml` file and modify it to reference your newly created images

It helps to have a little background knowledge with docker (mine is ok), but that should work.

**Comment by geekgonecrazy** [comment]
@ryannealmes 's instructions look spot on!
