### ISSUE TITLE
Rocket.Chat+ Mass deployment - Preferences/Settings/Config

### ISSUE THREAD

**Issue by doctorwho92** [RocketChat/Rocket.Chat#3781]
Rocket.Chat+ v1.3.1(15)

We are going to deploy Rocket.Chat+ to all the Macs and Windows machines in our company, and also put rocket.chat.electron on our Linux app server. I'd like a method of dictating default settings so that when any user launches the client, the server address is already populated, and the username field is already populated based on the current console user of the OS.

**Comment by doctorwho92** [comment]
It would be nice to be able to push out a mobileconfig on iOS to do the same

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by doctorwho92** [comment]
why did you close an 22 month old feature request because its not on the short-term road map? I waited this long. Can wait longer.

**Comment by doctorwho92** [comment]
To be clear, this is still the single biggest barrier to adoption of Rocket.Chat in our organization. If I could push it out a config to everyone's computers so that upon launch it would connect them to our rocketchat server, I would simply make Rocket.Chat+ open at login, and people would just provide their username and password, and the numebr of employees on it would exponentially increase. Instead, they all just use the free version of Slack.
