### ISSUE TITLE
Import chat history from gitter

### ISSUE THREAD

**Issue by alexweissman** [RocketChat/Rocket.Chat#3782]
Hi, my FOSS community and I are loving RocketChat!  Thank you so much for the hard work.

We recently set up our own RocketChat server to replace our Gitter chat room, with which we had [major privacy issues](https://github.com/gitterHQ/gitter/issues/1314).

I noticed that there is a feature to import Slack, Hipchat, and Mattermost chat histories.  How about a feature to import Gitter chat history?  Gitter [already offers a REST API](https://developer.gitter.im/docs/rest-api).

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by alexweissman** [comment]
It looks like there is now a generic [Import CSV](https://rocket.chat/docs/administrator-guides/import/csv/) feature, so theoretically I could scrape the Gitter API, parse it out into RC's required format, and then run the import tool.
