### ISSUE TITLE
When sending direct message to guests it shows the browser notification but the user can't see the message

### ISSUE THREAD

**Issue by luigibertaco** [RocketChat/Rocket.Chat#3783]
Rocket.Chat version: 0.35.0

Hi Guys, 

I was introduced to Rocket Chat just 1 hour ago and I am loving it. So I'm not sure about what I found.

When a guest user receives a direct message it shows the browser notification but the guest can't see any direct message.

So, either it should shows the message or it shouldn't allow the other user to send the message to a guest.

Cheers

**Comment by MartinSchoeler** [comment]
@luigibertaco Hey thanks for the bug report i`m currently working on a fix but in the meanwhile you can change the view-d-room permission in the admin permissions tab
