### ISSUE TITLE
Cannot quote attachments.

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3784]
Because attachment messages have no text string, when you quote them and post without editing, there's no content and nothing to link back to original comment.

Not sure what the intended result of quoting an attachment should be, but probably needs to be handled more gracefully. e.g. Auto-insert text like "Quoted attachment - click to view".

Pretty sure this isn't a priority for anyone including me, just logging what I found.

**Comment by MartinSchoeler** [comment]
Hey thanks for the feedback! We will take a  look at that.

**Comment by MartinSchoeler** [comment]
This seems to be working now, if you see this bug again please reopen this. Thanks!
