### ISSUE TITLE
Search for private groups

### ISSUE THREAD

**Issue by seobullshit** [RocketChat/Rocket.Chat#3785]
We use rocket chat as internal chat and discuss many issues in private channels.
Our problem is the search function of rocket.
By using STRG+P you`re able to search for users or channels. Unfortunately you`re not able to search for private groups.
Can you please extend the search function also on private groups.

**Comment by LNarita** [comment]
I'm also using Rocket Chat mainly with private groups, so expanding the search would help a lot. :smile: 
So may I give this issue a try? 
I checked the code out and I think it would be fairly simple to implement that... Well, at least the basic search of private groups you are a member of.

**Comment by engelgabriel** [comment]
Hi, what version are you guys using? On the demo server you can user the `ctrl+p`to search private groups that you are already a member:

![image](https://cloud.githubusercontent.com/assets/1000217/18414118/131e0d54-7795-11e6-918f-e9a2d2bd3ba9.png)

**Comment by LNarita** [comment]
Hi @engelgabriel, I'm using ver. 0.39.0
