### ISSUE TITLE
option to add unsubscribe link to mailer and To have a mail list 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3787]
Hello,

right now to send an email from mailer you have to include "[unsubscribe] link, can we make this optional?? as sometimes people may click on in error or perhaps admin doesnt want to provide that link in one of the emails? 

Also how about getting mailing list downloaded by Admin, in cases when the tool is not accessible, admin can email users from third party mailing system to notify users that they are working on any issues with the build? 

Thanks,

Your Rocket.Chat version: 0.35

**Comment by IQ2022** [comment]
just to add, 
I just tried the [unsubscribe] only bot received that email (luckily).. clicked at the unsubscribe link, which says you are unsubscribed, however it was rocket.chat logo??? 

also how to subscribe back again????

**Comment by isabellarussell** [comment]
This has been tested. Admins have to manually subscribe you again.

**Comment by esivres** [comment]
> This has been tested. Admins have to manually subscribe you again.

How to do that? I can`t find such option in admin panel

**Comment by elMor3no** [comment]
> This has been tested. Admins have to manually subscribe you again.

How?? For error I press on suscribe blink and now im not able to sucribe again. Im the admin

**Comment by vins345** [comment]
> This has been tested. Admins have to manually subscribe you again.

how to subscribe again?
