### ISSUE TITLE
Customize format of messages and message attachments

### ISSUE THREAD

**Issue by alexweissman** [RocketChat/Rocket.Chat#3790]
I'd like to customize the _format_ for messages that come in through my github webhook integration.  Currently, it is possible to customize the _content_ of webhook integrations, [using a custom script as described in the documentation](https://rocket.chat/docs/administrator-guides/integrations/).

However, this doesn't give me any control over the layout/format/CSS that gets applied to these messages.  For example, to format a Github issue comment notification, I tried the following script:

```
    return {
      content: {
        attachments: [
            {
                thumb_url: user.avatar_url,
                title: '#' + request.content.issue.number + ' - ' + request.content.issue.title,
                title_link: request.content.comment.html_url,
                text: request.content.comment.body,
                fields: []
            }
        ]
      }
    };
```

Note the use of `thumb_url` to grab the commentor's avatar and place it in the message.  This produces something like:

![screen shot 2016-07-15 at 6 55 34 pm](https://cloud.githubusercontent.com/assets/5004534/16891499/7b5540bc-4ac8-11e6-95a7-7a5c4547d797.png)

Note that the title is placed above the thumbnail, rather than aligned to the right above the text.  Also, I cannot control the size of the thumbnail.  I would like to instead format it to look more like:

![screen shot 2016-07-15 at 8 16 35 pm](https://cloud.githubusercontent.com/assets/5004534/16891533/10a01f5c-4ac9-11e6-9695-dd3f461dbe7a.png)

It would appear that the DOM for message attachments like this is specified in:
https://github.com/RocketChat/Rocket.Chat/blob/3c919925964f9b5705e30ecbbfc3ae619ba39d27/packages/rocketchat-message-attachments/client/messageAttachment.html

It would be good to have a way to modify this in production.

Your Rocket.Chat version: 0.35.0

**Comment by geekgonecrazy** [comment]
in the text property you can include html and inline css if you wish

**Comment by kiamgrebgnur** [comment]
Hi,

can you explain how to use html in the text property?
`"text": '<span>' + request.content.foo + '</span>'`
prints just the html and replaces the tags with entities.

I've tested it inside and outside the attachment key.

**Comment by jszaszvari** [comment]
@geekgonecrazy Is this still the case, I'm unable to get any custom HTML to render when putting it in the text property. 

Sorry for posting in a old issue.

**Comment by antgel** [comment]
I too see HTML rendered as text in `attachments.text`.

**Comment by valeriucraciun** [comment]
any resolution for this issue?

**Comment by anaida07** [comment]
Adding html in message API is not working for me as well:
Doing
```ruby
body = {channel: "aaaaaaaaa", attachments: [{ html: "<span>abc</span>" }]}
HTTParty.send("post", url, body: body.to_json, headers: login_headers)
```
spits out `<span>abc</span>` instead of just the content.

**Comment by geekgonecrazy** [comment]
I think this is related to some security changes we've made to prevent XSS.

**Comment by geekgonecrazy** [comment]
@rodrigok do we intend for that to still work? Or is this no longer supported?

**Comment by rodrigok** [comment]
It's no longer supported and we are migrating to use uikit for rich messages.

**Comment by duven87** [comment]
Hello! 
last week I upgraded my old rocketchat version 2 to version 4.8.1 and the integrations-webhooks of jira, bamboo, etc the texts now appear as paragraphs, not using the full width of the window, and the links are cut. If you click on them they do not appear complete in the new version.
I found this ticket and it seems to be what I am talking about...
With version 2 it worked correctly.
Do you know if for the imminent release of version 5 it will be fixed? or is there any way to fix it with the latest stable version?

BEFORE V. 2.0:
![image](https://user-images.githubusercontent.com/24485101/179509630-60452c07-02a2-46e0-9c12-e07d86cb04fb.png)

NOW V. 4.8.1:
![image](https://user-images.githubusercontent.com/24485101/179509716-b6a489b4-a49f-41fa-a439-ef6a35edf94b.png)
