### ISSUE TITLE
[request] mobile "location share" feature

### ISSUE THREAD

**Issue by tgxn** [RocketChat/Rocket.Chat#3791]
Your Rocket.Chat version: 0.35.0

I am requesting a "location share" feature for the mobile Rocket.Chat clients on both iOS and Android.
Location data is also available through the [Navigator.geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation) API and could be implemented on the web version also.

Attached sample screenshot from other apps.

![telegram](https://cloud.githubusercontent.com/assets/293107/16893367/2cb0af28-4b68-11e6-80f1-dccc8ac169d7.png)
![hangouts](https://cloud.githubusercontent.com/assets/293107/16893368/2d8a4d1e-4b68-11e6-81aa-56f0cad7fa24.png)

**Comment by soenkef** [comment]
+1 this would be a nice feature. I am looking for location sharing too.

**Comment by okworld26** [comment]
+1

**Comment by tgxn** [comment]
I've started some work on this in [my branch](https://github.com/tgxn/Rocket.Chat/commits/mapview)
