### ISSUE TITLE
New moderator of a channel can not modify there own chat lines until page reloaded

### ISSUE THREAD

**Issue by sacarlson** [RocketChat/Rocket.Chat#3794]
This was detected on the demo.rocket.chat on jul 17, 8:21 that runs version 0.35.0+ when I become moderator of #meteor I was no longer able to edit my own lines in that room.  I Could still edit in other rooms like #support.   When I was put back to user and no longer moderator I still couldn't edit my own lines until I reloaded the page.  I duplicated the same thing in version 0.33.0 and now found that when I become moderator it has the same problem until I reload the page.  So easy work around for now is to just reload the page when you become a moderator or are changed from one type user to another.

**Comment by MartinSchoeler** [comment]
Hey @sacarlson , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
