### ISSUE TITLE
livechat not used markdown sytax on client side

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#3796]
Your Rocket.Chat version: 0.35

**Comment by FibreFoX** [comment]
@vetash is markdown not shown when typed by the website visitor using livechat?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
