### ISSUE TITLE
I don't get the permission prompt in Chrome to enable the mic and camera for video conferencing

### ISSUE THREAD

**Issue by PvUtrix** [RocketChat/Rocket.Chat#3797]
Your Rocket.Chat version: 0.35
Chrome version: 51.0.2704.103

Permission denied, there was an error connecting to your microphone

http://screencast.com/t/WpPvJEYUo

When I try to enable screensharing, I get an error also
"Failed to install desktop sharing extension"
http://screencast.com/t/Cpa3DxY33

**Comment by geekgonecrazy** [comment]
Closing in favor of #3919
