### ISSUE TITLE
Email address slugification has been changed in LDAP login

### ISSUE THREAD

**Issue by junjikinoshita** [RocketChat/Rocket.Chat#3798]
Your Rocket.Chat version: 0.17.0

We've been using 0.17.0 with LDAP authentication and using email address as login name and username. When I tried to update Rocket.Chat to a newer version, I found username slugification changed from 0.18.0. Before 0.17.0, an email address like "jon.doe@company.com" was slugified to "jon.doe", which was good for us. But from 0.18.0, it is slugified to "jon.doeatcompany.com". So existing users cannot login. New users are OK, but a username is a bit long. This is related with #2262 but the problem is email slugification in our case. Is there any way to keep using the old slugification after update?

**Comment by MartinSchoeler** [comment]
Can the old users log in using  their email address?

**Comment by pierre-lehnen-rc** [comment]
Closing this as obsolete.
