### ISSUE TITLE
Prevent large messages

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#38]

**Comment by stephenreid** [comment]
This is important for IRC compatibility. Other chat softwares might recommend attaching the large blob as a text file, and we can even convert to text file for the user.

**Comment by karthick-i2i** [comment]
@rodrigok  Restricting message length to 150. Is that fine ?

**Comment by karthick-i2i** [comment]
@rodrigok  Restricting message length to 150 characters. Is that fine ?

**Comment by sampaiodiego** [comment]
@karthick-i2i I think 150 is too short. maybe it should limit to 500. but certainly should be configurable.

**Comment by karthick-i2i** [comment]
@sampaiodiego Is there any mailing list or any other communication channel for discussion ? So that i could get some help in fixing this issue.

**Comment by AdrianoCahete** [comment]
@karthick-i2i i find some help in #general room of Rocket Demo itself. Worth a try.

**Comment by sampaiodiego** [comment]
@karthick-i2i we used the own rocket.chat to discuss.. =) you can create a channel or group to a more "private" conversation

**Comment by karthick-i2i** [comment]
@AdrianoCahete  Are you saying about this one http://rocket.chat/login . I am unable to login. Its shows some script errors while logging in.

**Comment by AdrianoCahete** [comment]
@karthick-i2i I can't try right now (it's blocked in my work), but @sampaiodiego may can help you.

**Comment by sampaiodiego** [comment]
@karthick-i2i what errors are you getting on http://rocket.chat/login? can you open an issue showing the errors? thanks

**Comment by karthick-i2i** [comment]
![rocket-chat](https://cloud.githubusercontent.com/assets/3647767/8332784/50b87726-1aad-11e5-8bcf-757806416033.png)

**Comment by karthick-i2i** [comment]
Its shows Please wait for long time and i am unable to login. Should i need to make any local system configurations ?

**Comment by sampaiodiego** [comment]
@karthick-i2i I created an issue (#223) to talk about your problem.

**Comment by sampaiodiego** [comment]
I'm reopening this issue because we should check message length on server too, what #403 does not.

**Comment by callmephilip** [comment]
@sampaiodiego : nice catch! i'll patch it up in a new PR. thanks
