### ISSUE TITLE
Send message from cron output

### ISSUE THREAD

**Issue by fferraro87** [RocketChat/Rocket.Chat#3801]
Your Rocket.Chat version: (make sure you are running the latest) 0.35.0

Hi, i've a cron job on same server where is my rocket chat and i want to know if i send output on the chat.
there is a way to do that?
thanks

**Comment by vetash** [comment]
Depens of what you need to send. Is last message or somehing else?

**Comment by fferraro87** [comment]
it's a simple text message, that's an output from a my script.

**Comment by vetash** [comment]
Ok, so go to admin page -> integrations -> create new one -> incoming webhook. Fill all fields save it open it and use example curl command:
`curl -X POST --data-urlencode 'payload={"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' http://{{HERE YOUR WEBHOOK URL`

You need to install curl in your system too.
(apt-get install curl in ubuntu)

**Comment by fferraro87** [comment]
ops sorry but i don't understand, i've a script like this : 
```
#!/bin/sh
res=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "$1")
if [ $res -ne 200 ]
then
	echo "Site $1 is down"
fi]
```
and i put this on crontab to check every x minutes if this website is up or down. and if it's down i want to send a message to rocket chat channel so i haven't a webhook url but only a script
sorry i'm a newbie

**Comment by vetash** [comment]
Like this:
```
#!/bin/sh
res=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "$1")
if [ $res -ne 200 ]
then
curl -X POST --data-urlencode 'payload={"text":"Site $1 is down","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' http://{{HERE YOUR WEBHOOK URL}}
fi
```
To get it work you need go to admin page -> integrations -> create new -> incoming webhook.

**Comment by fferraro87** [comment]
Thanks it works fine, thanks for your help !
