### ISSUE TITLE
Notification problems with cordova mobile app, token not remebered ...

### ISSUE THREAD

**Issue by pandix** [RocketChat/Rocket.Chat#3803]
Your Rocket.Chat version: 0.35.0
Cordova 2.3.1

I succeed to send myself notification on my ios devices (ipad and iphone) with the official app from the appstore.
I need ti have my own compiled cordova app to run on my private server.

But when I'm logging in with my own cordova app and I try to test notification it says "sent to 1 device". But I don't receive anything (as i'm running that app on my device)
To receive a notification I need to quit the app right ?

But when I do, in the admin panel it says "no token for this device" when I try to sent a notification again. As if my device's token was not registered ...

Any idea how to fix that ?

**Comment by geekgonecrazy** [comment]
if i've had that issue in the past logging out and back in on mobile usually does the trick
