### ISSUE TITLE
Ability to ban a livechat guest

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#3806]
Your Rocket.Chat version: 0.35.0
When someone spam the livechat I can't do anything against him.
Is it possible to introduce a banning system for the livechat (browser & IP) ?
Edit : Already suggested here : https://github.com/RocketChat/Rocket.Chat/issues/1824#issuecomment-230642489

**Comment by louisemessage** [comment]
Closing as already suggested here: https://github.com/RocketChat/Rocket.Chat/issues/1824#issuecomment-230642489.
