### ISSUE TITLE
how do rocketchat login

### ISSUE THREAD

**Issue by namnn89** [RocketChat/Rocket.Chat#3807]
I have a website created by PHP, MySql. I want to integrate chat system on the site. when users login to my site, how do rocketchat also login?

**Comment by vetash** [comment]
You need to learn about OAuth. Once you done go to amdministration page an create custom OAuth with button `ADD CUSTOM OAUTH` and do what you want! :)

**Comment by IQ2022** [comment]
@vetash are you assuming to place RC in iframe within the site ? how about if you want the users login first to your website site, (if they are permitted) separate sub domain launch for RC chat, also can you have Social Sign On with OAUTH? basically login screen will always be on your website

**Comment by geekgonecrazy** [comment]
Typical way is via oauth / cas / saml etc.  We do have support for an iframe login method, documentation hopefully coming soon for it

I've opened a ticket on our documentation repo: https://github.com/RocketChat/Rocket.Chat.Docs/issues/109 for those interested in following it
