### ISSUE TITLE
Emoji One upgrade to v2.2.6

### ISSUE THREAD

**Issue by xasx** [RocketChat/Rocket.Chat#3809]
Emoji One has recently received another update.
https://github.com/Ranks/emojione/releases

> This release includes the addition of the Gay Pride Flag (1f3f3-1f308) to the artwork, as well as the removal of asterisk, pound sign, and digit (0-9) replacement which was causing unexpected results.

Please add support for the new ones.

Your Rocket.Chat version: 0.35.0

**Comment by xasx** [comment]
Instructions can be found here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emojione/README.md

However, I don't know whether it is also necessary to update the respective dependency.

**Comment by dwrensha** [comment]
I think this can be closed. https://github.com/RocketChat/Rocket.Chat/commit/b2afdb3af21ebecf9238896dd455fb7c37b947c6 updated to emojione 2.2.6

**Comment by xasx** [comment]
Well, I don't think that putting the new version alone is enough.

IIRC there was something to be done with the auto-completion/suggestion system.

**Comment by sampaiodiego** [comment]
I'll close this since the issue is to upgrade it.
