### ISSUE TITLE
Remove :ba: emoji from parser

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#3811]
Your Rocket.Chat version: 0.35
In last versions flags (`:ru:` `:us:` etc) emoji replaced with `:flag_{{country}}` but `:ba:` is still there :\ We are use RC as our comunication tool for work with networks, so we need to post mac addresses often. And every time wee post this we get:
![000000000000000004](https://cloud.githubusercontent.com/assets/8321589/16950297/8047c538-4dfa-11e6-9d4b-822215eda8f7.png)

This very disapoint me and my team.

**Comment by bott0r** [comment]
how about ``` MACADRESS 12:12:12:12:12 ```

**Comment by SeanPackham** [comment]
Remove in more recent versions of Rocket.Chat
