### ISSUE TITLE
Iframe embed stopped working upon upgrade

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#3816]
Your Rocket.Chat version: 0.35

We upgraded our R.C from 0.26 to 0.35, which we embed in an iframe. For some reason, without anything changing on the host, R.C would not load in the iframe. We received errors related to X-Frame-Options SAMEORIGIN, though we had that in place before the upgrade.

We wound up dropping X-Frame-Options in favor of whitelisting sources via Content-Security-Policy.

Can you think of any reasons moving from 0.26 to 0.35 would have changed anything related to X-Frame-Options?

Thanks!

**Comment by geekgonecrazy** [comment]
A lot changed between the versions.  But I would guess it might have something to do with our iframe settings we added.
