### ISSUE TITLE
Updating Application changes value for Max Message Size 

### ISSUE THREAD

**Issue by mylesw-luma** [RocketChat/Rocket.Chat#3817]
Your Rocket.Chat version: 0.35

When updating to a new version (e.g 0.34 to 0.35 in the last occurrence) the value for maximum message size gets set to 5000, overwriting the previous value.  5000 was the default value for this setting, but we've had to set it to a larger value after each upgrade.

**Comment by geekgonecrazy** [comment]
Is this still happening?  I'm guessing this might have something to do with our migration script.  Feel free to re-open if still occuring
