### ISSUE TITLE
Email validation for new bot user not required

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3818]
Running #develop branch 0.35.0+

When creating user from admin interface, you must provide an email, or get the error "The field Email is required". Is this actually necessary for bot users though, do bots get notifications?

I notice Rocket.Cat has no email, so its obviously not breaking anything. I'd like to avoid having to invent arbitrary variations on email addresses for my small army of Hubots.

**Comment by timkinnane** [comment]
Submitting PR now. This is part of some overhaul to UX and validation logic when manually creating new users as admin. This step addresses the different requirements when creating bot users, i.e. not requiring email address, password change or welcome email.

The UX side needs more work, the form could use more obvious validation states and visual indicators of required fields, also the field order should be changed to make dependent fields follow their parents and toggle entire display instead of just disable fields depending on context.

I will resolve the second part after @Ethaan's work on #3679 has been pulled into core.

**Comment by Rohlik** [comment]
Something new?

**Comment by timkinnane** [comment]
Closing this in favor of #7125 to deal with the validation issue as part of more general update to bot user creation that may end up not requiring an email at all.
