### ISSUE TITLE
Text input very slow, but only in some channels

### ISSUE THREAD

**Issue by Synchro** [RocketChat/Rocket.Chat#3819]
Your Rocket.Chat version: 0.35

I have about 20 channels open on one RC server. I'm using RC in Safari 9.1.1 on OS X 10.11. In some of the channels, the text input box is horribly slow - the fastest it will accept input is about 1 char per sec. This is consistent - once a channel starts acting slowly, it tends to stay that way - log out/in or refreshing the page (and clearing cache) doesn't help. Other channels on the same server work perfectly. It's not related to bandwidth.

I can paste in larger chunks of text and they appear instantaneously (or at least subject to the same inter-character delay I see when typing), so it's often quicker to type into another app and copy & paste into RC. I'm not seeing any JS errors relating to this slowdown.

**Comment by wargamesqcf** [comment]
I also get this, but I know I am not bandwidth, or ram limited and my cpus are around 30% usage.

**Comment by MartinSchoeler** [comment]
Could be related to #31

**Comment by spditner** [comment]
Running into the same input lag problem with RC OSX client 2.10.5. Once a channel goes bad, that's it, logged out, deleted all the caches I could find. Problem persists.

Joining the same channels via Chrome doesn't present the same problem.

**Comment by ggazzo** [comment]
@Synchro we changed the messsagebox and improved the way how we deal with the autogrow ... I think this issue was solved on "> 0.70.x" version of rocket.chat any problem let me know
