### ISSUE TITLE
OAuth server dont work with phabricator

### ISSUE THREAD

**Issue by tomaluca95** [RocketChat/Rocket.Chat#3821]
Hi, I'm using the last version of Rocket Chat (from the docker image) and I can't use the phabricator oauth server.

I write this php code
`
<?php
$data = json_decode(file_get_contents("https://phabricator.<domain>/api/user.whoami?access_token=".$_GET['access_token']));
$data->result->username = $data->result->userName;
$data->result->id = $data->result->phid;
echo json_encode($data);
`
and used the php code as identity path and it works

I think with this patch y
[rocket.chat.phab.patch.txt](https://github.com/RocketChat/Rocket.Chat/files/373756/rocket.chat.phab.patch.txt)

ou can make it works out of the box.

Now it works for me but i have to keep the "php hack", would be nice have this in the next release

**Comment by engelgabriel** [comment]
@tomaluca95  can you do a PR with the changes from the attached patch? I'll review it and approve if they fix the problem for you.

**Comment by tomaluca95** [comment]
My patch is only a guess, i'm not a coffiescript developer.
Now i'm using the php hack

**Comment by engelgabriel** [comment]
You guess seems correct. Do you want to create the PR and get the credits? :) OR do you prefer for us to do it?

**Comment by tomaluca95** [comment]
I prefer you do it
Thanks

**Comment by engelgabriel** [comment]
@rodrigok can you please do this?

**Comment by ruphy** [comment]
ping? the patch is already there, I think it just needs to be applied :)
