### ISSUE TITLE
Message attachments accept "pretext" field

### ISSUE THREAD

**Issue by kkesselwss** [RocketChat/Rocket.Chat#3828]
Rocket.Chat version: latest (v0.35.0)

It seems that markdown is not supported in the "pretext" field on a message attachment. Example JSON:

``` json
{
  "attachments": [
    {
      "color": "good",
      "fields": [
        {
          "title": "Requested by",
          "value": "Normal Paulk",
          "short": true
        },
        {
          "title": "Duration",
          "value": "00:02:03",
          "short": true
        },
        {
          "title": "Build Definition",
          "value": "ConsumerAddressModule",
          "short": true
        }
      ],
      "pretext": "Build <https://fabrikam-fiber-inc.visualstudio.com/web/build.aspx?pcguid=5023c10b-bef3-41c3-bf53-686c4e34ee9e&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f3|ConsumerAddressModule_20150407.2> succeeded",
      "mrkdwn_in": [
        "pretext"
      ],
      "fallback": "Build ConsumerAddressModule_20150407.2 succeeded"
    }
  ]
}
```

This is example JSON that TFS (Team Foundation Server) uses to post messages to channels. Based on previous pull requests, "slack" style webhook JSON schema is supported. However, the text in the `pretext` field seems to be excluded from markdown rendering (i.e. the link in the `pretext` field above does not get rendered as a link), even though this JSON is describing that there is markdown included in the `pretext` field via `mrkdwn_in`.

Also it seems that the "fallback" field is commented out in the [message attachment template](https://github.com/RocketChat/Rocket.Chat/blob/3c919925964f9b5705e30ecbbfc3ae619ba39d27/packages/rocketchat-message-attachments/client/messageAttachment.html#L3).

Thanks.

**Comment by kkesselwss** [comment]
@swe-covis - we've been using the incoming webhook script option to work with the incoming attachment and moving any pretext fields into the text field so that it gets the markdown rendering treatment. It works great, but the same script needs to be added on any incoming webhook that you might have.

**Comment by geekgonecrazy** [comment]
Re-labeled this.  It appears the ask here is that we accept the pretext field in attachments.
