### ISSUE TITLE
Social Feed

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3831]
Is there a way to create an incoming integration to pull data from social feeds, like https://www.rebelmouse.com which is a premium and charge money to add more than 25 feed source.?? 
its basically an ability to pull all kind of feeds from twitter, facebook, instagram.. the idea is to have this kind of feed into a single channel say #news or anything.. 

 Your Rocket.Chat version: (0.35)

**Comment by k0nsl** [comment]
I believe this would be possible via the webhook system. Please, someone correct me if I am wrong.
...although, a "point and click"integration into the administration interface would be an welcome addition. Maybe even as an optional plugin/extension.

**Comment by IQ2022** [comment]
something like this?? can you help in creating the webhook?

https://github.com/armaanshah96/cuRate

**Comment by geekgonecrazy** [comment]
Definitely possible via webhooks I think this would be our recommended approach for bringing feeds of data in.
