### ISSUE TITLE
"Search Emoji" UI Problem - Deux

### ISSUE THREAD

**Issue by codyaray** [RocketChat/Rocket.Chat#3835]
Your Rocket.Chat version: 0.35.0

This is a duplicate of the closed #3570 ticket. We're seeing this quite frequently across a bunch of different users in our company now. Any ideas?

**Comment by vetash** [comment]
Hello @codyaray . Can you post more info? E.g. wich browser you use, what you did before this issue? 
More info will be very helpful for devs. Also if you can post logs of your RC and if you can reproduce issue and post videos i'ts will be great :)

**Comment by codyaray** [comment]
This is in Chrome 52. Have others reported this issue? I've only hit it once, but many of my users have hit it several times. Not enough to be terribly pressing yet, but its on the rise.

![screen shot 2016-08-05 at 8 12 07 am](https://cloud.githubusercontent.com/assets/44062/18038313/0b727ac4-6d5c-11e6-8c41-58ab21ba0ba4.png)

**Comment by RichardFoxworthy** [comment]
I've got this issue again - this time via my Electron native client on Mac. The underlying RC is v35. It looks OK when accessed by my own Crome browser, but same issue occurs for my colleague

**Comment by codyaray** [comment]
This is occurring for almost all of our users now, post-upgrade to 0.39.0, across windows and mac native clients as well as web UI in Chrome.

**Comment by adesimonepeak6** [comment]
Same issue here, had to turn off emoji's

**Comment by brocktimusprime** [comment]
I am also seeing this issue. I also had to turn emoji's off

**Comment by codyaray** [comment]
Turning off emojis hasn't fully cleared it for me. But maybe I'm doing it
wrong.

**Comment by alpha14** [comment]
Same problem here, happens randomly. I have to restart the app to make it disappear.

**Comment by engelgabriel** [comment]
I believe this problem was fixed. Please reopen if the persists.
