### ISSUE TITLE
Allow to turn avatar image 90 or 270 degrees

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#3838]
With the Rocket.Chat iOS App, users can immediately take a picture to be used for their profile image. However, if they do it in portrait format, the image is 90 or 270 degrees flipped. 
Proposal: Offer a button, to correct the angle of the profile image in the changeavatar menu.

Your Rocket.Chat version: 0.34

**Comment by MartinSchoeler** [comment]
Please reopen this on the mobile repos. Thanks!
