### ISSUE TITLE
Rest API: login endoint does not exist

### ISSUE THREAD

**Issue by Jack-Collins** [RocketChat/Rocket.Chat#3839]
Your Rocket.Chat version: latest

![image](https://cloud.githubusercontent.com/assets/13108027/17050908/6da6dfdc-4fed-11e6-8d6a-8370d63a93de.png)

Has this endpoint been moved or am I missing something here?

thanks

**Comment by vetash** [comment]
Hello! Do you send login and password in request? 
```curl http://localhost:3000/api/login -d "user=myusername&password=mypassword"```

**Comment by Jack-Collins** [comment]
Ah thank you I was stupidly sending it like 

    curl http://localhost:3000/api/login **\** -d "user=myusername&password=mypassword"
