### ISSUE TITLE
Unable to use WebRTC over LAN and local STUN server

### ISSUE THREAD

**Issue by NaurisSadovskis** [RocketChat/Rocket.Chat#3841]
Your Rocket.Chat version: 0.35

Hi guys,
I'm running RocketChat on CentOS 7.2. Everything works fine, apart from WebRTC. I removed public stun/turn servers (as our machines don't have direct Internet access) and set up a STUN server (https://github.com/enobufs/stun) on Node JS. It appears to be working fine (STUN server outputs requests) when testing from running STUN client from other machines (both Windows and Linux). However, when server is added to WebRTC section in RocketChat config, it doesn't seem to make any connection from RocketChat -> STUN server and audio/video call does not start. 

Has anyone managed to get WebRTC working over LAN? What would you recommend?

Thanks in advance, RocketChat looks great.

**Comment by t2d** [comment]
I just removed all STUN servers. Worked with native client and chromium.

**Comment by rasos** [comment]
Usually you get much better connectivity results with an additional TURN server. In case the firewall / routing set-up does not allow p2p connections, a TURN server mirrors the streams.

**Comment by MartinSchoeler** [comment]
I will close this due lack of updates, if this issue turns relevant again, feel free to reopen this issue. Thanks
