### ISSUE TITLE
tagging user using @ is working only in the first line of the chat

### ISSUE THREAD

**Issue by kashifnawaz123** [RocketChat/Rocket.Chat#3842]
Your Rocket.Chat version: 0.35.0

 tagging user using @ is working only in the first line of the chat, if we use a line break and try to use @ in the second line its not working. Earlier it use to work, looks like some thing changed in the latest release.

Steps to reproduce:
1. in chat window type something and press shift +enter , 
2.now you are in second line , try to tag people using @ , highlighting doesnt comes up and i cannot send message to that user

![image](https://cloud.githubusercontent.com/assets/19670116/17064456/311c78a2-505a-11e6-84e3-d8ea27aee171.png)

**Comment by vetash** [comment]
@kashifnawaz123 you need to type at least one symbol at left for this:
![000000000000000008](https://cloud.githubusercontent.com/assets/8321589/17151857/32ee7b2c-53b0-11e6-90d4-6a5534dab86c.png)

heheheh. :smile:

**Comment by kashifnawaz123** [comment]
it works @vetash , but is this Workaround or working as expected, Rocket i guess still need to fix it right

**Comment by vetash** [comment]
Yeah, I thought as the same

**Comment by TwizzyDizzy** [comment]
still present in 0.61.0

**Comment by Hudell** [comment]
It's working on 0.65.1. It may have been fixed by the recent refactoring done in the notification system. If anybody runs into this problem again the issue can be reopened.
