### ISSUE TITLE
LDAP custom password reset link

### ISSUE THREAD

**Issue by michaudg** [RocketChat/Rocket.Chat#3844]
Your Rocket.Chat version: 0.35

We use LDAP authentification and it would be useful if we can change the password reset link to our own password reset link service.

Thank you.

**Comment by nebulade** [comment]
Given all those LDAP changes since this issue was created, is there any update on that?

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
