### ISSUE TITLE
Can't submit same attachment twice in a row.

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3853]
v0.35.0

If you try to send an attachment message with the same attachment that was last sent, nothing happens, no feedback or message submitted. However if you send attachment A, then B, then attachment A again, it sends normally.

Don't know if this is a bug, but there's at least inconsistent behaviour without clear feedback of what's happening. If the intention is to prevent duplicate submissions, it doesn't work consistently and should trigger a readable error alert.

**Comment by MartinSchoeler** [comment]
This has been fixed.
