### ISSUE TITLE
Emoji search on demo server broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#3854]
Your Rocket.Chat version: demo system

![2016-07-25 07_59_01- rocket chat](https://cloud.githubusercontent.com/assets/5877910/17091773/ca23a996-523d-11e6-8515-4b5da50533f6.jpg)

(Google Chrome)

**Comment by k0nsl** [comment]
Clear cache and `ctrl+r`, that should do it.

**Comment by TheReal1604** [comment]
Cache cleared and reloaded. Issue persists.

**Comment by TheReal1604** [comment]
Now its working... ?!
