### ISSUE TITLE
Iniciar automaticamente Ubuntu-Server 14.04

### ISSUE THREAD

**Issue by guilhermecatini** [RocketChat/Rocket.Chat#3856]
Instalei a última versão do Rocket.Chat e está funcionando corretamente quando executo node main.js

Porém quando fecho o terminal do AWS, o serviço para.

Como faço para deixar rodando de maneira automática?

**Comment by geekgonecrazy** [comment]
@guilhermecatini please see our documentation https://rocket.chat/docs/installation/manual-installation/pm2-systemd-upstart#pm2
