### ISSUE TITLE
Set default setting for notifications

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#3862]
Your Rocket.Chat version: 0.35

Allow user or admin to set a default setting for notifications. Currently it says 

> Mentions (default)

 but it doesn't seem possible to change this.
![image](https://cloud.githubusercontent.com/assets/5689874/17119449/e79a86fe-52bd-11e6-97c4-88db8d573c1e.png)

For our team, most channels don't get too many messages in, so it is fine to receive notifications for all channels, otherwise we end up missing them. It's annoying having to change the setting for every channel.

**Comment by Flipez** [comment]
+1

**Comment by megabit-computing** [comment]
+1

**Comment by jusfeel** [comment]
+1

**Comment by evtuhovdo** [comment]
+2

**Comment by willihelm** [comment]
+1

**Comment by KirschbaumP** [comment]
+1

**Comment by x-drum** [comment]
+1 , many users expect a different default behaviour for rooms (e.g: notify for every new message), this will be very useful for administrators and can ease the adoption.

**Comment by Rivenhall** [comment]
+1 as an admin for some of our rooms, this would be a very useful feature.

**Comment by fuzunspm** [comment]
+1 this should be very useful since the default one is not suits direct messages. I need to change it to all whenever a direct message created/received

**Comment by shubhampatel812** [comment]
+1

**Comment by rodrigok** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/pull/7479
