### ISSUE TITLE
Xmpp Using ejabberd server: Error Code 500: Users are not allowed to register accounts so quickly

### ISSUE THREAD

**Issue by svenkey** [RocketChat/Rocket.Chat#3864]
Hi All,
I have tried to register 10 users only using ejabberd server. When i have checked in the server/DB, only one user getting registered. We have found error code 500(resource-constraint) and it represents Users are not allowed to register accounts so quickly. Referred many sites and changed the configuration to {registration_timeout, infinity} in ejabberd server. Still we are facing the same issue.

I have referred many sites and done the changes accordingly still issues not yet solved. I am placing the script and dump content for reference. Please go through and anybody assist on this.

Below one is ejabberd yml file below.

pubsub_createnode:
- allow: local
  ## In-band registration allows registration of any possible username.
  ## To disable in-band registration, replace 'allow' with 'deny'.
  register:
- allow
  ## Only allow to register from localhost
  trusted_network:
- allow: loopback
  ## Do not establish S2S connections with bad servers
  ## s2s:
  ## - deny:
  ## - ip: "XXX.XXX.XXX.XXX/32"
  ## - deny:
  ## - ip: "XXX.XXX.XXX.XXX/32"
  ## - allow
## is limited to 1 account every 10 minutes. To disable, specify: infinity

registration_timeout: infinity

**Comment by svenkey** [comment]
Above statement is already given. Still we have issue to register more than one user within from same IP.

Please assist to solve this issue...

**Comment by geekgonecrazy** [comment]
@svenkey we have a bulk register api method.  Would this work?

**Comment by MartinSchoeler** [comment]
@svenkey please try to use the bulk register api method. If that doesn't work for you please reopen this. Thanks!
