### ISSUE TITLE
Bug with admin room menu

### ISSUE THREAD

**Issue by vetash** [RocketChat/Rocket.Chat#3868]
Your Rocket.Chat version: 0.35.
Some css\js bug with view admin page.
1 Open room\private channel\pm
2 Open admin page - select room section
3 Close admin page, select same room\private channel\pm
4 Open admin page:
![000000000000000010](https://cloud.githubusercontent.com/assets/8321589/17153732/ee33c5d8-53b8-11e6-9d81-0b58e135ecd9.png)

Messages messed up with server info.

**Comment by lucasvanhalst** [comment]
I've also noticed this, only happens sometimes

**Comment by timkinnane** [comment]
+1

**Comment by dytec** [comment]
+1

**Comment by phutchins** [comment]
This happens probably %20 of the time for me. Would love to see this one fixed...

**Comment by vetash** [comment]
I'm sure this bug is covered by some commit at least 2-5 releases ago.
