### ISSUE TITLE
Stuck showing loading gif after logging in

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#3872]
Your Rocket.Chat version: 0.35 latest development branch 0040e5a43b0b2c57a898e1f77d1eb1248a0edc8b 

After logging in it shows loading screen indefinitely until user refreshes.

To recreate:

1. Login
2. Send message in channel or create new channel
3. Logout
4. Log back in with the same user

For me the second time you log in it gets stuck every time, but only after sending a message. If you logout having not done anything, logging in is fine.

**Comment by dytec** [comment]
I can confirm this behaviour...

**Comment by waley1975** [comment]
I have the same problem.

**Comment by MaxXor** [comment]
I can confirm that this problem still exists in version 0.36.

**Comment by MartinSchoeler** [comment]
@rodrigok just so you know when you refresh the page the login process continues as normal, without asking to login again.

**Comment by Syirrus** [comment]
I posted about this over a month ago. 
#3761 
https://github.com/RocketChat/Rocket.Chat/issues/3761#issuecomment-238451078

**Comment by drickerusa** [comment]
I'm having the same issue in 0.39.0. I'm trying to run performance test with silk performer but the scripts keep on getting hung up on the login screen. Our test guy even put in a reload to get past this. Sometimes it works but most of the time its sets at the loading screen. From the users standpoint most of them see it waiting and when they reload it will continue.

**Comment by Syirrus** [comment]
@drickerusa Yeah it's still an issue. A quick and dirty hack that I've been using since I discovered this is to just reload the page.

Last line in rocketchat-ui-sidnav/side-nav/accountBox.coffee:  
added `windows.location.href='/home';` and commented out the line before.
To:
`
	'click #logout': (event) ->
		event.preventDefault()
		user = Meteor.user()
		Meteor.logout ->
			RocketChat.callbacks.run 'afterLogoutCleanUp', user
			Meteor.call('logoutCleanUp', user)
			#FlowRouter.go 'home'
			window.location.href='/home'
`
