### ISSUE TITLE
Feature request: Allow Rocket.Chat to act as OAuth server

### ISSUE THREAD

**Issue by plaidpowered** [RocketChat/Rocket.Chat#3880]
Your Rocket.Chat version: 0.35.0

My organization has multiple software packages that require logins, most of which support OAuth - but we can't use a third-party OAuth server like Facebook or Twitter. So we'd like to use the Rocket.Chat accounts across all our internal websites, with Rocket.Chat acting as the OAuth server/gateway. 

Is this already possible? Or is it something that would have to be developed?

**Comment by rasos** [comment]
Alternatively, you might want to build an LDAP service and let all your software authenticate against it, including Rocket.Chat. Here is a list of OAuth2 server implementations: http://oauth.net/2/

**Comment by louisemessage** [comment]
Closing to clear the backlog, but we can re-open if we decide to start developing this.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
