### ISSUE TITLE
Reset password URL incorrect

### ISSUE THREAD

**Issue by ketiltrout** [RocketChat/Rocket.Chat#3883]
Your Rocket.Chat version: 0.35.0

When requesting a password reset, the server sends me a two-part message:
- The first part has Content-Type: text/plain and provides an incorrect URL including a spurious hash mark.
- The second part has Content-Type: text/html and provides the correct URL.

E-mail quoted below.

```
From: "Rocket.Chat" <no-reply@rocket.chat>
To: [redacted]
Subject: How to reset your password on Rocket.Chat
Content-Type: multipart/alternative; boundary="----mailcomposer-?=_1-1469841040783"
Date: Sat, 30 Jul 2016 01:10:39 +0000

------mailcomposer-?=_1-1469841040783
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hello,

To reset your password, simply click the link below.

https://[redacted].rocket.chat/#/reset-password/[SHA256 hash]

Thanks.

------mailcomposer-?=_1-1469841040783
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hello,

To reset your password, simply click the link below.

https://[redacted].rocket.chat/reset-password/[SHA256 hash]

Thanks.

------mailcomposer-?=_1-1469841040783--
```

The hashes in the two URLs are the same; the only difference is the spurious `#/` in the text/plain part.

**Comment by rasos** [comment]
Still pending in 0.52. The URL is not linked in the e-mail message and thus not clickable.

**Comment by a11anarete** [comment]
Hi, I am getting the same url error after a password reset.

The email below shows the link but this link goes straight to the login page.
  
**However, I found by removing the hash # on the link it takes you to the correct page.**

Where can I change the URL and remove this # hash on the reset password?

###

_Hello,

To reset your password, simply click the link below.

https://[hostname]/#/reset-password/[SHA256 hash]

Thanks._

###


Many thanks,
Allan

**Comment by a11anarete** [comment]
Just for information, I was looking at the `app.js` which had this line and thought this was the problem.  I removed the `#/` and restarted the service but still the same error.

...
				Accounts.emailTemplates.resetPassword.html = function (userModel, url) {
					url = url.replace('/#/', '/');
					return html.replace(/\[Forgot_Password_Url]/g, url);
				};
...

**Comment by a11anarete** [comment]
@graywolf336 -- Just wondering if you could look at this issue as it is still outstanding since 2016?  I notice you looked at the same code block with issue #5914

code block:

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/sendForgotPasswordEmail.js#L14

Thanks in advance.
Allan

**Comment by a11anarete** [comment]
Right I got around the problem by adding a place holder for the reset password URL.

``` javascript
https://hostname/reset-password/sha256
```
The only issue I have with this is this `sha256` part,  I attempted to use the URL with just `https://hostname/reset-password/` but the page hangs.

Can this be changed somehow, without the `/sha256` part?

Allan

**Comment by geekgonecrazy** [comment]
Copying links over from my duplicate issue #8650

Here is where the email is constructed it looks like: https://github.com/meteor/meteor/blob/devel/packages/accounts-password/email_templates.js#L7

Here is where the url is built: https://github.com/meteor/meteor/blob/devel/packages/accounts-base/url_server.js#L7
