### ISSUE TITLE
When removing a user from a room it gives the error "Invalid role"

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#3884]
Your Rocket.Chat version: 0.35

When removing a user from a room it gives the error "Invalid role", even though the user is still removed from the room.

![image](https://cloud.githubusercontent.com/assets/5689874/17269018/e299800e-5634-11e6-836b-4976dc41df5d.png)

FYI I am an admin and the room owner

**Comment by k0nsl** [comment]
This is a duplicate of #3603.

**Comment by alexbrazier** [comment]
Thanks @k0nsl, didn't see that. Closing as it now seems to be resolved
