### ISSUE TITLE
SlackBridge images not downloading

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#3885]
Your Rocket.Chat version: 0.35
This is the log message I'm seeing

In rocketchat I see the message with the image title but the image itself is a 0kb file

`I20160730-06:59:31.602(0) SlackBridge ➔ Events.debug MESSAGE:  { type: 'message',   subtype: 'file_share',   text: '<@U02QXBU1T|mrplowdan> uploaded a file: <https://***.slack.com/files/mrplowdan/F1WLS0718/2knb9fq9jc.png|2KNB9FQ9JC.png>',   file:     { id: 'F1WLS0718',      created: 1469861970,      timestamp: 1469861970,      name: '2KNB9FQ9JC.png',      title: '2KNB9FQ9JC.png',      mimetype: 'image/png',      filetype: 'png',      pretty_type: 'PNG',      user: 'U02QXBU1T',      editable: false,      size: 25277,      mode: 'hosted',      is_external: false,      external_type: '',      is_public: false,      public_url_shared: false,      display_as_bot: false,      username: '',      url_private: 'https://files.slack.com/files-pri/T02LKC3LA-F1WLS0718/2knb9fq9jc.png',      url_private_download: 'https://files.slack.com/files-pri/T02LKC3LA-F1WLS0718/download/2knb9fq9jc.png',      thumb_64: 'https://files.slack.com/files-tmb/T02LKC3LA-F1WLS0718-f70c28fa71/2knb9fq9jc_64.png',      thumb_80: 'https://files.slack.com/files-tmb/T02LKC3LA-F1WLS0718-f70c28fa71/2knb9fq9jc_80.png',      thumb_360: 'https://files.slack.com/files-tmb/T02LKC3LA-F1WLS0718-f70c28fa71/2knb9fq9jc_360.png',      thumb_360_w: 98,      thumb_360_h: 64,      thumb_160: 'https://files.slack.com/files-tmb/T02LKC3LA-F1WLS0718-f70c28fa71/2knb9fq9jc_160.png',      image_exif_rotation: 1,      original_w: 98,      original_h: 64,      permalink: 'https://****.slack.com/files/mrplowdan/F1WLS0718/2knb9fq9jc.png',      permalink_public: 'https://slack-files.com/T02LKC3LA-F1WLS0718-54fe502be8',      channels: [],      groups: [],      ims: [],      comments_count: 0 },   user: 'U02QXBU1T',   upload: true,   display_as_bot: false,   username: '<@U02QXBU1T|mrplowdan>',   bot_id: null,   team: 'T02LKC3LA',   channel: 'G1WLEDK2B',   ts: '1469861971.000010' } 
`

**Comment by engelgabriel** [comment]
@mrplow I believe @marceloschmidt has fixed this on our current release, please reopen otherwise.
