### ISSUE TITLE
It is not possible to send direct message to myself over the API

### ISSUE THREAD

**Issue by tchap** [RocketChat/Rocket.Chat#3886]
Your Rocket.Chat version: unknown, but probably pretty much latest.

I am sending the following HTTP request:

``` bash
exec curl -H "X-Auth-Token: $TOKEN" \
          -H "X-User-Id: $USERID" \
          -H "Content-Type: application/json" \
          -X POST \
          -d '{"text": "HELLO!", "channel": "@nobody"}' \
          'https://hidden/api/v1/chat.postMessage'
```

In case `nobody` is the authenticated user, I get 

``` json
{"success":false,"error":"error-invalid-user"}
```

The command work just fine when sending to any other user than the authenticated one. So, why is it not possible to send messages to myself?

**Comment by NickBusey** [comment]
There is actually code preventing this from happening. I'm not sure why, and tried to remove it, unsuccessfully last year. I would still love to be able to message myself. Would be great to have an auto-syncing scratch pad on all devices.

**Comment by engelgabriel** [comment]
Was this solved by https://github.com/RocketChat/Rocket.Chat/issues/8015 ?

**Comment by ggazzo** [comment]
running on 0.74 works
```
curl -X POST \
  http://localhost:3000/api/v1/chat.postMessage \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \

  -H 'x-auth-token: asdasda' \
  -H 'x-user-id: asdasdaasd' \
  -d '{"text": "HELLO!", "roomId": "MJT9c4YfnGHPYmmfQ"}'
```
please any problem, reopen :)
