### ISSUE TITLE
Went to bed and now i woke up and RocketChat Magically won't work

### ISSUE THREAD

**Issue by Truative** [RocketChat/Rocket.Chat#3889]
Went to bed last night, setup rocket chat. Everything was working great. Woke up in the morning and went to go work on the chat and i get this 

[https://gyazo.com/d652c5deb8e3d5173820f2eeffa721c2](https://gyazo.com/d652c5deb8e3d5173820f2eeffa721c2)

Ran `Docker Ps`
in both directories for RocketChat and Root. Mongo and RocketChat are both running. 

Im on a Digital ocean VPS btw. 

Anything i am doing wrong?

**Comment by tgxn** [comment]
Hey there!

It would help a lot if you could provide extra details about how your environment is configured!

Are you running on the standard meteor port (3000) and do you have any reverse-proxying configured for this?

It seems from your screenshot that whatever service you're trying to hit on your server isn't running.

**Comment by graywolf336** [comment]
@Truative I'm going to go ahead and close this, however once you post more information about your setup please feel free to open again so we can help you get this figured out.
