### ISSUE TITLE
keep notification until chat windows load

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#389]
while in another tab the notifications for the last room are not displaying (eg. we have 2 rooms "work" and "social" and we are currently on "work" and switch to github. If someone type something in "work" there will not be a persistent notification as if someone type in "social" )

**Comment by rodrigok** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/397

**Comment by oinirio** [comment]
awesome thanks
