### ISSUE TITLE
inline code and multi line code blocks separators with some not english keyboards

### ISSUE THREAD

**Issue by maurocap** [RocketChat/Rocket.Chat#3894]
Your Rocket.Chat version: 0.35

Inline code and multiline code separators both use ` (ASCII 96). This character is not bound to any key in some of the international keyboards (like italian keyboards). These keyboards users must type alt+96 multiple times when they want to add a code fragment.
Not usable at all...

Suggestion: add a clickable link or button to write the `or````` sequence into the current chat text (like the github issue editor?). This should help usability with different keyboards layout.

**Comment by elrond1999** [comment]
This. The ``` is also hard to reach on a Norwegian keyboard. shift ` + space. That is many keystrokes. Clicking the "multi line" should add the quotes directly. Or allow to switch from ``` to """

**Comment by SeanPackham** [comment]
Is now implemented with inline and multi-line code buttons.
