### ISSUE TITLE
Using jmeter Version:2.8.20130705 --> Put Method is not working when passing the value through parameter for Http request in Jmeter tool. 

### ISSUE THREAD

**Issue by svenkey** [RocketChat/Rocket.Chat#3896]
Hi All,
I am using **Jmeter Version - 2.8.20130705**

I am using Put Method to update the records in http request while executing the api in response getting blank and error code is 400(Bad request) under Sampler result tab. When i checked the request tab, there is no value in Put data, that means input value is not going to server while executing. We referred many sites and got some information, but it is not working. We are using Apitoken, UserId & Content type as application/json in Header Manager. Enclosing the screen shot of put method for your reference

![update expense http request](https://cloud.githubusercontent.com/assets/20576069/17332575/d916bc80-58ec-11e6-878d-1291e974ab4f.png)

Please assist to solve this issue

Thanks,
Venkey.

**Comment by geekgonecrazy** [comment]
Looks like you are using some 3rd party tool to make api request.    From the look of it you're actually calling something besides Rocket.Chat api's also?  

Closing as does not appear to concern Rocket.Chat
