### ISSUE TITLE
Have an admin setting to set cookies with secure flag set

### ISSUE THREAD

**Issue by brendanheywood** [RocketChat/Rocket.Chat#3899]
Your Rocket.Chat version: 0.35

ie even if only serving over https with http redirecting to https, cookie session data is leaked if you can get the browser to visit the http.

I'd expect a new setting adjacent to: Admin > General > Force SSL

**Comment by marceloschmidt** [comment]
@ggazzo please assign someone to review if this is still an issue and if not, please close.

**Comment by engelgabriel** [comment]
@tassoevan is this still the case?

**Comment by engelgabriel** [comment]
We are now setting cookies as secure if the chat was accessed via https. Does this resolve the issue?

**Comment by engelgabriel** [comment]
Please reopen if this is still a problem after the change.
