### ISSUE TITLE
msgbox shimmy when typing new message

### ISSUE THREAD

**Issue by dbushong** [RocketChat/Rocket.Chat#3900]
Your Rocket.Chat version: 0.36.0

When you type the first char into the msg box for a new msg, the attachment icon shifts (something w/ flexbox css?) - it's super-distracting:

![shimmy](https://cloud.githubusercontent.com/assets/97162/17351390/e18d0bda-58e2-11e6-88d5-931e9b16acff.gif)

**Comment by danieldafoe** [comment]
What browser/device are you using?

**Comment by dbushong** [comment]
Chrome macOS & Electron macOS client.  Confirmed by other people using my same server - let me know if you want an acct - email me david@bushong.net  Confirmed that I do *not* see it in the same browser on https://demo.rocket.chat/

Forgot to mention that only saw this after 0.35 -> 0.36 upgrade (did full cache clears in the browser just to make sure all CSS updated)  I do have some custom site CSS, but I wiped it and still saw the same problem (again after cache clear)

I'll try to figure out what's different between mine & demo site to hunt this down.

**Comment by dbushong** [comment]
Ah hah, the difference is that the demo site never shows the video chat button.

It's this disappearing when you start typing that's causing the shimmy, somehow.

**Comment by dbushong** [comment]
Confirmed, if you disable "Admin > Messages > Video Recorder Enabled" the problem "goes away"
