### ISSUE TITLE
name/link of channel/room in email notifications doesn't work with subfolder

### ISSUE THREAD

**Issue by peccu** [RocketChat/Rocket.Chat#3902]
Your Rocket.Chat version: 0.36.0

PR #3814 is not work when ROOT_URL with subfolder.

My `ROOT_URL` is `http://domain/subfolder`.

notification mail link is like `http://domain/subfolderdirect/name`.

Is my `ROOT_URL` is wrong?

**Comment by engelgabriel** [comment]
We must try to replace all calls to `ROOT_URL` with a specific method that makes sure the returned string ends with a `/`

**Comment by MartinSchoeler** [comment]
Hey the issue is being worked on here #3946 we hope it solves your problem!

**Comment by peccu** [comment]
umm...
current develop branch(0762aeafb9000a32ed809cd0e84546097dbc7788) still generates wrong url.
PR #3946 changes url from `http://domain/subfolderdirect/name` to `http://domain/direct/name`.

I think it should `http://domain/subfolder/direct/name`.

**Comment by peccu** [comment]
This issue needs fixes like this PR.
https://github.com/RocketChat/Rocket.Chat/pull/3981/files
