### ISSUE TITLE
The custom field isn't displayed on the guest's chat window.

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#3905]
Your Rocket.Chat version: 0.36.0
I set one custom field for the Livechat but it isn't displayed on the guest's chat window:
![](https://i.unixfox.eu/53-14-40-2016.png)
Did I made a mistake or this feature don't work like that ?

**Comment by MartinSchoeler** [comment]
Did you call the rocket chat function in your code?
Like in this example https://rocket.chat/docs/developer-guides/livechat-api/

**Comment by unixfox** [comment]
Yes I've already tried it:
````
<!-- Start of Rocket.Chat Livechat Script -->
<script type="text/javascript">
(function (w, d, s, u) {
w.RocketChat = function (c) {
w.RocketChat._.push(c)
};
w.RocketChat._ = [];
w.RocketChat.url = u;
var h = d.getElementsByTagName(s)[0],
j = d.createElement(s);
j.async = true;
j.src = 'https://chat.aresrpg.fr/packages/rocketchat_livechat/assets/rocket-livechat.js';
h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://chat.aresrpg.fr/livechat');
</script>
<script type="text/javascript">
RocketChat(function() {
this.setCustomField('pseudo', 'Enter your nickname here.');
});
</script>
<!-- End of Rocket.Chat Livechat Script -->
````
No field is displayed:
![](https://i.unixfox.eu/00-14-38-2016.png)

**Comment by unixfox** [comment]
Okay I realised that the feature doesn't work like I was expected, I'll make an issue about I what I was thinking.

**Comment by vladimirprieto** [comment]
i have the exact same situation here.

issue is closet so i must understand that it was fixed?

rocket.chat 0.51 on ubuntu 16.10.

**Comment by unixfox** [comment]
@vladimirprieto I had misunderstood the feature, I made an issue about what I expected to see: https://github.com/RocketChat/Rocket.Chat/issues/4378

**Comment by vladimirprieto** [comment]
ok...i understand that we both understand the same.  so now the real question is:

what are custom fields for? how do we use them?

**Comment by unixfox** [comment]
Actually the custom fields are designed to track the user on the Livechat by adding additional information using the API (in Javascript) which will be available on information tab only by Livechat agents & managers:
![selection_108](https://cloud.githubusercontent.com/assets/4016501/22862201/a975675c-f12a-11e6-8f62-8e7840c523ef.png)

**Comment by vladimirprieto** [comment]
thank you very much!

**Comment by burhangul** [comment]
Hi, How i add custom field to this screen ? How can i communicate with api ? Thank you everyone already.
![exmp](https://cloud.githubusercontent.com/assets/18610205/24348727/60fbc570-12e5-11e7-99a5-0e64a0829ddd.PNG)

**Comment by unixfox** [comment]
@burhangul 
> How i add custom field to this screen ?
You can't, an issue has been opened for this feature: #4378.
> How can i communicate with api ?
The documentation is here: https://rocket.chat/docs/developer-guides/livechat-api#-set-custom-field-

**Comment by burhangul** [comment]
okey thank you. so  there is no way..
