### ISSUE TITLE
Outgoing webhooks using /commands broken on 0.36.0

### ISSUE THREAD

**Issue by zippy1978** [RocketChat/Rocket.Chat#3906]
Your Rocket.Chat version: 0.36.0

Since upgrade from 0.35.0 to 0.36.0 : Outgoing webhooks seem to be broken.

I have a GifRocket /gif command installed, however when I type **/gif test** in a channel, I get a reply from **rocketbot** (used to be rocket.cat) saying : **No such command: `/gif**

**Comment by jlgore** [comment]
I'm also seeing this w/GifRocket.

**Comment by asthomasdk** [comment]
same here on our internally hosted version.

**Comment by JorisVanEijden** [comment]
Webhooks are fine, it's just that anything starting with a slash is considered to be a rocket.chat command, such as /invite or /join
@see PR #3698 and issue #3877

**Comment by zippy1978** [comment]
OK, thanks
I modified my trigger workds (removed the slash) and now I can use GifRocket again with **gif _something_**

Thanks.

**Comment by geekgonecrazy** [comment]
I've opened #4360 that adds a setting to allow sending of unrecognized slash commands to restore this functionality.
