### ISSUE TITLE
CORS broken: OPTIONS requests returns 500 Internal Server Error

### ISSUE THREAD

**Issue by tchap** [RocketChat/Rocket.Chat#3909]
Your Rocket.Chat version: 0.35.0

Anyway, I am trying to make an API call from the browser. It sends an `OPTIONS` request before `POST` to `/api/logon` to check CORS. The thing is, I am getting `500 Internal Server Error` on this `OPTIONS` request, which is rendering Rocket Chat impossible to access from the browser.

**Comment by tchap** [comment]
Hmm, perhaps the admins need to enable `rocketchat:cors` somehow?

**Comment by tchap** [comment]
In any case, the server should not return `500 Internal Server Error`.

**Comment by k0nsl** [comment]
What exactly does the API call look like?

**Comment by tchap** [comment]
```javascript
logon(username: string, password: string) : Observable<Credentials> {
  const url = `${BASE_URL}/api/login`;

  const headers = new Headers({
    'Content-Type': 'x-www-form-urlencoded'
  });

  const body = encodeURIComponent(`user=${username}&password=${password}`).replace('%20', '+');

  // Send the POST request.
```

But the call that is failing really is `OPTIONS` that the browser sends before this request. This request is not even being sent, so not sure why it is important...

**Comment by Jack-Collins** [comment]
I am having this same issue.

**Comment by graywolf336** [comment]
Any errors happening in the logs? If so, can you paste them?

**Comment by geekgonecrazy** [comment]
Please let us know if you need any more help on this.

**Comment by huynhquocmy** [comment]
@geekgonecrazy I got the same error, even though after enabled Cors on Adminitratior panel, the error still happen, please help!!!

**Comment by jfcloutier** [comment]
Where does one enable CORS on the Administration panel. I can't find it.

**Comment by PalakjainJain** [comment]
I am also having this same issue

**Comment by toelapiut** [comment]
> Where does one enable CORS on the Administration panel. I can't find it.

administration > general > REST API
