### ISSUE TITLE
Exception in queued task: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by asthomasdk** [RocketChat/Rocket.Chat#3910]
Your Rocket.Chat version: 0.36

We are running Rocket.Chat from Docker containers. I noticed that every time we start up a server, the we get the following in the logs: 

Updating process.env.MAIL_URL 
I20160803-19:35:53.251(0) ufs: store created at  
I20160803-19:35:55.368(0) (migrations.js:114) Migrations: Not migrating, already at version 55
I20160803-19:35:56.318(0) Exception in queued task: RangeError: Maximum call stack size exceeded 
I20160803-19:35:56.724(0) Updating process.env.MAIL_URL 
I20160803-19:36:10.424(0) Exception in queued task: RangeError: Maximum call stack size exceeded

Is the RangeError something we should be worrying about? If it is - is there something we should be adjusting? 

Let me know if you need any details about the setup.

**Comment by waley1975** [comment]
I have the same question.

**Comment by geekgonecrazy** [comment]
do you still see this with recent releases?  Is this with MAIL_URL set or not set?

**Comment by TwizzyDizzy** [comment]
I see this on 0.56.0.

    Mai 31 14:39:55 chat01 RocketChat[11928]: Updating process.env.MAIL_URL
    Jun 19 12:04:01 chat01 RocketChat[11928]: Exception in callback of async function: RangeError: Maximum call stack size exceeded
    Jun 19 12:04:01 chat01 RocketChat[11928]: [Mon Jun 19 2017 12:04:01 GMT+0200 (CEST)] ERROR RangeError: Maximum call stack size exceeded

If I can be of further assistance, don't hesitate to ask. :)

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Ok so this is actually happening on immediately as soon as you start it up?  Are you also running in docker?

**Comment by TwizzyDizzy** [comment]
Nope, as you can see above: The server started on Mai 31st, the Exception happened on June 19th.

I'm not running in Docker, I'm running Rocket.Chat as systemd unit under Oracle Enterprise Linux 7 (=RHEL7).

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Some task is causing maximum call stack to be exceeded, but the log isn't helpful.  If you happen to see this error directly related to some action on the server please feel free to open a new bug or we can re-open this one with those details.  As of now though there isn't really anything for us to act on.
