### ISSUE TITLE
Rest API programming

### ISSUE THREAD

**Issue by Jack-Collins** [RocketChat/Rocket.Chat#3916]
I would like to write a job which uses the Rest API to do various tasks creating/deleting channels but have only managed to get cURL working from the cmd and I don't fancy writing a bash file. Is there a way to work with the API in a programming language like Java or Python?

Thanks,

**Comment by Jack-Collins** [comment]
Never mind , found a decent node client https://github.com/qeesung/rocketchat-node

**Comment by geekgonecrazy** [comment]
@Jack-Collins thanks for posting that!  We were unaware of this cool little wrapper. 👍
