### ISSUE TITLE
weird edge case when RC left open for a very long time

### ISSUE THREAD

**Issue by jadeqwang** [RocketChat/Rocket.Chat#3920]
Your Rocket.Chat version: (latest on Sandstorm Oasis as of yesterday)

Left my Rocket.Chat open in the background like I always do. A while later, it prompts me to register a username. I choose my usual, and it says I can't have it:

![image](https://cloud.githubusercontent.com/assets/1584904/17347545/56140d8c-58c5-11e6-8be1-8afde4749ad7.png)

After I take a screenshot, walk away to make tea, come back, it has started trying to fix itself (channels loaded on the sidebar, main chat area showing the red loading rocket / 'spinner'). The rocket spinner stays for a long time (possibly indefinitely, but I only waited about a minute).

Eventually, when I navigate to a channel (#general), everything went back to normal. (Not sure how to repro.)

**Comment by engelgabriel** [comment]
HI @jadeqwang is this still an issue?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates
