### ISSUE TITLE
Rooms appearing twice in sidebar

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#3925]
Issue occurs in 0.36.0 and 0.35.0

This issue was present in 0.35.0 with bot conversations. The sidebar room menu item for DMs with a Hubot would appear twice. Now in 0.36.0 it happens with public rooms too (regardless if there's a bot in the room).

Could this be an unclean data migration issue? My instance has changed from master .33 to #develop branch to .35 and .36. Is anyone else getting this?

**Comment by engelgabriel** [comment]
@timkinnane Once a room becomes duplicated, it is always duplicated even after a browser refresh? Just trying to figure out if this is a cache issue or a DB issue.

**Comment by timkinnane** [comment]
@engelgabriel They're always duplicated, even after complete rebuild, from as soon as I change version. If I roll back, the duplicates go away.

It started happening in development branch post 0.35.0 with bot DMs, but since 0.36.0 now its channels too. Actually channels appear in triplicate. Doesn't seem to happen to private channels or channels created since the migration.

e.g. attached.

<img width="257" alt="screenshot 2016-08-07 15 17 58" src="https://cloud.githubusercontent.com/assets/1774379/17460616/d4b6caf8-5cb2-11e6-9d34-59f4b66dc033.png">

**Comment by engelgabriel** [comment]
@rodrigok Any ideas on how to debug this?

**Comment by rodrigok** [comment]
@timkinnane can you clear the data cache and refresh your browser to see if the duplicates persists?

To clear the data cache you need to open your browser's developer tools and execute:
`RocketChat.CachedCollectionManager.clearAllCache()`

**Comment by timkinnane** [comment]
Thanks @rodrigok that worked... kind of...

It cleared the duplicate rooms, but it also removed ALL direct messages and private groups from the rooms menu/sidebar. It was easy enough for me to re-add them, but this could be quite a jarring solution for users.

Worse than that though, there was only one private room I was in before clearing cache, but now it's gone from the menu and I can't get it back. I can choose it from "More channels" but it doesn't stay in the menu. I can only view it, can't post. There's actually no message box displaying when I'm in the room, even though I'm an admin and room member. I can still add and remove users.

Wouldn't recommend that approach though. Any other ideas?
Should there be some cache cleanup action tied to version migrations?

**Comment by timkinnane** [comment]
For what its worth, this is on my local dev versions. I'm not breaking anything live, so no panic, but would like to find a solution before upgrading production instances beyond 0.35.0.

Hopefully someone else can confirm they're having this issue.

Thanks for your assistance as always :D

**Comment by timkinnane** [comment]
I also tried rolling back to 0.35.0 after the cache clear to see if that would restore access to the private room, but now I'm getting `Error: [Can't find migration version 56]` and can't build.

**Comment by KirbySSmith** [comment]
Saw the same issue with duplicate rooms. Traced it to the cachedCollection for subscriptions not being cleared on logout. If User A logs out and User B logs, User B would see User A's + User B's subscriptions. This issue was fixed in version 0.37 by pull request #4009.
