### ISSUE TITLE
Room Info Mail Messages: Select all messages redirecting to chat home page.

### ISSUE THREAD

**Issue by th3fall3n0n3** [RocketChat/Rocket.Chat#3928]
Your Rocket.Chat version: 0.36.0

While clicking on "select all" link in Mail Room messages it redirects to Chat home page. 

Select function works fine, for example if link is pressed with "Shift" new window opens and in old one all messages are selected. 

Can be fixed by adding e.preventDefault() to the beginning of the .select-all click function.

**Comment by MartinSchoeler** [comment]
Hey @th3fall3n0n3 , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
