### ISSUE TITLE
Rocket.Chat on Sandstorm takes 20 seconds to start

### ISSUE THREAD

**Issue by kentonv** [RocketChat/Rocket.Chat#3933]
Your Rocket.Chat version: 0.36.1

It seems Rocket.Chat first-time startup has gotten a lot slower lately. I think it's mainly on staratup of a brand-new instance, which does a bunch of database stuff, but it's disappointing for people trying to demo Rocket.Chat on Sandstorm that they have to wait a while.

Maybe there is some low-hanging fruit that could be optimized?

**Comment by engelgabriel** [comment]
@kentonv this https://github.com/RocketChat/Rocket.Chat/pull/5372 will probably help

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates. If the issue happens again, please reopen this. Thanks!

**Comment by kentonv** [comment]
This issue is still very much a problem. Rocket.Chat takes ~40s to load on Sandstorm. You can try it here: https://oasis.sandstorm.io/appdemo/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0

I can't re-open issues as I am not a project member.

**Comment by masonk** [comment]
I just tried a hard reload of a Rocket.Chat grain on a slow connection. 102 HTTP requests, 18.85MB compressed bytes, and 3.51 minutes later - I had a chat window open.

Can someone explain, in broad strokes, the critical path of events from reload to having a chat window?  And, like @kentonv asked before - does anyone have theories about low hanging fruits? I'm considering diving in and trying to make this better myself.
