### ISSUE TITLE
Webhook integration doesn't work behind reverse proxy.

### ISSUE THREAD

**Issue by takavfx** [RocketChat/Rocket.Chat#3934]
Your Rocket.Chat version: (0.36.0)

Hi, I need help for webhook integration. I think the problem is similar to #3073  .
Because the directory is the same level as old "file-upload" directory, we are not allowed to access the level behind reverse proxy.
Is that quickly fixable?

Ex.
- ~/rocket/channel/general ("general" channel as default)
- ~/hooks/xxxxxx (Currently, not accessible)
- ~/rokcet/hooks/xxxxxx (Should be)

**Comment by takavfx** [comment]
Hi I still need its quick fix.

Is that just because of this part? : https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/client/views/integrationsIncoming.coffee#L21-L24

Could it be fix by changing like this? : https://github.com/takavfx/Rocket.Chat/blob/incomingWebhook-behind-reverseProxy/packages/rocketchat-integrations/client/views/integrationsIncoming.coffee#L21-L27
```
if Meteor.settings.public.sandstorm or url.match /^(https?:)?\/\//i
    data.url = Meteor.absoluteUrl("hooks/#{data._id}/#{data.token}")
else
    data.url = Meteor.absoluteUrl().replace(/\/$/, '') + __meteor_runtime_config__.ROOT_URL_PATH_PREFIX + "hooks/#{data._id}/#{data.token}"
data.completeToken = "#{data._id}/#{data.token}"
Template.instance().record.set data
return data
```

**Comment by takavfx** [comment]
OK, this is not only the issue.

I tested and the result was failed: the settings are visually reset on the incoming webhook's view.

**Comment by takavfx** [comment]
Hi

I think this problem is solved by changing reverse proxy settings, by altering base url. I'm sorry to have caused you trouble.

Thanks.

**Comment by frdmn** [comment]
Glad you sorted it out👍
