### ISSUE TITLE
Publish online status

### ISSUE THREAD

**Issue by patrickpl** [RocketChat/Rocket.Chat#3936]
We have a confluence up and running here as a wiki that is usable also for business people. Most of our information about projects, development, ... is in this place. Probably most of you have something similar. Since we also have the information about each of the team member there we would like to see the online status of the team members - for example in a little iframe.

I've written a short story, some notes and I also attached two pictures how I could imagine how it should look like.

Please let me know what you thing :-)

**Story:**
As an user of a Rocket.Chat I want to publish my online status, so that other people can see if I'm online.

**Notes:**
- It is possible to get by http a picture/button, that shows if the user is online (eg. https://demo.rocket.chat/user/[username]/onlinePresencePicture)
- It is possible to get by http a text, that explains if the user is online (eg. https://demo.rocket.chat/user/[username]/onlinePresenceText)
- These two URLs are reachable without any authentication
- The user can decideif he wants to publish the online status. The options are: 
  - publish
  - don't publish
  - system default]
- The administrator can configure the system default:
  - publish
  - don't publish
- On the user settings there is a small html snipped that explains how to integrate it into a different website

**Extra (but super cool) Feature:**
- If you click on the online presence button you go directly to a one-to-one chat with the user - no matter if he is online or not

**How it could look like on a website:**

![rocketchat-teamcontact](https://cloud.githubusercontent.com/assets/1948076/17456821/5001c00c-5be4-11e6-9e92-f36dab125df4.png)

**Different buttons:**
![rocketchat-buttons](https://cloud.githubusercontent.com/assets/1948076/17456692/e7d461a4-5be0-11e6-9d5c-59e0075ef8f7.png)

**Comment by graywolf336** [comment]
@patrickpl This has been implemented, I never realized this issue existed. The documentation for this is located: https://rocket.chat/docs/developer-guides/rest-api/users/getpresence#user-get-presence

**Comment by patrickpl** [comment]
That's great. Thank you @graywolf336

**Comment by graywolf336** [comment]
If you guys build a service which enables those buttons, let me know as I'd be Interested in seeing it 👍
