### ISSUE TITLE
Live Chat: "Display name" instead of username

### ISSUE THREAD

**Issue by infinitnet** [RocketChat/Rocket.Chat#3938]
Hi,

so after the latest update I want to try the live chat part in production. However, there is one thing that bothers me: it displays the usernames of agents instead of their display names. Is there a way to change that?

Also, are there any plans to add visitor monitoring (current page, IP, country, # of visits, previous chats) and shortcuts for canned messages?

**Comment by sampaiodiego** [comment]
do you mean you like to have the display names on the livechat widget?

this is how it looks now:
![image](https://cloud.githubusercontent.com/assets/8591547/23141288/d6a3bc2c-f794-11e6-9c88-12f166afed27.png)

> Also, are there any plans to add visitor monitoring (current page, IP, country, # of visits, previous chats) and shortcuts for canned messages?

yes.. we already have the page history, IPs and previous chats.. shortcuts are planned..

**Comment by jeffrapp** [comment]
Also interested in this feature.  Ideally, we would be able to have the agents set a custom "display name" for presentation in the livechat widget.  Our primary concern is exposing the entire name of our agents (we're integrated with LDAP) to visitors.

**Comment by sampaiodiego** [comment]
closing since we're display real names

**Comment by assadvirgo** [comment]
@sampaiodiego Do we have a canned messages feature? I don't see it anywhere. Would appricate if you guide me if there is already one.
