### ISSUE TITLE
After Updating to 0.36.0 form 0.35.0, on removing existing user 400 error appears.

### ISSUE THREAD

**Issue by usmanasif** [RocketChat/Rocket.Chat#3941]
Your Rocket.Chat version: (0.36.0)
Thanks in advance

<a href='https://postimg.org/image/rja0fixlx/' target='_blank'><img src='https://s10.postimg.org/pepnefvzd/rocketchat_400.jpg' border='0' alt='rocketchat_400'/><br /><a target='_blank' href='https://postimage.org/'></a><br /><br />

**Comment by MartinSchoeler** [comment]
@usmanasif is this issue still happening?

**Comment by Rohlik** [comment]
I think this should be closed.

**Comment by MartinSchoeler** [comment]
@usmanasif I will close this issue, if the problem persists, please reopen this. Thanks!
