### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by erezson** [RocketChat/Rocket.Chat#3942]
I use 0.36.0 which I just installed and not upgraded.

I wanted to add a Googla Analytics code but I understand that you allow only Google Tag Manager. So I added my Google Tag Manager but then I found out that you're calling a URL which doesn't exist: http://www.googletagmanager.com/gtm.js 

The correct url should be:
www.googletagmanager.com/ns.html?id=GTM-XXX

**Comment by engelgabriel** [comment]
Fixed, you can now just add on the admin panel.
