### ISSUE TITLE
Private groups in 0.36.0

### ISSUE THREAD

**Issue by kshitijkamat** [RocketChat/Rocket.Chat#3943]
Your Rocket.Chat version: 0.36.0

The earlier version had the option of a separate private groups. The 0.36.0 merged the private groups into channels which can be changed from the individual user setting. 

It would be great if you can provide an option for the admin to enable / disable separate private groups
instead of clubbing them with the channels. 

Request that the private groups feature be a site configuration as well as user configuration.

The separate private groups feature was really a nice one and would love to have it back.

Thanks.

**Comment by graywolf336** [comment]
This is possible with the latest version: `Administration -> Layout -> User Interface`

![image](https://cloud.githubusercontent.com/assets/850391/18066497/4d0a02b6-6dfe-11e6-8b2b-253c49cc9fa6.png)
