### ISSUE TITLE
Files downloads broken in windows app because of forced authentication through browser.

### ISSUE THREAD

**Issue by twhiting** [RocketChat/Rocket.Chat#3947]
The latest update seems to have changed to way the Windows app authenticates file downloads.  If I upload a file through the windows app then choose to download it, I get a _File not found_ error page in my browser. 

![ptc](https://cloud.githubusercontent.com/assets/10718586/17494853/c2b2afae-5d73-11e6-9f5c-a81e6d13eb47.JPG)

Seeing this setting I realized that the windows app is forcing authentication through the browser and not the Windows app anymore.  So logging in to my site via the browser allows authentication and downloads work again in the Windows app.

Can we get this fixed so browser login isn't required to download files?

**Comment by MartinSchoeler** [comment]
Please reopen this issue in the [here](https://github.com/RocketChat/Rocket.Chat.Electron) . Thanks!

**Comment by jdoose** [comment]
No need to reopen, was fixed.
Works in 2.10.5
