### ISSUE TITLE
Cannot run Rocket Chat client on a x86 system

### ISSUE THREAD

**Issue by leandroqm** [RocketChat/Rocket.Chat#3949]
I can't run Rocket Chat Electron App (client) on a 32 bits system for some reason.
System is Windows 7 32 bits on an old Dell Opteron 380 with 4GB of RAM.

![selecao_001](https://cloud.githubusercontent.com/assets/2154464/17496913/bb253ee2-5d95-11e6-8919-45a0e8f23315.png)
![selecao_002](https://cloud.githubusercontent.com/assets/2154464/17496941/d725edc6-5d95-11e6-92cf-fd2db2b38f95.png)

For some reason, Electron thinks the system is x64 and tries to run it as a x64 app, which it is not.

The Client version is the last one (1.3.1), downloaded from this link: https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.1/rocketchat-v1.3.1-win32-x64.exe.
Also tried downloading from another link, but I think the files are identical ( https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.1/rocketchat-v1.3.1-win32-x64.exe).

**Comment by xasx** [comment]
There's just no 32-bit build for 1.3.1.

Latest 32-bit binary can be found here (1.3.0):
https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/1.3.0/rocketchat-v1.3.0-win32-ia32.exe

There were some issues with the ia32 version: RocketChat/Rocket.Chat.Electron#191

Please also head over to this project for reporting issues with the client.

**Comment by leandroqm** [comment]
Yes, I have a comment on this link from May 23rd, but there are still no answers.
TBH, I haven't realized I wasn't in the Rocket.Chat.Electron project when I posted the issue, I am sorry for this. :-)
