### ISSUE TITLE
How to login with LDAP

### ISSUE THREAD

**Issue by fantashi** [RocketChat/Rocket.Chat#395]
Do you have any tutorial for LDAP login?

**Comment by sampaiodiego** [comment]
@marceloschmidt can you help @fantashi please?

**Comment by marceloschmidt** [comment]
@fantashi LDAP is still on its baby-steps. We made it to simply connect to a given host and we haven't implemented it's login schema.

To try it out, you have to modify the following settings to your needs: 

LDAP_DN
LDAP_Port
LDAP_Url

These settings can be modified by accessing /settings on your instance (if you are admin) or directly modifying it on database collection rocketchat_settings.

Then, after this is setup, you can login by firing up your developer console and typing `Meteor.loginWithLDAP('username', 'password');`
