### ISSUE TITLE
Google oAuth login conflict with Admin account

### ISSUE THREAD

**Issue by mynameiskeo** [RocketChat/Rocket.Chat#3950]
Rocket.Chat version: lasted, one-click deploy on Heroku,

once the Google oAuth configured, i log out from admin account (created from mygmail@gmail.com)
to try the Google login, using the same email address, it does not work and create a conflict.

I can't acces the admin account anymore (Internal server error), or try to login normally (password error)

How can we handle to fix this ? Can't reset admin password

**Comment by tgxn** [comment]
This is a duplicate for Issue #3980

**Comment by mynameiskeo** [comment]
Same here. can't fix except editing in MongoDB directy ;)

**Comment by geekgonecrazy** [comment]
Solution to this one would be goto My Account-> Avatar and click on link with Google.  This will link your existing account with your Google account, and you will be able to login using google next time.
