### ISSUE TITLE
0.35.0 -> 0.36.0 Changes

### ISSUE THREAD

**Issue by Silvenga** [RocketChat/Rocket.Chat#3951]
It appears that the upgrade from 0.35 to 0.36 has seen some major breaking changes, e.g. Hubot is broken:

https://github.com/RocketChat/hubot-rocketchat/issues/142
https://github.com/RocketChat/hubot-rocketchat/issues/149
https://github.com/Silvenga/Rocket.Chat.Net/issues/2

Is there a known API upgrade path for those who do not, or cannot use the Javascript libraries?

**Comment by Sing-Li** [comment]
Please follow for resolution: 

https://github.com/RocketChat/hubot-rocketchat/issues/142

**Comment by TheReal1604** [comment]
@Sing-Li @MartinSchoeler I think this issue could be closed. RocketChat/hubot-rocketchat#142 resolves the issue.

**Comment by Silvenga** [comment]
I don't know. What I was really hoping for is API upgrade paths for non-JS libraries. Lot's of breaking changes without warning or an upgrade path really sucks for other open source projects. Since many of my tests are broken I
