### ISSUE TITLE
Jitsi.Meet video chat not working

### ISSUE THREAD

**Issue by nadirlc** [RocketChat/Rocket.Chat#3952]
Your Rocket.Chat version: 0.36.0

I am getting an error when I click on video chat button in direct message mode. I am using Chromium browser version: 52.0 on Debian Jessie. It works fine in Firefox

When I hit the video chat button, the webcam light turns on, but the video chat section remains black. Our installation uses https and a /chat sub directory. The url is https://exergoit.se/chat/.

We get the same error when trying to start a video chat session on  https://demo.rocket.chat. I tried to start video chat session in direct message mode. The webcam light came up but the video chat section remained black. Please see following javascript error:
[exergoit.se-1470734986943.txt](https://github.com/RocketChat/Rocket.Chat/files/408612/exergoit.se-1470734986943.txt)

Following are screenshots of the error:
![screenshot from 2016-08-09 14 24 05](https://cloud.githubusercontent.com/assets/20923812/17511703/9ebbf310-5e3d-11e6-8155-6b5bbae0fffd.png)
![screenshot from 2016-08-09 14 24 39](https://cloud.githubusercontent.com/assets/20923812/17511702/9ebac49a-5e3d-11e6-97fc-6f3b219caf88.png)

If I open the video chat section frame in a new window, then it works.

Thanks

**Comment by tastle73** [comment]
Me too on this.

**Comment by MartinSchoeler** [comment]
@nadirlc is this still happening in the latest version ?

**Comment by nadirlc** [comment]
I checked on https://demo.rocket.chat/home and its still not working

**Comment by qazbob** [comment]
I've just installed it. I can confirm that the issue is still there in the last version (50.1)

**Comment by reetp** [comment]
@rocket-cat close

I'm going to close this due to a lack of activity.
Please test on the latest version before reopening or creating a new issue.

**Comment by DouglasMorandi** [comment]
Hello,

Try to configure Jitsi video to open in new window. (rocket.chat Administration  -> video conference -> Jitsi -> Always Open in New Window

**Comment by reetp** [comment]
> Try to configure Jitsi video to open in new window. (rocket.chat Administration -> video conference -> Jitsi -> Always Open in New Window

Not much point adding to a long closed bug.

Follow this to test on latest version.

If it is still an Issue then open a new one. Fill the bug template in correctly here:

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Add a cross reference to this Issue

**Comment by douglasmcqoy** [comment]
![image](https://user-images.githubusercontent.com/13311864/77231894-a6be2600-6b95-11ea-9923-c9700a2c687a.png)
Jitsi meet server i installed on digital ocean and configured to use for video calls on rocket chat has noise and echoes during calls and can upload video chat messages.
