### ISSUE TITLE
24h clock in info

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#3953]
When you select a user for more information the clock there is still in 12h am/pm system. In the admin panel you can change so the chat uses 24h clock instead but apparantly this one doesn't get affected. Kinda awkward to have two different time system for the users.
![image](https://cloud.githubusercontent.com/assets/17712562/17513077/3377d2b6-5e2b-11e6-9956-fcfcd3b0bced.png)

Hope this one can get a hotfix :)
//molle

**Comment by tgxn** [comment]
Submitted pull request to correct this one.
