### ISSUE TITLE
How get I access to tabs in sidebar?

### ISSUE THREAD

**Issue by Buzzele** [RocketChat/Rocket.Chat#3954]
Hi,

in my installation i dont find the html files and more directorys. I need access to the tabs in directory packages/rocketchat-ui-flextab/flex-tab/tabs/.

How can I change or add files to modify the right sidebar? I think I have to deploy completely new, is this right? In the install instructions hey linkes to the latest releases on https://rocket.chat. There are the files missing too :( 

But its really important for me to change files there. 

I hope, I get help.

Best regards Buzzele

**Comment by tgxn** [comment]
Hi @Buzzele, 

Can you help us out with some more details about the environment you're running in?

Things that may help us diagnose your issue:
- Version of Rocket.Chat
- What method you followed to install Rocket.Chat.
- If you're trying to add a new tab to the right tabBar, you can do it by creating a new package, there is an example of how the "Mentions" tab item works in it's package [here](https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-mentions-flextab).

**Comment by Buzzele** [comment]
Hi @tgxn ,

thanks for the your reply. I have installed Rocket.Chat with this instructions: https://www.digitalocean.com/community/tutorials/how-to-install-configure-and-deploy-rocket-chat-on-ubuntu-14-04.

My Rocket.Chat version is 0.30.

Yes, I am trying to add a new tab, but the example Mentions I cant find. I dont know, where to look. I searched all directorys for example MentionedMessage.coffee but I cant find. The directory  rocketchat-mentions-flextab I cant find too.

**Comment by tgxn** [comment]
To start out with, I'm not overly familiar with version 0.30.

If you're installed from the pre-compiled version (the one that guide instructs you to download) the files are going to be minified and ready for a production host. To modify the files, you need to get a copy of this source, and then you will be able to locate the files that i linked in my previous reply.

**Comment by Buzzele** [comment]
Hm, i supposed this :(

Is there a way to modify the source files and then compile by myself, so that I can use my own link insteed of rocket.chat/releases/latest to download all the stuff?

Or how can I install the chat, that I have access to all files?

**Comment by tgxn** [comment]
@Buzzele 

Yes you can download the Rocket.Chat repository from here (GitHub) and modify any of the files to your content.

You will need to have a few dependencies installed, such as Meteor and NPM.

To run the server in development mode, you can use `meteor` on it's own, or if you would like to package your version for production, you can run `meteor build .` and it will create you a deployable .tar.gz package.

I'd really only suggest this if you're serious about setting up a development instance, as it can be fairly in depth to get this all set up, depending on your technical background.

**Comment by Buzzele** [comment]
Thank you very much. Meteor build was what I were looking for.
