### ISSUE TITLE
File Uploads to S3 are Expiring

### ISSUE THREAD

**Issue by mistakevin** [RocketChat/Rocket.Chat#3956]
Your Rocket.Chat version: 0.36.0

File uploads to S3 are expiring, even after setting "Protect uploaded files" to False, (along with a server restart).

Possibly related issue #3083

<img width="1119" alt="screen shot 2016-08-09 at 10 14 26 am" src="https://cloud.githubusercontent.com/assets/4411115/17521763/29da2a4e-5e1a-11e6-8b1d-5d77691cf334.png">

<img width="762" alt="screen shot 2016-08-09 at 10 14 58 am" src="https://cloud.githubusercontent.com/assets/4411115/17521770/3259231e-5e1a-11e6-8886-4aee1bd35cdb.png">

**Comment by mistakevin** [comment]
Does this address the issue? https://github.com/RocketChat/Rocket.Chat/pull/3846 @iroes

**Comment by iroes** [comment]
Yep @mistakevin, this fixes it. But it's not deployed to master yet (I suppose it would be included on version 0.37.0). 
Your server time is more than a minute delayed, as was mine. Now the default time span (delay) for the links to expire is 2 minutes (it was 1 minute). If it is not enough, you'll be able to set it.

**Comment by engelgabriel** [comment]
Thanks @iroes for the PR, and @mistakevin let me know if that was the problem for you. 

Please reopen this issue if not.
