### ISSUE TITLE
Push Notifications enabling sound setting 

### ISSUE THREAD

**Issue by thetacobean** [RocketChat/Rocket.Chat#3959]
Your Rocket.Chat version: 0.36

I'm running the latest release of rocket.chat. For my use we really need message sound notifications on the mobile devices that are running the rocket.chat app. I am using Docker to run the rocket.chat server and we have a mix of iphone/android devices. As of now rocket.chat will only send a vibrate notification.

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
