### ISSUE TITLE
Enhancement: Display the name of the current chat on the web browser tab

### ISSUE THREAD

**Issue by andylytical** [RocketChat/Rocket.Chat#3960]
With multiple web browser tabs open, each in a different chat, would be nice to see the chat room name in each tab to allow quick selection of the tab.

**Comment by andylytical** [comment]
This is a relatively dumb idea ... with multiple browser tabs open, multiple notifications are sent, one per browser tab.  I don't see a good way around this.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
