### ISSUE TITLE
IFrame login does not work

### ISSUE THREAD

**Issue by Informatic** [RocketChat/Rocket.Chat#3964]
Your Rocket.Chat version: 0.36.0 (latest)

Seems like iframe login is not displayed in latest RocketChat version. (No request is issued to target server, and displayed /home page seems to only contain empty `div.tooltip` element)
When downgraded to 0.35.0 iframe page is displayed correctly.

Deployed in docker-compose as per https://rocket.chat/docs/installation/docker-containers/

**Comment by rodrigok** [comment]
@Informatic sorry about that, I just fixed the iFrame problem here https://github.com/RocketChat/Rocket.Chat/commit/f88a9fc92a74283a2315d0c6e716e9628539e036

We will do a new release today
