### ISSUE TITLE
Firefox not working, but works in Chrome for popout box

### ISSUE THREAD

**Issue by jwaldron92** [RocketChat/Rocket.Chat#3969]
1. Use the chat properly on Chrome on website woofwarrior.com
2. Open web page in firefox and pop up box isn't "visible"
3. Inspect element and nothing changes

**Comment by MartinSchoeler** [comment]
Hey thanks for the report, but i opened you site through firefox and the pop up worked just fine, try updating your browser to a newer version or ask other people if their are having the same issue.

**Comment by jwaldron92** [comment]
I tried and it wasn't working still

**Comment by geekgonecrazy** [comment]
If this is still happening please disable any plugins you have installed and make sure you are using a recent version of Firefox.
