### ISSUE TITLE
don't email users when they are highlighted in a private channel they are not in

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#3972]
Right now a user gets a "you are highlighted in channel X" when they are @user mentioned, even when they're not in the private channel the mention happens in. That's not good.

**Comment by sinteur** [comment]
0.36.0

**Comment by MartinSchoeler** [comment]
@sinteur  I'm trying to replicate this bug with no success, could you give more information in how is this happening?
