### ISSUE TITLE
Jitsi Meet Video Chat not working in sub domain configuration

### ISSUE THREAD

**Issue by nadirlc** [RocketChat/Rocket.Chat#3973]
Your Rocket.Chat version: 0.36.0

Hello,

For your information we are running rocket chat in sub domain configuration. In order to get the Jitsi.Meet video chat to work we had to add following rules to apache virtual host configuration. We added these rules in addition to the rules given on https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx#running-behind-an-apache-ssl-reverse-proxy:

```
ProxyPass /packages http://localhost:1000/chat/packages
ProxyPassReverse /packages http://localhost:1000/chat/packages
ProxyPass /assets http://localhost:1000/chat/assets
ProxyPassReverse /assets http://localhost:1000/chat/assets
```

Thanks,
Nadir Latif

**Comment by karamata** [comment]
I run RC on my subdomain and it work perfect, but only has one problem. it only run on firefox, and chrome it didn't work. I think chrome has intercept my self cert

**Comment by geekgonecrazy** [comment]
@nadirlc the rules you added were rules you need for Rocket.Chat it's self.  Not jitsi specific. :)  Sounds like this is working for you.  Closing
