### ISSUE TITLE
Meteor-tool update hangs forever

### ISSUE THREAD

**Issue by jhj0072000** [RocketChat/Rocket.Chat#3975]
Is anyone having an issue with meteor-tool update? When I try to run it, it starts downloading meteor-tool@1.1.10 and when it reaches 100% it just hangs forever. I left it on overnight but still no luck. I know there are lots of questions about this online but nothing seems to work for me so far. Any ideas?

Info: OX X Yosemite

![screen shot 2016-08-10 at 11 33 24](https://cloud.githubusercontent.com/assets/9278558/17563859/81ec0f52-5eee-11e6-94a3-362e7a4e0c0b.png)

**Comment by mbanusic** [comment]
This is a meteor bug, see [here](https://github.com/meteor/meteor/issues/6960).

Try this [fix](http://stackoverflow.com/a/38034898/626640).
