### ISSUE TITLE
Collapsable Pinned Content

### ISSUE THREAD

**Issue by cpitman** [RocketChat/Rocket.Chat#3977]
Your Rocket.Chat version: 0.36

If you pin a message with expandable content, then look in the pinned messages, you cannot collapse/expand the content within the pinned message window. Even stranger, trying to expand or collapse the pinned version changes whether the _original in the chat window_ is expanded or collapsed.

**Comment by Flipez** [comment]
This is still a problem in 0.52.0 and very annoying

**Comment by TwizzyDizzy** [comment]
Still in 0.61.0

**Comment by reetp** [comment]
Anyone confirm if this is still there on latest (currently 0.71.x)?

**Comment by TwizzyDizzy** [comment]
Yep, still persists.

Cheers
Thomas

**Comment by reetp** [comment]
Bump - still exists on 0.74.2

You can open the image, but not collapse it.
