### ISSUE TITLE
Linking OAuth Accounts on non-verified email.

### ISSUE THREAD

**Issue by tgxn** [RocketChat/Rocket.Chat#3980]
Your Rocket.Chat version: develop (0.36.0)

How to reproduce:
- Deploy fresh RC instance.
- Login and create main admin account.
- Enable Google OAuth.
- Login with Google account linked to email that the initial admin user registered with.

Expected Issue:
- Login with UN/PW fails: "User not found or incorrect password"
- Login with Google Fails: "Internal Server Error"

DB Seems to indicate that the when the Google Auth happens, accounts seem to be linked successfully.
"requirePasswordChange" : true,
"requirePasswordChangeReason" : "This_email_has_already_been_used_and_has_not_been_verified__Please_change_your_password"

I assume that what is happening is that when the OAuth handler is being called, it is noticing that my initial admin account's email address never got verified, and therefore I cannot login to my account.

Deleting my account, recreating and verifying the email address prior to linking Google account works.
I would assume that manually verifying your account would resolve this issue, also.

**Comment by geekgonecrazy** [comment]
No other reports, closing.  Please let us know if still happening in newest release
