### ISSUE TITLE
Disable Channel Preview + Disable Invisible User + Kick from Room after X mins??

### ISSUE THREAD

**Issue by Dorm2016** [RocketChat/Rocket.Chat#3983]
Your Rocket.Chat version: 0.35.0

1. Was wondering if its possible to disable the Room Preview function, so that you only see what is inside the channel/room if you join.

2. I would also like to disable Invisible as a Status for anyone that isn't part of a specific moderator/admin permissions list. Basically to avoid people ghosting. 

3. Is there a way to kick people from channels and rooms after X minutes of inactivity?

Any help would be appreciated.

**Comment by graywolf336** [comment]
1. This was enabled via #4127.

The other two are not currently not possible, please open a new issue for each one individually so it can be tracked by itself.
