### ISSUE TITLE
Invalid scope when authenticating with Gitlab

### ISSUE THREAD

**Issue by pavankumarkatakam** [RocketChat/Rocket.Chat#3987]
Your Rocket.Chat version: latest (0.36.0)
![selection_003](https://cloud.githubusercontent.com/assets/6078669/17614658/8e085de8-6085-11e6-9439-c27beb3ab6d3.png)

Invalid scope problem.

**Comment by mkurzeja** [comment]
We have the same issue with Rocket.Chat 0.37.0

**Comment by uyson** [comment]
+1

**Comment by Shelnutt2** [comment]
This is do to commit 2b90787b481cfc37941f343e5fae2ad802484740 . If you remove the &scope=openid, gitlab will authenticate.
