### ISSUE TITLE
I'm noticing on the desktop that in rocket oftentimes I can't get a channel to unhighlight after I've gotten up to date on the messages there

### ISSUE THREAD

**Issue by kashifnawaz123** [RocketChat/Rocket.Chat#3988]
Your Rocket.Chat version: (0.36.0)
I'm noticing on the desktop that in rocket oftentimes I can't get a channel to unhighlight after I've gotten up to date on the messages there. It's annoying because I keep thinking I'm missing a new conversation when its just the highlight not going away

**Comment by skizzors** [comment]
+1 this, I have issues with rocket.chat updating channels as being read on app and web versions.

**Comment by kashifnawaz123** [comment]
MartinSchoeler , Could you or anyone from Rocket team can let us know when this would be fixed , its bit annoying behavior, and i feel like i missed something important message but nothing is there to read

**Comment by MartinSchoeler** [comment]
@kashifnawaz123 are you still getting this bug on the latest version

**Comment by kashifnawaz123** [comment]
Checking

**Comment by MartinSchoeler** [comment]
Hey @kashifnawaz123 , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
