### ISSUE TITLE
Incoming WebHook Integrations to post to multiple channels

### ISSUE THREAD

**Issue by invious** [RocketChat/Rocket.Chat#3989]
Use case for this, a Git hook posting in a dedicated git notifications channel, as well as a channel for discussing the integration of two repos.

**Comment by IQ2022** [comment]
Also to have an email forward messages to a channel would be a nice idea

**Comment by vetash** [comment]
Why not use custom script for this?

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this one out.  This is possible, it will get even easier with Rocket.Chat apps.
