### ISSUE TITLE
Filter link previews for given url

### ISSUE THREAD

**Issue by rogerpfaff** [RocketChat/Rocket.Chat#3990]
Your Rocket.Chat version: 0.36

It would be great to have a filter option to inline previews because we discovered that the link preview will invalidate one time password links. In our case we noted this on Drupal Installations where you can get a one time login link. If you post this to the chat the url is called and the link is invalidated.

Is something like this already possible? Where to look into if not?

**Comment by FibreFoX** [comment]
Have you tried to list that domain into the "embed ignored hosts" inside Administration > Message ?
