### ISSUE TITLE
Do not ask for location on load

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#3991]
The location share feature should only ask for permission to use the location when pushing the location share button, and not when the page loads.
This way the user knows and understands what it will be used for. At this moment everyone will just push 'no' when permission is asked because they don't know what it will be used for.
Pressing 'no' will also result in the location share button being hidden, which should not be happening in my opinion, it should be shown at all times unless the administrator disables it. When pushing the button, permission needs to be asked if necessary.

Your Rocket.Chat version: 0762aea

**Comment by tgxn** [comment]
Yeah, this is the issue I ran into because we do an initial check to see if the location API is available on load (so we know if we should show the button or not)

We could just show it by default if it is enabled in administration, and popup an error if there was an issue obtaining the user's location?

**Comment by geekgonecrazy** [comment]
@tgxn absolutely agree.  Asking on page load I tend to always block regardless of the website.  Only when a website prompts when I tap a location related function do I allow it. 👍

**Comment by TwizzyDizzy** [comment]
Still relevant in 0.62.0

Cheers
Thomas

**Comment by Krinkle** [comment]
Rocket.Chat should not be triggering the user's browser to share their physical location. I have no idea what this feature is even for, but I imagine for 99% of users it is never relevant.

Getting this prompt upon the first experience with https://open.rocket.chat/ is certainly a big red flag for anyone evaluating Rocket.Chat for their company.
