### ISSUE TITLE
Android app is not displaying the UI properly

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat#3997]
Android app is not displaying the UI properly. This is the screenshot I got

![smartselectimage_2016-08-14-23-38-33](https://cloud.githubusercontent.com/assets/1788360/17650194/1819f122-627a-11e6-9cb8-cd5650ac7e0c.png)

**Comment by tgxn** [comment]
It appears that your styles aren't loading properly, I guess there's a few causes to why this could happen, maybe we can start with some more details regarding how your instance is configured?

Are you running your own server?
How did you deploy it?
Have you configured the instance URL correctly?

**Comment by ccfiel** [comment]
@tgxn I am just using the https://demo.rocket.chat default link in the android app.

**Comment by tgxn** [comment]
Hmm, That's bizarre then.

Have you tried loading it in your mobile browser? Do the images/assets load then?
I just tested it on the latest app version on demo, and I'm not able to reproduce this issue.

What mobile platform are you running?

**Comment by ccfiel** [comment]
@tgxn yes I tried loading it in the mobile browser It was ok, images/assets load properly. I even tried to reinstall the app but still problem I got.

**Comment by MartinSchoeler** [comment]
@ccfiel is this still a issue on the latest version?

**Comment by ccfiel** [comment]
This is now ok.  Thanks!

**Comment by jfreakazoid** [comment]
Hi there. Sorry to open this thread again but recently I installed my own rocket.chat server and in the web browser everything is working pretty well but in the Android app the UI is not loading properly exactly in the same way that is reported here. Somebody can give me a clue about how can I solve this issue? 

I have ssl installed and I'm using nginx as a reverse proxy. 

Thank you in advance.

Cheers
