### ISSUE TITLE
Proposal: add a thumbnail picture to the channels

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#3998]
Like in Snapchat, it would be nice to have the possibility of adding a photo thumbnails on the channels

**Comment by tgxn** [comment]
I like the sound of this!
I believe TG has the same config option so you can have an image per channel.

Would be nice to see it under channel info, and possible in the header-bar.

**Comment by tgxn** [comment]
Duplicate Issue found: Issue #3582

**Comment by graywolf336** [comment]
Closing as it is a duplicate of #3582
