### ISSUE TITLE
Email not possible to translate

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#4000]
Your Rocket.Chat version: (make sure you are running the latest) 0,36
I am trying to localize the rocket.chat to Swedish.
But there are some mails that is not possible to change..

In the file /bundle/programs/server/packages/ accounts-password.js there are some hard coded phrases.

How should i update these?

Best Regards
Mathias

**Comment by tgxn** [comment]
Hey, It seems that you're talking about strings inside the compiled app files.
I'm not able to find the file you're talking about in the source files [under code](https://github.com/RocketChat/Rocket.Chat).
Are you able to let us know what the string is that seems to be hardcoded? we might be able to track it down inside one of the packages and update it to use the i18n format for strings.

**Comment by lunitic** [comment]
The files comes from the meteor package 

accounts-password

//Mathias

**Comment by AxxiD** [comment]
Still, I'd like to modify the text being send.
Still an issue in 0.46.0 (docker image)

**Comment by ggazzo** [comment]
hey @lunitic we made a lot of changes on emails, all emails should be translated ( and accepting any key from the dictionary) 
![image](https://user-images.githubusercontent.com/5263975/52458890-1cf5f980-2b49-11e9-843d-8c8e87ea5999.png)
![image](https://user-images.githubusercontent.com/5263975/52458899-254e3480-2b49-11e9-9007-3c8388741756.png)
any problem please tell me
