### ISSUE TITLE
new line (\n) does not work in password reset email

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#4001]
Your Rocket.Chat version: (make sure you are running the latest) 0,36

 \n does not seem to work in the accounts-password.js 

Same issue on demo.rocket.chat.

The mail you get refers to the link below. But everything is in one line

![image](https://cloud.githubusercontent.com/assets/17207375/17652117/effa0cf4-6274-11e6-9ae5-68ed740bbfef.png)

**Comment by isabellarussell** [comment]
I have tested this in 0.62 Cloud and it is still a problem. There is no new line for the link.
I also uncovered the same issue with the verification email.

**Comment by ggazzo** [comment]
closed by #12009 any problem related, please let me know
