### ISSUE TITLE
Hide/autohide the right sidebar

### ISSUE THREAD

**Issue by skizzors** [RocketChat/Rocket.Chat#4002]
Your Rocket.Chat version: 0.36

The right sidebar could be easily hidden with an optional button at the top right on the app.  This would help minimize clutter, especially on smaller screens.

 On the mobile app, this sidebar makes the chat very cluttered and difficult to read, taking up a chunk of space. It would be a great simple feature to be able to swipe to access it, and this would also allow for longer channel titles to be displayed more fully. 

![img_4303 2](https://cloud.githubusercontent.com/assets/17693312/17654074/841595fe-6264-11e6-87eb-52ba92a89f92.PNG)

**Comment by tgxn** [comment]
There is a pull request [here](https://github.com/RocketChat/Rocket.Chat/pull/3229) that contains updates to the styles concering 360px width devices/layout.

This may be the features/changes you're looking for.

**Comment by skizzors** [comment]
Nice yea that does look like it, hope they get finished with the testing and implementing soon!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Not relevant anymore, there is no sidebar on the right anymore, as all of this went up into the top bar.

Cheers
Thomas
