### ISSUE TITLE
Can't change colors and custom CSS/script doesnt work.

### ISSUE THREAD

**Issue by myaspm** [RocketChat/Rocket.Chat#4004]
Version 0.36.0.

Hello, i've installed a Rocket.Chat on Docker in my company server everything is good and well, i can change the images but for some reason i can't change the colors or add custom CSS/scripts from the 'Layout' tab. I can't provide links because it's a private company server.

Thanks in advance.

**Comment by vetash** [comment]
@myaspm hello there! Have you tried to add `!important` after css style?
like:
```code {
    font-size: 11px !important;
    font-weight: 100 !important;
}```

**Comment by myaspm** [comment]
Yeah i have but no good.

**Comment by vetash** [comment]
Can you post your css here?

**Comment by myaspm** [comment]
.side-nav .footer {
    background: #fff !important;
    background-color: #a8a9ad !important;
}
.flex-tab-bar {
background-color: #43ffff !important;
}

These were just our tests.

**Comment by maxlinux2000** [comment]
I've just tried without !important and it's works fine

```
html, body {
    height: 100%;
    margin: 0;         
}

.submit {
    margin: 10px;
    padding: 10px;
    background: #F44436;  
}
.register {
    margin: 10px;
    padding: 10px;
    background: #F44436;
}

.forgot-password {
    margin: 10px;
    padding: 10px;
    background: #F44436;
}
.input-message-container {
    border: 1px solid grey;
}

```

**Comment by myaspm** [comment]
I've just copy-pasted your code and still nothing. I can't even change colours from Layout menu, i don't know why.

**Comment by vetash** [comment]
@myaspm try to restart server. logout and login again, open browser in incognito mode. Also After you save changes click on random menu position in admin panel.

**Comment by vetash** [comment]
One more question: have you trying to change colors in `colors` section in layout?

**Comment by myaspm** [comment]
Yeah that is what i was saying. :/ Did everything i can come up with but no good. Thanks for your help so far^^

**Comment by maxlinux2000** [comment]
very strange..... try to restart with a fresh install.

**Comment by KirbySSmith** [comment]
Check your logs for a less compilation error. If there is an error while compiling your less files, the css does not get updated. After being compiled, the css is stored in db.rocketchat_settings.find({"_id":"css"}). You can check to see if the saved css includes your changes.

**Comment by myaspm** [comment]
Will do right now, thanks.

**Comment by AlecTroemel** [comment]
dont know if this is still a problem for you, but I was experiencing it today. Check this line here to see if it matches yours https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-theme/assets/stylesheets/utils/_colors.import.less#L1153

I think the name of that less variable was changed recently so as KirbySSmith suggested the less wasn't compiling. Updating this file resolved the issue for me.

**Comment by jszaszvari** [comment]
I've been having exactly the same issue recently. 

I need to restart multiple times before I can update any colors in the Web UI

In debug mode the console spams errors like this when trying to save 

rocketchat_theme server.coffee:107 rocketchat:theme ➔ stop_rendering 444
{ [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']
  type: 'undefined_method',
  filename: 'input',
  index: 182171,
  line: 7567,
  callLine: NaN,
  callExtract: undefined,
  column: 20,
  extract:
   [ '\t&:after {',
     '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',
     '\t}' ],
  message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',
  stack: undefined }
debug.js:15 Meteor ➔ method getStatistics -> userId: uLJ2GkWEz4KXywZrJ , arguments:  {}
debug.js:15 Meteor ➔ method saveSetting -> userId: uLJ2GkWEz4KXywZrJ , arguments:  { '0': 'theme-color-tertiary-background-color', '1': '#336699' }
Color
{ rgb: [ 42, 53, 66 ], alpha: 1 }
rocketchat_theme server.coffee:107 rocketchat:theme ➔ stop_rendering 361
{ [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']
  type: 'undefined_method',
  filename: 'input',
  index: 182171,
  line: 7567,
  callLine: NaN,
  callExtract: undefined,
  column: 20,
  extract:
   [ '\t&:after {',
     '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',
     '\t}' ],
  message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',
  stack: undefined }
debug.js:15 Meteor ➔ method UserPresence:away -> userId: null , arguments:  {}

**Comment by KirbySSmith** [comment]
@jszaszvari In the Layout->Colors section what are your settings for "Primary Background Color" and "Quaternary Font Color"?

**Comment by jszaszvari** [comment]
@KirbySSmith  

Primary Background Color = #2a3542

Quaternary Font Color = #e1e1e1

This is now the 3rd seperate instance of mine where the layout changing features have just completly stopped working. 

I just rebooted 3 times, waited 30 mins, and it's working again, but i expect it to break at some time in the near future as it never stays working for long.

`I20160906-16:33:52.308(0) { rgb: [ 42, 53, 66 ], alpha: 1 } 
I20160906-16:33:52.323(0) rocketchat_theme server.coffee:107 rocketchat:theme ➔ stop_rendering 526 
I20160906-16:33:52.324(0) { [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 182171,   line: 7567,   callLine: NaN,   callExtract: undefined,   column: 20,   extract:     [ '\t&:after {',      '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',      '\t}' ],   message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160906-16:33:53.040(0) cas_rocketchat.js:50 CAS ➔ info Disabling CAS login service 
I20160906-16:33:53.629(0) Color 
I20160906-16:33:53.629(0) { rgb: [ 42, 53, 66 ], alpha: 1 } 
I20160906-16:33:53.632(0) rocketchat_theme server.coffee:107 rocketchat:theme ➔ stop_rendering 447 
I20160906-16:33:53.633(0) { [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 182171,   line: 7567,   callLine: NaN,   callExtract: undefined,   column: 20,   extract:     [ '\t&:after {',      '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',      '\t}' ],   message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160906-16:33:53.939(0) (migrations.js:114) Migrations: Not migrating, already at version 58
I20160906-16:33:54.499(0) Color 
I20160906-16:33:54.500(0) { rgb: [ 42, 53, 66 ], alpha: 1 } 
I20160906-16:33:54.505(0) rocketchat_theme server.coffee:107 rocketchat:theme ➔ stop_rendering 421 
I20160906-16:33:54.506(0) { [Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']   type: 'undefined_method',   filename: 'input',   index: 182171,   line: 7567,   callLine: NaN,   callExtract: undefined,   column: 20,   extract:     [ '\t&:after {',      '\t\tbackground-color: mix(@quaternary-font-color, @primary-background-color, 65%);',      '\t}' ],   message: 'error evaluating function `mix`: Object [object Object] has no method \'toHSL\'',   stack: undefined } 
I20160906-16:33:54.527(0) Updating process.env.MAIL_URL `

**Comment by KirbySSmith** [comment]
@jszaszvari 
That error "no method 'toHSL'" is thrown if a value passed into the less color function is not a valid color string. 

It looks like there is a bug with the color administration page that may be related to your issue. If you type just the hex digits and click off the field, '#' is automatically added to the beginning. However when this happens it does not trigger the template event to update the setting's value. That means that even though the UI is showing "#2a3542", the value set and saved to the db maybe "2a3542". This would cause the errors you are seeing. 

Next time you see that error check the database to see if the values for rocketchat_settings {_id:'theme-color-primary-background-color'} and {_id:'theme-color-quaternary-font-color'} actually have '#' at the beginning.

**Comment by engelgabriel** [comment]
Indeed, this occurs when one of the colors has an invalid value. We have now created a RESET button that can be used to get the system back to a working state. We will add more validations to prevent it from getting into a invalid state again.
