### ISSUE TITLE
Revert main font change

### ISSUE THREAD

**Issue by ArchRoller** [RocketChat/Rocket.Chat#4008]
Your Rocket.Chat version: develop

Revert main font change because on Windows it's look ugly
# Before (Segoe UI)
![segoe_chat](https://cloud.githubusercontent.com/assets/16035824/17676840/a1441732-6349-11e6-9a1f-b3087e261ce4.png)
![segoe_settings](https://cloud.githubusercontent.com/assets/16035824/17676842/aa9bbcd6-6349-11e6-80aa-ff54fb127f91.png)

# After (Arial)
![arial_chat](https://cloud.githubusercontent.com/assets/16035824/17676856/bb871fb8-6349-11e6-8501-68fd2dc089c3.png)
![arial_settings](https://cloud.githubusercontent.com/assets/16035824/17676858/bfb2356e-6349-11e6-9165-cdac4b71b0df.png)

**Comment by engelgabriel** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat/commit/8ced9a903a07ceaba12bc46cf9cb365e9da70a39

**Comment by ArchRoller** [comment]
But because of this commit i've created this issue. 😄
