### ISSUE TITLE
Can't send selected messages by mail if I set 'hide right side bar with click' to 'yes' in account->preferences 

### ISSUE THREAD

**Issue by waley1975** [RocketChat/Rocket.Chat#4012]
when  I set 'hide right side bar with click' to 'yes' in account->preferences.
then , in rooms, I select some messages to send mail to others, Once I select messages by click them, the right side bar disappear,so I can't send mail.

It is ok when i  set 'hide right side bar with click' to 'no' in account->preferences.
So has it better solution?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
