### ISSUE TITLE
Uploading picture gives 403 sporadically

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#4014]
Your Rocket.Chat version: (make sure you are running the latest) 0,36

Very often when someone uploads a clipboard files it gets failed a 403 is showed in the console log.

![image](https://cloud.githubusercontent.com/assets/17207375/17688129/73ed947e-637c-11e6-9dbd-f423f9dfb9c7.png)

If the person do a refresh crtl+r of page then the image is showed!
Using GridFS.

This is very very annoying. Running the RC as 1 instance at the moment without any nginx loadbalancing.
However the nginx sits infront of the RC but only has 1 server upstream. Previously it had 3 upstream instances. But changed it to 1 to rule out session issues. 
Anyone else have the same experience.

**Comment by AlecTroemel** [comment]
The issue could be coming from this line of code here https://github.com/AlecTroemel/Rocket.Chat/blob/develop/lib/fileUpload.coffee#L56

Which could be because rocketchat is unable to get the rawCookies (or its missing the uid or token).  Maybe something with nginx

**Comment by lunitic** [comment]
@AlecTroemel  this is my config on the nginx i got the config from @Sing-Li 
Any NGINX pro that could look at it??




`# Upstreams

upstream backend {
        server 127.0.0.1:3000;
        server 127.0.0.1:3001;
        server 127.0.0.1:3002;
}

server {
        listen 443;
        server_name chat.example.com;
        error_log /var/log/nginx/example.access.log;

        ssl on;
        ssl_certificate /etc/nginx/certificate.crt;
        ssl_certificate_key /etc/nginx/certificate.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 ;

        error_page 497 https://chat.example.com;

    location / {
        proxy_pass http://backend/;
        #proxy_pass http://192.168.102.2:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}

server {
        listen 80;
        server_name www.example.com;
        error_log /var/log/nginx/www.example.access.log;
        #return         301 https://chat.example.com:81;


    location / {
        proxy_pass http://192.168.102.7/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;

    }

}

server {
        listen 80;
        server_name chat.example.com;
        error_log /var/log/nginx/example.access.log;
        return         301 https://chat.example.com;
        }
`

**Comment by lunitic** [comment]
And my config is identical with 

https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy-with-nginx

**Comment by lunitic** [comment]
This problem occur on 2 RC installations haven't anyone else seen it?

**Comment by lunitic** [comment]
Just to add this is windows 10 64bit clipboard 

On @Sing-Li suggestion i tested to use S3 instead. Behaves the same

**Comment by lunitic** [comment]
Not only clipboard files gives this result.. Also happend from regular (a png) pictures.

**Comment by lunitic** [comment]
This driving me nuts..

Just tested to disable firewall IDS system infront of the chat and the ngingx..
Still get this 403 now and then when i scroll back in messages.

**Comment by pierreozoux** [comment]
One of my user is hitting the same issue on his instance, let me know if I can help debug.

**Comment by engelgabriel** [comment]
We are updating the GridFS packages, can you guys please retry with the develop branch when https://github.com/RocketChat/Rocket.Chat/issues/4235 gets closed?

**Comment by pierreozoux** [comment]
@engelgabriel Thanks, but I can't test easily until it hits a release. Just let me know when it is released, and then I let know my user.

(Or do you have a develop docker image?)

**Comment by engelgabriel** [comment]
@pierreozoux and @lunitic can you please try with version `0.40.1` ?

**Comment by lunitic** [comment]
@engelgabriel just gonna update our live server to 0.39 then we will migrate to 0.40.1 on our lab server.

**Comment by lunitic** [comment]
@engelgabriel finally had time to upgrade lab server and it persists. in 0.43

**Comment by lunitic** [comment]
This weekend I will replace the Sophos firewall in front of the instance.  It's the last thing I can come up with

**Comment by lunitic** [comment]
Just notice that his happend on demo.rocket.chat too


![image](https://cloud.githubusercontent.com/assets/17207375/19679436/036b0db4-9aa2-11e6-836a-df639a54b9d5.png)

**Comment by lunitic** [comment]
Console log

![image](https://cloud.githubusercontent.com/assets/17207375/19679455/1763fdee-9aa2-11e6-8748-7830dfc48f8c.png)

**Comment by lunitic** [comment]
![image](https://cloud.githubusercontent.com/assets/17207375/19679706/2b4efd58-9aa3-11e6-8e9f-f18b0a616291.png)

**Comment by rodrigok** [comment]
Any way to reproduce? I can't :(

**Comment by engelgabriel** [comment]
@lunitic @AlecTroemel @pierreozoux Is this still happening?

**Comment by pierreozoux** [comment]
@engelgabriel I confirm that it is fixed, thanks (and sorry for delay)

**Comment by lunitic** [comment]
Sorry i saw the comment now.. I am at 0.43 and there it still exists.
Have not been able to upgrade to any later revision yet..  (waiting for a stable release) 
@engelgabriel @rodrigok

**Comment by garychapman** [comment]
Definitely not fixed. I can easily replicated it just by logging out and in again - refreshing the browser (while in the channel where the image is posted) fixes it for the duration of that particular login session.

I did some digging in packages/rocketchat-file-upload/server/lib/requests.js and it looks like it's picking up the `rc_token` value from the previous login. As soon as you refresh, you get a new `rc_token` and then the `findOneByIdAndLoginToken()` call succeeds.

**Comment by bbrauns** [comment]
I can confirm that this bug:  
docker image: rocket.chat:0.52
Ubuntu 14.04.5 LTS
haproxy:1.7 as reverse proxy

**Comment by lunitic** [comment]
Started to dig in this issue.. 0.55.1 is still having it.. (our current server) It seems that the Rocket.Chat client makes it worse.

**Comment by Khuman2** [comment]
Have the same issue with 0.74.3
