### ISSUE TITLE
Upload from mobile app broken

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4015]
Hey Guys, 

on the Demo system the upload from my mobile device seems broken, there is no button which I can click and upload a photo or something else. 

![](http://i.imgur.com/xPKmeNB.jpg)

Is there a new shortcut for this or is it just broken? 

Greetings
TheReal

**Comment by frdmn** [comment]
Fixed in d70a0e84f186eec5360bcc904d3a3bca84016cd8. Confirmed by @TheReal1604

**Comment by TheReal1604** [comment]
Fixed! Thx.
