### ISSUE TITLE
Can't delete user more than once.

### ISSUE THREAD

**Issue by alexandrezia** [RocketChat/Rocket.Chat#4018]
Your Rocket.Chat version: 0.37.0

If you create an user, deletes it, create again and delete again, 
MongoError: E11000 duplicate key error collection: rocketchat.rocketchat__trash index: _id_ dup key: { : "dDS6tiNnjSfcGXvNF" }

**Comment by MartinSchoeler** [comment]
Hey @alexandrezia i think that problem has been resolved in the version 0.37.1, try to update your rocket chat and see what happens. Thanks for the feedback!
