### ISSUE TITLE
Multiple instances of nodejs fails to propagate messages

### ISSUE THREAD

**Issue by alexandrezia** [RocketChat/Rocket.Chat#4019]
Your Rocket.Chat version: 0.37.0

When running multiple instances of nodejs they fail to show messages to users, messages are not shown on all clients, depending on which node clients are connected.

Tons of log entries such as:
StreamBroadcast ➔ Auth.info Authorizing with localhost:3000
streamBroadcast.coffee:62 StreamBroadcast ➔ Stream.error Stream broadcast from 'localhost:3001' to 'localhost:3000' with name room-messages not authorized

**Comment by AstrosMX** [comment]
I can confirm the same issue. The problem started after the upgrade to Rocket.Chat 0.37. In my case, resetting file permissions to be sure they match the user that runs the service and restarting the rocketchat instances apparently fix it. However, I haven't made further tests.

**Comment by mpetersen42** [comment]
I've seen this intermittently with 0.36 and 0.37.1, seems to happen quite a bit more than it used to with 0.37.1 though.  Only workaround seems to be restarting all instances when it happens.

**Comment by rodrigok** [comment]
@alexandrezia @AstrosMX @mpetersen42 Can you test the version 0.38? Should be solved now.

**Comment by AstrosMX** [comment]
Sure. I'm testing version 0.38 right now. I'll tell you if I find anything.

**Comment by alexandrezia** [comment]
Seems to be Ok now,

**Comment by rodrigok** [comment]
Awesome, please reopen this issue if the problem persists.

**Comment by ronaldosaheki** [comment]
We are running some load tests running 2 servers with 8 cpus, each server running 7 rocketchat processes (as it is single-threaded) listening in different ports and connected to a 3-member mongodb replicaset, using version 0.39.0 and we are getting the same error and then the chat content is updated only after a reload on the browser.

`» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.051300Z ip-172-28-12-92 rocketchat3005.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3005' to 'localhost:3001' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.051319Z ip-172-28-12-92 rocketchat3005.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3005' to 'localhost:3003' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.051332Z ip-172-28-12-92 rocketchat3005.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3005' to 'localhost:3003' with name notify-room not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.121953Z ip-172-28-12-92 rocketchat3000.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3000' to 'localhost:3003' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122013Z ip-172-28-12-92 rocketchat3000.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3000' to 'localhost:3003' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122033Z ip-172-28-12-92 rocketchat3000.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3000' to 'localhost:3001' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122247Z ip-172-28-12-92 rocketchat3006.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3006' to 'localhost:3003' with name notify-room not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122272Z ip-172-28-12-92 rocketchat3006.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3006' to 'localhost:3003' with name notify-room not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122287Z ip-172-28-12-92 rocketchat3006.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3006' to 'localhost:3003' with name room-messages not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122300Z ip-172-28-12-92 rocketchat3006.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3006' to 'localhost:3003' with name room-messages not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122312Z ip-172-28-12-92 rocketchat3006.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3006' to 'localhost:3003' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log
» 13 Sep 2016 18:01:15.141 <14>1 2016-09-13T21:01:15.122408Z ip-172-28-12-92 rocketchat3001.log - - - streamBroadcast.coffee:83 [31mStreamBroadcast ➔ Stream.error[39m [31mStream broadcast from 'localhost:3001' to 'localhost:3005' with name notify-user not authorized[39m rocketchat-performance/rocketchat.log`

**Comment by ronaldosaheki** [comment]
Para o rocketchat são duas instancias m4.2xlarge na AWS atrás de um nginx sem usar ELB e todos os processos estão conectando a mesma replicaset mongo:
* MongoDB shell version: 3.0.12
* nginx version: nginx/1.4.6 (Ubuntu)
* Ubuntu 14.04.4 LTS

As configurações para a conexão ao mongo:
env MONGO_URL="mongodb://mongo001.internal.socialbase.com.br:27017,mongo002.internal.socialbase.com.br:27017,mongo003.internal.socialbase.com.br:27017/rocketchat?replicaSet=rs0&readPreference=nearest"
env MONGO_OPLOG_URL="mongodb://mongo001.internal.socialbase.com.br:27017,mongo002.internal.socialbase.com.br:27017,mongo003.internal.socialbase.com.br:27017/local"
os hostnames são resolvidos pelo DNS interno para todas as máquinas

**Comment by rodrigok** [comment]
Hi @ronaldosaheki, If you are using more than 1 machine you should set the env var `INSTANCE_IP` on each instance then they can connect between machines, otherwise they will try to connect via localhost only.

**Comment by ronaldosaheki** [comment]
Rodrigok,

Thanks for the solution.

The INSTANCE_IP is set, the StreamBroadcast message error is gone, we upgraded to 0.43 but one user still reported that the message failed to propagate, checking the logs the only message we got is:

```
TypeError: Cannot read property 'split' of undefined
    at Object.get [as action] (server/publications/userData.coffee:1:1)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:149:25)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes/json-routes.js:76:1
TypeError: Cannot read property 'split' of undefined
    at Object.get [as action] (server/publications/userData.coffee:1:1)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:149:25)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes/json-routes.js:76:1
```

I am not sure if the root cause of this error is some css/site/code customization, not even if this message error is related with the propagation failure, but it's the only log message I have and it appears in every installation: single mongo, replicaset mongo, single server, multiple server, etc.

Regards,
Ronaldo Saheki
