### ISSUE TITLE
An attempt to install the latest version results in a database migration failure message

### ISSUE THREAD

**Issue by kingsalemno** [RocketChat/Rocket.Chat#4023]
+------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                              |
|                                                     ERROR! SERVER STOPPED                                                    |
|                                                                                                                              |
|                                                Your database migration failed:                                               |
|  The positional operator did not find the match needed from the query. Unexpanded update: attachments.$.title_link_download  |
|                                                                                                                              |
|                              Please make sure you are running the latest version and try again.                              |
|                                       If the problem persists, please contact support.                                       |
|                                                                                                                              |
|                                               This Rocket.Chat version: 0.37.0                                               |
|                                                Database locked at version: 34                                                |
|                                                  Database target version: 56                                                 |
|                                                                                                                              |
|                                       Commit: 7ab2481546957f5d455a9ceae89de936d7c3e636                                       |
|                                             Date: Mon Aug 15 18:52:47 2016 -0300                                             |
|                                                         Branch: HEAD                                                         |
|                                                          Tag: 0.37.0                                                         |
|                                                                                                                              |
+------------------------------------------------------------------------------------------------------------------------------+

**Comment by kruczjak** [comment]
I have almost the same, but my is I think caused by ID's duplicates by SlackBridge :(

**Comment by mrplow** [comment]
likely related to #4096

**Comment by tunglam14** [comment]
👍   I have the same problem

**Comment by adeweever91** [comment]
I found a solution that worked for me. 
By dropping into a mongo shell and doing the following:
```
root@a4fa974ca610:/# mongo 
MongoDB shell version: 3.2.6 
connecting to: test  
> use rocketchat
switched to db rocketchat
> db.rocketchat_message.update({'attachments.title_link': {$exists: true}, 'file._id': {$exists: true}, 'attachments.title_link_download': {$exists: false} }, {$set : {"attachments.$.title_link_download":true}}, {
multi: true})
WriteResult({ "nMatched" : 96, "nUpserted" : 0, "nModified" : 96 })
> db.migrations.update({"locked":true},{$set: {"locked":false}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
> exit
```
 
you only need to unlock the DB if you have already started the migration and had it fail. otherwise you should be able to ignore that. Hope it helps!

**Comment by tunglam14** [comment]
@adeweever91 👍  yeah, I did the same
