### ISSUE TITLE
Guide for integration Zapier - Rocket.chat

### ISSUE THREAD

**Issue by pacoeu** [RocketChat/Rocket.Chat#4024]
Hi, I'm running the version 0.36.0 in heroku (I'm testing rocket.chat, after the testing I will deploy the installation in the server).
I've read that we can integrate tweets in a channel in rocket via zapier, but I'm not able to configure zapier to do so.
Can anyone help me? A how-to, via UI, not via code.
Thanks

**Comment by asthomasdk** [comment]
I tried that the other day as a simple test - just by using a WebHook in Zapier.
