### ISSUE TITLE
Livechat options button not clickable 

### ISSUE THREAD

**Issue by AlecTroemel** [RocketChat/Rocket.Chat#4030]
Your Rocket.Chat version: 0.37

the new options button is currently unclickable. I believe this is because the "powered by" div is covering it. Adding a `margin-left: 50px;` fixed the issue for me in chrome.

**Comment by engelgabriel** [comment]
Thanks @AlecTroemel can you please do a PR with the fix?

**Comment by AlecTroemel** [comment]
beat me too it, but sampaiodiego's solution is better then what I was suggesting!
