### ISSUE TITLE
Sound not working: No live audio input

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat#4035]
Your Rocket.Chat version: 0.37.0

When I click on the microphone next to the main textbox, I get the following in the console:

```
b3d9e42….js?meteor_js_resource=true:208 No live audio input: [object NavigatorUserMediaError]
```

and

```
b3d9e42….js?meteor_js_resource=true:208 Uncaught NotSupportedError: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
AudioRecorder.e.start   @   b3d9e42….js?meteor_js_resource=true:208
click .message-form .mic    @   b3d9e42….js?meteor_js_resource=true:253
r.(anonymous function)  @   b3d9e42….js?meteor_js_resource=true:178
(anonymous function)    @   b3d9e42….js?meteor_js_resource=true:84
e._withTemplateInstanceFunc @   b3d9e42….js?meteor_js_resource=true:84
(anonymous function)    @   b3d9e42….js?meteor_js_resource=true:84
(anonymous function)    @   b3d9e42….js?meteor_js_resource=true:83
d._withCurrentView  @   b3d9e42….js?meteor_js_resource=true:83
(anonymous function)    @   b3d9e42….js?meteor_js_resource=true:83
(anonymous function)    @   b3d9e42….js?meteor_js_resource=true:83
dispatch    @   b3d9e42….js?meteor_js_resource=true:70
g.handle    @   b3d9e42….js?meteor_js_resource=true:70
```

I'm using Chromium 51.0.2704.79 on Linux. Please let me know what extra information (if any) you need to debug this.

**Comment by MartinSchoeler** [comment]
Hey @antgel  thanks for the bug report! Could you try this in another browser and tell us what happens?

**Comment by antgel** [comment]
Worked fine with Firefox 48. Where to go from here?

**Comment by yuchaozh** [comment]
Same things happens for me. My Rocket Chat version is: 0.35.0. Not working on chrome. But works on Firefox. Does anyone know how to fix this?

**Comment by antgel** [comment]
Can someone remove the "waiting response" label? :)

@yuchaozh 0.35 is really old, can you upgrade as a first step?

**Comment by RomanKisilenko** [comment]
We have this issue reproduced for 0.48, latest Google Chrome browser. Similar issue when I click on video message. It logs 
No live video input: [object NavigatorUserMediaError]

As a result, unable to send voice or video messages.

**Comment by MartinSchoeler** [comment]
This is a google chrome problem not a Rocket chat one. Chrome won't allow using your camera or microphone on non `https` sites. https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins 

Thanks!
