### ISSUE TITLE
Roles removed from user by editing and saving user

### ISSUE THREAD

**Issue by homberger** [RocketChat/Rocket.Chat#4036]
Your Rocket.Chat version: 0.37.0

When editing and saving a user (like changing the display name) he will lose all assigned roles.

Steps to reproduce (as admin):
1. Administration -> Users
2. Click on a user
3. Click on EDIT
4. Change "Name"
5. Click on SAVE

result: user is removed from all roles and is not able to enter any channels.

**Comment by Syirrus** [comment]
I can confirm that error. If you change an email address for a user as an admin, that user's role information is lost.
