### ISSUE TITLE
Report inapropiate message to admin

### ISSUE THREAD

**Issue by pacoeu** [RocketChat/Rocket.Chat#4037]
Version 0.36.0.
I've searched in github and docs, and I've not found any system of reporting available for the users, in order to communicate to the admin in case a user wanted to report a bad/inapropiate/incorrect/obscene message.
I wonder if there is any report system.
Thanks

**Comment by graywolf336** [comment]
@RocketChat/core Whatever happened to our report message feature we used to have on mobile? Does that only exist on the phones now? As I couldn't find it on the desktop with the other buttons

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #3514. If you do not agree, please get back to me :)

Cheers
Thomas
