### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by candro** [RocketChat/Rocket.Chat#4044]
Your Rocket.Chat version: (make sure you are running the latest)
I found a bug. After registration, if you exit from your account and enter through the email, rather than login, that you walk as a normal user, not admin.
Just when the first page does not load input in the console message something about a mistake in rocketchat_roles.

This is the latest version for developers...

**Comment by MartinSchoeler** [comment]
@candro is this issue still happening in the latest version?

**Comment by MartinSchoeler** [comment]
@candro Since this issue hasn't been updated for so long, I'm closing it until we see it happen again. Please reopen if so. Thanks.
