### ISSUE TITLE
Default channels/groups

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#405]
Right now, when a new user enters on rocket.chat it automatically join to GENERAL channel.

I think this behavior shoud be configurable and admins should have an option to choose which channels and/or groups new users will automatically join after registration.

**Comment by rodrigok** [comment]
+1

**Comment by wellingtonufsc** [comment]
Is there any prospect the development of this possibility?

**Comment by rodrigok** [comment]
Needs a config option

**Comment by mitar** [comment]
+1

**Comment by mitar** [comment]
+1

**Comment by jcardila** [comment]
+1

**Comment by Johann-Snapp** [comment]
+1 haha

**Comment by engelgabriel** [comment]
@sampaiodiego please add respective the room property to the channel settings.

**Comment by engelgabriel** [comment]
closed by https://github.com/RocketChat/Rocket.Chat/pull/2290

**Comment by FaizanZahid** [comment]
totally agree on this suggestion.

**Comment by RAurelian** [comment]
Hi,

Has this been added? I`m on version 2.4.2 (ubuntu snap) and cannot find any way to make a channel default.

**Comment by sampaiodiego** [comment]
@RAurelian there is a new snap release that fixes an issue to show the checkbox to mark a channel as default again.. you should be able to update your snap to version 2.4.9

**Comment by RAurelian** [comment]
Thanks, I`ll try the update maybe next week.

**Comment by RAurelian** [comment]
Apparently the snap updated itself automatically to 2.4.9 and while for the default room you have the checkbox and can make it not be default, there still are no checkboxes for other rooms to make them default.

**Comment by sampaiodiego** [comment]
On "Admin > Rooms", clicking in a public room will open a panel with the following options:
![image](https://user-images.githubusercontent.com/8591547/74537132-409c0e80-4f18-11ea-9597-6e513e3eb24a.png)

there you can change to make it default.

one thing to notice, different from the issue title, private groups cannot be default.

**Comment by RAurelian** [comment]
Thank you very much for the clarification - indeed, apart from 2 default public channels I had, I was looking at private groups. After creating another public channel, I was able to find the Default toggle and enable it.

**Comment by robpedersendev** [comment]
I have a room titled important-announcements that is a broadcast channel. When I got to select default, MI get this error. 
![image](https://user-images.githubusercontent.com/40696979/109545223-d05e1d80-7a85-11eb-8549-5aa92a9489d5.png)

Please adjust this so one can make a broadcast channel as a default group

**Comment by leoxu1007** [comment]
+1
