### ISSUE TITLE
Sharing an http link causes Mixed Content warnings

### ISSUE THREAD

**Issue by AstrosMX** [RocketChat/Rocket.Chat#4050]
Hello!

I'm running the latest version of rocketchat (0.37). My general setup is as follows: 

```
-Apache2 running ssl engine and proxy balancer which points to two instances of rocketchat.
- rocketchat has been setup without docker.
```

When a user shares an https link in the chat window, the preview is shown correctly and the ssl connection remains in a good condition. However, when the user shares an http link and the web page preview is shown, the ssl connection gets broken. Firefox complains about the connection being no longer secure. If I disable embed, everything seems to work fine.
Is this a bug or I misconfigured something? Is it posible to disable just the http link preview to avoid security issues?

Thank you in advance

**Comment by FibreFoX** [comment]
I can confirm this problem using HTTPS-setup and sharing HTTP-links. I suspect it is the preview-image which is getting loaded but not injected, and therefor the browser talks about "mixed-content". As the browser should avoid this, there only needs some disable-button for link-previews (I'm new to RocketChat, so maybe I just missed this setting).

**Comment by aldarionsevero** [comment]
Hi, 

We have the same problem here.  If any user shares an http link, and the preview is shown, the browser complains about it. http links without preview does not break the ssl. Disable just the http link preview would be really nice.

**Comment by luanguimaraesla** [comment]
Same problem here

**Comment by aldarionsevero** [comment]
This happens even in your demo... http://imgur.com/eQxPyOV

**Comment by AstrosMX** [comment]
I have a workaround for this problem. To implement it, you have to make sure that your rocket.chat server is not requiring outgoing connections through port 80 except for showing the http link preview. If your rocket chat server is using this port to perform any other action, you can not use this workaround. Also, you must be using iptables to set your firewall rules.

These are the steps I suggest you to follow:

1. Delete all the http links that might exist in all your channels. Then, logout and stop your rocket.chat server. 
2.  For this, I asume that your rocket.chat service is running as the rocketchat user.  If so, type or copy this command at your linux shell:
     	•	iptables -A OUTPUT -p tcp -m owner --uid-owner rocketchat  --dport 80   -j DROP

3. Make your iptables rule permanent. If you are using a SuSE based system, you need to proceed as follows:

	•	Go to the /etc/sysconfig directory. Then, using your favorite text editor, edit the SuSEfirewall2  file to include this line: FW_CUSTOMRULES="/etc/sysconfig/scripts/SuSEfirewall2-custom"
	•	Now, edit the /etc/sysconfig/scripts/SuSEfirewall2-custom file. In the fw_custom_before_port_handling() section include the following lines:

	       FW_USE_IPTABLES_BATCH="no" 
	       iptables -A OUTPUT -p tcp -m owner --uid-owner rocketchat  --dport 80
 		
	•	 Save your changes and execute the SuSEfirewall2 command (type SuSEfirewall2 at your command line and press enter).

4. Finally, restart your rocket.chat service.

Now, after login, you’ll be able to share http links without braking the ssl connection (the http link preview will not be shown); https link previews will work just fine. 

This is just a workaround. It would be very nice to have an option to disable just the http link preview.

**Comment by FibreFoX** [comment]
@AstrosMX another workaround would be to disable preview of shared links ;) but very nice hack you provided

**Comment by engelgabriel** [comment]
Guys, `break` is not the right word here. The fact that the browser warns you about not ALL the content being HTTPS is correct, and doesn't mean that the SSL was broken, just that you have mixed contents. You message stream and all the communications with the Rocket.Chat server as still encrypted, you have just requested an image from an unencrypted source. 

We can:

1. Make an option to disable previews from unencrypted source.

or

2. Create an internal encrypted proxy.

or

3. Add an option to use something like http://rsz.io/

But this is not a hight priority for us, PRs are welcome.

**Comment by FibreFoX** [comment]
I agree with @engelgabriel that this is not a high priority, as there are several ways to "not include" them, but: having MIXED CONTENT is the point, where the state of the website is BROKEN, because it might inject something from hijackable sources. I agree with the view of **HTTPS not being broken** itself, but the mixed-content is a problem of its own.

Another workaround: CSP-headers ... makes the browser already stop the request and mixed-content won't happen.

**Comment by geekgonecrazy** [comment]
> Another workaround: CSP-headers ... makes the browser already stop the request and mixed-content won't happen.

Only problem with CSP Headers is I don't think they are re-evaluated if they are changed dynamically.  With our current rendering engine, most changes like deciding if that were to be there or not would happen client side like with the title.

**Comment by herbsmn** [comment]
I like the idea of creating a toggle to disable just http link previews. Is this an easy thing to do?

**Comment by Hudell** [comment]
I've recently reopened issue #971 as a feature request for said setting.
