### ISSUE TITLE
Admin user is treated as a normal user; chat rooms are not always shown correctly

### ISSUE THREAD

**Issue by AstrosMX** [RocketChat/Rocket.Chat#4056]
Your Rocket.Chat version: (0.37)

Sometimes, after login, admin user is treated as a normal (unpriviliged) user. When this happens, the login process is particulary slow. Additionaly, the chat rooms are not always shown. 
On the other hand, sometimes, when a normal user tries to login, the login process stops. After a while, when the user finally gets logged, chat rooms are not shown but only direct channels. 
I think rocketchat is having trouble communicating with mongodb database and there might be a bug in rocketchat_roles.

**Comment by MartinSchoeler** [comment]
@AstrosMX have you seen this bug in the latests releases? Thanks for the feedback!

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates
