### ISSUE TITLE
jitsi document header and upper toolbar overlapping

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#4057]
In non full screen mode, it's impossible to click on the buttons in the shared document header.

![image](https://cloud.githubusercontent.com/assets/4588562/17787268/6dbf1f9c-6556-11e6-9adc-17ddcf413daf.png)

Using v0.37.0.

**Comment by geekgonecrazy** [comment]
@rockneverdies55 can you check again?  Jitsi Meet got a bit of a face lift.

**Comment by rockneverdies55** [comment]
Yes, it looks like better now.

![image](https://cloud.githubusercontent.com/assets/4588562/21195557/4477c676-c202-11e6-8da5-470eb55d538a.png)
