### ISSUE TITLE
Feature Requests multiple 

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4059]
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

Link to an external html page on the fly in window when you click on a user.
Ability to see how many people are active in a room without entering the room.
ability to see which rooms a user is active in.
script that automatically kicks inactive users from non-private, non-default rooms OR disallow users from being in more than 1 non-private, non-default room at a time
"No Distractions" mode: turns of notifications for all other rooms.
Ability for admins to enter private rooms. (for moderation purposes, possibly requiring a majority vote of those active in said room?)
Some way to limit the max size of the chat log! My poor laptop freezes if I don't forget to /clear from time to time.

**Comment by FibreFoX** [comment]
one ticket per feature-request ;) makes it better to distribute or discuss

**Comment by MartinSchoeler** [comment]
Hey @wargamesqcf  these are good ideas! But it will be easier for us to organize if you post an issue for each request, as @FibreFoX said. Thanks for the feedback!
