### ISSUE TITLE
Webhook integration doesn't send @all messages.

### ISSUE THREAD

**Issue by ronyodil** [RocketChat/Rocket.Chat#4060]
Your Rocket.Chat version: 0.37.1  (problem appeared in 0.36.0).

When trying to send message with @all tag I'm getting '{"success":false}'. Single-user tags and common messages work as before.
Changes to 'mention-all' permission does not help. (#3703)

```
$ curl -X POST --data-urlencode 'payload={"text":"@all: test"}' $WEBHOOKURL
{"success":false}
$ curl -X POST --data-urlencode 'payload={"text":" test"}' $WEBHOOKURL                                            {"success":true}
```

**Comment by Syirrus** [comment]
@MartinSchoeler make sure the permissions are correct (set in admin) for the user you are using the API with to send messages to everyone.

**Comment by ronyodil** [comment]
I'm using Rocket.Cat for that. He is in Bots group. Also tried to add him to admins, moderators and room owners groups. No luck. 
'mention-all' set to allow for everyone.

**Comment by vrooze** [comment]
I get this too. 
I've been through all of the process as far as I can trace and all mentions work except @all you simply get a response of : 
`{
  "success": false
}`

The query is simple:
`payload:{"text": "Alert test @all"}`

I was originally using a custom user but like the OP, I shifted to rocket.cat. I have given the bot group permissions to mention-all and it made no difference.
