### ISSUE TITLE
Where do we search the sent messages in the form from the livechat 

### ISSUE THREAD

**Issue by pacoeu** [RocketChat/Rocket.Chat#4061]
Your Rocket.Chat version: 0.36.0
After leaving the message in the livechat, where does the admin search it? 
We are not able to find the messages sent when the admin is not online, and the visitors fill up the form.
Thanks

**Comment by sampaiodiego** [comment]
@pacoeu that messages are sent via email.. you can change the email address from the admin panel:
![image](https://cloud.githubusercontent.com/assets/8591547/18633883/d57b99c8-7e54-11e6-9644-8278eebc9083.png)
