### ISSUE TITLE
Enhance configuration description of "Embed"

### ISSUE THREAD

**Issue by FibreFoX** [RocketChat/Rocket.Chat#4062]
Is it possible to enhance the title or description of the "message > Embed"-option?
Something like "Embed preview of links" would be better (at least for me).

The title "embed" suggested to me, that "embedding messages" is somehow ment ... this is confusing, but excepted, because I'm configuring messages, and not "links". But you really mean to embed links inside messages ;) not messages itselves, am I right?

Just found it on issue https://github.com/RocketChat/Rocket.Chat/issues/1659 while searching through closed bugs.

--
My Rocket.Chat version: 0.37.0

**Comment by graywolf336** [comment]
How does `Embed Link Previews` sound? @FibreFoX

**Comment by FibreFoX** [comment]
@graywolf336 sounds very good :D now i would understand it more clearly, thanks !
