### ISSUE TITLE
Developing rocket.chat very slow

### ISSUE THREAD

**Issue by basvdheijden** [RocketChat/Rocket.Chat#4064]
Your Rocket.Chat version: 0.37.0

if I run ``meteor``, it boots up really slow. Also, I get the following error:

``WARNING: The output directory is under your source tree.``

When I make a change to the code, it says ``=> Client modified -- refreshing`` and keeps hanging on that.

In other words: my development setup is unworkably slow. Any tips or things to be able to mitigate this?

I'm running the app on OSX btw.

**Comment by MartinSchoeler** [comment]
Hey @basvdheijden  you could try to remove the livechat package.  Meteor is indeed slow sometimes, and i think they are working on that.

**Comment by basvdheijden** [comment]
@MartinSchoeler The problem is: I do need the livechat package. That's the component I'm working on :-)

**Comment by MartinSchoeler** [comment]
Yep that is a problem with meteor building bigger applications, you could try posting an issue on their github. We are sorry for not being able to help

**Comment by basvdheijden** [comment]
Thanks. So what do you do when developing? Killing the app and (re)running ``meteor`` with every update?

**Comment by MartinSchoeler** [comment]
It happens more on the weaker pc`s around here and if the update is taking too long we kill it, else we just wait.

**Comment by basvdheijden** [comment]
ok, thx!

**Comment by basvdheijden** [comment]
One question though: I see it's minifying and building for cordova all the time. How can I disable this? It'll restart faster then :-)

**Comment by basvdheijden** [comment]
This is highly unworkable. My PC is quite fast (SSD, 2,7 GHz Intel Core i5 with 16 GB ram). I'd really like to know how to speed up the build times. Maybe depublishing some of the packages within RocketChat?

**Comment by graywolf336** [comment]
@basvdheijden Yes, the build is very slow. You could remove some of the internal packages you no longer need however a tip I've learned is don't stop the server itself when developing as it will catch all the edits and rebuild faster once it's back up.

As already mentioned by @MartinSchoeler, this is a problem with large Meteor applications and Rocket.Chat isn't the only one affected by it. You could take a read at this Medium article about it as well: https://medium.com/@lucashansen/faster-meteor-reloads-62cca5b56460#.z4fqr1ico

**Comment by rockneverdies55** [comment]
It's crazy how slow it is. I was surprised how the core team could stand with this.

**Comment by phuyem** [comment]
One year later, it is still incredibly slow ! The Laptop is core i7 4 core 2.71GHz, 16GB RAM. 

Not only that, it seems to eat up alot of CPU & RAM !!

Well, just so you know
