### ISSUE TITLE
Feature Requests Html link

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4065]
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

Link to an external html page on the fly in window when you click on a user, or maybe some way of having a profile that you can fill out with details?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this. Showing different information in the user profile is a bigger issue... there are dozens of those issues here on Github and I think they will be consolidated at some point in the future.

As for you request to make a username a link to an external page, this would break UX and is not desired.

Cheers
Thomas
