### ISSUE TITLE
Feature Requests see who is where

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4066]
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

Ability to see how many people are active in a room without entering the room.
ability to see which rooms a user is active in.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @wargamesqcf 

concerning your first topic (`Ability to see how many people are active in a room without entering the room.`): please continue in #4490. 

for the second: I don't think this is going to be implemented. It highly depends on your community whether this makes sense or not, but in the general case I would assume users value their privacy. If you still think you want this, please head over to the forums (https://forums.rocket.chat) and start a discussion over there :)

Cheers
Thomas
