### ISSUE TITLE
No Distractions

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4067]
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

"No Distractions" mode: turns of notifications for all other rooms.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
