### ISSUE TITLE
Feature Requests: admin can see into private rooms

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4068]
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

Ability for admins to enter private rooms. (for moderation purposes, possibly requiring a majority vote of those active in said room?)

**Comment by alexandrezia** [comment]
If you implement this feature, please add a toggle button so people can enable or disable it.
This is a big "no go" for us, we are subject to compliance rules, periodic auditing, etc.

**Comment by wargamesqcf** [comment]
More options the better!

**Comment by jszaszvari** [comment]
I agree with @alexandrezia - Any features that compromise a users privacy or inability to conduct private conversations is a big no go for the organisation I am deploying this for.

**Comment by Mte90** [comment]
I think that a setting to enable it in the panel from the user that create the room itself will be the easiest way.

**Comment by elfrinjo** [comment]
This might be a duplicate of #2869

**Comment by MartinSchoeler** [comment]
Duplicate of #2869
