### ISSUE TITLE
Feature Request: chat log size

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4069]
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

Some way to limit the max size of the chat log. I have some users on outdated laptops that freeze if they don't forget to ctrl+shift+k/clear from time to time.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
