### ISSUE TITLE
Notifications in mobile devices on Android and iOS (applications and browsers on both) didn't works, no popups and sounds.

### ISSUE THREAD

**Issue by Fenr1r90** [RocketChat/Rocket.Chat#4070]
Rocket.Chat version: 0.37.1 / server on Linux

After update from version 0.35 to 0.36, on mobile devices after receive message didn't appear any notifications. Tested on Android and iOS Rocket.Chat applications and browsers (Chrome and Opera). Test notification from account options work properly, pop-up notification shows but without sound. Upgrade to 0.37 and next 0.37.1 didn't take any effect.

**Comment by christianreiss** [comment]
Same issue here.

**Comment by Fenr1r90** [comment]
Any ideas to repair this issue? Notifications on mobile are "must have".

**Comment by Fenr1r90** [comment]
After update to 0.42 problem still exist...

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
