### ISSUE TITLE
Let users link their social media accounts

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#4071]
Would be cool if under "my account - settings" users could choose to add if they want their Facebook / Twitter / Youtube accounts. I upload a image how it could look like.
![icons](https://cloud.githubusercontent.com/assets/17712562/17832307/deb8f664-66ff-11e6-82e6-4bce5034ba9f.png)

//Molle

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's likely that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
