### ISSUE TITLE
A simple developer (noob) question

### ISSUE THREAD

**Issue by kkoci** [RocketChat/Rocket.Chat#4072]
Your Rocket.Chat version: (0.35.0)

Hi, Well, this is more like a developer question

I mean, I do know node.js, npm, io.js...

But I'm fairly new to meteor, so, forgive me if this a noob question, but I'd like to know, what is the method or philosophy behind putting all these templates/logic on the 'packages' folder?

I'm accustomed to other frameworks (ie. MVC, MVT, MVVM), and I've seen other simpler meteor apps, but I still don't get why all that logic is put on that folder for Rocket.Chat?

In simple words, just to get me started understanding the architecture a little better.

Thanks in advance!

**Comment by davidnguyen2205** [comment]
Ya, me too...

**Comment by geekgonecrazy** [comment]
The idea of putting a lot of things in packages for us is mostly for organization.  But also we want to make it modular so we could actually swap out packages and extend packages if we need to.

**Comment by kkoci** [comment]
Interesting, gonna study something about how to start it, Cheers
