### ISSUE TITLE
How can I change Rocket.Chat  default css?

### ISSUE THREAD

**Issue by wd2010** [RocketChat/Rocket.Chat#4077]
Your Rocket.Chat version: (make sure you are running the latest)

When I change the css in ` rocketchat-theme/assets/stylesheets/base.less` ,but I don't know where is the default CSS   `theme.css?cefd57372b7f9031562454a1f281f2b78fbac34e` 

![image](https://cloud.githubusercontent.com/assets/16284915/17847726/1f51ea68-6882-11e6-9ddf-dec46137c60b.png)

Please help me!

**Comment by khobbits** [comment]
If you are working on the code, and need to modify the css, you need to edit the less files, and less to generate the css files.

The css is a combination of these:
https://github.com/RocketChat/Rocket.Chat/blob/3fb03b5f87246a3210d31788fd3a217c630cdfef/packages/rocketchat-theme/server/server.coffee#L39

The ?<code> is to prevent css caching, 

If you are just wanting to customise the css, you can do so from the administrator panel, as the css entered into the custom css box overrides that of the theme css.

**Comment by geekgonecrazy** [comment]
Please join us in [#dev](https://demo.rocket.chat/channel/dev) to discuss development issues like this.
