### ISSUE TITLE
E-Mail notifications: localize subject line and offer separate prefix

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#4078]
Subject line of E-Mail notifications are English only: "[site name] You have been direct messaged by ... ".
Please consider  i18n, when working on #741 or on #854.
Also, (our rather long) site name is not an ideal prefix, so please offer an extra E-Mail subject line prefix in the administration settings for E-Mail.

Our Rocket.Chat version: 0.37

**Comment by rasos** [comment]
i18n and some design is also needed for self-registration message:   
 `Hello, To verify your account email, simply click the link below.`   
Now the link is even not clickable in most e-mail browsers.

**Comment by pkgodara** [comment]
@rasos Does #7342 meet the requirement. Subject lines are localized, `Administration -> Email -> Subject`. You can use some predefined prefixes or just write whatever you like in the subject line.

**Comment by isabellarussell** [comment]
This issue is now closed as the feature is not on our short term roadmap but may be revisited once other priorities have been addressed.
