### ISSUE TITLE
Indicate number of new messages in channels / private rooms

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#4080]
In the list of PM, a number indicates, how many new messages I have not read yet.
Users have asked for such an indicator also with channels and private rooms.
See also request #3060 for showing level of activity when subscribing channels.

Your Rocket.Chat version: 0.37

**Comment by ggazzo** [comment]
hey @rasos please check that config:
![image](https://user-images.githubusercontent.com/5263975/52482029-4fc6de80-2b97-11e9-8b35-faf8e92de0db.png)

**Comment by rasos** [comment]
Ah yes, meanwhile this feature is available as a setting. Thanks for notifying and closing.
