### ISSUE TITLE
Authenticating does not redirect to home

### ISSUE THREAD

**Issue by scott-wilson** [RocketChat/Rocket.Chat#4084]
Your Rocket.Chat version: 0.37.1

Hello, I set up a server using the AWS guide https://rocket.chat/docs/installation/paas-deployments/aws/ and every time someone has authenticated, they are taken to a loading page, but not redirected to the home page. Refreshing the page in Chrome, or reloading the Android app works around this.

**Comment by JohnCrist1988** [comment]
Confirming bug with Safari 10.0 (12602.1.50.0.2)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
