### ISSUE TITLE
Iframe login always return status code 400

### ISSUE THREAD

**Issue by viniciusrtf** [RocketChat/Rocket.Chat#4086]
Your Rocket.Chat version: 0.37.0 (deployed through https://rocket.chat/deploy -- I can provide installation ID if needed).

I'm trying to implement Iframe login.

API URL: https://xxx/chat/callback
Iframe URL: https://xxx/chat/auth
Method: POST

First thing Rocket.chat seems to do is calling /chat/callback (API URL). In the controller of that route we're registering and logging in the user via Rocket.chat REST API, then we return the token. Example of my console.log():

```
Object {statusCode: 200, content: "{"token":"vXvfkvS8J-wDbNR4NMzMoNK3XKlyzP1gvoz2r5h92D2"}", headers: Object, data: Object}
```

After that, Rocket chat calls /chat/auth (Iframe URL). The controller of that route simply pass the token to the view. The view does the following:

```
window.parent.postMessage({
      "event": "login-with-token",
      "token": "vXvfkvS8J-wDbNR4NMzMoNK3XKlyzP1gvoz2r5h92D2"
    }, "*");
```

Then  Rocket.chat always send the following postMessage to our view:

```
Object {event: "login-error", response: "Unrecognized options for login request [400]"}
```

We also tried "try-iframe-login" and Rocket.chat hits our API URL one more time, but returns the same error.

What am I doing wrong?

Thanks in advance for any insight.

**Comment by rodrigok** [comment]
Hi @viniciusrtf, Are you setting the token in user's record on database correctly?

**Comment by viniciusrtf** [comment]
Since we're using Rocket Cloud, I don't think we have access to the database.

We are assuming that logging in the user via Rocket Chat REST API is equivalent to setting the token directly in the database. Are we wrong about that?

Thanks for the reply.

**Comment by rodrigok** [comment]
@viniciusrtf Yes, unfortunately the iframe login uses a different toke property than the usual token.

We have 2 options here:

1. Add an option to use the default token property in iFrame login, then you can keep your approach
2. Add a new REST Api to create the iFrame token

**Comment by viniciusrtf** [comment]
I'm not sure if you did ask my opinion, but here it is... Option 2 seems more flexible to me. With regard to option 1, if we force the developer to choose between two token properties, we may break something that is already in production.

**Comment by rodrigok** [comment]
@viniciusrtf I was not asking your opinion, I was just thinking loud 😄  

What do you think about this solution: https://github.com/RocketChat/Rocket.Chat/pull/4373

**Comment by viniciusrtf** [comment]
@rodrigok I'm having an issue with this solution. It does authenticate, but always with default system account (admin user), not with the loginToken of a normal user that I pass through postMessage.
