### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by qweqweq** [RocketChat/Rocket.Chat#4088]
i got some problems,and i don't know how to solve is.anyone who can help me?
Your Rocket.Chat version: (make sure you are running the latest)
![image](https://cloud.githubusercontent.com/assets/10056390/17889888/122c13e8-6965-11e6-843c-3e9cac321399.png)

**Comment by qweqweq** [comment]
i can't open the url address.

**Comment by leapswitch** [comment]
Not migrating means it is already up to date. You will need to check firewall rules if you are unable to access. Use netstat -tunlp to check whether rocketchat is listening on port 3000.

**Comment by qweqweq** [comment]
ok,thanks  a lot.
