### ISSUE TITLE
option to disable tones for emojis

### ISSUE THREAD

**Issue by alfredbez** [RocketChat/Rocket.Chat#4093]
Is there an option to disable different tones for emojis? It really annoys me when I try to type `:thumbsup:`, see:

![image](https://cloud.githubusercontent.com/assets/1001186/17897021/e30f588e-6952-11e6-8aaf-4b17851e7f56.png)

**Comment by geekgonecrazy** [comment]
Agreed.  Found my self wanting this as well.  Or maybe set a default tone, and just have it substitute for that tone if available automatically

**Comment by marceloschmidt** [comment]
We fixed by only showing tones after you type the "_".
