### ISSUE TITLE
Migrating from 0.36 to 0.37 E11000 duplicate key error collection

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#4096]
Your Rocket.Chat version: 0.36 migrating to 0.37 and 0.37.1

I believe this is related to slackbridge but I'm not too sure
Your database migration failed:
rocketchat1 | | E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id dup key: { : "slack-C02LKC3LQ.S1418366811-000003" }

> mrplowdan@server:~/rocket.chat$ docker-compose up rocketchat1
Starting mongo
Recreating rocketchat1
Attaching to rocketchat1
rocketchat1    |
rocketchat1    | /app/bundle/programs/server/node_modules/fibers/future.js:278
rocketchat1    |                                                throw(ex);
rocketchat1    |                                                      ^
rocketchat1    | Error: No primary found in set
rocketchat1    |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat1    |     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
rocketchat1    |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
rocketchat1    |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
rocketchat1    |     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
rocketchat1    |     at new Mongo.Collection (packages/mongo/collection.js:102:1)
rocketchat1    |     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
rocketchat1    |     at new AccountsServer (accounts_server.js:16:5)
rocketchat1    |     at Package (globals_server.js:5:12)
rocketchat1    |     at /app/bundle/programs/server/packages/accounts-base.js:1814:4
rocketchat1    |     - - - - -   
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:483:45
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:393:9
rocketchat1    |     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
rocketchat1    |     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
rocketchat1    |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
rocketchat1    |     at [object Object].emit (events.js:95:17)
rocketchat1    |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
rocketchat1    |     at [object Object].emit (events.js:98:17)
rocketchat1    |     at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
rocketchat1 exited with code 0
rocketchat1    |
rocketchat1    | /app/bundle/programs/server/node_modules/fibers/future.js:278
rocketchat1    |                                                throw(ex);
rocketchat1    |                                                      ^
rocketchat1    | Error: No primary found in set
rocketchat1    |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat1    |     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
rocketchat1    |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
rocketchat1    |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
rocketchat1    |     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
rocketchat1    |     at new Mongo.Collection (packages/mongo/collection.js:102:1)
rocketchat1    |     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
rocketchat1    |     at new AccountsServer (accounts_server.js:16:5)
rocketchat1    |     at Package (globals_server.js:5:12)
rocketchat1    |     at /app/bundle/programs/server/packages/accounts-base.js:1814:4
rocketchat1    |     - - - - -   
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:483:45
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:393:9
rocketchat1    |     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
rocketchat1    |     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
rocketchat1    |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
rocketchat1    |     at [object Object].emit (events.js:95:17)
rocketchat1    |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
rocketchat1    |     at [object Object].emit (events.js:98:17)
rocketchat1    |     at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
rocketchat1    | Updating process.env.MAIL_URL
^CGracefully stopping... (press Ctrl+C again to force)
Stopping rocketchat1 ... done
mrplowdan@camosun:~/rocket.chat$ docker-compose up rocketchat1
mongo is up-to-date
Starting rocketchat1
Attaching to rocketchat1
rocketchat1    | Updating process.env.MAIL_URL
rocketchat1    | {"line":"114","file":"migrations.js","message":"Migrations: Migrating from version 55 -> 56","time":{"$date":1471985074364},"level":"info"}
rocketchat1    | {"line":"114","file":"migrations.js","message":"Migrations: Running up() on version 56","time":{"$date":1471985074368},"level":"info"}
rocketchat1    |
rocketchat1    | +----------------------------------------------------------------------------------------------------------------------------------------+
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                                          ERROR! SERVER STOPPED                                                         |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                                     Your database migration failed:                                                    |
rocketchat1    | |  E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id_ dup key: { : "slack-C02LKC3LQ.S1418366811-000003" }  |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                   Please make sure you are running the latest version and try again.                                   |
rocketchat1    | |                                            If the problem persists, please contact support.                                            |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                                    This Rocket.Chat version: 0.37.0                                                    |
rocketchat1    | |                                                     Database locked at version: 55                                                     |
rocketchat1    | |                                                       Database target version: 56                                                      |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                            Commit: 7ab2481546957f5d455a9ceae89de936d7c3e636                                            |
rocketchat1    | |                                                  Date: Mon Aug 15 18:52:47 2016 -0300                                                  |
rocketchat1    | |                                                              Branch: HEAD                                                              |
rocketchat1    | |                                                               Tag: 0.37.0                                                              |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | +----------------------------------------------------------------------------------------------------------------------------------------+
rocketchat1    |
rocketchat1 exited with code 0
rocketchat1    | 
rocketchat1    | /app/bundle/programs/server/node_modules/fibers/future.js:278
rocketchat1    |                                                throw(ex);
rocketchat1    |                                                      ^
rocketchat1    | Error: No primary found in set
rocketchat1    |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat1    |     at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
rocketchat1    |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
rocketchat1    |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
rocketchat1    |     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
rocketchat1    |     at new Mongo.Collection (packages/mongo/collection.js:102:1)
rocketchat1    |     at AccountsServer.AccountsCommon (accounts_common.js:23:18)
rocketchat1    |     at new AccountsServer (accounts_server.js:16:5)
rocketchat1    |     at Package (globals_server.js:5:12)
rocketchat1    |     at /app/bundle/programs/server/packages/accounts-base.js:1814:4
rocketchat1    |     - - - - -
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:483:45
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:393:9
rocketchat1    |     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
rocketchat1    |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
rocketchat1    |     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
rocketchat1    |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
rocketchat1    |     at [object Object].emit (events.js:95:17)
rocketchat1    |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
rocketchat1    |     at [object Object].emit (events.js:98:17)
rocketchat1    |     at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
rocketchat1    | Updating process.env.MAIL_URL
rocketchat1    | Updating process.env.MAIL_URL
rocketchat1    | {"line":"114","file":"migrations.js","message":"Migrations: Migrating from version 55 -> 56","time":{"$date":1471985074364},"level":"info"}
rocketchat1    | {"line":"114","file":"migrations.js","message":"Migrations: Running up() on version 56","time":{"$date":1471985074368},"level":"info"}
rocketchat1    | 
rocketchat1    | +----------------------------------------------------------------------------------------------------------------------------------------+
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                                          ERROR! SERVER STOPPED                                                         |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                                     Your database migration failed:                                                    |
rocketchat1    | |  E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id_ dup key: { : "slack-C02LKC3LQ.S1418366811-000003" }  |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                   Please make sure you are running the latest version and try again.                                   |
rocketchat1    | |                                            If the problem persists, please contact support.                                            |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                                    This Rocket.Chat version: 0.37.0                                                    |
rocketchat1    | |                                                     Database locked at version: 55                                                     |
rocketchat1    | |                                                       Database target version: 56                                                      |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | |                                            Commit: 7ab2481546957f5d455a9ceae89de936d7c3e636                                            |
rocketchat1    | |                                                  Date: Mon Aug 15 18:52:47 2016 -0300                                                  |
rocketchat1    | |                                                              Branch: HEAD                                                              |
rocketchat1    | |                                                               Tag: 0.37.0                                                              |
rocketchat1    | |                                                                                                                                        |
rocketchat1    | +----------------------------------------------------------------------------------------------------------------------------------------+
rocketchat1    | 
rocketchat1    | Updating process.env.MAIL_URL
^CGracefully stopping... (press Ctrl+C again to force)
Killing rocketchat1 ... done

**Comment by teamfighter** [comment]
I have the same issue while migrating from 0.35 to 0.37

**Comment by mrplow** [comment]
Well I managed to get the migration working

The migration error I was recieving:
`rocketchat1 | | E11000 duplicate key error collection: rocketchat.rocketchat_message index: _id dup key: { : "slack-C02LKC3LQ.S1418366811-000003" } |`

Connected to my mongo docker container and then mongo and then from mongo shell switched to db rocketchat and:
```
rocket1:PRIMARY> use rocketchat;
rocket1:PRIMARY> db.rocketchat_message.find( {"_id":"slack-C02LKC3LQ.S1418366811-000003"} )
{ "_id" : "slack-C02LKC3LQ.S1418366811-000003", "msg" : "Regarding the integrated channel <#C02QXJF5E> ", "rid" : "ttFZGg3XYF4mC4gHh", "u" : { "_id" : "CEumNhzFjMGfSMSTC", "username" : "mrplowdan" }, "ts" : ISODate("2014-12-12T06:46:51Z"), "_updatedAt" : ISODate("2016-08-17T01:20:58.104Z") }
```
So that was the message that was causing issues. I know its not important so I removed it.
```
rocket1:PRIMARY> db.rocketchat_message.remove( {"_id":"slack-C02LKC3LQ.S1418366811-000003"} )
WriteResult({ "nRemoved" : 1 })
```
I could then migrate from 55 -> 56

while migrating from 56 -> 57 I had more of these same errors but with many different ids but only one would should at a time. I had to remove it, set lock to false for the migration and restart rocketchat
each time I restarted it a new duplicate key error came up. I removed each duplicate key one at a time as I was restarting rocketchat.
All in all there were about 50 duplicate keys and it took me about an hour to clear them all out.

**Comment by teamfighter** [comment]
How did you set lock to false?

**Comment by mrplow** [comment]
@teamfighter 
```
root@3e1831156eb0:/# mongo
MongoDB shell version: 3.2.9
connecting to: test
rocket1:PRIMARY> use rocketchat;
switched to db rocketchat
rocket1:PRIMARY> db.migrations.find().pretty()
{
	"_id" : "control",
	"version" : 57,
	"locked" : true,
	"lockedAt" : ISODate("2016-08-29T02:11:59.004Z"),
	"buildAt" : "2016-08-17T20:05:41.190Z"
}
rocket1:PRIMARY> db.migrations.update({"locked":true},{$set: {"locked":false}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
rocket1:PRIMARY> db.migrations.find().pretty()
{
	"_id" : "control",
	"version" : 57,
	"locked" : false,
	"lockedAt" : ISODate("2016-08-29T02:11:59.004Z"),
	"buildAt" : "2016-08-17T20:05:41.190Z"
}
rocket1:PRIMARY>
```

**Comment by marceloschmidt** [comment]
I'm glad this has been resolved. I wonder why the migration regex didn't fire up for you two. I'm closing this, but let's keep an eye on any other reports regarding the same issue. Thanks.
