### ISSUE TITLE
0.37.1 Crash when setting avatar image

### ISSUE THREAD

**Issue by imtrobin** [RocketChat/Rocket.Chat#4099]
I'm upgraded to docker version, 0.37.1 , ubuntu 64bit from 0.32.

It will crash when I try to set upload a new avatar image, USE UPLOADED AVATAR. 

I restored from the vm snapshot, and the avatars images were missing.

**Comment by rodrigok** [comment]
@imtrobin It's working for me.

Can you see if there are some errors in your server/client logs?

**Comment by imtrobin** [comment]
I logged in using web version instead of client, I think the whole database is disconnected.

There is no error in the logs, the last line before it crash is setAvatarFromService. I can understand why, the database is no longer connected. How do I connect it again? I use docker.

![rocket chat -2016-08-25 08_42_54](https://cloud.githubusercontent.com/assets/531606/17952782/3d636afc-6aa0-11e6-916c-3fe89b911dc9.jpg)

**Comment by imtrobin** [comment]
An update, I reverted to a snapshot 0.31. The messages are there, but all the images/videos in the chat history are gone.

**Comment by imtrobin** [comment]
I reverted back to a snapshot, and rebooted the server back to 0.32. Everything is working fine, except the avatar images are gone. When I upload an avatar image like above log, rocketchat process is killed. No other error.

**Comment by engelgabriel** [comment]
@iamphill can you please try this with our `develop` branch when https://github.com/RocketChat/Rocket.Chat/issues/4235 gets closed?

**Comment by imtrobin** [comment]
Is this the right way to get the develop branch?
docker pull rocketchat/rocket.chat:develop

I pull it, set the avatar, same immediate server die
