### ISSUE TITLE
Avatars sometimes not rendered in main chat window

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#4100]
Your Rocket.Chat version: demo instance

Description: Sometimes the avatars are just missing in the main chat window. I already did some research to see if it's an client side issue, but it looks like that the server just renders the DOM incorrectly:

![em5wf2kge6zkjdjgt](https://cloud.githubusercontent.com/assets/944459/17934162/348d9c4c-6a17-11e6-9f15-45731fae3dba.png)

---

The DOM is rendered as:

``` html
<button class="thumb user-card-message" data-username="aaron.ogle" tabindex="1"></button>
```

rather than:

``` html
<button class="thumb user-card-message" data-username="aaron.ogle" tabindex="1">
  <div class="avatar">
    <div class="avatar-image" style="background-image:url(/avatar/aaron.ogle.jpg?_dc=0);"></div>
  </div>
</button>
```

Reported by: @Molle500, @TheReal1604, @lunitic and @frdmn

**Comment by Molle500** [comment]
Happends ALOT nowdays for some reason :/

**Comment by frdmn** [comment]
Oh right, I forgot to include you @Molle500 as reporter! 

Edited above :)

**Comment by agentirons** [comment]
This issue suddenly hit our server this morning. One user reported they were missing past a certain time in our message history, and as I was talking to him I switched tabs and came back and suddenly a portion of avatars were missing from my window as well. When I continued chatting the new messages had the avatars back again. I pulled the latest 0.44 release and refreshed and thought I fixed the issue, but they seem to randomly appear or disappear when changing between conversations.

<img width="472" alt="screen shot 2016-10-27 at 09 35 34" src="https://cloud.githubusercontent.com/assets/17654661/19776665/d961c24a-9c29-11e6-9408-433da9b9591d.png">

**Comment by engelgabriel** [comment]
This seem to be fixed on the latest versions. Can confirm if this is still happening?

**Comment by agentirons** [comment]
Haven't run into it in the last few weeks at least.

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/20979113/a0c077c2-bc92-11e6-8250-83c3e8446673.png)

![image](https://cloud.githubusercontent.com/assets/1000217/20979126/ad94af04-bc92-11e6-99a8-16a4512a1d11.png)

**Comment by Molle500** [comment]
I dont think this is happening anymore.

**Comment by engelgabriel** [comment]
It got a lot better, but apparently still happens sometimes on slow machines :(

**Comment by Molle500** [comment]
Hmm happen just now, one users avatar missing. But i´m on a super good computer and 100mbit/s internet @engelgabriel

**Comment by engelgabriel** [comment]
On what browser @Molle500 ?

**Comment by Molle500** [comment]
i think this is fixed. I will close this issue and then re open it if it happen again

**Comment by bakhtizin** [comment]
Happened on our instance today. We had to restart the server. 
```
➔ | Rocket.Chat Version: 0.58.2                            
➔ | NodeJS Version: 4.8.4 - x64                      
➔ | Platform: linux                             
➔ | Process Port: 3000                              
➔ | Site URL: https://whatevertheurlis.com 
➔ | ReplicaSet OpLog: Disabled                        
➔ | Commit Hash: 988103d449                  
➔ | Commit Branch: HEAD        
```
Dev Tools of the browser was showing GET request erros on `https://our-chat-url`/**avatar**/`username_X`**=?_dc=undefined**  404 (NOT FOUND)

**Comment by Hudell** [comment]
Has anybody seen this issue on any newer version?

**Comment by sampaiodiego** [comment]
nope
