### ISSUE TITLE
Feature request: In chat poll system + highlighted question posts by mods

### ISSUE THREAD

**Issue by arkayz** [RocketChat/Rocket.Chat#4102]
It would be pretty neat if there was a polling system in place where users/moderators can post poll questions and get feedback.

It would also be useful to have a way to post "official" questions where the replies would be displayed as a subthread to the question post, all in the chat.

**Comment by rasos** [comment]
Anybody tried with a bot like in Telegram? https://telegram-store.com/blog/telegram-polls/

**Comment by timkinnane** [comment]
I'm going to close this with the suggestion that it really would be best handled as a bot or slash command integration, which is outside the scope for these issues, but we collect them under one issue related to general bots features here: #10174
