### ISSUE TITLE
Allow change username of `rocket.cat`

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#4103]
Change all hard coded places where we use the username `rocket.cat` to find the correct username of user with _id `rocket.cat`, then users can change the bot username.

**Comment by DavePS** [comment]
Im aggree with you +1

**Comment by FibreFoX** [comment]
@rodrigok what about the scenario where the bot gets deleted? Is it even possible/safe to delete that user?

**Comment by graywolf336** [comment]
@FibreFoX It'll get added back into the system when the server gets started again.

**Comment by timkinnane** [comment]
Related #3078, #3869, #4016

**Comment by WebSavvyGuy** [comment]
Any update on this?

**Comment by crisbal** [comment]
i'm also interested on this. It is very confusing for new users to see rocket.cat, it can be easily confused for a real user, especially with the auto-reply feature to message like "Hello", "Goodmorning".

**Comment by justechn** [comment]
I was able to change the rocket.cat username simply by editing the user. But I had to assign an email, password and then log into the bot to change the avatar. It would be great if that was easier.

**Comment by Creanimo** [comment]
Hmmm if I change name and username of rocket.cat the bot answering still appears as rocket.cat.

**Comment by mnlbox** [comment]
@timkinnane Any news about this?

**Comment by timkinnane** [comment]
I haven't done anything about it, but I'm not up to date with changes in release. Personally I'd rather see rocket.cat and the idea of any default user or bot removed from core entirely and have all system notices use a consistent UI that is devoid of personality and doesn't appear to be user in any way.

**Comment by TheOneTwoThreeFour** [comment]
Any news about this yet?

**Comment by cyclops24** [comment]
Part of #8494

**Comment by cyclops24** [comment]
Another hard coded `rocket.cat`: 😞 
https://github.com/RocketChat/Rocket.Chat/blob/develop/server/startup/migrations/v099.js#L17

**Comment by timkinnane** [comment]
I think the specific instances of this issue are resolved. I've opened #10456 for the more general discussion.
