### ISSUE TITLE
Attempt to edit profile after first LDAP login creates a problem on subsequent logins

### ISSUE THREAD

**Issue by unquietwiki** [RocketChat/Rocket.Chat#4106]
**Your Rocket.Chat version:** 0.37.1

_This is possibly related  to https://github.com/RocketChat/Rocket.Chat/issues/3940_

**Steps to reproduce**

* Login as a user the first time with LDAP, regardless if using LDAPuser@LDAPdomain or just LDAPuser.
* Edit profile to correct blank user name entry.
* Warning will appear about "incorrect domain"; can still save/cancel changes though.
* Logout
* Try to login again: this time, you will need to use LDAPuser@LDAPdomain to log back in.

**Comment by rodrigok** [comment]
@unquietwiki Can you paste a print screen of the error?

**Comment by unquietwiki** [comment]
@rodrigok I won't be back at the office for a few days, so I won't be able to do much debugging. The login error was your standard "username or password didn't work" error. One interesting detail: I had followed up with my IT superiors, and not all our LDAP records may have correct email addresses in them. As folks tried the system, it seemed to evolve that some users could get in if they used their email address as a login ID; some the LDAP name; some the LDAP@LDAPdomain name. Overall, it should only be using the LDAP name, not the email address, in our install.

Currently I have the system wiped & reloaded with 0.38 + was trying to get folks to use the system again, but the initial issue has discouraged repeated adoption. :/ My own user may be working fine as far as LDAP goes, but the user editor was still generating an "invalid domain" error.

**Comment by unquietwiki** [comment]
Ack, accidental close

**Comment by rodrigok** [comment]
Can you post an example of your `LDAPdomain`?
Did you set the list of blocked or allowed domains?

**Comment by unquietwiki** [comment]
@rodrigok You know, I had on the original install, and haven't (that I recall) on the new one.

I won't be back at the office for a few days, so I can't get you any immediate feedback. I figure if you're hunting down the profile error, its going to be in one of these two files, but I'm not familiar enough with the code to know where an LDAP-derived account gets saved into the MongoDB originally (I assume its creating a profile based on the first login).

* https://github.com/RocketChat/Rocket.Chat/blob/e882a2a3304b73ef4d90de1fd59e016ef8502b34/packages/rocketchat-ui-account/account/accountProfile.coffee
* https://github.com/RocketChat/Rocket.Chat/blob/e882a2a3304b73ef4d90de1fd59e016ef8502b34/server/methods/saveUserProfile.coffee

**Comment by rodrigok** [comment]
@unquietwiki This error is related with email validation, that's why I need to know your configuration. Feel free to replay when you get back to your work.

**Comment by unquietwiki** [comment]
@rodrigok Acknowledged. A heads up: I hadn't configured email validation on either install, so is that something I should be enabling? Or something I could help you nail down when I do get back in?

**Comment by rodrigok** [comment]
@unquietwiki Just verify these settings and send me an example of your login and domain

**Comment by unquietwiki** [comment]
Hey, I got some more info for you.

* "User not found, or incorrect password": subsequent attempts to login, after the first successful logon.
* Can delete my LDAP user from Rocket.Chat, and log back in successfully the first time.
* "Invalid domain": attempt to change profile settings on a user.
* Per your concern about the domain checks, if I disable the block list, DNS domain check, registration with Auth, and Password Reset options; I can change profile settings without the "Invalid domain" error.
* LDAP search domain is simply "DC=sublevel,DC=toplevel"
* Tried using both "sublevel.toplevel" and "DC=sublevel,DC=toplevel" as default domains, but errors remain.

Currently using the Docker container for hosting Rocket.Chat: unclear where/if there are any log files I can parse for your needs on this.

**Comment by unquietwiki** [comment]
@rodrigok I do see 0.39 came out 2 days ago, with some LDAP fallback thing. Think that'll help any?

**Comment by unquietwiki** [comment]
@rodrigok I had a chance to load 0.39, and revisited my environment. Figure out that if I make sure "Merge existing users" is enabled in LDAP, it will allow me to login again without recreating the account. However, it seems to require a reload/refresh of the chat client to complete those subsequent logon attempts.

**Comment by venserwub** [comment]
+1 I am experiencing all the same issues with a very similar setup. I am using 0.39 and can confirm rocketchat is connecting to LDAP and is finding the User but then fails to log them in.

**Comment by unquietwiki** [comment]
@rodrigok @venserwub Upgrading to 0.40.1 appears to have fixed things: must be the updated LDAP & NodeJS code in 0.40. Thanks! 👍

**Comment by rodrigok** [comment]
@unquietwiki Awesome :)
