### ISSUE TITLE
Snapchat and RC blog.

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#4111]
you liked the idea of connecting the wordpress database with RC, so that RC can be used as facebook chat among users?
And also can add a photo as thumbnail channels?

Well, listen to these others ideas:
a) Each user can create a story like Snapchat, wheres upload photos and videos. Basically it is a chat where only the owner can write, and via javascript and css the last 24h medias will be displayed at full screen as a slide show..

The other idea is that each user can add fields, comments and photos on his profile so that they can also be used as CV or similar.

regards

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I am closing this, as this contains multiple feature requests. If you still want to see some of this implemented, please open seperate issues for each.

Cheers
Thomas
