### ISSUE TITLE
Unable to do I/O operations from incoming webhook scripts section

### ISSUE THREAD

**Issue by vikramjit30** [RocketChat/Rocket.Chat#4112]
I am trying to run the below part of code in the script section of "incoming web hooks" inside method 
" process_incoming_request({ request })"

```
fs = require('fs')
fs.readFile('/etc/hosts', 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  console.log(data);
});
```

but the below error is seen on the RocketChat logs

![error](https://cloud.githubusercontent.com/assets/13905577/17971645/fd1b41d6-6adb-11e6-8d63-70a00b6825fc.PNG)

Basically we cannot do any I/O operation inside the Hook's sandbox.

RocketChat Version: 1.3.0

**Comment by graywolf336** [comment]
This is the expected result in this case, as that'd open a can of worms.

@RocketChat/core what are your thoughts on this?

**Comment by geekgonecrazy** [comment]
Yeah this is javascript we are talking about here.  Expensive I/O operations can block the event loop.  If that happens the chat would lock up on your users

**Comment by MartinSchoeler** [comment]
I will be closing this due lack of updates in a long time. If this issue is still relevant in the latest versions please reopen this.
