### ISSUE TITLE
[sandstorm] Unable to use desktop client with sandstorm instance: Auth needed, try username:password@host

### ISSUE THREAD

**Issue by jinnko** [RocketChat/Rocket.Chat#4114]
Your Rocket.Chat version: 0.36.0
Sandstorm version: 0.178

Steps to reproduce:
1. Install Rocket.Chat in sandstorm.
2. Download Rocket.Chat OSX desktop app via App Store
3. Using the grain URL results in:
   
   ```
   No valid server found at the URL
   ```
4. Using the webkeys link to generate an API url results in:
   
   ```
   Auth needed, try username:password@host
   ```

The expected behaviour is that it's possible to use desktop and mobile apps with the sandstorm instance.

**Comment by Frstknght27** [comment]
Bump

**Comment by fadelkon** [comment]
Probably duplicate of #1352

**Comment by engelgabriel** [comment]
Indeed duplicate of #1352
