### ISSUE TITLE
Message bar bugged on phone

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#4115]
2 buggs on the phone, (at least on iphones). 

If you paste in a longer text than a row the message bar size stays the same and looks super weird.
![1](https://cloud.githubusercontent.com/assets/17712562/17979419/bdd63aca-6afa-11e6-8ee3-c12aed47c049.jpg)

If u then continue to type something the bar pops right.

![2](https://cloud.githubusercontent.com/assets/17712562/17979447/eabce2be-6afa-11e6-9e0d-5dfd6a15bfed.jpg)

And the second bug, If you press on the button down to the right (return) you send the message but the bar remain the same size.
![34](https://cloud.githubusercontent.com/assets/17712562/17979576/9f7e7136-6afb-11e6-8ddb-b16160adbcf9.PNG)

**Comment by skizzors** [comment]
+1 On this issue all our users experience this

**Comment by TheReal1604** [comment]
This bug is also happening at my users and me. :/
