### ISSUE TITLE
Question: Archiving LiveChats?

### ISSUE THREAD

**Issue by michaeltlombardi** [RocketChat/Rocket.Chat#4116]
Your Rocket.Chat version: 0.37.1

Is it possible to archive LiveChats and make them searchable? From my perspective, it would be useful for any agent - not just the livechat managers - to be able to search through the previous chats for issues or recurring questions, etc.

Secondarily, is it possible to pin closed conversations to a channel?

**Comment by graywolf336** [comment]
Currently those are not possible, but if someone is up to adding the new features we'd gladly help them get those features planned out and added. :+1:

**Comment by AlecTroemel** [comment]
Do you think all closed livechat's should be archived & searchable (they are saved in the DB), or would it be something an agent chooses to do (archive) when they close a chat? I've been working on a page that allows any livechat agent to search by phrase through all their chats as well as look through all their conversations. 

<img width="1266" alt="screen shot 2016-08-30 at 4 13 04 pm" src="https://cloud.githubusercontent.com/assets/8620042/18107166/839fd430-6ecc-11e6-8d5e-5514db57c740.png">

Not sure if that's exactly what this is asking for, but it may be a start!

**Comment by michaeltlombardi** [comment]
I think it probably makes the most sense for all closed livechat's to be archived and searchable! What you're working on there looks stellar - is it limited to only the livechats an agent participated in?

Ideally, it would make sense for all agents/managers (in my case, everyone, but we're a small team) to be able to search through all past livechats. That keeps the knowledge available and searchable for the future - if I leave the team, I'd hate for my conversations to leave with me.

The reason for requesting the feature is that livechats generally contain useful information - either that which should make its way into documentation or which should at least be searchable.

**Comment by AlecTroemel** [comment]
Maybe the scope of searches should be a settable (just your own, department, all agents), because I can see both sides. Its nice to have that info available, but some may not like all chats being visible to all agents (especially when there are a lot of agents).

**Comment by michaeltlombardi** [comment]
Configurable is probably the right way to go.

**Comment by marceloschmidt** [comment]
This have been implemented.
