### ISSUE TITLE
Question: How to remove user from channel once it is made private

### ISSUE THREAD

**Issue by lhaig** [RocketChat/Rocket.Chat#4120]
Your Rocket.Chat version: 0..37.1

Hi, How do I remove a user from **all** once I have made a channel private? 
We have a channel that I was asked to make private. I removed the users that were not supposed to be on the channel but when I comment using **@all** I still see the person in the list of recipients.

Can I remove the reference to the user?

Thanks

**Comment by MartinSchoeler** [comment]
Hi @lhaig, if the user that is not in the

**Comment by MartinSchoeler** [comment]
Hey @lhaig! If the user is not in the private room he will not be able to see or be notified of the "@all" message regardless of being in the recipients. Is this that you wanted to know?

**Comment by lhaig** [comment]
Thanks Buddy.
