### ISSUE TITLE
Change password for User error - "Removing the last Admin is not allowed"

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4131]
Your Rocket.Chat version: 0.37.1

If i try to change the password for my test user i get the error "Removing the last Admin is not allowed"
Screenshot:
![image](https://cloud.githubusercontent.com/assets/5877910/18042164/8487e56c-6dbf-11e6-8f23-7bd7c8984418.png)
There are no errors in the server log..

**Comment by MartinSchoeler** [comment]
Hey @TheReal1604  is the test user a adimin? and is the only user in the server?

**Comment by TheReal1604** [comment]
@MartinSchoeler Nope and nope! :-P

I have several other accounts and 1 separate admin account, my testuser is not an admin.

**Comment by alexgleason** [comment]
I'm also having this issue. I have 3 users:

* alex (admin)
* Rocket.Cat
* marykate (user)

When I try to change any of marykate's credentials, it pops up with that error: "Removing the last Admin is not allowed"

The only workaround is to delete the user and add them again with the correct credentials.

**Comment by alexgleason** [comment]
Relevant commit? (19 days ago) https://github.com/RocketChat/Rocket.Chat/commit/03f3db2588fc914569f8e2c2200032d6e17694eb

**Comment by alexgleason** [comment]
Pinging in @timkinnane

**Comment by timkinnane** [comment]
How embarrassing 😝 
Thanks for fixing my bad @sampaiodiego, @graywolf336, @engelgabriel

**Comment by TheReal1604** [comment]
@graywolf336, @engelgabriel, @sampaiodiego Thanks for the really fast bugfix! Awesome.
