### ISSUE TITLE
Exteneded hotkeys support

### ISSUE THREAD

**Issue by iamkarlson** [RocketChat/Rocket.Chat#4132]
Is it possible to add some useful hotkeys like jump to channel or DM, find message? Also, it will be great if it's possible to make compose input to flexible. For example, when press CTRL+Enter than new line, and when press Enter - send message, or vice versa.

Your Rocket.Chat version: (make sure you are running the latest)

**Comment by alfredbez** [comment]
Have you tried <kbd>CTRL</kbd>+<kbd>P</kbd>?

**Comment by iamkarlson** [comment]
@alfredbez Great! Exactly the same what I'm looking for!! But is it any search messages shortcut?

**Comment by iamkarlson** [comment]
Huh, my colleague found that SHIFT+Enter create new line in input box instead of sending message. Is it any shortcuts help like common '?' ?

**Comment by alfredbez** [comment]
see also #3281 and https://rocket.chat/docs/user-guides/keyboard-shortcuts/

You can edit the page here: https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/4.%20User%20Guides/Keyboard-Shortcuts/README.md

**Comment by lucasvanhalst** [comment]
@iamkarlson that is standard behaviour that happens with every textarea input in most browsers.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Looks like what was needed was found :+1:
