### ISSUE TITLE
Question: Having issues with LDAP/AD integration

### ISSUE THREAD

**Issue by marinkovicpetar** [RocketChat/Rocket.Chat#4133]
Your Rocket.Chat version: 0.37.1
For some uknown reason, I cannot get my Microsoft AD users to appear in the Users list. When I try "Test connection", I don't get any errors, and it's the same when I try to sync them.

My settings are the following (sensitive data changed):

host: dc.domain.com
port: 389
domain base: cn=users,dc=domain,dc=com
Use custom domain search
custom domain search: {"filter": "(&(objectCategory=person)(objectclass=user)(sAMAccountName=#{username}))", "scope": "one", "userDN": "CN=Administrator,CN=Users,DC=domain,DC=com", "password": "my_password"}
unique identified field: ObjectGUID
sync data: false
default domain: domain.com

Any help is highly appreciated. Also, I've tried not to use custom domain search filter, and to manually enter username, password, but still I only have first built-in account and the second one I created once I succesfully logged in to my rocket.chat instance.

DC and rocket.chat instance are in same subnet, DC is Windows Server 2008 R2 (which is used with LDAP integration for many other services), and rocket.chat is running as a VM on CentOS 6.

Thanks!

**Comment by khobbits** [comment]
Keep in mind that the userlist does not automatically pull in new users, even when pressing the sync button.
In 37.1, users do have to actually attempt to login, before they appear.
In 38.0, there is an option to import users from AD.

**Comment by pskumart** [comment]
I have the same issue and the rocket chat version is 0.52.0.

Users are not imported, when I press the sync button and instead there is internal server error.

I have the same issue with the latest version of Rocket Chat. Can you help me with the resolution?

Exception while invoking method 'ldap_sync_users' ConnectionError: 79__ldap://10.10.32.17:636 closed at Object.Future.wait (/opt/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15) at LDAP.searchAllSync (packages/meteor.js:213:24) at LDAP.searchUsersSync (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:291:16) at sync (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:740:26) at [object Object].ldap_sync_users (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:1089:17) at [object Object].methodsMap.(anonymous function) (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1064:26) at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:2108:12) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1042:22 at [object Object]..extend.withValue (packages/meteor.js:1122:17) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1041:43 at [object Object]..extend.withValue (packages/meteor.js:1122:17) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1040:48 at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1018:23) at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:880:89 - - - - - at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1277:17 at Array.forEach (native) at Client._onClose (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1272:19) at Socket.g (events.js:260:16) at emitOne (events.js:77:13) at Socket.emit (events.js:169:7) at TCP._onclose (net.js:486:12)
