### ISSUE TITLE
Automate a message with the steam browser protocol

### ISSUE THREAD

**Issue by DavePS** [RocketChat/Rocket.Chat#4135]
Rocket.Chat version: latest

Hey and thanks for the work on RocketChat,

Like I said in the title, I wanted to know how to make a custom message (automatically) every time that a user send a link like 'steam://connect/1.0.0.27:27015' on the chat it will be renamed to "Join the game" for example. All of that for the Steam browser protocol.

Thanks in advance.

**Comment by DavePS** [comment]
up ?

**Comment by jszaszvari** [comment]
>up ?

Don't try and bump your own threads. This isn't a forum.

**Comment by geekgonecrazy** [comment]
This should be possible via an outbound integration.  Please see our docs [here](https://rocket.chat/docs/administrator-guides/integrations)
