### ISSUE TITLE
Audio call sound disappears in certain cases

### ISSUE THREAD

**Issue by MightyPixel** [RocketChat/Rocket.Chat#4140]
Hi, I really like Rocket.Chat+, I think I just found a small bug, there is a way to go around it so it's not such a big deal, but here's how I think it can be reproduced: when I start the application (win 7 x 64, Rocket.Chat+ 1.3.1) and call someone (audio call) - when I go to another menu in the program (like Room Info, or another chat / general channel) the audio stops, when I go back to User info where the audio call interface is the audio starts working again. If I open another window and then go back to Rocket.Chat+ the problem is gone. The best way to get rid of the problem for me was to open Rocket.Chat+ menu and open About Rocket.Chat+, then while I have this About window on my screen I click on Room info - then the audio doesn't stop and after that I can click on every menu without it stopping. It's the same on Win 10 x64.

Another thing is it seems to be hard to call in the first place, when I try to make an audio call it sometimes doesn't work, when someone calls me I click "Yes" that I accept the call but nothing happens, and also sometimes when I click on the icon to call someone nothing happens at all.

Also the rocket.chat server is hosted on Heroku via the "One-Click Deploy" option on the free tier.

Cheers

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
