### ISSUE TITLE
"No users in this role" after adding users.

### ISSUE THREAD

**Issue by Valiantiam** [RocketChat/Rocket.Chat#4141]
Your Rocket.Chat version: 0.37.1

When editing permissions - I cannot see anyone under certain default or custom roles. I can see myself if I add myself to a specific role for a room, however those that have the permission already, or that I add after, don't show up.

They DO get the permissions though. This leaves me with a big problem. I can't remove people from permissions!!

![image](https://cloud.githubusercontent.com/assets/5394853/18068407/c4051b32-6e06-11e6-8f2c-8e1747d0d393.png)

![image](https://cloud.githubusercontent.com/assets/5394853/18068432/e0c919c6-6e06-11e6-9b07-b35e447485d3.png)

![image](https://cloud.githubusercontent.com/assets/5394853/18068489/292bf080-6e07-11e6-9eb1-aab021b00977.png)

**Comment by RichardFoxworthy** [comment]
still a problem for RC v45

**Comment by ggazzo** [comment]
fixed :)
