### ISSUE TITLE
Having issues with LDAP sync

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#4143]
Your Rocket.Chat version: 37.1

Unable to sync users with LDAP

![image](https://cloud.githubusercontent.com/assets/16605816/18076038/f5b04f4e-6e97-11e6-8ba8-e8617ca774fa.png)

**Comment by doctorwho92** [comment]
Also having the same issue, but the log doesn't mention which Email address is duplicated, so troubleshooting is impossible,

rocketchat:ldap sync.js:184 [31mLDAPSync ➔ error Error creating user { [Error: Email already exists. [403]]   error: 403,   reason: 'Email already exists.',   details: undefined,   message: 'Email already exists. [403]',   errorType: 'Meteor.Error' }

**Comment by danpospisil** [comment]
The same issue here - it would be awesome to somehow show in a tool tip which user that is.

**Comment by pyhtongates** [comment]
any solution to this?  having the same issue.  some users can logon via ldap and others get "user not found".   This is after an upgrade from .16 to .52

**Comment by localguru** [comment]
I have seen the error today too, and I'm not sure, but I think this happens if two users have the same email address in LDAP.

**Comment by rodrigok** [comment]
Duplicated of #4477
