### ISSUE TITLE
Backwards migrations cause errors for local development

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#4145]
0.35.0+

While testing different branches and doing local development I'm switching versions a lot, backwards and forwards. It seems the migrations script can only handle forward migrations though, because when I go from 0.37.x back to 0.35.0 (e.g. for instances that were stable with specific hubot-adaptor versions) I get the following error:

```
W20160830-18:00:15.942(10)? (STDERR) /Users/timkinnane/.meteor/packages/meteor-tool/.1.1.10.s5to2l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160830-18:00:15.942(10)? (STDERR)                        throw(ex);
W20160830-18:00:15.942(10)? (STDERR)                              ^
W20160830-18:00:15.970(10)? (STDERR) Error: [Can't find migration version 58]
W20160830-18:00:15.970(10)? (STDERR)     at Object.Migrations._findIndexByVersion (migrations.js:404:8)
W20160830-18:00:15.970(10)? (STDERR)     at Object.Migrations._migrateTo (migrations.js:255:22)
W20160830-18:00:15.970(10)? (STDERR)     at Object.Migrations.migrateTo (migrations.js:179:20)
W20160830-18:00:15.970(10)? (STDERR)     at server/startup/migrations/xrun.coffee:2:24
W20160830-18:00:15.970(10)? (STDERR)     at server/startup/migrations/xrun.coffee:1:1
W20160830-18:00:15.971(10)? (STDERR)     at /Volumes/Code/git/timkinnane/rocket.chat/.meteor/local/build/programs/server/boot.js:242:10
W20160830-18:00:15.971(10)? (STDERR)     at Array.forEach (native)
W20160830-18:00:15.971(10)? (STDERR)     at Function._.each._.forEach (/Users/timkinnane/.meteor/packages/meteor-tool/.1.1.10.s5to2l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160830-18:00:15.971(10)? (STDERR)     at /Volumes/Code/git/timkinnane/rocket.chat/.meteor/local/build/programs/server/boot.js:137:5
```

I can fix it using `meteor reset` but that loses everything and I have to re-create users etc.
It's not a problem in production because everything is blown away by the build tool and mongo is external so it persists. So its not a major issue, just wondering has anyone else encountered this, is there a better way to deal with it?

**Comment by lucasvanhalst** [comment]
just set the migration version to whatever you want in the database

**Comment by timkinnane** [comment]
Thanks @lucasvanhalst. Where would I run that? I can't call it from Meteor shell or console because startup doesn't complete. If I need to make file changes each time I check out a different version, that's a little tedious, but I guess it could work as a temp solution.

That seems to be the purpose of the `RocketChat.Migrations.migrateTo` method run on startup. I'm wondering if there's something missing in its logic that should be automatically detecting version and migrating down. There's a migrate 'down' method in migrations.js, but it seems its not being used.

**Comment by timkinnane** [comment]
Actually getting the same error on Heroku now. This instance uses persistent external (mlab) mongo, so I can't just `meteor restart` it. I wasn't even changing version (both were 0.37.1), just  deploying a feature branch to test. The branch builds and works locally, but can't deploy.

```
31 Aug 2016 12:16:09.875 144 <190>1 2016-08-31T02:16:09.588244+00:00 app web.1 - - [34mrocketchat:theme ➔ stop_rendering[39m 2090
» 31 Aug 2016 12:16:11.610 124 <45>1 2016-08-31T02:16:11.520379+00:00 heroku web.1 - - Process exited with status 8
» 31 Aug 2016 12:16:11.630 94 <190>1 2016-08-31T02:16:11.281181+00:00 app web.1 - -
» 31 Aug 2016 12:16:11.630 173 <190>1 2016-08-31T02:16:11.281302+00:00 app web.1 - - /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:245
» 31 Aug 2016 12:16:11.630 110 <190>1 2016-08-31T02:16:11.281722+00:00 app web.1 - - throw(ex);
» 31 Aug 2016 12:16:11.630 107 <190>1 2016-08-31T02:16:11.281726+00:00 app web.1 - - ^
» 31 Aug 2016 12:16:11.630 134 <190>1 2016-08-31T02:16:11.353459+00:00 app web.1 - - Error: [Can't find migration version 58] at Object.Migrations._findIndexByVersion (migrations.js:404:8) at Object.Migrations._migrateTo (migrations.js:255:22) at Object.Migrations.migrateTo (migrations.js:179:20)
» 31 Aug 2016 12:16:11.630 143 <190>1 2016-08-31T02:16:11.353464+00:00 app web.1 - - at server/startup/migrations/xrun.coffee:2:24
» 31 Aug 2016 12:16:11.630 142 <190>1 2016-08-31T02:16:11.353467+00:00 app web.1 - - at server/startup/migrations/xrun.coffee:1:1
» 31 Aug 2016 12:16:11.696 161 <190>1 2016-08-31T02:16:11.353468+00:00 app web.1 - - at /app/.meteor/heroku_build/app/programs/server/boot.js:242:10
» 31 Aug 2016 12:16:11.696 123 <190>1 2016-08-31T02:16:11.353469+00:00 app web.1 - - at Array.forEach (native)
» 31 Aug 2016 12:16:11.696 218 <190>1 2016-08-31T02:16:11.353470+00:00 app web.1 - - at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11)
» 31 Aug 2016 12:16:11.696 160 <190>1 2016-08-31T02:16:11.353471+00:00 app web.1 - - at /app/.meteor/heroku_build/app/programs/server/boot.js:137:5
» 31 Aug 2016 12:16:11.802 134 <45>1 2016-08-31T02:16:11.555761+00:00 heroku web.1 - - State changed from starting to crashed
```

**Comment by lucasvanhalst** [comment]
You would run that on the mongodb console. You can just connect to it using a mongodb client (just the command 'mongo' should do if you have it installed)

**Comment by timkinnane** [comment]
Doi! Of course, thanks @lucasvanhalst.
I think the issue should stay open though, until some change allows backward migrations to be handled more gracefully.

**Comment by dimti** [comment]
Hello

I reinstall rocket chat to 0.36.1 from my archlinux aur packages.

And after start app i see same error

    Error: [Can't find migration version 57]

I use our solutions with udate mongo db record from console and i try to update from robomongo gui, but, after start application rocket chat, - locked field rewrite to true

http://www.zimagez.com/zimage/2016-09-1008-44-08.php

http://www.zimagez.com/zimage/2016-09-1008-44-48.php

And. how to fix these errors: http://www.zimagez.com/zimage/2016-09-1008-45-40.php ([Error: error evaluating function `mix`: Object [object Object] has no method 'toHSL']) ?

**Comment by dimti** [comment]
Sorry. More..
New app on adnroid very not worked for me. GUI interface in android app - is confuse. Connection on my server not be established (Error: abort, abort). But from browser and from desktop app connection is work.

May be, after update (and successfully starting chat) porblems if fixed with connection from mobile android app..

How i can see current rocket chart version on my installation in filesystem, where version of chat in files, starting in bundle dir?

**Comment by engelgabriel** [comment]
The problem with migrating downwards, is that when you run a older version, the source code for that migration does not exists... so it is impossible-ish to solve the problem. We would have to have the migration scripts on an external package, that would always be imported as the latest version, with all the migration scripts for `up` and `down` migrations. but this would still be a problem for our pre built distribution, and the modules are pre-packaged.

You can always just delete the single control document on the migrations collection, rather than the whole DB.

```
db.migrations..drop();
```
