### ISSUE TITLE
Ability to reduct, edit or remove emoji reactions

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#4148]
Your Rocket.Chat version:  0.37.1

Our entire message can be edited except for attached emoji reaction(s).

Just for consideration due to recent need to edit a mis-fired reaction.

**Comment by djeber** [comment]
i think we should have an option to set and limit reactions like facebook reactions for example but giving admins the option to choose and set the reactions they see them good for their community

**Comment by marceloschmidt** [comment]
@Sing-Li you can remove a reaction by clicking on it again. Is this still an issue?

**Comment by libertizer** [comment]
It is however no joke that the lead developer of google material web, Kenneth G. Franqueiro has left Google, I'm interested what this means for the project. I'm actually developing a real project in google material web and I actually like it :-) The only missing part is the datatable

**Comment by pbexiga** [comment]
Hello,

This would be useful, as an admin, to be able to limit which reactions people can use on specific posts. Or at the very least, as an admin be able to remove certain reactions from a post.

Is this possible?
