### ISSUE TITLE
Users cannot register after being auto added by slack-bridge

### ISSUE THREAD

**Issue by phutchins** [RocketChat/Rocket.Chat#4149]
Your Rocket.Chat version: 1.3.1

After a user is added automatically by the slack-bridge, the user cannot register as it says that they are already registered.

If there is some other way for them to  register, it is not clear.

**Comment by xenithorb** [comment]
Hi! Welcome, 

The Rocket.Chat version we're looking for is of the server. i.e. 0.37.0, 0.37.8, etc. 

I do believe this is an extension of #3300

**Comment by engelgabriel** [comment]
@marceloschmidt what is the expected behaviour here? Should just users request a new password? Can we automate that for active user? Like just sending them a welcome email with a temp password when they get imported?

**Comment by phutchins** [comment]
Should have grabbed server version. It is 0.37.1.
@marceloschmidt & @xenithorb, I would expect to be able to attempt to register, then to be notified that I've already had a user created for me from X service (Slack in this case) and all I need to do is verify my email address and set a password.

Since the user isn't already expecting to have an account, they probably should be lead through a very similar process to regular registration.

Or maybe if the slack oauth integration is turned on, allow them to choose.

@xenithorb It does look like #3300 might be part of the answer for this however it doesn't capture the desired user experience/flow. 

@engelgabriel I would think that we would want to let the user know that they have a user account, send them an email with a link to set their password and telling them to ignore or notify an admin if they did not attempt to register for the chat...

**Comment by phutchins** [comment]
Any luck or word on movement for this? I'm pushing our company to move to Rocketchat but this is blocking us as we've run the bridge and none of our users can register without me manually enabling them and then instructing them to reset their password... 

My temporary solution is to look into writing a script to update all users in the DB to be activated and have a password that can be reset so they can click the reset password button and log in. I'll have to add something to direct Slack users that they need to do this instead of log in.

Thoughts?

**Comment by marceloschmidt** [comment]
@phutchins I'll work on this today and maybe tomorrow if needed. We'll have a solution asap.

**Comment by phutchins** [comment]
Awesome, thank you for this @marceloschmidt !!!
