### ISSUE TITLE
Deleting the first message of a set (sometimes) also delete the avatar

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#415]
This was an old bug, but back under some (not reliably reproducible) situations.

If you type two messages in rapid succession, and then delete the first one, sometimes the avatar next to the first message also disappears.

[Observed on Electron Mac app]

UPDATE: .... but after a few minutes, it fixes itself

**Comment by rodrigok** [comment]
@Sing-Li I made some changes to force re-render of messages around of the deleted message I hope that solve this problem :)

https://github.com/RocketChat/Rocket.Chat/commit/f012ee033067fc66526d647470f40555ac4ac8e8

**Comment by Sing-Li** [comment]
As of 11 AM (UTC - 4)  I am no longer fast enough to cause it to happen  :smile:
