### ISSUE TITLE
Admin view should disappear when you click the X on the admin menu

### ISSUE THREAD

**Issue by phutchins** [RocketChat/Rocket.Chat#4153]
Your Rocket.Chat version: 0.37.1

When you click the X in admin, the admin view should then disappear but you have to click on a channel to remove that view. 

It should then display the most recently viewed channel.

**Comment by Molle500** [comment]
@phutchins 

Made an issue about this already. #3195

**Comment by phutchins** [comment]
Ok, thanks @Molle500! I searched but didn't see it. Much appreciated.
