### ISSUE TITLE
Mautic Integration Guide

### ISSUE THREAD

**Issue by eirua** [RocketChat/Rocket.Chat#4154]
Hey guys,

Would love some guidance on integrating Rocket.Chat with Mautic. I see you have something planned for Zapier.  [Mautic has a beta invite out](https://zapier.com/developer/invite/43460/9a4d44ae0e3aff741b647237a2a6883e/).

I'm a beginner but I tried with a webhook from Mautic to Rocket.Chat directly. The tests succeed but I just get empty posts in my channel with no content (just avatar and user). Also tried a zapp (Mautic > Rocket.Chat webhook) but same thing after a bunch of jangling magic for both. I tried the example script but not really sure how to modify it properly at my level. Assume this is why I'm having trouble - I'm not using a proper script?

Two wicked cool open source projects here.  Happy to help document.

**Comment by graywolf336** [comment]
@eirua We are working on our Zapier integration and getting it extremely close to being invite ready, if you're still interested connect with me on the demo server via a direct message and we'll discuss it. 👍

**Comment by eirua** [comment]
Awesome. You mentioned in another thread I already hit you up a few days ago there.

**Comment by graywolf336** [comment]
@eirua I apologize for that, I have been heads deep in it that I didn't pay attention to the username. 😆

**Comment by eirua** [comment]
Hey no worries. I never did get an invite or a discussion about it. Still interested.

**Comment by graywolf336** [comment]
@eirua We're still working on the REST APIs needed to get this working, which just landed in the latest version so I will resume working on Zapier this week and get you an invite. :+1:

**Comment by graywolf336** [comment]
We are now ready to test out Zapier, so if someone is interested in testing it [consider yourself invited](https://zapier.com/developer/invite/32270/7c3feadc825db6ae9023ea2983e88875).

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  

Please move discussion to [forum](https://forums.rocket.chat) in the community support or feature request category
