### ISSUE TITLE
LDAP Configuration

### ISSUE THREAD

**Issue by akashkaveti** [RocketChat/Rocket.Chat#4160]
I have tried to configure Our Rocketchat with LDAP configuration. When I tested the connection it seems fine, but when I tried to login to rocketchat with my LDAP credentials I got an error that the user couldn't be found.

**Comment by jszaszvari** [comment]
What type of LDAP Server is it? 

Active Directory?
OpenDirectory (Apple)?
OpenLDAP?

**Comment by akashkaveti** [comment]
Open LDAP

**Comment by akashkaveti** [comment]
My configuration for LDAP,

    LDAP_Enable = True
    host= ldap.jumpcloud.com
    LDAP_Port = 636
Connection timeout= 600000
idle timeout= 600000
encryption=ssl/ldaps
Domain base= OU=users,O=org.id,DC=jumpcloud,DC=com

custom domain search = {"filter": "(&(objectCategory=person)(objectclass=inetOrgPerson)(memberOf=CN=rocket-chat-group,OU=users,O=org.id,DC=jumpcloud,DC=com)(uid=#{username}))", "scope": "sub", "userDN": "uid=binduser,ou=users,o=org.id,dc=jumpcloud,dc=com", "password": "password"}

My connection seems fine, when I sync users there weren't any errors but users are not synced. 
When I try to login with my LDAP credentials, I got User not found error.
