### ISSUE TITLE
How is Rocket.Chat better than Mattermost?

### ISSUE THREAD

**Issue by tgy** [RocketChat/Rocket.Chat#4161]
I just stumbled upon this project and it sounds interesting!

I am using Mattermost at work, I'd like to know how Rocket.Chat compares to Mattermost, how it is better (if it is). I checked the issues and couldn't find anything about this so I think it's good to clarify this!

**Comment by JackDragon** [comment]
http://www.akitaonrails.com/2016/08/13/choosing-mattermost-over-rocket-chat-and-slack
Here is why some people choose mattermost over rocketchat. Rocketchat is heavy on the client and is limited to mongo for now, though it's supposed to be db agnostic so postgres can come later.

A counter argument for rocketchat is that it's more flexible on more platforms, built on meteor/electron.

**Comment by jszaszvari** [comment]
Mattermost also costs $$$ for any sort of enterprise features like Rebranding or AD/LDAP Integration

**Comment by kaos** [comment]
AD/LDAP was the single most important feature that had us switch from Mattermost, as well as better HA support. So far, it's been a pleasure to work with, but there are some nagging glitches in our setup (sharding issues, probably related to GridFS, and sporadically too large avatar images).

**Comment by reitzig** [comment]
Mattermost seems to support AD/LDAP now.

**Comment by ssbarnea** [comment]
I think that a great way to achieve a good comparison would be with something like https://www.slant.co/topics/4554/~open-source-alternatives-to-slack 

PS. I am not affiliated with them, just a happy user. It works like a wiki, were people can add properties values so you can compare two different products or solutions.

**Comment by localguru** [comment]
@reitzig AD/LDAP is only supported in the Enterprise E10 version, SAML in Enterprise E20. So those features are not open source, which was a no go to me for mattermost.

**Comment by Rohlik** [comment]
@tgy Mattermost doesn´t have support for group video calls and for screen-sharing.

**Comment by abalter** [comment]
@Rohlik V3.8 (April 17) is _supposed_ to have 1:1 video, with group video supported by plugins.

I don't know about others, but I have found Mattermost very hard to deal with as a (prospective) customer. Very slow to respond. Even at the basic E10 enterprise level they only offer ticket support and at E20, email support. To get phone support is VERY expensive. We will probably go with them because we have been testing the Team edition for quite a while.

Also, our sysadmin is having trouble migrating from the gitlab integrated mattermost (which we have been testing on) to the standalone. They use different databases! As far as I can tell, there is not even an export feature like slack has so that we could export and reimport.

In my emails to Rocket.Chat, I have found them VERY responsive, and much more flexible. That being said, Mattermost does seem to be a bigger and more established organization. But Rocket.Chat might be the better product.

**Comment by SISolutions** [comment]
Have you ever tried Zulip? 
https://zulipchat.com/

 Zulip is 100% open source software, built by a vibrant community of hundreds of developers from all around the world. With 100,000 words of developer documentation, a high quality code base, and a welcoming community, it’s easy to extend or tweak Zulip.

Zulip has a significantly larger and more active development community than other modern open source group chat solutions like Mattermost, Rocket.Chat, and matrix.org. 

Give it a try ;)

**Comment by kaos** [comment]
Zulip, never heard of it before. Doesn't mean it's bad, but makes one wonder what they have to back up their claim for "Zulip has a significantly larger and more active development community than other modern open source group chat solutions like Mattermost, Rocket.Chat, and matrix.org."

Looking at their stars at github (5.9k).. they're rather far behind both that of mattermost (11.7k) and rocket chat (15.8k).

I stay clear of products being marketed under false pretence, even if it is for neglect of keeping their information up-to-date and accurate. (in case their statement was true at some point.)

Also, their LDAP integration is not included in the free open source version, according to their price plan. 👎

**Comment by abalter** [comment]
I was looking at matrix.org. Seems like that is more of a meta-system for building chat apps. I'm not sure how it fits in, and they don't explain it well on the website. I guess you are just supposed to be a hacker and "know."

**Comment by kaos** [comment]
Oh, matrix is seriously cool. It's an open standard for decentralized encrypted chatting with bridges to other communication technologies. It strikes my nerdier side.. no idea if any of the available servers offer any LDAP integration..

As end-user all you need is a client and connect to a matrix server.
But there are *alot* of projects implementing various client or server parts of the matrix eco system.
https://matrix.org/docs/projects/try-matrix-now.html has a long list of these..

**Comment by abalter** [comment]
That's just the thing. I'm not nerdy enough to understand what that means or how I would even use it.

It may be cool, but could my company use it as a slack replacement? If so, why would I chose it over the others.

I don't see that answered on their website.

**Comment by dbeuchler** [comment]
A big argument agains Mattermost is the missing fallback of websockets. In our company, websockets are blocked around the world.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi folks,

I'm not meaning to interrupt this discussion, yet it'd be awesome, if you could continue it over at https://forums.rocket.chat, because this is actually the bug tracker and there is no bug involved here. Thank you for understanding. :)

Cheers
Thomas
