### ISSUE TITLE
Add possibility to faster switch conversation

### ISSUE THREAD

**Issue by Franziskus1988** [RocketChat/Rocket.Chat#4168]
I think a cool feature would be a possiblity to fast switch conversations without using the mouse.

Like the CTRL+P functionality in VS Code or F2 (Quick command) in Vivaldi. 

Alternativ would be a searchbar in the conversations overview bar. 

Your Rocket.Chat version: 0.38.0

**Comment by MartinSchoeler** [comment]
Hey @Franziskus1988 there is a ctrl+p shortcut, take a look at this https://rocket.chat/docs/user-guides/keyboard-shortcuts/

**Comment by graywolf336** [comment]
Closing as it is part of Rocket.Chat already, the link Martin linked to shows that :+1:

**Comment by Franziskus1988** [comment]
Sorry guys. I've read the docs mutliple times, but always misted that.
