### ISSUE TITLE
BUG: 400 When Trying To Enable Bad Word Filter

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat#4170]
Your Rocket.Chat version: (make sure you are running the latest)

If you set the bad word filter to true, you get a 400 error.

LOG BELOW:
Exception while invoking method 'saveSetting' Error: Match error: Expected string, got boolean     at check (packages/check/match.js:33:1)     at [object Object].Meteor.methods.saveSetting (packages/rocketchat_lib/server/methods/saveSetting.coffee:5:3)     at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)     at livedata_server.js:708:19     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:706:40     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)     at livedata_server.js:704:46     at tryCallTwo (/app/.meteor/heroku_build/app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5) 
I20160901-16:13:10.437(0) Sanitized and reported to the client as: Match failed [400]

**Comment by graywolf336** [comment]
This was just fixed in beta builds.
