### ISSUE TITLE
Font Awesome Icon Support

### ISSUE THREAD

**Issue by NonlinearFruit** [RocketChat/Rocket.Chat#4171]
Incorporating [Font Awesome's](http://fontawesome.io) awesome icon set would be great, especially if the normal `:emoji:` worked with it. Something like `:fa-github:`. Their [license](http://fontawesome.io/license/) says that it is free for company and open source projects. [Here](https://github.com/FortAwesome/Font-Awesome) is their github repo.

Somewhat related to the Custom Emoji request: #4167

**Comment by graywolf336** [comment]
@nokobon by chance, how hard do you think this would be? I only ask you since you recently have been in the emoji code..

**Comment by nokobon** [comment]
I don't think it would be very hard. In my pull request, I adapted the original rocketchat-emojione package to work as a common package for supporting multiple packages.
What I think would be nice is a server setting to enable/disable certain packages. That would allow, for example, disabling emojione and exclusively using Font Awesome.

**Comment by graywolf336** [comment]
You could add settings to allow the enable/disabling of certain types of emojis.

**Comment by RichardFoxworthy** [comment]
This will be particularly useful since the Rocket Chat UX seems to actually use font awesome icons? Or at least icons that look extremely similar to those in font awesome.

This would help simplify user support messaging - you could embed UX icons into messages with explanations on how to use them

Font awesome does of course also include tons of other awesome icons that are fun and useful in their own right!

**Comment by NonlinearFruit** [comment]
@nokobon What would a custom emoji package for Font Awesome look like? Is it currently possible?

**Comment by NonlinearFruit** [comment]
Is using Font Awesome possible now that there is custom emojis?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I'll  close this issue as the request is to have custom emoji-**sets** which is currently not possible. Please have a look at #1838 for this and use this issue from now on.

Cheers
Thomas
