### ISSUE TITLE
DMs causing lag

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4174]
Your Rocket.Chat version: v38

Some of the people that runs roleplaying scenes for my chat seems to have massive amounts of lag when they start multiple dms with people to the point where they get disconnected from the chat.

I am sure its not their computers because this is one of the computers having issues and not how few DMs they have open to cause this issue.
http://i.imgur.com/LtR6Rgj.png

**Comment by geekgonecrazy** [comment]
This sounds like it is related to: #31 Please add your vote there
