### ISSUE TITLE
Bad character encoding in name/username during first SAML login

### ISSUE THREAD

**Issue by baierjan** [RocketChat/Rocket.Chat#4176]
Your Rocket.Chat version: 0.38.0

Hello, I found a problem with SAML integration. We use SSO solution, which can successfully send an login response to Rocket.Chat together with some attributes to populate name and e-mail. However, there  is an issue with encoding if the name contains accented characters.

Example value of string from SAML: C\u0004B\fernC\u0003B=
Stored in Rocket.Chat: CBernCB=
Correct value should be: Černý

I would like to know on which end of the SAML protocol to look for the error. Any hints welcomed. Thanks!

**Comment by pierre-lehnen-rc** [comment]
Well, unfortunately this one slipped by without attention for too long. I'm going to close it because it doesn't seem to be a bug in our end, as the example value was already using invalid escaped characters.
