### ISSUE TITLE
Screensharing

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#418]
Does the current video feature supports screensharing? 
If not, is it among the planned features?

**Comment by Sing-Li** [comment]
Not yet.  

And yes it is planned - webrtc styled video screen sharing.   Might you be able to help?

**Comment by rockneverdies55** [comment]
Glad to hear. That will be very nice feature to have. Especially in development environments, screensharing is vital between developers, between developers and testers or product managers etc...

**Comment by inderpreetsingh** [comment]
https://github.com/fishdude/meteor-RTCMultiConnection this needs to be updated and then screen can be shared.

**Comment by engelgabriel** [comment]
maybe @muaz-khan could help us?

**Comment by muaz-khan** [comment]
Simply replace [this file](https://github.com/fishdude/meteor-RTCMultiConnection/blob/master/lib/RTCMultiConnection.js) with [`https://cdn.webrtc-experiment.com/RTCMultiConnection.js`](https://cdn.webrtc-experiment.com/RTCMultiConnection.js).

It will be using this chrome-extension:

* https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk

However you can deploy or install local files as well:

* https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture

If you've deployed it on Google App Store then simply put your extension-id [here](http://www.rtcmulticonnection.org/docs/DetectRTC/#DetectRTC.screen):

```javascript
connection.DetectRTC.screen.extensionid = 'your-app-store-extensionid';
```

Firefox-based plugin can be found here:

* https://github.com/muaz-khan/Firefox-Extensions

BTW, it (both Chrome/Firefox) requires HTTPs.

**Comment by barhum** [comment]
I would love to help with this feature.

**Comment by rodrigok** [comment]
Hi @barhum, thanks for your interest

You can help us with this issue in this branch https://github.com/RocketChat/Rocket.Chat/tree/webrtc

**Comment by Sing-Li** [comment]
Implemented in #989.   Closing this issue.

**Comment by jonaskello** [comment]
The docs does not seem complete: https://rocket.chat/docs/user-guides/screensharing

I'm tying to find a way to test screen sharing at the demo site but I cannot find anyway to do it.

**Comment by jonaskello** [comment]
Found it, it is in the video conference feature so you need to start that first, then do screen sharing from there.

**Comment by mborhade** [comment]
In my case audio not working after sharing screen.
