### ISSUE TITLE
Google doesnt provide GCM API keys anymore

### ISSUE THREAD

**Issue by linjan** [RocketChat/Rocket.Chat#4182]
Hello!

1 September Google announced this (@ https://developers.google.com/cloud-messaging/ )
"Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure. See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future."

What I should use it Rocket.Chat PUSH preferences? Will it be supported by current rocket.chat codebase?

**Comment by rodrigok** [comment]
@linjan We do not support FCM yet, but google still does support for GCM

**Comment by linjan** [comment]
@rodrigok is there any way to get GCM key?

**Comment by rodrigok** [comment]
@linjan Yes, as we always did, https://github.com/raix/push/blob/v3.x/docs/ANDROID.md

**Comment by linjan** [comment]
@rodrigok Now its not possible, because Google forces FCM. Link from API list leads to https://firebase.google.com/docs/cloud-messaging/
![Google API List](https://dl.dropboxusercontent.com/1/view/ut604smnjb80ks5/Apps/Shutter/918bff62.png)

**Comment by rodrigok** [comment]
![](https://d17oy1vhnax1f7.cloudfront.net/items/0u27322L0b2F0u3F2y3a/Screen%20Recording%202016-09-03%20at%2011.32%20AM.gif)
![](https://d17oy1vhnax1f7.cloudfront.net/items/0z1l0O232F3E1409443K/Screen%20Recording%202016-09-03%20at%2011.33%20AM.gif)
![](https://d17oy1vhnax1f7.cloudfront.net/items/2C330p2l0m1q2c0i1Q3A/Screen%20Recording%202016-09-03%20at%2011.34%20AM.gif)

**Comment by linjan** [comment]
Thanks!

**Comment by juckeltour** [comment]
Unfortunately, this does not work anymore. Does anybody get this running?

**Comment by rodrigok** [comment]
@juckeltour Its working for me, we are you getting this log?

**Comment by juckeltour** [comment]
> *Why we need to go external:*

"Unauthorized" is the only word that I got in the logs of RC (highest log level).

**Comment by rodrigok** [comment]
@juckeltour Which RC version are you using?
Can you enable the `Push debug`, restart it and try again?

**Comment by bios-ben** [comment]
I'm running into the same thing:
```
Push: Send message "@ben" via query { userId: 'III' }
send to token { gcm: 'XXX' }
sendGCM [ 'XXX' ] { _id: 'JJJ',
  createdAt: Mon Oct 10 2016 15:18:57 GMT-0700 (PDT),
  createdBy: '<SERVER>',
  from: 'push',
  title: '@ben',
  text: 'This is a push test message',
  sound: 'chime',
  apn: { text: '@ben:\nThis is a push test message' },
  query: { userId: 'III' } }
Create GCM Sender using "KKK"
A:Send message to: XXX
Push: Sent message "@ben" to 0 ios apps 1 android apps
Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet...
Unauthorized
ANDROID: Result of sender is null
```
I don't know what affects privacy so I changed the big keys. III and JJJ are short ids from google, KKK is my server key that's correct what its in the console, and XXX is a huge gcm hash repeated multiple times in there.

**Comment by juckeltour** [comment]
In my case, this fault has disappeared some day, but it comes up from time to time. Maybe there is something wrong with the gateway or with GCM/FCM.

**Comment by bios-ben** [comment]
Well I set the gateway to match the domain of our RC server ... but it's behind a firewall and such so does that mean maybe there's some ports forwarding or something extra that needs to happen? I don't know the pupose of the "gateway" in the settings.

**Comment by fabian-z** [comment]
@bios-ben See my comment in #4861, maybe importing your GCM project into Firebase will solve the Unauthorized error for you.

**Comment by bios-ben** [comment]
Thanks @fabian-z but we decided to just switch over to Mattermost because the RC backend code and clients both really had a lot of leaking problems, and MM seems to have a bit more polish even if it's a bit uglier. So I can't test out your solution anymore.
