### ISSUE TITLE
placeholder overlaps with prepopulated text in login page

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#4183]
![placeholder-overlap-text-rocketchat-login](https://cloud.githubusercontent.com/assets/4588562/18217180/4e16030c-7129-11e6-9a5c-d74a2f6b8c27.png)

Textbox placeholders in login page overlap its content till clicked to enter data...

**Comment by MartinSchoeler** [comment]
@rockneverdies55 what version are you using? and in which browser?

**Comment by mide** [comment]
I also see this problem on `demo.rocket.chat`, and I think that's running `0.39.0`. 
<img width="591" alt="screen shot 2016-09-13 at 1 49 23 pm" src="https://cloud.githubusercontent.com/assets/546518/18485020/0394dd7e-79b9-11e6-81b1-a9db9c30fd3a.png">

**Comment by lunitic** [comment]
See this Issue to,, Chrome latest and win10 x64.

**Comment by MartinSchoeler** [comment]
I'm pretty sure that this bug was fixed, if you experience this in the latest version again please reopen this issue with updated details. Thanks!
