### ISSUE TITLE
LiveChat widget still appears even when offline and "display offline form" is set to False

### ISSUE THREAD

**Issue by mixrat** [RocketChat/Rocket.Chat#4184]
Rocket.Chat v0.37.1

I have set "Display offline form" to False in both the Administration->LiveChat menu and the LiveChat->Appearance menu but the Offline form still appears when LiveChat is offline...

![selection_513](https://cloud.githubusercontent.com/assets/20234985/18222331/aea311dc-71e8-11e6-9430-39246dc2edba.png)

![selection_514](https://cloud.githubusercontent.com/assets/20234985/18222335/b80a3f48-71e8-11e6-8331-bf791bf9f85d.png)

![selection_515](https://cloud.githubusercontent.com/assets/20234985/18222336/c020c0a8-71e8-11e6-9428-2a739c206c45.png)

**Comment by mixrat** [comment]
Still the same on 0.48.2.

**Comment by sampaiodiego** [comment]
on my test, the form itself is not showing, but the widget (the gray bar) is.

is it what is happening to you?

**Comment by mixrat** [comment]
That is correct. Is this the intended behavior? I thought that disabling the offline form would hide the widget altogether. That is how I would like it to function anyway.

**Comment by sampaiodiego** [comment]
I agree with you. I was just trying to make sure we are seeing the same issue.

I'm already working on a fix :wink:
