### ISSUE TITLE
Mobile push notifications not working for "All Messages"

### ISSUE THREAD

**Issue by yarone** [RocketChat/Rocket.Chat#4185]
Rocket.Chat version: latest. Issue with notifications on iOS. 

When changing the notification setting for a particular channel to "Mobile Push: All Messages" we are not getting alerts for all messages.

Mention alerts are working, however.

**Comment by yarone** [comment]
Posted this issue per Rodrigo's request.

**Comment by TheReal1604** [comment]
@yarone Can completely confirm that. I had some strange situations. For example: Started with version 0.17.0 and created a channel with incoming integrations for weather. After all updates I got new messages via push, but since I switched the button for mobile push messages from off to on (just for debugging purposes) I get no push messages anymore.. :( In all new created channels I get the desktop notifications but no push messages. 

It would be really nice if someone can fix that.

**Comment by linjan** [comment]
Maybe it linked to #4182

**Comment by rodrigok** [comment]
@linjan It's not related

**Comment by rodrigok** [comment]
@yarone I can't reproduce the problem

**Comment by rore** [comment]
It's a very common complaint, see #3519.
We're very frustrated about this, really holding back fully adopting rocket.

**Comment by rasos** [comment]
If it is only a setting issue, then it has just been fixed https://github.com/RocketChat/Rocket.Chat/issues/4270

**Comment by JoeArcher007** [comment]
My brother who is behind by about 2 iOS (iOS 8 I believe) is able to get push messages for all of the messages. I'm going to try using Default for Desktop, and see if that makes a difference (I read that in another bug tracker.)

**Comment by sscholl** [comment]
This issue seems not fixed.

**Comment by ondra-prochazka** [comment]
Same problem here with rocket chat 0.56.0 installed via snap on Ubuntu 16.04

Push test messages work fine, as well as push messages on mentions. There are no push notifications on direct messages, however. Any advice?

**Comment by rasos** [comment]
Push messages in DM need two pre-conditions:    
1. mobile client is disconnected
2. desktop client has not been used for 5 minutes
See #6988

**Comment by ondra-prochazka** [comment]
Many thanks @rasos, though I got to admit that the logic is not very clear to me. Why are these rules applied to DM, and not to mentions? And why are they in place in the first place - notifications on direct messages are very important, and I woold not mind to see them on both desktop and mobile, or when the mobile client is connected.

Do I read it correctly from  #6988 that this behavior will become configurable?

**Comment by Hudell** [comment]
We have recently refactored the notification system, so I'll be closing this old issue. If someone runs into this problem again, it can be reopened.
