### ISSUE TITLE
Toggle option for blocking invalid /commands

### ISSUE THREAD

**Issue by HelloAllan** [RocketChat/Rocket.Chat#4186]
Your Rocket.Chat version: 3.8

Would it be possible to get the blocking invalid /commands as a toggle option in the settings pane? 

Having it blocked by default affects users wishing to use custom / webhooks as well as pasting UNIX file paths in chats.

**Comment by webflo** [comment]
Already fixed in https://github.com/RocketChat/Rocket.Chat/pull/4360

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
