### ISSUE TITLE
Option to geo-locate user login and display a mini-country-flag (emoji one) next to the UTC offset on right flex 

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#419]
This would be a fascinating addition for our demo chat; and might be even useful for other use cases.
##

**Comment by engelgabriel** [comment]
It is underway! :)

**Comment by MagicFab** [comment]
This would be most useful if it showed current local time /timezone - not only a flag.

**Comment by rodrigok** [comment]
@MagicFab we already to this :smile: you can see user timezone in the list of room users and when you open the user profile.

**Comment by MagicFab** [comment]
Didn't notice, I am new to RC. In fact some may find a flag offensive/inappropriate, depending on locale.

**Comment by MartinSchoeler** [comment]
Closing this since today we already show the timezone on the user
