### ISSUE TITLE
different avatar for each channel ? 

### ISSUE THREAD

**Issue by artkill** [RocketChat/Rocket.Chat#4191]
Hi! 🙂 Is it possible to have a different avatar for each channel ? 

thx

**Comment by jszaszvari** [comment]
Does not look like it - https://demo.rocket.chat/channel/support?msg=WDRrYu7SWNdusYJtM

**Comment by thecanadianbaker** [comment]
@artkill @jszaszvari can you provide a use case for the different avatars?

**Comment by jszaszvari** [comment]
I don't want it, apologies. Was just pointing out that the question had
already been answered in the chat room.

John

**Comment by artkill** [comment]
Yes, i have a website for gamers.

instead of using an avatar. On my site , players would show their rank in the game.



________________________________
De : Jason Murray <notifications@github.com>
Envoyé : lundi 5 septembre 2016 13:23
À : RocketChat/Rocket.Chat
Cc : artkill; Mention
Objet : Re: [RocketChat/Rocket.Chat] different avatar for each channel ? (#4191)


@artkill<https://github.com/artkill> @jszaszvari<https://github.com/jszaszvari> can you provide a use case for the different avatars?

-

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
