### ISSUE TITLE
uploaded PSD file corrupted due to orientation adjusting

### ISSUE THREAD

**Issue by libmaru** [RocketChat/Rocket.Chat#4194]
`packages/rocketchat-file-upload/server/config/configFileUploadFileSystem.js`

`transformWrite` automatically adjust image orientation for any uploaded file with MIME type of `image/*`

any PSD file uploaded to local file system will be corrupted

sample: http://livven.me/uploads/psds/HTC%20Sense%20Clock%20PSD%20by%20Livven.zip

upload:
size: 2634032 bytes
md5: 2624db3292231002453d63efb8856bd7

download:
size: 8546716 bytes
md5: 36d80593a76aa2b98082766a3016c6b9

**Comment by libmaru** [comment]
[sample.zip](https://github.com/RocketChat/Rocket.Chat/files/454470/sample.zip)

**Comment by engelgabriel** [comment]
@rodrigok can you please fix this as part of https://github.com/RocketChat/Rocket.Chat/issues/4235 ?
