### ISSUE TITLE
Rocket Chat 0.38.0 + Hubot 0.1.4 errors

### ISSUE THREAD

**Issue by Hostile** [RocketChat/Rocket.Chat#4195]
Your Rocket.Chat version: (make sure you are running the latest)
Rocket Chat 0.38.0 + Hubot 0.1.4

`root@chat:~# docker run -it -e ROCKETCHAT_URL=chat.vodeoo.com:3000 -e ROCKETCHAT_ROOM='general' -e LISTEN_ON_ALL_PUBLIC=true -e ROCKETCHAT_USER=bot -e ROCKETCHAT_PASSWORD=bot -e ROCKETCHAT_AUTH=password -e BOT_NAME=bot -e EXTERNAL_SCRIPTS=hubot-pugme,hubot-help -v $PWD:/home/hubot/node_modules/hubot-rocketchat hihouhou/hubot-rocketchat
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Starting Rocketchat adapter version 0.1.4...
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Once connected to rooms I will respond to the name: hihouhou
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO I will also respond to my Rocket.Chat username as an alias: bot
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Connecting To: chat.vodeoo.com:3000
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Successfully connected!
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO general
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Logging In
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Successfully Logged In
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Looking up Room ID for: general
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO Joining Room: GENERAL
[Mon Sep 05 2016 06:38:12 GMT+0000 (UTC)] INFO rid:  [ 'GENERAL' ]
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] INFO All rooms joined.
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] INFO Successfully joined room: GENERAL
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] INFO Subscribing to Room: GENERAL
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] ERROR Unable to subscribe: {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"} Reason: Subscription not found
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] ERROR {"error":404,"reason":"Subscription not found","message":"Subscription not found [404]","errorType":"Meteor.Error"}
[Mon Sep 05 2016 06:38:13 GMT+0000 (UTC)] ERROR Unable to complete setup. See https://github.com/RocketChat/hubot-rocketchat for more info.
`

**Comment by wargamesqcf** [comment]
because 1.4 is garbage use 

hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3

**Comment by Hostile** [comment]
how can i make it use thsis image ?

i did it by this command from https://hub.docker.com/r/hihouhou/hubot-rocketchat/

**Comment by wargamesqcf** [comment]
I use docker-compose

`# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3
  volumes:
    - ./scripts:/home/hubot/scripts
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=
    - LISTEN_ON_ALL_PUBLIC=true
    - RESPOND_TO_DM=true
    - ROCKETCHAT_USER=
    - ROCKETCHAT_PASSWORD=
    - BOT_NAME=
#    - HUBOT_WOLFRAM_APPID=
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,basic
#hubot-wolfram    
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080`

**Comment by Hostile** [comment]
i got docker compose instales but i never used it 

i have to create docker-compose.yml and past your file?

**Comment by wargamesqcf** [comment]
yep, then just docker-compose up -d hubot

**Comment by Hostile** [comment]
@wargamesqcf where do i put docker-compose.yml

/root/docker-compose.yml     ?

**Comment by wargamesqcf** [comment]
yep

**Comment by Hostile** [comment]
@wargamesqcf 

didnt work our as planned :)

root@chat:~# docker-compose up -d hubot
Service "hubot" has a link to service "rocketchat" which does not exist.

**Comment by wargamesqcf** [comment]
My entire docker-compose looks like this, just need to fill in the username/password/botname stuff.

'''
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://five-rings-online.com:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3
  volumes:
    - ./scripts:/home/hubot/scripts
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=diceroom
    - LISTEN_ON_ALL_PUBLIC=true
    - RESPOND_TO_DM=true
    - ROCKETCHAT_USER=
    - ROCKETCHAT_PASSWORD=
    - BOT_NAME=
#    - HUBOT_WOLFRAM_APPID=
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,basic
#hubot-wolfram    
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
'''

**Comment by Hostile** [comment]
root@chat:~# docker-compose up -d hubot
Removing root_rocketchat_1...
root_mongo_1 is up-to-date
Recreating e7416ef65a_root_rocketchat_1...
driver failed programming external connectivity on endpoint root_rocketchat_1 (e75665ca639db9dabbdd812e88960dcdb254c00e8b0393183292c50ed7b25ed6): Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use
root@chat:~#

@wargamesqcf

**Comment by wargamesqcf** [comment]
You already have a rocket chat instance open is what that reads.

**Comment by Hostile** [comment]
yes, but i thought its bot and chat to separate things and bot connects to chat on same 3000 port
@wargamesqcf

**Comment by jszaszvari** [comment]
Send us your docker compose file

**Comment by Hostile** [comment]
how do i reinstall it ? 

root@chat:~# docker-compose up -d hubot
Starting root_mongo_1...
oci runtime error: container with id exists: 5e3e179b1c82d012d4cf807316513817e092ccf00ff0e9760c44ef311b30c20b

**Comment by Hostile** [comment]
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=https://chat.vodeoo.com:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3
  volumes:
    - ./scripts:/home/hubot/scripts
  environment:
    - ROCKETCHAT_URL=https://chat.vodeoo.com:3000
    - ROCKETCHAT_ROOM=general
    - LISTEN_ON_ALL_PUBLIC=true
    - RESPOND_TO_DM=true
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=bot
    - BOT_NAME=bot
#    - HUBOT_WOLFRAM_APPID=
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,basic
#hubot-wolfram
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080

**Comment by jszaszvari** [comment]
You need to remove the current container and start again.

In the same folder as your docker file

docker-compose down

 then run

docker ps

and make sure there are no more containers running, if there are more
containers running do

docker stop <containername> (eg docker stop mongo)

then run (in the same folder as docker-compose.yml)

docker-compose up

and if that works, press CTRL+C to exit the logs/console

and then start everything up again in the background with

docker-compose up -d

**Comment by Hostile** [comment]
kind of working but cant make bot join channel

`rocketchat_1 | ➔ +----------------------------------------------+
rocketchat_1 | ➔ |                SERVER RUNNING                |
rocketchat_1 | ➔ +----------------------------------------------+
rocketchat_1 | ➔ |                                              |
rocketchat_1 | ➔ |       Version: 0.38.0                        |
rocketchat_1 | ➔ |  Process Port: 3000                          |
rocketchat_1 | ➔ |      Site URL: https://chat.vodeoo.com:3000  |
rocketchat_1 | ➔ |                                              |
`

**Comment by jszaszvari** [comment]
Try linking direct to the container.

 - In the same folder as compose file run 'docker-compose down'

- under the hubot section of the docker compose file

edit and Change the line
- ROCKETCHAT_URL=https://chat.vodeoo.com:3000

too

- ROCKETCHAT_URL=rocketchat:3000

then

docker-compose up

Dont use the URL or the hostname, specifying rocketchat:3000 tells it to
use the docker link your created

**Comment by Hostile** [comment]
root@chat:~# docker-compose down
No such command: down

Commands:
  build              Build or rebuild services
  help               Get help on a command
  kill               Kill containers
  logs               View output from containers
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pulls service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  up                 Create and start containers
  migrate-to-labels  Recreate containers to add labels
  version            Show the Docker-Compose version information

**Comment by Hostile** [comment]
it looks like bot if not on chat but when i prv msg him i get logs, 

`rocketchat_1 | ====== BEGIN MAIL #0 ======
rocketchat_1 | (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
rocketchat_1 | MIME-Version: 1.0
rocketchat_1 | To: vodeooltd@gmail.com
rocketchat_1 | Subject: [Rocket.Chat] You have been direct messaged by hostile
rocketchat_1 | Content-Type: text/html; charset=utf-8
rocketchat_1 | Content-Transfer-Encoding: quoted-printable
rocketchat_1 |
rocketchat_1 | <table border=3D"0" cellspacing=3D"0" cellpadding=3D"0" width=3D"100%" =
rocketchat_1 | bgcolor=3D"#f3f3f3" style=3D"color:#4a4a4a;font-family: =
rocketchat_1 | Helvetica,Arial,sans-serif;font-size:14px;line-height:20px;border-collapse:callapse;border-spacing:0;margin:0 auto"><tr><td =
rocketchat_1 | style=3D"padding:1em"><table border=3D"0" cellspacing=3D"0" =
rocketchat_1 | cellpadding=3D"0" align=3D"center" width=3D"100%" =
rocketchat_1 | style=3D"width:100%;margin:0 auto;max-width:800px"><tr><td =
rocketchat_1 | bgcolor=3D"#ffffff" style=3D"background-color:#ffffff; border: 1px solid =
rocketchat_1 | #DDD; font-size: 10pt; font-family: Helvetica,Arial,sans-serif;"><table =
rocketchat_1 | width=3D"100%" border=3D"0" cellspacing=3D"0" cellpadding=3D"0"><tr><td =
rocketchat_1 | style=3D"background-color: #04436a;"><h1 style=3D"font-family: =
rocketchat_1 | Helvetica,Arial,sans-serif; padding: 0 1em; margin: 0; line-height: 70px; =
rocketchat_1 | color: #FFF;">Rocket.Chat</h1></td></tr><tr><td style=3D"padding: 1em; =
rocketchat_1 | font-size: 10pt; font-family: Helvetica,Arial,sans-serif;">bot<hr =
rocketchat_1 | style=3D"margin: 20px auto; border: none; border-bottom: 1px solid =
rocketchat_1 | #dddddd;"><a style=3D"color: #fff; padding: .5em; background-color: =
rocketchat_1 | #04436a; display: block; width: 10em; text-align: center; text-decoration: =
rocketchat_1 | none; margin: auto; margin-bottom: 8px;" =
rocketchat_1 | href=3D"https://chat.vodeoo.com:3000/direct/hostile">GO TO =
rocketchat_1 | MESSAGE</a></td></tr></table></td></tr><tr><td border=3D"0" =
rocketchat_1 | cellspacing=3D"0" cellpadding=3D"0" width=3D"100%" style=3D"font-family: =
rocketchat_1 | Helvetica,Arial,sans-serif; max-width: 800px; margin: 0 auto; padding: =
rocketchat_1 | 1.5em; text-align: center; font-size: 8pt; color: #999;">Powered by <a =
rocketchat_1 | href=3D"https://rocket.chat" =
rocketchat_1 | target=3D"_blank">Rocket.Chat</a></td></tr></table></td></tr></table>
rocketchat_1 | ====== END MAIL #0 ======`

**Comment by jszaszvari** [comment]
What flavour of linux is that?

Can you run 'docker-compose version' if this does not work..

Thats very strange.

Try the following for your version (use your container names if different)

root@chat:~# docker-compose stop hubot
Stopping rocketchat_hubot_1 ... done

root@chat:~# docker-compose rm hubot
Going to remove rocketchat_hubot_1
Are you sure? [yN] y

Removing rocketchat_hubot_1 ... done

Then make sure as above you have updated the URL for just hubot too

- ROCKETCHAT_URL=rocketchat:3000

then try


root@chat:~# docker-compose up

**Comment by Hostile** [comment]
root@chat:~# docker-compose version
docker-compose version: 1.4.2
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013 @

**Comment by jszaszvari** [comment]
Can you come on too https://demo.rocket.chat and send me a message and we
can work through it there and i'll post the solution here if we find it.?

There is a few more things we can try

docker-compose stop hubot
docker-compose stop rocketchat

docker-compose up -d

(just so you can run a 'docker-compose logs hubot' so we can see what the
bot is doing.)

**Comment by Hostile** [comment]
ok

**Comment by jszaszvari** [comment]
Hostile's issue is resolved

I've walked them through the fix for this, There was a few issues

- URL was wrong in docker-compose.yml, changed the address the bot connects to 

FROM -
https://rockechat.domain.com:3000
TO
rocketchat:3000 

as to use dockers internal networking.

Also, the digital-ocean guide they followed walked them through installing docker-compose 1.4 - I upgraded this to 1.8 for them as there is a lot of useful stuff thats been added since 1.4

And added in docker persistant containers as there was nothing being saved upon reboot. 

Then moved the service management from "forever-service" to upstart (ubuntu) 

all good now
