### ISSUE TITLE
channelSettings.coffee exceptions in Admin view

### ISSUE THREAD

**Issue by garychapman** [RocketChat/Rocket.Chat#4196]
Rocket.Chat version: 0.38.0 (running on Windows 10)

I'm seeing bugs in the latest release (both in the develop and master branches). It's probably easier to describe how to reproduce:
1. (after meteor reset and rebuilding) Create a new user, and then log in
2. Click on #general in the CHANNELS list
3. Click the (i)nformation icon on the top right to display the channel settings pane
4. Open the Administration pane
5. Select Rooms or Users - neither view displays, and the browser debug console will show an exception thrown at `channelSettings.coffee:89`
6. Clicking on other items in the Admin menu (View Logs, Mailer, Integrations) also displays similar behaviour

I've included a screenshot which shows a stack trace, and I've also circled some display glitches which occur intermittently.

![rc bug](https://cloud.githubusercontent.com/assets/2315465/18243215/768b8fac-739d-11e6-8c19-79d92ae4362f.png)

**Comment by MartinSchoeler** [comment]
Hey @garychapman , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
