### ISSUE TITLE
Rocket.Chat - Internal Server Error when attempting to join any channel beyond #general

### ISSUE THREAD

**Issue by myobfee** [RocketChat/Rocket.Chat#4197]
Attempting to go to #support and receiving "Internal Server Error"

Issue reported by several people in general channel as well

Tried disabling adblocker (ublock origin) and it did not resolve issue
Firefox (latest) dev console shows no errors.

**Comment by jszaszvari** [comment]
I've been seeing this in the public rocketchat room all day today.

https://demo.rocket.chat/channel/support?msg=DXbWfGStyK32ydC7W

**Comment by MartinSchoeler** [comment]
@myobfee @jszaszvari this should be fixed by now, thanks for the feedback!
