### ISSUE TITLE
Android Notifications doesn't work if Windows Client is open

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#4205]
Your Rocket.Chat version: 0.39.0

Hello,

I'm not able to receive mention notifications anymore on my cellphone if I leave my PC logged on with Rocket Chat client open.
That's annoying because if I forget to close rocket chat client before I leave home/office I'm not alerted anymore on my android phone until I close the client on the PC.

Is it possible to receive alert in both way ?

Regards

Arnaud

**Comment by rasos** [comment]
You could apply this two-line patch: https://github.com/RocketChat/Rocket.Chat/issues/1602#issuecomment-226559485

**Comment by Lucky21110** [comment]
Thx Rasos :) Works !!

**Comment by geekgonecrazy** [comment]
Please add your voice to change this logic to #1602
