### ISSUE TITLE
LDAP password field brings database value

### ISSUE THREAD

**Issue by pabloocastro** [RocketChat/Rocket.Chat#4206]
Your Rocket.Chat version:0.39

If you change type of password field from "password" to "text", it's possible to see the database value.

**Comment by MartinSchoeler** [comment]
@pabloocastro could you give more details?

**Comment by pabloocastro** [comment]
On image, you can see the password field and on inspection tool is possible to change the field type (from password to text). This exposes the field value and you can see the value brought from database. Maybe, you can bring '*' instead the real value of the field. 

![pass-field](https://cloud.githubusercontent.com/assets/6740209/18280248/ce1dbc40-742e-11e6-8b4a-28a3167f4763.png)

**Comment by dzaouch** [comment]
This is true with all the websites. 
It's like someone standing behind you, watching what you type, they'll know your password.
Try the same on facebook login page you'll see.
