### ISSUE TITLE
Slash command lets you make channel with capital letters

### ISSUE THREAD

**Issue by jszaszvari** [RocketChat/Rocket.Chat#4207]
On the latest

/create MyNewChannel 

will create a channel with the Capital letters in tact

Doing it through the sidebar removes all capitals from it

and both are seperate channels 

/join mynewchannel 

vs

/join MyNewChannel 

<img width="200" alt="screen shot 2016-09-06 at 11 18 52 am" src="https://cloud.githubusercontent.com/assets/872463/18259109/bc4db142-7423-11e6-88ae-6c34cc92abef.png">

Thanks @paulc in the community for finding this

**Comment by jszaszvari** [comment]
Whoops, Just found this - I guess this can be closed?


https://github.com/RocketChat/Rocket.Chat/pull/4051

**Comment by Molle500** [comment]
Better fix so you can create channels with capital letter in sidebar instead as well :)

**Comment by MartinSchoeler** [comment]
@jszaszvari since there is someone already on that and there is already a issue for that i will be closing this issue, but anyway thanks for the report!

**Comment by jszaszvari** [comment]
Yes apologies.  Only saw the fix as soon as I posted it.

Thanks
