### ISSUE TITLE
error: Can't install npm dependencies. Are you connected to the internet?

### ISSUE THREAD

**Issue by Forrest-Hu** [RocketChat/Rocket.Chat#4209]
Your Rocket.Chat version: (make sure you are running the latest)0.38.
While building package rocketchat:
error: Can't install npm dependencies. Are you connected to the internet?

I do not know why,who can help me? thank very much.

**Comment by geekgonecrazy** [comment]
Please give this a try on one of the newer releases.  Also make sure you update your version of nodejs to 4.8

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
