### ISSUE TITLE
Improvements regarding display of username

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#4210]
Your Rocket.Chat version: 0.39.0

Hi,

in our Rocket.Chat instance we've migrated now all users onto LDAP but their usernames are now quite cryptic and hard to remember. So it's now very difficult to identify users in the member list of a room or also in the direct messages section. Ideally Rocket.Chat would provide an option to:
- [ ] display user alias (i.e. full name) in the direct messages list (#5326)
- [ ] display user alias in the members list of a room
- [ ] display user alias in `@` mentions (#4624)
  - `@` mentions should also list entries based on the user alias (i.e. search user by the user's full name)
- [ ] display the user alias on actions like "enter room, invite, ..."

Thanks :)

**Comment by bhbarbosa** [comment]
I think this is related to [#3851](https://github.com/RocketChat/Rocket.Chat/pull/3851), still +1.

**Comment by subesokun** [comment]
* Search for direct messages via the user alias

In our current setup it's now almost impossible to search for a user to open a private chat with him as our LDAP usernames are super hard to remember.

**Comment by subesokun** [comment]
The cryptic usernames are becoming lately quite a problem. If you had a direct chat with several people it's nearly impossible to guess alone from the displayed username the correct channel. So you've to click through all channels unless you find the correct chat again. E.g. my direct channel list looks somewhat similar to:

* njd7sas
* d0asds
* aleq3n
* lk2dd
* ...

So I'd really appreciate if there could be at least a minimal fix for displaying the real user name in the direct channels list instead of the user alias.

**Comment by alexbrazier** [comment]
This is now complete in PR #3851 - waiting for approval
Still todo (in another PR)

- display full name in mentions
- display full name in channel members list

**Comment by subesokun** [comment]
@alexbrazier, awesome thanks a lot! Looking forward to it :)

I guess the issue to display the full name in mentions has been already solved via this commit, or? https://github.com/RocketChat/Rocket.Chat/commit/b3151e60bdfe3188f06ebd32cd40e1bfd8378ab7

**Comment by subesokun** [comment]
Is there any progress on displaying the full name in channel members list? Our number of users are constantly increasing and hence the member list became now completely useless as you can't guess anymore which user belongs to with username as they're way to cryptic to remember. Any chance that there will be a fix soon :(? First users are leaving already as they can't private chat because they can't find each other....

**Comment by willihelm** [comment]
I would also appreciate this feature. In my company we have cases where the name of a user changed by marriage but it is too much work to change the sAMAccountName. So they are displayed with their old names in rocket.

**Comment by subesokun** [comment]
@willihelm you should repost your comment here https://github.com/RocketChat/Rocket.Chat/pull/3851

Closing this issue in favor of that PR.
