### ISSUE TITLE
Changing a username causes user to be unable to access chat

### ISSUE THREAD

**Issue by skizzors** [RocketChat/Rocket.Chat#4212]
Your Rocket.Chat version: 0.37.1
These are our current settings
![screen shot 2016-09-06 at 9 21 36 am](https://cloud.githubusercontent.com/assets/17693312/18277330/b22c2410-7413-11e6-980d-a022568748ea.png)
Every time an admin changes someone's username it makes the sidebar invisible and chat inaccessible. We are forced to delete their account and let them create a new one with the new username.

**Comment by MartinSchoeler** [comment]
@skizzors could you check the roles of these users when they are unable to access the chat?

**Comment by skizzors** [comment]
How do I view an individual user's role? This also pops up admins or users try to change their username. 
![screen shot 2016-09-08 at 9 49 51 am](https://cloud.githubusercontent.com/assets/17693312/18354199/540286e8-75aa-11e6-8cf2-bedab1f9e7e6.png)

**Comment by MartinSchoeler** [comment]
@skizzors you could try updating your rocket chat to the latest version, this is an old bug that has been happening to you, where if the user gets his username changed he loses all his permitions

**Comment by MartinSchoeler** [comment]
@skizzors any news?

**Comment by skizzors** [comment]
@MartinSchoeler yes we updated and havent had this same issue again thanks!
