### ISSUE TITLE
use Rocket.Chat as a component

### ISSUE THREAD

**Issue by istvano** [RocketChat/Rocket.Chat#4213]
Hi Guys,

It is a fantastic little piece of software. On our we are about to start developing a commertial application. One requirement of the application is a slack like ( much simpler ) collaboration element.

I was wondering if from licencing point of view. 

- Can we use Rocket.Chat as part of our commercial offering?
- What is the best way to embed Rocket.Chat into a ReactJS application as a part of it's screen?

Thanks for any guides or pointers.

Kind Regards,

Istvan

**Comment by lucasvanhalst** [comment]
I'm pretty sure you can do whatever you want - see the license here https://github.com/RocketChat/Rocket.Chat/blob/develop/LICENSE

And the best (and probably only) way to embed it into your existing website is by using an iframe.

**Comment by istvano** [comment]
Hi,

thanks very much for your response.

Kind Regards
