### ISSUE TITLE
Request - Integration for PHPBB3.1+

### ISSUE THREAD

**Issue by Valiantiam** [RocketChat/Rocket.Chat#4214]
This is a request for some sort of community or official support for phpbb3.1 authentication tie in.

Currently we make use of this https://github.com/EoleDevel/authphpbb3/ and have made use of other integrations into the phpbb authentication db.

Is it possible we could get something setup for this along with SSO between them as well, taking advantage of the phpbb cookie to obtain the sessionid?

**Comment by Valiantiam** [comment]
I've been giving more thought to this. Is it possible to do this with iFrame auth?

**Comment by vitor251093** [comment]
I would like to see that happening as well. phpBB3 is an excellent forum; responsive, very modular and with integrated ReCaptcha support, but it lacks a chat like Rocket.Chat.

**Comment by Valiantiam** [comment]
Mostly i'd just like to provide a way for the community to not have to register twice.

**Comment by k0nsl** [comment]
A bridge would be nice to have -- phpBB3 is excellent, as @vitor251093 already wrote, with a very good track record with regards to security.

It uses MySQL/MariaDB (don't know if it supports any other database backends, but I doubt it does) so I am not sure how such a bridge could be implemented. However, if this is possible, then it is something I, too, would like to see.

**Comment by geekgonecrazy** [comment]
With the DB being different, its very unlikely we could even properly integrate with out adding a lot of extra code to Rocket.Chat that would not be shared with other features.  

Because of that, i'd recommend building a bridge external to Rocket.Chat to facilitate this.  Closing this as its not something we will likely implement.
