### ISSUE TITLE
Jitis not populating at all in Rocket Chat with HTTPS Nginx configured

### ISSUE THREAD

**Issue by amaraka** [RocketChat/Rocket.Chat#4216]
Your Rocket.Chat version: (make sure you are running the latest)
I have installed Rocket Chat with Nginx SSL so it loads fine with HTTPS and video messaging and audio works in Chrome but Jitsi never populates at all say cannot connect to DNS server and I select True SSL and add in the HTTPS link of my Jitis server. On its own Jitsi works fine.. Any idea why its not populating?

Enabled True   False
https://meet.energywave.net/amaraka
SSL True   
Enable in Channels True   

Unable to resolve servers DNS error.

 Please advise.. Thank you Zion

**Comment by compuguy** [comment]
I can tell you @amaraka that your ssl cert for your jitsi-meet server is self signed to an ip address which is why it doesn't work in rocketchat.

**Comment by geekgonecrazy** [comment]
as @compuguy said self signed isn't going to work.  You'd have to pin the ssl cert.  Easiest would be to just use lets encrypt :smile:
