### ISSUE TITLE
@nick-prefixed messages are not sent out to webhooks

### ISSUE THREAD

**Issue by niemeyer** [RocketChat/Rocket.Chat#4217]
Your Rocket.Chat version: 0.39.0

After much testing, it's quite clear that any messages prefixed by some `@nick` do not get sent out into the webhook server. Tried everything I could think of.. even using the nick as an explicit trigger. Still doesn't work. Every other message gets sent properly.

**Comment by niemeyer** [comment]
While logs are in debug mode, I can see the two messages going into the logs:
> I20160906-22:55:58.121(0) Meteor ➔ method sendMessage -> userId: 8xdecNvDYcDhdMdPA , arguments: { '0': { _id: 'ZEWrw4P3a9xGixyyG', rid: 'QubNxcTpdZr8N2Ltx', msg: 'echo one' } }
> I20160906-22:56:02.188(0) Meteor ➔ method sendMessage -> userId: 8xdecNvDYcDhdMdPA , arguments: { '0': { _id: 'N545jxrfkt2KxFsva', rid: 'QubNxcTpdZr8N2Ltx', msg: '@mup echo two' } }

The first one gets delivered to the other end (twice even, as I had two webhooks configured the same to make sure):
> Connect-Time: 0
> Cf-Connecting-Ip: 104.155.26.218
> Total-Route-Time: 0
> Connection: close
> Host: requestb.in
> Content-Type: application/json
> Cf-Ray: 2de582f4b3b5150f-CDG
> Cf-Ipcountry: US
> Cf-Visitor: {"scheme":"http"}
> Accept-Encoding: gzip
> Content-Length: 212
> Via: 1.1 vegur
> X-Request-Id: d6d6ca35-6da8-4d9f-a751-87dff471ed5f
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/41.0.2227.0 Safari/537.36
>
>{"token":"et8jFnbPgmfkh4ifkuCFgxiw","channel_id":"QubNxcTpdZr8N2Ltx","channel_name":"mup","timestamp":"2016-09-06T22:55:58.122Z","user_id":"8xdecNvDYcDhdMdPA","user_name":"niemeyer","text":"echo one","bot":false}

The @-prefixed one is never sent, despite the logging.

**Comment by rodrigok** [comment]
Can't reproduce
