### ISSUE TITLE
Email address changes cause Rocket Chat to view user as a new user

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#4221]
Rocket.Chat version: 0.39.0.. and all others back to 0.33.0. I currently have this system in a pilot scenario.
We have RC setup in our DMZ and using SAML as the mechanism to allow authentication to the RC service. During this process we create a user having a userid, first.last name and email address. 

Our company also has been purchasing companies on a regular bases. Right away these users will be integrated into the directory both eDIR and AD. The SAML works against eDIR and has been flawless in creation of users within the Rocket Chat system. 

**Issue**: Users are first integrated into the directory with their existing company email address. As the integration goes on this eventually changes to the master companies email system, hence the change in email address. Once the change happens RC no longer recognizes this as a current user on the system and would create a new user. The user no longer has access to the current channels and one to one chats.

The userid and username remain the same, its the email address that seems to be the issue once the main email address changes on PeopleSoft which syncs to the eDIR.

Is there a way to provide an admin option to:
1. Merge the users since they have the same userid and this is unique in the company. 
Or maybe a better option is to.... 
2. Overwrite the email address since they have the same userid and this is unique in the company. There would be no need to verify the email address since it is already coming from an authoritative source.

Not sure which would be the easiest to implement or if this is an issue or an enhancement.
Thanks

Updated to 0.40.1 same issue.

**Comment by geekgonecrazy** [comment]
This one is a bit old and we have gone through a few releases since then.  Please feel free to re-open if still and issue.
