### ISSUE TITLE
Displayed error when i use Costome OAuth . 

### ISSUE THREAD

**Issue by is984** [RocketChat/Rocket.Chat#4222]
Your Rocket.Chat version: (0.39.0)
1,Setup Microsoft OAuth.
2,use it
3, displayed error Internal Server Error and return login screen
Server Log 
W20160907-11:20:05.756(9) (oauth_server.js:398) Error in OAuth Server: The dotted field '@odata.context' in 'credential.serviceData.@odata.context' is not valid for storage.
I20160907-11:20:06.249(9) Exception while invoking method 'login' MongoError: The dotted field '@odata.context' in 'credential.serviceData.@odata.context' is not valid for storage.     at Object.Future.wait (/usr/local/src/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     at [object Object].MongoConnection.(anonymous function) [as update](packages/mongo/mongo_driver.js:736:1)     at [object Object].Mongo.Collection.(anonymous function) [as update](packages/mongo/collection.js:590:1)     at [object Object].Mongo.Collection.upsert (packages/mongo/collection.js:624:1)     at Object.OAuth._storePendingCredential (packages/oauth/pending_credentials.js:56:1)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:15:1)     at middleware (packages/oauth/oauth_server.js:173:1)     at packages/oauth/oauth_server.js:146:1     - - - - -     at Object.toError (/usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     at /usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     at /usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     at /usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     at Server.Base._callHandler (/usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     at /usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     at [object Object].MongoReply.parseBody (/usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     at [object Object].<anonymous> (/usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     at [object Object].emit (events.js:95:17)     at [object Object].<anonymous> (/usr/local/src/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13) 

What shall do i ?

**Comment by geekgonecrazy** [comment]
Please see: #6809 a wonderful guide posted there by a community member for integrating with microsoft.
