### ISSUE TITLE
Seafile integration plugin

### ISSUE THREAD

**Issue by LeDistordu** [RocketChat/Rocket.Chat#4223]
Seafile is a Dropbox open source with self hosted possibility

https://www.seafile.com/en/home/

it would be nice if when transferring a file in Rocket.Chat he offers us the upload on seafile, followed by the generation of a share link sent directly RocketChat

**Comment by compuguy** [comment]
While were at it, lets get owncloud and nextcloud support as well...

**Comment by chymian** [comment]
+1

**Comment by maxdwit** [comment]
+1 for owncloud and seafile

**Comment by hkmoon** [comment]
+1 for owncloud!

**Comment by leandroqm** [comment]
+1 for seafile.

**Comment by hodyroff** [comment]
WebDAV would bring ownCloud support. Can we get any guidance from RocketChat Devs how this could fit into roadmap, what would be needed?

**Comment by nez** [comment]
+1 for nextcloud/owncloud

**Comment by quesada** [comment]
+1 for seafile

**Comment by k0nsl** [comment]
Yeah Seafile is great -- but they split up into two entities somewhat recently and I do not know which one is the ‘most legit’ one.

Even so, I would like to have this option as well for when I begin using it again.

**Comment by Archer4l** [comment]
+1 for seafile.

**Comment by alexleosumy** [comment]
+1 owncloud/nextcloud

**Comment by BirknerAlex** [comment]
+1 for seafile

**Comment by Fearxpc** [comment]
+1 for seafile

**Comment by geekgonecrazy** [comment]
With the upcoming release of our Rocket.Chat Apps framework.  I think this is more fitting as a Rocket.Chat App.  

Please feel free to post your Rocket.Chat App idea to our [forum](https://forums.rocket.chat) so maybe someone(even you) can create it.

**Comment by marcosxaviergil** [comment]
+1 seafile
