### ISSUE TITLE
Show filename in image preview

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#4224]
Hi,

the image preview as well as the possibility to switch through all images in a channel using the arrow keys is great. It would be super helpful, though, if the image filename was shown above or below the image so it's always clear which image is shown at the moment.

**Comment by MartinSchoeler** [comment]
@andreas-bulling you can see the names if you go in files list tab, is this what you mean?

**Comment by andreas-bulling** [comment]
No. I mean if you click on a picture it opens up in fullscreen with nice backward/forward arrows that can be used with the arrow keys on the keyboard. It would be nice to show the current filename there

**Comment by andreas-bulling** [comment]
It would also be nice if a caption could be added to a figure and shown to the right of the figure or so. At the moment users have to write the caption as normal chat text and if other people write messages in the meanwhile that caption appears far below the figure in the worst case.

**Comment by andreas-bulling** [comment]
actually showing at the bottom, i.e. centred between the arrows, would be most meaningful I think

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
