### ISSUE TITLE
Get no Mails

### ISSUE THREAD

**Issue by Jan-Ra-wlec** [RocketChat/Rocket.Chat#4225]
Your Rocket.Chat version: 0.39.0

I registred my Gmail Account in RC. It said Mail sent and everything seems to be fine bit I don'tgeht the Testmail.

**Comment by zxweed** [comment]
There are another issue for it - https://github.com/RocketChat/Rocket.Chat/issues/2944

**Comment by MartinSchoeler** [comment]
Duplicate
