### ISSUE TITLE
Message dropdown overflows

### ISSUE THREAD

**Issue by PavelVanecek** [RocketChat/Rocket.Chat#4227]
Your Rocket.Chat version: 0.39

When in chat, the cog wheel shows a popup (edit, add reaction, star, ...). When the message title is long enough, the popup overflows behind the screen and it is not possible to reach all actions.

<img width="462" alt="screen shot 2016-09-07 at 15 16 34" src="https://cloud.githubusercontent.com/assets/1100170/18313318/7a1f5c94-750e-11e6-9af5-07d0d3d4b175.png">
<img width="511" alt="screen shot 2016-09-07 at 15 16 13" src="https://cloud.githubusercontent.com/assets/1100170/18313319/7a2a9e7e-750e-11e6-8471-0059cbc33e89.png">

**Comment by subesokun** [comment]
Some problem for me. I prefer running Rocket Chat in the "minimised" mode so that the blue side panel gets hidden but in that case the message action buttons are not accessible and I've to resize the window to reach all buttons which can be quite tedious.

**Comment by mrplow** [comment]
Note that this issue is exacerbated on Android. The right half of the action buttons are always cut off, even with short messages.

**Comment by OnthegOinOz** [comment]
👍 👍

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, since the whole UI changed. Please get back to me, if you think the overall issue is still present (I think it is not).

Cheers
Thomas
