### ISSUE TITLE
Android right flex rendering anomalies

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#423]
Happens frequently on latest updated Chrome running on Android 4.4.2;  Android 5.1.1 latest Chrome has no such problem.

Also the Hamburger left 'rocket-blue' slide works perfectly on Android 4.4.2, it is just the right 'gray' flex that has these anomalies.

###  Tab disappears

Sometimes, the arrow tab disappears, but you can still touch the area to open the flex:

![anprob1](https://cloud.githubusercontent.com/assets/122633/9150660/59a03b16-3db3-11e5-8fa0-67b6a1d8757b.png)

### Flex content disappears

Sometimes, the rendered flex is completely blank:

![anprob2](https://cloud.githubusercontent.com/assets/122633/9150664/9ba141f4-3db3-11e5-942f-842a012e96b8.png)

### Selective flex contents disappearance

Sometimes, it is partially rendered:

![anprob3](https://cloud.githubusercontent.com/assets/122633/9150670/b3a074d2-3db3-11e5-8210-c528aa321319.png)

**Comment by gmsecrieru** [comment]
Missing content might be related to #973

**Comment by engelgabriel** [comment]
Still happens? Please reopen if that is the case.
