### ISSUE TITLE
Image upload issue after upgrade to meteor 1.4.1.1

### ISSUE THREAD

**Issue by okworld26** [RocketChat/Rocket.Chat#4235]
Just upgraded. commit id:   b957fa9f5101ce62e14195a7a3a05076a70bce1f.

When uploading image in a room, after clicking the "Ok" button on image pop up preview dialog, it just disappeared and nothing else happen, the image isn't uploaded of course.

Below is error from browser console:

ufs-uploader.js:47 Uncaught TypeError: data is not an Blob or File

UploadFS.Uploader	@	ufs-uploader.js:47
FileUploadFileSystem	@	FileUploadFileSystem.js:14
fileUploadHandler	@	fileUploadHandler.js:8
(anonymous function)	@	fileUpload.coffee:91
reader.onload	@	fileUpload.coffee:11

However, avatar upload seems to be working fine.

I'm not a professional front end developer, anyone else has also see this issue after upgraded to meteor 1.4.1.1 ?

other useful info:
Rocket.Chat version: (0.39.0)
Meteor 1.4.1.1

**Comment by okworld26** [comment]
Did a research myself, and found the issue.

Rocket 0.39.0  is using    jalik:ufs@0.6.6.   However,  it should be no more than  jalik:ufs@0.6.0.

This is because there is a big change between 0.6.0 and 0.6.1.

see info from link below:
https://atmospherejs.com/jalik/ufs

you can see that "The method UploadFS.readAsArrayBuffer() is not available anymore,"...

Currently, the workaround is to use  jalik:ufs@0.6.0.  But perhaps someone could upgrade the code in file fileUpload.coffee regarding keyword "readAsArrayBuffer".

Hope that helps.  @MartinSchoeler  :)

**Comment by seanxlliu** [comment]
the storage type 'GridFS' works just fine, but 'SystemFile' doesn't work.

I also filed an issue: [https://github.com/RocketChat/Rocket.Chat/issues/4252](url), which could be related.

**Comment by thiesschneider** [comment]
In my installation GridFS also does not work. Looking forward tp the fix... Cannot upload stuff :(

**Comment by thiesschneider** [comment]
anybody working on this?

**Comment by pavankumarkatakam** [comment]
in my case "Grid FS" and filesystem both are not working.

**Comment by asthomasdk** [comment]
We are seeing issues when trying to upload files or screen shots from a web browser (Chrome). 

I am able to paste or upload from the Linux client though...

**Comment by engelgabriel** [comment]
@rodrigok please give this high priority today

**Comment by kylemclaren** [comment]
+1 have replicated this issue with GridFS, development branch of Rocket.Chat and Meteor 1.4.1.1 running on Docker.

**Comment by rodrigok** [comment]
@kylemclaren It's fixed now, can you try?

**Comment by kylemclaren** [comment]
@rodrigok Yup, that works 🙇

**Comment by pavankumarkatakam** [comment]
For me it is not working, but after this update progress is only showing not uploading the file.
