### ISSUE TITLE
Message action buttons are not accessible on small windows

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#4236]
Your Rocket.Chat version: 0.39.0

I prefer running Rocket Chat in the "minimised" mode so that the blue side panel gets hidden but in that case the message action buttons are not accessible and I've to resize the window to reach all buttons.

I'd like to attach a screenshot but for some reason it's not working...

**Comment by MartinSchoeler** [comment]
@subesokun i could not replicate this bug, a screenshot would really help, could you send one at https://demo.rocket.chat/channel/support ?

**Comment by MartinSchoeler** [comment]
@subesokun i think this is the same issue as this one #4227

**Comment by subesokun** [comment]
@MartinSchoeler exactly :) Sorry didn't see the other issue! Closing this one.
