### ISSUE TITLE
Hubot respond only random

### ISSUE THREAD

**Issue by LePandaDuNet** [RocketChat/Rocket.Chat#4237]
Your Rocket.Chat version: 0.39.0

Hi,

I have upgraded my version of Rocket Chat at the version 0.39.0 and my version of hubot at the version 1.0.3.
Since the upgraded at the version 0.38.0 and 0.39.0 of  Rocket Chat my hubot respond only randomly and I also tested with the basic bot and I get the same result.
For the bot I use an stunnel locally on my machine which passes through a localhost then go on rocketchat to do the convertion from http to https.

It seems like the bot will do as connect then disconnect like this:

[Thu Sep 08 2016 11:46:19 GMT+0000 (UTC)] INFO Successfully connected!
[Thu Sep 08 2016 11:46:19 GMT+0000 (UTC)] INFO sandbox3
[Thu Sep 08 2016 11:46:19 GMT+0000 (UTC)] INFO Logging In
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Successfully Logged In
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Joining Room: nQp9fJPv6cFfP9e7N
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO rid:  [ 'nQp9fJPv6cFfP9e7N' ]
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO All rooms joined.
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Successfully joined room: nQp9fJPv6cFfP9e7N
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Subscribing to Room: **my_messages**
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Successfully subscribed to messages
[Thu Sep 08 2016 11:46:20 GMT+0000 (UTC)] INFO Setting up reactive message list...
[Thu Sep 08 2016 11:46:59 GMT+0000 (UTC)] INFO Successfully connected!
[Thu Sep 08 2016 11:46:59 GMT+0000 (UTC)] INFO sandbox3
[Thu Sep 08 2016 11:46:59 GMT+0000 (UTC)] INFO Logging In
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Successfully Logged In
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Joining Room: nQp9fJPv6cFfP9e7N
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO rid:  [ 'nQp9fJPv6cFfP9e7N' ]
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO All rooms joined.
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Successfully joined room: nQp9fJPv6cFfP9e7N
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Preparing Meteor Subscriptions..
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Subscribing to Room: **my_messages**
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Successfully subscribed to messages
[Thu Sep 08 2016 11:47:00 GMT+0000 (UTC)] INFO Setting up reactive message list...

After more investigation with Wireshark it would seem the problem comes from an interruption of the tcp session but I don't understand why.

Do you think the problem comes from stunnel?
Can you help me, please?

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
