### ISSUE TITLE
Webhooks run with old configurations in the background

### ISSUE THREAD

**Issue by niemeyer** [RocketChat/Rocket.Chat#4246]
I've had multiple instances of webhooks acting strangely that were a side effect of a previous configuration being active. In the last case the webhook was sending messages to an endpoint which wasn't configured. It was quite confusing because it was showing up as a duplicated message. Took me a while to figure that removing all configuration would still keep it sending one of the copies, which meant it was an "invisible" webhook sending the message over. Restarting the server solved the problem

**Comment by engelgabriel** [comment]
I am totally lost on this one. @niemeyer Is there an way to consistently reproduce this?

**Comment by niemeyer** [comment]
No, I haven't tried to reproduce it explicitly, but I saw its effects very clearly, multiple times.

**Comment by niemeyer** [comment]
Ah, one idea: this was happening while #4217 was also a problem, which turned out to be related to #2504, both addressed by @geekgonecrazy.

There might be a problem in the error handling path, either when delivering or saving webhooks (or both), which causes a configuration to persist in the background incorrectly. I'd try to reproduce the above issues, and then observe its effects in that regard.

**Comment by geekgonecrazy** [comment]
One thought I had was that 0.39.0 is using Node.js 0.10.44.  Javascript VM's were pretty young at this point.  It seems like it drops these files in /tmp.  So its possible it was some how picking up and executing the left around copy of the script when an update was performed.  

0.40.0 of Rocket.Chat will be using Node.js 4.5.  I'm thinking javascript VM's are handled a good bit better, and this issue should go away.

**Comment by rodrigok** [comment]
@engelgabriel See #4356

**Comment by geekgonecrazy** [comment]
@rodrigok 👍 that looks to be it :)
