### ISSUE TITLE
The port of the attachement url is missing when displaying or downloading an attachment

### ISSUE THREAD

**Issue by seanxlliu** [RocketChat/Rocket.Chat#4252]
Your Rocket.Chat version: 0.39.0

The port of the attachement url is missing when displaying or downloading an attachment.

The following is my env settings:
environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - PORT=3000
    - ROOT_URL=http://192.168.3.11:3000
    - Accounts_UseDNSDomainCheck=False

The storage type is set to 'GridFS'.

![default](https://cloud.githubusercontent.com/assets/9614433/18381256/f8782cec-76ad-11e6-9ec0-a97d1c1d78c2.png)
![qq 20160909165112](https://cloud.githubusercontent.com/assets/9614433/18381273/15d4edde-76ae-11e6-9eef-d1654f86ff32.png)
![qq 20160909165204](https://cloud.githubusercontent.com/assets/9614433/18381275/18e671be-76ae-11e6-8a99-7de7aff50f79.png)

Another issue is the storage type 'FileSystem' doesn't work at all. The system dir has been set to '/app/uploads'. I don't know where I can find the log.

 volumes:
    - ./uploads:/app/uploads

Could be regression of the following fix, but I am not sure.
[https://github.com/RocketChat/Rocket.Chat/issues/3073](url)
[https://github.com/RocketChat/Rocket.Chat/pull/3695/files](url)

**Comment by TheReal1604** [comment]
@seanxlliu I think this could be "by design" because rocket.chat is not purposed to run without a reverse-proxy which is the endpoint for SSL. @MartinSchoeler can you say something about this?

**Comment by MartinSchoeler** [comment]
@seanxlliu could you tell us what is the value in the site url field under adiministration>general?

**Comment by engelgabriel** [comment]
@seanxlliu what is on your Admin -> General -> Site URL  setting?

**Comment by rodrigok** [comment]
Seems that this happens duo a miss configured Root URL. Please reopen it if the problem persists.

**Comment by seanxlliu** [comment]
sorry for late response. 
root url was set to "http://192.168.3.11:3000". the sever works just fine
Thank you!
