### ISSUE TITLE
Wrong German translation for "enter to"

### ISSUE THREAD

**Issue by rillig-nm** [RocketChat/Rocket.Chat#4253]
Your Rocket.Chat version: 1.3.1 for Windows

When editing a sent message, the following messages appear in the corners of the edit window:

* verlassen, um abbrechen
* betreten, um änderungen speichern

The words and the grammar are both wrong.

* Instead of "verlassen", it should be "Escape" or "Esc", since this is about the keyboard key, not escaping from prison. The whole message should be "Esc, um ab**zu**brechen". When starting a sentence with "Press a key to" in German, a following verb is modified, adding the **zu** syllable.
* The other message should be "Enter, um **Ä**nderungen **zu** speichern". In German, it looks weird to write nouns in lowercase.

To avoid these problems, translations should generally be done in complete sentences and not by combining parts of sentences. While it may work in English, the grammar of other languages is largely different.

**Comment by TheReal1604** [comment]
Hey @rillig-nm,

i think you can fix this by yourself with "lingohub".

The Rocket.Chat team use that tool, to translate all the things to the language the users want.

@Sing-Li or @marceloschmidt Can give you more information about this.

**Comment by rillig-nm** [comment]
I don't think I can fix this as a translator alone. If I were to translate "Cancel" with "abzubrechen" (as required in this case), it would become wrong in other places where "Abbrechen" is the correct translation. Therefore, this must be fixed in the code.

**Comment by rasos** [comment]
I have fixed this in Lingohub for the German langauge. I applied a shortened wording to circumvent the grammar problem:
Esc: Abbrechen
Enter-Taste: Änderungen speichern
Using "Key: meaning" should be very clear and not affect any other appearances. I recommend to translate that way also in other languages.

**Comment by rillig-nm** [comment]
That looks great. Since this only affect these two keys, it was indeed simple. I just couldn't see it. :)
