### ISSUE TITLE
bug: renaming channels

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#4254]
I am running .39 RC Version.

I can not rename a (private) channel via the info sidebar. The option is there, entering the name is working too; but hitting enter and the "save" button have no effect.

**Comment by MartinSchoeler** [comment]
@christianreiss this is strange, i tried to reproduce this bug with no success, could you give us more information? 
Thanks!

**Comment by christianreiss** [comment]
I recorded a video: https://misc.alpha-labs.net/renaming.ogv

**Comment by MartinSchoeler** [comment]
@christianreiss That is very strange indeed, can you see if there is anything in the server log?

**Comment by engelgabriel** [comment]
This was fixed by https://github.com/RocketChat/Rocket.Chat/pull/4226 and will be on the next release.
