### ISSUE TITLE
Problems when I change from a chat to another chat - The talks crashes  at all. 

### ISSUE THREAD

**Issue by victormuramoto** [RocketChat/Rocket.Chat#4258]
Your Rocket.Chat version: 0.39.0)

The talks are crashing when I change from a chat to another.

The following print shows the error:
![screen shot 2016-09-09 at 2 34 47 pm](https://cloud.githubusercontent.com/assets/9921593/18396834/e9714614-769b-11e6-822b-6fc309225e5b.png)

**Comment by MartinSchoeler** [comment]
@victormuramoto could you give us more info? like where are you using rocket chat and how to reproduce the bug?

**Comment by victormuramoto** [comment]
Well, I am using the RocketChat inside my company, I don't have all the info of how RocketChat is configured right here. If you need more info, I can talk with the responsible one that maintain the RocketChat right here.

 I am using   Franz + RocketChat and i just changed from a chat to another chat and the interface just "merged" the two chats.
 I don't know if Franz + RocketChat have anything about this bug, but I talked to a co-worker that is using RocketChat at the web browser and had the same problem too. 

 The print also shows that I was uploading a .png, maybe this could help too.

One more info, This errors happened when the RocketChat was in a period of latency, it was a little slow to load the chats. 

Right know the team responsible for the RocketChat just raised the resources  and rebooted the RocketChat's server

**Comment by alexandrezia** [comment]
We have this issue here too, 
Just switching channels sometimes causes this issue
Using latest develop branch 5232fbf5c015ac3c79a97d722f9d4dfc3511100f

**Comment by rodrigok** [comment]
@alexandrezia Any ideia on how to reproduce?

**Comment by alexandrezia** [comment]
I'm still trying to find out how to reproduce it

**Comment by MartinSchoeler** [comment]
Haven't seen this bug in a while. I will close this issue for now, feel free to reopen this if the problem appears again. Thanks!
