### ISSUE TITLE
Need help SSO with a java web application

### ISSUE THREAD

**Issue by vmnet04** [RocketChat/Rocket.Chat#4264]
I have a web application that is built on Java.
Currently this site is integrated with LDAP and users can use their MS Active directory credentials to Login and view the pages they have access to.
I am trying to add a chat link at the bottom of the page. The user should be able to click on the link and start communicating without the need to Login to Rocket Chat again.
I am looking for someone who has knowledge on how to achieve this.,I am willing to pay for their time.

**Comment by Sing-Li** [comment]
This is not a valid issue against the FOSS project.  

Closing it now.

Please use form at https://rocket.chat/services  or  find a freelance dev community member on https://demo.rocket.chat   

Thanks.

**Comment by vmnet04** [comment]
Thanks Li,i used the form on rocket.chat/services
