### ISSUE TITLE
Issue using Apache2

### ISSUE THREAD

**Issue by andrewwiik** [RocketChat/Rocket.Chat#4266]
Your Rocket.Chat version: latest as of 3 hours ago

Hello,

I am trying to run a Rocket Chat instance behind Apache, my apache version is 2.4.7, I have enabled all the web socket apache things and confirmed they are enabled.

My apache2 configuration:

```
<VirtualHost *:443>

ServerAdmin REDACTED
ServerName chat.vthscomputer.club
ErrorLog /var/log/chat.domain.com_error.log
TransferLog /var/log/chat.domain.com_access.log
LogLevel info
SSLEngine On
SSLCertificateFile /etc/letsencrypt/live/chat.vthscomputer.club/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/chat.vthscomputer.club/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/chat.vthscomputer.club/chain.pem

<Location />
        Order allow,deny
        Allow from all
</Location>

ProxyPreserveHost On
ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3255/sockjs/$1/websocket
ProxyPass / http://localhost:3255/
ProxyPassReverse / http://localhost:3255/

</VirtualHost>
```

This doesn't work, I am never presented with a login form, I have tried tons of other configurations found in other issues and they also didn't work. I am on Ubuntu 14.04 on a Digital Ocean VPS instance. 
#### Other configurations tried:

[Config 1](https://github.com/RocketChat/Rocket.Chat/issues/1061)

[Config 2](https://github.com/RocketChat/Rocket.Chat/issues/1483)

[Config 3](https://github.com/RocketChat/Rocket.Chat/issues/4123)

Thanks for your time,
Andrew Wiik

**Comment by TheReal1604** [comment]
Hey @andrewwiik,

make sure your rocketchat container or instance is listening on port 3255. Can you test this and check if you reach the instance without the reverse proxy? 

I don't think it's a rocketchat issue because all of my setups are working this way. But I use the default port 3000 on my docker rocketchat container. 

If you need further assistance you can write a pm on the demo system also and we can discuss all the steps. (TheReal-1).

Greetings
TheReal

**Comment by atikulhaider** [comment]
Here are some configuration to check:
**1.** Make sure port 3255 is open
**2.** Remove those from VirtualHost blocks:
`<Location />
        Order allow,deny
        Allow from all
</Location>`
**3.** Your certificates are not correctly ordered:
Keep this line outside VirtualHost block: 
`Include /etc/letsencrypt/options-ssl-apache.conf`

Try using above config. If no result, try removing this line:
`ProxyPassMatch ^/sockjs/(.*)/websocket ws://localhost:3000/sockjs/$1/websocket`

**Comment by andrewwiik** [comment]
@atikulhaider your solutions did not work and @TheReal1604 couldn't figure out why it wasn't working either

**Comment by zoopla** [comment]
Hi here my Apache configuration, it's working (Rocket.Chat listening on localhost:3000 and replace hostname with your hostname naturally) , you can try something similar.

```
<VirtualHost *:7080>
    ServerName myhostname
    ServerAlias myotherhostname
    Redirect / https://myhostname
</VirtualHost>

<VirtualHost *:7443>
        ServerName myhostname
        ServerAlias myotherhostname
        ProxyPreserveHost On

        LogLevel info
        SSLEngine On
        SSLOptions +StrictRequire
        SSLCertificateFile /etc/letsencrypt/live/myhostname/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/myhostname/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Location />
                Order allow,deny
                Allow from all
                ProxyPass http://localhost:3000/
                ProxyPassReverse http://localhost:3000/
        </Location>

</VirtualHost>
```

I also had to enable some Apache module (not sure they are all required...)

```
sudo a2enmod ssl
sudo a2enmod proxy
sudo a2enmod proxy_balancer
sudo a2enmod proxy_http
sudo a2enmod proxy_wstunnel
```


Good luck

**Comment by andrewwiik** [comment]
@zoopla Your configuration did not work and i don't know how it even does because you don't have any rules regarding the web sockets, which should throw a 400 error unless you have something in your apache2 configuration file. Thanks for your time.

**Comment by TheReal1604** [comment]
I looked with @andrewwiik at his configuration, all seems fine. But i think there could be a digitalocean / droplet configuration thingy that is bad and cause this issues. Andrew now try to install rc with docker components again.

**Comment by geekgonecrazy** [comment]
Did this get resolved?  Is apache2 a must?  If not i'd give nginx a try.

**Comment by geekgonecrazy** [comment]
Going to go ahead and close this.  Please check our documentation on [apache2](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy).  We've improved the example given there.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
