### ISSUE TITLE
Mobile Push Channel Notification 

### ISSUE THREAD

**Issue by zoopla** [RocketChat/Rocket.Chat#4270]
My Rocket.Chat version: 0.39.0

Hi, I have some issue with the Mobile Push configuration and I think there is a bug.
In the Notification panel of a channel, when I choose other than "Mentions (Default)" for Desktop Notification, then the settings in "Mobile push" are not taken into account (the default one is used "Mentions (Default)" ).

I look really quickly at the code (I don't know javascript) but I think it makes sense with the code in packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js (second else-if should be an if ?)

``` javascript
	RocketChat.models.Subscriptions.findNotificationPreferencesByRoom(room._id).forEach(function(subscription) {
		if (subscription.desktopNotifications === 'all') {
			settings.alwaysNotifyDesktopUsers.push(subscription.u._id);
		} else if (subscription.desktopNotifications === 'nothing') {
			settings.dontNotifyDesktopUsers.push(subscription.u._id);
		} else if (subscription.mobilePushNotifications === 'all') {
			settings.alwaysNotifyMobileUsers.push(subscription.u._id);
		} else if (subscription.mobilePushNotifications === 'nothing') {
			settings.dontNotifyMobileUsers.push(subscription.u._id);
		}
		settings.desktopNotificationDurations[subscription.u._id] = subscription.desktopNotificationDuration;
	});
```

If you can take a look and see if there is really an error.

Thank you for your time,
Axel

**Comment by MartinSchoeler** [comment]
@zoopla yes you are right, thanks!
