### ISSUE TITLE
Can't connect to custom Rocket.Chat Window Server using mobile app

### ISSUE THREAD

**Issue by SongTreasure** [RocketChat/Rocket.Chat#4273]
Hi.
I installed rocket.chat server on windows 10.
Chat server work on web.
But on mobile app cannot connect server.
Server no convert https.
Can't find convert https for rocket.chat server on windows.
Can connect on mobile app to windows server?

**Comment by wargamesqcf** [comment]
I think the mobile app is old and broken and won't connect to any new server.

**Comment by geekgonecrazy** [comment]
Mobile support is not currently supported with windows builds.  

See #3631
