### ISSUE TITLE
Leave unpinned history as a message

### ISSUE THREAD

**Issue by takavfx** [RocketChat/Rocket.Chat#4274]
Your Rocket.Chat version: (v0.39.0)

How about a pin function to leave unpinned history as a message?
After unpinned messages then people in the room notice each task has done.
This is not flashy thing but it's efficient, isn't it?

Thanks!

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
