### ISSUE TITLE
Chinese Traditional(Taiwan) "繁体中文（台湾）" doesn't work.

### ISSUE THREAD

**Issue by rankun203** [RocketChat/Rocket.Chat#4277]
Your Rocket.Chat version: (0.39.0)

After I check the language of "繁体中文（台湾）", it backs to Chinese Simplified(中文) instead of Chinese Traditional language(繁体).

I've checked the translation file, it's already there, but the interface failed to use it.

**Comment by MartinSchoeler** [comment]
I think it might have something to do with the uppercase in the "zh-TW" since this happens with other languages that have "-" after its name

**Comment by MartinSchoeler** [comment]
![capture2](https://cloud.githubusercontent.com/assets/20868078/18473509/b6f1e608-7993-11e6-8092-e1b7d9d324bd.PNG)

**Comment by rankun203** [comment]
Yes, the server got the `zh-TW` language setting, but the frontend just load the part before `-`.

```coffeescript
@setLanguage = (language) ->
	if !language
		return

	if loadedLanguages.indexOf(language) > -1
		return

	loadedLanguages.push language

	if isRtl language
		$('html').addClass "rtl"
	else
		$('html').removeClass "rtl"

	language = language.split('-').shift() // startup.coffee#42
	TAPi18n.setLanguage(language)

	language = language.toLowerCase()
	if language isnt 'en'
		Meteor.call 'loadLocale', language, (err, localeFn) ->
			Function(localeFn)()
			moment.locale(language)

```

What would this split('-').shift() use for? Will something break if I remove this line?

**Comment by rankun203** [comment]
Is there any update on this?

**Comment by garychapman** [comment]
@RoecketChat/core Could we get some clarification on this please? We're about to utilise this functionality with both mainland and Taiwanese Chinese customers. Thanks!
