### ISSUE TITLE
Missing settings menus

### ISSUE THREAD

**Issue by mikrobyte** [RocketChat/Rocket.Chat#4282]
Your Rocket.Chat version: 0.39.0

This happens from time to time and it doesnt matter what OS my client is Win or Linux. Also tried with Chrome, Firefox on both operative systems.

The settings list was like this
![selection_218](https://cloud.githubusercontent.com/assets/17494740/18464831/b50cf1c0-7993-11e6-9a5b-c88fb08f12fd.png)

But then, suddenly it starts looking like this, with plenty of setting menus missing

![selection_219](https://cloud.githubusercontent.com/assets/17494740/18464845/c8afc25c-7993-11e6-99f6-6bbfd9d0c86d.png)

Any idea of what is going on?

**Comment by MartinSchoeler** [comment]
@mikrobyte  does this happens from time to time? and what modifications you made on rocket chat?

**Comment by mikrobyte** [comment]
This has happened to me before even without changing any setting at all in rocket chat. However, i noticed it only started happening with version 0.37.0. Sometimes it only happens in chrome and not in firefox, but then it started again with firefox.

i have no clue how to debug it... this is the page source info when the menus are missing.

`<!DOCTYPE html>
<html>
<head>

<base href="/">

  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/a933a431253ec0900480e68055e40edd805a12d8.css?meteor_css_resource=true">  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/theme.css?a17c8d282574bca76c1b5fb17af784abdc22f0da">


<script type="text/inject-data">%7B%22fast-render-data%22%3A%7B%22collectionData%22%3A%7B%22users%22%3A%5B%5B%7B%22emails%22%3A%5B%7B%22address%22%3A%22haha%40hihi.com%22%2C%22verified%22%3Afalse%7D%5D%2C%22username%22%3A%22Leo%22%2C%22_id%22%3A%22tbcMX8bKTBsbX3GwS%22%7D%5D%5D%7D%2C%22subscriptions%22%3A%7B%22meteor.loginServiceConfiguration%22%3A%7B%22%5B%5D%22%3Atrue%7D%7D%2C%22loginToken%22%3A%22e6VUEl5j0bfEzG6-qAf5_pc_i-nGRoJk_BiyI09K6CP%22%7D%7D</script>
<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.2.1%22%2C%22PUBLIC_SETTINGS%22%3A%7B%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Funder.chat%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22accountsConfigCalled%22%3Atrue%2C%22autoupdateVersion%22%3A%22614fc6b9fdb139c9d77cf24854bc6ade87f6e679%22%2C%22autoupdateVersionRefreshable%22%3A%224e35a11b2ad06286dcbbed8595bd114bf3c0ffc5%22%2C%22autoupdateVersionCordova%22%3A%2247527de091e5d3568a21a135d18c9cd96a20490b%22%7D"));</script>

  <script type="text/javascript" src="/3d0a28d904f450b3cfeed1ccc35c905f68483edb.js?meteor_js_resource=true"></script>



<title>Rocket.Chat</title>
	<meta charset="utf-8" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="expires" content="-1" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="fragment" content="!" />
	<meta name="distribution" content="global" />
	<meta name="rating" content="general" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
	<meta name="msapplication-TileColor" content="#04436a">
	<meta name="msapplication-TileImage" content="images/logo/mstile-144x144.png?v=3">
	<meta name="msapplication-config" content="images/logo/browserconfig.xml?v=3">
	<meta name="theme-color" content="#04436a">
	<link rel="manifest" href="images/logo/manifest.json?v=3">
	<link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/nocfbnnmjnndkbipkabodnheejiegccf">
	<link rel="icon" sizes="any" type="image/svg+xml" href="assets/favicon.svg?v=3">
	<link rel="icon" sizes="256x256" type="image/png" href="assets/favicon_256.png?v=3">
	<link rel="icon" sizes="192x192" type="image/png" href="assets/favicon_192.png?v=3">
	<link rel="icon" sizes="128x128" type="image/png" href="assets/favicon_128.png?v=3">
	<link rel="icon" sizes="96x96" type="image/png" href="assets/favicon_96.png?v=3">
	<link rel="icon" sizes="64x64" type="image/png" href="assets/favicon_64.png?v=3">
	
	<link rel="shortcut icon" sizes="16x16 32x32 48x48" type="image/x-icon" href="assets/favicon_ico.ico?v=3" />
	<link rel="apple-touch-icon" sizes="57x57" href="images/logo/apple-touch-icon-57x57.png?v=3">
	<link rel="apple-touch-icon" sizes="60x60" href="images/logo/apple-touch-icon-60x60.png?v=3">
	<link rel="apple-touch-icon" sizes="72x72" href="images/logo/apple-touch-icon-72x72.png?v=3">
	<link rel="apple-touch-icon" sizes="76x76" href="images/logo/apple-touch-icon-76x76.png?v=3">
	<link rel="apple-touch-icon" sizes="114x114" href="images/logo/apple-touch-icon-114x114.png?v=3">
	<link rel="apple-touch-icon" sizes="120x120" href="images/logo/apple-touch-icon-120x120.png?v=3">
	<link rel="apple-touch-icon" sizes="144x144" href="images/logo/apple-touch-icon-144x144.png?v=3">
	<link rel="apple-touch-icon" sizes="152x152" href="images/logo/apple-touch-icon-152x152.png?v=3">
	<link rel="apple-touch-icon" sizes="180x180" href="images/logo/apple-touch-icon-180x180.png?v=3">
</head>
<body>

	<div id="initial-page-loading" class="page-loading">
		<div class="loading">
			<i class="icon-spinner animate-pulse"></i>
		</div>
	</div>


</body>
</html>
`

**Comment by mikrobyte** [comment]
I also see this when "inspecting element" on the settings menu.


          unreachable code after return statement[Learn More]3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:521:20414
CachedCollection subscriptions => Init on login3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => Init on login3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => 156 records loaded from cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => 4 records loaded from cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => 58 records loaded from cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
window.controllers is deprecated. Do not use it for UA detection.nsHeaderInfo.js:412:8
CachedCollection private-settings => 367 records loaded from cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => syncing from Thu Jan 01 1970 01:00:00 GMT+0100 (CET)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => 156 records updated in sync3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => saving cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => saving cache (done)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => syncing from Tue Sep 13 2016 13:46:54 GMT+0200 (CEST)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => saving cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => saving cache (done)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => syncing from Sun Sep 11 2016 21:16:47 GMT+0200 (CEST)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => saving cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => saving cache (done)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => syncing from Thu Jan 01 1970 01:00:00 GMT+0100 (CET)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => 156 records updated in sync3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => saving cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection public-settings => saving cache (done)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => syncing from Tue Sep 13 2016 13:46:54 GMT+0200 (CEST)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => saving cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection subscriptions => saving cache (done)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => syncing from Sun Sep 11 2016 21:16:47 GMT+0200 (CEST)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => saving cache3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
CachedCollection permissions => saving cache (done)3d0a28d904f450b3cfeed1ccc35c905f68483edb.js:190:9242
Error: Meteor does not currently support objects other than ObjectID as ids

**Comment by MartinSchoeler** [comment]
@mikrobyte 
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by MartinSchoeler** [comment]
Closing this due lack of response
