### ISSUE TITLE
"Has more..." just sits there

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#4285]
Since 0.39.0, when switching private channels, all that is shown is "has more.." and I have to click it to get the channel to load.. it's becoming a huge time sink and users are complaining about it...

**Comment by nowacki-lukasz** [comment]
true story... we really need this to work :+1:

**Comment by bmogadorski** [comment]
damn, how annoying it is :)

**Comment by rodrigok** [comment]
@sinteur @nowacki-lukasz @bmogadorski Are you using our branch `develop`?

**Comment by sinteur** [comment]
no - just 0.39.0 from the downloads page

**Comment by engelgabriel** [comment]
@sinteur are you using the Stable or Beta?

**Comment by sinteur** [comment]
this one:  https://rocket.chat/releases/0.39.0/download

**Comment by engelgabriel** [comment]
OK, this was fixed here: https://github.com/RocketChat/Rocket.Chat/commit/fecae37360efe9e9bc7193483f48990f4082d442

**Comment by sinteur** [comment]
Thx!
