### ISSUE TITLE
cannot upload files

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#4289]
cannot upload any kind of files either with drag & drop or with open file

Running latest version of rocketchat/rocket.chat:develop created 26 minutes ago

**Comment by Lucky21110** [comment]
same issue for me using develop

**Comment by engelgabriel** [comment]
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/4235 and @rodrigok is working on it.
