### ISSUE TITLE
cog menu bugged on mobile

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#4291]
When you press on someones name on in the feed to access the cog wheel menu, it bugs out if the keyboard is up and some part of the list is behind the keyboard. Now when the done button is removed for the keyboard it's much harder to get out of there. 
Would be nice if the menu pops the keyboard force closes.

![14360357_10157733260820643_622839659_o](https://cloud.githubusercontent.com/assets/17712562/18493023/b6f24dc0-7a0e-11e6-8404-94cd44ab882c.jpg)

**Comment by MartinSchoeler** [comment]
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
