### ISSUE TITLE
Notification API

### ISSUE THREAD

**Issue by Perksls** [RocketChat/Rocket.Chat#4303]
Not an issue just a request, is it possible to add an unread notifications API?

This would be an easy way to create a browser extension that would update the badge with notifications, among other things

**Comment by lucasvanhalst** [comment]
If it is only for notifications I would suggest implementing a service worker instead https://developer.mozilla.org/en/docs/Web/API/Service_Worker_API
Those can also send push notifications, but you don't need to install an extension for it.

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
