### ISSUE TITLE
Cannot remove a role if a role has too many users

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#4308]
version: 0.39.0
In Administration->persmissions-> click on the small icon next to role name

A user list is limited in lenght, and I cannot remove the role from a user if he is alphabetically too late in the list

**Comment by MartinSchoeler** [comment]
@sinteur could you post a screenshot to help us recognize the bug? Thanks!

**Comment by sinteur** [comment]
List of users starts alphabetically. Icon on the right is to remove role.

The list is only a limited amount of users long. If I want to remove the role from Zachadeus I'm out of luck, since he is not listed on this screen and I have no way to get him listed. Well, perhaps if I first remove 95% of the other users from the system....

![screen shot 2016-09-15 at 13 44 20](https://cloud.githubusercontent.com/assets/13427371/18548769/cfbe1356-7b4a-11e6-90ae-eb26a4ba561d.png)

**Comment by goobersmooch** [comment]
I'm having the exact same problem.

**Comment by MartinSchoeler** [comment]
@sinteur today you can click on 'view more' button.I know this is not the best solution for this but we are planning some serious changes on this part of the ui.
