### ISSUE TITLE
OpenID authentification

### ISSUE THREAD

**Issue by kmi9work** [RocketChat/Rocket.Chat#4310]
Is there any way to add OpenID authentification through my own server in Rocket.chat? Is there any documentation about it?

**Comment by kmi9work** [comment]
I newbie in OpenID, so it would be perfect if somebody competent just say yes or no. Should I try further or find another way.

**Comment by LiraNuna** [comment]
I think it's possible based on what I've seen. Try looking at https://[your-server]/admin/OAuth and adding a new custom oauth app. If the oauth app supports the `openid` scope it should be simple to add.

**Comment by geekgonecrazy** [comment]
@kmi9work OpenID is an authentication provider.  You can use it plus SAML / OAUTH etc to provide authorization into Rocket.Chat since we have oauth / saml support.

I'd suggest taking a look at OpenID and oauth.  Would be the easiest way to integrate.
