### ISSUE TITLE
Various Users Unable To View File Uploads

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#4312]
Your Rocket.Chat version: .38

We have a few users that are unable to view files. User A shared an image in an Direct Message to User B. User B is unable to view the image as it just shows as an empty box. When User B attempts to download the file, they receive an error "Failed - Forbidden".

Anyone else noticing this?

**Comment by MartinSchoeler** [comment]
yes @richardwlu this post is a duplicate of this one #4252
