### ISSUE TITLE
Attach file icon stucked on mobile

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#4314]
when you paste something like a link or a normal text, the attach file Button doesn't change to the send Button. You must start typing something before u can access the send Button. 
![image](https://cloud.githubusercontent.com/assets/17712562/18560178/c64ef1de-7b7a-11e6-95fe-0ceca00d9c00.png)

**Comment by MartinSchoeler** [comment]
@Molle500 Tested on the latest version and it is working, please reopen this if the issue persists. Thanks!
