### ISSUE TITLE
New conversations do not work until a page reload

### ISSUE THREAD

**Issue by alexandrezia** [RocketChat/Rocket.Chat#4322]
Your Rocket.Chat version: (latest 0.39.0)

when you start a new conversation with someone you've have spoken before, the sent messages appears greyed out, and the answers are not shown.
After a page restart (Command+R/Control+R) the conversation works as expected
The other side will sees your messages
If answer was sent, on the user list you will see a notification and number of unread messages, but you will not be able read until the reload.

**Comment by engelgabriel** [comment]
Ref: https://github.com/RocketChat/Rocket.Chat/issues/4322

**Comment by engelgabriel** [comment]
Reported by https://github.com/Movile/Rocket.Chat/issues/2

**Comment by engelgabriel** [comment]
@MartinSchoeler can you please try to replicate this?
