### ISSUE TITLE
How to link cloud based Rocket chat to my website App

### ISSUE THREAD

**Issue by shadowreturns** [RocketChat/Rocket.Chat#4324]
Your Rocket.Chat version: (make sure you are running the latest)
Hey guys,

Im trying to integrate/link Rocket Chat (cloud based one) to my web site app with is made from java, the idea is that there would be a facebook like chat box in my Java app. So that my users don't need to have rocket chat and my app opened. 

Im been reading around and im stuck on this. 

Help would be appreciated.

**Comment by shadowreturns** [comment]
Any help would be greatly appreciated. Is it possible to do it ? If not are there any other alternatives or any possible solutions ?

**Comment by matthewshirley** [comment]
You could use the Rocket.Chat API to send and receive messages. You would have to implement the style yourself. https://rocket.chat/docs/developer-guides/rest-api/

**Comment by MartinSchoeler** [comment]
Closing this issue due lack of updates in a long time.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)

Thanks!
