### ISSUE TITLE
Incorrect avatar image on Chrome 53

### ISSUE THREAD

**Issue by nishimaki10** [RocketChat/Rocket.Chat#4325]
Your Rocket.Chat version: 0.39.0

Could not render svg and not animated gif on Chrome 53.

![ss](https://cloud.githubusercontent.com/assets/9736483/18582173/bd7aa264-7c3e-11e6-8d43-45357ba5bfc1.png)

**Comment by simsinteractive** [comment]
Yes I've reported a related bug when using an SVG sprite sheet as a background.  On Chrome 53 results in corrupted background positioning and sizing - and sensitivity to browser window zooming.
