### ISSUE TITLE
Method to view channels with long names

### ISSUE THREAD

**Issue by doctorwho92** [RocketChat/Rocket.Chat#4328]
Your Rocket.Chat version: (0.39.0)
Channels with names longer than approx 22 characters get truncated in the UI left sidebar. I'd like to see a method where I can either:
A. Adjust the width of the client sidebar to reveal the longer names (manual and/or default=autofit);
B. Adjust the font size of the left sidebar to allow channels names to fit without truncation;
C. Allow an admin option to choose between truncation = left justified, or truncation = middle out.
D. Any other suggestions.

Our problem is channel names = Client_Product_Project_uidnumber and the only thing potentially differentiating two project channels might be the uidnumber.

**Comment by gabriellsh** [comment]
Just found out that you can hover over the room and it displays its full name. You can read the room name if you open it, it's always displayed on top, even if you didn’t join it. Does this help you?

![image](https://user-images.githubusercontent.com/40830821/72072187-27c28c80-32cc-11ea-93b5-52f598db98e5.png)

Also if you set your sidenav view mode to condensed, most of the text is displayed. If you still find that there is a need for something other than the alternatives above, please reopen this issue.
