### ISSUE TITLE
If there are points of administrators and ordinary users

### ISSUE THREAD

**Issue by guoyoujin** [RocketChat/Rocket.Chat#433]
Whether has the branch of administrators and ordinary users, if not, may go against management

**Comment by marceloschmidt** [comment]
@guoyoujin I'm sorry, we could not understand what the issue is. Can you explain a little better? Thanks.

**Comment by Sing-Li** [comment]
@guoyoujin  Please post in language you are most familiar with.  Community members are likely able to translate if needed. Thanks :smile:

**Comment by engelgabriel** [comment]
@guoyoujin if you are an admin, you should see a APP SETTINGS link on the bottom of the right blue nav bar. Inside there is a link to USERS, where you can add/remove/deactivate them. More features will be added soon.
