### ISSUE TITLE
Map LDAP fields to user custom fields

### ISSUE THREAD

**Issue by doctorwho92** [RocketChat/Rocket.Chat#4332]
Your Rocket.Chat version: (0.39.0)
Link custom fields to ldap fields, and populate the custom field with those values.

Requires Rocket.Chat to have an ldap listener to update records.

**Comment by Rohlik** [comment]
This can be useful for import fields like mobile_number or department.
+1 for this feature.

**Comment by JigSawFr** [comment]
Could be great too for us !

**Comment by willihelm** [comment]
I´m waiting for this feature too. I first mapped the phonNumber to the email field but as the field is not unique in LDAP it does not work for us anymore.

**Comment by willihelm** [comment]
There is a bounty for this one on bountysource.

**Comment by willihelm** [comment]
Also it would be great to see the number directly in the chat without having to toggle the side navigation.

**Comment by willihelm** [comment]
Any news here?

**Comment by N4IR0** [comment]
+1

**Comment by Cf9L588** [comment]
I can only get custom fields to populate on existing users if I delete the users and resync them. Is there a workaround for this?
