### ISSUE TITLE
Query-based Channel/Group membership

### ISSUE THREAD

**Issue by doctorwho92** [RocketChat/Rocket.Chat#4335]
Your Rocket.Chat version: (0.39.0)

Create the ability to update the membership of channels or groups based on rules. For e.g.:
customField1 = department
customField2 = office
channel name = Marketing.US
rule = '(&(department=Marketing)(|(office=New York)(office=Chicago)(office=Los Angeles)))'*
- I'm stealing ldap syntax here. Would be nice to use that!

Considerations:
1. The channel should be able to have the rule dictate its membership exclusively;
2. The channel should be able to have the rule contribute to a channel's membership, non-exclusively (so if the CEO insists she be added to private group dev.brasil, she can be added without changing her department from Exec to Dev);
3. There should be an option to switch on an auto-channel for a custom field (maybe with a checkbox), whose membership is managed by a dynamic rule like so:
   for value in customField1.values
     channel name = $value
     rule = '(customField1 = $value)'

Dynamic groups based on rules become particularly powerful when combined with #4332

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.

**Comment by doctorwho92** [comment]
why did you close an 20 month old feature request because its not on the short term road map? I waited this long. Can wait longer.
