### ISSUE TITLE
Inline code parse issue

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#4336]
Your Rocket.Chat version: demo server

Pasting a link and using inline code immediately after it procudes this result:
![](https://i.imgur.com/4gGfzSW.png)
text used:

```
https://www.google.be/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png `test` 
```

**Comment by TwizzyDizzy** [comment]
Still present in 0.61.0

**Comment by MartinSchoeler** [comment]
Seems to be fixed in the latest release.
![screen shot 2018-10-23 at 14 35 39](https://user-images.githubusercontent.com/20868078/47379330-fc587f80-d6d0-11e8-92b1-dc38dab97d00.png)
