### ISSUE TITLE
rocket chat shows has more instead of loading client content when scrolling thru channels. 

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#4337]
Your Rocket.Chat version: (make sure you are running the latest)
0.39

we have several users with over 20 channels. when they click on one channel after another from bottom to the top and again to the bottom the second time around the channel shows has more instead of the rocketchat messages. clicking has more beings up the channel content. 
this is both the website and using the electron client. 
for users with 5-6 channels we cannot reproduce.

**Comment by admin-crowd-iugo** [comment]
![rocket_chat_issue](https://cloud.githubusercontent.com/assets/17622866/18601941/c0dd87e2-7c1a-11e6-8449-b37b24927343.png)

**Comment by admin-crowd-iugo** [comment]
example screenshot. as noted above clicking has more.... loads the channel content normally.

**Comment by admin-crowd-iugo** [comment]
ok i see a potential fix. 
https://github.com/RocketChat/Rocket.Chat/commit/fecae37360efe9e9bc7193483f48990f4082d442
if this is the fix please close the bug. thanks.

**Comment by lunitic** [comment]
Seen this issue too

**Comment by sampaiodiego** [comment]
yep, it was fixed by fecae37
