### ISSUE TITLE
Option to use Google profile pic for user avatar when using Google OAuth

### ISSUE THREAD

**Issue by paulcrick** [RocketChat/Rocket.Chat#4342]
The Google OAuth integration works great, but Rocket.Chat doesn't use the user's Google profile picture as the Rocket.Chat user avatar picture by default - each user has to go into their profile settings and switch it over to use the Google profile pic.

Would it be possible to add a setting to the Google OAuth module that would set newly created users to use the Google profile pic by default? Seems like a fairly simple change, but it's been a while since I've written any code. I'll poke around and see if I can figure this out myself, create a pull request etc, but if someone gets there before me, great!

**Comment by spinza** [comment]
I think this should be more generic.  I use custom oauth on my instance and my oauth provider provides a profile pic url on the user info call.  However Rocket.Chat does not use this profile pic.

**Comment by paulcrick** [comment]
@spinza: My request was for the supplied Google OAuth integration, but I think you raise a valid point for custom OAuth integrations. How would you feel about for custom OAuth integrations having a) an option to provide the parameter name that contains the profile pic URL, and b) an option to specify whether this should be used as the user's default avatar?

**Comment by spinza** [comment]
I suspect that both will be answered: 
The[ standard claim](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) for `profile` includes the field `picture`
>page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.
Happy to just map that.

I'm assuming Google Oauth might be using the same claim so it might be 2 birds with one stone.
Also happy to leave it as options.  Would be nice to have the option to make it the default avatar (but allowing the user to change it afterwards).

**Comment by floor12** [comment]
I`m using custom oauth but there is no way to set up user picture from custom provider 8( i was trying to add a different prop names in json (picture, avatar...) that provider  send to rocket chat with person data... but rocket chat ignore it...

**Comment by engelgabriel** [comment]
@paulcrick I believe this have been done by @marceloschmidt can you please let me know if that is working for you?

**Comment by marceloschmidt** [comment]
What we did was to enable an option to set default avatar as the oauth logged in account: https://github.com/RocketChat/Rocket.Chat/pull/5338 
There's no support for the custom oauth avatar though... should we try to use the `picture` as mentioned by @spinza or add that field in the custom oauth setting as mentioned by @paulcrick ? 

Let's just bare in mind that a few oauth providers might not even have that as a field (eg. facebook has a url for you to request the profile pic).

**Comment by engelgabriel** [comment]
@marceloschmidt try to use the picture as mentioned by @spinza

**Comment by marceloschmidt** [comment]
Just tested with a google account and it's fetching the right avatar!
