### ISSUE TITLE
Rocket.Chat Call back plugin for ansible

### ISSUE THREAD

**Issue by Deepakkothandan** [RocketChat/Rocket.Chat#4346]
Your Rocket.Chat version: (0.36.0)
Hi All,

We had to use the callback feature of Ansible and notify us on failed ansible runs through the incoming webhooks feature. So, I forked the slack callback plugin and modified it for use with rocket chat and the link to source is [Ansible Callback plugin for RocketChat](https://gist.github.com/Deepakkothandan/4808bcb4e9881e2d4fe8a643a9bab4eb)

The only issue I am facing now is that, the markup for pretty table is not being rendered by Rocket Chat. So if you could point me to a documentation or provide your inputs on, supported markups by Rocket.Chat, I could modify the script accordingly and post pretty :smile: messages.

**Comment by lucasvanhalst** [comment]
Full markdown isn't supported yet, only the most common things like headers, quotes, code, links, bold, italics and strike through
Code for it can be found here, it shouldn't be too hard to implement tables.

https://github.com/RocketChat/Rocket.Chat/blob/83e743ac030a43ac2dfc9f505aa14b2a3b981f16/packages/rocketchat-markdown/markdown.coffee

**Comment by geekgonecrazy** [comment]
Going to close this in favor of #918 Also it looks like we have a PR open that will resolve this.  :)

@Deepakkothandan i'm very interested in your ansible callback plugin though.  Would love to see this used more.  Have you published it any where?  Feel free to send me a message on the community server @ `aaron.ogle`

**Comment by Deepakkothandan** [comment]
@geekgonecrazy I have shared this as a public gist and here is the link [Ansible Rocket.Chat Callback Plugin](https://gist.github.com/Deepakkothandan/4808bcb4e9881e2d4fe8a643a9bab4eb)

**Comment by geekgonecrazy** [comment]
Thanks!
