### ISSUE TITLE
Broken, but valid hyperlinks

### ISSUE THREAD

**Issue by Cheatha** [RocketChat/Rocket.Chat#4350]
Your Rocket.Chat version: 0.39

GitLab tends to add **utf8=✓** to links, for example: https://gitlab.example.com/search?utf8=✓&search=mysearch&group_id=&project_id=42&search_code=true&repository_ref=master

When you copy/paste this link into Rocket.Chat the link will be cut off in front of **✓**: https://gitlab.example.com/search?utf8=

**Comment by MartinSchoeler** [comment]
![screenshot from 2016-09-21 08-37-11](https://cloud.githubusercontent.com/assets/20868078/18709479/c2d3ff94-7fd6-11e6-9e18-95e431b170eb.png)
Just like this

**Comment by olafleur** [comment]
The problem is solved in version 1.1.1 of Autolinker (latest version : 1.2.0) : https://github.com/gregjacobs/Autolinker.js/releases
