### ISSUE TITLE
User Profile Time Format (Create at & Last Login)

### ISSUE THREAD

**Issue by spinza** [RocketChat/Rocket.Chat#4352]
Date / Time format not consistent with site settings.
![image](https://cloud.githubusercontent.com/assets/3501598/18638474/98908e56-7e90-11e6-9bdf-2ac48b294111.png)

Note 24h format (as per site setting) for the last seen time and the AM/PM format in Created at & Last login

Your Rocket.Chat version: 0.39.0

**Comment by ura14h** [comment]
The date format in the directory page and the message timestamp in the sidebar with extended mode have the ame issue too.

**Comment by gsunit** [comment]
I would like to work on this. @spinza Please let me know how to reproduce the same. @ggazzo could you guide me to the relevant files?
