### ISSUE TITLE
Desktop app on linux + Proxy

### ISSUE THREAD

**Issue by jadolg** [RocketChat/Rocket.Chat#4357]
Your Rocket.Chat version: 1.3.1
I've tried running RocketChat exporting my proxy variables and I have not being able to connect to the demo server. I don't see any feedback on my terminal. 
Can you make it proxy-friendly? (Something like a Settings option would be really cool **Check Telegram configuration for example)

**Comment by brtptrs** [comment]
I second this request. 
Linux client version 1.3.1 can not connect to a server from behind our proxy.
This is on Ubuntu 16.04

**Comment by geekgonecrazy** [comment]
Opened an issue on that repo: https://github.com/RocketChat/Rocket.Chat.Electron/issues/407
