### ISSUE TITLE
after entering channel only "has more" is shown to user (screenshot attached)

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#4370]
RocketChat 0.39.

Hello Devs.

I get a lot of user complaints regarding the subject of this issue. 

![bildschirmfoto 2016-09-20 um 11 23 53](https://cloud.githubusercontent.com/assets/631865/18664931/0b0ae532-7f25-11e6-9923-e174c680c89f.png)

Is this a known issue? Is there a way to get around this?

thanks and cheers
t.

**Comment by lunitic** [comment]
#4285 
Seems like it solved in next release

**Comment by himbeere** [comment]
Thanks for the link.
