### ISSUE TITLE
Addition to UX : inform the user that to leave the CTRL + P dialog you can press on ESC

### ISSUE THREAD

**Issue by olafleur** [RocketChat/Rocket.Chat#4372]
Your Rocket.Chat version: 0.39.0

When entering in the CTRL + P dialog, you are obligated to select something. If you don't you are not able to get out of the dialog.

You should be able to click out of the dialog and make it disappear, don't you think? (or at least quit by doing CTRL + P again)

**Comment by MartinSchoeler** [comment]
hey @olafleur have you tried to press esc to get out of the dialog?

**Comment by olafleur** [comment]
Ha! Ha! No, but you are right, it works. :)
Maybe we should document it somewhere in the dialog?

**Comment by MartinSchoeler** [comment]
@olafleur Yes, i will leave this issue open if some one wants to take a stab at it
