### ISSUE TITLE
Documentation for Server Meteor Method API

### ISSUE THREAD

**Issue by vbasky** [RocketChat/Rocket.Chat#4374]
Your Rocket.Chat version:
0.39

Can we have documentation of API's for the server meteor methods implemented, helps building client depending on Meteor DDP API's.

**Comment by rasos** [comment]
More documentation would be great, as we are also planning to develop lightweight Apps with Qt quick for Android, iPhone and WP.

**Comment by wildaces215** [comment]
Is this still open? I would love to tackle it!

**Comment by vikramiyer** [comment]
Seems to be open. Haven't seen great strides in API documentation.

**Comment by wildaces215** [comment]
Ok where do I start to write the documentation then?

**Comment by marceloschmidt** [comment]
You could refer to our Realtime API: https://rocket.chat/docs/developer-guides/realtime-api/#realtime-api.
