### ISSUE TITLE
Title site and icons 

### ISSUE THREAD

**Issue by droup** [RocketChat/Rocket.Chat#4376]
Your Rocket.Chat version: 0.40

I'm using docker.
How can change the Title of the Main page, "Rocket.chat" appear systematically during the loading on the tab.  
Apparently due because the title of head.html file is "rocket.chat".
How can i change that because on google search it's rocket.chat the Title of my site and not my title.

Also when i go on android and iphone web browser, the rocket-chat logo appears and not my logo.  

Thank you for you answers.
and BRAVO for all of your work!

(and sorry for my bad english)

**Comment by engelgabriel** [comment]
Take should use `/packages/rocketchat-ui-master/server/inject.js` for that.

**Comment by engelgabriel** [comment]
See https://github.com/meteorhacks/meteor-inject-initial

**Comment by engelgabriel** [comment]
Or https://github.com/kadirahq/meteor-dochead
