### ISSUE TITLE
Option to sort direct messages

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#4377]
Your Rocket.Chat version: 0.40.0
It would be very useful to be able to sort private chats alphabetically (available now) or by last activity (todo). What do you think?

**Comment by Flipez** [comment]
+1

Sort by activity should be implemented for every kind of chat (privtate, public..)

**Comment by dopykuh** [comment]
+1

**Comment by gempir** [comment]
+1

**Comment by VerusK** [comment]
+1

**Comment by tarabanton** [comment]
+1 Must have for our use case. With high number of DM it's pretty hard to find recent ones.

**Comment by stevenhfotofix** [comment]
+1

**Comment by publicvirtualvoid** [comment]
+∞ it's such a productivity killer

**Comment by Svenito** [comment]
:+1: sorting by last activity helps work out who you were recently speaking to

**Comment by Gimond** [comment]
+1
Basically, i need the listing that pops out when you click the search field to be set as the default one (via a user option, ideally)

**Comment by NonlinearFruit** [comment]
:+1: Instead of ASCIIbetical sorting, a natural sort would be great (and so would an activity sort). 

One of the problems I have is finding the direct message I'm looking for because some users entered their name as `Joe.Shmoe` and others `jane.doe`. In the direct message list they are displayed as:
```
Abel.Adamson
Beverly
Joe.Shmoe
arthur.doyle
ben
jane.doe
```
I feel like alphabetical would be a more intuitive (useful) sort because I won't have to remember the capitalization of name. Something like:
```
Abel.Adamson
arthur.doyle
Beverly
ben
Joe.Shmoe
jane.doe
```

**Comment by Flipez** [comment]
Any news on this? This relatively small feature would result in a huge improvement.

**Comment by MartinSchoeler** [comment]
This feature was added in this pr #7643 go to my account -> preferences -> Sidebar channel list mode setting

**Comment by gempir** [comment]
Is this already in a release? If so which version?

**Comment by gempir** [comment]
@MartinSchoeler I think this is not what the Issue was about.

You cannot split my category and then only sort PM's by activity.

**Comment by uselessanim** [comment]
@MartinSchoeler  About sorting messages by last activity. Is there any way to enable this feature by default for my server? If no, I think it would be a very useful feature.

**Comment by FaizanZahid** [comment]
I am unable to see the direct messages channels in my sidebar, do u know how to turn it on?
