### ISSUE TITLE
Upgrade to 0.40 fails

### ISSUE THREAD

**Issue by 78c59635bdd8** [RocketChat/Rocket.Chat#4379]
Your Rocket.Chat version: 0.40.

After upgrading to 0.40 this morning, our rocketchat service fails to start:

Sep 21 07:30:32 chat systemd: Started The Rocket.Chat  server.
Sep 21 07:30:32 chat systemd: Starting The Rocket.Chat  server...
Sep 21 07:30:32 chat rocketchat: assert.js:93
Sep 21 07:30:32 chat rocketchat: throw new assert.AssertionError({
Sep 21 07:30:32 chat rocketchat: ^
Sep 21 07:30:32 chat rocketchat: AssertionError: "undefined" === "function"
Sep 21 07:30:32 chat rocketchat: at wrapPathFunction (/root/Rocket.Chat/programs/server/mini-files.js:77:10)
Sep 21 07:30:32 chat rocketchat: at Object.<anonymous> (/root/Rocket.Chat/programs/server/mini-files.js:108:24)
Sep 21 07:30:32 chat rocketchat: at Module._compile (module.js:456:26)
Sep 21 07:30:32 chat rocketchat: at Object.Module._extensions..js (module.js:474:10)
Sep 21 07:30:32 chat rocketchat: at Module.load (module.js:356:32)
Sep 21 07:30:32 chat rocketchat: at Function.Module._load (module.js:312:12)
Sep 21 07:30:32 chat rocketchat: at Module.require (module.js:364:17)
Sep 21 07:30:32 chat rocketchat: at require (module.js:380:17)
Sep 21 07:30:32 chat rocketchat: at Object.<anonymous> (/root/Rocket.Chat/programs/server/boot.js:9:13)
Sep 21 07:30:32 chat rocketchat: at Module._compile (module.js:456:26)
Sep 21 07:30:32 chat systemd: rocketchat.service: main process exited, code=exited, status=8/n/a
Sep 21 07:30:32 chat systemd: Unit rocketchat.service entered failed state.
Sep 21 07:30:32 chat systemd: rocketchat.service failed.

**Comment by Cheatha** [comment]
Try `sudo n install 4.5` as [suggested in the docs](https://rocket.chat/docs/installation/updating/from-0-x-x-to-0-40-0/).

**Comment by rauhmaru** [comment]
> `n 4.5`

**Comment by 78c59635bdd8** [comment]
Thanks a lot.  I dug through the tar file looking for upgrade notes.  Guess I should have looked on the website.  Thanks!

**Comment by angshallen** [comment]
Perhaps worth mentioning, I had to do:
ln -sf /usr/local/n/versions/node/4.5.0/bin/node /usr/bin/node
to get 4.5.
