### ISSUE TITLE
Red square box on Livechat - Bug

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#4383]
Your Rocket.Chat version: 0.40

I've a small bug, on my livechat box when I'm unauthenticated I got a little red square box that always appears a few seconds after opening the livechat box. It skip the registration form.
I think it's related to the advanced modifications that my staff made on our Rocket Chat but I don't know the cause. I don't have this kind of bug on a fresh install.

URL of the livechat: https://aresrpg.fr/livechat.html
![capture du 2016-09-21 15-44-26](https://cloud.githubusercontent.com/assets/4016501/18713355/4bff8b40-8012-11e6-87b8-5cc07d8ba5ef.png)

**Comment by sampaiodiego** [comment]
hi.. you (or someone on your team) have created an empty trigger.
that's why it skips the registration form.

the trigger's UI is far from the best, you can go on `Livechat > Triggers` and click on `delete` button. it should "fix" the issue.

**Comment by unixfox** [comment]
It works, thank you.
