### ISSUE TITLE
DM email notification: add Reply-To header with sender’s email address if it is known

### ISSUE THREAD

**Issue by amiryal** [RocketChat/Rocket.Chat#4384]
In the current implementation, hitting Reply on a direct-message notification email creates a message to the instance’s configured From address.

Changing the From header is not always easy, and some ESPs don’t allow to change it dynamically at all. However, adding a Reply-To header should be easy enough to implement, if the email address of the direct-message sender is known.

Your Rocket.Chat version: 0.40.0

**Comment by rodrigok** [comment]
Closed via #7342
