### ISSUE TITLE
Allow disable LDAP synchronization for user

### ISSUE THREAD

**Issue by mjasion** [RocketChat/Rocket.Chat#4385]
Your Rocket.Chat version: 0.40.0

In collection `users` user that has been authenticated by LDAP has set flag `ldap: true`. To disable synchronization with LDAP for this user I have to set this flago to `false`

It would be nice to edit this flag from Administration UI

In gitlab i can remove LDAP identity by clicking button as below:
![image](https://cloud.githubusercontent.com/assets/5058132/18718738/d17332f6-8024-11e6-8133-b0ddd2a9b342.png)

**Comment by Jamie-Owen** [comment]
As the code stands right now setting `ldap: false` in the user document essentially disables LDAP auth (for this user) and they can't log in anymore (Even with fallback set to true). This field is not solely responsible for synchronising LDAP data (name, email)... At least with the LDAP settings that I have currently. 

You can set 'Merge existing users' to true, but then it sets `ldap: true` again in the DB, so my question is, are you wanting a way to add/remove the user management from LDAP for certain users or just the syncing of user data?
