### ISSUE TITLE
Allow setting profile image using Webcam

### ISSUE THREAD

**Issue by xasx** [RocketChat/Rocket.Chat#4386]
Your Rocket.Chat version: latest

Simple feature request:
The profile picture page `changeavatar' should allow to set the avatar from the locally installed Webcam.

jhuckaby/webcamjs might be a starting point for further research (browser side).

Demo: https://pixlcore.com/demos/webcamjs/demos/basic.html

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.
