### ISSUE TITLE
Custom Script for logged out users - Not Working

### ISSUE THREAD

**Issue by MastricX** [RocketChat/Rocket.Chat#4396]
Your Rocket.Chat version: 0.40

Granted I may be doing something wrong, but the last view versions the 'Custom Script for logged out users' has not functioned for me. Today I tested it on rocket.chat/deploy and confirmed it there as well.

Simple Script such as;
console.log("Hello World");
Won't run when placed in 'Custom Script for logged out users', works fine in 'Custom Script for logged in users'. The code does show up in the source, but doesn't execute and I'm not sure why, no visible JS errors in console.

**Comment by IQ2022** [comment]
is this script used for users log in on sites like wordpress for example and when they click on the chat, it will log them right in?

**Comment by k0nsl** [comment]
Confirmed!

I tested this for logged out users:
`console.log("Hello #1");`

And this for logged in users:
`console.log("Hello #2");`

They do not work.

**Comment by engelgabriel** [comment]
@MartinSchoeler please test this and create a custom test on our CI for it too.

**Comment by MartinSchoeler** [comment]
@MastricX strange, for me its working. Is this still happening in the latest version?

**Comment by MastricX** [comment]
@MartinSchoeler 
Checked again, Logged In is working
Logged Out is not.
