### ISSUE TITLE
Add setting to set oembed cache validity

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#4397]
It would be nice if we'd be able to choose how long the url previewer should cache things for, to both keep the database smaller and to get accurate/up to date previews.

Perhaps a list of urls that should only be cached for a very short time (a couple of hours) would also be nice. Use case for this would be to post the same url in the chat often, but the content behind the posted url changes every few minutes (a statistics page, for example)

As discussed here https://demo.rocket.chat/channel/support?msg=v9LBw9kPCFBzScpPd

**Comment by michaelPf85** [comment]
It looks like it has been implemented since 335b08c already, we could close it.

**Comment by lucasvanhalst** [comment]
Only partly, the part about ignoring some URL's isn't in there. But that should've been a separate issue anyway so I'm closing it
