### ISSUE TITLE
Copy Paste issue in mobile applicaiton

### ISSUE THREAD

**Issue by 8754463964** [RocketChat/Rocket.Chat#4399]
Your Rocket.Chat version: 0.40.0
   we cant copy and paste the previous chat history message. If I click and hold I'm getting copy option but its not copy. When I am past somewhere its not pasting.

**Comment by heunland** [comment]
on latest version of android app I find that I cannot copy selected text, if I try to do so it copies the entire comment to the clipboard but when I then try to paste it somewhere else it ends up pasting some other text I had previously on my clipboard from a totally different app.

**Comment by MartinSchoeler** [comment]
@8754463964 Tested on the latest version and it is working, please reopen this if the issue persists. Thanks!
