### ISSUE TITLE
Block message editing after 10min?

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#44]

**Comment by rodrigok** [comment]
@engelgabriel @marceloschmidt @sampaiodiego @rcaferati What do you think about this?

Maybe we can add this as an option in minutes:
* 0: no limit editing
* 1+: time to edit since created

I think that this is useful and can be planed for v0.2

**Comment by sampaiodiego** [comment]
I don't get the part "1+: time to edit since created"

**Comment by rodrigok** [comment]
You can set 0 for disable this feature or set time in minutes to block message to be edited.

**Comment by sampaiodiego** [comment]
ok.now I get it. so, we have to define the configuration page

**Comment by rodrigok** [comment]
@sampaiodiego of course, but we can implement this functionality separated from the configuration page

**Comment by engelgabriel** [comment]
Depends on #222
