### ISSUE TITLE
OAuth with Wordpress Error

### ISSUE THREAD

**Issue by Lucky21110** [RocketChat/Rocket.Chat#4402]
Your Rocket.Chat version: 0.39 and 0.40

Hello,
I don't know why but since I moved my rocket chat to a new server, my wordpress Oauth isn't working anymore.

Here is the log 👍 

`34mW20160922-02:30:27.174(-4) (oauth_server.js:398) [35mError in OAuth Server: Failed to fetch identity from wordpress at http://www.abc.com/oauth/me. Unexpected token <
[34mI20160922-02:30:27.313(-4) Exception while invoking method 'login' Error: Failed to fetch identity from wordpress at http://www.abc.com/oauth/me. Unexpected token <     at CustomOAuth.getIdentity (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:100:16)     at Object.handleOauthRequest (packages/rocketchat_custom-oauth/custom_oauth_server.coffee:109:20)     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)     at middleware (packages/oauth/oauth_server.js:173:1)     at packages/oauth/oauth_server.js:146:1 `

Wordpress plugin : 	Oauth Server 3.1.98
WordPress Plugin Redirect URI : http://chat.abc.com/_oauth/wordpress
Rocket Chat Oauth Wordpress Config : WordPress URL : http://www.abc.com
Rocket Chat WordPress CallBack URL : http://chat.abc.com/_oauth/wordpress

Anyone can help me for that ?

Regards

**Comment by Lucky21110** [comment]
Problem resolved. This was due to plugin.

**Comment by gjsman** [comment]
Please, can you tell me how you fixed it? Because I have the same error.
