### ISSUE TITLE
Disabling file uploads in DM alone

### ISSUE THREAD

**Issue by scorpfromhell** [RocketChat/Rocket.Chat#4404]
Your Rocket.Chat version: 0.40.0

**New feature request:** Due to our corporate security restrictions we need to disable file uploads only in DMs. Can this be added as a configurable parameter in the File Upload settings screen? Maybe something like "Disable file uploads in DM" with default value of "False", but with an option to make it "True".

**Comment by juanwolf** [comment]
Can I work on this issue?

**Comment by graywolf336** [comment]
@juanwolf Go for it! 👌

**Comment by MartinSchoeler** [comment]
Hey @scorpfromhell take a look on the PR i made!  #4940

**Comment by juanwolf** [comment]
Cheers @MartinSchoeler, I did not have time to look at it :/
