### ISSUE TITLE
How to remove the buggy guest generated by 0.40.0.

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat#4409]
Your Rocket.Chat version: 0.40.1
I've a buggy guest generated by the bug from the 0.40.0 #4382. I can't access to the conversation to close it.
I don't know how to remove/close it / the conversation ?
![capture du 2016-09-21 23-36-50](https://cloud.githubusercontent.com/assets/4016501/18729985/52e57428-8054-11e6-8ff1-06a84c2059ea.png)

**Comment by engelgabriel** [comment]
@sampaiodiego can we add a migration to fix this?

**Comment by sampaiodiego** [comment]
@engelgabriel I think it should be hard to properly fix it.. but we can remove them.

what you guys think?

**Comment by unixfox** [comment]
Maybe create a tutorial to get rid of the buggy guest ? I tried to remove the conversation in the MongoDB database yesterday but that's doesn't work.

**Comment by sampaiodiego** [comment]
oh, maybe the client cache is keeping it on your screen..
I'll write something on how to get rid of it.

**Comment by unixfox** [comment]
@sampaiodiego I think it's related to the cache `unread rooms` of the agent who took the livechat (me) because the conversation hasn't been locked Rocket Chat keeps showing this conversation as unread.

**Comment by unixfox** [comment]
Any news about this bug? I've the livechat notification sound that pops everytime I open Rocket Chat and I've to subtract the notification counter by one number to see if I've real notifications.

**Comment by sampaiodiego** [comment]
hi @unixfox .. you can try run this command direct on DB:
```
db['rocketchat_room'].find({ t: 'l', 'code.value': { $exists: 1 } }).forEach(function(r) {
    db['rocketchat_message'].remove({ rid: r._id });
    db['rocketchat_subscription'].remove({ rid: r._id });
    db['rocketchat_room'].remove({ _id: r._id });
});
```

**Comment by unixfox** [comment]
Thank you @sampaiodiego for this patch but this doesn't remove the notification but the conversation seems to be removed from `Current chats`.
Here are the output:
````
root@aresrpgv2:~# mongo
MongoDB shell version v3.3.15
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.3.15
Server has startup warnings: 
2016-10-10T23:38:13.590+0200 I STORAGE  [initandlisten] 
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] 
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.3.15) of MongoDB.
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] **       Not recommended for production.
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] 
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] 
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] 
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] ** WARNING: You are running in OpenVZ which can cause issues on versions of RHEL older than RHEL6.
2016-10-10T23:38:14.060+0200 I CONTROL  [initandlisten] 
> show dbs;
Proxy       0.000GB
admin       0.000GB
local       0.000GB
network     0.002GB
rocketchat  0.084GB
> use rocketchat
switched to db rocketchat
> db['rocketchat_room'].find({ t: 'l', 'code.value': { $exists: 1 } }).forEach(function(r) {
...     db['rocketchat_message'].remove({ rid: r._id });
...     db['rocketchat_subscription'].remove({ rid: r._id });
...     db['rocketchat_room'].remove({ _id: r._id });
... });
> exit
bye
````

**Comment by sampaiodiego** [comment]
it should still be in your client cache.. please logout and log in again and it should be gone

**Comment by unixfox** [comment]
I tried to logout and login again but the notification is still here.
Note: I tried on another browser that I never used on Rocket chat before and same behavior.

**Comment by sampaiodiego** [comment]
oh, so it was not removed at all :( 
I think you can try this:
```
db['rocketchat_subscription'].remove({ name: /guest\-\[object/ });
```

**Comment by unixfox** [comment]
The regex seems to not working, the command doesn't want to be send:
````
> db['rocketchat_subscription'].remove({ name: /guest\-\[object/ });
... 
... ;
... ^C
````

I tried with quoting them but it found no result:
````
> db['rocketchat_subscription'].remove({ name: "/guest\-\[object/" });
WriteResult({ "nRemoved" : 0 })
> exit
````

**Comment by sampaiodiego** [comment]
oh, I'm sorry, it worked on robomongo :thinking: 

anyway, here is the correct command:
`db['rocketchat_subscription'].remove({ t: 'l', name: new RegExp('guest\\-\\[object') });`

**Comment by unixfox** [comment]
Thank you @sampaiodiego, this solved the bug!
````
> db['rocketchat_subscription'].remove({ t: 'l', name: new RegExp('guest\\-\\[object') });
WriteResult({ "nRemoved" : 1 })
````

Should I close this issue?

**Comment by sampaiodiego** [comment]
I can close it =) thx
