### ISSUE TITLE
Protect Uploads

### ISSUE THREAD

**Issue by brady-young** [RocketChat/Rocket.Chat#4417]
Your Rocket.Chat version: 0.40.1

Hello,
We are on the most current Rocket.Chat service version running on CentOS behind a reverse proxy server.  We are having an access denied issue with file uploads.  We have to have the protect uploads enabled for data privacy issues.  We are getting the following errors:

"The image "https://server.com/file-upload/zfdsafesarefafee.jpg" cannot be display because it contains errors."

![image](https://cloud.githubusercontent.com/assets/22377631/18759906/fa3d805a-80bb-11e6-9f62-5f6d2200fce5.png)

When i turn off Protect uploads both these errors go away and the file can be downloaded no problem. Any help is greatly appreciated.

**Comment by engelgabriel** [comment]
you need to login into your server in the browser once

**Comment by brady-young** [comment]
I have.... I get the same errors both in the browser and the client.

**Comment by Bitti09** [comment]
with latest dev version i also get 403 when "Protect Uploads" is enabled
Protect Uploads on disabled  and  everything is ok

**Comment by brady-young** [comment]
Hello,
I am just seeing if there is any update on this.

**Comment by luckofthelefty** [comment]
Your Rocket.Chat version: 0.44
Default Browser: Chrome
Protected Files Enabled
LDAP Enabled
I can confirm this is still an issue (at least in Chrome). Steps to reproduce are as follows:
1. Upload file from within Desktop Client
2. Attempt to download from within client will open a tab in Chrome. Page will load but will get a blank screen or access denied.
3. Open chat server in Chrome window. Download file results in success.
4. File can now be downloaded from the client once a download attempt has been made from Chrome browser.

**Comment by brady-young** [comment]
Found that it is definitely a bug. I have to constantly be logged into a web browser (doesn't matter what browser, Chrome, FF, IE, Opera, etc.) for the uploaded files to work.  So there is an issue between the desktop rochet.chat client and opening and passing through authentication in the web browser.  If users do not use the desktop client and only use the web browser as the client it all works.  The only issue is when trying to click on the uploaded file link in the desktop client.

**Comment by reetp** [comment]
Same issue noted on 0.44 
Just upgraded to 0.45 but not yet tested.

**Comment by algonza** [comment]
4.5 here; it is still an issue.

**Comment by jsumners** [comment]
Same issue on 0.48.

The client should be downloading files directly instead of opening them in a separate browser process.

**Comment by Hudell** [comment]
This has already been fixed. If anybody runs into the problem again, the issue can be reopened.

**Comment by bub4z0r** [comment]
Just faced same issue at fresh installation from helm rocketchat 6.4.1
OS version: Windows10 22H2
rocket.chat version: 3.9.9
default browser: chrome
Protected Files: Enabled
Keycloak: Enabled
Basic auth: Disabled

100% repeateble at our installation (client need to login at browser before download files from rocket.chat client)

Clicking on cloud works fine. Clicking on file opens browser with 403
![image](https://github.com/RocketChat/Rocket.Chat/assets/1097555/bc5289ea-bf75-4fdb-b637-63e068018db9)

**Comment by essal0815** [comment]
Same here:
Server: 6.3.9
LDAP: enabled
Protected Files: Enabled

Client:
Linux, Mac: 3.9.9

**Comment by Robertpoleniusanderssonmiv** [comment]
I'm having the same issue.
