### ISSUE TITLE
Relative path on og:image meta tag results in broken preview image

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#4421]
Your Rocket.Chat version: 0.40.1

When sharing a URL like:
https://insights.ubuntu.com/2016/09/22/rocket-chat-a-new-snap-is-landing-on-your-nextcloud-box-and-beyond

The tag
```
<meta property="og:image" content="/wp-content/themes/resource-centre/static/img/facebook.png" />
```

Results in broken preview image

![image](https://cloud.githubusercontent.com/assets/1000217/18766024/987f2282-80ee-11e6-8835-1c8c33b2b883.png)

**Comment by Sx3** [comment]
happened again

![image](https://user-images.githubusercontent.com/3599933/80566052-ad9b4c80-8a0f-11ea-8c3e-301dbaaf7598.png)
