### ISSUE TITLE
Channel breaks when changing type between private group and channel

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#4423]
Your Rocket.Chat version: 0.40.1

When changing a channel to a private group (or the other way round) it causes a temporary error (requires page refresh)

Type goes to `undefined` and the main window errors
![image](https://cloud.githubusercontent.com/assets/5689874/18768755/58961bae-811f-11e6-8d44-62c28b3f4980.png)

As the channel url changes between `channel` and `group` the previous url no longer works. Maybe fixed by redirecting user to new url after changing type?

Alternatively we could try renaming the url from `group` to `channel`

**Comment by engelgabriel** [comment]
We will make all channels and groups use the same URL

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Could not reproduce this anymore on latest stable (0.62.1)

Cheers
Thomas
