### ISSUE TITLE
Multiple conversations at the same time

### ISSUE THREAD

**Issue by sta-szek** [RocketChat/Rocket.Chat#4426]
Your Rocket.Chat version: (0.4.2)
It would be nice to have a possibility to open few conversations at the same time.
I have about 30 public channels, 15 private channels and 30 private message (face to face) channels.
If I want to copy something, first I have to spend 5 minutes to find the channel, copy message and then again 5 minutes to find destination channel.

The solution could be to split screen on at least two parts (even four or more) and have open two channels at same time.

**Comment by rodorgas** [comment]
Maybe you will want to open multiple tabs in your browser. Also, you can quickly switch chat rooms with Ctrl+P.

**Comment by sta-szek** [comment]
:open_mouth: this shortcut is awsome! 
But this works only for rooms, not face2face messages :(

When I start typing someone's name e.g. `adm`:
![image](https://cloud.githubusercontent.com/assets/6240704/18785108/9fbea22c-8196-11e6-8b84-88fd32d047be.png)
and then I hit enter, nothing happens.

When Ctrl+P again I can see:
![image](https://cloud.githubusercontent.com/assets/6240704/18785137/c441be2c-8196-11e6-9ab6-557d645dce56.png)

But this is just a feature for changing rooms quickly, not having multiple conversations.

Having multiple tabs in my browser doesn't solve my problem, because it forces me to use Rocket.Chat as PSI (and other out-dated comunicators).

I would rather go in way to have just **one** communication interface, not multiple tabs.

One idea is to have multiple swimlanes that you could drag your conversation to.

**Comment by engelgabriel** [comment]
I'll close this as now Ctrl+P support all types of rooms, and even shows them on order os most recently opened, so it is easy to switch back and forward.

**Comment by ConvergentDev** [comment]
This would be incredibly useful. Something similar to Tweetdeck streams https://www.wired.com/2012/03/hands-on-tweetdeck-wants-to-be-your-pro-twitter-client-again/ would work really well.
