### ISSUE TITLE
Chatbar on the main site

### ISSUE THREAD

**Issue by JohnnyKing94** [RocketChat/Rocket.Chat#4428]
Your Rocket.Chat version: 0.40.1

Is it possible to include a chatbar over the main website for private and public chats (no html frame)?? It would be a great feature to add. These are example images of what i mean:

**Private chat**
![private](http://ww1.prweb.com/prfiles/2010/03/15/767104/gI_window.png.jpg)

**Public chat**
![public](https://www.arrowchat.com/store/images/s_b_38_3.gif)

**Comment by louisemessage** [comment]
Thank you for your suggestion. Closing this issue for the meantime as this feature is not on our short-term roadmap.

**Comment by JohnnyKing94** [comment]
That's not excuse to close it... then all the more reason you should have it open cause it's still a possible feature... otherwise it will never be a feature even on the long-term roadmap as you closed it and intentionally abandoned it

**Comment by SeanPackham** [comment]
@JohnnyKing94 what are your thoughts about using the https://forums.rocket.chat/c/feature-requests to discuss and upvote features requests?

**Comment by sampaiodiego** [comment]
you can configure Rocket.Chat to be used anonymously so you can achieve this by adding an `iframe` on your website opening a room URL of Rocket.Chat appending `?layout=embedded` to it.. so a very limited window will be shown

**Comment by JohnnyKing94** [comment]
this was something i already knew... but popup window doesn't show notification if closed... that's why i titled this topic "chatBAR" and not not "chat window"... shame that is not even considered...

**Comment by sampaiodiego** [comment]
sry @JohnnyKing94 .. this is not something we plan to do at the moment. but if you have a suggested implementation we'd like to evaluate the PR. thx

**Comment by JohnnyKing94** [comment]
don't worry i'm not mad at you... i already lost hope after the first year of waiting and then at the first closing... now it's almost two years later and there are plenty of open issues with feedbacks and ideas, surely better than mine... but still not considered...

**Comment by sampaiodiego** [comment]
I'm sorry for hearing that 😞 
but just like this issue we're currently trying to take look at all over the backlog to prioritize the things we really plan to do. feature requests like this we're asking to move a discussion into our forums: https://forums.rocket.chat if the discussion evolves and find a big number of the community wants to have such a feature we then prioritize.
