### ISSUE TITLE
Atlassian Crowd Integration does not allow for self signed certs.

### ISSUE THREAD

**Issue by AbrohamLincoln** [RocketChat/Rocket.Chat#4429]
I run a private Crowd server which uses certs signed by our internal PKI.  I haven't found any way to supply a CA Cert for the crowd connection.  I'm currently unable to use Crowd.

```
[34mI20160923-14:38:59.949(0) Error sending request: unable to verify the first certificate
[34mI20160923-14:38:59.956(0) rocketchat:crowd crowd.js:248 [31mCROWD ➔ error Invalid crowd connection details, check the url and application username/password and make sure this server is allowed to speak to crowd
```

If there are any more details I can provide please let me know

**Comment by qweqweq** [comment]
i have got this error too,have you had solved this problem?

**Comment by AbrohamLincoln** [comment]
Nope.  I'm using LDAP for the time being.

**Comment by qweqweq** [comment]
@AbrohamLincoln  ok,could you tell me how to use LDAP. In a word, could you let me know what you have done?thank you very much.

**Comment by AbrohamLincoln** [comment]
Our Crowd server ultimately uses openldap servers as a directory source.  I would have preferred to use crowd but using LDAP directly is what works.

**Comment by qweqweq** [comment]
@AbrohamLincoln  en, if LDAP works, could you tell me how to config LDAP in Rocket.chat?

**Comment by AbrohamLincoln** [comment]
Enable and configure via the LDAP administration page.  Its pretty straight forward.
https://rocket.chat/docs/administrator-guides/authentication/ldap/

**Comment by qweqweq** [comment]
@AbrohamLincoln  thanks bro.

**Comment by geekgonecrazy** [comment]
My guess is you'd have to add on your server as a trusted CA. 

Going to go ahead and close this as its not a Rocket.Chat specific problem.  Please feel free to reach out on our community server or other methods found in our [support guidelines](https://rocket.chat/docs/getting-support)
