### ISSUE TITLE
How to send to incoming webhook with linebreaks?

### ISSUE THREAD

**Issue by casper-gh** [RocketChat/Rocket.Chat#4434]
Your Rocket.Chat version: 0.35.0

When sending back a payload to incoming webhook integration, I tried to send this:

```
"text": "This is first line. \nThis is second line"
```

And the result I received:

```
This is first line. This is second line
```

Did I do it right or am I missing something?

EDIT: Typo from /n to \n

**Comment by olafleur** [comment]
It seems to me that you want to send \n instead of /n to mean a line break.

**Comment by casper-gh** [comment]
@olafleur sorry my bad, I actually tried with `\n`

**Comment by vetash** [comment]
@casper-gh try `\r\n` or `\r`

**Comment by DonMartin76** [comment]
It's been a while, has anybody succeeded with this since then? I am facing exactly the same problem. I have tried:

* `\n`
* `\r`
* `\r\n`
* `/n` (well well)
* `<br>`

And none of those work as I want to.

**Comment by DonMartin76** [comment]
*Resolved*: I was trying this in a non `text` field; in the `text` fields, `\n` works.

**Comment by geekgonecrazy** [comment]
Looks like a solution was found.  Going to go ahead and close this.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)

**Comment by MatthiasHertel** [comment]
its curious, if u put the new-line-tag `\n` at the end without any character afterwards - it won't will work.

eg.
***works not***

```
  'text' => "Lorem ipsum \n\n",
```

***works***

```
  'text' => "Lorem ipsum \n\n anychar",
```


**furthermore:**

in the pretext of a field:

nothing works 
either `\n` or `\r` or anything else

eg.

```
'attachments' => [[
            'color' => 'good',
            'pretext' => "Lorem ipsum:\n anychar",
            'fields' => [
              [
                "title" => "title 1" ",
                "value" => $request->title,
                "short" => false
              ],
...
```

**Comment by geekgonecrazy** [comment]
@graywolf336 any ideas on the pretext field? 

As to why text at the end won't allow you to do a new line.  I think it strips them off at the end. Which I think is probably intentional.

**Comment by DesRodman** [comment]
Where is solution?
I'm trying to send webhook to Rocket from PHP
I'm trying and `\n\n`, and `\n`, and `\r` and `\r\n`

and all time have 
```
Array
(
    [0] => <!DOCTYPE html>
    [1] => <html lang="en">
    [2] => <head>
    [3] => <meta charset="utf-8">
    [4] => <title>Error</title>
    [5] => </head>
    [6] => <body>
    [7] => <pre>Bad Request</pre>
    [8] => </body>
    [9] => </html>
)
```
What i need to use in string like
`$command = 'Hello Bro!'."\n".'How are you?';`

**Comment by DesRodman** [comment]
I found some interesting method
`$command = 'Hello Bro!\\nHow are you?';`

**Comment by niklasgrewe** [comment]
I am using a linux bash script to send messages to rocket.chat. but i nothing worked for me to display break lines, instead of sending a second message. I tried this

```
./postToRocketChat.sh -b "Notification send\\nNew Line"
```
and i will get this from server
```
{"text:" "Notification sendnNew Line"}
```

**Comment by thoniTUB** [comment]
I also use bash and struggled. But this works for me now:
```bash
payload="{\"text\": \"Hello\\\\nthere\", \"channel\": \"@user.name\"}"
curl \
        -XPOST \
        -k \
        -H "content-type: application/json" \
        -H "X-Auth-Token: ..." \
        -H "X-User-Id: ..." \
        -d @<(echo -e "$payload") \
        "https://chat/api/v1/chat.postMessage"
```

**Comment by waqasy** [comment]
I was having this issue while using php file to respond hooks. I added `header("Content-Type: text/plain");` now lines breaks `\n` are working fine.

**Comment by xoxloviwan** [comment]
Version 3.15.0. `<br>` worked

**Comment by phuongnguyen2311** [comment]
> Version 3.15.0. `<br>` worked

how to you fixed this?
you add `<br>` instead of `\n`. it's right?

**Comment by xoxloviwan** [comment]
> > Version 3.15.0. `<br>` worked
> 
> how to you fixed this?
> you add `<br>` instead of `\n`. it's right?

in version 3.16.4 it is broken

**Comment by eric-create** [comment]
@AdityaSaroj I've had problems with the line breaks in the attachements text. I solved it by using tripple "\": \\\n
