### ISSUE TITLE
syncing user list into wordpress

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#4436]
is there a way to import current RC users to wordpress? here is a wild thought that maybe imposisble can we just create a membership plugin for wordpress for user/permission management that works right away with RC, same time wordpress pages?  💨 

Your Rocket.Chat version: (0.40)

**Comment by graywolf336** [comment]
If someone who knows WordPress wants to take a stab at it, we would be happy to help them with it. 👍

**Comment by wargamesqcf** [comment]
there isn't a way currently I think, I used wordpress oauth and that pulls users from wordpress to RC.

**Comment by DMWOO7** [comment]
Seems not a good structure for me. Why not let a central LDAP server manage the crendetials? So you can reuse them in many other applications. And you're not depending on WP or any other specific application.

**Comment by wargamesqcf** [comment]
Because it was a way to sync everything on my website to a central point, it works out pretty ok. My wiki and forums also uses the WP userDB so yeah its not the worst option. But going ldap next time around to try it out.

**Comment by IQ2022** [comment]
@wargamesqcf what is your site if i may see how you did it? also do you have forum software that you used ? phpBB?

**Comment by wargamesqcf** [comment]
http://five-rings-online.com/

This is my site. It uses wordpress  for the frontpage, mybb as the forums, and doku as the wiki. We had issues with rocket for a while and are doing testing so the current chat that is linked is a terribad temp one. But you can find rocket here http://five-rings-online.com:3000/

So doku reads the userdb of wordpress with an extenstion, we run WP OAuth Server as a plugin for wordpress so rocket has an oauth to connect to. Sadly the way mybb works I have to use mybb sync on wordpress to push accounts to the mybb userdb.

This setup is garbage and a mess, but it works and will be trying to do an ldap setup in the future.

**Comment by IQ2022** [comment]
nice work :) ..

question what if your users want to login with social plugins i.e google, facebook, twitter, can you have those register in your wordpress, and then wordpress authenticate with Rocket.Chat?/ also noticed your forum require another login, did you try phpBB? i think you can integrate users with wordpress..

**Comment by wargamesqcf** [comment]
Its a complete mess and rush job but it works, and I will be using PHPBB in the future. I will also try and use drupal over wordpress because we had a pretty bad bruteforce attack on our xmlrpc.php. Hopefully next go around i will also have figured a few other things out.

**Comment by IQ2022** [comment]
someone was playing games on your site , btw, have you considered using membership plugins? like membership pro or ultimate membership, this way you ensure paid users are behaving?

**Comment by wargamesqcf** [comment]
Good I hope they were playing games, it is an rpg site that is free to use. So I have no paying users.

**Comment by IQ2022** [comment]
thats the problem with free, you get to fight hackers..... have a look at futures.io, its built over vbulletin and its paid membership so i guess no one can hack  - i will go with phpBB at the moment no time

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this, since the way to go here is oAuth ... in whatever direction. The issue at hand is too cluttered so if you still want to see this, please head over to the forums first and discuss this matter: https://forums.rocket.chat

Cheers
Thomas
