### ISSUE TITLE
Collapsible “navbar” (on the left)

### ISSUE THREAD

**Issue by bogeygoy** [RocketChat/Rocket.Chat#4441]
Your Rocket.Chat version: 0.40.1

Could the left-hand bar/pane, the so-called “navbar” (I believe), be made collapsible, too?  Like the one on the right-hand side.  

Thanks in advance.

**Comment by MartinSchoeler** [comment]
@bogeygoy no, its not possible to close this bar

**Comment by k0nsl** [comment]
@MartinSchoeler: I think he knows it isn't possible to do that _now_. He wants to know about the possibility of implementing this functionality into Rocket.Chat

**Comment by bogeygoy** [comment]
Exactly, @k0nsl.

**Comment by engelgabriel** [comment]
@karlprieb lets create a user preference to have the burger always ON.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this in favour of #4688. If somebody doesn't agree, please get back to me! :)

Cheers
Thomas
