### ISSUE TITLE
Disabling UI animations

### ISSUE THREAD

**Issue by bogeygoy** [RocketChat/Rocket.Chat#4442]
Your Rocket.Chat version: 0.40.1

Is it perhaps possible to disable UI animations?  (To speed up the interface.)  Or rather, to give users the ability to switch it “on” or “off”?  It might also improve overall performance.  

Thanks in advance.

**Comment by MartinSchoeler** [comment]
@bogeygoy no its not possible but we could leave this issue open if some one wants to take a stab at it

**Comment by bogeygoy** [comment]
Okay, that would be nice.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.
