### ISSUE TITLE
Mozilla/Firefox browser “newline” issues

### ISSUE THREAD

**Issue by bogeygoy** [RocketChat/Rocket.Chat#4443]
My Rocket.Chat version: 0.40.1
My Firefox version: 45.4.0  

Entering new lines in the text (message) area appears to not be possible, or with my version of Firefox.  Could this be fixed?  

Thanks in advance.

**Comment by MartinSchoeler** [comment]
hey @bogeygoy have you tried to press Shift+Enter?

**Comment by bogeygoy** [comment]
Yes, I have.  Doesn't work/make a difference.

**Comment by karlprieb** [comment]
Apparently it was already fixed. I tried with the same versions of Firefox and Rocket.Chat and can't reproduce :( Im using macOS and you?

![2016-10-05 23 12 13](https://cloud.githubusercontent.com/assets/9200155/19139244/3f36acfc-8b59-11e6-8dd6-9639da82f3ae.gif)

**Comment by k0nsl** [comment]
I tried it now on FF 49.0 and it doesn't work. I am running Gentoo on my workstation and the server which runs Rocket.Chat is running 45.0.0

**Comment by engelgabriel** [comment]
@bogeygoy I believe this was fixed. Please reopen if the problem persists.
