### ISSUE TITLE
when user login in ,and then create room automatically

### ISSUE THREAD

**Issue by qweqweq** [RocketChat/Rocket.Chat#4447]
![image](https://cloud.githubusercontent.com/assets/10056390/18820439/617a36c0-83d0-11e6-97d0-03b4eb28243c.png)
as you can see,in this picture ,i want to create the 'myroom' automatically for everyone who login in successfully.

**Comment by geekgonecrazy** [comment]
Go to: Administration->Rooms Click the room and set as default near the bottom.
