### ISSUE TITLE
archive/unarchive channels

### ISSUE THREAD

**Issue by ffogarasi** [RocketChat/Rocket.Chat#4451]
Your Rocket.Chat version:0.5

Could we have channel archiving/unarchiving in  REST api?
Also it would be nice to be able to set the members when creating a new channel.
Using _bulk/createRoom_ method it is possible and they are using the same underlying function, but the _channels.create_ function is simply passing empty array for members.

**Comment by engelgabriel** [comment]
Rocket.Chat version: 0.5? Are you sure @ffogarasi ?

**Comment by ffogarasi** [comment]
I was assuming this endpoint gives the proper value :(

> /api/version

 gives me:
{
  "status": "success",
  "versions": {
    "api": "0.1",
    "rocketchat": "0.5"
  }
}

The hosting company tells that we have version 0.32.

**Comment by graywolf336** [comment]
@ffogarasi Please have them update you to the latest version, which is, as of this comment, 0.42. https://github.com/RocketChat/Rocket.Chat/releases this version has the archive feature.

**Comment by ffogarasi** [comment]
We upgraded to 0.42
But I still cannot find the REST route to archive a channel.
I even searched the repo but cannot find the function to call.

**Comment by graywolf336** [comment]
I don't think we mentioned there was, as that doesn't exist. That'll need
to be a new issue or you can open a new pull request to add that
functionality :)
