### ISSUE TITLE
membership

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#4458]
am looking at setting up room memberships and roles, right now there is ability to mute a room and make it read only with option to add moderators to be able to write, or un-mute users?? 

also can we show role levels visible to ADMIN's, who is owner, who is moderator any new custom role types? 

Your Rocket.Chat version: 0.40

**Comment by IQ2022** [comment]
this member was already set as owner and moderator, for some reason when i click on his name it doesnt show anything..

![image](https://cloud.githubusercontent.com/assets/12454319/18849563/8502a1e6-8401-11e6-8ed9-0375f174e352.png)

**Comment by antgel** [comment]
Closing as it's ancient and diverse. If it's still relevant, please open issues for each feature you'd like to see, if they aren't already in the +2000 open issues.
