### ISSUE TITLE
Error when run Rocket.chat in sub dir (from ver 0.40.0)

### ISSUE THREAD

**Issue by dangkiena3** [RocketChat/Rocket.Chat#4460]
Your Rocket.Chat version: 0.40.1

From 0.40.0 version, I can't run Rocket.chat in subdir as older version. Just a loading status forever :(
0.40.1 is same issue. And Android App can not use sub dir Url too.
Please help me! Thank you very much!

![image](https://cloud.githubusercontent.com/assets/18433986/18858296/3e07e2b2-8495-11e6-95b4-09659c59d4e9.png)

**Comment by dangkiena3** [comment]
Version 0.38.0: Running normal

![image](https://cloud.githubusercontent.com/assets/18433986/18867659/5a1c3b80-84cf-11e6-8eef-1e47a08a143d.png)

**Comment by dungvu-qe** [comment]
same my issue +1

**Comment by engelgabriel** [comment]
Can you please share the console log of the browser?

**Comment by dangkiena3** [comment]
Thanks for reply!

![image](https://cloud.githubusercontent.com/assets/18433986/18897986/dca85cda-8558-11e6-8967-3232a6c08e77.png)

**Comment by sdorra** [comment]
we have the same issue with version 0.42.0

**Comment by alvarow** [comment]
+1
