### ISSUE TITLE
Channels notification configuration (Desktop Client 1.3.1)

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat#4461]
Your Rocket.Chat version: 0.40.1
Desktop Client 1.3.1
Description:
Is it possible to configure Desktop Client Channels notification the same as Direct Messages? I mean, if some one in Channel post some new message, other users get the same visual and sound notification (blinking task-bar icon). Because, if I don't use @all tag, no one know, that there are some new message. So, can I configure Channels notification the same as Direct Messages?

**Comment by MartinSchoeler** [comment]
![screenshot from 2016-09-27 08-30-48](https://cloud.githubusercontent.com/assets/20868078/18871652/bf86c24e-848c-11e6-92ba-c21d70e3b1ae.png)
@LXSysadmin you can try changing the settings in this tab

**Comment by LXSysadmin** [comment]
@MartinSchoeler Yes, but Task Bar icon is not blinking. There are only pop-up window for few seconds. So, if user is not at computer, when he returns, he don't know about new message as Task Bar icon is not blinking.

**Comment by LXSysadmin** [comment]
Is there any way to configure that type of alert? Change some where code?

**Comment by LXSysadmin** [comment]
In other words, is there possibility to notify always desktop user about new message in channel with blinking icon in task bar?  
![image](https://cloud.githubusercontent.com/assets/19779209/18985683/c2347af0-8701-11e6-833f-4f713d40d1a8.png)

**Comment by geekgonecrazy** [comment]
Please see: https://github.com/RocketChat/Rocket.Chat.Electron/issues/487

**Comment by imrealashu** [comment]
is there any possibility to change the notification setting of group/channel using API or RealTime api ?
