### ISSUE TITLE
Livechat 

### ISSUE THREAD

**Issue by ulisesguerrero** [RocketChat/Rocket.Chat#4463]
Your Rocket.Chat version: 0.40.1

LiveChat window is out of bounds in the iOS 6.1.6 Safari browser. Possible fix to enable custom CSS for Livechat window.

**Comment by engelgabriel** [comment]
Can you share a screenshot?

**Comment by ulisesguerrero** [comment]
Yes, here they are, can't even chat because its not possible to select the chat input box:
![img_0032](https://cloud.githubusercontent.com/assets/12837321/19025541/c4183642-88df-11e6-8090-ec2ffc93f6b5.PNG)
![img_0034](https://cloud.githubusercontent.com/assets/12837321/19025542/c54f8ed4-88df-11e6-90ba-b8d379c57945.PNG)
