### ISSUE TITLE
Livechat customization

### ISSUE THREAD

**Issue by ulisesguerrero** [RocketChat/Rocket.Chat#4464]
Your Rocket.Chat version> 0.40.1

To minimize the LiveChat box is not intuitive, clicking on the bar is not known by many users. Instead, an X on the corner should be added.

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/20979389/e6f20a0c-bc93-11e6-9522-065e280d0ad9.png)

**Comment by ulisesguerrero** [comment]
Oh yes, that's so much better! Nice!
