### ISSUE TITLE
All usernames changed to 'on'

### ISSUE THREAD

**Issue by abers** [RocketChat/Rocket.Chat#4466]
Your Rocket.Chat version: Info page in administration does not show Version.

Been trying to get Rocket.Chat up and running on a raspberry pi. I have tried installing the Rocket.Chat.RaspberryPi repository and installing via DPlatform-ShellCore. With both, however, I am experiencing the same problem that no matter what I put as the username it gets changed to 'on' for some reason. Changing it on the profile page and hitting 'save changes' does nothing. The issue obviously as well makes it impossible to create any new user accounts as no matter what input is getting for register username on hitting 'use this username' it results in "on is already in use :(" error message. 

Any help or suggestions for what could be wrong much appreciated.

Thank you.

**Comment by Sing-Li** [comment]
@abers   please join our RockOnPi community here:

https://demo.rocket.chat/channel/raspberrypi

The author of DPlatform-ShellCore, Julien, is an active community member.  We'll solve the problem with you!    Thanks.

**Comment by abers** [comment]
Thanks for the reply. I am unable to join the community - however, it has given some insight into what the issue might be. I am receiving the same problem when trying to create a new user on RockOnPi that it tries to change my username on registering to on. Someone else must have previously had the issue as I am receiving the "on is already in use :(" error message. 
Due to this I am assuming it is a browser related issue and either Firefox is not correctly submitting what I enter into the username field - or something is intercepting / replacing the input after I hit submit.  I am assuming its an addon as just tired to register with a clean portable install of Firefox and it worked fine without changing the username to on. 
I will play around with disabling different addons and settings to see if I can pin-point which one it is and let you know if I am successful.

**Comment by abers** [comment]
Found it! ImTranslator is the culprit. It's a generally annoying addon anyway and been meaning to find a better alternative so no great loss having to disable it.
