### ISSUE TITLE
Rocket.chat PUSH with Firebase, IOS

### ISSUE THREAD

**Issue by Akiren** [RocketChat/Rocket.Chat#4468]
Your Rocket.Chat version: Latest

It looks like GCM is no longer an option and has been deprecated by google in favor of Firebase push services...

Has anyone had any luck configuring push for Android.... and for that matter self hosted vanilla push with IOS and a custom rocket.chat.cordova app... Hours and hours with little documentation has left me spent.

**Comment by engelgabriel** [comment]
> Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

https://developers.google.com/cloud-messaging/android/android-migrate-fcm

**Comment by engelgabriel** [comment]
@RocketChat/cordova let's look into that.

**Comment by rodrigok** [comment]
@Akiren Can you follow these steps https://github.com/RocketChat/Rocket.Chat/issues/4182?ts=2#issuecomment-244549945 ?

**Comment by Akiren** [comment]
Ah, your correct. If I click on Google Cloud Messaging it forwards me to Firebase.. However if I type in Google Cloud Messaging it gives me a backdoor link to their soon to be deprecated GCM api creation.

**Comment by rodrigok** [comment]
@Akiren It will not be unavailable, it's deprecated already, but the new features will be available only via FCM.

We will migrate ASAP, but now the library we are using and the cordova it self are not compatible with the new technology.
- [Push Library Issue](https://github.com/raix/push/issues/226)
- [Cordova Issue](https://github.com/phonegap/phonegap-plugin-push/issues/929)
