### ISSUE TITLE
install Fork

### ISSUE THREAD

**Issue by boulakar** [RocketChat/Rocket.Chat#4469]
Hi

if i edited a code using fork github i can install it

Thanks for ur help

**Comment by marceloschmidt** [comment]
I don't think your question makes much sense. Please rephrase it if I get it wrong.
If you fork our repo, you can make whatever changes you want, and run your project just like any other meteor project. You do need to have git and meteor background, as stated here: https://rocket.chat/docs/developer-guides/pre-requisites/

**Comment by boulakar** [comment]
@marceloschmidt thanks so much yes this is my goal :)
but me i want deploying Rocket.Chat on ubuntu **"node main.js not meteor run "**
