### ISSUE TITLE
Mobile App crash since iOS 10 and 0.41.0

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4475]
Your Rocket.Chat version: 0.41.1

Hey,

on my rocketchat system there is a bug for mobile users with iOS clients. Since i upgraded to iOS 10 and 0.41.0 my users have the problem that they are not able to delete a message without a crash of the RC App. So my testing steps are the following:
- Open the RC Cordova App and connect to my system
- write a message in a channel where i have the rights to delete that message
- Tap and hold on the message -> delete
- The UI shows me "message deleted" but i see the message in the channel
- after 2-10 seconds the app is crashing on the phone
- after restart of the app the message is gone

If i try this on your demo system, all is working fine. So i think there must be a fix ;-).

Maybe its related to: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/137

Thanks for your awesome work guys!

Greetings
TheReal

**Comment by rodrigok** [comment]
I can reproduce here

**Comment by dangkiena3** [comment]
Please enable to use Subdir link in Mobile App.

Eg: https://sub.mydomain.com/chat

Thank you very much :)

**Comment by TheReal1604** [comment]
@engelgabriel @rodrigok Its also happening on a newer version like 0.48.1

**Comment by engelgabriel** [comment]
@dangkiena3 please open new specific for unrelated requests.

**Comment by laggedHero** [comment]
Hello @TheReal1604.

I'm not able to reproduce your error but something similar on `0.48.2`: the message won't leave the screen but no crash.

On `0.49.0-develop` everything is fine.

Would you be able to run a test against `0.49.0-develop` on your end?

**Comment by engelgabriel** [comment]
@TheReal1604 can you please reopen this issue if the problem persist?
