### ISSUE TITLE
Cron Like Jobs

### ISSUE THREAD

**Issue by hExPY** [RocketChat/Rocket.Chat#4480]
Your Rocket.Chat version: 0.41.0

Hey Guys,

i've been wondering if there is a function to fire commands periodically. E.G. We have a JS installed which inform Admins if theres a new Version of Rocket Chat available. We want to move the notification to a rest call which creates a jira issue.

Kind regards,

**Comment by marceloschmidt** [comment]
Hey @hExPY 

We use https://github.com/percolatestudio/meteor-synced-cron to do that, but that's code-based, and not application based. There's nothing implemented that would allow you to input your own code and run it from time to time in Rocket.Chat.
