### ISSUE TITLE
if a message exist or no

### ISSUE THREAD

**Issue by boulakar** [RocketChat/Rocket.Chat#4481]
Hi
my goal is comparison a string with database
if exist in database or no
if a message exist or no
i used all fountion in this link but not working
https://github.com/RocketChat/Rocket.Chat/tree/develop/packages/rocketchat-lib/server/models

**Comment by graywolf336** [comment]
@boulakar Please join our demo server in the #dev channel for answers to your question, as this question requires more explanation from you about how you are going to define "if a message exists or no".
