### ISSUE TITLE
Direct Messages Between Multiple Users

### ISSUE THREAD

**Issue by hughlroberts** [RocketChat/Rocket.Chat#4489]
Your Rocket.Chat version: 0.41.0 

Setting up a new private group is painful. Slack allows you to quickly add users together without naming the group but simply inviting users into a message together and then as those group messages aren't used they are moved down the most recent messages in direct messages. 

Any way that can be re-incorporated into rocket.chat?

**Comment by mkretzer** [comment]
My users also ask for this!

**Comment by alexandrezia** [comment]
Most requested here too

**Comment by 78c59635bdd8** [comment]
Yes, this would be great in our environment!

**Comment by drickerusa** [comment]
This would definitely make it easier on our migrated slack users.

**Comment by ruihildt** [comment]
You can create a private channel instead, but that's just a workaround before the main thing. :)

**Comment by xseguib** [comment]
+1

**Comment by brynn-macpherson** [comment]
Plus one for me as well, we're migrating from Slack and this will make things MUCH easier

**Comment by Dracozny** [comment]
Please just use the Thumbs up of the post you're +1ing. Otherwise, it drives unnecessary notifications to everyone following the issue.

**Comment by maver1ck** [comment]
+1

**Comment by OnthegOinOz** [comment]
👍

**Comment by gezims** [comment]
👍

**Comment by jlozadad** [comment]
1+

**Comment by flashbackcz** [comment]
This would be very nice and better than a new group (:

+1

**Comment by simonv3** [comment]
I feel like a way of doing this might be to have an "unnamed" private group, and only once you name it does it become a "channel". Otherwise it's a way private messages. Does that make sense?

**Comment by nakic** [comment]
Sounds like an obvious feature to implement to me: one of the first things we used with Slack. :\

**Comment by paul-siteway** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=38003640)](https://www.bountysource.com/issues/38003640-direct-messages-between-multiple-users?utm_source=38003640&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by gwpantazes** [comment]
@simonv3 With the note that a named group wouldn't carry the previous private message history into the channel, the newly named channel would start fresh with the members of the private message.
I think "unnamed" is the right idea, but the "name" of (or way of identifying) the private message "channel" would just be the members participating, right?

**Comment by simonv3** [comment]
Yeah, I would think so.

**Comment by gnidorah** [comment]
@simonv3 @gwpantazes Thanks! I've made a PR with that in mind https://github.com/RocketChat/Rocket.Chat/pull/9106 Please take a look. Though to match current behaviour of Rocket.Chat, conversion is done not through renaming, but via a separate checkbox like its done with private to public channel conversion.

**Comment by dcorrigangoempyrean** [comment]
Adding my name for highly wanted feature!

**Comment by metalcated** [comment]
Same here... I can't get 100% buy-in from the higher up's until this feature is available.

**Comment by nelsongraca** [comment]
any news on this? My users are requesting this too

**Comment by zdumitru** [comment]
Pull request #9106 is ready for review.
