### ISSUE TITLE
Number of people in a channel

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4490]
Rocket.Chat version: 0.41.0

It would be nice If rocket showed how people were in a room before joining it.

**Comment by marceloschmidt** [comment]
Why do you think this is good? What's the use case? And can you suggest how this would be done?

**Comment by wargamesqcf** [comment]
For me I use rocket for a role playing chat, I have 30 or so channels for people to join and chat and play. Right now they have to hop around to each of the 30 channel in the hope they can find someone to play with.  In our old chat we had a room like this and if people were in that room it was simply say how many people were in that room. Since rocket shows the number of unread messages on the right, perhaps on the left where the hastage # is could be a number showing the number of people in a room?

http://i.imgur.com/0E4Cseg.png?1

**Comment by chat4free** [comment]
It makes sense to show the number of online users in the channel list.
We're testing rocket.chat right now, and our testusers have also the problem that they have to go to every room to find other users.

**Comment by ggazzo** [comment]
I think the 'directory' feature solves your problems!
![image](https://user-images.githubusercontent.com/5263975/52458606-955bbb00-2b47-11e9-944c-884618ac56d2.png)
please open again if I'm wrong
