### ISSUE TITLE
Disabling file upload doesn't work

### ISSUE THREAD

**Issue by tristanflorcb** [RocketChat/Rocket.Chat#4493]
Your Rocket.Chat version: 0.40.1

File Upload is set to false but still can upload files.

**Comment by net-activities** [comment]
Your Rocket.Chat version: 0.41, 0.42, 0.43
OS Version: CentOS 7

Same here

**Comment by philinx** [comment]
Rocket.Chat version: 0.43, 0.44
OS Version: ubuntu - snap

Same here
