### ISSUE TITLE
cas  server  problem

### ISSUE THREAD

**Issue by qweqweq** [RocketChat/Rocket.Chat#4494]
i want to enable the caso with my own server which not in git、twitter、meteor...
i got some problems with other service .
![image](https://cloud.githubusercontent.com/assets/10056390/18982685/95bc2c66-871a-11e6-8a9a-6c48088ef04d.png)
![image](https://cloud.githubusercontent.com/assets/10056390/18982856/c9c98e08-871b-11e6-8341-5ff067c70e22.png)

can anyone give me some advice?

**Comment by engelgabriel** [comment]
What CAS versions and softwares do you use?

**Comment by qweqweq** [comment]
@engelgabriel  hi,the cas version is 1.0,and softwares is the lastest version.
i git clone  the repo and build it myself .
> meteor build --server https://demo.rocket.chat --directory /your/build/location

**Comment by corecache** [comment]
@qweqweq What is the content of the server logfiles? Could you enable debugging in Settings and reproduce the error?

**Comment by qweqweq** [comment]
@corecachee  server logfiles i don't remember ,i am not in company now and we have a long holiday  in china called Natoinal Day. 7 days later,i will send you the error messages and the CAS service software when i return . thanks a lot. :smile:

**Comment by qweqweq** [comment]
@corecache  hi ,CAS service software is the   

[](https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol.html)  we use 3.5.x version not 4.2.x

  and i want to combination with Rocket.chat .but i can't.

**Comment by corecache** [comment]
There are multiple CAS service softwares. Which one do you use? What is the name of the product/software?

**Comment by qweqweq** [comment]
oh sorry ,the link address not copied.the link is https://www.apereo.org/projects/cas
we use 3.5.x version

**Comment by qweqweq** [comment]
@corecache  hi i can't find where the cas.valide function defined. could you tell me how it works?
code as follows.

`cas.validate(ticketId, function(err, status, username) {
		if (err) {
			logger.error('error when trying to validate ' + err.message);
		} else if (status) {
			logger.info('Validated user: ' + username);
			_casCredentialTokens[token] = { id: username };
		} else {
			logger.error('Unable to validate ticket: ' + ticketId);
		}

		callback();
	});`

**Comment by corecache** [comment]
It is beeing imported from an external module called "CAS". What are you trying to do?

**Comment by qweqweq** [comment]
@corecache ,yeah,i want to know how does cas.validate() work when i got the ticket.  When I debug this code, I found I was unable to follow up this process 'CAS.VALIDATE()'. So I want to know how this approach is defined and how it is to verificate by ticketId.

**Comment by corecache** [comment]
It's all described in the Jasig CAS procol versions on the Jasig website. Here is an example diagram from Ruby Cas: https://rubycas.github.io/images/basic_cas_single_signon_mechanism_diagram.png

**Comment by corecache** [comment]
The actual code behind the imported CAS module is to be found here: https://github.com/kcbanner/node-cas/blob/master/lib/cas.js#L363

**Comment by qweqweq** [comment]
@corecache  ok,thanks bro. :smile:

**Comment by qweqweq** [comment]
@corecache  hi ,I appeared in the fifth step when the ticket is verified according to issues, returns no data, the picture is described when debugging problems.

![image](https://cloud.githubusercontent.com/assets/10056390/19296476/637a86b4-906e-11e6-9ac2-6fd4cb0b91cd.png)
![image](https://cloud.githubusercontent.com/assets/10056390/19296402/c5321a76-906d-11e6-9a33-0ea9b33dc785.png)
![image](https://cloud.githubusercontent.com/assets/10056390/19296309/308b75f2-906d-11e6-9f11-bd130e9c2c79.png)
![image](https://cloud.githubusercontent.com/assets/10056390/19296744/b1096362-9070-11e6-90c8-b2ac4570609f.png)

**Comment by corecache** [comment]
1. Have you whitelisted your service with the CAS service to allow non-HTTPS?
2. Your screenshot says you are using version 0.42 develop, but the code I see is from earlier versions or you have replaced it yourself with some debugging stuff. I can not reproduce the bug in the current version when you are using some completely different code base which is unknown to us.

**Comment by qweqweq** [comment]
@corecache  thanks a lot ,i will check it.

**Comment by qweqweq** [comment]
@corecache  hi bro ,i have update my code with version 0.42 develop.and i got a error message like this.
![image](https://cloud.githubusercontent.com/assets/10056390/19335523/863c8904-9136-11e6-8109-3021b0d23e78.png)

**Comment by corecache** [comment]
Are you perhaps using self-signed certificates? or have not yet imported your internal company CA for your current service?

**Comment by qweqweq** [comment]
oh yeah,i have not imported my company CA.thank you very much @corecache :+1:

**Comment by corecache** [comment]
So this solved your problem?

**Comment by qweqweq** [comment]
actually, i don't know how to import my company CA. i have  ask  my workmate for some help,and i have not receive any suggests. Do i need to change the code about cas-server.js like this?
before:
![Uploading qwe.jpg…]()
after:
![Uploading image.png…]()

**Comment by qweqweq** [comment]
actually, i don't know how to import my company CA. i have  ask  my workmate for some help,and i have not receive any suggests. Do i need to change the code about cas-server.js like this?
![image](https://cloud.githubusercontent.com/assets/10056390/19395228/2c6eb94e-926f-11e6-8642-91343a03ec8f.png)

**Comment by corecache** [comment]
You don't need to change code to import CA's.

**Comment by qweqweq** [comment]
@corecache  actually , i don't know how to fix it with this error.
![image](https://cloud.githubusercontent.com/assets/10056390/19512296/c3b05c34-961d-11e6-9935-3e35543923e0.png)

**Comment by corecache** [comment]
Sorry mate, can't held your hand through all this stuff.

Here is a similiar issue and probably a solution for your certificate issue: #919

**Comment by qweqweq** [comment]
thank you very much @corecache

**Comment by anvay452** [comment]
@qweqweq  , hi , i am having same issue , did you find any solution ?

**Comment by allenzhang5208** [comment]
@qweqweq Hi， i am having same issue yet, did you find any soltion? If you find a solution, please let me know，thanks！

**Comment by Xqua** [comment]
Hi, 

We are using a valid let's encrypt certificate, yet we are seeing this message
I have tried to add the `NODE_TLS_REJECT_UNAUTHORIZED=0` but it does not work.

**Comment by Xqua** [comment]
Actually I just solved this problem !

So, the issue was that we are using LetsEncrypt to generate our certificates ! And you HAVE TO use the fullchain.pem and not the cert.pem ! 

So if anyone above was using letsecnrypt that is the issue, if not, then the issue comes from the fact that nodeJS tries to validate your certificate, if this certificate is not issued by a valid CA you have to make it a FullChain so that it gets validated !

Voila !
