### ISSUE TITLE
Has anyone tried "embedding" a version of this into another meteor app?

### ISSUE THREAD

**Issue by Orbyt** [RocketChat/Rocket.Chat#45]
So you could use a smaller version inside other templates. Anyone tried this?
##

**Comment by engelgabriel** [comment]
It is not that easy to do this yet. We are restructuring to make it into a Meteor packedge, so you will be able to do
```meteor add rockectchat:core```

**Comment by engelgabriel** [comment]
We started to move things into the main rocketchat:lib package

**Comment by engelgabriel** [comment]
We decided to go another direction, where people add Rocket.Chat as a IFRAME and control it via APIs, so I think we should close this issue.
