### ISSUE TITLE
Permissions don't save on restart of Rocket.Chat Service

### ISSUE THREAD

**Issue by jtbrush56** [RocketChat/Rocket.Chat#4500]
Rocket.Chat version: 0.41.0
Database Migration: 63

Permission changes do not persist between restarts of Rocket.Chat service. They are active once the check box is checked, but on a restart, the permissions reset to the original values.

**Comment by MartinSchoeler** [comment]
@jtbrush56 is this still happening on the latest release?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates. If you experience this issue again, feel free to reopen this. Thanks!
