### ISSUE TITLE
Piwik issue

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#4501]
Your Rocket.Chat version: 0.41.0

The console shows:
`piwik.js:6 Uncaught Error: A siteId must be given to add a new tracker`

Screenshot:
![](https://k0nsl.img-cdn.ru/chrome_2016-09-30_16-41-10.png)

Of course, the `siteId` is correctly entered in the options and the corresponding entry exists on piwik end.

**Comment by graywolf336** [comment]
When did this start?

**Comment by OmarTrigui** [comment]
I'm also facing this problem on my Angular web app.
Affected Piwik version : 2.16.5

**Comment by k0nsl** [comment]
@graywolf336: I do not know but my guess is that it started with version `0.40.0`.

**Comment by jaredhilton** [comment]
@k0nsl, I'm trying to investigate this issue. Can you tell me what you were doing when you noticed this error in console?

**Comment by k0nsl** [comment]
@jaredhilton: I do not recall exactly what I were doing, but I imagine that I added the pertinent piwik settings to Rocket.Chat, then reloaded the browser and looked at the console output.
At any rate, in `0.51.0` (yes, I know that `0.52.0` is current) the issue seems to be fixed as I cannot replicate this issue.

So if there is nothing else to be added, I believe this issue can be closed and marked as solved.

**Comment by jaredhilton** [comment]
@K0nsl thanks for following up!

@marceloschmidt @bradleyhilton this item can be closed per.

**Comment by ShakedBu** [comment]
I have this issue with piwik 2.17
