### ISSUE TITLE
Administration - Custom Emoji window is blank.

### ISSUE THREAD

**Issue by goobersmooch** [RocketChat/Rocket.Chat#4503]
Rocket.Chat server version: 0.41.0
Client: macOS 10.11.6

When clicking on administration and then the custom emoji section, the window is blank. The only way i can resolve it is to quit the rocket.chat app and then reopen it. Once it reopens i can add custom emojis like normal. Note: When the custom emoji window is blank, i can still click on other items like View logs and Info and the windows display their information. It is only the Custom emoji window that seems to hang up.

![screen shot 2016-09-30 at 11 12 47 am](https://cloud.githubusercontent.com/assets/15216195/18998791/bce7b302-86ff-11e6-99a4-e2cd08996a68.png)

**Comment by engelgabriel** [comment]
I believe this was fixed. Please reopen is the problem persist after version 0.48.2
