### ISSUE TITLE
Recent conversations

### ISSUE THREAD

**Issue by felipegasparini** [RocketChat/Rocket.Chat#4504]
I want to propose a feature, ignore it if you don't find it useful for everyone. =)

Right now we have the following categories on the side menu: Favorites, Channels and Direct Messages.
IMO a new category called "Recent conversions" that displays the most recent N conversations would be great. It is something that I missed in Slack, in Rocket chat and in any other chat that I tried.

The reason I think this is very useful is because very often I have too many open conversations and is really hard to keep track of these conversations.

For this feature, I don't think that some fancy solution involving the server would be needed (but it would be nice to have the "Recent conversations" shared across devices). A simple LRU of notifications that the client manages (aka client side) would work (just keep a capped list of conversations, and keep in the head the most recent notification).

**Comment by felipegasparini** [comment]
Maybe it is not needed at all.

The ctrl+P already displays the channels with unread messages and recent messages! 

GJ and sorry for not noticing it before!

**Comment by NioTeX** [comment]
👍  I really find this featureusefull in Skype. Sometimes somebody writes a question but while I am answering I get interrupted by a more urgent message. After finishing the urgent issue I forget who I was talking to and what conversations I may have left unresolved.

**Comment by jtbrush56** [comment]
I agree, this would be very useful for us as well. It has been requested by members of our team several times.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Folks, you know that there is the `Sort by activity` setting in your preferences, right? Dunno if that's been there  back in 2016 (I guess not), but that's the way to go here :)

![image](https://user-images.githubusercontent.com/179595/36224914-4182fcc0-11c9-11e8-916e-da6479a98100.png)

If anyone doesn't agree with the close, please get back to me! :)

Cheers
Thomas
