### ISSUE TITLE
Rocket Chat windows download compromised ??

### ISSUE THREAD

**Issue by admin-crowd-iugo** [RocketChat/Rocket.Chat#4505]
I tried redownloading rocket chat this morning and microsoft security essentials flagged it as Trojan: Win32/Varpes.M!cl
This is the windows rocket chat client. 
Has the download site been compromised ?
Thanks.

**Comment by k0nsl** [comment]
That is a so-called "false positive". You can add an exclusion.

**Comment by h22a** [comment]
Definitely a false positive. I have uploaded the executable to Virus Total and it seems just fine, as expected. You can check the results below:
[VirusTotal - Rocket.Chat .exe](https://virustotal.com/en/file/cc5064bcecf34b92a8c58c8855baa74fa9392adeafdc6ef01a1774eecdf610e4/analysis/1475652310/)

**Comment by pards** [comment]
Symantec Endpoint Protection still flags this as a virus and prevents it from running.

**Comment by geekgonecrazy** [comment]
I believe this is now resolved with newer releases.  Please open an issue here: https://github.com/rocketchat/rocket.chat.electron/issues if not
