### ISSUE TITLE
Download protected files doesn't work from client unless you're logged in via browser

### ISSUE THREAD

**Issue by bighair** [RocketChat/Rocket.Chat#4516]
Your Rocket.Chat version: 0.39.0 / Manual installation on CentOS / NGINX web server

I'm experiencing a problem whereby file downloads from the desktop client app (either OSX or Windows) don't work when I have 'Protect uploaded files' enabled and I'm not logged into RC via a browser.

Specifically, I get a 'Forbidden' message pop up in the browser unless I'm logged in. If I'm logged in the file successfully downloads. This is the case in either Chrome or FF.

Any help would be greatly appreciated.

**Comment by alexandrezia** [comment]
This is a client issue (Desktop App), and there is already an existent issue:
https://github.com/RocketChat/Rocket.Chat.Electron/issues/227

**Comment by MartinSchoeler** [comment]
as @alexandrezia said this is a duplicate
