### ISSUE TITLE
Livechat add option: "Show queue list to all managers"

### ISSUE THREAD

**Issue by ulisesguerrero** [RocketChat/Rocket.Chat#4517]
Currently only the option "Show queue list to all agents" is available, there should be one more called "Show queue list to manager". 

This would be very useful when there is a bot agent doing the welcome and introductory conversation. A manager, could just monitor all bot's conversations and interact live when necessary.

**Comment by sampaiodiego** [comment]
Livechat managers can see it by default :wink:
