### ISSUE TITLE
Creating new kind of notifications

### ISSUE THREAD

**Issue by sboronska** [RocketChat/Rocket.Chat#4519]
Hello, 

I have an issue with notifications. I need distinctive notifications in my RC so I cannot use the default ones. Is is possible to create it using e.g. Materialize dialogs? And how can I do this?

Thanks.

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.
