### ISSUE TITLE
Dashboard for all incoming livechat and messages.

### ISSUE THREAD

**Issue by deep0892** [RocketChat/Rocket.Chat#4526]
Your Rocket.Chat version: (make sure you are running the latest)
Sorry but this not an issue but an additional feature.
If we can have a dashboard for all incoming chats and have feature for filter and all for manager or admin, it would be a great addon.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by JeroenAdam** [comment]
Can this be reopened? Similar feature request as https://github.com/RocketChat/Rocket.Chat/issues/4504
