### ISSUE TITLE
No mobile notifications

### ISSUE THREAD

**Issue by neimen** [RocketChat/Rocket.Chat#4527]
My Rocket.Chat version is 0.39.0 as this (as far as I know) is the latest version supported by Docker.

Whenever the server is trying to push a mobile notification, we receive this error message in the log, and no notification is received:

`I20161004-08:50:50.852(0) cordova.coffee:153 System ➔ error Error sending push to gateway (1 try) -> { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }`

The push notification settings are as following:
![skjermbilde 2016-10-04 kl 10 52 02](https://cloud.githubusercontent.com/assets/22317370/19067922/9d0ef026-8a20-11e6-8e1a-dbe303ae4311.png)

When sending "a test push to my user", it says the push was successful, however no notification is received, and the same error message shows up in the log.

Any tips/headers? 

Thank you! :)

**Comment by neimen** [comment]
Update: 
I tried changing the address to https://gateway.rocket.chat as per #4515 - no change.

**Comment by TheReal1604** [comment]
@neimen have your restarted your instance after that change?

**Comment by graywolf336** [comment]
@neimen Have you restarted your instance after changing that value as @TheReal1604 said?

**Comment by neimen** [comment]
@TheReal1604 @graywolf336 Yes, I tried restarting, and saw no change at all unfortunately. This is the current error message:

`cordova.coffee:153 System ➔ error Error sending push to gateway (2 try) -> { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' } `

**Comment by Sonoma95SS** [comment]
I am getting the same errors, was hoping to go live tomorrow morning but it doesn't look promising. This is my last hurdle.

`[34mI20161010-01:47:53.860(0) Push: send message "@quas" via query { userId: 'ofEP6ac6gyHHQAcCP' } 
[34mI20161010-01:47:53.866(0) Push: send to token { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' } 
[34mI20161010-01:47:54.048(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:47:54.270(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (1 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:47:55.383(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (2 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:48:05.480(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:48:07.935(0) Push: send message "@quas" via query { userId: 'ofEP6ac6gyHHQAcCP' } 
[34mI20161010-01:48:07.939(0) Push: send to token { gcm: 'eLZir9p4tsM:APA91bFJnWUhREb_Fb-P08MOsGVBGLnNVpvf5cadTOBCHmQ7lPNauQJRHo71R_5NfrrH_JwbNV98T8OYkz-zZBMRA6gyliBQfa48vjltEHl1V0EcHxB28yTEAludr3i4QxqMm7uYLv7z' } 
[34mI20161010-01:48:08.072(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (0 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:48:08.280(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (1 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:48:09.410(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (2 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } 
[34mI20161010-01:48:19.522(0) cordova.coffee:153 [31mSystem ➔ error Error sending push to gateway (3 try) -> { [Error: tunneling socket could not be established, statusCode=400] code: 'ECONNRESET' } `

**Comment by geekgonecrazy** [comment]
Lets close in favor of #1602

If you're still having issues please try one of our support methods https://rocket.chat/docs/getting-support
