### ISSUE TITLE
Window doesn't close when creating new msg

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#4529]
Your Rocket.Chat version: 1.3.1 client and 0.41.0 server.

Click "+" in "Priv msg" -> choose user and click "Create" -> new message thread is created but side window doesn't close, I have to click "x" on the top of it.

System: windows 10, 7, OS X Sierra, Linux etc.

**Comment by MartinSchoeler** [comment]
Hey I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
