### ISSUE TITLE
disable enable force SSL through mongodb

### ISSUE THREAD

**Issue by lethargosapatheia** [RocketChat/Rocket.Chat#4534]
Your Rocket.Chat version: I don't have access to the web interface - must be the latest, I installed it less than a week ago.

Since I enabled force SSL, I can't access RocketChat anymore.
I've no idea where to find and disable SSL in mongodb. I've looked into the rocketchat_settings collection, but there was nothing. Any ideas how I can do it?

I know this might not be the please to ask such questions, but I'm not sure where to turn to.

**Comment by lucasvanhalst** [comment]
It should be in the database with id Force_SSL
![](https://i.imgur.com/Sojuxzn.png)

**Comment by geekgonecrazy** [comment]
just to follow up here it would be: `db.rocketchat_settings.update({_id:"Force_SSL"}, {$set: {value: false}})`

**Comment by karlosgaldino** [comment]
O comando acima não funcionou no meu banco. Uso a versão mais novo. Tive a infelicidade de ativar está opção e agora o sistema não inicia. Ainda há alguém que possa ajudar ?
